### ISSUE TITLE
Strange Steam Windows leftover after switching KVM back to desktop

### ISSUE THREAD

**Issue by dkowis** [ValveSoftware/steam-for-linux#10010]
#### Your system information

* Steam Version:  1690583737
* Steam Client Build Date:  Fri, Jul 28 13:44 UTC -06:00
* Steam Web Build Date:  Fri, Jul 28 17:21 UTC -06:00
* Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu):  PopOS
* Opted into Steam client beta?:  No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12434089/steam-logs.tar.gz)
* GPU: Nvidia 3080Ti

#### Please describe your issue in as much detail as possible:
I expect the steam windows to stay "closed" or hidden or whatever, but instead I come back to this:
![SteamWindows](https://github.com/ValveSoftware/steam-for-linux/assets/28048/5410219e-61b1-4961-be80-4a6998e78772)

For some reason, every time, if steam is left running, and I lock my computer, and then switch to the work computer via KVM (I have a level1Techs KVM), when I return I'm greeted with a myriad of steam windows that I cannot close.

I went to get the steam client version by clicking on the item in the tray and Library and all the windows closed, except one:
![Clicked On Library](https://github.com/ValveSoftware/steam-for-linux/assets/28048/cc4cc923-990e-466a-9da9-550677a1a174)

Never saw this before the "new" steam version came out recently.

#### Steps for reproducing this issue:

1. Start up steam
2. Lock desktop
3. Switch KVM to another computer
4. Come back to this computer after using other computer for a day
5. See all the windows
6. Only way to get rid of all the windows is to Exit steam from the system tray, and start it again.

**Comment by kisak-valve** [comment]
Hello @dkowis, this issue is already being tracked at #9786. Closing as a duplicate.

**Comment by dkowis** [comment]
> Hello @dkowis, this issue is already being tracked at #9786. Closing as a duplicate.

Ah! I searched for it, but didn't use enough of the right words. Thanks! and sorry for the duplicate!
