### ISSUE TITLE
Team Fortress 2 Failing to launch on Arch Linux; possible fault in init script.

### ISSUE THREAD

**Issue by LargeOunce** [ValveSoftware/steam-for-linux#10029]
#### Your system information
Computer Information:
Manufacturer: ASRock
Model: B450M Pro4
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4426 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.4.12-arch1-1
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: i3
Steam Runtime Version: steam-runtime_0.20230606.51628
Video Card:
Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.52, 6.4.12-arch1-1)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.6-arch1.4
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73df
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3440 x 1440
Primary Display Size: 31.50" x 13.19" (34.13" diag), 80.0cm x 33.5cm (86.7cm diag)
Primary VRAM: 12288 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 15921 Mb
VR Hardware:
Headset: HTC Vive MV (lighthouse)
Base station or sensor: HTC HTC V2-XD/XE (lighthouse)
Base station or sensor: HTC HTC V2-XD/XE (lighthouse)
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 119110 MB
Largest Free Hard Disk Block: 25393 MB
Storage:
Number of SSDs: 3
SSD sizes: 1000G,1000G,128G
Number of HDDs: 0
Number of removable drives: 0

github gist link for steam runtime system information

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12477864/steam-logs.tar.gz)

* Steam client version (build number or date): 1.0.0.78-1 (according to pacman)
* Distribution (e.g. Ubuntu): Arch(labs) linux 6.4.12-arch1-1
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12477840/steam-logs.tar.gz)`]
* GPU: AMD ATI Radeon RX 6700 XT
#### Please describe your issue in as much detail as possible:
So yesterday/today morning. I was playing Team Fortress 2 no problem. Today, after a yay -Syu Team Fortress 2 no longer launches at all and immediately quits. I have verified my game files multiple times. 

I launched steam through the terminal and this is the output.
/bin/sh\0-c\0/home/brendan/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/brendan/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/hdd1/SteamDirectory/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam\0
chdir "/hdd1/SteamDirectory/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 16335 != 16334, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brendan/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
src/tcmalloc.cc:278] Attempt to free invalid pointer 0xae9bad0
/hdd1/SteamDirectory/steamapps/common/Team Fortress 2/hl2.sh: line 72: 16337 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Uploaded AppInterfaceStats to Steam

I checked inside hl2.sh and ensured that gdb was installed and up to date since in the status 42 section it requires it. 

I have changed nothing about my system aside from running my yay -Syu --removemake as I normally do when I first get on.

#### Steps for reproducing this issue:

1. Have a fully up to date arch linux system (as of 16:59 GMT +1 30/08/2023)
2. Open steam
3. Launch TF2
4. TF2 doesn't launch, spits the above output into the terminal every time.

Other games work fine

**Comment by LargeOunce** [comment]
https://gist.github.com/LargeOunce/19164bfbd0a0ce88dc6c2b63c5977c51

Forgot to post steam runtime information in the gist in the post.

**Comment by kisak-valve** [comment]
Hello @LargeOunce, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/5043. Closing as a duplicate.
