### ISSUE TITLE
Default `steam.desktop` has BAD options causing it to close and open repeatedly

### ISSUE THREAD

**Issue by theofficialgman** [ValveSoftware/steam-for-linux#10026]
#### Your system information

* Steam client version (build number or date): Jun 21 2023 21:17:38
* Distribution (e.g. Ubuntu):  Ubuntu 23.10 KDE Plasma
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Primary AMD, Secondary Intel (connected monitor currently off)

#### Please describe your issue in as much detail as possible:
Running steam from the default .desktop file causes the GUI to open and close over and over and I can not use steam.

#### Steps for reproducing this issue:

1. Install steam which will have the the following BAD options in the .desktop file
```
PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true
```
2. Start Steam from the .desktop file
3. Observe that it opens and closes repeatedly

#### Cause

This issue is caused due to BAD options present in the .desktop file. Since my Primary GPU (discrete AMD GPU) is the one that is currently connected to my active monitor (as it should be), I WANT to run on the Default GPU. However Steam has decided to set its default .desktop file to NOT use the primary GPU. This causes Steam to want to use my Secondary GPU (monitor currently off so the GPU is not active, my intel CPU's iGPU). The result is Steam will open and shut over and over.

This should be corrected ASAP to `PrefersNonDefaultGPU=false` or remove this option entirely. If you want to make it a configurable option, make it a configurable option, but this is BAD since it breaks for users who have normal setups (ie: anyone that has their monitor connected to their primary GPU).

**Comment by kisak-valve** [comment]
Hello @theofficialgman, this issue is already being tracked at #9383 / #9940. Closing as a duplicate.
