### ISSUE TITLE
Feature Request: Re add Ability to see precaching activity

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#10027]
Hey guys I wanted request the ability to see the activity of what game  shader cache processes in the background, which you used to be able to see when it was doing it and it would be great to be able to see this in big picture mode also. :smile: 

![image](https://github.com/ValveSoftware/steam-for-linux/assets/8393780/a7cd1e4b-83a4-483b-9a59-05551678a819)

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue is already being tracked at #9405. Closing as a duplicate.
