### ISSUE TITLE
Unable to restore game backups

### ISSUE THREAD

**Issue by gatenosix** [ValveSoftware/steam-for-linux#10028]
#### Your system information

* Steam client version (build number or date): Thu, Aug 24 9:51 PM UTC -08:00
* Distribution (e.g. Ubuntu): EndeavourOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
On a fresh install of EndeavourOS, I am unable to restore game backups.
When attempting to browse for the backup folder, it is impossible to get any further than the 'Backup destination' window, which is blank.

#### Steps for reproducing this issue:

1. Select Steam ->Restore Game Backup -> Browse...
2. The Backup Destination window does not list any files, folders, etc. making it impossible to restore a game backup.

I have tested with the Beta client as well as the stable client, and both produce the same issue.

Screenshot of the issue:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/6661236/cf981f8d-8e13-4d0b-8f8a-d149f1d90ea3)

**Comment by kisak-valve** [comment]
Hello @gatenosix, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

My understanding is that the Steam client should be calling xdg-desktop-portal here, and if that fails, then this fallback method appears.

Previously mentioned at https://github.com/ValveSoftware/steam-for-linux/issues/4003#issuecomment-1664693525.

**Comment by gatenosix** [comment]
Hi @kisak-valve  - here is the contents of Steam Runtime Diagnostics:

https://gist.github.com/gatenosix/b0238b3089c40d7593b570b47dbb5a99

**Comment by kisak-valve** [comment]
Thanks, https://gist.github.com/gatenosix/b0238b3089c40d7593b570b47dbb5a99#file-gistfile1-txt-L3629-L3673 is the section to focus on. xdg-desktop-portal is not installed / usable.

This could be considered a distro packaging issue: https://bugs.archlinux.org/task/78625

https://wiki.archlinux.org/title/XDG_Desktop_Portal would be worth reading.

**Comment by gatenosix** [comment]
Thanks! That did the trick.

**Comment by AungKoKoLin1997** [comment]
@kisak-valve 

I am facing the same problem in ubuntu 22.04 and I see only installation destination screen and can't choose folder.
I installed [xdg-desktop-portal-gtk](https://archlinux.org/packages/?name=xdg-desktop-portal-gtk).

And I only see this error>
"The 'version' property is not available for 'org.freedesktop.portal.ScreenCast', either there isn't a working xdg-desktop-portal or it is a very old version",

I think this error should not impact file chooser. Can you please help me how to fix the problem?

**Comment by mchdga** [comment]
I'm getting the same as AungKoKoLin1997

i asked chatGPT what to do.... GPT recommended to add a profile for lsof in /var/lib/snapd/apparmor/profiles/snap.steam.steam - but that did nothing.... i don't know...

**Comment by 00xBAD** [comment]
Seriously guys i don't know what i did, but after messing up reinstalling xdg-desktop-portal, after some trial and error it works now... 

#9775 This is the same issue, and helped me...

EndeavourOS 64bit - xfce4 - Steam Native
