### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by QueDemais** [ValveSoftware/steam-for-linux#10023]
Hello, the link that is offered to download steam.deb is not working
https://github.com/ValveSoftware/steam-for-linux

Also wanted to ask, is there another official way to download steam that valve supports, .deb flatpak snap rpm etc?
Is there another distribution that steam recommends besides Ubuntu with Kde etc?

**Comment by kisak-valve** [comment]
Hello @QueDemais, http://media.steampowered.com/client/installer/steam.deb works here in quick test. There's an alternative url at https://store.steampowered.com/about/ or https://repo.steampowered.com/steam/. Those should all point to the same .deb style distro package.

In terms of official support, the most recent Ubuntu LTS release is the only recommendation. That said, many people have success with using Steam on other distros with the distro-provided packaging.

**Comment by QueDemais** [comment]
Ok, thank you very much Kisak, success for you there 👍😄
