### ISSUE TITLE
Steam won't start after Flatpak update

### ISSUE THREAD

**Issue by ritchierope** [ValveSoftware/steam-for-linux#10034]
#### Your system information

* Steam client version (build number or date): 1.0.078
* Flatpak version: Flatpak 1.6.5
* Distribution (e.g. Ubuntu): Ubuntu 20.04.6
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

* GPU: Intel Corporation Device 9bc8 (rev 03)

#### Please describe your issue in as much detail as possible:
After doing a flatpak update via 'flatpak update', Steam won't start anymore. I removed Steam, reinstalled it, ran 'flatpak update' several times, none of this helped. When starting Steam via Terminal, I get the following error:

bwrap: Can't mkdir parents for /app/lib/debug/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256

#### Steps for reproducing this issue:

1.  Start the application: flatpak run com.valvesoftware.Steam

**Comment by kisak-valve** [comment]
Hello @ritchierope, this reads like a Flatpak issue before Steam starts that should be reported to the Flatpak devs or https://github.com/flathub/com.valvesoftware.Steam/issues.
