### ISSUE TITLE
Launching Steam with -silent still shows "Loading User Data" Splash Screen

### ISSUE THREAD

**Issue by ChaosBlades** [ValveSoftware/steam-for-linux#10031]
#### Your system information

* Steam client version: 1690583737 (Fri, Jul 28 2:44 PM UTC -05:00)
* Distribution: Pop!_OS 22.04 LTS x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Should not be needed
* GPU: AMD

#### Please describe your issue in as much detail as possible:
If I open terminal and launch steam with `steam -silent` it still produces a splash screen stating "Loading User Data". The silent argument by its typical description should launch steam completely without any GUI being presented except for the tray icon.

This became an issue with the recent Steam GUI refresh.

This is especially annoying when using tiling window managers which will cut the screen in half and make this splash screen the active window until it closes. Usually as soon as my computer starts I open an application like a web browser or terminal and start typing. This splash screen interrupts me mid sentence since it becomes the active window.

![Screenshot from 2023-08-30 21-06-33](https://github.com/ValveSoftware/steam-for-linux/assets/7530545/854622dd-756c-4871-b19c-69375e3e661d)

**Comment by JohnTheCoolingFan** [comment]
Looks like this is the same issue as #9382, which got closed but clearly is still present. Just saying for the record.

**Comment by ChaosBlades** [comment]
> Looks like this is the same issue as #9382, which got closed but clearly is still present. Just saying for the record.

It is not the same issue technically speaking. It was completely getting ignored before. Would even present the full GUI when fully launched. Looks like the original issue poster closed that issue not a Valve employee possibly concluding that it not showing the full GUI when loading finished was "fixed". Which I suppose is technically true.

**Comment by SunYu2004** [comment]
Same problem. My distro is Arch Linux.

**Comment by wtfiwinomgs** [comment]
this happening on windows too.. even with -silent -vgui doesn't work

**Comment by Sollace** [comment]
Reporting the same on Manjaro. Tried with  -silent -minimized -vgui -nofriendsui and everything else is hidden but the splash screen.

Will also add that enabling "Run steam at startup" inside the client does not append -silent to the startup action, and there appears to be no option to turn that on specifically so the only way to have it not show the full UI is to edit the action (or use the registry editor when on windows)

**Comment by ChaosBlades** [comment]
> Will also add that enabling "Run steam at startup" inside the client does not append -silent to the startup action, and there appears to be no option to turn that on specifically so the only way to have it not show the full UI is to edit the action (or use the registry editor when on windows)

Has been an issue for 5 years. Check my comment on that issue thread for the work around.

https://github.com/ValveSoftware/steam-for-linux/issues/5806#issuecomment-1096027594

**Comment by Sollace** [comment]
> > Will also add that enabling "Run steam at startup" inside the client does not append -silent to the startup action, and there appears to be no option to turn that on specifically so the only way to have it not show the full UI is to edit the action (or use the registry editor when on windows)
> 
> Has been an issue for 5 years. Check my comment on that issue thread for the work around.
> 
> [#5806 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/5806#issuecomment-1096027594)

Unfortunately that proporsed solution is not going to work as it doesn't do anything get around the core issue, which is that -silent doesn't work.

**Comment by Blood-Pirouette** [comment]
Any solutions yet? This is a really annoying bug. It gets in the way of third-party apps trying to open games to fullscreen, it gets in the way of windows managers, it looks ugly on boot and steals focus. And it serves no purpose, it tells the user nothing important. It completely ignores the intended purpose of the command argument -silent by not starting silently.

**Comment by markpendlebury** [comment]
Just adding my support to hopefully bring visibility to this issue. I'm in the same boat as the OP where i'm using a tiling window manager and launching steam seriously messes up my arrangements. This does seem like one of those simple fixes that valve will potentailly ignore however...

please give us a client switch --no-splash or similar

**Comment by janvkn** [comment]
To everyone who's been banging their head against this, I just wanted to chime in to say that if you use KDE, you can force the Steam client to bend to your will with a kwin window rule. It's still an annoying bug, and this is not a fix for everyone, but at least some people can be helped with it.

Basically, you can create a kwin rule that prevents the "Sign in to Steam" window to steal focus, force it to start minimized, and prevent it from creating a taskbar entry. If you then create an autostart script with `steam -silent`. Steam launches completely silently to the system tray when you login to your desktop and other Steam functionality is not affected as far as I can tell.

Below is the export of my kwin window rule. You can just save it to a file with a `.kwinrule` extension and then import it from `System Settings -> Window Management -> Window Rules -> Import...`

````
[steam splash screen bs]
Description=steam splash screen bs
below=true
belowrule=3
clientmachine=localhost
fsplevel=3
fsplevelrule=2
minimize=true
minimizerule=2
skiptaskbar=true
skiptaskbarrule=3
title=Sign in to Steam
titlematch=2
wmclass=steamwebhelper
wmclasscomplete=true
wmclassmatch=2
````

PS. bs stands for "boot silently", obviously ;)

**Comment by ChaosBlades** [comment]
The command is not `steam -silent`
It is `steam %U -silent`
Just rebooted several times. All I see now is the steam icon appear in the task tray. I searched high and low for what `%U` does but can't find it. It does not appear on any of the argument lists I could find. However it is in the .desktop file.

**Comment by Sollace** [comment]
> The command is not `steam -silent` It is `steam %U -silent` Just rebooted several times. All I see now is the steam icon appear in the task tray. I searched high and low for what `%U` does but can't find it. It does not appear on any of the argument lists I could find. However it is in the .desktop file.


`%U` isn't an argument. [It's a placeholder that your file manager will replace with a path asked to open a file with the program.](https://askubuntu.com/questions/1331125/in-a-desktop-file-what-is-the-u-variable)

That said, I did do some testing and it does look like the -silent argument is now fixed!
Nothing pops up when running just `steam -silent` in the terminal.
