### ISSUE TITLE
CS2 invite, massive download but cannot play new content (Linux/Mac)

### ISSUE THREAD

**Issue by g572staem** [ValveSoftware/steam-for-linux#10036]
Open CSGO, it presents something about CS2 invite. COOL!!  Or so I thought.
I downloaded something like 20GB of content for nothing playable... because I'm on Linux.
Here's another joker on Reddit saying the same, he's on Mac: https://www.reddit.com/r/GlobalOffensive/comments/167sdh4/help_no_option_to_play_cs2_after_invite_and/

Valve should add a simple test to their code: 
`if linux_or_mac then prompt_download_when_playable`

**Comment by kisak-valve** [comment]
Hello @g572staem, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3222 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3152 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3237.

Closing as a duplicate.
