### ISSUE TITLE
Steam chat doesn't input diacritics when entered using deadkey or compose key

### ISSUE THREAD

**Issue by UNF0RM4TT3D** [ValveSoftware/steam-for-linux#10043]
#### Your system information

* Steam client version (build number or date): 1693527575
* Distribution (e.g. Ubuntu): Arch Linux [KDE Plasma 5.27.7, Frameworks 5.109.0, Qt 5.15.10, Kernel 6.4.12-zen1-1-zen]
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12515579/steam-logs.tar.gz)
* GPU: AMD RX 6700 XT 12GB

#### Please describe your issue in as much detail as possible:
The steam chat window doesn't accept diacritics when using deadkey or compose key.
On a Czech keyboard it is possible to type ěščřžýžáíéůú (all of these work in steam chat) without using the deadkey, but I can't write ť, ď, ň these are always composed of a modifier and two keypresses (shift + ´ ˇ and t for example). These issues prevent me from forming a grammatically correct sentence.
Copying the character from another application works. There is also a [discussion topic on steamcommunity.com](https://steamcommunity.com/app/221410/discussions/0/6760518612021424403/), I attempted the suggested fix, but it didn't work. This seems to be a steam exclusive problem, any other application on my system doesn't have this issue regardless of X11 or Wayland.

#### Steps for reproducing this issue:

1. Open steam chat
2. Attempt to write a diacritic with a deadkey. Press shift + the ´ ˇ key and follow with with t, d, n.
3. Witness the nothing input into the chat window.
4. Write the same character in a different text window (not Steam).
5. Copy the character
6. Paste into Steam Chat
7. Witness the character being properly pasted and displayed.

**Comment by kisak-valve** [comment]
Hello @UNF0RM4TT3D, this issue is already being tracked at #9631. Closing as a duplicate.
