### ISSUE TITLE
Multiple blank windows spawned when monitor powered down

### ISSUE THREAD

**Issue by tailkinker** [ValveSoftware/steam-for-linux#10049]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): XUbuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD AMD RX 580

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When I turn off my monitor, Steam spawns fifteen to twenty blank windows that cannot be closed - attempting to close them just passes the click to the next window below.  I have to shut down Steam to get rid of them.

Expected behaviour:  This does not happen.

#### Steps for reproducing this issue:

1. Turn off monitor.
2. Turn monitor back on.

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12543705/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @tailkinker, this issue is already being tracked at #9786. Closing as a duplicate.
