### ISSUE TITLE
steam fails to initialize Vulkan for both native and Proton titles... follow up

### ISSUE THREAD

**Issue by leder11011** [ValveSoftware/steam-for-linux#10046]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1693527575
Steam Client Build Date:  Thu, Aug 31 11:03 PM UTC -08:00
Steam Web Build Date:  Thu, Aug 31 8:38 PM UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): ubuntu 22.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
actual error:
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!

expected:
games launch

#### Steps for reproducing this issue:

1. launch steam client
2. 
3.

**Comment by kisak-valve** [comment]
Hello @leder11011, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Thanks, at a glance, Vulkan is fine on your system, but the Steam-in-Snap packaging is breaking the Steam Linux Runtime - Sniper container environment which is used with Proton 8.0 and newer. (https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#snap-app-limitations)

Can you test how the .deb based Steam package behaves?

**Comment by leder11011** [comment]
Thank you for looking into this issue @kisak-valve . I used to have apt installation of steam client until the new GUI was established and old GUI via -vgui switch no longer worked. Cp. this isssue:
[https://github.com/ValveSoftware/steam-for-linux/issues/9769](9769)
With snap installation of steam client I got the new GUI running, but no games succeed to launch - neither native nor w/ Proton.

I will add the logs for your info. Please have a look!

**Comment by leder11011** [comment]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12568179/steam-logs.tar.gz)

**Comment by leder11011** [comment]
Bump @kisak-valve

**Comment by leder11011** [comment]
I deinstalled snap steam client and apt steam client is working now somehow - except for broken nVidia GPU rendering support!
