### ISSUE TITLE
i cant close steamplay help...

### ISSUE THREAD

**Issue by Henry194700** [ValveSoftware/steam-for-linux#10041]
#### Your system information

* Steam client version (build number or date): 1690583737 28th july friday
* Distribution: Ubuntu Mate 21.04.03
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [appinfo_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12506742/appinfo_log.txt)
* GPU: Nvidia

#### Problem:
i'd like to use steam with ony official linux based games (not like proton support)
but my steam client have bunch of problems for example i cant close Enable Steam Play For Supported titles i think its broken and i cant go to old steam ui i don't know what can i do, only steam support can help me...

#### Steps for reproducing this issue:

1. i clicked steam settings
2. i clicked steamplay
3. i cant close steamplay

**Comment by kisak-valve** [comment]
Hello @Henry194700, this issue is already being tracked at #9957. Closing as a duplicate.
