### ISSUE TITLE
Steam overlay shows wrong system time

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#10057]
#### Your system information

* Steam client version (build number or date): 1694456926
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12580777/steam-logs.tar.gz)

* GPU: Intel

#### Please describe your issue in as much detail as possible:
Steam Overlay shows wrong computer time. Local time shown by system(both desktop gui and `date` in terminal) is 12th september 01:19 while Steam overlay shows 11th september 22:19. As far as i can remember this started happening relatively recently and it used to be correct. 

![image](https://github.com/ValveSoftware/steam-for-linux/assets/42720874/6e5926c7-429a-4bb0-98c5-3857a9aee018)

**Comment by kisak-valve** [comment]
Hello @iodream, what timezone is the system configured to use? Maybe `timedatectl` in a terminal would have that.

**Comment by iodream** [comment]
```
[iod ~]$ timedatectl 
               Local time: вт 2023-09-12 01:56:04 EEST
           Universal time: пн 2023-09-11 22:56:04 UTC
                 RTC time: пн 2023-09-11 22:56:04
                Time zone: Europe/Kyiv (EEST, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by pacifi5t** [comment]
I have the same problem, here's `timedatectl` output:

```
               Local time: Thu 2023-10-05 01:52:56 EEST
           Universal time: Wed 2023-10-04 22:52:56 UTC
                 RTC time: Wed 2023-10-04 22:52:56
                Time zone: Europe/Kyiv (EEST, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Comment by Postnozet** [comment]
Temporary fix:
```
sudo timedatectl set-timezone Europe/Kiev
```

But this bug must be fixed on Steam side

**Comment by iodream** [comment]
I have not seen this bug for a long time now.  

Latest Steam beta 1711147596

**Comment by pacifi5t** [comment]
Yes, I the bug seems to be fixed.

**Comment by Postnozet** [comment]
Can confirm, bug has been fixed

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by jn64** [comment]
Still happening on regular Steam client 1747701111 on Fedora 41, not flatpak, not containerised.

```console
$ timedatectl 
               Local time: Thu 2025-06-19 14:27:15 +08
           Universal time: Thu 2025-06-19 06:27:15 UTC
                 RTC time: Thu 2025-06-19 06:27:15
                Time zone: Asia/Singapore (+08, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 36 Jul  2  2022 /etc/localtime -> ../usr/share/zoneinfo/Asia/Singapore
$ cat /etc/adjtime 
0.0 0 0.0
0
UTC
```

Both in-game overlay and Big Picture Mode show 06:27 (UTC) instead of 14:27.

All Steam logs use the correct local time.

**Comment by Husecelik70** [comment]
Help me. I can't withdraw my assets to my account. I can't unstake.iPhone’umdan gönderildijn64 ***@***.***> şunları yazdı (19 Haz 2025 09:51):﻿jn64 left a comment (ValveSoftware/steam-for-linux#10057)
Still happening on regular Steam client 1747701111 on Fedora 41, not flatpak, not containerised.
$ timedatectl 
               Local time: Thu 2025-06-19 14:27:15 +08
           Universal time: Thu 2025-06-19 06:27:15 UTC
                 RTC time: Thu 2025-06-19 06:27:15
                Time zone: Asia/Singapore (+08, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 36 Jul  2  2022 /etc/localtime -> ../usr/share/zoneinfo/Asia/Singapore
$ cat /etc/adjtime 
0.0 0 0.0
0
UTC
Both in-game overlay and Big Picture Mode show 06:27 (UTC) instead of 14:27.
All Steam logs use the correct local time.
