### ISSUE TITLE
Steam closes too early on gnome after executing gnome-session-quit

### ISSUE THREAD

**Issue by SnoutBug** [ValveSoftware/steam-for-linux#10069]
#### Your system information

* Steam client version (build number or date): 1694466342
* Distribution (e.g. Ubuntu): Fedora Linux 38
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
gnome-session-quit may call a popup to let the user confirm wether they want to shutdown the pc or not. Steam closes before the popup is shown. 

I expect steam to only close when I decide to confirm the popup, like any other app does.
#### Steps for reproducing this issue:

[Screencast from 2023-09-16 19-43-13.webm](https://github.com/ValveSoftware/steam-for-linux/assets/71790678/1d9f7f37-9df8-44b8-a4ee-9c3183b3e73e)

**Comment by kisak-valve** [comment]
Hello @SnoutBug, this issue is already being tracked at #4558. Closing as a duplicate.
