### ISSUE TITLE
[feature request] Vulkan shader processing "Skip" button on "Starting game" popup

### ISSUE THREAD

**Issue by GregTheMadMonk** [ValveSoftware/steam-for-linux#10064]
Hello!

Before the UI overhaul, on the "Starting game" popup there was a "Skip" button while processing Vulkan shaders. Now it is in the main Steam client. This results in worse user experience when, for example, launching games from the system tray, especially on slower machines where processing Vulkan shaders for some games can take a lot of tim.e

**Comment by kisak-valve** [comment]
Hello @GregTheMadMonk, this issue is already being tracked at #10032. Closing as a duplicate.

**Comment by GregTheMadMonk** [comment]
Oh, my bad. Thank you
