### ISSUE TITLE
Steam won't open from the system launcher, opens fine from the terminal

### ISSUE THREAD

**Issue by DarkArc** [ValveSoftware/steam-for-linux#10063]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Fedora KDE Spin (Wayland)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12602723/steam-logs.tar.gz)
* GPU: AMD 6700 XT

#### Please describe your issue in as much detail as possible:

When I launch steam from a terminal, it opens fine.

When I launch steam from Krunner, the main window is just a black rectangle that closes shortly thereafter. Occasionally, some other windows will initially open (e.g., the "Friends List" window).

#### Steps for reproducing this issue:

1. Open steam from Krunner

**Comment by kisak-valve** [comment]
Hello @DarkArc, this issue is already being tracked at #9383. Closing as a duplicate.

**Comment by DarkArc** [comment]
@kisak-valve I'm not using DRM_PRIME

**Comment by kisak-valve** [comment]
krunner is calling the desktop shortcut of Steam, which has `X-KDE-RunOnDiscreteGpu=true` and KDE among other things decides to set DRI_PRIME when it sees that.

**Comment by DarkArc** [comment]
Aha! Thank you so much, I removed the lines:

```
PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true
```

And that was sufficient to get things working again
