### ISSUE TITLE
how to skip crash upload? list of env vars?

### ISSUE THREAD

**Issue by colemickens** [ValveSoftware/steam-for-linux#10065]
Hi,

Sorry, I did look for an answer to this but didn't find it:

1. How can I disable crash log uploading? For example, I'm experimenting with HDR and gamescope... I doubt you want all these crash uploads, and I don't want to wait on the uploads to iterate.

2. Maybe there's an env var for this? Is there a list of env vars for controlling Steam-for-linux behavior by chance?

Thanks! Thanks x100 for all of Steam+linux efforts.

**Comment by kisak-valve** [comment]
Hello @colemickens, generally speaking disabling that sub-component is discouraged as it helps Valve devs prioritize crashing issues.

That written, you should be able to use ` steam -nominidumps -nobreakpad` as seen with Debian's distro-modified Steam packaging to do what you're asking for.
