### ISSUE TITLE
Lingering process after fully closing steam (steam-runtime-launcher-service)

### ISSUE THREAD

**Issue by 3331** [ValveSoftware/steam-for-linux#10060]
The process `steam-runtime-launcher-service` stays alive after fully closing steam.

```
user      329707  0.0  0.0   2740   276 ?        S    17:20   0:00 sh -c steam-runtime-launcher-service --alongside-steam
user      329711  0.0  0.0 251480  3824 ?        Sl   17:20   0:00  \_ steam-runtime-launcher-service --alongside-steam
```

**Comment by smcv** [comment]
This is meant to exit when its parent process does, but because Steam runs it via `sh -c`, its parent is actually the shell rather than Steam.

Please could a Steam developer set this up to be run either directly (not via a shell), or if the shell is necessary for some other reason, with `exec steam-runtime-launcher-service --alongside-steam`? That way, it should exit automatically.

**Comment by hustin-paul** [comment]
+1

Although my leftover process is not named `steam-runtime-launcher-service`.

After exiting steam or killing it by `killall steam` there is a leftover process (sometimes two) and I cannot reopen steam.

If I try to force kill the leftover process by `killall PID` or `kill -9 ...` the process refuses to shut down. Only option is to restart PC to be able to open Steam again.

**Comment by smcv** [comment]
@3331 wrote:
> The process steam-runtime-launcher-service stays alive after fully closing steam

This appears to have been a distro-dependent issue: it worked as intended in Arch and other distros where `/bin/sh` is bash (for example Fedora, although I have not verified that), but not in Debian-derived distros like Ubuntu, where `/bin/sh` is the smaller/simpler dash shell.

> Please could a Steam developer set this up to be run either directly (not via a shell), or if the shell is necessary for some other reason, with `exec steam-runtime-launcher-service --alongside-steam`? That way, it should exit automatically.

This change was made in or before Steam beta 1695334486, fixing this issue (I can no longer reproduce the problem on an Ubuntu 22.04 system while running the beta). It should propagate into the general-availability branch next time there is a big update from the beta branch.

A mitigation is that if you exit and re-run Steam, the leftover `steam-runtime-launcher-service --alongside-steam` process will be replaced by a new one, so there should be no more than one `steam-runtime-launcher-service --alongside-steam` process at any given time - this is a leak of one process per boot, not one process per Steam start.

@hustin-paul wrote:
> After exiting steam or killing it by killall steam there is a leftover process (sometimes two) and I cannot reopen steam.

I cannot reproduce this on my test systems, one of which *did* reproduce the lingering `steam-runtime-launcher-service` process. When I exit from Steam, all Steam processes exit within a few seconds (except for `steam-runtime-launcher-service` if I am running the non-beta branch on Debian/Ubuntu). Please open a separate issue with more details if you can still reproduce this.

**Comment by Conusoid** [comment]
Just noticed the same behavior on my Debian system. Though `killall steam-runtime-launcher-service ` helps to get rid of it, it's still a bit annoying, especially considering that Steam also leaves a significant amount of  some "u1000-*" labeled junk in the /dev/shm/, which also requires manual cleaning, but that’s another story.

**Comment by smcv** [comment]
This is already fixed in the beta branch. If this is sufficiently annoying to you, please [use the beta](https://help.steampowered.com/en/faqs/view/276C-85A0-C531-AFA3), and report any regressions as separate issues.

> a significant amount of some "u1000-*" labeled junk in the /dev/shm/

That's out of scope for this particular issue report.

**Comment by 3331** [comment]
This appears to be fixed
