### ISSUE TITLE
[Steam Client] Can't click on anything from the drop down menus.

### ISSUE THREAD

**Issue by iakovts** [ValveSoftware/steam-for-linux#10079]
#### Your system information

* Steam client version (build number or date):  1694466342
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Clicking on any item on dropdown menus in the library/store/etc other than the status bar on top does nothing. In fact, if an item exists (i.e. a link to the developer of a game) "behind" the dropdown menu, it gets clicked instead. 
Only way to access i.e. a game's properties is to go through Big Picture Mode which tends to work. 
I've attached a (probably not so helpful) gif:
![what](https://github.com/ValveSoftware/steam-for-linux/assets/24913676/6bbf8f16-2849-4526-bad5-fb99eebb9696)

Also my [system information](https://gist.github.com/iakovts/5a9d3949ddd755f182f24852825088f0).

#### Steps for reproducing this issue:

1. Click on any item from the drop down menus for a game in your library (Try Properties for example). Nothing happens.

**Comment by kisak-valve** [comment]
Hello @iakovts, this issue is already being tracked at #9273. Closing as a duplicate.
