### ISSUE TITLE
Click through rightclick/context menu in steam library

### ISSUE THREAD

**Issue by Rika-TH** [ValveSoftware/steam-for-linux#10071]
#### Your system information

* Steam client version (build number or date): Mon, Sep 11 9:49 PM UTC -08:00
* Distribution (e.g. Ubuntu): Endeavour/Arch (KDE Plasma)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12641640/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:

right clicked a game on my list in the library to go into properties and change the compat tool, on occasion it would "click-through" skipping the context menu and clicking whatever was behind it eg other game, scroll bar etc am using 

#### Steps for reproducing this issue:

1. right click game in library
2. left click properties

**Comment by kisak-valve** [comment]
Hello @Rika-TH, this issue is already being tracked at #9273. Closing as a duplicate.
