### ISSUE TITLE
Steam Overlay disabled for Cyberpunk 2077, cannot enable. Cyberpunk 2077 also gets only Xbox contr in Linux, normal KBM in Windows

### ISSUE THREAD

**Issue by NLBen** [ValveSoftware/steam-for-linux#10087]
#### Your system information

* Steam client version (build number or date): 1695334486
* Distribution (e.g. Ubuntu): Ubuntu 22.04 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: - done and attached -
* GPU: AMD RX 6600 XT
* 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12708806/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
- Steam Overlay does attempt to launch for some reason with Cyberpunk 2077, but the setting for it is turned off and it's greyed out (cannot enable)  
- Not sure if linked, but Cyberpunk 2077 in Windows can be played with KB+M in Windows (Windows version has issues of its own though...), but in Linux (despite both Steam and my system telling me (correctly) there's no controller attached) CP2077 thinks I am playing with a controller. I made a note of it to CD Project Red and they're aware, but not sure anymore if it might be a problem with Steam. (Edit: I did disable SteamInput by the way)

#### Steps for reproducing this issue:

1.  Start Cyberpunk 2077 with the latest patch
2. Run into problems
3.

**Comment by kisak-valve** [comment]
Hello @NLBen, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1732596496.
