### ISSUE TITLE
Strange folder named 'n+'$'\f' present in .steam/steam/ folder. 

### ISSUE THREAD

**Issue by mbcraft** [ValveSoftware/steam-for-linux#10089]
#### Your system information

* Steam client version (build number or date): 1694466342
* Distribution (e.g. Ubuntu): Linux Mint 21
* Opted into Steam client beta?: I don't know, it doesn't seem a beta since it's not written 'beta' into Steam informations
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12727895/steam-logs.tar.gz)`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I went into a steam internal folder, and i found a folder with a weird name. I was not expecting to find a folder with such a name and i thought it was probably en error in the code that created it with that name.

#### Steps for reproducing this issue:

1. Go into your home folder
2. Then go into .steam/steam/ folder
3. You'll find a folder named 'n+'$'\f' that looks like an error from bad code. I think that a steam folder should not have a name like this.

**Comment by kisak-valve** [comment]
Hello @mbcraft, can you check how old this folder is, and if it's not recently created, then does it reappear if you remove it and restart Steam?

**Comment by kisak-valve** [comment]
Closing pending feedback.
