### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by webmaster-exit-1** [ValveSoftware/steam-for-linux#10095]
![image](https://github.com/ValveSoftware/steam-for-linux/assets/98633966/13bb208e-2e74-4978-a8ba-1f8694e332f1)

**Comment by kisak-valve** [comment]
Hello @webmaster-exit-1, http://media.steampowered.com/client/installer/steam.deb works here in quick test. There's an alternative url at https://store.steampowered.com/about/ or https://repo.steampowered.com/steam/. Those should all point to the same .deb style distro package.

There's something more subtle going on here than a summary dead link.
