### ISSUE TITLE
Games not launching from NTFS filesystem, no error

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [ValveSoftware/steam-for-linux#10102]
#### Your system information

* Steam client version (build number or date): 
* Steam version according to "About" section: 1696019606
* 
* Distribution (e.g. Ubuntu): 
*     Garuda
* Opted into Steam client beta?: [Yes/No]
*No
* Have you checked for system updates?: [Yes/No]
*Yes 
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12775440/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD
* AMD RX6750XT

#### Please describe your issue in as much detail as possible:

Launching games from a Non-Linux filesystem (E.g. NTFS) Doesn't work or throw an error, it just does nothing. 
There should be some kind of error popup notifying the user that steam could not launch the game because it couldn't access/handle/use the filesystem provided.

#### Steps for reproducing this issue:

1. Install a game to a non-linux filesystem (E.g NTFS)
2. Try to launch it

**Comment by kisak-valve** [comment]
Hello @DisruptionSystemsINC, you're under-specifying that the issue you're seeing is with games run with Proton, not all games.

This issue is already being tracked at #8274. Closing as a duplicate.
