### ISSUE TITLE
Can't gather game logs.

### ISSUE THREAD

**Issue by jakubby2** [ValveSoftware/steam-for-linux#10100]
#### Your system information

* Steam client version (build number or date): 169019606
* Distribution (e.g. Ubuntu): Debian Testing
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Game launch options:
``DXVK_ASYNC=1 gamescope -w 1280 -h 720 -F fsr --sharpness 0 %command% &>~/log.log``
``DXVK_ASYNC=1 %command% &>~/log.log``

#### Steps for reproducing this issue:

1. Launch grim dawn with Proton 6/7, also tried non-valve affiliated Proton-GE.
2. The game crashes, want to investigate/provide logs of what happend.
3. Log file is 0Bytes.
4. Launch gamescope --prefer-output --help &> ~/log.log in terminal.
5. Stdout/stderr log gets logged. 

How can I redirect/find logs now?

**Comment by kisak-valve** [comment]
Hello @jakubby2, in general we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/466#issuecomment-1741762181.
