### ISSUE TITLE
CS2 and dota2 loading screen starts to flash between loading screen and desktop

### ISSUE THREAD

**Issue by lmalmstrom** [ValveSoftware/steam-for-linux#10104]
#### Your system information

* Steam client version (build number or date):  1696019606
* Distribution (e.g. Ubuntu): Nobara
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD 5700xt

#### Please describe your issue in as much detail as possible:
When starting dota2 or cs2 natively loading screen opens and after few seconds it starts to flash fast between loading screen and desktop. Process will not progress further. I have found only 2 games with this issue, others work fine. If I unplug my second monitor, the problem goes away.

**Comment by kisak-valve** [comment]
Hello @lmalmstrom, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2/issues/2482 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3268. Closing as a duplicate.
