### ISSUE TITLE
removing steam client via snap: runs forever

### ISSUE THREAD

**Issue by leder11011** [ValveSoftware/steam-for-linux#10108]
#### Your system information

* Steam client version (build number or date): latest snap version
* Distribution (e.g. Ubuntu): ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
`# snap remove steam`
runs forever at:
`Save data of snap "steam" in automatic snapshot set #8` 

#### Steps for reproducing this issue:

1. `# snap remove steam`
2. 
3. 

expected result:
steam is removed

actual result:
after interrupting the deinstallation, which runs forever, steam client snap is still installed

**Comment by kisak-valve** [comment]
Hello @leder11011, the behavior of the Snap utility should not be affected by any application packaged to run inside it. Report this issue to the Snap devs.

Closing as not a Steam client issue.
