### ISSUE TITLE
Feature Request - for: Steam application for Gnome (implement XDG background portal) 

### ISSUE THREAD

**Issue by herp1derp2** [ValveSoftware/steam-for-linux#10105]
#### Your system information

* Steam client version (build number or date):  
 Steam Version:  1696019606
 Steam Client Build Date:  Fri, Sep 29 23:23 UTC -08:00
 Steam Web Build Date:  Sat, Sep 30 02:10 UTC -08:00
 Steam API Version:  SteamClient020

* Distribution: 
 Arch, linux kernel 6.5.5-arch1-1

* Opted into Steam client beta?: [Yes/No] No 
* Have you checked for system updates?: [Yes/No] Yes  

#### Please describe your issue in as much detail as possible:

This is a feature request: 

Problem is on Gnome 45, there is no legacy system tray icon on Gnome, Gnome developers implemented "Background Apps" in their "Quick Settings" to display background running apps instead. 
So Steam application has no entry in that section when you close (minimize into tray) the application. 
Which causes issue to see/view if the Steam application is running in the background. 

**According to Gnome developers, you guys have to use the XDG background portal thingy into your application to solve this issue. 

So the request is to implement XDG background portal thingy into the Steam application.** 
 
_Please note that this does not cause issue to bring the Steam application forward again if it is running in background, you can "open" the application from the application menu or the dock and it will bring the application forward. Only problem is as described above. No visual indication of the program running in background._ 

#### Steps for reproducing this issue:

1. Arch linux
2. Official Steam application from official Repo. 
3. Close the application (not exit) 
4. You can see or rather don't see the Steam application in Gnome's "Background App" section on their Quick Settings. 

Thank you. 
Stay awesome!

**Comment by kisak-valve** [comment]
Hello @herp1derp2, this feature request is already being tracked at #9970.

Closing as a duplicate.

**Comment by herp1derp2** [comment]
>closed this as not planned 
Really sad to see. But thank you for the update. Cheers!

**Comment by kisak-valve** [comment]
The choice of wording is Githubs, with the tooltip that it's used with Won't fix, can't repro, duplicate, or stale.
