### ISSUE TITLE
Dropdown date or sort by in steam workshop clicks on the mod behind the option 

### ISSUE THREAD

**Issue by alphaomega325** [ValveSoftware/steam-for-linux#10118]
#### Your system information

* Steam client version (build number or date): 1696019606
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12838509/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD Nvidia

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When I dropdown the sort by or over time period and click on the setting the workshop pulls up the mod behind the option instead of sorting the workshop menu by the dropdown option.

#### Steps for reproducing this issue:

1. Enter workshop
2. Enter any category
3. Click on the Sort By or Over time period dropdown options
4. Click any option
5. Find you don't refresh the menu but instead is sent to the mod page behind the drop down

**Comment by kisak-valve** [comment]
Hello @alphaomega325, this issue is already being tracked at #9273. Closing as a duplicate.
