### ISSUE TITLE
Unable to drag games in LIBRARY in steam to add them to categorys. 

### ISSUE THREAD

**Issue by zooki2006** [ValveSoftware/steam-for-linux#10119]
#### Your system information

* Steam client version (build number or date): 1696019606
* Distribution (e.g. Ubuntu):arch 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12841182/steam-logs.tar.gz)]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I try to drag a item in the LIBRARY page on steam.
It doesn't show a image on my mouse of the game as it should instead it shows nothing, and I can't add the game I'm trying to drag to a category by dragging it. 

video demo:

https://github.com/ValveSoftware/steam-for-linux/assets/55743069/f094049f-60fb-4ba1-9a5a-3b9014e9fa03

#### Steps for reproducing this issue:

1. go onto the library page on the steam client
2. drag item in library
3. watch as it doesn't show the image of the game and doesn't let you add it to a category.

**Comment by AndreEckner** [comment]
I got the exact same problem. You just can't drag the items. This seems to be persistent over the last couple of ubuntu updates, so it doesn't seem to be a platform-specific quirk.

**Comment by EduFdezSoy** [comment]
can confirm on:

* Steam client version (build number or date): 1702079146
* Distribution (e.g. Ubuntu): pop-os
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13804808/steam-logs.tar.gz)
* GPU: AMD

**Comment by Hurlevent** [comment]
I think I'm facing the same issue on arch linux. I created a new collection, and tried to add games to it, but dragging and dropping doesn't seem to work at all.

**Comment by ErrantOverflow** [comment]
Yep, same here
[System information](https://gist.github.com/ErrantOverflow/aa18513b261de0a52402bf7a32a2524a)
System is fully updated

**Comment by zooki2006** [comment]
this issue was fixed for me in a resent update. will close this issue now unless other people still have the same problem.

**Comment by AndreEckner** [comment]
Can confirm, it's solved.
