### ISSUE TITLE
// webpage issue

### ISSUE THREAD

**Issue by Danielduel** [ValveSoftware/steam-for-linux#10113]
Where to post issues with steamcommunity.com?

My issue is that when in review you put a link in parentheses for example
`Something something (semver.com) something something`
The interpreter finds a `(semver.com)` as a link and tries to link this to `http://(semver.com)` instead of interpreting only the "content" - `semver.com` as a link.

Steps to reproduce:
https://steamcommunity.com/profiles/76561198023909718/recommended/620980/

@kisak-valve I know this is not the place for this issue, but it is the closest place that I know, could you move it if you will consider it worth to fix? And feel free to close this one, because it is out of scope in here.

**Comment by kisak-valve** [comment]
Hello @Danielduel, general Steam website issues should be reported to [Steam Support](https://help.steampowered.com).
