### ISSUE TITLE
`.desktop` files are not updated when a game details change

### ISSUE THREAD

**Issue by AFCMS** [ValveSoftware/steam-for-linux#10116]
#### Your system information

* Steam client version (build number or date): 1696541351
* Distribution: Fedora 38
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12838081/steam-logs.tar.gz)
* GPU: Nvidia RTX 4060 (laptop)

#### Please describe your issue in as much detail as possible:

I installed CS:GO several months ago. I made the CS2 update when CS2 launched, all details of the game changed in the steam client (game title, background, icon, etc).

The `.desktop` file created when I installed CS:GO works fine (since the game id hasn't changed), but still have the wrong title `Counter Strike: Global Offensive` instead of `Counter Strike 2` and the CS:GO icon (even after restarting the PC).

In the app:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/61794590/456ee3a1-72c7-43f0-b66e-0090bb20c602)

In the desktop app menu:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/61794590/85b69f0c-e4df-4510-a1ad-d3df948217b7)

#### Steps for reproducing this issue:

1. Install a game
2. Wait for the game to change its icon/title
3. See the Steam client show updated icon/title
4. See the `.desktop` file not updated

**Comment by spiffeeroo** [comment]
Valve never updated the desktop icon files for the Linux version of Counter-Strike 2. [SteamDB](https://steamdb.info/app/730/info/) still shows the old CS:GO icons for [_LinuxClientIcon_](https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/730/ff52d4cc462d49c0297b9bc0558b4ef4c3bdd9ae.zip). The Steam client downloads game icon files at installation time to _$STEAM_ROOT/steam/games/_ and creates various icon images at _/home/$USER/.local/share/icons/hicolor/*/apps/steam_icon_730.png_. Valve has to release an update to Counter-Strike 2.

**Comment by AFCMS** [comment]
Ohh, so not the steam client fault?

Is there an issue already opened in the CS2 bug tracker for this?

**Comment by AFCMS** [comment]
I opened one
