### ISSUE TITLE
Flatpak: System tray works but main window cannot open - it loops open-close-open-close

### ISSUE THREAD

**Issue by rybak** [ValveSoftware/steam-for-linux#10125]
#### Your system information

* Steam client version (build number or date): 
```
$ flatpak info com.valvesoftware.Steam

Steam - Launcher for the Steam software distribution service

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.78
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 35.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 4865d176e42fd233b38a6c40243f0d6abbe6d7549fc5c5e024eb0354a3834a43
      Parent: 124e023473a32629723ddbf5772b961ee59b61ed276c009bd7441e47cdda2464
     Subject: Fix typo in reference to 23.08-extra (3e5c5478)
        Date: 2023-09-06 14:50:13 +0000
```
* Distribution (e.g. Ubuntu): 
```
Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.2.0-34-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Dell Inc.
Product Name: Inspiron 5570
```
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs-2.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12851384/steam-logs-2.tar.gz)
* GPU: integrated Intel + discrete AMD

#### Please describe your issue in as much detail as possible:
When I try to open the Steam via application launcher (called Kickoff), i.e. via the `.desktop` file, the system tray icon and menu work, I can even launch games, but the actual Steam window is stuck in a loop of opening and closing, making games unplayable.

#### Steps for reproducing this issue:

1. Have Steam installed via Flatpak in KDE Neon.
2. Open Application Launcher (shortcut Alt+F1 or Meta)
3. Type "Steam" in the search OR go to Games > Steam
4. Click on "Steam"
5. Observe the main window

#### Workaround
- Launch without using GUI, through Bash:
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam com.valvesoftware.Steam
```

#### Notes
- People have been reporting this issue in reviews for a couple of weeks, it seems: [screenshot](https://github.com/ValveSoftware/steam-for-linux/assets/624072/1d8a668c-27ad-4fc2-90ec-8a797bdc11f0).
- I can't tell for sure, but this bug report seems very similar: https://github.com/flathub/com.valvesoftware.Steam/issues/1168

**Comment by kisak-valve** [comment]
Hello @rybak, this issue is already being tracked at #9383. Closing as a duplicate.
