### ISSUE TITLE
DOD:s No Longer Loads 

### ISSUE THREAD

**Issue by Kenjacques** [ValveSoftware/steam-for-linux#10126]
#### Your system information

* Steam Version:  1696019606
   Steam Client Build Date:  Fri, Sep 29 1:38 PM UTC -05:00
   Steam Web Build Date:  Fri, Sep 29 4:25 PM UTC -05:00
   Steam API Version:  SteamClient020
* System:
   Kernel: 6.2.0-34-generic x86_64 bits: 64 compiler: N/A Desktop: Xfce 4.18.1
     tk: Gtk 3.24.33 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 dm: LightDM 1.30.0
     Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: No logs are updated during this error
* Graphics:
   Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
     vendor: XFX Pine driver: amdgpu v: kernel pcie: speed: 16 GT/s lanes: 16
     ports: active: DP-3 empty: DP-1,DP-2,HDMI-A-1 bus-ID: 2b:00.0
     chip-ID: 1002:731f class-ID: 0300
   Display: x11 server: X.Org v: 1.21.1.4 compositor: xfwm v: 4.18.0 driver:
     X: loaded: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
     display-ID: :0.0 screens: 1
   Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.7x15.0")
     s-diag: 777mm (30.6")
   Monitor-1: DisplayPort-2 mapped: DP-3 model: Asus MG279 serial: <filter>
     res: 2560x1440 dpi: 109 size: 597x336mm (23.5x13.2") diag: 685mm (27")
     modes: max: 2560x1440 min: 720x400
   OpenGL:
     renderer: AMD Radeon RX 5700 (navi10 LLVM 16.0.6 DRM 3.49 6.2.0-34-generic)
     v: 4.6 Mesa 23.2.0-rc4 direct render: Yes

This game ran fine until a couple of Steam client updates back. Since then it behaves like a bugged Proton game. I would usually delete the local game files and Steam would repopulate them and that would fix the issue, but DOD:S is a native Linux game.  Deleting local files prompts the client to repopulate them, which it does successfully. However, the game fails to load. Attempting to run from the client just makes the play button momentarily turn blue, but then back to green. I've attempted complete reinstall with no success.

Initiating Steam from console, this is what I get when attempting to run DOD:S

/bin/sh\0-c\0/home/USERNAME/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=300 -- /home/USERNAME/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/USERNAME/.steam/debian-installation/steamapps/common/Day of Defeat Source/hl2.exe' -steam -game dod\0
chdir "/home/USERNAME/.steam/debian-installation/steamapps/common/Day of Defeat Source"
ERROR: ld.so: object '/home/USERNAME/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/USERNAME/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/USERNAME/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/USERNAME/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/USERNAME/.steam/debian-installation/steamapps/common/Day of Defeat Source/hl2.exe: 1: Syntax error: Unterminated quoted string
Uploaded AppInterfaceStats to Steam

**Comment by kisak-valve** [comment]
Hello @Kenjacques, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/5043. Closing as a duplicate.
