### ISSUE TITLE
Steamlink crashing on connection

### ISSUE THREAD

**Issue by Tr0lldr0id** [ValveSoftware/steam-for-linux#10123]
#### System information

* Steam client version (build number or date): Client: `steam-1.0.0.78-2`  Steamlink: `steamlink-1.2.0.241-1` (installed from AUR)
* Distribution (e.g. Ubuntu): EndeavourOS (Arch Linux derivative)
* Opted into Steam client beta?: pretty sure it's no
* Have you checked for system updates?: yes
* Steam Logs: Please advise - my issue is with the steam link package, not the steam client itself. Same logs, or different ones?
* GPU - Intel integrated graphics

#### Please describe your issue in as much detail as possible:
I'm trying to use remote play on my school laptop. I can connect to my main PC from my phone perfectly fine, but when I attempt to connect the laptop to the PC then I get a loading screen before the entire steam link program crashes completely.

Running the program from the terminal produces this output:
```INFO: Warning: Couldn't bind discovery port 27036
INFO: Hardware: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
INFO: Connected to Remote Client service with session 5310792855115288073
INFO: Starting Streaming
INFO: Received authorization proof request, responding with encrypted challenge
INFO: Received start streaming response k_ERemoteDeviceStreamingSuccess
INFO: Initializing player
INFO: Desktop mode: 1366x768
INFO: Refresh rate: 60.00
INFO: Effective rate: 59.75
INFO: Video rect: 0x0 at 0,0
INFO: Texture rect: 1366x768 at 0,0
INFO: Video size: 1366x768, output size: 1366x768, overlay size: 1366x768
INFO: Video rect: 1366x768 at 0,0
INFO: Texture rect: 1366x768 at 0,0
INFO: Video rect: 1366x768 at 0,0
INFO: Texture rect: 1366x768 at 0,0
INFO: Initialized player
INFO: Server available at address: 172.16.10.95:27031
INFO: Connecting to server at 172.16.10.95:27031 using direct UDP
INFO: Session state Idle -> Connecting
INFO: CStreamTransportClient stopping Remote Client service connection
INFO: Video size: 1366x768, output size: 1366x768, overlay size: 1366x768
INFO: Video rect: 1366x768 at 0,0
INFO: Texture rect: 1366x768 at 0,0
INFO: Video rect: 1366x768 at 0,0
INFO: Texture rect: 1366x768 at 0,0
INFO: Session state Connecting -> Handshake
INFO: Session state Handshake -> Authenticating
INFO: Got control packet k_EStreamControlServerHandshake
INFO: Session state Authenticating -> Negotiating
INFO: Got control packet k_EStreamControlAuthenticationResponse
INFO: Got control packet k_EStreamControlNegotiationInit
INFO: Session state Negotiating -> StreamStarting
INFO: Got control packet k_EStreamControlNegotiationSetConfig
INFO: Session state StreamStarting -> Streaming
INFO: Got control packet k_EStreamControlSetQoS
INFO: Got control packet k_EStreamControlSetTargetBitrate
INFO: Starting audio stream: frequency=48000, channels=2
INFO: Opened audio device: format=2, channels=2, frequency=48000
INFO: Initialized audio decoder: codec=3, sample rate=48000, channels=2
INFO: Got control packet k_EStreamControlStartAudioData
INFO: Got control packet k_EStreamControlSetSpectatorMode
INFO: Got control packet k_EStreamControlSetCaptureSize
INFO: Got control packet k_EStreamControlSetTitle
INFO: Got control packet k_EStreamControlSetIcon
INFO: Got control packet k_EStreamControlSetCursor
INFO: Got control packet k_EStreamControlSetKeymap
INFO: Got control packet k_EStreamControlSetActivity
INFO: Got control packet k_EStreamControlSetCursorImage
INFO: Got control packet k_EStreamControlStartVideoData
INFO: Got control packet k_EStreamControlVideoEncoderInfo
INFO: Got control packet k_EStreamControlVideoEncoderInfo
INFO: CVDPAUAccel: GL_NV_vdpau_interop not available on current context
INFO: ffmpeg verbose: Trying to use DRM render node for device 0.
INFO: ffmpeg verbose: libva: VA-API version 1.20.0
INFO: ffmpeg verbose: libva: Trying to open /usr/lib/dri/iHD_drv_video.so
INFO: ffmpeg verbose: libva: va_openDriver() returns -1
INFO: ffmpeg verbose: libva: Trying to open /usr/lib/dri/i965_drv_video.so
INFO: ffmpeg verbose: libva: va_openDriver() returns -1
INFO: ffmpeg error: Failed to initialise VAAPI connection: -1 (unknown libva error).
INFO: CVAAPIAccelDRM: av_hwdevice_ctx_create() failed: -5
/usr/bin/steamlink: line 2: 13354 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/opt/steamlink/lib /opt/steamlink/bin/steamlink $@
```

Steam Runtime Diagnostics info: https://gist.github.com/Tr0lldr0id/c9f35c55c372fd4436b3bac82c4bd386

#### Steps for reproducing this issue:

1. Open steamlink
2. click "connect" for my main PC

**Comment by kisak-valve** [comment]
Hello @Tr0lldr0id, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Tr0lldr0id** [comment]
Hello @kisak-valve, thanks for the direction. I've linked it in the OP as well but here's the link for your convenience. 
https://gist.github.com/Tr0lldr0id/c9f35c55c372fd4436b3bac82c4bd386

**Comment by kisak-valve** [comment]
Looking at your system information, https://gist.github.com/Tr0lldr0id/c9f35c55c372fd4436b3bac82c4bd386#file-gistfile1-txt-L1206-L1216 is the section to focus on. It looks like you don't have a working vaapi driver installed for your hardware. Maybe check if `lib32-libva-mesa-driver` system package is installed?

**Comment by Tr0lldr0id** [comment]
I've installed the driver package, but it's still crashing. Do you need a new diagnostic dump?

**Comment by Tr0lldr0id** [comment]
@kisak-valve please advise. Do I need to post a new copy of the Steam Runtime Diagnostics?

**Comment by kisak-valve** [comment]
The Steam Link App for Linux is a bit of an outlier and packaged for use in Flatpak which you can find at https://flathub.org/apps/com.valvesoftware.SteamLink. The AUR variant pulls it out of the steaming client's tested environment, so you're already off the beaten path.

I expect that 32 bit va-api is being used based on historic behavior in the Steam client, but that could be outdated or irrelevant with the Steam Link app. Since the initial suggestion I made didn't have an effect, I don't really have another quick test to try beyond rechecking the `"x11/vaapi"` sections of the Steam Runtime Diagnostics and adding any relevant system packages to get them healthier on your system in general. It wouldn't hurt to get both 32 bit and 64 bit va-api working for your hardware.

**Comment by Tr0lldr0id** [comment]
Wait... So if I install it through flatpak, I'll likely have better results and it will certainly be easier to support?

**Comment by Tr0lldr0id** [comment]
Having gotten the time to test this, I can confirm - the flatpak version runs just fine. First time the AUR has failed me, thanks @kisak-valve.
