### ISSUE TITLE
Is Valve even really supporting Linux anymore?

### ISSUE THREAD

**Issue by BlueGoliath** [ValveSoftware/steam-for-linux#10128]
Are you?

Steam's new desktop client still has memory leak problems many months after release.

This GitHub is full of bug reports that never seem to actually get addressed by anyone at Valve except one person in charge of janitorial work.

Now CS2 gets released and it both runs double the percentage points worse than the Windows DX11 renderer and doesn't have the ability to switch to the legacy CS:GO version like the Windows version can because someone decided to use a shell script instead of the normal Steam app launching mechanism.

Hilariously, A Valve employee left a comment with an absolute path containing their username in said launch script:

`/home/plagman/src/valve/Steam/main/client/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libdebuginfod.so.1)`

You have people who both use Linux and know Vulkan(what CS2 now uses on Linux, IIRC). Why is Linux's CS2 port so bad?

 Why is the support so abysmal? Has Valve decided to put Linux support on life support or what?

**Comment by kisak-valve** [comment]
Hello @BlueGoliath, there are various issue reports to track the specific issues you've mentioned and it's better to discuss those issues separately on the existing issue reports.

Yes, there are Valve developers doing ongoing work to support Steam on Linux.

**Comment by kisak-valve** [comment]
https://github.com/ValveSoftware/csgo-osx-linux/issues/3325 and https://github.com/ValveSoftware/csgo-osx-linux/issues/3291 disagrees with you.
