### ISSUE TITLE
Steam chat returns you to the desktop

### ISSUE THREAD

**Issue by crystaldaking** [ValveSoftware/steam-for-linux#10121]
#### Your system information

* Steam client version (build number or date): Latest Snap version
* Distribution (e.g. Ubuntu): Ubuntu (X11)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
If during the game I receive a new message in a dialog chat, then the game is turned onto the desktop

#### Steps for reproducing this issue:

1. Open some game (Dota2 in my case)
2. Ask a friend to write you a message
3. You get to the desktop

**Comment by kisak-valve** [comment]
Hello @crystaldaking, this issue is already being tracked at #5286. Closing as a duplicate.
