### ISSUE TITLE
Unable to launch CS2 CSGO legacy beta on Steam for Linux

### ISSUE THREAD

**Issue by eightyninetytwo** [ValveSoftware/steam-for-linux#10130]
#### Your system information

* Steam client version (build number or date): 1696019606
* Distribution (e.g. Ubuntu): Linux Mint 21.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12876320/steam-logs.tar.gz)

* GPU: NVIDIA GeForce GTX 1060 3GB

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After downloading the CS2 CSGO legacy beta, I should be able to pick between CSGO and CS2 when launching CS2, you are unable to do this as the menu does not appear, instead, CS2 just simply launches.

#### Steps for reproducing this issue:

1. Use Steam on a Linux distribution
2. Download CS2 beta "csgo_legacy - Legacy Version of CS:GO"
3. Once download is finished, attempt to launch by clicking "Play"
4. Menu to pick between CS2 and CSGO will not appear, CS2 launches instead

**Comment by kisak-valve** [comment]
Hello @eightyninetytwo, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3291. Closing as a duplicate.
