### ISSUE TITLE
Cannot open Steam window and play games (but system tray is okay)

### ISSUE THREAD

**Issue by guoyunhe** [ValveSoftware/steam-for-linux#10132]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:

After recent system update, I start Steam, it shows system tray icon, but Steam window is not opened. I cannot launch any games. Terminal shows some error messages about GTK 2:

```
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
```

#### Steps for reproducing this issue:

1. Install openSUSE Tumbleweed Linux
2. Install steam by `sudo zypper install steam`
3. Launch steam

**Comment by kisak-valve** [comment]
Hello @guoyunhe, can you check if any 32 bit OpenGL application like `glxinfo` from `Mesa-demo-x-32bit` works?

**Comment by guoyunhe** [comment]
@kisak-valve solved by delete and reinstall steam (opt out beta)
