### ISSUE TITLE
Gamescope issue on Gnome 44+ using X11

### ISSUE THREAD

**Issue by furai** [ValveSoftware/steam-for-linux#10146]
Hey,

So I'm currently on Gnome 45 using X11, it was also happening on Gnome 44.

Whenever I launch steam I get 2 modals one after another saying: ```wayland: skipping init because GAMESCOPE_WAYLAND_DISPLAY is not set```

![image](https://github.com/ValveSoftware/steam-for-linux/assets/2674689/67a2e164-f4a7-4971-adb6-bf48ea9ea4d9)

### System info:

* Steam client version: `1697508377`
* Distribution: `ArchLinux`
* Opted into Steam client beta?: `Yes`
* Have you checked for system updates?: `Yes`
* Steam Logs:  [steam-logs-20231017.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12924913/steam-logs-20231017.tar.gz)
* GPU: Nvidia

### Steps for reproducing this issue:

1. Use X11 session on Gnome.
2. Launch the steam client.

Cheers,
Furai

**Comment by licarite** [comment]
Exactly the same error message shows up for me on dwm with X11 on Artix. Steam launched from a terminal. The Steam window doesn't appear but tray icon is working.

**Comment by pointydev** [comment]
Can reproduce on Fedora 38 with KDE+X11, interestingly the error appears a second time after dismissing before I can proceed to the client. [System Information (Steam 1697843490)](https://cdn.discordapp.com/attachments/261531013027463178/1165461144799027220/steamsysteminfo-20231022.txt?ex=6546ef46&is=65347a46&hm=e23fcabb396ddc8907beafdcb2796f897c1915f3675e4eca4f30aa57262fbaed)

**Comment by furai** [comment]
Seems latest issue stopped the fatal error. Can still see warnings about it in dev console but that's OK I guess.

**Comment by kisak-valve** [comment]
Closing per the last comment.
