### ISSUE TITLE
[BETA] Big Picture sound cracked on Arch Linux with Pipewire

### ISSUE THREAD

**Issue by v38armageddon** [ValveSoftware/steam-for-linux#10147]
#### Your system information
* Steam client version (build number or date): 1697508377 (Tue, Oct 17, 3:34 AM UTC - 08:00)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12929945/steam-logs.tar.gz)
* GPU: Nvidia GeForce GTX 1050 Ti

#### Please describe your issue in as much detail as possible:
When opening the Big Picture mode, with Pipewire, when navigate through menus, the sounds like cracked. 

EDIT 1: After playing a game and close it, the sound become normal.

#### Steps for reproducing this issue:
1. Open Big Picture with Pipewire
2. Navigate through menus
3. Constat the issue

**Comment by isaboll1** [comment]
I am having the exact same issue with Steam. The issue seems isolated to Steam Big Picture mode and nothing else

**Comment by an9949an** [comment]
The same issue for me on fedora 38 (Intel UHD Graphics + rtx 3050 mobile, Steam from stable channel). Also whole big picture mode feels laggy.

**Comment by isaboll1** [comment]
as an update, downgrading pipewire fixed the issue for me. i'm now on version 0.3.62.2.dv sourced from SteamOS 3.0's repos. before I was on 0.3.82 when i had the issue.

**Comment by icculus** [comment]
I can’t reproduce this here so far. Maybe it was just a bleeding edge bug in PipeWire?

**Comment by aiudirog** [comment]
> I can’t reproduce this here so far. Maybe it was just a bleeding edge bug in PipeWire?

With today's upgrade from PipeWire 1:0.3.82-1 to 1:0.3.83-1 this issue went away for me, so definitely possible. I tested immediately before and after upgrading & rebooting.

**Comment by v38armageddon** [comment]
> With today's upgrade from PipeWire 1:0.3.82-1 to 1:0.3.83-1 this issue went away for me, so definitely possible. I tested immediately before and after upgrading & rebooting.

Can confirm, with the new update, the issue seem solved. However, not sure if it's resolved for everyone.

**Comment by hasezoey** [comment]
i also just had this problem (and had a new issue #10177), my pipewire version is 0.3.81, currently no (native package manager) upgrade available.

workaround is to go into steam settings, select a different audio output and then select back what it previously was, this workaround needs to be done every time steam is restarted.

another workaround i have noticed is when opening easyeffects and piping everything through there, just activating "bypass" and back also fixes steam sounds

PS: it also seems like it just affects steam, not games and not other applications

**Comment by lsahnicne** [comment]
Experiencing this as well. Pipewire version is 0.3.82

#### Your system information
* Steam client version (build number or date): 1698260427
* Distribution (e.g. Ubuntu): Pop!_OS 22.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13218199/steam-logs.tar.gz)
* GPU: AMD

**Comment by JackOfHertz** [comment]
I am still experiencing audio crackling after the pipewire 1.0.0 update (as well as for the past few years). Only Big Picture mode UI audio seems to be affected, game audio is not impacted. Crackling audio presents both when running Big Picture mode locally and when streaming to a Steam Link box or other Remote Play devices.

**Your system information**

    Steam client version: 1703100617 (built Wed, Dec 20)
    Distribution: EndeavourOS
    Kernel: 6.6.8-arch1-1
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes
    GPU: AMD Radeon 7900 XTX
    Pipewire: compiled with libpipewire 1.0.0

The workaround by @hasezoey still works for me:
> workaround is to go into steam settings, select a different audio output and then select back what it previously was, this workaround needs to be done every time steam is restarted.
