### ISSUE TITLE
steam desktop gui issue

### ISSUE THREAD

**Issue by kurokirasama** [ValveSoftware/steam-for-linux#10159]
#### Your system information

* Steam Version:  1696019606
* Steam Client Build Date:  Fri, Sep 29 14:38 UTC -04:00
* Steam Web Build Date:  Fri, Sep 29 17:25 UTC -04:00
* Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13073341/steam-logs.tar.gz)
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13073497/steam-logs.tar.gz)

* GPU: I have the issue in 2 machines:
* The first one:
* CPU: Intel i7-1065G7 (8) @ 3.900GHz
* GPU: Intel Iris Plus Graphics G7
* GPU: NVIDIA GeForce GTX 1050 3 GB Max-Q
* And the second one:
* CPU: AMD Ryzen 7 4800H with Radeon Grap 
* GPU: AMD ATI 05:00.0 Renoir 
* GPU: NVIDIA 01:00.0 NVIDIA Corporation 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

I cannot access the properties menu of any game. 
Check this video to watch the issue: https://yadi.sk/i/bDxE8vcppx2fjw
I already cleared cache and reinstalled steam.
I'm in ubuntu 20.04 in the latest steam version available.

On the second machine, I checked and it didn't have the problem. I updated the nvidia drivers to the 535 version and the problem appeared. I downgraded to version 525 (the I had) but the problem persist.

**Comment by kisak-valve** [comment]
Hello @kurokirasama, this issue is already being tracked at #9273. You might be able to workaround the issue by holding a modifier key like [CTRL] while selecting the menu item.

Closing as a duplicate.
