### ISSUE TITLE
[Feature request] 64-bit version of steam client with 32-bit libraries embedded in runtime

### ISSUE THREAD

**Issue by ShadowWarfare** [ValveSoftware/steam-for-linux#10154]
Could it be possible for Steam to have a 64-bit version of the Steam client on Linux with the 32-bit libraries embedded in that version for 32-bit games in a similar way to the snap package manager that Canonical's doing for Ubuntu?

32-bit seems to be slightly outdated now and those libraries could technically be embedded in the runtime for Steam when we download and install steam for the first time on the system. 

If possible could this be considered? Though I'm a bit pessimistic that it would be considered and be immediately closed as won't do.

**Comment by kisak-valve** [comment]
Hello @ShadowWarfare, a feature request for a purely 64 bit Steam client is already being tracked at #3518.

The Steam client already provides a base set of 32 bit libraries in the LD_* style Steam runtime, but it's not possible for that runtime to provide the 32 bit userspace for video drivers for all systems that use Steam.

Closing as a duplicate.
