### ISSUE TITLE
integrate discrete gpu confusion

### ISSUE THREAD

**Issue by lesar** [ValveSoftware/steam-for-linux#10158]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.78-1.fc38.src.rpm
* Distribution (e.g. Ubuntu): fedora 38
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* CPU: AMD Ryzen 9 7900X3D (24) @ 5.660GHz 
* GPU: AMD ATI Radeon RX 7900 XT/7900 XTX  (discrete)
* GPU: AMD ATI 19:00.0 Raphael (integrated not connected by cable to monitor)

#### Please describe your issue in as much detail as possible:
I have installed from fedora repo not Flatpak

#### Steps for reproducing this issue:

1. I have a integrated gpu and discrete gpu all AMD. in bios is primary gpu the discrete gpu.
2. I have cable connect only discrete gpu to my monitor
3. if I start steam by click on steam.desktop icon seams the app try to use integrate gpu and show black window that blink.
4. if I click on steam.desktop icon by right mouse button and choose "start by discrete gpu" the app start good
5. so I think that when the app try to start default gpu it start integrated (wrong) and when the app try to start integrated gpu instead start discrete gpu (good)
6. default gpu have to be my discrete gpu not integrated 

I hope this message help to fix some error.

best regards,
Leonardo
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13068845/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @lesar, this issue is already being tracked at #9383. Closing as a duplicate.
