### ISSUE TITLE
Steam Client - unable to click options in certian menus

### ISSUE THREAD

**Issue by kellick** [ValveSoftware/steam-for-linux#10162]
#### Your system information

* Steam client version: 1696019606 | Build date: Friday, September 29
* Distribution (e.g. Ubuntu): Linux Mint 21.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, none avialable
* Steam Logs: I will provide specific ones if requested
* GPU: Nvidia RTX 2080 | Driver version 535.113.01-ubuntu0.22.04.3

#### Please describe your issue in as much detail as possible:
Since the Steam client's major UI update in August, I have been unable to use certain menus. Having opened a ticket with Valve, I enabled GPU accelerated rendering which solved part of the issue where I could not click links in the Workshop pages.

Currently, I cannot click links in the context menu that opens when right-clicking a library entry. In the image, were I to click "Properties," It would take me to Rainbow Six: Vegas 2, the library listing underneath the menu.

![SteamLibrary](https://github.com/ValveSoftware/steam-for-linux/assets/69479322/6c6aa04a-cab4-4f53-a8a5-f2d06addc641)

Likewise, opening the drop-down to opt-in to the Steam Client beta under Settings > Interface as Valve had recommended for a possible solution results in the drop-down simply closing and nothing happening:

![SteamBeta](https://github.com/ValveSoftware/steam-for-linux/assets/69479322/95dcd0b0-7b2c-4e8b-8314-eeae4aed741b)

I have downloaded the steam_latest.deb and reinstalled / rebooted several times, find an obscure Linux Mint forum post detailing how to delete a certain cache file, and followed the resolution in this issue post, to no effect: https://github.com/ValveSoftware/steam-for-linux/issues/10084

Steam Runtime Information: https://gist.github.com/kellick/12e9d4513e038548bde818a49d57fc44 
Steam System Information: https://gist.github.com/kellick/62c461ed40f8143b7a0f72dc4c143cb4

#### Steps for reproducing this issue:

1a. Right click a library entry to open context menu
2a. Click a listing in the context menu
3a. Instead get taken to the library entry underneath the context menu

1b. Open Steam Settings, go to Interface settings
2b. Opt-in to Steam Client beta
3b. Click does not register, nothing happens

**Comment by kisak-valve** [comment]
Hello @kellick, this issue is already being tracked at #9273. You might be able to workaround this issue by holding down a modifier key like [CTRL] while clicking the dropdown menu.

Closing as a duplicate.

**Comment by kellick** [comment]
> Hello @kellick, this issue is already being tracked at #9273. You might be able to workaround this issue by holding down a modifier key like [CTRL] while clicking the dropdown menu.
> 
> Closing as a duplicate.

Appreciate the link, indeed it appeared to be part of Mint's focus settings as described in that thread. Thank you!
