### ISSUE TITLE
The Steam Client is constantly crashing 

### ISSUE THREAD

**Issue by sysadminpower2019** [ValveSoftware/steam-for-linux#10168]
#### Your system information

* Steam client version (build number or date): latest from debian repo
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No]: I don't know
* Have you checked for system updates?: [Yes/No]: yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD : AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
 I am on Debian 13 / sid and the steam client keeps opening and closing.

I have tried the no cef workaround, i tried the vgui work around, i tried to install libnm, i tried steam reset, i already tried steam -minimal none of those options work.

the first loading screen opens normally but then it keeps restarting which is annoying as it constantly takes the focus away from the screen.

steamwebhelper.sh[349600]: Runtime for steamwebhelper: defaulting to /home/user/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[349600]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
BuildCompleteAppOverviewChange: 170 apps
RegisterForAppOverview 1: 24ms
RegisterForAppOverview 2: 24ms
and then it just repeats to no end.

**Comment by kisak-valve** [comment]
Hello @sysadminpower2019, if you completely close Steam, then run `steam` from a terminal, does that have an effect?

**Comment by sysadminpower2019** [comment]
@sysadminpower2019 nop it makes no difference.
i have two amdgpu cards on this system. 
An integrated card and a dedicated card. Both of them use the same amdgpu driver.

**Comment by kisak-valve** [comment]
I suspect you're seeing #9383. Any chance `DRI_PRIME` is set in your environment somewhere? The next test would be to try `DRI_PRIME=0 steam` in the terminal.

**Comment by sysadminpower2019** [comment]
yes i set DRI_PRIME 1 in the start up files. I was not able to get my game to play with the dedicated card otherwise even if i ran steam dri prime 1

**Comment by kisak-valve** [comment]
The best suggestion I can give at this time is to run Steam with `DRI_PRIME` unset or set to zero, and to use `DRI_PRIME=1 %command%` in the per-game launch options of games you want to use with the secondary GPU.

Closing in favor of #9383.
