### ISSUE TITLE
The text size in the Steam Client is too small and there is no configuration option to change it.

### ISSUE THREAD

**Issue by pzim-devdata** [ValveSoftware/steam-for-linux#10160]
#### Your system information

* Steam client version (build number or date): 
Version de Steam:  1698185488
Date du build du client Steam:  mar. 24 oct. 23:20 UTC + 01:00
Date du build de la version Web de Steam:  mar. 24 oct. 23:47 UTC + 01:00
Version de l'API Steam:  SteamClient020
* Distribution (e.g. Ubuntu): 
Debian 12 - Cinnamon
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
 Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13165329/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD
Intel Xe Iris

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Hello,

I am using Debian 12 with Cinnamon and the Steam client has really small text display. By checking or unchecking the “Scale text per monitor settings” option, the text size remains too small. It could be useful to add a Display, text size option.

For information, my screen size is 2560x1440. Apparently this size is not well taken into account.

#### Steps for reproducing this issue:

Start Steam Client

Thank you

**Comment by kisak-valve** [comment]
Hello @pzim-devdata, this issue is already being tracked at #5460.

You should be able to workaround this issue by running Steam with `steam -forcedesktopscaling 1.75` or `STEAM_FORCE_DESKTOPUI_SCALING=1.75 steam` (adjust the value as needed).

Closing in favor of the older issue report.
