### ISSUE TITLE
Steam client don't count well the screenshots

### ISSUE THREAD

**Issue by Krovikan** [ValveSoftware/steam-for-linux#10161]
#### Your system information

* Steam Version:  1696019606
* Version Steam's API:  SteamClient020
* openSuSE Tumbleweed (TW)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13168445/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I expected that the number of screenshots marks well. But always mark 30 in everygame with more than 30 screenshots.

Example in this screenshot (the red circle):
![Capturas](https://github.com/ValveSoftware/steam-for-linux/assets/3192501/f1999f64-532b-4647-9ea6-892fc613c12c)
I have in this game 49 screenshots.

This applies to any game with more than 30 screenshots.

#### Steps for reproducing this issue:

1. Start a game.
2. Make 31 screenshots if you don't have yet.
3. Steam client says "Manage my 30 screenshots" like in the screenshot I posted above.

Best regards

**Comment by Krovikan** [comment]
As today, Steam version 1716584667, the issue is solved.

Steam displays the correct number of screenshots instead of only 30.

Greetings

**Comment by kisak-valve** [comment]
Closing per the last comment.
