### ISSUE TITLE
Exiting big picture mode to steam flickers

### ISSUE THREAD

**Issue by razzeee** [ValveSoftware/steam-for-linux#10167]
#### Your system information

* Steam client version (build number or date): 
* Steam Version:  1698451048
Steam Client Build Date:  Sat, Oct 28 01:26 UTC -08:00
Steam Web Build Date:  Sat, Oct 28 01:29 UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu):  Fedora 38 (Gnome)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

<details><summary>Steam Logs:</summary>

```
╰─ tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs                 ─╯
tar: Removing leading `/' from member names
/home/razze/.steam/steam/logs/
/home/razze/.steam/steam/logs/remote_connections.previous.txt
/home/razze/.steam/steam/logs/controller_ui.txt
/home/razze/.steam/steam/logs/systemmanager.txt
/home/razze/.steam/steam/logs/systemdockmanager.txt
/home/razze/.steam/steam/logs/config
/home/razze/.steam/steam/logs/steamui_system.previous.txt
/home/razze/.steam/steam/logs/steamui_system.txt
/home/razze/.steam/steam/logs/cache
/home/razze/.steam/steam/logs/steam-runtime-system-info-1683761662.txt
/home/razze/.steam/steam/logs/.cache/
/home/razze/.steam/steam/logs/.cache/.nv/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/74b75f37316fa002/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/74b75f37316fa002/508e5b5694d010c4.toc
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/74b75f37316fa002/d7db3d2566768e5a.toc
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/74b75f37316fa002/508e5b5694d010c4.bin
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/1019311f538082d1cec7f5679543357c/74b75f37316fa002/d7db3d2566768e5a.bin
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/67ece1d7bb765e2a/
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/67ece1d7bb765e2a/806023b2439c6b1a.toc
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/67ece1d7bb765e2a/806023b2439c6b1a.bin
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/67ece1d7bb765e2a/b6c0667cffa008ff.toc
/home/razze/.steam/steam/logs/.cache/.nv/GLCache/7dccdb8912afcd6839eeade90f7db1fc/67ece1d7bb765e2a/b6c0667cffa008ff.bin
/home/razze/.steam/steam/logs/.cache/tmp/
/home/razze/.steam/steam/logs/connection_log_27015.txt
/home/razze/.steam/steam/logs/data
/home/razze/.steam/steam/logs/steamui_html.previous.txt
/home/razze/.steam/steam/logs/workshop_log.txt
/home/razze/.steam/steam/logs/cef_log.previous.txt
/home/razze/.steam/steam/logs/steamui_update.txt
/home/razze/.steam/steam/logs/systemaudiomanager.txt
/home/razze/.steam/steam/logs/parental_log.txt
/home/razze/.steam/steam/logs/cloud_log.previous.txt
/home/razze/.steam/steam/logs/steamwebhelper.log
/home/razze/.steam/steam/logs/durationcontrol_log.txt
/home/razze/.steam/steam/logs/shader_log.previous.txt
/home/razze/.steam/steam/logs/transport_steamui.txt
/home/razze/.steam/steam/logs/webhelper.previous.txt
/home/razze/.steam/steam/logs/timedtrial_log.txt
/home/razze/.steam/steam/logs/appinfo_log.txt
/home/razze/.steam/steam/logs/transport_client.txt
/home/razze/.steam/steam/logs/streaming_log.previous.txt
/home/razze/.steam/steam/logs/connection_log.txt
/home/razze/.steam/steam/logs/sitelicense_log.txt
/home/razze/.steam/steam/logs/.steam/
/home/razze/.steam/steam/logs/.steam/steam.pid
/home/razze/.steam/steam/logs/.steam/bin
/home/razze/.steam/steam/logs/.steam/sdk32
/home/razze/.steam/steam/logs/.steam/steam
/home/razze/.steam/steam/logs/.steam/sdk64
/home/razze/.steam/steam/logs/.steam/root
/home/razze/.steam/steam/logs/.steam/bin64
/home/razze/.steam/steam/logs/.steam/bin32
/home/razze/.steam/steam/logs/librarysharing_log.txt
/home/razze/.steam/steam/logs/cloud_log.txt
/home/razze/.steam/steam/logs/.config/
/home/razze/.steam/steam/logs/steamui.txt
/home/razze/.steam/steam/logs/connection_log.previous.txt
/home/razze/.steam/steam/logs/steam-runtime-system-info-1698447639.txt
/home/razze/.steam/steam/logs/stats_log.previous.txt
/home/razze/.steam/steam/logs/client_networkmanager.txt
/home/razze/.steam/steam/logs/shader_log.txt
/home/razze/.steam/steam/logs/streaming_log.txt
/home/razze/.steam/steam/logs/cef_log.txt
/home/razze/.steam/steam/logs/parental_log.previous.txt
/home/razze/.steam/steam/logs/configstore_log.txt
/home/razze/.steam/steam/logs/content_log.previous.txt
/home/razze/.steam/steam/logs/compat_log.txt
/home/razze/.steam/steam/logs/console_log.previous.txt
/home/razze/.steam/steam/logs/client_networkmanager.previous.txt
/home/razze/.steam/steam/logs/appinfo_log.previous.txt
/home/razze/.steam/steam/logs/configstore_log.previous.txt
/home/razze/.steam/steam/logs/steamui_html.txt
/home/razze/.steam/steam/logs/steam_api_log.txt
/home/razze/.steam/steam/logs/controller_ui.previous.txt
/home/razze/.steam/steam/logs/steam-runtime-system-info-1683989588.txt
/home/razze/.steam/steam/logs/systemmanager.previous.txt
/home/razze/.steam/steam/logs/custom_log.txt
/home/razze/.steam/steam/logs/controller.previous.txt
/home/razze/.steam/steam/logs/compat_log.previous.txt
/home/razze/.steam/steam/logs/systemperfmanager.txt
/home/razze/.steam/steam/logs/webhelper.txt
/home/razze/.steam/steam/logs/container-runtime-info.txt.oLKWSv
/home/razze/.steam/steam/logs/connection_log_7777.txt
/home/razze/.steam/steam/logs/inventory_service_log.txt
/home/razze/.steam/steam/logs/steam-runtime-system-info-1683988260.txt
/home/razze/.steam/steam/logs/controller.txt
/home/razze/.steam/steam/logs/.local/
/home/razze/.steam/steam/logs/.local/share/
/home/razze/.steam/steam/logs/.local/share/Steam/
/home/razze/.steam/steam/logs/bootstrap_log.txt
/home/razze/.steam/steam/logs/stats_log.txt
/home/razze/.steam/steam/logs/workshop_log.previous.txt
/home/razze/.steam/steam/logs/console_log.txt
/home/razze/.steam/steam/logs/remote_connections.txt
/home/razze/.steam/steam/logs/text_filter_log.txt
/home/razze/.steam/steam/logs/broadcast_log.txt
/home/razze/.steam/steam/logs/systemdisplaymanager.txt
/home/razze/.steam/steam/logs/steamui_audio.txt
/home/razze/.steam/steam/logs/content_log.txt

```

</details>

* GPU: AMD

#### Please describe your issue in as much detail as possible:

This happens, when I try to go from big picture mode to normal steam. In reality it seems even worse, I think the capture was struggling to keep up.

[Screencast from 2023-10-28 02-53-32.webm](https://github.com/ValveSoftware/steam-for-linux/assets/5943908/539369b4-0a04-4248-aff3-746f9c3d6b88)

It should just cleanly exit / transition to the normal steam window.

Iam not sure, if that goes on forever, as I've always used the tray to exit steam. It still keeps on going for quiet a while, after that, but it eventually exits.

#### Steps for reproducing this issue:

1. Start big picture
2. Escape
3. Hit power
4. Exit Big Picture Mode

I suspect, that you need to run Gnome to run into this

**Comment by lsahnicne** [comment]
I'm having the same issue. It's not the screen, but rather a Steam Big Picture window that is flickering. Just when I got my hands on a big screen for couch gaming, damn :(

[screencast.webm](https://github.com/ValveSoftware/steam-for-linux/assets/43319094/52c8b0ba-842d-4a6a-be93-4dbc1e8c3a45)

#### Your system information
* Steam client version (build number or date): 1698260427
* Distribution (e.g. Ubuntu): Pop!_OS 22.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13218199/steam-logs.tar.gz)
* GPU: AMD

**Comment by Caffeineix** [comment]
> I suspect, that you need to run Gnome to run into this

Same issue on Pop!_OS with RTX 3060. This bug seems affect all window managers as far as I can tell, it just manifests differently. KWin is affected in a similar way to Gnome with the glitchy, but in XFWM it leaves an unresponsive minimised window that has to be killed.

**Comment by chrismegyeri** [comment]
Same issue here ongoing for at least a week since I've noticed, flickers like crazy until I alt tab off the steam instance, then it goes back to the normal desktop mode fine.

Steam Version:  1698777785
Steam Client Build Date:  Tue, Oct 31 13:09 UTC -08:00
Steam Web Build Date:  Sat, Oct 28 10:29 UTC -08:00
Steam API Version:  SteamClient020

██████████████████  ████████   ------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: X570 Taichi 
████████            ████████   Kernel: 6.1.55-1-MANJARO 
████████  ████████  ████████   Uptime: 2 days, 11 hours, 1 min 
████████  ████████  ████████   Packages: 2171 (pacman), 78 (flatpak), 21 (snap) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 5120x1440 
████████  ████████  ████████   DE: GNOME 44.5 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita 
████████  ████████  ████████   Theme: Adwaita-dark [GTK2/3] 
████████  ████████  ████████   Icons: Fluent-dark [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
                               GPU: AMD ATI Radeon RX 7900 XT/7900 XTX 
                               Memory: 10623MiB / 128737MiB

**Comment by BigMeanie-nl** [comment]
Same issue on fully updated openSUSE Tumbleweed.
GNOME 45.0 on Wayland
AMD CPU 7800X3D
AMD GPU 7900XTX

**Comment by SrivatsanSenthilkumar** [comment]
This issue is also present in the flatpak version of steam on universal blue version of Fedora Silverblue
GNOME 44.6 on Wayland
Ryzen 5600h + Radeon 5500M

Looks like AMD iGPU+dGPU is the common factor.

**Comment by Caffeineix** [comment]
> Looks like AMD iGPU+dGPU is the common factor.

It happens on NVIDIA as well, I can report the same issue with RTX 3060.

**Comment by jtkellys** [comment]
Same issue here

Fedora 39
Ryzen 6900hs
Radeon 6700s

**Comment by rvdbergh** [comment]
Running into the described issue on:
Steam version: 1698777785
Ubuntu 23.10
MSI B550M Mortar WiFi
Ryzen 9 3950X
AMD RX 580

**Comment by coreybruce** [comment]
Same issue on Manjaro Gnome, please fix this annoying bug!

Steam Version:  1698777785
Manjaro Linux
AMD Ryzen™ 7 5700X × 16
32.0 GiB
AMD Radeon™ RX 6700 XT


https://github.com/ValveSoftware/steam-for-linux/assets/8393780/197dee0f-abe3-4ebc-add8-60ba7609a6b2

**Comment by creativecoder** [comment]
Same issue here on latest Pop_OS! (Gnome 42.9, X11). I have to refresh the desktop (Alt + F2, type r) to resolve the issue before I can do anything else.

**Comment by Davidian1024** [comment]
I just installed Ubuntu 22.04 and I'm now seeing this issue.  Previously I was using 20.04 and I wasn't seeing it then.

Ubuntu 22.04
AMD Ryzen 5 3400G
NVIDIA GeForce GTX 1080 Ti
Steam Version:  1700160213
Steam Client Build Date:  Thu, Nov 16 1:23 PM UTC -05:00
Steam Web Build Date:  Thu, Nov 16 1:06 PM UTC -05:00
Steam API Version:  SteamClient021

**Comment by razzeee** [comment]
The same behavior also happens, when you say to minimize steam

**Comment by razzeee** [comment]
Here's a journal from when this is happening

the interesting part seems to be `Nov 23 19:16:01 fedora-desktop gnome-shell[2540]: meta_window_can_ping: assertion '!window->unmanaging' failed`

[log.txt](https://github.com/ValveSoftware/steam-for-linux/files/13452751/log.txt)

**Comment by TheBurnDoc** [comment]
Also experiencing this issue, Pop_OS! 22.04, AMD RX 7900 XT, exit Big Picture, goes mad

**Comment by geezuh** [comment]
same here. i've noticed clicking the tray icon for steam will stop it. this has been happening for months for me.

**Comment by razzeee** [comment]
There's an mutter issue for this, not sure that's the correct place https://gitlab.gnome.org/GNOME/mutter/-/issues/3126

**Comment by SrivatsanSenthilkumar** [comment]
For further information, this flickering/glitching does not occur when running steam big picture in windowed mode and then exiting big picture mode.

**Comment by spapadim** [comment]
FWIW, encountering same issue (flicker infinite loop when exiting full-screen big picture back into desktop mode). However, it seems to go away if I disable the [gTile](https://github.com/gTile) Gnome shell extension. No idea what gTile does to trigger the behavior.

Also FWIW, though I don't think its relevant, I've noticed BadWindow errors on xreparentwindow() in webhelper.txt logs with a resourceID of 0x0 (there's several other BadWindow errors with other resource IDs for various X requests, including reparentwindow). When the issue **does** occur, I see this repeated (at least 3-4 *consecutive* X req serials, then other errors, then again consecutive repeats, etc), where as when the issue does **not** occur, the BadWindow 0x0 error occurs just once (hence, I don't think it's cause, but perhaps it can provide hint about where it happens?).

Finally, for completeness:
Ubuntu 22.04
Gnome 3.36.8
Intel Core i7-4820K
NVIDIA GeForce RTX 3070 (nvidia driver 545.23.08)
Xorg server vendor version: 1.20.13 (12013000)
Steam Version:  1702079146
Steam Client Build Date:  Thu, Dec 7 7:33 PM UTC -05:00
Steam Web Build Date:  Fri, Dec 8 6:30 PM UTC -05:00
Steam API Version:  SteamClient021

**Comment by Whayme** [comment]
I have the same experience here on GNOME Wayland.  Here's another video of it occurring.  I really hope this is addressed soon, as I imagine with certain desktop backgrounds it could trigger someone's epilepsy.

https://github.com/ValveSoftware/steam-for-linux/assets/63085504/0c2522e5-43c8-42d2-ae26-40ee0a34c464

**Comment by lucaswj** [comment]
Same problem. 
i9-11980 HK
RX 5700xt
PopOS 22.04

cannot leave big picture mode without this same freakout occurring

**Comment by theflakes** [comment]
Seeing the same issue in X11 and Wayland in PopOS 22.04 with all the latest updates. Nvidia GPU and proprietary drivers, AMD 7945HX CPU.

**Comment by reilandeubank** [comment]
Might be beating a dead horse but I'm having an identical issue.
Pop_OS 22.04
Ryzen 5 3600X
RX 5700XT

**Comment by ellitedev** [comment]
This should be high priority, especially since it's dangerous for epileptic people.
Happens on both stable and beta branch.

**Comment by coreybruce** [comment]
I don't understand how such a big issue isn't high priority as it affects such a main features of the Steam client and has been left this long without being fixed...

**Comment by aliasbody** [comment]
Same issue on Xorg and Wayland with:
- Fedora 39
- AMD Ryzen™ 9 5900X
- AMD RX 6700 XT
- Steam Stable version: 1705108172

**Comment by jtkellys** [comment]
> This should be high priority, especially since it's dangerous for epileptic people. Happens on both stable and beta branch.

Actually great point, doesn't this create a legal liability?

**Comment by geezuh** [comment]
Issue has resolved itself for me. 

Manjaro
GNOME Shell 45.3

Steam Beta Branch:  Steam Beta Update
Steam Version:  1706390103
Steam Client Build Date:  Sat, Jan 27 2:58 PM UTC -06:00
Steam Web Build Date:  Fri, Jan 26 1:26 PM UTC -06:00
Steam API Version:  SteamClient021

**Comment by razzeee** [comment]
Same, seems fine on fedora with those same components. :tada:

**Comment by SrivatsanSenthilkumar** [comment]
This is yet to make it to the stable version of the steam client.

**Comment by Mordius** [comment]
Having the same issue, if I join steam beta the issue is resolved but whenever I press Guide/PS button within Big Picture controller stops working only in Big Picture interface. So basically non-beta controller works fine but Big Picture flickers when minimized, and in beta version Big Picture doesn't flickers anymore but controller doesn't work, lmao

**Comment by coreybruce** [comment]
Yeah I can confirm that beta has it fixed tho I noticed some controller input issues like not activating the big picture mode when the button on your controller is pressed or inputs on the BPM menu not working or being stuck going down on the menu.

**Comment by coreybruce** [comment]
Yeah I can confirm that beta has it fixed tho I noticed some controller input issues like not activating the big picture mode when the button on your controller is pressed or inputs on the BPM menu not working or being stuck going down on the menu and can't recommend the beta update or the updates in the beta channel to be pushed to stable until they fix these issues as it breaks things and causes other issues..

**Comment by lucaswj** [comment]
can also confirm my xbox 360 controller seems to go back and forth between
acting like a controller, acting like a mouse, and not working at all in
the beta.

**Comment by coreybruce** [comment]
Latest Steam release fixes the exiting out of big picture mode in fullscreen mode glitch, finally! :smile:
