### ISSUE TITLE
stuck on "processing Vulcan shaders"

### ISSUE THREAD

**Issue by creativitywithluke** [ValveSoftware/steam-for-linux#10176]
#### Your system information

* Steam client version: 1698260427
* Distribution: ubuntu
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* Steam Logs: N/A
* GPU: Nvidia

I am writing to report a critical issue I have encountered while attempting to play 'Counter Strike 2.' Before the massive update, the game ran just fine on my relatively old hardware. However, since this update, when I click the 'Play' button, a popup message appears, indicating that the game is "Processing Vulcan shaders." The problem is that it takes an extraordinarily long time to complete this process. I left the game running for 2 hours, and it only reached 50% completion. Moreover, when I attempt to click 'Skip' to bypass this step, it not only fails to do so but also causes the game to stop running entirely. Subsequently, when I attempt to click 'Play' again, the same 'Processing Vulcan shaders' popup appears.

I have taken various troubleshooting steps to address this issue, including reinstalling the game, but unfortunately, the problem persists. This bug is preventing me from enjoying the game, and I am seeking your assistance to resolve it.

#### Steps for reproducing this issue:

1. click  'play' on counter strike 2
2. the popup saying "processing Vulkan shaders' will appear
3. the skip button just closes the game entirely

**Comment by goldentg** [comment]
im having the same issue on Fedora 38 with AMD

**Comment by mcsygit** [comment]
+1. Stuck on 78%. Arch Linux.

**Comment by psemiletov** [comment]
+1, at 80%. Arch

**Comment by ameameam3** [comment]
Initially had this issue, 99%, except after letting it finish the first time, it would never take as long again. AMD.
Arch, EndeavourOS.

**Comment by goldentg** [comment]
now that i think of it, i believe this issue may lay behind wayland. Wayland does not yet fully support vulkan

**Comment by ameameam3** [comment]
> now that i think of it, i believe this issue may lay behind wayland. Wayland does not yet fully support vulkan

i've only been on X11, so probably not

**Comment by tlneondo** [comment]
One thing that i've noticed is that if one of your Libraries is on a Read only NTFS partition, then the Vulkan Shader processing will not finish processing.

This is a bit of a pain, as I don't want games on an NTFS partion to update through linux as I've gotten file corruption that way, But I do want my linux Partition's steam client to know that an update is required for said games, as that lets me know to reboot into windows and run updates.

Having Steam Skip over read only partitions when processing shaders (if that is indeed what this is) would be a good addition.
