### ISSUE TITLE
VRAM memory leak with "Enable GPU accelerated rendering in web views" option enabled

### ISSUE THREAD

**Issue by vic-bay** [ValveSoftware/steam-for-linux#10180]
#### Your system information

* Steam client version (build number or date): 1698260427
* Distribution: Manjaro Linux x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13211142/steam-logs.tar.gz)
* GPU: Nvidia RTX 2070 Super
* Desktop Environment: KDE Plasma
* XDG session type: x11 (Xorg)

#### Please describe your issue in as much detail as possible:
"Enable GPU accelerated rendering in web views" option causes VRAM leak on each Steam client window minimizing and restore, the VRAM usage goes higher by around 60MiB with each cycle, until it reaches VRAM limit. nvtop reports this behaviour on Xorg process. VRAM is not released until the Steam client is shut down or restarted.

![screenshot_20231031_042146](https://github.com/ValveSoftware/steam-for-linux/assets/10389448/20335076-bea8-4508-ac62-e0129c70faa9)

This leak doesn't happen if hardware acceleration is disabled.
I was able to reproduce it with steam stable and beta clients, with steam runtime (default way to run steam) and native option (system libraries). The issue can be reproduced with any combination of software versions on my side.

#### Steps for reproducing this issue:

1. Turn on "Enable GPU accelerated rendering in web views" option in the Settings - Interface.
2. Restart Steam.
3. Minimize and restore Steam client window. Observe VRAM usage in nvtop utility goes higher.

**Comment by kisak-valve** [comment]
Hello @vic-bay, this issue is already being tracked at #9638.

Closing as a duplicate.
