### ISSUE TITLE
[Feature request] AppImage release

### ISSUE THREAD

**Issue by kenderipa** [ValveSoftware/steam-for-linux#10188]
Hello,

have you considered AppImage release? 

Thanks!

**Comment by kenderipa** [comment]
@kisak-valve, what do you think?

**Comment by albertescanes** [comment]
This would be great.

**Comment by hajosattila** [comment]
This would be great!

**Comment by kenderipa** [comment]
No reaction from development team, no upvotes, therefore looks improbable, therefore closing.

**Comment by kenderipa** [comment]
No reaction from development team, no upvotes, therefore looks improbable, therefore closing.

**Comment by kenderipa** [comment]
No reaction from development team, no upvotes, therefore looks improbable, therefore closing.

**Comment by Samueru-sama** [comment]
> No reaction from development team, no upvotes, therefore looks improbable, therefore closing.

https://github.com/ivan-hc/Steam-appimage

**Comment by probonopd** [comment]
Why was this closed? Maybe the Valve team just didn't have the time to look into this yet?
In any case, if the Valve team is interested in providing an official AppImage, I'm here to help.
