### ISSUE TITLE
Cannot Add Drive to Steam, Popup is Empty

### ISSUE THREAD

**Issue by HairBomb7** [ValveSoftware/steam-for-linux#10189]
#### Your system information

* Steam Runtime Version: 1698777785
* Distribution (e.g. Ubuntu 18.04): Arch Linux
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My second "games" drive disappeared from Steam and I can no longer see my installed games in the Steam library. When I go to Add a Drive, it just brings up an empty popup window, with nothing to select. I verified that my drive is still mounted and my Heroic Games launcher can see it just fine. Any ideas on why nothing would be showing up in the Add Drive screen?

#### Steps for reproducing this issue:

1. Open Steam -> Settings
2. Go to Storage page
3. Click Add Drive in the drop-down menu
4. Empty popup comes up and there are no drives or folders to select

![image](https://github.com/ValveSoftware/steam-runtime/assets/149630104/e429688d-2127-4098-bf48-ce5373270c42)

**When I launch steam with the CLI, I noticed these two error messages:**
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant

**I see this in the Steam Runtime Diagnostics**
```
"xdg-portals" : {
    "details" : {
      "interfaces" : {
        "org.freedesktop.portal.Email" : {
          "available" : false
        },
        "org.freedesktop.portal.FileChooser" : {
          "available" : false
        },
        "org.freedesktop.portal.Inhibit" : {
          "available" : false
        },
        "org.freedesktop.portal.OpenURI" : {
          "available" : false
        },
        "org.freedesktop.portal.ScreenCast" : {
          "available" : false
        },
        "org.freedesktop.portal.Settings" : {
          "available" : false
        }
      },
      "backends" : {
        "org.freedesktop.impl.portal.desktop.gtk" : {
          "available" : false
        },
        "org.freedesktop.impl.portal.desktop.kde" : {
          "available" : false
        }
      }
    },
    "issues" : [
      "missing-interface",
      "no-implementation"
    ],
    "messages" : [
      "The 'version' property is not available for 'org.freedesktop.portal.Email', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.FileChooser', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.Inhibit', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.OpenURI', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.ScreenCast', either there isn't a working xdg-desktop-portal or it is a very old version",
      "The 'version' property is not available for 'org.freedesktop.portal.Settings', either there isn't a working xdg-desktop-portal or it is a very old version",
      "There isn't a working portal implementation"
    ]
  },
  ```

**Comment by kisak-valve** [comment]
Hello @HairBomb7, this issue is already being tracked at #10120.

Closing as a duplicate.
