### ISSUE TITLE
Fractional scaling game issues

### ISSUE THREAD

**Issue by inverse** [ValveSoftware/steam-for-linux#10195]
#### Your system information

* Steam client version (build number or date):  steam-runtime_0.20231024.64411
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia 3060 ti

#### Please describe your issue in as much detail as possible:

I'm running Cinnamon at 150% scaling on my UHD monitor and games scale incorrectly under this setting.

If i change my display to 100% it works fine but I was wondering how I could change games to launch at 100% scale under this environment without scaling back my DE when wanting to play.

The steam client scales perfectly.

#### Steps for reproducing this issue:

1. Set scale to 150% on Cinnamon on UHD monitor
2. Launch steam
3.  Load any game. e.g. Spore, etc

**Comment by kisak-valve** [comment]
Hello @inverse, issues with games run with Proton are being tracked in the Proton issue tracker. This specific issue is being tracked at https://github.com/ValveSoftware/Proton/issues/4904.

Closing as a duplicate.

**Comment by inverse** [comment]
ahh wasnt aware of that place  thanks!
