### ISSUE TITLE
nvidia stable driver 545: games not launching

### ISSUE THREAD

**Issue by leder11011** [ValveSoftware/steam-for-linux#10202]
#### Your system information

* Steam client version (build number or date): 1699401499
* Distribution (e.g. Ubuntu): Ubuntu 22.04.3 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13292197/steam-logs.tar.gz)

* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
expected:
games launch in 4k resolution
acutal:
games give an error, cp. screenshot/do not launch at all

#### Steps for reproducing this issue:

1. Cloudpunk
2. Figment 2
3. Marvel's Guardians of the Galaxy

![Bildschirmfoto vom 2023-11-08 05-32-38](https://github.com/ValveSoftware/steam-for-linux/assets/3330116/d7f45c7f-4600-4245-af97-f5ed84ecc192)

**Comment by kisak-valve** [comment]
Hello @leder11011, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by leder11011** [comment]
https://gist.github.com/leder11011/20291ba3b8e6fa29980ccae6c72f36b1

**Comment by kisak-valve** [comment]
Thanks, looking over the diagnostics information, your NVIDIA driver install is broken and Steam is being forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all. It's likely that nothing on your system can use the video card right now.

Report this issue to the package maintainer of the NVIDIA system packages you have installed.

**Comment by leder11011** [comment]
thank you  @kisak-valve ! I removed the ubuntu PPA and installed nVidia proprietary drivers package from nvidia.com:
- now my games show the launcher
- but the game has only black screen

Any idea?

**Comment by kisak-valve** [comment]
Please share an updated runtime diagnostics gist so that we can ponder the current state of your system.

The only quick guess I can make is that you could have changed the installed NVIDIA driver version, but the previous NVIDIA kernel module is still loaded into memory and rebooting the system might help.

**Comment by leder11011** [comment]
https://gist.github.com/leder11011/5e6e896ec45841e575ee0ed10104219a

**Comment by kisak-valve** [comment]
Unfortunately, https://gist.github.com/leder11011/5e6e896ec45841e575ee0ed10104219a#file-gistfile1-txt-L354-L460 doesn't look any healthier than before.

**Comment by leder11011** [comment]
nvidia driver works for:
- desktop
- nvidia-settings
- Stable Diffusion

How come, that the games do not launch?
