### ISSUE TITLE
Multiple windows about different driver updates, then Steam attemps to shut down

### ISSUE THREAD

**Issue by hjpaul7** [ValveSoftware/steam-for-linux#10206]
#### Your system information

* Steam client version (build number or date): Nov 9th
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13315501/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
As far as I can tell there was no user interaction to cause this, I came back to the PC and Steam was like this. Multiple windows popped up about different driver updates (there were 3, I closed two before I took the screenshot) along with the modal "Steam is shutting down..." (did not initiate shutdown). Clicking "Cancel" or the "X" on the shutdown prompt both do nothing, nor close the prompt.

Clicking "Update" on any of the driver update windows does nothing but close the window and re-opens it.

Total of 3 driver update windows:
- Sony dual sense controller [object object]
- Audio driver
- Gamepad driver

Windows would endlessly popup until I had to kill steam with `killall steam`.

Edit: It also opened the storage manager window, which I did not open.

#### Steps for reproducing this issue:

1. Honestly I'm not sure, came back to PC this way.

![steam-again](https://github.com/ValveSoftware/steam-for-linux/assets/63761039/5d4c737c-149d-41c8-b715-1229326de07f)

**Comment by kisak-valve** [comment]
Hello @hjpaul7, this issue is already being tracked at #10012. Closing as a duplicate.
