### ISSUE TITLE
prime-run steam not working

### ISSUE THREAD

**Issue by karesosis** [ValveSoftware/steam-for-linux#10208]
* System info via steam: [here](https://gist.github.com/karesosis/f1a712e7bb438ab430d8b228d9164629)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

* Steam Logs: [steam-logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/13319130/steam-logs.zip)
* GPU: Nvidia

i used to `prime-select nvidia` and run steam via terminal (idk why i cant able to run with steam icon) all was fine till i decide to use intel as prime ( why im trying this is prime nvidia power consumption and also unnecessary _fan noise_.) and launch steam on terminal with `prime-run steam`. its gives 
```
steam.sh[9687]: Running Steam on ubuntu 22.04 64-bit
steam.sh[9687]: STEAM_RUNTIME is enabled automatically
setup.sh[9757]: Steam runtime environment up-to-date!
steam.sh[9687]: Steam client's requirements are satisfied
[2023-11-10 15:19:09] Startup - updater built Oct 31 2023 02:08:17
[2023-11-10 15:19:09] Startup - Steam Client launched with: '/home/karesosis/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad'
11/10 15:19:09 Init: Installing breakpad exception handler for appid(steam)/version(1698777785)/tid(9816)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
as an terminal output. steam only shown in as process in system monitor.
inside [prime-run](https://gist.github.com/karesosis/a488be84598d680e84260478db32abc5)

#### Steps for reproducing this issue:

1. switch `prime-select intel`
2. run `prime-run steam` on terminal

**Comment by kisak-valve** [comment]
Hello @karesosis, this is the same issue being tracked at #9383. Closing in favor of the older issue report.
