### ISSUE TITLE
apex legensd/tf2/gmod proton 8 doesnt launch steamoverlay renderer

### ISSUE THREAD

**Issue by picarica** [ValveSoftware/steam-for-linux#10212]
#### Your system information

* Steam client version (build number or date): 12.11.23 idk newest
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] NO !
* Have you checked for system updates?: [Yes/No] YES!
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
i saw on protondb apex should run, i downloaded it installed proton, and it doesnt launch i got this snippet from terminal

```
pressure-vessel-wrap[643794]: W: "/home/picarica/diffusion/ana/bin/iconv" is unlikely to appear in "/run/host"
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_IE.utf8...
pressure-vessel-locale-gen: Generated locale en_IE.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[643869]: W: Container startup will be faster if missing locales are created at OS level
sh: line 1: xdg-user-dir: command not found
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
sh: line 1: xdg-user-dir: command not found
/bin/sh\0-c\0gamemoderun /home/picarica/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1172470 -- /home/picarica/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/picarica/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/picarica/.steam/debian-installation/steamapps/common/Proton 8.0'/proton waitforexitandrun  '/home/picarica/.steam/debian-installation/steamapps/common/Apex Legends/EasyAntiCheat_launcher.exe' -steam -novid +fps_max unlimited -preload\0
chdir "/home/picarica/.steam/debian-installation/steamapps/common/Apex Legends"
ERROR: ld.so: object '/home/picarica/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: line 1: gamemoderun: command not found
Uploaded AppInterfaceStats to Steam
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
```
but no idea what most of these means? similar error with thtat gameoverlayrendere shows on garrysmod and tf2 which also doesnt launch, some other proton games worked also CS2 worked,

anyone with similar problem? not sure if issue with gentoo shouldnt steam use its packaged libraries?

**Comment by kisak-valve** [comment]
Hello @picarica, we're tracking issues with games run with Proton in the Proton issue tracker. Usually I'd transfer this issue report to the Proton issue tracker, but this one is fairly obvious.

`/bin/sh\0-c\0gamemoderun /home/picarica/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1172470 -- /home/picarica/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/picarica/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/picarica/.steam/debian-installation/steamapps/common/Proton 8.0'/proton waitforexitandrun  '/home/picarica/.steam/debian-installation/steamapps/common/Apex Legends/EasyAntiCheat_launcher.exe' -steam -novid +fps_max unlimited -preload\0`

`/bin/sh: line 1: gamemoderun: command not found`

These lines tell us that you've set the game's launch options to something like `gamemoderun %command%` and that command doesn't exist on your system. Clear that game's launch options and retest. If that doesn't help, then add a note to https://github.com/ValveSoftware/Proton/issues/4350 with the retest results and continue discussing that specific game on the game's compatibility report.

You're most likely seeing https://github.com/ValveSoftware/Source-1-Games/issues/5043 with the Linux native variants of Team Fortress 2 and GMOD
