### ISSUE TITLE
Steam switches to Windows native distro for Linux native game at every game update

### ISSUE THREAD

**Issue by JonathanGrant92** [ValveSoftware/steam-for-linux#10213]
#### Your system information

* Steam client version (build number or date): 
  * Steam Version:  1698777785
  * Steam Client Build Date:  Mon, Oct 30 20:09 UTC -07:00
  * Steam Web Build Date:  Fri, Oct 27 17:29 UTC -07:00
  * Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): 23.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
  * [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13328465/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
With every update of one steam game, the installation is switched from the linux distro to Windows.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45248168/c146f0e2-db39-4d07-9c53-a8e2e4620e95)

When this happens, game fails to launch. Trying to launch Stellaris 4 times at 2023-11-12 8:34 AM MST. The only way to fix this is to "trick" Steam into switching distros again via Stellaris > Properties > Compatibility > quickly enable and disabling Force the use of a specific Steam Play compatibility tool.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45248168/e3fb5348-ab53-41bc-b5bc-e19bf48fcf47)

An update is queued.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45248168/d91d15f5-738d-4d00-8531-da5eb6590855)

And now the distro is Linux again.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45248168/79b2e004-10f3-4b98-a11d-e856379d7fe9)

Launching game at 8:39 AM MST is successful. I am collecting steam logs now for your analysis.
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13328465/steam-logs.tar.gz)

#### Steps for reproducing this issue:
Unknown
However, I was testing Proton 8 with Force the use of a specific Steam Play compatibility tool and restricting permissions on ~/.paradoxlauncher/ to workaround an issue with paradox launcher 2023.14 and 2023.14.1 throwing a crash report pop-up that distorts the display and crashes Stellaris if interacted with. I restored the original configuration for Linux native distro because the workarounds caused more problems, for example, missing image data for leaders, planets, builidings and ships in game with proton 8.

Now, any update to Stellaris installs the Windows distro, which fails silently on launch and I have to toggle on and off the Compatibility mode to queue the Linux distro again.

**Comment by kisak-valve** [comment]
Hello @JonathanGrant92, this issue is already being tracked at #9875. Closing as a duplicate.

**Comment by JonathanGrant92** [comment]
@kisak-valve Sounds good. I think it's odd that the Windows native game is installed without the proton distributables AFAIK, causing launch to silently fail, at least in some cases. My thinking on the steps to reproduce on a Linux machine like Ubuntu 23 are below:
1. go to Steam > Settings > Compatibility > enable both settings and Run other titles with Proton Experimental
    ![image](https://github.com/ValveSoftware/steam-for-linux/assets/45248168/80849fee-6911-47cb-a674-fc0840efca27)
2. Install any steam native game, especially one that may have middle-ware, like Stellaris, TF2, 7D2D
3. In the Steam library, right click the game > Properties > Compatibility > enable Force the use of a specific Steam Play compatibility tool
4. Launch the game with the compatibility tool.
5. Exit the game
6. In the Steam library, right click the game > Properties > Compatibility > disable Force the use of a specific Steam Play compatibility tool
7. Optionally, do NOT relaunch the game.
8. In the Steam library, right click the game > Manage > Browse local files > optionally Open in terminal > check the directory for dlls and exes 
9. After an update is pushed, recheck the directory for dlls and exes. Stellaris is a good choice because a dlc is releasing soon, so there will be many updates during the next month or two. Also, Stetllaris launch will silently fail, for example, no launch pop-up or message. The launching indicator in Steam library just switches back to PLAY.
