### ISSUE TITLE
Add Wayland support for Steam Link

### ISSUE THREAD

**Issue by jtkellys** [ValveSoftware/steam-for-linux#10220]
#### Your system information

* Steam client version (build number or date): Mon, Oct 30 7:09 PM UTC -08:00
* Distribution (e.g. Ubuntu): Fedora 39
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:

When trying to stream via Steam Link on Wayland, the remote client only shows a black screen. I understand the work around for this is to use Xorg or X11, but with many distros dropping support for X11/Xorg would it be possible to look into implementing streaming capabilities with Wayland? I know inputs are an issue with wayland, but Sunshine has found a work around and AMD systems are capable of using the `-pipewire` argument (to mixed results). As for using Steam Link over Sunshine, I have a physical Steam Link that I still use regularly. 

I understand this is a feature request and not an issue, I don't know how to add the feature request tag.

**Comment by kisak-valve** [comment]
Hello @jtkellys, this issue is already being tracked at #6148. Closing as a duplicate.
