### ISSUE TITLE
the content of the Steam Window is black screen up on resizing the window

### ISSUE THREAD

**Issue by Frambooisier** [ValveSoftware/steam-for-linux#10229]
#### Your system information

* Steam client version (build number or date): 1700160213
* Distribution (e.g. Ubuntu): Kubuntu 23.10
* Opted into Steam client beta?: Yes (tried both)
* Have you checked for system updates?: Yes
* Steam Logs:[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13401587/steam-logs.tar.gz)
* GPU: Nvidia RTX3070

#### Please describe your issue in as much detail as possible:
The window turns into blank black content if Steam window is dragged to the edge of the screen to switch it to maximized window or just pulling it down to the middle of the screen from maximized to windowed. Using maximize window button or resizing the window with drag works no problem. The content that has problems is browser type like "Store", "community" user profile section.

#### Steps for reproducing this issue:

1. run Steam into library
2. go to store
3.pull the window to the top edge to maximize the window

https://github.com/ValveSoftware/steam-for-linux/assets/15931041/f7933494-689f-4e89-b076-a912b73a17e4

**Comment by kisak-valve** [comment]
Hello @Frambooisier, this issue is already being tracked at #9375. Closing as a duplicate.

**Comment by Frambooisier** [comment]
Hello @kisak-valve thank you!
