### ISSUE TITLE
Steam loading video (new feature) does not show on Linux Steam Client

### ISSUE THREAD

**Issue by mbcraft** [ValveSoftware/steam-for-linux#10227]
#### Your system information

* Steam client version (build number or date): 1700160213
* Distribution (e.g. Ubuntu): Linux Mint 21
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13397581/steam-logs.tar.gz)`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I expected to see the startup video when steam is started after i bought and equipped it. No video is shown actually.

#### Steps for reproducing this issue:

1. Buy a steam startup video from the points shop
2. Equip it
3. Restart Steam Client

**Comment by kisak-valve** [comment]
Hello @mbcraft, the startup video you're referring to is part of the Steam Deck client, and not the general Linux desktop client.
