### ISSUE TITLE
Dualshock 4 doesn't recognized by client fully unless one goes into advanced diagnostics

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#10222]
#### Your system information

* Steam client version (build number or date): 1699498641
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13355723/logs.tar.gz)

* GPU: Not relevant

#### Please describe your issue in as much detail as possible:
Dualshock 4 controller doesn't get recognized fully ( as in led color changes made previously won't load and rumble function won't work, which can be tested within Steam's Input Testing in Controller menu) until one goes into "Diagnostics and Advanced Settings" in Controller menu. 

After that led color will change and rumble will start to work  which can be tested within Steam's Input Testing in Controller menu.
#### Steps for reproducing this issue:

1. Boot Steam
2. Connect Dualshock 4 controller via bluetooth
3. Go into Steam's Input Testing in Controller menu and see rumble doesn't work.
4. Go into Diagnostics and Advanced Settings" in Controller menu and see how led color changes.
5. Go into Steam's Input Testing in Controller menu again and see how rumble works now.

**Comment by Leopard1907** [comment]
Two beta releases happened after the report with bunch of Steam Input-controller fixes, improvement but there was no change for the issue. As a FYI.

**Comment by nm004** [comment]
Rumble in "Test Device Inputs" does not work until toggling "Game Rumble" option in "Calibration & Advanced Settings". Also, toggling "Game Rumble" option in "Calibration & Advanced Settings" does not take effect, which "Game Rumble" in "Controller" takes precedence over the former.

I tested it with a Dualshock 4 controller.

**Comment by nm004** [comment]
The issue of testing rumble can be seen in Windows too.

**Comment by Leopard1907** [comment]
@kisak-valve Can Windows tag ( if exist ) be added to per comment above from @nm004 ?

**Comment by Leopard1907** [comment]
I can't repro this anymore. Closing.

**Comment by nm004** [comment]
It is closed now but the issue still exist as of today.

**Comment by nm004** [comment]
@Leopard1907 On Windows. My Dualshock 4's model is CUH-ZCT1J (older Dualshock 4).
