### ISSUE TITLE
Steam store flickering

### ISSUE THREAD

**Issue by Asteliks** [ValveSoftware/steam-for-linux#10238]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13423524/steam-logs.tar.gz)
* Steam System Info: https://gist.github.com/Asteliks/c2c64fea3927eba80fe6e07901346d9a
* Steam runtime environment diagnostics: https://gist.github.com/Asteliks/97b8f2a7d540fb0ebe8ae66e1c1cc305
* Issue recording: [2023-11-20 22-34-12.zip](https://github.com/ValveSoftware/steam-for-linux/files/13423581/2023-11-20.22-34-12.zip)
* GPU: Nvidia RTX 3080

#### Please describe your issue in as much detail as possible:
Hello Steam Support,

I'm reaching out to bring attention to a technical glitch in the Steam application that has been affecting my user experience. The issue revolves around persistent "flickering," notably conspicuous during navigation within the store. Notably, this problem appears exclusive to the Steam application and does not manifest in any other software.

Furthermore, additional anomalies have been observed. These include erratic screen behavior, with noticeable vertical movement during scrolling, and a pronounced delay when inputting text—such as in this report.

For your convenience, I have attached a recording that captures the observed "flickering" phenomenon.

Your prompt attention and assistance in resolving these technical challenges would be greatly appreciated.

#### Steps for reproducing this issue:

1. Open Steam
2. Go to store
3. The flickering show has begun. No extra steps needed 

**Edit:
Disabling hardware acceleration doesn't resolve the issue.**

**Comment by kisak-valve** [comment]
Hello @Asteliks, from the comments on #10005, can you go to `Steam` -> `Settings` -> `Interface` and check if `Enable GPU accelerated rendering in web views` is enabled, and if togging it works around this issue.

**Comment by Asteliks** [comment]
Hello @kisak-valve, I've tried that yesterday and after your comment just in case. Unfortunately the issue persists no matter if GPU acceleration is enabled or disabled. However I must say that today after disabling the GPU acceleration the flickering is a bit less annoying. It is still there but it is slower.

**Comment by anohren** [comment]
Same problem on a fully updated Gnome Wayland on Ubuntu 23.10 on a Intel(R) Core(TM) i5-3427U with HD Graphics 4000

**Comment by IMHCWinston** [comment]
Same issue with me too on Wayland NVIDIA, except for me toggling `Enable GPU accelerated rendering in web views`  does seem to fix the issue. Only problem with that is toggling that option seems to cause Steam Library to lag.

**Comment by FishyW** [comment]
Same issue with me too on Fedora GNOME Wayland NVIDIA, except for me toggling Enable GPU accelerated rendering in web views does seem to fix the issue. Only problem with that is toggling that option seems to cause Steam Library to lag.

**Comment by hak8or** [comment]
Chiming in to say also disabling HW acceleration in web views resolved my flickering woes.

**Comment by ergo3d** [comment]
same problem
gpu: nvidia 4080
os: arch linux
composer: wayland
driver: 545.29.06 (and any previous)
source: flatpack (native too)

no matter enabled gpu acceleration or not, no flickering only wile used x11 
seems like problem happen beacouse steam working through xwayland not wayland native

**Comment by Asteliks** [comment]
@ergo3d you might be suffering the same issue as I'm could you attach your logs for the steam devs? Perhaps this will make their lives easier

**Comment by oahshtsua** [comment]
Same issue with me. Steam client flickers even when GPU accelerated rendering is disabled. I have noticed that this occurs when the steam client is maximized. This does not occur when it is not maximized and in the size with which it opened initially.

- Steam client version (build number or date):
  -  Steam Beta Branch:  Stable Client
  - Steam Version:  1705108172
  - Steam Client Build Date:  Sat, Jan 13 6:37 AM UTC -08:00
  - Steam Web Build Date:  Fri, Jan 12 10:47 PM UTC -08:00
  - Steam API Version:  SteamClient021
- Distribution (e.g. Ubuntu): Fedora (KDE 5.27.10 Wayland Session)
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by Asteliks** [comment]
@oahshtsua could you attach your logs for the steam devs? Perhaps this will make their lives easier

**Comment by ItsGamerik** [comment]
> Chiming in to say also disabling HW acceleration in web views resolved my flickering woes.

also chiming in to say that this fixed the issue for me too

**Comment by ergo3d** [comment]
problem fully fixed if you using new nouveau nvk driver, but it has bad performance for now and dont support cuda at all

**Comment by Asteliks** [comment]
I did some testing and it would seem that the cause of the issue are the Nvidia proprietary drivers. As stated by ergo3d the flickering stops on nouveau drivers. However a different issue appears there - when moving steam from one monitor to another it goes completely black

**Comment by anohren** [comment]
> it would seem that the cause of the issue are the Nvidia proprietary drivers

Should I delete my comment so that it doesn't conflict with your conclusion?

**Comment by Asteliks** [comment]
> > it would seem that the cause of the issue are the Nvidia proprietary drivers
> 
> Should I delete my comment so that it doesn't conflict with your conclusion?

@anohren It may be best if you open your own ticket with all the logs attached

**Comment by anohren** [comment]
Yeah maybe you're right. While I seem to have the same symptoms I can't assert that it's the same cause.

**Comment by ergo3d** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/4924#issuecomment-1975248612

**Comment by Asteliks** [comment]
> [#4924 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/4924#issuecomment-1975248612)

@ergo3d I've tried the suggested solution. It seems to solve the flickering issue but adds two new ones:

- when scrolling that store pages seem to jump. For example scroll down -> the steam page moves down -> for a second it jumps back up -> than jumps back to the intended position
- other apps seem to leak into the steam view. For example have steam store open and try doing anything. At random times other currently open applications will take over the steam store view (can be your browser, file explorer, gnome background - anything that is "behind steam"). When trying to print screen this issue everything gets the way it should. Only way to show this is by taking a picture of your screen with an external device.

**Comment by SadmL** [comment]
I've encountered with same problem on Arch, Plasma 5.27, nvidia-dkms 545 (if I not mistaken).
I've disabled smooth scroll and GPU rendering and there is no flickering anymore.

**Comment by FriedPotatoes49** [comment]
It looks like the steam beta update fixes this. I'm on Nobara Linux with Wayland on a GTX 1650 with driver 550.

**Comment by ItsGamerik** [comment]
I am also running the beta on fedora linux 40 with nvidia driver version 550.76. When turning on WebView the shop and community sections are still very glitchy and unusable.

**Comment by ergo3d** [comment]
seems like fixed NVIDIA-SMI 555.42.02  
with nvidia.NVreg_EnableGpuFirmware=0 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 on boot oprions

**Comment by dinhokusanagi** [comment]
I have the same problem with AMD lacquer, Proton games run, but native games like Dota 2 don't, Steam simply closes and I have to close the session

**Comment by iso2013** [comment]
> seems like fixed NVIDIA-SMI 555.42.02 with nvidia.NVreg_EnableGpuFirmware=0 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 on boot oprions

On my machine, setting only `nvidia_drm.fbdev=1` was sufficient.

**Comment by Asteliks** [comment]
This issue seems to be fixed on the current version of steam, fedora and NVidia drivers as such I'm closing this issue
