### ISSUE TITLE
Mouse clicks not registering on Steam Overlay while in CS2

### ISSUE THREAD

**Issue by DanCarzano** [ValveSoftware/steam-for-linux#10237]
#### Your system information

* Steam client version (build number or date): 1700533348 (Tue, Nov 21 12:07 PM UTC +10:00)
* Distribution (e.g. Ubuntu): Nobara 38 (Fedora)
* Opted into Steam client beta?: Yes and tried No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13423325/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Opening overlay while in Counter Strike 2 (Linux Native), keybind opens the overlay fine, however, mouse click input on items in the overlay are not registered. Keyboard input seems to work, mouse cursor input works fine, but left and right clicking does nothing.

#### Steps for reproducing this issue:

1. Open Counter Strike 2
2. Open Steam Overlay while in-game
3. Try to click on any button/resize windows - will not work

**Comment by kisak-valve** [comment]
Hello @DanCarzano, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3567. Closing as a duplicate.
