### ISSUE TITLE
Idea/Feature Request : Allow Linux native games to be distributed as a Flatpak from Steam's own Flatpak repo

### ISSUE THREAD

**Issue by RushingAlien** [ValveSoftware/steam-for-linux#10244]
#### Your system information

* Steam client version (build number or date): 1700160213 
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Hello! I would like for Steam to allow games to be published as a flatpak in Steam's/Valve's own flatpak repo, the flatpak binary itself would be provided within steam-runtime. With the runtimes games can use being either the Freedesktop Runtime(org.freedesktop.Platform) or the Steam Runtime(com.valveSoftware.Platform?), now begs the question: Should the Steam runtime extends from the Freedesktop runtime, I say yes, cause this way, steam can use GL drivers from flathub.

Flatpak supports [custom installation dirs](https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation), so shouldn't be too much of a problem for the storage manager.

I've had so many native linux games not run that it's easier to use proton

**Comment by orowith2os** [comment]
The largest problem with this wouldn't be distributing the games via Flatpak - that's very well possible with how pressure-vessel is designed - it's the legal troubles, or so I assume. How would Valve enforce that random people don't download games from their Flatpak repo? They obviously can't stop them from distributing the already-downloaded binaries, but not making an attempt to prevent people from downloading paid games for free on their servers would be An Issue.

For the runtime itself, they can just use something based on the Freedesktop runtime. The Steam runtime is old enough that nothing should break. 

> I would like for Steam to allow games to be published as a flatpak in Steam's/Valve's own flatpak repo,

This would also be my first time hearing that Valve has their own Flatpak repo. Their runtime doesn't come from Flatpak, it comes from Valve's own distribution system, run in their own containerization system.

**Comment by RushingAlien** [comment]
> This would also be my first time hearing that Valve has their own Flatpak repo. Their runtime doesn't come from Flatpak, it comes from Valve's own distribution system, run in their own containerization system.

I am aware, and that's exactly the request, to create one
