### ISSUE TITLE
Discovery list broken on steam deck

### ISSUE THREAD

**Issue by glauberdmo** [ValveSoftware/steam-for-linux#10249]
#### Your system information

* Steam client version (build number or date): 1700676668
* Distribution (e.g. Ubuntu): steamOS build 20231116.2
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes
* GPU: steam deck default

#### Please describe your issue in as much detail as possible:
Discovery list is not working on deck mode, store stays frozen after trying to access through main page.  Steam button continues to work. After that the only way to use the store is restarting steam client

#### Steps for reproducing this issue:

1. Open store in default deck page ("ótimos no deck" equivalent)
2. Access the thumb of discovery list
3. After that no scrolling or any interact is possible with store page.

**Comment by rhoot** [comment]
I have two Steam Decks and see this same problem on both, and it also happens in the Linux desktop Steam client in big picture mode. The store remains frozen until you restart the Steam Client.

**Comment by rhoot** [comment]
This appears to have been fixed at some point. Discovery queue works fine now in Steam client 1702079146.
