### ISSUE TITLE
Steam crashes from launcher, though not when running from CLI

### ISSUE THREAD

**Issue by taserian** [ValveSoftware/steam-for-linux#10250]
#### Your system information

* Steam client version (build number or date): 1700160213
* Distribution (e.g. Ubuntu): Pop!_OS 22.04 LTS x86_64 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13465000/steam-logs.tar.gz)`]
* GPU: NVidia GeForce GTX 1060 Mobile

#### Please describe your issue in as much detail as possible:
Launching the Steam Client from Applications causes it to crash shortly after the modal searching for updates. However, running `steam` from the CLI allows it to run normally. 

#### Steps for reproducing this issue:

1. Launch `Steam` from Applications. Crashes shortly thereafter.

**Comment by kisak-valve** [comment]
Hello @taserian, this is effectively the same issue as #9383. Closing in favor of the older issue report.
