### ISSUE TITLE
Close to Tray

### ISSUE THREAD

**Issue by kevincox** [ValveSoftware/steam-for-linux#1025]
There have been similar reports (#11 and #270) but they have been closed because they were talking about adding a system tray icon **which already exists**.  So to everyone who is reading this without a tray icon don't comment as it will get closed for the same reason.

Currently, when pressing the close or minimize buttons in the main steam window it causes steam to minimize.  It would be nice if the minimize button retained it's current behavior while the close button closed the main window but kept it running in the tray.

Currently the only way to have steam running in the tray is by launching it as `steam --applaunch $id` because the window is never opened.  Of course, once you open the window you have no way to close it.

I understand if this is a low priority enhancement request because it does not affect Unity but it would be a nice feature to eventually have implemented for traditional desktops.  It is really annoying to have the steam window taking up space in my panel when I am not actively using it and am just keeping it open to receive notifications.

**Comment by HitmanNumber86** [comment]
"Our hope is that the problems there will get worked out and then we can remove our workarounds and rely on the app indicator, at which point closing the window will close it."
--- gdrewb-valve Jan 29, 2013

Almost two years, and this still hasn't been fixed. I just got Steam, for the first time. I thought my install was effed up. I really don't like fighting my computer on things like this.

**Comment by Celexi** [comment]
Try work around on /usr/bin/steam or as a environment variable, it may or may not work for you ( the usr/bin/steam does for me )

**Comment by schoening** [comment]
The workaround is still working fine for me btw. Even after steam updates :)

**Comment by tengwar** [comment]
On Ubuntu I installed long time ago, environment variable still works even after Steam updates. On the other hand on recently installed openSUSE 13.2 x64 both /usr/bin/steam and environment variable do not work.

**Comment by fishxz** [comment]
i fixed it this way:
https://wiki.archlinux.org/index.php/steam#The_close_button_only_minimizes_the_window
on ubuntu. but please add this by default, because the windows version works the same way.

**Comment by Yanpas** [comment]
@fishxz Thanks! That works under XFCE
Whisker menu right click, Edit Menu, Steam. sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U

**Comment by asantos3** [comment]
Why isn't this the default? Pretty simple and works great. Perhaps even doing what #2239 suggests would solve this.

**Comment by MightyPork** [comment]
Guys it's pointless, they won't fix this no matter how much we complain.
It's been open for TWO YEARS. Stupid decision, but all we can do is the workaround.

**Comment by n1trux** [comment]
how the fuck is this still open? This is such an easy fix.

Valve devs seem to be really, really lazy.

**Comment by jhasse** [comment]
I think they aren't: This is intentional as Steam wants to push Ubuntu and this is only a low priority bug when using Unity.

It's still ridiculous as having two buttons doing the same thing is stupid. So please Valve: Please fix this, even if it isn't much of a annoyance with Unity.

**Comment by Yanpas** [comment]
Valve doesn't pficcialy support xfce and mate

**Comment by Plaque-fcc** [comment]
And what? 

3 июня 2015 г. 14:24:48 EET, Yan Pashkovsky <notifications@github.com> пишет:
>Valve doesn't pficcialy support xfce and mate
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/steam-for-linux/issues/1025#issuecomment-108311999

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by Yanpas** [comment]
Isn't it DE specific?

**Comment by Enverex** [comment]
Not really. It basically affects every desktop environment EXCEPT Gnome. This is because it's not honouring X standards (which exist specifically to avoid problems like this).

**Comment by Celexi** [comment]
I am using gnome in fedora and i am fairly sure it also affects gnome, sure the window gets thrown into activities if you don't have a dock or window list, but if you have those it doesn't and you have the tray ( gnome has an icon tray again ) and the window icon in dock or window list.
basically this affects any desktop environment.

**Comment by fishxz** [comment]
it also affects gnome for sure.

**Comment by Foggalong** [comment]
+1 for XFCE. I would love this feature

**Comment by elm0829** [comment]
+1 for Cinnamon and MATE

**Comment by Zer0t3ch** [comment]
This shouldn't be specific to any WM or DE.

**Comment by Xaekai** [comment]
>this has been open since Jan 2013
>still not fixed

Ok, I get that it's not possible to autodetect whether "app indicators" actually work or not, but that doesn't excuse the lack of UI option to specify that "Yes, I'm one of the 90% of Linux users not using your specific target distro/DE and yes app indicators work on my particular DE"

**Comment by cjwijtmans** [comment]
could you please make this default behavior? It works on ubuntu right? And you are targeting ubuntu. For people where it DOESNT work they could do STEAM_FRAME_FORCE_CLOSE=0

**Comment by david0rk** [comment]
+WORKAROUND/FIX FOR XFCE++
I've worked out a pretty simple fix for xfce, all it requires is installing devilspie



create the file ~/.devilspie/steamfix.ds
and paste the following in the file
```
; generated_rule steam fix
( if 
( begin 
( is ( window_name ) "Steam" )
) 
( begin 
( skip_pager )
( skip_tasklist )
( println "match" )
)
)
```
In xfce open  Settings Manager > Window Manager Tweaks > Cycling tab and look for this option Skip windows that have "skip pager" or "skip taskbar" properties set.
add devilspie to your session autostart in xfce, problem solved.

**Comment by nmschulte** [comment]
Bump!  So, @gdrewb-valve, has Unity resolved its problems yet?  3.5+ years later and Debian still works properly in this regard, but this issue remains, and the chatter is becoming nonsensical.

When can we expect things to work as they ought?

**Comment by gdrewb-valve** [comment]
The Steam team will post here when they have an update.  I have no idea when or if they'll have something.

**Comment by MattSturgeon** [comment]
Setting `STEAM_FRAME_FORCE_CLOSE=1` in my `/etc/environment` is working well for gnome-shell on Fedora 24 and Arch. (I have steam autostarting with `steam -silent` on my Arch machine)

I appreciate you at least having the option available via an environment variable.

------------------------

I think it makes sense to have this option integrated into the Settings menu, many apps have a "Close to tray" checkbox. This also means users having issues can disable closing to systray, while the vast majority for whom it "just works" can have it set to their preference.

IMO this would mitigate most arguments for not closing to tray by default.

-----------

This is probably a desirable settings option for all platforms with a systray though, not just linux; perhaps I should make a separate issue?

**Comment by sharifzadesina** [comment]
Why always everyone works so slow for Linux?
How many years should pass for fixing this small bug?
If you need money so say it...!

**Comment by n1trux** [comment]
I think Valve has enough money, SteamOS just isn't their main product. They rather develop features which actually net them money and fixing minor issues doesn't. As much as I love Linux, it's still a pretty niche system to see on desktops and especially gaming PCs.

**Comment by elm0829** [comment]
Depends on the distro and wm.

**Comment by sharifzadesina** [comment]
@elm0829 what? this issue?

**Comment by elm0829** [comment]
Yes, the close to tray works on some setups but not on others. On Arch with Gnome or bspwm. I've had issues with Debian based systems.

**Comment by david0rk** [comment]
close to tray sort of works in xubuntu 16.04.  The window disappears and the tray icon is visible, however steam still shows in the tasklist (as if it were minimized) 
I think the issue is how the window manager is handling the window.   
Valve settled on ubuntu as it is one of the more popular distros and generally compatible with most derivatives with minor issues, Unfortunately this issue i think will persist for anyone using a WM that doesn't handle windows like gnome/unity.

**Comment by sharifzadesina** [comment]
@elm0829 there is no close to tray which one you are speacking about? unofficial `STEAM_FRAME_FORCE_CLOSE` variable?
and also there is libraries for this which supports all distributions and desktop environments.

**Comment by sharifzadesina** [comment]
Anyway we have to wait an other 3 year for this small and important issue, I think.

**Comment by elm0829** [comment]
Well, this repo isn't steamos, just the Linux client, so they can't patch it. It depends on the wm mostly. Some distros can dictate how the wm behaves, but for the most part it is up to the wm.

**Comment by sharifzadesina** [comment]
Yes, I have said it, because this isn't for steamOS, We MUST wait an other 3 years...
I am not here for trolling just I am here for reminding.

**Comment by elm0829** [comment]
Time isn't the factor here. It's the wm. Use a different wm that is compatible and it'll work fine.

A wm it's not going to change it's functionality for one program.

**Comment by sharifzadesina** [comment]
@elm0829 Time isn't the factor? lol, so I hope my grandsons can enjoy steam's close on tray feature :D
What is the wm you are speaking about?

**Comment by elm0829** [comment]
Won't happen.

Wm is window manager. Essentially how the os controls how Windows are displayed and their functionality. 

https://wiki.archlinux.org/index.php/window_manager

So something like wayland. Valve can try to engineer their client to behave as suggested in this thread on Eastland, but they won't. It's not worth the effort for something that hypothetical.

If you want that functionality, you need to use a different Wm. Many of the options are in the link I mentioned.

**Comment by elm0829** [comment]
Wayland. Not Eastland ^

**Comment by jhasse** [comment]
This issue is essentially: The close button and the minimize button do the same thing. With *every* window manager.

**Comment by elm0829** [comment]
That isn't true though. I believe it was xfcwm that I've used in the past and had no issue.

**Comment by nmschulte-aviture** [comment]
> This issue is essentially: The close button and the minimize button do the same thing. With every window manager.

No, that is not this issue.  This is is this issue:

> Ah, I see, you don't want even the minimized form of the window. **We deliberately switched the close box to minimize because of the number of people where the app indicator didn't work.** If the window actually closes and there is no app indicator there's no UI at all for Steam even though it's still running, so we switched to minimizing. Unfortunately there's no way to know if app indicators are working (presence/absence is not sufficient as even if they're present they do not always work). Our hope is that the problems there will get worked out and then we can remove our workarounds and rely on the app indicator, at which point closing the window will close it.

Valve has made "close" == "minimize," to "accommodate" a (very, very, long standing, apparently)  bug in Unity, their "userbase of choice."  I say apparently, because I just assume it hasn't actually been fixed, and Valve is holding on to their "fix" because of it.

**Comment by elm0829** [comment]
"Unfortunately there's no way to know if app indicators are working (presence/absence is not sufficient as even if they're present they do not always work)."

So exactly as I said. Valve can't control it, the Wm does.

And no, unity is a desktop environment, not a Wm. So again, those indicators depend on the Wm.

**Comment by nmschulte-aviture** [comment]
> So exactly as I said. Valve can't control it, the Wm does.

I guess we're talking about two different "Its" then.  The "it" I'm referring to, and what this issue is about (as Valve has even clarified, as per my last reply), is that Steam treats "close" like "minimize."  If it would just treat "close" like "close," those with software compliant to the spec would have the expected behavior.  ("close" closes the window).

Valve can't control defects in Unity/Metacity/Compiz/..., sure, but they can control whether or not they let those defects cripple the functionality for everyone.  This issue is going to be turning four years old in January.  :birthday:

**Comment by sharifzadesina** [comment]
@elm0829 I didn't thought you mean WM = Windows Manager!!! dude It is not cause of windows managers system tray is an special feature for desktop environments. WM is just an API for drawing not for controlling. for example all of the steam's tray icon's menu buttons are made with GTK2...

**Comment by elm0829** [comment]
WM is not an API. And it is for control. The DE draws, while the WM controls behavior.

How is GTK+ relevant? GTK+ doesn't change functionality, just appearance...

**Comment by sharifzadesina** [comment]
@elm0829 You are right, I confused with display servers...

**Comment by nmschulte-aviture** [comment]
> This issue is going to be turning four years old in January.

@gdrewb-valve -- This issue has been rolling around for 4 years now; do the issues Valve/Steam was running up against w/ Ubuntu/Unity users and app indicators still apply, or can we remove the `STEAM_FRAME_FORCE_CLOSE` environment variable workaround and make it permanent/default?

**Comment by gdrewb-valve** [comment]
That's up to the Steam team to decide, if they change anything they'll update this issue.

**Comment by alemansec** [comment]
**STEAM_FRAME_FORCE_CLOSE=1** env var does not fix it :

$ env|grep STEAM
STEAM_FRAME_FORCE_CLOSE=1

$ steam

wait for it ...
click the close (x) icon

wait ...
keep waiting ...

steam still running minimized...
(stdout|stderr did not even notice the click event or at least shows nothing)


hitting the close button does nothing but minimize the steam client.

**Comment by nmschulte** [comment]
> steam still running minimized...

As in, Steam still shows in the task panel?  If Steam stays in the tray, but the window closes, then the environment variable is working as intended.  It's not supposed to exit Steam, just close the window.

I just want to clarify, as those details got lost along the way to now somehow (at least that's my understanding from grok'ing the thread).

**Comment by alemansec** [comment]
Steam client **minimizes when hitting the close icon**, with the env var set, but **this is ACTUALLY A PROBLEM** to me, that's why i opened a issue related to this : issue #4772

in a few words : "**close button**" in title bar **should actually close** the application, **not minimize** it ; the minimize icon was MADE FOR THIS SOLE PURPOSE.

Have a look at issue #4772 for details (marked as duplicate by error)

Someone marked it as a duplicate of this issue, hence my comment here (although it's clearly not a duplicate issue).

**Comment by nmschulte** [comment]
I agree, your concern is not a duplicate.  This issue is to deal w/ close not closing; the env var workaround should work.

**Comment by LiamDawe** [comment]
The latest Steam Beta Client has fixed this for me, great job Valve.

**Comment by sharifzadesina** [comment]
@LiamDawe Does closing from DesktopEnvironment  also work?

**Comment by kisak-valve** [comment]
Closing per "Unify close-to-tray behavior with other platforms. If using a distribution that doesn't have proper compatible tray support, use STEAM_FRAME_FORCE_CLOSE=0" in the [2017-01-05 steam beta client update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256).

**Comment by jchevarley** [comment]
Not sure if I should reopen this, but using the Latest KDE/Plasma release (including frameworks/etc), the latest beta still needs export STEAM_FRAME_FORCE_CLOSE=1 to close to tray, and, now neither right or left clicking on the icon after it minimizes does anything. Before, left clicking did nothing, but right clicking at least brought up the menu where I could open my library.

**Comment by Hi-Angel** [comment]
How funny that I came here for quite the reverse problem. So, what option should I check to minimize steam into tray upon closing the window?

**Comment by sharifzadesina** [comment]
This doesn't work when you are closing steam from Gnome, you have to just click on X button.

**Comment by Hi-Angel** [comment]
@sharifzadesina wait, isn't this whole bugreport, that said to be fixed, was about exiting upon pressing "X button"?

**Comment by sharifzadesina** [comment]
@Hi-Angel I didn't reply to you, I have just reported a bug :D

**Comment by Hi-Angel** [comment]
Anyway, I have to say steam behavior seems to be broken, beacuse there's no way to minimize it to tray at all. Upon closing window it exits. Upon pressing the tray icon it shows a menu. The menu have also no an option to minimize to tray.

**Comment by tengwar** [comment]
@Hi-Angel It should close to tray when you click the main window's "x" button. If that doesn't work then something is wrong. Is your steam fully updated? What DE are you using?

**Comment by Hi-Angel** [comment]
@tengwar I have neither DE nor a bar with "x" button upon windows — I'm using a tiling WM, i3. To close steam I simply press the closing hotkey.

**Comment by nmschulte** [comment]
@Hi-Angel, using i3's `kill` command and the latest Steam beta, Steam "closes" to the tray (in `i3bar`).  Left or right clicking on the tray icon opens the menu.  Choosing "exit" from that menu or Steam's main menu exists steam.

**Comment by Hi-Angel** [comment]
@nmschulte weird, for me i3's `kill` command closes steam completely. Upon opening from terminal, last steam words after I pressed the hotkey:

	Refresh rate: 1
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	Refresh rate: 1                                                                                             
	[2017-01-28 20:55:12] Startup - updater built Jan 19 2017 01:22:13                                          
	[2017-01-28 20:55:13] Проверка установки...                                                                 
	[2017-01-28 20:55:13] Verification complete                                                                 
	Unable to remove /home/constantine/.local/share/Steam/CONFIG/SteamAppData.vdf!                              
																												
	[2017-01-28 20:55:28] Shutdown                                                                              

i3 version 4.13 here.

**Comment by nmschulte** [comment]
I would open a new bug report w/ your details, then.  I am running on Debian (unstable) with a build of the latest `next` of i3.

**Comment by Hi-Angel** [comment]
@nmschulte nah, I can't. I'm on Archlinux, it's unsupported.

**Comment by Hi-Angel** [comment]
@nmschulte anyway, could you post output of `i3 --version`, please?

**Comment by nmschulte** [comment]
@Hi-Angel oh, I didn't realize that mattered. :neutral_face:  You could try reproducing it on Debian or Ubuntu.  ArchLinux is fairly similar, anyway.

```$ i3 --version
i3 version 4.13-35-gd4066a6c (2017-01-10, branch "next") © 2009 Michael Stapelberg and contributors```

**Comment by Hi-Angel** [comment]
@nmschulte well, having another distro doesn't mean I can't make [a generic feature](https://github.com/ValveSoftware/steam-for-linux/issues/4836) request ;)

**Comment by nmschulte-aviture** [comment]
@Hi-Angel, Brilliant!

**Comment by nmschulte** [comment]
@Hi-Angel, brilliant!

**Comment by ryleestatler** [comment]
This is still an issue on Linux Mint 22.3 - Cinnamon 64-bit

**Comment by LuigiKraken** [comment]
Steam is one of the most user-respecting platforms in the industry and generous refunds, Proton, the Deck, all of it. Which makes this one missing toggle so much more glaring. Every other application on my Linux desktop closes when I click the close button, because that's what the close button means Those that dont I dont use... Steam is the lone exception, and there isn't even a setting to opt out of it.

 Instead of closing, X minimizes to the tray, and to actually quit I have to dig into a menu or right-click the tray icon. That's an extra deliberate step, every single time, to do the one thing the button I just pressed is universally understood to do. STEAM_FRAME_FORCE_CLOSE=1 is unreliable on the current client, so there is currently no dependable way to get this behavior.
  
 This isn't a feature request for something complex. It's a single checkbox: "Close button exits Steam." Default it to the current behavior if you must, just give those of us who don't want a background process the choice. Respecting the user means respecting the close button.
