### ISSUE TITLE
Games crash if you invite friends via steam

### ISSUE THREAD

**Issue by damnkrat** [ValveSoftware/steam-for-linux#10257]
#### System information

* Steam client version (build number): 1700867040
* Distribution: Manjaro KDE
* Opted into Steam client beta?: Yes (but it happens whether it's beta or not)
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13487211/steam-logs.tar.gz)
* GPU: Nvidia RTX 3060

#### Please describe your issue in as much detail as possible:
Games crash on friend connecting if you invite friends via steam. It happens in many games like forts or 7 days to die (both native and proton). In forts, it happens even if you don't invite your friends, but open a server and someone comes in.

But it does not happen in CS 2. Also, it doesn't happen if friends connect to your pc via steam remote play in for example rounds

#### Steps for reproducing this issue:

1. Open game
2. Start world(or something)
3. Invite friend
4. Game crash on friend join

**Comment by damnkrat** [comment]
Fixed

**Comment by Jelly505** [comment]
How do you fixed it?

**Comment by damnkrat** [comment]
I don't know. It was just fixed in one of updates
