### ISSUE TITLE
[Steam Deck] Library navigation issue

### ISSUE THREAD

**Issue by KoreshKrasa** [ValveSoftware/steam-for-linux#10253]
#### Your system information

* Steam client version (build number or date): 1700867040
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
When navigation out from game page in library if B button quickly tapped then user is navigated to first tab of the library (Great on Deck) even if game page was opened from Installed tab. If B button is held then user return to correct page (Installed in my example)

#### Steps for reproducing this issue:

1. Open any tab that is not Great on Deck in library (e.g. Installed) 
2. Open any game page
3. Quickly tap B button
4. User navigated to Great on Deck tab instead of previously opened tab

**Comment by thorstenhirsch** [comment]
Also see #9640.

**Comment by houldsg** [comment]
I'm having the same issue as @Sterophonick. Multiple back button presses are required almost every time I'm done playing a game. It still works but it makes you doubt your sanity every once in a while. 

This is a new steam os install as of two weeks ago, using the restore image from valve's site.

**Comment by Managor** [comment]
This has been fixed in the latest beta.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where after playing a game it would require extra B button presses to back out of the game's library page." in the [2024-05-07](https://store.steampowered.com/news/app/1675200/view/4202497395530274132) Steam Deck client update.
