### ISSUE TITLE
Steam Deck / BPM: Allow Creators of Community Uploaded Controller Layouts to update existing Layouts.

### ISSUE THREAD

**Issue by YoreonX** [ValveSoftware/steam-for-linux#10260]
There are many instances I can think of where, something could be improved or maybe a Typo was made in the description.. 

It can be a little tedious & time consuming to start reuploading a new layout that's only slightly tweaked than the old one from scratch; while retyping the same name & deleting the old layout.

Would be great if an additional option appeared after clicking "Share with Community" maybe above "Layout Title", with "Update"(kinda like how Action Layers allows you to select which Action layer you want to copy, for the new layer) and you pick the existing layout for Steam ID(Game.exe).

It carries the original name and description, and it should probably notify existing users if they want to override their current layout with the new layout.

**Comment by kisak-valve** [comment]
Hello @YoreonX, this issue is already being tracked at #9440. Closing as a duplicate.
