### ISSUE TITLE
Beta 1701825895 hangs on steam deck

### ISSUE THREAD

**Issue by jbbandos** [ValveSoftware/steam-for-linux#10278]
#### Your system information

* Steam client version (build number or date):  1701825895
* Distribution (e.g. Ubuntu):  SteamOS 3.5.9 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal ``tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13577240/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Updated steam client, and the deck hangs after restarting. Was able to use the steam menu, power, then enter desktop mode. Steam client still hangs, but the rest works.
Launching with "steam -clearbeta" reverts to stable client and it works. Selecting again the "steam deck beta" channel, updating to the latest beta, and the hang is back.

#### Steps for reproducing this issue:

1. open the steam client
2. Select settings->interface->client beta participation->"Steam deck beta"
3.  Update the client and restart it
4.  Wait for it to show the library (hangs here)

**Comment by Tau5** [comment]
Can replicate on Steam Deck Preview Channel

**Comment by SaschaVasarrhelyi** [comment]
I am on Ubuntu-Mate 22.04LTS with the Steam- Beta Client and it hangs to in my System. The Library can not load (Steam hangs on Loadingscreen for the Library since the new Update from Steam-Beta-Client.

**Comment by devarionarias** [comment]
The latest patch today has fixed this issue for me. I'm in the preview channel (build 20231206.1).

**Comment by jbbandos** [comment]
Seems to be fixed on version 1702079146. Loads without issues both on gaming and desktop modes on the steam deck.

**Comment by kisak-valve** [comment]
Closing as fixed.
