### ISSUE TITLE
Unable to Watch Videos on Firefox Stating Steam Client is Outdated

### ISSUE THREAD

**Issue by Toasted-Meat** [ValveSoftware/steam-for-linux#10275]
#### Your system information

* Steam client version (build number or date): 1701289036 (Wed, Nov 29 11:59 AM UTC -08:00)
* Distribution (e.g. Ubuntu): Linux Mint 20.3 64-bit Cinnamon (Kernel 5.15.0-89-generic)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: https://mega.nz/file/FY5nSRSQ#df83VVTCrbN4XqawvakMaoPlDnFpTfoyXHI-7k3ButY
* GPU: AMD Radeon RX 5700 XT
* Firefox Version: 120.0.1

#### Please describe your issue in as much detail as possible:
I expected to be able to watch the video either in Firefox or in the Steam client but I was met with the message in Firefox that Steam is outdated. I'm not sure if this is an issue with Firefox or Steam.

#### Steps for reproducing this issue:

1. Press Play for Papers, Please - The Short Film
2. Authenticate Steam in Firefox through QR Code in iOS Steam App
3. Redirected to page stating Steam is outdated and must be updated in order to watch the video

**Comment by kisak-valve** [comment]
Hello @Toasted-Meat, you've described a general website issue instead of a Steam for Linux client issue. Please report this issue to [Steam Support](https://help.steampowered.com).

Closing as out of scope for this issue tracker.
