### ISSUE TITLE
Steam Hardware Survey Inaccuracies

### ISSUE THREAD

**Issue by JonStarritt** [ValveSoftware/steam-for-linux#10276]
#### Your system information
https://gist.github.com/JonStarritt/760741defe32c5cda004d1c4ffc455c3.js

* Steam client version (build number or date): Steam Version:  1701289036
                                                                         Steam Client Build Date:  Wed, Nov 29 14:59 UTC -05:00
                                                                         Steam Web Build Date:  Wed, Nov 29 14:03 UTC -05:00
                                                                         Steam API Version:  SteamClient021
* Distribution (e.g. Ubuntu): Mint 20.3 using kernel 5.15.0-89-generic, with the Xfce desktop.
* Opted into Steam client beta?: [Yes/No] No.
* Have you checked for system updates?: [Yes/No] Yes.
* Steam Logs: Not applicable for this issue.
* GPU: AMD R9 380.

#### Please describe your issue in as much detail as possible: Copied from my forum post on December 2, 2023 so I don't have to type it all again: Today's hardware survey has some inaccuracies I would like to address. Under the hard-drive section the survey thinks I have five (5) SSDs installed. In reality I only have one (1) SSD and three (3) HDDs. I have one (1) SSD at 1TB, one HDD (1) at 12TB, one HDD (1) at 4TB, and one HDD (1) at 2TB. The SSD with my OS does have two (2) partitions, one for the kernel and one for my home directory, which could be read by the survey as two (2) separate disks.

According to the response from Steam Support: "At the moment, Steam for Linux is currently only supported on the latest version of 64-bit Ubuntu LTS with Unity, Gnome, or KDE desktops. Since you are running another distribution of Linux, we will not be able to troubleshoot or assist you with the issue. We recommend you install the latest version of 64-bit Ubuntu for the best Steam experience on Linux." That sounds good for an AI generated response, however it doesn't address the issue with the survey.

As I understand Linux Mint is built on top of Ubuntu while removing the Canonical telemetry. I do still download and install Debian packages as anyone on Ubuntu would. My Steam client was installed from a Debian package. As far as hardware reporting, the desktop environment shouldn't make a difference. Using "lsblk" reports the correct disk information to the terminal, and it's built-in. Could they just use that on systems detected as Linux? 

To be clear, I have no issues with running Steam or playing any games on my system. I made the forum post and contacted support so they would be aware the survey is collecting inaccurate data from their users. I know I'm not the only one running a Linux distro other than the one (1) suggested by the support response. Does this mean survey responses from distros other than the one suggested are not parsed for their data? Or are they parsed and inaccurate information is entered into their hardware tracking system? Either way would be a nightmare for developers as they would be making decisions based on inaccurate information. I know their job is hard enough working on Half Life 3, no need to make it any more difficult.

I will gladly take their survey and report any inaccuracies as many times as they send it to me through Steam.

#### Steps for reproducing this issue:

1. Click the button on the Hardware Survey
2. OR Click "Help" then "System Information" at the top of the Steam client
3.

**Comment by kisak-valve** [comment]
Hello @JonStarritt, this issue is already being tracked at #8966. Closing as a duplicate.

> Does this mean survey responses from distros other than the one suggested are not parsed for their data?

https://store.steampowered.com/hwsurvey/?platform=linux, select the Linux Version section and that'll show a variety of distros.
