### ISSUE TITLE
Steam downloading Windows version of Starbound instead of Linux version

### ISSUE THREAD

**Issue by lotigara** [ValveSoftware/steam-for-linux#10279]
#### Your system information

* Steam client version (build number): 1701289036
* Distribution: Artix GNU/Linux-zen 64bit with Arch repos
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13578720/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I use Artix GNU/Linux-zen, the Steam client is installed from Arch Linux repositories. I turned on Steam Play for Starbound once to see if the game would run better through Proton than the Linux version. Now I want to turn off this feature (after installing the Windows version, the Linux version was deleted), but when reinstalling the game (in the sense, uninstall and reinstall. I also tried to delete the Starbound files for Windows manually and then fix the Starbound installation) the Windows version is downloaded anyway. How do I get the Linux version back? 
#### Steps for reproducing this issue:

1. Install Starbound
2. Enable Steam Play for Starbound
3. Reinstall the game with disabling Steam Play

**Comment by lotigara** [comment]
I'm sorry, my English is very bad!

**Comment by kisak-valve** [comment]
Hello @lotigara, this issue is already being tracked at #9875. Closing as a duplicate.
