### ISSUE TITLE
Add an option to "never update" a game

### ISSUE THREAD

**Issue by ralgar** [ValveSoftware/steam-for-linux#10284]
This isn't a Linux-specific issue, more of a general QoL feature request that I didn't know where else to post.

## The Issue

As many people know, Skyrim SE was recently updated again - an update that nobody asked for, almost solely for the purpose of attempting to shoehorn pay-to-play mods into the game. The immediate effect is that anyone with a noteworthy mod list has been left with a broken game *again*, and the need to somehow downgrade their game files *again*.

I know there are a variety of ways available to downgrade/restore the game files (filesystem snapshots, depot downloads, etc), but that doesn't make it any less inconvenient. Not only do we have to manage downgrading/restoring the game files, but we also have to run Steam in Offline Mode any time we want to play - to prevent it updating again.

This is such a common problem for the community that "downgrade patchers" had to be created for the game, which frankly is an insane solution to a problem that should simply be resolved at the source.

Of course, some less technically inclined users find any method of downgrading the game to be rather difficult. There are countless help requests on various community social platforms at the moment.

This is probably *the* single most frustrating issue with modding Steam games. For those of us with limited time available for gaming, it often results in us choosing not to play the game at all - which is completely unacceptable.

## Proposal

I would propose that a new option is added to the per-game update settings in Steam - a "never update this game" option. IMHO, this is an important QoL feature for any moddable, single-player/co-op game.

Hopefully there aren't any logistical blockers to this. I would like to think that multiplayer game servers already have some baked-in ability to reject out-of-date clients, in case this feature is incorrectly used.

If you wanted to go *even further* with this feature, I'm sure users would also welcome the ability to select the specific build/version of the game they'd like to have installed.

## Other games that would benefit from this

- **The Witcher 3:** Another modder's favorite that is currently receiving semi-regular updates.
- **Cyberpunk 2077:** Another hot game for modding, which recently received a major update.
- **Baldur's Gate 3:** Rapidly climbing the charts on Nexus Mods, likely to continue receiving regular updates and new content.
- **Starfield:** Same as above. Will almost certainly end up suffering the same issues as Skyrim.

And probably others that I'm not aware of...

**Comment by kisak-valve** [comment]
Hello @ralgar, this was previously requested at #8711 and the response at https://github.com/ValveSoftware/steam-for-linux/issues/8711#issuecomment-1197050595 is equally valid today as it was back then.

**Comment by ralgar** [comment]
Thanks for the reply @kisak-valve, and my apologies for not noticing the original issue.

I will respect Valve's decision, whatever it be, but I can't say I agree with the validity of your reasoning. I hope you'll at least consider raising these concerns internally.

1. We're not asking you to take *anything* away from developers. The fact is that what we're asking for (the ability to defer updates) is *already* possible. All we're asking for is a more convenient switch.
2. I would like to point out that both of your noteworthy competitors (GoG and EGS) offer the ability to control/defer updates in some manner. Clearly it isn't a show-stopping issue for developers.
3. Asking users to back up hundreds of gigabytes of content from multiple games is the single worst UX suggestion I've ever heard. Snapshots can help with this, but are still a pain and are beyond the technical skills of most users.
4. There are valid reasons for this aside from modding. For example - BG3 has had a couple of regressive patches, the most recent of which causes my (unmodded) game to consistently crash at the main menu with both renderers. Would you suggest that all users keep a full backup of their library, just in case of developer screw-ups?
5. How do you suggest we handle this on Steam Deck? The device doesn't exactly have extra space for backups, and doesn't support snapshots on the internal storage.
