### ISSUE TITLE
CS2 | Matchmaking Failed VAC was unable to verify your game session 

### ISSUE THREAD

**Issue by spikederailed** [ValveSoftware/steam-for-linux#10289]
#### Your system information

* Steam client version (build number or date):  1702079146
* Distribution (e.g. Ubuntu):  Kubuntu 23.10
* Opted into Steam client beta?: [Yes/No]  Tried Regular and Beta
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13642421/steam-logs.tar.gz)`]
* GPU: Nvidia/Intel/AMD: Nvidia 3080 driver 535.129.03

#### Please describe your issue in as much detail as possible:
[systemctl_services.txt](https://github.com/ValveSoftware/steam-for-linux/files/13642446/systemctl_services.txt)
[steam_runtime_system_information.txt](https://github.com/ValveSoftware/steam-for-linux/files/13642447/steam_runtime_system_information.txt)
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13642448/steam-logs.tar.gz)
o verify your game session."
![Screenshot_20231210_115129](https://github.com/ValveSoftware/steam-for-linux/assets/130270404/e929c9e5-750e-4764-ac9b-ee00db59faea)

As of last tuesday night I have started receiving
"Matchmaking Failed VAC was unable to verify your game session."

Was able to play tuesday afternoon(Dec 5, 2023) as I did not get hit with the false ban wave. Had to restart the game as I do every 2-3 casual rounds because of the over 44khz audio desync bug. Closed the game and restarted it and was no longer able to play anymore getting the error above.

"Matchmaking Failed VAC was unable to verify your game session."

This is the linux native build of CS2, not the windows build being run through proton. 

System is...
Kubuntu 23.10(kernel 6.5.0-14)
Asus X570 Tuf Gaming Wifi
Nvidia 3080; using NVidia 535.129.03 drivers
X11 Windowing system
KDE Plasma 5.27.8
Pipewire audio
Steam is installed from the .deb file from the website

System is patched fully against whats in the canonical repos. There were no changes on my system between being able to play and not play, was literally close the game and reopen to no long being able to play.

I have no cheat software and never have, i have no overlays running, the only changes to the NVidia control panel is manual fan control.

I have restarted the computer multiple times
Verified game files(no problems found)
Uninstalled CS2 cleared all files related to app id 730 from the ~/%myuser%/.steam folder, then reinstalled CS2.
Ran "steam --reset" from terminal
Installed steam as a flakpak and then CS2 from there.
Removed all launch options from CS2 and have no autoexec.cfg to speak of.
Played a COMP round of just bots.

All of which have still resulted in the vac unable to verify game session.

My computer does have KVM/QEMU and VMware installed, but neither of which are running and to make sure that neither of those were effecting it I stopped the services through systemctl

systemctl stop libvirtd.service
systemctl stop libvirt-guests.service
systemctl stop qemu-kvm.service
systemctl stop vmware.service

Still unable to get a VAC game.

The only thing I have not tried is uninstalling all of my games and steam itself then deleting the entire ~/%myuser%/.steam folder before reinstalling. I can as a troubleshooting step if necessary its just ~1TB of games installed to redownload.

I have included a screenshot of the error, a .txt file of the systemctl services as they are THIS SECOND(though in the past the kvm/qemu services were stopped, and the steam runtime system information. Can provide any other diagnostic information as requested.

Really at a loss as to what would be cause this and need some guidance. 

#### Steps for reproducing this issue:

1. Start game and attempt to connect to and vac secured server 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @spikederailed, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3589.

Closing as a duplicate.
