### ISSUE TITLE
CS2GO fullscreen mode not covering kde panels

### ISSUE THREAD

**Issue by luizluca** [ValveSoftware/steam-for-linux#10282]
#### Your system information

Steam Version:  1701289036
Steam Client Build Date:  Wed, Nov 29 4:59 PM UTC -03:00
Steam Web Build Date:  Wed, Nov 29 4:03 PM UTC -03:00
Steam API Version:  SteamClient021

* Steam client version (build number or date): 1701289036
* Distribution (e.g. Ubuntu): Ubuntu 23.10 running KDE
* Opted into Steam client beta?: [Yes/No] ?
* Have you checked for system updates?: [Yes/No] Yes, just qemu updates are missing.
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

When I use Fullscreen mode in CS2GO, it does not cover the KDE panels. It used to cover after the first Linux version was launched but now it does not.

If I change anything in the game display settings that reloads the screen, it will correctly cover the panel even if I undo the change. Another workaround is to switch to "Fullscreen Windowed", which solves the issue "permanently", even after I restart the game. I can also manually ask KDE to keep CS2GO windows on top of all other windows, which does make it cover the panels but kind of break the alt+tab usage.

This is how the game is after it is started with fullscreen mode:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/836788/f0c08cf3-51c0-48a5-b6fa-3e05fd58e9af)

#### Steps for reproducing this issue:

1. Use KDE in ubuntu 23.10
2. Set CS2GO to fullscreen
3. Close the game and start it again

**Comment by kisak-valve** [comment]
Hello @luizluca, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3454.

Closing as a duplicate.
