### ISSUE TITLE
Entering Big Picture Mode hangs Steam

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10293]
#### Your system information

* Steam client version: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/adb14945-8cae-44dd-a79d-b1f6baa2ed5d)
* Distribution: Arch Linux Plasma Wayland, SteamOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13664384/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/2MeKETD1DBE
When I try to open BPM, steam goes completely blank. No window pops up. The taskbar applet responds as expected but it is no longer able to invoke the steam window even after exiting BPM

#### Steps for reproducing this issue:

1. Open Big Picture Mode

**Comment by Managor** [comment]
And this is fixed in the latest beta.

**Comment by kisak-valve** [comment]
Closing per the last comment.
