### ISSUE TITLE
Steam infinitely loads nothing after opening.

### ISSUE THREAD

**Issue by Sectonidse** [ValveSoftware/steam-for-linux#10299]
#### Your system information

* Steam client version (build number or date): 1702079146
* Distribution (e.g. Ubuntu): Linux Mint 21.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13692752/steam-logs.tar.gz)
* GPU: Nvidia
* CPU: Intel

#### Please describe your issue in as much detail as possible:
When you open Steam, it loads like usual, then it open the login window. After few seconds it seemingly opens Steam window(?) 
but it doesn't load anything (as i see that the loading animation is smooth, usually when it loads something it kinda misses some frames.

Video showing this: [YouTube](https://www.youtube.com/watch?v=ytuw0Gsp1X0) (The comments and likes are turned off by me, not YouTube.)

#### Steps for reproducing this issue:

1. Open Steam with Internet on
2. that's literally it

**Comment by ipiepiepie** [comment]
Same on Fedora 39

**Comment by kisak-valve** [comment]
Hello @ipiepiepie, this issue is already being tracked at #10297. Closing as a duplicate.
