### ISSUE TITLE
Steam Crashes on Launch Manjaro Linu

### ISSUE THREAD

**Issue by SonicSaberYT** [ValveSoftware/steam-for-linux#10303]
#### Your system information

Steam client version (1.0.0.75-4): 
Manjaro
No
* Have you checked for system updates?: [Yes]
* Steam Logs:/home/stephen/.steam/steam/logs/
/home/stephen/.steam/steam/logs/console_log.previous.txt
/home/stephen/.steam/steam/logs/remote_connections.txt
/home/stephen/.steam/steam/logs/cloud_log.txt
/home/stephen/.steam/steam/logs/systemperfmanager.txt
/home/stephen/.steam/steam/logs/cef_log.txt
/home/stephen/.steam/steam/logs/timedtrial_log.txt
/home/stephen/.steam/steam/logs/appinfo_log.txt
/home/stephen/.steam/steam/logs/steamui_update.txt
/home/stephen/.steam/steam/logs/text_filter_log.txt
/home/stephen/.steam/steam/logs/shader_log.txt
/home/stephen/.steam/steam/logs/appinfo_log.previous.txt
/home/stephen/.steam/steam/logs/cef_log.previous.txt
/home/stephen/.steam/steam/logs/systemaudiomanager.txt
/home/stephen/.steam/steam/logs/cloud_log.previous.txt
/home/stephen/.steam/steam/logs/content_log.txt
/home/stephen/.steam/steam/logs/steamui_html.txt
/home/stephen/.steam/steam/logs/configstore_log.txt
/home/stephen/.steam/steam/logs/sitelicense_log.txt
/home/stephen/.steam/steam/logs/systemdockmanager.txt
/home/stephen/.steam/steam/logs/workshop_log.txt
/home/stephen/.steam/steam/logs/transport_client.txt
/home/stephen/.steam/steam/logs/bootstrap_log.txt
/home/stephen/.steam/steam/logs/webhelper.txt
/home/stephen/.steam/steam/logs/controller_ui.previous.txt
/home/stephen/.steam/steam/logs/compat_log.previous.txt
/home/stephen/.steam/steam/logs/stats_log.previous.txt
/home/stephen/.steam/steam/logs/configstore_log.previous.txt
/home/stephen/.steam/steam/logs/steamwebhelper.log
/home/stephen/.steam/steam/logs/stats_log.txt
/home/stephen/.steam/steam/logs/content_log.previous.txt
/home/stephen/.steam/steam/logs/steamui_audio.txt
/home/stephen/.steam/steam/logs/compat_log.txt
/home/stephen/.steam/steam/logs/systemmanager.txt
/home/stephen/.steam/steam/logs/transport_steamui.txt
/home/stephen/.steam/steam/logs/systemdisplaymanager.txt
/home/stephen/.steam/steam/logs/parental_log.txt
/home/stephen/.steam/steam/logs/connection_log_0.txt
/home/stephen/.steam/steam/logs/steamui_system.txt
/home/stephen/.steam/steam/logs/shader_log.previous.txt
/home/stephen/.steam/steam/logs/client_networkmanager.txt
/home/stephen/.steam/steam/logs/controller_ui.txt
/home/stephen/.steam/steam/logs/controller.txt
/home/stephen/.steam/steam/logs/connection_log.previous.txt
/home/stephen/.steam/steam/logs/console_log.txt
/home/stephen/.steam/steam/logs/connection_log.txt
/home/stephen/.steam/steam/logs/installscript_log.txt
/home/stephen/.steam/steam/logs/librarysharing_log.txt

* GPU: Nvidia GTX 1050
#### Please describe your issue in as much detail as possible:
No matter what fixes I've tried whenever I run Steam it silently crashes.
Steam logging initialized: directory: /home/stephen/.local/share/Steam/logs

/usr/share/themes/Matcha-dark-azul/gtk-2.0/main.rc:1113: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Matcha-dark-azul/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf6420dc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf641f500
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
crash_20231217215356_5.dmp[5124]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231217215356_5.dmp
/home/stephen/.local/share/Steam/steam.sh: line 798:  5100 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"

#### Steps for reproducing this issue:

1. Launch Steam

**Comment by boldviking** [comment]
I have the same error log

```
/usr/share/themes/Adwaita-dark/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Adwaita-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

Running Arch-Linux and an AMD Radeon RX 7900 XT

For reference everything else seems to be working fine, glxgears works, other games work, other launchers work. Just steam fails.

I tried downgrading the installed package, however that arch linux package is just a tiny shell, since the actual steam client updates itself during launch.

**Comment by kisak-valve** [comment]
Hello @SonicSaberYT, @boldviking, this reads like https://github.com/ValveSoftware/steam-for-linux/issues/10298#issuecomment-1858769500. Please verify that the 32 bit OpenGL render path works with something like `glxinfo32` from `lib32-mesa-utils` works and that your set of mesa system packages are approximately the same version.

**Comment by boldviking** [comment]
@kisak-valve yeah it seems there was an update to the arch linux package repositories for mesa 2h ago. Installing to `lib32-mesa-1:23.3.1-1` and `mesa-1:23.3.1-1` fixed the issue for me. 

I was going to downgrade my mesa libraries, but that does not seem to be required anymore ;). 

I did do a full system update before I posted, but it seems that the mirrors I used just did not have the required updates yet :D

**Comment by SonicSaberYT** [comment]
> lib32-mesa-1:23.3.1-1

Can confirm that manually updating the Mesa drivers through the Arch Archives solved the problem.

**Comment by SonicSaberYT** [comment]
Will leave this open for a few days in case this doesn't solve it for others

**Comment by kisak-valve** [comment]
Thanks for checking, that makes this a distro issue instead of a Steam issue. It would make more sense to report your findings to your distro's package maintainer(s) for mesa.
