### ISSUE TITLE
Steam Beta: Year in Review 2022/2023 Share > Save Image calls Open filepicker

### ISSUE THREAD

**Issue by DonKatsu** [ValveSoftware/steam-for-linux#10307]
#### Your system information

* Steam client version (build number or date): 1702667398
* Distribution (e.g. Ubuntu): Fedora 39 KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: RX 6700 XT

#### Please describe your issue in as much detail as possible:
Going to the Year in Review 2022/2023 page, clicking Share, then clicking Save Image on any of the formats calls an Open filepicker instead of a Save one.

#### Steps for reproducing this issue:

1. Go to either of those pages in Steam
2. Click Share button
3. Click Save Image button

**Comment by kisak-valve** [comment]
Hello @DonKatsu, this is the same issue as #6698. Closing in favor of the older issue report.
