### ISSUE TITLE
Ability to disable shader pre-caching for certain titles

### ISSUE THREAD

**Issue by AtFreezingPoint** [ValveSoftware/steam-for-linux#10302]
Ability to disable shader pre-caching manually for certain titles would be good to have, CS2 for example for some reason hangs at 0% and you have to disable shader pre-caching for all games to fix it (That deletes all pre-cached stuff, good luck & have fun re-caching)

**Comment by kisak-valve** [comment]
Hello @AtFreezingPoint, this issue is already being tracked at #6486. Closing as a duplicate.
