### ISSUE TITLE
Torchlight II/ModLauncher.bin.x86_64: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

### ISSUE THREAD

**Issue by als-creator** [ValveSoftware/steam-for-linux#10310]
Steam logging initialized: directory: /home/als/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xeb57fdc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xeb57e500
steamwebhelper.sh[91061]: Runtime for steamwebhelper: defaulting to /home/als/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[91061]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 91160
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
CAppInfoCacheReadFromDiskThread took 1017 milliseconds to initialize
/usr/share/themes/Arc-Dark/gtk-2.0/main.rc:1090: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Arc-Dark/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
BRefreshApplicationsInLibrary 1: 6ms
BuildCompleteAppOverviewChange: 3049 apps
RegisterForAppOverview 1: 912ms
RegisterForAppOverview 2: 917ms
/bin/sh\0-c\0/home/als/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=200710 -- /home/als/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64'\0
chdir "/mnt/Work/Games/Steam/steamapps/common/Torchlight II"
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
Uploaded AppInterfaceStats to Steam
/bin/sh\0-c\0/home/als/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=200710 -- /home/als/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64'\0
chdir "/mnt/Work/Games/Steam/steamapps/common/Torchlight II"
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
Uploaded AppInterfaceStats to Steam
[2023-12-22 00:31:24] Background update loop checking for update. . .
[2023-12-22 00:31:24] Проверка на наличие обновлений...
[2023-12-22 00:31:24] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=2301101716
[2023-12-22 00:31:25] Manifest download: send request
[2023-12-22 00:31:25] Manifest download: waiting for download to finish
[2023-12-22 00:31:26] Manifest download: finished
[2023-12-22 00:31:26] Download skipped: /steam_client_ubuntu12?t=2301101716 version 1702079146, installed version 1702079146, existing pending version 0
[2023-12-22 00:31:26] Nothing to do

OS: ArcoLinux 
Host: MS-7C52 1.0 
Kernel: 6.6.7-zen1-1-zen 
DE: Plasma 5.27.10 
WM: kwin 
CPU: AMD Athlon 200GE (4) @ 3.200GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 11.11GiB  
GPU Driver: amdgpu 
local/arcolinux-meta-steam-amd 23.06-01
    Installs steam on ArcoLinux for amd
local/steam 1.0.0.78-2
    Valve's digital software delivery system
                                    
I googled that the problem could be with the bit capacity of the libraries, but didn’t find a working solution, what can I do?

**Comment by kisak-valve** [comment]
Hello @als-creator, when Steam launches any game, it LD_PRELOADs a 32 bit and 64 bit variant of the Steam overlay. One silently gets loaded while the other fails harmlessly. This is a red herring and not your issue.

Instead, `/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var` is the line to focus on in your log and is similar to #6234. This issue should be reported to the game's developer(s).

**Comment by als-creator** [comment]
this problem does not have one specific game, but all that work through proton, regardless of whether it is on ntfs or ext4, I have now tried setting the line “LD_PRELOAD=/usr/lib/libfreetype.so %command%” as launch parameters "for several games, this does not solve the problem, in addition, I tried installing proton experimental and proton ge, this also did not solve the problem

**Comment by als-creator** [comment]
I launched the game torchlight 2 with the parameter "LD_PRELOAD=/usr/lib/libfreetype.so %command%", it works on xorg and wayland, but other games do not start, minion masters gives an error
/bin/sh\0-c\0/home/als/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=489520 -- /home/als/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/als/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/usr/share/steam/compatibilitytools.d/proton-ge-custom'/proton waitforexitandrun  '/home/als/.local/share/Steam/steamapps/common/Minion Masters/MinionMasters.exe'\0
chdir "/home/als/.local/share/Steam/steamapps/common/Minion Masters"
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/als/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pressure-vessel-wrap[5856]: W: Binding directories that are located under "/usr/" is not supported!
ProtonFixes[5965] INFO: Running protonfixes
ProtonFixes[5965] INFO: Running checks
ProtonFixes[5965] INFO: All checks successful
ProtonFixes[5965] INFO: Using global defaults for "Minion Masters" (489520)
ProtonFixes[5965] INFO: No protonfix found for "Minion Masters" (489520)
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
Setting breakpad minidump AppID = 489520
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198081092991 [API loaded no]
pid 5970 != 5969, skipping destruction (fork without exec?)
Game 489520 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 489520 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 489520 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 489520 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 489520 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 489520 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 489520 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 489520 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 489520 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 489520 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 489520 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 489520 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 489520 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 489520 created interface SteamController006 / Controller
Game 489520 created interface SteamFriends015 / Friends
Game 489520 created interface SteamMatchMaking009 / Matchmaking
Game 489520 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 489520 created interface SteamNetworking005 / Networking
Game 489520 created interface SteamUser019 / User
Game 489520 created interface SteamUtils009 / Utils
Game 489520 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 489520 method call count for IClientAppManager::GetAvailableLanguages : 1
Game 489520 method call count for IClientAppManager::GetAppInstallState : 2
Game 489520 method call count for IClientUtils::RecordSteamInterfaceCreation : 22
Game 489520 method call count for IClientUtils::GetSteamUILanguage : 1
Game 489520 method call count for IClientUtils::GetAppID : 24
Game 489520 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam

**Comment by kisak-valve** [comment]
` pressure-vessel-wrap[5856]: W: Binding directories that are located under "/usr/" is not supported!` is https://github.com/ValveSoftware/steam-runtime/issues/288#issuecomment-754151275 and is unrelated to your opening post.

**Comment by YellowOnion** [comment]
@als-creator  "ModLauncher.bin.x86_64" is a native linux app, and you're not using proton.

This is the steam runtime directly running the game:

`/bin/sh\0-c\0/home/als/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=200710 -- /home/als/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/Work/Games/Steam/steamapps/common/Torchlight II/ModLauncher.bin.x86_64'\0`

Your system is missing `/usr/lib/libfontconfig.so.1` it's either in a different location or you're missing a symlink.

i.e. `/usr/lib/` should contain depending on the version, these two links, and a 64bit dynamic library.

```
-r-xr-xr-x  2 root root 1018 Jan  1  1970 libfontconfig.la
lrwxrwxrwx 15 root root   23 Jan  1  1970 libfontconfig.so -> libfontconfig.so.1.12.1
lrwxrwxrwx 15 root root   23 Jan  1  1970 libfontconfig.so.1 -> libfontconfig.so.1.12.1
-r-xr-xr-x  2 root root 345K Jan  1  1970 libfontconfig.so.1.12.1
file: libfontconfig.so.1.12.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

You can also just try forcing the steam runtime:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/364160/68be8b4b-e0cb-4bd8-ad6a-5db27077830e)

Better yet, I would highly recommend you moving to a more establish Linux distro, ArcoLinux's confusing website leaves me thinking that your problems stem from ArcoLinux, Use ArchLinux, Ubuntu, or Fedora.

**Comment by als-creator** [comment]
Thank you, it’s no longer relevant to me, maybe someone else will need it

**Comment by nm004** [comment]
I had to rename the libfreetype.so file bundled with the game to fix the issue.
```
# cd <Torchlight II>
mv lib64/libfreetype.so.6{,.bak}
```

If the launcher doesn't show up, try updating the Launch Options as follows
```
LD_PRELOAD= %command%
```
It looks like `gameoverlayrenderer.so` conflicts with it. However, the Steam Overlay is not available while playing the game.

I encountered the issue with `gameoverlayrenderer.so` on Fedora 42. On Ubuntu 25.04 (running in a virtual machine), the launcher appeared without any modifications to the launch options.
