### ISSUE TITLE
Any hope of a 64-bit client?

### ISSUE THREAD

**Issue by GardenerAether** [ValveSoftware/steam-for-linux#10318]
########## SYSTEM ##########

Steam version: 10.0.0.7 (from `/steam/archive/stable/`)
Distro: NixOS
CPU: Apple M2 Pro (aarch64 only)
GPU: Apple M2 Pro (AGX2)

########## BACKGROUND ##########

I'm running an M2 Pro, so my hardware is not practically capable of running 32-bit software.

To be clear, this issue isn't:
- "so I don't have to install extra libraries"; id be fine with installing a bunch of extra libraries, if that was all this was about
- Me asking for aarch64 support, which would be a completely ridiculous ask
- Me asking for all my games to run; I'm talking exclusively about the client here
- Me even asking for the full GUI client; though it would be nice, steam-tui already exists

However, without turning to literally emulating MacOS (which would automatically deny me proton, and would be pointless anyways since I'm forced to dual-boot with MacOS). As I understand it, most of the games are already 64-bit; however, the primary thing preventing me from testing them at current is not being able to install steam.

The Asahi Linux team already have a working OpenGL driver (full 3.1 ES), with significant ongoing progress. Even Vulkan support is on the horizon.

I understand and respect that Valve, probably for the sake of preserving backwards compatibility, do not want to remove 32-bit support from the client. However, it would be really nice if there were a _separate_ 64-bit client for us plebeians that can't run 32-bit apps, especially since there already exists one for MacOS.

I'm not even talking the full GUI client here, which would probably be a much bigger task.

########## ISSUE ##########

Currently, attempting to run `steam` in `box64` yields the following error:

```
You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
```

So far, I've seen:
- People running the Steam client on generic arm hardware through `box86`
- The Asahi team running Steam on FEX (which doesn't actually work without hyper-specific memory alignment patches on Asahi Linux to begin with)
- An official 64-bit Steam client for MacOS

What is the likelihood of us seeing a 64-bit version of steamcmd? If prospects are good, is there any time frame we could hope for? If not, what are the major issues preventing Valve from being able to ship a 64-bit steamcmd for Linux? I know that last question probably seems un-necessary but that kind of transparency goes a long way.

I could be totally off the ball, but does having a 64-bit version for MacOS correlate at all to potential support for Linux?

I understand that this is probably not a major priority for Valve right now, but if it's not too major a task to complete for, it would be greatly appreciated. I certainly miss being able to play games (especially with friends), and I can't imagine I'm alone in that. Plus, I basically have to tell all my friends to just not buy me Steam gifts in the meantime :p

**Comment by kisak-valve** [comment]
Hello @GardenerAether, this issue is already being tracked at #3518. Closing as a duplicate.
