### ISSUE TITLE
Steam Error: Cannot run as root user

### ISSUE THREAD

**Issue by valdrinium** [ValveSoftware/steam-for-linux#10325]
#### Steps for reproducing this issue:

1. I am logged in as the root user in Linux and try to start Steam.
2. I see a completely arbitrary limitation that is not allowing me to start Steam.

**Comment by kisak-valve** [comment]
Hello @valdrinium, running Steam as root is explicitly unsupported and provides absolutely no benefit to you. This is not a bug.
