### ISSUE TITLE
Steam keeps launching an application after exiting it and switching an account

### ISSUE THREAD

**Issue by PackmanDude** [ValveSoftware/steam-for-linux#10322]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-2
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13780358/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Repetitive execution of last command via protocol after re-login.

#### Steps for reproducing this issue:

1. Execute `steam://run/<id>`
2. Exit newly launched application
3. Use Steam->Change account… option and select any account

**Comment by PackmanDude** [comment]
Probably related: #1721

**Comment by kisak-valve** [comment]
Hello @PackmanDude, this issue is already being tracked at #1414. Closing as a duplicate.
