### ISSUE TITLE
Crash when changing screenshot directory.

### ISSUE THREAD

**Issue by domdfcoding** [ValveSoftware/steam-for-linux#10320]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.61-2ubuntu3
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13777075/steam-logs.tar.gz)
* GPU: Nvidia GT 710

#### Please describe your issue in as much detail as possible:
In the Steam settings, under "In Game", after clicking on the "Change folder" button next to "Uncompressed screenshots folder" and selecting the desired folder the Steam client exits. The following lines appear in dmesg:

```
[Wed Dec 27 08:47:21 2023] steam[48556]: segfault at 0 ip 0000000000000000 sp 00000000da5fbc6c error 14 in steam[5657b000+29000]
[Wed Dec 27 08:47:21 2023] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
[Wed Dec 27 08:47:29 2023] traps: steamwebhelper[48326] trap invalid opcode ip:7ff0b87b535b sp:7ffcc64b2260 error:0 in libcef.so[7ff0b45e4000+7770000]
```

The setting remains unchanged after reopening Steam.

#### Steps for reproducing this issue:

1. From the Steam toolbar select "Steam" -> "Settings"
2. Click "In Game" from the sidebar.
3. Scroll down to "Screenshots"; click "Change folder" next to "Uncompressed screenshots folder" 
4. Select a folder (I chose ~/Pictures) and click "Select"

**Comment by kisak-valve** [comment]
Hello @domdfcoding, this issue is already being tracked at #9846. Closing as a duplicate.
