### ISSUE TITLE
Add support for switching Steam accounts while using Steam Link

### ISSUE THREAD

**Issue by Holzhaus** [ValveSoftware/steam-for-linux#10330]
#### Your system information

* Steam client version (build number or date): 2023-12-30
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: n/A
* GPU: AMD

#### Please describe your issue in as much detail as possible:

When switching accounts while being connected via Steam Link, the connection closes.

#### Steps for reproducing this issue:

1. While in Big Picture Mode and connected via Steam Link, click the profile pic in the top right
2. Click "Change Account"
3. Steam Link is disconnected. You now need to get up from the couch, go to the computer, select the new account and reconnect the Steam Link afterwards.

**Comment by kisak-valve** [comment]
Hello @Holzhaus, Steam Link specific requests should be made on the community forums. It looks like there are several threads on the topic https://steamcommunity.com/app/353380/discussions/search/?q=switch+account.

**Comment by Holzhaus** [comment]
Ah OK. I posted it here because in my understanding of the issue the problem is caused by the steam client stopping the stream when pressing the "Change Accounts" button in the Steam client. The steam link does not have account selection, only computers that are streamed from. 

I'll check the forums though.
