### ISSUE TITLE
Cache system-related files in the shared disk of multiple systems, and do not download them again every time you switch systems.

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [ValveSoftware/steam-for-linux#10332]
I have Windows and Linux and MacOS installed on the same computer.

They share an NTFS disk that holds a SteamLibrary.

I have steam installed on three systems and they can share the games in that NTFS disk.

The only problem is that when I switch from one system to another, steam will repeatedly download some system-related files for the game in the shared ntfs disk.

It seems that steam does not save these system-related files.

If it is the first time to switch from the first system to the second system, you should keep the files of the first system when downloading the files related to the second system.

In this way, you do not have to download the first system related files again when you switch back to the first system.

**Comment by kisak-valve** [comment]
Hello @I-Want-ToBelieve, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client."

Sharing a Steam library between OSes is not supported and undefined behavior can occur. Sorry, but this is not a supported use case.

**Comment by I-Want-ToBelieve** [comment]
All right . But I still want to say it. Implementing it shouldn't be complicated. You only need to save the system platform-related files in the folder with the system name.
Consider this python code
```python
>>> import platform
>>> platform.platform()
'Linux-3.3.0-8.fc16.x86_64-x86_64-with-fedora-16-Verne'
```
