### ISSUE TITLE
launch options are ignored

### ISSUE THREAD

**Issue by MartinX3** [ValveSoftware/steam-for-linux#10334]
#### Your system information

* Steam client version (build number or date): 1702079146
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13801770/steam-logs.tar.gz)
* GPU: Nvidia/Intel

#### Please describe your issue in as much detail as possible:
Launch options are ignored

#### Steps for reproducing this issue:

1. Writing `adasdsad` or `prime-run %command%` or `asdadasd %command%` or `prime-run %commanddddd%` in the launch options
2. The game just launches (and doesn't use my nvidia gpu)

**Comment by kisak-valve** [comment]
Hello @MartinX3, looking through the console_log.txt in the set of logs you shared, there's several lines like `[2023-12-31 17:35:36] Game process added : AppID 2224920 "prime-run /home/martin/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2224920 -- /home/martin/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/martin/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/martin/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/martin/.local/share/Steam/steamapps/common/Evacuation/hl2.exe' -steam -nohmd -game "evacuation"", ProcID 16038, IP 0.0.0.0:0`

This shows that Steam is correctly reading the per-game launch options and parsing `%command%` to allow you to pass values before the game's run command. There may be some other quirk with NVIDIA's PRIME Render offload or Arch's `prime-run` convenience script, but that's something to look at on the video driver's side.

If you typo or omit `%command%`, then the launch options are appended to the run command for the game to parse.

Closing as not broken.

**Comment by MartinX3** [comment]
@kisak-valve you're right

I tried the steam game `OpenTTD` and if works (my nvidia gpu is used).

I tried the HL2 Mod `Evacuation` which uses proton experimental and it runs on the intel iGPU.

Where to put the proton issue ticket?
