### ISSUE TITLE
Big Picture Mode opening in Windowed mode even when disabled in settings

### ISSUE THREAD

**Issue by Symbitic** [ValveSoftware/steam-for-linux#10331]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13799191/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
With the Windowed option disabled, Steam Big Picture Mode should start in full-screen mode. Instead, it is opening in windowed mode. See screenshot below.

To solve, toggle the Windowed option to enabled and then back to disabled. That results in full screen mode, but the problem repeats on every startup.

#### Steps for reproducing this issue:

1. Enable Big Picture Mode.
2. Enable Run Steam on Startup.
3. Ensure Windowed mode for Big Picture Mode is disabled.
4. Reboot.
5. Steam opens in Big Picture Mode with windows.

#### Screenshot

![Screenshot_20231002_164019](https://github.com/ValveSoftware/steam-for-linux/assets/9487468/b7eebe11-ac67-47e9-82d0-ec04605a8b71)

**Comment by Symbitic** [comment]
I forgot to get the client version and I can't boot my machine right now, but I did check for any updates today (December 30, 2023) and it said I was running the latest.

**Comment by kisak-valve** [comment]
Hello @Symbitic, this issue is already being tracked at #10059. Closing as a duplicate.
