### ISSUE TITLE
Steam UI: "Create or select new steam library folder" dialog is empty and previous additional paths are missing

### ISSUE THREAD

**Issue by maatta** [ValveSoftware/steam-for-linux#10349]
#### Your system information

* Steam client version (build number or date): 1702079146
* Distribution (e.g. Ubuntu): Ubuntu 20.04.6 LTS
* Opted into Steam client beta?: Yes (tried both)
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13840294/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

The "Create or select new steam library folder" dialog is empty and the previous additional entry (/mnt/games1/steam) went missing between two updates (unsure which ones though) making the games installed there unplayable.

Screenshot of the list of Library paths, that only has one entry (missing the other one in /mnt that should be there):
![steam_issue2](https://github.com/ValveSoftware/steam-for-linux/assets/17344309/f94a4031-c16d-4e17-a012-51899fde3d35)

Tried adding it back but the dialog is unusable with the "New Folder" button doing nothing, "Select" does nothing either making it impossible to add the other path back again.. 

![steam_issue](https://github.com/ValveSoftware/steam-for-linux/assets/17344309/413eb208-831b-4e93-8871-8abadba76a01)

#### Steps for reproducing this issue:

1. Install non-Beta (or Beta, doesnt matter) version of Steam from http://repo.steampowered.com/steam/
2. Open Settings
3. Click on Storage
4. Click on Add Drive

**Comment by kisak-valve** [comment]
Hello @maatta, this issue is already being tracked at #10207. Closing in favor of the older issue report.
