### ISSUE TITLE
Launching a game multiple times leads to the game info page being duplicated to the history 

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/steam-for-linux#10348]
#### Your system information

* Steam client version: 1704329464 (Steam Deck Beta)
* Distribution: SteamOS `20240104.1000` 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13838648/steam-logs.tar.gz)
* GPU: AMD Custom APU 0932 (Steam Deck OLED)

#### Please describe your issue in as much detail as possible:
Launching a game in Big Picture Mode / Game Mode will lead to a duplicate of the game info page being added to the page history stack. If you launch a game repeatedly, it can lead to the user having to press the back button multiple times before actually leaving the game info page. 

#### Steps for reproducing this issue:

1. Open Big Picture Mode or Steam Deck game mode.
2. Navigate to the info page for any game.
3. Launch the game.
4. Close the game.
5. Repeat steps 2 and 3 as many times as you like.
6. Observe as pressing the back button does not return you to the previous page.

#### Video
https://github.com/ValveSoftware/steam-for-linux/assets/34801996/e5755519-546f-4542-a93c-9b0fcaa9a60c

In this video I press the back button multiple times before it actually returns me to the library screen. This happened after I launched Alien Hominid HD multiple times.

**Comment by kisak-valve** [comment]
Hello @Sterophonick, this issue is already being tracked at #10253. Since this issue report adds a bit more detail, I've transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/10253#issuecomment-1878749036.
