### ISSUE TITLE
Wake Up! Don't Ignore the Linux Gaming Revolution!

### ISSUE THREAD

**Issue by RaulKong898** [ValveSoftware/steam-for-linux#10346]
Dear PC video game companies and launch developers,

As a PC gamer who proudly runs Linux, I'm writing to you today with a message straight from the heart: Stop neglecting Linux! We're a passionate, growing community that wants native support, and here's why you should care:

Linux isn't just for servers anymore. It is a powerhouse for performance, security and flexibility. You know those solid online game servers you rely on? Yes, many run on Linux! So why leave us, your dedicated customers, with nothing but leftovers?

Think of the advantages:

Security: Hackers and cheaters tremble at Linux's inherent resilience. Imagine free online games from their shadows!
Performance: No more locked systems – Linux unleashes true gaming potential, making even the most demanding titles soar.
Flexibility: Modify, optimize, customize - Linux is your playground, not a walled garden. Release the inner player!
Cost-effective: Open-source goodness means lower costs for both you and us. Everyone wins!
Growing market: Don't underestimate the tide of Linux gaming. Proton, Steam Play and our ever growing numbers prove that we are a force to be reckoned with.
Don't just port – embrace the natives! Give us Linux builds built from the ground up, not afterthoughts. We deserve a complete PC gaming experience, not a second-rate game.

And don't forget the launchers! Steam Deck, GOG Galaxy, Itch.io – make sure they fully embrace Linux, too. Let us browse, buy and download with ease, just like our Windows counterparts.

Enough is enough! Force the hand of those still stuck in Windows' past. Make native Linux support a non-negotiable requirement for your partnerships. We're no longer a niche – we're a revolution demanding to be heard!

Remember, it's not just about gaming, it's about choice, freedom, and pushing the boundaries of what gaming can be. Join us, embrace Linux, and together let's build a future where every gamer, regardless of their platform, can truly play!

Sincerely,

A frustrated (but hopeful) Linux gamer.

"Obligate all companies that make games for your launchers from where we buy games to make native support for linux as well. It is not nice to neglect the linux nonsense as many online games use linux servers."

**Comment by kisak-valve** [comment]
Hello @RaulKong898, you've come across the issue tracker for the Steam client for Linux. It is not a general purpose forum. This general topic should be discussed on the community forums instead of this issue tracker.

That written, Steam (cross)platform wide policy is up to Valve developers and is not open to public influence.
