### ISSUE TITLE
custom path as additional storage ?

### ISSUE THREAD

**Issue by mtricolici** [ValveSoftware/steam-for-linux#10350]
#### Your system information

Steam Version:  1702079146
Steam Client Build Date:  Fri, Dec 8 02:33 UTC -08:00
Steam Web Build Date:  Sat, Dec 9 01:30 UTC -08:00
Steam API Version:  SteamClient021
Distribution: Linux Mint 20 (based on ubuntu focal)

#### Please describe your issue in as much detail as possible:
```
$lsblk 
NAME                                          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sdb                                             8:16   0 931,5G  0 disk  
├─sdb1                                          8:17   0 512,2G  0 part  
│ └─luks-57f39e7d-2dd5-4483-8094-63960a4a2ac9 253:1    0 512,2G  0 crypt /home
└─sdb2                                          8:18   0 419,3G  0 part  /insecure
nvme0n1                                       259:0    0 238,5G  0 disk  
├─nvme0n1p1                                   259:1    0   100M  0 part  /boot/efi
├─nvme0n1p6                                   259:6    0   7,9G  0 part  /boot
```

I have a new folder with write access in /insecure/something-here that I'd like to add as 2nd storage for games (without encryption - to be faster)

According to steam logs it checks for write permissions in each root mounted point:

```
Couldn't write /.steam_exec_test.sh: Permission denied
Couldn't write /boot/.steam_exec_test.sh: Permission denied
Couldn't write /boot/efi/.steam_exec_test.sh: Permission denied
Couldn't write /insecure/.steam_exec_test.sh: Permission denied
Couldn't write /run/user/1000/doc/.steam_exec_test.sh: Permission denied
```

QUESTION: how to add a custom path as storage?

and btw. thank you guys very much for supporting linux :)

![storage-add-steam](https://github.com/ValveSoftware/steam-for-linux/assets/717384/c2b99858-39ad-483d-a32b-b8bfba23ad01)

**Comment by mtricolici** [comment]
as workaround I can do this:

mv $HOME/.local/share/Steam /insecure/my-folder/
ln -s /insecure/my-folder/Steam $HOME/.local/share/Steam

is this the only option?

**Comment by mtricolici** [comment]
I've figured out a nice workaround that works fine :)


```
sudo mkdir /media/games
sudo echo '/insecure/games /media/games none bind,uid=1000,gid=1000 0 0' >> /etc/fstab
sudo mount /media/games
```


now I see /media/games in steam client so I can add 2nd storage :P
issue can be closed.

**Comment by kisak-valve** [comment]
Hello @mtricolici, this issue is already being tracked at #9640. Closing as a duplicate.
