### ISSUE TITLE
Steam client keeps creating empty temp folders owned by user "nobody" and group 100 on btrfs

### ISSUE THREAD

**Issue by queenbiscuit311** [ValveSoftware/steam-for-linux#10358]
#### Your system information

* Steam client version (build number or date): Steam Version: 1702079146 Steam Client Build Date:  Thu, Dec 7 18:33 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]

Am i supposed to include all of these here? Here's a zipped version and if needed ill send individual logs.
[logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/13851605/logs.zip)

* GPU: Nvidia RTX 3060 Laptop GPU

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When starting a game or updating, steam will randomly fail saying that there are "missing file permissions". Here are some examples:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/88851292/2e2f3db1-a8c8-4ca9-8b08-f1ee7061240c)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/88851292/e74447ae-0c8b-4614-9c49-05dbde876c9f)

When inspecting the folder shown in the vrchat error message, the problem can be seen clearly:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/88851292/1cfea7d9-5619-42b4-a1a4-542ed819399a)

For some reason these temp folders will randomly be set to being owned by this user and this group. Steam is the only program I have that does this, and this happens regardless of the drive the steam library of a game is on, as long as its on btrfs. I've had this problem on 4 separate btrfs drives on this computer, so it is not a problem with my specific drive as far as i know.

In order to solve this problem, I must either use root user to delete these folders and have steam recreate them, or use chown to give myself full ownership of the steamlibrary folders. After doing this everything works as expected until it inevitably happens again. This happens extremely often, at least twice a week or more.

As you can see from these screenshots my steam client has a theme applied via adwsteamgtk, I have made absolutely certain that this is not the source of the problem, especially since it started long before i installed this theme. I've also attempted full clean installs of steam to no avail. This issue has persisted since I converted my system to brtfs about 7 or 8 months ago.

As for what I expected should happen, steam's temp folders should not have permission problems.

#### Steps for reproducing this issue:

1.  Have a steam library on a btrfs drive
2. Install games on it
3. This happens

**Comment by actioninja** [comment]
Bumping, just ran into the same issue.

**Comment by queenbiscuit311** [comment]
> Bumping, just ran into the same issue.

are you by any chance dual booting windows with winbtrfs

**Comment by actioninja** [comment]
> > Bumping, just ran into the same issue.
> 
> are you by any chance dual booting windows with winbtrfs

You know, thinking about it it did manifest after booting back in to a windows partition. I thought nothing of it because while I did use winbtrfs at one point I moved off of it due to occasional issues and filesystems are the last thing I want to be having problems with, but I do in fact still have the driver installed. Very strange issue, I wonder if steam is doing something goofy on windows when it hits the btrfs partition or if it's a bug with winbtrfs.

**Comment by queenbiscuit311** [comment]
For me, the problem was that winbtrfs automatically uses uid 100 and gid 100 for whatever reason, this means that when steam on windows creates temp folders, steam on linux can't erase or add to them. If you want I can find what I did to change it to the Linux default of 1000:1000 and see if it works for you.

**Comment by kisak-valve** [comment]
Hello @queenbiscuit311, "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md, sharing Steam Library folders between OSes is not supported and this is yet another example of undefined behavior that can happen. It might be worthwhile to report your findings to the WinBtrfs dev(s).

**Comment by queenbiscuit311** [comment]
For anyone else with this problem: https://github.com/maharmstone/btrfs#Mappings go to the mappings section of this page and follow the instructions to make sure your windows users accesses btrfs with the same uid and gid as your linux user, for example 1000:1000 or 1001:1001. I did this a while ago and this problem has not appeared since. This is seemingly intended behavior that isn't usually a problem except for things like steam.

**Comment by queenbiscuit311** [comment]
also thanks for closing the issue since i forgot
