### ISSUE TITLE
Difficult to read text in valve games.

### ISSUE THREAD

**Issue by spacelike** [ValveSoftware/steam-for-linux#1035]
The fonts on Linux in valve games are significantly harder to read than in the windows version.

To illustrate the problem, please view the following image:
![text](https://f.cloud.github.com/assets/3375079/108443/671101c0-6a4f-11e2-9e1e-ccffd8ff73d7.jpg)

As far as I can tell the font looks similar, and the drop shadow does exist in all 4 examples, but in windows the text is just thicker making it much more readable.

The screenshots were taken in TF2 at 1920x1080 resolution
and in cs 1.6 at 1024x768 resolution.

In windows I've never had to look for dark parts of the map to move into just so that I can read the chat text, but I find myself doing that (and quite often in cs 1.6) in linux. In TF2 it's a bit of an annoyance, but in cs 1.6 (on de_dust type maps) it becomes almost impossible to read most of the time.

If I were to take a guess as to what might be the difference, I would say it seems that in windows the text is set to BOLD but on linux it is not.

NOTE: I apologize if the cs 1.6 comparison looks a bit biased, I tried to find a screenshot online of windows that looked as similar as possible to mine. But I used to play a lot of cs 1.6 on windows and I can assure you, the text is always very readable.

**Comment by magynhard** [comment]
I've created a patch for Counter-Strike 1.6 and Day of Defeat 1.2 that can be found here:
https://github.com/magynhard/halflife_goldsrc_linux_font_patches
