### ISSUE TITLE
Impossible to play Counter Strike with 2 displays

### ISSUE THREAD

**Issue by carlosvalin94** [ValveSoftware/steam-for-linux#10359]
Steam client version (build number or date): January 7 2024
Distribution (e.g. Ubuntu): Ubuntu 23.10 x86_64,  Fedora 39
Opted into Steam client beta?: No
Have you checked for system updates?: Yes
Steam Logs:
GPU: AMD Radeon RX 6600M

#### Please describe your issue in as much detail as possible:
The issue is not present on the proton version but on the native one, the game have lot of glitches in a dual monitor setup and It's impossible to run it unless is configure to run with the -fullscreen option.

Here is an example video:
https://www.youtube.com/watch?v=8K2pCrj-DI4

Tested on Ubuntu 23.10 and Fedora 39 as well.

#### Steps for reproducing this issue:

1. Ensure that you are using 2 displays
2. Launch the game

**Comment by carlosvalin94** [comment]
This was tested in another computer with Ubuntu 23.10 and Nvidia RTX 4090 as well with the official drivers, same error.

**Comment by kisak-valve** [comment]
Hello @carlosvalin94, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3268. Closing as a duplicate.
