### ISSUE TITLE
Can't install steam on Debian (32-bit libraries problem)

### ISSUE THREAD

**Issue by tomcass240** [ValveSoftware/steam-for-linux#10371]
#### Your system information

* Steam client version (build number or date): Latest stable
* Distribution (e.g. Ubuntu):  Debian
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: Yes
* GPU: Nvidia

Can't install steam on Debian 12 (Bookworm) using apt install steam-installer. Running that gives a warning that 32-bit libraries need to be installed, but they're not available for bookworm. Therefore running steam-installer eventually throws up an error that it can't install without the 32-bit libraries.

**Comment by kisak-valve** [comment]
Hello @tomcass240, you need to be more specific as to what packages claim to be unavailable.

**Comment by ipr** [comment]
Did you add 32-bit arch first? sudo dpkg --add-architecture i386

See: https://repo.steampowered.com/steam/

**Comment by tomcass240** [comment]
Hey I managed to get it installed. Not sure why it wasn't installing before and not entirely sure what I did to fix it, I run a few commands and it seemed to install fine after running: 

sudo apt-get upgrade steam -f
sudo apt install nvidia-driver-libs:i386
