### ISSUE TITLE
Bug from Beta Client went Live, steamservice.so missing

### ISSUE THREAD

**Issue by maliciouspastry** [ValveSoftware/steam-for-linux#10392]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13941053/steam-logs.tar.gz)`]
* GPU: Multiple Machines Nvidia and Intel

#### Please describe your issue in as much detail as possible:

https://github.com/ValveSoftware/Proton/issues/2563
https://steamcommunity.com/groups/SteamClientBeta/discussions/0/4038104984899051781/
https://www.protondb.com/app/440900

Game was running perfectly for a long while via Proton and Steam. No major issues, latest steam update stopped that real quick. Apparently was reported in the beta before it was pushed to live as well. Links above.

On Arch/Artix I get the following, others have similar errors:

dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
*** bit out of range 0 - FD_SETSIZE on fd_set ***: terminated
pid 22781 != 22780, skipping destruction (fork without exec?)

Sorry if this is a duplicate, I could not find an existing issue request.

#### Steps for reproducing this issue:

1.  Load current version of steam (1/15/2024 - 1705108172) (Non-beta)
2.  Run Conan Exiles, run game via launcher or bypass launcher (does not matter)
3.  Crash back to Steam

**Comment by orlfman** [comment]
the game can get to be ran by disabling OnlineSubsystemSteam by setting bEnabled to false in the steamapps/common/Conan Exiles/ConanSandbox/Config/Windows/WindowsSteamEngine.ini

but since steam online services are disabled, you can't do anything. not even single player works, as it needs steam online services (which i guess is because it has co-op).

**Comment by kisak-valve** [comment]
Hello @orlfman, we're tracking issues with games run with Proton on the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title.

https://github.com/ValveSoftware/Proton/issues/2563 is the right place to discuss this issue and it's been mentioned a handful of times already. Closing in favor of the Proton compatibility report.
