### ISSUE TITLE
Steam on Linux incorrectly classifies HDDs and optical drives as SSDs

### ISSUE THREAD

**Issue by grepwood** [ValveSoftware/steam-for-linux#10399]
#### Your system information

* Steam client version (build number or date): 1702079146
* Distribution (e.g. Ubuntu): Gentoo Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
When asked Steam for System Information, HDDs and optical media are classified as SSDs, which is untrue.
Here is the storage section I have from Steam:
```
Storage:
Number of SSDs: 6
SSD sizes: 4000G,4000G,320G,128G,659M,0B
Number of HDDs: 0
Number of removable drives: 0
```

This is demonstrably untrue. Let's break this apart by each reported SSD size.
1. 4000G - this is correct, I have two 4TB SSDs, this is first of them
2. 4000G - this is also correct, I have two 4TB SSDs, this is the second of them
3. 320G - this is untrue, this is a SATA HDD sitting in my removable HDD bay
4. 128G - this is true, I have a NVME SSD that holds the EFI bootloader and an encrypted swap filesystem
5. 659M - this is absolutely incorrect, this is a CD I have in my SATA BluRay drive
6. 0B - this is probably my memory card reader reporting that there's no card inserted, but otherwise the device is ready for action

For comparison, here's my `lsblk` without the mountpoints:
```
NAME                   MAJ:MIN  RM   SIZE RO TYPE  MOUNTPOINTS
sda                      8:0     0 298,1G  0 disk
sdb                      8:16    0   3,6T  0 disk
sdc                      8:32    0   3,6T  0 disk
sdd                      8:48    1     0B  0 disk
sr0                     11:0     1 629,4M  0 rom
nbd0                    43:0     0     0B  0 disk
nvme0n1                259:0     0 119,2G  0 disk
nbd1                    43:256   0     0B  0 disk
nbd2                    43:512   0     0B  0 disk
nbd3                    43:768   0     0B  0 disk
nbd4                    43:1024  0     0B  0 disk
nbd5                    43:1280  0     0B  0 disk
nbd6                    43:1536  0     0B  0 disk
nbd7                    43:1792  0     0B  0 disk
nbd8                    43:2048  0     0B  0 disk
nbd9                    43:2304  0     0B  0 disk
nbd10                   43:2560  0     0B  0 disk
nbd11                   43:2816  0     0B  0 disk
nbd12                   43:3072  0     0B  0 disk
nbd13                   43:3328  0     0B  0 disk
nbd14                   43:3584  0     0B  0 disk
nbd15                   43:3840  0     0B  0 disk
```

First of all Steam should instead correctly recognize what is an SSD and what isn't. Next, it shouldn't assume that every block device is necessarily a disk drive - in case of `/dev/sr0` and generally device nodes that satisfy the regex `^sr[0-9]+$` are enumerated SCSI-driver ROM devices.

BTW don't worry, the Linux SCSI driver also handles IDE devices, so no need to worry yourself with `/dev/hd[a-z]` and hypothetically `/dev/hr[0-9]+`.

#### Steps for reproducing this issue:

1. Connect a HDD or optical drive, or both, to your computer.
2. Start Steam.
8. Ask Steam for System Information.

**Comment by kisak-valve** [comment]
Hello @grepwood, this issue is already being tracked at #8966. Closing as a duplicate.
