### ISSUE TITLE
Starting Non-Steam Games while in Family View not working without Workaround

### ISSUE THREAD

**Issue by silelmot** [ValveSoftware/steam-for-linux#10395]
#### Your system information

* Steam client version :  1705108172
* Distribution (e.g. Ubuntu): Fedora / Ubuntu(Mint)
* Opted into Steam client beta?: [Yes] and [No] - tried both with same results
* Have you checked for system updates?: [Yes]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
When I select any Non-Steam Game added to Steam while in Family View it should open the games page with the button "play". Instead i get the code-window for exiting family-view. Other than on DeckUI (issue posted by Maykin-99: https://github.com/ValveSoftware/steam-for-linux/issues/8656) ,without entering the code, the game does not start!

this can be worked around, by right clicking the game in the left list and chose "play" from the opening context-menu.

this behavior happens since somewhat half a year. worked before.

#### Steps for reproducing this issue:

1. Enable Family View
2. Add Non-Steam-Game
3. Left-Click on Non-Steam-Game

**Comment by kisak-valve** [comment]
Hello @silelmot, this is the same issue as #8656. Closing as a duplicate.
