### ISSUE TITLE
Steam Input: None Steam Apps folder ID requests

### ISSUE THREAD

**Issue by Lazorne** [ValveSoftware/steam-for-linux#10390]
As we are creating a flatpak application on flathub each time a user adds RetroDECK to Steam or any NONE-Steam-Game the ID of the folders where the controller profiles is stored is randomized. So we can not know where they will be stored.

Example: 

`/Steam Controller Configs/25233020/`

It would be great if there was an option to request a permanent ID for none Steam apps. 

Or a better wish that you create a integration Steam Linux version with flathub and make ID's for all those apps ;)

**Comment by kisak-valve** [comment]
Hello @Lazorne, this reads like the issue being tracked at #9463. Closing as a duplicate.
