### ISSUE TITLE
Steam Cloud

### ISSUE THREAD

**Issue by AgoraSim21** [ValveSoftware/steam-for-linux#10401]
Hello, suggestion: possibility of saving the progress of old games in the cloud, which do not have the Steam cloud option, in any game that does not save in the cloud.
To avoid having to do everything in the game again, after formatting your PC, or changing your PC, operating system, etc.
Game example: Euro Truck Simulator 1

Thank you very much in advance
Success to all 😁

**Comment by kisak-valve** [comment]
Hello @AgoraSim21, save game locations are not standardized and this needs to be configured on a per-game basis. Additionally, games that support multiple OSes have to consider possible cross-OS variations in the save file format and what effect that may have before setting up a common save folder or making per-OS save folders to avoid conflicts.

There's no magic bullet to enable this for all games.

**Comment by AgoraSim21** [comment]
Ok thanks 👍
