### ISSUE TITLE
Steam client keeps downloading something for the game left 4 dead 2.

### ISSUE THREAD

**Issue by H3r4cles** [ValveSoftware/steam-for-linux#10402]
#### Your system information

* Steam client version: 705108172
* Distribution: Debian GNU/Linux trixie/sid (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13980730/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Almost everyday the steam client downloads about 350mb~ for the game left 4 dead 2. There is no way to skip this and i could clear the downloads but it will keep on downloading anyway. I cannot run the game until this thing gets downloaded. It goes away if i restart steam after that but it does happen almost everyday.
I used to think that this was a bug on my end but i am doing this on a fresh install now.

![Screenshot from 2024-01-18 16-30-19](https://github.com/ValveSoftware/steam-for-linux/assets/74436522/b52bc348-a4ce-4ea3-977b-51845aa5ade6)
![Screenshot from 2024-01-18 16-30-43](https://github.com/ValveSoftware/steam-for-linux/assets/74436522/b74b3cbe-5a23-4e62-b486-4e0161c63bad)

#### Steps for reproducing this issue:

1. Boot your system.
2. Run Steam.
3. Watch it downloading stuff for left 4 dead 2.

**Comment by kisak-valve** [comment]
Hello @H3r4cles, this is a shader pre-cache update.

This issue is already being tracked at #8076 / #10285. Closing as a duplicate.
