### ISSUE TITLE
Steam gamepad ui not reacting to controller input after beta update (Xbox Elite 2 controller)

### ISSUE THREAD

**Issue by Juppstein** [ValveSoftware/steam-for-linux#10406]
#### Your system information

* Steam client version (build number or date): 1705630720
* Distribution (e.g. Ubuntu): Ubuntu 22.4 LTS
* Opted into Steam client beta?: [Yes/No] YES
* Have you checked for system updates?: [Yes/No] YES
* Steam Logs: [generate by running this command in a terminal [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13994404/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD NVIDIA

#### Please describe your issue in as much detail as possible:
After latest beta my Microsoft Elite 2 Xbox controller (connected via bluetooth / xpadneo) does not work anymore in gamepad ui. Steam is not reacting to any button or stick input, the only thing that still works is the home button which opens the side menu. When going to Settings/Controller/Test Device Inputs I can see that Steam recognizes button presses or stick movement, but this does trigger menus or control movements in the UI. Tested  in Dead Cells and the controller works in-game. Also tested successfully outside Steam (Kodi)

#### Steps for reproducing this issue:

1.  Update to latest beta
2.  Activate controller
3.  Try to navigate the UI

**Comment by autumngray** [comment]
Can confirm. As an aside: when I launch  the on-screen keyboard, I do get controller input and I can focus the main window and still use the controller.

**Comment by buckysrevenge** [comment]
This happens in the latest beta for me with at least a couple controllers I tested (Steam Controller (wireless) and Hyperkin Trooper 2). Button presses properly recognized in game and in the controller button test, but the BPM controls are not functioning as expected with a game controller

**Comment by hjpaul7** [comment]
+1 here with a PS5 controller. PS button also does not launch Big Picture Mode anymore.

**Comment by dataphract** [comment]
+1 here with a standard XBox One controller. Additionally, when opening Settings -> Controller -> Calibration & Advanced Settings:

- The UI cannot initially be controlled with a controller.
- After removing focus from Steam and then clicking back into the Calibration window, the controller can navigate the UI. -Backing out of the Calibration window by hitting B a few times causes the window contents to disappear (the window decorations remain) and ultimately freezes the entire Steam client.

**Comment by CplNathan** [comment]
I am unfortunately suffering from the same issue, annoyingly the stable client has an issue with hardware decoding for remote play which seems to be fixed in the beta version.

**Comment by Juppstein** [comment]
With today's update the issue has softened a bit. Navigation via left stick is working now but dpad input is still being ignored.

**Comment by OpenSauce04** [comment]
I have also been experiencing this issue with a DS4 controller when using the beta. The only button that was picked up was the home button
I uninstalled the beta, and the problem disappeared

**Comment by deathxxx123** [comment]
PS4 controller on steam beta
Buttons does not do what are supposed to do. It's some mismatch. Only PS button working as espected. In games buttons are working with no problem, only in Big picture mode is problem on steam beta only.

With steam stable - no problem.
Also beta gives more performance to Big picture and run more smooth On Nvidia driver.

**Comment by cjhelloletsgo** [comment]
On Ubuntu, similar to other reports. I can't use my dualsense controller anymore. Steam Beta

**Comment by Valmar33** [comment]
@kisak-valve 

Not sure whether this helps much, but for what it's worth, I've noticed my PS5 controller (connected by USB) works in a Gamescope session without any problems, while continuing to not work in regular non-Gamescope Big Picture mode.

The command I'm using for running Steam in Gamescope is
```
SDL_VIDEODRIVER=x11 gamescope --output-width 1280 --output-height 800 --nested-width 1280 --nested-height 800 --nested-refresh 120 --steam -- steam -gamepadui
```

**Comment by Juppstein** [comment]
Can confirm that my Elite 2 controller is again working in the latest Steam beta release

**Comment by hadim** [comment]
How do we know which beta version we are running and when a given beta is released on the "stable" channel?

**Comment by Juppstein** [comment]
> How do we know which beta version we are running and when a given beta is released on the "stable" channel?

You should be able to see the build number and the build date under Settings / System. the build that fixed the issue was the one from yesterday 9pm. 

As for what goes into the stable branch, I don't know. You probably have to read the release notes to see if this particular fix makes it into a future stable release.

**Comment by hadim** [comment]
Thanks.

Do you know where the release notes can be found?

**Comment by buckysrevenge** [comment]
https://store.steampowered.com/news/collection/steam/

**Comment by coreybruce** [comment]
Latest stable version fixes this issue, finally! :smile:

**Comment by Juppstein** [comment]
Closing this since the last update fixed the issue for me. Thanks!
