### ISSUE TITLE
Uninstalling a game deletes user generated content stored in compatdata

### ISSUE THREAD

**Issue by stevenre3d** [ValveSoftware/steam-for-linux#10419]
* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Expected behavior: If a game normally stores user generated content (such as screenshots taken using an in-game Photo mode) in the user's AppData folder, then when the game is uninstalled, this content should not be deleted.

Actual behavior: Upon Uninstalling a game, the entire folder in `compatdata` corresponding to this game ID is deleted.

#### Steps for reproducing this issue:

1. Install The Invincible
2. Play the game
3. Hit pause, use Photo Mode to take an in-game screenshot
4. Close the game, and notice that the photo was stored to `.../SteamLibrary/steamapps/compatdata/731040/pfx/drive_c/users/steamuser/AppData/Local/TheInvicible/Saved/Screenshots/WindowsNoEditor`
5. Using the steam client, Uninstall the game
6. Notice that the photo has been deleted.

The same steps on Windows will leave the folder, and thus the screenshot data, in-tact. A typical user will not know that this operation is safe on one platform, but destructive on another.

**Comment by kisak-valve** [comment]
Hello @stevenre3d, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/428.

Closing as a duplicate.
