### ISSUE TITLE
Steam Overlay not working with Flatpak Apps

### ISSUE THREAD

**Issue by nazdridoy** [ValveSoftware/steam-for-linux#10426]
#### system information

*Steam Version:  1705108172
* Distribution : Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: yes
* GPU: Nvidia

**Description:**
When attempting to launch Flatpak applications through Steam, the Steam Overlay fails to appear. This issue is specific to Flatpak apps, as non-Steam games (both native and Wine-based `bottles-AUR`) work as expected with the Steam Overlay.

**Steps to Reproduce:**
1. Launch Steam.
2. Add a Flatpak app (e.g., retroarch-flatpak or bottles-flatpak) to the Steam library.
3. Launch the Flatpak app from Steam.
4. Observe that Steam Input works, but the Steam Overlay does not appear.

**Additional Information:**
- All necessary permissions for the Flatpak apps have been granted.

**Comment by kisak-valve** [comment]
Hello @nazdridoy, this issue is already being tracked at #8952. Closing as a duplicate.
