### ISSUE TITLE
Streams from Desktop to Steam Deck (non HDR) have no brightness

### ISSUE THREAD

**Issue by perroboc** [ValveSoftware/steam-for-linux#10429]
#### Your system information

* Steam client version (build number or date): 1706155871
* Distribution (e.g. Ubuntu): Fedora on Desktop, Official Steam Deck distro on Steam Deck
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14053055/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:
When streaming games from Desktop to Steam Deck, the stream is too dark to play. It seems to detect the Steam Deck as HDR capable, but I only have a LED Steam Deck, not an OLED one, so the lack of brightness makes the games unplayable.

Take Hades for example. Here, I'm streaming from Desktop (4k, plasma 5 no HDR) to Steam Deck. The brightness is too low or non existant.
![WhatsApp Image 2024-01-25 at 10 59 15](https://github.com/ValveSoftware/steam-for-linux/assets/2722773/b3aad451-8bce-4416-8e82-e84659ce3188)
![steamuserimages-a akamaihd](https://github.com/ValveSoftware/steam-for-linux/assets/2722773/8c1aced8-63c5-4d57-9ebe-3e5314c12571)

Streaming from Desktop to iPhone seems to render better brightness, as the iPhone is HDR capable?
![WhatsApp Image 2024-01-25 at 11 09 05](https://github.com/ValveSoftware/steam-for-linux/assets/2722773/27b5f62d-16f4-4880-b1d6-f20d0f605a2f)

Streaming from Steam Deck to iPhone seems to have better results.
![WhatsApp Image 2024-01-25 at 11 15 39](https://github.com/ValveSoftware/steam-for-linux/assets/2722773/cdae682c-aa91-47eb-82b9-c3a5a68bb75a)

And this is how it looks when playing locally on the steam deck
![steamuserimages-a akamaihd2](https://github.com/ValveSoftware/steam-for-linux/assets/2722773/77be8527-550f-4990-8be0-9e834ac7d5d8)

#### Steps for reproducing this issue:

1. Play a streamable game from a desktop with a high resolution and HDR compatible (although no HDR enabled since plasma 5 is not hdr compatible)
2. Stream to a non HDR device, like a steam deck

**Comment by kisak-valve** [comment]
Hello @perroboc, this looks like https://github.com/ValveSoftware/SteamOS/issues/1166, can you check if switching to the preview update channel of SteamOS (for 3.5.13) resolves the issue (https://github.com/ValveSoftware/SteamOS/issues/1166#issuecomment-1880006243).

**Comment by perroboc** [comment]
Thank you @kisak-valve ! I tried the preview channel and it appears to be fixed! Will close this issue, then :)
