### ISSUE TITLE
Steam Deck  Proton and Steam Linux Runtime on internal and sd card

### ISSUE THREAD

**Issue by Zero1220** [ValveSoftware/steam-for-linux#10434]
#### Your system information
I have a Steam Deck looked at my storage to find my Internal Drive has Proton 7.0 and Steam Linux Runtime 2.0 (soldier), and my MicroSD card has the newer versions installed Proton 8.0 and  Steam Linux Runtime 3.0 is this going to cause problems if so how do I fix it.
Thank You
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Zero1220, these tools are self-contained and it shouldn't matter which medium they are on to work (provided a Linux native filesystem is in use).
