### ISSUE TITLE
Add mechanism to apply command line options globally (useful for PRIME Render Offload)

### ISSUE THREAD

**Issue by MateusRodCosta** [ValveSoftware/steam-for-linux#10439]
#### Your system information

* Steam client version (build number or date): 1706306386
* Distribution (e.g. Ubuntu): Fedora Silverblue 39 - Flatpak
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] N/A
* GPU: Intel UHD 630 + Nvidia GTX 1660 TI Mobile (Nvidia Optimus)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Depending on the scenario, it might be useful to set certain environment variables to all games at the same time, one good example is PRIME and Prime Render offload, where the user might prefer to run Steam in the iGPU but the games always in the dGPU.

If the user launches Steam in the dGPU, the games also render in the dGPU. But if Steam is launched in the iGPU, the user has to add `DRI_PRIME=1 %command%` or `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only %command%` to every single game manually.

It should be preferable to run Steam in the iGPU, as that allows the dGPU to be in low power mode or even completely turned off while the user is not currently gaming, but adding the flags can be slightly annoying, having a place where you can set global environment variables and paraters could be useful, then it would be a matter of the per-game setting using it and having an option to ignore the global values.

#### Steps for reproducing this issue:

1. N/A

**Comment by MateusRodCosta** [comment]
Partially related to  #9940

**Comment by kisak-valve** [comment]
Hello @MateusRodCosta, this issue is already being tracked at #3453. Closing as a duplicate.
