### ISSUE TITLE
In-game notifications no longer appears (screenshots and achievements notifications)

### ISSUE THREAD

**Issue by JoseZancanaro** [ValveSoftware/steam-for-linux#10441]
#### Your system information

* Steam client version (build number or date): 1705108172 - Fri, Jan 12 21:52 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux x86_64 - xfce4
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14074009/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
A few weeks ago I noticed a strange behavior with in-game notifications. In-game notifications (screenshots, achievements) disappear and no longer appear after some time (playing for hours and/or giving occasional Alt-Tabs). I recorded a video that demonstrates this strange behavior. Even though the options are properly enabled (sound and screenshot notification), it is not indicated by an in-game notification, only leaving and going to the library page.

I'm currently playing FINAL FANTASY XII THE ZODIAC AGE (595520), but this behavior also happened to me in Divinity: Original Sin - Enhanced Edition (373420). I'm usually playing with Proton-Experimental [bleeding-edge]. I believe it's not something with xfce4, as it hasn't been updated for some time. Maybe it's something from Steam or Nvidia? I'm not sure. Furthermore, this behavior doesn't bother me, but I found it curious and decided to report it.

https://github.com/ValveSoftware/steam-for-linux/assets/48338648/a7c56d54-0cfe-4f72-9e06-40f5aa8be4c8

#### Steps for reproducing this issue:

1. Start some game.
2. Play for a while and/or Alt-Tabbing to desktop.
3. screenshots and achievements work, but notifications no longer appear in-game.

**Comment by JoseZancanaro** [comment]
It seems the video in .mp4 didn't work? I'm re-sending it now in .webm

[without-notifications-in-game.webm](https://github.com/ValveSoftware/steam-for-linux/assets/48338648/d4006d1b-daa2-43dd-b82c-7e87d14185ab)

**Comment by SunRed** [comment]
I am experiencing this issue on plasma wayland as well. Proton version etc doesn't matter, it seems to happen in every game after I either tabbed out / minimized a game or used the Steam overlay a few times. In case of achievements, notifications for these are then displayed when I start the game next time when it is working again temporarily.
