### ISSUE TITLE
Show both iGPU and dGPU on System Information instead of current runnning GPU

### ISSUE THREAD

**Issue by MateusRodCosta** [ValveSoftware/steam-for-linux#10440]
#### Your system information

* Steam client version (build number or date): 1706306386
* Distribution (e.g. Ubuntu): Fedora Silverblue 39 - Flatpak
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] N/A
* GPU: Intel UHD 630 + Nvidia GTX 1660 TI Mobile (Nvidia Optimus)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Right now if you enter the System Information dialog it will only show the info from the currently in-use GPU.

If you are in a multi-GPU system and open Steam with the iGPU: only iGPU data appears, if you open with the dGPU, only info about the dGPU appears.

Ideally Steam should be able to detect both GPUs and show their information correctly.

#### Steps for reproducing this issue:

1. Have a system with more than one GPU
2. Open System Information
3. Notice that only one GPU is detected and has its infromation shown
4. Open Steam using the other GPU
5. Notice how now only the information about the other GPU is shown

**Comment by kisak-valve** [comment]
Hello @MateusRodCosta, for the purposes of basic troubleshooting of the Steam client, only the GPU that is being used with the Steam client is relevant. The current set of information is sufficient for that purpose and is consistent with other OSes.

For more in depth investigations, the Steam Runtime Diagnostics is a better set of details and that includes all GPUs.

**Comment by SyberHexen** [comment]
I think this should be revisited now that you can now attach system specs to reviews.
On hybrid systems reporting the iGPU even though you're really using a nice dGPU to actually play the games is inaccurate and misleading.
