### ISSUE TITLE
Steam download paused when sleep

### ISSUE THREAD

**Issue by dipras** [ValveSoftware/steam-for-linux#10458]
#### Your system information

* Steam client version (build number or date):  1705108172
* Distribution (e.g. Ubuntu): Kubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
My download got paused when my pc sleep. Even it's just sleep and not locked, but the download still paused

#### Steps for reproducing this issue:

1.  Download a game
2.  Wait until screen sleep
3.  Open the pc and the download got paused

**Comment by kisak-valve** [comment]
Hello @dipras, if you have a system suspend to ram (sleep), all applications are not running during that time and there's nothing the Steam client can do differently from the rest of the system. This is not a bug.
