### ISSUE TITLE
Whenever I launch the Steam client, it downloads the wrong version of the game.

### ISSUE THREAD

**Issue by solitary-sails** [ValveSoftware/steam-for-linux#10467]
#### Your system information

* Steam client version : 1705108172, Build date: Sat, Jan 13 8:52 AM UTC -08:00
* Distribution : "Arch Linux" (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14178896/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I only encountered this problem on one [game](https://store.steampowered.com/app/1052990/).
The Steam client will download the Steam play version of the game every time the client is launched instead of keeping the already downloaded Linux native version. 
After this error occurs, Steam can download the native Linux version again by turning on and off the compatibility settings in the game properties. However, the Steam Play version of the game will still be downloaded the next time you start Steam.
If I do nothing, when trying to launch the game, Steam is still trying to launch the game by launching the native version of Linux, which causes the game to fail to launch because the required file is not available.

For related settings, my specific settings are as follows:
Steam setting
	- Compatibility
		---- Enable Steam play for supported titles : on
		---- Enable Steam Play for all other titles : off
Game properties
	- Compatibility
		---- Force the use of a specific Steam Play compatibility tool : off

#### Steps for reproducing this issue:

1. Download this [game](https://store.steampowered.com/app/1052990/).
2. Enable option "Force the use of a specific Steam Play compatibility tool" in the compatibility setting of  game properties
3. Launch the game once through Steam play tool
4. Disable the options mentioned in the second step
5. Restart Steam client
6. Steam starts automatically downloading the wrong version

**Comment by kisak-valve** [comment]
Hello @solitary-sails, this issue is already being tracked at #9875. Closing as a duplicate.
