### ISSUE TITLE
Is possible block Steam client for automatically download dependencies ?

### ISSUE THREAD

**Issue by Augusto7743** [ValveSoftware/steam-for-linux#10460]
Hello.
Thanks for reading my topic.

Excuse me if here not is the correct area to post that topic. Report me and that topic will be closed.
I am a Steam client novice.

I have installed Steam for Linux in Ubuntu 20.04.6.
When I select an game to install automatically is downloaded Proton Experimental and 8.0.
However my video card is GT 640 kepler so not is exactly compatible with Proton Experimental current version and 8.0.
I need to use Proton version 7.0.
Using current settings only after that dependencies are downloaded and installed is possible install Proton 7.0.
I want avoid download Proton Experimental and 8.0 and only manually install dependencies.
Is possible to do it ?

Have an nice day.

**Comment by kisak-valve** [comment]
Hello @Augusto7743, the components of Proton are not packaged individually in Steam. If you want to experiment with that granularity, you would need to setup a build environment and manually build the individual components at the revisions you want to experiment with.

Sorry, but your hardware is not supportable with Proton going forward.

**Comment by Augusto7743** [comment]
Thanks for your reply.
I only want understand if is possible disable Steam doing automatic dependencies download when installing any game. In others words if I install an game only is done download for that game and I manually select the dependencies to install.
I understand kepler not is DX12 compatible.
However I want to use Steam with that video card for DX11 games.

**Comment by kisak-valve** [comment]
For the general intent of what you're asking here, you should be able to select Proton 7.0 (or older) as the default compatibility tool to be used with Windows based games in Steam's global settings at `Steam` -> `Settings` -> `Compatibility` -> Select the Proton version you want in the `Run other titles with:` dropdown list.

**Comment by Augusto7743** [comment]
Thanks for your reply.
I have done as you have replied above an works, but in some times automatically begin the task of download Proton current version experimental.
I undestand Steam try create and help some users so avoiding touch in settings and being easy to install games, but unhappily in some moments automatic task not are good.

Have an nice week.
