### ISSUE TITLE
Steam not starting after system update

### ISSUE THREAD

**Issue by angrypig555** [ValveSoftware/steam-for-linux#10468]
#### Your system information

* Steam client version (build number or date): latest (cant launch steam)
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs:[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14181416/steam-logs.tar.gz)
* GPU: Nvidia GTX 1070 with 545.29.06 proprietary drivers

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Yesterday before system update i played tf2, i did a full system update rebooted and steam doesnt work.
I opened steam from the desktop, nothing happened. Tried opening it from the command line, it gave me this error:
02/06 15:04:35 Init: Installing breakpad exception handler for appid(steam)/version(1705108172)/tid(6016)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

#### Steps for reproducing this issue:

1. Open steam from the terminal
2. see the error

**Comment by kisak-valve** [comment]
Hello @angrypig555, this is the same issue as #10465. Closing as a duplicate.
