### ISSUE TITLE
Cannot type in chat window without selecting it again

### ISSUE THREAD

**Issue by Ellestir** [ValveSoftware/steam-for-linux#10466]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
expected:
After opening the chat window and seeing it is in focus to be instantly able to type without moving the mouse or selecting the window again

reality:
After opening the chat window, the mouse needs to be on the window or the window has to be selected to type into the textbox.

#### Steps for reproducing this issue:

1. Right click on friend in friends list (or left click on the small arrow next to the name)
2. Then select and left click Send Message
3. The opened chat window shows the indicator and is in focus
4. It is not possible to start typing unless the mouse pointer is on the window or the window is selected again

#### Extra Info
Using Gnome with Wayland

**Comment by kisak-valve** [comment]
Hello @Ellestir, this issue is already being tracked at #9406. Closing as a duplicate.
