### ISSUE TITLE
Dropdown menus are unclickable

### ISSUE THREAD

**Issue by VoltPleiar** [ValveSoftware/steam-for-linux#10477]
#### My system info:

* Steam client version:
* Steam Beta Branch:  Stable Client
* Steam Version:  1705108172
* Steam Client Build Date:  Fri, Jan 12 9:52 PM UTC -08:00
* Steam Web Build Date:  Fri, Jan 12 2:02 PM UTC -08:00
* Steam API Version:  SteamClient021 
* Distribution (e.g. Ubuntu): Arch linux x86_64 6.7.3-arch1-2
* Opted into Steam client beta?: [Yes/No] No, and selecting it as an option requires the dropdown menu to work :(
* Have you checked for system updates?: [Yes/No] Yes, multiple times.
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] <- this won't generate a log, tried it and it failed. I will try to solve it and if I can figure out how to make it generate a log, I will post it here.
* GPU: Nvidia/Intel/AMD Nvidia GeForce GTX 1650

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist] Opened a dropdown menu, which worked, but clicking on it makes it simply disappear and will click on anything that is below the dropdown menu if it is above something else. Exceptions: the dropdown menus from the top left most corner and from the store page itself (maybe related to it being a web app) will work, but anywhere else on the library or on the steam settings menu won't.
(https://gist.github.com/)

#### Steps for reproducing this issue:

1. Select any dropdown menu from the library or steam settings
2. Try to click on them

**Comment by kisak-valve** [comment]
Hello @VoltPleiar, this issue is already being tracked at #9273. Closing as a duplicate.
