### ISSUE TITLE
CS2 doesn't launch on Linux Mint

### ISSUE THREAD

**Issue by la-dbs** [ValveSoftware/steam-for-linux#10471]
#### Your system information

* Steam client version (build number or date): not found
* Distribution (e.g. Ubuntu): Linux Mint 20 Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: not found
* GPU: Intel© Core™ i7-6600U CPU @ 2.60GHz × 2

#### Please describe your issue in as much detail as possible:
Hello,
I installed CS2 on my computer (using Linux Mint).
Unfortunately, when I launch the game, the game does not open and the button "play" goes to "cancel" or "stop" and then returns to "play".
Have you ever seen this king of issue with CS2 on Linux?
la-dbs

#### Steps for reproducing this issue:

1. Install Steam and CS2 on linux
2. Use proton experimental
3. Launch CS2

**Comment by kisak-valve** [comment]
Hello @la-dbs, we're tracking issues with games run with Proton in the Proton issue tracker, also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-1932061870.
