### ISSUE TITLE
Can't use /mnt/* as Storage Drive

### ISSUE THREAD

**Issue by willrabbermann** [ValveSoftware/steam-for-linux#10472]
#### Your system information

[steam_runtime_sys_info.json](https://github.com/ValveSoftware/steam-for-linux/files/14194754/steam_runtime_sys_info.json)

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Fedora 39
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] [logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14194592/logs.tar.gz)
* GPU: NVIDIA

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

1. Added my drive mounted at /mnt/samsung980 as a Storage Drive under Steam Settings.
2. Drive is added as External drive, showing /run/user/1000/doc/2F2ECEAB/steam instead of my declared mount point.
3. If I try installing a game to the "external drive" I get a "DISK WRITE ERROR" during space allocation. 

Here is relevant part of my fstab:
`PARTLABEL="samsung980" 			/mnt/samsung980		ext4	users,defaults,exec,auto 0 2`

**Comment by willrabbermann** [comment]
Specifically I pointed steam to /mnt/samsung980/Steam/ directory 
`drwxr-sr-x. 3 will will  4096 Feb  7 07:44 Steam`
`$ mount  -v | grep samsung
/dev/nvme0n1p4 on /mnt/samsung980 type ext4 (rw,nosuid,nodev,relatime,seclabel,stripe=32)`

**Comment by kisak-valve** [comment]
Hello @willrabbermann, please give https://github.com/flathub/com.valvesoftware.Steam/issues/1183 a read and check if that's relevant to your system.

**Comment by willrabbermann** [comment]
Hi @kisak-valve, I should have found that previous issue myself. 

solution:
1. Install Flatseal
2. 
![Screenshot from 2024-02-07 11-33-33](https://github.com/ValveSoftware/steam-for-linux/assets/105755092/650258e8-f5d4-4009-88de-c55be39c827c)

3. Add my directory to the application's filesystem permissions
![Screenshot from 2024-02-07 11-33-33](https://github.com/ValveSoftware/steam-for-linux/assets/105755092/1557076b-cc7a-4b46-992b-ee9e84e7bafe)

Thank you so much!

**Comment by rairay91** [comment]
https://github.com/flathub/com.valvesoftware.Steam/issues/1183#issuecomment-2260413362
Here is complere explanation, why even following mensioned method steam still won't use external drive for library. You follow these steps and you are good to go.
