### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by AgoraSim21** [ValveSoftware/steam-for-linux#10476]
Hello, I wanted to ask a question:
Will the Steam installer be available in .rpm for Fedora, for download from the official Steam website?
working as the .deb version, which installs additional components in the distribution, etc.

Example: Fedora Spin, Kde Plasma

Success to everyone always 👍😄

**Comment by kisak-valve** [comment]
Hello @AgoraSim21, this issue is already being tracked at #4480. Closing as a duplicate.

**Comment by AgoraSim21** [comment]
ok, thanks 😄
