### ISSUE TITLE
Steam won't remember maximized window state

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#10479]
#### Your system information

* Steam client version (build number or date): 1707518866
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14227725/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD Intel hd 3000
* Desktop Environment: KDE Plasma  5.27 X11

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

If you maximize the Steam window via its maximize button, then minimize it and restore it, it will be in an unmaximized state.
This works as expected on Steam stable channel.

#### Steps for reproducing this issue:

1. Open main steam window
2. Maximize window via maximize button
3. Minimize window via minimize button
4. Restore window via taskbar

Observed result: window is not maximized, state is lost
Expected result: window is maximized, state is as before

**Comment by iodream** [comment]
Latest Steam beta 1710198953 issue seems to be fixed. 

Fedora 39 Kde X11

**Comment by Louis2747** [comment]
still happening to me
Steam Version:  1709846872
arch KDE wayland

**Comment by kisak-valve** [comment]
Closing per @iodream's last comment.

Hello @Louis2747, if you're still seeing this issue, please open a new issue report with a full set of details requested in the issue template.

**Comment by Louis2747** [comment]
it seems to be fixed for me too now
