### ISSUE TITLE
Borderlands The Pre-Sequel won't launch with native linux build

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/steam-for-linux#10483]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No and Yes
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia RTX 3060 Ti

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The game just cannot launch with native linux build, only proton works.
Same is happen with Borderlands 2. Works only with Proton.
I even try reinstall clean Manjaro and clean Borderlands and check files too.

#### Steps for reproducing this issue:

1. Download the game
2. Start it
3. See nothingness

**Comment by kisak-valve** [comment]
Hello @deathxxx123, this issue should be reported to the game's dev(s).

Possble workarounds https://wiki.archlinux.org/title/Steam/Game-specific_troubleshooting#Borderlands_2 (and the section after that).

**Comment by deathxxx123** [comment]
Noting help. It just generating shaders and then exit.
In terminal i see steam tyring to run .exe file, but it shoud be a native? Yes?

**Comment by kisak-valve** [comment]
Check if you're encountering #9875.

**Comment by deathxxx123** [comment]
I will try some other things i could.
For now that is output when trying to launch Borderlands 2 native:
```
Fossilize INFO: Setting autogroup scheduling.
/bin/sh\0-c\0/home/death/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/death/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/death/.steam/debian-installation/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe'\0
chdir "/home/death/.steam/debian-installation/steamapps/common/Borderlands 2"
ERROR: ld.so: object '/home/death/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/death/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/death/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/death/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/death/.steam/debian-installation/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe: /home/death/.steam/debian-installation/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe: cannot execute binary file
Uploaded AppInterfaceStats to Steam
```

**Comment by deathxxx123** [comment]
Ahh that's it! As i suspect the Steam client things that is native game build, but it's not.
After switch back to proton and then back to native, i saw the game folder fill up with native linux files, then - boom, game is working!!!

**Comment by kisak-valve** [comment]
Closing in favor of #9875.

**Comment by deathxxx123** [comment]
So the FIX:
change compability to some Proton version, then back to native. And if is need, do it again.
Then watching game folder to get right files.

**Comment by deathxxx123** [comment]
Thank you my friend!!! I very hope others will see this.
