### ISSUE TITLE
gamepad input does not work in big picture beta

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#10485]
#### Your system information

* Steam client version (build number or date): 2/9/2024
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14229947/steam-logs.tar.gz)
* GPU: RX6700 XT

#### Please describe your issue in as much detail as possible:
Steam's big-picture interface does not respond to my dualsense controller.

The only thing that works is pressing the PlayStation button to open the Steam menu and the PlayStation button plus X to open the quick access menu.

I expect the dpad to navigate through the different items on the interface and the X button to select

Going back to the latest stable fixes the issue

This is similar to https://github.com/ValveSoftware/steam-for-linux/issues/10474, but Steam input does work in games for me; it's only the big picture UI that doesn't

#### Steps for reproducing this issue:

1. start steam in big picture
2. connect a controller
3. try to navigate the interface with a controller

**Comment by kisak-valve** [comment]
Hello @zany130, this issue is already being tracked at #10406. Closing in favor of the older issue report.
