### ISSUE TITLE
Helldivers 2 not launching on steamdeck after trying all the common fixes

### ISSUE THREAD

**Issue by Binksbrew123** [ValveSoftware/steam-for-linux#10498]
#### Your system information

* Steam client version (build number or date): 20231122.1
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] This doesn't work
* GPU: AMD 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I have tried every Proton version that has been said to work Including the most recent 8-32 and trying without forcing compatibility. I have increased the VRAM and tried in both game and desktop mode. I deleted the compatdata folder. I moved the game from my microSD to and external hard drive (I have the 64 gb steamdeck). The game just launches to the steam logo and then crashes. 
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Binksbrew123, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7486#issuecomment-1939895616.
