### ISSUE TITLE
Borderlands: The Pre-Sequel - native, keep reverting to windows build

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/steam-for-linux#10497]
#### Your system information

* Steam client version (build number or date): 1707518866
* Distribution (e.g. Ubuntu): Pop!_OS
* Opted into Steam client beta?: Yes and No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
This game just can't stop keeping wanted win build after every steam restart.
I use native build and play long time with no problem. After restart steam, the game want to update - to win build. To skip that, i need to change compability mode from native to Proton, wait little until start downloading something, then quick back to native build and game show's it's ready to play. And in this way i can play with native build again. This was happen with Manjaro clean install and Pop!_OS clean install, only keep hidden .steam folder to keep my games and all steam files.

#### Steps for reproducing this issue:

1. Download the game native build
2. Play if you want then restart steam client
3. Now game will ask for update. 

The steam just cannot see game build if is native or win for some reason.

**Comment by deathxxx123** [comment]
The Borderlands 2 was doing the same but it fix itself and no more revert to Proton/win build after restart.

**Comment by deathxxx123** [comment]
I do not know if i mess something when test the game with Proton build, before that it has no problem.

**Comment by kisak-valve** [comment]
Hello @deathxxx123, as previously mentioned in https://github.com/ValveSoftware/steam-for-linux/issues/10483, this issue is already being tracked at #9875. Closing as a duplicate.
