### ISSUE TITLE
Huge shader precaching updates are downloaded again

### ISSUE THREAD

**Issue by gregor3000** [ValveSoftware/steam-for-linux#10492]
#### Your system information

* Steam client version (build number or date): 
Steam Beta Branch:  Stable Client
Steam Version:  1705108172
Steam Client Build Date:  Sat, Jan 13 1:52 AM UTC -08:00
Steam Web Build Date:  Fri, Jan 12 6:02 PM UTC -08:00
Steam API Version:  SteamClient021
* Distribution (e.g. Ubuntu):  Kubuntu 22.04 LTS
* Opted into Steam client beta?: not sure, i believe no.
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14232947/steam-logs.tar.gz)
* GPU: Nvidia GTX 1650 4GB VRAM
Ryzen 5 3600, 32 GB RAM

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

This looks very similar to old issue resolved last year: https://github.com/ValveSoftware/steam-for-linux/issues/9200

The main culprit is now Counter Strike 2 since it received the largest updates, but there are other games i rarely play, that receive these as well. Sometimes small as they should be,  other times quite large (a few hundred MB). And while games such as Deep Rock Galactica do receive these (few 100 MB), they load a lot faster later on. CS currently downloads the updates twice a day at least, one of them is usually (likely) shader pre-caching update. And to load them, it occasionally takes 30 minutes or more.  I understand there are a lot of necessary updates for this game, yet this is getting a bit ridiculous. Each update is followed by another massive download. Doesn't this also put some strain on infrastructure and servers?

#### Steps for reproducing this issue:

1. Start steam
2. Downloads for shader pre-caching updates start
![shaders pre-caching update](https://github.com/ValveSoftware/steam-for-linux/assets/20200152/c33a9b0a-9a88-4871-90de-31e6fb35789c)

**Comment by kisak-valve** [comment]
Hello @gregor3000, this issue is already being tracked at #10285. Closing as a duplicate.
