### ISSUE TITLE
Borderlands: The Pre-Sequel - Authenticating with Gearbox Shift - not working

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/steam-for-linux#10490]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Cannot connect to Shift. That is ca-certificates problem. I even don't know for what certificate Borderlands is looking for. Do i have it?
I have some workaround long ago, but not working anymore now.

#### Steps for reproducing this issue:

1. Install native linux version and pair steam with gearbox shift site
2. Start game and will see the: Authenticating with Gearbox Shift - stay forever
3. You can play, but cannot get Shift keys

Maybe i can trace network on Borderlands and see what certificate is looking for and then try to provide it.

**Comment by kisak-valve** [comment]
Hello @deathxxx123, the Steam client has no influence on this particular game behavior. This needs to be reported to and evaluated by the game's dev(s).

**Comment by deathxxx123** [comment]
I will look for this, thank you again.
It seems cert is changing from time to time and every time need new workaround.
