### ISSUE TITLE
Family sharing stops working after reboot

### ISSUE THREAD

**Issue by chikenpotpi** [ValveSoftware/steam-for-linux#10505]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: none

#### Please describe your issue in as much detail as possible:
Family sharing stops allowing me to borrow the other accounts games after reboots. Happens on the steam-runtime package and the flatpak version aswell.

#### Steps for reproducing this issue:

1. Family share steam account games to another.
2. Reboot.
3. Check Steam to see if you can borrow games from the other account.

**Comment by kisak-valve** [comment]
Hello @chikenpotpi, this issue is already being tracked at #9918. Closing in favor of the older issue report.
