### ISSUE TITLE
steamwebhelper crashing repeatedly on launch, client will not open at all

### ISSUE THREAD

**Issue by yumio7** [ValveSoftware/steam-for-linux#10514]
#### Your system information

* Steam client version (build number or date): Unknown (cannot open client to check), package manager listing 'steam 1.0.0.78-2'
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14336249/steam-logs.tar.gz)
* GPU: Nvidia

[inxi -F](https://github.com/ValveSoftware/steam-for-linux/files/14336260/sysinfo.txt)

#### Please describe your issue in as much detail as possible:
As of a few days ago steam was working normally, but one night it wouldnt launch. Since then it has not worked at all. When I launched it from the command line it looked like the webhelper was launching repeatedly, or crashing, I'm not entirely sure. Sometimes I get the "steamwebhelper is not responding" box but none of the options fix the issue. I've reinstalled my nvidia drivers, vulkan and everything, including the app itself. Only thing I can get to launch is the flatpak version (duh) but even steam-runtime wont work. The most ive ever seen is the "Updating Steam" window followed by nothing (or the steamwebhelper crash window).

I appologize if there is already an issue open for this, I've looked thru a bunch but most of the related ones are from almost a year ago, and none of the proposed solutions in them worked.

#### Steps for reproducing this issue:

1. Launch steam
2. Observe webhelper crash

**Comment by GoDev87** [comment]
I have the same problem on Fedora 39 with steam in or out publicbeta.

**Comment by TTimo** [comment]
Hello @yumio7,

Your `steamwebhelper.log` reports `FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.` which could indicate an issue with your graphics drivers configuration.

You can try to disable GPU acceleration in the Steam client as a workaround by setting `-cef-disable-gpu` on the Steam command line.

**Comment by yumio7** [comment]
I had attempted to use that to the same result as stated above.

**Comment by TTimo** [comment]
Please update to the Steam beta client and check if the same problem occurs? (Steam -> Settings -> Interface -> Client Beta Participation)

**Comment by yumio7** [comment]
@TTimo I explicitly stated in my issue that I cannot open the client.

**Comment by TTimo** [comment]
Oh err .. I guess you can't do that if you are not able to bring up the UI either. There's a manual way to do it: `echo publicbeta > ~/.steam/steam/package/beta`

**Comment by crumblingstatue** [comment]
> Oh err .. I guess you can't do that if you are not able to bring up the UI either. There's a manual way to do it: `echo publicbeta > ~/.steam/steam/package/beta`

I did this, and the behavior is still the same (Arch Linux)
#10538 is probably a duplicate of this

**Comment by yumio7** [comment]
Behavior still the same for me too after switching to the beta.

**Comment by FedeAbella** [comment]
I'm having this same issue now on Ubuntu 23.10, after latest update (ran Steam perfectly earlier today on a different user on the same pc, but steam is globally installed, so I'm guessing this appeared for me after some update I received today)

**Comment by FedeAbella** [comment]
Switching to the beta in the terminal using @TTimo's command **and restarting afterwards** worked for me

**Comment by TTimo** [comment]
The stable client shipped just a short while ago. There should be no functional difference between beta and stable right now.

**Comment by ieyi4ooPAig1ui5U** [comment]
Perhaps it could have something to do with this childish nonsense?

```
steamwebhelper.sh[20212]: === Tue Feb 27 05:23:29 PM PST 2024 ===
steamwebhelper.sh[20212]: Starting steamwebhelper under bootstrap sniper steam runtime at /usr/local/games/steam_linux/ubuntu12_64/steam-runtime-sniper
pressure-vessel-wrap[20232]: W: Binding directories that are located under "/usr/" is not supported!
bwrap: Can't chdir to /usr/local/games/steam_linux/ubuntu12_64: No such file or directory

```

**Comment by kisak-valve** [comment]
Hello @ieyi4ooPAig1ui5U, https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#usrlocal is now relevant to your system now that steamwebhelper is being run in the Steam Linux Runtime - Sniper container environment. Your issue is unrelated to the issue reported in this issue report.

**Comment by crumblingstatue** [comment]
Interestingly, a fresh install of the flatpak version (`com.valvesoftware.Steam`) does produce a working version for me, even though https://github.com/flathub/com.valvesoftware.Steam/issues/1251 talks about the same issue with steamwebhelper on the flatpak version.

**Comment by TTimo** [comment]
@crumblingstatue please try something like this: `mv ~/.local/share/Steam ~/.local/share/Steam.off` then launch steam native. That will do a fresh install, do you get a functional setup if you do this?

If that works, please save an archive of `~/.local/share/Steam.off` for me! (minus `steamapps/` .. likely don't need that).

**Comment by zer0def** [comment]
In my case, after peeking into `~/.steam/steam/logs/steamwebhelper.log`, I was greeted by a familiar CEF warning:

```
pressure-vessel-wrap[3835945]: E: Cannot run /usr/bin/bwrap: wait status 256
pressure-vessel-wrap[3835945]: E: Diagnostic output:
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```

Whether that's something acceptable to the user up to their discretion.

**Comment by crumblingstatue** [comment]
> @crumblingstatue please try something like this: `mv ~/.local/share/Steam ~/.local/share/Steam.off` then launch steam native. That will do a fresh install, do you get a functional setup if you do this?

No, that doesn't work. It prompts me to reinstall, and I let it reinstall Steam, and then after I still get the steamwebhelper crash.

**Comment by TTimo** [comment]
thanks @crumblingstatue - you might want to open a separate issue and provide your own logs and system info. Make sure to try `-cef-disable-gpu` (it looks like we are tracking something unrelated to GPU accel though).

If your system is setup to collect crashes (`coredumpctl`) you could check for `steamwebhelper` crashes and provide the `coredumpctl debug` output for some of those?

**Comment by FedeAbella** [comment]
> Switching to the beta in the terminal using @TTimo's command **and restarting afterwards** worked for me.
> 
> Edit: It definitely didn't work right after moving to beta, until I restarted everything

Welp, after this solved it for me yesterday, it's now back to being broken for me. 

@TTimo is there something else that needs trying I can help with? I'm on Ubuntu 23.10.

**Comment by TTimo** [comment]
@FedeAbella please open a separate issue and provide your logs, thank you.

**Comment by DocMAX** [comment]
![grafik](https://github.com/ValveSoftware/steam-for-linux/assets/5351323/14a3fb1f-a8a2-4ba3-9da9-368d5f35d9cc)
Since some update Steam doesn't start. Always crashing.
The only log entry is:
```
steamwebhelper.sh[8735]: === Sun Mar  3 11:21:21 CET 2024 ===
steamwebhelper.sh[8735]: Starting steamwebhelper under bootstrap sniper steam runtime at /mnt/pve/data/syncthing/linux/profile/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
pressure-vessel-wrap[8755]: E: Could not create copy "./etc/ld.so.cache" from "/mnt/pve/data/syncthing/linux/profile/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/sniper_platform_0.20240212.77547/files/./etc/ld.so.cache" into "/mnt/pve/data/syncthing/linux/profile/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-BPUXJ2/usr": fstatat(./etc/ld.so.cache): No such file or directory

```

**Comment by yumio7** [comment]
As of upgrading to nvidia drivers v. 550.54.14 the issue is still persisting. Only the flatpak version of the client works on my machine still.

**Comment by yumio7** [comment]
Turns out this issue was related to Hyprland, my WM. I've since switched to swayfx and it works perfectly again. Closing this issue as its not related to steam itself.

**Comment by tjbp** [comment]
I had this same issue and tracked it down to a change I'd just made to try and get my Nvidia drivers working with Wayland. `__GLX_VENDOR_LIBRARY_NAME` was set to `nvidia` in those changes, and running `__GLX_VENDOR_LIBRARY_NAME= steam-runtime` got Steam running again.

**Comment by Keelhauled** [comment]
Also had this issue on hyprland and fixed it by moving the `.local/share/icons` folder. Quite odd it worked because flatpak steam is not even supposed to have access to it.

**Comment by NoahIles** [comment]
> Also had this issue on hyprland and fixed it by moving the `.local/share/icons` folder. Quite odd it worked because flatpak steam is not even supposed to have access to it.

this fixed it... I have no idea how you figured this out.

**Comment by alex190291** [comment]
> Also had this issue on hyprland and fixed it by moving the `.local/share/icons` folder. Quite odd it worked because flatpak steam is not even supposed to have access to it.

what the actual fuck... i searched 3 days before i found this post.... Thank you so much for this. It makes no sense and it absolutely works. You are a legend!
