### ISSUE TITLE
Sugestao de configuracao

### ISSUE THREAD

**Issue by AgoraSim21** [ValveSoftware/steam-for-linux#10524]
Ola, queria sugerir a Steam, a adicionar nas configuracoes de controle, para utilizar os simbolos dos botoes da Playstation em qualquer joystick, como X L3 R3 L1 etc, em qualquer jogo
Para correção nos joysticks genéricos, que são baseados no playstation, e  que nos jogos ficam com símbolos da xbox.
exemplo: joysticks generico estilo Ps3, Ps2

**Comment by kisak-valve** [comment]
Hello @AgoraSim21, this issue is already being tracked at #8746. Closing as a duplicate.

**Comment by AgoraSim21** [comment]
Ok Kisak, obrigado, sucesso por ai sempre
