### ISSUE TITLE
Non-functional GTK print dialog invocable after double-right click on context menu.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ValveSoftware/steam-for-linux#10529]
1.	#### **Your system information**

	

	Question                                               | Answer
	-------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	**Steam client version**  | **https://download.opensuse.org/repositories/openSUSE:/Factory:/NonFree/standard/x86_64/steam-1.0.0.79-1.1.x86_64.rpm** <br></br> <div class="tg-wrap"><table><tbody><tr><td><b>Build number</b></td><td>1708727058</td></tr><tr><td><b>Client build date</b></td><td>Fri, Feb 23 20:16 UTC -08:00</td></tr></tbody></table></div>
	**Distribution**                 | `cpe:2.3:o:opensuse:tumbleweed:20240222:*:*:*:*:*:*:*`
	**Opted into Steam client beta?**                      | Yes
	**Have you checked for system updates?**               | Yes
	**GPU**                                                | XFX AMD Radeon RX 5700 from https://www.amazon.co.uk/XFX-Radeon-5700-Boost-Ultra/dp/B07XVMXBQW

	

1.	#### **Steam Logs**

	<details>

	<blockQuote>

	</blockQuote>

	</details>
	
1.	#### **Steps for reproducing this issue**
	
	1.	Use the secondary mouse button to invoke a context menu on "Library" > ("Download" or "Home") cover art to invoke a context menu.
	1.	Perform the same on that context menu.
	1.	Select "Print".
	1.	Attempt to print.
		> ![20240224T130121GMT](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/99e173c0-38e7-43a9-93cb-e6c7e7fa7f87)

1.	#### **Please describe your issue in as much detail as possible**

	Nothing is printed.

**Comment by kisak-valve** [comment]
Hello @RokeJulianLockhart, this is the same issue as #10488 where there's an additional unintended context menu in some situations. Closing in favor of the older issue report.

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-1962398077`](https://github.com/ValveSoftware/steam-for-linux/issues/10529#issuecomment-1962398077)

@kisak-valve, this remains, despite [`issues/10488#issuecomment-2105386720`](https://github.com/ValveSoftware/steam-for-linux/issues/10488#issuecomment-2105386720):

<p></p><img width="1279" height="689" alt="Image" src="https://github.com/user-attachments/assets/bde265d9-578d-48a1-b8ee-a212e0bf2da4" /><p></p>

[`issues/11784#issuecomment-3401400393`](https://github.com/ValveSoftware/steam-for-linux/issues/11784#issuecomment-3401400393) provides environment information.

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-3401525859`](https://github.com/ValveSoftware/steam-for-linux/issues/10529#issuecomment-3401525859)

Actually, this issue isn't accurate anymore, because it now functions. [^1]

[^1]: [`user-attachments/files/22908122/output.pdf`](https://github.com/user-attachments/files/22908122/output.pdf)
