### ISSUE TITLE
Downloading games causes temporary HDD "destruction"

### ISSUE THREAD

**Issue by Oreeeee** [ValveSoftware/steam-for-linux#10523]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Debian 12
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14376943/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
When downloading or updating a game, after some time the installation will stop and say "Not enough free disk space". When trying to resume downloading I get "Disk Write Error". I'm having issues accessing the drive and I'm having a very typical dead HDD symptoms: my file explorer freezes when accessing it, ls on it is very slow, etc. When checking the drive's SMART I get a lot of errors, but none in the attributes. The errors disappear after a reboot and I can access all the data just fine. The drive is an WD10EZEX with an entire drive formatted to Btrfs. This only happens when downloading/updating games in Steam. I'm very sure the hard drive is fine.

#### Steps for reproducing this issue:

1.  Start downloading/updating a game to a Btrfs formatted HDD.
2.  Wait for some time.

**Comment by kisak-valve** [comment]
Hello @Oreeeee, this reads more like a btrfs or general out-of-storage issue that should be discussed on your distro's user forums (or other appropriate medium).

Some of btrfs's filesystem features like snapshots can leave you with less free space than you'd expect at first glance and you should verify if the out of disk space is legitimate from normal use of the filesystem. Also, Western Digital Blue series drives have had a history of being moderate or lower quality with a corresponding reduction in price to match that. For posterity, can you be more specific with the SMART errors you're seen with the hard drive?

**Comment by Oreeeee** [comment]
For now there are no SMART errors logged because I rebooted, but I'm gonna start downloading some games so that I can trigger it again

**Comment by Oreeeee** [comment]
I got it to trigger again, here is a part of the SMART error log
```
Error 15692 occurred at disk power-on lifetime: 8951 hours (372 days + 23 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  04 61 02 00 00 00 a0  Device Fault; Error: ABRT

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  ef 10 02 00 00 00 a0 08      00:10:49.636  SET FEATURES [Enable SATA feature]
  ec 00 00 00 00 00 a0 08      00:10:49.636  IDENTIFY DEVICE
  ef 03 46 00 00 00 a0 08      00:10:49.635  SET FEATURES [Set transfer mode]
  ef 10 02 00 00 00 a0 08      00:10:49.635  SET FEATURES [Enable SATA feature]
  ec 00 00 00 00 00 a0 08      00:10:49.634  IDENTIFY DEVICE
```

I'm gonna also check is the drive fine for sure

**Comment by Oreeeee** [comment]
The error just happened for me outside of Steam when doing a read/write heavy operation. I'm gonna close the issue for now since it's most likely not Steam related
