### ISSUE TITLE
For the last few months I was able to run Steam at least with the network connection disconnected, now it's impossible to run at all

### ISSUE THREAD

**Issue by EvgenyKV** [ValveSoftware/steam-for-linux#10539]
* 1.0.0.79-1
* Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: no logs
* GPU: AMD

For the last few months I was able to run Steam at least with the network connection disconnected, now it's impossible to run at all

**Comment by EvgenyKV** [comment]
steam -udpforce

it's hеlping

**Comment by kisak-valve** [comment]
Hello @EvgenyKV, what ISP are you using?

**Comment by EvgenyKV** [comment]
> Hello @EvgenyKV, what ISP are you using?

I don't even know what it is
I can provide that link
https://github.com/ValveSoftware/steam-for-linux/issues/10297#issuecomment-1925896824

**Comment by kisak-valve** [comment]
For clarity, ISP is short for internet service provider. What company are you using to connect to the internet?

**Comment by kisak-valve** [comment]
Thanks, that makes this the same issue as #10297 and is a regional issue with either dom.ru or with another company they use in their backend infrastructure to connect to Valve's servers.

Closing in favor of #10297.
