### ISSUE TITLE
Steam client only loads correctly when opening from terminal

### ISSUE THREAD

**Issue by bmhieserich** [ValveSoftware/steam-for-linux#10536]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): KDE Neon 5.27
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: https://github.com/ValveSoftware/steam-for-linux/files/14413986/steam-logs.tar.gz
* GPU: AMD Radeon RX 6400

#### Please describe your issue in as much detail as possible:
The Steam client will not open correctly when launched by any method except through the terminal. I have tested using the icon on the KDE task manager as well as through the KDE application launcher. What happens is that Steam does login and the icon appears in the system tray, but the actual client window continually attempts to load but immediately crashes before fully loading. This repeats every few seconds until the client is closed via the system tray icon.  When launched through the terminal, everything works as intended.

I have found the workaround to set `PrefersNonDefaultGPU=false` and this workaround does work; however, this leaves the side effect that I am unsure whether games will actually launch using the RX 6400 GPU.  While I do not play many graphically-intensive games myself (hence using a GPU that does not require (or provide) a lot of power), this may leave other users who experience the same issue needing to launch from the terminal to play those graphically intensive games unless this issue is resolved without the need for a workaround. This should also be resolved purely for the sake of convenience for those who prefer GUI interface.

#### Steps for reproducing this issue:

1. Attempt to launch Steam client from task manager or application launcher
2. Observe issue of client repeatedly failing to launch correctly
3. Open within terminal to correctly launch the client

**Comment by kisak-valve** [comment]
Hello @bmhieserich, this issue is already being tracked at #9383. Closing as a duplicate.
