### ISSUE TITLE
Problems with non-steam games and Big Picture on Linux

### ISSUE THREAD

**Issue by RickMarijn** [ValveSoftware/steam-for-linux#10530]
#### Your system information

* Steam client version (build number): 1708727058
* Distribution: Fedora 39
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: Bottom of issue
* GPU: AMD

#### Please describe your issue in as much detail as possible:

The new big picture UI doesn't change focus/ overlay properly with non-steam games.
I have Steam installed from the RPM Fusion repository and I've added a Dolphin Emulator game as a non-steam game:

flatpak run org.DolphinEmu.dolphin-emu -e "/home/rm/Games/Dolphin/New Super Mario Bros. Wii.wbfs"

(I have bought the game and have it on disc. I ripped it from my modded Wii. I LEGALLY OWN IT PLEASE DON'T BAN MY ACCOUNT)

It launches and closes properly, but when I try to open the menu using the guide button on my dualshock 4, I can hear it opening, and I can alt+tab to the menu, but in BeamNG which I installed as a steam-native game the overlay behaves, i assume, correctly by somewhat blurring the game and I don't have to alt+tab into the menu. This also happens when trying to launch a Windows game using proton.

#### Steps for reproducing this issue:

1. Install Steam from RPM-Fusion repository
2. Add non-steam game 
3. Launch from big picture
4. Open menu (guide button on dualshock)
5. Menu opens behind game

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14394279/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @RickMarijn, this issue is already being tracked at #8952. Closing in favor of the older issue report.
