### ISSUE TITLE
Black Screen Working Menus

### ISSUE THREAD

**Issue by Wazzzzuzp** [ValveSoftware/steam-for-linux#10546]
#### Your system information

* Steam client version : 28/2/2024
* Distribution (e.g. Ubuntu): Mint Mate 21.3
* Opted into Steam client beta?: NO
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14431042/steam-logs.tar.gz)
* GPU: Nvida 3070 ver 545.29.06

#### Please describe your issue in as much detail as possible:
Opened Steam today and it updated.
It installed the update and rebooted.
On reopening Steam was a black screen with working menus.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/135710766/455d1821-91a8-4f9f-9613-3af0eb92058b)

#### Steps for reproducing this issue:
1. Open Steam
2. 
3.

**Comment by lucifertdark** [comment]
Go to the settings & check to see if GPU accelerated rendering is activated. It was for me when I had that black screen, switching it off fixed it.

**Comment by BoiLudens** [comment]
@lucifertdark thank you so much, was experiencing this on x11 on arch and downgrading my nvidia drivers to 545.29.06 had done nothing. Turning off GPU Accelerated rending was the ticket!

**Comment by Wazzzzuzp** [comment]
> Go to the settings & check to see if GPU accelerated rendering is activated. It was for me when I had that black screen, switching it off fixed it.

Worked perfectly, thank you for taking the time to reply.

**Comment by Wazzzzuzp** [comment]
@lucifertdark solution worked.

**Comment by BoiLudens** [comment]
Is this something that should be closed, the original configuration seems like it broke in between updates @lucifertdark

**Comment by mcnuggetsx20** [comment]
I don't think disabling GPU acceleration is a satisfying solution. The option is very much needed when you want to use Big Picture for instance. Without acceleration it lags terribly. That is to say we have only found a workaround and not an actual solution.
