### ISSUE TITLE
Steam store web portal error code: -105 with systemd-resolved

### ISSUE THREAD

**Issue by nexussapphire** [ValveSoftware/steam-for-linux#10550]
#### Your system information

* Steam client version (build number or date): 1708985249
* Distribution (e.g. Ubuntu): archlinux(Hyprland)
* Opted into Steam client beta?: No
* Have you checked for system updates?:Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14440987/steam-logs.tar.gz)

* GPU: Nvidia
![screenshot, store tab](https://github.com/ValveSoftware/steam-for-linux/assets/154363034/740ff9de-7cdb-4095-a572-a3b7b7917aed)

#### Please describe your issue in as much detail as possible:
The builtin web browser shows Error code: -105 when clicking on any tab other than library. Sometimes clicking store, community, or username causes the application to crash taking the desktop with it. The library tab works like it should and with the  [stayfocused](https://wiki.hyprland.org/Configuring/Window-Rules/#static-rules) the options bar at the top works.

I have [iwd](https://iwd.wiki.kernel.org/) in standalone mode with systemd-resolved as the nss resolver.
#### Steps for reproducing this issue:

1. open app
2. click store(or have it load as default) get -105 error or have it hang while loading.
3. click another web portal tab potentially causing a hang or a full crash.

**Comment by RyuzakiKK** [comment]
One interesting piece of information from your logs seems to be this one:
```
[0228/174011.441119:ERROR:angle_platform_impl.cc(43)] Display.cpp:1021 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1404.
[0228/174011.441178:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1404.
[0228/174011.441213:ERROR:gl_display.cc(932)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[0228/174011.441242:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[0228/174011.442017:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0228/174011.446601:INFO:crash_reporting.cc(262)] Crash reporting enabled for process: gpu-process
[0228/174011.448246:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```

**Comment by nexussapphire** [comment]
I commented out env ELECTRON_OZONE_PLATFORM_HINT=wayland and then rebooted my computer but that didnt work. I saw ``` [0228/174011.441242:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed ``` so it was worth a try.

I have an environment variables forcing gbm backend but it's necessary for wlroots compositor to work from what I understand. ``` GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia ```

Here's vulkaninfo if you need it 
[vulkaninfo.log](https://github.com/ValveSoftware/steam-for-linux/files/14449251/vulkaninfo.log)

**Comment by nexussapphire** [comment]
Systemd-resolved was the problem. I don't know what exactly caused it but disabling built in network configuration in iwd, disabling systemd-resolved, and installing dhcpcd for the back end of iwd fixed the problem. 

I discovered it while trying to get the printer setup working. Apparently systemd-resolved causes issues for avahi too.

**Comment by nexussapphire** [comment]
Yeah most desktop environment moved from EGL streams to GBM on Nvidia at some point. Support was almost non-existent when Nvidia didn't support GBM.

**Comment by MichalKolasinski** [comment]
Hi there. 

Is there some way to make this work without replacing systemd-resolved? 

For me too steam started showing the 105 error after a system update. But name resolution is working as expected everywhere, so it seems that this is steam related. I think it would be great to know the exact reason for this problem so it can be solved without replacing the name resolution service?

Please help!

**Comment by nexussapphire** [comment]
> Hi there.
> 
> Is there some way to make this work without replacing systemd-resolved?
> 
> For me too steam started showing the 105 error after a system update. But name resolution is working as expected everywhere, so it seems that this is steam related. I think it would be great to know the exact reason for this problem so it can be solved without replacing the name resolution service?
> 
> Please help!

Not my issue anymore, good luck @MichalKolasinski

**Comment by janhradek** [comment]
Had the same problem on Archlinux. https://wiki.archlinux.org/title/Systemd-resolved#DNS helped with it, i.e. symlinking  /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf. Although the file existed on my system (from the filesystem package) it was basically empty which breaks DNS resolution for applications that "still" use it, like steam. Linking to the stub (as described on the link) fixed it.

**Comment by MichalKolasinski** [comment]
Yess, i can confirm this solved the problem. (I'm on arch too)

- delete /run/resolv.conf + reboot + start steam = Error Code - 105
- ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf + reboot + start steam = Everything working fine again. :)

Thank you!!

**Comment by GhostDog98** [comment]
> Had the same problem on Archlinux. https://wiki.archlinux.org/title/Systemd-resolved#DNS helped with it, i.e. symlinking /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf. Although /etc/resolv.conf existed on my system (from the filesystem package), it was basically empty, which breaks DNS resolution for applications that seem to "still?" use it (directly), like steam. Linking to the stub (as described on the link) fixed it.

TYSM, ridiculous that this is still an issue months later, just encountered it myself. For me, it also knocked out all game networking (multiplayer stopped working on DRG entirely).

**Comment by DrQwertySilence** [comment]
This happened to me couple days ago (I'm on Arch too). I'm glad I found this thread. As @GhostDog98 mentioned, multiplayer functionality is disable when the problem is active.

**Comment by Damglador** [comment]
I have this on my system (Arch Linux/KDE Plasma), but the weirdest thing is it goes away if I restart Steam. Sometimes the first start of Steam just borks inbuilt browser with -105 error, but just restarting Steam always fixes the issue

**Comment by GhostDog98** [comment]
Somewhat humorously, the only consistent fix I've been able to find has been to uninstall all wireless communication software from my desktop PC. 
P.s. We're at just over 300 days of this issue being open without a consistent fix, yay!

**Comment by looowizz** [comment]
Would love to see a fix for this!

**Comment by Kolgann** [comment]
I also had this exact error, and I also resolved it with this solution. Thank you! Also why is this still an issue after more than a year?? Is this a steam problem, or a systemd-resolved problem?

> Yess, i can confirm this solved the problem. (I'm on arch too)
> 
> * delete /run/resolv.conf + reboot + start steam = Error Code - 105
> * ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf + reboot + start steam = Everything working fine again. :)
> 
> Thank you!!

**Comment by gabriel-ataide-sudo** [comment]
> Yess, i can confirm this solved the problem. (I'm on arch too)
> 
>     * delete /run/resolv.conf + reboot + start steam = Error Code - 105
> 
>     * ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf + reboot + start steam = Everything working fine again. :)
> 
> 
> Thank you!!

Had the same issue today on Debian 12, this solved it.

**Comment by tsokano** [comment]
> Yess, i can confirm this solved the problem. (I'm on arch too)
> 
>     * delete /run/resolv.conf + reboot + start steam = Error Code - 105
> 
>     * ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf + reboot + start steam = Everything working fine again. :)
> 
> 
> Thank you!!

Works for me too!
Thanks
