### ISSUE TITLE
steamwebhelper and pressure-vessel no version info available

### ISSUE THREAD

**Issue by T-Quill** [ValveSoftware/steam-for-linux#10555]
#### Your system information

* Steam client version (build number or date): Flatpak version 1.0.0.78
* Distribution (e.g. Ubuntu): Alpine, Sway
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: see bottom of post
* GPU: AMD

Hello! A few days ago I was unable to start Steam when normally I could. I get the same error I've seen reported with the steamwebhelper popup, but I didn't see anyone's logs having the same error, so I thought I'd add in with my log. Downgrading the flatpak version did not help, nor did deleting my flatpak install manually and reinstalling. 

I've pasted two logs. One is my steamwebhelper log, which mentions that pressure-vessel does not have a version information available (required by /bin/bash). The other is just what happens when I run 'flatpak --user run com.valvesoftware.Steam'. Please note that once it starts repeating the call to start steamwebhelper I control-C a few times to end the process and collect the log. 

https://gist.github.com/T-Quill/e4df450dba966fded2922c3ff49f825b

**Comment by kisak-valve** [comment]
Hello @T-Quill, this is the same issue as #10554. Closing as a duplicate.

**Comment by smcv** [comment]
> ```
> /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
> ```

This particular message is only a warning, you can safely ignore it.

> pressure-vessel has no version information available

No, it's libtinfo.so.6 that has no version information available.

**Comment by smcv** [comment]
> ```
> [0229/171528.050338:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
> [0229/171528.050350:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
> ```

This is the fatal error, and yes, it appears to be the same as #10554.

**Comment by T-Quill** [comment]
Thank you for explaining! It makes me feel better that my error wasn't an oddity lol, appreciate it
