### ISSUE TITLE
Steam client fails to start due to steamwebhelper not responding.

### ISSUE THREAD

**Issue by CGeorgiades** [ValveSoftware/steam-for-linux#10560]
#### Your system information

* Steam client version (build number or date): 1708985249
* Distribution (e.g. Ubuntu): Arch Linux / Wayland / Hyprland
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14454353/steam-logs.tar.gz)

* GPU: AMD 6600

#### Please describe your issue in as much detail as possible:

When launching the steam client, it fails to do so. After a moment, it shows a popup stating that "steamwebhelper is not responding," along with some options to select to try and solve the issue. None of the option fix the problem.

The start of the crash appears to be from this line in the steam stdout: 
`src/steamUI/steamuisharedjscontroller.cpp (546) : Failed creating offscreen shared JS context`

Full error description and logs, additional troubleshooting steps that have been unsuccessful, as well as the core dump stack traces for convencience:
https://gist.github.com/CGeorgiades/c4cc2bb3e9fb916f90655c0ccac32545

Core dumps files via `coredumpctl`:
[gldriverquery.dump.gz](https://github.com/ValveSoftware/steam-for-linux/files/14454281/gldriverquery.dump.gz)
[steamwebhelper.dump.gz](https://github.com/ValveSoftware/steam-for-linux/files/14454261/steamwebhelper.dump.gz)

It appears that gldriver query fails once, and steamwebhelper is being tried and tried again by the steam command, generating an identical dump each time.

For all logs/dumps here, steam was ran from the commandline with `steam -cef-verbose-logging -cef-verbose-js-logging -cef-full-memory-crash-report`

#### Steps for reproducing this issue:

1.  Launch steam client.
2.  Wait for pop-up about steamwebhelper not responding.

**Comment by rustysack** [comment]
i've got this exact same issue and have tried the same steps to resolve - removing my steam install and starting over.  i have also tried reverting from nvidia 535 to 525 driver to no avail.

i'm on gentoo, nvidia proprietary drivers.  also using wayland.

**Comment by DoomSlinger** [comment]
I this same issue issue, but for me it's only on the second user I created that doesn't have sudo privileges. Tried many of the things people have posted in other threads with no luck.

**Comment by adoa** [comment]
Are there any symlinks in place that the steam runtime container might be tripping over?
see also #10552 and #10548

**Comment by DoomSlinger** [comment]
> Are there any symlinks in place that the steam runtime container might be tripping over? see also #10552 and #10548

Possibly?

All my games are on a separate ssd that is shared between windows and linux. There is a simlink that points to my compatdata folder which is on my linux ssd so that proton works properly.

This symlink is used by both users (as it points to a folder that both users can edit).

**Comment by smcv** [comment]
> All my games are on a separate ntfs ssd that is shared between windows and linux

Any issue involving steamwebhelper is about things that happen inside Steam itself, which happens before any games in your Steam Library can be started (or even accessed at all).

The problem situation with symlinks seen in https://github.com/ValveSoftware/steam-for-linux/issues/10552 and https://github.com/ValveSoftware/steam-for-linux/issues/10548 is that users whose `~/.config` is a symbolic link into a non-standard top-level directory were seeing a crash. More details at https://github.com/ValveSoftware/steam-for-linux/issues/10547#issuecomment-1972901294. A fix is in progress for this, but if that is the reason for the crash you are seeing, you can avoid it by using bind-mounts instead of symlinks.

**Comment by smcv** [comment]
> i've got this exact same issue

Sorry, nobody can say this with a high level of confidence, particularly not without looking at logs in detail. You can have the same *symptom* - the steamwebhelper crashing - but there are multiple reasons why that can happen, and solving one of those reasons will not help users who have the same symptom for a different reason.

**Comment by smcv** [comment]
@CGeorgiades: I confirm that your log looks like a crash internal to steamwebhelper: the Steam Linux Runtime container is starting up successfully, but steamwebhelper has crashed after that point.

It is possible that this is the same issue involving symlinks as https://github.com/ValveSoftware/steam-for-linux/issues/10552 and https://github.com/ValveSoftware/steam-for-linux/issues/10548. It is also possible that this is something different: there isn't enough information available to tell either way. A Valve developer might be able to get more information from the crash dump that was uploaded, ` CrashID=bp-6edbc58f-7db4-4955-a6f5-a6caf2240228`.

**Comment by rustysack** [comment]
> > i've got this exact same issue
> 
> Sorry, nobody can say this with a high level of confidence, particularly not without looking at logs in detail. You can have the same _symptom_ - the steamwebhelper crashing - but there are multiple reasons why that can happen, and solving one of those reasons will not help users who have the same symptom for a different reason.

fair enough, technically i can't confirm it's the exact same issue.  it's the same behaviour from my user point of view though.

the other bugs that have been shared (10552 and 10548) point to symlinks being the issue.  in my case, there are no symlinks involved that i am aware of (none created by me).  my home directory is an nfs mount.

if there are additional pieces of info i can offer, please let me know.  happy to share whatever i can to help get this addressed.  we pay money for some of these games and can't play them, which is a bit frustrating.

**Comment by kisak-valve** [comment]
Hello @rustysack, you might be seeing something closer to #10431.

**Comment by CGeorgiades** [comment]
@adoa 
> Are there any symlinks in place that the steam runtime container might be tripping over? see also #10552 and #10548

I hadn't seen #10552 - my home .config directory is a symlink to a separate filesystem. Using a bind mount instead of a symlink allows steam to launch normally.

As a side note, I am still getting the crashes on gldriverquery. It appears to be unrelated, but is not causing me any real trouble so I will be ignoring it.

Closing as a duplicate of #10552. Hopefully my core dumps will help someone pinpoint the issue.
