### ISSUE TITLE
Steamwebhelper is not responding for ubuntu

### ISSUE THREAD

**Issue by letorresl** [ValveSoftware/steam-for-linux#10562]
#### Your system information

Hardware Model: ASUS PRIME A320M-K
Memory: 40 GiB
Processor: AMD Ryzen 5 2400G
Graphics: NVIDIA GeForce GTX 1660 Ti

* Steam client version (build number or date): newest
* Distribution (e.g. Ubuntu): Ubuntu 22.04.4 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14456483/steam-logs.tar.gz)
* GPU: Nvidia

#### Steps for reproducing this issue:

1. Starting steam: STEAM_LINUX_RUNTIME_VERBOSE=1 steam

`steam.sh[147866]: Running Steam on ubuntu 22.04 64-bit
steam.sh[147866]: STEAM_RUNTIME is enabled automatically
setup.sh[148004]: Steam runtime environment up-to-date!
steam.sh[147866]: Steam client's requirements are satisfied
tid(148069) burning pthread_key_t == 0 so we never use it
[2024-02-29 22:32:36] Startup - updater built Feb 29 2024 00:39:10
[2024-02-29 22:32:36] Startup - Steam Client launched with: '/home/luis/.local/share/Steam/ubuntu12_32/steam'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
02/29 22:32:36 Init: Installing breakpad exception handler for appid(steam)/version(1709168962)/tid(148069)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2024-02-29 22:32:36] Loading cached metrics from disk (/home/luis/.local/share/Steam/package/steam_client_metrics.bin)
[2024-02-29 22:32:36] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2024-02-29 22:32:36] Using the following download hosts for Public, Realm steamglobal
[2024-02-29 22:32:36] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-02-29 22:32:36] Checking for update on startup
[2024-02-29 22:32:36] Checking for available updates...
[2024-02-29 22:32:36] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2024-02-29 22:32:36] Manifest download: send request
[2024-02-29 22:32:36] Manifest download: waiting for download to finish
[2024-02-29 22:32:37] Manifest download: finished
[2024-02-29 22:32:37] Download skipped: /client/steam_client_ubuntu12 version 1709168962, installed version 1709168962, existing pending version 0
[2024-02-29 22:32:37] Nothing to do
[2024-02-29 22:32:37] Verifying installation...
[2024-02-29 22:32:37] Performing checksum verification of executable files
[2024-02-29 22:32:37] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/luis/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf4105370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf4103cc0
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
steamwebhelper.sh[148086]: === jue 29 feb 2024 22:32:38 CST ===
steamwebhelper.sh[148086]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/luis/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 148162
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
steamwebhelper.sh[148297]: === jue 29 feb 2024 22:32:49 CST ===
steamwebhelper.sh[148297]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/luis/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
steamwebhelper.sh[148481]: === jue 29 feb 2024 22:32:59 CST ===
steamwebhelper.sh[148481]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/luis/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
src/steamUI/steamuisharedjscontroller.cpp (546) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (546) : Failed creating offscreen shared JS context
02/29 22:33:00 Init: Installing breakpad exception handler for appid(steam)/version(1709168962)/tid(148069)
02/29 22:33:00 Failed writing minidump, nothing to upload.
steamwebhelper.sh[148648]: === jue 29 feb 2024 22:33:09 CST ===
steamwebhelper.sh[148648]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/luis/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
[2024-02-29 22:33:20] Shutdown
`

**Comment by smcv** [comment]
From the attached `steamwebhelper.log`, the container runtime framework is starting up successfully, but I can't tell much beyond that.

It looks like the steamwebhelper is maybe crashing, but is unable to send in a crash report because of this:

```
[0229/222836.646493:ERROR:filesystem_posix.cc(63)] mkdir /tmp/dumps/new: Permission denied (13)
[0229/222836.649457:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
```

If this is a shared computer, it would be helpful to ask the user who currently owns `/tmp/dumps` to delete or rename it (or you might be able to remove it by restarting the computer), and then try this again with that directory not present, so that Steam can send in a crash dump that Steam developers can analyze.

One common issue at the moment is that it can cause problems if `~/.config`, `~/.cache` or `~/.local/share` are symbolic links (known to be a problem for `~/.config`, speculated to be a problem for the others). This is #10547 and #10552. I can't tell with the information available whether the crash you are encountering is this or not.

**Comment by letorresl** [comment]
I just deleted `/tmp/dumps` and steam is launching without problems. The owner of this dir was steam user itself, which I made some months ago to run an ark server.

**Comment by smcv** [comment]
> I just deleted `/tmp/dumps` and steam is launching without problems. The owner of this dir was steam user itself, which I made some months ago to run an ark server.

Thanks, this is very useful information. It seems that this is a new problem with the updated steamwebhelper (not the container runtime that it's running in, this time, but actually the steamwebhelper itself). Previously, having a `/tmp/dumps` owned by another user would just break crash reporting, but it seems that it now prevents starting steamwebhelper at all.

**Comment by letorresl** [comment]
The only issue now is that everytime I start my pc, `/tmp/dumps` creating the previous error. Deleting each time the dir fixes the problem.

**Comment by DomnMihai** [comment]
# Problem
I run in the terminal `steam` and I got the error `src/steamUI/steamuisharedjscontroller.cpp (545) : Failed creating offscreen shared JS context`
I check the logs in **~/.steam/steam/logs/steamwebhelper.log** and I found the error `/usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory`

# Solution
- Find **libdl.so.2** location. Command `sudo find / -name libdl.so*`. My location was **/usr/lib/x86_64-linux-gnu/libdl.so.2**
- Run steam in the terminal with the command `LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ steam`

**Comment by smcv** [comment]
@DomnMihai:

> Run steam in the terminal with the command LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ steam

This should not be necessary. Please report a separate issue in https://github.com/ValveSoftware/steam-runtime/issues with the logs from `~/.steam/steam/logs` and details of your system.

We can never solve this sort of issue without more information, and replying to someone else's closed issue report is rarely the right thing to do.

**Comment by Quix0r** [comment]
For me it was the cause because I ran steam in a screen like: `screen -dmS steam steam`. Without the screen, Steam is now starting again but did it in earlier versions anyway?
