### ISSUE TITLE
[Flatpak] Big Picture mode doesn't display the boot animation and menu options become invisible

### ISSUE THREAD

**Issue by CiscoDeTours** [ValveSoftware/steam-for-linux#10568]
**INFO**
---

**- Steam Client**

Steam Beta Branch:  Stable Client
Steam Version:  1709168962
Steam Client Build Date:  Wed, Feb 28 8:39 PM UTC -08:00
Steam Web Build Date:  Mon, Feb 26 4:21 PM UTC -08:00
Steam API Version:  SteamClient021

**- Steam Logs**

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14470651/steam-logs.tar.gz)

**- System**

~~~
~$ neofetch
 
DEVICE 
•PC: OMEN by HP Laptop 16-c0xxx 
 
SOFTWARE 
•Distro: Debian GNU/Linux 12 (bookworm) 
•Desktop: GNOME 43.9 
•Kernel: 6.6.15-amd64 
•Packages: 2567 (dpkg), 69 (flatpak) 
•Shell: bash 5.2.15 
 
COMPONENTS 
•CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 4.680GHz 
•GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
•GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
•Memory: 3,92GiB / 14,98GiB (26%)
~~~

**QUESTIONNAIRE**
---

**1. What's your problem with Steam?**

https://github.com/ValveSoftware/steam-for-linux/assets/67841579/7a3651ec-6fb6-4004-a76c-fb2cbbe72d0c

**2. Opted into Steam client beta?**
No.

**3. Have you checked for system updates?**
Up to date on Debian 12 and Flatpak.

**4. Does this issue reproduce with native Steam?**
No.

**Comment by RobotRoss** [comment]
Also having this issue on my end. Fedora 39, GNOME, RX6900 XT and 5800X3D.
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14470959/steam-logs.tar.gz)

**Comment by Loweville** [comment]
I'm also having this issue, POP_OS 22.04 LTS, GNOME, RTX 3090 with 5800X
[steam-logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/14507919/steam-logs.zip)

**Comment by bnpfeife** [comment]
I'm also having this issue ArchLinux, 6900XT with a 3900X:
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14515997/steam-logs.tar.gz)

**Comment by poisonsnak** [comment]
Same issue. Software: Debian 12, Kernel 6.1.0-18-amd64 (6.1.76-1), KDE 5.27.5 (X11), Flatpak 1.14.4, stable Steam client.  Hardware:

- AMD 5800X and 6900XT.  On this system I also tested the beta Steam client, same result.
- AMD 4700U with integrated graphics.  On this system I also tested with KDE on Wayland instead of X11, same result.

I tried installing Steam via the Debian repo (https://packages.debian.org/bookworm/steam-installer) on the 4700U system and it doesn't have the issue. I get the startup animation and the menu works correctly.  The only difference I can see (besides Flatpak itself) is, the Flatpak version of Steam is using Flatpak's Mesa (24.0.2) where the Debian version is using Debian's Mesa (22.3.6).

Logs from the 4700U attached, both the Flatpak and Debian versions for comparison.
[steam-logs-debian.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14516909/steam-logs-debian.tar.gz)
[steam-logs-flatpak.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14516910/steam-logs-flatpak.tar.gz)

**Comment by CiscoDeTours** [comment]
@kisak-valve 

Labels need to be updated. This problem is also present in Fedora, Ubuntu, and Arch based Distros.

**Comment by VoidAndCaffeine** [comment]
I have been having this issue consistently for the last few months. As I was attempting to get logs of the issue, I had a launch where the guide menu properly opened.

looking thru the logs, when the issue occurred there where the issue did not occur there were two crashes. the first with exit code 512 and then they both crash with exit code 8704. 

these appear to be chromium hardware acceleration errors
ec 512 appears to be a vulkan related issue
ec 8704 i haven't been find what causes this other than a generic hardware acceleration error, someone on the arch-wiki suggests that this is related to unstable infinity fabric timings which i will examine next. Given that all of us here appear to have AMD cpus, unstable infinity fabric timings might be the culprit but we shall see. 

I tried launching with steam -cef-disable-gpu the problem still occurred but with no error codes other then what i presume are no gpu acceleration error during initialization.

[steam-logs-no-occurance.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14625682/steam-logs-no-occurance.tar.gz)
[steam-logs-runtime-problem-occured.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14625683/steam-logs-runtime-problem-occured.tar.gz)
[steam-logs-cef-dissable-gpu.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14625846/steam-logs-cef-dissable-gpu.tar.gz)

**Comment by b-wize** [comment]
Running into this on Fedora Silverblue 39 (ublue-OS)
CPU: 7800X3D
GPU: 7900XT
Kernel: 6.7.10-200.fc39.x86_64
Desktop: Gnome 45.5
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14824520/steam-logs.tar.gz)

**Comment by hgaiser** [comment]
I had very similar results on my system. I opted into the beta client and it seems to work well now. My take is that this is fixed, but maybe it's good if others verify that.

**Comment by b-wize** [comment]
> I had very similar results on my system. I opted into the beta client and it seems to work well now. My take is that this is fixed, but maybe it's good if others verify that.

Opting into the beta seems to have fixed for me as well. Hopefully this makes its way to stable soon

**Comment by poisonsnak** [comment]
The beta fixed it for me too. Thanks!

**Comment by CiscoDeTours** [comment]
@JustCryen 

~~~
tar -zcvf ~/steam-logs.tar.gz ~/.steam/steam/logs
~~~

Generate your Steam native logs and try to upload the compressed file located in your home folder for those who are tracking the issue.

**Comment by JustCryen** [comment]
Sure thing (that's quite a lot of logs) xP

Quick system info:
OS: Archlinux
CPU: Ryzen 5 3600
GPU: RX 6700XT
Kernel: 6.8.7-zen1-2-zen
Desktop: Gnome 46.1

I'm also including a video of the issue, I entered steam big picture right when the UI loaded so it might look like it crashed but it is loading, just without the animation and its sound. 

https://github.com/ValveSoftware/steam-for-linux/assets/41633661/afb2c789-fc39-4301-a90a-4f38981e3030



[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15274677/steam-logs.tar.gz)

**Comment by RisaI** [comment]
You may want to try [the workaround](https://github.com/ValveSoftware/steam-for-linux/issues/10879#issuecomment-2171168395) for another issue I've discovered. I  also had this issue before.

**Comment by CiscoDeTours** [comment]
Steam version 1721173382 solved this issue in the stable channel. To avoid a laggy boot and increase responsiveness while using the menus, hardware acceleration options must be enabled.
