### ISSUE TITLE
LD_PRELOAD no longer working from launch options.

### ISSUE THREAD

**Issue by gegoxaren** [ValveSoftware/steam-for-linux#10573]
#### Your system information

* Steam client version (build number or date):  
* Distribution (e.g. Ubuntu): Debian 12 / Flatpak
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14474554/steam-logs.tar.gz)

* GPU: AMD rx 750 8GB

#### Please describe your issue in as much detail as possible:

When running a game with `gamemoderun` and/or `obs-gamecapture` the `LD_PRELOAD` enviorment variable that is set in the launch scripts, propagate to the execution environment.

You can see the problem with just trying to run a game using `gamemoderun` in that no clients are listed when running `gamemodelist` on the system.

#### Steps for reproducing this issue:

1. set `gamemoderun %command%` as launch option
2. launch game
3. on the system run `gamemodelist`
4. Client is not shown

**Comment by kisak-valve** [comment]
Hello @gegoxaren, looking at your console_log.txt, all the recent games you were testing have the `%command%` token typoed as `%commad%`. This is then passed to the game as command line arguments as a result.

**Comment by gegoxaren** [comment]
Yup.

That should probably prevent launching... I never questioned it as the game started.
