### ISSUE TITLE
Multiple Users - Steamwebhelper crashes with `mkdir /tmp/dumps/new: Permission denied`

### ISSUE THREAD

**Issue by Jcd1230** [ValveSoftware/steam-for-linux#10574]
#### Your system information

* Steam client version (build number or date): 
Steam Beta Branch:  Stable Client
Steam Version:  1709168962
Steam Client Build Date:  Wed, Feb 28 7:39 PM UTC -08:00
Steam Web Build Date:  Mon, Feb 26 3:21 PM UTC -08:00
Steam API Version:  SteamClient021
* Distribution: Archlinux, official pacman `steam` package 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
Relevant lines of steam console output:
```
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
```

Relevant line of steamwebhelper.log
```
[0303/194154.084417:ERROR:filesystem_posix.cc(63)] mkdir /tmp/dumps/new: Permission denied (13)
```
(Let me know if more logs would be helpful)
* GPU: AMD R9 Fury + AMD Vega64

#### Please describe your issue in as much detail as possible:
Running steam simultaneously as multiple users used to work out of the box. Sometime recently, this temp file started to get created, and has permissions set which prevent other users from using the same file/location. 
Steamwebhelper seems to crash completely when this occurs.
A simple workaround has been found, see below.

#### Steps for reproducing this issue:

1. Launch steam as one user
2. Launch steam as a second user
3. Steamwebhelper fails to start and prevents steam from launching

# Workaround:

1. After the /tmp/dump folder gets created by one user, set liberal permissions on the folder, i.e. `chmod -R 777 /tmp/dumps`
2. Other users should be able to run Steam now without steamwebhelper crashing.

**Comment by kisak-valve** [comment]
Hello @Jcd1230, this issue is already being tracked at #10549. Closing as a duplicate.

**Comment by Jcd1230** [comment]
Thank you! Apologies I missed that, tried searching for a bit from the error message but that one eluded me.
