### ISSUE TITLE
Steamwebhelper ERROR:broker_posix.cc(43) Invalid node channel message

### ISSUE THREAD

**Issue by dareni** [ValveSoftware/steam-for-linux#10576]
#### Your system information

* Steam client version (build number or date): 1709168962
* Distribution (e.g. Ubuntu): debian 12.5
* Opted into Steam client beta?: [Yes/No] Tried opted in and out.
* Have you checked for system updates?: [Yes/No] Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
We have 3 debian version 12.5 machines. On March 1st they produced the "Steamwebhelper is not responding" error window when executing the steam client command. The window has the error: "steamwebhelper, a critical Steam component, is not responding. The Steam UI will not be usable.". The window also has radio button options to "Restart Steam", "Restart Steam with GPU Acceleration disabled", "Restart Steam with Browser Sandboxing disabled", "Restart steamwebhelper", "Exit Steam". None of the options help. Prior to March 1st  the steam command executed without this error.

I have recreated the log files just now.

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14476651/steam-logs.tar.gz)
[assert_20240304145149_31.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/14476655/assert_20240304145149_31.dmp.txt)
[strace_std.txt](https://github.com/ValveSoftware/steam-for-linux/files/14476656/strace_std.txt)
[strace_error.txt](https://github.com/ValveSoftware/steam-for-linux/files/14476657/strace_error.txt)

#### Steps for reproducing this issue:
$ steam

**Comment by dareni** [comment]
A work around to be able to play a game: Login with chrome. Press "Play Now" from steam store.

**Comment by dareni** [comment]
I was running with a .steam symlink so i bind mounted this with no change.

daren@sweetpea:~$ ls -la |egrep 'steam|config|local|cache'
drwx------  46 daren daren    4096 Mar  4 15:49 .cache
drwx------  48 daren daren    4096 Feb 28 17:07 .config
lrwxrwxrwx   1 daren daren      46 Aug 25  2022 .dircolors -> /home/daren/bin/shellscripts/config/.dircolors
drwxr-xr-x   2 daren daren    4096 Sep  9  2014 .fontconfig
drwxr-xr-x   2 daren daren    4096 Aug 13  2015 fontconfig
-rw-r--r--   1 daren daren     183 Mar 24  2015 .gitconfig
drwx------   4 daren daren    4096 Oct  5 19:03 .local
lrwxrwxrwx   1 daren daren      44 Aug 25  2022 .profile -> /home/daren/bin/shellscripts/config/.profile
drwxr-xr-x   3 daren daren    4096 Mar  4 15:49 .steam
lrwxrwxrwx   1 daren daren      30 Mar  4 15:48 .steampath -> /home/daren/.steam/sdk32/steam
lrwxrwxrwx   1 daren daren      28 Mar  4 15:48 .steampid -> /home/daren/.steam/steam.pid
lrwxrwxrwx   1 daren daren      42 Aug 25  2023 _vimrc -> /home/daren/bin/shellscripts/config/_vimrc
lrwxrwxrwx   1 daren daren      47 Aug 25  2022 .Xdefaults -> /home/daren/bin/shellscripts/config/.Xresources
lrwxrwxrwx   1 daren daren      44 Aug 25  2022 .xinitrc -> /home/daren/bin/shellscripts/config/.xinitrc
lrwxrwxrwx   1 daren daren      47 Aug 25  2022 .Xresources -> /home/daren/bin/shellscripts/config/.Xresources

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14477111/steam-logs.tar.gz)
[assert_20240304154906_27.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/14477112/assert_20240304154906_27.dmp.txt)
[strace_std.log](https://github.com/ValveSoftware/steam-for-linux/files/14477114/strace_std.log)
[strace_error.log](https://github.com/ValveSoftware/steam-for-linux/files/14477116/strace_error.log)

The error is still:
src/steamUI/steamuisharedjscontroller.cpp (546) : Failed creating offscreen shared JS context

**Comment by dareni** [comment]
steam --reset
steam -clearbeta

Seemed to have fixed it. I guess this is something to do with stale data from the old version.

**Comment by smcv** [comment]
I think

```
[0304/154936.559612:ERROR:broker_posix.cc(43)] Invalid node channel message
```

is maybe a distinctive error message not seen in other issue reports? This doesn't mean anything to me, but hopefully it will be a good clue for a steamwebhelper developer.

@kisak-valve, if my guess is correct, it might be worth mentioning "Invalid node channel message" in the issue title to differentiate this from other reports of steamwebhelper crashing.

As in some other recent issue reports, the error messages involving EGL initialization and ANGLE look scary and bad, but it seems they're actually harmless - I get those from a working steamwebhelper.

**Comment by dareni** [comment]
4 machines here still having this problem. 3 machines on debian 12. 1 machine on debian 11.
I installed a new debian 12 virtual machine with steam and it did not have this problem. I thought maybe my machine installation was corrupt so I mounted the virtual image steam installation on my main host and ran steam and still get the error. I compared the console output from the steam startup on the virtual machine and the steam output on the host and noticed the vm startup is slower as you would expect. So I played around with suspending the steam startup and found if I suspend the process at the point when the steamwebhelper starts and then resume after 1 minute steam completes the startup as it should. 
Here is the console output of a successful start:

``daren@sweetpea:~$ steam
steam.sh[7382]: Running Steam on debian 12 64-bit
steam.sh[7382]: STEAM_RUNTIME is enabled automatically
setup.sh[7451]: Steam runtime environment up-to-date!
steam.sh[7382]: Steam client's requirements are satisfied
tid(7517) burning pthread_key_t == 0 so we never use it
[2024-04-06 08:44:00] Startup - updater built Mar  6 2024 20:27:25
[2024-04-06 08:44:00] Startup - Steam Client launched with: '/opt/game/steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad'
minidumps folder is set to /tmp/dumps
04/06 08:44:00 Init: Installing breakpad exception handler for appid(steam)/version(1709846872)/tid(7517)
[2024-04-06 08:44:00] Loading cached metrics from disk (/opt/game/steam/debian-installation/package/steam_client_metrics.bin)
[2024-04-06 08:44:00] Using the following download hosts for Public, Realm steamglobal
[2024-04-06 08:44:00] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-04-06 08:44:00] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-04-06 08:44:00] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-04-06 08:44:00] Verifying installation...
[2024-04-06 08:44:00] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /opt/game/steam/debian-installation/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf42a5780
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf42a4050
steamwebhelper.sh[7533]: === Sat 06 Apr 2024 08:44:26 AEST ===
steamwebhelper.sh[7533]: Starting steamwebhelper under bootstrap sniper steam runtime at /opt/game/steam/debian-installation/ubuntu12_64/steam-runtime-sniper
CAppInfoCacheReadFromDiskThread took 23 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 7602
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
^Z
[1]+  Stopped                 steam
daren@sweetpea:~$ fg
steam
steamwebhelper.sh[7774]: === Sat 06 Apr 2024 08:45:42 AEST ===
steamwebhelper.sh[7774]: Starting steamwebhelper under bootstrap sniper steam runtime at /opt/game/steam/debian-installation/ubuntu12_64/steam-runtime-sniper
[2024-04-06 08:46:26] Background update loop checking for update. . .
[2024-04-06 08:46:26] Checking for available updates...
[2024-04-06 08:46:26] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=857831540
[2024-04-06 08:46:26] Manifest download: send request
[2024-04-06 08:46:27] Manifest download: waiting for download to finish
[2024-04-06 08:46:27] Manifest download: finished
[2024-04-06 08:46:27] Download skipped: /steam_client_ubuntu12?t=857831540 version 1709846872, installed version 1709846872, existing pending version 0
[2024-04-06 08:46:27] Nothing to do
BRefreshApplicationsInLibrary 1: 0ms
BuildCompleteAppOverviewChange: 189 apps
RegisterForAppOverview 1: 5ms
RegisterForAppOverview 2: 5ms
[2024-04-06 08:47:54] Shutdown
``
So this suggests some sort of timing issue?

**Comment by dareni** [comment]
This definitely seems to be some type of timing issue. I still have to suspend at the point when the steamwebhelper starts but resume it again after only 30 seconds.  If the steamwebhelper  starts again, i suspend again but only for 10 seconds before resuming and the client starts up ok. I had to change the timings after one of the last updates.

**Comment by dareni** [comment]
Finally had the chance to have a good look at this. Found xdg-desktop-portal-gtk was failing. Just had to adjust .xinitrc with: `systemctl --user set-environment DISPLAY=$DISPLAY`
