### ISSUE TITLE
Counter Strike 2 fullscreen windowed bug

### ISSUE THREAD

**Issue by prufaraSS** [ValveSoftware/steam-for-linux#10579]
Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
Memory: 15.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A36
System Version: 1.0

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): KDE Plasma 6
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia

The problem appears only when playing in fullscreen windowed mode. In game trying to slightly adjust camera up or left direction causes game to not register this movement at all. Trying to flick also seem wobbly. But it works fine on right or down. Seem like cursor attachment set to top left border of the screen, instead of screen's center.

#### Steps for reproducing this issue:

1. Set display mode to Fullscreen windowed
2. Start a match
3. Very slowly move mouse up or left

**Comment by kisak-valve** [comment]
Hello @prufaraSS, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3301. Closing as a duplicate.
