### ISSUE TITLE
Fanatec Shifter v. 1.5 (connected with USB adapter) detected as a gamepad

### ISSUE THREAD

**Issue by sampie** [ValveSoftware/steam-for-linux#10570]
#### Your system information

* Steam client version (build number or date): 
Steam Beta Branch:  Stable Client
Steam Version:  1705108172
Steam Client Build Date:  Sat, Jan 13 2:52 AM UTC -08:00
Steam Web Build Date:  Fri, Jan 12 7:02 PM UTC -08:00
Steam API Version:  SteamClient021

* Distribution (e.g. Ubuntu): 
Ubuntu 23.10

* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes
* GPU: Nvidia/Intel/AMD
AMD
#### Please describe your issue in as much detail as possible:
Fanatec shifter is detected by steam client. However, when trying to configure the shifter, steam gives a gamepad layout.
On Linux, the shifter is not detected by games including dirt rally 2, EA WRC. jstest shows the shifter.

Please, write instructions how to make fanatec shifter to work with games in steam.

#### Steps for reproducing this issue:

1.  Connect fanatec shifter with USB
(2.  Open steam client and try to configure the shifter)
3. Try to play racing games with the shifter

**Comment by kisak-valve** [comment]
Hello @sampie, we're tracking issues with games run with Proton in the Proton issue tracker. Your previous issue report at https://github.com/ValveSoftware/Proton/issues/7427 seems to cover the topic.

Closing as a duplicate.
