### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by ClaudeLib** [ValveSoftware/steam-for-linux#10572]
#### Your system information
* Steam client version (build number or date): 1709168962
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14474273/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
When I download a game from Steam on Linux, the download speed is painfully slow. It's not consistently slow, it can be 2 MB/s, or 10, or 20 if I'm lucky. Changing the server barely helps. Trying to download the same game on Windows (on the same machine, virtualized) results in Steam consistently hitting my ISP's bandwidth limit, around 80 MB/s. The ISP is Ufanet, if that helps. All the network settings are as they come by default, untouched. The issue has been bothering me ever since I switched to Linux, persists through multiple reinstalls, different distros and also happens on my Deck running vanilla SteamOS.
![Screenshot_20240304_002417](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/cb4edd4b-5c66-486a-9895-a3f0c55a9949)

#### Steps for reproducing this issue:
1. Start downloading a game.

**Comment by ClaudeLib** [comment]
Reproduced the same issue on LMDE 6 (based on Debian 12)

#### Your system information

* Steam client version (build number or date): 1709168962
* Distribution (e.g. Ubuntu): Linux Mint Debian Edition
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14484016/steam-logs.tar.gz)
* GPU: AMD

![Screenshot from 2024-03-04 20-59-44](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/a7cb9064-07cd-4da2-8fce-44bb5f25cb7f)

**Comment by spiffeeroo** [comment]
This issue may be related to https://github.com/ValveSoftware/steam-for-linux/issues/10248. Do speeds improve if you apply the tweaks suggested there?

**Comment by ClaudeLib** [comment]
Welp, I now feel stupid that I have found that sooner. It does seem to improve the downloading speed significantly. Still not as fast as on Windows, but much faster nonetheless.
![Screenshot from 2024-03-06 06-55-28](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/e387f1ad-1b9b-491e-8b89-bc34cd174104)
![Screenshot from 2024-03-06 07-00-28](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/845052ae-3cf9-4117-a91c-dd96e0b0bb45)
![Screenshot from 2024-03-06 07-07-39](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/534661c9-0755-4d6e-8852-cb932620cb45)

**Comment by scramble45** [comment]
You should keep this open because, just setting those in `steam_dev` is not a solution. I'm on a 8gig symmetrical fiber connection on Arch Linux have those settings its a little faster but I should be able to max out my line like I can with Heroic Game Launcher downloading from Epic game store lol. Steam needs to fix the root problem.

**Comment by ClaudeLib** [comment]
Yeah, there's one thing I forgot to mention, whenever there's an update for the Steam Client, it also downloads painfully slow, and this HTTP2 toggle doesn't affect it either.

**Comment by kisak-valve** [comment]
Hello @ClaudeLib, it would be better to continue discussing this on the older issue report. Closing in favor of #10248.
