### ISSUE TITLE
Dual boots

### ISSUE THREAD

**Issue by heiowge** [ValveSoftware/steam-for-linux#1058]
I use Linux for most things, but sometimes I have to boot to windows.  Whenever I boot into windows after having steam on (or load steam for linux after loading windows), I have to face the fact that it assumes I'm on a new computer.

Please can you find a way to add support for those of us who dual-boot?

**Comment by kisak-valve** [comment]
Hello @heiowge, are you still experiencing your issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
