### ISSUE TITLE
Error Code -105 on all instances of integrated browser, on mutiple systems on different networks.

### ISSUE THREAD

**Issue by superbeelavaman** [ValveSoftware/steam-for-linux#10582]
#### Your system information

* Steam client version (build number or date):
Steam Beta Branch:  Stable Client
Steam Version:  1709168962
Steam Client Build Date:  Wed, Feb 28 4:39 PM UTC -08:00
Steam Web Build Date:  Mon, Feb 26 12:21 PM UTC -08:00
Steam API Version:  SteamClient021
* Distribution: Arch Linux (Recently updated both systems I've tested on) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14486746/steam-logs.tar.gz)
* GPU: tested with Nvidia+AMD dual gpu and Intel integrated

#### Please describe your issue in as much detail as possible:
The integrated web browser is displaying Error Code -105 when trying to display any page. Additionally, some images aren't able to display. Logging in and downloading games still works, and I can still access the website from other web browsers.

#### Steps for reproducing this issue:

1. Open steam
2. Click on the Store tab
3. See error

**Comment by kisak-valve** [comment]
Hello @superbeelavaman, this looks similar to #10550. Can you check if your network configuration is similar to that user?

**Comment by superbeelavaman** [comment]
Thanks for your help, my network configuration was similar to the other user. Switching to dhcpcd did help, but now I'm getting a different, likely unrelated issue - The browser is displaying a black screen.
