### ISSUE TITLE
Steam networking failure on Warhammer 40k: Darktide and Six days in Fallujah

### ISSUE THREAD

**Issue by soypat** [ValveSoftware/steam-for-linux#10598]
#### Your system information

Steam Beta Branch:  Stable Client
Steam Version:  1709846872
Steam Client Build Date:  Wed, Mar 6 5:28 PM UTC -03:00
Steam Web Build Date:  Thu, Mar 7 6:17 PM UTC -03:00
Steam API Version:  SteamClient021

```
$ neofetch
             ...-:::::-...                 pato@qtpi 
          .-MMMMMMMMMMMMMMM-.              --------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: B660M DS3H DDR4 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 5.15.0-100-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 4 hours, 13 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 3188 (dpkg), 23 (flatpak), 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: bash 5.1.16 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 1920x1080, 1920x1080 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Xfce 4.16 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Xfwm4 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Mint-Y-Dark-Purple [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: xfce4-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       Terminal Font: Monospace 17 
       '.-MMMM``--:::::--``MMMM-.'         CPU: 12th Gen Intel i5-12400F (12) @ 
            '-MMMMMMMMMMMMM-'              GPU: AMD ATI Radeon RX 6800/6800 XT  
               ``-:::::-``                 Memory: 13502MiB / 31933MiB 
```
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14547733/steam-logs.tar.gz)

Just ran 
```sh
sudo apt update -y && sudo apt upgrade -y
```
and still happening.

#### Please describe your issue in as much detail as possible:
Games that previously worked (Six days fallujah) now throwing a cloud error (I assume it is related to steam) on startup screen. I am not able to play online or invite friends to my game. See images.

Warhammer 40k: Darktide also throws a network error on startup and fails to run entirely.

I've tried several other games such as Counter Strike 2, Lethal Company, Broforce, Sid Meier's Civ VI, Ready Or Not, among others in online play and they seem to work OK, no errors. This is the behaviour I was expecting.

#### Warhammer 40,000: Darktide
After first startup cutscene (only option is to close it):
![image](https://github.com/ValveSoftware/steam-for-linux/assets/26156425/4537f57f-756c-4890-a0a4-2697be893539)

#### Six Days in Fallujah 
On loading game:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/26156425/6cb52e68-c23f-4e87-99ff-209291c603d7)
On clicking "Fireteams" or "Wargames":
![image](https://github.com/ValveSoftware/steam-for-linux/assets/26156425/b7d49e92-43d6-4f16-82a1-a145ba12740d)
On trying to invite friends:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/26156425/f2246364-e599-4bb9-bcc7-835dbd0ae3f2)

#### Steps for reproducing this issue:

1. Run Warhammer Dark Tide. Skip or dont skip cutscenes. Also run 6 days and observe message on load.

**Comment by kisak-valve** [comment]
Hello @soypat, we're tracking issues with games run with Proton in the Proton issue tracker, also, this needs to be evaluated on a per-game basis. Since you've also mentioned this on the compatibility report for Warhammer 40,000: Darktide, I've gone ahead and transferred this issue report to the corresponding comment.

Closing in favor of the Proton compatibility report.

**Comment by soypat** [comment]
Thanks, added 6days too: https://github.com/ValveSoftware/Proton/issues/7570
