### ISSUE TITLE
Overlapping text in Settings

### ISSUE THREAD

**Issue by RussianNeuroMancer** [ValveSoftware/steam-for-linux#106]
At the bottom of the "Downloads + Cloud" tab, in French, there is too much text to fit the window.
Here is a screenshot: 
![steam_overlap2](https://f.cloud.github.com/assets/2613247/24396/264fd154-4aa4-11e2-8fcf-bcb99af74312.png)

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed for French and German.
