### ISSUE TITLE
Steam randomly unable to open anymore, "Please, reactivate your key! License check has failed. Exiting."

### ISSUE THREAD

**Issue by GYKgamer** [ValveSoftware/steam-for-linux#10607]
#### Your system information

* Steam client version (build number or date):  Unknown, going to guess latest
* Distribution (e.g. Ubuntu): Raspbian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14552016/steam-logs.tar.gz)
* GPU: Videocore vii

I ran "steam" and steam loaded normally, I was testing to see if I could get Cry of Fear working on the Raspberry Pi 5 and I left it idle for about 20 - 30 minutes, when I came back steam was closed, trying to reopen steam led to these errors:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/41442793/60d43411-efe7-4bbc-b8c3-347c37c0ccc1)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/41442793/753ec712-4d20-4cfa-9962-137b86128cd1)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/41442793/9663577b-9f47-411f-bc3e-db900c8cd1fb)
And even steamcmd was affected
![image](https://github.com/ValveSoftware/steam-for-linux/assets/41442793/aa0f89db-5195-4545-b9ff-e85966661ef2)
FYI I am using https://github.com/Botspot/Pi-apps to get steam.

#### Steps for reproducing this issue:

1. Open up terminal
2. Type Steam
3. Error message

**Comment by kisak-valve** [comment]
Hello @GYKgamer, sorry, but running Steam for Linux on ARM based hardware is not supported at this time. (#4061)
