### ISSUE TITLE
Steam UI will not refresh after restoring from system tray until window resize

### ISSUE THREAD

**Issue by dafzor** [ValveSoftware/steam-for-linux#10600]
#### Your system information

* Steam client version (build number or date):  Thu, Mar 7 17:29 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: (Will provide on request)
* GPU: AMD
* Desktop: KDE Plasma 6.0.1, X11

#### Please describe your issue in as much detail as possible:

When restoring steam window from the system tray the UI will be refresh and show a frozen view of how the UI was when last closed with the close window button will display as if it's highlighted.

Even though there's UI refresh is frozen, clicking still interacts with it normally and it's possible to change and launch games by clicking blindly as there's no visual feedback.

 Example: If game A was selected, clicking game B on the list and then the game A play button will launch game B as that's what is actually selected.

Resizing the window will unfreeze the UI and show the actual state.

The current release version of steam (1709846872) does not have this issue.

#### Steps for reproducing this issue:

1. Open steam beta
3. Close window
4. Re-open window from system tray

**Comment by SpiritWinD86** [comment]
Same issue happening again. https://github.com/ValveSoftware/steam-for-linux/issues/10459#issuecomment-1986917246

**Comment by BetaVersionBY** [comment]
> Yes, I have this problem again too: Library window freezes after restoring Steam from system tray. And just as with #10459, disabling GPU rendering for web pages is a workaround for this issue.

Fixed again in the latest beta update.

**Comment by hyunlee1o** [comment]
I've had an issue similar to this for a long time.
```
Steam Beta Branch:  Stable Client
Steam Version:  1738026274
Steam Client Build Date:  Tue, Jan 28 01:50 UTC -08:00
Steam Web Build Date:  Tue, Jan 28 01:44 UTC -08:00
Steam API Version:  SteamClient021
Distribution (e.g. Ubuntu): Debian trixie
Kernel: Linux 6.12.10-amd64
Opted into Steam client beta?: No
Have you checked for system updates?: Yes
GPU: AMD
Desktop Environment: i3wm 4.24
```
The window freezes unless i full screen the window and undo it to normal maximized window. (i3wm doesn't minimize because it's a tiling window manager)
Most of the time it happens when steam is un a non active workspace and i change to the steam workspace.

**Comment by Vermoot** [comment]
Exact same thing as above happens to me, on ArchLinux, AwesomeWM, whether I'm using a compositor (picom) or not.
