### ISSUE TITLE
Integrate wine-discord-ipc-bridge

### ISSUE THREAD

**Issue by IogaMaster** [ValveSoftware/steam-for-linux#10605]
https://github.com/0e4ef622/wine-discord-ipc-bridge

**Comment by kisak-valve** [comment]
Hello @IogaMaster, this is an invalid request for the Steam client. For Proton, that request is being tracked at https://github.com/ValveSoftware/Proton/issues/1473.

**Comment by IogaMaster** [comment]
Oops sorry about that.
Thanks for redirecting me
