### ISSUE TITLE
Un-minimizing the Client from Previously Maximuzed State Causes Revert to Windowed Mode

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#10610]
#### Your system information

* Steam client version (build number or date): 1709846872 (Wed, Mar 6 2:28 PM UTC -08:00)
* Distribution: Gentoo Linux (LLVM & OpenRC)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14566216/steam-logs.tar.gz)
* GPU: AMD (XFX Merc319 RX 7800XT)
* Desktop Environment: KDE Plasma 5 (and 6, happens with both)
* Window Manager: Kwin
* Session Type: Wayland

#### Please describe your issue in as much detail as possible:

Minimizing the Steam client window, from the maximized state, reverts the client back to windowed mode after re-opening the client. Might be **related** to https://github.com/ValveSoftware/steam-for-linux/issues/10292 but the issues are distinctly different in effect.

#### Steps for reproducing this issue:

1. Open Steam
2. Maximize the window
3. Minimize the window
4. Un-minimize the window

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue is already being tracked at #10479. Closing as a duplicate.
