### ISSUE TITLE
Windows server 2019 and 2022 Steam CMD always reports Fully installed.

### ISSUE THREAD

**Issue by LeonStraathof** [ValveSoftware/steam-for-linux#10612]
Like the person who mentioned recent in a old issue. I can confirm that this problem has been happening on Windows platform for years. I do not know where to report it please forward move this to the team that does the Windows build for SteamCMD. I kept a old copy of my game server in a folder.
Command line i use:
C:\SteamCMD\steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +force_install_dir C:\SERVERS\ArkAscended\server_old\ +login anonymous +app_info_update 1 +app_status 2430930 +quit

Expected behaviour:

In the output, under install state the state should be Fully Installed,Update Required,

Actual behaviour:

In the output, under install state the state is always Fully Installed, despite the presence of an update

The story below is from another user that posted this in a old issue so i am not the only one.

    Steam client version (build number or date): SteamCMD, version 1705108307
    Distribution (e.g. Ubuntu): Windows 11
    Opted into Steam client beta?: [Yes/No] No
    Have you checked for system updates?: [Yes/No] Yes

Please describe your issue in as much detail as possible:

This issue is still present as of the 2023 version of SteamCMD. I am using force_install_dir prior to logging in. app_status is still only displaying "Fully Installed," when there is an app update available. I've checked build IDs separately (I'm using Palworld 2394010 for example), and the latest build ID reported by app_info_print does not match the local build ID.

    Install App ID 740 (CSGO Server in this case for testing) via SteamCMD into a directory called 740.
    Wait for a new update to be released.
    Check for updates using the following command:

+force_install_dir 740 +login anonymous  740 +app_info_update 1 +app_status 740 +quit`

Expected behaviour:

In the output, under install state the state should be Fully Installed,Update Required,

Actual behaviour:

In the output, under install state the state is always Fully Installed, despite the presence of an update, and the fact that you can install an update via app_update 740

I believe this issue should be reopened and re-investigated, as it has been 3 years.

_Originally posted by @cameronSchneider in https://github.com/ValveSoftware/steam-for-linux/issues/8075#issuecomment-1921962272_

**Comment by kisak-valve** [comment]
Hello @LeonStraathof, you've come across an issue tracker for the Steam client for Linux. The SteamCMD for Windows utility is out of scope for this issue tracker. You may have luck reporting this issue to [Steam Support](https://help.steampowered.com).
