### ISSUE TITLE
Navegador da Steam acessivel a qualquer momento

### ISSUE THREAD

**Issue by AgoraSim21** [ValveSoftware/steam-for-linux#10627]
Ola, queria deixar sugestao: tornar o navegador da Steam acessivel a qualquer momento, em alguma aba principal, ou icone etc, mesmo sem nenhum jogo aberto., apenas com o cliente steam aberto.
Funcionando como o Google chrome, com opcoes de configuracao, a possibilidade de enviar estatisticas de uso se o usuario quiser, logar na conta google, ver email  etc

👍😄

**Comment by kisak-valve** [comment]
Hello, @AgoraSim21, from the store tab, Control + Left click any URL, and that should open the link in a separate browser window for you to use as you want.

**Comment by AgoraSim21** [comment]
Ok, obrigado Kisak
