### ISSUE TITLE
Opening a game crates an extra step to go back with the back button

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10623]
#### Your system information

* Steam client version (build number or date): 1710281934
* Distribution: SteamOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/OettocRRMUM
Every time I open a game, it creates a new page history entry. In the video I show how repeatedly opening a game allows me to press back multiple times before I get back into the main menu.
I have previously reported this in the steam forums https://steamcommunity.com/app/1675200/discussions/1/4038102936183425207/

#### Steps for reproducing this issue:

1. Open a game
2. Close a game
3. Repeat
4. Attempt to go back to the main menu

#### Observed results
The view stays the same as if there's multiple entries in the page history for the game page

#### Expected results
No extra history entries should be made when opening a game

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #10253. Closing as a duplicate.
