### ISSUE TITLE
Steam Input UI bug: Joystick mode shift deadzone not saved

### ISSUE THREAD

**Issue by qwelias** [ValveSoftware/steam-for-linux#10620]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-2
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14617374/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Mode shift joystick deadzone is not saved, see [video](https://youtu.be/Wkph5dMsv-M)

#### Steps for reproducing this issue:
1. go to controller layout
2. edit controller layout
3. joysticks
4. add joystick mode shift
5. configure joystick mode shift
6. change deadzone

**Comment by qwelias** [comment]
Got it working on beta branch

**Comment by kisak-valve** [comment]
Closing as fixed in the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.
