### ISSUE TITLE
Unable to create a template layout if the controller config has already been saved

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10635]
#### Your system information

* Steam client version (build number or date): ![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/b5aaf174-7ef2-4024-8aed-f907710f98b6)
* Distribution: Arch Linux and SteamOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14645518/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/FrHJRBH4sEE
If a config has been saved, selecting Export Layout -> Save New Layout does nothing. This in turn doesn't allow you to create a template layout out of the one you're editing currently

#### Steps for reproducing this issue:

1. Save your config for a game or desktop
2. Attempt to go to the same menu again to create a template out of the config

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #10565. Closing as a duplicate.
