### ISSUE TITLE
steamwebhelper Gdk: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by Ciel-MC** [ValveSoftware/steam-for-linux#10637]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-2 on pacman
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14651217/steam-logs.tar.gz)
* GPU: AMD (7900xtx)

#### Please describe your issue in as much detail as possible:
When I try to start up steam, I get shown the user select screen for a brief second before it closes, and it reopens after a few seconds, indefinitely. If I launched steam from the terminal, ctrl-c does not kill the application.

I saw issues talking about a similar looking problem if .config is a symlink, but it's not. I've also nuked both my `.var/app/com.valvesoftware.Steam` and `.local/share/Steam` and reinstalled steam and tried both flatpak and pacman versions, but they all do the same thing. It downloads some stuff and crashed when it shows the login screen

I suspect that it is something to do with my computer recently(maybe after an update), some electron apps started needing me to manually specify `--ozone-platform-hint=auto` to not crash. In addition, I had also recently got my entire drive filled up by firefox spamming `.local/share/sddm/wayland-session.log`(though I have no idea what it could've corrupted to cause this since I already nuked the steam install to my knowledge), so it could be a combination of any of these

#### Steps for reproducing this issue:

1. Start steam

**Comment by kisak-valve** [comment]
Hello @Ciel-MC `[0319/213042.131876:ERROR:browser_main_loop.cc(271)] Gdk: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed` in steamwebhelper.log and cef_log.txt looks like a key detail to ponder.

**Comment by Ciel-MC** [comment]
> Hello @Ciel-MC `[0319/213042.131876:ERROR:browser_main_loop.cc(271)] Gdk: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed` in steamwebhelper.log and cef_log.txt looks like a key detail to ponder.

Definitely, I have also had this error on other electron apps (Discord and 1Password), but it doesn’t seem like I can specify —ozone-platform-hint=auto for steam, and itd be really weird that I need to start specifying everything all of a sudden for no reason

**Comment by Ciel-MC** [comment]
Okay y'all I just solved it, it's because `GDK_IM_MODULE` is set to `wayland` instead of being unset, which fucked up all electron apps, among which some part of steam is I suppose. It's dumb but it's solved.

**Comment by NiciTheNici** [comment]
my fucking god thank you

this stupid fucking thing just stole an hour of my life, I had just set GDK_IM_MODULE to wayland because fcitx told me to do so and I didnt realize that that was at fault.

It fixed both steam and prusa for me.

thank you

**Comment by Nahuy99** [comment]
i wish u could give u a kiss on the nose right now this fixed my problem too, changing the IM_MODULE from wayland to nothing fixed it in case someone just as dumb as me has to do this in hyprland, i just added this and the crashes stopped

env = GTK_IM_MODULE,
