### ISSUE TITLE
Steam Input not working on Wayland

### ISSUE THREAD

**Issue by spuxx1701** [ValveSoftware/steam-for-linux#10632]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Intel

#### Please describe your issue in as much detail as possible:

**Current behavior**: When connecting an XInput controller (an 8bitDo Ultimate Pro in my case) to your machine and running steam with Steam Input and a Desktop layout for said controller enabled, the controller input, particularly mouse emulation, will not work when using Wayland. It will work as expected when using X11.

**Expected behavior**: Steam Input and its desktop mode should work when using Wayland.

I am aware that this issue has been raised in various ways in multiple places, e.g.

* #4738
* #8205
* #6615

> **Note**: The behavior is not exclusive to Steam Controller.

However, @kisak-valve has been repeatedly closing these issues, pointing at https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/431, a merge request over at Wayland. If you read into that merge request, you will quickly notice that it is very unlikely to ever be merged. I quote:

> I don't think any particular client or use-case is important enough to justify peeling back the core design promises of Wayland. This use-case is one which, from the start, was going to be fraught with uncertainty. There are many other X11 programs which do not work correctly on Wayland for similar reasons - lock screens, screensavers, panels and bars, conky, dmenu, and so on. Feeding input into uinput, or using protocols like virtual input and virtual pointer, is the stated solution for this problem. [...]

This is not not something that will or should be solved in Wayland. Instead, Valve should migrate key functionalities of their client to support Wayland, which is steadily becoming the new standard and replacing X11. As far as I understand, this issue also blocks e.g. Steam Deck to utilize Wayland in desktop mode (although it is likely not the only blocker) since it would render the Steam Deck's controls unusable in desktop mode. Please do not simply close this issue. It remains a problem and it will *not* be fixed by Wayland. For many users, Wayland has become the preferrable choice over X11 due to that one's problems with e.g. screen tearing. Many of us rely on companies like Valve to improve their support of Wayland.

#### Steps for reproducing this issue:

1. Install any distribution that supports both X11 and Wayland.
2. Install steam and set up an XInput controller with Steam Input. Confirm that Steam Input works in desktop mode.
3. Switch to Wayland. Steam Input will no longer work in desktop mode.

I will try to maintain a list of related links and places this issue has also been documented. As of know, documentation is really fragmented and I'm hoping that others running into the same problem will find this issue and gain a better understanding of it.

* [Steam Controller mouse emulation in Wayland (ArchLinux forums)](https://bbs.archlinux.org/viewtopic.php?id=228032)
* [Cursor missing on Wayland Linux desktop (Steam Community)](https://steamcommunity.com/app/353370/discussions/1/3279193518776920323/)
* [Similar issue at gamescope](https://github.com/ValveSoftware/gamescope/issues/33) - however, this is likely no more a gamescope issue than it is a wayland issue
* [Steam Controller mouse emulation doesn't work under wayland (Red Hat)](https://bugzilla.redhat.com/show_bug.cgi?id=1765918)

**Comment by spuxx1701** [comment]
Ah, #8604 has slipped past my attention. I would have preferred an issue with more information ane one that's less specific, but alright.

**Comment by Sylk** [comment]
Man what a dream, this would be terribly nice...
