### ISSUE TITLE
line 85: steam-runtime-identify-library-abi: command not found

### ISSUE THREAD

**Issue by tojestzart** [ValveSoftware/steam-for-linux#10634]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14638394/steam-logs.tar.gz)
#### Your system information

* Steam client version (build number or date): 1:1.0.0.79
* Distribution (e.g. Ubuntu):  Kubuntu 23.10 (freshly reinstalled due to resizing partition)
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD Optimus AMDGPU + rtx3050m

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) expected login screen with qr code, actually doesnt open https://gist.github.com/tojestzart/026dfee2d73fd420782deedb692298b6

#### Steps for reproducing this issue:

1. from terminal running steam opened login window (once), then never
2. from KDE gui did nothing
3.

**Comment by smcv** [comment]
> line 85: steam-runtime-identify-library-abi: command not found

This is not the most relevant error message in your log. Steam successfully downloaded a newer version of itself that resolved this (you will see that after "Restarting Steam by request", this warning no longer appears).

**Comment by smcv** [comment]
This message in `steamwebhelper.log` might be relevant:

```
[0318/150624.272848:WARNING:connection.cc(41)] X error received.  Request: DestroyWindowRequest, Error: WindowError{.sequence = 391, .bad_value = 69206023, .minor_opcode = 0, .major_opcode = 4}
```

If you try starting Steam again, it might upload a crash report (you will see `CrashID=something` in its output). If it does, that CrashID could provide useful information to a Valve developer.

**Comment by tojestzart** [comment]
![runs_from_console](https://github.com/ValveSoftware/steam-for-linux/assets/37272009/535ff7cd-7d3c-4c6f-b12c-23997290a065)
1. runs from console 
2. manual start from "menu start" does nothing 
![does nothing](https://github.com/ValveSoftware/steam-for-linux/assets/37272009/d30d3131-2d31-4033-b7f0-15eb63096720)
3 rd shot from console 
![3rd shot vodka](https://github.com/ValveSoftware/steam-for-linux/assets/37272009/39705193-53d7-4167-a5bd-768029d9240e)

**Comment by tojestzart** [comment]
`lsd@Crawler-E25:~$ DEBUGGER=gdb steam
steam.sh[6200]: Running Steam on ubuntu 23.10 64-bit
steam.sh[6200]: STEAM_RUNTIME is enabled automatically
setup.sh[6314]: Steam runtime environment up-to-date!
steam.sh[6200]: Steam client's requirements are satisfied
gdb/cgdb launch with ARGSFILE: lsd.steam.gdb.Xnzf
gdb -x lsd.steam.gdb.Xnzf --args /home/lsd/.local/share/Steam/ubuntu12_32/steam
GNU gdb (Ubuntu 14.0.50.20230907-0ubuntu1) 14.0.50.20230907-git
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/lsd/.local/share/Steam/ubuntu12_32/steam...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /home/lsd/.local/share/Steam/ubuntu12_32/steam
(No debugging symbols found in /home/lsd/.local/share/Steam/ubuntu12_32/steam)                                                                                                              
LD_LIBRARY_PATH = /home/lsd/.local/share/Steam/ubuntu12_32:/home/lsd/.local/share/Steam/ubuntu12_32/panorama:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/lib:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/lsd/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib
  Cache hits (this session): 0
Cache misses (this session): 0
(gdb) run
Starting program: /home/lsd/.local/share/Steam/ubuntu12_32/steam 
Downloading separate debug info for /lib/ld-linux.so.2
Downloading separate debug info for system-supplied DSO at 0xf7fc7000                                                                                                                       
Downloading separate debug info for /lib/i386-linux-gnu/libdl.so.2                                                                                                                          
Downloading separate debug info for /lib/i386-linux-gnu/librt.so.1                                                                                                                          
Downloading separate debug info for /lib/i386-linux-gnu/libX11.so.6                                                                                                                         
Downloading separate debug info for /lib/i386-linux-gnu/libm.so.6                                                                                                                           
Downloading separate debug info for /lib/i386-linux-gnu/libpthread.so.0                                                                                                                     
Downloading separate debug info for /lib/i386-linux-gnu/libc.so.6                                                                                                                           
[Thread debugging using libthread_db enabled]                                                                                                                                               
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Downloading separate debug info for /lib/i386-linux-gnu/libxcb.so.1
Downloading separate debug info for /lib/i386-linux-gnu/libXau.so.6                                                                                                                         
Downloading separate debug info for /lib/i386-linux-gnu/libXdmcp.so.6                                                                                                                       
Downloading separate debug info for /lib/i386-linux-gnu/libbsd.so.0                                                                                                                         
Downloading separate debug info for /lib/i386-linux-gnu/libmd.so.0                                                                                                                          
tid(6405) burning pthread_key_t == 0 so we never use it                                                                                                                                     
[Inferior 1 (process 6405) exited normally]
(gdb) 
`

**Comment by TTimo** [comment]
```
- runs from console
- manual start from "menu start" does nothing
```

Seems to be the relevant thing here. Nothing much that we can investigate here, there are no error messages particularly indicative of a problem in those logs. Check for crash minidumps written to `/tmp/dumps` maybe, and also switch to the beta version of the Steam client.

**Comment by tojestzart** [comment]
`kubuntu@kubuntu:~$ steam
steam.sh[17916]: Running Steam on ubuntu 23.10 64-bit
steam.sh[17916]: STEAM_RUNTIME is enabled automatically
setup.sh[18030]: Steam runtime environment up-to-date!
/home/kubuntu/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[18042]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[17916]: Can't find 'steam-runtime-check-requirements', continuing anyway
tid(18080) burning pthread_key_t == 0 so we never use it
kubuntu@kubuntu:~$ 



`
tried liveiso, to make sure steam is a problem, and especially used gui method, similar errors, i will have a look to run steam  from shell after system startup (it always works after system startup)  so i will try to join beta, maybe it gives some more output

**Comment by tojestzart** [comment]
tested liveiso Linux Mint 21.3 "Virginia" cinnamon  and it works,
on main system switched to beta still, not working, something related to KDE?
https://gist.github.com/tojestzart/f093fc6c52c196a2a5572b4d3f7c7964
i give up on this

**Comment by tojestzart** [comment]
https://bugs.kde.org/show_bug.cgi?id=484672
seems to be resolved somehow, closing.
