### ISSUE TITLE
Steam downloads game content/cache everytime I restart/reboot the PC

### ISSUE THREAD

**Issue by axl303** [ValveSoftware/steam-for-linux#10631]
#### Your system information

* Steam client version (build number or date):
Steam Beta Branch:  Stable Client
Steam Version:  1709846872
Steam Client Build Date:  Wed, Mar 6 10:28 PM UTC -08:00
Steam Web Build Date:  Thu, Mar 7 11:17 PM UTC -08:00
Steam API Version:  SteamClient021
* Distribution (e.g. Ubuntu):  Debian 12
* Opted into Steam client beta?: [Yes/No] - No
* Have you checked for system updates?: [Yes/No] - Yes (latest system and steam updates)
* GPU: Nvidia/Intel/AMD - Nvidia gtx 970

#### Please describe your issue in as much detail as possible:

Everytime I restart/reboot the PC, the steam downloads Shader pre-caching update (Counter-Strike 2), wasting only GBs of bandwidth everytime and not only. Using Debian 12, previously on Ubuntu 18.04LTS was no issues. Is there any solution of this?

**Comment by kisak-valve** [comment]
Hello @axl303, this issue is already being tracked at #10285. Closing as a duplicate.
