### ISSUE TITLE
It takes almost 30 seconds just for the login window to appear

### ISSUE THREAD

**Issue by guihkx** [ValveSoftware/steam-for-linux#10636]
#### Your system information

* **Steam client version**: 1709846872
* **Distribution**: Arch Linux (Flatpak package)
* **Opted into Steam client beta?**: No
* **Have you checked for system updates?**: Yes
* **Steam Logs**: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14647049/steam-logs.tar.gz)
* **GPU**: NVIDIA GTX 660, driver version 470.239.06

#### Please describe your issue in as much detail as possible:

In recent times, Steam has been taking way to long to open on a fairly fast computer with SSD.

#### Steps for reproducing this issue:

This was reproduced on a clean installation of Steam (Flatpak), so:

1. Temporarily rename the Steam (Flatpak) folder: `mv ~/.var/app/com.valvesoftware.Steam{,.bak}`
2. Launch Steam for the firs time and wait for the entire installation
3. Once the login window opens, close it
4. Relaunch Steam with: `STEAM_LINUX_RUNTIME_VERBOSE=1 flatpak run com.valvesoftware.Steam`

After that, it takes around 30 seconds for the login window to appear again.

This was reproduced on a i5 3570k @ 3.4 GHz + 120 GB Sandisk SSD. Video:

https://github.com/ValveSoftware/steam-for-linux/assets/626206/d6dd9778-c3f7-4866-83f8-2f43eafc32dc

I have Windows 10 on dual boot, and over there it does not take Steam that long to start.

Steam used to launch much faster on Linux, too, so I assume this is a recent problem.

**Comment by kisak-valve** [comment]
Hello @guihkx, this issue is already being tracked at #10595. Per https://github.com/ValveSoftware/steam-for-linux/issues/10595#issuecomment-2004749084, opt into Steam's client beta and retest.

Closing in favor of the older issue report.
