### ISSUE TITLE
(beta) Steam switching to Windows depot on steam restart

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/steam-for-linux#10648]
#### Your system information

* Steam client version (build number or date): 1710786209
* Distribution (e.g. Ubuntu): Manjaro 23.1.3
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14694067/steam-logs.tar.gz)
* GPU: AMD Vega 64

#### Please describe your issue in as much detail as possible:

When restarting the steam client, it now always tries to download the windows depot for `Startdew Valley`(413153), even though no compatibility tool is forced to activate. But in the end, when actually trying to start the now windows depot app, it tries to start as if it is *not* the windows depot, ie not using Proton.
The only fix i have found is to force activate compatibility tool `Steam Linux Runtime` (1.0 scout, which is the only one available), which will force it to download the linux depot again. If removing the "Force compatibility tool" toggle again (to not use the steam linux runtime), it will reset to the windows depot again on client restart.
When letting the steam linux runtime activated (as a forced compat tool), it will *not* try to download the windows depot again on client restart.

Note: when using `Validate files` it succeeds without downloading anything in either depots.
also uninstalling and then re-installing the game download the windows depot. (if steam linux runtime is not forced to be activated).

Reverting to non-beta client `1709846872` also fixes the issue.

For context, in the windows depot there are the following files:
- `Stardew Valley.exe`

and in the Linux depot there are the files:
- `Stardew Valley` (ELF binary)
- `StardewValley` (bash script)

#### Steps for reproducing this issue:

1. Start steam (in beta update)
2. Install Stardew valley (make sure it is the linux depot)
3. restart the steam client
4. observe steam trying to "update" stardew valley and once through observe the files from the windows depot (ie `.exe` files)

---

In addition to changing the depot, it always clears out the save games files (`~/.config/StardewValley/Saves/*`) and steam cloud reports to have `0 bytes` stored), but as soon as going back to the linux depot, it has stuff stored again. also the `0 bytes` are verified to actually be empty when going to another device and trying to sync the saves.

PS: also from what i can tell, it currently only affects `Startdew Valley`(413153)

**Comment by kisak-valve** [comment]
Hello @hasezoey, this issue is already being tracked at #9875. Closing as a duplicate.
