### ISSUE TITLE
Steam doesn't allow to login twice (once with native steam and once using wine)

### ISSUE THREAD

**Issue by testian** [ValveSoftware/steam-for-linux#1065]
I think the DRM restriction should be per game or per "gaming". Steam shouldn't disallow logging in twice it should only disallow playing the same game twice, or if a harder restriction is desired: Allowing to run a game while another game runs.

Otherwise I can't update windows and Linux games at the same time.

**Comment by ion1** [comment]
Could you please reconsider this? Being able to run a native instance and a Wine instance simultaneously would alleviate the pain with switching between native and Wine games while #74 is not solved.

AFAIU the in-home streaming functionality lets an account run two instances on the same network. How much work would it take to make that possible on the same computer?

**Comment by Tele42** [comment]
I was under the impression this policy was put in place to break some tools that allowed players to control multiple characters in some games (zerging) and it has been in place for a relatively long time.

**Comment by ibrokemypie** [comment]
@Tele42  how come it doesnt efffect other computers with the same account?
