### ISSUE TITLE
Unable to browse the UI (store, settings, etc) when a software is launched from Steam in game mode

### ISSUE THREAD

**Issue by RodoMa92** [ValveSoftware/steam-for-linux#10659]
This to me looks a focusing issue, but as soon as I bootup an external program, I can't in any way go back seeing the main interface. If I open multiple softwares I can freely switch between them no problem, but I'm still not able to interact with the store/settings until I close all the opened softwares.

Pressing the Steam/QAM button show the suppored interface that should have shown up for a frame before showing the side menus correctly.

I'll attach a video demonstrating the issue shortly.

**Comment by RodoMa92** [comment]
I'm not running SteamOS to be clear, but Bazzite. Just for your information.

**Comment by MEGA-Dawg68** [comment]
Hello, sorry nobody has answered your issue. I can offer some advice like, have you tried anything but chromium? It could be an issue with chromium

**Comment by RodoMa92** [comment]
Found the issue, it wasn't the client fault. It was a plugin for decky, BrightnessBar, that was using useComposition() incorrectly in React and for whatever reason was breaking UI rendering on top of a running game.
