### ISSUE TITLE
steamdeck cs2 black textures

### ISSUE THREAD

**Issue by gagaggagg** [ValveSoftware/steam-for-linux#10662]
#### Steamdeck oled

* Steam client version: 20240228.2
* Distribution (e.g. Ubuntu): Linux Mesa i guess
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* GPU: Nvidia/Intel/AMD.    AMD

CS2, Native, broken textures, few weeks ago were no issues. 

![IMG_4761](https://github.com/ValveSoftware/steam-for-linux/assets/164861219/ce74700c-6cd7-4755-a36c-f41b98caf956)

**Comment by kisak-valve** [comment]
Hello @gagaggagg, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3657. Closing as a duplicate.
