### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by cucumber-sp** [ValveSoftware/steam-for-linux#10675]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-2
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia RTX 3050ti Mobile

#### Startup terminal log
```
[cucumbersp@VICTUS-LAPTOP ~]$ steam
steam.sh[2784]: Running Steam on arch rolling 64-bit
steam.sh[2784]: STEAM_RUNTIME is enabled automatically
setup.sh[2856]: Steam runtime environment up-to-date!
steam.sh[2784]: Steam client's requirements are satisfied
tid(2903) burning pthread_key_t == 0 so we never use it
[2024-03-27 13:48:15] Startup - updater built Mar  6 2024 20:27:25
[2024-03-27 13:48:15] Startup - Steam Client launched with: '/home/cucumbersp/.local/share/Steam/ubuntu12_32/steam'
minidumps folder is set to /tmp/dumps
03/27 13:48:15 Init: Installing breakpad exception handler for appid(steam)/version(1709846872)/tid(2903)
crash_20240327134815_2.dmp[2906]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240327134815_2.dmp
/home/cucumbersp/.local/share/Steam/steam.sh: line 813:  2903 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
[cucumbersp@VICTUS-LAPTOP ~]$ crash_20240327134815_2.dmp[2906]: Finished uploading minidump (out-of-process): success = yes
crash_20240327134815_2.dmp[2906]: response: CrashID=bp-e6793eb1-01de-493c-83ba-30c392240327
crash_20240327134815_2.dmp[2906]: file ''/tmp/dumps/crash_20240327134815_2.dmp'', upload yes: ''CrashID=bp-e6793eb1-01de-493c-83ba-30c392240327''
```
(Remove .txt from files extensions)

[crash_20240327134815_2.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/14772166/crash_20240327134815_2.dmp.txt)
[steam-logs.tar.gz.txt](https://github.com/ValveSoftware/steam-for-linux/files/14772171/steam-logs.tar.gz.txt)

**Comment by TTimo** [comment]
You are crashing in GLX initialization, this is probably a driver configuration problem.

**Comment by BiasedKiwi** [comment]
@TTimo Got the same issue and I managed to fix it by uninstalling `lib32-nvidia-utils`.

Any idea on why that works?

**Comment by TTimo** [comment]
> Any idea on why that works?

You need functional 32 bit and 64 bit GL drivers.
