### ISSUE TITLE
Dpad under buttons and buttons under dpad have no glyphs

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10685]
#### Your system information

* Steam client version: 1711147596
* SteamOS version:  3.5.17
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/xmIl2FItVjQ
When setting the physical dpad to have a button layout or the physical buttons to have a dpad layout, Steam Input shows no glyphs for them. This makes binding them hard. They're not in a simple clockwise order so you have to know by trial and error which of the bindings corresponds to which button
I have previously reported this on the Steam Forums: https://steamcommunity.com/groups/bigpicture/discussions/4/3802776070749559928/

#### Steps for reproducing this issue:

1. Set physical dpad to have the button layout
2. Set the physical buttons to have the dpad layout

#### Result
No glyphs are shown

#### Expected
Some sort of glyphs should be shown.

**Comment by Managor** [comment]
This has been fixed in the latest beta. Plz someone mark these in the patch notes.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.
