### ISSUE TITLE
Discrepancy between Gamemode and desktop library creation

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10681]
#### Your system information

* Steam client version: 1711147596
* SteamOS version:  3.5.17
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/mnIC7paFZLo
There is a disparity between gamemode and desktop library creation. In gamemode when you format the SD card, it creates a folder ../primary/steamapps, but when you create a library in the desktop mode it created a folder ../primary/SteamLibrary/steamapps. This is why you can't sometimes rediscover your games when swapping SD cards formatted in gamemode while on desktop

I previously reported this on the Steam Forums https://steamcommunity.com/app/1675200/discussions/1/3642874410681339368/

#### Steps for reproducing this issue:

1. Format an SD card or create a library on an already formatted one

#### Result
The library will be created in the root of the SD card

#### Continuation steps

2. Create a library in desktop mode

#### Result
The library will be created in a subfolder named SteamLibrary

#### Expected
Both methods should produce the same outcome

**Comment by lostgoat** [comment]
Thanks for the report, should be fixed in today's beta update.

**Comment by Managor** [comment]
If I format an SD card in gamemode, it still creates the library in the root of the SD card. Now if I go to desktop mode to create a library it appears in a `SteamLibrary` subfolder. Both methods should create a subfolder.
As for the hotplugging in desktop mode, I didn't test it throughly before reposting the report. It seems that hotplugging a Steam library that's been created in gamemode or desktop mode both won't be automatically discovered by Steam.

It's great if this report allowed you to find undiscovered issues, but the original purpose was to point out the root vs  subfolder discrepancy.

**Comment by lostgoat** [comment]
The discrepancy is intended for complicated reasons.

The bug that was fixed was that libraries in a subfolder were not being detected on hotplug. That should be fixed.

**Comment by Managor** [comment]
Understood. Then I assume the issue can be closed.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.
