### ISSUE TITLE
Install game under different path doesn't allow change in case of bad selection

### ISSUE THREAD

**Issue by azder** [ValveSoftware/steam-for-linux#1069]
Using Steam on Ubuntu 12.04 AMD64
1. Choose to install Counter-Strike (beta)
2. When asked `Choose location for install:` click `Create new Steam library on drive`...
3. Choose a wrong directory
4. There is no way (other than restart of Steam) to change the path to a different one on the same _drive_

**Comment by kisak-valve** [comment]
Closing as this is no longer relevant.
