### ISSUE TITLE
Add a way to create a start menu shortcut after installation 

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10703]
#### Your system information

* Steam client version:![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/235ca993-83be-46f0-a2ab-89f0b3abf98b)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14793620/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Atleast on linux for new users, you have to make a desktop shortcut and then deliver the .desktop file to ~/.local/share/applications/ which he might not have the knowledge to do. At least currently I can't just drag and drop a desktop file to the start menu, but I'll file a feature request to KDE.
I previously reported this on the Steam Forums: https://steamcommunity.com/discussions/forum/1/144512526673730328/

**Comment by kisak-valve** [comment]
Hello @Managor, this issue needs to be evaluated and resolved by your distro's packaging for Steam. Report this issue to your distro's package maintainer(s) for Steam.

**Comment by Managor** [comment]
How would that help? What I desire is to have a menu action in steam for adding a game to the start menu after installation. Similar to this menu entry.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/19d33526-b9e1-4acd-9892-ba17c3f2ff72)

The only ways to do it currently are to uninstall and reinstall the game or to manually place that desktop entry in ~/.local/share/applications/

**Comment by kisak-valve** [comment]
Sorry, I misread this as an issue with the application menu shortcut for the Steam client instead of for games. This issue is already being tracked at #8354. Closing as a duplicate.
