### ISSUE TITLE
Just fix this

### ISSUE THREAD

**Issue by paboum** [ValveSoftware/steam-for-linux#10713]
Started to happen with new UI some months ago. I'm sure it's because you can't into X code and workarounds work with KDE but fails on my xmonad.

https://github.com/ValveSoftware/steam-for-linux/assets/54635274/aab87cd5-8225-4fec-9ac4-5dfe17204d10

**Comment by paboum** [comment]
I waited these months so that someone else reports this but it seems not to be the case (didn't review 2700 open issues though).

**Comment by kisak-valve** [comment]
Hello @paboum, this issue is already being tracked at #9376. Closing as a duplicate.
