### ISSUE TITLE
Certain hostname in /etc/hosts causes slow Steam startup and broken BPM

### ISSUE THREAD

**Issue by ishitatsuyuki** [ValveSoftware/steam-for-linux#10712]
#### Your system information

* Steam client version (build number or date): 1711734008
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14812666/steam-logs.tar.gz)

* GPU: AMD Radeon 5700 XT

#### Please describe your issue in as much detail as possible:

Some web developer tools configure aliases for 127.0.0.1 for local web servers. They may scatter entries like the following in `/etc/hosts`:

```
127.0.0.1 postgres-13-5432.some.local
```

This exact hostname causes Steam's websocket server to reject requests with 403 (checked with -dev and F12). As a result, the client will wait until the 30s re-connect timeout until it give up and shows an window, and some Big Picture mode interface will also be broken.

#### Steps for reproducing this issue:

1. Put the following content in `/etc/hosts`.
    ```
   127.0.0.1 postgres-13-5432.some.local
   ```
2. Start Steam.

**Comment by lostgoat** [comment]
Thanks for the report. This issue should be fixed in the latest beta.

**Comment by ishitatsuyuki** [comment]
I haven't been playing games for a while so I won't be able to test this, but tentatively marking this closed since it was addressed
