### ISSUE TITLE
Steam does bunch of downloads && revalidation on EVERY reboot of steam client after steam was reinstalled

### ISSUE THREAD

**Issue by kaarelen** [ValveSoftware/steam-for-linux#10710]
#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14811043/steam-logs.tar.gz)

* GPU: Amd iGPU + nvidia GPU

#### Please describe your issue in as much detail as possible:
Every time when I start steam, it validating bunch of installed games (sometimes more, sometimes only few) and downloading some data. It's not full redownload but still it takes a lot of time because some games are 70+ GB and validating take SOME time. It makes steam barely usable because sometimes I have to wait 15–30 minutes, for each big game, just to play a game that 100% already downloaded & doesn't have any pending updates. Also, I have no idea why reevaluating took so much time - I have only SSD drives & my processor is 7600X (5GHz 6 core cpu) == there is no reason for bottlnecking.

#### Steps for reproducing this issue:

1. Reinstall steam
2. Add drive with already installed games from previous installation.
3. You will see validation process of random games on every steam boot. (checkout screenshots)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/57552528/3edf8f1b-6ff6-4af4-bac4-2f03dd99010c)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/57552528/57c0cbf3-4e1e-4909-9d2f-6b9e5596c9f5)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/57552528/183124be-6f9a-4a3a-b48e-5e259fa33eba)

Thanks!

PS: My English is far from perfect, I'm sorry for any inconveniences.

**Comment by kisak-valve** [comment]
Hello @kaarelen, this issue is already being tracked at #10285. Closing as a duplicate.

**Comment by kaarelen** [comment]
@kisak-valve i'm sorry that i havent find it. Thanks!
