### ISSUE TITLE
CS2 is "validating" all the time

### ISSUE THREAD

**Issue by trigger337** [ValveSoftware/steam-for-linux#10726]
#### Your system information

* Steam client version (build number or date): 1711734008
* Distribution (e.g. Ubuntu): Fedora 39
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14825732/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
CS2 keeps "validating" as the title says. Every time I start Steam, I see "validating" on CS2 and 2GB of my SSD's life are wasted. It also happens occasionally even when I'm playing the game, it randomly starts "validating" as if it just updated, but there were no updates. This only affects CS2 and happened on all accounts I tried, but only on my PC. I tried moving the game, reinstalling, repairing files and library, clearing download cache, reinstalling Steam, switching to beta and stable.
Here is a screenshot showing the problem:
![Screenshot](https://github.com/ValveSoftware/steam-for-linux/assets/72268042/12ecf5e5-1982-4421-b4a7-f2166a0ed57c)

#### Steps for reproducing this issue:

1. Start Steam and login
or
1. Play CS2 and wait

#### Found solutions
One temporary solution I found helps start the game. If you go to the "downloads" page, you can pause the "update" and start playing the game. The "validation" will continue on it's own later.

**Comment by kisak-valve** [comment]
Hello @trigger337, this issue is already being tracked at #10285. Closing as a duplicate.
