### ISSUE TITLE
Input Mode selection dropdown menu jitters if the preselected entry is low enough in the menu

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10728]
#### Your system information

* Steam client version: 1711734008
* SteamOS version:  3.5.17
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/Sum_VSjQngs
If I go to the joystick or trackpad settings, select an Input Mode as low as possible and then reopen that dropdown menu, it jitters a bit before settling down. It's like there are two forces acting upon it: The upward momentum of the menu while the system tries to periodically set the height of the menu correctly. This doesn't affect other input sources as they don't have enough input methods for this to manifest.

#### Steps for reproducing this issue:

1. Go to Trackpad input category
2. Set Input Mode to Single button
3. Reopen the Input Mode dropdown menu

#### Result:
The menu jitters for a moment

#### Expected:
The menu should open smoothly

**Comment by Managor** [comment]
This might have been fixed in the latest beta with "Minor UI Tweaks."

**Comment by kisak-valve** [comment]
Closing as fixed in the [2024-05-13](https://store.steampowered.com/news/app/593110/view/4204750469854687539) Steam client update.
