### ISSUE TITLE
Running Steam with gamemode hangs bwrap on: wait status 134

### ISSUE THREAD

**Issue by Galcian79** [ValveSoftware/steam-for-linux#10723]
#### Your system information

* Steam client version (build number or date):  1709846872
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam.log](https://github.com/ValveSoftware/steam-for-linux/files/14817943/steam.log)

#### Please describe your issue in as much detail as possible:

As a consequence Steam cannot run in unprivileged mode.

#### Steps for reproducing this issue:

Run steam w & w/o gamemode.

**Comment by smcv** [comment]
This looks like the same issue as https://github.com/ValveSoftware/steam-runtime/issues/658, which is really a bug in the gamemode `LD_PRELOAD` module (https://github.com/FeralInteractive/gamemode/issues/347).

The Steam public beta has a workaround for this. You can opt-in to the public beta by running Steam without `gamemoderun` and using the GUI, or by completely exiting from Steam, `echo -n publicbeta > ~/.steam/root/package/beta` and running Steam again.

`gamemoderun` can cause other problems that can harm performance (such as repeated crashes in `lsof`) and there is no general workaround for those, except for not running all of Steam under `gamemoderun`.

For games where it makes a genuine difference to performance and does not cause crashes, you can set the launch options for individual games to `gamemoderun %command%` instead, to activate gamemode more selectively.

**Comment by Galcian79** [comment]
> This looks like the same issue as [ValveSoftware/steam-runtime#658](https://github.com/ValveSoftware/steam-runtime/issues/658), which is really a bug in the gamemode `LD_PRELOAD` module ([FeralInteractive/gamemode#347](https://github.com/FeralInteractive/gamemode/issues/347)).
> 
> The Steam public beta has a workaround for this. You can opt-in to the public beta by running Steam without `gamemoderun` and using the GUI, or by completely exiting from Steam, `echo -n publicbeta > ~/.steam/root/package/beta` and running Steam again.
> 
> `gamemoderun` can cause other problems that can harm performance (such as repeated crashes in `lsof`) and there is no general workaround for those, except for not running all of Steam under `gamemoderun`.
> 
> For games where it makes a genuine difference to performance and does not cause crashes, you can set the launch options for individual games to `gamemoderun %command%` instead, to activate gamemode more selectively.

Mind you, i don't have a potato pc, i made use of gamemoded just to inhibit the screensaver and DPMS. This issue made me search for a better solution and, digging on the web, i found in KDE Wayland we have indeed such a smart interface: kde-inhibit.

`kde-inhibit --screenSaver --power steam`

**Comment by kapsh** [comment]
@Galcian79  _really_ offtopic here, but your case under KDE can be solved easier: create separate so called activity, disable screensaver and/or sleeping for it and run steam with games exclusively on it. When you are done, just switch back to default activity - no need to run obscure commands or close steam client launched with inhibitor.

**Comment by Galcian79** [comment]
> @Galcian79 _really_ offtopic here, but your case under KDE can be solved easier: create separate so called activity, disable screensaver and/or sleeping for it and run steam with games exclusively on it. When you are done, just switch back to default activity - no need to run obscure commands or close steam client launched with inhibitor.

I use scripts to launch games and close steam on game exit. I don't make much use of the steam client, except for managing games and browse the store. And managing env variables in shell scripts is simple like commenting and uncommenting a line.
Anyway really off topic here.

**Comment by SylvKT** [comment]
> For games where it makes a genuine difference to performance and does not cause crashes, you can set the launch options for individual games to `gamemoderun %command%` instead, to activate gamemode more selectively.

I'm not sure if this is an issue with the game its
elf, but I've found so far that doing that with SCP: Secret Laboratory causes the game to crash (no matter the Proton version) with an interesting log. This is a stretch, but perhaps this is related to the dbus NULL thing? This is also pretty recent, too.

[Player.log](https://github.com/ValveSoftware/steam-for-linux/files/14968497/Player.log)

**Comment by kisak-valve** [comment]
Closing as worked-around in the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.
