### ISSUE TITLE
dropdown menu items not clickable

### ISSUE THREAD

**Issue by Firefly1127** [ValveSoftware/steam-for-linux#10732]
#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): arch Linux
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14827504/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
certain dropdown menus are not working on the steam client specifically the sort by drop down of the wishlist. I can press them and see the options. But when I select one it closes it but doesn't apply it. If there is a button behind the menu that button is pressed (add to cart).
#### Steps for reproducing this issue:

1. open steam client
2. navigate to wishlist
3. attempt to modify the sort by: dropdown
4. won't change

**Comment by Firefly1127** [comment]
further note: the filters for customer reviews also do this

and it's not all dropdowns, all of the "in client" dropdowns work (for example the filter for the library and dropdowns when you select store, library, community etc work fine).

**Comment by kisak-valve** [comment]
Hello @Firefly1127, this issue is already being tracked at #9273. Closing as a duplicate.

**Comment by usr0x01ff** [comment]
Hello @Firefly1127, 

I had the same issue #10768

For me the workaround in Ubuntu dconf-editor setting "focus-mode"  to "click" worked.

Maybe 'arch Linux'  has a similar setting for you?
