### ISSUE TITLE
Steam Broadcasting does not work on Linux

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10744]
#### Your system information

* Steam client version: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/8ee156e7-c6cf-4e67-a09f-e8ce02cb9340)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14835681/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Steam Broadcasting does not work. The stream is stuck in "Waiting for stream to start" for a friend that tunes in to watch. This is somewhat odd since Steam Remote Play to my phone and to my Steam Link hardware works just fine

#### Steps for reproducing this issue:

1. Allow broadcasting in Steam settings -> Broadcast -> Privacy settings
2. Start a game
3. Get a friend to watch your broadcast

#### Result:
The stream is stuck in "Waiting for stream to start"

#### Expected:
Stream should work

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #6815. Closing as a duplicate.
