### ISSUE TITLE
Steam crashed in Orange PI 5/Ubuntu 22.04

### ISSUE THREAD

**Issue by lado2com** [ValveSoftware/steam-for-linux#10757]
#### Your system information

* Steam client version (build number or date): Latest (1.0.0.79)
* Distribution: Ubuntu 22.04.4 LTS (Orange PI 5 16Gb)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]

I tried to open Steam after installed/reinstalled:

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14855636/steam-logs.tar.gz)

#### Steps for reproducing this issue:

1. Execute steam via console:
steam.sh[30692]: Running Steam on ubuntu 22.04 64-bit
steam.sh[30692]: STEAM_RUNTIME is enabled by the user
setup.sh[30758]: Steam runtime environment up-to-date!
steam.sh[30692]: Steam client's requirements are satisfied
Box86 with Dynarec v0.3.1 e8d4ffc7 built on Aug  8 2023 13:12:28
[2024-04-03 10:33:25] Startup - updater built Mar  6 2024 20:27:25
[2024-04-03 10:33:25] Startup - Steam Client launched with: '/home/cristhian/.local/share/Steam/ubuntu12_32/steam'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2024-04-03 10:33:26] Loading cached metrics from disk (/home/cristhian/.local/share/Steam/package/steam_client_metrics.bin)
[2024-04-03 10:33:26] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2024-04-03 10:33:26] Using the following download hosts for Public, Realm steamglobal
[2024-04-03 10:33:26] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-04-03 10:33:26] Checking for update on startup
[2024-04-03 10:33:26] Checking for available updates...
[2024-04-03 10:33:26] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2024-04-03 10:33:26] Manifest download: send request
[2024-04-03 10:33:26] Manifest download: waiting for download to finish
[2024-04-03 10:33:26] Manifest download: finished
[2024-04-03 10:33:26] Download skipped: /client/steam_client_ubuntu12 version 1709846872, installed version 1709846872, existing pending version 0
[2024-04-03 10:33:26] Nothing to do
[2024-04-03 10:33:26] Verifying installation...
[2024-04-03 10:33:26] Performing checksum verification of executable files
[2024-04-03 10:33:27] Verification complete
UpdateUI: skip show logoError initializing native libpng12.so.0 (last dlerror is libpng12.so.0: clase ELF errónea: ELFCLASS64)

Steam logging initialized: directory: /home/cristhian/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0x40180120
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0x40180130
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier `direction', expected character `}'
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
steamwebhelper.sh[30819]: === mié 03 abr 2024 10:33:31 CST ===
steamwebhelper.sh[30819]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/cristhian/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
Error initializing native libgnutls.so.30 (last dlerror is libgnutls.so.30: clase ELF errónea: ELFCLASS64)
Error: Symbol __gmpz_scan1 not found, cannot apply R_386_JMP_SLOT 0xe1f0d010 (0x48b6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_init_set not found, cannot apply R_386_JMP_SLOT 0xe1f0d01c (0x48e6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_tdiv_qr not found, cannot apply R_386_JMP_SLOT 0xe1f0d024 (0x4906) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_copyd not found, cannot apply R_386_JMP_SLOT 0xe1f0d028 (0x4916) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_cnd_sub_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d030 (0x4936) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmp_get_memory_functions not found, cannot apply R_386_JMP_SLOT 0xe1f0d064 (0x4a06) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_set_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d074 (0x4a46) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_rshift not found, cannot apply R_386_JMP_SLOT 0xe1f0d07c (0x4a66) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_limbs_modify not found, cannot apply R_386_JMP_SLOT 0xe1f0d088 (0x4a96) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_sub not found, cannot apply R_386_JMP_SLOT 0xe1f0d098 (0x4ad6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_fdiv_q not found, cannot apply R_386_JMP_SLOT 0xe1f0d0a8 (0x4b16) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_sub_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d0b4 (0x4b46) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_setbit not found, cannot apply R_386_JMP_SLOT 0xe1f0d0c4 (0x4b86) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_tstbit not found, cannot apply R_386_JMP_SLOT 0xe1f0d0e0 (0x4bf6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_mul not found, cannot apply R_386_JMP_SLOT 0xe1f0d0e4 (0x4c06) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_mul_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d110 (0x4cb6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_fdiv_q_2exp not found, cannot apply R_386_JMP_SLOT 0xe1f0d124 (0x4d06) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_mul_2exp not found, cannot apply R_386_JMP_SLOT 0xe1f0d12c (0x4d26) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_limbs_read not found, cannot apply R_386_JMP_SLOT 0xe1f0d140 (0x4d76) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_submul_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d154 (0x4dc6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_add_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d15c (0x4de6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_sqr not found, cannot apply R_386_JMP_SLOT 0xe1f0d16c (0x4e26) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_limbs_finish not found, cannot apply R_386_JMP_SLOT 0xe1f0d178 (0x4e56) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_mul_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d180 (0x4e76) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_congruent_p not found, cannot apply R_386_JMP_SLOT 0xe1f0d184 (0x4e86) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_submul_1 not found, cannot apply R_386_JMP_SLOT 0xe1f0d18c (0x4ea6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_copyi not found, cannot apply R_386_JMP_SLOT 0xe1f0d198 (0x4ed6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_add_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d1a8 (0x4f16) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_invert not found, cannot apply R_386_JMP_SLOT 0xe1f0d1dc (0x4fe6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_probab_prime_p not found, cannot apply R_386_JMP_SLOT 0xe1f0d1f0 (0x5036) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_tdiv_q_2exp not found, cannot apply R_386_JMP_SLOT 0xe1f0d1f4 (0x5046) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_roinit_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d1f8 (0x5056) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_powm_sec not found, cannot apply R_386_JMP_SLOT 0xe1f0d214 (0x50c6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_fdiv_r not found, cannot apply R_386_JMP_SLOT 0xe1f0d220 (0x50f6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_init_set_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d238 (0x5156) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_zero not found, cannot apply R_386_JMP_SLOT 0xe1f0d264 (0x5206) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_gcd not found, cannot apply R_386_JMP_SLOT 0xe1f0d270 (0x5236) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_add not found, cannot apply R_386_JMP_SLOT 0xe1f0d274 (0x5246) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_perfect_square_p not found, cannot apply R_386_JMP_SLOT 0xe1f0d2a4 (0x5306) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_fdiv_r_2exp not found, cannot apply R_386_JMP_SLOT 0xe1f0d2b0 (0x5336) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_limbs_write not found, cannot apply R_386_JMP_SLOT 0xe1f0d2ec (0x5426) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_powm_ui not found, cannot apply R_386_JMP_SLOT 0xe1f0d2f0 (0x5436) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpz_com not found, cannot apply R_386_JMP_SLOT 0xe1f0d304 (0x5486) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_addmul_1 not found, cannot apply R_386_JMP_SLOT 0xe1f0d318 (0x54d6) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_mul_1 not found, cannot apply R_386_JMP_SLOT 0xe1f0d324 (0x5506) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: Symbol __gmpn_cnd_add_n not found, cannot apply R_386_JMP_SLOT 0xe1f0d32c (0x5526) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libhogweed.so.4
Error: relocating Plt symbols in elf libhogweed.so.4
Error: Symbol udev_device_get_usec_since_initialized not found, cannot apply R_386_JMP_SLOT 0xf547be2c (0x2436) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgudev-1.0.so.0
Error: Symbol udev_device_get_seqnum not found, cannot apply R_386_JMP_SLOT 0xf547be74 (0x2556) in /home/cristhian/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgudev-1.0.so.0
Error: relocating Plt symbols in elf libgudev-1.0.so.0
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
dbus[30793]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
/home/cristhian/.local/share/Steam/steam.sh: línea 813: 30793 Abortado                (`core' generado) "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by kisak-valve** [comment]
Hello @lado2com, sorry, but running Steam for Linux on ARM based hardware is not supported at this time. (#4061)
