### ISSUE TITLE
Ghost window pops up when closing child windows

### ISSUE THREAD

**Issue by rehdi93** [ValveSoftware/steam-for-linux#10758]
#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Fedora KDE 39
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steamlogs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14860968/steamlogs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
A "ghost" window briefly pops up on the top-left-ish of the screen when some child window close. 

This also happens w/ notifications which is very annoying.

https://github.com/ValveSoftware/steam-for-linux/assets/25366969/66acb700-221e-490a-8b9f-bfc871f58fd1

#### Steps for reproducing this issue:

1. Open a steam child window like the friends list, news or about steam
2. Close it

*OR*

1. Receive a notification

**Comment by kisak-valve** [comment]
Hello @rehdi93, I expect that this is a side effect of the "safe browser shutdown workaround." You can try to avoid this issue by running Steam with `STEAM_DISABLE_BROWSER_SHUTDOWN_WORKAROUND=1 steam` from a terminal (from https://github.com/ValveSoftware/steam-for-linux/issues/9458#issuecomment-1613759526).

My understanding is that workaround is to compensate for a video driver bug and will need to stick around until the affected driver versions are uncommon.

**Comment by rehdi93** [comment]
the env variable does fix it, ty ^-^

**Comment by Reonu** [comment]
> Hello @rehdi93, I expect that this is a side effect of the "safe browser shutdown workaround." You can try to avoid this issue by running Steam with `STEAM_DISABLE_BROWSER_SHUTDOWN_WORKAROUND=1 steam` from a terminal (from [#9458 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/9458#issuecomment-1613759526)).
> 
> My understanding is that workaround is to compensate for a video driver bug and will need to stick around until the affected driver versions are uncommon.

What are the affected driver versions? Is it safe to disable the workaround with the Nvidia 550 driver?

**Comment by kisak-valve** [comment]
Hello @Reonu, https://github.com/ValveSoftware/steam-for-linux/issues/9576#issuecomment-1989492738 looks like the relevant detail.

**Comment by Reonu** [comment]
Thanks!

**Comment by lorentzforces** [comment]
To update (given that previous answers assumed this would be resolved as of Nvidia's 550 drivers): I am using Nvidia's proprietary drivers, version `550.100`, and I am still experiencing this on X11 (without an environment variable set).

My system information:
- OS: OpenSUSE Tumbleweed
- Steam version: `1721173382`
- Output of `uname -a`: `Linux <redacted> 6.10.4-1-default #1 SMP PREEMPT_DYNAMIC Mon Aug 12 05:49:20 UTC 2024 (0363a35) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by rehdi93** [comment]
after upgrading to Fedora 41, this problem no longer happens. I can run Steam w/o `STEAM_DISABLE_BROWSER_SHUTDOWN_WORKAROUND`

running Wayland w/ nvidia driver 560.35.03

**Comment by kisak-valve** [comment]
Closing per the last comment.
