### ISSUE TITLE
Steam button and quick access button occasionally do not open menu on first press

### ISSUE THREAD

**Issue by Hayden120** [ValveSoftware/steam-for-linux#10750]
[I have also posted this issue on the SteamOS GitHub](https://github.com/ValveSoftware/SteamOS/issues/1389), but it might be more appropriate here.

#### Your system information

* Steam client version: 1708129125
* SteamOS version: 3.6
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
If you have played a game for a length of time (two hours or more, but it seems random), pressing either the Steam button or quick access button (...) while in game will not open the applicable menu on the first press.

You can hear a menu chime sound, which suggests that the press has registered, but nothing will appear on the screen. 

A second press of either the Steam button or quick access button will then open the menu. It will continue working reliably until the buttons are not used again for a couple of hours. 

This bug is reproducible in stable, beta, preview, and main update channels. 

Many other users have reported experiencing this issue: 

E.g. https://www.reddit.com/r/SteamDeck/comments/17913xs/am_i_the_only_one_whose_stream_button_and_menu/

https://www.reddit.com/r/SteamDeck/comments/164dcc8/need_to_press_steam_button_twice_to_open_menu/

https://www.reddit.com/r/SteamDeck/comments/18n100s/i_have_to_press_the_buttons_on_my_steam_deck/

#### Steps for reproducing this issue:

1. Play a game for two hours or so without pressing the quick access button or Steam button
2. Press either the quick access button or Steam button
3. Neither of the menus will open on first press, but you will hear a menu chime sound
4. Press either the quick access button or Steam button again, and the side menu will pop up.

**Comment by kisak-valve** [comment]
Hello @Hayden120, there's no value in fragmenting the discussion of your issue across multiple issue trackers. If it makes more sense to transfer the existing issue report, then make that request in a comment on that issue report. In this specific case, I don't know if this is more of an issue with SteamOS as a platform or some component of the Steam client, so I left your original issue report alone.

Closing as a duplicate.
