### ISSUE TITLE
wishlist sorting combox does not work (activates whatever is underneath)

### ISSUE THREAD

**Issue by usr0x01ff** [ValveSoftware/steam-for-linux#10768]
Steam Beta Branch:  Stable Client
Steam Version:  1709846872
Steam Client Build Date:  Wed, Mar 6 9:28 PM UTC -08:00
Steam Web Build Date:  Thu, Mar 7 10:17 PM UTC -08:00
Steam API Version:  SteamClient021
* Distribution: Ubuntu 22.04.4 LTS (64 bit)
* System info: https://gist.github.com/usr0x01ff/3cdf5fbcd64ea7a226a0a5b70d4a89f9
* Opted into Steam client beta? No
* Have you checked for system updates? Yes (no update available)
* Steam Logs:  N.A. (no log messages happen upon this issue)
* GPU: Nvidia (on-demand), else AMD Renoir

#### Please describe your issue in as much detail as possible:
The sorting combobox for the wishlist does not work (any more).
It keeps set on "Sort by: Price" and when trying to select another sorting with mouse button, this is activating the widgets from the wish list underneath the combobox list.

Note the "Search by name.." and "Options" all work correctly, so it concerns only this sorting combobox.

Note that settings->interface->"Enable context menu focus compatibility mode" has no effect on this (disabled or enabled).

#### Steps for reproducing this issue:
For example:
* Selecting "Name" (at rightside) will activate "remove" of the first item on the wishlist
* Selecting "Price" (at rightside) will activate the button, which can be either:
    -  "Play Now"  for a "free to play" game
    -  "Add to Cart" for a game on sale
    -  "Coming soon" for a not yet available game

In all situations the sorting does not change.
[steam_wishlist_sorting_does_not_work.webm](https://github.com/ValveSoftware/steam-for-linux/assets/166165734/a9f2e604-1e2b-40e8-9c2e-f3e4b7fd0936)

**Comment by kisak-valve** [comment]
Hello @usr0x01ff, this issue is already being tracked at #9273. Closing as a duplicate.

**Comment by usr0x01ff** [comment]
Issue #9273 describes dropdown in game->properties, which work in my client.
(eg proton compatibility, language, controller, etc.. all work)

I only have  an issue with the wishlist.

But #9273 does describe the same behaviour: 
"The form controls behind the dropdown seem to activate through it"

Note the suggested workaround  Shift/Alt/Ctrl+Click did not work for me on the wishlist dropdown menu.

What did work was in dconf-editor setting
/org/gnome/desktop/wm/preferences/focus-mode
to value "click" (iso "sloppy")

I guess it is indeed similar issue, but why the properties worked for me, I don't know.
