### ISSUE TITLE
Unable to uninstall preinstalled windows game without turning on forced compatibility.

### ISSUE THREAD

**Issue by TH3C4V** [ValveSoftware/steam-for-linux#10763]
#### Your system information

* Steam client version (build number or date): Latest
* Distribution: Xubuntu [Debian]
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: 
* GPU: Nvidia RTX 3060 Ti

#### Please describe your issue in as much detail as possible:
My windows build is no longer working on my computer, however I can still boot and use linux just fine. When I want to uninstall one of the games I downloaded in Windows, I have to enable forced compatibility before I can do so. I expect that you can uninstall any game you want to, without forcing proton to be installed.

#### Steps for reproducing this issue:

1. Install Game in windows.
2. Boot into linux.
3. Launch steam and attempt to uninstall from manage in context menu.
4. The button isn't there.

**Comment by kisak-valve** [comment]
Hello @TH3C4V, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing a Steam library folder between OSes is not supported and undefined behavior might occur. There are no pre-installed games done by Steam.

**Comment by TH3C4V** [comment]
> Hello @TH3C4V, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing a Steam library folder between OSes is not supported and undefined behavior might occur. There are no pre-installed games done by Steam.

The note regards "Files installed by Steam for Linux". I had assumed that since I can mount and use my Windows drives just fine in linux, that I would also be able to uninstall games to free up space.
