### ISSUE TITLE
Steam MUST stop being Linux native games only by default (and stop deleting saved games for non SteamCloud apps)

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/steam-for-linux#10770]
Steam for Linux has A LOT of issues, this made me delete everything because sometimes the client just wont launch for me after some time and the only way to fix it is "reinstalling" steam deleting almost everything at it's folder.

1- I delete the files and backup my games (steamapps folder).
2- Start Steam.
3- New folders and files created by the client (nice this will make it responsive again).
4- Close Steam and drag and drop my games backup.
5- Steam sees a lot of games that i've configured to use Proton but decides to install terrible Linux ports (I forgot to enable SteamPlay for all the titles).
6- Steam also starts deleting proton config folders for the games.
7- I lost my Dead or Alive 5 saves AGAIN because games not having Steam Cloud have their files on those proton folders and get deleted everytime i change the Proton version to use or Steam believes it needs to delete its proton folder because i don't want to use Proton for some reason).

Seriously, there is no point of using Steam on Linux without Proton for every title since Valve is not doing the whitelist thing anymore. Just make the Linux client act like a Steam Deck and enable Proton for every title forever and just advice about no confirmed compatibility on games.

For real, i lost all my progress like 3 times already just for changing proton versions on my Steam Deck or for not remembering to activate that opt-in option when resetting Steam.

This opt-in situation needs to stop, Proton for all titles must be default, and the proton version selected must be remembered when installing Steam again. I feel really sad losing my progress again, I was almost completing 100% the game.

**Comment by KibaGasteiz** [comment]
This is terrible for games not using Steam Cloud.

[Grabación de pantalla desde 2024-04-06 23-32-24.webm](https://github.com/ValveSoftware/steam-for-linux/assets/44957566/133e9200-998b-4d15-8053-b4e39962451a)


If at least I could MARK the files i want to save to SteamCloud without lazy devs intervention...

**Comment by kisak-valve** [comment]
Hello @KibaGasteiz, my understanding is that support for running games with Proton is unofficial and unofficial options can't be enabled by default.

The second half of your issue is already being tracked at #5901 and https://github.com/ValveSoftware/Proton/issues/428. Closing in favor of the older issue reports.
