### ISSUE TITLE
ERROR: ld.so: object [libextest.so] cannot be preloaded

### ISSUE THREAD

**Issue by Milliw** [ValveSoftware/steam-for-linux#10771]
#### Your system information

* Steam client version (build number or date): 1710458266
* Distribution (e.g. Ubuntu): Nobara 39
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: cmd generates empty file due to no log dir in that path
* GPU: Nvidia RTX 2070 Super

#### Please describe your issue in as much detail as possible:
Just saw this message appearing repeatedly in the logs. Seems to have no impact to me but thought reporting it would be good.
`ERROR: ld.so: object '/usr/lib/steam/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

#### Steps for reproducing this issue:
Launch Steam.

**Comment by kisak-valve** [comment]
Hello @Milliw, this reads more like a harmless side effect of a third party tweak which is adding a LD_PRELOAD of libextest.so into Steam's environment before it is started.

Do you have any extra system packages that fiddle with libextest.so?

**Comment by kisak-valve** [comment]
Looking at this a bit more, this is definitely a harmless quirk of a third party tool and not Steam itself: https://github.com/Supreeeme/extest/issues/2#issuecomment-1484166855

If you want to pursue this further, take it up with that project.

Closing as not-our-bug.
