### ISSUE TITLE
Blurred capsules in Home menu

### ISSUE THREAD

**Issue by Ornithorax** [ValveSoftware/steam-for-linux#10774]
#### Your system information

* Steam client version: 3.5.17
* Distribution: SteamOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
In the home screen for SteamOS, when a game is highlighted, the artwork becomes noticeably blurred. This applies to both regular and wide capsules and happens in both the Game Mode home menu as well as Big Picture mode while in desktop mode.

#### Steps for reproducing this issue:

1. Enter home menu on SteamOS
2. Highlight one of the recent games
3. Observe the artwork

https://github.com/ValveSoftware/steam-for-linux/assets/89544396/8b285ddf-aa37-4755-8b86-eb45e32fc367

**Comment by kisak-valve** [comment]
Hello @Ornithorax, this issue is already being tracked at #10613. Closing as a duplicate.
