### ISSUE TITLE
Onscreen keyboard initial location bug

### ISSUE THREAD

**Issue by Xenophobe-01** [ValveSoftware/steam-for-linux#10772]
#### Your system information

* Steam client version (build number or date): Steam Version:  1711734008 - Steam Client Build Date:  Fri, Mar 29 1:09 PM UTC -05:00
* Distribution (e.g. Ubuntu): Linux Mint 21.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14906964/steam-logs.tar.gz)
* GPU: RX 6950 XT, Driver Version: 4.6 (Compatibility Profile) Mesa 24.0.4 - kisak-mesa PPA

#### Please describe your issue in as much detail as possible:

The onscreen keyboard is not using the initial location chosen in settings, I use lower right in both drop down boxes. It is appearing wherever the cursor is, which ends up blocking the typing area. This has been happening since January 2024, I've been reporting this each client update in the Steam Beta Bug Reports https://steamcommunity.com/groups/SteamClientBeta/discussions/0/4142816719795960926/

#### Steps for reproducing this issue:

1. Open the forums
2. place cursor in typing area
3. open the onscreen keyboard with a controller.

#### Expected behavior:

The onscreen keyboard should use the selected initial location when opening regardless of cursor position.

**Comment by kisak-valve** [comment]
Hello @Xenophobe-01, this issue is already being tracked at #10684. Closing as a duplicate.

**Comment by Xenophobe-01** [comment]
Isn't https://github.com/ValveSoftware/steam-for-linux/issues/1068 Steam Deck/Steam OS specific?  That's why I didn't add to that one.  Plus their request is for an automatic opposite side from the cursor, whereas I'm requesting the OSK location follows the settings in the dropdown boxes found in settings under BPM.

**Comment by kisak-valve** [comment]
The other issue report is showing SteamOS running in desktop mode (as opposed to game mode), which shouldn't be a significantly different environment and Steam behavior with the on screen keyboard on your system.
