### ISSUE TITLE
[beta] since last update the client is randomly crashing at start

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#10788]
yep, I am going to collect the logs in both cases (successfully started, crashing) and post them here once I have them.

**Comment by sylware** [comment]
It is still rarely crashing at start, the logs diff does not seem to have anything significant from my knowledge, even that seems random (this smells some kind of races).

I guess I'll have to upload the logs to you then.

**Comment by sylware** [comment]
Ok, still rarely happening. Look like a nasty race.

I have been lazy to cleanup and gather logs for a clean report.

I now wrote scripts (simple sh scripts using conservative options and certainly not bash only scripts using niche and gnu-only command options......) to automate all that.

**Comment by sylware** [comment]
I saw some fixes went in the beta client about what could be this issue. I am still cleanely collecting logs in case those fixes missed this issue.

**Comment by sylware** [comment]
It seems it does not happen anymore.

**Comment by kisak-valve** [comment]
Closing per the last comment.
