### ISSUE TITLE
Cannot select global proton version on Steam Families Beta

### ISSUE THREAD

**Issue by Kaympe20** [ValveSoftware/steam-for-linux#10782]
#### Your system information

* Steam client version (build number or date): 1712795774
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes (Steam Families Beta)
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14969141/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
1. When on the Steam Families Beta, the dropdown for selecting your global proton version is missing
![alt text](https://i.imgur.com/w8Btjxb.png)

#### Steps for reproducing this issue:

1. Use Steam on Linux
2. Opt into the Steam Families Beta
3. Cannot select global proton verison

#### Other Information
Issue has occurred to a few different people including [u/cassgreen_ on Reddit](https://www.reddit.com/r/linux_gaming/comments/1c1dnj3/comment/kz57waf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

**Comment by Revival8697** [comment]
I'm facing a similar issue on build 1712795774, Arch Linux.

**Steps for reproducing this issue**:
1. Opt into Steam Beta Update.
2. Download a compatibility tool like GE-Proton.
3. Open Compatibility settings, the drop down is now blank

This issue only happen when _XDG_DATA_HOME/Steam/compatibilitytools.d_ is NOT empty.

**Comment by CypherDragon** [comment]
Also happening on build 1713317598, Arch Linux.

**Comment by SeongGino** [comment]
Can confirm I had the exact same issue, though it was just the normal Steam Beta Client; rolling back to the normal stable track resolved it.

**Comment by TTimo** [comment]
Thank you, this will be fixed in next Steam beta update.

**Comment by Revival8697** [comment]
> Thank you, this will be fixed in next Steam beta update.

This has been fixed for quite a while. It is working as of now, 1717294964.

**Comment by Revival8697** [comment]
> Thank you, this will be fixed in next Steam beta update.

This has been fixed for quite a while. It is working as of now, 1717294964.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
