### ISSUE TITLE
Unable to open steam on a new build and fresh install of Fedora 39

### ISSUE THREAD

**Issue by stardude900** [ValveSoftware/steam-for-linux#10781]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.79-3.fc39.i686
* Distribution (e.g. Ubuntu): Fedora 39, tried both kernel 6.5 (default installer kernel and 6.8.6-201 (latest))
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes `dnf update --refresh -y ; reboot`
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`].  Attached
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14968942/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD Radeon 7900XT

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I recent built a brand new computer and did a fresh install of Fedora 39.  I cannot get Steam to open after logging in though.  The steamwebhelper will crash immediately after the login swirl.

#### Steps for reproducing this issue:

1. Install Fedora 39 Workstation
2. Install/enable rpmfusion free and nonfree
3. Install Steam `dnf install steam`
4. Update and reboot the system `dnf update --refresh ; reboot`
5. Start Steam
6. Login (i've tried both steamguard and username/password)
7. Steam will crash

**Comment by stardude900** [comment]
Okay, figured it out.  This is due to an MSI bios setting, specifically Setting>Advanced>Integrated Graphics Configuration.  If it's set to UMA Auto it'll crash steam as described in the report, if it's disabled Steam works as expected.

**Comment by kisak-valve** [comment]
Hello @stardude900, that makes the issue you saw #9383.
