### ISSUE TITLE
Black window with MATE + Marco (No compositor)

### ISSUE THREAD

**Issue by fornellas** [ValveSoftware/steam-for-linux#10797]
#### Your system information

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Ubuntu 22.04.4 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15041517/steam-logs.tar.gz)
* GPU: Nvidia GeForce RTX 2070

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When _Settings > Interface > Enable GPU accelerated rendering in web views (requires restart)_ is enabled, Steam will open showing just a black window:

![Screenshot at 2024-04-19 15-10-26](https://github.com/ValveSoftware/steam-for-linux/assets/1386232/fbaf3328-82b2-4a95-bba3-60938126216d)

The issue goes away when GPU rendering is disabled, BUT:

- The menus have glitches rendering (they flicker when opening).
- Big Picture is **unusable**, as it goes below 1fps.

I did some testing, it seems that GPU rendering only works with a compositor:

- GNOME
- Mate + Marco (built-in: Xpresent)

and breaks with:

- Mate + Marco (No compositor)

Interestingly, if Steam is open with Marco (built-in: Xpresent) active, things work, ever after switching back to Marco (No compositor). The issue seems related to some Steam initialisation when no compositor is running.

There's good reason to *not* run a compositor, mainly related to very noticeable input / GUI lag.

It seems various other similar bugs were reported:

https://github.com/ValveSoftware/steam-for-linux/issues/10578
https://github.com/ValveSoftware/steam-for-linux/issues/10561
https://github.com/ValveSoftware/steam-for-linux/issues/10557
https://github.com/ValveSoftware/steam-for-linux/issues/10553
https://github.com/ValveSoftware/steam-for-linux/issues/10543

Which may all have a similar root cause.

#### Steps for reproducing this issue:

1. Open a Mate session.
2. Open MATE Tweak > Windows > Window Manager and select Marco (No compositor)
3. Open Steam: the window will be all black. If big picture is open, it will also be all black (but full screen).

**Comment by kisak-valve** [comment]
Hello @fornellas, this issue is already being tracked at #10543. Until it's fixed, running Steam with `-system-composer` (from https://github.com/ValveSoftware/steam-for-linux/issues/10543#issuecomment-1977277362) might get Steam to behave better for you.

Closing as a duplicate.
