### ISSUE TITLE
cs2 validates every time i boot my system

### ISSUE THREAD

**Issue by firashacker** [ValveSoftware/steam-for-linux#10796]
Your system information
Steam client version (build number or date): 0.20240301.0+srt1
Distribution (e.g. Ubuntu): Running Steam on arch rolling 64-bit
Opted into Steam client beta?: no
Have you checked for system updates?: Yes
Please describe your issue in as much detail as possible:
CS2 keeps "validating" as the title says. Every time I start Steam, I see "validating" on CS2 and 2GB of my SSD's life are wasted. It also happens occasionally even when I'm playing the game, it randomly starts "validating" as if it just updated, but there were no updates. This only affects CS2 and happened on all accounts I tried. I tried moving the game, reinstalling, repairing files and library, clearing download cache, reinstalling Steam, switching to beta and stable.

Steps for reproducing this issue:
Start Steam and login
or
Play CS2 and wait
Found solutions
One temporary solution I found helps start the game. If you go to the "downloads" page, you can pause the "update" and start playing the game. The "validation" will continue on it's own later.

**Comment by kisak-valve** [comment]
Hello @firashacker, this issue is already being tracked at #10285. Closing as a duplicate.
