### ISSUE TITLE
CS2 always downloading 2 GB+ after almost every Steam client restart

### ISSUE THREAD

**Issue by markusbrand** [ValveSoftware/steam-for-linux#10802]
#### Your system information

* Steam client version (build number or date): 1713317598
* Distribution (e.g. Ubuntu): Arch Linux (Garuda)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15049070/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Counter Strike 2 is almost every time I start Steam client downloading an update which has exactly 2 GB. Maybe after every validation - instead of downloading a few KB it always gets a 2 GB package.

This issue is in place already for months. In the Steam Community chat there are also other users complaining about this issue.

#### Steps for reproducing this issue:

1. Install Counter Strike 2
2. Shutdown Steam client (maybe even shutdown PC)
3. restart and see that Counter Strike 2 is updating again

**Comment by kisak-valve** [comment]
Hello @markusbrand, this issue is already being tracked at #10285.

Closing as a duplicate.
