### ISSUE TITLE
Small empty window shows up for an instant and steals my focus whenever I get a Steam notification

### ISSUE THREAD

**Issue by Reonu** [ValveSoftware/steam-for-linux#10809]
#### Your system information

* Steam client version (build number or date): 1713317598
* Distribution (e.g. Ubuntu): EndeavourOS with KDE Plasma up to date as of April 21st. Running Xorg, not Wayland. 
* Opted into Steam client beta?: [Yes/No] Yes, Steam Families Beta
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
Got the following error trying to run this command:
```tar: Removing leading `/' from member names
tar (child): /home/dani/Desktop/steam-logs.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/home/dani/.steam/steam/logs/
/home/dani/.steam/steam/logs/vrwebhelper_settings_desktop.txt
tar: /home/dani/Desktop/steam-logs.tar.gz: Cannot write: Broken pipe
tar: Child returned status 2
tar: Error is not recoverable: exiting now```
* GPU: Nvidia RTX 3070

More details: Dual monitor setup. One 1440p monitor as primary on the right and one 1080p monitor as secondary on the left. Both are 144 Hz. Using 125% DPI scaling. Note that the empty window always shows up in the secondary screen (which for some reason is also where Steam puts its notifications)

#### Please describe your issue in as much detail as possible:
Whenever I get a Steam notification, an empty X window appears in a corner and closes itself instantly. Annoyingly, this steals the focus from whatever window I was interacting why. Especially annoying if I happened to be typing something. More specifically, the empty window seems to show up as the notification is going away, rather than when it appears.

#### Steps for reproducing this issue:

1.  Ask a friend to spam you with lots of messages (have notifications for chat messages enabled)
2.  Minimize the chat window while you're being spammed
3. Suffer through a million empty windows as the notifications go away

Here's a screenshot of the empty window. Note that the window is transparent, so I've censored what was behind it.
![window](https://github.com/ValveSoftware/steam-for-linux/assets/15913880/01fbd682-771c-4a58-b86b-dc6ec5972748)

**Comment by kisak-valve** [comment]
Hello @Reonu, this issue is already being tracked at #10758. Closing as a duplicate.
