### ISSUE TITLE
the Steam client gets stuck when initializing

### ISSUE THREAD

**Issue by unclejack** [ValveSoftware/steam-for-linux#10800]
#### Your system information

* Steam client version:1713317598
* SteamOS version: 3.5.18
* Opted into Steam client beta?: [Yes/No] No
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expect the device to turn on, to boot and start the Steam client every single time. 

Instead, the screen stays black for a while and gets stuck on the Steam logo forever. The device is reachable via SSH on the wifi network without issues at that point. It appears to have booted and the Steam client gets stuck while trying to do something it doesn't really seem to manage to do after that point.

This Steam Deck unit was never opened. The only modification was the installation of the test kernels to check if they help with the amdgpu crashes on a previous version of the OS. There are no loaders/plugins/3rd party tools or anything else that would justify such odd behaviour.

I haven't started to dig into the logs yet. I've spent enough time debugging the amdgpu crash to spend more time doing debugging work.

Perhaps someone at Valve can check if there's some recent change which introduced this bug?

#### Steps for reproducing this issue:

1. Buy a Steam Deck LCD 
2. Opt into the Steam OS beta because of unresolved issues
3. Use the Steam Deck for a while
4. Update it
5. Try to boot the system
6. See the Steam logo on the screen and the device forever stuck in that state

The only workaround is to shut it down from the button and let it start again. The 3.5.18 didn't help with this issue if it was a matter of having an OS partition with corrupted data. The client updates also didn't help in case the Steam client installation was somehow in a bad state.

 The "verifying ..." message and progress bar appear on screen when the Steam client manages to load properly.

**Comment by kisak-valve** [comment]
Hello @unclejack, I've transferred this issue report to the steam-for-linux issue tracker because it reads more like an issue with the Steam client instead of SteamOS as a platform.

If a Steam developer evaluates this and determines it makes more sense to be treated as an issue with SteamOS, then they can give me a nudge to transfer this issue report back.

**Comment by unclejack** [comment]
I've filed it as a SteamOS issue because the default UI of the OS doesn't always load. Thanks for letting me know.

**Comment by unclejack** [comment]
This has been fixed as mentioned here: https://github.com/ValveSoftware/SteamOS/issues/1514#issuecomment-2133885864
