### ISSUE TITLE
Notifications appear on the top left instead of bottom right, after some recent update

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#10818]
Has been happening for around two weeks

Ubuntu 22.04
Steam Version:  1713825714

**Comment by hateball** [comment]
Same issue here. It does not always happen, but quite often. Especially if I let the monitor blank and then wake it.
Using steam family beta on Kubuntu 24.04, Wayland.

**Comment by Dwarsen** [comment]
I have the same issue, however I'm running Manjaro Linux on X11.

**Comment by echaskaris** [comment]
Seems to be fixed for some time now
