### ISSUE TITLE
Focus stolen by Steam notifications while typing

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/steam-for-linux#10827]
#### Your system information

* Steam client version (build number or date): 1713825714
* Distribution (e.g. Ubuntu): Gentoo Linux 23.0
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15134866/steam-logs.tar.gz)
* GPU: NVIDIA RTX 3080 Ti

#### Please describe your issue in as much detail as possible:

I'm running the Steam client in the background because it autostarts during desktop login. While Steam is running in the background and you're not actively running a game but instead type in other windows, Steam's desktop notifications steal focus: A notification displays, everything is fine, then the notification fades out, focus is stolen and I start typing in another window.

Maybe worth noting:

- running KDE Plasma 5.27.11 (X11 session)
- three monitors: left (portrait mode), center (4k landscape), right (FHD landscape)
- the Steam client is opened on the center monitor
- Steam notifications appear on the right monitor
- my center monitor is my main working (and gaming) monitor

#### Steps for reproducing this issue:

1. Open Steam on KDE Plasma 5.27.11
2. Work in another window in foreground, e.g., type some text
3. Wait for a Steam notification and see it steal window focus when it disappears

**Comment by kisak-valve** [comment]
Hello @kakra, this is the same issue as #10758. Closing as a duplicate.
