### ISSUE TITLE
Request ability to select which controller type icons appear ingame from steam input (Playstation or Xbox)

### ISSUE THREAD

**Issue by Sevenseraphim** [ValveSoftware/steam-for-linux#10825]
* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia

Steam input should have the ability to select which controller icons you want to appear in games if supported (i.e. if the game has the ability to display those icons whether for Playstation or Xbox)

For example I have a PS3 controller which is not natively supported by a game but PS4 and Xbox controllers _are_ natively supported. Using steam input I am able to use the PS3 controller to normally play the game but Xbox icons appear ingame instead of Playstation Icons and there is no way to change this from steam input.

A lot of people have had the same trouble with this and have made posts in many forums about it. Please give us an option to specify to the game which controller button layout appears for ingame prompts.

**Comment by kisak-valve** [comment]
Hello @Sevenseraphim, this request is already being tracked at #8746. Closing in favor of the older issue report.
