### ISSUE TITLE
Using chords with the QAM °°° button causes non-steam games to switch to the desktop config

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10834]
#### Your system information

* Steam client version:  1714160074
* SteamOS version:  3.5.19
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/_7q7VCEgV24 (video is old and might not match 1:1 with current behavior)
Using chords through the QAM button causes non-steam game binding to be overridden with the desktop config until you press the QAM button again. Using chords through the STEAM button does not have this effect
This might or might not be related to bug https://github.com/ValveSoftware/steam-for-linux/issues/10551
I reported this previously on the Steam Forums. https://steamcommunity.com/app/1675200/discussions/1/3642874410681493222/

#### Steps for reproducing this issue:

1. Open a non-Steam game
2. Use °°°+left joystick to adjust the bringhtness
3. Attempt use the controls

#### Result:
The game config got overridden with your desktop config

#### Expected:
The game config should stay on after using chord

**Comment by safijari** [comment]
I have the exact same issue. It used to happen a long time ago with all applications and then got fixed. Recently it started happening again but only with non-steam apps.

**Comment by Managor** [comment]
This seems to have been fixed. @safijari, can you confirm?

**Comment by kisak-valve** [comment]
Closing per the last comment.
