### ISSUE TITLE
Turn Camera X° binding does not calibrate correctly if Flick Stick is not bound to any input source

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#10845]
#### Your system information

* Steam client version:  1714520927
* SteamOS version:  3.5.19
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/_8R8QnmwMaM
Unless I have Flick Stick bound to a trackpad, joystick or dpad, the "Turn Camera X°" binding does not respect the set "Flick Stick ° to Mouse Pixels" setting. This is somewhat odd since re-setting Flick Stick to any input method, it remembers the value I calibrated it with so that value must be stored somewhere. The same is probably true for "Reset Camera Horizon" and "Turn Camera to Face Diretion" binding but I haven't tested.
Since the calibration affects multiple bindings now (with Gyro to Mouse on top of the ones previously mentioned), I think the best course of action is to move the calibration setting to somewhere like "Global Set Options" in the Action Sets menu.

#### Steps for reproducing this issue:

1. Calibrate Flick Stick correctly
2. Bind "Turn Camera 360°" to a button
3. Unbind Flick Stick from an input source
4. Use "Turn Camera 360°" in game

#### Result:
The binding acts as as if the calibration was never made

#### Expected:
The binding should pull the calibration values from where they are stored even if they are not bound.

**Comment by HilariousCow** [comment]
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4216008828237777536

Fixed

**Comment by Managor** [comment]
Can confirm it is now fixed

**Comment by kisak-valve** [comment]
Closing as fixed in the [2024-05-07](https://store.steampowered.com/news/app/1675200/view/4202497395530274132) Steam Deck client update.
