### ISSUE TITLE
The On Screen Keyboard is no longer opening using the steam controller on the May 3, 2024 beta

### ISSUE THREAD

**Issue by Xenophobe-01** [ValveSoftware/steam-for-linux#10849]
#### Your system information

* Steam client version (build number or date): 
     Steam Beta Branch:  Steam Beta Update
     Steam Version:  1714778942
     Steam Client Build Date:  Fri, May 3 7:11 PM UTC -05:00
     Steam Web Build Date:  Fri, May 3 5:07 PM UTC -05:00
     Steam API Version:  SteamClient021
* Distribution (e.g. Ubuntu): Linux Mint 21.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15205994/steam-logs.tar.gz)
* GPU: AMD RX 6950 XT

#### Please describe your issue in as much detail as possible:
The May 3, 2024 beta update has broken the onscreen keyboard completely for me. The onscreen keyboard is not opening when I click the left stick on the steam controller. I tried restarting steam and rebooting the pc and the OSK still doesn't open for me.  It was working fine prior to the update (except for the initial location bug).

#### Steps for reproducing this issue:

1. Update to May 3, 2024 beta.
2. Go to forums and click in a reply box.
3. Click left stick on steam controller.
4. See no On Screen Keyboard pop up.

**Comment by Xenophobe-01** [comment]
I switched to the stable client and the onscreen keyboard comes up, switched back to the beta client to see if reinstalling the beta would fix it and it still doesn't work. Sticking with the stable client for now.

**Comment by TTimo** [comment]
Hello,

Thank you for your report. We cannot reproduce. Using the latest Steam beta client (1714854927), steam controller in desktop mode and following your reproduction steps, pressing the left stick in a discussion reply correctly brings up the OSK:

![045239edae213649d2f542ef595db886](https://github.com/ValveSoftware/steam-for-linux/assets/6637/ad84e197-1733-4344-81a2-ba1a387eb1a6)

**Comment by Xenophobe-01** [comment]
Okay, I just opted back into the beta, version 1714854927, and now it's working ... aside from the initial location bug.  The beta build I had the issue on was Steam Version: 1714778942 as in the original post. Thanks for the update. This can be closed as resolved.
