### ISSUE TITLE
Game: Elder Ring can't start from last mounth,maybe due to steam update?

### ISSUE THREAD

**Issue by plainee** [ValveSoftware/steam-for-linux#10840]
#### Your system information
Elder ring can't start from last mounth,maybe steam update?

* Steam client version (build number or date):  latest
* Distribution (e.g. Ubuntu):  Arch Linux (linux-lts)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, everyday
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/15188435/logs.zip)

* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Elder ring can't start from last mounth,maybe steam update?
It's os mounths before. I guess maybe it's due to steam or arch linux updates.

#### Steps for reproducing this issue:

1. start steam
2. start Elder Ring
3.

**Comment by kisak-valve** [comment]
Hello @plainee, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game. Please use https://github.com/ValveSoftware/Proton/issues/5613 to discuss how this game behaves.

Looking at some recent discussion, if 32 bit Vulkan is broken on your system, that can lead to EAC and the game falling over at start.

Closing in favor of the Proton compatibility report.
