### ISSUE TITLE
Proton 9.0 No Longer Available to Install

### ISSUE THREAD

**Issue by ManedCalico** [ValveSoftware/steam-for-linux#10846]
Hello,

A few hours ago, every game started hanging on a "Downloading Content" screen without ever attempting to launch:

![steamuserimages-a akamaihd](https://github.com/ValveSoftware/Proton/assets/115047089/1d73427b-fd42-4641-b537-fe7f1c5ff62f)

After some investigating, I discovered that Proton 9.0 is no longer installed on my Steam Deck. Attempting to install it again does nothing. Forcing games to use another version of Proton fixes the issue.

It appears as if Proton 9.0 is not longer available to install:

![steamuserimages-a akamaihd](https://github.com/ValveSoftware/Proton/assets/115047089/a4334e62-da27-404d-8247-3715192e020f)

I found that I'm not alone in this having happened, so I wanted to report it here in the hopes that this could be resolved quickly.

Thanks!

**Comment by kisak-valve** [comment]
Hello @ManedCalico, the download and management of compatibility tools including Proton is handled by the Steam client, not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker for a Steam dev to ponder.

**Comment by TTimo** [comment]
Hello,

There were some configuration changes made roughly 2 hours ago (Fri, 03 May 2024 19:00:00 GMT), please let us know if you are still having an issue with Proton 9 not downloading.

**Comment by mercuriete** [comment]
It happen to me as well with Steam deck stable.
All unsupported games that default to latest protón stop opening and hangs on download content as OP said.
So I can't play almost anything from my library (games that defaults to 9.0-1)

On pc/Linux I was able to install It.

**Comment by TTimo** [comment]
@mercuriete right now still, after a restart of your deck / steam client, or that was still happening > 2 hours ago?

I assume if you search in your library for 'Proton 9' and try to install it, that will fail?

**Comment by mercuriete** [comment]
Yes, right now.
After reboot, library -> proton -> protón 9
No fail nor error, just a silenced error.
Maybe a problem with your CDN?
I am using Spain Madrid servers.

**Comment by TTimo** [comment]
Can you check this: open `~/.steam/steam/userdata/<steamid>/config/compat.vdf` (where <steamid> is your id) and look for an entry with "2805730". If that entry exists, delete it and try again?

**Comment by mercuriete** [comment]
Well, I didn't read you right and I deleted the whole file.
But I could download It.
Now I can play my games again.

**Comment by TTimo** [comment]
Alright, thanks for testing this out!

**Comment by mercuriete** [comment]
Thanks you for working late.
Remember...

https://shouldideploy.today/
Don't deploy on friday LOL!

I Hope you are well and please rest.
Here in Europe is 22:34 WEST.

**Comment by X6205** [comment]
On my end it is behaving the same. If i force on game version 9.0-1, it will download beta with old "soldier" runtime 2.0. Unless this is expected or forced per game basis, i would expect to download new runtime 3.0 "sniper" with final 9.0-1. 

But game is working with experimental so the result is what matters :)
![jedi_survivor](https://github.com/ValveSoftware/steam-for-linux/assets/14248415/687ed662-7656-4364-9a2f-5478c8283c2b)

**Comment by TTimo** [comment]
@X6205 you shouldn't attempt to force a given runtime on compat tools, they are meant for one specific runtime that is hardcoded in their configuration.

In any case, deleting / removing compat.vdf should work for you. Or switching to the latest Steam beta client which has a fix for this now.

**Comment by ManedCalico** [comment]
I'm able to run games again with the default Proton, but the behavior of the Proton 9.0 library item hasn't changed. It still says "Available on Steam" and selecting "Install" doesn't do anything.

That said, it's a non-issue now.

**Comment by LiamDawe** [comment]
There was a [Steam Beta](https://store.steampowered.com/news/app/1675200/view/4199120329637230599) that should solve this?

**Comment by TTimo** [comment]
@LiamDawe I expect these folks aren't using the beta client. We also made Proton 8 the default again over the weekend to avoid further issues.

**Comment by TTimo** [comment]
Proton 9 was set as the default Proton on Deck roughly 24 hours ago (May 9th, 21:00 GMT). We haven't observed new reports or issues with the switch, closing this.
