### ISSUE TITLE
Controller Buttons Double Input/Wrong Input Bug

### ISSUE THREAD

**Issue by Cederick** [ValveSoftware/steam-for-linux#10848]
#### Your system information

* Steam client version: 1714520927
* SteamOS version: 3.7 Build 20240503.1000
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
My inputs are counted as two inputs every time I press a button on an external controller (Xbox Series X and Nintendo Switch Pro Controller). It even happens when trying to input my PIN. The XYAB and the directional buttons have these issues in the SteamOS UI but everything looks fine on the input test screen. Even the reset device inputs option did not help.This issue prevents me from changing settings for games or even being able to do basic navigation. And the LB and RB buttons are seen as UP (LB) and DOWN (RB) which just adds to the frustration. So I currently have to use Hotkey + Right Stick and RT to navigate the menus most of the time.

#### Steps for reproducing this issue:

1. Turn on device and dock it to the official dock
2. Wait for the login screen
3. Use any external controller

**Comment by Plagman** [comment]
https://github.com/ValveSoftware/SteamOS/issues/1500
