### ISSUE TITLE
[bug] Steam doesn't focus on Farcry 5 after starting in big picture mode

### ISSUE THREAD

**Issue by light-and-ray** [ValveSoftware/steam-for-linux#10852]
I'm streaming the game from PC (Manjaro Linux, KDE) on Android tablet via steam link. Only in this game I have to press alt+tab on keyboard after the start, it's annoying. I guess steam mixes up the dummy small window with farcry logo and the main window. After this window is closed, farcry's window is under big empty steam window

**Comment by kisak-valve** [comment]
Hello @light-and-ray, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2356#issuecomment-2094344410.
