### ISSUE TITLE
Can't find 'steam-runtime-check-requirements', continuing anyway

### ISSUE THREAD

**Issue by Hellscaped** [ValveSoftware/steam-for-linux#10862]
#### Your system information

* Steam client version (build number or date): Unknown (Cannot --version or load into steamui)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: 
* `steam.sh[3212]: Running Steam on arch rolling 64-bit
steam.sh[3212]: STEAM_RUNTIME is enabled automatically
steam.sh[3212]: Error: You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0
libvdpau.so.1
steam.sh[3212]: Can't find 'steam-runtime-check-requirements', continuing anyway`
* GPU: Nvidia/**Intel**/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
It should have loaded up the steamui, but instead it showed this error.

I **DID** try to install the libraries in question, but they were already installed.

#### Steps for reproducing this issue:

1. Update your Arch Linux system
2. Run Steam
3. Error

**Comment by Hellscaped** [comment]
I managed to fix the issue myself: I had to install separate lib32- versions of those libs. Dunno why I never had that issue before. Having a separate issue now, it doesn't launch steam at all.
Steam does not produce logs,
but this was in stdout:
```
steam.sh[4561]: Running Steam on arch rolling 64-bit
steam.sh[4561]: STEAM_RUNTIME is enabled automatically
steam.sh[4561]: Can't find 'steam-runtime-check-requirements', continuing anyway
```

**Comment by smcv** [comment]
> `Error: You are missing the following 32-bit libraries, and Steam may not run: libpipewire-0.3.so.0 libvdpau.so.1`

Please ask the maintainers of https://archlinux.org/packages/multilib/x86_64/steam/ to add dependencies on the lib32- versions of those libraries.

> `steam.sh[4561]: Can't find 'steam-runtime-check-requirements', continuing anyway`

Did you already have Steam installed and working, or is this a new installation?

Seeing this message on first-run is harmless. A future Steam release might add it to the bootstrapper to silence this warning.

Seeing this in an existing installation is unexpected.

**Comment by Hellscaped** [comment]
> > `Error: You are missing the following 32-bit libraries, and Steam may not run: libpipewire-0.3.so.0 libvdpau.so.1`
> 
> Please ask the maintainers of https://archlinux.org/packages/multilib/x86_64/steam/ to add dependencies on the lib32- versions of those libraries.
> 
> > `steam.sh[4561]: Can't find 'steam-runtime-check-requirements', continuing anyway`
> 
> Did you already have Steam installed and working, or is this a new installation?
> 
> Seeing this message on first-run is harmless. A future Steam release might add it to the bootstrapper to silence this warning.
> 
> Seeing this in an existing installation is unexpected.

Existing installation

**Comment by Hellscaped** [comment]
Managed to fix it by backing up my .local/share/Steam directory and reinstalling steam. Dunno why it did that. 
Closing as I have everything now
