### ISSUE TITLE
Non-Steam games not showing in searchbar in Game Mode after May 7th 2024 update

### ISSUE THREAD

**Issue by midnightcatwalk** [ValveSoftware/steam-for-linux#10864]
#### Your system information

* Steam client version: May 7th update
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
The searchbar at the top of the game mode screen no longer shows non-Steam games I have installed when I type in their names, and is only showing Steam games. Previously, it would search for any game, Steam or non-Steam.

#### Steps for reproducing this issue:
Apply May 7th update and search for a non-Steam game

**Comment by kisak-valve** [comment]
Hello @midnightcatwalk, you've described an issue with the Steam client instead of SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by livejamie** [comment]
Found two more mentions of this issue:

- https://www.reddit.com/r/SteamDeck/comments/1cmjboo/the_new_update_killed_my_deck/l3s3liy/
- https://steamcommunity.com/app/1675200/eventcomments/4353369145003418738?snr=1_2108_9__2107#c4357872852116692179

I can also report it's happening to me as well.

**Comment by lostgoat** [comment]
Should be fixed in today's steam client update.

**Comment by poudink** [comment]
can confirm it's been fixed on my end

**Comment by Thornskade** [comment]
It is not fixed on my end

**Comment by midnightcatwalk** [comment]
It is fixed here.

**Comment by Thornskade** [comment]
All of my non-Steam games have disappeared since that update. Only one shows up which I had added after the update, not realizing others were missing

**Comment by kisak-valve** [comment]
Closing per "Fixed non-steam games not showing in search results." the the [2024-05-16](https://store.steampowered.com/news/app/1675200/view/4183358999817275190) Steam Deck client update.
