### ISSUE TITLE
Launching a steam game kills all sounds

### ISSUE THREAD

**Issue by arnaudgolfouse** [ValveSoftware/steam-for-linux#10878]
#### Your system information

* Steam client version (build number or date): 1714854927
* Distribution: Fedora 40
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15282618/steam-logs.tar.gz)

* GPU: NVIDIA RTX A1000 6GB Laptop GPU, driver version 550.78

#### Please describe your issue in as much detail as possible:

When starting any steam game, no sounds can be heard, from the game or any other application.

The sound will periodically restart (for every application), and then goes down again.

- Games tried : Elden ring, Lies of P, Factorio (the latter is running native, so I suspect this is not related to proton).
- My system uses wireplumber version `0.5.2` : running `systemctl --user restart wireplumber` brings the sound back for a few seconds.
- output of `wpctl status` when running factorio: <details>
  <summary>
  </summary>

  ```
  PipeWire 'pipewire-0' [1.0.6, arnaud@arnaud-precision-5480, cookie:3474079129]
   └─ Clients:
          31. gnome-shell                         [1.0.6, arnaud@arnaud-precision-5480, pid:59086]
          40. WirePlumber [export]                [1.0.6, arnaud@arnaud-precision-5480, pid:80382]
          45. Steam Voice Settings                [1.0.6, arnaud@arnaud-precision-5480, pid:80735]
          46. Factorio 1.1.107                    [1.0.6, arnaud@arnaud-precision-5480, pid:81198]
          50. uresourced                          [1.0.6, arnaud@arnaud-precision-5480, pid:59010]
          52. WirePlumber                         [1.0.6, arnaud@arnaud-precision-5480, pid:80382]
          55. wpctl                               [1.0.6, arnaud@arnaud-precision-5480, pid:81469]
          58. Steam                               [1.0.6, arnaud@arnaud-precision-5480, pid:80735]
          62. Factorio 1.1.107                    [1.0.6, arnaud@arnaud-precision-5480, pid:81198]
          79. GNOME Shell Volume Control          [1.0.6, arnaud@arnaud-precision-5480, pid:59086]
          80. pipewire                            [1.0.6, arnaud@arnaud-precision-5480, pid:3615]
          82. GNOME Volume Control Media Keys     [1.0.6, arnaud@arnaud-precision-5480, pid:59307]
          83. xdg-desktop-portal                  [1.0.6, arnaud@arnaud-precision-5480, pid:59877]
  
  Audio
   ├─ Devices:
   │      78. Raptor Lake-P/U/H cAVS              [alsa]
   │  
   ├─ Sinks:
   │      49. Raptor Lake-P/U/H cAVS Speaker      [vol: 0.42]
   │      53. Raptor Lake-P/U/H cAVS HDMI / DisplayPort 2 Output [vol: 1.00]
   │      72. Raptor Lake-P/U/H cAVS HDMI / DisplayPort 3 Output [vol: 1.00]
   │      75. Raptor Lake-P/U/H cAVS HDMI / DisplayPort 1 Output [vol: 1.00]
   │  *  185. Raptor Lake-P/U/H cAVS Headphones   [vol: 0.27]
   │  
   ├─ Sources:
   │  *   56. Raptor Lake-P/U/H cAVS SoundWire microphones [vol: 0.24 MUTED]
   │      77. Raptor Lake-P/U/H cAVS Headset Microphone [vol: 1.00]
   │  
   ├─ Filters:
   │  
   └─ Streams:
          41. Factorio 1.1.107                                            
               43. output_FR       > Headphones:playback_FR	[active]
               51. output_FL       > Headphones:playback_FL	[active]
  
  Video
   ├─ Devices:
   │  
   ├─ Sinks:
   │  
   ├─ Sources:
   │  
   ├─ Filters:
   │  
   └─ Streams:
  
  Settings
   └─ Default Configured Devices:
           0. Audio/Sink    alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire__sink
           1. Audio/Source  alsa_input.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_1__source
  ```
  </details>
- I tried both the RPM and flatpak versions of steam, the issue persist.
- It does not seem like any other applications does this on my system.

#### Steps for reproducing this issue:

1. Open steam
3. Launch any game, native or through proton
4. All sound stops in every application 😢

**Comment by kisak-valve** [comment]
Hello @arnaudgolfouse, this reads like a pipewire issue that should be mentioned to the audio devs and/or your distro's package maintainer for pipewire.

**Comment by arnaudgolfouse** [comment]
Ah indeed, this prompted me to change pipewire to pulseaudio (which apparently I did not tried before), and everything worked fine. I don't really know what went wrong, but at least that fixed it, so thanks ! I guess this can be closed.
(For the record, on fedora the command to replace pipewire with pulseaudio was `sudo dnf install pulseaudio --allowerasing`)
