### ISSUE TITLE
Cannot  download steam  for  Linux.I got  a 403 error.

### ISSUE THREAD

**Issue by Huayuluoshi** [ValveSoftware/steam-for-linux#10874]
#### Your system information

* Steam client version (build number or date): Haven't install steam yet.
* Distribution :Ubuntu-2404
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:No logs.This certainly the website issue.
* GPU: Intel

#### Please describe your issue in as much detail as possible:
Cannot download steam for linux.When I click [this link](https://media.st.dl.eccdnx.com/client/installer/steam.deb)on [here](https://store.steampowered.com/about/),I got a 403.
![截图 2024-05-10 15-42-09](https://github.com/ValveSoftware/steam-for-linux/assets/117527694/f42c5923-4d31-4155-9e09-109386f34eee)

More info:
OS:Ubuntu 2404
Browser:Firefox(snap,125.0.3,64bit)
#### Steps for reproducing this issue:
1. Visit https://store.steampowered.com/about/
2. Click Install steam
3.  Now I get a 403 error

**Comment by major-gnuisance** [comment]
Anything special about your Internet access?
Using a VPN or something?
Is it really Ubuntu and not a derivative like Ubuntu Kylin?

I get the impression that you're trying to do that from mainland China.

That domain name is registered to Alibaba, not Cloudflare as the error page suggests, and it resolves to IP addresses belonging to "CHINANET Shanghai province network"

When I download Steam I get this URL: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb

I think it's safe to assume that this issue is related to Internet censorship in China.
Your system may be compromised and facilitating state-sponsored man-in-the-middle attacks, which have lead up to this issue.

**Comment by Huayuluoshi** [comment]
******This comment has  so  many  words,but  English  isn't  my  native  language,so I am  sorry for  some  grammar faults.
1.Anything special about your Internet access?
Using a VPN or something?
No,I haven't using VPN  that  time.It is  only  a  normally WIFI.
2.Is it really Ubuntu and not a derivative like Ubuntu Kylin?
Yes ,it  is  Ubuntu,not  a derivative.
3.I get the impression that you're trying to do that from mainland China.
Yes ,you  are  right,I lived  in mainland  China now.Steam  has China  version,but  has no Linux 
version .
4.That domain name is registered to Alibaba, not Cloudflare as the error page suggests, and it resolves to IP addresses belonging to "CHINANET Shanghai province network"
When I download Steam I get this URL: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
I think it's safe to assume that this issue is related to Internet censorship in China.
Oh,it  seems so  strange...The  URL was  copied  form  the official  website,So I am  sure it isn't related Internet censorship.(What's more,If a website was  blocked  because of Internet censorship,it  should be   a timeout issue instead of  403 forbidden issue.)But,the launcher  app in this  github repository's reademe.md  can  download correctly.
5.Your system may be compromised and facilitating state-sponsored man-in-the-middle attacks, which have lead up to this issue.
It   may  be,although I haven't found  something about  this.Thank you for  your  remind!


******Something I want  to  say
Err...I test just  now  with  my  smart phone and  it  could  be  download correctly...I don't know how  this  happend...(But am sure that time I cannot  download it  using  my smart phone or my computer.)So,this  issue should be  closed. :)

Again,thanks for  your  reply!
