### ISSUE TITLE
Apex Legends season 21 - 5.1 surround sound silent directly ahead

### ISSUE THREAD

**Issue by MkThUnderwd** [ValveSoftware/steam-for-linux#10889]
#### Your system information

* Steam client version (build number or date): 

> Steam Beta Branch:  Stable Client
> Steam Version:  1714854927
> Steam Client Build Date:  Fri, May 3 18:11 UTC -06:00
> Steam Web Build Date:  Sat, May 4 15:14 UTC -06:00
> Steam API Version:  SteamClient021

* Distribution (e.g. Ubuntu): **Xubuntu 24.04.4 LTS**
* Opted into Steam client beta?: [**No**]
* Have you checked for system updates?: [**Yes**]
* Steam Logs: **should be irrelevant**
* GPU: **AMD**

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

> Stereo mode sounds normal. 5.1 surround sound before season 21 sounds normal. 5.1 surround sound AFTER season 21 launch is silent if the audio source is DIRECTLY center of screen horizontally. See any of the videos at the bottom.

#### Steps for reproducing this issue:

> 1. Use PulseAudio **or** Pipewire + Pipewire-Pulse + Wireplumber audio server in 5.1 surround mode.
> 2. Play Apex Legends season 21 in Steam using Proton Hotfix.
> 3. Make sure sounds device setting in Apex is in default or 5.1 surround sound mode.
> 4. Go to the firing range and use a Wattson Pylon or similar sound play entity and place it down.
> 5. Stand far enough away so that it can be heard but not overwhelm all speakers.
> 6. turn player camera left and right across the pylon 45 to 90 degrees.
> 7. audio should NOT be silent when looking directly at the sound source, but was.

See any of these 1 to 2 minute capture demos:
[Fuse and grenades (pipewire): https://youtu.be/VjY_dzEHB5g](https://youtu.be/VjY_dzEHB5g)
[Wattson's pylon 1 (pipewire): https://youtu.be/ZLjU1ccV6-E](https://youtu.be/ZLjU1ccV6-E)
[Wattson's pylon 2 (pulseaudio): https://youtu.be/vR1jIa0d6N4](https://youtu.be/vR1jIa0d6N4)

**Comment by kisak-valve** [comment]
Hello @MkThUnderwd, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-2109047592.
