### ISSUE TITLE
4:3 screen ratio not possible with Debian based Linux (PARDUS)

### ISSUE THREAD

**Issue by byzoo101** [ValveSoftware/steam-for-linux#10883]
#### Your system information

* Steam client version (build number or date):  1714854927
* Distribution (e.g. Ubuntu):  Pardus 23.1 debian based (kernel 6.6.13+bpo-amd64)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: NVIDIA GeForce GTX 770

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. When I change to 4:3 in video settings I get a black screen. I would expect it to change to 4:3.

Therefore, I can no longer use the 4:3 screen ratio because it will lead to a black screen. Instead, I must use 16:9.
Could you please advice on how to fix this on his side or if you are aware and working on an issue related to that problem?

I would really like to play 4:3 again.

**Comment by kisak-valve** [comment]
Hello @byzoo101, sorry, but this issue report isn't coherent in the context of the Steam client for Linux.

**Comment by kisak-valve** [comment]
You've described a rendering issue related to the aspect ratio used with some unknown game. The Steam client doesn't control this or have similar settings.
