### ISSUE TITLE
Disk write error for Steam Workshop updates

### ISSUE THREAD

**Issue by Tiagoquix** [ValveSoftware/steam-for-linux#10892]
#### Your system information

* Steam client version (build number or date): Stable Client, 1715635533
* Distribution (e.g. Ubuntu): Fedora Linux 40 KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15313000/steam-logs.tar.gz)
* GPU: NVIDIA GeForce GTX 1050 Ti

#### Please describe your issue in as much detail as possible:

When I open the Steam Client and then click to play Team Fortress 2 (or any other game possibly, but I only saw this occur with TF2) and it has to download an update for a Workshop map that I'm not subscribed, but that I have played on it (because of servers hosting Workshop maps with `tf_workshop_map_sync WORKSHOP_MAP_ID`), the game gets stuck at "`Downloading Workshop (0%)`" until I manually go to the Steam Client "Downloads" section, see that the game has "`Disk Write Error`" and manually press the "try again" button to make the game launch properly.

The error then goes away and everything works as expected, but it always happens when something from the Steam Workshop has to be updated and then manual intervention is required.

My Steam Library files are at `/mnt/HDD/SteamLibrary` (then `/steamapps/workshop`).

To be clear, the files are saved correctly after the manual intervention.

#### Steps for reproducing this issue:

Explained above.

**Comment by jorp** [comment]
Hello, are you using BTRFS? Can you include an output of `dmesg` shortly after this happens?

**Comment by dsalt** [comment]
I've just looked at the log text here (as it's another instance of `DISK WRITE ERROR` lacking context; see #7958) and the relevant parts look suspiciously similar to #10906.

**Comment by jorp** [comment]
> Yes; I'm using BTRFS. If the error happens again, I'll post an output of `dmesg`.

I would recommend testing your RAM as well

**Comment by dsalt** [comment]
So no hardware problems and no storage failures; as expected, given what I've seen here. As mentioned in another bug report, Steam **really** needs to report and log at least `strerror(errno)` (or equivalent; ideally, also `errno` to avoid any need for translation).

**Comment by jorp** [comment]
> @jorp 
> 
> 
> 
> [Steam Client Update - 18 June 2024](https://store.steampowered.com/news/app/593110/view/6087258371787336413?l=english)
> 
> 
> 
> > Fixed disk write failures reported in the logs when starting games with the shader manager disabled.
> 
> 

This unfortunately didn't do it for me. Did you happen to see resolution? @Tiagoquix

**Comment by jorp** [comment]
> Hey @jorp, I have not received any disk-related errors since that update. I believe it was fixed for me.
> 
> IDK if this matters, but I have Steam installed in my SSD and games in my HDD (Steam Workshop files are also in the HDD).

Thanks for sharing that. I'm glad everything is working out for you.
