### ISSUE TITLE
Steam Fails launches Login screen, but UI fails when launched through wofi

### ISSUE THREAD

**Issue by JacobJanzen** [ValveSoftware/steam-for-linux#10893]
#### Your system information

* Steam client version (build number or date): 1715635533
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15313744/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Expected: steam launches without issue when launched by `wofi`.

What happens: Selecting Steam from `wofi` application launcher opens the login screen and steam enters the system tray, but after login, the UI is completely inaccessible. There are two workarounds to this issue:
1. run `steam` from the command line
2. remove `PrefersNonDefaultGPU=true` from the steam.desktop file.

The second workaround is a significantly better long-term issue, however this is a non-obvious fix. Other people have run into this same issue as seen with [this](https://www.reddit.com/r/linux_gaming/comments/1casb3t/cant_launch_steam_with_wofi/) Reddit post and [this](https://github.com/NixOS/nixpkgs/issues/246007) issue in NixPkgs. I strongly suggest adopting the changes suggested in https://github.com/ValveSoftware/steam-for-linux/issues/9940 as it seems that that option is inherently broken on many systems.

#### Steps for reproducing this issue:

1. Use `sway` as your window manager and set wofi to be the menu application with
```sh
# other irrelevant configuration
set $menu wofi --show drun
bindsym $mod+d exec $menu
# other irrelevant configuration
```
4. Press `mod+d` to open wofi
5. Type steam to filter to the Steam desktop entry
6. Press enter to open the Steam desktop entry

**Comment by kisak-valve** [comment]
Hello @JacobJanzen, this issue is already being tracked at #9383. Closing as a duplicate.
