### ISSUE TITLE
[Feature Request] Option to disable game automatic updates

### ISSUE THREAD

**Issue by Kaoticz** [ValveSoftware/steam-for-linux#10911]
### System information (although this is all completely irrelevant for this issue in question)

* Steam client version (build number or date): 1715891371
* Distribution: Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: irrelevant
* GPU: Nvidia

### Description
Currently, there are 3 options for handling automatic game updates:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/1812311/e057f93e-9b60-4d09-93ec-45deb37aace3)

A **forth option** should be added to **completely disable automatic updates**.
Which means Steam would not look for updates, nor install them, for a particular game in the user's library.

### Motivation

**Everything below applies to single-player games only.**

- Compatibility
    - Some games have support for mods. Sometimes, game developers will push game updates that completely break compatibility with older mods. By manually disabling automatic updates, users can ensure that their current playthrough will not be affected by any breakage, giving them time to finish their playthrough.
    - For some games, the same applies to save files, which is even worse. Imagine losing your whole save, hours of progress, because of a game update. It's very disruptive and would be enough to make many people outright quit the game for good - or worse, **ask for refunds**!
- Waste of Write Cycles
    - SSDs are now commonplace in many gamers' computers. The lifespan of an SSD is directly tied to how many write operations are performed on its storage cells. In order to extend the lifespan of the SSD as much as possible, write operations should only be performed when data that is actually important needs to be persisted. Some games tend to have recurrent daily updates that don't impact the game experience at all (for example, an in-game microtransaction store that the user has never used, nor intends ever to). Giving users the option to not have Steam hammer their hardware with unnecessary write cycles would be beneficial to the health of their hardware.

**Comment by kisak-valve** [comment]
Hello @Kaoticz, this was previously requested at #8711 and the response at https://github.com/ValveSoftware/steam-for-linux/issues/8711#issuecomment-1197050595 is equally valid today as it was back then.

**Comment by Kaoticz** [comment]
Hello @kisak-valve. Thanks for responding, I was not aware of #8711 nor that Valve considered this matter to be an anti-feature.
I understand that game developers, much like gamers, are also users to Valve.

But when the interests of different user bases clash, the fairest compromise usually favors the side with the least leverage. Considering Valve's pro-consumer track record, it is somewhat surprising that Valve has chosen to not allow users to opt out of automatic updates.

I also can't help but feel disappointed by the suggestion that, if users want to avoid automatic updates, they should not use Steam at all. Since this decision was made internally long ago, there is little I can do but voice my discontent.

Either way, thanks for your response and your time.
