### ISSUE TITLE
Cloud saves don't work for Hades

### ISSUE THREAD

**Issue by ASHGOLDOFFICIAL** [ValveSoftware/steam-for-linux#10910]
#### Your system information

* Steam client version (build number or date): 1716072097
* Distribution (e.g. Ubuntu): NixOS unstable
* Opted into Steam client beta?: Steam Families Beta
* Have you checked for system updates?: Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Cloud saves for Hades do not work. It always says "Up to date" but storage is empty. I discovered it after reinstall.

#### Steps for reproducing this issue:

1. Open Hades.
2. Create save.
3. Check if save is placed into Steam Cloud.

**Comment by kisak-valve** [comment]
Hello @ASHGOLDOFFICIAL, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3312#issuecomment-2119261835.
