### ISSUE TITLE
Valve Anti-Cheat challenge timed out

### ISSUE THREAD

**Issue by g572staem** [ValveSoftware/steam-for-linux#10920]
**Valve Anti-Cheat challenge timed out**

Fix your damned software...

https://steamcommunity.com/app/730/discussions/0/4335356121962990706/

**Comment by kisak-valve** [comment]
Hello @g572staem, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3422.

Closing as a duplicate.

**Comment by g572staem** [comment]
@kisak-valve This is a new problem since the last update, I have not had this issue prior.  I play this game dozens of hours a week (I don't watch TV).  It is not a duplicate, it it was I would have been affected over the same time span.

**Comment by g572staem** [comment]
Ubuntu 20.04 LTS, Nvidia.  OS does not have boffin nonsense going on, very vanilla install.

**Comment by g572staem** [comment]
@kisak-valve **Not a duplicate**.

My steam is not installed by flatpak (unless Valve have a wrapped version in their installer?)

`$ dpkg -l steam:i386
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version             Architecture Description
+++-==============-===================-============-==============================================
ii  steam:i386     1:1.0.0.61-2ubuntu3 i386         Valve's Steam digital software delivery system`

@kisak-valve **Not a duplicate.**

How could I know this?  It affects windows too, see linked discussion in first post.

**Comment by kisak-valve** [comment]
For transparency, you've chosen to misfile an Anti-cheat and/or game issue on the Steam client issue tracker with a link to a forum post describing similar symptoms to the issue report I've linked. By the nature of anti-cheat software, we don't really get much insight into what's happening there.

I've chosen to point to a pre-existing issue report instead of letting it sit in limbo. Regardless, the steam-for-linux issue tracker isn't the right place for VAC or Counter-Strike 2 issues.

**Comment by g572staem** [comment]
```
update 2024-05-23 (big update) arrive yesterday for me.
  Weird VAC issue started, that I posted about above.
update 2024-05-24 (smaller update) arrived a few hours ago.
  Weird VAC issue went away (so far so good).
```

The symptoms are related, yes.  But the cause is different.  Linking them together won't hurt but they aren't duplicate.

> Regardless, the steam-for-linux issue tracker isn't the right place for VAC or Counter-Strike 2 issues.

Don't behave like a politician.  @kisak-valve people will take **any** avenue hoping for someone competent (you) at Valve to pass information to the right team, this is because Valve don't have somewhere else to report things in a way that would be properly acknowledged.  They should but they don't.

(p.s. fix the M249 & Galil sound and fire whoever made those changes.  Just horrible.)
