### ISSUE TITLE
Steam creates symlink of compatdata by itself on exfat formatted usb stick

### ISSUE THREAD

**Issue by sergen213** [ValveSoftware/steam-for-linux#10926]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Fedora (Nobara 39)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/15449065/steamwebhelper.log)
[controller.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449066/controller.txt)
[connection_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449067/connection_log.txt)
[compat_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449068/compat_log.txt)
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449069/bootstrap_log.txt)
[webhelper.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449070/webhelper.txt)
[transport_steamui.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449071/transport_steamui.txt)
[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449072/cef_log.txt)
[configstore_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449073/configstore_log.txt)
[steamui_html.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449074/steamui_html.txt)
[workshop_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449075/workshop_log.txt)
[transport_client.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449076/transport_client.txt)
[steamui_audio.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449077/steamui_audio.txt)
[shader_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449078/shader_log.txt)
[systemperfmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449079/systemperfmanager.txt)
[systemmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449080/systemmanager.txt)
[systemdockmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449081/systemdockmanager.txt)
[systemdisplaymanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449082/systemdisplaymanager.txt)
[systemaudiomanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449083/systemaudiomanager.txt)
[steamui.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449084/steamui.txt)
[steamui_update.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449085/steamui_update.txt)
[steamui_system.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449086/steamui_system.txt)
[controller_ui.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449087/controller_ui.txt)
[client_networkmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449088/client_networkmanager.txt)
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449089/content_log.txt)
[cef_log.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449090/cef_log.previous.txt)
[timedtrial_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/15449091/timedtrial_log.txt)
* GPU: AMD

#### Please describe your issue in as much detail as possible: As soon as I plugin an exfat formatted usb drive, Steam creates a symlink of steamapps/compatdata directory on that drive. I formatted the drive on a different PC(which doesn't have steam) with ext4 then plugged it back in and it didn't happen.

It just doesn't let me unmount or format, even after exiting from Steam problem still persists. When I check which process is using the drive, it shows that systemd is using it.

Also, shader precaching is enabled (background caching too).

USB drive is SAMSUNG MUF-256AB/AM FIT Plus 256GB

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @sergen213, this looks like it's coming from `/etc/systemd/system/steamos-automount@.service`, which is part of Nobara's distro customizations based off of SteamOS (from https://nobaraproject.org/docs/upgrade-troubleshooting/nobara-stop-automount/).

This isn't an issue with Steam itself and you should follow up with your distro's package maintainer(s).

**Comment by sergen213** [comment]
I knew it 😞
