### ISSUE TITLE
Steam link on Android TV - Controller input vanishes the moment streaming from a Linux host starts

### ISSUE THREAD

**Issue by killstrelok** [ValveSoftware/steam-for-linux#10937]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.74-1ubuntu2
* Distribution (e.g. Ubuntu):  Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15496748/steam-logs.tar.gz)
* GPU: AMD RX 6700 XT

#### Please describe your issue in as much detail as possible:
When I attempt to stream anything using Steam Link app on an Android TV Box the controller input vanishes until the stream is stopped. Not only the inputs are not read, the haptic feedback on the touch pads also stops the moment anything appears on the screen and does not come back until the stream ends. The device, however, IS detected and I can see the controller in "Controller" section of Steam. Unfortunately any attempts to test the inputs yield no results - nothing is picked up by the host computer. Disconnecting/reconnecting the controller is registered by the host properly but the inputs are still ignored.

I've had this issue for a while, starting in Ubuntu 20.04. I did a fresh install of Ubuntu 22.04 and am running using OS defaults if that helps.

#### Steps for reproducing this issue:

1.  Have a Linux machine with Steam running that will act as a host
2.  Connect to said machine using Steam Link app from Android TV
3.  The moment stream starts, all inputs from the controller vanish. The input from a remote that came with the TV box works though.

**Comment by kisak-valve** [comment]
Hello @killstrelok, Steam Link for Android issues are not tracked on this issue tracker. Please report this issue on the forums at https://steamcommunity.com/app/353380/discussions/4/ if it hasn't been already.
