### ISSUE TITLE
Counter strike 2 dont save monitor settings (starting on 2nd screen, not 1 and main screen)

### ISSUE THREAD

**Issue by thq919** [ValveSoftware/steam-for-linux#10939]
#### Your system information

* Steam client version Steam Client Update - May 20th 2024
* Distribution Linux Mint 21.3 x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?:Yes
* Steam Logs: [logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/15501584/logs.zip)
* GPU: NVIDIA GeForce RTX 3080 Lite Hash Rate 

#### Please describe your issue in as much 

What i have:
Counter strike 2  always opened on second screen (philips)

What i want:
Counter strike 2  always opened on the first and main in system screen (acer)

#### Steps for reproducing this issue:

1.  Buy two monitors, install fresh mint, download counter strike
2. Open counter strike
3. This game opened in second screen somehow, not saving any settings. (like every time i start game, im always set window mode, place on first monitor game, fullscreen mode, click save and again and again and again and again and again and again)

**Comment by kisak-valve** [comment]
Hello @thq919, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3454 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3282. Closing as a duplicate.
