### ISSUE TITLE
Steam ver. 1708985249 (2/27/2024) and later corrupts Store page and Quick Menus on nvidia-drm 555.42.02

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/steam-for-linux#10940]
#### Your system information

* Steam client version (build number or date): [1708985249](https://store.steampowered.com/news/app/593110/view/4161959294800836361)
* Distribution (e.g. Ubuntu): Fedora 40
* Opted into Steam client beta?: N/A
* Have you checked for system updates?: N/A
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/15507214/steam-logs.tar.gz)

* GPU: NVIDIA 4090, NVIDIA proprietary driver version 555.42.02

#### Please describe your issue in as much detail as possible:
Out of sheer dumb luck, I have figured out the cause of the current Steam client issues with NVIDIA's beta driver 555.42.02. On recent Steam client versions, the Steam front page displays garbled text on the Store page if Hardware Video Encoding is Enabled in the Steam interface settings.

![desktop store home page](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/76877ff5-0f3a-4597-a8ed-d2512fb5f2c9)

In Big Picture Mode as well as gamescope-session, the side menus are similarly garbled:

![gamescope-session quick menu](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/3fb39b5b-ee7f-4363-a74e-f23286b25461)

Earlier today, I restored some folder backups from my NAS drive, including .local with an old Steam folder within there. After loading up my Steam client after this, I noticed that 1: I was on a build from November of 2023, and 2: that all of the Steam client issues I was experiencing on the latest Steam client were now gone.

After going forward through each client release version, I finally reached a my first known bad build: https://store.steampowered.com/news/app/593110/view/4161959294800836361

The build I tried prior to this, 1705108172 from January 12th, 2024, works perfectly. I suspect it is the embedded Chromium update in 1708985249 that has caused issues on NVIDIA. I'm including some screenshots from the "known good" build below.

![desktop store](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/b0fadbfd-897b-402a-85e7-3dd44499a042)

![mostly working Big Picture Mode side menu](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/4768136f-f893-4546-9391-f08005cddcaf)

**Comment by kisak-valve** [comment]
Hello @matte-schwartz, this issue is already being tracked at #10537.

Closing as a duplicate.
