### ISSUE TITLE
CS2 bug ru word

### ISSUE THREAD

**Issue by MrGrafGitHub** [ValveSoftware/steam-for-linux#10953]
* Steam client version (build number or date): 
Steam Beta Branch:  Stable Client
Steam Version:  1716584667
Steam Client Build Date:  Fri, May 24 23:48 UTC -08:00
Steam Web Build Date:  Fri, May 24 23:31 UTC -08:00
Steam API Version:  SteamClient021

* Distribution: Archlinux x11
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steamLog.zip](https://github.com/user-attachments/files/15578383/steamLog.zip)
* GPU:  NVIDIA GeForce GTX 1070 
* CPU:  i7-6700K (8)

When entering Russian text, additional characters are added, the question symbol ? and various others

П%?ри%?в%?е%?т%? (Привет)
И%?г%?р%?а%? (Игра)

video example https://www.youtube.com/watch?v=vcxcLxFwT-c&list=PLq3r6iV1vlpbc5sNKk1J8q0UgC96T_ohG&index=17

This type of text input is somewhat difficult to contact with allies in the game.

This problem is only seen in CS2. After a recent major update.

**Comment by kisak-valve** [comment]
Hello @MrGrafGitHub, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3749.

Closing as a duplicate.

**Comment by MrGrafGitHub** [comment]
Thanks
