### ISSUE TITLE
Unable to initialize Vulkan

### ISSUE THREAD

**Issue by Sectonidse** [ValveSoftware/steam-for-linux#10961]
(Sorry if this issue is a duplicate, but i searched the whole internet but found no answers.)
### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [logs.tar.gz](https://github.com/user-attachments/files/15747724/logs.tar.gz)
* GPU: NVidia GeForce GTX 1050 Ti

### Please describe your issue in as much detail as possible:
i expected stable 60 fps but got ~6 fpm. I tested Vulkan, it works. I reinstalled my 550 NVidia driver with 32-bit compatibility and this issue still exists. Also, Steam doesn't detect the GPU: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/94748461/995c5acc-1014-4468-84f8-23cd2fc6205a)
```
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
```

#### Tested Games with this issue:
* Black Mesa (Necro Patch with no DXVK, fps is ~2)
* Half-Life 2 (OpenGL, Vulkan crashes for no reason)
* Half-Life 2: Update
* Half-Life 2: Deathmatch (fps is ~10 with big stuttering on movement on low graphics with lowest 16:9 resolution)
* Transmissions: Element 120 (Sourcemod)
* Counter-Strike: Source
* Half-Life (OpenGL fps is ~20 with big stuttering on movement, Software mode renders fine)
* Half-Life: MMod
* Sven Co-op (fps is ~20 with no stuttering)

### Steps for reproducing this issue:

1. open steam
2. run any Source Engine (or even Goldsrc) based game (Except Jabroni Brawl: Episode 3 because it works)
3. experience **_IMMEASURABLY HUGE LAG_** (average fps: ~0.1, which is 10 seconds)

**Comment by kisak-valve** [comment]
Hello @Sectonidse, the symptoms you're showing is that the NVIDIA proprietary driver is broken, incomplete, or misaligned with the host system in the Steam in Snap container environment. Steam is being forced to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

This driver issue isn't something that can be fixed from the Steam client side. Report this issue to the Steam in Snap package maintainers or use Steam outside of that container environment.

Similar: https://github.com/canonical/steam-snap/issues/311 https://github.com/canonical/steam-snap/issues/358
