### ISSUE TITLE
Add option to validate a single mod

### ISSUE THREAD

**Issue by Nate700** [ValveSoftware/steam-for-linux#10965]
It would be useful to be able to validate a mod the main use case would be if a mod updated or you know the mod to be corrupted

**Comment by kisak-valve** [comment]
Hello @Nate700, this level of granularity doesn't make sense to implement. If distributed content is damaged or incomplete, the full intended set should be rechecked on request, not a small subset.

As a side note, using the term mod in this context and #10964 is ambiguous if you're referring to a published game on Steam that is a standalone mod with a dependency on another game, DLC, Steam workshop content, or game mods distributed outside of Steam.
