### ISSUE TITLE
Empty download (0B) - Infinitode 2

### ISSUE THREAD

**Issue by BWindey** [ValveSoftware/steam-for-linux#10970]
#### Your system information

* Steam client version (build number or date): Fri, May 24 10:48 PM UTC -08:00
* Distribution (e.g. Ubuntu): Zorin OS 17 (based on Ubuntu 22.04 LTS)
* Opted into Steam client beta?: [Yes/No] Not consciously
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15801521/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD Nvidia RTX 3050 laptop

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When trying to download the game Infinitode 2 through the Steam app, it reports 0B to download. Downloading goes very quick, but then trying to play the game raises an error:
> An error occurred while launching this game : Missing game executable - ~/.steam/debian-installation/steamapps/common/Infinitode 2/infinitode-2

#### Steps for reproducing this issue:

1. Search Infinitode 2 on Steam on Linux (on Zorin OS)
2. Press Download -> popup saying 0B space needed
3. Try launch game -> missing executable error

**Comment by kisak-valve** [comment]
Hello @BWindey, looking at this game's depots, this game has a Linux 64 bit depot (937312) which intentionally does not have anything in it for the game's mainline release, but it does with the `1.9.0-obt` beta branch.

This is something that needs to be handled by the game's dev(s). Odds are it will naturally be resolved with the game's next major update is promoted to the mainline release.

**Comment by BWindey** [comment]
Oh, ok. Thanks for the info! Hopefully the devs will fix that
