### ISSUE TITLE
Can't open steam Ubuntu 24.04

### ISSUE THREAD

**Issue by CCWTech** [ValveSoftware/steam-for-linux#10988]
#### Your system information

* Steam client version (build number or date): 3.5.19
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD: AMD
[steam-logs.tar.gz](https://github.com/user-attachments/files/15855511/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible: Steam opens in the upper right corner of my screen but I can't do anything with it.
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I would expect it to open.

#### Steps for reproducing this issue:

1. Fresh install of Ubuntu 24.04
2. Install steam
3.

**Comment by mount2010** [comment]
Possibly related/duplicated to #10974

**Comment by CCWTech** [comment]
Interesting, Running steam from the terminal works fine.

**Comment by kisak-valve** [comment]
Hello @CCWTech, that makes this the same issue as #9383. Closing as a duplicate.

**Comment by retroDEG** [comment]
> Interesting, Running steam from the terminal works fine.

yeah same here, i commented on #10935 about it
