### ISSUE TITLE
Steam Link  NVENC issue

### ISSUE THREAD

**Issue by kokossVN** [ValveSoftware/steam-for-linux#10984]
#### Your system information

* Steam client version (build number or date): 1718305227 ( Jun 14 ) 
* Distribution (e.g. Ubuntu): Arch Linux 
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/user-attachments/files/15848413/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

 just set up Steam Link in headless mode and chose NVIDIA NVENC for encoding.  Yesterday, I connected to Steam Link, but all the games felt really laggy.  Then I noticed the encoder was set to  libx264. 

#### Steps for reproducing this issue:

1.
2. 
3.

**Comment by kokossVN** [comment]
> #### Your system information
> 
>     * Steam client version (build number or date): 1718305227 ( Jun 14 )
> 
>     * Distribution (e.g. Ubuntu): Arch Linux
> 
>     * Opted into Steam client beta?: No
> 
>     * Have you checked for system updates?: Yes
> 
>     * Steam Logs:  [steam-logs.tar.gz](https://github.com/user-attachments/files/15848413/steam-logs.tar.gz)
> 
>     * GPU: Nvidia
> 
> 
> #### Please describe your issue in as much detail as possible:
> 
> just set up Steam Link in headless mode and chose NVIDIA NVENC for encoding. Yesterday, I connected to Steam Link, but all the games felt really laggy. Then I noticed the encoder was set to libx264.
> #### Steps for reproducing this issue:

"sorry my english so bad"

**Comment by tnbp** [comment]
This is also an issue for me, using the current stable 555 driver, on openSUSE. With 550, my machine encodes using NVENC, but Wayland is awful. On 555, it falls back to libx264 on both Wayland and X11.
I can still use NVENC in HandBrake/ffmpeg.

**Comment by jasonsansone** [comment]
I tested 550 and 555. I am on X11, haven’t tested Wayland. NVENC works in Plex, handbrake, and ffmpeg.

**Comment by Jcwscience** [comment]
I am also experiencing this issue on the 555.58.02 driver (proprietary and open). Running steam from the command line shows that the HEVC encoding pipeline is started and the libnvenc library appears to load, however it returns a generic error 20 as soon as the first frame is sent and falls back to libx264.

**Comment by rstrube** [comment]
I can also confirm that I am experiencing the same issue with the open nvidia 555.58.02 driver.  After the remote play client connects, the host attempts to begin encoding with NVENC but the first frame fails.  It then falls back to VA-API which also fails.

_Note: I do have the NVDEC based backend for VA-API installed on my system - arch package `libva-nvidia-driver` - but this is designed specifically to support VA-AAPI decoding within Firefox so I wouldn't expect it to work for remote play encoding._

Finally it falls back to software encoding which succeeds.

In the past NVENC encoding was working correctly on my remote play host machine.  I have not tested NVENC for other applications, but `ffmpeg` lists it as a valid encoder.

**Comment by Jcwscience** [comment]
The issue is present on the 560.28.03 beta driver as well.

**Comment by Jcwscience** [comment]
I think the issue may stem from the removal of legacy encoding profiles in newer driver versions. Can someone with access to the code base check on this?

**Comment by kevindherdt** [comment]
No solution for this?

**Comment by tnbp** [comment]
> I think the issue may stem from the removal of legacy encoding profiles in newer driver versions. Can someone with access to the code base check on this?

I think this sounds very plausible and is almost definitely what happened, especially seeing as NVIDIA has announced the removal of some older presets for "Q1'24": https://discourse.gstreamer.org/t/nvcodec-nvenc-nvidia-deprecates-support-for-old-videocodec-sdk-h-264-hevc-encoder-presets-with-driver-r550-in-q124/182

This would mean that everything is working as expected, Valve just need to update their software to make use of the new presets. DISCLAIMER: This is, of course, speculation.

**Comment by rstrube** [comment]
I was curious if there's been any solutions people have found - for instance is there a way to re-enable the older preset manually (if that is indeed the problem)?

I haven't been able to use Remote Play for a couple of months at this point - it would be great to be able to stream from my gaming PC to my SteamDeck again!

**Comment by 3ster** [comment]
This is still an issue after the October 2nd beta patch that (probably) touched encoding code adding AV1 encoding.

**Comment by tedb04** [comment]
Yeah, this is frustrating - I'm facing the same issue.  I upgraded the GPU in my headless docker host around the same time this issue popped up and I was wondering why my framerate was so bad.

**Comment by HugoPlacer** [comment]
I'm facing the same issue too :(

**Comment by hannemann** [comment]
I solved it for me using the Intel iGPU. Had to install the 32 bit driver in my headless steam. Maybe this works also on a non headless installation. See https://github.com/Steam-Headless/docker-steam-headless/issues/161#issuecomment-2425182344

**Comment by kevindherdt** [comment]
> I solved it for me using my Intel iGPU. Had to install the 32 bit driver in my headless steam. Maybe this works also on a non headless installations. See https://github.com/Steam-Headless/docker-steam-headless/issues/161#issuecomment-2425182344

I am happy that u found a workaround but this is not a solution for people without igpu. 

I hope they can fix it soon because using sunshine isn't ideal and has some very annoying bugs too.

**Comment by rstrube** [comment]
I agree it's super frustrating.  I've switched over to using Sunshine / Moonlight for the time being and it's working quite well.  I wish I didn't need to install extra software on my host machine to get things working though...

**Comment by tnbp** [comment]
somebody test this, they just included a fix in the latest beta

**Comment by 3ster** [comment]
Seems to be working on latest beta client on Fedora 41, RTX 4070, driver version 565.57.01. Debug overlay is showing nvenc hevc and  there aren't any processes using copious amounts of CPU.

**Comment by 3ster** [comment]
Client debug stats are definitely claiming HEVC:
![IMG_1744](https://github.com/user-attachments/assets/45fef4da-401c-44a1-bb64-6c407df81dbc)

**Comment by DuzAwe** [comment]
I am having this issue currently on cachyOS. 580.95.05 driver
