### ISSUE TITLE
Steam Deck with Intel

### ISSUE THREAD

**Issue by Leandro599** [ValveSoftware/steam-for-linux#10989]
Hello, I wanted to make a suggestion: make a version of the Steam Deck with Intel available, for those who like Intel. With support for secure boot, and other security features in the bios. And great performance, low temperature and large battery.

I left the suggestion here, sorry, because I couldn't find a specific topic for the Deck, I wanted to leave this suggestion, in case Valve sees it as viable.

😄

**Comment by kisak-valve** [comment]
Hello @Leandro599, requesting a physical product to be prototyped and released is out of scope for this issue tracker.
