### ISSUE TITLE
steamcmd's app_info_print does not work on linux

### ISSUE THREAD

**Issue by SergeyTsalkov** [ValveSoftware/steam-for-linux#10990]
#### Your system information

* Steam client version (build number or date): 2024-06-16
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: none available
* GPU: none

#### Please describe your issue in as much detail as possible:
Steamcmd app_info_print is an important command for game hosting providers, because we use it to determine when everyone's games need updating. It has stopped working (on Linux) on June 13, 2024. I have confirmed this on Ubuntu machines in 4 different data centers around the world. I also confirmed this on a clean Ubuntu VPS, to make sure that nothing about my existing setup was breaking it.

#### Steps for reproducing this issue:

1. Run steamcmd on Linux: `./steamcmd.sh`
2. Login: `login anonymous`
3. Run command: `app_info_print 376030`
4. I expected some output, but nothing is displayed.

**Comment by SergeyTsalkov** [comment]
Looks like this is related to https://github.com/ValveSoftware/steam-for-linux/issues/10975

**Comment by kisak-valve** [comment]
Hello @SergeyTsalkov, if the output of app_info_print is in stderr.txt like #10975, then there's no point in pondering this separately from the older issue report.

Closing in favor of #10975.
