### ISSUE TITLE
Big differences when using Proton

### ISSUE THREAD

**Issue by Leandro599** [ValveSoftware/steam-for-linux#11009]
#### Your system information

* Steam client version (build number or date):  latest
* Distribution (e.g. Ubuntu): Linux Kubuntu 24.04 Lts
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/user-attachments/files/15938354/steam-logs.tar.gz)

* GPU: Intel

#### Please describe your issue in as much detail as possible:

Hi, I wanted to leave feedback:
Between the native Linux versions and the Proton version, the sound has a higher volume through the Proton, in all the games I've played so far. The volume is twice as much on the Proton.
I wanted to leave feedback here, I believe it is on the Steam client. I would like to see the volume double in native Linux versions as well.

Lenovo Ideapad 3 15itl6 82md
Intel i3 1115G4
Btrfs
abnt2, ptbr utf8
Steam .deb

Thank you very much in advance
😄

#### Steps for reproducing this issue:

1. Change the system's power profile to Performance, open the game FlatOut 2 via Proton, and notice that the volume is good, and loud.
2. Open a native Linux game, like Horizon Chase turbo. The volume needs to be double.
3. Force any native Linux game to use the latest stable Proton, and see the difference.

**Comment by kisak-valve** [comment]
Hello @Leandro599, the Steam client doesn't control the volume of individual applications or how they connect to your audio hardware.
