### ISSUE TITLE
Fallback File/Folder picker does not work at all

### ISSUE THREAD

**Issue by ChristophFranzen** [ValveSoftware/steam-for-linux#11007]
#### Your system information

* Steam client version (build number or date): Client version: 1718751621
* Distribution (e.g. Ubuntu): Devian/Devuan
* Opted into Steam client beta?: [Yes/No] tried all three options (No Beta, "normal" Beta, "Family Beta")
* Have you checked for system updates?: [Yes/No] Yes, but still not up to date (dependency problems)
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] See below in the text dor relevant log file lines
* GPU: Nvidia/Intel/AMD Nvidia GF119 with Nouveau

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The "fallback picker" is the thing to be used if the "XDG Desktop Portal" is not available, or its version is too old (the latter is the case here). It's made for exactly my use case, and should therefore work. So please do not tell me to upgrade my system first (as developers tend to do) – in that case the fallback picker would not be needed any more, the bug would be still there, but unnoticed, because the "portal" would be used instead.

If I open any window where I have to choose a file or folder on disk, one of the following 2 bugs occurs:

1. I see a totally empty window with no files or folders therein. Clicking on anything won't do anything, I can only abort the action.
2. I can see my full file and folder hierarchy, but clicking on any of those, and choosing "Select" makes the steam client crash immediately without any further error message or log entry.

#### Steps for reproducing this issue:

1. Go to the menu: "Steam" -> "Restore Game Backup…" -> a new window opens: "Restore From Backup"
2. Choose "Browse" -> a new window opens: "Backup destination" – this is the "fallback folder picker".
3. The folder picker is totally empty (no files/folders inside); pressing any button other than "Cancel" doesn't do anything.

The steam client's logs are not helpful, the only line added throug this action is something alike:
`[2024-06-22 19:47:14] Unsupported desktop portal version: 1, falling back to a different file picker`

1. Go to the "Steam settings" -> "In Game"
2. "External screenshots folder" -> "Choose folder": a new window opens: "Select external screenshots folder"
3. At first this seems to be fully functional, you can browse to any filesystem location.
4. Choosing "Select", however, leads to an immediate crash, no matter which folder is chosen.

No error messages or further log entries can be seen.

**Comment by kisak-valve** [comment]
Hello @ChristophFranzen, this issue is already being tracked at #10360 / #10415. Closing as a duplicate.

**Comment by ChristophFranzen** [comment]
This issue is **not** a "pure" duplicate.
In the recent beta update, the issue of "unpopulated" folder trees has been fixed, but one last problem remains:

1. Go to the "Steam settings" -> "In Game"
2. "External screenshots folder" -> "Choose folder": a new window opens: "Select external screenshots folder"
3. At first this seems to be fully functional, you can browse to any filesystem location.
4. Choosing "Select", however, leads to an immediate crash, no matter which folder is chosen.
No error messages or further log entries can be seen.

On my machine, this happens **everywhere** where the fallback file picker is used: as soon as I click on select after choosing a folder from the directory tree, the steam client crashes immediately.
