### ISSUE TITLE
Steam Deck virtual keyboard issue: Tab key doesn't work in desktop mode

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [ValveSoftware/steam-for-linux#11003]
#### Your system information

* Steam client version (build number or date): **6/19/24 Stable**
* Distribution (e.g. Ubuntu): **Steam Deck LCD**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**
* ~~Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]~~
* GPU: **AMD**

#### Please describe your issue in as much detail as possible:
The tab key on the virtual keyboard doesn't work in desktop mode, but works fine in game mode. Pressing the "..." button and the down button on the d-pad still works normally to input a tab, and I don't see this behavior with any other keys.

#### Steps for reproducing this issue:

1. Summon the virtual keyboard in desktop mode with a text editor open.
2. Use the Tab key on the keyboard. Nothing will be output to that text editor or any other program.

**Comment by kisak-valve** [comment]
Hello @UsernamesAreNotMyThing, this issue is already being tracked at https://github.com/ValveSoftware/SteamOS/issues/1325. Closing in favor of the older issue report.
