### ISSUE TITLE
Steamwebhelper crashes on login

### ISSUE THREAD

**Issue by Vejituh** [ValveSoftware/steam-for-linux#11015]
[steam-logs.tar.gz](https://github.com/user-attachments/files/15954296/steam-logs.tar.gz) Your system information

* Steam client version (build number or date): 1718904662
* Distribution (e.g. Ubuntu): Fedora 40
* Opted into Steam client beta?: No/also happens in Family beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15954341/steam-logs.tar.gz)

* GPU: AMD 7800XT

#### Please describe your issue in as much detail as possible:
When I open Steam I get a Zenity and steamwebhelper crash, This leads to the steam window showing up for half a second and going away repeatedly every 3-4 seconds. Seems to be trying to restart webhelper as webhelper goes away in the processes and then comes back when steam flashes back up and then goes away.

Steam works fine when going into terminal and doing `steam`.

I can also provide gnome crash reports for steamwebhelper and zenity if needed

#### Steps for reproducing this issue:

1. Fresh install of fedora 40 workstation (also happened on kde)
2. Install steam
3. open steam and sign in

**Comment by Vejituh** [comment]
[steam-logs.tar.gz](https://github.com/user-attachments/files/15954302/steam-logs.tar.gz)

**Comment by Vejituh** [comment]
Having seen a post on fedora discussion ([https://discussion.fedoraproject.org/t/steam-window-is-not-displayed/122163/2](url))
I went into my bios and disabled integrated gpu on my Ryzen 7800X3D and now my steam opens as normal.

I assume integrated gpu shouldn't be causing an issue, is there anything you'd like me to try on my end to fix this?

**Comment by kisak-valve** [comment]
Hello @Vejituh, this issue is already being tracked at #9383. Closing as a duplicate.
