### ISSUE TITLE
Steam Controller is crashing Steam/causing strange issues when using BLE

### ISSUE THREAD

**Issue by aidanhadley** [ValveSoftware/steam-for-linux#11013]
#### Your system information

* Steam client version (build number or date): latest as of 06-23-2024 (tested on beta build as well)
* Distribution (e.g. Ubuntu): this has been tested on fedora 40, bazzite (based on fedora) 40, and endeavour os (arch linux)
* Opted into Steam client beta?: [Yes/No] both yes and no. affects both
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] [steam-logs.tar.gz](https://github.com/user-attachments/files/15949269/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD tested on both intel and amd

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When connecting a steam controller via BLE, a few things may happen:
1. If Steam is not running, it will connect fine and stay in "lizard mode:
2. If Steam is attempted to open, it will not, and some sort of error will happen (such as on gnome it says "Steam is not responding")
3. If Steam is opened, and the Steam Controller is connected, it will NOT be detected, nor will the user be able to open the settings tab to check.
#### Steps for reproducing this issue:

1. connect a Steam Controller (via BLE) to one of the distros above
2. either have Steam open or open Steam
4. observe the issue

####Extra notes
- this has been tested by about 5 people running similar distros with the same effect happening
- a fresh install of Arch causes this issue as well
- soon (should be tomorrow), i will test on a Steam Deck. others have reported it to work successfully on them.
- using the Steam Dongle (idk the official term lol), it works fine.

**Comment by Tripp024** [comment]
Same problem here on the Steam Deck.

**Comment by kisak-valve** [comment]
Hello @aidanhadley, this issue is already being tracked at #10203. Closing as a duplicate.
