### ISSUE TITLE
Gameplay Recorder Timeline UI Cannot Fully Be Interacted With

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#11025]
#### Your system information

* Steam client version (build number or date): 1719420706
* Distribution (e.g. Ubuntu): Arch Linux (KDE Plasma Wayland 6.1.0)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: Not sure if relevant here, but I can provide if necessary
* GPU: AMD 7900XTX

#### Please describe your issue in as much detail as possible:
The UI for the Game Recording Timeline can only partially be interacted with. On a 150% scaled display on KDE Plasma Wayland 6.1.0, only about half of the timeline recording works.

When moving to a regular non-scaled 1080p display, more of the UI is interactable (I can use the playback controls but not the "Clip" button) but there still seems to be a cutoff on this UI element.

Other parts of the Steam Overlay do not exhibit this issue, such as the Screenshot Manager and Web Browser.

#### Steps for reproducing this issue:
1. Run Steam from the commandline in order for the Steam Overlay to work
2. Enable the Game Recording feature
3. Start a game with the Steam Overlay activve
4. When in-game, activate the Game Recording timeline
5. Only part of the UI can be interacted with.

**Comment by toby3d** [comment]
I can confirm. Only the top two quarters of the timeline block react to the cursor. Buttons and items do not respond to pointing and clicking. The pop-up window when the menu item "Game Recording" is clicked also opens a window unavailable for any interaction.

**Comment by t0ssox** [comment]
Same issue. 1440p screen. Played a little with monitor scaling and still can't interact. Overall steam overlay has issues with wayland scaling but that is for another issue I guess.

**Comment by sonic2kk** [comment]
I haven't had any Steam Overlay issues on Wayland with scaling outside of this one, at least here on KDE Plasma. I have been using a scaled display with Wayland on my gaming PC for a couple years now.

**Comment by sonic2kk** [comment]
This has been fixed alongside #11126 as of at least the latest Steam Client Beta:

Steam Beta Branch: Steam Beta Update
Steam Version: 1729015347
Steam Client Build Date: Tue, Oct 15 18:45 UTC -08:00
Steam Web Build Date: Mon, Oct 14 22:56 UTC -08:00
Steam API Version: SteamClient021

I cannot pinpoint an exact Beta where this was fixed, much like with the linked issue, but it is fixed at least as of this current Beta.
