### ISSUE TITLE
Connecting steam controller via BLE causes steam and controller to become unresponsive

### ISSUE THREAD

**Issue by CobaltChris** [ValveSoftware/steam-for-linux#11021]
#### Your system information

* Steam client version (build number or date):  1718904662
* Distribution: Manjaro (Arch)
* Opted into Steam client beta?: No (Happens on beta as well)
* Have you checked for system updates?: Yes, None available
* Steam Logs: 
[appinfo_log.txt](https://github.com/user-attachments/files/15992916/appinfo_log.txt)
[bootstrap_log.txt](https://github.com/user-attachments/files/15992917/bootstrap_log.txt)
[cef_log.txt](https://github.com/user-attachments/files/15992919/cef_log.txt)
[client_networkmanager.txt](https://github.com/user-attachments/files/15992920/client_networkmanager.txt)
[compat_log.txt](https://github.com/user-attachments/files/15992930/compat_log.txt)
[configstore_log.txt](https://github.com/user-attachments/files/15992932/configstore_log.txt)
[connection_log.txt](https://github.com/user-attachments/files/15992934/connection_log.txt)
[connection_log_7777.txt](https://github.com/user-attachments/files/15992935/connection_log_7777.txt)
[console-linux.txt](https://github.com/user-attachments/files/15992936/console-linux.txt)
[console_log.txt](https://github.com/user-attachments/files/15992938/console_log.txt)
[content_log.txt](https://github.com/user-attachments/files/15992940/content_log.txt)
[controller.txt](https://github.com/user-attachments/files/15992942/controller.txt)
[controller_ui.txt](https://github.com/user-attachments/files/15992944/controller_ui.txt)
[inventory_service_log.txt](https://github.com/user-attachments/files/15992945/inventory_service_log.txt)
[librarysharing_log.txt](https://github.com/user-attachments/files/15992946/librarysharing_log.txt)
[parental_log.txt](https://github.com/user-attachments/files/15992948/parental_log.txt)
[remote_connections.txt](https://github.com/user-attachments/files/15992950/remote_connections.txt)
[shader_log.txt](https://github.com/user-attachments/files/15992952/shader_log.txt)
[sitelicense_log.txt](https://github.com/user-attachments/files/15992954/sitelicense_log.txt)
[stats_log.txt](https://github.com/user-attachments/files/15992956/stats_log.txt)
[steam_api_log.txt](https://github.com/user-attachments/files/15992957/steam_api_log.txt)
[steam-runtime-system-info-1683504038.txt](https://github.com/user-attachments/files/15992958/steam-runtime-system-info-1683504038.txt)
[steamui.txt](https://github.com/user-attachments/files/15992959/steamui.txt)
[steamui_audio.txt](https://github.com/user-attachments/files/15992961/steamui_audio.txt)
[steamui_html.txt](https://github.com/user-attachments/files/15992963/steamui_html.txt)
[steamui_system.txt](https://github.com/user-attachments/files/15992966/steamui_system.txt)
[steamui_update.txt](https://github.com/user-attachments/files/15992967/steamui_update.txt)
[streaming_log.txt](https://github.com/user-attachments/files/15992970/streaming_log.txt)
[systemaudiomanager.txt](https://github.com/user-attachments/files/15992971/systemaudiomanager.txt)
[systemdisplaymanager.txt](https://github.com/user-attachments/files/15992972/systemdisplaymanager.txt)
[systemdockmanager.txt](https://github.com/user-attachments/files/15992973/systemdockmanager.txt)
[systemmanager.txt](https://github.com/user-attachments/files/15992975/systemmanager.txt)
[systemperfmanager.txt](https://github.com/user-attachments/files/15992976/systemperfmanager.txt)
[text_filter_log.txt](https://github.com/user-attachments/files/15992977/text_filter_log.txt)
[timedtrial_log.txt](https://github.com/user-attachments/files/15992978/timedtrial_log.txt)
[transport_client.txt](https://github.com/user-attachments/files/15992979/transport_client.txt)
[transport_steamui.txt](https://github.com/user-attachments/files/15992980/transport_steamui.txt)
[webhelper.txt](https://github.com/user-attachments/files/15992982/webhelper.txt)
[webhelper-linux.txt](https://github.com/user-attachments/files/15992983/webhelper-linux.txt)
[workshop_log.txt](https://github.com/user-attachments/files/15992985/workshop_log.txt)

* GPU: AMD (RX 570 8GB)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Bluetooth adapter: ID 8087:0029 Intel Corp. AX200 Bluetooth

#### Steps for reproducing this issue:
1. Close Steam
2. Pair Controller via system UI over Bluetooth
3. Confirm Steam Controller is functioning in Lizard mode
4. Disconnect Controller
5. Launch Steam
6. Reconnect Steam Controller via BLE (It seems to function via USB and possibly dongle, but I do not possess one at the moment)

Steam UI backend will hang when Steam Controller leaves Lizard Mode and only basic interactive elements will move, such as library list. Anything that hasn't been cached will not load. All menus become unresponsive. Both the Controller and Steam require restarts to function independently.

**Comment by kisak-valve** [comment]
Hello @CobaltChris, what version of bluez are you using? This looks like https://github.com/bluez/bluez/issues/880 which should be fixed by the commit that closed that issue report.

**Comment by CobaltChris** [comment]
I have confirmed that the version of bluez causing issues was installed on my system. The commit in this mentioned issue is claimed to not fully fix the issue, but does allow the steam controller to function if connected before opening Steam.

I will make a side note as I close this issue, downgrading the bluez package to v5.73 seems to be the most reliable fix at the moment.
Steam controller works perfectly with 5.73 installed.
