### ISSUE TITLE
Installation gets stuck on "Finalizing" for most windows games

### ISSUE THREAD

**Issue by Lich-Corals** [ValveSoftware/steam-for-linux#11033]
#### My system information

* Steam client version: Steam Client Beta - June 26th
* Distribution: EndeavourOS rolling
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16017150/steam-logs.tar.gz)
eam/logs`]
* GPU: NVIDIA GeForce GTX 1650 with Max-Q Design

#### Description:
After switching Distribution (about two months ago) I weren't able to install most windows games, since the installation gets stuck at "Finalizing" without any sign of progress. If I then press the pause button of the installation, the game shows the normal "Play" button. If I try to launch the games, they all get stuck in "Launching".

I've noticed, that, if I uninstall the Nvidia drivers, the installation works fine, but the games won't start with the Nvidia drivers re-enabled. Instead, most of them say they were running, but no window shows up; even after multiple minutes.

The issue effects multiple games, which are steam-deck verified or which ran fine on other systems with the same hardware and the same beta enabled.

The problem doesn't effect native games.

**Comment by harsh13virdi** [comment]
Can you try something for me ?

Go to Steam -> Settings -> Compatibility and turn off "Enable steamplay for all other titles option"

Then download a windows game and manually set the compatibility buy right clicking on the game entry -> properties -> Compatibility and then select a version of proton there. 

I have been able to run few old windows games this way but i havent tried any modern titles.

All of the windows games were bricked for me in the same fashion as you describe but I am able to play games this way. 

I will try with few other/modern games aswell hope this can be a temporary fix in the mean time.

**Comment by Lich-Corals** [comment]
Thanks for the answer @harsh13virdi, I just tried your solution and it seems to work.
