### ISSUE TITLE
Steam can not open window

### ISSUE THREAD

**Issue by FroggLive123** [ValveSoftware/steam-for-linux#11032]
Steam client do not work

1. Steam version : most recent as of June 27
2. Distribution: Linux Mint ( based on Ubuntu ) 21.3
3. Steam beta client is not used
4. [
[logs.tar.gz](https://github.com/user-attachments/files/16017688/logs.tar.gz)
](url)

5. GPU: Nvidia with latest drivers

**Comment by kisak-valve** [comment]
Hello @FroggLive123, I take it you're using the NVIDIA 390 series video driver? `*** stack smashing detected ***: terminated` in your webhelper-linux.txt log makes this the same issue as #10980. Closing in favor of the older issue report.

**Comment by FroggLive123** [comment]
It worked, thanks a lot )
