### ISSUE TITLE
System Information shows onboard graphics info but not PCIe GPU info

### ISSUE THREAD

**Issue by mven** [ValveSoftware/steam-for-linux#11035]
#### Your system information

* Steam client version (build number or date): Steam Beta Update 1719453458 (Wed, Jun 26 8:35 PM UTC -08:00)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: 
* GPU: NVIDIA 3090 (PCIe card), AMD (on-board CPU)

#### Please describe your issue in as much detail as possible:

Running `Help > System Information` results in missing information about my NVIDIA GPU. In the `Video Card` section, I see the following, with no mention of my NVIDIA 3090:

```
Video Card:
Driver: Mesa zink Vulkan 1.3(AMD Radeon Graphics (AMD_OPEN_SOURCE))
Driver Version: 4.6 (Compatibility Profile) Mesa 24.1.2-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 174 Hz
VendorID: 0x1002
DeviceID: 0x164e
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 2
Primary Display Resolution: 3440 x 1440
Desktop Resolution: 3440 x 1440
Primary Display Size: 31.89" x 13.78" (34.72" diag), 81.0cm x 35.0cm (88.2cm diag)
Primary VRAM: 512 MB
```

#### Steps for reproducing this issue:

1.  Have onboard graphics + GPU PCIe card
2.  Open Steam client
3.  Go to Help > System Information menu
4.  View `Video Card` section and GPU PCIe card information is not shown

**Comment by kisak-valve** [comment]
Hello @mven, this is a repeat of #9712. Steam's basic system information is reporting the GPU that the Steam client is rendering with. Any in-depth troubleshooting should use Steam Runtime Diagnostics (`Steam` -> `Help` -> `Steam Runtime Diagnostics`).
