### ISSUE TITLE
Steam UI in game mode crashes when searching with the space in between the search words

### ISSUE THREAD

**Issue by dshk0718** [ValveSoftware/steam-for-linux#11034]
#### Your system information
Steam Deck OLED
* Steam client version (build number or date): 1719453458
* Distribution (e.g. Ubuntu): SteamOS 3.6.8
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16021099/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
What I expected:  Steam UI doesn't crash when I am searching for things.
What did happen: Steam UI crashed when I searched for things.

#### Steps for reproducing this issue:

1. Start typing in the search bar in the top bar header in Big Picture mode or game mode.
2. After typing the first word, enter a space and start typing a second word.
3. Steam UI should crash and show the error screen.

Screenshot of the error:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/22249997/27148a63-de3e-4d97-a6e7-70b11990506e)

**Comment by ZereoX** [comment]
@kisak-valve This ticket can be closed as Fixed. I confirmed that the issue has been resolved with the June 27th Steam Deck Beta Client Update: https://store.steampowered.com/news/app/1675200/view/4257672198480093316?l=english

From the changelog:
> Fixed error when entering multiple words into search box
