### ISSUE TITLE
New Screenshot UI "Copy to Clipboard" Share Option Does Not Work

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#11048]
#### Your system information

* Steam client version (build number or date): 1719532075
* Distribution (e.g. Ubuntu): Arch Linux (KDE Plasma Wayland 6.1.1)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: Can provide if necessary but not sure if needed here?
* GPU: AMD 7900XTX

#### Please describe your issue in as much detail as possible:
When opening the new Screenshot UI and clicking on the "Share" button, and then selecting the "Copy to Clipboard" option, nothing happens.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/7917345/ed26197f-8c89-4de0-8a88-fbf817a431f4)

I thought maybe blank or bogus data was being copied to the clipboard but inspecting my clipboard contents that doesn't seem to be the case.

Similar issues have cropped up in the past with copying to clipboard on Plasma Wayland for the store page, but these have been resolved since.

#### Steps for reproducing this issue:
1. Open the Screenshot Manager.
2. Select a screenshot.
3. Click the share button and choose "Copy to Clipboard".
4. Inspect clipboard, no screenshot copied.

**Comment by LarveyOfficial** [comment]
Can verify, this is indeed an issue. on EndeavourOS KDE Wayland 6.1.2, on the newest steam beta.
Seems to only be a problem with copying images or video, right clicking a steam store page and selecting "Copy Page URL" works fine, and so does clicking the URL at the top of the page, but whenever I copy a clip w/ the new game recording feature to clipboard, or copy a screenshot, it does not copy.

**Comment by sonic2kk** [comment]
This has been fixed at least as of the latest Steam Client Beta. I last tried this a couple of weeks ago or so and it was not fixed, but as of the latest Steam Client Beta, it is fixed.

Steam Beta Branch: Steam Beta Update
Steam Version: 1729015347
Steam Client Build Date: Tue, Oct 15 18:45 UTC -08:00
Steam Web Build Date: Mon, Oct 14 22:56 UTC -08:00
Steam API Version: SteamClient021

Closing as this problem is fixed! Woohoo!
