### ISSUE TITLE
Steam Client UI freezes for Library and Downloads after playing a game

### ISSUE THREAD

**Issue by Swivelgames** [ValveSoftware/steam-for-linux#11056]
# DUPLICATE OF #10806

> [!TIP]
> Current workaround is to:
>
> 1. Go to Steam Settings
> 2. Click the `Interface` tab
> 3. Uncheck the `Enable GPU accelerated rendering in web views` setting
>
> Please contribute to #10806 going forward.

---

#### Your system information

* Steam client version (build number or date): Stable Client (1718904662, Thu, Jun 20 12:14 UTC -08:00)
* Distribution (e.g. Ubuntu): Arch (Linux 6.9.6-zen1-1-zen, X11 + i3)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.9.6-zen1-1-zen)
* Mesa Version: 4.6 (Compatibility Profile) Mesa 24.1.2-arch1.1

#### Please describe your issue in as much detail as possible:

The Library and Downloads UI _appears_ to be unresponsive after getting out of a game. In reality, it is interactive, but the UI renderer doesn't seem to refresh.

It feels like it's an optimization, maybe for the Steam Deck, that's a bit overzealous. It happens occasionally, but it's more easy to reproduce by starting a game and then quitting.

It starts working again as soon as the window is moved or resized. Given that i3 is a tiling manager, resizing a  window a bit more annoying than with other Desktop Environments. Given a small amount of time, however, the UI stops refreshing again.

#### Steps for reproducing this issue:

1. Open Steam
2. Go to your Library tab
3. Notice that you can scroll, click on things, and interact with it
4. Launch a game, like Counter-Strike 2
5. Exit the game
6. Attempt to scroll, click on, or otherwise interact with the UI items

**Expected Result**

The UI for the Steam Library and Downloads tabs are visually responsive.

**Actual Result**

Interactivity works, but the UI itself does not _visually_ update.

**Workaround**

Resizing or moving the window forces the UI renderer to refresh the viewport.

**Caveat**

Other areas of the Steam Client are still functioning. For instance, going to the Store still works. The Library or Downloads screens, however, still don't visually update after returning to them from the Store.

**Comment by antoyo** [comment]
Same issue for me.
Another workaround is to minimize the window to the system tray and opening it again.

**Comment by Swivelgames** [comment]
@antoyo Good to know it's not limited to i3.

Are you on X11 or Wayland?

It may be an X11 bug...

**Comment by antoyo** [comment]
Oh, I'm also on i3, so X11.

**Comment by wasowski** [comment]
Same here, also i3 X11

**Comment by wasowski** [comment]
I also tested with sway Wayland (the equivalent setup to i3 x11), also on Ubuntu 24.04, and so far the problem does not appear, while on X11 I can reproduce it predictably

**Comment by Swivelgames** [comment]
I wish I could say it's becoming second nature to constantly resize my Steam Client, but it's definitely not. Now it's plaguing even the Store pages.

Valve, please. :pray:

**Comment by Swivelgames** [comment]
When I say plaguing, I mean that almost every interaction with the Steam Client requires me to regularly resize the client in order for it to start refreshing again.

**Comment by Swivelgames** [comment]
Oddly enough keeping a chat window open seems to keep the UI updating, which is a half-decent temporary workaround lol

**Comment by ruinedraziel** [comment]
You might wanna try this, I've a similar issue, but not linked to playing a game, I can cause the issue at  will by simply change workspaces out, example:
Steam on workspace 4,
got to workspace 1, then back, steam wont update it ui, simply workaround is just change its size, u can either use a float window or full screen shortcut and back and it goes back to normal, I've posted a video on a similar open issue, maybe a duplicate.

Check this discussion: https://github.com/ValveSoftware/steam-for-linux/issues/10806

**Comment by Swivelgames** [comment]
@ruinedraziel Indeed. I outlined that workaround above:

> When I say plaguing, I mean that almost every interaction with the Steam Client requires me to *_regularly resize the client in order for it to start refreshing again._*

The problem is that this is required on nearly every other interaction, and it's only becoming more and more frequent.

The other workaround that I had at one point was to keep a chat window open, but that doesn't seem to be a long-term workaround.

Someone else mentioned:
> Disabling "Enable GPU accelerated rendering in web views" in interface setting, work for me

I'll give that a try.

**Comment by Swivelgames** [comment]
Closing as duplicate of #10806
