### ISSUE TITLE
Controller input not working with Steam Input enabled

### ISSUE THREAD

**Issue by DonKatsu** [ValveSoftware/steam-for-linux#11060]
#### Your system information

* Steam client version (build number or date): 1719618357
* Distribution: CachyOS (Arch)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [controller_ui.txt](https://github.com/user-attachments/files/16070030/controller_ui.txt) [controller.txt](https://github.com/user-attachments/files/16070032/controller.txt)
* GPU: AMD RX 6700 XT

#### Please describe your issue in as much detail as possible:
I haven't used my controller in a while, so I'm not sure when this started. Controller is an 8bitdo Pro 2.

When Steam Input is enabled for a game, controller input does not work. When Steam Input is disabled, it works.
This happens with both Standard and Beta releases. Runtime and Native as well. Wired and Bluetooth both experience the issue.

Settings>Controller>Test Device Inputs works without issue.

#10998 seems similar, but says disabling Steam Input still doesn't work, and my Controller Layout pages seem to work as expected.

#### Steps for reproducing this issue:

1. Enable Steam Input on a game's settings
2. Launch game, controller does nothing
3. Disable Steam Input, launch game, controller works

**Comment by kisak-valve** [comment]
Hello @DonKatsu, can you check if the Steam overlay is working with the game(s) you tested?

**Comment by DonKatsu** [comment]
Yes, the overlay is working.
As far as specific games I've tried, the following don't work with Steam Input enabled:
Rabbit and Steel, Rabi-Ribi., Monster Hunter Rise, Dark Souls 3, Earth Defense Force 5, Deep Rock Galactic, Brigador (Native)
Games I've tried where Steam Input enabled **does** work:
Armored Core 6.

**Comment by DonKatsu** [comment]
I'm not sure what happened, but after a restart or two Steam Input is now working again for everything.
I switched back to the standard Steam release and it's working there too so it couldn't have been the Beta update that released earlier today?

**Comment by lonkalsim** [comment]
My steam input doesn't work for days in Monster Hunter Rise... With Dualshock the game is just glitching, with Xbox 360 controller my stick is drifting even though I set the dead zone to maximum...
