### ISSUE TITLE
Steam through Wine

### ISSUE THREAD

**Issue by Leandro599** [ValveSoftware/steam-for-linux#11065]
#### Your system information

* Steam client version (build number or date): Most current Steam.exe
* Distribution (e.g. Ubuntu): Fedora 40 Spin KDE 6 Wayland
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* GPU: Intel

#### Please describe your issue in as much detail as possible:

Hello, when installing and running the official steam .exe, via wine from the Fedora repositories, performance is a little low, with some frequent freezes.
In the big picture, the wifi is turned off, and it shows the message that it is offline. Sometimes, the message was in red, in the internet area.

In the games I have, some opened well, others closed along with Steam.

I wanted to leave this feedback to help with development, 😄

Lenovo Ideapad 3 15itl6 82md
Intel i3 1115G4
btrfs
4gb ram, 20gb swap
ptbr utf8, abnt2

joystick 2.4ghz wireless smart gamepad tgz 706w

#### Steps for reproducing this issue:

1. Install wine through the terminal, sudo dnf install wine
2. download the steam .exe file from the official website, and double-click on the file to install
3. See performance when trying to play games, navigate the big picture, etc.

**Comment by kisak-valve** [comment]
Hello @Leandro599, running Steam for Windows with wine is not supported.
