### ISSUE TITLE
No UI on Nvidia 390

### ISSUE THREAD

**Issue by TailsFanLOL** [ValveSoftware/steam-for-linux#11062]
#### Your system information

* Steam client version (build number or date): 03.07.2024 Beta (reproducable since last month)
* Distribution (e.g. Ubuntu): Mint 21 (Ubuntu Jammy), running KDE Plasma
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16081814/steam-logs.tar.gz)
* GPU: Nvidia Geforce 820m

#### Please describe your issue in as much detail as possible:
About a month ago Steam stopped showing a user interface. Instead, it puts itself in tray with all the regular options, yet the only functional one is "Exit Steam". Attempting to start a game from within the start menu or through the URL doesn't result in anything. I also appear offline in my profile during this.
This is definitely something NoVideo 390.x driver related: if I start a Wayland session (therefore disabling the GPU because the respective library doesn't get loaded), Steam functions as normal on Intel HD Graphics 4000.

#### Steps for reproducing this issue:

1. Run Steam

**Comment by kisak-valve** [comment]
Hello @TailsFanLOL, this issue is already being tracked at #10980. Closing as a duplicate.

**Comment by nex86** [comment]
I have the same issue, is there a solution?
390 is the only driver I can use with my GTX880M
My Laptop also does not have the iGPU available due to its displaytype.

**Comment by kisak-valve** [comment]
An NVIDIA GTX 880M should be a Kepler generation NVIDIA gpu. The last NVIDIA driver series to officially support Kepler laptops is 418.xx, but some people have seen it working with 470.xx which is the last series to support that hardware generation in general.

**Comment by diaphragm-workplace** [comment]
@nex86 , there's no workaround. Not sure about you but I found my integrated graphics (Intel Graphics 4000) actually be slightly faster than my overclocked 820m anyway.

**Comment by nex86** [comment]
> An NVIDIA GTX 880M should be a Kepler generation NVIDIA gpu. The last NVIDIA driver series to officially support Kepler laptops is 418.xx, but some people have seen it working with 470.xx which is the last series to support that hardware generation in general.

I tried 418.X but resulting in a black screen on boot. I had to revert to 390 in safemode.

**Comment by nex86** [comment]
> [@nex86](https://github.com/nex86) , there's no workaround. Not sure about you but I found my integrated graphics (Intel Graphics 4000) actually be slightly faster than my overclocked 820m anyway.

yea I wish I could use the integrated graphics but its disabled on this laptop due to the display type.
