### ISSUE TITLE
UI breaking when trying to add new a new drive

### ISSUE THREAD

**Issue by Ahickling04** [ValveSoftware/steam-for-linux#11076]
#### Your system information

0.20240610.0+srt1: 
Arch: 
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

i just switched to linux and was trying to get my games to work on my second hard drive (which was still running NTFS). upon seeing that they would not work, i formatted the drive and tried adding the storage device in steam but encountered this graphical bug. i don't know what to do

#### Steps for reproducing this issue:

1. format 2nd hard drive to ext4
2. log into i3 and mount to /mnt
3.  open steam and got to settings > storage > add new drive
![2024-07-07_21-01](https://github.com/ValveSoftware/steam-for-linux/assets/147832079/e9e7eb8a-e85f-4af5-b514-d35bc408f38e)
log out i3 and repeat steps in KDE plasma (x11) same graphical bug

**Comment by kisak-valve** [comment]
Hello @Ahickling04, Steam should be trying to call `xdg-desktop-portal` to give you a user selected dialog window and has failed before trying to use the fallback picker UI. The preferred solution would be to set that up on your system (https://wiki.archlinux.org/title/XDG_Desktop_Portal).

The issue with the fallback UI is already being tracked at #10415. Closing as a duplicate.
