### ISSUE TITLE
Linux Mint window focus behavior breaks clicking submenus in library.

### ISSUE THREAD

**Issue by Skyro468** [ValveSoftware/steam-for-linux#11077]
#### Your system information
    Steam client version: 1719967667
    Distribution: Linux Mint virginia 21.3 x86_64
    Window Manager: X-Cinnamon X11
    Desktop Environment: Cinnamon 6.0.4
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Right clicking a game in Library will open a submenu, however clicking any options in the menu will close the menu without performing the action.

#### Steps for reproducing this issue:

1. Change Window behavior for focus from default "Click" to "Mouse"
2. Try to click Properties or any other option in the right-click menu for a game in Library.
3. Submenu closes without action.

**Comment by kisak-valve** [comment]
Hello @Skyro468, this issue is already being tracked at #6. Closing as a duplicate.
