### ISSUE TITLE
New Game Recording Beta does not capture microphone

### ISSUE THREAD

**Issue by LarveyOfficial** [ValveSoftware/steam-for-linux#11072]
#### Your system information

* Steam client version (build number or date): 1719967667
* Distribution (e.g. Ubuntu): EndeavourOS, KDE Wayland 6.1.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: Not sure if needed, but can generate if required.
* GPU: AMD 7900 GRE

#### Please describe your issue in as much detail as possible:
The new beta game recording feature does not capture my microphone, my microphone is properly configured in settings in the voice section, but actual clips do not contain my voice. The game recording **does** capture discord and game audio, just not my microphone.

Example clip (I am speaking during this):
https://github.com/ValveSoftware/steam-for-linux/assets/39219859/7dbc0af5-68a5-4a8f-94e4-c3870707d4e7

#### Steps for reproducing this issue:

1.  Start game recording
2.  Listen to game recording and realize my voice isn't captured

**Comment by LarveyOfficial** [comment]
It seems this was marked as a feature request, does that mean it is currently intended behavior for the default microphone to not be recorded in the Game Recordings?

**Comment by LarveyOfficial** [comment]
Hello @kisak-valve, thank you for the quick response, I assumed that microphone capture was intended to be a feature due to the Windows client having the option for microphone capture. Please let me know if I am mistaken or not.

**Comment by Managor** [comment]
I'll chime in that I would like to see this implemented in the future. Voice chats are very one-sided in the recordings.

**Comment by Managor** [comment]
This feature is now implemented.

**Comment by micr0-dev** [comment]
I have found that it seems to not really work, the volume of the microphone is EXTREMELY quiet, (even with it working and sounding nice in steam voice settings)

i am on arch linux with pipewire
6.11.1-arch1-1

i am using an external microphone via a ADC and an xlr cable

please tell me what info i could provide to help solve this issue, i am confident its on steam's side as all other application and even games work. discord, teamspeak, obs, lethal company, etc all work fine

if needed i can provide a sample of what it sounds like but its basically mute, with the slightest signal coming through

and i have tried toggling and different configurations including noise reduction automatic gain and all that in steam.

**Comment by kisak-valve** [comment]
Closing as implemented.

Hello @micr0-dev, please open a new issue report focusing on your follow up issue.
