### ISSUE TITLE
Controller not working in any game regardless of connection method

### ISSUE THREAD

**Issue by Gwynsav** [ValveSoftware/steam-for-linux#11082]
#### Your system information

* Steam client version (build number or date): 1.0.0.79
* Distribution (e.g. Ubuntu): Void Linux (running Steam through flatpak)
* Opted into Steam client beta?: Tried both Yes and No.
* Have you checked for system updates?: Yes
* Steam Logs: [steam.logs.tar.gz](https://github.com/user-attachments/files/16160091/steam.logs.tar.gz)

* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Similar to [11060](https://github.com/ValveSoftware/steam-for-linux/issues/11060) and [10998](https://github.com/ValveSoftware/steam-for-linux/issues/10998). I have a Dualsense controller which works just fine in the Steam Client: I can navigate the Big Picture UI with it just fine, and all submenus relative to controller configuration, testing and setup work as expected.

I was using the controller with Steam Input disabled and a wired connection until recently, when it suddenly just stopped working with games. It may have been a recent update, though I've tried both the Stable and Beta releases and it didn't make a difference. I've also tried using the native distro-provided Steam package, but the exact same issue happens.

The issue starts when I open any game. I've tried a few games, namely Brawlhalla, Monster Hunter: World, MONSTER HUNTER RISE and Red Dead Redemption 2; as well as bluetooth and wired connections. When I connect my controller through a wired connection with Steam Input disabled, the game can only use the trackpad as a mouse, all other input is ignored. In other words, the game isn't recognizing the controller. Using a bluetooth connection with Steam Input enabled (tried both with the general setting set to Gamepad and game-specific configurations) results in the exact same behavior.

In the case of Steam Input, it seems as though my controller configuration is entirely ignored in-game, as if the configuration was for a different controller other than the one in use.

#### Steps for reproducing this issue:
The issue started pretty suddenly recently, and I don't really know what may have caused it. It may have been an update.

**Comment by kolemcrae** [comment]
I can second this - duelsense controller, using opensuse. If I enable steam input, the game completely ignores my controller. If I disable it, the game uses a totally wrong control mapping. I have tried using rocketleague, trackmania and tony hawk 1&2, same problem for all three of them. 

Tried leaving the beta and.... still doesn't work. So something borked!

**Comment by btwonion** [comment]
same here

**Comment by Arceles** [comment]
And... same here, was working ok just some days ago, but now Mi Dual Sense Edge is simply not recognized at all in the controller section of steam. (Using Endeavour OS updated to latest 14.07.2024)

**Comment by Korafex** [comment]
also happening on a xbox one controller. (assassins creed black flag and Odessy are the only ones i've tested)

**Comment by Korafex** [comment]
when pressing buttons on the controller... it's wonky as all hell. 

A= left trigger
B=B
X= left trigger
Y = left trigger

left bumper = left trigger (and now it's acting like the key is stuck being pressed in) 

seems everything is trying to go to left trigger basically and that's only when you click to remap the buttons. moment you hit "listen" it is registering the inputs 100% fine...

**Comment by Gwynsav** [comment]
Today, having some free time, I decided to revisit this problem and try to figure out a solution. I started out by cleaning up my environment, by:
1. Uninstalling Steam and removing all Steam related files.
2. Performing updates on both my system and flatpak to have all latest packages and possible dependencies.
3. Rebooting.
4. Installing Steam through flatpak again, alongside `steam-udev-rules` (on Void, equivalent to the `steam-devices` package of other distros).
5. Launching Steam, installing a game and testing the controller.

And now my controller actually works! It's still unclear to me why it originally worked regardless of me being missing `steam-udev-rules` and suddenly just stopped. So other people suffering from similar issues, try this out.



> when pressing buttons on the controller... it's wonky as all hell.
> 
> A= left trigger B=B X= left trigger Y = left trigger
> 
> left bumper = left trigger (and now it's acting like the key is stuck being pressed in)
> 
> seems everything is trying to go to left trigger basically and that's only when you click to remap the buttons. moment you hit "listen" it is registering the inputs 100% fine...

I'm unsure how this is related to the issue I presented, but feel free to try my solution out.

**Comment by codemonkeyiow** [comment]
> And now my controller actually works! It's still unclear to me why it originally worked regardless of me being missing `steam-udev-rules` and suddenly just stopped. So other people suffering from similar issues, try this out.

On Arch linux, the AUR package https://aur.archlinux.org/packages/game-devices-udev fixed this issue for me. https://github.com/ValveSoftware/steam-for-linux/issues/10998#issuecomment-3318741348
