### ISSUE TITLE
Recommendation: Steam shouldn'T start downloading when choosing different "compatibility tool"

### ISSUE THREAD

**Issue by YoinkerBoinker** [ValveSoftware/steam-for-linux#11086]
This is more of a recommendation than an issue. When trying to selecting a different compatibility tool for a game by "checking" the box for "force the use of a specific steam play compatibility tool".  Steam will start to download new binaries for the game immediately. 
This is problematic especially when running "Native" games. So in case you had a "Linux version" before.. steam will now start downloading the Windows version for the game since "Proton" is the first selected "compatibility tool" in the list. 

My recommendation: 
The Download should start after selecting AND closing the Window. To prevent unnecessary downloads.

![grafik](https://github.com/user-attachments/assets/7ace6aaa-37a9-4686-b76c-cb0ba143e066)

**Comment by kisak-valve** [comment]
Hello @YoinkerBoinker, this issue is already being tracked at #6870. Closing as a duplicate.
