### ISSUE TITLE
[Feature Request] Per game shader pre-caching enable/disable checkbox

### ISSUE THREAD

**Issue by Xenophobe-01** [ValveSoftware/steam-for-linux#11081]
It would be very convenient to be able to enable/disable shader pre-caching on a per game basis, just like cloud saves have a per game option in addition to the global cloud setting.

I have around 50 games installed (6TB of SSD) that I cycle playing through the year and the shader update routine every time I start steam is ridiculous. Being able to limit the shader pre-caching to only the game(s) I'm currently playing would be far superior.

**Comment by kisak-valve** [comment]
Hello @Xenophobe-01, this request is already being tracked at #6486. Closing as a duplicate.
