### ISSUE TITLE
Freezing on launch in Wayland Session

### ISSUE THREAD

**Issue by iseldacyn** [ValveSoftware/steam-for-linux#11080]
#### Your system information

* Steam client version (build number or date): Latest (1.0.0.79-2?)
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16133356/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

Using Steam on Wayland (Hyprland) seems to completely crash steam, making it hang on start up. The output of my terminal when running can be found [here](https://gist.github.com/iseldacyn/9e7bb2954a10f931f29ffee29c348bd6). Steam boots and runs fine when running with X11 (XMonad), but completely stops loading when running in Wayland.

The updater appears and disappears for a second, with the process running continuously in the background but not using any resources. I have no clue what the root of this bug is, and have let it run for several hours and no further output is displayed to the terminal afterwards.

**Comment by cirk2** [comment]
[console.log](https://github.com/user-attachments/files/16201903/console.log)
[logs.tar.gz](https://github.com/user-attachments/files/16201907/logs.tar.gz)

Observing the same behavior on Arch with AMD/Mesa and Sway. Originally was on the steam client beta but opted out via console argument for testing, behavior and log output is the same in both versions.

I tried putting steam into game scope but it froze the same way [gamescope.log](https://github.com/user-attachments/files/16201938/gamescope.log)

**Comment by iseldacyn** [comment]
As an update, I have narrowed it down only to a Wayland issue. Reinstalling steam completely doesn't change this behavior at all. Additionally, I have tried Sway (like above) and KDE Plasma to no avail. Steam runs just fine in Hypr, AwesomeWM, and DWM though. Maybe it has something to do with a newer version of wl-roots? If not, I am lost as to what causes this.

**Comment by iseldacyn** [comment]
A recent system update fixed this for me. I think it may have been an xorg-xwayland issue, as a new version fixed this.

**Comment by kisak-valve** [comment]
Closing per the last comment.
