### ISSUE TITLE
Web view shows black screen when GPU accelerated rendering is enabled.

### ISSUE THREAD

**Issue by Revival8697** [ValveSoftware/steam-for-linux#11107]
#### Your system information

* Steam client version: 1721173529 to 1722380543.
* Distribution: Arch Linux + KDE + Wayland
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16288992/steam-logs.tar.gz)

* GPU: Intel i7-10750H UHD Graphics (Intel + Nvidia laptop)

#### Please describe your issue in as much detail as possible:
When GPU accelerated rendering is enabled, I expected web view to show up. Instead, the web view shows black screen.
#### Steps for reproducing this issue:

1. Verify that `Steam` > `Settings` > `Interface` > `GPU accelerated rendering in web views` is enabled.
2. Click on the `Community` tab.
3. Web view shows black screen:

![Screenshot_20240719_033153 cleaned](https://github.com/user-attachments/assets/683ea502-2b64-44e1-992d-a939f05d259b)

**Comment by Revival8697** [comment]
Might relate to https://github.com/ValveSoftware/steam-for-linux/issues/11094.

**Comment by aPoCoMiLogin** [comment]
for me only on beta branch the store view is black, disabling accelerated rendering fixes the issue. or switching to stable branch also fixes the issue.

- Steam client version: 1721173529
- Distribution: Pop!_OS 22.04 LTS + Gnome + X11
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
- GPU: NVIDIA GeForce RTX 2060 (drivers 550.67)

**Comment by vient** [comment]
Copying from #11114 dup, same issue with
* Steam client version (build number or date): 1721420033
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: Intel Arc, integrated in Core 155H cpu

**Comment by Davidekiller1999** [comment]
Same issue here. I need it for my family sharing. Manjaro and 550 Nvidia driver.

**Comment by TheDevMinerTV** [comment]
I'm getting something similar:
![image](https://github.com/user-attachments/assets/f1981be5-fe0f-48a7-81d5-1c0a6ced876c)

Steam Version: 1721173382 stable
GPU: Nvidia 4080
Distro: Arch

**Comment by Revival8697** [comment]
I just updated to Mesa 24.1.5 and this has been fixed so I guess this was a Mesa issue?

**Comment by buckysrevenge** [comment]
Running Manjaro Gnome stable, kernel 6.10.3-1-MANJARO
Steam family beta current
Desktop client with GPU acceleration enabled, integrated GPU (Intel UHD Graphics 360, driver 24.1.5-manjaro1.1), the store appears blank but the cursor changes when moving it around (pointer hand vs arrow), turning off GPU acceleration allows web based pages to display properly

Stable Steam client doesn't have this issue for me

**Comment by lzhecz** [comment]
System: Arch linux, dwm (x11 window manager), linux-zen 6.10.4.zen2-1
Steam Beta Branch:  Steam Families Beta (Same on beta)
Steam Version:  1723685248
GPU: Nvidia 2060 Super with nvidia-open-dkms 555.58.02-15 (same on non-open drivers nvidia-dkms)

Same issue black screen on web with GPU acceleration
Disabling GPU accelerated rendering helps

**Comment by Revival8697** [comment]
CC: @aPoCoMiLogin @Davidekiller1999 @TheDevMinerTV @lzhecz.

Can you update to the latest Beta and test?

https://store.steampowered.com/news/group/4397053/view/4241914673855027247

**Comment by Davidekiller1999** [comment]
just tested. For me it works fine. Thanks for the fix!

**Comment by lzhecz** [comment]
now everything works, thanks for the fix

**Comment by buckysrevenge** [comment]
Yes, the latest beta fixes this issue for me as well

**Comment by Revival8697** [comment]
Seems fixed for everyone now.

**Comment by aPoCoMiLogin** [comment]
> CC: @aPoCoMiLogin
> 
> Can you update to the latest Beta and test?
> 
> https://store.steampowered.com/news/group/4397053/view/4241914673855027247

works like a charm with:

> Steam Beta Branch:  Steam Beta Update
> Steam Version:  1724453533
> Steam Client Build Date:  Sat, Aug 24 00:35 UTC -08:00
> Steam Web Build Date:  Fri, Aug 23 23:43 UTC -08:00
> Steam API Version:  SteamClient021

cheers
