### ISSUE TITLE
Steam downloads and cloud saves fail with "No Connection", logout and cant login back

### ISSUE THREAD

**Issue by ku4eto** [ValveSoftware/steam-for-linux#11106]
#### Your system information
Laptop Lenovo ThinkPad T15, 1.62 UEFI (latest)

`lshw` output: https://gist.github.com/ku4eto/aa390a0c440d3470311aa301a83c260d

* Steam client version (build number or date):  1718904662 
```steam-launcher/unknown,unknown,now 1:1.0.0.79 all [installed]
steam-libs-amd64/unknown,now 1:1.0.0.79 amd64 [installed]
steam-libs-i386/unknown,now 1:1.0.0.79 i386 [installed,automatic]
steam/unknown,now 1:1.0.0.79 i386 [installed]
```
* Distribution` (e.g. Ubuntu): Linux Mint 20.3, Kernel 5.15.0-111
* Opted into Steam client beta?:  No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/16288234/steam-logs.tar.gz)

* GPU: Intel Iris XE

#### Please describe your issue in as much detail as possible:
About a week ago, maybe after an `apt-get dist-upgrade`, Steam started being unable to sync cloud saves from the cloud to the laptop.
At the same time, it started being unable to download updates for games (Dota2).
Tried changing downloads region. Same issue.
Tried clearing `Download Cache`.
Now Steam is stuck on loading screen after picking out my account to log in.

Checked the logs. It complains it cant download files, along with unable to resolve hostnames.
Files are downloadable via `curl` , hostnames are also resolvable.
Tried changing the DHCP provided DNS (ie, from being my router and then my ISP DNS) to 1.1.1.1, no difference. Both times reachable via `curl`, but seemingly not by Steam.

Tried downgrading Kernel from 5.15.0-111 to 5.15.0-107, no difference.

Additional syslogs:
```
Jul 18 22:35:24 ku4eto geoclue[6025]: Failed to query location: Not Found
Jul 18 22:35:24 ku4eto rtkit-daemon[1041]: Supervising 11 threads of 3 processes of 1 users.
Jul 18 22:35:24 ku4eto rtkit-daemon[1041]: Supervising 11 threads of 3 processes of 1 users.
Jul 18 22:35:37 ku4eto geoclue[6025]: Failed to query location: Not Found
Jul 18 22:35:43 ku4eto assert_20240718223543_33.dmp[9265]: Uploading dump (out-of-process)#012/tmp/dumps/assert_20240718223543_33.dmp
Jul 18 22:35:43 ku4eto assert_20240718223543_33.dmp[9265]: Finished uploading minidump (out-of-process): success = no
Jul 18 22:35:43 ku4eto assert_20240718223543_33.dmp[9265]: error: Couldn't resolve host name
Jul 18 22:35:43 ku4eto assert_20240718223543_33.dmp[9265]: file ''/tmp/dumps/assert_20240718223543_33.dmp'', upload no: ''Couldn't resolve host name''
Jul 18 22:36:05 ku4eto rtkit-daemon[1041]: Supervising 11 threads of 3 processes of 1 users.
Jul 18 22:36:05 ku4eto rtkit-daemon[1041]: Supervising 11 threads of 3 processes of 1 users.
Jul 18 22:38:46 ku4eto systemd[1136]: Started VTE child process 9359 launched by gnome-terminal-server process 6138.

```
The `geoclue` seems to be due to the Mozilla Location Service being deprecated.
Disabling the services does nothing. Not sure if Steam depends on it in any way.
No idea about the rest.

#### Steps for reproducing this issue:

1. ???

**Comment by kisak-valve** [comment]
Hello @ku4eto, did any system packages related to DNS lookup change in the system update? Lines like `[2024-07-18 21:34:24] HTTPS (SteamCache,407) - cache12-vie1.steamcontent.com (0.0.0.0:443 / 0.0.0.0:443, host: cache12-vie1.steamcontent.com): cache12-vie1.steamcontent.com/depot/1201541/manifest/8893749534534721892/5/14266025872791968126 - received 0 (Invalid) HTTP response` hints that *.steamcontent.com are resolving to 0.0.0.0 instead of a real IP address.

**Comment by ku4eto** [comment]
Sorry, my bad.
After further debugging, it seems like i have bee fiddling with `/etc/nsswitch.conf`
`hosts:          resolve dns files mdns4_minimal [NOTFOUND=return] [!UNAVAIL=return] myhostname` is the currently working configuration.
`hosts:          resolve files mdns4_minimal [NOTFOUND=return] [!UNAVAIL=return] dns myhostname` is the previously broken configuration.
Not sure why it is like that - specifically the NOTFOUND, UNAVAIL args and everything else bug Steam and Battle.net failing.
