### ISSUE TITLE
Linux users = Low MMR compared to the windows one's / Trust FACTOR = NO NO

### ISSUE THREAD

**Issue by ilievi187** [ValveSoftware/steam-for-linux#11105]
#### Your system information

* Steam client version -latest beta build
* Distribution -  Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

* GPU: AMD 7900XT

#### Please describe your issue in as much detail as possible:
I've played 2 maches on same map with 3 accounts. 6 victoryies. Windows account =DMG2 and 2 linux accounts one is gold nova 2 the other one is silver elite.
Play on a map to get rank 🥇 
Win game on 3 accounts 🔢 

Second test 👍 
Main account 10 premier wins = less than 5k elo = In the first match i played i beated a 18k elo player - https://steamcommunity.com/id/ajnik/
here is the match ---> https://csstats.gg/match/140060985
He has similar stats as me 1.4 kdr but he get ranked so much higher. 
Same account thath i beat; after 10 wins got 12363+ ELO because he is using WINDOWS.

Trust factor for linux users not working at all i dunno why i allways play against new accounts using cheats against me.
I have more matches against cheaters than everybody on this forum u can check my stats. 330+ games against CHEATERS 
https://csstats.gg/player/76561199032915381/csgo#/matches

This is because trust factor is not working for Linux users its very obvious somthing is wrong. 
 i got 600+ maches from since i start playing CS , 500 maches are against cheaters. 330+are vac banned.
Please revisit trust factor because obviously is not recognizing my account as trusted one. I have previosly overwarch , i have banned cheaters etc. Still mached against new cheat accounts.  

So many coincidences and evidence that cannot be coincidence.

Please its really painfull and its ruining my gameplay expirience.

Thank you very much.

**Comment by kisak-valve** [comment]
Hello @ilievi187, account issues are not handled in any capacity on GitHub.

**Comment by ilievi187** [comment]
> Hello @ilievi187, account issues are not handled in any capacity on GitHub.

Bro its not account issue its OS related. Wanna test it ? Try
