### ISSUE TITLE
"Show only games that run on Linux" should filter for native apps

### ISSUE THREAD

**Issue by naomi-lgbt** [ValveSoftware/steam-for-linux#11108]
#### Your system information

* Steam client version (build number or date): 1.0.0.79-2
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes - steam family beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16289445/steam-logs.tar.gz)
* GPU: Nvidia

---

![image](https://github.com/user-attachments/assets/94764154-0584-4249-a128-b5628e1b1a36)

The `Show only games that run on Linux` filter seems to show *all* games, when "Enable Steam Play for all other titles" is toggled on.

It would be nice if this still filtered to games that had a proper native Linux build.

**Comment by kisak-valve** [comment]
Hello @naomi-lgbt, this issue is already being traced at #5639. Closing as a duplicate.

**Comment by naomi-lgbt** [comment]
Whoops, sorry! Tried to search for dupes. 

Thanks for letting me know!
