### ISSUE TITLE
Black screen on tabs powered by the built-in browser

### ISSUE THREAD

**Issue by vient** [ValveSoftware/steam-for-linux#11114]
#### Your system information

* Steam client version (build number or date): 1721420033
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16318183/steam-logs.tar.gz)
* GPU: Intel, integrated in Core 155H cpu

#### Please describe your issue in as much detail as possible:
All tabs that use browser are black. Mouse shows that elements are there, I can click on them and URL changes, but the whole tab is black. That means I can only see library, store and community tabs do not work.

A week ago everything worked fine.

Title shamelessly copied from #9598 - my issue does not exactly match that one though, so I created a new one.

#### Steps for reproducing this issue:

1. Launch Steam

Well, no more steps, it launches with a store tab opened which is black.

**Comment by vient** [comment]
Opted out of beta, client version 1721173382 works fine. Just in case of some spurious issue like file corruption, opted in beta again, black screen reproduced. So the issue is in beta version somewhere. Logs after doing all this: [steam-logs.tar.gz](https://github.com/user-attachments/files/16318221/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @vient, this issue is already being tracked at #11107. Closing as a duplicate.

**Comment by vient** [comment]
Yeah, saw that issue after submitting this one, was reading it when you wrote :)
Confirmed now that disabling GPU accelerated rendering helps, so definitely the same issue.
