### ISSUE TITLE
Steam storefront loads into black screen

### ISSUE THREAD

**Issue by Juppstein** [ValveSoftware/steam-for-linux#11113]
#### Your system information

* Steam client version (build number or date): 1721173529
* Distribution (e.g. Ubuntu): Ubuntu 22.04 / Kernel 6.8.9-1
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/user-attachments/files/16316922/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD Nvidia 550.90.07 running under xfce/lightdm

#### Please describe your issue in as much detail as possible:

Opening the store front with the latest beta version gives me a black screen instead of the store layout. Tried disabling/enabling GPU blocklist as well as jumping between menus before trying to open the store, but to no avail. Also no difference between big picture and regular mode.

#### Steps for reproducing this issue:

1. Start Steam
2. Go to store front
3. Get black screen

![Workspace 1_270](https://github.com/user-attachments/assets/3c9e69e5-70a3-496f-9cc7-560f7ed70b32)

**Comment by kisak-valve** [comment]
Hello @Juppstein. these look like some lines of interest from your steamwebhelper.log:
```
[0529/171415.493088:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglMakeCurrent: Failed to make the GLX context current
[0529/171415.493199:ERROR:gl_context_egl.cc(475)] eglMakeCurrent failed with error EGL_CONTEXT_LOST
```
Does completely closing Steam, then running `steam -system-compose` or `steam -cef-disable-gpu` workaround the issue? (from #10561)

**Comment by mhanuszh** [comment]
I have the same problem, but only when GPU accelerated web view are enabled

Steam: 1721173529 (beta branch)
Debian 12, Gnome 43.9, X11, Nvidia 535.183.01, Kernel 6.1.0-17-amd64
Intel Core i5-2500, GeForce GTX 1050 Ti, 16GB DDR3

**Comment by RandomHuman2020** [comment]
Encountering the same problem, though it only appeared for me after killing all steamwebhelper processes as a temporary workaround for #9561 

tested the two arguments, `-system-compose` did not solve the problem, but `-cef-disable-gpu` did.

Steam: 1721420033 (Families beta branch)
Debian 12, KDE Plasma 5.27.5, NVIDIA Driver 535.183.01, Kernel 6.1.0-23-amd64
Intel Core 17-12700F, GeForce RTX 3060, 48GB DDR4

**Comment by mhanuszh** [comment]
Same on my other PC. This is not Nvidia specific

Steam 1721420033
Fedora 40, Gnome 46.3.1, Wayland, Intel Mesa 24.1.2 i915, Kernel 6.9.9-200.fc40.x86_64
Intel Xeon E3-1225 v5, Intel HD Graphics P530, 8GB DDR4

**Comment by Juppstein** [comment]
> steam -system-compose

It does work with 

> Hello @Juppstein. these look like some lines of interest from your steamwebhelper.log:
> 
> ```
> [0529/171415.493088:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglMakeCurrent: Failed to make the GLX context current
> [0529/171415.493199:ERROR:gl_context_egl.cc(475)] eglMakeCurrent failed with error EGL_CONTEXT_LOST
> ```
> 
> Does completely closing Steam, then running `steam -system-compose` or `steam -cef-disable-gpu` workaround the issue? (from #10561)

It does work with cef-disable-gpu but not with system-compose

**Comment by sh3zb0t** [comment]
`-system-compose sems` to have fixed it for me

arch/kde/wayland nv555 here

**Comment by akrychowski** [comment]
fedora 40 64bit, intel 12th gen, KDE - same issue. helping opt-out from beta (or beta_families) or steam -cef-disable-gpu

**Comment by pullasuti** [comment]
Same problem. Both `-cef-disable-gpu` and `-system-composer` (instead of "compose") fix the issue. Using stock Pop OS 22.04 and nvidia driver 555.58.02

**Comment by kust2708** [comment]
Same problem with Intel iGPU (Intel(R) UHD Graphics 770). Using NVIDIA GPU (NVIDIA GeForce GTX 1080 Ti) with `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia steam` or `steam -cef-disable-gpu` solve the problem.
[steam-logs.tar.gz](https://github.com/user-attachments/files/16445513/steam-logs.tar.gz)

**Comment by oreo639** [comment]
I am experiencing this with Steam beta client 1723601482 on Void Linux with an intel igpu.
https://gist.github.com/oreo639/999ccf9a318a958fe6983d3c46229da4

**Comment by pullasuti** [comment]
Still having the issue with beta 1723685248

**Comment by TTimo** [comment]
The next beta client update will have some fixes for this. Note that for this specific problem, you shouldn't need to use `-cef-disable-gpu` as a workaround. It should be enough to set `-system-composer`.

**Comment by kust2708** [comment]
The issue seems to be solved.

**Comment by Juppstein** [comment]
Yup, can confirm that this seems to have been fixed in the recent updates 👍🏼
