### ISSUE TITLE
Вылетают игры

### ISSUE THREAD

**Issue by Dorit280** [ValveSoftware/steam-for-linux#11120]
#### Your system information

* Steam client version (build number or date): Последняя
* Distribution (e.g. Ubuntu): не имеет значения
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: нетимсеет значения
* GPU: не имеет значения

#### Please describe your issue in as much detail as possible:
Проблема состоит в том, что у меня всего 4 гб ОЗУ, и при запуске пк свободно ~2 гб, при запуске steam он съедает все 2 гб и оставляет 100-200 мб на работу пк. Игры в стиме я не могу запустить из за этого, как снизить нагрузку стима на компьютер?

#### Steps for reproducing this issue:

1. Запустить стим
2. Зайти в игру
3. Вылет из игры с сообщением о маленькой свободной памяти ОЗУ от самого Ubuntu

**Comment by kisak-valve** [comment]
Hello @Dorit280, you can add a swap partition or swapfile to use your storage device as additional RAM to avoid out of memory issues.

The general topic of resource usage by the Steam client is being tracked at #6802. Closing in favor of the older issue report.
