### ISSUE TITLE
Cannot read properties of undefined (reading 'BLoadingClips')

### ISSUE THREAD

**Issue by wereii** [ValveSoftware/steam-for-linux#11121]
#### Your system information

* Steam client version (build number or date):  1721420033 
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16319886/steam-logs.tar.gz)
* GPU: Nvidia 

#### Please describe your issue in as much detail as possible:

~~The new Game Recording does not work. Any window that should seemingly show it (I don't even know how it looks) results in an error, be it `View -> Recordings & Screenshots` or in overlay. Black background with this text:~~

I am getting a black window with following text:
```
Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_9051698_c9074a2fca142c7b
Cannot read properties of undefined (reading 'BLoadingClips')
```

#### Steps for reproducing this issue:

~~1. Open any window that should view Game Recording~~

1. Open `View -> Recordings & Screenshots` OR in overlay, from the Game Overview button (the first icon from the left of the toolbar).

#### Notes
- not using Archs `steam-native-runtime`
- Tried `steam-runtime --reset`, issue still persists (the logs are from after the reset)

**EDIT:** I am now not sure how much it has to do with Game Recording - in overlay, I can click the Game Recording button which takes me into the settings of that feature. Selecting any of the "on" modes causes the overlay to show extra error on top of the overlay 'GetTimelineLoaderForGame'.  
When off, I am only getting the 'BLoadingClips'

![image](https://github.com/user-attachments/assets/a7d17868-b565-4e19-8bce-86f80081b4ac)

**Comment by artik** [comment]
I reported the issue on this post https://github.com/ValveSoftware/steam-for-linux/issues/11045, and I'm still facing this bug with the latest Beta updates.

The "not able to save disk" error is vanished BTW.

**Comment by wereii** [comment]
I don't have this problem anymore
