### ISSUE TITLE
[Feature Request] Provide search tool feature parity between Steam Client and Steam Website

### ISSUE THREAD

**Issue by SaltyBet** [ValveSoftware/steam-for-linux#11127]
#### Your system information

* Steam client version (build number or date): Latest Stable
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: N/A
* GPU: AMD

#### Please describe your issue in as much detail as possible:

- Steam client seems to be limited in the search options when compared to the Steam website search.
- Found out when trying to search for HDR compatible games on the Steam Client (no option whatsoever).
- See illustrative images at the end of the issue.

#### Steps for reproducing this issue:

1. Activate search tab on Steam client.
2. Go to search page on Steam website.
3. Visualize the discrepancy.

#### Comparison images:

**Search options on Steam Client**

![Search options on Steam Client](https://github.com/user-attachments/assets/61a1d34a-9c4a-4f7f-ba4b-8172b3c93421)

**Search options on Steam Website**

![Search options on Steam Website](https://github.com/user-attachments/assets/6fec420d-6c3d-4314-b2e5-4b6a9b7da49c)

**Comment by kisak-valve** [comment]
Hello @SaltyBet, you're comparing a Steam Library search to a Steam Store search. For the latter on Steam Deck, `Steam` button -> `Store` -> `Search Steam` in the top right -> Press `Y` to filter the search with the set you've screenshot.

**Comment by SaltyBet** [comment]
@kisak-valve sorry, my bad, I was definitely not clear.

What I meant to ask for was, effectively, to have the Library search include the complete set of options as the website search, mainly to use those options as a way to define more accurate Dynamic Collections.

Is that a sensible request? Should I open a new issue?

**Comment by kisak-valve** [comment]
I don't think it makes sense to have a broad spectrum request to force the Steam Library and the Steam Store to have the exact same structure. They're objectively separate for the purpose they serve.

If there's a specific search filter that you need, make that clear and we can repurpose this issue report to focus on that specific criteria.
