### ISSUE TITLE
Failure when opening screenshots/videos management window

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/steam-for-linux#11137]
```
Something went wrong while displaying this content. Refresh

Error Reference: Shared SteamUI_9068695_3f03af87cbea5b7e
Cannot read properties of undefined (reading 'toLocaleLowerCase')
```

Only happens the first time that I open a screenshots/videos management window after starting Steam. Something (in a script) being used before being assigned a value?

(Devuan stable, Steam build datestamp 1722028579.)

**Comment by grandemango** [comment]
I am having this problem every time i try to access my screenshots/video management. If you come across a fix please let me know.

**Comment by grandemango** [comment]
In case anyone sees this thread, downloading the steam installer and running it to the same file path your steam is already in, will repair your steam and fix the problem.

**Comment by dsalt** [comment]
> I am having this problem every time i try to access my screenshots/video management. If you come across a fix please let me know.

Whereas I'm seeing it only the first time; second and subsequent attempts succeed. **Which makes me think that you have a different (but similar) problem.**

> In case anyone sees this thread, downloading the steam installer and running it to the same file path your steam is already in, will repair your steam and fix the problem.

What, specifically, was changed by this?

**Comment by dsalt** [comment]
Re-tested with 1722380543 (for which this is listed as fixed). Working.
