### ISSUE TITLE
"Validating" pre-caching every time after a reboot

### ISSUE THREAD

**Issue by ziomek64** [ValveSoftware/steam-for-linux#11132]
Is it necessary that it's pre-caching every single time when I start steam after reboot? Why is it doing that exactly? Is there no other way to make it? Sometimes steam even does something for an hour for no reason(when there's no "validating" in steam) ,because CPU is constantly at 20% or something ,I don't think it takes that long.

I'm using CachyOS which is arch based.

**Comment by kisak-valve** [comment]
Hello @ziomek64, this issue is already being tracked at #6546. Closing as a duplicate.
