### ISSUE TITLE
[Feature request] the ability to claer cloud saves for certain games

### ISSUE THREAD

**Issue by Yasand123** [ValveSoftware/steam-for-linux#11147]
There's many games that don't allow you to delete saves, and steam doesn't have an option to clear the cloud, so you are forced to either completely disable cloud saves feature or have the saves suck permanently there and just deal with it.

## Specific example
Resident Evil 4 Remake. It doesn't have an option in-game to delete saves, and if you delete them manually from the folder, Steam simply re-downloads them. I now have no option but disable cloud saves feature altogether for a service I paid for.

I really think the user should be given this extremely basic feature. A simple button next to the toggle under STEAM CLOUD section in a game's properties that says "Clear saves for this game" or something along those lines.

**Comment by kisak-valve** [comment]
Hello @Yasand123, this request is already being tracked at #5900. Closing as a duplicate.
