### ISSUE TITLE
Expose `-forcedesktopscaling` via a settings option

### ISSUE THREAD

**Issue by mondalaci** [ValveSoftware/steam-for-linux#11156]
Or better yet, make the Steam client detect OS scaling. I'm using Linux Mint 22 with Cinnamon, and desktop scaling is set to 2, which the Steam client disrespects.

#### Your system information

* Steam client version (build number or date): 1721173382
* Distribution (e.g. Ubuntu): Linux Mint 22
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/user-attachments/files/16482926/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD Nvidia

**Comment by kisak-valve** [comment]
Hello @mondalaci, https://github.com/ValveSoftware/steam-for-linux/issues/5460#issuecomment-2253588058 takes priority here. Opt into Steam's client beta and if that new scaling control method isn't behaving as expected, then follow up with the SDL and/or Cinnamon dev(s).
