### ISSUE TITLE
Steam shows as SDL Application

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#11151]
#### Your system information

* Steam client version (build number or date): 1722380543
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: YEs
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16439255/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I think that with today's beta update (But not sure at all) the client window is showing up as SDL Application instead of just Steam

#### Steps for reproducing this issue:

1. Run regular Steam (steam-runtime on Arch) on a Gnome Wayland session

![Captura desde 2024-07-31 11-21-21](https://github.com/user-attachments/assets/7419988c-88f0-4b22-b1a1-1a1a2e02e6b5)
![Captura desde 2024-07-31 11-21-26](https://github.com/user-attachments/assets/7663a8bb-79a9-4fc9-9994-f4b1a6aa38a4)

**Comment by echaskaris** [comment]
July 30th steam beta did this

**Comment by rmbleeker** [comment]
The problem is not exclusive to Arch since I have it on Pop!_OS as well, which is a derivative of Ubuntu and falls within the Debian family of Linux distributions.

**Comment by ShlomoSerber** [comment]
This also happens to me on Ubuntu 22.04.4 LTS (
![Screenshot from 2024-08-01 23-30-06](https://github.com/user-attachments/assets/4c211e38-d045-47cd-9f54-78d62b51c436)
)
![Screenshot from 2024-08-01 23-27-22](https://github.com/user-attachments/assets/3e2b2efe-9853-43f2-8108-cf6f6359166a)

**Comment by ColbyB722** [comment]
Also on Fedora 40

**Comment by theme118** [comment]
It happens on EndeavourOS too.

@alosarjos It works with your workaround :clap:

**Comment by 70705** [comment]
Also on NixOS

**Comment by adcowley** [comment]
Just want to note I am also seeing this on Tumbleweed Linux after the July 30th beta update.

**Comment by NLBen** [comment]
Also present on Ubuntu 24.04 LTS. Also seems to make the client way more unstable for some reason, seeing a lot more hang-ups

**Comment by williamjcm** [comment]
Judging by what I can see, I think the change is also the reason why Steam now shows up separately from my pinned taskbar icon on KDE:
![image](https://github.com/user-attachments/assets/b3eec60d-cd4d-46a3-819a-5bd6710fa6b1)

Using Xorg, but I presume it'd do the same on Wayland.

**Comment by echaskaris** [comment]
Fixed with Aug 13 update

**Comment by williamjcm** [comment]
Can confirm it's fixed here too. The patch notes didn't mention it, though.

**Comment by NLBen** [comment]
Same here, restarting Steam and letting it apply the patch fixed the issue.

Seems also more stable currently for now compared to when the SDL version showed up. Any out-of-focus hang-ups which increased with SDL for now don't seem to occur (anymore?), but that bit would require some further testing if that was SDL-related or something deeper within the client.

**Comment by alosarjos** [comment]
Fixed
