### ISSUE TITLE
[Feature Request] Add an option to force PRIME unloading for all games

### ISSUE THREAD

**Issue by awsms** [ValveSoftware/steam-for-linux#11168]
AFAIK there is no way to do this. Either launch Steam with PRIME offloading, such as `prime-run steam-native`, or add `prime-run %command%` as a custom launch options for each game.
Both options are not ideal, the first one will allocate VRAM to Steam which means wasted VRAM. The second one is incredibly annoying if you have more than 5 games in your library.
Or even better, an option to pick a preferred GPU (Integrated/NVIDIA) for all titles.

**Comment by kisak-valve** [comment]
Hello @awsms, this request is already being tracked at #3453. Closing as a duplicate.

**Comment by awsms** [comment]
Hi kisak, thanks for the heads up.
