### ISSUE TITLE
Specific previously installed games on external device pointlessly try to reinstall on new systems/reinstalled systems

### ISSUE THREAD

**Issue by svin24** [ValveSoftware/steam-for-linux#11177]
#### Your system information

* Steam client version (build number or date): 1722380543
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] Yes 
* Have you checked for system updates?: [Yes/No]Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/user-attachments/files/16568946/steam-logs.tar.gz)
* GPU: AMD
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I have various games installed on an external hard drive, some of them windows games, some of them linux games. When i enabled proton support for all games on my reinstall of linux for some reason it tried to reinstall the games completely.
However the files are there and triggering a file validation check does nothing to fix the issue.

This seems to be mostly an issue with proton games ,particularly ones that have no full support and need to be enabled via the "enable steam play for all titles" setting.

I have also tried clearing all download cache.

#### Steps for reproducing this issue:

1. move games on an external hard drive
2. go on a new linux computer
3. install steam and connect the game library from the hard drive.

#### Additional info

My external drive is formatted as XFS
I also tried non beta steam

**Comment by kisak-valve** [comment]
Hello @svin24, you've described the issue being tracked at #5901. Closing as a duplicate.
