### ISSUE TITLE
Steam link falls back to software encoding with Nvidia drivers >535

### ISSUE THREAD

**Issue by Jcwscience** [ValveSoftware/steam-for-linux#11176]
Disros tested (Arch, Manjaro, Ubuntu)

Any recent steam version, stable and beta

Drivers tested (550.107.02, 555.08.02, 560.31.02) open and proprietary

Desktop environments tested (KDE Plasma, Gnome, lxqt) X11 and Wayland

The error occurs when steam attempts to create an NVENC pipeline. Based on the drivers that have this error I believe it may be related to the removal of legacy encoding profiles in recent releases.

See https://docs.nvidia.com/video-technologies/video-codec-sdk/12.2/nvenc-preset-migration-guide/index.html

I am still working on isolating the exact failure point, so this may not be the issue.

**Comment by kisak-valve** [comment]
Hello @Jcwscience, this issue is already being tracked at #10984. Closing as a duplicate.
