### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by debil2004** [ValveSoftware/steam-for-linux#11170]
I think Steam should be using QT. Why? Because I can't access Steam for 2 months. Modern software development requires stability, why do all companies use idiotic systems like chromium and electron, steam uses its own embedded browser. Only Tesla uses the QT framework in their cars and guess what?  It runs smoothly and without any problems. Why do I have to put up with constant problems, why can't I just use the application as intended? Why do I have to keep coming to this page looking for solutions to my problems? Why do I have to endlessly open my terminal emulator and jerk steam -def-disable-gpu steam -system-composer steam -reset??????

**Comment by kisak-valve** [comment]
Hello @debil2004. this request is already being tracked at #7454. Closing as a duplicate.
