### ISSUE TITLE
Vac unable to verify game session

### ISSUE THREAD

**Issue by charmpitz** [ValveSoftware/steam-for-linux#11172]
#### Your system information

* Steam client version (build number or date): 1721173382
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: [Yes/No] I don't know, it says `Steam Beta Branch:  Stable Client`
* Have you checked for system updates?: [Yes/No]  Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/user-attachments/files/16563779/steam-logs.tar.gz)

* GPU: Nvidia 4070

#### Please describe your issue in as much detail as possible:
When I try to play I receive `Vac unable to verify game session`. I reinstalled the game a couple of times and verified installation files a lot. I also purged Steam from the system, reinstalled and still doesn't work.
What works though is creating a new account and playing on it. I think it is something related to my account configuration that gets synced in the cloud.. Let me know if I can provide any other details..

#### Steps for reproducing this issue:

1. Open the game
2. Hit play, choose any Matchmaking mode and Start
3. Receive `Vac unable to verify game session`

**Comment by kisak-valve** [comment]
Hello @charmpitz, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3408.

Closing as a duplicate.
