### ISSUE TITLE
Dota 2 crash in Manjaro

### ISSUE THREAD

**Issue by BEbrik123** [ValveSoftware/steam-for-linux#11178]
#### Your system information

* Steam client version (build number or date): Wed, Jul 17 4:22 AM UTC +05:00
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]ar (child): /home/nejet8/Desktop/steam-logs.tar.gz: Функция open завершилась с ошибкойtar: Удаляется начальный `/' из имен объектов
: Нет такого файла или каталога
tar (child): Error is not recoverable: exiting now
tar: /home/nejet8/Desktop/steam-logs.tar.gz: Функция write завершилась с ошибкой: Обрыв канала
tar: Child returned status 2
tar: Error is not recoverable: exiting now
zsh: Отказано в доступе: /home/nejet8/.steam/steam/logs/

* GPU: Nvidia/Intel/AMD Nvidia 540M Notebook

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist]
the game crashes when I launch it with proton, and if without it my video card does not support Vulcan, the version of proton me (Dota 2 game)

#### Steps for reproducing this issue:

1. I click play (with proton)
2. Waiting
3. Dota 2 crash

**Comment by kisak-valve** [comment]
Hello @BEbrik123, both Dota 2 (native) and Proton require the video driver to support Vulkan. Sorry, but your Fermi generation GPU has no video driver that provides that and is not supported.
