### ISSUE TITLE
Buttons stop working after exiting a non-steam game

### ISSUE THREAD

**Issue by jamescastells** [ValveSoftware/steam-for-linux#11188]
#### Your system information

* Steam client version: 1723685248
* SteamOS version: 3.5.19
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After exiting a non-steam game added to the SteamOS interface, the buttons stop working until I hit the Steam menu button.

#### Steps for reproducing this issue:

1. Add a non-steam game to SteamOS.
2. Enter the game.
3. Exit the game.
4. The buttons now don't respond until you hit the Steam menu button.

**Comment by kisak-valve** [comment]
Hello @jamescastells, you've described an issue with the Steam client instead of SteamOS as a platform, so I've transferred this issue to the steam-for-linux issue tracker for a Steam dev to ponder.

**Comment by samend13** [comment]
I don't think my issue is quite the same thing, it starts being a problem the moment you open a game (can be seen in the overlay) and persists throughout the entire interface, even after working around this one by pressing the menu button

**Comment by Labestiajake** [comment]
Still bug in version 1725412627

**Comment by Labestiajake** [comment]
Works without problems in : 1726025281
Great work.

**Comment by jamescastells** [comment]
I can confirm version 1726025281 fixes this issue.
