### ISSUE TITLE
Steam (Runtime) on Arch Linux has massive interface tearing in web/ui elements.

### ISSUE THREAD

**Issue by Oroborius** [ValveSoftware/steam-for-linux#11185]
#### Your system information

* Steam client version (build number or date): 0.20240610.0+srt1
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] [https://www.mediafire.com/file/0tyxfqwiuumtliz/steam-logs.tar.gz/file](steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD Nvidia

#### Please describe your issue in as much detail as possible: Steam (Runtime) installed with `sudo pacman -S steam` ends up looking like this. Resizing it fixes the issue for that specific page.
![image](https://github.com/user-attachments/assets/cb84509c-6b29-4046-a66b-0c511d4f85dd)

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Expected to see a store page instead the page looks like it's been shredded to bits.

#### Steps for reproducing this issue:

1. `sudo pacman -S steam`
2. `steam` or use the `.desktop`
3. Witness horror.

**Comment by kisak-valve** [comment]
Hello @Oroborius, this issue is already being tracked at #10537. Closing as a duplicate.
