### ISSUE TITLE
Steam stuck on "Loading User Data" screen

### ISSUE THREAD

**Issue by cblinq** [ValveSoftware/steam-for-linux#11181]
#### Your system information

* Steam client version (build number or date):  steam-1.0.0.79-2
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: I got some logs before it actually loaded, I will attach them.
[steam-logs.tar.gz](https://github.com/user-attachments/files/16576030/steam-logs.tar.gz)

* GPU: Nvidia RTX 4060 Laptop

#### Please describe your issue in as much detail as possible:
Sometimes launching Steam is fast, sometimes I thought it was never gonna load, until I started writing this issue it actually loaded after a few mins.. 3-4 minutes my guess, I also saw something similar here https://github.com/ValveSoftware/steam-for-linux/issues/9769 but their loading screen freezes, mine doesn't, and eventually loads.

#### Steps for reproducing this issue:

1. Launch Steam
2. It auto logs-in and then comes the Loading User Data loading screen
3. Loading User Data loading screen takes a while (this is not happening all the time, but it recently started for me)

**Comment by cblinq** [comment]
Latest steam update seems to have fixed this issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.
