### ISSUE TITLE
ERROR: ld.so: object '/run/host/usr/lib/libfreetype.so' from LD_PRELOAD cannot be preloaded 

### ISSUE THREAD

**Issue by als-creator** [ValveSoftware/steam-for-linux#11187]
OS: Arch Linux (x86_64)
Kernel: Linux 6.10.4-1-cachyos
DE: Xfce4 4.18
Shell: zsh 5.9
CPU: AMD A10 PRO-7800B R7, 12 Compute Cores 4C+8G (4) @ 3,50 GHz
GPU: AMD Radeon R7 Graphics [Discrete]
OpenGL: 4.5 (Compatibility Profile) Mesa 24.1.6-arch1.1
Board: Bantry CRB (NOK)
steam log torchlight 2 https://pastebin.com/NmMgRSPD i use LD_PRELOAD=/usr/lib/libfreetype.so %command% for game start
start Torchlight without LD_PRELOAD=/usr/lib/libfreetype.so %command% https://pastebin.com/MM98fnZF
driver:    
local/amd-ucode 20240809.59460076-1
    Microcode update image for AMD CPUs
local/lib32-vulkan-radeon 1:24.1.6-1
    Open-source Vulkan driver for AMD GPUs - 32-bit
local/vulkan-radeon 1:24.1.6-1
    Open-source Vulkan driver for AMD GPUs
local/xf86-video-amdgpu 23.0.0-2 (xorg-drivers)
    X.org amdgpu video driver

**Comment by kisak-valve** [comment]
Hello @als-creator, you're mixing Arch-specific advice meant for the Linux native variant of Torchlight II while having Steam configured to run the Windows variant of the game. This isn't a Steam client issue.

**Comment by als-creator** [comment]
But I attached the log without using the parameters to launch the game in the second case, judging by the page in the store, this game has native linux support, why doesn’t the game launch in the second case?
