### ISSUE TITLE
Proton Experimental - Gamepad Disconnect / Reconnect Regression

### ISSUE THREAD

**Issue by jSQrD-dev** [ValveSoftware/steam-for-linux#11182]
Operating System: EndeavourOS 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.3-zen1-2.1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7800X3D 8-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: AMD Radeon RX 7800 XT
Manufacturer: ASRock
Product Name: B650E Taichi Lite

Steam Beta Branch:  Steam Beta Update
Steam Version:  1722380543
Steam Client Build Date:  Tue, Jul 30 17:44 UTC -06:00
Steam Web Build Date:  Tue, Jul 30 17:44 UTC -06:00
Steam API Version:  SteamClient021

Have you checked for system updates?: Yes
Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16576774/steam-logs.tar.gz)

There seems to be a regression on how proton handles controller/gamepad disconnects in Proton Experimental. Once a controller/gamepad disconnect it can not be reconnected until full restart of the game running. Similar to Issue #9150. 

#### Steps for reproducing this issue:

1. Run game under Proton Experimental
2. Disconnect controller/gamepad ( by accident, loose coneection, etc.)
3. Reconnect controller/gamepad

**Comment by jSQrD-dev** [comment]
Added Context 

This was notice after the issue was resolved by choosing a different Proton version (ie. Proton 9.0-2)

**Comment by kisak-valve** [comment]
Hello @jSQrD-dev, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/7952.

Closing as a duplicate.
