### ISSUE TITLE
Text-to-speech (TTS) does not appear in games running through Proton

### ISSUE THREAD

**Issue by hazelthatsme** [ValveSoftware/steam-for-linux#11196]
#### Your system information

* Steam client version (build number or date): 1721173382
* Distribution (e.g. Ubuntu): Fedora Linux 40 (Everything spin, kernel 6.10.4)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, there are none.
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16658856/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
No options for TTS appear in Proton games, like Overwatch 2;
![image](https://github.com/user-attachments/assets/4b1d2444-cf4c-4c45-b7df-a5a74e117128)

#### Steps for reproducing this issue:
1. Open game with Proton,
2. Navigate to the game's Accessibility options,
3. No TTS options appear.

**Comment by hazelthatsme** [comment]
Note: TTS library Flite is installed, and voices are available through it:
![image](https://github.com/user-attachments/assets/50310af3-bfa6-4341-b7ac-19e02c4a5092)

**Comment by kisak-valve** [comment]
Hello @hazelthatsme, we're tracking issues with games run with Proton in the Proton issue tracker. Also, this type of issue needs to be evaluated on a per-game basis and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7033#issuecomment-2296455784.
