### ISSUE TITLE
Steam on distributions other than Ubuntu

### ISSUE THREAD

**Issue by Leandro599** [ValveSoftware/steam-for-linux#11190]
Hello, I wanted to clarify doubts, please don't be mad:
Currently, what would be the safest way recommended by Valve to run Steam on distributions other than Ubuntu?

I saw that there is a Steam flatpak, also distro prepared for games with Steam already included, etc.

😄

**Comment by kisak-valve** [comment]
Hello @Leandro599, there's no broad-spectrum recommendation for an unspecified distro, but in general, a distro's package maintainers should have made minor adjustments to the Steam package they provide for it to work well on their distro.

**Comment by Leandro599** [comment]
ok, thanks 😄
