### ISSUE TITLE
Problems with using a secondary drive on Mint

### ISSUE THREAD

**Issue by Maytriss** [ValveSoftware/steam-for-linux#11193]
#### Your system information

* Steam client version (build number or date): Steam Version:  1721173382
* Distribution (e.g. Ubuntu):  Mint
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16647853/steam-logs.tar.gz)

* GPU: AMD
* 
I've been trying to use my new HDD to store my games but have struggling to actually do this.

When added as a drive it is treated as an external drive and when you browse the local folders for the drive through steam it points to a completely different directory than if you were to manually go to the library. If you try to install a game to that drive it will display a disk write error and fail. A Linux supported game can be moved to the secondary drive and be played without any issue until Steam is restarted then it would have forgotten any games that would have been stored on the secondary drive. Any games transferred to the secondary drive are still on the secondary drive.

When checking the Libraryfolders.vdf it will list the file directory that you are taken to when you browse the local folder which is:
(run/user/1000/doc/11ba79f7/stream-drive"). When helped with changing the libraryfolder.vdf file to the correct file path and adding the appmanifests that are on the secondary drive only removed the drive from storage all together.

**Comment by polluxau** [comment]
Remount the drive with something like gnome disks, mine is mounted under /games and /extragames, then this problem should be fixed, pretty sure linux automatically mounts drives in a temporary place that steam struggles to understand properly

**Comment by Maytriss** [comment]
yeah... I was already using gnome disks to mount my drive just named Mintchan and mounted under /mnt/stream-drive

**Comment by polluxau** [comment]
> yeah... I was already using gnome disks to mount my drive just named the drive Mintchan and mounted under /mnt/stream-drive

Try not mounting the drive under mnt thats a temporary place

**Comment by Maytriss** [comment]
Turns out it was a permission issue as I installed a program called Flatseal which I then told Flatseal that Steam can mess around with the drive/ file system I was trying to point it out and that seems to have fixed the issues I was having. Thank you for your help
