### ISSUE TITLE
Browser component goes blank shortly after switching workspaces

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/steam-for-linux#11198]
1. Run Steam.
2. Ensure that the library is displayed.
3. Ensure that a web page (store, activity; doesn't matter what) is displayed – important thing is that steamwebhelper is active.
4. Switch to another workspace.
5. Switch back.
6. **Observe that the browser content part of the window becomes blank (black) after maybe a second.** (The frame & controls *remain visible*.)
7. Go back a page then go forward a page.
8. Notice that the content is once more displayed.
9. Hide the window (minimise; don't switch workspace).
10. Show the window (unminimise).
11. Observe that the content *remains displayed*: the bug does not occur.

This also affects the separate web view window, except there restoration is done by switching to another tab then back again.

This bug first appeared over a year ago. I didn't report separately at the time because it would very likely be swamped with confusion regarding other browser content-hiding bugs; and it wasn't obvious that the bug is separate.

Devuan daedalus, Xfce4. Accelerated rendering makes no difference.

I was watching logged messages while doing this (`tail *.txt` in `Steam/logs`), and the following is what got logged in `webhelper.txt` when the blanking happened:
```
[2024-08-20 01:37:26] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1024x768
[2024-08-20 01:37:26] SP Desktop_uid0-'Steam': WasHidden 1: (0, 0) 1024x768
[2024-08-20 01:37:26] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1024x768
[2024-08-20 01:37:26] SteamBrowser-'Welcome to': WasHidden 1: (1, 92) 1022x625
[2024-08-20 01:37:26] SteamBrowser-'Welcome to': WasHidden 0: (1, 92) 1022x625
[2024-08-20 01:37:27] SP Desktop_uid0-'Steam': WasHidden 0: (0, 0) 1024x768
```

**Comment by kisak-valve** [comment]
Hello @dsalt, this issue is already being tracked at #10869. Closing as a duplicate.
