### ISSUE TITLE
problem with cs2 on linux

### ISSUE THREAD

**Issue by didakaherpes** [ValveSoftware/steam-for-linux#11194]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. in cs2 when i move my mouse in the menus is completely fine but when i actually play the game its delayed if i move my mouse slightely but when i move it agressively its kind of ok
2. i dont under why this bug happens and it only happens on linux ive used both mint and ubuntu and both of them have done the same thing but when i used my windows 11 its how its supposed to be
3. please tell me how i can fix this one of things might help is how i can turn raw input in steam
4. 
5.

**Comment by kisak-valve** [comment]
Hello @didakaherpes, this issue already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3342.

Closing as a duplicate.
