### ISSUE TITLE
gldriverquery leaves an inhibitor lock on the system until logout

### ISSUE THREAD

**Issue by Jonathing** [ValveSoftware/steam-for-linux#11207]
#### Your system information

* Steam client version (build number or date): 1724453533 Beta
* Distribution (e.g. Ubuntu): [Nobara Linux 40](https://nobaraproject.org/) (Fedora modified)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16737926/steam-logs.tar.gz)
* GPU: AMD Radeon RX 7700S (Framework Laptop 16 dGPU)

*This bug is also present in the stable version of the Steam client.*

#### Additional Info

* KDE Plasma 6.1.3
* KDE Frameworks 6.4.0
* Qt 6.7.2
* Kernel 6.10.3-201.fsync.fc40.x86_64
* Graphics Platform Wayland

#### Please describe your issue in as much detail as possible:

One day, after leaving my laptop on without manually locking or putting to sleep, I returned home to notice that it was still powered on, and the monitors (both internal and external) had neither dimmed nor turned off. When I checked the battery widget, I had noticed that there were two inhibitor locks on my system, both from an unknown application.

![Battery widget showing two instances of "My SDL application: Playing a game"](https://discuss-cdn.kde.org/uploads/default/original/2X/b/ba7c52929cfb2712a432ea154b5f947d9ad1a44d.png)

Note that when an application does not supply its own name and reason, [these are the default values that SDL uses.](https://github.com/libsdl-org/SDL/blob/a2d3be904b219e4257fb11a8ecb51f5f9a9e60f7/src/core/linux/SDL_dbus.c#L372-L377)

I went onto KDE Discuss with the thought that KDE itself might be the problem, and also since KDE does not tell me the source application of the inhibitor lock. After some discussion, I was able to write a few bash scripts to run at startup in order to figure out what is placing the inhibitor locks on my system.

The first script below will simply output the results of dbus-monitor to a file in the downloads folder, acting like a log file:

```bash
#!/bin/bash
dbus-monitor "interface='org.freedesktop.ScreenSaver'" > $HOME/Downloads/dbus-monitor.txt
```

The second script takes each line from dbus-monitor and uses some weird regex to extract the sender string so it can be parsed to find the sender information. From the sender information, I then find the command line used to spawn the process ID from the sender information. All lines generated from the script are then outputted to another text file acting like a log:

```bash
#!/bin/bash
dbus-monitor "interface='org.freedesktop.ScreenSaver'" | \
while read line ; do
    sender_value=$(echo "$line" | grep -oP 'sender=\K[^ ]+')
    if [ $? = 0 ]
    then
        echo $( cat /proc/$(dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetConnectionUnixProcessID string:"$sender_value" | grep -oP 'uint32 \K\d+')/cmdline | tr '\0' ' ' ) >> $HOME/Downloads/dbus-processes.txt
    fi
done
```

Here is the resulting “log” file of the second script:

```
/usr/bin/dbus-broker-launch --scope user
/usr/bin/dbus-broker-launch --scope user
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_64/gldriverquery
/usr/bin/xdg-dbus-proxy --args=43
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_64/gldriverquery
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_64/gldriverquery
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_32/gldriverquery
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_32/gldriverquery
/home/jonathing/.local/share/Steam/ubuntu12_32/../ubuntu12_32/gldriverquery
```

So from what it looks like, `gldriverquery` is placing an SDL inhibitor lock without ever asking it to uninhibit the system. So even after the connection is lost when `gldriverquery` is closed, the lock is never lifted. I think that this is very bad.

#### Steps for reproducing this issue:

1. Open Steam
2. The system will no longer go to sleep or lock on its own, even after fully closing Steam.

Here is the thread on KDE Discuss I created where I initially asked for help regarding this bug. Note that due to the nature of it, I was unaware that this was a Steam bug at the time, and did not believe Steam had a part in it.
https://discuss.kde.org/t/my-sdl-application-is-inhibiting-screen-lock/20273

**Comment by Jonathing** [comment]
Hey good evening. I'm not convinced as to close this yet, but I noticed that after resetting and re-installing steam (the entire runtime including the ubuntu runtime), the SDL locks are no longer being set on my system. I wonder if it was an issue with a faulty `gldriverquery`?

In any case, there have been times where Steam would boot and this problem didn't occur. I'll let you know in a few days and if I don't encounter this issue again, I'll close this.

**Comment by TTimo** [comment]
There was a recent fix for `gldriverquery` crashing during shutdown. Maybe that has an impact on this? If this lock is negotiated via dbus, shouldn't the setup be smart enough to lift the lock if the process dies?

**Comment by Jonathing** [comment]
I'm not sure. In any case, even after a recent reset of the runtime, I have now begun receiving these locks on my system again. 'twas a good day without them, yesterday was.
![image](https://github.com/user-attachments/assets/c2a6dbf4-a1fd-4f85-b9e4-fe23bca525f0)

**Comment by TTimo** [comment]
You can set `SDL_VIDEO_ALLOW_SCREENSAVER=1` to stop SDL from disabling the screensaver.

We will add this hint to `gldriverquery` - it shouldn't disable the screensaver in the first place it's a very short lived process.

We assume this happens because `gldriverquery` is still crashing for you, either you are running an old build or have some other issue causing this (https://github.com/ValveSoftware/steam-for-linux/issues/11052).

DBus not being resilient to process crashes seems like a shortcoming of the API though. But that's not us.

Note that unrelated to this the Steam client will also prevent the screensaver from kicking in: https://github.com/ValveSoftware/steam-for-linux/issues/5607

**Comment by Jonathing** [comment]
Yeah, though the Steam client is actually identifying itself when it places an inhibitor lock on my system. When the Steam client is closed and minimized to tray, I do not have the problem of it trying to inhibit screen lock on my system. My issue is solely with `gldriverquery`. Is there a way to find logs of that process in particular?

**Comment by Jonathing** [comment]
Closing this issue in favor of #11052 and because the discussion surrounding it provides decent workarounds to the problem I've been having. Launching Steam with `SDL_VIDEO_ALLOW_SCREENSAVER=1` prevents SDL-specific inhibitor locks from being placed on my system which solves this problem for me. While it's possible that `gldriverquery` might still be crashing for me, it hasn't caused any issues outside of the lock problem that I opened this issue for, so I'll just hope that some update fixes it eventually.

For anyone who might come across this problem in the future, I wrote this script (for KDE) that cleans up any and all dbus inhibitor locks on the system for scenarios like this:
```bash
#!/bin/bash

kdialog --warningyesno 'This script will clear all inhibitor locks placed on the system. Are you sure you want to do this?'
if [ $? -eq 0 ]; then
    for i in {1..403} ; do echo -n "$i " ; qdbus org.freedesktop.PowerManagement /org/freedesktop/PowerManagement/Inhibit org.freedesktop.PowerManagement.Inhibit.UnInhibit $i ; done
    kdialog --msgbox 'Inhibitors have been cleaned up.'
fi
```
