### ISSUE TITLE
quake champions vulkan shaders processing very long

### ISSUE THREAD

**Issue by olaulau** [ValveSoftware/steam-for-linux#11201]
#### Your system information

* Steam client version (build number or date): 1721173382
* Distribution (e.g. Ubuntu): debian testing
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* GPU: Nvidia rtx4060ti (535)

#### Please describe your issue in as much detail as possible:
processing vulkan shaders is usually long, but is very very long for quake champions (about an hour)

**Comment by kisak-valve** [comment]
Hello @olaulau, this is not a bug by itself. Some games have millions of shaders and it takes that long to run them through your video driver to warm the driver-specific on-disk shader cache.

**Comment by olaulau** [comment]
maybe some optimizations are needed ?
not being able to run a game ina  decent time for a technical reason si a bug, from the user point of view.
especially when having a decent computer !

**Comment by kisak-valve** [comment]
Those optimizations would primarily be in the video driver's shader compiler. On Steam's side, there's a setting to let it process shaders in the background so that it can work ahead of asking the game to start.
