### ISSUE TITLE
Stuck on login window unless launching with `-tcp` argument.

### ISSUE THREAD

**Issue by drwhut** [ValveSoftware/steam-for-linux#11219]
#### Your system information

* Steam client version (build number or date): 1721173382
* Distribution (e.g. Ubuntu): Linux Mint 22
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16801895/steam-logs.tar.gz)
* GPU: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER]

#### Please describe your issue in as much detail as possible:
All of a sudden, when launching the client normally, Steam will not get past the login window.

When launching Steam via a terminal, this error message can be seen:
```
src/clientdll/cminterface.cpp (3556) : m_VecAddressWebSocketCMs.Count()
src/clientdll/cminterface.cpp (3556) : m_VecAddressWebSocketCMs.Count()
assert_20240829170431_29.dmp[11754]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240829170431_29.dmp
assert_20240829170431_29.dmp[11754]: Finished uploading minidump (out-of-process): success = yes
assert_20240829170431_29.dmp[11754]: response: CrashID=bp-4a1ef766-89f0-4970-b79e-e724b2240829
assert_20240829170431_29.dmp[11754]: file ''/tmp/dumps/assert_20240829170431_29.dmp'', upload yes: ''CrashID=bp-4a1ef766-89f0-4970-b79e-e724b2240829''
```

However, when launching Steam with the `-tcp` argument, it launches correctly as before.

#### Steps for reproducing this issue:

1. Launch Steam normally through the desktop environment.
2. See that the login window appears, but it does not continue.

**Comment by kisak-valve** [comment]
Hello @drwhut, this issue is already being tracked at #11216. Closing as a duplicate.
