### ISSUE TITLE
CS2 is unplayable on linux. Native has worse performance than proton but proton isn't playable on vac servers

### ISSUE THREAD

**Issue by CubanMathExpert** [ValveSoftware/steam-for-linux#11239]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Mint
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]

* GPU: Nvidia/Intel/AMD (Nvidia RTX 2060)

#### Please describe your issue in as much detail as possible: I have tried playing cs2 and I get ALOT of stuttering and fps drops. I played around with the graphics drivers and that didn't help. Then I saw some people were playing the game running it with proton and that won't let me connect to vac servers so there's no point in using that (although the performance was significantly better using proton). But in general the native version of the game is unplayable for someone who wants to be competitive. 
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Just running the game (native) has terrible performance
2. 
3.

**Comment by kisak-valve** [comment]
Hello @CubanMathExpert, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3325. Closing as a duplicate.
