### ISSUE TITLE
Random window(s) spawning, while getting a notification, hovering over a friend menu, or when closing a window

### ISSUE THREAD

**Issue by XCroatoanX** [ValveSoftware/steam-for-linux#11235]
#### Your system information

* Steam client version (build number or date): 1724878532
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Every time, you hove a cursor at some window, or close some window, there are random black/transparent window (or multiple windows) spawning. This makes using steam unpleasant, and even irritating, while using the friend menu. Also, when you get a notification, during the moving down of it, it spawns a black/transparent window too, which steals the focus. This is insanely irritating during playing a game. Also, it happens, when you use steam overlay and close a window of the browser or a chat. The game just minimizes (both full-screen, windowed and full-screen borderless). This happens both in Beta and Stable.

#### Steps for reproducing this issue:

1. Open a chat window, or right-click a person or get a notification
2. wait for the closing of a notification, or hover over a menu with an arrow
3.  Random windows spawn, and steal the attention, if you use any other window.

I pinned some videos as demonstration of the issue

https://github.com/user-attachments/assets/5cda12a1-2300-4cc8-9979-0906ba6ab93b

**Comment by XCroatoanX** [comment]
Upd: here are the logs
[steam-logs.tar.gz](https://github.com/user-attachments/files/16855599/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @XCroatoanX, this issue is already being tracked at #10758. Closing as a duplicate.
