### ISSUE TITLE
Steam SHOULD NOT demand user-namespace

### ISSUE THREAD

**Issue by sipaktli** [ValveSoftware/steam-for-linux#11238]
Recently you have started to demand the use of unprivileged namespaces (UNs) without providing any technical rationale for it.

You have provided the following link as a justification, but what is says is basically "modern systems use flatpak so it must be cool". That is not a valid technical reason.
https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#kernelunprivileged_userns_clone

1) The runtime has been running fine thus far without requirement for unprivileged namespaces, so I still fail to see why it is randomly necessary now.
2) Now, that's the runtime, but why should the native client require UNs???

The use of UNs leaves the system vulnerable to a plethora of vulnerabilities. The extent of which being so that it does not justify you requirement. 

Basically you have gone the nuclear option, and I will assume malicious intent unless you can provide a valid technical justification.ac

**Comment by kisak-valve** [comment]
Hello @sipaktli, please do not intentionally open duplicate issue reports. You were given a straight answer that there is an alternative available by using a setuid-root variant of bwrap on #11237. If you have further concerns with bwrap, then direct that feedback at the upstream bubblewrap project.

Closing as a duplicate of #11237.

**Comment by sipaktli** [comment]
setud is even worse... You are not understanding, or even trying to understand the issue (kind of expected).

And I did not open a duplicate, you are closing the tickets without proper feedback or solution.
