### ISSUE TITLE
[Feature Request] A separate Steam settings menu for forcing a discrete GPU, MangoHUD, and Gamemode on every Steam game

### ISSUE THREAD

**Issue by KingKrouch** [ValveSoftware/steam-for-linux#11244]
If there's one thing Steam desperately needs on Linux, it's a settings menu that shows Linux specific options _(depending on what dependencies are installed)_. Ideally, things like forcing games globally to use the discrete GPU on a laptop, forcing gamemode globally _(which has CPU scheduler changes and inhibits sleep mode)_, using Mangohud as a performance overlay (like how the Steam Deck game mode functions) instead of Steam's own internal FPS overlay, and per-game gamescope resolution and scaling options (on desktop mode where it's not accessible without launch parameters, rather than game mode on the Deck where it's forced).

I have a discrete GPU on my laptop, and I'm tired of having to remember to adjust the launch parameters for every game I play to ``DRI_PRIME=1 gamemoderun %command%``, so I can have the correct GPU being used by the game and to inhibit sleep mode from occurring on KDE Plasma when I use a controller. 

The problem is if I attempt to run steam with the DRI_PRIME=1 parameter beforehand _(so I don't have to adjust this on a per-game basis)_, that causes crashing issues with the Steam Web Helper that runs the client's UI, but it doesn't crash when it's handled on a per-game basis.

Your average person probably wouldn't know how to fix these issues, and then get frustrated at playing games on Linux as a result, when third-party game launchers _(Like Heroic and Lutris)_ already have these options available. Assuming the discrete GPU thing is made a simple toggle, it would work more consistently than Windows _(Where I often have to adjust per-executable GPU settings to get it on the right GPU)_. This kind of settings menu would be such a massive quality of life change for Steam and gaming on Linux.

**Comment by kisak-valve** [comment]
Hello @KingKrouch, this request is already being tracked at #3453. Closing as a duplicate.

**Comment by Leandro599** [comment]
top
