### ISSUE TITLE
Steam deck startup customization doesn't work after new update stable channel 11th September 

### ISSUE THREAD

**Issue by Kamui96** [ValveSoftware/steam-for-linux#11253]
#### Your system information

* Steam client version (build number or date): 20240422.1
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expect that the custom startup movie to apply to the boot of the system when it was completely turned off. What I am experiencing is the lack of startup movie when the system is turned on. It only shows the startup movie when, from sleep, it wakes up the Steam Deck. This happened after the stable release of September 11th.

**Comment by waspennator** [comment]
I can confirm the same issue happens on my le 1tb oled deck and it only started happening with this update. (I use the oled boot movie) apparently the default lcd steam deck boot movie kinda works checking around.

**Comment by waspennator** [comment]
Update: I can confirm the issue fixes itself if I change it back to the default boot movie (startup), it seems like changing it to any of the boot movies from the point shops (or custom ones), just fail to play period unless you preview them in the customization tab.

**Comment by waspennator** [comment]
Curious if this on the beta client fixes the issue.

"Fixed startup movie intermittently failing to play at launch."

**Comment by Kamui96** [comment]
Solved with the new stable release of the 17th of September.
