### ISSUE TITLE
Postal 2: letter inputs are scrambled

### ISSUE THREAD

**Issue by PimpOfSune** [ValveSoftware/steam-for-linux#11256]
#### Your system information

* Steam client version (build number or date): 1726256783
* Distribution (e.g. Ubuntu): Ubuntu 24.04.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17002171/steam-logs.tar.gz)
* GPU and other system specific details: https://gist.github.com/PimpOfSune/20d6b2b391daadf70ce827232060ac64

#### Please describe your issue in as much detail as possible:
Regardless of what I do, keybinds with letters don't work in the game, ever. WASD don't move me anywhere, G won't do a birdie, etc.

If I try to rebind some manually, key presses detected by the game are not matching keys I actually press.
Like, if I hit W - game says it's F for some reason o_o

All other (i. e. non-letter) keybings, like jumping with Space and inventory usage with Tab, are working fine.

That's completely fresh game install.
Ubuntu 24.01.1 x64 . en_US Linux interface - but with non-en_US (ru_RU in my particular case) date/time/currency formatting.
Messing around with Player.ini did no good. Nor did trying to force en_US keyboard layout prior to game start.
I'm fairly certain that the game worked fine like six months ago (or a bit earlier)... but rollback to older versions of the game does nothing.
And I got a similar problem with [American Truck Simulator](https://github.com/ValveSoftware/steam-for-linux/issues/11257) recently, which I'll post in a separate issue.

#### Steps for reproducing this issue:

Run native Postal 2 of latest version w/ all DLCs.
Load into the game and try to walk around.
Then try reconfiguring controls. See scrambled inputs.

**Comment by PimpOfSune** [comment]
Outputs from two specific locale related commands from terminal. Feel free to delete this comment if it's redundant.

locale
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```

localectl
```
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=ru_RU.UTF-8
               LC_TIME=ru_RU.UTF-8
               LC_MONETARY=ru_RU.UTF-8
               LC_PAPER=ru_RU.UTF-8
               LC_NAME=ru_RU.UTF-8
               LC_ADDRESS=ru_RU.UTF-8
               LC_TELEPHONE=ru_RU.UTF-8
               LC_MEASUREMENT=ru_RU.UTF-8
               LC_IDENTIFICATION=ru_RU.UTF-8
    VC Keymap: (unset)                      
   X11 Layout: us
    X11 Model: pc105
```

**Comment by PimpOfSune** [comment]
The problem was fixed (kinda) by swapping input sources, making en_US topmost:
![Screenshot from 2024-09-16 20-36-27](https://github.com/user-attachments/assets/7f8004f8-0acc-4466-a47c-1d9ec2584e53)
While topmost input source is ru_RU (or whatever causes the bug for you), launched game still ignores ALL letters regardless of currently selected keyboard layout.
As prefering (often inaccurate) list in settings over currently-selected layout is probably 100% game's fault, this issue can probably be closed.
And maybe deleted.

**Comment by kuromaku7** [comment]
Had the same issue, thank you very much for suggestion
