### ISSUE TITLE
Steam Big picture mode laggy on latest stable update

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#11261]
#### Your system information

* Steam client version (build number or date):   1726256783
* Distribution (e.g. Ubuntu):  Manjaro
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/user-attachments/files/17004861/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD
RX 6700XT

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam big picture mode is slow and laggy after latest update, I have GPU acceleration on 

![image](https://github.com/user-attachments/assets/a1cc0763-3de5-4ae7-b8a3-4eacfe7c8a89)

https://github.com/user-attachments/assets/10ec0007-5a86-4da7-930e-b4b12a19b4d4

I even fully reset Steam as I was on the beta version for the family share feature and it still is laggy, I am also experiencing the same issue on my Ryzen 7 5700U laptop with Radeon graphics

**Comment by tnbp** [comment]
This is likely bug #11255.

**Comment by kisak-valve** [comment]
Hello @coreybruce, as @tnbp noted, this issue is already being tracked at #11255. Closing as a duplicate.

**Comment by Zolfbs** [comment]
I'm also having the same issue on Ubuntu 24.04.1 Valve finally fixed the "Steam is not responding" issue that kept happening, but now this new problem has come up. I tried disabling hardware acceleration and enabling/disabling the GPU blocklist, but unfortunately, nothing works
