### ISSUE TITLE
Left clicks not registered in Wishlist->Sort By drop down box.

### ISSUE THREAD

**Issue by lvl20** [ValveSoftware/steam-for-linux#11280]
#### Your system information

* Steam client version (build number or date): 
> Steam Beta Branch:  Stable Client
> Steam Version:  1726604483
> Steam Client Build Date:  Tue, Sep 17 1:03 PM UTC -08:00
> Steam Web Build Date:  Mon, Sep 16 4:12 PM UTC -08:00
> Steam API Version:  SteamClient021

* Distribution: Linux Mint 22 Wilma Xfce

* Opted into Steam client beta?: No

* Have you checked for system updates?: Yes

* Steam Logs: 
``tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs
tar: Removing leading `/' from member names
/home/person/.steam/steam/logs/
/home/person/.steam/steam/logs/steamui_login.txt
/home/person/.steam/steam/logs/systemmanager.txt
/home/person/.steam/steam/logs/webhelper.txt
/home/person/.steam/steam/logs/remote_connections.txt
/home/person/.steam/steam/logs/bootstrap_log.txt
/home/person/.steam/steam/logs/systemdockmanager.txt
/home/person/.steam/steam/logs/steamui_audio.txt
/home/person/.steam/steam/logs/connection_log.txt
/home/person/.steam/steam/logs/compat_log.txt
/home/person/.steam/steam/logs/cloud_log.txt
/home/person/.steam/steam/logs/systemdisplaymanager.txt
/home/person/.steam/steam/logs/webhelper-linux.txt
/home/person/.steam/steam/logs/streaming_log.txt
/home/person/.steam/steam/logs/sitelicense_log.txt
/home/person/.steam/steam/logs/appinfo_log.txt
/home/person/.steam/steam/logs/workshop_log.txt
/home/person/.steam/steam/logs/transport_client.txt
/home/person/.steam/steam/logs/client_networkmanager.txt
/home/person/.steam/steam/logs/text_filter_log.txt
/home/person/.steam/steam/logs/configstore_log.txt
/home/person/.steam/steam/logs/cef_log.txt
/home/person/.steam/steam/logs/systemperfmanager.txt
/home/person/.steam/steam/logs/controller.txt
/home/person/.steam/steam/logs/steamui_update.txt
/home/person/.steam/steam/logs/transport_steamui.txt
/home/person/.steam/steam/logs/console-linux.txt
/home/person/.steam/steam/logs/stats_log.txt
/home/person/.steam/steam/logs/systemaudiomanager.txt
/home/person/.steam/steam/logs/console_log.txt
/home/person/.steam/steam/logs/shader_log.txt
/home/person/.steam/steam/logs/content_log.txt
/home/person/.steam/steam/logs/timedtrial_log.txt
/home/person/.steam/steam/logs/steamui_system.txt
/home/person/.steam/steam/logs/steamui_html.txt
/home/person/.steam/steam/logs/parental_log.txt
/home/person/.steam/steam/logs/cef_log.previous.txt
/home/person/.steam/steam/logs/controller_ui.txt
/home/person/.steam/steam/logs/librarysharing_log.txt
``

* GPU: integrated, from Intel i7-1355U

#### Please describe your issue in as much detail as possible:
When on the wishlist, after left clicking "Sort by: Your Rank", mousing down to "Price", and left clicking it, the click does not register on "Price" but on whatever was underneath it. In this case what is underneath it is the "Add to Cart" button for the game currently at the top of my wishlist.

#### Steps for reproducing this issue:

1. Find a L140AU laptop originally sold by LaptopsWithLinux.
2. Install Mint 22 Xfce.
3. Update your disto until it is current.
4. Install Steam as a system package, not a flatpak, and update it.
5. Log into your account.
6. Go to the wishlist page.
7. Ensure that at least one game is already wishlisted.
8. Left click on the "Sort by: " button.
9. Mouse down to "Price".
10. Left click on "Price".

**Comment by kisak-valve** [comment]
Hello @lvl20, this issue is already being tracked at #9273. Closing as a duplicate.

`Settings` -> ` Interface` -> `Enable context menu focus compatibility mode` might mitigate this issue.
