### ISSUE TITLE
steamwebhelper keeps crashing on Fedora 40 unless Steam is started via the terminal

### ISSUE THREAD

**Issue by SamusAranX** [ValveSoftware/steam-for-linux#11286]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): Fedora 40 KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17085990/steam-logs.tar.gz)
* GPU: AMD, AMD Radeon RX 7700S/AMD Radeon 780M

#### Please describe your issue in as much detail as possible:
The device is a Framework Laptop 16 with the graphics module connected.
I installed Steam by running `sudo dnf install steam`. If I start it from the KDE start menu, it repeatedly tries and fails to spawn a window.
The first time this happened, I got a fancy dialog about steamwebhelper having crashed, but for some reason that dialog's not popping up anymore.
If I start Steam from the terminal by simply running `steam`, it works flawlessly.

#### Steps for reproducing this issue:

1. Install Steam from the rpmfusion nonfree repository
2. Try to launch it from the start menu or the closest equivalent
3. Watch as it endlessly tries and fails to spawn a window

**Comment by kisak-valve** [comment]
Hello @SamusAranX, this issue is already being tracked at #9383. Closing as a duplicate.
