### ISSUE TITLE
Unable to Uninstall Games via the Context Menu

### ISSUE THREAD

**Issue by vigil007** [ValveSoftware/steam-for-linux#11284]
#### Your system information

* Steam client version: **1726604483**
* Distribution: **Pop!_OS 22.04 LTS**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**
* GPU: **Nvidia RTX 4070**
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17083112/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
I right-clicked my game to open the steam context menu in order to uninstall Total War: Rome II - Emperor Edition. I navigated the menus with my mouse to go into Manage -> Uninstall and it had no effect. I tried doing so multiple times and it did not uninstall the game.

#### Steps for reproducing this issue:

1. Right click on a game in the library view in Steam.
2. Hover your mouse over manage, and hover the mouse to uninstall.
3. Click uninstall.

**Comment by kisak-valve** [comment]
Hello @vigil007, this issue is already being tracked at #10925. Closing as a duplicate.
