### ISSUE TITLE
Optionally prevent game file validation

### ISSUE THREAD

**Issue by Yasand123** [ValveSoftware/steam-for-linux#11289]
I have Steam games backed up on my hard drive to prevent re-downloading in the future, slow Internet, and some games are modified (modded), and others use older versions because more recent versions are broken.

When reinstalling Steam, and getting those files where they belong (`common` directory) and hitting install on Steam, it does a mandatory file check first, where it would re-download all modified files, breaking mods, or updating the game to the latest (broken) version that I cannot use. This means I would have to wait for it to finish downloading, then re-download the older version that works or reapply the mods and hope Steam doesn't re-validate the files.

I think Steam should just check whether you own the game or not, and ask you whether you want to verify/validate file integrity, but it should not force it.

My current work-around is to have 2 back-ups of each game. One back up of the latest unmodified game, and the other for an older version, or a modified one. So I first let Steam validate the unmodified, latest version of a game, so it doesn't have to re-download anything, and then delete it and replace it with the other copy.

This is a terrible experience because you have to pick between two bad things, either have each game backed up twice, wasting space, or waste bandwidth and time for when Steam re-downloads the latest unmodified files after validating. 

This hurts the user experience for people in my situation which I think is a lot. I think most people have an issue with the latest version of a game. For example Skyrim, Fallout, Witcher 3, all these popular moddable games always break mods. And there's instances where the latest game just doesn't work properly or has issues which is unrelated to modding.

Another solution is to allow users to pick the version they want, but I can't see that happening for some reason. Giving the user the option to never validate the files is a good middle ground solution imo.

**Comment by kisak-valve** [comment]
Hello @Yasand123, this is functionally the same issue as #8711 and https://github.com/ValveSoftware/steam-for-linux/issues/8711#issuecomment-1197050595 is equally valid today as it was back then.
