### ISSUE TITLE
Proper location for `compatibilitytools.d`

### ISSUE THREAD

**Issue by ndlarsen** [ValveSoftware/steam-for-linux#11294]
#### Your system information
* Steam client version (build number or date): 
   ```
   Steam Beta Branch:  Stable Client
   Steam Version:  1726604483
   Steam Client Build Date:  Tue, Sep 17 22:03 UTC -08:00
   Steam Web Build Date:  Tue, Sep 17 01:12 UTC -08:00
   Steam API Version:  SteamClient021
   ```
* Distribution (e.g. Ubuntu): 
   ```
   $ lsb_release -a
   No LSB modules are available.
   Distributor ID:	Ubuntu
   Description:	Ubuntu 20.04.6 LTS
   Release:	20.04
   Codename:	focal
   ```
* Opted into Steam client: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]: Not relevant
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Custom compatibility tools such as ProtonGE installed into `~/.steam/steam/compatibilitytools.d`, which I understand is the new "proper" location, are not detected by the Steam client but only when installed into `~/.steam/root/compatibilitytools.d` they are. 

#### Steps for reproducing this issue:

1. place custom compatibility tool into `~/.steam/steam/compatibilitytools.d`
2. launch steam and observe the installed tool missing from `settings -> Compatibility -> Run other Titles with`
3. remove custom compatibility tool from `~/.steam/steam/compatibilitytools.d`
4. place custom compatibility tool into `~/.steam/root/compatibilitytools.d`
5. launch steam and observe the installed tool being present in `settings -> Compatibility -> Run other Titles with` 

So, 
1. which of the following locations is actually the correct one?
   `~/.local/share/Steam/compatibilitytools.d`
   `~/.steam/root/compatibilitytools.d`
   `~/.steam/steam/compatibilitytools.d` (current according to various sources)
2. if `~/.steam/steam/compatibilitytools.d` is the correct one, how can I debug why it is no honoured?

**Comment by kisak-valve** [comment]
Hello @ndlarsen, see https://github.com/ValveSoftware/steam-for-linux/issues/6310#issuecomment-511630263.

`~/.steam/steam` and ~/.steam/root` should both coincidentally be a symlink to the same Steam install folder typically found at `~/.local/share/Steam`. This has been true for a fairly long time. If that's not true due to using an older distro-modified package, then it's probably something for the package maintainers for the distro-modified Steam package to clarity.

**Comment by ndlarsen** [comment]
> Hello @ndlarsen, see [#6310 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/6310#issuecomment-511630263).
> 
> `~/.steam/steam` and `~/.steam/root` should both coincidentally be a symlink to the same Steam install folder typically found at `~/.local/share/Steam`. This has been true for a fairly long time. If that's not true due to using an older distro-modified package, then it's probably something for the package maintainers for the distro-modified Steam package to clarity.

Thank you. So, if I understand you and the linked post correctly, then the correct place for me to put them would be `~/.steam/root/compatibilitytools.d` if present in one form or another else `~/.local/share/Steam/compatibilitytools.d` or `~/.local/share/Steam/root/compatibilitytools.d` (neither of the latter are present for me)

There seem to be a lot of confusion about this in the community, is this documented anywhere (besides here and in the linked post)?

**Comment by ndlarsen** [comment]
@kisak-valve Closing this issue as completed is a bit premature imo.
