### ISSUE TITLE
Steam won't start on freshly installed Void Linux

### ISSUE THREAD

**Issue by arspacer** [ValveSoftware/steam-for-linux#11302]
#### Your system information

OS: Void x86_64
Kernel: Linux 6.6.52_1 LTS
DE: Xfce 4.18
WM: Xfwm4 (X11)
CPU: 12th Gen Intel i9-12900H (20) @ 4.900GHz
GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics]
GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU 8GB
Memory: 32GB RAM

* Steam client version (build number or date): 
  I can not find out the version because steam does not open after installation, installed in September this month, but this problem is already half a year ago.

* Distribution (e.g. Ubuntu): 
  Void Linux

* Opted into Steam client beta?: [Yes/No]
  No

* Have you checked for system updates?: [Yes/No]
  Yes

* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]

  launching steam via terminal
~]$ steam
/home/void/.local/share/Steam/steam.sh: line 192: VERSION_ID: unbound variable
/home/void/.local/share/Steam/steam.sh: line 192: VERSION_ID: unbound variable
steam.sh[5682]: Running Steam on void  64-bit
/home/void/.local/share/Steam/steam.sh: line 192: VERSION_ID: unbound variable
steam.sh[5682]: STEAM_RUNTIME is enabled automatically
setup.sh[5756]: Steam runtime environment up-to-date!
/home/void/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[5768]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[5682]: Couldn't find /home/void/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[5682]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2024-09-27 23:09:36] Startup - updater built Jul 16 2024 23:21:18
[2024-09-27 23:09:36] Startup - Steam Client launched with: '/home/void/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
09/27 23:09:36 minidumps folder is set to /tmp/dumps
09/27 23:09:36 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(5799)
assert_20240927230936_3.dmp[5802]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240927230936_3.dmp
src/steamexe/updateui_xwin.cpp (1467) : BFileExists( m_FontFileLight )
src/steamexe/updateui_xwin.cpp (1467) : BFileExists( m_FontFileLight )
09/27 23:09:36 minidumps folder is set to /tmp/dumps
09/27 23:09:36 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(5799)
assert_20240927230936_3.dmp[5802]: Finished uploading minidump (out-of-process): success = no
assert_20240927230936_3.dmp[5802]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20240927230936_3.dmp[5802]: file ''/tmp/dumps/assert_20240927230936_3.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
assert_20240927230936_6.dmp[5805]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240927230936_6.dmp
09/27 23:09:36 minidumps folder is set to /tmp/dumps
09/27 23:09:36 Init: Installing breakpad exception handler for appid(steam)/version(0)/tid(5799)
assert_20240927230936_6.dmp[5805]: Finished uploading minidump (out-of-process): success = no
assert_20240927230936_6.dmp[5805]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20240927230936_6.dmp[5805]: file ''/tmp/dumps/assert_20240927230936_6.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  156 (NV-GLX)
Minor opcode of failed request:  6
Value in failed request:  0x0
Serial number of failed request:  36
xerror_handler: X failed, continuing
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

* GPU: Nvidia/Intel/AMD
  Nvidia Geforce RTX 3070 Ti Laptop

#### Please describe your issue in as much detail as possible:
  By the way, I want to note that on my PC with AMD CPU + AMD GPU.
steam works natively without any problems in Void Linux, but it doesn't work on my laptop with Intel CPU + Nvidia GPU although everything is the same except hardware and drivers for them.

#### Steps for reproducing this issue:

1. A year ago everything worked on this laptop with Void Linux, without any problems, worked natively without flatpak, but after a complete cleaning of the laptop and After fresh installation of xfce 2024-03-14 Live image [glibc] Steam just stopped starting. 

2. If you need more information I will add to it

3. All necessary packages are installed: libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit nvidia-libs-32bit

**Comment by Singustromo** [comment]
I also got the same issue. Can't remember the cause, unfortunately.

**Comment by kisak-valve** [comment]
Hello @arspacer, the X error you're showing hints that the 32 bit OpenGL render path is broken. Can you test if any 32 bit OpenGL application works? I'd usually suggest a 32 bit build of glxinfo, but in a quick check it's not clear if Void provides that in any package anymore.

**Comment by arspacer** [comment]
@kisak-valve Thanks, you made me think I should have installed the mesa-dri-32bit package before. The documentation was a bit confusing, mesa is labeled as an opensource driver and I only installed it for my pc with AMDCPU+AMDGPU build.

and for my laptop I only installed nvidia proprietary, nvidia-libs-32bit, and libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit. 

I thought there might be conflicts between mesa-dri-32bit and nvidia-libs-32bit.


I apologize for taking the time to solve such a trivial problem, I am new to linux systems. Thank you for responding.

**Comment by kisak-valve** [comment]
Hello @Singustromo, your issue should be evaluated separately. Please open a new issue report with a full set of requested details from the template.

**Comment by sww1235** [comment]
> @kisak-valve Thanks, you made me think I should have installed the mesa-dri-32bit package before. The documentation was a bit confusing, mesa is labeled as an opensource driver and I only installed it for my pc with AMDCPU+AMDGPU build.
> 
> and for my laptop I only installed nvidia proprietary, nvidia-libs-32bit, and libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit. 
> 
> I thought there might be conflicts between mesa-dri-32bit and nvidia-libs-32bit.
> 
> 
> I apologize for taking the time to solve such a trivial problem, I am new to linux systems. after installing mesa-dri-32bit everything worked!
> Thank you for responding.

I can confirm that installing mesa-dri-32bit package on void Linux fixed the issue described above with steam not launching.
