### ISSUE TITLE
Steam hangs when trying to shut down  (and games increadibly slow)

### ISSUE THREAD

**Issue by soerko** [ValveSoftware/steam-for-linux#11300]
#### Your system information

* Steam client version (build number or date):  Steam Beta Branch:  Steam Beta Update
Steam Version:  1726683985
Steam Client Build Date:  Wed, Sep 18 7:13 PM UTC -08:00
Steam Web Build Date:  Tue, Sep 17 1:12 AM UTC -08:00
Steam API Version:  SteamClient021

* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes all updated to latest versions
* Steam Logs: [generate by running this command in a terminal [steam-logs.tar.gz](https://github.com/user-attachments/files/17166571/steam-logs.tar.gz)]
* GPU: Nvidia/Intel/AMD:  *-display                 
       description: VGA compatible controller
       product: TU116 [GeForce GTX 1660 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:141 memory:a3000000-a3ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:4000(size=128) memory:c0000-dffff
  *-graphics
       product: simpledrmdrmfb
       physical id: 2
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1920,1080

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam does not shut down completely byt is left with several processes still running (especially the d3ddriverquery64.exe program)
I expect that this program hanging in a do_wai state is also the cause for all my games running increadibly slow for the last 2 weeks.

Output from ps:
```
0 S skoch      11988    3177  0  80   0 -  2712 do_wai 17:43 ?        00:00:00 bash /home/skoch/.steam/steam.sh -nominidumps -nobreakpad
0 S skoch      12105    2794  0  80   0 -  6957 pipe_r 17:43 ?        00:00:00 /home/skoch/.steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/srt-logger --sh-syntax --rotate=8388608 --log-directory /home/skoch/.steam/steam/logs --filename console-linux.txt --log-fd=7 --journal-fd=5 --parse-level-prefix
4 S skoch      12134   11988  1  80   0 - 239499 hrtime 17:43 ?       00:00:06 /home/skoch/.steam/ubuntu12_32/steam -srt-logger-opened -nominidumps -nobreakpad
0 S skoch      12394   12134  0  80   0 - 79860 do_pol 17:43 ?        00:00:00 steam-runtime-launcher-service --alongside-steam
0 Z skoch      12530   12134  0  80   0 -     0 -      17:43 ?        00:00:00 [steam-runtime-s] <defunct>
0 S skoch      12783   12134  0  80   0 -   701 do_wai 17:43 ?        00:00:00 sh -c -- LD_LIBRARY_PATH="$SYSTEM_LD_LIBRARY_PATH" PATH="$SYSTEM_PATH"  STEAM_COMPAT_APP_ID='1420170' STEAM_COMPAT_TOOL_PATHS='' STEAM_COMPAT_LIBRARY_PATHS='' STEAM_COMPAT_SHADER_PATH='/home/skoch/.steam/steamapps/shadercache/1420170' STEAM_COMPAT_INSTALL_PATH='/home/skoch/.steam/steamapps/common/Proton 5.13' STEAM_COMPAT_MOUNTS='' STEAM_COMPAT_DATA_PATH='/home/skoch/.steam/steamapps/compatdata/1420170' STEAM_COMPAT_CLIENT_INSTALL_PATH='/home/skoch/.steam' PROTON_CRASH_REPORT_DIR='/tmp/proton_crashreports' STEAM_FOSSILIZE_DUMP_PATH='/home/skoch/.steam/shader_cache_temp_dir_d3d11_64/fozpipelinesv6/steamapprun_pipeline_cache' STEAM_FOSSILIZE_DUMP_PATH_READ_ONLY='$bucketdir/steam_pipeline_cache.foz;$bucketdir/steamapp_pipeline_cache.foz' FOSSILIZE_APPLICATION_INFO_FILTER_PATH='/home/skoch/.steam/fossilize_engine_filters.json' ENABLE_VK_LAYER_VALVE_steam_fossilize_1='1' FONTCONFIG_PATH='' '/home/skoch/.steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=run -- '/home/skoch/.steam/steamapps/common/Proton 5.13'/proton run  /home/skoch/.steam/ubuntu12_32/../bin/d3ddriverquery64.exe 2>/dev/null 
4 S skoch      12784   12783  0  80   0 -  1200 do_pol 17:43 ?        00:00:00 /home/skoch/.steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/libexec/steam-runtime-tools-0/srt-bwrap --args 134 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 17 --regenerate-ld.so-cache /var/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --overrides-path /usr/lib/pressure-vessel/overrides --exit-with-parent --subreaper --assign-fd=1=5 --assign-fd=2=6 --shell=none --terminal=none -- /home/skoch/.steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/skoch/.steam/steamapps/common/Proton 5.13/proton run /home/skoch/.steam/ubuntu12_32/../bin/d3ddriverquery64.exe
4 S skoch      12886   12784  0  80   0 -  7865 do_wai 17:43 ?        00:00:00 /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb --generate-locales --fd 17 --regenerate-ld.so-cache /var/pressure-vessel/ldso --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu --add-ld.so-path /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu --set-ld-library-path /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases --overrides-path /usr/lib/pressure-vessel/overrides --exit-with-parent --subreaper --assign-fd=1=5 --assign-fd=2=6 --shell=none --terminal=none -- /home/skoch/.steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/steam-runtime-launcher-interface-0 container-runtime /home/skoch/.steam/steamapps/common/Proton 5.13/proton run /home/skoch/.steam/ubuntu12_32/../bin/d3ddriverquery64.exe
0 S skoch      12941   12886  0  80   0 -  5137 do_wai 17:43 ?        00:00:00 python3 /home/skoch/.steam/steamapps/common/Proton 5.13/proton run /home/skoch/.steam/ubuntu12_32/../bin/d3ddriverquery64.exe
0 S skoch      12954   12941  0  80   0 - 449112 do_pol 17:43 ?       00:00:00 steam /home/skoch/.steam/ubuntu12_32/../bin/d3ddriverquery64.exe
1 S skoch      12960   12886  0  80   0 -  3604 ep_pol 17:43 ?        00:00:00 /home/skoch/.steam/steamapps/common/Proton 5.13/dist/bin/wineserver
1 S skoch      14065    2794  0  80   0 -  3911 do_pol 17:51 ?        00:00:00 /tmp/dumps/assert_20240927175116_39.dmp uptime 462071 StartupTime 1727451986 CrashTime 1727452519 BuildID 20240918171256 GL_RENDERER llvmpipe (LLVM 15.0.7, 256 bits) GL_VENDOR Mesa GL_VERSION 4.5 (Compatibility Profile) Mesa 24.2.2 - kisak-mesa PPA Platform Linux ProductName steam STEAM_RUNTIME /home/skoch/.steam/ubuntu12_32/steam-runtime SteamUniverse Public URL www.steampowered.com UserID 76561198877112078 Vendor Valve Version 1726683985
1 S skoch      14068    2794  0  80   0 -  3911 do_pol 17:51 ?        00:00:00 /tmp/dumps/assert_20240927175116_42.dmp uptime 462228 StartupTime 1727451986 CrashTime 1727452677 BuildID 20240918171256 GL_RENDERER llvmpipe (LLVM 15.0.7, 256 bits) GL_VENDOR Mesa GL_VERSION 4.5 (Compatibility Profile) Mesa 24.2.2 - kisak-mesa PPA Platform Linux ProductName steam STEAM_RUNTIME /home/skoch/.steam/ubuntu12_32/steam-runtime SteamUniverse Public URL www.steampowered.com UserID 76561198877112078 Vendor Valve Version 1726683985
0 S skoch      14072    9107  0  80   0 -  2286 pipe_r 17:51 pts/0    00:00:00 grep --color=auto steam
skoch@skpc:~$ 
```

#### Steps for reproducing this issue:

1. Start steam (click on steam icon in  sidebar
2. Exit steam (or try to) by selecting 'Exit steam' by clicking on steam icon at top right of screen.

**Comment by kisak-valve** [comment]
Hello @soerko, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

In particular, I'm curious what video driver version you're using is, if the driver's 32 bit userspace libraries are functional, and how it was installed.

**Comment by som-cs** [comment]
I had this same issue and now it has escalated to new heights of kernel panic. My distro is manjaro but I run steam and wayland on nvidia, which seems to be causing some problems.

**Comment by soerko** [comment]
Here is the requested steam runtime report (I hope that I have done it correctly)

<script src="https://gist.github.com/soerko/379e74ce2f5aac9ea574fb04b49071ed.js"></script>


I'm using this video driver:
NVIDIA driver metapacke from nvidia-driver-560 (proprietary)
But the issue arises with all the drivers for my video card  I have tried so far.

**Comment by soerko** [comment]
Here3 is another link if the one above doesn't work...
https://gist.github.com/soerko/379e74ce2f5aac9ea574fb04b49071ed#file-steam_runtime_diagnostics-txt

My video drivers have been installed through the normal 'additional drivers' system in Ubuntu

**Comment by kisak-valve** [comment]
Thanks, https://gist.github.com/soerko/379e74ce2f5aac9ea574fb04b49071ed#file-steam_runtime_diagnostics-txt-L4344-L4351 is the section to focus on. Your NVIDIA driver install is missing the video driver's 32 bit userspace libraries and is being forced to fallback to llvmpipe (Mesa's faster CPU renderer) to run at all.

Try to add the `libnvidia-gl-560:i386` system package with something like `sudo apt install libnvidia-gl-560:i386`. If that doesn't work, then switch to a different release series of the NVIDIA driver.

**Comment by soerko** [comment]
Thanks for the help.
I couldn't install the libnvidia-gl-560:i386 (it apparently doesn't exist in the repository) but changing to the
NVIDIA driver metapackage from nvidia-driver-550 (proprietary) driver worked as that could install the i386 part (and installed it automatically) fixed the issue!
Now steam works as it should and i can play games at more than 0.3 frame /second (yes that's no typo it was that slow)
