### ISSUE TITLE
Big Picture Mode Lags at resolutions greater than 720p

### ISSUE THREAD

**Issue by kellyfay94** [ValveSoftware/steam-for-linux#11301]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): Garuda Linux (Arch)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17166505/steam-logs.tar.gz)
* GPU: AMD RX 6800XT (amdgpu driver)

#### Additional
* CPU: AMD Ryzen 7 5800X
* Kernel: 6.10.10-zen1-zen
* Resolution: 2560x1440

#### Please describe your issue in as much detail as possible:
I expect that in Big Picture Mode on resolutions greater than 720p on hardware strong than the SteamDeck, the UI be as responsive as 720p on the Steam Deck, where individual elements are near instantaneously scrolled between, including between tabs and different titles.

When Big Picture Mode is started with the default Big Picture Mode settings, the UI is not responsive, and actions often occur with an ~500ms-1sec delay.  An example of this is navigating the Home Screen top-row library, where scrolling between titles took an unexpectedly long time to load and play animations.  

Even after enabling Hardware Acceleration, GPU Blocklist, and other suggested fixes from other threads, the responsiveness did not improve.

If Downloads are paused, responsiveness improves, but only to a minor degree.

If Big Picture mode changes to Windowed Mode, the responsiveness improves to the expected speed (however, it's not much of a "Big Picture").

If the following steps are taken, Big Picture Mode's performance improves significantly, but can still lag:
- Downloads are paused
- Big Picture Mode's Automatic Scaling is disabled
- Big Picture Mode's Manual Scaling is set to show "More Content" (all the way to the left)
- Big Picture Mode is exited
- Big Picture Mode is reopened

Additional NOTE: If I use `gamescope-plus` to run Steam at 720p and launch Big Picture Mode, it runs very smoothly.  However, resolutions of 1080p and greater all run poorly, as detailed above.

#### Steps for reproducing this issue:

1. Have a monitor with at least 1440p resolution; go to the Display Manager, and set Display Scaling to 100% (integer scaling).
2. Ensure that Steam has all of the default settings for Big Picture Mode configured.  (If not, open Big Picture Mode, restore defaults, and exit Big Picture mode to restart.)
3. Open Big Picture Mode, and ensure it's at full screen.
4. On the home screen, move left / right between titles in the User's Library.  The background images take time to load, and each element takes approximately 500ms to 1sec to scroll between

**Comment by kisak-valve** [comment]
Hello @kellyfay94, this issue is already being tracked at #11255. Closing as a duplicate.
