### ISSUE TITLE
Sea of Thieves does not recognize Proton EasyAntiCheat Runtime

### ISSUE THREAD

**Issue by TomyLobo** [ValveSoftware/steam-for-linux#11317]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Prefer not to share this publicly, as it contains all kinds of private data. Send me a list of files you absolutely need and I'll manually censor and post them.
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
```
Launch Error

Unexpected error. (#1)

Exit
```
![image](https://github.com/user-attachments/assets/2ed2b0a9-ae2f-4975-b60f-56cd84579d14)

For details, see repro steps below

#### Steps for reproducing this issue:

1. Install FlatPak
2. Activate FlatHub
3. Install FlatSeal from FlatHub
4. Install Steam from FlatHub
5. Change the following permissions in FlatSeal (for privacy reasons):
     * Deactivate share=ipc
     * Activate device=dri
     * Deactivate device=all
     * Deactivate allow=devel
     * Deactivate allow=bluetooth
6. Install Proton EasyAntiCheat Runtime
7. Install Start Sea of Thieves
8. Launch Start Sea of Thieves
     * Expected: Game launches
     * Actual: The error depicted in the issue details above

Running it through FlatPak and the permission changes in step 5 are non-negotiable, I'm not giving Steam and all games free reign over my system.
Steam is neither inspecting nor sandboxing the games on its own and I don't want some rogue game to steal my browser cookies or something, so I'm taking what I think are appropriate precautions.

**Comment by kisak-valve** [comment]
Hello @TomyLobo, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-2393714518.
