### ISSUE TITLE
Half-Life: Alyx - Multiple saves folders 

### ISSUE THREAD

**Issue by eyJhb** [ValveSoftware/steam-for-linux#11313]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Not relevant
* GPU: AMD

#### Please describe your issue in as much detail as possible:
It seems like there is a mismatch in the code, and that both a folder named "SAVE" (uppercase) and "save" (lowercase) is being used. Where the actual save files are in `save`, but only the files in `SAVE` are being synced using the Steam Cloud.
This issue does not impact Windows, as Windows folders are case in-sensitive.

#### Steps for reproducing this issue:

1. Play Half-Life Alyx on Linux (make progress, close game)
2. See that it's not synced at all
3. Play on another game, and see it's not synced.

**Comment by kisak-valve** [comment]
Hello @eyJhb, this issue is already being tracked at https://github.com/ValveSoftware/SteamVR-for-Linux/issues/353. Closing as a duplicate.
