### ISSUE TITLE
Doubt about hardware acceleration

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#11321]
Hi, I wanted to ask a question, please don't get mad:

Linux distros, such as Debian and Fedora, Kde Plasma, Wayland, always show some errors like Acpi not found and other errors, I believe it is something missing in the main kernel, since everything is updated on the PC, even the BIOS.
Do these errors affect the hardware acceleration in Steam, in the integrated browser that is accessed by alt+tab in an open game, in the integrated chromium?
Does it also influence the function of things that are disabled/enable in chrome://gpu?

Lenovo ideapad 3 15itl6 82md laptop
intel i3 1115G4

Thanks in advance, always good luck 👍😄

**Comment by SZUPEK** [comment]
I believe ACPI is related to power management, which is lacking in linux. It sounds like these error messages should have little impact on if you have 3d acceleration enabled via Steam Launcher.  The IDEAPAD series is not very "strong" with GPU integration, so there is only so much it's going to be able to do, if anything.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
