### ISSUE TITLE
steam crash loop on several distros tested

### ISSUE THREAD

**Issue by Nosleep8607** [ValveSoftware/steam-for-linux#11325]
#### Your system information

* Steam client version idk i installed it from https://store.steampowered.com/about/ so im assuming latest?
* Distribution linux mint 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] (command didnt work btw)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I installed steam on a newly installed distro (linux mint and ive had the same exact issues on ubuntu, pop os elementory os and zorian os basicly all debian/ubuntu based distros) and when steam was fully installed i started the client and it popped up the sign in page worked fine until it was loading past the sign in page to the actual client and it kept popping up and flashing on the screen for less than a second.

#### Steps for reproducing this issue:

1. install steam
2. open steam
3. suffer in pain

**Comment by Nosleep8607** [comment]
Hopefully people smarter than me can figure this out because this happens on several distros as stated and i wanna game on linux but steam client never works for me so i go back to windows

**Comment by kisak-valve** [comment]
Hello @Nosleep8607, this issue is already being tracked at #9383. Closing in favor of the older issue report.
