### ISSUE TITLE
steamVR not working on hyprland.

### ISSUE THREAD

**Issue by kgncengiz** [ValveSoftware/steam-for-linux#11337]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): ARCH
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes
* Steam Logs: 
* GPU: Nvidia RTX 4050 560.35.03

#### Please describe your issue in as much detail as possible:
I'm using Arch Linux with Hyprland on my PC. Recently, I tried streaming SteamVR to my Meta Quest 3 over Wi-Fi 6, but it says that SteamVR is not available on my PC. Additionally, when I try streaming just the desktop, the entire screen appears black.

#### Steps for reproducing this issue:

1. install arch.
2. install hyprland.
3. install steam && steamvr.
4. install steamvr beta.
5. try to use it with meta quest 3 over wifi.

**Comment by kisak-valve** [comment]
Hello @kgncengiz, this issue is already being tracked at https://github.com/ValveSoftware/SteamVR-for-Linux/issues/655. Closing as a duplicate.

**Comment by Poellebob** [comment]
you can fix this by putting `QT_QPA_PLATFORM=xcb` at the front in the launch options

**Comment by ShayBox** [comment]
Yep that fixes it and a few other programs which don't work using wayland on hyprland, such as moonlight.
