### ISSUE TITLE
Steam won't start - webhelper crashes due to vulkan error

### ISSUE THREAD

**Issue by Storyyeller** [ValveSoftware/steam-for-linux#11339]
#### Your system information

* Steam client version (build number or date): Latest deb downloaded from website 
* Distribution (e.g. Ubuntu): Linux Mint 20
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD - Nvidia GeForce GTX 460

#### Please describe your issue in as much detail as possible:

Steam will not start up at all. When I run `steam` from the console, it shows the webhelper endlessly crashing and being restarted. The `webhelper-linux.txt` logs (attached) show that it keeps crashing with the error "Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1404."
[webhelper-linux.txt](https://github.com/user-attachments/files/17336895/webhelper-linux.txt)

Things I have already tried
* Deleting all Steam files and reinstalling (several times)
* Rebooting the computer (several times)
* enabling "nvidia_drm.modeset=1"
* running steam with various options (e.g. reset, clearbeta)
* running steam with "-no-cef-sandbox"

This is my first time trying to run Steam, so I can't tell if it worked before.

#### Steps for reproducing this issue:

1. run steam
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Storyyeller, your log tells us you have the NVIDIA 390.157 driver release. The Vulkan error is a red herring and #10980 is a better match to your issue. Give https://github.com/ValveSoftware/steam-for-linux/issues/10980#issuecomment-2183858579 a try.

Closing in favor of the older issue report.
