### ISSUE TITLE
Add an option to containerize the filesystem

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#11330]
#### Your system information
* Steam client version: 1728093750
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Oftentimes native Linux games like to barf their savefiles all over the home folder. For this I propose an option in the compatibility tab to force containerization of the filesystem for that game. It would also have a nice side effect of keeping both windows and linux save data in the same place in `steamapps/compatdata`.

#### Steps for reproducing this issue:

1. Install Postal 2 or Factorio
2. Check your home folder

#### Results:
There is now an extra folder in the home dir

#### Expected:
I would like to not litter my home folder.

**Comment by kisak-valve** [comment]
Hello @Managor, Steam is not a security barrier and doesn't pretend to be. My understanding is that this request is a non-starter in the near future.

Having written that, Pressure Vessel did have an experimental environment variable `PRESSURE_VESSEL_SHARE_HOME=0`.

**Comment by Managor** [comment]
I don't intend it in a security sense. This would be just to make sure games don't litter the home folder by using a shadow filesystem. If `PRESSURE_VESSEL_SHARE_HOME` exists, then what I am asking is just an UI checkbox to enable it.

**Comment by Managor** [comment]
@kisak-valve Can I get your opinion on this?

**Comment by kisak-valve** [comment]
The runtime devs / Steam devs would need to be happy enough with how SLR behaves with that environment variable to no longer consider it an experiment before it can be exposed to end users as a feature.
