### ISSUE TITLE
CS on new X server.

### ISSUE THREAD

**Issue by demencia** [ValveSoftware/steam-for-linux#1134]
I've edited my xinitrc file to run "steam steam://rungameid/10

and run "startx -- :1" so I would have counter strike running on a separate X server. This improves perfomance A LOT. I've encountered a few problems that might be bugs or might 
be some tweaks I've got to make to the settings of X11.

The first one is that if you open the overlay, you cant get the mouse to look around anymore.
The otherone is that if you are pressing a mouse button, it wont let you look around either.

The perfomance is outstanding. I'm running archlinux, and I get 100/150 fps @ 1366*768 if 
I run the game this way. I get 30/50 fps @ same res under Unity, and around 80fps @ same res under KDE with kwin. Something around 20/30 fps @ same res on Win 7.

https://gist.github.com/4690618

This is my xinitrc.

I've managed to "fix" this runing it on anilla openbox, which is pretty light, the perfomance is quite similar that if I run it without openbox but it has window border.

**Comment by kisak-valve** [comment]
Hello @demencia, it looks like you found an acceptable solution for yourself and running games without a window manager is a pretty rare configuration.

It's a bit of a stretch to find an actionable feature request here, so I'm going to close this.
