### ISSUE TITLE
 Subject: AMD 7900 XT Driver Issues on Linux  WRONG POWER / Freq /Timings

### ISSUE THREAD

**Issue by ilievi187** [ValveSoftware/steam-for-linux#11347]
Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: MPG B550 GAMING PLUS (MS-7C56)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 5800X3D 8-Core Processor
CPU Family: 0x19
CPU Model: 0x21
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4550 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"ArcoLinux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.11.3-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12401003
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240806.97925
Video Card:
Driver: AMD AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 18.1.8, DRM 3.59, 6.11.3-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.4-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 199 Hz
VendorID: 0x1002
DeviceID: 0x744c
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1080
Desktop Resolution: 2560 x 1080
Primary Display Size: 27.17" x 11.46" (29.45" diag), 69.0cm x 29.1cm (74.8cm diag)
Primary VRAM: 20480 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 32019 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 431713 MB
Largest Free Hard Disk Block: 119612 MB
Storage:
Number of SSDs: 3
SSD sizes: 500G,0B,0B
Number of HDDs: 0
Number of removable drives: 0

#### Steps for reproducing this issue:

1. Launch game from steam 
2. enable mangohud and track watts/freq/fps

Subject: AMD 7900 XT Driver Issues on Linux

Hello,

I’m not sure if this is the correct place to report this issue, but I’ll post it here and hope it can be forwarded to the appropriate team. Feel free to delete the thread once it’s moved.

At the moment, the driver for the AMD 7900 XT isn’t functioning correctly. It seems to have the wrong power table, or something else is off. I’ve tested all the supported Linux distributions, and the issue is the same across the board – my 7900 XT is locked to 265 watts and boosts to a maximum of 2 GHz. In gaming scenarios, it doesn’t go beyond 200 watts, and I’ve verified that I’m not CPU-limited in the games I’ve played.

On Windows, everything works as expected without intervention. The card reaches up to 330 watts, frequencies are stable, and the FPS is 2-3 times better with no stuttering. This leads me to believe that the problem lies with the AMD Linux driver.

I’ve tested various Linux distributions, including Arch, Debian, Sid, and others listed as supported on the site. I’ve tried both old and new kernels, and the result is the same every time. It doesn’t seem to be a distro-specific issue but rather a driver-related one.

Another problem is that the zero-RPM mode is hardware-locked, so I can’t disable it. This causes the GPU to run hot, whereas if I could set the fans to just 10%, the temperatures would be fine.

Since I bought the 7900 XT, I’ve been unable to use Linux effectively. Please, this issue has persisted for two years now, and it needs to be addressed. I’ve been a Linux user for years, but this has made the platform unusable for me with this GPU.

Thank you for your attention to this matter.

**Comment by kisak-valve** [comment]
Hello @ilievi187, the Steam client is not responsible for power or clock management of video cards. This is something for your video driver vendor to look closer at in detail.

Closing as not a Steam issue.
