### ISSUE TITLE
Sony Dual Sense - Steam Chord turn off controller function issue.

### ISSUE THREAD

**Issue by hexmanUK** [ValveSoftware/steam-for-linux#11341]
* Steam client version (1728606687): 
* Distribution (Fedora KDE): 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* GPU: AMD

Hello,
In Linux the steam button chord to turn of a Sony Dual Sense controller (PS button + Y) does not work and hasn't worked for a couple of years. It still works in windows just not Linux.

A) Problem remains present regardless of controller firmware.
B) Problem remains present regardless of Linux distribution or Kernel.
C) Controller is enabled in steam settings via Bluetooth.

**Comment by kisak-valve** [comment]
Hello @hexmanUK, this issue is already being tracked at #8066. Closing as a duplicate.
