### ISSUE TITLE
Error in "must have non-limited account" dialogue when trying to create a review

### ISSUE THREAD

**Issue by Peppernrino** [ValveSoftware/steam-for-linux#11345]
* Steam client version (build number or date): Using Steam AppImage with all patches installed.
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?:  no
* Have you checked for system updates?: yes
* GPU: Nvidia 1660. seems irrelevant.

When attempting to make a review for a game I have purchased, I receive a dialogue stating, that I "must have a non-limited Steam account"... which is not my issue.

The problem is that the dialogue exposes the html code of the warning. "<code>a href... Click here< /a>.</code>" Not a huge deal, just kind of sloppy.

**Comment by kisak-valve** [comment]
Hello @Peppernrino, this issue is already being tracked at #9503. Closing as a duplicate.
