### ISSUE TITLE
steamwebhelper won't respond after ubuntu 24.10 update 

### ISSUE THREAD

**Issue by Oka-z** [ValveSoftware/steam-for-linux#11343]
## Your system information

* Steam client version (build number or date): 1.0.0.81
* Distribution (e.g. Ubuntu):ubuntu 24.10 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[logs.tar.gz](https://github.com/user-attachments/files/17355845/logs.tar.gz)
* GPU: intel hd 530 (igpu of  an i5 6400T)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
hello ! Yesterday i updated ubuntu from 24.04.1 to 24.10 since then steam wont work, every time i try to open steam a windows saying that steamwebhelper don't respond apear
![Capture d’écran du 2024-10-13 16-25-18](https://github.com/user-attachments/assets/c2fe5127-3697-44e7-bf56-316a91ee8914)
 ,compleatly freezing my computer for a minute or so . i try many thing including :
- restart steam 
-restart steam without accelerated gpu render 
-restart steam without isolated browser 
-restart steam web helper 
-restart my computer 
[-check for update 
-uninstall steam 
- install it with a deb 
- uninstall steam and install it with sudo apt install
- uninstall it and install it with snaps
- delete all file or folder with the word steam in it ]
- repeat the procedure inside brackets after having uninstall and reinstall libudev 0 
- repeat the procedure inside brackets after reinstalling my gpu driver
- repeat the procedure insdie brackets after having delete the file /tmp/dumps 

if try to run steam via the terminal this apear :
https://gist.github.com/Oka-z/d18f3e94dccad1bd47ba2c6557276ea4#file-gistfile1-txt

i have no anti virus no dns or vpn 
#### Steps for reproducing this issue:

1. install steam on ubuntu 24.04
2. update to ubuntu 24.10 i guess 

if you try to find a solution or even read this message thank you so much!!

**Comment by kisak-valve** [comment]
Hello @Oka-z, `pressure-vessel-wrap[45986]: E: Could not create copy "./share/zoneinfo/right/America/Rankin_Inlet" from "/home/oka-z/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/sniper_platform_0.20240618.92328/files/./share/zoneinfo/right/America/Rankin_Inlet" into "/home/oka-z/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-ORH5U2/usr": fstatat(./share/zoneinfo/right/America/Rankin_Inlet): Aucun fichier ou dossier de ce nom` looks like the line of interest from your terminal spew. can you verify your filesystem and this file is healthy? Maybe try reinstalling the `tzdata` system package.

**Comment by Oka-z** [comment]
hello again @kisak-valve , what you asked me to do actually worked , thank you so much for your help !
