### ISSUE TITLE
game crashes when selecting team or in-game using Ubuntu 22.04 + Flatpak

### ISSUE THREAD

**Issue by zoltan-sule** [ValveSoftware/steam-for-linux#11352]
#### Your system information

* Steam client version (build number or date): Steam Runtime Version: steam-runtime_0.20240806.97925
  * Freedesktop SDK 23.08 (Flatpak runtime) (64 bit)
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta? No
* Have you checked for system updates? Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: NVIDIA Corporation NVIDIA GeForce RTX 3060 Laptop (Driver Version: 4.6.0 NVIDIA 470.256.02) (OpenGL Version: 4.6)

#### Please describe your issue in as much detail as possible:
1. It should start a game and should not crash.
2. But instead it crashes when I click on a team.
3. If I am lucky and I can start a game then it has a high chance that it crashes in-game and then it starts validating the source taking precious time. Then I start it again but it doesn't offer me to join to the same game I was playing. If it crashes in-game again, then I have 2 not finished game with the fraction of the points that I could have made if it would not have crashed.

The crashes started after the upgrade and none of the fixes fixed it.

#### Steps for reproducing this issue:

1. start the game 
2. join a lobby
4. click on a team -> 9 of 10 times it crashes
5. if it doesn't crash by joining a team it will crash in-game

**Comment by kisak-valve** [comment]
Hello @zoltan-sule, sorry, but this isn't coherent when directed at this issue tracker (the Steam for Linux client), and there's no hints as to what game you're referring to in order to point you toward the game's support or issue tracker.

**Comment by zoltan-sule** [comment]
Hello @kisak-valve, I reported an issue of CS2 through the UI and I was redirected to this github repository. Where should I report CS2 issues?
