### ISSUE TITLE
csgo not using full gpu in linux

### ISSUE THREAD

**Issue by cowjuice8** [ValveSoftware/steam-for-linux#11357]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): linux mint
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* GPU: Nvidia/Intel/AMD AMD

#### Please describe your issue in as much detail as possible: When i play cs-go on my PC on Linux it never uses the full GPU. I should be getting 200 to 300 fps but i get 180 max and 120 most of the time with drops to 60. the power limit is at about half of the possible draw and the usage percentage hangs from 40 to 60%. i have disabled v sync and frame limit(via fps_max 0) and tried disconnecting all monitors but my primary. the only other games that(i know of) this happens in also are Deep rock galactic and lethal company. the other games i have tested that use the full gpu are crab champions and forza horizon 5. i have corectrl installed and am overclocking. i have tried not overclocking and that doesn't work either. i've also tried using wayland but that too was fruitless
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
specs:
gpu:rx 6600 AMD
cpu: AMD ryzen 5 5500
ram: ddr4 3000mhz
motherboard: asus b550 plus
above 4g decoding:yes

**Comment by kisak-valve** [comment]
Hello @cowjuice8, I'm guessing you're referring to Counter-Strike 2. That issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3338.

General support for Counter-Strike: Global Offensive has ended with the game's relaunch as Counter-Strike 2.

Closing as a duplicate.

**Comment by ilievi187** [comment]
@kisak-valve Can you share some thoughts bout whats is happening 2 years almost issues like this are all across. Do you thing someone gonna fix the issues or they just gonna stay for like 5 more years, because honestly  i know cases bean here stuck forever  like for example display scaling.
