### ISSUE TITLE
Saving controller configs is entirely broken

### ISSUE THREAD

**Issue by Aepoh** [ValveSoftware/steam-for-linux#11367]
I just lost 3 hours worth of progress on making a config when saving it because it reverted to a previous version.

The “Update Layout” and “Save New Layout” buttons do not work properly. Who tested them? Did anyone test them? Does anyone test anything? 

Expected behavior when using the “Save New Layout” button: system takes you to the new layout export dialogue box where you get to give it a name and description.

Actual behavior: Nothing happens. It closes the export window and nothing happens.

**Comment by Aepoh** [comment]
#SteamInputIsBroken

**Comment by kisak-valve** [comment]
Hello @Aepoh, this issue is already being tracked at #10565. Closing as a duplicate.
