### ISSUE TITLE
[General] - "Low Disk Space" toast has broken styling.

### ISSUE THREAD

**Issue by ZereoX** [ValveSoftware/steam-for-linux#11374]
#### Your system information

* Steam client version (build number or date): 1726604483 (Stable) / 1729208001 (Beta)
* Distribution (e.g. Ubuntu): SteamOS 3.5.19 / 3.6.19 / 3.7.0 (Deck) and Manjaro w/ Gnome 46 (Desktop)
* Opted into Steam client beta?: Issue is present on both Stable and Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17496045/steam-logs.tar.gz)
* GPU: AMD Van Gogh RDNA 2.0 (Steam Deck) and RX 7800XT (Desktop)

#### Please describe your issue in as much detail as possible:
When the primary storage device is nearing capacity (<= 2GB of free space), Steam notifies the user via a **Low Disk Space** toast. Instead of expanding from the bottom-right side of the screen, the toast can be seen floating near the bottom.

| Low Disk Space :x: | Low Battery :white_check_mark: (Example) |
| ------------------ | ------------------------------ |
|![Low_Disk_Space](https://github.com/user-attachments/assets/ccacab21-e05b-4ec9-8e58-9deee9a90c25)|![Low_Battery](https://github.com/user-attachments/assets/ea38f58c-7b52-4910-a692-a905807e7405)|

#### Steps for reproducing this issue:

Deck:
1. Open the **SteamOS Devkit Client** (see https://partner.steamgames.com/doc/steamdeck/loadgames to setup Devkit Management Tool).
2. Select the target device and chose **Remote Shell**
3. Run the following command: `fallocate -l 500G temp; rm temp`

Desktop:
1. Launch Steam as a deck-like session via the following terminal command: `gamescope -- steam -gamepadui -steamdeck`.
2. In a terminal window, run the following command: `fallocate -l 500G temp; rm temp`

_Note: Adjust the size parameter of `fallocate` based on your device's storage capacity._

Reproduction Rate: 5/5

#### Affected Platforms
- LCD: Yes
- OLED: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: No. Issue is not present on either the default Steam client or Big Picture Mode.

#### Actual result
- **Low Disk Space** toast appears floating near the bottom of the screen.

#### Expected result
- **Low Disk Space** toast appears as if sliding in from the right-hand side of the screen to resemble more closely other system notification.

#### Notes
- This issue is not present on the similar **Battery Low** system notifications.
- The notification can also be re-triggered when rebooting the device.
- If the notification does not appear immediately, navigating to **Steam > Settings > Storage** will make it pop-up.

**Comment by mikela-valve** [comment]
Thanks @ZereoX. This will be fixed in the next client beta.

**Comment by ZereoX** [comment]
I can confirm this issue is now fixed in Steam Stable (1730853027 - November 5th 2024).

Thanks.

| Low Disk Space :white_check_mark: |
| --------------------------------- |
|![Notification Fixed](https://github.com/user-attachments/assets/4037ff0c-ece7-417c-a42c-36632d42f9ae)|
