### ISSUE TITLE
[Media] - Incorrect screenshot shortcut is shown when viewing an empty media library.

### ISSUE THREAD

**Issue by ZereoX** [ValveSoftware/steam-for-linux#11386]
#### Your system information

* Steam client version (build number or date): 1726683985 (Stable) / 1729208001 (Beta)
* Distribution (e.g. Ubuntu): SteamOS 3.6.19 / 3.7.0 (Deck) and Manjaro w/ Gnome 46 (Desktop)
* Opted into Steam client beta?: Issue is present on both Stable and Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17523554/steam-logs.tar.gz)
* GPU: AMD Van Gogh RDNA 2.0 (Steam Deck) and RX 7800XT (Desktop)

#### Please describe your issue in as much detail as possible:
When viewing the **Media** tab without having any media present the user is informed that they can take a screenshot using the following: <kbd>Steam + A</kbd>

That shortcut however is the Steam button shortcut to **Toggle Manual Recording**.  This issue is also present on Steam Stable even though the **Game Recording** feature is not available.

| Steam Stable | Steam Beta | Steam Chords |
| ------------------- | ----------------- | -------------------- |
|![Stable](https://github.com/user-attachments/assets/be99de6b-cc7c-4dd6-af15-7871bf7ae198)|![Beta](https://github.com/user-attachments/assets/ee446486-0858-4c46-96f7-1840c9a8e44b)|![Chords](https://github.com/user-attachments/assets/533df2ea-1b97-43d3-b6dc-6c864f6f9003)|

#### Steps for reproducing this issue:

1. Navigate to **Steam > Media**.
2. If media is present, press <kbd>☰</kbd> and select **Delete** on all pieces of media.

Reproduction Rate: 5/5

#### Affected Platforms
- LCD: Yes
- OLED: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: Yes, in Big Picture Mode

#### Actual result
- The shortcut of **Toggle Manual Recording** is shown on the **Media** tab instead of the **Take Screenshot**.

#### Expected result
- The **Media** tab shows the **Take Screenshot** shortcut as <kbd>Steam + R1</kbd> instead of <kbd>Steam + A</kbd>.

**Comment by austinp-valve** [comment]
Fixing this in today's beta

**Comment by ZereoX** [comment]
I can confirm this issue is now fixed in Steam Stable (1730853027 - November 5th 2024).

Thanks.

| Screenshot Shortcut :white_check_mark: |
| --------------------------------- |
|![Shortcut Fixed](https://github.com/user-attachments/assets/62369bcc-e2e1-4221-97fb-4e98da71fda3)|
