### ISSUE TITLE
Shader cache not getting compiled

### ISSUE THREAD

**Issue by Revival8697** [ValveSoftware/steam-for-linux#11398]
#### Your system information

* Steam client version: 1729917543
* Distribution: CachyOS Handheld
* Opted into Steam client beta?: Yes, Steam Deck Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17542467/steam-logs.tar.gz)

* GPU: AMD Ryzen Z1 Extreme

#### Please describe your issue in as much detail as possible:
I expected Steam to download shader cache and compile them. Steam downloaded shader cache but did not compile them.
#### Steps for reproducing this issue:

1. Download a game with large amount of shader cache (Counter-Strike 2); or force shader cache to be re-downloaded by disable then enable _Enable Shader Pre-Caching_.
2. Play the game, Steam does not compile shader cache (launch straight into the game).
3. Steam does not compile shader cache in the background with _Allow background processing of Vulkan shaders_ enabled in desktop mode (verify by monitoring _fossilize_ processes).

**Comment by TTimo** [comment]
Hello,

It's not clear from your logs that there is any problem with shader compiling. There are several entries in `shader_log.txt` indicating the start of shader compiling for one game or another (`Starting processing job for app`). The last time you had one for CS2 (730) was on `[2024-10-26 09:44:21] Starting processing job for app 730!`

You may want to move your current Steam Library aside (rename `~/.local/share/Steam`), start from an empty one and install + launch just CS2. See if shaders get processed or not.

I also notice that CachyOS tries to pretend this is a Steam Deck via launch command line options, without being on actual Deck hardware. That may be what's breaking things there but I haven't been able to reproduce.

**Comment by Revival8697** [comment]
> It's not clear from your logs that there is any problem with shader compiling. There are several entries in `shader_log.txt` indicating the start of shader compiling for one game or another (`Starting processing job for app`). The last time you had one for CS2 (730) was on `[2024-10-26 09:44:21] Starting processing job for app 730!`

I thought that shader cache compilation used a lot of CPU over time. However, I didn't see any change in CPU usage, and from the logs, it took seconds (it took hours on my laptop). Am I under the wrong impression?

> You may want to move your current Steam Library aside (rename ~/.local/share/Steam), start from an empty one and install + launch just CS2. See if shaders get processed or not.

I will test this.

**Comment by Revival8697** [comment]
I reinstalled my system and it is working fine so far so closing this.
