### ISSUE TITLE
[General] - Pressing "Back" on the "Running multiple games" prompt will select the "Launch <GAME> anyway" option.

### ISSUE THREAD

**Issue by ZereoX** [ValveSoftware/steam-for-linux#11400]
#### Your system information

* Steam client version (build number or date): 1726683985 (Stable) / 1729917543 (Beta)
* Distribution (e.g. Ubuntu): SteamOS 3.6.19 / 3.7.0 (Deck) and Manjaro w/ Gnome 46 (Desktop)
* Opted into Steam client beta?: Issue is present on both Stable and Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17547176/steam-logs.tar.gz)
* GPU: AMD Van Gogh RDNA 2.0 (Steam Deck) and RX 7800XT (Desktop)

#### Please describe your issue in as much detail as possible:
If a title is already running, attempting to launch another title will prompt the user with a choice selection: **Cancel launch**, **Switch to \<GAME\>**, or **Launch \<GAME\> anyway**.

Pressing <kbd>B</kbd> to **Back** out will select **Launch \<GAME\> anyway**.

##### Video
https://github.com/user-attachments/assets/5dff0431-c9d4-4d5d-813c-a5dee7f70898

#### Steps for reproducing this issue:

1. Select any title and press **Play**.
2. Once the title has launched, navigate to **Steam > Home** and select another title.
3. Press **Play**.
4. Once the **Running multiple games** prompt appears, press <kbd>B</kbd>.

Reproduction Rate: 5/5

#### Affected Platforms
- LCD: Yes
- OLED: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: No (This prompt does not appear in Big Picture Mode on Desktop)

#### Actual result
- Pressing **Back** / <kbd>B</kbd> dismisses the prompt, but behaves as if **Launch <GAME> anyway** was selected.

#### Expected result
- Pressing **Back** / <kbd>B</kbd> should dismiss the prompt and return the user to the **Game Details Page**. Secondary title should only launch if **Launch \<GAME\> anyway** is explicitly selected.
- Alternatively provide an option to close all running titles and proceed with launch.

**Comment by mikela-valve** [comment]
Thanks @ZereoX. This will be fixed in the next client update.
