### ISSUE TITLE
Steam client installs some missing extras in the distro

### ISSUE THREAD

**Issue by Veryfun616** [ValveSoftware/steam-for-linux#11408]
Hi, Suggestion: if possible, if you see this as viable, the Steam client download and install the codecs and additional things that Steam see that are missing, which are not yet installed from the distro, at the time of installation and in future Steam updates.
So that everything works perfectly, chromium hardware acceleration will fully enable, etc.

Such as gstreamer, libavcodec, openh264, vaapi, ffmpeg, etc.

Good luck always.

**Comment by kisak-valve** [comment]
Hello @Veryfun616, the Valve-provided Steam package already requests known dependencies that need to come from the host system and provides the rest for itself.

If there's a specific library that you know is needed and missing, then that specific scenario should be evaluated. If you're using a distro-provided Steam package, then it would be more productive to follow up with your distro's package maintainer(s) for their Steam package.
