### ISSUE TITLE
"Copy to Clipboard" in Screenshots Manager is broken

### ISSUE THREAD

**Issue by EricZhang456** [ValveSoftware/steam-for-linux#11411]
#### Your system information

* Steam client version (build number or date): 1726604483
* Distribution (e.g. Ubuntu): Arch Linux w/ KDE on X
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17588822/steam-logs.tar.gz)
* GPU: Nvidia with Optimus

#### Please describe your issue in as much detail as possible:
Right clicking on a screenshot in the Screenshot Manager and selecting "Copy to Clipboard" should copy the image to the clipboard

#### Steps for reproducing this issue:

1. Take a screenshot in-game by pressing F12
2. Go to View -> Screenshots and select one of the screenshots
3. Right click on the screenshot and select "Copy to Clipboard"
4. The screenshot is not copied to the clipboard

**Comment by kisak-valve** [comment]
Hello @EricZhang456, per #11048, please opt into Steam's client beta and retest.

**Comment by EricZhang456** [comment]
It works in the beta client

**Comment by komasio71** [comment]
still broken to this day...

**Comment by MrMcyeet** [comment]
Unsure if this is been reintroduced or a new bug, but this still is happening, even on the beta branch.

**Comment by m-alice** [comment]
Does not work in the latest beta version 1789086785
