### ISSUE TITLE
Smoke being totaly glitched and can see through 

### ISSUE THREAD

**Issue by CeiLciuZ** [ValveSoftware/steam-for-linux#11422]
#### Your system information

* Steam client version (build number or date):  1726604483
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia 3050TI for laptop

hi,
i play on this game and since CS2
when maybe 2 or 3 smoke draw on my screen i can see trough
can u tell me how can i do

i play with the linux version, on last stable version of the game, and last stable version of steam linux, my GPU drivers are update, and my OS too

have a good day

PS: when the glitch happen to me i just look the ground and shoot nobody.. i'm not a cheater

---------------
OS: Arch Linux x86_64
Host: GF63 Thin 11UC REV:1.0
Kernel: 6.11.3-arch1-1
Uptime: 4 hours, 54 mins
Packages: 955 (pacman)
Shell: bash 5.2.37
Resolution: 1920x1080
DE: Plasma 6.2.1
WM: KWin
Theme: Breeze-Dark [GTK2], Breeze [GTK3]
Icons: breeze-dark [GTK2/3]
Terminal: konsole
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz
GPU: Intel TigerLake-H GT1 [UHD Graphics]
GPU: NVIDIA GeForce RTX 3050 Mobile
Memory: 4586MiB / 31798MiB

#### Steps for reproducing this issue:

1 . multiple smoke in alignement of view
![image](https://github.com/user-attachments/assets/bb0c165d-4b3e-4823-a1bd-040c80f1bb11)

**Comment by kisak-valve** [comment]
Hello @CeiLciuZ, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3882. Closing as a duplicate.

**Comment by CeiLciuZ** [comment]
Ok, how play without being repport for cheat if i kill someone through smoke without know a smoke is here 🤣

Anyway, i've add -vulkan in start option and for moment i don't get the glitch again

I think the glitch come over, when my vram is overflow, all smoke type particles aren't renderend ( molotov smoke, HE explosion particles, and smoke)

Since -vulkan maybe the vram have better traitement and my vram dosn't overflow anymore

Big mapping is more sensitive to this bug ( inferno in banana, inferno on A site , dust2 on long, dust 2 on window site B, dust2 on top mid, mirage on A site )
