### ISSUE TITLE
Missing xrandr binary in Steam runtime breaks Slay the Spire

### ISSUE THREAD

**Issue by kkurczewski** [ValveSoftware/steam-for-linux#11437]
#### Your system information

* Steam client version (build number or date): 1730853027
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: N/A
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

After recent Steam runtime update **[Slay the Spire](https://store.steampowered.com/app/646570/Slay_the_Spire/)** fails to start due to missing **[xrandr](https://x.org/releases/X11R7.5/doc/man/man1/xrandr.1.html)** binary. Multiple people reported this problem in last few days:

https://steamcommunity.com/app/646570/discussions/1/4626979420667653742/
https://steamcommunity.com/app/646570/discussions/1/4626979420667648411/
https://steamcommunity.com/app/646570/discussions/1/4628104871029020787/

#### Steps for reproducing this issue:

1. Start game via Steam
2. Game fails with following exception:
```
09:33:33.530 INFO desktop.DesktopLauncher> Launching application...
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:558)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 2 more
```

Which can be traced to this [line](https://github.com/LWJGL/lwjgl/blob/2df01dd762e20ca0871edb75daf670ccacc89b60/src/java/org/lwjgl/opengl/LinuxDisplay.java#L953) and further to this [command](https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/opengl/XRandR.java#L72).

Running it manually from jar (it is based on Java engine) works without issue (granted binary is installed).

**Comment by kisak-valve** [comment]
Hello @kkurczewski, this issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/702. Closing as a duplicate.

**Comment by smcv** [comment]
Fixed in yesterday's beta, [details here](https://github.com/ValveSoftware/steam-runtime/issues/702#issuecomment-2473390139)
