### ISSUE TITLE
Steam permanently disables screensaver, monitor suspend, and system suspend even when steam is not running

### ISSUE THREAD

**Issue by dpantel** [ValveSoftware/steam-for-linux#11443]
#### Your system information

* Steam client version (build number or date): 1730853027 / Tue, Nov 5 14:33 UTC -07:00
* Distribution (e.g. Ubuntu): Linux Mint 22
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: attached
* GPU:  Intel® UHD Graphics 770

#### Please describe your issue in as much detail as possible:

After installing and using Steam, my screensaver and suspend settings have been permanently disabled. As a result, the screensaver never turns on, the session never locks, the monitor never goes to sleep, and the system does not go into suspend mode.

This is different than other reported bugs because this happens even when I completely quit steam. So trying to use options like `-disable-screensaver-inhibit` does not do anything.

#### Steps for reproducing this issue:

1. Install steam
2. Use steam

[steam-logs.tar.gz](https://github.com/user-attachments/files/17690144/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @dpantel, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/11354. Since your logs might have a hint for a Steam dev to ponder, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/11354#issuecomment-2466743519.

**Comment by dpantel** [comment]
Those issues all describe steam inhibiting screensaver when it’s running but idle. My issue is that the behavior persists even after steam is stopped. But if you think it’s the same problem, that’s fine.

**Comment by kisak-valve** [comment]
Re-reading #11354, you are correct. It should be evaluated separately.

**Comment by kisak-valve** [comment]
Please reproduce the issue with Steam run with `steam -verbose-screensaver-inhibit -verbose-computer-activity` and share an updated set of console*.txt logs, which is found in `<steam install folder>/logs/`. That should make it easier for a Steam dev to see how that sub-component was behaving up until Steam closed down.

**Comment by dpantel** [comment]
Unfortunately there is no "reproducing". My screensaver, etc is now permanently non-functional (unless I activate it manually). It will not automatically activate despite being set up to do so.

It would be helpful to know how I can reset whatever Steam did to the screensaver/power settings.

[console-linux.txt](https://github.com/user-attachments/files/17692599/console-linux.txt)
[console_log.txt](https://github.com/user-attachments/files/17692600/console_log.txt)

**Comment by RaiderZulu** [comment]
This has been happening to me as well for, I think a few years?  It most often happens now after running Resonite in VR though Proton.

**Comment by TTimo** [comment]
> Unfortunately there is no "reproducing". My screensaver, etc is now permanently non-functional (unless I activate it manually). It will not automatically activate despite being set up to do so.

To be clear, you are saying that your system is in such a state now that you can be powered off, boot up, not start the steam client at all, and your screensaver doesn't activate anymore when it used to, and you believe Steam caused this.

Steam calls to SDL to disable the screensaver: https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11events.c#L2061

Whether this goes through the DBus path or the X11 path, we don't know of a way these APIs could cause the screensaver to stop working permanently.

**Comment by dpantel** [comment]
Not sure what happened but I can no longer reproduce the issue after a reboot.
Screensaver/monitor suspend/pc suspend is now working properly.

**Comment by RaiderZulu** [comment]
> > Unfortunately there is no "reproducing". My screensaver, etc is now permanently non-functional (unless I activate it manually). It will not automatically activate despite being set up to do so.
> 
> To be clear, you are saying that your system is in such a state now that you can be powered off, boot up, not start the steam client at all, and your screensaver doesn't activate anymore when it used to, and you believe Steam caused this.
> 
> Steam calls to SDL to disable the screensaver: https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11events.c#L2061
> 
> Whether this goes through the DBus path or the X11 path, we don't know of a way these APIs could cause the screensaver to stop working permanently.

Something in this is where it goes wrong most often for me.  I am almost always seeing an orphan "My SDL Application" in the Cinnamon Inhibit Applet when Steam causes it.  Right now it reports that "Steam" is inhibiting, but it is not actually inhibiting.  The API, applet, or both, clearly have some deep running bugs that need to be fixed.
