### ISSUE TITLE
Steam games not starting anymore from library in /usr/games/

### ISSUE THREAD

**Issue by graham2071** [ValveSoftware/steam-for-linux#11445]
#### Your system information

* Steam client version (build number or date): 
```
Steam Beta Branch:  Stable Client
Steam Version:  1730853027
Steam Client Build Date:  Tue, Nov 5 10:33 PM UTC +01:00
Steam Web Build Date:  Wed, Nov 6 1:21 AM UTC +01:00
Steam API Version:  SteamClient021
```
* Distribution (e.g. Ubuntu): 
```
Command: cat /etc/os-release
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
```
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: see below
* GPU: Intel

#### Please describe your issue in as much detail as possible:
All games fail to start !
Running steam from terminal, there are warnings

```console
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_DATA_PATH="/usr/games/SteamLibrary/steamapps/compatdata/718670" with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_INSTALL_PATH="/usr/games/SteamLibrary/steamapps/common/Cultist Simulator" with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_LIBRARY_PATHS="...:/usr/games/SteamLibrary/steamapps:..." with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_MOUNTS="...:/usr/games/SteamLibrary/steamapps/common/SteamLinuxRuntime:..." with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_MOUNTS="...:/usr/games/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier:..." with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Not sharing path STEAM_COMPAT_SHADER_PATH="/usr/games/SteamLibrary/steamapps/shadercache/718670" with container because "/usr" is reserved by the container framework
pressure-vessel-wrap[15267]: W: Unable to share "/usr/games/SteamLibrary/steamapps/common/Cultist Simulator" with container: Path "/usr" is reserved by the container framework
```

Here is the workaround:
1. From Steam Settings / Storage: removed steamlibrary (in '/')
2. moved SteamLibrary to /opt with `sudo mv /usr/games/SteamLibrary /opt`
3. From Steam Settings / Storage: added SteamLibrary located in /opt/SteamLibrary

Now everything works again.

#### Steps for reproducing this issue:

1. Start steam
5. "Play" any game installed in `/usr/games/SteamLibrary`

**Comment by kisak-valve** [comment]
Hello @graham2071, this is an expected side effect of `Native titles will execute in 'Steam for Linux runtime 1.0 (scout)' by default, instead of the legacy runtime environment.` in the ['2024-11-05](https://store.steampowered.com/news/app/593110/view/4472730495692571024) Steam client update leading to https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#usrlocal.

Having user-controlled Steam library folders under /usr isn't something that can be supported sanely in that runtime environment and this is unlikely to change in the near future. Closing as won't fix.

**Comment by graham2071** [comment]
Thanks for letting me know. I could find this info with google.
Since it took me a bit of time to find what was going wrong, I've posted here hoping it can help others with the same issue.
