### ISSUE TITLE
Steam stuck in infinite loading if launched from pin

### ISSUE THREAD

**Issue by strattonbrazil** [ValveSoftware/steam-for-linux#11456]
#### Your system information

* Steam client version (build number or date): 1731433018
* Distribution (e.g. Ubuntu): Ubuntu 24.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17734516/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
On this machine on Ubuntu 22.04 I noticed after some point that the Steam icon didn't load Steam anymore. Instead I would see the Steam icon appear in the top right of the screen with the other "applets", but the UI would never show up and clicking on the applet pulldowns didn't do anything. 

I lated reinstalled 24.04 with a new GPU and after a fresh install experienced the same thing. 

The app seems to be in a permanent loading loop. It will steal focus from other apps every few seconds. 

Logs from a specific start: 
https://gist.github.com/strattonbrazil/758efc1066ee2802fbf04a002b0e2c9e

If I run `steam` directly from the command line though, the app starts fine. 

#### Steps for reproducing this issue:

1. Click on `Steam` in the Ubuntu launcher
2. Watch while the app continually tries to start

**Comment by kisak-valve** [comment]
Hello @strattonbrazil, you've described the issue being tracked at #9383. Closing as a duplicate.
