### ISSUE TITLE
Horizon Forbidden West accumulates graphics/audio errors and then crashes

### ISSUE THREAD

**Issue by ExecutorElassus** [ValveSoftware/steam-for-linux#11462]
#### Your system information

* Steam client version (build number or date): 2024-11-05
* Distribution (e.g. Ubuntu): Gentoo Linux
* Opted into Steam client beta?: Yes (but reverted it because the beta client has no in-game sound)
* Have you checked for system updates?: Yes
* Steam Logs: attached
[steam-logs.tar.gz](https://github.com/user-attachments/files/17748026/steam-logs.tar.gz)
* GPU: AMD (Radeon RX 5700 XT)

#### Please describe your issue in as much detail as possible:
Since last week's update the game rapidly accumulates the following errors:
* tall grass proliferates in environments where it shouldn't be (ie, covers an entire hillside where normally it's just a couple isolated clumps, or fills an entire settlement)
* the in-game map won't load, showing instead a black screen (even though hovering the mouse around the screen causes the sound of the map _as if_ the map is there)
* certain audio channels stop: music, dialogue with NPCs, most environmental sound, most combat sounds; but _not_ the sounds of footsteps. 
* the "compiling shaders" black screen starts interrupting gameplay
* certain campfires (which are the quick-save points) stop working
* clothes start showing scrambled textures
* at this point, I have to save and restart the game, because  it freezes not long after.

#### Steps for reproducing this issue:

1. steam client auto-updates from last week's update
2. play the game for maybe 20 minutes
3. start noticing problems

I did not have any of these problems after the game updated to its current version over the summer. This only started happening after the Steam client updated last week. I am using GE-Proton-9.{11,15,19}, but that doesn't seem to have any effect.

**Comment by kisak-valve** [comment]
Hello @ExecutorElassus, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7590#issuecomment-2474765658.
