### ISSUE TITLE
Error appears when trying to launch source mod

### ISSUE THREAD

**Issue by prufaraSS** [ValveSoftware/steam-for-linux#11481]
#### Your system information

* Steam client version (build number or date): Tue, Nov 12 11:10 PM UTC -08:00
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: No
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17789675/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
I'm launching Half-Life 2 source mod (pre 20 anniversary) and expected to see Vulkan shader processing, but _sometimes_ instead I see a black box appearing at window top which shifts whole UI down and cutting bottom part of UI. The message is something about can't show 'display_name' (I'll show a screenshot of this error when it'll happen again)

#### Steps for reproducing this issue:

1. Install source mod
2. Reload steam
3. Launch the mod
4. Wish for bug to randomly appear

**Comment by kisak-valve** [comment]
Hello @prufaraSS, this issue is already being tracked at #11291. Closing as a duplicate.
