### ISSUE TITLE
powerprofilesctl no longer works as a wrapper command

### ISSUE THREAD

**Issue by griffi-gh** [ValveSoftware/steam-for-linux#11483]
#### Your system information

* Steam client version (build number or date): 1731433018
* Distribution (e.g. Ubuntu): NixOS (`nixos-unstable`)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17790929/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
`powerprofilesctl launch` used to work as a wrapper command, but does not anymore.\
It broke more than a month ago i think? After one of the Steam client/runtime updates.

#### Steps for reproducing this issue:

1. Set `powerprofilesctl launch %command%` as command for any game
2. The game won't launch and will fail with following errors:

```
chdir "/home/user/.local/share/Steam/steamapps/common/Half-Life 2"
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game Recording - would start recording game 220, but recording for this game is disabled
Adding process 20135 for gameID 220
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
steam-launch-wrapper: Unrecognised option /home/user/.local/share/Steam/ubuntu12_32/reaper
Game Recording - game stopped [gameid=220]
Removing process 20135 for gameID 220
```

**Comment by kisak-valve** [comment]
Hello @griffi-gh, this issue needs to be reported to and evaluated by the third party utility's dev(s).

**Comment by smcv** [comment]
> Set `powerprofilesctl launch %command%` as command for any game

Depending on how powerprofilesctl does its command-line parsing, `powerprofilesctl launch -- %command%` might work better.
