### ISSUE TITLE
Ubuntu Realtime Kernel From PRO problems

### ISSUE THREAD

**Issue by he11ah0und** [ValveSoftware/steam-for-linux#11493]
#### Your system information

* Steam client version (build number or date): Wed, Nov 13 3:10 AM UTC +10:00
* Distribution (e.g. Ubuntu): Kubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17811494/steam-logs.tar.gz)
* GPU: Nvidia (565.57.01)

#### Please describe your issue in as much detail as possible:
instability with steam and some games like cs2
bugs with smokes (transparent) in cs2
lag spikes in cs2
breaked SDR, from RU to JP no direct route, only through Honkong or Seoul
Seoul as Direct Route (nope, only through japan, so triple ping if it trying to connect to japan through seoul)
or connects to Japan through Honkkong so got 190ms ping

but if trying to 'ping' every servers of SDR official in json TYO, got ~40ms like normal 

All on tested on Rostelecom

after migrating from ubuntu_rt pro (service) to xanmod_rt kernel all works like to be

#### Steps for reproducing this issue:

1. use steam from flatpak
2. use ubuntu pro to install realtime kernel
3.

**Comment by kisak-valve** [comment]
Hello @he11ah0und, if a Linux kernel update induces a regression, that needs to be reported to the kernel dev(s) who maintain that kernel build.
