### ISSUE TITLE
issue steam shows me as in game when i'm not

### ISSUE THREAD

**Issue by reapingdarkly** [ValveSoftware/steam-for-linux#1149]
After playing a game in steam from a windows pc and turning that pc off then signing into the steam client on ubuntu 12.04 it still shows me as playing the game I had open on windows. As steam thinks I'm in game it wont let me sign out or quit steam from ubuntu, 
it will let me play other games that I have installed but won't show that I'm playing said game. Even after quitting that game it will still show me as playing the game I was in while in windows.

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1600 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-36-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6310 Graphics

```
Driver Version:  4.2.11978 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9802
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20.43" x 12.76"  (24.06" diag)
                                        51.9cm x 32.4cm  (61.1cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  7591 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  696508 Mb
    Largest Free Hard Disk Block:  549567 Mb

Installed software:

Recent Failure Reports:
    Thu Jan 31 22:48:18 2013 GMT: file ''/tmp/dumps/assert_20130131224812_1.dmp'', upload yes: ''CrashID=bp-6bf65ee1-4a34-4771-9cb0-93d3f2130131''
    Fri Feb  1 00:20:14 2013 GMT: file ''/tmp/dumps/assert_20130201002012_1.dmp'', upload yes: ''CrashID=bp-bcdfecb3-58aa-49bd-8742-8497f2130131''
    Fri Feb  1 00:26:34 2013 GMT: file ''/tmp/dumps/assert_20130201002632_2.dmp'', upload yes: ''CrashID=bp-25f310d9-ba41-4849-87d9-957432130131''
    Fri Feb  1 11:20:05 2013 GMT: file ''/tmp/dumps/assert_20130201112003_1.dmp'', upload yes: ''CrashID=bp-aa11acba-54f8-4d1d-b6c5-40cda2130201''
    Fri Feb  1 11:30:33 2013 GMT: file ''/tmp/dumps/assert_20130201113031_2.dmp'', upload yes: ''CrashID=bp-3c740c1d-61c8-4c06-8fef-9b24d2130201''
    Fri Feb  1 11:38:05 2013 GMT: file ''/tmp/dumps/assert_20130201113802_1.dmp'', upload yes: ''CrashID=bp-617617b1-0c2f-4961-a3aa-76aa72130201''
    Fri Feb  1 11:38:28 2013 GMT: file ''/tmp/dumps/assert_20130201113825_2.dmp'', upload yes: ''CrashID=bp-c6585206-ea8b-431c-a0f7-22b512130201''
    Fri Feb  1 11:40:48 2013 GMT: file ''/tmp/dumps/assert_20130201114045_1.dmp'', upload yes: ''CrashID=bp-2426b968-0cec-405b-90c8-0732e2130201''
    Fri Feb  1 11:41:08 2013 GMT: file ''/tmp/dumps/assert_20130201114106_2.dmp'', upload yes: ''CrashID=bp-a00289e8-9dfa-4d03-b309-267542130201''
    Fri Feb  1 11:43:30 2013 GMT: file ''/tmp/dumps/assert_20130201114327_1.dmp'', upload yes: ''CrashID=bp-dd8f7829-9750-458f-9b46-e4ea02130201''
    Fri Feb  1 11:43:58 2013 GMT: file ''/tmp/dumps/assert_20130201114356_2.dmp'', upload yes: ''CrashID=bp-c00d4850-b8b1-47ce-ad5a-a46fa2130201''
    Fri Feb  1 11:46:59 2013 GMT: file ''/tmp/dumps/assert_20130201114657_1.dmp'', upload yes: ''CrashID=bp-0fe40ce4-a27e-4682-9ce2-15b0d2130201''
    Fri Feb  1 11:47:39 2013 GMT: file ''/tmp/dumps/assert_20130201114736_2.dmp'', upload yes: ''CrashID=bp-9d507188-a0e1-4e8f-8069-af7522130201''

**Comment by kisak-valve** [comment]
Hello @reapingdarkly, if you are still experiencing this issue with an up to date system, please open a new issue report.
