### ISSUE TITLE
Steam client have very small font size on monitor with 2k or 4k resolution

### ISSUE THREAD

**Issue by VladimirMrzv** [ValveSoftware/steam-for-linux#11490]
#### Your system information

* Steam client version (build number or date):  1731716808
* Distribution (e.g. Ubuntu):  Ubuntu Unity 24.10
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD - AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I have monitor with resolution 3440x1440 and TV 3840x2160 . All text in steam are very small and difficult to read. Steam does not have option to change font size only size for element in library.
![image](https://github.com/user-attachments/assets/3cf3a371-9b05-4e5b-9b20-2ebf29813d31)

I think it would be good thing have an option to scale size for text. Not only in interface and also in game launchers.

#### Steps for reproducing this issue:

1. Start steam on monitor with 2k or 4k resolution.

**Comment by kisak-valve** [comment]
Hello @VladimirMrzv, this issue is already being tracked at #11189. Closing as a duplicate.
