### ISSUE TITLE
Steam update download dialog missing font

### ISSUE THREAD

**Issue by Bodyash** [ValveSoftware/steam-for-linux#11516]
#### Your system information

* Steam client version (build number or date): Steam 1726088054
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Steam Update download dialog missing font for non English characters (in my case my Steam client is in Ukrainian language)
![image](https://github.com/user-attachments/assets/048f9e5b-2772-4c6c-aa7c-2b097a48857b)

This bug exists for many years on many distros I've used.

**Comment by kisak-valve** [comment]
Hello @Bodyash, this issue is already being tracked at #8006. Closing as a duplicate.
