### ISSUE TITLE
half life 2 is freeze dont start dont working linux ubuntu 22.04.5 LTS NVIDIA Driver Version 560.35.03

### ISSUE THREAD

**Issue by foxfox843** [ValveSoftware/steam-for-linux#11525]
half life 2 is freeze dont start dont working here is system informations and screenshots then game is start
is download but half life 2 is freeze nothing is happen game dont start dont working 
22.04.5 LTS NVIDIA Driver Version 560.35.03

Computer Information:
Manufacturer: EVGA INTERNATIONAL CO.,LTD
Model: EVGA E672
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
CPU Family: 0x6
CPU Model: 0x3a
CPU Stepping: 0x9
CPU Type: 0x0
Speed: 3900 MHz
4 logical processors
4 physical processors
Hyper-threading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
BMI1: Unsupported
BMI2: Unsupported
F16C: Supported
FMA: Unsupported
Operating System Version:
Ubuntu 22.04.5 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.8.0-49-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101004
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20241024.105847
Client Information:
Version: 1731433018
Browser GPU Acceleration Status: Disabled
Browser Canvas: Unavailable
Browser Canvas out-of-process rasterization: Disabled
Browser Direct Rendering Display Compositor: Disabled
Browser Compositing: Disabled
Browser Multiple Raster Threads: Enabled
Browser OpenGL: Disabled
Browser Rasterization: Disabled
Browser Raw Draw: Disabled
Browser Skia Graphite: Disabled
Browser Video Decode: Disabled
Browser Video Encode: Disabled
Browser Vulkan: Disabled
Browser WebGL: Unavailable
Browser WebGL2: Unavailable
Browser WebGPU: Disabled
Browser WebNN: Disabled
Video Card:
Driver: Mesa llvmpipe (LLVM 15.0.7, 256 bits)
Driver Version: 4.5 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x13c2
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55" (21.54" diag), 47.7cm x 26.8cm (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 7168 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Realtek ALC889
Memory:
RAM: 11924 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: fi_FI.UTF-8
Total Hard Disk Space Available: 937291 MB
Largest Free Hard Disk Block: 501198 MB
Storage:
Number of SSDs: 1
SSD sizes: 1000G
Number of HDDs: 0
Number of removable drives: 0
![Kuvakaappaus - 2024-11-28 06-56-59](https://github.com/user-attachments/assets/43f0c13c-1ec8-46e3-8005-40df7e263430)
![Kuvakaappaus - 2024-11-28 06-57-00](https://github.com/user-attachments/assets/7a5cdaeb-57fe-4f94-8347-e8c430f6ca0a)
![Kuvakaappaus - 2024-11-28 06-57-01](https://github.com/user-attachments/assets/db66d3ff-4bcd-4f25-b00b-eb533e3caa89)
![Kuvakaappaus - 2024-11-28 06-57-03](https://github.com/user-attachments/assets/d4c68deb-22ba-4c5d-bea5-c0d1b4bfd797)
![Kuvakaappaus - 2024-11-28 06-57-12](https://github.com/user-attachments/assets/ebb7af49-3db3-4e8b-aa33-ac6fabe0c5c9)
![Kuvakaappaus - 2024-11-28 06-58-06](https://github.com/user-attachments/assets/37f1a87f-2c95-44e6-84e5-c4c3aa8927b1)
![Kuvakaappaus - 2024-11-28 06-58-07](https://github.com/user-attachments/assets/a80bc42e-9694-4bfc-b772-045b1a1ecc11)
![Kuvakaappaus - 2024-11-28 06-58-09](https://github.com/user-attachments/assets/fd117885-0420-4504-816f-5df7c63f104b)
![Kuvakaappaus - 2024-11-28 06-58-09-1](https://github.com/user-attachments/assets/bfa7ab19-6e01-48fc-9af6-8415d1e8190a)
![Kuvakaappaus - 2024-11-28 06-58-13](https://github.com/user-attachments/assets/30f88545-2e8f-4820-b171-b41eec26d09c)
![Kuvakaappaus - 2024-11-28 06-58-14](https://github.com/user-attachments/assets/67bbaf0a-2281-416f-9647-dab63a063173)

**Comment by kisak-valve** [comment]
Hello @foxfox843, ` Driver: Mesa llvmpipe (LLVM 15.0.7, 256 bits)` in your system information tells us that your NVIDIA driver install is incomplete and likely missing the driver's 32 bit userspace libraries. The game is being forced to fallback to mesa's CPU renderer instead of using your video card.

This is a video driver packaging issue, not a game issue and needs to be resolved by the package maintainer(s) of the NVIDIA driver. Assuming this is https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa/+sourcepub/16508159/+listing-archive-extra where the i386 (32 bit) packages are missing.

The quick fix would be to switch to a driver release that isn't missing i386 packages.
