### ISSUE TITLE
Linux Native Games now all use "Steam Play" and "Steam Linux Runtime" despite not forcing any compatibility tool.

### ISSUE THREAD

**Issue by CaptainCoward** [ValveSoftware/steam-for-linux#11545]
#### Your system information

* Steam client version (build number or date): 
Steam Beta Branch:  Stable Client
Steam Version:  1733265492
Steam Client Build Date:  Mon, Dec 2 10:26 PM UTC -08:00
Steam Web Build Date:  Mon, Dec 2 10:20 PM UTC -08:00
Steam API Version:  SteamClient021

* Distribution (e.g. Ubuntu): 
EndeavourOS
* Opted into Steam client beta?: [Yes/No]
No

#### Please describe your issue in as much detail as possible:
All games that seem that used to run native now instead run with Steam Play and there seems to be no way to actually run any game native anymore.

#### Steps for reproducing this issue:

1.  Enable "Steam Play for all other Titles" in Settings and choose Any Proton for "Run other titles with"
2.  Check out any Native Linux games by checking its page
3.  see the following result:
![grafik](https://github.com/user-attachments/assets/efc8b95f-21bc-494c-8458-62bb946ae172)
![grafik](https://github.com/user-attachments/assets/da9bcb1e-067f-4819-b170-b1163081d2f5)

**Comment by kisak-valve** [comment]
Hello @CaptainCoward, this is an intentional change in the Steam client per
```
Native titles will execute in 'Steam for Linux runtime 1.0 (scout)' by default, instead of the legacy runtime environment.
This behavior is consistent with Steam Deck and promotes better compatibility across all Linux desktop distributions.
Note that this new feature can be turned off globally with "-compat-force-slr off" on the Steam client command line.
```
in the [2024-11-05](https://store.steampowered.com/news/app/593110/view/4472730495692571024) Steam client update.

Note that this is still the Linux native variant of the game being used, it's just being run in the Steam Linux Runtime 1.0 (scout) container environment instead of the LD_* style legacy runtime environment.
