### ISSUE TITLE
on launch will update compatdata "0" with every proton version in the compatibilitytools.d

### ISSUE THREAD

**Issue by silverhikari** [ValveSoftware/steam-for-linux#11550]
#### Your system information

* Steam client version (build number or date): 1733265492
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18050208/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

after waiting a few minutes on the steam client(doesn't matter if in the store or library) in the background a compatdata folder named "0" will update it's prefix with every proton version in the compatibilitytools.d folder. this will happen every time steam is launched unless you only have 1 proton version in compatibilitytools.d. if the prefix "0" is deleted it will be remade on the next steam launch and updated with every proton version.

i have tested and this effects both the stable steam client and the beta client as of 12/7/24

i have tested and this problem is not specific to GE-Proton and also effects wine-tkg-proton(i have installed them via protonup-qt)

i have tested with the latest versions of GE-Proton and Wine-tkg-Proton along with older versions, and does not seem to matter

i am running steam with the steam runtime on manjaro not the native version

#### Steps for reproducing this issue:

1. have 1 or more proton-based compatibility tool in compatibilitytools.d
2. open steam in a terminal(this is used to show the prefix updates)
3. look for lines in the terminal such as "Proton: Upgrading prefix from x to y ($HOME/.local/share/Steam/steamapps/compatdata/0/)"

**Comment by kisak-valve** [comment]
Hello @silverhikari, this issue is already being tracked at #8114. Closing as a duplicate.
