### ISSUE TITLE
Steam generates double/phantom input when HID driver is in use

### ISSUE THREAD

**Issue by hikagura99** [ValveSoftware/steam-for-linux#11565]
* Steam client version (build number or date): 1733944536
* Distribution: Arch Linux 
* Opted into Steam client beta? Yes, but the issue persists on the stable as well
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18115441/steam-logs.tar.gz)
* GPU: AMD

This post is a follow up  to #11509, i found some more info:
- The issue appears only when udev rules for the kernel to load controllers on my system as HID devices are triggered;
- The issue arises with all kind of controllers, both cabled and wireless, both first party and third party (Hori Horipad S, Dualshock 4, Fineblue PS3 controller, Joycons), and not only with the Hori one contrary to what I mentioned in the previous report;
- The issue arises with all steam games, and not only with some games contrary to what I mentioned in the previous report;
- The system and the local (non steam) games opened outside of steam work flawlessly when the controller is loaded through HID, and the opposite is true when HID is unloaded. This does not change even when a global SDL config environmental variable is called at boot and/or at launch.

All of this showed up around a month ago. I tried changing kernels just to make sure (hopped from zen to vanilla), but the issue is still there.
There's little to no info or reports on the internet, so it might actually be just a problem of mine and I'm quite literally lost, so if you'd want to ask any questions or experiments I could try I'm pretty much eager to try whatever.

#### Steps for reproducing this issue:

1.  Have a file for your controller of choice with udev rules to load it via HID, e.g.
`# Hori HORIPAD S; USB`
`KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00c1", MODE="0660", TAG+="uaccess"
`;
2. If not present already, run `udevadm control --reload-rules && udevadm trigger` and reboot
3. Launch any steam or non-steam game and see results;
4. Try the opposite (you might want to remap the controller in steam first).

**Comment by kisak-valve** [comment]
Hello @hikagura99, I'm not seeing any details here that makes this a distinctly different issue from your previous issue report, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/11509#issuecomment-2501035349.

Closing as a duplicate.
