### ISSUE TITLE
Steam launch issues

### ISSUE THREAD

**Issue by eons93** [ValveSoftware/steam-for-linux#11560]
#### Your system information

* Steam client version (build number or date): 1733265492
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/user-attachments/files/18088330/steam-logs.tar.gz)`]
* GPU: AMD

The issue started when I switched my graphics card from a Nvidia to an AMD. I suspect the underlying issue is something relating to drivers but to the best of my ability, it seems I have the proper elements installed.

What happens is that when I start Steam via the Icon I  have pinned to my taskbar, the client window will pop up briefly and then disappear. A few seconds will go by and the window will blink back into existence and disappear (a few frames, quarter second max). 

To work around this issue, I have to run the command [steam] from terminal which starts steam with no issue (though steam is behaving weirdly even then, unsure if that is a side effect of running steam via terminal or additional issues in general). This works more or less but Steam does seem to crash if I leave it running for too long (hours on end). 

#### Steps for reproducing this issue:

1. Start Steam via Icon 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @eons93, this issue is already being tracked at #9383. Closing as a duplicate.
