### ISSUE TITLE
Black Mesa reproducible crashing on Unforseen Circumstances level when entering water

### ISSUE THREAD

**Issue by outlandist** [ValveSoftware/steam-for-linux#11561]
#### Your system information

* Steam client version (build number or date): 

> Steam Beta Branch:  Stable Client
> Steam Version:  1733265492
> Steam Client Build Date:  Mon, Dec 2 10:26 PM UTC -08:00
> Steam Web Build Date:  Mon, Dec 2 10:20 PM UTC -08:00
> Steam API Version:  SteamClient021

* Distribution (e.g. Ubuntu): 
> Ubuntu 24.04.1 LTS
* Opted into Steam client beta?: [Yes/No] 
> No
* Have you checked for system updates?: [Yes/No] 
> Yes
* Steam Logs: [generate by running this command in a terminal 
> Note: provided log path is incorrect for Ubuntu 24.04. Path should be ~/snap/steam/common/.steam/steam/logs for tar command
[steam-logs.tar.gz](https://github.com/user-attachments/files/18092935/steam-logs.tar.gz)`]
* GPU: 
> Nvidia (Gigabye Geforce RTX 4080 Super)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The game crashes when playing the Unforseen Circumstances level as soon as you enter water. This happens every time on any level of graphical settings that work. Game won't play with overall setting less than Medium. I tried individually turning down settings to minimum also, but this didn't prevent the crash.
The crash also corrupts the save. 

The error message displayed is: 
> failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=-12, nFirstVertex=28156

#### Steps for reproducing this issue:

1. Start Unforseen Circumstances level in Black Mesa
2. Jump in water or trigger an explosion (such as the mortar strike)
3. Crash with provided error message

**Comment by kisak-valve** [comment]
Hello @outlandist, this issue needs to be reported to and evaluated by the game's dev(s). Closing as not a Steam client issue.
