### ISSUE TITLE
Petition to add Mebibyte (MiB) as a unit of Information data in Steam.

### ISSUE THREAD

**Issue by Chosin137** [ValveSoftware/steam-for-linux#11568]
Currently Steam defaults to MB or Mb. Having an additional option for MiB to display the unit of information data is admittedly a small ask, but one that I would like to see included.

Apologies if this is the wrong place to post, and thank you for your time.
A humble Steam user, since the beginning.

**Comment by kisak-valve** [comment]
Hello @Chosin137, this request is already being tracked at #6328. Closing as a duplicate.
