### ISSUE TITLE
[HL1/CS] Software mode is broken

### ISSUE THREAD

**Issue by AnAkkk** [ValveSoftware/steam-for-linux#1156]
Software mode seem to be completely broken, see this screenshot:
http://imgur.com/yhMGzyW
It does that on both of my computers.

I would suggest removing software mode, as the performance in it is very bad anyway, no one uses it.

**Comment by klaus1488** [comment]
I agree with the post above. There is no need to remove the software mode for CS 1.6 in GNU/Linux

@kisak-valve
