### ISSUE TITLE
Button glyphs are blank on Steam Deck Mafia 1 Definitve Editive

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#11575]
#### Your system information

* Steam client version (build number or date): Steam OS 20241030.1
* Distribution (e.g. Ubuntu): Steam OS 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

While playing the game certain button glyphs which is most show up as a blank  box making the game almost unplayable on the Steam deck or Linux in general

![screenshot](https://github.com/user-attachments/assets/3f7f4780-4d91-4adf-87cc-6cf07a35f492)

**Comment by kisak-valve** [comment]
Hello @coreybruce, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4220#issuecomment-2543162561.
