### ISSUE TITLE
Some alphanumeric keys act as arrow keys when the virtual keyboard is used in Big Picture mode.

### ISSUE THREAD

**Issue by segakawaii** [ValveSoftware/steam-for-linux#11588]
#### Your system information

* Steam client version (build number or date): 1733265492 (Dec 2)
* Distribution (e.g. Ubuntu): Bazzite 41 (Fedora 41) and Ubuntu 22.04.5
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* GPU: Nvidia (Bazzite) AMD (Ubuntu)

#### Please describe your issue in as much detail as possible:

In games that require the on screen keyboard in big picture mode, some keys do not work properly. The key "q" goes left, "r" goes right, "o" goes up, "t" goes down. This happens on both a physical keyboard and the virtual keyboard. Even when dismissing the virtual keyboard, the physical keyboard is still unable to type these letters. I'm trying to chat in the game "Sky: Children of the Light", which has a chat box that pops up automatically when you start chatting. It's a free game, so this is the easiest to test with. I do not experience this issue with some games, but those games do not raise the virtual keyboard when I enter chat.

A similar issue was reported earlier, but I tried both Stable and Beta versions and neither fix the issue for me. Other users have also reported the same issue in the comments:
https://github.com/ValveSoftware/steam-for-linux/issues/9095

#### Steps for reproducing this issue:

1. Use Bazzite 41 (also replicated on Fedora 41) or Ubuntu 22.04 (possibly newer as well?)
2. Install Sky: Children of the Light using Proton 9 or Experimental and launch it in Big Picture mode.
3. Press enter in-game to start chatting and try pressing the "q", "r", "t", and "o" keys. You will notice that they behave like arrow keys instead of inserting the letters.

**Comment by kisak-valve** [comment]
Hello @segakawaii, this issue is already being tracked at #11158. Closing as a duplicate.
