### ISSUE TITLE
Feature request: Per-game shader precache toggle

### ISSUE THREAD

**Issue by Reonu** [ValveSoftware/steam-for-linux#11584]
It would be good if we were able to toggle the shader pre-caching feature on a per-game basis. Similarly to the background downloads setting, there could be a global setting (on/off) and a per-game override (use global setting/on/off).

Some games take ages to compile shaders, others don't. It's a big help in some games, and useless in others. Considering the amount of background CPU work it adds, or the delay in opening games if you disable that, it shouldn't just be a global setting.

**Comment by kisak-valve** [comment]
Hello @Reonu, this request is already being tracked at #6486. Closing as a duplicate.
