### ISSUE TITLE
[General] - Dismissing the "Controller settings" with the Steam button breaks Steam navigation flow.

### ISSUE THREAD

**Issue by ZereoX** [ValveSoftware/steam-for-linux#11587]
#### Your system information

* Steam client version (build number or date): 1733265492 (Stable) / 1734391190 (Beta)
* Distribution (e.g. Ubuntu): SteamOS 3.6.20 / 3.7.0 (Deck) and Manjaro w/ Gnome 46 (Desktop)
* Opted into Steam client beta?: Yes. Issue is present on both Stable and Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18170539/steam-logs.tar.gz)
* GPU: AMD Van Gogh RDNA 2.0 (Steam Deck) and RX 7800XT (Desktop)

#### Please describe your issue in as much detail as possible:
If the **Controller settings** panel is opened while in-game and is dismissed using the <kbd>Steam</kbd> button, pressing <kbd>Steam</kbd> will no longer open the Steam menu. Pressing it will instead toggle visibility of the **Controller settings** panel until you dismiss it by pressing <kbd>B</kbd> twice. This will then return you to the active title at which point pressing <kbd>Steam</kbd> will allow you to open the Steam Menu again. Upon exiting the game however, the user will be prompted with the **Controller settings** however many times they had toggled it while in-game.

#### Video
https://github.com/user-attachments/assets/f9ed770d-6d12-4344-8bea-e6a23a50a70b

#### Steps for reproducing this issue:

1. Launch any title.
2. Once in-game, press <kbd>Steam</kbd>.
3. Highlight **Controller settings** and press <kbd>A</kbd> twice (this will open the controller layout and then the **Controller settings**).
4. Press <kbd>Steam</kbd> to return to game.
5. Press <kbd>Steam</kbd> to open the Steam Menu.

Reproduction Rate: 5/5

#### Affected Platforms
- LCD / Jupiter: Yes
- OLED / Galileo: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: Yes, in Big Picture Mode

#### Actual result
- <kbd>Steam</kbd> can no longer be used to open the Steam Menu and the user isn't returned to the expected page when exiting the title.

#### Expected result
- Pressing <kbd>Steam</kbd> while on the **Controller settings** panel should simply re-open the **Steam Menu**. This would match the behaviour of other Steam Menu entry that take the user away from it (such as **View game details** and **Recording Settings** under **Game Recording**).

#### Notes
- This can also be reproduce with an external controller by pressing the relevant Steam Menu button for that controller type.

**Comment by Managor** [comment]
A duplicate report can be found here #10755

**Comment by kisak-valve** [comment]
Thanks @Managor for pointing that out, let's continue tracking this issue on the older issue report.

Issue transferred to https://github.com/ValveSoftware/steam-for-linux/issues/10755#issuecomment-2558133051.
