### ISSUE TITLE
[General] - Steam doesn't dynamically reflect the active timezone.

### ISSUE THREAD

**Issue by ZereoX** [ValveSoftware/steam-for-linux#11581]
#### Your system information

* Steam client version (build number or date): 1733265492 (Stable) / 1734061824 (Beta)
* Distribution (e.g. Ubuntu): SteamOS 3.6.20 / 3.7.0 (Deck) and Manjaro w/ Gnome 46 (Desktop)
* Opted into Steam client beta?: Yes. Issue is present on both Stable and Beta
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18156666/steam-logs.tar.gz)
* GPU: AMD Van Gogh RDNA 2.0 (Steam Deck) and RX 7800XT (Desktop)

#### Please describe your issue in as much detail as possible:
Steam does not dynamically reflect the active timezone. Steam will therefore always reflect the timezone set on its launch and maintain it until it is restarted. On Steam Deck, the user isn't prompted to restart the device when changing the timezone (under **Steam > Settings > General > Timezone**) which make it appear as if it wasn't applied.

| Steam Deck - EST :white_check_mark: | Steam Deck - CST :x: | Desktop :x: |
| ---------------- | ---------------- | ---------------- |
|![Default_TimeZone](https://github.com/user-attachments/assets/3226b401-f690-4b57-864c-5ccec0960db3)|![Different_TimeZone](https://github.com/user-attachments/assets/2dce5fff-4f77-4a39-a1a6-1eb5552cf077)|![Desktop_Timezone_Change](https://github.com/user-attachments/assets/af12bfc9-cd23-4b2e-8df1-8efd99eb24ad)|

##### Video
https://github.com/user-attachments/assets/95e66981-3c55-4239-bd0f-70c6e98e483a

_Note: The video above shows the system timezone is correctly being updated by Steam, but Steam's own clock doesn't reflect the change._

#### Steps for reproducing this issue:

1. Navigate to **Steam > Settings > General**.
2. Select a different timezone from the one currently set.

Reproduction Rate: 5/5

#### Affected Platforms
- LCD / Jupiter: Yes
- OLED / Galileo: Yes
- Desktop Deck-like session (`gamescope -e -- steam -gamepadui -steamdeck`): Yes
- Desktop: Yes

_Note: On Desktop the timezone must be changed at a system level as Steam's **Timezone** option is only available on Steam Deck / Deck-like session._

#### Actual result
- The system clock on Steam Deck retains the previous timezone when changed. On Desktop this also affects the Steam Overlay and Clock module.

#### Expected result
- Steam dynamically updates the system clock when the timezone is changed or prompts the user that Steam must be restarted for the setting to apply.

**Comment by kisak-valve** [comment]
Hello @ZereoX, your feedback here adds some insight to an older issue report on the ValveSoftware/SteamOS issue tracker, which then was transferred over here for a Steam dev to ponder. In the end, this issue report has now been transferred to https://github.com/ValveSoftware/steam-for-linux/issues/11582#issuecomment-2546680521.
