### ISSUE TITLE
Enable Steam Play by default on Steam for Linux

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#11596]
#### Please describe your issue in as much detail as possible:
Steam for Linux should have Steam Play enabled by default. The Steam client that comes with the Steam Deck has Steam Play enabled by default. Most games do not have native versions for Linux. People who don't know Steam Play exists may not ever enable it and think that Linux has little game support.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost immediately.

Setting that aside, my understanding is that support for running games with Proton is unofficial and unofficial options can't be enabled by default. Functionally, the request at #7234 would be better.

**Comment by defiling9046** [comment]
I feel like this should be enabled as Proton is becoming the main way to play windows games on Linux as if it wasn’t it wouldn’t be enabled by default for the Steam Deck.

And I know that I’m only one voice here but there’s at least over 100 people that agree with this change on the r/Linux_Gaming Reddit with a post that gained over 100 upvotes in the last 6 hours so if you could reconsider that would be great. [https://www.reddit.com/r/linux_gaming/comments/1ib1mkf/steam_play_should_be_on_by_default_for_new_steam/](url)
