### ISSUE TITLE
Little Inferno (221260) graphical issues in native Linux version

### ISSUE THREAD

**Issue by joshas** [ValveSoftware/steam-for-linux#11591]
#### Your system information

* Steam client version (build number or date): 1733265492
* Distribution (e.g. Ubuntu): Fedora Linux 41 (Workstation Edition) GNOME + Wayland
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD Radeon RX 5600 XT, 4.6 (Compatibility Profile) Mesa 24.2.8

#### Please describe your issue in as much detail as possible:
Graphical glitches in-game, ranging from random black blocks to fully black screen. Intro and menu works without issues, problems starts only after starting the game.
Steam Linux Runtime 1.0 (scout) and Legacy Runtime 1.0 have same issues.

![Screenshot From 2024-12-20 22-02-03](https://github.com/user-attachments/assets/75e39f03-6039-4680-8070-b9e0481a4052)
![Screenshot From 2024-12-20 22-04-58](https://github.com/user-attachments/assets/2c9ffd08-7237-4743-820f-bf4e59577fd9)
![Screenshot From 2024-12-21 12-42-56](https://github.com/user-attachments/assets/8a05298b-ee5a-446c-af9e-abe07caa13e2)
![Screenshot From 2024-12-21 16-10-19](https://github.com/user-attachments/assets/63e9ceb2-1cc3-4adc-a4b7-0bdd01c31d05)

#### Steps for reproducing this issue:

1. Launch the game and start a new game.

**Comment by kisak-valve** [comment]
Hello @joshas, this issue needs to be evaluated by your video driver vendor and/or the game's dev(s).

Closing as not a Steam client issue.

**Comment by kisak-valve** [comment]
Looks like this issue is being tracked at https://gitlab.freedesktop.org/mesa/mesa/-/issues/7903.
