### ISSUE TITLE
CS2 lagging with mouse movement

### ISSUE THREAD

**Issue by ByPaco10** [ValveSoftware/steam-for-linux#11601]
#### Your system information

* Steam client version: Stable Client 1733265492 Mon, Dec 2 10:26 PM UTC -08:00 (Running both steam and steam-native-runtime from AUR doesn't change anything)
* Distribution: Arch Linux x86_64
* Opted into Steam client beta: No
* Have you checked for system updates: Yes
* Steam Logs: [steam_logs.tar.gz](https://github.com/user-attachments/files/18255064/steam_logs.tar.gz)
* Session: KDE + Wayland
* GPU: AMD MSI RX 5700XT

#### Please describe your issue in as much detail as possible:
After around 40 minutes to 1 hour of playing the game (even in menu) the game starts lagging when I move the mouse.

#### Steps for reproducing this issue:

1. Start the game
2. Wait around 1 hour
3. Move the mouse

#### CS2 Launch options used:
MANGOHUD=0 gamemoderun %command% SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 -threads 6 -tickrate 128 -vulkan -novid -nojoy +fps_max 0 +cl_forcepreload 1 -fullscreen

#### System logs:
[eglinfo -B.txt](https://github.com/user-attachments/files/18255087/eglinfo.-B.txt)
[steam system info.txt](https://github.com/user-attachments/files/18255088/steam.system.info.txt)
[usb-devices.txt](https://github.com/user-attachments/files/18255089/usb-devices.txt)
[vulkaninfo.txt](https://github.com/user-attachments/files/18255090/vulkaninfo.txt)

journalctl doesn't spit any USB device error. This only happens in CS2

**Comment by kisak-valve** [comment]
Hello @ByPaco10, you've described the issue being tracked at #11446. Closing as a duplicate.
