### ISSUE TITLE
Steam beta client crashing in Guilty Gear Xrd rev2 lobbies

### ISSUE THREAD

**Issue by daveosaur** [ValveSoftware/steam-for-linux#11605]
#### Your system information

* Steam client version (build number or date): Beta 1734743608
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes (full system update earlier today)
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18258482/steam-logs.tar.gz)

* GPU: Nvidia RTX 3060

#### Please describe your issue in as much detail as possible:
On the steam beta client, when running Guilty Gear Xrd rev2, whenever you join or host a network lobby, both the steam client and the game crash. 100% consistently, only on the beta client. Switching back to the regular client fixes this.

I've been on the beta client for months, and this issue has only popped up recently (I haven't played Xrd in a week or so, so this is very recent).

#### Steps for reproducing this issue:

1. Enable Steam beta client.
2. Join/host a lobby in Guilty Gear Xrd rev2.

**Comment by ioletsgo** [comment]
I'm having a similar issue with the Steam Beta crashing, at my end it seems to be failing to create Pipewire nodes that the games rely on.

**Comment by kisak-valve** [comment]
Hello @daveosaur, this should be the same issue as #11592. Opt out of Steam's client beta until the next beta update cycle.

Closing in favor of the older issue report.
