### ISSUE TITLE
Opening the controller configurator in the desktop overlay causes the overlay to close instantly

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#11612]
#### Your system information

* Steam client version: 1734743608
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/18267652/steam-logs.tar.gz)
* GPU: Intel

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/UH0p_tWANJE
If I try to configure the controller config while in a game, the overlay closes on me automatically.

#### Steps for reproducing this issue:

1. Plug in a controller
2. Shift+tab to open the overlay
3. Open the controller configurator

#### Result:
The overlay closes on you

#### Expected:
The overlay should stay open.

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #11307. Closing as a duplicate.
