### ISSUE TITLE
Missing systray's icon image after build from 01 feb 2013

### ISSUE THREAD

**Issue by swiftgeek** [ValveSoftware/steam-for-linux#1190]
This build contains regression - it doesn't display image of steam's icon (standard "missing icon/image/file" image is displayed instead).

Also it contains fix for missing theming in appindicator's menu.

xfce4.10

**Comment by JamesTheAwesomeDude** [comment]
@ManuGithubSteam Gentoo uses the `ABI_X86` USE_EXPAND flag for multilib support. Add `32` to yours.

**Comment by weberkai** [comment]
Run 32 bit version of gdk-pixbuf-query-loaders
gdk-pixbuf-query-loaders-32 > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
