### ISSUE TITLE
Categories don't seem to sync on first run.

### ISSUE THREAD

**Issue by The-MAZZTer** [ValveSoftware/steam-for-linux#121]
I logged in and none of my categories for my Windows games were present.  When I logged out (well, I logged back in on my Windows box forcing Linux to log out) and back in later, my categories only then immediately synced to Linux.

**Comment by kisak-valve** [comment]
Hello, can someone confirm this is still an issue with the current stable or beta steam client?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by RussianNeuroMancer** [comment]
No longer reproducible for me.
