### ISSUE TITLE
Slow load times in TF2

### ISSUE THREAD

**Issue by Rua** [ValveSoftware/steam-for-linux#125]
This is a well known issue I believe but it still has to be reported. :)

Map loading in TF2 is very slow. It often takes 2 minutes or more even on my 1-year old desktop computer. By the time the map has loaded, the setup time has usually already passed, which is rather frustrating.

When starting the game, the menu background shows but it takes rather long for the menu to actually appear, compared to the Windows version.

Disconnecting from a server also seems to take a rather long time. I'm not sure if it's related.

**Comment by mtmkls** [comment]
This hasn't affected me. Maps load in 15-20 seconds, and I'm usually among the first to arrive at mvm missions (I assume matchmaking connects all players to the server at the same time)

**Comment by Asrael** [comment]
This is also no longer a problem for me since around October. I didn't think to mention it here, it doesn't seem very active.

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been resolved.

It should be noted that opengl video drivers that do not support an on-disk shader cache will still need to compile shaders on each game start, and video drivers that do have an on-disk shader cache need to build that cache on first start and might need to rebuild the cache after video driver changes.
