### ISSUE TITLE
Placement of titlebar buttons inconsistent with rest of the system

### ISSUE THREAD

**Issue by kumikumi** [ValveSoftware/steam-for-linux#128]
All Steam windows have their window titlebar buttons (minimize, maximize, close) incorrectly placed on the right side of the titlebar. This is confusing to the end user, and inconsistent with the standard Ubuntu desktop application behaviour as applications should have these window controls on the left side.

Perhaps it would even be good practice to set the location for the window controls based on the user's desktop environment (the way google chrome/chromium does) or even give users the option to choose from the settings menu.

**Comment by kisak-valve** [comment]
Closing in favor of #1040.
