### ISSUE TITLE
Enable prop driver packages error

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/steam-for-linux#1292]
Steam requires vendor-supplied...blah, blah, blah. I have the latest fglrx drivers installed and recognized and running but steam thinks they aren't enabled because in linux mint 13's software sources there is no "Proprietary drivers for devices (restricted)" option and jockey-gtk doesn't realize I installed the fglrx drivers either...this is really frustrating to have pop up at every startup and should be rectified.

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2700 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-36-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7700 Series

```
Driver Version:  4.2.12002 Compatibility Profile Context 9.012
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x683d
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17.44" x 9.80"  (20.00" diag)
                                        44.3cm x 24.9cm  (50.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7973 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  48225 Mb
    Largest Free Hard Disk Block:  29301 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @calexil, if you are still experiencing this issue with an up to date system, please open a new issue report.

**Comment by calexil** [comment]
four years later.... not bad steam... not bad

/s
