### ISSUE TITLE
[CS:S] Custom models texture issue Linux

### ISSUE THREAD

**Issue by Dasani** [ValveSoftware/steam-for-linux#1298]
Something odd is going on with custom models I'm not 100% sure but I think it might be models that use custom textures that are located in folders that differ in name to the orignal folder.

For example:

If I use a custom m4a1 model and the textures are in a folder other than rif_m4a1 then the model loads but with no textures. Tested on a Windows install and everything works fines.

**Comment by kisak-valve** [comment]
Hello @Dasani, if you are still experiencing this issue with case-sensitivity taken in mind, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
