### ISSUE TITLE
Resizing main window seems to cause jitters

### ISSUE THREAD

**Issue by boombatower** [ValveSoftware/steam-for-linux#1308]
Resizing primary window causes flashing and jitters in addition to the window not properly redrawing (border is large, but bleeds through to background).

When I move mouse of window I see the interface correctly drawn at the right size as it flashes there and the size it was before. Example when full inteface is not shown, but you can tell the interface has been drawn for the larger area.

![image](https://f.cloud.github.com/assets/209374/131051/21e5ef7c-7047-11e2-8868-de1282ade851.png)

If I quit steam and reopen..it opens at the resized window size and looks fine until I resize it again.

KDE 4.9.5 on openSUSE 12.2 (tumbleweed).

```
Processor Information:
    Vendor:  GenuineIntel
    Speed: 3501 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 12.2 (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.6-22-desktop
    X Server vendor:  The X.Org Foundation
    X Server release:  11302000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series 

    Driver Version:  4.2.12002 Compatibility Profile Context 9.012
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  3
    Number of Video Cards Not Detected
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 6400 x 1600
    Primary Display Size: 25.24" x 15.75"  (29.72" diag)
                                            64.1cm x 40.0cm  (75.5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  32190 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  202061 Mb
    Largest Free Hard Disk Block:  189115 Mb
```

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by AlexandreBonneau** [comment]
@kisak-valve nope, not for a long time now.

Note: I moved away from *ubuntu and switched to Debian testing. That and the fact mesa and kde matured 2 years since then could explain why this work perfectly now!

**Comment by kisak-valve** [comment]
Thanks for the feedback @AlexandreBonneau, closing.
