### ISSUE TITLE
Big Picture flashes

### ISSUE THREAD

**Issue by boombatower** [ValveSoftware/steam-for-linux#1312]
Big picture mode flashes when running, although the animation seems smooth, but the entire screen flashes. I have lunched it repeatedly and in different manors with the same result. One time out of over 20 launches it did not flash which is rather interesting.

Might be related to #1311 or ATI driver in general.

The only note of itnerest from output seems to be

```
**** Panel FavoritePages has fill-parent-flow for height, but isn't in a flowing layout
sdlopenglsurface.cpp (1221) : Assertion Failed: bSuccess
Assert( Assertion Failed: bSuccess ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/panorama/./renderer/sdlopenglsurface.cpp:1221
```

```
Processor Information:
    Vendor:  GenuineIntel
    Speed: 3501 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 12.2 (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.6-22-desktop
    X Server vendor:  The X.Org Foundation
    X Server release:  11302000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series 

    Driver Version:  4.2.12002 Compatibility Profile Context 9.012
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  3
    Number of Video Cards Not Detected
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 6400 x 1600
    Primary Display Size: 25.24" x 15.75"  (29.72" diag)
                                            64.1cm x 40.0cm  (75.5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  32190 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  202061 Mb
    Largest Free Hard Disk Block:  189114 Mb
```

Should probably just pastebin my machine profile instead of pasting over and over.

**Comment by adolson** [comment]
This is still occurring with the latest stable Steam and NVIDIA drivers on Debian Jessie. Seems to be random when it starts, and I can't make it go away without restarting Steam (just quitting BPM and going back in does not work).

**Comment by adolson** [comment]
I'm not 100% sure on this, but it may have something to do with changing video modes. I noticed it seems to occur after I quit out of a game that had changed my display resolution before (I forget what games but I'll try to make a note next time), and now I am noticing if I set my PC to automatically go into BP, and then Ctrl+Alt+F3 to log in to another tty in text mode, and then go back to the tty with Steam, the flicking happens...

I hope this can be solved somehow. It's been an issue for a long time...

**Comment by adolson** [comment]
As another follow-up, It seems like if I add compton to the xinitrc, then this problem goes away. However, it introduces a crazy amount of screen tearing, making Steam and games nearly unbearable.

**Comment by kisak-valve** [comment]
Hello, is anyone experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
