### ISSUE TITLE
Reduce the size of updates

### ISSUE THREAD

**Issue by alexwh** [ValveSoftware/steam-for-linux#1322]
The updates for the Steam client are huge - like ~130MB huge.
Can't these updates be compressed or cut down a little more? Do we really need to ship openssl, drivers, docs and other packages that can just be added as a dependency (and will most likely be already installed anyway)?
The main Steam binary is only 5MB, but can be `strip`ped to 3.7 (this'll also lower memory footprint).

It's also pretty inconvenient for capped bandwidth users that need to download an update that large once a week or more.

**Comment by dustwolf** [comment]
Anyone else reading this find this ironic? 5 years later and it's still redownloading 100+ MB on each update, issue not having been addressed at all.
