### ISSUE TITLE
Savegame timestamps use access time, not modification time

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#1337]
After the latest update, save-game location moved so I dutifully `mv` all my files to the new location, but now Half-Life doesn’t know how to sort them, as 
save game timestamps appear to use access time, not modification time.

http://steamcommunity.com/sharedfiles/filedetails/?id=125467450
vs

```
-rw-rw-r--  1 john john  189581 2013-01-31 01:02 Half-Life-121.sav
-rw-rw-r--  1 john john  185721 2013-01-31 01:02 Half-Life-122.sav
-rw-rw-r--  1 john john  185608 2013-01-31 23:17 Half-Life-123.sav
-rw-rw-r--  1 john john  319276 2013-01-31 23:27 Half-Life-124.sav
```

**Comment by jvasileff** [comment]
> I looked over the code, we use mtime from the stat() call

It's actually using the *greater* of `mtime` and `ctime` (at least on macOS), making it impossible to correct times for older saves after a restore or sync.
