### ISSUE TITLE
Video driver recommended by Steam

### ISSUE THREAD

**Issue by Disk981** [ValveSoftware/steam-for-linux#136]
I have Steam installed on Ubuntu 12.04, I also installed the AMD driver 12.10 from terminal, all ok but when I open the program, a window appears that says: "Steam could not find recommended video driver packages on your system."
What are the drivers that Steam recommend? And / Or why not find them?
![Schermata del 2012-12-20 17:48:13](https://f.cloud.github.com/assets/3091347/24909/34ba449c-4ac5-11e2-8b12-81d3c365e386.png)

**Comment by Sasszem** [comment]
When I start Steam, I ALWAYS get a message: "Your system is running older proprietary nVidia video drivers. Steam requires driver version 304.22 or higher.", but my video card(FX 5200) CAN NOT run the newest driver, only an old version. I don't want to play any "big" games, that require good graphics cards, and I know, my video card CAN run TF2, Portal, HL2 & MC, and I don't need more. I just want to use Steam under Ubuntu. When I tried to use it under WinXP, there wasn't any problems. Can I fix it or I can play only under WinXP?
