### ISSUE TITLE
FPS counter is part of Steam Overlay

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#1370]
FPS counter is usefull to measure performane of games.
But there is no Linux native apps that can do it, and many games hasn't builtin fps counter.
So i propose to add FPS counter into Steam Overlay.

**Comment by Shished** [comment]
http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/215377632967251340

> Added FPS counter to Steam Overlay 

This ticket can be closed now XD

**Comment by kisak-valve** [comment]
Closing as implemented.
