### ISSUE TITLE
Problems with fonts when STEAM_RUNTIME=1

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#1401]
Games launched in steam with STEAM_RUNTIME=1 has unreadable text wich consist of squares.

My locale is 
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC=ru_RU.utf8
LC_TIME=ru_RU.utf8
LC_COLLATE="ru_RU.utf8"
LC_MONETARY=ru_RU.utf8
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT=ru_RU.utf8
LC_IDENTIFICATION="ru_RU.utf8"

I think its because missing fonts. I copied /usr/share/fonts folder into ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/share but it doesn't helped..

My pc specs http://pastebin.com/r6e2BiGS

**Comment by kisak-valve** [comment]
Hello @Shished, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Shished** [comment]
I can confirm that this problem is fixed.
