### ISSUE TITLE
Steam crashes unless LANG=en_US.utf8

### ISSUE THREAD

**Issue by heftig** [ValveSoftware/steam-for-linux#1420]
Steam crashes unless run with LANG=en_US.utf8. Log follows:

Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 10475 with name 0eBlobRegistryMutex_E4E7A313AFC0ADE4727A2610FD2EA665
removing stale semaphore last operated on by process 10475 with name 0eBlobRegistrySignal_E4E7A313AFC0ADE4727A2610FD2EA665
removing stale semaphore last operated on by process 10475 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 10475 with name 0eSteamEngineLock
surface_linux.cpp (686) : Assertion Failed: XOpenIM() failed, LANG = en_DE.utf8
Assert( Assertion Failed: XOpenIM() failed, LANG = en_DE.utf8 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/surface_linux.cpp:686

Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20130208180745_1.dmp
success = yes
response:  CrashID=bp-2737d1e0-899e-48da-a091-019ec2130208

(steam:12725): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:989: error: unexpected identifier `direction', expected character`}'
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
[0208/180820:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Installing breakpad exception handler for appid(steam)/version(1360282734_client)
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  18 (X_ChangeProperty)
Value in failed request:  0x0
Serial number of failed request:  90
xerror_handler: X failed, continuing
Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20130208180821_2.dmp
success = yes
response:  CrashID=bp-8d20fff3-1283-4c15-8540-4ae692130208
/home/jan/.local/share/Steam/steam.sh: line 561: 12725 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

**Comment by rosmanov** [comment]
`LC_ALL=C steam` helped to launch it. After 10 seconds or so it crashed with the same segmentation fault at line 713.

I stopped playing on steam about 3 months ago because of this exact issue in hope that something will be fixed soon. Sometimes I feel like rather playing with some code. At that rate, my love to gaming is going to cease =)

**Comment by q3452** [comment]
I experienced this error on a clean install of Linux Mint 18 which is more or less Ubuntu 16.04.  I documented my logs etc in @ #4665 though the OP there may or may not have had the same issue (it appears the same at first glance though).

It was fixed by:
`LANG=en_US.utf8 steam`
