### ISSUE TITLE
Firing while moving with mouse

### ISSUE THREAD

**Issue by dizietsma** [ValveSoftware/steam-for-linux#1457]
Maybe i'm missing something but in HL 1 while i'm shooting i can't mouse look, moving the mouse has no effect, not so bad for single shot kills but using the mp5 in long bursts is no good if the enemy so much as takes a step to the side :)

kde 4.8.5, xserver 1.13.2,

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by dizietsma** [comment]
just reinstalled and played a few minutes, seems ok, mouse looking and firing ok.  this with the non beta selected in the game properties in steam client.

**Comment by kisak-valve** [comment]
Thanks for retesting @dizietsma, closing.
