### ISSUE TITLE
TF2 promises to install 4.7GB, but downloads 12.2GB

### ISSUE THREAD

**Issue by Majkl578** [ValveSoftware/steam-for-linux#1459]
The dialog before install contains an information that 4773MB will be required. However when download starts, it's actually downloading 12.2GB.

[System info](https://gist.github.com/Majkl578/f91695cbc471769b849d/ad94c0a8d36a789815d0f959b94bcc9cd72d9f90)

**Comment by kisak-valve** [comment]
Closing as this appears to have naturally resolved itself with the transition to steampipe.
