### ISSUE TITLE
Talking indicator in chat windows doesn’t invalidate correctly

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#1491]
When scrolling the userlist in a chat window with people using voice chat, speaker icons just accumulate all over the place.

![Screenshot from 2013-02-03 19:01:33](https://f.cloud.github.com/assets/7708/142240/8fc24324-72d6-11e2-93cb-eec1906afa5d.png)
![Screenshot from 2013-02-03 19:01:38](https://f.cloud.github.com/assets/7708/142241/9fb74c70-72d6-11e2-93f3-728675714510.png)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
