### ISSUE TITLE
[CS1.6][Mac]Crash when joining server

### ISSUE THREAD

**Issue by jimbond** [ValveSoftware/steam-for-linux#1503]
The Mac build of the CS1.6 Beta crashed on me today when I tried to join a server.  This is the message I received:
![Screen Shot 2013-02-09 at 3 07 42 PM](https://f.cloud.github.com/assets/3443260/142639/51f90376-7307-11e2-9770-36bbeb9d4ad1.png)

**Comment by kisak-valve** [comment]
Closing due to insufficient information to take action.
