### ISSUE TITLE
Crash on MOTD

### ISSUE THREAD

**Issue by dolohow** [ValveSoftware/steam-for-linux#1508]
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20130210005404_1.dmp
success = yes
response:  CrashID=bp-ad9ea68b-54d7-45ec-a3a8-5afe02130209
/path/hl2.sh: line 72: 26041 Naruszenie ochrony pamięci   ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 440 "Team Fortress 2", ProcID 26041 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

Naruszenie ochrony pamięci - segfault

https://gist.github.com/dolohow/4743373

Have you got this dump somewhere in database? I can enclose if no.

**Comment by kisak-valve** [comment]
If anyone is still encountering this issue with an up to date system, please open a new issue report. Closing.
