### ISSUE TITLE
Steam Overlay in games with aspect ratio's other than 16:9 still leaves artifacts while using AMD and Nvidia drivers.

### ISSUE THREAD

**Issue by olavd** [ValveSoftware/steam-for-linux#1525]
While the latest client update might have fixed this for users of Intel hardware, it's still a issue with e.g AMD Catalyst 13.1 and Nvidia's 310.32. Any game occupying less screen real state should be affected by this.

My system information: https://gist.github.com/olavd/4377544, https://gist.github.com/olavd/4377514.

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.
