### ISSUE TITLE
Game installation: Disk space check and folder selection in wrong order

### ISSUE THREAD

**Issue by blackmole** [ValveSoftware/steam-for-linux#1534]
Hey guys,

the disk space check is a bit messy. It always checks the default partition, so when I don't have enough space on my home partition, I can't install the game, even though I have enough space on a different partition that I added as a Steam Library Folder. Please let the user choose the folder first and then perform the disk space check.

This just happened to me, because I've got my home on a quite full RAID1 and not-so-important stuff on a RAID0 mounted in a sub-folder of my home, so I could not install CS:S.

Best regards
Johannes

Edit: I was wrong, the problem is that CS:S is lacking a selection of the installation folder. For Half-Life (Beta), I can choose the folder and the "Disk space available" is correct. For CS:S, I cannot choose a different folder. And I don't know how to set the default folder, so I cannot install it anywhere else.

**Comment by kisak-valve** [comment]
Hello @blackmole, are you still experiencing this issue when adding your storage partition as a Steam Library folder in the settings?

**Comment by kisak-valve** [comment]
Closing pending feedback.
