### ISSUE TITLE
Count software installed on Linux box.

### ISSUE THREAD

**Issue by pashazz** [ValveSoftware/steam-for-linux#1554]
If you're planning to include installed software in Linux's future section of hwsurvey,
then give distributors a way to report installed software by the API to Steam. 

Linux has several types of package managers. You can only implement APT support if you wanna, but there are also RPM/YUM, Portage and Packman. So there must be a way to get that info not on Ubuntu only.

**Comment by kisak-valve** [comment]
Closing as the installed software section was removed from the system information.
