### ISSUE TITLE
[STEAM] overlapping lines on Steam

### ISSUE THREAD

**Issue by revo4ever** [ValveSoftware/steam-for-linux#1585]
Hi everyone,  I still see this problem on Steam, the issue is the overlapping lines on primary steam window

![Steam_001](https://f.cloud.github.com/assets/3428035/147026/1585f5be-749e-11e2-9f80-0a6928161da6.png)

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3067 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-6-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11302000

Video Card:
    Driver:  NVIDIA Corporation GeForce G210/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xa60
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                        44,3cm x 24,9cm  (50,8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3817 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  147848 Mb
    Largest Free Hard Disk Block:  130850 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as this was fixed some time ago.
