### ISSUE TITLE
Steam stuck on uninstalling game which hasn't been completely downloaded

### ISSUE THREAD

**Issue by Majkl578** [ValveSoftware/steam-for-linux#1599]
I started downloading Team Fortress 2, but stopped it after ~150MB. Then I wanted to remove it, so I clicked "Remove local content" in context menu in Library. The uninstall dialog appeared, but hasn't finished.
After a while, the downloading was still there, presented as Paused (but cannot be resumed, that button does nothing), but the game was NOT in the library at all

[System info](https://gist.github.com/Majkl578/f91695cbc471769b849d/ad94c0a8d36a789815d0f959b94bcc9cd72d9f90)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
