### ISSUE TITLE
Clocks, semaphores and ports

### ISSUE THREAD

**Issue by ManInTheGitHub** [ValveSoftware/steam-for-linux#1606]
I was trying to debug why Steam is unwilling to install TF2 (validation results in: "validated succesfully", "steam servers busy" and "no disk space available" (although steam reports 740GB free) ALL at the same time; but I'll make a separate bug report for that) and I was using strace to find out what file might be causing problems and couldn't help notice the following:

[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491034006}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491115024}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491189406}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491261344}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491334470}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491408712}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491482955}) = 0
[pid 26713] semop(4063238, {{0, -1, IPC_NOWAIT}}, 1) = -1 EINVAL (Invalid argument)
[pid 26713] clock_gettime(CLOCK_MONOTONIC, {605579, 491557268}) = 0

It keeps doing this all the time; the strace output is unreadable because of the enormous amount of clock_gettime, semop calls with invalid arguments and nanosleep calls.

When closing steam to retry (but with strace rerouted to a file and filtered on file access calls) I also noticed the following: 

[pid 26569] bind(15, {sa_family=AF_INET, sin_port=htons(881), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EACCES (Permission denied)

Since the latest version Steam won't be running as root anymore and ports under 1024 are root only, so this is not going to work.

**Comment by kisak-valve** [comment]
Hello @ManInTheGitHub, have you seen this issue with an up to date client?

**Comment by ManInTheGitHub** [comment]
No; I've retested it with the client built om March 22 and the strace now shows all the expected stuff and none of the unexpected EINVAL or EACCESS or similar.

Thanks for the effort!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
