### ISSUE TITLE
Friends images in Steam are resized down

### ISSUE THREAD

**Issue by scqless** [ValveSoftware/steam-for-linux#1613]
Friend images in Steam (though not all of them, and not all at one time) are sometimes resized to about 2/3 their original size, as seen in Steam chat and the Friends window.

[System Information](http://pastebin.com/sUbeek2C)

![steam-friendsimage](https://f.cloud.github.com/assets/3085852/149106/efd14c1e-7520-11e2-90f4-54306ccad925.jpg)

**Comment by kisak-valve** [comment]
Hello @scqless, are you still experiencing this issue with an up to date system?

**Comment by scqless** [comment]
I have not experienced this issue in years.

But while we're on the topic of necroing old threads, #3977 is in dire need of attention. One of my pet peeves is critical bugs that go unfixed for long stretches of time. :)

On 04/05/2017 01:08 PM, kisak-valve wrote:

Hello @scqless<https://github.com/scqless>, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
