### ISSUE TITLE
glibc error when trying to restart after offline mode

### ISSUE THREAD

**Issue by ltodoto** [ValveSoftware/steam-for-linux#1622]
Steam leave crash report in the terminal when you try to restart it from dialog which allow you to select to restart steam, or going to offline mode. Crash won't reproduce if restart from offline mode.

> Processor Information:
>    Vendor:  GenuineIntel
>    Speed: 2701 Mhz
>    4 logical processors
>    2 physical processors
>    HyperThreading:  Supported
>    FCMOV:  Supported
>    SSE2:  Supported
>    SSE3:  Supported
>    SSSE3:  Supported
>    SSE4a:  Unsupported
>    SSE41:  Supported
>    SSE42:  Supported
> 
> Operating System Version:
>    Ubuntu 12.04.2 LTS (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.2.0-32-generic
>    X Server vendor:  The X.Org Foundation
>    X Server release:  11103000
> 
> Video Card:
>    Driver:  NVIDIA Corporation NVS 4200M/PCIe/SSE2
>    Driver Version:  4.3.0 NVIDIA 310.32
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x10de
>    DeviceID:  0x1057
>    Number of Monitors:  1
>    Number of Logical Video Cards:  1
>    Primary Display Resolution:  1280 x 1024
>    Desktop Resolution: 1280 x 1024
>    Primary Display Size: 14,80" x 11,85"  (18,94" diag)
>                                            37,6cm x 30,1cm  (48,1cm diag)
>    Primary Bus: PCI Express 16x
>    Primary VRAM: 1023 MB
>    Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>    Audio device: Conexant CX20590
> 
> Memory:
>    RAM:  3907 Mb

Steps to reproduce:
1. Start Steam in offline mode and then exit.
2. Start Steam again and choose "Retry connection"
3. Terminal output will be something like this:

> Running Steam on ubuntu 12.04 64-bit
> STEAM_RUNTIME is enabled automatically
> Installing breakpad exception handler for appid(steam)/version(1360439662_client)
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> Installing breakpad exception handler for appid(steam)/version(1360439662_client)
> Installing breakpad exception handler for appid(steam)/version(1360439662_client)
> Installing breakpad exception handler for appid(steam)/version(1360439662_client)
> Running Steam on ubuntu 12.04 64-bit
> STEAM_RUNTIME has been set by the user to: /media/Steam/ubuntu12_32/steam-runtime
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> unlinked 0 orphaned pipes
> removing stale semaphore last operated on by process 2267 with name
> 0eBlobRegistryMutex_327326B2781718FBD878666B6E07827F
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> [0212/212336:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
> Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Generating new string page texture 5: 128x256, total string texture memory is 442,37 KB
> Generating new string page texture 6: 32x256, total string texture memory is 475,14 KB
> Generating new string page texture 7: 384x256, total string texture memory is 868,35 KB
> Generating new string page texture 8: 64x256, total string texture memory is 933,89 KB
> Adding license for package 0
> roaming config store loaded successfully - 2562 bytes.
> migrating temporary roaming config store
> removing stale semaphore last operated on by process 2267 with name
> 0eBlobRegistryMutex_33C5DA80F77A82563CA07F4E72DFA2B8
> removing stale semaphore last operated on by process 2267 with name
> 0eBlobRegistrySignal_33C5DA80F77A82563CA07F4E72DFA2B8
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> ExecCommandLine: "/media/Steam/ubuntu12_32/steam -dev"
> Store/Community web auth request failed: Auth error
> Generating new string page texture 72: 1024x256, total string texture memory is 1,98 MB
> Generating new string page texture 73: 128x256, total string texture memory is 131,07 KB
> `menu_proxy_module_load': /media/Steam/ubuntu12_32/steam: undefined symbol: menu_proxy_module_load
> 
> (steam:2468): Gtk-WARNING **: Failed to load type module: (null)
> 
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Generating new string page texture 75: 128x256, total string texture memory is 2,11 MB
> Generating new string page texture 76: 256x256, total string texture memory is 2,38 MB
> Installing breakpad exception handler for appid(steam)/version(1360621458_client)
> Shutting down. . .
> <b>**\* glibc detected **\* /media/Steam/ubuntu12_32/steam: corrupted double-linked list: 0x0a084cf8 ***</b>
> ======= Backtrace: =========
> /lib/i386-linux-gnu/libc.so.6(+0x75ee2)[0xf7328ee2]
> /lib/i386-linux-gnu/libc.so.6(+0x76258)[0xf7329258]
> /lib/i386-linux-gnu/libc.so.6(+0x7722f)[0xf732a22f]
> /lib/i386-linux-gnu/libc.so.6(__libc_malloc+0x6c)[0xf732cddc]
> /media/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6(_Znwj+0x27)[0xf7523627]
> /media/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6(_Znaj+0x1b)[0xf752374b]
> /media/Steam/ubuntu12_32/libsteam.so(+0x244706)[0xf41fe706]
> /media/Steam/ubuntu12_32/libsteam.so(+0x2ed26)[0xf3fe8d26]
> /media/Steam/ubuntu12_32/libsteam.so(+0x61d73)[0xf401bd73]
> /media/Steam/ubuntu12_32/libsteam.so(+0x61f03)[0xf401bf03]
> /media/Steam/ubuntu12_32/libsteam.so(+0x14234e)[0xf40fc34e]
> /media/Steam/ubuntu12_32/libsteam.so(+0x15bad4)[0xf4115ad4]
> /media/Steam/ubuntu12_32/libsteam.so(+0x15bd89)[0xf4115d89]
> /media/Steam/ubuntu12_32/libsteam.so(+0x13bae7)[0xf40f5ae7]
> /media/Steam/ubuntu12_32/libsteam.so(SteamShutdownEngine+0x50)[0xf41dc5f0]
> /media/Steam/ubuntu12_32/libsteam.so(+0x2010fd)[0xf41bb0fd]
> /media/Steam/ubuntu12_32/steam[0x8067588]
> /media/Steam/ubuntu12_32/steam[0x8050206]
> /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0xf72cc4d3]
> /media/Steam/ubuntu12_32/steam[0x80523a5]
> ======= Memory map: ========
> 08048000-083cd000 r-xp 00000000 07:02 3018377                            /media/Steam/ubuntu12_32/steam
> 083cd000-083f8000 rw-p 00385000 07:02 3018377                            /media/Steam/ubuntu12_32/steam
> 083f8000-0841a000 rw-p 00000000 00:00 0 
> 09084000-0cce3000 rw-p 00000000 00:00 0                                  [heap]
> 23578000-23580000 ---p 00000000 00:00 0 
> 23580000-23590000 rw-p 00000000 00:00 0 
> ... [rest of memmap] ...

**Comment by kisak-valve** [comment]
Hello @ltodoto, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
