### ISSUE TITLE
DEFCON: Screen changes to 1024x768 on exit

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/steam-for-linux#1627]
I guess this sorta made sense when the game was set to run at 1024x768, but it still sets this mode when I quit the game when the game is set to my laptop's native panel resolution.

**Comment by kisak-valve** [comment]
Hello @directhex, was this issue brought to the attention of the game devs?

**Comment by Uramekus** [comment]
In my testings, DEFCON actually set the default display resolution back on game exit nowadays, can you guys please close that? @directhex @kisak-valve
