### ISSUE TITLE
Unable to perform steam cloud sync

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#1639]
It seems since the past few days Steam cloud sync stopped working for me and I've been unable to sync my game saves, uploading screenshots doesn't work at all, launching games waits forever at the "preparing to launch ..", shutting down steam takes much longer.

I did a netstat during all these events, I saw steam always stuck forever at SYN_SENT stage when it tried to connect to `65.113.241.45:27014`. I can ping the ip fine though..

```
% netstat -anep --tcp | grep steam
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:57343         0.0.0.0:*               LISTEN      1000       642360      4012/steam      
tcp        0      0 10.10.1.2:57298         146.66.152.13:27019     ESTABLISHED 1000       642403      4012/steam      
tcp        0      1 10.10.1.2:58912         65.113.241.45:27014     SYN_SENT    1000       652093      4012/steam

% ping 65.113.241.45
PING 65.113.241.45 (65.113.241.45) 56(84) bytes of data.
64 bytes from 65.113.241.45: icmp_req=1 ttl=111 time=306 ms
64 bytes from 65.113.241.45: icmp_req=2 ttl=111 time=335 ms
64 bytes from 65.113.241.45: icmp_req=3 ttl=111 time=355 ms
```

**Comment by sobfiggis** [comment]
This is also a great example why linking to threads doesn't work. Searching for this issue almost 5 years later link is dead. Use excerpts!!

**Comment by SwissJay** [comment]
> This is also a great example why linking to threads doesn't work. Searching for this issue almost 5 years later link is dead. Use excerpts!!

I agree, but in extreme cases, WayBack Machine can help: https://web.archive.org/web/20170526084351/http://forums.steampowered.com/forums/showthread.php?t=3073793
