### ISSUE TITLE
HL minimizes(?)

### ISSUE THREAD

**Issue by UraniumDeer** [ValveSoftware/steam-for-linux#1659]
HL minimizes(?) when you push CTRL, and "Show position of pointer when the Control key is pressed" in the "Mouse and Touchpad" settings.

OS: Ubuntu 12.04 LTS, 64 bit, nVidia 310.14 drivers

I tried replicating it in a couple of 3d games:
- Legend of Grimrock has no issues
- Serious Sam 3 shows the pointer position animation, and it seems like it wants to change focus, but it remains fullscreen.
- Half-Life loses focus (minimizes?) and the desktop shows.

**Comment by kisak-valve** [comment]
Hello @UraniumDeer, are you still encountering this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
