### ISSUE TITLE
[CS 1.6] Low fps on fullscreen with normal setting

### ISSUE THREAD

**Issue by revo4ever** [ValveSoftware/steam-for-linux#1674]
Hi all, why CS1.6 still buggy on fullscreen mode using the latest Unity interface ? [Ubuntu 13.04]
i get only 35 fps
to get 100 fps i should open CS with -nofbo option

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3067 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-6-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11302000

Video Card:
    Driver:  NVIDIA Corporation GeForce G210/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xa60
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                        44,3cm x 24,9cm  (50,8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3817 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  147848 Mb
    Largest Free Hard Disk Block:  116509 Mb

Installed software:

Recent Failure Reports:
    Wed Feb 13 12:32:36 2013 GMT: file ''/tmp/dumps/crash_20130213123215_1.dmp'', upload yes: ''CrashID=bp-5c844a25-8058-4456-ad5b-fe5d32130213''

**Comment by kisak-valve** [comment]
Hello @revo4ever, are you still experiencing this issue? The specs provided are rather low and I would not be surprised if Unity plus the game was maxing out the vram and the game was bumped to the system ram.

**Comment by kisak-valve** [comment]
Closing pending feedback.
