### ISSUE TITLE
Interesting Steam crash with TF2 and MvM

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#1695]
Since the Update a few days ago, I been having this weird random crash problem showing up while playing TF2 MvM.  I have not seen it happen during normal TF2 play.

Kubuntu 12.10  12GB ram, Nvidia Graphics 310 driver, KDE desktop.

Crash report as seen on the console:  http://pastebin.com/Lrmh1L4m
Dumps from crash:
http://biovore.texnolyze.us/files/Steam_Debug_Dumps/assert_20130213225329_1.dmp
http://biovore.texnolyze.us/files/Steam_Debug_Dumps/crash_20130213225321_1.dmp

Logs seem to point out something with pulse audio.  Was running TeamSpeak3 at the same time...  Maybe caused from something weird from pulseAudio???

It happens almost every time I play, if I wait long enough...  And TS3 need not be running to cause it..

-- Edit --
This is without setting any STEAM_RUNTIME enviroment variables..
will try playing with SDL_AUDIODRIVER=alsa when starting steam and see if it goes away..
New steam update (Feb 14) Problem still persists..
Running steam in STEAM_RUNTIME=0 seems to fix the crash problem....
Will try with STEAM_RUNTIME=1 and use ALSA as sound backend.. (eliminate pulse-audio as suspect)
Note: To get alsa to work with TF2 on 64bit (k)ubuntu you need to install ia32-libs

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
