### ISSUE TITLE
Chinese characters cannot display under Linux Steam games

### ISSUE THREAD

**Issue by woodelf** [ValveSoftware/steam-for-linux#1696]
These days I installed steam for Linux on my Gentoo Linux x64. I downloaded some games and tried the under Linux. However, I found if I set game language as Simplified Chinese, then Chinese characters are all displayed as blank boxes. Please check my attachment.
It happens on Half-Life, Counter Strike, Counter Strike Souce, and Team Fortress 2.
Chinese characters in steam client is OK and correctly displayed. I am just wondering whether it is because of a lack font or anything else? If yes, which font shall I install?
And one more question, I cannot run Counter Strike Source smooth with Intel HD 3000 graphics. Since I also have Nvidia GT540M with Optimus technology, is there anyway to run CSS through "bumblebee" project with "optirun" command? I cannot find the execution file for CSS so I do not know where to find it.
Thank you. 
![screeshot](https://f.cloud.github.com/assets/2378867/155667/428fc8aa-7660-11e2-9fb6-75b86186692a.png)

**Comment by Farzam003** [comment]
i had the same problem on arch linux, then i installed adobe chinese serif and sans chinese fonts + taiwanese font because i wasnt sure which was what, maybe that helps
