### ISSUE TITLE
I cannot input any words in Steam for Linux

### ISSUE THREAD

**Issue by woodelf** [ValveSoftware/steam-for-linux#1697]
I have Gentoo Linux amd64 with kernel 3.7.5 installed, and I have upgrade steam to latest version. However, I cannot input any words in text box in Steam for Linux.
Some other distros are also tested, such as Ubuntu, Mint and Linux Deepin, all with the same issue. So I suppose this should be your upstream problem.
Please check it.

**Comment by kisak-valve** [comment]
Hello, is anyone still encountering this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by linuxiorr** [comment]
I'm not sure whether I should create a new issue, or whether it's connected to this one.

I have a problem, where the Steam client freezes when starting to input text (in any text field - be it the library, store, or chat) the first time after you launch Steam. After it unfreezes, it doesn't freeze again when inputting text.

If I were to restart the Steam client though, the issue repeats (freezes on first text input, and after it unfreezes, text input works).

I'm on openSUSE Tumbleweed with GNOME and mesa 25.0.1.
