### ISSUE TITLE
SteamCMD (for Dedicated Server) + CentOS = No bueno?

### ISSUE THREAD

**Issue by Mecha-Weasel** [ValveSoftware/steam-for-linux#1701]
SteamCMD (for Dedicated Server) + CentOS = No bueno?

I haven't had any cause to do anything with "SteamCMD" prior to now.  Since allegedly HL1 and Counter-Strike (1.6-ish) are being switched-over to it SteamCMD tomorrow, I gave it a shot this evening.  When tried to run on hosted CentOS 5.x (32-bit) dedicated server for the first time, the result was, eh .... "distressing" to say the least (see below).  So much for my very popular HL1 server as of tomorrow???

[code]
[not-root]$ ./steam.sh
Running Steam on Linux 2.6.18-028stab069.6 32-bit
STEAM_RUNTIME is enabled automatically
Unpack runtime failed, error code 1
Error:
Couldn't set up the Steam Runtime. Are you running low on disk space?
Continuing...
Press enter to continue:
./steam.sh: line 446: ulimit: open files: cannot modify limit: Operation not permitted
./steam.sh: line 473: /usr/not-root/steamcmd/ubuntu12_32/steam: No such file or directory
Error:
Couldn't start bootstrap and couldn't reinstall from /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz.  Please contact technical support.
Press enter to continue:
[not-root]$
[/code]

Thought it might be a permissions issue, so I re-applied (all executable, etc.) - no luck.
I'd get my paddle out, but apparently I am up the creek without one?

**Comment by Poorchop** [comment]
I'm trying to install Serious Sam 3 dedicated server. I have tried the Linux Game Server Managers method but that failed, so I tried to do things manually but that didn't work as well. I've searched like crazy but I can't find a solution.

I followed the [SteamCMD instructions](https://developer.valvesoftware.com/wiki/SteamCMD) exactly, and I tried multiple times but when I try to launch the SS3 dedicated server, I just get the following error:
```
ldd: ./Sam3: No such file or directory
ldd: ./Sam3: No such file or directory
cat: /etc/debian_version: No such file or directory
LOG:  Loaded "/home/steam/steamcmd/ss_bfe/Bin/GameEnv_Steam.so".
INF:  GameEnv API: Steam
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
libXrandr.so.2: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
```

I tried following [this step](https://developer.valvesoftware.com/wiki/SteamCMD#Unable_to_locate_a_running_instance_of_Steam). No `~/.steam/` folder was created by default so I created the directory myself and then created the symlink:
```
mkdir -p ~/.steam/sdk32/
ln -s /home/steam/steamcmd/linux32/steamclient.so /home/steam/.steam/sdk32/steamclient.so
```
As expected, this didn't work either. There is a `steamclient.so` in the Serious Sam 3 install directory but that doesn't seem to matter. I ran `steamclient.sh` just to see what would happen and I received the same error messages as in the first post.

My setup is CentOS 7 64-bit, completely up to date.

It just seems like I can't run Steam headless. I don't understand what I'm doing wrong but I've tried both methods multiple times and I just can't launch the dedicated server. Same for Serious Sam HD: The Second Encounter. I was actually able to run CSS completely headless using Linux Game Server Managers although I couldn't connect to the server or see it in the server list when I launched the game locally. I don't think my provider is blocking any ports but even if they are, I don't think that should stop be from at least launching the SS3 dedicated server.

**Comment by Mecha-Weasel** [comment]
Can close this old case I suppose - since it surrounded getting things to work under CentOS, and given the new official stance/emphasis on Ubuntu: [Reference](https://www.mail-archive.com/hlds_linux@list.valvesoftware.com/msg76132.html)

**Comment by BenNewsome** [comment]
I know this is old, but I ran into a similar problem. Steam requires the 32 bit library.

sudo apt-get install lib32gcc1 fixed my diskspace issue on debian.

Its similar on CentOS acording to the wiki:
https://developer.valvesoftware.com/wiki/SteamCMD#Linux.2FOS_X
