### ISSUE TITLE
minor font clipping gui bug

### ISSUE THREAD

**Issue by kdpin** [ValveSoftware/steam-for-linux#1709]
hello,
first of all my config :+1: 
And sorry for my english ^^

Ubuntu 12.04 lts 64 bits
Motherboard : Asus P8H67
cpu : intel i7 2600k
gpu :nvidia gtx 570 ( Drivers : 310 experimental )
Screen : Samsung smbx2250, 1920x1080 60hertz

![Capture du 2013-02-14 12:32:16](https://f.cloud.github.com/assets/3593093/156563/f11e33bc-769b-11e2-9b10-f11ef809be5c.png)

" Pause " the p is not correctly displaying.
These thing is little compared to other problem submited here, but i'm happy to share it with you :p

**Comment by kisak-valve** [comment]
Closing in favor of #3057.
