### ISSUE TITLE
SteamUpdateUI: An X Error occurred X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by esacteksab** [ValveSoftware/steam-for-linux#172]
➜  ~  steam -tcp &
[1] 3200
➜  ~  Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
unlinked 0 orphaned pipes
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
[1220/144015:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
GLError: 1282
Generating new string page texture 6: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 7: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 8: 256x256, total string texture memory is 442.37 KB
Generating new string page texture 9: 64x256, total string texture memory is 507.90 KB
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Generating new string page texture 11: 512x256, total string texture memory is 1.03 MB
Generating new string page texture 12: 384x256, total string texture memory is 1.43 MB
Generating new string page texture 13: 24x256, total string texture memory is 1.45 MB
Generating new string page texture 14: 16x256, total string texture memory is 1.47 MB
Generating new string page texture 15: 32x256, total string texture memory is 1.50 MB
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Generating new string page texture 20: 8x256, total string texture memory is 1.51 MB
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0xbaa7a0
Serial number of failed request:  24230
➜  ~  Installing breakpad exception handler for appid(steam)/version(1355957371_client)

➜  ~  uname -a
Linux bigb0x 3.2.0-34-generic #53-Ubuntu SMP Thu Nov 15 10:48:16 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by YtvwlD** [comment]
I have encountered this problem on Ubuntu 16.04, too.
And it is a problem - Steam won't start anymore.
Yesterday it worked.

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2016-06-14 17:56:11] Startup - updater built Jun  9 2016 20:55:22
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

**Comment by YtvwlD** [comment]
Another thing that worked for me is disabling the Steam runtime:

    STEAM_RUNTIME=0 steam

**Comment by coderguy1777** [comment]
> Another thing that worked for me is disabling the Steam runtime:
> 
> ```
> STEAM_RUNTIME=0 steam
> ```

Shit this works

**Comment by markus-wa** [comment]
this is still an issue

**Comment by prmbittencourt** [comment]
This is still a problem. I'm running EndeavourOS fully updated. Here's the output of `steam` or `steam-runtime`:

> Running Steam on endeavouros rolling 64-bit
> STEAM_RUNTIME is enabled automatically
> Steam runtime environment up-to-date!
> Can't find 'steam-runtime-check-requirements', continuing anyway
> WARNING: Using default/fallback debugger launch
> /home/paulo/.local/share/Steam/ubuntu12_32/steam
> [2021-11-30 07:45:28] Startup - updater built Oct 13 2021 19:47:06
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
> Installing breakpad exception handler for appid(steam)/version(0)
> SteamUpdateUI: An X Error occurred
> X Error of failed request:  BadValue (integer parameter out of range for operation)

After this, the program hangs and I have to interrupt it with Ctrl+C to get back to my prompt.

And here's `STEAM_RUNTIME=0 steam` or `steam-native`:

> Running Steam on endeavouros rolling 64-bit
> STEAM_RUNTIME is disabled by the user
> Can't find 'steam-runtime-check-requirements', continuing anyway
> WARNING: Using default/fallback debugger launch
> /home/paulo/.local/share/Steam/ubuntu12_32/steam

In this case, it exits back to a prompt after printing the above messages.

In both cases, no GUI elements appear at all.

**Comment by prmbittencourt** [comment]
EDIT: (note: this was on EndeavourOS) This turned out to be an Nvidia issue. I had the `nvidia-470xx-dkms` and `nvidia-470xx-utils` installed, which are appropriate for my graphics card (GeForce GTX 760), but the `lib32-nvidia-utils` package instead of `lib32-nvidia-470xx-utils`. Removing the former lib32 package and installing the latter seems to have fixed the problem.

**Comment by SeanRamey** [comment]
> EDIT: (note: this was on EndeavourOS) This turned out to be an Nvidia issue. I had the `nvidia-470xx-dkms` and `nvidia-470xx-utils` installed, which are appropriate for my graphics card (GeForce GTX 760), but the `lib32-nvidia-utils` package instead of `lib32-nvidia-470xx-utils`. Removing the former lib32 package and installing the latter seems to have fixed the problem.

Fixed my issue to, but I was using the beta version, so I just switched all the nvidia drivers to the standard ones.

**Comment by xdevs23** [comment]
> EDIT: (note: this was on EndeavourOS) This turned out to be an Nvidia issue. I had the `nvidia-470xx-dkms` and `nvidia-470xx-utils` installed, which are appropriate for my graphics card (GeForce GTX 760), but the `lib32-nvidia-utils` package instead of `lib32-nvidia-470xx-utils`. Removing the former lib32 package and installing the latter seems to have fixed the problem.

This fixes the issue on Arch Linux (using GTX 760 as well with NVIDIA 470xx DKMS drivers)

**Comment by xdevs23** [comment]
At this point I've been so fed up with NVIDIA that I completely gave up on their graphics cards and switched to AMD Radeon – albeit the card I bought being relatively old and used but comparable to what I had. These issues with NVIDIA are very annoying and Steam has no fault in this.

**Comment by DoniBesp** [comment]
(steam:9961): GLib-CRITICAL **: 20:16:13.613: g_main_context_push_thread_default: assertion 'acquired_context' failed

(steam:9961): GLib-CRITICAL **: 20:16:13.613: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing
Steam: An X Error occurred

same issue then trying laung Medieval 2 total war. I don't know why sometimes game launch, sometimes don't launch

**Comment by kisak-valve** [comment]
Hello @DoniBesp, you're looking for the issue being tracked at #9164 instead of this issue report.
