### ISSUE TITLE
CS Update messes steam up

### ISSUE THREAD

**Issue by Xalus** [ValveSoftware/steam-for-linux#1732]
Today CS 1.6 got updated for everyone, and everyone is like 'wtf happend'

If you go in a server, every sprite and everything is messedup. If you open steam chat (alt + shit)

You get this:
http://cloud-2.steampowered.com/ugc/594743832029109511/D789F4E112A715EA9FAF976D4A954277EB3FD800/

[Edit]
You may also read this:
http://steamcommunity.com/app/10/discussions/0/864959809694782852/

**Comment by kisak-valve** [comment]
Closing per the last comment.
