### ISSUE TITLE
[ContentStorage] Set +C flag on btrfs volumes for *.gcf files

### ISSUE THREAD

**Issue by Spacefish** [ValveSoftware/steam-for-linux#1737]
I experienced pretty Bad performance while loading games / updating on btrfs.
Setting +C flag on the SteamApps Folder and rmoving / redownloading its contents solved the problem for me.

The main problem is with the *.gcf files, btrfs uses COW and scrubs the disk a lot for such large files (when they are accessed / changed).

Setting the "C" Flag on the SteamApps Folder via "chattr +C SteamApps", add it for every new created file in that folder automatically.

Would be nice if you can set this flag in steam by default!

**Comment by nazar-pc** [comment]
@Spacefish, thank you a lot!
I was very sad that my btrfs RAID1 of two SATA3 SSD are blazing fast everywhere except slow and even freezing Steam games with extremely high disk I/O.
Your fix helped me and fixed this odd bug!
Steam should definitely apply `chattr -R +C folder` for all folders involved into Steam (folder inside home directory and all libraries) on disks with btrfs filesystems. This is just A MUST to be usable.

**Comment by nazar-pc** [comment]
Well, it works better, but anyway stuck sometimes.
Only whole system restart helps.
Ubuntu 15.04 x64
Linux 3.19-rc3
Steam Beta

**Comment by OlliC** [comment]
I just made a 6,5TB btrfs raid1 array for all my data and the steam library. 

Is it still necessary to disable Copy on Write? 

I made a quick search in my library and couldn't find any *.gcf files. Also i don't get why it would degrade performance for games that only read data while loading.

**Comment by nazar-pc** [comment]
I do not experience this issue for a long time now, so this is probably irrelevant now (though, my storage is also much faster now than it was back then).

**Comment by kisak-valve** [comment]
@Spacefish, is the same true for you?

**Comment by Spacefish** [comment]
@kisak-valve
I switched back to ext4 and use an PCIe 4x SSD now so I can't test it out..
But I guess this problem was probably related to btrfs which has seen a lot of development in the last 4 years..
As btrfs is slower compared to ext4 I guess it won't see much use in desktop Linux distros.. servers might use it due to the snapshot and raid features built into it.
So I guess we should close this 4 year old issue.

**Comment by OlliC** [comment]
I use btrfs on my desktop precisely because of raid, snapshots and checksums. OpenSuse now uses it as their default root filesystem. Its going to be used more and more on desktops. 

Anyways i have a nearly 1TB steam library now on btrfs with default settings and cow not disabled which i am going to use and test. If i run into any problems i will probably just open a new issue.

**Comment by kisak-valve** [comment]
Thanks for the feedback. GCF files shouldn't exist in the wild since the steampipe conversion was completed years ago.

Closing.
