### ISSUE TITLE
Support PRIMARY selection (aka mouse selection / middle-click clipboard)

### ISSUE THREAD

**Issue by paradigm** [ValveSoftware/steam-for-linux#175]
Please support `PRIMARY` selection in addition to `CLIPBOARD`.

X11 has three selections (or "clipboards"):

`CLIPBOARD` is usually accessed by pressing ctrl-c to copy and ctrl-v to paste, and acts as one would expect from experience with other windowing systems such as what Windows uses.  This works fine in Steam on Linux.

`PRIMARY` is copied into by simply highlighting something with the mouse, and pasted from by middle clicking or pressing shift-insert.  This does not seem to work in the current-as-of-time-of-writing Steam on Linux.

`SECONDARY` technically exists but is rarely used and is safely disregarded.

This could be particularly useful for things such as pasting a Steam Guard key or pasting a game activation key set in the `PRIMARY` selection.

This is a low priority, as it is trivial to use another program which supports both selections to transfer from one to the other to get `PRIMARY` selection information (into `CLIPBOARD` and then) into Steam.

Thank you.

**Comment by ChipmunkV** [comment]
How is the progress? Nobody uses ctrl+v usually.

**Comment by tvn87** [comment]
:+1: I am using the mouse selection most of the time. Its kind of boring that steam doesn't fit.

**Comment by kon14** [comment]
Please implement this. It's something most of us use and can be quite handy in many situations.

**Comment by liamdawe** [comment]
@ChipmunkV "How is the progress? Nobody uses ctrl+v usually."

Since when? I do, as I imagine many others do.

**Comment by ScoreUnder** [comment]
You'd be surprised. The only people I know in meatspace who use ctrl+v by default are people who use Windows as their primary OS. Middle click paste is just comfier.

**Comment by kon14** [comment]
I use both of them, especially when I need to cut, paste and combine things, but usually I just select the text and middle click unless I'm on a laptop with no wheel :S

**Comment by Swiftpaw** [comment]
Middle-click for pasting in Steam would be nice indeed! :wolf:

**Comment by jjkinas** [comment]
I use middle click to copy paste ,  +1

**Comment by tadzik** [comment]
Yes please, it's annoying as hell to have to copypaste something to other app to be able to get it inside PRIMARY.

**Comment by tomtomme** [comment]
+1, middle click copy paste was one of the reasons I switched to linux! This is a must have for every Linux App!

**Comment by MiroslavR** [comment]
+1, I also would appreciate this feature.

**Comment by pstn** [comment]
Please implement it. I'm always confused when middle click does not work.

**Comment by ArseniyShestakov** [comment]
Totally agree this should be implemented. Please!

**Comment by Plaque-fcc** [comment]
Well, +1, it is fast and convenient to use.

**Comment by KillaW0lf04** [comment]
I'd love to see this supported if possible!

**Comment by ChipmunkV** [comment]
And that was a bus from the r/linux_gaming!

**Comment by ChipmunkV** [comment]
People, let's celebrate! It's fixed!!!

**Comment by fyrkrans** [comment]
Not being able to use primary selection is such a letdown.  It's sad that not much has happened over the last 5 years when it comes to that.  I really hope it gets fixed as soon as possible.

**Comment by fyrkrans** [comment]
Another year has past and apparently there has been zero progress regarding this issue.  It might not be a big issue, but it's definitely something that makes using Steam cumbersome.

**Comment by Newbie13XD** [comment]
PRIMARY selection is working in the Steam client for me when using middle-click to paste, however, Shift + Insert pastes the CLIPBOARD, so I suppose this is partially fixed?

**Comment by Managor** [comment]
Yeah, you can paste to steam with middle click but you can't copy from steam by highlighting.

**Comment by ChipmunkV** [comment]
In current Steam beta you can copy from steam by highlighting. Do you agree that it's fixed now?

**Comment by Managor** [comment]
I can. PRIMARY selection works from the web view as well as the URL bar

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
