### ISSUE TITLE
Steam Client "About Steam" labels truncated

### ISSUE THREAD

**Issue by yaakov-h** [ValveSoftware/steam-for-linux#1768]
In the "About Steam" dialog, the "Steam package versions" field is visually truncated.

![about_steam_lin](https://f.cloud.github.com/assets/426009/159185/3fa97cb8-7709-11e2-8d0d-079e8d331c48.PNG)

```Processor Information:

```
Vendor:  GenuineIntel

Speed: 3411 Mhz

4 logical processors

4 physical processors

HyperThreading:  Unsupported

FCMOV:  Supported

SSE2:  Supported

SSE3:  Supported

SSSE3:  Supported

SSE4a:  Unsupported

SSE41:  Supported

SSE42:  Supported
```

Network Information:

```
Network Speed:  
```

Operating System Version:

```
Ubuntu 12.04.2 LTS (64 bit)

Kernel Name:  Linux

Kernel Version:  3.2.0-23-generic

X Server vendor:  The X.Org Foundation

X Server release:  11103000
```

Video Card:

```
Driver:  VMware, Inc. Gallium 0.4 on SVGA3D; build: RELEASE;  

Driver Version:  2.1 Mesa 8.0.4

Desktop Color Depth: 24 bits per pixel

Monitor Refresh Rate: 59 Hz

VendorID:  0x15ad

DeviceID:  0x405

Number of Monitors:  1

Number of Logical Video Cards:  1

Primary Display Resolution:  1476 x 871

Desktop Resolution: 1476 x 871

Primary Display Size: 15.39" x 9.06"  (17.83" diag)

                                        39.1cm x 23.0cm  (45.3cm diag)

Primary VRAM Not Detected
```

Sound card:

```
Audio device: Cirrus Logic CS4297A rev 3
```

Memory:

```
RAM:  3948 Mb
```

Miscellaneous:

```
UI Language:  English

LANG:  en_US.UTF-8

Microphone:  Not set

Total Hard Disk Space Available:  41896 Mb

Largest Free Hard Disk Block:  26886 Mb
```

Installed software:

Recent Failure Reports:

```
```

**Comment by kisak-valve** [comment]
Closing as the clipped text does not usually show multiple steam versions anymore.
