### ISSUE TITLE
Trine 2 - "Can't set locale to 'en_GB'"

### ISSUE THREAD

**Issue by PhilipWitte** [ValveSoftware/steam-for-linux#1780]
I'm using Arch Linux 64, Catalyst 13.1, and Gnome-Shell 3.6.3
Everything on this system has be setup correctly, and my default locale is set to 'en_US.utf8'

The Trine 2 launcher has a major bug. It opens fine, but as soon as I click on anything in my system after that, Trine 2 GUI or otherwise (basically on any click event) an error alert pops up saying "Error: Can't set locale to 'en_GB'"

The Trine 2 launcher takes up ~100% of my 4 core AMD Phenom II, so I'm not sure what's going on. The only way I can quit it is through the system-monitor (or terminal) and I cannot play the game.

I have tried launching steam in the following ways, to no avail:

$ LC_ALL=en_US.UTF-8 steam
$ LC_ALL=en_US.utf8 steam
$ LANG=en_US.utf8 steam
$ LANG=C steam

**Comment by kisak-valve** [comment]
Hello @PhilipWitte, are you still experiencing this issue with an up to date system?

**Comment by PhilipWitte** [comment]
Holy crap, it's been awhile. I don't have the same PC hardware, and I'm running Arch-based Linux with KDE 5 on my main PCs now. I can run a test for you after work tonight too see if this issue still exists. Will report back soon.

**Comment by kisak-valve** [comment]
Closing pending feedback.
