### ISSUE TITLE
Anomaly Warzone Earth - Menu fails to load

### ISSUE THREAD

**Issue by d7gonzo** [ValveSoftware/steam-for-linux#1791]
Problem Description:
The intros play back fine but when it's supposed to show the menu a small clump of pixels appears on the very right hand side in the middle, the mouse cursor and the music is still present. Cannot switch to the terminal console and when attempted the mouse cursor is then lost. Only a cold reboot solves the problem but can be accomplished through ssh as well so the computer is not frozen other than the video.

Workarounds:
None known.

Reproduce the issue:
Launch the game and wait for the main menu to try to load.

Processor Information:
Vendor: AuthenticAMD
Model: AMD C-60 APU with Radeon(tm) HD Graphics
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt arat cpb npt lbrv svm_lock nrip_save pausefilter

Operating System Version:
Mint 13 LTS (64 bit)
Kernel Version: 3.2.0-37-generic
Xorg Version: 1:7.6+12ubuntu2

Video Card:
Model: AMD Radeon HD 6290 Graphics
Driver Version:  12.10
Display Resolution:  1366 x 768
GLX Version: 1.4
OpenGL Version: 4.2.11931 Compatibility Profile Context

Memory:
RAM: 3768876 kB

``` systeminfo
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-37-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6290 Graphics

    Driver Version:  4.2.11931 Compatibility Profile Context
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9807
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 10,08" x 5,67"  (11,54" diag)
                                            25,6cm x 14,4cm  (29,3cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3680 Mb

Miscellaneous:
    UI Language:  English
    LANG:  is_IS.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  388781 Mb
    Largest Free Hard Disk Block:  89641 Mb

Installed software:

Recent Failure Reports:

```

**Comment by dieeasy** [comment]
Looks like a time/wait issue.
Workaround involving building and preloading a shared object [here](http://steamcommunity.com/app/282070/discussions/0/610573751159186268/?ctp=4#c530647080133257413).
