### ISSUE TITLE
Steam error when logging in

### ISSUE THREAD

**Issue by AlexanderWright** [ValveSoftware/steam-for-linux#1800]
Like issue #78 I am unable to log into steam.

My computer has full network connectivity, and I can log in from Windows. A packet trace indicates a request for a steampowered.com IP address (208.64.200.190), but no further network activity to that, or any other valve IP address.

Trying to create a new account almost works, correctly flagging up duplicate account names, but then fails with the following error:

Steam error:  SteamGetAppStats(0xf3eccbb8,0xffea9100) failed with error 101: Not logged in
Steam error:  SteamGetAppStats(0xf3eccbb8,0xffea9100) failed with error 101: Not logged in
Steam error:  SteamGetAppStats(0xf3eccbb8,0xffea9100) failed with error 101: Not logged in
SteamDoc.cpp (1809) : Assertion Failed: nRetries > 0
Assert( Assertion Failed: nRetries > 0 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamui/SteamDoc.cpp:1809

Installing breakpad exception handler for appid(steam)/version(1360841030_client)
Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20130215190231_1.dmp
success = yes
response:  CrashID=bp-a10462c0-2c36-415f-a692-7c1c02130215
Generating new string page texture 39: 512x256, total string texture memory is 1.84 MB
Shutting down. . .
unlinked 2 orphaned pipes
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 1874 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 3 multi object alertable sleeps

The dump file can be found here if it is of any help:
https://docs.google.com/file/d/0BzaLDQFArf87azJJd1phcExib1k/edit?usp=sharing

**Comment by kisak-valve** [comment]
Hello @AlexanderWright, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by AlexanderWright** [comment]
Sorry, no longer running a Linux desktop, so can't test.
