### ISSUE TITLE
Preparing to launch Half-Life - freeze, always foreground - Mint

### ISSUE THREAD

**Issue by ymilhahn** [ValveSoftware/steam-for-linux#1803]
After I clicked PLAY in the Half-Life site,
the window with the text "Preparing to launch Half-Life..." is freezing and always in the foreground. I can't click CANCEL, the click get noticed by the window behind it, so the click "goes through" the window.

Half-Life is starting anyway, and is playable.

As far as I noticed this problem only occurs with Half-life.
(Tested TF2 and CS)

Hardware Info:
http://dl.dropbox.com/u/54434157/steam/hwinfo-2013_02_15

**Comment by kisak-valve** [comment]
Hello @ymilhahn, @rogueKLR, are either of you still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
