### ISSUE TITLE
Please make libcef compatible with GLIBC_2.13.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#1806]
Debian testing (and even Debian sid) ship with eglibc 2.13. However, libcef.so requires `GLIBC_2.15`, only for `__fdelt_chk`:

```
$ readelf -s libcef.so | grep -E "@GLIBC_2\.1[4567]"
1037: 00000000     0 FUNC    GLOBAL DEFAULT  UND __fdelt_chk@GLIBC_2.15 (49)
2733: 00000000     0 FUNC    GLOBAL DEFAULT  UND __fdelt_chk@@GLIBC_2.15
```

Is it possible to remove this function from the dynamic imports, so that libcef.so (and thus steamui.so and steam) may load under Debian testing? I'm not really keen on getting the libc from Debian experimental, and I can't figure out [how to shim this function](http://stackoverflow.com/questions/14879644/can-i-trick-libc-glibc-2-13-into-loading-a-symbol-it-doesnt-have-from-glibc).

**Comment by kisak-valve** [comment]
Closing as Debian Sid has moved forward since this issue report.
