### ISSUE TITLE
[Valve games] Mouse leaves window

### ISSUE THREAD

**Issue by spacelike** [ValveSoftware/steam-for-linux#1818]
[EDIT]Added post explaining that this is probably not a steam issue as previously thought[/EDIT]

Several days ago I noticed this starting to occur in all valve games, hl, cs 1.6, cs:source, and tf2.
What happens is sort of like the mouse just stops working (as far rotation goes) but I can still shoot. So it seems the mouse is leaving the window when I turn too fast. This didn't happen before recent updates, sorry I can't pinpoint exactly when it started occurring but it was a few updates ago.

---

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2668 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.1" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.6.11-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11301000
    X Window Manager:  Openbox
    Steam Runtime Version:  <Runtime enabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 295/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x5e0
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 896 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  5961 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  460352 Mb
    Largest Free Hard Disk Block:  357243 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello, if anyone is still experiencing this issue on an up to date system, please open a new issue report in the game-specific issue tracker.
