### ISSUE TITLE
Downloading TF2 is really unreliable

### ISSUE THREAD

**Issue by whereami8224** [ValveSoftware/steam-for-linux#1828]
Steam will start downloading TF2 and make decent progress (~1GB), but then the download will simply stop. It still says "Downloading" but the rate drops to zero. Pausing and resuming has no effect. Restarting steam will allow it to download again for a while. If I wait long enough, it will eventually download a little bit more for a few (~15?) seconds.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3201 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  <Runtime enabled>

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CYPRESS

```
Driver Version:  2.1 Mesa 9.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 30 Hz
VendorID:  0x1002
DeviceID:  0x6898
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 6.30" x 3.54"  (7.20" diag)
                                        16.0cm x 9.0cm  (18.3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  12007 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  612818 Mb
    Largest Free Hard Disk Block:  495471 Mb

Installed software:

Recent Failure Reports:
    Sat Feb 16 03:29:09 2013 GMT: file ''/tmp/dumps/assert_20130215192903_1.dmp'', upload yes: ''CrashID=bp-f1671c9a-ddb8-4ea4-a78a-f2be72130215''
    Sat Feb 16 05:47:09 2013 GMT: file ''/tmp/dumps/assert_20130215214703_1.dmp'', upload yes: ''CrashID=bp-c86be374-33f9-4148-b32b-d24e72130215''

**Comment by kisak-valve** [comment]
Hello @whereami8224, if you are still having this issue with an up to date client, please open a new issue report.
