### ISSUE TITLE
[TF2] Windowed No Border mode reserves space for the border

### ISSUE THREAD

**Issue by hookyboysb** [ValveSoftware/steam-for-linux#1833]
Not really much to explain, a picture best describes the problem.
![Screenshot from 2013-02-16 02:17:05](https://f.cloud.github.com/assets/1856039/163190/674e7a4c-7809-11e2-92a1-9dd05e3fd52c.png)

In this, I am running TF2 in 1440x810, so for most people it would really not be much empty space. However, it kinda gets annoying, especially since you can't really have fullscreen windowed mode (but it seems like alt-tabbing is much more efficient on Mint, at least, than Windows).

I did a lshw (long): http://pastebin.com/VDPj89JL

**Comment by kisak-valve** [comment]
Hello @hookyboysb, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
