### ISSUE TITLE
[TF2] Missing textures on some maps

### ISSUE THREAD

**Issue by ontaiwolf** [ValveSoftware/steam-for-linux#1837]
Hello,

I have a problem since the last update to Catalyst 13.1 with my AMD Radeon HD 6850. I dont have textures on some TF2 maps. Installing 13.2 beta drivers doesn't help, same problem there too.

Screenshot: http://i.imgur.com/AIV9FDP.jpg

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-23-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11300000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series  

```
Driver Version:  4.2.12002 Compatibility Profile Context 9.012
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                        51,8cm x 32,4cm  (61,0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC889A

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  81222 Mb
    Largest Free Hard Disk Block:  36899 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
