### ISSUE TITLE
Steam running fine, TF2 crashing on launch. Arch 64bit

### ISSUE THREAD

**Issue by ArchUser** [ValveSoftware/steam-for-linux#1845]
http://pastie.org/pastes/6198997/text

I have installed lib32-libtxc_dxtn as the wiki says and am running the proprietary nvidia drivers.

**Comment by kisak-valve** [comment]
Hello @ArchUser, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
