### ISSUE TITLE
Back button in Discussions not working properly

### ISSUE THREAD

**Issue by Niwakaame** [ValveSoftware/steam-for-linux#1854]
When I open a discussion with more than 15 posts, there are at least two pages of posts. When I switch to the second page and then hit the back button in the top left corner, the second page is still displayed and not the first one. When I hit the back button again, I come back to the discussions overview.

Can anybody else confirm this?

EDIT: I'm running Ubuntu 12.04 64 bit and Arch Linux 64 bit. It happens both times.

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
