### ISSUE TITLE
Crackling sound in Team Fortress 2

### ISSUE THREAD

**Issue by rabdulatipoff** [ValveSoftware/steam-for-linux#1859]
On my Linux PC I can barely hear any sound in Team Fortress 2. The crackling reduces if I disable "Multicore rendering" in Video settings and almost disappears if I set __GL_THREADED_OPTIMIZATIONS to 0. It also affects Counter-Strike: Source.
GoldSrc games are not affected

http://pastebin.com/DVPEPbLZ
(CPU is Pentium E2180)

**Comment by kisak-valve** [comment]
Hello @rabdulatipoff, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by rabdulatipoff** [comment]
It seems like all the Source games I played on Linux had a similar sound
issue for some time -- a month ago there was an update for CS:GO and I had
crackling sound and half as much FPS before your team fixed it. I guess
there's too little inforamtion to bother with this, and different issues
may be unrelated, next time i'll just create a new bug report
