### ISSUE TITLE
can't type in login panel on archlinux

### ISSUE THREAD

**Issue by alayii** [ValveSoftware/steam-for-linux#1876]
I'm using Archlinux 64bit, 32bit intel driver, nouvea driver and flash-plugin installed, according to Arch wiki https://wiki.archlinux.org/index.php/Steam
not any key can work.
### use Chinese locale cause this problem, you can change to English locale solve it temporarily.

this is console output:

> Running Steam on arch  64-bit
> STEAM_RUNTIME is enabled automatically
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> unlinked 0 orphaned pipes
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> [0218/225511:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> Installing breakpad exception handler for appid(steam)/version(1360966495_client)
> PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
> Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
> Generating new string page texture 8: 32x256, total string texture memory is 163.84 KB
> Generating new string page texture 9: 48x256, total string texture memory is 212.99 KB
> Generating new string page texture 10: 256x256, total string texture memory is 475.14 KB
> Generating new string page texture 11: 64x256, total string texture memory is 540.67 KB
> Shutting down. . .
> unlinked 2 orphaned pipes
> CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
> CAsyncIOManager: 515 single object sleeps, 0 multi object sleeps
> CAsyncIOManager: 0 single object alertable sleeps, 1 multi object alertable sleeps

**Comment by kisak-valve** [comment]
Hello @alayii, are you still encountering this issue with an up to date client?

**Comment by kisak-valve** [comment]
Closing pending feedback.
