### ISSUE TITLE
Team Fortress 2 freeze on loading with shaders setting on high

### ISSUE THREAD

**Issue by razorbackdb** [ValveSoftware/steam-for-linux#1886]
Team Fortress 2 freeze on loading with shaders setting on high, i can set all the other settings to max and msaa x4 without problems, changing shaders setting to high in-game also freeze the game.

Linux Mint 14 64Bit - AMD 13.2 beta 3 drivers.

(sorry for the english)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
