### ISSUE TITLE
Browse Local Files fails due to case sensitivity (Mythbuntu 12.04)

### ISSUE THREAD

**Issue by markau** [ValveSoftware/steam-for-linux#1887]
1. Right-click TF2 -> Properties -> Local Files -> Browse to local files 
2. Error prompt - location not found.

The client is looking for an all lower-case path, e.g. "~/<path>/steamapps", but the directories are named in mixed-case e.g. "Steamapps", therefore not found in Linux.

(Note, this is before I copied any Source libraries from a Windows install, the issue occurs by default with Steam for Linux install.)

Possibly same root cause as #1174 and #1069.

**Comment by kisak-valve** [comment]
Closing as @markau's issue was fixed.
