### ISSUE TITLE
Chat userlist user menu overlaps and out of line

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#1892]
Minor alignment and clipping issue. Can’t confirm if its the same on Windows client.

![Screenshot from 2013-02-19 12:28:36](https://f.cloud.github.com/assets/7708/171214/ee3ad0c2-7a8f-11e2-8412-4bc202af6fd5.png)

**Comment by eiglow** [comment]
With the new Friends UI, this issue seems to now be resolved, if I understand the issue correctly.

**Comment by kisak-valve** [comment]
Closing per the last comment.
