### ISSUE TITLE
Screenshots window has clipping & overlap issues

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#1893]
Scrollbar is clipped (and cannot be used for half of the width), images overlap the window.

![Screenshot from 2013-02-19 01:44:56](https://f.cloud.github.com/assets/7708/171236/a93951fe-7a91-11e2-81f8-ffa01829e570.png)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago.
