### ISSUE TITLE
Steam hangs after purchase is completed

### ISSUE THREAD

**Issue by imranoftherings** [ValveSoftware/steam-for-linux#1895]
after I make a purchase, i.e. on the confirmation screen once I click purchase, steam changes the button to working and then just hangs. The purchase is successful though as I receive an email saying the purchase is successful.

I have noticed it for the 2 purchases I have made using the linux client. I have the dump report saved, but I don't see an option to attach it.

Steam version: built on 15th feb 12:24:26

**Comment by kisak-valve** [comment]
Hello @imranoftherings, if you are still experiencing this issue, please open a new issue report.
