### ISSUE TITLE
"no content server" error dialog set as sticky and always-on-top

### ISSUE THREAD

**Issue by ticho** [ValveSoftware/steam-for-linux#1898]
The error dialog saying:
"No Steam content servers are currently configured to deliver content for this game. This will be corrected soon. Please try again in a few minutes."

...is set to sticky (appears on all virtual desktops) and always-on-top (no other window can cover it). This is not a good idea.

This is the second dialog window with this exact problem, see issue #256 (already fixed).

**Comment by kisak-valve** [comment]
Hello @ticho, are you still experiencing this issue?

**Comment by ticho** [comment]
Hi. I honestly can't tell, because I am not aware of a game which would cause this dialog to appear. :) If you can point me to some, I will gladly test it.

**Comment by kisak-valve** [comment]
Closing pending confirmation this issue still occurs.
