### ISSUE TITLE
Download progress shows total size for some games

### ISSUE THREAD

**Issue by koraktor** [ValveSoftware/steam-for-linux#1905]
I don't know exactly, but I guess this is related to SteamPipe.

For example:

Latest L4D2 update shows 15.5GB although only 16.7MB have been downloaded.

![steam-download](https://f.cloud.github.com/assets/66112/173756/4fdf22b8-7ae7-11e2-9b63-6e077b4811ee.png)

**Comment by kisak-valve** [comment]
Closing as the download information has been reworked since this issue report.
