### ISSUE TITLE
Swapped name in the "Installing" popup

### ISSUE THREAD

**Issue by nivensd** [ValveSoftware/steam-for-linux#1914]
I decided to install BeatHazard, and while I was doing that, activate a key from a bundle (specifically, Demigod). And when I checked both again after afk, I saw that the install window said that it was installing Demigod, even though I had made no action in that direction. Now, it didn't install Demigod (good, as it isn't a SFL game), but it confused me for a second there.

**Comment by kisak-valve** [comment]
Has anyone seen this issue with an up to date client?

**Comment by kisak-valve** [comment]
Closing pending feedback.
