### ISSUE TITLE
[TF2] Format conversion update

### ISSUE THREAD

**Issue by OliverSwift** [ValveSoftware/steam-for-linux#1915]
Hi,

This morning Steam client proposed to update game content to a new format. Ok with this, but the client was totally stuck because on the progress popup that won't dismiss. Moreover, I can't even get the client to iconify so I coumd try to start another game. The client keeps grabbing focus, it is responsive to UI request but popup get on top and I get the "notification bell sound".

I can't even start othe games from start menu I get the "Game is missing" error.

 -Oliver

**Comment by kisak-valve** [comment]
Closing because this scenario should not exist in the wild anymore.
