### ISSUE TITLE
TF2: FPS Drops possibly related to steam ingame

### ISSUE THREAD

**Issue by Arcticcu** [ValveSoftware/steam-for-linux#1924]
Experiencing fps drops which show as slight jitter. Fps drop always when any graphics of steam overlay come to the screen (not talking about a small fps drop, fps literally at least halves). Also, possibly some other random fps drops that show as jitter - i'm not entirely certain if all of it is related to steam ingame.

Intel i7-2600 3.4ghz
AMD Radeon HD 6870
8GB Ram

**Comment by kisak-valve** [comment]
Closing as general video driver performance from 2013 is no longer relevant.
