### ISSUE TITLE
1.0.0.29 segfaults on startup

### ISSUE THREAD

**Issue by kriebz** [ValveSoftware/steam-for-linux#1925]
Cannot run the client at all, but starting from a clean home directory downloads and update and login dialogs appear.  

Debian 7.0 64-bit with glibc files from Ubuntu available in LD_LIBRARY_PATH

Output without debugger is the same with STEAM_RUNTIME set to 0 or 1, line 561, like issue 1226, but stack trace is totally different.

kriebel@farnsworth:~$ DEBUGGER=gdb steam
Running Steam on debian 7.0 64-bit
STEAM_RUNTIME is enabled automatically
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /home/kriebel/Downloads/steam-1.0.0.29/ubuntu12_32/steam...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/kriebel/Downloads/steam-1.0.0.29/ubuntu12_32/steam 
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Installing breakpad exception handler for appid(steam)/version(0_client)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1.0_client)
Installing breakpad exception handler for appid(steam)/version(1.0_client)
[New LWP 31227]
Installing breakpad exception handler for appid(steam)/version(1.0_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 30835 with name 0eBlobRegistryMutex_40A0AB4B4182C7FDA3D4E36E4FD02E4E
removing stale semaphore last operated on by process 30835 with name 0eBlobRegistrySignal_40A0AB4B4182C7FDA3D4E36E4FD02E4E
removing stale semaphore last operated on by process 30835 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 30835 with name 0eSteamEngineLock
[New LWP 31301]
Installing breakpad exception handler for appid(steam)/version(1.0_client)
[0220/151003:ERROR:resource_bundle.cc(411)] Failed to load /home/kriebel/Downloads/steam-1.0.0.29/ubuntu12_32/cef_gtk.pak
Some features may not be available.
[0220/151003:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1.0_client)
Installing breakpad exception handler for appid(steam)/version(1.0_client)
[New LWP 31309]
Installing breakpad exception handler for appid(steam)/version(1.0_client)
Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442.37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 11: 16x256, total string texture memory is 524.29 KB
Generating new string page texture 12: 24x256, total string texture memory is 548.86 KB
Generating new string page texture 13: 32x256, total string texture memory is 581.63 KB
Installing breakpad exception handler for appid(steam)/version(1.0_client)
Generating new string page texture 22: 384x256, total string texture memory is 974.85 KB
Generating new string page texture 24: 256x256, total string texture memory is 1.24 MB

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 31309]
0xf7ccb6d1 in ?? () from /home/kriebel/Steamlibc/libc.so.6
(gdb) bt
#0  0xf7ccb6d1 in ?? () from /home/kriebel/Steamlibc/libc.so.6
#1  0xe9ae253e in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/steamclient.so
#2  0xe9d04f26 in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/steamclient.so
#3  0xe9d05237 in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xe9abae64 in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xe9abbb3e in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xf5a21bba in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/libtier0_s.so
#7  0xf5a202a3 in ?? ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/libtier0_s.so
#8  0xf5a20bd5 in CatchAndWriteMiniDumpExForVoidPtrFn ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/libtier0_s.so
#9  0xf5a20c27 in CatchAndWriteMiniDumpForVoidPtrFn ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/libtier0_s.so
#10 0xf5a22f20 in SteamThreadTools::CThread::ThreadProc(void*) ()

   from /home/kriebel/.local/share/Steam/ubuntu12_32/libtier0_s.so
#11 0xf7d47d4c in start_thread () from /home/kriebel/Steamlibc/libpthread.so.0
#12 0xf7c85f4e in clone () from /home/kriebel/Steamlibc/libc.so.6

(gdb)

**Comment by kisak-valve** [comment]
Hello @kriebz, if you are still experiencing this issue with an up to date system, please open a new issue report.
