### ISSUE TITLE
steam-client startup returns no information

### ISSUE THREAD

**Issue by redhatnation** [ValveSoftware/steam-for-linux#1934]
While helping a fellow Steam user convert to Linux, we came across an unusual symptom.  When starting the steam client from the desktop, nothing happens.  When starting the steam-client from cmd-line, the user sees this:

> Running Steam on ubuntu 12.10 64-bit
> STEAM_RUNTIME is enabled automatically

Then returns to a shell prompt.  No other messages or errors.  Attempts to pipe output to a log file (steam > error.log) returned the same information.

User has a fresh install of Ubuntu 12.10 (64bit).  It was fully patched.  User installed linux-headers and linux-source-generic.  User installed the latest AMD drivers via Software Sources -> Additional Drivers app.  

User has:

> CPU: Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz
> RAM: 8GB
> Video:  Cypress PRO [Radeon HD 5800 Series]
> Steam Client:  1.0.0.29
> AMD Driver: fglrx-amdcccle:amd64 2:9.000-0ubuntu3

User has full access to his desktop and no other problems running apps.

**Comment by kisak-valve** [comment]
Hello @ChrisCrossed, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as upstream support for Ubuntu 12.10 has been discontinued.
