### ISSUE TITLE
Valve source games set their volume to 0

### ISSUE THREAD

**Issue by unbridledExuberance** [ValveSoftware/steam-for-linux#1947]
Half Life 1 when run through pulseaudio and Team Fortress 2 when run with either pulseaudio or ALSA, both set their application volume to 0, so you get no sound.

The workaround is to switch workspaces to get out of the application while leaving it running, going into sound settings, then the applications tab, and moving the volume slider from 0 to max. Ubuntu remembers this setting afterwards so it only needs to be done once.
![Screenshot from 2013-02-21 18:56:00](https://f.cloud.github.com/assets/3622757/183018/50b8376e-7c82-11e2-8176-11eb8d3ca3a7.png)

This issue occurs on Ubuntu 12.04 LTS 64-bit Linux 3.5. Adjusting the volume once for one Source game seems to fix the issue on all other Source games as well.

**Comment by kisak-valve** [comment]
Hello @unbridledExuberance, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
