### ISSUE TITLE
[Support FAQ] 9439-QHKN-1308 "Steam Play" outdated

### ISSUE THREAD

**Issue by housed** [ValveSoftware/steam-for-linux#1952]
https://support.steampowered.com/kb_article.php?ref=9439-QHKN-1308

SteamPlay now supports Linux, but this article doesn't make reference to it. Here's an update to the graphic, too, that's inside of said article:

platform_steamplay.png: ![platform_steamplay](https://f.cloud.github.com/assets/760280/183591/73377918-7ca4-11e2-99a8-ab0627840de3.png)

**Comment by kisak-valve** [comment]
Closing as the referenced page appears to have been updated.
