### ISSUE TITLE
Counter-strike source error

### ISSUE THREAD

**Issue by SteelR** [ValveSoftware/steam-for-linux#1953]
This exit playing on a server...

```
           System:
```

Información sobre el procesador:
    Fabricante:  AuthenticAMD
    Velocidad: 3022 Mhz
    Procesadores lógicos 3
    Procesadores físicos 3
    HyperThreading:  No compatible
    FCMOV:  Compatible
    SSE2:  Compatible
    SSE3:  Compatible
    SSSE3:  Compatible
    SSE4a:  Compatible
    SSE41:  No compatible
    SSE42:  No compatible

Información sobre la red:
    Velocidad de la red:  

Versión del sistema operativo:
    Ubuntu 12.10 (32 bits)
    Nombre de kernel: Linux
    Versión de kernel: 3.5.0-25-generic
    Editor de X Server: The X.Org Foundation
    Versión de X Server: 11300000
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime enabled>

Tarjeta de vídeo:
    Controlador:  ATI Technologies Inc. AMD Radeon HD 6800 Series    

```
Versión de controlador: 4.2.12172 Compatibility Profile Context 12.10.17
Densidad de color del escritorio: 24 bits por píxel
Frecuencia de actualización del monitor: 60 Hz
Identificador del fabricante: 0x1002
Identificador del dispositivo: 0x6739
Número de monitores: 1
Número de tarjetas de vídeo lógicas: 1
Resolución de pantalla principal: 1920 x 1080
Resolución de escritorio: 1920 x 1080
Tamaño de pantalla principal: 18,78" x 10,55"  (21,54" diag)
                                        47,7cm x 26,8cm  (54,7cm diag)
No se ha detectado la memoria VRAM principal
```

Tarjeta de sonido:
    Dispositivo de sonido: Realtek ALC889

Memoria:
    RAM:  3997 Mb

Varios:
    Idioma de la IU:  Español
    LANG:  es_UY.UTF-8
    Micrófono:  Not set
    Espacio total en disco disponible: 280531 MB
    Bloque libre más grande en el disco: 143972 MB

Software Instalado:

Informes de fallos recientes:
    Fri Feb 22 06:11:57 2013 GMT: file ''/tmp/dumps/crash_20130222041150_1.dmp'', upload yes: ''CrashID=bp-76c81980-40cb-4c8d-801e-d1eeb2130221''
    Fri Feb 22 06:15:21 2013 GMT: file ''/tmp/dumps/crash_20130222041514_1.dmp'', upload no: ''Couldn't connect to server''
    Fri Feb 22 06:19:21 2013 GMT: file ''/tmp/dumps/crash_20130222041912_1.dmp'', upload yes: ''CrashID=bp-8b25742e-6f2f-493d-b015-959962130221''

```
       Console output:
```

failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/bin/libsteam.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/bin/libsteam.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system DOES NOT support the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
Installing breakpad exception handler for appid(gameoverlayui)/version(20130219161018_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
[0222/041630:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 240
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198018397264 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198018397264
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_ATI_meminfo: GL_TEXTURE_FREE_MEMORY_ATI: Total Free: 899870, Largest Avail: 678208, Total Aux: 1685765, Largest Aux Avail: 8192
GL_MAX_SAMPLES_EXT: 8
[0222/041632:ERROR:resource_bundle.cc(411)] Failed to load /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cef_gtk.pak
Some features may not be available.
[0222/041632:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3022 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4191158272
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3022 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4191158272
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx6.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx6.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx6.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx6.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx7.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx7.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx7.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx7.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx8.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx8.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx8.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx8.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx9.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/cstrike/bin/game_shader_dx9.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
 failed to dlopen /home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx9.so error=/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2/bin/game_shader_dx9.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 2, MultisampleQuality: 0
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 0 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 96 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 100 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 100 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 100 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 100 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 168 ps-combo 3
CGLMShaderPair::SetProgramPair: Centroid masks differ at link time of vertex shader lightmappedgeneric_vs20 and pixel shader decalbasetimeslightmapalphablendselfillum2_ps20b!
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file teeth_flashlight_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file teeth_flashlight_ps20b ps-index 0 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file teeth_flashlight_ps20b ps-index 0 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file teeth_flashlight_ps20b ps-index 0 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 4 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 4 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 4 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 4 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 4
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 5
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 6
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 7
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 8
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 9
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 10
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 11
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 12
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 13
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 14
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1056 ps-combo 15
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000004) differs from mask derived from shader name (0x0000000C) for shader ps-file shatteredglass_ps20b ps-index 40 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 4
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 5
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 6
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 7
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 8
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 9
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 10
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 11
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 12
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 13
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 14
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file worldtwotextureblend_ps20b ps-index 1632 ps-combo 15
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 24 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 24 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 24 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 24 ps-combo 3
Loaded program cache file "glshaders.cfg", total keyvalues: 352, total successfully linked: 352
Precache: Took 27378 ms, Vertex 812, Pixel 1282
Game.so loaded for "Counter-Strike: Source"
Game update: AppID 240 "Counter-Strike: Source", ProcID 3455, IP 200.69.192.155:27016
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 40 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 40 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 40 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 40 ps-combo 3
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file eyes_flashlight_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file eyes_flashlight_ps20b ps-index 0 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file eyes_flashlight_ps20b ps-index 0 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file eyes_flashlight_ps20b ps-index 0 ps-combo 3
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20130222041912_1.dmp
success = yes
response:  CrashID=bp-8b25742e-6f2f-493d-b015-959962130221
/home/steelr/Steam/SteamApps/steelro/Counter-Strike Source/hl2.sh: línea 72:  3455 Violación de segmento  (`core' generado) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 240 "Counter-Strike: Source", ProcID 3455 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by kisak-valve** [comment]
Hello @SteelR, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
