### ISSUE TITLE
TF2: Raw input unreliable

### ISSUE THREAD

**Issue by BlueIce** [ValveSoftware/steam-for-linux#1960]
Since it seems i cannot reopen a closed issue, I'm creating a new one.
In TF2 with raw input enabled, sometimes mouse clicks are not registered:
See #967.
If some can reopen #967, feel free to close this one.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by cob16** [comment]
@kisak-valve I currently have this issue. It started without changing any in game settings this week. If you are interested i can post my system info.

**Comment by kisak-valve** [comment]
Hello @cob16, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
