### ISSUE TITLE
MOTD cannot be closed with KP_ENTER

### ISSUE THREAD

**Issue by hleVqq** [ValveSoftware/steam-for-linux#1962]
The KP Enter button can no longer be used to close the MOTD, so the players are forced to either do it with their mouse or press Enter (which requires to move one of the arms away from either WASD or the mouse). Kinda annoying when you're trying to quickly join the game and team.

**Comment by kisak-valve** [comment]
Hello @hleVqq, if you are still experiencing this issue, please open a new issue report on the appropriate game-specific issue tracker.
