### ISSUE TITLE
CS:S crashes after short time being in game

### ISSUE THREAD

**Issue by MitchK** [ValveSoftware/steam-for-linux#1966]
Hi,

CS:S worked perfectly with bumblebee/primus and nvidia-current, now i switched to nvidia-experimental-310 (with bumblebee and primus). With my current configuration Serious Sam 3 and Half Life run perfectly, but CS:S does no more.

CS:S crashes after approx. 10 seconds being ingame.

I'm using 
Ubuntu 12.04 64bit with Bumblebee and Primus (with 32-Bit Primus-Libs) and nvidia-experimental-310

My full system's specs are here: https://www.dropbox.com/s/25mznnowghj66t6/hardware.txt
Crash output: https://www.dropbox.com/s/znufgxgk9iswjzk/crash-output.txt
dmp-File: https://www.dropbox.com/s/s8n6pusl5zta3s8/crash.dmp

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
