### ISSUE TITLE
Segfault when starting steam after GPU crash

### ISSUE THREAD

**Issue by tadzik** [ValveSoftware/steam-for-linux#1969]
This is related to https://github.com/ValveSoftware/halflife/issues/484

The game crashes with the following log (ran with gdb): https://gist.github.com/tadzik/5019648

I tried installing libdrm-intel1-dbg and libdrm-intel1-dbg:i386, but that didn't give any more detailed information.

Reboot fixes the issue.

This may be more of a driver bug, as starting other, non-steam games sometimes result in a segfault too (for example the game redeclipse), the general conclusion being: steam broke my GPU driver system-wide, for some reason. That may not be the client's fault, but I'm opening this just in case.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
