### ISSUE TITLE
Steam Cloud deleted my Dungeon of Dredmore saves

### ISSUE THREAD

**Issue by mirkobern** [ValveSoftware/steam-for-linux#1971]
i had a Dredmore game going,  playing and saving ok, 

then yesterday i was on a place without internet connection, tried to start dredmore and it taken a loong time, than thought it a connection problem,  so i started steam and put it in offline mode.

then launched  dredmore and it started ok.

i played for a few hours, then saved and quitted.

today i started steam, gone on-line  started dredmore and my savegame reverted to the day before yesterday throwing away 5 hours of gameplay!!!!

i tryed to look to the savegames, both in 
/home/berna/.local/share/Dredmor/indiana\ raist.dredmorsave/ 
and
/home/berna/.local/share/Steam/userdata/68855062/98800/remote/indiana\ raist.dredmorsave/

in the first of the two directories the savegame presented the correct number of saved levels (i descended to the third) in the second dir it showed only two levels (and an old screenshot)...

so i tryed a hand copy of the files from the first to the second...

on the library tab of steam i saw the syncronization taking place, slowly, so i thought un upload was in action...

then i restarted dredmore and saw that the saves were still the old ones :(

exited the game and saw that the fucking sync had functioned...   in reverse!!!!
the old files overwritten the newer!!!

so i permanently lost 5 hours of game play...

then it got worse,  after a sequence of event that unfortunately i could only partially reconstruct    i frantically tried  many things,  

starting and stopping steam, going off line, starting a new dredmore char saving and quitting  going online starting dredmore to see if the bad sincronization repeat  and some more things....

even the old save of my beloved char wasn't present anymore!!!

looking in the save directory (indiana raist.dredmorsave) thins time the directory was present but empty in the local copy and present and full in the steam one, but the game doesn't show the option to select it to me!!

what could i do to recover that game?

i was hoping that the steam cloud help not losing the saves  not kill it even more!!!

**Comment by kisak-valve** [comment]
Hello @mirkobern, are you still experiencing this issue? Can you confirm that this was brought to the attention of the game devs?

**Comment by mirkobern** [comment]
Hello @mirkobern, are you still experiencing this issue? Can you confirm that this was brought to the attention of the game devs?




Sorry the fact happened so many years ago that I don't remember anything

**Comment by kisak-valve** [comment]
Closing pending feedback.
