### ISSUE TITLE
Counter Strike: Source font unavailable on Debian Sid x86_64

### ISSUE THREAD

**Issue by flyingstar16** [ValveSoftware/steam-for-linux#1975]
Hi,

I've just downloaded and installed CS:S, and, after solving a missing dependency, I was able to start the game.
My problem is that there seems to be no font support for it: every character is replaced by a black rectangle, and sometimes there's no text at all.

I tried logging on to a random sever (via random clicking) and that seems to work, but when I reached the team (or weapon?) selection screen, there was no way I would've understood what to do.

I'm attaching 2 screenshots, one of the first page of the game, and one of what I think is the "Settings" menu. (4th link, top to bottom, in the main screen)

Thanks!

Claudio

![Main screen](https://f.cloud.github.com/assets/582280/188251/089f5db8-7dd6-11e2-8052-6a3545551a92.png)

![Settings menu](https://f.cloud.github.com/assets/582280/188250/0861199a-7dd6-11e2-89e0-30ead01a6296.png)

**Comment by kisak-valve** [comment]
Hello @flyingstar16, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
