### ISSUE TITLE
[Steam] Loading pages extremly slow

### ISSUE THREAD

**Issue by gutigen** [ValveSoftware/steam-for-linux#1996]
I've noticed that everytime I change a page in discussion or try to move from Library to Store or any other part of Steam it takes literally 20-30seconds to load when at same moment it's pretty much instant when I'm using Google Chrome to surf through Steam content.

Happens in Ubuntu 12.10 and 13.04, Unity and Gnome Shell.
Everything updated to latest versions from official Ubuntu repos.
60Mbit connection with no packet loss (tested with MTR).

System info:
https://gist.github.com/gutigen/4984001

Terminak output:
https://gist.github.com/gutigen/5024272

**Comment by kisak-valve** [comment]
Hello @gutigen, are you still experiencing this issue with an up to date system?

**Comment by gutigen** [comment]
Hey @kisak-valve, I suspect this was fixed some time ago, cause I don't really recall last time I encountered this issue.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
