### ISSUE TITLE
Parse /etc/os-release instead of relying on lsb_release for distribution information.

### ISSUE THREAD

**Issue by Meyithi** [ValveSoftware/steam-for-linux#2005]
The client should parse /etc/os-release instead of depending on the lsb_release script.

I know only Ubuntu is supported (which coincidentally has an /etc/os-release file) but a lot of distro's which have /etc/os-release will not have lsb_release installed as default (such as Arch Linux) so there is no way of knowing the host distro.

**Comment by itaranto** [comment]
Not every distro have the command **lsb_release** installed by default.
Almost all modern distros use **/etc/os-release** (Debian, Ubuntu, openSUSE, Fedora, Arch, ...). 
Please use that instead.
