### ISSUE TITLE
[3rd party games] Kentucky Route Zero: Crash after the 1. Act

### ISSUE THREAD

**Issue by goodn1ght** [ValveSoftware/steam-for-linux#2014]
At the end of Act 1 the game crashes, tried 2 times both times crash. Also had a crash in the middle of the game before but could play on after restarting the game, not this time though.

Console output:

Installing breakpad exception handler for appid(steam)/version(1360966495_client)
Failed to load installscript /home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/installscript.vdf
Game update: AppID 231200 "Kentucky Route Zero", ProcID 14305, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Found path: /home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI
Mono path[] = '/home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI_Data/Managed'
Mono path[1] = '/home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI_Data/Mono'
CAPIJobRequestUserStats - Server response failed 2
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Installing breakpad exception handler for appid(gameoverlayui)/version(20130215122411_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)

(gameoverlayui:14353): Gtk-WARNING **: Im Modulpfad »oxygen-gtk« konnte keine Themen-Engine gefunden werden,

(gameoverlayui:14353): Gtk-WARNING **: Im Modulpfad »oxygen-gtk« konnte keine Themen-Engine gefunden werden,
[0225/175407:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0225/175407:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Generating new string page texture 156: 128x256, total string texture memory is 2,02 MB
Generating new string page texture 157: 512x256, total string texture memory is 2,54 MB
Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!
Game removed: AppID 231200 "Kentucky Route Zero", ProcID 14305 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Generating new string page texture 169: 1024x256, total string texture memory is 3,59 MB
Generating new string page texture 170: 256x256, total string texture memory is 3,85 MB
Failed to load installscript /home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/installscript.vdf
Game update: AppID 231200 "Kentucky Route Zero", ProcID 14607, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Found path: /home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI
Mono path[] = '/home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI_Data/Managed'
Mono path[1] = '/home/micha/Soft/steam/usr/lib/steam/SteamApps/common/KentuckyRouteZero/KentuckyRouteZero_ActI_Data/Mono'
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Installing breakpad exception handler for appid(gameoverlayui)/version(20130215122411_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)

(gameoverlayui:14655): Gtk-WARNING **: Im Modulpfad »oxygen-gtk« konnte keine Themen-Engine gefunden werden,

(gameoverlayui:14655): Gtk-WARNING **: Im Modulpfad »oxygen-gtk« konnte keine Themen-Engine gefunden werden,
[0225/184924:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0225/184924:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x220265d
Serial number of failed request:  797932
xerror_handler: X failed, continuing
Game removed: AppID 231200 "Kentucky Route Zero", ProcID 14607 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please contact the game devs.
