### ISSUE TITLE
Steam uses 'execheap' which according to expert ' is really a bad idea'

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/steam-for-linux#2028]
Ulrich Drepper - the lead contributor and maintainer on GNU C - said this about using execheap:

"The POSIX specification does not permit it, but the Linux implementation of mprotect allows changing the access protection of memory on the heap (e.g., allocated using malloc). This error indicates that heap memory was supposed to be made executable. Doing this is really a bad idea. If anonymous, executable memory is needed it should be allocated using mmap which is the only portable mechanism."

There are a couple of articles about it:

http://danwalsh.livejournal.com/6117.html
http://www.akkadia.org/drepper/selinux-mem.html

The use of execheap is a Linux wide issue, but the issue was reported by SELinux on Fedora 18. #1471 dismissed it as a Fedora issue incorrectly when it in fact affects Ubnutu and all other Linux distributions equally.

**Comment by xenithorb** [comment]
I'm seeing this issue trying to run CS: GO

```
type=AVC msg=audit(1447315069.388:734): avc:  denied  { execheap } for  pid=5299 comm="csgo_linux" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=proce
type=ANOM_ABEND msg=audit(1447315069.458:735): auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=5299 comm="csgo_linux" exe=2F686F6D652F78656E6974682F2E6C6F63616C2F73686172652F537465616D2F73
```

**Comment by Ruedii** [comment]
43 and 88 should be moved to this bug, not the other way around.

As of the bug itself, yes, I agree this is a bad idea.  It impedes porting this to other platforms.

However, I also think since it's not causing any major bugs, it should be very low priority if it is reopened.

**Comment by 12g** [comment]
This happened to me when running Half-Life 2 as well.

`type=AVC msg=audit(1506262460.962:1067): avc:  denied  { execheap } for  pid=17822 comm="hl2_linux" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0`
