### ISSUE TITLE
[Team Fortress 2] Mouse, graphics, and minimization issues

### ISSUE THREAD

**Issue by Sakura** [ValveSoftware/steam-for-linux#2040]
This is probably around three or four distinct bugs, but they have a combined effect that makes it less than functional for some reason.  

Mouse 1:  The mouse ingame mouse coordinates don't line up with the WM mouse pointer, causing some buttons to be hard/impossible to click in 800x600 (default resolution fr some reason.)

Mouse 2 & Minimization 1: When the mouse leaves the window for any reason (like trying to scroll down to the config menu (as a side note the TF2 config directory does not appear to be populated)), the window will minimize. 

Minimization 2 & Graphics 1: When the window is restored from minimized, the size of the underlying screen changes (looking like it would be suitable on 1024x768).  

And graphics 2? (& client 1?)  For whatever reason, -w (which should allow me to set the width, isn't being respected or passed.

What TF2 _thinks_ it's showing me:  
http://i.imgur.com/YG36U7a.jpg
What TF2 is actually showing me:
http://i.imgur.com/ckZAGn8.png
(These were taken after a minimize cycle.)

<pre>Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2111 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-3-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  FVWM
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22
    
Video Card:
    Driver:  NVIDIA Corporation GeForce 9800 GTX/9800 GTX+/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 313.18
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 84 Hz
    VendorID:  0x10de
    DeviceID:  0x612
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1024 x 768
    Desktop Resolution: 1600 x 1200
    Primary Display Size: 13.62" x 10.20"  (17.01" diag)
                                            34.6cm x 25.9cm  (43.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 512 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: TriTech TR28602
    
Memory:
    RAM:  8005 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  395199 Mb
    Largest Free Hard Disk Block:  19026 Mb
    
Installed software:
    
Recent Failure Reports:
    Wed Feb 20 06:11:52 2013 GMT: file ''/tmp/dumps/assert_20130219221145_1.dmp'', upload yes: ''CrashID=bp-939a6f21-69b7-4958-9ed7-f99ed2130219''
    Wed Feb 20 06:12:13 2013 GMT: file ''/tmp/dumps/assert_20130219221206_1.dmp'', upload yes: ''CrashID=bp-22457476-684d-4b62-9889-106b92130219''
    Wed Feb 20 10:04:51 2013 GMT: file ''/tmp/dumps/assert_20130220020447_1.dmp'', upload yes: ''CrashID=bp-c154c883-96ab-4d33-89ec-349cd2130220''
    Wed Feb 20 23:04:52 2013 GMT: file ''/tmp/dumps/assert_20130220150445_1.dmp'', upload yes: ''CrashID=bp-574db788-646e-44d5-b63e-0cf022130220''
    Thu Feb 21 11:59:13 2013 GMT: file ''/tmp/dumps/assert_20130221035907_1.dmp'', upload yes: ''CrashID=bp-6cd1aead-a1d3-4d4b-880e-5af3a2130221''
    Tue Feb 26 04:51:14 2013 GMT: file ''/tmp/dumps/assert_20130225205113_1.dmp'', upload no: ''Couldn't resolve host name''
    Wed Feb 27 01:46:29 2013 GMT: file ''/tmp/dumps/assert_20130226174625_1.dmp'', upload yes: ''CrashID=bp-933a2ca4-f68d-499e-978f-cc59d2130226''
    Wed Feb 27 13:09:33 2013 GMT: file ''/tmp/dumps/assert_20130227050904_1.dmp'', upload yes: ''CrashID=bp-7ef02ac2-d119-488e-9310-ea81e2130227''
</pre>

**Comment by kisak-valve** [comment]
Hello @Sakura, a fair bit has changed since this issue report was filed. If you are still experiencing these issues with an up to date system, please open a new issue report in the Source-1-Games issue tracker, one issue per issue report.

For the game minimizing, this sounds like the desktop environment was taking focus away from the game, and the default behavior, which you can change, is to minimize the game. `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` stops this behavior.
