### ISSUE TITLE
Team Fortress 2 Crash on Load

### ISSUE THREAD

**Issue by dsnettleton** [ValveSoftware/steam-for-linux#2047]
Error message received in console:
/home/dsnettleton/.local/share/Steam/SteamApps/common/Team Fortress 2 Beta/hl2.sh: line 72: 18883 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 520 "Team Fortress 2 Beta", ProcID 18877 

It should be noted that I have an NVidia optimus graphics card, so I'm launching the game with the launch option:
"$OPTIMUS_PREFIX %command%"

Hardware detection according to Steam, which is launched without the optimus prefix, is below.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2301 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-25-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 9.0.2
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xdcd
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 15.04" x 8.46"  (17.24" diag)
                                        38.2cm x 21.5cm  (43.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  7880 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  430083 Mb
    Largest Free Hard Disk Block:  176655 Mb

Installed software:

Recent Failure Reports:
    Sun Feb 24 19:24:07 2013 GMT: file ''/tmp/dumps/assert_20130224142359_1.dmp'', upload yes: ''CrashID=bp-eb158b4f-1f2c-48c2-ad22-3a6232130224''
    Sun Feb 24 23:39:59 2013 GMT: file ''/tmp/dumps/assert_20130224183959_1.dmp'', upload no: ''Couldn't resolve host name''

**Comment by kisak-valve** [comment]
Hello @dsnettleton, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
