### ISSUE TITLE
Engine Error in TF2

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/steam-for-linux#2049]
It seems like at random during play it will get this error:

Model models/player/items/spy/veteran_hat.mdl not found and models/error.mdl couldn't be loaded

After I click OK, the game crashes along with the Steam client.

Here are my specs, just in case it means anything:
OS/Distro: Ubuntu Linux 12.04 64-bit (Kernel Version: 3.5.0-25-generic)
Desktop Environment: Unity 2D
Motherboard: ASRock Z68 Pro3-M
Processor: Intel Core i7-2600 @ 3.8GHz (Hyperthreading Enabled)
Graphics: Nvidia GeForce GTX 560 (1GB VRAM)
Memory: 16GB DDR3 1333MHz RAM
Hard Drive: 500GB Samsung SSD

This has happened both in the Nvidia 310.32 driver and when I upgraded to 313.18.

**Comment by kisak-valve** [comment]
Hello, is anyone seeing this issue with an up to date system?

**Comment by salt86** [comment]
No

**Comment by kisak-valve** [comment]
Thanks for retesting @salt86, closing.
