### ISSUE TITLE
Big Picture Mode loses focus after exiting a game

### ISSUE THREAD

**Issue by discreaderror** [ValveSoftware/steam-for-linux#2050]
After launching a game from within Steam Big Picture Mode, and then exiting the game, the Big Picture Mode window remains minimized, instead of regaining focus. Tested it with TF2, Bastion and Shank 2.

Repro steps:
1. Start Steam
2. Click Big Picture Mode Icon
3. Select game from library
4. Exit game
5. Now back on the desktop

System info:

```
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.9-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302901
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GTS 450/PCIe/SSE2

    Driver Version:  4.3.0 NVIDIA 313.18
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 74 Hz
    VendorID:  0x10de
    DeviceID:  0xdc4
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16.14" x 10.24"  (19.09" diag)
                                            41.0cm x 26.0cm  (48.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3955 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  74160 Mb
    Largest Free Hard Disk Block:  1724 Mb

Installed software:

Recent Failure Reports:
```

**Comment by GNUletik** [comment]
I got the same issue with my two archlinux configs (laptop and desktop).

Here are my system informations.
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6601
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 12,17" x 6,89"  (13,98" diag)
                                            30,9cm x 17,5cm  (35,5cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: IDT 92HD91BXX
    
Memory:
    RAM:  15949 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  346457 Mb
    Largest Free Hard Disk Block:  59797 Mb
    VR Headset: None detected
```

**Comment by Hori873** [comment]
I've got this issue too on a laptop on my current Arch Linux installation and I remember having it on the previous installation also.
GNOME 3.20 DE

**Comment by ouija** [comment]
Same issue as well with Ubuntu 14.04

**Comment by Enigma0** [comment]
This issue is not fixed or has come up again in 16.04.1.

**Comment by mattbell87** [comment]
Happens to me on Fedora 24 and did the same when I was on 23, both on stock Gnome3. I have to Alt+Tab every time I quit a game. 

A side note, I also often get the screen appearing off centre after I quit a game. I can see my Gnome wallpaper behind Big Picture after I switch back. Seems to happen more if I use a lower resolution in Steam than my native. I'm not sure if that is related to this bug or if it belongs in another issue.

**Comment by taylorjacklespriggs** [comment]
Same issue with Openbox and Steam version 1474415843

**Comment by parkerlreed** [comment]
Happening on Arch Linux using Gnome on the latest Steam beta.

**Comment by HoratiuMl** [comment]
I can confirm this is still happening for me too on Arch with Gnome - and it has been happening for a looong time. I've been using BP regularly for about a year now but I used it before as well (rarely) and the bug was there even then.

It is very annoying when using a controller.

**Comment by parkerlreed** [comment]
@HoratiuMl The even more annoying part is this even happens when using the Steam Link. (Granted the mouse controls of the Steam controller make it a bit easier to get back to it)

Also there is a currently open issue https://github.com/ValveSoftware/steam-for-linux/issues/4611

**Comment by HoratiuMl** [comment]
@parkerlreed Thanks for the link to the open issue.
Wow, I didn't expect it to happen to the Steam Link as well. This is really bad. Unfortunately I don't have one so I cannot try it. I wouldn't have a need for it personally since I don't have a TV anyway.

**Comment by parkerlreed** [comment]
I'm not sure when or what update but Big Picture is correctly coming into focus after exiting games now. Using both the exit menu in the overlay and exiting a game from its own menu.

**Comment by wright3189** [comment]
Having the same issue. Noticed it while streaming games from my Windows box to my Fedora system. It's annoying because I launch Steam in Big Picture mode through an SSH session, but whenever I exit a game, I need to VNC and remaximize Steam again.
