### ISSUE TITLE
[Linux] Team Fortress 2 black screen

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2056]
OS: Ubuntu 12.04.2 LTS x64 bit
Kernel: 3.5.0-*
Issue: Screen is always black, sound can be heard
Reproduction steps: N/A
System config:

**Processor Information:**
    Vendor:  GenuineIntel
    Speed: 2133 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported  

**Operating System Version:**
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-25-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

**Video Card:**
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2

```
Driver Version:  2.1 Mesa 9.0.2
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x8086
DeviceID:  0x46
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13,54" x 7,64"  (15,51" diag)
                                        34,4cm x 19,4cm  (39,4cm diag)
Primary VRAM Not Detected
```

**Sound card:**
    Audio device: Intel IbexPeak HDMI

**Memory:**
    RAM:  3755 Mb

**Miscellaneous:**
    UI Language:  English
    LANG:  sk_SK.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  339105 Mb
    Largest Free Hard Disk Block:  167190 Mb

**Comment by kisak-valve** [comment]
Closing as the user has turned into a ghost and per the last comment.
