### ISSUE TITLE
TF2 fps problem

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2061]
I'm no expert, but I noticed some video settings combinations that seem to fix a couple of problems. For example, HDR disabled causes the game not to crash on Server Welcome Screen. Upgrading the Kernel to 3.5.0-25 on Ubuntu 12.04 fixes fps random drops (see tutorial bellow). On Ubuntu 13.04 with 310.32 drivers, disabling anti-aliasing fixes fps drop problem.

http://steamcommunity.com/app/221410/discussions/0/864960986991466725/

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3013 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-9-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 310.32
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x614
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 12,20" x 9,06"  (15,20" diag)
                                        31,0cm x 23,0cm  (38,6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1705

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  253885 Mb
    Largest Free Hard Disk Block:  205418 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @amarildojr, I'm going to go ahead and close this as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report in the Source-1-Games issue tracker.
