### ISSUE TITLE
CS 1.6. - MOTD window BUG Report! (Steam)

### ISSUE THREAD

**Issue by Nbanow** [ValveSoftware/steam-for-linux#2062]
Hello, I have noticed a bug. It is not because of plugin's fault, It's because of MOTD Window, which is not working correctly. MOTD window can't open plugin's Windows media player window. Problem appeared 2-3 days ago, after I've updated steam. 

![missingb](https://f.cloud.github.com/assets/3747295/212681/6b42fd72-8325-11e2-85fb-05baf6afae33.jpg)

**Comment by kisak-valve** [comment]
Closing per the last comment.
