### ISSUE TITLE
Steam failing to load due to segfault

### ISSUE THREAD

**Issue by brittyazel** [ValveSoftware/steam-for-linux#2063]
Yesterday steam was working beautifully, but today I can not get it to load at all. I have purged it from my system numerous times, and I have ran steam --reset to no avail. According to the report there is some sort of segfault on line 700 of the steam.py script. I have also seen that other people from other distros are having this same issue.

I am running arch linux x86_64.

[britt@BrittArchPC ~]$ steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[2013-03-02 02:39:42] Checking for update on startup
[2013-03-02 02:39:42] Checking for available updates...
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[2013-03-02 02:39:42] Download complete.
[2013-03-02 02:39:42] Verifying installation...
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 7670 with name 0eBlobRegistryMutex_1C921C0FBC6C50F24AD711C8EFBFB84D
removing stale semaphore last operated on by process 7670 with name 0eBlobRegistrySignal_1C921C0FBC6C50F24AD711C8EFBFB84D
removing stale semaphore last operated on by process 7670 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 7670 with name 0eSteamEngineLock

(steam:7782): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:7782): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1137: error: unexpected identifier `direction', expected character`}'
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[0302/023943:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
/home/britt/.local/share/Steam/steam.sh: line 700:  7782 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
[britt@BrittArchPC ~]$

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
