### ISSUE TITLE
Team Fortress 2 - FPS drop after using FN keys to change volume.

### ISSUE THREAD

**Issue by Tikie** [ValveSoftware/steam-for-linux#2067]
When I use my FN keys during in-game without the Steam overlay, the FPS drops around 50%. Was running it on 1024x768.

On the other hand, when I changed the volume when I had the Steam overlay on, it did not impact the FPS in my opinion.

System Info:
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1600 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-25-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6310 Graphics

```
Driver Version:  4.2.12172 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x9802
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 10.63" x 5.91"  (12.13" diag)
                                        27.0cm x 15.0cm  (30.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3557 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  95714 Mb
    Largest Free Hard Disk Block:  45982 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver performance from 2013 is no longer relevant.

This is low end hardware and the desktop environment most likely was compositing a volume level indicator to cause the performance drop.
