### ISSUE TITLE
Unable to Browse the Sever List  

### ISSUE THREAD

**Issue by emini** [ValveSoftware/steam-for-linux#2072]
When i was just updating somehow then i started TF2 and look at severs and it is empty and i thought that Source's master sever database is unavailable that means i cannot manually view or connect to any severs and my Favorite lists were not shown up. I have tried other ways (Reinstalling, Checking File Integrities, Changing Scripts, Looking up Commands, Reading Logs that have no trace to this) none have worked and i thought that my Steam Cloud sever listing files where defective. Is there any other cure to this?       

![2013-03-02--1362263801_1360x768_scrot](https://f.cloud.github.com/assets/3175003/213490/7ae9ff2c-838a-11e2-992d-4586e5a003a2.png)
## ![2013-03-02--1362263918_1360x768_scrot](https://f.cloud.github.com/assets/3175003/213493/9d10e34a-838a-11e2-8389-f9056971731e.png)

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.0-9.dmz.2-liquorix-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 313.18
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x11c6
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1360 x 768
Desktop Resolution: 1360 x 768
Primary Display Size: 18.15" x 10.24"  (20.83" diag)
                                        46.1cm x 26.0cm  (52.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7977 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  146212 Mb
    Largest Free Hard Disk Block:  92218 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
