### ISSUE TITLE
Big Picture with "broken" top left corner

### ISSUE THREAD

**Issue by thor27** [ValveSoftware/steam-for-linux#2075]
If you open Steam with steam -bigpicture, as soon as the main screen shows, steam loses focus, when you alt+tab again to get focus on the top left corner of the window looks broken, and the mouse cursor changes.

This was originally posted as a steam-login issue here: https://github.com/thor27/steam-login/issues/8 but this actually happens when using steam with any DE that I tried.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
