### ISSUE TITLE
No sounds in Half Life 1 (Lubuntu 12.10)

### ISSUE THREAD

**Issue by maxbrunner** [ValveSoftware/steam-for-linux#2079]
I've installed steam and Half Life 1 but there is no sound (no music and no sound effects).

Reading another issues, I tried to start with SDL_AUDIODRIVER=alsa and SDL_AUDIODRIVER=pulseaudio, with the same result (no audio).

Somebody can help me? 

Terminal output starting only with steam:

$ steam
Running Steam on ubuntu 12.10 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 1992 with name 0eBlobRegistryMutex_35449F5EA50C7C38242274C3EEA43E8B
removing stale semaphore last operated on by process 1992 with name 0eBlobRegistrySignal_35449F5EA50C7C38242274C3EEA43E8B
removing stale semaphore last operated on by process 1992 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 1992 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[0303/130429:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB

(steam:2292): GLib-CRITICAL **: g_io_channel_new_file: assertion `filename != NULL' failed
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Adding license for package 0
Adding license for package 34
Adding license for package 19336
ExecCommandLine: "/home/max-lubuntu/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 72: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 73: 128x256, total string texture memory is 1,49 MB
Generating new string page texture 74: 256x256, total string texture memory is 262,14 KB
Generating new string page texture 75: 64x256, total string texture memory is 1,56 MB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 78: 384x256, total string texture memory is 1,95 MB
Generating new string page texture 79: 8x256, total string texture memory is 1,96 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 80: 256x256, total string texture memory is 2,22 MB
roaming config store loaded successfully - 306 bytes.
migrating temporary roaming config store
System startup time: 25,34 seconds
Running Steam on ubuntu 12.10 32-bit
STEAM_RUNTIME has been set by the user to: /home/max-lubuntu/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/max-lubuntu/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 83: 512x256, total string texture memory is 2,74 MB
Generating new string page texture 84: 128x256, total string texture memory is 2,88 MB
Failed to load installscript /home/max-lubuntu/.local/share/Steam/SteamApps/common/Half-Life/installscript.vdf
Game update: AppID 70 "Half-Life", ProcID 2415, IP 0.0.0.0:0

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2292): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198057925417 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198057925417
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Error initializing MSAA frame buffer

ARB Multitexture extensions found.

8 texture units.  Detail texture supported.

Installing breakpad exception handler for appid(gameoverlayui)/version(20130224234706_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
[0303/130500:ERROR:resource_bundle.cc(411)] Failed to load /home/max-lubuntu/.local/share/Steam/SteamApps/common/Half-Life/cef_gtk.pak
Some features may not be available.
[0303/130500:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
[0303/130500:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Platform config directory: platform/config
0:Initializing platform...
S_Startup: SNDDMA_Init failed.

AL lib: pulseaudio.c:651: Stream did not get ready: Argumento inválido
ALSA lib pcm_pulse.c:750:(pulse_prepare) PulseAudio: Unable to create stream: Argumento inválido

AL lib: alsa.c:642: set params failed: Erro de entrada/saída
Server module initialized.

World module initialized.

STEAM Auth Server

AL lib: pulseaudio.c:651: Stream did not get ready: Argumento inválido
AppActive: active
ALSA lib pcm_pulse.c:750:(pulse_prepare) PulseAudio: Unable to create stream: Argumento inválido

AL lib: alsa.c:642: set params failed: Erro de entrada/saída
AppActive: active
Installing breakpad exception handler for appid(hl_linux)/version(1.0_client)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198057925417 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198057925417
Game update: AppID 70 "Half-Life", ProcID 2424, IP 0.0.0.0:27015
AL lib: pulseaudio.c:651: Stream did not get ready: Argumento inválido
ALSA lib pcm_pulse.c:750:(pulse_prepare) PulseAudio: Unable to create stream: Argumento inválido

AL lib: alsa.c:642: set params failed: Erro de entrada/saída
Unknown command: VModEnable

Dropped Player from server
Reason:  Server shutting down

AL lib: pulseaudio.c:651: Stream did not get ready: Argumento inválido
ALSA lib pcm_pulse.c:750:(pulse_prepare) PulseAudio: Unable to create stream: Argumento inválido

AL lib: alsa.c:642: set params failed: Erro de entrada/saída
World module shutdown.

Server module shutdown.

SDL_InitSubSystem(SDL_INIT_AUDIO) failed.
Game removed: AppID 70 "Half-Life", ProcID 2424 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by kisak-valve** [comment]
Hello @maxbrunner, @FreeSlave, are either of you still experiencing this issue with an up to date system?

**Comment by FreeSlave** [comment]
No, I have not experienced this problem in Half-Life for a long time. I don't even remember the moment when it got fixed.

**Comment by maxbrunner** [comment]
@kisak-valve I'm not playing Half-Life on Ubuntu for a while now. But I also remember playing it with sound, so it should be ok.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
