### ISSUE TITLE
After update Waveform does not allow to configure resolution

### ISSUE THREAD

**Issue by lumag** [ValveSoftware/steam-for-linux#2080]
After one of recent updates, Waveform starts with fullscreen resolution (but not in fulscreen mode). Previously Waveform displayed additional window with mode selection. Now I see that window being opened and immediately disappearing, so no mode selection is possible.
System details: Debian 7.0 weezy (testing), nouveau video driver.

**Comment by kisak-valve** [comment]
Hello @lumag, are you still experiencing this issue with an up to date system? If you are, this should be brought to the attention of the game's devs.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
