### ISSUE TITLE
Player models not downloading?

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/steam-for-linux#2082]
I play on custom css server which have custom models for players. For some reason terrorist models don't download/work. It's russian server so it's too complicate to ask them for a help. I see terrorists as HUGE error text.

**Comment by kisak-valve** [comment]
Hello @deri82, was this the same issue as https://github.com/ValveSoftware/Source-1-Games/issues/535? If you encounter this issue again, check what sv_pure is set to on the server.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/Source-1-Games/issues/535.
