### ISSUE TITLE
Install popup overlaps estimated time and install path - latest steam update

### ISSUE THREAD

**Issue by aurikai** [ValveSoftware/steam-for-linux#2083]
I just updated steam linux today (march 3rd, 2013) and decided to purchase a couple games made available to steam linux recently. Attached is an image demonstrating a strange occurrence on the window that comes up after purchase to install the games now.

The "Estimated Time" section overlaps the dropdown for the the install location. This did not happen on previous versions of Steam Linux.  I tried a search and did not see a duplicate post of this issue so my apologies if a duplicate exists.

Steps to re-create: Add game(s) to cart, complete purchase, in the popup to install games now, go through the steps to reach the screen attached below.

![installoverlap](https://f.cloud.github.com/assets/3112036/214848/560b4b7a-844d-11e2-8177-fde37ce3df17.png)

System info:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2

```
Driver Version:  4.2.0 NVIDIA 304.51
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xe22
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 17.05" x 10.67"  (20.08" diag)
                                        43.3cm x 27.1cm  (51.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1023 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  142107 Mb
    Largest Free Hard Disk Block:  27441 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @aurikai, if you are still experiencing this issue, please open a new issue report.
