### ISSUE TITLE
Wargame: European Escalation not start

### ISSUE THREAD

**Issue by Longer** [ValveSoftware/steam-for-linux#2084]
Failed to load installscript /home/longer/.local/share/Steam/SteamApps/common/Wargame European Escalation/installscript.vdf
Game update: AppID 58610 "Wargame: European Escalation", ProcID 32114, IP 0.0.0.0:0

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:31322): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Setting breakpad minidump AppID = 58610
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198025556803 [API loaded no]
terminate called after throwing an instance of 'Eugen::EGraphicInit'
  what():  ChangeMode failure
Game removed: AppID 58610 "Wargame: European Escalation", ProcID 32114

---

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2095 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile 

```
Driver Version:  2.1 Mesa 9.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x116
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13,54" x 7,64"  (15,51" diag)
                                        34,4cm x 19,4cm  (39,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  2853 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  371191 Mb
    Largest Free Hard Disk Block:  21542 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @Longer, are you still experiencing this issue with an up to date system?

**Comment by Longer** [comment]
@kisak-valve this problem gone in 2013. I long time not playing in this game, but in second part of 2013 I normally played.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
