### ISSUE TITLE
Steam can't login, "having trouble connecting to the Steam servers"

### ISSUE THREAD

**Issue by sylbru** [ValveSoftware/steam-for-linux#2085]
At first launch, Steam displays an error message saying something like "Fatal error: Steam needs to be online to [...]", yet it does download the files without any issues after clicking Ok. I'm not sure this is related to the real issue, that is:
When it is fully downloaded and I try to login, it fails: "Steam is having trouble connecting to the servers." Retrying doesn't help.
The internet is perfectly working, and Steam for Windows logs in without any issues.
I already tried a full reinstall, including rm -r .steam/ .steampid .steampath .local/share/Steam/

I'm using Arch Linux, with NetworkManager.
Someone suggested the bug has something to do with launching NetworkManager through dbus, or so.

**Comment by ivan-kolmychek** [comment]
It's been a while, but I just fixed the same issue by removing `dhclient` from the system. Quite strange, actually, but fairly ok. :)

**Comment by vboufleur** [comment]
@ivan-kolmychek how did you knew you had to remove the dhclient package?

**Comment by ivan-kolmychek** [comment]
I don't remember exactly, but probably it was a tip from this comment just a bit above on this thread:

> At least in my case, (where it could not access the servers and whatnot) it was a bug relating to the fact that I had both dhclient and dhcpcd installed on my system. I'm not sure if dhclient alone will get along with steam, but once I switched back to dhcpcd everything started working again.
([willrandship commented on Sep 22, 2013](https://github.com/ValveSoftware/steam-for-linux/issues/2085#issuecomment-24886584))

So, I've decided to check it and it so happens to work. I don't really need dhclient and I don't even remember why I had it installed. :)

**Comment by Diederikjh** [comment]
Had the "could not connect" problem on Ubuntu with working Internet just now. Launching with `--reset` command line param fixed it for me.
