### ISSUE TITLE
Indicator whites-out when clicking Unity button

### ISSUE THREAD

**Issue by njallam** [ValveSoftware/steam-for-linux#2089]
When in the dash (after clicking the Home button in the launcher), the steam indicator at the top whites out.  This is because when in the dash, the indicators appear white.  This however does not work for the Steam icon very well and looks like a bug while it is actually normal functionality in Unity.

![Steam Indicator Normal](https://f.cloud.github.com/assets/3257085/218215/19dd70c2-8503-11e2-928f-99613c41509e.png)
![Steam Indicator Dash](https://f.cloud.github.com/assets/3257085/218217/1c6846be-8503-11e2-8403-6ceac4942cc1.png)

**Comment by kisak-valve** [comment]
Hello @njallam, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
