### ISSUE TITLE
[TF2]: Crash in team selection when map is loaded only in online game

### ISSUE THREAD

**Issue by ZeXx86** [ValveSoftware/steam-for-linux#209]
Hello
My issue persist maybe from beginning of Beta test and occurs on two different distributions I've tested - Ubuntu 12.10 64bit and Arch Linux 64bit (same machine).
This bug affecting me cca 7/10 cases I start the game and ONLY in Online, mostly official servers.

I can start Team Fortess 2 and it works always as it should in menu and working with around 100 - 200 FPS in any map I've tested in Offline/Training practise with 16 bots.

A) If I am connected to Online server(Find server automatically) and I wait until level is loaded then I can see Team selection menu but this is time where TF2 freezes completly. Sound starts to loop last sequence for cca 3 seconds and then game crashes completly.

B) Whats more, another 2/10 cases game does not crash in Team selection I can play game BUT FPS is locked to cca 9-12 FPS only and command top show me around 120% CPU and 46% MEM usage of first instance of MainThrd, second instance is around 3% CPU / 10% MEM. In this time, my desktop environment is very lazy and sometime I can see SWAP Memory is used by 260MB after map is loaded. This case is very likely BUG #140.

C) Last 1/10 cases game is running online without any issue - this case happen only when I am connected to some community servers with rather small maps (Dodge ball maps, DM_Store, etc)

Interestingly, if I start Offline map, disconnect from it and then connect to any online server, game is running without any issue too. So simply I dont understand it, it seems it is not memory related, just something with initialization.

My log from console after crash:
http://pastebin.com/2L2DEfw9

Log from pmap when TF2 is running with ~10FPS - pmap $(pidof hl2_linux):
http://pastebin.com/xBBNrUDP
Screenshot of top command:
![Sn mek obrazovky po zen 2012-12-21 11:17:10](https://f.cloud.github.com/assets/3097353/26931/7d997dae-4b60-11e2-9cb2-5d9c89bd1287.png)

My HW config:
http://pastebin.com/4VjHLGJD

Thanks for any help

**Comment by kisak-valve** [comment]
Closing as general video driver and/or TF2 stability from 2012 is not longer relevant. If you are still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
