### ISSUE TITLE
New username-based menu makes notifications menu and account menu unusable

### ISSUE THREAD

**Issue by meowy** [ValveSoftware/steam-for-linux#2096]
After opening up the notification button menu, I'm unable to click on any items. It appears that the new big button beneath the menu is being told that the mouse hovers over it, making it open up its own menu. And that, for some reason, closes both menus, leaving me with none open. 

The same issue occurs when I try to use the menu provided by the "username's Account" link when the Steam client is resized to its minimum width. However, this menu is still usable and functions completely normally under one condition: I have to move my cursor around the bounding box of the text before hovering over the menu; the cursor must not enter the bounding box. If I "enter" the menu with my cursor that way, it will not be closed abnormally.

This issue is illustrated in the following screen capture:
[dead link]
I haven't made a capture of the behavior when "username's Account" is clicked, but I could supply one if needed.

The menus that are opened by Steam's menu bar (Friends, Games, Help...) do not trigger this behavior, at least not with the other buttons.

System information:
Linux Mint 14 Nadia (64-bit)
Cinnamon desktop (GNOME 3-based)

Steam version/build: March 4 2013, at 13:20:23

**Comment by kisak-valve** [comment]
Hello @meowy, @stevethepocket, are either of you experiencing this issue with the current client?

**Comment by meowy** [comment]
Hey @kisak-valve, I cannot reproduce this, though I'm no longer on the Linux client.

**Comment by kisak-valve** [comment]
Glad to hear it got fixed and thanks for retesting. Closing.
