### ISSUE TITLE
CS doesn't launch

### ISSUE THREAD

**Issue by mentorious** [ValveSoftware/steam-for-linux#2105]
Here's terminal output:
http://pastebin.com/syieS6YZ

System informations:
http://pastebin.com/ha5HZq2V

Drivers fglrx-updates (though Additional Drivers), version:

ls /var/lib/dkms/fglrx-updates
9.000  kernel-3.5.0-26-generic-x86_64

**Comment by kisak-valve** [comment]
Hello @mentorious, if you're still experiencing this issue with an up to date system, please open a new issue report.
