### ISSUE TITLE
TF2 "This system supports the OpenGL extension"

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2106]
Ubuntu 13.04, fully updated with 313.26 drivers.

I'm getting tired of trying everything in order to play TF2. This happens on every distro of Ubuntu and also openSUSE, with every possible combination, except on this tutorial http://steamcommunity.com/app/221410/discussions/0/864960986991466725/

It starts with normal FPS then drops to 10. On openSUSE it starts with 10.
I had a copy of TF2 downloaded on Ubuntu 12.04 from January 6 (just for bandwidth saving), this caused the game to start at 10 fps, but I decided to re-download it and it starts normal but again drops to 10 fps.

It's very frustrating because a lot of users seem to have this and it doesn't seem that it's being fixed at all.

---

teste@teste-desktop:~$ steam
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[0307/065728:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
`menu_proxy_module_load': /home/teste/.local/share/Steam/ubuntu12_32/steam: undefined symbol: menu_proxy_module_load

(steam:2644): Gtk-WARNING **: Failed to load type module: (null)

Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Adding license for package 0
Adding license for package 7
Adding license for package 37
Adding license for package 523
Adding license for package 609
Adding license for package 783
Adding license for package 980
Adding license for package 2319
Adding license for package 2481
Adding license for package 4415
Adding license for package 4466
Adding license for package 7932
Adding license for package 13054
Adding license for package 16222
roaming config store loaded successfully - 1939 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
ExecCommandLine: "/home/teste/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 70: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 71: 128x256, total string texture memory is 1,49 MB
Generating new string page texture 72: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 73: 32x256, total string texture memory is 1,52 MB
Generating new string page texture 74: 64x256, total string texture memory is 1,59 MB
Generating new string page texture 77: 128x256, total string texture memory is 1,72 MB
Generating new string page texture 78: 512x256, total string texture memory is 2,24 MB
Generating new string page texture 79: 384x256, total string texture memory is 2,64 MB
Generating new string page texture 80: 24x256, total string texture memory is 2,66 MB
Generating new string page texture 81: 8x256, total string texture memory is 2,67 MB
Generating new string page texture 104: 128x256, total string texture memory is 2,80 MB
System startup time: 8,18 seconds
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/teste/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/teste/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 82: 256x256, total string texture memory is 3,06 MB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Game update: AppID 440 "Team Fortress 2", ProcID 2764, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:2644): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
Installing breakpad exception handler for appid(gameoverlayui)/version(20130224234706_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Gtk-Message: Failed to load module "overlay-scrollbar"
[0307/065745:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 440
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198042163203 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198042163203
Did not detect any valid joysticks.
Gtk-Message: Failed to load module "overlay-scrollbar"
[0307/065747:ERROR:resource_bundle.cc(411)] Failed to load /home/teste/.local/share/Steam/SteamApps/toquinhasss/Team Fortress 2/cef_gtk.pak
Some features may not be available.
[0307/065747:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Loaded program cache file "glbaseshaders.cfg", total keyvalues: 266, total successfully linked: 266
Loaded program cache file "glshaders.cfg", total keyvalues: 304, total successfully linked: 304
Precache: Took 2183 ms, Vertex 869, Pixel 1769
Game.so loaded for "Team Fortress"
Game update: AppID 440 "Team Fortress 2", ProcID 2770, IP 200.98.130.163:27015
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 524288, Total Avail: 524288, Current Avail: 314872
GL_MAX_SAMPLES_EXT: 16
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3611 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4146069504
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3611 MHz, Processor: AuthenticAMD
GlobalMemoryStatus: 4146069504
IDirect3DDevice9::Create: BackBufWidth: 1280, BackBufHeight: 1024, D3DFMT: 3, BackBufCount: 1, MultisampleType: 4, MultisampleQuality: 0
Game removed: AppID 440 "Team Fortress 2", ProcID 2770 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x10004b0
Serial number of failed request:  37283
xerror_handler: X failed, continuing

---

Sys info

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3613 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-11-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.26
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x614
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 12,20" x 9,06"  (15,20" diag)
                                        31,0cm x 23,0cm  (38,6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1705

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  253959 Mb
    Largest Free Hard Disk Block:  187525 Mb

Installed software:

Recent Failure Reports:
    Thu Mar  7 10:26:06 2013 GMT: file ''/tmp/dumps/crash_20130307072601_1.dmp'', upload yes: ''CrashID=bp-37a0f855-6c24-402b-9b21-5d48a2130307''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
