### ISSUE TITLE
Workaround for FPS drop on TF2

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2110]
Such a simple fix for the fps drop! No Kernel upgrade, no scripts, nothing.
Simply open the Terminal and type "sudo nvidia-settings"
Next go to "Nvidia Settings configuration" and there change "Power Mizer Monitor" to 60000 and uncheck that box. There you go =)

http://img585.imageshack.us/img585/4190/selection001a.png

Now only thing left is to solve that problem with HDR.

Don't forget to uncheck "Sync to v-blank" as well, to make sure your mouse works properly.

Please respond if this fixed your problems. Hope it helps more out there.

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3613 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Raring Ringtail (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-11-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.26
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x614
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 12,20" x 9,06"  (15,20" diag)
                                        31,0cm x 23,0cm  (38,6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1705

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  232671 Mb
    Largest Free Hard Disk Block:  188908 Mb

Installed software:

Recent Failure Reports:

**Comment by rgrauphics** [comment]
GENTS - seems like this is a dead thread but... I had some issues with Frame lag. I would get 50-100+ FPS but would still get the jumping video... What my XServer was doing was seeing my dual monitors as one large monitor. 3840x1080... I told the x server to look at the 2 monitors instead of thinking it was one.

Problem solved for me.

**Comment by kisak-valve** [comment]
Hello @amarildojr, the same as #2061. Closing as general video driver quality from 2013 is no longer relevant.
