### ISSUE TITLE
Counter Strike Mouse Wheel less sensitive

### ISSUE THREAD

**Issue by bvibhav** [ValveSoftware/steam-for-linux#2112]
Well I am using mouse wheel to jump and it has just become insensitive with today's update, i plug-in my old mouse the scroll works fine. it seems to be working fine in cs1.6 non steam as well as CSS but not in CS after the update.

I have to drag the scroll fully to make a successful jump which is useless for a gamer.
how do i sort it out. is there a new command for wheel sensitivity too??

**Comment by kisak-valve** [comment]
Closing as this appears to have been a hardware issue.
