### ISSUE TITLE
Half-Life - Buggy Raw Mouse Input in Fuduntu

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/steam-for-linux#2114]
Hey guys. I have been playing Half-Life on my recent installation of Fuduntu 2013.1 (a fork of Fedora), and everything works fine for the most part. However, I am having an issue when I have raw mouse input enabled. I can look around just fine, but sometimes it won't register a left mouse click to swing the crowbar or fire a weapon. It will sometimes even register several continuous clicks (several crowbar swings, etc) until I click again. It's pretty difficult to explain. I had to disable raw input in order to have complete responsiveness. This issue persists on both a Razer Naga and a generic Gateway mouse. Other people I've talked to (that also use Fuduntu) also have this problem when raw input is enabled. I'll also note that I don't have this problem on Ubuntu 12.04.

Here's my specs:
GPU: Nvidia GeForce GTX 560
CPU: Intel Core i7-2600 @ 3.8 GHz (Hyperthreading Enabled)
RAM: 16 GB DDR3 @ 1333 MHz

**Comment by kisak-valve** [comment]
Hello @PyGuy95, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
