### ISSUE TITLE
Steam doesn't remember my computer - with every start, guard wants new key

### ISSUE THREAD

**Issue by play3man** [ValveSoftware/steam-for-linux#2125]
Everything is in name of this issue. It also lost save data (iBomber Defense Pacific Demo), but I think it has something to do with first issue.

Intel GMA 4500M
Ubuntu 12.10 32bit

Steam version from february 24th

**Comment by kisak-valve** [comment]
Closing as this issue does not appear to be actionable. If you are still having trouble with that game, please contact the game devs.
