### ISSUE TITLE
Segfault on TF2 startup (Ubuntu 12.10 64bit, GEForce GTX 480)

### ISSUE THREAD

**Issue by roylaurie** [ValveSoftware/steam-for-linux#2134]
Hi, guys.

I have the Ubuntu experimental 310 drivers installed.

I tried two different install methods:
- dpkg -i foo.deb
- apt-get steam

I wiped the ~/.steam and ~/.local/shared/Steam before re-installing.

The result is the same in both attempts: Steam runs fine, but TF2 fails to start. An X Window opens with the words "OpenGL" in the Window Title, then closes a second later. Nothing happens afterwords. Here's a partial log of steam installing TF2 and then attempting to start it. The SEGFAULT is near the bottom.

System startup time: 4404.44 seconds
Running Steam on ubuntu 12.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/rlaurie/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/rlaurie/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 110: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 111: 128x256, total string texture memory is 1.38 MB
Generating new string page texture 139: 48x256, total string texture memory is 1.43 MB
Generating new string page texture 140: 256x256, total string texture memory is 1.69 MB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 142: 1024x256, total string texture memory is 2.74 MB
Generating new string page texture 143: 512x256, total string texture memory is 3.26 MB
Generating new string page texture 144: 128x256, total string texture memory is 3.39 MB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
CAsyncIOManager: creating I/O worker thread
CAsyncIOManager: creating I/O worker thread
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
CAsyncIOManager: creating I/O worker thread
CAsyncIOManager: creating I/O worker thread
CAsyncIOManager: creating I/O worker thread
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
CAsyncIOManager(0xd7abeb40) send on fd 75 failed with errno 11 (Resource temporarily unavailable)
Generating new string page texture 185: 256x256, total string texture memory is 3.65 MB
CAsyncIOManager: creating I/O worker thread
Generating new string page texture 150: 384x256, total string texture memory is 4.05 MB
Generating new string page texture 188: 128x256, total string texture memory is 4.18 MB
Generating new string page texture 151: 256x256, total string texture memory is 4.44 MB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Game update: AppID 440 "Team Fortress 2", ProcID 3984, IP 0.0.0.0:0
saving roaming config store to 'sharedconfig.vdf'
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
roaming config store 2 saved successfully
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
Installing breakpad exception handler for appid(gameoverlayui)/version(20130224234706_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Using breakpad crash handler

(gameoverlayui:3995): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(gameoverlayui:3995): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Setting breakpad minidump AppID = 440
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970999086 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197970999086
[0310/182056:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Did not detect any valid joysticks.

(hl2_linux:3990): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(hl2_linux:3990): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
[0310/182058:ERROR:resource_bundle.cc(411)] Failed to load /home/rlaurie/.local/share/Steam/SteamApps/kylratix/Team Fortress 2/cef_gtk.pak
Some features may not be available.
[0310/182058:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
The program 'hl2_linux' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 676 error_code 8 request_code 140 minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Missing shutdown function for DevShotGenerator_Init() : DevShotGenerator_Shutdown()
Missing shutdown function for MapReslistGenerator_Init() : MapReslistGenerator_Shutdown()
Missing shutdown function for COM_InitFilesystem( m_StartupInfo.m_pInitialMod ) : COM_ShutdownFileSystem()
Missing shutdown function for Steam3Client().Activate() : Steam3Client().Shutdown()
/home/rlaurie/.local/share/Steam/SteamApps/kylratix/Team Fortress 2/hl2.sh: line 72:  3990 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 440 "Team Fortress 2", ProcID 3990 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

Here is my Steam System Information output:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3601 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-02-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xe22
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3200 x 1080
Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                        52.1cm x 29.3cm  (59.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1023 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  7775 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  600904 Mb
    Largest Free Hard Disk Block:  322621 Mb

Installed software:

Recent Failure Reports:
    Sun Mar 10 22:32:06 2013 GMT: file ''/tmp/dumps/assert_20130310153148_1.dmp'', upload yes: ''CrashID=bp-e5fa0dbc-0f84-40e5-a98c-587d72130310''
    Sun Mar 10 22:32:17 2013 GMT: file ''/tmp/dumps/assert_20130310153211_1.dmp'', upload yes: ''CrashID=bp-2d4771f4-a585-4cdf-aa42-6822f2130310''
    Sun Mar 10 22:32:27 2013 GMT: file ''/tmp/dumps/assert_20130310153159_1.dmp'', upload yes: ''CrashID=bp-e6584857-06a9-4a80-8e55-5a1e42130310''

**Comment by kisak-valve** [comment]
Closing as general video driver issues from 2013 are no longer relevant.
