### ISSUE TITLE
Team Fortress 2 - Horrible performance with AMD 7850.

### ISSUE THREAD

**Issue by mikedebian** [ValveSoftware/steam-for-linux#2141]
Having gone through the drivers and clean installs to check for errors since Ubuntu 12.04/12.10 with the AMD Catalyst 12.10-13.1-beta7 driver I've gone from about 5 fps to about 25 FPS when joining multiplayer and offline training servers. If I change any of these settings to a higher value, my FPS will crawl, making the game quite unplayable.

I have no problems with other OpenGL applications/games. I have no running desktop applications in the background and I even keep the steam window closed and start the game from the icon on my Unity bar. I've done clean installs and tested the provided driver by Ubuntu and built the latest for myself using AMDs latest packages. I had the same performance when I had my AMD Radeon HD 5770, using another computer (I have quite a few to test the game out on.)

All applications are updated and so is Steam.
If any more info is required, please ask (note that English is my third language, so please keep that in mind if you're planning to write a technical reply to me with "fancy" english words in them ;) )

AMD FX-4100
DDR3 4GB RAM @ 1600MHZ
AMD Radeon HD 7850.

My Team Fortress video settings are as follows:

Resolution:         1920x1080
Fullscreen

Model detail:       High
Texture detail:     Medium
Shader detail:      High
Water detail:        Simple reflections
Shadow detail:     Medium
Color Correction:  Enabled

AA Mode:             None
Filtering mode:      Bilinear
VSYNC:               Disabled
Motion Blur:          Disabled
FOV:                    90
Multicore rendering: Disabled
HDR:                    None
No bloom effects
## 

Prosessorinformasjon:
    Leverandør: AuthenticAMD
    Hastighet: 4214 Mhz
    4 logiske prosessorer
    4 fysiske prosessorer
    Hypertrådkjøring: Som ikke støttes
    FCMOV: Som støttes
    SSE2: Som støttes
    SSE3:Som støttes
    SSSE3:Som støttes
    SSE4a:Som støttes
    SSE41:Som støttes
    SSE42:Som støttes

Nettverksinformasjon:
    Nettverkshastighet: 

Operativsystem-versjon:
    Ubuntu 12.10 (64 biter)
    Kjernenavn: Linux
    Kjerneversjon: 3.5.0-26-generic
    X Serverleverandør: The X.Org Foundation
    X Serverutgave: 11300000
    X Window Manager: Compiz
    Steam Runtime-versjon: steam-runtime-release-i386_2013-03-08

Skjermkort:
    Driver: ATI Technologies Inc. AMD Radeon HD 7800 Series

```
Driverversjon: 4.2.12172 Compatibility Profile Context 12.10.17
Dybde på skrivebordsfarge: 24 biter per piksel
Skjermoppdateringsfrekvens: 60 Hz
Leverandør-ID:  0x1002
Enhets-ID:  0x6819
Antall skjermer: 1
Antall logiske skjermkort: 1
Oppløsning på hovedskjerm: 1920 x 1080
Skrivebordsoppløsning: 1920 x 1080
Størrelse på hovedskjerm: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Hoved-VRAM ikke oppdaget
```

Lydkort:
    Lydenhet: Realtek ALC892

Minne:
    RAM: 3918 MB

Diverse:
    Grensesnittspråk: Norsk (Norsk)
    LANG:  en_US.UTF-8
    Mikrofon:  Not set
    Total harddiskplass tilgjengelig: 779896 MB
    Største ledige harddiskblokk: 423206 MB

**Comment by kisak-valve** [comment]
Hello @mikedebian, if you are still experiencing this issue with an up to date system, please open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. We're going to have to assume this was a general video driver quality issue from 2013. Closing.
