### ISSUE TITLE
Counter-Strike Source crash on start/applaunch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2145]
Hi, I'm running Linux Mint 14 Nadia 64bit (MATE) ..comparable to Ubuntu 12.10 Quantal?
with ia32-libs installed
## Kernel:

3.5.0-25-lowlatency
## output running steam in terminal

("steam" in terminal ..when it started, pressing play in steam)
Running Steam on linuxmint 14 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
unlinked 0 orphaned pipes
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
[0313/131639:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Adding license for package 0
Adding license for package 37
Adding license for package 13054
roaming config store loaded successfully - 709 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
ExecCommandLine: "/home/tom/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 71: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 72: 256x256, total string texture memory is 262,14 KB
Generating new string page texture 73: 128x256, total string texture memory is 1,49 MB
Generating new string page texture 74: 128x256, total string texture memory is 393,22 KB
Generating new string page texture 75: 64x256, total string texture memory is 1,56 MB
Generating new string page texture 76: 32x256, total string texture memory is 1,59 MB
Generating new string page texture 80: 384x256, total string texture memory is 1,98 MB
Generating new string page texture 81: 256x256, total string texture memory is 2,24 MB
System startup time: 12,20 seconds
Running Steam on linuxmint 14 64-bit
STEAM_RUNTIME has been set by the user to: /home/tom/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/tom/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 83: 128x256, total string texture memory is 2,38 MB
Generating new string page texture 84: 512x256, total string texture memory is 2,90 MB
Game update: AppID 240 "Counter-Strike: Source", ProcID 24077, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:23359): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
SDL video target is 'x11'
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130224234706_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
[0313/131715:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 240
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198050320689 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198050320689
[0313/131717:ERROR:resource_bundle.cc(411)] Failed to load /home/tom/.local/share/Steam/SteamApps/tom/Counter-Strike Source/cef_gtk.pak
Some features may not be available.
[0313/131717:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
/home/tom/.local/share/Steam/SteamApps/tom/Counter-Strike Source/hl2.sh: line 72: 24083 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 240 "Counter-Strike: Source", ProcID 24083 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
## output running hl2.sh in terminal

LD_PRELOAD="~/.steam/bin/gameoverlayrenderer.so" ./hl2.sh -game cstrike -steam
ERROR: ld.so: object '~/.steam/bin/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '~/.steam/bin/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '~/.steam/bin/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '~/.steam/bin/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '~/.steam/bin/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system DOES NOT support the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
Using breakpad crash handler
Setting breakpad minidump AppID = 240
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198050320689 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198050320689
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_ATI_meminfo: GL_TEXTURE_FREE_MEMORY_ATI: Total Free: 924328, Largest Avail: 760352, Total Aux: 1703125, Largest Aux Avail: 1641
GL_MAX_SAMPLES_EXT: 8
Could not load chromehtml library.IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
./hl2.sh: line 72: 24402 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
## ldd gameoverlayrenderer.so

ldd /home/tom/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
    linux-gate.so.1 =>  (0xf77b6000)
    libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xf7634000)
    libGL.so.1 => /usr/lib32/fglrx/libGL.so.1 (0xf754a000)
    librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf7540000)
    libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7514000)
    libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf750f000)
    libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7426000)
    libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf740b000)
    /lib/ld-linux.so.2 (0xf77b7000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7260000)
    libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xf723e000)
    libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xf722c000)
    libatiuki.so.1 => /usr/lib32/fglrx/libatiuki.so.1 (0xf7215000)
    libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf71f7000)
    libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xf71f2000)
    libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xf71eb000)
## Computer

Processor: 4x AMD Phenom(tm) II X4 955 Processor
Memory: 8176MB (1692MB used)
Operating System: Linux Mint 14 Nadia
User Name: tom (Tom)
-Display-
Resolution: 1920x1080 pixels
GPU: ATI Radeon HD 5870 (Powercolor PCS)
X11 Vendor: The X.Org Foundation
-Multimedia-
Audio Adapter: HDA-Intel - HDA ATI SB
## fglrxinfo (using fglrx-updates from additional drivers menue)

display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: ATI Radeon HD 5800 Series
OpenGL version string: 4.2.11903 Compatibility Profile Context

edit:
Latest Beta Driver 13.2 from http://support.amd.com/us/gpudownload/Pages/index.aspx works (but still having some microlags)

**Comment by kisak-valve** [comment]
Closing a general video driver quality from 2013 is no longer relevant, and the user appears to have turned into a ghost.
