### ISSUE TITLE
counter strike source (linux) can't see greek characters

### ISSUE THREAD

**Issue by bluelife3d** [ValveSoftware/steam-for-linux#2146]
I can't see greek characters on chat or on players names. I have seen cyrillic/slavic names but I can't see greek..

I have to point that I can't even see what I write when I use greek, but others can...

system is ubuntu 12.10 with hd 5770 card

**Comment by kisak-valve** [comment]
Hello @bluelife3d, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
