### ISSUE TITLE
Unity of Command doesn't start

### ISSUE THREAD

**Issue by BastienDurel** [ValveSoftware/steam-for-linux#2148]
Hello,

Unity of command does not start. Whend clicking on "Play", a pop-up shows, I choose "Play Unity of Command", then click on "Play", I see another window during half a second, then nothing.

Here are the stdout logs :

ExecSteamURL: "steam://open/downloads"
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Installing breakpad exception handler for appid(steam)/version(1361807486_client)
Generating new string page texture 137: 256x256, total string texture memory is 5,55 MB
Failed to load installscript /opt/steam/SteamApps/common/Unity of Command/installscript.vdf
Game update: AppID 218090 "Unity of Command", ProcID 13637, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Segmentation fault
Game removed: AppID 218090 "Unity of Command", ProcID 13637 
saving roaming config store to 'sharedconfig.vdf'

There is no installscript.vdf in /opt/steam/SteamApps/common/Unity of Command/
I tried to validate files, all succesfully validated.

**Comment by kisak-valve** [comment]
Hello @BastienDurel, are you still experiencing this issue with an up to date system? Do you happen to remember if the game devs were made aware of this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.
