### ISSUE TITLE
[CS1.6-Linux 5984] Cannot use mouse buttons anymore (again)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2154]
Hello, despite the update I am still unable to use the buttons of my mouse. Disabling m_rawinput will make the game totally ignore my mouse (while in game). The strange thing is that I have changed nothing on my system and it was working fine (rawinput) _before_ the 5983 build.

console output : 

] version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 11:05:05 Mar 13 2013 (5984)

Kernel info:
xx@xx:~$ uname -a
Linux xx 3.2.0-4-amd64 #1 SMP Debian 3.2.35-2 x86_64 GNU/Linux

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/halflife/issues/900#issuecomment-15868958.
