### ISSUE TITLE
Windows with graphical errors

### ISSUE THREAD

**Issue by obedlink** [ValveSoftware/steam-for-linux#2168]
when I change the language to steam and then I click "ok", the window asking if steam must be restarted is displayed with graphical errors.

same for when selecting the option "Check for Video driver updates"

I leave the pictures to see the problem.
this problem always appears with steam in English or Spanish. I think that is independent of the language that has steam.
![update video drivers](https://f.cloud.github.com/assets/3372664/265694/af2880fe-8db9-11e2-8f93-a944bfd46fde.jpeg)
![restart after change the language](https://f.cloud.github.com/assets/3372664/265695/b71640ee-8db9-11e2-9531-4b19834026b1.jpeg)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue, please open a new issue report and contact your driver vendor.
