### ISSUE TITLE
The search bar is not where it should be in Steam-Spanish

### ISSUE THREAD

**Issue by obedlink** [ValveSoftware/steam-for-linux#2169]
I use steam in spanish lenguage and de search bar is not where it should be.
in steam in english the search bar is ok

see de picture

![steam-spanish](https://f.cloud.github.com/assets/3372664/265719/010ae41a-8dbb-11e2-8375-13687ecd6e8a.jpeg)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
