### ISSUE TITLE
Mouse/firing/animation in Day of Defeat

### ISSUE THREAD

**Issue by corax205** [ValveSoftware/steam-for-linux#2171]
1. Fast firing with Allied Rifleman gives sometimes a double shot.
2. Also Rifleman, not every mouse click gives a shot (yes I know there is a waiting time for the next shot)
3. Rifleman/Grenadier (maybe other to) have some reload animation issues if you click the firebutton  again, again and again.....
4. There are some issues with my custom mouseconfig (Firing left mouse button, walking forward right button).
   Reproduce:
   Tested with Rifleman/Grenadier 
   Walk forward and shoot (fast) at once. stop move. The Player will not stop.
   Not every time but often.

The Grenadier sometimes don't move.

**Comment by kisak-valve** [comment]
Hello @corax205, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
