### ISSUE TITLE
Wine games under Steam

### ISSUE THREAD

**Issue by Soulsuke** [ValveSoftware/steam-for-linux#2176]
I've tried to add a Wine game under Steam (namely Guild Wars 2), and I'm experiencing a weird issue, but first i'll add some details: the game is Guild Wars 2, it's running in wine's virtual desktop (1280x1024), and the mouse pointer is allowed to leave the game window (unless the right button is pressed, then it gets captured to move the camera).
Running the game via Steam has the following side effects:
- the mouse can't leave the game window anymore (unless i press shift+tab, but then...)
- steam overlay appears normally, but then won't just disappear
- the mouse won't reach the left edge of the game window, stopping about at 1cm away from it

I've also tried to add gnome-terminal as an application to run through Steam, and launching wine from there has the same results. Also, these popup:

ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

Reporting this from Debian Sid amd_64, running kernel 3.7c

Forgot to add this, my bad:

Informazioni sul processore:
    Produttore:  GenuineIntel
    Velocità:  2201 MHz
    Processori logici 8
    Processori fisici 4
    HyperThreading:  Supportato
    FCMOV:  Supportato
    SSE2:  Supportato
    SSE3:  Supportato
    SSSE3:  Supportato
    SSE4a:  Non supportato
    SSE41:  Supportato
    SSE42:  Supportato

Informazioni sulla rete:
    Velocità rete:  

Versione di Sistema Operativo:
    Debian GNU/Linux 7.0 (wheezy) (64 bit)
    Nome del kernel: Linux
    Versione del kernel: 3.7-trunk-amd64
    Produttore dell'X Server: The X.Org Foundation
    Versione dell'X Server: 11204000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-08

Scheda video:
    Driver:  NVIDIA Corporation GeForce GTX 560M/PCIe/SSE2

```
Versione driver: 4.3.0 NVIDIA 313.18
Intensità colore desktop: 24 bit per pixel
Frequenza di aggiornamento del monitor: 60 Hz
VendorID: 0x10de
DeviceID: 0x1251
Numero di monitor: 1
Numero di schede video logiche: 1
Risoluzione visualizzazione primaria: 1920 x 1080
Risoluzione desktop: 1920 x 1080
Dimensioni visualizzazione primaria: 15,04" x 8,46"  (17,24" diag)
                                        38,2cm x 21,5cm  (43,8cm diag)
Bus primario: PCI Express 16x
VRAM primaria: 1536 MB
Modalità MSAA supportate: 2x 4x 8x 16x 
```

Scheda audio:
    Periferica audio: IDT 92HD73C1X5

Memoria:
    RAM: 7989 Mb

Varie:
    Lingua IU:  Italiano
    LANG:  it_IT.utf8
    Microfono: Not set
    Spazio totale disponibile su disco rigido:  684017 Mb
    Blocco libero più ampio del disco rigido:  70251 Mb

Software installato:

Rapporti dei fallimenti recenti:

**Comment by kisak-valve** [comment]
Hello @Soulsuke, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
