### ISSUE TITLE
TF2 DLC not showing up

### ISSUE THREAD

**Issue by weltall** [ValveSoftware/steam-for-linux#2177]
On windows I've:
Team Fortress 2 - Premium DLC
Team Fortress 2 - Summer 2011 DLC
![steamcontent](https://f.cloud.github.com/assets/1127663/267075/8a79b204-8e55-11e2-8860-babc2673e1dd.png)

on linux it says I've no dlc.
![steamcontent](https://f.cloud.github.com/assets/1127663/267076/91562332-8e55-11e2-8cf2-1eff7814edc8.png)

**Comment by kisak-valve** [comment]
Closing pending feedback.
