### ISSUE TITLE
Super Hexagon: screen tearing

### ISSUE THREAD

**Issue by MrSchism** [ValveSoftware/steam-for-linux#2184]
System Information: https://gist.github.com/MrSchism/385f8ecd3425deeecd9f

I've been loving Super Hexagon since I got it in the bundle, but I noticed a little bit of screen-tearing on my netbook.  This does not change if I enable/disable the community.

It occurs exactly where xfpanel's boundary is.

Will upload video/screenshot when possible.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
