### ISSUE TITLE
Antialiasing decreases performance extensively

### ISSUE THREAD

**Issue by haikarainen** [ValveSoftware/steam-for-linux#2191]
This happens in all sourcegames I've tried, I think it is AMD-related. These titles includes:
TF2
HL2DM
CS: Source

It renders every game unusuable because of performance decreases.

2x XFX HD6870 in CrossFire
Catalyst 13.1 (revision 2 of catalyst-dkms in ArchLinux repos)
ArchLinux x86_64

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
