### ISSUE TITLE
Steam doesn't correctly detect direct rendering support and OpenGL extensions

### ISSUE THREAD

**Issue by baryluk** [ValveSoftware/steam-for-linux#2201]
I am running Ubuntu 12.04 amd64 chroot inside a Debian wheezy/unstable amd64.

I passed environment (mostly DISPLAY=:0), I have mounted /dev/shm and /tmp, etc, from outside of chroot to have access to X server. I installed fglrx 13.1 from Debian experimental both 64 and 32 bit versions, both in Debian and chrooted Ubuntu, so they match and work. After setting LD_LIBRARY_PATH or adding necessary paths to /etc/ld.so.conf, I have working OpenGL with direct rendering:

```
(precise_amd64)xxx@yhyh:~$ glxinfo | egrep -i 'direct rend|draw_buffers2|string'
direct rendering: Yes
server glx vendor string: ATI
server glx version string: 1.4
client glx vendor string: ATI
client glx version string: 1.4
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7900 Series 
OpenGL version string: 4.2.12002 Compatibility Profile Context 8.982.13
OpenGL shading language version string: 4.20
    GL_EXT_direct_state_access, GL_EXT_draw_buffers2, GL_EXT_draw_instanced, 

```

In fact this is exactly the same output I am getting outside of the chroot! glxgears work (4000+ fps)

I also successfully run Unigine Valey benchmark in it without ANY ISSUES with full speed.

The graphic card is Radeon 7970 (from gigabyte).

I can start steam without much issues, and it works. But it reports I do not have direct rendering for no apparent reasons:

```
(precise_amd64)xxx@yhyh:~$ steam
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
unlinked 0 orphaned pipes

(process:17562): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
[0321/003508:ERROR:bus.cc(261)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0321/003508:ERROR:bus.cc(261)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0321/003508:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/surface_linux.cpp (1743) : Assertion Failed: X context is not using direct rendering. Unfasten your seatbelt...

Assert( Assertion Failed: X context is not using direct rendering. Unfasten your seatbelt...
 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/surface_linux.cpp:1743
```

I think steam messes up with library search.

Or is it releated to 32-bit vs 64-bit libs? I installed both, and both should work I think.

```
(precise_amd64)xxx@yhyh:/$ cat /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf 
#/usr/lib/x86_64-linux-gnu/mesa
/usr/lib/x86_64-linux-gnu/fglrx
(precise_amd64)xxx@yhyh:/$ cat /etc/ld.so.conf.d/i386-linux-gnu_GL.conf 
#/usr/lib/i386-linux-gnu/mesa
/usr/lib/i386-linux-gnu/fglrx
```

(with ldconfig followed under root)

Any ideas why steam thinks my X doesn't support direct rendering? 

I tried running TF2, but it doesn't work. It ends with "Could not find required OpenGL entry point 'glColorMaskIndexedEXT'! Either your video card is unsupported, or your OpenGL driver needs to be updated."

**Comment by kisak-valve** [comment]
Hello @baryluk, if you are still experiencing this issue with an up to date system, please open a new issue report and we can investigate further.
