### ISSUE TITLE
Japanese Fonts

### ISSUE THREAD

**Issue by x414e** [ValveSoftware/steam-for-linux#2207]
I am using Linux Mint 14 64 bit, set to Japanese language and also Steam client is set to Japanese. The font in the steam client works fine and also in Counter Strike: Source the steam overlay font works fine. 

However the font for the Find/Create Server, Options, Quit menu seems to be missing. It is not showing missing font squares or the black texture, there is just no text at all.

This displays correctly when steam is set to English however when using Japanese it does not show. Clicking around randomly where the menu should be causes the game to quit, or show a popup with no fonts that I assume is asking me if I would like to quit.

I apologizes if this issue is already known.

プロセッサ情報：
    メーカー：GenuineIntel
    速度：2933Mhz
    2ロジカルプロセッサ
    2物理プロセッサ
    ハイパースレッド：使用不可
    FCMOV：使用可能
    SSE2：使用可能
    SSE3:使用可能
    SSSE3:使用可能
    SSE4a:使用不可
    SSE41:使用不可
    SSE42:使用不可

ネットワーク情報：
    回線速度：

オペレーティングシステムのバージョン：
    Linux Mint 14 Nadia（64 ビット）
    カーネル名: Linux
    カーネルバージョン: 3.5.0-17-generic
    X Server ベンダー: The X.Org Foundation
    X Server リリース: 11300000
    X ウィンドウマネージャ: Xfwm4
    Steam ランタイム バージョン: steam-runtime-release-i386_2013-03-08

ビデオカード：
    ドライバ：NVIDIA Corporation GeForce GTX 280/PCIe/SSE2

```
ドライバのバージョン：3.3.0 NVIDIA 310.14
デスクトップの色の解像度：24ビット/ピクセル
モニターのリフレッシュレート：59 Hz
メーカーID：0x10de
デバイスID：0x5e1
モニター数：1
論理ビデオカード数：1
メイン解像度：1920 x 1200
デスクトップ解像度：1920 x 1200
メイン表示サイズ：20.43 x 12.76 インチ（対角線 24.06 インチ）
                                        51.9cm x 32.4cm（対角線 61.1cm）
メインバス：PCI Express 16x
メインVRAM：1024 MB
サポートされているMSAAモード：2x 4x 8x 16x 
```

サウンドカード：
    オーディオデバイス：Analog Devices AD1988B

メモリ：
    メモリ：3953Mb

その他：
    UIの言語：日本語（Japanese）
    LANG:  ja_JP.UTF-8
    マイク：Not set
    HDDの合計空き容量：1873762Mb
    ハードディスクの最大空きブロック：1573092Mb

インストールされたソフト:

最新のエラー報告:

**Comment by kisak-valve** [comment]
Hello @x414e, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
