### ISSUE TITLE
Steam fails to start - Steam.sh fails at line 704

### ISSUE THREAD

**Issue by LinuxEnthusiast32** [ValveSoftware/steam-for-linux#2232]
error log is as follows - 

Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 9109 with name 0eBlobRegistryMutex_A1D04F7AF159F1CB1F57A4F9F2B11D60
removing stale semaphore last operated on by process 9109 with name 0eBlobRegistrySignal_A1D04F7AF159F1CB1F57A4F9F2B11D60
removing stale semaphore last operated on by process 9109 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 9109 with name 0eSteamEngineLock
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
[0327/093256:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Installing breakpad exception handler for appid(steam)/version(1363394289_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130327093256_1.dmp
/home/paul/.local/share/Steam/steam.sh: line 704:  9236 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-ea933646-9ca7-4877-ba64-56f012130327
- export TEXTDOMAIN=steam
- TEXTDOMAIN=steam
- export TEXTDOMAINDIR=/usr/share/locale
- TEXTDOMAINDIR=/usr/share/locale
- ARCHIVE_EXT=tar.xz
  ++ cd /home/paul/.local/share/Steam
  ++ echo /home/paul/.local/share/Steam
- STEAMROOT=/home/paul/.local/share/Steam
- STEAMDATA=/home/paul/.local/share/Steam
- '[' -z ']'
  ++ basename /home/paul/.local/share/Steam/steam.sh .sh
- STEAMEXE=steam
- '[' steam = steamcmd ']'
- cd /home/paul/.local/share/Steam
- MINIMUM_STEAMSCRIPT_VERSION=100020
- export SYSTEM_PATH=/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- SYSTEM_PATH=/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- export SYSTEM_LD_LIBRARY_PATH=
- SYSTEM_LD_LIBRARY_PATH=
  ++ uname
- UNAME=Linux
- '[' Linux == Linux ']'
  ++ detect_platform
  ++ platform=ubuntu12_32
  ++ case "$(detect_distro)-$(detect_release)" in
  +++ detect_distro
  +++ '[' -f /etc/lsb-release ']'
  +++ . /etc/lsb-release
  ++++ DISTRIB_ID=Ubuntu
  ++++ DISTRIB_RELEASE=13.04
  ++++ DISTRIB_CODENAME=raring
  ++++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  +++ echo Ubuntu
  +++ tr '[A-Z]' '[a-z]'
  +++ detect_release
  +++ '[' -f /etc/lsb-release ']'
  +++ . /etc/lsb-release
  ++++ DISTRIB_ID=Ubuntu
  ++++ DISTRIB_RELEASE=13.04
  ++++ DISTRIB_CODENAME=raring
  ++++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  +++ echo 13.04
  ++ echo ubuntu12_32
- PLATFORM=ubuntu12_32
  ++ echo ubuntu12_32
  ++ fgrep 32
- PLATFORM32=ubuntu12_32
  ++ echo ubuntu12_32
  ++ fgrep 64
- PLATFORM64=
- '[' -z ubuntu12_32 ']'
- '[' -z '' ']'
  ++ echo ubuntu12_32
  ++ sed s/32/64/
- PLATFORM64=ubuntu12_64
- STEAMCONFIG=/home/paul/.steam
- PIDFILE=/home/paul/.steam/steam.pid
- STEAMBIN32LINK=/home/paul/.steam/bin32
- STEAMBIN64LINK=/home/paul/.steam/bin64
- STEAMSDK32LINK=/home/paul/.steam/sdk32
- STEAMSDK64LINK=/home/paul/.steam/sdk64
- STEAMROOTLINK=/home/paul/.steam/root
  ++ detect_steamdatalink
  ++ '[' -f /home/paul/.local/share/Steam/steam_dev.cfg ']'
  +++ detect_package
  +++ case `detect_universe` in
  ++++ detect_universe
  ++++ test -f /home/paul/.local/share/Steam/Steam.cfg
  ++++ test -f /home/paul/.local/share/Steam/steam.cfg
  ++++ STEAMUNIVERSE=Public
  ++++ echo Public
  +++ STEAMPACKAGE=steam
  +++ echo steam
  ++ STEAMDATALINK=/home/paul/.steam/steam
  ++ echo /home/paul/.steam/steam
- STEAMDATALINK=/home/paul/.steam/steam
- STEAMSTARTING=/home/paul/.steam/starting
- '[' '!' -f /home/paul/.steam/steam.pid ']'
  ++ cat /home/paul/.steam/steam.pid
- kill -0 9236
- INITIAL_LAUNCH=true
- '[' '' = --reset ']'
- '[' true ']'
- show_license_agreement
- LICENSE=/home/paul/.local/share/Steam/steam_install_agreement.txt
- '[' '!' -f /home/paul/.steam/steam_install_agreement.txt ']'
- '[' -z /usr/bin/steam ']'
- '[' -f /usr/bin/steam ']'
- check_scriptversion /usr/bin/steam STEAMSCRIPT_VERSION 100020
- SCRIPT=/usr/bin/steam
- VERSION_TOKEN=STEAMSCRIPT_VERSION
- MINIMUM_VERSION=100020
  ++ detect_scriptversion /usr/bin/steam STEAMSCRIPT_VERSION
  +++ fgrep STEAMSCRIPT_VERSION= /usr/bin/steam
  ++ SCRIPT_VERSION='export STEAMSCRIPT_VERSION=100036'
  ++ [[ -n export STEAMSCRIPT_VERSION=100036 ]]
  ++ expr 'export STEAMSCRIPT_VERSION=100036' : '._=(._)'
- VERSION=100036
- [[ 100036 -lt 100020 ]]
- return 0
  ++ dirname /usr/bin/steam
  ++ detect_package
  ++ case `detect_universe` in
  +++ detect_universe
  +++ test -f /home/paul/.local/share/Steam/Steam.cfg
  +++ test -f /home/paul/.local/share/Steam/steam.cfg
  +++ STEAMUNIVERSE=Public
  +++ echo Public
  ++ STEAMPACKAGE=steam
  ++ echo steam
- STEAMDEPS=/usr/bin/steamdeps
- '[' -f /usr/bin/steamdeps -a -f /home/paul/.local/share/Steam/steamdeps.txt ']'
- /usr/bin/steamdeps /home/paul/.local/share/Steam/steamdeps.txt
- '[' '!' -e /home/paul/.steam ']'
- '[' /home/paul/.local/share/Steam '!=' /home/paul/.steam/root -a /home/paul/.local/share/Steam '!=' /home/paul/.steam/steam ']'
- rm -f /home/paul/.steam/bin32
- ln -s /home/paul/.local/share/Steam/ubuntu12_32 /home/paul/.steam/bin32
- rm -f /home/paul/.steam/bin64
- ln -s /home/paul/.local/share/Steam/ubuntu12_64 /home/paul/.steam/bin64
- rm -f /home/paul/.steam/sdk32
- ln -s /home/paul/.local/share/Steam/linux32 /home/paul/.steam/sdk32
- rm -f /home/paul/.steam/sdk64
- ln -s /home/paul/.local/share/Steam/linux64 /home/paul/.steam/sdk64
- rm -f /home/paul/.steam/root
- ln -s /home/paul/.local/share/Steam /home/paul/.steam/root
- '[' /home/paul/.steam/steam ']'
- rm -f /home/paul/.steam/steam
- ln -s /home/paul/.local/share/Steam /home/paul/.steam/steam
- rm -f /home/paul/.steampath
- ln -s /home/paul/.steam/bin32/steam /home/paul/.steampath
- rm -f /home/paul/.steampid
- ln -s /home/paul/.steam/steam.pid /home/paul/.steampid
- rm -f /home/paul/.steam/bin
- ln -s /home/paul/.steam/bin32 /home/paul/.steam/bin
  ++ distro_description
  +++ detect_distro
  +++ '[' -f /etc/lsb-release ']'
  +++ . /etc/lsb-release
  ++++ DISTRIB_ID=Ubuntu
  ++++ DISTRIB_RELEASE=13.04
  ++++ DISTRIB_CODENAME=raring
  ++++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  +++ echo Ubuntu
  +++ tr '[A-Z]' '[a-z]'
  +++ detect_release
  +++ '[' -f /etc/lsb-release ']'
  +++ . /etc/lsb-release
  ++++ DISTRIB_ID=Ubuntu
  ++++ DISTRIB_RELEASE=13.04
  ++++ DISTRIB_CODENAME=raring
  ++++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  +++ echo 13.04
  +++ detect_arch
  +++ case $(uname -m) in
  ++++ uname -m
  +++ echo 64-bit
  ++ echo 'ubuntu 13.04 64-bit'
- echo 'Running Steam on ubuntu 13.04 64-bit'
  Running Steam on ubuntu 13.04 64-bit
- '[' '' = debug ']'
- '[' '' = 1 ']'
- '[' '' = 0 ']'
- '[' -z '' ']'
- runtime_supported
- case "$(detect_distro)-$(detect_release)" in
  ++ detect_distro
  ++ '[' -f /etc/lsb-release ']'
  ++ . /etc/lsb-release
  +++ DISTRIB_ID=Ubuntu
  +++ DISTRIB_RELEASE=13.04
  +++ DISTRIB_CODENAME=raring
  +++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  ++ echo Ubuntu
  ++ tr '[A-Z]' '[a-z]'
  ++ detect_release
  ++ '[' -f /etc/lsb-release ']'
  ++ . /etc/lsb-release
  +++ DISTRIB_ID=Ubuntu
  +++ DISTRIB_RELEASE=13.04
  +++ DISTRIB_CODENAME=raring
  +++ DISTRIB_DESCRIPTION='Ubuntu Raring Ringtail (development branch)'
  ++ echo 13.04
- return 0
- echo 'STEAM_RUNTIME is enabled automatically'
  STEAM_RUNTIME is enabled automatically
- export STEAM_RUNTIME=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime
- STEAM_RUNTIME=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime
- '[' /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime -a /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime '!=' 0 ']'
- unpack_runtime
- has_runtime_archive
- for file in '"$STEAM_RUNTIME.$ARCHIVE_EXT".part*'
- '[' '!' -f /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz.part0 ']'
- '[' '!' -f /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime.checksum ']'
- return 0
- '[' -f /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/checksum ']'
- cmp /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime.checksum /home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/checksum
- return 0
- case $(uname -m) in
  ++ uname -m
- export PATH=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- PATH=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- export LD_LIBRARY_PATH=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
- LD_LIBRARY_PATH=/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
- export LD_LIBRARY_PATH=/home/paul/.local/share/Steam/ubuntu12_32:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
- LD_LIBRARY_PATH=/home/paul/.local/share/Steam/ubuntu12_32:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/paul/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
- check_shared_libraries
- '[' -f /home/paul/.local/share/Steam/ubuntu12_32/steamui.so ']'
  ++ get_missing_libraries /home/paul/.local/share/Steam/ubuntu12_32/steamui.so
  ++ ldd /home/paul/.local/share/Steam/ubuntu12_32/steamui.so
  ++ ldd /home/paul/.local/share/Steam/ubuntu12_32/steamui.so
  ++ grep '=>'
  ++ grep -v linux-gate
  ++ grep -v /
  ++ awk '{print $1}'
- MISSING_LIBRARIES=
- '[' '' '!=' '' ']'
- export SDL_VIDEO_X11_DGAMOUSE=0
- SDL_VIDEO_X11_DGAMOUSE=0
- ulimit -n 2048
- '[' Linux = Linux ']'
- :
- MAGIC_RESTART_EXITCODE=42
- STEAM_DEBUGGER=
- unset DEBUGGER
- '[' '' == gdb ']'
- '[' '' == cgdb ']'
- '[' '' == valgrind ']'
- /home/paul/.local/share/Steam/ubuntu12_32/steam
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  unlinked 0 orphaned pipes
  removing stale semaphore last operated on by process 9236 with name 0eBlobRegistryMutex_A1D04F7AF159F1CB1F57A4F9F2B11D60
  removing stale semaphore last operated on by process 9236 with name 0eBlobRegistrySignal_A1D04F7AF159F1CB1F57A4F9F2B11D60
  removing stale semaphore last operated on by process 9236 with name 0emSteamEngineInstance
  removing stale semaphore last operated on by process 9236 with name 0eSteamEngineLock
  Gtk-Message: Failed to load module "overlay-scrollbar"
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  [0327/093311:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  Installing breakpad exception handler for appid(steam)/version(1363394289_client)
  Uploading dump (out-of-process) [proxy '']
  /tmp/dumps/crash_20130327093312_1.dmp
  /home/paul/.local/share/Steam/steam.sh: line 704:  9366 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
- STATUS=139
- export PATH=/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- PATH=/usr/lib/lightdm/lightdm:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
- export LD_LIBRARY_PATH=
- LD_LIBRARY_PATH=
- '[' Linux = Linux ']'
- '[' true -a 139 -ne 42 -a -f /home/paul/.steam/starting -a -z '' -a -z '' ']'
- '[' 139 -eq 42 ']'
  Finished uploading minidump (out-of-process): success = yes
  response: CrashID=bp-43631824-5d90-4c5e-8d0a-163ab2130327

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
