### ISSUE TITLE
steamcmd crash

### ISSUE THREAD

**Issue by piegtas** [ValveSoftware/steam-for-linux#2235]
Running steamcmd - centos 5.9 clean install

1- downloaded the steamcmd client
2- copied libstdc++.so.6 to linux32 from other instalation (missing in downloaded client)
3- steamcmd auto update goes fine
4- after update, steam tries to run with error.
Loading Steam3...client_api.cpp (275) : Assertion Failed: ClientAPI_InitGlobalInstance: InternalAPI_Init_Internal failed.

OS: Centos 5.9
ldd (GNU libc) 2.5
Packages Installed:
compat-libstdc++-33-3.2.3-61
compat-libstdc++-296-2.96-138
libstdc++-4.1.2-54.el5
libstdc++44-devel-4.4.7-1.el5
glibc-common-2.5-107
glibc-2.5-107
glibc-devel-2.5-107
gcc-4.1.2-54.el5
compat-gcc-34-3.4.6-4.1
gcc44-4.4.7-1.el5
compat-gcc-34-c++-3.4.6-4.1
libgcc-4.1.2-54.el5
compat-libgcc-296-2.96-138

GDB output:

[root@localhost steamcmd]# ./steamcmd.sh
GNU gdb (GDB) CentOS (7.0.1-45.el5.centos)
Reading symbols from /opt/games/steamcmd/linux32/steamcmd...(no debugging symbols found)...done.
(gdb) r
Starting program: /opt/games/steamcmd/linux32/steamcmd
[Thread debugging using libthread_db enabled]
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[New Thread 0xb7df6b90 (LWP 2756)]
[  0%] Checking for available updates...
[New Thread 0xb7cf5b90 (LWP 2757)]
[  0%] Download complete.
[----] Verifying installation...
[Thread 0xb7df6b90 (LWP 2756) exited]
[New Thread 0xb7b32b90 (LWP 2758)]
[New Thread 0xb7a31b90 (LWP 2759)]
[Thread 0xb7a31b90 (LWP 2759) exited]
[New Thread 0xb6f2fb90 (LWP 2760)]
[New Thread 0xb6e2eb90 (LWP 2761)]
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam3...client_api.cpp (275) : Assertion Failed: ClientAPI_InitGlobalInstance: InternalAPI_Init_Internal failed.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x007c5355 in AssertMsgImplementation () from /opt/games/steamcmd/linux32/libtier0_s.so
(gdb) bt
#0  0x007c5355 in AssertMsgImplementation () from /opt/games/steamcmd/linux32/libtier0_s.so
#1  0x0071ee23 in Q_strncat () from /opt/games/steamcmd/linux32/steamconsole.so
#2  0x0071f274 in Q_strncat () from /opt/games/steamcmd/linux32/steamconsole.so
#3  0x007419c8 in SteamDllMainEx () from /opt/games/steamcmd/linux32/steamconsole.so
#4  0x0805f992 in RunSteam(int, char**, bool, bool) ()
#5  0x080607ca in main ()

(gdb)

**Comment by kisak-valve** [comment]
Hello @piegtas, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
