### ISSUE TITLE
Adding keys of games/apps which are not available on Linux. [Feature request]

### ISSUE THREAD

**Issue by xentropy** [ValveSoftware/steam-for-linux#2248]
Adding keys of games and applications which are not available on the Linux platform has been possible for quite a while. This has changed now.

Please (re-)add this feature. 
While I can imagine why this option has been removed, to avoid keys being "burned" on non-supported OS installations (?), it turned out really practical to me as I mainly use Linux but also have a Windows installation of Steam.

I'd suggest telling the user that the game/app is not available on the current platform (maybe listing on which it currently is) and providing a checkbox to "force" adding the key.

Thanks for looking into this!

**Comment by kisak-valve** [comment]
Closing as this was fixed some time ago.
