### ISSUE TITLE
TeamFortress hangs on startup (blackscreen)

### ISSUE THREAD

**Issue by folone** [ValveSoftware/steam-for-linux#2249]
It starts, plays some kind of a sound for maybe a second, and then hangs. Here's the output of the client: https://gist.github.com/folone/b0f6d4a6057b58cd73e7. I've skimmed through the [closed](https://github.com/ValveSoftware/steam-for-linux/issues?labels=Team+Fortress+2&page=1&state=closed) and [open](https://github.com/ValveSoftware/steam-for-linux/issues?labels=Team+Fortress+2&page=1&state=open) issues, but did not notice any similar tickets.
My config is:
- Arch Linux (+ xmonad), thinkpad x220:
- Intel® Core™ i5-2520M (2.5GHz, 3MB L3 cache)
- 16gb RAM
- Intel HD Graphics 3000

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
