### ISSUE TITLE
Falling of models under textures (Bug Counter-Strike)

### ISSUE THREAD

**Issue by UniverseTech** [ValveSoftware/steam-for-linux#2252]
![1](https://f.cloud.github.com/assets/4023437/322862/213ede30-9a81-11e2-9ed9-90430c8084f2.png)
![2](https://f.cloud.github.com/assets/4023437/322864/3b539478-9a81-11e2-8ea7-caf7686de870.png)

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/halflife/issues/76 / https://github.com/ValveSoftware/halflife/issues/907.
