### ISSUE TITLE
Strings too long in german version

### ISSUE THREAD

**Issue by pmk1c** [ValveSoftware/steam-for-linux#2256]
In the Steam Cloud section of the settings, the strings in the german version are too long. You can see it on the Screenshot.
![Bildschirmfoto vom 2013-04-02 09:51:13](https://f.cloud.github.com/assets/2379198/327212/624984cc-9b6a-11e2-8ccc-a5b1ed55d6c3.png)

**Comment by kisak-valve** [comment]
Closing as the settings layout was changed a fair while ago and the referenced text overlap no longer occurs.
