### ISSUE TITLE
Team Fortress 2 fails to start -- hl2.sh not found.

### ISSUE THREAD

**Issue by imba3r** [ValveSoftware/steam-for-linux#2267]
I can't launch Team Fortress 2 because my Steam account name has a dollar sign ($) in it. It seems like that dollar sign is not properly escaped in a certain launch script used by steam. Below is the error shown when I launch Steam from the command line:

`/bin/sh: /home/<user>/.local/share/Steam/SteamApps/<Steam account>/Team Fortress 2/hl2.sh: No such file or directory`

I removed my real names, instead I provide an example using an arbitrary Steam account name: `nickname$123`.

The real call should be:
`/home/<user>/.local/share/Steam/SteamApps/nickname$123/Team Fortress 2/hl2.sh`
but instead this gets called, resulting in an error:
`/home/<user>/.local/share/Steam/SteamApps/nickname/Team Fortress 2/hl2.sh`

I tried to provide a symlink `nickname` which links to `nickname$123`, but that doesn't work. However if I rename the directory to `nickname` Team Fortress 2 works.

This issue also occurs when I try to start Counter Strike: Source. Day of Defeat: Source and HL2: Deathmatch (both Source games) on the other hand work.

**Comment by kisak-valve** [comment]
Hello @imba3r, @wantkaos, are either of you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
