### ISSUE TITLE
Team Fortress 2 - Medic übercharge graphics and sounds persists through death

### ISSUE THREAD

**Issue by Zeraxxus** [ValveSoftware/steam-for-linux#2276]
Medic übercharge graphics and sounds persists through death and class change.
It happens when I die with 100% übercharge, either activated or not. 
The übercharge game mechanics however does NOT persist through death, but just the visuals and sounds.

I always play 2Fort on instant respawn servers, so I only know that it is reproducible there.

I use Ubuntu 12.10 64-bit with Nvidia 310 experimental drivers on a GeForce 460GTX

![2013-04-05_00002](https://f.cloud.github.com/assets/948880/346445/7f1e6e90-9e45-11e2-8c11-9236c7ef18ac.jpg)
![2013-04-06_00001](https://f.cloud.github.com/assets/948880/346476/bf1f4414-9e46-11e2-9a3b-54cfad0bfdd0.jpg)

**Comment by kisak-valve** [comment]
Hello, if anyone is still experiencing this issue with an up to date TF2 install, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
