### ISSUE TITLE
gl_vsync does not work

### ISSUE THREAD

**Issue by ostrolucky** [ValveSoftware/steam-for-linux#2279]
I can't disable vsync. Neither gl_vsync 0 or unchecking option "Wait for vertical sync" disables vsync. I have vblank_mode set to 0. Tested in Counter-Strike 1.6.

System info:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2400 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11400000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2

```
Driver Version:  2.1 Mesa 9.1.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x8086
DeviceID:  0x46
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 11,93" x 7,48"  (14,06" diag)
                                        30,3cm x 19,0cm  (35,7cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel IbexPeak HDMI

Memory:
    RAM:  3815 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  47491 Mb
    Largest Free Hard Disk Block:  10266 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
