### ISSUE TITLE
Source engine games fail to start on Xinerama

### ISSUE THREAD

**Issue by Spanguole** [ValveSoftware/steam-for-linux#2285]
If I have Xinerama enabled, when I try to launch any of the Source engine games [TF2; HL2 DM; CSS], they all crash on startup with this error:

![SS_2013_04_07_23_30_50](https://f.cloud.github.com/assets/4086651/349430/30669c62-9fc3-11e2-92d7-629c153863a3.png)

the terminal output says [taken from a TF2 crash]:

<pre><code>Game update: AppID 440 "Team Fortress 2", ProcID 4950, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Xlib:  extension "RANDR" missing on display ":0.0".
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
PROBLEM: You appear to have OpenGL 0.0.0, but we need at least 2.0.0!
Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully</code></pre>

When I turn Xinerama off & disable my second monitor, all those games work fine.

WITH Xinerama ON, most other games work fine (Killing Floor, Amnesia: The Dark Descent, for example). Nvidia driver's sanity check indicates the driver is fine. glxgear indicates only a small performance drop. Thus, I do not think the driver is to blame.

System information [from steam]:

<pre><code>
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3500 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-26-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Marco
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

    Driver Version:  4.3.0 NVIDIA 313.18
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x1201
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 47.40" x 13.50"  (49.25" diag)
                                            120.4cm x 34.3cm  (125.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC889
    
Memory:
    RAM:  7903 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  398203 Mb
    Largest Free Hard Disk Block:  312340 Mb
    
Installed software:
    
Recent Failure Reports:</code></pre>

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue with an up to date system, please open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
