### ISSUE TITLE
Counter Strike: Source and HL2DM freeze up my system after a short (random) amount of playtime

### ISSUE THREAD

**Issue by waaaaargh** [ValveSoftware/steam-for-linux#2290]
## Problem Description

So here is my problem: Everytime I play CS:S or HL2DM, after a short amount of time (3-10 minutes) my system freezes up completely. I can't use my mouse and keyboard any more, the screen freezes at the last rendered frame and the sound gets stuck in a short loop. Voice Communication programs such as mumble and music players (audacious and mpd in my case) still work. Also I am still able to ping my machine and ssh into it, but i can't shut it down gracefully, as the shutdown command just doesn't do anything (including exit). Unfortunately, there is no debug output in the kernel log.

Another Arch User seems to experience the exact same problem: https://bbs.archlinux.org/viewtopic.php?id=159667

I think it's a very obscure issue with the AMD Graphics driver for the Radeon HD 7770.
## OS

```
    Linux dashy 3.8.4-1-ARCH #1 SMP PREEMPT Wed Mar 20 22:10:25 CET 2013 x86_64 GNU/Linux
```
## Hardware Info Output

```
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7700 Series 

    Driver Version:  4.2.12173 Compatibility Profile Context 9.012
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x683f
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                            51,8cm x 32,4cm  (61,0cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  16051 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  195778 Mb
    Largest Free Hard Disk Block:  69477 Mb

Installed software:

Recent Failure Reports:
    Mon Apr  8 20:59:16 2013 GMT: file ''/tmp/dumps/assert_20130408225907_1.dmp'', upload yes: ''CrashID=bp-6fd4da98-3dc5-47b2-9906-a9c5f2130408
    ''
```

**Comment by jamiesonbecker** [comment]
Don't overlook simple hardware issues.. I had a lot of issues with certain games w/ nvidia drivers, and then I opened up the temperature monitor and left it running on another screen while I played. Surprisingly, even though that nvidia card (GTX 670, hardly a weak card) didn't seem have any issues on most of my games (and it wasn't overclocked or anything and the fan seemed to be working), the temperature spiked and froze my system. Replacing it with a different card (GTX 920, only slightly better but two big fans) fixed everything.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.

**Comment by jamiesonbecker** [comment]
@kisak-valve well, you just closed a bug that valve never even responded to back in 2013, so you may never know if the original reporter thought it was still relevant. ;)

**Comment by kisak-valve** [comment]
Hello @jamiesonbecker, unfortunately, there may be a fair amount of issues like this one in the steam-for-linux issue tracker. Specific to this issue report, fglrx has been discontinued by AMD in favor of mesa and AMDGPU-PRO. No vendor fixes are expected for a discontinued driver.

If this is still an issue with one of those drivers on an up to date system, then a new investigation needs to be done and for these games, and that should be done in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker or by contacting the driver vendor.

**Comment by jamiesonbecker** [comment]
@kisak-valve sounds good! thank you :)
