### ISSUE TITLE
Team Fortress 2 stops responding on loading screen

### ISSUE THREAD

**Issue by kerrickstaley** [ValveSoftware/steam-for-linux#2294]
When TF2 is loading a map, it apparently stops processing GUI events for several seconds, causing this error dialog:

```
“Team Fortress 2 - OpenGL” is not responding.

You may choose to wait a short while for it to continue
or force the application to quit entirely.

                                 [Force Quit]  [Wait]
```

If you click "Wait", the map eventually loads successfully, but the pop-up is annoying.

**Comment by Polochamps** [comment]
I had the same error you mentioned but only appears when launching the game.
I fixed it by removing the "-novid" in launch options

on 
__GL_THREADED_OPTIMIZATIONS=1 %command% -novid

into
__GL_THREADED_OPTIMIZATIONS=1 %command%

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by hhiru** [comment]
I'm having the same problem. Using Ubuntu Gnome and the -novid launch option

**Comment by kisak-valve** [comment]
Hello @hhiru, thanks for testing. I've gone ahead and transferred your comment to the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. Let's track the -novid issue at https://github.com/ValveSoftware/Source-1-Games/issues/2280.
