### ISSUE TITLE
"Warning: Could not find '/tmp/<random string here>', starting '/bin/bash' instead." when gnome-terminal is not installed

### ISSUE THREAD

**Issue by bladerunner92** [ValveSoftware/steam-for-linux#2298]
I'm a Linux Mint 14 KDE (x64) user. I switched from the cinnamon release a couple of days ago, and Steam has been constantly pestering me by launching a Konsole (terminal) when starting up, spewing the text above in bright red. Every time that file mentioned (with a random/mangled name) in /tmp exists, and has 700 permissions with me as the owner. Since that did not happen in the Cinnamon edition, I tried fixing it by installing gnome-terminal, and sure enough it stopped opening that screen every time.

Even though it's not a problem anymore, I still don't like the fact that I need 30MB worth of GNOME stuff so that steam could start normally (yeah, it doesn't start until you close the terminal).

Steps to reproduce this:
1. Grab a Linux Mint 14 KDE without gnome-terminal installed.
2. Run steam

Now, the above I haven't tested on any other machines since I've no access, but I'd be grateful if anyone else can give it a go. In my case, I installed Steam on top of my pre-existing one from the Cinnamon edition.

**Comment by kisak-valve** [comment]
Hello @bladerunner92, are you still experiencing this issue with an up to date system?

**Comment by bladerunner92** [comment]
@kisak-valve, I'm on a completely different system now, so the comparison doesn't seem all that valid, but no, I'm not experiencing it. I don't have gnome-terminal installed and I am not getting any pop-ups or similar error messages.

**Comment by kisak-valve** [comment]
Thanks for retesting @bladerunner92, closing.
