### ISSUE TITLE
Defcon Steam authentication fails

### ISSUE THREAD

**Issue by theli-ua** [ValveSoftware/steam-for-linux#2304]
Defcon version: 1.62 STEAM
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2201 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "NAME=Gentoo" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.3-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11400000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile 

```
Driver Version:  2.1 Mesa 9.0.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID Not Detected
DeviceID Not Detected
Number of Monitors:  2
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3520 x 1080
Primary Display Size: 20,51" x 11,54"  (23,50" diag)
                                        52,1cm x 29,3cm  (59,7cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: 

Memory:
    RAM:  7900 Mb

Miscellaneous:
    UI Language:  English
    LANG:  uk_UA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  119803 Mb
    Largest Free Hard Disk Block:  2752 Mb

**Comment by kisak-valve** [comment]
Hello @theli-ua, are you still experiencing this issue with an up to date system?

**Comment by theli-ua** [comment]
@kisak-valve I have absolutely no memory of this issues but I set a reminder to retest tonight.

**Comment by theli-ua** [comment]
I was unable to reproduce this anymore.
