### ISSUE TITLE
[Linux] Half-Lfe and Counter-Strike 1.6 beta status reset when restarting Steam

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2309]
I am having a (minor) issue with Steam : whenever I restart Steam, the beta status of both Half-Life and Counter-Strike 1.6 are being reset to "NONE: Opt out[...]". (These two are my only games where I select to participate in the Beta). 

I am running on Debian Wheezy x64 (uname -a output : Linux  3.2.0-4-amd64 #1 SMP Debian 3.2.41-2 x86_64 GNU/Linux)

**Comment by kisak-valve** [comment]
Closing as the user has become a ghost. If experiences this issue, please open a new issue report.
