### ISSUE TITLE
TF2 vs HL2:DM: Team Fortress 2 Drastic FPS Drop - ati legacy drivers (Mobility HD 3470), ati 13.1

### ISSUE THREAD

**Issue by kbarter-cz** [ValveSoftware/steam-for-linux#2319]
Hello,

I'm sorry if this issue was solved before, but I need to report drastic FPS drop in Team Fortress 2 (I presume orange box engine).

System is installed from Ubuntu 12.10 minimal, LXDE, openbox, because game was unplayable on other tested environments such as Unity, Gnome Shell, KDE...

I'm running TF2 on smallest possible settings (all to low or none), graphic card: Mobility Radeon HD 3470, resolution of game: 640x480. To clarify this, same card in windows performs without any FPS drop.

For easiness, I'm reporting what happens, average values:
No players: fps 120
2 players: fps 60
4 or more: fps 15

In contrast to Half-life 2 Deathmatch, HL2 DM has no significant problems. HL2DM runs even on my maximum resolution (1280x800) with very small jitters, so I think there is problem in orange box engine. I am aware that also version of the driver can cause problems. Version of fglrx-legacy is 13.1, installed from makson96/fglrx

System specifications
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2001 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-26-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11204000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  ATI Technologies Inc. ATI Mobility Radeon HD 3400 Series

```
Driver Version:  3.3.11672 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x95c4
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 2960 x 1050
Primary Display Size: 13,03" x 8,15"  (15,35" diag)
                                        33,1cm x 20,7cm  (39,0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC268

Memory:
    RAM:  3006 Mb

Miscellaneous:
    UI Language:  English
    LANG:  cs_CZ.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  181516 Mb
    Largest Free Hard Disk Block:  148957 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @kbarter-cz, this issue was most likely vram pressure related. Source 1 games on linux uses ToGL internally, which translates directx to opengl on the fly and requires more vram than using directx directly. Although not supported, your best chance for a good experience on this hardware would be to run mesa and wine with gallium-nine support.
