### ISSUE TITLE
problem with steelseries mice

### ISSUE THREAD

**Issue by m4son** [ValveSoftware/steam-for-linux#2324]
Im having problems with my mouse, Steelseries Sensei Raw, it does not work with any of the games for linux. I can see the pointer on the screen, but none of the buttons work.

Im using LinuxMInt 64bit.

**Comment by kisak-valve** [comment]
Hello @m4son, are you still experiencing this issue with an up to date system?

**Comment by m4son** [comment]
It is all good, i am not having any problems.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
