### ISSUE TITLE
DoD Crashing at random with hl.sh: line 38: 14174 Segmentation fault

### ISSUE THREAD

**Issue by jrewolinski** [ValveSoftware/steam-for-linux#2327]
I'll just be playing along just fine and my game will disappear.  stdout.txt file in the /var/dumps folder shows this seg fault error.
<code>
/home/jeff/.local/share/Steam/SteamApps/common/Half-Life/hl.sh: line 38: 14174 Segmentation fault      ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
Game removed: AppID 30 "Day of Defeat", ProcID 14174
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
</code>
Not sure if it's related to drivers or what.
If there's anything I can do to better troubleshoot, let me know.
Thanks.

Specs:
Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-40-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Muffin
    Steam Runtime Version:  steam-runtime-release-i386_2013-03-25

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 5800 Series 

```
Driver Version:  4.2.12173 Compatibility Profile Context 12.10.17
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6899
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18.66" x 11.65"  (21.97" diag)
                                        47.4cm x 29.6cm  (55.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  223937 Mb
    Largest Free Hard Disk Block:  206985 Mb

Installed software:

Recent Failure Reports:
    Sun Apr 14 22:10:00 2013 GMT: file ''/tmp/dumps/assert_20130414141000_1.dmp'', upload yes: ''CrashID=bp-942e3fe0-08c9-42b8-9697-5c46a2130414
    ''
    Sun Apr 14 22:24:47 2013 GMT: file ''/tmp/dumps/assert_20130414142447_1.dmp'', upload yes: ''CrashID=bp-97975c05-e4c7-4a06-a9e3-c63a62130414
    ''
    Sun Apr 14 22:24:47 2013 GMT: file ''/tmp/dumps/assert_20130414142447_1.dmp'', upload yes: ''CrashID=bp-88b03d3d-6105-47f1-bf09-d44712130414
    ''

**Comment by theapplicant** [comment]
I returned to dod after 5 years and now I have a Mac. It happens to me exactly what is discussed here. I have noticed that usually spend more on large maps that small. Do you think correct this bug? It's a shame because you can not play like that.

Is there a command that can be activated and to eliminate or reduce the potential for this problem to happen?

Thanks and regards.

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/halflife/issues/1447.
