### ISSUE TITLE
CSS intel gm45 good graphic but dont work

### ISSUE THREAD

**Issue by dimazanyat** [ValveSoftware/steam-for-linux#2328]
`[0417/090425:ERROR:resource_bundle.cc(411)] Failed to load /home/user/Steam/SteamApps/common/Counter-Strike Source/cef_gtk.pak
Some features may not be available.`

what here can make?

what this /Steam/SteamApps/common/Counter-Strike Source/cef_gtk.pak? i em dont have this file
only for files

hl2.sh
hl2_linux
steam_appid.txt
thirdpartylegalnotices.doc

thx

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If this is still an issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
