### ISSUE TITLE
Trine 2 does not start after Mesa Update in Kubuntu 13.04

### ISSUE THREAD

**Issue by obedlink** [ValveSoftware/steam-for-linux#2330]
updates after the 04/18, which updates Mesa to version 9.1.1 Trine 2 does not start, shows the configuration window. To start the game does not show the "Trine 2 " logo and then closes.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3301 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BARTS

```
Driver Version:  3.0 Mesa 9.1.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6738
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,87" x 11,81"  (23,98" diag)
                                        53,0cm x 30,0cm  (60,9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: 20K2

Memory:
    RAM:  7954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  es_GT.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  57992 Mb
    Largest Free Hard Disk Block:  18796 Mb

Installed software:

Recent Failure Reports:

Konsole Log:

obed@kubuntu:~$ steam //35720
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
unlinked 0 orphaned pipes
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
[0420/103653:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Installing breakpad exception handler for appid(steam)/version(1366403468_client)

(steam:4289): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(steam:4289): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
`menu_proxy_module_load': /home/obed/.local/share/Steam/ubuntu12_32/steam: undefined symbol: menu_proxy_module_load

(steam:4289): Gtk-WARNING **: Failed to load type module: (null)

Installing breakpad exception handler for appid(steam)/version(1366403468_client)
Adding license for package 0
Adding license for package 305
Adding license for package 1451
Adding license for package 1676
Adding license for package 2035
Adding license for package 2300
Adding license for package 2487
Adding license for package 4077
Adding license for package 4314
Adding license for package 6098
Adding license for package 7658
Adding license for package 8186
Adding license for package 8253
Adding license for package 11010
Adding license for package 11072
Adding license for package 11746
Adding license for package 11747
Adding license for package 11984
Adding license for package 12517
Adding license for package 13054
Adding license for package 13093
Adding license for package 13756
Adding license for package 16531
Adding license for package 16549
Adding license for package 18181
Adding license for package 18876
Adding license for package 27162
roaming config store loaded successfully - 4226 bytes.
migrating temporary roaming config store
ExecCommandLine: "/home/obed/.local/share/Steam/ubuntu12_32/steam //35720"
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Generating new string page texture 69: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 70: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 71: 32x256, total string texture memory is 475,14 KB
Generating new string page texture 72: 64x256, total string texture memory is 540,67 KB
Attempting to use a Windows only path root on non-Windows platform for game 221810
Attempting to use a Windows only path root on non-Windows platform for game 221810
Attempting to use a Windows only path root on non-Windows platform for game 221810
System startup time: 8,26 seconds
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/obed/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/obed/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 86: 256x256, total string texture memory is 393,22 KB
Generating new string page texture 87: 128x256, total string texture memory is 671,74 KB
Generating new string page texture 92: 256x256, total string texture memory is 933,89 KB
Failed to load installscript /home/obed/.local/share/Steam/SteamApps/common/Trine 2/installscript.vdf
Game update: AppID 35720 "Trine 2", ProcID 4402, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Game removed: AppID 35720 "Trine 2", ProcID 4402 

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed
`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

`menu_proxy_module_load': ./bin/trine2_linux_launcher_32bit: undefined symbol: menu_proxy_module_load

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Failed to load type module: (null)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4289): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: GModule (/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(trine2_linux_launcher_32bit:4406): Gtk-WARNING **: Loading IM context type 'ibus' failed
Generating new string page texture 125: 128x256, total string texture memory is 1,06 MB
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Game update: AppID 35720 "", ProcID 4419, IP 0.0.0.0:0
Setting breakpad minidump AppID = 35720
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197990360023 [API loaded no]
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
ALSA lib pcm_asym.c:106:(_snd_pcm_asym_open) capture slave is not defined
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.modem.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.modem.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.modem.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.SB-XFi.pcm.modem.0:CARD=0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM phoneline
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Game removed: AppID 35720 "", ProcID 4419 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
unlinked 2 orphaned pipes
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 169440 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 1 multi object alertable sleeps
[2013-04-20 10:36:53] Startup - updater built Apr 19 2013 12:00:04
[2013-04-20 10:36:53] Opted in to client beta 'publicbeta' via beta file
[2013-04-20 10:36:53] Verifying installation...
[2013-04-20 10:36:53] Verification complete
Shutting down. . .
[2013-04-20 10:37:44] Shutdown
obed@kubuntu:~$

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date version of mesa, please contact the driver vendor.
