### ISSUE TITLE
Steam logging me out of my system and/or killing lightdm upon steam launch.

### ISSUE THREAD

**Issue by Benguin** [ValveSoftware/steam-for-linux#2333]
Steam was working fine for me yesterday, and I'm not sure what changed (I think maybe there was an update,) but today when I tried to open it, it logged me out of my computer, taking me back to the login screen, and then the _second_ time I tried to open it, it killed lightdm and left me at the commandline.

this is what steam gives me when I run it in a terminal (had to send output to a file, since it kills the display:)

```
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1366403468_client)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 55 requests (55 known processed) with 0 events remaining.
[2013-04-22 08:09:41] Startup
[2013-04-22 08:09:41] Opted in to client beta 'publicbeta' via beta file
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  137 (NV-GLX)
Minor opcode of failed request:  4
Resource id in failed request:  0x5000002
Serial number of failed request:  43
xerror_handler: X failed, continuing
Installing bootstrap /home/ben/.steamLibrary/bootstrap.tar.xz
```

I tried rebooting, but no dice. 

I should also say that the only other program that has done something like this before, for me, was the linux version of Dungeon Defenders (not downloaded via steam,) and that was caused by me not having a screensaver installed, which I worked around somehow by (I think,) just putting a script that does nothing, where the screensaver should be.

**Comment by aydintd** [comment]
I am also experienced this issue in OpenSUSE 13.1 after upgrading x packages of my system.

All i need to do to solve this issue, i ran my Nvidia Driver installer which compatible to my device, and the installer script recreated the nvidia X files instead of X server default configuration files which replaced after the upgrade. Now all seems ok and works like a charm.
