### ISSUE TITLE
Wrong joystick buttons in games

### ISSUE THREAD

**Issue by nullguy** [ValveSoftware/steam-for-linux#2342]
I have PS3-like controller and i would like to use xbox 360 button setup on it.
All steam games that support joystick recognize it as xbox joystick, but the main button configuration is wrong.  For examle, pressing Y button returns A, pressing X returns Y, pressing A returns X, and only B button is working properly.
I tried using jstest and jscal, the buttons appear to be remapped in some applications, but games still use old configuration, and that is very unconfortable.(Imagine, game asks you to press A, but you have to press X instead)
I'm on Ubuntu 12.10. 
Games affected: Bastion, Shank 2, Super Meat Boy, haven't tried anything else.

**Comment by kisak-valve** [comment]
Hello @nullguy, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
