### ISSUE TITLE
Some mild quirks with TF2 controller support

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/steam-for-linux#2349]
Hey Valve. I really appreciate the work that has been done lately with making Team Fortress 2 controller-friendly. However, there are a few things that get in the way of a seamless experience. These bugs were found on a wireless Xbox 360 controller.

-When I am notified of item drops in the main menu, I'm unable to bring up the screen which shows what I got.
-Every time I launch TF2, controller input is not detected in the menus until I open a sub-menu (such as the options menu or the server browser).
-At times, the controller will get caught in a loop of vibration during a match. This issue persists until I re-insert the battery pack.

And here's my system info.
``` Processor Information:
    Vendor:  GenuineIntel
    Speed: 3392 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-29-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 319.12
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1201
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15963 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  460118 Mb
    Largest Free Hard Disk Block:  391918 Mb

Installed software:

Recent Failure Reports:
    Sun Apr 28 08:26:35 2013 GMT: file ''/tmp/dumps/crash_20130428042624_1.dmp'', upload yes: ''CrashID=bp-183483f4-c33f-4726-80f2-9028e2130428
    ''
    Sun Apr 28 08:26:38 2013 GMT: file ''/tmp/dumps/assert_20130428042635_1.dmp'', upload yes: ''CrashID=bp-de1b123f-d2e7-4fee-8d53-36e612130428
    ''
    Sun Apr 28 08:28:12 2013 GMT: file ''/tmp/dumps/assert_20130428042809_2.dmp'', upload yes: ''CrashID=bp-47a03428-5204-44eb-800b-b26572130428
    ''
    Sun Apr 28 08:28:38 2013 GMT: file ''/tmp/dumps/assert_20130428042836_3.dmp'', upload yes: ''CrashID=bp-3322aff6-0efe-4142-b133-5fb7e2130428
    ''
    Sun Apr 28 08:29:23 2013 GMT: file ''/tmp/dumps/assert_20130428042922_4.dmp'', upload yes: ''CrashID=bp-6913c90a-8508-48b6-b413-da0b12130428
    ''
    Sun Apr 28 08:36:00 2013 GMT: file ''/tmp/dumps/assert_20130428043550_5.dmp'', upload yes: ''CrashID=bp-3e66fd0e-2a22-411f-977f-698522130428
    ''

```
```

**Comment by kisak-valve** [comment]
Hello @PyGuy95, if you are still experiencing issues with controllers in TF2, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker with one issue per issue report.
