### ISSUE TITLE
TF2 MVM graphics artifacts

### ISSUE THREAD

**Issue by RodionovAlexey** [ValveSoftware/steam-for-linux#2354]
I have this strange graphics artifacts only on MVM

This is with motion blur enabled - picture is too bright and blurred

![mb](https://f.cloud.github.com/assets/3327805/448860/f7442fe0-b25e-11e2-9429-32f77b448093.jpg)

This is without motion blur. In game it looks like new frames are added to old ones

![no_mb](https://f.cloud.github.com/assets/3327805/448858/d3627212-b25e-11e2-8e3f-60d9a0bb39f2.jpg)

My system info:

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2800 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.9.0-030900-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6900 Series   

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x671f
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23,50" x 13,23"  (26,97" diag)
                                        59,7cm x 33,6cm  (68,5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7982 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  323930 Mb
    Largest Free Hard Disk Block:  206470 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @RodionovAlexey, I'm going to close this issue report because vendor support for fglrx has been discontinued. If you are still experiencing this issue with an up to date system and mesa, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
