### ISSUE TITLE
Steam does not set min-size hints on main window

### ISSUE THREAD

**Issue by magcius** [ValveSoftware/steam-for-linux#2359]
Steam's main window doesn't set min-size hints, instead opting to send a ConfigureRequest to the window manager if it goes below an acceptable size. The window manager, however, is free to ignore the ConfigureRequest and opt to send a synthetic ConfigureNotify for the old size. Steam does not adapt its display to the ConfigureNotify, and instead renders assuming the window manager will resize the window.

This can happen in tiling window managers, or window managers like gnome-shell that implement Windows 7-like side-by-side tiling.

While Steam should not assume the ConfigureRequest will be acknowledged by the WM and respond appropriately to the ConfigureNotify anyway, an easy solution is to set WM_NORMAL_HINTS with an appropriate min_width/min_height. This will signal to the WM that it should never resize the window below this size, ever.

**Comment by kisak-valve** [comment]
Closing in favor of #807.
