### ISSUE TITLE
Portal - Locked out of my save file after falling in acid in Test Chamber 18

### ISSUE THREAD

**Issue by PyGuy95** [ValveSoftware/steam-for-linux#2364]
In Test Chamber 18, I fell into the green acid and the game froze into a black screen. When I re-launch, I am unable to open my save files. Seems like a pretty harsh death consequence, eh? No worries, though. I understand it's a Beta. Here's my system info:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3391 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-41-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1201
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1023 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  15962 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  453413 Mb
    Largest Free Hard Disk Block:  381174 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @PyGuy95, if you encounter this issue again with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
