### ISSUE TITLE
Crash with  Segmentation fault when joining to game in Counter Strike Source

### ISSUE THREAD

**Issue by qwazer** [ValveSoftware/steam-for-linux#2376]
System Info https://gist.github.com/qwazer/5510743
Log with error

3416 Segmentation fault ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

 https://gist.github.com/qwazer/5510772

Steps to reproduce: create local game or join to any remote game

**Comment by kisak-valve** [comment]
Hello @qwazer, your system information indicates that llvmpipe was being used, which is the faster software opengl implementation in mesa. Source 1 games are not expected to work with llvmpipe, and even if they do, there is a severe performance penalty for using the cpu to render games.
