### ISSUE TITLE
Reduce the number of the Linux Distribuitions in Steam Hardware Survey

### ISSUE THREAD

**Issue by brunotix** [ValveSoftware/steam-for-linux#2379]
Instead of several Linux distributions, only the top 3
should be listed in Steam Hardware Survey
others will be listed on other Linux
Exemple: 
Ubuntu xx.xx: X%
Ubuntu xy.xy: X%
Arch X%
Mint xx X%
Mint xy X%
Other Linux X%

**Comment by kisak-valve** [comment]
The number of visible distros in the survey has been reduced since this request.
