### ISSUE TITLE
[L4D2] mouse cursor is visible when playing

### ISSUE THREAD

**Issue by ZeXx86** [ValveSoftware/steam-for-linux#2385]
Hello

First, big thanks for awesome port of L4D2.
I just found one issue right after level is loaded - while playing I can see mouse cursor.
This cursor is moving as in desktop environment and when its visible during gameplay I can turn around player until mouse cursor hits screen edges.

Workaround for this issue is to activate for example chat window and close it.
Then cursor disappear and I can turn player correctly/freely.
With raw mouse input this issue is not present at all.

All other Source based games are not affected by this issue.

System info:
http://pastebin.com/y0D5Rgjv

Ubuntu 13.04 64bit, Gnome 3 Classic (no effects)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by jazztickets** [comment]
I have not experienced it.

**Comment by kisak-valve** [comment]
Thanks for retesting @jazztickets, closing.
