### ISSUE TITLE
[l4d2] No online games

### ISSUE THREAD

**Issue by kshcherban** [ValveSoftware/steam-for-linux#2387]
No online games can be found for any game section in L4D2 for Linux. Works only single game and quick match.
Connection is OK.

Screenshot:
![223530_screenshots_2013-05-04_00001](https://f.cloud.github.com/assets/2072958/462587/bcb51f56-b4c5-11e2-946a-b60f238a10f8.jpg)

OS: Debian wheezy with latest updates
Steam: API v012
Built on 3d of May 2013
Version: 1367621987

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago. If you are still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
