### ISSUE TITLE
World of Goo: Game screen extended over multiple displays

### ISSUE THREAD

**Issue by mikma** [ValveSoftware/steam-for-linux#239]
World of Goo is the first Steam game I have tried in Linux.
And the problem is that the game screen is extended over both my displays.

I use an ASUSK53SD notebook which has Intel+Nvidia graphics card. I use one external (VGA) display and my main display (it has the gnome shell toolbars) is the built in LCD.
The "Primary Display Resolution:  1366 x 768" below is correct, but the game is run over the complete "Desktop Resolution: 2646 x 1024" instead.

And I use optirun from bumblebee to start the game. 

Known work-around: Disable the external display.

Some packages:
bumblebee: 3.0.1-3~preciseppa2

From Steam's Hardware Information"

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2201 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-35-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  NVIDIA Corporation GeForce 610M/PCIe/SSE2

```
Driver Version:  4.2.0 NVIDIA 304.64
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1058
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 2646 x 1024
Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                        34.4cm x 19.4cm  (39.4cm diag)
Primary VRAM: 2047 MB
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  7765 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  151189 Mb
    Largest Free Hard Disk Block:  18918 Mb

Installed software:

Recent Failure Reports:
    Fri Dec 21 18:49:29 2012 GMT: file ''/tmp/dumps/assert_20121221194921_1.dmp'', upload yes: ''CrashID=bp-330bc7f0-e132-4f96-86d4-c9bdf2121221''

(I don't think the dump is related to the issue I report.)

**Comment by schorsch3000** [comment]
Today nostalgia kicked in, bought the game on steam (played on wii last time) this helped me, thanks!
