### ISSUE TITLE
assert in tier1/fileio.cpp (2519)

### ISSUE THREAD

**Issue by sorokin** [ValveSoftware/steam-for-linux#2391]
I have a few asserts in stderr:

/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/fileio.cpp (2519) : Assertion Failed: Failed to determine free disk space for /mnt/a/Steam/steamapps/common/Surgeon Simulator 2013, error 2
Assert( Assertion Failed: Failed to determine free disk space for /mnt/a/Steam/steamapps/common/Surgeon Simulator 2013, error 2 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/fileio.cpp:2519
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/fileio.cpp (2519) : Assertion Failed: Failed to determine free disk space for /mnt/a/Steam/steamapps/common/Kairo, error 2
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/fileio.cpp (2519) : Assertion Failed: Failed to determine free disk space for /mnt/a/Steam/steamapps/common/Guns of Icarus Online, error 2

error 2 is ENOENT. The problem is that path should be '/mnt/a/Steam/SteamApps/common/', not '/mnt/a/Steam/steamapps/common/'.

Probably because of that updates of games do not work. Steam prints that update is 'Paused' and does not update anything.

**Comment by goakley** [comment]
I had a similar issue while pausing my installing of Frozen Cortex (app 237350).  I was installing to a separate library located on a different disk (`/mnt/steam/steamapps/`).  Resuming the download caused everything to complete fine.

```
$ cat /proc/mounts
/dev/sdb1 /mnt/steam ext4 rw,nosuid,nodev,relatime,data=ordered 0 0
```

```
../tier1/fileio.cpp (2957) : Assertion Failed: Failed to determine free disk space for /mnt/steam/steamapps/common/Frozen Endzone, error 2
assert_20151127173715_28.dmp[1544]: Finished uploading minidump (out-of-process): success = yes
assert_20151127173715_28.dmp[1544]: response: CrashID=bp-46684277-0413-481f-972f-83fd42151127
assert_20151127173715_28.dmp[1544]: file ''/tmp/dumps/assert_20151127173715_28.dmp'', upload yes: ''CrashID=bp-46684277-0413-481f-972f-83fd42151127''
```

**Comment by kisak-valve** [comment]
Closing in favor of #2409.
