### ISSUE TITLE
CSS Options->Multiplayer tab, settings do not save

### ISSUE THREAD

**Issue by arfett** [ValveSoftware/steam-for-linux#2395]
No matter how many time you set your crosshair up or advanced settings like your left hand weapon model, disable HTML MOTD, etc, etc these settings are reverted after restarting the game. All other settings in the options appear to save correctly.

This has been an issue since day 1 of linux release on Ubuntu 12.10 x64, Arch x64 and Mint 14 x64.

Edit: Ubuntu 12.10, don't know about 12.04.

**Comment by kisak-valve** [comment]
Hello @arfett, are you still experiencing this issue?

**Comment by arfett** [comment]
I don't know. I don't play CSS any longer.

**Comment by kisak-valve** [comment]
Fair enough, thanks for the feedback. If someone happens upon this issue on an up to date system, then they can open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. Closing.
