### ISSUE TITLE
Extreme texture corruption, Steam Overlay lag, and unbearably low framerates with Radeon HD 7900

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#2406]
Using Ubuntu 13.04 with the latest AMD driver (Catalyst 13.4)
- TF2 is completely unplayable at lowest settings with the latest AMD driver. Framerates are absolutely horrible.
- DODS is playable-ish, so long as you don't use a high level of AF and have AA disabled. There is a lot of texture corruption here as well.
- Steam overlay reduces framerates drastically, that includes whenever someone messages me in-game.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
