### ISSUE TITLE
Consider updating open source libraries

### ISSUE THREAD

**Issue by h010c** [ValveSoftware/steam-for-linux#2408]
Consider updating open source libraries such as:
1. FMOD Sound and Music System 
   current: fmod.dll ver.3.7.1.0 
   last updated Apr 12, 2013 to version 4.44?
2. International Components for Unicode
   current: icudt.dll ver.4.6.0.0
   updated: icudt51.dll ver.51.1.0.0 at Apr 20, 2013
   http://site.icu-project.org/download/51
3. Chromium Embedded Framework (CEF) Dynamic Link Library
   current: libcef.dll ver.1.989.464.0
   updated: ver.1.1364.1123 at Mar 4, 2013
   http://www.magpcss.net/cef_downloads/
4. Miles Sound System (not open source, hah, but you've got a license)
   current: Mss32.dll ver.9.3a
   updated: ver.9.3e at Apr 24, 2013
   http://www.radgametools.com/msshist.htm
5. Simple DirectMedia Layer
   current: sdl2.dll ver.1.3.0.0
   updated: ver.2.0 at May 4, 2013
   http://www.libsdl.org/hg.php

Not a big deal really, but anyway, just letting you know.

P.S. And also letting you know, that all you updates are ponies, you didn't fix anything of importance(probably slowhacking only in the LATEST UPDATE), but broke all mods, addons and plugins which were built for the game during last decade. Cheers.

**Comment by kisak-valve** [comment]
Closing as this this is out of date well as not a linux request. Most if not all of these libraries have been updated over the years.
