### ISSUE TITLE
L4D2 Cannot execute game if it is installed on non-home partition.

### ISSUE THREAD

**Issue by lanseg** [ValveSoftware/steam-for-linux#2412]
Following errors, If the game is installed on non-home partition (by creating symlink to ~/.local/share/steam, or selecting during install):

Summary:
Steam client says, that game is not installed after steam client restart, or even after game download. After pressing "Install game" again, steam starts validating already installed game (18GB for L4D2, about 20 minutes) and only after that, play button becomes enabled. 

Additional information:
If executing steam from terminal, it says 'Game removed: AppID 223530 "Left 4 Dead 2 Beta", ProcID 5475'

**Comment by kisak-valve** [comment]
Hello @lanseg, are you still experiencing this issue with a secondary steam library folder?

**Comment by lanseg** [comment]
I'm far from my machine now, I'll be able to try it again in a week or two

**Comment by kisak-valve** [comment]
Closing pending feedback.
