### ISSUE TITLE
Steam client has too binaries installed in /home/*

### ISSUE THREAD

**Issue by castarco** [ValveSoftware/steam-for-linux#2414]
Steam client has too binaries installed in /home/\* ...
I understand that games are in /home/\* ... but Steam Client updates should be done via repositories in case there are repository system, like apt. May be this can be done using a flag in a settings file (combined with symbolic links).

In part, to save net resources, in part, because there are a lot of machines where system files are in ssd (to become faster), while user files are yet in hdd (because the greater capacity). If I have steam files in /home/\* , then I can't take advantage of the system configuration.

**Comment by kisak-valve** [comment]
Closing per the last comment.
