### ISSUE TITLE
Steam client lost all bookmarked servers and game groups.

### ISSUE THREAD

**Issue by pztrn** [ValveSoftware/steam-for-linux#2416]
Today, when I logged in in Steam, I see no games groups and bookmarked servers anymore.

[System information](http://server.pztrn.ru/paste/282)

**Comment by kisak-valve** [comment]
Hello @pztrn, have you seen this issue in recent history?

**Comment by pztrn** [comment]
Nope, nothing like that for last 4 years :)

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
