### ISSUE TITLE
Corrupted game files after format upgrade

### ISSUE THREAD

**Issue by sebleblanc** [ValveSoftware/steam-for-linux#2419]
I had not run Steam for a while, then I migrated from Ubuntu to Arch Linux. Upon trying to start Counter-Strike: Source, I got a pop-up telling me that CS:S resources had to be upgraded to a more efficient format. After accepting, and waiting a few minutes, the popup mentioned that the upgrade was complete (I forgot the actual message).

Once I tried starting CS:S, I got another error message, this time related to corrupted files. I right-click on CS:S then select "Verify integrity of game cache" in the Properties dialog. After a quick scan, I get a message telling me that 1600-something files out of 1600-something are corrupted, and need to be downloaded again. Cue a couple gigabytes download.

I have no idea what triggered this issue.

**Comment by kisak-valve** [comment]
Closing because steampipe migrations almost never happen in the wild anymore.
