### ISSUE TITLE
Steam Client unresponsive to mouse clicks after workspace switch

### ISSUE THREAD

**Issue by glaere** [ValveSoftware/steam-for-linux#2425]
I prefer to use a workspace per application but when I switch between workspaces and back to Steam mouse clicks become unresponsive.  Keyboard works fine.  

This happens regardless of whether Steam is fullscreen or not, or whether I'm using the integrated or discrete graphics chip.

I can work around this by unfullscreening or snapping the client with the panel controls or keyboard shortcuts which restore normal functionality until the next time I switch.

This regularly but not always happens when switching between any workspaces.  It doesn't matter whether I actually do anything or click on those workspaces.  If i keep switching I regain mouse use after about four times.

Specs:
Ubuntu 13.04 
https://gist.github.com/glaere/790136117b74d21992ee

**Comment by kisak-valve** [comment]
Hello @glaere, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
