### ISSUE TITLE
Portal does not initial fullscreen window properly with tiling window managers

### ISSUE THREAD

**Issue by hcaulfield57** [ValveSoftware/steam-for-linux#2431]
I tried playing Portal (thanks so much for porting it!) with dwm. The game appeared windowed and small and did not respond to mouse clicks. I have heared that others with other similar window managers could not get the game to work either. I installed openbox and the game seems to play as it should. I consider this a bug, becasue I played Portal through wine under dwm, and it worked fine.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system and dwm or larswm?

**Comment by acafresna** [comment]
larswm is now unmaintained. I at least don't use it anymore.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by stephen-smith** [comment]
Had this happen today.  Different, but still tiling, window manager, XMonad.  Portal window did not fullscreen automatically, and the mouse pointer was offset.
