### ISSUE TITLE
TF2 slow and beta unclickable

### ISSUE THREAD

**Issue by olaulau** [ValveSoftware/steam-for-linux#2441]
Hi ;

I'm currently testing steam for linux on a fresh install of Ubuntu 13.04 amd64 with nvidia 313 drivers.
All valve products works correctly but TF2 doesn't :
- TF2 is very slow in game, especially when I go outside in maps (complex graphics, action ...) it sometimes freeze for 1 second. very poor performance compared to windows version.
- TF2 beta : I can't click in the menu so I must exit with alt+f4.

here is my config :
AMD Phenom II X4 955
8Gb of DDR3
GeForce 460

**Comment by kisak-valve** [comment]
Hello @olaulau, I'm fairly sure your issue is the same one being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/23. Closing in favor of that issue report.
