### ISSUE TITLE
clipboard

### ISSUE THREAD

**Issue by rfreytag1** [ValveSoftware/steam-for-linux#2450]
Hello, I have some issues with clipboard usage.
As already reported here #2424, Steam and my Desktop become unresponsive after middle-clicking and also there is no text pasted as it should.
I also can't use ctrl+c/v/x, it simply doesn't work.
When I select in Steam and press ctrl+c and then want to paste it somewhere there is nothing in the clipboard or older stuff I copied before, right-click -> copy works however.
If I want to paste something in a textbox in steam with ctrl+v nothing happens, right-click -> paste works however too.

I'm using Arch Linux with Xfce4(with xfwm4) on xorg 1.13

**Comment by kisak-valve** [comment]
Hello @rfreytag1, are you able to copy/paste with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
