### ISSUE TITLE
[L4D2] High mem usage, possible memleak

### ISSUE THREAD

**Issue by jelly** [ValveSoftware/steam-for-linux#2453]
I'm running L4D2 for an hour and it uses about 2G of memory. The log:

WARNING: setlocale('en_US.UTF-8') failed, using locale:'C'. International characters may not work.
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 2097152, Total Avail: 2097152, Current Avail: 1846616
GL_MAX_SAMPLES_EXT: 64
Using breakpad crash handler
Setting breakpad minidump AppID = 223530
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198046463793 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198046463793
Did not detect any valid joysticks.
Could not load chromehtml library.Querying for subscribed files
IDirect3DDevice9::Create: BackBufWidth: 1920, BackBufHeight: 1080, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
BinkOpen( /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/media/valve.bik )
ConVarRef volume doesn't point to an existing ConVar
BinkOpen( /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/media/l4d2_intro.bik )
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Loaded program cache file "glshaders.cfg", total keyvalues: 0, total successfully linked: 0
Precache: Took 0 ms, Vertex 0, Pixel 0
Game.so loaded for "Left 4 Dead 2"
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 0 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 80 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 464 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 8 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 392 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 392 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 1 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x0000000E) differs from mask derived from shader name (0x0000001F) for shader ps-file shadow_ps20b ps-index 0 ps-combo 0
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 888 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 1272 ps-combo 1
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 120 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x000000E0) differs from mask derived from shader name (0x000000C0) for shader ps-file water_ps20b ps-index 504 ps-combo 1
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
Unable to remove /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_beta/textwindow_temp.html!
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_011.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_011.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_007.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_007.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/update/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/update/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_008.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_008.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_003.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_003.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc1/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc1/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_000.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_002.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_002.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_003.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_003.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_010.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_010.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc1/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc1/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_009.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_009.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_002.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc2/pak01_002.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_006.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_006.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_005.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_005.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_004.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2/pak01_004.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_001.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_002.vpk was never closed
File /home/jelle/Steam/SteamApps/common/Left 4 Dead 2 Beta/left4dead2_dlc3/pak01_002.vpk was never closed

**Comment by kisak-valve** [comment]
Hello, is anyone is still experiencing this issue with an up to date system?

**Comment by jelly** [comment]
I haven't played L4D2 in a while (1 year) so can't tell.

**Comment by kisak-valve** [comment]
If anyone is still experiencing this issue, please open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. There's a known high memory usage with mesa and integrated graphics being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/2212.
