### ISSUE TITLE
Dungeon Defenders randomly crashes

### ISSUE THREAD

**Issue by logan123** [ValveSoftware/steam-for-linux#2455]
First off I post this information in the game's bugzilla and in the AMD forum 
The game crashes at random point in the game and different times.
I used gdb and this is what I got

0xf592451e in ?? () from /usr/lib/i386-linux-gnu/dri/fglrx_dri.so
I think this will be helpful
http://pastebin.com/R9M9TaUH

Here is my System Information:
http://pastebin.com/WNBefMVP

You should also know that I tried to running this game with open source driver and with only Intel graphics and It still crashed.
I thought maybe its because of this:
#2  0xf39f441f in ?? () from /home/logan/.local/share/Steam/linux32/steamclient.so

Any Ideas?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant. If you are still experiencing this issue with an up to date system, it may be worthwhile to contact your driver vendor.
