### ISSUE TITLE
Segfaults with catalyst + awesome 3.5 + xinerama

### ISSUE THREAD

**Issue by klj613** [ValveSoftware/steam-for-linux#2458]
The other day I was trying to get steam working, however was segfaulting.

I had xinerama installed for dual monitor support since awesome 3.5 requires it.

I installed awesome 3.4 instead because xinerama was giving me other issues.

Now I noticed steam started working. However I am not sure if it is because of xinerama or awesome 3.5 or something else. I will investigate when I have time however I thought I'd raise a issue here in case someone else is having the same issue.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
