### ISSUE TITLE
Steam client is thinking mouse is in a different position

### ISSUE THREAD

**Issue by j-walk** [ValveSoftware/steam-for-linux#2465]
It thinks Im pointing about 1cm to the upper left of where my cursor is.. I have no idea how to fix it.. Is there anyway i can like re coordinate my steam?

**Comment by kisak-valve** [comment]
Hello @j-walk, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
