### ISSUE TITLE
Steam error sound repeats very fast in some conditions

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/steam-for-linux#2482]
## Steps to reproduce :
- 1 - Launch a game that will be updated before it can launch (Example : the new Half-Life 2 version)
- 2 - Somehow forbid steam to synchronize saved games with steam cloud (If there is only port 443/80 opened, it works well). Steam will display an error message : "Could not synchronize to steam cloud" or something similar. 
- 3 - Next, bring the first window (the one with the update progress bar on it) with Alt-Tab or with the taskbar. You will hear the steam error sound repeatedly. It also works with steam main window.
### Interpretation :

It seems that The steam warning message is unable to bring itself back to foreground. 
The error sound playback  should at least be stopped, because it is really annoying.

It may also be a problem with others error dialogs, I didn't tried.
## System Info :

Distribution : Slackware linux 14.0 64.
Window manager : KDE 4.10.3 (trying with others desktop managers right now, I will edit this issue)
EDIT : Seems not to happen with Xfce. Maybe an issue related to effects? I am running out of games to update...
Desktop effects enabled (OpenGL) with KDE.

Latest steam beta build at the time of writing (Wednesday, 15th may 19:45 GMT)

**Comment by MayeulC** [comment]
I am reviewing my old bug reports, and can confirm this one is still present, at least for the KDE desktop.

Here is a simpler way to trigger it:
1. Open steam settings
2. Click on the button to change the beta status
3. use the taskbar to bring the settings window to the foreground

## System info:
Distribution: Arch Linux
Desktop environment: KDE plasma 5.9.5

### Misc
I also tried this on XFCE, the background window gets reactivated instantly, which is consistent with the expected behavior. I let you judge if this needs to be fixed or not, but I can understand that the priority is rather low.

**Comment by kisak-valve** [comment]
Hello @MayeulC, this issue is also being tracked at #846. Thanks for confirming, but I'm going to close this in favor of the older issue report.
