### ISSUE TITLE
Emoticons view totally screwy in Trading Card beta

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/steam-for-linux#2483]
![screenshot from 2013-05-16 14 21 02](https://f.cloud.github.com/assets/308992/512558/975d37ba-be2b-11e2-86b2-40156fc3a170.png)

Those emoticons are cut off randomly, rather than being properly grid-aligned.

**Comment by Uramekus** [comment]
fixed on the new steam chat

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
