### ISSUE TITLE
Non-steam game will not change the status.

### ISSUE THREAD

**Issue by adam900710** [ValveSoftware/steam-for-linux#2484]
BUG:
When imported a working .desktop and run it,
the status of your account will not change.
That is different from the behavior of windows version.

And about the .desktop file, the exec word will call a bash script to setup the needed environment to start a wine with xboxdrv.

Step to reproduce:
1. Import a desktop file which will exec a bash script.
2. Run it
3. Check the status of your account.

System Info:(nothing to do with the bug though)
Archlinux
WM: Openbox 3.5.0

Additional info:
Some desktop file will be OK, like the one of chromium but some will not, like audacious.

**Comment by kisak-valve** [comment]
Hello @adam900710, are you able to reproduce this issue with an up to date client?

**Comment by kisak-valve** [comment]
Closing pending feedback.
