### ISSUE TITLE
Missing .desktop file for Team Fortress 2.

### ISSUE THREAD

**Issue by mavit** [ValveSoftware/steam-for-linux#2486]
Other Steam games install .desktop files to `~/.local/share/applications/`, causing an icon for the game to appear in the Gnome menus, but for Team Fortress 2 there is none.  I'm pretty sure the icon used to appear in the Gnome menus, so it appears that it was lost in a recent update.

I was able to replace the icon by selecting <kbd>Create desktop shortcut</kbd> in Steam and then moving the resulting `Team Fortress 2.desktop` file from `~/Desktop/` to `~/.local/share/applications/`.

I'm running Fedora 18.

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.

**Comment by kisak-valve** [comment]
Closing in favor of #3651.
