### ISSUE TITLE
TF2 OpenGL set entry point "glGetError" error on launch, incorrect OpenGL version detection.

### ISSUE THREAD

**Issue by hkparker** [ValveSoftware/steam-for-linux#250]
When launching tf2 I receive the error "Could not find required OpenGL entry point "glGetError"! Either your video card is unsupported, or your OpenGL driver needs to be updated".

OS: Mint 14 with Cinnamon 64 bit
CPU: i7-3930k
Mobo: ASUS Rampage IV Extreme
RAM: 32GB Corsair Vengeance 9-9-9-24 1333MHz
Graphics: ASUS AMD Radeon 6970
Graphics Driver: 12.11 beta
OpenGL version (According to CCC): 4.2.11995 Compatibility Profile Context.

When I run steam from terminal, I can see the error right before the message is displayed.

SDL failed to create GL compatibility profile (whichProfile=0!
PROBLEM: You appear to have OpenGL 1.4.0, but we need at least 2.0.0!
Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated.

It appears to think I have OpenGL 1.4.0 installed, though AMD reports 4.2.  Also, this error appears often in terminal output:

libGL error: failed to load driver: swrast

Could I have two versions of OpenGL installed?  Any help would be appreciated please, thank you.  Also I was able to run tf2 fine about a week ago, this is a new error.

Full terminal output:

Installing breakpad exception handler for appid(steam)/version(1355957371_client)
libGL error: failed to load driver: swrast
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
unlinked 0 orphaned pipes
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
libGL error: failed to load driver: swrast
libGL error: Try again with LIBGL_DEBUG=verbose for more details.

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:6516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
surface_linux.cpp (1383) : Assertion Failed: X context is not using direct rendering. Unfasten your seatbelt...

Assert( Assertion Failed: X context is not using direct rendering. Unfasten your seatbelt...
 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/surface_linux.cpp:1383

Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20121221134357_1.dmp
[1221/134357:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
success = yes
response:  CrashID=bp-d0d7959b-18e5-44c0-ba0c-42f6a2121221
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Adding license for package 4314
Adding license for package 469
Adding license for package 7566
Adding license for package 37
Adding license for package 8183
Adding license for package 663
Adding license for package 13318
Adding license for package 12064
Adding license for package 13601
Adding license for package 16549
Adding license for package 0
roaming config store loaded successfully - 1113 bytes.
migrating temporary roaming config store
ExecCommandLine: "/home/hayden/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 74: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 75: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 76: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 77: 8x256, total string texture memory is 516.10 KB
Generating new string page texture 78: 32x256, total string texture memory is 548.86 KB
Generating new string page texture 80: 24x256, total string texture memory is 573.44 KB
System startup time: 9.94 seconds
libGL error: failed to load driver: swrast
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 132: 128x256, total string texture memory is 704.51 KB
Generating new string page texture 133: 384x256, total string texture memory is 1.10 MB
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Game update: AppID 440 "Team Fortress 2", ProcID 6610, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
libGL error: failed to load driver: swrast
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
PROBLEM: You appear to have OpenGL 1.4.0, but we need at least 2.0.0!
Could not find required OpenGL entry point 'glGetError'! Either your video card is unsupported, or your OpenGL driver needs to be updated.
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
Game removed: AppID 440 "Team Fortress 2", ProcID 6610 
Generating new string page texture 160: 256x256, total string texture memory is 1.36 MB
Installing breakpad exception handler for appid(steam)/version(1355957371_client)
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Shutting down. . .
unlinked 6 orphaned pipes
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 347621 single object sleeps, 735 multi object sleeps
CAsyncIOManager: 25 single object alertable sleeps, 2 multi object alertable sleeps

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been resolved. This is a system configuration issue. Source 1 Games including TF2 require a sane 32 bit opengl driver that supports OpenGL 2.1 + sRGB (an OpenGL 3.0 feature) in order to work. For nVidia, this was introduced in the 310 series driver.
