### ISSUE TITLE
CS:Source Random FPS Decrease and Inability to use Mouse 

### ISSUE THREAD

**Issue by LinuxEnthusiast** [ValveSoftware/steam-for-linux#2510]
This has happened since I started playing CSS near enough when it became available. When starting the game (say a one in seven chance) when entering an online or local game there is a noticeable decrease in my framerate to where it's around 20. This is always accompanied by the inability to use the mouse for panning your view. All the buttons on the mouse work (LMB scroll wheel etc) it's just panning that doesn't.

I've ran CS:S via terminal and here is the output when such a problem occured. http://pastebin.com/ETuq4ZcK
Usually I can just exit and re-open CS:S and it works but sometimes I have to also restart steam.

**Using Intel HD 2k IGP onboard an i5-2320. Using the 'Unity' desktop environment on Ubuntu 13.04.

**Comment by kisak-valve** [comment]
Hello @LinuxEnthusiast, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
