### ISSUE TITLE
Add /usr/local/share/applications to the *.desktop search path for non-steam games

### ISSUE THREAD

**Issue by g2p** [ValveSoftware/steam-for-linux#2519]
Some games (like Closure) have their shortcuts in `/usr/local/share/applications`.
Please add that directory to the "add a non-Steam game to my library" search path.

**Comment by johnv-valve** [comment]
should be fixed in the just-released beta https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1447198999525237825
