### ISSUE TITLE
Friend status pulls game titles from my library instead of theirs

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/steam-for-linux#2524]
One of my friends has been playing _Half-Life 2_ of late, and the way it's displayed changes based on which OS I'm in. When I'm in Linux, the status reads "In-Game: Half-Life 2 (Beta)", and in Windows it reads "In-Game: Half-Life 2". So unless she is also dual-booting and switching between systems at the exact same time as I am, it's pulling the title of the game from my library instead of hers.

**Comment by kisak-valve** [comment]
Hello @stevethepocket, as far as I can tell, this behavior is intentional and beneficial to developers. It prevents unreleased game titles from showing up by accident to friends of devs. If there are any major discrepancies, then they should be brought to the attention of the game's devs.
