### ISSUE TITLE
Help Desk Error when trying to install some of the games from HB8

### ISSUE THREAD

**Issue by Naddiseo** [ValveSoftware/steam-for-linux#2529]
I'm currently putting in the steam codes from the latest HB, but I get "An error occurred while installed <gamename> (invalid platform)". 

Additionally, the [link provided](https://support.steampowered.com/kb_article.php?ref=9361-YAGV-7766&l=english) gives the following error

> Help Desk Error
> The specified article does not exist or you do not have permission to view it.

**Comment by kisak-valve** [comment]
Hello @Naddiseo, this url appears to have been fixed some time ago.

If you encounter the invalid platform error and the game claims support for your OS, then this should be brought to the game's devs on a per-game basis.
