### ISSUE TITLE
Half Life: Opposing Forces crashes

### ISSUE THREAD

**Issue by salt86** [ValveSoftware/steam-for-linux#2534]
This game won't load or allow for a new game to be started. When a second attempt is made, the game crashes and exits.
# Terminal output

$ steam
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
[0530/001505:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1369788789_client)

(steam:14114): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:14114): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
roaming config store loaded successfully - 25018 bytes.
migrating temporary roaming config store
`menu_proxy_module_load': /home/kurtis/.local/share/Steam/ubuntu12_32/steam: undefined symbol: menu_proxy_module_load

(steam:14114): Gtk-WARNING **: Failed to load type module: (null)

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Adding license for package 0
Adding license for package 1
Adding license for package 25
Adding license for package 37
Adding license for package 59
Adding license for package 64
Adding license for package 217
Adding license for package 258
Adding license for package 294
Adding license for package 295
Adding license for package 305
Adding license for package 415
Adding license for package 418
Adding license for package 426
Adding license for package 434
Adding license for package 439
Adding license for package 469
Adding license for package 470
Adding license for package 518
Adding license for package 601
Adding license for package 1062
Adding license for package 1070
Adding license for package 1331
Adding license for package 1549
Adding license for package 1636
Adding license for package 1677
Adding license for package 1910
Adding license for package 1942
Adding license for package 2063
Adding license for package 2103
Adding license for package 2288
Adding license for package 2294
Adding license for package 2747
Adding license for package 4076
Adding license for package 4314
Adding license for package 4326
Adding license for package 4451
Adding license for package 4453
Adding license for package 4457
Adding license for package 4458
Adding license for package 4459
Adding license for package 4460
Adding license for package 4482
Adding license for package 4670
Adding license for package 4775
Adding license for package 4776
Adding license for package 4991
Adding license for package 6056
Adding license for package 6185
Adding license for package 6268
Adding license for package 6381
Adding license for package 6387
Adding license for package 6424
Adding license for package 6428
Adding license for package 6469
Adding license for package 6646
Adding license for package 6651
Adding license for package 6896
Adding license for package 6970
Adding license for package 7128
Adding license for package 7135
Adding license for package 7166
Adding license for package 7392
Adding license for package 7416
Adding license for package 7427
Adding license for package 7477
Adding license for package 7514
Adding license for package 7528
Adding license for package 7566
Adding license for package 7584
Adding license for package 7586
Adding license for package 7731
Adding license for package 7864
Adding license for package 7967
Adding license for package 7969
Adding license for package 7971
Adding license for package 8056
Adding license for package 8077
Adding license for package 8091
Adding license for package 8132
Adding license for package 8181
Adding license for package 8182
Adding license for package 8183
Adding license for package 8306
Adding license for package 8386
Adding license for package 8405
Adding license for package 8441
Adding license for package 8470
Adding license for package 8500
Adding license for package 8535
Adding license for package 8536
Adding license for package 8560
Adding license for package 8566
Adding license for package 8583
Adding license for package 8632
Adding license for package 8641
Adding license for package 8647
Adding license for package 8648
Adding license for package 8691
Adding license for package 8706
Adding license for package 8731
Adding license for package 8756
Adding license for package 8757
Adding license for package 8866
Adding license for package 11002
Adding license for package 11005
Adding license for package 11010
Adding license for package 11033
Adding license for package 11098
Adding license for package 11144
Adding license for package 11273
Adding license for package 11274
Adding license for package 11322
Adding license for package 11347
Adding license for package 11376
Adding license for package 11538
Adding license for package 11574
Adding license for package 11624
Adding license for package 11653
Adding license for package 11683
Adding license for package 11733
Adding license for package 11780
Adding license for package 11787
Adding license for package 11788
Adding license for package 11789
Adding license for package 11793
Adding license for package 11802
Adding license for package 11864
Adding license for package 12000
Adding license for package 12024
Adding license for package 12048
Adding license for package 12051
Adding license for package 12079
Adding license for package 12152
Adding license for package 12164
Adding license for package 12165
Adding license for package 12189
Adding license for package 12209
Adding license for package 12242
Adding license for package 12281
Adding license for package 12283
Adding license for package 12284
Adding license for package 12298
Adding license for package 12361
Adding license for package 12383
Adding license for package 12456
Adding license for package 12486
Adding license for package 12487
Adding license for package 12505
Adding license for package 12513
Adding license for package 12517
Adding license for package 12521
Adding license for package 12572
Adding license for package 12573
Adding license for package 13082
Adding license for package 13161
Adding license for package 13270
Adding license for package 13289
Adding license for package 13290
Adding license for package 13326
Adding license for package 13363
Adding license for package 13364
Adding license for package 13390
Adding license for package 13514
Adding license for package 13566
Adding license for package 13582
Adding license for package 13595
Adding license for package 13600
Adding license for package 13602
Adding license for package 13603
Adding license for package 13624
Adding license for package 13637
Adding license for package 13646
Adding license for package 13734
Adding license for package 13743
Adding license for package 13764
Adding license for package 13792
Adding license for package 13836
Adding license for package 13960
Adding license for package 13971
Adding license for package 13993
Adding license for package 13997
Adding license for package 14007
Adding license for package 14165
Adding license for package 14193
Adding license for package 14217
Adding license for package 14241
Adding license for package 14288
Adding license for package 14303
Adding license for package 14323
Adding license for package 14476
Adding license for package 14479
Adding license for package 14528
Adding license for package 14539
Adding license for package 14543
Adding license for package 14630
Adding license for package 14633
Adding license for package 14695
Adding license for package 14708
Adding license for package 14814
Adding license for package 14818
Adding license for package 14819
Adding license for package 14820
Adding license for package 14870
Adding license for package 14871
Adding license for package 14891
Adding license for package 14938
Adding license for package 14977
Adding license for package 15055
Adding license for package 15059
Adding license for package 15116
Adding license for package 15136
Adding license for package 15176
Adding license for package 15383
Adding license for package 15386
Adding license for package 15612
Adding license for package 15638
Adding license for package 15833
Adding license for package 16020
Adding license for package 16026
Adding license for package 16056
Adding license for package 16081
Adding license for package 16128
Adding license for package 16131
Adding license for package 16132
Adding license for package 16342
Adding license for package 16360
Adding license for package 16549
Adding license for package 16604
Adding license for package 16632
Adding license for package 16898
Adding license for package 16931
Adding license for package 17011
Adding license for package 17675
Adding license for package 17762
Adding license for package 17804
Adding license for package 17864
Adding license for package 17883
Adding license for package 17884
Adding license for package 17915
Adding license for package 17921
Adding license for package 17957
Adding license for package 17968
Adding license for package 18120
Adding license for package 18207
Adding license for package 18267
Adding license for package 18488
Adding license for package 18613
Adding license for package 18616
Adding license for package 18629
Adding license for package 18770
Adding license for package 18875
Adding license for package 18877
Adding license for package 18899
Adding license for package 19296
Adding license for package 25581
Adding license for package 26004
Adding license for package 26476
Adding license for package 26585
Adding license for package 26703
Adding license for package 27531
primarycache setting for app 65300 is set to non-existent cache 65304
primarycache setting for app 65300 is set to non-existent cache 65304
ExecCommandLine: "/home/kurtis/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 93: 64x256, total string texture memory is 376.83 KB
Generating new string page texture 94: 128x256, total string texture memory is 507.90 KB
Generating new string page texture 95: 32x256, total string texture memory is 540.67 KB
Generating new string page texture 99: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 100: 8x256, total string texture memory is 548.86 KB
System startup time: 30.58 seconds
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/kurtis/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/kurtis/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 128: 128x256, total string texture memory is 679.94 KB
Generating new string page texture 129: 512x256, total string texture memory is 1.20 MB
Generating new string page texture 130: 128x256, total string texture memory is 1.34 MB
Generating new string page texture 131: 384x256, total string texture memory is 1.73 MB
Generating new string page texture 133: 16x256, total string texture memory is 1.74 MB
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Game update: AppID 50 "Half-Life: Opposing Force (Beta)", ProcID 14254, IP 0.0.0.0:0
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:14114): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Using breakpad crash handler
Setting breakpad minidump AppID = 50
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197967881941 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197967881941
GL_SIZES:  r:8 g:8 b:8 a:8 depth:24

ARB Multitexture extensions found.

8 texture units.  Detail texture supported.

Installing breakpad exception handler for appid(gameoverlayui)/version(20130528172028_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "overlay-scrollbar"
[0530/001615:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
[0530/001615:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Platform config directory: platform/config
0:Initializing platform...
Server module initialized.

World module initialized.

STEAM Auth Server

AppActive: active
AppActive: active
CAPIJobRequestUserStats - Server response failed 2
Couldn't get GiveFnptrsToDll in 

Host_Error: Couldn't get DLL API from !

Loading game from SAVE/autosave01.sav...

/home/kurtis/.local/share/Steam/SteamApps/common/Half-Life/hl.sh: line 38: 14258 Segmentation fault      (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
Game removed: AppID 50 "Half-Life: Opposing Force (Beta)", ProcID 14258 
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
Installing breakpad exception handler for appid(steam)/version(1369788789_client)
# system info

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3500 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-22-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7900 Series

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.55" x 11.57"  (23.58" diag)
                                        52.2cm x 29.4cm  (59.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  16032 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  150098 Mb
    Largest Free Hard Disk Block:  37399 Mb

Installed software:

Recent Failure Reports:
    Thu May 30 01:54:56 2013 GMT: file ''/tmp/dumps/assert_20130529185436_1.dmp'', upload no: ''Couldn't resolve host name''
    Thu May 30 01:55:07 2013 GMT: file ''/tmp/dumps/assert_20130529185447_2.dmp'', upload no: ''Couldn't resolve host name''
    Thu May 30 01:55:28 2013 GMT: file ''/tmp/dumps/assert_20130529185507_3.dmp'', upload no: ''Couldn't resolve host name''
    Thu May 30 01:55:28 2013 GMT: file ''/tmp/dumps/assert_20130529185508_1.dmp'', upload no: ''Couldn't resolve host name''
# additional info

Multi-player does work. Blue Shift won't load or start a new game either. Somehow, Half-Life does work just fine.

**Comment by kisak-valve** [comment]
Hello @salt86, are you still experiencing this issue with an up to date system?

**Comment by salt86** [comment]
no @kisak-valve
