### ISSUE TITLE
Steam won't run on Fedora 18 64bit w/ Bumblebee (nVidia Optimus)

### ISSUE THREAD

**Issue by runecasters** [ValveSoftware/steam-for-linux#2541]
Trying to get Steam working on a fresh install of Fedora 18 on a HP Envy DV7 using one of those ridiculous Optimus cards. I've got Bumblebee set up and working for both optirun and primusrun at least for GLX test programs, registering the right driver (nVidia ver 310) etc. But running Steam with either optirun or primusrun causes a segfault at startup. This segfault doesn't happen when running Steam normally, but of course games can't make use of the graphics card then (I also tried getting games running by setting primusrun %command% in the launch options for the game, but that also seems to segfault when the game is run).

primusrun steam: http://pastebin.com/TC8xHnBr (dumpfile: http://filebin.ca/izV3OHqyfRI)
optirun steam: http://pastebin.com/rP4CZXcD (no dump produced?)
steam (as normal, then attempt to run TF2 w/ "primusrun %command%" in launch options): http://pastebin.com/46QUx6He

Steam System Information: http://pastebin.com/V4HfLupa
glxinfo (normal - Intel graphics): http://pastebin.com/8YkX9MAm
glxinfo (optirun): http://pastebin.com/MGS7EXcF
glxinfo (primusrun): http://pastebin.com/H49e3mzy

**Comment by kisak-valve** [comment]
Hello @runecasters, are you still experiencing this issue with an up to date system?

**Comment by runecasters** [comment]
@kisak-valve I never got that Optimus/Bumblebee thing working properly with that machine, and eventually gave up. Very rarely and randomly it would work, and then stop working the next day with no system changes. I've gone back to gaming on a desktop with a PROPER NVIDIA card, and sworn off ever buying a machine with Optimus again.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing per the last comment.
