### ISSUE TITLE
Condition Zero - Mouse buttons lag

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2544]
I played CZERO few months ago with this problem. Basically sometimes I click but nothing happens, it's like if no button was pressed. Other times when pressed MOUSE1 it unloads my magazine. It also happens with all keys when raw input is on. I can't disable raw input, that's unfortunately not an option.

**Comment by kisak-valve** [comment]
Hello @amarildojr, are you experiencing this issue with an up to date system? If you are, what DE are you using and do you have middle mouse click emulation turned on?

**Comment by kisak-valve** [comment]
Closing as this appears to have been a system issue related to middle mouse click emulation.

**Comment by amarildojr** [comment]
@kisak-valve This bug was fixed shortly after I reported it, I'm pretty sure VALVe developers fixed it.
