### ISSUE TITLE
Generic Linux Kernel Causes Input Lag, Delayed Audio Playback, Choppy and Distorted Audio

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#2547]
The problem:
- The generic kernel is too high in latency for gaming.
- The latency issue is causing a lot of input lag and framerate latency.
- It is also causing a lot of buffer underrun/overrun and audio latency issues.

The solution:
- Replace the kernel with a low latency kernel, which has solved all of my issues with audio latency, choppy and distorted audio, and finally input lag.

For Ubuntu, instead of having to compile the kernel yourself, you can install a low latency kernel from KXStudio developers (supports Lucid (10.04) all the way to Saucy (13.10)).

sudo add-apt-repository ppa:kxstudio-team/kernel -y; sudo apt-get install linux-lowlatency -y

Reboot and select the lowlatency kernel manually in grub (if it is not already the default kernel).

**Comment by kernelOfTruth** [comment]
Appending 

```
threadirqs
```

to the kernel command line

and the following script might help:

```
#!/bin/bash

# Sorted view:
# ps -eLo rtprio,cls,pid,pri,nice,cmd | grep "FF" | sort -r

# ps -eLo pid,cls,rtprio,pri,nice,cmd | grep -i "irq"

# For a non-RT kernel, use kernel option: threadirqs

# http://subversion.ffado.org/wiki/IrqPriorities
# http://alsa.opensrc.org/Rtirq

#piwl=$(pgrep "irq/.*-iwlwifi")
#[[ -n $piwl ]] && chrt -f -p 10 $piwl

#peth=$(pgrep "irq/.*-eth0")
#[[ -n $peth ]] && chrt -f -p 30 $peth

#peth=$(pgrep "irq/.*-eth1")
#[[ -n $peth ]] && chrt -f -p 30 $peth

peth=$(pgrep "irq/.*-eth")
[[ -n $peth ]] && chrt -f -p 50 $peth

# ehci instead of uhci
pmouse=$(pgrep "irq/23-ehci")
[[ -n $pmouse ]] && chrt -f -p 59 $pmouse

pmouse=$(pgrep "irq/20-ehci")
[[ -n $pmouse ]] && chrt -f -p 59 $pmouse

#pmouse=$(pgrep "irq/19-uhci")
#[[ -n $pmouse ]] && chrt -f -p 59 $pmouse

psnd=$(pgrep "irq/.*-snd_hda")
[[ -n $psnd ]] && chrt -f -p 80 $psnd

#pnouveau=$(pgrep "irq/.*-nouveau")
#[[ -n $pnouveau ]] && chrt -f -p 80 $pnouveau

pnvkm=$(pgrep "irq/.*-nvkm")
[[ -n $pnvkm ]] && chrt -f -p 80 $pnvkm


#pkbd=$(pgrep "irq/.*-i8042")
## 2 of them
#for p in $pkbd ; do
#   chrt -f -p 60 $p
#done

prtc=$(pgrep "irq/.*-rtc0")
[[ -n $prtc ]] && chrt -f -p 90 $prtc

( while true ; do 
   # Does not have an IRQ until Xorg is running
   pnvidia=$(pgrep "irq/.*-nvidia")
   if [[ -n $pnvidia ]] ; then
      chrt -f -p 80 $pnvidia
      break
   fi
   sleep 20
done ) &
```

source: https://forums.gentoo.org/viewtopic-p-7153966.html#7153966
