### ISSUE TITLE
Keyboard input issue during scene load in both Source and GoldSrc

### ISSUE THREAD

**Issue by ksthiele** [ValveSoftware/steam-for-linux#2560]
I experienced it so far a couple of time in Portal and CS:Source. After a few minutes of playing, when I walk in a direction, doesn't matter in which one, using the keyboard, it sometimes hangs and he's walking in this direction all the time, all I can do is hitting all other keys until it eventually stops and I can walk in the other direction again. This can be very annoying sometimes.

**Comment by kisak-valve** [comment]
Hello @ksthiele, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
