### ISSUE TITLE
Source engine games have slow player movement, and gravity is off

### ISSUE THREAD

**Issue by mcl21014** [ValveSoftware/steam-for-linux#2565]
After using the beta on Linux, I have noticed that especially in Half Life 2 Gordon moves quite slowly. So slowly that when escaping the apartment block raid in Point Insertion, it is extremely easy to get beaten, shot, etc. This issue will likely get worse as the player progresses, and the enemies get more difficult. Also, he seems to hover a little bit while jumping. Only seems to happen on Linux. Haven't noticed the issue on Windows yet, but then again I've only played the episodic games recently on Windows. They worked fine. I will update if the issue persists on Windows 8 with HL2.

**Comment by kisak-valve** [comment]
Hello @mcl21014, if you are still experiencing this issue with an up to date system, please open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
