### ISSUE TITLE
"A connection to the Steam VAC servers could not be made"

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2567]
I keep getting this issue after playing for a few minutes. Last time this happened the client itself closed but the game was still open until it crashed too.

System info:

---

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  NVIDIA Corporation GeForce 9800 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.30
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 75 Hz
VendorID:  0x10de
DeviceID:  0x614
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 12,20" x 9,06"  (15,20" diag)
                                        31,0cm x 23,0cm  (38,6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1705

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  934457 Mb
    Largest Free Hard Disk Block:  781841 Mb

Installed software:

Recent Failure Reports:
    Fri Jun  7 00:38:21 2013 GMT: file ''/tmp/dumps/crash_20130606213820_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:38:21 2013 GMT: file ''/tmp/dumps/assert_20130606213821_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:38:21 2013 GMT: file ''/tmp/dumps/assert_20130606213821_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:39:37 2013 GMT: file ''/tmp/dumps/assert_20130606213937_2.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:39:52 2013 GMT: file ''/tmp/dumps/assert_20130606213952_3.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:40:23 2013 GMT: file ''/tmp/dumps/assert_20130606214023_4.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:40:30 2013 GMT: file ''/tmp/dumps/assert_20130606214029_2.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:41:48 2013 GMT: file ''/tmp/dumps/crash_20130606214148_5.dmp'', upload no: ''HTTP response code said error''
    Fri Jun  7 00:41:55 2013 GMT: file ''/tmp/dumps/assert_20130606214150_3.dmp'', upload no: ''HTTP response code said error''

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Ketchup901** [comment]
I am getting this. Please reopen.

**Comment by kisak-valve** [comment]
Hello @Ketchup901, given the years of inactivity on this issue report, I'm not going to reopen this issue report.

Here's some open related issue reports to check: #474 #3296 #5200

If the behavior you're seeing doesn't match these, please open a new issue report.
