### ISSUE TITLE
[STEAM CLIENT] Downloads speed on Ubuntu 

### ISSUE THREAD

**Issue by loisgomez** [ValveSoftware/steam-for-linux#2573]
Hi
I dont know if this is intented but downloads speeds on my linux clients are much less stable  than on windows, they go up and down all the time. 
Ive seen this beahaviour for a while now. 
Im using the same server location on both windows and linux machines and ive seen it on my desktop and on my laptop, dont think its hardware related.

![downloads](https://f.cloud.github.com/assets/3087254/627352/85ce58e2-d020-11e2-8a0f-0fb1a35fe9cf.jpg)

**Comment by kisak-valve** [comment]
Hello, is anyone seeing this behavior on an up to date system?

**Comment by nh2** [comment]
That's what it looks like for me today:

![screenshot from 2017-05-17](https://cloud.githubusercontent.com/assets/399535/26133292/4fe9bf42-3aa6-11e7-93a9-de5927126c3a.png)

Still doesn't download things in one go, but it's not clear if that's intended or not, as there is disk activity going on and it's probably also decompressing or something similar.

At least the issue that originally downloads slowed down logarithmically to a crawl seems fixed now.

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been resolved.
