### ISSUE TITLE
Rumble not working if using xboxdrv

### ISSUE THREAD

**Issue by Skiski** [ValveSoftware/steam-for-linux#2578]
Hi,

I'm trying to use xboxdrv instead of xpad to adjust the deadzone of the sticks since some games, like Thomas was alone, doesn't take it into account. I'm using a wired xbox360 controller.

Games works fine with both xpad and xboxdrv, but I only get rumble with xpad (I've tried in Portal and Shank).

I'm using this command to launch xboxdrv:

sudo xboxdrv -d --deadzone 5000 --force-feedback --mimic-xpad --silent --no-extra-devices

I've tested with fftest and both drivers are working, using /dev/input/event6.

I'm using Fedora 17 x64.

I don't know if this can be fix, at least for Portal.

Thanks.

**Comment by kisak-valve** [comment]
Hello @Skiski, @LinAGKar, are either of you still experiencing this issue with an up to date system?

**Comment by Skiski** [comment]
Hi,
I've just checked and everything works fine with Portal and Shank. I'm now using Fedora 24 and I've haven't touched anything about the gamepad drivers, so I'm still using xpad.

So everything is fine now.

**Comment by kisak-valve** [comment]
Closing per the last comment.
