### ISSUE TITLE
Steam and FHS compliance

### ISSUE THREAD

**Issue by mwpow3ll** [ValveSoftware/steam-for-linux#2580]
The other issue discussing this problem was closed, but I didn't see a reason given and this really needs a solution. Here's my suggestion:
- Install the steam client to /opt/valve/steam and use /var/opt/valve/steam accordingly.

The installer would require elevation to create a steam group, make the current user a member of said group (steam), install the client in /opt/valve/steam, and set the group ownership of /opt/valve/steam and /var/opt/valve/steam. This way, the steam client can be run at the user level.
- Games would be stored in /usr/share/games/<game>, a symlink of the game to /usr/games/<game>, shared libs added to /usr/lib/games/<game>, and /var/games/<game> for local user leader board data, etc.

If the steam client wants to install a game it would request elevation, install the game, and set all created root <game> folders, along with the binary link, to the group ownership of steam. That way, the steam client could remove a game, without elevation, provided the user is a member of the steam group.
- /home/<user>/.steam would contain a few client preferences or config files and a database of the games the user has installed which also tracks the DLCs, mods, etc they have access to.
- /home/<user>/.<game> would be the location where games store their save games, screenshots, etc.

Finally, if a user wanted to back-up their games, the steam client could simply tar the /usr/*/<game> locations. If the user chooses to include their specific data in the back-up, the steam client could tar that as well.

This solution really also depends on Valve guiding the game developers to embrace the FHS when porting.

**Comment by rokejulianlockhart** [comment]
This was closed as https://github.com/ValveSoftware/steam-for-linux/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted+sort%3Aupdated-desc by @mwpow3ll at https://github.com/ValveSoftware/steam-for-linux/issues/2580#event-3375219201. Does that mean that the suggestions have been implemented? If not, this should be closed as invalid/unplanned instead.

**Comment by rokejulianlockhart** [comment]
However, I wholeheartedly agree with @mwpow3ll – multi-user systems with not much storage space using family sharing (a common scenario for poor families) are absolutely demolished by Steam.
