### ISSUE TITLE
Steam client is totally unresponsive on 13.04

### ISSUE THREAD

**Issue by axfelix** [ValveSoftware/steam-for-linux#2584]
Can't interact with the Steam client at all after starting; using latest version (.39).

Using Sandybridge graphics with Mesa 9.2.

Windows version works perfectly through wine :)

I get the following output trying to run from shell.

$ steam
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 21138 with name 0eBlobRegistryMutex_9A3F652E66124A18FA18DC13C72CCBB3
removing stale semaphore last operated on by process 21138 with name 0eBlobRegistrySignal_9A3F652E66124A18FA18DC13C72CCBB3
removing stale semaphore last operated on by process 21138 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 21138 with name 0eSteamEngineLock
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
[0611/145247:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)

(steam:23177): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:23177): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!
Generating new string page texture 12: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311.30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 15: 384x256, total string texture memory is 835.58 KB

(steam:23177): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:23177): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

**Comment by kisak-valve** [comment]
Closing as upstream support for Ubuntu 13.04 has been discontinued. If you are still experiencing this issue with an up to date system, please open a new issue report.
