### ISSUE TITLE
[HL2] Game Stucks when I get an achivement

### ISSUE THREAD

**Issue by daJoschi** [ValveSoftware/steam-for-linux#2592]
When I see a Lambda and it counts the Lambda detective achivement, so the game stucks.

Driver for Graphic Card: radeon open source driver (fglrx doesn't run on my system)

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-25-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV710

```
Driver Version:  3.0 Mesa 9.1.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9553
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 14,45" x 9,06"  (17,05" diag)
                                        36,7cm x 23,0cm  (43,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Conexant CX20561 (Hermosa)

Memory:
    RAM:  3919 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_AT.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  371439 Mb
    Largest Free Hard Disk Block:  348040 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @superboom, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
