### ISSUE TITLE
offline mode only

### ISSUE THREAD

**Issue by garrett85** [ValveSoftware/steam-for-linux#2593]
Steam is only starting in offline mode and will not go into online mode at all. When I click > Steam > Go Online... > RESTART AND GO ONLINE, steam shuts down and does not restart. If I manually start steam up again it will still be in offline mode, I am unable to play multiplayer games at all. Specs below.

Mint Linux 64 bit

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2000 Mhz
    1 logical processor
    1 physical processor
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-23-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Muffin
    Steam Runtime Version:  steam-runtime-release-i386_2013-05-08

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon 3000 Graphics

```
Driver Version:  3.3.11672 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9616
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 16.14" x 9.06"  (18.50" diag)
                                        41.0cm x 23.0cm  (47.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  3702 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  226875 Mb
    Largest Free Hard Disk Block:  119743 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
