### ISSUE TITLE
Steam text/fonts problems

### ISSUE THREAD

**Issue by Ghost99** [ValveSoftware/steam-for-linux#2601]
I have Gentoo on AMD64. My Xorg DPI setting is 106. System locale is "ru_RU.UTF8".
1. Text in update window's title is written in incorrect encoding. That problem is occurs only in update window.
   This is not a Cyrillic:
   ![not_cyrillic](https://f.cloud.github.com/assets/2134112/675177/c005ab72-d8eb-11e2-9d9f-913509c05e85.png)
2. Text in some Steam elements (buttons, text fields etc) seems to be overflowed. This is most certainly related for my system's non-standard DPI (106). But still.
   ![text_overflow](https://f.cloud.github.com/assets/2134112/675224/9555681c-d8ec-11e2-8018-55c0f11065e7.png)

**Comment by kisak-valve** [comment]
Closing as this was fixed some time ago.
