### ISSUE TITLE
The color of background in menu of Personal Achievements are the same as font

### ISSUE THREAD

**Issue by danvyr** [ValveSoftware/steam-for-linux#2604]
I had this bug since closed beta.

Gentoo Linux 3.9.4
KDE 4.10.3
Qt 4.8.4-r4
app-emulation/emul-linux-x86-sdl 20130224 
and other emul-linux-x86  20130224
media-libs/libsdl  1.2.15-r2

![steam](https://f.cloud.github.com/assets/1217671/676855/9ef3d6de-d90e-11e2-9db5-91fc37acd2cf.png)

**Comment by kisak-valve** [comment]
Closing because Steam no longer uses WebKit.
