### ISSUE TITLE
Fedora 19: Game overlay causes certain games not to start

### ISSUE THREAD

**Issue by zerodogg** [ValveSoftware/steam-for-linux#2612]
If the game overlay is enabled then certain games will not start under Fedora 19, 64bit. So far that includes "Thomas was alone" and "Organ trail: directors cut".

It may be some incompatibility with an update in Fedora 19 (which is currently beta, pending release in the coming weeks), since it used to work around three weeks ago.

The issue appears both in the latest beta client (as of today, 22nd of June) and in the latest stable one. It also doesn't cause all games to fail, ie. I tried to launch "The Cave" with the overlay enabled, and it worked fine.

I have attempted to remove the runtime directory to force a reinstall of that,it did not help. Nor did running steam as 'linux32 steam' to ensure it wasn't the new 64bit overlay stuff making it confused.

The problem manifests itself as a hanging game. For instance, when I start "Thomas was alone" it opens up a maximized window, which is black, and then proceeds to just hang there indefinitely - until I kill the process. There's no noteworthy output from the games in a terminal (same output with and without the overlay enabled). I have also attempted to disconnect my gamepad, in case that had anything to do with it (at least Thomas was alone used it), but that didn't have any effect either.

**Comment by kisak-valve** [comment]
Closing as upstream support for Fedora 19 has been discontinued. Additionally, the steam overlay on Fedora 25 does not have this issue with Thomas Was Alone.
