### ISSUE TITLE
Custom game launch commands broke

### ISSUE THREAD

**Issue by stevepoppers** [ValveSoftware/steam-for-linux#2614]
Linux Archtop 3.9.7-1-ARCH #1 SMP PREEMPT Thu Jun 20 22:45:32 CEST 2013 x86_64 GNU/Linux

baseboard-manufacturer: Acer
baseboard-product-name: JE50_HR
baseboard-version     : Base Board Version
system-manufacturer   : Acer
system-product-name   : Aspire 5750
system-version        : V1.21
bios-vendor           : Acer
bios-version          : V1.21
bios-release-date     : 08/09/2012

Bumblebee 3.2.1

Launching Steam games by modifying their command argument from within the Steam GUI to 'primusrun %command%' quit working after some recent update. Using 'optirun -b primus %command%' works as desired. Steam itself and other programs can be launched in the normal way, e.g. 'primusrun steam' results in Steam launching and games running without modified commands.

Some logs of launching steam and then TF2:

%command%
http://pastebin.com/L9qEcRGj

primusrun %command%
http://pastebin.com/sg08gy2s

optirun %command%
http://pastebin.com/hsFB5977

optirun -b primus %command%
http://pastebin.com/XwD2mCbk

**Comment by kisak-valve** [comment]
Closing per the last comment.
