### ISSUE TITLE
I end up in the floor after the SAS opens for the scrap yard in Half-life 2

### ISSUE THREAD

**Issue by arteymix** [ValveSoftware/steam-for-linux#2615]
It's at the end of Black Mesa East level when the scrapyard part ends loading.
![capture d cran de 2013-06-24 11 50 12](https://f.cloud.github.com/assets/1318477/696428/efef4d2c-dce5-11e2-88f5-ef3f76f2a48e.png)

**Comment by kisak-valve** [comment]
Has anyone seen this issue in the last couple years?

**Comment by arteymix** [comment]
Doubt it and I've recently (i.e. two days ago!) replayed this game and did not encounter the issue.
