### ISSUE TITLE
Steam High CPU Usage (100% core)

### ISSUE THREAD

**Issue by CommanderAlchemy** [ValveSoftware/steam-for-linux#2621]
<strong>Issue:</strong>
Steam consumes sometimes 100% of my CPU core from startup and will do so until I terminate Steam and restart it. Cannot cleanly reproduce it other than restarting my system and or start/stop steam from the terminal couple of times.

Pic :
http://i.imgur.com/fYn2fsG.png

Strace Steam : 
https://gist.github.com/CommanderAlchemy/5869631

Strace CIPCServer::Thr :
https://gist.github.com/CommanderAlchemy/5869748

<strong>Situation:</strong>
Computer launches with KDE.
Steam launches automagicaly to library.
CPU usage spikes and keeps that way.

Looking at the logs it got issues getting the time or something?

<strong> Steam System Info :</strong>
https://gist.github.com/CommanderAlchemy/4957992

**Comment by kisak-valve** [comment]
Hello @CommanderAlchemy, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by volca02** [comment]
I suffer from this issue. Steam under *wine* sits on at least 1 CPU core permanently (>=100% CPU usage). It does NOT happen though when switching the steam to offline mode. Only online steam exhibits this behavior. 

strace of the process when it does this: https://gist.github.com/volca02/0a89bf6b3f1d4a00025fcdbb24452f7b

**Comment by dcog989** [comment]
still an issue here in mid-2026 ... and it can cause terrible in-game performance if i do not 'fix' it by randomly interacting with the Steam app (usually I open Settings > Downloads then close Settings) which seems to stop the 100% CPU from a `steamwebhelper`

<img width="2167" height="742" alt="Image" src="https://github.com/user-attachments/assets/9f911c3e-507e-4ad7-af7d-7fdb9b8c24e0" />

https://github.com/ValveSoftware/steam-for-linux/issues/13455
