### ISSUE TITLE
Unable to connect to network after reinstall.

### ISSUE THREAD

**Issue by SayWhat1** [ValveSoftware/steam-for-linux#2626]
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
[2013-06-27 11:42:02] Startup - updater built Jun  6 2013 13:48:29
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
[2013-06-27 11:42:02] Verifying installation...
[2013-06-27 11:42:02] Verification complete
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
[0627/114234:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)
Installing breakpad exception handler for appid(steam)/version(1370553818_client)

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!

(steam:5989): GLib-GIO-WARNING **: g_simple_async_result_complete() called from wrong context!
Generating new string page texture 12: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311.30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 15: 384x256, total string texture memory is 835.58 KB
Generating new string page texture 18: 24x256, total string texture memory is 860.16 KB

When I start Steam like this from the command line it pulls up the following error:

Unable to connect to the Steam network. 'Offline Mode' is unavailable because there is no Steam login information stored on this computer.

You will not be able to use Steam until you can connect to the Steam network again.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
