### ISSUE TITLE
Self Updater Freezes

### ISSUE THREAD

**Issue by Mq-** [ValveSoftware/steam-for-linux#2627]
Self Updater freezes, when popped up to ask for a steam restart.
Click on any button ("RESTART STEAM", "CLOSE", "X") does not show any effect.

**Comment by kisak-valve** [comment]
Hello @Mq-, are you still experiencing this issue with an up to date system?

**Comment by Mq-** [comment]
Hi @kisak-valve, no I do not.

**Comment by kisak-valve** [comment]
Thanks for retesting @Mq-, closing.

**Comment by guglovich** [comment]
Join. If the update window hangs for a long time, for example at night, then the system hangs and also lags. After updating it is necessary to close the Steam client that freezes were gone.

System info: Arch + XFCE4 and AMDGPU + Mesa
