### ISSUE TITLE
[Achievements] [Big picture] Half Life2

### ISSUE THREAD

**Issue by BKPepe** [ValveSoftware/steam-for-linux#2632]
Hello,
When I playing through Big Picture on Linux game: Half Life 2
So it does not unlock achievements. Example: Revenge,Zero-Point Energy
When i playing through normal mode it unlock achievements.

My sys info
https://gist.github.com/BKPepe/5903680

**Comment by kisak-valve** [comment]
Hello @BKPepe, if you see this issue again, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker (or contact the devs of the affected game).
