### ISSUE TITLE
Slow Download Speed After Last Update(s)

### ISSUE THREAD

**Issue by jeffisabelle** [ValveSoftware/steam-for-linux#2645]
First, sorry for asking a noobish question on the bug tracker but I'm having really difficult time on downloading games today.

I have read and tried everything stated on here;
https://support.steampowered.com/kb_article.php?ref=1456-EUDN-2493

I don't see anything wrong on my console output. 
http://paste.ubuntu.com/5848041/

I haven't been using steam for a while, I fire up it today to buy L4D2, it made some updates (I'm not sure how many updates steam got last week), I've also updated ubuntu itself today. 

After getting steam running and downloading almost 1gig of L4D2, the speed got really slow, I mean it drops to bytes per seconds. (Man, I could count the 1-0 bits that is downloading on that speed)  

Then, I've tried everything I could find. I disabled my firewall on the router, I've reinstalled steam-launcher, I've deleted already downloaded content and tried to reinstall, I've changed download region from settings to several options. I've rebooted my machine and my modem several times. I've removed/moved some of the fancy .blob and .vdf files as suggested on the internet. 

I thought this could be an issue with L4D2 itself, because it's free to play weekend etc. But I made 2 of my friends to buy this game just to support steam on linux and they were downloading just fine. Their downloads have finished hours ago, mine still says 'time remaining: 35 days'

I'm really sorry to asking this, but I'm not able to track the issue. Anybody can direct me? 

note; I've downloaded several games on the same machine without problems some weeks ago. It just stopped to work. 

Thank's in advance.

**Comment by NoXPhasma** [comment]
I have the same behaviour here, 150 MBit down network but Steam gives me very low download speed. It jumps up to 1 Megabyte/s sometimes for a few seconds and then again down to somewhat like 10 - 100 KB/s. On Windows I get always full speed, up to 19 Megabyte/s on downloads.

Steam downloads are the only network related stuff which has such low speeds on my Linux machine.

I'm connected via LAN cable to my router, so there are no WLAN issues involved here.

**Comment by kisak-valve** [comment]
Hello @jeffisabelle, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by tr37ion** [comment]
Personally, I can't verify against Windows anymore. I didn't experience this behaviour of dropping bandwidth for quite some time. I would say it is fixed.
