### ISSUE TITLE
UI elements' borders in Big Picture Mode are shifted to right

### ISSUE THREAD

**Issue by vbuell** [ValveSoftware/steam-for-linux#2651]
Blue-glowing borders that widgets like buttons and windows has are not aligned correctly. They are shifted to the top-right so the gap between the widget's panel itself and the border became visible.

![2013-07-07-200321_1920x1200_scrot](https://f.cloud.github.com/assets/82733/758320/727b8b50-e729-11e2-8c03-af04323148d7.png)
![2013-07-07-200316_1920x1200_scrot](https://f.cloud.github.com/assets/82733/758319/7276e834-e729-11e2-92eb-6066a5c36230.png)

**Comment by kisak-valve** [comment]
Closing as this section of big picture mode has been redesigned some time ago.
