### ISSUE TITLE
Backup/Restore problem has returned

### ISSUE THREAD

**Issue by jedrivisser** [ValveSoftware/steam-for-linux#2652]
Steam backups are again not restoring correctly. This was corrected previously:

https://github.com/ValveSoftware/steam-for-linux/issues/2488

I tried backing up and restoring Shank 1 &2 and Zen Bound

**Comment by kisak-valve** [comment]
Hello @jedrivisser, are you still experiencing this issue with an up to date system?

**Comment by jedrivisser** [comment]
Don't know unfortunately, not using steam on linux anymore

**Comment by kisak-valve** [comment]
Thanks for the feedback @jedrivisser, if someone else is experiencing this issue, we'll use their issue report to track the issue. Closing.
