### ISSUE TITLE
Chat notification not opening new chat window

### ISSUE THREAD

**Issue by AnAkkk** [ValveSoftware/steam-for-linux#266]
I've searched and couldn't find the issue, so I guess it hasn't been posted here.

http://steamcommunity.com/app/221410/discussions/0/882965239655674529/

"If i get a chat notification from someone whom i don't currently have a chat window open for, it doesn't open a new window for that person so if i'm afk or something and someone sends an IM, i won't know that they did until i manually open chat windows for all of my friends until i find out whether someone had sent an IM or not. This is really annoying because i've missed a lot of messages because of it."

I am getting the same issue with Cinnamon.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2403 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.0-7-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11300902

Video Card:
    Driver:  NVIDIA Corporation GeForce 8800 GT/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 313.09
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x611
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18,62" x 11,65"  (21,93" diag)
                                        47,3cm x 29,6cm  (55,7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 512 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: 

Memory:
    RAM:  2002 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  33965 Mb
    Largest Free Hard Disk Block:  19512 Mb

Installed software:

Recent Failure Reports:

**Comment by cheetah2003** [comment]
This problem is not fixed.  Still happening in 2025.  Debian 12.9 with Cinnamon desktop.
