### ISSUE TITLE
Every time I open Steam I see a 0 bytes update for HL2 Episode One

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/steam-for-linux#2661]
The title pretty much explains it.
Here's a screenshot of the bug: http://i.imgur.com/3zllUwk.png
System info: https://gist.github.com/pizzadude/faad0fabae18720174ad

**Comment by kisak-valve** [comment]
Hello, has anyone seen this issue with an up to date client?

**Comment by kisak-valve** [comment]
Closing pending feedback.
