### ISSUE TITLE
Games stoped working

### ISSUE THREAD

**Issue by entropyencoded** [ValveSoftware/steam-for-linux#2665]
Today I bought complete set of Half-Life games and downloaded it. Every game worked perfectly. 
After some time, I tried to play Half-Life 2, but I could see only a black screen. Same thing happened to episodes, but with first Half-Life didn't even get a black screen, though I could see a process of "hl_linux".
I'm absolutely sure that it is a steam bug, because I can run half-life from command line (like "./hl.sh -steam")  and it works fine, but I would rather like to play it from steam.
I have reinstalled steam and games a few times, but it didn't help.
Here is my system info: http://pastebin.com/ZkuEWnnJ
And here is steam command line output: http://pastebin.com/GKiRkmLN

**Comment by kisak-valve** [comment]
Hello @entropyencoded, are you still experiencing this issue on an up to date system?

**Comment by enderleseb** [comment]
Try it with `sudo zypper dup`- I had the same/similar issue ([Link](https://github.com/ValveSoftware/steam-for-linux/issues/5033))

**Comment by kisak-valve** [comment]
Closing pending feedback.

Note: There is a more recent openSUSE issue which is similar to this being tracked at #5000.
