### ISSUE TITLE
Steam bug deps after install dpkg [Linux Mageia 3 x64 KDE]

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/steam-for-linux#2666]
Hi.
I use Steam and play well some game but when I want to try report bug in Dota 2 i running Steam in cosole and I see few error.

The first error was not installed "dpkg" dependence steam - Please install dependence to Steam.
Ok, I close steam and install dpkg on my steam. Next I open console and start steam and... I see more depending missing but some i check and it's installed on my system.

Here is my steam system spec: https://gist.github.com/xpris/e6a35a232370737a6f87

What I see after install dpkg:

[x@localhost ~]$ steam
which: no gnome-terminal in (/usr/bin:/bin:/usr/local/bin:/usr/X11R6/bin/:/usr/games:/usr/lib64/qt4/bin:/home/x/bin)
Package curl needs to be installed
Package jockey-common needs to be installed
Package python-apt needs to be installed
Package xterm needs to be installed
Package xz-utils needs to be installed
Package zenity needs to be installed
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Package libc6:i386 needs to be installed
Running Steam on mageia 3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
unlinked 0 orphaned pipes

(steam:2256): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",

(steam:2256): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
[0711/165410:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0711/165410:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)

*\* (steam:2256): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:2256): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Process 2256 created /x-ValveIPCSharedObjects5
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
roaming config store loaded successfully - 1502 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Adding license for package 0
Adding license for package 37
Adding license for package 64
Adding license for package 2481
Adding license for package 7706
Adding license for package 8089
Adding license for package 11005
Adding license for package 11793
Adding license for package 12329
Adding license for package 12558
Adding license for package 13602
Adding license for package 13616
Adding license for package 14633
Adding license for package 14909
Adding license for package 14938
Adding license for package 15136
Adding license for package 15638
Adding license for package 15919
Adding license for package 16020
Adding license for package 16222
Adding license for package 16342
Adding license for package 16360
Adding license for package 16549
Adding license for package 16640
Adding license for package 16767
Adding license for package 17250
Adding license for package 17607
Adding license for package 18629
Adding license for package 18769
Adding license for package 18773
Adding license for package 26703
Adding license for package 27322
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
ExecCommandLine: "/home/x/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 72: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 73: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 74: 32x256, total string texture memory is 475,14 KB
Generating new string page texture 75: 24x256, total string texture memory is 499,71 KB

Although the steam works. But now, even as I want to run it without the console, using the icon on the desktop it first opened to me a new console window and asked:

"Steam needs to install these additional packages:
         curl, jockey-common, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri: i386 libgl1-mesa-glx: i386 libc6: i386
x is not present in the file sudoers. This incident will be reported.
x is not present in the file sudoers. This incident will be reported.

x is not present in the file sudoers. This incident will be reported.
Press return to continue:
"

Any know how fix it?

EDIT:

I deinstall dpkg and I see:

"[x@localhost ~]$ steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on mageia 3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
unlinked 0 orphaned pipes

(steam:14729): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",

(steam:14729): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
[0711/194937:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0711/194937:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)
Installing breakpad exception handler for appid(steam)/version(1373503443_client)

*\* (steam:14729): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:14729): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files
"

**Comment by kisak-valve** [comment]
Hello @AngryPenguinPL, are you still experiencing this issue on an up to date system?

**Comment by AngryPenguinPL** [comment]
No. It fiexed few years ago :)

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
