### ISSUE TITLE
Steam menu freezing

### ISSUE THREAD

**Issue by txdv** [ValveSoftware/steam-for-linux#2668]
Sometimes the menues in Steam don't close properly and leave a rectangle on all ~~opengl~~ surfaces. I am talking about the grey filled one, the white border rectangle is from my screenshot tool scrot.

![](http://inightmare.org/~bentkus/images/screenshots/2013-07-11-225653_410x683_scrot.png)

**Comment by kisak-valve** [comment]
Hello @txdv, are you still experiencing this issue with an up to date system?

**Comment by txdv** [comment]
I haven't experienced them in a while for like multiple years, since the report is 4 years old....

**Comment by kisak-valve** [comment]
Thanks for the feedback @txdv.
