### ISSUE TITLE
Team Fortress 2 hangs on startup

### ISSUE THREAD

**Issue by vooolll** [ValveSoftware/steam-for-linux#2672]
When I try to open TF2 it starts hanging and some times not loading at all. It seems to be as this issue https://github.com/ValveSoftware/Source-1-Games/issues/102. When I switch for power saving gpu it starts loading but steal too long and in game it has bad performance. Installed latest driver for Ubuntu 13.4 (generated by amd client)

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1600 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-26-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7600G

```
Driver Version:  4.2.12217 Compatibility Profile Context 12.104
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6841
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  5352 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  698309 Mb
    Largest Free Hard Disk Block:  635408 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as per the last comment.
