### ISSUE TITLE
Counterstrike does not finish downloading

### ISSUE THREAD

**Issue by plakkies** [ValveSoftware/steam-for-linux#2676]
I have installed Ubuntu and Steam. Steam started downloading counterstrike but has stuck on 97%. It has been like this for several days.
I have searched the forums and the support site but cant find a solution. 

I contacted Steam support and they told me to reset steam which resulted in it getting updates again then they asked that I rename my steam apps folder so that counter strike could be re downloaded. They have now asked that I put the problem here as none of the above solved the problem.

Thanks for any help that you can give.

**Comment by kisak-valve** [comment]
Hello @plakkies, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
