### ISSUE TITLE
Steam freezes and locks mouse input

### ISSUE THREAD

**Issue by vendrillionQ** [ValveSoftware/steam-for-linux#2677]
Hi, this bug have been around since Steam for Linux was released and still exits so I think that this bug isn't still discovered.

I have fully updated Ubuntu 12.04 64-bit and AMD 6950 grapichs card with latest stable drivers from AMD website. This bug exits with all AMD drivers offered by Ubuntu 12.04 and at least with newest drivers (beta and stable) from AMD website.

Here's the bug: First Steam works just perfectly but after some time of usage (something like 10-15 minutes) Steam just stops responding mouse and keyboard and only way to solve this is close Steam via ctrl+f4 or via system monitor by terminating Steam process. During Steams unresponsivess my computer mouse stops working with other applications too but keyboard still works. This bug makes Steam for Linux pretty useless for me since I have to kill and restart it all the time. Btw sorry for my english. I wish that you can still understand what I want to tell you :)

Here's my terminal input during some random Steam usage which ends to bug mentioned above:

user@PC:~$ steam
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
user@PC:~$ steam
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
[0713/173958:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
local (potentially out of sync) copy of roaming config loaded - 13329 bytes.
roaming config store loaded successfully - 13329 bytes.
migrating temporary roaming config store
Adding license for package 0
Adding license for package 36
Adding license for package 156
Adding license for package 218
Adding license for package 402
Adding license for package 403
Adding license for package 451
Adding license for package 515
Adding license for package 636
Adding license for package 773
Adding license for package 965
Adding license for package 980
Adding license for package 1045
Adding license for package 1427
Adding license for package 1465
Adding license for package 1579
Adding license for package 1602
Adding license for package 1774
Adding license for package 1787
Adding license for package 1793
Adding license for package 2481
Adding license for package 2644
Adding license for package 3083
Adding license for package 4282
Adding license for package 4639
Adding license for package 4678
Adding license for package 6098
Adding license for package 6381
Adding license for package 6442
Adding license for package 6749
Adding license for package 7175
Adding license for package 7410
Adding license for package 7432
Adding license for package 7477
Adding license for package 7587
Adding license for package 7594
Adding license for package 7706
Adding license for package 7877
Adding license for package 8009
Adding license for package 8183
Adding license for package 8186
Adding license for package 8201
Adding license for package 8462
Adding license for package 8535
Adding license for package 8538
Adding license for package 8846
Adding license for package 8861
Adding license for package 8886
Adding license for package 11072
Adding license for package 11089
Adding license for package 11612
Adding license for package 11707
Adding license for package 11728
Adding license for package 11734
Adding license for package 11793
Adding license for package 11856
Adding license for package 11920
Adding license for package 12084
Adding license for package 12210
Adding license for package 12225
Adding license for package 12248
Adding license for package 12249
Adding license for package 12252
Adding license for package 12255
Adding license for package 12370
Adding license for package 12393
Adding license for package 12517
Adding license for package 12521
Adding license for package 13054
Adding license for package 13353
Adding license for package 13503
Adding license for package 13602
Adding license for package 13801
Adding license for package 13992
Adding license for package 14335
Adding license for package 14562
Adding license for package 14633
Adding license for package 14786
Adding license for package 14842
Adding license for package 14870
Adding license for package 14977
Adding license for package 15371
Adding license for package 15479
Adding license for package 15596
Adding license for package 15919
Adding license for package 16020
Adding license for package 16249
Adding license for package 16342
Adding license for package 16359
Adding license for package 16360
Adding license for package 16521
Adding license for package 16531
Adding license for package 16589
Adding license for package 16640
Adding license for package 16675
Adding license for package 16724
Adding license for package 16831
Adding license for package 16889
Adding license for package 17111
Adding license for package 17226
Adding license for package 17879
Adding license for package 18018
Adding license for package 18082
Adding license for package 18191
Adding license for package 18207
Adding license for package 18221
Adding license for package 18358
Adding license for package 18629
Adding license for package 18773
Adding license for package 25518
Adding license for package 26380
Adding license for package 26817
Adding license for package 26827
Adding license for package 27530
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
ExecCommandLine: "/home/user/.local/share/Steam/ubuntu12_32/steam"
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Opening joystick X360 Wireless Controller
Generating new string page texture 73: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 76: 32x256, total string texture memory is 1.52 MB
Generating new string page texture 77: 8x256, total string texture memory is 1.53 MB
Generating new string page texture 83: 64x256, total string texture memory is 1.60 MB
Generating new string page texture 84: 128x256, total string texture memory is 1.73 MB
Generating new string page texture 86: 128x256, total string texture memory is 1.86 MB
Generating new string page texture 87: 384x256, total string texture memory is 2.25 MB
Generating new string page texture 88: 256x256, total string texture memory is 2.51 MB
Generating new string page texture 89: 128x256, total string texture memory is 2.65 MB
System startup time: 10.08 seconds
Generating new string page texture 91: 48x256, total string texture memory is 2.70 MB
Generating new string page texture 110: 24x256, total string texture memory is 2.72 MB
Generating new string page texture 111: 512x256, total string texture memory is 3.24 MB
Running Steam on ubuntu 12.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/user/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/user/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 114: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 115: 64x256, total string texture memory is 3.31 MB
Generating new string page texture 136: 256x256, total string texture memory is 3.57 MB
Generating new string page texture 137: 128x256, total string texture memory is 3.70 MB
[0713/174342:ERROR:reference_audio_renderer.cc(46)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnCreated(media::AudioOutputController_)
[0713/174342:ERROR:reference_audio_renderer.cc(50)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPlaying(media::AudioOutputController_)
[0713/174342:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174342:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174348:ERROR:reference_audio_renderer.cc(46)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnCreated(media::AudioOutputController_)
[0713/174348:ERROR:reference_audio_renderer.cc(50)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPlaying(media::AudioOutputController_)
[0713/174348:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174348:ERROR:reference_audio_renderer.cc(46)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnCreated(media::AudioOutputController_)
[0713/174348:ERROR:reference_audio_renderer.cc(50)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPlaying(media::AudioOutputController_)
[0713/174348:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174352:ERROR:reference_audio_renderer.cc(54)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPaused(media::AudioOutputController_)
[0713/174352:ERROR:reference_audio_renderer.cc(54)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPaused(media::AudioOutputController_)
[0713/174352:ERROR:reference_audio_renderer.cc(54)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPaused(media::AudioOutputController_)
[0713/174401:ERROR:reference_audio_renderer.cc(46)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnCreated(media::AudioOutputController_)
[0713/174401:ERROR:reference_audio_renderer.cc(50)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPlaying(media::AudioOutputController_)
[0713/174401:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174407:ERROR:reference_audio_renderer.cc(54)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPaused(media::AudioOutputController_)
ExecSteamURL: "steam://open/friends"
[0713/174521:ERROR:reference_audio_renderer.cc(46)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnCreated(media::AudioOutputController_)
[0713/174521:ERROR:reference_audio_renderer.cc(50)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPlaying(media::AudioOutputController_)
[0713/174521:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0713/174524:ERROR:reference_audio_renderer.cc(54)] Not implemented reached in virtual void media::ReferenceAudioRenderer::OnPaused(media::AudioOutputController*)
Generating new string page texture 152: 16x256, total string texture memory is 3.72 MB
[0713/174709:WARNING:backend_impl.cc(1930)] Destroying invalid entry.
[0713/174709:WARNING:backend_impl.cc(1930)] Destroying invalid entry.
unlinked 2 orphaned pipes
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 18597 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 8 multi object alertable sleeps
[2013-07-13 17:39:57] Startup - updater built Jul  9 2013 17:43:28
[2013-07-13 17:39:57] Verifying installation...
[2013-07-13 17:39:57] Verification complete
Shutting down. . .
[2013-07-13 17:47:35] Shutdown

I would really appreciate if somebody have some fix for my problem

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been a video driver issue from 2013. If anyone is still experiencing this issue with an up to date system, please open a new issue report.

**Comment by bertvandepoel** [comment]
This still happens. Ubuntu 18.04 with Nvidia 460.80 drivers here. Often have to unplug and replug my mouse to gain control again. Happens when Steam is open but while not playing a game. Sometimes also causes my keyboard to reinitialize (I see numpad flicker off and on again two times), which can cause key sticking (for example ctrl+tab in a browser window, really annoying).

I have no idea how to debug this though. It's WEIRD.

**Comment by bringerer** [comment]
I have this issue now as well on my Pop OS. 
22.04 LTS x86_64,
Kernel: 6.6.10-76060610-generic
GPU: AMD ATI Radeon RX Vega 56/64

Randomly on start of steam app my mouse would lock at some specific location of the screen where steam app is running in. (i have two displays)

When i try to move the mouse pointer it reacts and wishes to move but it behaves like ti is pulled magnetically to the same spot and flickers. 
When i manage to pull pointer off to another screen it just reset it back to steam app. 

Really annoying.
