### ISSUE TITLE
"jumplist" configuration on GNU/Linux

### ISSUE THREAD

**Issue by hobarrera** [ValveSoftware/steam-for-linux#2684]
The interface tab in the settings menu has a "Set taskbar menu/jumplist preferences" button.
This text does not apply to linux, since there is no jumplist (which is a windows 7-only feature).

This button should read "taskbar menu" on non-windows builds.

**Comment by kisak-valve** [comment]
Closing as this was changed some time ago.

**Comment by hobarrera** [comment]
Thanks!
