### ISSUE TITLE
Valve games launch to black screen, non valve games do not launch if game overlay enabled

### ISSUE THREAD

**Issue by kerpderp** [ValveSoftware/steam-for-linux#2686]
Hello,

All valve games do not properly load if you allow steam to have overlay enabled. Issue started shortly after a recent steam update. Games will not even start a process, but rather load a black screen that results in the screen needing to be killed. Subsequently, non-steam games will stay on splash screens and never load or do nothing if they lack a splash screen. Disabling overlay resolves the issue. However, once the games do launch it is worth noting that they are laggy and generally play very poorly in comparison to prior to this issue.

System as follows:
Fedora 19 running 64bit version, steam system info:

Processor Information:
Vendor: AuthenticAMD
Speed: 3479 Mhz
6 logical processors
6 physical processors
HyperThreading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Unsupported
SSE4a: Supported
SSE41: Unsupported
SSE42: Unsupported

Network Information:
Network Speed: 

Operating System Version:
"Fedora release 19 (Schrödinger’s Cat)" (64 bit)
Kernel Name: Linux
Kernel Version: 3.9.9-302.fc19.x86_64
X Server Vendor: Fedora Project
X Server Release: 11402000
X Window Manager: KWin
Steam Runtime Version: steam-runtime-release-i386_2013-06-28

Video Card:
Driver: NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

Driver Version: 4.3.0 NVIDIA 325.08
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1081
Number of Monitors: 2
Number of Logical Video Cards: 2
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 3600 x 1080
Primary Display Size: 20.91" x 11.77" (23.98" diag)
53.1cm x 29.9cm (60.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1280 MB
Supported MSAA Modes: 2x 4x 8x 16x 

Sound card:
Audio device: CA0106

Memory:
RAM: 12018 Mb

Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 653702 Mb
Largest Free Hard Disk Block: 320503 Mb

Installed software:

Recent Failure Reports:

details from console when games are launched and overlay enabled:

[wizord@Serenity-DT ~]$ steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on fedora 19 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 12398 with name 0eBlobRegistryMutex_7E5114644D8974AB306BE3BA9498BD6C
removing stale semaphore last operated on by process 12398 with name 0eBlobRegistrySignal_7E5114644D8974AB306BE3BA9498BD6C
removing stale semaphore last operated on by process 12398 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 12398 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
[0714/105802:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
Installing breakpad exception handler for appid(steam)/version(1373418487_client)

(steam:12767): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(steam:12767): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1373418487_client)

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.                                      

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.                                      

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:12767): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Adding license for package 0
Adding license for package 1
Adding license for package 11
Adding license for package 25
Adding license for package 518
Adding license for package 636
Adding license for package 1260
Adding license for package 1290
Adding license for package 1579
Adding license for package 2242
Adding license for package 2294
Adding license for package 4067
Adding license for package 4314
Adding license for package 6098
Adding license for package 6254
Adding license for package 6330
Adding license for package 6516
Adding license for package 7207
Adding license for package 7877
Adding license for package 8500
Adding license for package 11463
Adding license for package 11692
Adding license for package 12361
Adding license for package 14335
Adding license for package 16549
roaming config store loaded successfully - 2422 bytes.
migrating temporary roaming config store
removing stale semaphore last operated on by process 12398 with name 0eBlobRegistryMutex_1C7E32D508F7B654B7EA9BD8D1E22B88
removing stale semaphore last operated on by process 12398 with name 0eBlobRegistrySignal_1C7E32D508F7B654B7EA9BD8D1E22B88
Installing breakpad exception handler for appid(steam)/version(1373418487_client)
ExecCommandLine: "/home/wizord/.local/share/Steam/ubuntu12_32/steam"

*\* (steam:12767): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/1 settings: (1) type

*\* (steam:12767): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/2 settings: (1) type
Generating new string page texture 84: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 85: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 86: 32x256, total string texture memory is 475.14 KB
Generating new string page texture 87: 64x256, total string texture memory is 540.67 KB
Generating new string page texture 88: 8x256, total string texture memory is 548.86 KB
System startup time: 5.17 seconds
Running Steam on fedora 19 64-bit
STEAM_RUNTIME has been set by the user to: /home/wizord/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/wizord/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 136: 128x256, total string texture memory is 679.94 KB
Generating new string page texture 137: 256x256, total string texture memory is 942.08 KB
Generating new string page texture 139: 384x256, total string texture memory is 1.34 MB
Generating new string page texture 140: 512x256, total string texture memory is 1.86 MB
Generating new string page texture 141: 24x256, total string texture memory is 1.88 MB
Generating new string page texture 142: 128x256, total string texture memory is 2.02 MB
Generating new string page texture 143: 2048x256, total string texture memory is 4.11 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 144: 128x256, total string texture memory is 4.24 MB
Generating new string page texture 147: 256x256, total string texture memory is 4.51 MB
CAPIJobRequestUserStats - Server response failed 2
Game update: AppID 223530 "Left 4 Dead 2 Beta", ProcID 12879, IP 0.0.0.0:0
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130709174336_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
[0714/105811:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 223530
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197973607467 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197973607467
[0714/105814:ERROR:resource_bundle.cc(411)] Failed to load /home/wizord/.local/share/Steam/SteamApps/common/Left 4 Dead 2 Beta/cef_gtk.pak
Some features may not be available.
[0714/105815:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1373418487_client)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by mooninite** [comment]
I am not experiencing this issue any longer and I haven't for a long time. Apologies for not providing an update sooner.

**Comment by kisak-valve** [comment]
Thanks for the feedback @mooninite, closing.
