### ISSUE TITLE
Game (STEAM) disappeared from my account (GNU / Linux)

### ISSUE THREAD

**Issue by antiyanki** [ValveSoftware/steam-for-linux#2687]
I bought three games to Steam (big mistake I think).
One is killing floor (with which I have no problem).
The others are are left 4 Dead 2 for Linux. One of them took up 13GB in downloading the other just 4 (I think).
By downloading the first one (the biggest) play as well ... but to download the second two are absent. I offered to buy them ... BUT HOW PEOPLE EXPLAIN uselessly STEAM, the game I bought.
You will have a reference solution or the problem.
From already thank you very much.
(This message was translated by google)

**Comment by kisak-valve** [comment]
There does not appear to be enough information here to pursue this further. Closing pending feedback.
