### ISSUE TITLE
incorrect nVidia driver detection

### ISSUE THREAD

**Issue by mxdpeep** [ValveSoftware/steam-for-linux#2692]
Popup shows I have old drivers installed.

![selection_003](https://f.cloud.github.com/assets/75358/805299/9659074a-ee23-11e2-94fb-301de4261167.png)

However this is not true.

![screenshot from 2013-07-16 16 26 17](https://f.cloud.github.com/assets/75358/805306/bdaa847c-ee23-11e2-8c66-7b4342035fcf.png)

(my driver was manually installed using nVidia binary package from CLI)

**Comment by kisak-valve** [comment]
This would be the expected behavior of anything checking the package manager for a driver's version and the package manager has been bypassed by nvidia's installer. Additionally, video driver update checks are no longer provided by steam.
