### ISSUE TITLE
CS:S crashes. reverse logo

### ISSUE THREAD

**Issue by trow** [ValveSoftware/steam-for-linux#2699]
A screen like than appears and then crash and exit game.
![css](https://f.cloud.github.com/assets/5037587/817912/00d9df1c-ef83-11e2-95c6-a7ad5f33119e.png)
![css2](https://f.cloud.github.com/assets/5037587/817951/9ad11bca-ef84-11e2-9c1b-16a7f5f95904.png)
The same problem on portal.

**Comment by kisak-valve** [comment]
Hello @trow, if you are still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
