### ISSUE TITLE
Steam crashes

### ISSUE THREAD

**Issue by VlasovRoman** [ValveSoftware/steam-for-linux#2700]
[Google.Translate]

When I play everything TF2 works as it is necessary. I talk to other players, etc. But after a while when pressing the button of activation of a microphone game begins terribly laging.
As it appears, Steam falls. The problem is observed on two different computers with Ubuntu 13.10 and Ubuntu 13.04 of different architecture.

/.steam/root/steam.log

DebugAssert, Name: ?, Line: 1106, Expr: "open for read/write failed in CreateFile" && !pchErr, File: /home/buildbot/buildslave_steam/steam2_rel_beta_linux/build/Projects/GazelleProto/Client/Engine/../../../Common/Misc/PosixWin32.cpp

CsComm Session Jul-18-2013 08:57:25.823 [2962176832] ReconnectThread (2962176832) Starting
CsComm Session Jul-18-2013 09:50:05.022 [2962176832] ReconnectThread (2962176832) Told to exit

CsComm Session Jul-18-2013 09:50:40.345 [2913786688] ReconnectThread (2913786688) Starting

CsComm Session Jul-18-2013 16:45:27.311 [2911968064] ReconnectThread (2911968064) Starting

**Comment by kisak-valve** [comment]
Hello @VlasovRoman, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
