### ISSUE TITLE
[Important - regarding all games] Games on partitions other then boot don't run well

### ISSUE THREAD

**Issue by Aviramk** [ValveSoftware/steam-for-linux#2701]
I think I discovered the cause for the problems I had with some games. I noticed all the games that I have problems running well are in a library placed in other partition (not boot). The problems were that after 1 run of each game, they wont start anymore and crash on launch, then I moved them to the boot partition library and they ran well.
Also I tried moving a game that always worked good, Dota 2 Test to the other partition (not boot) and game started having lags and stuttering.. when I placed it back on the home library it ran smooth and good.

**Comment by kisak-valve** [comment]
Hello @Aviramk, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
