### ISSUE TITLE
FPS Drop on L4D2

### ISSUE THREAD

**Issue by LinuxEnthusiast** [ValveSoftware/steam-for-linux#2706]
Normally my settings for l4d2 are set to high with AA off. On starting the game up for the first time whenever I play a game of any mode I get a drastic FPS drop.

![c1m1_hotel0003](https://f.cloud.github.com/assets/4052281/828743/668f0050-f0bc-11e2-989a-dd37c99bb126.jpg)

This is remedied by going to the video settings and switching everything down to 'low',  and hitting done. It freezes for around 10 seconds and then comes back. I can then go straight back into the settings and put everything back up to high. Going back into a game brings my FPS to it's normal 55-60.

So when I start the game up I always go to the settings, put everything down low, hit done, go back in, put everything back up to high and resume playing as normal.

I'm on Ubuntu 13.04, using a six core AMD CPU, a Radeon 7790 with 13.6 blob driver and the Unity DE.

**Comment by kisak-valve** [comment]
Closing as video driver quality from 2013 is no longer relevant.
