### ISSUE TITLE
Unity does not allow Source Games to use the whole screen in -noborder -windowed mode. 

### ISSUE THREAD

**Issue by NothingMuchHereToSay** [ValveSoftware/steam-for-linux#2709]
This is what happens when I run TF2 with those two commands:

http://i.imgur.com/ZoVYyhq.jpg

Ubuntu 13.10, Nvidia 319.32 drivers, 5GB RAM, Core 2 Quad.

**Comment by kisak-valve** [comment]
Closing pending feedback.
