### ISSUE TITLE
Resume problem: discards last downloads and starts downloading from begining

### ISSUE THREAD

**Issue by sajjadG** [ValveSoftware/steam-for-linux#2710]
Time to time my Linux steam client discard the last downloaded files and starts all over again from the 0Kb. it really hurt when you want to download a large game and it discard about 6GB of your download.

I am using ubuntu 13.04 with kernel 3.8.0-21-generic multiarch enable. I installed from `steam_latest.deb` from steam site (the one is mentioned in ubuntu wiki).

**Comment by kisak-valve** [comment]
Hello @sajjadG, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
