### ISSUE TITLE
Dungeon Defender - couldn't set full screen mode on Fedora 19 x86-64

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#2717]
When I try change it pop's error windows with message "Assertion failure at MacResizeOpenGLViewFullScreen"

Demonstration: https://docs.google.com/file/d/0B0nwzlfiB4aQdWhaWlI0ZzBEVkk/edit?usp=sharing

System Info:

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3401 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 19 (Schrödinger’s Cat)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.9.9-302.fc19.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11402000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 9.2.0-devel
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  14994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  2816556 Mb
    Largest Free Hard Disk Block:  707372 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @NTMan, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
