### ISSUE TITLE
Steam Linux- L4D2 random crashes (segfault) at the end of map loading

### ISSUE THREAD

**Issue by elthommy** [ValveSoftware/steam-for-linux#2719]
Hi everyone :-)
My L4D2 tends to crash randomly when joining a game.
I will try to explain it better: sometimes when I join an online game, it crashes with segfault and coredump. But sometimes the same map load fine, sometime it happen for official maps, sometime for workshop maps, but I couldn't narrow the issue to a specific map, as I was able to play all of them, it jsut that sometime for an unknow reason it just crash.
When the issue happen: it happen at the end of the loading of the map, just before being able to play a character.
I could see in the logs that Steam was unable to uplaod my minidumps. Therefore I attach them separatly => You can downlaod them from here: https://www.wuala.com/elthommy/Public/Share_Github_steam/dumps/?key=rUidxALCNsDI

Please don't hesitate to contact me if you need more information or have any questions 

Cheers
Thomas (elthommy)

**Comment by kisak-valve** [comment]
Hello, if anyone is still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/) issue tracker and make sure to include the server's ip address to help reproduce the issue.
