### ISSUE TITLE
The Polynomial is missing two required libraries

### ISSUE THREAD

**Issue by jrstjohn** [ValveSoftware/steam-for-linux#2721]
The Polynomial is missing two required libraries. This game requires `libIlmImf.so.6` and `libHalf.so.6`.

`libIlmImf.so.6` is provided by openexr version 1.7.0.
`libHalf.so.6` is provided by ilmbase 1.0.2.
Both of these can be found here: http://www.openexr.com/downloads.html

Arch Linux ships openexr 2.0.0 and ilmbase 2.0.0, which have received a soname bump (for example, ilmbase 2.0.0 provides `libHalf.so.10`).

> Processor Information:
>    Vendor:  GenuineIntel
>    Speed: 2267 Mhz
>    4 logical processors
>    2 physical processors
>    HyperThreading:  Supported
>    FCMOV:  Supported
>    SSE2:  Supported
>    SSE3:  Supported
>    SSSE3:  Supported
>    SSE4a:  Unsupported
>    SSE41:  Supported
>    SSE42:  Supported
> 
> Network Information:
>    Network Speed:  
> 
> Operating System Version:
>    "Arch Linux" (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.9.9-1-ARCH
>    X Server Vendor:  The X.Org Foundation
>    X Server Release:  11402000
>    X Window Manager:  Mutter (Muffin)
>    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28
> 
> Video Card:
>    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2
> 
>    Driver Version:  2.1 Mesa 9.1.5
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x8086
>    DeviceID:  0x46
>    Number of Monitors:  1
>    Number of Logical Video Cards:  1
>    Primary Display Resolution:  1600 x 900
>    Desktop Resolution: 1600 x 900
>    Primary Display Size: 15.04" x 8.46"  (17.24" diag)
>                                            38.2cm x 21.5cm  (43.8cm diag)
>    Primary VRAM Not Detected
> 
> Sound card:
>    Audio device: Intel IbexPeak HDMI
> 
> Memory:
>    RAM:  3756 Mb
> 
> Miscellaneous:
>    UI Language:  English
>    LANG:  en_US.utf8
>    Microphone:  Not set
>    Total Hard Disk Space Available:  161297 Mb
>    Largest Free Hard Disk Block:  52770 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved by the game dev.
