### ISSUE TITLE
Ghosting in tf2

### ISSUE THREAD

**Issue by Oscillope** [ValveSoftware/steam-for-linux#2724]
Occasionally in Team Fortress 2 the map and elements on it will ghost until the entire screen is white. The HUD and gun are still visible, as well as things like intelligence suitcases or carts depending on game mode. The issue seems to come back and resolve itself randomly.
![2013-07-19_00001](https://f.cloud.github.com/assets/2652071/837469/b3f1055e-f306-11e2-8eb2-2d2e64e69ab8.jpg)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
