### ISSUE TITLE
Half life 2 won't run

### ISSUE THREAD

**Issue by not83** [ValveSoftware/steam-for-linux#2726]
my other games work on my gaming computer. but when i click play on HL2 it just does nothing or if i click a lot it will say something about cloud sync also if i click a lot it might say already running. please fix quickly so i can play more before studies start again. it has only done this today. turning off cloud sync getting better internet connection and upgrading to beta does not fix this problem.

**Comment by kisak-valve** [comment]
Closing as video driver quality from 2013 is no longer relevant.
