### ISSUE TITLE
Steam Client - Crashed While playing game and will not start back up.

### ISSUE THREAD

**Issue by blu006** [ValveSoftware/steam-for-linux#2728]
Hello all,

My steam setup is a little custom (I ran a script to get it working on Debian, but understand some of the internal workings of the script.)

But it should have the same libraries as a user on Ubuntu should (other than graphics libraries, but I don't think that's where the problem is)

So, to give you guys the proper debugging info, I have run a few things: a simple dump of console output, a bit of gdb output, and a hardinfo report.  I will paste the console output and gdb output.  The hardinfo report is available on request (it's a bit large!).
#### 

; Begin Console output
#### 

brandon@gravylap:~$ steam
Running Steam on debian 7 64-bit
STEAM_RUNTIME is enabled automatically
[2013-07-22 23:16:11] Startup - updater built Jul  9 2013 17:43:28
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[2013-07-22 23:16:11] Checking for update on startup
[2013-07-22 23:16:11] Checking for available updates...
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[2013-07-22 23:16:11] Download skipped: /client/steam_client_ubuntu12 version 1374006490, installed version 1374006490
[2013-07-22 23:16:11] Error: Failed to verify package manifest.
[2013-07-22 23:16:11] Verifying installation...
[2013-07-22 23:16:11] Verification complete
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 11919 with name 0eBlobRegistryMutex_CA2116F4E518E7F2773F63519BEA1879
removing stale semaphore last operated on by process 11919 with name 0eBlobRegistrySignal_CA2116F4E518E7F2773F63519BEA1879
removing stale semaphore last operated on by process 11919 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 11919 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[0722/231612:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130722231611_1.dmp
/home/brandon/.local/share/Steam/steam.sh: line 704: 12032 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
brandon@gravylap:~$ Finished uploading minidump (out-of-process): success = no
error: HTTP response code said error
#### 

; End console output
#### 
#### 

; Begin GDB
#### 

brandon@gravylap:~/.local/share/Steam/debian_bin$ DEBUGGER=gdb ./steam
Running Steam on debian 7 64-bit
STEAM_RUNTIME is enabled automatically
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /home/brandon/.local/share/Steam/ubuntu12_32/steam...(no debugging symbols found)...done.
"/home/brandon/.local/share/Steam/" is not a core dump: Is a directory
(gdb) run
Starting program: /home/brandon/.local/share/Steam/ubuntu12_32/steam 
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[2013-07-22 23:17:59] Startup - updater built Jul  9 2013 17:43:28
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[2013-07-22 23:17:59] Checking for update on startup
[2013-07-22 23:17:59] Checking for available updates...
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[New LWP 12292]
[2013-07-22 23:18:00] Download skipped: /client/steam_client_ubuntu12 version 1374006490, installed version 1374006490
[2013-07-22 23:18:00] Error: Failed to verify package manifest.
[2013-07-22 23:18:00] Verifying installation...
[2013-07-22 23:18:00] Verification complete
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 12171 with name 0eBlobRegistryMutex_CA2116F4E518E7F2773F63519BEA1879
removing stale semaphore last operated on by process 12171 with name 0eBlobRegistrySignal_CA2116F4E518E7F2773F63519BEA1879
removing stale semaphore last operated on by process 12171 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 12171 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[New LWP 12299]
[0722/231800:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[New LWP 12310]
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1374006490_client)

Program received signal SIGSEGV, Segmentation fault.
0xf70c1d7c in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
(gdb) bt
#0  0xf70c1d7c in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#1  0xf70c1883 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#2  0xf70ab66f in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#3  0xf7097b6f in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#4  0xf71d5886 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#5  0xf71c5d10 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#6  0xf71c60ef in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#7  0xf71c9391 in ?? () from /usr/lib/i386-linux-gnu/dri/i965_dri.so
#8  0xef60025c in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#9  0xef5fe538 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#10 0xef5c8cbe in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#11 0xef5c90a8 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#12 0xf525934a in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/steamui.so
#13 0xf525d948 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/steamui.so
#14 0xef5f64db in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#15 0xef5f8432 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
---Type <return> to continue, or q <return> to quit---
#16 0xef6071e6 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/vgui2_s.so
#17 0xf4b43fd2 in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/steamui.so
#18 0xf4ac6ccd in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/steamui.so
#19 0xf4b2bd5c in ?? ()

   from /home/brandon/.local/share/Steam/ubuntu12_32/steamui.so
#20 0x08067c86 in RunSteam(int, char**, bool, bool) ()
#21 0x08050838 in main ()

(gdb) 
#### 

; End GDB output
#### 

If you guys need me to provide any more info, I would be more than willing to do so.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
