### ISSUE TITLE
Team Fortress 2 string format placeholders not always interpolated

### ISSUE THREAD

**Issue by Prinzhorn** [ValveSoftware/steam-for-linux#273]
It happened on two separate occasions.
1. When I just got killed it said `%NEMESIS_NAME%` (not sure if it was all caps) in the lower right corner. I guess the name of the player should have been there.
2. When I just got killed and I did more X than ever before (not quite sure what it was) it said `foo foo foo %1s% foo foo foo` where the "foo"s where actually text like "You did more damage than ever before", but the `%1s%` (or `%s1%`, not sure) was not interpolated. I guess it should have been replaced with the amount of damage (or whatever) I did.

I wasn't able to take screenshots because I wasn't fast enough.

Processor Information:
Vendor: GenuineIntel
Speed: 2401 Mhz
4 logical processors
2 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed:

Operating System Version:
Ubuntu 12.10 (64 bit)
Kernel Name: Linux
Kernel Version: 3.5.0-21-generic
X Server vendor: The X.Org Foundation
X Server release: 11300000

Video Card:
Driver: NVIDIA Corporation GeForce 610M/PCIe/SSE2
Driver Version: 4.2.0 NVIDIA 304.64
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1058
Number of Monitors: 1
Number of Logical Video Cards: 2
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.54" x 13.23" (26.97" diag)
59.8cm x 33.6cm (68.5cm diag)
Primary VRAM: 1023 MB

Sound card:
Audio device:

Memory:
RAM: 7847 Mb

Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 923882 Mb
Largest Free Hard Disk Block: 767533 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @Prinzhorn, if you are still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
