### ISSUE TITLE
Counter Strike running slow

### ISSUE THREAD

**Issue by garrett85** [ValveSoftware/steam-for-linux#2734]
I just re-installed my OS Mint-Ubuntu to the latest version and upon restarting Steam > Counte-Strike I found the game to play very slowly. I'm not sure if it's lag or dropping frames but I lean towards lag. I even deleted all local content and steam directories in my ~/home folder and reinstalled everything from scratch but ever since I re-installed/upgraded my OS, CS has ran very slowly. Any ideas? Please help, I love this game. My specs are below.

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 2000 Mhz
    1 logical processor
    1 physical processor
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RS780

```
Driver Version:  3.0 Mesa 9.1.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9616
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 16.14" x 9.06"  (18.50" diag)
                                        41.0cm x 23.0cm  (47.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  7734 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  234603 Mb
    Largest Free Hard Disk Block:  130060 Mb

Installed software:

Recent Failure Reports:
    Tue Jul 23 22:39:51 2013 GMT: file ''/tmp/dumps/assert_20130723173937_16.dmp'', upload yes: ''CrashID=bp-d2e090a7-5beb-43d0-ab76-a33142130723''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
