### ISSUE TITLE
Incorrect UI elements in full screen HTML 5 videos (BIG PICTURE MODE)

### ISSUE THREAD

**Issue by karmictoucan** [ValveSoftware/steam-for-linux#2735]
When you open video in the full screen mode there are scrolling bars, top bar, youtube interface, "More" button and "Steam" button present on the screen ![Screenshot 1](https://f.cloud.github.com/assets/3246385/851132/dcf5998e-f495-11e2-92fe-552f722b26a5.png) After few seconds(if you don't touch mouse, gamepad or keyboard), all interface elements, except from Top bar, disappear. ![Screenshot 2](https://f.cloud.github.com/assets/3246385/851160/32811428-f496-11e2-9890-fb9da89166c7.png) Also it is possible to "move" focus from video content with scroll bars, mouse or gamepad. ![Screenshot 3](https://f.cloud.github.com/assets/3246385/851176/8c7b5c68-f496-11e2-8cbe-7a2c013dadc1.png)  ![Screenshot 4](https://f.cloud.github.com/assets/3246385/851202/dd39fe70-f496-11e2-8ede-e599a54e6734.png)  ![Screenshot 5](https://f.cloud.github.com/assets/3246385/851235/5a75a34e-f497-11e2-9054-8a3aa3e91508.png)

**Comment by kisak-valve** [comment]
Closing as this appears to have been improved some time ago.
