### ISSUE TITLE
Need Package for install Steam el6

### ISSUE THREAD

**Issue by AbedSHP** [ValveSoftware/steam-for-linux#2736]
hi 
i install ... redhat 6.2
http://steamcommunity.com/app/221410/discussions/1/846939071258869580/
but ..!
need package 
steam-1.0.0.36-1.noarch requires glibc >= 2.15
steam-1.0.0.36-1.noarch requires zlib >= 1.2.3.3
steam-1.0.0.36-1.noarch requires openal-soft >= 1.13

now package used

install glibc >= 2.14
install zlib >= 1.2.3.29
install openal-soft >=is Not !

**Comment by kisak-valve** [comment]
The current steam client default configuration should use the steam-runtime variant of libraries if they are newer than what the system provides.

Feel free to reach out to your distro's package maintainer for steam if you wish to pursue this further.
