### ISSUE TITLE
Please port 'app_config_override' from Steam to Steamcmd

### ISSUE THREAD

**Issue by devicenull** [ValveSoftware/steam-for-linux#2737]
app_config_override - <appid> <key> <value> : Overrides app config

I've encountered some games that make their content only available for windows.  It would be nice to be able to override their setting and download the content on linux anyway (so I don't have to download it to a windows machine and copy it over).

This command already exists within the actual steam client, it's just not available in steamcmd.

**Comment by zkenj** [comment]
As someone running a dedicated game server in WINE for a Windows-only game, this would be highly appreciated.

**Comment by devicenull** [comment]
There's some third party software called 'depotdownloader' that we've been using for this.  It's a shame the official software doesn't support it.

**Comment by kisak-valve** [comment]
Adding [`+@sSteamCmdForcePlatformType windows`](https://developer.valvesoftware.com/wiki/SteamCMD#Cross-Platform_Installation) to your steamcmd command will provide the override requested.
