### ISSUE TITLE
Crash dumps failing to upload

### ISSUE THREAD

**Issue by epitron** [ValveSoftware/steam-for-linux#2738]
I've been experiencing a consistent crash in L4D2 for Linux.

I'll be playing the game, everything will be going fine, then the game will suddenly freeze, terminate, and then Steam will try to upload a crash dump, and fail.

Example:

```
Recent Failure Reports:
    Wed Jul 24 06:27:08 2013 GMT: file ''/tmp/dumps/crash_20130724014604_1.dmp'',
      upload no: ''HTTP response code said error''
    Fri Jul 26 05:11:11 2013 GMT: file ''/tmp/dumps/crash_20130726010328_1.dmp'',
      upload no: ''HTTP response code said error''
```

This happens almost every time that I play, usually after about 10-15 minutes, but sometimes after an hour.

When the game dumps out in this way, I noticed that the logs on my (dedicated) server show that I was dropped because of an authorization error.

I also get authorization errors in TF2 (which manifest themselves, not as crashes, but as my inventory disappearing, and an error dialog that says "cannot contact item server" when I try to view my inventory.)

I have a hunch that Steam is having an intermittent problem calling the Valve home base. I'm on a flaky wireless, so it's quite likely that TCP connections are periodically dying.

**Comment by kisak-valve** [comment]
Hello @epitron, are you still experiencing this issue on an up to date system?

**Comment by epitron** [comment]
Nope! It all runs smooth as silk now. Kudos!
