### ISSUE TITLE
Sound down and up in Steam Ubuntu 12.10

### ISSUE THREAD

**Issue by dianaharm** [ValveSoftware/steam-for-linux#2743]
Hi. I have a problem with steam in Ubuntu 12.10. When I start to play (for example Bastion Game) sound up and down without control. I updated sound libraries, and try launch steam SDL_AUDIODRIVER="pulseaudio" steam and SDL_AUDIODRIVER="alsa" steam, but don't fix the problem? Can someone help me?

**Comment by kisak-valve** [comment]
Hello @dianaharm, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
