### ISSUE TITLE
Steam crashes while browsing the game library[Debian 7]

### ISSUE THREAD

**Issue by Illasera** [ValveSoftware/steam-for-linux#2747]
Issue : Steam crashes when i go through the games in my library (using the arrow buttons), Steam crashes occurs after iterating through X amount of games, usually about ~20-30 games.

Can be reproduced by me and a friend that is also using debian 7.

Software info : 

Operating System and kernel: Linux 3.9-0.bpo.1-686-pae #1 SMP Debian 3.9.6-1~bpo70+1 i686
X.Org X Server version : 1.12.4
Steam : Not using Beta version, Using the version from July 30 2013

GPU info :

GPU - intel GMA 450
intel: Driver for Intel Integrated Graphics Chipsets: i810,
VESA: driver for VESA chipsets: vesa
intel(0): Integrated Graphics Chipset: Intel(R) G41
intel(0): Chipset: "G41"

Crash Info : 
steam.sh: line 704:  7861 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130730103629_1.dmp

**Comment by kisak-valve** [comment]
Hello @Illasera, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
