### ISSUE TITLE
Black screen on every game

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#2749]
I installed openSUSE 12.3 with "/swap", "/var", "/tmp" and "/home" encrypted. The driver version is 319.32.
The problem happens when "Steam Community In-Game" is enabled.

Console output:

junior@PC-Junior:~> steam
Running Steam on opensuse 12.3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 3869 with name 0eBlobRegistryMutex_71FCD51A4967003D61D885AFEB7352FC
removing stale semaphore last operated on by process 3869 with name 0eBlobRegistrySignal_71FCD51A4967003D61D885AFEB7352FC
removing stale semaphore last operated on by process 3869 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 3869 with name 0eSteamEngineLock

(steam:4545): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(steam:4545): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
[0727/192532:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0727/192532:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)

*\* (steam:4545): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:4545): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Installing breakpad exception handler for appid(steam)/version(1374006490_client)

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
roaming config store loaded successfully - 2329 bytes.
migrating temporary roaming config store
Adding license for package 0
Adding license for package 7
Adding license for package 37
Adding license for package 523
Adding license for package 609
Adding license for package 783
Adding license for package 980
Adding license for package 2319
Adding license for package 2481
Adding license for package 4415
Adding license for package 4466
Adding license for package 7932
Adding license for package 13054
Adding license for package 16222
Adding license for package 27531
Adding license for package 29082
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
ExecCommandLine: "/home/junior/.local/share/Steam/ubuntu12_32/steam"
Generating new string page texture 73: 1024x256, total string texture memory is 1.36 MB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 128x256, total string texture memory is 1.49 MB
Generating new string page texture 76: 32x256, total string texture memory is 1.52 MB
Generating new string page texture 82: 64x256, total string texture memory is 1.59 MB
Generating new string page texture 83: 128x256, total string texture memory is 1.72 MB
Generating new string page texture 84: 512x256, total string texture memory is 2.24 MB
Generating new string page texture 85: 256x256, total string texture memory is 2.51 MB
Generating new string page texture 86: 384x256, total string texture memory is 2.90 MB
System startup time: 6.84 seconds
Running Steam on opensuse 12.3 64-bit
STEAM_RUNTIME has been set by the user to: /home/junior/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/junior/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 110: 24x256, total string texture memory is 2.92 MB
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
Game update: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 4722, IP 0.0.0.0:0

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:4545): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Installing breakpad exception handler for appid(steam)/version(1374006490_client)
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20130709174336_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)

(gameoverlayui:4730): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(gameoverlayui:4730): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
[0727/192639:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0727/192639:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Using breakpad crash handler
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID: Caching Steam ID: 76561198042163203 [API loaded yes]
Steam_SetMinidumpSteamID: Setting Steam ID: 76561198042163203

(hl2_linux:4725): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(hl2_linux:4725): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
[0727/192642:ERROR:resource_bundle.cc(411)] Failed to load /home/junior/.local/share/Steam/SteamApps/common/Left 4 Dead 2/cef_gtk.pak
Some features may not be available.
[0727/192642:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0727/192642:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
/home/junior/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67: 4725 Killed ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

Game removed: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 4725

Generating new string page texture 133: 256x256, total string texture memory is 3.19 MB

Generating new string page texture 142: 128x256, total string texture memory is 3.32 MB

Game update: AppID 10 "Counter-Strike", ProcID 4822, IP 0.0.0.0:0

CAPIJobRequestUserStats - Server response failed 2

Using breakpad crash handler

Setting breakpad minidump AppID = 10

Forcing breakpad minidump interfaces to load

Looking up breakpad interfaces from steamclient

Calling BreakpadMiniDumpSystemInit

Looking up breakpad interfaces from steamclient

Calling BreakpadMiniDumpSystemInit

Steam_SetMinidumpSteamID: Caching Steam ID: 76561198042163203 [API loaded yes]

Steam_SetMinidumpSteamID: Setting Steam ID: 76561198042163203

/home/junior/.local/share/Steam/steam.sh: line 704: 4545 Terminated $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

**Comment by kisak-valve** [comment]
Hello @amarildojr, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by amarildojr** [comment]
You know, since 2013 drivers changed, games changed, and even my hardware changed, @kisak-valve.

Although I appreciate VALVe going back to these threads, it's not gonna do much to help people.

Cheers,
Amarildo
