### ISSUE TITLE
3D Performance Nvidia [Phoronix article]

### ISSUE THREAD

**Issue by ksthiele** [ValveSoftware/steam-for-linux#2755]
PC-BSD scored pretty well, especially in Xonotic, maybe you can investigate it together with Nvidia. I'd love to see the same scores on Linux :)

http://www.phoronix.com/scan.php?page=article&item=freebsd_win8_ubuntu&num=1

**Comment by kisak-valve** [comment]
Closing as general video driver performance from 2013 is no longer relevant.
