### ISSUE TITLE
Failed to install steam via Ubuntu Software Center (ubuntu 12.04.2 full updated) 

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2757]
Hello.
I want install skype ONLY via Ubuntu Software Center, I follow instructions :
"The Steam Client is available through the Ubuntu Software Center (USC). Run the USC, search for Steam, and install it"
Source : https://wiki.ubuntu.com/Valve

USC failed and show always this message :
W:Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/steam/ubuntu/dists/precise/main/binary-amd64/Packages The requested URL returned error: 401
, W:Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/steam/ubuntu/dists/precise/main/binary-i386/Packages The requested URL returned error: 401
, E:Some index files failed to download. They have been ignored, or old ones used instead.

I think than
Added by software-center; credentials stored in /etc/apt/auth.conf
https://private-ppa.launchpad.net/commercial-ppa-uploaders/steam/ubuntu

is dead/broken !

Steam can resolve this ??

**Comment by kisak-valve** [comment]
Closing as the Ubuntu Software Center has been discontinued.
