### ISSUE TITLE
Slowdown on big picture and some games - might be CPU

### ISSUE THREAD

**Issue by strattonbrazil** [ValveSoftware/steam-for-linux#2759]
I've always had really poor performance on some games.  Serious Sam takes minutes to load from launch.  Bastion takes a long time even getting passed the splash screen (where it explains the saving symbol).  I alt-tabbed out and see the game is taking 100% of the CPU, which seems crazy since it's just sitting there doing nothing.  In DOTA 2, when I launch, there's a big slowdown showing the animated Valve logo.  I've gotten into a mission once, but the framerate is in the 5's, I imagine.  I even loaded Big Picture and seem the framerate is rather low during transitions like it's chugging along.  

I decided to launch Portal and once I got into the game, I can play it at 1080p and it seems to have a pretty good framerate.  Can anyone give me some idea what is causing my games to run so slowly when many others seem to be having so much success?  

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2333 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-37-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  NVIDIA Corporation GeForce 8800 GTS/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x193
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                        60.0cm x 34.0cm  (68.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 320 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC889A

Memory:
    RAM:  7985 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  296422 Mb
    Largest Free Hard Disk Block:  225950 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Odds are this issue was related to the 320MB of VRAM which was available, as Big Picture mode is expected to need a bit more VRAM than the desktop client.

Closing as general video driver performance from 2013 is no longer relevant.
