### ISSUE TITLE
[Linux] Book of Unwritten Tales, consistent crashes

### ISSUE THREAD

**Issue by gmjck** [ValveSoftware/steam-for-linux#2761]
In the Linux version of The Book of Unwritten Tales, with Catalyst 13.6 beta or 13.8 beta, entering certain areas of the game causes a crash to desktop every time. This is a separate issue from the known crash to desktop associated with going to the Settings menu, which has a community fix.

The first place I noticed this was when Ivo enters McGuffin's house. The game crashes as soon as the new area has loaded, every time. I was running Catalyst 13.6 beta when this was occurring. Reverting to the Catalyst 13.4 (non-beta) driver resolved this.

After completing the game, I installed the Catalyst 13.8 beta driver, and now see the problem again. I no longer have a save file from just outside McGuffin's house, but I do have one save file from inside the Crypt, and one save file from just outside the Crypt (area with the Paladin). Every time I try to load the Crypt save file, the game crashes to the desktop as soon as the area is 100% loaded. Every time I load the Outside save file, it works fine, but then every time I try to enter the Crypt, the game crashes as soon as the area is 100% loaded.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 2833 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release-i386_2013-06-28

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series 

```
Driver Version:  4.3.12438 Compatibility Profile Context 13.20.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6738
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 3840 x 1200
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  703361 Mb
    Largest Free Hard Disk Block:  562156 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
