### ISSUE TITLE
Broken text entry for overlay in source games

### ISSUE THREAD

**Issue by Skrikey** [ValveSoftware/steam-for-linux#2772]
ISSUE
Text entry within the overlay on any Source games (L4D2, CS:S, TF2, HL2 etc) does not work, either in chat windows or the web browser. You can still use emoticons from the GUI and copy/paste text via right-click, however the keyboard is all but useless; almost as though the application has seized total control of the keyboard and disregards the overlay completely.

Side note: hitting the Escape key will exit the overlay.

OS
Sabayon Linux amd64 KDE

STEPS
Start Source game
Hit Shift&Tab to bring up the overlay
Type like a madman

RESULTS
Zilch, nada, zip.

EXPECTED
Anything but blank text fields!

**Comment by kisak-valve** [comment]
Hello @Skrikey, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
