### ISSUE TITLE
Segfault when trying to run Steam

### ISSUE THREAD

**Issue by KlavKalashj** [ValveSoftware/steam-for-linux#2775]
Yesterday Steam worked perfectly but today(I think there was an update to Steam just before I shutdown my computer yesterday) it does not start anymore. Here is the output when trying to run it:

[17:07:49] oscar@arch-desktop: [~] >>> steam
Running Steam on arch  64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/oscar/.local/share/Steam/steam.sh: line 704:  5476 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Installing bootstrap /home/oscar/.local/share/Steam/bootstrap.tar.xz
Running Steam on arch  64-bit
STEAM_RUNTIME has been set by the user to: /home/oscar/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/oscar/.local/share/Steam/steam.sh: line 704:  5557 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

I use Arch Linux 64-bit on an Intel CPU and AMD HD6950 with newest catalyst drivers. Everything fully updated.

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.
