### ISSUE TITLE
I cannot input my account number or password or anything 

### ISSUE THREAD

**Issue by tianqiujie** [ValveSoftware/steam-for-linux#2783]
I install steam for linux on ubuntu 13.04 64
and then i want to input my account, but it cannot.
I cannot input anything into the textBoxs.

tian@tian:~/桌面$ steam
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0819/021940:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Generating new string page texture 12: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311.30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 15: 384x256, total string texture memory is 835.58 KB
Installing breakpad exception handler for appid(steam)/version(1374875626_client)
Generating new string page texture 21: 64x256, total string texture memory is 901.12 KB
unlinked 2 orphaned pipes
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 4210 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 5 multi object alertable sleeps
[2013-08-19 02:19:38] Startup - updater built Jul 26 2013 14:20:54
[2013-08-19 02:19:38] Verifying installation...
[2013-08-19 02:19:38] Verification complete
Shutting down. . .
[2013-08-19 02:24:10] Shutdown

**Comment by kisak-valve** [comment]
Closing due to lack of feedback.
