### ISSUE TITLE
TF2 crash in MVM

### ISSUE THREAD

**Issue by gtbX** [ValveSoftware/steam-for-linux#2792]
I'm experiencing crashes when playing MVM on linux; the console mentions a std::logic_error exception.  This only seems to happen in MVM after playing for a few minutes.  Playing in normal mode doesn't exhibit this behavior.

Gentoo 64bit, kernel 3.8.13, Core i5,GeForce GTX 560, nvidia drivers 325.15

Log snippet:
GtB_ killed Sniper with axtinguisher. (crit)
GtB_ killed Spy with degreaser.
GtB_ killed Sniper witerminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
th axtinguisher. (crit)

m_face->glyph->bitmap.width is 0 for ch:32 TF2 Build

Cannot update control point 0 for effect 'player_sparkles_red'.
Cannot update control point 0 for effect 'player_sparkles_red'.
Cannot update control point 0 for effect 'player_sparkles_red'.
Cannot update control point 0 for effect 'player_sparkles_red'.

cocojack suicided.
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130820230426_1.dmp
Finished uploading minidump (out-of-process): success = no
error: HTTP response code said error
/home/drew/.local/share/Steam/SteamApps/common/Team Fortress 2/hl2.sh: line 67:  5014 Aborted                 ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 440 "Team Fortress 2", ProcID 5014

**Comment by kisak-valve** [comment]
Hello @gtbX, @CalcProgrammer1, are either of you still experiencing this issue on an up to date system?

**Comment by gtbX** [comment]
@kisak-valve I have not seen this happen in quite some time. IIRC, the crash disappeared in the patch immediately following this bug report.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
