### ISSUE TITLE
Wine applications added as non-Steam games produce upside down screenshots

### ISSUE THREAD

**Issue by Tea23** [ValveSoftware/steam-for-linux#2794]
If you add a Windows game as a non-Steam application that is running through Wine and take a screenshot, the screenshot is upside down.

Example here: http://steamcommunity.com/sharedfiles/filedetails/?id=171721045

Uncompressed image:
![12552054098825838592_2013-08-22_00001](https://f.cloud.github.com/assets/1298028/1009230/725a4f96-0b35-11e3-93fa-272ebf1f8800.png)

**Comment by zekesonxx** [comment]
This issue is still present as of 2016-11-07.

The [opened WineHQ Bug](http://bugs.winehq.org/show_bug.cgi?id=35525) was closed almost two years ago now with a status of RESOLVED NOTOURBUG. Valve, can you please look into this? It's a minor thing sure, but is incredibly annoying.

**Comment by kisak-valve** [comment]
Closing presumed fixed.
