### ISSUE TITLE
Engine error: no permissions to run 'hl2mp'

### ISSUE THREAD

**Issue by billythakidd04** [ValveSoftware/steam-for-linux#2796]
![screenshot from 2013-08-23 11 38 40](https://f.cloud.github.com/assets/888231/1018218/d22786fc-0c23-11e3-9891-c5a5508e795b.png)

Changed all file/folder permissions to 777 and unable to launch the base mod with no changes made. I have looked and found no reference to this error anywhere other than Windows needing to run as admin.

https://gist.github.com/billythakidd04/6323012

```
steam-runtime-sdk_2013-07-15/runtime$ ./run.sh ~/workspace/source-sdk-2013/mp/game/mod_hl2mp/bin/client.so
Segmentation fault (core dumped)
```

**Comment by kisak-valve** [comment]
Hello @billythakidd04, if you are still experiencing this issue with an up to date system, please open a new issue report in the [source-sdk-2013](https://github.com/ValveSoftware/source-sdk-2013) issue tracker.
