### ISSUE TITLE
Steam exits when opening shutdown or logout dialog

### ISSUE THREAD

**Issue by minerz029** [ValveSoftware/steam-for-linux#2799]
When I click on the "Shut Down..." or "Log Out..." buttons in the system menu (at the top left of screen), Steam quits regardless of whether I perform the operation (shutdown or logout) or cancel the dialog. Happens whether or not Steam is the active window

Using Steam on Ubuntu 13.04 (64-bit)

**Comment by ElTimablo** [comment]
Well, it's definitely not obscure. I've had this problem for months and only just traced it back to Steam. It doesn't happen all the time, but it also blocks Gnome from logging out at all when it closes. I checked what was happening by running steam from the terminal and logging out, and it looked like a completely normal shutdown. I don't even know where Steam would find out that the shutdown dialog box is open, let alone close when it does. Please take a look at this as it's causing me to have to hard power off my computer if I accidentally try to shut down with Steam running.

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been resolved.
