### ISSUE TITLE
Steam needs to install these additional packages: libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386

### ISSUE THREAD

**Issue by dunca123** [ValveSoftware/steam-for-linux#2814]
I have a fresh install of Ubuntu 12.04.3 64 bit and I get this error message when I try to install it. 

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-glx:i386 : Depends: libglapi-mesa:i386 (= 8.0.4-0ubuntu0.6)
E: Unable to correct problems, you have held broken packages.

After that an error message pops up saying,

You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6

I saw there was another thread about this issue and it was resolved, but obviously not. Maybe we all need to downgrade our Kernel to 12.04.2 If so, please point me in the direction of how to do so.

**Comment by thankyoualot** [comment]
sudo apt-get install libgl1-mesa-dri-lts-trusty:i386 libgl1-mesa-glx-lts-trusty:i386 libc6:i386

**Comment by victordev** [comment]
@thankyoualot works for me! thanks

**Comment by luksi-l** [comment]
i don't get it,im right now trying to install steam but i get this:
Steam needs to install these additional packages:
    libgl1-mesa-dri:i386, libgl1:i386, libc6:i386
[sudo] password for korisnik: 
..................
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfprint-2-tod1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  gcc-10-base:i386 libatomic1:i386 libbsd0:i386 libcrypt1:i386
  libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386
  libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386
  libffi7:i386 libgcc-s1:i386 libglapi-mesa:i386 libglvnd0:i386
  libglx-mesa0:i386 libglx0:i386 libidn2-0:i386 libllvm10:i386
  libpciaccess0:i386 libsensors5:i386 libstdc++6:i386 libtinfo6:i386
  libunistring2:i386 libvulkan1:i386 libwayland-client0:i386 libx11-6:i386
  libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386
  libxcb-glx0:i386 libxcb-present0:i386 libxcb-randr0:i386 libxcb-sync1:i386
  libxcb1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386
  libxshmfence1:i386 libxxf86vm1:i386 libzstd1:i386 mesa-vulkan-drivers:i386
  zlib1g:i386
Suggested packages:
  glibc-doc:i386 locales:i386 lm-sensors:i386
The following NEW packages will be installed:
  gcc-10-base:i386 libatomic1:i386 libbsd0:i386 libc6:i386 libcrypt1:i386
  libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386
  libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386
  libffi7:i386 libgcc-s1:i386 libgl1:i386 libgl1-mesa-dri:i386
  libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386
  libidn2-0:i386 libllvm10:i386 libpciaccess0:i386 libsensors5:i386
  libstdc++6:i386 libtinfo6:i386 libunistring2:i386 libvulkan1:i386
  libwayland-client0:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386
  libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386
  libxcb-randr0:i386 libxcb-sync1:i386 libxcb1:i386 libxdamage1:i386
  libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxshmfence1:i386
  libxxf86vm1:i386 libzstd1:i386 mesa-vulkan-drivers:i386 zlib1g:i386
0 upgraded, 49 newly installed, 0 to remove and 28 not upgraded.
Need to get 34,6 MB of archives.
After this operation, 404 MB of additional disk space will be used.
Do you want to continue? [Y/n]
