### ISSUE TITLE
No sound coming from any Steam Game

### ISSUE THREAD

**Issue by Kelkadoor** [ValveSoftware/steam-for-linux#2815]
I have searched for hours on end to find a solution for this issue but I could not find a solution that worked for me. I am using a modified Ubuntu 12.04 and I have tried STEAM_RUNTIME=0 and SDL_AUDIODRIVER=alsa among other things that I can't remember right now. 
Two things that may be interesting to note:
1. I cannot open alsamixer no matter what, and I have searched that for hours too.
2. Sound plays from the steam overlay browser, but not from the game.
Please help. :<

**Comment by kisak-valve** [comment]
Hello @Kelkadoor, are you still experiencing this issue up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
