### ISSUE TITLE
Fullscreen steam games show only black

### ISSUE THREAD

**Issue by malcolm2608** [ValveSoftware/steam-for-linux#2826]
The problem can be duplicated by downloading a game on steam and launching it , most of them will launch in full-screen so its easy to observe the bug. While they are in full screen I can hear signs that my cursor is actually moving and the game is still running ,however I can't see anything but black.

Tested with:
- Stacking
- Garry's Mod
- VVVVVV ( This actually works full screen )
- CS:S

My Setup:
- Elementary Os Luna ( Ubuntu 12.04 )
- HD 6770 running the fglrx-experimental-13 driver

I have posted this on the [bug tracker for elementary os](https://bugs.launchpad.net/gala/+bug/1220725) , but because I am not sure if this is a bug caused by the following :
- Gala Window Manager
- fglrx-experimental-13 driver
- Steam's Client 
- Individual games on steam

[System Information](https://gist.github.com/malcolm2608/6437510)

**Comment by kisak-valve** [comment]
Hello @malcolm2608, if you are still experiencing this issue with an up to date system, please open a new issue report.

Closing as general video driver quality from 2013 is no longer relevant.
