### ISSUE TITLE
Videos play too fast

### ISSUE THREAD

**Issue by scrawl** [ValveSoftware/steam-for-linux#2832]
If I go to a game's store page from within the client and try to play a video, it plays at about 2-3x speed.
I'm not sure if it's using the html5 or flash player. Any way to check?

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2533 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Metacity
    Steam Runtime Version:  steam-runtime-release-i386_2013-08-26

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2

```
Driver Version:  2.1 Mesa 9.0
OpenGL Version: 2.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x46
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13,54" x 7,60"  (15,51" diag)
                                        34,4cm x 19,3cm  (39,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC272X

Memory:
    RAM:  3629 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  296745 Mb
    Largest Free Hard Disk Block:  4691 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @scrawl, @PragTob, are either of you still experiencing this issue on an up to date system?

**Comment by PragTob** [comment]
Hasn't happened to me in a while, thanks!

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
