### ISSUE TITLE
Trying the LXDE Env Destroyed My Steam Client on Ubuntu 13.04 (Unity)

### ISSUE THREAD

**Issue by junktext** [ValveSoftware/steam-for-linux#2833]
I wanted to test out LXDE (desktop environment as opposed to Unity on Ubuntu 13.04) to see if my Steam games would run any smoother, so I installed LXDE from the Software Center, rebooted, chose LXDE as my desktop environment prior to logging in (which loaded up just fine), and then tried to launch Steam. For me, Steam just had a blip of the GUI pop up stating "Verifying installation..." (this is in my ZIP file I uploaded to www.junktext.net/pub/SteamErrors_2013-09.zip) and then nothing else happens graphically. I figured the problem was with LXDE, so I rebooted and went back to Unity. Now I get the same results, with just a blip of the Steam GUI loading and nothing else.

I then concluded my Steam installation was broken, so I tried to fully reinstall Steam from scratch, but the methods I choose don't seem to be able to get me back to a usable Steam client. I have attempted the following methods to reinstall my Steam client on Unity:

```
*** In all of the below examples, I also manually deleted the following directories before reinstalling: "~/.steam" and "~/.local/share/Steam" 

1. Removed and reinstalled Steam using the graphical Ubuntu "Software Center".
2. Ran in terminal: sudo apt-get remove steam-launcher (and then later: sudo apt-get update && sudo apt-get install steam-launcher)
3. Ran in terminal: sudo apt-get purge steam-launcher (and then later: sudo apt-get update && sudo apt-get install steam-launcher)

*** Also, I know that the normal Ubuntu repository has an outdated Steam client (v1.0.0.35) versus Valve's repository once Steam is actually installed (v1.0.0.41).  So, after doing any method above, I also ran a final: sudo apt-get update && sudo apt-get upgrade (which bumps my Steam client to v1.0.0.41, but this still doesn't fix anything for me).
```

I recorded what error messages are reported in a terminal by launching Steam via the "steam" command (this is also in the ZIP file I uploaded to www.junktext.net/pub/SteamErrors_2013-09.zip). The first part of the output is regarding the re-building of my Steam client files (from a fresh install) and the rest of the output is what will result if I kill out the previous "steam" command and re-run "steam", resulting in a bunch of "GLXBadDrawable" messages from Steam. Be aware that even though no Steam GUI loads up, the Steam process is still running in the background unless I kill it, which I have confirmed with "top" (even though nothing happens if I wait for 20+ minutes, and the Steam client only uses up between 1-3% of my CPU which I think is low from when it was working fine).
- My system: I am running Ubuntu 13.04 (64-bit) with an NVIDIA driver (GeForce 310M) on a Samsung Q430 laptop (Intel i5 CPU M450 @ 2.40GHz x 2 Cores, 4.0 GB of RAM). Keep in mind that prior to me using LXDE, every Steam game I had worked flawlessly for over 4 months, so I do not think it is my NVIDIA driver, as every other graphical app I use (Firefox, Konversation, Thunderbird, et cetera) still works fine in Unity.

**Comment by kisak-valve** [comment]
Hello @junktext, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
