### ISSUE TITLE
Games has no sound if system's pulseaudio is linked with liborc 0.4.17 or newer

### ISSUE THREAD

**Issue by krnekit** [ValveSoftware/steam-for-linux#2834]
I use Mageia Cauldron (development version of Mageia) and it has pulseaudio linked with more recent liborc, that is shipped with Steam. Because of Steam uses LD_LIBRRY_PATH, it uses own library, and this cause pulseaudio errors and games has no sound. Workaround is to delete Steam's liborc library. See this [bugreport](https://bugs.mageia.org/show_bug.cgi?id=10788) for more details.
Possible solution is to update liborc in Steam package.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
