### ISSUE TITLE
[Steam Linux - Cloud sync] Half-Life always syncing

### ISSUE THREAD

**Issue by Lord-Avallon** [ValveSoftware/steam-for-linux#2839]
Every time I launch Steam Half-Life syncs, even if I don´t play it, it happens all the time (I deleted it now because I finished the game, but if it´s necessary I can re-install).

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
