### ISSUE TITLE
Half Life Deathmatch: Source shows up in the library, can not install

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/steam-for-linux#2844]
Half Life Deathmatch: Source is showing up in my library, but when I try to install it, it hangs on preparing files.

Sysinfo:
https://gist.github.com/pizzadude/faad0fabae18720174ad

**Comment by kisak-valve** [comment]
Hello, if anyone is still encountering this issue, please open a new issue report and include the affected region.
