### ISSUE TITLE
Legend of Dungeon frequently freezes for several seconds

### ISSUE THREAD

**Issue by slouken** [ValveSoftware/steam-for-linux#2852]
When playing Legend of Dungeon with the game controller it appears to freeze for a few seconds fairly often in a random pattern.  It would always come back, but made for a frustrating game experience.

**Comment by kisak-valve** [comment]
@slouken, I'm going to go ahead and close this as general video driver quality from 2013 is no longer relevant. If this issue still affects an up to date system, we can re-open.
