### ISSUE TITLE
Low fps of dota2: on Linux mint 13 64bit, Alienware M15x

### ISSUE THREAD

**Issue by leslielg** [ValveSoftware/steam-for-linux#2855]
I got very low fps(10~30) when playing native dota2 in steam. My environment is as below:

hardware: Alienware m15x laptop, intel i7 1.8G qual core, 8G ram, nvidia gtx460m
software: Linux mint mate 13 64bit full update, installed ia32-libs, nvidia official driver 319.

any suggestion?

thanks in advance

**Comment by kisak-valve** [comment]
Closing as general video driver performance from 2013 is no longer relevant.
