### ISSUE TITLE
Categories odd behaviour

### ISSUE THREAD

**Issue by robertoszek** [ValveSoftware/steam-for-linux#2857]
Despite I change the category of a game after a few moments it returns to the initial category. I tried the option "Delete from [...] category" and it isn't persistant either. I changed the category and restarted the client immediatly too, but no luck.

The output when attempting is a bunch of these:
<code>(steam:19234): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.</code>

**Comment by kisak-valve** [comment]
Hello @robertoszek, are you still experiencing this issue on an up to date system?

**Comment by robertoszek** [comment]
I'm not, as a matter of fact. This was reproducible in that version of Steam (almost 4 years ago) but since then it seems like it has been fixed along the way. I couldn't say in which exact version it stopped happening, however.
I'm closing this issue, thanks for the reminder, I completely forgot I opened it. Cheers.
