### ISSUE TITLE
Steam login dialog can be resized too small

### ISSUE THREAD

**Issue by aaronp24** [ValveSoftware/steam-for-linux#286]
According to xprop, the Steam login dialog has a minimum size of 128 by 66 pixels.  This too small to use any of the UI elements.  The minimum should probably be the default of 420x352.

![Screenshot from 2012-12-22 08:12:19](https://f.cloud.github.com/assets/343551/28566/6edb05e2-4c52-11e2-8086-4e81d2732382.png)

**Comment by outlying** [comment]
Problem still occurs, in my case Ubuntu 14.04 with Gnome Shell

**Comment by robclancy** [comment]
Same issue for me, arch linux gnome 3

**Comment by robclancy** [comment]
Guess they are just going to ignore this in classic Valve fashion.

Incase someone needs a shitty workaround you can launch with `-bigpicture` to be able to login then restart and it should auto login.

**Comment by ValerioCietto** [comment]
It just happened to me today, thanks @robclancy for the shitty workaround.
Using Ubuntu 14.04, Unity, dual monitor.
Steps to reproduce:
-drag window between 2 workspaces
-resize
-change password
-close window
-launch. Now window is too small to use

**Comment by nsilent22** [comment]
Happened today to me. Ubuntu 14.04.5 + Mate. Thanks to @robclancy's workaround I managed to login, but some other windows are still 128x66, for example dialog from steam update agent or 'about' window.
![about](https://cloud.githubusercontent.com/assets/14313222/18028588/2d6f2692-6c83-11e6-84fc-f1dcb9d776c5.png)
![selfupdater](https://cloud.githubusercontent.com/assets/14313222/18028590/3afdff22-6c83-11e6-8554-950fdebec49d.png)

**Comment by mchavarriagam** [comment]
Same issue on Ubuntu 14.04, fixed thanks to @robclancy.

**Comment by jason-oliveira** [comment]
Happening to me right now on Gentoo Linux amd64 in KDE/KWin every time username/password window appears in Steam Beta. Identical to @aaronp24, in 2019.
