### ISSUE TITLE
CS 1.6 crashes when autobuy(F1) key is pressed or triggered on mouse(SOLVED)

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/steam-for-linux#2865]
!!SYSTEM Summary!!
Computer
Processor   6x AMD Phenom(tm) II X6 1045T Processor
Memory  8164MB (2099MB used)
Operating System    Linux Mint 13 Maya
User Name   jd (JD)
Date/Time   Fri 20 Sep 2013 09:20:35 PM EDT
Display
Resolution  1600x900 pixels
OpenGL Renderer AMD Radeon HD 7700 Series
X11 Vendor  The X.Org Foundation
Multimedia
Audio Adapter   HDA-Intel - HDA ATI SB
Audio Adapter   USB-Audio - USB Device 0x46d
Input Devices
Power Button  
Power Button  
AT Translated Set 2 keyboard  
Mad Catz Mad Catz R.A.T.7 Mouse 
UVC Camera (046d:0825)  
HDA ATI SB Line 
HDA ATI SB Front Mic  
HDA ATI SB Rear Mic 
HDA ATI SB Front Headphone  
HDA ATI SB Line-Out Side  
HDA ATI SB Line-Out CLFE  
HDA ATI SB Line-Out Surround  
HDA ATI SB Line-Out Front  
Printers (CUPS)
THOR    Default
SCSI Disks
ATA ST31000528AS  
ATA OCZ-VERTEX3 
ATAPI iHAS324 C 
Operating System
Version
Kernel  Linux 3.2.0-41-generic (x86_64)
Compiled    #66-Ubuntu SMP Thu Apr 25 03:27:11 UTC 2013
C Library   Unknown
Default C Compiler  GNU C Compiler version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
Distribution    Linux Mint 13 Maya
Current Session
Computer Name   Marzipan
User Name   jd (JD)
Home Directory  /home/jd
Desktop Environment MATE
Misc
Uptime  1 day, 1 hour and 59 minutes
Load Average    1.46, 1.38, 1.09
Display
Display
Resolution  1600x900 pixels
Vendor  The X.Org Foundation
Version 1.11.3
Monitors
Monitor 0   1600x900 pixels
Extensions
AMDXVBA 
AMDXVOPL  
ATIFGLEXTENSION 
ATIFGLRXDRI 
BIG-REQUESTS  
Composite  
DAMAGE  
DOUBLE-BUFFER  
DPMS  
DRI2  
GLX 
Generic Event Extension 
MIT-SCREEN-SAVER  
MIT-SHM 
RANDR  
RECORD  
RENDER  
SECURITY  
SGI-GLX 
SHAPE  
SYNC  
X-Resource  
XC-MISC 
XFIXES  
XFree86-DGA 
XFree86-VidModeExtension  
XINERAMA  
XINERAMA  
XInputExtension 
XKEYBOARD  
XTEST  
XVideo  
XVideo-MotionCompensation  
glesx  
OpenGL
Vendor  Advanced Micro Devices, Inc.
Renderer    AMD Radeon HD 7700 Series
Version 4.2.12217 Compatibility Profile Context 12.104
Direct Rendering    Yes

!!TERMINAL OUTPUT!!!

ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20130920211724_1.dmp
/home/jd/.local/share/Steam/SteamApps/common/Half-Life/hl.sh: line 38:  7238 Segmentation fault      (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@
Game removed: AppID 10 "Counter-Strike", ProcID 7238 
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-a2506322-47a3-4ae9-83f8-e28b22130920

!!.DMP FILE!!

http://www.filedropper.com/assert201309202117241

**Comment by 666threesixes666** [comment]
and today i run into this issue...  i suspect garbage in .steam, deleting that flushing steam then reinserting it.
