### ISSUE TITLE
Wrong resolution with CSS ?

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/steam-for-linux#2867]
I have played CSS before succefully.

I 1st started it normally and end up on the starting menu. When I am trying to select searching servers, mouse doesn't pick up that selection.

I think the game/kde or something similar is on wrong resolution and my selection isn't there where my mouse is.

Then i added launch options -w 1920 -h 1080 -novid

and I have pretty much same problem, but while game loads it loads on 640x480 bitmap on screen or something like that and when it's fully loaded scales in full screen.

And I still have the same issue.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3511 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.10.12-031012-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11304000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7800 Series  

```
Driver Version:  4.3.12441 Compatibility Profile Context 13.20.5
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x679e
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,82" x 10,59"  (21,57" diag)
                                        47,8cm x 26,9cm  (54,8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7905 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  283122 Mb
    Largest Free Hard Disk Block:  66559 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
If this issue is still occurring on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
