### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by AJIeKCaHDp** [ValveSoftware/steam-for-linux#2868]
Running Steam on arch  64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 10794 with name 0eBlobRegistryMutex_252CE762D438A18B6C3A8C3716CB25E5
removing stale semaphore last operated on by process 10794 with name 0eBlobRegistrySignal_252CE762D438A18B6C3A8C3716CB25E5
removing stale semaphore last operated on by process 10794 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 10794 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0922/175235:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0922/175235:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)

*\* (steam:16467): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:16467): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442,37 KB
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
Installing breakpad exception handler for appid(steam)/version(1378500910_client)

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Adding license for package 0
Adding license for package 7
Adding license for package 22
Adding license for package 218
Adding license for package 305
Adding license for package 469
Adding license for package 502
Adding license for package 2485
Adding license for package 2620
Adding license for package 4097
Adding license for package 4559
Adding license for package 4639
Adding license for package 6257
Adding license for package 6896
Adding license for package 7320
Adding license for package 7427
Adding license for package 7612
Adding license for package 7877
Adding license for package 8089
Adding license for package 8185
Adding license for package 8306
Adding license for package 8866
Adding license for package 8926
Adding license for package 11591
Adding license for package 11616
Adding license for package 11734
Adding license for package 12083
Adding license for package 12544
Adding license for package 12572
Adding license for package 13298
Adding license for package 13656
Adding license for package 14842
Adding license for package 15334
Adding license for package 15740
Adding license for package 16549
Adding license for package 17040
Adding license for package 18029
Adding license for package 25518
Adding license for package 26380
Adding license for package 27531
Adding license for package 31949
local (potentially out of sync) copy of roaming config loaded - 0 bytes.
ExecCommandLine: "/home/ajiekcahdp/.local/share/Steam/ubuntu12_32/steam"
System startup time: 11,25 seconds
Running Steam on arch  64-bit
STEAM_RUNTIME has been set by the user to: /home/ajiekcahdp/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 73: 1024x256, total string texture memory is 1,49 MB
Generating new string page texture 74: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 75: 128x256, total string texture memory is 1,62 MB
Generating new string page texture 76: 256x256, total string texture memory is 1,88 MB
Generating new string page texture 77: 32x256, total string texture memory is 1,92 MB
Generating new string page texture 78: 64x256, total string texture memory is 1,98 MB
Installing breakpad exception handler for appid(steam)/version(1378500910_client)
ExecCommandLine: "/home/ajiekcahdp/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:16467): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 101: 128x256, total string texture memory is 2,11 MB
Generating new string page texture 103: 256x256, total string texture memory is 2,38 MB
Generating new string page texture 104: 128x256, total string texture memory is 2,51 MB
Generating new string page texture 105: 8x256, total string texture memory is 2,51 MB
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20130922175229_1.dmp
/home/ajiekcahdp/.local/share/Steam/steam.sh: line 704: 16467 Ошибка сегментирования                   (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-0211cfb1-e9db-44af-ba00-09a9a2130922

uname -a
Linux ajiekcahdp 3.11.1-1-ARCH #1 SMP PREEMPT Sat Sep 14 19:30:21 CEST 2013 x86_64 GNU/Linux

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
