### ISSUE TITLE
Game stuck in "Update Required" status

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#2869]
One of my Linux games, X3: Reunion has been stuck in an "Update Required" status and I've been unable to get it out.  I've tried verifying the local game cache, which reports that it's fine.  If I try to play the game, I get a "Preparing to launch X3: Reunion" dialog whose progress bar never changes.  In the "Downloads" view, it usually starts off in a "Suspended" state - I can hit "pause" and then "resume" which just brings it back into Suspended.  The "Resume All" button doesn't seem to do anything.  On that screen it says "Updated: 0 bytes / 0 bytes, Time Initiated: 21:20, Time Remaining:" (with no value after Time Remaining) - the "Time Initiated" value might change from run to run, I'm not sure about that.

I've also tried setting it to not auto-update, but that doesn't seem to change it either.  This has persisted throughout many restarts of the Steam client over the course of the past week or two.  I CAN play the game if I move Steam into offline mode first, at least, so that's nice.  It'd be nice to figure out how to get it to start behaving on its own though.

I assume that I could probably fix it by completely deleting the game and then redownloading it, but I'd rather just figure out a way to fix it that's less destructive.  There doesn't seem to be any useful output on the console.  If there's more information I could provide, please let me know.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2936 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 19 (Schrödinger’s Cat)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.10.11-200.fc19.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11402000
    X Window Manager:  IceWM 1.3.7 (Linux 2.6.32-358.2.1.el6.x86_64/x86_64)
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti/PCIe/SSE2

    Driver Version:  4.3.0 NVIDIA 319.32
    OpenGL Version: 4.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x11c6
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                            52.1cm x 29.3cm  (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: TriTech TR28602

Memory:
    RAM:  5970 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  238752 Mb
    Largest Free Hard Disk Block:  40951 Mb

Installed software:

Recent Failure Reports:
```

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved. If anyone is still encountering this issue, please open a new issue report.
