### ISSUE TITLE
Can't install X3: Reunion (case sensitive path issues?)

### ISSUE THREAD

**Issue by jonquark** [ValveSoftware/steam-for-linux#2871]
I can't install X3: Reunion on my (Fedora 19) Linux system. Other games (including X3: Terran Conflict and Portal) install fine.

Clicking the install button brings up the install dialogs as usual but it seems to hang in the state that says:

"Creating local game cache files:
Preparing X3: Reunion files for install..."
The 3 ellipses after for install cycle between 1 and 3 (until eventually I get told "Connection timed out" even though I have installed other games before and since).

Looking in the config.vdf file I see the string:
                    "2810"
                    {
                        "installdir"        "/home/jon/.local/share/steam/steamapps/common/x3 - reunion"
                        "UpdateKBtoDL"      "0"
                    }
So the case of steam/steamapps is wrong (on my system they are Steam/SteamApps) but creating symbolic links so that that path exists did not help.

No related text seems to be output on the console.. 

If any more diagnostic information is wanted, let me know how to gather it.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved. If anyone is still encountering this issue, please open a new issue report.
