### ISSUE TITLE
Random freeze in some games(Source games?)

### ISSUE THREAD

**Issue by aknarts** [ValveSoftware/steam-for-linux#2873]
While playing **TF2** or **Dota 2** I do get these random freezes for a second or two, which is kind of inconvenient during the gameplay. Haven't tried other games, but it is possible this happens elsewhere.

Using **intel graphics** (**VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller**)
64bit system kernel version: **3.11.1**
DE irelevant(tried KDE, Gnome, xfce - all the same)

Driver info:

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.1 (Core Profile) Mesa 9.2.0
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 9.2.0
OpenGL shading language version string: 1.30
```

Nothing relevant in the steam log(No output during the short freeze)
Other than that, games runs OK, before and after the freeze.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
