### ISSUE TITLE
Big Picture Mode crashes when browsing to youtube.com

### ISSUE THREAD

**Issue by noammor** [ValveSoftware/steam-for-linux#2878]
Steps to reproduce:
1. Big Picture Mode
2. Web
3. youtube.com

When entering youtube.com, the screen (the part of it on which youtube.com is rendered) flickers for 2-3 seconds. After that, once I got a freeze, and once I got Steam crashing. When steam crashed, All of Google Chrome's tab processes die ("He's dead, Jim!" page). Verified it twice. also verified that steam crashes even if Chrome is not running. Steam doesn't crash when going to google.com. Here's a crash log:

roaming config store loaded successfully - 1945 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
ExecCommandLine: "/home/noam/.local/share/Steam/ubuntu12_32/steam"
System startup time: 6.23 seconds
Running Steam on ubuntu 13.04 32-bit
STEAM_RUNTIME has been set by the user to: /home/noam/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 71: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 72: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 73: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 74: 32x256, total string texture memory is 540.67 KB
ExecCommandLine: "/home/noam/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
[0926/213949:ERROR:cef_context.cc(499)] No data resource available for id 4501
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Compiled against SDL version 2.0.0 and linked against SDL version 2.0.0
DeleteFBOFreeList: Removing 0 FBO objects, total 0
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
WebM decoder 0x0xdf6bd30 is playing file: /home/noam/.local/share/Steam/tenfoot/resource/images/intro_movie.webm
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
WebM decoder 0x0xdf88e98 is playing file: /home/noam/.local/share/Steam/tenfoot/resource/images/browser/reticle.webm
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
0x0xdf88e98 11687ms WebM decoder: Frame times: peak=522, avg=194
0x0xdf88e98 11687ms WebM decoder: Video decode times: peak=516, avg=284
0x0xdf88e98 11687ms WebM decoder: Audio decode times: no calls
0x0xdf88e98 11687ms WebM decoder: Video present times: peak=0, avg=0
0x0xdf88e98 11687ms WebM decoder: Audio commit times: no calls
0x0xdf88e98 11687ms WebM decoder: Sleep times: peak=14116, avg=7058
Pushing to backstack: ShowMainMenu (focus: StoreButton)
Pushing to backstack: ShowMainMenu (focus: StoreButton)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
HTTP Response for http://store.steampowered.com/api/featured/: 200
HTTP Response for http://store.steampowered.com/api/featuredcategories/: 200
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
Pushing to backstack: ShowWebBrowser (focus: StoreButton)
0x0xdf6bd30 17278ms WebM decoder: Frame times: peak=51935, avg=1
0x0xdf6bd30 17278ms WebM decoder: Video decode times: peak=29158, avg=12015
0x0xdf6bd30 17278ms WebM decoder: Audio decode times: peak=182, avg=50
0x0xdf6bd30 17278ms WebM decoder: Video present times: peak=1036, avg=419
0x0xdf6bd30 17278ms WebM decoder: Audio commit times: peak=13, avg=5
0x0xdf6bd30 17278ms WebM decoder: Sleep times: peak=37637, avg=151
WebM decoder 0x0xe86b010 is playing file: /home/noam/.local/share/Steam/tenfoot/resource/images/browser/reticle.webm
Installing breakpad exception handler for appid(steam)/version(1380154943_client)
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
0x0xe86b010 18684ms WebM decoder: Frame times: peak=905, avg=0
0x0xe86b010 18684ms WebM decoder: Video decode times: peak=890, avg=252
0x0xe86b010 18684ms WebM decoder: Audio decode times: no calls
0x0xe86b010 18684ms WebM decoder: Video present times: peak=23, avg=12
0x0xe86b010 18684ms WebM decoder: Audio commit times: no calls
0x0xe86b010 18684ms WebM decoder: Sleep times: peak=35766, avg=31
/home/noam/.local/share/Steam/steam.sh: line 717:  5187 Killed                  $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

I'm on latest Ubuntu, here's lspci:

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.2 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 3 (rev c4)
00:1c.3 PCI bridge: Intel Corporation 82801 PCI Bridge (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation H77 Express Chipset LPC Controller (rev 04)
00:1f.2 IDE interface: Intel Corporation 7 Series/C210 Series Chipset Family 4-port SATA Controller [IDE mode](rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
00:1f.5 IDE interface: Intel Corporation 7 Series/C210 Series Chipset Family 2-port SATA Controller [IDE mode](rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 660](rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 0e0b (rev a1)
03:00.0 Ethernet controller: Qualcomm Atheros AR8161 Gigabit Ethernet (rev 10)
04:00.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev 41)

I'm using nvidia video driver version 313.30.
Bug #72 applies to me too.

**Comment by kisak-valve** [comment]
Hello @noammor, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by noammor** [comment]
I'm no longer experiencing this issue.
