### ISSUE TITLE
Videos in Steam doesn't work while Firefox is playing (and vice versa)

### ISSUE THREAD

**Issue by Reinis** [ValveSoftware/steam-for-linux#2884]
For example if running http://youtu.be/-tNTqpH7XhE and the opening some game's page in Steam store, the video in steam is not playing and also doesn't cycle trough screenshots etc. And also video in Steam blocks the video in Firefox if it was started first.

Note that it is HTML5 video in Firefox 24. I'm using Gentoo Linux on ~amd64.

This issue might also be related to the few Steam client crashes I had (and dumps were automatically sent).

**Comment by kisak-valve** [comment]
Hello @Reinis, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
