### ISSUE TITLE
Opening a game from big picture and turning on controller support freezes the system

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/steam-for-linux#2888]
So I wanted to set up my controller so I can open a game in big picture so I can join the beta for the controller and the steam machines. So I set up the controller and then started up L4D2 and then it detected that I was running big picture so it asked for me to turn on controller support so I did and freeze there. So then I tried again same story. And then I tried with TF2 outside of big picture and it worked flawlessly but then I started it in big picture and it crashed just like L4D2. 

So the common denominator is big picture. Im using the standard out of the box xbox controller driver on Ubuntu 13.04 with 3.0 mesa 9.2.0-devel from the xorg edgers PPA. If it matters im running a haswell i5 without any GPU but it shouldn't since its an input error.

**Comment by kisak-valve** [comment]
Hello @shanefagan, are you still experiencing this issue with an up to date system?

**Comment by shanefagan** [comment]
Not recently looks like it was resolved
