### ISSUE TITLE
Black screen when launching games that exclusively grab the keyboard

### ISSUE THREAD

**Issue by bilbo2** [ValveSoftware/steam-for-linux#2889]
When launching steam games that do not exclusively grab the keyboard (i.e. they do not forbid using ALT-TAB and other special keys defined by the window manager), everything works fine.

When launching steam games that do grab the keybatrd (i.e. you can't ALT-tab out of them), and if the "Enable steam communuty in-game" checkbox in the game properties is checked (which is the default), then launching the game will just yield moving mouse cursor on a black screen and since you can't alt-tab out of it, it may be tricky to kill the game to get back to your desktop (if CTRL-ALT-Fx to swich VT and CTRL-ALT-BKSP keys to kill X server are disabled in your X server config, then you may even need to reboot ....).

If I uncheck the "Enable steam communuty in-game" checkbox, then the overlay is no longer available (via shift-tab), but the game runs (no black screen).

Examples of affected games: Darwinia, Uplink, Mark of the Ninja, Amnesia the dark descent, Penumbra (Black plague, Overture and Requiem).

I am using 64bit Debian unstable and latest nvidia drivers that are in debian repos (304.108)

**Comment by kisak-valve** [comment]
Hello @bilbo2, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by bilbo2** [comment]
it seems to be running fine now under current system (after several updates :)
