### ISSUE TITLE
Incorrect button mapping in Big Picture Mode (XBOX 360 gamepad)

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/steam-for-linux#2890]
Rereporting of https://github.com/ValveSoftware/steam-for-linux/issues/95 
Same issue "B" registers as "A" and "X" registers as "B". The triggers and other buttons aren't mapped at all. 

Controller version:
Gamestop wired xbox 360 controller BB-070

Ubuntu 13.04 
Linux 3.8.0-31-generic
Mesa version 9.2.0~git20130729 (xorg edgers ppa current version)

**Comment by henryford** [comment]
I am experiencing this problem as well - using Linux Mint 17.1. This issue is now open for over a year...

**Comment by evanrblack** [comment]
I have this problem too. Works correctly with the wired controller for me, but the wireless one (which uses a 3rd party receiver) has the buttons buttons mapped incorrectly. The receiver works fine under windows.

**Comment by calexil** [comment]
issue is ongoing

**Comment by sunjay** [comment]
Anything we can do? Still experiencing this on Linux Mint 17.3

**Comment by rbjorklin** [comment]
Encountering this issue in Fedora 25 right now ``--mimic-xpad`` seems to still work as a workaround though!
