### ISSUE TITLE
HLDM:S and HL:S out of Beta but not listed as Linux/OS X-supported on Steam page

### ISSUE THREAD

**Issue by connorshea** [ValveSoftware/steam-for-linux#2893]
Half-Life Deathmatch: Source and Half-Life: Source have both been released on OS X and Linux, but don't have OS X or Linux icons nor do they have system requirements.

[Half-Life: Source Steam Page](http://store.steampowered.com/app/280/)

[Half-Life Deathmatch: Source Steam Page](http://store.steampowered.com/app/380/)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago.
