### ISSUE TITLE
Steam cannot detect VRAM size (Mesa drivers)

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/steam-for-linux#2897]
System information:

```
Operating System Version:
    Ubuntu 13.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-031100-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TURKS

    Driver Version:  3.0 Mesa 9.3.0-devel (git-b280516 raring-oibaf-ppa+glvdpau)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6758
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary VRAM Not Detected

```

While dmesg shows:

```
dmesg | grep VRAM
[    7.161765] radeon 0000:01:00.0: VRAM: 1024M 0x0000000000000000 - 0x000000003FFFFFFF (1024M used)
[    7.161770] [drm] Detected VRAM RAM=1024M, BAR=256M
[    7.163143] [drm] radeon: 1024M of VRAM memory ready
```

**Comment by bluszcz** [comment]
Ubuntu Trusty 14.04 Radeon 6800.

https://gist.github.com/bluszcz/acd31503858c156d5b0c

**Comment by baos780** [comment]
Tested nvidia with 960 then 970(because I wanted more vram)

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 14.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-46-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 73.70" x 41.46"  (84.53" diag)
                                            187.2cm x 105.3cm  (214.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Nvidia ID 71
    
Memory:
    RAM:  16006 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  17705 Mb
    Largest Free Hard Disk Block:  9790 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by bootkiller** [comment]
Happy to report vram now shows correctly on amd open source, at least on this brand new card (RX460). Not sure if it displayed correctly on my HD4770 before I changed it.

`Video Card:
    Driver:  X.Org Gallium 0.4 on AMD POLARIS11 (DRM 3.3.0 / 4.8.0-rc4-mainline, LLVM 3.8.1)

    Driver Version:  3.0 Mesa 12.0.3
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67ef
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18,74" x 10,55"  (21,50" diag)
                                            47,6cm x 26,8cm  (54,6cm diag)
    Primary VRAM: 4060 MB`

**Comment by stevethepocket** [comment]
Yeah, this has been resolved for me as well, although it's still detecting the wrong OpenGL version (see #4698 for deets). My guess is that it was a Mesa deficiency all along.

**Comment by kisak-valve** [comment]
Closing per last 2 comments, thanks.

**Comment by gulafaran** [comment]
doesnt detect it still on mesa/nouveau

`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.11.5-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  nouveau Gallium 0.4 on NVF1

    Driver Version:  3.0 Mesa 17.1.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                            59.8cm x 33.6cm  (68.5cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  16004 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  233199 Mb
    Largest Free Hard Disk Block:  159601 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    `

**Comment by stevethepocket** [comment]
Looks like it has no idea what your card even is. What is it?

**Comment by gulafaran** [comment]
its a 780ti

**Comment by NovaCygni** [comment]
Appears to still be a issue sadly :(

**Comment by nikikrupka** [comment]
On my RX470 this is still a issue. I don't know if this is an issue of my Distro (Debian) or of steam.

**Comment by stevethepocket** [comment]
@NovaCygni and @nikikrupka has this been resolved now? The latest patch notes say:

>Fixed low resolution in Big Picture mode due to incorrect video memory detection on Mesa
