### ISSUE TITLE
BigBicture Beta hangs when game is opened in windowed mode

### ISSUE THREAD

**Issue by Wardevour** [ValveSoftware/steam-for-linux#2900]
ran BigPicture then kerbal then it opened windowed and steam was all black and i could see and use unity. once i closed kerbal it sayed that way, black and unresponsive

steam log: http://pastebin.com/MbSRUQfn
lspci: http://pastebin.com/izdYFsbv
lscpu: http://pastebin.com/k3n1acp4

atisysteminfo-report http://pastebin.com/fvcjKtJ8

**Comment by kisak-valve** [comment]
Hello @Wardevour, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
