### ISSUE TITLE
TF2 Intermittent Lockups

### ISSUE THREAD

**Issue by voice06** [ValveSoftware/steam-for-linux#2901]
While playing Team Fortress 2 the game will periodically lock up between 2 to 10 seconds. This has been happening for a while, attached is a older screenshot of what the net_graph is showing during these locks. 
![2013-06-05_00001](https://f.cloud.github.com/assets/4512200/1275702/b87f6d4e-2e03-11e3-8532-a0a4357b3729.jpg)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3068 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 14 Nadia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.5.0-40-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11300000
    X Window Manager:  Marco
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 680/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 325.15
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1180
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 16.14" x 10.08"  (19.02" diag)
                                        41.0cm x 25.6cm  (48.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT2020

Memory:
    RAM:  16048 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  275247 Mb
    Largest Free Hard Disk Block:  133006 Mb

**Comment by kisak-valve** [comment]
Hello @voice06, if you are still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. Closing as general video driver driver performance from 2013 is no longer relevant.
