### ISSUE TITLE
Left 4 Dead 2 (Beta) failed to load (outdated libstdc++ library) and how to fix

### ISSUE THREAD

**Issue by SIR-Taco** [ValveSoftware/steam-for-linux#2904]
The other day I received the following error in the console while attempting to launch L4D2:

Failed to load the launcher (/home/phil/.local/share/Steam/SteamApps/common/Left 4 Dead 2/bin/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/phil/.local/share/Steam/SteamApps/common/Left 4 Dead 2/bin/libtier0.so))
Game removed: AppID 550 "Left 4 Dead 2 (Beta)", ProcID 7063

Possibly I have updated my glib to a newer version and that caused problems (currently running on Arch Linux).

How I fixed the issue was to replace the libstdc++.so.6 in the game's bin/ with my systems current version:

cp /usr/lib32/libstdc++.so.6.0.18 ~/.steam/steam/SteamApps/common/Left\ 4\ Dead\ 2//bin/libstdc++.so.6

Hope this helps someone else if they run into this problem.

Cheers

**Comment by kisak-valve** [comment]
We will be tracking steam runtime issues cumulatively from now on. Closing in favor of #4768.
