### ISSUE TITLE
[Family Sharing Beta] Authorization under Linux allows not to enter PC name

### ISSUE THREAD

**Issue by OneCrazyRussian** [ValveSoftware/steam-for-linux#2905]
On Windows Steam made sure that I change the "Friendly name", same as Steam Guard does, but on Ubuntu it allowed me to authorize a PC (and use it with another account) without doing that. I also can't rename it by any means (only deauthorize)
![2013-10-07 23 57 03](https://f.cloud.github.com/assets/3639846/1283792/bcb20ae2-2f8a-11e3-9179-124f6fb42aa6.png)

Moreover, Steam Guard recognized my PC name under Linux, and Family Sharing didn't

**Comment by kisak-valve** [comment]
Closing as this section of steam client has been reworked and has feature parity between OSes.
