### ISSUE TITLE
Scrolling the chat window with mouse wheel flips a whole page

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#2910]
It scrolls exactly the size of the window now: if the bottom line is half-visible, after scrolling only its bottom half will be on the top of the window. Mouse wheel should only scroll about 3 lines.

**Comment by linweilian03** [comment]
Scrolling in the store page (or other pages) with mouse wheel flips about 15 lines. Flipping 15 lines is too much. 5 lines or 3 lines should be more appropriate.
