### ISSUE TITLE
Steam failed to load: *SteamStartEngine(0xff94d2c0) on latest update

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2914]
Hello,

Steam automatically updated today and I am now unable to play any games.

The error I get when loading up Steam is the following:

"Fatal Error: Steam failed to load: *SteamStartEngine(0xff94d2c0) fail with error 1: A Steam Engine Instance already exists"

However the window opens after I press on the error message's, it does load up Steam but I then cannot open games because it says I do not have an instance of the Steam Engine.

"Steam is not running. You must start Steam in order to play this game."

Smells like some dodgy exception handling has snuck in to the code.

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/steam-for-linux/issues/3154#issuecomment-42761879.
