### ISSUE TITLE
Strange steam regression renders games unplayable from client

### ISSUE THREAD

**Issue by vdevel** [ValveSoftware/steam-for-linux#2920]
Steam build 1381282832/1381282832 
Steam for Linux has a strange regression on launching a game from the client, the game window is black and blank, game hangs, this has happened since June

System info
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2900 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 12.3 (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.10-1.16-desktop
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11302000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2013-09-05

Video Card:
    Driver:  NVIDIA Corporation GeForce 210/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 319.32
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xa65
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 16.14" x 9.06"  (18.50" diag)
                                        41.0cm x 23.0cm  (47.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  11996 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  467278 Mb
    Largest Free Hard Disk Block:  346195 Mb

Installed software:

Recent Failure Reports:
    Wed Sep 25 06:49:38 2013 GMT: file ''/tmp/dumps/assert_20130925094339_1.dmp'', upload no: ''HTTP response code said error''
    Sat Sep 28 08:14:21 2013 GMT: file ''/tmp/dumps/crash_20130928111411_13.dmp'', upload yes: ''CrashID=bp-48932f76-02e2-4722-93a6-654a22130928''
    Fri Oct  4 20:14:50 2013 GMT: file ''/tmp/dumps/crash_20131004231404_11.dmp'', upload yes: ''CrashID=bp-32fc239d-873d-4b96-accf-a7a8d2131004''
    Sun Oct  6 17:49:16 2013 GMT: file ''/tmp/dumps/crash_20131006204905_11.dmp'', upload yes: ''CrashID=bp-ff4ac8a4-7a96-4b0f-a5b7-67bde2131006''
    Mon Oct  7 13:24:12 2013 GMT: file ''/tmp/dumps/crash_20131007162401_11.dmp'', upload yes: ''CrashID=bp-26854c5a-077f-4342-9c82-dde242131007''
    Thu Oct 10 19:05:01 2013 GMT: file ''/tmp/dumps/assert_20131010220414_11.dmp'', upload yes: ''CrashID=bp-c10cdcd2-bf75-45e5-8033-4451d2131010''
    Fri Oct 11 19:58:14 2013 GMT: file ''/tmp/dumps/crash_20131011225812_11.dmp'', upload no: ''Failure when receiving data from the peer''
    Sun Oct 13 13:29:29 2013 GMT: file ''/tmp/dumps/crash_20131013162721_11.dmp'', upload no: ''Couldn't connect to server''

**Comment by kisak-valve** [comment]
Hello @vdevel, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
