### ISSUE TITLE
Steam Hangs if a window is dragged over it (Compositing Related)

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/steam-for-linux#2923]
I've noticed is that steam can freeze or even crash just from dragging a window over it, i also notice that dragging a window over it (be it the steam friends list or some other window) will leave a "trail" similar to what you will see on an old windows XP installation before installing the graphics drivers. It takes some time for the trail to disappear, this only happens with steam and no other application just to be clear.

Steam will usually (if not always) hang when i drag a window over it, and depending on how much/rapidly i drag it over, and how often it will hang longer. The trail although it can take a few seconds to go away will usually be long gone before steam starts responding again.

I have once had steam crash while it was frozen.

The friends list often seems unresponsive as-well and i think that is a related issue. Somtimes dragging the steam window, friends window or conversation window will not be possible (clicking the top of it wont grab a hold of it) and usually when that happens the rest of the window isn't responding either, or if it is responding only specific parts of it are (for example i may be able to type, but i cannot click any buttons)

Dragging the steam window itself doesn't do anything bad (unless it moves over the friends window)

I'm using up-to-date (stable) Archlinux, My WM is openbox, i have an i7, 24GB of RAM and an Nvidia GTX 670 GPU, i'm using nvidia drivers 325.15-9, GTK2 2.24.22-1 and GTK3 3.10.1-1 and steam version 1.0.0.42-1. <- The current versions within the Archlinux Repositories.

**Comment by kisak-valve** [comment]
Hello @Rabcor, are you still experiencing this issue on an up to date system? The way this issue is described makes it sound like the issue was with openbox.

**Comment by kisak-valve** [comment]
Closing pending feedback.
