### ISSUE TITLE
tf2: incredibly slow startup

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#2927]
The native client needs about 5 minutes to start, with wine it's about 20 seconds. Other Orange Box games don't have this problem.

**Comment by kisak-valve** [comment]
Hello @mtmkls, are you still experiencing this issue on an up to date system?

**Comment by mtmkls** [comment]
With Mesa 17.2 the startup speed is adequate. Closing the issue.
