### ISSUE TITLE
AMD FGLRX RadeonSI Drivers Cuts FPS in Half When Steam is Running

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#2928]
Simply put, I was just testing some non-steam games in Wine in Ubuntu 13.10, which releases within the next 12 hours, with my HD 7950 and noticed that when Steam had yet to be installed, I had ~730FPS. However, later, after I installed Steam and Steam was running in the background (not using overlay), the same game then ran at 300FPS. After exiting from Steam, the game was able to run at 730FPS again.

Later, I've tested in Ubuntu 13.04 with Catalyst 13.8 and 13.11 and the same issue exists.

Therefore, there's an AMD driver bug affecting Catalyst (not sure if it affects the open source drivers, but those drivers are very unstable with my GPU).

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
