### ISSUE TITLE
Can't turn off reminder to update drivers

### ISSUE THREAD

**Issue by neonmagnets** [ValveSoftware/steam-for-linux#2950]
I use a radeon 6900 series and the experimental-13 performs way worse than experimental-12. So, naturally, I went back to 12, and every time I start steam a window pops up telling me to "upgrade". Please give us some way to turn this off, or just tell me once.
Maybe 3 buttons: upgrade/remind me later/don't ask me again ?

**Comment by kisak-valve** [comment]
Hello @neonmagnets, steam no longer checks for driver updates on any platform. Closing.
