### ISSUE TITLE
Ticket to Ride doesn't work

### ISSUE THREAD

**Issue by Alarmfifa** [ValveSoftware/steam-for-linux#2951]
Ticket to Ride doesn't work from Steam.
If I launch the game manually (without Steam) it works perfectly.
(I mean $ cd ~/.local/share/Steam/SteamApps/common/Ticket\ to\ Ride/ && ./custom-ticket-to-ride-64 )
But when I try to launch it from Steam interface, a java process hangs and the game doesn't start.
Unfortunately, if I launch T2R not from Steam, there are no purchased maps =( consequently, I can't play at all...

My sysinfo is [here](https://gist.github.com/Alarmfifa/d5920ab2f3ea17ee7319).

**Comment by kisak-valve** [comment]
Hello @Alarmfifa, are you still experiencing this issue?

**Comment by Alarmfifa** [comment]
Hi!
I've just tested, it seems works. Thanks! =)

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
