### ISSUE TITLE
Team Fortress 2 Halloween crash log and dump file

### ISSUE THREAD

**Issue by Freddi** [ValveSoftware/steam-for-linux#2952]
Here are the last entries in a terminal before Team Fortress 2 crashes.

Running Ubuntu 13.10 Desktop 64-bit on an AMD Radeon HD5850 with the Gallium driver.

Dump file: https://dl.dropboxusercontent.com/s/ym5e6ol872y5e6s/crash_20131030103931_1.dmp

CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
CTexture::GetTextureHandle(): nFrame is < 0!
Model '(null)' doesn't have attachment 'backblast' to attach particle system 'rocketbackblast' to.
Model '(null)' doesn't have attachment 'backblast' to attach particle system 'rocketbackblast' to.
BlackOUploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20131030103931_1.dmp
/mnt/0fec8883-e4a0-46f9-ba38-68559662d66f/Steam/SteamApps/common/Team Fortress 2/hl2.sh: line 67: 14948 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 440 "Team Fortress 2", ProcID 14948 
Finished uploading minidump (out-of-process): success = no
error: Failure when receiving data from the peer

**Comment by kisak-valve** [comment]
Closing per the last comment.
