### ISSUE TITLE
No in-game sound in BPM, sound ok in DM

### ISSUE THREAD

**Issue by teeedubb** [ValveSoftware/steam-for-linux#2953]
Hey all,

Ive been slowly setting up steam on ubuntu 13.10 x64 minimal with a Openbox desktop environment with no pulse audio, only alsa. In Big Picture Mode I get the ambient and navigation sounds but no sound in either l4d2 or serious sam 3 and disabling all GUI sounds has no effect. If I launch the games from Desktop Mode I get sound in both games. Looking at the game logs the sound device is busy when launching a game via BPM. I am using a ~/.asoundrc, with out it I get no sound at all:

```
    pcm.!default {
    type hw
    card 0
    device 3
    }

    ctl.!default {
    type hw
    card 0
    device 3
    }
```

Steam cli output when running two games, first from desktop mode, 2nd in BPM. Cav Story + will crash instantly on load if run from BPM, fine in DM.

http://paste.ubuntu.com/6329569/

I've tried using the following environmental variables with out any luck

```
    SDL_AUDIODRIVER=alsa
    STEAM_RUNTIME=0 steam
```

I only have the one sound card enabled and only one module loaded in /proc/asound/modules. I can load steam desktop mode, launch a game - get sound, close the game, switch to steam bpm, launch a game with no sound. I get sound in both xbmc + chromium too.

Not sure if this is a bug or if I'm missing something obvious? Is steam BPM not ALSA compatible? Has anyone got it working with pure ALSA? 

Original forum thread http://steamcommunity.com/app/221410/discussions/0/810939351350711180/

**Comment by kisak-valve** [comment]
Closing as this a system config issue and appears to have been resolved.
