### ISSUE TITLE
Show Online Friend Only Error

### ISSUE THREAD

**Issue by caisar** [ValveSoftware/steam-for-linux#2956]
I found that checked "show online friend only" will show your offline contacts and unchecked will show online frined only.
![screenshot from 2013-11-01 18 48 55](https://f.cloud.github.com/assets/5735742/1453220/7960824e-42ec-11e3-9513-c8311f8502ce.png)
![screenshot from 2013-11-01 18 49 33](https://f.cloud.github.com/assets/5735742/1453224/8f15dfe4-42ec-11e3-80e9-dc3ebc1a0edd.png)

**Comment by kisak-valve** [comment]
Hello @caisar, are you still experiencing this issue on an up to date system?

**Comment by caisar** [comment]
@kisak-valve no. its work perfectly with up to date system.
