### ISSUE TITLE
Steam message boxes are visually corrupt

### ISSUE THREAD

**Issue by Freddi** [ValveSoftware/steam-for-linux#2960]
As seen on the screenshot. Using Ubuntu 13.10 Desktop 64-bit with the Gallium free software graphics processing unit driver.

![steam-visually-corrupted-message-box-window](https://f.cloud.github.com/assets/3420089/1460937/6a90542e-4481-11e3-948e-e8f11514f69c.png)

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago.
