### ISSUE TITLE
Fullscreen games show a black screen, same with Big Picture mode

### ISSUE THREAD

**Issue by aleksander13** [ValveSoftware/steam-for-linux#2967]
I can't play any game, unless I play them in window mode. But even then, it lags horribly. I used all the drivers available in the Additional Drivers setting, but to no effect. I tried both the stable and the beta versions of the drivers from the AMD website, but that didn't help either. Here are my specs. Help?

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x6
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3705 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    elementary OS Luna (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-51-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Gala
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6570

```
Driver Version:  4.2.12172 Compatibility Profile Context 13.25.18
OpenGL Version: 4.2
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6759
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 16.14" x 9.06"  (18.50" diag)
                                        41.0cm x 23.0cm  (47.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1705

Memory:
    RAM:  5970 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  80470 Mb
    Largest Free Hard Disk Block:  71187 Mb

Installed software:

Recent Failure Reports:
    Tue Nov  5 20:44:42 2013 GMT: file ''/tmp/dumps/assert_20131105224428_23.dmp'', upload yes: ''CrashID=bp-45f32aac-b390-44d3-b38e-810322131105''

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
