### ISSUE TITLE
Steam crashes when loading Portal from Big Picture Mode

### ISSUE THREAD

**Issue by mhess126** [ValveSoftware/steam-for-linux#2970]
Running amd HD7850 w/ latest beta catalyst.  When running Portal from Big Picture, the game video never appears.  I hear the "Valve tone" and then Big Picture becomes unresponsive.

When running Portal from the regular Steam UI, it loads properly.

**Comment by kisak-valve** [comment]
Hello @mhess126, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
