### ISSUE TITLE
Direct Rendering Detection Error

### ISSUE THREAD

**Issue by arrowsama** [ValveSoftware/steam-for-linux#2971]
Steam (since update on Oct 30) is crashing on direct rendering pointing to this page: https://support.steampowered.com/kb_article.php?ref=9938-EYZB-7457

I also had this error when trying the beta client about three weeks ago. I _think_ that the client is checking the direct rendering support for the dgpu (amd) and not the igpu (intel) which is actually the one I'm using ("libGL error: AtiQueryDirectRenderingCapable failed").

Computer is a laptop Vaio VPCSA25GX which might be using a non-standard amd+intel pairing (in windows, official amd drivers won't install, they ask to install sony provided drivers)

Steam: An X Error occurred
X Error of failed request:  BadRequest (invalid request code or no such operation)
Major opcode of failed request:  155 (ATIFGLEXTENSION)
Minor opcode of failed request:  66
Serial number of failed request:  35
xerror_handler: X failed, continuing
Error: OpenGL GLX context is not using direct rendering, which may cause performance problems.

$ ldd ./glxinfo
        linux-gate.so.1 =>  (0xf7774000)
        libGL.so.1 => /usr/lib/i386-linux-gnu/mesa/libGL.so.1 (0xf76f4000)
        libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xf75bd000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7409000)
        libglapi.so.0 => /usr/lib/i386-linux-gnu/libglapi.so.0 (0xf73f2000)
        libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xf73e0000)
        libXdamage.so.1 => /usr/lib/i386-linux-gnu/libXdamage.so.1 (0xf73dc000)
        libXfixes.so.3 => /usr/lib/i386-linux-gnu/libXfixes.so.3 (0xf73d5000)
        libX11-xcb.so.1 => /usr/lib/i386-linux-gnu/libX11-xcb.so.1 (0xf73d1000)
        libxcb-glx.so.0 => /usr/lib/i386-linux-gnu/libxcb-glx.so.0 (0xf73b9000)
        libxcb-dri2.so.0 => /usr/lib/i386-linux-gnu/libxcb-dri2.so.0 (0xf73b4000)
        libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xf7392000)
        libXxf86vm.so.1 => /usr/lib/i386-linux-gnu/libXxf86vm.so.1 (0xf738c000)
        libdrm.so.2 => /usr/lib/i386-linux-gnu/libdrm.so.2 (0xf737e000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7363000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf735e000)
        /lib/ld-linux.so.2 (0xf7775000)
        libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xf735a000)
        libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xf7353000)

$ ./glxinfo | egrep -i 'direct rend|draw_buffers2|string'
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2
OpenGL version string: 3.0 Mesa 9.1.4
OpenGL shading language version string: 1.30
    GL_ARB_vertex_array_object, GL_ATI_separate_stencil, GL_EXT_draw_buffers2,

**Comment by kisak-valve** [comment]
Hello @arrowsama, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver issues from 2013 is no longer relevant.
