### ISSUE TITLE
Counter strike font problem

### ISSUE THREAD

**Issue by Tamq** [ValveSoftware/steam-for-linux#2974]
When i start Counter Strike on Linux Mint 15 (Olivia) i have bad font in game.
Just look at screens, i can't read nothing.

Sorry for bad English, i'm from Poland :D 
![2013-11-03_00001](https://f.cloud.github.com/assets/5880775/1496008/0cc711ae-47f4-11e3-82c5-8341b2b2e558.jpg)

Anyone have an idea what is wrong?

**Comment by kisak-valve** [comment]
Hello @Tamq, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If you're still experiencing this issue, please open a new issue report in the [halflife](https://github.com/ValveSoftware/halflife) issue tracker. Closing.
