### ISSUE TITLE
Zero Byte Update To Half Life on Every Start

### ISSUE THREAD

**Issue by 3vi1** [ValveSoftware/steam-for-linux#2975]
For months, I've noticed that each time I start steam I get a game update for Half-Life.  The update is always zero bytes and completes instantly.  The game itself plays fine.

I've tried completely deleting the local content and reinstalling the game, but the issue persists.

![steam_041](https://f.cloud.github.com/assets/628806/1501345/192c830c-488a-11e3-9cd7-9602fc67ce51.png)

**Comment by 3vi1** [comment]
I haven't seen this bug recur in nearly a year now, and I don't see anyone else reporting otherwise in that time.  Closing.

**Comment by Plaque-fcc** [comment]
> I haven't seen this bug recur in nearly a year now, and I don't see
> anyone else reporting otherwise in that time.  Closing.

I didn't report that because I got used to it. Shame on me, but it
happens rarely, and recently I removed almost all HL2-based games. But
I've seen that 2-3 months ago, AFAIR.
