### ISSUE TITLE
Big Picture mode goes to a black screen

### ISSUE THREAD

**Issue by ribeirobreno** [ValveSoftware/steam-for-linux#2977]
1 - Start steam with a regular monitor (here: LG W1752T) via VGA cable
2 - Turn off the monitor and remove the cable
3 - Plug the VGA cable to a TV (here: Philips 32PFL5604/78)
4 - Turn the TV on
5 - Start Big Picture

The sounds can be heard and pressing alt+F4 takes steam out of BP mode.
Restarting steam before step 5 makes it work as expected.

System info:
https://gist.github.com/ribeirobreno/b9e54da8bda64d901835

**Comment by kisak-valve** [comment]
Hello @ribeirobreno, are you still experiencing this issue on an up to date system?

**Comment by ribeirobreno** [comment]
@kisak-valve haven't tried this in a while, i will try again and see if it still happens.
My answer may come after the weekend as i am away from this machine. :)

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by sebekk23** [comment]
I have the similar problem with SHARP LCD TV - i made my own steam machine which dosen't have keyboard (only 2 controllers) and steam goes black after while when not used (i think it might be realted with screen saver in steam - i disabled screen saver in openbox settings and also in steam).

**Comment by sebekk23** [comment]
And one more thing - when mouse is plugged i can "wake up" steam with any mouse move, but i can not do the same with steam controller or with xbox controller.

**Comment by kisak-valve** [comment]
Hello @sebekk23, that sounds like the display is being turned off by [DPMS](https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling) power management. This is set separately from the screensaver with some desktop environments.

**Comment by TiagoTiago** [comment]
I get this occasionally; not sure what makes it start happening, nor what makes it stop happening.

**Comment by TiagoTiago** [comment]
Oh, and the controller config window, even outside of BigScreen mode seems to be just loading a blank black window as well. I hear the sounds when I move the stick of the controller, which makes it sound like it is working behind the scenes, but it just isn't rendering the GUI correctly.

**Comment by BrenniusXIV** [comment]
I have the same issues as @TiagoTiago described: launching Big Picture mode through Steam, Steam Link, or opening the controller config window from the regular Steam Library just brings up a black screen with all the sounds and button presses still being recognized. I haven't experienced this before recently (maybe the last month or so).
