### ISSUE TITLE
DotA2 fails to launch when Mesa is compiled with DRI3 support and the runtime is enabled

### ISSUE THREAD

**Issue by heftig** [ValveSoftware/steam-for-linux#2981]
Arch Linux x86_64

Mesa libGL with DRI3 support loads libxcb-dri3, which isn't in the runtime, so it's taken from the system.

libxcb-dri3 needs the symbol xcb_send_fd, which is in the system libxcb, but not in the runtime one. Hence the symbol cannot be found and the linker fails.

**Comment by kisak-valve** [comment]
Per the [2017-01-05 steam beta update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256), does this issue still occur with the beta client?

**Comment by kisak-valve** [comment]
Thanks for retesting @heftig. Closing as fixed.
