### ISSUE TITLE
Steam for Linux Video Driver Updates leading to graphics issues for new users

### ISSUE THREAD

**Issue by cthornett** [ValveSoftware/steam-for-linux#2984]
This is closer to a feature request than an actual bug.

I'm using Ubuntu 12.04.3 and Nvidia's 304 driver, which is the 'current driver' option specified in the Ubuntu Software Center. 

The Steam for Linux at start checks for Video Driver Updates and will throw up a window that tells a user that they must upgrade to 319 drivers as that is a more recent driver version.

Clicking 'Upgrade' creates an internal error most of the time.

Cancelling removes the window, but it leaves the user with a dilemma, either they continue using 304 drivers or, as many new users will do, they will go ahead and download the 319 drivers from Nvidia and attempt to install them. Gamers, particularly those moving from Windows, will always assume that the latest drivers are the best option (unless they are labelled as beta).

What ultimately has happened to me is that I installed them manually (stopped X to install them etc) and now have a system that doesn't boot into the desktop. I'll figure out how to purge the drivers and get my screen working again, but the point is that I'm using the recommended version of Ubuntu for Steam and shouldn't be experiencing this kind of thing.

My assumption is that either the automatic Check for Video Drivers Update doesn't check to see whether the installed Nvidia driver is the currently supported driver by the distro (in my case Ubuntu) or that the distros aren't supplying that information to the Steam team. I assume it just checks to see what the latest graphics driver is for your hardware and throws up the result.

In terms of user experience, the messages from the Steam for Linux client are confusing for new users and can lead to a less than smooth Linux experience and we don't want that. Thanks!

**Comment by kisak-valve** [comment]
Closing as steam no longer provides this functionality.
