### ISSUE TITLE
Steam client crash on Ubuntu 13.10

### ISSUE THREAD

**Issue by bbfan** [ValveSoftware/steam-for-linux#2986]
I could launch steam client when i am using Ubuntu 13.04, however, when i recently update the system to 13.10 and find steam will not launch anymore. 
Below is the detailed information.
![screenshot from 2013-11-08 18-34-40](https://f.cloud.github.com/assets/5935676/1538433/1dcad742-4ce5-11e3-93c2-bd4d0d2476a1.png)

**Comment by kisak-valve** [comment]
Closing as general video driver issues from 2013 is no longer relevant. If anyone here is still experiencing this issue, please reach out to your distro's community for help getting your OpenGL driver working.
