### ISSUE TITLE
[Linux] Enlightenment17DE: Display mode crashes

### ISSUE THREAD

**Issue by Pon3** [ValveSoftware/steam-for-linux#2992]
Sometimes, when I switching between windows or virtual desktops, full screen mode crashes and switches to window mode, and I have to hit alt+ctrl+F to switch it back to full screen mode (yea, big deal). But anyway, fix it please!) The problem appears only with Enlightenment17 DE.

**Comment by kisak-valve** [comment]
Hello @Pon3, are you still experiencing this issue on an up to date system?

If you are, please clarify if full screen mode as described here is steam's Big Picture Mode or the desktop client full screened by the DE. You make it sound like it is the latter and at no point does the steam client actually stop running.

**Comment by kisak-valve** [comment]
Closing pending feedback.
