### ISSUE TITLE
Ugly text alignment in game properties box on latest beta

### ISSUE THREAD

**Issue by mcl21014** [ValveSoftware/steam-for-linux#2993]
Well, the issue is self-explanatory. Look at the alignment, guys. It's pretty ugly. I'm on Ubuntu 13.10 64 bit. To reproduce, just right click a game and click properties. System info just in case:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2534 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.0-031200-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ironlake Mobile x86/MMX/SSE2

```
Driver Version:  2.1 Mesa 9.2.1
OpenGL Version: 2.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x68e4
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 15.04" x 8.46"  (17.24" diag)
                                        38.2cm x 21.5cm  (43.8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: IDT 92HD81B1X5

Memory:
    RAM:  7782 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  468645 Mb
    Largest Free Hard Disk Block:  341867 Mb

Installed software:

Recent Failure Reports:

And there you are. I'll also attach a screenshot.

**Comment by kisak-valve** [comment]
Closing in favor of #1443.
