### ISSUE TITLE
BPM: no controller detected (0666 permissions in /dev/input/eventX)

### ISSUE THREAD

**Issue by fjvazquezaraujo** [ValveSoftware/steam-for-linux#2995]
I know there have been a lot of people complaining about their controller not being detected in big picture mode, but in all the forum threads/bug reports/blog posts etc I've seen the problem was caused by bad permissions in /dev/input/eventX. That's not my case. 

I'm trying to use an Xbox 360 controller in BPM (I've also tried with an old Saitek P880; it has the same problem). I'm running Steam in a 32bit chroot in Gentoo. I can cat /dev/input/event6 and /dev/input/js0 as any user, and it prints characters as I use the gamepad, both outside and inside the chroot. Some games I've tested work fine with the controller (And Yet It Moves, Stealth Bastard Deluxe, Shatter...). But not Steam. 

Is there any way to find out why is it failing?

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
