### ISSUE TITLE
Bug in steamclient.so

### ISSUE THREAD

**Issue by morfin60** [ValveSoftware/steam-for-linux#2999]
I have a problem with SRCDS for Linux(and steamclient.so): when server is trying download from Steam Workshop it's crashing with next error:
pipes.cpp (659) : Assertion Failed: bRet
Assert( Assertion Failed: bRet ):/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp:659

ExceptionHandler::GenerateDump waitpid failed:ExceptionHandler::WaitForContinueSignal sys_read failed:Invalid argument
Bad file descriptor
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20131109002902_1.dmp
pipes.cpp (730) : Assertion Failed: CClientPipe::BWriteAndReadResult: BReadResult failed
interfacemap_client.h (1508) : Assertion Failed: bufRet.GetUint8() == k_EClientCommandInterface
Finished uploading minidump (out-of-process): success = no
error: Failed to open/read local data from file/application
Sat Nov 9 01:06:25 YEKT 2013: Server Quit

I am trying to run it on FreeBSD 9.2(amd64) using linux(x86) compatibility(with Debian enviroment and kernel module).
 Also steamcmd which i used to download SRCDS had issue with pipes.cpp too(but there was another error):
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp (723) : Assertion Failed: Stalled cross-thread pipe
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp (723) : Fatal assert failed: /home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/clientdll/../common/pipes.cpp, line 723. Application exiting.
that's what steamcmd says when i am downloading content(can happen in any moment)

**Comment by kisak-valve** [comment]
Hello, can someone check if this is still an issue on an up to date release of *BSD?

**Comment by tynorton** [comment]
It's still happening for me

```
[norton@cumulus ~]$ steamcmd/steamcmd_freebsd.sh +login anonymous +force_install_dir C:\ArkServer3 +app_update 376030 +quit
Redirecting stderr to '/home/norton/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...opensslconnection.cpp (1393) : Assertion Failed: unable to load trusted SSL root certificates
OK.

Connecting anonymously to Steam Public...net.cpp (1913) : Assertion Failed: Unable to set default socket options, error 22
net.cpp (1913) : Assertion Failed: Unable to set default socket options, error 22
net.cpp (1913) : Assertion Failed: Unable to set default socket options, error 22
net.cpp (1913) : Assertion Failed: Unable to set default socket options, error 22
cminterface.cpp (2591) : Assertion Failed: m_VecNetAdrNetFilterCMs.Count() > 0
Retrying. . .
^C
[norton@cumulus ~]$ freebsd-version
11.1-RELEASE-p1
[norton@cumulus ~]$
```

**Comment by kisak-valve** [comment]
Hello @morfin60. your console spew indicates an issue with steamcmd, not srcds. Please open a new issue report for your issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.

If this is still an issue with srcds, then please open a new issue in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker and the steamcmd variant is at #3141.
