### ISSUE TITLE
[Linux] Few games crashing due to working Steam

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#3000]
This problem affects 3 games in my library: 'Metro: Last Light', Worms Reloaded and Natural Selection 2. 
This games are crashing if i launching them from Steam for Linux client.
But if i shutdown Steam and launch game manually from file manager (only Metro and Worms can be launched in this way), it launches Steam and starts itself and works normally.
After that any of described games can be launched from client.

My PC specs (translated): http://pastie.org/8492759

**Comment by kisak-valve** [comment]
Hello @Shished, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
