### ISSUE TITLE
Installation fails on fresh install of Ubuntu 13.1

### ISSUE THREAD

**Issue by opeterson** [ValveSoftware/steam-for-linux#3001]
Hello!

I was told by steam support to post this issue here on GitHub, so the following is a copy of what I put in my ticket. Please let me know if I you need more information and I'll do the best I can to provide what you might need. 

Thanks!

I'm having some issues installing steam on Ubuntu 13.10, which I know isn't supported yet, but I thought it might be good to file this ticket anyway.

I downloaded the installer from steampowered.com and ran it through the ubuntu software center, and that part of the installation worked fine. However once I ran steam the first time, I encountered this error:

oapeter@oapeter:~$ Repairing installation, linking /home/oapeter/.steam/steam to /home/oapeter/.local/share/Steam
rm: cannot remove ‘/home/oapeter/.steam/steam’: Is a directory
Setting up Steam content in /home/oapeter/.local/share/Steam
rm: cannot remove ‘/home/oapeter/.steam/steam’: Is a directory

So I deleted /home/oapeter/.steam/steam, which led to the following errors:

Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/oapeter/.local/share/Steam/steam.sh: line 755: 5754 Segmentation fault (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/oapeter/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/oapeter/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/oapeter/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/oapeter/.local/share/Steam/steam.sh: line 755: 5871 Segmentation fault (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"

I don't really expect anything out of this ticket, I just hope that it can help in some way with the development of a 13.10 version of Steam.

Thanks!

**Comment by kisak-valve** [comment]
Hello, if anybody is still experiencing this issue on an up to date system, it'll need a new investigation in order to figure out what's gone wrong. Closing.
