### ISSUE TITLE
Email verification via Linux client does not send email

### ISSUE THREAD

**Issue by gmjck** [ValveSoftware/steam-for-linux#3003]
For about as long as the official Steam for Linux client has been available, my client has been displaying the "Is this still your current address?" green banner. Every once in a while I'll try getting rid of it by clicking "Yes". This brings up the "Verify Email" dialog. Clicking next briefly displays the "Contacting Steam Servers" message, and then displays the "A message has been sent to: [my address]".

But I never receive the verification email. I've checked Junk folders and spam filters; nothing should be blocked. Other Steam emails come through fine: new computer confirmations, marketplace transactions, game purchases, etc.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2833 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 15 Olivia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6800 Series 

```
Driver Version:  4.3.12614 Compatibility Profile Context 13.20.5
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6738
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 3840 x 1200
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3953 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  703361 Mb
    Largest Free Hard Disk Block:  488180 Mb

Installed software:

Recent Failure Reports:
    Sat Nov 23 18:39:04 2013 GMT: file ''/tmp/dumps/assert_20131123133831_13.dmp'', upload yes: ''CrashID=bp-a176d951-2451-42f8-a328-462222131123''

**Comment by kisak-valve** [comment]
Hello @gmjck, @Undeterminant, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
