### ISSUE TITLE
Large Mode Window Invisible After Exiting Big Picture Mode

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#3004]
The large mode window was invisible after exiting big picture mode.  Hovering over menu items still produced menus.  Opening up child windows worked, and they could be placed behind the invisible main steam window.

![screenshot from 2013-11-24 10 58 04](https://f.cloud.github.com/assets/6024315/1608977/af2e1b1c-5524-11e3-852c-e0d7c69bda07.png)

**Comment by kisak-valve** [comment]
Hello @nightsky30, have you seen this issue since the initial incident?

**Comment by nightsky30** [comment]
Hey @kisak-valve, I do still have this system lying around.  It has not functioned as my main system for a while, but I can throw the latest Ubuntu/Nvidia/Steam versions on there and test it out.

I was and am no longer using the Unity DE, and Ubuntu is not continuing new development after 17.04, Unity will still live on with 16.04 for quite a while.  So maybe this is still relevant for the time being.

Let me give it a shot.

**Comment by nightsky30** [comment]
And also I guess it might not be a Unity issue at all, but perhaps Nvidia/Steam...

**Comment by nightsky30** [comment]
@kisak-valve, I can't reproduce the bug.  It could have been fixed in many ways.  Thank you.  Closing.
