### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nilscab** [ValveSoftware/steam-for-linux#3006]
Dear people of valve, please, please, please! add support to nvidia legacy driver 173.xx.xx, counter strike runs awesome in a fx5500 even better then windows, the only thing why i can't switch entirely to linux is the steam client, i can't believe i can play cs in xp, vista or windows 7 whit this card but no in linux i mean c'mon

**Comment by kisak-valve** [comment]
While the steam client does not explicitly check for driver versions anymore, it generally expects GL 2 capable hardware. Your mileage will vary with hardware before that. There's no reasonable expectation for pre-GL2 hardware to gain support in the future.
