### ISSUE TITLE
Dota 2 and TF2 loading speed

### ISSUE THREAD

**Issue by deri82** [ValveSoftware/steam-for-linux#3007]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3511 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.0-031200rc7-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7800 Series

```
Driver Version:  4.3.12614 Compatibility Profile Context 13.25.18
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x679e
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18,82" x 10,59"  (21,57" diag)
                                        47,8cm x 26,9cm  (54,8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7904 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  930696 Mb
    Largest Free Hard Disk Block:  821773 Mb

Installed software:

Recent Failure Reports:

It is very slow. 

Haven't measured but I think it's close to 1 minute on TF2

**Comment by kisak-valve** [comment]
Hello @deri82, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
