### ISSUE TITLE
[Resolved] Arch Linux - Network: "Select a Network" is blank

### ISSUE THREAD

**Issue by jschroed** [ValveSoftware/steam-for-linux#3009]
I'm running a 64-bit install of Arch Linux without a Desktop Environment (DE). When I first started up steam, it asked for Language settings etc., and then when it got to "Network - Configure your network settings - Select a Network", it was blank.

Network settings works okay on my Ubuntu PC. I thought maybe there was a package missing that Steam needs for Network settings (especially since that net-tools is not installed by default because it is deprecated). I tried install both "net-tools" and "networkmanager" but the Steam Network Settings is still blank.

Is there a package that Steam needs for Network Settings or could there be something else causing this issue on Arch Linux?

Edit:
The fix was to install the 32-bit version of NetworkManger at https://aur.archlinux.org/packages/lib32-networkmanager/ and run this command to get NetworkManager to run at start up:

```
systemctl enable NetworkManager
```

I was pointed to some information for Steam on Arch at: https://wiki.archlinux.org/index.php/Steam#Using_native_runtime

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.
