### ISSUE TITLE
ALT + F4ing Steam while a YouTube video is playing doesn't stop the video

### ISSUE THREAD

**Issue by Dmck2b** [ValveSoftware/steam-for-linux#3016]
Basically, if I force close the main Steam window with a YouTube video playing within it, the video's audio (and presumably the video) keeps on playing the background, forcing you to reopen Steam and load a different page to stop it.

Issue is not prevalent with Steam hosted videos (Eg, game trailers on store pages.)

For me, bug was noticed and replicable on http://steamcommunity.com/sharedfiles/filedetails/?id=160936704

System details https://gist.github.com/Dmck2b/5b76ccd8e44502602075

**Comment by kisak-valve** [comment]
Hello @Dmck2b, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
