### ISSUE TITLE
"Play now" links from Firefox won't launch Steam

### ISSUE THREAD

**Issue by Xodetaetl** [ValveSoftware/steam-for-linux#3018]
This is a Firefox issue but it affects Steam in a pretty dramatic way and I believe Valve and / or Steam users can have some weight in making Mozilla people solve it faster.

The bug is: with Firefox in Ubuntu, clicking on the "Play now" link in the store page of owned games won't launch Steam. Instead you get a popup asking you to choose the application to use for this type of links and then you have to browse the filesystem to find the Steam executable – not user-friendly at all.

The problem is reported [here at Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=397700). It needs more people to show there is interest in seeing it fixed fast. 
I've opened a [money bounty](http://freedomsponsors.org/) to help with this. It's a crowdfunding site for fixing issues in libre software, people pledge money, someone picks the job and people pay her when the patch is satisfying and implemented.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved upstream.
