### ISSUE TITLE
Buy menu doesn't work (CS:S / Ubuntu 12.04 LTS)

### ISSUE THREAD

**Issue by Riphath** [ValveSoftware/steam-for-linux#3022]
My buy menu displays fine, but does not allow me to buy anything (exception: autobuy works) - both using menu numbers and clicking on the buttons causes me to exit the buy menu, and leaves a message in the console stating: "Unknown command: Resource/UI/BuyPistols_CT.res" (equivalent message for every category on the buy menu).
Everything else works great, I just can't buy anything unless I use 'autobuy'!

I did try Verify Integrity of Game Cache, but it found no issues.
I initially got this error running CS:S on Lubuntu 13.10 - reformatted and installed Ubuntu 12.04 LTS / Steam / CS:S all from fresh downloads, and ran into the same problem.
This happens every time I run CS:S - I just start it, Create Server, join a team and try to buy something.

System Information:

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0xf
    CPU Model:  0x4b
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  2400 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-34-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  NVIDIA Corporation GeForce 7600 GT/PCIe/SSE2

    Driver Version:  2.1.2 NVIDIA 304.88
    OpenGL Version: 2.1
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x391
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                            52.1cm x 29.3cm  (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM Not Detected
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  281482 Mb
    Largest Free Hard Disk Block:  246135 Mb

Installed software:

Recent Failure Reports:
    Sat Dec  7 02:54:55 2013 GMT: file ''/tmp/dumps/assert_20131206195433_12.dmp'', upload yes: ''CrashID=bp-499ed292-bbab-4172-8722-083222131206''
```

**Comment by kisak-valve** [comment]
Hello @Riphath, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Riphath** [comment]
I had forgotten all about this trouble ticket, honestly. I hadn't logged into my gaming email account for a while, so just saw the last two comments now.
I built a new computer two weeks ago (running ArchLinux now), and installed Steam and CounterStrike: Source - everything seems to be working perfectly without any adjustments needed! As far as I'm concerned, this is resolved.
