### ISSUE TITLE
Steam and Bumblebee: "SteamUpdateUI: An X Error occurred"

### ISSUE THREAD

**Issue by pank** [ValveSoftware/steam-for-linux#3027]
Hi,

I am trying to move to the Linux Steam client (from Wine).  I use a Thinkpad W530 with Intel and a discrete NVIDIA K2000M.

I have insalled Bumblebee and primus.  I'm able to run glxgears and Crusader Kings 2 via Wine-Steam with both optirun and primus.  I have tried the fixes that I could find by searching on strings such as `SteamUpdateUI: An X Error occurred` (see below), but without luck.

I have tried many different versions of Steam and Linux (the Kernel). I have tried various combinations of drivers without success which.

My software stack is: Linux 3.12.3 (64bit) (with CK-patches to make NVIDIA work), Bumblebee 3.2.1, Primus (plus lib32) 20131027, nvidia propriatary drivers 331.20, nvidia utils (plus lib32) 331.20, xf86-video-intel 2.21.15, intel-dri 9.2.4 (plus lib32), Steam 1.0.0.45.

Following is the output to the console when launching Steam and glxinfo.  Please let me know if you need anything else.

I appreciate you guys looking into this,
Rasmus

Steam with Intel graphics:
https://gist.github.com/anonymous/7919553  (old: ~~https://gist.github.com/anonymous/7858133~~)

Via `primusrun`:
https://gist.github.com/anonymous/7919573 (old: ~~https://gist.github.com/anonymous/7858120~~)

`glxinfo`s.  First Intel:
https://gist.github.com/anonymous/7858112

Then NVIDIA:
https://gist.github.com/anonymous/7858098

**Comment by kisak-valve** [comment]
Hello @pank, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
