### ISSUE TITLE
Immediate client exit: Failed to load steamui.so: AMD 13.11beta-v9.4 / Ubuntu 13.04 x86_64

### ISSUE THREAD

**Issue by wackston** [ValveSoftware/steam-for-linux#3028]
Platform see above.

Downloading and running steam on this platform results in 

Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1386125885_client)
Xlib:  extension "XFree86-DRI" missing on display ":0.0".
Installing breakpad exception handler for appid(steam)/version(1386125885_client)
[2013-12-08 15:57:38] Startup - updater built Dec  3 2013 18:36:06
[2013-12-08 15:57:38] Verifying installation...
[2013-12-08 15:57:38] Verification complete
[2013-12-08 15:57:40] Shutdown

Investigations with DEBUGGER=strace, and ldd-ing for missing libraries etc didn't reveal anything untoward.  

.local/share/Steam/ubuntu12_32/steam is execve-ed.  
steamui.so and a bunch of shared libraries are loaded,
X server is polled for a bunch of extensions strings, 
a font "mut-clearlyu" is queried and 
the connection to X is then shutdown and an there's an orderly exit.

 Any suggestions for further investigations or is this a known problem?

**Comment by kisak-valve** [comment]
Hello @wackston, are you still experiencing this issue with an up to date system?

**Comment by wackston** [comment]
No,

Alls well again these days.


Best regards,

Andrew

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
