### ISSUE TITLE
Missing multiarch support in cracklib2 causes segfault in several games when using sssd

### ISSUE THREAD

**Issue by chrisaq** [ValveSoftware/steam-for-linux#3031]
When using sssd for users on 64bit systems several games segfault when trying to find a non-existing libnss-sssd:i386. This cannot be installed because of missing multiarch support in ubuntus cracklib2.

This seems to be on the way though:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=679962

This affects the following games that I have in my library:
Anomaly Korea
Anomaly Warzone Earth
Anomaly Warzone Earth Mobile Campaign
Crusader Kings II
Europa Universalis
Hotline Miami

And probably several others.

**Comment by kisak-valve** [comment]
Hello @chrisaq, are you still experiencing this issue on an up to date system?

**Comment by chrisaq** [comment]
@kisak-valve Hi

I have changed distros since this happened 4 years ago.
I see that ubuntu now has a i386 version of cracklib though, so I would guess this is solved.

**Comment by kisak-valve** [comment]
Thanks for checking, closing.
