### ISSUE TITLE
[GarrysMod] Crash on starting a multiplayer game

### ISSUE THREAD

**Issue by WindohsCrasher** [ValveSoftware/steam-for-linux#3032]
When starting a new game and selecting other than "Singleplayer" in the Combobox (e.g. "2 players"), the whole UI freezes.

This has been tested on the following system:

Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x2a
    CPU-Stepping: 0x7
    CPU-Typ: 0x0
    Geschwindigkeit: 3800 MHz
    8 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "openSUSE 13.1 (Bottle) (x86_64)" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.11.6-4-desktop
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11403901
    X-Fenstermanager: KWin
    Steam-Runtime-Version: steam-runtime-release_2013-10-23

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 760/PCIe/SSE2
    Treiber-Version: 4.4.0 NVIDIA 331.20
    OpenGL-Version: 4.4
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x1187
    Anzahl der Monitore: 1
    Keine Grafikkartenanzahl entdeckt
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktop-Auflösung: 1920 x 1080
    Prim. Anzeigegröße: 106,0 cm x 62,6 cm (123,1 cm diag.)
    Primärer Bus: PCI Express 16x
    Primärer VRAM: 2048 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: SigmaTel STAC9708,11

Speicher:
    RAM: 7977 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 450547 MB
    Größter freier Festplattenspeicherblock: 172999 MB

**Comment by kisak-valve** [comment]
Hello @WindohsCrasher, are you still experiencing this issue on an up to date system?

**Comment by WindohsCrasher** [comment]
Hi @kisak-valve, this seems to work perfectly nowadays. I'm running Linux Mint 18.2 KDE now and just tested it. Closing the ticket ;)
