### ISSUE TITLE
steamcmd assertion failed

### ISSUE THREAD

**Issue by parasyte** [ValveSoftware/steam-for-linux#3034]
Trying to download starbound with steamcmd, download timed out. After restarting the download, I was greeted with the following message:

```
/home/buildbot/buildslave_steam/steam_rel_client_linux/build/src/public/tier1/thash.h (267) : Assertion Failed: Performance warning: too many items, not enough buckets
not enough buckets in thash class 6CTHashIP14CTCPConnectionjE (500 records, 100 buckets)
```

**Comment by kisak-valve** [comment]
Hello @parasyte, @hitmany, are either of you still experiencing this issue on an up to date system?

**Comment by hitmany** [comment]
@kisak-valve no, its working well

**Comment by kisak-valve** [comment]
Thanks for retesting @hitmany. Closing.
