### ISSUE TITLE
Counter Strike CZ and 1.6 screen problems

### ISSUE THREAD

**Issue by gabrield** [ValveSoftware/steam-for-linux#3038]
Hello
I got Counter Strike CZ and 1.6 installed on my macbook running linux. The problem is that the window gets cropped;
I got the same games running on mac os/x and there they work fine. I have tried to change the resolution, etc, etc, but nothing works. Maybe it's a problem with my NVIDIA driver... My card is a Geforce 9400M and the driver version is 304.88. I'm running Xubuntu 13.04 x86_64 with ia32-libs.

I took a photo to show you what is going on...

![unnamed](https://f.cloud.github.com/assets/213093/1744791/b78bbb8a-6423-11e3-84f7-078eb7b366a6.jpg)

PS: In windowed mode, the game seems to run nice, the images are in the right size, but it's still not the fullscreen mode :(

**Comment by kisak-valve** [comment]
Hello @gabrield, @healthycs16, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
