### ISSUE TITLE
Can't write using overlay

### ISSUE THREAD

**Issue by Patrick-Edouard** [ValveSoftware/steam-for-linux#3041]
Hi,

I am using Steam with Fedora 18 (gnome 3 version).
While playing DOTA 2 I am unable to write any text using the Steam overlay (chat or typing an url in the steam web browser).

**Comment by MartinPL** [comment]
Still happens when i use DotA 2 with Vulkan, on OpenGL i can write but without Polish characters :(

> Desktop environment: Gnome: 3.22.2
> Operating system: Antergos (Linux 4.8.13-1-ARCH)
> GL_VENDOR	NVIDIA Corporation
> GL_RENDERER	GeForce GTX 1070/PCIe/SSE2
> GL_VERSION	4.5.0 NVIDIA 375.26

**Comment by MartinPL** [comment]
Fixed
http://store.steampowered.com/news/26953/
> Linux
> - Fixed keyboard input and cursor switching in overlay for Vulkan applications

**Comment by kisak-valve** [comment]
Is anyone on Fedora still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Patrick-Edouard** [comment]
@kisak-valve Working properly on Fedora 26 (dota 2 vulkan).

I however have wierd behavior with my  numpad where it randomly 
- paste my clipboard data
- erase what was written in the chat
- write at the start of the chat instead of the current position

Nothing really blocking tho.

**Comment by kisak-valve** [comment]
Sounds like the issue being tracked at #4592.
