### ISSUE TITLE
[STEAM_CLIENT_BETA][LINUX] Updating games are stuck.

### ISSUE THREAD

**Issue by salamanderrake** [ValveSoftware/steam-for-linux#3042]
Updating games are stuck at "Requires Update" and does not update, deleting of ClientRegistry.blob file and a steam restart is needed to update the games. I have updates enabled for all my games by default.and this is even when I am not in a game so its not that its refusing to update while I'm in game.

**Comment by kisak-valve** [comment]
Hello @salamanderrake, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
