### ISSUE TITLE
Steam Overlay segfaults preventing more than one game launch per system boot after playing World of Goo (Retail)

### ISSUE THREAD

**Issue by dilworks** [ValveSoftware/steam-for-linux#3045]
After the December 13th beta update, unfortunately I've been experiencing a odd issue I've never had since I'm using Steam on my Debian Jessie/amd64 system.

Everything seems to be working as usual - run client, play a game... and when you try to run the next game, game simply dies. Taking a look at my dmesg, I get a bunch of segfaults like this one:

```
[ 2797.611148] sh[4339]: segfault at 7fefb0871748 ip 00007fef40d5d5eb sp 00007fff41c99320 error 4 in gameoverlayrenderer.so[7fef40d4d000+2e000]
[ 2831.746605] sh[4537]: segfault at 7fc1d0fcb748 ip 00007fc1614b75eb sp 00007ffff0027a30 error 4 in gameoverlayrenderer.so[7fc1614a7000+2e000]
[ 2852.080740] sh[4539]: segfault at 7f68b9c5b748 ip 00007f684a1465eb sp 00007fff24afe300 error 4 in gameoverlayrenderer.so[7f684a136000+2e000]
[ 2861.867673] sh[4542]: segfault at 7fd6007db748 ip 00007fd590cc75eb sp 00007fffc7431600 error 4 in gameoverlayrenderer.so[7fd590cb7000+2e000]
[ 2929.733887] sh[4791]: segfault at 7f8c77a09748 ip 00007f8c07ef55eb sp 00007fff70d7b1e0 error 4 in gameoverlayrenderer.so[7f8c07ee5000+2e000]
[ 2932.672393] sh[4793]: segfault at 7f08b0640748 ip 00007f0840b2c5eb sp 00007ffff9018d20 error 4 in gameoverlayrenderer.so[7f0840b1c000+2e000]
[ 2936.110369] sh[4795]: segfault at 7f4bb40e2748 ip 00007f4b445ce5eb sp 00007fff4d080160 error 4 in gameoverlayrenderer.so[7f4b445be000+2e000]
[ 2947.645471] sh[4797]: segfault at 7f9a45ead748 ip 00007f99d63995eb sp 00007fff7d7e1640 error 4 in gameoverlayrenderer.so[7f99d6389000+2e000]
[ 2994.289165] sh[4811]: segfault at 7fc5726e0748 ip 00007fc502bcc5eb sp 00007fffc52cc6b0 error 4 in gameoverlayrenderer.so[7fc502bbc000+2e000]
```

Looking at the offsets, it looks like the segfault is caused by the 64-bit overlay lib, even on 32-bit games (i.e. pretty much anything on my library except for Euro Truck Simulator 2). Deleting the 64-bit gameoverlayrenderer.so has no effect, games just die with another kind of segfault - for example in Python/Ren'Py titles, I get a Python error message, then game dies). It even happens with non-Steam games that I've integrated into my client!

Unfortunately, the workarounds for me are:
1) Disable Steam overlay (not exactly what I want, but at least it lets me run my games)
2) Reboot my system... which not only is annoying, it only allows me to run a single game before encountering with this issue again

EDIT: OK, after some testing, I've discovered the trigger of all of this mess: World of Goo.

If I run the retail edition, it works fine. Then any game launched after it will crash and burn, even if the Steam client is restarted. I've even tried exiting the beta branch and using the main stable client, but surprisingly the same still happened whenever I launch World of Goo!

Looks like this game is doing something nasty that causes either Steam or Debian libs to become icky...

**Comment by dr4Ke** [comment]
What is the state on this?

**Comment by kisak-valve** [comment]
Closing as fixed.
