### ISSUE TITLE
Cloned framebuffer? under big-picture mode [debian 7]

### ISSUE THREAD

**Issue by Illasera** [ValveSoftware/steam-for-linux#3050]
Alright so this one is a bit odd for me to explain.

Here is what i have done.
1.)Launched big picture mode under my debian 7 desktop.
2.)Used the web tab, and clicked youtube.
3.)Played a random video
4.)Pressed the fullscreen button.
5.)Went out from big picture mode straight to the desktop.

Afterward, Everytime i have clicked to switch to a steam window (Any steam window like a chat window) on my KDE taskbar, i got a "Non interactive snapshot" of my current desktop. (Snapshot of the screen with no input ability).

I have tried to restart steam but the exit button didn't work, So i sent a kill signal to it, it killed the UI interface but the process became a ZOMBIE process, Obviously i couldn't re-launch steam, Error : An instance of steam already exists, I shall try to reproduce it once i will restart my system and relaunch.

Logs : No logs.

Software info :

Operating System and kernel: Linux SMP Debian 3.10.11-1~bpo70+1 i686
X.Org X Server version : 1.12.4
Steam : Not using Beta version, Using the version up to date for December 18th 2013.

GPU info :

GPU - intel GMA 450
intel: Driver for Intel Integrated Graphics Chipsets: i810,
VESA: driver for VESA chipsets: vesa
intel(0): Integrated Graphics Chipset: Intel(R) G41
intel(0): Chipset: "G41"

_EDIT_ : Could not be re-produced , tried 5 times, It seems like a one time thing.

**Comment by kisak-valve** [comment]
Closing per the last line.
