### ISSUE TITLE
 Steam won't let me change popup notifications location to TopRight 

### ISSUE THREAD

**Issue by lonerunner** [ValveSoftware/steam-for-linux#3054]
I have read on forums, one of valve guys explained how to move popup notifications to different position.

But it won't let me do that on my pc.

The file that need to be changed is .local/share/Steam/resource/steam.styles

In one of the lines it says

Notifications.PanelPosition "BottomRight" // Can be "BottomRight", "BottomLeft", "TopRight","TopLeft"

And i can change that to move popups to other position. I wanted to move it to TopRight.

But every time i change that to TopRight and restart steam. Steam updates it self and overwrite file with default.

Im on Ubuntu 12.04 with Gnome classic

**Comment by Tcll** [comment]
seconded
been nearly 4 years and still no UI option to select the position of notifications like many other apps do

shame on the devs

**Comment by OvermindDL1** [comment]
Rather I wish it just used the system notification interfaces, getting steam notifications via the KDE system would be so much nicer as they'd be properly themed with the system, I could filter things, change timeout lengths based on contents, it could have richer data (responding to a message from inside the notification for example), etc... etc...
