### ISSUE TITLE
Metro Last Light - level with airplane is broken

### ISSUE THREAD

**Issue by andrew-aladev** [ValveSoftware/steam-for-linux#3055]
I've started playing the game and all worked good. Than I've stuck at the level with airplane. Game is segfaulting randomly and I cant pass this location.

I've tested it with glibc 2.15-r3, 2.16, 2.17
nvidia-drivers 331.20, 319.76
kernel 3.12, 3.11, 3.10
steam runtime on/off
default to application, force enabled and force disabled nvidia features.

I think, that this level was just not tested with linux.

See video http://www.youtube.com/watch?v=WI7kqrPotLE

kernel: [ 9820.243500] traps: MetroLL[14471] general protection ip:8fa3802 sp:c92fec8c error:0
kernel: [ 9820.243500] MetroLL[14473]: segfault at 8fa36e0 ip 0000000008fa3802 sp 00000000c82fcc8c error 7 in MetroLL[8048000+1336000]
kernel: [ 9820.243512]  in MetroLL[8048000+1336000]

**Comment by kisak-valve** [comment]
Hello @andrew-aladev, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
