### ISSUE TITLE
[Feature Request] Redesign check local files dialogue for games

### ISSUE THREAD

**Issue by tarvitz** [ValveSoftware/steam-for-linux#3065]
While files is checking for vaild/invalid cache state there's no ability to use steam completely every functional blocks until this process is done even some social features such like as steam chat, community and store.
For example if I want to say something urgent to my friend I forced to use another IM client (jabber, icq, skype, whatever) just because local cache dialogue blocks everything instead itself.

For big games with 10+ gb of local storage this process could take 5+ minutes.

**Comment by kisak-valve** [comment]
Closing as validating local game files has been a non-blocking operation for quite some time.
