### ISSUE TITLE
Allow selecting a default library folder

### ISSUE THREAD

**Issue by strugee** [ValveSoftware/steam-for-linux#3066]
I prefer to keep my Steam games in `/usr/steam`. However, whenever I download a game, the default selection is `~/.local/share/Steam`.
It'd be nice if I could override the default with a different directory. I checked in Settings > Downloads > Manage Library Folders, but saw nothing.

**Comment by kisak-valve** [comment]
Hello @strugee, looks like this can be done with the current steam client by right clicking on the library folder in the settings and selecting Make Default Folder.
