### ISSUE TITLE
Steam above lockscreen [Cinnamon]

### ISSUE THREAD

**Issue by cmllr** [ValveSoftware/steam-for-linux#3069]
If Steam is maximized and I lock my desktop, Steam is located above my lockscreen.

Unlocking the computer is possible, but the only thins I can see is Steam instead of my lockscreen.

I'm using Cinnamon 2.0.14 on Manjaro 0.8.8 x64_86.

**Comment by kisak-valve** [comment]
Hello @cmllr, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
