### ISSUE TITLE
Steam Load Subscriber agreement with now buttons

### ISSUE THREAD

**Issue by MikeyCarter** [ValveSoftware/steam-for-linux#3070]
I get as far as the Steam Subscriber Agreement.  It shows the text for the agreement but no buttons or anything.  So I can't go any further.

Guess I should say I'm running Fedora 20 64bit

**Comment by kisak-valve** [comment]
Hello @MikeyCarter, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
