### ISSUE TITLE
Gnome-shell, Linux: Can't type in any element of the overlay UI

### ISSUE THREAD

**Issue by Saroufim** [ValveSoftware/steam-for-linux#3072]
When running a steam game under gnome-shell, it's possible to activate the overlay mode, move windows within the overlay, and click on objects and interact with them using a mouse. However, it's not possible to type anything into the browser or the chat windows. The issue doesn't happen on KDE. I've tested this on Manjaro 0.8.8 (x64, GNOME 3.10) and openSUSE 13.1 (x64, GNOME 3.10).

**Comment by HarlemSquirrel** [comment]
Chootin, that worked for me! Sorry about the late update.

**Comment by kisak-valve** [comment]
Hello, is anyone experiencing this issue on an up to date system?

**Comment by HarlemSquirrel** [comment]
@kisak-valve I just tested this on my update-to-date Arch Linux install with GNOME 3.26 using Dota 2 and CS:GO and it seems to be working to type in chat and the web browser in the overlay.

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.
