### ISSUE TITLE
Steam crashes when activating Big Picture.

### ISSUE THREAD

**Issue by iMp-Rex** [ValveSoftware/steam-for-linux#3079]
<pre>vinyl@vinyl:~$ steam -bigpicture
Running Steam on ubuntu 12.04 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 5228 with name 0eBlobRegistryMutex_AF432493ED192E74929CBFC65DFA49ED
removing stale semaphore last operated on by process 5228 with name 0eBlobRegistrySignal_AF432493ED192E74929CBFC65DFA49ED
removing stale semaphore last operated on by process 5228 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 5228 with name 0eSteamEngineLock
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
[0103/000400:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
Installing breakpad exception handler for appid(steam)/version(1386799584_client)
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
steam: ../../src/xcb_io.c:160: append_pending_request: La declaración `!xcb_xlib_unknown_seq_number' no se cumple.
[2014-01-03 00:03:58] Startup - updater built Dec 11 2013 10:59:29
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2014-01-03 00:03:59] Checking for update on startup
[2014-01-03 00:03:59] Checking for available updates...
[2014-01-03 00:04:00] Download skipped: /client/steam_client_ubuntu12 version 1386799584, installed version 1386799584
[2014-01-03 00:04:00] Nothing to do
[2014-01-03 00:04:00] Verifying installation...
[2014-01-03 00:04:00] Performing checksum verification of executable files
[2014-01-03 00:04:00] Verification complete
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140103000358_1.dmp
/home/vinyl/.local/share/Steam/steam.sh: línea 755:  5784 Abortado                (`core' generado) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = no
error: HTTP response code said error
</pre>

It's odd, it was working fine a few hours ago. i tried downgrading the AMD driver (fglrx-experimental-13 to 8, 9 & 12. none has worked so far to fix the issue. I suppose steam client had a recent update, i do not recall though.

I'm not using steam beta client, i've tried accessing Big Picture by the steam large mode menu, the button and launching the application with the option on. all of them generate a segmentation fault. After a few tries it deleted my cache and had issues to read the steam library.

here are my specs:

<pre>
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x12
    CPU Model:  0x1
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2500 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 12.04.3 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-57-generic-pae
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Mutter
    Steam Runtime Version:  steam-runtime-release_2013-10-23
    
Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6410D 

    Driver Version:  4.2.11978 Compatibility Profile Context
    OpenGL Version: 4.2
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x9645
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 62,99" x 35,43"  (72,24" diag)
                                            160,0cm x 90,0cm  (183,5cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: ATI R6xx HDMI
    
Memory:
    RAM:  1485 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  es_ES.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  50394 Mb
    Largest Free Hard Disk Block:  19369 Mb
    
Installed software:
    
Recent Failure Reports:
    Fri Jan  3 05:49:44 2014 GMT: file ''/tmp/dumps/crash_20140102234827_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jan  3 05:56:48 2014 GMT: file ''/tmp/dumps/crash_20140102235645_1.dmp'', upload no: ''HTTP response code said error''
    Fri Jan  3 06:04:05 2014 GMT: file ''/tmp/dumps/crash_20140103000358_1.dmp'', upload no: ''HTTP response code said error''
    
</pre>

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
