### ISSUE TITLE
[Ubuntu LTS] No steam icon in leftmenu

### ISSUE THREAD

**Issue by Tehmal** [ValveSoftware/steam-for-linux#3080]
He,idk but i cant see left menu at 12.04 LTS.

http://ubuntuone.com/7NqczV5FZFwj0GT9keZwnD

**Comment by kisak-valve** [comment]
Hello @Tehmal, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
