### ISSUE TITLE
No List in Small Mode

### ISSUE THREAD

**Issue by caisar** [ValveSoftware/steam-for-linux#3081]
After last update, I can't use small mode because there's no game shown on my list event I had clear the search bar

![screenshot from 2014-01-05 06 04 41](https://f.cloud.github.com/assets/5735742/1845617/58e0375e-7595-11e3-8113-7b832fb01ed1.png)

**Comment by kisak-valve** [comment]
Hello @caisar, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
