### ISSUE TITLE
Steam overlay has broken

### ISSUE THREAD

**Issue by maximvl** [ValveSoftware/steam-for-linux#3093]
Some latest changes have broken overlay, I tried tf2 and dota2. Overlay just does not appear, neither by shift+tab nor by links from games.

My steam info: https://gist.github.com/maximvl/8382582

**Comment by stephanfriedrich** [comment]
Hy this Problem still exists, with civilisation 5

**Comment by jacobblock** [comment]
FYI, the archlinux steam page had a fix that worked for me (https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues):

```
find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete
```

**Comment by chrisjamesberg** [comment]
This still doesn't work for me. Civ 5 crashes after starting a game from main menu. Running Ubuntu trusty on new Chromebook Pixel.

**Comment by Fale** [comment]
I had the same problem with Counter strike on Fedora. Disabling SELinux, it worked

**Comment by sylware** [comment]
On Thu, Jun 18, 2015 at 03:20:20PM -0700, Fabio Alessandro Locati wrote:
> I had the same problem with Counter strike on Fedora. Disabling SELinux, it worked

Don't even have SElinux compiled in... something else, maybe the keyboard.

**Comment by alsternerd** [comment]
Here it is again, this time while trying to start Insurgency:

 Game update: AppID 222880 "Insurgency", ProcID 5601, IP 0.0.0.0:0
 ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
 ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 5604 != 5603, skipping destruction (fork without exec?)
 ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
 ERROR: ld.so: object '/home/luca/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
 libGL error: unable to load driver: r600_dri.so
 libGL error: driver pointer missing
 libGL error: failed to load driver: r600
 libGL error: unable to load driver: swrast_dri.so
 libGL error: failed to load driver: swrast
 X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  109
  Current serial number in output stream:  110
 Game removed: AppID 222880 "Insurgency", ProcID 5601

**Comment by khaoz** [comment]
Having this same issue right now.

I'm using Debian Stable with some backports pacakges (mainly nvidia-driver, xserver-xorg-video-intel, bumblebee-nvidia and primus).

But it happens only when trying to run dota 2 with primusrun or optirun (-b primus)
[error.txt](https://github.com/ValveSoftware/steam-for-linux/files/139910/error.txt)

**Comment by sieira** [comment]
Same issue with ubuntu 16.04 trying to launch home gone home (fglx)

**Comment by doug65536** [comment]
Removing ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1 did not work. Can't buy MvM tickets in TF2. Why do I have to use that crappy overlay to buy? Idiotic design.

**Comment by sylware** [comment]
On Fri, Sep 16, 2016 at 02:29:17PM -0700, Doug Gale wrote:
> Removing
> ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
> did not work. Can't buy MvM tickets in TF2. Why do I have to use that crappy
> overlay to buy? Idiotic design.

It's related to the c++ ABI nightmare and some gcc *BIP*. valve SDK2 should
include static libstdc++ and static libgcc.
(c++ is already idiotic in itself...)

-- 
Sylvain

**Comment by Spitfire1900** [comment]
I am also getting this error, the script below used to fix this before upgrading to Ubuntu 16.10.

uname -a:
`Linux mainstay 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Script:
`LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libstdc++.so.6' DISPLAY=:0 steam`

Output:
```
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/kyle/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by Tele42** [comment]
@Spitfire1900, This line
```ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.```
is telling you that preloading that library failed because it is 64 bit, while steam is 32 bit, so I was ignored. You could try preloading both the 32 bit and 64 bit variant.

**Comment by Spitfire1900** [comment]
@Tele42 , I have tried with 32-bit lib as well.

```
kyle@mainstay:/etc/pam.d$ LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6' DISPLAY=:0 steam
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
...
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Running Steam on ubuntu 16.10 64-bit
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
STEAM_RUNTIME is enabled automatically
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/bin/bash: /home/kyle/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1476379980)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

```
