### ISSUE TITLE
can't run steam on ubuntu13.10

### ISSUE THREAD

**Issue by timeswind** [ValveSoftware/steam-for-linux#3094]
Running Steam on ubuntu 13.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
unlinked 0 orphaned pipes
removing stale semaphore last operated on by process 3887 with name 0eBlobRegistryMutex_9ECE257EFFD5ACD692241A9A20CBEDE6
removing stale semaphore last operated on by process 3887 with name 0eBlobRegistrySignal_9ECE257EFFD5ACD692241A9A20CBEDE6
removing stale semaphore last operated on by process 3887 with name 0emSteamEngineInstance
removing stale semaphore last operated on by process 3887 with name 0eSteamEngineLock
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0113/142534:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Installing breakpad exception handler for appid(steam)/version(1389129507_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140113142533_1.dmp
/home/chucky/.local/share/Steam/steam.sh: line 755:  4360 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = no
error: HTTP response code said error

**Comment by kisak-valve** [comment]
Hello @timeswind, if you're still experiencing this issue on an up to date system, we'll need to do a fresh investigation. Closing.
