### ISSUE TITLE
Big picture mode integrated browser zoom

### ISSUE THREAD

**Issue by Tele42** [ValveSoftware/steam-for-linux#3097]
On my unofficial SteamOS test box, I went into the release news in the system settings section and since I was sitting a fair distance away, I used Ctrl + "+" to zoom in, during it's smooth transition, it jerked off to the side and recentered where it was supposed to be. (Jan. 13th client release) Issue is not present in big picture mode on my desktop (January 7th client release).

I reproduced this on the January 13th linux client in big picture mode, so closing https://github.com/ValveSoftware/SteamOS/issues/118 in favor of reporting the issue here.

**Comment by eiglow** [comment]
I don't think this issue exists anymore?

**Comment by kisak-valve** [comment]
Hello, retesting big picture mode's web component, it looks like the behavior has changed in a way that there is no longer any transition effect as described in the opening post, making this issue outdated. Thanks @eiglow.
