### ISSUE TITLE
First/Last game counters doesn't show in Profile/Games

### ISSUE THREAD

**Issue by chupasaurus** [ValveSoftware/steam-for-linux#3098]
NaN is showing instead of first/last counters in user's Games section of profile.
There is no console output related to this problem.
A problem is exists on any language settings
![steam-bug](https://f.cloud.github.com/assets/2997276/1918224/f3778f5e-7db7-11e3-9de2-224545ca9e94.png)
![steam-bug1](https://f.cloud.github.com/assets/2997276/1918225/f377dacc-7db7-11e3-8be1-347644edf576.png)

**Comment by kisak-valve** [comment]
Closing as the games page of the profile was redesigned and no longer includes the affected line.
