### ISSUE TITLE
gameoverlayrenderer.so cannot be preloaded

### ISSUE THREAD

**Issue by rebl** [ValveSoftware/steam-for-linux#31]
Every game I tried can't use the steam overlay. The full message is:

`ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.`

I'm running Steam in Debian wheezy amd64 with the nvidia driver 310.14-1.

**Comment by alsternerd** [comment]
I wouldn't close this, as it still exists on 64 Bit Ubuntu and Debian with X11.
There's a lot mor errors in this repository that have not been fixed since.

**Comment by gdrewb-valve** [comment]
The preload error messages are expected and normal.  They are produced by the system, not Steam, so Steam doesn't have direct control over what they say or how they appear, thus there doesn't appear to be a reason to keep this open.

If the overlay doesn't work that's something else and a new issue (or one of the existing issues) should cover it.  The preload messages themselves are not a cause of overlay problems.

**Comment by alsternerd** [comment]
It's the same message and only log I get while trying to start Incurgency, since it's based on Source too it may be related.
Since the game trys to start and just stops while Steam says "running" for nearly a second.
Nothing else happens.

**Comment by Keylessboi** [comment]
What was the fix for this issue? It's closed but it seems there was never a clear fix for it

**Comment by carrotflowerr** [comment]
@Keylessboi Did you ever get it working? I'm having the same problem.

**Comment by RolandMarchand** [comment]
I am still having this exact same issue. Disabling the overlay in TF2's settings does not fix the issue.

**Comment by isinaltinkaya** [comment]
This worked for me: remove the 32bit part from LD_PRELOAD and only leave 64bit part
```
export LD_PRELOAD=/home/USER/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
```

**Comment by Keylessboi** [comment]
> @Keylessboi Did you ever get it working? I'm having the same problem.

No, sadly...
