### ISSUE TITLE
Adding a non-Steam game that requires a command (e.g. java -jar "~/Minecraft.jar") does not work

### ISSUE THREAD

**Issue by Zachs-Kappler** [ValveSoftware/steam-for-linux#3101]
I've been trying to figure out what is going on with adding certain launchers (.desktop files) to games or programs to Steam. From my experimentation and due to how sparse the options are regarding non-Steam games, I have found that the only launchers that work are those that are already installed by your package manager and do not need extra commands added to them to make them work.

I wanted to add Minecraft and the Feed The Beast Launcher to Steam to make them easier to launch; but given the method of executing them requires using a java command and not a binary executable, I cannot.

This could also affect programs that are built with Python, Shell, and other interpreted languages.

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/steam-for-linux/issues/3855#issuecomment-322624400.
