### ISSUE TITLE
[ubuntu 13.10][team fortress 2]game text show NOTHING with NON-English interface of steam linux

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3103]
[ubuntu 13.10][team fortress 2]game text show NOTHING with NON-English interface of steam linux client.

how to reproduce the issue.

play team fortress 2, before playing it, switch the steam client for linux language interface to NON-English language, e.g. simplified chinese.

then under non-English interface of steam client linux, to play team fortress 2, no matter team fortress 2 's language pack is english or not, into the game, you 'd see nothing with all the in game buttons,

no characters, no text, only blank buttons with stupid icons!
## 

hope this would be fixed soon.

**Comment by shenxs** [comment]
还是没有改进,依然只有按钮

**Comment by not83** [comment]
English?

**Comment by shenxs** [comment]
Ｉ use Steam on Ubuntu 14.04 LTS . And I download  team fortress 2,When the language setting of Steam is English ,the game works well. Because I am a chinese ,when I use simplified chinese in Steam  ,then I run the game ,only to found that the interface has no characters, no text, only blank buttons

**Comment by not83** [comment]
Is this within the game? This place is for errors found in steam. Not for
steam games. Maybe it's best you post this to the team fortress 2 devs

**Comment by shenxs** [comment]
For the steam client , it also has some bug ,I can't input in chinese ,by the way i use Fctix

**Comment by shenxs** [comment]
Sorry

**Comment by Uramekus** [comment]
so, there is some duplicates of that issue, but nowadays setting my steam to chinese just fallbacks to english, even after a reboot
![2018-08-23-12 16 14-screenshot](https://user-images.githubusercontent.com/4643873/44534545-7454fa00-a6ce-11e8-97f8-986c035dd953.png)

https://github.com/ValveSoftware/steam-for-linux/issues/23
https://github.com/ValveSoftware/Source-1-Games/issues/1690
