### ISSUE TITLE
Unstable FPS in CS:S

### ISSUE THREAD

**Issue by laasonen** [ValveSoftware/steam-for-linux#3110]
I'm running Arch64 on my t430s laptop with i5 and hd4000. I installed Steam and CS:S on December and it worked great with constant 80FPS, but about a week ago my FPS started to drop sometimes to 30 for couple of seconds without any logical reason. After that the FPS drops have become more and more common and now my FPS is most of the time 30 and only sometimes 80, which renders the game unusable. I tried to disable SpeedStep from BIOS without any effect.

Steam log: http://pastebin.com/4qJzC0CD

Packages:
xorg-server 1.15.0-5
xf86-video-intel 2.99.907-2
intel-dri 10.0.2-1
lib32-intel-dri 10.0.2-1
awesome 3.5.2-1
linux 3.12.7-2
steam 1.0.0.45-1

**Comment by kisak-valve** [comment]
Hello @laasonen, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
