### ISSUE TITLE
Runtme should include libgcrypt-1.5.x

### ISSUE THREAD

**Issue by lordheavy** [ValveSoftware/steam-for-linux#3113]
Games like Hal Life 1 seems to depend on libgcrypt.so.11:

[lordh@archMain Half-Life]$ ./hl.sh
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197992653503 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197992653503
GL_SIZES:  r:8 g:8 b:8 a:0 depth:24

ARB Multitexture extensions found.

8 texture units.  Detail texture supported.

Error:libgcrypt.so.11: cannot open shared object file: No such file or directory
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140121201150_1.dmp
./hl.sh : ligne 38 : 27154 Erreur de segmentation  (core dumped)${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@

**Comment by kisak-valve** [comment]
Closing as libgcrypt.so.11 is in the steam runtime.
