### ISSUE TITLE
TF2 Mouse Clicks Sometimes Don't Register

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#3122]
Happens on all of my machines. Sometimes mouse clicks do not register, other times it will repeatedly click by itself until I click to stop it. Happens on all of my machines which are using Ubuntu 13.10 and Ubuntu 14.04 with the latest open source drivers. Raw input is enabled in TF2.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2800 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Zorin OS 8 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-031300-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BARTS

```
Driver Version:  3.0 Mesa 10.1.0-devel (git-f7c118f saucy-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6739
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 21.38" x 12.01"  (24.49" diag)
                                        54.3cm x 30.5cm  (62.2cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7983 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  821116 Mb
    Largest Free Hard Disk Block:  165235 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @mmstick, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as upstream support for Ubuntu 13.10 has been discontinued. If you are still experiencing this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
