### ISSUE TITLE
[ubuntu 13.10(64bit)][bug]steam client for linux unity desktop top-bar steam applet would not quit if game process killed

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3126]
[ubuntu 13.10(64bit)][bug]steam client for linux unity desktop top-bar steam applet NOT quit if game process killed

platform: ubuntu 13.10 64bit linux
steam client for linux latest ver.

game: left 4 dead 2 for linux.

how to reproduce the issue:

start left 4 dead 2 or other games on steam client for linux. in windowed mode.

then play the game, try your best to freeze the game, here is one method i found.

e.g. start left 4 dead 2 for linux, in the game, go campaign mode, -> play online, try to find some add-on campaign hosted by other players online.

then, if the game campaign add-on is from some famous websites, for instance, l4dmaps.com, or other similar, in the l4d2 for linux game, click the campaign game entry, the details of the map would show the download website of the map files.

click the link, and another detailed window in game would show, and clearly states the website link. click the link, in linux ver. of l4d2, it would not automatically redirect you through firefox or similar web-browser on linux, it just freezes the game. everything hang there!

and, force-quit/kill  the game process in linux, then , the game process killed, and steam client itself still there.
then, normally quit the steam client for linux.

you 'd found an interesting issue that, watch the up-right corner of default ubuntu 13.10,
the top-bar of unity interface of ubuntu, steam applet icon still there, you can click the icon, choose quit steam, but, it would NOT work!

and even, sometimes, you can start the steam client for linux another time normally, and the up-right corner, would show 2 steam applet icons there!

obviously one is the dead one, another one is the correctly active one.

the dead steam icon for unity top-bar, the process is named "cipcserver::thr". it can be terminated in system monitor of ubuntu, or you just find the pid, and use "sudo kill" command to kill it.

linux users could work around it, but really annoying, because linux games on steam are becoming more and more, valve cannot guarantee everything on steam has no bug, so, crash, game freeze, could be seen by many steam linux users.

so, steam for linux, prepared for these issues?

personally, i think steam can be much better. hope the bug could be fixed soon.

thank you.

**Comment by kisak-valve** [comment]
Hello, @alexanderhou, @brunonova, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
