### ISSUE TITLE
Steam will not open after Mesa update from Edgers PPA.

### ISSUE THREAD

**Issue by 3gengames** [ValveSoftware/steam-for-linux#3132]
Steam will not open after I received an update from my Edgers PPA for my R9 270X GPU. The updates gave much better performance, but caused Steam to fail to open. The report for steam is given below. This is happening to me and my friend who has a similar build with the GPU and PPA. We both are running Linux Mint 16, 64-Bit, and 3.13 generic kernels. We both have the FOSS drivers, with Mesa for OpenGL. Using AMD drivers, or the current stable Mesa drivers produces horrible results, with both crashing both of our systems in the same way, and all around buggy with our cards. They also don't play games with any drivers except from the edgers PPA.

Any more testing or information needed, I'd be glad to work with anyone.

Steam crash output to stdout:

aaron@aaron-desktop ~ $ steam
Running Steam on linuxmint 16 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1390852599_client)
steam: ../../../../src/loader/loader.c:114: asserted_dlsym: Assertion `result' failed.
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2014-01-30 13:08:54] Startup - updater built Nov 25 2013 18:07:05
[2014-01-30 13:08:54] Opted in to client beta 'publicbeta' via beta file
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140130130854_1.dmp
/home/aaron/.local/share/Steam/steam.sh: line 755: 10650 Aborted                 $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/aaron/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/aaron/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on linuxmint 16 64-bit
STEAM_RUNTIME has been set by the user to: /home/aaron/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(1390852599_client)
steam: ../../../../src/loader/loader.c:114: asserted_dlsym: Assertion`result' failed.
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2014-01-30 13:08:56] Startup - updater built Nov 25 2013 18:07:05
[2014-01-30 13:08:56] Opted in to client beta 'publicbeta' via beta file
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140130130856_1.dmp
/home/aaron/.local/share/Steam/steam.sh: line 755: 10774 Aborted                 $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-c85a124c-6a2c-48f2-9283-edb9e2140130
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-864c71c4-994d-4f77-9ddc-133f82140130
aaron@aaron-desktop ~ $

**Comment by kisak-valve** [comment]
Closing as a general video driver issues from 2014 is no longer relevant.

**Comment by AaronBottegal** [comment]
Agreed. Plus, I'm sure this was actually fixed long ago.
