### ISSUE TITLE
Portal - Please update your OpenGL driver

### ISSUE THREAD

**Issue by latsfro** [ValveSoftware/steam-for-linux#3133]
I had a look through the logs on here but couldn't find anything relating to my issue, please let me know if this has already been solved.

I have a Sony Vaio FW series running ubuntu 12.04 with an ATI mobility Radeon HD3470.

After trying to launch Portal through steam, it gave me an error message:

'Required OpenGL extension "GL_EXT_texture_sRGB_decode" is not supported. Please update your OpenGL driver'

And the game failed to launch. Checking my fglrx driver it showed it was currently up to date - 2:8.960-0ubuntu1. After some tinkering, I rolled my driver back to 2:0.000-0ubuntu1. Now there is no more message and the game launches and appears to run correctly. However, steam now constantly tells me my graphics driver is out of date and that I should update. I am not going to upgrade the driver back at the moment though as I am playing this game.

I noticed I also get the same error for 'Estranged' and 'No more room in hell' and after rolling back the driver everything is fine for those games too.

If anyone has any insights or recommendations please let me know as I would like to keep my system up-to-date if I can.

**Comment by kisak-valve** [comment]
Source 1 games including Portal requires an OpenGL 2.1 + sRGB extensions in order to render properly. Mesa should provide this functionality for this generation of hardware.

Closing as general video driver quality from 2014 is no longer relevant.
