### ISSUE TITLE
TF2 Resolution issue when out of focus.

### ISSUE THREAD

**Issue by Half-Shot** [ValveSoftware/steam-for-linux#3143]
Basically if i try to load up Team Fortress 2 and let the game lose focus (e.g. Alt Tab) then the game will make itself a 800x600 window and will only go to the correct res if I focus back and wait for it to fully load. If I leave it to fully load first, it stays windowed and the graphics/mouse do not scale to the window (squashed and mouse in wrong place).

This can also (but rarely) happen if I load a server and switch away before returning. This is not a new issue and i've had it for as long as I can remember but I never really thought of reporting it.

Not a critical issue but its a problem for those of us who like to load games in the background while reading reddit :P.

Screenshot: http://i.imgur.com/wSokeze.png

Distro: Arch Linux 64 bit

System Infomation:
https://gist.github.com/Half-Shot/8851819

**Comment by volca02** [comment]
try this:
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0

**Comment by kisak-valve** [comment]
Hello @Half-Shot, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If this issue is still happening. please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
