### ISSUE TITLE
Football Manager 2014

### ISSUE THREAD

**Issue by Umeaboy** [ValveSoftware/steam-for-linux#3159]
Let me start off by telling you that I have a stationary computer that I run the Linux-distribution Mageia 4 on and as a graphics-card I have the 82G33/G31 Express Integrated Graphics Controller which uses the i915-module according to lsmod.

Kernel I use is: 3.12.9-desktop-1.mga4

In harddrake2 (which is the graphical tool to display current hardware) I got this information about my card:

Identification
Manufacturer: ‎Intel Corporation

Description: ‎82G33/G31 Express Integrated Graphics Controller

Mediaclass: ‎VGA compatible controller

Connection
Bus: ‎PCI

PCI domain: ‎0

PCI bus #: ‎0

PCI device #: ‎2

PCI function #: ‎0

PCI revision: ‎0x10

Manufacturer ID: ‎0x8086

Device ID: ‎0x29c2

Manufactuers sub ID: ‎0x1849

Device sub id: ‎0x29c2

Various
Module: ‎Card:Intel 810 and later

Module doesn't seem right when I use harddrake2 thou.

Result of glxinfo | grep "OpenGL.*version" is:
OpenGL version string: 2.1 Mesa 10.0.3
OpenGL shading language version string: 1.20

Problem is that if I install Football Manager 2014 & run it I just get to the screen where you type in your credentials and then the gui of the game turns into another colour which makes it impossible to see what you should click on and type.

This has happened to me more than once since I bought this game on Steam.

Official Steam-version (which I built from source) is 1.0.0.47 and I ticked the Beta-option and still have the same issue.

Anything else you need?

**Comment by kisak-valve** [comment]
Hello @Umeaboy, are you still experiencing this issue on an up to date system or did you hear back from the game devs?

**Comment by Umeaboy** [comment]
I switched from the desktop to a laptop so I can't reproduce it. I'm therefor closing this.

**Comment by sailinggalaxians** [comment]
Now I can't even run it in Mageia 9 with a fresh installation and I also use compatibility mode in the game settings.
It says it's loading, but it fails to run and start the GUI.

[kristoffer@localhost ~]$ glxinfo | grep "OpenGL.*version"
OpenGL core profile version string: 4.5 (Core Profile) Mesa 23.1.5
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 23.1.5
OpenGL shading language version string: 4.50
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

Using 6.4.9-desktop-4.mga9 as kernel from the official Mageia 9 repo.

Version of Steam is 1694466342
Steam's API version is SteamClient020
Version of Steam package installed in Mageia is steam-1.0.0.70-3.mga9.nonfree

[Football Manager 2014 fails to start.log](https://github.com/ValveSoftware/steam-for-linux/files/12622942/Football.Manager.2014.fails.to.start.log)
