### ISSUE TITLE
Double enter problem on linux

### ISSUE THREAD

**Issue by dawwin** [ValveSoftware/steam-for-linux#3161]
I have a problem when I'm navigating Big Picture with keyboard. It looks like it always triggers actions for **enter** two times.
For example when I'm here
![1](https://f.cloud.github.com/assets/6729869/2209988/3cb6e90c-9993-11e3-86ad-aff248cce720.png)
After pressing **enter** navigation goes here
![2](https://f.cloud.github.com/assets/6729869/2210012/b6795edc-9993-11e3-9111-da0b07a0bf6f.png)
instead of
![3](https://f.cloud.github.com/assets/6729869/2210014/bc3fd882-9993-11e3-82f7-7ce47cdd216d.png)

It happens everywhere - not only in the example described above. When I'm using my mouse or gamepad everything is fine.
I'm using Steam Beta, Built: Feb 18 2014, at 10:55:11
My system information:

> Processor Information:
>    Vendor:  GenuineIntel
>    CPU Family:  0x6
>    CPU Model:  0x3a
>    CPU Stepping:  0x9
>    CPU Type:  0x0
>    Speed:  2501 Mhz
>    4 logical processors
>    2 physical processors
>    HyperThreading:  Supported
>    FCMOV:  Supported
>    SSE2:  Supported
>    SSE3:  Supported
>    SSSE3:  Supported
>    SSE4a:  Unsupported
>    SSE41:  Supported
>    SSE42:  Supported
> 
> Network Information:
>    Network Speed:  
> 
> Operating System Version:
>    Ubuntu 13.10 (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.11.0-15-generic
>    X Server Vendor:  The X.Org Foundation
>    X Server Release:  11405000
>    X Window Manager:  Compiz
>    Steam Runtime Version:  steam-runtime-release_2014-02-05
> 
> Video Card:
>    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2>
> 
>    Driver Version:  3.0 Mesa 10.2.0-devel
>    OpenGL Version: 3.0
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x8086
>    DeviceID:  0x166
>    Number of Monitors:  1
>    Number of Logical Video Cards:  1
>    Primary Display Resolution:  1600 x 900
>    Desktop Resolution: 1600 x 900
>    Primary Display Size: 15,04" x 8,46"  (17,24" diag)
>                                            38,2cm x 21,5cm  (43,8cm diag)
>    Primary VRAM Not Detected
> 
> Sound card:
>    Audio device: Intel PantherPoint HDMI
> 
> Memory:
>    RAM:  7852 Mb
> 
> Miscellaneous:
>    UI Language:  English
>    LANG:  en_US.UTF-8
>    Microphone:  Not set
>    Total Hard Disk Space Available:  42579 Mb
>    Largest Free Hard Disk Block:  34189 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @dawwin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by CreamyCookie** [comment]
@kisak-valve I don't think I have seen this again, so it may have been fixed (at least for me) :)
