### ISSUE TITLE
Overlay steam menu bug

### ISSUE THREAD

**Issue by txdv** [ValveSoftware/steam-for-linux#3164]
Steam doesn't close the menu correctly and i have it on all my screens: my screen http://inightmare.org/~bentkus/images/screenshots/2014-02-22-014031_1676x1027_scrot.png

I just right click on a game and sometimes it doesn't close it.

**Comment by kisak-valve** [comment]
Hello @txdv, @mthadley, are either of you still experiencing this issue on an up to date system?

**Comment by mthadley** [comment]
@kisak-valve Sorry, I no longer have that original machine that I used to reproduce the issue. So I really can't say.

**Comment by txdv** [comment]
@kisak-valve I haven't seen this bug in a while now.

If I see this again, I will reopen this issue.
