### ISSUE TITLE
Allow -steamos argument without having to configure a network

### ISSUE THREAD

**Issue by lrusak** [ValveSoftware/steam-for-linux#3165]
Please allow for use of the -steamos or -bigpicture launch argument without the network manager dependency.

I ask this because I want to use the -steamos and -bigpicture argument but I don't want NM.

I get stuck on the configuration screen at configure network because Steam cannot find any networks and doesn't let you continue. Simply allowing it to continue would be fine as well.

**Comment by kisak-valve** [comment]
Hello @lrusak, looks like `steam -bigpicture` no longer gets stuck at a configuration screen if NM is not running.

Closing as fixed.
