### ISSUE TITLE
[feature request][linux][steam client]default steam folder assign higher privilege

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3168]
[feature request][linux][steam client]default steam folder assign higher privilege

this is due to this issue. see here:
https://github.com/ValveSoftware/Dota-2/issues/1205

in that dota2 #1205 issue. clearly , dota 2 for linux cannot download match replay dem file from game servers, that was due to steam for linux, its default folder/file privilege or permissions was assigned as low level... not enough for games,

so, if the default [steam for linux] folder permissions can reach into medium level, e.g. owner's privilege "write and read", owner's group "write and read" , other users "read-only", then the issue would be solved easily!
## 

thanks.

**Comment by kisak-valve** [comment]
Hello @alexanderhou, it looks like this was fixed some time ago. Closing.
