### ISSUE TITLE
No audio with Asus Xonar d2x soudcard

### ISSUE THREAD

**Issue by bakteria1** [ValveSoftware/steam-for-linux#3169]
There's no output options for my soundcard and no sound at all. 
Sound works perfectly under ubuntu 12.04.

Here's a thread on steam community with more details http://steamcommunity.com/groups/steamuniverse/discussions/0/558747287244269995/

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/SteamOS/issues/183.
