### ISSUE TITLE
Screensaver Ignores Gamepad Input and Fullscreen Applications

### ISSUE THREAD

**Issue by IMetZach** [ValveSoftware/steam-for-linux#3170]
So when I play a game with the gamepad, after a while the screen starts to fade and then lock unless I move the mouse around. Obviously the power management doesn't acknowledge the gamepad and proper input to keep the screen awake.

I was using Unity and XFCE in Ubuntu 64bit for a long time. I recently switched to OpenSuse 13.1 64bit with Gnome and it still happens. I know Windows has a way that it will recognize fullscreen applications and not engage the screensaver but Linux doesn't have anything like that in the Kernel yet (AFAIK). 

I was wondering what work around others have used in Linux for this issue?

**Comment by Narann** [comment]
Thanks!

**Comment by krux02** [comment]
As much as I like the fact that there is joystickwake, isn't there a proper solution? Something that is not "install this software hack that fixet it for you, as long as you start it every time you want to play a game and do not forget it?"

**Comment by kisak-valve** [comment]
Per "The screensaver will now be correctly interrupted when using controllers or In-Home Streaming" in the [2018-07-16](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/2642934601329286934) Steam client beta update, please opt into Steam's beta and retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed in the 2018-07-16 Steam client beta update.

**Comment by ranomier** [comment]
Tested with Witcher 3 in Steam play (proton) and it doesn't work. I will provide information if needed.

archlinux, kde, steam installed via multilib repo.

<details>
    <summary>click to expand</summary>
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8350 Eight-Core Processor           
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.19.8-arch1-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12003000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2018-11-28

Video Card:
    Driver:  X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.19.8-arch1-1-ARCH, LLVM 7.0.0)
    Driver Version:  4.4 (Compatibility Profile) Mesa 18.2.6
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 23.35" x 14.61" (27.52" diag)
                                            59.3cm x 37.1cm (69.9cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  15999 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  208192 Mb
    Largest Free Hard Disk Block:  139796 Mb
    VR Headset: None detected

Recent Failure Reports:
</details>

**Comment by kisak-valve** [comment]
Hello @ranomier, please open a new issue report and in it also confirm that you have the issue with a native linux game.
