### ISSUE TITLE
Steam Install Broken in Ubuntu 14.04

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#3171]
After freshly installing Steam in Ubuntu 14.04, attempting to run Steam only results in the following:

ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2014-02-25 10:35:16] Startup - updater built Nov 25 2013 18:07:05
libGL error: Couldn't dlopen libudev.so.1 or libudev.so.0, driver detection may be broken.
steam: ../../../../src/loader/loader.c:129: asserted_dlsym: Assertion `result' failed.
Aborted (core dumped)
/usr/games/steam: 16: /usr/games/steam: /home/mmstick/.steam/steam.sh: not found

**Comment by kisak-valve** [comment]
Hello @mmstick, are you still experiencing this issue on an up to date system?

**Comment by mmstick** [comment]
@kisak-valve I can't speak for Ubuntu anymore, as I only use Solus OS & Arch now.

**Comment by kisak-valve** [comment]
It looks like the [distro-provided package](https://packages.ubuntu.com/xenial-updates/steam) for 16.04 directly depends on libudev1, so this shouldn't be encountered by new Ubuntu users.

Thanks for the feedback, closing.
