### ISSUE TITLE
Self-updater changelog text cut off on right

### ISSUE THREAD

**Issue by dancemasterglenn** [ValveSoftware/steam-for-linux#3172]
I've found that (at least in linux) when I get a popup telling me a new update has been found for the steam client, the changelog text can be cut off on the right. This wouldn't really be a big deal, but the self-updater window is not resizeable, so I'd have to click through to read the update elsewhere to properly look at it.

I'm under the impression I didn't do anything "weird" to change my steam font... is there any chance we can make that window resizeable? Or at least make it a little wider? That would be excellent!

**Comment by kisak-valve** [comment]
Closing as the text is no longer cutoff.
