### ISSUE TITLE
Self-Updater notification window hard to notice

### ISSUE THREAD

**Issue by OlliC** [ValveSoftware/steam-for-linux#3173]
![steam_window_updater](https://f.cloud.github.com/assets/6794707/2270953/771c73bc-9ef4-11e3-8e3f-25ea27a82709.png)

I'm on Debian 7 with standard Gnome 3 (Same as SteamOS). Every time steam updates itself it tries afterwards to show a window with the changelog and a button to restart steam. 
That window is very hard to notice because only a small part of it shows up in the gnome shell window overview. Also it has no title. See picture in attachment.

**Comment by kisak-valve** [comment]
Hello @OlliC, are you still experiencing this issue on an up to date system?

**Comment by OlliC** [comment]
No, i have not seen this issue for a while. Forgot about it also, so i can probably be closed.
