### ISSUE TITLE
multimonitor screen switching problem

### ISSUE THREAD

**Issue by xpander69** [ValveSoftware/steam-for-linux#3176]
hello,

after last update of steam, every time i start steam my monitors will be swapped around

heres my normal layout: https://dl.dropboxusercontent.com/u/28788188/ss_27022014_21.27.40.png

i do have third one also but its mostly turned off.

anyway if i start steam, they switch places and thus messing up all on my desktop as well.
have to manualy put them back into correct order

nvidia drivers 331.49
Arch Linux x86_64 up to date

**Comment by kisak-valve** [comment]
Hello @xpander69, are you still experiencing this issue on an up to date system?

**Comment by xpander69** [comment]
ohh, i did not even remember this bug :) sorry i didn't post before, but i haven't experienced this long long time. so it seems fixed :) either it was fault on my side somewhere or somewhere else.. its all fine now. Can be closed

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
