### ISSUE TITLE
Upgrade TLS support of in-game browser

### ISSUE THREAD

**Issue by panzi** [ValveSoftware/steam-for-linux#3192]
TLS support in the in-game browser is currently sub-par. https://www.howsmyssl.com/ currently criticizes these things:
#### Version

Your client is using TLS 1.0, which is very old, possibly susceptible to the BEAST attack, and doesn't have the best cipher suites available on it. Additions like AES-GCM, and SHA256 to replace MD5-SHA-1 are unavailable to a TLS 1.0 client as well as many more modern cipher suites.
#### TLS Compression

Your TLS client supports compressing the settings that encrypt your connection. This is really not good. It makes your TLS connections susceptible to the CRIME attack and your encrypted data could be leaked!
#### Insecure Cipher Suites

Your client supports cipher suites that are known to be insecure:

SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA: This cipher was meant to die with SSL 3.0 and is of unknown safety.
TLS_DHE_DSS_WITH_RC4_128_SHA: This cipher uses keys smaller than 128 bits in its encryption.

**Comment by kisak-valve** [comment]
Closing as steam switched to libcef quite a while ago.
