### ISSUE TITLE
Half-Life 2 problems with fonts

### ISSUE THREAD

**Issue by NetWormKido** [ValveSoftware/steam-for-linux#3196]
openSUSE 13.1 (Bottle) (x86_64) (3.11.10-7) KDE 4.11.5 ru_RU.UTF-8

I run the game and see it
![hl2](https://f.cloud.github.com/assets/3027212/2366019/2151296e-a6ec-11e3-9741-67c7e643fb59.jpeg)

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/Source-1-Games/issues/129 / https://github.com/ValveSoftware/Source-1-Games/issues/153.
