### ISSUE TITLE
And Yet It Moves fails to start due to underquoting in AndYetItMovesSteam.sh

### ISSUE THREAD

**Issue by jepler** [ValveSoftware/steam-for-linux#3197]
As mentioned in a comment on Issue #1970 after it was closed, the script doesn't work.  The following patch fixes it for me and for another commenter:

```
--- AndYetItMovesSteam.sh.orig  2014-03-08 20:20:00.961627715 -0600
+++ AndYetItMovesSteam.sh       2014-03-08 19:39:21.936986366 -0600
@@ -5,8 +5,8 @@
 ### Enjoy!
 ###  webs

-ayim_dir="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"
-rootdir=$ayim_dir
+ayim_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
+rootdir="$ayim_dir"
 libdir="lib"
 bin=lib/AndYetItMoves

```

**Comment by boombatower** [comment]
Tired of devs that leave something to be desired on Linux? Join us at [steamtricks](https://github.com/steamtricks/steamtricks) in automating fixes to reduce the pain of Steam on linux.

[This fix](https://github.com/steamtricks/steamtricks-data/tree/master/data/18700-And_Yet_It_Moves) is automatically applied by steamtricks.
