### ISSUE TITLE
ubuntu 12.10 fatal error: failed to load steamui.so

### ISSUE THREAD

**Issue by titatoofenaer** [ValveSoftware/steam-for-linux#321]

**Comment by cjwijtmans** [comment]
it just happened after an update.

**Comment by DavidYKay** [comment]
Happening for me, too. Will run through these solutions to see if I can fix.

**Comment by ulidtko** [comment]
So what am I supposed to do if all `steamui.so` libdeps are met, but it still says "failed to load steamui.so" ?

    $ LD_LIBRARY_PATH=. ldd steamui.so | grep 'not found'
    $ pwd
    /home/ulidtko/.local/share/Steam/ubuntu12_32

**Comment by kisak-valve** [comment]
Hello @ulidtko, please open a new issue report with your distro, what video driver is in use (glxinfo may help find that), and we can try to figure out what is going on there.
