### ISSUE TITLE
Fedora 20 - Graphic glitch in Oil Rush

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#3212]
After start game see white screen :(

Demonstration: https://drive.google.com/file/d/0B0nwzlfiB4aQVW9iT1U1WWVwbGs/edit?usp=sharing

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.6-200.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 10.0.4
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31123 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  2816556 Mb
    Largest Free Hard Disk Block:  151086 Mb

Installed software:

Recent Failure Reports:

**Comment by ryao** [comment]
kuuchan on the steam fourms posted a workaround. You put this into ~/.drirc:

```
<driconf>
<!-- Please always enable app-specific workarounds for all drivers and
screens. -->
<device>
<!-- mesa commit b0ff18bd3441ce7f28354686934440a92826eaf8 -->
<application name="Oil Rush 32-bit" executable="OilRush_x86">
<option name="allow_glsl_extension_directive_midshader" value="true" />
<application name="Oil Rush 64-bit" executable="OilRush_x64">
<option name="allow_glsl_extension_directive_midshader" value="true" />
</application>
</device>
</driconf>
```

https://github.com/ValveSoftware/steam-for-linux/issues/3212

It is amazing how simple the workaround is.

**Comment by ryao** [comment]
A patch has been sent to upstream mesa so that future releases implement the workaround automatically:

http://lists.freedesktop.org/archives/mesa-dev/2015-August/091540.html

**Comment by kisak-valve** [comment]
Closing per https://cgit.freedesktop.org/mesa/mesa/commit/?id=ec6af4f54cbfe1a779af7245f1bd65c9e5a00dce.
