### ISSUE TITLE
Steam-Launcher SegFault on Linux Mint 16

### ISSUE THREAD

**Issue by dbass81** [ValveSoftware/steam-for-linux#3218]
I installed Linux Mint 16.  I tried installing fglrx driver from repos, but it said unsupported hardware.  Downloaded and installed AMD Catalyst 14.3 Linux beta driver.  Installed steam_latest.deb from steampowered.com.  Ran Steam in terminal and segfaulted.  Output as follows:

dylan@dylan-PC ~ $ steam
Running Steam on linuxmint 16 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140318154835_1.dmp
/home/dylan/.local/share/Steam/steam.sh: line 755:  4579 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/dylan/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/dylan/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-b784486e-c2a9-47d9-8dcf-83a712140318
Running Steam on linuxmint 16 64-bit
STEAM_RUNTIME has been set by the user to: /home/dylan/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140318154836_1.dmp
/home/dylan/.local/share/Steam/steam.sh: line 755:  4706 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-51b96ba2-6e41-4d53-860d-82d8a2140318
dylan@dylan-PC ~ $

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
