### ISSUE TITLE
Game overlay lib not loaded correctly

### ISSUE THREAD

**Issue by ItachiSan** [ValveSoftware/steam-for-linux#3222]
As in title.
While opening games, I've errors (in terminal) like:

```
ERROR: ld.so: object '/home/ency/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ency/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

The first one is kinda good, the second doesn't.
Ideas?
I'm on ArchLinux with GNOME 3.10, with all latest updates.
No problems in giving debug messages.

**Comment by kisak-valve** [comment]
Hello @ItachiSan, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
