### ISSUE TITLE
Choppy sound in BPM, sound ok in OS/games.

### ISSUE THREAD

**Issue by roytt** [ValveSoftware/steam-for-linux#3227]
*\* Description **

The issue happens in both these situations on the same hardware:
1/ Ubuntu 13.10 with Steam in Big Picture Mode (outside of BPM, everything is fine).
2/ Inside SteamOS

The issue itself :
All sounds inside the Big Picture Mode client are choppy and distorted. When playing game trailers (Flash) from inside the Big Picture Mode the sound is choppy and parts are skipped. If I play the exact same trailers from the "normal" Steam client for Linux, everything is fine.

*\* Sound recordings *\* 

(all recorded from within Ubuntu 13.10):
- Steam for Linux BPM intro (very choppy)
  https://raw.githubusercontent.com/roytt/SteamBugs/master/bpm_intro.ogg
- Dota 2 trailer from store page, from within BPM (very choppy and skipped parts, seems sped up)
  https://raw.githubusercontent.com/roytt/SteamBugs/master/dota2_trailer_bpm.ogg
- Dota 2 trailer from store page, from the normal Steam for Linux client (normal)
  https://raw.githubusercontent.com/roytt/SteamBugs/master/dota2_trailer_steamclient.ogg

All games I have played behave normally and are not affected by this issue (e.g. TF2, Portal 2 beta). These issues occur in no other circumstances whatsoever, only and exclusively inside of Steam BPM.

*\* System Info **

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2660 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-18-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11405000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.49
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xe22
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18.66" x 11.65"  (21.97" diag)
                                        47.4cm x 29.6cm  (55.8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 768 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3945 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  108278 Mb
    Largest Free Hard Disk Block:  44109 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing as the original issue with Big Picture Mode appears to have been resolved (https://github.com/ValveSoftware/steam-for-linux/issues/3227#issuecomment-49170538).
