### ISSUE TITLE
Error in message render

### ISSUE THREAD

**Issue by twisted87** [ValveSoftware/steam-for-linux#3229]
Everything is working correctly, but when I click "play now" in Carmageddon: Reincarnation it tells me.. something.

Linux Mint 16 updated.

https://gist.github.com/twisted87/9842652

![kazam_screenshot_00000](https://cloud.githubusercontent.com/assets/5989824/2554998/1bdbaedc-b6b9-11e3-87e0-5d4c58b78b2b.png)

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2013 is no longer relevant.
