### ISSUE TITLE
[Feature Request] Include option to filter "Early Access" games from Steam's lists

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#3235]
I'm glad that Steam provides a way for users to get to Early Access games if they want, but I've been becoming more and more frustrated by their presence in both the big banners and the lists of games.  I've done various Early Access / Beta games in the past, and have had a handful of good experiences, but I've come to the conclusion that it's just not The Model For Me.  I keep seeing interesting-looking things in the list and then being let down a bit that it's something I simply won't be buying until it's in a "final" state.

So anyway, having a checkbox-or-something somewhere which would prevent Early Access stuff from showing up would be great.  Thanks!

**Comment by Uramekus** [comment]
![2018-08-23-01 35 48-screenshot](https://user-images.githubusercontent.com/4643873/44504916-f1ec1c00-a674-11e8-9c5a-fd06616f265d.png)
fixed https://store.steampowered.com/account/preferences
