### ISSUE TITLE
Multi-Monitor Video Full-Screen Opens on Wrong Monitor

### ISSUE THREAD

**Issue by F1nny** [ValveSoftware/steam-for-linux#3236]
With a multi-monitor setup, when selecting to full-screen a video from the store for example, it opens on the 0,0/left-most monitor which is in most cases not the main monitor nor the monitor where steam resides. I have steam running on my primary which is the 3rd from left, so it gets a bit frustrating. Using NVidia Tegra card using 4 outputs from 1 video card, monitors work independently/each own task bar/etc.
Not using base mosiac or anything like that, just plugged all 4 monitors into the one card and enabled in X settings, it does technically function as ONE screen however each monitors bounds work correctly/etc... (maximizing only maximizes to that monitor, can carry windows/mouse across monitors/etc.)

**Comment by kisak-valve** [comment]
Hello @F1nny, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Since this issue was reported, I'm fairly sure there was a general improvement at some point, then a December regression when the way the full screen video window is spawned changed.

If you're still seeing this issue, it's most likely now the more recent regression being tracked at #5277.
