### ISSUE TITLE
The "View item inventory" button doesn't work

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#3240]
In the "Trade completed" dialog there are two buttons: "Close window", and "View item inventory". The latter used to close the dialog and the main window jumped to the inventory display, but for some months it just closes the dialog.

**Comment by kisak-valve** [comment]
Hello @mtmkls, are you still experiencing this issue on an up to date system?

**Comment by mtmkls** [comment]
Now with the mandatory mobile authenticator it's rather difficult to test this.

**Comment by kisak-valve** [comment]
Closing pending confirmation this is still an active issue.
