### ISSUE TITLE
tf2: only first letter is shown of chemistry set inputs

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#3242]
It looks like this:
S x 3
R x 3
Both in the new item found dialog, and in the inventory.

**Comment by mtmkls** [comment]
The same applies for the paint selection popup (BTW replacing the buttons with the popup was a bad idea IMHO)

**Comment by mtmkls** [comment]
This issue is still there. It also affects the progress bar text of the mission shelf.

**Comment by mtmkls** [comment]
This issue is still there.

**Comment by mtmkls** [comment]
This also affects the contract names in the contract tracker.

**Comment by kisak-valve** [comment]
Hello @mtmkls, let's track this issue in the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2353.
