### ISSUE TITLE
Star Conflict crashes due to missing "radeon_dri.so"

### ISSUE THREAD

**Issue by EoD** [ValveSoftware/steam-for-linux#3244]
When trying to start up Star Conflict, it crashes with a missing "radeon_dri.so" I don't have such a library and I never had:
`Game update: AppID 212070 "Star Conflict", ProcID 5773, IP 0.0.0.0:0
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/Steam/SteamApps/common/star conflict/StarConflict: /usr/lib32/libcrypto.so.1.0.0: no version information available (required by /Steam/SteamApps/common/star conflict/StarConflict)
/Steam/SteamApps/common/star conflict/StarConflict: /usr/lib32/libcurl.so.4: no version information available (required by /Steam/SteamApps/common/star conflict/StarConflict)
Setting breakpad minidump AppID = 212070
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198054163081 [API loaded no]
libGL error: MESA-LOADER: could not create udev device for fd 744
libGL error: dlopen /usr/lib32/dri/radeon_dri.so failed (/usr/lib32/dri/radeon_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: radeon_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeon
Game removed: AppID 212070 "Star Conflict", ProcID 5774 
`

All Source games work just fine. I also tested the following non-Source games: Defcon, Hacker Evolution, X3: Albion Prelude, Solar 2.

This is the output of my hardware info. The last two crash reports are for Star Conflict:

```
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3200 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.9-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Openbox
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD BARTS

    Driver Version:  3.0 Mesa 10.1.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6738
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                            52.1cm x 29.3cm  (59.7cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7895 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  100665 Mb
    Largest Free Hard Disk Block:  3930 Mb

Installed software:

Recent Failure Reports:
    Tue Apr  8 21:43:33 2014 GMT: file ''/tmp/dumps/crash_20140408234329_5.dmp'', upload yes: ''CrashID=bp-0c73aada-fccb-46a5-87a9-45fd82140408''
    Tue Apr  8 21:46:26 2014 GMT: file ''/tmp/dumps/crash_20140408234623_5.dmp'', upload yes: ''CrashID=bp-aec97c03-996b-4d4c-8ac0-0c1732140408''
```

The same issue happens both with STEAM_RUNTIME enabled and disabled.

See also https://forum.star-conflict.com/index.php?showtopic=22962 .

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
