### ISSUE TITLE
[3rd party game][ubuntu 13.10][linux]not supporting linux at all, but labelled linux support, how to solve

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3251]
[3rd party game][ubuntu 13.10][linux]not supporting linux at all, but labelled linux support, how to solve such issue.

the game dwarfs F2P
http://store.steampowered.com/app/213650/

does not support linux, i tested with ubuntu 13.10 64bit.

and i go to their developer website, 
http://forums.tripwireinteractive.com/forumdisplay.php?f=120

i found, since autumn of 2013, Dwarfs F2P, this game already got linux running/starting issue. but the developer of this game, obviously ignored the support for linux ver.
now it's been almost 6 months passed, linux ver. of the game, still cannot run on linux normally.

if the game not supporting linux at all, why steam labels it as linux available?

i waste so much time to download it, and test it. and report the bug to different web sites. waiting for the linux issue fix.

well, if the developer of the games on steam, they ignore linux version support, making the game not supporting linux, then how to solve this, where to complain such issue?

i mean, if the developers of the games on steam, they obviously gave up the support for linux ver. then, where to complain such issue, how  to get help?

could you help me? they stopped the support for linux version, and labeled  the game as linux available, this is CHEATING/FRAUD.
~
could you help me, thanks.

**Comment by kisak-valve** [comment]
Hello @alexanderhou, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
