### ISSUE TITLE
[Debian] missing libc.so.6 warning, missing games

### ISSUE THREAD

**Issue by liskin** [ValveSoftware/steam-for-linux#3252]
When I launched steam today, I got the "You are missing the following 32-bit libraries, and Steam may not run: libc.so.6 warning", and then all games seems uninstalled and the game folder list said just "Searching".

error.log contains this several times

```
sh: symbol lookup error: /lib/i386-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
```

Apparently, /bin/bash needs libncurses.so.5, and:

```
$ objdump -T /lib/i386-linux-gnu/libncurses.so.5 | grep nc_putchar
00000000      DF *UND*  00000000              _nc_putchar
$ objdump -T /lib/i386-linux-gnu/libtinfo.so.5 | grep nc_putchar
0000f180 g    DF .text  0000002c  Base        _nc_putchar
$ objdump -T ~/.steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libtinfo.so.5 | grep nc_putchar
$
```

Changing the ~/.steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libtinfo.so.5 symlink to point to /lib/i386-linux-gnu/libtinfo.so.5 solves this issue here.

Sadly, I'm not sure if it's my system that changed or if it's something in steam that used to work and now doesn't. :-(

**Comment by kisak-valve** [comment]
We will be tracking steam runtime issues cumulatively from now on. Closing in favor of #4768.
