### ISSUE TITLE
Unresponsive/delayed menu with GtkStatusIcon fallback

### ISSUE THREAD

**Issue by elizagamedev** [ValveSoftware/steam-for-linux#3256]
When the main steam window is closed, or when the main window is on the Library tab, the system tray menu is unresponsive in virtually _every_ desktop environment other than Unity.

All other software that uses libappindicator on Linux works properly when in [GtkStatusIcon fallback mode](https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators#Custom_Fallbacks), and Steam itself works just fine with it in every tab but the Library tab. That makes this a Steam bug.

According to other users, the following window managers/desktop environments are affected:
- GNOME
- Mate
- Openbox + tint2
- Fluxbox
- Awesome
- i3
- Cinnamon
- xfce4

I've seen mixed responses about whether KDE is still affected or not.

**Comment by kisak-valve** [comment]
Hello @elizagamedev, are you still experiencing this issue on an up to date system?

**Comment by elizagamedev** [comment]
@kisak-valve I am not, thank you for confirming. It seems to have been fixed for me for a while now (at least a year).

**Comment by kisak-valve** [comment]
Thanks for checking. Closing.
