### ISSUE TITLE
Steam glitches when minimized

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#3262]
Major annoyance. When i minimized the steam window it glitches out and draws on top of other windows but it does this on-off drawing. pulling steam up again fixes the issue. Steam does go below other windows fine except when its minimized.

**Comment by aldrik** [comment]
This issue was [fixed some time ago by Nvidia (in the v340.24 driver update)](https://devtalk.nvidia.com/default/topic/751552/linux/any-opengl-window-shown-on-all-workspaces-occludes-other-applications/post/4243826/#4243826).

**Comment by graphitemaster** [comment]
This issue seems to be back now on 340.65

```
]# glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3.0 NVIDIA 340.65
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL version string: 3.3.0 NVIDIA 340.65
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.65 340.65
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
```

**Comment by graphitemaster** [comment]
Further testing indicates these glitches happen when launching steam cold while a flash player applet is running in a browser like chrome or firefox. Flash player uses overlays so it looks like a driver issue *failing to clear the overlay buffer*. Closing any flash applets before launching steam fixes the issue.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
