### ISSUE TITLE
steam cliend 22 april update stop working on opensuse 13.1 kde

### ISSUE THREAD

**Issue by nevenblazic** [ValveSoftware/steam-for-linux#3268]
Everything was working fine but after update from 22 april of steam client it wont start anymore

Restarting Steam by request...
Running Steam on   64-bit
STEAM_RUNTIME has been set by the user to: /home/neven/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(1398120891_client)
No protocol specified
No protocol specified
Assert( Assertion Failed: Could not open connection to X ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./updateui_xwin.cpp:343

Installing breakpad exception handler for appid(steam)/version(1398120891_client)
Error: Unable to open a connection to X.  Check your DISPLAY environment variable and make sure that you have enabled X.  If you are running remotely, make sure that you have a remote connection which will allow an X connection.

For more information visit https://support.steampowered.com/kb_article.php?ref=4050-WOJB-0608.
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140423222928_3.dmp
[2014-04-23 22:29:28] Startup - updater built Apr 21 2014 15:29:49
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./updateui_xwin.cpp (343) : Assertion Failed: Could not open connection to X
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamexe/./main.cpp (457) : Assertion Failed: failed to initialize update status ui, or create initial window
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-65c6cba0-27de-4c9c-ad2c-386322140423

**Comment by kisak-valve** [comment]
We will be tracking steam runtime issues cumulatively from now on. Closing in favor of #4768.
