### ISSUE TITLE
Steam fails to Launch the game "Star Conflict" 

### ISSUE THREAD

**Issue by ustcltx** [ValveSoftware/steam-for-linux#3269]
Here is the debug log file:

(steam:4466): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  78
  Current serial number in output stream:  76
Segmentation fault (core dumped)
Game removed: AppID 212070 "Star Conflict", ProcID 4668

Thanks

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by EoD** [comment]
@kisak-valve it did already work for me in April 2014 and it is still working for me, not sure what the exact issue here is/was.

**Comment by kisak-valve** [comment]
Thanks, closing as general video driver issues from 2014 are no longer relevant.
