### ISSUE TITLE
Problem with libstdc++.so.6 bundled with steam-runtime 2014-04-15

### ISSUE THREAD

**Issue by jsa1983** [ValveSoftware/steam-for-linux#3273]
Not sure if this belongs here or in https://github.com/ValveSoftware/steam-runtime/issues/13, where I originally posted. Just posting here in case it need to be here as it is a linux specific problem.

After a graphics drivers and llvm update (mesa git 2014.04.26, compiled with llvm 3.5; llvm 3.5 svn 207303) I have experienced the following problem:

libGL error: dlopen /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1)) libGL error: dlopen ${ORIGIN}/dri/radeonsi_dri.so failed (${ORIGIN}/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio) libGL error: dlopen /usr/lib/dri/radeonsi_dri.so failed (/usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio) libGL error: unable to load driver: radeonsi_dri.so libGL error: driver pointer missing libGL error: failed to load driver: radeonsi libGL error: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: versionGLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/swrast_dri.so failed (${ORIGIN}/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
ExecCommandLine: "/home/jose/.local/share/Steam/ubuntu12_32/steam"
System startup time: 8,15 seconds
libGL error: dlopen /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1)) libGL error: dlopen ${ORIGIN}/dri/radeonsi_dri.so failed (${ORIGIN}/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio) libGL error: dlopen /usr/lib/dri/radeonsi_dri.so failed (/usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio) libGL error: unable to load driver: radeonsi_dri.so libGL error: driver pointer missing libGL error: failed to load driver: radeonsi libGL error: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: versionGLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/swrast_dri.so failed (${ORIGIN}/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Running Steam on ubuntu 14.04 64-bit

However the command strings /home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6 | grep GLIB did show version 3.4.18.

Removing the libstdc++.so.6 libstdc++.so.6.0.16 files solved the issue and now steam starts with direct GPU acceleration.

**Comment by soerengrunewald** [comment]
Also using F21 x64 and for me the following command was the solution
```
$ ln -sf /usr/lib/libstdc++.so.6.0.20 ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
```

**Comment by louima** [comment]
Debian maintainers found a workaround by `rm -f`'in the libraries before actually running the steam binary.

    # remove steam-runtime's libstdc++, which is incompatible with newer mesa drivers
    # (https://bugs.freedesktop.org/78242)
    rm -f $ubuntu32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6*
    rm -f $ubuntu32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6*

See http://sources.debian.net/src/steam/1.0.0.49-1/debian/scripts/steam/#L21

**Comment by jorti** [comment]
I can start steam removing the libraries, but some games don't start (like Kerbal Space Program). I have to launch it from command line.

**Comment by es20490446e** [comment]
I confirm that creating a symlink worked for me under Ubuntu, and games run fine:
ln -sf /usr/lib/libstdc++.so.6.0.20 ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6

**Comment by dl00** [comment]
I confirm the symlink also works for me on Arch Linux.

**Comment by piranna** [comment]
What about just removing the runtime? Would it work? Or symlink the directory? Would it crash my system libraries?

**Comment by hvr** [comment]
@piranna whether you symlink `libstdc++.so.6` or just remove it should be the same (it would fall back to the next `libstdc++.so.6` the linker finds in the library search path)

**Comment by piranna** [comment]
I was asking about removing the full runtime so all the libraries it fetch are the system ones...

**Comment by pbhj** [comment]
Yes, I got the "OpenGL GLX context is not using direct rendering, which may cause performance problems.

For more information visit https://support.steampowered.com/kb_article.php?ref=9938-EYZB-7457." error.

Disabling the libstdc++.so.6 as for others (in both the i386 and amd64 branches of the steam-runtime) fixed it for me too.

**Comment by kode-kristoff** [comment]
Does the symlink solution work after a steam update?

I tried to remove steam's libstd-files, but when steam updated itself it restored the files (and my problem).

Another woraround with an explanation is found here: https://wirejungle.wordpress.com/2015/01/09/how-to-fix-broken-steam-linux-client-with-radeon-graphics-driver-workaround/

**Comment by Lucretia** [comment]
On Gentoo 64-bit. I just moved from fglrx to amdgpu and got the following output from steam:

/home/laguest/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
/home/laguest/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
Running Steam on gentoo  64-bit
/home/laguest/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1461972496)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

** Just sits there doing nothing...

Then used this command, from https://wiki.gentoo.org/wiki/Steam/Client_troubleshooting#libGL_fails_to_load:

find ~/.local/share/Steam/ \( -name libgcc_s.so* -o -name libstdc++.so* \) -print -delete

Steam, then loads.

**Comment by es20490446e** [comment]
The fix is to enter this commands into the Terminal application:

BEFORE RUNNING STEAM:
ln -sf /usr/lib/libstdc++.so.6.0.20 ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6

AFTER RUNNING STEAM:
rm $HOME/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
rm $HOME/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by mariojuniorjp** [comment]
Many thanks @soerengrunewald! Works like a charm on Arch. :+1:

**Comment by CaptainKraft** [comment]
This post on the Arch Linux subreddit may be helpful and can prevent this problem from coming back in the future.

https://www.reddit.com/r/archlinux/comments/4l0tir/no_more_steam_broke_on_latest_update_posts_please/

**Comment by Mailaender** [comment]
Compare https://build.opensuse.org/request/show/407547

**Comment by kisak-valve** [comment]
We will be tracking steam runtime issues cumulatively from now on. Closing in favor of #4768.

**Comment by jsroyal** [comment]
jsroyal@Hp:~$ chmod +x genymotion-2.8.1_x64.bin
jsroyal@Hp:~$ ./genymotion-2.8.1_x64.bin
Installing for current user only. To install for all users, restart this installer as root.

Installing to folder [/home/jsroyal/genymotion]. Are you sure [y/n] ? y


- Trying to find VirtualBox toolset .................... OK (Valid version of VirtualBox found: 5.0.32_Ubuntur112930)
- Extracting files ..................................... OK (Extract into: [/home/jsroyal/genymotion])
- Installing launcher icon ............................. OK

Installation done successfully.

You can now use these tools from [/home/jsroyal/genymotion]:
 - genymotion
 - genymotion-shell
 - gmtool

jsroyal@Hp:~$ cd genymotion/
jsroyal@Hp:~/genymotion$ ./genymotion
Logging activities to file: /home/jsroyal/.Genymobile/genymotion.log
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

Is there any solutuion find??

**Comment by sylware** [comment]
solution: steam client and games binaries do link statically libgcc and libstdc++.

Binaries in the world of linux based OSes should depend on a minimal set of ELF
symbols from a minimum set of system libs (x11/wayland/vulkan/alsa/posix|libc).
A lot of abstraction is dealed by libSDL2 which is open source the right way
(Lesser GNU GPL).

libgcc ABI is too volatile with its problems and c++ ABIs are manifestations of
insanity on earth (is clang c++ ABI does work with gcc c++ ABI?). Only 1-2 (gcc/clang)
compilers are roughly able to deal with advanced c++ code, and they have been in
developpement for decades...

c++ is good as an element to learn object orientation since it's explicit in the syntax. 
But it's should stay only an academic language because its implementation complexity
and the tendancy of coders to abuse its complex syntax as a proof of their
mental sic... cleverness.

-- 
Sylvain

**Comment by es20490446e** [comment]
Sylvain Bertrand:
> A lot of abstraction is dealed by libSDL2 which is open source the right way
> (Lesser GNU GPL).

Why is that the right way?


Sylvain Bertrand:
 > C++ should stay only an academic language because its implementation
 > complexity and the tendency of coders to abuse its complex syntax as
 > a proof of their mental sic... cleverness.

What language do you suggest when the application requires performance 
to be regular? Lets say a game engine, where we don't want to have 
micro-stuttering because of a garbage collector.

**Comment by kparal** [comment]
This is not a chat, please take your off-topic discussion elsewhere, all 3 of you. Each of your comments is spamming 30 people.

**Comment by es20490446e** [comment]
Kamil Páral:
> Please take your off-topic discussion elsewhere.

Sorry, you are right.
