### ISSUE TITLE
Repository problem in Ubuntu 14.04

### ISSUE THREAD

**Issue by Vincentdc94** [ValveSoftware/steam-for-linux#3278]
The repository steam uses on thrusty is a precise repository. 

An other problem I encountered with this is when doing a "sudo apt-get update" It keeps hanging at 100%.

Removing the steam ppa from "software sources" in "settings" solved this problem.

**Comment by Goddard** [comment]
Running 14.04.3 on a fresh install and I have this issue.

Every time I launch steam I am pestered to install some i386 libraries for Mesa.  It never finds them.  I thought the repo should have a directory listing... Is this correct? 

http://repo.steampowered.com/steam/dists/precise/steam/binary-amd64/Packages
