### ISSUE TITLE
Still not fixed: xcb_send_fd

### ISSUE THREAD

**Issue by cookiengineer** [ValveSoftware/steam-for-linux#3281]
When will this issue be fixed? It's marked as fixed, but not shipped yet. After over 4 months. I mean, pretty all Linux users can't use the steam runtime at the moment.

See the other issues #3231, #3238, #3204

Updated a minute ago (Ubuntu 14.04 LTS), still having the identical issues as already reported. Don't want to comment an all the re-referenced bugs as someone closes it and it seems to never get fixed otherwise. I mean, there's already an arch wiki entry for overwriting the library due to no-reaction on your side (https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Game_does_not_start_with_libxcb-dri3_error_message)
1. Why is it marked as fixed and not rolled out?
2. How can it be proven to work if not in production?
3. Why are all issues closed if it's not fixed yet?
4. Is there an official upgrade guide for a nightly build?

You currently leave Linux users no other option than fixing it themselves and patching libraries. I wanted to avoid that, but I can't, as nothing happens on your side.

``` bash
(steam:20690): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 242: 1024x256, total string texture memory is 3,06 MB
Generating new string page texture 243: 8x256, total string texture memory is 3,06 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 254: 128x256, total string texture memory is 3,19 MB
Generating new string page texture 279: 256x256, total string texture memory is 3,46 MB
CAPIJobRequestUserStats - Server response failed 2
Game update: AppID 80 "Counter-Strike: Condition Zero", ProcID 20801, IP 0.0.0.0:0
Could not load hw.so.
Please try again at a later time.Error:/usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_fd
CGameStreamThread: Added instance ID 20801 for appid 80
CGameStreamThread: Set render instance ID 20801 for appid 80
Game removed: AppID 80 "Counter-Strike: Condition Zero", ProcID 20801 
```

**Comment by kisak-valve** [comment]
Closing pending feedback.
