### ISSUE TITLE
Wargame Airland Battle: Nvidia Optimus (Bumblebee) not working under Linux.

### ISSUE THREAD

**Issue by Arandhras** [ValveSoftware/steam-for-linux#3290]
I am running Ubuntu 14.04 64 bit on an Asus N550JV laptop and I cannot use the dedicated GPU (an Nvidia Geforce GT 750M) that my computer has. To make use of it, I have successfully installed Bumblebee following the instructions on Ubuntu's wiki ( https://wiki.ubuntu.com/Bumblebee ), and the card works well with any other game I have tested so far.

Even if I launch Wargame ALB as stated in the Steam knowledge-base ( https://support.steampowered.com/kb_article.php?ref=6316-GJKC-7437 ), the game is telling me that it's using the integrated Intel video card instead of the discrete Nvidia one -- and the game is noticeably slower than what it is under Windows.

**Comment by kisak-valve** [comment]
Hello @Arandhras, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
