### ISSUE TITLE
Awesome WM: Steam pops up in other screen.

### ISSUE THREAD

**Issue by FreeSlave** [ValveSoftware/steam-for-linux#3299]
Awesome WM has arbitrary number of screens, and I usually leave steam in one of them. But sometimes steam pops up in other screens if it's not minimized. It's only image, not actual window.

[Example](https://dl.dropboxusercontent.com/u/40401686/steam_awesome_glitch.png). Here I'm currently on fourth screen with Google Chrome. Steam is on first. But it renders to another screen somehow. Some areas of google chrome were updated and we got this mess.

My system according to Xorg -version:

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-4-amd64 i686 Debian
Current Operating System: Linux debian 3.10-3-686-pae #1 SMP Debian 3.10.11-1 (2013-09-10) i686
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.10-3-686-pae root=UUID=454a0eec-27cc-4dbc-8b68-24fdefbab3e0 ro quiet

Awesome version:

awesome v3.4.15 (Never Gonna Give You Up)
 • Build: Feb 17 2013 11:18:13 for i686 by gcc version 4.7.2 (buildd@biber)
 • D-Bus support: ✔

There is also another similar problem with games: for example, after I quit Half-Life, its menu is still displayed on current screen where steam is placed. It disappears after some screen update. 
Sometimes I switch from another screen to screen with steam, but image remains the same as on last screen, and steam window appears only after update.

My steam version is from April 23 2014

**Comment by kisak-valve** [comment]
Closing as this does not appear to be a steam issue.
