### ISSUE TITLE
Overlay crashes when removing a friend / request

### ISSUE THREAD

**Issue by copywrong** [ValveSoftware/steam-for-linux#3300]
The Steam Overlay crashes when I remove a friend or remove a friend request using the Friends window in Overlay mode. I only tested it with 800x600 resolution but it should crash with any resolution.

Steam Runtime Version:  steam-runtime-release_2014-04-15

**Comment by kisak-valve** [comment]
Hello @copywrong, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
