### ISSUE TITLE
Unable to start Steam on Debian jessie with proprietary AMD Catalyst 14.4

### ISSUE THREAD

**Issue by BitVortex** [ValveSoftware/steam-for-linux#3304]
Debian jessie (`Linux olympus 3.13-1-amd64 #1 SMP Debian 3.13.10-1 (2014-04-15) x86_64 GNU/Linux`)
`steam 1.0.0.47-2`
`fglrx-driver 1:14.4-2`
HD7950 (3 connected displays)

I was able to install and update Steam just fine, but it refuses to start while the proprietary AMD drivers are active, leaving me with the following:
Output when starting it in console: http://pastebin.com/TrnYePGP
Output when starting it in console with STEAM_RUNTIME=0: http://pastebin.com/v03ciMk1

I am able to start Steam with the open-source driver, but as soon as I revert to the proprietary one, it stops working again. Performance-wise, the open-source driver just isn't suited for gaming on this card, so someone should definitely look into this.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
