### ISSUE TITLE
The name org.freedesktop.NetworkManager was not provided by

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3305]
Hi,

To start with I know that the Steam client is only supported on Ubuntu, or at least that's my understanding, or another distro along the same lines as Ubuntu...

But it would be nice if this issue can be passed along to Valve to change the way the client is reporting networking.

I use Steam in Slackware and yes it does have the NetworkManager that was just added into Slackware 14.1, but I only use wicd.

It would be nice for other distro/network users if something could be changed in the code regarding this.

Also if I go into 'Big Picture' nothing is listed for my Network, so it would be nice to get Steam also working with others Network Clients besides the NetworkManger.

Please add support for wicd, and remove WARNING about the NetworkManager when it's not installed on a distro.

Or no matter what network client you use, it works properly with the Steam.

Thank you for your consideration. :)

**Comment by moulei** [comment]
I've recently switch from connman back to wicd, since wicd just released a new version.

When I'm running Steam there is no networking detected, it also says there's no wired and wireless...

Why wouldn't steam at least detect the wired and wiireless hardware? Hmm

```lspci``` for my wired and wireless;
```03:00.0 Network controller: Atheros Communications Inc. AR9485 Wireless Network Adapter (rev 01)
04:00.0 Ethernet controller: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet (rev c0)
```

**Comment by meuwe** [comment]
@Tele42 wicd development has not been halted, a new version was released on Dec. 2014, version 1.7.3

https://launchpad.net/wicd

**Comment by kisak-valve** [comment]
While steam is still throwing a warning if there isn't a running instance of networkmanager, there should be no other show stoppers left here that prevents users from using other connection managers. As long as Steam is able to reach Valve's servers in general, then there should not be a functional problem.
