### ISSUE TITLE
Constantly Get Can't Connect To Steam Client Message

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3310]
Hi,

Quite often I get a message with steam telling me it can't connect, after I type in my username and password, then it says connecting steam account, and then I get a message it can't connect

Here's some system specs; (If you need more let me know)

```
Slackware 14.1 86_64
Openbox 3.5.2
wicd 1.7.2.4
```

Here's a dump it gave me from /tmp/dump

assert_20140517173359_13.dmp
https://www.dropbox.com/s/8w59a1b09zahee3/assert_20140517173359_13.dmp

log.txt
https://www.dropbox.com/s/1c3xaript47rucq/log.txt

stdout.txt
https://www.dropbox.com/s/eqkfaq9bvrsof1j/stdout.txt

**Comment by kisak-valve** [comment]
Closing as the user has turned into a ghost.
