### ISSUE TITLE
Unicode font corruption

### ISSUE THREAD

**Issue by Asrael** [ValveSoftware/steam-for-linux#3311]
Hello, sorry if this has already been reported. I noticed Chinese characters being corrupted on the friends list and chat dialogs, screenshot attached. My locale is en-US.

If there's any further information I can give to help, let me know.

![screenshot - 05192014 - 01 40 23 pm](https://cloud.githubusercontent.com/assets/1847101/3019776/76581d04-df96-11e3-95e4-2f480c752475.png)

**Comment by kisak-valve** [comment]
Closing in favor of #1889.
