### ISSUE TITLE
Steam uses the microphone x-fi, but adjusts the volume of the microphone realtek

### ISSUE THREAD

**Issue by obedlink** [ValveSoftware/steam-for-linux#3312]
![instantnea1](https://cloud.githubusercontent.com/assets/3372664/3022182/067673d2-dfc3-11e3-9599-597d8f853052.jpeg)
I have a creative x-fi, the microphone of the x-fi is the primary, the secondary is the realtek microphone.

Steam beta perfectly detects the default microphone using pulseaudio (microphone x-fi). but the microphone volume control adjusts the volume of the realtek card.

no matter if I use "change device" or "pulseaudio default"

to adjust the volume of my microphone x-fi I have to use kmix.

summarizing:
Steam uses the microphone x-fi, but adjusts the volume of the microphone realtek

I use Kubuntu 14.04 updated.

**Comment by kisak-valve** [comment]
Hello @obedlink, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
