### ISSUE TITLE
ATI/Xinerama Segmentation Fault (and fix) - Mint 17

### ISSUE THREAD

**Issue by mikeeheler** [ValveSoftware/steam-for-linux#3321]
I was receiving a segmentation fault when launching the steam client on Mint 17. I don't have Xinerama enabled, and I only have 1 screen on.

OS: Mint 17 Cinnamon (based on Ubuntu 14.04 LTS)
ATI Driver: fglrx-updates 2:13.350.1-0ubuntu2
-- As of right now, fglrx and fglrx-updates are the same version.

To fix the crash, I ran:

$ apt-get install libxinerama1:i386

**Comment by johnv-valve** [comment]
This is fixed in the current .deb package (1.0.0.50) which is available on steampowered.com.
