### ISSUE TITLE
The Witcher 2: Assassins of Kings Enhanced Edition - Failed to start game (missing executable)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#3322]
![screenshot from 2014-05-24 15 03 15](https://cloud.githubusercontent.com/assets/200750/3074137/835138c2-e326-11e3-8070-95f37ff8f677.png)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.4-200.fc20.x86_64+debug
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 10.1.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31074 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  3815446 Mb
    Largest Free Hard Disk Block:  1449347 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @NTMan, @nekoexmachina, are either of you still experiencing this issue?

**Comment by nekoexmachina** [comment]
This is quite a joke of the responce speed.

I'm quite sure that problem is limited to Russia. I recall playing without issue a year or two ago, but I've moved out from Ru almost 3 years ago.

**Comment by NTMan** [comment]
Thanks, on latest Fedora 27 x86_64 + kernel 4.15 + mesa 17.4 and llvm 6.0 on AMD Vega 56 The Witcher 2 works perfect. Also The Witcher 2 works on Fedora 27 with default kernel + mesa 17.2.4 and llvm 4.0.1 on Intel GPU Haswell but not so good as on AMD Vega 56.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
