### ISSUE TITLE
[all steam client version][feature request]free 2 play games entry would be removed when game content removing

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3331]
[all steam client version]free 2 play games entry would be removed when game content removing

many free to play games on steam, all got this issue.
and windows ver. and linux ver. of steam client all got this issue.

the free to play game entry only got kept in the steam client game library, only when you have related game content on your harddisk left there. 
if you delete the harddisk content about the game, the game entry would be deleted from you steam library of the steam client.

so, if you want the free2play game entries left in you library, and you have to keep the game content, you cannot delete them.

or, you have another way, set the auto download disabled.
and only download the very tiny beginning part of the game, to save some harddisk space.

i thought this is inconvinient. 

maybe you can change it. make the free2play games which players once played/downloaded, can be kept/left in the game library of the steam client for the users.

thank you.

**Comment by dreamer** [comment]
Maybe it's resurrecting an old issue, but it's still a problem as of 2019.

It's a shame really - because I can't have games like Battle for Wesnoth or Deus Ex: Revision kept in my Library - even if I specifically tag them or add to Favourites - while all of them are recognized by external services as "In my library".

**Comment by OvermindDL1** [comment]
> It's a shame really - because I can't have games like Battle for Wesnoth or Deus Ex: Revision kept in my Library - even if I specifically tag them or add to Favourites - while all of them are recognized by external services as "In my library".

And of course you can still play them with the appropriate `steam://...` url too, so they really should be listed...

**Comment by kisak-valve** [comment]
Closing per "Free to Play games will now remain in your Steam Library when uninstalled. You can remove these titles by right clicking on the game’s entry in your library." in the [2019-10-30](https://store.steampowered.com/news/55600/) Steam client update.
