### ISSUE TITLE
Steam won't start

### ISSUE THREAD

**Issue by HantraxHat** [ValveSoftware/steam-for-linux#3332]
Running Steam on ubuntu 14.04 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/threadtools.cpp (2024) : Assertion Failed: File già esistente
Assert( Assertion Failed: File già esistente ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/threadtools.cpp:2024

Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20140529221250_4.dmp
[2014-05-29 22:12:50] Startup - updater built May 29 2014 09:19:23
[2014-05-29 22:12:50] Verifying installation...
[2014-05-29 22:12:50] Verification complete
[2014-05-29 22:12:51] Shutdown
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-c4b44a3e-d0ff-403b-8ffe-7d7292140529

Just reinstalled, purged, deleted steam and local/steam folder but nothing...

**Comment by kisak-valve** [comment]
Hello @HantraxHat, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
