### ISSUE TITLE
Steam - BPM: Shutdown and restart not working

### ISSUE THREAD

**Issue by melo0187** [ValveSoftware/steam-for-linux#3333]
I'm running Steam on Ubuntu 14.04 64-bit (Kernel 3.13.0-24-generic) and Steam doesn't seem to be able to shutdown or reboot the system. 
When selecting "Shutdown" or "Restart" in BPM simply nothing happens. I can choose return to desktop or exit Steam, but selecting shutdown or reboot does nothing. I was running Steam on Ubuntu 13.04 before and was not experiencing this problem.

Related discussion on steamcommunity: http://steamcommunity.com/app/221410/discussions/0/558754259527313408/

Hope this gets a little attention since you can not finish a gaming session from the couch, making the use of BPM less attractive.

I would be glad to help with system details, tests and any information I can provide.

**Comment by johnv-valve** [comment]
reboot and shutdown should now work if you have either ConsoleKit OR logind/systemd.

**Comment by melo0187** [comment]
I am confused. Just yesterday I had to install ConsoleKit on Ubuntu 15.04 64bit to get reboot and shutdown to work in Steam BPM, but you say having systemd should also work. Ubuntu 15.04 made the switch to systemd. So why did I still need to install ConsoleKit to make this work or am I mixing things up here?
Thanks in advance for clarification.
