### ISSUE TITLE
"OpenGL GLX extension not supported by display" & xorg.conf

### ISSUE THREAD

**Issue by GitRASQ** [ValveSoftware/steam-for-linux#3334]
I installed steam and it worked fine at first. Then I created an xorg.conf file to fix a text scaling issue with the Nvidia drivers. After a reboot I tried to start steam and got the error message: "OpenGL GLX extension not supported by display". 

Removed xorg.conf, rebooted and it works again. Replaced xorg.conf with default version to check whether the problem was caused by the line I added, but got the same error with default file. Steam won't start as long as the file exists.

Kubuntu 14.04
Nvidia GTX 560
Driver 331.38

**Comment by kisak-valve** [comment]
Hello @GitRASQ, are you still experiencing this issue on an up to date system?

**Comment by GitRASQ** [comment]
I've been using Arch for a long time and have different hardware now. This certainly isn't a problem for *me* anymore.
