### ISSUE TITLE
"View" Toolbar menu leaves square portion of desktop background visible in Big Picture mode

### ISSUE THREAD

**Issue by erpadmin** [ValveSoftware/steam-for-linux#3337]
When switching from Large Mode view to Big Picture mode there is a square in the shape of the View Toolbar window which contains the desktop background that remains visible.

When switching from small mode to Big Picture mode the results are similar only that the toolbar menu is actually there.

This is on Linux Mint 16 Mate Desktop, latest Nvidia Driver.

So maybe that description is confusing, I will attach some images:
![screen1](https://cloud.githubusercontent.com/assets/2635831/3140713/a9168980-e935-11e3-80f3-00ceb00f363f.png)
![screen2](https://cloud.githubusercontent.com/assets/2635831/3140714/ae96cb9a-e935-11e3-9509-b9c8c5b4af5e.png)

Work around after the fact is to get back to the desktop and Click "view" again to the get the toolbar menu to close then go back to Big Picture mode.  Launching Big Picture mode from the system tray icon or, if in Large mode, the Big Picture (icon?) on the right will avoid the issue.

**Comment by kisak-valve** [comment]
Hello @erpadmin, @ali1234, are either of you still experiencing this issue on an up to date system?

**Comment by ali1234** [comment]
I can no longer reproduce this.

**Comment by kisak-valve** [comment]
Thanks for retesting @ali1234, closing.
