### ISSUE TITLE
Steam does not work on linux ubuntu 14.04

### ISSUE THREAD

**Issue by FlorusG** [ValveSoftware/steam-for-linux#3345]
When you start steam message "Steam is having trouble connecting to the Steam servers.

From terminal:
jakub@PC:~$ steam
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0526/004126:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
[HTTP Remote Control] HTTP server listening on port 34547.
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Installing breakpad exception handler for appid(steam)/version(1400690891_client)
Generating new string page texture 7: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 8: 64x256, total string texture memory is 196,61 KB
Generating new string page texture 9: 48x256, total string texture memory is 245,76 KB
Generating new string page texture 10: 256x256, total string texture memory is 507,90 KB
Generating new string page texture 11: 16x256, total string texture memory is 524,29 KB
Generating new string page texture 12: 24x256, total string texture memory is 548,86 KB
Generating new string page texture 13: 32x256, total string texture memory is 581,63 KB
Installing breakpad exception handler for appid(steam)/version(1400690891_client)

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been a local network issue.
