### ISSUE TITLE
Steam Crashes on Startup Linux Mint 17

### ISSUE THREAD

**Issue by Ubuntumaster** [ValveSoftware/steam-for-linux#3348]
Terminal Output:
me@computer ~ $ steam
Running Steam on linuxmint 17 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140606230339_1.dmp
/home/me/.local/share/Steam/steam.sh: line 755: 19405 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/me/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/me/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on linuxmint 17 64-bit
STEAM_RUNTIME has been set by the user to: /home/me/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140606230340_1.dmp
/home/me/.local/share/Steam/steam.sh: line 755: 19535 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-7938169f-b6f8-4111-893e-fcc672140606
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-9f2e10c5-ba0a-4af7-836f-635ef2140606

Here is a download for the crash .dmp file:  http://www.mediafire.com/download/3z7hzaaee8p3zqw/crash_20140606205721_1.dmp 

Thanks for looking over my boring bug report.

**Comment by kisak-valve** [comment]
Hello @Ubuntumaster, @xMouch, if either of you are still experiencing this issue, it'll require a new investigation. Please open a new issue report if that is the case.

Closing as general video driver related issues from 2014 is no longer relevant.
