### ISSUE TITLE
[Minor] Store page videos stutter if mouse is not moving

### ISSUE THREAD

**Issue by praashie** [ValveSoftware/steam-for-linux#3350]
When videos are played in game store pages, the framerate stutters, but audio plays fine. The problem disappears when the mouse is moved at least one pixel per frame, but returns whenever the mouse is not moving.

Hardware info:

    Operating System Version:
        Ubuntu 14.04 LTS (64 bit)
        Kernel Name:  Linux
        Kernel Version:  3.13.0-031300-generic
        X Server Vendor:  The X.Org Foundation
        X Server Release:  11501000
        X Window Manager:  Compiz
        Steam Runtime Version:  steam-runtime-release_2014-04-15

    Video Card:
        Driver:  X.Org Gallium 0.4 on AMD BARTS

        Driver Version:  3.0 Mesa 10.3.0-devel (git-1751a9b trusty-oibaf-ppa)
        OpenGL Version: 3.0
        Desktop Color Depth: 24 bits per pixel
        Monitor Refresh Rate: 60 Hz
        VendorID:  0x1002
        DeviceID:  0x673e
        Number of Monitors:  2
        Number of Logical Video Cards:  1
        Primary Display Resolution:  1920 x 1080
        Desktop Resolution: 3200 x 1080
        Primary Display Size: 20.08" x 11.42"  (23.07" diag)
                                                51.0cm x 29.0cm  (58.6cm diag)
        Primary VRAM Not Detected

**Comment by D-Code** [comment]
Noticed that videos are a lot smoother when watching them in fullscreen.

**Comment by praashie** [comment]
@D-Code I just tried watching trailers with both the Beta and non-Beta -versions of the Steam Client, and the Beta version fixes the problem for me too.
