### ISSUE TITLE
Clear, Narrow Box Visible on Applications in Front of Steam Client

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/steam-for-linux#3351]
The very, <i>very</i> odd time the Steam client is open, I will see the graphic of a clear, narrow box on top of any application I have running in front of the Steam client.

Here I have a browser open in front of the Steam client.

![screenshot from 2014-06-09 03 26 41](https://cloud.githubusercontent.com/assets/1007764/3214574/dc46a57e-efb1-11e3-9fb9-59c9e396ee21.png)

What's more, if I click on the box, it brings the Steam client to the front, and highlights whatever item my cursor was on top of at the moment (a game title, a link, etc).

I can see the box outline on top of the Steam client and on the desktop background, too.

Thank you.

System Information:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x5
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-39-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6700 Series

```
Driver Version:  4.3.12682 Compatibility Profile Context 12.104
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x673e
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                        60.0cm x 34.0cm  (68.9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  232570 Mb
    Largest Free Hard Disk Block:  114934 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @sunnybubblegum, have you seen this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
