### ISSUE TITLE
 Civilization V won't start

### ISSUE THREAD

**Issue by zaufi** [ValveSoftware/steam-for-linux#3353]
I was really exciting when my favourite game came into Linux world (finally), until tried to start it:

Running Steam on gentoo 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
[0612/001913:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
[HTTP Remote Control] HTTP server listening on port 48521.
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1401381906_client)

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/13 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/0 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/1 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/2 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/6 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/7 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/8 settings: (1) type

*\* (steam:3966): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/9 settings: (1) type
Adding licenses for the following package(s): 0, 5, 19, 502, 36076
roaming config store loaded successfully - 191 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
sh: lspci: command not found
ExecCommandLine: "/home/zaufi/.local/share/Steam/ubuntu12_32/steam"
System startup time: 6,61 seconds
Running Steam on gentoo 64-bit
STEAM_RUNTIME has been set by the user to: /home/zaufi/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 70: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 71: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 72: 64x256, total string texture memory is 507,90 KB
Generating new string page texture 73: 32x256, total string texture memory is 540,67 KB
ExecCommandLine: "/home/zaufi/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Generating new string page texture 98: 384x256, total string texture memory is 933,89 KB
Generating new string page texture 99: 24x256, total string texture memory is 958,46 KB
Generating new string page texture 100: 128x256, total string texture memory is 1,09 MB
Generating new string page texture 105: 512x256, total string texture memory is 1,61 MB
Generating new string page texture 106: 8x256, total string texture memory is 1,62 MB
Generating new string page texture 107: 16x256, total string texture memory is 1,64 MB
Generating new string page texture 108: 256x256, total string texture memory is 1,90 MB
Steam: An X Error occurred
X Error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 40 (X_TranslateCoords)
Resource id in failed request: 0x183ee72
Serial number of failed request: 4691
xerror_handler: X failed, continuing
Generating new string page texture 113: 128x256, total string texture memory is 2,03 MB
Generating new string page texture 114: 48x256, total string texture memory is 2,08 MB
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Installing breakpad exception handler for appid(steam)/version(1401381906_client)
Game update: AppID 8930 "Sid Meier's Civilization V", ProcID 4189, IP 0.0.0.0:0
ERROR: ld.so: object '/home/zaufi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/zaufi/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3966): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID: Caching Steam ID: 76561197974839199 [API loaded no]
Game removed: AppID 8930 "Sid Meier's Civilization V", ProcID 4190

googling gave no helpful info, so I'm here... hope someone can help...

**Comment by agwilt** [comment]
2 years later I have the same problem. Did you manage to fix it?

**Comment by Gagravarr** [comment]
I bought a new laptop and it started working! My previous laptop didn't quite meet the minimum spec's, and rather than the game giving some helpful warnings about this, it just silently exited.

**Comment by agwilt** [comment]
Wow, that was fast! I managed to run Civ 5 on my laptop before, so I'm doubly puzzled why it won't start now. But I just found some rather useful dmesg output:

`Civ5XP[8783] general protection ip:f6c606d1 sp:f5812a44 error:0 in libxcb.so.1.1.0[f6c53000+2a000]`

Maybe I'll try downgrading lib32-libxcb ..

**Comment by agwilt** [comment]
Yes, that did it.

**Comment by kisak-valve** [comment]
Hello @zaufi, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as this does not appear to be a steam client issue.
