### ISSUE TITLE
Wrong CPU speed detected

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3355]
Hi,

so, I just noticed Steam detecing wrong CPU speed. The system information output says the following. 
https://gist.github.com/Paxnos/8b960dbdca12c74a2bde

The CPU in my computer is an Intel Core i5-2400.
I'm using the current Steam Beta.

Not really issue and just something I wanted to add: It'd be cool if the system information statistics showed the circulation of AVX (and possibly AVX 2) support.

**Comment by kisak-valve** [comment]
Closing as the user has turned into a ghost. Steam should just be collecting the cpu speed reported by the kernel at the time the system information is generated.
