### ISSUE TITLE
Trade offer notification

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3357]
I had 7 new trade offers, I did couple of them and 2 of them became inactive because of "Items Now Unavailable For Trade". So now in upper right corner I have green envelope and I cant mark trade offers as read because they are inactive, and green envelope is still on.

**Comment by kisak-valve** [comment]
Hello @ahailes, @ozone89, have either of you seen this issue in recent history?

**Comment by kisak-valve** [comment]
Closing as this issue would require a new investigation if it is still around.
