### ISSUE TITLE
closing friends window closes steam

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#3358]
i am on gentoo/kde and when i right click the friends window in the taskbar to close it it closes all of steam.

**Comment by kisak-valve** [comment]
Hello @cjwijtmans, @boombatower, are either of you still experiencing this issue on an up to date system?

**Comment by cjwijtmans** [comment]
I am currently not running gentoo/kde anymore due to KDE "abbandoning" support for X11 and nvidia. I could try it on a few mint machines but not sure that will reproduce the bug..

**Comment by kisak-valve** [comment]
Closing pending feedback.

As a side note, https://blog.martin-graesslin.com/blog/2018/01/kwinx11-is-feature-frozen/ should be read as "no more X11 exclusive features allowed" not "no more support for X11." It makes sense that they don't want to support enhancements to kwin that won't be usable in a potentially wayland-centric future.
