### ISSUE TITLE
_xgeWireToEvent: Unknown extension 148, this should never happen.

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/steam-for-linux#3364]
This message is being spammed over and over again to the console when simply running the steam client, many times per second, while the mouse keeps moving over the steam window. While the mouse stands still over the window, it stops.

The latest (well, from over three months ago) commit to libXext removes this warning message with the explanation:

> When mixing Xlib and xcb, it's quite possible for some events to be
received for xcb-only extensions, which will subsequently not be
translatable by the Xge WireToEvent/EventToWire hooks

http://cgit.freedesktop.org/xorg/lib/libXext/commit/?id=11aad96bd689d54156064d2e81213dc827a689d1

This is with archlinux with a lot of bleeding edge stuff.

**Comment by MagiX13** [comment]
Not sure if this helps, but I upgraded to Ubuntu 14.10 and got this message and problems following it.
I then formatted my / (kept /home) and installed 14.04 again. The message disappeared and everything worked flawless (so far)

**Comment by swat30** [comment]
Having the same issue w/ Fedora 21. Have subscribed to Steam Beta, still seeing the journalctl messages.

@Plagman has the fix been pushed yet?

**Comment by xarinatan** [comment]
@Plagman The latest Steam beta update seems to fix the issue for me! I've left my laptop running with Steam open all night and there's no excessive log spam or /tmp filling so far. I'll get back here if that changes, but so far so good :+1:

**Comment by Plagman** [comment]
Thanks for the confirmation!

**Comment by xarinatan** [comment]
Thanks for the fix! It was really a pain to come back to a completely filled up /tmp partition every now and then, causing lots of programs to behave erratically. I've also had a much better battery life the past two days.
