### ISSUE TITLE
Friend is un-added everytime I exit Steam

### ISSUE THREAD

**Issue by NinjaGal** [ValveSoftware/steam-for-linux#3367]
Steps to reproduce:
1. Add friend: http://steamcommunity.com/profiles/76561198028885025/
2. Exit Steam Application
3. Look through friends list and scroll through page.
4. Notice that the friend I just added is gone.

FYI: Here's my SteamAddress - http://steamcommunity.com/id/ninjagal/

We've already added each other multiple times, I've added a nickname/alias already so he's easily searchable but everytime we check each other's name, we're automatically removed from each other's friends list.

**Comment by kisak-valve** [comment]
Hello @NinjaGal, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
