### ISSUE TITLE
Market price graph cursor `.graph {cursor:crosshair}` does not display properly

### ISSUE THREAD

**Issue by boombatower** [ValveSoftware/steam-for-linux#3368]
![image](https://cloud.githubusercontent.com/assets/209374/3349729/46e95aa2-f976-11e3-82d3-425a0ae1a939.png)

On Windows this looks as expected.

**Comment by kisak-valve** [comment]
Hello @boombatower, are you still experiencing this issue on an up to date system?

**Comment by boombatower** [comment]
Does not appear to still be an issue.
