### ISSUE TITLE
Interface responds to mouse rollover, but clicking does nothing.

### ISSUE THREAD

**Issue by supereater14** [ValveSoftware/steam-for-linux#3369]
The steam interface outside of the main frame (things like the store, library and community buttons) light up as they should when the mouse rolls over them, but do not respond to being clicked.Currently I am switching between the store, library, etc. and going back in the store by closing the window (which has to be done from the taskbar, since the "close" button is ppart of the interface that isn't working) and reopening via the dashbar icon. I am running Steam on Arch linux with an intel core i5 and intel hd 4000 graphics (it's a lenovo T430)

**Comment by kisak-valve** [comment]
Closing in favor of #3078.
