### ISSUE TITLE
Steam doesn't properly discover existing files when installing

### ISSUE THREAD

**Issue by RollingStar** [ValveSoftware/steam-for-linux#3370]
Here's how I encountered this bug:
1. Install Windows 7 x64.
2. Install games on Steam to F:\Program Files (x86)\steam\steamapps...\
3. Install Windows 8.1 x64.
4. Install Steam to C:\ and cut-and-paste my existing Steam library to D:\PX\steam\steamapps...\
5. Try re-installing a game I already had 100% installed, like Lunnye Devitsy, Dust: An Elysian Tail, or Fez.
6. The Dust installer says it discovered the original files, but then starts downloading the entire game at 0%.
7. "Verify integrity of game cache" on Dust: AET.
8. Pause and re-start "all" downloads within the Steam client.
9. Steam discovers the existing files and continues the download from around 99% complete.

Sorry that it's for Windows, but I don't have a Steam community forums account.

**Comment by kisak-valve** [comment]
Hello @RollingStar, @praashie, are either of you still experiencing this issue on an up to date system?

**Comment by RollingStar** [comment]
I can't say one way or the other. Many Steam changes over the years with library folders so I would assume it's fixed.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
