### ISSUE TITLE
Tf2 bugg

### ISSUE THREAD

**Issue by Wakkyjax** [ValveSoftware/steam-for-linux#3374]
Dear Valve again and this is about tf2 and im not pleased cuz i my taunt is not working for any of my class want to see? And it is in my backpack but not in the classes ;-;
![2014-06-23_00002](https://cloud.githubusercontent.com/assets/7689354/3363313/56d8d7ba-fb12-11e3-8099-78f684fff575.jpg)
![2014-06-23_00001](https://cloud.githubusercontent.com/assets/7689354/3363335/6702b73c-fb12-11e3-8a67-7f00116b1456.jpg)

**Comment by kisak-valve** [comment]
Hello @Wakkyjax, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If this is still an issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
