### ISSUE TITLE
Portal 2 Thinking with Time Machine - Protagonist displayed without textures

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#3375]
Portal 2 Thinking with Time Machine - Protagonist displayed without textures

![2014-06-24_00003](https://cloud.githubusercontent.com/assets/200750/3374598/46e4b244-fbc0-11e3-8e4b-d0edd31bdb14.jpg)
![2014-06-24_00002](https://cloud.githubusercontent.com/assets/200750/3374597/46e3d928-fbc0-11e3-88d7-e37b52cde110.jpg)
![2014-06-24_00001](https://cloud.githubusercontent.com/assets/200750/3374599/46e6b602-fbc0-11e3-8831-d3f1eaa8d656.jpg)

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.8-200.fc20.x86_64+debug
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 10.1.5
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31094 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  3815446 Mb
    Largest Free Hard Disk Block:  1296696 Mb

Installed software:

Recent Failure Reports:
    Tue Jun 24 16:44:07 2014 GMT: file ''/tmp/dumps/assert_20140624224342_21.dmp'', upload yes: ''CrashID=bp-79956e89-41a4-4287-8a11-bb1ad2140624''

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/portal2/issues/289.
