### ISSUE TITLE
Alsa 1.0.28 breaks sound with steam runtime

### ISSUE THREAD

**Issue by dcelasun** [ValveSoftware/steam-for-linux#3376]
I'm on an up-to-date Arch Linux x86_64. Two days ago, all alsa related packages got a version bump:

```
[2014-06-20 12:30] [PACMAN] upgraded alsa-lib (1.0.27.2-1 -> 1.0.28-1)
[2014-06-20 12:30] [PACMAN] upgraded alsa-plugins (1.0.27-2 -> 1.0.28-1)
[2014-06-20 12:30] [PACMAN] upgraded alsa-utils (1.0.27.2-1 -> 1.0.28-1)
[2014-06-23 10:44] [PACMAN] upgraded lib32-alsa-lib (1.0.27.2-1 -> 1.0.28-1)
[2014-06-23 10:44] [PACMAN] upgraded lib32-alsa-plugins (1.0.27-1 -> 1.0.28-1)
```

Now there is no sound with steam runtime enabled. I tried flash videos on the store and in-game in TF2. Starting steam with `STEAM_DEBUG=1`, alsa 1.0.28 has the following error:

```
ALSA lib pcm_ioplug.c:920:(snd_pcm_ioplug_create) ioplug: Plugin version mismatch
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
```

I have tried removing related libraries from the runtime to no avail. As a workaround I have downgraded to 1.0.27, but this should probably be fixed in the runtime.

[Here](http://www.alsa-project.org/main/index.php/Changes_v1.0.27.2_v1.0.28) is the upstream changelog.

**Comment by ivan-kolmychek** [comment]
Yeah, got this yesterday.

Removing the `libasound.so` files and `alsa-lib` folders works for me too.

**Comment by her001** [comment]
For those that are having issues and waiting for a fix, you can also just not use 32bit flashplayer and then everything will work fine.

**Comment by boskar** [comment]
Worked for me today in Debian sid (broken ~3 days ago).

**Comment by samuelholuk** [comment]
No joy for me, also on sid

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
