### ISSUE TITLE
Steam frontpage update (during summersale) crashes client to memory leak

### ISSUE THREAD

**Issue by vatjjar** [ValveSoftware/steam-for-linux#3379]
I was running steam linux client during the summer sale, and during the idle time the frontpage updated (timer expire and new flash sales should come up). At this exact moment the client crashes. Last lines in the console are:

[0626/114649:ERROR:nss_ocsp.cc(588)] No URLRequestContext for OCSP handler.
ExecSteamURL: "steam://openurl/http://steamcommunity.com/my/gamecards/303700/"
**\* Error in `/home/xxx/.local/share/Steam/ubuntu12_32/steam': double free or corruption (fasttop): 0xf862c880 ***

**Comment by kisak-valve** [comment]
Hello @vatjjar, have you seen this issue with an up to date client?

**Comment by vatjjar** [comment]
Wow, this is an old one already. :) No, I've not had any related issues with the up-to-date client, thank you!

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
