### ISSUE TITLE
CS:S + LINUX + MIC = BROKEN ... WTF?

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [ValveSoftware/steam-for-linux#3380]
When will Counter-Strike Source support microphones on Linux? This is BS. This was a bug while in BETA and is STILL BROKEN!!!!! WTF?!?!?!

**Comment by kisak-valve** [comment]
Hello @DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K, if you're still experiencing this issue on an up to date system, please open a new issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
