### ISSUE TITLE
TF2 mini-freezes after switching tags

### ISSUE THREAD

**Issue by kiwec** [ValveSoftware/steam-for-linux#3385]
TF2 works perfectly with AwesomeWM, until I switch tabs to see a skype message or something else. Then, when I switch back, TF2 is running at about 50fps (instead of 250), BUT there are freezes constantly, making it feel like the game is at 5fps.

The only way to avoid this is to never switch or to relaunch the game after switching.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.15.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7800 Series 

```
Driver Version:  4.4.12967 Compatibility Profile Context 14.20
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6818
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,91" x 11,77"  (23,98" diag)
                                        53,1cm x 29,9cm  (60,9cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3912 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  112449 Mb
    Largest Free Hard Disk Block:  74299 Mb

**Comment by kisak-valve** [comment]
Hello @kiwec, if you're still experiencing this issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/issues) issue tracker.

Closing as general video driver performance from 2014 is no longer relevant.
