### ISSUE TITLE
Counter Strike: Global Offensive overlay problem  

### ISSUE THREAD

**Issue by grottjam** [ValveSoftware/steam-for-linux#3388]
First of all, you are in a lobby and you are not the leader of the lobby. You open up your inventory and you starts to preview a weapon that you currently have.

Problem: When the lobby leader exits the lobby you will receive a pop up window under the "previewing a weapon" screen. The lobby pop up is (a head pop up witch means it needs to be closed down before anything else) blocking everything else and you need to close that one down before you can click anything else down but when the "preview a weapon" pop up is over the "close cross" you can´t close it down or even shut down the game. Witch means you have to close it down with "task manager" or simply make it crash.

**Comment by kisak-valve** [comment]
Hello @grottjam, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If you're still experiencing this issue with an up to date system, please open a new issue report in the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux) issue tracker.
