### ISSUE TITLE
xcom: some objects are not rendered (while other are ok)

### ISSUE THREAD

**Issue by pva** [ValveSoftware/steam-for-linux#3396]
Hello. I've successfuly installed steam on Gentoo linux, mananged to start it, download xcom and start the game. It launches successfuly, but some objects are not renedered. For example, take a look at screenshots: shield is supposed to be renedered there, but no shiled is visible or inside "circle" earth is supposed to be visible and mans are not supposed to be green. Is this known problem, what can we do about this?

If this is wrong place to ask such questions, please, point me to correct location.

Thanks for your time. 
![2014-07-07 10 25 58](https://cloud.githubusercontent.com/assets/92356/3492354/4d44f800-05a8-11e4-8ac8-c33497e2aaa0.png)
![imag0144](https://cloud.githubusercontent.com/assets/92356/3492357/583ef86e-05a8-11e4-9d8c-fd7f8f0db282.jpg)

**Comment by kisak-valve** [comment]
Hello @pva, are you still experiencing this issue on an up to date system? This looks like it may have been missing s3tc support with Mesa.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
