### ISSUE TITLE
Long ongoing issue with Connection Error dialog

### ISSUE THREAD

**Issue by fourzerofour** [ValveSoftware/steam-for-linux#3398]
So occasionally for some unknown reason, I get prompted with this dialog on connecting to Steam when my connection to internet is perfectly fine.

http://i.imgur.com/9m6sqQj.png

That's problem number 1.

Problem number 2 is if I click Retry Connection, it wants me to re-enter my password when it was already saved by Steam before.

http://i.imgur.com/rfVt7x3.png

And problem number 3 is if I click Quit, instead of immediately quit, it retries connecting to Steam server (now without asking to re-enter password) and when Steam is fully running and ready to use, only then it quits.

So there're 3 problems..

**Comment by anonymau5** [comment]
Issue number two has existed on the Windows client for years now.  The current solution I've found is to force quite the application and relaunch.  I've found this solution works on both Windows and Linux.  I have not tested this on OSX though but assume it will exhibit the same flaw.
