### ISSUE TITLE
Some of games are black when using steam beta version.

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#3399]
When im using latest beta version in Steam. All my games not working. Games are only black screen. 

my hardware specs https://gist.github.com/lahtis/8935236

**Comment by kisak-valve** [comment]
Hello @lahtis, are you still experiencing this issue on an up to date system?

**Comment by lahtis** [comment]
fixed, can be close.

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
