### ISSUE TITLE
Steam games audio fails when JACK Server is being used

### ISSUE THREAD

**Issue by thndgonz** [ValveSoftware/steam-for-linux#3400]
There's this ongoing problem with Steam current environment that for some reason steam (Linux) games fail to open audio. I thought it was just a misconfiguration on my part, perhaps. Sadly, I think this is an issue with Steam. I'll bring an example, (I can bring two more if needed) 

Super Hexagon, which is the fastest game to launch. 

Launching it on Steam: http://pastebin.com/NzzpDr5h

This is a version I got from GOG. http://pastebin.com/yediRif8 (despite the failure to find pulse, audio works, you can see it by the call it did to jack_client_new which has been renamed to jack_client_open)

Image on qjackctl, I renamed the client for the sake of clarity: https://dl.dropboxusercontent.com/u/37705/2014-07-11-11%3A23%3A12-screenshot.png

This is my asoundrc which Steam somehow fails to work with: 

pcm.!default {
    type plug
    slave { pcm "jack" }
}

pcm.jack {
    type jack
    playback_ports {
        0 system:playback_1
        1 system:playback_2
    }
    capture_ports {
        0 system:capture_1
        1 system:capture_2
    }

```
hint {
  show on
  description "JACK Audio Connection Kit Server"
}
```

}

ctl.mixer0 {
    type hw
    card 1
}

I've also tested Guacamelee, Monaco and Edge and they work fine outside the Steam environment.

**Comment by Brottweiler** [comment]
Just found this issue, and I want to add my input.

I recently installed **Binding of Isaac: Rebirth** and Don't Starve. When I installed Binding of Isaac, I had no sound. I did what was described [here](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#No_sound_2) to get it to work. (The Binding of Isaac section didn't exist, I added it).

Later, I installed **Don't Starve**, and the same thing there. I had no sound. I did what was [described on the archlinux wiki again](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#No_sound_2) but this time that didn't work. I did what else was described in that section, such as installing `lib32-alsa-plugins`, but still nothing.

I can't for the life of me get sound in Don't Starve. Here's some errors:

When starting Steam in a console, then starting Don't Starve, I get these errors:

```
Cannot read socket fd = 46 err = Success
Could not read result type = 22
Client name = rjack conflits with another running client
Cannot connect to the server
FMOD Error: Error initializing output device. 
SoundSystem::Initialize failed
cDontStarveGame::DoGameSpecificInitialize()
FMOD Error: An invalid object handle was used.
```
Then I get this error everytime I hover over a button, which should give a sound `FMOD Error: Can't play event dontstarve/HUD/click_mouseover: An invalid object handle was used.`.

Related threads (I made these, no reply):
- http://redd.it/2wokpo
- https://bbs.archlinux.org/viewtopic.php?id=193998

**Comment by krysanto** [comment]
Hello I know that this is an old thread but I think I've found the solution.
I couldn't start Darkest Dungeon after installing jack so i started it via terminal.

Turns out that it loaded the default device configured for pulseaudio. 
So what I did was change the **Input Devices** to **Jack source (PulseAudio JACK Source)**
and **Output Devices** to **Jack sink (PulseAudio JACK Sink)** via pavucontrol.

Darkest Dungeon loaded fine after that. I've tested out Binding of Isaac and it works too.

**Comment by prikhi** [comment]
As someone that doesn't want to run pulseaudio, I had resorted to killing/starting JACK & swapping `.asoundrc` files before/after playing games.

I was finally able to get all my games working with JACK by switching away from the alsa-jack plugin, and using a loopback device instead:
 http://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge

If you're running JACK via Cadence, you can just switch the ALSA Bridge to `ALSA -> Loop -> JACK`.

**Comment by kisak-valve** [comment]
Hello @thndgonz, @edward81, are either of you still experiencing the original issue in this issue report?

The current steam client should be preferring system libraries over the steam runtime if the system libraries are newer than the steam runtime variants.

**Comment by thndgonz** [comment]
@kisak-valve Can't confirm. I'm no longer using linux, hopefully edward still is.

**Comment by kisak-valve** [comment]
Thanks, closing pending feedback from @edward81.
