### ISSUE TITLE
Steam crashes during install

### ISSUE THREAD

**Issue by nickles0n** [ValveSoftware/steam-for-linux#3405]
After I run the .deb, and install the missing programs, I get this when running steam in the terminal. I've looked online for similar issues, but the only issue that is close #1075 was patched a long time ago.

Here's the terminal:
nsa@nsa-K55N:~$ steam
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140714174906_1.dmp
/home/nsa/.local/share/Steam/steam.sh: line 755: 13089 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
mv: cannot stat ‘/home/nsa/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/nsa/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-c2d4de7d-be65-42ce-8846-d2c322140714
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/nsa/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140714174909_1.dmp
/home/nsa/.local/share/Steam/steam.sh: line 755: 13217 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$PLATFORM/$STEAMEXE" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-0017704a-a1e2-484f-be87-6f8842140714

Thank you for your time.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
