### ISSUE TITLE
Some games and Steam crash in offline mode when network is down

### ISSUE THREAD

**Issue by RGamma** [ValveSoftware/steam-for-linux#3408]
When trying to run certain games in Steam's offline mode when the network is down, they and/or Steam may hang or crash.

This is a similar issue to https://github.com/ValveSoftware/steam-for-linux/issues/2295 with some more data (logs) and more examples.

Games I tested (crash = Steam and game crash; hang = game hangs and needs to be killed, Steam crashes in the process):
- Antichamber (crash)
- Duke Nukem 3D: Megaton Edition (hang)
- Dust: An Elysian Tail (pass)
- Reus (pass)
- Rogue Legacy (pass)
- System Shock 2 (pass)
- To the Moon (pass)
- XCOM: Enemy Unknown (crash)

Note, that for the error to occur, the network must be down, i.e. it doesn't occur when you have an internet connection while testing.
Also, when running Steam under strace (try e.g. strace -f -e trace=network steam) I couldn't reproduce the issue as detailed below, but the game doesn't start either.

Example (XCOM: Enemy Unknown):
Test 1 (internet connection on):
1. Start Steam in offline mode
2. Start game
=> Success
Log produced: http://bpaste.net/show/485400/

Test 2 (internet connection off (here I achieve this by doing "/etc/init.d/wpa_supplicant stop", your distribution may require you to do something else, taking down the interface using ifconfig or ip should work)):
1. Start Steam in offline mode
2. Start game
=> Steam crashes, the XCOM splashscreen lingers around for a bit, then the game crashes too
Log produced: http://bpaste.net/show/485398/
Note: Unfortunately it doesn't tell what hostname it's trying to resolve.

System info: http://bpaste.net/show/485403/

P.S.: It's a shame you can't attach files here, I can make some dumps from /tmp/dumps available when needed.

**Comment by kisak-valve** [comment]
Hello @RGamma, are you still experiencing this issue on an up to date system?

You can put minidumps in an archive and drag and drop them into the comment box if it is.

**Comment by RGamma** [comment]
Oh wow, it's been 4 years already... Totally forgot this was an issue.

I use a new distro (up-to-date Arch Linux) now and did a quick test with Antichamber, which used to crash. With network down and  Steam in offline mode it starts without issue now. AFAICT this is fixed.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
