### ISSUE TITLE
TF2 Trading cards non stop

### ISSUE THREAD

**Issue by Covalent-Bonds** [ValveSoftware/steam-for-linux#3411]
Basically, i get tf2 trading cards even though it says i only have one more card drop.

Reproducing this, i have no idea. All that happens is that i get in tf2, and get 3 or 4 trading card drops with having 1 drop remaining

**Comment by kisak-valve** [comment]
Hello @Covalent-Bonds, are you still experiencing this issue on an up to date system?

**Comment by Covalent-Bonds** [comment]
I actually do not know because since then I've stopped playing team
fortress 2, you guys probably updated and fixed the issue, its just that
when trading cards first came out around that time is when the problem
happened. It happened for just a select few other games that didn't really
have anything to do with tf2 as it was some random indie game I have since
forgot. I am quite sure you guys have fixed it though as other games with
trading cards it doesn't seem to give me non stop trading cards

**Comment by kisak-valve** [comment]
Closing per the last comment.
