### ISSUE TITLE
Games don't auto update

### ISSUE THREAD

**Issue by gwarokk** [ValveSoftware/steam-for-linux#3419]
games used to auto update fine until the last steam update, now i have to manually update them. If I restart steam it will update a couple of games, then stop. they just say "update queued", even when there is nothing downloading. This has not happened in the past...why now??

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date client?

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago.
