### ISSUE TITLE
Steam causes screen rendering error

### ISSUE THREAD

**Issue by hrzhu** [ValveSoftware/steam-for-linux#3423]
Sometimes Steam causes screen rendering error. Part of my screen get overlayed. This usually happens when I alt-tab switch between game and desktop apps. Restarting Steam solves the problem.

My DE is xfce and my whole sys info:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  3003 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.4 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-49-generic-pae
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.38
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1284
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 13.27" x 10.63"  (16.97" diag)
                                        33.7cm x 27.0cm  (43.1cm diag)
Primary Bus: PCI Express 8x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC662 rev1

Memory:
    RAM:  4030 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  150456 Mb
    Largest Free Hard Disk Block:  4138 Mb

**Comment by kisak-valve** [comment]
Hello @hrzhu, are you still experiencing this issue on an up to date system?

**Comment by hrzhu** [comment]
No, I'm not experiencing the issue on latest OS/Steam. I think this issue can be closed.
