### ISSUE TITLE
[beta] waking from hibernation makes steam window dissappear.

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#3425]
When i wake up from hibernation my steam window doesnt want to render. Its there on the taskbar and icon tray. But the window doesnt want to draw whatever i do. Restarting steam "fixes" the issue.

[quote]Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11599903
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-07-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 343.13
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1184
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                        47.7cm x 26.8cm  (54.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  32079 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_IN.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  300321 Mb
    Largest Free Hard Disk Block:  273374 Mb

Installed software:

Recent Failure Reports:
    Sun Aug 10 18:40:29 2014 GMT: file ''/tmp/dumps/crash_20140810204022_4.dmp'', upload yes: ''CrashID=bp-6911bf44-28fb-42c9-8f96-818042140810''[/quote]

**Comment by volca02** [comment]
I do not have this issue now on latest steam beta. The window redraws fine after suspend-resume. From my point of view this seems fixed.

**Comment by kisak-valve** [comment]
Hello @cjwijtmans, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as this appears to be a system or driver issue.
