### ISSUE TITLE
Optimus and Nouveau driver 

### ISSUE THREAD

**Issue by stevenwalton** [ValveSoftware/steam-for-linux#3428]
When trying to run steam through Optimus I get an error that it is not running directly and then steam fails to load.  As seen in the attached picture.  I have also included the bash output up to the interrupt.  I have tested Optimus with other programs and it runs without a hitch.  The only problem I run into is with Steam.  Is there a way I can modify Steam so that it does not crash when running Optimus?

Steam runs fine without the Optimus command but does not seem to be running off of my graphics card.  In fact, it even runs well through wine (with few exceptions on some games).  

https://i.imgur.com/9viRH2c.jpg
http://pastebin.com/v3UNyf99 (30 days to expire)
[steven@Serenity ~]$ uname -srmo
Linux 3.15.8-1-ARCH x86_64 GNU/Linux
HP Envy 15t-j000 Quad Edition

**Comment by kisak-valve** [comment]
Hello @stevenwalton, a lot has changed with the steam client since this issue report and if you're still experiencing this issue with an up to date system, we'll need to do a fresh investigation. Closing.
