### ISSUE TITLE
Steam Overlay causes massive fps drops when appearing

### ISSUE THREAD

**Issue by bgulowaty** [ValveSoftware/steam-for-linux#3429]
Specs:
Fedora 20 x64 + nvidia drivers (http://www.if-not-true-then-false.com/2014/fedora-20-nvidia-guide/)
Gnome3
GF 560 TI
i5 2500k

Reproduce - play ANY game (not only steam, league of legends for example), wait until someone writes to you or just steam overlay appears for some reason = FPS DROP (less than 30).

Same happens to the beta release of steam (with the new look).

**Comment by LethalManBoob** [comment]
10 years later. same issue.

**Comment by wem1c** [comment]
Very disheartening finding this conversation 10 years later. Very different OS (Arch [Garuda] - KDE - Wayland), but same issue.
