### ISSUE TITLE
32 bit support dropped in current linux kernel; transition should be made within 1 year.

### ISSUE THREAD

**Issue by anadon** [ValveSoftware/steam-for-linux#343]
https://git.kernel.org/?p=linux/kernel/git/torvalds/linux.git;a=commit;h=743aa456c1834f76982af44e8b71d1a0b2a82e21

i586 support is older, so assume that would be going as well.  Also, when configuring 3.8rc1 and linux-next I'm not seeing any options for 32-bit support.

Given this, you can expect ubuntu to likely have a kernel which drops 32 bit support in late April, and a guarantee for late October.  Most large and easy linux distro's will follow a similar timeline.  Faster moving distro's, like arch and gentoo, will have it within 1.5 months.

This should be a matter of a simple recompile and a few bug fixes, but get on this!

**Comment by bigdaddymccarron** [comment]
When will Valve make us a 64 bit steamcmd for gods sake?
