### ISSUE TITLE
[Linux] Team Fortress 2 Fullscreen Window Does Not Disable Hot Corners

### ISSUE THREAD

**Issue by Saroufim** [ValveSoftware/steam-for-linux#3431]
Team Fortress 2's window is still subjective to hot corners (tested under Compiz, Kwin, and Gala). Hovering the mouse to an edge of the screen would trigger the associated hot corner function. If the "spread" hot corner is triggered, Team Fortress 2 would get minimized automatically and wouldn't appear in docks (such as Plank). Sometimes, it doesn't appear in window switchers as well, making it nearly impossible to retrieve the window again. Other windows such as DotA2 do not seem to have any of these problems. They neither trigger hot corners or get minimized.

**Comment by kisak-valve** [comment]
Hello @Saroufim, are you still experiencing this issue on an up to date system?

**Comment by Saroufim** [comment]
I tried it again and the issue seems to be gone from GNOME on XWayland and on Xorg.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
