### ISSUE TITLE
Steam overlay is not working on my Ubuntu 14.04

### ISSUE THREAD

**Issue by AlexKibo88** [ValveSoftware/steam-for-linux#3433]
I checked and unchecked the related checkbox many times from my client "Properties" menu, restarted the client several times, but nothing changed... the overlay won't show up!
I read there's a file to delete from the source folders (libxcb.so.1) and tried to eliminate that, but nothing happened.
I have Catalyst drivers installed and recently updated them to the latest version. My video card is an ATI Radeon HD 7770 and its driver are up-to-date.

Could you please help me with this issue I'm having?

**Comment by kisak-valve** [comment]
Hello @AlexKibo88, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
