### ISSUE TITLE
Steam freezes when opening "library" tab

### ISSUE THREAD

**Issue by dawwin** [ValveSoftware/steam-for-linux#3434]
Steam freezes always when i pick "Library" tab. The problem appeared for the first time when I bought Leadwerks Game Engine. Before last steam update it only occurred when I picked "Software" tab but it now appears in the entire "Library" tab. The last thing I can see in console before freeze is 

> Installing breakpad exception handler for appid(steam)/version(1407966480)

but it's probably not related. 
I had noticed that steam uses entire processor core when it's freezed:
![image](https://cloud.githubusercontent.com/assets/6729869/3926790/cba149be-23f4-11e4-81b2-7f28efcac44e.png)

It is really annoying bug because now I can run games only in big picture mode.
The problem occurs in both versions: stable and beta.

My system specification:

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x3a
>     CPU Stepping:  0x9
>     CPU Type:  0x0
>     Speed:  2501 Mhz
>     4 logical processors
>     2 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     Ubuntu 13.10 (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  3.11.0-15-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11406000
>     X Window Manager:  Compiz
>     Steam Runtime Version:  steam-runtime-release_2014-07-22
> 
> Video Card:
>     Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
> 
> ```
> Driver Version:  3.0 Mesa 10.3.0-devel
> OpenGL Version: 3.0
> Desktop Color Depth: 24 bits per pixel
> Monitor Refresh Rate: 60 Hz
> VendorID:  0x8086
> DeviceID:  0x166
> Number of Monitors:  2
> Number of Logical Video Cards:  1
> Primary Display Resolution:  1600 x 900
> Desktop Resolution: 2880 x 1024
> Primary Display Size: 15,04" x 8,46"  (17,24" diag)
>                                         38,2cm x 21,5cm  (43,8cm diag)
> Primary VRAM Not Detected
> ```
> 
> Sound card:
>     Audio device: Intel PantherPoint HDMI
> 
> Memory:
>     RAM:  7852 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  42579 Mb
>     Largest Free Hard Disk Block:  20195 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

**Comment by kisak-valve** [comment]
Closing per the last comment.
