### ISSUE TITLE
dota 2 game window closes after loading

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3435]
Hi,

Please advice on this issue. When start to play dota from steam client, the game window suddenly closes after the logo VALVE logo display. Bellow are the logs:

kickr@magelan:~$ uname -a
Linux magelan 3.2.0-4-686-pae #1 SMP Debian 3.2.60-1+deb7u1 i686 GNU/Linux

kickr@magelan:~$ steam-debian 
Running Steam on debian 7 32-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1407966480_client)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steamwebhelper)/version(20140813141634)
Installing breakpad exception handler for appid(steamwebhelper)/version(1407939394)
Installing breakpad exception handler for appid(steamwebhelper)/version(20140813141634)
Installing breakpad exception handler for appid(steamwebhelper)/version(1407939394)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",

(steam:7668): Gtk-WARNING **: Unable to locate theme engine in module_path: "xfce",
Installing breakpad exception handler for appid(steam)/version(1407966480)
Installing breakpad exception handler for appid(steam)/version(1407966480)
Adding licenses for the following package(s): 0, 6254, 12205, 13855, 47618, 48323, 48324, 48325, 49074, 49084, 49086, 49447
roaming config store loaded successfully - 1069 bytes.
migrating temporary roaming config store
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
[0815/070651:ERROR:browser_main_loop.cc(218)] GTK theme error: Unable to locate theme engine in module_path: "xfce",
Installing breakpad exception handler for appid(steam)/version(1407966480)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/kickr/.local/share/Steam/ubuntu12_32/steam" "
System startup time: 6.28 seconds
Generating new string page texture 68: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 69: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 70: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 71: 32x256, total string texture memory is 540.67 KB
Running Steam on debian 7 32-bit
STEAM_RUNTIME has been set by the user to: /home/kickr/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/kickr/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Installing breakpad exception handler for appid(steam)/version(1407966480)
[0815/070652:ERROR:renderer_main.cc(227)] Running without renderer sandbox
Installing breakpad exception handler for appid(steam)/version(1407966480)
Generating new string page texture 137: 128x256, total string texture memory is 671.74 KB
Generating new string page texture 138: 1024x256, total string texture memory is 1.72 MB
Generating new string page texture 139: 2048x256, total string texture memory is 3.82 MB
Generating new string page texture 140: 512x256, total string texture memory is 4.34 MB
Generating new string page texture 141: 128x256, total string texture memory is 4.47 MB
Generating new string page texture 142: 384x256, total string texture memory is 4.87 MB
Game update: AppID 570 "Dota 2", ProcID 7777, IP 0.0.0.0:0
ERROR: ld.so: object '/home/kickr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/kickr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 7780 != 7779, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/kickr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/kickr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Installing breakpad exception handler for appid(gameoverlayui)/version(20140813141643)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198022995641 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198022995641
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system DOES NOT support the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 1
Adding VPK file: /home/kickr/.local/share/Steam/SteamApps/common/dota 2 beta/dota/sound_vo_english
Adding VPK file: /home/kickr/.local/share/Steam/SteamApps/common/dota 2 beta/dota/pak01
Adding VPK file: /home/kickr/.local/share/Steam/SteamApps/common/dota 2 beta/platform/pak01
Did not detect any valid joysticks.
WARNING: unable to link Test_StartScript and Test_StartScript because one or more is a ConCommand.
WARNING: unable to link Test_RandomChance and Test_RandomChance because one or more is a ConCommand.
WARNING: unable to link Test_LoopForNumSeconds and Test_LoopForNumSeconds because one or more is a ConCommand.
WARNING: unable to link Test_Loop and Test_Loop because one or more is a ConCommand.
WARNING: unable to link Test_LoopCount and Test_LoopCount because one or more is a ConCommand.
WARNING: unable to link Test_StartLoop and Test_StartLoop because one or more is a ConCommand.
WARNING: unable to link log_flags and log_flags because one or more is a ConCommand.
WARNING: unable to link log_color and log_color because one or more is a ConCommand.
WARNING: unable to link log_verbosity and log_verbosity because one or more is a ConCommand.
WARNING: unable to link log_level and log_level because one or more is a ConCommand.
WARNING: unable to link log_dumpchannels and log_dumpchannels because one or more is a ConCommand.
Load a scaleform font provider?
Creating D3D9 device with D3DCREATE_MULTITHREADED
IDirect3DDevice9::Create: BackBufWidth: 1440, BackBufHeight: 900, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED

 ##### swap interval = 1     swap limit = 1 #####
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred
ERROR: ld.so: object '/home/kickr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20140815070700_1.dmp
/home/kickr/.local/share/Steam/SteamApps/common/dota 2 beta/dota.sh: line 77:  7782 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 7782 
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-4184ba35-a0d6-4539-ae89-116a52140814
pid 7793 != 7792, skipping destruction (fork without exec?)

**Comment by kisak-valve** [comment]
Closing as the user has turned into a ghost.
