### ISSUE TITLE
LINUX L4D2 crash in "The Sacrifice"

### ISSUE THREAD

**Issue by microcai** [ValveSoftware/steam-for-linux#3439]
Hello, I'm having a crash at the end of loading "The Sacrifice" map. 

but minidump can't be uploaded

Finished uploading minidump (out-of-process): success = no
error: Couldn't connect to server

**Comment by kisak-valve** [comment]
Hello @microcai, if you're still experiencing this issue on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.

Closing as this issue report is not actionable with the information provided.
