### ISSUE TITLE
Add support for multiple gamepads

### ISSUE THREAD

**Issue by CreamyCookie** [ValveSoftware/steam-for-linux#3441]
At the moment I can only configure one gamepad when both are plugged in. Also it seems that this configuration gets removed now and then (different USB port?).

**Comment by kisak-valve** [comment]
Hello @CreamyCookie, are you still experiencing this behavior on an up to date system?

**Comment by CreamyCookie** [comment]
@kisak-valve Thanks for asking. No, I haven't experienced this recently. (I hope it's okay that I closed it.)

Have a nice day! :)
