### ISSUE TITLE
libasound.so.2.0.0 old/buggy

### ISSUE THREAD

**Issue by DrMcCoy** [ValveSoftware/steam-for-linux#3443]
As per https://github.com/KillaW0lf04/The-Witcher-2-Issues/issues/45 , the libasound.so.2.0.0 provided by Steam seems to have a bug, crashing in snd_config_update_free_global(), triggered by a new-ish version of OpenAL-Soft.

Replacing Steam's libasound.so.2.0.0 with Debian Sid's (version 1.0.28 instead of 1.0.25) fixes the crash, and I guess an updated version out of a newer Ubuntu should do it as well.

**Comment by rip-off** [comment]
A similar issue was found investigating a startup crash in Double Fine's MASSIVE CHALICE (http://www.doublefine.com/forums/viewthread/16046/).

The crash was elsewhere "snd_config_iterator_next () from /home/user/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2", but the fix the same, I replaced the steam runtime version with the system provided library. The Ubuntu version that works appears to be 1.0.27.2-3ubuntu7.

**Comment by julien-f** [comment]
After some updates of my Debian (Stretch) my games (Big Pharma, Divinity: Original Sin) would not run anymore:

```
*** Error in `/home/julien/.steam/steam/steamapps/common/Big Pharma/Big Pharma.x86': free(): invalid pointer: 0x1c1c1c1c ***
======= Backtrace: =========
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x694e9)[0xf72aa4e9]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6f0b7)[0xf72b00b7]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(cfree+0x9a)[0xf72b3b8a]
/home/julien/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/libasound.so.2(snd_device_name_free_hint+0x33)[0xf0f4b6d3]
/home/julien/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/libasound.so.2(snd_device_name_hint+0x226)[0xf0f4b916]
```

Installing Debian libasound v1.1.0-1 (`apt install libasound:i386`) and removing libasound.so.2 and libasound.so.2.0.0, they started working again.

**Comment by IdleGandalf** [comment]
Can confirm this happening with Debian testing and multiple games (Cities Skylines, Dying Light and more) as well.

Removing the libasound lib from the steam-runtime solves this problem, like mentioned before.

**Comment by kisak-valve** [comment]
Hello, the default behavior of steam has changed so that it prefers host libraries if they are newer than those provided by the steam runtime. This issue should no longer be an problem on most systems.
