### ISSUE TITLE
Steam segfaults while just running in the background

### ISSUE THREAD

**Issue by CommanderAlchemy** [ValveSoftware/steam-for-linux#3446]
Seems that steam just segfaults lately. Noticed it few beta updates ago.
Last i could get from it, everything else in terminal log is libdbusmenu warnings.
http://codepad.org/KkRFiDz7

Steam systeminfo: (steam just updated when i updated the gist)
https://gist.github.com/CommanderAlchemy/83c70f2deffb678192c3

All steam was doing was being in the background.

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2014 is no longer relevant.
