### ISSUE TITLE
Messages sent while the other person is offline, are never actually "delivered"

### ISSUE THREAD

**Issue by CreamyCookie** [ValveSoftware/steam-for-linux#3448]
I wrote and send a message while a friend was offline. When he came online, I asked him over VoIP (because he didn't answer) if he did get a message on Steam. He didn't.

Ubuntu 14.04 LTS / 64bit

**Comment by kisak-valve** [comment]
Hello @CreamyCookie, have you seen this issue since the initial report?

**Comment by CreamyCookie** [comment]
No, I haven't seen this again, but I also haven't tried this recently. (Writing someone who's offline.) I guess it can be closed if nobody has had this issue again recently.

**Comment by kisak-valve** [comment]
Closing pending feedback.
