### ISSUE TITLE
Feature request: Browse by category AND by platform

### ISSUE THREAD

**Issue by KennethNielsen** [ValveSoftware/steam-for-linux#3449]
The browse by category function (which I would otherwise very much like to use) is not very helpful when using a minority platform like Linux, because it will show a bunch a results that I cannot play.

It would be nice, if it was possibly to browse by both parameters.

If that is possible by some other means I apologize for the noise.

**Comment by kisak-valve** [comment]
Hello @KennethNielsen, please go to `Steam` -> `Settings` -> `View Account Details` -> `Preferences` -> `Platform Preferences` and select the OSes that interest you. After that, does browsing the storefront behave as expected for you?

**Comment by kisak-valve** [comment]
Closing as this should have been implemented some time ago.
