### ISSUE TITLE
Steam segfaults when networkmanager 0.9.10.0 and steam_runtime=0

### ISSUE THREAD

**Issue by CommanderAlchemy** [ValveSoftware/steam-for-linux#3457]
So it seems that steam fails to launch when having lib32-networkmanager 0.9.10.0 installed when launching with steam_runtime=0

Downgrading back to 0.9.8.10 fixes the issue.

lib32-networkmanager 0.9.8
https://gist.github.com/CommanderAlchemy/25e02dccd9e06676ad0e

lib32-networkmanager 0.9.10
https://gist.github.com/CommanderAlchemy/862ce6bae3349ce32396

Steam system info:
https://gist.github.com/CommanderAlchemy/83c70f2deffb678192c3

**Comment by kisak-valve** [comment]
Hello @CommanderAlchemy, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
