### ISSUE TITLE
Steam insists on configuring network settings

### ISSUE THREAD

**Issue by jimmyvh** [ValveSoftware/steam-for-linux#3460]
/client/steam_client_ubuntu12 version 1407966480 . Running this on XBMCbuntu Trusty and launching straight to BPM.

Since the latest beta update, Steam BPM starts with a configuration wizard and insists on configuring network settings
However, I already had fully functional network settings configured on OS level: This is confirmed by the fact that steam did manage to detect and download the latest update. It's AFTER the update that stuff went wrong.
Tried to re-enter the same network settings as my OS within Steam and then run the network test: This didn't work as it keeps trying to connect forever and there is no way to skip this network configuration menu. As a result it's impossible to use Steam.
Outside of steam my network connection is fine.

**Comment by kisak-valve** [comment]
Hello, is anyone seeing this issue with an up to date system?

**Comment by sid3windr** [comment]
Switched to Steam link so cannot currently provide useful comment...

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing.
