### ISSUE TITLE
After the last update сan not print on Russian in Steam

### ISSUE THREAD

**Issue by Manazius** [ValveSoftware/steam-for-linux#3461]
After the last update сan not print in Russian on Steam. Update: 28.08.2014
OS: Arch Linux
Video: http://www.youtube.com/watch?v=UAz8H4Bbpys
Please fix it.
The same problem with Ubuntu 12.04
UPD: On Russian language it is impossible to write only in the community. In a private message on Russian language writes.

**Comment by kisak-valve** [comment]
Hello @Manazius, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
