### ISSUE TITLE
steam processes defunct, child of pid 1, on debian

### ISSUE THREAD

**Issue by bjmgeek** [ValveSoftware/steam-for-linux#3462]
I started steam on debian sid.  It updated, then I got an icon in the system tray, but nothing else happened.

The console showed 
    `Requested Force create but SharedObjectMutex already created`
    `Forced create but already created for SharedObjectEvent`

I tried to kill the process but it didn't work.  I got some unkillable defunct processes that were the child of PID 1 (init; in my case systemd)

```
bminton@bminton:~/.steam$ ps auxf
[...]
bminton   2489  0.1  0.9 227572 72360 pts/9    Dl   Aug28   0:57 /home/bminton/.steam/ubuntu12_32/steam
bminton   2494  0.0  0.0      0     0 pts/9    Z    Aug28   0:00  \_ [steam] <defunct>
bminton   2887  0.0  0.0      0     0 pts/9    Z    Aug28   0:00  \_ [steam] <defunct>
[...]
bminton@bminton:~/.steam$ ps axo stat,euid,ruid,tty,tpgid,sess,pgrp,ppid,pid,pcpu,comm|grep steam
Dl    1000  1000 pts/9     2399  3790  2402     1  2489  0.1 steam
Z     1000  1000 pts/9     2399  3790  2402  2489  2494  0.0 steam <defunct>
Z     1000  1000 pts/9     2399  3790  2402  2489  2887  0.0 steam <defunct>
bminton@bminton:~/.steam$ dpkg -l steam
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
++-===========================-==================-==================-===========================================================
ii  steam                       1.0.0.48-2         i386               Valve's Steam digital software delivery system
bminton@bminton:~/.steam$ uname -a
Linux bminton.is-a-geek.net 3.14-1-amd64 #1 SMP Debian 3.14.12-1 (2014-07-11) x86_64 GNU/Linux
bminton@bminton:~/.steam$ kill -9 2489
bminton@bminton:~/.steam$ ps 2489
  PID TTY      STAT   TIME COMMAND
 2489 pts/9    Dl     0:57 /home/bminton/.steam/ubuntu12_32/steam
```

-- System Information:
Debian Release: jessie/sid
  APT prefers unstable
  APT policy: (500, 'unstable'), (500, 'stable'), (500, 'oldstable')
Architecture: i386 (x86_64)
Foreign Architectures: amd64

Kernel: Linux 3.14-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=C, LC_CTYPE=C (charmap=ANSI_X3.4-1968)
Shell: /bin/sh linked to /bin/bash

Versions of packages steam depends on:
ii  debconf [debconf-2.0]                 1.5.53
ii  eterm [x-terminal-emulator]           0.9.6-1
ii  gnome-terminal [x-terminal-emulator]  3.12.3-2
ii  konsole [x-terminal-emulator]         4:4.14.0-1
ii  libc6                                 2.19-10
ii  libgl1-mesa-dri                       10.2.6-1
ii  libgl1-mesa-glx                       10.2.6-1
ii  libstdc++6                            4.9.1-9
ii  libtxc-dxtn-s2tc0 [libtxc-dxtn0]      0~git20131104-1.1
ii  libudev1                              208-8
ii  libx11-6                              2:1.6.2-3
ii  libxinerama1                          2:1.1.3-1
ii  mrxvt [x-terminal-emulator]           0.5.4-1.1
ii  multiarch-support                     2.19-10
ii  pterm [x-terminal-emulator]           0.63-7
ii  xfce4-terminal [x-terminal-emulator]  0.6.3-1
ii  xterm [x-terminal-emulator]           308-1
ii  xz-utils                              5.1.1alpha+20120614-2

Versions of packages steam recommends:
ii  fonts-liberation  1.07.4-1
ii  zenity            3.12.1-1.1

steam suggests no packages.

-- debconf information:
- steam/question: I AGREE
- steam/license:
  steam/purge:

**Comment by kisak-valve** [comment]
Hello @bjmgeek, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
