### ISSUE TITLE
[Linux Mint 17] graphics error

### ISSUE THREAD

**Issue by mattispasch** [ValveSoftware/steam-for-linux#3466]
Hey,
I'm on a fresh install on linux mint 17 (Qiana) - 64Bit Cinnamon and installed all updates.
My Graphics card is an Intel HD 4000.

In Counter-Strike:Source I have graphic problems: Dialogs are missing the edges, the background image in the menu is black and maps are completely black or at least very dark.

After a lot of searching I've found the solution: install the package "libtxc-dxtn-s2tc0:i386".

Unfortunately there is no useful output in the logs which makes it easy to find this solution, so please either install it together with CS:S or at least output something in the case its missing.

Thank you, Mattis

**Comment by toaster** [comment]
Hi, I have the same issue on Gentoo.
Is there something I can do about it?

**Comment by Tele42** [comment]
@toaster On gentoo, the VIDEO_CARDS="intel / nouveau / radeon" useflag on games-util/steam-games-meta pulls this dependency for you. Please stop into #steamlug or #gentoo-gamerlay on freenode irc if you need additional help.

**Comment by toaster** [comment]
@Tele42 Thanks for the help. The s3tc useflag was not included since I did not have the steamgames_source_engine useflag set.
Now everything works.
