### ISSUE TITLE
Please help me about the ip address info

### ISSUE THREAD

**Issue by acgotaku** [ValveSoftware/steam-for-linux#3468]
My network can't login Steam.
I use wireshark network analysis.
I find can not tcp query from 208.64.200.137.
what is the ip address correspond domain ?
Please help me . Thank you.
![2014-08-31-140548_1014x492_scrot](https://cloud.githubusercontent.com/assets/1191834/4101223/9364e824-30da-11e4-8139-f23ecfe4f8d2.png)

**Comment by kisak-valve** [comment]
Hello @acgotaku, if you are still having trouble connecting to steam's servers with an up to date system, please open a new issue report.
