### ISSUE TITLE
Add support for exiting to main window/terminate current load screen via escape key.

### ISSUE THREAD

**Issue by anadon** [ValveSoftware/steam-for-linux#347]
Just as general convention, the escape key should be supported for a "back" feature, and to terminate the current load screen.  Add this and a confirm dialog please.

**Comment by kisak-valve** [comment]
Closing as the Steam client does not have any cancel-able load screens. Feel free to make this request on a per-game basis, as there is no unified input system mandated by Steam. Signaling for a window to close by other hotkeys such as alt-F4 should be handled by the desktop environment, not Steam.
