### ISSUE TITLE
steam process uses 100% CPU

### ISSUE THREAD

**Issue by Tolianych** [ValveSoftware/steam-for-linux#3471]
My laptop HP Pavilion 17 e026sr:
AMD A4 5150M (2 x 2.7 HHz)
RAM 4 GB
AMD Radeon HD 8670M
AMD Radeon HD 8350G
Debian 7 wheezy 64 bit, XFCE

Steam uses one CPU core by ~100% permanently.

System information: https://gist.github.com/Tolianych/374a65a2d2edb7a5d31a
TOP: https://gist.github.com/Tolianych/97b34974026af614742f
PowerTop:
Summary: 136.6 wakeups/second,  0.0 GPU ops/second, 0.0 VFS ops/sec and 103.2% CPU use
                Usage       Events/s    Category       Description
            961.8 ms/s      23.2        Process        /home/tolianych/.local/share/Steam/ubuntu12_32/steam

**Comment by kisak-valve** [comment]
Hello @Tolianych, @Plaque-fcc, are either of you still experiencing this issue on an up to date system?

**Comment by Tolianych** [comment]
Hi! Sorry, I've commented earlier from another account, I installed Xubuntu 14.04 and problem was gone. Now I'm using another laptop with nvidia video and haven't any problems, but can't check on original hardware.

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing.
