### ISSUE TITLE
steamwebhelper seems to cause slowdowns and garbled up webviews after running for a while

### ISSUE THREAD

**Issue by Daverball** [ValveSoftware/steam-for-linux#3472]
After leaving steam running for a while the client starts responding slowly to page refreshes and changing lets say from the steam store front to your activity feed or the steam community front page.

Scrolling the page will result in a garbled page with some sections of the screen having scrolled properly while others haven't. Also after it starts to respond slowly it might show pages without the CSS stylesheet applied and/or with missing graphics.

![screen](https://cloud.githubusercontent.com/assets/5726519/4143058/46d81d5a-33c3-11e4-924f-e5ea8bf94ff6.png)

Force quitting the steamwebhelper processes solves these issues temporarily, as well as restarting the steam client.

This has started happening with today's steam client beta update.

I'm running openSUSE 13.1 x86_64 with KDE.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Daverball** [comment]
This specific issue is no longer happening on my system.

**Comment by mbtuchman** [comment]
Seems to have been fixed for me.

**Comment by kisak-valve** [comment]
Thanks for retesting @Daverball, @mbtuchman. Closing.
