### ISSUE TITLE
Steam UI crashes when mouse over the STORE/LIBRARY/COMMUNITY/USER bar -WINDOWS

### ISSUE THREAD

**Issue by Spiral90210** [ValveSoftware/steam-for-linux#3475]
Apologies for posting this in linux, I followed a link here and didn't realise. Can this be moved?

When I launch the ui (loading into library view), I can launch games ok, but when I move my mouse over the top area of the window (STORE/LIBRARY/COMMUNITY/USER area), the application stops responding (consistently). This only started happening sometime within the past 2 weeks, although I don't use steam often enough for that to be an accurate indication of when the bug was introduced. If I move the mouse onto steam from the top, I can still access the menu (I used that to get to the tool to generate system information).

I had a quick look for log files and found a debug.log in the root steam install folder. Clearing out and reproducing the error yields 1 line: 

[0907/135508:ERROR:renderer_main.cc(227)] Running without renderer sandbox

following sections
==WINLOG==
==SYSINFO==

==WINLOG==
Windows event log is not very helpful: -

` <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Hang" /> 
  <EventID Qualifiers="0">1002</EventID> 
  <Level>2</Level> 
  <Task>101</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2014-09-07T12:44:15.000000000Z" /> 
  <EventRecordID>13384</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DAISY</Computer> 
  
  <Security /> 
  </System>
- <EventData>
  <Data>Steam.exe</Data> 
  <Data>2.37.82.33</Data> 
  <Data>1444</Data> 
  <Data>01cfca994363a3e2</Data> 
  <Data>7</Data> 
  <Data>C:\Program Files (x86)\Steam\Steam.exe</Data> 
  <Data>ab1499de-368c-11e4-8285-8c89a52ffe4c</Data> 
  <Data /> 
  <Data /> 
  <Binary>55006E006B006E006F0077006E0000000000</Binary> 
  </EventData>
  </Event>`

==SYSINFO==
`
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3293 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 8.1 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  AMD Radeon HD 5800 Series

```
DirectX Driver Name:  aticfx32.dll
Driver Version:  13.251.0.0
DirectX Driver Version:  8.17.10.1247
Driver Date: 6 Dec 2013
OpenGL Version: 4.3
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
DirectX Card: AMD Radeon HD 5800 Series
VendorID:  0x1002
DeviceID:  0x6899
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary Bus Type Not Detected
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Speakers (ASUS Xonar DS Audio D

Memory:
    RAM:  8160 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  3099582 Mb
    Largest Free Hard Disk Block:  2176002 Mb
    OS Install Date: Jan 01 1970
    Game Controller: Generic   USB  Joystick   detected

Installed software:
     Tools for .Net 3.5
    7-Zip 9.20 (x64 edition)
    Adobe AIR
    Adobe Community Help
    Adobe Photoshop CS5
    Age of Empires II: HD Edition
    AMD Accelerated Video Transcoding
    AMD Catalyst Install Manager
    Apple Application Support
    Apple Mobile Device Support
    Apple Software Update
    ASUS Xonar DS Audio
    AzureTools.Notifications
    Behaviors SDK (XAML) for Visual Studio
    Blend for Visual Studio 2013
    Blend for Visual Studio 2013 ENU resources
    Blend for Visual Studio SDK for .NET 4.5
    Blend for Visual Studio SDK for Silverlight 5
    Bonjour
    Brackets
    Build Tools - amd64
    Build Tools - x86
    Build Tools Language Resources - amd64
    Build Tools Language Resources - x86
    Canon IJ Network Scanner Selector EX
    Canon IJ Network Tool
    Canon IJ Scan Utility
    Canon MX450 series MP Drivers
    Canon MX450 series User Registration
    Catalyst Control Center InstallProxy
    CloudReading
    Counter-Strike: Global Offensive
    Dawn Of War
    Dawn of War - Dark Crusade
    Dawn Of War - Winter Assault
    Definition Update for Microsoft Office 2010 (KB982726) 64-Bit Edition
    Dotfuscator and Analytics Community Edition
    Entity Framework Tools for Visual Studio 2013
    Fallout: New Vegas
    Fiddler
    Fleet Operations version 3.2.7
    Foxit Reader
    Google Chrome
    Google Update Helper
    Half-Life
    Half-Life 2
    Half-Life 2: Episode One
    Half-Life 2: Episode Two
    IIS 8.0 Express
    IIS Express Application Compatibility Database for x64
    IIS Express Application Compatibility Database for x86
    Inkscape 0.48.5
    iTunes
    Java 7 Update 45
    Java 7 Update 45 (64-bit)
    Java Auto Updater
    JavaScript Tooling
    JetBrains ReSharper 8.0.2
    LocalESPC Dev12
    LocalESPCui for en-us Dev12
    Malwarebytes Anti-Malware version 1.75.0.1300
    Microsoft .NET Framework 4 Multi-Targeting Pack
    Microsoft .NET Framework 4.5 Multi-Targeting Pack
    Microsoft .NET Framework 4.5 SDK
    Microsoft .NET Framework 4.5.1 Multi-Targeting Pack
    Microsoft .NET Framework 4.5.1 Multi-Targeting Pack (ENU)
    Microsoft .NET Framework 4.5.1 RC Multi-Targeting Pack for Windows Store Apps
    Microsoft .NET Framework 4.5.1 RC Multi-Targeting Pack for Windows Store Apps (ENU)
    Microsoft .NET Framework 4.5.1 SDK
    Microsoft Advertising SDK for Windows 8.1 - ENU
    Microsoft Advertising Service Extension for Visual Studio
    Microsoft ASP.NET MVC 4 - Visual Studio 2013 - ENU
    Microsoft ASP.NET MVC 4 Runtime
    Microsoft ASP.NET Web Frameworks and Tools - Visual Studio 2013 - ENU
    Microsoft ASP.NET Web Pages 2 - Visual Studio 2013 - ENU
    Microsoft ASP.NET Web Pages 2 Runtime
    Microsoft C++ Azure Mobile SDK for Visual Studio 2013
    Microsoft C++ REST SDK for Visual Studio 2013
    Microsoft Exchange Web Services Managed API 2.0
    Microsoft Expression Blend SDK for .NET 4
    Microsoft Help Viewer 2.1
    Microsoft Identity Extensions
    Microsoft LightSwitch for Visual Studio 2013 Core
    Microsoft LightSwitch for Visual Studio 2013 CoreRes - ENU
    Microsoft LightSwitch for Visual Studio 2013 v4.0 Tools
    Microsoft LightSwitch for Visual Studio 2013 v4.0 ToolsRes - ENU
    Microsoft LightSwitch v4.0 SDK
    Microsoft NuGet - Visual Studio 2013
    Microsoft Office 2003 Web Components
    Microsoft Office 2013 Developer Tools for Microsoft Visual Studio (x64)
    Microsoft Office 2013 Developer Tools for Microsoft Visual Studio (x64) - ENU Language Pack
    Microsoft Office Access MUI (English) 2010
    Microsoft Office Access Setup Metadata MUI (English) 2010
    Microsoft Office Excel MUI (English) 2010
    Microsoft Office Groove MUI (English) 2010
    Microsoft Office InfoPath MUI (English) 2010
    Microsoft Office Office 32-bit Components 2010
    Microsoft Office OneNote MUI (English) 2010
    Microsoft Office Outlook MUI (English) 2010
    Microsoft Office PowerPoint MUI (English) 2010
    Microsoft Office Professional Plus 2010
    Microsoft Office Proof (English) 2010
    Microsoft Office Proof (French) 2010
    Microsoft Office Proof (Spanish) 2010
    Microsoft Office Proofing (English) 2010
    Microsoft Office Publisher MUI (English) 2010
    Microsoft Office Shared 32-bit MUI (English) 2010
    Microsoft Office Shared MUI (English) 2010
    Microsoft Office Shared Setup Metadata MUI (English) 2010
    Microsoft Office Word MUI (English) 2010
    Microsoft Portable Library Multi-Targeting Pack
    Microsoft Portable Library Multi-Targeting Pack Language Pack - enu
    Microsoft Report Viewer Add-On for Visual Studio 2013
    Microsoft SharePoint 2013 Developer Tools for Visual Studio
    Microsoft SharePoint 2013 Developer Tools for Visual Studio 2012 Nuget Package
    Microsoft SharePoint 2013 Developer Tools for Visual Studio ENU Language Pack
    Microsoft Silverlight
    Microsoft Silverlight 5 SDK
    Microsoft SQL Server 2012 Command Line Utilities 
    Microsoft SQL Server 2012 Data-Tier App Framework 
    Microsoft SQL Server 2012 Data-Tier App Framework  (x64)
    Microsoft SQL Server 2012 Express LocalDB 
    Microsoft SQL Server 2012 Management Objects 
    Microsoft SQL Server 2012 Management Objects  (x64)
    Microsoft SQL Server 2012 Native Client 
    Microsoft SQL Server 2012 T-SQL Language Service 
    Microsoft SQL Server 2012 Transact-SQL ScriptDom 
    Microsoft SQL Server Compact 4.0 SP1 x64 ENU
    Microsoft SQL Server Data Tools - enu (12.0.30919.1)
    Microsoft SQL Server Data Tools Build Utilities - enu (12.0.30919.1)
    Microsoft SQL Server System CLR Types
    Microsoft SQL Server System CLR Types (x64)
    Microsoft System CLR Types for SQL Server 2012
    Microsoft System CLR Types for SQL Server 2012 (x64)
    Microsoft Team Foundation Server 2013 Object Model (x64)
    Microsoft Team Foundation Server 2013 Object Model Language Pack (x64) - ENU
    Microsoft Visual Basic for Applications 7.1 (x64)
    Microsoft Visual Basic for Applications 7.1 (x64) English
    Microsoft Visual C++  ARM Libraries
    Microsoft Visual C++  x64 Libraries
    Microsoft Visual C++  x64 Native Compilers
    Microsoft Visual C++  x64 Native Compilers - ENU Resources
    Microsoft Visual C++  x64-arm Cross Compilers
    Microsoft Visual C++  x64-arm Cross Compilers - ENU Resources
    Microsoft Visual C++  x64-x86 Cross Compilers
    Microsoft Visual C++  x64-x86 Cross Compilers - ENU Resources
    Microsoft Visual C++  x86 Libraries
    Microsoft Visual C++ 2005 Redistributable
    Microsoft Visual C++ 2005 Redistributable (x64)
    Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148
    Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
    Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
    Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219
    Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
    Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.60610
    Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.60610
    Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.60610
    Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.60610
    Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.60610
    Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.60610
    Microsoft Visual C++ 2013  x64 Designtime - 12.0.21005
    Microsoft Visual C++ 2013 32bit Compilers - ENU Resources
    Microsoft Visual C++ 2013 Compilers
    Microsoft Visual C++ 2013 Compilers - ENU Resources
    Microsoft Visual C++ 2013 Core Libraries
    Microsoft Visual C++ 2013 Extended Libraries
    Microsoft Visual C++ 2013 Microsoft Foundation Class Libraries
    Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x64 Debug Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x86 Debug Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005
    Microsoft Visual C++ 2013 x86-x64 Compilers
    Microsoft Visual Studio 2005 Remote Debugger Light (x64) - ENU
    Microsoft Visual Studio 2010 Tools for Office Runtime (x64)
    Microsoft Visual Studio 2013 Devenv
    Microsoft Visual Studio 2013 Devenv Resources
    Microsoft Visual Studio 2013 Performance Collection Tools
    Microsoft Visual Studio 2013 Performance Collection Tools - ENU
    Microsoft Visual Studio 2013 Preparation
    Microsoft Visual Studio 2013 Profiling Tools
    Microsoft Visual Studio 2013 Shell (Minimum)
    Microsoft Visual Studio 2013 Shell (Minimum) Interop Assemblies
    Microsoft Visual Studio 2013 Shell (Minimum) Resources
    Microsoft Visual Studio 2013 Team Explorer Language Pack - ENU
    Microsoft Visual Studio 2013 VsGraphics Helper Dependencies
    Microsoft Visual Studio Professional 2013
    Microsoft Visual Studio Professional 2013 - ENU
    Microsoft Visual Studio Ultimate 2013 XAML UI Designer Core
    Microsoft Visual Studio Ultimate 2013 XAML UI Designer enu Resources
    Microsoft Web Deploy 3.5
    Microsoft Web Developer Tools 2013 - Visual Studio 2013
    Microsoft_VC80_ATL_x86_x64
    Microsoft_VC80_CRT_x86
    Microsoft_VC80_CRT_x86_x64
    Microsoft_VC80_MFCLOC_x86
    Microsoft_VC80_MFCLOC_x86_x64
    Microsoft_VC80_MFC_x86
    Microsoft_VC80_MFC_x86_x64
    Microsoft_VC90_ATL_x86
    Microsoft_VC90_ATL_x86_x64
    Microsoft_VC90_CRT_x86
    Microsoft_VC90_CRT_x86_x64
    Microsoft_VC90_MFC_x86
    Microsoft_VC90_MFC_x86_x64
    Mozilla Firefox 31.0 (x86 en-US)
    Mozilla Maintenance Service
    Notepad++
    Open XML SDK 2.5 for Microsoft Office
    OpenAL
    OpenRA
    Paint.NET v3.5.11
    PDF Settings CS5
    PreEmptive Analytics Visual Studio Components
    Prerequisites for SSDT 
    Python 2.7.3
    Python Tools Redirection Template
    Reason 4.0
    Sandboxie 4.08 (64-bit)
    Security Update for Microsoft Office 2010 (KB2553284) 64-Bit Edition
    Security Update for Microsoft Office 2010 (KB2687423) 64-Bit Edition
    Security Update for Microsoft Office 2010 (KB2850016) 64-Bit Edition
    Security Update for Microsoft Office 2010 (KB2880971) 64-Bit Edition
    Security Update for Microsoft Office 2010 (KB2881071) 64-Bit Edition
    Service Pack 2 for Microsoft Office 2010 (KB2687455) 64-Bit Edition
    SharePoint Client Components
    SketchUp 2013
    Skype™ 6.11
    SolidWorks 2013 x64 Edition SP0
    SolidWorks eDrawings 2013 x64 Edition SP0
    Source SDK Base 2007
    SourceTree
    Steam
    Sublime Text 2.0.2
    Supreme Commander 2
    Team Explorer for Microsoft Visual Studio 2013
    TeamViewer 9
    The Elder Scrolls V: Skyrim
    tools-freebsd
    tools-linux
    tools-netware
    tools-solaris
    tools-windows
    tools-winPre2k
    TradeManager 2014 Beta1
    Update for  (KB2504637)
    Update for CHS Microsoft IME HAP Dictionary
    Update for Microsoft Access 2010 (KB2553446) 64-Bit Edition
    Update for Microsoft Excel 2010 (KB2837600) 64-Bit Edition
    Update for Microsoft Filter Pack 2.0 (KB2878281) 64-Bit Edition
    Update for Microsoft InfoPath 2010 (KB2817369) 64-Bit Edition
    Update for Microsoft InfoPath 2010 (KB2817396) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2589298) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2589352) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2589375) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2597087) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2687502) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2760598) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2794737) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2825635) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2825640) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2837581) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2837606) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2878252) 64-Bit Edition
    Update for Microsoft Office 2010 (KB2881028) 64-Bit Edition
    Update for Microsoft OneNote 2010 (KB2837595) 64-Bit Edition
    Update for Microsoft Outlook 2010 (KB2687567) 64-Bit Edition
    Update for Microsoft PowerPoint 2010 (KB2837579) 64-Bit Edition
    Update for Microsoft SharePoint Workspace 2010 (KB2760601) 64-Bit Edition
    Update for Microsoft Visio 2010 (KB2880526) 64-Bit Edition
    Update for Microsoft Visio Viewer 2010 (KB2837587) 64-Bit Edition
    Update for Microsoft Word 2010 (KB2880529) 64-Bit Edition
    VirtualCloneDrive
    Visual F# 3.1 SDK
    Visual F# 3.1 VS
    Visual Studio 2013 Prerequisites
    Visual Studio 2013 Prerequisites - ENU Language Pack
    Visual Studio Extensions for Windows Library for JavaScript
    VLC media player 2.1.2
    VmciSockets
    VMware Workstation
    WCF Data Services 5.6.0 Runtime
    WCF Data Services Tools for Microsoft Visual Studio 2013
    WCF RIA Services V1.0 SP2
    WinCDEmu
    Windows App Certification Kit Native Components
    Windows App Certification Kit x64
    Windows Azure Mobile Services SDK
    Windows Azure Mobile Services Tools for Visual Studio 2013 Preview - v1.0
    Windows Azure Shared Components for Microsoft Visual Studio 2013 - v1.0
    Windows Azure Tools for LightSwitch for Visual Studio 2013 - v2.1
    Windows Runtime Intellisense Content - en-us
    Windows Software Development Kit
    Windows Software Development Kit DirectX x64 Remote
    Windows Software Development Kit DirectX x86 Remote
    Windows Software Development Kit for Windows Store Apps
    Windows Software Development Kit for Windows Store Apps DirectX x64 Remote
    Windows Software Development Kit for Windows Store Apps DirectX x86 Remote
    Windows XP Targeting with C++
    Workflow Manager Client 1.0
    Workflow Manager Tools 1.0 for Visual Studio
`

**Comment by kisak-valve** [comment]
Hello @Spiral90210, are you still experiencing this issue on an up to date system?

**Comment by Spiral90210** [comment]
I've not been using it for a while, but I'll check this evening or tomorrow and get back to you.

**Comment by kisak-valve** [comment]
Closing pending feedback.
