### ISSUE TITLE
Game re-runs after restarting Steam for update

### ISSUE THREAD

**Issue by ali1234** [ValveSoftware/steam-for-linux#3478]
To reproduce:
1. Quit Steam if it is running.
2. Click on a launcher for a game. Steam loads up, then the game loads up.
3. Quit the game.
4. Wait for a Steam update.
5. Restart Steam to install update.

Result: Steam exits, downloads the update, automatically re-opens, and then the game you originally ran also loads up.

Expected: The game should not automatically load up when Steam restarts.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #1414.
