### ISSUE TITLE
Psychonauts installation doesn't download any files

### ISSUE THREAD

**Issue by elizagamedev** [ValveSoftware/steam-for-linux#3482]
I can't seem to download Psychonauts on x64 Arch Linux.

File sizes don't appear in the install wizard:
![Error](http://i.imgur.com/iPi0ZiI.png)

And after trying to install,
![Error](http://i.imgur.com/5Fk0ByF.png)

I've seen people post about this around online in 2012 and 2013, but all the bug reports and such have since been closed (since the Linux version wasn't strictly ready yet then). I've had to look it up to confirm that, [yes, the files should be downloading in 2014](http://steamcommunity.com/app/3830/discussions/0/864958451785375756/).

Should I be reporting the bug here or contacting DoubleFine about this issue?

**Comment by kisak-valve** [comment]
Hello @elizagamedev, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
