### ISSUE TITLE
Streaming Linux to Linux - Startup splash screens not handled properly sometimes

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#3485]
I've been playing around with Linux-to-Linux streaming, and one thing I've noticed is that games with splash screens sometimes don't handle them properly.  I've seen this on XCOM and on Witcher 2.  Often, when launching the game via streaming, the streaming window will open fullscreen but not actually render (so it looks just like an unresponsive desktop).  If I go over to the streaming server, the splash screen is showing, and if I make my selection to actually start the game, the stream resumes properly and I can play the game on the client.

This doesn't _always_ happen, though.  Sometimes the splash screen comes up without a problem.  I've yet to figure out if there's a reproducible pattern there.

(As an aside, and unrelated: thanks for bringing this feature over to Linux!  I'm quite impressed with how well it works.  I've been trying out various games at a full 1080p (over wifi, no less) and the responsiveness is amazing.  I'm sure it helps that I've got a GPU capable of doing hardware encoding, but still.  Well done!)

**Comment by kisak-valve** [comment]
Hello @apocalyptech, are you still experiencing this issue with an up to date system?

**Comment by apocalyptech** [comment]
A good question!  I'll have to reinstall some of those and give them another try.  WIll let you know!

**Comment by kisak-valve** [comment]
Closing pending feedback.
