### ISSUE TITLE
TF2 recent updates borked my framerates

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#3486]
The recent updates have made my frame rates go down when out in the open while looking into numerous enemies. Before (read like a month ago or before) my frames never went lower than 70 on these ocasions, but now I came back at playing TF2 with the same locations and everything, and the frames drop to 30, but when I look back (meaning there are not so many enemies) they go to normal (170-200).

What did you guys do?

Athlon II X2 250 @3.76 GHz
9800GT (OpenGL 3.3)
Arch Linux (meaning latest kernel and NVIDIA drivers)
4 GB Corsair Vengeance @1666M MHz

**Comment by kisak-valve** [comment]
Hello @amarildojr, TF2 has changed fairly substantially over the last several years. If this is still an issue with an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
