### ISSUE TITLE
"Store password on this computer" in login dialog glitches when running from 2 OSes on same comp.

### ISSUE THREAD

**Issue by dimgel** [ValveSoftware/steam-for-linux#3488]
Hi. I have Win8 and GentooLinux in two partitions on my notebook. When I login to Steam on Linux, I check "Store password on this computer" checkbox - and it works OK, next time I run Steam it logins automatically without showing me login dialog. But if I reboot to windows, run Steam there with "Store password" checkbox UNchecked (reason: unlike Linux, my Windows partition is unencrypted) and then reboot back to Linux and run Steam, then it shows me login dialog although I think it should not. Thanks.

**Comment by kisak-valve** [comment]
Hello @dimgel, are you still experiencing this issue on an up to date system? (Note: #5030 may interfere with testing)

**Comment by dimgel** [comment]
I have no windows version to try, but two linux versions on neighbor comps auto-login ok.

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
