### ISSUE TITLE
(Walk Around) Steam Crashes Xwayland or Can't Find a Xwindow

### ISSUE THREAD

**Issue by waitwhobrokethat** [ValveSoftware/steam-for-linux#3490]
Steam For Linux Crashes Xwayland or Can't Find a Xwindow With Xwayland in Fedora 21

**Comment by kisak-valve** [comment]
Hello @waitwhobrokethat, the steam client was adjusted to prefer system libraries over the steam runtime variants by default and shouldn't encounter a Xwayland specific issue anymore.

Closing.
