### ISSUE TITLE
Fonts looking terrible after latest (Discovery) update

### ISSUE THREAD

**Issue by Throwaway1912** [ValveSoftware/steam-for-linux#3496]
After the latest update, my fonts are now almost illegibly small and poorly anti-alised. A screenshot can be seen below:

http://i.imgur.com/vULduK6.png

**Comment by kisak-valve** [comment]
Hello @Throwaway1912, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
