### ISSUE TITLE
switching desktops in bspwm crashes Steam

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3499]
Distro: Arch Linux (64 bit)
Window Manager: bspwm
Graphics driver: catalyst (14.9)

After the latest Steam update, I can't switch desktops without crashing the application. It worked fine before.

Console output:
http://nopaste.info/e52aaa92e7.html

Sadly, strace output isn't possible because Steam simply freezes after being run with strace. Without strace, it crashes.

**Comment by gheja** [comment]
Similar symptoms here on Debian 8.2, amd64, nVidia GeForce GTX 460 (nVidia driver 340.65).

When switching desktop the Steam stops updating the screen (i.e. when I drag a window before it, it leaves it parts in Steam window) but still works (right click on the notification area icon brings up the menu and starts games).

Although might be nVidia/X issue, when running a game during the switch it crashes most of the times, also sometimes the whole X session crashes.

Let me know if I can help by supplying logs, turning on switches, etc.

**Comment by kisak-valve** [comment]
Hello @gheja, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
