### ISSUE TITLE
Segmentation fault when using microphone in Steam settings or Dota 2

### ISSUE THREAD

**Issue by timss** [ValveSoftware/steam-for-linux#3503]
When trying to use a microphone in either the Steam voice settings, using the hotkey in Dota 2 or accessing the settings in Dota 2 I get a segmentation fault.

As it seems to be related to the Steam runtime/environment as a whole I chose to report this bug for the client itself. Note that I'm currently participating in the Steam Beta Update, but the bug was present without joining the beta aswell.

I've installed Steam using the official repository of Debian testing (jessie). To be on the safe side I completely reinstalled it (including the removal of `$HOME/.steam`) before debugging. 

Using the same machine and install of Debian I remember the microphone working in Dota 2 about a year ago, but I can't say when the problems started to appear.

Unlike [#847](https://github.com/ValveSoftware/Dota-2/issues/847) over at the Dota 2 issue tracker, I experience segmentation faults both in Steam voice settings and in game. Other than that I was only able to find really old issues that were now supposedly resolved. 

**Debugging and output:**

[System Information](https://gist.github.com/timss/fba7d17176644bdad158#file-steam-system-information) (crash dumps IDs included and uploaded)

[gdb output](https://gist.github.com/timss/fba7d17176644bdad158#file-debugger-gdb-steam) (includes backtrace)

[LD_DEBUG=all](https://gist.github.com/timss/fba7d17176644bdad158#file-ld_debug-all) (very long)

[pacmd list-sinks](https://gist.github.com/timss/fba7d17176644bdad158#file-pacmd_list-sinks-txt) (audio devices detected by PulseAudio)

**Screenshots:**

[Steam Settings - Voice and Select Sound Input](https://gist.github.com/timss/fba7d17176644bdad158#file-steam_sound_devices-png) (relevant devices are listed, but all lead to crashes)

[PulseAudio Volume Control - Input Devices](https://gist.github.com/timss/fba7d17176644bdad158#file-pavucontrol_input-png) (working microphone)

[PulseAudio Volume Control - Recording - Mumble is working](https://gist.github.com/timss/fba7d17176644bdad158#file-pavucontrol_recording-png) (Using PulseAudio's 'Default Input' works using Mumble)

When I press 'test microphone' in the Steam voice settings, Steam pop up for a very short period in PulseAudio Volume Control, showing that it atleast can locate the PulseAudio process:

[PulseAudio Volume Control - Recording - Steam appearing for a milisecond](https://gist.github.com/timss/fba7d17176644bdad158#file-pavucontrol_recording_steam-png)

**More information?**

I tried to keep this concise and add everything I could find. Please notify if there's something missing and I'd be happy to help.

**Comment by timss** [comment]
@kisak-valve: I'm not. Haven't really used that setup in a really long time
so can't really remember what came out of it unfortunately. Thanks though.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
