### ISSUE TITLE
No sound on Steam Store videos; YouTube-published ones work fine.

### ISSUE THREAD

**Issue by Plaque-fcc** [ValveSoftware/steam-for-linux#3504]
Using Ubuntu 14.04 x86, Steam Client Beta and PulseAudio 4.0; Steam interface sounds (Big Screen,, for instance) work, YouTube videos, in-game sounds work. All except official Steam Store trailers work, there no PulseAudio client shows up to play sound for them.

**Comment by kisak-valve** [comment]
Hello @Plaque-fcc, @Hirato, are either of you still experiencing this issue on an up to date system?

**Comment by Hirato** [comment]
Seems to be working fine on my Arch system via the Steam Runtime.

**Comment by kisak-valve** [comment]
Thanks for the feedback.

By default, Steam now prefers system libraries when they are newer than the Steam runtime variant, which should have mitigated this issue. Closing.
