### ISSUE TITLE
Serious Sam 3 fail's to detect steam (debian Jessie 32bit)

### ISSUE THREAD

**Issue by Jenco420** [ValveSoftware/steam-for-linux#3505]
I have been trying to get SS3 to start. keep coming back to this error

I am using 7750 HD 1g  ati non free drivers and i have portal 2, Fez and Starbound working

jenco@debian:~/.local/share/Steam/SteamApps/common/Serious Sam 3/Bin$ ./Sam3
WRN:  CPU Power saving is enabled and performance governor is not used.
INF:  GameEnv API: Steam
dlopen failed trying to load:
/home/jenco/.local/share/Steam/ubuntu12_32/steamclient.sowith error:
libtier0_s.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; Sys_LoadModule failed to load: /home/jenco/.local/share/Steam/ubuntu12_32/steamclient.so
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
jenco@debian:~/.local/share/Steam/SteamApps/common/Serious Sam 3/Bin$

**Comment by kisak-valve** [comment]
Hello @Jenco420, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
