### ISSUE TITLE
'View' menu not hidden in Big Picture Mode

### ISSUE THREAD

**Issue by Atalanttore** [ValveSoftware/steam-for-linux#3508]
Hi,

I've experienced a problem running Steam on Kubuntu 14.04.

The 'View' menu is not hidden in Big Picture Mode.

Screenshot:
![bigpicturemode](https://cloud.githubusercontent.com/assets/628474/4406356/38825c06-44c2-11e4-8fa9-1406e9236b01.png)

Regards,
Ettore Atalan

**Comment by kisak-valve** [comment]
Hello @Atalanttore, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing presumed fixed some time ago.
