### ISSUE TITLE
Tiling WM with Big Picture

### ISSUE THREAD

**Issue by koahv** [ValveSoftware/steam-for-linux#3509]
Hi,

DWM window manager does not register ALT+# keystrokes to navigate away from the virtual desktop where Big Picture is running because the application is fullscreen.

This means I can't switch workspace without closing Big Pic first.

Is there a way to run BP in borderless fullscreen windowed? 
Could you suggest any other workaround ?

Thank you,

Al

**Comment by aldrik** [comment]
Your issue with [DWM](http://dwm.suckless.org/) should be reported to and addressed by it's developers. It's not a Steam issue.

**Comment by kisak-valve** [comment]
Hello @koahv, was this issue also brought to the attention of a dwm dev? Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
