### ISSUE TITLE
zsh parse fails on implied variable test [[ $foo ]]

### ISSUE THREAD

**Issue by seriu** [ValveSoftware/steam-for-linux#3512]
There is a very small portability issue with zsh not accepting the bash implied test [[ $foo ]]. This is used in line 218 of the steam frontend script steam.sh on Ubuntu 14.04. Unknown if other distros are affected.

function in question:
function detect_scriptversion()
{
        SCRIPT_VERSION=$(fgrep "$2=" "$1")
        if [[ "$SCRIPT_VERSION" ]]; then
                expr "$SCRIPT_VERSION" : ".*=\(.*\)"
        else
                echo "0"
        fi
}

workaround:
add -z to the test condition
if [[ -z "$SCRIPT_VERSION" ]]; then

as opposed to above.

Note, it will also be necessary to remove 3 bytes from the file to accommodate this change, due to steam checking the size (thankfully not the checksum) of this script file on boot.

**Comment by johnv-valve** [comment]
no plans to make this script work with zsh as well as bash
