### ISSUE TITLE
Steam does not load content from servers.

### ISSUE THREAD

**Issue by EmptyHelmet** [ValveSoftware/steam-for-linux#3515]
After recent update Steam does not load anything. Running on Ubuntu 14.04 64bit. nvidia driver 331.38. everything updatet.

https://www.youtube.com/watch?v=KKcKkVmc7EQ

Terminal output.

manson@manson-PC:~$ steam
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steamwebhelper)/version(20140922201705)
Installing breakpad exception handler for appid(steamwebhelper)/version(1411417025)
Installing breakpad exception handler for appid(steamwebhelper)/version(20140922201705)
Installing breakpad exception handler for appid(steamwebhelper)/version(1411417025)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0927/111822:ERROR:nss_util.cc(1018)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Installing breakpad exception handler for appid(steam)/version(1411443970)
Adding licenses for the following package(s): 0, 37, 284, 518, 609, 715, 1053, 1580, 1619, 2481, 4315, 4885, 6257, 7877, 8672, 11675, 12172, 13054, 14840, 16222, 16549, 16779, 30182, 30669, 32375, 47466, 51437, 51730
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/manson/.local/share/Steam/ubuntu12_32/steam" "
System startup time: 16,69 seconds
[0927/111838:ERROR:renderer_main.cc(227)] Running without renderer sandbox
Generating new string page texture 67: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 68: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 69: 128x256, total string texture memory is 1,49 MB
Generating new string page texture 70: 64x256, total string texture memory is 1,56 MB
Generating new string page texture 71: 32x256, total string texture memory is 1,59 MB
Generating new string page texture 74: 256x256, total string texture memory is 1,85 MB
Generating new string page texture 76: 128x256, total string texture memory is 1,98 MB
Generating new string page texture 77: 512x256, total string texture memory is 2,51 MB
Generating new string page texture 78: 384x256, total string texture memory is 2,90 MB
Generating new string page texture 79: 24x256, total string texture memory is 2,92 MB
Generating new string page texture 80: 8x256, total string texture memory is 2,93 MB
CAPIJobRequestUserStats - Server response failed 2
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/manson/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/manson/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 82: 256x256, total string texture memory is 393,22 KB
Generating new string page texture 83: 128x256, total string texture memory is 3,06 MB
ExecSteamURL: "steam://open/friends"
[0927/111847:ERROR:renderer_main.cc(227)] Running without renderer sandbox
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Generating new string page texture 88: 48x256, total string texture memory is 3,11 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 89: 64x256, total string texture memory is 458,75 KB
Generating new string page texture 91: 64x256, total string texture memory is 3,18 MB
Generating new string page texture 93: 128x256, total string texture memory is 3,31 MB
Generating new string page texture 95: 16x256, total string texture memory is 3,33 MB
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
Installing breakpad exception handler for appid(steam)/version(1411443970)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/clientdll/configstore.cpp (792) : Assertion Failed: false
Assert( Assertion Failed: false ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/clientdll/configstore.cpp:792

Installing breakpad exception handler for appid(steam)/version(1411443970)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/clientdll/configstore.cpp (792) : Assertion Failed: false
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20140927111949_19.dmp
Installing breakpad exception handler for appid(steam)/version(1411443970)
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-bfe3b5e3-dc8a-495c-a64b-f08a12140927
Installing breakpad exception handler for appid(steam)/version(1411443970)

Its not a network issue. Windows version works on same network.

**Comment by kisak-valve** [comment]
Hello @EmptyHelmet, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
