### ISSUE TITLE
Dump files could not be uploaded, linking the dumps

### ISSUE THREAD

**Issue by wilx** [ValveSoftware/steam-for-linux#3524]
I have just noticed that some Steam crash dumps were not uploaded. I have put them into [.tar.xz and uploaded to Dropbox](https://www.dropbox.com/s/9l0svcehgogerl8/steam-dumps.tar.xz?dl=0)

**Comment by kisak-valve** [comment]
Hello @wilx, if you're still seeing issues with an up to date system, it will require a new investigation.

In general, as long as a linux system has libcurl.so and can resolve Valve domains, then minidumps will reach the crash report system.
