### ISSUE TITLE
Steam UI becomes unusable after resizing or locking screen

### ISSUE THREAD

**Issue by copywrong** [ValveSoftware/steam-for-linux#3528]
Steam UI becomes unusable after changing screen resolution or locking screen. It might be related with steamwebhelper (what is that?). Only tray icon is usable, and I can play games and use Steam overlay.

Arch Linux + Xfce + xfwm4 + nvidia

**Comment by eiglow** [comment]
I was unable to reproduce this issue. I'm on Fedora KDE with AMD graphics.

**Comment by kisak-valve** [comment]
Closing per the last comment.
