### ISSUE TITLE
[fglrx] Hammerwatch: The cursor icon isn't displayed correctly. 

### ISSUE THREAD

**Issue by Arandhras** [ValveSoftware/steam-for-linux#3532]
In any menu of the game the mouse cursor is surrounded by a filled white box; I guess it is an alpha transparency issue caused by my video card drivers, as this behavior isn't showing on my other computer which is based on an Nvidia GPU.

The curious thing is that the transparency issue doesn't show at all on screenshots, either taken by Steam or any other screenshot application.

Computer specs:
- CPU: AMD FX 6300 @ 3.5 GHz
- GPU: AMD RadeonHD 7850 2 GB
- Motherboard: Asus Sabertooth 990FX R2.0
- RAM: 8 GB DDR3-1866
- OS: Xubuntu Linux 14.04.1
- Kernel release: 3.13.0-37-generic
- GPU drivers: AMD Catalyst (fglrx) version 14.9

```
$ fglrxinfo 
display: :0.0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7800 Series
OpenGL version string: 4.4.13084 Compatibility Profile Context 14.301.1001
```

**Comment by kisak-valve** [comment]
Hello @Arandhras, are you still experiencing this issue on an up to date system?
