### ISSUE TITLE
[music] tracks of an album are hard to read in desktop interface

### ISSUE THREAD

**Issue by panzi** [ValveSoftware/steam-for-linux#3540]
See screenshot.
![steam_music_hard_to_read](https://cloud.githubusercontent.com/assets/134175/4607840/921bb2c8-5262-11e4-8302-09b7f8e01697.png)

**Comment by Uramekus** [comment]
opacity/fonts were altered since quite some time ago
![2018-08-24-17 45 37-screenshot](https://user-images.githubusercontent.com/4643873/44607083-967d7380-a7c5-11e8-979d-e5f4ac397ceb.png)

**Comment by kisak-valve** [comment]
Thanks for noticing @Uramekus, closing.
