### ISSUE TITLE
[Robocraft] Not work register button

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#3546]
Not work register button

Demonstration: https://drive.google.com/file/d/0B0nwzlfiB4aQVE9XMF9BR01XZ1k/view?usp=sharing

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.17.1-300.fc21.x86_64+debug
    X Server Vendor:  Fedora Project
    X Server Release:  11601000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 10.3.0
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31087 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  3815446 Mb
    Largest Free Hard Disk Block:  873247 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @NTMan, are you still experiencing this issue on an up to date system? Was it brought to the attention of the game devs?

**Comment by kisak-valve** [comment]
Closing pending feedback.
