### ISSUE TITLE
Autoplay prevents movie from playing

### ISSUE THREAD

**Issue by qfox** [ValveSoftware/steam-for-linux#3548]
This is something that's affected me a few weeks now, though I don't have an exact timeframe for it.

If the autoplay setting is on, the first movie of a game page refuses to play. You'll only get a poster. If a game has more than one movies it will play the others fine. But even switching back and forward between movies will not make the first movie work.

However, if you disable the autoplay setting (and refresh the page by going back to store first) all the movies work fine.

**Comment by Footissimo** [comment]
Just to say, the problem seems to have been resolved in the latest update.

**Comment by qfox** [comment]
Ooh, looks that way. Super!

Let's hope this also fixes the general instability (which I think is/was related to this issue).

Closing.
