### ISSUE TITLE
Supply full set of application icons

### ISSUE THREAD

**Issue by monreal** [ValveSoftware/steam-for-linux#355]
In order to look good (not blurry) in all possible places (panel, launchers, window switchers...) on various Linux desktop environments, Steam should supply a full set of application icons. This consists of:
- 16x16 px icon
- 22x22 px icon
- 24x24 px icon (= 22x22 plus 1 px border)
- 32x32 px icon
- 48x48 px icon
- 256x256 px high resolution image

The deb/rpm package should put these icons in /usr/share/hicolor/$size/apps/steam.png

Ideally, the icons should follow the Tango Style [1]

[1] http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines

**Comment by dreamer** [comment]
I am looking through various Steam icon related issues and this one seems to be fixed? Steam provides the following icons:

    /usr/share/icons/hicolor/16x16/apps/steam.png
    /usr/share/icons/hicolor/24x24/apps/steam.png
    /usr/share/icons/hicolor/32x32/apps/steam.png
    /usr/share/icons/hicolor/48x48/apps/steam.png
    /usr/share/icons/hicolor/256x256/apps/steam.png

Icons 24x24, 32x32 and 48x48 are proper ones, not a upscaled versions. Size 22x22 is not used anymore in Linux desktops (aside of MATE, I think). Scalable icon, while nice, does not provide any significant improvement over 256x256 at this point in time (as it didn't in 2013).

Perhaps this issue should be closed?

**Comment by kisak-valve** [comment]
Closing per the last comment.
