### ISSUE TITLE
Audio Jitter in Steam Music Player

### ISSUE THREAD

**Issue by smagrath** [ValveSoftware/steam-for-linux#3552]
Hi,
I've just installed Steam on Fedora 20 and mostly all OK. However, the Steam Music Player significantly jiiters on audio playback indicating some sort of insufficient buffering. However I can't find anyway to configure the music player and fix it.

Can't seem to find anyone else on this board with this problem...

Processor Information:
Vendor: AuthenticAMD
CPU Family: 0x15
CPU Model: 0x2
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4000 Mhz
8 logical processors
8 physical processors
HyperThreading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported

Network Information:
Network Speed:

Operating System Version:
Linux 3.10 (64 bit)
Kernel Name: Linux
Kernel Version: 3.16.4-200.fc20.x86_64
X Server Vendor: Fedora Project
X Server Release: 11404000
X Window Manager: KWin
Steam Runtime Version: steam-runtime-release_2014-08-20

Video Card:
Driver: NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

Driver Version: 4.4.0 NVIDIA 331.89
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1380
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.08" x 11.42" (23.07" diag)
51.0cm x 29.0cm (58.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes: 2x 4x 8x 16x

Sound card:
Audio device: USB Mixer

Memory:
RAM: 7943 Mb

Miscellaneous:
UI Language: English
LANG: en_AU.UTF-8
Microphone: Not set
Total Hard Disk Space Available: 1931491 Mb
Largest Free Hard Disk Block: 1610282 Mb

Installed software:

**Comment by kisak-valve** [comment]
Hello @smagrath, are you still experiencing this issue qith an up to date system?

This sounds like a general pulseaudio configuration issue with USB audio devices. You may have some success with suggestions from [Arch's pulseaudio troubleshooting](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Glitches.2C_skips_or_crackling) section.

**Comment by smagrath** [comment]
4 year response time? Really?

**Comment by kisak-valve** [comment]
Closing pending usable feedback.
