### ISSUE TITLE
ATI Drivers 14.9 and DOTA2/CS:GO "Black Screen"/Freeze

### ISSUE THREAD

**Issue by alkavan** [ValveSoftware/steam-for-linux#3559]
Hay, I'm running Steam on Gentoo GNU/Linux.

Just updated my 'ati-drivers' package to latest 14.9.
Now both my DOTA2 and CS:GO stopped working properly.

I see a "black screen", I hear DOTA/CS loading sounds, but after that nothing happens.
To check the issue I downloaded Borderlands 2 and couple of more games, they all seemed to work fine with OpenGL rendering n' all.

I also found [this related discussion](http://steamcommunity.com/app/440/discussions/0/616189742710481608/) on the forums.

Here's the details of 'lspci' command:

```
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Curacao PRO [Radeon R9 270]
```

Everything did work fine with 14.6_beta2 drivers.

This might be a Source engine issue.

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved shortly after it was reported in 2014 (per discussion on https://github.com/ValveSoftware/Source-1-Games/issues/1841)
