### ISSUE TITLE
Notification area icon is difficult to see

### ISSUE THREAD

**Issue by mhoran** [ValveSoftware/steam-for-linux#3566]
A recent update to Steam for Linux has rendered the notification area icon difficult to see:

![steam](https://cloud.githubusercontent.com/assets/5330/4875791/4b5631e6-62a8-11e4-9079-d30142ed5efa.png)

The application launcher icon is much easier to see as it is dark. Either an option to change the color scheme of the notification area icon, or automatically choosing the color scheme based on system theme would be preferred.

**Comment by CoolSilver** [comment]
Might be a duplicate but the other issue is also marked closed when the issue still exists.
