### ISSUE TITLE
Buying game in external browser allows user to install unsupported games

### ISSUE THREAD

**Issue by joemppe** [ValveSoftware/steam-for-linux#357]
Using the install link in the Steam Store allows you to install games that are not supported on Linux.

Steps to reproduce
1) Buy a game as usual, using a standalone browser (I bought Saints Row: The Third)
2) When the purchase is complete, click the install link ("Yes, I have Steam")
3) Steam will begin downloading the game even if it is not supported on Linux

OS: Ubuntu 12.04 64-bit
Browser: Chromium Version 20.0.1132.47 Ubuntu 12.04 (144678)

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.

Steampowered.com provides a steam:// url which your desktop environment can associate with steam or steam in wine. The steam client then checks for platform support.
