### ISSUE TITLE
Steam leaves files behind that prevents subsequent users from running it

### ISSUE THREAD

**Issue by scaronni** [ValveSoftware/steam-for-linux#3570]
After exiting Steam, some files are left behind. This prevents other users logging into the system from using Steam.

Details:

This is the error that is printed in the log:

```
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/webhelper/../common/html/chrome_ipc_server.cpp (155) : Assertion Failed: !"Failed to bind shmem socket"
```

After exiting the client, the Chrome socket is left behind in /tmp with restricted permissions, preventing a new user that subsequently logs in the system from overwriting the file and thus starting the client.

```
$ ls -al /tmp/steam_chrome_shmem 
srwxrwxr-x. 1 slaanesh slaanesh 0 Nov  3 10:40 /tmp/steam_chrome_shmem
```

A simple rm command in the Steam startup script should suffice in solving this, as the file it's recreated when starting again the client.

Thanks,
--Simone

**Comment by roy937** [comment]
Every time I start Steam I am doing "sudo rm -f /tmp/steam_chrome_shmem".
And then when I quit Steam I do it again.
If I forget, my son coming to pc after me won't start Steam properly and have to reboot pc.
It's realy a pain...
Hello STEAM people, is it really so hard to fix it?

**Comment by ArseniyShestakov** [comment]
Confirm this one for latest stable Steam client.
It's just make Steam UI freeze.

**Comment by scaronni** [comment]
Ping...

**Comment by roy937** [comment]
Reply.

scaronni píše v Po 25. 05. 2015 v 08:54 -0700:

**Comment by Chidorin** [comment]
sorry if i'm in wrong section, couldn't find mac one
same problem: long steam response, couldn't find steam_chrome_shmem on sierra
any changes on names/routes?

**Comment by kisak-valve** [comment]
Closing as the file name conflict was fixed some time ago.
