### ISSUE TITLE
Steam menu 

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#3574]
I have a Steam program menu bug.  When you open menu. 
The edges of the menu will shine. Although the menu is closed.

Menu edges also show in my desktop. The edges of the menu will also appear on your desktop. And if it is the case, for example, an icon can not be clicked.

Look at the following screenshot program.
https://dl.dropboxusercontent.com/u/62997820/Steam-menu-ui-bug.png

im using latest Steam for Ubuntu 12.04 
[code]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-44-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560 Ti/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.104
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1200
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1360 x 768
Desktop Resolution: 1360 x 768
Primary Display Size: 16,14" x 10,08"  (19,02" diag)
                                        41,0cm x 25,6cm  (48,3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fi_FI.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  930710 Mb
    Largest Free Hard Disk Block:  456944 Mb

Installed software:

Recent Failure Reports:

[/code]

**Comment by kisak-valve** [comment]
Hello @lahtis, are you still experiencing this issue on an up to date system?
