### ISSUE TITLE
The wallpaper is visible when tiled Steam windows are resized

### ISSUE THREAD

**Issue by ScoreUnder** [ValveSoftware/steam-for-linux#3576]
This is demonstrated in a previous video: http://youtu.be/tdypcnuRRkY

When the steam windows resize (particularly noticeable when the dialog is closed near the end of the video) the wallpaper sometimes flickers on-screen. Steam is the only program that causes this.

I have seen this happen on ATI Radeon HD 7770 and Nvidia GeForce GTX 660 Ti, both using proprietary drivers.

**Comment by kisak-valve** [comment]
Hello @ScoreUnder, this is an inherent tendency when resizing all X applications and not specific to Steam. Any X application that is not ready to render the new dimensions of the resized window on the same frame the resize occurred can show uninitialized memory.
