### ISSUE TITLE
Steam makes a horrible noise when you're verifying cache integrity and attempt to interact with the client

### ISSUE THREAD

**Issue by Tea23** [ValveSoftware/steam-for-linux#358]
I realise this is not specific to Steam for Linux - but it's about time we actually reported this sort of stuff and we've never had a very good arena for such issue reports before.

When you go to verify cache integrity, interaction with the rest of the client is lost. This is fine (although perhaps chat should remain interactive) except the default Steam error noise is jarring and when wearing headphones - or indeed in some other environments - is actually very painful to hear.

Either the default error noise needs to be changed, or support for sound schemes should be added in - it is currently possible to change the sounds yourself, but they will be overwritten during a Steam update.

The "duh-ding" noise serves to punish the user for trying to explain to their friend why they have to verify cache integrity rather than informing them that interaction with the client is not possible whilst verifying. So a much less violent sound should be picked. Perhaps on Windows, Steam should just use the system sound scheme (I'm not sure if Mac does a similar thing) whilst on Linux the default sounds could just be less painful and customisable without risk of being overwritten.

**Comment by kisak-valve** [comment]
Closing as verifying game files no longer blocks Steam's UI.
