### ISSUE TITLE
steam launcher crashes on second run (libdbus)

### ISSUE THREAD

**Issue by njsg** [ValveSoftware/steam-for-linux#3580]
Steam had been working for months, but, since some time ago, it always
crashes when starting: I issue "steam --reset", steam will start the
first time, but after that, it will always segfault on line 729 of
steam.sh.

According to gdb, the segmentation fault occurs on libdbus-1.so.3, as
steam seems to be trying to do something networkmanager-related.
(Full backtrace: https://bpaste.net/raw/c23e3838b652)

This is on Gentoo GNU/Linux (amd64). I am using the runtime libraries
packaged with steam, and I've also tried after starting the system
messagebus and by running steam through dbus-launcher.

I don't have networkmanager, but other people tell me they are able to
run steam without networkmanager, so I suppose this is not the issue.

**Comment by ennui93** [comment]
I can confirm this issue running Steam inside a 32-bit chroot without the dbus daemon running and the "Remember my password" option checked.

`rm -fr .local/share/Steam/config` clears up the issue. Will leave the save password option unchecked for the time being.

Stack trace from gdb for those interested.
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xddd35b40 (LWP 3738)]
0xe00820b6 in dbus_connection_ref () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
(gdb) bt
#0  0xe00820b6 in dbus_connection_ref () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3
#1  0xdf9f5275 in dbus_g_connection_ref () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libdbus-glib-1.so.2
#2  0xdf9bf670 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/libnm-glib.so.4
#3  0xe55c9683 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#4  0xdf9bf7a0 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/libnm-glib.so.4
#5  0xdf9c2294 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/libnm-glib.so.4
#6  0xe55cacf9 in g_object_newv () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#7  0xe55cb543 in g_object_new_valist () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#8  0xe55cb7a0 in g_object_new () from /home/steam/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#9  0xde891051 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xde80ddef in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xde8e5e7f in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xde463b59 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xde8e4e0e in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xde462c11 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xde4664a4 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xde467180 in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xe1f4a04a in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so
#18 0xe1f4870c in ?? () from /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so
#19 0xe1f48945 in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so
#20 0xe1f48997 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so
#21 0xe1f4c740 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so
#22 0xe5e462bf in start_thread () from /lib/libpthread.so.0
#23 0xe5d81a5e in clone () from /lib/libc.so.6
