### ISSUE TITLE
Launching Transistor or connecting to a server in Monaco causes router to crash

### ISSUE THREAD

**Issue by QRQD** [ValveSoftware/steam-for-linux#3588]
Distro: Kubuntu 14.04

Happens after transistor finishes loading its opening cutscene, or when Monaco trying to connect to a server or connect someone to your own server. Router seems to hard crash, not accepting pings or connections from any connected computers and requiring a physical restart to fix.

Issue only happens when steam is in online mode. Other games may also cause this, but I haven't tested extensively - Cave Story Plus, Super Meat Boy, Team Fortress 2 and Dota 2 all seem to work fine.

My router is a Billion BiPAC 7800NXL with default firmware, for reference.

**Comment by kisak-valve** [comment]
Hello @QRQD, are you still experiencing this issue with an up to date system? If your router is crashing, then there is bigger issues with the router.

**Comment by kisak-valve** [comment]
Closing as the quality of network hardware is outside the scope of this issue tracker.
