### ISSUE TITLE
Crash when changing the profile picture

### ISSUE THREAD

**Issue by ltworf** [ValveSoftware/steam-for-linux#3591]
When I try to change my profile picture from the steam client. I get that very annoying non-standard dialog which lacks completion or knowledge of what the `~` symbol means.

Then I go to the root directory, and slowly start to navigate toward the image I want, but when I enter my home directory, the client crashes.

**Comment by kisak-valve** [comment]
Hello @ltworf, are you still experiencing a crash with this issue on an up to date system?

**Comment by ltworf** [comment]
Can no longer reproduce
