### ISSUE TITLE
Trying to delete local content results in a segfault

### ISSUE THREAD

**Issue by hendersj** [ValveSoftware/steam-for-linux#3593]
Running on openSUSE 13.1 x86_64 here.

Today, the client updated to the version indicated as built Nov 11, 2014 at 16:52:24.

I just purchased "Light" in the latest humble bundle, and messed the installation up, so I wanted to delete local files and just reinstall (the mono installation is toast for it after doing a verify), but when I try to delete the local files for the game, I get a segmentation fault.  The output is as follows:

./steam.sh: line 729:  8053 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-f29524d8-939f-4ad0-bc7b-8922d2141113

What additional information is necessary to resolve this issue?

**Comment by kisak-valve** [comment]
Hello @hendersj, are you still experiencing this issue on an up to date system?

**Comment by hendersj** [comment]
Now running on openSUSE Leap 42.3 and just was able to delete the game - I'd totally forgotten about this ticket and issue.

The game in question doesn't launch, but that looks to be a separate issue.

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as the original issue appears to have been resolved some time ago.
