### ISSUE TITLE
[feat-req] Manually enter download speed

### ISSUE THREAD

**Issue by ozone89** [ValveSoftware/steam-for-linux#3594]
Some countries (helloooo, Italy!) have lines whose speed are not suitable for tiered limits, especially when dealing with lower speeds.
In my case: I have a 4Mbps line, so the nearest tier would be 512KB/s, which is the exact limit of my line!
(512*8 = 4096)

~~However, if I was to set the immediate lower tier, I'd have 256KB/s, which is too low (In my case, I'd settle for something in between)~~
(scratch this part, just received the latest update that added an intermediate option. the case remains, though)

What i suggest is to add an optional text field so that users may input the desired limit.
(a feature any download manager have since years!)

**Comment by kisak-valve** [comment]
Hello @ozone89, per "Changed download throttling setting to be a custom value in Kbps" in the [2020-09-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4042499938193651739) Steam client beta update, this request has been implemented.

**Comment by cybik** [comment]
@kisak-valve a nit/complaint: the divider used in your UI to go from kbps to mbps is 1000, while the real divider is 1024.
