### ISSUE TITLE
Steam overlay causes black screen for Planetary Annihilation

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#3601]
For some reason each time I cold-start Planetary Annihilation with steam community enabled for it, the game gives me a black screen. With it turned off there is no issue.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3401 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 17 Qiana (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-release_2014-08-20

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650 Ti/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 340.58
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x11c6
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 6.30" x 3.54"  (7.20" diag)
                                        16.0cm x 9.0cm  (18.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7930 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  460838 Mb
    Largest Free Hard Disk Block:  230474 Mb

Installed software:

Recent Failure Reports:

**Comment by liamdawe** [comment]
Nearly a month has passed, and it is still happening.

Any news on this?

**Comment by liamdawe** [comment]
I finally caught it happening in the terminal:

Pastebin: http://pastebin.com/dxARvr06

**Comment by not83** [comment]
Liam dawe :) I recognise the name
