### ISSUE TITLE
Steam crashes on startup (I am using OpenRC init)

### ISSUE THREAD

**Issue by sergioad** [ValveSoftware/steam-for-linux#3608]
Hello as I said I am using OpenRC on Arch; launching the game I found this error

sergio@Manjaro
OS: Manjaro 0.8.11-rc1 Ascella
 Kernel: i686 Linux 3.16.7.1-1-MANJARO
Packages: 1175
Shell: zsh 5.0.7
Resolution: 1280x800
DE: XFCE4
WM: Xfwm4
WM Theme: Menda
GTK Theme: Menda [GTK2], Not Found [GTK3]
Icon Theme: Menda-Square
Font: Cantarell 11
CPU: Intel Core2 Duo CPU T5250 @ 1GHz
RAM: 299MB / 996MB

Manjaro% steam
Running Steam on manjarolinux 0.8.11-rc1 32-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steamwebhelper)/version(20141121162341)
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
Installing breakpad exception handler for appid(steamwebhelper)/version(20141121162341)
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
Installing breakpad exception handler for appid(steam)/version(1416617579)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
Assert( Assertion Failed: descs.Count() >= 1 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp:276

Installing breakpad exception handler for appid(steam)/version(1416617579)
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/crash_20141126235912_6.dmp
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
FillInMachineIDInfo took a total of 6 milliseconds
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)

(steam:3194): GLib-GObject-WARNING **: invalid cast from 'NMSettingIP6Config' to 'NMRemoteSettings'

(steam:3194): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(steam:3194): GLib-GObject-WARNING **: gsignal.c:3101: signal id '168' is invalid for instance '0xaf6c6188'

(steam:3194): GLib-GObject-WARNING **: invalid cast from 'NMSettingIP6Config' to 'NMRemoteSettings'

(steam:3194): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(steam:3194): GLib-GObject-WARNING **: gsignal.c:3101: signal id '168' is invalid for instance '0xaf6c6188'

(steam:3194): GLib-GObject-WARNING **: invalid cast from 'NMSettingWired' to 'NMRemoteSettings'
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20141126235908_1.dmp
/home/sergio/.local/share/Steam/steam.sh: línea 729:  3194 Violación de segmento  $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
Finished uploading minidump (out-of-process): success = no
error: Failure when receiving data from the peer
Finished uploading minidump (out-of-process): success = no
error: Couldn't connect to server
Manjaro%

**Comment by phaazon** [comment]
Same issue here as well when trying to use the native runtime of Archlinux:

```phaazon@illusion ~ % STEAM_RUNTIME=0 steam
/home/phaazon/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/phaazon/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on arch  64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steam:14838): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
Installing breakpad exception handler for appid(steam)/version(1424305157)

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(steamwebhelper:14841): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
Installing breakpad exception handler for appid(steamwebhelper)/version(20150218153139)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424273499)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150218153139)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424305157)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424305157)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
Assert( Assertion Failed: descs.Count() >= 1 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp:276

Installing breakpad exception handler for appid(steam)/version(1424305157)
crash_20150324002021_5.dmp[14864]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150324002021_5.dmp
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/vgui2/src/../vgui_surfacelib/FontManager.cpp (276) : Assertion Failed: descs.Count() >= 1
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)

(steam:14838): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'NMRemoteSettings'

(steam:14838): GLib-GObject-CRITICAL **: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed

(steam:14838): GLib-GObject-CRITICAL **: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
assert_20150324002020_1.dmp[14879]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150324002020_1.dmp
/home/phaazon/.local/share/Steam/steam.sh: line 757: 14838 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

**Comment by Oxalin** [comment]
phaazon, if you are on Arch, add the alucryd-multilib repository and install lib32-libnm-glib46. This may fix your NMRemoteSettings error. You may need to install some other libs also. See https://wiki.archlinux.org/index.php/unofficial_user_repositories#alucryd-multilib for the repository.

**Comment by phaazon** [comment]
Thank you, I’ll test that tonight.

**Comment by Oxalin** [comment]
@sergioad , @phaazon , @uberscientist : did using the alucryd-multilib repository and installing the lib32-libnm-glib (...-glib46) fixed the problem for you, since you are all on Arch? I'm trying to help somebody using OpenSUSE Tumbleweed and I suspect he is hitting the same issue as this one: the shipped libnm is 1.0.0, which has an incompatible API with the 0.9.8 version used by Steam.

**Comment by phaazon** [comment]
@Oxalin nope. Still the same issue.

**Comment by uberscientist** [comment]
@Oxalin Same issue as well, I also have to set a correct `LD_LIBRARY_PATH` before executing now too: `STEAM_RUNTIME=0 LD_LIBRARY_PATH="/usr/lib32" steam`

and it's *still* seg faulting... probably not a high priority to fix it.

**Comment by sergioad** [comment]
@Oxalin I used it on a 32 bits system

**Comment by Oxalin** [comment]
@uberscientist , the LD_LIBRARY_PATH is not set by default. You could add as empty at boot. There is a specific bug about it. Steam launch script would only need a really simple modification to be fixed, but seems to be a really low priority sadly.

We can work on your problem from there. I can't remember exactly all I did to make it work properly, but I think I have some mother libs frtom the alucryd repository. But I could try to find the deleted libs from Steam and all the needed libs from alucryd. I'll have a look at home.

**Comment by vdrandom** [comment]
Same issue. Was hoping to figure out why AoW3 slows down when running in steam environment, but I guess tough luck, huh.
Archlinux, x86_64, all the deps installed (even lib32-p11-kit fixed manually).

**Comment by Oxalin** [comment]
To all of the one using Archlinux (and maybe Manjaro), about alucryd repository, could you install the steam-libs package? That will let you know if you have any other libraries that should be pulled from alucryd or missing one (just in case).

**Comment by CommanderAlchemy** [comment]
@Oxalin Seems alucryd is missing one package but dont think its related.

Libteam is missing for x86_64, arch repo got 1.14-2 while alucryd is using 1.11 but not supplying a x86_64 package for it and it fails for me to install.

Other than that, FontManager.cpp (276) errors, font issue maybe?

**Comment by Oxalin** [comment]
@CommanderAlchemy , yes, I see. However, Archlinux provides the 1.14-2 version both for 32 and 64bit. They are the one installed on my system, and I don't have any problem with them. Maybe Alucryd should remove or modify the steam-libs dependencies, but that is another story.

About the FontManager.cpp errors, I don't think you need to worry about them. I have the same errors and everything works fine.

**Comment by kisak-valve** [comment]
Hello, if anyone is still experiencing this issue on an up to date system, then it would be best to open a new issue report so we can do a fresh investigation.
