### ISSUE TITLE
7 Days To Die Alpha 10.1 Fails To Launch

### ISSUE THREAD

**Issue by egee-irl** [ValveSoftware/steam-for-linux#3609]
I have 7 Days To Die on two computers: a desktop with an AMD processor and an AMD Radeon graphics card (using Mesa 10.3.3) and a laptop with an Intel Celeron processor with Intel HD graphic (also using Mesa 10.3.3). The desktop machine launches 7 Days To Die Alpha 10.1 without any problems. The laptop fails to launch the game entirely (a window appears for less than a second and then closes without an alerts or messages). I am able to launch the game on the laptop just fine without Steam (or Steam Runtime) however the game doesn't play without Steam enabled.

It should be noted that I was able to play 7 Days To Die Alpha 10.0 without any problem what-so-ever.

Here is the debug log for Alpha 10.1:

ERROR: ld.so: object '/home/userName/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Inconsistency detected by ld.so: dl-open.c: 678: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
ono/etc'

Selecting FBConfig
GLX_FBCONFIG_ID=103
GLX_BUFFER_SIZE=32
GLX_DOUBLEBUFFER=1
GLX_RED_SIZE=8
GLX_GREEN_SIZE=8
GLX_BLUE_SIZE=8
GLX_ALPHA_SIZE=8
GLX_DEPTH_SIZE=24
GLX_STENCIL_SIZE=8
GLX_SAMPLES_ARB=0
GLX_SAMPLE_BUFFERS_ARB=0
GLX_CONFIG_CAVEAT=NONE

Desktop is 1366 x 768 @ 60 Hz
OpenGL:
    Version:  OpenGL 3.0 [3.0 Mesa 10.3.3]
    Renderer: Mesa DRI Intel(R) Bay Trail x86/MMX/SSE2
    Vendor:   Intel Open Source Technology Center
    VRAM:     256 MB
    Extensions: [Lots of GL extensions here...]
Setting maxVSyncInterval to 4
GL: disabling shadows on Intel 9xx (buggy)
GL: disabling framebuffer blit, antialiasing, SRGB on Intel
GL: Detected 0 MB VRAM
Total system RAM: 3848 MiB
Initialize engine version: 4.5.5p4 (1279c4722048)

And here is the debug log for Alpha 10.0 (the version that works):

ERROR: ld.so: object '/home/userName/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 251570
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198072661541 [API loaded no]
**\* Error in `./7DaysToDie.x86': corrupted double-linked list: 0x0ad457e8 ***
======= Backtrace: =========
/lib/libc.so.6(+0x6d7e3)[0xf72f57e3]
/lib/libc.so.6(+0x7392a)[0xf72fb92a]
/lib/libc.so.6(+0x73bd0)[0xf72fbbd0]
/lib/libc.so.6(+0x7453b)[0xf72fc53b]
./7DaysToDie.x86[0x8087326]
./7DaysToDie.x86[0x8087482]
./7DaysToDie.x86(_ZdlPv+0x2f)[0x8083a5f]
./7DaysToDie.x86[0x84be48c]
./7DaysToDie.x86[0x85662fb]
./7DaysToDie.x86[0x84cb198]
./7DaysToDie.x86[0x83794e4]
./7DaysToDie.x86[0x891d635]
/lib/libc.so.6(__libc_start_main+0xf3)[0xf72a1993]

[Truncated the rest; log was very long]

**Comment by kisak-valve** [comment]
Hello @egee-irl, are you still encountering this issue on an up to date system?

**Comment by egee-irl** [comment]
@kisak-valve Hm this bug was a from several years ago, and I've been playing 7dtd since then. I actually haven't had _any_ problems in a pretty long time.

If you don't mind, let's go ahead and close this issue and if to crops up again, I'll create a new issue with newer information.

**Comment by kisak-valve** [comment]
Thanks, closing.
