### ISSUE TITLE
segmentation fault when starting steam on linux

### ISSUE THREAD

**Issue by Eleuin** [ValveSoftware/steam-for-linux#3610]
before anyone suggests, yes i have tested on multiple installs (Ubuntu, Xubuntu, and ElementaryOS), and i have done apt-get install --reinstall several times too

this is the console output in its entirety

```
eleuin@eleuin-pc:~$ steam
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2014-11-30 00:51:49] Startup - updater built Nov 25 2013 18:07:05
Segmentation fault (core dumped)
/usr/games/steam: 16: /usr/games/steam: /home/eleuin/.steam/steam.sh: not found
```

i have removed all steam files, and even tried this on fresh installs, with and without the FOSS drivers.
just on the odd chance this might be the issue:

uname -a: http://paste.ubuntu.com/9309880/
lsmod: http://paste.ubuntu.com/9309877/
lspci: http://paste.ubuntu.com/9309886/

**Comment by patflick** [comment]
Same issue on Ubuntu 14.04.2 LTS with `fglrx-updates` AMD drivers:
```
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2015-06-30 16:46:22] Startup - updater built Nov 25 2013 18:07:05
Segmentation fault (core dumped)
/usr/games/steam: 16: /usr/games/steam: /home/patrick/.steam/steam.sh: not found
```
