### ISSUE TITLE
Pulseaudio input device crashes Steam

### ISSUE THREAD

**Issue by z33ky** [ValveSoftware/steam-for-linux#3625]
Attempting to use a microphone in a Source game (e.g. Counter-Strike: Global Offensive) or in Steam (e.g. voice chat) crashes Steam when a Pulseaudio input device is selected.

Here's a gist with my system information: https://gist.github.com/z33ky/0435072225813cff9179
Take special note where it says "Microphone:  Not set", although a microphone is plugged in; I should note that selecting an ALSA device works, although the information doesn't change.
Here's the console output when it crashed:

```
warning: The VAD has been replaced by a hack pending a complete rewrite
assert_20141209205823_1.dmp[3823]: Uploading dump (out-of-process)
/tmp/dumps/assert_20141209205823_1.dmp
/home/z33ky/.local/share/Steam/steam.sh: line 729:  3737 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
assert_20141209205823_1.dmp[3823]: Finished uploading minidump (out-of-process): success = yes
assert_20141209205823_1.dmp[3823]: response: CrashID=bp-5c4026af-2591-4919-9be4-c8df02141209
assert_20141209205823_1.dmp[3823]: file ''/tmp/dumps/assert_20141209205823_1.dmp'', upload yes: ''CrashID=bp-5c4026af-2591-4919-9be4-c8df02141209''
```

I'm using Pulseaudio 5.0. Sound output seems to work fine. Other applications, e.g. Mumble, can use the mic through Pulseaudio.

**Comment by z33ky** [comment]
This is still an issue. Is there any additional info you need, or are there other ways I can help?

Here's a fresh dump btw

    assert_20150207172805_1.dmp[4321]: file ''/tmp/dumps/assert_20150207172805_1.dmp'', upload yes: ''CrashID=bp-166f023d-35d0-4672-a525-e0b042150207''

**Comment by z33ky** [comment]
I tracked down the issue to a conflict with the Pulseaudio communication between the 32-bit chroot and the 64-bit host. My current workaround is using Pulse's TCP networking instead of shm or whatever is used by default, but this is certainly not an issue with Steam, so this issue can probably be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
