### ISSUE TITLE
Screenshots come out all black

### ISSUE THREAD

**Issue by noccy80** [ValveSoftware/steam-for-linux#3627]
Since one of the beta updates, all screenshots I've taken has come out all black. Overlays and toasts work just fine, even get one saying "Screenshot captured" with the black screenshot.

On Ubuntu 14.10 64-bit, ATI Mobility Radeon HD4250 using OSS radeon driver.

Related [Steam community forum thread](http://steamcommunity.com/app/221410/discussions/0/624076851085243707/)

**Comment by ItsMeOnly** [comment]
Mine were fine, but after last update they are all black. In-game screenshots (not caught by steam) work fine

**Comment by Plagman** [comment]
Hello, what game are you testing with?

**Comment by ItsMeOnly** [comment]
Portal2, HL2, HL

**Comment by Plagman** [comment]
Is this still the case with the latest beta build that just released? If so, what graphics card and driver are you running?

**Comment by ItsMeOnly** [comment]
So far so good, every attempt to take screenshots with the latest beta work. Just FYI, since you asked:

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.22
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                            52.1cm x 29.3cm  (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC889
    
Memory:
    RAM:  6012 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Total Hard Disk Space Available:  225286 Mb
    Largest Free Hard Disk Block:  54885 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by Plagman** [comment]
Thanks! We're refactoring the screenshot code a bit and are trying to iron out the last few quirks. Let us know if there's a game where it still doesn't work.

**Comment by ItsMeOnly** [comment]
I spoke too soon. Black screenshots in HL2 after restarting.

**Comment by kisak-valve** [comment]
Hello, is anybody still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing presumed fixed some time ago.
