### ISSUE TITLE
Steam doesn't detects that connection is reestablished

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3628]
Sometimes the connection dies due to a bug with NetworkManager and Steam shows "No connection". After the connection is back I need to manually restart Steam so it detects the connection is back.

**Comment by garciabruno** [comment]
I can confirm this, it is really annoying that Steam does not restablishes the connection.
Specially if you are on a lousy wireless network.

**Comment by Plaque-fcc** [comment]
It doesn't try to go back online when the connection has gone; while it
tries to manage connections (like in #3424). Weird paradigm…

+1, this bug affects me too.

**Comment by kisak-valve** [comment]
Hello @garciabruno, @Plaque-fcc, are either of you seeing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by garciabruno** [comment]
@kisak-valve Issue seems to be solved. Appreciated.
