### ISSUE TITLE
problem with steam on ubuntu 14.04

### ISSUE THREAD

**Issue by Andorial** [ValveSoftware/steam-for-linux#3632]
Hello, help to solve the problem.After logging in Steam, he crashes.I tried reinstall Steam and change drivers, steam not working.
P.S. Sorry for my english)
antoh@antoh-MS-7529:~$ steam
rm: невозможно удалить «/home/antoh/.steam/steam»: Это каталог
rm: невозможно удалить «/home/antoh/.steam/bin»: Это каталог
Running Steam on ubuntu 14.04 32-bit
STEAM_RUNTIME is enabled automatically
[2014-12-14 19:55:56] Startup - updater built Nov 21 2014 16:23:41
Installing breakpad exception handler for appid(steam)/version(1416617579)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1416617579)
[2014-12-14 19:55:56] Checking for update on startup
[2014-12-14 19:55:56] Checking for available updates...
Installing breakpad exception handler for appid(steam)/version(1416617579)
[2014-12-14 19:55:57] Download skipped: /client/steam_client_ubuntu12 version 1416617579, installed version 1416617579
[2014-12-14 19:55:57] Nothing to do
[2014-12-14 19:55:57] Verifying installation...
[2014-12-14 19:55:57] Performing checksum verification of executable files
[2014-12-14 19:55:57] Verification complete
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Installing breakpad exception handler for appid(steamwebhelper)/version(20141121162341)
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
Installing breakpad exception handler for appid(steamwebhelper)/version(20141121162341)
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
[1214/195558:ERROR:nss_util.cc(1018)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(1416587021)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Generating new string page texture 7: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180,22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442,37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507,90 KB
Generating new string page texture 12: 8x256, total string texture memory is 516,10 KB
Generating new string page texture 13: 16x256, total string texture memory is 532,48 KB
Generating new string page texture 14: 24x256, total string texture memory is 557,06 KB
Generating new string page texture 15: 32x256, total string texture memory is 589,82 KB
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
Installing breakpad exception handler for appid(steam)/version(1416617579)
ExecCommandLine: "/home/antoh/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Adding licenses for the following package(s): 0, 17250, 21310, 36804, 47466, 52998, 54974, 55143, 55144, 56320
roaming config store loaded successfully - 409 bytes.
migrating temporary roaming config store
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/antoh/.steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1416617579)
System startup time: 15,36 seconds
Running Steam on ubuntu 14.04 32-bit
STEAM_RUNTIME has been set by the user to: /home/antoh/.steam/ubuntu12_32/steam-runtime
Uploading dump (out-of-process) [proxy '']
/tmp/dumps/assert_20141214195556_1.dmp
/home/antoh/.steam/steam.sh: строка 729:  4027 Ошибка сегментирования                   (подготовлен дамп ядра) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
antoh@antoh-MS-7529:~$ Finished uploading minidump (out-of-process): success = yes
response: CrashID=bp-627f4215-3bf7-4da4-9015-e65c42141214
Finished uploading minidump (out-of-process): success = no
error: Couldn't connect to server

**Comment by kisak-valve** [comment]
Hello @Andorial, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
