### ISSUE TITLE
Can't install / download anything on Fedora 21

### ISSUE THREAD

**Issue by davorb** [ValveSoftware/steam-for-linux#3634]
When I try to install games, I get to "Steam is now downloading ...", but after that it doesn't actually download anything. I get stuck at 0 bytes.

Here's a log of [sysout](https://gist.github.com/davorb/14831098ce1cd463c263) and here's my [system info](https://gist.github.com/davorb/14631715ca59d828f541).

**Comment by kisak-valve** [comment]
Hello @davorb, if you're still experiencing this issue on an up to date system, please open a new issue report.
