### ISSUE TITLE
Client won't start

### ISSUE THREAD

**Issue by boostoo** [ValveSoftware/steam-for-linux#3635]
Please view this question https://support.steampowered.com/view.php?ticketref=8486-RUHX-3535

**Comment by kisak-valve** [comment]
Hello @boostoo, are you still experiencing this issue on an up to date system?

**Comment by boostoo** [comment]
I have since moved to a Windows system, I do not recall what happened on
the old one. Thank you for following up.

Le ven. 18 mai 2018 à 15:37, kisak-valve <notifications@github.com> a
écrit :
