### ISSUE TITLE
steam system tray icon does nothing / non interatctive

### ISSUE THREAD

**Issue by anexation** [ValveSoftware/steam-for-linux#3638]
As said in the description the steam system tray icon shows up but it is non interactive, it does nothing on double click or right click..

OS: Arch Linux 64bit
Desktop: KDE Plasma 5

![image](https://cloud.githubusercontent.com/assets/6136025/5516760/9d348518-8877-11e4-8d79-2941e33f67aa.png)

**Comment by kisak-valve** [comment]
Closing as Arch's packaging has changed significantly since this issue report was made and I can not reproduce this issue on my Arch test box.
