### ISSUE TITLE
Christmas Wish; A triple-A casual racing title for SteamOS

### ISSUE THREAD

**Issue by KennethNielsen** [ValveSoftware/steam-for-linux#3640]
Dear Santa Newell

I have been good all year, and I only have one computer game related Christmas wish:

 * I would like a triple-A, casual racing title, to be brought to the SteamOS and Linux.

Anything you can do to make this happen, would make it an even merrier Christmas than it already is.

Regards Kenneth (33 years old)

**Comment by KennethNielsen** [comment]
@CommanderAlchemy I know it's not relavant here, this was just meant as a joke and at the same time try to highlight that SteamOS has been a little in the genre. Distance looks interesting, but, as you mention, still not complete.

@Balderick Both iracing and assetto corsa would qualify, except they are not yet available for SteamOS.

With the SteamOS sale, Grid Autosport was announced as coming to SteamOS, which would fix this, but not until later in the year. I'll leave the bug open until them.

**Comment by ozone89** [comment]
@KennethNielsen 
also Project Cars 1 and 2
https://www.gamingonlinux.com/articles/project-cars-2-announced-with-linux-support.5551

**Comment by MrSchism** [comment]
While this is old, I do want to point out that I've been riding both Feral and Aspyr about this (but mostly Feral).  The Steam Controllers have paddles on the back of the controller which feel perfect for a serious racing game, but there isn't a title around on the platform that uses shifting (yet).

**Comment by KennethNielsen** [comment]
I think it is great that more car games are promised to be ported that does not make them available. If I'm allowed I will keep this open untill the actual release of a triple A racing game being available.

@MrSchism great, keep up the hold work.

**Comment by autonomouse** [comment]
ho ho ho http://www.feralinteractive.com/en/mac-games/gridautosport/

**Comment by KennethNielsen** [comment]
@autonomouse That looks great, and it would be great if they would manage making it available before Christmas (although a year late ;)) but as mentioned in some of the previous comments, since it is not available for SteamOS **yet**, I will leave the issue open until then.

Thanks and merry X-mas

**Comment by KennethNielsen** [comment]
@autonomouse ah, I see now that it was in the pipeline and is now available.

Cool, that solves this issue. Let's hope that more will follow.
