### ISSUE TITLE
Inadequate error message for improperly named steam library's steamapps folder

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3649]
While moving to a new computer I moved over my library and it had the "steamapps" folder named "SteamApps" which prevented it from being read, however, I got this error message when I tried to add my library http://puu.sh/dL7JY/cb471473f6.png  "New Steam library folder must be on a filesystem mounted with execute permissions". I suggest a more appropriate error dialog for the situation to prevent future confusion.

**Comment by TheSentry** [comment]
I can confirm the issue, the error message and the workaround, the NTFS partition is mounted without "noexec" option and renaming the folder "SteamApps" to "steamapps" solves the problem.

**Comment by apeiron** [comment]
This is a hilariously misleading message and really ought to be fixed.

**Comment by Gartral** [comment]
I'm being plauged by this myself, but in my case it's an EXT4 1 TB drive and it was working for a yeal, suddenly it doesn't.. started two days ago... it's driving me insane

**Comment by hlangeveld** [comment]
I just encountered this issue this morning after an ubuntu 14.04 LTS kernel update to 3.13.0.59.66.
After the reboot, steam could not find my library folders.

**Comment by mevdschee** [comment]
@hlangeveld: see: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479093

**Comment by wayneschuller** [comment]
Ubuntu have fixed the kernel and released an update to this bug. They had released a kernel that caused ld to crash on 64 bit systems running 32 bit binaries.

However Valve could improve the steam error messages. :)

**Comment by Larrik** [comment]
I struggled with this one off and on for months, changing my fstab in tons of different ways. Turns out it was capitalization? That's bonkers! Thanks for this tickets, otherwise I never would have found it!

**Comment by Spooner** [comment]
Thanks for this. Was very misleading!

**Comment by fuzetsu** [comment]
Just happened to me, fortunately found this issue after about an hour of messing around with fstab....

**Comment by kisak-valve** [comment]
If anyone here can easily test this, per "Fixed a bug where trying to re-add old Steam Library folders to the client would fail with an error about the filesystem not being mounted with execute permissions" in the [2018-04-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1657763209739490075) Steam beta client, please opt into the beta and check if this the Steam client's behavior has improved.

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by jagdtigger** [comment]
Just here to chime in, this problem just stuck his ugly head out once again. Steam client up-todate, non-beta. 

Error from launching steam in terminal:
sh: 1: /mnt/DS416_Data_2/Games/Zbox_Games_Steam/.steam_exec_test.sh: not found

CIFS mount options:
[code]exec,vers=3.0,rw,credentials=/home/<user>/.smbcredentials,iocharset=utf8,dir_mode=0777,file_mode=0777,uid=1000,gid=1000,auto[/code]

OS: Ubuntu Mate 18.10, also up-to-date.

**Comment by kisak-valve** [comment]
Hello @jagdtigger, your issue doesn't match the issue tracked here. Please open a new issue report.

**Comment by jagdtigger** [comment]
I originally found my problem here:
https://github.com/ValveSoftware/steam-for-linux/issues/3812

But it was closed because its a duplicate of this....
