### ISSUE TITLE
issues in bigrock , plr_pipeline etc.

### ISSUE THREAD

**Issue by HalfDeadTF2** [ValveSoftware/steam-for-linux#3652]
in bigrock, there is a fence next to a building thingy with a ammo pack and a health pack,when i rocket jump towards the fence, i get stuck.
the only way to escape is to respawn but i dont think i can if i cant change classes during waves.
secondly,the red team's spawn in plr_pipeline's final round has a fan,where engineers can place teleporter exits which blu spies can exit on the "feet" of the fan.
i actually wanted to upload a screenshot but it was not supported :\

**Comment by Tele42** [comment]
This appears to be referencing TF2. You can click and drag screenshots into the dialog box below this message, or click the "selecting them" button below. Please include some of your system information with this issue report.

**Comment by HalfDeadTF2** [comment]
the default tf2 screenshots are .tga files, can't seem to add it in....

**Comment by HalfDeadTF2** [comment]
and there's another issue as well tho, whenever another team is doing the conga taunt, and as an engineer I do the rancho relaxo taunt, they appear invisible.....

**Comment by kisak-valve** [comment]
@HalfDeadTF2, if you're still seeing this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
