### ISSUE TITLE
Steam for Linux runs unworkably slow since update

### ISSUE THREAD

**Issue by thornate** [ValveSoftware/steam-for-linux#3653]
I recently installed Steam on my Linux box and it worked fine for a week or so. Yesterday it downloaded a large (200+MB) update and now it barely runs. None of the main pages (Store/Library/etc) load at all. When I click any button or menu, it takes minutes before any effect occurs.

I did a complete uninstall and reinstall, then it downloaded that update again. Even the initial splash screen is unworkably slow; it took about two minutes to have any effect from clicking the 'Login to an existing account' button, then I wasn't able to type anything into the text boxes.

When I look at the System monitor, there are three processes labelled 'Steam'. One of them is using 25 CPU pretty much constantly.

I'm running Ubuntu 14.10. I've tried this in both the normal Unity desktop and the steam-login desktop (https://github.com/thor27/steam-login/), which loads nothing but Steam.

Is anyone else getting this? How can I get Steam to run again?

Here is my system configuration:

CPU:

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 4
On-line CPU(s) list: 0-3
Thread(s) per core: 2
Core(s) per socket: 2
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 69
Model name: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
Stepping: 1
CPU MHz: 1306.101
CPU max MHz: 2600.0000
CPU min MHz: 800.0000
BogoMIPS: 3790.88
Virtualisation: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 3072K
NUMA node0 CPU(s): 0-3

UNAME info:

Linux nils 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:37:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Oxalin** [comment]
By any chance, could you launch steam from a terminal and see if it is outputting anything interesting?

**Comment by thornate** [comment]
Oh, In the time since I posted this, it resolved itself. From memory, it wasn't outputing anything particularly noteable.
