### ISSUE TITLE
Assassin´s Creed IV Black Flag Season Pass Steam client

### ISSUE THREAD

**Issue by Ajaxtomas** [ValveSoftware/steam-for-linux#3661]
I report bug about Season Pass of AC IV because i bought it and i have that DLC which i wanted but for DLC like Freedom Cry its showing me i dont own it in Steam and for Illustrious Pirates Pack and Guild of Rogues. Only show i own  Crusader and Death Vessel Pack.

**Comment by Plaque-fcc** [comment]
Is it specific at Steam for Linux only?

**Comment by MrSchism** [comment]
Are you certain you're reporting this in the right place?  I'm not sure how this involves linux at all...

**Comment by Ajaxtomas** [comment]
I have Windows 8.1 but how you can see this problem i think it will be not for operating system

**Comment by gdrewb-valve** [comment]
This is only for Linux-specific problems, please report your issue in the regular Steam forums.  There is no guarantee any of the non-Linux Steam team will see it here.

**Comment by MrSchism** [comment]
If you would, report this through appropriate channels.

**Comment by kisak-valve** [comment]
Closing as out-of-scope for this issue tracker.
