### ISSUE TITLE
Crash on startup-nvidia drivers

### ISSUE THREAD

**Issue by xicor333** [ValveSoftware/steam-for-linux#3662]
here is a link to my original support request: https://support.steampowered.com/view.php?ticketref=6082-QAKV-7211

essentially, if you install the nvidia drivers before installing AND updating steam, it will get stuck and crash on startup every attempt. the only fix i found for this is to uninstall both steam and the nvidia driver, reinstall steam, update, and then install the nvidia driver.

**Comment by kisak-valve** [comment]
Hello @xicor333, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
