### ISSUE TITLE
Steam overlay uses 100% of a single cpu core

### ISSUE THREAD

**Issue by Svenare** [ValveSoftware/steam-for-linux#3664]
i5 4670K CPU
Arch Linux
Only happens on beta client

**Comment by Plagman** [comment]
Can you detail how to reproduce this, what game you are running, etc?

**Comment by Svenare** [comment]
Using the beta client and playing Counter-Strike Global Offensive.

**Comment by kisak-valve** [comment]
Hello @Svenare, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
