### ISSUE TITLE
Friends can't join multi-chat

### ISSUE THREAD

**Issue by psychoraz** [ValveSoftware/steam-for-linux#3673]
I was chatting with Contact A using the steam overlay, and wanted to invite Contact B to the conversation.
Invited him, chat look became "multi" (with contact avatars/names on the right side), but only A was on the chat. The chat logged "B has been invited to chat" -or something like that-, but B never got the invite.

Tried it the  other way, creating the chat from Contact B conversation, this time Contact A never got the invite.

I was running steam beta for linux on arch, fully updated. A and B were using steam beta on windows. A and B are also friends.

**Comment by Uramekus** [comment]
Group chat/steam chat overhaul fixed this
