### ISSUE TITLE
Steam starts on the left monitor

### ISSUE THREAD

**Issue by ScoreUnder** [ValveSoftware/steam-for-linux#3674]
Even when the right monitor's workspace is focused, Steam starts on the left monitor. I don't want this because my left monitor is small and steam does not resize properly at smaller sizes.

**Comment by Honiix** [comment]
Same problem on Windows. My "Friend list" doesn't retain it's last position and always pop in my primary display.
When you say "left screen" for me it is the primary monitor. Is that the same for you?

**Comment by ScoreUnder** [comment]
My left monitor is apparently my primary monitor. I should set that to my right monitor.

Either way though, my complaint is more along the lines that steam chooses a monitor without remembering what monitor it was on last time, and that it overrides the window manager's default window placement (which would have been correct).

**Comment by kisak-valve** [comment]
Hello @ScoreUnder, @Honiix, are you still experiencing this issue on an up to date system?

If you are, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, which DE are you using?

**Comment by Honiix** [comment]
I don't have multimonitor anymore. Can't help sorry.

**Comment by ScoreUnder** [comment]
This seems to have been fixed for me. Thanks

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
