### ISSUE TITLE
Validating Game Files hangs

### ISSUE THREAD

**Issue by HansReich** [ValveSoftware/steam-for-linux#368]
Every time my client downloads an update it goes through the validating game files dialog and hangs at 100% for an inordinate amount of time.

![SteamBug100Percent](https://f.cloud.github.com/assets/1022782/30045/adaf9b12-4e04-11e2-9877-538e8cb02537.png)

Granted I'm on my laptop which isn't the fastest machine in the world but it was well over 30 minutes (It completed just before I started typing up this report at around 2:55pm). I also have steam on my windows partition on this laptop and have never had file validation take that long. I did not have any network issues while it was downloading or running that I was aware of (and I was browsing the internet the whole time so likely would have noticed if there had been any).

Running Ubuntu 12.10 with Unity on an Asus U56E laptop.

Sorry for the lack of any other relevant information but I had it running in the background and didn't notice the hang for a while so didn't see the lead-up or actual running of the validation. I just noticed that it was sitting at 100% after a bit and started to wonder why.

**Comment by kisak-valve** [comment]
Hello @HansReich, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
