### ISSUE TITLE
steam hangs on exit

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/steam-for-linux#3680]
After the Jan. 19th steam update (http://store.steampowered.com/news/15512/), steam hangs after you exit, with 100% cpu utilization.

stdout:
```
Installing breakpad exception handler for appid(steam)/version(1421694684)
process 884: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/threadtools.cpp (3633) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
Assert( Assertion Failed: Illegal termination of worker thread 'CFileWriterThread' ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/threadtools.cpp:3633

Installing breakpad exception handler for appid(steam)/version(1421694684)
crash_20150119160539_32.dmp[1055]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150119160539_32.dmp
```
It always produces that .dmp file when you exit.

system info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/bf99667cefda3ef4c0cd624c28fc38eb57c3783b/gistfile1.txt

**Comment by vimbaer** [comment]
With the latest update (Jan 23) this is fixed for me.

**Comment by jazztickets** [comment]
Still happens after the Jan. 23rd update.

**Comment by jazztickets** [comment]
Appears to be fixed in the Jan. 30th beta update.

**Comment by d14b3l** [comment]
Hi, I have similar issue. Steam hangs up after exit but fully utilizes only one thread - not the whole processor. It makes games unplayable though. I got i3-3220, gtx 660, external usb soundcard (audiotrak prodigy cube) and windows 8.1
