### ISSUE TITLE
vblank_mode=0 stopped working (forced vsync?) 

### ISSUE THREAD

**Issue by Esorable** [ValveSoftware/steam-for-linux#3683]
Yesterday out of no where my games are unable to get more than 60 fps. My fps in DoD:S, Tf2 and TFC keep getting stuck at 60 and can't get any more than that.

Yes wait for vsync is disabled. Checked million of times in all source and gold source games.

**Comment by Esorable** [comment]
I use nvidia optimus with bumblebee. The latest driver from the official repository and checked with xorg edgers and even reinstalled Ubuntu and tried again.

**Comment by eydee** [comment]
And while you're at it, please make it to work with Radeon as well.

**Comment by Esorable** [comment]
I fixed the issue. I basically reinstalled mesa libraries, and completely removed bumblebee and reinstalled it again and it suddenly started to use vblank_mode again. I'm sorry I didn't figure it out earlier.

**Comment by kisak-valve** [comment]
Closing as this appears to have been identified and resolved as a bumblebee issue.
