### ISSUE TITLE
"Enable streaming" checkbox on the settings panel is misplaced

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3685]
The checkbox appears a bit lower than it should and overlaps the separator line that should be below it.

To reproduce:
1. Start Steam
2. View -> Settings
3. Go to the In-Home Streaming tab
4. Observe the misplaced checkbox.

(It is in the right place under windows.)

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
