### ISSUE TITLE
The Witcher 2: Assassins of Kings Enhanced Edition couldn't launch on Fedora 21 x86_64

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#3698]
=== copy paste from console ===
Game update: AppID 20920 "The Witcher 2: Assassins of Kings Enhanced Edition", ProcID 10574, IP 0.0.0.0:0
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

(desktop-launcher:10576): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(desktop-launcher:10576): Gtk-WARNING *_: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character`}'
Gtk-Message: Failed to load module "pk-gtk-module"
*_ Message: window size should be 487x713
ERROR: ld.so: object '/home/mikhail/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR - eON failed to initialise!
Game removed: AppID 20920 "The Witcher 2: Assassins of Kings Enhanced Edition", ProcID 10574 

=== System Information ===
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.18.5-200.fc21.x86_64+debug
    X Server Vendor:  Fedora Project
    X Server Release:  11602901
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Desktop 

```
Driver Version:  3.0 Mesa 10.4.3
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x412
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                        50,9cm x 28,6cm  (58,3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31079 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  3815446 Mb
    Largest Free Hard Disk Block:  468062 Mb

Installed software:

Recent Failure Reports:

**Comment by not83** [comment]
I found later on the day after (after restarting) the game then worked.
After the beta update it was forever loading but later on it somehow worked

**Comment by kisak-valve** [comment]
Hello @NTMan, are you still experiencing this issue on an up to date system?

**Comment by NTMan** [comment]
Very old my report looks like affected by Kernel problem.
Details here: https://news.softpedia.com/news/Linus-Torvalds-to-Patch-the-Kernel-for-a-Witcher-2-Problem-471046.shtml

In nowadays prevents to run this game only the problem with the EULA confirmation: https://github.com/ValveSoftware/steam-for-linux/issues/5489

**Comment by kisak-valve** [comment]
Thanks for digging that up. Closing as resolved back in early 2015.
