### ISSUE TITLE
Message notification from blocked user

### ISSUE THREAD

**Issue by ltworf** [ValveSoftware/steam-for-linux#3701]
I have been added as a friend by a user, who was actually a scammer, so I blocked the user.

I've seen a notification of unread messages, but to open them I need to unblock the user.

I think messages from blocked users shouldn't generate notifications.

**Comment by gdrewb-valve** [comment]
Probably not a Linux-specific issue.

**Comment by kisak-valve** [comment]
Hello @ltworf, have you seen this issue in recent history?

**Comment by ltworf** [comment]
Haven't used steam's friends thing in a long time, I don't know.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing presumed fixed some time ago.
