### ISSUE TITLE
Steam not running on RPM based distros and asking about dependencies.

### ISSUE THREAD

**Issue by w-e-g** [ValveSoftware/steam-for-linux#3702]
After updating to latest Beta (released 30th December)  on Linux on RPM-based distro (ROSA Linux) I can't run Steam. When I try to run Steam I see a message:

Steam needs to install these additional packages:
curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for %user:

Same situation in Mageia as I can understand (see http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/204121161638599509 message from user DamonLinuxTerror).

Previous version of Steam Beta worked fine. Can you help me?

Thank you in advance.

**Comment by Oxalin** [comment]
Neither DamonLinuxTerror or you are saying if you tried to install manually the missing dependencies reported by steam. Are all the dependencies already installed?

**Comment by w-e-g** [comment]
Of course. Otherwise I can't run Steam earlier. 

Nota bene: after updating Steam yesterday — I was able to run Steam, but asking dependencies still appears. 

It looks like:
Steam needs to install these additional packages: 
        curl, python-apt, xterm, xz-utils, zenity, libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for roger: 
sudo: apt-get: command not found

sudo: apt-get: command not found
Press return to continue:

After pressing Enter Steam running and working fine.

**Comment by Plaque-fcc** [comment]
apt-get on a RPM-based system?

**Comment by w-e-g** [comment]
Of course no. I think apt-get calling is hardcoded into Steam.

**Comment by Tele42** [comment]
Is there an installed script called steamdeps from steam's package? What is the behaviour if you remove/rename that file.

**Comment by w-e-g** [comment]
On any modifying/deleting of steamdeps script, Steam run updater and restore all modified/removed files. Terminal window with asking dependencies still appears of course.

**Comment by Tele42** [comment]
That doesn't sound right, what is the absolute path to steamdeps on your system?

**Comment by w-e-g** [comment]
I don't understand you correctly and I try to remove files in $USER/.local/share/Steam (steamdeps.txt and bin_steamdeps.py). My fault, sorry.

If I rename/move /usr/bin/steamdeps file — Steam running without any errors or messages.

**Comment by kisak-valve** [comment]
Hello @w-e-g, are you still experiencing this issue on an up to date system? This issue should be brought to the attention of the package maintainer(s) for the steam package on Rosa Linux.

**Comment by kisak-valve** [comment]
Closing pending feedback.
