### ISSUE TITLE
Black Steam window and unresponsive UI when exiting BigPicture

### ISSUE THREAD

**Issue by thetargos** [ValveSoftware/steam-for-linux#3703]
I just noticed that exiting Big Picture from the option of return to desktop caused the main Steam window to remain black, only the menubar is visbile and the cursor turns into a hand as if to click a hyperlink. Nothing in the UI is responsive to user input, only option is to hard kill steam with killall -9 steam.

Relevant information (as per system information):
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.18.3-201.fc21.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11603000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 346.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 34.88" x 19.61"  (40.00" diag)
                                            88.6cm x 49.8cm  (101.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  11913 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  es_MX.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  153572 Mb
    Largest Free Hard Disk Block:  33427 Mb
    
Installed software:
    
Recent Failure Reports:
    Wed Feb  4 20:45:42 2015 GMT: file ''/tmp/dumps/crash_20150204144532_2.dmp'', upload yes: ''CrashID=bp-c0fa2a1e-a50e-4476-9b91-a9fe02150204''
    
I corroborated this issue twice already.

**Comment by Plagman** [comment]
Can you try yesterday's client Beta to see if this problem is solved for you?

**Comment by thetargos** [comment]
I notice dthat Steam updated today, trying BP for a while and exit work fine again.

**Comment by Plagman** [comment]
Thanks for confirming!
