### ISSUE TITLE
Steam client stop render properly after VT switch

### ISSUE THREAD

**Issue by Ghost99** [ValveSoftware/steam-for-linux#3704]
After switching VT (ctrl+alt+f1, ctrl+alt+f2 etc) Steam windows stop render properly, stop redraw itself.
Steps to reproduce:
1. Start Steam, wait it fully start
2. Press Ctrl+Alt+F1
3. Press Ctrl+Alt+F7, to switch back to your main session
4. Rendering is broken, but all other windows renders properly

Unfortunately this happens from time to time, so you probably should try this few times.
Other windows (even with running games) work and renders fine. Only Steam windows stop render properly.

System: Gentoo x86_64
Drivers: x11-drivers/nvidia-drivers-343.36

**Comment by Ghost99** [comment]
I can reproduce bug only with Marco, the fork of Metacity window manager for MATE. With kwin, modern window manager for KDE, rendering work right after VT switch.

**Comment by kisak-valve** [comment]
Hello @Ghost99, are you still experiencing this issue on an up to date system? This reads like a long-standing nVidia proprietary driver quirk.

**Comment by Ghost99** [comment]
Hello,
No, latest Steam client renders properly with marco-1.18.2 and nvidia-drivers-387.34 after VT switch.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
