### ISSUE TITLE
Steam crash before showing login window (Ubuntu 14.10)

### ISSUE THREAD

**Issue by timonoj** [ValveSoftware/steam-for-linux#3706]
Hi guys, 

I'm having a laptop with Nvidia 755m SLI. Drivers (nvidia-331-updates) seem to work fine for other 3D tasks, but Nvidia will crash before even showing the login window. If I install xserver-xorg-video-nouveau driver instead, I get to see the first window, where I'm asked to either create a new account, using a PSX account or using an existing account. After clicking an existing account, the window disappears to never come back. With nvidia I don't even get to see that initial window. Running Elementary OS Freya, based on Ubuntu 14.10, packages up to date. Here's the console output:

$ steam
Running Steam on elementary os 0.3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150123134624)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
[0208/120037:ERROR:nss_util.cc(1018)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150123134624)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
[0208/120038:ERROR:renderer_main.cc(227)] Running without renderer sandbox
[0208/120038:ERROR:renderer_main.cc(227)] Running without renderer sandbox
assert_20150208120035_1.dmp[4807]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150208120035_1.dmp
/home/timonoj/.local/share/Steam/steam.sh: line 736:  4751 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[0208/120038:WARNING:content_browser_client.cc(499)] No browser info matching frame process id 1 and routing id 1
[0208/120038:WARNING:content_browser_client.cc(499)] No browser info matching frame process id 2 and routing id 1
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
assert_20150208120035_1.dmp[4807]: Finished uploading minidump (out-of-process): success = yes
assert_20150208120035_1.dmp[4807]: response: CrashID=bp-b83b6f6f-631a-4296-8725-f7ecc2150207
assert_20150208120035_1.dmp[4807]: file ''/tmp/dumps/assert_20150208120035_1.dmp'', upload yes: ''CrashID=bp-b83b6f6f-631a-4296-8725-f7ecc2150207''

Any ideas? I tried this also on normal Kubuntu 14.10, and still get the same error.

**Comment by timonoj** [comment]
Additional comment: I think it might be related to the NSS libraries, but not sure how to get them in Ubuntu. I saw the Fedora instructions, but package names don't match apparently :(

**Comment by timonoj** [comment]
Additional comment: I think it might be related to the NSS libraries, but not sure how to get them in Ubuntu. I saw the Fedora instructions, but package names don't match apparently :(

EDIT: Well maybe it wasn't that. Found/installed libnss3:i386 (as I already had libnss3), and that error no longer shows, but I still get the same crash:

timonoj@Timo-PC:~$ steam
Running Steam on elementary os 0.3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150123134624)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150123134624)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
Installing breakpad exception handler for appid(steamwebhelper)/version(1422020784)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1422054110)
Installing breakpad exception handler for appid(steam)/version(1422054110)
[0208/121948:ERROR:renderer_main.cc(227)] Running without renderer sandbox
[0208/121948:ERROR:renderer_main.cc(227)] Running without renderer sandbox
assert_20150208121945_1.dmp[3025]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150208121945_1.dmp
/home/timonoj/.local/share/Steam/steam.sh: line 736:  2967 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[0208/121948:WARNING:content_browser_client.cc(499)] No browser info matching frame process id 1 and routing id 1
[0208/121948:WARNING:content_browser_client.cc(499)] No browser info matching frame process id 2 and routing id 1
Requested Force create but SharedObjectMutex already created
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
assert_20150208121945_1.dmp[3025]: Finished uploading minidump (out-of-process): success = yes
assert_20150208121945_1.dmp[3025]: response: CrashID=bp-235ad0aa-e750-4d6a-9d6b-a46812150207
assert_20150208121945_1.dmp[3025]: file ''/tmp/dumps/assert_20150208121945_1.dmp'', upload yes: ''CrashID=bp-235ad0aa-e750-4d6a-9d6b-a46812150207''

**Comment by Oxalin** [comment]
I had a similar error on Archlinux. I had to run the following to identify what was still missing:
$ cd ~/.local/share/Steam/ubuntu12_32
$ LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}" ldd $(file *|sed '/ELF/!d;s/:.*//g')|grep 'not found'|sort|uniq

I don't know if this could help you to identify what could still be missing.

**Comment by kisak-valve** [comment]
Hello @timonoj, are you still experiencing this issue on an up to date system?

**Comment by timonoj** [comment]
Hi...Not anymore. But this was reported on a system from 2014, and we're at
2018...Even the machine is different.

**Comment by kisak-valve** [comment]
Thanks, closing.
