### ISSUE TITLE
No focus in PayPal login window attempting to add to Steam Wallet

### ISSUE THREAD

**Issue by efflandt** [ValveSoftware/steam-for-linux#3709]
While attempting to add funds to Steam Wallet and selecting MyPayPal (used previously some time ago) from Linux Steam beta client, at some point it takes you to a window to log into PayPal. However, that page is unresponsive with no way to get focus to the text fields to enter login information (mouse clicks do not work on anything on the page, including any links), therefore, no way to log into PayPal to authorize the payment. This has been a problem since at least November 2014, including 64-bit Ubuntu 12.04 (14.04.1 was fresh installed Jan 2015). Before it switched from old style PayPal login to new style, only part of that page would load, so maybe something on the page does not load completely in Steam beta client.

That all works fine using Linux Firefox while logged into store.steampowered.com, so it does not appear to be any problem with PayPal, it is a problem with the Steam beta client.

PS: Could not figure out how to do code block below from markdown instructions

> Processor Information:
>    Vendor:  GenuineIntel
>    CPU Family:  0x6
>    CPU Model:  0x25
>    CPU Stepping:  0x2
>    CPU Type:  0x0
>    Speed:  3201 Mhz
>    4 logical processors
>    2 physical processors
>    HyperThreading:  Supported
>    FCMOV:  Supported
>    SSE2:  Supported
>    SSE3:  Supported
>    SSSE3:  Supported
>    SSE4a:  Unsupported
>    SSE41:  Supported
>    SSE42:  Supported
> 
> Network Information:
>    Network Speed:  
> 
> Operating System Version:
>    Ubuntu 14.04.1 LTS (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.13.0-45-generic
>    X Server Vendor:  The X.Org Foundation
>    X Server Release:  11501000
>    X Window Manager:  Compiz
>    Steam Runtime Version:  steam-runtime-release_2015-01-06
> 
> Video Card:
>    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2
> 
>    Driver Version:  4.5.0 NVIDIA 346.35
>    OpenGL Version: 4.5
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x10de
>    DeviceID:  0x1380
>    Number of Monitors:  1
>    Number of Logical Video Cards:  1
>    Primary Display Resolution:  1920 x 1080
>    Desktop Resolution: 1920 x 1080
>    Primary Display Size: 45.28" x 25.59"  (51.97" diag) `actually 32" diagonal`
>                                            115.0cm x 65.0cm  (132.0cm diag)
>    Primary Bus: PCI Express 16x
>    Primary VRAM: 2048 MB
>    Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>    Audio device: Intel IbexPeak HDMI
> 
> Memory:
>    RAM:  7912 Mb
> 
> Miscellaneous:
>    UI Language:  English
>    LANG:  en_US.UTF-8
>    Microphone:  Not set
>    Total Hard Disk Space Available:  423125 Mb
>    Largest Free Hard Disk Block:  215471 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

**Comment by kisak-valve** [comment]
If anyone happens to be making a purchase using Paypal, please retest this issue report using the [2017-05-09](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1309830331020534164) steam beta client.

**Comment by kisak-valve** [comment]
Closing as per the 2017-05-09 beta notes.
