### ISSUE TITLE
Game Downloads Abort After 3-5 seconds of activity

### ISSUE THREAD

**Issue by RecceDG** [ValveSoftware/steam-for-linux#3718]
This has been going on for a while now.

A game in the download queue will connect, download for 3-5 seconds, then silently abort, heading to the "Update Required (Not Queued)" queue.

Changing download site and/or throttling speed makes no difference, although subjectively outside of NA servers seem like they persist slightly longer.

Nothing is reported to the console as to why the download was aborted.

The part of the code that decides to abort the DL is broken or overly aggressive.

**Comment by SigSegFault** [comment]
One year later, 0 activity on the issue, while it still persists. Very nice.

**Comment by sharifzadesina** [comment]
Same problem!

**Comment by kisak-valve** [comment]
Hello, @RecceDG, @SigSegFault, @sharifzadesina, are any of you still experiencing this issue? If you are, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please copy `~/.local/share/Steam/logs/content_log.txt` to a gist and include a link to it as well.

**Comment by kisak-valve** [comment]
Closing pending feedback.
