### ISSUE TITLE
Cannot Install Steam from .deb if AMD Catalyst drivers are installed

### ISSUE THREAD

**Issue by RecceDG** [ValveSoftware/steam-for-linux#3719]
In order to successfully install Steam from Ubuntu Software Center of from a directly downloaded .deb, the Catalyst drivers must be uninstalled, the Open Source drivers installed, Steam installed (it will install to completion) then Catalyst re-installed.

Once initial installation is complete the client works fine.

**Comment by gdrewb-valve** [comment]
This seems like a duplicate.  What failures are you seeing?

**Comment by RecceDG** [comment]
It would install from the .deb just fine, but running steam would complain about missing files and then segfault.
Having figured out how to get it installed, I can no longer reproduce the actuall errors.

To see for yourself:

1. Find a machine with a reasonably recent AMD graphics card (mine is an HD 7870)
2. Install Ubuntu 14.04 LTS 64 bit
3. Install Catalyst from .deb
4. Install Steam from .deb
5. Run steam from a console, and watch the fireworks.

**Comment by johnv-valve** [comment]
This should be fixed with the latest steam package (1.0.0.50) available from steampowered.com
