### ISSUE TITLE
Steam crashes when trying to select all type in add non-Steam games dropdown menu

### ISSUE THREAD

**Issue by minecraft2048** [ValveSoftware/steam-for-linux#3720]
How to reproduce:
1. Press Add a game
2. Add a non-Steam games
3. Browse
4. Select home directory
5. Change file type dropdown menu to all files

It crashes there

System specs:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2501 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-45-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Openbox
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 630M/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.113
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0xde9
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 18.19" x 10.24"  (20.87" diag)
                                        46.2cm x 26.0cm  (53.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3839 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  148241 Mb
    Largest Free Hard Disk Block:  14392 Mb

Installed software:

Recent Failure Reports:
    Tue Feb 17 10:18:51 2015 GMT: file ''/tmp/dumps/assert_20150217171819_47.dmp'', upload yes: ''CrashID=bp-b90272e9-fcd9-491f-9a9a-b02252150217''
    Tue Feb 17 10:23:23 2015 GMT: file ''/tmp/dumps/assert_20150217162432_1.dmp'', upload yes: ''CrashID=bp-cc999e78-5b7a-465d-ac21-9b83e2150217''
    Tue Feb 17 10:31:40 2015 GMT: file ''/tmp/dumps/assert_20150217173129_23.dmp'', upload yes: ''CrashID=bp-754622bf-9125-47dd-9e4e-9d72d2150217''
    Tue Feb 17 10:32:57 2015 GMT: file ''/tmp/dumps/assert_20150217172323_1.dmp'', upload no: ''Couldn't connect to server''
    Tue Feb 17 10:35:42 2015 GMT: file ''/tmp/dumps/assert_20150217173452_1.dmp'', upload yes: ''CrashID=bp-d14a2256-f5be-41ee-8832-7ba4e2150217''
    Tue Feb 17 10:40:22 2015 GMT: file ''/tmp/dumps/assert_20150217173907_1.dmp'', upload yes: ''CrashID=bp-8f3ed730-5512-4524-bd89-0e88c2150217''

Terminal log: https://gist.github.com/minecraft2048/3bf58244ce9053a5f195

**Comment by kisak-valve** [comment]
Hello @minecraft2048, are you still experiencing this issue on an up to date system?

**Comment by minecraft2048** [comment]
Ahh, this bug is so old that I have changed distro and laptop twice while waiting for any followup to this bug... anyway there is no crashes anymore when I try to follow that reproduction step
