### ISSUE TITLE
"Steam Streaming Client Exited Unexpectedly (2)"  Message gets stuck.

### ISSUE THREAD

**Issue by Gordon01** [ValveSoftware/steam-for-linux#3721]
Running the latest build of SteamOS with the latest client update. 
If something goes wrong (i.e. failed inhome translation) "Steam Streaming Client Exited Unexpectedly (2)", message pops up and the ok button does nothing. 
Pressing any button does not help. 
I have to reboot the system or kill steam from another tty.

**Comment by kisak-valve** [comment]
Hello @Gordon01, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
