### ISSUE TITLE
In-home streaming crashes with hardware acceleration on the client side turned on

### ISSUE THREAD

**Issue by Rovanion** [ValveSoftware/steam-for-linux#3723]
Running on 64-bit Ubuntu 14.04 on an Intel(R) Core(TM)2 Duo CPU E6750  @ 2.66GHz with an Intel 82Q35 Express Integrated Graphics.

Here follows the crash dump: https://www.dropbox.com/s/qzknzrnleqdm55j/crash_20150219211425_2.dmp?dl=0

Here's the steam_log: http://paste.ubuntu.com/10313355

And the steam_stdout: http://paste.ubuntu.com/10313358

**Comment by kisak-valve** [comment]
Hello @Rovanion, your backtrace indicates swrast_dri.so was being used. Swrast is mesa's slower cpu renderer and no video acceleration was being used. Separately from that, the Q35 chipset is Intel third generation graphics and that has no h264 hardware acceleration available.
