### ISSUE TITLE
Error causing multiple games to crash: ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by MajorLunaC** [ValveSoftware/steam-for-linux#3724]
When running various free Steam games for Linux, I get an error, that crashes the game (NOT Steam), along the lines of:

ERROR: ld.so: object 'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

Note that TF2, Robocraft, Fistful of Frags, Double Action and pretty much all the other available free games for Linux run perfectly fine for me.

*Gear Up Crash: https://gist.github.com/MajorLunaC/89df29a0f17348097e97
Says Gear Up is still running when I try to exit Steam. No such processes are listed as running in 'ps'.

*Dwarfs F2P Crash: https://gist.github.com/MajorLunaC/601bf26a60997d004b30
Nothing even shows up when trying to run it.

*Dota 2 -- Bot Match Crash: https://gist.github.com/MajorLunaC/7c229db23c3914d4a8e9
I can start up the game fine, but when trying for a Bot Match, the map loads completely ("Loading..." finishes), and then it just barely starts showing in-game images (more of a scrambled mess) and then crashes.

*Dota 2 -- Training (1st mission) Crash: https://gist.github.com/MajorLunaC/32721c0ae6e724c60174
Finishes loading the training map and tries to start the in-game graphics, and crashes.

*Dota 2 -- Normal Game (unranked via Matchmaking) Crash: https://gist.github.com/MajorLunaC/f3a63b7ce887c603f70e
It finishes loading a map, I see some blurred images of some buildings with a black background, then crash.

*System Info: https://gist.github.com/MajorLunaC/955597ed7a8b4a238bb2

Note: A similar error is reported in another repository having to do with Steam, but the offered solutions don't seem to help in these cases: https://github.com/GhostSquad57/Steam-Installer-for-Wheezy/issues/37

**Comment by gdrewb-valve** [comment]
Preload messages are expected in many cases and that may not be the actual issue, but the crash is definitely something wrong.

**Comment by tpruzina** [comment]
preload messages are to be expected, since they mix both 64/32 bit libpraries =32bit apps will complain about 64bit libs and vice versa).

**Comment by gracicot** [comment]
Happen with Torchlight 2 on Arch 64 bit

**Comment by kisak-valve** [comment]
Closing as this is a non-issue. When steam launches a game, it preloads a 32 bit and 64 bit variant of the steam overlay. One will silently work, while the other is non-fatally rejected with an error message.

The game crashes you were seeing were unrelated to these messages and most likely due to using a version of mesa that predates the release of the intel chipset in use.
