### ISSUE TITLE
tf2: if the mvm loot review popup is closed, loot reveal stops

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#3725]
When finishing a mann up mission, a popup shows the earned loot for all players, and the stuff is revealed one-by-one. If I close the popup (eg. to collect the remaining money), and reopen it, the reveal doesn't continue.

**Comment by kisak-valve** [comment]
Hello @mtmkls, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If you're able to reproduce this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
