### ISSUE TITLE
Steam segmentation fault before showing login

### ISSUE THREAD

**Issue by timonoj** [ValveSoftware/steam-for-linux#3727]
Hi guys,

I'm having this nagging issue...Through a wide variety of distros. So far I tested Elementary OS, Ubuntu, Kubuntu and Cinnamon. On all of them I fail to get to see the login screen, it always crashes on a segmentation fault. 

I've seen mentioned multiple times to do the first run on non propietary drivers, but also nouveau gives me segmentation fault error. Otherwise I've been trying with nvidia-331-updates.

Lenovo Y510P, Nvidia 755M SLI.

Any suggestion? Steam is the only thing that consistently crashes on this lenovo. My previous Dell laptop with an old nvidia 8600M GT runs steam perfectly.

**Comment by tpruzina** [comment]
Same here, started today.

When I do steam --reset, steam comes up, but when I close it and relounch, segfault happens.

/home/tomas/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
/home/tomas/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
Running Steam on gentoo  64-bit
/home/tomas/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150218153139)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424273499)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150218153139)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424305157)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1424305157)
Installing breakpad exception handler for appid(steam)/version(1424305157)
assert_20150221162622_1.dmp[15960]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150221162622_1.dmp
/home/tomas/.local/share/Steam/steam.sh: line 757: 15916 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20150221162622_1.dmp[15960]: Finished uploading minidump (out-of-process): success = yes
assert_20150221162622_1.dmp[15960]: response: CrashID=bp-a758e044-76d4-423e-b57d-fc7862150221
assert_20150221162622_1.dmp[15960]: file ''/tmp/dumps/assert_20150221162622_1.dmp'', upload yes: ''CrashID=bp-a758e044-76d4-423e-b57d-fc7862150221''

**Comment by kisak-valve** [comment]
Hello @timonoj, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
