### ISSUE TITLE
Cannot start starbound from steam client

### ISSUE THREAD

**Issue by khers** [ValveSoftware/steam-for-linux#3733]
I am running Ubuntu 14.10 with KDE.

Trying to start starbound from the steam client fails.  I do not get an error message (I don't even see the Preparing to launch Starbound... window).  If I run the starbound x86_64 binary from the command line, the game wil start fine.  Verification of files completes fine and everything is up to date.

The steam support channel suggested I report it here (or install Ubuntu 12.10 :/ )

**Comment by Plagman** [comment]
Hi,

Looking at the game they added a Qt5-based launcher, with a bundle of libs to support it, but it seems to be missing a few. libxslt is the one omission that is causing it to fail to launch at the moment, but there might be others. This would need to be reported back to the developers.

**Comment by khers** [comment]
Thanks, I will report that to chuckle fish.

**Comment by Skiski** [comment]
You can solve this by going into the starbound folder (steam/SteamApps/common/Starbound) then the linux64 folder. Then you need to edit "launch_launcher.sh" and replace the line about "./launcher" by "./starbound". You can find more details in the steam forum of the game.

**Comment by kisak-valve** [comment]
Closing because it appears the launcher in question is no longer used.
