### ISSUE TITLE
Add GLX_MESA_query_renderer support to Steam to fix primary VRAM detection

### ISSUE THREAD

**Issue by Oxalin** [ValveSoftware/steam-for-linux#3734]
Hi,
GLX_MESA_query_renderer is now available since Mesa 10.3. Would it be possible to add this extension to Steam Linux client so it can correctly report the primary VRAM for drivers implementing it? Opens source Intel, Nouveau (Nvidia), Radeon and swrast drivers expose this extension. While it doesn't fix the problem for proprietary drivers (AMD's Catalyst and Nvidia's Geforce), it will be a first step to:
- Support the extension;
- Encourage AMD and NVidia in implementing their equivalent.

Cheers!
Alexandre

**Comment by Oxalin** [comment]
By the way, it would fix partially https://github.com/ValveSoftware/steam-for-linux/issues/1311

**Comment by Stebs** [comment]
BTW, there is an incoming patch for glxinfo for querying GLX_MESA_query_renderer:
https://www.mail-archive.com/mesa-dev%40lists.freedesktop.org/msg73416.html

So maybe another way to implement this, is just shipping with the newest (or patched) glxinfo?

**Comment by Oxalin** [comment]
Stebs: This patch enables glxinfo to query the GLX_MESA_query_renderer for its own needs if the GL extension is available. Mesa already exposes the extension to whatever application asks for it.

In other words, Valve, or any other application, can use this patch to code something really (I mean REALLY) similar to get the needed details. It should need only a couple of minutes to implement this check directly in Steam.

**Comment by gulafaran** [comment]
so still no news on this?

**Comment by hanetzer** [comment]
christ. Its getting to the end of 2017 and my sapphire rx480 8gb gpu is still being detected as 256mb of vram as mentioned in #1311
Is there any workaround?

**Comment by kisak-valve** [comment]
Hello @Oxalin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
