### ISSUE TITLE
steam wuld not start missing lib after nvidia driver update unable to find lib that are installed  

### ISSUE THREAD

**Issue by matsaa93** [ValveSoftware/steam-for-linux#3739]
the problem started when i updated from nvidia driver 346.35 to 346.47 
when trying to start steam it wont start only giving oute that libnvidia-tls.so.346.35
libnvidia-glcore.so.346.35 is missing but sinse the driver has updated it is becouse it will not recognice the libs when the lib name is libnvidia-tls.so.346.47
libnvidia-glcore.so.346.47
have tryed to reinstall steam did not work and the driver is installed correctly i started stem with terminal and giving this oute put 

``` console
§: steam
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libnvidia-tls.so.346.35
libnvidia-glcore.so.346.35
[2015-02-26 23:57:54] Startup - updater built Feb 25 2015 20:37:03
[2015-02-26 23:57:54] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1424971303)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1424971303)
[2015-02-26 23:57:54] Checking for update on startup
[2015-02-26 23:57:54] Checking for available updates...
Installing breakpad exception handler for appid(steam)/version(1424971303)
[2015-02-26 23:57:54] Download skipped: /client/steam_client_publicbeta_ubuntu12 version 1424971303, installed version 1424971303
[2015-02-26 23:57:54] Nothing to do
[2015-02-26 23:57:54] Verifying installation...
[2015-02-26 23:57:54] Performing checksum verification of executable files
[2015-02-26 23:57:55] Verification complete
[2015-02-26 23:57:56] Shutdown
Installing breakpad exception handler for appid(steam)/version(1424971303)
/home/steinfejll/.steam/steam.sh: line 765: STEAMSCRIPT_OUTOFDATE: unbound variable
```

sow wat to do ?

**Comment by gdrewb-valve** [comment]
The unbound variable is an issue but for the NVIDIA driver problem you should also contact NVIDIA.

**Comment by Tele42** [comment]
This sounds like nvidia provided 32bit libraries did not get updated when you updated nvidia's driver. This is not valve's problem to solve.

**Comment by matsaa93** [comment]
yes they did if you red i sed they changed name from libnvidia*.so.346.35 to libnvidia*.so.346.47 and steam did not recognice sow it is not the driver because i have only problem with steam and sow i sed steam cod not recocnice the files ven they changed name after opdate i cheched iin /usr/lib/i366-linux-gnu/ for the files and they are there sow it is not the driver  the driver installed the filkes correctly 
if i try to trick ubuntu with sym.link it gests an gl error tat the wersion that you are running is not 346.35 bot 346.47 thet is because i tryed to change the name then but i can contact nvidia but i dont think it is the driver since this was the fist driver working correctly vith my graphical card gtx 970

**Comment by matsaa93** [comment]
i found the problem it was and libgl.so.346.35 file in the stem folder that have been placed there for some reason.
