### ISSUE TITLE
Left 4 Dead 2 immediately crashes on startup

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3740]
Output of the steam client run from the command line.  Note: this is on Debian Sid.  Other games run just fine.

Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
[2015-02-26 23:09:13] Startup - updater built Feb 20 2015 17:37:42
[2015-02-26 23:09:13] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1424485524)
Installing breakpad exception handler for appid(steam)/version(1424485524)
[2015-02-26 23:09:13] uninstalled manifest found in /home/wls/.local/share/Steam/package/steam_client_publicbeta_ubuntu12 (1).
[2015-02-26 23:09:13] Found pending update
[2015-02-26 23:09:13] Installing update...
[2015-02-26 23:09:13] Extracting package...
[2015-02-26 23:09:21] Installing update...
[2015-02-26 23:09:21] Cleaning up...
[2015-02-26 23:09:21] Update complete, launching Steam...
[2015-02-26 23:09:21] Shutdown
Restarting Steam by request...
Running Steam on debian 8 64-bit
STEAM_RUNTIME has been set by the user to: /home/wls/.steam/root/ubuntu12_32/steam-runtime
[2015-02-26 23:09:22] Startup - updater built Feb 25 2015 20:37:03
[2015-02-26 23:09:22] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
[2015-02-26 23:09:22] Verifying installation...
[2015-02-26 23:09:22] Verification complete

(steam:6877): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:6877): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character`}'
Installing breakpad exception handler for appid(steam)/version(1424971303)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(steamwebhelper:6882): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steamwebhelper:6882): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character`}'
Installing breakpad exception handler for appid(steamwebhelper)/version(20150225203700)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424896620)
[0226/230923:ERROR:nss_util.cc(1018)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150225203700)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424971303)
Installing breakpad exception handler for appid(steamwebhelper)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)

*\* (steam:6877): WARNING **: Unknown device type 14

*\* (steam:6877): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type
Installing breakpad exception handler for appid(steam)/version(1424971303)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Installing breakpad exception handler for appid(steam)/version(1424971303)
Adding licenses for the following package(s): 0, 36, 37, 2481, 7877, 13054, 17222, 39747, 54974, 55143, 55144, 56320, 58580, 58582, 58584, 58590, 60574, 60859, 60860, 60861, 62024
roaming config store loaded successfully - 602 bytes.
migrating temporary roaming config store
ExecCommandLine: ""/home/wls/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1424971303)
System startup time: 3.59 seconds
Generating new string page texture 70: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 71: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 72: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 73: 32x256, total string texture memory is 540.67 KB
[0226/230927:ERROR:renderer_main.cc(227)] Running without renderer sandbox
Running Steam on debian 8 64-bit
STEAM_RUNTIME has been set by the user to: /home/wls/.steam/root/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/wls/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0226/230929:ERROR:renderer_main.cc(227)] Running without renderer sandbox
Generating new string page texture 88: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 99: 128x256, total string texture memory is 671.74 KB
Generating new string page texture 100: 384x256, total string texture memory is 1.06 MB
Generating new string page texture 101: 256x256, total string texture memory is 1.33 MB
Generating new string page texture 102: 128x256, total string texture memory is 1.46 MB
Generating new string page texture 127: 2048x256, total string texture memory is 3.56 MB
Generating new string page texture 128: 1024x256, total string texture memory is 4.60 MB
Installing breakpad exception handler for appid(steam)/version(1424971303)
Game update: AppID 550 "Left 4 Dead 2", ProcID 7053, IP 0.0.0.0:0
ERROR: ld.so: object '/home/wls/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/wls/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 7056 != 7055, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/wls/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/wls/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 8
Using breakpad crash handler
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198114500194 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198114500194
Did not detect any valid joysticks.

(hl2_linux:7058): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(hl2_linux:7058): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character`}'
[0226/230938:ERROR:resource_bundle.cc(411)] Failed to load /home/wls/.local/share/Steam/SteamApps/common/Left 4 Dead 2/cef_gtk.pak
Some features may not be available.
[0226/230938:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
Querying for subscribed files
IDirect3DDevice9::Create: BackBufWidth: 640, BackBufHeight: 480, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: YES
BinkOpen( /home/wls/.local/share/Steam/SteamApps/common/Left 4 Dead 2/left4dead2/media/valve.bik )
ConVarRef volume doesn't point to an existing ConVar
Failed to open BO for returned DRI2 buffer (2560x1440, dri2 back buffer, named 17).
This is likely a bug in the X Server that will lead to a crash soon.
ERROR: ld.so: object '/home/wls/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
assert_20150226230936_1.dmp[7082]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150226230936_1.dmp
/home/wls/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67:  7058 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2", ProcID 7058 
assert_20150226230936_1.dmp[7082]: Finished uploading minidump (out-of-process): success = yes
assert_20150226230936_1.dmp[7082]: response: CrashID=bp-c2385e9a-322b-4024-96fc-d69732150226
assert_20150226230936_1.dmp[7082]: file ''/tmp/dumps/assert_20150226230936_1.dmp'', upload yes: ''CrashID=bp-c2385e9a-322b-4024-96fc-d69732150226''
pid 7082 != 7081, skipping destruction (fork without exec?)

**Comment by amorphine** [comment]
Same issue.

`warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
warning: Unknown nb_ctl request:  4
or material for particle\smokesprites_0015.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fastsidesprites\fastsidesprite128.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fastsidesprites\fastsidesprite128.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fire_burning_character\fire_burning_character_modulate.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\particle_flares\particle_flare_004b_mod.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\particle_flares\particle_flare_004b_mod_noignorez.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fire_tiled_1\fire_tiled_1.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\indicators\card_locator_generic.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\banner_beam.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\particle_flares\particle_flare_002.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\explosion_smoke_2048\explosion_smoke_2048.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_splash.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_splash.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_splash.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_long.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_long.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water_drop_long.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp1_warp.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp1_warp.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\smoke1\dust_motes.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\smoke1\dust_motes.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp1_warp.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp1_warp.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water\water_beam_01_warp_oriented.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\water\watersplash_001a_refract.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for effects\fire_embers3.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp4_warp_noz.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\smokesprites_0015.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp4_warp_noz.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\smokesprites_0015.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fastsidesprites\fastsidesprite128.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\vistasmokev1\vistasmokev2.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\warp4_warp_noz.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\smokesprites_0015.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\fastsidesprERROR: ld.so: object '/home/amorphine/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20161012203044_1.dmp[14872]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161012203044_1.dmp
/home/amorphine/.local/share/Steam/steamapps/common/Left 4 Dead 2/./hl2.sh: строка 72: 14837 Ошибка сегментирования                   (подготовлен дамп ядра) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2", ProcID 14837 
No cached sticky mapping in ActivateActionSet.crash_20161012203044_1.dmp[14872]: Finished uploading minidump (out-of-process): success = yes
crash_20161012203044_1.dmp[14872]: response: CrashID=bp-30646cb4-073e-4fef-a7c7-9bca82161012
crash_20161012203044_1.dmp[14872]: file ''/tmp/dumps/crash_20161012203044_1.dmp'', upload yes: ''CrashID=bp-30646cb4-073e-4fef-a7c7-9bca82161012''
pid 14872 != 14871, skipping destruction (fork without exec?)
`
link to dump-file [https://www.dropbox.com/s/kw8w4s33f79mj0g/crash_20161012203044_1.dmp?dl=0](url)

**Comment by kisak-valve** [comment]
Hello @amorphine, if you are still experiencing this issue on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
