### ISSUE TITLE
Steam account shared between Windows user accounts

### ISSUE THREAD

**Issue by LinAGKar** [ValveSoftware/steam-for-linux#3747]
It seems that on Windows Steam accounts are shared between user account i.e. if you log to in to an account in Steam and then switch account in Windows you will still be logged in to the same account in Steam. This does no seem to happen under Linux.

**Comment by gdrewb-valve** [comment]
When you say "switch account in Windows" do you mean fast user swiching?  That doesn't log the other user out so it's expected that the running Steam instance would not be affected.  Existing Steam and then starting Steam with the new user should use the new user's info.  That should match the Linux behavior.

**Comment by LinAGKar** [comment]
I mean logging out and logging in on a different account. This is presumably due to Steam mixing the user data with the installation in "C:\program files(x86)\steam". Linux is not affected because Steam is installed into the home directory.

**Comment by gdrewb-valve** [comment]
I doubt the Windows behavior is intentional, I'll pass this on to the Windows team.  I don't see anything changing in the Linux version so I'm closing this Linux issue.
