### ISSUE TITLE
Steam won't install  from software center

### ISSUE THREAD

**Issue by villandra** [ValveSoftware/steam-for-linux#3749]
I just installed Ubuntu 14.04 yesterday.  Steam hung on trying to install it form the software center, but a failed to install message and even some kind of system damage popup on reboot because the system hung.   I reported the bug and got a message that it is a confirmed bug and was taken to a page maybe on Launchpad, where people have been reporting the issue for over a year - and it hasn't been fixed yet.

However, when I downloaded the package from the Steam web site and installed it in Terminal it worked perfectly.

I was able to open Steam.  I have not yet installed any games.  I have installed two 32 bit libraries that people are saying on forums one needs to run Steam on 32 bit linux.

**Comment by Vikloen** [comment]
Same problem one month ago for the summer sales of steam I was forced to temporarily install ubuntu 15.04.

Actually on Ubuntu 14.04.2 :
Via Ubuntu Software Center (USC) -> reinstall the previous purchases :
The install fail !

W:Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/steam/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError401
, W:Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/steam/ubuntu/dists/trusty/main/binary-i386/Packages  HttpError401
, E:Some index files failed to download. They have been ignored, or old ones used instead.
![capture du 2015-07-13 15 24 08](https://cloud.githubusercontent.com/assets/12892023/8650539/acace0b0-2973-11e5-9aa8-d501210332e9.png)




Launchpad bug sources :
https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1424263
https://bugs.launchpad.net/ubuntu/+source/steam/+bug/1424263

**Comment by Tele42** [comment]
Http error 401 is authorization required. This issue reads as an ubuntu issue, not solvable by valve and is being tracked at https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/1130945, https://answers.launchpad.net/ubuntu/+question/247218, or https://bugs.launchpad.net/ubuntu/+bug/1309884. They all point to a user misconfiguration.

**Comment by kisak-valve** [comment]
Closing as this does not appear to be a Steam issue.
