### ISSUE TITLE
Steam Broadcast player works incorrectly in fullscreen mode

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#3751]
When Steam Broadcast is displayed in Steam client in fullscreen mode, it works incorrectly.
Video and player controls does not stretching to the size of the screen. Instead, they has same size as when video played in window and the rest of the screen space is just black.

My PC specs: http://pastebin.com/RwJTf1dY

Example image:
![Example image](https://cloud.githubusercontent.com/assets/3143668/6553283/d7a6dc96-c657-11e4-88be-8d27342d0b84.png)

**Comment by kisak-valve** [comment]
Hello @Shished, are you still experiencing this issue on an up to date system?

**Comment by Shished** [comment]
It works correctly now.
