### ISSUE TITLE
Store bug: Listing upcoming Linux games gives no results 

### ISSUE THREAD

**Issue by Basaltq** [ValveSoftware/steam-for-linux#3753]
You can see it here:

http://store.steampowered.com/search/?filter=comingsoon&os=linux

The same applies for Mac.

(Also while I'm at it, the total number of games seems to differ based on sorting method. But this is different issue.)

**Comment by liamdawe** [comment]
This has been an issue since the new updated storefront, and it still doesn't work today.

**Comment by liamdawe** [comment]
Is there any news to share on this? I completely forgot I even commented on it as it's been left for so long.

**Comment by Swiftpaw** [comment]
Can confirm.  It is strange this bug affecting both Linux and Mac has gone on for so long.

**Comment by liamdawe** [comment]
Guys, this is increasingly annoying and such a basic feature. Four months since the initial bug report here, can we get a comment on it?

**Comment by liamdawe** [comment]
I'm really surprised with SteamOS coming next month, that this hasn't been fixed? What's going on?

**Comment by scaine** [comment]
Duplicates of this are being identified and closed by Valve staff as far back as April, so they're definitely aware of the issue. Not sure why such a ridiculously simply bug is being left open though.

**Comment by keizgon** [comment]
I've used Linux Mint 17.2, Ubuntu 14.04 LTS, and Ubuntu 15.10 and on 2 different laptops and a regular desktop PC and the results are the exact same across all their clients (browser, Big Picture Mode, Steam Client, AND Steam Client Beta). Why hasn't this been fixed? This is an issue on ALL Linux users clients, including SteamOS (how is this at least not a priority?).

Also related issues:

1) Steam Big Picture Mode lists non-compatible games for Linux.
This is probably the biggest blunder for SteamOS right now. Even reviewers are criticizing Steam Machines for this. Nobody wants to be taunted to purchase a game they cannot play.

2) Browsing Steam from Firefox on the desktop no longer filters by OS you are on. Used to be a feature previously. I would also like to add that the old bug with the Steam Linux client occurs in Firefox when you hover over drop down menus and it immediately disappears, making them unusable.

3) UNDER $10/$5 section in desktop client lists non-compatible games. Should automatically filter for OS but doesn't.

4) Large featured sale banners sometimes displays a non-compatible Linux game.

**Comment by RussianNeuroMancer** [comment]
I created ticket about 2) in Steam Support (4522-RHJZ-0931) and the answer was:

> Ваши отзывы и комментарии важны нашей компании. Я передам их в соответствующий отдел.

(Generic "Your opinion is very important to us".)

**Comment by sevenskull** [comment]
This is very annoying bug, and confusing for people, showing games to buy and that can't be played!

**Comment by NaughtySquid** [comment]
This is FINALLY fixed! https://www.gamingonlinux.com/articles/valve-have-finally-fixed-the-upcoming-steamos-linux-game-filter-nearly-a-year-later.6576
