### ISSUE TITLE
Fullscreen video

### ISSUE THREAD

**Issue by koahv** [ValveSoftware/steam-for-linux#3756]
Display Manager: dwm
OS: Gentoo hardened x64 multilib
Reproducable: when loading any video into fullscreen with the Steam video player
Issues: all function buttons unusable. unable to exit fullscreen

Pause/play with double click works.

Could be related to similar issue of steam group window announcements of wrong window size due to layout of tiling window manager.

Thank you

**Comment by kisak-valve** [comment]
Hello @koahv, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
