### ISSUE TITLE
erro installing steam on ubuntu 14.04 with GNOME

### ISSUE THREAD

**Issue by funkygiblets** [ValveSoftware/steam-for-linux#3757]
when i try to install steam the terminal says:
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 gnome-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
 libgl1-mesa-glx:i386 : Depends: libglapi-mesa:i386 (= 10.1.3-0ubuntu0.4)
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Press return to continue: 
when i continue an error message appears and says
You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
when i quit that pop-up the installer says 
Fatal Error :failed to load steamui.so
and thats all it does, i am very new to linux/ubuntu(installed it today haha) so any help is greatly appreciated

**Comment by myromance123** [comment]
Are you attempting to install Steam through the terminal using the following command?
```bash
sudo apt-get install steam
```
If you are, I strongly advise against it. To get the latest version of Steam installed in Ubuntu, please head here and click Install Steam Now:
http://store.steampowered.com/about/
<a href="http://imgur.com/Fj2RKwL"><img src="http://i.imgur.com/Fj2RKwL.png" title="source: imgur.com" /></a>
This will download a file that ends in .deb. All you need to do is double click it, and it will open up the installer. 
<a href="http://imgur.com/MuWc5vV"><img src="http://i.imgur.com/MuWc5vV.png" title="source: imgur.com" /></a>
The file should look something like this:
<a href="http://imgur.com/WW58uTK"><img src="http://i.imgur.com/WW58uTK.png" title="source: imgur.com" /></a>
Read and Agree to any EULA that may appear (may require a tick), and it should start updating. Steam should then open, and you're done.

**Comment by kisak-valve** [comment]
Hello @funkygiblets, there's two parts to this issue.

The first part is Ubuntu's package manager detected something with the package management wasn't sane and stopped before more harm could have been done.

The second half is the lack of 32 bit libGL.so.1, which effectively means that you were missing a 32 bit opengl driver. Steam is a 32 bit opengl application and needs a sane video driver installed.

If you're still seeing this issue on an up to date system, it's probably best to reach out to your distro's community for help troubleshooting the package manager issue. Closing as this was a general Ubuntu issue and not related to steam.
