### ISSUE TITLE
Unable to use overlay after playing a video (clicks aren't responded to)

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#3758]
After I start playing a video on Youtube in the overlay, I can't click on the video or anything else, even after the video is finished. This means I can't stop listening to a video I don't like either.

**Comment by Half-Shot** [comment]
Same problem here. 
[System Specs](https://gist.github.com/Half-Shot/d9c4aecfb50910dec6b0)

**Comment by kisak-valve** [comment]
Hello @vadi2, @Half-Shot, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
