### ISSUE TITLE
Incorrect link creation in ${HOME}.steam

### ISSUE THREAD

**Issue by sergeygalkin** [ValveSoftware/steam-for-linux#3759]
Steam package version 1426284031
bash - 4.3.33
After run steam I have incorrect simlinks in .steam
As I see in debug steam output

The first iteration is OK  
(if [ "$STEAMROOT" != "$STEAMROOTLINK" -a "$STEAMROOT" != "$STEAMDATALINK" ]; then)
- '[' /usr/local/home/gals/.local/share/Steam '!=' /usr/home/gals//.steam/root -a /usr/local/home/gals/.local/share/Steam '!=' /usr/home/gals//.steam/steam ']'
  ... skipped
- rm -f /usr/home/gals//.steam/root
- ln -s /usr/local/home/gals/.local/share/Steam /usr/home/gals//.steam/root

The second  iteration is not  OK  
- '[' /usr/home/gals/.steam/root '!=' /usr/home/gals//.steam/root -a /usr/home/gals/.steam/root '!=' /usr/home/gals//.steam/steam ']'
  .... skipped 
- rm -f /usr/home/gals//.steam/root
- ln -s /usr/home/gals/.steam/root /usr/home/gals//.steam/root

after this steam games are broken and maybe fixed by
cd ~/.steam
rm root
ln -s /usr/local/home/gals/.local/share/Steam/ root

I guess 
'STEAMCONFIG=~/.steam'  
is incorrect and should used 
'STEAMCONFIG=${HOME}.steam'

**Comment by Plagman** [comment]
Should be fixed in today's Beta, thanks.
