### ISSUE TITLE
Dreamfall chapters immediately exits on launch

### ISSUE THREAD

**Issue by nanonyme** [ValveSoftware/steam-for-linux#3765]
# Log just says:

game update: AppID 237850 "Dreamfall Chapters", ProcID 6900, IP 0.0.0.0:0
ERROR: ld.so: object '/home/nanonyme/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/nanonyme/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Found path: /home/nanonyme/.local/share/Steam/SteamApps/common/Dreamfall Chapters/Dreamfall Chapters
Mono path[0] = '/home/nanonyme/.local/share/Steam/SteamApps/common/Dreamfall Chapters/Dreamfall Chapters_Data/Managed'
Mono path[1] = '/home/nanonyme/.local/share/Steam/SteamApps/common/Dreamfall Chapters/Dreamfall Chapters_Data/Mono'
Mono config path = '/home/nanonyme/.local/share/Steam/SteamApps/common/Dreamfall Chapters/Dreamfall Chapters_Data/Mono/etc'
# Game removed: AppID 237850 "Dreamfall Chapters", ProcID 6900 

Game immediately exits after this without any useful errors

**Comment by gdrewb-valve** [comment]
You should report this to the game developers also.

**Comment by tomtomme** [comment]
No, I bet he should not. This is also a unity3d-engine game and ALL games using this engine refuse to start through steam, but run fine solo, see my bug-report: https://github.com/ValveSoftware/steam-for-linux/issues/3888

@nanonyme : could you confirm that you have other games that do not launch / show this error? Could you tell us which ones and if some of them can be run solo? You can do this by right clicking on the game entry in steam, selecting properties, then local files, the browse local files and then click on the game binary.

**Comment by tomtomme** [comment]
try Installing the alsa-devel and alsa-devel-32bit packages - this solved the issue for me :)

thank Tuk for the fix, see https://github.com/ValveSoftware/steam-for-linux/issues/3888

**Comment by kisak-valve** [comment]
Hello @nanonyme, @tomtomme, are either of you still experiencing this issue on an up to date system?

**Comment by nanonyme** [comment]
I haven't been using Steam except throgh the Flatpak on Linux for a while since it's less messy so I'd prefer if

**Comment by tomtomme** [comment]
This issue is solved for me. I just tried to uninstall alsa-devel and alsa-devel-32bit and this is not possible anymore without also removing steam. So the deps are correct now on opensuse tumbleweed at least since steam version 1.0.0.54-5.4 as of Di 14 Nov 2017 13:00:00 CET

**Comment by kisak-valve** [comment]
Thanks for retesting. Steam's handling of the runtime has also changed so that the default is to prefer host libraries. That makes it less likely to mix incompatible libraries which may also help avoid this.

Closing per the last couple comments.
