### ISSUE TITLE
Steam Client hangs on start

### ISSUE THREAD

**Issue by jdost** [ValveSoftware/steam-for-linux#3766]
Running on Arch Linux, whenever I start the steam client, it hangs with just the following as the output:

```
Running Steam on arch  64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1422054110_client)
```

**Comment by gdrewb-valve** [comment]
Can you give more configuration details, such as what video card and driver you have, etc.?

**Comment by jdost** [comment]
The card is an NVidia GeForce GTX 260.  The driver is the proprietary NVidia driver version `340.76`.

**Comment by Aaron1011** [comment]
I can reproduce this on Ubuntu 14.04

**Comment by Aaron1011** [comment]
The error turned out to be an X11 `BadAlloc` error. I'd been getting this with `cheese` and `glxgears` as wel..

Updaing to the drivers in [this PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) fixed  the issue (The normal warnings about downloading from a PPA apply).

**Comment by kisak-valve** [comment]
Hello @jdost, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing assuming this was a video driver issue from 2015.

If anyone on an nvidia system has this symptom, the most likely cause is that nvidia's running kernel module version does not match the userspace library version.
