### ISSUE TITLE
BigPicture doesn't work with Russian Language (broke after today update steam)

### ISSUE THREAD

**Issue by lexxus-lex** [ValveSoftware/steam-for-linux#3768]
1 image - big picture on Ru
<a target="_blank" href="http://itmages.com/image/view/2393229/379a1c31"><img src="http://storage1.static.itmages.com/i/15/0325/s_1427290579_1361356_379a1c3138.png" /></a>

2 image - big picture on En
<a target="_blank" href="http://itmages.com/image/view/2393232/895a4c37"><img src="http://storage2.static.itmages.com/i/15/0325/s_1427290580_8732814_895a4c377e.png" /></a>

3 image - Steam window on Ru - all work.
<a target="_blank" href="http://itmages.com/image/view/2393231/cb3747eb"><img src="http://storage1.static.itmages.com/i/15/0325/s_1427290579_9390708_cb3747eb50.png" /></a>

P.S. client steam update  today.

Процессор:
    Поставщик:  GenuineIntel
    Семейство процессора: 0x6
    Модель процессора: 0x2a
    Степпинг процессора: 0x7
    Тип процессора: 0x0
    Тактовая частота: 3400 МГц
    Кол-во логических процессоров: 4
    Кол-во физических процессоров: 4
    HyperThreading:  Не поддерживается
    FCMOV:  Поддерживается
    SSE2:  Поддерживается
    SSE3:  Поддерживается
    SSSE3:  Поддерживается
    SSE4a:  Не поддерживается
    SSE41:  Поддерживается
    SSE42:  Поддерживается

Сеть:
    Скорость соединения: 

Версия ОС:
    Ubuntu 14.10 (64 бит)
    Название ядра: Linux
    Версия ядра: 3.16.0-33-generic
    Поставщик X-сервера: The X.Org Foundation
    Версия X-сервера: 11601901
    Менеджер окон X Window System: KWin
    Версия клиента Steam: steam-runtime-release_2015-01-06

Видеокарта:
    Модель:  NVIDIA Corporation GeForce GTX 770/PCIe/SSE2

```
Версия драйвера:  4.4.0 NVIDIA 340.76
Версия OpenGL: 4.4
Глубина цвета: 24 бит/пикс
Частота обновления: 60 Гц
ID производителя: 0x10de
ID карты:  0x1184
Кол-во экранов:  1
Количество логических видеокарт:  1
Разрешение осн. экрана:  1920 x 1080
Разрешение рабочего стола: 1920 x 1080
Размер осн. экрана:
```

В дюймах: 18,78" x 10,55" (диагональ 21,54")
В сантиметрах: 47,7 см x 26,8 см (диагональ 54,7 см)
    Осн. шина: PCI Express 16x
    Осн. видеопамять: 4096 MB
    Поддерживаемое сглаживание:  2x 4x 8x 16x 

Звуковая карта:
    Аудио устройство: Realtek ALC892

Память:
    Оперативная память:  7954 МБ

Разное:
    Язык интерфейса:  Русский
    ЯЗЫК: ru_RU.UTF-8
    Микрофон:  Not set
    Места на диске:  846257 Мб
    Наиболее свободный диск:  14982 Мб

Установленное программное обеспечение:

Последние сообщения об ошибках:

**Comment by lexxus-lex** [comment]
and this:

<a target="_blank" href="http://itmages.com/image/view/2393383/c9365c23"><img src="http://storage2.static.itmages.com/i/15/0325/s_1427292556_7947913_c9365c232e.png" /></a>

no Ru lang :(

**Comment by lexxus-lex** [comment]
after today update, problem NOT SOLVE

In beta version - all work fine.

**Comment by Cactus64k** [comment]
Столкнулся с похожей проблемой.
Не нашел решения?

**Comment by lexxus-lex** [comment]
<b>Cactus64k</b>, решение одно))) выпрямить руки разработчикам.

**Comment by kisak-valve** [comment]
Hello @lexxus-lex, @Cactus64k, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
