### ISSUE TITLE
Verify game cache does not show display correctly

### ISSUE THREAD

**Issue by tmwbook** [ValveSoftware/steam-for-linux#3770]
The verifying game cache window shows "Validating `game` file (1 of 1)" for all points of the process.  This has only been tested while verifying Dota 2.

Specs:
Memory 3.4 GiB
Processor Intel Core i5-34670 CPU @ 3.20GHz x 4
GPU Gallium 0.4 on AMD PITCAIRN
OS: Arch Linux 32-bit

**Comment by kisak-valve** [comment]
Hello @tmwbook, are you still experiencing this issue on an up to date system?

**Comment by tmwbook** [comment]
@kisak-valve Thanks for checking up on this.  Unfortunately I no longer run this system and have not used steam for linux for close to a year.  I had forgotten that this issue was still open and I will close it.
