### ISSUE TITLE
Broadcasting options exposed on unsupported platform.

### ISSUE THREAD

**Issue by beansmyname** [ValveSoftware/steam-for-linux#3771]
ISSUE: Broadcasting is not yet available for Linux, however the options for broadcasting are made available in Big Picture Mode (BPM). These options are not available via the desktop client running in desktop mode.

OS: Tested on [64-bit Archlinux](https://gist.github.com/beansmyname/918d0a122d31c263c7c0#file-steam_sysinfo) and [up-to-date gentoo](http://runlinux.net/steam/sysinfo.txt)

Steps (must have Steam Overlay enabled):
- Launch Steam
- If not launched in BPM, switch to BPM
- Go to settings -> Broadcasting
- Allow friends to view broadcast
- Launch a game
- Observe notification indicating that broadcasting is enabled ![Screenshot of notification inside BPM](http://runlinux.net/steam/broadcasting.png)
- Quit game
- Exit Big Picture Mode
- Launch a game
- After Steam overlay notification, observe a notification that broadcasting is enabled ![Screenshot of notification outside BPM](http://runlinux.net/steam/broadcasting1.png)
  - It may be necessary to restart Steam to see the notification correctly as fonts are often not visible after leaving Big Picture mode (an entirely different bug)

Results: Steam presents notification that broadcasting is enabled on an unsupported platform.

Expected Behavior: Broadcasting options should be unavailable in BPM until broadcasting is supported.

**Comment by kisak-valve** [comment]
Hello @beansmyname, looks like this got wired up. Closing per the discussion on #5275.
