### ISSUE TITLE
Steam needs to be killed with -9 (SIGKILL)

### ISSUE THREAD

**Issue by RobinJ1995** [ValveSoftware/steam-for-linux#3772]
Normally, when a program on Linux freezes, you can just kill it and it will exit. For some reason the developers seem to have decided that they're just going to ignore the kill signal and instead the Steam client will keep running/hanging as usual. Inevitably the Steam client will hang at some point at least once every week. I'll tell it to launch a game and it'll be stuck on "Preparing to launch...", it'll be stuck attempting to sync save files (and probably overwriting the new one with the old one as it so often does), or it'll just be in zombie mode (everything seems to work and windows open and close just fine, but the friend list no longer refreshes and launching games or exiting Steam won't work as happens every time the system comes out of standby). In all of these scenario's there's no option but to kill Steam with `-9` (`SIGKILL`), because that's (as far as I know) the only signal it can't capture and/or ignore.

This is ridiculous, and unless there's a very good reason Steam does this it's a bug that should be fixed.

**Comment by Plaque-fcc** [comment]
I won't be surprized if this happens because of file descriptors
leakage.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2017-01-05 steam beta client update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256). If Steam is not deadlocked it will listen to SIGTERM.
