### ISSUE TITLE
BigPicture Mode causes web contento to be displayed with a different font

### ISSUE THREAD

**Issue by thetargos** [ValveSoftware/steam-for-linux#3775]
Hi all. For some strange reason I have yet to pinpoint, BigPicture Mode causes display of web content with a font other than "sans" or the default typeface selected in my desktop configuration. I do have said font installed, but it is in no way selected as any default font. Following are two screenshots, one showing Steam Desktop after exiting from BPM leaving it in this state. The font in question is called FormalScrp:
![captura de pantalla de 2015-03-30 15 45 45](https://cloud.githubusercontent.com/assets/4742429/6907824/d9077672-d6f6-11e4-9ac3-34657ad9fb23.png).

**Comment by kisak-valve** [comment]
Hello @thetargos, are you still experiencing this issue on an up to date system?

**Comment by thetargos** [comment]
I had seen this isaue on and off with the beta client, however, I have not come across this in BPM for at least the last 5 or so updates. I think it can be closed now.

**Comment by kisak-valve** [comment]
Thanks, closing.
