### ISSUE TITLE
Steam crashes after updating when starting

### ISSUE THREAD

**Issue by Zachs-Kappler** [ValveSoftware/steam-for-linux#3781]
Commandline Output:
> rm: cannot remove ‘/home/daniel/.steam/steam’: Is a directory
> rm: cannot remove ‘/home/daniel/.steam/bin’: Is a directory
> Running Steam on elementary os 0.3 64-bit
> STEAM_RUNTIME is enabled automatically
> [2015-04-02 20:30:27] Startup - updater built Apr  1 2015 12:15:46
> [2015-04-02 20:30:27] Opted in to client beta 'publicbeta' via beta file
> You are in the 'publicbeta' client beta.
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> [2015-04-02 20:30:28] uninstalled manifest found in /home/daniel/.steam/package/steam_client_publicbeta_ubuntu12 (1).
> [2015-04-02 20:30:28] Found pending update
> [2015-04-02 20:30:28] Installing update...
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> [2015-04-02 20:30:28] Extracting package...
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> Installing breakpad exception handler for appid(steam)/version(1427922473)
> [2015-04-02 20:30:34] Installing update...
> [2015-04-02 20:30:34] Cleaning up...
> [2015-04-02 20:30:34] Update complete, launching Steam...
> [2015-04-02 20:30:34] Shutdown
> /home/daniel/.steam/steam.sh: line 765: STEAMSCRIPT_OUTOFDATE: unbound variable

**Comment by Tele42** [comment]
@Zachs-Kappler as a workaround, you should be able to get past this by running `STEAMSCRIPT_OUTOFDATE=0 steam` in a terminal

**Comment by johnv-valve** [comment]
I believe this is fixed
