### ISSUE TITLE
Feature Request: Cross-platform downloads.

### ISSUE THREAD

**Issue by Diversant** [ValveSoftware/steam-for-linux#3784]
Quite a neat thing being done about possibility to add library folders from different filesystems. But dual-booting into Windows or using Steam under WINE causes Steam to redownload the content for each system. Maybe it is possible to minimize the download size by making some kind of check to download only necessary binaries/libs for particular OS where is Steam being launched, not the packed content of the games either? 
And every platform change (access to steam library) causes Steam to show "update needed" for each game. Maybe some workaround possible (not just manual turning off for each game)?

**Comment by gdrewb-valve** [comment]
This has been requested in the past and as far as I know this isn't going to be added so closing this.

**Comment by Diversant** [comment]
This is sad. Because traffic gets higher and more unnecessary downloads.
