### ISSUE TITLE
I can't get start client

### ISSUE THREAD

**Issue by WyRe** [ValveSoftware/steam-for-linux#3787]
I'm running on ArchLinux x86_64 and i just install steam client, i have got multilib repos activated and 32bit libraries required installed but when i try to start steam from prompt i get:

[wyre@NZXTArch ~]$ steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1427176184)

It remains hung for a long and won't seems start.
However... if i start ./steam located in ~/.local/share/Steam/ubuntu12_32/ i get this:

[wyre@NZXTArch ubuntu12_32]$ ./steam
[2015-04-07 04:37:26] Startup - updater built Mar 23 2015 20:05:07
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

And same, it won't seems start :( 
.... What could be wrong or what am i doing wrong? ... :D Thank so much guys! :P

**Comment by Tele42** [comment]
What video driver are you using?

**Comment by WyRe** [comment]
https://www.archlinux.org/packages/extra/x86_64/nvidia/

**Comment by Shished** [comment]
Same happens for me. But steam starts when launched second time.
I'm using openSUSE Tumbleweed x86_64, linux 3.19.3 and nvidia 349.12.

**Comment by WyRe** [comment]
In my case there isn't wa to start it, for many times that i try it it remains stuck, this is my nvidia packages tree 

http://paste.debian.net/165679/

Yesterday driver in Arch repos was updated to 346.59-1 but still i have that bug (the same) ...

**Comment by WyRe** [comment]
Sorry, it was my fault, i have some 32bit packages from 340xx series... Can u close the issue :D and i'm so sorry for be so dumb xD

**Comment by Tele42** [comment]
The user who opened the issue report is also able to close it.
