### ISSUE TITLE
Feature Request: Start Steam in background option.

### ISSUE THREAD

**Issue by PTNobel** [ValveSoftware/steam-for-linux#3789]
If you could add a option (say `-q`) that starts Steam in the background,
  so I could use it in config files (such as `~/.i3/config`) so I can launch
  steam in the background and have the social aspects of steam running without
  needing to have the client open every time I log in.

**Comment by vinman07a** [comment]
I would love to have this as a system stray in i3

**Comment by beansmyname** [comment]
Steam already has an option for this (`-silent`). Found that on [Valve's Developer Wiki](https://developer.valvesoftware.com/wiki/Command_Line_Options#Steam_.28Windows.29). Even though the options listed are for Windows many of them still apply to the Linux client.

**Comment by kisak-valve** [comment]
Closing per the last comment.
