### ISSUE TITLE
URLs don't open

### ISSUE THREAD

**Issue by opeik** [ValveSoftware/steam-for-linux#3793]
Hi, I'm using Debian Jessie and Iceweasel. When I click on a URL in a Steam chat, it doesn't open. I have Iceweasel set to my default browser.

**Comment by Tele42** [comment]
If my memory is correct, steam calls xdg-open, which in turn opens the browser. does `xdg-open http://github.com` work for you?

**Comment by opeik** [comment]
Solved with
```
sudo aptitude install xdg-utils
```
Thanks!
