### ISSUE TITLE
force 32 bits only on 64/32 bits x86 systems

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#3800]
Is there a way on a 64/32 bits x86 GNU/linux systems to force the steam client to behave like it's a 32 bits only OS?
It would install only 32 bits builds of video games.
(I apologize since I don't think it's the right place to ask for that)

**Comment by Tele42** [comment]
Yes, make yourself a 32bit chroot environment, then install steam in it. No, I will not give step-by-step instructions in doing this.

**Comment by sylware** [comment]
You missed the point. The idea is to do it in a config file or command line option or trick whatever 32/64 bits detection the client have.

**Comment by gdrewb-valve** [comment]
No, there isn't a way to do this.
