### ISSUE TITLE
[steam client][linux]game folder lowercase/uppercase messed up![R.2015apr13]

### ISSUE THREAD

**Issue by alexanderhou** [ValveSoftware/steam-for-linux#3815]
[steam client][linux]game folder lowercase/uppercase messed up![R.2015apr13]

OS: ubuntu 14.04.2 LTS 64bit.
steam client newest update 2015apr13 update

by default, steam client for linux, only mounts this folder as game install destination.
/home/MYNAME/.steam/SteamApps/.......

but, one user can add 1 or more folders from different harddrive mount point. of course assigning sufficient privileges.

but, now after 2015apr13 update for linux ver. the stupid thing is,

e.g. /media/MYNAME/26b2daee-33b0-4696-a683-1b4d5806f5ca/steamlib/SteamApps/

i assigned read+write/read+write/read-only privileges to those folders.

but the steam client still report errors when i want to add "steamlib" folder to the game install paths as 2nd choice in steam client UI.

the reason is, in recent steam update, you changed the customize-able "steam library/SteamApps" folder name!

the traditional name is "SteamApps" but now you changed to "steamapps"... see the difference?!

LINUX IS NOT WINDOWS, UNDER LINUX, UPPERCASE IS NOT THE SAME AS LOWERCASE! DO YOU UNDERSTAND?

why change it to all lowercase?! that means, the steam client for linux always report errors saying not enough privileges for execute... but actually NO! i have assigned enough privilege, you changed it to all lowercase. not that "SteamApps".

so bug happens.

please fix that. otherwise i have to do a small work-around, rename the SteamApps to steamapps, then re-add the folder to steam client, then, my games installed to the customized folder would be back.

but if i trust your steam client, as no privilege issue,  then Gigabytes of game data would be lost. that is somewhat silly.

i think, maybe in future, for steam linux client, both folder path "steamapps" and "SteamApps" are supported, then that is better!

**Comment by gdrewb-valve** [comment]
Same underlying issue as #3649.
