### ISSUE TITLE
beta client: web component update broke tons of stuff

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#3816]
dota2 in game web components are broken. In the client, many times I need to refresh the page or I get buggy pages. Keyboard input is weird (for instance backspace does not work).
steamOS (debian 7 + alchemist beta repos) and dvorak keyboard (xfce desktop).

**Comment by Vash63** [comment]
Same here. Both SteamOS and on my Arch Linux system. The period key above right alt doesn't work but the one on the numpad does, backspace doesn't work, very odd input in general.

**Comment by Vash63** [comment]
Also, this looks like a duplicate of #3811, you should probably close this bug and subscribe/comment on that one instead.

**Comment by sylware** [comment]
#3811 related to  keyboard issue only. I get rendering issue too in the client and in-game (dota2)

**Comment by Plaque-fcc** [comment]
#3811 is not about keyboard only.

**Comment by sylware** [comment]
On Mon, Apr 27, 2015 at 10:10:23AM -0700, Plaque FCC wrote:
> #3811 is not about keyboard only.

The reporter should change the title then.

**Comment by Plaque-fcc** [comment]
I only mean that one of these two is a duplicate; otherwise we need to
separate keyboard issues from rendering issues into two different bug
reports.

**Comment by sylware** [comment]
Based on the title, this issue is more pertinent than the other one. The other
one should have its title changed to augment the spread of the pb or be closed,
and that one kept opened. Please refrain from trolling.

**Comment by Plaque-fcc** [comment]
I don't ever think of trolling. I guess the only trolling now may be in
the ignorance the devs show us about this bug. I can't fix this, they
can fix it. I only hope.

**Comment by sylware** [comment]
c++ hell I guess

**Comment by sylware** [comment]
web rendering issues are gone but keyboard issues remain, then #3811 is enough

**Comment by Plaque-fcc** [comment]
Agreed.
