### ISSUE TITLE
Steam folder

### ISSUE THREAD

**Issue by Ron7So** [ValveSoftware/steam-for-linux#3817]
hello please could take the folder Steam the home of Ubuntu? not like me, that folder that are used to store info Sold do not need this visible to the common User

**Comment by bjwest** [comment]
If I understand you correctly, you're asking if the games folder is viewable by others on the system?  If this is correct, then no, it's not.  Everything under you home directory (/home/Ron7So, if that's your user name on the system) should be private and only viewable by you and root.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear to be an issue?
