### ISSUE TITLE
Steam overlay Causes crashes on dota 2 

### ISSUE THREAD

**Issue by Celexi** [ValveSoftware/steam-for-linux#3819]
I reported this in dota 2, but no one saw it, so i am reporting here, this issue is old and annoying now, sometimes the overlay when getting a new message, will promptly crash dota2, alt tabbing with the overlay enabled is a casino slot machine on if its going to not crash or not when back in game, this is horrible.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.5-200.fc21.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11603000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 346.59
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1201
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3840 x 1080
Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                        53.1cm x 29.9cm  (60.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7930 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  879807 Mb
    Largest Free Hard Disk Block:  485390 Mb

Installed software:

Recent Failure Reports:
    Tue Apr 28 20:00:08 2015 GMT: file ''/tmp/dumps/crash_20150428205903_22.dmp'', upload no: ''HTTP response code said error''
    Tue Apr 28 23:41:19 2015 GMT: file ''/tmp/dumps/crash_20150429002632_1.dmp'', upload no: ''HTTP response code said error''
    Wed Apr 29 00:18:16 2015 GMT: file ''/tmp/dumps/crash_20150429004158_1.dmp'', upload no: ''HTTP response code said error''
    Wed Apr 29 00:24:04 2015 GMT: file ''/tmp/dumps/assert_20150429012258_21.dmp'', upload yes: ''CrashID=bp-ac4b4a39-6042-442a-b582-cfc322150428''

**Comment by ramma** [comment]
Same issue here, I'm getting a core dump which prints this is console.

```
##### CMaterialReference::Init got error material for particle\warp_spiral01b.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for models\projectiles\projectile_jar.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for models\projectiles\projectile_jar.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for models\projectiles\projectile_jar.vmt in tex group Other textures
 ##### CMaterialReference::Init got error material for particle\dust\ground_expa.vmt in tex group Other textures
ERROR: ld.so: object '/home/derp/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150428200709_1.dmp[21590]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150428200709_1.dmp
/home/derp/.steam/steam/SteamApps/common/dota 2 test/dota.sh: line 77: 21444 Floating point exception(core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

**Comment by kisak-valve** [comment]
Hello @Celexi, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
