### ISSUE TITLE
Dota 2 blog and Store pages don't load.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/steam-for-linux#3821]
The bug was originally reported on the Dota 2 issue tracker at [bug #1735](https://github.com/ValveSoftware/Dota-2/issues/1735)
Downgrading Steam to stable from the Beta branch fixes the issue.

**Comment by r3pek** [comment]
The April 30 Beta update didn't fix the problem

**Comment by kisak-valve** [comment]
Hello @ramma, @r3pek, are either of you seeing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
