### ISSUE TITLE
Game sounds play static in Dota 2 and CS:GO.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/steam-for-linux#3823]
The current beta client causes many game sounds to be played as static. Reverting to the stable version works around the issue for now.

The samples are potentially **very LOUD**, be prepared.
[Example CS:GO video](https://www.youtube.com/watch?v=NMviwn_z18Q)
[Example Dota 2 video](https://www.youtube.com/watch?v=IpoArpiZDAQ) The game crashes at the end due to bug #3819.

[System info](https://gist.github.com/ramma/8dc867b11b44917debfc)

**Comment by r3pek** [comment]
Also, running snd_restart command on the console fixes the problem of constant static. Still, there are some static noises during normal music playback.

**Comment by ramma** [comment]
snd_reset didn't fix the problem for me.

CS:GO is no longer playing static for me though.

Dota 2 is still playing static though. The live version is playing much less static now, but the test client is still unplayable with the beta steam client due to the sound.

**Comment by gavindi** [comment]
This issue is also happening to me and I can confirm both that snd_* commands do not help and that by downgrading Steam client from beta to stable does fix the issue.

**Comment by urbinek** [comment]
Same problem her on beta client

**Comment by r3pek** [comment]
There was a Steam Beta update today/yesterday but it didn't fix the problem...

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed in the [2015-05-01](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/231150996262799070) Steam client beta update.
