### ISSUE TITLE
Feature request::Built-in calibration for gamepad analog sticks within Steam BPM

### ISSUE THREAD

**Issue by immerohnegott** [ValveSoftware/steam-for-linux#3829]
Something that's been bugging me for a while on linux is gamepad calibration. Jstest-gtk sort of works, but appears to have been abandoned for a while and doesn't properly save preferences to keep deadzones and such persistent for my Xbox 360 pads. Ergo, I need to recalibrate every reboot.

As BPM already includes a method for properly remapping gamepad buttons and axes, would it be possible to expand this functionality to include calibration/deadzoning of the analog sticks? 

Thanks a bunch!

**Comment by Uramekus** [comment]
Steam input has proper calibration and deadzone input, asking for closure
![2018-08-23-01 40 12-screenshot](https://user-images.githubusercontent.com/4643873/44505047-953d3100-a675-11e8-8782-3afdb9e84294.png)

**Comment by kisak-valve** [comment]
Thanks @Uramekus, closing.
