### ISSUE TITLE
Steam on Fedora21 64bit crash when online

### ISSUE THREAD

**Issue by RGeri77** [ValveSoftware/steam-for-linux#3832]
Hi,

I have a freshly installed Fedora 21 64 bit with Bumblebee (optirun) and Steam latest. If I start Steam online then its crash after few seconds. If I start Steam offline then working well. Its the same if I set the beta signup and Steam download the beta version. All of other 3D application are working (ex. steam with wine,or any 3d game). On the other notebook which has an intel gpu I can use Steam Online, and its the same Fedora 21 64 bit

Test phase 1:
I removed abrt package (yum remove abrt) and now Steam not crashing but freezing. No segmentation error attonce, just freeze when Im in Online mode and get segfault later. In Offline mode working normally.

Test phase 2:
On the other notebook working well with intel GPU.

Test phase 3:
Wireless connection active, start steam with optirun steam, login with my account in online mode, when Steam logged in I disconnect the wireless network fast, and then Steam its not freezing. I can select game or any what I can do in offline mode, few seconds after Steam say "No internet connection" but its working, and not freezing. I turn on wireless connection, and after few secs, Steam freezing. Quite interesting :-)

I know its not Steam specific error, but somehow connected to Steam.

Link to steamcommunity : http://steamcommunity.com/app/221410/discussions/0/620712364032277833/

Thanks
Geri

**Comment by RGeri77** [comment]
Test phase 4:
I revert back the driver from NVidia 349.16 to Nouveau.
Now I can login, and I dont have segfault error. I can download games, and configure steam. It seems working well. 
Question: What a hell is the connection between Nvidia driver 349.16 and Steam in Online mode ? Because in Offline mode Steam worked OK with Nvidia driver.........

**Comment by RGeri77** [comment]
Thank you guys to start the investigation. In the meantime I try to configure primusrun maybe will be worky. Its important to make Steam working because we have (Fedora ambassadors) many event where we represent Linux Gaming, and Steam is a pillar of that. Thanks.

**Comment by RGeri77** [comment]
Here is the steam debug log : http://ur1.ca/kbcwq

**Comment by RGeri77** [comment]
Hey,hey. Im using Steam in Online with the following workaround.

1. Start steam normally with network
2. Login with password
3. Disable network connection
4. Wait, but not too much (Steam not recognize there is no network)
5. Reenable wireless network
6. Tadam, Im online with Steam, and I can download games

**Comment by RGeri77** [comment]
Steam crashing more frequently. Sometimes the workaround not working. Now I have 352.21 nvidia drivers. Usually I need to play with the workaround tons of times. Is there any idea why steam crashing when its online ?

**Comment by kisak-valve** [comment]
Hello @RGeri77, are you still experiencing this issue on an up to date system?

**Comment by RGeri77** [comment]
Hello. Sorry I forgot to comment when its solved. I use Fedora 28 and Steam release 28. Aug. and everythin is working now.
Thank you,

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
