### ISSUE TITLE
Please create 64 bit native Steam Linux client!

### ISSUE THREAD

**Issue by roadapathy** [ValveSoftware/steam-for-linux#3833]
Why on earth are we still using a 32bit Steam client for Linux? I can't even imagine it. This is BREAKING my system with all of these old 32bit libs. Please fix this.

**Comment by LollenJumplan** [comment]
+1 my poor debian is also flooded by 32 bit deps. :/

**Comment by gdrewb-valve** [comment]
Duplicate of #179.
