### ISSUE TITLE
News open in external browser instead of Steam

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3834]
If inside Steam I go to some game’s store page, then click on the title of a news item, it displays the news item inside Steam; however if I click on "Read related news" and _then_ click on the title of a news item (to read the comments or write one), it is shown in Firefox.

This is annoying because I typically read the news from the downloads page when a game has been updated, and the same issue happens in that case.

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed some time ago.
