### ISSUE TITLE
[META] GitHub issues need to be re-assigned

### ISSUE THREAD

**Issue by Zer0t3ch** [ValveSoftware/steam-for-linux#3837]
There are currently 35 open issues assigned to @johnv-valve who has not committed anything (according to hid GitHub page) since October 2014. (Over 6 months ago) 

This is a request that all "reviewed" issues assigned to @johnv-valve be re-reviewed and assigned to someone else. 

**EDIT - I have just realized that the actual steam script isn't in this repo, and that @johnv-valve could be very active and we wouldn't have any way to tell. This issue could be completely useless/irrelevant, and if it is, sorry.

**Comment by cjwijtmans** [comment]
lol

**Comment by lukasepple** [comment]
rofl

**Comment by ProfessorKaos64** [comment]
Who is this johnv-valve????. He must seriously be slacking! 

jk, well anyway, @Zer0t3ch , you probably could close this, kind of a non-issue.

**Comment by Zer0t3ch** [comment]
I'm a dumbass.
