### ISSUE TITLE
Cannot rebind controller in Big Picture

### ISSUE THREAD

**Issue by Kirov123** [ValveSoftware/steam-for-linux#3840]
I can navigate big picture with the analogue stick just fine(afterglow 360pad), but to select a category, I have to use B instead of A and trying to rebind simply does not work. I cannot rebind anything at all. Button/keyboard pressed do nothing, it seems like it simply stops recognizing the input.

**Comment by ProfessorKaos64** [comment]
I believe this was recently added back , at least in the beta client. Can you recheck settings again if you opt into the client beta?

**Comment by kisak-valve** [comment]
Closing pending feedback on the last comment.
