### ISSUE TITLE
steam client takes a lot of time to reconect after suspend-resume

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#3841]
After resume the steam client doesn't recognize that it's not connected to steam for about half an hour. I can even browse the store, and steamcommunity from the client, and the web pages say I'm offline, while the client shows in the bottom right corner that I'm online. If I manually set myself offline during this period, I can't set myself online again, until the period is over, and the client finally reconnects to the network.

**Comment by Tele42** [comment]
This issue is being tracked on #474.

**Comment by mtmkls** [comment]
Yes, it seems my search was inadequate.
