### ISSUE TITLE
CJK fonts in big picture mode

### ISSUE THREAD

**Issue by extraymond** [ValveSoftware/steam-for-linux#3844]
Fonts went missing in big picture mode if I choose chinese traditional.
My system:
OS-ubuntu 15.04  64bit
CPU-AMD APU A10-5800K
GPU-AMD R7-265

**Comment by extraymond** [comment]
http://imgur.com/e4sYbNp
This is the screenshot.

**Comment by jeifour** [comment]
Exactly the same happens with Japanese here. Only in Big Picture, though.

**Comment by Plagman** [comment]
Can you confirm whether this is fixed?

**Comment by extraymond** [comment]
It's fixed on my setup!!
Thx valve for fixing it asap.

2015-06-10 6:47 GMT+08:00 Pierre-Loup A. Griffais <notifications@github.com>
:

**Comment by jeifour** [comment]
Confirm working for me with Japanese on GNU/Linux. Even chooses the correct font so that the text looks good (the regular client uses a Chinese font instead). Thanks.

**Comment by Plagman** [comment]
Thanks for the confirmation!
