### ISSUE TITLE
[Steam] favorites and groups disposed 

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#3847]
Steam disposed of all favorites and own created groups, during the update, or if the same account to use two machines (Intra-in broadcasts Home, vs. linux and windows). This is really annoying.

this bug is Windows and Linux steam versions.

**Comment by kisak-valve** [comment]
Hello @lahtis, have you seen this issue since the initial report?

**Comment by lahtis** [comment]
nope. Tested only Steam in Linux in wine steam. All working in me.
