### ISSUE TITLE
Black splash screen

### ISSUE THREAD

**Issue by TylerJWhit** [ValveSoftware/steam-for-linux#3849]
Won't fully open. Black splash screen.
PC Specs:
http://pastebin.com/YAQ5X3fx

OS:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"

![screenshot from 2015-05-19 21 35 14](https://cloud.githubusercontent.com/assets/1591808/7719023/ff459aae-fe6e-11e4-9919-405bf63ee52d.png)

**Comment by TylerJWhit** [comment]
Complete reinstall of OS still hasn't fixed issue. Only think that was kept was my home directory.

**Comment by Tele42** [comment]
Steam is stored in your home folder (~/.local/share/Steam by default). Does running `steam --reset` help?

**Comment by TylerJWhit** [comment]
Still the same. I can't upload the dumpfile though since it's larger than 512. If you need it let me know how I can get it to you.

**Comment by TylerJWhit** [comment]
Is anyone reviewing these? Tell me what you need and I'll get it to you, it's been a half a year and I have not been able to use steam on my PC.

**Comment by Tele42** [comment]
@TylerJWhit I'm not proper support but let's do a couple things to try to figure this out, can you open a terminal, run steam, and post the output here?

What video driver are you using? Please also include the output of ```glxinfo | grep OpenGL```

**Comment by TylerJWhit** [comment]
This last update just fixed the issue. Thank you
