### ISSUE TITLE
Steam crashes after entering Steam Guard code

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#3850]
PC specs: http://pastebin.com/MS88CP5a

I just enable new Steam Guard mobile authenticator and tried to test it.
I selected "change user" and Steam logged out.
After that login windows appears, I entered login credentials. Then Steam Guard window appears, asking for code. I entered code and window closed but then nothing happened.
I launched game in the terminal emulator and this is debug output from Steam

```
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  18 (X_ChangeProperty)
Value in failed request:  0x0
Serial number of failed request:  757
xerror_handler: X failed, continuing
Frame::ApplyLayoutTemplate() : couldn't find subpanel 'frame_title' as specified in template 'Frame'
assert_20150520205310_1.dmp[15829]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150520205310_1.dmp
/home/yuri/.local/share/Steam/steam.sh: line 756: 15760 Ошибка сегментирования                   $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20150520205310_1.dmp[15829]: Finished uploading minidump (out-of-process): success = no
assert_20150520205310_1.dmp[15829]: error: HTTP response code said error
assert_20150520205310_1.dmp[15829]: file ''/tmp/dumps/assert_20150520205310_1.dmp'', upload no: ''HTTP response code said error''
```

---

Turns out that Steam only crashes when system language is Russian (my LANG is ru_UA.utf8)
When LANG env variable is set to C or en_US, Steam loads properly

Additional files: 
full stdout: http://pastebin.com/TSKwUmM4
Binary dump generated by Steam: https://mega.co.nz/#!NZA1AYYL!7bi5Voq-SoeqBNJOq5Fev-YYg9X3N9Q5QH7zrjlB60A

**Comment by kisak-valve** [comment]
Hello @Shished, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
