### ISSUE TITLE
"Developer Tools" accessible from developer console; not working

### ISSUE THREAD

**Issue by MrSchism** [ValveSoftware/steam-for-linux#3852]
By launching Steam with the -dev flag, it exposes the "developer tools" button on right-click.  When clicked, this creates a new Steam window that is blank.

I first thought this was being brought in from one of my Chrome extensions, but I had someone without the extension installed (they didn't even know about the extension) check and that wasn't the cause.

**Comment by kisak-valve** [comment]
Hello @MrSchism, are you still seeing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
