### ISSUE TITLE
Add Non-Steam Game Doesn't Work Properly

### ISSUE THREAD

**Issue by Enverex** [ValveSoftware/steam-for-linux#3855]
Steam seems to ignore everything after the first space on the Exec line in .desktop files so any arguments get ignored. Spaces are valid for .desktop files so obviously this shouldn't happen.

Example .desktop file:

```
[Desktop Entry]
Name=Super Mario Kart
Exec=emuGame snes "Super Mario Kart (USA).sfc"
Terminal=false
Type=Application
Categories=Game;
```

It picks up "/bin/emuGame" and nothing more. So trying to add any other .desktop files that start with "emuGame" are all ignored as it classes them all as the same shortcut/program.

**Comment by Enverex** [comment]
This seems to relate to https://github.com/ValveSoftware/steam-for-linux/issues/711 as well as trying to add Steam .desktop files (even ones created by Steam itself, installed in Wine) doesn't work. For example: adding PAC-MAN Championship Edition DX+'s .desktop File, which has an Exec line as follows...

    Exec=env WINEPREFIX="/home/arcade/.wine" wine C:\\\\windows\\\\command\\\\start.exe steam://rungameid/236450

Somehow in native Steam when added this becomes...

    Target: "/home/arcade/.local/share/Steam/ubuntu12_32/"

I have no idea where it's even getting that from as it's not even referenced in the .desktop file that was added. Not to mention it's copied literally nothing from the Exec line of the file that was selected.

**Comment by Enverex** [comment]
Renamed bug because this seems more general than simply issues with spaces in the name.

**Comment by 3vi1** [comment]
I ran into this same problem while playing with my new SteamOS system:  https://steamcommunity.com/linkfilter/?url=https://github.com/ValveSoftware/steam-for-linux/issues/3855

It seems to me that when adding the .desktop items, Steam should at the very least copy everything after the first space in the Exec into the Launch Options of the newly created item.  If you put them in there manually, it will work - but it's a pain for things with lots of long/complicated parameters like Enverex's original example.

**Comment by johnv-valve** [comment]
should be fixed in the just-released beta https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1447198999525237825
