### ISSUE TITLE
web overlay does not appear, bigpicture overlay does appear

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#3857]
I cannot get the web overlay to appear. The big picture
overlay does appear.

(mesa radeon drivers? keyboard xkb?...)

**Comment by gdrewb-valve** [comment]
Are you just pressing Shift+Tab?  Have you changed any defaults?  Can you add details on specifically what you're doing and what your configuration is?

**Comment by gdrewb-valve** [comment]
Also, what game are you running when you try to bring up the overlay?

**Comment by sylware** [comment]
My configuration is gnu/linux with a full state-of-art mesa opengl stack for
radeon GPUs. My radeon GPU is tahiti xt (R9 280X), I use the linux 4.1 with
all the fixes from AMD (agd5f). drm, llvm, mesa, xserver, ati xorg
driver, all from their git repos from last week-end.

I have a basic x11 window manager which does not support x11 hints for fullscreen
(it is a heavily modified old openbox).

I'm unable to make the web based overlay appear in any game I tried
(portal2/dota2/mark of the ninja...). I tried the default shift+tab, f12...  My
x11 xkb configuration is in /share/x11, but their is a link in /usr/share/x11
pointing at /share/X11.

The bigpicture overlay is appearing in all the games I tried with the above key
shortcuts.

-- 
Sylvain

**Comment by sylware** [comment]
It's still around. I noticed the following weird messages in the client log file I get:
ERROR: ld.so: object '/opt/steam/i686/home/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/opt/steam/i686/home/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by sylware** [comment]
latest issue #3984
