### ISSUE TITLE
Steam client segfaults when trying to access home dir from file browser while changing avatar

### ISSUE THREAD

**Issue by saucyfox** [ValveSoftware/steam-for-linux#3858]
Sorry for the long subject, but it's a little difficult to explain concisely. 

Basic spec rundown:
- OS - Arch Linux x64 w/ Linux 4.0.4-2-ARCH
- Steam Runtime Version - steam-runtime-release_2015-01-06

Steps to reproduce:
- Access profile via steam client and click "Edit Profile"
- In the Avatar section, click "Choose File"
- In the file browser, select the root directory under the "Look in:" menu (side note: it looks like the browser automatically opens to ~/.local/share/Steam/ and clicking the "Up" icon to move to the parent directory doesn't do anything; which is a bit strange.)
- From there, navigate to /home/ and click a user's home directory. The client crashes shortly after.

Here's what was written out to the terminal:

```
/tmp/dumps/assert_20150526165530_1.dmp
/home/user/.local/share/Steam/steam.sh: line 756:  4201 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20150526165530_1.dmp[4349]: Finished uploading minidump (out-of-process): success = no
assert_20150526165530_1.dmp[4349]: error: HTTP response code said error
assert_20150526165530_1.dmp[4349]: file ''/tmp/dumps/assert_20150526165530_1.dmp'', upload no: ''HTTP response code said error''
```

At a glance it's not really clear to me what's happening, and while I doubt this is happening to other users (I wasn't able to find any other reports like this), I'm definitely interested in determining what combination of factors could cause this. It doesn't look like a permissions issue, and I'm not sure what HTTP requests/responses have to do with the built-in file browser.

Any input is greatly appreciated.

**Comment by alexeyknyshev** [comment]
Confirm problem:
Steam from 23 July 15
package ver: 1437790054

Crashes when openning ~/home/%username%/Downloads
while selecting avatar file

**Comment by kisak-valve** [comment]
Hello @saucyfox, @alexeyknyshev, are either of you still experiencing this issue on an up to date system?

**Comment by alexeyknyshev** [comment]
Going to try to reproduce it in the near future.

пт, 21 Сен 2018 г., 16:35 kisak-valve <notifications@github.com>:

**Comment by kisak-valve** [comment]
Closing pending feedback.
