### ISSUE TITLE
Overlay does not accept mouse input for games running via Wine

### ISSUE THREAD

**Issue by lavacano201014** [ValveSoftware/steam-for-linux#3862]
I don't mean the game itself, I mean the overlay. If I press Shift+Tab, keyboard input works as expected. I can press Shift+Tab/Esc to exit the overlay, I can press Ctrl+Tab to cycle through active chat tabs, but if I move my mouse around, nothing happens. The mouse _appears_ when I go to the very edge, but is invisible otherwise (and does not manage to actually click anything).

Reproducible in Oblivion GOTY (disc version) and Skyrim (WinSteam and Skyrim under Wine, overlay in WinSteam disabled)

**Comment by mastercoms** [comment]
What Wine version?

**Comment by lavacano201014** [comment]
It's been pretty consistent for me since 1.6, if not earlier, with and without the wine-staging patches, but 1.7.43-staging for sure.

Also I confirmed that it's not just a Bethesda game, but Dragon Age Origins does it too. Interestingly, DAO's cursor appeared on the overlay but I couldn't click anything with it. I think it's something to do with how it captures the mouse.

I don't think I even have Gallium 9 support (proprietary nVidia drivers), but it's been pretty consistent with and without CSMT.

**Comment by mastercoms** [comment]
Hmm, because I had it working with Skyrim, but I'm not sure what my configuration was, let me check.

**Comment by lavacano201014** [comment]
I'm not using the Windows overlay at all, by the way, I'm not sure it's clear. I'm using the Linux overlay.

**Comment by mastercoms** [comment]
Sorry but I'm not familiar with that setup. So you're running Steam for Windows but it launches the Linux overlay?

**Comment by lavacano201014** [comment]
...sort of.

I have two instances of Steam running, Windows Steam and Linux Steam. Windows Steam runs in offline mode, and is configured to not open the overlay under *any* circumstances. From there, my Windows games are added to my Linux Steam instance as non-Steam shortcuts, and with that, the overlay is provided by the Linux version of Steam.

As I think I said, it's not exclusive to games that rely on Windows Steam. My copy of Dragon Age: Origins is an Origin copy (har har), and Windows Steam is in no way involved with it (it's usually not even running at the time). The overlay still fails to receive mouse input. I believe it's something to do with how wine captures mouse input.

**Comment by mastercoms** [comment]
Yeah, probably because wine is asking for mouse input since it is a game, and doesn't recognize the Linux Steam overlay.

But why go through such lengths to use the overlay? Is the Windows Steam overlay not working?

**Comment by lavacano201014** [comment]
I just prefer to launch all my games through the same Steam instance.

Also, I'd like to point out (once again) that it's consistent across Wine
games, including games where Steam is not required in any form whatsoever.
Therefore, Windows Steam isn't actually relevant to the bug that I'm
actually trying to report. If I completely uninstalled Windows Steam and
all games tied to it, the bug would persist for Wine games that aren't
involved. This is an actual problem.

So can you please stop hounding me about the Windows overlay? It's not
relevant to this bug. Thank you.

**Comment by MrSchism** [comment]
You probably won't see any real movement in this; Valve has really heavily hinted at not supporting issues regarding Steam and Wine.

**Comment by mastercoms** [comment]
I'm sorry if you felt that way. In no way was I trying to be intrusive or hounding, though now I see how you would think that.

Does the game respond to your mouse?

**Comment by lavacano201014** [comment]
>You probably won't see any real movement in this; Valve has really heavily hinted at not supporting issues regarding Steam and Wine.
Well they definitely won't fix things they don't even know about. Besides, this might even occur with some native Linux game - if Wine can do it...

>I'm sorry if you felt that way. In no way was I trying to be intrusive or hounding, though now I see how you would think that.
Apology accepted, and no harm done or offense taken.

>Does the game respond to your mouse?
Not with the overlay up, at least not in any way that I can notice. DAO's cursor did appear on the overlay, but clicking menu options didn't seem to have an effect. I should probably retest though, my memory is garbage.

**Comment by mastercoms** [comment]
If the game does not respond to the mouse when the overlay is working, it is probably a Steam for Linux bug, although caused by Wine.

**Comment by MrSchism** [comment]
I'm unable to reproduce with a pure Linux install. 

The description of the issue leads me to suspect that the issue may be the game in Wine capturing the cursor and not releasing it to the unrelated (Steam for Linux) overlay.

**Comment by mastercoms** [comment]
If the game was capturing the cursor, wouldn't the game respond to mouse input?

**Comment by MrSchism** [comment]
What I mean is that the game releases the cursor, but *not* to the Steam overlay.  It might just wind up buried (for lack of a better term) under the different layers (which is how compositors handle multiple items on screen).  That might be why the cursor only shows up at the very edges.

**Comment by mastercoms** [comment]
Yes, that makes sense. Could the Steam overlay somehow force capture to itself?

**Comment by MrSchism** [comment]
As I'm not a Valve employee, but rather a collaborator of theirs, I can't speak for the client's potential behavior.  Hypothetically, that's possible, but I don't think that's how the client currently handles it.

Having discussed this issue with some other developers who have worked with Wine in their projects (not Valve employees, mind you), they feel that this scenario is neither a Wine issue, nor a Steam issue, but rather a configuration issue.  That is, this is outside of the specifications of how either is really supposed to handle things.  You might be able to craft some sort of kludge to get it to work... maybe a trigger that forces the cursor to top when the Steam Overlay (linux) is brought up, but again, that's outside of the purview of either Valve or Wine.

**Comment by Plaque-fcc** [comment]
This happens also when I try using Steam overlay UI without any WINE, doesn't matter which game in: it simply pushes you back to the game many times, and rarely the overlay usable is.

**Comment by MrSchism** [comment]
@Plaque-fcc that's different from what was reported here.  That sounds more like #3093.

#3427 has some information that may help the OP's situation, too.  Granted, that's a stab in the dark.  First step (as mentioned on this second issue) is running Steam without the runtime: 
`STEAM_RUNTIME = 0 steam`

**Comment by lavacano201014** [comment]
I can't run with STEAM_RUNTIME=0, since I'm apparently missing a 32 bit lib that it needs, and it won't tell me precisely which.

Also, I triple checked, and I can confirm that neither the overlay nor the game itself actually responds to mouse input (using Dragon Age Origins again since that cursor still renders on top of the overlay somehow)

**Comment by MrSchism** [comment]
Exactly what is the error?

**Comment by kisak-valve** [comment]
For anyone stumbling upon this issue report, this issue predates Proton by several years and https://github.com/ValveSoftware/steam-for-linux/issues/3862#issuecomment-107778461 is a rare configuration.

Since we haven't heard from a Valve dev since the initial assessment, it's safe to say this issue is stuck in limbo with little to no chance of getting more attention.

If anyone figures out what's going on here and has an actionable hint, give me a ping and we can re-open this issue report.
