### ISSUE TITLE
Steam ignores soundcard capabilities, always does 16-bit audio

### ISSUE THREAD

**Issue by Cat-Ion** [ValveSoftware/steam-for-linux#3865]
If the ALSA soundcard used by Steam requires the sample format to be S32_LE, Steam will (presumably) still write S16_LE audio to it and produce nothing but noise. This can happen e.g. if the soundcard supports multiple sample formats and another software opens it first and selects anything but 16-bit LE, 'locking' it into that format. This can easily checked with ALSA's loopback module.

**Comment by kisak-valve** [comment]
Hello @Cat-Ion, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
