### ISSUE TITLE
ENTER key not working in SteamOS BPM browser

### ISSUE THREAD

**Issue by Vangamar** [ValveSoftware/steam-for-linux#3866]
The ENTER key does not work while editing text in multi-line text input boxes in the BPM browser in SteamOS. It instead makes a SteamOS UI low beep sound and does nothing. It's definitely not the keyboards I'm using (I've tried two so far), the ENTER key works in games and on the SteamOS desktop just fine.

**Comment by Vangamar** [comment]
Verified problem is in BPM browser for Ubuntu 15.04 and Archlinux, so Steam for Linux, not just SteamOS.

**Comment by kisak-valve** [comment]
Hello @Vangamar, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Vangamar** [comment]
Sorry man, it's been a while since I had an install of Steam for Linux
after moving, I will test this once I get one back up :-)
