### ISSUE TITLE
Overlay conflicts with Google Chrome and Chromium

### ISSUE THREAD

**Issue by Celexi** [ValveSoftware/steam-for-linux#3867]
The steam overlay will freeze Google Chrome if copy pasting from it, it will also crash the steam overlay and the game its running right after if a google chrome notification is shown.

it is probably also related to https://github.com/ValveSoftware/steam-for-linux/issues/3819

and https://github.com/ValveSoftware/Dota-2/issues/1766

**Comment by kisak-valve** [comment]
Hello @Celexi, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
