### ISSUE TITLE
Steam not working on Ubuntu 15.04 Nvidia Driver 346.72

### ISSUE THREAD

**Issue by tad1073** [ValveSoftware/steam-for-linux#3870]
$ steam
Running Steam on ubuntu 15.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by Tele42** [comment]
https://github.com/ValveSoftware/steam-runtime/issues/13

**Comment by gdrewb-valve** [comment]
Closing duplicate.
