### ISSUE TITLE
Steam installer breaks with newer Linux installs

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/steam-for-linux#3872]
This is an issue with how Steam updates the runtime specifically so read carefully because its hard to explain. 

Steam ships quite an old version of the runtime with its installer that is in both the Ubuntu repo and on the Steam website. It is fine with older versions of Ubuntu and other distributions but causes serious headaches when you install it. 

Steps to reproduce the problem: Install Ubuntu 15.04 (I don't know about Nvidia or Intel) install the closed source driver for AMD cards. Install steam, run steam, it crashes out with an error. 

Steps to fix: Steam needs to blindly update without checks if there is an update available. Ignore the steam runtime errors for libgl or anything else for that matter since they will be fixed with steam runtime updates. The problem is just with the default installer.

**Comment by johnv-valve** [comment]
Which version of the steam installer do you have? There is a fix that matches the problem you describe in 1.0.0.50 which is the latest available from www.steampowered.com. Ubuntu probably doesn't have this fix.

**Comment by shanefagan** [comment]
I tried the one from the Steam website 2 weeks ago and had the problem unless it was updated more recently. The one in the Ubuntu repo is much more out of date though and I saw different users complaining about that one. It might have something to do with the AMD driver update in 15.04.

**Comment by johnv-valve** [comment]
The AMD driver crashes if libXinerama:i386 is not present. The steam installer 1.0.0.50 includes libXinerama in the bootstrap runtime to avoid this problem. (you can also do 'apt-get libxinerama1:i386' to workaround the bug) 

Ubuntu is shipping an older version, 1.0.0.48. But for some reason they rev'd the epoch so it will appear newer than the Valve package. Please reopen this issue if you can reproduce this with 1.0.0.50.
