### ISSUE TITLE
[Family Sharing] Request access crash (in French)

### ISSUE THREAD

**Issue by gnuletik** [ValveSoftware/steam-for-linux#3873]
When clicking "Play" on a game that doesn't belong to you.

Two identical windows opens to ask me to buy the game or request the access.

I can click on the first window but then I have to click on the second window. 
If I click on a button of the second window. Steam crashes.

I have a dump that I can send.

I tested this on two ArchLinux computers : Same problem.

This bug only occurs when the UI is set to french.

**Comment by kisak-valve** [comment]
Hello @gnuletik, are you still experiencing this issue on an up to date system?

**Comment by gnuletik** [comment]
Hi @kisak-valve, I don't have any more game that I don't own sorry.
But it is easily reproducible on linux while setting the UI in french for someone who have a shared library.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing pending confirmation this issue is still occurring.
