### ISSUE TITLE
Camera doesen't stop rotating on Metro franchise games in both Fedora 21 and Opensuse Tumbleweed

### ISSUE THREAD

**Issue by MaxPayneFH** [ValveSoftware/steam-for-linux#3874]
While playing any game of the Metro franchise (Metro 2033 Redux, Metro: Last Light and Metro: Last Light Redux) on Fedora 21 or OpenSuse Tumbleweed the first person camera keeps rotating endlessly to the left, rendering the game unplayable, also on the options menu, things like the volume bar keep decreasing on their own to left.

This bug isen't present on Ubuntu 14.04LTS and in the past it wasen't present on Fedora 20, however I can't rectify whether or not this bug is present in Fedora 20 nowadays.

Basic System Specs:
OS: Fedora 21
Window Manager: Gnome 3.14.2
kernel: 4.0.4
Video Driver: 352.09(Nvidia beta proprietary driver directlly from their website)
Sound card: Realtek ALC889 (motherboard integrated sound card)
CPU: AMD FX8350
RAM: 16GB
Video Cards: Nvidia GTX760 SLI(AA mode)

**Comment by AsavarTzeth** [comment]
Just have to ask, are you using a controller? or have one connected at all while playing?

**Comment by MaxPayneFH** [comment]
Had that bug on GTA: Vice City when my joystick was connected, so this time around I already made sure no other peripherals besides the keyboard and mouse where connected.

**Comment by AsavarTzeth** [comment]
Oh, well. In that case I am sorry to say I can't help much.

In my case this issue occurs because the game binds something like the left trigger axis of the controller to the camera. Then because it incorrectly assumes that the center of that axis is 0 the player camera spins endlessly. That is unless I can hold it in the center, which is a trial by itself.

**Comment by ozmartian** [comment]
Exact same problem with my gaming mouse.. Can only play Metro titles with my crappy bluetooth spare mouse :-(  ? It has to be something dodgy in the games, doesn't happen anywhere else and i've tried removing xpad and joystick modules withouth effect.

**Comment by ozmartian** [comment]
Oh I should add, I'm running on latest Manjaro distro (Arch based w/ KDE flavour)

**Comment by kulga** [comment]
I had this identical issue. In my case, the kernel was interpreting my mouse as a joystick
```
/dev/input/by-id/usb-Microsoft_Microsoft®_Nano_Transceiver_v2.0-if02-event-joystick: symbolic link to ../event8
/dev/input/by-id/usb-Microsoft_Microsoft®_Nano_Transceiver_v2.0-if02-joystick:       symbolic link to ../js0
```

To **temporarily** stop the issue, you can remove the file. However, you you cannot remove the by-id or by-path symbolic links, you must delete the file. In this case **event8** and **js0** (This will change!)
If you unplug the device and replug it, it will return when the kernel probes it.

This shouldn't be considered a method of solving the issue, just a workaround so the game is playable.

**Comment by kisak-valve** [comment]
Hello @MaxPayneFH, are you still experiencing this issue on an up to date system?

https://github.com/denilsonsa/udev-joystick-blacklist may be related.

**Comment by kisak-valve** [comment]
Closing pending feedback.
