### ISSUE TITLE
Can no longer launch games Ubuntu 14.04

### ISSUE THREAD

**Issue by slmyers** [ValveSoftware/steam-for-linux#3875]
```
Game update: AppID 240760 "Wasteland 2", ProcID 8530, IP 0.0.0.0:0
ERROR: ld.so: object '/home/steve/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/steve/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Found path: /home/steve/.steam/steam/steamapps/common/Wasteland 2/Linux/WL2
Mono path[0] = '/home/steve/.steam/steam/steamapps/common/Wasteland 2/Linux/WL2_Data/Managed'
Mono path[1] = '/home/steve/.steam/steam/steamapps/common/Wasteland 2/Linux/WL2_Data/Mono'
Mono config path = '/home/steve/.steam/steam/steamapps/common/Wasteland 2/Linux/WL2_Data/Mono/etc'
Game removed: AppID 240760 "Wasteland 2", ProcID 8530 
```

**Comment by gdrewb-valve** [comment]
Does this affect all games or just WL2?  Did this work in the past?  If so, what changed between when it was working and when it wasn't?

**Comment by slmyers** [comment]
This did not affect all games. I tested three games: `Pillars of Eternity` and `Wasteland 2` failed, but `Civilization beyond earth` passed. All three of these games are part of a library shared by my brother. I think it had something to do with him being online when I started `Steam`, but when I did try to run the games he was definitely offline -- his PC was off.

**Comment by tomtomme** [comment]
This seems to be the same error that I have - the not working games are using the Unity 3D engine...
see https://github.com/ValveSoftware/steam-for-linux/issues/3888

**Comment by slmyers** [comment]
1. No, I didn't try that. 
2. I'm using a `radeon` driver.

**Comment by tomtomme** [comment]
try Installing the alsa-devel and alsa-devel-32bit packages - this solved the issue for me :)

thank Tuk for the fix, see https://github.com/ValveSoftware/steam-for-linux/issues/3888

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
