### ISSUE TITLE
Steam client segfaults when I cancel two "Want to play this game?" pop-up windows

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3884]
If I try to play a game which I bought from another account, Steam suggests me to buy it with **two** pop-up windows, and if I close them both Steam crashes with a segfault.

Download link for the content of `/tmp/dumps` folder:

https://mega.co.nz/#!xBJRCZrD!AGje-e0yGD7MuKynkv8NZZd2_DsL34w8dTR_beb1rCs

**Comment by kisak-valve** [comment]
Closing as the user has turned into a ghost and the linked file is gone.
