### ISSUE TITLE
Package in RPMFusion has unsatisfiable dependencies

### ISSUE THREAD

**Issue by stevenroose** [ValveSoftware/steam-for-linux#3893]
I just tried to install Steam on a new Fedora 22 installation using the RPMFusion repo as [described by the Steam wiki](https://developer.valvesoftware.com/wiki/Steam_under_Linux#Fedora).

However, one of the dependencies seems to be unsatisfiable:
```
$ sudo dnf install steam
Last metadata expiration check performed 0:00:28 ago on Sat Jun 20 23:52:33 2015.
Error: package steam-1.0.0.50-2.fc22.i686 requires libtxc_dxtn(x86-32), but none of the providers can be installed
```

What's weird is that it tries to install the i686 package while I'm on a 64-bit system. The wiki states clearly that the package should be available for 64-bit systems as well.

**Comment by Tele42** [comment]
The fedora package maintainer should be contacted with this information. Valve only maintains the packages for ubuntu and steamos. The last person to have worked on the fedora package appears to be Simone Caronni (slaanesh AT fedoraproject.org).

Steam is a 32 bit application (and has many 32 bit games), there is no 64 bit release at this time, so it needs 32 bit dependencies to run on a 64 bit system.

**Comment by gdrewb-valve** [comment]
Closing non-Valve issue.
