### ISSUE TITLE
Ubuntu 14.04 + fglrx + Steam + Obey -> gameoverlayrenderer.so

### ISSUE THREAD

**Issue by MPW1412** [ValveSoftware/steam-for-linux#3896]
Hello,

I'm having an issue with OBEY here. It worked yesterday with the oss radeon driver, after the update for Obey it stopped working and gave me this all the time, when starting Obey:

ERROR: ld.so: object '/home/mpw/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mpw/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Found path: /home/mpw/.local/share/Steam/steamapps/common/OBEY/OBEY.x86
Mono path[0] = '/home/mpw/.local/share/Steam/steamapps/common/OBEY/OBEY_Data/Managed'
Mono path[1] = '/home/mpw/.local/share/Steam/steamapps/common/OBEY/OBEY_Data/Mono'
Mono config path = '/home/mpw/.local/share/Steam/steamapps/common/OBEY/OBEY_Data/Mono/etc'

As this shall be an issue with mesa and the open source radeon driver, I installed catalyst:
$ lspci -k|grep -A2 290
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290]
	Subsystem: PC Partner Limited / Sapphire Technology Device e285
	Kernel driver in use: fglrx_pci

After that, I completly reinstalled steam, purged the package and manually deleted ~/.steam and ~/.local/share/Steam. The game was reinstalled.

System:
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

I googled around and tried like 10 solutions, none of those worked. As the problem came up with yesterday's updates, I guess I'll need a different fix.

Most ridiculous thing is, that I disabled the overlay, but steam still tries to load it :(.

Any ideas? Thanks for reading.

Greatings
MPW

**Comment by MPW1412** [comment]
Seems to be a problem with Unity: http://steamcommunity.com/app/346970/discussions/0/594820656479701708/

**Comment by gdrewb-valve** [comment]
The overlay hooks are used for streaming also.

Closing this as from the community thread it appears to be a confirmed Unity issue.
