### ISSUE TITLE
Couldn't set up the Steam Runtime. Running low on disk space?

### ISSUE THREAD

**Issue by orglce** [ValveSoftware/steam-for-linux#3899]
Hello.

Recently when I was trying to open Steam I got this message. "Couldn't set up the Steam Runtime. Are you running low on disk space?". Just this, no logs or anything.
Before this, Steam was working just fine. And no, I am not running low on space. I have 90 Gb of free storage on my SSD. 
I have tried some things I could find on other forums but nothing has helped. I have ubuntu 15.04 64bit.

These are the solutions I tried:
- http://steamcommunity.com/app/221410...4247/?l=german
- https://github.com/ValveSoftware/ste...ux/issues/2881
- I also tried purging and reistalling Steam
- I tried steam --reset but it gives me the same error

Thanks in advance!

**Comment by orglce** [comment]
I have resolved the problem. I didn't realize that i have installed Steam on my secondary hard drive. So, i just deleted the folder and run steam again. It asked me if i want to reinstall into ~/.local/share/Steam. And now everything works great.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by KotTheKitty** [comment]
Getting this error after having added games to an external folder that's no longer accessible. Currently trying to figure out the fix without completely nuking the Steam folder.

`
❯ steam
/usr/lib/steam/steam: ligne 105: /home/(user)/.local/share/Steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/logger-0.bash: Aucun fichier ou dossier de ce nom
bin_steam.sh[6656]: Couldn't set up srt-logger, not logging to console-linux.txt
/usr/lib/steam/steam: ligne 105: /home/(user)/.local/share/Steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/logger-0.bash: Aucun fichier ou dossier de ce nom
bin_steam.sh[6656]: Couldn't set up srt-logger, not logging to console-linux.txt
/usr/lib/steam/steam: ligne 105: /home/(user)/.local/share/Steam/ubuntu12_32/steam-runtime/usr/libexec/steam-runtime-tools-0/logger-0.bash: Aucun fichier ou dossier de ce nom
bin_steam.sh[6656]: Couldn't set up srt-logger, not logging to console-linux.txt
steam.sh[6656]: Running Steam on cachyos rolling 64-bit
steam.sh[6656]: STEAM_RUNTIME is enabled automatically
steam.sh[6656]: Unpack runtime failed, error code 1
steam.sh[6656]: Error: Couldn't set up the Steam Runtime. Are you running low on disk space?
/home/(user)/.local/share/Steam/steam.sh: ligne 89: LD_LIBRARY_PATH : variable sans liaison
`
