### ISSUE TITLE
Launching Dota2 fails on Fedora using Bumblebee

### ISSUE THREAD

**Issue by stevenroose** [ValveSoftware/steam-for-linux#3901]
I just installed Steam on Fedora using the [Negativo17 repo](http://negativo17.org/steam/).

I also have Bumblebee installed for my NVIDIA hybrid GPU. Steam runs fine with Bumblebee, but launching Dota fails. Running Dota does work without Bumblebee.

This is my log file:
https://gist.github.com/stevenroose/1afeda27f96dae2f0b98

EDIT: The difference between regular launch and optirun launch:
https://gist.github.com/stevenroose/92e521dcc67c009d5ed9#file-sdiff-200-diff

**Comment by stevenroose** [comment]
Did anyone look at this? Is this a Dota issue or a Bumblebee issue?

**Comment by stevenroose** [comment]
I created a gist with log files both with and without optirun, and created a difference view using `sdiff`.

This is the difference file: https://gist.github.com/stevenroose/92e521dcc67c009d5ed9#file-sdiff-200-diff

**Comment by stevenroose** [comment]
Why is this ignored?

**Comment by stevenroose** [comment]
Currently, the last entry in the log after Dota2 crashes is a segmentation fault.
```
*** ConCommand "togglecon/home/steven/.local/share/Steam/steamapps/common/dota 2 beta/dota.sh: line 77: 13691 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

**Comment by stevenroose** [comment]
I found a way to make it work! So please, Valve devs, fix this so that future Fedora users don't have to go through the hassle of not being able to play for over a month :)

Run steam like this to make it work:
```
LD_PRELOAD="libpthread.so.0 libGL.so.1" __GL_THREADED_OPTIMIZATIONS=1 optirun steam
```

I found the solution here:
https://unix.stackexchange.com/questions/133921/is-it-possible-to-run-steam-games-using-optirun

**Comment by kisak-valve** [comment]
Hello @stevenroose, are you still experiencing this issue on an up to date system?

**Comment by stevenroose** [comment]
@kisak-valve haven't used Fedora nor Steam in years :D So can't tell, I'm sorry.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.

**Comment by Jpfonseca** [comment]
The issue continues to happen in Archlinux for what I can tell. Tested it now :disappointed:
