### ISSUE TITLE
[fglrx] Steam with FGLRX crashing Linux

### ISSUE THREAD

**Issue by baz2142** [ValveSoftware/steam-for-linux#3903]
I had AMD 6850 with Kernel 4.0 and Mesa 11, steam worked fine. 
I bought AMD R9 285(Tonga), downloaded latest Fglrx 15.20 to replace unworkable Mesa on my chip,
after that, then I tried to start Steam, after few seconds, system just get down. Not Steam, Linux. 
I tried Arch Linux and Ubuntu with different DE's, tried start Steam in Big Pictures mod..
If launch Steam from console -- no one issue until system crash.
If launch Steam and immediately hide it, system will continue work fine,
only when Steam try to paint new GUI element, it can crash system.

Ubuntu 15.04
Xorg 1.17
Fglrx 15.20
Kernel 3.19

Logs:
-Xorg: http://pastebin.com/paLfBqFB
-Kernel http://pastebin.com/FXGJAS1f
-GPU-Manager http://pastebin.com/yUwNGVj0
-Steam error.log http://pastebin.com/ssxjs60e

**Comment by gdrewb-valve** [comment]
This seems likely to be an AMD driver bug.

**Comment by baz2142** [comment]
In Xorg logs new string, when Steam launched:
[   380.474] (II) fglrx(0): EDID vendor "SAM", prod id 1589
[   380.474] (II) fglrx(0): Using hsync ranges from config file
[   380.474] (II) fglrx(0): Using vrefresh ranges from config file
[   380.474] (II) fglrx(0): Printing DDC gathered Modelines:
[   380.474] (II) fglrx(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz eP)
[   380.474] (II) fglrx(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
[   380.474] (II) fglrx(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz e)
[   380.474] (II) fglrx(0): Modeline "640x480"x0.0   31.50  640 656 720 840  480 481 484 500 -hsync -vsync (37.5 kHz e)
[   380.474] (II) fglrx(0): Modeline "640x480"x0.0   31.50  640 664 704 832  480 489 492 520 -hsync -vsync (37.9 kHz e)
[   380.474] (II) fglrx(0): Modeline "640x480"x0.0   30.24  640 704 768 864  480 483 486 525 -hsync -vsync (35.0 kHz e)
[   380.474] (II) fglrx(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[   380.474] (II) fglrx(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
[   380.474] (II) fglrx(0): Modeline "1280x1024"x0.0  135.00  1280 1296 1440 1688  1024 1025 1028 1066 +hsync +vsync (80.0 kHz e)
[   380.474] (II) fglrx(0): Modeline "1024x768"x0.0   78.75  1024 1040 1136 1312  768 769 772 800 +hsync +vsync (60.0 kHz e)
[   380.474] (II) fglrx(0): Modeline "1024x768"x0.0   75.00  1024 1048 1184 1328  768 771 777 806 -hsync -vsync (56.5 kHz e)
[   380.475] (II) fglrx(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
[   380.475] (II) fglrx(0): Modeline "832x624"x0.0   57.28  832 864 928 1152  624 625 628 667 -hsync -vsync (49.7 kHz e)
[   380.475] (II) fglrx(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
[   380.475] (II) fglrx(0): Modeline "800x600"x0.0   50.00  800 856 976 1040  600 637 643 666 +hsync +vsync (48.1 kHz e)
[   380.475] (II) fglrx(0): Modeline "1152x864"x0.0  108.00  1152 1216 1344 1600  864 865 868 900 +hsync +vsync (67.5 kHz e)
[   380.475] (II) fglrx(0): Modeline "1280x800"x0.0   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz e)
[   380.475] (II) fglrx(0): Modeline "1280x960"x0.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
[   380.475] (II) fglrx(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
[   380.475] (II) fglrx(0): Modeline "1440x900"x0.0  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
[   380.475] (II) fglrx(0): Modeline "1440x900"x0.0  136.75  1440 1536 1688 1936  900 903 909 942 -hsync +vsync (70.6 kHz e)
[   380.475] (II) fglrx(0): Modeline "1600x1200"x0.0  162.00  1600 1664 1856 2160  1200 1201 1204 1250 +hsync +vsync (75.0 kHz e)
[   380.475] (II) fglrx(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)

**Comment by ranisalt** [comment]
I remember having that problem when using Fedora 20 and GNOME 3.10 with fglrx, all of a sudden Steam would crash the entire DE. I can't update the info since I now run Arch Linux, i3-wm and open Intel drivers.

**Comment by kisak-valve** [comment]
Hello @baz2142, @ranisalt, fglrx has been discontinued in favor of mesa and amdgpu-pro. If you are still experiencing this issue with one of those drivers on an up to date system, please open a new issue report.

Closing as video driver quality from 2015 is no longer relevant.
