### ISSUE TITLE
Half-Life 2+Episodes Won't Launch

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#3904]
I keep getting these errors when trying to launch Half-Life 2 and its episodes, including HL: Source. This happens with both the stable and beta builds of the games. I should note that I run Steam with the runtime disabled (STEAM_RUNTIME=0).

pid 13296 != 13295, skipping destruction (fork without exec?)
Failed to load the launcher

CSGO will start up just fine, as do all my other Steam games.

My specs are in my Steam profile, which is linked in my Github page.

**Comment by shoober420** [comment]
I also ran "ldd" on hl2_Linux, and I had all the dependencies required. It was working fine about a month ago.

**Comment by shoober420** [comment]
You can close this, they have been launching fine for a while now.

**Comment by Tele42** [comment]
@shoober420, you have the ability to close your own issue reports.

**Comment by shoober420** [comment]
This has been fixed a long time ago. My apologies.
