### ISSUE TITLE
Infinifactory fails to launch after update

### ISSUE THREAD

**Issue by BenTheElder** [ValveSoftware/steam-for-linux#3905]
There seems to be some weird edge case that has occurred twice for me now where after updating infinifactory steam fails to launch it, after rebooting it works and I can consistently quit and open steam and launch the game, but not immediately after an update without rebooting.

I've also sent an email to the developers.

I'm on ubuntu gnome 15.04 64 bit, running nvidia drivers. This occured out of and then in steam beta.

**Comment by Uramekus** [comment]
Fixed ages ago. infinifactory got a lot of updates during that time
![2018-08-23-00 46 57-screenshot](https://user-images.githubusercontent.com/4643873/44503880-1c3adb00-a66f-11e8-85fb-47590be07745.png)
![2018-08-23-00 51 00-screenshot](https://user-images.githubusercontent.com/4643873/44503882-1c3adb00-a66f-11e8-9bfe-444a35c71bf2.png)
