### ISSUE TITLE
STEAM_RUNTIME=0 bug on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by tomtomme** [ValveSoftware/steam-for-linux#3908]
log https://gist.github.com/tomtomme/cae063e02a80f7fbcdfd

It was mentioned here: https://github.com/ValveSoftware/steam-for-linux/issues/3697
and it was suggested to move this into a seperate bug-report, so here it is.

Steam does not launch without its runtime because of these errors:
´STEAM_RUNTIME=0 steam
/home/yuri/.local/share/Steam/steam.sh: line 145: DISTRIB_ID: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 145: DISTRIB_ID: unbound variable
/home/yuri/.local/share/Steam/steam.sh: line 159: DISTRIB_RELEASE: unbound variable´

Shished proposed this as a fix - which I can confirm works:
"Commenting the "if" string [in the steam.sh lines 144 and 158] and changing first "elseif" into "if" fixes this problem."
But this works only 1 time, because steam always pulls a backup of steam.sh...

Can this fix be included in steam?

**Comment by johnv-valve** [comment]
I believe this is fixed

**Comment by tomtomme** [comment]
confirmed - thx!
