### ISSUE TITLE
Unable to link latest master on Solaris

### ISSUE THREAD

**Issue by stuartthebruce** [ValveSoftware/steam-for-linux#3915]
I am no longer able to link a 64-bit version from master on Solaris 11. gmake results in,

Undefined                       first referenced
 symbol                             in file
g_weak_ref_clear                    /opt/csw/lib/amd64/libpangoft2-1.0.so.0
pango_font_map_changed              /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unicode_script_to_iso15924        /opt/csw/lib/amd64/libharfbuzz.so.0
g_atomic_int_dec_and_test           /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_atomic_int_inc                    /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unichar_compose                   /opt/csw/lib/amd64/libharfbuzz.so.0
g_unichar_decompose                 /opt/csw/lib/amd64/libharfbuzz.so.0
g_unichar_fully_decompose           /opt/csw/lib/amd64/libharfbuzz.so.0
g_weak_ref_get                      /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_weak_ref_set                      /opt/csw/lib/amd64/libpangoft2-1.0.so.0
g_unicode_script_from_iso15924      /opt/csw/lib/amd64/libharfbuzz.so.0
ld: fatal: symbol referencing errors
collect2: ld returned 1 exit status

However, ./configure passes and ends up with.

  configuration summary:

   - Package version: duc 1.3.3
   - Prefix: /usr/local
   - Database backend: tokyocabinet
   - X11 support: yes
   - OpenGL support: no
   - UI (ncurses) support: yes
   - Graph cairo support: yes

and picking on one of the unresolved symbols it looks like it is available,

root@ldas-dev:~# nm /opt/csw/lib/amd64/libglib-2.0.so.0 | grep g_unicode_script_to_iso15924
[5494]  |              672912|                  43|FUNC |GLOB |0    |15     |g_unicode_script_to_iso15924

Note, I have the same problem if trying to build 32-bit (i.e., without the -m64 flag and without needing to manually add -L/opt/csw/lib/amd64

**Comment by beansmyname** [comment]
I could be wrong but I think you meant to post this in [duc's issue tracker](https://github.com/zevv/duc/issues).

**Comment by stuartthebruce** [comment]
Indeed, this was submitted to the wrong issue tracker.
