### ISSUE TITLE
client fails to minimize to tray after latest update

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/steam-for-linux#3916]
After the latest update (Jul 3 2015, 13:50:32), clicking the "close" button on the main client screen fails to close the client window but only minimizes it to the taskbar. (And the longstanding bug where sending the X close command via keyboard or selecting "close" from the taskbar exits Steam entirely is still in place.)

**Comment by kisak-valve** [comment]
Hello @chrylis, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Back in 2015, this was the intended behavior for the close button and the default behavior controlled by `STEAM_FRAME_FORCE_CLOSE` has changed since then.
