### ISSUE TITLE
[Request] Reboot option gone in latest beta client - please add back

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steam-for-linux#3918]
Distribution: SteamOS Alchemist
Kernel version: 3.10-5-amd64
Steam Client version: 1428529675
Steam API verion: v017

I noticed the reboot option is gone for the latest Steam client beta. I am using SteamOS, and very much appreciated this option when tweaking and tinkering with the system in my living room. Especially since controllers don't turn on the system (without WOL hackery), I please ask this be added back as an option in the interface menu.

**Comment by MattDevo** [comment]
seconded - I dual boot between SteamOS and OpenELEC, and the removal of this option is a pretty big detriment to that.

**Comment by kisak-valve** [comment]
Closing as this was fixed some time ago.
