### ISSUE TITLE
Steam sometime crashes on attempt to take a screenshot

### ISSUE THREAD

**Issue by mattyy1hp** [ValveSoftware/steam-for-linux#392]
Steam crashes on attempt to take a screenshot.

This happening randomly in all games - sometime yes, sometime no.

---

Steps to reproduce:

1/ Start game
2/ Press F12
3/ Steam sometimes crashes, if not, try start game again and take screenshot again

---

I have terminal output for three games:

Killing Floor: http://pastebin.com/qNtDZAJT
World of Goo: http://pastebin.com/kymQ9kPw
Trine 2: http://pastebin.com/39ikxS6i 

---

System Specs:

AMD catalyst driver 12.11 beta11 manual install
AMD Radeon HD 6470M (beta11 shows 7400M series)

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 1400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.6.5-030605-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7400M Series

```
Driver Version:  4.2.11995 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6760
Number of Monitors:  1
Number of Logical Video Cards:  2
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  3418 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  593389 Mb
    Largest Free Hard Disk Block:  48404 Mb

Installed software:

Recent Failure Reports:
    Tue Dec 25 19:43:14 2012 GMT: file ''/tmp/dumps/assert_20121225204308_1.dmp'', upload yes: ''CrashID=bp-75667abd-7c68-4320-b50b-651b32121225''
    Tue Dec 25 19:44:57 2012 GMT: file ''/tmp/dumps/crash_20121225204450_2.dmp'', upload yes: ''CrashID=bp-a67d6428-e4e4-4862-bfda-768d72121225''
    Tue Dec 25 19:45:02 2012 GMT: file ''/tmp/dumps/assert_20121225204457_1.dmp'', upload yes: ''CrashID=bp-564016ac-c104-4525-be7e-29f542121225''
    Tue Dec 25 19:50:01 2012 GMT: file ''/tmp/dumps/crash_20121225204956_1.dmp'', upload yes: ''CrashID=bp-9dfdbd16-ae22-4b3a-890b-5beac2121225''
    Tue Dec 25 19:50:06 2012 GMT: file ''/tmp/dumps/assert_20121225205002_1.dmp'', upload yes: ''CrashID=bp-f436845c-8af2-4a64-8cf7-e37772121225''
    Tue Dec 25 19:53:02 2012 GMT: file ''/tmp/dumps/assert_20121225205301_1.dmp'', upload yes: ''CrashID=bp-8b090551-60e4-4e91-95b1-d07b02121225''
    Tue Dec 25 19:53:07 2012 GMT: file ''/tmp/dumps/assert_20121225205304_2.dmp'', upload yes: ''CrashID=bp-55ac2d19-e5d5-45a1-8da6-bc68a2121225''
    Tue Dec 25 20:08:30 2012 GMT: file ''/tmp/dumps/crash_20121225210824_1.dmp'', upload yes: ''CrashID=bp-d6be9f3c-4d41-4505-8ee4-7a15b2121225''
    Tue Dec 25 20:08:33 2012 GMT: file ''/tmp/dumps/assert_20121225210830_1.dmp'', upload yes: ''CrashID=bp-de0e8877-4d3d-4b6b-828c-de9a32121225''
    Tue Dec 25 20:09:25 2012 GMT: file ''/tmp/dumps/assert_20121225210922_2.dmp'', upload yes: ''CrashID=bp-957f3bec-7190-440e-b21a-024312121225''
    Tue Dec 25 20:12:07 2012 GMT: file ''/tmp/dumps/assert_20121225211159_1.dmp'', upload yes: ''CrashID=bp-0b078a05-0bc1-456d-a8b7-704be2121225''

**Comment by Ruedii** [comment]
I'm not sure if this is the same bug, but I've been experiencing a similar issue in Borderlands 2 under Steam in Linux after the release of latest stable update of the Steam Client.
