### ISSUE TITLE
Crash when watching videos in the store

### ISSUE THREAD

**Issue by jeifour** [ValveSoftware/steam-for-linux#3920]
This is always reproducable for me, maybe someone else also has this happening? I basically just have to start up Steam, then visit about 3-4 store pages and watch the video on there. At some point during the video the client will crash. I'm not really sure that it is really because of the video player, though. This is console output from a crash:

```
Installing breakpad exception handler for appid(steam)/version(1433441724)
Generating new string page texture 99: 384x256, total string texture memory is 3.24 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 103: 128x256, total string texture memory is 3.38 MB
Installing breakpad exception handler for appid(steam)/version(1433441724)
Failed to open BO for returned DRI2 buffer (1359x1050, dri2 back buffer, named 7).
This is likely a bug in the X Server that will lead to a crash soon.
assert_20150708102315_1.dmp[5041]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150708102315_1.dmp
/home/jei/.local/share/Steam/steam.sh: 756 行:  4724 Segmentation fault      (コアダンプ) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[0708/102605:WARNING:content_browser_client.cc(565)] No browser info matching frame process id 2 and routing id 1
assert_20150708102315_1.dmp[5041]: Finished uploading minidump (out-of-process): success = no
assert_20150708102315_1.dmp[5041]: error: HTTP response code said error
assert_20150708102315_1.dmp[5041]: file ''/tmp/dumps/assert_20150708102315_1.dmp'', upload no: ''HTTP response code said error''
```

And the file which it seemed like it couldn't upload: https://d.maxfile.ro/lhjzijituv.dmp
System information: https://gist.github.com/jeifour/c73da74f42666fab29cc

**Comment by lcfg** [comment]
I know this is a place for bug reports and not really a forum for exchanging fixes... However, for the sake of finding out what's happening here, could you do the following:

Create a file __/etc/X11/xorg.conf.d/20-intel.conf__ with the following content:

```bash
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
    Option      "AccelMethod"  "sna"
    Option      "TearFree"    "false"
EndSection
```
Afterwards, reboot and see if the crash still happens.

**Comment by jeifour** [comment]
I didn't have this file before. It seems like this change fixes my previous experience. I can't get it to crash again now.

**Comment by Tele42** [comment]
Since this change fixed it, you should find which setting causes/prevents the crash and report the information to Mesa, where the intel and/or interested devs can look into this. There's also a chance that this has already been reported and fixed in mesa's git-master.

**Comment by kisak-valve** [comment]
Hello @jeifour, are you still experiencing this issue on an up to date system?

**Comment by jeifour** [comment]
I'm not experiencing this anymore. Granted, I'm not owning the same computer hardware as in 2015 anymore.

**Comment by kisak-valve** [comment]
Thanks for the feedback, if someone else comes across a similar issue, then there would need to be a fresh investigation anyway.

Closing.
