### ISSUE TITLE
Unresponsive behavior of steam browser.

### ISSUE THREAD

**Issue by volvofixthis** [ValveSoftware/steam-for-linux#3921]
Way to reproduce:
1. Try to open discussion in some game community.
2. Try to click on right, bottom box of topics.
3. Check out this freeze.

https://dl.dropboxusercontent.com/u/25725476/screenshot-2015.07.08-14%3A01%3A36.png

Процессор:
    Поставщик:  AuthenticAMD
    Семейство процессора: 0x10
    Модель процессора: 0x4
    Степпинг процессора: 0x3
    Тип процессора: 0x0
    Тактовая частота: 2800 МГц
    Кол-во логических процессоров: 4
    Кол-во физических процессоров: 4
    HyperThreading:  Не поддерживается
    FCMOV:  Поддерживается
    SSE2:  Поддерживается
    SSE3:  Поддерживается
    SSSE3:  Не поддерживается
    SSE4a:  Поддерживается
    SSE41:  Не поддерживается
    SSE42:  Не поддерживается

Сеть:
    Скорость соединения: 

Версия ОС:
    Ubuntu 14.04.2 LTS (64 бит)
    Название ядра: Linux
    Версия ядра: 3.14.35-031435-generic
    Поставщик X-сервера: The X.Org Foundation
    Версия X-сервера: 11501000
    Менеджер окон X Window System: Compiz
    Версия клиента Steam: steam-runtime-release_2015-01-06

Видеокарта:
    Модель:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

```
Версия драйвера:  4.5.0 NVIDIA 346.72
Версия OpenGL: 4.5
Глубина цвета: 24 бит/пикс
Частота обновления: 60 Гц
ID производителя: 0x10de
ID карты:  0x11c0
Кол-во экранов:  1
Количество логических видеокарт:  1
Разрешение осн. экрана:  1920 x 1080
Разрешение рабочего стола: 1920 x 1080
Размер осн. экрана:
```

В дюймах: 18,78" x 10,55" (диагональ 21,54")
В сантиметрах: 47,7 см x 26,8 см (диагональ 54,7 см)
    Осн. шина: PCI Express 16x
    Осн. видеопамять: 2048 MB
    Поддерживаемое сглаживание:  2x 4x 8x 16x 

Звуковая карта:
    Аудио устройство: VIA VT1708S

Память:
    Оперативная память:  7984 МБ

Разное:
    Язык интерфейса:  Русский
    ЯЗЫК: ru_RU.UTF-8
    Микрофон:  Not set
    Места на диске:  172646 Мб
    Наиболее свободный диск:  71431 Мб

Установленное программное обеспечение:

Последние сообщения об ошибках:
    Tue Jul  7 19:04:59 2015 GMT: file ''/tmp/dumps/assert_20150707220400_6.dmp'', upload yes: ''CrashID=bp-c369ae7f-789c-4a16-ac84-e44a22150707''

**Comment by kisak-valve** [comment]
Hello @volvofixthis, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
