### ISSUE TITLE
Fonts in Steam Overlay randomly changed to Courier New

### ISSUE THREAD

**Issue by bulikandryo786** [ValveSoftware/steam-for-linux#3923]
![couriernew](https://cloud.githubusercontent.com/assets/13306831/8641484/034af6e0-28e4-11e5-889b-e69a3cdd8c9b.png)

I don't know how this happened, but for some reason the font normally displayed in the steam overlay changed to courier new.  This happened after I was editing some L4D2 configs to try to get splitscreen to work, if that narrows it down at all.  I don't see how that would affect the steam overlay for all games, but shit happens I guess.  Please fix this, it's a pain to read, and if it is just something I did, please tell me how to get things back to normal.

**Comment by bulikandryo786** [comment]
Restarting steam fixed this, but you guys might wanna still look into it.  No idea wtf happened.

**Comment by evilblade666** [comment]
Just exactly the same thing happened to my Steam, also reverting back to normal on the next start. So I may confirm this happens sometimes for whatever reason.

**Comment by ONicholai** [comment]
This happens after switching to Big Picture Mode, then back to desktop.

**Comment by z3ntu** [comment]
I have the same issue right now. I will try restarting.

**Comment by flotts** [comment]
I found that the best way to fix this problem permanently is by installing a Steam Skin/Theme.

**Comment by werecat** [comment]
If you install microsoft fonts, then opening and closing big picture will not change the font on the overlay. I think the important font is Arial though I could be wrong. If it is then you could probably get away with installing a font of your choosing as Arial.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by z3ntu** [comment]
What I've tested:
1. Launch steam
1. Launch game - fonts are fine in overlay
1. Enter big picture mode
1. Launch game - fonts are fine in overlay
1. Exit big picture mode
1. Launch game - fonts are still fine in overlay

**Comment by z3ntu** [comment]
What I've tested (on Arch Linux with linux-steam-integration):
1. Launch steam
1. Start a game - overlay font is fine
1. Enter big picture mode
1. Start a game - overlay font is fine
1. Exit big picture mode
1. Start a game - overlay font is still fine

**Comment by kisak-valve** [comment]
Thanks for retesting @z3ntu, closing.
