### ISSUE TITLE
Show on disk for screenshots won't work in MATE

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#3924]
Under MATE desktop the Show On Disk feature for screenshots doesn't work.

For some reason on my desktop it loads up a media player?

**Comment by gdrewb-valve** [comment]
I believe the Steam client just does an xdg-open on the screenshot filename, so the behavior is going to come down to what your configuration is for xdg-open.

**Comment by liamdawe** [comment]
I have my filemanager set in the preferred applications, so I've reported it to MATE directly. Not had this issue in other desktops.

**Comment by kisak-valve** [comment]
Closing per https://github.com/mate-desktop/mate-desktop/issues/184#issuecomment-122509064.
