### ISSUE TITLE
Steam launcher browser problem!

### ISSUE THREAD

**Issue by Iseg** [ValveSoftware/steam-for-linux#3928]
Hi, recently there was a problem and it does not load the page the customer such as a shop, profile, etc., ie, All the pages that are loaded internal client browser instead of pages blank black screen and wheel load the page. The client has been reset to reset the profile (in the system), it did not help! I applied to the support they gave me did not help, sent here for a solution to my problem!

Steam version (1433441724), if install beta version, problem not solved!

Screen problem: http://5.firepic.org/5/images/2015-07/21/2tyqv9b8t617.png

In console steam say: 
[0721/185604:ERROR:child_process_launcher.cc(479)] Failed to launch child process
[0721/185607:ERROR:child_process_launcher.cc(479)] Failed to launch child process

My System info:
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x6
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2900 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Operating System Version:
    Ubuntu 13.04 (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11303000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GT 640/PCIe/SSE2/3DNOW!

    Driver Version:  4.3.0 NVIDIA 313.30
    OpenGL Version: 4.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xfc1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 1600 x 900
    Primary Display Size: 17,44" x 9,80"  (20,00" diag)
                                            44,3cm x 24,9cm  (50,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT1708S
    
Memory:
    RAM:  4034 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  105486 Mb
    Largest Free Hard Disk Block:  61125 Mb
    

Help!!!

**Comment by Tele42** [comment]
@Iseg Nvidia drivers 313.30 is quite old these days, I'm curious if a newer driver version changes the behavior.

As a side note, Ubuntu 13.04's upstream support ended on January 27, 2014, but valve has not made a stance if they match upstream's release lifecycle.

**Comment by Iseg** [comment]
@Tele42 new video driver may be installed only on the new OSes, what is my OS is outdated I know, but for some reason I do not want to upgrade, you want to say that the client browser does not work because of outdated systems and drivers?

**Comment by Iseg** [comment]
My problem is so complex that no one can help me?

**Comment by Iseg** [comment]
Support can not help, no one here knows what the problem is, there are still forums or community where I write to address the problem or all still working or not?

**Comment by Iseg** [comment]
Okay so hard if I close the issue, it does not work then you can delete the Steam!
