### ISSUE TITLE
Terraria Linux beta - resize failure (but manual works) and lockups with AMD binary driver (for radeon 285)

### ISSUE THREAD

**Issue by mjevans** [ValveSoftware/steam-for-linux#3933]
When launching BuildID: 706396 and going through the initial menus the game became unresponsive when the controls screen was selected; however I have not been able to repeat this.

https://gist.github.com/mjevans/7649d188401e44f62de5

For some reason resizing the window automatically fails.  However it does accept resize updates from the window-manager (kwin) and re-launches with the previous window size.

**Comment by mjevans** [comment]
Here is a crash log: https://gist.github.com/mjevans/ee929957555d2b93e4c6

**Comment by mjevans** [comment]
Checking again after a cold boot this morning, BuildID: 708143 still has this same issue with the Radeon driver that the maintainers in my distribution feel is 'stable' (I have heard that there are a number of undesirable issues with the more recently released 'beta' version).

**Comment by MrSchism** [comment]
Have you also mentioned this to the Terraria devs?

**Comment by mjevans** [comment]
This is the only place I know of to post this.  If there were a function for reporting a bug/lockup via steam (it doesn't detect this as a crash since the game live-locks) I'd use it.  If there were a list here I'd use that.

**Comment by mjevans** [comment]
Very strangely, the build hasn't updated, and I don't recall having restarted (only suspended/resumed) within the last day, but for some reason Terraria Linux Beta build 708143 actually was working today.

Even more confusingly, previously it should have had better access to system resources, as /that/ test was right after a cold boot, while now I've played Minecraft and reloaded (too many) Chrome/Chromium tabs.

A way of collecting more concrete data, particularly on graphics sub-system resources at the time of the error, seems desirable.

**Comment by mjevans** [comment]
I decided to try again while watching a video... livelocked again.

**Comment by mjevans** [comment]
https://gist.github.com/mjevans/172f92a2b4ed3d062024

The crashes seem fairly frequent, and the game now exits on lockup after I installed gdb.

**Comment by mjevans** [comment]
I've also actually looked (since no one helpfully linked) and after waiting for my request to join the 'user community' posted the bug report there too: http://forums.terraria.org/index.php?threads/crash-lockup-just-after-loading-world-drawing-failure-in-libmonosgen-2-0-s0-opengldevice-glenum.28340/

**Comment by mjevans** [comment]
The fourth beta of this game, buildID: 710313 seems to have, probably, fixed the issue.

I haven't been able to repeat it, but I'll test it again with some more intense videos to make sure.

**Comment by mjevans** [comment]
I'm willing to believe that the update fixed this issue.
