### ISSUE TITLE
Steam/GNOME Freezes Arch Linux amd64

### ISSUE THREAD

**Issue by markzz** [ValveSoftware/steam-for-linux#3934]
When running steam for a few minutes, Steam causes GNOME to not respond to mouse and keyboard commands, but animations will still play.  For example, if you tap the top-left hot corner with your mouse, the animation plays, but the Activities Overview will not open.  Not even pressing the Super key (Command on Mac; Windows Logo on other) will open it.  The only way to fix it sometimes is to open a console (`CTRL+ALT+F2`) and restart X (`systemctl restart gdm.service`).

In the past I avoided this issue by running Steam without the runtime `STEAM_RUNTIME=0 steam`, but that no longer works because it appears to segfault and crash if I do.  This issue without the runtime is present already on this site and I will not go into that.

GNOME Version: 3.16 and was present in 3.14.

**Comment by Tele42** [comment]
@markzz There's a chance the steam_runtime=0 segfault may be due to a bad interaction between steam and very new udev, at least I am seeing a startup crash right about when steam tries to initialize the main window with ```STEAM_RUNTIME=0``` and eudev-3.1.2 on gentoo, but not older udev/eudev.

**Comment by markzz** [comment]
This bug is referring to the steam runtime being enabled.  I am pretty sure it has to do with libgudev, which I covered here (https://markzz.com/blog/post/6/).

**Comment by Tele42** [comment]
Right, I specifically addressed the part where I might have been able to give additional insight from a different point of view.
On gentoo with the steam-overlay, steam is given /opt/steam-runtime/usr/lib32/libgudev-1.0.so.0.1.1 to resolve that dependency, which has been in place for a fairly long time. There is a new compatibility issue with eudev-3.1.2 (which is an equivilent to udev-220) and works here with eudev-1.10-r2 (udev-216). In both cases the system version of gudev is /usr/lib32/libgudev-1.0.so.0.2.0.

If you want to stop discussing this part of the issue report and focus on the main issue, that's fine, I won't derail it any further.

**Comment by Oxalin** [comment]
@markzz still experiencing this problem?

**Comment by markzz** [comment]
@Oxalin I haven't used Steam on that computer without being in my Windows VM for some time now. The VM is where I play all of my games and have no need to run Steam natively on that machine. I do believe it was an issue only with the proprietary Nvidia driver. I have no idea whether it has been fixed or not nor do I really care anymore personally.

**Comment by kisak-valve** [comment]
Closing per the last comment.
