### ISSUE TITLE
Steam won't work with Ubuntu(14.04) kernel 3.13.0-59-generic

### ISSUE THREAD

**Issue by salihozd** [ValveSoftware/steam-for-linux#3938]
I had an update today via Ubuntu Software Updater. It updated kernel 3.13.0-58-generic to 3.13.0-59-generic. Steam client is normal but library have some issues. Steam says, "Available space is 0MB" but i have enough speca... Downgraded the kernel to 3.13.0-58-generic and it's ok again.

If you test and can not generate the error, i can update and generate it for you.

**Comment by alien2003** [comment]
The same problem on Ubuntu 14.04 x64

**Comment by Mecha-Weasel** [comment]
Same issue already reported in this issue: https://github.com/ValveSoftware/steam-for-linux/issues/3936

**Comment by gdrewb-valve** [comment]
I changed the title of #3936 to call out that it is related to the update so closing this as a duplicate.
