### ISSUE TITLE
Disk write error since recent update

### ISSUE THREAD

**Issue by Freeman-AM** [ValveSoftware/steam-for-linux#3939]
Hello,

Since an update (i read it was related to steamVR update) at 28/07/2015, i'm unable to update nor play those games and getting a DISK WRITE ERROR :
Team Fortress 2
Half-Life 2
Half-Life 2: Episode One
Half-Life 2: Episode Two
Counter Strike: Source

When downloading some other games like Left 4 Dead is working well.

Notable fact, when i delet half life and try to ReDL it from scratch, i'm getting not enough place on hard drive. (there is enough), 2nd try work fine, download start but it's quickly stopped by DISK WRITE ERROR.

I followed this step.

https://support.steampowered.com/kb_article.php?ref=9709-FKCB-4230

My hard drive is not faulty.
So i guess something is fucked with recent updates.

**Comment by Freeman-AM** [comment]
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x10
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3393 Mhz
    2 logical processors
    1 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
    
Video Card:
    Driver:  NVIDIA GeForce GT 740

    DirectX Driver Name:  nvd3dum.dll
    Driver Version:  10.18.13.5330
    DirectX Driver Version:  10.18.13.5330
    Driver Date: 17 June 2015
    OpenGL Version: 4.5
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: NVIDIA GeForce GT 740
    VendorID:  0x10de
    DeviceID:  0xfc8
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 18.98" x 10.67"  (21.73" diag)
                                            48.2cm x 27.1cm  (55.2cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 
    
Sound card:
    Audio device: Haut-parleurs (Realtek High Def
    
Memory:
    RAM:  4017 Mb
    
Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  1430696 Mb
    Largest Free Hard Disk Block:  700135 Mb
    OS Install Date: janv. 01 1970
    Game Controller: None detected

**Comment by Tele42** [comment]
This issue tracker is limited to the steam client on linux, please use valve's main support page (https://help.steampowered.com/).
