### ISSUE TITLE
Since update : impossible to run games, filesystem error and no more store

### ISSUE THREAD

**Issue by Abalson** [ValveSoftware/steam-for-linux#3940]
Hello, 

Since a system update yesterday, the steam client is not able to run my games. For the client, it looks like the game are not installed anymore. Actually they are still sitting in the steamapps folder but the client keeps asking for a new install location : 
![step2](https://cloud.githubusercontent.com/assets/13560518/8967693/d2687702-3638-11e5-98da-1e547de2ce5f.jpg)

I select the Steam folder in my "home" directory (so I have all needed rights) and click "New Folder" (which correctly creates the folders SteamLibrary and steamapps ). Then I click "Select" and the following messages appears : 

![step3](https://cloud.githubusercontent.com/assets/13560518/8967732/17c3ed2c-3639-11e5-95f0-63cb49d3d6c8.jpg)
"new steam library must be on a filesystem mounted with execute permissions"

Also, I noticed that the Store page is not displayed anymore (which cannot be a network error, network connectivity is fine) : 
![step4](https://cloud.githubusercontent.com/assets/13560518/8967765/4c5fe52c-3639-11e5-9986-a93246f68c1d.jpg)

Troubleshooting steps : 

1. reset 
$ steam --reset
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.

2. delete / reboot / install
sudo apt-get autoremove --purge steam
sudo apt-get install steam
delete the .steam folder
-> The issue is still the same. 

Please let me know which debugs may be useful in oder to tshoot the issue.

**Comment by Tele42** [comment]
@Abalson this issue is being tracked on #3936.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
