### ISSUE TITLE
Steam fails to start since today

### ISSUE THREAD

**Issue by jeifour** [ValveSoftware/steam-for-linux#3941]
Output

```
Running Steam on manjarolinux 0.8.13.1 64-bit
STEAM_RUNTIME is enabled automatically
[2015-07-30 05:00:29] Startup - updater built Jul 23 2015 11:48:12
Installing breakpad exception handler for appid(steam)/version(1437790054)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

Same thing happens when I disable Steam Runtime. Changing locale also didn't help (right now ja_JP.utf8).

System:

```
$ sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: GM206 [GeForce GTX 960]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:31 memory:ee000000-eeffffff memory:d0000000-dfffffff memory:e0000000-e1ffffff ioport:e000(size=128) memory:ef000000-ef07ffff

$ lscpu
アーキテクチャ: x86_64
CPU 操作モード:   32-bit, 64-bit
バイト順序:       Little Endian
CPU:                   8
オンラインになっている CPU のリスト:0-7
コアあたりのスレッド数:2
ソケットあたりのコア数:4
ソケット数:       1
NUMA ノード数:     1
ベンダー ID:       GenuineIntel
CPU ファミリー:   6
モデル:             60
モデル名:          Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
ステッピング:    3
CPU MHz:               3827.304
CPU 最大 MHz:        3900.0000
CPU 最小 MHz:        800.0000
BogoMIPS:              6998.08
仮想化:             VT-x
L1d キャッシュ:   32K
L1i キャッシュ:   32K
L2 キャッシュ:    256K
L3 キャッシュ:    8192K
NUMA ノード 0 CPU:  0-7

$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:    0.8.13.1
Codename:   Ascella
```

**Comment by jeifour** [comment]
Steam successfully starts up after I restarted my system. I seemingly lost a lot of my games, though. Only 10 are still listed as installed, where before there were about 50 or more. I also seem to have over 700gb free hard disk space when I had about 500gb free hard disk space before. I don't seem to have lost anything else than the games, though. My personal files are still intact.

**Comment by lahtis** [comment]
Steam games are installed then, but the steam can not find them. If I try to re-install. Steam says that the disk space is not enough. What in this situation can do. I have 285 GB free space. I installed games take up space 472.5 GB. Installed games are still Steam default location. Using  Ubuntu 14.04 LTS   Steam Runtime -version: steam-runtime-release_2015-06-12

**Comment by Oxalin** [comment]
@jeifour and @lahtis , is this bug still encountered?

@jeifour , if you had more than one library folder in your Steam setup, their paths will be missing. After adding the missing path you had previously configured, Steam should be able to detect your missing games.

@lahtis , is it possible that you have no more space on one of your partitions, even though you still have plenty on the whole harddrive?

**Comment by lahtis** [comment]
No. I have 285 GB free space in same partition. Fix in the problem, removed all games and steam. And reinstalled steam and all my games. Maybe is fixed.

**Comment by kisak-valve** [comment]
Hello @jeifour, @lahtis, have you seen this issue in recent history?

**Comment by lahtis** [comment]
nope. Fixed.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
