### ISSUE TITLE
Big picture: Spurious input forever

### ISSUE THREAD

**Issue by alexhultman** [ValveSoftware/steam-for-linux#3943]
I've been following the development of big picture for a while. Recently the big picture had become absolutely 100% broken. I click around, scroll a little on the mouse wheel and there we have it: big picture begins to receive spurious input events that never did occur. Triggers 100% after spending 5 - 10 seconds in big picture.

**Comment by tjaart** [comment]
I can confirm that I am experiencing the same issue in Kubuntu 15.04. What I tried:

- Unplugging controllers
- My Microsoft Keyboard was showing up as a joystick, fixed that in /etc settings file but the issue persists.

It seems that the input is moving UP. The Ui move sound plays repeatedly as if someone is mashing a key. The main screen is stuck on "Downloads" in the top left corner.

**Comment by alexhultman** [comment]
Yep, nice to hear that someone else is having this completely-broken-piece-of-software bug as I am.

**Comment by tjaart** [comment]
It's annoying and makes Big Picture unusable for me.

**Comment by tjaart** [comment]
So I found what is causing this for me at least. Unplugging my keyboard solved the problem. It seems that this issue has also already been reported:

https://github.com/ValveSoftware/steam-for-linux/issues/3384

**Comment by alexhultman** [comment]
I just received my pre ordered Steam Controller. It is simply awesome. But I cannot use it because Big Picture is broken. Even if it can be traced to broken Microsoft devices I don't get why everything else is working perfectly well. I mean, if games doesn't have this issue - why is Big Picture having this issue? Why not rewrite in input in the same way games do it? I tried removing my keyboard but it still doesn't work. I'm just saying - if an app can get correct events for keyboard input then why cannot Big Picture manage to get this right?

**Comment by alexhultman** [comment]
Why is my mouse and keyboard working perfectly well in *all* apps and games, yet Big Picture is completely broken? That is one question one should ask before blaming the kernel.

**Comment by alexhultman** [comment]
It is my CM Storm Mizar that is causing the input. And this mouse is working perfectly in all other apps and games. Even on 8200 DPI.

**Comment by alexhultman** [comment]
Wow I actually found that Metro 2033 Redux also has the exact same bug as Big Picture. This means I was very wrong about other apps. This really seems to be a deeper issue. My Mizar is recognized as a gamepad and in game I'm rotating left forever.

**Comment by tjaart** [comment]
@alexhultman I think we should provide feedback on the bug I linked. There are more people with the same issue and more details there in general. It doesn't look like Valve is doing anything about it. Maybe if we are on the same bug they will pay more attention.
