### ISSUE TITLE
Steam not close 

### ISSUE THREAD

**Issue by cppvoid** [ValveSoftware/steam-for-linux#3946]
Steam not close no matter what i do. The icon is still alive but it don't reacts, when i open a terminal and tip the command 'ps -b', its not show any process and looks inactive. So i shutdown the PC and its end in a blackscreen. The only way to bring down the PC is to hold the powerbutton.

This happens any time when i close steam.

System:
Linux Mint 17 64 bit Cinnamon 
Kernel 3.19.0
GeForce GT 740M
nvidia-331

**Comment by kisak-valve** [comment]
Hello @cppvoid, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
