### ISSUE TITLE
Steam does not launch due to missing "Chrome SUID sandbox"

### ISSUE THREAD

**Issue by bcnjr5** [ValveSoftware/steam-for-linux#3947]
When I try to launch Steam, it throws an error about a missing SUID sandbox, then freezes until I kill it.
##### Log

```
bcnjr5@MB ~ % /usr/bin/env STEAM_RUNTIME=0 LD_LIBRARY_PATH=/home/bcnjr5/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib  /usr/bin/steam $USER
Running Steam on debian 8 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1437790054)
Installing breakpad exception handler for appid(steam)/version(1437790054)
Installing breakpad exception handler for appid(steam)/version(1437790054)
[0801/195622:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150723114749)
Installing breakpad exception handler for appid(steamwebhelper)/version(1437790054)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150723114749)
Installing breakpad exception handler for appid(steamwebhelper)/version(1437652069)
Installing breakpad exception handler for appid(steamwebhelper)/version(1437790054)
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamUI/../common/steam/client_api.cpp (320) : Assertion Failed: ClientAPI_InitGlobalInstance: InternalAPI_Init_Internal failed, most likely because you are missing a 32-bit dependency of steamclient.so (the Steam client is a 32-bit app).

Assert( Assertion Failed: ClientAPI_InitGlobalInstance: InternalAPI_Init_Internal failed, most likely because you are missing a 32-bit dependency of steamclient.so (the Steam client is a 32-bit app).
 ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamUI/../common/steam/client_api.cpp:320

Installing breakpad exception handler for appid(steam)/version(1437790054)
assert_20150801195622_5.dmp[11609]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150801195622_5.dmp
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/steamUI/SteamStartup.cpp (780) : Assertion Failed: ! "There was a problem with your Steam installation.\n" "Please reinstall steam.\n"
^C
```
##### OS Info

Posted on Gist, since it is probably mostly irrelevant: https://gist.github.com/bcnjr5/a52b4ee66cdc3dbd9c38

**Comment by bcnjr5** [comment]
This might be my fault, as I used apt-get to install every missing i386 library it specified when it crashed. (libcurl, libgconf, libnss, etc.)

**Comment by MrDetonia** [comment]
Exact same issue here. I also manually installed i386 libraries, due to the default steam runtime failing to load video drivers correctly. Any ideas on a fix yet?

**Comment by bcnjr5** [comment]
I see 2 solutions:
 1. Everyone with this problem downloads the Chrome SDK, etc. (still figuring out how)
 2. They turn off the development stuff in release versions of Steam. (not sure on this yet)

I'll look at the source file mentioned in the error message and see if the latter is a trivial fix.

**Comment by felixmole** [comment]
I got a similar problem: Steam will run perfectly fine except for the browser. Impossible to see the "Update news", either. Every time I try to use the browser, the following message pops up:

[1206/155943:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

**Comment by Oxalin** [comment]
@felixmole While I don't see why this would prevent Steam from running (about the others experiencing a hang), that could explain why I'm unable to launch any videos from my library though... Are you able to launch one of the free videos available from Steam?

**Comment by felixmole** [comment]
@Oxalin Indeed, it's probably something else, and this indicates that the missing "Chrome SUID sandbox" is apparently not (directly) related to the freeze reported here.

As to the "free videos available from Steam", I'm not sure what you mean. What free videos? Those available from the store? One thing is certain, I'm unable to do anything that requires the browser, so no store, no community, no "Update news", etc. The pages remain blank, there is just "Failed to launch child process" on the log.

**Comment by Oxalin** [comment]
@felixmole I was indeed talking about the videos available in the store. On my side, the Videos under Library is the only thing not working and could be related to missing SUID sandbox...

**Comment by andwn** [comment]
I was running into this issue today and solved it by going to ~/.steam/bin32 and running:

LD_LIBRARY_PATH=. ldd steamclient.so

That lists every dependency. I was still missing these

libnm-glib.so.4 => not found
libnm-util.so.2 => not found
libudev.so.0 => not found

I don't know what these packages are in your OS but from the AUR I installed lib32-libnm-glib and lib32-libudev0. That did the trick.

**Comment by bcnjr5** [comment]
As to the freeze I originally reported, it turns out that my computer just has a problem with C# applications.
A few other applications written in C# would hang at various points as well; it seems to be an issue with some common library.

If I let steam hang for around an hour, the screen will eventually display stuff. (but with a framerate of ~0.0000000001 FPS, it's unusable)

So the SUID sandbox doesn't cause a freeze; the freeze is just a special case that is probably not worth pursuing. (my system is an old Atom, anyway)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? The libcef log lines look unrelated.

**Comment by kisak-valve** [comment]
Closing pending feedback.
