### ISSUE TITLE
Steam hangs on launch

### ISSUE THREAD

**Issue by rbingham** [ValveSoftware/steam-for-linux#3951]
When I try and launch steam, it hangs and won't open. Below is the console output when running steam.

```console
Setting up Steam content in /home/username/.local/share/Steam
/home/username/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/username/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/username/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
```

I am running steam in arch linux and have tried uninstalling and reinstalling steam and my graphics drivers. I have also searched for ways to fix this issue.

I have steam installed on an almost identical arch installation and was able to install steam without any issues. The only main difference is that this computer has a dedicated graphics card installed (nvidia gtx 970 m). 

Note: I have installed all the 32 bit libraries required by steam.

Note: I have been able to get rid of the version_error by following the steps at the bottom of  issue [3851](https://github.com/ValveSoftware/steam-for-linux/issues/3851). The output after applying those fixes is below.

```console
Running Steam on arch 4.1.4-1-ARCH 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
```

Please let me know what else I can do to solve this issue.

**Comment by ViktorF** [comment]
I got the exact same error.
I recently updated the kernel and my nvidia driver to the beta one. My guess is the error come from one of these updates because steam worked just fine before.

**Comment by SpoolC** [comment]
third with this exact issue, I also just updated the kernel to 4.1.4 nvidia driver is currently 352.30

**Comment by ViktorF** [comment]
Ok i solved the problem on my end. 
My nvidia driver (version 355.06) caused the problem. So i removed this version and installed 352.30 version of it. 
Now steam is starting just fine again.

**Comment by Oxalin** [comment]
For those still experiencing this problem (and @ViktorF solution seems to point exactly at the root), have a look at this section of Arch's wiki: https://wiki.archlinux.org/index.php/Steam#You_are_missing_the_following_32-bit_libraries.2C_and_Steam_may_not_run:_libGL.so.1

**Comment by ViktorF** [comment]
Yeah I recently got steam working even with the beta driver.
I literally face-palmed myself when I found out why it didn't start in the first place. 
I just forgot to install the 32 bit version of the nvidia beta driver.

**Comment by BeatVids** [comment]
Ahhh thank you so so much ViktorF!
In case any future readers read this, if you are using "testing" repos for 64 bit, make damn sure you allow "testing" for your 32 bit.

God, I spent so much time on this, thanks again..

**Comment by rbingham** [comment]
I have been able get steam to launch properly.
