### ISSUE TITLE
Cannot delete web page favorites with gamepad

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steam-for-linux#3953]
Affects: both my Ubuntu client and SteamOS installations
Client type: beta and non-beta
Steam version (non-beta): 1437790054
Steam version (beta): 1438363888
Controllers tested: Microsoft Xbox 360 (wireless), Sony Dualshock 4 (wired)
Controller mappings checked in system menu: yes

I did a search for this issue, and it did not seem to be present here or on the SteamOS tracker, even under closed reports.

**Comment by kisak-valve** [comment]
Hello @mdeguzis, are you still experiencing this issue on an up to date system?

**Comment by mdeguzis** [comment]
No longer an issue @kisak-valve  thanks! The latest Steam client beta on SteamOS restored all the navigational controls it seems. That could have been after a reapply of the BPM controller layout as suggested by the recent beta client notes for chat controls.
