### ISSUE TITLE
Dying Light not running on Ubuntu 12.04, libc6 version problem

### ISSUE THREAD

**Issue by dionysius** [ValveSoftware/steam-for-linux#3955]
How recent is the statement in the current Readme?

    Steam for Linux requires the following:
    [...]
    Ubuntu 12.04 LTS, fully updated
    [...]

Because, when I try to start Dying Light, I get following error:

    [...]
    /media/ElementsL/SteamLibrary/steamapps/common/Dying Light/DyingLightGame: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /media/ElementsL/SteamLibrary/steamapps/common/Dying Light/DyingLightGame)
    /media/ElementsL/SteamLibrary/steamapps/common/Dying Light/DyingLightGame: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /media/ElementsL/SteamLibrary/steamapps/common/Dying Light/DyingLightGame)
    [...]

precise: http://packages.ubuntu.com/precise/libc6 -> version 2.15-0ubuntu10.11
precise-updates: http://packages.ubuntu.com/precise-updates/libc6 -> version 2.15-0ubuntu10.12

As I found out libc6 is a very central component of a linux distro and faulty changes can destroy your system. So either, can someone give me a save source how to update libc6 for 12.04 or can this game be compiled for 2.15? (depends on if the Readme requirements also should state for the games itself)

**Comment by Oxalin** [comment]
This must be an error in the Readme since, as you stated it, libc6 packages is limited to 2.15. It should have been written "Ubuntu 14.04 LTS...".

Could you upgrade your Ubuntu version to 14.04 (or a newer version) which would provide version 2.19?

**Comment by dionysius** [comment]
I could but haven't done that yet. But I'm very sure this would solve it. 

But this request ist more of a "political" one: So there is no sort of compatibility "workflow" which ensures that game developers are pleased to "also" support the "older" but still actual LTS versions (if technical possible)?

**Comment by Tele42** [comment]
Game developers have always been free to decide where they start support for their games, regardless of flavor of OS. I do not see this changing as it's an all-platforms policy change.

There can be other factors like known faulty graphic driver versions for some vendors that are simply not available for newer distro releases.

**Comment by Oxalin** [comment]
@dionysius I understand what you mean. However, as @Tele42 stated, developers are free to decide, as they can do for Windows or OSX.

The true error here is stating in the game that it supports a given distribution (or OS) version which is actually not supported...

**Comment by dionysius** [comment]
Thank you all. Then everything is clear.
