### ISSUE TITLE
Steam UI Unresponsive

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3957]
Sometimes there are delay when i want to click ui elements, it feels laggy and not smooth at all!

Notification has some delay too

Why don't you develop a full native desktop app instead of web app stuff?

EDIT:

OS: Arch Linux
Kernel: 4.1.4-1-ARCH

i3 4150

Intel HD 4400 / AMD HD 7700
8 go DDR3

**Comment by TheBatman** [comment]
SteamOS have one, use debian instead of arch because yes you can custom the distro but i dont recommend you Arch use Debian instead.

**Comment by howdoicomputer** [comment]
Desktop environment: i3-gaps

I noticed it was unresponsive as well. One interesting thing to note is that when I click on a UI element (say, a game item in the library) it fails to properly select. However, when I switch back and forth between workspaces the element is selected.

**Comment by Lurenai** [comment]
Not sure if I'm experiencing the same Issue, but sometimes it feels like Steam isn't registering my clicks, or the clicks are being captured by other window or they are being captured on the wrong coordinates.

Under Ubuntu 14.04 with Gnome shell.

**Comment by howdoicomputer** [comment]
@Lurenai Neat! A separate desktop environment is helpful. I wonder if this has to to do with UI elements not redrawing on events?

**Comment by theforkofjustice** [comment]
Ubuntu Mint 64-bit 15.04

Steam for Linux takes forever to load and the menu lags when it does load.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? If so, was there heavy disk activity at the time?

**Comment by kisak-valve** [comment]
Closing pending feedback.
