### ISSUE TITLE
All web views (store, community, etc) are blank since today

### ISSUE THREAD

**Issue by Macil** [ValveSoftware/steam-for-linux#3958]
Steam has worked okay for me before, but today I found that if I try to go to any non-Library pages, like anything under the Store, Community, or <username> menus, then a loading spinner appears in the top right as expected, spins for a moment, disappears, but no page ever appears. The view remains blank black. Everything under Library works fine. All other windows work fine (View->Settings, View->Friends, chat windows, etc).

Here's the output from running `steam`: http://pastebin.com/weqwUGqa . I notice that this line appears whenever I try to go from Library to a web view:

```
[0809/120114:ERROR:renderer_main.cc(200)] Running without renderer sandbox
```

**Comment by AgentME** [comment]
Since today's Steam update, web views are still blank. Just now the loading spinner never stops on any of them. Here's a new log from `steam`: http://pastebin.com/cWiMADyi . There was something interesting about an assertion failure this time when I went to a web view:

```
Assert( Assertion Failed: BIsValidBrowserHandle( htmlCommand.BodyConst().browser_handle(), iClient_ ) ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/webhelper/html_chrome.cpp:764
 
Installing breakpad exception handler for appid(steamwebhelper)/version(1439401440)
crash_20150812210514_5.dmp[6839]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150812210514_5.dmp
[0812/210514:ERROR:renderer_main.cc(200)] Running without renderer sandbox
crash_20150812210514_5.dmp[6839]: Finished uploading minidump (out-of-process): success = yes
crash_20150812210514_5.dmp[6839]: response: Discarded=1
crash_20150812210514_5.dmp[6839]: file ''/tmp/dumps/crash_20150812210514_5.dmp'', upload yes: ''Discarded=1''
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/webhelper/html_chrome.cpp (764) : Assertion Failed: BIsValidBrowserHandle( htmlCommand.BodyConst().browser_handle(), iClient_ )
```

**Comment by AgentME** [comment]
I ran `steam --reset` and things seem to work correctly for me now.

One interesting thing I notice is that now when I go from the library to a web view, the web view's background is gray (matching the steam window border) while it loads, instead of pure black while I was having the issue.

**Comment by AgentME** [comment]
Just had this start happening again today. Restarting steam didn't fix it. Had to `steam --reset` again.

**Comment by AgentME** [comment]
This is looking like a nearly-weekly thing for me. It's happening again. I'm not really clear what would re-trigger it so far apart like this. I noticed a message I hadn't noticed before showing up occasionally while waiting for web pages to (never) load:

```
[0824/192834:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[0824/192834:ERROR:channel.cc(300)] RawChannel read error (connection broken)
```

Another `steam --reset` fixed it for now.

**Comment by AgentME** [comment]
Ran into the issue again. Had to `steam --reset` to fix it again.

Is this the correct place for support? Is there anything I can do to help gather information about the bug?

**Comment by AgentME** [comment]
Still running into this often. `steam --reset` usually fixes it for a few days.

When the browser stuff is broken, often I'll have the two steamwebhelper processes both at 100% CPU.

When the browser stuff is broken, sometimes I'll see the following error message many times per second from Steam if I launched it from the console. I haven't seen this error at the same time the processes were pegged at 100% though.

```
Received signal 11 SEGV_ACCERR 000057733fb4
#0 0x0000f245b0da <unknown>
#1 0x0000f77b6bf0 ([vdso]+0xbef)
#2 0x0000f5288eca <unknown>
#3 0x0000f51e1b82 <unknown>
#4 0x0000f33069ac <unknown>
#5 0x0000f3333000 <unknown>
#6 0x0000f3332f2f <unknown>
#7 0x0000f51c82d6 <unknown>
#8 0x0000f51fa7c8 <unknown>
#9 0x0000f51fd14d <unknown>
#10 0x0000f51f5d58 <unknown>
#11 0x0000f51f664e <unknown>
#12 0x0000f534434d <unknown>
#13 0x0000f48d03f3 <unknown>
#14 0x0000f48d259c <unknown>
#15 0x0000f245c8c9 <unknown>
#16 0x0000f53dfb97 <unknown>
#17 0x0000f53de1fc <unknown>
#18 0x0000f53e1152 <unknown>
#19 0x0000f245c8c9 <unknown>
#20 0x0000f247f0bd <unknown>
#21 0x0000f247f4cf <unknown>
#22 0x0000f247f769 <unknown>
#23 0x0000f248134a <unknown>
#24 0x0000f247ec64 <unknown>
#25 0x0000f24985cb <unknown>
#26 0x0000f247e64e <unknown>
#27 0x0000f5224e90 <unknown>
#28 0x0000f5dd9fff <unknown>
#29 0x0000f5dda4b6 <unknown>
#30 0x0000f5ddae7d <unknown>
#31 0x0000f5dd9c35 <unknown>
#32 0x0000f2329317 <unknown>
#33 0x0000f22b09fc cef_execute_process
#34 0x000056636539 <unknown>
#35 0x00005662d5de RealMain()
#36 0x00005666b4c8 <unknown>
#37 0x00005666c532 <unknown>
#38 0x0000565b6f96 <unknown>
#39 0x0000f1cc373e __libc_start_main
#40 0x0000565b79dd <unknown>
  gs: 00000063  fs: 00000000  es: 0000002b  ds: 0000002b
 edi: 578110f0 esi: 577b7c40 ebp: fffe6d68 esp: fffe6d2c
 ebx: f761ca98 edx: 57734000 ecx: 577b7c94 eax: ff40574a
 trp: 0000000e err: 00000004  ip: f5288eca  cs: 00000023
 efl: 00210206 usp: fffe6d2c  ss: 0000002b
[end of stack trace]
Received signal 11 SEGV_ACCERR 000057733fb4
```

The issue is similar to https://github.com/ValveSoftware/steam-for-linux/issues/4098, but killing the steamwebhelper process doesn't fix the issue in Steam for me. (There seem to be two steamwebhelper processes usually. Killing the first one causes both of them to die, and then two new ones start up after a few seconds. It doesn't resolve any issues in Steam though.)

**Comment by kisak-valve** [comment]
Hello @Macil, are you still experiencing this issue on an up to date system?

**Comment by Macil** [comment]
No, I think the problem went away after some update after my last post.
