### ISSUE TITLE
Starting AVGN the movie with Steam Streaming makes me enter my user/password

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steam-for-linux#3965]
When I hit play, I am directed to the steam browser to sign in. The controller just makes symbols and letters with no on screen keyboard. I can't enter an underscore with the keyboard to actually type in my name. why is it doing this? This worked fine, even resuming the video several times. Trying a reboot now.

Steam client beta: yes, updated
OS; SteamOS 2.0-beta
Controller: Official xb360 wireless

**Comment by ProfessorKaos64** [comment]
rebooting worked,  but odd bug.

**Comment by mdeguzis** [comment]
Nope, no longer and issue. Thanks for checking in! I admit I should check up on issues as well here to see if I can help out.
