### ISSUE TITLE
Age verification pages sometimes are not displaying the dropdown menu, only the shadow of the menu appears

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3967]
Steps to reproduce:

Go to http://store.steampowered.com/agecheck/app/41000/ within the Steam client.  This particular age check page is for Serious Sam HD.

Click on any of the drop down boxes for the dates.  No menu boxes appear, but you see shadow lines going above the boxes when you click on them.

The weird thing is, after leaving it open for a while and clicking on it again and again, it suddenly eventually corrects itself and starts displaying the menus below the date boxes as it should.

Issue exists in Steam beta as well.

Distro: Linux Mint 17.2 64-bit w/ Cinnamon.  Nvidia driver 355.06, but I've seen it in 352 as well.

**Comment by JamesChristie** [comment]
I can confirm this issue appears on Ubuntu 15.04 as well. Intel Iris Pro graphics with stock Ubuntu packages.

**Comment by ravgill** [comment]
I can confirm as well on ubuntu 14.04 LTS, Radeon 7950 HD.

**Comment by kisak-valve** [comment]
Hello @JamesChristie, @ravgill, are either of you still experiencing this issue on an up to date system?

**Comment by JamesChristie** [comment]
I am happy to report that this was fixed for me long ago. 🙂

**Comment by ravgill** [comment]
Haven't encountered this issue in a long time.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
