### ISSUE TITLE
Steam in app browser does not work [Ubuntu 12.04 - x64]

### ISSUE THREAD

**Issue by sankasan** [ValveSoftware/steam-for-linux#3972]
So none of the community, store, news pages work. I tried steam --reset, reinstalling steam, removing the .steam folder but for now without success.

I have this issue for a couple of months now. I created a ticket on steampowered.com but has gotten no reaction thus far. You can find that ticket over here: https://support.steampowered.com/view.php?ticketref=1639-TGKC-1433

Looking forward to a reply.

**Comment by kisak-valve** [comment]
Hello @sankasan, distro support for Ubuntu 12.04 has reached its end of life. If you're still seeing this issue with an up to date system, please open a new issue report.
