### ISSUE TITLE
Missing strings in library view for demo

### ISSUE THREAD

**Issue by jeifour** [ValveSoftware/steam-for-linux#3973]
I installed demo for a game (http://store.steampowered.com/app/383460), now when I go into library to play it there seems to be missing strings
![bildschirmfoto vom 2015-08-19 22-52-32](https://cloud.githubusercontent.com/assets/3247063/9368813/d8e392fe-46c5-11e5-86f2-e3d84131d804.png)

System: https://gist.github.com/jeifour/1fb9b3f106e922152a7d

**Comment by kisak-valve** [comment]
Hello @jeifour, are you still experiencing this issue on an up to date system?

**Comment by jeifour** [comment]
No I don't.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
