### ISSUE TITLE
Arrow in update history no longer opens page in browser.

### ISSUE THREAD

**Issue by scqless** [ValveSoftware/steam-for-linux#3976]
It instead just refreshes the page in the update dialog.

**Comment by kisak-valve** [comment]
Hello @scqless, are you still experiencing this issue on an up to date system?

**Comment by scqless** [comment]
Just tested by opting into the beta and checking for updates. It now opens the forum thread in the main Steam window, which I assume is the intended behavior.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as this is a sane scenario.
