### ISSUE TITLE
How to remove restriction?

### ISSUE THREAD

**Issue by ernanjohn29** [ValveSoftware/steam-for-linux#3978]
This is written If nothing further occurs to restrict your access, you'll be able to use The Community Market on 9/20/2015, 2:01:48 PM

But when i log out and relogin .. You must have a valid steam purchase that is between 30 days and a year old with no recent chargebacks or payment disputes. To remove this restriction...

**Comment by gdrewb-valve** [comment]
This is a bug tracker for Linux and Mac issues.  You'll want to ask your question of Steam support.

**Comment by ernanjohn29** [comment]
Before
![123](https://cloud.githubusercontent.com/assets/13898898/9421854/edd23c66-48ae-11e5-9685-a8936944a427.png)

After
![after](https://cloud.githubusercontent.com/assets/13898898/9421855/026bc7fa-48af-11e5-875a-ae366f069ca2.png)
