### ISSUE TITLE
Cannot launcher steam after nvidia driver install.

### ISSUE THREAD

**Issue by caoli5288** [ValveSoftware/steam-for-linux#3979]
My nvidia driver version is 352.30, kernel version is 4.1.5.

```
$ steam 
Running Steam on fedora 22 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1440016726)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

That is all. But can launcher with out nvidia driver.

**Comment by gdrewb-valve** [comment]
It's possible installing the drivers has messed up your OpenGL state.  It's also possible you're hitting some of the other known conflicts with the Steam runtime.

**Comment by caoli5288** [comment]
@gdrewb-valve I install xorg-x11-drv-nvidia-libs.i686 manual. It works. THX.

**Comment by faassen** [comment]
I had the same issue, and it was also solved by installing the i686 version (non-64 bit) version of xorg-x11-drv-nvidia-libs. Thanks @caoli5288

**Comment by kisak-valve** [comment]
Closing as this was a system config issue.
