### ISSUE TITLE
Steam complains "Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1"

### ISSUE THREAD

**Issue by dankegel** [ValveSoftware/steam-for-linux#3982]
This looks like another incarnation of issue 2940.

On a freshly installed 64 bit Ubuntu 15.04 system (Aspire E15 E5-573G-59C3, with Nvidia 940m; see http://kegel.com/new-computer-2015b.html ),
installing steam from steampowered.com and running it does give the "Updating Steam" dialog,
and downloads 226MB of updates, but then fails with

Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1

That file is not missing, though:

$ find / -name libGL.so.1 
/usr/lib/nvidia-346/libGL.so.1
/usr/lib/i386-linux-gnu/primus/libGL.so.1
/usr/lib/i386-linux-gnu/mesa/libGL.so.1
/usr/lib/x86_64-linux-gnu/primus/libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
/usr/lib32/nvidia-346/libGL.so.1
$ dpkg-query -S /usr/lib32/nvidia-346/libGL.so.1
nvidia-346: /usr/lib32/nvidia-346/libGL.so.1

Working around the warning as others have suggsted with
$ ln -s /usr/lib32/nvidia-346/libGL.so.1 ~/.steam/bin
gets a different error:
You are missing the following 32-bit libraries, and Steam may not run:
libnvidia-tls.so.346.59
libnvidia-glcore.so.346.59

Adding symlinks to those files yields a crash.

**Comment by fishxz** [comment]
https://wiki.ubuntuusers.de/Steam

says: "sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so.1"

**Comment by dankegel** [comment]
Sure, but I want to use nvidia, not mesa.  

Turns out the problem went away after I finished setting up bumblebee (which messes with things like libGL.so.1).

steam now seems to work.
