### ISSUE TITLE
Amnesia crash on x86_64

### ISSUE THREAD

**Issue by schrotthaufen** [ValveSoftware/steam-for-linux#399]
As soon as the menu is being loaded the crash happens in
<_ZN3hpl16iParticleEmitter11GetMaterialEv+24>: mov rax, QWORD PTR [rdx+rax*8]
Both rdx and rax are NULL
The calling function is hpl::iParticleEmitter::GetMaterial() ()

If 32bit compatibility libraries are installed setting LD_LIBRARY_PATH="~/.local/share/Steam/SteamApps/common/Amnesia The D
ark Descent/libs" and running Amnesia.bin (the 32bit binary) it works as intended.

Here is a workaround https://gist.github.com/c6dccd2b730b08c5ef2f
Unless the libraries were added and/or modified by valve this should also be reported upstream.

**Comment by Shotweb** [comment]
How do you use the workaround? I'm not a linux sysadmin that instinctively knows what to do with those things

**Comment by schrotthaufen** [comment]
> How do you use the workaround? I'm not a linux sysadmin that instinctively knows what to do with those things

I don't have Steam installed on Linux anymore, and it's been over a decade since I've posted this issue -> I have no idea where the file `run_steam.sh` is supposed to be. Presumably inside the game directory.
Assuming you find the file in question, you download [my patch](https://gist.githubusercontent.com/anonymous/c6dccd2b730b08c5ef2f/raw/b834270ac519f98351fb8b56af4f58fd4c866115/run_steam.sh.patch), and apply it with `patch < run_steam.sh.patch`.
[Here](http://stephenjungels.com/jungels.net/articles/diff-patch-ten-minutes.html)'s a concise guide to `patch`, and `diff`.
Please note: Since this fix hasn't been adopted upstream, you might need to apply the patch every time Amnesia gets an update.
