### ISSUE TITLE
graphical artifacts in terminal applications

### ISSUE THREAD

**Issue by incertia** [ValveSoftware/steam-for-linux#3998]
this has mostly happened to me in xfce4-terminal in an xfce4 environment. i don't use urxvt much in xfce4 and i don't run steam when i'm in an xmonad environment so i can't say much about those two.

however, bits of what appears to be steam end up artifacting in my terminal occasionally as i'm working, and i have to redraw the entire screen (namely <C-l> or the equivalent in whatever application i'm in) to clear it up.

system information:

```
Linux incertia-y40 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
mesa 10.6.5-1
xorg-server 1.17.2-4
Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
microcode: 0x17
```

Screenshot: [![artifacts](http://i.imgur.com/uhPd6cb.png)](http://i.imgur.com/uhPd6cb.png)

**Comment by kisak-valve** [comment]
Hello @incertia, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
