### ISSUE TITLE
[Linux] [Beta] Random crashes while listening to music

### ISSUE THREAD

**Issue by jeifour** [ValveSoftware/steam-for-linux#4001]
So because in the Steam client beta now Steam Music finally has some support for audio codecs other than mp3, I decided to try it out. Functionality is great, and it's very convenient to be able to listen to music directly from Steam overlay. But, I experience crashes, even after the beta update from sep 2nd. (But also before.) They make everything close, including the game I was playing (CS:GO).

System: https://gist.github.com/jeifour/141af9340db33a4c17ba
Stdout: https://gist.github.com/jeifour/67b3a4ae3c5723baea06
/tmp/dumps/ folder: https://d.maxfile.ro/lzodhnfcqb.tar.gz

Edit: Not totally sure if this is really related to the music feature of course, but I didn't have these before.

**Comment by jeifour** [comment]
Ok I can reproduce a crash now. Happens as soon as I click on this entry in my Music list
![Image of Steam Music](https://i.imgur.com/d2Zd2dt.png)

**Comment by jeifour** [comment]
Ok pretty sure now this is related to tagging. One of the files I opened in EasyTAG and just saved tag information without actually modifying values. After that it opened fine in Steam and didn't crash, when it crashed with the same file before that.

**Comment by vlv-henryg** [comment]
Thanks for the report and the test file. It turns out that ID3v2 tag fields can be optionally zlib-compressed, and our parser didn't know how to handle this. It'll be fixed in an upcoming beta release.
