### ISSUE TITLE
[Linux] RadeonSI flickering overlay in Dota 2 Reborn

### ISSUE THREAD

**Issue by dietrmat** [ValveSoftware/steam-for-linux#4002]
When the overlay is opened the screen flickers. Running AMD open source drivers (RadeonSI) on Kernel 4.1 and Mesa 10.6.5.

As this is NOT an issue on Dota2 with Source 1 engine but with Source 2 engine. So it seems an issue with Reborn.
If you need more information feel free to comment here.

As commented here, it seems a steam issue: https://github.com/ValveSoftware/Dota-2-Reborn/issues/358

------------------

Prozessor:
Hersteller: GenuineIntel
CPU-Familie: 0x6
CPU-Modell: 0x3c
CPU-Stepping: 0x3
CPU-Typ: 0x0
Geschwindigkeit: 3600 MHz
4 logische Prozessoren
4 technische Prozessoren
HyperThreading: Nicht unterstützt
FCMOV: Unterstützt
SSE2: Unterstützt
SSE3: Unterstützt
SSSE3: Unterstützt
SSE4a: Nicht unterstützt
SSE41: Unterstützt
SSE42: Unterstützt

Netzwerkinformationen:
Netzwerk-Geschwindigkeit:

Betriebssystem:
"Manjaro Linux" (64 Bit)
Kernel-Name: Linux
Kernel-Version: 4.1.6-1-MANJARO
X-Server-Vendor: The X.Org Foundation
X-Server-Release: 11702000
X-Fenstermanager: KWin
Steam-Runtime-Version: steam-runtime-release_2015-06-12

Grafikkarte:
Treiber: X.Org Gallium 0.4 on AMD PITCAIRN

Treiberversion: 3.0 Mesa 10.6.5
OpenGL-Version: 3.0
Desktop-Farbtiefe: 24 Bit per Pixel
Monitor-Aktualisierungsrate: 60 Hz
Anbieterkennung: 0x1002
Gerätekennung: 0x6810
Anzahl der Monitore: 1
Anzahl der logischen Grafikkarten: 1
Prim. Anzeigeauflösung: 1920 x 1080
Desktopauflösung: 1920 x 1080
Prim. Anzeigegröße: 47,7 cm x 26,8 cm (54,7 cm diag.)

Kein prim. VRAM entdeckt

Soundkarte:
Audiogerät: Realtek ALC662 rev1

Speicher:
RAM: 7927 MB

Weitere Daten:
UI-Sprache: Deutsch (Deutsch)
SPRACHE: de_DE.UTF-8
Mikrofon: Not set
Verfügbarer Festplattenspeicher insgesamt: 930713 MB
Größter freier Festplattenspeicherblock: 458384 MB

Installierte Software:

Neueste Fehlerberichte:

**Comment by danginsburg** [comment]
I have checked in a fix for this issue, see also: https://github.com/ValveSoftware/Dota-2-Reborn/issues/358 .  The fix will be in a future Steam update.  Closing.

**Comment by dietrmat** [comment]
@danginsburg Thx for your fast fix.

**Comment by dietrmat** [comment]
Today's steam update finally fixed the issue. Thank you.
