### ISSUE TITLE
Bringing up overlay in-game leaves key pressed

### ISSUE THREAD

**Issue by raidermax** [ValveSoftware/steam-for-linux#4004]
I am not sure how to title this bug. I have my overlay shortcut set to "Left Ctrl + Tab" and whenever I press it the overlay comes up but it acts as if the ctrl button is stilled pressed. When I starting typing in a steam chat my words begin to disappear and other things that would occur if I were actually pressing Ctrl actually occur. If I press ctrl once more after loading up the overlay the problem goes away. So it seems like for some odd reason it is not letting go of the ctrl button.

**Comment by raidermax** [comment]
Dear Plagman, Happy New Year!

I am not trying to rush or be rude but has there been any progress on this "bug"? Lately I have not been encountering it too often as I used to.

**Comment by kisak-valve** [comment]
Hello @raidermax, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
