### ISSUE TITLE
Cannot launch steam after system update

### ISSUE THREAD

**Issue by sadger** [ValveSoftware/steam-for-linux#4005]
Updated my system yesterday but now steam hangs with the message

```
/home/william/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/william/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/william/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1440016726)
```

Any ideas what could cause this and how to diagnose the problem?

**Comment by sadger** [comment]
On Archlinux 64 bit using Nvidia graphics version 352.30

**Comment by rr-** [comment]
Same issue -_-

    rr-@tornado:~$ steam
    /home/rr-/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
    /home/rr-/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
    Running Steam on arch  64-bit
    /home/rr-/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
    STEAM_RUNTIME is enabled automatically
    Installing breakpad exception handler for appid(steam)/version(1440016726)

    rr-@tornado:~$ ldd ~/.steam/bin/steam
	linux-gate.so.1 (0xf773f000)
	libX11.so.6 => /usr/lib32/libX11.so.6 (0xf75be000)
	librt.so.1 => /usr/lib32/librt.so.1 (0xf75b5000)
	libm.so.6 => /usr/lib32/libm.so.6 (0xf7568000)
	libdl.so.2 => /usr/lib32/libdl.so.2 (0xf7563000)
	libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf73ec000)
	libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf73ce000)
	libc.so.6 => /usr/lib32/libc.so.6 (0xf7214000)
	libxcb.so.1 => /usr/lib32/libxcb.so.1 (0xf71ee000)
	/lib/ld-linux.so.2 (0xf7740000)
	libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf71d4000)
	libXau.so.6 => /usr/lib32/libXau.so.6 (0xf71cf000)
	libXdmcp.so.6 => /usr/lib32/libXdmcp.so.6 (0xf71c8000)

Drivers version: 352.41-1

**Comment by sadger** [comment]
If my ldd trace will help also
```
	linux-gate.so.1 (0xf776c000)
	libX11.so.6 => /usr/lib32/libX11.so.6 (0xf75c6000)
	librt.so.1 => /usr/lib32/librt.so.1 (0xf75bd000)
	libm.so.6 => /usr/lib32/libm.so.6 (0xf7570000)
	libdl.so.2 => /usr/lib32/libdl.so.2 (0xf756b000)
	libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xf73f4000)
	libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf73d6000)
	libc.so.6 => /usr/lib32/libc.so.6 (0xf721c000)
	libxcb.so.1 => /usr/lib32/libxcb.so.1 (0xf71f6000)
	/lib/ld-linux.so.2 (0xf776d000)
	libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xf71dc000)
	libXau.so.6 => /usr/lib32/libXau.so.6 (0xf71d7000)
	libXdmcp.so.6 => /usr/lib32/libXdmcp.so.6 (0xf71d0000)
```

Updating my gfx driver to the latest doesn't seem to have helped either

**Comment by sadger** [comment]
glxgears demo is working on machine and I have an X display so don't think it's my drivers unless I'm missing something for 32-bit compatability. Said that, it was working fine before my system update.

**Comment by sadger** [comment]
On some investigating it seems to be a Arch Linux library issue, incompatible library versions between nvidia and 32bit-libgl. I worked out a potentially fix until the main drivers are updated in the repositories. @rr- see my last post on here https://bbs.archlinux.org/viewtopic.php?id=202084 hope that helps.

**Comment by amarildojr** [comment]
Could you try this command

>find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete

Close Steam, enter the command above, then open Steam again. It will download the newer Runtime and should work.

**Comment by rr-** [comment]
Neither installing newer nvidia drivers or removing the dlls mentioned above did help - in fact, there were no such files in `~/.steam/root`...

    rr-@tornado:~/.steam$ pacman -Ss nvidia|grep installed
    testing/nvidia 355.11-1 [installed]
    extra/libvdpau 1.1-1 [installed]
    extra/nvidia 352.41-1 [installed: 355.11-1]
    extra/xf86-video-nouveau 1.0.11-3 (xorg-drivers xorg) [installed]
    multilib/lib32-nvidia-libgl 352.41-1 [installed]
    multilib/lib32-nvidia-utils 352.41-1 [installed]

(I wonder why I still have 32-bit versions set to 352.)

**Comment by sadger** [comment]
@rr Your nvidia and lib32-nvidia are at different versions. Did you do a full system upgrade? Mine are all at 355.11-1 now. 

Mine:
lib32-nvidia-libgl 355.11-1
lib32-nvidia-utils 355.11-1
nvidia-beta 355.11-1
nvidia-libgl-beta 355.11-1
nvidia-utils-beta 355.11-1
opencl-nvidia-beta 355.11-1

**Comment by rr-** [comment]
I did; perhaps our `pacman` sources are different? I'll be able to investigate things more once I get home.

**Comment by sadger** [comment]
Ok sure, just paste what you can and i'll compare with my own hopefully we can fix yours.

**Comment by rr-** [comment]
Installing following packages from AUR helped:

    nvidia-beta
    lib32-nvidia-libgl-beta
    lib32-nvidia-utils-beta

After this, `pacman -Qm|grep nvidia`:

    lib32-nvidia-libgl-beta 355.11-1
    lib32-nvidia-utils-beta 355.11-1
    lib32-opencl-nvidia-beta 355.11-1
    nvidia-beta 355.11-1
    nvidia-utils-beta 355.11-1
    opencl-nvidia-beta 355.11-1

...and Steam works again. Thank you for help @sadger.

**Comment by sadger** [comment]
No problem, happy to be of help.  The nvidia packages from extra/ are known to be outdated, what I would recommend is waiting til they are and switching back to them, unless of course you want to keep the beta drivers but you may encounter bugs. 

Happy gaming. :computer: :video_game: :space_invader:
