### ISSUE TITLE
TF2 Debian Jessie T420 / T430 Thinkpad (no nvidia | only intel HD 3000 / 4000) Crash On Startup | Works Fine on WINE but not Native! (Now includes strace.log)

### ISSUE THREAD

**Issue by War3Evo** [ValveSoftware/steam-for-linux#4008]
CrashID=bp-7e92c57b-80a8-40ae-9d63-a6bbd2150907

crash_20150907083710_1.dmp[5912]: Finished uploading minidump (out-of-process): success = yes
crash_20150907083710_1.dmp[5912]: response: CrashID=bp-7e92c57b-80a8-40ae-9d63-a6bbd2150907
crash_20150907083710_1.dmp[5912]: file ''/tmp/dumps/crash_20150907083710_1.dmp'', upload yes: ''CrashID=bp-7e92c57b-80a8-40ae-9d63-a6bbd2150907''

I do get around 60fps on WINE with no problems other  than this laptop runs hotter and would prefer it run natively on this T420 Thinkpad laptop.  This T420 Thinkpad Laptop does not come with the optional extra graphics on board (only the intel HD 3000).  I've done tons of research, and googled everything.  I can not seem to find a solution that works.

lspci00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:16.3 Serial controller: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller (rev 04)
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4)
00:1c.1 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b4)
00:1c.3 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 4 (rev b4)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b4)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation QM67 Express Chipset Family LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port SATA AHCI Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 04)
03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak](rev 34)
0d:00.0 System peripheral: Ricoh Co Ltd PCIe SDXC/MMC Host Controller (rev 08)

war3evo@T420Laptop:~$ /usr/bin/steam
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0907/083650:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150819112727)
Installing breakpad exception handler for appid(steamwebhelper)/version(1439983647)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150819112727)
Installing breakpad exception handler for appid(steamwebhelper)/version(1440016726)
Installing breakpad exception handler for appid(steamwebhelper)/version(1440016726)
[0907/083650:ERROR:nss_util.cc(981)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
Dongle firmware /home/war3evo/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1435869091.
Installing breakpad exception handler for appid(steam)/version(1440016726)
Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 8: 64x256, total string texture memory is 196.61 KB
Generating new string page texture 9: 48x256, total string texture memory is 245.76 KB
Generating new string page texture 10: 256x256, total string texture memory is 507.90 KB
Generating new string page texture 11: 8x256, total string texture memory is 516.10 KB
Generating new string page texture 12: 16x256, total string texture memory is 532.48 KB
Generating new string page texture 13: 24x256, total string texture memory is 557.06 KB
Generating new string page texture 14: 32x256, total string texture memory is 589.82 KB
Installing breakpad exception handler for appid(steam)/version(1440016726)
Installing breakpad exception handler for appid(steam)/version(1440016726)
local (potentially out of sync) copy of roaming config loaded - 1433 bytes.
Installing breakpad exception handler for appid(steam)/version(1440016726)
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0xa00981
Serial number of failed request:  781
xerror_handler: X failed, continuing
roaming config store loaded successfully - 1433 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1440016726)
Adding licenses for the following package(s): 0, 218, 518, 2481, 11793, 13602, 14938, 15638, 16020, 16223, 16360, 17250, 18629, 21433, 27530, 28047, 28838, 73198, 73643, 75739, 76386, 76727, 77033, 77034, 77035, 77682, 77694, 77700
Dongle firmware /home/war3evo/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1435869091.
Dongle firmware /home/war3evo/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1435869091.
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1440016726)
ExecCommandLine: ""/home/war3evo/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1440016726)
System startup time: 11.91 seconds
[0907/083702:ERROR:renderer_main.cc(200)] Running without renderer sandbox
Generating new string page texture 315: 128x256, total string texture memory is 720.90 KB
Generating new string page texture 316: 512x256, total string texture memory is 1.25 MB
Generating new string page texture 317: 48x256, total string texture memory is 1.29 MB
Generating new string page texture 318: 128x256, total string texture memory is 131.07 KB
Installing breakpad exception handler for appid(steam)/version(1440016726)

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Generating new string page texture 325: 256x256, total string texture memory is 1.56 MB
Generating new string page texture 326: 128x256, total string texture memory is 1.69 MB
Generating new string page texture 327: 64x256, total string texture memory is 1.75 MB
Installing breakpad exception handler for appid(steam)/version(1440016726)
Generating new string page texture 374: 384x256, total string texture memory is 2.15 MB
Generating new string page texture 375: 1024x256, total string texture memory is 3.19 MB
Generating new string page texture 376: 2048x256, total string texture memory is 5.29 MB
Generating new string page texture 422: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 423: 256x256, total string texture memory is 5.55 MB
Running Steam on debian 8 64-bit
STEAM_RUNTIME has been set by the user to: /home/war3evo/.local/share/Steam/ubuntu12_32/steam-runtime
ExecCommandLine: "/home/war3evo/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 2139: 128x256, total string texture memory is 5.69 MB
Game update: AppID 440 "Team Fortress 2", ProcID 3942, IP 0.0.0.0:0
ERROR: ld.so: object '/home/war3evo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/war3evo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 3945 != 3944, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/war3evo/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/war3evo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:3495): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
SDL video target is 'x11'
SDL video target is 'x11'
Using Breakpad minidump system. Version: 2941077 AppID: 440
Setting breakpad minidump AppID = 440
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198030613061 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198030613061
Did not detect any valid joysticks.
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2 3.0 Mesa 10.3.2 (3.0.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
Dongle firmware /home/war3evo/.local/share/Steam/linux32/../controller_base/d0ggle.bin loaded, version 1435869091.
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_MAX_SAMPLES_EXT: 4
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3200 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3200 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 640, BackBufHeight: 400, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED

 ##### swap interval = 0     swap limit = 1 #####
Installing breakpad exception handler for appid(steam)/version(1440016726)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860160 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 3833862 of shader (dyn=24)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 860240 of shader (dyn=160)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 1998080 of shader (dyn=160)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 145200 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 11796864 of shader (dyn=24)
Shader 'shaders\fxc\skin_ps20b.vcs' - Couldn't load combo 71680 of shader (dyn=160)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 884742 of shader (dyn=24)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1867782 of shader (dyn=24)
Shader 'shaders\fxc\vertexlit_and_unlit_generic_ps20b.vcs' - Couldn't load combo 1597440 of shader (dyn=24)
Loaded program cache file "glbaseshaders.cfg", total keyvalues: 266, total successfully linked: 227
CGLMShaderPair::SetProgramPair: Centroid masks differ at link time of vertex shader lightmappedgeneric_vs20 and pixel shader decalbasetimeslightmapalphablendselfillum2_ps20b!
Loaded program cache file "glshaders.cfg", total keyvalues: 3118, total successfully linked: 3118
Precache: Took 146577 ms, Vertex 3707, Pixel 10343
server.so loaded for "Team Fortress"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
ERROR: ld.so: object '/home/war3evo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150907083710_1.dmp[5912]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150907083710_1.dmp
/home/war3evo/.local/share/Steam/SteamApps/common/Team Fortress 2/hl2.sh: line 67:  3947 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 440 "Team Fortress 2", ProcID 3947 
crash_20150907083710_1.dmp[5912]: Finished uploading minidump (out-of-process): success = yes
crash_20150907083710_1.dmp[5912]: response: CrashID=bp-7e92c57b-80a8-40ae-9d63-a6bbd2150907
crash_20150907083710_1.dmp[5912]: file ''/tmp/dumps/crash_20150907083710_1.dmp'', upload yes: ''CrashID=bp-7e92c57b-80a8-40ae-9d63-a6bbd2150907''
pid 5912 != 5911, skipping destruction (fork without exec?)

sudo lshw -short
# H/W path         Device      Class          Description

```
                         system         Computer
```

/0                           bus            Motherboard
/0/0                         memory         7886MiB System memory
/0/1                         processor      Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
/0/100                       bridge         2nd Generation Core Processor Family DRAM Controller
/0/100/2                     display        2nd Generation Core Processor Family Integrated Graphics Controller
/0/100/16                    communication  6 Series/C200 Series Chipset Family MEI Controller #1
/0/100/16.3                  communication  6 Series/C200 Series Chipset Family KT Controller
/0/100/19        eth1        network        82579LM Gigabit Network Connection
/0/100/1a                    bus            6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2
/0/100/1a/1      usb1        bus            EHCI Host Controller
/0/100/1a/1/1                bus            Integrated Rate Matching Hub
/0/100/1a/1/1/3              generic        Biometric Coprocessor
/0/100/1a/1/1/4              communication  Broadcom Bluetooth Device
/0/100/1b                    multimedia     6 Series/C200 Series Chipset Family High Definition Audio Controller
/0/100/1c                    bridge         6 Series/C200 Series Chipset Family PCI Express Root Port 1
/0/100/1c.1                  bridge         6 Series/C200 Series Chipset Family PCI Express Root Port 2
/0/100/1c.1/0    wlan0       network        Centrino Advanced-N 6205 [Taylor Peak]
/0/100/1c.3                  bridge         6 Series/C200 Series Chipset Family PCI Express Root Port 4
/0/100/1c.4                  bridge         6 Series/C200 Series Chipset Family PCI Express Root Port 5
/0/100/1c.4/0                generic        MMC/SD Host Controller
/0/100/1d                    bus            6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1
/0/100/1d/1      usb2        bus            EHCI Host Controller
/0/100/1d/1/1                bus            Integrated Rate Matching Hub
/0/100/1f                    bridge         QM67 Express Chipset Family LPC Controller
/0/100/1f.2                  storage        6 Series/C200 Series Chipset Family 6 port SATA AHCI Controller
/0/100/1f.3                  bus            6 Series/C200 Series Chipset Family SMBus Controller
/0/2             scsi0       storage  
/0/2/0.0.0       /dev/sda    disk           500GB Samsung SSD 850
/0/2/0.0.0/1     /dev/sda1   volume         243MiB Linux filesystem partition
/0/2/0.0.0/2     /dev/sda2   volume         465GiB Extended partition
/0/2/0.0.0/2/5   /dev/sda5   volume         297GiB Linux filesystem partition
/0/2/0.0.0/2/6   /dev/sda6   volume         167GiB Linux filesystem partition
/0/3             scsi1       storage  
/0/3/0.0.0       /dev/cdrom  disk           DVDRAM GT50N
/1               tap0        network        Ethernet interface

cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)

sudo dmidecode -t processor
# dmidecode 2.12

SMBIOS 2.6 present.

Handle 0x0001, DMI type 4, 42 bytes
Processor Information
    Socket Designation: CPU
    Type: Central Processor
    Family: Core i5
    Manufacturer: Intel(R) Corporation
    ID: A7 06 02 00 FF FB EB BF
    Signature: Type 0, Family 6, Model 42, Stepping 7
    Flags:
        FPU (Floating-point unit on-chip)
        VME (Virtual mode extension)
        DE (Debugging extension)
        PSE (Page size extension)
        TSC (Time stamp counter)
        MSR (Model specific registers)
        PAE (Physical address extension)
        MCE (Machine check exception)
        CX8 (CMPXCHG8 instruction supported)
        APIC (On-chip APIC hardware supported)
        SEP (Fast system call)
        MTRR (Memory type range registers)
        PGE (Page global enable)
        MCA (Machine check architecture)
        CMOV (Conditional move instruction supported)
        PAT (Page attribute table)
        PSE-36 (36-bit page size extension)
        CLFSH (CLFLUSH instruction supported)
        DS (Debug store)
        ACPI (ACPI supported)
        MMX (MMX technology supported)
        FXSR (FXSAVE and FXSTOR instructions supported)
        SSE (Streaming SIMD extensions)
        SSE2 (Streaming SIMD extensions 2)
        SS (Self-snoop)
        HTT (Multi-threading)
        TM (Thermal monitor supported)
        PBE (Pending break enabled)
    Version: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Voltage: 1.2 V
    External Clock: 100 MHz
    Max Speed: 2500 MHz
    Current Speed: 2500 MHz
    Status: Populated, Enabled
    Upgrade: ZIF Socket
    L1 Cache Handle: 0x0002
    L2 Cache Handle: 0x0003
    L3 Cache Handle: 0x0004
    Serial Number: Not Supported by CPU
    Asset Tag: None
    Part Number: None
    Core Count: 2
    Core Enabled: 2
    Thread Count: 4
    Characteristics:
        64-bit capable

Beats the hell out of me why it runs fine on Wine, but will NOT run Natively on Linux.

**Comment by sizeofbool** [comment]
Post additional info:
```
$ glxinfo | egrep "display|rendering:|server|client|OpenGL"
```
```
$ Xorg -version
```
Also what Desktop Environment you use?

**Comment by War3Evo** [comment]
Do note that I've switched to the T430, same results.  The difference from the T420 and T430 is the cpu processor speed from 2.5ghz to 2.6ghz, and from intel hd 3000 to intel hd 4000.  Nothing much else difference that really matters.  I did notice a major improvement in native windows FPS for the T430 compared to the T420, but native linux does not play it.  Native linux will however play on my i7-920 desktop w/ nvidia graphics card on this same linux setup (I cloned from my desktop to my laptop...removed the nvidia drivers and setup the intel drivers).  Debian Jessie started with Gnome, and then I added Fluxbox windows manager, and did not disable Gnome as I can still access its software when needed.

INFO You Requested:

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.3.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.0
OpenGL ES profile extensions:

X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux HPDeskJetFax300 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.16.0-4-amd64 root=/dev/mapper/HPDeskJetFax300-root ro quiet splash i965.modeset=1
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.

**Comment by War3Evo** [comment]
I really want to figure out.. if I should just give up on linux and move to windows .. or keep my linux setup and wait for a bug fix?

**Comment by sizeofbool** [comment]
Well, you can try run it with strace to at least see where exactly it segfaults.
I use Xfce and never had any grave problems with games.
To run TF2 with strace edit launch options in steam like this:
```
GAME_DEBUGGER="strace -f -e trace=open -o strace.log" %command%
```
Look for "strace.log" file in game's folder.
strace can generate huge file if it set to grab everything.

**Comment by War3Evo** [comment]
Pretty huge, can't upload it via text comment, so here is the file download:

http://war3evo.info/stracelog/stracelog.zip

Let me know when you get this, so I can delete it.

**Comment by sizeofbool** [comment]
Strange, it seems to segfault during loading process of game resources. Test it several times to see if it segfaults always in the same place.
Verify integrity of game cache, just in case, or delete and re-download TF2. Also show me:
```
$ ulimit -a
```
```
$ cat /proc/meminfo
```

**Comment by kisak-valve** [comment]
Hello @War3Evo, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing due to lack of feedback. If you're still experiencing this issue, please use [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/) issue tracker for TF2 issues.
