### ISSUE TITLE
mic sound bad in steam

### ISSUE THREAD

**Issue by 159shadows357** [ValveSoftware/steam-for-linux#4011]
Issues
Microphone sound so bad whit steam and in game too, I try to speak with my friend in facebook and skype sound is cool, my all device driver is lasted version.

My laptop spec
Lenovo(Z40)
Operating System: Windows 10
Processor: AMD A10-7300 Radeon R6, 10 Compute Cores 4C + 6G
Memory: 2 GB RAM
Graphics: AMD Radeon R6 M255DX AMD Radeon(TM) R6 Graphic
Sound Card: AMD High Definition Audio Device, Conexant SmartAudio HD

**Comment by kisak-valve** [comment]
Closing as audio issues with Steam for Windows is out-of-scope for this issue tracker. If you're still experiencing this issue, please use Steam Support.
