### ISSUE TITLE
Steam on ubuntu 15.04(64-bit)

### ISSUE THREAD

**Issue by Src02** [ValveSoftware/steam-for-linux#4017]
Steam on ubuntu 15.04(64-bit) causes High CPU usage over time. 
Everything was normal, but, Since some ubuntu updates or maybe steam updates, this has been happening to me. Maybe it's something related to the compatibility and steam need to be updated.

When i start a game mainly, steam uses 100% of the ram memory and the system starts to use swap memory, and then, everything starts lagging and i can't play my games.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 11.1.0-devel (git-67d2d3b 2015-09-14 vivid-oibaf-ppa)
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x166
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 12,17" x 6,81"  (13,94" diag)
                                        30,9cm x 17,3cm  (35,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  3846 Mb

Miscellaneous:
    UI Language:  English
    LANG:  pt_BR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  464896 Mb
    Largest Free Hard Disk Block:  325136 Mb

**Comment by theforkofjustice** [comment]
Same version of Linux here but it takes a long time to load and there is a lot of menu lag.

**Comment by Src02** [comment]
This problem is just on Ubuntu 15.04+, i think. I changed my primary OS to Debian(8.2) and everything is fine now. Is that some compatibility problem on ubuntu 15.04+, i guess . . . ?

**Comment by theforkofjustice** [comment]
I found recently that deleting the appcache folder helps this a lot.

**Comment by Src02** [comment]
Is this a fix for the issue or just an workaround?
How that works?

**Comment by theforkofjustice** [comment]
Damned if I know but it helped anyway.

**Comment by kaniawave** [comment]
@theforkofjustice May I ask, how do you clear the appcache folder? Where can I find it? 

I have a problem with steam, where a game goes smoothly and fine for couple of minutes and cpu usage is around 40 or less % and then it goes sky rocket to 100 % all cores and everything lags like hell for about 15 seconds. The problem occurs every 4 minutes or so.

**Comment by theforkofjustice** [comment]
It should be in your .steam folder in your home directory.  Just find it and delete it.

**Comment by kaniawave** [comment]
@theforkofjustice. But do you think the cache could be a problem with a completely new system and fresh installation of steam?

Maybe I should start a new topic. The problem I have is that on 14.04 LTS the game Insurgency was running slow, with kind of low fps, but stable. Now after fresh system reinstall to 15.10 I have much better performance but these lags occur which makes gaming a bit impossible. Anyone encountered this kind of problem?

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing the memory leak mentioned in the opening post on an up to date system?

**Comment by kisak-valve** [comment]
Closing from lack of feedback and Ubuntu 15.04 /15.10 has been EOL'd.
