### ISSUE TITLE
steamcmd update loop

### ISSUE THREAD

**Issue by vidje** [ValveSoftware/steam-for-linux#4018]
Basically, I can't do a thing with steamcmd. Been stuck in this update loop for weeks now, no idea how to resolve it. Hope this helps: http://pastebin.com/WfgeA0Yp

Also, there's no stderr.txt that steamcmd suggests was made.

**Comment by esdf** [comment]
managed to find a fix,

rm -r ./linux32/
mv  ./package/tmp/* ~/steamcmd/
./steamcmd.sh +login anonymous +quit

**Comment by xyzdevdox** [comment]
This bug still not fixed ?

**Comment by kisak-valve** [comment]
Hello @vidje, @qwexvf, have either of you seen this issue in recent history?

**Comment by kisak-valve** [comment]
Closing pending feedback.
