### ISSUE TITLE
TTY doesn't load up

### ISSUE THREAD

**Issue by annoyedannex** [ValveSoftware/steam-for-linux#4019]
so there is an issue with tty (ctrl + alt + f1)  I've opened tty2 tried to login but it wont take the login info i'm really annoyed because i need to installed updated nvidia drivers which i can't because i'm locked out of tty2 and TTY refuses to load up and freezes my screen.

**Comment by annoyedannex** [comment]
lets add that now im completely locked out of my system i can't even sudo now, never has this happened before. what the hell is going on it's beginning to really anger me.

**Comment by Tele42** [comment]
This question should be directed at your distro's community, it is unrelated to the steam-for-linux client.

**Comment by gdrewb-valve** [comment]
Closing non-Steam issue.
