### ISSUE TITLE
Can't launch steam with Nvidia drivers 346.82 Ubuntu 14.01lts

### ISSUE THREAD

**Issue by davethegamer** [ValveSoftware/steam-for-linux#4023]
No error code appeared, no message popped up, but every time I try and launch steam it never opens. It opens when I use the Open source drivers but with those I can't use 1080p. Is there some kind of work around for this? I'm using Ubuntu 14.01 and using the Nvidia binary drivers version 346.82. Thanks for the help.

**Comment by kisak-valve** [comment]
Hello @davethegamer, are you still experiencing this issue on an up to date system? If the nvidia kernel module version does not match the (32 bit) userspace library version, this scenario can occur.

**Comment by kisak-valve** [comment]
Closing pending feedback.
