### ISSUE TITLE
[Bug] When watching a video, choosing quality arrow is broken

### ISSUE THREAD

**Issue by JoshuaMurphynz** [ValveSoftware/steam-for-linux#4031]
When watching a video using BP mode the arrows for choosing quality & speed are broken.

I have attached a picture: https://lh3.googleusercontent.com/oaPdwbPux7S7cY3dhOjevClP7Dpekt3y5tUw3rPf-9LSFPhLx9M=w1247-h706-no (LINK IS BROKEN)

Steps to reproduce:
1. Open BP mode
2. Find a video to watch
3. Change the quality (because laptop lags a tiny bit at 1080P)

Basically the arrows are in the wrong place. Please see the picture.

The screen resolution of this PC is 1368x768 if that matters.

Please credit me if this gets mentioned in release notes :P 

If you need any help fixing this please reply.

**Comment by not83** [comment]
I will see if this issue still exists

**Comment by kisak-valve** [comment]
Hello @JoshuaMurphynz, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
