### ISSUE TITLE
[Bug] After watching a TV/Movie in BP mode, the user manually has to exit.

### ISSUE THREAD

**Issue by JoshuaMurphynz** [ValveSoftware/steam-for-linux#4032]
Steps to reproduce:
1. Enter BP mode
2. find a movie to watch (for example payday web series)
3. watch till the end

Then the movie stops playing one second before the end of the movie, and has to be manually stopped by pressing the stop button.

**Comment by not83** [comment]
I will check if this issue is still around.

**Comment by kisak-valve** [comment]
Hello @JoshuaMurphynz, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
