### ISSUE TITLE
[Bug] Can't find any videos using BP mode store

### ISSUE THREAD

**Issue by JoshuaMurphynz** [ValveSoftware/steam-for-linux#4033]
Steps to replicate:
1. Enter BP mode
2. Try searching for "Payday, the web series"
3. find no results

This happens with both the "enable all content no matter the OS" on and off. 

I have gotten around this by using the firefox web browser, but this will not be ideal for SteamOS.

**Comment by kisak-valve** [comment]
Hello @JoshuaMurphynz, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
