### ISSUE TITLE
[Suggestion] Add command line option to launch a game/app_id without opening the steam client window and exit the steam client afterwards

### ISSUE THREAD

**Issue by Holzhaus** [ValveSoftware/steam-for-linux#4035]
I would be nice if Steam provided a command line option that directly launches a game and exits the steam client afterwards.

Right now, we can launch a game via:

```
steam steam://rungameid/APPID
steam -applaunch APPID
```

But the steam client will stay open after the game exited. Could you add an command line option that does that without showing the Steam client window and exits the steam client after closing the game?

**Comment by Tele42** [comment]
Duplicate of #1721.

**Comment by Holzhaus** [comment]
Okay, closing this.
