### ISSUE TITLE
TF2 Terrible performance only before changing video options in-game

### ISSUE THREAD

**Issue by silverhammermba** [ValveSoftware/steam-for-linux#4036]
When I launch TF2 and join a server I always get awful unplayable performance: about 10-20 FPS. However if I then go into the advanced video options and change something (like increase AA from None to 2x) it stutters for a bit while it reloads, but then I get great performance: 60 FPS.

The performance stays great through map changes and server changes, so I only have to repeat the trick when I restart the game. The trick doesn't work if I change the video options while outside a server. Note that this has nothing to do with the performance of my hardware since I can actually increase my FPS by increasing the video options (like raising AA from None to 2x) (also TF2 runs fine in Windows on the same PC).

It seems like TF2's renderer is loading "wrong" the first time, and changing the video options in-game forces it to reload "correctly". But I have no idea how to fix it. It's not the end of the world since I figured out the workaround, but it can get pretty frustrating - especially when TF2 crashes and I have to repeat the ritual. I tried doing a fresh install of TF2 to no effect.

I'm running on fully up-to-date Arch Linux. Here are my specs:

> Vendor: GenuineIntel
> CPU Family: 0x6
> CPU Model: 0x2a
> CPU Stepping: 0x7
> CPU Type: 0x0
> Speed: 3700 Mhz
> 4 logical processors
> 4 physical processors
> HyperThreading: Unsupported
> FCMOV: Supported
> SSE2: Supported
> SSE3: Supported
> SSSE3: Supported
> SSE4a: Unsupported
> SSE41: Supported
> SSE42: Supported
> 
> Network Information:
> Network Speed: 
> 
> Operating System Version:
> "Arch Linux" (64 bit)
> Kernel Name: Linux
> Kernel Version: 4.1.6-1-ARCH
> X Server Vendor: The X.Org Foundation
> X Server Release: 11702000
> X Window Manager: awesome
> Steam Runtime Version: steam-runtime-release_2015-06-12
> 
> Video Card:
> Driver: NVIDIA Corporation GeForce GTX 570/PCIe/SSE2
> 
> Driver Version: 4.5.0 NVIDIA 352.41
> OpenGL Version: 4.5
> Desktop Color Depth: 24 bits per pixel
> Monitor Refresh Rate: 59 Hz
> VendorID: 0x10de
> DeviceID: 0x1086
> Number of Monitors: 2
> Number of Logical Video Cards: 1
> Primary Display Resolution: 2560 x 1440
> Desktop Resolution: 4480 x 1440
> Primary Display Size: 23.50" x 13.23" (26.97" diag)
> 59.7cm x 33.6cm (68.5cm diag)
> Primary Bus: PCI Express 16x
> Primary VRAM: 1280 MB
> Supported MSAA Modes: 2x 4x 8x 16x 
> 
> Sound card:
> Audio device: Realtek ALC889
> 
> Memory:
> RAM: 7956 Mb
> 
> Miscellaneous:
> UI Language: English
> LANG: en_US.UTF-8
> Microphone: Not set
> Total Hard Disk Space Available: 953866 Mb
> Largest Free Hard Disk Block: 286159 Mb
> 
> Installed software:
> 
> Recent Failure Reports:

I also posted this on the [Steam forums](http://steamcommunity.com/app/221410/discussions/2/523898291487840397/).

**Comment by kisak-valve** [comment]
Hello @silverhammermba, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If you can reproduce this issue, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games/) issue tracker.
