### ISSUE TITLE
Activation of a product on Steam causes client crash

### ISSUE THREAD

**Issue by Plaque-fcc** [ValveSoftware/steam-for-linux#4037]
Current Steam Beta instance when I click `Games` → `Activate a product on Steam` simply crashes before anything other happens.
No updates available as it says.

I got Ubuntu 15.04 i686 on AMD A4-5000 and ATI Radeon HD 8330M + ATI Radeon HD 8570M.

CrashID=bp-8084c5f2-b2be-459e-8afa-138752150924
CrashID=bp-aad8b397-c660-4d47-abf1-a2c282150924
CrashID=bp-9c0e7fde-a48f-4ad6-b25b-c67982150924

**Comment by kisak-valve** [comment]
Hello @Plaque-fcc, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
