### ISSUE TITLE
featured slider showing windows games saying recommended for me

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4038]
Weirdly, the featured slider on the homepage has now begun constantly showing me Windows-only games, and saying "recommended for you".

It used to only show games that are on SteamOS/Linux, I consider this a really annoying bug. Happens in both the client and web browser.

**Comment by fleskesvor** [comment]
I'm experiencing the same issue. I think it started happening sometime this week. And it's not just the featured slider; it's everything on the front page.

**Comment by LiamDawe** [comment]
Thanks for checking in with me, can't say I've had this issue in a long time.
