### ISSUE TITLE
Absence of controller configurations in BPM

### ISSUE THREAD

**Issue by mhalano** [ValveSoftware/steam-for-linux#4044]
I'm using a Xbox360 controller with xboxdrv (and not xpad) configured without the xboxdrv's option "mimic_xpad". The problem is when i go to the controller configurations in Big Picture Mode The controller works, but is recognized as a "Xinput device" and don't have option to remap controller. Some folks and me think should have option to remap controller.

**Comment by raelgc** [comment]
+1

**Comment by mainmachine** [comment]
+1

**Comment by melo0187** [comment]
+1

I'm not even sure if it has anything to do with the use of mimic_xpad driver option in xboxdrv settings. 

The controller screen in the settings has been reworked and does not offer a way to map the controller buttons, axis and triggerd like it used to do in older versions of the Steam client.

**Comment by vexofp** [comment]
+1

Ubuntu 14.04.3 with PS3 controller via sixad.

**Comment by KhelbenArunsun** [comment]
Same issue. This is a real head-scratcher. Been trying everything I can think of:

* Things I Tried:
    * I had previously blacklisted xpad
    * xboxdrv
    * removed xboxdrv
    * installed steamos-xpad-dkms

and nothing worked. There's still no way to edit the configuration.

My Specs:
Arch x86_64 Xbox360 controller
AMD FX-8350 4.0Ghz Eight-core processor
Nvidia Geforce GTX 750ti 2gb DDR5 VRAM
24gb RAM

**Comment by darkszluf** [comment]
this happens with my gamestop xbox 360 wired pad using xpad too, for some reasons it finds it like a logic 3 controller, xboxdrv doesn't find this controller for some reason even if it's listed in the xboxdrv compatible controllers.

Specs:
Ubunut gnome 15.10
amd FX-4300
XFX r7 250 2gb gddr3 core edition
4 gb ram 1600mhz crucial

lshw content:
http://pastebin.com/K1u8PbkD

**Comment by ProfessorKaos64** [comment]
I really do hope the BPM configuration comes back. This has been long gone in the client beta. I can confirm that configurations for BPM/Browser are coming (desktop configuration is already here) for the Steam Controller, but we have had no word on if the standard configuration coming back. Perhaps they wish everything to be automatic.

**Comment by tgurr** [comment]
+1 for bringing back the possibility to configure a Xbox360 controller, it worked great before and now the option is completely gone and everywhere are just images of a Steam controller. Now the Xbox360 wireless gamepad it just recognized as Xinput Controller and no way to configure it in Big Picture Mode.

Additionally SDL_GamepadBind key is gone from ~/.local/share/Steam/config/config.vdf which allowed copying the Steam configured controller settings to SDLGamepad.config of various games like e.g. Costume Quest which is now unplayable via the Xbox360 controller on Linux.

**Comment by filipnaumovic** [comment]
+1

**Comment by darkszluf** [comment]
i can confirm that you can use the feature again now.

**Comment by ProfessorKaos64** [comment]
@mhalano , please close. Configurations are back.

**Comment by mhalano** [comment]
I agree the configuration back with xpad kernel module using a official Xbox 360 controller. xboxdrv still don't work because the controller is always recognized as "XInput Controller" even with the option to mimic xpad enabled.

Someone could tell me if use xpad and the controller still is recognized as "XInput Controller"? There is no configuration screen for this type of controller and if is just a incompatibility with zboxdrv it is fine, but if is a problem with more controller models, even using xpad kernel module, I wll keep this bug open.

**Comment by tgurr** [comment]
@mhalano Thanks, I also use xboxdrv and as long as the controller configuration doesn't come back when using xboxdrv (it definitely worked at some point in the past) I also consider this bug as still valid.

**Comment by mhalano** [comment]
This issue is still valid? I think Valve reworked the input subsystem and now xpad kernel module is standard de facto for Xbox 360 controllers.

**Comment by darkszluf** [comment]
yeah it's fixed please close it.
