### ISSUE TITLE
Disk usage not being drawn on  Steam UI

### ISSUE THREAD

**Issue by bertogs** [ValveSoftware/steam-for-linux#4048]
As the title say the disk  usage is not being draw on Linux. Its drawn on Windows.

**Comment by FrancescoCeruti** [comment]
:+1: 
Same here, on Arch Linux 64bit

![schermata da 2015-10-03 22-12-45](https://cloud.githubusercontent.com/assets/5596673/10264924/f4939c8c-6a1b-11e5-8003-b6c7e06d2d50.png)

**Comment by inversephase** [comment]
+1. Also on Arch x64, currently kernel 4.2.1-1-ARCH but it never worked previously or on any other system including my Ubuntu laptop.

**Comment by ptrj** [comment]
Same problem on Linux Mint 17.x

**Comment by ToxikCoder** [comment]
Same problem Ubuntu 16.04 amd64 on 4.2.0-36 kernel

**Comment by Plagman** [comment]
This is fixed and will be released in a future update. Thanks!

**Comment by inversephase** [comment]
this can probably be considered closed for me, I get disk usage now.
