### ISSUE TITLE
Feature Request: Allow force install of game on linux when game is for Windows

### ISSUE THREAD

**Issue by anadon** [ValveSoftware/steam-for-linux#4052]
Since it is possible to get steam games running under wine in linux, to better allow users to do this to play games a "force install" option should be available.  While formal support shouldn't really exists, users hacking on games to just play them should find this useful.

**Comment by thePalindrome** [comment]
The main problem that I see for this is that the games run under wine couldn't talk properly with the linux steam client, among a host of other problems (directx installs anyone?)

An interesting feature for sure, not sure if it'd work well though.

**Comment by anadon** [comment]
More often than not, that's not the problem I've run into when I've use CLI args to force install something.  And getting a parallel windows steam install for something like fallout NV with sym-linking is at least a way to play the game, whereas it's very difficult to do so now.

I'm not suggesting that this is for novice users, but some on Linux are quiet adept at getting things to work if given the chance.

**Comment by thePalindrome** [comment]
Oh yeah, forgot that the CLI client can force install things...

Yeah, I'd for sure allow this, maybe only in the public betas though, because anyone that uses the beta is required to be willing  to clean up their system after the segfault-splosion ;)

**Comment by gdrewb-valve** [comment]
This is a duplicate but I couldn't find the other issue.  The chance of this happening is low.

**Comment by Antoine-Pous** [comment]
@gdrewb-valve I understand the difficulty but this feature would be amazing!

Many friends stay on windows only for games, allow them to use Linux would be a boost for the platform.

I really hope to see the linux client implement this feature :)

**Comment by Uramekus** [comment]
@kisak-valve  please close as proton is there to do it nowadays

**Comment by kisak-valve** [comment]
Closing per https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561.
