### ISSUE TITLE
Video playback with the Steam client

### ISSUE THREAD

**Issue by garrett85** [ValveSoftware/steam-for-linux#4054]
When viewing video game preview in the Steam client the playback is very slow to load and no more than a few seconds at a time will play before it has to buffer. This issue does not exist when view the same video game previews on the Steam site in my browser, only in the client.

OS = Linux Mint.

**Comment by reavertm** [comment]
I have the same problem. But I would say more - it's not just video playback. It feels like whole embedded chromium works terribly slowly.

In my case:
- Intel 2600k @4.4GHz, GTX 570 on Gentoo x86_64, using steam runtime for games (no special hacks to make steam use multilib (x86) from the system, only SDL_AUDIODRIVER=alsa overriden as I don't have pulseaudio), nvidia-drivers-381.22
- "Big picture" and all games work fine

Problems:
- steamwebhelper process consumes between 30% and 100% CPU, 100% when doing any actions causing steam-client to repaint
- scrolling when browsing steam store is sluggish
- there is visible lag in as-you-type text (even in this text editor when writing post, hence "sluggish" feel)
- this problem with videos - I think there is like 5 frames per second during playback, browsing store from Web - using chromium-60.0.3112.78:0 - is snappy

Some other related issue is https://github.com/ValveSoftware/steam-for-linux/issues/4653.
But, I explicitly disabled compositing. It doesn't help.

It used to work well in a past, unfortnately I cannot pinpoint the time where it stopped working well. I tried Steam Beta but it behaves identically.

**Comment by kisak-valve** [comment]
Hello @garrett85, @reavertm, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
