### ISSUE TITLE
Use system file manager instead of Steam's for file selection

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4058]
When selecting a new avatar for instance, Steam should use the system file manager instead of its own which has problems such as https://github.com/ValveSoftware/steam-for-linux/issues/3895

Steam having its own inconvenient file browser, which strangely always launches in Steam's directory as opposed to the user's home directory, is completely unnecessary, does not add to the experience, and just feels like a nuisance if anything.

**Comment by kisak-valve** [comment]
Closing in favor of #6828 because the user has turned into a ghost.
