### ISSUE TITLE
Client gives no notification about being kicked from a group

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#4059]
The web interface shows an invite notification for that, but it doesn't appear in the client.

**Comment by kisak-valve** [comment]
Hello @mtmkls, have you seen this issue in recent history?

**Comment by mtmkls** [comment]
I haven't been kicked from a group for a long time, so I haven't seen this issue. The notification system has seen some changes recently, so this issue might be fixed now.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
