### ISSUE TITLE
BPM language issue

### ISSUE THREAD

**Issue by Mohandevir** [ValveSoftware/steam-for-linux#4062]
Since udpdate 2.34, the filter menu at the left ("Recently played", "Installed"...)displays "<Span class..." instead of a qty. It's more client related but the bug appeared on brewmaster first (beta client I guess). There are no writings on some buttons too.

For the record, my Steam client is in french and I switched the interface to english to confirm that the problem is not present. 

Keep doing your great job.
Thanks!

**Comment by kisak-valve** [comment]
Hello @Mohandevir, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/steam-for-linux/issues/4064#issuecomment-456081325.
