### ISSUE TITLE
Big Picture displays HTML tags in menu items

### ISSUE THREAD

**Issue by kochd** [ValveSoftware/steam-for-linux#4064]
Screenshot attached.
![steambug](https://cloud.githubusercontent.com/assets/1825660/10475172/c3b35684-7240-11e5-89b1-7f8e4d0461fb.png)

<pre>
Linux claw-t430 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux
ii  steam:i386                                    1.0.0.50-6                          i386         Valve's Steam digital software delivery system
</pre>

**Comment by kochd** [comment]
This is fixed with the latest update ( 20151014 )

**Comment by GargGit** [comment]
Exactly the same issue (windows + linux, beta and stable)
For information I use french. I my case, Game label is empty.

**Comment by Mohandevir** [comment]
I confirm, Games label stands empty. This is the same issue that I got on this thread:
https://github.com/ValveSoftware/steam-for-linux/issues/4062

At the beginning it was far worse but many corrections have been made.

Thanks for your great work so far.

**Comment by GargGit** [comment]
I hope that will be fixed asap because it's like that since 2 or 3 months in my case (beta + stable client).

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Mohandevir** [comment]
No. Everything has been fine for quite some time, now. :)
Thanks for checking.

**Comment by kisak-valve** [comment]
Thanks for the feedback @Mohandevir, closing.
