### ISSUE TITLE
BIG Picture

### ISSUE THREAD

**Issue by samrock09** [ValveSoftware/steam-for-linux#4065]
Por favor gostaria de relatar um bug para equipe de STEAM corrigir, em modo de Big Picture no Linux na hora de jogar qualquer jogo, apresentar um BUG na hora de captura da tela. quando captura da tela a foto fica feia. 

Placa de video é AMD

**Comment by gdrewb-valve** [comment]
Google translate:

Please would like to report a bug to fix STEAM team in Big Picture mode in Linux's time to play any game, submit a bug on the screen capture time. screen capture when the picture is ugly.

Graphics card is AMD

**Comment by kisak-valve** [comment]
Hello @samrock09, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
