### ISSUE TITLE
In-Game Overlay disables keyboard and mouse after returning to the game

### ISSUE THREAD

**Issue by rea987** [ValveSoftware/steam-for-linux#4066]
**ISSUE:**
Steam In-Game Overlay appears to be broken.

**OS:**
Linux Mint 13 Mate (x86)

**STEPS:**
- Launch a game from Steam library
- Press shift+tab to open in-game overlay
- Return to the game

**RESULTS:**
Keyboard and mouse are disabled after returning to the game from Steam In-Game Overlay.

**EXPECTED:**
Keyboard and mouse should work fine after returning to the game from Steam In-Game Overlay.

**ADDITIONAL INFORMATION:**
When the problem occures, any keyboard and mouse command including launching Overlay does not work. System requires hard reboot. The problem persists on many games including The Original Strife: Vetean Edition, Cave Story+ with the exception of GoldSrc games (Half-Life, Counter-Strike, etc.). The problem appeared with client updated of 7th and 8th October 2015 and keeps going on with the client update of 14th October 2015; both stable and beta versions of the client are affected by the bug.

**CLIENT VERSION:**

![ekrangoruntusu-isimsiz pencere](https://cloud.githubusercontent.com/assets/1547646/10515455/3d57821e-735c-11e5-9b9d-3ac0313db884.png)

**SYSTEM INFORMATION:**

```
Processor Information:
Vendor:  GenuineIntel
CPU Family:  0x6
CPU Model:  0xd
CPU Stepping:  0x8
CPU Type:  0x0
Speed:  1867 Mhz
1 logical processor
1 physical processor
HyperThreading:  Unsupported
FCMOV:  Supported
SSE2:  Supported
SSE3:  Unsupported
SSSE3:  Unsupported
SSE4a:  Unsupported
SSE41:  Unsupported
SSE42:  Unsupported

Network Information:
Network Speed:  

Operating System Version:
Linux Mint 13 Maya (32 bit)
Kernel Name:  Linux
Kernel Version:  3.2.0-91-generic
X Server Vendor:  The X.Org Foundation
X Server Release:  11103000
X Window Manager:  Marco
Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
Driver:  Tungsten Graphics, Inc Mesa DRI Intel(R) 915GM x86/MMX/SSE2

Driver Version:  1.4 Mesa 8.0.4
OpenGL Version: 1.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x2592
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1280 x 800
Desktop Resolution: 1280 x 800
Primary Display Size: 13,03" x 8,15"  (15,35" diag)
                                        33,1cm x 20,7cm  (39,0cm diag)
Primary VRAM Not Detected

Sound card:
Audio device: Realtek ALC250 rev 2

Memory:
RAM:  2004 Mb

Miscellaneous:
UI Language:  English
LANG:  tr_TR.UTF-8
Microphone:  Not set
Total Hard Disk Space Available:  48062 Mb
Largest Free Hard Disk Block:  6993 Mb

Installed software:

Recent Failure Reports:
```

**SAME/RELATED ISSUES:**

http://steamcommunity.com/app/221410/discussions/0/490123197938909995/
http://steamcommunity.com/app/221410/discussions/0/487870763304938758/

**Comment by Tele42** [comment]
There's been trouble in the past with tr_TR.UTF-8, can you do a test by closing steam, then run LANG=C steam and test a game.

**Comment by rea987** [comment]
@Tele42 Unfortunately no difference. For the second attemp; I additionally alt+tab AFTER shift+tab to return the terminal instead of the game in order to save the output. The lines before "Killed" is the full output until I opened the overlay. **Killed** indicates that I killed the running and already keyboard/mouse locked game by using mate-system-monitor. I immediately quit Steam afterwards.

    $ LANG=C steam
    Running Steam on linuxmint 13 32-bit
    STEAM_RUNTIME is enabled automatically
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    [1015/200235:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
    [1015/200235:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
    Installing breakpad exception handler for appid(steamwebhelper)/version(20151014123328)
    Installing breakpad exception handler for appid(steamwebhelper)/version(1444826008)
    [1015/200235:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
    Installing breakpad exception handler for appid(steamwebhelper)/version(20151014123328)
    Installing breakpad exception handler for appid(steamwebhelper)/version(1444853545)
    Installing breakpad exception handler for appid(steamwebhelper)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    FillInMachineIDInfo took a total of 0 milliseconds
    Wireless receiver firmware /home/rifat/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1442256398.
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
    Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    local (potentially out of sync) copy of roaming config loaded - 9134 bytes.
    roaming config store loaded successfully - 9134 bytes.
    migrating temporary roaming config store

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

    (steam:2572): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    Failed to init SteamVR because it isn't installed
    ExecCommandLine: ""/home/rifat/.local/share/Steam/ubuntu12_32/steam" "
    System startup time: 20,04 seconds
    Installing breakpad exception handler for appid(steam)/version(1444853545)
    [1015/200250:ERROR:renderer_main.cc(200)] Running without renderer sandbox
    Generating new string page texture 73: 1024x256, total string texture memory is 1,36 MB
    Generating new string page texture 74: 128x256, total string texture memory is 131,07 KB
    Generating new string page texture 75: 128x256, total string texture memory is 1,49 MB
    Generating new string page texture 76: 64x256, total string texture memory is 1,56 MB
    Generating new string page texture 77: 8x256, total string texture memory is 1,56 MB
    Generating new string page texture 78: 32x256, total string texture memory is 1,60 MB
    Generating new string page texture 83: 512x256, total string texture memory is 2,12 MB
    Generating new string page texture 84: 384x256, total string texture memory is 2,51 MB
    Generating new string page texture 85: 128x256, total string texture memory is 2,65 MB
    Generating new string page texture 88: 24x256, total string texture memory is 2,67 MB
    Generating new string page texture 89: 256x256, total string texture memory is 2,93 MB
    Running Steam on linuxmint 13 32-bit
    STEAM_RUNTIME has been set by the user to: /home/rifat/.local/share/Steam/ubuntu12_32/steam-runtime
    ExecCommandLine: "/home/rifat/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
    ExecSteamURL: "steam://open/driverhelperready"
    Game update: AppID 317040 "Strife: Veteran Edition", ProcID 2746, IP 0.0.0.0:0
    ERROR: ld.so: object '/home/rifat/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
    ERROR: ld.so: object '/home/rifat/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
    ERROR: ld.so: object '/home/rifat/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
    Setting breakpad minidump AppID = 317040
    Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198002510878 [API loaded no]
    Installing breakpad exception handler for appid(gameoverlayui)/version(20151014123426)
    Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
    Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
    Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
    Killed
    Game removed: AppID 317040 "Strife: Veteran Edition", ProcID 2750 
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    Refresh rate: 1
    [2015-10-15 20:02:06] Startup - updater built Oct 14 2015 12:33:51
    Looks like steam didn't shutdown cleanly, scheduling immediate update check
    [2015-10-15 20:02:06] Checking for update on startup
    [2015-10-15 20:02:06] Checking for available updates...
    [2015-10-15 20:02:07] Download skipped: /client/steam_client_ubuntu12 version 1444853545, installed version 1444853545
    [2015-10-15 20:02:07] Nothing to do
    [2015-10-15 20:02:07] Verifying installation...
    [2015-10-15 20:02:07] Performing checksum verification of executable files
    [2015-10-15 20:02:28] Verification complete
    [2015-10-15 20:08:08] Shutdown

**Comment by sevenskull** [comment]
I am having this bug also.
I am using Linux Mint 17.2 Cinnamon 64-bit (ubuntu 14.04).
Block Keyboard and Mouse after the first time you use overlay. The only way i found is CTRL + F1 and killing the game process.

**Comment by rea987** [comment]
As it turned out Unity engine games such as **Canabalt** and **Gravity Badgers** are not affected by the Steam Overlay bug. As 25th October 2015, the bug has not been fixed.

http://store.steampowered.com/app/358960/
http://store.steampowered.com/app/267060/

**Comment by Sector14** [comment]
We're seeing this as well. Need to investigate further, I'll update once we've done more testing.

**Comment by ExplosiveSilo** [comment]
Linux Mint 17.3 MATE 64bit here.
Killing Floor 1 experiences the same problem.

**Comment by Plagman** [comment]
Can people affected by this issue run Steam with the STEAM_OVERLAY_LOGGING environment variable set to 1, and attach /tmp/gameoverlayrenderer.log after running into the issue?

**Comment by agolp** [comment]
$ cat /tmp/gameoverlayrenderer.log
    Fri Jan 01 16:15:36 2016 UTC - Failed to increase file count limit. Currently: 4096
    Fri Jan 01 16:15:36 2016 UTC - GameID = 102840, PID: 13462
    Fri Jan 01 16:15:36 2016 UTC - ----------------------------
    Fri Jan 01 16:15:36 2016 UTC - One-time initialization: pid 13462 for game 102840
    Fri Jan 01 16:15:38 2016 UTC - OpenGL version: 4.5 compatibility (overlay will use fixed function)
    Fri Jan 01 16:15:38 2016 UTC - OpenGL version is >= 3.1
    Fri Jan 01 16:15:38 2016 UTC - OpenGL Enabled LOD bias
    Fri Jan 01 16:15:38 2016 UTC - Texture units detected: 4
    Fri Jan 01 16:15:46 2016 UTC - Enabling overlay
    Fri Jan 01 16:15:46 2016 UTC - First swap of overlay on 0x8593740 0x240000f
    Fri Jan 01 16:15:46 2016 UTC -   using display 0x858e5a0 window 0x240000f key input win 0x240000e (event mask 0x624003)
    Fri Jan 01 16:15:46 2016 UTC - Game process locale is 'C'
    Fri Jan 01 16:15:46 2016 UTC - Update size of 0x240000f to 1680,1050
    Fri Jan 01 16:15:51 2016 UTC - Disabling overlay
    Fri Jan 01 16:15:51 2016 UTC - Restore win 0x240000f cursor to 0x240000b (valid)
    Fri Jan 01 16:15:57 2016 UTC - Enabling overlay
    Fri Jan 01 16:15:57 2016 UTC - First swap of overlay on 0x8593740 0x240000f
    Fri Jan 01 16:15:57 2016 UTC -   using display 0x858e5a0 window 0x240000f key input win 0x240000e (event mask 0x624003)
    Fri Jan 01 16:15:57 2016 UTC - Game process locale is 'C'
    Fri Jan 01 16:15:57 2016 UTC - Update size of 0x240000f to 1680,1050
    Fri Jan 01 16:16:26 2016 UTC - XUngrabPointer 0x858e5a0 time 0
    Fri Jan 01 16:16:26 2016 UTC - XUngrabKeyboard 0x858e5a0 time 0
    Fri Jan 01 16:16:26 2016 UTC - XUngrabPointer 0x858e5a0 time 0
    Fri Jan 01 16:16:26 2016 UTC - XUngrabKeyboard 0x858e5a0 time 0
    Fri Jan 01 16:16:26 2016 UTC - Destroy window 0x240000f
    Fri Jan 01 16:16:26 2016 UTC - Destroy window 0x240000d
    Fri Jan 01 16:16:26 2016 UTC - Destroy window 0x240000e

**Comment by ekaris** [comment]
This bug is still not fixed! Playing Killing floor and using steam overlay leads to this problem!
http://steamcommunity.com/app/1250/discussions/0/490123197946609705/

**Comment by ekaris** [comment]
Thu Dec 22 14:16:59 2016 UTC - GameOverlay process started: pid: 31645
Thu Dec 22 14:16:59 2016 UTC - GameOverlay process connecting to: pid: 31638
Thu Dec 22 14:16:59 2016 UTC - BuildID: 1482202190
Thu Dec 22 14:16:59 2016 UTC - Steam Path: /home/unknown/.steam/
qui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:16:59 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDqui dez 22 14:17:01 2016 UTC - Generating new string page texture 2748: 32x256, total string texture memory is 32.77 KB
qui dez 22 14:17:01 2016 UTC - Generating new string page texture 2749: 48x256, total string texture memory is 81.92 KB
qui dez 22 14:17:01 2016 UTC - Generating new string page texture 2750: 128x256, total string texture memory is 212.99 KB
qui dez 22 14:17:01 2016 UTC - Generating new string page texture 2751: 256x256, total string texture memory is 475.14 KB
qui dez 22 14:17:04 2016 UTC - Overlay enable requested by game
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3001: 64x256, total string texture memory is 540.67 KB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3002: 384x256, total string texture memory is 933.89 KB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3003: 256x256, total string texture memory is 1.20 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3004: 128x256, total string texture memory is 1.33 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3005: 16x256, total string texture memory is 1.34 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3006: 24x256, total string texture memory is 1.37 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3007: 8x256, total string texture memory is 1.38 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3009: 64x256, total string texture memory is 1.44 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3010: 128x256, total string texture memory is 1.57 MB
qui dez 22 14:17:05 2016 UTC - Generating new string page texture 3011: 16x256, total string texture memory is 1.59 MB
qui dez 22 14:17:08 2016 UTC - Overlay disable requested by game
qui dez 22 14:17:11 2016 UTC - Overlay enable requested by game
qui dez 22 14:17:15 2016 UTC - opening url: http://steamcommunity.com/sharedfiles/filedetails/?id=820576577
qui dez 22 14:17:15 2016 UTC - Errors in resource/layout/overlaywebbrowser.layout:
Unknown key 'scaling' set in style 'URLStatusImage' in file 'resource/layout/overlaywebbrowser.layout'
qui dez 22 14:17:17 2016 UTC - Overlay disable requested by game
qui dez 22 14:17:40 2016 UTC - Warning: The game hasn't rendered a frame from us in over 10 seconds
qui dez 22 14:17:53 2016 UTC - Overlay enable requested by game
qui dez 22 14:17:53 2016 UTC - Generating new string page texture 3050: 1024x256, total string texture memory is 2.64 MB
qui dez 22 14:17:59 2016 UTC - Overlay disable requested by game
qui dez 22 14:23:51 2016 UTC - Overlay enable requested by game
qui dez 22 14:23:52 2016 UTC - Generating new string page texture 3057: 256x256, total string texture memory is 2.90 MB
qui dez 22 14:23:56 2016 UTC - Generating new string page texture 3060: 512x256, total string texture memory is 3.42 MB
qui dez 22 14:23:58 2016 UTC - Overlay disable requested by game
qui dez 22 14:24:02 2016 UTC - Overlay enable requested by game
qui dez 22 14:24:02 2016 UTC - Overlay disable requested by game
qui dez 22 14:24:03 2016 UTC - Overlay enable requested by game
qui dez 22 14:24:06 2016 UTC - Overlay disable requested by game
qui dez 22 14:24:10 2016 UTC - Overlay enable requested by game
qui dez 22 14:24:16 2016 UTC - Detected possibly crashed/killed game, exiting
qui dez 22 14:24:16 2016 UTC - Shutting down overlay

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by rea987** [comment]
It has been a long time since I issued that bug report and I haven't encountered recently. So, closing the issue.
