### ISSUE TITLE
Specific music file crashes Steam Overlay when selected

### ISSUE THREAD

**Issue by jeifour** [ValveSoftware/steam-for-linux#4067]
I'm running currently newest Beta of the client.
![_2015-10-15_21-54-23](https://cloud.githubusercontent.com/assets/3247063/10525855/6811e6b8-7387-11e5-9987-e454e04cef00.png)
This is my system: https://gist.github.com/jeifour/242a44a3758b4b89a8ac

The problem is: When I'm in-game (I tried different games, outcome seems to be the same) and I'm browsing my music library via the Steam Overlay, when I click on a certain Album, the overlay will disappear and not open again. Sometimes it will open again 10-15 seconds later but still not be really responsive. This happens only for specific files, I tested this and also tried changing some parameters like album art size or tagging, but wasn't able to find what exactly makes this occur. It however seems to happen consistently with the same file, and not happen at all with other files.

I don't have any problems when I browse the music library via the Steam client, it seems to be specific to the overlay. The music file itself plays fine in Steam. I also generally don't have a problem with browsing the music library through the overlay, as long as I don't try and select this album/artist.

You can get a copy of the music file here: https://my.mixtape.moe/knepik.flac

**Comment by kisak-valve** [comment]
Hello @jeifour, are you still experiencing this issue on an up to date system?

**Comment by jeifour** [comment]
I don't experience this issue. If it is not reproducible with the file I uploaded then this is probably fixed I'd assume.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
