### ISSUE TITLE
Steam Won't Open Game Since Last Update

### ISSUE THREAD

**Issue by gary-hammer** [ValveSoftware/steam-for-linux#4068]
Steam is not loading games for me. Steam itself opens and runs fine.
When I choose a game to play, the game attempts a launch, then is just gone.
I have reset steam, left the steam beta, verified local files, removed and installed games, nothing has helped.
This is the only error I see in the syslog:
CivBE[3286] trap invalid opcode ip:f7084cdb sp:e90fda00 error:0 in libpthread-2.19.so[f7074000+18000]

I also see this in the console if I launch steam from there:
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

Steam client built Oct 14 at 12:40:46
Steam API v017
Steam package version 1444853545

**Comment by PepsiGuy** [comment]
If I add this under launch options, I get the game to open and run.
LD_PRELOAD=/usr/lib/nvidia/libGL.so %command%

**Comment by koahv** [comment]
I have the same issue with Gentoo x64. Your fix works.

First noticed after upgrading glibc from 2.21-r1 to 2.22-r1. Could be unrelated.

**Comment by koahv** [comment]
Fault exists with a hardened sources gresec option. I'll try to find which one some other time. Could be memory related due to "segfault at 0 ip" dmesg.

**Comment by kisak-valve** [comment]
Hello @gary-hammer, are you still experiencing this issue on an up to date system?

**Comment by gary-hammer** [comment]
After 3 years and change why would you ask?
