### ISSUE TITLE
AMD R9 Nano GPU not recognized by Big Picture Mode correctly

### ISSUE THREAD

**Issue by majewsky** [ValveSoftware/steam-for-linux#4069]
When I entered "Big Picture" mode, it initially had some ridiculously low resolution (compared to my native 4K), so I dove into "Settings > Display" where I could increase the resolution to Full HD, but only with a warning that the GPU has only 256 MB RAM. Indeed the Display Device reported in the same view is "ATI Technologies Inc. 256 MB", which is definitely not correct. :)

uname, glxinfo: https://gist.github.com/majewsky/4a280bcfd789dc76b884

**Comment by majewsky** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon (TM) R9 Fury Series 

    Driver Version:  4.5.13399 Compatibility Profile Context 15.20.1046
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x7300
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 34.57" x 19.09"  (39.49" diag)
                                            87.8cm x 48.5cm  (100.3cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  15995 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  469029 Mb
    Largest Free Hard Disk Block:  381477 Mb
    
Installed software:
    
Recent Failure Reports:
    Fri Oct 16 23:14:55 2015 GMT: file ''/tmp/dumps/assert_20151017011454_33.dmp'', upload yes: ''CrashID=bp-83c5261a-c8ca-4c6c-9f1e-18f212151016''

**Comment by Tele42** [comment]
Duplicate of #1311, this does not affect any games, it's only cosmetic. Did this message prevent you from increasing the resolution?

**Comment by majewsky** [comment]
Yes, that's the issue. I already suspected this to be a cosmetic problem since games are not affected, but it's nice to have that confirmed.
