### ISSUE TITLE
Add support for Steam controller on udev rules

### ISSUE THREAD

**Issue by mhalano** [ValveSoftware/steam-for-linux#4072]
The package steam-launcher has the file /lib/udev/rules.d/99-steam-controller-perms.rules but this fill still don't have permissions for Steam controller, just Oculus. There is a person talking about problems with Kubuntu on the link https://bugs.launchpad.net/ubuntu/+source/steam/+bug/1498655

Someone can add rules to access hidraw with vendor ID and product ID? Use just vendor ID is a bad practice and make the things insecure.

**Comment by kisak-valve** [comment]
Hello @mhalano, this issue was addressed distro-side back in 2015. Since then the udev files have been split off into a separate `steam-devices` package.

Is there a scenario where you're still seeing this issue?

**Comment by mhalano** [comment]
@kisak-valve 

This seems fixed now. I will close this issue.
