### ISSUE TITLE
Support is horrendous

### ISSUE THREAD

**Issue by gear4s** [ValveSoftware/steam-for-linux#4078]
My account was hijacked, and I submitted a ticket, and they tell me my account hasn't been hijacked ? wtf ? an obvious South African account suddenly playing in SEA, with a completely different IP, and wi th submitted proof the account is mine ? this is horseshit service -_-

**Comment by gdrewb-valve** [comment]
I'm sorry you had a bad experience but unfortunately this isn't the place to post about it.
