### ISSUE TITLE
Sound-Related Crashes in Steam

### ISSUE THREAD

**Issue by ButchDeLoria** [ValveSoftware/steam-for-linux#4079]
For the past couple of weeks I've been getting intermittent Steam crashes, usually when getting chat messages. It didn't click with me since I had the notification sound turned off that it might be an audio issue. Below is Steam's terminal output, logging straight in and going immediately to Settings -> Voice, trying to change the default audio device, and it crashing. So far this is the easiest way I've found to reproduce the crashing. I'm running Steam on the latest KDE Plasma 5 on Arch, up to date as of 10/20/15.

Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[1020/223830:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
[1020/223830:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151014123328)
Installing breakpad exception handler for appid(steamwebhelper)/version(1444826008)
[1020/223830:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
[1020/223830:ERROR:nss_util.cc(1007)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151014123328)
Installing breakpad exception handler for appid(steamwebhelper)/version(1444853545)
Installing breakpad exception handler for appid(steamwebhelper)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
Wireless receiver firmware /home/joshua/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1442256398.
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
FillInMachineIDInfo took a total of 0 milliseconds

** (steam:12263): WARNING **: Unknown device type 14

** (steam:12263): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type
Installing breakpad exception handler for appid(steam)/version(1444853545)

** (steam:12263): WARNING **: Ignoring invalid property 'secondaries'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'

** (steam:12263): WARNING **: Ignoring invalid property 'secondaries'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'

** (steam:12263): WARNING **: Ignoring invalid property 'secondaries'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'

** (steam:12263): WARNING **: Ignoring invalid property 'route-data'

** (steam:12263): WARNING **: Ignoring invalid property 'address-data'
Installing breakpad exception handler for appid(steam)/version(1444853545)
Installing breakpad exception handler for appid(steam)/version(1444853545)
local (potentially out of sync) copy of roaming config loaded - 7037 bytes.
roaming config store loaded successfully - 7037 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1444853545)
ExecCommandLine: ""/home/joshua/.local/share/Steam/ubuntu12_32/steam" "
Installing breakpad exception handler for appid(steam)/version(1444853545)
System startup time: 4.59 seconds
Running Steam on arch rolling 64-bit
STEAM_RUNTIME has been set by the user to: /home/joshua/.local/share/Steam/ubuntu12_32/steam-runtime
[1020/223834:ERROR:renderer_main.cc(200)] Running without renderer sandbox
Generating new string page texture 225: 64x256, total string texture memory is 65.54 KB
Generating new string page texture 226: 256x256, total string texture memory is 327.68 KB
Generating new string page texture 227: 128x256, total string texture memory is 458.75 KB
Generating new string page texture 228: 48x256, total string texture memory is 507.90 KB
ExecCommandLine: "/home/joshua/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 232: 128x256, total string texture memory is 638.98 KB
Generating new string page texture 233: 256x256, total string texture memory is 901.12 KB
Generating new string page texture 234: 128x256, total string texture memory is 1.03 MB
Generating new string page texture 235: 384x256, total string texture memory is 1.43 MB
Generating new string page texture 236: 64x256, total string texture memory is 1.49 MB
Generating new string page texture 237: 1024x256, total string texture memory is 2.54 MB
Generating new string page texture 243: 128x256, total string texture memory is 2.67 MB
Generating new string page texture 270: 256x256, total string texture memory is 2.93 MB
Generating new string page texture 277: 32x256, total string texture memory is 2.97 MB
Generating new string page texture 308: 24x256, total string texture memory is 2.99 MB
Generating new string page texture 309: 48x256, total string texture memory is 3.04 MB
Generating new string page texture 310: 128x256, total string texture memory is 3.17 MB
Generating new string page texture 311: 64x256, total string texture memory is 3.24 MB
Generating new string page texture 315: 16x256, total string texture memory is 3.25 MB
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:942:(snd_pcm_route_determine_ttable) Invalid slave channel: FL
ALSA lib pcm_route.c:942:(snd_pcm_route_determine_ttable) Invalid slave channel: FL
ALSA lib setup.c:519:(add_elem) Unknown field skip_rest
ALSA lib setup.c:519:(add_elem) Unknown field skip_rest
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started
assert_20151020223830_1.dmp[12434]: Uploading dump (out-of-process)
/tmp/dumps/assert_20151020223830_1.dmp
/home/joshua/.local/share/Steam/steam.sh: line 756: 12263 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[1020/223841:WARNING:pref_notifier_impl.cc(27)] pref observer found at shutdown plugins.always_authorize
[1020/223841:WARNING:pref_notifier_impl.cc(27)] pref observer found at shutdown plugins.allow_outdated
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
assert_20151020223830_1.dmp[12434]: Finished uploading minidump (out-of-process): success = yes
assert_20151020223830_1.dmp[12434]: response: CrashID=bp-896f7cf9-17a8-42bc-9358-9a2d02151020
assert_20151020223830_1.dmp[12434]: file ''/tmp/dumps/assert_20151020223830_1.dmp'', upload yes: ''CrashID=bp-896f7cf9-17a8-42bc-9358-9a2d02151020''

**Comment by uberscientist** [comment]
might not help, but I was getting crashes that I thought were related to the sound because those were the only errors I would see in the log, but it turned out my GPU was overheating.  I replaced the thermal paste and cleaned it well and I haven't had issues.

**Comment by ButchDeLoria** [comment]
I just tried reproducing it on my laptop, so maybe it's an issue with how my desktop is configured. I'll see what I can find out.

**Comment by ButchDeLoria** [comment]
Deleting everything in my ~/.steam folder but SteamApps and reinstalling seems to have done the trick. Must have been something odd happening during an update or something.

**Comment by sizeofbool** [comment]
By the looks of your log:
```
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:942:(snd_pcm_route_determine_ttable) Invalid slave channel: FL
ALSA lib pcm_route.c:942:(snd_pcm_route_determine_ttable) Invalid slave channel: FL
ALSA lib setup.c:519:(add_elem) Unknown field skip_rest
ALSA lib setup.c:519:(add_elem) Unknown field skip_rest
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started
```
Your sound system configuration is clearly messed up. Try to completely remove and reinstall alsa related packages(to regen default alsa configuration). Remove "jackd" server if you don't use it and install pulseaudio(i've found pulseaudio is more simple to use and robust).
ArchWiki is quite good to look for an additional info about alsa configuration and testing. [Link to ArchWiki](https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture)

**Comment by ButchDeLoria** [comment]
I've got a lot of packages that require jack to be installed and I already use PulseAudio, but I'll give reinstalling alsa packages a shot. No matter how screwed up my sound is though, it's fixed in the Steam Beta client.

**Comment by ButchDeLoria** [comment]
Steam has started doing it again, but this time I'm just going to include a full copy of the error log. Same way to reproduce it on my system, just send a message to the client and it will crash from the audio ping, or go to Settings -> Voice -> Change Default Microphone. You can just hit Cancel and it will crash anyway. jack has to be installed for other programs I use but isn't running while Steam is, and I'm using Pulseaudio with a clean configuration.
[error_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/36242/error_log.txt)

**Comment by Tele42** [comment]
@ButchDeLoria do you have openal's .alsoftrc configured to use JACK? If so, then all the openal libraries in the steam's folder (including the runtime) are too old to understand the config file, and will fail.

**Comment by ButchDeLoria** [comment]
@Tele42 I don't have an .alsoftrc file and I haven't done any manual configuration of ALSA, as far as I know it's the stock configuration from the Arch devs. I created a new user with a fresh home directory, and I still had the crashing problem, as well as with another desktop environment. On my Arch install on my laptop however, with the same amount of not messing with configuration files, there was no crashing problem, while also giving significantly less audio errors. Both are using Pulseaudio, with jack installed as a dependency for mpv, mpd, gstreamer plugins, etc. There has to be some fundamental hardware or software problem that's present on my desktop but not my laptop, and both have almost identical local home directories and config files. Maybe it's an nVidia-related problem, since my laptop uses integrated Intel graphics, and my desktop uses a GTX 780.

**Comment by ButchDeLoria** [comment]
I am a tremendous moron. I tried switching back to the release nVidia proprietary drivers, and it works perfectly. It's an issue with the beta drivers, and likely is on nVidia's end.
