### ISSUE TITLE
Could not load cef_extensions.pak

### ISSUE THREAD

**Issue by linuxcbon** [ValveSoftware/steam-for-linux#4080]
Hi,
when running steam client, I have always this error message : 
ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
But I can't find that file, steam client doesn't have it.
Thanks for your help

**Comment by gdrewb-valve** [comment]
Is something not working or are you just curious about the message?

**Comment by linuxcbon** [comment]
Hi,

I don't know, it seems to work, but there is always that error message because many distros don't have that file.
Is it possible for you to include it by default to steam client ?
Thanks for your help.

Cheers
linuxcbon

**Comment by Oxalin** [comment]
@linuxcbon are you using Steam's runtime libraries or are you using your system's native libraries? Are you able to launch the web browser in Big picture mode? Are you able to launch videos under Library->Videos (you may have to find a free video from the Store)?

**Comment by Oxalin** [comment]
@gdrewb-valve , whether or not the missing file has an impact on Steam, to make this error disappear, the missing file should be taken from the Chromium Embedded Framework (CEF) project (https://bitbucket.org/chromiumembedded/cef). Valve is already using CEF for its browser and, if I'm right, its video player. According to Steam updates, the last big CEF update was less than 2 weeks ago when it was updated to version 47. In the original CEF bundle, the file cef_extensions.pak is under Resources, along with cef.pak, cef_100_percent.pak and cef_200_percent.pak, which are already included in Steam client.

cef_extensions.pak was added in Chromium 45 (CEF bundle 2454).
https://bitbucket.org/chromiumembedded/cef/issues/1565/re-implement-pdf-viewer-using-out-of#comment-20427105
https://bitbucket.org/chromiumembedded/cef/issues/1565/re-implement-pdf-viewer-using-out-of#comment-20427478

Adding manually the file next to the other .pak files make the error disappear.

**Comment by gdrewb-valve** [comment]
The Steam team will grab the file eventually but as it doesn't cause any problems it's very low on the priority list.

**Comment by linuxcbon** [comment]
Many linux distributions don't have that file (cef_extensions.pak), so in my opinion, yes it is important to have it by default included in the steam client.
Thanks in advance.

**Comment by kisak-valve** [comment]
Closing as cef_extensions.pak was added some time ago.
