### ISSUE TITLE
libGL error: unable to load driver

### ISSUE THREAD

**Issue by linuxcbon** [ValveSoftware/steam-for-linux#4081]
Hi,
when runing steam client in linux, I always have this error messages : 
"libGL error: unable to load driver"
"libGL error: driver pointer missing"

solution found : remove 2 files /.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6*

thanks for your help

**Comment by gdrewb-valve** [comment]
Duplicate of #3273.
