### ISSUE TITLE
Crash on launch attempt after last update

### ISSUE THREAD

**Issue by uberscientist** [ValveSoftware/steam-for-linux#4082]
```
$ steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
/home/nak/.local/share/Steam/steam.sh: line 756:  9111 Illegal instruction     (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

I get the same with STEAM_RUNTIME=0 too.

If anyone needs more info let me know!

**Comment by OrdinaryMagician** [comment]
Does your dmesg show something like this? I had the same issue too and had to delete the whole thing and redownload.
`traps: steam[15676] trap invalid opcode ip:568542f9 sp:ff921660 error:0 in steam[5661d000+3a2000]`

**Comment by mikebryant** [comment]
I think this is a duplicate of #4077

**Comment by uberscientist** [comment]
Thanks guys the "deleting ~/.local/share/Steam/package/beta, then running steam --reset." work around seems to have worked for now
