### ISSUE TITLE
32-bit Linux Mint 13/Ubuntu 12.04 "Illegal instruction" after latest steam update

### ISSUE THREAD

**Issue by Max-E** [ValveSoftware/steam-for-linux#4084]
Virtually identical to this issue:
https://github.com/ValveSoftware/steam-for-linux/issues/54

Here's the difference:
1. I very definitely have SSE2. I have a Nehalem-era Core i5. Here is my /proc/cpuinfo: http://pastebin.com/BG5CvsA9
2. Steam was working fine for me yesterday, it was the latest update that caused the problem.

The STEAM_RUNTIME environment variable didn't seem to make a difference either way:
maxtothemax@maxtothemax-mint ~ $ steam
Running Steam on linuxmint 13 32-bit
STEAM_RUNTIME is enabled automatically
/home/maxtothemax/.local/share/Steam/steam.sh: line 756: 15926 Illegal instruction     $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
maxtothemax@maxtothemax-mint ~ $ STEAM_RUNTIME=0 steam
Running Steam on linuxmint 13 32-bit
STEAM_RUNTIME is disabled by the user
/home/maxtothemax/.local/share/Steam/steam.sh: line 756: 16062 Illegal instruction     $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

My guess is that someone thought it would be a bright idea to use -March=native for the latest build, and accidentally included some instructions my CPU doesn't support. If this was a deliberate choice, consider the fact that I've had a pretty stable experience with Steam on this computer and haven't had bad performance with it, so unless something has radically changed, I don't think it's justified to hike the system requirements like this.

**Comment by deathlire** [comment]
They have fixed this issue. try mv'ing steam.sh to steam.old and run steam..should get you the new update.

**Comment by Max-E** [comment]
That appears to have worked, thank!
