### ISSUE TITLE
X no longer starting

### ISSUE THREAD

**Issue by mafgh** [ValveSoftware/steam-for-linux#4086]
As of 21. October 2015 X is no longer starting on my machine.

I can see Grub starting, a couple of console log messages, a resolution switch, a mouse pointer appearing for just a second and disappearing again. After that, resolution switch after resolution switch.

**Comment by sizeofbool** [comment]
Why do you think this is Steam Client issue?

Boot in "single" mode and look in logs for clues, why Xorg crashes.

**Comment by mafgh** [comment]
Please close, got the wrong project, sorry for the noise.

**Comment by mafgh** [comment]
FWIW, it was a Steam Client Bug, see https://github.com/ValveSoftware/steam-for-linux/issues/4076
