### ISSUE TITLE
Games needing a keyboard no longer start

### ISSUE THREAD

**Issue by mafgh** [ValveSoftware/steam-for-linux#4088]
This is on SteamOS. I was affected by #4077 and run a *steam --reset* which did install an update and now the client is starting again.

However I can no longer play games requiring a keyboard, f.e. Contraption Maker or Broken Sword 5. They seem to start for a second, sometimes I do see a Developer/Publisher/... Logo, but then I get dropped back into the client.

/tmp/dump/steam_stdout has:
> Detected possibly crashed/killed game, exiting

Contraption Maker log ends with
> entering CMSteamWorkshop

**Comment by mafgh** [comment]
There was an update today and it seems that I can play keyboard games again, Contraption Maker and Broken Sword 5 are starting again.

**Comment by liamdawe** [comment]
Is this still the case (fixed?). This can be closed if so.

**Comment by mafgh** [comment]
It still works for me

**Comment by liamdawe** [comment]
Awesome, this can be closed then.
