### ISSUE TITLE
Cant run steam in Ubuntu Mate 15.10

### ISSUE THREAD

**Issue by Vutras** [ValveSoftware/steam-for-linux#4094]
I get this error

steam
Running Steam on ubuntu 15.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by gdrewb-valve** [comment]
This is probably a duplicate of other issues here, such as #3273.

**Comment by Tele42** [comment]
Long story short, use the <a href="https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues">Arch workaround</a>.

**Comment by Danny3** [comment]
Arch workaround worked for me, thanks
After the first command Steam started updating and disappeared without saying anything
I had to run the second command too to get it to start

**Comment by keizgon** [comment]
The Steam package in Ubuntu 15.10's software center does not work. Did you try downloading directly from Steam? That solved my issue.

**Comment by kisak-valve** [comment]
Closing as fixed in steam's 1.0.0.55 bootstrap runtime.
