### ISSUE TITLE
Big picture: Store is not working

### ISSUE THREAD

**Issue by alexhultman** [ValveSoftware/steam-for-linux#4095]
Ever since the new redesigned Big picture mode came along I get no entries in my store page. Only Videos shows up. All the other tabs are empty.

![screenshot from 2015-10-27 15-22-46](https://cloud.githubusercontent.com/assets/3397140/10760906/1a7d9ff0-7cbf-11e5-8536-08d209d70ade.png)

**Comment by alfred-valve** [comment]
This should be fixed if you opt into the Steam Client beta.
