### ISSUE TITLE
Sword coast legends lockup with open source Radeon drivers

### ISSUE THREAD

**Issue by bluescarni** [ValveSoftware/steam-for-linux#4097]
The game lockups either on startup or when loading a level. Full details are available here:

https://bugs.freedesktop.org/show_bug.cgi?id=92428

Both reporters are using the radeonsi open-source radeon driver.

**Comment by gdrewb-valve** [comment]
You'll want to report this to the developers also.

**Comment by h0ser81** [comment]
I've reported it to the game developers on both their forums and through their zendesk ticketing system and have received only a canned response through their ticketing system telling me to verify my steam cache and to report it on the forums.

**Comment by kisak-valve** [comment]
Hello @bluescarni, @h0ser81, are either of you still experiencing this issue on an up to date system?

It looks like the b.fd.o report fell into limbo.

**Comment by bluescarni** [comment]
Sorry haven't played the game since. I can try to re-install it over the weekend.

**Comment by kisak-valve** [comment]
Closing pending feedback.
