### ISSUE TITLE
Fedora 22 segfaulting

### ISSUE THREAD

**Issue by mwic** [ValveSoftware/steam-for-linux#4099]
So I bought a new video card to run steam games, then I installed fedora 22 to run steam games, then I installed the latest nvidia drivers to run steam games, then I went through this ridiculous 10-step process to install steam so that I could run steam games, and finally I got a steam package installed and tried to run it and i got this:

Running Steam on fedora 22 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/mcrouch/.local/share/Steam/steam.sh: line 756:  2831 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by kisak-valve** [comment]
Hello @mwic, are you still experiencing this issue on an up to date system? If you are, is any 32 bit opengl application like `glxinfo32` from 32 bit `glx-utils` working?

**Comment by mwic** [comment]
um, this was 3 and a half years ago, I don't actually have a recent test of the bug.

**Comment by kisak-valve** [comment]
Fedora 22 is past its end of life. Closing as obsolete.
