### ISSUE TITLE
Unable to run Steam on 64-bit Debian Jessie with Nvidia driver 352.55

### ISSUE THREAD

**Issue by divmgl** [ValveSoftware/steam-for-linux#4100]
Having an issue similar to #3979. 

```
$ steam
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1444853545)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
^C
$ nvidia-smi | grep NVIDIA-SMI
| NVIDIA-SMI 352.55     Driver Version: 352.55         | 
$ uname -r
3.16.0-4-amd64
```

Drivers are installed fine from what I can tell. `glxgears` working fine. Any ideas on how to fix this?

**Comment by divmgl** [comment]
I can confirm that rolling back to driver 340.65 works. If you need help rolling back, you need to do the following.

1. If you're going to be using `sudo`, ensure you are part of the `sudo`ers group.
```
$ su
# adduser <user> sudo # replace <user> with your username
# reboot # if necessary
```
2. Press <kbd>Ctrl+Alt+F1</kbd> to launch a separate session. Login.
3. Stop your window manager. In my case, it's Gnome 3.
```
$ sudo /etc/init.d/gdm3 stop
```
4. Remove your current Nvidia drivers.
```
$ sudo nvidia-uninstall
```
5. Install the Nvidia drivers that are part of the `non-free` source. You may need to add this to `/etc/apt/sources.list`.
```
sudo apt-get install libgl1-nvidia-glx:i386
```
6. Reboot.

**Comment by Nerun** [comment]
I have the same issue.
Debian 8.2 (Jessie) 64-bit + Driver NVidia 352.63 (NVIDIA-Linux-x86_64-352.63.run)
Installing steam from repository (sudo aptitude install steam) after adding multiarch.
I tried to add "libgl1-nvidia-glx:i386" but Debian insist to install nvidia-driver too, and they are incompatible together. aptitude ask to uninstall NVIDIA-Linux-x86_64-352.63.run then install nvidia-driver. But nvidia-driver doesn't work for me. Debian can't start X after installing nvidia-driver so i really need to install ".run" driver.
