### ISSUE TITLE
beta client: illegal instruction

### ISSUE THREAD

**Issue by lievendp** [ValveSoftware/steam-for-linux#4101]
while running beta client (because I was hoping this would maybe solve the issue that I cannot use a btrfs-on-ssd based library folder - which it didn't) all of a sudden (couple weeks ago now) the client stopped working.
It just wouldn't load.

here's the issue:

    [lieven@localhost ~]$ steam
    Running Steam on mageia 5 64-bit
    STEAM_RUNTIME is enabled automatically
    /home/lieven/.local/share/Steam/steam.sh: line 756:  9903 Illegal instruction     $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

I did manage to solve it by returning to the standard client instead of beta.
- removed the "beta" file from "package" folder in user homedir
- ran steam --reset
- started steam again logging in with account and starting from scratch

found the instructions for this [here] (https://steamcommunity.com/app/221410/discussions/2/490123727975601710/)

Is there a reason why beta cannot be used anymore?

some system info:

    [root@localhost ~]# cat /etc/issue
    Mageia release 5 (Official) for x86_64
    Kernel 4.1.8-desktop-1.mga5 on a 4-processor x86_64 / \l

    [root@localhost ~]# cat /etc/redhat-release 
    Mageia release 5 (Official) for x86_64
 
    [root@localhost ~]# uname -a
    Linux localhost 4.1.8-desktop-1.mga5 #1 SMP Sun Sep 20 12:39:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gdrewb-valve** [comment]
This should have been fixed a while back.  Try running steam --reset when you're in the beta state.

**Comment by lievendp** [comment]
I did a reset after opting out of beta by renaming the file. 
Now I opted in again to beta and restarted steam just fine without errors.
