### ISSUE TITLE
steam client fails to open existing and previously accessible library

### ISSUE THREAD

**Issue by lievendp** [ValveSoftware/steam-for-linux#4102]
After I installed my OS from scratch for a newer version, I cannot open one of my steam libraries anymore.

I know this is solved on ubuntu with a 3-version kernel.

Here's my OS information:

```
[root@localhost ~]# uname -a
Linux localhost 4.1.8-desktop-1.mga5 #1 SMP Sun Sep 20 12:39:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ~]# cat /etc/issue
Mageia release 5 (Official) for x86_64
Kernel 4.1.8-desktop-1.mga5 on a 4-processor x86_64 / \l
```

This is the mount where the steam library is located which I cannot open anymore:

```
/dev/sdc3 on /steam type btrfs (rw,relatime,ssd,space_cache)
```

This is the error message when I try to open this library:

![steam-ssd_btrfs-libfolder01](https://cloud.githubusercontent.com/assets/3162618/10863109/e6e552c6-7fc2-11e5-85b0-2a0383dcb9f0.png)

And I can see following error in the console when I tried to open the library:

```
sh: /steam/data//steamapps/.steam_exec_test.sh: No such file or directory
```

I have another library which can be used just fine:

```
/dev/mapper/vgSATA-lvSteam on /steamSATA type ext4 (rw,relatime,data=ordered)
```

**Comment by kisak-valve** [comment]
Hello @lievendp, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
