### ISSUE TITLE
Dust Elysian Tail crashes if dualshock3 plugged on boot

### ISSUE THREAD

**Issue by cforain** [ValveSoftware/steam-for-linux#4109]
I have successfully installed DS3 controller using hid_sony kernel driver. If I open the game with the DS3 paired, the game crashes with a window full with XNA debug messages. If I open the game with the DS3 unpaired, and then pair the DS3, everything works as expected.

**Comment by rmbleeker** [comment]
You should probably let Ethan Lee aka flibitijibibo know about this, he maintains the port for Dust: An Elysian Tail and the underlying FNA framework.

**Comment by cforain** [comment]
Do you know where can I contact him?

**Comment by flibitijibibo** [comment]
Someone sent me here!

Try the `fna-unstable` beta branch on Steam.

**Comment by kisak-valve** [comment]
Hello @cforain, are you still experiencing this issue on an up to date system?

**Comment by cforain** [comment]
@kisak-valve There has been a while, also I'm using DS4 now. If this helps, I can test it.

**Comment by kisak-valve** [comment]
Thanks for the feedback @cforain, I'm going to guess the DS3 and DS4 have subtlely different behavior, but if you're still having issues, it would be good to let @flibitijibibo know.

Closing as out-of-date and no longer testable.
