### ISSUE TITLE
[Left 4 Dead 2] Looping sound after recent game updates.

### ISSUE THREAD

**Issue by sizeofbool** [ValveSoftware/steam-for-linux#4113]
Somehow sound subsystem fails while I play the game and some looping sound is played *(as if contents or small part of sound buffer plays over and over again)*. It began to happen after recent game updates. (Current BuildID: 848523)

I can fix it without restarting the game, by selecting "Headphones" and then changing it back to "Speakers 5.1" in audio options menu.

I play with Analog 5.1 Headset (6 jacks) and use ALSA + PulseAudio.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0xb
    CPU Type:  0x0
    Speed:  2664 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 340.93
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1200
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18.66" x 11.65"  (21.97" diag)
                                            47.4cm x 29.6cm  (55.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: SigmaTel STAC9271D
    
Memory:
    RAM:  3897 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  234600 Mb
    Largest Free Hard Disk Block:  80990 Mb
    
Installed software:
    
Recent Failure Reports:
```
I will provide any other info on request.

**Comment by Tele42** [comment]
Potentially related to https://github.com/ValveSoftware/Counter-Strike-Global-Offensive/issues/310, does the game console give a simular message to the ```Error: Total static audio channels have been used: 96``` reported in 310?

**Comment by sizeofbool** [comment]
@Tele42 no. Nothing about audio or sound in console or logs.

Unless "channel.cc" is related to sound. This is from "/tmp/dumps/name_stdout.txt"
```
[1107/181656:WARNING:channel.cc(558)] Failed to send message to remove remote endpoint (local ID 2147483649, remote ID 3)
[1107/181656:WARNING:channel.cc(558)] Failed to send message to remove remote endpoint (local ID 2147483648, remote ID 2)
```

**Comment by sizeofbool** [comment]
Bug still present in BuildID: 853124.

**Comment by undeference** [comment]
snd_restart also works, but doing either that or changing speaker configuration in the sound menu prevents any voice chat from working—nothing received, nothing transmitted—and my voice_scale setting is capped to 1.0 (I have it at 1.5 so I can hear people over most effects)

Not sure if this is related, but it seems to not be saving my speaker settings, so every time I start, it sets it back to 5.1 rather than headphones, and I have to change that in the sound menu (then set my voice_scale again) before joining a game; if I do it in game, voice chat stops.

**Comment by buckwangs** [comment]
I'm having the same issue as undeference, I can't change 5.1 to headphones or 2 speakers and have it stick after a restart of the game. Also changing it in game causes me to lose my microphone in game. I'm here cause I am too experiencing crashing of game audio that loops until I quit and restart L4D2.

**Comment by undeference** [comment]
This still happens after the 10 December 2015 update

**Comment by dantob** [comment]
Same occasional stuck looping audio. I'm using SPDIF Optical Out, also using 5.1. This is the same "fix" Ive been using too..
"I can fix it without restarting the game, by selecting "Headphones" and then changing it back to "Speakers 5.1" in audio options menu."

I'll make sure to check out the console next time.

00:1f.3 Audio device: Intel Corporation Sunrise Point-H HD Audio (rev 31)

**Comment by sizeofbool** [comment]
Bug is still not fixed in game **BuildID: 902343**
I experience this issue at least once in every game.

As an additional workaround you can use key bind to fix this sound problem in game asap.
Put in your *"autoexec.cfg"* file this line:
```
bind "F5" "snd_restart;voice_scale 0.7"
```

**Comment by buckwangs** [comment]
I can do a snd_restart;voice_scale 0.7 but I'll lose the microphone. If I change from 5.1 speakers to anything at all, I lose the microphone and haven't found a way to get it back short of restarting the game. Playing the game without a mic kind of sucks :(

**Comment by undeference** [comment]
I'm noticing a trend here: lots of updates for Steam controller but no fixes for recently introduced bugs

**Comment by crazyjust** [comment]
I am also experiencing this problem with linux mint 17.2 cinnamon.

**Comment by gfaccin** [comment]
Having the same problem here with Gentoo Linux and Xonar 7.1 audio. By the way 7.1 sound does not work as it should, but 5.1 appears fine. 

The rest is as you guys reported: after ~30 min of game the sound enters a loop and stays that way until the map changes (multiplayer game). The set 5.1 -> headphones trick works to regain game sound, but I cannot hear other players speak or talk on the mic anymore.

This bug did not exist in the past, it came about recently as you guys pointed out. Still looking for a solution.

**Comment by davidw-valve** [comment]
We have just released an update which fixes this problem.

**Comment by hereblur** [comment]
Great to hear that it's fixed. 
It's was happened to me last night, will check again tonight.

**Comment by buckwangs** [comment]
I didn't get an update and checking for an update tells me I'm up to date (built jan 1st). I restarted steam and checked again, nothing. I switched to the beta which was built Jan 14th and I'm guessing this is it?

**Comment by Tele42** [comment]
Related to this, the game got an update yesterday, not the steam client (https://steamdb.info/app/550/history/).

**Comment by buckwangs** [comment]
I haven't played the game long enough yet to run into it. Let's hope it's over.

**Comment by dantob** [comment]
I've been able to play through multiple complete campaigns now, and this is yet to return. thanks!

**Comment by buckwangs** [comment]
I agree with @dantob. I haven't seen this either since the update. Thanks!
