### ISSUE TITLE
Streaming Settings Tab Description being outdated, please fix

### ISSUE THREAD

**Issue by kon14** [ValveSoftware/steam-for-linux#4117]
The text that's been displayed in Steam Desktop/BigPictureMode Streaming Settings is outdated and only mentions Windows as a valid streaming host. More specifically for english users:

"Stream gameplay from your Windows PC to other computers detected on your local network. To connect, simply log into this same Steam account on another local device."

[Here](http://i.imgur.com/TKcNpCN.png)'s a screenshot from BigPicture.

While translating the new string into multiple languages might not be a priority for you (even though SteamMachines are launching 2.5 days from now...) I'd suggest you at least omit the windows part in the english text and change the string to something like:

"Stream gameplay to other computers detected on your local network. To connect, simply log into this same Steam account on another local device."

Steam streaming now works on every platform supported by steam anyway.

**Comment by Mblackwell1024** [comment]
Can confirm the bad string is in both the regular and Big Picture settings panels.

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
