### ISSUE TITLE
Steam won't create a desktop shortcut on Kubuntu

### ISSUE THREAD

**Issue by Konstamokh** [ValveSoftware/steam-for-linux#4120]
Whenever I install a game on Kubuntu and check "Create desktop shortcut", it doesn't work. I'm not sure if this is Kubuntu specifically or Ubuntu in general.
Might be this is a bug with Kubuntu and not Steam.

**Comment by bjwest** [comment]
I'm going to ask a dumb question Konstamokh, but do you have your desktop set to folder view or default desktop?

**Comment by Konstamokh** [comment]
I had it indeed set to default desktop. Well, since I like the default desktop, could Steam somehow support that one? I really like the customization options I have with the default desktop that I don't have in folder view.
Maybe it's too much to ask for support of a specific distribution, I understand that.
