### ISSUE TITLE
No sound on Half-Life based games: Team Fortress 2, Fistful of Frags, Codename Cure

### ISSUE THREAD

**Issue by cyberalex4life** [ValveSoftware/steam-for-linux#4126]
On Manjaro Gnome Shell the output is similar for all:
[alex@alex-ntbk ~]$ env STEAM_RUNTIME=1 steam steam://rungameid/265630
Running Steam on manjarolinux 15.09 64-bit
STEAM_RUNTIME is enabled by the user
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)

(steam:17814): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:17814): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita/gtk-2.0/gtkrc:1163: error: unexpected identifier `direction', expected character`}'
Installing breakpad exception handler for appid(steam)/version(1447125378)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[1110/233814:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
[1110/233814:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20151109182310)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447093390)
[1110/233814:ERROR:main_delegate.cc(751)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20151109182310)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447125378)
Installing breakpad exception handler for appid(steamwebhelper)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Wireless receiver firmware /home/alex/.local/share/Steam/ubuntu12_32/../controller_base/d0ggle.bin loaded, version 1442256398.
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
FillInMachineIDInfo took a total of 0 milliseconds

*\* (steam:17814): WARNING **: Unknown device type 14

*\* (steam:17814): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type
Installing breakpad exception handler for appid(steam)/version(1447125378)

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'autoconnect-priority'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'autoconnect-priority'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'autoconnect-priority'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'hidden'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'autoconnect-priority'

*\* (steam:17814): WARNING **: Ignoring invalid property 'secondaries'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'route-data'

*\* (steam:17814): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442.37 KB
Installing breakpad exception handler for appid(steam)/version(1447125378)
local (potentially out of sync) copy of roaming config loaded - 2566 bytes.
roaming config store loaded successfully - 2566 bytes.
migrating temporary roaming config store
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1447125378)
Failed to init SteamVR because it isn't installed
ExecCommandLine: ""/home/alex/.local/share/Steam/ubuntu12_32/steam" "steam://rungameid/265630" "
ExecSteamURL: "steam://rungameid/265630"
Installing breakpad exception handler for appid(steam)/version(1447125378)
System startup time: 3.44 seconds
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Running Steam on manjarolinux 15.09 64-bit
STEAM_RUNTIME has been set by the user to: /home/alex/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(1447125378)
ExecCommandLine: "/home/alex/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 75: 256x256, total string texture memory is 704.51 KB
Game update: AppID 265630 "Fistful of Frags", ProcID 17956, IP 0.0.0.0:0
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 17972 != 17971, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
Installing breakpad exception handler for appid(gameoverlayui)/version(20151109182348)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Using Breakpad minidump system. Version: 0 AppID: 265630
Setting breakpad minidump AppID = 265630
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198078828792 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198078828792
Did not detect any valid joysticks.
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
OpenGL: GeForce 610M/PCIe/SSE2 4.5.0 NVIDIA 352.55 (4.5.0)
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_ARB_buffer_storage: AVAILABLE
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 2097152, Total Avail: 2097152, Current Avail: 2079396
GL_MAX_SAMPLES_EXT: 32
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3300 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
CShaderDeviceMgrBase::GetRecommendedConfigurationInfo: CPU speed: 3300 MHz, Processor: GenuineIntel
GlobalMemoryStatus: 4294967295
IDirect3DDevice9::Create: BackBufWidth: 1366, BackBufHeight: 768, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: DISABLED

 ##### swap interval = 0     swap limit = 1 #####
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Loaded program cache file "glshaders.cfg", total keyvalues: 3, total successfully linked: 3
Precache: Took 31 ms, Vertex 128, Pixel 9
ConVarRef mat_dxlevel doesn't point to an existing ConVar
server.so loaded for "Fistful of Frags"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
ExecSteamURL: "steam://open/games"
[1110/233826:ERROR:renderer_main.cc(200)] Running without renderer sandbox
Generating new string page texture 85: 128x256, total string texture memory is 835.58 KB
Generating new string page texture 86: 64x256, total string texture memory is 901.12 KB
Generating new string page texture 87: 32x256, total string texture memory is 933.89 KB
Generating new string page texture 88: 128x256, total string texture memory is 1.06 MB
Generating new string page texture 90: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 94: 2048x256, total string texture memory is 3.16 MB
Generating new string page texture 95: 256x256, total string texture memory is 3.42 MB
Generating new string page texture 96: 1024x256, total string texture memory is 4.47 MB
Generating new string page texture 116: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 118: 128x256, total string texture memory is 4.60 MB
Generating new string page texture 136: 24x256, total string texture memory is 4.63 MB
Generating new string page texture 139: 512x256, total string texture memory is 5.15 MB
Generating new string page texture 140: 64x256, total string texture memory is 458.75 KB
Installing breakpad exception handler for appid(steam)/version(1447125378)
/home/alex/.local/share/Steam/steamapps/common/Fistful of Frags/sdk/hl2.sh: line 67: 17974 Killed                  ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 265630 "Fistful of Frags", ProcID 17974 
ExecSteamURL: "steam://open/games"
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)
Installing breakpad exception handler for appid(steam)/version(1447125378)

The result is the same with or without nvidia optimus (bumblebeed) activated.

**Comment by cyberalex4life** [comment]
So, I took a look here: 
https://bbs.archlinux.org/viewtopic.php?id=157364

and found that editing launchers like this: 

bash -c "env STEAM_RUNTIME=1 SDL_AUDIODRIVER=alsa steam steam://rungameid/440"

will enable sound on these kind of games.
It's probably related to pulseaudio.

**Comment by ryanpcmcquen** [comment]
Also if you have a newer version of ALSA than steam ships with (I have 1.1.0), you can fix sound by running steam like this:

    LD_PRELOAD=/usr/lib/libasound.so.2 steam

**Comment by cyberalex4life** [comment]
Unfortunately this solution doesn't work either:

LD_PRELOAD=/usr/lib/libasound.so.2 steam 
ERROR: ld.so: object '/usr/lib/libasound.so.2' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

LD_PRELOAD=/usr/lib32/libasound.so.2 steam
ERROR: ld.so: object '/usr/lib32/libasound.so.2' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by ryanpcmcquen** [comment]
@cyberalex4life I got the same error, but guess what? Sound worked. Did you actually test that?

**Comment by cyberalex4life** [comment]
I tested, yes.

**Comment by cyberalex4life** [comment]
I have modified /etc/pulse/daemon.conf. I'm posting the content, just in case:
```
; daemonize = no
; fail = yes
allow-module-loading = yes
; allow-exit = yes
; use-pid-file = yes
; system-instance = no
; local-server-type = user
; enable-shm = yes
; shm-size-bytes = 0 # setting this 0 will use the system-default, usually 64 MiB
; lock-memory = no
; cpu-limit = no

high-priority = yes
nice-level = -13

realtime-scheduling = yes
realtime-priority = 5

exit-idle-time = 20
scache-idle-time = 20

; dl-search-path = (depends on architecture)

load-default-script-file = yes
default-script-file = /etc/pulse/default.pa

; log-target = auto
; log-level = notice
; log-meta = no
; log-time = no
; log-backtrace = 0

; resample-method = speex-float-1
enable-remixing = yes
enable-lfe-remixing = no
; lfe-crossover-freq = 120

flat-volumes=no
; flat-volumes = yes

; rlimit-fsize = -1
; rlimit-data = -1
; rlimit-stack = -1
; rlimit-core = -1
; rlimit-as = -1
; rlimit-rss = -1
; rlimit-nproc = -1
; rlimit-nofile = 256
; rlimit-memlock = -1
; rlimit-locks = -1
; rlimit-sigpending = -1
; rlimit-msgqueue = -1
; rlimit-nice = 31
; rlimit-rtprio = 9
; rlimit-rttime = 200000

default-sample-format = s32le
default-sample-rate = 96000
alternate-sample-rate = 96000
; default-sample-channels = 2
; default-channel-map = front-left,front-right

default-fragments = 2
default-fragment-size-msec = 2

```

**Comment by ryanpcmcquen** [comment]
Ah, well I don't have pulseaudio here and everything is working.  ;-)

**Comment by cyberalex4life** [comment]
lol

**Comment by kisak-valve** [comment]
Hello @cyberalex4life, are you still experiencing this issue on an up to date system?

**Comment by alexandrupetrini** [comment]
Hello @kisak-valve, I've moved from Manjaro or Arch based distro's quite a long ago, so, like in Mission Impossible, can't confirm or deny :). I am on Ubuntu 18.04, and things look OK here from this perspective.

**Comment by kisak-valve** [comment]
Thanks for the feedback @alexandrupetrini. Since this issue report was active, the way Steam handles the Steam runtime has changed to prefer system libraries over the runtime, which could have mitigated the most common scenario for this issue.

If anyone is still experiencing this issue with a Source 1 based game, please use the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.
