### ISSUE TITLE
Big Picture Mode crashes a lot with steam controller

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4129]
I am finding that SBP is freezing rather often when I have my Steam Controller attached to it. Proving to be extremely annoying, and it's starting to put a downer on the experience.

I have put my steam log file here for reference: https://gist.github.com/liamdawe/3a91ec9911f0066bdca5

Crash dmp is here https://www.dropbox.com/s/0ir6lxyzocgo2u6/assert_20151111131308_55.dmp?dl=0

This happens on both Stable and Beta client.

**Comment by Tele42** [comment]
Crash reason:  DUMP_REQUESTED
Crash is deep in crashhandler.so.

**Comment by liamdawe** [comment]
I don't know if it's useful at all, but I just caught big picture dying again. Seems to happen most often for me when quitting a game. Caught this in terminal:

Timed out waiting for mutex in PutInternal()
Timed out waiting for mutex in PutInternal()
Timed out waiting for mutex in PutInternal()
Timed out waiting for mutex in PutInternal()
Timed out waiting for mutex in PutInternal()
threadtools.cpp (1375) : Assertion Failed: Thread synchronization object is unuseable
Assert( Assertion Failed: Thread synchronization object is unuseable ):threadtools.cpp:1375

Installing breakpad exception handler for appid(steam)/version(1447189674)
assert_20151111224438_244.dmp[8601]: Uploading dump (out-of-process)
/tmp/dumps/assert_20151111224438_244.dmp
assert_20151111224438_244.dmp[8601]: Finished uploading minidump (out-of-process): success = yes
assert_20151111224438_244.dmp[8601]: response: CrashID=bp-0e4145ad-1138-4fab-a822-44c2f2151111
assert_20151111224438_244.dmp[8601]: file ''/tmp/dumps/assert_20151111224438_244.dmp'', upload yes: ''CrashID=bp-0e4145ad-1138-4fab-a822-44c2f2151111''

It was spamming the line "Timed out waiting for mutex in PutInternal()" for quite some time before reaching that end.

**Comment by liamdawe** [comment]
Also, here's the dump file for the above: https://www.dropbox.com/s/3gyb2r7iasrmoxi/assert_20151111224438_244.dmp?dl=0

**Comment by liamdawe** [comment]
This looks related: http://steamcommunity.com/groups/SteamClientBeta/discussions/0/496881136900608371/?tscn=1447281380

**Comment by LiamDawe** [comment]
Hasn't been an issue for a long time, closing.
