### ISSUE TITLE
Steam Controller sends wrong input for Keypad/Numpad

### ISSUE THREAD

**Issue by Mblackwell1024** [ValveSoftware/steam-for-linux#4131]
When trying to assign buttons like KP8, KP5, etc the Steam Controller has an off-by-one issue.

In the game tested (Dying Light) I attempted to bind my normal keypad mappings for movement (8456) but they failed to function. After some normal troubleshooting going in-game to Key Bindings and binding whatever the Steam Controller button reported revealed that (for example) KP8 was triggering KP7, KP6 was triggering KP5, etc.

This does not happen with the regular section of the keyboard, so a binding of WASD will trigger correctly.

**Comment by Mblackwell1024** [comment]
This has improved, but the input for Keypad . when I did some testing (for me normally bound to CROUCH). So far other keys seem to function.

**Comment by kisak-valve** [comment]
Hello @Mblackwell1024, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
