### ISSUE TITLE
Steam does not notify about new messages

### ISSUE THREAD

**Issue by Yanpas** [ValveSoftware/steam-for-linux#4134]
High, I'm using XFCE. When incoming message comes to me I do not hear any sound and window does not pop up. Instead of it minimized chat window appears on the panel.

How do I run steam: sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U
I use this option because without it it is impossible to close Steam window on XFCE, it only minimizes
Sysinfo https://gist.github.com/Yanpas/99842e1885b36b20d2c8

**Comment by kisak-valve** [comment]
Hello @Yanpas, are you still experiencing this issue on an up to date system?

**Comment by Yanpas** [comment]
I don't use steam on Linux that frequent, so closing.
