### ISSUE TITLE
Ubuntu 15.10 - very high CPU usage (Insurgency)

### ISSUE THREAD

**Issue by kaniawave** [ValveSoftware/steam-for-linux#4136]
Hi all...
The problem I encountered is that on 14.04 LTS the game Insurgency was running slow, with kind of low fps, but stable. Now after fresh system reinstall to 15.10 I have much better performance but I have a problem, where a game goes smoothly and fine for couple of minutes and cpu usage is around 40 or less % and then it goes sky rocket to 100 % on all cores and everything lags (fps drops to few fps, sound lags etc.)  for about 15 seconds. The problem occurs every 4 minutes or so which makes gaming a bit impossible. What do you think could be a problem? Overheating? Hardware or drivers?

I want to point out again: on 14.04 the game was running less efficient but without lags. The 15.10  is a fresh installation. Steam and Insurgency are installed fresh. 

I'm running Lenovo Think Pad E420s:
Intel® Core™ i3-2310M processor (dual-core, 2.10GHz, 3MB Cache) 
with integrated Intel HD Graphics 3000

Greets

**Comment by Tele42** [comment]
@kaniawave since you suspect high temps are involved, get lm_sensors setup and monitor the temps yourself, ```watch sensors``` after ```sudo sensors-detect``` in a terminal help you get started.

**Comment by kaniawave** [comment]
@Tele42 Yeah, I did what you wrote. The temperature is high but still away from critical. But I'm quite sure now that the drops are connected to the CPUs working on lower frequencies. Also the fan is not working as fast as on 14.04 so it means that 15.10 keeps the fan slower and CPUs colder and cuts them down earlier? I cant's see any other explanation. 

If anyone has any other idea I would be very happy to read it!

**Comment by not83** [comment]
Since this is an issue with the game and not the steam linux client, I'd suggest that this is the incorrect place to report this. Try closing this issue, and sending this bug report to the game devs, that way the right eyes will be looking at it
