### ISSUE TITLE
Continuous crashes Ubuntu 15.10

### ISSUE THREAD

**Issue by loisgomez** [ValveSoftware/steam-for-linux#4142]
I am suffering from an unexpected amount of crashes on the steam client since last updates to the steam client beta. 

I have uploaded all the dump crashes to dropbox.

https://www.dropbox.com/sh/b0mbpgc42vi0zzt/AACIb-kXV4zYRdRdzCp0nogVa?dl=0

**Comment by jmauss** [comment]
Having the exact same issue on 14.04.3 (but with the non-beta client). Constant crashes, mostly while downloading games.

**Comment by kisak-valve** [comment]
Hello @loisgomez, if you're still experiencing this issue on an up to date system, please open a new issue report. Closing as this issue report is no longer actionable.
