### ISSUE TITLE
Steam terminal output

### ISSUE THREAD

**Issue by loisgomez** [ValveSoftware/steam-for-linux#4143]
Steam used to give much more information when ran throught the terminal. I was able to fix quite a few games not launching due to missing libraries. Nowadays the steam client just spams these like hell: 

Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 15
Refresh rate: 15

No usable info when a game fails to launch.

**Comment by sizeofbool** [comment]
@bertogs It is not required to launch Steam Client from console to get logs. These logs are saved automatically by default here: 
```
/tmp/dumps/yourusername_stdout.txt
```

**Comment by bertogs** [comment]
Ive reinstalled steam from the .deb package on steam website and now im able to see logs in the terminal again... I was installing it directly from Ubuntu software center before and maybe something went wrong...

**Comment by Tele42** [comment]
If steam is already running when you try to run steam from a terminal, then you will not see stdout from games in that terminal.

**Comment by bertogs** [comment]
Think first time on Ubuntu i  just did sudo apt-get install steam but something must be wrong with the steam package with Ubuntu cos i was missing those stdout debug info... installing from the deb package from steam website fixed it.

**Comment by kisak-valve** [comment]
Hello @loisgomez, Ubuntu's package for Steam (inherited from Debian) redirects stdout to `~/.steam/error.log`. If you still want to pursue this issue, then this needs to be reported to the distro's package maintainer(s) for Steam.
