### ISSUE TITLE
Tutorial: How to use SteamCMD on Debian Jessie with enabled grsec (MPROTECT)

### ISSUE THREAD

**Issue by AlexanderCurl** [ValveSoftware/steam-for-linux#4146]
Hi guys!

I has been decided how to run steamcmd on a grsec MPROTECT enabled kernel. I can show everybody, because takes for me 2-3 weeks, when I successfully started :+1:

It just a few steps, i haven't got enough time to add the all of the commands and everything, if somebody can do, do it :)

First of all, need to enable the multilib feature:

dpkg --add-architecture:i386
apt-get update && apt-get upgrade

Then, if the grsec kernel running alredy, need to remount your root filesystem with user_xattr option.
So edit your /etc/fstab and add the user_xattr option your mount options.

After you have to install the attr package.
apt-get install attr

Then reboot the server.

When the server successfully rebooted download the steamcmd sources and unpack it.
After, when you unpacked need to set the pax flags, like this, the whole directory:

setfattr -n user.pax.flags -v pemrs /where/is/unpacked/steamcmd/*

Now the steamcmd could starts, and doesn't crash after the update porcedure.

Don't forget, you have to apply these flags for the downloaded gameservers as well!
For me, I successfully created a CS:GO Server:
setfattr -n user.pax.flags -v pemrs /where/is/csgo/server/*

It worked for me, could be works every Linux distributions as well!
I hope i helped so much people in the world! :)

**Comment by a-detiste** [comment]
Adding extra Debian-specifix information to the `steamcmd` package is always welcome.
https://packages.qa.debian.org/s/steamcmd.html

Can/should this be translated in a post-inst script ?

The self-updating feature makes this thing really hard to package.

**Comment by kisak-valve** [comment]
Hello @AlexanderCurl, this issue report appears to be informational and not an actionable issue. Closing.
