### ISSUE TITLE
Segfault when attempting to create a game backup at non-default location

### ISSUE THREAD

**Issue by silviucc** [ValveSoftware/steam-for-linux#4151]
I can reproduce this every time I want to backup a game to a separate drive. By default Steam wants to backup the game somewhere to `$HOME/.local/share/Steam/Backups` but if I choose another directory on different drive, it segfaults. I do have read/write permission to it. It's where my library of Steam games is located.

This is what dmesg shows:

```
steam[5358]: segfault at 43a07ffc ip 00000000f7328c86 sp 00000000ffefb7f0 error 4 in libc-2.19.so[f72b2000+1a8000]
```

System info in attached file.
[steam_system_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/41014/steam_system_info.txt)

Crash does not happen if I use nvidia driver 355.11 instead of 358.16. So this is probably related to issue #4144

**Comment by xenithorb** [comment]
Also seeing this on Fedora 23 w/ nvidia 358

**Comment by xenithorb** [comment]
Temporary fix (since downgrading to 355 can be difficult in Fedora) is to downgrade to the rpmfusion available stable driver NVIDIA 340.96 `dnf install akmod-nvidia-340xx xorg-x11-drv-nvidia-340xx-libs.i686` after `dnf remove akmod-nvidia "kmod-nvidia*"`

**Comment by kisak-valve** [comment]
Hello @silviucc, @xenithorb, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as video driver quality from 2015 is no longer relevant.
