### ISSUE TITLE
Steam is "grinding" my HDD while installing Terraria

### ISSUE THREAD

**Issue by silviucc** [ValveSoftware/steam-for-linux#4153]
While installing Terraria I notice that disk usage as showed by Steam is extremely low all while the HDD is active and extremely noisy. The install takes a long time too despite Terraria being about 250MB in size. Even after the download is complete Steam still grinds the HDD while the transfer rate remains very low.

![steam_terraria_install_low_transfer_rate](https://cloud.githubusercontent.com/assets/3889481/11323233/096661e6-9116-11e5-94e3-ef29683622d8.png)

I copied a bunch of big files  from another drive to that one and that task completed very fast.

![hdd_transfer_rate](https://cloud.githubusercontent.com/assets/3889481/11323256/a3791d8c-9116-11e5-9c86-b970fa9d9505.png)

I saw the same thing happen while attempting to restore Terraria from a backup. An estimated time of 2 hours to restore 250MB of game data.

What the heck is Steam doing?!

**Comment by Tele42** [comment]
This is an mildly extreme example, Terraria is ~250MB, but that is across 9300 files, which is what steam is having a harder time processing.

**Comment by kisak-valve** [comment]
Hello @silviucc, are you still experiencing this issue on an up to date system?

**Comment by silviucc** [comment]
Hi.

I don't think this bug is relevant anymore. Terraria itself went through changes and my system now is more powerful and uses an nvme SSD. I installed Terraria with no issues and very fast.
