### ISSUE TITLE
Steam deleted all games after a --reset

### ISSUE THREAD

**Issue by rmbleeker** [ValveSoftware/steam-for-linux#4154]
**OS**: Ubuntu 14.04 LTS
**kernel**: 3.19.0-33-generic
**WM**: Unity 7.2.6
**System**: Intel Core2 Duo E8500, 8GB RAM
**GPU**: nVidia GTX 560Ti 2GB
**Graphics driver**: 358.16-0ubuntu0~gpu14.04.1 from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

I was having some issues with Steam (random crashes) so I did a `steam -- reset` on the command line as I have done many times before. Only this time it appears Steam has deleted all games with it, which it isn't supposed to do. There is no `~/.local/share/Steam/steamapps/.save` folder and disk usage seems to support the data being gone (from almost full to almost empty). Luckely I have a fast internet connection so redownloading isn't a real issue, but I wanted to report this nonetheless. Please ask for any additional info and I will try to provide.

**Comment by rmbleeker** [comment]
Additional note: it seems Steam only deleted the games in `.local/share/Steam/steamapps/common`, not the one game in my other Steam library in `/opt/games/Steam`

**Comment by sizeofbool** [comment]
@rmbleeker have you installed Steam Client from Ubuntu repo or official package from Valve repo?

**Comment by rmbleeker** [comment]
The official package from the Valve repo at http://repo.steampowered.com/steam/

**Comment by Plagman** [comment]
Thanks, the steam.sh reset script wasn't updated to backup the new lowercase steamapps location. Fixed.

**Comment by not83** [comment]
Awesome stuff. If this bug no longer exists then could you please close this issue OP. Thanks

**Comment by rmbleeker** [comment]
I doubt the change has been pushed to the steam client yet, so I can't really confirm it yet now can I? :-)

**Comment by not83** [comment]
The package on the steam site did get a change recently so yeah try it out

**Comment by gourdcaptain** [comment]
This still happened to me last night in the middle of a giant mess with trying to get Steam games to work with my radeon drivers (crashing at launch with the runtime enabled, games crashing at game launch with it disabled and then Steam refusing to close without SIGKILL-ing them). I will not be able to render further assistance for a while, as the deletion of approximately four hours worth of downloads over a slow ADSL connection caused me to rage uninstall Steam.

**Comment by rmbleeker** [comment]
I just tested this and it seems to be fixed. My lower-case "steamapps" folder was not deleted after a --reset.
