### ISSUE TITLE
Unable to stream from Mac host to SteamOS client

### ISSUE THREAD

**Issue by bstascavage** [ValveSoftware/steam-for-linux#4155]
Mac OSX: 10.10.5, 2014's MBP model
SteamOS: Brewmaster 49

When I launch a streaming game on the SteamOS machine (which is a fresh install), BPM and the game launch on my Mac, but the Linux Steam client ends up timing out.  Sometimes it says "User intervention required" (which isn't true, since nothing is prompted on the Mac) and sometimes it just said "Unable to launch Stream".  Both the Mac host and SteamOS client are running the latest Steam client beta.

Not really sure if this is Steam for Linux issue or a Steam for Mac issue, so I figured I'd open it here.  I don't have any other host computers to check with, sadly.

**Comment by kisak-valve** [comment]
Hello @bstascavage, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
