### ISSUE TITLE
Steam crashes after couple of seconds

### ISSUE THREAD

**Issue by omerfirmak** [ValveSoftware/steam-for-linux#4157]
I am running Arch Linux x86_64 and Nvidia hardware with latest drivers. (358.16-2.1)

Here is the stdout of steam.
https://www.dropbox.com/s/cap74nrglaxeryb/steamlog.txt?dl=0

And the dump file mention at the end of that log.
https://www.dropbox.com/s/3ajfasx7t5o2m0t/assert_20151125225451_1.dmp?dl=0

**Comment by omerfirmak** [comment]
Downgrading nvidia driver to 355.11 and xorg-server to 1.17.4 seems to solve the issue

**Comment by frostworx** [comment]
this bug has some duplicates like
#4151 
 #4073
(more?)
downgrading nvidia-drivers is no option for me, so I'll wait and live with the crashes

**Comment by Kiibakun** [comment]
This is affecting me too. Using Nvidia 358.16 on Ubuntu GNOME 15.10.

**Comment by ButchDeLoria** [comment]
I had a duplicate a while back while using the nVidia beta drivers from the AUR on Arch, and it was at 358 and still is.
#4079

**Comment by Hirato** [comment]
For me it seems to be triggered by the notifications collapsing uninterrupted.
The timing's just too convenient, and I've not run into any crashes after disabling those under the "Friends" tab in options.

**Comment by kisak-valve** [comment]
Hello is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as video driver quality from 2015 is no longer relevant.
