### ISSUE TITLE
Continous Crashing On Chat

### ISSUE THREAD

**Issue by bakgwailo** [ValveSoftware/steam-for-linux#4159]
Steam has crashed ~4 times on me in the last 15 minutes. I have basically been just chatting with a friend. I have attached the core dump (renamed to .txt due to GitHub not liking .dmp files). I am running Arch Linux with Testing Enabled, and the Plasma 5.5 beta/Applications 5.12 beta. I have the latest NVIDIA drivers (358.16). I have an FX-8350 with a 560ti. Please let me know if there is anything else I can provide.

[crash_20151126232508_1.txt](https://github.com/ValveSoftware/steam-for-linux/files/45416/crash_20151126232508_1.txt)

**Comment by Tele42** [comment]
There have been several reports of instability with nvidia 358, but not 355, please see if this is true for you as well.

**Comment by SunDwarf** [comment]
+1, had issues with 358 but not 355.

**Comment by OrdinaryMagician** [comment]
Arch with same GPU here and same drivers, it's also crashing. I don't use testing.

It's really annoying when so many people want to chat with you.

**Comment by Sonicadvance1** [comment]
This issue also effects me, I'm not using testing.
I run a Core i7-4930MX with a Quadro K2100m.
I'm using the 358.09 Nvidia driver.

**Comment by mlandalv** [comment]
Same problem with me after upgrade to 358. Both the "Recent Failure Reports" below are related to it, and occurred when chatting.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.43" x 12.76"  (24.06" diag)
                                            51.9cm x 32.4cm  (61.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  16019 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  168880 Mb
    Largest Free Hard Disk Block:  70239 Mb
    
Installed software:
    
Recent Failure Reports:
    Sun Dec  6 12:39:56 2015 GMT: file ''/tmp/dumps/assert_20151206123521_1.dmp'', upload yes: ''CrashID=bp-ff4bedfe-0470-4de5-b812-9fe432151206''
    Sun Dec  6 12:41:13 2015 GMT: file ''/tmp/dumps/assert_20151206134003_1.dmp'', upload yes: ''CrashID=bp-a39da8ab-25d4-4373-a911-5dee62151206''
```

**Comment by tuutti** [comment]
Happening to me too with nvidia 358.16-2.1.

**Comment by bandroidx** [comment]
just figured id add that its also doing the same thing for me, 358 drivers, arch, beta steam.

**Comment by bandroidx** [comment]
i pray this is fixed soon, its driving me mad.

**Comment by Hirato** [comment]
If any of you want a workaround for the interim.
1. Open options
2. go to the friends tab
3. disable all 3 of the 'Show Notification' settings there.

I've yet to have another crash after doing that several days ago.
Just goes to show that steam should really be using libnotify for these things.

**Comment by bandroidx** [comment]
Hirato, thanks but that doesnt work for me.  It commonly crashes for me when I am in the middle of typing a message so I dont think its notification related alone.

**Comment by Plagman** [comment]
There's a known issue with the 358.xx driver series that NVIDIA has fixed, but the fix won't be until the next driver release series; it's recommended that you downgrade to 355.x in the interim.

**Comment by OrdinaryMagician** [comment]
Updated to 361.18, notifications do not crash, but incoming chat windows cause a segfault.
`steam[3460]: segfault at 0 ip 00000000ef966b49 sp 00000000ffa30230 error 4 in vgui2_s.so[ef90e000+f8000]`
