### ISSUE TITLE
Killing Floor Perks and Mutators

### ISSUE THREAD

**Issue by Tele42** [ValveSoftware/steam-for-linux#416]
Killing Floor is checking the wrong files when mutators are used on multiplayer servers. Instead of using the cached files from the server, the local version is checked in order to allow perks to be saved. As a result, experience is accumulated throughout a match, but is lost on map change or disconnecting from the server. This behavior is predictable and if the linux client has all the mutators that the server is using, then the client works as expected.

**Comment by linuxgruven** [comment]
I have a fix just use sam....works for me...if they cant fix there crap deal...I got tired of re-perking...have over 1000 hours as a lvl 2 sharp...screw them...I think its more of a steam issue...it is a "perk" thing...I should not have to use "quick" fixes/scripts for devs lack of coding knowledge...just saying.
