### ISSUE TITLE
[DoD:S][Linux] No sound after ALSA upgrade

### ISSUE THREAD

**Issue by ikokostya** [ValveSoftware/steam-for-linux#4160]
After upgrading `ALSA` library

```
[2015-11-26 21:18] [ALPM] upgraded alsa-lib (1.0.29-1 -> 1.1.0-1)
[2015-11-26 21:18] [ALPM] upgraded alsa-tools (1.0.29-1 -> 1.1.0-1)
[2015-11-26 21:18] [ALPM] upgraded alsa-utils (1.0.29-2 -> 1.1.0-1)
```
sound in `Day Of Defeat Source` game is gone.
In another applications (e.g. audio/video players) sound works.

* [System Information](https://gist.github.com/ikokostya/5181528)
* [Steam client log](https://gist.github.com/ikokostya/fc9db05dca7511acfabd) of next steps:
  1. Run steam client
  2. Run `Day Of Defeat Source` game
  3. Exit from game
  4. Exit from steam client

**Comment by Tele42** [comment]
Duplicate of #4139.

**Comment by ikokostya** [comment]
@Tele42 thanks
