### ISSUE TITLE
Voice settings not saved unless 'Use for voice output too' is checked

### ISSUE THREAD

**Issue by bstascavage** [ValveSoftware/steam-for-linux#4164]
When setting up a microphone, if 'Use for voice output too' is not checked, the 'Voice recording device' will immediately default back to 'Built-in Audio'.  It will only save the microphone settings if 'Use for voice output too' is checked.

**Comment by kisak-valve** [comment]
Hello @bstascavage, Steam's voice chat has been overhauled since this issue report. If you're still experiencing this issue on an up to date system, please open a new issue report.
