### ISSUE TITLE
Would be great if the overlay could (optionally) show temperatures

### ISSUE THREAD

**Issue by frioux** [ValveSoftware/steam-for-linux#4167]
Given that a number of people are/will be building their own steam machines, it would be pretty nice to be able to have support for looking at the temperature of the machine from within the overlay.  Maybe not a huge deal, but if I see that my system is way hot maybe I'll add extra ventilation / cooling.

**Comment by sizeofbool** [comment]
You can get temperatures and any other info by simple script, send it to local http server and view it via Steam In-Game Overlay web browser.
This way you can have any and all information you want.

**Comment by frioux** [comment]
Sure, but do you really expect all other users to be engineers?

-- 
sent from a rotary phone, pardon my brevity

**Comment by sizeofbool** [comment]
This is not rocket science. And if one build his own PC\Steam Machine and use Linux, then this should not be too hard for him. In fact, I will create something like this on github for myself.
Its just my opinion and this is not social network so I won't answer any further.
