### ISSUE TITLE
play and configure scripts for Mound and Blade Warband do not set LD_LIBRARY_PATH appropriately

### ISSUE THREAD

**Issue by ohcfe** [ValveSoftware/steam-for-linux#4168]
On a fresh install of mount and blade Warband, clicking "Play"  or "configure" does not start anything
using steam API v 017 built Nov 9 2015 .

If I open-up a terminal, and make my LD_LIBRARY_PATH:

``` bash
mark@sparky:~/.steam/root/steamapps/common/MountBlade Warband$ echo $LD_LIBRARY_PATH
/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/mark/.steam/root/steamapps/common/MountBlade Warband:/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu
```

the mb_warband_linux executable will start the game, and it runs.

Modifying `mb_warband.sh` to set the above LD_LIBRARY_PATH I have made a version of mb_warband.sh which allows me to run the game on my system from the terminal:

``` bash
#!/bin/sh

#PROGRAM_DIRECTORY="`dirname "$0"`"
#export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY"
PROGRAM_DIRECTORY="/home/mark/.steam/root/steamapps/common/MountBlade Warband"
export LD_LIBRARY_PATH="/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/mark/.steam/root/steamapps/common/MountBlade Warband:/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu"
cd "$PROGRAM_DIRECTORY"
pwd
"$PROGRAM_DIRECTORY/mb_warband_linux" "$@"
```

However, I still can-not run the game by clicking "play" in the STEAM UI.

How can I get the game to launch by clicking "play" in STEAM? 
the "Configure" option also does not work, although I haven't put any effort into troubleshooting it yet.

**Comment by gdrewb-valve** [comment]
You'll want to report this to the game developers also.

**Comment by ohcfe** [comment]
Here's what I needed to do to make mbw_config.sh work on my system:
```bash
cd ~/.steam/root/ubuntu12_32
ln -sv  libaudio.so libaudio.so.2
```
Replacing mbw_config.sh with the following made it work on my system:
```bash
#!/bin/sh

PROGRAM_DIRECTORY="`dirname "$0"`"
#export LD_LIBRARY_PATH="$PROGRAM_DIRECTORY"
export LD_LIBRARY_PATH="/home/mark/.steam/root/steamapps/common/MountBlade Warband:/home/mark/.steam/root/ubuntu12_32:/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/mark/.steam/root/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu"

"$PROGRAM_DIRECTORY/mbw_config_linux" "$@"
```

If anyone is curious how I managed to come up with what to put in `LD_LIBRARY_PATH`, the trick is to add `ldd mbw_config_linux` to the script after the `export LD_LIBRARY_PATH=...` line, `ldd` will show you all of the libraries that the executable is linked against, and (if it's not working) some of them will say `not found`.  Fortunately steam is a self-contained distribution which (should) have all the required libraries available somewhere in the `~/.steam/` directory structure, to find the exact folder to add to `LD_LIBRARY_PATH`
```bash
cd ~/.steam
find -L |  grep -i the_lib_you_want
```
Likely you'll find something that matches exactly what you need, sometimes you'll need to fudge it a bit like I did for  `libaudio.so.2` in this case. `mbw_config_linux` wanted `libaudio.so.2` but I could only find `libaudio.so`, this is solved by making a symbolic link from one to the other.

**Comment by ohcfe** [comment]
@gdrewb-valve I put in a ticket at: https://www.taleworlds.com/en/Home/Support

the ticket-id is 492520

I gave them a link to here so hopefully they will close this issue when they resolve it.

**Comment by Dinsmoor** [comment]
Let's get an update on this issue, and if it's resolved or not. Since last update just over a year ago.

**Comment by profesorfalken** [comment]
The configuration window does not start, still today. 

I had bought the Napoleonic DLC but I cannot choose it without modifying the script or adding symbolic links. I have asked a refund.

**Comment by kisak-valve** [comment]
Hello, is this issue still happening on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
