### ISSUE TITLE
What libSDL2 doing in "$STEAMROOT/$PLATFORM/"?

### ISSUE THREAD

**Issue by dyrverE** [ValveSoftware/steam-for-linux#4169]
Merely questioning if "$STEAMROOT/$PLATFORM/" is even the right place for this particular library during install since I saw it listed among packages in steam_runtime already, it also probably exist in most distributions at this point as well, sooo?!

Basically the bundled library seems to be a core cause behind a lot of crashes during initial launch of Steam on my system (need relaunching ten times or more), seems to affect all mine and other peoples **Nvidia-binary** installs while with **STEAM_RUNTIME=0** and who knows what else issues occur due to this.
Not sure about Radeon since all those in my possession run the FOSS driver and I'm not messing with those headless+production systems.

Now, what I would like to know; would there be a better way to force steam **NOT** to download/extract this or any other so chosen library into the ubuntu12_32 directory to do some further tests than to merely force it to use system-libraries by the often times ugly _LD_PRELOADs_?

I would also like to add; If anyone would question why I would disable steam_runtime, answer is easy. I already have a perfectly functional package manager with a second frontend capable of cross-distro interactions, I don't need one from Valve.
If you do need specific libraries, rather get involved cooperating with the _PackageKit+AppStream_ developers instead, just don't make them a hard-dependency.
Cheers!

**Comment by Tele42** [comment]
The most likely answer for this is that valve is shipping a git version of libsdl2 (newer than 2.0.3) to address specific issues they encountered and libsdl2 has not done a point release for quite a while. Packages in the steam runtime appear to be sticking as close to their upstream origins as possible.

**Comment by dyrverE** [comment]
Ah thanks. But could anyone adress my other question about overriding /ubuntu12_32 libraries for further testing? I'd just like to override some files in there, symlinks and deletions just get overwritten. Haxing the shellscript does not seem to be enough and I might be missing something simple.

**Comment by windo** [comment]
Specific libraries can be overridden by LD_PRELOAD, ex:

$ DEBUGGER=gdb LD_PRELOAD=/home/siim/projects/SDL/build/libSDL2-2.0.so steam

**Comment by kisak-valve** [comment]
Hello @dyrverE, are you still experiencing the crashes mentioned in your opening post?

**Comment by kisak-valve** [comment]
Closing pending feedback.
