### ISSUE TITLE
Opening Steam overlay causes input hang with certain games

### ISSUE THREAD

**Issue by Basaltq** [ValveSoftware/steam-for-linux#4171]
I can open overlay once, close it and after that the game and the whole DE stops listening to my input. Only way out is to change to tty1 and kill the game. This happens both with BPM and desktop mode. If I'm using Steam Controller,  I can still open and close the overlay but nothing else.

This happens with Zen Bound 2, Psychonauts, Pier Solar and the Great Architects. Probably others too.

I've repeated this with two hardware setups, both using latest beta client (One using NVIDIA 358.16, Linux Mint Cinnamon 17.3, the other one uses Intel mesa drivers with Ubuntu 15.04), ruling out hardware issue.

I would assume this is caused by the way these games handle full screen, using direct rendering or grapping X session to themselves(?) instead of using borderless full screen.

**Comment by megatog615** [comment]
I can confirm this issue on Debian as well, x86_64. This occurs with Awesomenauts and other games(such as non-steam game GZDoom), but only if it's fullscreen.

**Comment by bartvanheukelom** [comment]
Hi, I'm Awesomenauts' new Linux developer. I'm looking into this issue, but it doesn't seem like we can do anything about it, other than switching to borderless window full screen, which I can't guarantee is feasible at the moment. If this issue could be fixed from the Steam side, that'd be great.

**Comment by Tele42** [comment]
@Basaltq I'm a little curious if you have cinnamon set to unredirect fullscreen windows, if so does turning that setting off change the behavior?

**Comment by bartvanheukelom** [comment]
I can confirm that this issue only occurs in exclusive fullscreen mode. Defying expectations, we've managed to get borderless window support in Awesomenauts, and this issue no longer occurs in that mode.

**Comment by Plagman** [comment]
Thanks for your patience and working around it... is there a switch we can use to re-enable exclusive fullscreen, for the purpose of tracking down this bug eventually?

**Comment by Plagman** [comment]
We managed to reproduce this with another title and will have a fix included in the next Beta client update.

**Comment by not83** [comment]
Awesome! Glad to see this being fixed

**Comment by Plagman** [comment]
Can you guys verify the fix with today's Beta?

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.
