### ISSUE TITLE
Steam overlay closes when scrolling in the browser.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/steam-for-linux#4172]
The steam overlay has been consistently closing when used during games that place a high level of stress on the system, especially when multiple browser windows are opened.

This is a little difficult to consistently reproduce, since it seems dependent on the amount of strain put on your system by the game. Which game doesn't seem to matter, but some take longer for the first close of the overlay to happen.

The most consistent way I have reproduced it is finding a guide with embedded Youtube videos. When the videos are opened on Youtube instead of played where embedded (which opens a new browser window), the overlay will often close. Once it has closed in that way for the first time, scrolling on any page after reopening the overlay closes it again. Only restarting the game will make the overlay functional again.

[System info](https://gist.github.com/ramma/925cc19fb6fd7805979e)

**Comment by kisak-valve** [comment]
Hello @ramma, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
