### ISSUE TITLE
steam segfaults after today's update

### ISSUE THREAD

**Issue by Bednar87** [ValveSoftware/steam-for-linux#4173]
Dumps attached. Steam segfaults after a few seconds.

/home/bednar/.local/share/Steam/steam.sh: line 756: 24435 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  7947 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  48966 Mb
    Largest Free Hard Disk Block:  19226 Mb
    
Installed software:
    
Recent Failure Reports:
    Thu Dec 10 07:39:54 2015 GMT: file ''/tmp/dumps/assert_20151210083935_1.dmp'', upload yes: ''CrashID=bp-eec3a207-4846-4a5a-a782-52cb72151209''
    Thu Dec 10 07:40:11 2015 GMT: file ''/tmp/dumps/assert_20151210083953_1.dmp'', upload yes: ''CrashID=bp-0d806dea-6b67-47aa-9b4c-1eef02151209''
    Thu Dec 10 07:40:36 2015 GMT: file ''/tmp/dumps/assert_20151210084019_1.dmp'', upload yes: ''CrashID=bp-5eb409ad-fca5-4089-b05b-3f5042151209''
    

[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/57715/dumps.zip)

**Comment by Tele42** [comment]
@Bednar87 there are multiple issue reports already open regarding steam crashing with nvidia 358 but not 355.

**Comment by ronchaine** [comment]
I began to experience this issue with Intel Graphics card today (I'm not sure if I ran steam yesterday).  Can't run steam to get the machine info from there, but

Arch Linux 64-bit, 4.2.5-1-ARCH kernel
Intel HD Graphics 3000:
(    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Sandybridge Mobile  (0x126)
    Version: 11.1.0
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
)

**Comment by Bednar87** [comment]
UPDATE: 361.18 resolves this issue completely for me.
