### ISSUE TITLE
Steam deleted all games after an update

### ISSUE THREAD

**Issue by wotan343** [ValveSoftware/steam-for-linux#4176]
http://steamcommunity.com/app/221410/discussions/2/494631967654036666/

I just got steam package 1449778863 rolled out to me yesterday

the games I had installed were deleted from my steam directory, as in physically deleted from the .steam/steam/steamapps/common/ folder seemingly in the course of the update.

no mention of it in the update logs, I'm not sure if bootstrap_log.previous.txt is where I should be looking but it wiped out and replaced a swathe of steam client assets by reading them as 0bytes then redownloaded zip files, perhaps my .steam/steam/steamapps/common/ folder was emptied by the same strange operation? these assets had a real size and were in use before yesterday's 60MB update, but the installed games were wiped around the same time. Am I just a test subject here? 

it doesn't seem to be a "steam --reset" issue as with https://github.com/ValveSoftware/steam-for-linux/issues/4154 or at least there's nothing like that mentioned in the logs so I don't know where to begin looking.

**Comment by kisak-valve** [comment]
Hello @wotan343, have you seen this issue since it was initially reported?

**Comment by kisak-valve** [comment]
Closing pending feedback.
