### ISSUE TITLE
Cannot open games from client.

### ISSUE THREAD

**Issue by Undeterminant** [ValveSoftware/steam-for-linux#4177]
I get:

```
ERROR: ld.so: object '/home/myuser/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/myuser/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

and similar from every game I open in the steam client. This seems to be happening for multiple people and has been going on for weeks without any response. Some games manage to still open up fine without the steam overlay but many just crash. I've tried all of the workarounds mentioned on the Arch Linux wiki with no avail.

Running on Arch Linux with the latest version of everything.

**Comment by prcastro** [comment]
Maybe is the new C++ ABI. Have you tried to disable the overlay at the game?

**Comment by Undeterminant** [comment]
I've tried disabling the overlay, and using a fully native runtime. Both do not work.

**Comment by Oxalin** [comment]
@prcastro , maybe but probably not related: I'm also using ArchLinux with the latest C++ ABI and everything still runs as it was (a few games fail, but the were failing prior to this change).

@Undeterminant , I'm also seeing these errors, but I don't think this is the real problem here. Do you have any other output errors displayed when you launch steam from a terminal?

If you are using a fully native runtime, don't you get any errors?

**Comment by Oxalin** [comment]
@Undeterminant , I forgot to ask: are you using an NVidia card? If so, which driver (and version) are you using?

**Comment by Undeterminant** [comment]
I'll try reinstalling Steam and we'll see how that goes.

Right now: Arch Linux, and I'm using bumblebee but only for specific games, and it still doesn't work when it's not disabled. It appears to be an error with steam overlay, because Starbound is the only game to start successfully, but it doesn't show an overlay.

**Comment by Oxalin** [comment]
Bumblebee: intel/nvidia drivers ot intel/nouveau drivers?

Also, are you able to launch some of your games as standalone from a terminal? If so, which ones? What happens (error log) for those crashing?

Is your problem recent? If so, when did you notice the problem?

**Comment by prcastro** [comment]
Bumblebee with Intel/NVIDIA drivers here. When I override the C libraries when running steam with:

```
LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1'
```

 Everything goes right.

**Comment by Oxalin** [comment]
@undeterminant, the solution from prcastro is one proposed on the Arch Wiki. My feeling is that one of the fixes should have solved your problem.

**Comment by Undeterminant** [comment]
@Oxalin: I've tried these fixes and none of them seem to work. It really depends on the game, because it appears that the steam API itself is failing (throwing a null pointer) and many games fail to recover from this.

For example, Crypt of the NecroDancer throws the specific error:
```
Assert( Assertion Failed: ClientAPI_Init(GlobalInstance): GetIClientUser returned NULL. ):../../common/steam/client_api.cpp:455

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
crash_20151226133426_4.dmp[28482]: Uploading dump (out-of-process)
/tmp/dumps/crash_20151226133426_4.dmp
Assert( Fatal Assertion Failed: ClientAPI_Init() ):main.cpp:360
```

Which is from part of Steam's API. And, because I have no access to this code myself, I don't have any way of specifically debugging the problem.

**Comment by Undeterminant** [comment]
This was a misconfigured firewall. Error provided was very poor, but I'm going to say that this was all my fault.

I updated the Arch Wiki to make a note of this.

**Comment by Oxalin** [comment]
Thanks for letting us know. It may help others.

**Comment by Oxalin** [comment]
@Undeterminant Could you give more details about what was wrong with your firewall settings?

**Comment by Undeterminant** [comment]
@Oxalin: My firewall was blocking internal networking requests, i.e. over interface `lo`. This caused this error:

```
Assert( Assertion Failed: ClientAPI_Init(GlobalInstance): GetIClientUser returned NULL. ):../../common/steam/client_api.cpp:455
```

**Comment by Nikitf777** [comment]
I have the same issue on Ubuntu 24.04 when trying to open any game with Proton
![image](https://github.com/user-attachments/assets/cd759647-2887-453c-838f-a74de1ea6036)
