### ISSUE TITLE
Enable graphics driver installation/update support through Steam client

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/steam-for-linux#418]
Since Ubuntu's built-in support for fetching and updating proprietary drivers is spotty at best (and I'm sure some distros are even worse), the "Check for Video Driver Updates" feature in the Steam menu would be a very useful feature to port to the Linux client. And judging from how many of the beta users need still-forthcoming AMD drivers in order to play certain games right now, I'd advise getting this to a functional state in time for said drivers' release.

**Comment by kisak-valve** [comment]
This is hazardous in the best of scenarios and always leads to someone having a bad experience.
