### ISSUE TITLE
Chrome doesn't launch in 64-bit Steam for Linux

### ISSUE THREAD

**Issue by aaronfranke** [ValveSoftware/steam-for-linux#4182]
The process starts but no window appears. The same commands ran from a Terminal work fine.

Specs: Xubuntu 15.10 64-bit, latest Steam for Linux (opted into the beta), latest Google Chrome 47 Linux 64-bit, [rests of my specs](http://pcpartpicker.com/p/2y22vK).

**Comment by Cheeseness** [comment]
This also seems to effect games using current versions(0.12.x) of node.js and has been hampering CrossCode Linux testing efforts.

**Comment by Plagman** [comment]
Do you have an example of such a game that we could reproduce the issue on?

**Comment by Cheeseness** [comment]
CrossCode is all that I'm aware of at the moment

**Comment by Cheeseness** [comment]
Today's update seems to resolve things. Thank you!

**Comment by not83** [comment]
Awesome! Feel free to close this issue

**Comment by Tele42** [comment]
@aaronfranke, please retest when you have some free time.

**Comment by aaronfranke** [comment]
I can confirm that launching Chrome now works as it is supposed to. Issue closed as fixed.
