### ISSUE TITLE
Steam Controller stops working inside games

### ISSUE THREAD

**Issue by Vintodrimmer** [ValveSoftware/steam-for-linux#4183]
Steam Controller works great out of the box, everything in Steam or outside of it works, but none of the games seem to notice the controller. It's as if it's not plugged in or no input reaches them. I can still summon steam's overlay to check configs, but the game itself does not react to the controller whatsoever.

I've tried it with Binding of Isaac: Rebirth; Towerfall:Ascension; Sublevel Zero; Portal

The only modification to the original Steam Runtime is deleted video libraries so my radeonsi driver works.

My system information is as follows:

```  
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3800 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.2-swift_alicorn
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11704000
    X Window Manager:  bspwm
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.7.0)

    Driver Version:  3.0 Mesa 11.0.7
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID Not Detected
    DeviceID Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 1440
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  15966 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  2861587 Mb
    Largest Free Hard Disk Block:  2676334 Mb
    
Installed software:
    
Recent Failure Reports:
    Mon Dec 14 14:00:38 2015 GMT: file ''/tmp/dumps/assert_20151214170037_19.dmp'', upload yes: ''CrashID=bp-59998f22-a42f-4f0c-91fb-5589a2151214''
    Mon Dec 14 14:23:15 2015 GMT: file ''/tmp/dumps/crash_20151214172312_121.dmp'', upload yes: ''CrashID=bp-d6214fe1-20e2-46e3-82ae-1b30b2151214''
    Mon Dec 14 14:23:44 2015 GMT: file ''/tmp/dumps/assert_20151214172342_123.dmp'', upload yes: ''CrashID=bp-5181b04c-3d9c-4f7e-933c-1c1862151214''
` ` `

**Comment by Retik** [comment]
Just started having the same problem after recent update.

**Comment by voidplayer** [comment]
This same thing happens to me, but only on gamepad mode. Games that uses K+M layout seems to work fine (like life4dead 2 or portal)

**Comment by aldrik** [comment]
You need to configure permissions to the HID device nodes:
https://steamcommunity.com/app/353370/discussions/0/490123197956024380/

**Comment by Vintodrimmer** [comment]
Created `/etc/udev/rules.d/90-steam-controller.rules` with 
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"

KERNEL=="uinput", MODE="0660", GROUP="games", OPTIONS+="static_node=uinput"
```
And nothing changed. Maybe because I already had `/etc/udev/rules.d/99-joystick.rules` with 

```
KERNEL=="event[0-9]*", ENV{ID_BUS}=="?*", ENV{ID_INPUT_JOYSTICK}=="?*", GROUP="games", MODE="0660"
KERNEL=="js[0-9]*", ENV{ID_BUS}=="?*", ENV{ID_INPUT_JOYSTICK}=="?*", GROUP="games", MODE="0664"

```

**Comment by not83** [comment]
Are you still able to reproduce this?

**Comment by Vintodrimmer** [comment]
Kinda. It works if I use it for keyboard bindings, but games just don't recognise it as gamepad. Even the ones with official bindings like "they bleed pixels" just say "please, connect the gamepad".

**Comment by aldrik** [comment]
> if I use it for keyboard bindings, but games just don't recognise it as gamepad.

The second line of your udev rules is responsible for the gamepad functionality. Change the `MODE` from `0660` to `0666` and it should work.

**Comment by Vintodrimmer** [comment]
Didn't help, sadly.

I even commented everything in my "joystick.rules" out to doublecheck.

In-game HUD shows only keyboard buttons and trackpads. Any other key/stick/trigger shows nothing if it's set to standard gamepad actions.

And if it was due to permissions, I don't think it would work inside "big picture" either.

**Comment by aranel** [comment]
I had precisely same issue, and adding udev rules file, as mentioned here, resolved this issue.

root # cat /etc/udev/rules.d/99-steam-contoller.rules 
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE=="0666"
KERNEL=="uinput", MODE="0666", GROUP="games", OPTIONS+="static_node=uinput"


unfortunately it's necessary to reboot, then it should apply new udev rules.

**Comment by Vintodrimmer** [comment]
Yeah, problem was on my side after all, sorry.

First of all, I've been missing ` User level driver support `  from the kernel, which might have caused it.
Secondly, Steam from overlay comes with it's own rules, which I was unaware of:

/lib/udev/rules.d/99-steam-controller-perms.rules

` ` ` 
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"
` ` ` 
I've removed them and created 

/etc/udev/rules.d/99-steam-controller-perms.rules

` ` ` 
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="games"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"
` ` ` 

Everything works great now. Thank you all for the help!

**Comment by ack0329** [comment]
OK Problem after switching back to a different Distro Root Partition,

and the last solution WORKED !! THANKS !!  with a twist ... I just changed the one File,
                       ∘  $ sudo gedit /lib/udev/rules.d/99-steam-controller-perms.rules

SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666" KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess" KERNEL=="hidraw*", 
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"   

- Change to, ... and Save/Reboot

SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666" KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input" KERNEL=="hidraw*", 
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"

**Comment by jomarocas** [comment]
with this udev rules always working for me "without put GROUP MEMBER"
```

# Valve USB devices
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0660", TAG+="uaccess"

# Steam Controller udev write access
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"

# Valve HID devices over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="28de", MODE="0660", TAG+="uaccess"

# Valve HID devices over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*28DE:*", MODE="0660", TAG+="uaccess"

# DualShock 4 over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c4", MODE="0660", TAG+="uaccess"

# DualShock 4 wireless adapter over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ba0", MODE="0660", TAG+="uaccess"

# DualShock 4 Slim over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="09cc", MODE="0660", TAG+="uaccess"

# DualShock 4 over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*054C:05C4*", MODE="0660", TAG+="uaccess"

# DualShock 4 Slim over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*054C:09CC*", MODE="0660", TAG+="uaccess"

# Nintendo Switch Pro Controller over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009", MODE="0660", TAG+="uaccess"

# Nintendo Switch Pro Controller over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*057E:2009*", MODE="0660", TAG+="uaccess"

# Nacon PS4 Revolution Pro Controller
KERNEL=="hidraw*", ATTRS{idVendor}=="146b", ATTRS{idProduct}=="0d01", MODE="0660", TAG+="uaccess"

# Razer Raiju PS4 Controller
KERNEL=="hidraw*", ATTRS{idVendor}=="1532", ATTRS{idProduct}=="1000", MODE="0660", TAG+="uaccess"

# Razer Panthera Arcade Stick
KERNEL=="hidraw*", ATTRS{idVendor}=="1532", ATTRS{idProduct}=="0401", MODE="0660", TAG+="uaccess"

# Mad Catz - Street Fighter V Arcade FightPad PRO
KERNEL=="hidraw*", ATTRS{idVendor}=="0738", ATTRS{idProduct}=="8250", MODE="0660", TAG+="uaccess"

# Mad Catz - Street Fighter V Arcade FightStick TE S+
KERNEL=="hidraw*", ATTRS{idVendor}=="0738", ATTRS{idProduct}=="8384", MODE="0660", TAG+="uaccess"

# EMiO Elite Controller for PS4
KERNEL=="hidraw*", ATTRS{idVendor}=="0c12", ATTRS{idProduct}=="1cf6", MODE="0660", TAG+="uaccess"

# HORI RAP4
KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="008a", MODE="0660", TAG+="uaccess"

# HORIPAD 4 FPS
KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="0055", MODE="0660", TAG+="uaccess"

# HORIPAD 4 FPS Plus
KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="0066", MODE="0660", TAG+="uaccess"

# Armor Armor 3 Pad PS4
KERNEL=="hidraw*", ATTRS{idVendor}=="0c12", ATTRS{idProduct}=="0e10", MODE="0660", TAG+="uaccess"

# STRIKEPAD PS4 Grip Add-on
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c5", MODE="0660", TAG+="uaccess"

# NVIDIA Shield Portable (2013 - NVIDIA_Controller_v01.01 - In-Home Streaming only)
KERNEL=="hidraw*", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7203", MODE="0660", TAG+="uaccess", ENV{ID_INPUT_JOYSTICK}="1", ENV{ID_INPUT_MOUSE}=""

# NVIDIA Shield Controller (2015 - NVIDIA_Controller_v01.03 over USB hidraw)
KERNEL=="hidraw*", ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7210", MODE="0660", TAG+="uaccess", ENV{ID_INPUT_JOYSTICK}="1", ENV{ID_INPUT_MOUSE}=""

# NVIDIA Shield Controller (2017 - NVIDIA_Controller_v01.04 over bluetooth hidraw)
KERNEL=="hidraw*", KERNELS=="*0955:7214*", MODE="0660", TAG+="uaccess"
```

**Comment by supersasho** [comment]
@jomarocas Thank you so much! From all the udev rules this one actually worked. I'm considering myself lucky that after 3 years someone replied to this thread.

So what worked for me:

1. Move all udev rules somewhere away (don't delete just in case)
`mv /etc/udev/rules.d/99-steam* ~/etc-udev/`
`mv /lib/udev/rules.d/99-steam* ~/lib-udev/`
2. Copy above content from @jomarocas 
`vi /lib/udev/rules.d/99-steam-controller-perms.rules`
3. Don't need to reboot just resend the udev rules:
`udevadm trigger`
4. Profit :)
