### ISSUE TITLE
Steam download speeds slow to a crawl and cease - disk write error - SD card - Ubuntu

### ISSUE THREAD

**Issue by casparcedro** [ValveSoftware/steam-for-linux#4186]
Hi, I seem to have a strange issue with steam downloads onto an sd card. Whenever I try to download a large game like L4D2 or otherwise the downloads will pick up at the start but then promptly die down finally displaying a disk write error on steam.

I try to resume but the error message won't budge. I then have to run fsck -y on the drive to fix seeming corruption issues but this also has the effect of deleting past progress achieved in the download reseting how much has to be downloaded.

I have tried to use a usb drive and that worked flawlessly. I can use the sd card normally with ubuntu and works when a game like xonotic is downloaded onto the main hard drive and then copied over without any issues.

Some hardware specifications: I am running ubuntu 15.10 on an asus x205ta laptop along with a 128gb sd card from sandisk that appears to be legit. I have had to do one thing to get the sd card reader working though which may or may not be relevant, specifically I had to edit /etc/modprobe.d/sdhci.conf by adding the line options sdhci debug_quirks=0x8000 and then running update-initramfs -u -k all in a terminal.

I'm not quite sure what could be causing this issue but I'd appreciate it if it could be looked into.
Thanks.

**Comment by Tele42** [comment]
As disheartening as it might sound, this is a do not fix from valve's perspective. This is a fundimental weakness of the storage medium. SD cards have about 1000 writes per block, and there is no load balancing by the hardware. The only protection on these cards is on the first block where the (ex)FAT table is expected to be stored. You are very likely burning out blocks by trying to use a SD card as a game repo.

**Comment by casparcedro** [comment]
@Tele42 I figured as much from what I've found on the internet but is it not strange that if an already downloaded executable game like xonotic would work after just being copied rather then having the hard disk thrashed with the downloaded data? Granted I have no idea how Steam does its downloads under the hood.

**Comment by Tele42** [comment]
The main issue with using an SD card with steam is the many small adjustments to the filesystem's superblocks hitting the same physical blocks, not the game files themselves.

**Comment by casparcedro** [comment]
RIP. I guess streaming isn't a bad solution then.

**Comment by kisak-valve** [comment]
Closing as this is a technical limitation of the storage media.
