### ISSUE TITLE
Steam causes kernel panic during shutdown/termination

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/steam-for-linux#4189]
Sometimes after pressing exit button in Steam or shutting down PC while Steam is running, system hangs.
Journalctl shows kernel panic.
SIGKILL on Steam process also can trigger it.
[PC specs](http://pastebin.com/VD7WLy0B)
[Kernel panic trace](http://pastebin.com/jaAYpVck)

**Comment by Plagman** [comment]
Sounds like the xpad driver in your kernel is faulty and can crash on closing the device; you should report a bug on the linux-input mailing list instead.
