### ISSUE TITLE
Big picture: Hinder monitor from blanking

### ISSUE THREAD

**Issue by alexhultman** [ValveSoftware/steam-for-linux#4190]
I just spent some time in Big picture with my Steam controller and it was kind of pleasant until the screen went black. I think you know what I want you to do.

Here is a reference to an identical Chrome bug I filed: https://code.google.com/p/chromium/issues/detail?id=246060

**Comment by kisak-valve** [comment]
Hello @alexhultman, this issue was already being tracked at #2649. Closing as a duplicate.
