### ISSUE TITLE
Warn user when playing on battery

### ISSUE THREAD

**Issue by ltworf** [ValveSoftware/steam-for-linux#4191]
It would be nice if the steam client would show a warning when starting games while the computer is running on battery. Sometimes the cable might just be unplugged by mistake.

This feature would have prevented me to damage my battery.

**Comment by dragetd** [comment]
Most laptops usually give an acoustic signal when the external power is disconnected or have an LED indicating the status.
Last but not least, my desktop environment tells me when I disconnect from power.

IMHO this is not relevant for a gaming platform.

**Comment by ltworf** [comment]
My laptop does not give acoustic signal and the lad is placed in such a position that it is invisible from the user.

**Comment by Tele42** [comment]
All modern laptops (anything using a rechargeable lithium ion or lithium polymer) cut power to the system before there is a risk of damage to the battery. If this is implemented, it should be a generic, and capable of showing multiple batteries including controllers.

**Comment by ltworf** [comment]
It's an OS thing, not an hardware thing.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #3033.
