### ISSUE TITLE
Football Manager 2016 segfault

### ISSUE THREAD

**Issue by reyhansofian** [ValveSoftware/steam-for-linux#4193]
Hi, I'm having this error while trying to run FM16

```
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
ExecCommandLine: "/home/vicz/.local/share/Steam/ubuntu12_32/steam steam://rungameid/378120"
ExecSteamURL: "steam://rungameid/378120"
Installing breakpad exception handler for appid(steam)/version(1450127196)
Game update: AppID 378120 "Football Manager 2016", ProcID 6853, IP 0.0.0.0:0
ERROR: ld.so: object '/home/vicz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vicz/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/vicz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vicz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vicz/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 378120
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198091266849 [API loaded no]
Segmentation fault
Game removed: AppID 378120 "Football Manager 2016", ProcID 6855 
```

It's worked 2 weeks ago. Today, when I'm trying to play it again, I got Steam update and FM16 update. And this error came up. I also have disabled the overlay setting.

**Comment by haube** [comment]
Do not get distracted from the gameoverlay so error. I get this error for games which work without problems too, seems to have no effect and also the error is marked with "ignored".

You may take a look in your /var/log/kern.log , maybe there is more information about the Segmentation fault which happend. 
take a look for something similar like: 
>kernel: hl_linux[24034]: segfault at 0 ip 00000000ed06fe71 sp 00000000ffebaa80 error 6 in client.so[ecf5e000+1e2000]

**Comment by reyhansofian** [comment]
hi @haube 
thanks for your response. Here is my Segmentation fault log
> Dec 21 09:15:07 vicz kernel: [ 1395.345593] fm[12821]: segfault at 0 ip 0000000009ae7ead sp 00000000ed0fe0ec error 4 in fm[804f000+21a9000]

**Comment by ggn06awu** [comment]
Identical experience here, please let me know if you need anything else to help with this.

**Comment by reyhansofian** [comment]
@ggn06awu hi, I can't play FM16 because of this issue. I've tried to delete the FM16 and re-install it, but not working. Is there a way so I can play FM16 again?

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system, if you are, this should be brought to the game dev's attention.

**Comment by kisak-valve** [comment]
Closing pending feedback.
