### ISSUE TITLE
360 controller not working in steam games

### ISSUE THREAD

**Issue by abagjo** [ValveSoftware/steam-for-linux#4197]
My xbox 360 wireless controller no longer works in steam games. I can navigate big picture mode using the controller fine, and I can play games in Dolphin Emulator. I've tried playing Shovel Knight and Alien Isolation and neither game detects my controller. The last time my controller worked in a steam game was on December 3rd when I was playing Dirt Showdown. My distro is Fedora 23.

**Comment by maxbiostat** [comment]
Same here with Ubuntu 14.04.

**Comment by kisak-valve** [comment]
Hello @abagjo, @maxbiostat, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
