### ISSUE TITLE
Big picture mode flickering

### ISSUE THREAD

**Issue by M4T1A5** [ValveSoftware/steam-for-linux#4198]
I seem to have a problem with big picture mode causing the screen to flicker randomly(not a constant flicker. The interval between black frames seems to be anything from 0.1 seconds to a few seconds). This happens the least in the start screen(although it happens there occasionally too), but most prominently in other views like store, library and community.

I have a laptop with a i3-2370M with Intel HD 3000 graphics. I am currently running arch linux with latest updates as of writing(mesa 11.1, newest Intel drivers etc.).

This is a problem only in big picture mode and doesn't happen in Windows on this particular machine.

**Comment by kisak-valve** [comment]
Hello @M4T1A5, are you still experiencing this issue on an up to date system?

**Comment by M4T1A5** [comment]
Oh wow, I didn't even remember I had this bug open. I tested big picture with an up-to-date Arch Linux installation on the machine(I don't really use it for anything anymore, least of all gaming) and do not see this issue anymore. I would imagine it got resolved sometime in the last 3 years.
