### ISSUE TITLE
[Left 4 Dead 2] keys getting rebound

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#4201]
For the past couple days, a couple of my bound keys have reset to default periodically. I've only noticed it with two specific keys (1 and 2), but my bet is the default binds are being inexplicably reloaded, overwriting those custom bindings.

**Comment by sizeofbool** [comment]
When you verify integrity of game cache your "config.cfg" gets replaced by a default one. I recommend you to create "autoexec.cfg" with all binds and commands, so you will have persistent game config.
Also this problem probably tied to Steam Cloud feature so disable it as well.

**Comment by undeference** [comment]
This happens sometimes when switching maps (even different chapters within the same campaign)

**Comment by kisak-valve** [comment]
Hello @undeference, are you still experiencing this issue on an up to date system?

**Comment by undeference** [comment]
I moved my binds to my autoexec.cfg a long time ago.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Left 4 Dead 2 issues are being tracked in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker, so I'm going to close this issue because you're no longer affected and it's out-of-scope for this issue tracker.
