### ISSUE TITLE
Steam offers to add an old ppa (Ubuntu 12.04)

### ISSUE THREAD

**Issue by Pharmasolin** [ValveSoftware/steam-for-linux#4204]
Steps to reproduce:
1. Launch Steam client in Ubuntu 12.04

Expected result: steam client will offer to add a ppa with up-to-date graphic drivers
Actual result: steam client offers to add outdated ppa http://ppa.launchpad.net/ubuntu-x-swat/x-updates/ubuntu

Notes:
I can advice to offer this ppa for ubuntu 12.04 https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa?field.series_filter=precise or even remove this info message.

Click to view screenshot [old-ppa](https://cloud.githubusercontent.com/assets/13041082/12004247/fee93346-ab51-11e5-837b-62091152402c.png)

**Comment by Pharmasolin** [comment]
Similar will add here too:
Page https://support.steampowered.com/kb_article.php?ref=5452-IOSM-1474 needs to be updated too

**Comment by jamesmorris2** [comment]
Bumping this as the PPA no longer exists.

**Comment by kisak-valve** [comment]
Helllo @Pharmasolin, @J-M0, Steam no longer checks for video driver updates.
