### ISSUE TITLE
big picture notifications wiped on accepting gift

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4206]
So, I had 9 notifications. One gift, and eight comment replies.

I went through the screens to select a gift, and it wiped the ability to see the other eight notifications. I had to then go to the steam website manually (because the normal steam client doesn't scale AT ALL on big resolutions).

I imagine this is the same on SteamOS.

**Comment by NaughtySquid** [comment]
In addition to this, Big Picture mode seems utter tosh with notifications in general. Could it be because my Steam is set to load directly into Big Picture? I never seem to see notifications now, so I have to view Steam Store in Firefox.

**Comment by kisak-valve** [comment]
Hello @LiamDawe, have you seen this issue in recent history?

**Comment by LiamDawe** [comment]
Sorry, I practically never use it now and since no one else ever did in years I will close it.
