### ISSUE TITLE
Steam client looks strange

### ISSUE THREAD

**Issue by LSDsl** [ValveSoftware/steam-for-linux#4207]
See screenshot
https://www.dropbox.com/s/sngcjpcwcn5yaku/steam_client.png?dl=0

**Comment by sizeofbool** [comment]
You don't use custom Steam Client skins, do you?
Try to reset Steam Client with this:
```
/usr/bin/steam --reset
```
If it doesn't help then post more information about your PC specs and check steam log file in:
```
/tmp/dumps/username_stdout.txt
```

**Comment by kisak-valve** [comment]
Hello @LSDsl, are you still experiencing this issue on an up to date system? Your screenshot has been lost to time.

**Comment by kisak-valve** [comment]
Closing as this issue report is no longer actionable.
