### ISSUE TITLE
Big picture: Handle suspend / resume redraw

### ISSUE THREAD

**Issue by alexhultman** [ValveSoftware/steam-for-linux#4214]
When resuming from a suspend the graphics are all messed up. This is a similar bug reported and solved in GNOME where the NVIDIA driver does not keep what is in a framebuffer over suspend/resume. One very simple solution would be to set a flag (redrawNextFrame = true) when suspending the computer from within Big picture and then have it redraw every buffer on the next frame. Maybe you already solved this in SteamOS itself but it would be nice if Big picture itself could handle this in a cross-platform way.

As you might have figured out I use the NVIDIA prop. driver. I got the same issue in GNOME prior to the bug fixing. Btw it is really cool that you can actually resume the computer wirelessly with the steam controller!

**Comment by Plagman** [comment]
It's not as simple, as suspend resume discards many of Big Picture's internal rendering buffers. This is a design issue in the NVIDIA driver and not easily worked around for modern apps. I would recommend reporting this with them.
