### ISSUE TITLE
Youtube videos sometimes stop working when valve upgrades chromium

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4215]
Youtube videos sometimes stop working, displaying a black screen and only playing sound, this sometimes is fixed when valve upgrades chromium until it is broken again when upgraded again

**Comment by MRebhan** [comment]
Just curious, when do you watch Youtube videos in Steam?

**Comment by ekaris** [comment]
When clicking on steam guides that are on youtube

**Comment by ekaris** [comment]
Seems fixed
