### ISSUE TITLE
HTTPS should be made the default for all pages

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4216]
HTTPS should be made the default protocol for all pages to protect users privacy and security

**Comment by ozone89** [comment]
:+1:

**Comment by Konstamokh** [comment]
+1

**Comment by not83** [comment]
You can use HTTPS Everywhere to force this.

Which pages don't load in HTTPS for you?

**Comment by ekaris** [comment]
HTTPS Everywhere only works with predefined rules.
For example store.steampowered.com isn't available in HTTPS making all downloads of the steam client vulnerable to interception and infection.
Steam should deploy HTTPS by default on all pages no exception period.

**Comment by ekaris** [comment]
"Other vulnerabilities that are favorite attack vectors? The personal devices employees bring into the office on which they’ve allowed their kids to load Steam games, and which the workers then connect to the network."

Rob Joyce (TAO, NSA) just said Steam games are a security threat #enigma2016

http://www.wired.com/2016/01/nsa-hacker-chief-explains-how-to-keep-him-out-of-your-system/

**Comment by kisak-valve** [comment]
Migration to HTTPS happened a fair while ago, closing.
