### ISSUE TITLE
operating on multiple selections crashes steam

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/steam-for-linux#4217]
latest nvidia driver short lived
latest debian sid
latest steam client beat (its been happening for a while now)

If you select multiple games and click on install, the client crashes
If you select multiple games and select change categories, the game client crashes

**Comment by gdrewb-valve** [comment]
The categories crash is already here as #4203.

**Comment by voidplayer** [comment]
yeah, i saw that one. I opened a new one because i can change category okay if i do it one by one. It seems to be when you operate on several items., but feel free to merge them if you think they are the same :)

**Comment by voidplayer** [comment]
the installation problem is fixed as well
