### ISSUE TITLE
Steam crashes when using integrated file browser

### ISSUE THREAD

**Issue by omerfirmak** [ValveSoftware/steam-for-linux#4219]
When i try to restore a backup. right after i select my backup folder steam just crashes. Steam has gone crazy since the last nvidia driver.

I am running Arch Linux x86_64 and Nvidia hardware with latest drivers. (358.16)

https://www.dropbox.com/s/g1oezp2kyio6iuy/dump.dmp?dl=0
https://www.dropbox.com/s/suavp6rq34focaz/stdout.txt?dl=0

**Comment by Plagman** [comment]
You'll need to downgrade to the 355.xx drivers or wait for the next driver release series from NVIDIA; 358.xx drivers are known to be faulty and to crash the Steam client.
