### ISSUE TITLE
Streaming client hangs in a few minutes after begining a translation.

### ISSUE THREAD

**Issue by lesterb** [ValveSoftware/steam-for-linux#4220]
When I start streaming any game everything starts up fine until after a few minutes a client hangs for no reason. Sometimes I can switch between ttys and X session back and forth but the video is stuck. Sometimes it hangs so hard the system halts. The logs were taken when I was able to switch.

Host rig: AMD FX-9370/Nvidia GTX 980/Windows 7
Client: Gigabyte Brix J1900 GB-BXBT-1900 (Intel Celeron J1900)/Ubuntu 15.10

Streaming txt contains a backtrace of streaming_client's threads. I didn't find a streaming log of the client in ~/.local/steam/ - neither in log nor in stream directories. Maybe it's just me.

Attached also an hwinfo output just in case.

[streaming.txt](https://github.com/ValveSoftware/steam-for-linux/files/75113/streaming.txt)
[Xorg.0.txt](https://github.com/ValveSoftware/steam-for-linux/files/75112/Xorg.0.txt)
[hwinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/75114/hwinfo.txt)

**Comment by lesterb** [comment]
During search on the interwebs I found many similar cases of the deadlock in xcb. Possible solution can be found here http://lists.x.org/archives/xorg/2013-March/055539.html

**Comment by kisak-valve** [comment]
Hello @lesterb, are you still experiencing this issue on an up to date system?

**Comment by lesterb** [comment]
Hi kisak-valve, I guess this issue is valid no more since I don't own a mentioned configuration :)

**Comment by kisak-valve** [comment]
Thanks, closing.
