### ISSUE TITLE
Steam is trying to open games in "steamapps" not "SteamApps"

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/steam-for-linux#4221]
As of today steam has started tying to open games that were running in:

```
/mnt/Games/Games/steamapps/common/
```

not the folder they are actually installed in:

```
/mnt/Games/Games/SteamApps/common/
```

Log of output from trying to launch game and trying to open installed location.

```
Game update: AppID 346510 "Hyphen", ProcID 5361, IP 0.0.0.0:0
ERROR: ld.so: object '/home/steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /mnt/Games/Games/steamapps/common/Hyphen/./Hyphen: No such file or directory
Game removed: AppID 346510 "Hyphen", ProcID 5361 
Installing breakpad exception handler for appid(steam)/version(1450127196)
Generating new string page texture 122: 16x256, total string texture memory is 3.21 MB
Generating new string page texture 129: 64x256, total string texture memory is 3.28 MB
Generating new string page texture 130: 48x256, total string texture memory is 3.33 MB
Generating new string page texture 131: 128x256, total string texture memory is 3.46 MB
Generating new string page texture 133: 256x256, total string texture memory is 3.72 MB
Game update: AppID 346510 "Hyphen", ProcID 5634, IP 0.0.0.0:0
ERROR: ld.so: object '/home/steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /mnt/Games/Games/steamapps/common/Hyphen/./Hyphen: No such file or directory
Game removed: AppID 346510 "Hyphen", ProcID 5634 
gvfs-open: /mnt/Games/Games/steamapps/common/Hyphen: error opening location: Error when getting information for file '/mnt/Games/Games/steamapps/common/Hyphen': No such file or directory
```

**Comment by abc-mikey** [comment]
In fact looking further I can see that 
```
/mnt/Games/Games/steamapps/
```
appears to have been populated with the various configuration files but
```
/mnt/Games/Games/SteamApps/common
```
appears to have the actual game data installed to it.

**Comment by abc-mikey** [comment]
A workarround appears to be to move the gamedata into the folder with the steam config files:
```
cd /mnt/Games
mv Games/SteamApps/common/* Games/steamapps/common/
rmdir Games/SteamApps/common/
rmdir Games/SteamApps/
```
And symlink the other directory name steam is trying to access to the common one:
```
cd Games/
ln -s steamapps SteamApps
```
However steam should not be confusing upper and lower case paths like this!

**Comment by rmbleeker** [comment]
Related to #4154? That one is fixed though.

**Comment by not83** [comment]
If it is the same as #4154 and is fixed, could this please be closed then.

**Comment by abc-mikey** [comment]
It looks like it may be related to the switch to a lower case "steamapps" folder as mentioned in #4154 but not to the actual issue in that thread as I have never run "steam --reset".

My guess would be that there an issue in migrating people to the lower case name perhaps related to the slightly unusual path that I picked in /mnt/ or the fact that this was my second install location. 

There then seems to have been a recent change to the way that the locations are picked for launching games, as they only stopped working shortly before I posted this issue.

**Comment by not83** [comment]
So if you run steam --rest the bug goes away?

**Comment by abc-mikey** [comment]
Sorry I have reordered my collection so that I no longer am able to reproduce the issue.

**Comment by not83** [comment]
That's fine. Feel free to close this bug

**Comment by kisak-valve** [comment]
Hello @abc-mikey, Steam no longer supports the older camel-cased SteamApps naming convention and will automatically migrate the folder to all lower case  if it can safely.
