### ISSUE TITLE
Add post images to google+

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4226]
Not all of us use facebook

**Comment by rmbleeker** [comment]
Seconded

**Comment by not83** [comment]
Which images are you talking about?

**Comment by ekaris** [comment]
Screenshots of the games using the built in steam tool to do it and upload.

**Comment by rmbleeker** [comment]
![screenshot from 2016-01-09 14 25 54](https://cloud.githubusercontent.com/assets/4312801/12216325/af64a386-b6dd-11e5-85d3-347d72ea90e6.png)

**Comment by alextpedro** [comment]
A generic share that allows us to then choose more of the most popular social networks would actually be amazing.

**Comment by kisak-valve** [comment]
Google Plus is about to be discontinued.
