### ISSUE TITLE
Cache Inventory to make it faster

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4228]
Cache all Inventory items to make it faster to display

**Comment by not83** [comment]
What do you mean by this? What are you steps to reproducing this bug?

**Comment by ekaris** [comment]
What I mean is to cache all inventory items like cards because with a very high number of items it is very slow to load. Steps to reproduce are having a inventory with like 2000 different cards and open it.

**Comment by ekaris** [comment]
Also cache the emotions, they take a looooong time to load when they are many

**Comment by Tele42** [comment]
As a side note, your request is for a large core change and is not OS-specific. Inventory and all related parts are webpages viewed through the steam client.

**Comment by not83** [comment]
I'm wondering if this can't be done because it could lead to issues.

What if items they no longer own are cached and still show up
