### ISSUE TITLE
Audio Passthrough kills Steam Client in Background

### ISSUE THREAD

**Issue by tommyknows** [ValveSoftware/steam-for-linux#4230]
I have a very weird issue with SteamOS and Steam itself.
I use SteamOS with Kodi - I added Kodi as a non-Steam Product to my Library and I am starting Kodi from there.
Kodi is also running from the steam user:

``` shell
desktop@steamos:~$ ps -ef | grep kodi
steam     2112  2111  0 17:02 ?        00:00:00 /bin/sh -c "/usr/bin/kodi"
steam     2113  2112  0 17:02 ?        00:00:00 /bin/sh /usr/bin/kodi
steam     2121  2113  4 17:02 ?        00:00:33 /usr/lib/kodi/kodi.bin
desktop   2257  2060  0 17:14 pts/1    00:00:00 grep kodi
```

I have a steam controller attached and working. I start the application, everything works fine. As soon as I start a movie / tv show / music, something happens:
My Steam Controller doesn't work anymore, like it's disconnected (it is not). Reconnecting doesn't work neither.
When I stream Kodi to Steam on my laptop, it disconnects abruptly when starting a song. I can't see my steamos-machine anymore.
I watched the log files and got the following in /tmp/dumps/steam_stdout.txt:

``` shell
/home/steam/.local/share/Steam/steam.sh: line 756:  1888 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

The complete log file [steam_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/76652/steam_stdout.txt)
.
Now the steam.sh shows following lines:

``` shell
    752 elif [ "$STEAM_DEBUGGER" == "strace" ]; then
    753     strace -osteam.strace "$STEAMROOT/$STEAMEXEPATH" "$@"
    754 else
    755         $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
    756 fi
    757 STATUS=$?
```

Kodi shows nothing in the log files. 
Mouse & Keyboard works fine.
Internet works fine too.
Just Steam like "crashing in the background".

**Comment by ramonrue** [comment]
Update:
I disabled Audio Passthrough (DTS; DD; DD+) and set the HDMI-Output to 5.1
Now it's working. No Log File Problem, Controller working.
Update 2: Disabled the option to stream (as I read that Steam In-Home Streaming only allows Stereo.) Enabled the Audio Passthrough. Not working.

So as long as passthrough is disabled, Steam keeps working.
The problem is passthrough, or maybe pulseaudio.
I checked the pulseaudio-logs, but did not found any relevant information. (I'm just wondering why PA is running in System-Mode, but I think this is none of my concern :-) ).

**Comment by ramonrue** [comment]
Pulseaudio-Logfile (cut down to 30min):
[Pulseaudio.txt](https://github.com/ValveSoftware/steam-for-linux/files/76666/Pulseaudio.txt)

**Comment by sque** [comment]
I can also confirm this. I am experiencing exactly the same thing on SteamOS Brewmaster 2.0 and Kodi 16.1.

By the moment I start playing a movie with DTS passthrough, steam controller becomes zombie (light is constant on but whatever you press.. no change).
My `/tmp/dumps/steam_stdout.txt` also ends with the same line:
```
...
Not pushing commsnd this frame due to failed lock
/home/steam/.local/share/Steam/steam.sh: line 713: 810 Segmentation fault $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

I cannot understand how steam client crashes when another application is using passthrough, but at least a good workaround is needed here.

**Comment by tommyknows** [comment]
Yes, problem still persists on Brewmaster - Kodi is not the problem here. It's as soon as something starts to passthrough audio. 
I think, if Multi-Channel Audio should come to Linux Gaming (if I remember correctly, not a single game supports multi channel at the moment), then this is an important thing as a DD(+) or DTS signal is far better than a normal PCM....@Plagman are you working on this?

Is multi channel output in games not supported because of that problem? Or are there other problems that make it difficult? Windows got it working too, so it would be great if Linux / SteamOS had that too...

**Comment by pierrep** [comment]
I can confirm I also have this problem. Selecting audio pass-through from within Kodi causes Steam to freeze/crash.

**Comment by jjpe** [comment]
I'm using Fedora 27, and the issue still persists. 
Has Valve given up on supporting Linux, or is this a classic "Valve Time" thing? :)

**Comment by tommyknows** [comment]
I found the following on the (kodi)[https://kodi.wiki/view/PulseAudio#Passthrough_Mode] wiki:
```
IMPORTANT: Passthrough is always an exclusive mode. If you have another application hogging the device, e.g. Chrome or Skype, passthrough won't work. Even applications that simply monitor the device, such as SoundWireServer, will prevent passthrough from working.
REMEMBER: To use passthrough you need to be using 2.0 channel configuration via pavucontrol (e.g. Digital Stereo (HDMI)
```

As steam is running in the background, the first condition is violated. 
I assume that, when kodi tries to enable passthrough, it just "kills" everything else in the background. 
One solution, if you really want passthrough, is to replace the desktop config of gnome (which gets loaded when you go to the desktop from within big-picture mode) with a config for kodi. 
With this, steam will get cancelled in the background and passthrough should theoretically work. 
You'd have to find a way to launch steam from kodi though...don't know if the "Exit Kodi" method starts steam again.

I'm closing this issue as this is not a steam-for-linux issue, but more a purely technical limitation of passthrough...
