### ISSUE TITLE
Kali Linux 2.0 - You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1

### ISSUE THREAD

**Issue by Sevii69** [ValveSoftware/steam-for-linux#4233]
I can't resolve this error : "You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1 "

Someone can help me please? :(
![screenshot from 2016-01-04 01 28 34](https://cloud.githubusercontent.com/assets/16530540/12081474/d6e7cf1e-b282-11e5-8568-5012d76daab2.png)
![screenshot from 2016-01-04 01 28 46](https://cloud.githubusercontent.com/assets/16530540/12081475/d6e8ba00-b282-11e5-9218-fa3acceb45ed.png)

**Comment by Sevii69** [comment]
When I try to fix this....
![screenshot from 2016-01-04 01 44 39](https://cloud.githubusercontent.com/assets/16530540/12081537/f2531dc4-b284-11e5-9877-5ef94b02a11c.png)

**Comment by ViBENo1** [comment]
what VGA you have? is it an Intel based notebook or an Optimus notebook (Intel + NVIDIA VGA)?

**Comment by gdrewb-valve** [comment]
Do you have 32-bit OpenGL support installed?  Do any 32-bit OpenGL applications work?

**Comment by Sevii69** [comment]
I don't have OpenHL installed and my laptop is Asus R501VB

**Comment by Sevii69** [comment]
Now I install OpenGL but still not working.
PS : Sorry for my English

**Comment by Sevii69** [comment]
Thanks for helping ! I resolve this problem.
I reinstall the system and first time I install skype with this tutorial ( https://forums.kali.org/showthread.php?27578-Install-Skype-on-Kali-Sana-2-0-64-bit ) and steam with this tutorial ( https://www.youtube.com/watch?v=iuRRHN9VowU ) .
