### ISSUE TITLE
steam built-in screenshot tool causes corrupt screenshots with non-valve game Ark

### ISSUE THREAD

**Issue by Gartral** [ValveSoftware/steam-for-linux#4234]
as the title says when I use the valve-supplied (Default key is F12) screenshot tool in Ark: Survival Evolved I get a very corrupt version of a screenshot (Albeit a very interesting one!):
![2016-01-02_00003](https://cloud.githubusercontent.com/assets/649782/12081794/32f396f6-b253-11e5-8654-77f7d542445b.jpg)

this only seems to happen with this game, and only with the valve screenshot tool, I can use any other method of obtaining a screenshot and it works fine.

for completion's sake here's my hardware/OS info

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-22-lowlatency
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.63
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x13c2
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 33.58" x 18.90"  (38.50" diag)
                                        85.3cm x 48.0cm  (97.8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 4096 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15974 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  2800503 Mb
    Largest Free Hard Disk Block:  1999597 Mb

Installed software:

Recent Failure Reports:
    Sun Jan  3 10:57:03 2016 GMT: file ''/tmp/dumps/assert_20160102222804_2.dmp'', upload yes: ''Discarded=1''

**Comment by Germano0** [comment]
I am experiencing this problem with SOMA game. I tried with Serious SAM 3 BE and it seems to not be affected by this problem.
 Operating System: Fedora 25 (kernel 4.8.14-300.fc25.x86_64), VGA: Radeon RX480 with amdgpu drivers

**Comment by kisak-valve** [comment]
Hello @Gartral, @Germano0, are you still experiencing this issue on an up to date system?

**Comment by Germano0** [comment]
At the moment I don't have a machine to run tests

**Comment by Gartral** [comment]
> Hello @Gartral, @Germano0, are you still experiencing this issue on an up to date system?

I'm in the same boat as @Germano0. my current computer just crashes out ARK on load, this is an ARK issue and not something Valve can fix.

**Comment by kisak-valve** [comment]
Thanks for the feedback, some workarounds at https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#ARK:_Survival_Evolved might help get the game to run.

**Comment by kisak-valve** [comment]
Closing pending confirmation this issue can be reproduced.
