### ISSUE TITLE
Seemingly random steam client shutdowns (and the games that are currently running at time)

### ISSUE THREAD

**Issue by makkenhoff** [ValveSoftware/steam-for-linux#4236]
First time I've done a bug report here, so pardon if everything is horribly hard to read. As you can see, I've been "roughing" these crashes for some time, mildly annoying, but most of the games I tend to play aren't really affected by the crashes (near persistent auto-saves). Will provide more information as soon as I know what else is required.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  2812 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-0.bpo.1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GT 640/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0xfc1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 45.28" x 25.59"  (51.97" diag)
                                            115.0cm x 65.0cm  (132.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT1708S
    
Memory:
    RAM:  7987 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  922648 Mb
    Largest Free Hard Disk Block:  554545 Mb
    
Installed software:
    
Recent Failure Reports:
    Tue Dec 29 12:06:22 2015 GMT: file ''/tmp/dumps/crash_20151229070616_21.dmp'', upload yes: ''CrashID=bp-188f447f-31e7-47d0-9153-d78f62151229''
    Tue Dec 29 12:13:44 2015 GMT: file ''/tmp/dumps/assert_20151229071337_16.dmp'', upload yes: ''CrashID=bp-d60d698f-96a2-46a9-8347-c27f72151229''
    Tue Dec 29 14:31:56 2015 GMT: file ''/tmp/dumps/assert_20151229071244_1.dmp'', upload yes: ''CrashID=bp-a03dcb76-3f5e-40f4-a249-e13e12151229''
    Tue Dec 29 23:47:00 2015 GMT: file ''/tmp/dumps/assert_20151229093204_1.dmp'', upload yes: ''CrashID=bp-5b739629-5093-488c-937a-7ab822151229''
    Tue Dec 29 23:47:35 2015 GMT: file ''/tmp/dumps/assert_20151229184711_1.dmp'', upload yes: ''CrashID=bp-84d64009-5d39-4633-98a0-712b52151229''
    Wed Dec 30 21:02:18 2015 GMT: file ''/tmp/dumps/assert_20151230160147_1.dmp'', upload yes: ''CrashID=bp-9e77c4e9-f0e9-42c2-ac52-5973d2151230''
    Wed Dec 30 21:37:37 2015 GMT: file ''/tmp/dumps/crash_20151230163734_7.dmp'', upload yes: ''CrashID=bp-0265b7ec-b3be-49f6-94c1-5045d2151230''
    Thu Dec 31 18:01:00 2015 GMT: file ''/tmp/dumps/crash_20151231130058_7.dmp'', upload yes: ''CrashID=bp-f3044f65-65fa-46f4-b8c8-25ec92151231''
    Thu Dec 31 18:51:02 2015 GMT: file ''/tmp/dumps/assert_20151230160243_1.dmp'', upload yes: ''CrashID=bp-25fca02b-3301-48d9-af73-f72152151231''
    Thu Dec 31 19:57:02 2015 GMT: file ''/tmp/dumps/crash_20151231145700_9.dmp'', upload yes: ''CrashID=bp-e19868d3-a591-421d-8b89-ae39e2151231''
    Thu Dec 31 19:57:31 2015 GMT: file ''/tmp/dumps/crash_20151231145729_7.dmp'', upload yes: ''CrashID=bp-ac50934f-f8b8-44e2-b3aa-69c2a2151231''
    Fri Jan  1 05:21:04 2016 GMT: file ''/tmp/dumps/crash_20151231183645_1.dmp'', upload yes: ''CrashID=bp-714e6db3-918e-4160-85e2-76d042151231''
    Fri Jan  1 15:41:48 2016 GMT: file ''/tmp/dumps/assert_20160101104144_18.dmp'', upload yes: ''CrashID=bp-232aac0f-bdf7-474a-8adc-173582160101''
    Fri Jan  1 19:23:54 2016 GMT: file ''/tmp/dumps/assert_20160101104847_1.dmp'', upload yes: ''CrashID=bp-0382989c-c939-43df-ab52-008632160101''
    Fri Jan  1 19:23:58 2016 GMT: file ''/tmp/dumps/assert_20160101142354_2.dmp'', upload yes: ''Discarded=1''
    Fri Jan  1 21:40:39 2016 GMT: file ''/tmp/dumps/crash_20160101164037_8.dmp'', upload yes: ''CrashID=bp-17a70b96-8db9-4be4-a644-d74382160101''
    Sat Jan  2 16:09:39 2016 GMT: file ''/tmp/dumps/assert_20160101214724_1.dmp'', upload yes: ''CrashID=bp-a240288b-7b17-4cb0-a460-2cf082160102''
    Sat Jan  2 18:47:14 2016 GMT: file ''/tmp/dumps/crash_20160102134712_7.dmp'', upload yes: ''CrashID=bp-ae5a85bd-780d-4880-9820-89a372160102''
    Sun Jan  3 01:38:45 2016 GMT: file ''/tmp/dumps/crash_20160102202833_1.dmp'', upload yes: ''CrashID=bp-6ff83804-b62d-467d-aea7-95b672160102''
    Mon Jan  4 13:27:02 2016 GMT: file ''/tmp/dumps/crash_20160102204355_1.dmp'', upload yes: ''CrashID=bp-b3f8611c-2da9-4648-8dd3-c78b92160104''
    Mon Jan  4 14:13:00 2016 GMT: file ''/tmp/dumps/crash_20160104091202_1.dmp'', upload yes: ''CrashID=bp-88a7ea2b-ecfe-4bcb-9737-a8e7f2160104''
    Mon Jan  4 14:41:21 2016 GMT: file ''/tmp/dumps/crash_20160104091456_1.dmp'', upload yes: ''CrashID=bp-06ada959-62ec-41c7-b74b-2b16d2160104''
    
[makkenhoff_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/77338/makkenhoff_log.txt)
[makkenhoff_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/77339/makkenhoff_stdout.txt)

**Comment by Tele42** [comment]
There is a known regression in nvidia 358, but not 355. Please check to see if this applies to you.

**Comment by makkenhoff** [comment]
Okay, thanks for the comment Tele42. Just verifying that I'm in the 358.18 camp.
