### ISSUE TITLE
Steam Controller: right bumper button, when click moves cursor up forever

### ISSUE THREAD

**Issue by ChrisFernandez** [ValveSoftware/steam-for-linux#4237]
so is all working great, and even in some games with out any change on my part, but on "big screen" and "some" games, when I press the right bumper button, I believe is the left click by default, acts like if my mouse were scrolling up, non-stop until I stop steam and turn off the controller..
I did notice that if I "disable" the analog option then seems to work on all games.. on big picture I cant disable this option since there is no way to change defaults from big screen yet.. STILL even if I could this is clearly a bug, I want my controller to work, if not im going to have to return it. I spoke with support and they told me to post the issue here since Im not using Ubuntu, my system is Manjaro GNU/Linux using KDE, nvidia card, etc.  Any ideas? anyone else having this problem?

**Comment by hooloovooo** [comment]
I'm having the same issue. It seems to translate the analog right trigger to moving the mouse up and down on the screen. If i connect the controller it will not happen until the first time i press the trigger.

**Comment by xPathin** [comment]
Having the same issue. It's really annoying...

**Comment by ChrisFernandez** [comment]
@xPathin thanks for your findings.. Ill try that when I get home. btw on what distro are you guys?
i'm on arch gnu/linux just curious.

**Comment by xPathin** [comment]
I'm on Manjaro Cinnamon, so arch in a nutshell...
That might explain why I had the same problem :)

**Comment by rathsky** [comment]
Just to confirm: Same problem, same solution (removing xf86-input-joystick); also on Arch (+ git versions of all X11 stuff).

The issue showed itself a bit differently though:
* Right bumper: perma-move cursor leftwards (not upwards)
* Left bumper: perma-scroll leftwards (seen eg. when clicking on tabs or interacting with a horizontal scrollbar in Chrome)
* Both bumpers: Other than the bugged behavior, clicking either would also issue a single mouse click as intended.

**Comment by hooloovooo** [comment]
I'm guessing this really isn't an issue with steam itself. The xf86-input-joystick package is just doing what it's supposed to. Might want to get Arch to ditch it from whatever metapackage it comes with since i doubt almost anyone want that feature by default.

**Comment by ChrisFernandez** [comment]
closing this issue since is been working for 8 months fine. reopen if someone else needs help

**Comment by unnome** [comment]
hello from 2021!
I seem to have the exact same symptoms  (right bumper moves mouse upwards forever).
I don't seem to have the package xf86-input-joystick installed though.

using MX linux 19

**Comment by Jezza** [comment]
I'm using Debian, same issue.  
I don't have any such package, but I did manage to find `xserver-xorg-input-joystick`.  
Removing that package fixed my issue.
