### ISSUE TITLE
Crash each time I'd add or remove a category from a game in the library

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/steam-for-linux#4243]
Today when I went to remove a category from a game in my library, Steam crashed with a segfault. I then discovered this happens each time I change the categories for any game. I've attached the log and the minidump.

I'm using Arch Linux with all software up to date.

[steam-crash.txt](https://github.com/ValveSoftware/steam-for-linux/files/83315/steam-crash.txt)

[assert_20160108164516_1.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/83319/assert_20160108164516_1.dmp.zip)

**Comment by gdrewb-valve** [comment]
Can you post which video driver you're using?  There's a known issue with NVIDIA 358 drivers.

Also see #4203.

**Comment by yaomtc** [comment]
Yup, that's the one. 358.16-3. Looks like I should have searched! This is a duplicate after all, whoops.
