### ISSUE TITLE
Civ 5 Mods

### ISSUE THREAD

**Issue by ts1829** [ValveSoftware/steam-for-linux#4248]
Having a problem with mods in Civ5.  When I enable the mods I've subscribed to in Steam the "Configuring Game Data Please Wait" window appears and then the game crashes and goes back to Steam.  When I restart the game, the mods are shown as enabled, but they don't appear in the game.  I've tried verifying and re-downloading the game cache.

**Comment by Tele42** [comment]
@Thor828 by any chance are you using nvidia 358?

**Comment by kisak-valve** [comment]
Hello @ts1829, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
