### ISSUE TITLE
Steam tray icon has different color unlike official Steam logo

### ISSUE THREAD

**Issue by TotalCaesar659** [ValveSoftware/steam-for-linux#4249]
On Lubuntu 15.10, Steam tray icon has different color unlike official Steam logo:
it is grey-and-white and fades on background with same color, as you can see on first 2 screenshots.
![screenshot from 2016-01-10 01-50-53](https://cloud.githubusercontent.com/assets/14265316/12219195/7134c02a-b749-11e5-9e0e-a7731655edd6.png)
![screenshot from 2016-01-10 01-51-19](https://cloud.githubusercontent.com/assets/14265316/12219196/7138317e-b749-11e5-9b37-0f62f31f61b5.png)
Can you replace it by official Steam logo or at least add an option for choosing tray icon?
The right logo is very precise and it looks very good, I draw the picture of this:
![end_result](https://cloud.githubusercontent.com/assets/14265316/12219226/03e22f92-b74b-11e5-9843-3f52b01e67bc.png)
I can give you more information if you want.

**Comment by Plagman** [comment]
We provide two icons, one monochrome and the other with color. The expectation is that a desktop environment deciding to use the monochrome one should tint it appropriately given its theme, which doesn't seem to be happening properly here. I would take this up with your distribution vendor.
