### ISSUE TITLE
Random Segmentation Fault while using Steam chat.

### ISSUE THREAD

**Issue by Okoyl** [ValveSoftware/steam-for-linux#4255]
Hey, I have been having some segmentation faults lately while using steam chat.
these don't reproduce while playing games, browsing and doing other stuff on Steam.
I tried to reset steam (deleting everything except steamapps).

Using Archlinux with 4.3.3 kernel. Kde
Basic System Info collected by Steam:
`
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.3-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11800000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 358.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                            51.8cm x 32.4cm  (61.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: 
    
Memory:
    RAM:  16077 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Total Hard Disk Space Available:  228744 Mb
    Largest Free Hard Disk Block:  14744 Mb
    
Installed software:
    
Recent Failure Reports:
    Thu Jan 14 18:11:06 2016 GMT: file ''/tmp/dumps/assert_20160114191127_1.dmp'', upload yes: ''CrashID=bp-f8d94512-e26c-47fd-b352-26e0e2160114''
    Thu Jan 14 18:36:29 2016 GMT: file ''/tmp/dumps/assert_20160114201108_1.dmp'', upload yes: ''CrashID=bp-e0c41953-b6d5-4f81-9601-9bbc22160114''
    Thu Jan 14 18:51:31 2016 GMT: file ''/tmp/dumps/assert_20160114203640_1.dmp'', upload yes: ''CrashID=bp-5fa1c80a-2eaa-4643-969a-aa4e02160114''
    
`

[assert.dump.zip](https://github.com/ValveSoftware/steam-for-linux/files/90858/assert.dump.zip)

**Comment by gdrewb-valve** [comment]
The crashes are all in the NVIDIA OpenGL driver.  There are known problems with 358, you might try a different version.

**Comment by CommanderAlchemy** [comment]
Since you are using KDE you want to use the latest beta driver 361.18.
358.16 will crash steam
361.16 will crash QT/KDE
361.18 should work fine.
