### ISSUE TITLE
reproducible Steam crash @ Audio Settings

### ISSUE THREAD

**Issue by adolson** [ValveSoftware/steam-for-linux#4257]
Hello. Steam crashes for me every time I try to change the audio levels for the Interface or Voice. 

I am logged into my desktop as my user (dana) and running Steam via sudo as a secondary user (steam) which is dedicated to only running games. This keeps all game-related stuff separate from my main user account's data. This has many benefits, such as ease of backing up my save files.

To get audio to work with this setup, I had to set up Pulse as a server on my main user account (load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1), and my steam user has a Pulse client config telling it to connect to that server on localhost (default-server = 127.0.0.1). It works perfectly for all of my games and for Steam audio, web browser audio, etc, EXCEPT for when I want to change the audio levels for the interface or for voice. Then it crashes, every time. This used to work fine, but it broke at some point (maybe around the time Big Picture mode was redesigned, but I can't quite recall exactly). I didn't think to report until now.

I know this setup is a little unorthodox, but I also know I am not the only one doing it this way, and in all other aspects it works fine. If nothing else, I think Steam should handle whatever error is going on behind the scenes gracefully rather than just closing.

I am not sure how to get any kind of helpful debug information to troubleshoot this, so please let me know if there's anything more I can do.

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/steam-for-linux#reporting-issues, especially any CrashIDs related to the crash in the settings.

**Comment by adolson** [comment]
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.0-0.bpo.1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x11c0
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 62.99" x 35.43"  (72.24" diag)
                                            160.0cm x 90.0cm  (183.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  7926 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  150102 Mb
    Largest Free Hard Disk Block:  95701 Mb
    
Installed software:
    
Recent Failure Reports:
    Mon Jan 11 07:58:13 2016 GMT: file ''/tmp/dumps/crash_20160111025804_205.dmp'', upload yes: ''CrashID=bp-3f074b02-7296-455b-9924-6d8822160110''
    Fri Jan 15 06:08:23 2016 GMT: file ''/tmp/dumps/assert_20160115010818_967.dmp'', upload yes: ''CrashID=bp-6a0e3f85-2fec-458f-8bed-82b442160114''
    Fri Jan 15 07:31:12 2016 GMT: file ''/tmp/dumps/assert_20160115023109_325.dmp'', upload yes: ''CrashID=bp-648fa44a-24c8-4326-a620-c58312160114''
    Fri Jan 15 09:57:33 2016 GMT: file ''/tmp/dumps/assert_20160115045729_395.dmp'', upload yes: ''CrashID=bp-c2922000-e450-4118-811c-0f6032160115''
    Fri Jan 15 11:08:22 2016 GMT: file ''/tmp/dumps/assert_20160115060815_659.dmp'', upload yes: ''CrashID=bp-5a58885b-8d70-40d0-9918-766362160115''
```

**Comment by gdrewb-valve** [comment]
Crash in ActivateActionSet.

**Comment by adolson** [comment]
This is definitely related to #4272 and has nothing to do with my client/server Pulseaudio and sudo setup.
I tested by running pactl unload-module module-combine-sink ; pactl unload-module module-combine, and Steam no longer crashes. I need to research how and why those are being loaded on my system, but I'm glad to have found the cause.

I don't think we need both issues open, so I will close this one, since I seem to have been on the wrong track all along. If someone feels differently, feel free to reopen.
