### ISSUE TITLE
Loss of cards at around same time as steam database corruption

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4258]
I have games that had 3 cards and now they show that I have only 2, I can assure that the account wasn't compromised, I don't trust steam support to handle this, if you want more info I can provide by private msg

**Comment by gdrewb-valve** [comment]
This isn't the appropriate place to report the problem as this repo is for Linux- and Mac-specific bugs in the Steam client.  Steam support is actually the right place or you can post in the general Steam forums.
