### ISSUE TITLE
Pulseaudio crashes a lot when launching steam games on ubuntu 15.10

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4259]
Pulseaudio crashes a lot when launching steam games on ubuntu 15.10 leaving the games without sound

**Comment by gdrewb-valve** [comment]
Possible Steam runtime incompatibility.

**Comment by Edupop** [comment]
As I can no longer find ~/.local/share/Steam/, I'll assume you guys fixed up your end. 

The other half of the issue is fixed upstream in pulse 1.7, adding ppa:ubuntu-audio-dev/pulse-testing to your sources resolves the issue in 15.10.

**Comment by ekaris** [comment]
Closing, problem is solved on 16.04
