### ISSUE TITLE
Steam Won't Finish Installing Games on Linux Mint 17.3 [FIXED]

### ISSUE THREAD

**Issue by berkiyo** [ValveSoftware/steam-for-linux#4263]
So I recently made the switch from Arch to Linux Mint and its fairly good! Recently I discovered an annoying issue that can't install games like CS:GO and others properly. When they download, they are literally stuck at the end and won't budge. I have attached link that is showing the problem occurred. 

Things I have tried:
Changing Steam Download Server Region 
Un-install reinstall the game 
Reinstall Steam
Reinstall the OS
Update Mint

Nothing managed to fix it :(

Specs:
i3 3227U + 6GB Ram + 750GB HDD + Linux Mint 17.3 /w MATE Desktop.

Link to screenshot: https://drive.google.com/file/d/0ByWODPOi1II1NGZZbVZEMUo3MTg/view

EDIT: Also if you cancel the download in the manager, they say 'CONNECTION TIME OUT'

You can also contact me here: https://steamcommunity.com/id/stickybranches

Thanks!

**Comment by gdrewb-valve** [comment]
In your Steam directory there should be a logs subdir, can you take the content_log.txt from there and put it up as a gist (or whatever other file sharing you'd like)?

**Comment by berkiyo** [comment]
Here is the full text in that content_log text file: http://pastebin.com/haJMMKXS

**Comment by berkiyo** [comment]
UPDATE: I fixed it by logging in from another account. I think its an account issue.

**Comment by kisak-valve** [comment]
Hello @berkiyo, have you experienced this issue in recent history?

**Comment by kisak-valve** [comment]
Closing pending feedback.
