### ISSUE TITLE
Slow download that produces lots of traffic

### ISSUE THREAD

**Issue by kochd** [ValveSoftware/steam-for-linux#4265]
Currently download in steam big picture mode shows 0-500kb/s on a 32Mbit connection.
Using other tools e.g iftop / openwrt graph i see that the connection runs at maximum using multiple servers.

<pre>
steambox.lan                          => 162-254-197-23.valve.net                    38,2Kb  52,5Kb  13,2Kb
                                      <=                                             11,2Mb  9,50Mb  2,38Mb
steambox.lan                          => 162-254-197-24.valve.net                       0b   48,0Kb  13,2Kb
                                      <=                                                0b   8,20Mb  2,10Mb
steambox.lan                          => 162-254-196-18.valve.net                       0b   27,6Kb  12,3Kb
                                      <=                                                0b   6,27Mb  1,91Mb
steambox.lan                          => 162-254-197-25.valve.net                     130Kb  38,3Kb  10,1Kb
                                      <=                                             19,2Mb  4,23Mb  1,06Mb
steambox.lan                          => 162-254-196-26.valve.net                       0b   28,9Kb  8,37Kb
                                      <=                   
</pre>

So actually downloaded 5GB. Where 100 MB were used for the wanted content.
Something is absolutely broken here.

Just guessing: The client is downloading the same chunks multiple times from multiple server.
It does not matter which product.

**Comment by not83** [comment]
What happens when you change your steam downloads  server?

**Comment by kochd** [comment]
I already tried that without sucsess

**Comment by kochd** [comment]
Now a few hours later it  seams that a fresh ( from zero ) started download of "The Witcher 2" shows download at correct speed while "7 Days to Die" show exactly the reported behavior.

**Comment by kochd** [comment]
Closed. This happens when you try to adblock by mapping hosts to 0.0.0.0. Looks like some steam servers are on the lists around
