### ISSUE TITLE
Cannot Load on Kali 64

### ISSUE THREAD

**Issue by Jyffeh** [ValveSoftware/steam-for-linux#4266]
"You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6"

**Comment by sizeofbool** [comment]
You have to install multiarch support package for your distro, and also install necessary 32-bit libraries, to be able to play 32-bit games.

**Comment by Ancurio** [comment]
From the readme:

    Steam for Linux requires the following:
    ...
    Ubuntu 12.04 LTS, fully updated

**Comment by gdrewb-valve** [comment]
Steam is a 32-bit app so this is expected, closing.
