### ISSUE TITLE
Can't type some special characters in Steam Overlay

### ISSUE THREAD

**Issue by gr0ebi** [ValveSoftware/steam-for-linux#4267]
I'm on Debian 8 x64, using XFCE with German Keyboard and got Steam working yesterday.
Today I noticed, when playing Dota 2 and opening the Steam Overlay, I can't write some special characters (like Shift+3 for '§') and also some language specific mutations like "ä,ö,ü".
My `/etc/default/locale` looks like this:

```
LANG="de_AT.UTF-8"
LANGUAGE="de_AT:de"
```

If I chat over Steam without the Steam overlay, I can write all of this characters.
Edit:
Shift+2 for "
Shift+4 for $
Shift+5 for %
are all working btw

**Comment by steffenWi** [comment]
This is still an issue. For me it's äöüß and @ that aren't working.

**Comment by kisak-valve** [comment]
Closing as a duplicate of #2122.

**Comment by kattmat3** [comment]
Still an issue latest version of Steam while playing ARK on Fedora WS 35.

**Comment by retlok** [comment]
Still a problem in latest version of steam while playing any game on Windows 11 with an Azerty keyboard.
