### ISSUE TITLE
Steam fails to start on debian testing

### ISSUE THREAD

**Issue by lakeman** [ValveSoftware/steam-for-linux#4269]
Updating steam dialog flashes up and disappears. No other UI appears. Some time later the steam process dies.

```
../common/pipes.cpp (739) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (739) : Fatal assert failed: ../common/pipes.cpp, line 739.  Application exiting.

Assert( Assertion Failed: fatal stalled cross-thread pipe ):../common/pipes.cpp:739
```

Started failing after installing package updates and reboot. Full error.log and recently installed packages;
https://gist.github.com/lakeman/7a290958bdfa7a785b0a

I've tried forcing steam to update itself. Downloaded 200Mb-ish of updates, but the problem persists.

**Comment by Tele42** [comment]
from the error log "
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc" is potentially where the problem is starting

**Comment by lakeman** [comment]
Those messages come from running grep and awk in check_shared_libraries() after LD_LIBRARY_PATH has changed. 
$ ldd `which grep`
Shows dependencies in /lib/x86_64-linux-gnu. If I clone steam.sh and add the following;
```
export LD_LIBRARY_PATH="/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
```
Those warnings disappear, but steam still fails to start.

**Comment by lakeman** [comment]
Still don't know what changed on my system to cause this problem, still crashes on startup. However I have found an ugly workaround for now.

When running steam with "DEBUGGER=gdb", the assert doesn't cause steam to crash. Whatever timeout is triggering this issue still occurs, more than once during the start up process. But steam will launch after a few minutes.

Searching online for "common/pipes.cpp" reveals logs from other people hitting the same assertion. But with the slightly more informative file path "steam_rel_client_linux[64]/build/src/clientdll/../common/pipes.cpp".

Is there anything that could be done to this code to log a more informative error on failure?

**Comment by lakeman** [comment]
Still no idea what the cause was, but the problem has disappeared & steam now starts normally.
