### ISSUE TITLE
Adjusting Taskbar settings causes Steam to crash

### ISSUE THREAD

**Issue by karai17** [ValveSoftware/steam-for-linux#4273]
## Steps to Reproduce
1. Open Steam Settings
2. Navigate to `Interface` category
3. Press `Set Taskbar Preferences` button
4. Press `OK`
## Expected Result

Dialog window disappears and settings are saved.
## Actual Result

Dialog window disappears, Steam locks up and then closes without saving settings.
## System Information

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 23 (Twenty Three)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.3-300.fc23.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11800000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 550 Ti/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 358.16
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1244
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3000 x 1920
Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                        52.1cm x 29.3cm  (59.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: USB Mixer

Memory:
    RAM:  11986 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  412312 Mb
    Largest Free Hard Disk Block:  385764 Mb

Installed software:

Recent Failure Reports:
    Sat Jan 23 02:12:29 2016 GMT: file ''/tmp/dumps/assert_20160118023716_1.dmp'', upload yes: ''CrashID=bp-078f62fc-0461-4443-bb49-04da02160122''
    Sat Jan 23 02:14:50 2016 GMT: file ''/tmp/dumps/assert_20160122221253_1.dmp'', upload yes: ''CrashID=bp-8483eaca-d29c-447e-aa7a-834b22160122''
    Sat Jan 23 02:19:12 2016 GMT: file ''/tmp/dumps/assert_20160122221458_1.dmp'', upload yes: ''CrashID=bp-df99ad36-7d7f-4897-925d-339582160122''

**Comment by Tele42** [comment]
There is a known issue with nvidia 358, retest with another driver version.

**Comment by kisak-valve** [comment]
Hello @karai17, are you still experiencing this issue on an up to date system?

**Comment by karai17** [comment]
I don't think I've seen this issue in a while, no.

**Comment by kisak-valve** [comment]
Thanks for the feedback @karai17, closing.
