### ISSUE TITLE
[Steam Controller] Disconnecting controller and reconnecting causes gamepad emulation to stop working

### ISSUE THREAD

**Issue by GhostSquad57** [ValveSoftware/steam-for-linux#4277]
Title says it all.

Here's a video demonstration: https://www.youtube.com/watch?v=bnCaWu-5Y2c

-Arch Linux
-Latest Steam beta + latest controller firmware
-Intel i7-4790k
-Nvidia GTX 970 w/ latest drivers

**Comment by Plagman** [comment]
That happens if the game doesn't support hotplugging controllers, but it should be similar to disconnecting and reconnecting a wired Xbox360 controller.

**Comment by GhostSquad57** [comment]
Someone commented on my video with a fix:
Arch's Steam package has a different udev  perms file
>#USB devices
>SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0660", TAG+="uaccess"
>KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess"

Changing it to:
># This rule is needed for basic functionality of the controller in Steam and keyboard/mouse emulation
>SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
>
># This rule is necessary for gamepad emulation; make sure you replace 'pgriffais' with a group that >the user that runs Steam belongs to
>KERNEL=="uinput", MODE="0660", GROUP="pgriffais", OPTIONS+="static_node=uinput"

as mentioned here: https://steamcommunity.com/app/353370/discussions/0/490123197956024380/#forum_op_490123197956024380

Fixed the issue.
