### ISSUE TITLE
Cannot start Borderlands 2

### ISSUE THREAD

**Issue by d3rrial** [ValveSoftware/steam-for-linux#4286]
I can't start Borderlands 2 from within Steam.

I can run it just fine when I start the binary directly from console, but then I don't have the steam overlay, savegames or network functionality.
When I hit "play" in steam, the steam launcher starts, my online status turns green and changes to "in game" and then it immediately turns blue again and removes my in game status.

The console from which I started steam is telling me about some errors regard ELF classes and drirc.d files, but those are unrelated to Borderlands 2, because as I've said previously I can start the game just fine.

Edit:
I now found out that, even tho I can't start it *through* steam, Steam still detects when I start the game manually and changes my status. I can also use ingame functionality for matchmaking, so steamworks isn't entirely broken for this game. The big thing I'm missing is the Steam Overlay.

**Comment by Thermionix** [comment]
I've had to `SET LAUNCH OPTIONS...` (under game properties in steam) to `SSL_CERT_DIR="/etc/ssl/certs" LD_PRELOAD='./libcxxrt.so:/usr/$LIB/libstdc++.so.6' %command%` to get my game to launch within steam

I was getting errors along the lines of `Symbol '_ZTVN10__cxxabiv120__si_class_type_infoE' has different size in shared object, consider re-linking`
