### ISSUE TITLE
Big Picture mode much slower/lower quality

### ISSUE THREAD

**Issue by mcoumans** [ValveSoftware/steam-for-linux#429]
Steam in BigPicture mode is much slower: TF2 plays 50-60 fps in normal mode, 12-15 fps in BigPicxture.

Also, when checking settings it recommends 720p graphics and lists my GPU as ATI Technology Inc 268,44 MB, whereas I have an Asus RadeonHD 6770 (with latest beta Catalyst drivers).

Processor Information:
    Vendor:  AuthenticAMD
    Speed: 3200 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 14 Nadia (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.7.0-7-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11300902

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6700 Series 

```
Driver Version:  4.2.11986 Compatibility Profile Context
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x68ba
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20,39" x 12,76"  (24,02" diag)
                                        51,8cm x 32,4cm  (61,0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7819 Mb

Miscellaneous:
    UI Language:  English
    LANG:  nl_NL.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  466109 Mb
    Largest Free Hard Disk Block:  133969 Mb

Installed software:

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by ksthiele** [comment]
@kisak-valve I don't, it got a lot better for me

**Comment by Tak** [comment]
Seems resolved here.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing due to multiple confirmations.
