### ISSUE TITLE
BPM needs links to game's Store page

### ISSUE THREAD

**Issue by adolson** [ValveSoftware/steam-for-linux#4290]
Big Picture used to have a way to access a game's Store page from the game's Library page, but this was removed sometime around the redesign. It would be nice to have it back, for fast access to DLC, purchasing gift copies, and so on.

**Comment by gdrewb-valve** [comment]
This repo is for Linux issues but leaving open for now.

**Comment by adolson** [comment]
Sorry... Where can I request features not Linux-specific?

**Comment by gdrewb-valve** [comment]
The steampowered.com forums cover pretty much anything.

**Comment by adolson** [comment]
This has been incorporated in the most recent beta. Thank you!
