### ISSUE TITLE
[Vulnerability] Chromium runs with --no-sandbox

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4293]
Chromium runs with --no-sandbox by default on steam

**Comment by ekaris** [comment]
http://www.ghacks.net/2016/02/08/steam-uses-insecure-out-of-date-chromium-browser/

**Comment by Plagman** [comment]
We're looking into how to best enable the sandbox, but it's not currently possible on certain distributions based on what what sort of namespacing they allow for unprivileged users. Thanks!

**Comment by lucasduffey** [comment]
so it's not solved then

**Comment by lucasduffey** [comment]
should be left open as this is still unsolved
