### ISSUE TITLE
Source engine games are mute with ALSA 1.1

### ISSUE THREAD

**Issue by ltworf** [ValveSoftware/steam-for-linux#4296]
I have gotten an upgrade of ALSA and all the source engine games are mute.

If I downgrade ALSA (just the userland, no need to touch the kernel) then they work again.

```
SDLAUDIO: SDL_OpenAudioDevice() failed: ALSA: Couldn't open audio device: Invalid argument
```

I get this error message on the console.

**Comment by Tele42** [comment]
Duplicate of #4139.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
