### ISSUE TITLE
Steam is incredibly slow on Ubuntu 15.10 / 64

### ISSUE THREAD

**Issue by soerenkampschroer** [ValveSoftware/steam-for-linux#4298]
Steam starts up fine, the login screen works perfectly. But as soon as I'm logged in, Steam starts to become unresponsive. I can click on things but it takes about 30 seconds to register and the notifications freeze as well.

I have a GTX670, tried driver versions 340.96 and 352.63. See attached the contents of error.log.

http://pastebin.com/hCt9gbVN

Lines 248 - 254 start repeating until I quit Steam.

Any advice? Thanks!

**Comment by MarkSill** [comment]
I had a similar issue with 14.04 until I switched to Xubuntu 15.10. Haven't had the problem since.

**Comment by L1ghtn1ng** [comment]
@soerenkampschroer try adding this PPA https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa I use this and I get the latest stable update of the driver which is 361.xx @gdrewb-valve Would be good if this ppa was in steamOS

**Comment by gdrewb-valve** [comment]
The Steam team is the group that would make any decisions about inclusion in SteamOS. They see this and they can consider it.

**Comment by soerenkampschroer** [comment]
@L1ghtn1ng Thank you for the advice. It has gotten somewhat better. The time windows where steam unfreezes are a little bigger, but the problem is essentially the same. I'm on 361.28 now.

[New error.log](http://pastebin.com/B6d4dLDV)

**Comment by L1ghtn1ng** [comment]
Try running sudo apt-get remove --purge steam then in your home directory sudo rm -rf .steam Then sudo apt-get update then install steam and see if that helps. Also looks like you are using a different theme. Try also changing that and report back

**Comment by soerenkampschroer** [comment]
@L1ghtn1ng 
I reinstalled steam and set my gtk and gnome-shell theme to default: Steam is still freezing..

**Comment by soerenkampschroer** [comment]
I uninstalled flash: no change.

Installed steam_latest.deb, still freezing. [New error log. ](http://pastebin.com/fnwhvfYJ)

**Comment by soerenkampschroer** [comment]
After a reinstall of Ubuntu GNOME it's working. No idea what caused it to begin with, but the log messages from my first post are gone as well.
