### ISSUE TITLE
Steam exits when WSALookupServiceBegin returns an error value.

### ISSUE THREAD

**Issue by RomanHargrave** [ValveSoftware/steam-for-linux#4299]
This is causing issues launching steam on Wine, as the Wine implementation is a constant function that returns `SOCKET_ERROR` (`8`).

**Comment by Tele42** [comment]
Any issues with the windows steam client that occur with wine but not a windows installation should be directed at the wine bug tracker. To the best of my knowledge, valve does not provide any support towards steam for windows on wine.

**Comment by RomanHargrave** [comment]
I posted there before here. I figured that I would post it here too, because up to now, this message was logged by steam but did not appear to be critical, e.g. Steam continued to run without issue.

**Comment by gdrewb-valve** [comment]
In addition to what Tele42 said this repo is for the Linux and Mac Steam clients, not the Windows client.  You can go to the regular steampowered.com forums if you want to ask about the Windows client.
