### ISSUE TITLE
Some games won't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by ZwS** [ValveSoftware/steam-for-linux#4301]
Some games crashes (I tested on Don't Starve, Don't Starve Together and Sigils of Elohim) on startup on Ubuntu 16.04. They just crashing with segmentation fault.
I found that removing ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.2 fixes this issue.

**Comment by Tele42** [comment]
Duplicate of #4139.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
