### ISSUE TITLE
The Book of Unwritten Tales 2: Crash on launch

### ISSUE THREAD

**Issue by Happy-Ferret** [ValveSoftware/steam-for-linux#4304]
When I try to launch the game through the Steam client or through the shell, I see a black screen for approximately half a second, then am booted back to the desktop. 

It worked one time prior but after I quit and relaunched it went back to this weird behaviour. 

I already re-installed it today, hoping I could watch the directory via inotify and trigger that one successful launch, figuring out where the difference between a successful and unsuccessful launch lie and whether Steam or game add any files that may block proper execution. 

Unfortunately, I can't seem to trigger a successful launch again, ever.

No segfault or anything else is reported aside of the usual /dev/input/js0 misreport<sup>[1](#foot)</sup>
 that is Unity3D specific.
#### **My computer**:

```
Ubuntu 16.04 x64 (11 days old daily build with all the recent updates) 
RAM: 16GB DDR3-1600
CPU: Intel i5 2500k@Stock
GPU: NVIDIA Geforce GTX 680 2GB
```
#### **GPU Driver info (NVIDIA Nouveau drivers):**

```
OpenGL renderer string: Gallium 0.4 on NVE4
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.1.1
OpenGL version string: 3.0 Mesa 11.1.1
```

<br>
<br/>

**Do note that I'm already aware of the issues with `libasound.so.2`. Removing this lib, unfortunately, did nothing for this particular game, so this might not even be related to that.**

<br>
<br/>
<br>
<br/>
<br>
<br/>

<a name="foot"><sup>_1_</sup></a><sup>_:`Too many axes; using axes 0 - 19 and ignoring axes 20 - 36: Too many buttons; using buttons 0 - 19 and ignoring buttons 20 - 68"`_</sup>

**Comment by gdrewb-valve** [comment]
You'll want to report this to the game developer also.

**Comment by Happy-Ferret** [comment]
Already added it to the developer's Steam group.

**Comment by Happy-Ferret** [comment]
In case it matters, 
here's the execute line from my steam.desktop shortcut. 

```Exec=env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/lib/libsteam_api.so /usr/$LIB/libasound.so.2' DISPLAY=:0 steam```

**Comment by Happy-Ferret** [comment]
I just replaced the whole ```plugins``` folder with the one provided by Among the Sleep. 
It works now. Still have to investigate which library was actually the faulty one. I only know it couldn't have been libsteam_api.so, as I already replaced that one previously.

**Comment by SAC-01** [comment]
I think I have a simmiliar Problem on debian testing. Since a few days I cant lauch any game that is installed over steam. I also tried it with new installed games - same problem. Reinstalling steam didn't take any effect. I think the problem started after some regular systemupdates in the last days, but can't locate wich update it might have been

Wich logfiles can i provide for this issue?
Wehre can I get the plugin foler Happy-Ferret used to replace?

Thanks 
SAC-01

My System:
debian testing 
Linux version 4.3.0-1-amd64 
NVIDIA Corporation GK208M [GeForce GT 730M]
Intel Corporation 4th Gen Core Processor Integrated Graphics Controller
Using nouveau-driver

**Comment by Happy-Ferret** [comment]
Can you try launching Steam from the commandline with the following line?

```LD_PRELOAD='/usr/$LIB/libasound.so.2' DISPLAY=:0 steam```

**Comment by SAC-01** [comment]
Thanks for your support. Launching steam by this way works fine :-)

**Comment by Happy-Ferret** [comment]
You're welcome! Happy it's working properly now. 

If you have a shortcut you normally start Steam from, you can edit the existing Exec line inside the .desktop file to look like this. 

```Exec=env LD_PRELOAD='/usr/$LIB/libasound.so.2' DISPLAY=:0 steam```

**Comment by Happy-Ferret** [comment]
@Plagman 

Feel free to close the ticket at any time.

I can pretty much rule out any fault at Steam's end and have already contacted the developer through the email address on their website, proposing a fix.

**Comment by kisak-valve** [comment]
Hello @Happy-Ferret, since this issue report was last commented on, Steam's handling of the Steam runtime has changed to prefer host libraries over the runtime variants. Are you still experiencing this issue on an up to date system and no LD_PRELOAD workaround?

**Comment by Happy-Ferret** [comment]
@kisak-valve 

Haven't played a video game in a while. Especially not the one in the OP, and not on Linux.
I'll try next time I boot into Linux and get back to you.

I assume LD_PRELOAD is no longer needed though. I have read about Steam's change of runtime behavior.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
