### ISSUE TITLE
[Vulnerability]  Chromium runs with --enable-system-flash

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4305]
Flash is a deprecated technology and valve doesn’t use it in it's websites, besides most major websites are now using HTML5 making this a needless possible security problem if flash is installed on the host.

**Comment by Plagman** [comment]
Some of the store trailers can use flash if available, and a lot of third-party websites do still rely on it, sometimes with no alternative, so this is by design. You can use our browser to navigate to third-party websites through the overlay or Big Picture.
