### ISSUE TITLE
Latest steam client beta use big picture overlay broken on Linux

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4309]
Just to let you know, this latest steam client beta: http://steamcommunity.com/groups/SteamClientBeta/announcements/detail/907842849554681945?utm_source=dlvr.it&utm_medium=twitter

The option to use big picture overlay doesn't actually work on Linux, the properties on a game has a new lonely checkbox, but it does nothing:
https://www.gamingonlinux.com/articles/steam-beta-adds-hardware-accelerated-encoding-for-nvidia-on-linux-steam-controller-major-update.6633

**Comment by NaughtySquid** [comment]
Updated:

The option to configure the controller from a "desktop library context menu" doesn't exist on Linux either.

**Comment by NaughtySquid** [comment]
Another update: Okay so editing the config does work, but there definately isn't a way to get the desktop client to launch with big picture overlay as the changelog says on Linux.

**Comment by Plagman** [comment]
You have to have a Steam controller active for the config editor option to be present, but the overlay option is disabled right now on Mac and Linux due to focus tracking bugs in SDL preventing it from working properly. This was originally specified in the beta release notes, but got lost in translation, sorry for the mixup.

**Comment by NaughtySquid** [comment]
I see, any word on when those might be looked into?

**Comment by DelusionalLogic** [comment]
Is this still the case? I still can't get the controller overlay to work at least (even though the regular overlay works fine).

**Comment by her001** [comment]
This is still the case. To get the Big Picture Mode overlay on Linux, you need to use BPM for now.

**Comment by DelusionalLogic** [comment]
Thanks, knowing that i can get it from BPM is helpful. At least i don't have to quite the game to configure the controller constantly like this.

**Comment by Myrddin-Wyllt** [comment]
The global setting now works, the overlay is functional; however input is broken in every game I've tested. Haptic feedback is missing, so configurations aren't loading properly.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? It looks like #7727 was recently opened for the follow up issue.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as fixed some time ago.
