### ISSUE TITLE
[FIXED] New beta update broke russian language in menu

### ISSUE THREAD

**Issue by lexxus-lex** [ValveSoftware/steam-for-linux#4310]
Look my pic :)

Ubuntu 15.10 (64 bit)

<a target="_blank" href="http://itmages.com/image/view/3862788/f1d542b4"><img src="http://storage6.static.itmages.com/i/16/0210/s_1455115512_8576873_f1d542b4f1.png" /></a>

**Comment by kergalym** [comment]
![steam](https://cloud.githubusercontent.com/assets/9489149/12950843/6a815d98-d039-11e5-8281-3cd2a05200e2.png)

I don't confirm on Gentoo 64-bit

**Comment by lexxus-lex** [comment]
у тебя не бета ;)

**Comment by TyanNN** [comment]
Manjaro 64-bit, same 
![image](http://i.imgur.com/SVcLhVu.png)
![image](http://i.imgur.com/fuaTFWZ.png)

**Comment by lexxus-lex** [comment]
now been beta update, bug not fix

**Comment by lexxus-lex** [comment]
now update beta, bug not fixed

**Comment by seddor** [comment]
Ubuntu 15.10 64 
![2016-02-15 22-56-19](https://cloud.githubusercontent.com/assets/4966083/13058903/837cd79e-d437-11e5-9f16-7d984a25d78c.png)

**Comment by overcrook** [comment]
Xubuntu 14.04 x64, same behavior, latest beta version.
![steam](https://cloud.githubusercontent.com/assets/3685897/13096885/bef10010-d52d-11e5-8b2e-c0b2f61159d5.png)

**Comment by lexxus-lex** [comment]
Now been update, bug not fixed

**Comment by vovochka404** [comment]
openSUSE 42.1 x64
![screenshot_20160220_092012](https://cloud.githubusercontent.com/assets/1563204/13191969/27ee74a6-d7ab-11e5-9b76-00622ad277b0.png)

**Comment by MrSchism** [comment]
It's been reviewed. Commenting every update won't really help.

When it gets fixed, they'll post here or you can close it then.

**Comment by mrdeathman** [comment]
fixed

**Comment by lexxus-lex** [comment]
bug been fixed afte new update.

Close :)
