### ISSUE TITLE
Exiting game a in Steam Big Picture Mode gets semi-windowed BPM

### ISSUE THREAD

**Issue by afettouhi** [ValveSoftware/steam-for-linux#4313]
I'm running Steam on my Arch Linux 64 bit box with a i7-2600k board and GTX 580 card and the latest Nvidia drivers (as of this writing I'm using 361.28). As my desktop I'm using KDE Plasma 5 also latest stable version available. I bought a Steam Controller a couple of months and I've been using it as my main controller with Steam Big Picture Mode. I've noticed with every game I run that if start the game from BPM that when I exit the game BPM is no longer in fullscreen and the statusbar is suddenly visible below and I have to click in the icon in the statusbar to make it go fullscreen. Not a huge issue but annoying.

**Comment by Tele42** [comment]
This sounds like it's KDE 5 not picking focus on it's own, this should also be mentioned to the KDE devs.

**Comment by afettouhi** [comment]
I will open up a bug report at kde.org and link this one to it. Thanks!

**Comment by afettouhi** [comment]
Running Steam BPM beta from March 11 and the behaviour of BPM has changed now with that version. When I exit a game I still get a semi windowed mode but now the Steam BP UI is shifted a bit upwards.

**Comment by NerosTie** [comment]
Same thing here. @afettouhi have you opened a bug report on kde.org?

**Comment by afettouhi** [comment]
@NerosTie Yeah I did open a bug report on KDE.org.

**Comment by NerosTie** [comment]
@afettouhi Found it, thank you.

**Comment by reddraggone9** [comment]
[Link to KDE bug](https://bugs.kde.org/show_bug.cgi?id=359327)

**Comment by afettouhi** [comment]
Small update on this via the above KDE bug. See this specifically this comment

https://bugs.kde.org/show_bug.cgi?id=359327#c28

**Comment by afettouhi** [comment]
Seems the conclusion in the kde.org bug report is that Steam seems to change _NET_WM_STATE for some reason.

**Comment by afettouhi** [comment]
It would be nice if someone would look into this issue now that it has been established that is a Steam issue.

**Comment by subdiff** [comment]
I've looked into this the last few days. Apparently the problem lies in SDL.

Following patch to SDL makes it work for me directly on X (SDL 2.0.9 branch):

```
diff --git a/src/video/x11/SDL_x11window.c b/src/video/x11/SDL_x11window.c
index 0a254b0..43e1bed 100644
--- a/src/video/x11/SDL_x11window.c
+++ b/src/video/x11/SDL_x11window.c
@@ -1167,6 +1167,7 @@ void
 X11_RestoreWindow(_THIS, SDL_Window * window)
 {
     SetWindowMaximized(_this, window, SDL_FALSE);
+    window->flags &= ~SDL_WINDOW_MINIMIZED;
     X11_ShowWindow(_this, window);
     SetWindowActive(_this, window);
 }
```

On Wayland an additional patch is necessary to regain focus:
https://phabricator.kde.org/D19262

**Comment by kisak-valve** [comment]
Assigning a SDL dev.

**Comment by afettouhi** [comment]
So the issue is with the sdl library within Steam for linux then?

**Comment by subdiff** [comment]
> So the issue is with the sdl library within Steam for linux then?

Yes, that's what I believe.

**Comment by DanMan** [comment]
I didn't get this when I was still using Fedora 33, but after upgrading to Fedora 35 w/ Gnome 41.1, I get this as well. 🙁

**Comment by kisak-valve** [comment]
Hello @DanMan, looking at the history on this issue report, it looks like the issue reported here was fixed by https://github.com/libsdl-org/SDL/commit/62a57970883eaee9a920e413c3686bcc7d8361cf, which made its way into SDL2 2.0.10. The Steam runtime picked up that version a long time ago (and newer since then).

Please open a new issue report so that your new issue can be tracked properly. Closing as outdated.

**Comment by bjornfor** [comment]
I'm also affected by this today, so I made https://github.com/ValveSoftware/steam-for-linux/issues/8280.
