### ISSUE TITLE
No sound since last update 

### ISSUE THREAD

**Issue by Achifaifa** [ValveSoftware/steam-for-linux#4317]
Since yesterday (I haven't played in a while so I assume this broke in the last update), I have no sound in CS:CZ (Nor CS:CZ deleted scenes). Here is the output when launching one of those games:

```
Running Steam on debian  32-bit
STEAM_RUNTIME is enabled by the user
[2016-02-14 01:19:52] Startup - updater built Feb  4 2016 12:22:08
[2016-02-14 01:19:52] Verifying installation...
[2016-02-14 01:19:52] Verification complete
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Running Steam on debian  32-bit
STEAM_RUNTIME has been set by the user to: /home/achifaifa/.steam/ubuntu12_32/steam-runtime
SDL_InitSubSystem(SDL_INIT_AUDIO) failed.
```

And the output when using `soundinfo` in the console in-game:

```
]soundinfo
sound system not started
```

My laptop is not very powerful, so I can't really try this on any other game, but after looking things up and finding issue #1179 (Plus plenty of duplicates, blog entries and other issues directly related to that one) I thought it may be related to the steam client.

Im using ALSA in a 32-bit debian testing machine.

I've tried the two major solutions to that issue. 
- Setting the `STEAM_RUNTIME` env variable to `0`: Steam did not start (No message, it just shuts down)
- Setting the `SDL_AUDIODRIVER` env variable to `alsa`: No visible effect

I'm not sure if this issue is the same as #1179 or something different (That one was almost 3 years ago and it seems weird the exact same thing would have failed now), so opening this just in case. 
Let me know if there is anything I can do.

**Comment by gdrewb-valve** [comment]
There are a number of sound issues here, many to do with Steam runtime incompatibility.

**Comment by kisak-valve** [comment]
Hello @Achifaifa, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
