### ISSUE TITLE
100% reproducible segfault in libnm if new network device is added/removed

### ISSUE THREAD

**Issue by matevarga** [ValveSoftware/steam-for-linux#4318]
I am using Docker for development and that adds/removes new veth devices on demand. Any time this happens, Steam (the app or a game) dies.

Environment:
- actual distro doesn't matter, reproduced both on Ubuntu and on Arch
- kernel 4.1

[stack.txt](https://github.com/ValveSoftware/steam-for-linux/files/130949/stack.txt)

**Comment by RamchandraApte** [comment]
Steam uses an ancient version of NM .so pre-packaged in .steam, that's probably why.

**Comment by kisak-valve** [comment]
Hello @matevarga, since this issue report was last commented on, Steam's handling of the Steam runtime has changed to prefer host libraries over the runtime. Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
