### ISSUE TITLE
No sound in steam (voice/music player) and some games (TF2/CS:GO) but sound in steam store and other games.

### ISSUE THREAD

**Issue by GuilloOme** [ValveSoftware/steam-for-linux#4320]
What I did: plug my TV to my laptop to play, unplug afterwards and, since then, no more sound.

Seems NOT related to any steam client update.

The sound in steam looks muted but only for:
- Voice in (the voice out is ok because my friend can here me)
- Steam music player
- Microphone tester (the meter is reacting to my voice but nothing is "played" to the speakers)
- Valve's games that I own (TF2/CS:GO/Portal2)

Sounds is OK for:
- Steam store video
- Other games

What I tried but change nothing:
- Removing steam client completely and reinstall:
  - `$ aptitude purge steam`
  - `$ rm -fr ~/.local/share/Steam ~/.steam`
  - `$ aptitude install steam`
  - re-install my games in steam client
- Running steam client with:
  - `$ SDL_AUDIODRIVER=alsa steam`
  - `$ AUDIODEV=xxx steam` with `xxx` from `$ aplay -l` [https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#No_audio_4]
  - `$ STEAM_RUNTIME=0 steam` [https://wiki.archlinux.org/index.php/steam#Using_native_runtime]

System info from steam client:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3400 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.2.0-27-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 765M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.79
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x11e2
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 11.57" x 6.50"  (13.27" diag)
                                            29.4cm x 16.5cm  (33.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  15974 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  199524 Mb
    Largest Free Hard Disk Block:  15936 Mb

Installed software:

Recent Failure Reports:

```

**Comment by gdrewb-valve** [comment]
So sound worked properly everywhere prior to unplugging the TV?

**Comment by GuilloOme** [comment]
yes, it was.
(Actually, I can't tell for the music player because I didn't use it often).

**Comment by GuilloOme** [comment]
Here is the workaround I found:

1. plug my computer back to the TV
2. go in my sound configuration panel
3. switch from HDMI output to analog output (so the sound get out from my laptop speaker/headphones)
4. unplug my computer from the TV
5. enjoy sound in my games !!

Looks like that if we do not switch back to analog output before unplugging the TV, the Steam client do not notice the change and keep send the sound through the wrong output. 
And, since there was nothing connected to my HDMI, I wasn't able to "force" switch back to my analog output (can't get to HDMI and back to analog to reset the settings of my steam client)

**Comment by kisak-valve** [comment]
Hello @GuilloOme, are you still experiencing this issue on an up to date system?

**Comment by GuilloOme** [comment]
Sorry, I don't have any system that I could use to test it again… Thanks for the follow up!

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing per the last comment.
