### ISSUE TITLE
Segfaults on fedora (in relation to in-home-streaming)

### ISSUE THREAD

**Issue by Rabcor** [ValveSoftware/steam-for-linux#4323]
I have not found a precise way to reproduce this issue, but I am streaming from a windows pc to my fedora workstation from time to time, and these segfault seem to frequently happen either after those sessions, or when I launch the streaming. I'm streaming usually non-steam applications.

I'm running a currently up to date fedora 22 workstation (cinnamon flavor), intel Sandy Bridge CPU and a GTX 550-Ti Graphics Card on the proprietary nvidia drivers (I would be using nouveau but it was causing problems with this card for some reason; crashes and freezes. Performs fine under nvidia proprietary drivers besides clocking itself a bit too high and running a bit hot from time to time for menial tasks) installed through rpmfusion repositories. This has been going on for a few weeks, or ever since I switched to fedora.

This is the generated error output in terminal:

```
Generating new string page texture 153: 16x256, total string texture memory is 3.47 MB
assert_20160217192918_1.dmp[29443]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160217192918_1.dmp
/home/cestarian/.local/share/Steam/steam.sh: line 756:  3883 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
assert_20160217192918_1.dmp[29443]: Finished uploading minidump (out-of-process): success = yes
assert_20160217192918_1.dmp[29443]: response: CrashID=bp-ef7482a7-3b24-48d8-8cbd-8ced42160217
assert_20160217192918_1.dmp[29443]: file ''/tmp/dumps/assert_20160217192918_1.dmp'', upload yes: ''CrashID=bp-ef7482a7-3b24-48d8-8cbd-8ced42160217''
```

[Here is the .dmp file](https://www.mediafire.com/?36rfys44azuylx7); can't read it myself though, so I have no idea what's what.

The problem may be SELINUX related (although I've had no SELINUX warnings that seemed related). After launching steam again after this crash occurs I frequently get the following error:

`CAPIJobRequestUserStats - Server response failed 2
`
And the program can crash again. In this particular crash case, the windows machine's steam was actually turned off and the linux steam failed to dectet that it was so, so it crashed when I tried to start a stream.

**Comment by Rabcor** [comment]
I found that this crash may not be related to in-home streaming after all, steam is sometimes crashing completely randomly, and I also noticed it may crash when setting a game's category in the library. (I was on a relatively fresh setup of fedora when I was trying to stream initially)

Still no solid way to reproduce this error, but  if I launch steam and open my friends list, then try to talk to someone right afterwards, it will commonly crash right there and then.

**Comment by Tele42** [comment]
@Rabcor what version of the nvidia driver are you using?

**Comment by Rabcor** [comment]
@Tele42 I am using version 358.16

**Comment by kisak-valve** [comment]
Hello @Rabcor, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as general video driver quality from 2016 is no longer relevant.
