### ISSUE TITLE
[Left 4 Dead 2] Speaker setting reverts to 5.1 channels every time

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#4325]
From https://github.com/ValveSoftware/steam-for-linux/issues/4113#issuecomment-157600002:

> it seems to not be saving my speaker settings, so every time I start, it sets it back to 5.1 rather than headphones, and I have to change that in the sound menu (then set my voice_scale again) before joining a game; if I do it in game, voice chat stops.

**Comment by steamlinux** [comment]
I have the same problem
and with setting "speaker 5.1" sound is heard from 2 speakers
with setting "speaker 3" sound is heard from 6 speakers (5.1)

**Comment by Joeppie** [comment]
I have this problem, and when I change from 5.1 speakers to headphones, my Left4Dead2 in-game microphone stops working until the next level loads. Every time I start the game, it is reverted to 5.1 speakers.

**Comment by undeference** [comment]
Does that happen when you change it before joining a game?
> I have to change that in the sound menu… before joining a game; if I do it in game, voice chat stops.

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2000.

**Comment by vitacell** [comment]
This bug is affecting me right now. And still they did not fix it.
