### ISSUE TITLE
Latest Steam Beta breaks X-COM: Enemy Unknown and Enemy Within

### ISSUE THREAD

**Issue by Polochamps** [ValveSoftware/steam-for-linux#4326]
Launches game with sound but no video.

Ubuntu 15.10 
Nvidia 352.63
GeForce GTX 660Ti

System:    Kernel: 4.2.0-27-generic x86_64 (64 bit)
                 Desktop: Unity 7.3.3  Distro: Ubuntu 15.10 wily
Machine:  System: ASUS product: All Series
                 Mobo: ASUSTeK model: MAXIMUS VI IMPACT v: Rev 1.xx
                 Bios: American Megatrends v: 1603 date: 08/15/2014
CPU:         Quad core Intel Core i5-4670K (-MCP-) speed/max: 3400/3800 MHz
Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
                 Card-2: NVIDIA GK104 [GeForce GTX 660 Ti]
                 Display Server: X.Org 1.17.2 driver: nvidia
                 Resolution: 1920x1080@60.00hz
                 GLX Renderer: GeForce GTX 660 Ti/PCIe/SSE2
                 GLX Version: 4.5.0 NVIDIA 352.63
Network:   Card-1: Intel Ethernet Connection I217-V driver: e1000e
                 Card-2: Broadcom BCM4352 802.11ac Wireless Network Adapter
                 driver: wl
Drives:     HDD Total Size: 820.2GB (62.7% used)
Info:         Processes: 231 Uptime: 4:19 Memory: 2226.1/7666.7MB
                Client: Shell (bash) inxi: 2.2.16 

https://www.reddit.com/r/linux_gaming/comments/46l7fn/heads_up_latest_steam_beta_breaks_xcom_enemy/

**Comment by dhollinger** [comment]
I can verify this as well.

Ubuntu 15.10
Nvidia 361.28
GeForce GTX 850m

**Comment by linuxgamer91** [comment]
Same Issuses with GRID Autosport on SteamOS, Audio works but no Video.

**Comment by Plagman** [comment]
We're looking into this, thanks.

**Comment by Plagman** [comment]
Can you confirm this is now fixed in tonight's update?

**Comment by her001** [comment]
I can confirm that the update fixed GRID: Autosport for me.

**Comment by salamanderrake** [comment]
I have audio but the graphics freeze with a 'screen shot' of the desktop.

**Comment by salamanderrake** [comment]
Ubuntu 15.10. 

System Specs:
https://gist.github.com/salamanderrake/935ecc98805b0bfcd890

**Comment by linuxgamer91** [comment]
GRID Autosport and XCOM works now after Steam Update on SteamOS.

**Comment by johnv-valve** [comment]
Fixed in the latest beta update https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/907844028509521842
