### ISSUE TITLE
Vulkan loader (from the steam runtime) ignores ICD in /usr/share/vulkan/icd.d

### ISSUE THREAD

**Issue by Jajcus** [ValveSoftware/steam-for-linux#4328]
According to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/sdk-1.0.3/loader/LoaderAndLayerInterface.md, the Vulkan loader should look for ICD configuration in  `/usr/share/vulkan/icd.d` and `/etc/vulkan/icd.d`, but the loader included in steam runtime seems to look only into `/etc/vulkan/icd.d` (checked with strace).

Vulkan apps started from Steam won't see my Vulkan driver unless I put their ICD json file in `/etc/vulkan/icd.d`. My Linux distribution package with the driver puts the JSON file in the `/usr/share/vulkan/icd.d` directory, as suggested by the Khronos document:

> The "/usr/share/vulkan/icd.d" directory is for ICDs that are installed from Linux-distribution-provided packages.

**Comment by Plagman** [comment]
We have a fix coming for this, thanks for the report.

**Comment by Plagman** [comment]
Can you confirm the fix with tonight's update?

**Comment by mrdethman** [comment]
How start Steam on Vulkan API ?

**Comment by Jajcus** [comment]
> Can you confirm the fix with tonight's update?

Yes, it is working now.
