### ISSUE TITLE
Dying light, cities skylines and NeonXSZ broken without this workaround on newer distros

### ISSUE THREAD

**Issue by NaughtySquid** [ValveSoftware/steam-for-linux#4329]
It seems on newer distributions (Ubuntu 16.04 64bit for me), Dying light, cities skylines and NeonXSZ are all broken unless you run Steam like so:
`LD_PRELOAD='/usr/$LIB/libasound.so.2 '${LD_PRELOAD} steam`

Is this a Steam issue, or a bug I need to report somewhere else?

Thanks to this reddit comment: https://www.reddit.com/r/linux_gaming/comments/46sske/cities_skylines_crashing_on_launch/d07ljf9

**Comment by NaughtySquid** [comment]
Looks like these are related:
https://github.com/ValveSoftware/steam-for-linux/issues/4319
https://github.com/ValveSoftware/steam-for-linux/issues/4322
https://github.com/ValveSoftware/steam-for-linux/issues/4304

**Comment by Tele42** [comment]
Duplicate of #4139.

**Comment by NaughtySquid** [comment]
@Tele42 which seems to be a dupe of https://github.com/ValveSoftware/steam-for-linux/issues/4304

**Comment by IdleGandalf** [comment]
It's even older than that: dup of #3443

**Comment by NaughtySquid** [comment]
Fixed in latest beta client.
