### ISSUE TITLE
[Counter-Strike] Thick red line

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#4331]
I've noticed that this happens on Catalyst, but not on Radeon. Whenever I open Counter Strike (or any Gold-Source VALVe game) in a lower resolution that what my desktop uses, a thick red stripe appears on the monitor.

Since I couldn't take a screenshot of it, I took a photo instead.

Image: http://i.imgur.com/7RRNXgW.jpg

My desktop is in 1280x1024, and Counter-Strike must be in 1024x768.

This happens on Debian Jessie (Catalyst 15.9.4) and Arch (Catalyst 15.12), and probably on every other distro.

I'm using Debian Jessie;
Catalyst 15.09.4
Counter-Strike 1.6

**Comment by amarildojr** [comment]
BTW, this doesn't happen on openSUSE (Catalyst 15.30).

@gdrewb-valve , I also forgot to mention that you must set "Low Video Quality" on Counter-Strike in order for this to happen.

**Comment by kisak-valve** [comment]
Hello @amarildojr, Catalyst has been obsoleted by mesa and AMDGPU-PRO. If you're still experiencing this issue on an up to date system, please open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker.

Closing as general video driver quality from 2015 is no longer relevant.
