### ISSUE TITLE
News categories for games do not filter (or filter nothing)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4332]
News categories for filtering do not work; see image below.

The only one that works is All News. This is for all games.

![selection_001](https://cloud.githubusercontent.com/assets/7646510/13229838/bb15914e-d970-11e5-8c51-8ac7bdb3a488.png)
![selection_001](https://cloud.githubusercontent.com/assets/7646510/13229856/d7020d92-d970-11e5-8435-1ac26327d05f.png)
![selection_001](https://cloud.githubusercontent.com/assets/7646510/13229886/f4da31a0-d970-11e5-8842-1eb5b93f6992.png)
![selection_001](https://cloud.githubusercontent.com/assets/7646510/13229904/0b666f92-d971-11e5-94b3-7e46f4d5f620.png)

**Comment by kisak-valve** [comment]
Unable to reproduce and the user has turned into a ghost.
