### ISSUE TITLE
Big Picture freezes or crashes Xorg when DRI3 is enabled and user changes system volume

### ISSUE THREAD

**Issue by urbenlegend** [ValveSoftware/steam-for-linux#4333]
I can make Big Picture mode crash Xorg whenever I enable DRI3 in the Intel graphics driver and try to change my volume. I can reproduce this 100% of the time on Fedora 23.

**Steps to reproduce:**
1. Enable DRI3 for the Intel GPU (enabled by default in latest intel driver update in Fedora 23)
2. Launch Big Picture
3. Adjust system volume using volume buttons on keyboard
4. See Gnome volume OSD appear. The whole screen will start to flicker like crazy. Most likely compositor unredirection related
5. Big Picture will either crash to login screen or freeze after 5 seconds.
6. **If it freezes**, you can still hear audio and mouse clicks seem to be interacting with UI items because you can hear the interface sounds. At this point, alt-tab and force close Steam. When you force close, Xorg will crash to login screen.

Disabling DRI3 causes it to not crash.

**System Specs**

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 23 (Twenty Three)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.3.5-300.fc23.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11800000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile 

    Driver Version:  3.0 Mesa 11.1.0 (git-525f3c2)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0xa16
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 3360 x 2130
    Primary Display Size: 18.66" x 11.65"  (21.97" diag)
                                            47.4cm x 29.6cm  (55.8cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7868 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  120823 Mb
    Largest Free Hard Disk Block:  93728 Mb

Installed software:

Recent Failure Reports:
```

**Comment by Tele42** [comment]
@urbenlegend why do you think this is a steam issue and not a mesa issue? This should be reported to the freedesktop bug tracker.

**Comment by urbenlegend** [comment]
This may very well be something in Mesa, but the crash only happens with Big Picture. Any other 3D application works fine and doesn't crash. I can run Steam games just fine.

**Comment by jljusten** [comment]
@urbenlegend: Can you reproduce it with the steps in https://bugs.freedesktop.org/show_bug.cgi?id=92258#c6

I'm wondering if these issues are related.

**Comment by urbenlegend** [comment]
No, those steps work perfectly fine for me.

**Comment by jljusten** [comment]
@urbenlegend: I've tried a few things, but I can't reproduce it yet. Do you know what version of gnome you are running? I'm running 3.18.

**Comment by urbenlegend** [comment]
I am running 3.18 as well. I'll test again tonight.

**Comment by kisak-valve** [comment]
Per the [2017-01-05 steam beta update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256), does this issue still occur with the beta client?
