### ISSUE TITLE
Beta v1456366706 cannot display some letters in Hungarian

### ISSUE THREAD

**Issue by ViBENo1** [ValveSoftware/steam-for-linux#4336]
On Ubuntu 14.04 x64 a bunch of letters like "Á" "É" "Ő" "Ú" "Ű" cannot be displayed or just replaced with an "S".

![steambug](https://cloud.githubusercontent.com/assets/640109/13335524/d663d46c-dc11-11e5-85de-bb06e8cc4b62.jpg)

**Comment by gdrewb-valve** [comment]
Also #4310.

**Comment by mrdeathman** [comment]
fixed
