### ISSUE TITLE
Steam client crash after install and agree license....

### ISSUE THREAD

**Issue by AJIeKCaHDp** [ValveSoftware/steam-for-linux#4337]
Hello all, please help me resolve my problem.
I reinstall nvidia driver over 10 times and no result...
Installed libraries for x32
http://pastebin.com/d9j5rm7p

**Comment by kisak-valve** [comment]
Hello @AJIeKCaHDp, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
