### ISSUE TITLE
[SOLVED] [Steam Client] Crashing at startup - Segmentation fault, line 756 - Arch Linux

### ISSUE THREAD

**Issue by SALVOuankeBALDO** [ValveSoftware/steam-for-linux#4340]
Hello all.
Recently, after days of not booting steam (several system upgrades were done in the meantime), I've encountered problems in starting the client. With or without STEAM_RUNTIME=0, I run in the following error after starting from terminal:

```

/home/MYNAME/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable

/home/MYNAME/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable

Running Steam on arch  64-bit

/home/MYNAME/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable

STEAM_RUNTIME is enabled automatically

/home/MYNAME/.local/share/Steam/steam.sh: line 756: 11626 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

```

I've googled for the errors, and it looks like the segmentation fault at line 756 is a common issue, but there are various solutions, and I've tried several, with no luck.
I've tried

1. Removing the nvidia driver of my card, going back to nouveau (all the following actions were made with nouveau), reinstalling steam;
2. Installing steam-libs and trying to run with STEAM_RUNTIME=0 (never neeeded it);
3. Copiyng the libraries as suggested in Arch Wiki (https://wiki.archlinux.org/index.php/Steam#Native_runtime:_steam.sh_line_756_Segmentation_fault);
4. Removing mesa and reinstalling it, with all dependencies (whew!)

Nothing worked, so I'm looking for help.

Thanks in advance.

**Comment by SALVOuankeBALDO** [comment]
I've solved the problem. I removed the folder /home/USER/.local/share/Steam, uninstalled steam (I do not think it is necessary, but I did it anyway) and reinstalled it. It asked me to reinstall that folder, and updated. Now it's working. I'm marking it as solved.

**Comment by LeonardKoenig** [comment]
Remove everything except `~/.local/share/Steam/steamapps`

**Comment by Bfgeshka** [comment]
There's no need to remove everything, `config/config.vdf` is enough.

**Comment by SALVOuankeBALDO** [comment]
Thank you for your suggestions. Removing the "Remember password" flag should not help while the bug is happening, as I wasn't even able to reach the login screen. Steam crashed just after typing "steam" in the console. Now it's working fine, but next time I'll try your methods to solve it.

**Comment by C0rn3j** [comment]
In response to the command above - you need to install steam-native-runtime, not reinstall steam, as that doesn't help.

**Comment by bkdwt** [comment]
> There's no need to remove everything, `config/config.vdf` is enough.
> And ever more, seems like if you'll remove flag for remembering password at login screen steam wouldn't segfault anymore. At least works for me.
Thank you very much! This works for me on Gentoo. Unfortunately having to enter the password every time you start the app is uncomfortable, but that's the way.

**Comment by sarpik** [comment]
For anyone else coming up here - my issue was solved here: https://github.com/ValveSoftware/steam-for-linux/issues/6399#issuecomment-512867551

I needed to

```sh
sudo pacman -S lib32-nvidia-utils
```

since I didn't have'em. Leggo!

**Comment by auroraflux** [comment]
> For anyone else coming up here - my issue was solved here: [#6399 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/6399#issuecomment-512867551)
> 
> I needed to
> 
> ```shell
> sudo pacman -S lib32-nvidia-utils
> ```
> 
> since I didn't have'em. Leggo!

This worked for me (as the other stuff about the config.vdf didn't seem to apply to me because this file wasn't present on my system). I just wanted to chime in here since this is currently the top result on Google if you search for "steam.sh segmentation fault".  Installing these utils is what worked. 

Info about my setup: 

- Fully up to date ArchLinux 64-bit as of today

- Kernel: `5.5.10-zen1-1-zen #1 ZEN SMP PREEMPT`

- GPU: NVidia GTX 1080Ti

I did not install any "native runtime". I'm using just the standard `steam` package.

**Comment by robin-thoni** [comment]
Removing the `ConnectCache` entry in `config/config.vdf` is enough, although it's just a WAR...

**Comment by pueppiblue** [comment]
> Removing the `ConnectCache` entry in `config/config.vdf` is enough, although it's just a WAR...

Had the same problem on Ubuntu focal, after a steam update. Removing `ConnectCache` entry worked for me as well.

**Comment by kisak-valve** [comment]
Hello @robin-thoni, @pueppiblue, the issue you've described is being tracked at #6101 instead of this issue report.

**Comment by me4real** [comment]
> Thank you for your suggestions. Removing the "Remember password" flag should not help while the bug is happening, as I wasn't even able to reach the login screen. Steam crashed just after typing "steam" in the console. Now it's working fine, but next time I'll try your methods to solve it.

Bro I'm having this issue. How did you solve it then?
