### ISSUE TITLE
SteamCMD exit codes

### ISSUE THREAD

**Issue by dgibbs64** [ValveSoftware/steam-for-linux#4341]
Sorry if I have posted in the wrong place. However there is not a repo for SteamCMD. 

I am wondering if a Valve employee is able to provide and docs/info on the SteamCMD exit codes and there meanings. I have looked around with no luck.

I am the main developer or Linux Game Server Managers and am looking to give users better feedback when they get an error from SteamCMD.

For example many users that use SteamCMD may come across this sort of error (or variation):
    Error! App '237410' state is 0x602 after update job.

with $? returning 8

However this means nothing to an end user. Googling this error may return vague random forum posts that might not be accurate. Causing the user difficulty in resolving the issues. I want to be sure on what the errors mean and for LGSM to be able to suggest fixes. This sort of info would also be great on the Valve wiki. 

so for example error "0x602" exitcode 8 might mean low disk space

So yeah any documentation on these errors would be very beneficial to developers and users alike.

Thanks for any help you can provide.

**Comment by Royalgamer06** [comment]
Here is some that I found:

0: Success!
1: ERROR! Timed out waiting for AppInfo update.
5: Login Failure: Two-factor code mismatch (88)
5: Login Failure: Rate Limit Exceeded (84)
8: ERROR! Failed to install (No subscription).
8: Error! State is 0x402 after update job. 
8: Error! State is 0x602 after update job.

**Comment by dgibbs64** [comment]
thanks @Royalgamer06 this is a great start. I can look at adding these in to my scripts

**Comment by dgibbs64** [comment]
I don't think I will get any further with this. But I have managed to get some info. https://github.com/gameservermanagers/linuxgsm/issues/719 I will close this issue down
