### ISSUE TITLE
Overlay in Team Fortress 2

### ISSUE THREAD

**Issue by Kengur8** [ValveSoftware/steam-for-linux#4343]
Fedora 23/Gnome/radeon oss
Steam client version: 1.0.0.51-1.fc23
Opted into Steam client beta?: y

In steam settings UNCHECKED "Enable overlay". In Team Fortress 2 properties UNCHECK "Enable overlay". Playing Team Fortress 2 full screen mode native client.

Steam group events still cause messages to pop-up. Gnome desktop reacts by drawing a notification window may be? Desktop fall though at the top of the screen for a couple of seconds.

**Comment by Plagman** [comment]
Yes, that's probably just the desktop notifications rather than overlay rendering.

**Comment by Kengur8** [comment]
The problem is not the notification itself. The problem is Steam raising notification while I'm playing the game in full screen mode. Please reopen.

**Comment by Plagman** [comment]
There is no concept of exclusive fullscreen on Linux and Steam doesn't know what a particular game might be doing. You can disable friend notifications or unfollow groups that you'd like to stop receiving event notifications for.

**Comment by Kengur8** [comment]
So you mean to say glutFullScreen is a bogus? Or there's no sane way of disabling all notifications during play somehow not hindering user experience here?

**Comment by Tele42** [comment]
I'd expect the compositor of the DE would have control over this behavior if there is any control at all, not steam.
