### ISSUE TITLE
in-game overlay ignores mouse buttons

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4347]
The mouse cursor is there, I can see the buttons (the gfx widget) being enabled when I hover the cursor on them, but clicks are ignored.

I run an up-to-date steamOS beta with an up-to-date Steam beta client (steamos compositor/big picture mode).

**Comment by sharkwouter** [comment]
I have been noticing this as well with the Steam Client Beta. I don't know when this was introduced, though.

**Comment by sylware** [comment]
What's up with this issue?

Fresh install of steamOS, fresh upgrade to steamOS beta and client beta.
Bug is still there (tested with dota2 overlay)
(GFX is AMD HD 7970, default steamOS driver, and mouse is USB)

**Comment by Plagman** [comment]
Mouse clicks regressed in the Big Picture overlay across all platforms, not just Linux. It's on the list of things to fix.

**Comment by sylware** [comment]
It seems fixed in the beta client.

**Comment by Plagman** [comment]
Yes, fix was rolled out in the new Beta. Thanks for confirming.
