### ISSUE TITLE
Adding the pop-up comment translation into Steam shortcut in main menu

### ISSUE THREAD

**Issue by TotalCaesar659** [ValveSoftware/steam-for-linux#4352]
There is no translation for pop-up comment in Steam shortcut (/usr/share/applications/steam.desktop).
Quote:

> [Desktop Entry]
> Name=Steam
> Comment=Application for managing and playing games on Steam
> Exec=/usr/bin/steam %U

It should be better to add the translations for the comment to other languages. For example:

> [Desktop Entry]
> Name=Steam
> Comment=Application for managing and playing games on Steam
> **Comment[ru]=Программа для управления и запуска игр в Steam**
> Exec=/usr/bin/steam %U

It more surprises that there more strings in this file that already has translation to basic world languages. For example:

> [Desktop Action Store]
> Name=Store
> Name[de]=Shop
> Name[es]=Tienda
> Name[fr]=Magasin
> Name[it]=Negozio
> Name[pt]=Loja
> Name[ru]=Магазин
> Name[zh_CN]=商店
> Name[zh_TW]=商店
> Exec=steam steam://store

Could you fix this oversight?

**Comment by scootergrisen** [comment]
I looked at the steam.desktop file in Ubuntu and it now contains german translation for the comment:

    Comment=Application for managing and playing games on Steam
    Comment[de]=Spiele auf Steam verwalten und spielen

So have this now been fixed so people can add translations?
And if so how/where do i add translation?

**Comment by scootergrisen** [comment]
It seems translations have now been added to steam.desktop so this issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
