### ISSUE TITLE
[Big Picture] Randomly, the back button will stop working.

### ISSUE THREAD

**Issue by aaronfranke** [ValveSoftware/steam-for-linux#4354]
The only solution I've found is to use the mouse to click the Steam logo in the top left to return to the top menu. When using the mouse to click the back button in the very top left or pressing the "Escape" key, nothing happens.

**Comment by kisak-valve** [comment]
Hello @aaronfranke, are you still experiencing this issue on an up to date system?

**Comment by aaronfranke** [comment]
I can't reproduce it anymore. It's either fixed or really good at hiding itself.

**Comment by bojanivanovic** [comment]
Hi, sorry for bumping such an old issue, but this is exactly what started happening to me. It'll work properly but then the back button stops working, rebinding doesn't help. Seems like there's not way to go back using the controller except for using the trackpad and clicking on the back button in the UI. I have to restart Steam completely for it to work again.

Running Arch + sway (wayland)
