### ISSUE TITLE
Steam hangs after hovering the mouse at drop-down menus

### ISSUE THREAD

**Issue by mradermaxlol** [ValveSoftware/steam-for-linux#4357]
I get a hang after hovering the mouse near the menus like "Library", "Store", etc. The only way to fix this is to do "kill -9", because Steam stops responding completely. It's been happening since the last client update for Linux.  
I've encountered the bug on Ubuntu 15.10, Debian Sid, ArchLinux and Gentoo ~amd64. All my PCs use the open-source Mesa stack. I'll attach the video for you to see what's happening.

**Comment by mradermaxlol** [comment]
Here's the [video](https://drive.google.com/file/d/0ByNv_f3Uax4zcWNVRm9rZGY0MFU/view?usp=sharing).

**Comment by mradermaxlol** [comment]
Will something be done about the issue?

If you need the info, I'm using the latest X.org 1.18.2 with GNOME 3.18.4 + DRI3 on Radeon R7 370 with latest stable mesa (11.1.X) and libDRM, as well as the kernel - 4.5.0. Multilib is enabled, the required packages are installed.  
Before the update the client was working flawlessly, except one thing: I wasn't able to run 7 Days To Die, for example, from Steam, but I was if I ran it manually from commandline.  
I hope the issue will be fixed soon, as it's impossible to work with Steam. I've also noticed that there are similar hangs happening randomly. I can leave my PC for an hour, get back to it and notice that the client is not working.

**Comment by Tele42** [comment]
Hi, out of curiosity, does this happen with DRI2 instead of DRI3?

**Comment by mradermaxlol** [comment]
@Tele42 it's quarter to eleven (Moscow time) right now, thus I can't test it. However, I wouldn't think of it 'cause the previous version of the client worked just fine.

**Comment by mradermaxlol** [comment]
@Tele42 actually, after disabling Radeon DDX at all (thus using the Modesetting driver) it began working properly. I'm closing the issue and now I'm gonna make a bug report at freedesktop.org. Thanks!

**Comment by mradermaxlol** [comment]
Filed a bug [here](https://bugs.freedesktop.org/show_bug.cgi?id=94611).
