### ISSUE TITLE
Steam loads dual-core at 100% and slows game

### ISSUE THREAD

**Issue by sergei-swh** [ValveSoftware/steam-for-linux#4359]
Hello, with the last update Steam began to slow my laptop while running torchlight 2. Sorry, I'm rather new to Linux, so I can provide a couple of screenshots and some system info:

-Computer-
Processor       : 2x Intel(R) Pentium(R) CPU B960 @ 2.20GHz
Memory      : 3993MB (1542MB used)
Operating System        : Linux Mint 17.2 Rafaela
User Name       : sergei (Sergei Ivantsov)
Date/Time       : Fri 18 Mar 2016 10:46:30 AM KRAT
-Display-
Resolution      : 1366x768 pixels
OpenGL Renderer     : GeForce GT 520M/PCIe/SSE2
X11 Vendor      : The X.Org Foundation
-Multimedia-
Audio Adapter       : HDA-Intel - HDA Intel PCH
## Operating System

-Version-
Kernel      : Linux 3.16.0-38-generic (x86_64)
Compiled        : #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
C Library       : Unknown
Default C Compiler      : GNU C Compiler version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) 
Distribution        : Linux Mint 17.2 Rafaela
-Current Session-
Computer Name       : sergei-SWH
User Name       : sergei (Sergei Ivantsov)
Home Directory      : /home/sergei
Desktop Environment     : MATE (mate)
-Misc-
Uptime      : 1 hour, 27 minutes
Load Average        : 0,00, 0,00, 0,00

![screenshot](https://cloud.githubusercontent.com/assets/17918761/13868051/3a8230fc-ed00-11e5-84a4-8edb1a13e970.png)

**Comment by kisak-valve** [comment]
Hello @sergei-swh, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
