### ISSUE TITLE
Steam repository is insufficiently signed on Ubuntu 16.04 (and next version of Debian too)

### ISSUE THREAD

**Issue by BryanQuigley** [ValveSoftware/steam-for-linux#4364]
Error message is like:
sudo apt update
....
W: gpgv:/var/lib/apt/lists/repo.steampowered.com_steam_dists_precise_InRelease: The repository is insufficiently signed by key BA1816EF8E75005FCF5E27A1F24AEA9FB05498B7 (weak digest)

Blog post about the change:
https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/

Just FYI, There's been similar fallout in Ubuntu - https://lists.ubuntu.com/archives/ubuntu-devel/2016-March/039271.html

**Comment by mhalano** [comment]
This bug was not fixed? I don't see any warnings on my Ubuntu 16.04.

**Comment by DisDis** [comment]
+1

**Comment by neclimdul** [comment]
In the future, as a courtesy to silent subscribers, please use reactions and notifications instead of +1 comments https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by BryanQuigley** [comment]
Indeed this does appear to be fixed.  Thanks!
