### ISSUE TITLE
a few suggestions.

### ISSUE THREAD

**Issue by fishxz** [ValveSoftware/steam-for-linux#4366]
hey,
i wonder if the following problems ever get fixed? im using steam for linux quite a while now, but the following problems seems never get fixed.

- its not possible minimize steam to tray (funnily enough you can minimize the compact view to tray).
- new windows like a chat messages or any popup from steam are sized wrong in the gnome overview.
![bildschirmfoto von 2016-03-22 15-07-09](https://cloud.githubusercontent.com/assets/1385258/13954770/827b4336-f042-11e5-94b0-2368d45a121a.png)
- if you close any other steam window, e.g. a chat window over the gnome overview you close whole steam client.
- the tray use wrong skin on gnome 3.
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333234363338352f3134333534382f61643061313031632d373362302d313165322d386566312d6436626362343837343332332e706e67](https://cloud.githubusercontent.com/assets/1385258/13954755/73c4c042-f042-11e5-8d0a-462cfe485264.png)
- many steam games especially valve games use wrong icons, no icons or wrong names.
![bildschirmfoto von 2016-03-22 15-36-09](https://cloud.githubusercontent.com/assets/1385258/13955180/0307bc72-f044-11e5-8ed9-60988f4a3bf9.png)

**Comment by gdrewb-valve** [comment]
These issues are all open here.  Issues get closed when they're fixed so you can monitor them for when they're addressed.  I can't answer as to when that'll be, you just have to wait for the Steam team.
