### ISSUE TITLE
steam always crash after 10-20 min

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#4367]
my inxi -xbbb output

System:    Host: ruslan Kernel: 4.4-6.dmz.1-liquorix-amd64 x86_64 (64 bit gcc: 5.3.1)
           Desktop: Gnome 3.18.4 (Gtk 2.24.30)
           Distro: Debian GNU/Linux stretch/sid
Machine:   Mobo: ASUSTeK model: M5A99FX PRO R2.0 v: Rev 1.xx
           Bios: American Megatrends v: 2501 date: 04/07/2014
CPU:       Octa core AMD FX-8350 Eight-Core (-MCP-) speed/max: 1400/4000 MHz
Graphics:  Card: NVIDIA GK104 [GeForce GTX 660 Ti] bus-ID: 01:00.0
           Display Server: X.Org 1.18.2 driver: N/A
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 660 Ti/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 352.79 Direct Rendering: Yes
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: a000 bus-ID: 09:00.0
Drives:    HDD Total Size: 1160.2GB (53.0% used)
Info:      Processes: 246 Uptime: 1:41 Memory: 1905.6/7953.2MB
           Init: systemd runlevel: 5 Gcc sys: 5.3.1
           Client: Shell (bash 4.3.421) inxi: 2.2.28 

steam output after crash

../common/pipes.cpp (745) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
../common/pipes.cpp (745) : Fatal assert failed: ../common/pipes.cpp, line 745.  Application exiting.

_ExitOnFatalAssert

I try drivers from debian repository (352.79) and from nvidia site (352.63 352.79 358.16 361.28 364.12) and try steam beta client
I can't normal play

**Comment by steamlinux** [comment]
I play on payday 2 and have thi message
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Broken pipe).  Continuing.
../common/pipes.cpp (745) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
../common/pipes.cpp (745) : Fatal assert failed: ../common/pipes.cpp, line 745.  Application exiting.

_ExitOnFatalAssert

**Comment by steamlinux** [comment]
before I run from terminal 'steam', now I run script steam.sh
all output http://pastebin.com/VBw5ZqFz
upload dumps from this log?

**Comment by steamlinux** [comment]
I run steam debug http://pastebin.com/0zJ9wA0L

**Comment by steamlinux** [comment]
80% crash when the steam reacts with the Internet. for example starts to update the game, someone wrote me a message, someone leaves a comment and I notice comes, etc.

**Comment by steamlinux** [comment]
if I understand, this bug with new networkmanager
how to fix this?

**Comment by steamlinux** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/3959
I have same problem
steam use old network api?

**Comment by steamlinux** [comment]
I try install libnm-glib4 v.0.9.4 from debian wheeze and steam crash after 15-30 min with this log http://pastebin.com/SR68Daih
any help?

**Comment by kisak-valve** [comment]
Hello @steamlinux, are you still experiencing this issue on an up to date system?

**Comment by steamlinux** [comment]
hey again! I don't have this problem

**Comment by kisak-valve** [comment]
Thanks for rechecking, closing.
