### ISSUE TITLE
steam beta + l4d2 = Game freezes hard

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#4369]
if I run l4d2 with steam beta and minimize, game freezed and I need kill process
with steam stable game normal minimizing
This bug appeared 2-3 weeks ago

$ inxi -xbbb
System:    Host: ruslan Kernel: 4.4-6.dmz.1-liquorix-amd64 x86_64 (64 bit gcc: 5.3.1)
           Desktop: Gnome 3.18.4 (Gtk 2.24.30)
           Distro: Debian GNU/Linux stretch/sid
Machine:   Mobo: ASUSTeK model: M5A99FX PRO R2.0 v: Rev 1.xx
           Bios: American Megatrends v: 2501 date: 04/07/2014
CPU:       Octa core AMD FX-8350 Eight-Core (-MCP-) speed/max: 1400/4000 MHz
Graphics:  Card: NVIDIA GK104 [GeForce GTX 660 Ti] bus-ID: 01:00.0
           Display Server: X.Org 1.18.2 driver: N/A
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 660 Ti/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 364.12 Direct Rendering: Yes
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: a000 bus-ID: 09:00.0
Drives:    HDD Total Size: 1160.2GB (52.8% used)
Info:      Processes: 250 Uptime: 2:30 Memory: 1728.5/7953.2MB
           Init: systemd runlevel: 5 Gcc sys: 5.3.1
           Client: Shell (bash 4.3.421) inxi: 2.2.28

**Comment by steamlinux** [comment]
before I have this troule only with steam beta
today updated steam stable and game freezed when minimized
good job!

**Comment by steamlinux** [comment]
when game freezed, one cpu core load on 100% (I have cpu with 8 cores)
I try set mat_queue_mode to -1, 0, 1, 2 and nothing

**Comment by kisak-valve** [comment]
Hello @steamlinux, are you still experiencing this issue on an up to date system?

**Comment by steamlinux** [comment]
hey! I think issue not actualy, game work not bad

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
