### ISSUE TITLE
Steam hangs on Installing breakpad message

### ISSUE THREAD

**Issue by QkiZMR** [ValveSoftware/steam-for-linux#4370]
I'm trying to run steam from console but sometimes it hangs on message:

```
Running Steam on ubuntu 15.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1457636973)
```

**Comment by gdrewb-valve** [comment]
Similar to several open issues.  More detail, such as repro steps that could help narrow the problem, would be great.

**Comment by QkiZMR** [comment]
Repro steps? Just run Steam client. But I found workaround. After relogin to Ubuntu account everything back to normal.

**Comment by Tele42** [comment]
@QkiZMR I believe @gdrewb-valve is asking for detailed instructions on how steam was installed on your system, so he can reproduce the issue locally.

When this happens to you, is steam still running in the background and not showing a window?

**Comment by QkiZMR** [comment]
Steam was installed from official repositories. I added repo, next install steam client from Synaptic Package Manager.
Yes, Steam process is still in memory. This happens from time to time, not every time.

**Comment by kisak-valve** [comment]
Hello @QkiZMR, are you still experiencing this issue on an up to date system? If you are, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by QkiZMR** [comment]
On 18.10 steam is working fine.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
