### ISSUE TITLE
Numerical keyboard doesn't work when ingame

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4373]
Numerical keyboard doesn't work correctly on google search in steam overlay

**Comment by ekaris** [comment]
When I click on numbers 4 6 8 and 2, instead of writing Numbers the keys do left write down and up on google search, these keys have arrows.
Keyboard is Logitech K360

**Comment by ekaris** [comment]
Actually it doesn't work at all while ingame

**Comment by kisak-valve** [comment]
Closing as a duplicate of #4170.
