### ISSUE TITLE
Gamepad mappings not remembered if Steam is launched directly into Big Picture Mode

### ISSUE THREAD

**Issue by vexofp** [ValveSoftware/steam-for-linux#4375]
When launching Big Picture Mode (BPM) from the normal (desktop) Steam window, everything works as expected. Custom game-pad mappings are remembered and loaded automatically as appropriate.

When launching directly into BPM, however, either by setting the "Start in Big Picture Mode" configuration setting, or by launching steam with the -tenfoot option, no previously set game-pad mappings are remembered. The mappings can be re-created through the UI and will function correctly, but will not be remembered upon next direct-to-BPM launch.

Running on Ubuntu 5.10 Wily. Issue present in both beta and non-beta releases.

Are there any log files that would be relevant to diagnosing this issue?

**Comment by kisak-valve** [comment]
Hello @vexofp, are you still experiencing this issue on an up to date system?

**Comment by vexofp** [comment]
No; this issues has been resolved somewhere along the way.
