### ISSUE TITLE
downloading latest installer give a 403 error 

### ISSUE THREAD

**Issue by icf20** [ValveSoftware/steam-for-linux#4380]
here a web snapshot https://archive.is/ulOJc

**Comment by asuvorov-softheme** [comment]
I have the same issue right now.
OS Ubuntu 15.10 x86_64,
browser Google Chrome Version 49.0.2623.110 (64-bit)

**Comment by Sinap** [comment]
I was able to find the launcher install here.
http://repo.steamstatic.com/steam/pool/steam/s/steam/

**Comment by kisak-valve** [comment]
Hello, this was fixed a long time ago. Closing.
