### ISSUE TITLE
Steam in linux crash constantly after 31/3 update, without error messages

### ISSUE THREAD

**Issue by IniZio** [ValveSoftware/steam-for-linux#4381]
Ever since the update on 31/3, the steam crashes constantly without error messages, i do not know what actions trigger the crashes but seems to happen more when i touch my friend list or community pages.

**Comment by Tele42** [comment]
Please include your system information as requested at https://github.com/ValveSoftware/steam-for-linux#reporting-issues, especially any CrashIDs that are related to this issue.

**Comment by IniZio** [comment]
No crashIDs shown just sudden closure.
Operating system: Linux mint 17.3
Linux kernel: 3.19.0.32-generic
Graphic cards: Intel Corporation Broadcom-U Integrated Graphics
Processor: i7-5500U
64-bit system

**Comment by IniZio** [comment]
no longer playing steam, closing lol
