### ISSUE TITLE
[Left 4 Dead 2]Crashed when launching

### ISSUE THREAD

**Issue by mopperwhite** [ValveSoftware/steam-for-linux#4384]
I cannot quit the game.
I removed local files and reinstall but it didn't work.

Ubuntu 15.04 64bit
Intel® HD Graphics 5500 (Broadwell GT2)

**Comment by kisak-valve** [comment]
Hello @mopperwhite, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If you're still experiencing this issue, please use the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker for Left 4 Dead 2 issues.
