### ISSUE TITLE
Superbrothers Sword & Sworcery Won't Start

### ISSUE THREAD

**Issue by sajanp** [ValveSoftware/steam-for-linux#439]
The game initially wouldn't start because of an existing issue at #251.  @thestinger has a comment on that issue that fixes it.

Once I did that and tried to run the game again from terminal, I got the error below.  I'm assuming that's another shared library I need to symlink?  But from where to where?

Thanks.

```
sajan@vor:~/.local/share/Steam/SteamApps/common/Superbrothers Sword & Sworcery EP$ ./run.sh 
./swordandsworcery_pc: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory
```

[System Information](https://gist.github.com/4396716)

Also to note, I got this game through the Humble Bundle and had installed it manually in the past and it worked fine.

**Comment by forivall** [comment]
I had this same problem (but on 64-bit Manjaro (Arch derivative)), but my solution was to copy the files from the humble bundle version into the steam directory. It seems that the problem might be that the steam version is out of date or was compiled in a way that it loads one of the libraries in an incompatible way.
