### ISSUE TITLE
Keyboard appears in incorrect position in BPM browser

### ISSUE THREAD

**Issue by yevheniypopov** [ValveSoftware/steam-for-linux#4391]
Steam Client Build - April 4th 2016

Steps to reproduce:
1) Start Steam in Big Picture Mode and Controller connected.
2) Open Browser
3) Open New Tab (In CURRENT section)
Result:
![screenshot from 2016-04-09 20 08 43](https://cloud.githubusercontent.com/assets/3246385/14405076/144d1e42-fe8f-11e5-9db3-4a01917663ed.png)

**Comment by karmictoucan** [comment]
This issue is fixed in both stable and beta clients.

**Comment by kisak-valve** [comment]
Closing per the last comment.
