### ISSUE TITLE
Useless empty tabs in BPM browser

### ISSUE THREAD

**Issue by yevheniypopov** [ValveSoftware/steam-for-linux#4392]
Steam Client Build: April 4th 2016

It is possible to create many useless empty tabs in big picture browser
Steps to reproduce:
1) Open browser in Big Picture Mode
2) Open a new tab (CURRENT tab -> New Tab)
3) Go back to the 'CURRENT' tab(Esc on kb or 'B' on gamepad)
4) Now there will be an empty tab near the 'New Tab' in the 'CURRENT' browser tab
You can make many of them:
![screenshot from 2016-04-09 20 17 19](https://cloud.githubusercontent.com/assets/3246385/14405139/6d924ddc-fe90-11e5-8a40-8a36ae226592.png)

Empty browser window is displayed when you open it:
![screenshot from 2016-04-09 20 20 36](https://cloud.githubusercontent.com/assets/3246385/14405142/89ac3cee-fe90-11e5-94ee-5dd6636ffdf2.png)

Those tabs are completely useless: 'X' button doesn't work in when the tab is open and there is no virtual keyboard.

**Comment by kisak-valve** [comment]
Hello @yevheniypopov, it looks like the UI was fixed some time ago.
