### ISSUE TITLE
[Beta] [Big Picture] Disk Management: Library Folders List Not Selectable w/ Steam Controller

### ISSUE THREAD

**Issue by starlightknight** [ValveSoftware/steam-for-linux#4394]
Hi,
Using SteamOS + latest beta client, which added initial support for using multiple library folders in big picture mode, as long as you register them in desktop mode first.

When you go to settings -> disk management in big picture mode, there is now a drop down for library folders, but the drop down's list cannot be toggled with the steam controller or via pressing enter on a keyboard - you have to click it with a mouse. 

This makes it hard to manage storage. Please make the drop down have an event listener for input from the A button on the steam controller or enter on the keyboard

**Comment by starlightknight** [comment]
There seems to be other inconsistencies with drop down menus in BPM as well. For ex, on the audio pages, you can glitchily get the drop down to expand by holding down the A button until the menu flickers and releasing it, but this does not work at all on the Disk Management one. 

Also, other drop downs seem to work with the enter key on a keyboard, but the disk management one does not. Perhaps a common event handler for this widget type should be used to avoid issues on specific pages

**Comment by sylware** [comment]
I installed a fresh steamOS (beta OS, and beta bigpicture client): there is no way, I'm aware of, in order to add a folder to increase game storage space. I can add folders to the music storage though.

**Comment by gofydo** [comment]
Using Steam BPM beta on Windows 10 and have the same issue. The disk managment library folder drop-down is focusable, but not changeable.

**Comment by kisak-valve** [comment]
Hello @starlightknight, per "Fixed Big Picture Mode’s Disk Management screen to accept gamepad/keyboard input on the disk selection dropdown." in the [2018-02-13 Steam beta client](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1662261735523902150), please retest this with the current Steam beta client.

**Comment by kisak-valve** [comment]
Closing as fixed.
