### ISSUE TITLE
Steam html5app player segfaults with STEAM_RUNTIME=0

### ISSUE THREAD

**Issue by Oxalin** [ValveSoftware/steam-for-linux#4395]
I've been trying to make it work for some time now, but whenever I launch Steam with STEAM_RUNTIME=0 (while this works), I'm unable to view videos in my library. I'm not talking about the teasers in the store, but the real full video under Library->Videos.

Let's use "Kung Fury" as an example. Here is what I get in a terminal:
Game update: AppID 374570 "Kung Fury", ProcID 15450, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160404205501)
[0410/113217:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
[0410/113217:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160404205501)
[0410/113217:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
Game removed: AppID 374570 "Kung Fury", ProcID 15453 
No cached sticky mapping in ActivateActionSet.CAPIJobRequestUserStats - Server response failed 2

However, when using STEAM_RUNTIME=1 (with some tweaks since I use AMD's open source driver, such as removing libstdc++...), it works fine.

Yesterday, I tried to debug html5app_steam with gdb. However, symbols are missing. Would it be possible to get them? Or to have a debug compiled html5app_steam?

I'm using today's latest Steam test version on ArchLinux 64.

**Comment by gdrewb-valve** [comment]
I believe the app is just a wrapper around core Steam services so you'd need a debug version of Steam.  I don't think there are any plans to release something like that.

**Comment by Oxalin** [comment]
Well, that could be usefull for Valve at some point and for us to give you a better hand.

Anyway, I'll try to remove libraries one at a time from steam-runtime until I get the same crash.

That being said, is there a better way of identifying the source of the crash? Maybe Valve could add some debug output or be more verbose?

**Comment by gdrewb-valve** [comment]
The Steam team will take a look at this, they may add something.

**Comment by Oxalin** [comment]
I was lucky to query a dmesg for some other reason after trying to launch a movie with STEAM_RUNTIME=0. I found this a segfault related to libudev.so.0.13.1:
[  837.321419] html5app_steam[17113]: segfault at 73656375 ip 00000000f1c74449 sp 00000000ffe5acd0 error 4 in libudev.so.0.13.1[f1c71000+10000]
[  842.325318] html5app_steam[17149]: segfault at 73656375 ip 00000000f1c5c449 sp 00000000ffd012b0 error 4 in libudev.so.0.13.1[f1c59000+10000]
[  851.657851] html5app_steam[17189]: segfault at 73656375 ip 00000000f1c5c449 sp 00000000ffe37cb0 error 4 in libudev.so.0.13.1[f1c59000+10000]

Just in case, I created a symlink to the Steam-runtime libudev next to html5app_steam. However, even if html5app_steam uses steam-runtime libudev version with this trick, it crashes in the same way.

**Comment by Oxalin** [comment]
I've been able to fix the problem by removing libgcrypt15 package (and steam-libs) after removing
libgpg-error.so* from Steam's folder.

However the proposition for a debug version of Steam or something similar would still be a great idea.

**Comment by Oxalin** [comment]
Well, it seems to be something else after all: it worked correctly until I restarted... Investigating

**Comment by Oxalin** [comment]
It seems it was just "luck": I'm able to launch the player from time to time (once every 10 to 20 times). Most often, it works if I quickly try launching it after starting Steam and connecting (but it can work at any other time, it just happens more often).

I would be tempted to think there is really a bug lurking somewhere around the html5app_steam player that is revealed once STEAM_RUNTIME is turned off.

**Comment by Oxalin** [comment]
Here is a new log where at first it wouldn't allow playing a movie, but after a couple of launches, it worked. Nothing special can be seen from comparing when it works from when it doesn't, but it may give your team a clue where to look. I removed some warnings that are related to fontconfig and some "Mesa: User error: GL_INVALID_ENUM in glMatrixMode(mode)" irrelevant to the bug:

steam&
~$ Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)

(steam:12993): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:12993): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Installing breakpad exception handler for appid(steam)/version(1463778979)

{Fontconfig warnings}

[0525/180121:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0525/180121:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160520185747)
Installing breakpad exception handler for appid(steamwebhelper)/version(1463770667)
[0525/180121:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160520185747)
Installing breakpad exception handler for appid(steamwebhelper)/version(1463778979)
Installing breakpad exception handler for appid(steamwebhelper)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Unknown device type 14
Installing breakpad exception handler for appid(steam)/version(1463778979)

** (steam:12993): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'

** (steam:12993): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:12993): WARNING **: Ignoring invalid property 'route-data'

** (steam:12993): WARNING **: Ignoring invalid property 'address-data'
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
Installing breakpad exception handler for appid(steam)/version(1463778979)
roaming config store loaded successfully - 3033 bytes.
migrating temporary roaming config store

{Fontconfig warnings}

Installing breakpad exception handler for appid(steam)/version(1463778979)
ExecCommandLine: ""/home/ademers/.local/share/Steam/ubuntu12_32/steam" "
System startup time: 5,21 seconds
Installing breakpad exception handler for appid(steam)/version(1463778979)
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1463778979)
Generating new string page texture 73: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 74: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 75: 64x256, total string texture memory is 507,90 KB
Generating new string page texture 76: 8x256, total string texture memory is 516,10 KB
Generating new string page texture 77: 32x256, total string texture memory is 548,86 KB
ExecCommandLine: "/home/ademers/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
CAPIJobRequestUserStats - Server response failed 2
Installing breakpad exception handler for appid(steam)/version(1463778979)
Generating new string page texture 94: 128x256, total string texture memory is 679,94 KB
Generating new string page texture 95: 512x256, total string texture memory is 1,20 MB
Generating new string page texture 96: 384x256, total string texture memory is 1,60 MB
Generating new string page texture 97: 128x256, total string texture memory is 1,73 MB
Generating new string page texture 98: 48x256, total string texture memory is 180,22 KB
Generating new string page texture 101: 24x256, total string texture memory is 1,75 MB
CAPIJobRequestUserStats - Server response failed 2
Generating new string page texture 102: 2048x256, total string texture memory is 3,85 MB
Generating new string page texture 103: 1024x256, total string texture memory is 4,90 MB
Game update: AppID 374570 "Kung Fury", ProcID 19700, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160520185747)
[0525/180135:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0525/180135:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160520185747)
[0525/180135:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Game removed: AppID 374570 "Kung Fury", ProcID 19722 
No cached sticky mapping in ActivateActionSet.Game update: AppID 374570 "Kung Fury", ProcID 22231, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160520185747)
[0525/180137:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0525/180137:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
ERROR: ld.so: object '/home/ademers/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(html5app)/version(20160520185747)
[0525/180137:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Open http://store.steampowered.com/video/watch/374570/

{Fontconfig warnings}

Installing breakpad exception handler for appid(gameoverlayui)/version(20160520185836)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)

{Fontconfig warnings}

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Console Message: %c[video]%c - http://store.akamai.steamstatic.com/public/shared/javascript/dash_player.js?v=0w8lxz5IzVou&l=english:6
Console Message: %c[video]%c - http://store.akamai.steamstatic.com/public/shared/javascript/dash_player.js?v=0w8lxz5IzVou&l=english:6

{Mesa: User error: GL_INVALID_ENUM in glMatrixMode(mode) repeated again and again and again}

Game removed: AppID 374570 "Kung Fury", ProcID 22234 
No cached sticky mapping in ActivateActionSet.process 12993: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace
[2016-05-25 18:01:19] Startup - updater built May 20 2016 18:57:58
[2016-05-25 18:01:19] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-05-25 18:01:19] Checking for update on startup
[2016-05-25 18:01:19] Checking for available updates...
[2016-05-25 18:01:20] Download skipped: /client/steam_client_publicbeta_ubuntu12 version 1463778979, installed version 1463778979
[2016-05-25 18:01:20] Nothing to do
[2016-05-25 18:01:20] Verifying installation...
[2016-05-25 18:01:20] Performing checksum verification of executable files
[2016-05-25 18:01:20] Verification complete
assert_20160525180119_1.dmp[27752]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160525180119_1.dmp

**Comment by Oxalin** [comment]
Tested once again today and everything seems fine (after a few tests). This bug can be closes for now.
