### ISSUE TITLE
Steam crashes and causes other programs to crash since approx 24th March

### ISSUE THREAD

**Issue by leighco** [ValveSoftware/steam-for-linux#4397]
Using Linux Mint 17.3

Since approx 14th of March many programs have been crashing, particularly web browsers (firefox/google chrome). After experimentation I found that these crashes were happening more frequently when Steam was open in the background. Steam itself has also been crashing. After uninstalling Steam these web browser crashes stopped. Reinstalling Steam caused these problems to begin again. This also happened when using Steam also on a fresh user profile.

**Comment by kisak-valve** [comment]
Hello @leighco, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
