### ISSUE TITLE
Steam overlay degrades performance greatly compared to no overlay

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4400]
Steam overlay degrades performance greatly compared to no overlay:
https://www.gamingonlinux.com/articles/the-talos-principle-vulkan-benchmarks-on-stable-and-beta-builds.7035

**Comment by Plagman** [comment]
There's a known performance issue right now when the overlay is _rendering_, but there shouldn't be an issue when it's simply enabled, but not rendering. Do you know if the folks running the benchmark were getting notifications while running the benchmark, or did they have the Steam FPS counter enabled?

**Comment by LiamDawe** [comment]
I did have that FPS counter on it seems (don't even notice I have it on sometimes).

So it seems it is the rendering issue, not just having it turned on (i did some tests to verify).

**Comment by Plagman** [comment]
Thanks for double-checking.

**Comment by Plagman** [comment]
This should be improved in tonight's client Beta.

**Comment by not83** [comment]
Awesome
