### ISSUE TITLE
glXChooseVisual failed

### ISSUE THREAD

**Issue by computerfr33k** [ValveSoftware/steam-for-linux#4401]
```bash
STEAM_RUNTIME=1 steam

/home/eric/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/eric/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
STEAM_RUNTIME is enabled by the user
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
glXChooseVisual failedMain.cpp (307) : Assertion Failed: Fatal Error: glXChooseVisual failed
Assert( Assertion Failed: Fatal Error: glXChooseVisual failed ):Main.cpp:307

Installing breakpad exception handler for appid(steam)/version(1459463254)
crash_20160413195608_6.dmp[5476]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160413195608_6.dmp
[0413/195608:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
[0413/195608:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160331191033)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459451433)
[0413/195608:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160331191033)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459463254)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459463254)
crash_20160413195608_6.dmp[5476]: Finished uploading minidump (out-of-process): success = yes
crash_20160413195608_6.dmp[5476]: response: CrashID=bp-8d78475d-553d-4ccf-90a4-053a42160413
crash_20160413195608_6.dmp[5476]: file ''/tmp/dumps/crash_20160413195608_6.dmp'', upload yes: ''CrashID=bp-8d78475d-553d-4ccf-90a4-053a42160413''
```

**Comment by gdrewb-valve** [comment]
Can you provide more system information, particularly your monitor and display settings?

**Comment by computerfr33k** [comment]
I am using a BenQ 24" Monitor (1920 x 1080) using an Nvidia 960 GPU.
I am also using Cinnamon 2.8.8 for my Desktop Environment.

Let me know if that's enough information that you need.

**Comment by computerfr33k** [comment]
Something weird, is if I run it without the steam runtime, then I get the unable to load steamui.so

```bash
/home/eric/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/eric/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
STEAM_RUNTIME is disabled by the user
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
[2016-04-13 21:55:08] Startup - updater built Mar 31 2016 19:10:48
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-04-13 21:55:08] Checking for update on startup
[2016-04-13 21:55:08] Checking for available updates...
[2016-04-13 21:55:08] Download skipped by HTTP 304 Not Modified
[2016-04-13 21:55:08] Nothing to do
[2016-04-13 21:55:08] Verifying installation...
[2016-04-13 21:55:08] Performing checksum verification of executable files
[2016-04-13 21:55:09] Verification complete
[2016-04-13 21:55:11] Shutdown
```

Not sure if they are both related somehow?

**Comment by computerfr33k** [comment]
The problem seems to have gone away after upgrading to the most recent version of the nvidia driver (nvidia-364.16).

**Comment by trite2k3** [comment]
I have the same problem, fresh install of slackware 64-current today with latest nvidia installed from nvidia.com .run-file and multilib from alien slakcware repo

ran glxgears and moved the windows like crazy, stable fps and everything seems to work. got GSYNC, two 1440p monitors and GSYNC on the main one.

restarted multiple times
steam doesnt start


root@bifrost:~# nvidia-smi -a

==============NVSMI LOG==============

Timestamp                           : Fri Oct 13 19:31:02 2017
Driver Version                      : 384.90

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Product Name                    : GeForce GTX 980
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0323614114278
    GPU UUID                        : GPU-5b953fca-b3dc-b086-25c3-7f246f4cd127
    Minor Number                    : 0
    VBIOS Version                   : 84.04.1F.00.02
    MultiGPU Board                  : No
    Board ID                        : 0x100
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    PCI
        Bus                         : 0x01
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x13C010DE
        Bus Id                      : 00000000:01:00.0
        Sub System Id               : 0x85041043
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 8000 KB/s
    Fan Speed                       : 30 %
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
    FB Memory Usage
        Total                       : 4035 MiB
        Used                        : 193 MiB
        Free                        : 3842 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 4 MiB
        Free                        : 252 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 2 %
        Memory                      : 2 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 49 C
        GPU Shutdown Temp           : 96 C
        GPU Slowdown Temp           : 91 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 45.13 W
        Power Limit                 : 180.00 W
        Default Power Limit         : 180.00 W
        Enforced Power Limit        : 180.00 W
        Min Power Limit             : 120.00 W
        Max Power Limit             : 225.00 W
    Clocks
        Graphics                    : 911 MHz
        SM                          : 911 MHz
        Memory                      : 3505 MHz
        Video                       : 838 MHz
    Applications Clocks
        Graphics                    : 1126 MHz
        Memory                      : 3505 MHz
    Default Applications Clocks
        Graphics                    : 1126 MHz
        Memory                      : 3505 MHz
    Max Clocks
        Graphics                    : 1392 MHz
        SM                          : 1392 MHz
        Memory                      : 3505 MHz
        Video                       : 1281 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1334
            Type                    : G
            Name                    : /usr/libexec/Xorg
            Used GPU Memory         : 190 MiB

root@bifrost:~# lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 980] [10de:13c0] (rev a1) (prog-if 00 [VGA controller])
root@bifrost:~# nvidia-settings &
[1] 2496
root@bifrost:~# glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
719 frames in 5.0 seconds = 143.759 FPS
720 frames in 5.0 seconds = 143.808 FPS
720 frames in 5.0 seconds = 143.803 FPS
720 frames in 5.0 seconds = 143.810 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
719 frames in 5.0 seconds = 143.606 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.807 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.806 FPS
720 frames in 5.0 seconds = 143.808 FPS
720 frames in 5.0 seconds = 143.805 FPS
720 frames in 5.0 seconds = 143.809 FPS
720 frames in 5.0 seconds = 143.807 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 60 requests (60 known processed) with 0 events remaining.
root@bifrost:~# uname -a
Linux bifrost 4.13.6 #1 SMP Fri Oct 13 18:27:00 CEST 2017 x86_64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz GenuineIntel GNU/Linux
[1]+  Done                    nvidia-settings

**Comment by Braveheart53** [comment]
Same issue on Fedora 26, fully update as of today. 

Console output as follows:
<pre>
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1509425745)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
glXChooseVisual failedMain.cpp (321) : Assertion Failed: Fatal Error: glXChooseVisual failed
Assert( Assertion Failed: Fatal Error: glXChooseVisual failed ):Main.cpp:321

Installing breakpad exception handler for appid(steam)/version(1509425745)
assert_20171209152738_8.dmp[3538]: Uploading dump (out-of-process)
/tmp/dumps/assert_20171209152738_8.dmp
assert_20171209152738_8.dmp[3538]: Finished uploading minidump (out-of-process): success = no
assert_20171209152738_8.dmp[3538]: error: HTTP response code said error
assert_20171209152738_8.dmp[3538]: file ''/tmp/dumps/assert_20171209152738_8.dmp'', upload no: ''HTTP response code said error''
</pre>

Linux driver version 387.34

Running <pre>modinfo nvidia</pre> gives:

<pre>
filename:       /lib/modules/4.13.16-202.fc26.x86_64/extra/nvidia/nvidia.ko.xz
alias:          char-major-195-*
version:        387.34
supported:      external
license:        NVIDIA
srcversion:     EBF1F3E36DFB3BFB97BB385
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        
name:           nvidia
vermagic:       4.13.16-202.fc26.x86_64 SMP mod_unload 
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_TCEBypassMode:int
parm:           NVreg_UseThreadedInterrupts:int
parm:           NVreg_EnableStreamMemOPs:int
parm:           NVreg_EnableBacklightHandler:int
parm:           NVreg_EnableUserNUMAManagement:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RegistryDwordsPerDevice:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp
</pre>

While
<pre>cat /proc/driver/nvidia/version</pre>
 gives:
<pre>
NVRM version: NVIDIA UNIX x86_64 Kernel Module  387.34  Tue Nov 21 03:09:00 PST 2017
GCC version:  gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) 
</pre>
