### ISSUE TITLE
No easy way to run Steam from openSUSE Tumbleweed

### ISSUE THREAD

**Issue by PeterDCarter** [ValveSoftware/steam-for-linux#4402]
Attempting to run Steam on openSUSE Tumbleweed in KDE throws the error: 'cannot run as root user'. This despite being logged into a user account. It appears that in some senses the current version of openSUSE defaults to root, even when logging in via the user account on startup. If you could fix this error it would be great as I'd really like access to Steam chat for tech purposes. Thanks. /n/t :~)

**Comment by Tele42** [comment]
This is definitely not an error, it is a design decision to protect the majority of ex-windows users who have the mentality that privilege escalation will in any way fix a random unrelated issue they encounter. Feel free to override the safeties, but that is at your own risk.

**Comment by gdrewb-valve** [comment]
I doubt this will change for the reasons Tele42 gives but I'll leave it open.

**Comment by PeterDCarter** [comment]
Seems to have been solved by latest openSUSE updates as there were updates pending and after the restart the Steam install now progresses to the terms and conditions screen. Either that or it was to do with a previous issue which caused me to have to restart the x server... Either way you can close this particular issue now.
