### ISSUE TITLE
Steam segfaults during start on arch linux

### ISSUE THREAD

**Issue by LeoVerto** [ValveSoftware/steam-for-linux#4406]
I'm running steam on an updated 64-bit Arch Linux with a GTX 960 and version 364.16-2 of the nvidia drivers and KDE as my desktop environment.

As of the most recent update, Steam just segfaults while starting. Sometimes it shows the login window for a short amount of time but most of the time not even that.

This issue started occurring about two days ago and seems to be unrelated to the update to kernel 4.5 and the corresponding nvidia drivers.

I have already tried reinstalling all direct steam dependencies and removing both the ~/.steam and ~/.local/share/Steam directories.

```
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
[0415/135752:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
[0415/135752:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160331191033)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459451433)
[0415/135752:ERROR:main_delegate.cc(777)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160331191033)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459463254)
Installing breakpad exception handler for appid(steamwebhelper)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1459463254)
Installing breakpad exception handler for appid(steam)/version(1459463254)
assert_20160415135751_1.dmp[28262]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160415135751_1.dmp
/home/user/.local/share/Steam/steam.sh: line 756: 28212 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
assert_20160415135751_1.dmp[28262]: Finished uploading minidump (out-of-process): success = yes
assert_20160415135751_1.dmp[28262]: response: CrashID=bp-3d9638cc-4e1c-4c29-b819-bdc6b2160415
assert_20160415135751_1.dmp[28262]: file ''/tmp/dumps/assert_20160415135751_1.dmp'', upload yes: ''CrashID=bp-3d9638cc-4e1c-4c29-b819-bdc6b2160415''
```

**Comment by computerfr33k** [comment]
Steam works just fine for me on Arch 64-bit. I also have GTX 960 with the same nvidia driver as well.

**Comment by dragonnn** [comment]
I am having the same problem and it is strange because it appears on a fresh installed system, on an old system (full update) it works fine :/.

**Comment by Turbito** [comment]
I solved it by downgrading network manager and the applet (sounds weird but worked for me)

**Comment by LeoVerto** [comment]
@Turbito To which versions did you downgrade? Which DE are you using?
I tried this on KDE with `networkmanager` downgraded to 1.1.94, `networkmanager-qt` to 5.20.0 and `plasma-nm` to 5.6.2 and steam still crashes.

**Comment by Turbito** [comment]
@LeoVerto i finally get it working with the up-to-date version
just go etc/NetworkManager/NetworkManager.conf and search 
dhcp=internal
change it to dhcp=dhclient
(you had to have installed dhclient ofc)

**Comment by LeoVerto** [comment]
@Turbito Unfortunately that is already my current setting.

**Comment by LeoVerto** [comment]
Steam has mysteriously started working again for me.

I haven't updated any packages, I think in my case changing my region from `ngs_DE` to `de_DE` fixed it.

Alternatively it could've been the last Steam beta update and a reboot, though it failed to start directly after the update.
