### ISSUE TITLE
Steam segfaults in some time after running

### ISSUE THREAD

**Issue by chukago** [ValveSoftware/steam-for-linux#4408]
OS: Gentoo x64
Kernel: 4.1.15
Driver: NVidia 364.15

Steam client segfaults every time.
It happens in some time after application started.
I can't solve this problem using different versions of driver and kernel.

Stack trace:
#0  0xf7b28a16 in malloc_usable_size () from /lib32/libc.so.6
#1  0xf1ea55f9 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#2  0xf1ea52b0 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#3  0xee7a81f8 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xf77f995a in CRYPTO_free ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libcrypto.so.1.0.0
#5  0xf79a4443 in SSL_SESSION_free ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libssl.so.1.0.0
#6  0xf79a2030 in SSL_free ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libssl.so.1.0.0
#7  0xee7a1976 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xee7a1f66 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xee04b418 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xee76066e in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xee760a12 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xee760de9 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xee74ab2a in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xee7ae493 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xee7ac260 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xee7456c9 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xedecc328 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xee3dc4d5 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xedece3ff in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#20 0xedecf37c in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/steamclient.so
#21 0xf1ea9efe in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#22 0xf1ea8584 in ?? ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf1ea8824 in CatchAndWriteMiniDumpExForVoidPtrFn ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf1ea886a in CatchAndWriteMiniDumpForVoidPtrFn ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#25 0xf1eac693 in SteamThreadTools::CThread::ThreadProc(void*) ()

   from /home/crtc/.local/share/Steam/ubuntu12_32/libtier0_s.so
#26 0xf7c6b251 in start_thread () from /lib32/libpthread.so.0
#27 0xf7b9d98e in clone () from /lib32/libc.so.6

**Comment by kisak-valve** [comment]
Hello @chukago, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by chukago** [comment]
Hello,

It isn't observed in the latest release.

Thank you.

пт, 26 апр. 2019 г., 22:14 kisak-valve <notifications@github.com>:
