### ISSUE TITLE
[drm:uvd_v1_0_ib_test [radeon]] *ERROR* radeon: fence wait failed (-35)

### ISSUE THREAD

**Issue by amarildojr** [ValveSoftware/steam-for-linux#4409]
Team Fortress 2 have a big problem with Radeon/Mesa.

After playing for a few seconds on turbine (with lots of engineers, which seems to cause the crash), the system suddenly freezes.

Happens  on Debian, Ubuntu, Arch Linux, and openSUSE (all distros I've tested).

>Apr 17 02:24:51 amarildo kernel: radeon 0000:02:00.0: ring 5 stalled for more than 10000msec
Apr 17 02:24:51 amarildo kernel: radeon 0000:02:00.0: GPU lockup (current fence id 0x0000000000000004 last fence id 0x0000000000000006 on ri
Apr 17 02:24:51 amarildo kernel: [drm:uvd_v1_0_ib_test [radeon]] *ERROR* radeon: fence wait failed (-35).
Apr 17 02:24:51 amarildo kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 5 (-35).
Apr 17 02:25:00 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:25:06 amarildo kernel: radeon 0000:02:00.0: ring 0 stalled for more than 10172msec
Apr 17 02:25:06 amarildo kernel: radeon 0000:02:00.0: GPU lockup (current fence id 0x00000000000f41a6 last fence id 0x00000000000f41ad on ri
Apr 17 02:25:07 amarildo kernel: radeon 0000:02:00.0: Saved 273 dwords of commands on ring 0.
Apr 17 02:25:07 amarildo kernel: radeon 0000:02:00.0: GPU softreset: 0x00000049

>pr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: WB enabled
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00 and cpu addr 0xffff880211a78c00
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04 and cpu addr 0xffff880211a78c04
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08 and cpu addr 0xffff880211a78c08
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c and cpu addr 0xffff880211a78c0c
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10 and cpu addr 0xffff880211a78c10
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18 and cpu addr 0xffffc90001435a18
Apr 17 02:21:53 amarildo kernel: radeon 0000:02:00.0: VCE init error (-22).
Apr 17 02:21:53 amarildo kernel: [drm] ring test on 0 succeeded in 3 usecs
Apr 17 02:21:53 amarildo kernel: [drm] ring test on 1 succeeded in 1 usecs
Apr 17 02:21:53 amarildo kernel: [drm] ring test on 2 succeeded in 1 usecs
Apr 17 02:21:53 amarildo kernel: [drm] ring test on 3 succeeded in 6 usecs
Apr 17 02:21:53 amarildo kernel: [drm] ring test on 4 succeeded in 6 usecs
Apr 17 02:21:54 amarildo kernel: [drm] ring test on 5 succeeded in 2 usecs
Apr 17 02:21:54 amarildo kernel: [drm] UVD initialized successfully.
Apr 17 02:21:54 amarildo kernel: [drm] ib test on ring 0 succeeded in 0 usecs
Apr 17 02:21:54 amarildo kernel: [drm] ib test on ring 1 succeeded in 0 usecs
Apr 17 02:21:54 amarildo kernel: [drm] ib test on ring 2 succeeded in 0 usecs
Apr 17 02:21:54 amarildo kernel: [drm] ib test on ring 3 succeeded in 0 usecs
Apr 17 02:21:54 amarildo kernel: [drm] ib test on ring 4 succeeded in 0 usecs
Apr 17 02:22:04 amarildo kernel: radeon 0000:02:00.0: ring 5 stalled for more than 10000msec
Apr 17 02:22:04 amarildo kernel: radeon 0000:02:00.0: GPU lockup (current fence id 0x0000000000000002 last fence id 0x0000000000000004 on ri
Apr 17 02:22:04 amarildo kernel: [drm:uvd_v1_0_ib_test [radeon]] *ERROR* radeon: fence wait failed (-35).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 5 (-35).
Apr 17 02:22:04 amarildo kernel: radeon 0000:02:00.0: scheduling IB failed (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_vce_get_create_msg [radeon]] *ERROR* radeon: failed to schedule ib (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_vce_ib_test [radeon]] *ERROR* radeon: failed to get create msg (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 6 (-12).
Apr 17 02:22:04 amarildo kernel: radeon 0000:02:00.0: scheduling IB failed (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_vce_get_create_msg [radeon]] *ERROR* radeon: failed to schedule ib (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_vce_ib_test [radeon]] *ERROR* radeon: failed to get create msg (-12).
Apr 17 02:22:04 amarildo kernel: [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on ring 7 (-12).
Apr 17 02:22:19 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:22:51 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:23:24 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:23:56 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:24:28 amarildo systemd-timesyncd[650]: Failed to call clock_adjtime(): Invalid argument
Apr 17 02:24:39 amarildo kernel: radeon 0000:02:00.0: ring 0 stalled for more than 10216msec
Apr 17 02:24:39 amarildo kernel: radeon 0000:02:00.0: GPU lockup (current fence id 0x00000000000f391e last fence id 0x00000000000f3926 on ri
Apr 17 02:24:39 amarildo kernel: radeon 0000:02:00.0: Saved 337 dwords of commands on ring 0.

**Comment by Plagman** [comment]
Hi,

This seems to indicate a GPU programming error with the driver, rather than a problem with the game; no use of the OpenGL API should be able to result in a system component crashing or a system lockup. I would recommen reporting this to the Mesa community instead.

**Comment by amarildojr** [comment]
Why the F did this thread get closed so quickly? --'

**Comment by Tele42** [comment]
This issue report was closed due to it being an obvious driver issue, as stated by @Plagman, with a good suggestion on how to proceed.

**Comment by amarildojr** [comment]
I thought it was obvious too, but there are people not using radeon and experiencing this as well (they use Intel GPU's). Other numerous TF2 players confirm that the game is leaking memory. So it's not just radeon.

**Comment by amarildojr** [comment]
See what I'm saying, @davidw-valve ?

http://steamcommunity.com/app/440/discussions/0/368542585857761697/?tscn=1461900320#c364040166676319705

If you look at the image provided by the user, you'll see the following line:

>Apr 29 13:18:51 TheRig kernel: hl2_linux[3683]: segfault at 0 ip 00000000f4da6177 sp 00000000ffef1ff0 error 6 in i965_dri.so[f4a30000

Here you can see the user has an intel GPU: http://steamcommunity.com/app/440/discussions/0/368542585857761697/?tscn=1461900320#c364040166674007991

**Comment by Tele42** [comment]
```Apr 29 13:18:51 TheRig kernel: hl2_linux[3683]: segfault at 0 ip 00000000f4da6177 sp 00000000ffef1ff0 error 6 in i965_dri.so[f4a30000```
This is saying that i965_dri.so code segmentation faulted, which crashed hl2_linux, which is a driver bug.

Out of curiousity, are you using DRI2 or DRI3?

**Comment by amarildojr** [comment]
>Out of curiousity, are you using DRI2 or DRI3?

That was not my crash, though :)

I was using DRI3. But now it doesn't matter, I'm back on Windows. I can't expect neither VALVe or Radeon developers to fix their crap anymore. On the VALVe side there are poor ports with tons of issues that are years old; on the Radeon side they keep introducing bugs (like this one -probably-, the X-Plane one, the power management which makes my screen flicker). 4 years after the release of Steam for Linux and we still have these kinds of issues. When I first installed Steam on Linux (October 2012) I though we would be able to compete whith Windows in the game scenario. Clearly I was wrong ;-)

**Comment by winny-** [comment]
This Freedesktop Bug report seems to be related: https://bugs.freedesktop.org/show_bug.cgi?id=95308
