### ISSUE TITLE
Changing game category crashes steam client

### ISSUE THREAD

**Issue by mraggi** [ValveSoftware/steam-for-linux#4413]
Running Linux parhi 4.2.6-1-CHAKRA #1 SMP PREEMPT Tue Jan 26 19:23:21 GMT 2016 x86_64 GNU/Linux

This is the error message I get at the terminal:
http://pastebin.com/LHzCyttJ
Using nvidia drivers version 358.16.

I've had this problem for a while now on multiple computers.

**Comment by Tele42** [comment]
This version of the nvidia driver has a known defect related to multithreaded opengl supposedly fixed in nvidia 361. nvidia 361 has other issues related to libglvnd, which supposedly are fixed with 361.42.
