### ISSUE TITLE
Games segfault on startup, null OpenGL?

### ISSUE THREAD

**Issue by FrictionCow** [ValveSoftware/steam-for-linux#4415]
Hello, I'm trying to play some games, but I can't run any of them. Trying to launch Binding of Isaac: Afterbirth, for example, results in nothing happening. Running x86_64 binary from BoI's install directory results in a segfault in the terminal.

Here's a pretty good chunk of code when I try to launch BoI through Steam in the terminal.
`libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
GLFW Error 65544: GLX: Failed to create context: GLXBadFBConfig
Failed to create OpenGL window / context
OpenGL version (null)
GLSL version (null)
isaac.x64: Couldn't find current GLX or EGL context.`

I'm on Antergos (Arch) 64-bit, open source AMD drivers on the 6550D integrated graphics processor. The last time I could run games through steam was around a week ago, as far as I can remember.

I remember previously trying this which helped with one of those "Direct rendering GLX" errors, but I guess this isn't the same.
`find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete`

I tired so I probably worded this very oddly, so I'll reiterate/provide more information if you need me to. Thanks very much.

**Comment by Tele42** [comment]
This most likely is fallout from Arch updating from gcrypt 1.6.5 to 1.7.0 which is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/4410.

**Comment by FrictionCow** [comment]
Yes, the workaround of deleting Steam's libgpg-error seems allows me to run BoI again, so I'd say this is the same issue. Thanks a bunch!
