### ISSUE TITLE
Steam not installing on Ubuntu 16.04 LTS due to dependences issue

### ISSUE THREAD

**Issue by mhsabbagh** [ValveSoftware/steam-for-linux#4416]
After trying the .deb file from the official website for Ubuntu, Steam fails to install because of some problems with dependences on Ubuntu 16.04 LTS - 64x Bit.

```
Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for mhsabbagh: 
........
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libllvm3.8:i386 but it is not going to be installed
                        Depends: libstdc++6:i386 (>= 5.2) but it is not going to be installed
                        Recommends: libtxc-dxtn-s2tc0:i386 but it is not going to be installed or
                                    libtxc-dxtn0:i386
 libgl1-mesa-glx:i386 : Depends: libxdamage1:i386 (>= 1:1.1) but it is not going to be installed
                        Depends: libxext6:i386 but it is not going to be installed
                        Depends: libxfixes3:i386 but it is not going to be installed
                        Depends: libxxf86vm1:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Press return to continue:
```
I hope there will be a fix for this.

**Comment by Anthony4444** [comment]
I have a similar problem even though I installed through the software center.

**Comment by xksteven** [comment]
I removed Steam from Ubuntu software center (by uninstalling it with the gui) and also ran sudo apt-get remove steam.

After that I installed steam by sudo apt-get install steam and it worked for me.  Albeit the steam logo that gets installed is the old logo.  One might also have to move or remove the .steam file but this is after the installation anyways.

**Comment by mhsabbagh** [comment]
Still doesn't work for me, using `sudo apt install steam` gives the same thing.

**Comment by gilarthon** [comment]
Recently installed kubuntu 16.04 64-bit from scratch and I am getting the same error. Any fix on this?

**Comment by gilarthon** [comment]
I have solved this issue by changing the repository server from Turkey to United States.

**Comment by mhsabbagh** [comment]
Confirmed, will report the bug to Ubuntu on lanuchpad then since it's from their local repositories.
