### ISSUE TITLE
User discrimination when using a VPN

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4422]
There is discrimination when offers are sent and confirmed by email, they get canceled and activation of Humble Bundle keys says too many activation attempts or key invalid!

**Comment by Plaque-fcc** [comment]
Possibly not a GNU/Linux-related issue, right?

**Comment by not83** [comment]
Correct

**Comment by ekaris** [comment]
It affects Linux users

**Comment by not83** [comment]
But this place is for Linux only bugs

**Comment by ekaris** [comment]
Do you have another place where I can report it? I don't think so

**Comment by ekaris** [comment]
Issue Fixed
