### ISSUE TITLE
Ubuntu 16.04 64bit - couldn't login

### ISSUE THREAD

**Issue by fischerq** [ValveSoftware/steam-for-linux#4425]
Upgraded Ubuntu to 16.04, on next start the client was unable to log in. 

After some googling I tried to start with `steam --reset`, which failed:

```
fischerq@fischerq-laptop:~$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2016-04-26 15:21:18] Startup - updater built Mar 31 2016 19:10:48
[2016-04-26 15:21:18] Verifying installation...
[2016-04-26 15:21:18] Verification complete
^C
fischerq@fischerq-laptop:~$ steam --reset
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.
```

Reinstalled with 
        sudo apt-get remove steam
        sudo apt-get install steam

Works again!

**Comment by kisak-valve** [comment]
Hello @fischerq, have you encountered this issue since the initial report?

**Comment by kisak-valve** [comment]
Closing pending feedback.
