### ISSUE TITLE
Updated Ubuntu 14.04 to 16.04 now STEAM wont run anymore

### ISSUE THREAD

**Issue by vbdeman** [ValveSoftware/steam-for-linux#4429]
You guys have any clue?

steam did notthing after upgrade to ubuntu 16.04
uninstalled steam wtih synaptic from 16.04 and reinstalled.
first time run - it did do a update and then notting.
i rebootted then this

terminal:

ben@lpt-001:~$ steam
Running Steam on ubuntu 16.04 32-bit
STEAM_RUNTIME is enabled automatically
[2016-04-27 16:45:12] Startup - updater built Mar 31 2016 19:10:48
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

any ideas? 

running a laptop with intel integrated graphics.

**Comment by gdrewb-valve** [comment]
Likely duplicate of other issues here, look at the ones referencing 16.04 and specifically #4417.

**Comment by kisak-valve** [comment]
Hello @vbdeman, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
