### ISSUE TITLE
Some x86_64 games do not launch due to spurious LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by reavertm** [ValveSoftware/steam-for-linux#4434]
Disclaimer: this problem appears even when using built-in steam runtime.

steam.sh contains certain malicious line that breaks games launcher for some games on non-Ubuntu x86_64 Linux setups:

```
# Need to add /usr/lib32 to the library path to pick up libvdpau_nvidia.so on Ubuntu 12.04
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/lib32"

```

This is ugly hack, it's not known whether it's still needed after four years and causes nontrivial to spot problems with games that rely on dlopen - notable example being Kerbal Space Program that does not launch out of the box on non-Ubuntu x86_64.

Existing issues related to this problem LD_LIBRARY_PATH:
#3907
#3851
#3624
Also please see https://bugs.gentoo.org/show_bug.cgi?id=531990 that had to be worked around in ugly fashion just because of spurious LD_LIBRARY_PATH.

Dear Valve, if you really need to have Ubuntu specific hacks in launch scripts, please move them away from steam.sh and put them to pre-launcher script that is installed to /usr/bin.

**Comment by sallyx** [comment]
Why was this closed? I have this problem on OpenSuse Tumbleweed now.

**Comment by cirelli94** [comment]
Probably because they support Ubuntu only
