### ISSUE TITLE
Change target distribution from precise to stable

### ISSUE THREAD

**Issue by tomchiverton** [ValveSoftware/steam-for-linux#4436]
from apt-get update:

```
E: The repository 'http://repo.steampowered.com/steam xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by ShabbyX** [comment]
I just tried adding the steam repo to 16.04 (I had steam from 14.04, and at another computer I downloaded the .deb file), and I get the same issue. Additionally, I see:

```
E: Failed to fetch http://repo.steampowered.com/steam/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 24.200.120.16 80]
E: Failed to fetch http://repo.steampowered.com/steam/dists/xenial/main/binary-i386/Packages  404  Not Found [IP: 24.200.120.16 80]
```

**Comment by Plagman** [comment]
It seems like a distribution upgrade changed the target distribution for our repository from 'precise' to 'xenial' in your APT sources. If you use the 'precise' target you should be able to install our package without issues.

**Comment by ShabbyX** [comment]
We _are_ on xenial! But now that you have found the issue, then hopefully fixing it on your side is just a matter of configuration.

**Comment by Plagman** [comment]
We use the precise folder for all versions post-precise, so 'precise' is what you need to target for our repository.

**Comment by not83** [comment]
People who know nothing about ubuntu or steam just want to play steam
games. I don't think asking everyone to edit config files will work out

**Comment by Plagman** [comment]
The bug is with the Ubuntu distribution upgrade script mistakenly editing third-party software sources.

**Comment by not83** [comment]
Who do we contact in order to get this fixed

**Comment by Tele42** [comment]
I'd expect ubuntu's bug tracker would be a sensible place to continue pursuing this, but I suspect there's more legitimate scenarios where this behavior is for the greater good.

**Comment by tomchiverton** [comment]
I believe @Plagman is incorrect. The Steam repository is broken if it doesn't follow the convention of accepting the currently running client O/S as a folder. All they need to do is add sym links, for instance, to fix it.

**Comment by ShabbyX** [comment]
I agree with @tomchiverton. It makes more sense for distribution upgrade to set the correct distribution for third party repositories. If it didn't, everybody had to manually update all their third party repositories to the correct distribution, which is certainly a bigger hassle for the users.

A symlink is likely all it takes, requiring no extra disk space. The problem is a lot simpler to fix on Steam side than on users'.

**Comment by mfulgo** [comment]
@Plagman, I think the way Google Chrome handles this would also work well for you. Rather than using the distro name, they use **stable**.

See step 2 [here](http://askubuntu.com/a/510186).

**Comment by nicdumz** [comment]
@Plagman any chance you could reopen this bug, and make it a TODO and your guys' side to implement https://github.com/ValveSoftware/steam-for-linux/issues/4436#issuecomment-222023703 ?

Thanks much

**Comment by smcv** [comment]
A `stable` suite is now available (it has the same content as `precise`). Version 1.0.0.64 of the `steam-launcher` package, currently in beta, changes `steam.list` for new installations to have this content:

```
deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam

# Uncomment these lines to try the beta version of the Steam launcher
#deb [arch=amd64,i386] https://repo.steampowered.com/steam/ beta steam
#deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ beta steam
```

`steam.list` is managed as a dpkg conffile, so for existing installations, whether it is replaced or kept as-is will depend on your apt/dpkg configuration and whether you have modified it locally.
