### ISSUE TITLE
Kubuntu 16.04, segfault on launch, non-steam games run in x86 and x86_64 mode

### ISSUE THREAD

**Issue by paines** [ValveSoftware/steam-for-linux#4438]
So I installed Steam and bought Tomb Raider, played for an hour (awesome port btw...) and now a few days later Steam segfaults on startup.

steam.real gives me 

```
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2016-05-04 09:45:29] Startup - updater built Jun 16 2014 11:16:02
[2016-05-04 09:45:29] uninstalled manifest found in /home/al/.steam/steam/package/steam_client_ubuntu12 (1).
[2016-05-04 09:45:29] Found pending update
[2016-05-04 09:45:29] Shutdown
```

steam gives me:

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2016-05-04 09:46:00] Startup - updater built Mar 31 2016 19:10:48
[2016-05-04 09:46:00] Verifying installation...
[2016-05-04 09:46:00] Verification complete
```

Both calls would generate a .dmp file in tmp and produce an output in dmesg:

```
[ 1999.296847] steam[3186]: segfault at 0 ip           (null) sp 00000000ffdad37c error 14 in steam[565c3000+3a9000]
[ 2195.609711] steam[3393]: segfault at 8 ip 0000000000000008 sp 00000000ffd7394c error 14 in steam[56593000+3a9000]
```

Like mentioned, OpenGL works, I tested it with GoneHome (from HumbleBundle) both 32 and 64bit variant, work flawlessly and fast in maximum settings.
Unfortunately  I cannot attach the dmp/core files....

**Comment by gdrewb-valve** [comment]
Likely a duplicate of the other 16.04 issues here.

**Comment by kisak-valve** [comment]
Hello @paines, are you still experiencing this issue on an up to date system?

**Comment by paines** [comment]
@kisak-valve To be honest, i moved forward with (K)Ubuntu now at 19.xx. I use steam on LInux on a regularly basis und couldn't be more happier. I do not know how the situation back then cleared up. Thanks for you great work!
