### ISSUE TITLE
Green screen with Unreal Tournament 4 when trying to use In-Home Streaming

### ISSUE THREAD

**Issue by Alexey-Akishin** [ValveSoftware/steam-for-linux#4439]
My host PC has GTX 680 card, I'm using newest NVidia driver and Linux. When I try to run Unreal Tournament 4, it looks good on host PC, but on client computer I get green screen.

I have tried both Linux and Windows as clients, in both cases I get green screen. I also have tried to disable hardware encoding on Linux host, did not change anything.

Linux version of UT4 can be downloaded [here](https://www.epicgames.com/unrealtournament/forums/showthread.php?12011-Unreal-Tournament-Pre-Alpha-Playable-Build) if you have Epic Games account (or few minutes of spare time to create one) or [here](https://aur.archlinux.org/packages/ut4/) without registration.

**Comment by Plagman** [comment]
If you just run the game on your host PC, are you able to take Steam screenshots or do they also come out green?

**Comment by Alexey-Akishin** [comment]
Steam screenshots come out black for this game, even though Steam overlay works (I can monitor FPS, etc).

If I manage somehow bring normal window in foreground (such as text editor) while In-Home Streaming is active, I can see Unreal Tournament 4 normally in the background, but FPS feels low. If I make UT4 window foreground again, everything become green (I guess Steam switches to more efficient method of capturing real-time video, but something goes wrong and it does not work).

**Comment by kisak-valve** [comment]
Hello @Alexey-Akishin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
