### ISSUE TITLE
Steam Linux Interface Bug

### ISSUE THREAD

**Issue by Parduk** [ValveSoftware/steam-for-linux#4441]
Hi, I had problem with steam when using Turkish Language. Some interface windows can't readable or clickable. There is the screenshots:

OS:Ubuntu 16.04 x86_64

System Language Turkish:
https://drive.google.com/open?id=0B906vOqmI0PCbzV5M1R2Y09TTzg
https://drive.google.com/open?id=0B906vOqmI0PCS0ZIaWt5N3l4UXM
https://drive.google.com/open?id=0B906vOqmI0PCd09weDVUd3dJUlE
https://drive.google.com/open?id=0B906vOqmI0PCUFQxNjdEdHFiMjQ

System Language English:
https://drive.google.com/open?id=0B906vOqmI0PCa1M5amphLTdyOGs
https://drive.google.com/open?id=0B906vOqmI0PCRGg3dTRNN2lrck0

**Comment by Parduk** [comment]
13July16 - problem continues

**Comment by Parduk** [comment]
13 September 2016 - Problem Continues

**Comment by Parduk** [comment]
Nobody cares?

**Comment by kisak-valve** [comment]
Hello @Parduk, apparently this can be worked around by setting the env variable `LC_ALL=C` when running steam. Closing in favor of #4792.
