### ISSUE TITLE
Feature Request: Download game ignoring platform availability

### ISSUE THREAD

**Issue by a1batross** [ValveSoftware/steam-for-linux#4442]
Hello.

At first, sorry if this is a duplicate of another issue.

Many games in Steam have a native Linux/Mac port. For example, Quake or Serious Sam. 
But developers or publishers doesn't care and they will not release game for Linux/Mac. So I requesting a feature, where users can download a game ignoring availability without downloading and installing Windows Steam and Wine or downloading illegal copy of game from Web.

I think, many Linux users will agree with my suggestion.

**Comment by Tele42** [comment]
Duplicate of #1989.

**Comment by starlightknight** [comment]
I'd personally love to see a couple of advanced options for Wine. Plenty of older games that have little to no chance of ever getting a native port work great in it, but there's no way to have a good experience in Big Picture Mode right now. In this case, I don't really see the difference between wine as an option, versus some old games on steam being wrapped in dosbox.

If you could do what this issue requests, then you could put wine launching options in the advanced launch options dialog that already exists. Between this and #4412, a user could fairly easily and cleanly run wine compatible games out of Big Picture Mode without a lot of effort. 

As far as potential case sensitivity differences on the file system, steam already supports multiple library folders. We could just add a 2nd one that points to an NTFS partition and then do the "force install" of any games we intend to use with wine there (or eat the performance penalty and let wine query for it).

Hide it behind a "there are dragons this way" button if you must, but it'd be extremely useful to have a few of these fixes for those of us who are trying to go completely Windows-free

**Comment by a1batross** [comment]
No, Wine in Linux Steam is not what I wanted to say. 

I mean just downloading game data for native Linux ports, which exists outside the Steam and running it by hand. Yes, without the label "Playing in $GAME" in Steam Friends or any another Steam feature. 

For example, downloading game data for [Quake II](http://store.steampowered.com/app/2320/) and running it under original [Quake II port](https://github.com/id-Software/Quake-2) or under any other Quake II engine fork with Linux/Mac support, such as [Yamagi Quake II](http://www.yamagi.org/quake2/)

**Comment by starlightknight** [comment]
It's a good point that you'd be able to do that as well. I have a handful of titles like that which have Linux options that are not on Steam - older Quakes, Unreal Tournament, etc

**Comment by YourLocalCultLeader** [comment]
SteamCMD can do this: https://developer.valvesoftware.com/wiki/SteamCMD#Cross-Platform_Installation

**Comment by a-detiste** [comment]
`game-data-packager` is meant to automate this whole process:
- call steamcmd and forcefully download "windows" game
- create a .deb or .rpm
- install it, this will automatically pull in matching opensource engine.  (doom,quake1/2/4, scummvm, wolf4sdl, iortcw ...)

as a bonus, the game can the be played by all local users.

steamcmd can even be ran on arm machines thanks to QEMU user mode emulation

**Comment by a-detiste** [comment]
I made a list of those games: https://steamcommunity.com/groups/debian_gdp#curation

**Comment by CaptSilver** [comment]
Add this plus a full path exec function for advanced users only (maybe beta only), so we can run wine on these games. That way, Steam won't support the use of wine, but ease the use of running the programs. I am tired of making desktop files and having duplicate entries of the same game.

**Comment by a1batross** [comment]
Fixed. Thanks to new Steam Play, @ValveSoftware! :)
