### ISSUE TITLE
Store / Featured Tab: Upcoming Titles Not Filtered for Linux

### ISSUE THREAD

**Issue by starlightknight** [ValveSoftware/steam-for-linux#4443]
Within the store tab in the client, on the Featured page, "Popular New Releases", "Top Sellers", and "Specials" all only show games that are available on Linux - but upcoming titles shows everything. 

This makes the list of upcoming titles often drowned out by Windows only titles, making it harder to see at a glance what's coming soon for Linux. It would be helpful if this was also filtered for Linux

Note: If you go the full list it works as expected - its just broken on the featured page - but considering thats the front section, its high visibility.

**Comment by Tele42** [comment]
Duplicate of #4038.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
