### ISSUE TITLE
libGL errors on Ubuntu 16.04 desktop amd64

### ISSUE THREAD

**Issue by DejanSRB** [ValveSoftware/steam-for-linux#4451]
Installation of Steam was without errors but later when I tried to start it for the first time I got all this errors:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1461972496)
libGL error: unable to load driver: vmwgfx_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vmwgfx
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

After some research I executed this two:

rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libgcc_s.so.1

After that Steam had gone thru update process after which I got same errors as above.
I would appreciate some help since I'm trying to switch to Linux after long time on Windows.

**Comment by gdrewb-valve** [comment]
Check out the other 16.04 issues here, it's highly likely you're hitting the same thing as the others.

**Comment by DejanSRB** [comment]
So far no luck in other issues. I'll wait patiently for my issue. No hurries, got plenty of other thing to do with Ubuntu. Thanks for trying to resolve it.

**Comment by Goddard** [comment]
Same issue here.  What is fix?

**Comment by DejanSRB** [comment]
Nothing so far.

**Comment by teresko** [comment]
What helped me (on ArchLinux, current) was running it with this command: 
`LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' steam`


After some tinkering I was able to shorten it to `LD_PRELOAD='/usr/$LIB/libstdc++.so.6  /usr/$LIB/libgpg-error.so' steam`

**Comment by DejanSRB** [comment]
Thank you teresko.
With that second line I did managed to start it. It works fine but in the background there are a lot of errors like this:
ERROR: ld.so: object '/usr/$LIB/libgpg-error.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc

But to repeat once more. It does work even with errors.

**Comment by teresko** [comment]
That latter one will probably be due to missing `libgpg-error` (either 64 or 32 bit variant). The trick with `LD_PRELOAD` is a workaround, which manually feeds Steam those libs.

**Comment by Oxalin** [comment]
You better stick with the first one though, libgcc_s and libxcb being related to some problems here and there.

**Comment by teresko** [comment]
The `libxcb` I actually got fixed by installing `lib32-qt5-base-bin`.

**Comment by DejanSRB** [comment]
Same thing regardless if I use first or second line. Thanks for help both of you. I think it's ok for now since I can start it regardless of errors. When I learn little more of my Ubuntu I'll try to dig deeper into this. :+1:

**Comment by Oxalin** [comment]
@DejanSRB, I'll just add a little note: you may see a lot of errors that should be considered as warnings. Steam runs as a 32 bit application, so it may have a look at your libs and discards the 64bit version of them. Then, you may have some 64 bit games launched from Steam, and they will be looking for the 64 bit version of the libs. When Steam or a game encounters a library not meant for the architecture it is looking for, it will throw an error even though it may be able to find a suitable one.

Other times, you may have an error (warning) because Steam is expecting to find something in the library but can't. It may be because it is a different version from what it is expecting.

That being said, if you are able to launch Steam, have fun! ;)

**Comment by DejanSRB** [comment]
Thanks a lot man. I appreciate your time to explain this in details for me. Now I know  a lot more about this.

**Comment by kisak-valve** [comment]
Hello @DejanSRB, since the last comment on this issue report, Steam's handling of the Steam runtime has changed to prefer host libraries before the steam runtime variants, which should avoid the issue described here. Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
