### ISSUE TITLE
screenshots don't uploading after last update. steam beta.

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#4459]
1. steam beta
2. debian sid x86_64
3. screenshots doesn't work and I can upload old screenshots ("error code 1. steam cloud may not work"). without beta update screenshots normally work and uploading.

**Comment by steamlinux** [comment]
after today update screenshots work
thread may close

**Comment by Tele42** [comment]
@steamlinux you can close your own issue reports.
