### ISSUE TITLE
Steam should change to 64 bits by default and drop 32 bits

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4465]
99% of users out there use 64 bit Linux systems, there should at least be a 64 bit steam client or better, drop 32 bit, that way more devs will put games in 64 bits with better performance.

**Comment by LinuxDonald** [comment]
Yeah that would be very cool :)

**Comment by Tele42** [comment]
Duplicate of #179.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
