### ISSUE TITLE
Right clicking copy doesnt copy links unless they are selected

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4470]
#### Your system information
- Steam client version:
  29 April 2016
- Distribution (e.g. Ubuntu): 
  Ubuntu 16.04
- Opted into Steam client beta?: [Yes/No] 
  NO
- Have you checked for system updates?: [Yes/No]
  YES
#### Please describe your issue in as much detail as possible:

On chat and right clicking on links and select copy doesn't copy the links unless they are totally selected.
#### Steps for reproducing this issue:
1. Get a friend to past link on chat
2. Select copy using right click in the link
3. Doesn't copy

**Comment by kisak-valve** [comment]
Closing as fixed some time ago and because the user has turned into a ghost.
