### ISSUE TITLE
LWJGL/libGDX games fail to start with new xorg

### ISSUE THREAD

**Issue by isage** [ValveSoftware/steam-for-linux#4471]
#### Your system information
- Steam client version: any
- Distribution (e.g. Ubuntu): Fedora 23/24 / Ubuntu 16.04 / Any other distro with xorg 1.18
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
#### Steps for reproducing this issue:
1. Run any libgdx/lwjgl game ( The Way, for example)
2. Game crashes

**Comment by Plagman** [comment]
Narrowed scope a bit, we'll look into it. X protocol should be compatible even with older client libraries.

**Comment by isage** [comment]
Newer xrandr uses newer libXrandr and new api - XRRGetProviderInfo
For now, you can just provide relevant version of xrandr binary in runtime.
But seriously, consider doing things, that you cut from my post.

**Comment by Plagman** [comment]
The runtime is required to effectively being able to support games sold through Steam; we can't require users to have to install an unspecified amount of distribution packages before the game they bought will start running. There are issues with the runtime and we'll work on fixing them, but suggesting to rip it out altogether is not helpful.

**Comment by isage** [comment]
I'm not suggesting to rip it all out, I'm suggesting to rip out only
system-essential ones. Ones, that are present on every system, just because
it won't work without them. If you worried about i386 libs on x86_64
systems - there's package-manager dependencies for this.

Providing stuff like libsdl/glew/cg/etc. is fine, however

**Comment by kisak-valve** [comment]
Hello @isage, since this issue report, Steam's handling of the Steam runtime has changed to prefer host libraries before the steam runtime variants. Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
