### ISSUE TITLE
[Feature Request] Hide application from Activities overview when close button is clicked

### ISSUE THREAD

**Issue by LumpBloom7** [ValveSoftware/steam-for-linux#4476]
#### Your system information

* Steam client version: Steam API: v017
* Distribution (e.g. Ubuntu): Ubuntu GNOME 16.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Most of the time I keep Steam open in the background while doing something else, the Steam icon remains in the taskbar and/or activities overview while having an icon in the system tray. It gets pretty annoying when you're doing something that requires constant switching of applications.

#### What is expected
When clicking the close button, it should act like the Windows version. It should hide the app from activities overview, alt-tab menu, taskbar and similar menus, while still being shown in the system tray.

#### Steps for reproducing this issue:

1. Start Steam Client
2. Press close button on Steam Client
3. Check the Ubuntu taskbar, GNOME activities overview and Alt-Tab menu.

**Comment by Tele42** [comment]
Hello, the environment variable ```STEAM_FRAME_FORCE_CLOSE=1``` from https://github.com/ValveSoftware/steam-for-linux/issues/1025#issuecomment-12860675 should give you the behavior you are looking for.

**Comment by LumpBloom7** [comment]
But it would be better if it would just do it without extra procedures. Steam client does not show at all and only the tray icon can be seen if a Steam game was started through the GNOME/Unity dash.

**Comment by Tele42** [comment]
When that env variable was put into place in 2013, libappindicator was unreliable depending on which desktop environment you use. I do not know if the situation has changed, but my understanding is that it is undesirable to have steam is running without a user visible window and no tray icon at the same time.

**Comment by LumpBloom7** [comment]
If other apps can do it, why can't Steam fix theirs to do the same. 
Examples of apps that can completely hide to tray: Transmission, Whatsie

**Comment by gdrewb-valve** [comment]
Closing duplicate.
