### ISSUE TITLE
Games won't start

### ISSUE THREAD

**Issue by d3rrial** [ValveSoftware/steam-for-linux#4478]
#### Your system information

* Steam client version: Apr. 29 (API v017)
* Distribution: x86_64 Linux 4.5.4-1-ARCH
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### My issue in as much detail as possible:
Whenever I try starting a game from within Steam, the launcher opens, my status changes to "In Game" and then the launcher immediately closes and my status changes back to "Online" with no game started. This used to only happen to Borderlands 2 and Dota 2, but it didn't happen to CS:GO in the past. Now it's also happening with CS:GO.

It's not much of a problem with Borderlands and Dota, because I can just start them from the commandline, but I can't start CS:GO from the commandline without the game detecting it as "Unsafe Mode" and not allowing me to join ranked matches.

I've done everything that's suggested on the Arch wiki, nothing helped. I've tried both with Steam In-Game UI enabled and disabled.

Excerpt from Steam System Information tool:

Operating System Version:
-    Linux (64 bit)
-    Kernel Name:  Linux
-    Kernel Version:  4.5.4-1-ARCH
-    X Server Vendor:  The X.Org Foundation
-    X Server Release:  11803000
-    X Window Manager:  i3
-    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
-    Driver:  X.Org Gallium 0.4 on AMD HAWAII (DRM 2.43.0, LLVM 3.8.0)
-    Driver Version:  3.0 Mesa 11.2.2
-    OpenGL Version: 3.0

#### Steps for reproducing this issue:

1. Start any of those games: Dota 2, CS:GO, Borderlands 2

> Game update: AppID 730 "Counter-Strike: Global Offensive", ProcID 4115, IP 0.0.0.0:0
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> pid 4117 != 4116, skipping destruction (fork without exec?)
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/usr/lib32/libxcb.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/username/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/tls/radeonsi_dri.so
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/radeonsi_dri.so
> libGL: dlopen /usr/lib32/xorg/modules/dri/radeonsi_dri.so failed (/usr/lib32/xorg/modules/dri/radeonsi_dri.so: wrong ELF class: ELFCLASS32)
> libGL error: unable to load driver: radeonsi_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: radeonsi
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/tls/swrast_dri.so
> libGL: OpenDriver: trying /usr/lib32/xorg/modules/dri/swrast_dri.so
> libGL: dlopen /usr/lib32/xorg/modules/dri/swrast_dri.so failed (/usr/lib32/xorg/modules/dri/swrast_dri.so: wrong ELF class: ELFCLASS32)
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> /home/username/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo.sh: line 64:  4119 Segmentation fault      (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
> Game removed: AppID 730 "Counter-Strike: Global Offensive", ProcID 4115 
> No cached sticky mapping in ActivateActionSet.

**Comment by LinuxDonald** [comment]
Have you already looked here? https://wiki.archlinux.org/index.php/Steam/Troubleshooting

**Comment by d3rrial** [comment]
I did say that I went through everything on the Arch wiki, so yes. But thanks

**Comment by za3k** [comment]
@d3rrial , can you mention what specifically the problem was and what specifically you did to fix it? (Which library?)

**Comment by ainiml** [comment]
same

```
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fcd9c6eb6d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fcd98aaee08) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
```

not really sure what errors are relevant here

**Comment by za3k** [comment]
@ainiml, open a new bug. This one is closed and probably not the same issue.
