### ISSUE TITLE
Bad performance when running RepPy games

### ISSUE THREAD

**Issue by kapsh** [ValveSoftware/steam-for-linux#4482]
#### Your system information
- Steam client version: Apr 29 2016 
- Distribution (e.g. Ubuntu): Gentoo x86-64
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

When I am trying to run any game on RenPy from Steam (e.g. with Play button) it shows me message "This computer is displaying graphics slowly". Game window becomes heavy laggy and unusable. I attached Steam logs and two logs from game (Sakura Dungeon in this case) — one from direct launch and other from steam launch. 

[kapsh_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/301295/kapsh_log.txt)
[kapsh_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/301296/kapsh_stdout.txt)
[gamelog_bad.txt](https://github.com/ValveSoftware/steam-for-linux/files/301298/log.txt)
[gamelog_good.txt](https://github.com/ValveSoftware/steam-for-linux/files/301307/log.txt)

When I launch same game without Steam (with gamename.sh from it distribution) everything works normally. 
#### Steps for reproducing this issue:
1. Run any renpy-based game from Steam application. 
2. Suffer.

**Comment by gdrewb-valve** [comment]
If you disable the Steam overlay in the Steam properties for the game does that help?

**Comment by kapsh** [comment]
No, that doesn't help.

**Comment by Oxalin** [comment]
From Steam, what do you get under Help -> System Information -> Video Card? Is there an OpenGL driver listed?

**Comment by Tele42** [comment]
For what it's worth, the steam-meta package from steam-overlay has a fairly complete dependency tree if you set ```USE="-steamruntime"```, but dependency issues have to go to the overlay instead of here if you use that useflag.

**Comment by kapsh** [comment]
I have "steamruntime" use flag enabled. 

Here is system information gotten from Steam application:
```
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) x86/MMX/SSE2

    Driver Version:  3.0 Mesa 11.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x1912
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.90" x 10.63"  (21.65" diag)
                                            48.0cm x 27.0cm  (55.0cm diag)
    Primary VRAM Not Detected
```

**Comment by kapsh** [comment]
Hello again.

Now I am using the same system but with nvidia video card running proprietary driver (instead of CPU's builtin stub). And Steam detects it properly:
{{{
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.90" x 10.63"  (21.65" diag)
                                            48.0cm x 27.0cm  (55.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
}}}

**Comment by kisak-valve** [comment]
Hello @kapsh, are you still experiencing this issue on an up to date system?

**Comment by kapsh** [comment]
@kisak-valve hello. My environment has changed a lot since opening this ticket. I can only say that I don't remember encountering similar errors in the near past. Also checked game mentioned in topic, it runs out of the box on current Steam beta.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
