### ISSUE TITLE
Steam won't launch civilization 5

### ISSUE THREAD

**Issue by ZiLot34** [ValveSoftware/steam-for-linux#4483]
* Steam client version: Apr 29 2016, 22:27:58
* Distribution (e.g. Ubuntu): arch linux
* Opted into Steam client beta?: [Yes/No] No 
* Have you checked for system updates?: [Yes/No] Yes

Hello.
Few days ago civilization 5 was running without a single issue. Now it doesn't start when launching with steam. 
Here is the terminal output :

```
Game update: AppID 8930 "Sid Meier's Civilization V", ProcID 17281, IP 0.0.0.0:0
ERROR: ld.so: object '/home/zilot/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/zilot/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197990842332 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(20160429221935)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Game removed: AppID 8930 "Sid Meier's Civilization V", ProcID 17282 
No cached sticky mapping in ActivateActionSet.
```

However, If I run the game directly with
` ~/.local/share/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ V/Civ5XP`
it works. 

It seems that's I'm not the first to encounter this issue, I already saw threads talking about it but often the terminal gives some clues about a missing library or a segfault... and all the solution that were given didn't solved my issue. 

Thx.

**Comment by ZiLot34** [comment]
game

**Comment by ademar111190** [comment]
I'm getting the same issue, and running by command line works:

```
Generating new string page texture 116: 256x256, total string texture memory is 2,38 MB
Game update: AppID 8930 "Sid Meier's Civilization V", ProcID 3782, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ademar/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 3782 for game ID 8930
ERROR: ld.so: object '/home/ademar/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
/home/ademar/.local/share/Steam/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv120__si_class_type_infoE' has different size in shared object, consider re-linking
/home/ademar/.local/share/Steam/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv117__class_type_infoE' has different size in shared object, consider re-linking
/home/ademar/.local/share/Steam/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv121__vmi_class_type_infoE' has different size in shared object, consider re-linking
>>> Adding process 3783 for game ID 8930
Game removed: AppID 8930 "Sid Meier's Civilization V", ProcID 3782 
No cached sticky mapping in ActivateActionSet.% 
```

**Comment by plomp90** [comment]
Yup, this is still an issue. My version of arch is completely up-to-date, and I still cannot run from steam (but can from command line), and I'm getting the exact same errors. I really hope someone fixes this soon, I'd like to be able to play online.

**Comment by Pillgar** [comment]
Can't launch via Steam either.  Launches fine in a terminal as others have reported using: ~/.local/share/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ V/Civ5XP.   Latest kernel in Arch also.

**Comment by DoMiNeLa10** [comment]
I can't run the game from Steam, but launching the binary directly works. I can post errors I get in terminal, and I see a segfault in dmesg after launching the game.

@Pillgar: it's possible to play online if you put game's appid (that's 8390) in `steam_appid.txt` and run the binary while Steam is running. I got the game to work online that way.

**Comment by chrjguill** [comment]
if I run `Civ5XP` directly:

`🐺  ~/.local/share/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ V/Civ5XP 
/home/arcana/.local/share/Steam/steamapps/common/Sid Meier's Civilization V/Civ5XP: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

It works fine when I run it from the directory, but online doesn't work, even with the local steam_appid.txt - I get the following output, but the overlay never loads, and I'm not listed as in-game.

`Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198092295564 [API loaded no]
`
In fact - the following happens in my steam client:

![image](https://user-images.githubusercontent.com/3235827/29566231-110639e6-8717-11e7-8da2-b15c02390e2e.png)

There definitely seems to be a bug _somewhere_ with running steam games from outside of steam.

**Comment by venthur** [comment]
The issue is still present on Debian/Sid, tested on two different machines.

**Comment by ixaxaar** [comment]
+1 Issue present on Arch. 
In fact trying to directly launch gives me this:

```
./Civ5XP                                                                                                                               139 ↵
GUID Assets\dlc\dlc_01\mongol.civ5pkg 7a036b7fb9a80e8dea7b73fb58c5a288
GUID Assets\dlc\dlc_02\spaininca.civ5pkg 4f75e72761f4c6019b55a0a7b90444a2
GUID Assets\dlc\dlc_03\polynesia.civ5pkg 99ac9d5f6ca4b5bed0ab89c0fd3b9e6d
GUID Assets\dlc\dlc_04\denmark.civ5pkg 0efb155307bd6d14c9290b49b5364a3e
GUID Assets\dlc\dlc_05\korea.civ5pkg 9f4df81cf712ae9480737f816bf6f4c8
GUID Assets\dlc\dlc_06\ancientwonders.civ5pkg 92b102db9a3c7dc068030c3ce33bbb48
GUID Assets\dlc\dlc_07\civcomplete.civ5pkg eb01a0be4d8e5312f53b042c8a7c30b5
GUID Assets\dlc\dlc_deluxe\babylon.civ5pkg 712495341921f2b288746c6d44fd6867
GUID Assets\dlc\dlc_sp_maps\dlc_sp_maps.civ5pkg 52b285c37939913e0a5b72933bb06067
GUID Assets\dlc\dlc_sp_maps_2\dlc_sp_maps_2.civ5pkg 16a61e7a2a7bb4bc2d1f677b5bb58ff4
GUID Assets\dlc\dlc_sp_maps_3\dlc_sp_maps_3.civ5pkg 1954db58e0a60b018969c49440fa01ef
GUID Assets\dlc\expansion\expansion1.civ5pkg 8bc30c58378345cb0911c5848926f1ff
GUID Assets\dlc\expansion2\expansion2.civ5pkg 31dfaa9838c5b051d4c2112ddd9e7eb3
GUID Assets\dlc\shared\upgrade1.civ5pkg e818fa28902977b42ee5e3426f5112e6

[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
[1]    6992 segmentation fault (core dumped)  ./Civ5XP
```

and via steam :

```
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to ProcessingShaderCache with ""
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 8930, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 8930, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 70
Game update: AppID 8930 "", ProcID 5867, IP 0.0.0.0:0
ERROR: ld.so: object '/home/ixaxaar/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 5867 for game ID 8930
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/ixaxaar/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to Completed with ""
>>> Adding process 5868 for game ID 8930
Game update: AppID 8930 "", ProcID 5868, IP 0.0.0.0:0
Setting breakpad minidump AppID = 8930
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198086597123 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(20180724182706)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1532458786)
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
Installing breakpad exception handler for appid(steam)/version(1532458786)
Game removed: AppID 8930 "", ProcID 5868 
No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
```

**Comment by EUA** [comment]
On my Arch Linux (x64), the issue is the OpenAL.
journalctl -e:
```Eyl 10 14:42:30 Ryzen systemd-coredump[22167]: Process 22128 (Civ5XP) of user 1000 dumped core.
                                               
                                               Stack trace of thread 22141:
                                               #0  0x00000000e30634e1 pa_smoother_new (libpulsecommon-12.2.so)
                                               #1  0x00000000e30cd9d4 n/a (libpulse.so.0)
                                               #2  0x00000000f77a409b n/a (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
                                               #3  0x00000000f77a432c n/a (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
                                               #4  0x00000000f777b9a3 alcCreateContext (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
                                               #5  0x0000000009126f4a YUV12 (Civ5XP)
                                               #6  0x00000000091264a2 YUV12 (Civ5XP)
                                               #7  0x0000000009113bee check_for_pending_io (Civ5XP)
                                               #8  0x0000000009114188 BinkOpen (Civ5XP)

```
And this solves my problem:
`LD_PRELOAD="/usr/lib32/libopenal.so.1" steam-native`

**Comment by kisak-valve** [comment]
Hello @EUA, sounds like you should check for a game-bundled openal library and see if moving it out of the way helps.

**Comment by addeps3** [comment]
> +1 Issue present on Arch.
> In fact trying to directly launch gives me this:
> 
> ```
> ./Civ5XP                                                                                                                               139 ↵
> GUID Assets\dlc\dlc_01\mongol.civ5pkg 7a036b7fb9a80e8dea7b73fb58c5a288
> GUID Assets\dlc\dlc_02\spaininca.civ5pkg 4f75e72761f4c6019b55a0a7b90444a2
> GUID Assets\dlc\dlc_03\polynesia.civ5pkg 99ac9d5f6ca4b5bed0ab89c0fd3b9e6d
> GUID Assets\dlc\dlc_04\denmark.civ5pkg 0efb155307bd6d14c9290b49b5364a3e
> GUID Assets\dlc\dlc_05\korea.civ5pkg 9f4df81cf712ae9480737f816bf6f4c8
> GUID Assets\dlc\dlc_06\ancientwonders.civ5pkg 92b102db9a3c7dc068030c3ce33bbb48
> GUID Assets\dlc\dlc_07\civcomplete.civ5pkg eb01a0be4d8e5312f53b042c8a7c30b5
> GUID Assets\dlc\dlc_deluxe\babylon.civ5pkg 712495341921f2b288746c6d44fd6867
> GUID Assets\dlc\dlc_sp_maps\dlc_sp_maps.civ5pkg 52b285c37939913e0a5b72933bb06067
> GUID Assets\dlc\dlc_sp_maps_2\dlc_sp_maps_2.civ5pkg 16a61e7a2a7bb4bc2d1f677b5bb58ff4
> GUID Assets\dlc\dlc_sp_maps_3\dlc_sp_maps_3.civ5pkg 1954db58e0a60b018969c49440fa01ef
> GUID Assets\dlc\expansion\expansion1.civ5pkg 8bc30c58378345cb0911c5848926f1ff
> GUID Assets\dlc\expansion2\expansion2.civ5pkg 31dfaa9838c5b051d4c2112ddd9e7eb3
> GUID Assets\dlc\shared\upgrade1.civ5pkg e818fa28902977b42ee5e3426f5112e6
> 
> [S_API FAIL] SteamAPI_Init() failed; no appID found.
> Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
> [1]    6992 segmentation fault (core dumped)  ./Civ5XP
> ```
> 
> and via steam :
> 
> ```
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to ProcessingShaderCache with ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
> GameAction [AppID 8930, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
> Opted-in Controller Mask: 70
> Game update: AppID 8930 "", ProcID 5867, IP 0.0.0.0:0
> ERROR: ld.so: object '/home/ixaxaar/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> >>> Adding process 5867 for game ID 8930
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
> ERROR: ld.so: object '/home/ixaxaar/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> GameAction [AppID 8930, ActionID 2] : LaunchApp changed task to Completed with ""
> >>> Adding process 5868 for game ID 8930
> Game update: AppID 8930 "", ProcID 5868, IP 0.0.0.0:0
> Setting breakpad minidump AppID = 8930
> Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198086597123 [API loaded no]
> Installing breakpad exception handler for appid(gameoverlayui)/version(20180724182706)
> Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
> Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
> Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
> Installing breakpad exception handler for appid(steam)/version(1532458786)
> JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
> Installing breakpad exception handler for appid(steam)/version(1532458786)
> Game removed: AppID 8930 "", ProcID 5868 
> No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
> ```
Solution is to:
export LD_PRELOAD=/usr/lib32/libopenal.so.1
./Civ5XP

**Comment by addeps3** [comment]
Just as a variation, I use:
```
export LD_PRELOAD=/usr/lib32/libopenal.so.1
./Civ5XP
```

**Comment by icf20** [comment]
did anyone manage to solve this ?

**Comment by danielrobbinssmells** [comment]
@icf20 what did I write on nov 28?

**Comment by addeps3** [comment]
@icf20  
What did I write on Nov 28?

**Comment by icf20** [comment]
@addeps3 yes, i tested that and dint work today

**Comment by addeps3** [comment]
@icf20 Did you start Civ5 from its data directory? Meaning directly via terminal, and not via Steam?

**Comment by jarrard** [comment]
No cached sticky mapping in ActivateActionSet. Error actually happens with war thunder running under Proton also, clearly its a library issue somewhere.

**Comment by Nayr438** [comment]
On Arch Linux I do have to use "LD_PRELOAD=/usr/lib32/libopenal.so.1 %command%" in Launch Options for the Game to Start. I do have the "native-steam-runtime" installed as well and may or may not be needed. 

> No cached sticky mapping in ActivateActionSet.
> Error actually happens with war thunder running under Proton also, clearly its a library issue somewhere.
> 
> Don't think LD_PRELOAD=/usr/lib32/libopenal.so.1 resolves this problem in my case.
From what I have gathered from other game issues "No cached sticky mapping in ActivateActionSet" shouldn't prevent the game from starting. What distribution are you running?

**Comment by jarrard** [comment]
antergos kde

**Comment by Nayr438** [comment]
> antergos kde
Its basically the same as Arch.
I did however do a clean install of Antergos KDE  with  "nvidia" "steam" and "lib32-libpulse" and can confirm that installing "steam-native-runtime" and adding "LD_PRELOAD=/usr/lib32/libopenal.so.1 %command%" to the Launch Options makes the game playable. If your still having issues, you can try posting any library errors the konsole spits out when steam is launching the game.

**Comment by jarrard** [comment]
Yeah that doesn't work for me with War Thunder windows64 exe. Just closes in steam, works fine in Lutris.

**Comment by Nayr438** [comment]
My post was mostly regarding "Civilization 5" For "War Thunder" I will have to look into that since I don't personally play it. I do however see your issue under Proton. So I will message back there if I find a solution.

**Comment by azat-io** [comment]
The same problem for Civilization V and The Binding of Isaac

**Comment by simsilver** [comment]
> On my Arch Linux (x64), the issue is the OpenAL.
> journalctl -e:
> 
> ```
>                                                
>                                                Stack trace of thread 22141:
>                                                #0  0x00000000e30634e1 pa_smoother_new (libpulsecommon-12.2.so)
>                                                #1  0x00000000e30cd9d4 n/a (libpulse.so.0)
>                                                #2  0x00000000f77a409b n/a (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
>                                                #3  0x00000000f77a432c n/a (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
>                                                #4  0x00000000f777b9a3 alcCreateContext (/mnt/Programming/SteamLibrary/steamapps/common/Sid Meier's Civilization V/libopenal.so.1)
>                                                #5  0x0000000009126f4a YUV12 (Civ5XP)
>                                                #6  0x00000000091264a2 YUV12 (Civ5XP)
>                                                #7  0x0000000009113bee check_for_pending_io (Civ5XP)
>                                                #8  0x0000000009114188 BinkOpen (Civ5XP)
> ```
> 
> And this solves my problem:
> `LD_PRELOAD="/usr/lib32/libopenal.so.1" steam-native`

I don't use steam-natvie, so just rename libopenal.so.1 in the game folder and it works well

**Comment by carabolic** [comment]
Thank you @simsilver. removing/moving the openal files from `~/.local/share/Steam/steamapps/common/Sid Meier's Civilization V` resolved the issue for me. Before running it directly from the command line gave me `./Civ5XP: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`
