### ISSUE TITLE
Segmentation fault if the password is being remembered

### ISSUE THREAD

**Issue by Sworddragon** [ValveSoftware/steam-for-linux#4484]
#### Your system information
- Steam client version: 1461972496 (a -v/--version argument could help)
- Distribution (e.g. Ubuntu): Ubuntu 16.10 dev
- Opted into Steam client beta?: No 
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

On login if the checkbox for remembering the password is checked Steam crashes the next time it gets started (with "./steam.sh: line 756: 52797 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@""). A workaround is to set RememberPassword to 0 in ~/.steam/steam/config/SteamAppData.vdf.
#### Steps for reproducing this issue:
1. Start Steam and login with enabling the checkbox to remember your password.
2. Exit Steam.
3. Start Steam again.

Now Steam crashes with the error message above printed to the last line in the terminal.

**Comment by Sworddragon** [comment]
The issue still exists with an up-to-date upstream Steam. The old workaround did not work for me anymore but it seems deleting the key "InstallConfigStore" -> "Software" -> "Valve" -> "Steam" -> "MTBF" in ~/.steam/steam/config/config.vdf does the trick too.

**Comment by kisak-valve** [comment]
Hello @Sworddragon, are you still experiencing this issue on an up to date system? If you are, can you check if you have a system-wide dbus instance running?

**Comment by kisak-valve** [comment]
Closing pending feedback.
