### ISSUE TITLE
Official Repo Is Stuck On 12.04, Latest Version Is 16.04

### ISSUE THREAD

**Issue by sudopluto** [ValveSoftware/steam-for-linux#4485]
#### Your system information
- Steam client version: Latest
- Distribution (e.g. Ubuntu): Ubuntu
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

The repo for ubuntu is still labeled for 12.04, while latest version is 16.04
#### Steps for reproducing this issue:
1. go to http://repo.steampowered.com/steam/
2. go to archive

**Comment by gdrewb-valve** [comment]
I believe this is intentional since the Steam runtime was based on 12.04.

**Comment by sudopluto** [comment]
Two points:

- this naming style could be confusing for users because when they update ubuntu, they see the steam repo labeled as a 12.04 repository. maybe it could be renamed to something like "stable" like google does with chrome

-is the steam runtime still based off of 12.04? I could only imagine that that would cause issues in bleeding edge distros like arch.

**Comment by gdrewb-valve** [comment]
The naming is up to the Steam team, they'll comment here if they want to weigh in.  The runtime still mimics 12.04, it's intended to be a fixed platform to target.

**Comment by YtvwlD** [comment]
> -is the steam runtime still based off of 12.04? I could only imagine that that would cause issues in bleeding edge distros like arch.

It even causes issues in the current version of Ubuntu (see https://github.com/ValveSoftware/steam-for-linux/issues/172#issuecomment-225929024).
