### ISSUE TITLE
Start using rust programing languague

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4487]
A truly successor to c/c++

"Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety. "

Featuring:
    zero-cost abstractions
    move semantics
    guaranteed memory safety
    threads without data races
    trait-based generics
    pattern matching
    type inference
    minimal runtime
    efficient C bindings

https://www.rust-lang.org/

**Comment by Tele42** [comment]
Requesting the entire steam project be rewritten in another language is both gratuitous and unnecessary. While rust may be a good idea for new projects where appropriate, you are asking valve to throw away all previous work on the steam client and make a new client from scratch.

**Comment by ekaris** [comment]
I'm not asking that, I'm asking to start using rust in some parts.

**Comment by gdrewb-valve** [comment]
Sorry, I don't believe this is going to happen.
