### ISSUE TITLE
MESA_GL_VERSION_OVERRIDE not working after update to June 10 2016 steam version

### ISSUE THREAD

**Issue by mezcalbert** [ValveSoftware/steam-for-linux#4491]
#### Your system information

* Steam client version: June 10 2016 | API v017 | Package versions 1465507923
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I'm running on Ubuntu 16.04, latest Mesa-dev, with r600g open source driver and latest kernel (4.7 rc2).

#### Please describe your issue in as much detail as possible:

Dirt Showdown was expected to run (as before latest update)

The game worked flawlessly until yesterday's latest update but now I get the "Unfortunately your machine does not meet the full OpenGL 4.1 requirements so the game may not perform correctly" error again. This is not expected behaviour since I'm overriding it. 

it doesn't occur on Manjaro gnome 16.06 after update, and this Ubuntu-specific issue persists even when rolling back to stable kernel and mesa.

#### Steps for reproducing this issue:

1. Use the following launch options to run Dirt Showdown: MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410 DRI_PRIME=1 %command%
2. Start the game before the update with these launch options, works flawlessly.
3. Update Steam client to June 10 2016 stable version.
4. Start the game after the update with same launch options. Doesn't work anymore.

![screenshot from 2016-06-11 14-14-39](https://cloud.githubusercontent.com/assets/19873056/15985128/c5b2ddc2-2fe3-11e6-921f-97b2e79e895b.png)

**Comment by mezcalbert** [comment]
This have been solved in the meantime.
I had tried different versions of Mesa and of the kernel without any luck and it worked on Manjaro, so it was either due to r600g driver (xserver-xorg-video-ati-....) or Steam. But since it didn't work right after a Steam update, I still believe it was due to the update. Probably what went awry got tinkered with in a later update and it now works again.

**Comment by darky** [comment]
I confirm this issue on steam version for now.

**Comment by darky** [comment]
Not working with:
* Mesa - 17.3.0-rc1.
* Driver - amdgpu or i915
* Steam version - Oct 30 2017
