### ISSUE TITLE
Failed to create D3D device after update to June 10 steam version

### ISSUE THREAD

**Issue by mezcalbert** [ValveSoftware/steam-for-linux#4492]
#### Your system information

    Steam client version: June 10 2016 | API v017 | Package versions 1465507923
    Distribution (e.g. Ubuntu): Ubuntu 16.04
    Opted into Steam client beta?: [Yes/No] No
    Have you checked for system updates?: [Yes/No] Yes

I'm running on Ubuntu 16.04, latest Mesa-dev, with r600g open source driver and latest kernel (4.7 rc2).

#### Please describe your issue in as much detail as possible:

Dirt Showdown was expected to run (as before latest update).

The game worked flawlessly until yesterday's latest update but now I get the "Failed to create D3D Device" error. Right after issue #4491 occurs.

As for #4491, it doesn't occur on Manjaro gnome 16.06 after update, and this Ubuntu-specific issue persists even when rolling back to stable kernel and mesa.

Please be aware this issue may be closely linked to issue #4491 

#### Steps for reproducing this issue:

1. Use the following launch options to run Dirt Showdown:
MESA_GL_VERSION_OVERRIDE=4.1 MESA_GLSL_VERSION_OVERRIDE=410 DRI_PRIME=1 %command%
2. Start the game before the update with these launch options, works flawlessly.
3. Update Steam client to June 10 2016 stable version.
4. Start the game after the update with same launch options.
5. First I receive the message such as in issue #4491 
6. Then I receive a second error: "Failed to create D3D device" as seen in attached screenshot. This is a Windows related issue, which is wrong.

![screenshot from 2016-06-11 14-15-02](https://cloud.githubusercontent.com/assets/19873056/15985495/b338bad4-2fef-11e6-80d1-0afbea91a87c.png)

**Comment by Tele42** [comment]
The most likely cause of this is that you removed some steam runtime libraries in the past to get steam to behave with mesa on ubuntu 16.04, and the steam client update has regenerated the removed libraries. You can try the <a href="https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues">arch workaround</a> and see if that improves your experience.

**Comment by mezcalbert** [comment]
Indeed, I had tinkered quite a bit along time with runtime libraries.

I did a steam --reset. Then I started Steam with system libraries preload and finally by removing Steam runtime libraries as mentionned in the Arch workaround.

To no avail.

**Comment by mezcalbert** [comment]
Linked to [#4491](https://github.com/ValveSoftware/steam-for-linux/issues/4491) and as foreseen they were solved together.
