### ISSUE TITLE
S3TC texture support cannot be found after June 10 2016 Steam update

### ISSUE THREAD

**Issue by mezcalbert** [ValveSoftware/steam-for-linux#4493]
#### Your system information

Steam client version: June 10 2016 | API v017 | Package versions 1465507923
Distribution (e.g. Ubuntu): Ubuntu 16.04
Opted into Steam client beta?: [Yes/No] No
Have you checked for system updates?: [Yes/No] Yes

I'm running on Ubuntu 16.04, latest Mesa-dev, with r600g open source driver and latest kernel (4.7 rc2).
#### Please describe your issue in as much detail as possible:

Team Fortress 2 is expected to run (as before latest update).

The game worked flawlessly until yesterday's latest update but now I get a S3TC texture support related error such as described in the screenshot below. Basically, Steam can't find GL_EXT_texture_compression_s3tc.

But I can start the game if I start Steam with
`$ force_s3tc_enable=true steam`

libtxc-dxtn-s2tc0 was installed a few weeks ago (and is still installed). The game started perfectly up to yesterday's steam update.
#### Steps for reproducing this issue:
1. Start the game before the update with package libtxc-dxtn-s2tc0 installed, works flawlessly.
2. Update Steam client to June 10 2016 stable version.
3. Start the game after the update. Error received such as in screenshot. As can be seen in the screenshot, libtxc-dxtn-s2tc0 is still installed.

![screenshot from 2016-06-11 14-14-02](https://cloud.githubusercontent.com/assets/19873056/15985529/f47f5da8-2ff0-11e6-9ed8-6325e04b85c6.png)

**Comment by gdrewb-valve** [comment]
Presumably the same thing as #4491 and #4492.

**Comment by Uramekus** [comment]
above issues were fixed, all S3TC support was mainlined on mesa, requesting for closure.

**Comment by kisak-valve** [comment]
Thanks @Uramekus, anyone seeing this issue should update to mesa 17.3 or newer.
