### ISSUE TITLE
Steam won't do anything at all

### ISSUE THREAD

**Issue by majoramaster** [ValveSoftware/steam-for-linux#4495]
I use Ubuntu 16.04, the current version of Steam will not even complete installation. I can't play games, I can't even open the program. My system is up to date, steam is up date. it just won't work.

when I attempt to open Steam through Terminal, this is the result:

Repairing installation, linking /home/stephen/.steam/steam to /home/stephen/.local/share/Steam
rm: cannot remove '/home/stephen/.steam/steam': Is a directory
Setting up Steam content in /home/stephen/.local/share/Steam
rm: cannot remove '/home/stephen/.steam/steam': Is a directory

Steam support has been no help, here is the link to that conversation: [https://support.steampowered.com/view.php?ticketref=5774-TZCB-3123]

**Comment by 1ShotSniper** [comment]
Same problem, Linux Mint 18 beta (based on Ubuntu 16.04).

rm: cannot remove '/home/tango/.steam/steam': Is a directory
rm: cannot remove '/home/tango/.steam/bin': Is a directory
/bin/bash: /home/tango/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
awk: /home/tango/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
Installing breakpad exception handler for appid(steam)/version(1465507923)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by Tele42** [comment]
@1ShotSniper in your case, take a look at the <a href="https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues">arch workaround</a>. There is a long standing steam runtime compatibility issue with mesa 10.5 and newer.

**Comment by 1ShotSniper** [comment]
Thank you @Tele42 , my problem has been solved.

**Comment by majoramaster** [comment]
Unfortunatly, this seemed to not work at all. Thanks for trying tho @Tele42

**Comment by Tele42** [comment]
@majoramaster right, sorry, that was specifically addressed at @1ShotSniper. Where did you install steam from? Ideally, you should be using the steam package from ubuntu's repositories for 16.04.

**Comment by majoramaster** [comment]
I installed mine directly from the Steam website. whichever version they have in the "download" tab is what I've been trying to install ever few days.

**Comment by Tele42** [comment]
@majoramaster: https://www.reddit.com/r/linux_gaming/comments/4g2tij/your_steam_package_is_out_of_date_ubuntu_1604/d2gfnd7 looks like the right instructions for switching from the steam bootstrapper on valve's site to the ubuntu 16.04 variant. Worst case scenario you can just do the instructions in reverse to get back to where you are now.

**Comment by majoramaster** [comment]
@Tele42 
Alas, twas for naught. It unfortunatly returned the same results.

**Comment by YtvwlD** [comment]
@majoramaster I had the same problem. And I think, I've solved it. (see https://github.com/ValveSoftware/steam-for-linux/issues/172#issuecomment-225929024)

**Comment by majoramaster** [comment]
@YtvwlD that wasn't what I got when trying to execute Steam. but thanks anyways

**Comment by Tele42** [comment]
@majoramaster has steam ever worked on your system? What video driver version are you using?

**Comment by majoramaster** [comment]
I'm not sure about video driver, but Steam worked perfectly when I was
using Ubuntu 14.04. I never even really got any lag. it has just been since
I updated to 16.04 that it has not worked.

**Comment by YtvwlD** [comment]
That has been the case for me, too.

**Comment by majoramaster** [comment]
I tried your fix tho and it did not help at all

**Comment by phantom-voltage** [comment]
I have the same error after upgrading to 16.04. 

On the commandline I get:

```
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
```

This gives me an error in the GUI, 
"Fatal Error: Failed to load steamui.so"

**Comment by KathyReid** [comment]
Status: currently unresolved

Exactly the same issue, command line same as above when running Steam from the command line. Running Ubuntu 16.04 on Asus-N76 hardware with Nvidia graphics. 

Here is what I've tried so far: 

- https://askubuntu.com/questions/648905/get-steamupdateui-an-x-error-occurred-when-trying-to-run-steam/786997 - that is, deleting a bunch of outdated libraries and installing another package. Still failing. 
- re-installing, moving to another directory, yada yada. 
- tried disabling the Steam runtime as documented here - https://github.com/ValveSoftware/steam-for-linux/issues/172#issuecomment-225929024

**Current status** - when I run steam from the  command line I get the following output: 

```
kathyreid@kathyreid-N76VZ:~/.steam/steam/ubuntu12_32/steam-runtime$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libXtst.so.6
libXrandr.so.2
libGL.so.1
libgtk-x11-2.0.so.0
libgdk_pixbuf-2.0.so.0

Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
Installing breakpad exception handler for appid(steam)/version(1471977975)
[2016-08-27 10:19:42] Startup - updater built Aug 23 2016 18:24:59
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-08-27 10:19:42] Checking for update on startup
[2016-08-27 10:19:42] Checking for available updates...
[2016-08-27 10:19:43] Download skipped: /client/steam_client_ubuntu12 version 1471977975, installed version 1471977975
[2016-08-27 10:19:43] Nothing to do
[2016-08-27 10:19:43] Verifying installation...
[2016-08-27 10:19:43] Performing checksum verification of executable files
[2016-08-27 10:19:44] Verification complete
[2016-08-27 10:19:47] Shutdown
```

Should I manually install the following libs? :
libXtst

- .so.6
- libXrandr.so.2
- libGL.so.1
- libgtk-x11-2.0.so.0
- libgdk_pixbuf-2.0.so.0
-

**Comment by kisak-valve** [comment]
Hello, is anyone who commented on this issue report still having trouble starting Steam on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
