### ISSUE TITLE
Steam Still Visible In Top Left Corner

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#4496]
#### Your system information
- Steam client version: June 10th 2016 beta
- Distribution (e.g. Ubuntu): Arch (Testing)
- Opted into Steam client beta?: [Yes/No] Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Part of Steam is imposed on the top left of the screen. Just a little rectangle of it. This has been going on for 2 years, even when I used Debian Sid. I thought the bug was with Linux, but after so many years going by, I now think its a Steam bug. This doesn't happen when you're in small mode, only in large mode.
#### Steps for reproducing this issue:
1. Open Steam
2. Make sure you're in large mode
3. Open Game

![13453992_1597212967256641_838669483_n](https://cloud.githubusercontent.com/assets/5150898/16034213/78cae48a-31de-11e6-99fd-0085de3bf547.jpg)
![13435713_1597213013923303_1914843683_n](https://cloud.githubusercontent.com/assets/5150898/16034218/7f850be8-31de-11e6-93b6-19b7eb4e3d83.jpg)

**Comment by shoober420** [comment]
By the way, my system information is in my Steam profile, which is linked in my github profile. I also have the Render and composite extensions disabled.

**Comment by gdrewb-valve** [comment]
Duplicate of other issues still open.

**Comment by shoober420** [comment]
I haven't had this happen for a long time, so I'm closing this issue. Thank you for fixing this.
