### ISSUE TITLE
Stop the insanity and switch to Snappy?

### ISSUE THREAD

**Issue by mg-13** [ValveSoftware/steam-for-linux#4499]
#### Your system information

* Steam client version: the current one
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
We know the insanity of steam downloading and dropping all the dynamically linked libs into /home. This seems to be a pragmatic solution, but it is problematic and non-standard, ugly behaviour and often leads to problems.
Switch the steam client over to a snap package. Canonical standardised this package format for exactly this use case when apps depend on specific versions of libs. snapd has been ported to other distributions already: [ubuntu insights](https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/)

#### Steps for reproducing this issue:

1. Install any Linux distribution
2. Try to install Steam
3. Try to launch Steam
4. Install games
5. Try to launch games

**Comment by gdrewb-valve** [comment]
Closing duplicate.

**Comment by mg-13** [comment]
I could not find the original issue.

Could you please link to the duplicate when closing?

**Comment by Tele42** [comment]
@gdrewb-valve is most likely referring to the Flatpak request from a couple weeks ago (#4473), which has the same intent as this issue report, just a different implementation.

**Comment by gdrewb-valve** [comment]
I was actually referring to the entire set of Steam runtime problems, of which there are many, that are already open here, but I should have been more clear.

**Comment by amarildojr** [comment]
Snap format? "Oh hell no".

Not only this is a very new format (others have implemented this more successfuly), Canonical's CLA's are TERRIBLE and mostly don't allow much external code to be written to *their* creations.
