### ISSUE TITLE
Steam host crashes when trying to stream.

### ISSUE THREAD

**Issue by bjwest** [ValveSoftware/steam-for-linux#4509]
#### Your system information

* See below (two different version reported by Steam, by the way, on in help one in system info)
* See below 
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

Using latest Steam client (built June 14 2016 at 23:24:07 w/ API v017 and package versions 1465948400) on both computers, the steam client on the host computer crashes when I try to stream a game.  This happens both when I initiate the game from either host or client computer.  Client computer displays black screen which closes when host crashes.  Tried with three separate games.  Streaming from a Windows host to Linux client works fine.  Linux to Windows crashes Linux host same as above.  I have only one Windows box, so can't test Win to Win.

I get the following on the terminal:

bjwest@razorback:~$ CCrossProcessPipe::BWrite wrote too few bytes: 32 (Broken pipe).  Continuing.
../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
../common/pipes.cpp (765) : Fatal assert failed: ../common/pipes.cpp, line 765.  Application exiting.

_ExitOnFatalAssert

System Info:

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3900 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750 Ti/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 361.45.11
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1380
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                            52.1cm x 29.3cm  (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC887-VD
    
Memory:
    RAM:  15975 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  2064116 Mb
    Largest Free Hard Disk Block:  181800 Mb
    VR Headset: None detected
    
    Mon Jun 20 02:39:27 2016 GMT: file ''/tmp/dumps/crash_20160616214937_1.dmp'', upload yes: ''CrashID=bp-9e9b091d-41e8-4d82-a61f-4bcd52160619''
    Mon Jun 20 02:39:28 2016 GMT: file ''/tmp/dumps/assert_20160619213927_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:40:49 2016 GMT: file ''/tmp/dumps/assert_20160619214048_5.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:40:49 2016 GMT: file ''/tmp/dumps/crash_20160619214004_1.dmp'', upload yes: ''CrashID=bp-12337d93-2b3f-45e5-a4d0-f87192160619''
    Mon Jun 20 02:41:06 2016 GMT: file ''/tmp/dumps/crash_20160619214106_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:42:32 2016 GMT: file ''/tmp/dumps/crash_20160619214232_6.dmp'', upload yes: ''CrashID=bp-19462048-24ec-410b-a7d4-104c52160619''
    Mon Jun 20 02:42:32 2016 GMT: file ''/tmp/dumps/crash_20160619214124_1.dmp'', upload yes: ''CrashID=bp-04d6b7da-8e24-475e-bf5d-a13672160619''
    Mon Jun 20 02:44:06 2016 GMT: file ''/tmp/dumps/assert_20160619214405_8.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:44:07 2016 GMT: file ''/tmp/dumps/crash_20160619214406_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:45:10 2016 GMT: file ''/tmp/dumps/crash_20160619214452_1.dmp'', upload yes: ''CrashID=bp-efda01fc-ad30-430c-a1f7-0cf2d2160619''
    Mon Jun 20 02:45:12 2016 GMT: file ''/tmp/dumps/crash_20160619214511_6.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:45:27 2016 GMT: file ''/tmp/dumps/crash_20160619214527_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:46:17 2016 GMT: file ''/tmp/dumps/crash_20160619214537_1.dmp'', upload yes: ''CrashID=bp-44e13368-a99c-4207-a427-409182160619''
    Mon Jun 20 02:46:18 2016 GMT: file ''/tmp/dumps/crash_20160619214617_6.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:46:18 2016 GMT: file ''/tmp/dumps/crash_20160619214614_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:46:34 2016 GMT: file ''/tmp/dumps/crash_20160619214633_2.dmp'', upload yes: ''Discarded=1''
    Mon Jun 20 02:47:55 2016 GMT: file ''/tmp/dumps/crash_20160619214725_1.dmp'', upload yes: ''CrashID=bp-25f91dc9-9f11-4ccc-ab24-440dd2160619''
    Mon Jun 20 02:50:49 2016 GMT: file ''/tmp/dumps/crash_20160619214852_1.dmp'', upload yes: ''CrashID=bp-1da97a1b-4527-4d0e-99f5-1235a2160619''
    Mon Jun 20 02:54:25 2016 GMT: file ''/tmp/dumps/crash_20160619215401_1.dmp'', upload yes: ''CrashID=bp-06a895e8-77c5-4724-9606-e9c542160619''

**Comment by bjwest** [comment]
Sorry guys.  This may have been a problem with my system.  I'd had a problem with no audio on in Chrome  and some strange crashes here and there for a couple of days prior.  I rebooted my machine and all is well now.  Streaming works, and audio is back in Chrome.  It'd been a while since my last reboot, I usually put it to sleep at night.  I guess the days of Linux running for years at a time, at least on the desktop, are gone.

The "did you try turning if off and back on again" bug has migrated from Windows to Linux... :(

**Comment by deri82** [comment]
I can't even start steam anymore I get identical output

../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected

**Comment by fedya** [comment]
@deri82 
probably issue in dbus versions in steam container and host system

try this
rm -rf ~/.local/share/Steam/config/
