### ISSUE TITLE
Fails to download or remove DLC

### ISSUE THREAD

**Issue by maulkin** [ValveSoftware/steam-for-linux#4510]
#### Your system information
- Steam client version: 1466475117
- SteamOS version: 2.0 u 1:2.70
- Opted into Steam client beta?: Yes
- Opted into SteamOS beta?: Yes 
- Have you checked for updates in Settings > System?: Yes
#### Please describe your issue in as much detail as possible:

When trying to select DLC for a game (in my example, X-Plane 10), you can't select or deselect any items to install or remove from the library.
#### Steps for reproducing this issue:
1. Select game in library
2. Select Manage DLC
3. Press 'A' on install, or 'uninstall' on any of the DLC items
4. A sound happens, but no icons are changed and no download or uninstall occurs.

**Comment by maulkin** [comment]
Note: moved from SteamOS tracker to here, pertinent information from another user (@beansmyname) is:

> FYI, this is not limited to SteamOS. BPM on desktop distribution of Linux exhibits the same behaviour.
> 
> Steam client version: 1466475117
> Distribution: 64-bit Archlinux
> Opted into Steam client beta?: Yes
> Tested with Awesomenauts where I had 1/2 DLC installed. Pressing 'A' did not cause either item to install or uninstall.
> Also tested with Dota 2 by attempting to install Vulkan support DLC.
> 
> As above, sound indicates button has been pressed but no action occurs.

**Comment by kisak-valve** [comment]
Hello @maulkin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
