### ISSUE TITLE
error running "Egg Returns Home"

### ISSUE THREAD

**Issue by dooglus** [ValveSoftware/steam-for-linux#4522]
#### Your system information
- Steam client version: I let it update recently, then tried switching to the beta program to see if that would help. It didn't. Help->About Steam doesn't give a version number. It tells me the build date though - it's Jun 23 2016 at 00:51:58.
- Distribution (e.g. Ubuntu): Debian GNU/Linux 8.5 (jessie) (64 bit)
- Opted into Steam client beta?: [Yes/No] Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I only installed Steam a month or so ago, and have only installed 4 games. The first 3 worked (and still work) but "Egg Returns Home" doesn't.

When I try to play it, I see a pop-up for a split second saying "Preparing to launch ..." but then it goes away again. Standard output shows this each time I try:

```
Game update: AppID 363790 "Egg Returns Home", ProcID 25842, IP 0.0.0.0:0
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Found path: /home/user/.local/share/Steam/steamapps/common/Egg Returns Home/EggReturnsHome.x86_64
Mono path[0] = '/home/user/.local/share/Steam/steamapps/common/Egg Returns Home/EggReturnsHome_Data/Managed'
Mono path[1] = '/home/user/.local/share/Steam/steamapps/common/Egg Returns Home/EggReturnsHome_Data/Mono'
Mono config path = '/home/user/.local/share/Steam/steamapps/common/Egg Returns Home/EggReturnsHome_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
client has 3 screens
displaymanager screen (0)(eDP1): 1366 x 768
Using libudev for joystick management


Importing game controller configs
Aborted
```

`/tmp/gameoverlayui.log` shows this:

```
Mon Jun 27 23:22:57 2016 UTC - GameOverlay process started: pid: 24458
Mon Jun 27 23:22:57 2016 UTC - GameOverlay process connecting to: pid: 24442
Mon Jun 27 23:22:57 2016 UTC - BuildID: 1465948400
Mon Jun 27 23:22:57 2016 UTC - Steam Path: /home/user/.local/share/Steam/
Mon Jun 27 23:22:58 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDMon Jun 27 23:22:58 2016 UTC - WM_ACTIVATE received before BasePanel() knows about the game IDMon Jun 27 23:23:01 2016 UTC - Generating new string page texture 2740: 128x256, total string texture memory is 131.07 KB
Mon Jun 27 23:23:01 2016 UTC - Generating new string page texture 2741: 256x256, total string texture memory is 393.22 KB
Mon Jun 27 23:23:12 2016 UTC - Game Exit Event signaled.
Mon Jun 27 23:23:12 2016 UTC - Shutting down overlay
```

I see that I need "at least ubuntu 12.10" or something in the game requirements. I figured Debian was close enough, but could that be the problem?

**Comment by gdrewb-valve** [comment]
You'll want to contact the game developers also.

**Comment by kisak-valve** [comment]
Hello @dooglus, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
I got a chance to take a look at this and the issue. The game was built with gcc 5.x and Debian Jessie's libstdc++.so.6 is too old to be used with the game. Bundling a newer libstdc++.so.6 with the game tends to make more problems than it solves.

The system requirements for the game should be updated to indicate the game supports Ubuntu 16.04+. The game also works with Debian Stretch.
