### ISSUE TITLE
mouse unusable w/ steam 3d games

### ISSUE THREAD

**Issue by TamasSzerb** [ValveSoftware/steam-for-linux#4525]
#### Your system information

* Steam client version: 1.0.0.52-1
* Distribution (e.g. Ubuntu): Debian unstable (sid)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Every game which should use 3D and mouse, I found the view points to one direction and i can only rotate the view. In eg. Team Fortress 2, PayDay 2. GDM3, with wayland, i915 kernel driver. Any idea? I was trying to adjust with:

xinput list --name-only|while read i; do xinput list-props "$i";done
Device 'Virtual core pointer':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
Device 'Virtual core XTEST pointer':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	XTEST Device (238):	1
Device 'xwayland-pointer:12':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (244):	0
	Device Accel Constant Deceleration (245):	1.000000
	Device Accel Adaptive Deceleration (246):	1.000000
	Device Accel Velocity Scaling (247):	10.000000
Device 'Virtual core keyboard':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
Device 'Virtual core XTEST keyboard':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	XTEST Device (238):	1
Device 'xwayland-keyboard:12':
	Device Enabled (119):	1
	Coordinate Transformation Matrix (121):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000

but no luck. Any idea?

**Comment by gdrewb-valve** [comment]
Is this Steam-specific somehow?  You might want to ask in a forum related to your distro.

**Comment by TamasSzerb** [comment]
I think it's steam specific, in case you'd like to support steam on linux. As a debian developer, I'm trying to debug it as much as possible, but not familiar with wayland, which is the candidate as X on debian. It might happen on SteamOS as well. :)

**Comment by gdrewb-valve** [comment]
Can you give details as to why you think it's Steam-specific?

**Comment by TamasSzerb** [comment]
Hello,

OK, you're right, it's not steam related:

https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Mouse_locking_and_relative_mouse_movement_is_not_implemented_yet.2C_affecting_games

I also tried it with openarena, exactly the same what I experienced with Steam games.

I'm sorry about my report. Feel free to close it, and I'd recommend to advertise that information/page to the people.

Thanks,

**Comment by gdrewb-valve** [comment]
Thanks, closing.
