### ISSUE TITLE
Fonts displayed incorrectly on Debian Jessie

### ISSUE THREAD

**Issue by K0HAX** [ValveSoftware/steam-for-linux#4535]
#### Your system information
- Steam client version: Clean install from the Debian repo after deleting the .steam directory
- Distribution (e.g. Ubuntu): Debian Jessie 64-bit
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

I started the Steam client, and all text on the login window is replaced with squares. I expect to be able to read the login window.
#### Steps for reproducing this issue:
1. Install Steam
2. Start Steam
3. Look at display

![image](https://cloud.githubusercontent.com/assets/278074/16616457/fd23daaa-4342-11e6-9ee7-283ba92acd30.png)

**Comment by kisak-valve** [comment]
Hello @K0HAX, are you still experiencing this issue on an up to date system? If you are, please add the output of `locale` and `locale -a`.

**Comment by kisak-valve** [comment]
Closing pending feedback.
