### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by saucyjack42** [ValveSoftware/steam-for-linux#4538]
#### Your system information
- Steam client version: latest beta
- Distribution (e.g. Ubuntu): Arch
- Opted into Steam client beta?: Yes 
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

steam.sh: line 756: 21965 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
#### Steps for reproducing this issue:
1. run steam from terminal

**Comment by gdrewb-valve** [comment]
Likely the same kind of Steam runtime issue as #4537.

**Comment by kisak-valve** [comment]
Hello @saucyjack42, there's not much usable information here. Are you still experiencing an issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
