### ISSUE TITLE
Steam crashed after update client

### ISSUE THREAD

**Issue by yuhas** [ValveSoftware/steam-for-linux#4545]
#### Your system information
- Steam client version: version(1468023329) 1.0.0.52
- Distribution (e.g. Ubuntu): Opensuse 13.2 x86
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
#### Steps for reproducing this issue:
1. run steam from terminal
2. auto start update client window
3. crash update window & closed
4. auto open window  for "Log in"
5. crash Login window

```
Installing breakpad exception handler for appid(steam)/version(1468023329)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0712/134237:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0712/134237:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160708214346)
Installing breakpad exception handler for appid(steamwebhelper)/version(1468014226)
[0712/134237:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steamwebhelper)/version(20160708214346)
Installing breakpad exception handler for appid(steamwebhelper)/version(1468023329)
Installing breakpad exception handler for appid(steamwebhelper)/version(1468023329)
[0712/134237:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
Generating new string page texture 7: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180,22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442,37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507,90 KB
Installing breakpad exception handler for appid(steam)/version(1468023329)
Installing breakpad exception handler for appid(steam)/version(1468023329)
assert_20160712134235_1.dmp[25705]: Uploading dump (out-of-process)
/tmp/dumps/assert_20160712134235_1.dmp
~/.local/share/Steam/steam.sh: line 713: 25662 Ошибка сегментирования                   $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20160712134235_1.dmp[25705]: Finished uploading minidump (out-of-process): success = yes
assert_20160712134235_1.dmp[25705]: response: CrashID=bp-33313eba-08e9-4d0f-ae60-2a3a02160712
assert_20160712134235_1.dmp[25705]: file ''/tmp/dumps/assert_20160712134235_1.dmp'', upload yes: ''CrashID=bp-33313eba-08e9-4d0f-ae60-2a3a02160712''
```

Dump file - 

https://mega.nz/#!dJZCCbZA!b5JT0wJ3RFsFujwDtnP7H06YqCeHSfh6oRXbb1iNk-A

**Comment by Tele42** [comment]
Hello @yuhas, your crash is in libcrypto, making your issue related to #4504 or #4537.

**Comment by yuhas** [comment]
Hi @Tele42 .
Why i should install Mesa from "no true" repo or rebuild mesa with "holey" sha1 ( #4504 )?
By steam...

**Comment by Storm-Engineer** [comment]
Not sure if same issue, but Steam worked yesterday, then after updating itself it stopped to work. I did a system upgrade to see if that fixes but no.

Dumps:
https://www.dropbox.com/sh/hqu2f06b8pirant/AADEtPRyR1H5uaqO73k42obPa?dl=0

How do I start a game that is supposed to run without Steam and does so on Windows? They tell me go to game folder in Steam and just run it - that works on Windows but on Linux it will cry about not finding all kinds of dirs. This game should run without Steam, and I want to play! Please help!

**Comment by Storm-Engineer** [comment]
I just tried now and Steam started up, it seemed to work... then while I came here to report that it crashed, and now won't start again. So the issue persists, but it's weird that at first it started up. Here is the dump for that crash: https://www.dropbox.com/s/hd8v7xw5wgf2hi7/crash_20160721032114_1.dmp?dl=0

**Comment by Storm-Engineer** [comment]
Apparently my issue was #4561 - an issue caused with beta participations no longer existing.

**Comment by kisak-valve** [comment]
Hello @yuhas, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as fixed in mesa years ago with https://gitlab.freedesktop.org/mesa/mesa/commit/d1efa09d342bff3e5def2978a0bef748d74f9c82.
