### ISSUE TITLE
Memory leak when leaving Steam client open or downloading games

### ISSUE THREAD

**Issue by DrakeJa** [ValveSoftware/steam-for-linux#4549]
#### Your system information
- Steam client version: 1.0.0.52
- Distribution (e.g. Ubuntu): Xubuntu 16.04
- Opted into Steam client beta?: No 
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

When I download games or leave Steam open for a long period of time (around 2 hours), my system becomes unusable because of a memory leak caused by the Steam client. 

Here is a screenshot to a program called htop showing the memory usage by the Steam client: https://i.imgur.com/YHwU6ez.png

When I close Steam, the memory usage goes down to 1GB and the Swap partition is cleared.
#### Steps for reproducing this issue:
1. Leave the Steam client running for around 1-2 hours or download games

**Comment by ekaris** [comment]
Probably because steam is using a very outdated version of chromium 49 vs the most recent stable 52

**Comment by kisak-valve** [comment]
Hello @DrakeJa, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
