### ISSUE TITLE
Clicking links in Steam is broken

### ISSUE THREAD

**Issue by Enzime** [ValveSoftware/steam-for-linux#4550]
#### Your system information

* Steam client version: 1468023329
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Clicking any links in Steam chat that should be opened in your browser, now just outputs to console xdg-open failed

`sh: STEAM_RUNTIME=0 LD_LIBRARY_PATH="$SYSTEM_LD_LIBRARY_PATH" PATH="$SYSTEM_PATH" /usr/bin/xdg-open: No such file or directory`

**Comment by Tele42** [comment]
This should already be fixed in the steam beta client. See #4536.

**Comment by gdrewb-valve** [comment]
@Enzime , can you verify that it is working for you with the beta client?

**Comment by gdrewb-valve** [comment]
You can close this if it is.

**Comment by Enzime** [comment]
@gdrewb-valve Yes, it does work in the beta client for me
