### ISSUE TITLE
Steam crash after startup

### ISSUE THREAD

**Issue by Lehmax** [ValveSoftware/steam-for-linux#4551]
- Steam client version: 1.0.0.52
- Distribution (e.g. Ubuntu): Kubuntu 16.04
- Opted into Steam client beta?: [No] 
- Have you checked for system updates?: [Yes]

I get the "loggin in" message and after that Steam crashes.
[terminal output](https://github.com/ValveSoftware/steam-for-linux/files/366368/max_stdout.txt)

**Comment by Tele42** [comment]
Hello @Konstamokh, if you search this issue tracker for "X Error of failed request:  BadValue" you should be able to find several issue reports that cover this issue. What it comes down to is a long standing steam runtime incompatibility with mesa 10.5 or newer and there are a couple workarounds available to get steam working.

**Comment by Storm-Engineer** [comment]
Not sure if same issue, but Steam worked yesterday, then after updating itself it stopped to work. I did a system upgrade to see if that fixes but no.

Dumps:
https://www.dropbox.com/sh/hqu2f06b8pirant/AADEtPRyR1H5uaqO73k42obPa?dl=0

How do I start a game that is supposed to run without Steam and does so on Windows? They tell me go to game folder in Steam and just run it - that works on Windows but on Linux it will cry about not finding all kinds of dirs. This game should run without Steam, and I want to play! Please help!

**Comment by Konstamokh** [comment]
There is still GOG if Steam doesn't suit your needs.

**Comment by Storm-Engineer** [comment]
@Konstamokh please explain to me how will GOG give me free access to my $1100 worth of Steam games, my Steam item inventory and my Steam friends?

**Comment by Storm-Engineer** [comment]
As of now, my Steam seems to work again. I still don't know however if my issue was the same.

**Comment by Storm-Engineer** [comment]
Apparently my issue was #4561 - an issue caused with beta participations no longer existing.

**Comment by kisak-valve** [comment]
Hello @Lehmax, are you still experiencing this issue on an up to date system?

**Comment by Lehmax** [comment]
Since three years have passed and I'm not using Kubuntu at the moment I'd guess this is not an issue anymore. This can probably be closed.

**Comment by kisak-valve** [comment]
Thanks for following up, closing.
