### ISSUE TITLE
queue customization ignores OS/machine filters

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4552]
#### Your system information

* Steam client version:as of today
* Distribution (e.g. Ubuntu): debian jessie x86
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
the queue customization select windows (ERK!) games, even if I'm on a linux box.

**Comment by Tele42** [comment]
Duplicate of #4500.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
