### ISSUE TITLE
Steam Background Viewer Problem

### ISSUE THREAD

**Issue by Balashka** [ValveSoftware/steam-for-linux#4555]
Your system information
- Steam client version:
  Built: Jul 8 2016 at 21:44:35
  Steam API: v017
  Steam Package Versions: 1468023329
- Distribution (e.g. Ubuntu): Ubuntu 14.04
- Opted into Steam client beta?: No
- Have you checked for system updates?: I check it daily, it is up to date
#### Please describe your issue in as much detail as possible:

I expected to view a background in full size. Plus, links doesn't work, which might be related. When I click a link, or in Inventory a background, it does nothing. Before, the links were opened in a web browser, mine is Google Chrome. I tried switching the default browser to Mozilla Firefox, to no avail. The steps to reproduce are below. I would like to see this work as it is intended. In the browser, I can use it normally, but that's not my client that I'm used to.
#### Steps for reproducing this issue:
1. Go to "Ownname"->Inventory, on the top, with huge capitals.
2. Scroll to a background in your inventory, using the arrow keys on the bottom of the inventory screen, if you have many items. (optional, might be on the first page)
3. Click on the background.
4. On the right, you will see a grey View Full Size icon/link.
5. Click it, and, if the bug is on other computers with Ubuntu running as well, it will do nothing.
   Alternative:
6. Click a link anywhere that is underlined or bold and leads to an external site. It does nothing. I know I shouldn't write more bugs in one, but these two might be related.
   ![steam background problem](https://cloud.githubusercontent.com/assets/17047056/16910871/5ebb40f4-4cdb-11e6-8c3a-2bc427eafff7.jpg)

**Comment by Tele42** [comment]
I have a feeling this is another facet of the xdg-open issue that's already been fixed in the beta client.

**Comment by gdrewb-valve** [comment]
Yes, you might try opting into the beta client.

**Comment by Balashka** [comment]
Sorry guys, I'm not using unstable versions. Better off in browser then, sometime it might be available for me, too, thanks.

**Comment by kisak-valve** [comment]
Hello @Balashka, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
