### ISSUE TITLE
Gamemaker games crash on startup (Undertale, PDTA)

### ISSUE THREAD

**Issue by Darktori** [ValveSoftware/steam-for-linux#4556]
#### Your system information

* Steam client version: comilation date: Jul 12, steam api v017, 1468520696 (current beta, same problem on stable channel)
* Distribution (e.g. Ubuntu): Kubuntu 16.04
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
OK, so I'm not sure if this problem is with my system, Steam, game maker or something else, but I tried everything Google found and I still have this issue.

Two games I found so far crash on startup: "Undertale" and "Please, Don't Touch Anything". Both of them are game maker tittles I assume, as the both have the "YoYo Games Linux Runner V1.3" script in the files. No other games so far have this problem on my system.

When launching the games from within Steam I get to error, the game window shows up for a split-second, but otherwise fails silently. Steam acknowledges that the game was run, as the "Last Played" value is updated.

To get some errors I had to navigate to the game files, and run the run scripts manually, from the console.
Here is the output from both games: https://gist.github.com/Darktori/dfe8b0b571551636159c22c28d7b74b1

An interesting thing is that I found the problem first on PDTA, reported it on the community page (http://steamcommunity.com/app/354240/discussions/0/364043054110224335/) but the problem vanished a few days later. I played the game and forgot about it. Now that I wanted to play Undertale, the problem is back.

Other system info:
https://gist.github.com/Darktori/356d4c2965eb35ecd205c826b72d0cd7

**Comment by gdrewb-valve** [comment]
Most likely another instance of Steam runtime clashes.

**Comment by Darktori** [comment]
I guess that's good that it's a know issue, but is there anyway I can help to debug it? Or a workaround to play the games?

**Comment by gdrewb-valve** [comment]
It's just a theory so it's not a specific known issue.  However if you read through the issues here, particularly ones dealing with 16.04, you'll see a lot of possible workarounds.

**Comment by Darktori** [comment]
BTW I'm wondering - since to get the logs I use the exe directly from the terminal (I can skip the run.sh script of the games, and open the runner binary) how exactly could the Steam runtime clash? Perhaps it's my systems fault? But it would be very strange that I would get a FPE in a popular tittle...

**Comment by Darktori** [comment]
Risk of Rain, another gamemaker game, has the same issue.

**Comment by Darktori** [comment]
OK, final comment - I manually upgraded from nvidia driver 364 to 367 (it was available in the repo, but the system updater didn't show it to me), and now the games work.

**Comment by gdrewb-valve** [comment]
Glad you found the issue, closing this out.
