### ISSUE TITLE
browse local files not working

### ISSUE THREAD

**Issue by lahtis** [ValveSoftware/steam-for-linux#4560]
#### Your system information

* Steam client version: steam-runtime-beta-release_2016-06-15
* Distribution (e.g. Ubuntu): 16.04.1 Ubuntu 
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. game browse local files not opened. Game has installed. 
When you go to game properties -> LOCAL FILES -> Browse local files 
2. nothing happened. Files not opened. 
3.

**Comment by Tele42** [comment]
Hello @lahtis, this was identified as an issue with steam's usage of xdg-open and has already been fixed in the beta client.
Duplicate of #4528.

**Comment by gdrewb-valve** [comment]
Closing duplicate.

**Comment by Inotamira** [comment]
Issue is not resolved
