### ISSUE TITLE
Steam startup crash when a game is opted into a beta that no longer exists

### ISSUE THREAD

**Issue by mark-blum** [ValveSoftware/steam-for-linux#4561]
## Your system information
- Steam client version: 1468520696
- Distribution (e.g. Ubuntu): Arch Linux x86_64
- Opted into Steam client beta?: [Yes/No]  Yes
- Have you checked for system updates?: [Yes/No] Yes
## Please describe your issue in as much detail as possible:

I first noticed this problem when I opted into the (short) Undertale linux beta. Everything worked fine, but when the beta ended in the morning, Steam had (presumably) crashed overnight and would crash everytime it was started up. When I deleted/renamed the relevant appmanifest_####.acf in my steamapps folder however, steam would start up alright, and could even download the game again just fine. I encountered this problem again when terraria's open beta ended. This problem may not be linux exclusive but I can't tell.
## Steps for reproducing this issue:
1. Open Steam
2. Opt into a beta for a game
3. Wait for the developer of the game to remove said beta
4. Your steam client should crash, and will crash every time you try to start it up.
## Fix for those with this problem

Just delete the appmanifest_######.acf for the game that was in the beta and steam should start up fine.

**Comment by barsanuphe** [comment]
I can confirm both the problem and the fix.

**Comment by Storm-Engineer** [comment]
I confirm. I had this with Ultimate Chicken Horse. Removing its appmanifest and re-downloading the game fixed it.

**Comment by Chuckaluphagus** [comment]
I can confirm the bug and the fix as well.  I was in the beta for Defect, which then went to full release right around the time Steam stopped working ([noted here](https://github.com/ValveSoftware/steam-for-linux/issues/4554#issuecomment-233743100)).  I followed werecat's instructions and Steam is now running correctly again.

**Comment by mjevans** [comment]
I don't have time to play games during the work week anyway, so I just moved all of the affected files to the side.  I can copy them back when a fixed version is ready to be tested to confirm that Steam doesn't crash with a known crash causing set of data.

**Comment by DarkAceZ** [comment]
Confirming for Terraria. (appmanifest_105600)

**Comment by Cheeseum** [comment]
Also confirmed for Starbound (211820).
Removing appmanifest_211820.acf as prescribed allows steam to start up again.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
