### ISSUE TITLE
Store pages do not load and display correctly

### ISSUE THREAD

**Issue by nukeop** [ValveSoftware/steam-for-linux#4564]
#### Your system information
- Steam client version: 1468520696
- Distribution (e.g. Ubuntu):  Mint 17
- Opted into Steam client beta?: [Yes/No]  Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Clicking a videogame on the main store page loads its page for a split second then goes directly to http://error/.
#### Steps for reproducing this issue:
1.  Go to Store section in the Steam client.
2.  Click on any videogame.
3.  Observe as its page loads and immediately goes to http://error/.

**Comment by xpd259** [comment]
On Debian testing (stretch) I had this issue too
```
apt-get install libgpg-error0:i386
```
seems to have fixed it. 

not sure if it will fix it for you but, worth a try

**Comment by nukeop** [comment]
I already have it unfortunately.

**Comment by nutron** [comment]
Adding this package resolved my issue which was that any tabs that the browser used in the client would just sit blank and have the spinning load icon go forever.

I tried loading it from the commandline to see if anything of use was in the output but there was nothing it really complained about.  As soon as I installed the package.  WHAMMO, fixed.

I am running Debian Testing (stretch)

**Comment by nukeop** [comment]
This is still ocurring.

**Comment by kisak-valve** [comment]
Hello @nukeop, are you still experiencing this issue on an up to date system?

**Comment by nukeop** [comment]
It was an issue with some dependencies but doesn't occur anymore.
