### ISSUE TITLE
Steam Login Disappear !

### ISSUE THREAD

**Issue by dogukanservi** [ValveSoftware/steam-for-linux#4565]
I put on my problem in this video.

Youtube Link : https://youtu.be/-5L3rA_ndoM

**Comment by gdrewb-valve** [comment]
Can you post your full system information from Steam?  You might want to check issues like #4561 also and see if that applies.

**Comment by dogukanservi** [comment]
@gdrewb-valve 

`dogukan@pc:~$ steam
Running Steam on ubuntu 16.04 32-bit
STEAM_RUNTIME is enabled automatically
[2016-07-24 20:37:11] Startup - updater built Jul  8 2016 21:43:51
[2016-07-24 20:37:12] Verifying installation...
[2016-07-24 20:37:12] Verification complete
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
`

**Comment by gdrewb-valve** [comment]
The system info in Steam is under the Help menu in the Steam client.

**Comment by Tele42** [comment]
Hello @dogukanservi, is this a new install of steam?

I suspect there is a locale issue going on here. What locale are you using? Does running ```LANG=C steam``` from a terminal help? Also, is the en_US.UTF-8 locale available?

**Comment by dogukanservi** [comment]
@Tele42 "Yeah ! Thank you. My problem has been solved."

**Comment by gdrewb-valve** [comment]
So this should be closed?  @dogukanservi you can close it if you no longer have an issue.
