### ISSUE TITLE
[feature-request] Option in settings to toggle "Close to tray" and "Show tray icon"

### ISSUE THREAD

**Issue by MattSturgeon** [ValveSoftware/steam-for-linux#4569]
There should be an option in the _Settings -> Interface_ section to toggle closing the window vs quitting the application when hitting the `x` in the top corner of the window.

This should negate the need on linux to use the minimize-on-close workaround currently in place (see #1025) as users having issues will be able to disable closing to tray.

--------------------

Another option may be to have a drop-down or radio option, where the user can choose the behaviour of the Close button; setting it to either _"Close window, but keep open in the system tray"_, _"Minimize window"_ or _"Quit Steam"_

Personally, I cannot see a reason to use the systray at all if the user chooses the minimize or quit options... Some other apps have a "Show icon in tray" option that can be set to things like _"Always show icon"_, _"Never show icon"_ and _"Only show when closed to tray"_

**Comment by gdrewb-valve** [comment]
There's no need for a duplicate issue, this is already covered in #1025.  Also as this repo is for bugs specific to the Linux port of the Steam client a general, platform-neutral option isn't really in scope here (although we keep a lot open for simplicity).
