### ISSUE TITLE
Bluetooth module is detected as a gamepad in Overlord games

### ISSUE THREAD

**Issue by hidekin** [ValveSoftware/steam-for-linux#4570]
CPU : Intel I7 3820 3.6GHz
GPU : Nvidia Gtx 1070 Gigabyte G1 gaming (drivers 367.35)
RAM : 16GB DDR 2133MHz
DM : Gnome 3.20
Bluetooth : Atheros Communications, Inc. AR3011 Bluetooth
- Steam client version: 1468023329 (Latest Stable)
- Distribution (e.g. Ubuntu): Archlinux
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes

I played Overlord that just released yesterday on Steam on linux. I have this issue when the bluetooth is enabled the game camera moves itselfs. Seems that the bluetooth module is detected as a steam controller by Steam
Virtual-programming helped me with a workaround for their game but it would be nice to be resolved in Steam.
I link the issue on VP github https://github.com/virtual-programming/overlord-linux/issues/6

Here is my log file from Overlord game it could be useful . 
[eon.txt](https://github.com/ValveSoftware/steam-for-linux/files/385972/eon.txt)
1. Enable Bluetooth module
2. Launch Overlord or Overlord II game with steam
3. start a new game or load game
4. Camera move itself while playing

Thank you very much

**Comment by kisak-valve** [comment]
Hello @hidekin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
