### ISSUE TITLE
Ghost chat issue

### ISSUE THREAD

**Issue by nukeop** [ValveSoftware/steam-for-linux#4573]
#### Your system information
- Steam client version: 1468520696
- Distribution (e.g. Ubuntu):  Mint 17
- Opted into Steam client beta?: [Yes/No]  Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Group chat frequently (2-3 times a day) malfunctions in the following way: it disconnects all users from the chat, although each user will not be notified, and will continue to see the connected users as if nothing happened. You can still type and send messages, although you won't get anything back, because you're not actually connected. It looks that the chat room fails to send a disconnection message to the client, so it won't take note of that. This is not limited to a single group, happens wherever I join.
#### Steps for reproducing this issue:
1. Happens randomly during the day. Join a group chat and wait long enough, and eventually it will happen.

**Comment by kisak-valve** [comment]
Hello @nukeop, have you seen this issue in recent memory?

**Comment by nukeop** [comment]
Nope, since chat has been upgraded everything's working great, I'll close this issue now.
