### ISSUE TITLE
Steam won't start fresh 16.04 kubuntu r9 290

### ISSUE THREAD

**Issue by Goddard** [ValveSoftware/steam-for-linux#4576]
#### Your system information
- Steam client version: 
- Distribution (e.g. Ubuntu): 16.04 
- Opted into Steam client beta?: [Yes/No]  No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/irenicus/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Error: You are missing the following 32-bit libraries, and Steam may not run:
libXtst.so.6
libgobject-2.0.so.0
libpulse.so.0
libXrender.so.1
libpcre.so.3
libpango-1.0.so.0
libgobject-2.0.so.0
libgmodule-2.0.so.0
libgobject-2.0.so.0
libpng12.so.0
libtiff.so.4
libjpeg.so.8
libpango-1.0.so.0
libgobject-2.0.so.0
libXrender.so.1
libpango-1.0.so.0
libgobject-2.0.so.0
libfreetype.so.6
libgobject-2.0.so.0
libpixman-1.so.0
libfreetype.so.6
libpng12.so.0
libXrender.so.1
libgobject-2.0.so.0
libgmodule-2.0.so.0
libpango-1.0.so.0
libgobject-2.0.so.0
libfreetype.so.6
libfreetype.so.6
libXrender.so.1
Installing breakpad exception handler for appid(steam)/version(1468023329)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast                      
#### Steps for reproducing this issue:
1. type steam in terminal

I have the open AMD GPU driver that comes in the kernel.  I was able to get this working in the past, but I reinstalled and now I can't get this working at all.

**Comment by Tele42** [comment]
Hello @Goddard, it looks like you need to enable multilib support and add the 32 bit libraries that are listed. Additionally, you may need to use the [Arch workaround](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues) because you are using mesa 10.5 or newer.

**Comment by Goddard** [comment]
I am not sure exactly what the issue was, but I did this and it fixed my issue.  I still have to use this special shell script to launch it on my AMD R9 290 though.  Going to buy an Nvidia card soon which I am sure I won't have any of these issues.

first 
```
cd ~/.local/share/Steam/
./steam.sh --reset
```

Then make a steam.sh in your home directory.
if [ "$(glxinfo | grep Mesa)" ]; then
    LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' exec "/usr/bin/steam" "$@"
else
    exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@"
fi

**Comment by kisak-valve** [comment]
Hello @Goddard, Steam's handling of the Steam runtime has changed to prefer host libraries before the runtime variants, which avoids this issue. This was also added to the bootstrapper environment in the Steam 1.0.0.55 package.

Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.

The bootstrap environment in the distro-provided Steam package is still affected and it is unlikely to get an update, so if you use that package, the workaround mentioned should only be needed to get Steam to run once, then it shouldn't need a workaround to work after that.
