### ISSUE TITLE
Button mis-mapping, analog issues, rapid gamepad/mouse switch during In-home streaming on Feral games

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/steam-for-linux#4578]
Your system information

Motherboard : MSI 970A-G46

Processor : AMD FX-8350 4Ghz Octocore

Cooling : Cooler Master Hyper 212 Evo

Memory : 16GB PNY-XLR8 DDR3 1600Mhz 9-9-9-27

Operating System : Linux Mint 18 Sarah

Display : Asus 24in Lcd 1920x1080

Video Card : XFX Radeon R9 380X

Graphics Driver : amdgpu+Mesa 11.2

HDD : WD Blue 1TB

SSD : OCZ-VERTEX3

PSU : Rosewill Photon 750

Steam client version: latest non beta in xenial repo whichever that is steam:i386 1:1.0.0.48-1ubuntu3
Distribution (e.g. Ubuntu): Linux mint 18
Opted into Steam client beta?: [No]
Have you checked for system updates?: [Yes]
#### Please describe your issue in as much detail as possible:

Tomb Raider, Life is Strange, Grid, etc it seems all feral games have this issue where if I'm playing with a wired xbox 360 controller(rock candy) over in home streaming. pressing the 'b' button escapes to the menu, while simultaneously doing it's in-game function.

controller pid:Bus 005 Device 004: ID 0e6f:011f Logic3 

this only happens when using the controller over in-home streaming, plugged directly into the main box it works fine. 

I also noticed something else, the analog sticks seem to get stuck going one direction permanently when using a controller over in home streaming. again with no such error when plugged directly, like the input gets gleamed... and then switches back to mouse and makes you walk forward

I think I may know what is going on as the game gave me a good clue.

It keeps switching from controller to mouse very rapidly in the affected scenarios, I can tell because the mouse cursor disappears and reappears constantly.

as if steam is not sure the input device is a gamepad or not.

This issue only seems to occur in feral games,
#### Steps for reproducing this issue:
1. run a feral game using in home streaming
2. use a wired xbox 360 controller by rock candy
3. hit the 'b' button when appropriate, get kicked to menu

**Comment by esmithferal** [comment]
Checked with Calaxil and he used the following pad:

Bus 005 Device 004: ID 0e6f:011f Logic3

Both the sender and the receiver distros were Mint 18.

--
Attempted reproduction at Feral using two machines both running Ubuntu 16.04 with a Steam Controller and a wired first party Xbox One controller without any success.

**Comment by ninoslayer** [comment]
Same issue on me too. I am using wireless xbox 360 controller.
Host Machine : Linux Mint XFCE
Client Machine : Debian Stable

Applied Valve's Xbox driver DKMS on both machine.
