### ISSUE TITLE
OpenSUSE Tumbleweed - SegFaults when connecting to account

### ISSUE THREAD

**Issue by MGM175** [ValveSoftware/steam-for-linux#4581]
#### Your system information
- Steam client version: Unknown -  unable to check (freshly installed and updated to newest version)
- Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed (snapshot 20160625) 64-Bit - KDE DE;
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Just tried to log-in, pretty much. More is described in the links (managed to dump output produced by Steam from launch to SegFault; where I should put the minidumps?):
- After succesfully signing in with saving my pass on PC: https://gist.github.com/MGM175/458ca1360fb57382c3622fb2b9b1d352
- After signing in without saving my pass (and deleting config.vdf):
  https://gist.github.com/MGM175/70482e66fb26f7e42324f83e5f04204c
#### Steps for reproducing this issue:
1.  Install via YaST or Zypper the "steam" package";
2.  Let the Steam update;
3.  Sign in (sometimes SegFault shows up here when trying to enter SteamGuard code);
4. When logging in; here comes (most frequently) the SegFault (line is random pretty much).

**Comment by moozaad** [comment]
Here's the corresponding opensuse bug https://bugzilla.opensuse.org/show_bug.cgi?id=988273

From what I understand it's identifying the statically linked openssl as causing the issue with no workaround if the distro is to continue using openssl (as most distros do). Hopefully steam will action this bug.

**Comment by wstephenson** [comment]
Diagnosis in https://github.com/ValveSoftware/steam-for-linux/issues/4619

**Comment by boombatower** [comment]
Fixed in [openSUSE Tumbleweed 20160924](https://github.com/ValveSoftware/steam-for-linux/issues/4537#issuecomment-249340953).

**Comment by kisak-valve** [comment]
Closing per the last comment.
