### ISSUE TITLE
Steam can't interact with other apps

### ISSUE THREAD

**Issue by caisar** [ValveSoftware/steam-for-linux#4582]
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3100 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.4 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-79-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 750/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.63
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x1381
Revision Not Detected
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17.09" x 9.29"  (19.45" diag)
                                        43.4cm x 23.6cm  (49.4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7929 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  187612 Mb
    Largest Free Hard Disk Block:  30233 Mb
    VR Headset: None detected
#### Your system information
- Steam client version: 
- Distribution (e.g. Ubuntu): Ubuntu **14.04**
- Opted into Steam client beta?: **[No]** 
- Have you checked for system updates?: **[Yes]**
#### Please describe your issue in as much detail as possible:
- "show on disk" not triger nautilus
- "browse local file" not triger nautilus 
- right click copy can't be pasted outside steam (browser, text editor, etc)
#### Steps for reproducing this issue:
1. view - screenshot - select image - show on disk
2. librar -right click - properties - local files - browse local file
3. select text - right click - copy - paste outside steam  

![screenshot from 2016-08-10 01 24 15](https://cloud.githubusercontent.com/assets/5735742/17530020/eb8ed75e-5e9f-11e6-934b-750c4f13b178.png)
![screenshot from 2016-08-10 02 17 51](https://cloud.githubusercontent.com/assets/5735742/17530241/f3480802-5ea0-11e6-97e6-b3bf40b394da.png)
![screenshot from 2016-08-10 02 08 35](https://cloud.githubusercontent.com/assets/5735742/17530040/05a0350c-5ea0-11e6-9e87-188c45c68313.png)

**Comment by Tele42** [comment]
Hello @caisar, for the first two parts, this is due to broken usage of xdg-open in the steam client which has already been fixed in the beta client. I do not know about the copy buffer.

**Comment by kisak-valve** [comment]
Hello @caisar, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
