### ISSUE TITLE
Unable to type in steam overlay whilst in vulkan dota 2. Does not happen with OpenGL Dota 2. Does not happen with any other game. Tested across KDE, GNOME, and XFCE.

### ISSUE THREAD

**Issue by davay** [ValveSoftware/steam-for-linux#4585]
#### Your system information
- Steam client version: Built Jul 8 2016, at 21:44:35. Steam API: v017. Steam package version: 1468023329
- Distribution (e.g. Ubuntu): Manjaro Linux. Tested with Kernel 4.4 and 4.6 (bug happens with both).
- Opted into Steam client beta?: [Yes/No] Bug happens in both beta and none beta version of steam.
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

When I bring up the steam overlay, my dota 2 cursor does not change into a normal cursor. I can click on friends list, guides, news, any button basically but I cannot type in anything. 
#### Steps for reproducing this issue:
1. Launch dota 2 using vulkan
2. bring up steam overlay
3. try to type

**Comment by davay** [comment]
Any news on this? This is still happening to me as of today

**Comment by Kurolox** [comment]
Same thing. It have been happening to me since yesterday.

**Comment by Plagman** [comment]
This will be fixed in the next major Beta cycle for the client.

**Comment by davay** [comment]
A patch was released today 1st June 2017 that is supposed to fix this, but now Dota 2 just crashes at launch with vulkan enabled.

**Comment by kisak-valve** [comment]
Hello @davay, please open a new issue report in the [Dota-2-Vulkan](https://github.com/ValveSoftware/Dota-2-Vulkan/) issue tracker if the client is crashing with vulkan but not opengl.

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been investigated and resolved back in November.
