### ISSUE TITLE
Checking system info from steam client crashes it

### ISSUE THREAD

**Issue by 420git** [ValveSoftware/steam-for-linux#4586]
#### Your system information
- Steam client version:V017
- Distribution (e.g. Ubuntu): Arch
- Opted into Steam client beta?: [Yes/No]  
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Checking system info from steam client crashes it after few seconds.
attached crash dump and cli dumps

[crash_20160813090054_21.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/416438/crash_20160813090054_21.dmp.txt) added .txt to extension because unsupported
[cli dump.txt](https://github.com/ValveSoftware/steam-for-linux/files/416441/cli.dump.txt)

I marked the section generated after I check system info in cli dump
#### Steps for reproducing this issue:
1. start steam
2. check system info from steam
3. steam crashes

**Comment by kisak-valve** [comment]
Closing in favor of #4964.
