### ISSUE TITLE
Steam restarts when exiting

### ISSUE THREAD

**Issue by MyCatFishSteve** [ValveSoftware/steam-for-linux#4588]
#### Your system information
- Steam client version: Beta (August 13 2016, at 00:25:06)
- Distribution (e.g. Ubuntu): Arch Linux (x64)
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Launching steam with these flags will always prompt me to reenter my login details on each Steam restart, without them Steam fails with a driver error to do with Swrast.so. After logging in Steam works fine but when you try to exit Steam, it will shutdown and then restart and then prompt for login details again by itself after you told it to shutdown and nothing else. After relogging into Steam and then pressing exit, the application will then close cleanly without issues and on next restart it won't prompt for login details, but after exiting on that session then it will restart again and act like you never logged in before.
LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam

http://pastebin.com/E7srhZ7b
#### Steps for reproducing this issue:
1. Open Steam and login
2. Exit the Steam application
3. It will restart, relog back in
4. Exiting will work fine
5. Next restart will forget your login details

**Comment by kisak-valve** [comment]
Hello @MyCatFishSteve. are you still experiencing this issue on an up to date system? Also, the LD_PRELOAD workaround should not have been needed since the 1.0.0.55 steam package update.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by MyCatFishSteve** [comment]
Hi,

Apologies for not getting back to you sooner.
It does appear that the issue is fixed and a workaround is no longer required. :)
