### ISSUE TITLE
Steam Screenshots in-game - black screen.

### ISSUE THREAD

**Issue by Lance321** [ValveSoftware/steam-for-linux#4590]
#### Your system information
- Steam client version:  1468023329 (API: v017) (July 8th, 2016)
- Distribution (e.g. Ubuntu): Ubuntu 16.04
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Screenshots in-games appear as black screen. Most recent game tested is "Ark" but others don't work as well.
#### Steps for reproducing this issue:

Launch a game and press the screenshot key (mine is currently bound to F12).

**Comment by kisak-valve** [comment]
Hello @Lance321, are you still experiencing this issue on an up to date system?

**Comment by Lance321** [comment]
@kisak-valve I wouldn't know if this is still happening. Because this bug was posted 3 years ago!

Its a little late now...

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing presumed fixed some time ago.
