### ISSUE TITLE
When copying text in Steam overlay Web-Browser window, the browser tab locks up and must be closed.

### ISSUE THREAD

**Issue by Lance321** [ValveSoftware/steam-for-linux#4591]
#### Your system information
- Steam client version: V017 (Updated July 8th, 2016)
- Distribution (e.g. Ubuntu): 16.04
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

When copying text via highlight mouse & right-click, or keyboard shortcuts (Ctrl+C or Ctrl+V) the browser tab locks up in Steam overlay while in game. I must close the tab. Copy or paste is unusable between the client and a game, or withing web browser tabs.

**Comment by kisak-valve** [comment]
Hello @Lance321, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
