### ISSUE TITLE
Overlay crashes when removing friend through FL

### ISSUE THREAD

**Issue by n1trux** [ValveSoftware/steam-for-linux#4593]
System info: [sysinfo_steam.txt](https://github.com/ValveSoftware/csgo-osx-linux/files/417012/sysinfo_steam.txt)
- Steam client version: 1468023329
- Distribution (e.g. Ubuntu): Arch x86_64, Kernel 4.7
- Opted into Steam client beta?: not sure, I don't think so
- Have you checked for system updates?: yes
#### Please describe your issue in as much detail as possible:

While removing friends from the FL in the overlay, I expected a confirmation popup and the removal of said friend. The popup doesn't show, instead the overlay crashes but the game still works.

If I remove the friend from their profile (even in overlay) or from the out-of-game Steam FL, the error doesn't occur.
#### Steps for reproducing this issue:
1. Start a game (tested with _CS:GO_ and _Race The Sun_)
2. open Steam Overlay with Shift+Tab
3. open the friends list
4. select one of them
5. attempt remove via "remove this friend" in drop down menu.

**Comment by Tele42** [comment]
Duplicate of #4356.

**Comment by kisak-valve** [comment]
Hello @n1trux, are you still experiencing this issue on an up to date system?

**Comment by n1trux** [comment]
Doesn't happen anymore on Fedora 30 with Steam built on Jun 17 2019.
