### ISSUE TITLE
In game screenshots tool no longer places the pics in Image folder

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4595]
#### Your system information
- Steam client version: Latest stable
- Distribution (e.g. Ubuntu): UBuntu 16.04.1
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Regression in the place where pics are stored when clicking on F12

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
