### ISSUE TITLE
Opening the Steam library throttles network traffic on my system

### ISSUE THREAD

**Issue by meanwhile0** [ValveSoftware/steam-for-linux#4596]
#### Your system information
- Steam client version: Latest stable
- Distribution (e.g. Ubuntu): Manjaro (Arch)
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

This issue has been occurring for me for quite a while, and only today I was able to pinpoint the cause this issue to the Steam library.

What happens is the speed of all network traffic on my system drops significantly while the Steam library is open, causing major slowdowns in web browsing, YouTube video buffering, voice chat and even in multiplayer games.

[I recorded a video to show this occurring as best I can.](https://www.youtube.com/watch?v=5LX4aStcMd8)

Unfortunately, when I was recording this issue, the impact of it wasn't as drastic as it has been in the past. Using Insurgency and nload to record how much the Steam library throttled my network traffic, I found that while recording Insurgency's download was throttled to around 500KB/s - 1MB/s, while with the Steam library closed the download climbed up to 3 - 4MB/s and potentially further if I let it.

nload also shows longer bursts of incoming traffic while the Steam library is closed, and shorter bursts while it is open.
#### Steps for reproducing this issue:

Start a download (on Steam or in a web browser) and open the Steam library while watching the download speed.

**Comment by kisak-valve** [comment]
Hello @meanwhile0, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
