### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by Scoopta** [ValveSoftware/steam-for-linux#4600]
#### Your system information

* Steam client version: Latest
* Distribution (e.g. Ubuntu): Debian 8.5 Jessie with vanilla kernel 4.7.2 from kernel.org
* Opted into Steam client beta?: [Yes/No] 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My internet speed is 80Mbps which should allow me to download at around 10MB/s but for whatever reason my Steam downloads peak at 3MB/s and normally sit around 1MB/s. When I download files through chrome or game launchers I get the speed I'm supposed to, around 8.5MB/s, so it's just a Steam issue. My settings have no bandwidth limit and the download region is set to the one closest to me. This issue occurs both on the beta and stable client.

#### Steps for reproducing this issue:

1. Open Steam
2. Download game

**Comment by steamlinux** [comment]
try install dnsmasq and resolvconf

**Comment by Scoopta** [comment]
dnsmasq was already installed on my system. I installed resolvconf but it's still slow.

**Comment by steamlinux** [comment]
with this packages my download speed 3-5MB/S, without this packages 50KB/S

**Comment by Scoopta** [comment]
Yea...it doesn't help me at all.

**Comment by steamlinux** [comment]
what your fs? ext4 journal? try this:
1. install iotop
2. run iotop (as root)
3. start download in steam
4. look in iotop, if some process load io >98% (ex. kworker), install eatmydata, and run steam this mode "eatmydata steam" for disabling journalling

**Comment by Scoopta** [comment]
Yea my fs is ext4 journaled but that's not the issue. Everything is at 0% in iotop. There are some spikes to like .4% or so but steam is the one doing the majority of disk usage.

**Comment by Scoopta** [comment]
@steamlinux ok...you were right...dnsmasq...it's fantastic. It fixed my issue. It was already installed like I said but it turns out it wasn't configured and never actually got run so my dns queries weren't being cached. Properly configuring dnsmasq causes my games to download like they're supposed to.

**Comment by steamlinux** [comment]
@Scoopta can you post your settings?

**Comment by Scoopta** [comment]
@steamlinux I'm using gnome 3 with the gnome 3 network manager so I went to `/etc/NetworkManager/NetworkManager.conf` and added `dns=dnsmasq` to the `[main]` section. The network manager takes care of the rest. While I'm not positive on this I'm pretty sure that the following config will have the same result.

/etc/dnsmasq.conf:
`no-resolv`
`server=8.8.8.8`
`server=8.8.4.4`

/etc/resolv.conf:
`nameserver 127.0.0.1`

**Comment by steamlinux** [comment]
thank's
