### ISSUE TITLE
amdgpu-pro causes random crashes

### ISSUE THREAD

**Issue by Scoopta** [ValveSoftware/steam-for-linux#4601]
#### Your system information

* Steam client version: Latest
* Distribution (e.g. Ubuntu): Debian 8.5 Jessie with vanilla kernel 4.7.2 from kernel.org
* Opted into Steam client beta?: [Yes/No] 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Ever since I upgraded from fglrx to the amdgpu-pro beta driver Steam has been randomly crashing. Does Steam use vulkan for rendering when available? I ask because I'm using the amdgpu upstream DRM that's part of my kernel which unlike the DKMS module does not include fully working vulkan. If not then I'm not sure what the issue is. This happens on both the stable and beta clients.

**Comment by Tele42** [comment]
Hello @Scoopta, this should be reported to the driver vendor. Steam itself uses very basic opengl, which ends up being about opengl 2.0. You should test with the amdgpu-pro provided kernel module before reaching out to them.

**Comment by Scoopta** [comment]
Alright...I only assumed maybe vulkan because I've had issues with vulkan. All of my games work fine as long as I use OpenGL and I haven't had any OpenGL issues. It's just Steam so I figured it'd be a Steam issue.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear to be a Steam issue.  Note that Steam is 32-bit, if you've only been testing 64-bit OpenGL games try a 32-bit OpenGL game.
