### ISSUE TITLE
Steam is not auto-starting on boot anymore.  Started happening about 3 weeks ago.

### ISSUE THREAD

**Issue by arcooke** [ValveSoftware/steam-for-linux#4602]
#### Your system information
- Steam client version: 1471380192, API v017
- Distribution (e.g. Ubuntu): Mint 17.3 KDE (Ubuntu 14.04)
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Steam stopped loading at system startup.  I've gone into the settings and cycled the auto-start option, and it's still not launching at start, I have to manually do it.  This only started happening about 3ish weeks ago.
#### Steps for reproducing this issue:
1. Turn on "Run Steam when my computer starts"
2. Reboot

**Comment by tukkek** [comment]
Not a proper fix but you can add a symbolic link to the Steam executable into the `~/.config/autostart`  folder (if you're running a recent KDE you can do that also by typing Autostart in the KDE menu/application launcher). This should make Steam launch automatically again whenever you log-in to your computer.

**Comment by arcooke** [comment]
Thanks. I'm just going to keep launching it manually so I can see when/if it gets fixed.  I don't mind too much launching it from krunner

**Comment by kisak-valve** [comment]
Hello @arcooke, are you still experiencing this issue on an up to date system? If you are, please uncheck the autostart option on the settings, close the settings window, then re-open the settings and re-enable it before retesting.

**Comment by arcooke** [comment]
@kisak-valve Hi. No, I haven't had trouble with this in a couple years, though I've switched distributions a few times since then. Thanks for following up.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
