### ISSUE TITLE
line 713:  8098 Seg fault

### ISSUE THREAD

**Issue by keredomo** [ValveSoftware/steam-for-linux#4612]
#### Your system information

* Steam client version: 1.0.0.52?
* Distribution (e.g. Ubuntu): Linux Mint 17.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I ran Steam's self-update last night and it did not restart like it normally would. I thought nothing of it and shutdown my computer for the night. This morning, when I start Steam it goes through the "Checking for updates" dialogue and asks for my password and steam guard code (just like normal) but then simply stops. Running it in terminal generates the following output:

`Running Steam on linuxmint 17.3 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0831/045514:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[0831/045514:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160830235626)
Installing breakpad exception handler for appid(steamwebhelper)/version(1472601386)
Installing breakpad exception handler for appid(steamwebhelper)/version(20160830235626)
Installing breakpad exception handler for appid(steamwebhelper)/version(1472604293)
Installing breakpad exception handler for appid(steamwebhelper)/version(1472604293)
[0831/045514:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442.37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507.90 KB
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Generating new string page texture 15: 384x256, total string texture memory is 901.12 KB
Generating new string page texture 16: 24x256, total string texture memory is 925.70 KB
Generating new string page texture 17: 32x256, total string texture memory is 958.46 KB
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
Installing breakpad exception handler for appid(steam)/version(1472604293)
roaming config store loaded successfully - 19628 bytes.
migrating temporary roaming config store
crash_20160831045413_1.dmp[6690]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160831045413_1.dmp
/home/scott/.local/share/Steam/steam.sh: line 713:  6552 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20160831045413_1.dmp[6690]: Finished uploading minidump (out-of-process): success = yes
crash_20160831045413_1.dmp[6690]: response: CrashID=bp-f0069b21-ddc9-4ab8-b75d-32dc52160831
crash_20160831045413_1.dmp[6690]: file ''/tmp/dumps/crash_20160831045413_1.dmp'', upload yes: ''CrashID=bp-f0069b21-ddc9-4ab8-b75d-32dc52160831''
`

#### Steps for reproducing this issue:

To reproduce this issue all I have to do is start Steam.

**Comment by gdrewb-valve** [comment]
Likely one of the Steam runtime incompatibilities already open here.

**Comment by jonathonf** [comment]
Not sure about that. I was also running fine (on Manjaro/Arch x64) until yesterday's/today's Steam beta update with `STEAM_RUNTIME=1 LD_PRELOAD='/usr/$LIB/libudev.so.1 /usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' steam` (from [1]).

Final entries under gdb:

```
[New Thread 0xe68ffb40 (LWP 11234)]
[New Thread 0xe5effb40 (LWP 11235)]
[New Thread 0xe54ffb40 (LWP 11236)]
[Thread 0xe5effb40 (LWP 11235) exited]
[New Thread 0xe4affb40 (LWP 11237)]
Installing breakpad exception handler for appid(steam)/version(1472604293)
[New Thread 0xeeaffb40 (LWP 11238)]
Installing breakpad exception handler for appid(steam)/version(1472604293)
[New Thread 0xecce2b40 (LWP 11239)]
Installing breakpad exception handler for appid(steam)/version(1472604293)
roaming config store loaded successfully - 15155 bytes.
migrating temporary roaming config store

Thread 5 "CIPCServer::Thr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xeedc6b40 (LWP 11189)]
0xefa3b80a in ?? () from /home/jonathon/Steam/ubuntu12_32/steamclient.so
```

[1] https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Dynamic_linker

**Comment by robblue2x** [comment]
I was able to get gaming again by deleting `~/.steam` and `~/.local/share/Steam` (back up games where needed) then run steam again so it recreate those directories.

**Comment by jonathonf** [comment]
@robblue2x Yeah, that resets the Steam client back to the default stable release update channel (which will be good for anyone wanting to get back to a working state). After opting in to the beta channel again the same issue reoccurs.

```
/home/jonathon/Steam/steam.sh: line 713: 27160 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20160831203759_1.dmp[28082]: Finished uploading minidump (out-of-process): success = yes
assert_20160831203759_1.dmp[28082]: response: CrashID=bp-8af7cb50-e8d2-4e22-a72c-ed97b2160831
assert_20160831203759_1.dmp[28082]: file ''/tmp/dumps/assert_20160831203759_1.dmp'', upload yes: ''CrashID=bp-8af7cb50-e8d2-4e22-a72c-ed97b2160831''
```

**Comment by gdrewb-valve** [comment]
Turns out this is something happening on all platforms and the full Steam team has a fix coming.

**Comment by keredomo** [comment]
After installing the latest update, everything seems to be working again.
