### ISSUE TITLE
Can't post comment or browse my inventory on Linux Mageia or OpenMandriva

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/steam-for-linux#4620]
#### Your system information
- Steam client version: 1471977975
- Distribution (e.g. Ubuntu): Linux Mageia 5 x64 and OpenMandriva LX3 x64
- Opted into Steam client beta?: [No] 
- Have you checked for system updates?: [Yes]
#### Please describe your issue in as much detail as possible:

For all time i use Steam client on this distro - Linux Mageia 5 x64, and not have any issues. Now I see that I can't post any comment in Steam community via my Steam Client. Also I can't browse my inventory, so I can open it but I see only first intem and can't click to other or change page.

This issue I have only in Steam Client. I tested it on Mageia 5 x64 and also on my notebook with OpenMandriva LX 3 x64 - on both I have this issues. But on my second system on notebook - on Ubuntu 16.04 x64 I not have it, it working fine. So? Also on web browser this all features working fine.
#### Steps for reproducing this issue:
1. Install Mageia 5 x64 or OpenMandriva LX 3 x64
2. Open Steam and trying post comment or browse inventory.

My steam spec from desktop pc with Mageia 5x64

https://gist.github.com/xpris/2ddbe85024815b9a9977e8e89dcb6570

**Comment by Tele42** [comment]
This is likely the intermittent server-side issues that have been going on with steamcommunity.com for the last week or so.

**Comment by kisak-valve** [comment]
Hello @AngryPenguinPL, have you seen this issue in recent history?

**Comment by AngryPenguinPL** [comment]
No, i dont see it anymore. This it is fixed. Thanks.
