### ISSUE TITLE
Can anyone post the fix for the segment error with their own repo

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [ValveSoftware/steam-for-linux#4621]
Have waited for almost two months for the official fix about the segment error but it seems there is no fix coming. I remember someone posted that they make a repo which can fix it. I can't find it. Can anyone post it? It's an opensuse repo.
#### Your system information
- Steam client version:
- Distribution (e.g. Ubuntu): 
- Opted into Steam client beta?: [Yes/No] 
- Have you checked for system updates?: [Yes/No]
#### Please describe your issue in as much detail as possible:

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
#### Steps for reproducing this issue:
1. 
2. 
3.

**Comment by gdrewb-valve** [comment]
It sounds like there's already an issue open for your problem?

**Comment by kisak-valve** [comment]
Closing as this should have been an issue with Mesa 13.0 which was resolved in the driver.
