### ISSUE TITLE
Beta Linux Steam client: font too small.

### ISSUE THREAD

**Issue by Tetractys** [ValveSoftware/steam-for-linux#4622]
Hi!,
i have a 4k monitor @3840x2160 28"
LinuxMint 18 Sarah - Cinnamon 3.0.7
NVIDIA GTX980
i7 6700K @4.0GHz
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

![steam-beta-client version](https://cloud.githubusercontent.com/assets/465836/18399678/717f1910-76d2-11e6-8f46-423a952067bb.png)
![steam-actual-fonts](https://cloud.githubusercontent.com/assets/465836/18399687/7ab7a47a-76d2-11e6-8d36-2f851ed5e16e.png)
Both normal client and the beta one fonts looks far too small! Barely readable.
Can you fix this please?
Looking foreword your kind answer, i attach a screenshot depicting the problem. (Last beta client)
Kind Regards

**Comment by Tele42** [comment]
Duplicate of #3492. Currently there is no HiDPI support in vgui for any platform (meaning it's a cross-plaform issue).

**Comment by Tetractys** [comment]
Sorry, i was not aware of the existing thread.
I'll follow the #3492. THanks.
Closing this issue.
