### ISSUE TITLE
Internal web browser doesn't load any page of store and community network

### ISSUE THREAD

**Issue by emmecii** [ValveSoftware/steam-for-linux#4623]
#### Your system information
- Steam client version: 1471977975
- Distribution (e.g. Ubuntu): Ubuntu 16.4.1
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

WIth a new clean install of Ubuntu and after all the update of Ubuntu checked and installed, the internal web browser of Steam doesn't load any page of the store or the community network. All the other parts of the client work with no problem.

the .deb file was installed with dpkg command after installed the required dependencies (**curl** and **python-apt**)
#### Steps for reproducing this issue:

**The output from the terminal executing steam:**
[steam.txt](https://github.com/ValveSoftware/steam-for-linux/files/464701/steam.txt)

**Comment by Tele42** [comment]
Hello @emmecii, the key detail in your log is
```
/home/ivan/.local/share/Steam/ubuntu12_32/steamwebhelper: error while loading shared libraries: libgpg-error.so.0: cannot open shared object file: No such file or directory
```
which means you are missing 32 bit libgpg-error.so.0. I'm not an ubuntu user, but I can guess that ```sudo apt-get install libgpg-error0:i386``` should help.

**Comment by emmecii** [comment]
@Tele42 libgpg-error0 is a package already installed in my system (most probably required during the post-installation/configuration of  steam.deb)

**Comment by jonpile** [comment]
@emmecii - when you try to navigate to the community (or store) page within the client, does the throbber stop spinning? Or does it just trundle along forever?

**Comment by emmecii** [comment]
@jonpile The throbber trundle forever like if the browser is waiting for a response from the server, but failing to close the connection for a HTTP error. The page is black.

![screen 1 2016-09-10 20-06-10](https://cloud.githubusercontent.com/assets/22106041/18412576/31207db2-7792-11e6-877d-6bfc6a47537c.png)
![screen 2 2016-09-10 20-06-44](https://cloud.githubusercontent.com/assets/22106041/18412577/312c3d0a-7792-11e6-979a-6a680a5b897c.png)

**Comment by rkfg** [comment]
For me the message was: `/opt/SteamLinux/ubuntu12_32/steamwebhelper: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory`

I strace'd the client with `strace -fp $(pidof -s steam) -e file -t` and found out that it doesn't search its own runtime and other directories, only the system ones. So I copied `libcef.so` to `/usr/lib/i386-linux-gnu/` and voila, it works. So I suppose the `steam` process doesn't preserve the environment when launching `steamwebhelper` (and with `cat /proc/$(pidof -s steamwebhelper)/environ | tr '\0' '\n' | grep LD_LIBRARY_PATH` returning nothing this is confirmed).

Please fix.

**Comment by rkfg** [comment]
Hmm, that's not it. It was my own mistake, played with capabilities and set `cap_net_admin,cap_sys_admin+eip` to `/bin/dash`, after removing them everything works fine. False alarm.

**Comment by gforceg** [comment]
I had this same issue. I think the libs create a "version drift" between updates on distros such as Fedora where things are updated frequently.

After a few days a steam client update came through and now everything is working for me. :D

**Comment by kisak-valve** [comment]
Hello @emmecii, are you still experiencing this issue on an up to date system?

**Comment by emmecii** [comment]
> Hello @emmecii, are you still experiencing this issue on an up to date system?

I forgot this issue, now it work perfectly on Ubuntu 18.04.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
