### ISSUE TITLE
Launching with -bigpicture fails in fvwm2 and has screen corruption

### ISSUE THREAD

**Issue by pancus** [ValveSoftware/steam-for-linux#4625]
#### Your system information
- Steam client version: 1471977975
- Distribution (e.g. Ubuntu): Gentoo
- Opted into Steam client beta?: Yes (tested both)
- Have you checked for system updates?: Yes (full upgrade)
#### Please describe your issue in as much detail as possible:

I use fvwm2 on my linuxbox as a lightweight wm for running kodi and whatnot. Logging into steam previously worked fine a few months back (sorry don't have a better timeline), tried it a few days ago and since then it no longer works. Removing -bigpicture from the commandline brings up the regular menu, logging in works fine, launching BPM from there works fine, launching games works fine (only tested 2). Launching with -bigpicture I can hear the boot sound but the screen remains black, a long pause then the screen pops up with corruption.

used vnc on my phone to get a [screenshot](http://imgur.com/a/ccbFW)

the very simple /etc/system.fvwm2rc

```
DeskTopSize 1x1

Style *         NoTitle, NoHandles, Sticky, WindowListSkip, BorderWidth 0, StaysOnTop
```

Now if I wait it out, let it load and login (slowly, input is very sluggish, whole process takes a few minutes) then it goes back to normal. BPM works like it should, sometimes there is background corruption but usually not. To be clear I do not believe this is the video card dying as launching without BPM has no corruption.

Everything is launched using a lengthy custom script (usually from lircd). the meat of it is

```
nohup startx -- :0 >/dev/null 2>&1 &
/usr/bin/fvwm2 -f /etc/system.fvwm2rc &
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session /usr/bin/steam -login login pass "steam://open/bigpicture"
```

I have steam on two other linux machines (desktop and optimus laptop) with kde5, no issues.
#### Steps for reproducing this issue:
1. launch script above.
2. fails.

**Comment by J4nsen** [comment]
Same here on Ubuntu 16.04 x64 with nvidia-367. Window managers tested: kwin & openbox.

Downgrading the driver to nvidia-340 fixes the problem. :-/

**Comment by kisak-valve** [comment]
Hello @pancus, is your desktop also an nvidia system?

**Comment by pancus** [comment]
Yes.
01:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 630 Rev. 2] (rev a1)

I haven't tested this issue in a while. The motherboard has been upgraded but the video card is the same. Luckily I did not need to reinstall the OS (lateral upgrade really). The system was fully upgraded about a week ago, would you like me to test this again?

**Comment by kisak-valve** [comment]
It would be good to know if 375.26 is affected. If that combined with 340.xx are fine, then this issue is effectively resolved on the driver side.

**Comment by pancus** [comment]
Works fine now. nvidia 375.26

**Comment by kisak-valve** [comment]
Thanks @pancus, closing as fixed driver-side.
