### ISSUE TITLE
SUID Sandbox "required" by Steam is deprecated

### ISSUE THREAD

**Issue by robinhood2014** [ValveSoftware/steam-for-linux#4627]
#### Your system information
- Steam client version: 1:1.0.0.48-1ubuntu3
- Distribution (e.g. Ubuntu): Linux Mint
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

I expected Steam to start as it did in Windows, but absolutely nothing happened.
#### Steps for reproducing this issue:
1. In order to troubleshoot the problem, I had to run Steam from a terminal. First, I got errors that said I was missing the drivers for "r600" and "swrast". My computer has an AMD Radeon HD 7340 video card; sadly, AMD seems to have stopped making drivers for that card.
2. I ran a Google search on "r600 and swrast not found" and discovered that some bright soul disabled the Steam runtime en route to troubleshooting his problem; i.e. "STEAM_RUNTIME=0 steam".
3. When I duplicated this process, I received all of this garbage: 
   https://gist.github.com/robinhood2014/b7357e34a657bb35f736515f0e7fbb11
4. Focusing on the message "Running without the SUID sandbox!", I followed the accompanying link, which directed me to a couple of pages that said the Linux SUID sandbox is deprecated and needs to be replaced in Steam:
   https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md
   https://bugs.chromium.org/p/chromium/issues/detail?id=598454
5. Therefore, until the Linux SUID sandbox is replaced, Steam is unusable in Ubuntu and derivatives (including Linux Mint).

**Comment by gdrewb-valve** [comment]
Was some functionality not actually working or are you only commenting on the terminal spew?

**Comment by ameriviking** [comment]
If like my experience it's definitely functionality. Despite at least 3 major tweaks, and several attempts to install, mine simply won't work. I'm running Nvidia. I've tried on Mint 17.3 32bit Cinnamon and Xfce. KDE 64bit starts but won't run games but that is a hardware limitation on that computer. 17.2 32bit ran fine, so I'm inclined to believe it's root problem (no punn intended) is a change in 17.3 32bit only.

**Comment by mtmkls** [comment]
If it says that drivers for "r600" and "swrast" are not found, then you should first focus on installing a working video driver before focusing on hacking steam into pieces. What is the version of mesa on your system? You can use the command "dpkg -l | grep mesa"  to list the relevant packages. Note that steam and most of its games are 32bit, so on a 64bit system you need to add i386 as a secondary architecture, and install the necessary 32bit libraries. Refer to the manual of your distribution on how to do that.

Oh and by the way AMD didn't stop making drivers for your card. The binary-only driver (fglrx) was discontinued, but the drivers for AMD cards in Mesa are mostly developed by AMD people.

**Comment by Kakurady** [comment]
@mtmkls ideally, shouldn't installing Steam from Valve take care of the driver dependency? It should "just work".

**Comment by kisak-valve** [comment]
Hello @robinhood2014, are you still experiencing this issue on an up to date system?

You've indicated that you had disabled the Steam runtime and then your log was telling you that steamclient.so was missing a dependency which would normally be provided by the Steam runtime. This is unrelated to libcef telling you it was running without a sandbox.

**Comment by kisak-valve** [comment]
Closing pending feedback.
