### ISSUE TITLE
Robocraft fails to launch with gameoverlayrenderer.so from LD_PRELOAD error

### ISSUE THREAD

**Issue by rottekruid** [ValveSoftware/steam-for-linux#4628]
#### Your system information

* Steam client version: 1471977975
* Distribution (e.g. Ubuntu): Ubuntu 14.04 64-bit
* Opted into Steam client beta?: No idea, not impossible 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Robocraft used to launch and work fine, however a few weeks ago it just would not launch anymore with the following errors:

```
ExecSteamURL: "steam://rungameid/301520"
Game update: AppID 301520 "Robocraft", ProcID 8038, IP 0.0.0.0:0
ERROR: ld.so: object '/home/dude/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dude/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Found path: /data/STEAM/steamapps/common/Robocraft/Robocraft.x86_64
Mono path[0] = '/data/STEAM/steamapps/common/Robocraft/Robocraft_Data/Managed'
Mono path[1] = '/data/STEAM/steamapps/common/Robocraft/Robocraft_Data/Mono'
Mono config path = '/data/STEAM/steamapps/common/Robocraft/Robocraft_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
client has 4 screens
displaymanager screen (0)(eDP1): 1920 x 1080
Using libudev for joystick management


Importing game controller configs
Game removed: AppID 301520 "Robocraft", ProcID 8038
```

#### Things I have tried so far:

* I have verified Robocraft's game cache and I have re-installed the game, but it did not solve the problem. 
* I have done `steam --reset`, but without having any effect on the problem.

**Comment by Tele42** [comment]
Hello

**Comment by Tele42** [comment]
Hello @rottekruid,

I looks like Robocraft is currently using Unity 5.3.6f1. The engine log should be at ```~/.config/unity3d/Freejam/RobocraftClient/Player.log```, please copy and paste it into a gist and include a link in this issue report.

**Comment by rottekruid** [comment]
Hi @Tele42,

Thanks, I have created the [requested gist](https://gist.github.com/rottekruid/3738262b8f9e592d4a54eef342ad697f).

**Comment by rottekruid** [comment]
Thank you for your help @Tele42, you have pointed me in the right direction. I got Robocraft to launch now.

The screen resolution values were invalid in the preference file `~/.config/unity3d/Freejam/RobocraftClient/prefs`

After changing the resolution values to 768 X 1280, the game launched just fine.

```
<pref name="Screenmanager Resolution Height" type="int">768</pref>
<pref name="Screenmanager Resolution Width" type="int">1280</pref>
```

My issue seem related to a Robocraft update (or some other process) that changed the resolution values and not the Steam Linux client.
