### ISSUE TITLE
Steam doesn't work in kali rolling 2016.2

### ISSUE THREAD

**Issue by Margular** [ValveSoftware/steam-for-linux#4629]
- Steam client version:1.0.0.52-4
- Distribution (e.g. Ubuntu): kali rolling 2016.2
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Running Steam on kali kali-rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
sh: 1: /home/cui/.local/share/Steam/steam_msg.sh: not found
Assert( Assertion Failed: Could not open connection to X ):updateui_xwin.cpp:337

Installing breakpad exception handler for appid(steam)/version(1.0)
crash_20160916082027_3.dmp[16873]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160916082027_3.dmp
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2016-09-16 08:20:27] Startup - updater built Mar 29 2016 17:40:06
updateui_xwin.cpp (337) : Assertion Failed: Could not open connection to X
main.cpp (514) : Assertion Failed: failed to initialize update status ui, or create initial window
crash_20160916082027_3.dmp[16873]: Finished uploading minidump (out-of-process): success = yes
crash_20160916082027_3.dmp[16873]: response: CrashID=bp-2b391277-1207-45d5-bd61-53ea62160915
crash_20160916082027_3.dmp[16873]: file ''/tmp/dumps/crash_20160916082027_3.dmp'', upload yes: ''CrashID=bp-2b391277-1207-45d5-bd61-53ea62160915''
#### Steps for reproducing this issue:
1. I tried xhost +;steam
   `xhost:  unable to open display ":0steam"`
2. I tried STEAM_RUNTIME=0 steam
   just like my questioned issue
3. I have tried 
   `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get dist-upgrade`

They are not work.

**Comment by kisak-valve** [comment]
Hello @Margular, are you still experiencing this issue on an up to date system? In particular, does it behave better with the 1.0.0.55 steam package or newer?

In general, Kali Linux is one of the few distros that is not considered supported for Steam on Linux because the distro considers general desktop use a non-feature.
