### ISSUE TITLE
[Linux Client] Steam HTML video player no image, sound ok.

### ISSUE THREAD

**Issue by corvusd** [ValveSoftware/steam-for-linux#4634]
#### Your system information
- Steam client version: Build: Sep 20 2016 at 18:21:08, Steam API: v017, Steam Package versions: 1474475843
- Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS 64 bits
- Opted into Steam client beta?: [Yes/No] No
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

Expect see de video in the section. The result is this:
[Screeshot](http://pix.toile-libre.org/upload/original/1474794147.jpg)
#### Steps for reproducing this issue:
1. Go to Steam Machines section
2. Go to video.

**Comment by kisak-valve** [comment]
Hello @corvusd, are you still experiencing this issue on an up to date system?

**Comment by corvusd** [comment]
I think no, because was in strem machine store page. Ans now this not exist any more. All the rest video run fine.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
