### ISSUE TITLE
Client Push-to-talk not working, Mic volume slider ignored.

### ISSUE THREAD

**Issue by HellishINC** [ValveSoftware/steam-for-linux#4635]
#### Your system information
- version: Stable + Beta
- Distribution: Arch*
- beta?: y
- system updates?: Multiple times daily.
#### issue :

Because on my system using steam's libs resulted in more issues than I'd like to list, I'm using native libs. (STEAM_RUNTIME=0) Steam refuses to load at all with its libs.
As described in (closed) issue #2066, PTT in the steam client does not work. Setting to PTT results in a still open mic. Microphone input volume slider also does nothing. My system is pure ALSA though this issue also exsisted when using Pulse in a XFCE4 setup. I also use a DMIX setup as is required for a functional system.

Games such as Dota2 and CS:GO have functional PTT. This only affects client voice chat.
#### reproducing:
1. Run steam
2. Set voice options to push-to-talk
3. Not profit.

```
$ cat /proc/asound/cards
 0 [D1             ]: AV200 - Xonar D1                        <--- Output
                      Asus Virtuoso 100 at 0xd000, irq 17
 1 [Device         ]: USB-Audio - C-Media USB Audio Device    <--- Input
                      C-Media USB Audio Device at usb-0000:03:00.0-1.2, full speed

$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: D1 [Xonar D1], device 0: Multichannel [Multichannel]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: D1 [Xonar D1], device 1: Digital [Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [C-Media USB Audio Device], device 0: USB Audio [USB Audio] <---- Device in use
  Subdevices: 1/1
  Subdevice #0: subdevice #0

  $ lspci | grep -i audio
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT HDMI Audio [Radeon HD 7970 Series] *Blacklisted*
05:00.0 Multimedia audio controller: C-Media Electronics Inc CMI8788 [Oxygen HD Audio] *This is my Asus Xonar card, not usb mic*

```

**Comment by HellishINC** [comment]
Just want to add that this is still an issue. Using Pulse now instead of pure ALSA.

Same soundcard, same usb mic. Still using Arch but running kernel 4.12.4 and newer libraries.

**Comment by h1z1** [comment]
What is in your ~/.asoundrc though

**Comment by HellishINC** [comment]
Closing as this no longer applies since steam is now running on chrome.
