### ISSUE TITLE
Problem with the logic keeping the SteamOS browser locked up before you receive your security key to unlock the Steam client GUI.

### ISSUE THREAD

**Issue by LexBarringer** [ValveSoftware/steam-for-linux#4640]
The biggest problem I've seen and I've mentioned this numerous times to Valve Software customer support but seems to go nowhere. The problem is this, when you first install SteamOS and everything is all ready and then you go to login you fill in your account information and then it asks for your security code but there is a serious problem. How do you get to the browser to get at your E-Mail to read the code and put it into the box that's asking for it? Surely you people at Valve Software have thought this one through. You expect the person using this to have a smart phone or another computer to access your E-Mail account to get that code so you can unlock the fullscreen GUI. Then do, what? Access the Steam browser? This should be accessible before you're asked for the security code to unlock the GUI.

Some of us don't have smartphones, so that makes it very tough. For me as a developer, I have multiple computer and I can check my E-Mail on any of them but there will probably be someone that doesn't have a smartphone nor an extra computer, just a Steam Machine.

Do you see the problem in logic? As a matter of fact; all of the GUI and the browser (which is a part of it) should be accessible after the install is done. When it boots into full-screen mode, the GUI should be accessible without having to login to your system. People should be able to use the system and tweak / tune the settings to their liking, start the browser, login and go from there.

This is the reason why I prefer to use Xubuntu, SteamOS it's not quite up to par just yet.

**Comment by gdrewb-valve** [comment]
Did you mean to file this in the SteamOS repo?  This isn't really the right area for it.

**Comment by LexBarringer** [comment]
Good point, however, I tried to post in the repo and for some reason I didn't have permission to do so. I will give a try again.

**Comment by Plagman** [comment]
Tracked in the SteamOS issue list now.
