### ISSUE TITLE
PA Titans won't start on ubuntu 16.04

### ISSUE THREAD

**Issue by alberto-esposito** [ValveSoftware/steam-for-linux#4641]
I am running ubuntu 16.04 64 bit, OS and steam are updated. 

PA: Titans stopped working, it freeze at start. It runs if I launch it from the executable. 

Here's the console log:

http://pastebin.com/ixWntLcx

I've tried to preload several libraries, as suggested by arch wiki, but it doesn't work.

**Comment by Tele42** [comment]
Hello @servermeta, your backtrace is hinting that something's gone wrong in libasound.so.2, does preloading the system variant of that along with what you are already doing change the behavior?

**Comment by JOndra91** [comment]
This is known issue: [Titans on Ubuntu 16.04 Steam not working](https://forums.uberent.com/threads/titans-on-ubuntu-16-04-steam-not-working.71646/#post-1128751)

Preloading system version of libasound.so.2 "solves" the issue.

**Comment by kisak-valve** [comment]
Hello @alberto-esposito, since this issue report was last commented on Steam has changed how it handles the Steam runtime. It now prefers the host system's libraries if they are newer than the Steam runtime variant.

Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
