### ISSUE TITLE
Client fails to start - coredump

### ISSUE THREAD

**Issue by markitoxs** [ValveSoftware/steam-for-linux#4642]
#### Your system information
- Steam client version:
  Name            : steam
  Version         : 1.0.0.52-4
  Description     : Valve's digital software delivery system
  Architecture    : x86_64
  Kernel:  Linux casablanca 4.8.0-rc6-gd4690f1 #1 SMP PREEMPT Sun Sep 18 14:31:19 PDT 2016 x86_64 GNU/Linux
- Distribution (e.g. Ubuntu): 
  Arch Linux
- Opted into Steam client beta?: [Yes/No] 
  N/A Unable to. 
- Have you checked for system updates?: [Yes/No] 
  Yes

I started the client and it got stuck in checking for updates. After a file it just closed. 

Since then, lauching with native/steam runtime causes a core dump. It should be uploaded:

```
~  steam
/home/markitoxs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
/home/markitoxs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/markitoxs/.local/share/Steam/steam.sh: line 161: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1474415843)
assert_20161001141252_1.dmp[1663]: Uploading dump (out-of-process)
/tmp/dumps/assert_20161001141252_1.dmp
/home/markitoxs/.local/share/Steam/steam.sh: line 756:  1660 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20161001141252_1.dmp[1663]: Finished uploading minidump (out-of-process): success = yes
assert_20161001141252_1.dmp[1663]: response: CrashID=bp-28f41896-72f6-46de-92b4-e99162161001
assert_20161001141252_1.dmp[1663]: file ''/tmp/dumps/assert_20161001141252_1.dmp'', upload yes: ''CrashID=bp-28f41896-72f6-46de-92b4-e99162161001''
```

**Comment by markitoxs** [comment]
I have also attempted steam --reset , which doesnt fix the issue. 

I have also attempted to laucnh with  LIBGL_DRI3_DISBALE=1 just in case, but not change.

**Comment by ambiente1** [comment]
Same for me @markitoxs .

Client was updated on 23.09.2016 to latest version.
After that, the client crashs after i try to login with same coredump.

I already tried whole reset and blank re-installation without any success.

#### Your system information

* Steam client version: 1474415843
* Distribution (e.g. Ubuntu): Gentoo 13.0
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

> ~ $ steam 
Running Steam on gentoo 13.0 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: wrong number of matrix elements
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[1002/140706:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20160920182018)
Installing breakpad exception handler for appid(steamwebhelper)/version(1474395618)
Installing breakpad exception handler for appid(steamwebhelper)/version(20160920182018)
Installing breakpad exception handler for appid(steamwebhelper)/version(1474415843)
Installing breakpad exception handler for appid(steamwebhelper)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Created shared memory when not owner SteamController_Shared_mem
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
Generating new string page texture 7: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 8: 48x256, total string texture memory is 180.22 KB
Generating new string page texture 9: 256x256, total string texture memory is 442.37 KB
Generating new string page texture 10: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 11: 8x256, total string texture memory is 516.10 KB
Generating new string page texture 12: 16x256, total string texture memory is 532.48 KB
Generating new string page texture 13: 24x256, total string texture memory is 557.06 KB
Generating new string page texture 14: 32x256, total string texture memory is 589.82 KB
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Installing breakpad exception handler for appid(steam)/version(1474415843)
Generating new string page texture 16: 384x256, total string texture memory is 983.04 KB
crash_20161002140705_1.dmp[31194]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161002140705_1.dmp
/home/alex/.local/share/Steam/steam.sh: line 713: 29062 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20161002140705_1.dmp[31194]: Finished uploading minidump (out-of-process): success = yes
crash_20161002140705_1.dmp[31194]: response: CrashID=bp-bce28114-5759-494a-a43f-b70672161002
crash_20161002140705_1.dmp[31194]: file ''/tmp/dumps/crash_20161002140705_1.dmp'', upload yes: ''CrashID=bp-bce28114-5759-494a-a43f-b70672161002''

**Comment by markitoxs** [comment]
Absolutely unable to use steam at this point. I even completely deleted ~/.local/share/Steam but still no go.

**Comment by markitoxs** [comment]
alright, so after some easy debugging, probably is the fault of the amd driver:

**Comment by markitoxs** [comment]
So, I uninstalled the amdgpu driver and using mesa it does indeed load and work. 
What changed? Why was this working for months and all of a sudden it core dumps?

**Comment by Tele42** [comment]
Hello @markitoxs, you should also contact the video driver vendor if you wish to pursue this further.

**Comment by markitoxs** [comment]
I'd give that a shot, but there were no video drivers update. The only thing that updated was steam.

**Comment by ambiente1** [comment]
For me, i tried several installation methods and saw via dmesg this error coming up when client crashs:

> steam: segfault at f57a4513 ip 00000000f6371aa5 sp 00000000ffbefc5c error 7 in libcrypto.so.1.0.0[f6233000+1e0000]

Seems, this could be related to the latest OpenSSL-1.0.2j ?

**Comment by puustina** [comment]
Been having this problem since I clicked "Cancel" on the Steam Updater which appears upon starting Steam. I think this was just under a week ago. Tried --reset and manually clearing the Steam installation folder along with a reinstall through the package manager. Also tried reinstalling older versions from the package manager cache but the same error persisted. With a debugger I reached the same result as @markitoxs.
> Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) backtrace
#0  0x00000000 in ?? ()
#1  0xf6b2d89a in ?? () from /usr/lib32/dri/amdgpu_dri.so
Backtrace stopped: previous frame inner to this frame (corrupt stack?)


System information
Steam client version: 1.0.0.52-4 (according to pacman, VERSION_ID is unbound as with @markitoxs)
Distribution (e.g. Ubuntu): Arch Linux 4.7.2-1-cik kernel for 290X support with AMDGPU-PRO drivers.
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

@ambiente1 All I see in dmesg when Steam coredumps is
> [269426.488708] steam[9178]: segfault at 0 ip           (null) sp 00000000ff8eb4f8 error 14 in steam[56598000+3a9000]

**Comment by markitoxs** [comment]
@Tele42 it seems that other users are having the same result as me. 

Steam working correctly, and after a "steam update" failure/cancellation we are completely unable to start.

**Comment by markitoxs** [comment]
Ok, so more data points, I reinstalled amdgpu-pro (**exact same version** as when it was all working correctly.) Now, whenever I run steam, X crashes immediately. 

Checking the journal:

```
Oct 06 21:28:03 casablanca systemd[1]: Started Process Core Dump (PID 7512/UID 0).
Oct 06 21:28:03 casablanca org.a11y.atspi.Registry[603]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Oct 06 21:28:03 casablanca org.a11y.atspi.Registry[603]:       after 93 requests (93 known processed) with 0 events remaining.
Oct 06 21:28:03 casablanca pulseaudio[7180]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
Oct 06 21:28:03 casablanca pulseaudio[7180]:       after 12 requests (6 known processed) with 0 events remaining.
Oct 06 21:28:03 casablanca systemd[491]: pulseaudio.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 21:28:03 casablanca systemd[491]: pulseaudio.service: Unit entered failed state.
Oct 06 21:28:03 casablanca systemd[491]: pulseaudio.service: Failed with result 'exit-code'.
Oct 06 21:28:03 casablanca polkitd[505]: Unregistered Authentication Agent for unix-session:c18 (system bus name :1.167, object path /org/gnome/PolicyKit1/AuthenticationAg
Oct 06 21:28:03 casablanca lightdm[7228]: pam_unix(lightdm:session): session closed for user markitoxs
Oct 06 21:28:03 casablanca systemd[491]: pulseaudio.service: Service hold-off time over, scheduling restart.
Oct 06 21:28:03 casablanca systemd[491]: Stopped Sound Service.
Oct 06 21:28:03 casablanca systemd[491]: Starting Sound Service...
Oct 06 21:28:03 casablanca rtkit-daemon[502]: Successfully made thread 7519 of process 7519 (/usr/bin/pulseaudio) owned by '1000' high priority at nice level -11.
Oct 06 21:28:03 casablanca rtkit-daemon[502]: Supervising 1 threads of 1 processes of 1 users.
Oct 06 21:28:03 casablanca pulseaudio[7519]: W: [pulseaudio] pid.c: Stale PID file, overwriting.
Oct 06 21:28:04 casablanca systemd-coredump[7513]: Process 7181 (Xorg) of user 0 dumped core.
                                                   
                                                   Stack trace of thread 7181:
                                                   #0  0x00007ff28369704f raise (libc.so.6)
                                                   #1  0x00007ff28369847a abort (libc.so.6)
                                                   #2  0x000000000059f40e OsAbort (Xorg)
                                                   #3  0x000000000047b25c ddxGiveUp (Xorg)
                                                   #4  0x00000000005a5072 n/a (Xorg)
                                                   #5  0x00000000005a5e7d FatalError (Xorg)
                                                   #6  0x000000000059cc8e n/a (Xorg)
                                                   #7  0x00007ff2836970b0 __restore_rt (libc.so.6)
                                                   #8  0x00007ff27d471897 n/a (amdgpu_dri.so)
                                                   #9  0x00007ff27c90df77 n/a (amdgpu_dri.so)
                                                   #10 0x00007ff27c88b236 n/a (amdgpu_dri.so)
                                                   #11 0x00007ff27d2ea16c n/a (amdgpu_dri.so)
                                                   #12 0x00007ff27d3f7113 n/a (amdgpu_dri.so)
                                                   #13 0x00007ff27d3f1d76 n/a (amdgpu_dri.so)
                                                   #14 0x00007ff27d3ef3c0 eglCreateImageKHR (amdgpu_dri.so)
                                                   #15 0x00007ff27f1c3c74 glamor_egl_create_textured_pixmap (amdgpu_drv.so)
                                                   #16 0x00007ff27f1a71d4 amdgpu_glamor_create_textured_pixmap (amdgpu_drv.so)
                                                   #17 0x00007ff27f19c987 amdgpu_set_shared_pixmap_backing (amdgpu_drv.so)
                                                   #18 0x00007ff27f1a721b n/a (amdgpu_drv.so)
                                                   #19 0x00007ff27f19f3a3 n/a (amdgpu_drv.so)
                                                   #20 0x000000000056da61 n/a (Xorg)
                                                   #21 0x000000000056d381 n/a (Xorg)
                                                   #22 0x000000000043673f n/a (Xorg)
                                                   #23 0x000000000043a763 n/a (Xorg)
                                                   #24 0x00007ff283684291 __libc_start_main (libc.so.6)
                                                   #25 0x00000000004246e9 _start (Xorg)
```

So basically the steam client is somehow doing something that is making amdgpu VERY angry. 

Now, more interestingly, if I open steam from a terminal, it loads up fine. Pops up with the' Updating Steam...' window, Checking for available update.

Checking the logs shows that all the files are somehow corrupt?
```
...
[2016-10-06 21:32:44] BVerifyInstalledFiles: tenfoot/resource/layout/streaming/howtostream.xml is -1 bytes, expected 1257
[2016-10-06 21:32:44] BVerifyInstalledFiles: tenfoot/resource/layout/streaming/streamingdetails.xml is -1 bytes, expected 1019
[2016-10-06 21:32:44] BVerifyInstalledFiles: tenfoot/resource/layout/streaming/streamingoverlay.xml is -1 bytes, expected 554
...
```
 Then after a while it moves into Extracting package...  then into unpacking steam runtime. 

I then get presented with two windows, the standard Create new account/Login to an existing account, and a popup window with a warning about direct rendering with a link to the KB. 

From here I can log in just fine. But upon next steam launch, bam, the same thing. If launched from xfce menu, X restarts, if launched from terminal, stame thing, updating/extracting/logging again.

**Comment by markitoxs** [comment]
Alright, more data!

From terminal: 
STEAM_RUNTIME=1 works
STEAM_RUNTIME=0 causes X restart

**Comment by markitoxs** [comment]
Could this maybe be caused by libc.so.6 instead?

**Comment by markitoxs** [comment]
@puustina can you maybe do this?
`
pacman -Qo /usr/lib/libc.so.6
`
I get:
```
/usr/lib/libc.so.6 is owned by glibc 2.24-2
```

**Comment by puustina** [comment]
@markitoxs Same thing here:
> /usr/lib/libc.so.6 is owned by glibc 2.24-2

According to pacman log (/var/log/pacman.log) glibc and lib32-glibc were updated on 2016-09-25 on my system.

**Comment by mikel392** [comment]
i'm having the same problem was able to play cs:go before  steam broke after i updated to amdgpu-pro

**Comment by tpgxyz** [comment]
My system after yesterday steam update crashes at start. Ofcourse removing local steam files and bootstrapping it again does not help.
There were no system updates related to openssl, glibc or any other core stuff on my OpenMandiva Lx 3.0 system during past few days.

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 9285]
0xf647cd4e in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libcrypto.so.1.0.0
(gdb) backtrace
#0  0xf647cd4e in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libcrypto.so.1.0.0
#1  0xf647cf5c in ENGINE_finish () from /home/tpg/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libcrypto.so.1.0.0
#2  0xf646aa6e in RSA_free () from /home/tpg/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libcrypto.so.1.0.0
#3  0xeeafca07 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#4  0xee7db03a in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xee7dd502 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xee4ace3b in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#7  0xee4b2258 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xee4aa0fe in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xeeb5a7c0 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#10 0xeeb5cd80 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#11 0xee4aa14e in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#12 0xeeb5fcc2 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xeeb5fd5c in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xeecdd6b1 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xeeb51c56 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xeeb07151 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xeeb07c8e in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xee207ad9 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xee208956 in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/steamclient.so
#20 0xf1ec3ec0 in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/tpg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#21 0xf1ec216b in ?? () from /home/tpg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#22 0xf1ec243f in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/tpg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf1ec2491 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/tpg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf1ec6ad1 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/tpg/.local/share/Steam/ubuntu12_32/libtier0_s.so
#25 0xf7cfee62 in start_thread () from /lib/libpthread.so.0
#26 0xf7c4426e in clone () from /lib/libc.so.6

**Comment by kisak-valve** [comment]
Hello, I'm going to close this because general video driver issues from 2016 is no longer relevant.

The mesa issue was limited to the 13.0.x release cycle.

If anyone happens across a similar issue on an up to date system, it will need a new investigation.
