### ISSUE TITLE
[Security Issue] Steamlogin cookies aren't randomly generated

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4643]
The steamLogin cookie value isn't randomly generated, at least all digits aren't because the first ones seem to be the same every time which means = BAD PROGRAMMING = BAD PROGRAMMERS = BAD SECURITY

**Comment by gdrewb-valve** [comment]
As you have been told before, please open a Steam support ticket for issues like this.

**Comment by ekaris** [comment]
I prefer the public tracker

**Comment by gdrewb-valve** [comment]
Sorry, I'll be more clear: you have had many warnings about deliberately abusing this forum.  If you post another issue like this you will be banned.

**Comment by ekaris** [comment]
I'm not abusing the forum. 
Then ban if you want.

**Comment by Tele42** [comment]
@ekaris, you have consistently opened issue reports for your concerns about Valve's web services (not OS specific) to the steam-for-linux port team (Linux steam client only) for higher visibility of your opinions.

As a side note, if you had reported any security issue of consequence in this way, it's both highly unethical and an irresponsible disclosure of information to contact a company publicly before they have a reasonable amount of time to acknowledge and triage the security issue(s).

**Comment by ekaris** [comment]
@Tele42 I have opened issues about Linux specific stuff like the embedded chromium browser is currently at version 49 full of security bugs while the latest stable version as of today is  53, also worth nothing is that sandbox is disable on the Linux client and not on windows or mac.

It's not irresponsible disclosure, if you had any experience in reporting vulnerabilities you would know that some company care and other's don't (like valve) so in this case the best way is to make it public until they decide to hire a security team or fire the existing one.

**Comment by apaloma** [comment]
@ekaris Instead of reporting security issues here, please send an email to security@valvesoftware.com. See here for more info: http://www.valvesoftware.com/security/

**Comment by ekaris** [comment]
@apaloma Thanks man, an email, that's what I wanted, didn't want to deal with customer support :D
