### ISSUE TITLE
Ubuntu repository failure

### ISSUE THREAD

**Issue by jpptinsley** [ValveSoftware/steam-for-linux#4648]
**Your system information**

-     Steam client version: 1474415843
-     Distribution (e.g. Ubuntu): Ubuntu 16.04
-     Opted into Steam client beta?: [Yes/No] No
-     Have you checked for system updates?: [Yes/No] Yes

**Please describe your issue in as much detail as possible:**

Apt reports that Steam's debian repository is missing a Releases file:
https://gist.github.com/jpptinsley/a2be806f86fe1e1c665a3ef399bea545

Steps for reproducing this issue:
1. Repository; ```deb http://repo.steampowered.com/steam/ xenial steam```
2. ```sudo apt-get update```

**Comment by Tele42** [comment]
There is only one ubuntu variant in that repo, ubuntu precise (12.04). Either use that with xenial or use the distro-packaged variant (http://packages.ubuntu.com/xenial/steam).

**Comment by jpptinsley** [comment]
@Tele42 thanks. Closing issue.
