### ISSUE TITLE
Steam needs Preload after ubuntu 16.04 update to start, but games wont

### ISSUE THREAD

**Issue by rhagu** [ValveSoftware/steam-for-linux#4650]
#### Your system information
- Steam client version: v017  Steam-Paket-Version: 1475701795
- Distribution (e.g. Ubuntu): Ubuntu 16.04.1 
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Hi, I had Steam running on Ubuntu 16.04.1 until about a month ago, when steam was updated. After the update I was unable to start steam unless I used the preload option mentioned at: https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Dynamic_linker

Using this workaround I was able to start steam, but my games wouldn't start anymore.

Starting Civ V from the command line without starting steam first, works. Therefore I think the dynamic linker option enables me to start steam, but makes all the games fail.

This was all done without joining the beta program. The steam support asked me to reinstall steam and then join the beta program to fix the issue, but neither worked.
#### Steps for reproducing this issue:
1. Use the open source r600 drivers, that come with Ubuntu 16.04.1 
2. Install steam from the repository and update your system and steam
3. See how steam fails to start

I have attached the terminal output I see, when I try to start steam without dynamic linker option as no_dynamic_linker_at_steamstart.txt

[no_dynamic_linker_at_steamstart.txt](https://github.com/ValveSoftware/steam-for-linux/files/517518/no_dynamic_linker_at_steamstart.txt)

And the terminal output I see, when I start steam with dynamic linker option and the game CiV_Beyond_Earth

[dynamic_linker_starting_civ_beyond_earth.txt](https://github.com/ValveSoftware/steam-for-linux/files/517523/dynamic_linker_starting_civ_beyond_earth.txt)

kind regards,
rhagu

**Comment by kisak-valve** [comment]
Hello @rhagu, are you still experiencing this issue on an up to date system?

Steam's handling of the Steam runtime has changed to prefer the system variant of libraries over the Steam runtime if they are newer, which avoids the common case for this kind of issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
