### ISSUE TITLE
libGL.so.1 is missing

### ISSUE THREAD

**Issue by giulianisanches** [ValveSoftware/steam-for-linux#4654]
#### Your system information

* Steam client version: Lastest Steam on Debian Jessie (from repositories)
* Distribution (e.g. Ubuntu):  Debian Jessie
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I installed all required packages from jessie-backports, but when i try to run steam i got the following error:

![e1](https://cloud.githubusercontent.com/assets/81200/19224603/8f59a5f0-8e5f-11e6-833c-a3316dad65bc.jpg)

I have found the required file under a primus lib diretory. Tirying to run steam with primusrun, i got the following errors (primusrun raise the same error):

![e2](https://cloud.githubusercontent.com/assets/81200/19224605/953976b2-8e5f-11e6-9307-ad1de09e92fe.jpg)

#### Steps for reproducing this issue:

1. Follow the instructions here https://wiki.debian.org/Bumblebee and here https://wiki.debian.org/Steam but using the jessie-backports (apt -t jessie-backports install <package-name>)
2. Try to run steam with and without the optirun (or primusrun)

**Comment by gdrewb-valve** [comment]
Steam is a 32-bit app so you'll need 32-bit OpenGL in addition to 64-bit OpenGL.  That usually comes from your video driver.  What version of the NVIDIA driver do you have installed?

**Comment by giulianisanches** [comment]
Yes, i have both 32 and 64bits installed.

For the NVIDIA version, i followed the steps here:

- https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_8_.22Jessie.22

Using -t jessie-backports switch.

Looking at https://packages.debian.org/jessie-backports/nvidia-driver, version is 352.79.

**Comment by ProfessorKaos64** [comment]
That library is provided in [these packages](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=contents&keywords=libGL.so.1). The [nvidia-driver-libs](https://packages.debian.org/jessie-backports/nvidia-driver-libs) dependency pulls in [libgl1-nvidia-glx)](https://packages.debian.org/jessie-backports/libgl1-nvidia-glx) and that library. I'm not sure that installing the :i386 nvidia-driver with a `-t` switch assumes to install the :i386 driver of libgl1-nvidia-glx. Can you check the status of the libgl1-nvidia-glx:i386 package?

**Comment by giulianisanches** [comment]
Hi,

I have all those packages installed using :i386 switch or the packages with -i386 in their name, including libgl1-nvidia-glx and libgl1-mesa-glx (32 and 64).

In the attatched screenshot in my first comment, you will see the following libraries:

- /usr/lib/i386-linux-gnu/primus/libGL.so.1
- /usr/lib/x86_64-linux-gnu/primus/libGL.so.1

Later, i will generate a list of everything that i have installed related to steam and will update here.

**Comment by giulianisanches** [comment]
[video-packages.txt](https://github.com/ValveSoftware/steam-for-linux/files/520644/video-packages.txt)
![screenshot from 2016-10-10 21 03 47](https://cloud.githubusercontent.com/assets/81200/19254797/0491d242-8f2e-11e6-93f8-355e3cd137ab.png)

**Comment by giulianisanches** [comment]
So,

Reread the answer from @ProfessorKaos64 and got Steam working. I was missing the nvidia-driver-libs:i386.

Thank you very much!
