### ISSUE TITLE
Steam controller does not work over USB

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/steam-for-linux#4662]
I'm on the latest Steam stable build dated Oct 13th at 00:48:25 on Arch Linux. I had tried the beta a few days ago and ran into this same issue and reported it on the community forums (linked below) but got no response, and the issue has now been pushed to the stable client.

As described in the community thread below, since updating my system journal is filled with:

```
Oct 06 01:28:24 vashnix steam.desktop[1986]: controllerabstraction.cpp (560) : Assertion Failed: hid_get_feature_report returned false
Oct 06 01:28:24 vashnix steam.desktop[1986]: CGetControllerInfoWorkItem::RunFunc: Read failure.
Oct 06 01:28:25 vashnix steam.desktop[1986]: controllerabstraction.cpp (560) : Assertion Failed: hid_get_feature_report returned false
Oct 06 01:28:25 vashnix steam.desktop[1986]: CGetControllerInfoWorkItem::RunFunc: Read failure. 
```

The above was from the beta on October 6th, the messages on the current stable from October 13th are identical.
#### Steps for reproducing this issue:
1. Make sure Steam is up to date
2. Plug in a Steam controller
3. Attempt to use the Steam controller

More information here:
http://steamcommunity.com/groups/SteamClientBeta/discussions/0/350543951938736491/

**Comment by Plagman** [comment]
(note: maybe wired only)

**Comment by ilc** [comment]
I hit this issue, with Fedora 24, using the Steam Controller wired.

Wireless, it works properly.

**Comment by NathanWarden** [comment]
I thought it was my OS, but I've now tried it on Ubuntu 16.04, 16.10, and Solus and have the same problem. It works properly as a mouse until I start the Steam Client. Once the Steam Client starts the Controller ceases to function at all. It is also wired. Wireless works as expected.

**Comment by flypp** [comment]
Pretty same here. Steam controller only works via wireless dongle. When plugged directly to usb wire, steam picture see three dummy controllers. After a few seconds, the "input: Microsoft X-Box 360 pad as /devices/virtual/input/inputxxx" spam.

Using debian stretch 64 bits.

Loading/removing xpad, joydev and even xboxdrv modules won't fix the issue at all.

I am impress how this issue happened suddenly. No steam or system updates. It just stopped working from one day to another.

**Comment by her001** [comment]
This has been fixed for me in the latest Steam client beta.

**Comment by Vash63** [comment]
Closing, this has been fixed for a while and I forgot to close the bug.
