### ISSUE TITLE
Steam overlay is very slow when running on wayland

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4663]
#### Your system information

* Steam client version: Latest stable as of today
* Distribution (e.g. Ubuntu): Ubuntu Gnome 16.10 with wayland session
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
It seems the steam overlay is not optimized when running the desktop session trough wayland,
the mouse is slow and moving windows are slow too.

#### Steps for reproducing this issue:

1. Install ubuntu gnome 16.10
2. Run the wayland session
3. Run steam

**Comment by Plagman** [comment]
Please report this to the Wayland X compatibility folks instead, thanks.
