### ISSUE TITLE
segfault amdgpu-pro

### ISSUE THREAD

**Issue by mikel212** [ValveSoftware/steam-for-linux#4669]
#### Your system information
- Steam client version:
- Distribution (e.g. Ubuntu): arch
- Opted into Steam client beta?: [Yes/No]  yes
- Have you checked for system updates?: [Yes/No] yes

Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
crash_20161016164059_1.dmp[3129]: Uploading dump (out-of-process)
/tmp/dumps/crash_20161016164059_1.dmp
/home/kelo/.local/share/Steam/steam.sh: line 756:  3126 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20161016164059_1.dmp[3129]: Finished uploading minidump (out-of-process): success = yes
crash_20161016164059_1.dmp[3129]: response: CrashID=bp-2c5a6a88-fe30-4c8b-a7b4-3ea6b2161016
crash_20161016164059_1.dmp[3129]: file ''/tmp/dumps/crash_20161016164059_1.dmp'', upload yes: ''CrashID=bp-2c5a6a88-fe30-4c8b-a7b4-3ea6b2161016''

i've tried deleting and downloading steam again
#### Steps for reproducing this issue:
1. amdgpu-pro (rx-480)
2. launch steam
3.

**Comment by TowerRaven** [comment]
Chiming in to say I have this same issue, also on Arch (running the testing 4.8 kernel) on an R9 380. Using amdgpu-pro (as provided on the AUR). I also have the steam-native package but that has no effect.

    Running Steam on arch rolling 64-bit
    STEAM_RUNTIME is enabled automatically
    Installing breakpad exception handler for appid(steam)/version(0)
    crash_20161021110757_1.dmp[2511]: Uploading dump (out-of-process)
    /tmp/dumps/crash_20161021110757_1.dmp
    /home/tower/.local/share/Steam/steam.sh: line 756:  2508 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
    crash_20161021110757_1.dmp[2511]: Finished uploading minidump (out-of-process): success = yes
    crash_20161021110757_1.dmp[2511]: response: CrashID=bp-4e6f1793-74c4-4227-88cd-572f52161021
    crash_20161021110757_1.dmp[2511]: file ''/tmp/dumps/crash_20161021110757_1.dmp'', upload yes: ''CrashID=bp-4e6f1793-74c4-4227-88cd-572f52161021''

**Comment by kisak-valve** [comment]
Hello @mikel212, @TowerRaven, are either of you still experiencing this issue on an up to date system?

**Comment by mikel212** [comment]
old. switched to open source drivers haven't had that problem again.
