### ISSUE TITLE
Analog button considered pressed when not 0

### ISSUE THREAD

**Issue by LinAGKar** [ValveSoftware/steam-for-linux#4672]
When an axis is mapped to a face button in big picture mode, it will be considered as pressed when it is not 0. However, the analog axes for the face buttons on a PS3 controller are maximally negative when not pressed.

**Comment by kisak-valve** [comment]
Hello @LinAGKar, are you still experiencing this issue on an up to date system?

**Comment by LinAGKar** [comment]
The DS3 driver only provides the face buttons as digital buttons nowadays, same with the D-PAD and L1/R1. Only L2/R2 are still analog, and they seem to work fine in big picture.
