### ISSUE TITLE
Family mode code cannot be input with controller if it involves the d-pad.

### ISSUE THREAD

**Issue by victort** [ValveSoftware/steam-for-linux#4674]
#### Your system information
- Steam client version: latest
- Distribution (e.g. Ubuntu): SteamOS (pre-installed on Alienware Alpha)
- Opted into Steam client beta?: [Yes/No] Yes
- Have you checked for system updates?: [Yes/No] Yes
#### Please describe your issue in as much detail as possible:

If Parental Control Code has a 7, 8, 9, or 0, the d-pad on the steam controller will not input it. 
#### Steps for reproducing this issue:
1. set family mode code to 0987 (or some combination thereof)
2. opt to turn family mode off
3. With controller, attempt to input family mode code...
4. ...experience failure!

Unfortunate Workaround, 
Family mode Code can be input with keyboard.

**Comment by victort** [comment]
additionally, 
- The Steam Controller config has not been changed for big picture mode.
- The Steam Controller's d-pad works fine in every other context.
- The problem persists regardless of which (of my 4) Steam Controller is used.

**Comment by kisak-valve** [comment]
Hello @victort, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
