### ISSUE TITLE
"Install games" after purchasing does not work

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#4675]
#### Your system information
- Steam client version: october 20, 2016 version
- Distribution (e.g. Ubuntu): Ubuntu 16.04
- Opted into Steam client beta?: [Yes/No] no
- Have you checked for system updates?: [Yes/No] yes
#### Please describe your issue in as much detail as possible:

After purchasing a game, the "Install games" button does not work. Clicking on it does nothing but freeze the cursor to the pointy hand type for a few minutes inside the Steam window.
#### Steps for reproducing this issue:
1. Buy a game
2. Click "Install games"

**Comment by inliniac** [comment]
I saw the same on a fresh install. In my case it was related to 'keybase', a tool for managing gpg keys and such. It creates a special mount point using fusefs. Not sure why, but I noticed that on this system 'df -h' would hang as well. After killing keybase, the frozen steam immediately came to life and showed me the install steps. So maybe your case is related to keybase or a fusefs as well?

**Comment by kisak-valve** [comment]
Hello @vadi2, are you still experiencing this issue on an up to date system?

**Comment by vadi2** [comment]
I don't think so. Thanks for checking by!
