### ISSUE TITLE
[big picture] [overlay] seeing a steam profile from dota2 in overlay does not work the first time

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4676]
up-to-date steamOS beta and up-to-date client beta:

In dota2 profile screen, I need to click 2 times on seeing the steam profile in order to see the steam profile in the overlay.
(It's the same from dota2 store, when I want to pay in the overlay: the first time does not work)

**Comment by kisak-valve** [comment]
Hello @sylware, are you still experiencing this issue on an up to date system?

**Comment by sylware** [comment]
On Fri, Sep 20, 2019 at 08:59:14AM -0700, kisak-valve wrote:
> Hello @sylware, are you still experiencing this issue on an up to date system?

Hi

This bug is fixed. But I have a worst one now (I usually disable the overlay).
mouse events are going through the vulkan overlay into dota, it becomes tough
to interact with the overlay UI.
If you don't know of this bug, I'll update first my vulkan loader before
creating a new bug.

**Comment by sylware** [comment]
On Fri, Sep 20, 2019 at 04:58:29PM +0000, sylvain.bertrand@gmail.com wrote:
> If you don't know of this bug, I'll update first my vulkan loader before
> creating a new bug.

Forgot about GL. Tested the GL overlay, same issue.

**Comment by kisak-valve** [comment]
Thanks for retesting. You're most likely encountering #6506 with the followup issue.
