### ISSUE TITLE
Steam no longer starts on opensuse 13.2 ( /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64)

### ISSUE THREAD

**Issue by robbyb67** [ValveSoftware/steam-for-linux#4682]
#### Your system information

* Steam client version: 1.0.0.52
* Distribution (e.g. Ubuntu): opensuse 13.2
* Opted into Steam client beta?: No 
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:

** Thu Oct 27 19:40:42 2016
Starting '/opt/cxoffice/bin/wineloader' 'winewrapper.exe' '--wait-children' '--start' '--'
'C:/users/Public/Start Menu/Programs/Steam/Steam.lnk'

err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
Application tried to create a window, but no driver could be loaded.
Unknown error (127).
err:systray:initialize_systray Could not create tray window
fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:exec:SHELL_execute flags ignored: 0x00004100
err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
[2016-10-27 19:40:42] Startup - updater built Jan 25 2014 13:46:00
err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": /usr/lib/libX11.so.6: undefined symbol: xcb_poll_for_reply64
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f005ab0, 0x3f03ab30, 0x3f03ab28
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f005ab0, 0x3f03ab68, 0x3f03ab60
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f005ab0, 0x3f03aaf8, 0x3f03aaf0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f005ab0, 0x3f03aba0, 0x3f03ab98
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f005ab0, 0x3f03abd8, 0x3f03abd0
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
Application tried to create a window, but no driver could be loaded.
Unknown error (127).
main.cpp (456) : Assertion Failed: failed to initialize update status ui, or create initial window
Assert( Assertion Failed: failed to initialize update status ui, or create initial window ):main.cpp:456

fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub

#### Steps for reproducing this issue:

start steam from console

**Comment by gdrewb-valve** [comment]
Are you trying to launch the Windows version of Steam via wine?

**Comment by robbyb67** [comment]
Maybe. I've installed from opensuse build service http://download.opensuse.org/repositories/games:/tools/

**Comment by robbyb67** [comment]
That was the clue ! I've used the wrong steam starter after reorganizing my KDE desktop and had an old starter script in the PATH.
This issue can be closed. Sorry for inconvenience and thanks for help !

**Comment by gdrewb-valve** [comment]
Thanks, closing.
