### ISSUE TITLE
games fail to update on Steam beta client

### ISSUE THREAD

**Issue by rmbleeker** [ValveSoftware/steam-for-linux#4686]
#### Your system information

* Steam client version: beta update October 31
* Distribution (e.g. Ubuntu): Ubuntu 14.04 LTS kernel 4.4.0-45-generic
* Filesystem where Steam games are installed: XFS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When there was an update for ARK: Survival Evolved available it started downloading, but soon stopped again with a "disk write error" in the download manager. Verifying local game cache, restarting Steam and restarting my machine did not solve the issue. I then deleted the entire game and tried to download it again, with the same result.

After I opted out of the Steam Client beta the update resumed and finished normally.

#### Steps for reproducing this issue:

1. Opt-in to the Steam Client beta
2. Install a new game or update an existing one on an XFS filesystem
3. Download stops with a "disk write error", restarting will download a few KB but then stop again with the same error.
4. Opt-out of the Steam Client beta and updates resume as expected.

**Comment by rmbleeker** [comment]
I suspect this has something to do with this line from the update notes of the beta update for October 31st:

**Linux**
* Fixed issues when installing games into filesystems such as ZFS which report an abnormally large sector size

**Comment by rmbleeker** [comment]
I did some further testing. First I checked the disk and the file system, they are both okay. I then opted back in to the Steam Client beta and installed the game "Black Mesa" that I had bought during the Halloween sale but hadn't installed yet. After 3 or 4 attempts to put it back in the download queue again after it stopped I actually got it to download about 3.5GB of the 5.8GB total, but then it gave me the "disk write error" again. 

Opting out of the Steam Client beta again fixed it, so even if the issue can't be reproduced reliably at least the fix is reliable.

**Comment by alfred-valve** [comment]
Can you post a link to your content_log.txt file from this install please

**Comment by rmbleeker** [comment]
I've restarted a few times obviously so I hope the information in there is still useful.

https://gist.github.com/rmbleeker/dc4f33d26f2d90e051ab71a2f2fbb085

**Comment by rmbleeker** [comment]
For completion's sake I've also included the previous content log file (content_log.previous.txt)

https://gist.github.com/rmbleeker/d00d5a072b0dd8f2a5f7b1a32b1e48f8

**Comment by bootkiller** [comment]
Has the same issue with the recent CS:GO update, with btrfs filesystem.
I kept forcing the update and it eventually finished.

https://gist.github.com/bootkiller/b0546825d78127d420d294bc08476a9b

**Comment by sakuramboo** [comment]
Same here. I have 5 games that failed to update, Dota 2 (which I need working), Kerbal Space Program, Robocraft, Age of Wonders 3, and CS:GO.

**Comment by LiamDawe** [comment]
Ah good, thought this was just me.

I keep getting "disk write error" and I have to tell them to update multiple times before they decide to do it (ext4 the default file system for Ubuntu).

My content log: https://gist.github.com/LiamDawe/61fa738d1062d7ea71445bff3b46bcf0

**Comment by yochaigal** [comment]
I'm having the same issue on Arch 64bit with ext4 on an SSD. Sky Break and Hero Siege will not update; I don't get a disk I/O error; the download simply stops halfway through (and doesn't complete on subsequent retries).

**Comment by Plagman** [comment]
We're working on fixing the more general regression; if you need to update or download games you can either temporarily opt-out of the Beta or keep requeuing the download until it succeeds.

**Comment by israelsmith** [comment]
I am having the same issue on my Kubuntu 16.04 Linux install

Linux imperium 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz - 2 x GTX980 SLI - 32GB Ram - Hard drives are SSD (one is M.2)

**Comment by rmbleeker** [comment]
From the November 3 update notes for the beta client: 

Linux and Mac OS 
* Fixed disk error messages when downloading updates.

@Plagman: Does this fix this issue?

**Comment by Plagman** [comment]
Yes, it should. Some downloads might have gotten stuck in an 'update pending' state as a result of the "disk errors", but trying to run the game should let you proceed. Please let me know if the issue persists and I'll re-open.

**Comment by rmbleeker** [comment]
I've resubscribed to the beta and pulled down several updates so far without issues.

**Comment by betseg** [comment]
If you create the directory and file using `mkdir` and `touch` it won't give this error and update successfully.

**Comment by bootkiller** [comment]
> Yes, it should. Some downloads might have gotten stuck in an 'update pending' state as a result of the "disk errors", but trying to run the game should let you proceed. Please let me know if the issue persists and I'll re-open.

Been having this problem again.

[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/703169/content_log.txt)
