### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by virissokk** [ValveSoftware/steam-for-linux#4692]
#### Your system information

* Steam client version: latest
* Distribution (e.g. Ubuntu): ubuntu 16.10
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible: 
After launching displays here it is, and nothing else happens, I am sure you are aware of this problem, be it fixed a kind. For a long time watching this issue

STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1459463254)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast 

#### Steps for reproducing this issue:

1. Workaround Deleting library of Steam directory

Если вдруг вы можете ответить на Русском - отвечайте)

**Comment by gdrewb-valve** [comment]
Closing duplicate.
