### ISSUE TITLE
Steam crashes when editing any Steam Controller configuration

### ISSUE THREAD

**Issue by joaormatos** [ValveSoftware/steam-for-linux#4693]
#### System information
* Steam client version: Beta, Built: Nov 3 2016, at 20:53:55
* Distribution: Debian GNU/Linux testing (future "stretch")
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Issue description
Steam crashes after changing anything (even just a binding label) in any Steam Controller Configuration (including base configurations),

#### Steps for reproducing this issue
1. Open Big Picture
2. Open the Steam Controller configuration for the desktop
3. Rebind the "Start" button to the "F1" key
4. Steam goes back to the configuration overview screen
5. Steam crashes immediately

No new messages appear on the terminal at the time of the crash.

**Comment by Tele42** [comment]
Hello @joaormatos, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. It's helpful to Valve devs if any CrashIDs related to the issue is included when a crash is involved. You can also look in ```/tmp/dumps/<username>_stdout.txt``` for a related CrashID.

**Comment by joaormatos** [comment]
@Tele42
System information gist:
https://gist.github.com/joaormatos/8cd7a6f7b3c424ba19a3433d9718180a

I don't see any such file in /tmp/dumps/, only a bunch of .dmp files (Mini DuMP crash reports, according to file(1)) and steam_log.txt, the contents of which are included in the system information and contain a list of CrashIds.

**Comment by joaormatos** [comment]
This bug is still present in the beta client with build time "Nov 9 2016, at 23:06:06"

**Comment by joaormatos** [comment]
**I can not reproduce this bug when Steam is in offline mode.**
(In the latest beta client as per my previous comment.)

However, any changes to the configuration made in offline mode are lost when Steam goes back online.

This is probably an issue in the code that syncs controller configurations with the Steam cloud.

**Comment by joaormatos** [comment]
I can not reproduce this bug in the stable client.
(Built: Oct 13 2016, at 00:48:25)

However, changes done in offline mode are still lost.
(This probably merits a separate issue.)

**Comment by joaormatos** [comment]
Fixed in build "Nov 15 2016, at 00:32:34"
