### ISSUE TITLE
Steam Issue On 16.04 and 16.10

### ISSUE THREAD

**Issue by HavenSouth** [ValveSoftware/steam-for-linux#4696]
When ever i try to open steam on my Linux desktop computer it fails giving me an error saying Could not load module 'filesystem_stdio.so'. so i contacted steam support, they told me that if i did steam --reset it would reset my steam files and hopefully stop the problem but it didn't. Steam support later said they weren't very good with in depth linux crashes and to contact askubuntu and here for more help on the problem

this was the first time i used steam on this computer most the time i am on my windows laptop but my desktop is better for gaming so i switched to it and as soon as I tried to run steam for the first time  this happened

**Comment by gtsiros** [comment]
Valve needs to get with the times and release a runtime that works respectably and that does not recommend a FOUR VERSIONS OLDER (16->15->14->13->12) operating system.

Can you IMAGINE the shitstorm if they recommended windows XP (10->8->7->Vista->XP)?

**Comment by kisak-valve** [comment]
Hello @HavenSouth, are you still experiencing this issue on an up to date system? If you are, please describe how you installed steam and include either `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log` in this issue report?

**Comment by kisak-valve** [comment]
Closing pending feedback.
