### ISSUE TITLE
Steam store still showing Windows games even after selecting Linux/SteamOS as a preference

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/steam-for-linux#4697]
Currently: Dishonored2, COD Infinite Warfare and Skyrim, all games Windows only showing in the banner on Linux. 

I don't know if it is part of deals with the publishers that make the games but it definitely could lead to disappointment and confusion.

**Comment by doraskayo** [comment]
Indeed, very frustrating. This is the setting in question:

![](http://i.imgur.com/f4BrQWc.png "https://store.steampowered.com/account/preferences")

Which is located [here](https://store.steampowered.com/account/preferences).

**Comment by gdrewb-valve** [comment]
Mostly a duplicate of issues like #4500 / #4443 / #4448.

**Comment by shanefagan** [comment]
Well I thought it would need re-reporting given the store was updated specifically for filtering and discovery

**Comment by Tele42** [comment]
@shanefagan, although loosely enforced, intentionally creating duplicates of open issue reports is a violation of the [code of conduct](https://github.com/ValveSoftware/steam-for-linux#conduct) for this issue tracker as all it does is fragment the discussion of specific issues and adds unneeded moderation overhead. Commenting on the existing issue report gets to the same devs as opening a duplicate.

**Comment by shanefagan** [comment]
Ahh ok, normally in Ubuntu where I usually contribute they create new bugs if versions change because it might not be the same issue you are specifically running into.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? Please check your platform preferences set in Steam -> Settings -> View Account Details -> Preferences and scroll down to the platform preferences.

**Comment by shanefagan** [comment]
I haven't seen this in a while so I'd say it's fair enough to close.
