### ISSUE TITLE
Motorsport Manager has a SteamOS icon, version not actually planned until later

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4701]
The recently released Motorsport Manager has a SteamOS icon, so it is supposed to be playable right now.

However, it downloads nothing.

Does Steam do no checks when a game is released to ensure the Linux content is actually linked to store keys? It should.

Update: http://steamcommunity.com/app/415200/discussions/0/217690940939429422/?tscn=1478780559#c217691032428105786

They don't even plan Linux until later, please sort this mess out.

**Comment by Tele42** [comment]
Hello @LiamDawe, reach out to the game devs and let them know that they have forgotten to add Depot 415203 to Sub 83529. (Observed at https://steamdb.info/sub/83529/depots/ versus https://steamdb.info/sub/83528/)

**Comment by LiamDawe** [comment]
See here: http://steamcommunity.com/app/415200/discussions/0/217690940939429422/?tscn=1478780559#c217691032428105786

They don't even plan to add Linux/SteamOS until later, they outright shouldn't be allowed to have ever had the SteamOS icon.

False advertising, and as a customer and purchaser, I feel this is something Valve really need to solve to prevent frustrations.
