### ISSUE TITLE
Failed to save LED Color setting for PS4 Controller

### ISSUE THREAD

**Issue by supirman** [ValveSoftware/steam-for-linux#4702]
#### Your system information

* Steam client version:
Built Nov 9 2016, at 23:06:06
Steam API: v017
Steam package versions: 1478736940
Steam runtime version: steam-rutime-beta-release_2016-09-02
* Distribution : Ubuntu 16.04 ( Kernel Version:  4.4.0-45-generic )
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Try to modify LED Color setting but it can not be saved and now the LED is turned off. The LED color can be modified when in setting window but when it saved it turned off. And the setting can not keep the modification.

#### Steps for reproducing this issue:

1. Run Big Picture with PS4 Controller support Enabled
2. Open Controller Preferences
3. Modify the LED Color, Brightness and Saturation and Save. The LED will then turned off.
4. Reopen the Preference, the brigthness slider set in 0 even when was maxed.

**Comment by kisak-valve** [comment]
Closing in favor of #4790.
