### ISSUE TITLE
Dota 2 not updating

### ISSUE THREAD

**Issue by computerfr33k** [ValveSoftware/steam-for-linux#4704]
#### Your system information

* Steam client version: Built Nov 9 2016, at 23:06:06
* Steam API: v017
* Steam Package Versions: 1478736942
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I am unable to update Dota 2. When I validate local files it says they are all up to date, but steam does not think there is an update for Dota 2. But when I load Dota the game then pops up a message saying my client is out of date.

**Comment by gdrewb-valve** [comment]
This should be resolved, are you still having problems?

**Comment by computerfr33k** [comment]
Seems to be working now.
