### ISSUE TITLE
Steam client does not launch

### ISSUE THREAD

**Issue by alexandrpaliy** [ValveSoftware/steam-for-linux#4705]
* Steam client version: [system information](https://gist.github.com/alexandrpaliy/5046ca26db17609d746cc6c9371d4c59)
![steam client version](http://i.imgur.com/2sLoki2.png)
* Distribution: Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

I have troubles starting my steam client. It crashes. Here is an example of many cases: [log](https://gist.github.com/alexandrpaliy/4e2a38f14bcf1be8dc686f2fcad5b562)
Anyway, I can easily launch client by doing it after `rm -rf ~/.steam`. Yes, I will need to log in again, but at least I can use steam that way.

In log, I can see that line:
```
[1110/201633:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
[1110/201633:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
...
[1110/201633:ERROR:main_delegate.cc(779)] Could not load cef_extensions.pak
```

But how can everything work at the first launch then?

**Comment by alexandrpaliy** [comment]
For some reason, last 1-2 days I did not experience this. Right now I was able to start Steam without any problems, without removing `~/.steam` and without logging in again.

**Comment by alexandrpaliy** [comment]
I don't face this issue for a long time already.
Steam always starts, it takes long time and sometimes logs me off - but that can be a reason for another issue.
Thss issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
