### ISSUE TITLE
Incompatible version of liggpg-error.so.0 with MESA 12

### ISSUE THREAD

**Issue by megian** [ValveSoftware/steam-for-linux#4706]
#### Your system information

* Steam client version: 1474415843
* Distribution (e.g. Ubuntu): Debian SID
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I'm running Debian Linux amd64 SID, which the i386 libraries installed. It seams an issue with the newest MESA libraries version 12.

gabriel@andromeda:~$ uname -r
4.8.0-1-amd64

gabriel@andromeda:~/.steam$ LIBGL_DEBUG=verbose steam
Running Steam on debian 64-bit
STEAM_RUNTIME is enabled automatically
[2016-11-06 14:48:41] Startup - updater built Sep 20 2016 18:20:24
SteamUpdateUI: An X Error occurred
X Error of failed request: BadValue (integer parameter out of range for operation)
^C

The steam error.log did contain:
gabriel@andromeda:~/.steam$ cat error.log-2
/home/gabriel/.steam/steam.sh: Zeile 154: VERSION_ID ist nicht gesetzt.
rm: das Entfernen von '/home/gabriel/.steam/steam' ist nicht möglich: Ist ein Verzeichnis
rm: das Entfernen von '/home/gabriel/.steam/bin' ist nicht möglich: Ist ein Verzeichnis
/home/gabriel/.steam/steam.sh: Zeile 154: VERSION_ID ist nicht gesetzt.
/home/gabriel/.steam/steam.sh: Zeile 154: VERSION_ID ist nicht gesetzt.
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1474415843)
libGL: Can't open configuration file /home/gabriel/.drirc: Datei oder Verzeichnis nicht gefunden.
libGL: pci id for fd 7: 8086:0412, driver i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/i965_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/i965_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/i965_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/i965_dri.so
libGL: dlopen ${ORIGIN}/dri/i965_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying /usr/lib/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/dri/i965_dri.so
libGL: dlopen /usr/lib/dri/i965_dri.so failed (/usr/lib/dri/i965_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: pci id for fd 7: 8086:0412, driver i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/i965_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/i965_dri.so failed (**/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference**)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/i965_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/i965_dri.so
libGL: dlopen ${ORIGIN}/dri/i965_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying /usr/lib/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib/dri/i965_dri.so
libGL: dlopen /usr/lib/dri/i965_dri.so failed (/usr/lib/dri/i965_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/i386-linux-gnu/dri/swrast_dri.so
libGL: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying ${ORIGIN}/dri/tls/swrast_dri.so
libGL: OpenDriver: trying ${ORIGIN}/dri/swrast_dri.so
libGL: dlopen ${ORIGIN}/dri/swrast_dri.so failed (/lib/i386-linux-gnu/libgcrypt.so.20: symbol gpgrt_lock_lock, version GPG_ERROR_1.0 not defined in file libgpg-error.so.0 with link time reference)
libGL: OpenDriver: trying /usr/lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/dri/swrast_dri.so
libGL: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Removing the the liggpg-error.so.0 from the STEAM RUNTIME libraries and using the system libraries did resolve the error.**

mv ./steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgpg-error.so.0 ./steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgpg-error.so.0.bak
gabriel@andromeda:~/.steam$ mv ./steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0 ./steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0.bak

gabriel@andromeda:~/.steam$ dpkg -S /usr/lib/i386-linux-gnu/dri/i965_dri.so
libgl1-mesa-dri:i386: /usr/lib/i386-linux-gnu/dri/i965_dri.so

gabriel@andromeda:~/.steam$ dpkg -s libgl1-mesa-dri:i386
Package: libgl1-mesa-dri
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 118878
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Architecture: i386
Multi-Arch: same
Source: mesa
Version: 12.0.3-3
Depends: libc6 (>= 2.17), libdrm-amdgpu1 (>= 2.4.63), libdrm-intel1 (>= 2.4.48), libdrm-nouveau2 (>= 2.4.66), libdrm-radeon1 (>= 2.4.31), libdrm2 (>= 2.4.66), libelf1 (>= 0.142), libexpat1 (>= 2.0.1), libgcc1 (>= 1:3.4), libgcrypt20 (>= 1.7.0), libllvm3.8, libstdc++6 (>= 5.2)
Recommends: libtxc-dxtn-s2tc | libtxc-dxtn-s2tc0 | libtxc-dxtn0
Breaks: xserver-xorg-core (<< 2:1.14.3-5)
Conffiles:
/etc/drirc d279cb60294ad49d90803416a310683e
Description: free implementation of the OpenGL API -- DRI modules
This version of Mesa provides GLX and DRI capabilities: it is capable of
both direct and indirect rendering. For direct rendering, it can use DRI
modules from the libgl1-mesa-dri package to accelerate drawing.
.
This package does not include the OpenGL library itself, only the DRI
modules for accelerating direct rendering.
.
For a complete description of Mesa, please look at the
libgl1-mesa-glx package.
Homepage: http://mesa3d.org/

gabriel@andromeda:~/.steam$ ldd /lib/i386-linux-gnu/libgcrypt.so.20
linux-gate.so.1 (0xf770f000)
libgpg-error.so.0 => /lib/i386-linux-gnu/libgpg-error.so.0 (0xf75ef000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7438000)
/lib/ld-linux.so.2 (0x56645000)

gabriel@andromeda:~/.steam$ dpkg -S /lib/i386-linux-gnu/libgpg-error.so.0
libgpg-error0:i386: /lib/i386-linux-gnu/libgpg-error.so.0

gabriel@andromeda:~/.steam$ dpkg -s libgpg-error0:i386
Package: libgpg-error0
Status: install ok installed
Priority: standard
Section: libs
Installed-Size: 573
Maintainer: Debian GnuPG Maintainers <pkg-gnupg-maint@lists.alioth.debian.org>
Architecture: i386
Multi-Arch: same
Source: libgpg-error
Version: 1.24-1
Depends: libc6 (>= 2.15)
Description: library for common error values and messages in GnuPG components
Library that defines common error values for all GnuPG
components. Among these are GPG, GPGSM, GPGME, GPG-Agent, libgcrypt,
pinentry, SmartCard Daemon and possibly more in the future.
Homepage: https://www.gnupg.org/related_software/libgpg-error/

Please provide a newer version or remove the library from the STEAM RUNTIME.

**Comment by Tele42** [comment]
Hello @megian, looking at the changelog for Debian SID's steam package (http://metadata.ftp-master.debian.org/changelogs/non-free/s/steam/steam_1.0.0.52-5_changelog), this appears to have been resolved for your distro with the steam-1.0.0.52-3. Are you sure you are using the steam package maintained for your distro?

**Comment by megian** [comment]
You have been right. My version was outdated, because I did no longer 
had the non-free packages source in my sources.list.

Updated steam:i386 (1.0.0.51-1) to (1.0.0.52-5)

Seams to work fine.

**Comment by gdrewb-valve** [comment]
@megian if there's no active issue can you close this?

**Comment by megian** [comment]
Incident closed
