### ISSUE TITLE
Libexo - undefined reference when starting SteamVR

### ISSUE THREAD

**Issue by mungewell** [ValveSoftware/steam-for-linux#4707]
#### Your system information

* Steam client version: steam-launcher                         1.0.0.53
* Distribution (e.g. Ubuntu): Xubuntu, xenial
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When starting SteamVR it pops up window and then closes, console where Steam was launched reports. Expected to see the SteamVR console (as I do on Win64).

    /bin/bash: /home/simon/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
    exo-open: symbol lookup error: /usr/lib/x86_64-linux-gnu/libexo-1.so.0: undefined symbol: g_type_check_instance_is_fundamentally_a

    $ objdump -T /usr/lib/x86_64-linux-gnu/libexo-1.so.0
    ...
    0000000000000000      DF *UND*      0000000000000000  GLIBC_2.2.5 strlen
    0000000000000000      DF *UND*      0000000000000000              g_type_check_instance_is_fundamentally_a

#### Steps for reproducing this issue:

1. Start Steam from console
2. Launch SteamVR util
3. Observe error message

**Comment by gdrewb-valve** [comment]
Likely another instance of Steam runtime compatibility problems.

**Comment by kisak-valve** [comment]
Hello @mungewell, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
