### ISSUE TITLE
libgl1:i386 and libGL.so.1 Error

### ISSUE THREAD

**Issue by EmreOvunc** [ValveSoftware/steam-for-linux#4710]
#### Your system information

* Steam client version: I downloaded from (media.steampowered.com/client/installer/steam.deb)
* Distribution (e.g. Ubuntu): Debian 8 x64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I installed steam by using these steps;

```
    Download the steam.deb package from this location.
    Open a graphical file manager (for Ubuntu 12.04, click the folder icon on the Unity Launch bar).
    Navigate to the directory containing steam.deb and double-click it. This launches Ubuntu Software Center and installs the package.
    If you prefer to install from the command-line, use gdebi. Install the gdebi-core package (apt-get install gdebi-core) and then install the Steam for Linux package (gdebi steam.deb).

```

When I write "steam" to run from terminal , I get an error;

```
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Package libc6:i386 needs to be installed
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
[2016-11-18 17:33:29] Startup - updater built Oct 13 2016 00:47:16
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-11-18 17:33:29] Checking for update on startup
[2016-11-18 17:33:29] Checking for available updates...
[2016-11-18 17:33:31] Shutdown
[2016-11-18 17:33:31] Error: Download failed: http error 0
[2016-11-18 17:33:31] Verifying installation...
[2016-11-18 17:33:31] Performing checksum verification of executable files
[2016-11-18 17:33:31] Verification complete

```

> apt-get install libgl1-mesa-dri:i386

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libllvm3.5:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

> uname -a

`Linux PC 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

**Comment by ProfessorKaos64** [comment]
Debian provides it's own `steam` package.

https://packages.debian.org/search?keywords=steam

**Comment by EmreOvunc** [comment]
It gives same error.

**Comment by ProfessorKaos64** [comment]
You can either drill down the dependency list trying to find out why "it is not going to be installed," with `apt-get install` or `apt-get policy` or ensure your sources are right. Are you sure you have [multiarch](https://wiki.debian.org/Multiarch/HOWTO) enabled?

**Comment by EmreOvunc** [comment]
Yes , I'm sure to multiarch enabled (https://wiki.debian.org/Multiarch/HOWTO)

>  dpkg --print-architecture 

`amd64`

> dpkg --print-foreign-architectures 

`i386`

> cat /etc/apt/source.list

```
deb [arch=amd64,i386] http://ftp.tr.debian.org/debian/ jessie main
deb-src http://ftp.tr.debian.org/debian/ jessie main

deb [arch=amd64,i386] http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb [arch=amd64,i386] http://ftp.tr.debian.org/debian/ jessie-updates main
deb-src http://ftp.tr.debian.org/debian/ jessie-updates main

deb [arch=amd64,i386] http://httpredir.debian.org/debian jessie-backports main contrib non-free
deb [arch=amd64,i386] ftp://ftp.debian.org/debian stable main contrib non-free
```

> apt-get install steam

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by alexandrpaliy** [comment]
```
libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libllvm3.5:i386 but it is not going to be installed
```
If you try to install those packages by yourself, why can't they be installed?

**Comment by EmreOvunc** [comment]
They can be installed buy steam gives same error. 
I downloaded from https://packages.debian.org/jessie/i386/libgl1-mesa-glx and copied to current directories.

> steam

```
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Package libc6:i386 needs to be installed
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libglapi.so.0
libxshmfence.so.1
libdrm.so.2
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
Installing breakpad exception handler for appid(steam)/version(1476379980)
[2016-11-20 00:05:26] Startup - updater built Oct 13 2016 00:47:16
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2016-11-20 00:05:26] Checking for update on startup
[2016-11-20 00:05:26] Checking for available updates...
[2016-11-20 00:05:27] Download skipped: /client/steam_client_ubuntu12 version 1476379980, installed version 1476379980
[2016-11-20 00:05:27] Nothing to do
[2016-11-20 00:05:27] Verifying installation...
[2016-11-20 00:05:27] Performing checksum verification of executable files
[2016-11-20 00:05:27] Verification complete
[2016-11-20 00:05:28] Shutdown

```

**Comment by gdrewb-valve** [comment]
Can you clarify what you think the Steam issue is?

**Comment by Tele42** [comment]
@EmreOvunc, just so it's clear. Steam is trying to tell you you do not have a sane 32 bit opengl implementation installed. You need to add that to your system in order to use steam.

**Comment by EmreOvunc** [comment]
@Tele42 I already installed 32-bit library by using "dpkg --add-architecture i386". 
Last week, I was using steam with my Ubuntu, but I change my operating system to Debian and it does not work now.

**Comment by mewtikz** [comment]
Hey!  Come look at this reddit thread about installing steam on Linux, because you may have missed a step that's been written:

https://www.reddit.com/r/GlobalOffensiveLinux/comments/5cmogn/csgo_tweaks_sticky/d9y0iym/

**Comment by EmreOvunc** [comment]
Finally, I solved this problem and I tried almost everything to install steam on the internet.
It's just about libdrm-intel1 library.
Solution that error for debian users is:
```
The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

> 1. Open "Synaptic Package Manager"
> 2. Search "libdrm-intel1
> 3. Right click to downgrade its version to stable one.
> 4. Then run steam from the command line.
> 5. Steam wants to install missing packages& libraries, press "Y" to install them.

I think that some packages or libraries use non-stable version and that causes some installation error like Steam. 
Thanks for advices.

**Comment by KiengKnot** [comment]
I recently face the same issue.

```
Package libgl1-mesa-dri:i386 needs to be installed
Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1496897923)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
```
Then, I try to install 
`sudo apt-get install libgl1-mesa-dri:i386`
But It failed
```
The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libgcrypt20:i386 (>= 1.7.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Then, I tried to install `libgcrypt20:i386`, but failed. I lose the error log. However, If can't install `libgcrypt20:i386` like me. It likely to be the same issue.

**Solution**
I manually download `libgcrypt20 (1.7.8-2)` both amd64 and i368 (multiarch) from [https://packages.debian.org/sid/libgcrypt20](https://packages.debian.org/sid/libgcrypt20)

1. Install the deb files (amd64 and i386) using dpkg.
2. `sudo apt-get install -f`
3. `sudo apt-get install libgl1-mesa-dri:i386`

Now, it works, I can install `libgl1-mesa-dri:i386` on my Debian Stretch recently updated from Jessie
Then I can run the installed steam that I downloaded from steam official website.

**Comment by ChristopherMcCown** [comment]
I installed on Kubuntu 16.04 LTS apt command line and get the same error when I try to start it.

When I run the installed binary from the menu it tells me:
_you are missing the following 32-bit libraries libgl.so.1_

Why are you guys not compiling 64 bit?  No gamers use 32 bit Raspberry PIs.  I'm pretty sure you can compile all OSes with appropriate libraries using Gitian 32 and 64 bit versions.

**Comment by kisak-valve** [comment]
Closing because the original issue was a system config issue and resolved.
