### ISSUE TITLE
[beta] Streaming video player not working in Steam client beta on Linux

### ISSUE THREAD

**Issue by rmbleeker** [ValveSoftware/steam-for-linux#4713]
I've reported this before on the [Steam community page for Con Man](http://steamcommunity.com/app/549290/discussions/0/217691032441752811/) but since there was no reply to that thread I thought I'd report it again here.

#### System information:

* Steam client version: 1479769971
* Distribution (e.g. Ubuntu): Ubuntu 14.04 LTS
* Opted into Steam client beta?: Yes 
* Have you checked for system updates?: Yes

#### Description of the issue:
I recently bought Season 1 of [Con Man](http://store.steampowered.com/app/549290/) on Steam. When trying to watch it while opted in to the Steam client beta the videos don't play. The player doesn't even start or perhaps crashes right after starting. When starting Steam from a console I get the following output:
```
Game update: AppID 549320 "Con Man: Stalled", ProcID 11501, IP 0.0.0.0:0
>>> Adding process 11501 for game ID 549320
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxxxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 11502 for game ID 549320
>>> Adding process 11503 for game ID 549320
>>> Adding process 11504 for game ID 549320
>>> Adding process 11505 for game ID 549320
../../common/steam/client_api.cpp (454) : Assertion Failed: ClientAPI_Init: InternalAPI_Init_Internal failed.

Failed to connect to SteamGame removed: AppID 549320 "Con Man: Stalled", ProcID 11501 
No cached sticky mapping in ActivateActionSet.
```
I've checked with other (free) streaming videos on Steam like the [Mortal Kombat: Legacy](http://store.steampowered.com/app/361700/) series or [PAYDAY: The Web Series](http://store.steampowered.com/app/354500/) and the show the same behaviour.

#### Steps for reproducing this issue:

1. Opt in to the Steam for Linux client beta
2. Go to the **videos** section of your library
3. Click on any video in an attempt to play it and watch nothing happen

**Comment by Tele42** [comment]
This should be fixed per the [2016-11-22 steam beta](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/599372277797190674) update notes.

**Comment by rmbleeker** [comment]
Tested with the latest beta and I can confirm that the player now starts. However when trying to watch Con Man it first tells me: "Retrieving additional components required for playback. This is a one-time process that may take a few minutes to complete." After about 3 or 4 minutes I'm being told: "The additional components required for playback could not be retrieved. Please restart the video to try again." I've tried this 3 times now to no avail. 

I assume it's some sort of DRM component that can't be retrieved/installed, since other videos like [Free to Play](http://store.steampowered.com/app/245550/), [Kung Fury](http://store.steampowered.com/app/374570/) or the [PAYDAY Web Series](http://store.steampowered.com/app/354500/) work just fine now.

**Comment by Tele42** [comment]
Looks like Wildvine protected video playback has been fixed in the [2016-11-28](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/599372277819234842) steam beta update.

Are you still experiencing an issue with the update from today?

**Comment by rmbleeker** [comment]
The Widevine update seems to have fixed the issue, the Con Man videos play again without issues.
