### ISSUE TITLE
[beta] Steam controller no longer recognized 

### ISSUE THREAD

**Issue by lktaylor49** [ValveSoftware/steam-for-linux#4716]
#### Your system information

* Steam client version: 1479865477
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After the update on 11/22, controller is no longer detected. I tried adding it again as new, but there is no response when starting the controller while holding X.

#### Steps for reproducing this issue:

1. Update to beta build from 11/22

![sysinfo](https://cloud.githubusercontent.com/assets/23709023/20580828/cf0fd3d4-b1a2-11e6-94e5-e846535f558d.png)

**Comment by Alan-James** [comment]
I just posted a duplicate issue. Glad it's not just me.

**Comment by Tele42** [comment]
Hello @lktaylor49 and @Alan-James, please adjust your udev rule to conform to http://steamcommunity.com/app/353370/discussions/0/490123197956024380/, then reload the udev rules or reboot.

**Comment by Alan-James** [comment]
Thanks Tele42, adding these two rules did the trick

# Valve HID devices over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="28de", MODE="0666"

# Valve HID devices over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*28DE:*", MODE="0666"

**Comment by lktaylor49** [comment]
Yup, that did it. Thanks!
