### ISSUE TITLE
In the i3 tiling WM, you can't select other games after moving the steam window to another workspace

### ISSUE THREAD

**Issue by Majora320** [ValveSoftware/steam-for-linux#4718]
In the latest versions of Steam & i3 on Arch Linux, once you move the steam window to another workspace you can't select more than the game you previously had selected, or the client move the selection "indicator" to cover all of the games between the one you had previously and the once you are trying to select:
![Steam bugging out](https://cloud.githubusercontent.com/assets/16787503/20582613/7e740d60-b197-11e6-909a-9756ffae4706.png)
It works normally when selecting the game you had selected earlier.
This behaviour persists even after moving the steam window back again.

I have tested this over several system, driver, kernel and steam versions and it has acted the same every time.

**Comment by Tele42** [comment]
Hello @Majora320, this is commonly seen when steam is given a keydown event for one of the modifier keys, but not the corresponding keyup event. Press your alt, control, and/or shift keys get steam to release the modifier key.

**Comment by Majora320** [comment]
@Tele42 Correct, the problem seems to have been with the Steam client recieving the super key for "begin move", but i3 intercepting the workspace number. Thanks!
