### ISSUE TITLE
403 Forbidden when downloading Steam client for Linux

### ISSUE THREAD

**Issue by predr** [ValveSoftware/steam-for-linux#4719]
#### Steps for reproducing this issue:

1. Go to Steam website http://store.steampowered.com/about/
2. Try to download Steam client while on Linux
3. Get You don't have permission to access /steam/archive/precise/steam_latest.deb on this server.

There was an update to 1.0.0.54 yesterday so it has something to do with that.

**Comment by Tele42** [comment]
Hello @predr, you can also get the steam client from http://repo.steampowered.com/steam/pool/steam/s/steam/. However, unless you have a problem which is fixed by the new steam package version, you should be using the steam package provided by your distro's package manager.

**Comment by predr** [comment]
Hi @tele42, I don't have a problem but people trying to download Steam from website do.

![download](https://cloud.githubusercontent.com/assets/17696117/20608655/0128e3c4-b284-11e6-9a3d-6bc5fd10344e.gif)

**Comment by xmwx38** [comment]
Ahh.. Experiencing the same situation here.  I was able to install from this link: [steam-launcher_1.0.0.48_all](http://repo.steampowered.com/steam/pool/steam/s/steam/steam-launcher_1.0.0.48_all.deb)

**Comment by k0pernikus** [comment]
@xmwx38 How did you figure out that link?

**Comment by predr** [comment]
This happened before several times #3465

**Comment by predr** [comment]
It's working now, closing this issue.
