### ISSUE TITLE
Failed to install/launch client

### ISSUE THREAD

**Issue by greyscaleroses17** [ValveSoftware/steam-for-linux#4720]
#### Your system information

* Steam client version: Base version
* Distribution (e.g. Ubuntu): Linux mint 18
* Opted into Steam client beta?: Didn't make it that far
* Have you checked for system updates?: No, but new version is on it's way

#### Please describe your issue in as much detail as possible:
Tried to install steam via http://archive.ubuntu.com/ubuntu xenial/multiverse i386 steam i386 1:1.0.0.48-1ubuntu3
This is what seemed to go wrong first V
https://gist.github.com/greyscaleroses17/88c01d7687e14c86632ab5480fd3f040

#### Steps for reproducing this issue:

1. sudo apt install steam
2. there you go
3. Thanks :)

**Comment by Tele42** [comment]
Hello @greyscaleroses17, does running ```steam --reset``` from a terminal help?

**Comment by greyscaleroses17** [comment]
"Can't find boot strap" in a window.

**Comment by greyscaleroses17** [comment]
I am running a nvidia gtx 550ti 2mb, an intel e8400, have 4.9 1044mhz ddr3 RAM on an intel motherboard, atx 2.x if that helps at all.

**Comment by kisak-valve** [comment]
Hello @greyscaleroses17, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
