### ISSUE TITLE
Scrolling the store window with mouse wheel flips too much

### ISSUE THREAD

**Issue by linweilian03** [ValveSoftware/steam-for-linux#4722]
Scrolling the store page (or other pages) with mouse wheel flips about 15 lines. Flipping 15 lines is too much. 5 lines or 3 lines should be better.

My system information
* Steam client version: the newest version in oct 13
* Distribution (e.g. Ubuntu):  ubuntu 16.04 lts
* Have you checked for system updates?: Yes

It is related to https://github.com/ValveSoftware/steam-for-linux/issues/2910

**Comment by Chiitoo** [comment]
As a reply to @Ragmaanir in 'Incorrect scolling behavior in Linux client. #4644':

> for me this scrolling behavior is everywhere (store, community, library/tools, friends list). The store is just the most annoying and important part. I dont know, but i guess the issue is more general than the store-page issue and that there is/might be a general solution.

Indeed, it happens all over the place.

An interesting(?) thing I noticed, is that Steam seems to ignore the user settings in the Windows build as well, while running it via Wine.  To be a bit more specific, for me the Windows build scrolls about four (4) lines, while the Linux build scrolls about nine (9) lines (tested on the hardware & software survey section).

I can set the scrolling to 0 lines, and I get no scrolling in, for example, the Falkon web-browser, but Steam still does what it does.

Tested on Gentoo Linux mainly with LXQt, and somewhat with Xfce4.

According to a friend of mine, it's a little bit funky in a native Windows environment as well, where having the Windows setting at 2 lines will scroll 4 lines, and 3 will scroll 9 lines.

**Comment by Thraix** [comment]
Is there any new on this topic? The issue has been opened since Nov 25, 2016, and is a huge annoyance when browsing anything related to the steam client. I'm actually going out of my way not to use the client as much as possible since the scroll is so horrendous.

**Comment by zjeffer** [comment]
@gdrewb-valve This is still an issue, any progress on this?

**Comment by kisak-valve** [comment]
Hello @zjeffer, Opt into Steam's beta client (https://github.com/ValveSoftware/steam-for-linux/issues/4644#issuecomment-442668092).

**Comment by kisak-valve** [comment]
Closing per "Fixed incorrect mouse wheel scrolling offsets" in the [2019-02-01](https://store.steampowered.com/news/48091/) Steam client update.
