### ISSUE TITLE
When starting an install on a remote machine from the phone app, Steam does not respect the default library folder.

### ISSUE THREAD

**Issue by rbutcher** [ValveSoftware/steam-for-linux#4723]
#### Your system information
* Steam client version:
    * Windows Client
        * API: v017
        * Package Versions: 1476379980
    * Android Client
        * 2.1.6

* Distribution (e.g. Ubuntu): 
    * Windows 10 (OSVersion 14393.447)
    * Android 5.1.1 (Kernel 3.10.49)

* Opted into Steam client beta?: [Yes/No] 
    * No

* Have you checked for system updates?: [Yes/No]
    * No, that won't help.

#### Please describe your issue in as much detail as possible:
After purchasing some games from my mobile yesterday (11/24/2016), I went to my games list on the mobile and had it trigger a remote install on my desktop. On my desktop I have 2 drives C:\ and M:\\. C is an SSD with very little disk space, M is a large HDD with tons of available disk space. I have steam installed on C but setup a install library folder that is set to default on M. The remote install started installing on C instead of M. Remote installs should respect the default library folder.

#### Steam Library Folder settings
![image](https://cloud.githubusercontent.com/assets/7253688/20629097/b68d255e-b2f7-11e6-97e4-d3bd85df56dd.png)
Note: the 1 installed item on C:\Program Files (x86)\Steam is another application that did this but was too small for me to notice it. I always install on M: for obvious reason you can see in this picture.

#### Steps for reproducing this issue:
Preconditions:
* Steam is setup on a desktop machine with its core install directory on one drive and the default game install directory on another drive.
* Steam is logged in on both the mobile app and the desktop

1. On the mobile app, open the hamburger menu and select library.
    * Upon loading, the mobile app shows that you are logged in on the split install desktop machine.
2. Tap the download button
    * The application will show the download running
3. Go to the desktop machine and observe the download has been started on the wrong library folder (the core steam install folder not the default one)

**Comment by rbutcher** [comment]
This may have not been the place for this. Sorry, I followed a link from the internet to get here and then didn't check the name of the repo. If you could let me know where to put this kind of stuff it would be helpful. Its not an easy thing to figure out.

**Comment by gdrewb-valve** [comment]
You can post at steamcommunity.com or you can open a support ticket at support.steampowered.com.  This'll stay open for a bit but as you mention it's not really the right audience and will get closed at some point.
