### ISSUE TITLE
Steam and Optirun

### ISSUE THREAD

**Issue by EmreOvunc** [ValveSoftware/steam-for-linux#4724]
Hi all, I want to play my games by using optirun to run them with my external graphic card.
I change "Set Launch Options" but it doesn't work for me.  How can I do ?

> System: Ubuntu 16.04
> Graphic Card: GTX870M

In addition, my games are running smoothly on integrated graphic card.
 
I wrote "Set Launch Options many things to run:
```
LD_PRELOAD="libpthread.so.0 libGL.so.1" __GL_THREADED_OPTIMIZATIONS=1 optirun %command%

vblank_mode=0 optirun %command%

optirun %command%

primusrun %command%
```

**Comment by gdrewb-valve** [comment]
What happens when you use the launch options?

**Comment by EmreOvunc** [comment]
Actually nothing, when I press the play button, steam displays near the game header "Running" but after 1-2 seconds running header goes away and game is not running. Also, there is no error messages on the screen.

**Comment by gdrewb-valve** [comment]
If you run Steam from a terminal do you get any interesting spew in the terminal window?

**Comment by EmreOvunc** [comment]
> optirun steam

```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2016-11-27 21:19:28] Startup - updater built Oct 13 2016 00:47:16
[2016-11-27 21:19:28] Verifying installation...
[2016-11-27 21:19:28] Verification complete
```

and gives me an error.
![error](https://cloud.githubusercontent.com/assets/15659223/20650762/29615008-b4df-11e6-8159-2dd968812aba.png)

**Comment by gdrewb-valve** [comment]
There are several open issues and several closed issues with steamui load errors, you might want to check them to see if any apply.

**Comment by EmreOvunc** [comment]
yep I know that there are many issues with steamui.so load error but my problem is going on. I added i386 lib with "dpkg --add-architecture i386"

**Comment by kisak-valve** [comment]
Hello @EmreOvunc, are you still experiencing this issue on an up to date system?

**Comment by EmreOvunc** [comment]
It's been three years, I can't re-test .
