### ISSUE TITLE
Steam-native runtime error, can't launch (initial launch) on Arch Linux 64-bit

### ISSUE THREAD

**Issue by Relsre** [ValveSoftware/steam-for-linux#4726]
#### Your system information

* Steam client version: steam-native 1.0.0.52-8
* Distribution (e.g. Ubuntu): Arch Linux 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Upon running "steam-native" in the terminal, the Steam 'updating' window briefly pops up, doesn't get past the 'Verifying Installation' stage and exits with a series of errors ([GitHub Gist here](https://gist.github.com/Relsre/23899b82b7210901eaee30e46acd79a5)). I've installed the necessary NVIDIA proprietary drivers (am using a GTX 780, which requires the 'nvidia', 'nvidia-libgl' and 'lib32-nvidia-libgl' packages), xorg-server and its utilities, and also the steam and steam-native-runtime packages from the Arch Linux repositories; I'm not sure what is going wrong.

If it matters, running "steam" instead of "steam-native" also outputs a similar set of error messages. Let me know if you need more information.

**UPDATE:** I've resolved most of the 'X error' messages by switching my monitor colour depth from 16-bit to 24-bit. There are still some errors, however: [updated GitHub Gist](https://gist.github.com/Relsre/095dff18f41c7bf05a60a329a46198d4)

**UPDATE WITH SOLUTION**: I've figured out that it was actually an issue with my system locale, it was set to a version of English that was not supported by Steam. Changing my locale to en_US.UTF-8 fixed the issue. Thanks all for your help.

#### Steps for reproducing this issue:

1. Install Arch Linux 64-bit
2. Install the aformentioned proprietary NVIDIA drivers, xorg-server (and whatever DE/WM and DM you desire), 'steam' and 'steam-native-runtime'
3. Execute 'steam-native' on the command line/terminal

**Comment by gdrewb-valve** [comment]
There's no support for steam-native here but your regular Steam runtime issues are likely the same compatibility problems for which there are many open issues here.

**Comment by Relsre** [comment]
@gdrewb-valve I see; to clarify, all the error messages aside from the 'Gtk-WARNING' messages are present when running 'steam' instead of 'steam-native'. I've looked around the Issues posts, and can't seem to find others with the issue I have. More importantly, I'm not sure what exactly is the compatability issue I'm having here -- any clues as to what it may be, looking at the error messages?

**Comment by Tele42** [comment]
Hello @Relsre,
I interpret the X errors as a high probability (not definitive) that you do not have a sane 32 bit opengl implementation. Do you have some way to test this outside of steam? Does the running version of the nvidia kernel module, 64 bit, and 32 bit userspaces match?

**Comment by Relsre** [comment]
@Tele42 If you're referring to the intial GitHub gist, I've resolved most of the errors by changing my monitor colour depth (as mentioned in the UPDATE). I don't know of a way to test this other than using a (supposedly) 32-bit OpenGL game, unfortunately.

Checking via `pacman -Qs nvidia`, I know that all three running versions (`nvidia`, `nvidia-libgl`, `lib32-nvidia-libgl`) are at 375.20-1.

**Comment by Relsre** [comment]
**UPDATE WITH SOLUTION**: I've figured out that it was actually an issue with my system locale, it was set to a version of English that was not supported by Steam. Changing my locale to en_US.UTF-8 fixed the issue. Thanks all for your help.
