### ISSUE TITLE
Anti-aliasing drops FPS in CS:GO/TF2

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4730]
#### Your system information

* Steam client version: 1476379980
* Distribution: Ubuntu 16.04 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In a game of Counter-Strike: Global Offensive and Team Fortress 2 on Linux I had some problems when using Anti-Aliasing. During the game may occur a sudden drop to 5-10 FPS. In Left 4 Dead 2 or Counter-Strike: Source like that did not happen.

#### Steps for reproducing this issue:

1. Turn on MSAA
2. Join to server
3. Wait for a 1-20 minutes
4. ??????
5. ISSUE!

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost and these games have changed substantially since 2016.
