### ISSUE TITLE
Steam takes 15 seconds to start

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4734]
* Steam client version: 1476379980 
* Distribution (e.g. Ubuntu): Devuan x64 & Openbox
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Steam displays the login message after about 11 seconds and is finally ready after 15 seconds. It's too long! Pretty much any other program except Firefox starts instantly on Openbox!

My suggestion is to look for what causes the 11s- gap and move the login process behind the interface start entirely to spare the remaining 4s. I am absolutely sure that this 11s have to do with Steam being unable to remove "SteamAppData.vdf", because after "Verification complete" it takes that much time and at the same moment the message not to be able to remove the file is displayed the login window appears.

`
Running Steam on devuan  64-bit
STEAM_RUNTIME is enabled automatically
[2016-12-04 14:01:58] Startup - updater built Oct 13 2016 00:47:16
[2016-12-04 14:01:58] Installation wird überprüft...
[2016-12-04 14:01:58] Verification complete
Unable to remove /home/user/.steam/CONFIG/SteamAppData.vdf!

Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Running Steam on devuan  64-bit
STEAM_RUNTIME has been set by the user to: /home/user/.steam/ubuntu12_32/steam-runtime
`

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost and this issue was non-fatal.
