### ISSUE TITLE
Missing mouse cursor with Steam Controller

### ISSUE THREAD

**Issue by NoLdman** [ValveSoftware/steam-for-linux#4738]
#### Your system information

* Steam client version: Okt 13 2016 at 00:48:25 (Package version: 1476379980 - Steam API: v017)
* Distribution: Fedora 25 (Kernel: 4.8.11 - Gnome: v3.22.2)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When you connect the Steam-Controller to the PC (Steam in Desktop mode), the mouse-cursor works fine till the user-profile is loaded. (I assume it's the user-profile since in the first 1-2sec the touchpad sound of the controller is a bit louder and the custom key-mappings don't work.)
After the profile has loaded the cursor is still visible and usable via conventional mouse, but if you try to use the touchpad of the Steam Controller, the mouse cursor stays at the same position. However it seems to work in the background, since I'm able to detect hover-effects when I use the touchpad.

Also tried to opt-in to the BETA program (Built: Dec 6 2016, at 00:45:50; Steam API: v017; Steam package version: 1480987489), however that resulted in a non-functioning controller all together.

I assume it's some sort of conflict with the new Wayland technology used in Gnome 3.22.

#### Steps for reproducing this issue:

1. Connected Controller to PC
2. Fresh installation of Fedora 25 Workstation
3. Update to the latest packages: `dnf update -y`
4. Installed Steam
5. Launched Steam (into default desktop mode)
6. Started Steam Controller

(Also tried the other way round: first starting Steam Controller and then launching Steam, same result.)

**Comment by Tele42** [comment]
Hello @NoLdman,
In order to use the steam controller with the steam beta client, you (or your distro's package maintainer for steam) need to update the udev rule as noted at http://steamcommunity.com/app/353370/discussions/0/490123197956024380/.

**Comment by NoLdman** [comment]
Hi @Tele42 ,

Thanks for your reply. Your suggestion only solves the problem, that the Steam-Controller doesn't get recognized on the current Steam-Beta, which seems to use it's own drivers.

Unfortunately the problem itself persists, the cursor doesn't get drawn on the screen. - Just to clarify: the mouse emulation of the controller works, only the drawn cursor-icon doesn't move.

**Comment by oddeyed** [comment]
I can confirm this issue - moving the mouse with the trackpad moves an invisible cursor but not the cursor drawn on the screen.
I don't know how to autogenerate that snippet from the post at the top but here is some system info.

Fedora 25
Linux Kernel: 4.8.15-300.fc25.x86_64
Steam API: v017
Steam package versions: 1483649853
Built: Jan 5 2017, at 18:41:06
GNOME Version 3.22.2 running on Wayland

**Comment by oddeyed** [comment]
Apologies for the double comment but to follow up: launching the GNOME session on X Windows does not create this bug!

So this would seem to be related to Wayland.

**Comment by NoLdman** [comment]
Can confirm, that it only happens on Wayland, but since the controller works till the user profile is loaded, I think it's an issue from the steam client.

**Comment by Plagman** [comment]
If something works well in Steam's native X environment and not in Wayland, odds are it's an issue or decision that has to do with Wayland's X compatibility; please raise this to the appropriate distro folks instead.

**Comment by anderejd** [comment]
I think I have the same issue. The cursor does not work properly on wayland. Please investigate.

**Comment by eanschuetz** [comment]
I also have this issue. The cursor does not appear on Wayland.

**Comment by djibux** [comment]
Same issue here :(

**Comment by jwlarocque** [comment]
Same issue, but some additional observations:

- The cursor works as expected for two or three seconds when I first plug in the wireless dongle, and then further movement is invisible.  
- Also, while in the activities overview (Gnome 3.34), the controller's mouse continues to interact with the focused window (still with no cursor) rather than interacting with the activities overview UI.

**Comment by buckysrevenge** [comment]
This issue has been passed over by whoever (wayland devs, Valve, ?...) for quite some time, considering that Steam's new BPM is seemingly requiring Wayland (at least in my experience with Nvidia GPUs and proprietary drivers), perhaps Valve can look into this again if they are planning to eventually release a generic SteamOS 3.x ISO?

**Comment by monreal** [comment]
I think this goes further than "Steam Controller", I get the same when trying to use "Joystick mouse" using my Xbox gamepad on a game using Steam Input (The Room).

**Comment by JBAnderson5** [comment]
Same issue six years later

**Comment by chaorace** [comment]
Just FYI: Until a better solution comes around, you can workaround the issue using this project: https://github.com/Supreeeme/extest

**Comment by LordMZTE** [comment]
I can reproduce this issue with Gnome 44 running on the Steam Deck under arch. Seems like it doesn't just affect the Steam controller.

**Comment by chaorace** [comment]
Just in case there's any Nixers watching this thread: I've created [an unofficial nix flake](https://github.com/chaorace/extest-nix) for extest

**Comment by spuxx1701** [comment]
I can confirm this issue still persists. Reproduced on Pop_OS! 22.04 With Wayland and a standard XInput controller (8bitDo Ultimate). 'Joystick Mouse' will not work.

**Comment by Skaifer** [comment]
Same issue here on PikaOS4, Wayland. Never had this issue on Bazzite. Probably, Gamescope serves as a workaround there. Someone mentioned here SC-Controller from Kozec, but there is a newer fork in case someone stumbles upon this comment - https://github.com/Ryochan7/sc-controller.

**Comment by h-n-a** [comment]
Still persists in Pop_OS! 24.04 with Cosmic. Kernel 6.18.7

**Comment by dann1609** [comment]
Same issue in windows.

**Comment by bartshin** [comment]
same issue in Ubuntu 24.04.4 LTS Wayland
mouse function fully work with Steam controller2 only Lizard mode
