### ISSUE TITLE
undefined symbol: xcb_wait_for_reply64

### ISSUE THREAD

**Issue by computerfr33k** [ValveSoftware/steam-for-linux#4739]
#### Your system information

* Steam client version:
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I cannot seem to launch steam anymore with or without the steam runtime.

This is the output I am receiving when I try to start steam
```bash
Running Steam on antergos 2015.11.01 64-bit
STEAM_RUNTIME is enabled by the user
Installing breakpad exception handler for appid(steam)/version(0)
/home/eric/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib32/libX11.so.6: undefined symbol: xcb_wait_for_reply64
mv: cannot stat '/home/eric/.steam/registry.vdf': No such file or directory
Installing bootstrap /home/eric/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on antergos 2015.11.01 64-bit
STEAM_RUNTIME has been set by the user to: /home/eric/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0)
/home/eric/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib32/libX11.so.6: undefined symbol: xcb_wait_for_reply64
```

#### Steps for reproducing this issue:

1. execute the steam command from terminal

Oddly enough steam launches just fine on my laptop running the same OS and DE. So, I'm basically just trying to figure out why my desktop stopped launching steam correctly and if anyone else has experienced this error as well and knows a way to fix it.

**Comment by gdrewb-valve** [comment]
Likely the same Steam runtime compatibility problem as other open issues here.

**Comment by kisak-valve** [comment]
Hello @computerfr33k, since this issue was last commented on, Steam's handling of the Steam runtime has changed to prefer host libraries over the runtime variants. Are you still experiencing this issue on an up to date system?

**Comment by computerfr33k** [comment]
I no longer run Arch Linux, so I cannot test this after being open for 3 years.
