### ISSUE TITLE
controller support broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4740]
up-to-date beta steamOS.
up-to-date beta steam client.

If I start steamOS  with my USB xin-mo based controller (arcade stick) plugged-in, I end up with a black screen.
If I start steamOS without my USB xin-mo based controller (arcade stick) plugged-in, I start OK.

----

If I hotplug my USB xin-mo based controller (arcade stick) once in big picture, the big picture client will freeze.

----

After a little strace investigation, the client does an endless loop on /dev/input/eventXX once I plug my USB xin-mo controller (arcade stick).

**Comment by Tele42** [comment]
There's some chatter on https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/599373548479454288 hinting that this is a cross-platform issue.

**Comment by joaormatos** [comment]
Also happening on Debian testing with a (wired) Steam Controller.

And since the stable client is still affected by #4662, I have no way to roll back to the previous beta and I lost my wireless receiver, my Steam Controller has essentially become a paperweight.

**Comment by rcano** [comment]
@joaormatos precisely my case.

**Comment by Tele42** [comment]
This should be fixed per "Fixed hang at startup if a controller is connected" in the [2016-12-08 steam beta client](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/599373548483218104) update.

**Comment by Unaccounted4** [comment]
@Tele42 It doesn't. The new beta does fix the hang but you can't use the controller at all still.

**Comment by Plagman** [comment]
Are you using a Steam or PS4 controller? You'll need the new set of udev rules for recent Beta builds:

http://steamcommunity.com/app/353370/discussions/0/490123197956024380/

**Comment by sylware** [comment]
fixed for me

**Comment by Unaccounted4** [comment]
@Plagman I have set the udev rules. Using the December 8th beta my Steam Controller doesn't work.

**Comment by rcano** [comment]
fixed for me.

**Comment by Brottweiler** [comment]
Yeah, it's fixed with the [Dec 8th](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/599373548483218104) update.

**Comment by Unaccounted4** [comment]
After deleting, copying, reloading and triggering the new udev rules (again) the Steam Controller now works in the latest beta (9th).
