### ISSUE TITLE
Steam connection issues on Ubuntu Zesty

### ISSUE THREAD

**Issue by MarkLutring** [ValveSoftware/steam-for-linux#4743]
#### Your system information

* Steam client version: 2016-09-02 beta
* Distribution (e.g. Ubuntu): Ubuntu 17.04 Zesty amd64
* Opted into Steam client beta?: [Yes/No] (tried both)
* Have you checked for system updates?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

I have a dual boot system, and steam works fine on my Windows 10, but i have problems on my both computer with Ubuntu 17.04 Development Branch.
I can't buy games, i can't load my profile settings and i can't download games.
I tried to reinstall steam, but after i removed i wasn't able to download steam files, the only workaround was to add 94.21.255.224 media.steampowered.com line to /etc/hosts file.
With this workaround i can download and install steam, but the buying games, installing/updating games issue is still exist.

**Comment by gdrewb-valve** [comment]
You're using a pre-release OS?  Have you brought this up with Canonical?

**Comment by Tele42** [comment]
Hello @MarkLutring, do you have libnss-resolve:i386 installed (from #4661)?

**Comment by MarkLutring** [comment]
Nope, and it solved my problem. Thank you Your help.

**Comment by gdrewb-valve** [comment]
Thanks, closing.
