### ISSUE TITLE
Cave story steam controller buttons stopped working

### ISSUE THREAD

**Issue by sweeze** [ValveSoftware/steam-for-linux#4744]
#### Your system information

* Steam client version: Dec 9 2016
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

As of a few days ago, my steam controller's triggers, X, Y, and B buttons have stopped working in cave story using a keyboard mapping that was working until recently.  The A button works fine to jump and the joystick works to move, but all the other buttons do nothing.  All buttons work fine in games that have native gamepad support, as well as in steam big picture mode itself.  Also in big picture mode, games seem to relaunch themselves after exiting, as if a button is being held in?  I see this behavior with the both the old and new udev rules on the non-beta client, and with the new udev rules on the beta client (old udev rules on beta resulted in no controller support as of the Dec 8 build at least).

**Comment by gdrewb-valve** [comment]
You might want to look at #4740.

**Comment by sweeze** [comment]
Thanks @gdrewb-valve, seems related but distinct.  I've reapplied the udev rules as per #4740 and updated to both latest stable and latest beta steam clients, but still seeing the same behavior.  one other thing i'm sometimes seeing is a steam soft keyboard opening up on top of cave story, but not clear what triggers that.

**Comment by sweeze** [comment]
@gdrewb-valve after playing with it a little more, I discovered that cave story appears to be getting the 'desktop bindings' for the steam controller instead of the game specific bindings.  So I'm able to now work around by remapping the desktop bindings / cave story controls, but it should be observing the game specific mappings, shouldn't it?

**Comment by gdrewb-valve** [comment]
I have no idea, this will need somebody from the Steam team to take a look.

**Comment by kisak-valve** [comment]
Hello @sweeze, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
