### ISSUE TITLE
[big picture] emoticons in chat are not properly displayed.

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4746]
Use an emoticon in chat, it will be located "above" normal text, like superscript.

**Comment by kisak-valve** [comment]
Hello @sylware, are you still experiencing this issue on an up to date system?

**Comment by sylware** [comment]
lol, the big picture interface was replaced by the web chat interface.

I'll test again once the big picture chat interface is back again or big
picture is killed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
