### ISSUE TITLE
[big picture] [txt chat] the display of messages is shifted of one message 

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4747]
up-to-date beta SteamOS
up-to-date beta steam client

The first message I sent is not displayed. I need to send another message to make the first message to be displayed... and the one I just sent is then not displayed (it's similar for the messages received).
And it's like that for the following messages.
(It already did happen in the past)

**Comment by sylware** [comment]
It seems it happens while there is a download in progress (I was downloading dota 700).

**Comment by sylware** [comment]
Now I have a notification of a txt message which never goes away.

**Comment by kisak-valve** [comment]
Hello @sylware, are you still experiencing this issue on an up to date system?

**Comment by sylware** [comment]
lol, big picture chat interface was replaced by the web chat.
Will test again once it is back or big picture is killed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
