### ISSUE TITLE
Corrupt update file. Autobuy.txt

### ISSUE THREAD

**Issue by AkAntA** [ValveSoftware/steam-for-linux#4754]
#### Your system information

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-53-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2016-09-02
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 375.20
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c0
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 6,30" x 3,54"  (7,20" diag)
                                            16,0cm x 9,0cm  (18,3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT2020
    
Memory:
    RAM:  16006 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  fi_FI.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  49085 Mb
    Largest Free Hard Disk Block:  16024 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Wed Dec 14 18:09:48 2016 GMT: file ''/tmp/dumps/assert_20161214200946_33.dmp'', upload yes: ''CrashID=bp-9e2cc2f3-9898-480f-8345-37c2f2161214''
    

* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I tried to start playing CS:GO earlier today and it immediately gave me an error message:
"An error occurred while updatin Counter-Strike: Global Offensive (corrupt update files) :
    .../Steam/steamapps/downloading/730/csgo/autobuy.txt"

![autobuyerror](https://cloud.githubusercontent.com/assets/19632383/21196015/d8330862-c23e-11e6-8e00-613af0641e53.png)

Since that I've tried various different methods to fix this e.g. clearing my download cache, changing my download region, removing my RAM one by one in case this is a memory fault (haven't tried out GPU memory),  validating game files, reinstalling CS etc. etc.

#### Steps for reproducing this issue:

1. Start the game
2. Wait it to download 6.1GB of update files
3. Receive the error message and start the file downloading again

**Comment by Tele42** [comment]
Hello @AkAntA, if you are installing the game to NTFS or F2FS, this is a duplicate of #4752.

**Comment by AkAntA** [comment]
@Tele42 yeah they seems to be on a NTFS. I'll check  the #4752 from here on now. Thank you!
