### ISSUE TITLE
Linux streaming host not available unless steam link is turned on

### ISSUE THREAD

**Issue by walmartshopper** [ValveSoftware/steam-for-linux#4755]
#### Your system information

* Steam client version: Dec 9, 2016
* Distribution (e.g. Ubuntu):  Arch 64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I have a streaming host running Arch and a guest laptop also running Arch.  If I login to steam on both, they are not available to stream to each other.  But if I turn on my steam link, the streaming option appears and I can then stream from host to laptop.

#### Steps for reproducing this issue:

1. Login to 2 different linux boxes. Streaming is not available.
2. Turn on a steam link on the same network and streaming becomes available between the two linux boxes.

**Comment by bandresen** [comment]
My Problem seems similar:
Windows host
Linux client

Windows host can see Linux client in the devices list, but "not connected"
Linux host can't see anything.

Haven't done any streaming in a month, so I don't know which update is responsible.

Updating to Beta didn't help.

**Comment by kisak-valve** [comment]
Hello @walmartshopper, @bandresen, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
