### ISSUE TITLE
resizing window moves window size randomly

### ISSUE THREAD

**Issue by Gibbz** [ValveSoftware/steam-for-linux#4757]
#### Your system information

* Steam client version:
dec 9 2016
* Distribution (e.g. Ubuntu): 
ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] 
no
* Have you checked for system updates?: [Yes/No]
no
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  open steam, any window main library or chat window for example
2. cursor over any of the window corners (also happens on edges)
3. dont move the mouse, just click and hold. The window will randomly resize.

Also frustratingly note that steam doesnt seem to remember the window size, i always find myself making the window small as possible on each launch....

**Comment by kisak-valve** [comment]
Hello @Gibbz,
What desktop environment are you using?

**Comment by Gibbz** [comment]
ubuntu 16.04 stock which uses unity

**Comment by kisak-valve** [comment]
Hello @Gibbz, are you still experiencing this issue on an up to date system?

**Comment by Gibbz** [comment]
Yes this is working fine now!
