### ISSUE TITLE
grep errors after update

### ISSUE THREAD

**Issue by win8linux** [ValveSoftware/steam-for-linux#4763]
#### System information
Kernel: x86_64 Linux 4.4.0-21-generic
Shell: zsh 5.1.1
Resolution: 1920x1080
DE: KDE5
WM: KWin
CPU: AMD A8-5600K APU with Radeon HD Graphics @ 3.6GHz
RAM: 5984MiB

* Steam client version: 1468023329 (terminal output)
* Distribution (Linux Mint 18 KDE): 
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

#### Steps for reproducing this issue:

1. Update Steam to latest version (as of time of writing)
2. Run Steam from terminal

HI there! I recently updated my Steam install and it's now it's no longer launching properly; it's currently spitting this out from the terminal:

`Running Steam on linuxmint 18 64-bit`
`STEAM_RUNTIME is enabled automatically`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`Installing breakpad exception handler for appid(steam)/version(1468023329)`

I've seen similar reports here on GitHub, but they all seem to be related to graphics issues. Mine doesn't seem to be that, since none of the solutions on those pages have worked and I don't see any references to drivers in my errors.

The original error output was this:

`Running Steam on linuxmint 18 64-bit`
`STEAM_RUNTIME is enabled automatically`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`/bin/bash: /home/julius/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)`
`awk: /home/julius/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc`
`Installing breakpad exception handler for appid(steam)/version(1468023329)`

I partially fixed this with the following:

`cd ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu`
`mv libstdc++.so.6 libstdc++.so.6.bak`

This left me with the grep errors remaining. Has anyone else experienced this and does anyone know how to solve this?

P.S. This is my first issue report, so pardon if there's anything wrong with this.

**Comment by kisak-valve** [comment]
Hello @win8linux,

This is a steam runtime compatibility issue. One of the workaround methods at https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues may be useful to you.

**Comment by win8linux** [comment]
Thanks, kisak-valve! It took me a while, but I found the right one.

For those who might later on have the same problem, go to the page suggested by kisak-valve and scroll to the very bottom; the relevant header is "Symbol lookup error using dri3".

**Comment by shraddhapp** [comment]
@win8linux / @kisak-valve  Could you please share the resolution for the "grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc"?

**Comment by win8linux** [comment]
https://wiki.archlinux.org/title/Steam/Troubleshooting#Symbol_lookup_error_using_DRI3

**Comment by kisak-valve** [comment]
Hello @shraddhapp, looking around a bit it looks like issues with pcre_jit_stack_alloc and grep were happening around 2016, but the way Steam handles the LD_* style Steam runtime has changed a fair bit and that particular issue doesn't seem to happen in the wild anymore.

If you're seeing a similar issue on an up to date system, please open a new issue report so that your issue can be tracked properly.

**Comment by shraddhapp** [comment]
Sure I will open a new issue

@win8linux @kisak-valve Thanks for your response.
