### ISSUE TITLE
Failed to create OpenGL device ! (Error: 0xFFFFFFFF)

### ISSUE THREAD

**Issue by Litarvan** [ValveSoftware/steam-for-linux#4765]
#### Your system information

* Steam client version: Dec 9 2016, at 20:41:34. 1481318740
* Distribution: Arch Linux 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

https://gist.github.com/Litarvan/40ba997c6809c4c1f7dd75199d5d1a2a

#### Please describe your issue in as much detail as possible:

When launching any source game, I get a this message, and the game crash : 

![Error message](https://i.gyazo.com/2b5f48ef92a671bda5aced9de070a075.png)

#### Steps for reproducing this issue:

1. Launch any source game

**Comment by Litarvan** [comment]
Oh. It doesnt work on KDE, but work on LXDE both with LightDM

**Comment by kisak-valve** [comment]
Hello @Litarvan,
please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report.

**Comment by Litarvan** [comment]
https://gist.github.com/Litarvan/40ba997c6809c4c1f7dd75199d5d1a2a

**Comment by kisak-valve** [comment]
Does this issue occur with nvidia 375.26?

**Comment by Litarvan** [comment]
Installing nvidia 375.26 mess up all my computer (LightDM-Webkit2, Plasma, Steam, and more) so I can't test it... I'll try tomorrow (sorry in France it is late) to downgrade nvidia more, because a couple of days ago i didn't have any problem

**Comment by Litarvan** [comment]
Ok so downgrading to nvidia 375.10-1 (375.10-2 for nvidia-utils and everything else) worked, thanks !
