### ISSUE TITLE
PrefetchW not supported

### ISSUE THREAD

**Issue by silviucc** [ValveSoftware/steam-for-linux#4766]
#### Your system information

* Steam client version: 1481318740
* Distribution (e.g. Ubuntu): Ubuntu 14.04 64bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam lists my CPU as not supporting PrefetchW.

It's an i5-2500k, I'm quite sure it does support it. Windows 10, on this same machine installed and works. It did not complain about missing features of my CPU before upgrading.

#### Steps for reproducing this issue:

1. I go to Help -> Systeminfo

**Comment by kisak-valve** [comment]
Hello @silviucc,
A quick search says your processor should not support PrefetchW, which is found on AMD processors.
Is there an actual problem you are encountering that goes along with this or just an oddity you noticed?

**Comment by silviucc** [comment]
Hi,

Your own software disagrees with that. On Windows, Steam lists the same processor as supporting PrefetchW.

![steam_windows_prefetchw](https://cloud.githubusercontent.com/assets/3889481/21448098/3a46ea9c-c8e7-11e6-863b-afb8e8f31251.PNG)

And here's a dump from Sysinternals Coreinfo:
[cpu_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/670331/cpu_info.txt)

**Comment by Danny3** [comment]
It still says PrefetchW: Unsupported on Linux!
At least with an AMD Ryzen 7 3700X.

**Comment by Delicates** [comment]
Still an issue on AMD Zen4 CPUs.

Why is this bug marked as closed?
