### ISSUE TITLE
Custom menubar not working properly

### ISSUE THREAD

**Issue by alemansec** [ValveSoftware/steam-for-linux#4770]
#### Your system information

* Steam client version:1482214037
* Distribution (e.g. Ubuntu): Debian GNU/Linux Jessie x86_64 up-to-date
* Opted into Steam client beta?: [Yes/No] Yes & No (both afected)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
custom secondary "title bar" (containing "STORE", "LIBRARY", "COMMUNITY" and "<profile_name>" links are not working properly when moving the mouse from below a menu item to that menu item : 

dropdown list will randomly disappear.

To get it working (somehow) we have to move the cursor from above menu items, so they won't disappear on you.

#### Steps for reproducing this issue:

1. move mouse cursor to LIBRARY menu item, coming from below

### expected behaviour
LIBRARY dropdown should popup and STAY VISIBLE when not moving mouse cursor outside droplist

### obtained behaviour
dropdown list randomly disappear

see following video:
http://5.39.79.140/vokoscreen-2016-12-21_19-28-38.mkv

**Comment by kisak-valve** [comment]
Hello @alemansec, just to double check, do you have focus-follows-mouse set in your DE, which might cause this kind of issue?

**Comment by alemansec** [comment]
@kisak-valve indeed, i always setup my windowmanager (i don't use any desktop manager) to let _me_ control focused window, using mouse-follow focus.

**Comment by kisak-valve** [comment]
This is a long standing issue that is being tracked at #6. Closing as a duplicate.
