### ISSUE TITLE
Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf!

### ISSUE THREAD

**Issue by Hadesy2k** [ValveSoftware/steam-for-linux#4773]
#### System information

* Steam client version:
* Distribution (e.g. Ubuntu): Kubuntu 16.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Issue in detail:
First I was using Nouveau driver. I got graphic problems when I tried to play borderlands 2. So I installed Nvidia (v367) for 940M. After the reboot, when I tried to connect to steam, the below statement is shown in terminal after I clicked login and connecting..

> Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf!

I already tried the solution `LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam` from [here](https://github.com/ValveSoftware/steam-for-linux/issues/4559). But it does not solve the problem.

#### Steps for reproducing this issue:

1. After installing Nvidia driver for 940M
2. `Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf!` shown after clicking login
3. Unable to login to steam

#### What I have tried
1. Removing .steam, Steam
2. Reinstalled steam but the problem still exist

**Comment by kisak-valve** [comment]
Hello @Hadesy2k, the steam network is temporarily down. You can monitor it's status at https://steamstat.us/.
