### ISSUE TITLE
Your coumputer is eighter unable to reach the steam servers 

### ISSUE THREAD

**Issue by Lacoz** [ValveSoftware/steam-for-linux#4774]
#### Your system information

* Steam client version: steam-launcher                                1.0.0.54
* Distribution (e.g. Ubuntu):  Ubuntu 16.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expect the steam will create my account

#### Steps for reproducing this issue:

1. Start steam from desktop
2. create new account
3. after filling username and password get error "Your coumputer is eighter unable to reach the steam servers ... "
![screenshot from 2016-12-23 18-46-09](https://cloud.githubusercontent.com/assets/1428538/21459676/bbf8801a-c940-11e6-8642-0b06cf4c69dc.png)

**Comment by kisak-valve** [comment]
Hello @Lacoz, the steam service is temporarily offline. You can monitor it's status at https://steamstat.us/.
