### ISSUE TITLE
ETS2 aborts on start on Ubuntu 16.04 64 bit 

### ISSUE THREAD

**Issue by truckerboy** [ValveSoftware/steam-for-linux#4776]
#### Your system information

* Steam client version: 1482202190 (Built Dec 20 2016)
* Distribution (e.g. Ubuntu): Ubuntu 16.04 (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
 I am not being able to launch Euro Truck Simulator 2 from 64 bit Ubuntu
16.04 after latest Steam update on 20-Dec-2016 (steam package version 1482202190). It was working fine before that.
This is what I am getting in xorg log file:

>>> Game update: AppID 227300 "Euro Truck Simulator 2", ProcID 10224, IP 0.0.0.0:0
>>> ERROR: ld.so: object '/home/racer/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> ERROR: ld.so: object '/home/racer/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 10224 for game ID 227300
>>> Adding process 10225 for game ID 227300
>>> Adding process 10226 for game ID 227300
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID: Caching Steam ID: 76561198123339408 [API loaded no]
Aborted
Game removed: AppID 227300 "Euro Truck Simulator 2", ProcID 10226

I have now tested and confirmed this issue on two separate computers
running native Ubuntu 16.04 64 bit (everything updated and latest).
One has an Intel HD Graphics 4000 card and the other a Nvidia GTX
1070.
I also verified the integrity and it shows "all files successfully
validated".

#### Steps for reproducing this issue:

1. Install ETS2 via Steam on Ubuntu 16.04 64 bit with default library option
2. Run ETS2
3. ETS2 fails to start.

**Comment by kisak-valve** [comment]
Hello @truckerboy, you should also contact the game devs about this issue.

This might be a steam runtime compatibility issue (some info at #4768), but there's not enough information here to tell.

**Comment by kisak-valve** [comment]
Hello @truckerboy, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
