### ISSUE TITLE
Steam won't install in docker container

### ISSUE THREAD

**Issue by joshuacox** [ValveSoftware/steam-for-linux#4778]
When installing in a docker container steam complains about not agreeing to the terms of service, I have set these:

```
echo "steam steam/purge note" | sudo debconf-set-selections
echo "steam steam/license note" | sudo debconf-set-selections
echo "steam steam/question select I AGREE" | sudo debconf-set-selections 
```

but steam still refuses to install, how can I get steam to install inside a docker container or how can I agree to the terms of service otherwise?   The repo I'm using is here:

https://github.com/Thalhalla/steamer

**Comment by joshuacox** [comment]
I made a branch for this issue:
https://github.com/Thalhalla/steamer/tree/4778
`make build` in that directory should get you the same results as me.

**Comment by kisak-valve** [comment]
Hello @joshuacox, you may have a better chance of solving this by reaching out to the user who made the docker setup. At a glance this appears to be for dedicated server instances using steamcmd, not the main steam client.

**Comment by joshuacox** [comment]
I think I got it working, that branch represents a working point for now, I'm continuing to test

**Comment by joshuacox** [comment]
btw I am the user who made the docker setup, it is for dedicated servers, but recently servers seem to be looking for required by steam
