### ISSUE TITLE
Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf

### ISSUE THREAD

**Issue by tophertzu** [ValveSoftware/steam-for-linux#4779]
#### Your system information

* Steam client version:
* Distribution (e.g. Ubuntu):  Ubuntu 16.10
* Opted into Steam client beta?: [Yes/No] 
* Have you checked for system updates?: [Yes/No]  Yes

#### Please describe your issue in as much detail as possible:
Installed steam and when I try to run through the terminal it asks me to log in through steam as I would expect, I get the error message "Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf" after logging in, and steam does not start.  I followed the steps in this thread suggested by LexBarringer:  https://github.com/ValveSoftware/steam-for-linux/issues/4559, but when I get to the step to type "LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam" into the terminal, it does not successfully launch steam.

#### Steps for reproducing this issue:

1.  Type 'steam' into terminal
2.  Log into steam
3.  Error message 'Unable to remove /home/USER/.steam/CONFIG/SteamAppData.vdf'

**Comment by kisak-valve** [comment]
Hello @tophertzu, you are most likely encountering one or more steam runtime compatibilty issues (being tracked at #4768). Are you using the distro-provided steam package? What video driver are you using?

As a side note, the error message about SteamAppData.vdf is unrelated and harmless.

**Comment by tophertzu** [comment]
So first off, I'm very new to Linux and not super tech-savy to begin with so forgive me if I'm missing the obvious stuff.

I'm not sure which steam package I'm using.  To install, I just typed in "sudo apt-get install steam" in the terminal.

My current driver:
X.Org X server -- Nouveau display dirver from xerver-xorg-viedo-nouveau
I also have access to a Nvidia legacy driver (version 304.134), but when I use it I get stuck in a login loop when I reboot.

**Comment by tophertzu** [comment]
Anyone have any ideas?

**Comment by Ruff9** [comment]
I have the exact same problem than @tophertzu , and I followed the same steps from https://github.com/ValveSoftware/steam-for-linux/issues/4559.

when I launch steam from command line, I got this: 

```
$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2017-01-02 22:15:08] Startup - updater built Dec 20 2016 05:49:54
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-01-02 22:15:08] Checking for update on startup
[2017-01-02 22:15:08] Checking for available updates...
[2017-01-02 22:15:09] Download skipped: /client/steam_client_ubuntu12 version 1482202200, installed version 1482202200
[2017-01-02 22:15:09] Nothing to do
[2017-01-02 22:15:09] Verifying installation...
[2017-01-02 22:15:09] Performing checksum verification of executable files
[2017-01-02 22:15:09] Verification complete
Unable to remove /home/remy/.steam/CONFIG/SteamAppData.vdf!

Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME has been set by the user to: /home/remy/.steam/ubuntu12_32/steam-runtime
Refresh rate: 1
```

for the video drivers, here is the output of `sudo lshw -c video`

```
  *-display               
       description: VGA compatible controller
       product: GK208M [GeForce GT 730M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:02:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:17 memory:f0000000-f0ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:3000(size=128) memory:f1000000-f107ffff
  *-display
       description: VGA compatible controller
       product: 4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:30 memory:f1400000-f17fffff memory:e0000000-efffffff ioport:4000(size=64)
```

This problem is really new for me: I was playing yesterday night without any issue.

If anything else can help, please ask.

**Comment by tophertzu** [comment]
Not sure if this thread is still active...should I close it and open another?

**Comment by kisak-valve** [comment]
@tophertzu, it looks like the example workaround you tried does not match the layout of your system. Does steam start with `LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6 /lib/i386-linux-gnu/libgpg-error.so.0' steam`?

**Comment by tophertzu** [comment]
This is the output I get.  It also starts a steam login loop where I login, I see the outline of the steam program, but it vanishes and asks me to log in again.

ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/i386-linux-gnu/libgpg-error.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/i386-linux-gnu/libgpg-error.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/i386-linux-gnu/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/i386-linux-gnu/libgpg-error.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Running Steam on ubuntu 16.10 64-bit
STEAM_RUNTIME is enabled automatically
[2017-01-13 11:46:08] Startup - updater built Dec 20 2016 05:49:54
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-01-13 11:46:09] Checking for update on startup
[2017-01-13 11:46:09] Checking for available updates...
[2017-01-13 11:46:10] Download skipped: /client/steam_client_ubuntu12 version 1482202200, installed version 1482202200
[2017-01-13 11:46:10] Nothing to do
[2017-01-13 11:46:10] Verifying installation...
[2017-01-13 11:46:10] Performing checksum verification of executable files
[2017-01-13 11:46:15] Verification complete
Unable to remove /home/chris/.steam/CONFIG/SteamAppData.vdf!

Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60
Refresh rate: 60

**Comment by kisak-valve** [comment]
Hello @tophertzu, @Ruff9, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
