### ISSUE TITLE
PS4 button glyphs missing on Linux

### ISSUE THREAD

**Issue by Nadia-h** [ValveSoftware/steam-for-linux#4782]
#### Your system information

* Steam client version: 1482214037 / Built Dec 20 2016 02:18:40
* Distribution (e.g. Ubuntu):  Arch Linux x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The button glyphs for the PS4 controller in the footer other than triangle are missing on Linux.
![skaermbillede pa 2016-12-30 03-58-12](https://cloud.githubusercontent.com/assets/893884/21559077/b3b40e56-ce45-11e6-87f8-0c951c03998b.png)

(I have changed my configuration to use O as the confirm button, but I don't think  this should matter)

#### Steps for reproducing this issue:

1. Enable PS4 configuration support
2. Connect a PS4 controller
3. Use the controller to navigate to a screen that shows buttons in the footer
4. The cross, circle and square glyphs are missing.

**Comment by prcastro** [comment]
I  can confirm the problem here:

**Your system information**
-     Steam client version: 1482202200
-     Distribution (e.g. Ubuntu): Arch Linux x86_64
-     Opted into Steam client beta?: No
-     Have you checked for system updates?: Yes

**Comment by kisak-valve** [comment]
Per "Fixed PS4 Glyphs in Big Picture appearing incorrectly in SteamOS/Linux." in the [2017-04-18 Steam Beta client](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/562230888516495043), please opt-in to the beta client and retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by thankjura** [comment]
Same problem for today's update (beta version).
If interface langiage is english problem disapper.
If change interface language to russian the problem appears again
![screen](https://user-images.githubusercontent.com/2144212/31406849-86ecdffa-ae0b-11e7-8b41-cf3b2f383721.png)

**Comment by kisak-valve** [comment]
Hello @thankjura, please open a new issue report for your issue.
