### ISSUE TITLE
Steam doesn't display all DLC I own for Killing Floor 1

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4783]
#### Your system information

* Steam client version: Latest stable as of today
* Distribution (e.g. Ubuntu): Ubuntu 16.10 amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam only shows that I own: Killing Floor - Community Weapon Pack 1,
when in reality I also own the Killing Floor - Community Weapon Pack 2
and Killing Floor - Community Weapon Pack 3.
It shows on the respective steam store pages that I own them, and I can use them in-game but
there is no option to disable them, in the game properties and DLC tab, it only shows pack 1.

#### Steps for reproducing this issue:

1. Have the mentioned game and DLCs
2. Go to the properties of the game and DLC tab
3. It will not show all DLC own

**Comment by kisak-valve** [comment]
Hello @ekaris, you should contact the game developers for help with this issue.
