### ISSUE TITLE
steamwebhelper segfaults and hangs Xorg when closing Dota 2

### ISSUE THREAD

**Issue by Demiu** [ValveSoftware/steam-for-linux#4784]
#### Your system information

* Steam client version: 1482202190, API v017
* Distribution (e.g. Ubuntu): Manjaro XFCE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Upon closing Dota 2 client the screen freezes & stops responding, some X bindings work, other do not. For example, I couldn't ctrl+alt+backspace to restart X. Fortunately I was able to switch another virtual terminal. I run htop and saw Xorg taking 100% CPU on one of the cores. With Xorg still unresponding to anything other than VT switch I sent a sigkill to it and then kept using the PC as usual, thinking that it was a problem with system packages and will be solved. Then it happened again and after some digging I found that some time before the crash the Xorg was reporting. 

> NVIDIA(0): Setting mode "nvidia-auto-select+0+0{ForceFullCompositionPipeline=On}"
> NVIDIA(0): ACPI: failed to connect to the ACPI event daemon

This first appeared after 44 hours of uptime and then repeated in random intervals.
What led me to report this bug here instead of Dota 2 tracker was a particular bug in dmesg

> steamwebhelper[1398]: segfault at 58 ip 000055fe11260cb7 sp 00007fe579f6ba50 error 4 in steamwebhelper[55fe11225000+285000]

Sadly this are the only two things out of the ordinary that I could find. I also have no concrete  reporduction steps for this and only related things seem to be long uptimes of both the PC and Dota 2.

#### Steps for reproducing this issue:

1. Turn on the PC
2.  Launch Steam
3.  Launch Dota 2
4. Possibly play a match (?)
5. Wait a long period of time, about 48 hours
6. Shut down Dota 2 using the close button in the top right corner in the game

**Comment by kisak-valve** [comment]
Hello @Demiu, no OpenGL application should be capable of locking up the system, which means this is most likely a driver bug. That said, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a gist, then include a link to the gist in this issue report. If you can find any CrashIDs or minidump files related to this issue, please include them in this issue report.

**Comment by Demiu** [comment]
The system info:
https://gist.github.com/Demiu/713905190bcc3fbb8cf17eabf75507db
Here's a possibly relevant stacktrace from journalctl, however it is from after I login and kill Xorg, but before the segfault in the OP (that one is also after the kill)
https://gist.github.com/Demiu/7db272ad8f889f7c51642c889604985f

Unfortunately I cannot provide the dump files - the /tmp/dumps folder has been cleared on reboot and the 2 files in the system info are from when I closed steam after it couldn't connect and the only .dmp files I could find in steam's install path were related to insurgency.

**Comment by kisak-valve** [comment]
Hello @Demiu, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
