### ISSUE TITLE
Taking a screenshot with F12 not always makes a sound 

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4786]
#### Your system information

* Steam client version: Latest stable as of today
* Distribution (e.g. Ubuntu):  Ubuntu 16.10 amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I click on F12 to take a screenshot, steam does not make a sound most of the time at the first click despite taking a screenshoot and saving the file file disk.

#### Steps for reproducing this issue:

1. Run a fullscreen steam game
2. Click on F12
3. It will not make a sound most of the time at first click

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost and Ubuntu 16.10 has reached its end of life.
