### ISSUE TITLE
Uploading screenshots with the option to save an uncompressed copy enabled doesn't upload them, uploads instead lossy JPEG

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4788]
#### Your system information

* Steam client version: Latest stable as of today
* Distribution (e.g. Ubuntu): Ubuntu 16.10 amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Uploading screenshots with the steam settings option to save an uncompressed copy enabled doesn't upload the PNGs, uploads instead lossy JPEG

#### Steps for reproducing this issue:

1. Enable "save an uncompressed copy" in the steam settings
2. Take a screenshot in game with F12
3. Uploading to the steam cloud doesn't upload the uncompressed copy

**Comment by kisak-valve** [comment]
Hello @ekaris, this is the intended behavior. Closing.
