### ISSUE TITLE
Disabling steam runtime causes steam to shutdown immediately.

### ISSUE THREAD

**Issue by Jayman2000** [ValveSoftware/steam-for-linux#4789]
#### Your system information

* Steam client version: 1482202200, API v017 (Ubuntu package version 1:1.0.0.48-1ubuntu3)
* Distribution (e.g. Ubuntu): KDE neon 5.8 (Ubuntu 16.04 derivative)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Disabling the steam runtime causes steam to shutdown immediately after verification. No steam window ever pops up.

#### Steps for reproducing this issue:

1. Run 'STEAM_RUNTIME=0 steam'

#### Result:
jayman@jason-desktop:\~$ STEAM_RUNTIME=0 steam
Running Steam on neon 16.04 64-bit
STEAM_RUNTIME is disabled by the user
[2017-01-01 18:49:25] Startup - updater built Dec 20 2016 05:49:54
[2017-01-01 18:49:25] Verifying installation...
[2017-01-01 18:49:25] Verification complete
[2017-01-01 18:49:26] Shutdown
jayman@jason-desktop:\~$

**Comment by kisak-valve** [comment]
Hello @Jayman2000, disabling the steam runtime is unsupportable by Valve.

That said, you are most likely missing one or more dependencies. Use `LD_DEBUG=LIBS steam` to help yourself troubleshoot or reach out to your community for support.
