### ISSUE TITLE
Turkish Invisible menus on Steam client,missing writings

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#4792]
#### Your system information

* Steam client version:1482202200,API V017
* Distribution (e.g. Ubuntu): Linux Mint 18.1 64-bit(based on Ubuntu 16.04 64-bit)
* Opted into Steam client beta?: NO 
* Have you checked for system updates?: Yes,i'm already running latest version

#### Please describe your issue in as much detail as possible:
I'm using Linux Mint 18.1 64 bit Cinnamon in Turkish language.When we just download latest.deb from official Valve page and install it,after that instead of login  page just comes with a blank screen with only Steam logo.But the buttons are still there and functioning.It's same on Ubuntu as well.I tried that.

We can correct this issue with a method.

Just with a command from terminal.

`LC_ALL=C steam`

With that command Steam overlay and Steam client interface 'arayüz'section becomes visible.But this time we can't type some letters.Like 'i'for instance.

And also in this situation some games doesn't even start.For example;Football Manager 2016 stuck at loading screen when we start Steam normally,without Lc All C command.

With Lc All C command it starts to work.

This a 2 or 3 year issue.It's all been broken since years.

Without All C command screenshot
![ekran goruntusu - 2017-01-02 20-29-47](https://cloud.githubusercontent.com/assets/24878978/21593638/fd7fbc40-d121-11e6-810c-322cf380b8ed.png)

With All C command screenshot

![ekran goruntusu - 2017-01-02 20-32-08](https://cloud.githubusercontent.com/assets/24878978/21593655/2ec01570-d122-11e6-9447-d78b5af75527.png)

#### Steps for reproducing this issue:

1. A Linux Mint or Ubuntu installation with Turkish language
2. Just install the latest Steam Client from this page. http://store.steampowered.com/about/
3. And if you try to login you will see a blank Steam window,just a Steam logo and nothing else.

**Comment by kisak-valve** [comment]
Previously reported at #4441, however this fully investigated. Thanks for the well written report.

**Comment by Leopard1907** [comment]
So are you gonna try to fix it or not?

Because we have also a forum site about Linux and this problem occurs on every system.With Amd,Nvidia or Intel Gpu's.

We need a locale tr Utf8 support i guess.

**Comment by kisak-valve** [comment]
@Leopard1907, so that it is clear, I am a moderator for the issue tracker. We'll need to wait to hear from a Valve dev.

**Comment by Leopard1907** [comment]
@kisak-valve 

Thanks for the reply.I hope Valve devs will respond quickly.

Thanks again.

**Comment by Leopard1907** [comment]
@kisak-valve Hi,sorry to bother you.I was searching for this problems source and some Greek Steam user offers a solution,maybe this could be areference for what's needed to be done with Steam non-English systems.Also this can be worth giving a try for issue #4790 . It seems it's a common problem with non-English systems.You can see already a Danish and a Russian user are suffering from this.

> Well to me it seems that this is like 99% NOT a steam issue.
This problem exists in most of the programs in Linux and it happens if you are not able to set up your locale correctly to your distro.
I am using Greek Locale in everything I do and all are working fine.
In my noobish Linux era I had problems as well running programs because I had Greek Locale.
by changing only the Language/locale in your distro you are using is not enough, you have to generate your locale.

This is how you do it...
First choose what locale you are using by removing the #

sudo gedit /etc/locale.gen

Example:
#dv_MV UTF-8 
#dz_BT UTF-8 
el_GR.UTF-8 UTF-8 
el_GR ISO-8859-7 
el_CY.UTF-8 UTF-8 
el_CY ISO-8859-7 
#en_AG UTF-8 
#en_AU.UTF-8 UTF-8

Then regenerate your locale - reboot and you should be fine

sudo locale-gen

**Comment by Leopard1907** [comment]
Also that LC_ALL=C problem is mentioned here.

A Danish user and a Russian user.

https://github.com/ValveSoftware/steam-for-linux/issues/4790

**Comment by Leopard1907** [comment]
I've also noticed that some of the writings at 'Arayüz (Interface)' are overlapping.
Download timer and bandwith limiter sections are doing that.

Of course , i'm running it with LC_ALL=C. Otherwise it is blank.

![12](https://cloud.githubusercontent.com/assets/24878978/25380278/698d742e-29b8-11e7-9aec-02a53d8d9ae0.png)

**Comment by kisak-valve** [comment]
@Leopard1907, please open a new issue report for the overlapping text so that it can be tracked properly.

**Comment by Leopard1907** [comment]
@kisak-valve I'll do it , thanks.

**Comment by Parduk** [comment]
This is very annoying issue, please fix this

**Comment by semihkiroglu** [comment]
I have the same problem, if I using Ubuntu (16.04 to 17.04) or Manjaro 17.0.x in Turkish language.

**Comment by yuceltoluyag** [comment]
please fix this !

**Comment by BTaskaya** [comment]
Same on arch (Kernel 4.16)

**Comment by Leopard1907** [comment]
@Plagman I know Valve time is a bit different than real life time but...

**Comment by Leopard1907** [comment]
@kisak-valve @Plagman

Looks like it is fixed lately.

There is no need for that command now. These invisible parts are visible without that command too.

I can type Turkish characters etc. Didn't try FM 2016 though. 

Odd thing is , if you are running without that command. Unreal Engine 4 games are not booting anymore.

After putting that command in an Unreal Engine 4 game launch options , it is working.

LANG=C %command%

or 

LC_ALL=C %command%

So there is something deeper going on. That language problem reported to Epic Games.

Fwiw , Feral Interactive ports are also in a need for that.

https://github.com/FeralInteractive/ferallinuxscripts/issues/6#bottom

**Comment by kisak-valve** [comment]
Closing because the original issue appears to have been resolved.
