### ISSUE TITLE
Interface for unofficial engine ports.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4793]
Many old games only working on Windows tend to be lost when people switch to Linux entirely. That might be one of the biggest reasons for low numbers in the hardware survey each month.

But luckily there are kind people porting these engines to Linux so they run even better than ever before.
I see a great willingness to do more and more such ports like OpenMW, OpenTomb or OpenRW in the community. But I also feel that many people discard these ideas quickly, seeing no chance for a wide spread application of their work due to the massive obstacles for the end user(steamcmd, knowing about the project etc...)

Opening the door for these engines like "Sadly your requested game is not officially supported on your platform. An unofficial open source port is available. Would you like to proceed at your own risk?",  seems to be the key to improve both the attraction of Linux to users and open source developers who think about porting a game.

**Comment by shoober420** [comment]
Totally agree. With QuakeSpasm, yamagi-quake2, ioquake3, iortcw, dhewm3, oldunreal, and ecwolf to name a few, it would be great to be able to launch these from Steam and have them count as your hours played during the game.

**Comment by mtmkls** [comment]
Don't forget ScummVM.

**Comment by jcelerier** [comment]
For reference here is a more exhaustive list : http://osgameclones.com/

**Comment by kisak-valve** [comment]
Hello, the bits needed to make a community bundle of foss game engines to run games with has been implemented as part of Proton's integration in Steam. Additionally, these can be installed and maintained as regular distro packages (#6310).

See https://github.com/dreamer/boxtron as a working example of this.
