### ISSUE TITLE
Gamepad bindings hidden from Steam Controller's desktop configuration

### ISSUE THREAD

**Issue by joaormatos** [ValveSoftware/steam-for-linux#4801]
On Linux the gamepad bindings work fine in the desktop configuration, so please don't hide those settings from us just because they don't work on Windows!

* Steam client version: Jan 10 2017, at 00:59:06
* Distribution: Debian testing amd64
* Opted into Steam client beta?: Yes 
* Have you checked for system updates?: Yes

**Comment by kisak-valve** [comment]
Related intentional change in the 2017-01-09 steam beta client noted at https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182177118126.

**Comment by kisak-valve** [comment]
Hello @joaormatos, looks like this was re-enabled some time ago.
