### ISSUE TITLE
CSGO wont launch 

### ISSUE THREAD

**Issue by Firefly1029** [ValveSoftware/steam-for-linux#4805]
#### Your system information

* Steam client version: unknown/latest
* Distribution (e.g. Ubuntu): ubuntu
* Opted into Steam client beta?: [Yes/No] Don't think so EDIT: yes 
* Have you checked for system updates?: [Yes/No]no

#### Please describe your issue in as much detail as possible: Just got steam to launch thanks to help from a user in this hub. I have to launch steam using "LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6 /lib/i386-linux-gnu/libgpg-error.so.0' steam" but now I can't launch games. 
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) Expected a game to launch, it didn't. No error code, just says im ingame but it doesnt launch

#### Steps for reproducing this issue:

1. install game
2. launch
3. fail

My game seems to be working now.

**Comment by kisak-valve** [comment]
Closing as this appears to have been resolved.
