### ISSUE TITLE
Mighty No. 9 does not start unless LD_PRELOAD='/usr/lib32/libopenal32.so'

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#4806]
* Steam client version: January 12th
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Steps for reproducing this issue:

1.  Launch the game

With the runtime disabled, Mighty No. 9 does not launch unless you put LD_PRELOAD='/usr/lib32/libopenal32.so' in the games launch options under properties.

**Comment by kisak-valve** [comment]
Hello @shoober420, the game has bundled openal and that is taking priority. You should contact the game dev and/or make a note about this at https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting.

Closing as there is no action for a Valve dev.

**Comment by shoober420** [comment]
OK, thank you for the information.
