### ISSUE TITLE
Prison Architect loads then crashes on optimus system

### ISSUE THREAD

**Issue by tomerobin** [ValveSoftware/steam-for-linux#4807]
* Steam client version: 1482202200
* Distribution (e.g. Ubuntu): Debian 3.16.0-4-amd64
* Opted into Steam client beta?: [Yes/No] N
* Have you checked for system updates?: [Yes/No] Y

#### Please describe your issue in as much detail as possible:
So the game runs when launched in safe mode from the steam client but not using optirun or primusrun. When I do that there is a black screen for 20s, then the game loads to the opening screen, but only run for about 2s before crashing.

Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Printing DDC gathered Modelines:
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Printing DDC gathered Modelines:
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Printing DDC gathered Modelines:
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 14 01:41:57 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 14 01:41:57 debian gnome-session[994]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2800010 (Prison Arc)
Jan 14 01:42:24 debian kernel: [ 4806.403952] PrisonArchitect[5930]: segfault at 208 ip 00007fdc18795d2d sp 00007ffff7787d10 error 4 in i965_dri.so[7fdc18442000+51e000]
Jan 14 01:42:24 debian gnome-session[994]: Failed to open BO for returned DRI2 buffer (1600x900, dri2 back buffer, named 19).
Jan 14 01:42:24 debian gnome-session[994]: This is likely a bug in the X Server that will lead to a crash soon.
Jan 14 01:42:24 debian kernel: [ 4806.472885] gnome-shell[5789]: segfault at 208 ip 00007f172866cd2d sp 00007ffdc7f21df0 error 4 in i965_dri.so[7f1728319000+51e000]
Jan 14 01:42:24 debian gnome-session[994]: x-session-manager[994]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
Jan 14 01:42:24 debian x-session-manager[994]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
Jan 14 01:42:24 debian gdm-Xorg-:0[958]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 14 01:42:24 debian gdm-Xorg-:0[958]: (II) intel(0): Printing DDC gathered Modelines:
Jan 14 01:42:24 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 14 01:42:24 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 14 01:42:25 debian gnome-session[994]: Gjs-Message: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
Jan 14 01:42:25 debian dbus[654]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service'
Jan 14 01:42:25 debian systemd[1]: Starting Location Lookup Service...
Jan 14 01:42:25 debian dbus[654]: [system] Successfully activated service 'org.freedesktop.GeoClue2'
Jan 14 01:42:25 debian systemd[1]: Started Location Lookup Service.
Jan 14 01:42:27 debian gdm-Xorg-:0[958]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 14 01:42:27 debian gdm-Xorg-:0[958]: (II) intel(0): Printing DDC gathered Modelines:
Jan 14 01:42:27 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 14 01:42:27 debian gdm-Xorg-:0[958]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 14 01:42:28 debian gnome-session[994]: (gnome-shell:5947): Gjs-WARNING **: JS ERROR: Exception in callback for signal: startup-complete: Error: Requiring GSystem, version none: Typelib file for namespace 'GSystem' (any version) not found
Jan 14 01:42:28 debian gnome-session[994]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:216
Jan 14 01:42:28 debian gnome-session[994]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
Jan 14 01:42:28 debian gnome-session[994]: LayoutManager<._startupAnimationComplete@resource:///org/gnome/shell/ui/layout.js:704
Jan 14 01:42:28 debian gnome-session[994]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Jan 14 01:42:28 debian gnome-session[994]: _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:91
Jan 14 01:42:28 debian gnome-session[994]: _callOnFunction@resource:///org/gnome/gjs/modules/tweener/tweener.js:203
Jan 14 01:42:28 debian gnome-session[994]: _updateTweenByIndex@resource:///org/gnome/gjs/modules/tweener/tweener.js:333
Jan 14 01:42:28 debian gnome-session[994]: _updateTweens@resource:///org/gnome/gjs/modules/tweener/tweener.js:345
Jan 14 01:42:28 debian gnome-session[994]: _onEnterFrame@resource:///org/gnome/gjs/modules/tweener/tweener.js:360
Jan 14 01:42:28 debian gnome-session[994]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
Jan 14 01:42:28 debian gnome-session[994]: ClutterFrameTicker<._onNewFrame@resource:///org/gnome/shell/ui/tweener.js:208
Jan 14 01:42:28 debian gnome-session[994]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Jan 14 01:42:28 debian gnome-session[994]: `ClutterFrameTicker<._init/<@resource:///org/gnome/shell/ui/tweener.js:183`

#### Steps for reproducing this issue:

1.  Install nvidia proprietary driver with 32 bit libraries as detailed here https://wiki.debian.org/Bumblebee#Usage
2. Install steam
3. Download and run Prison Architect

**Comment by kisak-valve** [comment]
Hello @tomerobin, can you please opt into the steam beta client and retest?

**Comment by tomerobin** [comment]
hi kisak, I have opted into the beta and I am unfortunately getting exactly the same issue.

**Comment by tomerobin** [comment]
Here's the log now I have opted in:


Jan 15 10:59:17 debian kernel: [  232.582723] bbswitch: enabling discrete graphics
Jan 15 10:59:17 debian org.gnome.zeitgeist.SimpleIndexer[1084]: ** (zeitgeist-fts:1359): WARNING **: Unable to get info on application://nautilus-autostart.desktop
Jan 15 10:59:18 debian kernel: [  233.512968] nvidia: module license 'NVIDIA' taints kernel.
Jan 15 10:59:18 debian kernel: [  233.512991] Disabling lock debugging due to kernel taint
Jan 15 10:59:18 debian kernel: [  233.543566] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=io+mem,decodes=none:owns=none
Jan 15 10:59:18 debian kernel: [  233.544832] [drm] Initialized nvidia-drm 0.0.0 20150116 for 0000:01:00.0 on minor 1
Jan 15 10:59:18 debian kernel: [  233.544864] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  340.96  Sun Nov  8 22:33:28 PST 2015
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: removing GPU device /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1 /dev/dri/card1
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: (II) config/udev: Adding drm device (/dev/dri/card1)
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: (II) xfree86: Adding drm device (/dev/dri/card1)
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: (II) LoadModule: "modesetting"
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: (II) Module modesetting: vendor="X.Org Foundation"
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: compiled for 1.16.4, module version = 0.9.0
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: Module class: X.Org Video Driver
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: ABI class: X.Org Video Driver, version 18.0
Jan 15 10:59:18 debian gdm-Xorg-:0[983]: xf86: found device 1
Jan 15 10:59:19 debian kernel: [  234.469686] nvidia 0000:01:00.0: irq 50 for MSI/MSI-X
Jan 15 10:59:19 debian kernel: [  234.480592] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.480983] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.481267] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.481596] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.481859] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.554931] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.556291] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.556549] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:19 debian kernel: [  234.556820] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:23 debian kernel: [  238.474354] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:23 debian kernel: [  238.877909] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:23 debian acpid: client connected from 1979[0:999]
Jan 15 10:59:23 debian acpid: 1 client rule loaded
Jan 15 10:59:24 debian bumblebeed[648]: [  240.264650] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Jan 15 10:59:24 debian bumblebeed[648]: [  240.264728] [WARN][XORG] (WW) Unresolved symbol: fbGetGCPrivateKey
Jan 15 10:59:24 debian bumblebeed[648]: [  240.264785] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
Jan 15 10:59:24 debian bumblebeed[648]: [  240.264841] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Jan 15 10:59:24 debian gnome-session[1008]: Running Steam on debian 8 64-bit
Jan 15 10:59:25 debian gnome-session[1008]: STEAM_RUNTIME is enabled automatically
Jan 15 10:59:25 debian kernel: [  240.522041] [drm] Module unloaded
Jan 15 10:59:25 debian gdm-Xorg-:0[983]: removing GPU device /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1 /dev/dri/card1
Jan 15 10:59:25 debian kernel: [  240.528623] bbswitch: disabling discrete graphics
Jan 15 10:59:25 debian kernel: [  240.528668] ACPI Warning: \_SB_.PCI0.PEG0.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140424/nsarguments-95)
Jan 15 10:59:25 debian kernel: [  240.543017] pci 0000:01:00.0: Refused to change power state, currently in D0
Jan 15 10:59:25 debian crash_20170115105925_17.dmp[2083]: Uploading dump (out-of-process)#012/tmp/dumps/crash_20170115105925_17.dmp
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Printing DDC gathered Modelines:
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Printing DDC gathered Modelines:
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Printing DDC gathered Modelines:
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 15 10:59:26 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 15 10:59:26 debian gnome-session[1008]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c00010 (Prison Arc)
Jan 15 10:59:29 debian crash_20170115105925_17.dmp[2083]: Finished uploading minidump (out-of-process): success = yes
Jan 15 10:59:29 debian crash_20170115105925_17.dmp[2083]: response: CrashID=bp-3725b79c-fc04-414b-8620-148d22170115
Jan 15 10:59:29 debian crash_20170115105925_17.dmp[2083]: file ''/tmp/dumps/crash_20170115105925_17.dmp'', upload yes: ''CrashID=bp-3725b79c-fc04-414b-8620-148d22170115''
Jan 15 11:00:00 debian kernel: [  275.237515] PrisonArchitect[2092]: segfault at 208 ip 00007f53d8017d2d sp 00007fff73cdb860 error 4 in i965_dri.so[7f53d7cc4000+51e000]
Jan 15 11:00:00 debian gnome-session[1008]: Failed to open BO for returned DRI2 buffer (1600x900, dri2 back buffer, named 5).
Jan 15 11:00:00 debian gnome-session[1008]: This is likely a bug in the X Server that will lead to a crash soon.
Jan 15 11:00:00 debian kernel: [  275.308207] gnome-shell[1253]: segfault at 3c ip 00007f483e0672bc sp 00007ffff10f0350 error 4 in i965_dri.so[7f483dcd3000+51e000]
Jan 15 11:00:00 debian x-session-manager[1008]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
Jan 15 11:00:00 debian gnome-session[1008]: x-session-manager[1008]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
Jan 15 11:00:00 debian gdm-Xorg-:0[983]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 15 11:00:00 debian gdm-Xorg-:0[983]: (II) intel(0): Printing DDC gathered Modelines:
Jan 15 11:00:00 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 15 11:00:00 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 15 11:00:00 debian wpa_supplicant[989]: nl80211: send_and_recv->nl_recvmsgs failed: -33
Jan 15 11:00:01 debian gnome-session[1008]: Gjs-Message: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
Jan 15 11:00:01 debian dbus[667]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service'
Jan 15 11:00:01 debian systemd[1]: Starting Location Lookup Service...
Jan 15 11:00:01 debian dbus[667]: [system] Successfully activated service 'org.freedesktop.GeoClue2'
Jan 15 11:00:01 debian systemd[1]: Started Location Lookup Service.
Jan 15 11:00:03 debian gdm-Xorg-:0[983]: (II) intel(0): EDID vendor "LGD", prod id 735
Jan 15 11:00:03 debian gdm-Xorg-:0[983]: (II) intel(0): Printing DDC gathered Modelines:
Jan 15 11:00:03 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 1774  900 903 907 912 +hsync -vsync (54.7 kHz eP)
Jan 15 11:00:03 debian gdm-Xorg-:0[983]: (II) intel(0): Modeline "1600x900"x0.0   97.12  1600 1648 1696 2370  900 903 907 1024 +hsync -vsync (41.0 kHz e)
Jan 15 11:00:04 debian gnome-session[1008]: (gnome-shell:2108): Gjs-WARNING **: JS ERROR: Exception in callback for signal: startup-complete: Error: Requiring GSystem, version none: Typelib file for namespace 'GSystem' (any version) not found
Jan 15 11:00:04 debian gnome-session[1008]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:216
Jan 15 11:00:04 debian gnome-session[1008]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
Jan 15 11:00:04 debian gnome-session[1008]: LayoutManager<._startupAnimationComplete@resource:///org/gnome/shell/ui/layout.js:704
Jan 15 11:00:04 debian gnome-session[1008]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Jan 15 11:00:04 debian gnome-session[1008]: _addHandler/params[name]@resource:///org/gnome/shell/ui/tweener.js:91
Jan 15 11:00:04 debian gnome-session[1008]: _callOnFunction@resource:///org/gnome/gjs/modules/tweener/tweener.js:203
Jan 15 11:00:04 debian gnome-session[1008]: _updateTweenByIndex@resource:///org/gnome/gjs/modules/tweener/tweener.js:333
Jan 15 11:00:04 debian gnome-session[1008]: _updateTweens@resource:///org/gnome/gjs/modules/tweener/tweener.js:345
Jan 15 11:00:04 debian gnome-session[1008]: _onEnterFrame@resource:///org/gnome/gjs/modules/tweener/tweener.js:360
Jan 15 11:00:04 debian gnome-session[1008]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
Jan 15 11:00:04 debian gnome-session[1008]: ClutterFrameTicker<._onNewFrame@resource:///org/gnome/shell/ui/tweener.js:208
Jan 15 11:00:04 debian gnome-session[1008]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Jan 15 11:00:04 debian gnome-session[1008]: ClutterFrameTicker<._init/<@resource:///org/gnome/shell/ui/tweener.js:183

**Comment by kisak-valve** [comment]
You may be able to find some hints at https://wiki.archlinux.org/index.php/bumblebee.

After confirming optirun work outside of steam, I would give `optirun -b primus %command%` a try, if that doesn't work then I would try `LD_PRELOAD="libpthread.so.0 libGL.so.1" optirun -b primus %command%` a try (from #3506).

**Comment by tomerobin** [comment]
Great, thanks for putting me onto that.

Now I have Prison Architect running on my discrete GPU va optirun.
For reference, from the thread you linked I used BogdanOlar's script and then added `LD_PRELOAD="libpthread.so.0 libGL.so.1" optirun -b primus %command%` into the launch options through the steam interface.

From reading some comments it appears just modifying the launch options without running BogdanOlar's script might work so try that first to save time.
