### ISSUE TITLE
Steam controller doesn't work with latest beta (Jan 13)

### ISSUE THREAD

**Issue by yoyko** [ValveSoftware/steam-for-linux#4809]
#### Your system information

* Steam client version: 1484353539 (Jan 13 2017 23:53:23)
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: ???

#### Please describe your issue in as much detail as possible:
Steam controller doesn't work with the latest beta client: the client detects the controller, then there's a crash mentioned on the console (steam continues to run, so must be some subprocess..) and the client seems to re-detect the controller a couple of times, but it doesn't work anymore:

https://gist.github.com/yoyko/1de651f06da004a236e1f677b9507d43#file-steam-log

This log was with the controller connected wirelessly, but the same happens when it's wired.

It works OK with the stable client (1482202200, Dec 20 2016 02:18:40).
I have the udev rules from the sticky post on the forums: https://gist.github.com/yoyko/1de651f06da004a236e1f677b9507d43#file-ls-l-dev

The errors look similar to #4662 except that there's no crash mentioned there and the client version are different (it works for me with current stable, doesn't work with beta...)

I have the dump file mentioned in the logs, I can upload it somewhere if needed...

#### Steps for reproducing this issue:

1. Run steam
2. Turn on steam controller
3. Try to use the controller / look into logs

**Comment by maweil** [comment]
**My Client Information**
- Steam client version: 1484790260 (Jan 19 2017, at 01:23:20) (Steam client beta)
- Distribution: Fedora 25

The issue seems to be related to the _Generic Gamepad Configuration Support_.

As a temporary workaround, you can try to disable it in the Controller Settings.

After doing so, my steam controller works fine again both wireless and wired.

**Comment by mm1ke** [comment]
Hi,

I have a similar/same Problem.
My Controller doesn't work anymore with Steam. Last time i know it did work was 4 December.

**Your system information**

- Steam client version: 1489101908
- Distribution (e.g. Ubuntu): Gentoo
    
**Operating System Version:**

    "Gentoo Base System release 2.3" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.10.0-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11902000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

Steam also creates a crash dump every time i start it. However, except the controller, everything works.
I've also tried to:
* try different udev configurations
* steam --reset
* different user on same system

The controller only work if i start the sc-controller software. Steam then recognizes the Controller as a Xinput Controller.

Steam-Log: https://gist.github.com/mm1ke/edf9b78a03de2e1e10e49d4588bafda2

Some help would be appreciated.

**Comment by yoyko** [comment]
> The issue seems to be related to the Generic Gamepad Configuration Support.
> 
> As a temporary workaround, you can try to disable it in the Controller Settings.

Thanks! Yes, that works.

What does that option actually mean/do? I played only a couple of games (some with controller support such as XCOM, others with keyboard/mouse emulation) and the controller worked ok.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system and Generic Gamepad Configuration Support enabled?

**Comment by maweil** [comment]
> Hello, is anyone still experiencing this issue with an up to date system and Generic Gamepad Configuration Support enabled?

I just did a quick retest with _Shadow of the Tomb Raider_ (Native Linux) and _Monster Hunter World_ (SteamPlay). The Steam Controller works fine in both cases with all available Gamepad Configuration Support options enabled.

I'm using the latest Steam Client (1573780595) on Fedora 31 as operating system.

**Comment by kisak-valve** [comment]
Thanks for retesting @maweil, closing as fixed some time ago.
