### ISSUE TITLE
Can move selection past the rightmost option in big picture controller setup

### ISSUE THREAD

**Issue by yoyko** [ValveSoftware/steam-for-linux#4810]
#### Your system information

* Steam client version: 1482202200 (Dec 20 2016 02:18:40)
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No 
* Have you checked for system updates?: ???

#### Please describe your issue in as much detail as possible:
When assigning actions for controller inputs in Big Picture mode (Settings -> Base configurations -> Big Picture configuration) it is possible to move the selection to the right past the rightmost options (and it's not possible to move back afterwards)

#### Steps for reproducing this issue:

1. In Big Picture mode go to Settings -> Controller -> Base configurations -> Big Picture Configuration
2. Select any input to remap
3. On the "select  action" screen keep pressing Right until the selection moves past the rightmost option.

BTW the selection screen say "Select an in-game action" (and these are big picture mode actions)

**Comment by kisak-valve** [comment]
Hello @yoyko, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
