### ISSUE TITLE
No tray icon with elementaryOS 'Loki'

### ISSUE THREAD

**Issue by wilsenhc** [ValveSoftware/steam-for-linux#4812]
#### Your system information

* Steam client version: 148353539 (Jan 13 1027)
* Distribution (e.g. Ubuntu): elementaryOS 'Loki' 0.4 (Based on Ubuntu 16.04)
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES, everything up to date.
* Linux Kernel Version: 4.8.14-040814-generic x86_64 x86_64 GNU/Linux

#### Please describe your issue in as much detail as possible:
When closing the Steam main windows it doesn't minimize to tray, also there is no tray icon.

#### Steps for reproducing this issue:

1. Open Steam
2. Close main Steam Window. 
3. Client doesn't stay in the background

**Comment by kisak-valve** [comment]
Hello @WilsenHernandez, what desktop environment are you using?

If you completely close steam, with Steam -> Exit, then run `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal, does the tray icon appear with the steam client?

This issue is possibly related to #4795.

**Comment by WilsenHernandez** [comment]
No, tray icon doesn't appear when run as `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`

Might it be related to [this](http://elementaryos.stackexchange.com/q/4226)?

**Comment by kisak-valve** [comment]
Steam is using libappindicator built against gtk2 for the tray icon, so this your issue may be similar to http://elementaryos.stackexchange.com/questions/288/network-icon-gone-missing-in-wingpanel.

As a side note, you could use `STEAM_FRAME_FORCE_CLOSE=0` to make the close button act like the minimize button.

**Comment by kisak-valve** [comment]
After looking at this for a bit, it looks like this is an intentional design decision by the elementaryOS team to not support system tray icons in Loki.

**Comment by darealshinji** [comment]
Same or similar issue here on Ubuntu 16.04 with MATE 1.12.2 desktop environment.
When I close the window is doesn't minimize to the tray and it isn't visible anymore in the taskbar. But Steam is still running in the background.

Why can't minimizing to the tray be turned off in the settings anyway?

**Comment by kisak-valve** [comment]
Hello @darealshinji, you are most likely encountering #4795, not this issue.

**Comment by wilsenhc** [comment]
This issue has been fixed already.
Closed #4812
