### ISSUE TITLE
Windows steamapps on linux?

### ISSUE THREAD

**Issue by Firefly1029** [ValveSoftware/steam-for-linux#4814]
This may not be the place to ask but could I use my windows steamapps folder to run games on linux instead of reinstalling the game(s)?

Thanks and sorry for not really having an issue per se.

**Comment by kisak-valve** [comment]
Hello @Firefly1029, if a game already exists in steamapps/common, then steam will detect the existing files and reuse what it can, downloading only the difference between the platforms. Sharing the same steamapps folder between multiple installs of steam is not recommended.

As a side note, file permissions are not checked, so you need to make sure those are set properly.
