### ISSUE TITLE
Invalid pointer crash on startup

### ISSUE THREAD

**Issue by stertingen** [ValveSoftware/steam-for-linux#4815]
#### Your system information

* Steam client version: 1.0.0.54
* Distribution (e.g. Ubuntu): Arch Linux (Yeah, I know, not offically supported.)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Running ldd on the binary:
https://gist.github.com/stertingen/a521f63b8371249594c82e42ce1df00d

#### Please describe your issue in as much detail as possible:
Launching Steam on Arch Linux does not work, creating following console output: https://gist.github.com/stertingen/84849aa4626ced88727b9f30f886fc9e
I tried both runtime enabled and disabled (disabled = load native system libraries), scroll down to see the log with runtime disabled.

Dump for the crash (runtime enabled)
[assert_20170116101753_1.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/707719/assert_20170116101753_1.dmp.txt)
Renamed to .txt for upload reasons.
These files contain more information about my hardware. (CPU etc.)

Dump for the crash (runtime disabled)
[assert_20170116101430_1.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/707721/assert_20170116101430_1.dmp.txt)

#### Steps for reproducing this issue:
That's hard because on my Laptop, also Arch Linux, it works fine.

**Comment by kisak-valve** [comment]
Hello @stertingen,
Your assert appears to be outside of steam, maybe related to Mesa:
https://gist.github.com/kisak-valve/860c5a2256778c10db07382440c310ef

**Comment by stertingen** [comment]
Well, I tried different versions of Mesa, yesterday a new version of Mesa was released – still crashing. I'm running out ouf ideas.

Do you have any hints on debugging it by myself? (How did you process that memdump?)

**Comment by kisak-valve** [comment]
Steam uses breakpad by default. I have [minidump_stackwalk](https://www.chromium.org/developers/decoding-crash-dumps) from the chromium os, but you can use other debuggers with the `DEBUGGER` env variable like `DEBUGGER=gdb steam` Note: you will encounter SIGTRAP breakpoints that you need to tell gdb to continue.

**Comment by stertingen** [comment]
Thanks.

This issue seems unrelated to the video card; this looks very similar:
https://bbs.archlinux.org/viewtopic.php?id=219603 (and it looks like Nvidia GPU)

**Comment by bortloff** [comment]
@stertingen: Looks like someone screwed around with how the __STEAM_RUNTIME__ variable is handled between releases. I've updated [the relevant Arch Linux forum post](https://bbs.archlinux.org/viewtopic.php?pid=1694134#p1694134) with the following fix that I found from another issue logged here.

@kisak-valve: was this change anywhere in the changelogs for the newer Steam Linux client releases? I've been fighting this for weeks, and I'm incredibly annoyed at the upstream breakage of something working perfectly fine.

**Comment by bortloff** [comment]
Ah yes, can you add this to a workaround on #4768, @kisak-valve?

Also, could you please ask the Linux team to... put these changes into the changelogs?

**Comment by kisak-valve** [comment]
@bortloff, the original issue report predates the change to prefer system libraries over the steam runtime. Also, the change you are referring to is in the [changelog](http://store.steampowered.com/news/26953/) for the current steam stable client.

**Comment by bortloff** [comment]
Interesting that, because I didn't see it when the client was originally released, or worse, I trusted there to be some better warning and drunkenly just let it update. Also probably relied a little too heavily on the maintainer for the Arch package to be on top of it. Play with [rolling-release] fire, bound to get burned!

#4768 does, I'm sure, but this issue comes up quite a bit, and the workarounds are virtually nowhere to be found. Considering how thin the manpage is that I have available to me, I'd gander that it'd be the perfect place to add things like the workarounds in that issue. Heck, I may just make such a thing myself.

**Comment by morphex** [comment]
I had the ssfn error as well, then I tried some workarounds and got different issues.

What fixed it for me was downgrading the NVIDIA graphics driver from 384.90 to 375.82.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated. If anyone comes across this issue it will need a fresh evaluation.
