### ISSUE TITLE
Steam fails to start on new account because of outdated libxcb

### ISSUE THREAD

**Issue by lumag** [ValveSoftware/steam-for-linux#4816]
#### Your system information

* Steam client version: 1.0.0.5.
* Distribution (e.g. Ubuntu): Debian 9 stretch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:

Fresh install of steam does not start up:

```
lumag@lothlorien:~$ rm -rf .steam* .local/share/Steam/
lumag@lothlorien:~$ steam
Setting up Steam content in /home/lumag/.local/share/Steam
/home/lumag/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/lumag/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on debian  64-bit
/home/lumag/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/lumag/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
/home/lumag/.local/share/Steam/steam.sh: line 444: no match: ssfn*
lumag@lothlorien:~$
```

Steam installer presents EULA, then fails to start/download after accepting the license.

Removing `~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
` allows steam client to start downloading update package.

#### Steps for reproducing this issue:

1. Start with a fresh clean Linux account
2. Execute `steam`
3. Accept EULA
4. Fail

**Comment by kisak-valve** [comment]
Hello @lumag, there is an updated libxcb.so.1 in the steam beta client which was added in the [2017-01-05 beta update](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256).

**Comment by lumag** [comment]
@kisak-valve The problem is that the error happens before I'm able to opt-in to beta. It happens right after I first start steam in a new Linux account. No UI, nothing.

**Comment by kisak-valve** [comment]
Your choices should be to either LD_PRELOAD the 32 bit system variant of libxcb.so.1 or use `LIBGL_DRI3_DISABLE=1` to get steam fallback to DRI2, which is not affected by the bug in the older steam runtime bundled libxcb.so.1, then opt into the steam beta. When the next stable client update occurs, then this issue should be resolved.

If you are still experiencing this issue with the steam beta client, then we can investigate further.

**Comment by Plagman** [comment]
echo publicbeta > ~/.local/share/Steam/package/beta

**Comment by Tids** [comment]
@kisak-valve Thing is that this bug is fixed now in the steam client, but still there at the "installers" 

http://repo.steampowered.com/steam/pool/steam/s/steam/

The first run still needs to be without DRI3. We need an update of the "initial bootstraplinux_ubuntu12_32.tar.xz"-libs to make the fix work for everyone. So time to make a steam_1.0.0.55.tar.gz available.

**Comment by Tids** [comment]
Any news on this? This is now also a problem on Ubuntu 17

**Comment by osiyuk** [comment]
I have the same problem:
`.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds`

**Comment by oldgaro** [comment]
ffs even on Ubuntu they are having this issue. I think I will stick with either SteamOS or Windows to play...FCKKKKKK!

**Comment by phgachoud** [comment]
`LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam` worked for me...

**Comment by derTobsch** [comment]
I have the same problem with ubuntu 17.10 (gnome-shell, wayland) - the workaround from @phgachoud worked but a update would be great ;)

**Comment by kholyphoenix1** [comment]
Solved?

**Comment by birgersp** [comment]
Same problem here. Please elaborate how to apply this workaround @phgachoud, is that a command you execute in a terminal?

**Comment by yanickrochon** [comment]
fresh install of Manjaro 17. I dragged my /home partition from Debian, and Steam won't start for an unknown reason. Nothing that is suggested work, and I have no idea why.

**Comment by Tids** [comment]
@yanickrochon so maybe you're wrong here. Go to our manjaro forums at https://forum.manjaro.org and create a topic for this, set steam as tag, maybe also mark user Tids (me), and we'll look into that.

**Comment by rdnetto** [comment]
Running with `LD_DEBUG=libs` and grepping for `calling init.*xcb` makes it pretty clear what's going wrong:

    6075:        calling init: /home/reuben/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
    6075:        calling init: /usr/lib32/libxcb-dri2.so.0
    6075:        calling init: /usr/lib32/libxcb-glx.so.0
    6075:        calling init: /usr/lib32/libX11-xcb.so.1
    6075:        calling init: /usr/lib32/libxcb-sync.so.1
    6075:        calling init: /usr/lib32/libxcb-present.so.0
    6075:        calling init: /usr/lib32/libxcb-xfixes.so.0
    6075:        calling init: /usr/lib32/libxcb-dri3.so.0

We're using `libxcb` from the steam-runtime, but everything else comes from the distro since `libxcb-dri3`, etc. aren't present in the runtime. Based on that, the fix should be pretty simple - just add those libraries to the runtime.

**Comment by direc85** [comment]
Confirming. Running Steam with the command `LIBGL_DRI3_DISABLE=1 steam` didn't work for me (I think this is because I use "bleeding edge" X.org PPA, so just forget about it). Running the command @phgachoud posted `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' steam`, enabling beta channel and updating Steam fixes the problem.

**Comment by AngryPenguinPL** [comment]
Same issue today on fresh install Linux Mageia 6 x64 (spirit successor of Mandriva).

Issue at launch:

```
[x@localhost ~]$ steam
Repairing installation, linking /home/x/.steam/steam to /home/x/.local/share/Steam
Running Steam on mageia 6 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/x/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /lib/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
/home/x/.local/share/Steam/steam.sh: linia 444: brak pasującego: ssfn*
```
Fixed by launch with 

> LIBGL_DRI3_DISABLE=1 steam

After that steam download update and after this workaround with disable dri3 is not needed.

**Comment by udAL** [comment]
Same issue. 
Removing ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1 fixed it.

**Comment by TheBoneJarmer** [comment]
Removing ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1 fixed it for me as well. Using Ubuntu 17.

**Comment by kdkwiatkow** [comment]
Removing ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1 fixed it for me as well. Using Ubuntu 17.10 :)

**Comment by deejayingo** [comment]
Same for me, thank you kdkwiatkow!
For all that are not familiar with the terminal:
`sudo rm -r ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1`
All the best,
Igor

**Comment by kisak-valve** [comment]
@deejayingo, that file is owned by the regular user, so `sudo` is not needed, also, it's a single file, so the recursive `-r` is also not needed.

**Comment by ringofyre** [comment]
Playing devil's advocate here - I did "mv -v libxcb.so.1 libxcb.so.backup"

You only make an rm mistake once.

**Comment by bhartvigsen** [comment]
Can confirm this issue on latest Ubuntu. Hard to believe a massive product like Steam is currently completely 100% broken on the most-used Linux distro.

**Comment by Sergio2552** [comment]
Removing the file :
> ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
 works for me :+1: : , Im using MX Linux 17

**Comment by bluuman** [comment]
Same issue on ubuntu 17.10

```rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1```

fixes it.

**Comment by Fordi** [comment]
How is this still a problem on the public download?

**Comment by raki123** [comment]
Just installed the package from http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
using
dpkg -i steam_latest.dep
apt-get -f install (for dependencies)
and still got the same error
The fix using `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam` still worked for me

**Comment by okurz** [comment]
Now broken on the upcoming [openSUSE Leap 15.0](https://bugzilla.suse.com/show_bug.cgi?id=1085222) as well

**Comment by lagerspetz** [comment]
Same workaround works after upgrading to Ubuntu 18.04.

**Comment by retorquere** [comment]
So is the LD_PRELOAD or the removal of `libxcb.so.1` the recommended fix?

**Comment by Tids** [comment]
@retorquere whatever you want. You only need to do that one time, when after the first steam update there is no need for that workaround anymore.

**Comment by pesr0412** [comment]
On Ubuntu 18.04.1 LTS the issue still happens, so I used the fix that phgachoud put more than a year ago above:

LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam 

After that the GUI started to show and update happening and it seems it is working now.

**Comment by bhartvigsen** [comment]
Valve, what in the world is going on over there? Are you guys just asleep at the wheel or what? Why are you investing in new Linux development when your client can't even open?

**Comment by Plagman** [comment]
This should actually be fixed with version .55 of the Steam package; @pesr0412, is that what you were using? What's the output of `apt-cache policy steam-launcher`?

**Comment by pesr0412** [comment]
@Plagman I would define myself as someone who is not an experienced Linux user, hence my choice of Ubuntu latest stable version since it seems to be one of the most popular and so my thought was that when installing programs I would not run into issues, I downloaded and installed Steam around a month or two ago so I don't know how to obtain the version number, however based on the output of  the command you kindly gave I assume is .55, however this output is after I ran the other command I have stated so I'm not sure if that would have modified this output
steam-launcher:
  Installed: 1.0.0.55
  Candidate: 1.0.0.55
  Version table:
 *** 1.0.0.55 500
        500 http://repo.steampowered.com/steam precise/steam amd64 Packages
        500 http://repo.steampowered.com/steam precise/steam i386 Packages
        100 /var/lib/dpkg/status

**Comment by Plagman** [comment]
Thanks; this package version is intended to work out of the box on 18.04, but that's clearly not the case. To clarify, was your Steam install from 1-2 months ago not working for all that time, and the workaround you just applied let you use it for the first time?

**Comment by pesr0412** [comment]
yeah, it was from 1-2 months ago when I installed, tried and upon seeing nothing happening I just left it there until I recently decided to google the issue for solutions...

**Comment by prashant1rana** [comment]
> Same issue today on fresh install Linux Mageia 6 x64 (spirit successor of Mandriva).
> 
> Issue at launch:
> 
> ```
> [x@localhost ~]$ steam
> Repairing installation, linking /home/x/.steam/steam to /home/x/.local/share/Steam
> Running Steam on mageia 6 64-bit
> STEAM_RUNTIME is enabled automatically
> Installing breakpad exception handler for appid(steam)/version(0)
> /home/x/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /lib/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
> /home/x/.local/share/Steam/steam.sh: linia 444: brak pasującego: ssfn*
> ```
> Fixed by launch with
> 
> > LIBGL_DRI3_DISABLE=1 steam
> 
> After that steam download update and after this workaround with disable dri3 is not needed.

Worked for me too ....  Thnaks a lot.. 

Using OpenSUSE LEAP 15

**Comment by TTimo** [comment]
Please test this release candidate for 1.0.0.60 installer:

http://repo.steampowered.com/download/testing/steam-launcher_1.0.0.60_all.deb
`fc32d588a5b5fe04cd8d0781c6f934cf steam-launcher_1.0.0.60_all.deb`

It should work out of the box on ubuntu 18.04, several issues were addressed.

**Comment by TTimo** [comment]
steam-launcher 1.0.0.61 is officially out, assuming this issue is fixed, closing due to lack of feedback (feel free to comment and we'll reopen if needed).

**Comment by bhartvigsen** [comment]
And this two year saga has ended. Great job!

**Comment by jR4v** [comment]
Hi!
I encountered this problem on Puppy Linux based on Ubuntu 18.04, though as here indicated the problem was solved.
