### ISSUE TITLE
Steam hangs/lags when Yubikey inserted

### ISSUE THREAD

**Issue by hsanjuan** [ValveSoftware/steam-for-linux#4817]
#### Your system information

* Steam client version: Latest stable (2016-12-20) 1482202200 and beta
* Distribution (e.g. Ubuntu): OpenSUSE 42.2
* Opted into Steam client beta?: [Yes/No] Yes (happens in both beta and stable)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When starting steam and loading the store page with a Yubikey NEO plugged-in, steam hangs (or rather has a 6-7 second lag). At that moment, it prints:

`./steamwebhelper: symbol lookup error: /usr/lib64/opensc-pkcs11.so: undefined symbol: ENGINE_by_id`

Unplugging the Yubikey fixes the problem.

OpenSC package (providing `opensc-pkcs11.so`) is `opensc-0.13.0-6.5.x86_64`

#### Steps for reproducing this issue:

1. Plug Yubikey NEO
2. Start steam

**Comment by Plagman** [comment]
Can you explain how this setup works? Your setup must be moving libraries around when it's plugged in.

**Comment by hsanjuan** [comment]
There's no "moving libraries around". The Yubikey NEO is a smartcard and opensc-pkcs11.so is used for reading smart cards.

Why the steam store (or rather steamwebhelper) ends up using that library, and what it is trying to do with it is something I don't know and I was hoping someone would clarify. `ENGINE_by_id` seems part of libcrypto which is part of openssl. Have there been changes to these libs in the last weeks? To be honest, I have no idea how to dig up the real issue, but the fact is that problem's gone when Yubikey is removed.

**Comment by kisak-valve** [comment]
The most significant change in recent history that could be releated is "Improved interactions between the Steam runtime and host distribution libraries, which should let Steam work out of the box with open-source graphics drivers on modern distributions. If using an older distribution or running into problems, use STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 to revert to previous behavior." in the [2017-01-05 steam beta client](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/586991182161672256).

Maybe there is a subtle ABI compatibility issue going on here with preferring your system libraries over the steam runtime. `lddtree ~/.local/share/Steam/ubuntu12_64/libcef.so` should list all system libraries in use by steamwebhelper.

**Comment by kisak-valve** [comment]
Hello @hsanjuan, are you still experiencing this issue on an up to date system?

**Comment by hsanjuan** [comment]
No, don't think so.
