### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by Firefly1029** [ValveSoftware/steam-for-linux#4818]
#### Your system information

* Steam client version: latest
* Distribution (e.g. Ubuntu): ubuntu
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] no

#### Please describe your issue in as much detail as possible: I get low fps in cs go, I'm not sure if it's just because of linux. it is less then half what I get on wndows. I might be missing grpahics drivers but I'm not sure how to update. 
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) Expected to get normal fps, got much lower

#### Steps for reproducing this issue:

1. install csgo
2. launch
3. play
4. low fps?

**Comment by kisak-valve** [comment]
Hello @Firefly1029, general performance issues with CS:GO on linux is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1111.

As noted in that issue report, additional resources are needed compared to the windows client and video driver performance varies depending on driver vendor so performance parity is not really expected at this time with Mesa. You may have a better experience with updated drivers.
