### ISSUE TITLE
steam can't start since latest update

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#4820]
#### Your system information

* Steam client version:
* Distribution (e.g. Ubuntu): Debian unstable
* Opted into Steam client beta?: [Yes/No]  no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I get this:
~$ steam
Running Steam on debian  64-bit
STEAM_RUNTIME is enabled automatically
[2017-01-20 21:39:41] Startup - updater built Jan 19 2017 01:22:13
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

I tried STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 as suggested in the release notes for the update, but it didn't help.

**Comment by gbitzes** [comment]
This has been a longstanding issue also for me, even before the update. Until now, I was launching steam the following way:

    LD_LIBRARY_PATH="/usr/lib32/nvidia-367" steam

After the Jan 19 update the above command stopped working for me, and now I'm running this command instead:

    STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LD_LIBRARY_PATH="/usr/lib32/nvidia-367" steam

I'm running Ubuntu 16.10. (If you want to try the above commands, you'll need to change the paths if you have a different version of the nvidia driver, of course)

**Comment by kisak-valve** [comment]
Hello @mtmkls, what video card and driver are you using?

**Comment by mtmkls** [comment]
My video driver is radeonsi from Mesa 13.0.2. Meanwhile I also noticed that ~/.steam/error.log contains this:
```
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
/bin/bash: /home/miki/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
awk: /home/miki/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
Installing breakpad exception handler for appid(steam)/version(1484790260)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by kisak-valve** [comment]
One or more steam packaged libraries are too old to be used with your distro's build of Mesa. This is being tracked at #4768.

You could try to workaround this with: `LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6 /lib/i386-linux-gnu/libgpg-error.so.0' steam`

**Comment by mtmkls** [comment]
With `~$ LIBGL_DEBUG=verbose steam` I see in the error.log that
```
libGL: OpenDriver: trying /usr/lib/dri/radeonsi_dri.so
libGL: dlopen /usr/lib/dri/radeonsi_dri.so failed (/usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
```
Probably because it's `/usr/lib/i386-linux-gnu/dri/radeonsi_dri.so`

**Comment by kisak-valve** [comment]
Closing in favor of #4768.
