### ISSUE TITLE
Can't bring up overlay since the Jan 19 update

### ISSUE THREAD

**Issue by lowlyocean** [ValveSoftware/steam-for-linux#4827]
#### Your system information

* Steam client version: 1484790260
* Distribution (e.g. Ubuntu): Ubuntu 16.04, 64 bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When pressing Shift+Tab in game I expect to see Steam overlay and FPS counter. This was working fine before latest client update released on January 19th.

#### Steps for reproducing this issue:

1. Install Steam from apt on an up-to-date Ubuntu 16.04 64-bit system using nvidia-378 proprietary drivers
2. Make sure Steam -> Settings -> In-Game indicates that in-game overlay is enabled
3. Start any game (e.g., Counter-Strike: Global Offensive) and attempt to bring up the overlay using shortcut keys

**Comment by kisak-valve** [comment]
Hello @radical-equanimity, please copy the stdout log from either `/tmp/dumps/<username>_stdout.txt` or completely close steam, then run steam from a terminal and put in a gist. 

Does the overlay have a problem if you run steam a terminal with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`?

**Comment by radical-equanimity** [comment]
The overlay is still not accessible if I run with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam.

<script src="https://gist.github.com/radical-equanimity/070aefb9222acf7a4574410499c92cdf.js"></script>

**Comment by predr** [comment]
@kisak-valve Something has gone wrong with the update and Steam wasn't able to find correct libs after. @radical-equanimity was able to make Steam start but some libs might be still missing in action.
FYI http://steamcommunity.com/app/221410/discussions/0/143388344304227393/

**Comment by radical-equanimity** [comment]
@triage-valve @kisak-valve I have some more information. At the moment I launch CS:GO, I notice that .steam/error.log reports the following error:
`ERROR:` ld.so: object '/home/daniel/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored

Tried preloading the 64-bit version; the message in error.log goes away but I still can't bring up overlay or see my FPS.
`LD_PRELOAD='~/.steam/ubuntu12_64/gameoverlayrenderer.so' steam`

Has something recently changed with the way the overlay libraries are loaded on a 64-bit Linux machine?

**Comment by kisak-valve** [comment]
Steam preloads both the 32 bit variant and 64 bit variant of the overlay when starting a steam game. One works while the other harmlessly fails. This is not an indicator of a problem.

**Comment by radical-equanimity** [comment]
I understand, thank you. I've removed the .steam directory and installed the latest .deb from steampowered.com. After installing, I launched CS:GO. I've attached the output of "lsof -p <pid> | grep \.so" for the pids of the steam client as well as the Counter-Strike executable. The output of this command shows the shared libraries that are being accessed by each of those running processes, including their paths on the filesystem. Do you notice any combination of libraries that would cause the overlay to fail? Please let me know what else is needed- some game functionality relies on overlay to be working.

[loaded_libraries_overlay_issue.txt](https://github.com/ValveSoftware/steam-for-linux/files/737328/loaded_libraries_overlay_issue.txt)

**Comment by radical-equanimity** [comment]
This is odd- I ran a trace on gameoverlayui and it references something called WinAppMain. Has the Linux overlay been built using Windows source code, explaining the segfault shown here?
```
daniel@daniel-desktop:~$ ltrace -f  /home/daniel/.local/share/Steam/ubuntu12_32/gameoverlayui
[pid 11357] __libc_start_main(0x56630550, 1, 0xffbd3204, 0x566307c0 <unfinished ...>
[pid 11357] dlopen("libtier0_s.so", 2)           = 0
[pid 11357] dlopen("libvstdlib_s.so", 2)         = 0
[pid 11357] dlopen("gameoverlayui.so", 2)        = 0
[pid 11357] dlsym(0, "WinAppMain")               = 0
[pid 11357] dlclose(0 <no return ...>
[pid 11357] --- SIGSEGV (Segmentation fault) ---
[pid 11357] +++ killed by SIGSEGV +++
daniel@daniel-desktop:~$
```

**Comment by radical-equanimity** [comment]
Are these versions of the system C/C++ libraries (latest from Ubuntu 16.04) compatible with Steam?
```
daniel@daniel-desktop:~$ dpkg -l libstdc++6:i386 libgcc1:i386
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  libgcc1:i386                                  1:6.2.0-3ubuntu11~16.04     i386                        GCC support library
ii  libstdc++6:i386                               6.2.0-3ubuntu11~16.04       i386                        GNU Standard C++ Library v3

```

**Comment by radical-equanimity** [comment]
Are you able to reproduce this? What additional information can I provide? Waiting for reply

**Comment by kisak-valve** [comment]
Hello @lowlyocean, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
