### ISSUE TITLE
breakpad_linux assertion failed, leaving steam hanging

### ISSUE THREAD

**Issue by shaohme** [ValveSoftware/steam-for-linux#4830]
#### Your system information

* Steam client version: 1484790260
* Distribution (e.g. Ubuntu): Debian Stretch
* Opted into Steam client beta?: No 
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
After running steam in big-picture mode, from a terminal, exiting makes it hang. Last message is:
[2017-01-24 18:14:04] Shutdown
breakpad_linux.cpp (364) : Assertion Failed: m_bInitialized

#### Steps for reproducing this issue:

1. Open terminal
2. Start steam
3. Exit steam
4. Observe terminal output

**Comment by kisak-valve** [comment]
Hello @shaohme, are you still experiencing this issue on an up to date system?

**Comment by shaohme** [comment]
> Hello @shaohme, are you still experiencing this issue on an up to date system?

No, have not experienced it in a long time now
