### ISSUE TITLE
Problem with installing or updating Dota 2(missing update files)

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#4834]
Issue transferred from https://github.com/ValveSoftware/steam-runtime/issues/67.
@PenguiN560 posted on 2017-01-27T21:18:04:

Hello, have a problem with installing Dota 2 at Gentoo ~amd64. Other games installing and updating without any problems, for example Portal 2, Dont Starve Together and some other tested games. Steam support gave this link for send this problem and try to get your help.

What I try before:
1. Delete Dota 2 content from Steam, check clean in SteamLibrary folder and reinstall: fail
2. Check partition for errors - no errors, one more try to install: fail
3. Clear Download Cache, one more try to install: fail
4. $ steam --reset, one more try to install: fail
5. try to change region for downloading, one more try to install: fail
6. ???, one more try to install: fail
7. install from LiveUSB Ubuntu - ok. Reboot in my installed Gentoo - Success. It run and it work on my Gentoo, before came new update...
8. Try to update Dota2 on gentoo: fail...

So what libraries and what versions of it are needed for successful install or update Dota2, but not needed for other games, or what can be wrong? Repeat, all other games that i installed or updated are ok on my Gentoo. Problem detected only with missing update files Dota2

**Comment by kisak-valve** [comment]
Hello @PenguiN560, what filesystem are you installing Dota 2 onto when it fails?

**Comment by PenguiN560** [comment]
Hello @kisak-valve, ntfs, becouse i have Win10 as second system and main partition for games in ntfs. after ~12hours i can try to install dota2 on home ext4 partition if you think this can be problem, but as i wrote other games installing and updating on this ntfs SteamLibrary folder without any problems.

**Comment by kisak-valve** [comment]
Unfortunately, there is a known compatibility issue with the steam linux client updating games on ntfs which is being tracked at #4800. There is a known workaround at https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-271763278.

**Comment by PenguiN560** [comment]
Oh, sorry for duplication, thank you so much, I'll try it some later.

Hm, why it worked on Ubuntu LiveUSB? But i don't remember how i mount it ntfs partition >_<

**Comment by PenguiN560** [comment]
Looks like it's work for me. Dota 2 successful updated at my Gentoo in SteamLibrary on NTFS. Thank you

**Comment by kisak-valve** [comment]
Closing as a duplicate of #4800.
