### ISSUE TITLE
steam doesn't run TBOI 

### ISSUE THREAD

**Issue by AllanPamplona** [ValveSoftware/steam-for-linux#4854]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-1
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] Yes

When i launch TBOI i got this:
https://gist.github.com/AllanPamplona/de8d745a0ec1790ae39c28ef18f1d239

The last week everything was okay. Other games works (Dota2, Portal).
My graphic:
 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)

#### Steps for reproducing this issue:

1. Open from terminal for see the output.
2. Try to launch TBOI
3. See the terminal output.

**Comment by kisak-valve** [comment]
Hello @AllanPamplona, you should also reach out to the game devs. Additionally, the attached log does not appear to have any game specific info, perhaps this game logs to a separate log file?

**Comment by AllanPamplona** [comment]
@kisak-valve where can i find the game's log? I posted that  because in the last part shows an error.

**Comment by kisak-valve** [comment]
Sorry, I do not know where The Binding of Isaac keeps it's log off hand. If you are referring to the LD_PRELOAD messages, those are harmless and are unrelated to your issue.

**Comment by AllanPamplona** [comment]
But it only appear when i launch isaac, so, are they no related?

**Comment by kisak-valve** [comment]
When steam starts a game, it preloads both the 32 bit and 64 bit variant of the steam overlay. One silently works while the other fails harmlessly. This is unrelated to your issue.

**Comment by kisak-valve** [comment]
Hello @AllanPamplona, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
