### ISSUE TITLE
Steam client Ubuntu Unity appindicator missing all menu entries

### ISSUE THREAD

**Issue by o2r** [ValveSoftware/steam-for-linux#4861]
#### Your system information

* Steam client version (build number or date): 2/15/2017, 22:49:45
* Distribution (e.g. Ubuntu): Ubuntu 16.04.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The Steam appindicator formerly would contain a dynamically generated list of recently played titles, as well as the menu items selected under Interface>Taskbar Preferences.

Currently, the Steam appindicator has no menu items. Clicking Steam's appindicator icon brings up an empty menu, approximately 7 lines tall.

#### Steps for reproducing this issue:

1. Click on Steam appindicator
2. See the absence of a menu

**Comment by kisak-valve** [comment]
Hello @o2r, this issue is being tracked at #4795. There is a summary of the issue at https://github.com/ValveSoftware/steam-for-linux/issues/4795#issuecomment-271268063. Closing as a duplicate.
