### ISSUE TITLE
Steam browser is 125-150% scale in Dota2

### ISSUE THREAD

**Issue by artemjackson** [ValveSoftware/steam-for-linux#4863]
#### System information

* Steam client version (build number or date): steam 1.0.0.54-1
* Distribution: ArchLinux Kernel 4.9.8-1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected steam browser to be 100% scale. But the browser is 125-150% scale (see screenshots below) so content doesn't fit the page.

#### Steps for reproducing this issue:

1. Open Dota2 client
2. Visit any of news on main page

![screenshot from 2017-02-16 20-24-34](https://cloud.githubusercontent.com/assets/3768221/23032626/bb71800c-f47d-11e6-9591-e82fd0b92e9d.png)
![screenshot from 2017-02-16 20-24-29](https://cloud.githubusercontent.com/assets/3768221/23032631/bd8b8856-f47d-11e6-9184-444d1782e7e7.png)

**Comment by kisak-valve** [comment]
Hello @artemjackson, the issue you've described is in Dota 2, not the steam client. let's continue tracking this in the Dota 2 issue tracker at https://github.com/ValveSoftware/Dota-2/issues/1178.
