### ISSUE TITLE
failed to load steamui.so on Sparky Linux 64bit (debian testing)

### ISSUE THREAD

**Issue by galenthurber** [ValveSoftware/steam-for-linux#4864]
#### Your system information

steamui.so
distro: Debian Linux 4 64bit
nvidia driver: 375.26
xserver: 1.19.1 (11901000)
 Opted into Steam client beta? N
Have you checked for system updates?: Y

#### Please describe your issue in as much detail as possible:
start previously working steam gui

#### Steps for reproducing this issue:

1. start steam

#### attempted fixes

steam --reset

referring to
http://steamcommunity.com/app/221410/discussions/0/350542683198244989

```
STEAM_RUNTIME is enabled automatically
/bin/bash: /home/sparky/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
awk: /home/sparky/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc
Installing breakpad exception handler for appid(steam)/version(1484790260)
Installing breakpad exception handler for appid(steam)/version(1484790260)
Installing breakpad exception handler for appid(steam)/version(1484790260)
Installing breakpad exception handler for appid(steam)/version(1484790260)
[2017-02-17 10:12:50] Startup - updater built Jan 19 2017 01:22:13
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-02-17 10:12:50] Checking for update on startup
[2017-02-17 10:12:50] Checking for available updates...
[2017-02-17 10:12:51] Download skipped: /client/steam_client_ubuntu12 version 1484790260, installed version 1484790260
[2017-02-17 10:12:51] Nothing to do
[2017-02-17 10:12:51] Verifying installation...
[2017-02-17 10:12:51] Performing checksum verification of executable files
[2017-02-17 10:12:51] Verification complete
[2017-02-17 10:12:58] Shutdown
```

**Comment by kisak-valve** [comment]
Hello @galenthurber, do you happen to know what changed in the system between the last know working state and now?

One thing you could try is more aggressively using the steam runtime with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`.

**Comment by kisak-valve** [comment]
Testing note: No problem encountered with following https://wiki.debian.org/Steam on Debian 9 pre-release on a dual core atom / nvidia ion test system (nvidia 340.101).

@galenthurber, did you use the distro-provided steam package to install steam?

**Comment by ronny-valve** [comment]
As of February 2017 we are dropping all support for the linux kernel and moving over to the GNU Hurd kernel. I reccomend installing debian/hurd if you want to continue using steam on *nix.

**Comment by galenthurber** [comment]
repo.steampowered.com  (precise)
1.0.0.52-2 testing latest

support has responded again and notified me only Debian/HURD kernel will be support from now on

on this machine I can get Steam to run under Xubuntu 16.04 but not sparky debian

**Comment by kisak-valve** [comment]
Hello @galenthurber, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
