### ISSUE TITLE
Lost so much FPS if game lunched from steam

### ISSUE THREAD

**Issue by PenguiN560** [ValveSoftware/steam-for-linux#4865]
#### System information

* Steam client version (build number or date): 15.02.2017 22:49:55  1487202861
* Distribution (e.g. Ubuntu): Gentoo ~AMD64
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Hello. When I played some times in WarThunder from Steam, i set my settings and game give me 28 average FPS in ingame benchmark. But when i lunched it at this weekend I had get 15 average FPS. When i try to lunch WarThunder without steam by SteamLibrary/steamapps/common/War\ Thunder/launcher it give me 45 average FPS at the same settings. It was tested not one time, and it happend at this moment too. But I have a problem with some other steam games (eg. Dota2 or CS: GO), what can't be lunched without steam and had so low FPS at low settings.

#### Steps for reproducing this issue:

1. Run WarThunder from steam client
2. Run WarThunder manual from SteamLibrary without steam client
3. Compare FPS

PS: I tried lunch steam without steam runtime (STEAM_RUNTIME=0 steam), but steam wrote that can't connect to steam service, and give so much messages in console `appdatacache.cpp (2079) : Assertion Failed: !bSharedKVSymbols`. What libraries steamclient is needed and what version, and how to run steam client without steam runtime on native system libs? Or what can be problem with so low FPS in games lunched from steam insted of lunched without it?

**Comment by kisak-valve** [comment]
Hello @PenguiN560,
Running steam without the steam runtime is not supportable by Valve, however, on Gentoo you can use `USE="-steamruntime"` to pull in the additional dependencies to run steam without the steam runtime. Additionally, any issues with this configuration need to go to your package maintainer for steam, not here.

That said, does the terminal log at `/tmp/dumps/<username>_stdout.log` or completely closing steam, then running steam from a terminal give you any insight as to what's gone awry. The symptoms you describe hint at this being a steam runtime compatibility issue that is resulting in a library spamming a logfile somewhere.

**Comment by PenguiN560** [comment]
@kisak-valve, Thank you for recommendation about use flag, I'll try it.

Problem was in other place... after system update or steam update steam runned on discret NVIDIA video card don't start game on the same NVIDIA card(before it happend, I always started steam on NVIDIA and all games work on NVIDIA too). Atm I add to my games parameters `vblank_mode=0 optirun -b primus %command%`, and now I can run steam on intel but games will be run on NVIDIA.

**Comment by kisak-valve** [comment]
Glad to hear you figured out a working configuration. I'm going to close this issue report for now because there does not appear to be an actionable issue to address by a Valve dev with steam.
