### ISSUE TITLE
Indicator applet is showing no entries

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#4866]
#### Your system information

* Steam client version (build number or date): jan 19 2017
* Distribution (e.g. Ubuntu): ubuntu 16.04
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
I'm not getting anything in the indicator applet:

![workspace 1_006](https://cloud.githubusercontent.com/assets/110988/23106132/0eb0ca80-f6e9-11e6-9186-984a4c8dbe92.png)

#### Steps for reproducing this issue:

1. Just opening Steam causes it to be this way.
2. 
3.

**Comment by kisak-valve** [comment]
Hello @vadi2, this issue is being tracked at #4795 and has been summarized at https://github.com/ValveSoftware/steam-for-linux/issues/4795#issuecomment-271268063. Closing as a duplicate.
