### ISSUE TITLE
Watching 

### ISSUE THREAD

**Issue by Zerophase** [ValveSoftware/steam-for-linux#4868]
#### Your system information

* Steam client version: 1487202861
* Distribution (e.g. Ubuntu): Arch LInux Cinnamon desktop
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Playing game preview movies with the steam window docked to the right or left side of the screen, in full screen mode causes the video to play in the left hand corner of the full screen video. I think this should be playing in the center of the screen.

#### Steps for reproducing this issue:

1. Got to a game's page.
2. dock steam to the right or left of the screen
3. Play the video 
4. Enter full screen.

**Comment by kisak-valve** [comment]
Hello @Zerophase, this issue is already being tracked at #3699. Closing as a duplicate.
