### ISSUE TITLE
BPM crash after exiting a game

### ISSUE THREAD

**Issue by mlauss** [ValveSoftware/steam-for-linux#4871]
#### Your system information

* Steam client version (build number or date): 23.02.2017
* Distribution (e.g. Ubuntu): Gentoo/x64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

BPM crashes after exiting a game (e.g. "Mark of the Ninja")

Following backtrace from gdb/corefile:

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/mano/.local/share/Steam/ubuntu12_32/steam'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:51
51              cmpb %dh, (%eax)        /* is byte NUL? */
[Current thread is 1 (Thread 0xec292b40 (LWP 1369))]
(gdb) bt     
#0  __strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:51
#1  0xf7232efa in _IO_vfprintf_internal (s=0xec280fa0, format=0xedad6108 "[AppID %u] Failed to stop all item playtime tracking for AppID %u: %s (%s)", ap=0xec281568 "I")
    at vfprintf.c:1637
#2  0xf7255b2f in _IO_vsnprintf (string=0xec281120 "[AppID 214560] Failed to stop all item playtime tracking for AppID 3988164406:  (", maxlen=<optimized out>, 
    format=0xedad6108 "[AppID %u] Failed to stop all item playtime tracking for AppID %u: %s (%s)", args=0xec281558 " F\003") at vsnprintf.c:114
#3  0xf0f83dba in V_vsnprintf () from /home/mano/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#4  0xecd4cc15 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#5  0xecff1d36 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#6  0xecfd3320 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#7  0xecef9e64 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#8  0xed6da697 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#9  0xf0f7a410 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#10 0xf0f7b44e in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#11 0xf0f7b58f in Coroutine_Continue () from /home/mano/.local/share/Steam/ubuntu12_32/libvstdlib_s.so
#12 0xed6daba2 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#13 0xed6e056f in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#14 0xed6e0809 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#15 0xed6df138 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#16 0xed6b46d6 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#17 0xecd47740 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#18 0xecd48546 in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/steamclient.so
#19 0xf3d94e30 in SteamThreadTools::CThread::ThreadExceptionWrapper(void*) () from /home/mano/.local/share/Steam/ubuntu12_32/libtier0_s.so
#20 0xf3d9321b in ?? () from /home/mano/.local/share/Steam/ubuntu12_32/libtier0_s.so
#21 0xf3d934ef in CatchAndWriteMiniDumpExForVoidPtrFn () from /home/mano/.local/share/Steam/ubuntu12_32/libtier0_s.so
#22 0xf3d93541 in CatchAndWriteMiniDumpForVoidPtrFn () from /home/mano/.local/share/Steam/ubuntu12_32/libtier0_s.so
#23 0xf3d97ac1 in SteamThreadTools::CThread::ThreadProc(void*) () from /home/mano/.local/share/Steam/ubuntu12_32/libtier0_s.so
#24 0xf73a34fa in start_thread (arg=0xec292b40) at pthread_create.c:456
#25 0xf72d6286 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:110

#### Steps for reproducing this issue:

1. Run "Mark of the Ninja" in BPM
2. Exit the game
3. Watch Steam crash

**Comment by kisak-valve** [comment]
Hello @mlauss, are you still experiencing this issue on an up to date system?

**Comment by mlauss** [comment]
A quick test shows the problem no longer exists.
