### ISSUE TITLE
Steam linux Client Loading Workshop Content without Mentioned Libary Downloads

### ISSUE THREAD

**Issue by h1ght** [ValveSoftware/steam-for-linux#4875]
#### Your system information

* Steam client version (build number or date): steam package version 1484790260
* Distribution (e.g. Ubuntu): Debian Jessie, fglrx
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Steam is downloading Workshopcontent without any notification within the steamclient.
fix it pls. 
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Most likely not a linux-specific issue.

**Comment by kisak-valve** [comment]
Hello @h1ght, per "Fixed bugs preventing workshop items or newly installed DLC from showing up on the downloads page" in the [2018-04-02](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1658888566594367670) Steam beta client update, please opt into steam's beta and retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
