### ISSUE TITLE
View rotates 45 degrees to the bottom right on push-to-talk and sometimes on it's own

### ISSUE THREAD

**Issue by ifohancroft** [ValveSoftware/steam-for-linux#4876]
#### Your system information

* Steam client version (build number or date): Feb 232017, at 00:38:08
* Distribution (e.g. Ubuntu): Fedora 24 x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While in-game when I press the push-to-talk button (no matter if it's bind to a mouse or a keyboard button) besides the input from my mic being send in-game, my view rotates about 45 degrees to the bottom right. I expect the input from my mic to be send in-game without my view rotating. If I press it again, right after it happened, it won't happen again. It seems to be happening either after a longer period of time if pressed again or after a certain event (or both).
Also, at times the view rotates the same way on its own, without pressing push-to-talk. I thought it may be lag peak but I've noticed it rotates to the same direction by the same amount that it also does when pressing push-to-talk.

I have just tested on Windows with bots in Competitive and it doesn't happen there.

#### Steps for reproducing this issue:

1. Launch CS:GO
2. Start a game
3. Play a little and press the push-to-talk button.
OR
3. Play a little (the view will just rotate on its own (mostly noticed it when going cat to short on Dust ii))

**Comment by kisak-valve** [comment]
Hello @ifohancroft, let's track this issue on the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1330.

**Comment by ifohancroft** [comment]
The issue is present again but only happens randomly. I've noticed it today.
