### ISSUE TITLE
Change language of games isn't working

### ISSUE THREAD

**Issue by tr0n0s** [ValveSoftware/steam-for-linux#4879]
#### Your system information

* Any Steam client version until today (01/03/2017)
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Tried with both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I can't change the language on Steam for Linux, tried on multiple Ubuntu machines. (My language is Spanish). Tried with CSGO, ARK, and more games...

#### Steps for reproducing this issue:

1. Right click on any game
2. Click on Properties
3. Go to the Language tab, change it and Accept.

**Comment by kisak-valve** [comment]
Hello @tr0n0s,
This issue needs to be addressed on a per game basis. The CS:GO issue report for this issue is at https://github.com/ValveSoftware/csgo-osx-linux/issues/705 and you should bring this to the attention of an ARK game dev.
