### ISSUE TITLE
Add option to disable guide button hijacking

### ISSUE THREAD

**Issue by LinAGKar** [ValveSoftware/steam-for-linux#4885]
Pressing the guide button on a controller will bring up Steam, even if you're doing something completely different, and pressing the guide button while Steam is in the foreground will open Big Picture. This is extremely annoying, and conflicts with literally anything else using the guide button.

**Comment by Plagman** [comment]
Go into "Controller settings" in Big Picture and disable "Guide Button Focuses Steam".

**Comment by LinAGKar** [comment]
That should be under the normal settings, since it affects steam outside of Big Picture. It doesn't even affect Big Picture at all.

**Comment by tatsujb** [comment]
@Plagman  this is a bug repport. you're not taking the fact that this is a bug report into account on a bug report place...

doing what you say does basically nothing. it does not work.
