### ISSUE TITLE
Steam controller via in-home streaming: Configs broken

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#4888]
Issue transferred from https://github.com/ValveSoftware/portal2/issues/277.
@b3nn0 posted on 2017-03-06T20:58:26:

Hi,
I'm trying to play Portal 2 via in-home streaming with my steam controller. Host and client are both Linux.
I don't have a Windows machine to double check if the issue exists there.

General procedure seems to work. When I select one of the "Configuration Templates" for the steam controller config, things seem to work mostly (well, the configs are bad, but they work).

However, when I select e.g. Valve's recommended steam controller config (or one of the community configs), the input isn't recognized.

The main difference I noticed (and this is why I report it as a Portal bug - even though I'm not sure if that's 100% correct, might also be a steam controller API bug. Please forward it to the respecitve team in that case) is:
While the config templates use a generic gamepad mapping (i.e. button X mapped to gamepad button X, button Y mapped to gamepad button Y, etc), the community/Valve configs seem to be aware of the game's capabilities. In the controller config overlay, the buttons are mapped to their actions (e.g. X = jump, Y = crouch, ...). However, this doesn't seem to work at all - input is not recognized.

***
@kisak-valve commented on 2017-03-06T22:07:08

Hello @b3nn0, as far as I can tell this issue is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/3786. Closing in favor of that issue report.

***
@b3nn0 commented on #3786 on 2017-03-07T11:50:15

Alright, so my issue I reported on Portal 2 was closed and referenced to this one.
Personally I don't think it's the same issue. Controller data is transferred just fine. It's just a matter of the bindings that are wrong.

I also just tried with using Windows as an in-home-streaming host and it shows the same issue:
Using the controller configuration templates works fine, the steam controller overlay works, but using the recommended or community configs that map buttons to actions (X=crouch instead of X=gamepad X) doesn't work.

Tested configs:
Linux host (Steam beta) + Linux client (Steam beta)
Linux host (Steam stable) + Linux client (Steam stable)
Windows host (Steam beta) + Linux client (Steam beta)

Note: This report is very old and seems to be mostly ignored. As my other report was closed referencing to this one, I will be as helpful (and also as annoying) as needed to get this fixed. I bought two Steam controllers to play games in my living room via streaming. For now, that does not work, so the product is completely useless for me right now, which is unacceptable for the > 100€ spent.

**Comment by b3nn0** [comment]
Bug still exists in latest beta. Also when streaming from Windows.

**Comment by Mernst1** [comment]
Can confirm this bug. Have the same problem.
All games with custom mappings doesnt work.
Only in In-Home-Streaming. PS4-Xbox360 or Steam-Controller.

**Comment by b3nn0** [comment]
For me, the bug was actually fixed in one of the last Steam Beta releases.
You might want to make sure that you use Steam beta and also that you are running big picture mode on the client machine when starting the game.

**Comment by Mernst1** [comment]
Okay sorry my fault. Tried it again and with the Steam Controller it does really work.
But with PS4 in Steam Controller Mode it doesnt.
Sorry for the mistake.

**Comment by kisak-valve** [comment]
@b3nn0 glad to hear this is working for you now.

@Mernst1, if #4689 does not cover your issue, please open a new issue report for the DS4 controller issue.

Closing per the last few comments.
