### ISSUE TITLE
Steam can open multiple applications at the same time

### ISSUE THREAD

**Issue by ClayHanson** [ValveSoftware/steam-for-linux#4892]
#### Your system information

* Steam client version (build number or date): Mar 9 2017, at 22:27:47
* Distribution (e.g. Ubuntu): Ubuntu 14.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

What I expected to happen:
1. Open a game (any game; I used Half-Life 2)
2. Open another game while Half-Life 2 is running
3. It wouldn't run because Steam can only show the name of one game you are playing

What actually happened:
1. Opened a game (Again, I used Half-Life 2)
2. Opened another game while Half-Life 2 was running, and it opened. I can run as many games as I want at the same time, it seems
3. Lag out my computer because I accidentally opened multiple games, which is how I discovered this bug

And yes, the games were opened via the Game Library. Link to a photo of it:
http://i.imgur.com/WIr0xqM.png

**Comment by kisak-valve** [comment]
This behavior is consistent with steam on other platforms and is intended for single player games.
