### ISSUE TITLE
streaming: out of memory (1610612736b), HD to 4k

### ISSUE THREAD

**Issue by Mirarkitty** [ValveSoftware/steam-for-linux#4895]
#### Your system information

* Steam client version (build number or date): Mar 15, 2017, 23:45
* Distribution (e.g. Ubuntu): Linux Mint 18.1
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The streaming client reports a lot of 
```
***** OUT OF MEMORY! attempted allocation size: 1610612736 ****
***** OUT OF MEMORY! attempted allocation size: 1610612736 ****
```

I stream from a HD windows client (1920x1080) to a 4k (3840x2160) Linux.

Eventually the streaming client dies; uncertain if it's related.

I suspect this might be correct and the problem is that the streaming client is running on 32 bit so it actually runs out of address space, albeit 1.6GB is quite a lot. The client machine has 16GB RAM (at least 6GB completely unused) + swap, so if the client would use 64 bit it would be able to allocate this memory.

#### Steps for reproducing this issue:

1. Stream from HD windows to Linux 4k.

**Comment by kisak-valve** [comment]
Hello @Mirarkitty, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
