### ISSUE TITLE
Verifying integrity of game files will cause those game files' update files to be corrupt

### ISSUE THREAD

**Issue by ClayHanson** [ValveSoftware/steam-for-linux#4897]
#### Your system information

* Steam client version (build number or date): Mar 13 2017, at 20:56:36
* Distribution (e.g. Ubuntu): Ubuntu 14.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:

I honestly don't know why this is happening; Please refer to the steps down below on how to reproduce it, though. I'm not too sure on what the 'Verify integrity of game files' button actually does, but on Windows it usually fixes some dumb problems. Apparently on Linux it just causes more problems.

#### Steps for reproducing this issue:
1. Download a game. Any game, it seems; I encountered the problem with Garry's Mod and then tested it with The Escapists.
2. After the game is done installing, immediately use the 'Verify integrity of game files...' button from the game's properties menu. It will then say that a bunch of files failed to validate, despite having just downloaded a fresh copy of the game.
3. The game then proceeds to re-install itself, and when it reaches 100%, it will pause the download, and will only sometimes say that there were corrupt update files. When you resume the download, it will begin at 0%. This is seemingly permanent, too.

#### What methods I've tried to fix this bug
+ Restart Steam
+ Restart computer
+ Clear download cache
+ Delete the entire Garry's Mod folder

#### 'Special' installation notes
+ I am using a built in harddrive to install my games to. The filesystem of that hard drive is NTFS. The filesystem of the drive I'm booting Steam off of is ext4. The ext4 drive is also what I'm using to live-boot Ubuntu. It has 32 GB of persistent space.

**Comment by kisak-valve** [comment]
Hello @ClayHanson, the issue with corrupt game updates on NTFS is already being tracked at #4800. There is a possible workaround in that issue report. Closing as a duplicate.
