### ISSUE TITLE
exploring steam queue does not work

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#4898]
up-to-date beta steamOS
up-to-date beta steam client (big picture)

When exploring my queue:
 - I can get windows only games.
 - I get very quickly an error when jumping to next game, blocking the exploration.

**Comment by kisak-valve** [comment]
Hello @sylware, the first bullet point is being tracked at #4500 and the second bullet point is a general steam web services issue, not OS-specific.

**Comment by sylware** [comment]
seems fixed.
