### ISSUE TITLE
games dont grab (input)focus properly on launch

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/steam-for-linux#4899]
#### Your system information
* Steam client version (build number or date): 1489791860
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I am playing on my steamlink but this issue is not isolated to BPM/streaming.
Some games on launch fail to grab focus from steam/BPM.
Terraria: no visual focus but input focus.(game is windowed though)
Rocketleague: visual focus but no input focus (and desktop cursor is visible)
Binding of isaac: visual focus but no input focus
Portal2: visual focus AND input focus.
Etc.

Focus grabbing prevention turned OFF on KDE.
With physical access to desktop i can grab focus to the game.

Very annoying bug and discouraging to play games via my desktop...

**Comment by kisak-valve** [comment]
Possibly SDL related, assigning to the SDL dev. Some of these games bundle SDL, so the individual game devs may need to contacted after this is figured out.

**Comment by cjwijtmans** [comment]
Would like to add that i dont have SDL installed on my system.

**Comment by cjwijtmans** [comment]
Also when i press i press the steam button on the controller i see the steam overlay in the game and i have input focus but when i close the menu again no input focus in the game.

**Comment by Uramekus** [comment]
@cjwijtmans can you still reproduce that? cant reproduce on my i3wm setup, its surely WM dependent

**Comment by cjwijtmans** [comment]
Dont have a desktop gentoo box atm so afraid not.

**Comment by kisak-valve** [comment]
Closing per the last comment.
