### ISSUE TITLE
Steam recent font change causing several issues

### ISSUE THREAD

**Issue by JacobSvenningsen** [ValveSoftware/steam-for-linux#4900]
#### Your system information
* Steam client version (build number or date): Mar 17 2017, at 22:24:06
* Distribution (e.g. Ubuntu): Debian 9
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Sometime during the last few hours, the font changed for the steam browser which has caused several issues when it comes to kerning. Have a look at http://pix.toile-libre.org/upload/original/1489858237.png
The amount of kerning between two f's is just unacceptable. The same issue applies for two v's, which becomes almost indistinguishable from w.
Another issue this recent change seems to have added, is lack of spacing between elements, which can be seen in the steam settings window for Steam in-home streaming http://pix.toile-libre.org/upload/original/1489861673.png

This issue didn't appear with a steam client update, seeing it went from working fine to being broken without restarting the client.

#### Steps for reproducing this issue:
1. Open up the steam browser
2. Go to any community page
3. Look for a reply with a word such as "offer", or write ff in the reply-field

**Comment by kisak-valve** [comment]
Hello @JacobSvenningsen, please open a separate issue report for the layout issue in the settings window so that can be tracked properly.

**Comment by kisak-valve** [comment]
Hello @JacobSvenningsen, are you still experiencing this issue on an up to date system?

**Comment by JacobSvenningsen** [comment]
I don't. Can no longer reproduce it on any system
