### ISSUE TITLE
Lack of spacing between elements in the Steam Settings Window

### ISSUE THREAD

**Issue by JacobSvenningsen** [ValveSoftware/steam-for-linux#4901]
#### Your system information
* Steam client version (build number or date): Mar 17 2017, at 22:24:06
* Distribution (e.g. Ubuntu): Debian 9
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The lack of spacing can be seen here; http://pix.toile-libre.org/upload/original/1489861673.png

#### Steps for reproducing this issue:
1. Open the Steam Settings Window
2. Go to "In-Home Streaming" settings menu

**Comment by kisak-valve** [comment]
Hello @JacobSvenningsen, are you still experiencing this issue on an up to date system?

**Comment by JacobSvenningsen** [comment]
No. Can no longer reproduce the issue
