### ISSUE TITLE
make tux buyable

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/steam-for-linux#4903]
I badly want one of those [tux](https://wiki.teamfortress.com/wiki/Tux) but they cant be traded or bought

I only play on linux and missed the window to get them. I dont mind paying for them! Let me give you my money god damned!

**Comment by kisak-valve** [comment]
Transferred to Source-1-Games.

**Comment by voidplayer** [comment]
[thanks!](https://github.com/ValveSoftware/Source-1-Games/issues/2204)
