### ISSUE TITLE
Team Fortress 2 freezes while trying to load world

### ISSUE THREAD

**Issue by furycd001** [ValveSoftware/steam-for-linux#4904]
HI Guys

TF2 on my laptop has stopped working as of the most recent update. The game loads fine (maybe a bit slower than before) and I can access and play with all the menus. The problem is whenever I try to launch a game mode either online or offline it freezes while trying to load the world. How can I fix my TF2 install and start playing the game again :? My specs are listed below. Many thanks in advanced for your help and time...

**OS:** Ubuntu 16.04
**GRAPHICS:** NVIDIA C79 GeForce 9400M G / http://i.imgur.com/jRPz0y8.png
**CPU:** Intel Core2 Duo CPU P7350 @ 1.995GHz
**GPU:** Gallium 0.4 on NVAC - RAM: 631MiB / 1744MiB
**STEAM CLIENT:** Newest release with all updates installed.

STEAM + TF2 RUN FROM TERMINAL PRODUCES THIS http://paste.ubuntu.com/24210348/

**Comment by kisak-valve** [comment]
Hello @furycd001, issue transferred to the Source-1-Games issue tracker.
