### ISSUE TITLE
undefined symbol: udev_device_new_from_syspath with Dota 2 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by wyqydsyq** [ValveSoftware/steam-for-linux#4906]
#### Your system information

* Steam client version (build number or date): `1.0.0.54-16.2`
* Distribution (e.g. Ubuntu): `OpenSUSE Tumbleweed`
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've been able to play Dota 2 on OpenSUSE TW for the last year or so thanks to [boombatower](https://github.com/boombatower)'s repo posted in https://github.com/ValveSoftware/steam-for-linux/issues/4537 until the last 2 weeks where it hasn't launched, giving this error instead:
![image](https://cloud.githubusercontent.com/assets/621277/24191720/52ae63f2-0f38-11e7-8106-ea125da98867.png)

I've got everything up to date, I've tried switching to the official steam package from the OpenSUSE repos, tried changing from OpenGL to Vulkan, and tried booting to an older kernel `4.9.x` from `4.10.x` to no avail. Most of my other Linux-native games on Steam run just fine still.

Gist: https://gist.github.com/wyqydsyq/a7c0854e2da778812006b2c9eb9e0b80

I've pasted some relevant errors that appear in my terminal below:
```
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 9519 != 9518, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Generating new string page texture 276: 128x256, total string texture memory is2.91 MB
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

```

ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/damon/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

**Comment by kisak-valve** [comment]
Hello @wyqydsyq, please copy the console spew from Dota 2 trying to start and put it in a [gist](https://gist.github.com/). This can be found in `/tmp/dumps/<username>_stdout.txt` or completely closing steam, then running steam from a terminal.

**Comment by wyqydsyq** [comment]
I've pasted the console output of running Steam with this error occurring in the gist below:
https://gist.github.com/wyqydsyq/a7c0854e2da778812006b2c9eb9e0b80

**Comment by kisak-valve** [comment]
So, the actual error message from the log is `failed to dlopen "librendersystemgl.so" error=/home/damon/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemgl.so: undefined symbol: udev_device_new_from_syspath`

**Comment by wyqydsyq** [comment]
```
 ~  zypper if libudev0-shim
Loading repository data...
Reading installed packages...


Information for package libudev0-shim:
--------------------------------------
Repository     : @System
Name           : libudev0-shim
Version        : 1-6.4
Arch           : x86_64
Vendor         : obs://build.opensuse.org/home:boombatower
Installed Size : 7.8 KiB
Installed      : Yes
Status         : up-to-date
Source package : libudev0-shim-1-6.4.src
Summary        : Dynamic library to access udev device information
Description    :
    This package contains the dynamic library libudev, which provides access to
    udev device information

```

**Comment by wyqydsyq** [comment]
I'm still having this issue with latest versions of Steam and OpenSUSE.

@boombatower have you had any luck running Dota with steamtricks and your shim? I have both installed but no luck.

**Comment by wyqydsyq** [comment]
I haven't been able to reproduce this in the last few months, appears to be resolved.
