### ISSUE TITLE
Blank login window

### ISSUE THREAD

**Issue by Kubuxu** [ValveSoftware/steam-for-linux#4910]
#### Your system information

* Steam client version (build number or date):  recent, no idea how to check
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When starting Steam only thing I get is "invisible" (in color of previous foreground) login window. I can move it around and it will sometimes change the color to other foreground.
![](https://ipfs.io/ipfs/QmWdDm3va9uGXoRfvgVvnn9mSknfbkstGZKT5v4p4sCXYv/image.jpg)
Logs:
```
/home/kubuxu/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/kubuxu/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/kubuxu/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Installing breakpad exception handler for appid(steam)/version(1490228413)
Generating new string page texture 12: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311.30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442.37 KB
```

#### Steps for reproducing this issue:

1. Install steam `sudo pacman -S steam`
2. Start steam with `steam`.

**Comment by kisak-valve** [comment]
Hello @Kubuxu, what your screenshot is showing in your screenshot is an uninitialized X window. What video card and driver version are you using? Can you verify you have a sane opengl driver with glxgears or glxinfo?

**Comment by kbrenneman** [comment]
I'm running into the same behavior on Mint 18, using MATE desktop, running on a GTX 1060 with version 375.39 of the NVIDIA driver.

glxinfo prints everything that I'd expect, and every other GLX application I've tried so far seems to work correctly.

I get the same results with different window managers, and with and without compositing.

Also, if I force it to use indirect rendering (but still on the same local X server), then it displays correctly.

**Comment by kbrenneman** [comment]
One other thing just occurred to me: This problem only started on my system after a CPU upgrade. Combined with the fact that indirect rendering works okay, that might point to a synchronization problem between X and GLX.

**Comment by Kubuxu** [comment]
Can you try starting `glxgears32`. It is black for me also.

**Comment by kbrenneman** [comment]
Ah, you're right. A 32-bit build of glxgears is solid black. I'm not sure if that's from the same problem as the steam client, though.

**Comment by Kubuxu** [comment]
I think they are.

**Comment by Leopard1907** [comment]
Can you try that workaround?

https://github.com/ValveSoftware/steam-for-linux/issues/4792

**Comment by kisak-valve** [comment]
Also encountered in #4846.

**Comment by Kubuxu** [comment]
@kbrenneman I might be it. I will be back home in a week I will check it. If it is it, thank you a lot.

**Comment by Kubuxu** [comment]
Disabling 'Above 4G Decoding' have resolved it.

**Comment by Kubuxu** [comment]
Disabling 'Above 4G Decoding' have resolved it.
