### ISSUE TITLE
CS:GO window squashed on restore fullscreen window

### ISSUE THREAD

**Issue by yami-kage** [ValveSoftware/steam-for-linux#4911]
#### Your system information
As reported by Steam's [System Information](https://pastebin.com/Y4yANezY)
* Steam client version (build number or date): March 24 - Steam Client Beta Update - March 23
* Distribution (e.g. Ubuntu): Linux Mint 18.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since I changed my left and right monitors to be rotated counter clockwise (tall) I have been having a problem with CS:GO.
The game is running on my primary (middle) monitor at normal rotation. All three monitors are of the same model and configured identically except for the orientation.

When the window loses focus from fullscreen it minimizes as expected, but then becomes distorted as in [this screenshot](https://steamuserimages-a.akamaihd.net/ugc/84847250221266098/489B9CB881E4B5EABDD0B153049CFE93D74165E9/)
This is not visible when taking a screenshot using the steam overlay (looks as if the screen was normal).
The mouse is restricted to a small portion of the monitor in the top left corner and the only work around I have found is to move the window to the left or right monitor (which enables regular mouse control, but the screen is distorted as in [this screenshot](https://steamuserimages-a.akamaihd.net/ugc/84847250221269253/1D446C8DEE303386832CCBD1A85F449CDE30B086/)) then changing video settings to windowed mode, moving it to center monitor and finally changing settings to fullscreen again.

The issue is not present when using windowed mode, but then the performace suffers too much to use it because of my distro's compositor muffin (a mutter fork, based on clutter).

If there is any more information I can provide, please let me know.

#### Steps for reproducing this issue:

1. Rotate Left and Right monitors clockwise to vertical orientation, Center monitor not rotated.
2. Set CS:GO to run in fullscreen on center monitor
3. Lose window focus
4. Restore window

**Comment by kisak-valve** [comment]
Hello @yami-kage, let's track this issue in the CS:GO issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1362.
