### ISSUE TITLE
Steam Controller: Mouse back and forward is mapped incorrectly on Linux

### ISSUE THREAD

**Issue by trygveaa** [ValveSoftware/steam-for-linux#4912]
#### Your system information

* Steam client version (build number or date): Mar 22 2017
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The buttons for mouse back (labeled 4 in Big Picture) and mouse forward (labeled 5) in the desktop Configuration for the Steam controller sends the wrong button events. It sends button 6 for back and button 7 for forward, while normal mouses sends 8 for back and 9 for forward. This can be checked with [xev](https://www.x.org/archive/current/doc/man/man1/xev.1.xhtml). This is general for all Linux distributions, not specific for Arch Linux. See e.g. [here for Ubuntu](https://ubuntuforums.org/showthread.php?t=1957300&p=11839258#post11839258), which lists:

```
# b:1  -  left mouse button
# b:2  -  wheel button
# b:3  -  right mouse button
# b:4  -  mouse wheel up
# b:5  -  mouse wheel down
# b:6  -  mouse wheel left
# b:7  -  mouse wheel right
# b:8  -  back side button
# b:9  -  forward side button
```

#### Steps for reproducing this issue:

1. Map mouse back and mouse forward to buttons on the Steam Controller for the desktop configuration (e.g. the default desktop configuration).
2. Go to a web page in a separate browser (not the browser inside Steam).
3. Press one of the mapped buttons.

Expected result:
The web browser should go back or forward one page.

Actual result:
The web browser scrolls left or right.

**Comment by kisak-valve** [comment]
Per "Fixed Linux mouse button assignments for Forward and Backwards" in the [2017-05-08](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1303074557798719943) steam client beta, please opt into the beta and retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
