### ISSUE TITLE
Steam Controller non-functional ONLY when streaming from Windows

### ISSUE THREAD

**Issue by halferuga** [ValveSoftware/steam-for-linux#4923]
* Steam client version: Mar 22 2017, at 23:45:04
* Distribution: Ubuntu 16.10
* Opted into Steam client beta: No
* Have I checked for system updates:  Yes

#### Steps for reproducing this issue:

1.  Launch Steam
2.  Connect the Steam Controller
3.  Launch a Stream from a Windows machine

#### A better explanation of the issue
My Steam Controller works fine in desktop mode when Steam is running, **works fine in BP**, **works fine when playing a native game**; but when launching a Stream from my Windows machine, no input is sent through to the host. The Host shows the Controller as connected (the notification pops up, the configuration is there), but no inputs go through. While the stream is going, **I can use KB+M to control the game**, and I can use the Steam Controller in BP and desktop (alt-tabbing using the controller works, for example) - so it's basically **_just the stream_ that's not working.** 
Also, Xbox 360 controllers work with no issues.

#### The most important thing:
Disconnecting the controller and then reconnecting it _whilst the stream is active_ results in ~0.5 seconds of normal behaviour, after that the controller is dead again. To reiterate: **disconnecting then connecting the controller makes it work for 0.5 seconds**, then it "dies" again.

#### Logs:
[Parts of the log](https://gist.github.com/halferuga/6bd4016e3a05b33ad3dc8364ab3139c6) I thought are relevant to the issue

This is what shows up when I [disconnect/connect the controller as mentioned above](https://gist.github.com/halferuga/a915ba78bed9c1f3735af134b43c505d)

#### What I tried already:
* Updating to 16.10 from 16.04.
* Purging Steam
* Checking udev rules
* Playing wired
Initially I was on 16.04, and this issue appeared about 2 weeks ago. Today I tried updating to 16.10, purging all Steam related packages, then installing Steam again, but this time also installing the package "steam-devices". This rendered the controller completely dead (so the udev rules the package provides do not do a thing), so I used the rule provided [in the official guide](https://steamcommunity.com/app/353370/discussions/0/490123197956024380/), which got me back at square one

**Comment by halferuga** [comment]
So I just updated to 17.04 and the issue seems to be gone? Not sure if it's the recent Steam client update that did it, or the OS upgrade, though

**Comment by kisak-valve** [comment]
Glad to hear it's working now, if if someone happens to find a way to reproduce this issue, we can reopen this issue. Closing.
