### ISSUE TITLE
gdebi steam_latest.deb doesnt work

### ISSUE THREAD

**Issue by nebulousdog** [ValveSoftware/steam-for-linux#4929]
gdebi steam_latest.deb doesnt work, but apt-get does

* Steam client version (build number or date): `steam_latest.deb`
* Distribution (e.g. Ubuntu): `Ubuntu 16.04.1 LTS`
* Opted into Steam client beta?: [Yes/No] no?
* Have you checked for system updates?: [Yes/No] yes

I downloaded the `steam_latest.deb` and ran `gdebi steam_latest.deb` to install. The launcher proceeded to install a bunch of stuff and gave me a desktop icon and item in the dropdown menu, however clicking it didnt do anything. Running `ps -ef | grep steam` revealed there were as many steam processes as the times I clicked the icon, but nothing happened. I purged steam from my computer and then did `sudo apt-get install steam` and this worked. I did get a "its not safe to reset steam, couldnt find bootstrap message, contact technical support", but it seemed to work anyway. thanks!

**Comment by kisak-valve** [comment]
Hello @nebulousdog, are you still experiencing this issue on an up to date system?

**Comment by nebulousdog** [comment]
thanks for checking in @Plagman, you can close this if you wish. I've been using the Aptitude method ever since.

**Comment by kisak-valve** [comment]
Closing per the last comment.
