### ISSUE TITLE
 Counter Strike, Day of Defeat don't launch correctly

### ISSUE THREAD

**Issue by workqian** [ValveSoftware/steam-for-linux#4930]
Whenever I launch CS or DoD, the programs open, run and then appear on one of my screens at a very small resolution with no mouse control. I can't see the cursor or make it interact with anything on the menu screen. I can't alt tab out of the running program so I have to open up another shell and reboot. I'm pretty sure this is a video issue, but I want to know if there is anyone else out there with this issue.

* Steam client version (1.0.0.49-1)
* Distribution (Debian8.7.1)
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

any idea?

![timg](https://cloud.githubusercontent.com/assets/27684921/25089987/bcc244f8-2378-11e7-84ca-7639fcda2d07.png)

**Comment by kisak-valve** [comment]
Hello @workqian, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by workqian** [comment]
Thanks @kisak-valve   @triage-valve
after some search i find this 

SetLocale('en_US.UTF-8') failed. Using 'C'.
You may have limited glyph support.
Please install 'en_US.UTF-8' locale.

anyway the game runs well now 
appreciate for your help!
[http://steamcommunity.com/app/221410/discussions/1/864958088286447162/](url)
