### ISSUE TITLE
Steam installer using deprecated commands?

### ISSUE THREAD

**Issue by spyjoshx** [ValveSoftware/steam-for-linux#4935]
#### Your system information

* Steam client version (build number or date): Downloaded 4/13/17
* Distribution (e.g. Ubuntu): Kubuntu 16.10 x86_64
* Opted into Steam client beta?: [Yes/No] No (never got the chance)
* Have you checked for system updates?: [Yes/No] Yes. Installed. Still happens.

#### Steps for reproducing this issue:

1. Downloaded .deb file from official Steam website.
2. Installed with Gdebi
3. Launched steam from app launcher (kickoff)
4. Got error. Says "Couldn't set up Steam data - Please contact technical support."
5. Executed "steam" from command line (konsole). got:
```
Repairing installation, linking /home/<user>/.steam/steam to /home/<user>/.local/share/Steam
rm: cannot remove '/home/<user>/.steam/steam': Is a directory
setting up Steam content in /home/<user>/.local/share/Steam
rm: cannot remove '/home/<user>/.steam/steam': Is a directory
```
Username cut for privacy's sake (This error was gotten from someone else, posted by me.)

**Comment by kisak-valve** [comment]
Hello @spyjoshx, this issue is already being tracked at #4929. Closing as a duplicate.
