### ISSUE TITLE
Turkish Steam Client , text overlaps

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#4936]
#### Your system information

* Steam client version (build number or date):Build Date: April 20,2017 Build number:  1492730551
* Distribution (e.g. Ubuntu): Linux Mint 18.1 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I've already told that LC_ALL=C issue here. 
https://github.com/ValveSoftware/steam-for-linux/issues/4792

I've also noticed that some writings are overlapping at ' İndirmeler (Downloads)' section.
![12](https://cloud.githubusercontent.com/assets/24878978/25389013/1faf4a42-29d8-11e7-861b-4bcb156c5a37.png)

Download timer and bandwith limiter sections are doing that.

#### Steps for reproducing this issue:

1. A Linux Mint installation with Turkish locale
2. A Steam installation
3. Quick peek at 'İndirmeler' section

**Comment by Leopard1907** [comment]
@kisak-valve Looks like it's fixed.
![121221](https://user-images.githubusercontent.com/24878978/30038761-d2cf8f46-91d0-11e7-92b8-c351923ed1e1.png)

Issue #4792 still exists though. Any work on that?

**Comment by kisak-valve** [comment]
Thanks for following up @Leopard1907. I don't have any info on the other issue, we'll need to hear from a Steam dev.

Closing.

**Comment by Leopard1907** [comment]
@kisak-valve While i don't know when it happened, it seems like this particular issue arised again. Not 100 percent same looking but it is just a text overlap in Downloads section yet again.

Latest Steam client beta-build date: Jun 7 2021

![Ekran Görüntüsü - 2021-06-08 22-49-32](https://user-images.githubusercontent.com/24878978/121248204-d2692100-c8ab-11eb-89fd-a14d5b9a2342.png)

Since i don't know if opening a new issue ticket for a regression is suitable, i pinged you. Sorry about that.

**Comment by kisak-valve** [comment]
Hello @Leopard1907, with almost 4 years of separation, it's unlikely this is a regression and would need a new investigation. Feel free to open a new issue report.

**Comment by Leopard1907** [comment]
Will do. Thanks.
