### ISSUE TITLE
CS:GO no background music.

### ISSUE THREAD

**Issue by SovietSquid** [ValveSoftware/steam-for-linux#4938]
Nvidia GeForce 740, AMD Phenom II,

The Latest Version
OpenSUSE 13.2
No beta
My whole distribution is outdated

Ever since the new CS:Go update, my background music has stopped playing. All the soundeffects are still present, just no music.

#### Steps for reproducing this issue:

1. Launch CS:GO
2.  Notice no music
3.  Post on forums

**Comment by kisak-valve** [comment]
Hello @SovietSquid, this issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1392. Closing as a duplicate.
