### ISSUE TITLE
Can't type on the overlay while playing Dirt Rally

### ISSUE THREAD

**Issue by Redneckita** [ValveSoftware/steam-for-linux#4941]
#### Your system information
* Steam client version: Latest, no update available (how do i check it if needed?) 
* Distribution: Elementary OS Loki (based on Ubuntu xenial) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Steam overlay did not allow me to type anything while playing Dirt Rally, but i can use the keyboard to minimize the game. This issue only happen while playing DR and not on every other game i have.

#### Steps for reproducing this issue:
None as far as i know

**Comment by kisak-valve** [comment]
Hello @Redneckita, are you still experiencing this issue on an up to date system?

**Comment by Redneckita** [comment]
Hi @kisak-valve, just tested on Ubuntu 18.04 and latest Steam.
It works with both desktop overlay and big picture overlay, physical and virtual keyboard

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
