### ISSUE TITLE
Exiting a Streaming instance minimizes Steam

### ISSUE THREAD

**Issue by halferuga** [ValveSoftware/steam-for-linux#4942]
#### Your system information

* Steam client version: Apr 25 2017, at 22:46:35
* Distribution: Ubuntu 17.04
* Opted into Steam client beta: No
* Have I checked for system updates:  Yes

#### Please describe your issue in as much detail as possible:
Exiting a an In-Home Streaming instance minimizes Steam Big Picture, in order to get back to Steam, I have to either press the Steam/Guide button on my controller; or get a keyboard/mouse to AltTab or find Steam's instance in the desktop environment. It doesn't matter whether or not you've quit the game using it's own "quit" function, or you quit using the Steam Overlay - the result is the same.
This issue does not occur with native games, when you've quit _them_, you get straight back to Big Picture

#### Steps for reproducing this issue:

1. Launch a In-Home Stream.
2. Exit the game in any way you want (using the in-game "exit" options, or through the Steam Overlay)

**Comment by kisak-valve** [comment]
Hello @halferuga, this issue is being tracked at #4611 and is not limited to in home streaming. Closing as a duplicate.
