### ISSUE TITLE
Steam Overlay FPS counter not working on OpenMandriva LX 3.01

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/steam-for-linux#4943]
#### Your system information

* Steam client version (build number or date): Latest stable.
* Distribution (e.g. Ubuntu): OpenMandriva LX 3.01
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

When I playing on Linux OpenMandriva I see that Steam Overlay in game FPS counter not working. I can't see my FPS. I trying few times, enable it in Steam options, next disable and again enable not working. Trying change corner but also is the same. Trying checking it on few games for e.g Arma: Armed Assault, Age of Wonders 3, Dota2 and CS:GO. Trying also launch game with enabled compositions and disabled compositions - in both cases is the same.

#### Steps for reproducing this issue:

1. Install OpenMandriva LX 3.01
2. Install Steam. In system terminal "su" and next "urpmi steam"
3. Launch any Steam game and see, Steam FPS counter not working.

My Steam and PC info:

https://pastebin.com/jEbpGwUh

**Comment by kisak-valve** [comment]
Hello @AngryPenguinPL, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
