### ISSUE TITLE
In Home Streaming does not work properly with debian

### ISSUE THREAD

**Issue by finlstrm** [ValveSoftware/steam-for-linux#4949]
#### Your system information

* Steam client version (build number or date): 1493162727
* Distribution (e.g. Ubuntu): Debian stretch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

debian stretch for steam client/host. upon launch of clients both see each other on the network.
firewall is disabled on both systems. 

#### Steps for reproducing this issue:

1. Launch Steam Client on both systems
2. From the client, attempt to launch (stream) a game from the host
3. Game allways launches on other screen but one of two things will happen to the client
-- Error message unable to connect, or
-- Game connects but then is distorted

**Comment by kisak-valve** [comment]
Hello @finlstrm, are you still experiencing this issue on an up to date system?

**Comment by finlstrm** [comment]
@kisak-valve I honestly haven't played with this since I posted this bug. Considering It's almost 3 years old, I actually forgot about it. I currently don't have the setup to test at the moment. I should have my office back up and running in a 2 or 3 months, I'll be able to test again as time allows then.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Quite a bit has changed with Steam's streaming, so I'm going to close this. If you're still having this issue when you can test again, let me know and I'll re-open this issue report.
