### ISSUE TITLE
Webview stopped working

### ISSUE THREAD

**Issue by User65k** [ValveSoftware/steam-for-linux#4951]
#### Your system information

* Steam client version (build number or date): 

> Built: Apr 25 2017, at 22:46:35
> Steam API: v017
> Steam package versions: 1493162727

* Distribution (e.g. Ubuntu): 

> Ubuntu 16.04.2 LTS (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.8.0-51-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11804000
>     X Window Manager:  Mutter (Muffin)
>     Steam Runtime Version:  steam-runtime-beta-release_2016-12-05

* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:

Internal Webbrowser stopped working after a client update.

#### Steps for reproducing this issue:

- Start Steam
- Open anything needing a web component (e.g. Store)
- Expected: Store page displays
- Actual: Page stays black, in terminal this line is printed multiple times:
`[0507/121416.957305:ERROR:child_process_launcher.cc(522)] Failed to launch child process`

The first few terminal lines when starting steam give me:
```
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1493162727)
Installing breakpad exception handler for appid(steam)/version(1493162727)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1493162727)
LaunchProcess: failed to execvp:
./steamwebhelper
```

Launching steamwebhelper directly prints:
`./steamwebhelper: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory`

This looks pretty much like #4687.
However starting steam with `export LD_LIBRARY_PATH=/mnt/data/usr/.local/Steam/ubuntu12_64` did not fix the issue. (libcef.so is within this directory)

**Comment by kisak-valve** [comment]
For what it's worth, `.local/Steam` sounds abnormal in the path to the ubuntu12_64 folder. If you are using the valve-provided steam package, that folder are expected to be in `~/.local/share/Steam/ubuntu12_64` and if it's the distro-provided package, then `~/.steam/ubuntu12_64` is expected.

**Comment by User65k** [comment]
I have symlinked `~/.local/share/Steam` to `/mnt/data/usr/.local/Steam/`

**Comment by pclose** [comment]
I have the same behavior occuring, with a different error message. [steam.sh.log.zip](https://github.com/ValveSoftware/steam-for-linux/files/994081/steam.sh.log.zip)

    chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
    ./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest

**Comment by SergeiFranco** [comment]
Just got new update and problem is still there with Build date `May 12 2017, at 23:46:20`...

**Comment by ardje** [comment]
Since 19 may I got the SDL_SetWindowHitTest lookup error on steamos stable. I think I can leverage my problem by not using the steamos libs:
steam@steamos:~$ strings -a /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.2.0|grep SDL_SetWindowHit
steam@steamos:~$ strings -a .local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0|grep SDL_SetWindowHit
SDL_SetWindowHitTest
SDL_SetWindowHitTest
steam@steamos:~$ dpkg -l libsdl2-2.0-0|tail -1
ii  libsdl2-2.0-0:amd64 2.0.2+dfsg1-6+bsos1 amd64        Simple DirectMedia Layer

I must confess that I upgraded my system with 381.09 nvidia drivers using normal debian methods, but that should not break this.

**Comment by kisak-valve** [comment]
@NotMrFlibble posted on 2017-05-19T22:43:14 at #4983:

Steam client build no.: 1495155850
Running on SteamOS brewmaster + jessie-backports (for use with current Mesa)

This pair of messages is repeatedly being output on the terminal:
```
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
```
Running with STEAM_RUNTIME=1 does not help. Moving the system libSDL2-2.0.so.0 out of the way works around the issue. Upgrading should fix it, but that would require pulling in packages from Debian stretch (which may be problematic regarding pulling in other packages) or locally recompiling.

***

From this hint, running steam from a terminal with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` may workaround this issue

**Comment by kisak-valve** [comment]
@User65k, I've made a mistake here, your issue most likely has something to do with apparmor blocking cef and everything else in this issue report is the system variant of libSDL2 being older than 2.0.4.

**Comment by SergeiFranco** [comment]
+1 on `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` working.

**Comment by User65k** [comment]
`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` does not work for me: [wHOST_LIBs.txt](https://github.com/ValveSoftware/steam-for-linux/files/1016074/wHOST_LIBs.txt)
Note that the `no version information available` messages do not appear when starting normal.

I have apparmor in complain mode - will switch it off and update this comment.

Also, libSDL is 2.0.4:
```
dpkg -l libsdl*|grep -v ^un
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                       Version              Architektur  Beschreibung
+++-==========================-====================-============-=================================================================
ii  libsdl-image1.2:amd64      1.2.12-5build2       amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2debian:amd64      1.2.15+dfsg1-3       amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64        2.0.4+dfsg1-2ubuntu2 amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386         2.0.4+dfsg1-2ubuntu2 i386         Simple DirectMedia Layer
ii  libsdl2-ttf-2.0-0:i386     2.0.14+dfsg1-1       i386         TrueType Font library for Simple DirectMedia Layer 2, libraries
```

**Comment by kshade** [comment]
I've got a similar error with the current beta client where the browser doesn't show up at all in the Steam overlay, but works normally otherwise. Regular release works fine.

**Comment by kisak-valve** [comment]
Hello @kshade, that overlay issue is being tracked at #4957.

**Comment by kisak-valve** [comment]
@User65k, I'm going to go ahead and close this issue report as this appears to have been a user configuration issue with apparmor. If you find something interesting for a Steam dev to look into, please let me know and we can re-open this issue report.
