### ISSUE TITLE
0MB space left in a NFS share library

### ISSUE THREAD

**Issue by pablow1422** [ValveSoftware/steam-for-linux#4952]
#### Your system information

* Steam client version (build number or date): 1493162727
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed, Kubuntu 17.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
I have a NAS with a NFS share where my steamlibrary is stored. I can play games from it just fine but can't install a new one. Steam reports that I have no space left, but there is almost 3TiB free (filemanagers can see this).

I can't tell if it was working before because just recently set up the NAS, copying my steam library folder to the share. I only have a SSD in my gaming PC so space is an issue for local install.

In settings, the library in the NFS share shows there's 0MB available.

(EDIT): Game updates works.
(EDIT2): Ubuntu 17.04 also affected.
#### Steps for reproducing this issue:

1. Open steam. Make sure you have a NFS share mounted with write permissions.
2. Try to install a game in the library stored on the NFS share
3. Steam will report there's no space left in that library

**Comment by zv0n** [comment]
This also happens to me with SMB share.

**System info:**
Client version: 1494374828
Distribution: Arch Linux
Opted into beta?: Yes
Checked for system updates?: Yes

**More details**
Steam sees available space fine when mounted through gvfs, it seems to be only misbehaving when the share folder is mounted manually using cifs

**Comment by minus7** [comment]
Same problem here with sshfs on Arch Linux. This used to work just fine.

**Comment by pablow1422** [comment]
Any news on this? It's holding back my recent purchases.

This is from the console output when trying to install a game:
`../tier1/fileio.cpp (3268) : Assertion Failed: Failed to determine free disk space for /media/STEAM, error 75
Assert( Assertion Failed: Failed to determine free disk space for /media/STEAM, error 75 ):../tier1/fileio.cpp:3268`

And, this is the crash ID:
`CrashID=bp-f1a51323-f084-49b9-ac9a-5f8d72170702`

**Comment by minus7** [comment]
Seems to work again on sshfs.

**Comment by pablow1422** [comment]
Still an issue here (Ubuntu, Fedora, openSUSE clients with Debian, CentOS NFS servers)

**Comment by Pilzschaf** [comment]
Problem still exists with NFS on Manjaro 17.0.2 and Debian 8.9 as NFS server.
This setup worked before.
Switching to SMB or SSHFS didn't work for me either. 
But sshfs gave me another error: "New Steam library folder must be writeable" even though I have write permissions and it even could create a new SteamLibrary folder. 
I am using steam beta version 1503954609. Non beta version also didn't work but I tested just NFS with that.

**Comment by Pilzschaf** [comment]
It works perfectly on kernel version 4.9 but on 4.13 it just shows 0MB space left.

**Comment by Techjar** [comment]
I'm also experience this issue. Steam library on CIFS mount shows 0 bytes of free space. Would greatly appreciate this being fixed.

**Comment by IGBC** [comment]
also have this
4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linux
Steam-native no beta.

**Comment by Phalen** [comment]
Per #5364  kernel 4.13 and 4.14 on ubuntu 16.04 do the same thing.

**Comment by Phalen** [comment]
Per #5364 Kernel 4.13 and 4.14 on ubuntu 16.04 have the same issue. I might have upgraded kernels around that time originally while trying to update amdgpu-pro drivers.  beta makes no difference

**Comment by mastercake10** [comment]
Error still exists, running ubuntu 16.04, kernel 14.14.

**Comment by cuteboi** [comment]
Just tried to install a new game, unable to install Dead Maze, reports 0 space on NFS mounted home directory.  Updates to Factorio succeed.

**Comment by nyanloutre** [comment]
Also affected on Manjaro with a NFS share

**Comment by HughPH** [comment]
I have this issue too, with Ubuntu 18.04, Steam built Jun 1 2018 at 10:15;49, Kernel 4.16.10
Server is Ubuntu 17.10 with Kernel 4.13.0
This worked until a point, but I have no idea what that point was. Games just stopped updating.

Regarding switching to NFSv4, I thought that required Kerberos etc? Possibly a little heavyweight for general home users?

**Comment by HughPH** [comment]
@penetal Thanks for the info. I managed to move it to v4 with a bit of googling, but unfortunately it hasn't made any difference for me.

Another symptom - I don't know if anyone else has it? Even with the default folder in ~/.steam and plenty of space on my local disk, I can't actually install _anything_ - it declares that there's no space left even before it asks me where I want to install, and even if local (with space) is default.

A very untidy, hacky work-around is to exit Steam, unmount, reload Steam, install locally, exit Steam, remount, move the files, reload Steam, and - if necessary - re-add the remote Steam folder. Although that's not exactly practical if you want to install a 50Gb+ game and don't have 50Gb space on your local disk...

My fileserver and gaming machine are on a 1Gbps switch, so I thought about trying iSCSI. I'll let you know - although having this fixed would be a much better answer for most people.

**Comment by microcai** [comment]
same issue here
kernel 5.1

**Comment by nyanloutre** [comment]
I fixed this by creating a ZFS share limited to 2TB (if the size is bigger it will show 0 space free)

**Comment by IGBC** [comment]
> I fixed this by creating a ZFS share limited to 2TB (if the size is bigger it will show 0 space free)

Combined with the people here reporting this on iSCSI I think this is a FS too big bug.

I suggest we file a new error for filesystems over 2TB

**Comment by kisak-valve** [comment]
Hello @IGBC, the trouble with filesystems larger than 2TB sounds like #4982 / #5180.

**Comment by IGBC** [comment]
@kisak-valve can we use the testimonials here to change #4982 to confirmed and get some progress to a fix?

**Comment by jerrac** [comment]
@nyanloutre  Thanks. https://github.com/ValveSoftware/steam-for-linux/issues/4952#issuecomment-494362796 helped a lot. Limiting my nfs share to 2TB made Steam figure out that I really do have disk space.

**Comment by TTimo** [comment]
Can you run `stat -f [nfs mount]` on your nfs client system, do the same on the server side for the backing partition, and report the results?

**Comment by kisak-valve** [comment]
Hello, per "Fixes to free disk space checks to address issues with some NFS mounts" in the [2019-11-07](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1600394952171527192) Steam client beta update, please opt into Steam's beta client if you haven't already and retest this issue.

**Comment by TTimo** [comment]
(more precisions)

Latest steam beta (Nov 7) comes with several changes to the way the client obtains free disk space information, which may help with this - please retest.

If you are still experiencing this bug, please set DBG_STAT environment variable before running steam and provide the diagnostic output to statfs64 and statvfs64 calls from Steam client stdout.

**Comment by TTimo** [comment]
Let's just all track this at https://github.com/ValveSoftware/steam-for-linux/issues/4982 which has been more active anyway.
