### ISSUE TITLE
Dota 2 vulkan will only work with nvidia-beta drivers. Steam will not start with beta drivers..

### ISSUE THREAD

**Issue by arkhanari** [ValveSoftware/steam-for-linux#4953]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Arch LInux
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
As of latest Dota 2 update Dota 2 will crash with -vulkan enabled. It seems nvidia-beta drivers are needed. Steam will not start with beta drivers however.

#### Steps for reproducing this issue:

1. Install Linux
2. Update Dota 2
3. Launch with "-vulkan" launch option

**Comment by kisak-valve** [comment]
Hello @arkhanari, a couple basic questions. Have you restarted since updating the nvidia driver? Is steam giving any error message or console spew when trying to start?

**Comment by kisak-valve** [comment]
When you installed the beta package, did it also install something like `lib32-nvidia-libgl-beta`?

**Comment by bill-mavromatis** [comment]
Hi, I'm not OP but I have the same issue. Installed it with
`yaourt -S nvidia-full-beta-all lib32-nvidia-libgl-full-beta-all`

I'm sure it installs because I can see the version on nvidia-settings being 381.09. Steam just hangs.

**Comment by kisak-valve** [comment]
Hello @bill-mavromatis, swrast is a software renderer in mesa. The fact steam is trying to use it in this case hints that you're trying to use mesa's libGL with nvidia (that's incompatible) or maybe something has gone wrong with libglvnd.

**Comment by bill-mavromatis** [comment]
@kisak-valve The problem is that my package manager says this:

> nvidia-utils-full-beta-all and libglvnd are in conflict. Remove libglvnd? [y/N]

So I have to remove libglvnd if I want to continue installation.... Maybe it's a problem with my package manager and the specific package. I know this is probably out of your field and more of a package manager issue, I'll try to check it. [Other suggested](https://aur.archlinux.org/packages/nvidia-full-beta-all/) that I install **nvidia-libgl-beta**. Is this the package I need? I think this creates even more conflicts...

**Comment by kisak-valve** [comment]
Hello @arkhanari, @vmavromatis, are either of you still experiencing this issue on an up to date system. nVidia's proprietary driver requires that the running kernel module version, 32 bit userspace version, and 64 bit userspace version exactly match for everything to work as expected.
