### ISSUE TITLE
life is strange out of memory on wayland

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-for-linux#4954]
#### Your system information

* Steam client version (build number or date): 1493162727
* Distribution (e.g. Ubuntu): Gentoo x86_64 stable
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Window Manager: sway

#### Please describe your issue in as much detail as possible:
Life is Strange goes onto 'out of memory' on start then crashes creating dmp file when sdl video driver set to wayland and using steam runtimed libSDL2 (e.g. when i add SDL_VIDEODRIVER=wayland to launch command), but when i preload system libSDL2 like this `LD_PRELOAD=/usr/lib64/libSDL2-2.0.so.0` game starts and works.

Crash file: [lis_wayland_outofmemory_crash.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/981984/lis_wayland_outofmemory_crash.dmp.zip)
System info: https://gist.github.com/soredake/80d067c101202ef91a6872aa67984d53
Steam launch command: `env LD_PRELOAD='/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/32/libstdc++.so.6:/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6' STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LIBGL_DEBUG=verbose steam "$@"
`
Life is Strange launch command: `LD_LIBRARY_PATH=/home/bausch/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/bausch/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu LD_PRELOAD=/usr/lib64/libSDL2-2.0.so.0:/usr/lib64/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6 %command%`
#### Steps for reproducing this issue:

1. Setup sway+gentoo
2. Launch life is strange with my command and set the SDL_VIDEODRIVER to wayland
3. Try to preload system libsdl2

**Comment by kisak-valve** [comment]
Hello @soredake, as far as I know, the stream runtime variant of SDL 2 is not built with wayland support right now.

**Comment by soredake** [comment]
@kisak-valve I thought so, but this is the only game that issued 'out of memory' instead of `SDL_Init(SDL_INIT_VIDEO) failed: wayland not available`, anyway thanks for answering.
