### ISSUE TITLE
life is strange uses incorrect pixel bit depth on wayland

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-for-linux#4955]
#### Your system information

* Steam client version (build number or date): 1510357240
* Distribution (e.g. Ubuntu): Gentoo x86_64 stable
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Window Manager: sway

#### Please describe your issue in as much detail as possible:
Note: i use `LD_PRELOAD=/usr/lib64/libSDL2-2.0.so.0` because of this bug https://github.com/ValveSoftware/steam-for-linux/issues/4954
Life is Strange uses incorrect pixel bit depth (lower than needed, about 16, i can not say for sure) instead of 24 (it seems this is the standard depth).
Screenshots:
Sway + SDL_VIDEODRIVER=wayland ![sway_wayland](https://cloud.githubusercontent.com/assets/5204968/25785812/cfdc1d4c-3378-11e7-936d-d96454620616.png)
Sway + SDL_VIDEODRIVER=x11 ![sway_x11](https://cloud.githubusercontent.com/assets/5204968/25785825/f40b3b9e-3378-11e7-95c0-d30271d02457.png)

Probably sdl bug.

System info: https://gist.github.com/soredake/80d067c101202ef91a6872aa67984d53
Steam launch command: `firejail --profile="$XDG_CONFIG_HOME/firejail/steam.profile" -- env LD_PRELOAD='/usr/lib64/gcc/x86_64-pc-linux-gnu/7.2.0/libstdc++.so.6' steam
`
Life is Strange launch command: `SDL_VIDEODRIVER=<driver> LD_PRELOAD=/usr/lib64/gcc/x86_64-pc-linux-gnu/7.2.0/libstdc++.so.6:/usr/lib64/libSDL2-2.0.so.0 LD_LIBRARY_PATH="$HOME/.steam/root/steamapps/common/Life Is Strange/lib/x86_64:$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu" %command% -nostartupmovies`
#### Steps for reproducing this issue:

1. Setup sway+gentoo
2. Launch life is strange with my command and SDL_VIDEODRIVER=wayland, take a screenshot of game
3. Launch life is strange with my command and SDL_VIDEODRIVER=x11, take a screenshot of game
4. Compare it

**Comment by kisak-valve** [comment]
Assigning to the SDL dev.

**Comment by soredake** [comment]
Still a problem on latest archlinux with SDL_VIDEODRIVER=wayland

**Comment by soredake** [comment]
@kisak-valve can you transfer this issue to https://github.com/ValveSoftware/steam-runtime?

**Comment by kisak-valve** [comment]
Hello @soredake, sorry, no. The issue described here is after forcefully replacing SDL with your system variant to expose a bug with an option that is otherwise unavailable. That is not a steam-runtime bug.

If you need to signal boost your issue further, then report it to upstream libSDL.

**Comment by soredake** [comment]
> Hello @soredake, sorry, no. The issue described here is after forcefully replacing SDL with your system variant to expose a bug with an option that is otherwise unavailable. That is not a steam-runtime bug.
> 
> If you need to signal boost your issue further, then report it to upstream libSDL.

This happens with bundled sdl too, i reported it here https://github.com/libsdl-org/SDL/issues/4132

**Comment by icculus** [comment]
(In case this shows up in a Google search: we pushed a fix to SDL today, so this will Just Work as updated builds make their way around eventually.)
