### ISSUE TITLE
Steam BPM does not regain focus when game exits

### ISSUE THREAD

**Issue by calexil** [ValveSoftware/steam-for-linux#4956]
#### Your system information

* Steam client version (build number or date):   build apr 25 2017
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: [Yes/No]   NO
* Have you checked for system updates?: [Yes/No]    YES

#### Please describe your issue in as much detail as possible:
when exiting any game that was launched from bpm, bmp does not properly regain focus

#### Steps for reproducing this issue:

1.Use linux mint 18.1 with the mate desktop, pkppa mesa drivers, r9 380x, kernel 4.8.0.59 marco wm and compton compositor 
2. launch bpm
3. start a game from bpm
4. quit the game

this happens:

![screenshot at 2017-05-08 21-08-42](https://cloud.githubusercontent.com/assets/3487071/25831565/1622b0a8-3433-11e7-9941-84b99aa4b5e0.png)

5. no gamepad buttons work anymore, and if you were couch browsing you have to get up and find a keyboard to alt tab back into bpm.

**Comment by kisak-valve** [comment]
Hello @calexil, this issue is already being tracked at #4611. Closing as a duplicate.

**Comment by calexil** [comment]
thanks @kisak-valve
