### ISSUE TITLE
Recently played with doesn't show all players

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4958]
#### Your system information

* Steam client version (build number or date): Latest stable as of today
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The recently played with option is not working

#### Steps for reproducing this issue:

1. Used Killing Floor
2. Started a match with a friend, them other random people joined
3.  Only my friend shows on recently played with

**Comment by kisak-valve** [comment]
This is not an OS-specific issue.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
