### ISSUE TITLE
Unable to share Google Photos links with friends

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#4960]
#### Your system information

Irrelevant, problem is in backend servers and affects all clients and website also.

#### Please describe your issue in as much detail as possible:

I can't share Google Photos with friends. When I try it's removed by the url filters showing {LINK REMOVED}. It's because these urls start with goo.gl which is Google's url shortening service. I know why these are blocked and that is ok, but Google Photos does not give any other url for sharing. It's easy to distinguish Google Photo urls from the rest of shortened urls by checking if url starts with goo.gl/photos/. Google Maps also does the same thing with goo.gl/maps/ but unlike photos address bar url can be used for sharing instead.

Many people (me included) tried raising this issue several times over the years in the forums only to be dismissed as pirates. I'm affected on Linux in the Steam for Linux client so I'm reporting it here. If it's not the right place or you don't want to support these urls (goo.gl/photos and goo.gl/maps not all goo.gl urls), please close this issue. Thanks.

#### Steps for reproducing this issue:

1. Open Google Photos and upload and select an image
2. Click Share and then Get link
3. Copy and paste short url into chat and get {LINK REMOVED}

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
