### ISSUE TITLE
Issue with loading update from steam from last week - download has been interrupted after 12-15%

### ISSUE THREAD

**Issue by shadowman79** [ValveSoftware/steam-for-linux#4963]
#### Your system information

* Steam client version (build number or date): April 24, 2017
* Distribution (e.g. Ubuntu): Chakra, x86_64
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Issue with loading update from steam from last week for DOTA 2 - download has been interrupted after 12..15%  (about 186 MB, need to dowload 1.3 GB in total)

even if downloading starts again, the issue appears with 12..15% threshold. Also I've tried to remove "downloading" folder - to starts update again. Still unable to download client update.

System info - http://pastebin.ca/3809929

#### Steps for reproducing this issue:

1. Open steam. Dota 2 downloading has been started.
2. Waiting some time to download update
3. Check if stream loaded more then 15%. 

Actual: no. Downloading has been interrupted. "Connection timeout". Download speed strives for zero.

Tested file systems: ext4 - primary, ntfs - results the same.

**Comment by shadowman79** [comment]
connection info - ethernet.  100 MB/s.

**Comment by kisak-valve** [comment]
Hello @shadowman79, can you please include `~/.local/share/Steam/logs/content_log.txt`, which might have a hint to what's going on here? You should be able to drag and drop it into the comment box.

**Comment by shadowman79** [comment]
Hello @kisak-valve, i have just looked and now downloading was successful.  Thank you. 
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/994452/content_log.txt)
