### ISSUE TITLE
Reliably able to crash steam via system info window

### ISSUE THREAD

**Issue by boustrophedon** [ValveSoftware/steam-for-linux#4964]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Opening the system info window and then going to another desktop for about 30s-1m reliably crashes steam for me.

May be related to #4856 
#### Steps for reproducing this issue:

1. Open Steam
2. Open Help -> System Information
3. Switch to a different desktop
4. Wait 30s-1m
5. Steam crashes with the following error:
6. (optional) if it does not crash, try selecting some text in the window and then changing desktops
```
../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Broken pipe)
threadtools.cpp (1343) : Assertion Failed: Thread synchronization object is unuseable
```
https://gist.github.com/boustrophedon/0bc26572c0fb74ecd0142f5155e8cc52 contains my last few dumps from system information (it just crashed again while pasting into the gist).

**Comment by kisak-valve** [comment]
Hello @boustrophedon, can you add a note if you are using steam with the steam runtime or with the native runtime?

**Comment by boustrophedon** [comment]
I have steam installed from my package manager and I don't have the steam-native-runtime package installed. I can try installing it and testing again if you'd like.

**Comment by YangtseSu** [comment]
Archlinux x86_64.
Steam runtime crash,but native not.

**Comment by rivertam** [comment]
Same error is occurring for me when I start up. I reinstalled and deleted all my local files, but now it just fails earlier. The login form shows up but I can't interact with it as Steam has already segfaulted and is just cleaning up or something.

I'm on Ubuntu, though. Not sure if this is the right place to post this.

**Comment by boustrophedon** [comment]
@rivertam are you sure this is the same issue? This crash only occurs for me when the "system information" window is open.

**Comment by rivertam** [comment]
Could definitely be a different cause, but it seems to be breaking on the same line with the same error (same assertion). It just happens earlier.

**Comment by kisak-valve** [comment]
Noted in #5053, this is also seen with Slackware.

**Comment by kisak-valve** [comment]
Is anyone seeing this issue with the current steam beta client?

**Comment by boustrophedon** [comment]
I'll check and get back to you.

**Comment by boustrophedon** [comment]
I left it open for about 30 minutes while on a different desktop and did not observe a crash.
