### ISSUE TITLE
Steam wont launch

### ISSUE THREAD

**Issue by aeon1111** [ValveSoftware/steam-for-linux#4969]
Host: AeonMint Kernel: 4.4.0-53-generic x86_64 (64 bit) Desktop: Cinnamon 3.2.7
           Distro: Linux Mint 18.1 Sere

* Steam client version (build number or date): 1:1.0.0.52-5ubuntu1
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No]??
* Have you checked for system updates?: [Yes/No]

I guys,
I just cannot launch steam at all... when I click the icon nothing works... It use to work with the exact configuration but I wanted to move a folder then... So I uninstall it then reinstall it but now it doesn't start anymore.\Any idea?

**Comment by kisak-valve** [comment]
Hello @aeon1111, does running steam from a terminal give any useful hints? The steam packaging is only the launcher, while steam itself is in the user's folder. You could try `steam --reset` in a terminal to reset it as if it was the first time running on your system.

**Comment by aeon1111** [comment]
I do not know how to run a program from the terminal..

There is nothing in the user folder 

I tried the command:
tar: This does not look like a tar archive
xz: (stdin): File format not recognised
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/aeon/.steam/ubuntu12_32/steam-runtime’: No such file or directory
tar: This does not look like a tar archive
xz: (stdin): File format not recognised
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/aeon/.steam/ubuntu12_32/steam-runtime’: No such file or directory

**Comment by aeon1111** [comment]
I just erase the hidden files in Home then reinstall.... It works now
Thx

**Comment by kisak-valve** [comment]
Closing per the last comment.
