### ISSUE TITLE
Steam doesnt work

### ISSUE THREAD

**Issue by Darkblood618** [ValveSoftware/steam-for-linux#4970]
* Steam client version: Latest version
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: Yes

So I am not really good at this linux stuff, but it was the only operating system that I could currently use. While playing csgo on steam, it randomly crashed and I was unable to open it again. Whenever I clicked it, it just did nothing. If someone could teach me step by step, that would be great.

**Comment by kisak-valve** [comment]
Hello @Darkblood618, you may get better advice by reaching out to your distro's community for help learning about linux in general.
