### ISSUE TITLE
Steam application loads but then behaves as if not logged in

### ISSUE THREAD

**Issue by OOPMan** [ValveSoftware/steam-for-linux#4971]
#### Your system information

* Steam client version (build number or date):   April 20 2017, at 21:59:41
* Distribution (e.g. Ubuntu): Kubuntu 16.10 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Hi

My Steam installation on Linux seems to be misbehaving. The client application connects and logs in but once it is running it seems to think it is not logged in.

If I visit a store page it doesn't let me wishlist, but says I need to sign in. If I click on my username and select preferences or click on the "Sign-on to wishlist" link I get the message about verifying login information and then an error message about being unable to contact the steam servers.

Also, my game download queue does not seem to be processed.

This issue only occurs on my Linux client, my Windows clients work fine. 

According to About Steam my client details are as follows:

Built: April 20 2017, at 21:59:41
Steam API: v017
Steam package versions; 1492730551

#### Steps for reproducing this issue:

Unknown. My Steam on Linux didn't used to do this, but it's doing it now. I was wondering if there is some kind of session cache I could clear or something?  I already tried logging out and logging in again with no luck.

**Comment by OOPMan** [comment]
I'm attaching some screen-shots to demonstrate further:

![screenshot_20170513_200746](https://cloud.githubusercontent.com/assets/248980/26028163/0154d9a8-381b-11e7-88a5-79cd39d85982.png)
![screenshot_20170513_200821](https://cloud.githubusercontent.com/assets/248980/26028165/015892be-381b-11e7-8155-da5ff2f18f8c.png)
![screenshot_20170513_200834](https://cloud.githubusercontent.com/assets/248980/26028164/01564798-381b-11e7-9dae-2cbd95511e0a.png)
![screenshot_20170513_200849](https://cloud.githubusercontent.com/assets/248980/26028166/01677842-381b-11e7-9494-fbf14ad3b92f.png)
![screenshot_20170513_200902](https://cloud.githubusercontent.com/assets/248980/26028167/0168adac-381b-11e7-8da4-21fe63b55bec.png)

**Comment by OOPMan** [comment]
Woops, look like I doubled up on one of them. Oh well.  The third one was meant to be showing a Store page with the Wishlist/Follow buttons unavailable and instead displaying the "Sign In to Wishlist/Follow" text.

**Comment by deresh** [comment]
@OOPMan 

I have the exactly same problem. Did you manage to fix this somehow?

**Comment by deresh** [comment]
Those are my versions, im using ubuntu gnome, and have opted for beta versions, but the problem is the same...

Operating System Version:
    Ubuntu 17.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.10.0-21-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2

**Comment by OOPMan** [comment]
@deresh Yes, I did manage to fix it. Initially I tried completely nuking my `.steam` directory and starting from scratch but that led to a new error which after some searching turning out to be because `libnss-resolve:i386` was not installed. It is a dependency of Steam which is not listed in the Ubuntu packages.

Try `sudo apt install libnss-resolve:i386` and see if that fixes it for you.

**Comment by deresh** [comment]
@OOPMan:

Thank you, that resolved issue for me. Eitherways some of the Valve guys should fix this properly. I think it's caused by Steam using system libs since recently.

So we should leave this ticket opened.

**Comment by kisak-valve** [comment]
Per "Fixed an issue that could cause Store or Community pages to stop being logged in until restarting the Steam client" in the [2018-05-09](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3808235299524574139) Steam beta client update, please opt into Steam's beta client and retest this issue.

**Comment by tunanachos** [comment]
@kisak-valve this doesn't fix the issue unfortunately.
