### ISSUE TITLE
html_chrome.cpp (3127) : Assertion Failed: WideVine CDN download failure 0

### ISSUE THREAD

**Issue by shakaran** [ValveSoftware/steam-for-linux#4973]
Another error with same system that #4966

![image](https://cloud.githubusercontent.com/assets/14254/26057549/767a681e-397a-11e7-9397-fd925c45138f.png)

```
Store/Community web auth request failed: Auth error
html_chrome.cpp (3127) : Assertion Failed: WideVine CDN download failure 0
```
In browser I can access perfectly:

![image](https://cloud.githubusercontent.com/assets/14254/26057639/c8cdaf9a-397a-11e7-8436-a20fcb0da3d7.png)

**Comment by shakaran** [comment]
I have a bit of progress, after I change resolv.conf

From:

```
cat /etc/resolv.conf 
nameserver 127.0.1.1
```

To:

```
cat /etc/resolv.conf 
# Generated by NetworkManager
options timeout:1 rotate attempts:1
search localdomain
nameserver 127.0.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```
it is downloading well (it seems a problem with my router and Vodafone? restrictions from ISP?)

But it is showing now this error:

`[0515/203734.600800:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization`

**Comment by kisak-valve** [comment]
Since that config is pointing to a loopback device, it may also be an issue with a local dns service like dnsmasq.

**Comment by kisak-valve** [comment]
Hello @shakaran, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
