### ISSUE TITLE
 GLib-GObject-WARNING **: ../../../../gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x577a80d8' of type 'GtkMenu'

### ISSUE THREAD

**Issue by shakaran** [ValveSoftware/steam-for-linux#4974]
Same system that #4966

`(steam:23013): GLib-GObject-WARNING **: ../../../../gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x577a80d8' of type 'GtkMenu'`

I think that I know why this error is produced. In the tray icon a Steam menu is created in first stage, when you have login remembered, this initial menu is empty, after the auth login succeed it is prefilled with GktMenu entries, but in a intial stage is empty, that makes that the warning appears. So it should be prefilled at least with one entry (for example "Exit") for avoid this warning and error.

**Comment by kermeat** [comment]
It's a bug
https://askubuntu.com/questions/364594/has-the-appindicator-or-gtkmenu-api-changed-in-saucy

**Comment by kisak-valve** [comment]
Hello @shakaran, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
