### ISSUE TITLE
GPU usage drops to 0% in some games

### ISSUE THREAD

**Issue by TwistedCheshireCat** [ValveSoftware/steam-for-linux#4977]
#### Your system information

* Steam client version (build number or date):  25.04.2017. 22:46:35
* Distribution (e.g. Ubuntu): Devuan GNU+Linux Ceres branch (unstable)
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

CPU: Intel i5 4460
Graphics card: MSI Gaming X RX 470 4GB
Linux kernel: Linux devuan 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux
Display Server: X.Org 1.19.3 driver: amdgpu
GLX Renderer: Gallium 0.4 on AMD POLARIS10 (DRM 3.8.0 / 4.9.0-3-amd64, LLVM 4.0.1)
Mesa version: Mesa 17.1.0

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When I run some games, my GPU usage drops to 0% when I am moving mouse in the menu or in game. That results in getting 0-1FPS. The games where I noticed it happens: Left 4 Dead 2, Dota 2 and Company of Heroes 2. This happened even when I was using Devuan Ascii (testing branch) which had older 4.9 kernel, LLVM 3.9 and Mesa 13.0.6-1+b2. If you require more info, please let me know.

#### Steps for reproducing this issue:

1. Launching Steam
2. Launching game
3. Moving mouse

**Comment by kisak-valve** [comment]
Hello @TwistedCheshireCat, this should also be brought to the attention of your video driver vendor.

**Comment by NotMrFlibble** [comment]
https://bugs.freedesktop.org/
#radeon on irc.freenode.net

I suggest trying Linux 4.10 or 4.11 first, though.

**Comment by kisak-valve** [comment]
It should be noted that initial troubleshooting steps were done on [#radeon](https://people.freedesktop.org/~cbrill/dri-log/index.php?channel=radeon&date=2017-05-18) yesterday.

**Comment by TwistedCheshireCat** [comment]
I tried today the latest kernel available from experimental repo (Linux devuan 4.11.0-trunk-amd64 #1 SMP Debian 4.11-1~exp2 (2017-05-05) x86_64 GNU/Linux) and I have the same results.

**Comment by justinkterry** [comment]
If you're still experiencing this, I recommend trying the amdgpu pro drivers. I'm using a 480 (which is the same generation as the 470 so will have near identical drivers) in an otherwise near identical setup and don't experience these issues. The open source graphics card drivers on linux still don't work entirely right (unlike cpus and most other components now days), so I was getting all sorts of odd issues before I installed it.

**Comment by TwistedCheshireCat** [comment]
This appears to be gone once I tried different window manager, Enlightenment e17.. It appears to be i3 wm related.

**Comment by justinkterry** [comment]
That means is definately driver based. If it happens without installing AMDPRO, you cross need to report it to the relevant linux kernel team and to the effected window manager. Tell me if you need help with that.

**Comment by justinkterry** [comment]
Do you want me to close this since it's not a steam problem?

**Comment by TwistedCheshireCat** [comment]
Sure thing :)

**Comment by justinkterry** [comment]
Closed

**Comment by justinkterry** [comment]
Interesting. @kisak-valve please close? 

@TwistedCheshireCat did you submit the relevant bug reports?
