### ISSUE TITLE
no page displays (store/profile/friends...)

### ISSUE THREAD

**Issue by sysms** [ValveSoftware/steam-for-linux#4980]
#### Your system information

* Steam client version (build number or date):  Beta May 19 2017 1495155850
* Distribution (e.g. Ubuntu): Debian 8
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The latest beta client does not display any web pages from the store/friends/groups/profile/...

In the terminal I get this output indefinetely:

chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process

#### Steps for reproducing this issue:

1.  download latest beta client
2. try to open a page like store/friends/groups, you will only get a blank display

**Comment by kisak-valve** [comment]
Hello @sysms, this issue is already being tracked at #4951. Closing as a duplicate.
