### ISSUE TITLE
Steam client: built-in browser is not working

### ISSUE THREAD

**Issue by NotMrFlibble** [ValveSoftware/steam-for-linux#4983]
Steam client build no.: 1495155850
Running on SteamOS brewmaster + jessie-backports (for use with current Mesa)

This pair of messages is repeatedly being output on the terminal:
```
chrome_ipc_client.cpp (112) : Assertion Failed: GenerateCEFLogFileName in unknown process
./steamwebhelper: symbol lookup error: ./steamwebhelper: undefined symbol: SDL_SetWindowHitTest
```
Running with STEAM_RUNTIME=1 does not help. Moving the system libSDL2-2.0.so.0 out of the way works around the issue. Upgrading should fix it, but that would require pulling in packages from Debian stretch (which may be problematic regarding pulling in other packages) or locally recompiling.

**Comment by kisak-valve** [comment]
Hello @NotMrFlibble, this issue is already being tracked at #4951. Closing as a duplicate.
