### ISSUE TITLE
Client crashes with high color bit depth

### ISSUE THREAD

**Issue by omgold** [ValveSoftware/steam-for-linux#4984]
#### Your system information

* Steam client version (build number or date): 
1493162727
* Distribution (e.g. Ubuntu): 
Arch (kernel 4.10.13-1-ARCH, nvidia driver packages 381.22-1,
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Steam client crashes on start, when X11 color bit depth is set to 10 bit.

#### Steps for reproducing this issue:

1. Modify xorg.conf to use 10-bit color

```
Section "Screen"                                                               
    ...
    DefaultDepth 30                                                            
    ...
EndSection
```

[xdpyinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/1016017/xdpyinfo.txt)
[glxinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/1016019/glxinfo.txt)

2. try to run steam-native

[steam_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/1016016/steam_log.txt)

**Comment by kisak-valve** [comment]
Hello @omgold, this issue is already being tracked at #4399. Closing as a duplicate.
