### ISSUE TITLE
Steam won't run with optirun. (solved)

### ISSUE THREAD

**Issue by MachinaeWolf** [ValveSoftware/steam-for-linux#4987]
#### Your system information
Kernel: 4.10.15-towo.1-siduction-amd64 x86_64 (64 bit)
Machine:   Device: laptop System: Dell product: Inspiron 17-7779
CPU:       Dual core Intel Core i7-7500U (-HT-MCP-) cache: 4096 KB 
           clock speeds: max: 3500 MHz 1: 675 MHz 2: 611 MHz 3: 630 MHz 4: 638 MHz
Graphics:  Card-1: Intel Device 5916
           Card-2: NVIDIA GM108M [GeForce 940MX]
16gb ram
* Steam client version (build number or date): 
Steam package version 1493162727
* Distribution (e.g. Ubuntu): 
siduction which is debian sid based
* Opted into Steam client beta?: [Yes/No]
no
* Have you checked for system updates?: [Yes/No]
yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I can run steam fine by itself (which will only use the integrated graphics) but if I run optirun steam it gives me some errors:

ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.

If I run optirun -b primus steam it gives me a few less errors:

Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
[2017-05-21 11:45:41] Startup - updater built Apr 25 2017 22:45:11
Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.

I have even tried opening steam normally and setting the launch options to primusrun %command% and it says the game is running then quickly stops running before it even opens up a new window to run the game in. I've done this running steam from a terminal and it provided no details or errors as to why it does this.
#### Steps for reproducing this issue:

1. Running optirun steam or optirun -b primus steam or loading steam normally and running a game with launch options of primusrun %command%

**Comment by MachinaeWolf** [comment]
I even tried running as root tee /proc/acpi/bbswitch <<<ON and verifying that the nvidia card was in use with cat /proc/acpi/bbswitch but steam doesn't seem to see that I have it in use...

**Comment by snj33v** [comment]
do you have both 64bit and 32bit libs of nvidia installed?

**Comment by MachinaeWolf** [comment]
I have 
bumblebee-nvidia                                install
glx-alternative-nvidia                          install
libegl-nvidia0:amd64                            install
libegl1-glvnd-nvidia:amd64                      install
libgl1-glvnd-nvidia-glx:amd64                   install
libgl1-nvidia-glvnd-glx:amd64                   install
libgldispatch0-nvidia:amd64                     install
libglx-nvidia0:amd64                            install
libglx0-glvnd-nvidia:amd64                      install
libnvidia-eglcore:amd64                         install
libnvidia-glcore:amd64                          install
libnvidia-ml1:amd64                             install
nvidia-alternative                              install
nvidia-driver                                   install
nvidia-driver-bin                               install
nvidia-driver-libs:amd64                        install
nvidia-egl-common                               install
nvidia-egl-icd:amd64                            install
nvidia-installer-cleanup                        install
nvidia-kernel-common                            install
nvidia-kernel-dkms                              install
nvidia-kernel-support                           install
nvidia-legacy-check                             install
nvidia-modprobe                                 install
nvidia-support                                  install
nvidia-vdpau-driver:amd64                       install
xserver-xorg-video-nvidia                       install

**Comment by kisak-valve** [comment]
I'm not sure which of those would be the head package, but I'd expect nvidia-driver-libs:i386 and libglx-nvidia0:i386 would be needed.

**Comment by MachinaeWolf** [comment]
Finally!!! Seems I was just missing those, optirun -b primus steam works with 0 errors. System information on steam sees the nvidia card instead of the integrated graphics. Thank you kisak-valve :)

**Comment by kisak-valve** [comment]
Closing as this was a system issue.
