### ISSUE TITLE
Game Page endless reload loop

### ISSUE THREAD

**Issue by Witko** [ValveSoftware/steam-for-linux#4989]
#### Your system information

* Steam client version (build number or date): Apr 25, 2017 22:46:35 (would be nice if could copy from about)
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Im using external sound card and have pulseaudio at 384kHz by default(not sure it plays role)
When I view a game page in store which contains video that starts to play the whole page freezes and reloads after couple of seconds. This repeats itself endlessly. The game page does not react at all. The rest of the client works ok.

#### Steps for reproducing this issue:

1. Open Steam client
2. Go to Store
3. Open a game page with video and autoplay enabled
4. The page starts to reload endlessly

This could be potentially related to similar chromium issues which crashes completely upon sound playback unless started with [audio buffer size parameter](https://bbs.archlinux.org/viewtopic.php?id=225820)

Thank you for help!

**Comment by kisak-valve** [comment]
Hello @Witko, if this issue is related to audio like you suspect, then this may need to be addressed upstream by chromium devs.

**Comment by Witko** [comment]
Hi @kisak-valve ,
so if I understand correctly steam client uses chromium based web component, thus the error from chromium itself propagates to steam client, right? Is there an option to pass params to chromium?
Thanks!

**Comment by kisak-valve** [comment]
Steam currently uses [cef](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework) for it's web subsystem. I personally do no know of a method to pass that variable to it. We'll need to wait to hear from a Steam dev for that.

**Comment by k4os77** [comment]
* Steam client version Jun 8 2017
* Distribution (e.g. Ubuntu): Debian 9 (64bit) [XFCE]
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Game Page endless reload loop.

NOTE: **Only the beta seems affected** - **Stable version is not affected**

**Comment by k4os77** [comment]
* Steam client version Jun 21 2017 [Beta - Doesn't Work]

Last version still affected.

**Comment by Witko** [comment]
This still happens - both on nvidia proprietary drivers as well as on intel.

**Comment by kisak-valve** [comment]
Hello @Witko, @k4os77, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
