### ISSUE TITLE
Clock truncated in top right corner of non-home screen in BPM/SteamOS

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steam-for-linux#4991]
#### Your system information

* Steam client version: May 23rd beta client
* Distribution (e.g. Ubuntu):  SteamOS 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
In BPM under SteamOS (not sure about other distros), the Steam client shows odd numbers in the top right, and has for several client iterations over the past few months. When I click on Library or Store etc... It shows something like '...07' in the top right. 

#### Steps for reproducing this issue:

1.  Go to any screen but the home screen

**Comment by kisak-valve** [comment]
This is the clock. I see similar with a 1280x1024 display, and only shows ellipsis at 1920x1080.

**Comment by kisak-valve** [comment]
Issue does not occur on my Gentoo desktop, possibly font related.

**Comment by littlegamer87** [comment]
Would like to confirm this bug still exists in July 17 2017 build on SteamOS, and accidentally caught it on camera in another bug report: https://youtu.be/AJ0O14sdNeU?t=53s

The clock becomes visible when the mouse is used

**Comment by kisak-valve** [comment]
Per "Fixed a bug which caused the clock display to truncate unnecessarily." in the [2018-05-07](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1657765746057424027) Steam beta client update, please opt into Steam's beta client and retest this issue.

**Comment by mdeguzis** [comment]
woo hoo! Thanks, will update soon and report back.

**Comment by kisak-valve** [comment]
Closing as fixed in the 2018-05-07 update. If anyone happens across this issue, please open a new issue report with steps to reproduce and the screen resolution of the affected system.
