### ISSUE TITLE
Right Clicking in steam beta does not show popup.

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#4993]
Issue transferred from https://github.com/ValveSoftware/csgo-osx-linux/issues/1416.
@salamanderrake posted on 2017-05-24T15:13:05:

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):  https://gist.github.com/salamanderrake/9ce9689884873920eeadbfda71635600
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. Open up steam
2. Help -> System Information
3. Right click, not popup menu

Expected: A right click context popup menu...pops up.
Actual: Nothing happens.

**Comment by salamanderrake** [comment]
I have the same issue
 https://gist.github.com/salamanderrake/9ce9689884873920eeadbfda71635600

**Comment by salamanderrake** [comment]
Thanks for posting it here for me.

**Comment by kisak-valve** [comment]
This issue is already being tracked at #4531. Closing as a duplicate.
