### ISSUE TITLE
Camera view won't move - I can't look around me in a game. AMD graphics problem?

### ISSUE THREAD

**Issue by Leibide** [ValveSoftware/steam-for-linux#4994]
#### Your system information

* Steam client version (build number or date): 1493162727 April 25 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04.02
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

The problem is: I can not move the camera view when I move the pointer.
I can do everything else: move around, jump, duck, shoot, but I can't look around.

I've tried changing all the game settings. I've tried both the standard open source AMD driver that comes with Ubuntu 16.04.02, and the latest proprietary AMD driver. I've reinstalled Ubuntu. I've reinstalled the game. Nothing works. I'm using the proprietary driver at the moment and I've uninstalled Team Fortress after many failed efforts to the game to work.

Hardware:
Intel Pentium 4560 Processor
AMD RX 460 Graphics card
2x4Gb DDR4 Memory
MSI H110M PRO VD Motherboard

#### Steps for reproducing this issue:

1. Install game
2. Open game and start any match - practice or online game
3. The game starts and the problem is there.

**Comment by kisak-valve** [comment]
Hello @Leibide, let's continue this in the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2278.
