### ISSUE TITLE
Steam client does not support for primary selection

### ISSUE THREAD

**Issue by Sunderland93** [ValveSoftware/steam-for-linux#4995]
#### Your system information

* Steam client version (build number or date):  1493162727 25 April 2017
* Distribution: Debian 9
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam client does not support for primary selection. When I highlight text with left mouse button and then try to paste it with middle mouse button - nothing happens.

#### Steps for reproducing this issue:

1. Open Steam client and going to community forums
2. Highlight some text (message, title, etc)
3. Try to paste it to text editor (for example) with middle mouse button

**Comment by kisak-valve** [comment]
Hello @Sunderland93, this request is already being tracked at #175. Closing as a duplicate.
