### ISSUE TITLE
Steam crash when opening system information.

### ISSUE THREAD

**Issue by YangtseSu** [ValveSoftware/steam-for-linux#4996]
Archlinux,Steam runtime.

assert_20170525174808_1.dmp[27753]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170525174808_1.dmp
/home/yangtse/.local/share/Steam/steam.sh: 行 727: 27675 已放弃               (核心已转储)$STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170525174808_1.dmp[27753]: Finished uploading minidump (out-of-process): success = yes
assert_20170525174808_1.dmp[27753]: response: CrashID=bp-9abef18d-09c7-46fa-b9d9-4e39e2170525
assert_20170525174808_1.dmp[27753]: file ''/tmp/dumps/assert_20170525174808_1.dmp'', upload yes: ''CrashID=bp-9abef18d-09c7-46fa-b9d9-4e39e2170525''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:765

crash_20170525174821_2.dmp[27764]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170525174821_2.dmp
crash_20170525174821_2.dmp[27764]: Finished uploading minidump (out-of-process): success = yes
crash_20170525174821_2.dmp[27764]: response: Discarded=1
crash_20170525174821_2.dmp[27764]: file ''/tmp/dumps/crash_20170525174821_2.dmp'', upload yes: ''Discarded=1''
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
Refresh rate: 1
../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (断开的管道)

**Comment by kisak-valve** [comment]
Hello @YangtseSu, this issue is already being tracked at #4964. Closing as a duplicate.
