### ISSUE TITLE
Monitor of Pulseaudio sink with LADSPA module not working

### ISSUE THREAD

**Issue by radical-equanimity** [ValveSoftware/steam-for-linux#4997]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/radical-equanimity/a25072452f6ae6d18396f0dee3974580
* Have you checked for system updates?: [Yes/No]
Yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I run the following commands to create a pitch-shifted version of my microphone input (which I want to use in Steam). However, selecting the corresponding device in Voice options does not result in a pitch-shifted voice. Instead, the result is an unshifted voice.

pactl load-module module-null-sink
pactl load-module module-ladspa-sink master=null plugin=tap_pitch label=tap_pitch control=-8,0,-90,0 channels=1 rate=48000
pactl load-module module-loopback source=alsa_input.usb-046d_HD_Webcam_C525_46671310-00.analog-mono sink=null.ladspa latency_msec=1

#### Steps for reproducing this issue:

1. Run the above commands, subsituting channels and rate with the appropriate settings for your own microphone. Make sure to use the correct source in the last command... check output of pacmd list-sources to find out the name of your input
2. Load steam and change voice input to be Monitor of LADSPA Plugin TAP Pitch Shifter on Null Output
3. Test microphone in Steam, hear your unmodified voice

**Comment by kisak-valve** [comment]
Hello @radical-equanimity, please test if other steam games are affected. If they are, edit your opening post and replace it with the referenced issue report, otherwise we will track it in the CS:GO issue tracker. It shouldn't be tracked in both places.

**Comment by radical-equanimity** [comment]
There is evidence of an issue before even launching any game. The Steam client itself is all that's needed

**Comment by kisak-valve** [comment]
Possibly related to #4272.

**Comment by radical-equanimity** [comment]
Alright... I've figured out what's wrong. If you want to do this, you need to have a file ~/.config/pulse/default.pa with the following contents. Replace source with your actual mic device. Notice that default source is not null.lapsda.monitor but instead it is null.monitor.
`.include /etc/pulse/default.pa

load-module module-null-sink
load-module module-ladspa-sink master=null plugin=tap_pitch label=tap_pitch con$
load-module module-loopback source=alsa_input.usb-046d_HD_Webcam_C525_46671310-$

set-default-sink alsa_output.pci-0000_00_1b.0.iec958-stereo
set-default-source null.monitor`
It also turns out that in CSGO specifically, OpenAL does not allow the user to switch Pulseaudio streams by default. See the last comment here: https://github.com/ValveSoftware/csgo-osx-linux/issues/97 . To fix this, we need to create a file ~/.alsoftrc with the following contents:
`[pulse]
allow-moves=true`
Once this is done, user should enter a CSGO game with bots, enter command '+voicerecord' in console, switch to pavucontrol's Recording tab and change csgo_linux64 to capture stream to "Monitor of Null output"
