### ISSUE TITLE
Double clicking steam icon in taskbar does not open steam 

### ISSUE THREAD

**Issue by RedRain32** [ValveSoftware/steam-for-linux#4999]
#### Your system information

* Steam client version (build number or date): Beta May30
* Distribution (e.g. Ubuntu): Ubuntu 16.04lts xfce
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When steam is closed into the system tray I try to double click on the icon like in windows to open steam, instead it just opens the right click menu and closes it again.

#### Steps for reproducing this issue:

1. install steam 
2. close steam
3. double click on steam icon in tray

**Comment by kisak-valve** [comment]
Hello @RedRain32, this issue is already being tracked at #3519. Closing as a duplicate.
