### ISSUE TITLE
time stamps in 24h format

### ISSUE THREAD

**Issue by MaxPayneFH** [ValveSoftware/steam-for-linux#500]
Could you please make an option to use 24h format time stamps in steam chat instead of 12h time stamps, or some way for steam to use time stamps according to what the user has on their desktop clock.

**Comment by Dumbledorf** [comment]
This please.

**Comment by Newbie13XD** [comment]
This seems to have been fixed now, I'm using 24h timestamps in the Steam chat.

**Comment by kisak-valve** [comment]
Setting is at Friends List -> Settings gear at top right -> Chat -> Always display timestamps in 24-hour format
