### ISSUE TITLE
A random not user-friendly error

### ISSUE THREAD

**Issue by artemjackson** [ValveSoftware/steam-for-linux#5001]
#### Your system information

* Steam client version (build number or date):  1493162727
* Distribution (e.g. Ubuntu):  ArchLinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Sorry, I have no idea how to name the thread.

Sometimes I see an error probably related to Steam. It's quite difficult to determine what exactly the error belongs to cuz the error message is not user friendly. So I decided that it's a runtime error for devs or something like that.

I have no problems with it. It's just for your interesting and better UX :)
 
#### Steps for reproducing this issue:

1. Run Steam
2. Run Dota2 v7.06c
3. Randomly see the error window with strange message.

![screenshot from 2017-06-03 16-03-38](https://cloud.githubusercontent.com/assets/3768221/26755535/bcdea51e-4897-11e7-8516-412dde4bfb16.png)

**Comment by jamal-valve** [comment]
bruh what language is that??

**Comment by kisak-valve** [comment]
Hello @artemjackson, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
