### ISSUE TITLE
Video Playback in 4k

### ISSUE THREAD

**Issue by justinkterry** [ValveSoftware/steam-for-linux#5002]
#### Your system information

* Steam client version (build number or date): 1496344747
* Distribution (e.g. Ubuntu): Ubuntu Gnome 16.04.2 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
AMD Radeon RX 480, AMD Pro drivers, fully up to date.

When you playback game videos on the 4k monitor they display massively improperly in full screen mode, example here. It affects all videos.
http://i.imgur.com/J1wCQ2f.jpg

#### Steps for reproducing this issue:

1. Install updated steam on updated Ubuntu Gnome 16.04.2 LTS
2. Start playing literally any video
3. Press full screen button

**Comment by kisak-valve** [comment]
Hello @justinkterry, this issue is already being tracked at #3699. Closing as a duplicate.
