### ISSUE TITLE
Notification Area Icon Equivalent Menu Display Error in Gnome

### ISSUE THREAD

**Issue by justinkterry** [ValveSoftware/steam-for-linux#5003]
#### Your system information

Steam client version (build number or date): 1496344747
Distribution (e.g. Ubuntu): Ubuntu Gnome 16.04.2 LTS
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In windows, steam has a right clickable button with options in the notification area in windows. In the equivalent of this in Gnome, the right click display uses MS-DOS styled grey design instead of the normal steam UI design language or Gnome UI design language. Note that Gnome is the most popular UI and that Ubuntu is shipping all future versions using it.

Pictures (taken by phone because linux wouldn't let me take screenshots with the dialog open:
http://i.imgur.com/2Zt5HUK.jpg
http://i.imgur.com/q60b6hn.jpg

#### Steps for reproducing this issue:

1. sudo apt install steam on updated Ubuntu Gnome 16.04.2
2. Click on "notification area" button

**Comment by kisak-valve** [comment]
Hello @justinkterry, this is already being tracked at #1542. Closing as a duplicate.
