### ISSUE TITLE
Chinese/Japanese characters not rendering properly in chat

### ISSUE THREAD

**Issue by GUiHKX** [ValveSoftware/steam-for-linux#5005]
#### Your system information

* Steam client version (build number or date): Jun  1 2017, at 18:41:15 (Steam API v017)
* Distribution (e.g. Ubuntu): Arch Linux x64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

* I have disabled [embedded bitmap](https://wiki.archlinux.org/index.php/Font_configuration#Disable_bitmap_fonts);
* I have Arial installed, from [ttf-ms-win10](https://aur.archlinux.org/packages/ttf-ms-win10/);

* [Output of `fc-match -v Arial`](https://gist.githubusercontent.com/GUiHKX/26396788e4aba96c6eadf76b3d31a19e/raw/f3cb3a5e45a70ceba0c90907dc6d078487baa4fa/gistfile1.txt);
* I have tried installing `wqy-zenhei` fonts, but it had no effect;
* **I'm not** using any patched version of `fontconfig`.
* Font renders just fine anywhere else but in Steam Friends/Chat window:

Previews:

![screenshot_2017-06-03_18-14-37](https://cloud.githubusercontent.com/assets/626206/26757232/4f3a1f94-488c-11e7-9fe8-efa91cbbeece.png)

![screenshot_2017-06-03_18-21-47](https://cloud.githubusercontent.com/assets/626206/26757242/98eddd1a-488c-11e7-9eb9-6712a843f11b.png)

![screenshot_2017-06-03_18-24-14](https://cloud.githubusercontent.com/assets/626206/26757245/af503878-488c-11e7-8004-bea663e9ac26.png)

**Comment by kisak-valve** [comment]
Hello @GUiHKX, there may be some helpful hints in #1889.

**Comment by GUiHKX** [comment]
Thank you! I've tried some of those suggestions. None of them really worked, but some of them helped me reach a solution. If you installed `ttf-ms-win10` like I did, try the following steps to fix the rendering issue:

1. Remove all international fonts used by `ttf-ms-win10` (don't worry, this will not remove the [main fonts](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-ms-win10#n55) in the package):
```
sudo pacman -Rs ttf-ms-win10-{japanese,korean,other,sea,thai,zh_cn,zh_tw}
```
2. Install `wqy-zenhei`, which contains chinese/japanese characters ([see here for some other fonts suggestions](https://wiki.archlinux.org/index.php/fonts#Non-latin_scripts)):

```
sudo pacman -S wqy-zenhei
```

3. Restart Steam. That's it!

I don't have any knowledge about fonts, but [this comment](https://github.com/ValveSoftware/steam-for-linux/issues/1889#issuecomment-57581704) makes a lot of sense regarding the embedded bitmap thing, even though it doesn't provide an actual solution.

Anyway, I'm closing this.

**Comment by Direct-A** [comment]
> Thank you! I've tried some of those suggestions. None of them really worked, but some of them helped me reach a solution. If you installed `ttf-ms-win10` like I did, try the following steps to fix the rendering issue:
> 
> 1. Remove all international fonts used by `ttf-ms-win10` (don't worry, this will not remove the [main fonts](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-ms-win10#n55) in the package):
> 
> ```
> sudo pacman -Rs ttf-ms-win10-{japanese,korean,other,sea,thai,zh_cn,zh_tw}
> ```
> 
> 1. Install `wqy-zenhei`, which contains chinese/japanese characters ([see here for some other fonts suggestions](https://wiki.archlinux.org/index.php/fonts#Non-latin_scripts)):
> 
> ```
> sudo pacman -S wqy-zenhei
> ```
> 
> 1. Restart Steam. That's it!
> 
> I don't have any knowledge about fonts, but [this comment](https://github.com/ValveSoftware/steam-for-linux/issues/1889#issuecomment-57581704) makes a lot of sense regarding the embedded bitmap thing, even though it doesn't provide an actual solution.
> 
> Anyway, I'm closing this.

Thanks, I’ve finally soloved it, it just caused by ms-fonts(any fonts from win).
