### ISSUE TITLE
Most of Steam overlay isn't clickable

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#5006]
#### Your system information

* Steam client version (build number or date): 1/6/17
* Distribution (e.g. Ubuntu): Ubuntu gnome 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam overlay clickable options don't work for most part like view all achievements or guides, browser, music or settings work though.
I don't know if it's related bu I switched to a 4k monitor

#### Steps for reproducing this issue:

1. Launch a steam game
2. Click shift+tab
3. Try to open all achievements

**Comment by kisak-valve** [comment]
Hello @ekaris, this issue is already being tracked at #4957. Closing as a duplicate.
