### ISSUE TITLE
Borderlands 2 stops at "Downloading updates" screen if started with steam in online mode on NixOS

### ISSUE THREAD

**Issue by BoloG** [ValveSoftware/steam-for-linux#5007]
#### Your system information

* Steam client version (build number or date): Jun 1 2017
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
https://github.com/NixOS/nixpkgs/issues/25443

Borderlands 2 only runs if steam is started in offline mode (in this case it runs perfectly). In online mode it abruptly stops without any relevant log messages after "press any key" screen and after displaying "Downloading updates".  Likely the same issue as [this](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Borderlands_2) but it isn't solved by solution offered there. 

#### Steps for reproducing this issue:

1.  Start Borderland 2 with online Steam client
2. Press any key after (or skipping) the intro

**Comment by orivej** [comment]
NixOS has fixed this issue in https://github.com/NixOS/nixpkgs/pull/31480 by adding `/etc/services` into the chroot with Steam.

**Comment by kisak-valve** [comment]
Thanks for cross-referencing this @orivej, closing per https://github.com/NixOS/nixpkgs/commit/b6b931a4f9746854c493bc0d3de7a4c942100381.
