### ISSUE TITLE
Steam update knackers games on OpenSUSE 42.2

### ISSUE THREAD

**Issue by alanhants** [ValveSoftware/steam-for-linux#5009]
#### Your system information

* Steam client version (build number or date): Jun 1 2017 at 18:41:15
* Distribution (e.g. Ubuntu): OpenSUSE 42.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (all updates applied)

#### Please describe your issue in as much detail as possible:

Since the last update of the Steam client I am unable to run *any* games on my OpenSUSE 42.2 system. The client starts up fine, but executing any game results in the game crashing during its initialisation (i.e. before it attempts to grab the screen, hence no screenshots).

I have generated a log file (see https://gist.github.com/alanhants/7a5b2cf622e22e59b741005114ba1658) by running the Steam client manually in a command window. Towards the bottom of the file you will find the message "Ohhhh jeeee: ... this is a bug (global.c:137:global_init)", followed by a message indicating that a library file has an incorrect class. I suspect that this particular X marks the spot.

#### Steps for reproducing this issue:

1. Start up the Steam client on an OpenSUSE 42.2 system.
2. Start up a game.
3. Client will show the game as "Running" for a few seconds, before clearing the state indicator (this occurs after the game has crashed and a core dump generated).

**Comment by kisak-valve** [comment]
Hello @alanhants, this issue is already being tracked at #5000. Closing as a duplicate.

**Comment by alanhants** [comment]
Just updated Steam client to build  "Jun 8 2017, at 04:34:18". No change, still crashes on TF2.
