### ISSUE TITLE
Links not working in the overlay

### ISSUE THREAD

**Issue by PSeeCO** [ValveSoftware/steam-for-linux#5010]
#### Your system information

* Steam client version (build number or date): jun 1 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In the overlay clicking on "show all achievements", "show all guides", "community hub" and "go to discussions" do nothings, by the way the overlay browser works without any problem opening it clicking on "web browser" in the bottom of the screen so it just may be a linking problem of the other buttons.

#### Steps for reproducing this issue:

1. launch any game
2. shift + tab to open the overlay
3. click on the buttons to go to the achievements, guides, community or discussions pages

**Comment by kisak-valve** [comment]
Hello @PSeeCO, this issue is already being tracked at #4957. Closing as a duplicate.
