### ISSUE TITLE
My Friends can't hear my voice in game.

### ISSUE THREAD

**Issue by KsiTah** [ValveSoftware/steam-for-linux#5011]
I have been playing cs 1.6 For a long time. Now i came up on a Issue with my microphone. On the right side i See my name But can't hear any Voice, I have send transmissions to my friends And they said they can see my name but Can't Hear any voice. Whenever I write in console voice_loopback 1 It automatically turns to 0 The second i Do it. Help me.

**Comment by kisak-valve** [comment]
Hello @KsiTah, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, can you confirm that your microphone works outside of steam?

**Comment by dexter-spigot** [comment]
Try doing +voicerecord in console
Tab out and go to pavucontrol and set the recording device
Go back in and -voicerecord

See if it works

**Comment by kisak-valve** [comment]
Closing pending feedback. In general, issues with gold source games including Counter-Strike 1.6 should be reported to the [halflife](https://github.com/ValveSoftware/halflife) issue tracker.
