### ISSUE TITLE
Missing Executable for Brigador: Up-Armored Edition

### ISSUE THREAD

**Issue by rcorre** [ValveSoftware/steam-for-linux#5015]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-1
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I activated a key for "Brigador: Up-Armored Edition" from the humble bundle and installed it in steam. The download completed immediately and the game directory is empty. When I try to run it, I get a "missing executable error".  "Validate game files" does not find any errors. I can download other games sucessfully. 

#### Steps for reproducing this issue:

1. Activate Brigador
2. Install in steam
3. Try to start game

**Comment by kisak-valve** [comment]
Hello @rcorre, this issue should be brought to the attention of the game's devs.

**Comment by rcorre** [comment]
Looks like the developers resolved it.
