### ISSUE TITLE
Notification Sound can crash steam client

### ISSUE THREAD

**Issue by DefaultUser** [ValveSoftware/steam-for-linux#5016]
#### Your system information

* Steam client version (build number or date):
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Due to a bug in alsa 1.1.4 64bit and 32bit applications can not use dmix at the same time (http://mailman.alsa-project.org/pipermail/alsa-devel/2017-May/121055.html). Recieving a game invitation with notification sounds turned on will lead to the error message
`ALSA lib pcm_dmix.c:1077:(snd_pcm_dmix_open) unable to create IPC shm instance`
followed by a segfault. Disabling the notification sound will resolve the problem.

While the music player will print the same alsa error message, it will not crash the client.

The bug in alsa has been fixed with version 1.1.4.1, still, being unable to play a sound should not crash the client

#### Steps for reproducing this issue:

1. Use a 64bit system and alsa 1.1.4 (no pulseaudio) with dmix
2. start a 64bit media player and play sound with it
3. start steam client and recieve a game invitation (notification sound needs to be turned on)

**Comment by kisak-valve** [comment]
Hello @DefaultUser, this should also be brought to the attention of your distro's package maintainer for alsa.

**Comment by DefaultUser** [comment]
All alsa packages in manjaro have already been updated so that this bug is no longer triggered. However similar errors in the underlying sound libraries might cause client crashes in the future.

**Comment by kisak-valve** [comment]
Closing per the last comment. If this issue comes back in the future, it'll need a new investigation.
