### ISSUE TITLE
Last update od Steam client broke most of games

### ISSUE THREAD

**Issue by MisakCZ** [ValveSoftware/steam-for-linux#5018]
#### Your system information

* Steam client version (build number or date): 
Jun 8 2017, v017, 
* Distribution (e.g. Ubuntu): 
OpenSUSE Leap 42.2
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

I started Steam client after 2 weeks, client have done update. Most of games did not start now. 
Nothing have changed on PC, only new steam client. Via forum I have tried find solution... for some games helped for me running of steam via command STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
but this command did not help me for GRID Autosport (I have bought this game for my son at yesterday...)
I think that problem is probably with libcrypto library.

./runner: relocation error: ./runner: symbol ENGINE_load_builtin_engines, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference

1. start updated Steam client
2. start game
3. game will crash

**Comment by MKN-dev-LINUX** [comment]
Just out of curiosity have you tried reinstalling the steam client?

You can also try to reset steam:
steam --reset

A more of an extreme troubleshoot would be:

# Of course with you variant of command line syntax
sudo apt-get purge steam
sudo apt-get purge steam-devices
reboot
sudo apt-get install steam
sudo apt-get install steam-devices
reboot

Keep in mind I am not expert in any case, make sure you backup your data. GL!

**Comment by kisak-valve** [comment]
Hello @MisakCZ, this is a distro-specific issue and also being tracked at https://bugzilla.opensuse.org/show_bug.cgi?id=1032151.

**Comment by MisakCZ** [comment]
Feral gave beta patch for GRID Autosport.

We now have a beta version of an update available, which will hopefully work around the issues you have been seeing.

Please carry out the following steps:

In Steam, go to Library > All Games
Right click on GRID Autosport in the list
Select Properties from the drop down options.
Select the Beta tab.
Enter “feralsupport” into the text box and press CHECK CODE
Select "mac_linux_beta_patch" from the drop down.
Once the game has updated, launch the game

**Comment by Uramekus** [comment]
this bug is probably feral games only related and dependant on https://github.com/FeralInteractive/ferallinuxscripts/issues/2

**Comment by kisak-valve** [comment]
Hello @MisakCZ, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
