### ISSUE TITLE
Steam crashes when entering Audio Interface or Voice settings

### ISSUE THREAD

**Issue by Varstahl** [ValveSoftware/steam-for-linux#5019]
#### Your system information

* Steam client version: 1496897923 (Jun 8, 2017)
* Distribution: Debian Jessie (Linux 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64 GNU/Linux)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
This bug has been going around in various forms for more than a year, [as can also be seen here](http://steamcommunity.com/app/221410/discussions/0/458606248632117281/). By configuring the audio needs elsewhere — in my case I used _pavucontrol_ — Steam works fine and has no audio problems running or streaming games. But if the on-board is setup as 5.1, going to Interface or Voice settings will cause Steam to CTD. This has happened since the alchemists builds I initially had installed, and up until a few days ago I didn't notice that the 5.1 was responsible for it. If the on-board is instead set to 2.0 stereo, Steam doesn't crash. This happens regardless of whether Steam is actually using that audio card or not.

In my current setup I have an on-board ALC898 sound card, and an Nvidia GTX 670 which Steam is using to send the audio stream to the TV. The ALC898 is configured to send DTS 5.1 PCM through digital output signal, and is used by other home-theatre software, not Steam itself.

After reading some of the threads in here I also double checked that no fancy pulseaudio module was installed or used, but as it turned out nothing out of the bare minimum default is installed or used. It's also clear that the setup is (possibly?) not to blame since by only switching from the 5.1 digital output to the stereo digital output causes the problem to cease (I'll stress it again, even if Steam is only using the HDMI audio port provided by the graphic card). Also, just to take it out of the equation, I previously had an ATI Sapphire HD3850 which steam used with DVI video+audio to HDMI, and the same crashes were happening back then.

Let me know if I have to provide additional information or files.

#### Steps for reproducing this issue:

1. Have an on-board audio device configured for DTS 5.1
2. Load Steam BPM, navigate to Settings > Audio > Interface or Settings > Audio > Voice

**Comment by kisak-valve** [comment]
Hello @Varstahl, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, please include the tail end of `~/.steam/error.log` after this issue occurs and if you can find any CrashIDs or minidumps related to this issue, please include them as well. You can put minidumps in an archive and drag and drop the archive directly into the comment box.

**Comment by Varstahl** [comment]
As requested, [here you can find the system information](https://gist.github.com/Varstahl/f74e892c08cb19532db62f25557cb12b), and [here you can find a couple dumps](http://www.underealm.com/dd/SteamLinuxCrashDump.zip). I tried to upload the zip in here as you asked, but the darned GitHub keeps claiming they _don't support the file type_ (zip) and to _try and upload a zip_. Tried with Vivaldi, Firefox and IE, no luck, so I uploaded onto my website, it just won't work for me tonight.

Here are the crash IDs I collected (there might have been more, but I flushed the entire thing a few times while trying to figure out the nature of the problem):
```
bp-9d6fda41-cae2-4bd1-a918-4a7722170609
bp-ff1be8f9-0ea9-4037-ac6f-a3a3f2170609
bp-9a4d00f5-13dc-4e03-b99a-786df2170609
bp-2929f1ab-0668-41dd-b3db-e22c32170609
bp-9764081a-91c2-4551-9aaf-850c82170610
```

As for the log, a quick snippet (the rest is in the file):

```
crash_20170611003548_2.dmp[13488]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170611003548_2.dmp
crash_20170611003548_2.dmp[13488]: Finished uploading minidump (out-of-process): success = yes
crash_20170611003548_2.dmp[13488]: response: Discarded=1
crash_20170611003548_2.dmp[13488]: file ''/tmp/dumps/crash_20170611003548_2.dmp'', upload yes: ''Discarded=1''
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Broken pipe).  Continuing.
../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Broken pipe)
```

Just a last thing: while navigating the logs I noticed that in the various tests I might have purge the steam version from repo.steampowered.com and installed the Debian one. I assure you in any case the the problem is there with both, but I don't know if that would make a difference. If it does, I can just purge the current one, reinstall from the right repo and provide new data, just let me know.

**Comment by kisak-valve** [comment]
For reference, the three attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by kisak-valve** [comment]
Hello @Varstahl, are you still experiencing this issue on an up to date system?

**Comment by Varstahl** [comment]
Ugh, it was almost 3 years ago, I had the problem up to the point where I last used it, but I've switched systems since, I can no longer test this easily in the same conditions.

If you want I can try updating both the dismissed debian partition and steam, although I don't remember what exact hardware configuration I had back then.

**Comment by kisak-valve** [comment]
That's okay, there's no need to go out of your way and thanks for the follow up.

If someone else encounters the same issue, they can open a new issue report and we can investigate further for them.

Closing per the last comment.
