### ISSUE TITLE
Steam won't open & segfaults with i965_dri.so

### ISSUE THREAD

**Issue by pullasuti** [ValveSoftware/steam-for-linux#5020]
#### Your system information

* Steam client version (build number or date): 1496897923
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: yes and no
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Running Steam should run Steam, but it keeps crashing with a broken pipe error. 
Tried with DRI2 and 3, with "stable" and oibaf built driver, clean Steam install, Steam reset, not getting past login. Also tried installing Steam from the Ubuntu repository as well as the latest deb from Valve. Tried installing Steam for a new user, but nothing makes any difference. Every crash = intel driver segfault in system log. 

#### Steps for reproducing this issue:

1. Run Steam

Getting the same error here as issue #5008  since last night. Running Ubuntu 17.04.

`Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID: Caching Steam ID: 76561197960265728 [API loaded no]
Generating new string page texture 12: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311,30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442,37 KB
assert_20170610195010_1.dmp[13690]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170610195010_1.dmp
/home/suti/.local/share/Steam/steam.sh: rivi 727: 13617 Muistialueen ylitys (luotiin core-tiedosto) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170610195010_1.dmp[13690]: Finished uploading minidump (out-of-process): success = yes
assert_20170610195010_1.dmp[13690]: response: CrashID=bp-f9b6d52e-f76c-498b-8027-469cb2170610
assert_20170610195010_1.dmp[13690]: file ''/tmp/dumps/assert_20170610195010_1.dmp'', upload yes: ''CrashID=bp-f9b6d52e-f76c-498b-8027-469cb2170610''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:765

crash_20170610195013_2.dmp[13694]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170610195013_2.dmp
crash_20170610195013_2.dmp[13694]: Finished uploading minidump (out-of-process): success = yes
crash_20170610195013_2.dmp[13694]: response: Discarded=1
crash_20170610195013_2.dmp[13694]: file ''/tmp/dumps/crash_20170610195013_2.dmp'', upload yes: ''Discarded=1''

../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Katkennut putki)

`
Error accompanied every time with one of these:
[35092.919299] steam[13617]: segfault at 0 ip 00000000f65db1e6 sp 00000000ffcf5cc0 error 4 in i965_dri.so[f6207000+722000]

**Comment by linuxid10t** [comment]
I am having the same problem with both Intel and R600g.

**Comment by pullasuti** [comment]
I noticed that if I run Steam from the terminal with the -bigpicture switch, it runs. But as soon as I try to exit big picture mode, it breaks again. Still running in normal mode crashes every time.

**Comment by deri82** [comment]
I can confirm this bug Kaby lake gpu, mesa and the bigpicture switch does work. This is really major bug right now.

**Comment by Friz-zy** [comment]
The same problem here + black screen in bigpicture mode

Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
OpenGL version string: 3.0 Mesa 17.0.7
ubuntu kernel 4.9.0

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?
