### ISSUE TITLE
Steam can't create shortcuts

### ISSUE THREAD

**Issue by DrDoctor13** [ValveSoftware/steam-for-linux#5021]
#### Your system information

* Steam client version (build number or date): Built: Jun 8, 2017 at 04:34:18
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Installing a game will no longer create shortcuts in /usr/share/applications or ~/Desktop. Trying to click "create shortcut" in Steam triggers an error saying that a shortcut already exists. This happens with every game, either freshly downloaded or already installed. 

#### Steps for reproducing this issue:

1. Either download a game or choose an installed game in the library.
2. Right click and select Create Desktop Shortcut
3. Steam gives error: Could not create shortcut. A shortcut to this game is probably already on the desktop.

**Comment by Videonauth** [comment]
I can second that on Ubuntu 16.10, as well latest client. Weirdly removing a Game deletes as expected the short-cut from desktop, but creating always results in a message that a short-cut already exists or could not be created.

**Comment by kisak-valve** [comment]
Hello @DrDoctor13, @Videonauth, this issue is already being tracked at #5012. Closing as a duplicate.

**Comment by Fenri69** [comment]
Same issue here, Ubuntu 18.04.1 LTS

**Comment by Sebastian1978** [comment]
Confirm for Ubuntu 18.04.1 LTS

**Comment by lq95v5** [comment]
Same issue  ubuntu18.04.1 LTS
