### ISSUE TITLE
Bad font rendering for overlapping characters

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#5022]
#### Your system information

* Steam client version (build number or date): Built at: Jun 8 2017, at 04:34:18, Steam API: v017, Steam package versions: 1496897923
* Distribution (e.g. Ubuntu): Kubuntu 17.04, x86_64
* Opted into Steam client beta?: No. The problem persists with beta client as well.
* Have you checked for system updates?: Yes, the system is fully updated.

#### Please describe your issue in as much detail as possible:

Font rendering in some cases is incorrect: when adjacent characters are overlapping, the characters are rendered cropped on the sides. I've attached two screenshots that display the problem: the first is taken with the standard libfreetype from Kubuntu, the second one with libfreetype with Infinality patches. Both screenshots display the problem, but it is slightly more pronounced on the Infinality screenshot. Pay attention to the following pieces of text:

- "PAYDAY 2" on the left, in the list of games
- "PAYDAY 2" on the central panel, on the top
- "INSTALL" (the T letter) and "GAME PURCHASED" (the H letter) below the game title.

You can see some of the letters are cropped on the right side.

![steam_fonts_ubuntu](https://user-images.githubusercontent.com/1589747/27032397-466161dc-4f7d-11e7-8361-c462e0881e23.png)
![steam_fonts_infinality](https://user-images.githubusercontent.com/1589747/27032400-4b8f7fc2-4f7d-11e7-9d1e-39dfa0a2dc38.png)

#### Steps for reproducing this issue:

1. Start Steam client.
2. Font corruption may be more or less noticeable, depending on the page contents. I found it more pronounced in the Library page, PAYDAY 2 game.

**Comment by kisak-valve** [comment]
Hello @Lastique, this issue is already being tracked at #3057. Closing as a duplicate.
