### ISSUE TITLE
Steam for Linux doesn't show CD Key for Windows games

### ISSUE THREAD

**Issue by rea987** [ValveSoftware/steam-for-linux#5024]
#### System Information

* Steam client version: Jun 8 2017, at 04:34:18; Steam API: v017; Steam package versions: local
* Distribution: Ubuntu Mate 17.04 x64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### The issue in as much detail as possible:

Steam client has an option to show **CD Key** of certain games. Here are those games:

ShowCDKeyOnLaunch: https://steamdb.info/search/?a=app_keynames&keyname=179
ShowCDKeyInMenu: https://steamdb.info/search/?a=app_keynames&keyname=181

However, as I found out, **Steam for Linux** is unable to show cd keys of non-Linux titles:

Here is the CD Key output of [Warhammer 40,000: Dawn of War - Game of the Year Edition](http://store.steampowered.com/app/4570/Warhammer_40000_Dawn_of_War__Game_of_the_Year_Edition/):

- Steam for **Linux**: https://yadi.sk/i/XgOE57633K3cgM
- Steam for **Windows** via PlayOnLinux: https://yadi.sk/i/1XjAUZ4l3K3cgY

When I try to see the cd key of a Linux game, Steam for Linux instantly shows the key:

[Cities in Motion 2](http://store.steampowered.com/app/225420/Cities_in_Motion_2/) via Steam for Linux:

https://yadi.sk/i/MZ9wymlo3K3d8T

As it turned out Steam client two different method to show CD keys; **ShowCDKeyOnLaunch** and **ShowCDKeyInMenu**. Apparently, CD key "**option**" of the games that use ShowCDKeyOnLaunch method does not show up on Steam client if the games don't support that OS (eg Linux). [FlatOut: Ultimate Carnage](store.steampowered.com/app/12360/FlatOut_Ultimate_Carnage/) which uses ShowCDKeyOnLaunch method is an example of that:

Steam for Linux: https://yadi.sk/i/6lVS9Hjx3K5AiM
Steam for Windows via PlayOnLinux: https://yadi.sk/i/2NZHmMaP3K5Ai5

On the other hand, CD key option of the games that use ShowCDKeyInMenu method does appear on Steam client of all 3 operating systems, but CD key cannot be retrieved if the game does not support the operating system in question (eg Linux). Previously showed [Warhammer 40,000: Dawn of War - Game of the Year Edition](http://store.steampowered.com/app/4570/Warhammer_40000_Dawn_of_War__Game_of_the_Year_Edition/) is an example of that.

A [Feral Interactive](https://www.feralinteractive.com) employee, [edddeduck_feral](https://www.reddit.com/user/edddeduck_feral) explained the cause of the problem on Reddit:

https://www.reddit.com/r/linux_gaming/comments/6grmop/steam_for_linux_doesnt_show_cd_key_for_windows/distlgd/

. My system information via Steam client: [Github Gist](https://gist.github.com/rea987/fe150c69a717a8296e5faab25a3f5522)

#### Steps for reproducing this issue:

1. Launch Steam for Linux
2. Find a game which has [CD key](https://steamdb.info/search/?a=app_keynames&keyname=179) [option](https://steamdb.info/search/?a=app_keynames&keyname=181).
3. See if CD key option appears.
4. If CD key option is present, click it to get license code of non-Linux games.

**Comment by kisak-valve** [comment]
Hello @rea987, this issue is already being tracked at #212. Feel free to add your findings to that issue report. Closing as a duplicate.
