### ISSUE TITLE
Viewing profiles from ingame using the steam overlay is not working

### ISSUE THREAD

**Issue by JShorthouse** [ValveSoftware/steam-for-linux#5025]
#### Your system information

* Steam client version (build number or date): Jun 8 2017 04:34:18
* Distribution (e.g. Ubuntu): Xubuntu 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Attempting to view a players' profile when in game (either from the scoreboard or from the dropdown on a chat box) does nothing. The steam overlay opens but the profile is not displayed.

The ingame browser is working perfectly fine though and profiles can be view using it if the URL is copied from somewhere else.

The issue happens in CS:GO as well as GMod, I haven't tested any other games.

#### Steps for reproducing this issue:

1. Open CS:GO
2. Right click on any friends' name
3. Click "Community Profile"

**Comment by kisak-valve** [comment]
Hello @JShorthouse, this issue is fixed in the [2017-06-12](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1330099069779739080) steam beta client. Please opt into the steam beta client.

**Comment by JShorthouse** [comment]
Working as intended after installing the beta update, thanks
