### ISSUE TITLE
Steam logins but friend chat offline / Impossible to access community profiles

### ISSUE THREAD

**Issue by murkdum** [ValveSoftware/steam-for-linux#5026]
AMD FX6300 + R7 240 2gb + 8GB Ram ddr3

* Steam client version (build number or date): Jun 8 2017, 04:34:18 API v.017 
* Distribution (e.g. Ubuntu): Tested on Ubuntu Gnome 16.04, 16.10 and 17.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

This are two distinct issues.

Both happen on Ubuntu 16.04, 16.10 and 17.04 and are independent of DE used.

When steam starts, the friend chat is always offline by default. I installed steam with wine to see if it happens on both native and windows version but nope. Only the native linux version starts and needs me to click to sign in so that I can see my friends.

The second issue is a bit more annoying. Also tested on 16.04, 16.10 and 17.04. I cannot open community profiles. If I play dota2 and want to check the steam profile, the steam overlay opens but only shows the default things (friends, time and shortcuts) - It doesn't open the profiles. Same happens on csgo, If I press tab and right click to open community profile of a player (from my team or enemy team), steam overlay shows up and does nothing. Links to the community market are also not working, if a game has a function to open community market or discussions, the overlay opens but doesn't load any page nor does the browser show up.

The only way to access community profiles is to ask a team mate or friend to post link on chat, so that I can open steam overlay, press browser, and paste the link to access the profile. 

Issue #1
1. Start Steam
2. Press login on friend chat

Issue #2 
1. Press "open/see community profile"
2. Press "open community page of game x"

**Comment by kisak-valve** [comment]
Hello @murkdum, In the future, please limit issue reports to one issue per report. Only the first issue will be tracked in this issue report.

That said, there is a config option at `Steam` -> `Settings` -> `Friends` -> `Automatically sign into Friends when I start Steam`. Please confirm that box is checked.

The second issue was tracked at #4957 and is fixed in the 2017-06-12 steam beta client.

**Comment by murkdum** [comment]
Solved. This is rather dumb, I don't remember having it turned off. And the
windows version on wine logged in by default.

Regarding the second issue, the issue will be solved on the next stable
version of the client?

Em 14/06/2017 21:39, "kisak-valve" <notifications@github.com> escreveu:

**Comment by kisak-valve** [comment]
Changes to the steam beta client periodically are pushed to the stable release of the client.

**Comment by murkdum** [comment]
Thanks then

Em 14/06/2017 22:02, "kisak-valve" <notifications@github.com> escreveu:
