### ISSUE TITLE
Steam launcher not starting in linux mint 18.1 Cinnamon (v.3.2.6)

### ISSUE THREAD

**Issue by fuzzly98** [ValveSoftware/steam-for-linux#5027]
#### Your system information

* Steam client version (build number or date): most recent build available at the steam download page as of 15/6-2017
* Distribution (e.g. Ubuntu): Linux Mint 18.1 Cinnamon (v.3.2.6)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### 
I have downloaded and installed the steam-launcher package from the official website several times but whenever i try to "execute" the installed file (I'm new to Linux, don't know what to call it since there are apparently no executables) it responds with nothing. I've googled around for a bit and purghed the file a few times but still there's no window opening.

Is there another version i should install or is there something else I'm missing?

All help is appreciated

#### Steps for reproducing this issue:

1. Downloading the package in debian form
2. Installing the package
3. attempting to start the launcher

**Comment by kisak-valve** [comment]
Hello @fuzzly98, open Software Manager, search for steam, double click on "Steam" in the search results, and click the Install button.

**Comment by fuzzly98** [comment]
@kisak-valve wow, thanks a bunch :)

**Comment by kisak-valve** [comment]
Closing per the last comment.
