### ISSUE TITLE
Can not use the ^ charakter in csgo (key binding)

### ISSUE THREAD

**Issue by Falseee** [ValveSoftware/steam-for-linux#5029]
#### Your system information

* Steam client version (build number or date):  1497312328 
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I cant use the ^ character for key binding (use microphone)

#### Steps for reproducing this issue:

1. Open CS:GO
2. Go to the keyboard Settings
3. Try to set the ^

**Comment by kisak-valve** [comment]
Hello @Falseee, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/523. Closing as a duplicate.
