### ISSUE TITLE
steamcommunity.com malicious website blocked

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5031]
#### Your system information

* Steam client version (build number or date):  8 June
* Distribution (e.g. Ubuntu): UBuntu 16.04.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
https://i.imgur.com/A9O4GLf.png

#### Steps for reproducing this issue:

1. Use norton's DNS
2.  Load steam
3.  malicious website blocked page appears

**Comment by kisak-valve** [comment]
Closing because the user has turned into a ghost.
