### ISSUE TITLE
Text not rendered in steam client

### ISSUE THREAD

**Issue by enderleseb** [ValveSoftware/steam-for-linux#5033]
#### Your system information

* Steam client version (build number or date):  Cannot get the version because of the bug
* Distribution (e.g. Ubuntu): openSUSE Leap 42.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

As I tried to start Steam, all seemed to work. But as the window opened I only saw a mostly empty window. The only textures I was able to see weren't in any language, they are only random symbols.

![Screenshot](https://user-images.githubusercontent.com/20817574/27255829-9feff4a2-53a6-11e7-8007-094e657c4c60.png)

The most interesting part of the log was this: `/usr/share/themes/Adwaita/gtk-2.0/main.rc:728: error: unexpected identifier 'direction', expected character '}'`

#### Steps for reproducing this issue:

1. Have/Install openSUSE Leap 42.2
2. Install Steam
3. Start the Client
4. Wait until the window opens

**Comment by kisak-valve** [comment]
Hello @enderleseb, is this a new steam install or a regression? Did you install steam via your distro's package manager?

**Comment by enderleseb** [comment]
@kisak-valve As I saw it, I tried to reinstall Steam. The version before and after the reinstallation is downloaded and installed via the standard package manager. So it should be the newest Steam version. The fix for the mentioned issue didn't work.

**Comment by enderleseb** [comment]
The text rendered after I did a distribution update (`sudo zypper dup`). All works fine now!
