### ISSUE TITLE
[CS1.6] crash on de_aztec if cl_weather is "3"

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#5034]
#### Your system information

* Steam client version (build number or date): June 12 2017
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

If you set the cl_weather cvar to "3", the game will crash within a matter of minutes, sometimes seconds.

#### Steps for reproducing this issue:

1. Set "cl_weather 3" in console
2. Wait for the crash

My system specs are in my Steam profile, which is linked in my GitHub.

**Comment by kisak-valve** [comment]
Hello @shoober420, let's track this issue in the halflife issue tracker at https://github.com/ValveSoftware/halflife/issues/1812.
