### ISSUE TITLE
[big picture] web browser broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5038]
up-to-date beta steamos
up-to-date beta steam client

go browse twitch.tv in the web brower of the big picture client: it will crash or get corrupted.
AMD GCN1 hardware (tahiti xt), either on 
radeon linux module or amdgpu linux module

**Comment by sylware** [comment]
the last update did even broke youtube videos (and more opening a new bug)

**Comment by sylware** [comment]
I tried to go back to the non-beta steam client (at the time of writing), the web component is still broken!

**Comment by ardje** [comment]
I can confirm that on a zotac sn970 steam machine switching to beta, reboot and immediately play a video from youtube (works), then switching back (left shoulder) to the main window leaves a lot of corruption in the main screen. The browser window seems fine though.
This is with nvidia 381.22 and steamos beta.
This corruption appear to me as nvidia driver bugs, as when I do desktop and switch resolutions it is easy to get corruption like this, but now it seems this might not be a driver bug at all ;-).

**Comment by ardje** [comment]
![meeh](https://user-images.githubusercontent.com/4538490/27732496-d8cb0c86-5d91-11e7-8749-7bee525a6264.png)
![meeh2](https://user-images.githubusercontent.com/4538490/27732495-d8c9aaee-5d91-11e7-91d8-bdbdc098ec36.png)

**Comment by sylware** [comment]
Then it means that the bugs are either or in both:
 - in CEF code/integration.
 - driver (userland/kernel) code shared by the AMD/nvidia drivers (I recall
   that the 3D stack is BSD licensed, meaning nvidia certainly hides a lot of
   open source code).

**Comment by sylware** [comment]
wow, cannot even go in the account settings... it's crashing the client.
I know the "modern" web (aka javascript) is one of the worst thing this planet ever created... but there it seems to be a nastier issue. The "web" client should suffer the same issues if big picture is using the same web component.

**Comment by sylware** [comment]
Was asked through the dota2 issues to re-test the new stable steam client: the web component is working now.

**Comment by sylware** [comment]
latest _stable_ steam client: the web component broke like the _beta_ steam client.
dota2 web market is then broken.

**Comment by kisak-valve** [comment]
Hello @sylware, please retest with the 2017-07-11 steam beta client.

**Comment by sylware** [comment]
fixed
