### ISSUE TITLE
Opening any game's store page freezes the browser

### ISSUE THREAD

**Issue by JacobSvenningsen** [ValveSoftware/steam-for-linux#5039]
#### Your system information
CPU: AMD Ryzen 1700x 
GPU: Radeon 270x using the Padoka PPA (commit 79bd1d4)
Kernel: Linux 4.12.0-rc2

* Steam client version (build number or date): Built Jun 21 2017, at 21:32:32
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I went to the store page and clicked on any game. When I went to the game's page, the steam browser became unresponsive. I can still open up my own profile, library and the community, but I cannot interact with any store page, which also means I cannot actually purchase any game.

#### Steps for reproducing this issue:

1. Opt into Beta
2. Go to Store
3. Click any game to go to the store page
4. Browser becomes unresponse and the following error gets written to stdout:
`[0622/105529.245937:ERROR:gl_implementation.cc(246)] Failed to load /home/USERNAME/.local/share/Steam/ubuntu12_64/swiftshader/libGLESv2.so: /home/USERNAME/.local/share/Steam/ubuntu12_64/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory`

Creating the swiftshader directory and symlinking both libEGL.so and libGLESv2.so from the parent directory fixes the issue. Symlinking the files provided by the GPU driver fixes the issue as well.
If only libGLESv2.so gets linked, it'll then just complain about missing libEGL.so, so both libraries are required.

**Comment by k4os77** [comment]
Is this related to #4989 ?

**Comment by JacobSvenningsen** [comment]
It could be. Disabling autoplay seems to avoid the issue, and as soon as you click play a video, it will once again complain about missing libraries. So I guess they're related in that way

**Comment by kisak-valve** [comment]
Hello @JacobSvenningsen, does adding the `libgles2-mesa-dev` package to your system help? It looks like Debian packages libGLESv2.so in that package (compared to libGLESv2.so.2 which is in the `libgles2-mesa` package). Also, both library name variants are provided by the nvidia proprietary package.

**Comment by JacobSvenningsen** [comment]
Nope, doesn't fix the issue. Symlinking `libGLESv2.so.2` does fix the issue if the link is renamed to `libGLESv2.so.2`, which makes sense since the `libGLESv2.so` file included with `libgles2-mesa-dev` is just a symlink to the same file `libGLESv2.so.2` is. Both are links to `libGLESv2.so.2.0.0`.

Without manually creating the `swiftshader` directory and linking the libraries, the same error gets written to stdout

**Comment by kisak-valve** [comment]
Also seen on my Gentoo mesa/r600g laptop and with Ubuntu 17.04 and mesa on #5044. Mesa users are affected while nvidia proprietary users are not.

**Comment by kisak-valve** [comment]
Closing as fixed in the 2017-07-06 steam beta client.
