### ISSUE TITLE
Bug at OpenSuse 42.2 (64 bit)

### ISSUE THREAD

**Issue by fzzio** [ValveSoftware/steam-for-linux#5040]
#### Your system information

* Steam client version (build number or date): Built Jun 8 2017, at 04:34:18 - SteamAPI v017
* Distribution (e.g. Ubuntu): OpenSuse 42.2 x86_64, KDE Desktop
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Attachments: [steamBug.txt](https://github.com/ValveSoftware/steam-for-linux/files/1099901/steamBug.txt)

#### Please describe your issue in as much detail as possible:
Hello Steam team

I am a user of OpenSuSe (linux) and today I installed steam and I bought a video game called LIMBO. Apparently I'm having a problem and not letting me play. I attached the screenshot of the Linux Terminal with what it shows me every time I try to play.

`GameAction [AppID 48000, ActionID 2] : LaunchApp changed task to Starting with ""
GameAction [AppID 48000, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 48000, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 48000, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 48000, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 48000 "LIMBO", ProcID 12537, IP 0.0.0.0:0 `

`>>>Adding process 12537 for game ID 48000
GameAction [AppID 48000, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/usuario/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 48000, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/usuario/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored. `

`>>>Adding process 12538 for game ID 48000
Game update: AppID 48000 "LIMBO", ProcID 12538, IP 0.0.0.0:0
Setting breakpad minidump AppID = 48000
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198098844360 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(20170608043310)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
libgcrypt selftest: binary  (0): No such file or directory
Ohhhh jeeee: ... this is a bug (global.c:137:global_init)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Game removed: AppID 48000 "LIMBO", ProcID 12538 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)`

I also have another news, in the time counter in steam only tells me that I have played 1 minute the game. That happens because the game is not opened.

#### Steps for reproducing this issue:

1. Open Steam Client
2. Click to Play any game
3. Bug

**Comment by kisak-valve** [comment]
Hello @fzzio, this issue is being tracked at #5000. You can workaround this issue by completely closing steam , then running steam with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal.

Closing as a duplicate.

**Comment by fzzio** [comment]
Hi @kisak-valve 
I just checked the # 5000 and did everything that was indicated but it still does not work for me. I'm still giving this problem.
[Link]https://gist.github.com/fzzio/d9f2fc8049dce3721d741617a5564736)
