### ISSUE TITLE
Steam Client crash after login

### ISSUE THREAD

**Issue by threexone** [ValveSoftware/steam-for-linux#5041]
#### Your system information

* Steam client version (build number or date): 1496897923
* Distribution :  Fedora 25 64bits
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For days since the last update I had to reselect the language for steam and most of the time to type my username. It was annoying but i could do with it. Same issue than this one : #5035 

Since this morning, the steam client does not log in. It said that that the network is not reachable and offered to log offline. Now it just crashes after login.

I don't know if this problem is linked with #5035 or not. But as it is, i can't use steam at all. 

Here is the messages that appear in the terminal when executing steam client : [Gist ](https://gist.github.com/threexone/71a13447c775079f587a07f5f53ee19f)

**Comment by kisak-valve** [comment]
Hello @threexone, can you do a quick test to see if steam starts up with your steam controller disconnected?

**Comment by threexone** [comment]
Hello,

Thanks for the quick response.

Same problem without the controller : [Gist](https://gist.github.com/threexone/0b886d5453248598a8d6e139ae21dec4)

**Comment by threexone** [comment]
Hi,

The problem had to do with the files related to my account. I tried to connect with a different account and it worked.

So I deleted the folder of my account in ".steam/steam/userdata". Steam has downloaded a new folder and now it works.

Problem fixed for me. I can use steam has usual.

**Comment by kisak-valve** [comment]
Glad to hear you got things working, but there's not much more that can be done here in terms of figuring out what went wrong since as you say, the problem files was deleted.

If anyone else stumbles upon this issue report and has the same issue, please set aside the folder, try to isolate which file steam is having trouble with and open a new issue report.

Closing as resolved.
