### ISSUE TITLE
Left 4 Dead 2 the main menu music does not exit.

### ISSUE THREAD

**Issue by YasheshRathod** [ValveSoftware/steam-for-linux#5042]
#### Your system information

* Steam client version (build number or date): Jun 8 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After downloading and starting the game for the first time I noticed that the main menu music was not playing. Checked for the integrity of the files but nothing happened. The problem persisted. My hardware specs are as below.

CPU: i5 4440
GPU: Nvidia Geforce GTX 1050
Motherboard: GA-B85M-D3H (Gigabytye)
RAM: 4GB
Monitor: HD TV (ONIDA)

I am using DVI(GPU) to HDMI(HD TV) cable. Everything else works fine but only in this game Left 4 Dead 2 the problem dwells heavily, Which is the missing main menu music. Such a problem never occurred in the windows version of this game.
 
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @YasheshRathod, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/416. Closing as a duplicate.
