### ISSUE TITLE
Game application window wont launch 

### ISSUE THREAD

**Issue by bensohyh** [ValveSoftware/steam-for-linux#5043]
#### Your system information

* Steam client version (build number or date):  1496897923 Jun 8 2017
* Distribution (e.g. Ubuntu):  Centos 7 centos-release-7-3.1611.el7.centos.x86_64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes. 

#### Please describe your issue in as much detail as possible:
I recently ran an update on centos 7 and reinstalled Nvidia drivers. However, when I tried to launch dota2 it failed. So I decided to perform a complete reinstallation of steam and dota, but sadly that didn't fix my issue. I tried changing Nvidia drivers.
-NVIDIA-Linux-x86_64-375.66.run  (FROM)
- NVIDIA-Linux-x86_64-381.22.run (CURRENT)

I wished I had kept my old kernel before removing it.  Any help is appreciated....

Running Steam on centos 7 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)

(steam:7958): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(steam:7958): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)

** (steam:7958): WARNING **: Unknown device type 13

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:7958): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:7958): WARNING **: Unknown device type 14

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/0: unknown object type

** (steam:7958): WARNING **: Unknown device type 13

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:7958): WARNING **: Unknown device type 16

** (steam:7958): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198177984301 [API loaded no]

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Unknown setting 'bridge'

** (steam:7958): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Unknown setting 'bridge'

** (steam:7958): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/3 settings: (3) type

** (steam:7958): WARNING **: Ignoring invalid property 'interface-name'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'assigned-mac-address'

** (steam:7958): WARNING **: Ignoring invalid property 'mac-address-randomization'

** (steam:7958): WARNING **: Ignoring invalid property 'secondaries'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'

** (steam:7958): WARNING **: Ignoring invalid property 'addr-gen-mode'

** (steam:7958): WARNING **: Ignoring invalid property 'route-data'

** (steam:7958): WARNING **: Ignoring invalid property 'address-data'
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
Installing breakpad exception handler for appid(steam)/version(1496897923)

(steam:7958): GLib-GObject-WARNING **: gsignal.c:2516: signal 'child-added' is invalid for instance '0xf84a40e8' of type 'GtkMenu'
Installing breakpad exception handler for appid(steam)/version(1496897923)
roaming config store loaded successfully - 708 bytes.
migrating temporary roaming config store
Failed to init SteamVR because it isn't installed
Installing breakpad exception handler for appid(steam)/version(1496897923)
ExecCommandLine: "'/home/bsoh/.local/share/Steam/ubuntu12_32/steam'"
Installing breakpad exception handler for appid(steam)/version(1496897923)
System startup time: 4.09 seconds
Generating new string page texture 73: 128x256, total string texture memory is 442.37 KB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 64x256, total string texture memory is 507.90 KB
Generating new string page texture 76: 32x256, total string texture memory is 540.67 KB
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 87: 8x256, total string texture memory is 548.86 KB
ExecSteamURL: "steam://openurl/http://store.steampowered.com/app/633890?snr=1_41_4__42"
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 121: 128x256, total string texture memory is 679.94 KB
Generating new string page texture 122: 128x256, total string texture memory is 811.01 KB
Generating new string page texture 124: 48x256, total string texture memory is 860.16 KB
Generating new string page texture 131: 384x256, total string texture memory is 1.25 MB
Generating new string page texture 132: 24x256, total string texture memory is 1.28 MB
Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8104, IP 0.0.0.0:0
>>> Adding process 8104 for game ID 570
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8106 != 8105, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8108 != 8105, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 2] : LaunchApp changed task to Completed with ""
>>> Adding process 8105 for game ID 570
>>> Adding process 8107 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8104 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8117, IP 0.0.0.0:0
>>> Adding process 8117 for game ID 570
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8119 != 8118, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8121 != 8118, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 8118 for game ID 570
>>> Adding process 8120 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8117 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 6] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 6] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8229, IP 0.0.0.0:0
>>> Adding process 8229 for game ID 570
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8231 != 8230, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8233 != 8230, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 6] : LaunchApp changed task to Completed with ""
>>> Adding process 8230 for game ID 570
>>> Adding process 8232 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8229 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1496897923)
Installing breakpad exception handler for appid(steam)/version(1496897923)
Generating new string page texture 139: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 140: 256x256, total string texture memory is 1.54 MB
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to Starting with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to UpdatingAppInfo with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 570, ActionID 8] : LaunchApp waiting for user response to CreatingProcess ""
GameAction[AppID 570, ActionID 8] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 570 "Dota 2", ProcID 8238, IP 0.0.0.0:0
>>> Adding process 8238 for game ID 570
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 8240 != 8239, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/bsoh/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long
pid 8242 != 8239, skipping destruction (fork without exec?)
GameAction [AppID 570, ActionID 8] : LaunchApp changed task to Completed with ""
>>> Adding process 8239 for game ID 570
>>> Adding process 8241 for game ID 570
Game removed: AppID 570 "Dota 2", ProcID 8238

**Comment by kisak-valve** [comment]
Hello @bensohyh, `/home/bsoh/dota/steamapps/common/dota 2 beta/game/dota.sh: line 101: /home/bsoh/dota/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2: Argument list too long` in your log sounds like the culprit here, but it's not immediately clear why you are encountering that.

If you run `getconf ARG_MAX` in a terminal, do you get a reasonably high number? (It's 2097152 on the system I'm writing from). Do you have something abnormal set in the game's launch options?

**Comment by bensohyh** [comment]
Yes, I get 2097152.  I've cleared the game launch options to default and even deleted the autoconfig.cfg file was used.

**Comment by bensohyh** [comment]
I tried running team fortress and it loaded fine in opengl.
Maybe something broke with the dota script?

**Comment by bensohyh** [comment]
Well, Guess I'm going to take a drastic route of reformatting and do a fresh installation to fix this. Wish me luck :D

**Comment by bensohyh** [comment]
Ah! Sadly, it didn't work either.

**Comment by bensohyh** [comment]
I'm posting the issue here instead: 
https://github.com/ValveSoftware/Dota-2/issues/1258
