### ISSUE TITLE
Steam browser unresponsive in game store page

### ISSUE THREAD

**Issue by xksteven** [ValveSoftware/steam-for-linux#5044]
#### Your system information

* Steam client version (build number or date): Jun 21 2017, package version 1498083198
* Distribution: Ubuntu 17.04
* Opted into Steam client beta?: beta Yes
* Have you checked for system updates?: Yes, system is up to date

#### Please describe your issue in as much detail as possible:
After the steam summer sale started, I get the following errors when visiting a games store page.  It prevents me from making purchases and doing anything on a store page.

`threadtools.cpp (1343) : Assertion Failed: Thread synchronization object is unuseable
cef_clienthandler.cpp (2088) : Assertion Failed: killing unresponsive browser for URL http://store.steampowered.com/app/app_number/app_name`

I use this ppa for my mesa drivers. https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa

Update: 
I get the same issue when trying to watch a friends stream via stream broadcasting.  So it seems like the issue has to do with steam's browser and videos.

#### Steps for reproducing this issue:

1. Start steam
2. Visit any games store page

Might be related to #5039

**Comment by kisak-valve** [comment]
Hello @xksteven, symptom-wise, this is an exact match to #5039 in what is happening and that mesa users are affected, but nvidia proprietary users are not. Let's track this on that issue report.
