### ISSUE TITLE
Steam Overlay Buttons dont open browser

### ISSUE THREAD

**Issue by ibrokemypie** [ValveSoftware/steam-for-linux#5045]
#### Your system information

* Steam client version (build number or date):  1.0.0.54 62c554c
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In games such as Team Fortress 2, clicking buttons in the overlay which should bring up windows, such asa any of the guides, achievements, players, trade windows etc, does nothing. Nothing seems to open anything in inbuilt browser asside from the browser button itself. This makes it impossible to trade normally in TF2,and very difficult to navigate to the guides and achievements which are sitting right there in front of you.

#### Steps for reproducing this issue:

1. Run TF2
2.  Open steam overlay
3.  Click any guide or achievement.

**Comment by ibrokemypie** [comment]
Problem fixed in steam beta it seems.

**Comment by kisak-valve** [comment]
Hello @ibrokemypie, yes this issue was tracked at #4957 and the fix is already in the beta client. Closing as a duplicate.
