### ISSUE TITLE
Steam Client crash at the entrance to the Big Picture

### ISSUE THREAD

**Issue by Wolfen113** [ValveSoftware/steam-for-linux#5046]
#### Your system information

* Steam client version (build number or date): 1496897923
* Distribution:  Linux 4.11.6-3-ARCH
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Google translator
In the period from 9 to 10 June a problem arose which could not be solved until now.
  When you try to open the Big Picture or, apply the settings that require the client to reboot. Client steams hangs and throws out after a while.
During the problem, it is noted how the RAM is filled with dumps.
  If you run the settings menu of the Steam controller through the settings - controller. The opened Big Picture window works for a few minutes before hanging and crashing

#### Steps for reproducing this issue:
1. Trying to launch big picture manager
2. Attempt to apply settings that require the client to reboot. Such as, change the version to beta, change the language of the client.
3. Trying to run the settings big picture manager or settings steam controller

#### How did you try to solve the problem before applying?
1. Asked advice from friends with the same problem. No one does not have it.
2. I deleted the steam and cleaned his catalogs, put it again. I did not go over the beta version and back
2. I applied to technical support steam. They advised to apply here

#### Files that indicate an error
1. Terminal output.
https://www.dropbox.com/s/m0y9bomf0nk9j42/Steam%20Error.txt?dl=0
https://www.dropbox.com/s/bhx5ssockc19o9b/Steam%20error2.txt?dl=0
2. Pacman log. Presumably updates that the client could break
https://www.dropbox.com/s/3ydukm5r51sdope/Pacman.txt?dl=0
3. Picture an example of a problem
https://www.dropbox.com/s/g2os8qt197sf3s7/St%20BPM%20Error.png?dl=0

**Comment by kisak-valve** [comment]
Hello @Wolfen113, thanks for the detailed report. This sounds like it's the same issue as https://github.com/ValveSoftware/csgo-osx-linux/issues/1438, which is fixed in upstream openal, but the next point release of openal has not yet occurred.

Like that CS:GO issue, can you downgrade openal to 1.17.2-1 and see if that resolves your issue?

**Comment by Wolfen113** [comment]
Hello @kisak-valve Thank you for responding. I downgrade openal to 1.17.2-1. But unfortunately it did not help me :(

**Comment by kisak-valve** [comment]
Did you test downgrading both the 32 bit and 54 bit variants? (lib32-openal)

**Comment by Wolfen113** [comment]
@kisak-valve  No. Again downgrade openal including lib32-openal. It works now!
Thank you, thanks and thanks again :)

**Comment by guihkx** [comment]
This has been fixed a long time ago so it can be closed now.

**Comment by guihkx** [comment]
@kisak-valve 

Wolfen113 [said](https://github.com/ValveSoftware/steam-for-linux/issues/5046#issuecomment-311411620) that downgrading both `openal` and `lib32-openal` fixed the issue for him, which matches the symptoms of issue #1438, which was fixed two years ago.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
