### ISSUE TITLE
Playing a game before it is fully installed defaults to windows launch behaviour

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#5048]
#### Your system information

* Steam client version (build number or date): Jun 8 2017
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
If you play a game while it is installing, and select the launch when ready option, it will use the windows platform launch configuration. This does not seem to reproduce for games that are already installed and require patching. This happened with Circuits, and I reproduced it with the game Darwinia for this issue.

#### Steps for reproducing this issue:

1. Hit play and it prompts to install the game.
2. While the game is installing, hit play again.
3. Select the [] Launch when ready option in the Updating %game% dialogue
4. Once game is downloaded, it will complain about missing executable *binary.exe*
5. Hit play and the game will launch correctly.

![screenshot 2017-06-27 191525](https://user-images.githubusercontent.com/7708/27603491-c7f0c0d2-5b65-11e7-84d8-1acf9b99f493.png)

![screenshot 2017-06-27 185338](https://user-images.githubusercontent.com/7708/27603499-cc8a6da0-5b65-11e7-99ce-9a1372bc5c15.png)

**Comment by kisak-valve** [comment]
Hello @johndrinkwater, are you still experiencing this issue on an up to date system? You may need to run `steam steam://run/<appid>` to get the dialog box to to pop up.

**Comment by kisak-valve** [comment]
Closing pending feedback.
