### ISSUE TITLE
[big picture] steam voice broken

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5050]
At the time of writing this issue, the last beta client update did broke steam voice.

up-to-date beta steamos (gpu is amd tahiti xt)
up-to-date beta client

I have an usb mic, last update broke the ability of steam voice able to use it.
In the voice settings, I have the hdmi/radeon audio device, my motherboard hdaudio, and my usb mic (actually the usb mic of my webcam).
Usually I select the webcam and it works (I can check that with the test). Now it's seems ignoring my setting and goes for the audio input of my hdaudio motherboard device instead of the usb mic.

**Comment by sylware** [comment]
tested with the _stable_ steam client, it's broken there too.

**Comment by sylware** [comment]
It's still weird, but I can manage to make my usb webcam
mic work again. I'll do more testing is the next few days (i.e. dota2 voice).
(The weirdness is once I selected and tested the usb webcam mic, if I leave the voice settings and come back... my built in audio (intel HDA realtek codec) is shown as my voice device... but if I don't touch it and does a test, it is still my usb webcam mic which is actually used.
In the voice device drop down, I have in order:
amd tahiti xt hdmi/displayport
build in audio
webcam usb audio

**Comment by kisak-valve** [comment]
Hello @sylware, are you still encountering this issue on an up to date system?

**Comment by sylware** [comment]
the big picture UI for chat was removed and replaced with the new web chat UI.

tested today, it works because I am able to select the right input device (or
build a proper "virtual" alsa device to trick much software into working):

I still have weird capture device names in the input selection drop box: for
each alsa device with capture capabilities, I actually get 2 or 3 with
different suffixes: -default, -front-speakers, -digital-spdif.

It should be probably only the version with the default suffix I guess (namely
using the plug/dsnoop devices/plugins). Or pertinent suffixes
("-front-speakers" suffix is clearly not pertinent for a capture device
name, or spdif for a usb mic neither).

**Comment by kisak-valve** [comment]
Thanks for retesting. I'm going to close because the original issue has been resolved.

**Comment by sylware** [comment]
On Fri, Feb 14, 2020 at 10:02:09AM -0800, kisak-valve wrote:
> Thanks for retesting. I'm going to close because the original issue has been resolved.

Indeed, I think I did report already the misleading entries in the input entry
drop boxes elsewhere.
