### ISSUE TITLE
Steam launcher scripting to install 32 bit opengl drivers is broken on KDE Neon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by 200Puls** [ValveSoftware/steam-for-linux#5052]
#### Your system information

* Steam client version (build number or date): 
current version
* Distribution (e.g. Ubuntu): 
KDE Neon (Ubuntu 16.04 64 bit with up-to-date kde)
* Opted into Steam client beta?: [Yes/No]
no
* Have you checked for system updates?: [Yes/No]
yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I downloaded the steam client from the website and it wouldnt start. It always said that it failing to find a driver.

Then I tried installing from mulltiverse. This also didnt work.  Failed to load steamui.so. I finnaly got it running by manually installing dependencies:
sudo apt-get install libc6:i386 libgl1-mesa-dri-lts-utopic:i386 libgl1-mesa-glx-lts-utopic:i386
sudo apt-get install libgl1-mesa-glx-lts-utopic:i386

I read that steam is supposed to open a console to install these. This didnt happen. I found this thread (https://steamcommunity.com/discussions/forum/1/154643795212078209/) 

"you may want to bring this to Steam's attention. Preliminary investigation suggests that steam's installer attempts to call konsole with a --nofork option which hasn't existed in quite a while. Calling with an unsupported option makes konsole not start which in turn prevents the automatic installation of dependencies."

Maybe its related?

**Comment by kisak-valve** [comment]
Hello @200Puls, are you still experiencing this issue on an up to date system?

**Comment by 200Puls** [comment]
Hi @200Puls,

on my current setup (Kubuntu 19.10) I'm not experiencing these issues anymore.

**Comment by kisak-valve** [comment]
Thanks for the follow up, closing.
