### ISSUE TITLE
Steam beta crash when paticipating in user survey / showing system information

### ISSUE THREAD

**Issue by af7567** [ValveSoftware/steam-for-linux#5053]
#### Your system information

* Steam client version (build number or date): Beta Jun 28 2017, at 21:35:54
* Distribution (e.g. Ubuntu): Slackware64 current
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I logged into steam and got asked to participate in the survey, so I accepted.  After showing the second screen with the system info steam crashed when I clicked the next button. 
After restarting steam I was given the survey and it crashed again, this time I didn't actually click the next button on the system info page, I just held the mouse button down on it without releasing.
Restarted again and this time clicked the next button as quickly as possible and it seemed to complete the survey OK, (although I didn't get any questions about broadband speed and microphone like I have when running steam client in wine)

I just opened the system information screen to copy paste it here and steam crashed again, so it seems to be the system info dialog that is causing problems.

minidumps attached
[sysinfocrash.zip](https://github.com/ValveSoftware/steam-for-linux/files/1116733/sysinfocrash.zip)

**Comment by kisak-valve** [comment]
Hello @af7567, this is most likely the same issue as #4856 or #4964.

For reference, all the attached asserts are SIGABRTs in libc-2.25.so.

**Comment by af7567** [comment]
Yes, this does seem to be the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/4964.  If I just open the system info window it sometimes crashes after a few secs, if I change desktops then it crashes immediately.

**Comment by kisak-valve** [comment]
Thanks for checking, let's track this on the existing issue report.
