### ISSUE TITLE
Using ingame overlay freezes game randomly

### ISSUE THREAD

**Issue by nagger420** [ValveSoftware/steam-for-linux#5054]
#### Your system information
https://gist.github.com/nagger420/7acce4634db9831e25410da94113ccb5

* Steam client version (build number or date): 
Built Jun 8 2017 at 04:34:18
* Distribution (e.g. Ubuntu): 
Debian 9 Stretch + Plasma 5
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes and system is up to date

#### Please describe your issue in as much detail as possible:
At least while playing CSGO, use of overlay can cause the game to freeze fully, and the process of the game must be killed and the game needs to be started again. It happens randomly, and it is always when the overlay is open so I suspect it has something to do with overlay as this issue never has happened while not in overlay. It is fully random, it can suddenly just freeze right after opening the overlay or after using it for quite a long time, I havent found a way to trigger it every time but it does happen often enough that I prefer to alt+tab out of the game to use chat etc. to avoid freezes. I know at least 2 other people who run Debian 9 and have AMD graphics card and use AMDGPU drivers and have the same issue happening to them, if the hardware/software has something to do with the issue

#### Steps for reproducing this issue:

1.  Open in-game overlay
2.  Use it and have it open
3.  It freezes the whole game randomly at some point

**Comment by kisak-valve** [comment]
Hello @nagger420, this issue is being tracked at #4933. Closing as a duplicate.
