### ISSUE TITLE
Steam/Wine: Opening Library Folder in 32-bit Prefix Deletes All 64bit Apps w/o Warning

### ISSUE THREAD

**Issue by starlightknight** [ValveSoftware/steam-for-linux#5055]
#### Your system information

* Steam client version (build number or date): 
Jun 7 2017 / Wine Staging 2.10
* Distribution (e.g. Ubuntu): 
Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:

Just trying to play some Windows only games with Wine. A growing number of games are shipping 64-bit only now. Wine 32-bit still works better for most things, so it is generally preferable for 32-bit apps. However, if you import a steam library folder that has 64-bit only games downloaded inside of it, Steam instantly deletes all of the 64-bit games data without warning. I lost >100GB of game data in the blink of in eye with NO WARNING. This is a BAD default behavior, especially since games can already pop up a warning saying it doesn't support 32-bit operating systems. For god's sake please just do this instead of deleting all data. Especially for those of us with bandwidth caps, losing over 100GB of data just from opening steam is a disaster.

#### Steps for reproducing this issue:

1. Have a steam drive.
2. Have a few 64-bit only games in there
3. Import your steam drive as a library folder in 32-bit Wine
4. Cry when you realize all data was destroyed without warning

**Comment by kisak-valve** [comment]
Hello @starlightknight, this issue is already being tracked at #2812. Closing as a duplicate.

**Comment by starlightknight** [comment]
@kisak-valve #2812 is for trying to share Linux & Windows library which is a different and more complex use case in my opinion (have both binaries downloaded and share assets) - as there are all kinds of potential file system and permission issues in doing that. 

This bug report is for all Windows binaries, just 32bit versus 64bit, on a normal NTFS drive. Same thing would happen if you dual booted 32bit & 64bit Windows, though I don't know why you would normally do that - the primary way you'd hit this seems to be Wine on Linux, as it would be common there. 

Also, that bug report goes back to 2013... personally I think its awful that valve would leave a severe data loss bug around THAT long. I don't know about you, but I don't think software wiping out 10's to 100's of GB of data just from being opened is EVER an acceptable scenario. As a developer by trade, I'm shocked that in 4 years Valve can prioritize and figure out a way to say if(os.platform == 'x86') { don't delete x64 data };

Forgive me if I'm appearing rude in this response but, I just lost 100+GB of data and will now be spending the forseeable future re-downloading it, while Valve has just pointed me to a 4 year old issue.
