### ISSUE TITLE
Delayed chat history opens a chat window

### ISSUE THREAD

**Issue by vfjpl** [ValveSoftware/steam-for-linux#5056]
#### Your system information

* Steam client version (build number or date): 02.07.2017
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. Open chat window
2. Close it before chat history is loaded
3. Chat window will open again by itself

**Comment by kisak-valve** [comment]
Hello @vfjpl, are you still experiencing this issue on an up to date system?

**Comment by vfjpl** [comment]
No, I think it is no longer relevant :)
It haven't happened to me on new steam chat.
