### ISSUE TITLE
Credential verification is failing in client

### ISSUE THREAD

**Issue by FurretUber** [ValveSoftware/steam-for-linux#5058]
#### Your system information

* Steam client version (build number or date): 08 Jun 2017
* Distribution (e.g. Ubuntu): Xubuntu 17.04 amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After I log in on Steam client, I can choose to play games, chat with my friends and see the store and community. However, I am unable to publish on community or see my notifications, because it tries to verify the credentials and then fail saying there was a problem when communicating with the Steam servers.

When connecting from internet navigator, I can successfully publish in community.

This problem started today.

Expected behavior: once logged in the Steam client, I would be able to have full access to my account, being able to publish in communities.

Observed behavior: I have limited access, being unable to publish in communities and to see new notifications.

#### Steps for reproducing this issue:

1. Log in Steam client;
2. Tries to access notifications or tries to publish in a community;
3. Notice how it says "Please wait" and then an error saying it was unable to connect to Steam servers appear.

**Comment by kisak-valve** [comment]
Hello @FurretUber, this should be the same issue as #4971. Does `sudo apt install libnss-resolve:i386` in a terminal and restarting steam help? (from https://github.com/ValveSoftware/steam-for-linux/issues/4971#issuecomment-303506713)

**Comment by FurretUber** [comment]
Installing the package `libnss-resolve:i386` have solved this problem, now I can see the notifications again. Why this package was not required until 2 days ago?

Thank you.

**Comment by kisak-valve** [comment]
Most likely there was no change to cause this issue on your system and there was a DNS change in steam's servers which the client was failing to follow.

Thanks for testing the workaround, closing in favor of #4971.
