### ISSUE TITLE
Steam BigPicture interfering with F710 input.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5059]
#### Your system information

* Steam client version (build number or date): Jun 8 2017, at 04:34:18
* Distribution (e.g. Ubuntu): Mint 18.1 (Ubuntu 16.04)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I switched over to using a Logitech F710 with my HTPC. It works flawlessly with all my games, except when I run them through Steam in BigPicture mode. I have to go through Steam's controller config and set it to work as a Xbox 360 gamepad to make it work with games. Even then, some older games still don't work with it.

I tried going into Steam's gamepad settings and disabling Configuration Support, but that just makes it so it doesn't work at all in any games. Like I said, if I run my games without Steam, it works fine with all my games (that can run without Steam anyway), even ones that I can't get working at all with the gamepad when Steam is running.

Is there a way to have Steam just treat the gamepad like it would a Logitech F310? That's what I was using before and it worked fine.

#### Steps for reproducing this issue:

1. Have a Logitech F710 gamepad connected and setup.
2. Start Steam in BigPicture mode.
3. Try running older linux games with it.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
