### ISSUE TITLE
Controller unintentional register

### ISSUE THREAD

**Issue by vfjpl** [ValveSoftware/steam-for-linux#5063]
#### Your system information

* Steam client version (build number or date): 1496897923
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Xbox 360 controller is always registering in steam desktop mode. In Big picture it stays unregistered.
#### Steps for reproducing this issue:

1. unregister your controller
2. unplug
3. plug again

**Comment by kisak-valve** [comment]
Hello @vfjpl, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
