### ISSUE TITLE
[Suggestion] Platform-Agnostic Downloading

### ISSUE THREAD

**Issue by KevinAT** [ValveSoftware/steam-for-linux#5064]
Allow everyone, regardless of their OS and architecture to download any game/software files.

If you select an on your system unsupported game, it should say that it won't be able run without further input from the user, but still allow to download its files. I'd like to have the ability to download all os versions of a game (Windows, Linux/SteamOS, and even macOS if available), no matter what OS i'm using when I initiate the download. Even when i'm using an OS for which the game is available i'd like to be able to download it for others too. When I pay for a game or software on Steam, i pay for the ability to legally download and use that software, it shouldn't be any of Steams/Valves concern which OS i'm using at that time.

Steam works with little effort under Wine, and I've never heard of Valve banning anyone for using it. So apparently they don't have a problem with their users downloading games for other OSs than they currently use, which makes it even more ridiculous to not have this feature.

**Comment by kisak-valve** [comment]
Hello @KevinAT, this feature request is already being tracked at #4442. Closing as a duplicate.

**Comment by roman-yagodin** [comment]
Vote for it!
