### ISSUE TITLE
Steam ask for login every update + Steam reinstall game instead of launching/updating them

### ISSUE THREAD

**Issue by theo546** [ValveSoftware/steam-for-linux#5065]
#### Your system information

* Steam client version (build number or date): 1499120811
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No]: Yes
* Have you checked for system updates?: [Yes/No]: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When i try to start / update a game, steam is redownloading the game (17gb for Payday 2).
And when steam is updating, it ask for login after the update, even if i check remember password.

#### Steps for reproducing this issue:

For the reinstall bug: Just update a game
For the update bug: Just update steam and it will ask login

![capture du 2017-07-06 19-22-19](https://user-images.githubusercontent.com/16925280/27923956-770ac9a2-6280-11e7-8a24-dfc21090ecf7.png)

**Comment by kisak-valve** [comment]
Hello @theo546, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, what filesystem are you using with the steam library that has Payday 2 and how much space is free?

Separately, reporting multiple issues per issue report is bad for any issue tracker. Only the first issue will be tracked in this issue report.

**Comment by theo546** [comment]
Hi, i can't get these information, the Steam client crash one i enter this :/

**Comment by Zamundaaa** [comment]
it seems like the error I get (#5123) is strongly correlated with your reinstall error

**Comment by theo546** [comment]
Well, this issue is no more.
