### ISSUE TITLE
CSGO Competitive Queue Crash after todays patch

### ISSUE THREAD

**Issue by ddemoss** [ValveSoftware/steam-for-linux#5067]
#### Your system information

* Steam client version (build number or date):  steam api: v 017; steam package versions: 1496897923
* Distribution (e.g. Ubuntu): ubuntu
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Support sent me here from an open ticket regards to CSGO.

Basically, since the new patch today, i can enter search queue for a CSGO competitive match, and when it finds a match (via the textual updates on queueing) then the whole CSGO app crashes without any notice to me. 

I never had this issue prior to the new patch. 

#### Steps for reproducing this issue:

1. Open CSGO
2. Comp match search queue
3. ...crash!

thanks!

**Comment by kisak-valve** [comment]
Hello @ddemoss, this issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1461 and it being looked into per https://github.com/ValveSoftware/csgo-osx-linux/issues/1461#issuecomment-313815880. Closing as a duplicate.
