### ISSUE TITLE
CSGO for MAC/LINUX: Crashing when trying to confirm match

### ISSUE THREAD

**Issue by FelipeNBrito** [ValveSoftware/steam-for-linux#5068]
#### Your system information

* Steam client version (build number or date): 7/7/2017 update
* Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Zeenbook
Memory: 7,7 GiB,
Processor: Intel® Core™ M-5Y10c CPU @ 0.80GHz × 4,
Graphics: Intel® HD Graphics 5300 (Broadwell GT2),
OS: Ubuntu 16.04 LTS 64-bit
Disk: 73,9 GB of 243 GB used 

The game was running great until now. I played one competitive round earlier today, and when tried to play another, it asked to restart the game due to needed updates. After the update, I open the game on competitive lobby and it starts searching for a game. Whenever it finds a match, before I'm able to click on the green start button, it crashes with no error message.

Community discussion about this issue: https://steamcommunity.com/app/730/discussions/0/1457328392104774997/ 

#### Steps for reproducing this issue:

1. Enter a lobby for a competitive match.
2. Wait until a match is found.
3. Crashes when the match is found.

**Comment by kisak-valve** [comment]
Hello @FelipeNBrito, this issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1461 and it being looked into per https://github.com/ValveSoftware/csgo-osx-linux/issues/1461#issuecomment-313815880. Closing as a duplicate.
