### ISSUE TITLE
Waylad Display Server Protocol Support

### ISSUE THREAD

**Issue by DmitryHetman** [ValveSoftware/steam-for-linux#5070]
#### Your system information
Gentoo GNU/Linux nomultilib, Weston Window Manager.
* Steam client version (build number or date):
any 
* Distribution (e.g. Ubuntu): 
Gentoo GNU/Linux Nomultilib
* Opted into Steam client beta?: [Yes/No]
no
* Have you checked for system updates?: [Yes/No]
yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Steam uses deprecated X11 (xorg) as display server. On any modern DE, WM it's not able to launch.
#### Steps for reproducing this issue:

1. Install any GNU/Linux distribution
2. Install any modern DE
3. Install Steam
4. Can't find display server, crash.

Please make sure that you switched Steam to Wayland.
https://wayland.freedesktop.org/
https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)
https://jan.newmarch.name/Wayland/ProgrammingClient/

**Comment by kisak-valve** [comment]
Hello @DmitryHetman, this feature request is already being tracked at #4924. Closing as a duplicate.
