### ISSUE TITLE
Portal 2 run and close in a second.

### ISSUE THREAD

**Issue by SupremeTamer** [ValveSoftware/steam-for-linux#5073]
#### Your system information

* Steam client version (build number or date): 2016-12-05
* Distribution (e.g. Ubuntu): Ubuntu 17.10
    Ubuntu Artful Aardvark (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.11.0-10-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  GNOME Shell
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

CPU Brand:  Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Memory:
    RAM:  7906 Mb

Video Card:
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD TAHITI (DRM 2.49.0 / 4.11.0-10-generic, LLVM 5.0.0) (0x6798)
    Version: 17.2.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD TAHITI (DRM 2.49.0 / 4.11.0-10-generic, LLVM 5.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.0-devel - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 3.0 Mesa 17.2.0-devel - padoka PPA
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.0-devel - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

#### Please describe your issue in as much detail as possible:
Portal 2 runs and close in a second
[lshw.txt](https://github.com/ValveSoftware/steam-for-linux/files/1139547/lshw.txt)
[steam_system_information.txt](https://github.com/ValveSoftware/steam-for-linux/files/1139548/steam_system_information.txt)

**Comment by kisak-valve** [comment]
Hello @SupremeTamer, this issue is being tracked at https://github.com/ValveSoftware/portal2/issues/248 and can be worked around by removing the game bundled libstdc++.so.6. Closing as a duplicate.

**Comment by SupremeTamer** [comment]
Thanks, removing **libstdc++.so.6** file from game folder helped.
