### ISSUE TITLE
1.Not working Russian chat/Не работает русский чат/Не видно русских ников

### ISSUE THREAD

**Issue by one-developers** [ValveSoftware/steam-for-linux#5074]
#### Your system information

* Distribution (e.g. Ubuntu,Debian,Papermint,Mint Debian Edition): 
![730_screenshots_20170711012326_1](https://user-images.githubusercontent.com/24843984/28090753-35b96d36-66af-11e7-9f96-20f3c2082e47.jpg)

Доброго времени суток. У меня в Counter-Strike: Global Offensive возникли проблемы. А именно:
1.Не работает русский чат
2.Не отображаются ники игроков в которых присутствуют русские символы
Использую систему Linux Mint Debian (LMDE)
(3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux)
4.Почему такое сильное различие в FPS между Linux и Windows?
в Windows у меня FPS 240+ а в Linux 150-170? Версия драйверов 375.66
-------------------------------------------------------------------------
Good time of day. I have counter-strike: global offensive problems. Namely:
1.Not working Russian chat
2.Not displayed the nicknames of the players, in which there are Russian characters
I use Linux mint Debian (LMDE)(3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) architecture x86_64 GNU/Linux)
4.Why such a strong difference in FPS between Linux and Windows?
in Windows my FPS 240+ and Linux 150-170? Drivers 375.66

**Comment by kisak-valve** [comment]
Hello @one-developers, let's track this issue in the CS:GO issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1476.
