### ISSUE TITLE
Skins not detected

### ISSUE THREAD

**Issue by Shadlock0133** [ValveSoftware/steam-for-linux#5079]
#### Your system information

* Steam client version (build number or date): 1499823214
* Distribution (e.g. Ubuntu): ubuntu 17.04 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Tried installing [Air](https://github.com/outsetini/Air-for-Steam/wiki) skin for Steam. After putting skin folder into "~/.local/share/Steam/skins" and restarting Steam skin doesn't show up in skin dropdown menu. Tried restarting Steam multiple times, tested also with [Metro](http://www.metroforsteam.com/).

#### Steps for reproducing this issue:

1. Put Air skin folder into "~/.local/share/Steam/skins" folder
2. Restart Steam
3. Open Setting > Interface > Skin
4. Shows only \<default skin\> entry

**Comment by awlayton** [comment]
I seem to have this issue as well. Was pointed here from Outsetini/Air-for-Steam#161.

### Your system information

Steam client version (build number or date): 1503954609
Distribution (e.g. Ubuntu): Ubuntu 16.04.3 64-bit
Opted into Steam client beta?: [Yes/No] Yes
Have you checked for system updates?: [Yes/No] Yes

**Comment by awlayton** [comment]
I got it to work if I instead put the Air folder in `~/.steam/skins/`. Not sure if this is a bug or feature or what.

**Comment by Shadlock0133** [comment]
Can confirm that putting skin folder into ```~/.steam/skins``` does indeed work.

**Comment by Chase78712002** [comment]
I got it working by making a directory called 'skins' in `~/.steam/steam/`
