### ISSUE TITLE
Steam Overlay screenshot doesn't work consistently in HL2 Episode 2

### ISSUE THREAD

**Issue by marc2377** [ValveSoftware/steam-for-linux#5080]
System information: https://gist.github.com/marc2377/18f12f5609af38da031e92f42337b70f/

Steam client version: 1499997556
Distribution: Arch Linux
Steam Beta: No
Checked for system updates: Yes

In Half-Life 2 Episode 2 for Linux, the f12 key won't take screenshots as it's supposed to do.

At first, it made the game unresponsive (stopped responding, had to be force closed). I tested many times.

Then, after restarting the computer, now it:
- Sometimes it takes one screenshot successfully and all subsequent screenshots won't work until the game is restarted
- Sometimes it takes _two_ screenshots successfully, and all subsequent screenshots won't work until the game is restarted
- In most cases, screenshot doesn't work at all, until the game is restarted.

I was previously running the amdgpu kernel driver. Then I switched to the radeon driver (I have Southern Islands) but the issue persists.

I have xorg-server 1.19.3 and mesa 17.1.4. Kernel is linux-mainline 4.12.0.

I tried assigning another key in the Steam Preferences, as well as disabling the sound feedback and the notification. Issue is still present.

In Team Fortress 2, issue is not present (screenshot works).

#### Steps for reproducing this issue:

1. Launch Half-Life 2: Episode 2 in Linux
2. Try to get a couple of screenshots with the F12 key

**Comment by marc2377** [comment]
Now **_this_** is interesting.

This is the specific scene where the f12 action halts the game, forcing me to press ALT+F4 a few times in order to force-close:

![ep2_outland_030000](https://user-images.githubusercontent.com/8507649/28236498-195cdba4-68fe-11e7-99c3-ec2d31232585.jpg)
(this is chapter "This Vortal Coil", in map "ep2_outland_03").

That was taken with the built-in screenshot functionality (f5 key), which works correctly.

Attempting to grab an screenshot of the same area with the f12 key crashes **every time**.

The funny thing is, doing the same thing a few steps further away from the wall, does not freeze the game.

This is the closest I could get f12 to work (even though only one time, or twice at most, as I said previously):
![20170715012835_1](https://user-images.githubusercontent.com/8507649/28236559-1a90149a-68ff-11e7-8bae-e5a14ff1f32a.jpg)

**Comment by kisak-valve** [comment]
Hello @marc2377, this issue is already being tracked at #4928. Closing as a duplicate.
