### ISSUE TITLE
steam prevent my system to shutdown

### ISSUE THREAD

**Issue by kjwz** [ValveSoftware/steam-for-linux#5081]
#### Your system information

* Steam client version (build number or date): 2017 jul 14
* Distribution (e.g. Ubuntu): mint
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

if i try click a shutdown button in my mint(kde version)
steam blocks my system to turn off at first .
so i have to click again to actually shutdown.
it only happen when steam is running.
and it's been really annoying..

**Comment by kisak-valve** [comment]
Hello @kjwz, this issue is already being tracked at #3301. Closing as a duplicate.
