### ISSUE TITLE
steam://open/newforyou does not work with notify about changes unchecked

### ISSUE THREAD

**Issue by guihkx** [ValveSoftware/steam-for-linux#5086]
#### Your system information

* Steam client version (build number or date):  Jul 17 2017
* Distribution (e.g. Ubuntu):  Arch Linux x64
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
The **"Update News"** option located in the **"View"** menu does nothing when clicked on. Plus, clicking that option makes the entire menu kind of freeze, so you have to open the **"View"** menu again to unfreeze it.

#### Steps for reproducing this issue:

1. Open **View** > **Update news**
2. Alternatively, open **steam://open/newforyou**
3. Nothing will happen
3. The **View** menu will "freeze"

**Comment by kisak-valve** [comment]
Hello @GUiHKX, there appears to be some other factor involved to cause this issue. I was not able to reproduce this issue on my Arch test box, among other test boxes.

Please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by GUiHKX** [comment]
Sorry, I forgot about that! But it won't be needed anymore, I know what is causing this.

If you go to **Settings** > **Interface** and untick the option *"Notify me about additions or changes to my game, new releases, and upcoming releases"*, the *Update news* option in the menu will stop working.

**Comment by GUiHKX** [comment]
Sorry, I forgot about that! But it won't be needed anymore, I know what is causing this.

If you go to **Settings** > **Interface** and untick the option *"Notify me about additions or changes to my game, new releases, and upcoming releases"*, the **Update news** option in the menu will stop working.

**Comment by kisak-valve** [comment]
This is a cross-platform issue.

**Comment by Zorrototo** [comment]
This doesn't work at all wether I have ticked or unticked the setting "Notify me about additions or changes to my games, new releases, and upcoming releases".

**Comment by Managor** [comment]
I can confirm this is still the case.

**Comment by Zorrototo** [comment]
And can you try now? Apparently it now works (see the link above in my issue).

**Comment by Managor** [comment]
Still nothing. When the option is unticked, the news popup does not appear.

**Comment by Zorrototo** [comment]
what Steam version?
![Screenshot_20191013_052820](https://user-images.githubusercontent.com/17416415/66710507-56d36b80-ed7a-11e9-83e4-f411ecd7bdaf.png)

**Comment by Managor** [comment]
This seems to be fixed.

**Comment by guihkx** [comment]
Confirming it's fixed. Tested on:

```
Steam Version:  1687015240
Steam Client Build Date:  Sat, Jun 17 11:53 UTC -03:00
Steam Web Build Date:  Fri, Jun 16 21:51 UTC -03:00
Steam API Version:  SteamClient020
```
