### ISSUE TITLE
IPC error: LockMgrMutex failed to acquire SysMgrMutex

### ISSUE THREAD

**Issue by Mad-Hacker** [ValveSoftware/steam-for-linux#5089]
#### Your system information

* Can't tell
* Debian
* No
* Yes

#### Please describe your issue in as much detail as possible:
When I am starting steam from the command line I get this

Installing breakpad exception handler for appid(steam)/version(1500335472)
IPC error: LockMgrMutex failed to acquire SysMgrMutex

The IPC line just loops over and over in the output.

**Comment by kisak-valve** [comment]
Hello @Mad-Hacker, there's not much to go on here, can you give a better description of your system?

Is this a new install or a regression? If this is a new install, how did you install steam? Was it with a distro-provided package or the Valve-provided package? OpenGL driver/vendor are you using?

**Comment by Mad-Hacker** [comment]
This installation is about a year old.
It was installed via a .deb download from the steam webpage.
Distro is Debian buster/sid
OpenGL version string: 4.5.0 NVIDIA 375.66

If you need anything else I can provide more information.

**Comment by kisak-valve** [comment]
Can you try to run `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal and see if it makes a difference?

**Comment by Mad-Hacker** [comment]
Gave it a shot:

With STEAM_RUNTIME_PREFER_HOST_LIBRARIES:
`/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on debian  64-bit                                                   
/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically                                            
/bin/bash: /home/madhacker/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc           
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc           
grep: symbol lookup error: grep: undefined symbol: pcre_jit_stack_alloc           
awk: /home/madhacker/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
Installing breakpad exception handler for appid(steam)/version(1500335472)        
Installing breakpad exception handler for appid(steam)/version(1500335472)        
Installing breakpad exception handler for appid(steam)/version(1500335472)        
Installing breakpad exception handler for appid(steam)/version(1500335472)        
sh: /home/madhacker/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by sh)
/bin/bash: /home/madhacker/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
IPC error: LockMgrMutex failed to acquire SysMgrMutex`

Without:
`/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on debian  64-bit                                                   
/home/madhacker/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically                                            
Installing breakpad exception handler for appid(steam)/version(1500335472)        
Installing breakpad exception handler for appid(steam)/version(1500335472)      
Installing breakpad exception handler for appid(steam)/version(1500335472)        
Installing breakpad exception handler for appid(steam)/version(1500335472)        
IPC error: LockMgrMutex failed to acquire SysMgrMutex `

**Comment by Mad-Hacker** [comment]
Also tried complete reinstallation via repository and via .deb download from the steam webpage. Both resulting in the same error.

**Comment by Mad-Hacker** [comment]
Any news on the front? Is it a bigger problem or is there a fast hotfix/hack which can solve this problem?

**Comment by jackyko1991** [comment]
same issue here, install from .deb file from steam offical site
reinstall the file does not help

**Comment by avindra** [comment]
Seeing this on openSUSE Tumbleweed now. Not sure what's causing it or how to fix it.

**Comment by bbarker** [comment]
Seems to have resolved for me.

**Comment by gladstonedigital** [comment]
Same problem on Debian. I had steam running, then exited it and relaunched it. When I went to relaunch it I encountered this problem and now I can't get it to start

**Comment by gladstonedigital** [comment]
@kisak-valve @triage-valve any word on this issue?

**Comment by gladstonedigital** [comment]
Found a suggestion to try `steam --reset`, which made some movements like it might fix it but... reset finished and the issue remains. Still can't get steam to launch, still getting that IPC error. I've paid for these products from you guys and it really sucks not being able to use something that you paid for, with no messages from Valve about it for 6 months. You guys working on this?

**Comment by Fireshadow3** [comment]
I just had the same problem on Chakra Linux, a fork of Arch Linux.
See the file [LOG.txt](https://github.com/ValveSoftware/steam-for-linux/files/1648921/LOG.txt) for the log.
If, as suggested by Kisak, I put in console the command `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` then steam works fine. Here is the output of the working Steam (see [LOG2.txt](https://github.com/ValveSoftware/steam-for-linux/files/1648922/LOG2.txt)).
I installed Steam from the official Chakra repository, and the version is `1.0.0.54-4`.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?
