### ISSUE TITLE
Steam don't lunch

### ISSUE THREAD

**Issue by ad1rie1** [ValveSoftware/steam-for-linux#5091]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.54-10.fc26.src.rpm
* Distribution (e.g. Ubuntu):  fedora 26 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When i lunch steam i have this : 

Steam dont lunch after clear install . 
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)

Nothing else append

i'm on intel cpu gen 7 with bumblebee. But it append also on my main workstation on nvidia card

#### Steps for reproducing this issue:

1. dnf install steam
2. steam

**Comment by kisak-valve** [comment]
Hello @ad1rie1, can you try to run `LIBGL_DRI3_DISABLE=1 steam` from a terminal? If that helps, then you should only need to use the workaround once. (from #4816)

**Comment by ad1rie1** [comment]
nothing change with your command. Do you have another idea ?

[uranium@Uranium-PC ~]$ LIBGL_DRI3_DISABLE=1 steam
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)

**Comment by ad1rie1** [comment]
Can i have a méthod for get more log ? Or verify all dependencie are installed ?

**Comment by kisak-valve** [comment]
For the most part, all that steam requires beyond the dependencies that are provided by the package is a working 32 bit opengl driver. You could double check that you have the driver packages that apply to you in the 'Before you Install' section of https://linuxconfig.org/installing-steam-on-fedora-25-linux.

**Comment by gidoBOSSftw5731** [comment]
I'm having the same issue, I also found this: `$ steam -textclient
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1500335472)
Installing breakpad exception handler for appid(steam)/version(1500335472)
Installing breakpad exception handler for appid(steam)/version(1500335472)
Installing breakpad exception handler for appid(steam)/version(1500335472)
Failed to load steamconsole.so - dlerror(): steamconsole.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1500335472)
[2017-07-25 13:15:43] Startup - updater built Jul 17 2017 23:10:02
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-07-25 13:15:43] Checking for update on startup
[2017-07-25 13:15:43] Checking for available updates...
[  0%] Checking for available updates...
[2017-07-25 13:15:43] Download skipped: /client/steam_client_ubuntu12 version 1500335472, installed version 1500335472
[2017-07-25 13:15:43] Nothing to do
[2017-07-25 13:15:43] Verifying installation...
[----] Verifying installation...
[2017-07-25 13:15:43] Performing checksum verification of executable files
[2017-07-25 13:15:44] Verification complete
[----] !!! Fatal Error: Failed to load steamconsole.so
[2017-07-25 13:15:44] Shutdown
` So whatever this steamconsole.so is its borked af

**Comment by ad1rie1** [comment]
héhé it's not the same issue because i have no information at all. on your, you have a steam version . I think you're good to delete your local steam folder. or if you have the file steamconsole.so, find him with : find / -name "steamconsole.so"

if you have this file, use ldd to verify you have all dependencie installed

**Comment by ad1rie1** [comment]
@kisak-valve , i have already installed this dépendencie :/

**Comment by ad1rie1** [comment]
@kisak-valve i have more information about my problem , i have found the debug mode :) 
this is my error : 
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2017-07-26 10:16:04] Startup - updater built Nov 23 2016 01:05:42
Installing breakpad exception handler for appid(steam)/version(0)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

Do you have that file ?

**Comment by ad1rie1** [comment]
@kisak-valve , no error in debug log , do you have an idea ? : 
LIBGL_DRI3_DISABLE=1 steam
+ export TEXTDOMAIN=steam
+ TEXTDOMAIN=steam
+ export TEXTDOMAINDIR=/usr/share/locale
+ TEXTDOMAINDIR=/usr/share/locale
+ ARCHIVE_EXT=tar.xz
+++ dirname /home/uranium/.local/share/Steam/steam.sh
++ cd /home/uranium/.local/share/Steam
++ echo /home/uranium/.local/share/Steam
+ STEAMROOT=/home/uranium/.local/share/Steam
+ '[' -z /home/uranium/.local/share/Steam ']'
+ STEAMDATA=/home/uranium/.local/share/Steam
+ '[' -z ']'
++ basename /home/uranium/.local/share/Steam/steam.sh .sh
+ STEAMEXE=steam
+ '[' steam = steamcmd ']'
+ cd /home/uranium/.local/share/Steam
+ export SYSTEM_PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/uranium/Qt/5.7/gcc_64/bin:/home/uranium/.local/bin:/home/uranium/bin:/home/uranium/Qt/5.7/gcc_64/bin
+ SYSTEM_PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/uranium/Qt/5.7/gcc_64/bin:/home/uranium/.local/bin:/home/uranium/bin:/home/uranium/Qt/5.7/gcc_64/bin
+ export SYSTEM_LD_LIBRARY_PATH=
+ SYSTEM_LD_LIBRARY_PATH=
++ uname
+ UNAME=Linux
+ '[' Linux '!=' Linux ']'
++ detect_platform
++ platform=ubuntu12_32
++ case "$(detect_distro)-$(detect_release)" in
+++ detect_distro
+++ '[' -f /etc/lsb-release ']'
+++ '[' -f /etc/os-release ']'
+++ . /etc/os-release
++++ NAME=Fedora
++++ VERSION='26 (Twenty Six)'
++++ ID=fedora
++++ VERSION_ID=26
++++ PRETTY_NAME='Fedora 26 (Twenty Six)'
++++ ANSI_COLOR='0;34'
++++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
++++ HOME_URL=https://fedoraproject.org/
++++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++++ REDHAT_BUGZILLA_PRODUCT=Fedora
++++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
++++ REDHAT_SUPPORT_PRODUCT=Fedora
++++ REDHAT_SUPPORT_PRODUCT_VERSION=26
++++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
+++ echo fedora
+++ tr '[A-Z]' '[a-z]'
+++ detect_release
+++ '[' -f /etc/lsb-release ']'
+++ '[' -f /etc/os-release ']'
+++ . /etc/os-release
++++ NAME=Fedora
++++ VERSION='26 (Twenty Six)'
++++ ID=fedora
++++ VERSION_ID=26
++++ PRETTY_NAME='Fedora 26 (Twenty Six)'
++++ ANSI_COLOR='0;34'
++++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
++++ HOME_URL=https://fedoraproject.org/
++++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++++ REDHAT_BUGZILLA_PRODUCT=Fedora
++++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
++++ REDHAT_SUPPORT_PRODUCT=Fedora
++++ REDHAT_SUPPORT_PRODUCT_VERSION=26
++++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
+++ echo 26
++ echo ubuntu12_32
+ PLATFORM=ubuntu12_32
++ echo ubuntu12_32
++ grep 32
+ PLATFORM32=ubuntu12_32
++ echo ubuntu12_32
++ grep 64
++ true
+ PLATFORM64=
+ '[' -z ubuntu12_32 ']'
+ '[' -z '' ']'
++ echo ubuntu12_32
++ sed s/32/64/
+ PLATFORM64=ubuntu12_64
+ STEAMEXEPATH=ubuntu12_32/steam
+ STEAMCONFIG=/home/uranium/.steam
+ PIDFILE=/home/uranium/.steam/steam.pid
+ STEAMBIN32LINK=/home/uranium/.steam/bin32
+ STEAMBIN64LINK=/home/uranium/.steam/bin64
+ STEAMSDK32LINK=/home/uranium/.steam/sdk32
+ STEAMSDK64LINK=/home/uranium/.steam/sdk64
+ STEAMROOTLINK=/home/uranium/.steam/root
++ detect_steamdatalink
++ '[' -f /home/uranium/.local/share/Steam/steam_dev.cfg ']'
+++ detect_package
+++ case `detect_universe` in
++++ detect_universe
++++ test -f /home/uranium/.local/share/Steam/Steam.cfg
++++ test -f /home/uranium/.local/share/Steam/steam.cfg
++++ STEAMUNIVERSE=Public
++++ echo Public
+++ STEAMPACKAGE=steam
+++ echo steam
++ STEAMDATALINK=/home/uranium/.steam/steam
++ echo /home/uranium/.steam/steam
+ STEAMDATALINK=/home/uranium/.steam/steam
+ STEAMSTARTING=/home/uranium/.steam/starting
+ : ''
+ steamos_arg
+ return 1
+ '[' '!' -f /home/uranium/.steam/steam.pid ']'
++ cat /home/uranium/.steam/steam.pid
+ kill -0 5262
+ INITIAL_LAUNCH=true
+ '[' '' = --reset ']'
+ '[' true ']'
+ show_license_agreement
+ LICENSE=/home/uranium/.local/share/Steam/steam_install_agreement.txt
+ '[' '!' -f /home/uranium/.steam/steam_install_agreement.txt ']'
+ '[' -z /usr/bin/steam ']'
+ '[' -z '' ']'
++ dirname /usr/bin/steam
++ detect_package
++ case `detect_universe` in
+++ detect_universe
+++ test -f /home/uranium/.local/share/Steam/Steam.cfg
+++ test -f /home/uranium/.local/share/Steam/steam.cfg
+++ STEAMUNIVERSE=Public
+++ echo Public
++ STEAMPACKAGE=steam
++ echo steam
+ STEAMDEPS=/usr/bin/steamdeps
+ '[' -f /usr/bin/steamdeps -a -f /home/uranium/.local/share/Steam/steamdeps.txt ']'
+ '[' '!' -e /home/uranium/.steam ']'
+ '[' /home/uranium/.local/share/Steam '!=' /home/uranium/.steam/root -a /home/uranium/.local/share/Steam '!=' /home/uranium/.steam/steam ']'
+ rm -f /home/uranium/.steam/bin32
+ ln -s /home/uranium/.local/share/Steam/ubuntu12_32 /home/uranium/.steam/bin32
+ rm -f /home/uranium/.steam/bin64
+ ln -s /home/uranium/.local/share/Steam/ubuntu12_64 /home/uranium/.steam/bin64
+ rm -f /home/uranium/.steam/sdk32
+ ln -s /home/uranium/.local/share/Steam/linux32 /home/uranium/.steam/sdk32
+ rm -f /home/uranium/.steam/sdk64
+ ln -s /home/uranium/.local/share/Steam/linux64 /home/uranium/.steam/sdk64
+ rm -f /home/uranium/.steam/root
+ ln -s /home/uranium/.local/share/Steam /home/uranium/.steam/root
+ '[' /home/uranium/.steam/steam ']'
+ rm -f /home/uranium/.steam/steam
+ ln -s /home/uranium/.local/share/Steam /home/uranium/.steam/steam
+ rm -f /home/uranium/.steampath
+ ln -s /home/uranium/.steam/bin32/steam /home/uranium/.steampath
+ rm -f /home/uranium/.steampid
+ ln -s /home/uranium/.steam/steam.pid /home/uranium/.steampid
+ rm -f /home/uranium/.steam/bin
+ ln -s /home/uranium/.steam/bin32 /home/uranium/.steam/bin
++ distro_description
+++ detect_distro
+++ '[' -f /etc/lsb-release ']'
+++ '[' -f /etc/os-release ']'
+++ . /etc/os-release
++++ NAME=Fedora
++++ VERSION='26 (Twenty Six)'
++++ ID=fedora
++++ VERSION_ID=26
++++ PRETTY_NAME='Fedora 26 (Twenty Six)'
++++ ANSI_COLOR='0;34'
++++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
++++ HOME_URL=https://fedoraproject.org/
++++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++++ REDHAT_BUGZILLA_PRODUCT=Fedora
++++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
++++ REDHAT_SUPPORT_PRODUCT=Fedora
++++ REDHAT_SUPPORT_PRODUCT_VERSION=26
++++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
+++ echo fedora
+++ tr '[A-Z]' '[a-z]'
+++ detect_release
+++ '[' -f /etc/lsb-release ']'
+++ '[' -f /etc/os-release ']'
+++ . /etc/os-release
++++ NAME=Fedora
++++ VERSION='26 (Twenty Six)'
++++ ID=fedora
++++ VERSION_ID=26
++++ PRETTY_NAME='Fedora 26 (Twenty Six)'
++++ ANSI_COLOR='0;34'
++++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
++++ HOME_URL=https://fedoraproject.org/
++++ BUG_REPORT_URL=https://bugzilla.redhat.com/
++++ REDHAT_BUGZILLA_PRODUCT=Fedora
++++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
++++ REDHAT_SUPPORT_PRODUCT=Fedora
++++ REDHAT_SUPPORT_PRODUCT_VERSION=26
++++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
+++ echo 26
+++ detect_arch
+++ case $(uname -m) in
++++ uname -m
+++ echo 64-bit
++ echo 'fedora 26 64-bit'
+ echo 'Running Steam on fedora 26 64-bit'
Running Steam on fedora 26 64-bit
+ : ''
+ '[' '' = debug ']'
+ '[' '' = 1 ']'
+ '[' '' = 0 ']'
+ '[' -z '' ']'
+ runtime_supported
+ case "$(detect_distro)-$(detect_release)" in
++ detect_distro
++ '[' -f /etc/lsb-release ']'
++ '[' -f /etc/os-release ']'
++ . /etc/os-release
+++ NAME=Fedora
+++ VERSION='26 (Twenty Six)'
+++ ID=fedora
+++ VERSION_ID=26
+++ PRETTY_NAME='Fedora 26 (Twenty Six)'
+++ ANSI_COLOR='0;34'
+++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
+++ HOME_URL=https://fedoraproject.org/
+++ BUG_REPORT_URL=https://bugzilla.redhat.com/
+++ REDHAT_BUGZILLA_PRODUCT=Fedora
+++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
+++ REDHAT_SUPPORT_PRODUCT=Fedora
+++ REDHAT_SUPPORT_PRODUCT_VERSION=26
+++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
++ echo fedora
++ tr '[A-Z]' '[a-z]'
++ detect_release
++ '[' -f /etc/lsb-release ']'
++ '[' -f /etc/os-release ']'
++ . /etc/os-release
+++ NAME=Fedora
+++ VERSION='26 (Twenty Six)'
+++ ID=fedora
+++ VERSION_ID=26
+++ PRETTY_NAME='Fedora 26 (Twenty Six)'
+++ ANSI_COLOR='0;34'
+++ CPE_NAME=cpe:/o:fedoraproject:fedora:26
+++ HOME_URL=https://fedoraproject.org/
+++ BUG_REPORT_URL=https://bugzilla.redhat.com/
+++ REDHAT_BUGZILLA_PRODUCT=Fedora
+++ REDHAT_BUGZILLA_PRODUCT_VERSION=26
+++ REDHAT_SUPPORT_PRODUCT=Fedora
+++ REDHAT_SUPPORT_PRODUCT_VERSION=26
+++ PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
++ echo 26
+ return 0
+ echo 'STEAM_RUNTIME is enabled automatically'
STEAM_RUNTIME is enabled automatically
+ export STEAM_RUNTIME=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime
+ STEAM_RUNTIME=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime
+ '[' /home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime -a /home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime '!=' 0 ']'
+ unpack_runtime
+ has_runtime_archive
+ '[' '!' -f /home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz.part0 ']'
+ return 1
+ '[' -d /home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime ']'
+ return 0
+ case $(uname -m) in
++ uname -m
+ export PATH=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/uranium/Qt/5.7/gcc_64/bin:/home/uranium/.local/bin:/home/uranium/bin:/home/uranium/Qt/5.7/gcc_64/bin
+ PATH=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/uranium/Qt/5.7/gcc_64/bin:/home/uranium/.local/bin:/home/uranium/bin:/home/uranium/Qt/5.7/gcc_64/bin
+ export LD_LIBRARY_PATH=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ LD_LIBRARY_PATH=/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ export LD_LIBRARY_PATH=/home/uranium/.local/share/Steam/ubuntu12_32:/home/uranium/.local/share/Steam/ubuntu12_32/panorama:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ LD_LIBRARY_PATH=/home/uranium/.local/share/Steam/ubuntu12_32:/home/uranium/.local/share/Steam/ubuntu12_32/panorama:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/uranium/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ '[' -z '' ']'
+ check_shared_libraries
+ '[' -f /home/uranium/.local/share/Steam/ubuntu12_32/steamui.so ']'
++ get_missing_libraries /home/uranium/.local/share/Steam/ubuntu12_32/steam
++ LD_PRELOAD=
++ ldd /home/uranium/.local/share/Steam/ubuntu12_32/steam
++ LD_PRELOAD=
++ grep '=>'
++ grep -v linux-gate
++ ldd /home/uranium/.local/share/Steam/ubuntu12_32/steam
++ awk '{print $1}'
++ grep -v /
++ true
+ MISSING_LIBRARIES=
+ '[' '' '!=' '' ']'
+ export SDL_VIDEO_X11_DGAMOUSE=0
+ SDL_VIDEO_X11_DGAMOUSE=0
+ '[' Linux = Linux ']'
+ :
+ MAGIC_RESTART_EXITCODE=42
+ SEGV_EXITCODE=139
+ STEAM_DEBUGGER=
+ unset DEBUGGER
+ '[' '' == gdb ']'
+ '[' '' == cgdb ']'
+ '[' '' == valgrind ']'
+ '[' '' == callgrind ']'
+ '[' '' == strace ']'
+ /home/uranium/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(0)

**Comment by MasterLampe** [comment]
I have the same Problem! I mentioned it at #3954 see last post

**Comment by MasterLampe** [comment]
Hey guys, I found a way to get some more info on my problem. When I run the following command:
`LD_DEBUG=libs $HOME/.steam/steam/ubuntu12_32/steam LD_DEBUG=libs $HOME/Steam/ubuntu12_32/steam `

I get the result:


      1988:     find library=libX11.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libX11.so.6
      1988:
      1988:     find library=librt.so.1 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/librt.so.1
      1988:
      1988:     find library=libm.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libm.so.6
      1988:
      1988:     find library=libdl.so.2 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libdl.so.2
      1988:
      1988:     find library=libstdc++.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libstdc++.so.6                                                                                                        
      1988:                                                                                                                                                    
      1988:     find library=libpthread.so.0 [0]; searching                                                                                                    
      1988:      search cache=/etc/ld.so.cache                                                                                                                 
      1988:       trying file=/usr/lib32/libpthread.so.0                                                                                                       
      1988:                                                                                                                                                    
      1988:     find library=libc.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libc.so.6
      1988:
      1988:     find library=libxcb.so.1 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libxcb.so.1
      1988:
      1988:     find library=libgcc_s.so.1 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libgcc_s.so.1
      1988:
      1988:     find library=libXau.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libXau.so.6
      1988:
      1988:     find library=libXdmcp.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libXdmcp.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libpthread.so.0
      1988:
      1988:
      1988:     calling init: /usr/lib32/libc.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libXdmcp.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libXau.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libgcc_s.so.1
      1988:
      1988:
      1988:     calling init: /usr/lib32/libxcb.so.1
      1988:
      1988:
      1988:     calling init: /usr/lib32/libm.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libstdc++.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libdl.so.2
      1988:
      1988:
      1988:     calling init: /usr/lib32/librt.so.1
      1988:
      1988:
      1988:     calling init: /usr/lib32/libX11.so.6
      1988:
      1988:
      1988:     initialize program: /home/lamprecht/.steam/steam/ubuntu12_32/steam
      1988:
      1988:
      1988:     transferring control: /home/lamprecht/.steam/steam/ubuntu12_32/steam
      1988:
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2017-07-28 20:06:42] Startup - updater built Nov 23 2016 01:05:42
      1988:
      1988:     calling init: /home/lamprecht/.steam/steam/ubuntu12_32/crashhandler.so
      1988:
Installing breakpad exception handler for appid(steam)/version(0)
      1988:     find library=libGL.so.1 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libGL.so.1
      1988:
      1988:     find library=libGLX.so.0 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libGLX.so.0
      1988:
      1988:     find library=libXext.so.6 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libXext.so.6
      1988:
      1988:     find library=libGLdispatch.so.0 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libGLdispatch.so.0
      1988:
      1988:
      1988:     calling init: /usr/lib32/libGLdispatch.so.0
      1988:
      1988:
      1988:     calling init: /usr/lib32/libXext.so.6
      1988:
      1988:
      1988:     calling init: /usr/lib32/libGLX.so.0
      1988:
      1988:
      1988:     calling init: /usr/lib32/libGL.so.1
      1988:
      1988:     find library=libGLX_nvidia.so.0 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libGLX_nvidia.so.0
      1988:
      1988:     find library=libnvidia-tls.so.384.59 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/tls/libnvidia-tls.so.384.59
      1988:
      1988:     find library=libnvidia-glcore.so.384.59 [0]; searching
      1988:      search cache=/etc/ld.so.cache
      1988:       trying file=/usr/lib32/libnvidia-glcore.so.384.59
      1988:
      1988:
      1988:     calling init: /usr/lib32/libnvidia-glcore.so.384.59
      1988:
      1988:
      1988:     calling init: /usr/lib32/libGLX_nvidia.so.0
      1988:
      1988:     /usr/lib32/libpthread.so.0: error: symbol lookup error: undefined symbol: pthread_setname_np, version GLIBC_2.0 (fatal)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

Any ideas?

**Comment by ad1rie1** [comment]
Oh thanck you for the command, i will try for me rapidely but i'm on holliday :)

**Comment by kisak-valve** [comment]
Hello @ad1rie1, are you still experiencing this issue on an up to date system?

**Comment by ad1rie1** [comment]
hello, no, i dont use optimus anymore because nvidia do same with their own driver now, i close the ticket, 

Thanck you
