### ISSUE TITLE
Ingame screenshots doesn't work anymore

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#5092]
#### Your system information

* Steam client version (build number or date): 17/7/17
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The screenshot tool doesn't work anymore after a recent steam update, it only takes one or two screenshots after it stops working per game launched.

#### Steps for reproducing this issue:

1. Launch a game.
2. Click on F12.
3. Few or none screenshots are taken

**Comment by kisak-valve** [comment]
Hello @ekaris, this issue is already being tracked at #4928. Closing as a duplicate.
