### ISSUE TITLE
Error message at open steam on linux

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5093]
Issue transferred from https://github.com/ValveSoftware/csgo-osx-linux/issues/1482.
@cunhazera posted on 2017-07-22T01:23:59:

When I try to run steam at my arch linux appears the following message: OpenGL GLX extension not supported by display.

How can I fix it?

**Comment by kisak-valve** [comment]
Hello @cunhazera, this message can be interprited either that you do not have a working 32 bit opengl driver setup, or that you are using wayland without xwayland. Can you describe your system including how you installed steam and what video driver / vendor you are using?

**Comment by cunhazera** [comment]
lscpi -v prints it in the end: NVIDIA Corporation GK208M [GeForce GT 740M]
And uname -a shows this: Linux hostname 4.9.37-1-MANJARO #1 SMP PREEMPT Thu Jul 13 06:40:16 UTC 2017 x86_64 GNU/Linux

**Comment by cunhazera** [comment]
@kisak-valve does it is enough info for you?
Let me know if it ins't

**Comment by cunhazera** [comment]
About my video driver, maybe it's better:
```
lspci | grep VGA ; lsmod | grep "kms\|drm" ; find /dev -group video ; \
cat /proc/cmdline ; find /etc/modprobe.d/; cat /etc/modprobe.d/*kms* ; \
ls /etc/X11/xorg.conf ; glxinfo | grep -i "vendor\|rendering" ; \
grep LoadModule /var/log/Xorg.0.log
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
drm_kms_helper        126976  1 i915
drm                   294912  7 i915,drm_kms_helper
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
/dev/video0
/dev/fb0
/dev/dri/card0
/dev/dri/renderD128
/dev/dri/controlD64
BOOT_IMAGE=/boot/vmlinuz-4.9-x86_64 root=UUID=4e2004c2-580d-4de7-a394-d5167f470176 rw quiet resume=UUID=2ce83fbe-36bd-461e-9b8b-acb7c2a910d2
/etc/modprobe.d/
/etc/modprobe.d/r8169_blacklist.conf
/etc/modprobe.d/mhwd-nvidia.conf
/etc/modprobe.d/bumblebee.conf
/etc/modprobe.d/mhwd-bbswitch.conf
zsh: no matches found: /etc/modprobe.d/*kms*
/etc/X11/xorg.conf
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center
[     3.239] (II) LoadModule: "glx"
[     3.270] (II) LoadModule: "intel"
[     3.275] (II) LoadModule: "nvidia"
[     3.330] (II) LoadModule: "dri3"
[     3.330] (II) LoadModule: "dri2"
[     3.330] (II) LoadModule: "present"
[     3.429] (II) LoadModule: "libinput"
[     3.885] (II) LoadModule: "synaptics"
[     3.934] (II) LoadModule: "synaptics"
```

**Comment by kisak-valve** [comment]
Just a guess, but can you try `LIBGL_DRI3_DISABLE=1 steam` in a terminal? If that helps, the workaround should only need to be done once.

**Comment by cunhazera** [comment]
@kisak-valve my steam is already working... sometimes it works, sometimes it doesn't.
Next time I can try it.

**Comment by cunhazera** [comment]
@kisak-valve just to know: must I export it as an env variable?

**Comment by kisak-valve** [comment]
`LIBGL_DRI3_DISABLE=1` is an environment variable, however, it's unlikely to be related to your issue. This sounds more like you're doing a system update that requires restarting X, re-modprobing a kernel module, or rebooting the system. In any case, Steam requires a sane, working 32 bit opengl driver to start, and as you said you're not currently experiencing this issue it's unreasonable to investigate further.

If rebooting your system does not help next time you experience this issue, let me know and I can re-open this issue.

**Comment by cunhazera** [comment]
@kisak-valve rebooting my computer is not working to start my steam... is there anything I can do?

**Comment by kisak-valve** [comment]
Hello @cunhazera, are you still experiencing this issue on an up to date system?

**Comment by cunhazera** [comment]
@kisak-valve no :)

**Comment by kisak-valve** [comment]
Thanks, closing.
