### ISSUE TITLE
Steam doesn't start: pipes.cpp (571) : Assertion Failed: m_pInternalPipe->BRead failed

### ISSUE THREAD

**Issue by JaimeLazo** [ValveSoftware/steam-for-linux#5096]
Hello, I have this problem with steam. Firstly, thantks for reading and trying to help.

#### Your system information

* Steam client version (build number or date): 1500335472
* Distribution (e.g. Ubuntu): ubuntu 16.04 64-bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes. All updated.

#### Please describe your issue in as much detail as possible:
Steam seems to start, but crashes immediately. Trying to start it through the console gives the next outcome:

```
jaime@jaime-PC:~$ steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
[2017-07-23 10:31:58] Startup - updater built Jul 17 2017 23:10:02
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-07-23 10:31:58] Checking for update on startup
[2017-07-23 10:31:58] Checking for available updates...
[2017-07-23 10:31:59] Download skipped: /client/steam_client_ubuntu12 version 1500335472, installed version 1500335472
[2017-07-23 10:31:59] Nothing to do
[2017-07-23 10:31:59] Verifying installation...
[2017-07-23 10:31:59] Performing checksum verification of executable files
[2017-07-23 10:32:00] Verification complete
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
Refresh rate: 15
jaime@jaime-PC:~$ ../common/pipes.cpp (571) : Assertion Failed: m_pInternalPipe->BRead failed
Refresh rate: 15

```
#### Steps for reproducing this issue:

1. Open a terminal and enter 'steam' (with or without setting the STEAM_RUNTIME flag)

#### Aditional notes:
I've been yesterday trying to solve this problem with the information I found on the internet (in gibthub and steamcommunty). 
I tried diferent `STEAM_RUNTIME` flag.
I tried to login with and without steam mobile verification.
And also I made a clean reinstallation of steam (I purged it and deleted all the files, then I installed it via `apt-get install steam`).
Also I tried to reset steam via: `steam --reset`. It gives: 
`Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.`

**Comment by Zamundaaa** [comment]
I got exactly the same error. Suddenly, without any problem before. Tried everything you tried, too. No results

**Comment by kisak-valve** [comment]
Hello @JaimeLazo, are you also using a bleeding edge build of mesa? If you are, can you try the latest point release like from xorg-edgers or pkppa? There is a [upstream issue](https://bugs.freedesktop.org/show_bug.cgi?id=101876) currently in mesa git master which is also being tracked at #5095.

**Comment by JaimeLazo** [comment]
Dear kisak-valve. Thanks for fixing my problem.

I changed to an stable version of mesa and steam works perfectly.

Thanks again.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing in favor of #5095.

**Comment by fennectech** [comment]
Im having this issue on manjaro.  I am using latest stable mesa

**Comment by mshade** [comment]
I get this error on Arch linux when asked to run the steam hardware survey.
