### ISSUE TITLE
Steam client crashes on startup

### ISSUE THREAD

**Issue by cat-cat-cat-cat** [ValveSoftware/steam-for-linux#5097]
#### Your system information

* Steam client version (build number or date): Latest? I don't know how to check it because I can't launch it.
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam just crashes when I try to start it. I see "updating" window for a second and then steam process terminates.

[Crash log](https://gist.github.com/cat-cat-cat-cat/51c17d6ce3c950ee748c0eb22f7f612e)

#### Steps for reproducing this issue:

1. Start steam

**Comment by kisak-valve** [comment]
Hello @cat-cat-cat-cat, as far as I can tell, CEF (the web component of steam) is trying to talk to the gpu and is failing.

What video driver vendor / version are you using? Is this a new install or a recent regression?

**Comment by cat-cat-cat-cat** [comment]
I'm using NVIDIA drivers, 375.26. This install is very old already. I've tried to rename Steam folder to reinstall steam but it didn't help, it still crashes (and creates a new folder)

**Comment by cat-cat-cat-cat** [comment]
The issue is solved by updating nvidia driver to 384.59.
