### ISSUE TITLE
Steam stuck on extracting package

### ISSUE THREAD

**Issue by BoberMod** [ValveSoftware/steam-for-linux#5098]
System information
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Linux home 4.11.9-1-ARCH #1 SMP PREEMPT
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

[Github Gist start log](https://gist.github.com/BoberMod/f00a2473d97900010b3316f77741c560)
When i start steam he stuck on `extracting package`

**Comment by kisak-valve** [comment]
Hello @BoberMod, this sounds similar to #4378. Does adding Arch's equivalent of `libnss-resolve:i386 libcurl3:i386` or adding the `steam-native-runtime` package help?

**Comment by BoberMod** [comment]
@kisak-valve 
> or adding the steam-native-runtime package help?
I have installed  `steam-native-runtime package` but nothing has changed
https://gist.github.com/BoberMod/2fef06d15173856d826c438f4c6ab267

**Comment by ryad-eldajani** [comment]
Can confirm crashing steam on launch on Arch x64.
Neither installing `steam-native-runtime` nor setting `STEAM_RUNTIME` or `LIBGL_DRI3_DISABLE` to 1 or 0 does help.

Stdout/Stderr from steam: https://gist.github.com/ryad-eldajani/a97bbee26892360c2cb4cc9d67dae29d

**Comment by Jaegrqualm** [comment]
Echoing @ryad-eldajani , I had to `steam --reset` to get things working again. I can't say if it's actually fixed, however, as this is the output of this line off of the archwiki steam troubleshooting page:

>$ cd ~/.local/share/Steam/ubuntu12_32
>$ file * | grep ELF | cut -d: -f1 | LD_LIBRARY_PATH=. xargs ldd | grep \'not found\' | sort | uniq
libdbus-glib-1.so.2 => not found
	libnm-glib.so.4 => not found
	libnm-util.so.2 => not found
	libudev.so.0 => not found

I'm not sure that I have the right issue here, but the fix worked so I'll leave it here for now.

**Comment by kisak-valve** [comment]
Hello @BoberMod, @ryad-eldajani, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
