### ISSUE TITLE
Steam beta client crashing when auto logging in with saved password

### ISSUE THREAD

**Issue by af7567** [ValveSoftware/steam-for-linux#5099]
#### Your system information

* Steam client version (build number or date): Jul 25 2017, at 23:33:06
* Distribution (e.g. Ubuntu): Slackware64-current
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is crashing today when trying to login automatically, which is how I normally have it logging in.  I have found that if I remove config.vdf then I need to enter my password and steam guard again and steam client starts up OK.  If I tell it to remember the password again then the next time I start steam client it crashes again.

#### Steps for reproducing this issue:

1.  Login and tick the box to remember the password
2.  Quit steam after logging in
3.  Start steam again

attached minidump and stdout
[steamautologcrash.zip](https://github.com/ValveSoftware/steam-for-linux/files/1177603/steamautologcrash.zip)

edit:
I did also have some system updates today, in case that could have triggered the problem the updated packages are libidn2-2.0.3, libinput-compat32-1.8.1, gdk-pixbuf2-2.36.7, gdk-pixbuf2-compat32-2.36.7, nvidia-kernel-384.59, nvidia-driver-384.59.

**Comment by danilw** [comment]
I can not login after "today" steam-linux-clietn update
even after cleaning ~/.steam/steam steam crash after "phone code confirmation"

**Comment by Vash63** [comment]
I can duplicate this on Arch Linux. Originally didn't think I could launch it at all but removing config.vdf did allow me to log in.

**Comment by Seil0** [comment]
I had the same issue, starting steam with STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 works for me.

**Comment by af7567** [comment]
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 fixes it for me too.

**Comment by kisak-valve** [comment]
Hello @af7567, can you pin the steam runtime variant of libdbus with `ln -s ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3` and see if that works as a workaround.

**Comment by ParkerMc** [comment]
I think I have the same issue in #5102 that fix @kisak-valve has works for me.

**Comment by af7567** [comment]
@kisak-valve Creating that symlink fixes steam startup for me when the password is saved.

I did also try downgrading my nvidia driver to 381.22 again earlier but still got the crash, so this is unrelated to the new nvidia drivers it was just a coincidence.

**Comment by Vash63** [comment]
I'm not sure if this should be a separate bug or not but I'm also getting other random crashing if I don't set STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 - just tried to launch Pyre and the Steam client crashed before it even got to the game launch. Setting the above variable fixed it, and as I mentioned before I'm also impacted by the 'save password' crash so I suspect it's the same bug and not something different.

**Comment by reist** [comment]
@kisak-valve Hit the same issue. Symlink fixes things for me as well on slackware-current (32bit) with latest updates and beta opt-in.

**Comment by mastercoms** [comment]
Pinning libdbus works for me as well.

**Comment by reist** [comment]
I guess there's quite a large gap between libdbus 1.4.18 (libdbus-1.so.3.5.8) and Slackware's 1.10.22 (3.14.13).

**Comment by Bovive** [comment]
I do not have a pinned_libs_32 directory so unfortunately that solution would not work for me. Experiencing the same issue however.

**Comment by af7567** [comment]
Is anyone else who is using the dbus symlink work around getting really long game loading times now?  I notice it most with csgo where it shows a black screen 2 mins before showing the valve logo.  Then when I get to the main menu it takes another 10 secs before showing my rank and the hydra menu.  It was a lot faster last week, so I wondered if it is something to do with all the dbus warning messages shown in the terminal.

**Comment by Vash63** [comment]
I can't duplicate that at all, I have the dbus errors after pinning the symlink but CSGO still starts up fast for me. 

I am getting errors when loading anything in the CEF though, CSGO's blog page is missing and Steam's store and community pages are just showing a 'Bad Request' http error.

**Comment by higuita** [comment]
notice that i also had this problem on slackware, but using mesa drivers (-git versions). the workaround solved the problem

**Comment by af7567** [comment]
This has not happened for a long time so it seems to be fixed now.

**Comment by munirehmad** [comment]
Just happened to me, restarting system usually fixes this.

```
munir@abc:~/go/src/gksgsrvr$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Gtk-Message: 15:52:37.985: Failed to load module "gail"
Gtk-Message: 15:52:37.985: Failed to load module "atk-bridge"
dbus[11148]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
crash_20180417155235_1.dmp[11156]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180417155235_1.dmp
/home/munir/.local/share/Steam/steam.sh: line 927: 11148 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180417155235_1.dmp[11156]: Finished uploading minidump (out-of-process): success = yes
crash_20180417155235_1.dmp[11156]: response: CrashID=bp-4cb1117f-5513-490a-88a3-97c142180417
crash_20180417155235_1.dmp[11156]: file ''/tmp/dumps/crash_20180417155235_1.dmp'', upload yes: ''CrashID=bp-4cb1117f-5513-490a-88a3-97c142180417''

```

**Comment by phoenixhaxor** [comment]
having the exact same problem as @munirehmad after updating my ubuntu 17.10 to 18.04

**Comment by munirehmad** [comment]
@af7567 should re-open this

**Comment by phoenixhaxor** [comment]
@munirehmad i'm able to open the steam using the following command "STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam"

from [here](https://github.com/ValveSoftware/steam-for-linux/issues/5101#issuecomment-326657075)

**Comment by dmitry64** [comment]
Same issue. I've installed steam on ubuntu 18.04 and it worked fine for the first time. After that i've installed some packages, tested some steam games under wine (perhaps that's unrelated) and now my native steam fails to launch. Setting that enviroment variable fixes this issue. Tested this on current release and beta release.

**Comment by jlanzobr** [comment]
This bug has reappeared as of June 13 2021 on Arch Linux with NetworkManager and Docker running - unable to determine if that's relevant but it's my only other system change.

**Comment by kisak-valve** [comment]
Hello @jlanzobr, you're looking for #7813 instead of this issue report.
