### ISSUE TITLE
Merged bug report: strings that doesn't make sense anymore

### ISSUE THREAD

**Issue by swiftgeek** [ValveSoftware/steam-for-linux#51]
Please post in comments all strings that doesn't make sense anymore

my batch:
settings → interface | Run Steam when my computer starts # This should be more like "... when I log in" or "... when my desktop environment starts"

Steam → Check for Video Driver Updates... # This shouldn't appear on unsupported distributions

**Comment by kisak-valve** [comment]
The first string is consistent with Steam on other OSes and is not a linux-specific issue. Checking for video driver updates has been removed from the linux client.

If you want to pursue this further, please contact steam support.
