### ISSUE TITLE
Arguments to dbus_message_new_method_call() were incorrect

### ISSUE THREAD

**Issue by lpellegr** [ValveSoftware/steam-for-linux#5103]
#### Your system information

* Steam client version (build number or date): 2017-07-28
* Distribution (e.g. Ubuntu): Fedora 26
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The Steam client crashes on startup.

Below is the full output:

https://gist.github.com/lpellegr/3308c77ce08f5177d310391dfbc89900

I think the interesting part if the following:

> dbus[19583]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../dbus/dbus-message.c line 1367.
> This is normally a bug in some application using the D-Bus library.

#### Steps for reproducing this issue:

1. Install Fedora 26 with latest updates
2. Install the Steam client.
3. Start the Steam client.

**Comment by lpellegr** [comment]
A workaround is to opt-out the beta and to restart the client:

> mv ${HOME}/.local/share/Steam/package/beta ${HOME}/.local/share/Steam/package/beta.disabled

**Comment by kisak-valve** [comment]
Hello @lpellegr, this issue is already being tracked at #5101, feel free to add your findings to the existing issue report.

Closing as a duplicate.
