### ISSUE TITLE
aimtux detected

### ISSUE THREAD

**Issue by awesomememe** [ValveSoftware/steam-for-linux#5109]
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): SteamOS because novac on linux
* Opted into Steam client beta?: [Yes/No] no beta is for fags
* Have you checked for system updates?: [Yes/No] no how to do it

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
1 vac ban on record

#### Steps for reproducing this issue:

1. install csgo, go to GE, get $$ and skins
2. install aimtux
3. 1 VAC-Ban on record https://steamcommunity.com/profiles/76561198173426483/

**Comment by awesomememe** [comment]
pls kisak help me

**Comment by coldpatcher** [comment]
what is aimtux? is cheat for CSGO on linux?

**Comment by awesomememe** [comment]
best cheat, # NOVACONLINUX

**Comment by kisak-valve** [comment]
Hello @awesomememe, account issues including VAC are not handled on this issue tracker.
