### ISSUE TITLE
Thread synchronization object is unuseable for Linux Mint 18.2

### ISSUE THREAD

**Issue by airatin** [ValveSoftware/steam-for-linux#5111]
#### Your system information

* Steam client version (build number or date): 1500335472 Jul 17 2017 23:10:02
* Distribution (e.g. Ubuntu): Linux Mint 18.2 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expected Steam to launch. It did not launch, even with adding `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`. Using the suggested `ln -s ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3` did not work as I don't have a Steam folder under ./local/share (installed it via Software Manager; even when I removed the Software Manager version and installed it from the Steam website directly, the pinned_libs_32 folder didn't exist and when I created it manually it still didn't solve the issue).

[Terminal output here.](https://gist.github.com/airatin/af7ea9adff8d38bece4488153d64e694)

#### Steps for reproducing this issue:

1. Type `steam` into terminal.

**Comment by kisak-valve** [comment]
Hello @airatin, can you confirm you have a working 32 bit opengl driver? The 32 bit variant of glxinfo should be sufficient to use as a test.

**Comment by kisak-valve** [comment]
Closing pending feedback.
