### ISSUE TITLE
Hardware survey crashes Steam

### ISSUE THREAD

**Issue by sumurt** [ValveSoftware/steam-for-linux#5114]
#### Your system information

* Steam client version (build number or date): 17 July 2017
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, last update today, last reboot after the update.

#### Please describe your issue in as much detail as possible:
As I agree to participate in the survey Steam crashes in a couple of seconds.
https://gist.github.com/sumurt/262e4f0a208f44ff415b275642c63845

#### Steps for reproducing this issue:

1. Get offered to participate in the hardware survey.
2. Agree to participate.
3. Steam crashes.

**Comment by OlliC** [comment]
Have the same problem. Probably related to https://github.com/ValveSoftware/steam-for-linux/issues/4856

**Comment by Adonai** [comment]
Same here. Crash occurs not immediately after agreeing to participate but some time after Steam gathers yuor system info. Then in 1-3 seconds it crashes.

**Comment by kisak-valve** [comment]
Hello @sumurt, the Arch variant of this issue is already being tracked at #4964. Closing as a duplicate.

**Comment by image28** [comment]
May not be related, froze on my system until i turning of port 80/8080 being blocked by the firewall
