### ISSUE TITLE
Steam Controller doesn't work in Outlast

### ISSUE THREAD

**Issue by kapsh** [ValveSoftware/steam-for-linux#5115]
#### Your system information

* Steam client version (build number or date): jul 17 2017

* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Steps for reproducing this issue:

1. Launch Steam, turn on controller.
2. Launch Outlast.
3. Controller works only in menus but not in game (it is configured to emulate xbox gamepad). It works in other games and it worked in this too until recently.

[kapsh_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/1202714/kapsh_stdout.txt)

**Comment by kisak-valve** [comment]
Possibly resolved by https://hg.libsdl.org/SDL/rev/2c405337cf3d when it gets into the steam runtime.

**Comment by kisak-valve** [comment]
Hello @kapsh, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by bravemenrun** [comment]
I don't think this is a Steam issue, I bought the game on GOG and I am having the same issue with the game as described with the native Linux version. I think this port is just terrible. Maybe it worked at one point. Who can say?
