### ISSUE TITLE
I can`t use my Chinese input method on Fedora 26

### ISSUE THREAD

**Issue by LinjingFcode** [ValveSoftware/steam-for-linux#5118]
#### Your system information

* Steam client version (build number or date): Jul 17 2017,23:10:56；
* Distribution (e.g. Ubuntu): fedora release 26;
* Opted into Steam client beta?: [Yes/No]No;
* Have you checked for system updates?: [Yes/No]Yes;

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
       To my great delight, steam for linux is running almost perfectly on my operating system. But there is a small issue but is necessary to solve. I can`t use my Chinese input method on it. My input method is named "IBus", when i switch to Chinese input mode it did not work but i can input English letters.    
#### Steps for reproducing this issue:

1.
2. 
3.

**Comment by kisak-valve** [comment]
Hello @LinjingFcode, this issue is already being tracked at #781. Closing as a duplicate.
