### ISSUE TITLE
Steam closed/crashed after canceling screenshots uploading and didn't sent a crash report

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5121]
#### Your system information

* Steam client version (build number or date): 17/7/17
* Distribution (e.g. Ubuntu): Ubuntu Gnome 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam closed/crashed after canceling screenshots uploading and didn't sent a crash report according to the recent report failures.

#### Steps for reproducing this issue:

1. Cancel upload or remove two pictures
2. Steam becomes unresponsive
3. Steam closes

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost and Ubuntu 17.04 has reached its end of life.
