### ISSUE TITLE
libappindicator: secondary activation

### ISSUE THREAD

**Issue by kitsunyan** [ValveSoftware/steam-for-linux#5122]
libappindicator supports secondary activation: `app_indicator_set_secondary_activate_target`.

This action may be bound to expanding/iconifying the application (like left click on the regular systray icon). Is it possible to implement this feature in Steam?

**Comment by kisak-valve** [comment]
Hello @kitsunyan, this feature request is already being tracked at #4836. Closing as a duplicate.
