### ISSUE TITLE
[Minor] "Game Bought: Today" information background box is not sized correctly

### ISSUE THREAD

**Issue by MoritzMiddendorf** [ValveSoftware/steam-for-linux#5124]
(No hardware information needed)
* Steam client version (build number or date): newest public release, build date Jul 17, 2017
* Distribution (e.g. Ubuntu): Windows 10 64 Bit 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Description:
The background box of the "Game Bought: Today" label is wrongly sized. You will know what i mean after you checked the attached image. I only checked it in german language. Making the background box just a few pixels bigger will fix the "problem".
![minor bug](https://user-images.githubusercontent.com/20604843/29191176-2516a6ee-7e1d-11e7-9691-01bf48dafbf1.PNG)

#### Steps for reproducing this issue:
1. Switch language to german
2. Buy a new game
3. Check it out in the game library.

**Comment by kisak-valve** [comment]
Hello @MoritzMiddendorf, in the future, please report Steam for Windows issues to [Steam Support](https://help.steampowered.com/).

Closing because this is no longer relevant due to the Steam Library refresh.
