### ISSUE TITLE
XBONE controller via USB fails to work in in-home streaming mode.

### ISSUE THREAD

**Issue by hamishmaku** [ValveSoftware/steam-for-linux#5125]
#### Your system information

* Steam client version (build number or date):  july 17
* Distribution (e.g. Ubuntu): debian sid
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

official XBONE controller (USB connection) fails to function over in-home streaming service. have made /dev/uinput writable on host machine.

streaming controller usage worked until a couple days ago (5th?) when it suddenly stopped, unsure what in relation to.

also the right analogue stick doesn't work in some games anymore(tested: Psychonauts, Yooka Laylee) although with YL it won't recognise the controller _at all_, but I'm following that up with the development team.

happens in both stable and beta, in either big picture or normal modes.

#### Steps for reproducing this issue:

1. start steam
2. start streaming game
3.  controller fails to work, though detected by host computer.

thanks!

**Comment by hamishmaku** [comment]
recent updates have fixed this problem, unsure how precisely but it is no longer an issue.

**Comment by kisak-valve** [comment]
Thanks for the follow up, closing.
