### ISSUE TITLE
ubuntu lts 16.04 error swrast

### ISSUE THREAD

**Issue by mchoccac** [ValveSoftware/steam-for-linux#5126]
#### Your system information

* Steam client version (build number or date): 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. start steam
2. 
3. 

out:

Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by kisak-valve** [comment]
Hello @mchoccac, please describe how you installed steam.

What video card do you have and can you confirm you have a working 32 bit opengl implementation installed? Swrast is mesa's slower software opengl implementation and steam trying to use it usually indicates that the preferred video driver is not setup properly.

**Comment by MysteryPig** [comment]
I'm having the same issue. I have the same ubuntu version and an Intel HD Graphics 400. I installed steam with a .deb from the steam website. LibGL seems to be working, at least for my xscreensaver.

I am running this on a chromebook, so it might be due to another issue.

**Comment by mchoccac** [comment]
@kisak-valve hi use video driver nvidia

**Comment by kisak-valve** [comment]
Hello @mchoccac, are you still experiencing this issue on an up to date system? This was a nvidia driver install issue.
