### ISSUE TITLE
[installer] LIBGL_DRI3_DISABLE mandatory for installer, but will hang dota2

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5127]
From a fresh custom gnu/linux distro, the installer wants LIBGL_DRI3_DISABLE=1... but if you keep this env variable the steam client will be fine but not dota2 will hang (git mesa/git gcc/git glibc on amd tahiti xt gpu/amdgpu from linux 4.12.4)

**Comment by kisak-valve** [comment]
Hello @sylware, this issue is already being tracked at #4816. Closing as a duplicate.
