### ISSUE TITLE
[client] the client on recent gnu/linux distros seems to trigger easily glibc bug 21041 (aka segfault on longjmp with pthread)

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5132]
When trying to make work the steam installer and client on my fresh distro, I was hit hard by a permanent segfault I could not fix due to a total stack corruption.
Upgrading to a recent glibc (after the 8th of august 2017) and rebuilding did fix it.
It seems that some code paths in the client and third party libs, triggered a nasty glibc bug related to longjmp/setjmp:  https://sourceware.org/bugzilla/show_bug.cgi?id=21041
longjmp/setjump interfaces from libpng/freetype/others are probably the culprit. (it may explain the segfaults on many recent distros... or not).
Did not check, but if the glibc/libgcc_s code paths are still unwinding the stack with the dwarf2 bytecode for a longjmp call... oh my.

**Comment by kisak-valve** [comment]
Hello @sylware, are you still experiencing this issue on an up to date system?

**Comment by sylware** [comment]
I have been running the client with glibc 2.28 (32 bits) and glibc 2.27
(64bits) without excessive recuring crashes since then. I have not tested the
installer in a long time though, because of the bash only scripts and 32bits
libs pain.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Since the upstream bug report was fixed years ago I don't think there's any action to take here.
