### ISSUE TITLE
There was an error communicating with the Steam servers. Please try again later.

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#5133]
#### Your system information

* Steam client version (build number or date): 17/7/17
* Distribution (e.g. Ubuntu): Ubuntu gnome 17.04 amd64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I constantly get "There was an error communicating with the Steam servers. Please try again later."
on the steam client.
This has been happening for some days already.

#### Steps for reproducing this issue:

1.  Just login to steam and go to activity for example

**Comment by kisak-valve** [comment]
Hello @ekaris, can you see if installing libnss-resolve:i386 improves the behavior of steam on your system? (from https://github.com/ValveSoftware/steam-for-linux/issues/4971#issuecomment-303506713)

**Comment by ekaris** [comment]
Hi, the problem just stopped happening all of a sudden

**Comment by kisak-valve** [comment]
Thanks for the followup @ekaris. Closing.
