### ISSUE TITLE
steam crashes

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#5134]
#### Your system information

* Steam client version (build number or date):  last beta builds
* Distribution (e.g. Ubuntu):  debian sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Open steam
2. wait incoming message, try to talk via dialog
3. steam crash without errors or messages in dmesg

if steam crash, after launch steam requests log in or settings go back to default: custom skin and language (from ru to en)

if I play to game and use steam dialog, steam doesn't crash

**Comment by kisak-valve** [comment]
Hello @steamlinux, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please attach them.

**Comment by steamlinux** [comment]
Hello! my system info from steam https://gist.github.com/steamlinux/f830d0e7d88de8aa4ecada76647cc6b7
where I can find dumps? I can't found

**Comment by kisak-valve** [comment]
Minidumps are commonly found in /tmp/dumps/, which you can put in an archive and drag and drop into the comment box. There might also be a hint as to what's going on in ~/.steam/error.log.

**Comment by steamlinux** [comment]
[steamlog.zip](https://github.com/ValveSoftware/steam-for-linux/files/1236705/steamlog.zip)
include dir /tmp/dumps/ and ~/.steam/error.log

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

It's not really clear what's going wrong here so we'll probably need to see if others are having the same issue.

**Comment by steamlinux** [comment]
I need attach my crashhadler.so? I have 3 lib:
~/.steam/linux32/crashhandler.so
~/.steam/ubuntu12_32/crashhandler.so
~/.steam/linux64/crashhandler.so

**Comment by steamlinux** [comment]
after upload archive I have new crash and I have new file
/tmp/dumps/crash_20170820040049_18.dmp
I update all fies and add crashhandler.so (if I correctly understand
[steamlog_updated.zip](https://github.com/ValveSoftware/steam-for-linux/files/1236775/steamlog_updated.zip)
)

**Comment by steamlinux** [comment]
I disable audio notification and steam doesn't crash
maybe steam crash with audio because I change pulseaudio settings? (/etc/pulse/daemon.conf)

**Comment by kisak-valve** [comment]
Hello @steamlinux, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
