### ISSUE TITLE
voice chat no work

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#5135]
#### Your system information

* Steam client version (build number or date): I don't remember, I have this trouble ~ half year
* Distribution (e.g. Ubuntu): Debian sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. open steam
2. go to settings
3. select "voice" tab
4. check microphone. my microphone work
5. open dialog with someone in friend list
6. make voice chat (call)
if I call to friend or friend call me, no difference
7. I hear friend, but friend don't hear me

I try change build to stable, nothing

**Comment by kisak-valve** [comment]
Hello @steamlinux, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
