### ISSUE TITLE
Steam client on random becomes unresponsive, flooding console.

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/steam-for-linux#5136]
#### Your system information

* Steam client version (build number or date): Jul 17 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Randomly Steam client can become really unresponsive, working at around 0,5 FPS, while flooding console with: `Timed out waiting for mutex in PutInternal()`.
Restarting the client helps.

#### Steps for reproducing this issue:
There's no known for me way to reliably reproduce the issue.

**Comment by kisak-valve** [comment]
Hello @kiroma, are you still experiencing this issue on an up to date system?

**Comment by kiroma** [comment]
No, I don't recall experiencing this issue any time recently.

**Comment by kisak-valve** [comment]
Thanks for the follow up. Closing per the last comment.
