### ISSUE TITLE
Button presses in Steam Overlay are also sent to the game

### ISSUE THREAD

**Issue by littlegamer87** [ValveSoftware/steam-for-linux#5137]
#### Your system information

* Steam client version (build number or date): July 17 2017
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
In SteamOS, in game, with an X360 controller, after opening the overlay by pressing the Xbox-button, every button pressed there is also processed by the game

#### Steps for reproducing this issue:

See this video: https://youtu.be/AJ0O14sdNeU?t=3s

**Comment by kisak-valve** [comment]
Thanks for the follow up @littlegamer87, closing.
