### ISSUE TITLE
Can't install/delete DLC with a controller

### ISSUE THREAD

**Issue by littlegamer87** [ValveSoftware/steam-for-linux#5139]
#### Your system information

* Steam client version (build number or date): July 17 2017
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

In the game's page, right before launching it, there's a section with "DLC installed". This menu does not respond to the Xbox 360 button, it only plays an 'error/wrong button' sound. I am unable to get this menu to work with the controller, it only responds to mouse clicks.

#### Steps for reproducing this issue:

See this video: https://youtu.be/AJ0O14sdNeU?t=53s

**Comment by littlegamer87** [comment]
Addition: Also doesn't work with a PS4 controller

**Comment by littlegamer87** [comment]
hello @kisak-valve, can you please advise whether this issue is being tracked internally?

I went through great effort to properly document and record this bug (and #5138 too) and I found a lot more bugs that aren't exactly critical or system breaking, but do impact the overall user experience and quality of life on Steam(OS). It isn't motivating to continue testing if my contributions still haven't been picked up after a year.

**Comment by kisak-valve** [comment]
Hello @littlegamer87, are you still experiencing this issue on an up to date system?

**Comment by littlegamer87** [comment]
Hello @kisak-valve 
I can confirm that the little DLC menu now does respond to button presses. Now it is possible to install/remove DLC with a controller, *but* there is also a "Done" button below that does not respond to anything. You can workaround it by pressing the B button to cancel the DLC menu, but I wouldn't check this off just yet.

I also retested #5138 and this bug still exist

**Comment by kisak-valve** [comment]
Thanks for retesting. Since the original issue is resolved I'm going to close this issue report. Feel free to open a new issue report for the follow up issue you found.
