### ISSUE TITLE
Steam client interrupting shutdown process on linux mint 18

### ISSUE THREAD

**Issue by Makreig** [ValveSoftware/steam-for-linux#5140]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/6011781/29537990-b781feec-86bb-11e7-886b-83b12ff70e68.png)

* Distribution (e.g. Ubuntu):  Linux Mint 18.1 Serena
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've recently noticed an issue with the Linux client of steam on mint 18. When attempting to shut down my system i need to instruct my system twice. It appears that this is occurring due to steam interfering with the shutdown procedure when it closes.

In particular, i have noticed that my system will begin shutting down normally until steam is closed, at which point the shutdown sequence seems to halt. Initiating a shutdown sequence after steam has closed works as expected and the system shuts down without issues.

I have noticed this issue occurring on both my home PC and my work laptop (both run mint 18.1).

Full system information for my home PC can be found here:
https://gist.github.com/anonymous/1503f4709b86a368c0049b3da03a2b35

#### Steps for reproducing this issue:

1. Open steam and additional applications
2. Attempt to shutdown the system
3. Wait ... the shutdown should cease once steam closes

**Comment by kisak-valve** [comment]
Hello @Makreig, this issue is already being tracked at #3301. Closing as a duplicate.
