### ISSUE TITLE
Portal 2: Chelle is completely black unless she's directly lit

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#5141]
#### Your system information

* Steam client version (build number or date): Jul 17 2017
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:

Check out this screenshot:
![20170822193438_1](https://user-images.githubusercontent.com/957339/29586523-39a684a4-878b-11e7-9372-4e77a35ceeb4.jpg)
When she is lit from the direction of the portal, she looks normal, otherwise she is completely black.

At the end of the game her hands are visible in first person. Those are also completely black.

**Comment by kisak-valve** [comment]
Hello @mtmkls, let's track this issue in the Portal 2 issue tracker at https://github.com/ValveSoftware/portal2/issues/289.
