### ISSUE TITLE
gameoverlayui hangs when taking screenshots

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#5142]
#### Your system information

* Steam client version (build number or date): Jul 17 2017
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:

When starting a game steam also launches a corresponding gameoverlayui process. Taking screenshots makes it hang (after 1-5 screenshots), and I can't take a new screenshot until I kill it manually. Starting another game launches a new gameoverlayui, and the in-game overlay works, but taking screenshot doesn't.

**Comment by kisak-valve** [comment]
Hello @mtmkls, this issue is already being tracked at #5120. Closing as a duplicate.

**Comment by mtmkls** [comment]
Mmmmkay, but in my case it doesn't crash the game.
