### ISSUE TITLE
Portal 2 always resets audo to 5.1

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#5143]
#### Your system information

* Steam client version (build number or date): Jul 17 2017
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:

I expected it to remember my audio setup.

#### Steps for reproducing this issue:

1. Have 2 speakers
2. Start the game
3. Don't hear anything that happens behind you

**Comment by kisak-valve** [comment]
Hello @mtmkls, let's track this issue in the Portal 2 issue tracker at https://github.com/ValveSoftware/portal2/issues/288.
