### ISSUE TITLE
Missing `libpulsecommon-1.1.so`

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [ValveSoftware/steam-for-linux#5144]
#### Your system information

* Steam client version (build number or date): Newest (how to check?)
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No..?
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
It says I have a missing lib, when I run `steam` I get
```
gido5731@gido-desk:~$ steam
Running Steam on ubuntu 17.04 64-bit
STEAM_RUNTIME is enabled automatically
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpulsecommon-1.1.so
Installing breakpad exception handler for appid(steam)/version(1500335472)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

and at  it has a popup saying to press enter, then it freezes until ^C.

#### Steps for reproducing this issue:

1. Install steam
2. Run it
3. Profit (..?)

**Comment by kisak-valve** [comment]
Hello @gidoBOSSftw5731, is this a new install? Did you install steam with the distro-provided steam package or the valve-provided steam package?

You might be able to workaround this issue by running `sudo apt install libpulse0:i386` in a terminal.

**Comment by gidoBOSSftw5731** [comment]
Aha! that fixed it it seems! I wish it did that for me on install but ¯\_(ツ)_/¯

**Comment by korenmic** [comment]
I'm having roughly the same issue:
```
$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpulsecommon-11.1.so
Steam client's requirements are satisfied
```

I did `sudo apt purge pulseaudio; sudo apt install pulseaudio` and I verified that this file actually exists: `/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so` yet the issue persists.

Steam is failing to see that this existing file exists. *shrugs*
