### ISSUE TITLE
arguments to dbus_connection_ref() were incorrect

### ISSUE THREAD

**Issue by techtonik** [ValveSoftware/steam-for-linux#5146]
#### Your system information

* Steam client version (build number or date): Aug 24 2017
* Distribution (e.g. Ubuntu): 17.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Running Steam in terminal overruns the buffer with these messages:
```
process 26194: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
This is normally a bug in some application using the D-Bus library.
process 26194: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
process 26194: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
process 26194: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
```
This pattern repeats itself endlessly.

#### Steps for reproducing this issue:

1. Set "Run in terminal" in launcher options
2. Click the launcher

**Comment by kisak-valve** [comment]
It should be noted this is non-fatal.

**Comment by kaadmy** [comment]
I'm getting the same thing, Arch Linux (not latest, a couple weeks out of date probably).

**Comment by snkiz** [comment]
Just did a clean install on ubuntu 17.10 getting the same.

**Comment by AlejandroC90** [comment]
I'm getting this error while trying to open Rocket League, doesn't happen in other games like Dota or The Talos Principle.

**Comment by kaadmy** [comment]
I'm getting it while running any Source game (TF2, CS:GO, Insurgency)

**Comment by kiroma** [comment]
This also appears when a notification pops up. Animation of the notification stutters since last update.

**Comment by kaadmy** [comment]
On some machines I've had problems that printing a large about of text to the console slowed things down; might be the same thing as @kiroma

**Comment by Muslic** [comment]
Same issue with Fedora 26 when starting Rocket League.

D-Bus not built with -rdynamic so unable to print a backtrace
process 5337: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.

**Comment by RafneQ** [comment]
The same issue in openSUSE Leap 42.2 - terminal is flooded with two types of outputs:

- with "_line 2656_":
```
process 4778: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
This is normally a bug in some application using the D-Bus library.
```

- and with "_line 2794_"

```
process 4778: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
```

**Comment by AlejandroC90** [comment]
Anyone knows a way to pass this issue? in my case Rocket League **doesn't open** and it's been week now, I'm starting to get bored. Thanks.

**Comment by kisak-valve** [comment]
Hello @AlejandroC90, Give the workaround at https://github.com/ValveSoftware/steam-for-linux/issues/5101#issuecomment-326645335 a try and see if that makes a difference.

**Comment by AlejandroC90** [comment]
That solved to problem, the game starts normally, thanks!.
The output in the terminal is the same though:

`process 29469: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.`

Thank you.

**Comment by SoaT** [comment]
I installed **_primus-libs-ia32:i386_** and **_primus-libs:i386_** in my Debain Sid and the problem was solved!
https://packages.debian.org/sid/primus-libs-ia32

**Comment by kaadmy** [comment]
Interesting, I'm not using Bumble at all although this is an Optimus system, I just force Nvidia always on though.

**Comment by kiroma** [comment]
Looks like `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1` alleviates the problem.

**Comment by trustin** [comment]
> Looks like STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 alleviates the problem.

Didn't work for me. (Arch Linux)

**Comment by ICHx** [comment]
have you installed steam-native on arch?

**Comment by trustin** [comment]
@ICHx I use `steam-runtime`, not `steam-native`. I guess `steam-native` may resolve this issue but some games didn't work with it.

**Comment by C0d3rM0nk3y-Nathan** [comment]
I find running steam with STEAM_RUNTIME=0 fixes it on Arch

**Comment by abc-mikey** [comment]
I'm experiencing the same issue (Fedora 25) but no combination of launching steam with the environmental variables suggested set makes the warnings go away:

```
STEAM_RUNTIME=0
STEAM_RUNTIME=1
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1
```
Nor does the suggestion I've seen to pin some of the libdbus 32 bit libraries.

`ln -s ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3 `

I'm also experiencing crashes in SOMA whenever picking up any object (99% of the time) which disappear when running the non-Steam binary, which may be related.

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Phenom(tm) II X4 955 Processor
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3600 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.12.9-200.fc25.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11903000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 1030/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.69
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1d01
    Revision Not Detected
    Number of Monitors:  1
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 4x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: %s1

Memory:
    RAM:  3947 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  238357 Mb
    Largest Free Hard Disk Block:  33063 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by ajcollett** [comment]
This is being repeated a good 10+ times a second in my system logs. Any ideas how to stop it?

**Comment by pbhj** [comment]
As for abc-mikey, none of the fixes appear to work for me. With `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1` I do get extra errors:

`(steam:857): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.`

gets logged to the console a couple dozen times before the other errors start.

AFAIR this is new in the last week or so, I don't recall updating anything else in that time so I suspect it's from the steam end of things.

I did try soft linking the runtime libdbus-1.so.3 to my systems one but it didn't help.

**Comment by matthew-cline** [comment]
Under Fedora 25, Steam beta, none of the suggestion help, and `STEAM_RUNTIME=0` makes Steam freeze when attempting to auto-login.

**Comment by unique1984** [comment]
My Linux is - 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
Optimus is enabled and primus-libs packages installed, including i386.
```
STEAM_RUNTIME=0
STEAM_RUNTIME=1
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1

ln -s ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3
```
I tried all of these but no luck. Steam opening but game is not.

**Comment by recolic** [comment]
ArchLinux: Linux RECOLICPC 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
with core/dbus 1.10.24-1 core/glibc 2.26-4 (base)
Screen freezes while loading CS:GO Map...
```
Oct 05 23:03:42 RECOLICPC steam.desktop[1307]: process 1568: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
10月 05 23:03:42 RECOLICPC steam.desktop[1307]: This is normally a bug in some application using the D-Bus library.
10月 05 23:03:42 RECOLICPC steam.desktop[1307]: process 1568: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
10月 05 23:03:42 RECOLICPC steam.desktop[1307]: This is normally a bug in some application using the D-Bus library.
```

I installed nvidia driver(extra/nvidia 387.12-1), and made lots of rolling upgrade after last successful launch.

**Comment by StripedMonkey** [comment]
This is not causing me any issues AFAIK however in the process of debugging a gnome error I looked in my journalctl and saw a MASSIVE amount of spam relating to this however it was specifically for starbound.

```
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: process 1687: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: This is normally a bug in some application using the D-Bus library.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: process 1687: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: This is normally a bug in some application using the D-Bus library.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: process 1687: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: This is normally a bug in some application using the D-Bus library.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: process 1687: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
Oct 10 21:27:40 strangemonkey Starbound.desktop[1527]: This is normally a bug in some application using the D-Bus library.
```
AMD R9 390x, Arch Linux 4.12.13 let me know if you need any other information.
Like I said, this isn't (at least that I can tell) causing any issues for me other than spamming logs that I'm using to debug a different problem.

**Comment by ikeydoherty** [comment]
To alleviate dbus-related segfaults - (not their root causes), you can:

`export DBUS_FATAL_WARNINGS=0`

(Note, this does not correct the NULL path issues with dbus, it just stops the segfault, and is another issue entirely: https://github.com/ValveSoftware/steam-for-linux/issues/5201)

**Comment by Videonauth** [comment]
Have this:
Oct 26 20:54:39 NEXUS-ONE org.gnome.Shell.desktop[1672]: process 14347: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../../dbus/dbus-connection.c line 2688.
Oct 26 20:54:39 NEXUS-ONE org.gnome.Shell.desktop[1672]: This is normally a bug in some application using the D-Bus library.

As well happen in 17.10 release version with vanilla gnome desktop. but instead clogging the terminal it clogs the syslog for about 62 MB per day writing the same entry about 8-12 times per secont to /var/log/syslog. I call this critical because it adds unnecessary write cycles to my SSD. 

Only workaround I found so far is starting steam from terminal with the following command (beware you wont see anything output anymore ;) )

`steam > /dev/null 2>&1`

**Comment by folknor** [comment]
See https://github.com/systemd/systemd/issues/6432 where the systemd devs need convincing that apps that spam 60mb of useless and annoying data actually exists, to consider adding filtering to journald at collection time.

But I'm sure they'll just say "fix steam" or "fix dbus."
Anyway, at least I plugged the issue reference.

**Comment by Videonauth** [comment]
@folknor  im sitting here now since release of Ubuntu 17.10 and try to figure out how to stop logging for certain apps at collection time. this would definitively help it to have that.

**Comment by lulcat** [comment]
folknor.. I am on a non systemd 'arch', and I also get this.. it isn't systemd specific, as I don't have any systemd libs whatsoever.

**Comment by ikeydoherty** [comment]
Depending on how much dbus is annoying you, I have a patch to shut it up for this exact situation..

Patch dbus with [this patch](https://dev.solus-project.com/source/dbus/browse/master/files/0001-dbus-Teach-it-a-new-trick-Shutting-up.patch) and start apps with `DBUS_SILENCE_WARNINGS=1` to hide all the dbus spam.

**Comment by Vash63** [comment]
I'm still reproducing this with the current version and it's pretty bad just how frequent the messages are. Just in the last 15 minutes since booting my system there have been 3775 lines in my journal written by Steam regarding this dbus error. I'd really like a fix that isn't just piping all Steam output to /dev/null or custom patching dbus.

**Comment by illis** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/3831 

Been an issue since 2015 :/

**Comment by WoefulDerelict** [comment]
This issue arises when legacy libraries included in the Steam runtime conflict with newer software installed on the system. The simplest mitigation is to set STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1. This can lead to other warnings if the system doesn't have the appropriate libdbusmenu packages installed as it will attempt to use the runtime library with the system's version of dbus. Setting STEAM_RUNTIME=0 also works; however, it requires the libraries present in the runtime to be installed on the system.

It is also possible to remedy the issue without negatively impacting Steam or games that depend on Steam's runtime by deleting the links to the offending libraries from the pinned_libs_* folders Steam creates at ~/.local/share/Steam/ubuntu12_32/steam-runtime. This forces Steam to use the libraries installed on the system without setting flags. The system must have these libraries installed for Steam to fall back on or you'll encounter more errors.

pinned_libs_32 contains four links to libraries that must be removed to properly mitigate the issue:
libdbus-1.so.3: Direct cause of the reported issue.
libdbusmenu-glib.so.4: Causes the following warning if left after removing libdbus-1.so.3 "LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent."
libdbusmenu-gtk.so.4
libgtk-x11-2.0.so.0: If left after removing libdbus-1.so.3, libdbusmenu-glib.so.4 and libdbusmenu-gtk.so.4 it will prevent Steam's appindicator/status icon from working properly.

pinned_libs_64 contains 2 links which should also be removed.
libdbusmenu-glib.so.4
libdbusmenu-gtk.so.4

This is not a permanent fix as Steam will recreate these links during updates. Valve needs to remove these from the runtime or adopt more modern versions to permanently fix the issue.

**Comment by WoefulDerelict** [comment]
While it is generally not fatal the issue has a noteworthy impact on affected systems. On an Arch Linux test system where the application was installed on February 1, 2018 and allowed to run with the issue unmitigated for about five days it generated hundreds of thousands of lines in the system journal, bloating it to over 1 GiB. Not only does this bury useful information in a sea of frequently repeated output it can result it older logs being purged prematurely once the journal's maximum size is reached. This could easily result in the loss of important log information users may have otherwise wished to preserve and consult when tracking other issues and assessing system health.

**Comment by barf** [comment]
On Ubuntu 18.04 I think I have a related crash, exporting STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 seems to fix it
`$ export STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1
$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Gtk-Message: 21:44:47.552: Failed to load module "appmenu-gtk-module"
Gtk-Message: 21:44:47.552: Failed to load module "gail"
Gtk-Message: 21:44:47.552: Failed to load module "atk-bridge"
dbus[1651]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
crash_20180419214445_1.dmp[1661]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180419214445_1.dmp
/home/barf/.local/share/Steam/steam.sh: line 927:  1651 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180419214445_1.dmp[1661]: Finished uploading minidump (out-of-process): success = yes
crash_20180419214445_1.dmp[1661]: response: CrashID=bp-de86bd65-5724-405d-8781-4f7b32180419
crash_20180419214445_1.dmp[1661]: file ''/tmp/dumps/crash_20180419214445_1.dmp'', upload yes: ''CrashID=bp-de86bd65-5724-405d-8781-4f7b32180419''`

**Comment by Soapux** [comment]
I think this has been fixed in the May 16th update.  I'm not seeing this anymore.  And the client no longer crashes if you use your system libdbus-1.so.3 instead of the steam i386 one.

**Comment by kiroma** [comment]
I can confirm that as well, the issue is now gone.

**Comment by kaadmy** [comment]
Can also confirm, I no longer get this issue.

**Comment by techtonik** [comment]
Aug 08 2018
Ubuntu 18.04
No message anymore.

**Comment by gartuz** [comment]
It works for me to edit the Run.sh script on:

~./local/share/Steam/steamapps/common/WormsWMD/



export DBUS_FATAL_WARNINGS=0
export MESA_LOADER_DRIVER_OVERRIDE=i965
export STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0
export STEAM_RUNTIME=0

This is the file:

`#!/bin/bash

export LC_ALL=C
export DBUS_FATAL_WARNINGS=0
export MESA_LOADER_DRIVER_OVERRIDE=i965
export STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0
export STEAM_RUNTIME=0
export LD_LIBRARY_PATH="/usr/lib:/usr/local/lib"
chmod a+x ./Worms\ W.M.Dx64
./Worms\ W.M.Dx64`
