### ISSUE TITLE
Steam crashes from libdrm and mesa 32-bit / 64 bit version mismatch on Arch

### ISSUE THREAD

**Issue by gregf** [ValveSoftware/steam-for-linux#5148]
#### Your system information

* Steam client version (build number or date):  ?
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam to run

#### Steps for reproducing this issue:

1.  Open steam
2. It crashes

```
$ steam 
Repairing installation, linking /home/gregf/.steam/steam to /home/gregf/.local/share/Steam
/home/gregf/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/gregf/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/gregf/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
*** Error in `/home/gregf/.local/share/Steam/ubuntu12_32/steam': realloc(): invalid next size: 0x56de4260 ***
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2017-08-26 15:10:52] Startup - updater built Nov 23 2016 01:05:42
crash_20170826151052_1.dmp[13556]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170826151052_1.dmp
/home/gregf/.local/share/Steam/steam.sh: line 713: 13553 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
/home/gregf/.local/share/Steam/steam.sh: line 444: no match: ssfn*
crash_20170826151052_1.dmp[13556]: Finished uploading minidump (out-of-process): success = yes
crash_20170826151052_1.dmp[13556]: response: CrashID=bp-1f887ffa-9d4c-409d-8ed0-67e7b2170826
crash_20170826151052_1.dmp[13556]: file ''/tmp/dumps/crash_20170826151052_1.dmp'', upload yes: ''CrashID=bp-1f887ffa-9d4c-409d-8ed0-67e7b2170826''
```

Upload of /tmp/dumps/crash_20170826151052_1.dmp:

https://filebin.pw/ytUZjV/

I tried blowing away my .steam direcotry, it opens up askes me to accept the eula then crashes again.

**Comment by kisak-valve** [comment]
Hello @gregf, did you recently update mesa or libdrm? There's some trouble going on with arch's packaging of mesa per #5145, https://bugs.archlinux.org/task/55297, and https://bugs.archlinux.org/task/55303.

**Comment by jomihaka** [comment]
Downgrading libdrm from 2.4.83-1 back to 2.4.82-1 fixed it for me.

**Comment by random2324** [comment]
Some more information here:
https://bugs.freedesktop.org/show_bug.cgi?id=102432

Its really an arch problem. lib32-libdrm is too old on arch. Once both are up to date, things are working.

**Comment by gregf** [comment]
Yep, this appears to be the case. Thanks for the information everyone.
