### ISSUE TITLE
Please help! CS 1.6 SteamCMD Linux NOT DOWNLOAD

### ISSUE THREAD

**Issue by byraccun** [ValveSoftware/steam-for-linux#5150]
I am trying to install a Linux server but the files are missing, I'm trying ten days, please help. .
Dedicated server files (ID:90) not completely descending.
Screen; http://imgur.com/a/gz9U5
There are a lot of users who have this problem like me (http://steamcommunity.com/discussions/forum/16/1369506834138679429/ --
 http://steamcommunity.com/discussions/forum/16/2741975115069089758/)

**Comment by kisak-valve** [comment]
Hello @byraccun, this issue is already being tracked at #4950. Closing as a duplicate.
