### ISSUE TITLE
Steam not installing (Missing libc.so.6)

### ISSUE THREAD

**Issue by qreilly00** [ValveSoftware/steam-for-linux#5152]
#### Your system information
OS: 64-bit Lubuntu with Windows 10 dualboot
RAM: 16 GB
Available partition space: 12 GB
CPU: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
GPU: GTX 1050ti
* Steam client version (1.0.0.54): 
* Distribution (Steam not working on Lubuntu (Missing libc.so.6)): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
When I try to install steam onto my Lubuntu partition, it says that I am missing libc.so.6 and fails to install.

#### Steps for reproducing this issue:

1. install steam

**Comment by kisak-valve** [comment]
Hello @Quinn-R, what steps did you take to install the steam package? Is it the distro-provided steam package or the valve-provided steam package?

**Comment by Quinn-R** [comment]
Hi. I downloaded it through steam. I then typed steam into the terminal and also tried double clicking it in the file explorer, both of which brought up the software library to install. It also has .deb on the end.

**Comment by kisak-valve** [comment]
Open a terminal and give `sudo apt purge steam && sudo apt install steam` a try.

**Comment by eplgr** [comment]
I have/had the same issue. Today I did a fresh Debian install and went straight into Sid. I had a million dependency problems, but after a lot of hours I managed to narrow it down to a single error:
>The folllowing packages have unmet dependencies:
libgl1-mesa-dri:i386 : Depends: libllvm4.0:386: libllvm4.0:386 (>= 1:4.0~) but it is not going to be installed.

@kisak-valve : Yes, the previous errors always ended up in `libc.so.6` missing. I installed the .deb package from steam's website, which is the only way I could install it (the error appears when I execute steam).
And when I try to install `libllvm4.0:386`, it wants me to downgrade my whole system.

There's a reddit thread that describes the same issue:
https://www.reddit.com/r/debian/comments/6wj1ql/cant_install_steam_in_sid/
2 days old, pretty recent. He just replied going back to `testing` fixed it, so I'm gonna give that a try.

**Comment by Quinn-R** [comment]
`sudo apt purge steam && sudo apt install steam` doesn't seem to work.

**Comment by kisak-valve** [comment]
@Quinn-R, did it give any terminal spew? In what way did it fail?

**Comment by Quinn-R** [comment]
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'steam:i386' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-30 linux-headers-4.10.0-30-generic
  linux-image-4.10.0-30-generic linux-image-extra-4.10.0-30-generic
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 steam:i386 : Depends: libc6:i386 (>= 2.15) but it is not going to be installed
              Depends: libstdc++6:i386 (>= 4.3) but it is not going to be installed
              Depends: libx11-6:i386 but it is not going to be installed
              Depends: libudev1:i386 but it is not going to be installed
              Depends: libxinerama1:i386 but it is not going to be installed
              Depends: libtxc-dxtn0:i386
              Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
              Depends: libgpg-error0:i386 but it is not going to be installed
              Recommends: libxss1:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by Vistaus** [comment]
Are you using any PPA's?

**Comment by kisak-valve** [comment]
Hello @qreilly00, are you still experiencing this issue on an up to date system? Your last comment indicated the package manager was refusing to install any 32 bit packages and stopped early, but doesn't really tell us why.

**Comment by qreilly00** [comment]
Hi. That was a while ago now. I am using pop_os now and I wouldnt know if this is still a problem or not. Thanks.

**Comment by kisak-valve** [comment]
Thanks for the follow up. I'm going to assume that there was a package manager conflict outside of Steam's packaging.
