### ISSUE TITLE
Steam client the output of the terminal is overloaded with the same message.

### ISSUE THREAD

**Issue by Wolfen113** [ValveSoftware/steam-for-linux#5153]
#### Your system information

* Steam client version: 1503954609
* Distribution: Linux 4.12.8-2-ARCH
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
A few days ago in the news window wrote that there was a new steam client. After that, it was noticed in the terminal appears constantly inscription.
process 2572: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
The inscription repeats every 10 seconds.
Deterioration of the work of the customer's Steam is not noticed. But this inscription prevents you from tracking other conclusions in the terminal. For example, games errors.
Sorry, I'm writing a Google translator.

Image of the problem
https://www.dropbox.com/s/4lvlf6ezzctizt7/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_026.png?dl=0

**Comment by kisak-valve** [comment]
Hello @Wolfen113, this issue is already being tracked at #5146. Closing as a duplicate.
