### ISSUE TITLE
Linux Steam - feature missing - Install DX9c game via WINE wrapper just like dosbox

### ISSUE THREAD

**Issue by charliebrownau** [ValveSoftware/steam-for-linux#5155]
![screenshot at 2017-09-03 00-24-41](https://user-images.githubusercontent.com/31475201/29996246-80c2dc0a-903e-11e7-82c2-128a0431b12e.png)
#### Your system information

* Steam client version (build number or date): Current stable 22/Aug/2017
* Distribution (e.g. Ubuntu): Ubuntu Mate v17.04 64bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Gday
Ive just recently migrated from win7 to Linux
I was shocked to see that Steam Linux + Wine is not integrated
to install DX9c games as an wrapper , just like dosbox supported titles

Why cant we right click on an DX9c game and choose INSTALL in WINE 
instead of it just bitching its only designed for Win dx9c "invalid platform"

#### Steps for reproducing this issue:

1. Ubuntu Mate 17.04
2. Install DX9c game , eg Grim dawn
3. Invalid platform error instead of installing via WINE within steam linux native client

**Comment by kisak-valve** [comment]
Hello @charliebrownau, this feature request is already being tracked at #74. Closing as a duplicate.
