### ISSUE TITLE
Can't open the System Information menu

### ISSUE THREAD

**Issue by cybik** [ValveSoftware/steam-for-linux#5156]
#### Your system information

* Steam client version (build number or date): 1503954609
* Distribution (e.g. Ubuntu): Gentoo (mostly unsupported then)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Meh

#### Please describe your issue in as much detail as possible:
I can't open Help > System Information

#### Steps for reproducing this issue:

1. Be dumb enough to run gentoo
2. Install Steam Client
3. Onboard onto beta
4. Open Help menu
5. Open "System Information"
6. Collect logs

#### Files

https://github.com/cybik/steam-crashes/blob/0673ea9494cc8ceb9476d533b867331f06783c05/steam-crash-02-10-2017.tar.gz

**Comment by kisak-valve** [comment]
Hello @cybik, for reference, your attached minidump is a SIGSEGV in libSDL2-2.0.so.0.

Can you test updating to =media-libs/libsdl2-2.0.5-r1, `rm -r ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*`, then restart the client to regenerate the pinned library folder and retest?

**Comment by cybik** [comment]
Fixed!
