### ISSUE TITLE
Closing the chat window via middle click on the window panel causes Steam to completely close.

### ISSUE THREAD

**Issue by fantoro** [ValveSoftware/steam-for-linux#5157]
#### Your system information

* Steam client version (build number or date): Aug 28 2017, at 11:55:28
* Distribution (e.g. Ubuntu): Linux Mint Cinnamon 18 64 bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Basically closing the chat window via middle click on the window panel causes Steam to shut down.

#### Steps for reproducing this issue:

1. Open up Steam.
2. Open the "Friends" window.
3. Open a chat with one of your friends.
4. Middle click on the chat window in the window panel

(This issue can be reproduced using other windows like for example Event Notification)

**Comment by kisak-valve** [comment]
Hello @fantoro, I can not reproduce this issue on my Arch / Cinnamon 3.4.4 and Gentoo / Cinnamon 3.0.7 systems with the steps provided. We'll need to see if someone has an idea as to what's going on here.

What version of Cinnamon is on your system? Do you have an extra button binding to the middle click?

**Comment by fantoro** [comment]
My Cinnamon version is 3.4.6, I also installed GNOME 3.18.5 (and I switched to it) and the problem is still there, and no, I don't have any extra button binding to middle click.

**Comment by undeference** [comment]
Middle click for chat windows no longer causes Steam to quit, but it does for other Steam windows (e.g., Friends)

**Comment by fantoro** [comment]
I can confirm that the issue with chat is fixed (and for friends window too) but when middle clicking on the main window the issue still exists.

**Comment by Managor** [comment]
Is this still a thing after the redesign?

**Comment by kisak-valve** [comment]
Hello @fantoro, @undeference, are either of you still experiencing this issue on an up to date system?

**Comment by undeference** [comment]
> I can confirm that the issue with chat is fixed (and for friends window too) but when middle clicking on the main window the issue still exists.

This exactly

**Comment by undeference** [comment]
Closing an alert (e.g., the best-ever-phrased "invalid platform" one) causes Steam to completely close.

**Comment by fantoro** [comment]
Oh God I'm sorry I haven't checked my GitHub notifications in a while.

I've moved to KDE on Arch since opening this issue and it doesn't seem to be there, although like I said I'm on a different system and DE now so I'm not sure about my previous configuration.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
