### ISSUE TITLE
Stopped running steam client after Arch nvidia update.

### ISSUE THREAD

**Issue by Wolfen113** [ValveSoftware/steam-for-linux#5158]
#### Your system information

* Steam client version: 1503954609
* Distribution: Linux 4.12.10-1-ARCH
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Today there was an update of the system after which the Steam stopped running.
The client if it hangs trying to update. This problem has already happened to many who have Arch Linux and Antrgos
https://www.dropbox.com/s/7sddd89aqg9yycy/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202017-09-05%2014-05-25.png?dl=0

#### Steps for reproducing this issue:

1. System Update
https://www.dropbox.com/s/5mk7zojfbxmy0cw/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_028.png?dl=0

**Comment by theo546** [comment]
i have this problem too

**Comment by Plasticoo** [comment]
Well, me too. GG boys.

**Comment by Majora320** [comment]
Same thing for me, after updating to latest kernel and nvidia proprietary drivers. 
Some more info:
```
$ pidof steam
5320
$ strace -p 5320
strace: Process 5320 attached
strace: [ Process PID=5320 runs in 32 bit mode. ]
futex(0x56fbf718, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 5320 detached
 <detached ...>
$ kill 5320
[In the original terminal where I started $HOME/.local/share/Steam/steam.sh]
/home/moses/.local/share/Steam/steam.sh: line 941:  5320 Terminated              $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Installing bootstrap /home/moses/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on arch rolling 64-bit
STEAM_RUNTIME has been set by the user to: /home/moses/.local/share/Steam/ubuntu12_32/steam-runtime
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2017-09-05 13:41:21] Startup - updater built Nov 23 2016 01:05:42
Installing breakpad exception handler for appid(steam)/version(1503954609)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

**Comment by kisak-valve** [comment]
This issue is because Arch package maintainers did not update lib32-nvidia-utils along with the rest of the nvidia packages. The nvidia userspace and kernel module must match, otherwise it will refuse to run any opengl application.

Do another update cycle, make sure lib32-nvidia-utils package matches nvidia-utils and nvidia-dkms and reboot to get your system to start using the new nvidia kernel module.

**Comment by Majora320** [comment]
Apparently `lib32-nvidia-utils` *has* been updated in the official repos, but not all of the mirrors are in sync.

**Comment by OlliC** [comment]
Con confirm. After lib32-nvidia-utils got updated it runs again.

**Comment by kisak-valve** [comment]
Thanks for the follow up. Ate this point there should be no new users encountering this specific issue. Closing.
