### ISSUE TITLE
Failed to connect with local Steam Client process (Source games)

### ISSUE THREAD

**Issue by thedarkfighter413** [ValveSoftware/steam-for-linux#5162]
#### Your system information

* Steam client version (build number or date): up to date (8th September 2017)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* System info: https://gist.github.com/thedarkfighter413/82aed1964515c1e46f2131fab33999fc
* Terminal output: https://gist.github.com/thedarkfighter413/cb20ac5deafcae14fe34f9d4629eccfd

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I was expecting to launch CSGO, get kicked for not speaking russian with 7 days ban and throw my computer out of the window but CSGO did not start at all. Instead Steam crashed and this error appeard: "Failed to connect with local Steam Client process"

#### Steps for reproducing this issue:

1. Start Steam on an up to date Arch Linux
2. Start CSGO (or any Source 1 game - TF2, CSS, HL2...)
3. ![snimek z 2017-09-08 19-43-06](https://user-images.githubusercontent.com/28152817/30230415-8435c922-94e6-11e7-838f-3d434bfb01c3.png)

**Comment by kisak-valve** [comment]
Hello @thedarkfighter413, this issue is already being tracked at #5161. Closing as a duplicate.

**Comment by thedarkfighter413** [comment]
Just to let you know @kisak-valve - today I tried making dual boot with Ubuntu Gnome 17.10 and it doesn't work either. Exactly the same problem. I hope it helps.
