### ISSUE TITLE
Previously-created categories do not show in client

### ISSUE THREAD

**Issue by leftmostcat** [ValveSoftware/steam-for-linux#5165]
#### Your system information

* Steam client version (build number or date): Sep 6, 2017 20:37:28
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Library pane does not show categories. I had previously created a number of categories and used them for a period of years. After multiple client restarts on three different systems over a period of days (and client updates), categories are still absent.

#### Steps for reproducing this issue:
Unknown. Issue appeared with no immediately apparent cause.

**Comment by kisak-valve** [comment]
Hello @leftmostcat, Steam's library UI has been overhauled since this issue report. If you come across this issue again with an up to date client, it will need a new investigation. Possibly was a rare server-sided issue.

Closing as outdated.
