### ISSUE TITLE
Steam won't display the GUI and exits on CLI call

### ISSUE THREAD

**Issue by ChristopherBare** [ValveSoftware/steam-for-linux#5166]
#### Your system information

* Steam client version (build number or date): 9/12/2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04LTS
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

Hello,
I had just recently fixed a similar issue with my steam where it would give an error when I just ran "steam" in terminal. I removed a couple of conflicting libGL files and it worked for a while. Now when I run "steam" it just says: 
`Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!`

and exits the program.

I just need a little push in the right direction. 

Thanks!

**Comment by kisak-valve** [comment]
Hello @ChristopherBare, can you check if any 32 bit opengl application works outside of steam?

**Comment by rdnetto** [comment]
I've started seeing the same thing, on Sabayon (Gentoo derivative) - prints the following and hangs:
```
Running Steam on sabayon 2.2 64-bit
STEAM_RUNTIME is enabled by the user
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1504757234)
```

Driver is nvidia-drivers-384.69. The native (64-bit) glxgears works, as does the one extracted from [Ubuntu's i386 package for zesty](https://packages.ubuntu.com/zesty/mesa-utils).

### Workaround
Deleting `~/.steam` and `~/.local/share/Steam`, then running `steam` to reinstall it seems to fix it.
(Note: you probably want to backup `/.steam/steam/SteamApps` before doing this)

**Comment by ChristopherBare** [comment]
I have found a fix and wrote a quick script for the next time it happens: 
``` 
#! /bin/bash
#Steam fix script

rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
rm ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1

cd $HOME/.steam/bin/steam-runtime/i386/usr/lib/i386-linux-gnu
mv libstdc++.so.6 libstdc++.so.6.bak
cd $HOME/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu
mv libstdc++.so.6 libstdc++.so.6.bak

rm /usr/lib/i386-linux-gnu/mesa/libGL.so.1
rm /usr/lib/i386-linux-gnu/mesa/libGL.so.1.2.0 
```
It was the last part of the script that was what made it work for me. 
Hope this helps someone else! 

P.S. - You need to run it as root.

**Comment by igorsantos07** [comment]
[This SO answer](https://askubuntu.com/a/903488) explains the OP's solution.
