### ISSUE TITLE
'More discussions' temporarily freezes Steam when popup is longer than one line

### ISSUE THREAD

**Issue by Lakorta** [ValveSoftware/steam-for-linux#5167]
#### Your system information

* Steam client version (build number or date): Sep  6 2017, at 20:37:28
* Distribution (e.g. Ubuntu): Debian GNU/Linux testing (buster) (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If you are visiting a forum thread there's a box in the bottom right (you may have to scroll down) with suggestions for other threads to visit titled 'More discussions'. When hovering over one of the suggestions with your mouse a little popup appears with the text of the thread's first post as content. When this text is longer than one line it freezes Steam from one to up to several seconds (it seems to freeze longer if the text has automated line breaks instead of user made line breaks).
Popups that are just one line don't seem to cause any problems.

#### Steps for reproducing this issue:

1. Visit the Forum/Discussions of any game
2. Click on any thread
3. Hover your mouse over any of the suggested threads (you may have to scroll down to see the suggestions and it seems like the freeze starts after you move away your mouse from the suggestion).

#### Additional infos
I have this bug pretty much since I'm using Steam on Linux (I don't know when I first noticed this, so I'm not completely sure on this) and I'm using Steam on Linux since it was released for Linux. I have changed my OS a few times (different Ubuntu, SteamOS and Debian versions), replaced some hardware components and wiped my system a few times during that time. The terminal gives no output except "Refresh rate: XX" (with XX being different numbers, mostly 15 or 60) which it also does when this bug doesn't appear.
Here are some more system informations:
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3201 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Debian GNU/Linux testing (buster) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.12.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 375.82
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1600 x 900
    Desktop Resolution: 3200 x 900
    Primary Display Size: 17.40" x 9.80" (19.96" diag)
                                            44.2cm x 24.9cm (50.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT1718S

Memory:
    RAM:  7976 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_NZ.UTF-8
    Total Hard Disk Space Available:  826127 Mb
    Largest Free Hard Disk Block:  68713 Mb
    VR Headset: None detected

```

**Comment by kisak-valve** [comment]
Hello @Lakorta, this issue is already being tracked at #3994. Closing as a duplicate.

**Comment by Lakorta** [comment]
Sorry about that. I searched for similar bugs before opening this one but I guess I missed that one :)
