### ISSUE TITLE
Steam breaks on clicking play CSGO on Ubuntu 16.04

### ISSUE THREAD

**Issue by andersonzanichelli** [ValveSoftware/steam-for-linux#5168]
#### Your system information

* Steam client build date: Sep 6 2017, at 20:37:38
* Distribution: Ubuntu 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Just click on Play CSGO and the game don't open and the steam breaks.
I have tried the command: 
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
without success.

The error on the console:

[2017-09-17 01:28:58] Verifying installation...
[2017-09-17 01:28:58] Verification complete
assert_20170917012858_1.dmp[32329]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012858_1.dmp
/home/user/.local/share/Steam/steam.sh: line 941: 32242 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170917012858_1.dmp[32329]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012858_1.dmp[32329]: response: CrashID=bp-8d207190-686d-4ae0-924e-475ef2170916
assert_20170917012858_1.dmp[32329]: file ''/tmp/dumps/assert_20170917012858_1.dmp'', upload yes: ''CrashID=bp-8d207190-686d-4ae0-924e-475ef2170916''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:766

ERROR: ld.so: object '/home/user/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
assert_20170917012919_3.dmp[32334]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012919_3.dmp
assert_20170917012919_3.dmp[32334]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012919_3.dmp[32334]: response: Discarded=1
assert_20170917012919_3.dmp[32334]: file ''/tmp/dumps/assert_20170917012919_3.dmp'', upload yes: ''Discarded=1''
pid 32334 != 32333, skipping destruction (fork without exec?)
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:766

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
assert_20170917012921_6.dmp[32337]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012921_6.dmp
assert_20170917012921_6.dmp[32337]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012921_6.dmp[32337]: response: Discarded=1
assert_20170917012921_6.dmp[32337]: file ''/tmp/dumps/assert_20170917012921_6.dmp'', upload yes: ''Discarded=1''
[0917/012928.608538:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization

#### Steps for reproducing this issue:

1. Open the steam
2. Click play CSGO

**Comment by EnforcerZhukov** [comment]
Does it show some error? Maybe this is a similar/same problem as I'm dealing with here: https://github.com/ValveSoftware/steam-for-linux/issues/5159

**Comment by andersonzanichelli** [comment]
Here shows this message:

![csgoerror](https://user-images.githubusercontent.com/424028/30642235-5c9ef58e-9de0-11e7-8aaf-83d500a3e057.png)

**Comment by andersonzanichelli** [comment]
The resolution is on this issue:
https://github.com/ValveSoftware/steam-for-linux/issues/5161
