### ISSUE TITLE
Can't install Steam on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by songproducer** [ValveSoftware/steam-for-linux#5170]
#### Your system information

* Steam client version (build number or date): The latest from the website
* Distribution (e.g. Ubuntu): Ubuntu 16.04.3
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

```
$ ./steam_latest.deb

./steam_latest.deb: line 1: syntax error near unexpected token `newline'
./steam_latest.deb: line 1: `!<arch>'
```

#### Steps for reproducing this issue:

1. Make installer executable
2. Run it in terminal

**Comment by kisak-valve** [comment]
Hello @songproducer, no package manager allows the packages themselves to be executable. You'll want to run something like `apt install steam` in a terminal if there isn't a more convenient package manager utility.

Closing as invalid.
