### ISSUE TITLE
Tray icon is missing

### ISSUE THREAD

**Issue by kapsh** [ValveSoftware/steam-for-linux#5171]
#### Your system information

* Steam client version (build number or date): Sep 6 2017
* Distribution (e.g. Ubuntu): Getnoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Steps for reproducing this issue:

1. After some of system and/or Steam updates tray icon was gone.
2. This seems to be relevant error:

> (steam:13663): libappindicator-WARNING **: Unable to get the session bus: Command line `dbus-launch --autolaunch=1d35b7691f42f02d424b6b6056830dba --binary-syntax --close-stderr' exited with non-zero exit status 127: dbus-launch: /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by dbus-launch)\ndbus-launch: /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by dbus-launch)\ndbus-launch: relocation error: dbus-launch: symbol _dbus_ensure_standard_fds, version LIBDBUS_PRIVATE_1.10.22 not defined in file libdbus-1.so.3 with link time reference\n

Full log: [kapsh_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/1309338/kapsh_stdout.txt)

It looks like incompatibility between my dbus version (1.10.22) and included in steam runtime.

**Comment by soredake** [comment]
I fixed this on gentoo by adding LD_PRELOAD, like this `LD_PRELOAD='/usr/lib64/libdbus-1.so.3' steam`

**Comment by kisak-valve** [comment]
Another possible alternative would be to pin the system variant with `ln -s /usr/lib64/libdbus-1.so.3 ${HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libdbus-1.so.3`, although, it's not clear why steam is trying to use the steam runtime variant of this library over the system variant. Are you using STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0?

**Comment by kisak-valve** [comment]
@kapsh, I was unable to reproduce this issue on my gentoo / steam-runtime test box with dbus 1.10.22. What useflags are you using with the steam package and dbus? Can you list the contents of ~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*?

This probably should be brought to @anyc's attention over at https://github.com/anyc/steam-overlay as this is a distro-specific issue.

**Comment by kapsh** [comment]
@kisak-valve Yes, you are right - STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 is set in environment. I completely forgot about this (this was a fix for something that I cannot remember). 
After unsetting this variable tray icon reappeared.

**Comment by kapsh** [comment]
@kisak-valve and no tray icon with pinned system version and prefer_host_libraries=0 (should it works in this combination?)

This is pinned_libs_64 content:

```total 16K
-rw-r--r-- 1 kapsh kapsh   0 Sep  4 16:36 has_pins
lrwxrwxrwx 1 kapsh kapsh  23 Sep 18 13:59 libdbus-1.so.3 -> /usr/lib/libdbus-1.so.3
lrwxrwxrwx 1 kapsh kapsh 107 Sep  4 16:36 libGLU.so.1 -> /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004
lrwxrwxrwx 1 kapsh kapsh 108 Sep  4 16:36 libSDL2-2.0.so.0 -> /home/kapsh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.5.0
-rw-r--r-- 1 kapsh kapsh  50 Sep  4 16:36 system_libGLU.so.1
-rw-r--r-- 1 kapsh kapsh  60 Sep  4 16:36 system_libSDL2-2.0.so.0
```

Flags for dbus: X -debug -doc -elogind (-selinux) -static-libs -systemd -user-session (-test) abi_x86: 32 (64) (-x32)
Flags for steam-launcher:  steamruntime build_options: symbols=strip -dwarf_compress -optional_tests -trace work=tidyup 

[packages_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/1310461/packages_info.txt)

**Comment by kisak-valve** [comment]
The pinned library folders are expected to only be used with the steam runtime enabled and STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 (the defaults). You should not need to pin the 64 bit libdbus-1.so.3 since having STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 explains why steam was using the steam runtime variant in the first place.

If you happen to remember the library conflict which you used STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 to workaround, you should be able to pin the runtime variant of the specific library to get the same effect without needing to use that env variable and also bring it to the attention of your package maintainer for steam.

**Comment by kapsh** [comment]
Thanks for the feedback!
