### ISSUE TITLE
Steam crashes as it tries to start

### ISSUE THREAD

**Issue by airatin** [ValveSoftware/steam-for-linux#5172]
#### Your system information

* _Steam client version (build number or date):_ 1.0.0.54 I believe, but no idea now.
* _Distribution (e.g. Ubuntu):_ Linux Mint 18.2 64-bit
* _Opted into Steam client beta?: [Yes/No]_ Yes (but I deleted the beta file and it still won't load)
* _Have you checked for system updates?_: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
_Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)_

Can't start Steam whether through clicking the icon or by launching it via the terminal. The following output occurs when I type `steam` into the terminal: [Posted as a Gist](https://gist.githubusercontent.com/airatin/7c3ec4613ac18dd9701dc2c91aa781d0/raw/2b29223f0024b20f40b6f33d566dada6b62289b0/gistfile1.txt)

#### Steps for reproducing this issue:

1. Type `steam` into the terminal.

**Comment by kisak-valve** [comment]
Hello @airatin, can you test if any 32 bit opengl application works? What video card vendor / driver version are you using?

If you've recently done a system update that bumped the kernel or video driver version, you may need to reboot.

**Comment by airatin** [comment]
Hello @kisak-valve, I have Nvidia 384.59 for GeForce GTX 765M. Linux kernel is 4.4.0-93. These have stayed the same before and after I've had this issue, but even still I've tried rebooting several times to no avail.

What other 32 bit opengl application can I use? I'm not sure which applications I have that are 32bit opengl.

**Comment by kisak-valve** [comment]
I would use glxinfo from mesa-utils:i386 as a basic testcase.

**Comment by airatin** [comment]
According to the terminal, if I installed mesa-utils:i386 it would remove cinnamon which I don't want. Having said that, I typed in glxinfo into the terminal and this was the result:

`name of display: :0`
`X Error of failed request:  BadWindow (invalid Window parameter)`
`  Major opcode of failed request:  155 (NV-GLX)`
`  Minor opcode of failed request:  4 ()`
`  Resource id in failed request:  0x4e00003`
`  Serial number of failed request:  37`
`  Current serial number in output str`

**Comment by kisak-valve** [comment]
Right, it's definitely not okay for a simple test to mess with the general setup of your system. You could grab the .deb for the package, unpack it, and run it from your home folder, but you've already gotten a straight answer that the nvidia driver is currently broken and needs to be fixed.

**Comment by airatin** [comment]
Well that's strange, but I updated my Nvidia driver and it launches perfectly now. Thanks for the help!
