### ISSUE TITLE
 Problem in competitive games using S.O Linux

### ISSUE THREAD

**Issue by Gesbrener** [ValveSoftware/steam-for-linux#5173]
#### Your system information

* Steam client version (v017): 
* Distribution (Ubuntu 16.04 LTS): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
During all competitive games an error reporting "No User Logon" appears where the system disconnects me from the games not letting it reconnect until I completely close Steam and connect again. This occurs throughout the competitive section, the curious thing is that this error does not occur during any other game modalities, only competitive.

#### Steps for reproducing this issue:

1. Error mensange. 
2. Does not reconnect until restarting Steam.
3. After a few seconds, the error happens again.

![captura de tela de 2017-09-17 14-06-32](https://user-images.githubusercontent.com/32039937/30554958-845fa7ea-9c7c-11e7-94d8-d2d77565f534.png)

**Comment by kisak-valve** [comment]
Hello @Gesbrener, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1518. Closing as a duplicate.
