### ISSUE TITLE
[Web][Debian][Ubuntu][VPN] still getting http error 407 after removing proxy configs

### ISSUE THREAD

**Issue by kshatriya-abhay** [ValveSoftware/steam-for-linux#5174]
#### Your system information

* Steam client version (build number or date): 1.0.0.54 (version)
* Distribution (e.g. Ubuntu): Ubuntu 16.04.3 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Error in console: https://gist.github.com/kshatriya-abhay/0dd76d687522f8bfaa1e887e56c2ece6

Fatal error: Steam needs to be online to update.
I presume that steam should connect to internet through VPN. But as shown in the above error, it still seems to be detecting the proxy. I don't know how steam get the network info (about proxy). My current Internet connect runs Steam on Windows (via VPN) but not in Ubuntu.

#### Steps for reproducing this issue:

1. System configured (apt, bash, NetworkManager) to work with an authenticated proxy server.
2. Use a VPN client connection system-wide.
3. Remove all above proxy configurations. (system not running on proxy then)
4. Install steam from Software Center.
5.  Run steam for first time, issue reproduced.

**Comment by kshatriya-abhay** [comment]
issue solved, kindly close it

**Comment by kisak-valve** [comment]
Closing per the last comment.
