### ISSUE TITLE
Steam BPM X360 controller detection inside LXD container

### ISSUE THREAD

**Issue by honeydroid** [ValveSoftware/steam-for-linux#5175]
#### Your system information

* Steam client version (build number or date): 1504757234
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I'm definitely working on a fringe case here so I'm not looking to register an issue so much as seek a little guidance on what to look at next. I am trying to get Steam BPM running inside a LXD container. The host is Ubuntu 16.04 and the guest is also Ubuntu 16.04. I have everything working for Steam inside the LXD container for in-home streaming including audio, video, and X360 wireless controller pass-through.

My final challenge is with the addition of X360 wireless controllers during execution of Steam. It will pick up controllers that were activated prior to execution, but once inside Steam BPM a new controller, or a reconnected controller will not work until Steam is re-launched.

I'm hoping to get some advice on what mechanism Steam uses to detect newly added controllers so that I can find a way to manually trigger the event inside the container, with the hope that Steam will then pick the device up. My guess is that Steam hooks into udev and since udev does not run inside containers this event is getting missed. If this is the case, is there any code I can look at to help me narrow down my efforts in manually reproducing the event? Alternatively, if there is a verbose logging mode I could try which indicates any failed attempts to watch udev (or other) that might help me locate what is missing inside the container environment.

Many thanks for any help that can be offered. I realise my setup probably reaches beyond what could reasonably be considered in-scope for the project, so I'll be very grateful for any direction.

#### Steps for reproducing this issue:

1. Connect X360 wireless controller to host OS, device is mounted to guest using host udev rule
2. Start Steam BPM inside guest container, controller works
3. Power down X360 wireless controller
4. Reconnect X360 wireless controller, device is re-mounted to guest using host udev rule
5. Controller does not work inside Steam BPM
6. Exit and re-open Steam BPM. Controller works.

**Comment by kisak-valve** [comment]
Hello @honeydroid, are you still experiencing this issue on an up to date system? Possibly related to #5063.

**Comment by kisak-valve** [comment]
Closing pending feedback.
