### ISSUE TITLE
PrefetchW on linux not supported

### ISSUE THREAD

**Issue by dormancygrace** [ValveSoftware/steam-for-linux#5176]
#### Your system information

* Steam client version (build number or date): Sep 6 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.04 64 bit
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
![screenshot from 2017-09-20 14-13-35](https://user-images.githubusercontent.com/20384748/30657156-3ed6ddb4-9e3f-11e7-8d71-9f91e8bb9b88.png)
![steam windows](https://user-images.githubusercontent.com/20384748/30657157-3edefac6-9e3f-11e7-98cf-4d36f9cf61ac.png)

#### Please describe your issue in as much detail as possible:
In windows 10 pro 64-bit steam says that PrefetchW is supported. on ubuntu it say Not supported. 
The CPU is Intel Xeon E5430
#### Steps for reproducing this issue:
Simply open Help>System Information

**Comment by kisak-valve** [comment]
Hello @dormancygrace, a quick google search indicates this hardware does not support PrefetchW. Additionally, it is required for [Windows 10 64-bit](https://www.microsoft.com/en-us/windows/windows-10-specifications#additional-requirements), so there most likely is an Intel driver for Windows that is emulating the hardware feature.

Closing as this is not a steam for linux problem.

**Comment by dormancygrace** [comment]
I`ve checked on windows 7 pro 64-bit, with CPU Intel T8300. Still says that PrefetchW supported, I can`t find info about when this instruction appeared in Intel CPU....

**Comment by kisak-valve** [comment]
Take a look at the first PDF page at https://www-ssl.intel.com/content/www/us/en/embedded/products/broadwell-u/5th-gen-core-mobile-u-processor-platform-brief.html, which indicates a real prefetchw implementation first appeared in Intel with Broadwell processors. It was originally introduced as part of 3dnow on AMD cpus.

**Comment by dormancygrace** [comment]
Thx. I`ve found about the origin of that instruction, but not about Intel. I`ve created "ticket" on steam support for windows
