### ISSUE TITLE
Problem with steam magnetic link

### ISSUE THREAD

**Issue by SergioGlorias** [ValveSoftware/steam-for-linux#5177]
#### Your system information

* Steam client version (build number or date): 1504757234
* Distribution (e.g. Ubuntu): Linux Mint 18.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam magnetic link does not start its task
as shown in this video: https://youtu.be/sMHRZOmKzEM

#### Steps for reproducing this issue:

1. * Steam client version (build number or date): 1504757234
2. Find a steam magnetic link (any)
3. try to run it (with the game open and not open (any))

**Comment by kisak-valve** [comment]
Hello @sergio200hs, this functionality is handled outside of steam, typically by your desktop environment. In a working setup, `xdg-open` followed by the steam:// url should launch the game.

**Comment by sergio200hs** [comment]
OK
I managed to start the game by the shortcut but he did not go to the demos
but another thing I wanted to be able to do this without having to create a shortcut type the faceit has the button with the link and the command of the console and I create start directly through the browser (which also does not give (does the same thing as in the discord ))

> I'm sorry for my english
> I'm not good
> and I have to use google

**Comment by kisak-valve** [comment]
Hello @SergioGlorias, are you still experiencing this issue on an up to date system?

**Comment by SergioGlorias** [comment]
@kisak-valve this bug is no longer happening

**Comment by kisak-valve** [comment]
Thanks, closing.
