### ISSUE TITLE
Steam starts game after self-update

### ISSUE THREAD

**Issue by nazar-pc** [ValveSoftware/steam-for-linux#5179]
#### Your system information

* Steam client version (build number or date): Sep 21 2017, at 17:46:42
* Distribution (e.g. Ubuntu): Ubuntu 17.10 x64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

0. Have Steam closed
1. Open some Steam game using Desktop link (like `steam steam://rungameid/212070`)
2. Close game, leave Steam running in background
3. Receive Steam update, agree to restart

#### What happened
Steam have launched the game I've initially opened

#### What should have happened instead
Steam after restart should only start itself, not the game it was started for initially

**Comment by kisak-valve** [comment]
Hello @nazar-pc, this issue is already being tracked at #1414. Closing as a duplicate.
