### ISSUE TITLE
System Shock 2: libGL.so.1: undefined symbol: xcb_unregister_for_special_event

### ISSUE THREAD

**Issue by yegortimoshenko** [ValveSoftware/steam-for-linux#5182]
#### Your system information

* Steam client version (build number or date): Sep 6 2017, at 20:37:28
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

See https://github.com/NixOS/nixpkgs/issues/29709 for context.

System Shock 2 comes with custom `libxcb.so` which isn't compatible with modern Mesa versions.

1. Download latest Mesa drivers (you need Intel integrated graphics).
2. Install and try to run System Shock 2.

```
$ tail /tmp/dumps/_stdout.txt
>>> Adding process 31293 for game ID 238210
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 31382 for game ID 238210
>>> Adding process 31471 for game ID 238210
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/chronos/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
/home/chronos/.local/share/Steam/steamapps/common/SS2/bin/wineloader: symbol lookup error: /run/opengl-driver-32/lib/libGL.so.1: undefined symbol: xcb_unregister_for_special_event
>>> Adding process 31490 for game ID 238210
Game removed: AppID 238210 "System Shock 2", ProcID 31164 
No cached sticky mapping in ActivateActionSet.
```

Proposed solution is to ask System Shock 2 developers to either remove `lib/libxcb.so.1.1.0` from game distribution and use the one that is provided in Steam runtime, or update it to the newest version.

**Comment by kisak-valve** [comment]
Hello @yegortimoshenko, the proposed solutions are fair, but your developer is in another castle. This issue tracker is meant for the Steam client itself and you need to reach out to the game devs.

**Comment by yegortimoshenko** [comment]
@kisak-valve Sorry, I thought this tracker takes in 3rd party game bug reports as well. I'll email the devs. Should I close this?

**Comment by kisak-valve** [comment]
The third party game issues in this tracker are generally those where it is unclear if the issue is with the game or some part of steam. Since the cause of this issue is clearly a game bundled library, there isn't much for a Valve dev to do to resolve the issue.

**Comment by yegortimoshenko** [comment]
I see. Thanks for prompt replies!
