### ISSUE TITLE
Steam doesn't support newer dbus or glibc?

### ISSUE THREAD

**Issue by jcfrosty** [ValveSoftware/steam-for-linux#5183]
#### Your system information

* Steam client version (build number or date): 1506111624
* Distribution (e.g. Ubuntu): Sabayon Linux (Gentoo)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam has issues with newer versions of dbus and glibc.

https://help.steampowered.com/en/wizard/HelpRequest/HT-3PGR-2642-VPR6

#### Steps for reproducing this issue:

1. Run Steam from terminal.
2. Profit

This is normally a bug in some application using the D-Bus library.
process 5478: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
process 5478: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.
This is normally a bug in some application using the D-Bus library.
process 5478: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
process 5478: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.
process 5478: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2794.
This is normally a bug in some application using the D-Bus library.

jcfrosty 5478 14.6 0.4 687432 145420 pts/1 Sl+ 22:13 0:01 /home/jcfrosty/.local/share/Steam/ubuntu12_32/steam

[10433.698834] steam[5478]: segfault at 114 ip 00000000ef65e116 sp 00000000ffb5d390 error 4 in libdbus-1.so.3.5.8[ef633000+47000]
[10433.705314] CIPCServer::Thr[5525]: segfault at cf5e3000 ip 00000000f73fcf72 sp 00000000e80feb78 error 4 in libc-2.23.so[f72c4000+19f000]

Package: sys-libs/glibc-2.23-r4 branch: 5, [sabayonlinux.org] 
╠          Available:     version: 2.23-r4 ~ tag: NoTag ~ revision: 0
╠          Installed:     version: 2.23-r4 ~ tag: NoTag ~ revision: 0

Package: sys-apps/dbus-1.10.22 branch: 5, [sabayonlinux.org] 
╠          Available:     version: 1.10.22 ~ tag: NoTag ~ revision: 0
╠          Installed:     version: 1.10.22 ~ tag: NoTag ~ revision: 0

**Comment by kisak-valve** [comment]
Hello @jcfrosty, the dbus_connection messages are typically non-fatal and is being tracked at #5146. Are you hitting a functional issue in addition to these messages?

**Comment by jcfrosty** [comment]
I've noticed instability, but I'm going to blame AMDGPU for that until its complete. I'm not using display code or PRO. 4.12 and latest xf86-video-amdgpu seems to cause issues with libcef.so and games tend to crash after few hours of gameplay. I'm also not sure if my issues for steam Big Picture mode are related to AMDGPU, my 3840x1080 49inch monitor, or some other strange incompatibilities.

**Comment by kisak-valve** [comment]
Those symptoms do not sound related to dbus or glibc. Please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to the crashes you are seeing, please attach them as well.

**Comment by ranisalt** [comment]
Welcome to proprietary software hell.

**Comment by kisak-valve** [comment]
Hello @jcfrosty, are you still experiencing this issue on an up to date system?

**Comment by jcfrosty** [comment]
This has been fixed

**Comment by kisak-valve** [comment]
Thanks for the follow up, closing.
