### ISSUE TITLE
Low hitbox on linux client

### ISSUE THREAD

**Issue by SupremeTamer** [ValveSoftware/steam-for-linux#5186]
#### Your system information

* Steam client version (build number or date): Ubuntu  steam client from repository (I d`ont remember it because i deleted ubuntu)
* Distribution (e.g. Ubuntu): Ubuntu 17.04, 17.10
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
In windows client i have normal hitbox. Fore example from AK i make 70-90 damage from 2-3 shots.
In linux client usual i make 5-7 shots from AK, but only 1-2 of them passes, and make 18-27 damage.
After migrating from linux to windows i have ranked up from gold nova 1 to gold nova 4 in 2 days. And yesterday when i played on linux again, i saw this difference again.

**Comment by kisak-valve** [comment]
Hello @SupremeTamer, this sounds like a CS:GO issue, so let's track it in the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1528.
