### ISSUE TITLE
[alsa] steam voice gets scratchy after a while

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5187]
stable steam client: 1504757234

After playing dota2 a while, steam voice gets scratchy. I have to restart steam to fix it. The people I played with, did report to me the issue I could confirm in the steam voice test.

alsa and usb mic.
linux 4.13.3
system alsa-lib 1.1.4.1
no pulseaudio

**Comment by sylware** [comment]
with the new steam voice, in-game voice is now broken on my system (alsa dmix on realtek HDA chip). Cannot test anymore.

**Comment by cminnoy** [comment]
Maybe related or not, but streaming for a longer period of time to the steam-link hardware also starts producing scratch sound (happens after tens of minutes). It looks like a timing/sync issue. With the steam link if you choose to stop streaming, but leave the game running, and then reconnect to the game the scratchy sound disappears. This leads me to believe that it is a sync problem.

**Comment by sylware** [comment]
cannot reproduce. Will re-open if back.
