### ISSUE TITLE
Steam friend status won't update after resuming the system from suspend

### ISSUE THREAD

**Issue by Kurolox** [ValveSoftware/steam-for-linux#5189]
#### Your system information

* Steam client version (build number or date): Sep 21 2017, at 17:46:42
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Whenever you resume your system from suspend, and steam was opened before the suspend was issued, when resuming the friend list will be stuck at the same state it was before suspending, and it won't correct itself until about 10 minutes have passed (the steam chat will disconnect and then reconnect).

The chat should disconnect and reconnect as soon as you resume your system from suspend, instead of being an arbitrary amount of time stuck. While it's stuck, trying to message steam friends will result in them not receiving any message without any warning. The only workaround is to manually close steam and open it again after suspend.

#### Steps for reproducing this issue:

1. Open steam
2. Open the friend list
3. Suspend the system (ie: `systemctl suspend`)
4. Wait some time before resuming
5. Resume your system, your friends list will be stuck in the same status it was when you suspended until steam decides to disconnect and reconnect automatically

**Comment by kisak-valve** [comment]
Hello @Kurolox, can you check if this is the same issue reported at #3689? Do you run networkmanager as a system service?

**Comment by Kurolox** [comment]
I can confirm that it's the same issue. I don't run networkmanager. I'm using networkctl to manage my network.

**Comment by kisak-valve** [comment]
Thanks, closing in favor of the existing issue report.

**Comment by Cabanur** [comment]
I also have this issue, but I *am* running NetworkManager

* Steam client version (build number or date): Sep 21 2017, at 17:46:42
* Distribution: Debian Testing
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* [Full system information](https://gist.github.com/Cabanur/34a95df37251818ac46cc7d311e56a96)

When waking up the system after suspension/sleep, the friend list shows all friends' status as they were before suspension. The client allows me to open chat windows and send chat messages, but fails to deliver them.

Upon launching a game, the steam cloud sync will fail, and the client will offer to launch the game without syncing.

```
cabanur $ sudo service network-manager status
● NetworkManager.service - Network Manager
   Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-09-27 16:11:34 CEST; 1 day 1h ago
     Docs: man:NetworkManager(8)
 Main PID: 648 (NetworkManager)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/NetworkManager.service
           └─648 /usr/sbin/NetworkManager --no-daemon

Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1627] manager: NetworkManager state is now CONNECTING
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1635] device (eth1): state change: prepare -> config (reason
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1642] device (eth1): state change: config -> ip-config (reas
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1727] device (eth1): state change: ip-config -> ip-check (re
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1738] device (eth1): state change: ip-check -> secondaries (
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1743] device (eth1): state change: secondaries -> activated 
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1745] manager: NetworkManager state is now CONNECTED_LOCAL
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1903] manager: NetworkManager state is now CONNECTED_GLOBAL
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1904] policy: set 'manual ' (eth1) as default for IPv4 routi
Sep 28 17:05:44 sobremesa NetworkManager[648]: <info>  [1506611144.1908] device (eth1): Activation: successful, device activate
```
