### ISSUE TITLE
CS:GO won't launch; says Steam client needs to be updated, and then confirms that it's up to date.

### ISSUE THREAD

**Issue by krompus** [ValveSoftware/steam-for-linux#5190]
I'm on Steam main branch, Arch Linux, everything is up to date. Rebooted, etc.

Other people have reported the issue on Reddit, and both MacOS and Linux are affected.

It seems beta branch opt-in fixes the issue, but I've had many issues with beta before, and I'd prefer to stick to main because, well, it's usually less likely to do weird stuff like this. :P

**Comment by klausenbusk** [comment]
I can confirm this on ArchLinux with everything up to date.

**Comment by ilivans** [comment]
Ubuntu as well, other games work perfectly

**Comment by klausenbusk** [comment]
Reddit post: https://www.reddit.com/r/GlobalOffensive/comments/73250i/csgo_wont_start_up_on_my_mac_anymore/

**Comment by uldall** [comment]
Linux Mint 18.2 here. I can now install CS:GO after opting in for the Steam Beta Client. I will update more post when I know whether I can launch as well.

**Comment by kisak-valve** [comment]
For easy reference, you can opt into the steam beta client with Steam -> Settings -> the change button in the Beta participation section -> switch the dropdown choice from none to Steam Beta Update.

**Comment by agutierrezrodriguez** [comment]
Same problem on Ubuntu 16.04

**Comment by EtienneWan** [comment]
Seeing this too on Ubuntu 17.04

**Comment by kisak-valve** [comment]
This issue should now be resolved. Please tell steam to check for a client update if you are encountering this issue.

**Comment by krompus** [comment]
@kisak-valve

Awesome, thanks for the rapid response!

(haven't yet confirmed, mind; I'm away from my box)
