### ISSUE TITLE
CS:GO requires update to start, but steam is already up-to-date

### ISSUE THREAD

**Issue by cunhazera** [ValveSoftware/steam-for-linux#5191]
#### Your system information

* Steam client version (build number or date): 17.0.4 64-bit
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

I'm trying to run CS:GO, but it says that I must update steam to run it. And when I try to update steam it says it's already up-to-date.

#### Steps for reproducing this issue:

1. Open steam
2. Try to run a game
3. Check that it doesn't start requiring update.

**Comment by kisak-valve** [comment]
Hello @cunhazera, this issue should be resolved. Have steam check for a new steam client update.

Closing as a duplicate of #5190.
