### ISSUE TITLE
line 941 Segmentation fault

### ISSUE THREAD

**Issue by fennec2000** [ValveSoftware/steam-for-linux#5192]
#### Your system information

* Steam client version (build number or date): Fri 29 Sept
* Distribution (e.g. Ubuntu): Steam on fedora 26 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
$ steam
Repairing installation, linking /home/fennec/.steam/steam to /home/fennec/.local/share/Steam
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1506500000)
/home/fennec/.local/share/Steam/steam.sh: line 941: 13417 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
/home/fennec/.local/share/Steam/steam.sh: line 657: no match: ssfn*

#### Steps for reproducing this issue:
1. run steam in console
I have tried alot of work arrounds that I have found none have helped.
STEAM_RUNTIME=0 steam
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
LC_ALL=C steam
steam --reset

The only different one is the steam -textclient which gives
$ steam -textclient
Repairing installation, linking /home/fennec/.steam/steam to /home/fennec/.local/share/Steam
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1506500000)
Installing breakpad exception handler for appid(steam)/version(1506500000)
Installing breakpad exception handler for appid(steam)/version(1506500000)
Failed to load steamconsole.so - dlerror(): steamconsole.so: cannot open shared object file: No such file or directory
Installing breakpad exception handler for appid(steam)/version(1506500000)
Installing breakpad exception handler for appid(steam)/version(1506500000)
[2017-09-29 15:03:08] Startup - updater built Sep  6 2017 20:37:15
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-09-29 15:03:08] Checking for update on startup
[2017-09-29 15:03:08] Checking for available updates...
[  0%] Checking for available updates...
[2017-09-29 15:03:08] Download skipped: /client/steam_client_ubuntu12 version 1506500000, installed version 1506500000
[2017-09-29 15:03:08] Nothing to do
[2017-09-29 15:03:08] Verifying installation...
[----] Verifying installation...
[2017-09-29 15:03:08] Performing checksum verification of executable files
[2017-09-29 15:03:09] Verification complete
[----] !!! Fatal Error: Failed to load steamconsole.so
[2017-09-29 15:03:09] Shutdown

I have ran out of ideas, any others?

**Comment by kisak-valve** [comment]
Hello @fennec2000, is this a new install or a regression on your system? Please describe your hardware, in particular, what video card vendor / version you are using. Can you confirm that any other 32 bit opengl application works?

**Comment by fennec2000** [comment]
this is a new install did it this morning.
Intel(R) Core(TM) i7-4820K CPU
GP104 [GeForce GTX 1080] = GIGABYTE NVIDIA GeForce GTX 1080 G1 GAMING
Linux undefined 4.12.14-300.fc26.x86_64 #1 SMP Wed Sep 20 16:28:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
its fedora 26 MATE
I can play games like: A Virus Named TOM and 10,000,000 which I download off humble bundle

**Comment by kisak-valve** [comment]
I don't have 10,000,000 to test, besides that, glmark2 from the package manager should be 64 bit by default and A Virus Named Tom should have both a 32 bit and 64 bit variants. See if CircuitGame.bin.X86 works (instead of the launcher script using CircuitGame.bin.X86_64).

**Comment by fennec2000** [comment]
Yeah I have tried running the x86 versions and it does not run.
I have worked it out, what i did was install all 32bit libs required and all mesa from the distro.
This did not work, so as a last shot, reinstalled nvidia, since doing that it has worked.
Thanks for the help.

**Comment by tbarbette** [comment]
I have the exact same problem. Any more details on your nvidia reinstallation?

**Comment by fennec2000** [comment]
I installed all the mesa parts I could find and made sure god was also working. Then I did a clean install of the Nvidia drivers. Then I did a clean install of steam. My problem was the order in which I did it. On mine Nvidia could not find mesa because I installed it after and the reinstall must of included the new files. Then everything started to work.
