### ISSUE TITLE
"one instance" does not work anymore; steam starts an own instance for every

### ISSUE THREAD

**Issue by Tids** [ValveSoftware/steam-for-linux#5194]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/18744080/31076071-dfc4be3e-a778-11e7-80c0-833cfb208eb7.png)
* Distribution (e.g. Ubuntu):
Manjaro 
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
When i type in a terminal: `steam&steam&steam` it launches 3 instances of steam. This behavior was not always there, normally steam should see that there is a running instance and use this one. This is also a big issue since i just click on games on the menu and also in there, steam tries to start a new instance for every game.

#### Steps for reproducing this issue:

1. start a game from the menu, close the game
2.  start another one from the menu

![image](https://user-images.githubusercontent.com/18744080/31076294-c33f9f44-a779-11e7-9d53-56b1756899b2.png)

**Comment by kisak-valve** [comment]
Hello @Tids, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
