### ISSUE TITLE
In LXD container: Client crashes on "Help > System Information"

### ISSUE THREAD

**Issue by simos** [ValveSoftware/steam-for-linux#5196]
#### Your system information

* Steam client version (build number or date): *Built Sep 6 2017, at 20:37:28 (package ver: 1506500000)*
* Distribution (e.g. Ubuntu): *Ubuntu 16.04 in an LXD container*
* Opted into Steam client beta?: [Yes/No] *No*
* Have you checked for system updates?: [Yes/No] *Yes*

#### Please describe your issue in as much detail as possible:
I set up an LXD container according to the instructions at
https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/
and installed Steam.

#### Steps for reproducing this issue:

1. Run `steam`
2. Get prompted to participate in the survey or click Help→System Information
3. Steam will try to retrieve system information and then it will crash, leaving a dump in /tmp/

Workaround: 
Install the package `dbus-x11` by running

`sudo apt install dbus-x11`

**Comment by kisak-valve** [comment]
Hello @simos, looks like this package provides dbus-launch, which I doubt can be sanely provided cross-platform. You may also want to bring this to the attention of your distro's package maintainer for steam.

**Comment by simos** [comment]
The warning is
`
(steam:13313): libappindicator-WARNING **: Unable to get the session bus: Error spawning command line `dbus-launch --autolaunch=5bfb43196f47422f80eb40261cfa68cb --binary-syntax --close-stderr': Failed to execute child process "dbus-launch" (No such file or directory)
`

I think that `steam` should check when `dbus-launch` is missing and deal with it gracefully (that is, not crash, perhaps refuse to run if DBUS is not found).

**Comment by kisak-valve** [comment]
Hello @simos, are you still experiencing this issue on an up to date system?

**Comment by simos** [comment]
Hi @kisak-valve, I no longer can replicate this issue on my system.

Therefore, I am closing this issue.

p.s. I am using now these updated steps to run Steam in a LXD container.
