### ISSUE TITLE
PS4 DS4 controller not recognized by Steam on Ubuntu 16.04

### ISSUE THREAD

**Issue by Stivanification** [ValveSoftware/steam-for-linux#5198]
#### system information

* Steam client version (build number or date): Built: Oct 4 2017, at 22:37:25
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam does not recognize my PS4 DS4 controller. The controller is connected via Bluetooth and is recognized by the OS, which I know because it works on http://html5gamepad.com/. When I open Steam and press the PS4 button, the system enters the Big Picture Mode, however it doesn't seem to respond to any action besides that. The controller menu in the Big Picture Mode says "no controller detected". I get the exact same results when connecting the controller via USB. 

#### Steps for reproducing this issue:

1. Connect controller to computer via USB or Bluetooth.
2. Start Steam.
3. Enter Big Picture Mode.

**Comment by kisak-valve** [comment]
Hello @Stivanification, can you give the workaround at https://github.com/ValveSoftware/steam-for-linux/issues/2218#issuecomment-50720454 a try?

**Comment by Stivanification** [comment]
Nevertheless, I made the dev/input/event15 file readable for everyone and executed `env SDL_JOYSTICK_DEVICE=/dev/input/event15 steam`, still the controller is not detected.

**Comment by Stivanification** [comment]
I made the dev/input/event15 file readable for everyone and executed `env SDL_JOYSTICK_DEVICE=/dev/input/event15 steam`, still the controller is not detected.

**Comment by Enigma0** [comment]
For me, I am able to use the touchpad as a mouse and for clicking somehow but nothing else works.

**Comment by Enigma0** [comment]
I reinstalled my OS and started pairing by just plugging it in via USB and it was properly detected and worked. After that I unplugged it and paired it via bluetooth. (PS4 configuration support enabled)

Still doesn't work in most games though so huge let down.

**Comment by darkblackcorner** [comment]
Same here.  USB and Bluetooth both work using the HTML tester, but neither are picked up by Steam.

**Comment by leifmetcalf** [comment]
I have the same problem on a fresh install of Ubuntu 18.10. Games and http://html5gamepad.com detect the DS4, but Steam doesn't. The workaround at #2218 does not fix the issue.

I am using the Steam beta.

**Comment by harritaylor** [comment]
Just dropping by, I suddenly started having this issue too. Freshly installed 18.04 LTS and controller not being detected by steam despite it working previously.

**Comment by kisak-valve** [comment]
Hello @harritaylor, do you have the `steam-devices` package installed?

**Comment by harritaylor** [comment]
@kisak-valve 
> Hello @harritaylor, do you have the `steam-devices` package installed?

Hello, no - I don't think so. 
`hlt@ubuntu:~$ steam-devices`
`steam-devices: command not found`
and `dpkg -l | grep steam-devices` returns nothing.

How do I install it? Thanks.

**Comment by Noctis-Bennington** [comment]
I guess kisak-valve was talking about:
"sudo apt install steam-devices"
But it didn't work (at least for me), I had to do this steps ---> https://steamcommunity.com/app/221410/discussions/0/1693795812304458372/

**Comment by kisak-valve** [comment]
Hello, is anyone seeing this issue on an up to date system? If the distro-provided `steam-devices` package is out of date, then that should be mentioned to the distro's package maintainer(s) for Steam.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by MurdoMaclachlan** [comment]
I've randomly started having this issue on Slackware 14.2. The controller was working fine for me a few days ago on Dark Souls Remastered, but it randomly started not detecting it. The workaround at https://steamcommunity.com/app/221410/discussions/0/1693795812304458372/ doesn't work for me because my 99 .rules file is not -steam-controller-perms, it's -fuse.

**Comment by pttoth** [comment]
I've had the same problem on Linux Mint 19.3 (Tricia).
Giving read permissions and setting the environment variables didn't work.

Installing the 'steam-devices' package fixed the issue:
1: sudo apt install steam-devices)
2: restart steam
3: reconnect the controller via USB
