### ISSUE TITLE
debian; after putting machine to sleep steam client does not login to service

### ISSUE THREAD

**Issue by DeliveryService** [ValveSoftware/steam-for-linux#5199]
#### Your system information

* Steam client version (build number or date):    build 4th of Oct 2017 blah blah
* Distribution (e.g. Ubuntu): Debian testing fully updated
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After putting my box to sleep, then steam client does not reauthenticate (after a minute). 

#### Steps for reproducing this issue:

1. login to steam
2. put device to sleep
3. wait an hour
4. wake up device
5. steam does not authenticate and you cannot start an online game

Workaround; exit and restart steam,

Issue is rather annoying

**Comment by kisak-valve** [comment]
Hello @DeliveryService, this issue is already being tracked at #474. Closing as a duplicate.
