### ISSUE TITLE
Mic on L4D2 Just Randomly Stops Working

### ISSUE THREAD

**Issue by buckwangs** [ValveSoftware/steam-for-linux#5202]
#### Your system information

* Steam client version (build number or date): Latest (not beta)
* Distribution (e.g. Ubuntu): Fedora 26 (up to date)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Randomly at some point, my mic just stops working in Left 4 Dead 2. This was not a problem until very recently. It's quite upsetting as voice is a pretty big deal in the game and just losing it out of nowhere sucks quite a lot. I don't know the steps to reproduce it but lately it's pretty reliably just failing on me out of nowhere. Are there any logs or something I can do to figure out what's going on?

**Comment by kisak-valve** [comment]
Hello @buckwangs, L4D2 should be using OpenAL for voice chat and the most recent game update was 2 months ago. If it was known good in this time, then it hints that a system change may be involved.

**Comment by kisak-valve** [comment]
Let's track this in the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2328.
