### ISSUE TITLE
Team Fortress 2 crashing

### ISSUE THREAD

**Issue by diamondburned** [ValveSoftware/steam-for-linux#5204]
* Steam client version (build number or date): 1.0.0.54-1, 1507158695, built Oct 4 2017, 22:37:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

Normally, I was able to play Team Fortress 2 on my machine. However, when I join a server, TF2 suddenly crash. Here's the crash log: https://dtf2second.ddns.net/dumps/

#### Steps for reproducing this issue:

1. Launch the game
2. Join a server
3. TF2 prints out crash dump at /tmp

**Comment by kisak-valve** [comment]
Hello @diamondburned, let's track this issue on the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2330.

**Comment by diamondburned** [comment]
Fixed by switching to Steam (Runtime)
