### ISSUE TITLE
Unnecessary security dialog launching Source mods

### ISSUE THREAD

**Issue by scqless** [ValveSoftware/steam-for-linux#5206]
This was technically observed in Windows (and WINE), but I am unaware of a good place for reporting Windows issues. But it probably would happen in Linux too, anyways. **EDIT**: It happens on Linux too.

#### Your system information

* Steam client version (build number or date): Oct 13 2017, at 16:28:02
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
What should happen is that Steam launch the mod normally, as no launch options are present for this Source mod. However, instead I get an unnecessary security dialog:

![image](https://user-images.githubusercontent.com/3085852/31577939-288037be-b0e5-11e7-892c-18c4ef7c872c.png)

This occurs on a fresh install of Windows as well as WINE.

#### Steps for reproducing this issue:

1. Install a mod (in this case, GoldenEye: Source which runs on Source SDK Base 2007)
2. Run it
3. ???
4. PROFIT!

**Comment by kisak-valve** [comment]
Hello @scqless, in general, Source SDK 2007 does not have a linux client. This issue is outside the scope of this issue tracker, so there may be little to no feedback here.

**Comment by scqless** [comment]
I just tested, and this happens with Linux and SDK Base 2013 as well:

![screenshot from 2017-10-14 15-48-05](https://user-images.githubusercontent.com/3085852/31578830-3e4a8358-b0f7-11e7-87d2-607d806844f3.png)

So I believe at this point it happens with all Source mods, regardless of platform.

**Comment by scqless** [comment]
@kisak-valve forgot to add the wontfix-because-we-stopped-caring-about-our-community tag

**Comment by scqless** [comment]
Closed because this went away on its own, probably by accident since obviously Valve doesn't pay attention to these issues.
