### ISSUE TITLE
UI not redrawing after restarting in offline mode while in Big Picture mode

### ISSUE THREAD

**Issue by buckysrevenge** [ValveSoftware/steam-for-linux#5208]
#### Your system information

* Steam client version (build number or date): 13.Oct.2017 1507938604, but has been an issue for months
* Distribution (e.g. Ubuntu): SteamOS 2.0, update 1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If you click on the power icon in the Big Picture interface and select the option to go offline, once the system gets back to the main screen, the interface no longer redraws when moving around with a game controller (you can hear sounds like the highlighted selection changing). Logging out and logging back in seems to fix this. I saw on the Steam Big Picture forums someone on Windows 10 was having this problem, too, but no one responded to them (post was from April 2017) so I thought we'd have better luck getting feedback here.

#### Steps for reproducing this issue:

1. Be in Big Picture mode using a controller
2. Select the power icon and choose to restart in offline mode

**Comment by kisak-valve** [comment]
Hello @buckysrevenge, are you still experiencing this issue on an up to date system?

**Comment by buckysrevenge** [comment]
I'm no longer using SteamOS, so I can't recreate this (running manjaro stable with steamos-compositor-plus)

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
