### ISSUE TITLE
libc.so.6

### ISSUE THREAD

**Issue by TheMixtureMedia** [ValveSoftware/steam-for-linux#5209]
#### Your system information

* Steam client version (build number or date): Not sure it will not boot up
* Distribution (e.g. Ubuntu): Kubuntu 17.10 64bit 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: can not will not load

#### Please describe your issue in as much detail as possible:
Hi there I am using Kubuntu 17.10 64bit and getting this error when I try to launch Steam. "You are missing the following 32-bit libraries, and Steam may not run: libc.so.6". I have tried to uninstall Steam and reinstall it and same issue.

#### Steps for reproducing this issue:

1. did update for steam
2. did update for Kubuntu
![screenshot_20171015_133843](https://user-images.githubusercontent.com/32842614/31615429-ec08a286-b25f-11e7-9d38-67477d72b462.png)

**Comment by kisak-valve** [comment]
Hello @TheMixtureMedia, what does steam do after running `sudo apt install libc6-i386` in a terminal?

**Comment by TheMixtureMedia** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6-i386 is already the newest version (2.26-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by TheMixtureMedia** [comment]
Hey there I just cleaned out Steam again from my os and got this error message now
"Fatal Error: Failed to load steamui.so"

**Comment by TheMixtureMedia** [comment]
"Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386"

"Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libdrm-amdgpu1:i386 (>= 2.4.80) but it is not going to be installed
                        Depends: libdrm-intel1:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.66) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.75) but it is not going to be installed
 libgl1-mesa-glx:i386 : Depends: libdrm2:i386 (>= 2.4.75) but it is not going to be installed
                        Conflicts: libgl1
E: Unable to correct problems, you have held broken packages.
Press return to continue: "

**Comment by kisak-valve** [comment]
These packages are for 32bit mesa, the general idea is that Steam needs a sane 32 bit opengl implementation in order to work.

Just to confirm, what video card vendor / version are you using?

**Comment by TheMixtureMedia** [comment]
Hi there I am running Gigabyte RX480 8gig video card at this moment. It was working before either update from Steam or Kubuntu/Ubuntu caused this issue. I did both updates then rebooted the computer the next day and was not able to load Steam.

**Comment by scqless** [comment]
Try `sudo apt install -f`; looks like a failed upgrade for some reason.

**Comment by kisak-valve** [comment]
Hello @TheMixtureMedia, are you still experiencing this issue on an up to date system?
