### ISSUE TITLE
CS:Go crashes randomly which causes hang on all system

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#5210]
#### Your system information

`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 18.2 Sonya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.11.0-14-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 384.90
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c8d
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.60" (15.51" diag)
                                            34.4cm x 19.3cm (39.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC233

Memory:
    RAM:  7866 Mb

Miscellaneous:
    UI Language:  English
    LANG:  tr_TR.UTF-8
    Total Hard Disk Space Available:  938771 Mb
    Largest Free Hard Disk Block:  375720 Mb
    VR Headset: None detected

Recent Failure Reports:

`

* Steam client version (build number or date): October 13 2017 , 1507938604
* Distribution (e.g. Ubuntu): Linux Mint 18.2 Cinnamon 64 bit
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:

CS:Go hangs my all system sometimes. I don't know what is the reason , it just happens.
#### Steps for reproducing this issue:

1. A Steam installation
2. CS:Go installation
3. It is crashing sometimes , my driver version is 384.90

**Comment by kisak-valve** [comment]
Hello @Leopard1907, let's track this issue in the CS:GO issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1539.

**Comment by Leopard1907** [comment]
Can you open it again? Because it is happening ,  not fixed.

And i have an idea actually why it happens.

I force closed my laptop again and i saw cpu throttled messages. 

When CPU gets heated and automatically throttles itself , CS:Go crashes.

I have to say , i'm playing Doom 2016 on Ultra settings via Wine but that never occurred and that game also heats a lot.

So that is clearly a CS:Go issue , not driver originated.

@kisak-valve
