### ISSUE TITLE
Disconnected from CSGO matches, "No User Logon"

### ISSUE THREAD

**Issue by krompus** [ValveSoftware/steam-for-linux#5211]
This happens every couple of days, seemingly randomly, and it's quite frustrating when playing competitive matches. It even happens when I'm practicing nades offline.

Internet connection is fine, and it lets me rejoin before kicking me again one minute later.

What could be the cause? A restart fixes it, but I'd like to prevent it entirely.

I suppose I should mention that I'm running on Arch rather than SteamOS/Ubuntu, but I don't believe this would cause the issue; works fine 99% of the time.

**Comment by kisak-valve** [comment]
Hello @krompus, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1518. Closing as a duplicate.

**Comment by krompus** [comment]
@kisak-valve ah, I wasn't aware; thank you!
