### ISSUE TITLE
Installing Steam fills up entire SSD. Seemingly no file to blame. Fixed after uninstalling and leaving computer off overnight.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5213]
#### Your system information

* Steam client version (build number or date): 21st October 2017
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed Steam at around 8pm on the 21st. Installation went smoothly. I run the program and it brings up a popup saying 32-bit libraries are missing. I click OK to close it and go to my package manager to install the missing dependencies (which I would have expected it to do when installing it in the first place). Whilst I'm going to do that, Steam opens as if there was no error. I log in and Steam opens. I turn off a lot of the community and overlay settings, then close it. When I open it again, I get the same errors, and I get to the logon screen again as if this was the first time I ran it. I close it again and try installing some of the 32-bit libraries, so which it says there is no available disk space. I have a 240GB SSD that, at 8pm, had 136GiB of free space. I check my storage and it says it is completely full to the brim: 0B free.

I uninstall Steam and reboot my PC and it can't even open sddm. I login from a TTY and run startx, but it says it cannot launch because there are no available system resources, so I'm now stuck in a TTY with a full SSD and have to try and find what Steam has done to my SSD and delete it. After about an hour of investigating, I decide to leave it for the next day and turn off my PC, then turn off the PSU too as I normally do.

When I boot up the following morning, sddm launches and I can log in. Whatever it was that was eating up 136GiB of space was now gone and I had all that space free again.

#### Steps for reproducing this issue:

1. Install Steam
2. Run Steam
3. Close Steam
4. Run Steam again
5. Close Steam again
6. Try (and fail) to install a package
7. Discover SSD is now completely full

**Comment by kisak-valve** [comment]
Hello @0TheB, this sounds like something was writing to a log file until there was no space free, and the log was in a tmp folder that got purged like normal on reboot.

**Comment by 0TheB** [comment]
Possibly, but could a log file *really* take up 136GiB? One line of text in a text file is under 100B, so a 136GiB would need to have well over 1000 million lines, which seems rather suspicious for just installing a single program.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
