### ISSUE TITLE
Can't Right-Click on Steam Tray Icon

### ISSUE THREAD

**Issue by SolarLune** [ValveSoftware/steam-for-linux#5215]
#### Your system information

* Steam client version (build number or date): Oct. 19 2017
* Distribution (e.g. Ubuntu): Linux Mint 18.2, KDE Plasma Version 5.8.7
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I expected to be able to right-click on the tray icon to bring up the Steam menu. I can't, though, which means I can't access Steam after I initially close it after starting it up. When running Steam from the terminal, this is the response on right-clicking:

```
(steam:22288): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
```

I'm also getting these errors a lot in the terminal:

```
process 22288: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2686.
This is normally a bug in some application using the D-Bus library.
process 22288: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
process 22288: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
process 22288: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2686.
```

#### Steps for reproducing this issue:

1. Right click on the tray icon. It doesn't respond.

EDIT: This seems to be the same bug as #4795, but that issue is closed, so maybe this one could be closed and that one re-opened, since there's more information there.

**Comment by kisak-valve** [comment]
Hello @SolarLune, what files are in the pinned_libs_* folders that are found in the steam runtime folder (should be something like ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_*). If you close steam, move those folders out of the way, then restart steam, does the steam tray behave?

**Comment by SolarLune** [comment]
Yep, that seems to have done it. 

There were two folders, `pinned_libs_32` and `pinned_libs_64`, in the folder you mentioned, (which is `~/.local/share/Steam/ubuntu12_32/steam-runtime`). They can also be reached through the symlinked `steam` directory, which would be `~/.steam/steam/ubuntu12_32/steam-runtime`. Moving those folders aside fixed the issue for me, and the menu now appears correctly.

Thanks!
