### ISSUE TITLE
Strange segmentation fault at line line 713

### ISSUE THREAD

**Issue by lassade** [ValveSoftware/steam-for-linux#5216]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.54-10.fc26.src.rpm from rpmfusion-nonfree
* Distribution (e.g. Ubuntu): Fedora 26, Kernel 4.13 64bits, proprietary Nvidea drivers
* Opted into Steam client beta?: [Yes/No] Not sure about that
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

1. I installed steam by runing `# dnf install steam`
2. Then run steam from start menu (from terminal nothing changes)
3. The accept terms of conditions appear, I hit Yes
4. Segmentation Fault, full message:
```
Repairing installation, linking /home/lassade/.steam/steam to /home/lassade/.local/share/Steam
Running Steam on fedora 26 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/lassade/.local/share/Steam/steam.sh: line 713:  2308 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
/home/lassade/.local/share/Steam/steam.sh: line 444: no match: ssfn*
```
I tried a few different forums and even an issue very similar to this one in this git repo. But the thing is none of them seem like is the same kind of error because I only get this tiny log, that does not help much in track down the problem.

Any ideas how to proceed?

**Comment by kisak-valve** [comment]
Hello @lassade, can you check if any 32 bit opengl application works?

**Comment by lassade** [comment]
Blender works fine, I also used glfw3 and gl3w in one of my programs no problem.

**Comment by lassade** [comment]
Yea maybe there is a problem with 32 bit opengl just tried Godot Engine 32bit gives segmentation fault, backtrace is almost the same as steam.
Steam's backtrace:
```
#0  0x00000000 in ?? ()
#1  0xf7c58dde in __pthread_once_slow () from /lib/libpthread.so.0
#2  0xf7281568 in ?? () from /lib/libGLX_nvidia.so.0
#3  0xf724966c in ?? () from /lib/libGLX_nvidia.so.0
#4  0xf7fe6400 in _dl_init () from /lib/ld-linux.so.2
#5  0xf7feb142 in dl_open_worker () from /lib/ld-linux.so.2
#6  0xf7bd3405 in _dl_catch_error () from /lib/libc.so.6
#7  0xf7fea539 in _dl_open () from /lib/ld-linux.so.2
#8  0xf7dedc05 in dlopen_doit () from /lib/libdl.so.2
#9  0xf7bd3405 in _dl_catch_error () from /lib/libc.so.6
#10 0xf7dee38e in _dlerror_run () from /lib/libdl.so.2
#11 0xf7dedc8e in dlopen@@GLIBC_2.1 () from /lib/libdl.so.2
#12 0xf738d869 in __glXLookupVendorByName () from /lib/libGLX.so.0
#13 0xf738ebf8 in __glXLookupVendorByScreen () from /lib/libGLX.so.0
#14 0xf7387ee6 in glXChooseVisual () from /lib/libGLX.so.0
#15 0x565a0827 in ?? ()
#16 0x565a6203 in CBaseLinuxUpdateUI::BaseCreateWindow() ()
#17 0x565a70ee in CXWindowsUpdateUI::BCreateWindow() ()
#18 0x56577420 in ?? ()
#19 0xf7ab82c3 in __libc_start_main () from /lib/libc.so.6
#20 0x5657aae9 in _start ()
```

**Comment by Trophonix** [comment]
I am having the exact same problem as described here. Also on Fedora 26 with 384.90 nvidia proprietary drivers.

**Comment by lassade** [comment]
I was just about to update the nvidia driver, but I guess won't.
I'm pretty sure this is a problem with nvidia, Yesterday I got steam working in my notebook that have the same specs but don't have an nvidia card.

@Trophonix can you see if Godot Engine 32bit or any other 32bits application that uses opengl works in your system?

**Comment by lassade** [comment]
Any updates?

**Comment by kisak-valve** [comment]
In case it's not clear, steam requires a working 32 bit opengl driver, and this needs to be fixed on your system. If this is not easy to fix, then you should reach out to your distro's community for help with that.

**Comment by Trophonix** [comment]
Ahh, other 32bit opengl applications were also not working. For some reason I got the idea in my head that it wasn't that because I found someone with that issue and my error seemed to be different. I got some help with fixing the 32bit opengl, and it works now. Thanks!

**Comment by Trophonix** [comment]
In case someone saw that last message, I derped. I installed Windows Steam under wine as a test and after doing some opengl stuff I accidentally ran that, so I thought it was fixed. Heh... Anyway, 32 bit opengl applications do not work for me still. I'll keep following that line of thinking and see if I can find anyway to get it to work.

**Comment by lassade** [comment]
Hey every one, I managed to fix this issue.
I guess the frist time I installed the nvidia drivers I do not installed the 32-bit compatibility libs.
For anyone facing the same issue:
1. reboot at runlevel 3
2. rerun the nvidia install once again, and when it aks you to install the 32 libs hit yes

:)
