### ISSUE TITLE
Steam segfaults with BadWindow error

### ISSUE THREAD

**Issue by CherryMan** [ValveSoftware/steam-for-linux#5218]
#### Your system information

* Steam client version (build number or date): 62c554c
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

[crash log](https://pastebin.com/s5cEDDcC)

#### Steps for reproducing this issue:

1. Start the steam client

**Comment by kisak-valve** [comment]
Hello @CherryMan, can you check if any 32 bit opengl application works?

**Comment by CherryMan** [comment]
Driver is nvidia-384.90, and no this isn't a new install of steam, it always worked before.

I don't know of any 32-bit OpenGL software I could try running, I'll take any suggestions.

**Comment by kisak-valve** [comment]
You should be able to use glxinfo or glxgears, which should be in the i686 variant of mesa-demos.

Also, can you check if nvidia-libs-32bit matches the rest of the nvidia packages? nVidia's userspace version must match the running kernel module's version.

**Comment by CherryMan** [comment]
Ran glxgears, it indeed does give the same error as Steam. The package version for nvidia-libs-32bit is the same as the rest.

**Comment by kisak-valve** [comment]
So, that is telling you that 32 bit opengl on your system is broken and needs to be fixed.

**Comment by CherryMan** [comment]
Thanks for the help, issue's been fixed.
