### ISSUE TITLE
Steam Big Picture Mode sound interface segfault

### ISSUE THREAD

**Issue by krafczyk** [ValveSoftware/steam-for-linux#5219]
#### Your system information

* Steam client version (build number or date): ?
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've just run into a similar sort of problem as #4753, but the crash seems different enough that I've opted to open a new issue. None of the fixes discussed there seem to work for me.

As is described there, you simply have to open BPM, then click the settings button, then the menu item labeled 'interface' under 'Audio' and steam crashes for me.

Running from command line I get the error:

`~/.local/share/Steam/steam.sh: line 941: 27371 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"`

And running the dump through gdb I have this stacktrace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf4ee5c9b in ?? ()
   from /home/matthew/.local/share/Steam/ubuntu12_32/libaudio.so
```

#### Steps for reproducing this issue:

1. Launch Steam Big Picture Mode
2. Select Settings Button
3. Select the 'Interface' menu item under the 'Audio' category

**Comment by kisak-valve** [comment]
Hello @krafczyk, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, please include any CrashIDs or minidumps related to this issue.

Are you running audio middleware like pulseaudio? if you are, have you customized the config for it?

**Comment by krafczyk** [comment]
Sorry about that, I forgot to produce the system information.
System Information: https://gist.github.com/krafczyk/a39ea0bcb36ae0b1237fe5cd9926a4ec
I've not been able to find any CrashIDs or minidumps. (I have a coredumpctl managed dump file, but it's a .lz file.)

In fact, I am running pulse audio in addition to JACK.

My pulseaudio configuration is:
```
load-module module-native-protocol-unix
load-module module-jack-sink channels=6
load-module module-jack-source channels=2
load-module module-null-sink
load-module module-stream-restore
load-module module-rescue-streams
load-module module-always-sink
load-module module-suspend-on-idle
set-default-sink jack_out
set-default-source jack_in
```

I have also customized ALSA to accommodate JACK as well.

```
pcm.!default {
    type plug
    slave { pcm "jack" }
}

pcm.jack {
    type jack
    playback_ports {
        0 system:playback_1
        1 system:playback_2
        2 system:playback_3
        3 system:playback_4
        4 system:playback_5
        5 system:playback_6
    }
    capture_ports {
        0 system:capture_1
        1 system:capture_2
    }
}

ctl.mixer0 {
    type hw
    card 0
}
```

This way both Pulse and ALSA applications should connect to JACK by default.

Is this config causing these problems?

**Comment by kisak-valve** [comment]
Jack type pcm is flaky on the best of days, and has never been reliable for me, but that's just my personal experience. On the system I use jack with, I found that using an dmix into an alsa loopback device, then bridging it into jack was the least hassle solution for alsa-only applications.

Minidumps by steam and steam apps are commonly found in /tmp/dumps.

**Comment by kisak-valve** [comment]
Hello @krafczyk, are you still experiencing this issue on an up to date system?

**Comment by krafczyk** [comment]
I've managed to move away from Jack to a pulse-audio only system for the time being. I haven't had this issue in a while.

**Comment by krafczyk** [comment]
I guess I can close it.

**Comment by mathew2214** [comment]
i am still having the issue that steam segfaults when i enter big picture mode. 
system info: https://gist.github.com/mathew2214/36dc386767011550657c96262eade22c

steam generated a dmp file during the segfault, somehow. 
this dmp file is linked here: https://drive.google.com/file/d/1XgSXMhl3nbafX4_NkTSXVXyTOqd4sYAy/view?usp=sharing
sorry for the gdrive link, for some reason, github wont allow me to attach a .dmp
