### ISSUE TITLE
Fullscreen window has blank gap after restoring [Steam big picture/Dota]

### ISSUE THREAD

**Issue by Parduk** [ValveSoftware/steam-for-linux#5221]
* Steam client version 
Built: Oct 24 2017
Steam API:v017
Steam package versions: 1508910373
* Ubuntu 17.10 x86_64 Gnome 3.26 Kernel 4.13
![2017-10-28 18-43-50 ekran goruntusu](https://user-images.githubusercontent.com/19241802/32135993-93251f68-bc10-11e7-8e96-0bd8ccc292da.png)

Steps for reproducing this issue:
1. Minimize big picture 
2. Maximize with alt+tab

Dota have same issue
https://github.com/ValveSoftware/Dota-2/issues/985

**Comment by kisak-valve** [comment]
Possibly related to https://github.com/ValveSoftware/csgo-osx-linux/issues/1498#issuecomment-337974036.

**Comment by MaikuMori** [comment]
Workaround is to use active corner and switch window there. This will fix the blank space.

ALT+TAB indeed produces the same result on my machine running ArchLinux + Gnome 3.26.2.

**Comment by kisak-valve** [comment]
Hello @Parduk, @MaikuMori, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by crystaldaking** [comment]
this problem is relevant. Ubuntu 22.04
