### ISSUE TITLE
"No user logon"

### ISSUE THREAD

**Issue by dale032** [ValveSoftware/steam-for-linux#5223]
#### Your system information

* Steam client version (build number or date): **Steam package versions**: 1508910373 (date: 24.10.2017.)
* Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
First of all I play only Counter-Strike: Global Offensive and here is the issue:
If I play more than 30 minutes in every start of a round I get error for no internet connection (checked this, internet is okay) but then when I reconnect somehow after few seconds I get kicked from match and error is: "No user logon". After that I restart the game but error is same. Ofcourse I can chat in steam, I am normally logged in. Only when I restart steam everything is okay for another 30 minutse approx.

**Comment by kisak-valve** [comment]
Hello @dale032, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1518. Closing as a duplicate.
