### ISSUE TITLE
Automatic login does not works

### ISSUE THREAD

**Issue by Valkeru** [ValveSoftware/steam-for-linux#5224]
#### Your system information

* Steam client version (build number or date): 1508910373
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] — No
* Have you checked for system updates?: [Yes/No] — Yes

#### Please describe your issue in as much detail as possible:
Expected behavior: after launching of Steam client it automatically logging in my account. Interface of Steam client and Steam store is Russian.
Actual behavior: I log in to my account manually every time with entering of my login and password, if system was rebooted after last launch. "Save password" checkbox switches on every time. At the first launch after reboot I see all information in Steam Store on English (should be Russian), but client interface still Russian. At the next launch interface language switches to English.

#### Steps for reproducing this issue:

1. Close Steam client
2. Reboot system
3. Launch Steam

**Comment by kisak-valve** [comment]
Hello @Valkeru, this issue is already being tracked at #5030 and #5035. Closing as a duplicate.
