### ISSUE TITLE
No right padding on game info

### ISSUE THREAD

**Issue by williamvds** [ValveSoftware/steam-for-linux#5226]
#### Your system information

* Steam client version (date): Oct 27 2017 
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
There is no padding on the right side of the box displaying play time and last played date.

This issue only occurs on games unavailable for the current platform.

See the screenshot:
![Screenshot showing lack of right padding](https://user-images.githubusercontent.com/26379999/32186377-d5e36bcc-bd99-11e7-9a4c-5e5146d68820.png)

#### Steps for reproducing this issue:

1. Use default Steam skin
2. Navigate to game library 
3. Select detail view
4. Select a game that is not available for the current (ie GNU/Linux) platform

**Comment by kisak-valve** [comment]
Hello @williamvds, Steam's Library interface has been overhauled since this issue was last commented on.

If you're still experiencing this issue, it'll need a new investigation. Closing as outdated.
