### ISSUE TITLE
Can't get gamepad rumble to work with steam

### ISSUE THREAD

**Issue by Gfurst** [ValveSoftware/steam-for-linux#5227]
#### Your system information

* Steam client 24/10/2017
* Distribution: Archlinux
* Opted into Steam client beta?: nope
* Have you checked for system updates?: yep

#### Please describe your issue in as much detail as possible:
I can't get rumble to work with steam or any of its games, the gamepad in question being a generic dualshock (named Microntek). It is known to work with other games though. 

The gamepad has been configured on steam big picture, and works nearly perfectly otherwise (with the exception of maybe over sensitivity). I've tested with other game in the past, but right now I was trying with Tomb Raider 2013.

**Comment by kisak-valve** [comment]
Hello @Gfurst, per "Added support for rumble pass-through for virtual controllers. This fixes missing rumble support for any controllers opted into Steam Input, and rumble emulation support for the Steam controller." in the [2019-05-22](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1612764629382440848) Steam client beta update, please opt into Steam's beta client and retest this issue.
