### ISSUE TITLE
Steam can't remember my username/password

### ISSUE THREAD

**Issue by NoIE** [ValveSoftware/steam-for-linux#5228]
#### Your system information

* Steam client version (build number or date): 1509425745 Oct 30 2017
* Distribution (e.g. Ubuntu):  Ubuntu 17.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Can not save username/password, although "Remember my password" is checked.
2. I removed folder "Steam" and ".steam", but the problem is still.
3.

**Comment by kisak-valve** [comment]
Hello @NoIE, is the username also not remembered?

**Comment by NoIE** [comment]
Hello @kisak-valve. No, username also not remembered.

**Comment by kisak-valve** [comment]
Thanks for checking. This issue is already being tracked at #5030. Closing in favor of the existing issue report.
