### ISSUE TITLE
Steam client resets language preferences on startup and it doesn't remember login data

### ISSUE THREAD

**Issue by rob93c** [ValveSoftware/steam-for-linux#5229]
#### Your system information

* Steam client version (build number or date): 1509425745
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
I'm using Steam on Ubuntu 17.10 (freshly installed) with the Italian language (both the OS and the client). Sometimes (not always) when I open Steam, it loads in English even if I didn't change settings and every now and then when I open it, it forces me to login (even if I always flag the checkbox to remember my data).
This happens to me both on Ubuntu 17.10 and Kubuntu 17.04

#### Steps for reproducing this issue:

1. Launch Steam
2. It will sometimes force you to login and resets language preferences

**Comment by kisak-valve** [comment]
Hello @rob93c, this issue is already being tracked at #5030 and #5035. Closing as a duplicate.

**Comment by rob93c** [comment]
Oh damn, my bad.
