### ISSUE TITLE
steam dont start after update

### ISSUE THREAD

**Issue by pearlydragon** [ValveSoftware/steam-for-linux#5230]
#### Your system information

* Steam client version (build number or date): 1509425745
* Distribution (e.g. Ubuntu): Opensuse 13.2, kernel 3.16.7-53-desktop
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After any update, steam dont run without "env STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0", any updates later steam dont run fully. Window with "Connecting to account" and stuck, as any updates ago, without "env STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0". I cant run steam, and play(

#### Steps for reproducing this issue:

1. Open konsole, write env STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 /usr/bin/steam %U
2. Enter
3. see:
"/home/defender/.local/share/Steam/steam.sh: line 138: DISTRIB_ID: unbound variable
/home/defender/.local/share/Steam/steam.sh: line 152: DISTRIB_RELEASE: unbound variable
/home/defender/.local/share/Steam/steam.sh: line 138: DISTRIB_ID: unbound variable
/home/defender/.local/share/Steam/steam.sh: line 152: DISTRIB_RELEASE: unbound variable
Running Steam on   64-bit
/home/defender/.local/share/Steam/steam.sh: line 138: DISTRIB_ID: unbound variable
/home/defender/.local/share/Steam/steam.sh: line 152: DISTRIB_RELEASE: unbound variable
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
/home/defender/.local/share/Steam/steam.sh: line 269: no match:         libpostfix-master.so.1 -> libpostfix-master.so.1.0.1.*}so
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
(steam:29322): GLib-CRITICAL **: PCRE library is compiled without UTF8 properties support
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_regex_match_full: assertion 'regex != NULL' failed
(steam:29322): GLib-CRITICAL **: g_match_info_get_match_count: assertion 'match_info' failed
(steam:29322): GLib-CRITICAL **: g_regex_unref: assertion 'regex != NULL' failed
Installing breakpad exception handler for appid(steam)/version(1509425745)
../vgui_surfacelib/FontManager.cpp (290) : Assertion Failed: descs.Count() >= 1
Assert( Assertion Failed: descs.Count() >= 1 ):../vgui_surfacelib/FontManager.cpp:290

Installing breakpad exception handler for appid(steam)/version(1509425745)
assert_20171104130437_6.dmp[29364]: Uploading dump (out-of-process)
/tmp/dumps/assert_20171104130437_6.dmp
../vgui_surfacelib/FontManager.cpp (290) : Assertion Failed: descs.Count() >= 1
../vgui_surfacelib/FontManager.cpp (290) : Assertion Failed: descs.Count() >= 1
../vgui_surfacelib/FontManager.cpp (290) : Assertion Failed: descs.Count() >= 1
Installing breakpad exception handler for appid(steam)/version(1509425745)
[1104/130438.940936:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
assert_20171104130437_6.dmp[29364]: Finished uploading minidump (out-of-process): success = yes
assert_20171104130437_6.dmp[29364]: response: CrashID=bp-ee6c62b2-f66f-4c06-ac06-2db492171103
assert_20171104130437_6.dmp[29364]: file ''/tmp/dumps/assert_20171104130437_6.dmp'', upload yes: ''CrashID=bp-ee6c62b2-f66f-4c06-ac06-2db492171103''
[1104/130439.941952:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
[1104/130440.942933:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
[1104/130441.943736:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
[1104/130442.945055:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442.37 KB
Assert( Assertion Failed: !bSharedKVSymbols ):appdatacache.cpp:2104

crash_20171104130451_17.dmp[29431]: Uploading dump (out-of-process)
/tmp/dumps/crash_20171104130451_17.dmp
crash_20171104130451_17.dmp[29431]: Finished uploading minidump (out-of-process): success = yes
crash_20171104130451_17.dmp[29431]: response: CrashID=bp-b5d72089-08c8-4e36-81d9-68a082171103
crash_20171104130451_17.dmp[29431]: file ''/tmp/dumps/crash_20171104130451_17.dmp'', upload yes: ''CrashID=bp-b5d72089-08c8-4e36-81d9-68a082171103''
^C"

**Comment by kisak-valve** [comment]
Hello @pearlydragon, since `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` helps, this hints that there is one or more system libraries which are incompatible with steam. You should also bring this to the attention of your package maintainer for steam, but it's not likely this situation will improve because OpenSUSE Leap 13.2 has been discontinued.

**Comment by kisak-valve** [comment]
On further reflection, I'm going to close this issue because it's a distro-specific compatibility issue and support for OpenSUSE 13.2 has ended by the distro.
