### ISSUE TITLE
Controller Light Brightness works ON/OFF only

### ISSUE THREAD

**Issue by cprn** [ValveSoftware/steam-for-linux#5231]
#### Your system information

* Steam client version (build number or date): Oct 30 2017, at 19:09:46 (1509425745)
* Distribution (e.g. Ubuntu): Manjaro.i3 64bit (4.11.12-1-rt16-MANJARO)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I'm trying to dim the Steam Controller's LED light but the setting doesn't save. I don't know when it stopped working, my LED was dimmed for a **long** time but I wanted to dim it some more and it broke.

Expected behaviour: setting saved, LED light dimmed
Actual behaviour: anything below `1.0` is mapped to `0.0`, LED light goes off on Submit

I don't know how to debug this. :(

Controller Firmware Version: 1472158736
Receiver Firmware Version: 1444168478
Steam Runtime Version:  steam-runtime-beta-release_2017-07-24

#### Steps for reproducing this issue:

1. In Big Picture go to `Controller Settings > (detected controller) -> Preferences`
1. set `Controller Light Brightness` to `0.5` (half way)
1. submit the setting - it'll get "zeroed" and the LED is OFF now
1. set it to full bar, i.e. `1.0`
1. submit the setting - it'll stay at full and the LED is ON again

**Comment by whitemarvin** [comment]
I'm experiencing the same issue in Ubuntu 16.04. I've also noticed that Haptics Preference sometimes resets to default.

> Computer Information:
>     Manufacturer:  Unknown
>     Model:  Unknown
>     Form Factor: Desktop
>     No Touch Input Detected
> 
> Processor Information:
>     CPU Vendor:  GenuineIntel
>     CPU Brand:  Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
>     CPU Family:  0x6
>     CPU Model:  0x25
>     CPU Stepping:  0x5
>     CPU Type:  0x0
>     Speed:  3679 Mhz
>     4 logical processors
>     2 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
>     AES:  Unsupported
>     AVX:  Unsupported
>     CMPXCHG16B:  Supported
>     LAHF/SAHF:  Supported
>     PrefetchW:  Unsupported
> 
> Operating System Version:
>     Ubuntu 16.04.3 LTS (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.4.0-98-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11804000
>     X Window Manager:  Compiz
>     Steam Runtime Version:  steam-runtime-beta-release_2017-07-24
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GTX 750/PCIe/SSE2
>     Driver Version:  4.5.0 NVIDIA 384.90
>     OpenGL Version: 4.5
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     VendorID:  0x10de
>     DeviceID:  0x1381
>     Revision Not Detected
>     Number of Monitors:  1
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 1920 x 1080
>     Primary Display Size: 18,78" x 10,55" (21,54" diag)
>                                             47,7cm x 26,8cm (54,7cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 1024 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Realtek ALC887-VD
> 
> Memory:
>     RAM:  7910 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Total Hard Disk Space Available:  125863 Mb
>     Largest Free Hard Disk Block:  22537 Mb
>     VR Headset: None detected
> 
> Recent Failure Reports:
> 
>

**Comment by kisak-valve** [comment]
Hello @cprn, @whitemarvin, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
@whitemarvin, can you confirm the udev rule for the steam controller is behaving? (https://github.com/ValveSoftware/steam-devices/blob/master/steam_input.rules)

**Comment by whitemarvin** [comment]
@kisak-valve Can you elaborate? How do I do that?

**Comment by cprn** [comment]
I have the udev rules file installed via package on Manjaro. I guess it
works? What would happen if it wasn't?

Last time I was using the controller I tried to change the light again,
same behaviour. It was a week ago, though (Saturday). I don't know if there
was an update.

Is this somehow related to sound settings (volumes) reseting to zero each
time I run Big Picture? I never connected the dots but since whitemarvin
mentioned haptics settings reseting as well, maybe this issue is more
general?

**Comment by kisak-valve** [comment]
This may be the same issue as #4519, what's the output of `locale` and does completely closing steam, then running `LC_ALL=C steam` from a terminal change the behavior? (from https://github.com/ValveSoftware/steam-for-linux/issues/4519#issuecomment-280881585)

**Comment by cprn** [comment]
You're absolutely right and setting decimal separator to dot solves the issue. Closing as it's an exact duplicate of #4519.

**Comment by whitemarvin** [comment]
@kisak-valve Starting Steam with `LC_ALL=C steam` fixes the brightness issue, but Haptics Preference still resets to default like I described previously.

Here's the `locale` output:

> LANG=en_US.UTF-8
> LANGUAGE=en
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=ro_RO.UTF-8
> LC_TIME=ro_RO.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY=ro_RO.UTF-8
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER=ro_RO.UTF-8
> LC_NAME=ro_RO.UTF-8
> LC_ADDRESS=ro_RO.UTF-8
> LC_TELEPHONE=ro_RO.UTF-8
> LC_MEASUREMENT=ro_RO.UTF-8
> LC_IDENTIFICATION=ro_RO.UTF-8
> LC_ALL=
