### ISSUE TITLE
Latest Steam client beta incompatible with current NixOS package

### ISSUE THREAD

**Issue by yegortimoshenko** [ValveSoftware/steam-for-linux#5233]
The latest Steam client beta update can't find 32-bit libraries and fails to load `steamui.so`.
See https://github.com/NixOS/nixpkgs/issues/31384.

#### Your system information

* Steam client version (build number or date): latest beta
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

**Comment by kisak-valve** [comment]
Hello @yegortimoshenko, steam does not expect be denied write access to its own folder and the steam runtime has changed in the 2017-11-07 steam beta client update.

The line of interest is "/home/chronos/.local/share/Steam/steam.sh: line 874: /steamrt/run.sh: No such file or directory" in the terminal spew, and this will need to be resolved by the NixOS package maintainer for steam.

**Comment by yegortimoshenko** [comment]
Just so that you know, it's broken for Solus users as well: https://github.com/solus-project/linux-steam-integration/issues/29

**Comment by ikeydoherty** [comment]
This is unrelated to Solus, @yegortimoshenko - Solus users only need to install `libva-32bit` for the Steam beta to work, something we've already resolved in our unstable repo. Please let's not say stuff is broken when it is not.

**Comment by yegortimoshenko** [comment]
@ikeydoherty Well, I am no Solus user, but if package doesn't fetch all its dependencies, it's broken. Good to know you've fixed that in unstable, but it probably should make its way into release as well.

**Comment by ikeydoherty** [comment]
@yegortimoshenko alright man - so first you're making assumptions about the state of something and now you're telling me how to do my release cycle. Please, only do this if informed. Our sync window is Friday, and is fixed on a Friday every week. The Steam package update will be available to all Solus users then.

If the need arises we can sync before then (we cannot guesstimate the balance of stable to beta users).

**Comment by Dynamic-Gravity** [comment]
@yegortimoshenko on Solus, installing the `libva-32bit libvdpau-32bit` packages resolves the problem. So turns out this isnt related to Solus, just that steam needed need dependencies. I guess search for those packages with your package manager?

**Comment by kisak-valve** [comment]
Closing per https://github.com/NixOS/nixpkgs/commit/459e4b78db754872dfbd741e9f136d8998ffcaff.
