### ISSUE TITLE
VPLTD ports stopped working

### ISSUE THREAD

**Issue by ardje** [ValveSoftware/steam-for-linux#5235]
#### Your system information

* Steam version: 1510099762
* Distribution (e.g. Ubuntu): steamos (steam machine), ubuntu 17.10 (gpd win)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hi guys,
since above mentioned steam version, the ports of vpltd have stopped working. Or rather exact: I have tested saints row 3 on the gpd win/ubuntu 17.10 that worked on the steam version before that, and after the update stopped working. I noticed that it stopped working too on the steam machine.
Starting the game pops up a message with: "Please make sure that the steam client is running and that you own the game on the logged in steam account"
The eon wrapper logs that "SteamAPI_Init() returns false"
This is the case with all the vpltd games I have tested: saintsrow 3, 4: gat out of hell, and witcher 2.

I will paste some more logs... first I need to submit and take over the ticket on a system that has good access to all machines :-).

**Comment by ardje** [comment]
Ok, so the /tmp/dumps/steam_stdout.txt says:

dlopen failed trying to load:
/home/steam/.local/share/Steam/ubuntu12_32/steamclient.sowith error:
libtier0_s.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; Sys_LoadModule failed to load: /home/steam/.local/share/Steam/ubuntu12_32/steamclient.so
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 128 (130 input number was)
OnFocusWindowChanged to game window type: AppID 301910
Controller 0 WASD + Weapon Wheel + Mouse uses xinput : true
Loaded Config for Local Selection Path for App ID 301910: /home/steam/.local/share/Steam/steamapps/workshop/content/241100/662814971/controller_configuration.vdf

**Comment by ardje** [comment]
Ok, digging some further... de libtier0_s.so is loaded:

gat out of hell at least has the right one open:

G.Main  19994 steam  mem       REG              254,0   223967 11142165 /home/steam/.local/share/Steam/ubuntu12_32/libtier0_s.so

Anyway: GooH 's eon.txt logs this (last 3 lines):
[thread 00000004][W][334]: eON_HeapSetInformation() - requested heap corruption termination, ignoring
[thread 00000004][W][348]: REGISTRY OPERATION: RegOpenKeyExW() returns ERROR_NOT_FOUND (subkey not found) key = HKEY_CURRENT_USER, 
[thread 00000004][W][862]: SteamWrap: SteamAPI_Init() returns false!

**Comment by ardje** [comment]
I've been trying some games, and it is not an "All vpltd": SaintsRow 4 works, however SaintsRow 4 Gat out of Hell, doesn't.
So the list for me currently is SR3, SR4GooH, witcher 2: ... 
Working: SR4, SR2, Overlord (vpltd ports), and anything non-vpltd so far.
The non-working all fail with Steamwrap: SteamAPI_INIT() failed though.
I will look some more into SR4 vs SR4GooH, as those should be almost the same.

**Comment by kisak-valve** [comment]
Hello @ardje, you should also bring this issue to the attention of a VP dev.

**Comment by ardje** [comment]
@kisak-valve : it's support ticket 608 at VP. I've asked to continue here to see what has changed.
More results: copying the SR4 libsteam_api.so to SR3 results in SR3 not being able to find it's savegames. I don't know how the SR4 savegames are called but I found savesr3... in the SR4 userdata folder.
SR3 was unable to find savegames or create new savegames.
After downgrade to steam stable and restoring the original libsteam_api.so, the game works fine, and the savegames are back.

**Comment by Plagman** [comment]
I'm looking into this; these games shipped with an old build of the Steamworks SDK from before it had official Linux support. Can you confirm the full list of affected titles? My current understanding is that it's:
 - Saints Row: The Third (55230)
 - Saints Row: Gat out of Hell (301910)
 - The Witcher 2: Assassins of Kings Enhanced Edition (20920)
 - Spec Ops: The Line (50300)
 - Bioshock: Infinite (8870)

**Comment by ardje** [comment]
@Plagman indeed, that's the list of failing games in my repo.
There is also list of working EON titles:
Dirt: showdown (201700), SR2 (9480), SR4 (206420, the game on which SR4GooH/301910 was based).
Ok, you hinted me at something, so I did something else:
```
steam@steamos:~/.steam/steam/steamapps/common$ md5sum */libsteam_api.so|sort
0ebacb34047691d5606c9eddac93583d  Planetary Annihilation Titans/libsteam_api.so
1cb11f69786a6c48fe85802ea7f92cf6  Imperium Galactica II/libsteam_api.so
2905a4e3fddac01cf4a98fced6e102ae  POSTAL1/libsteam_api.so
2905a4e3fddac01cf4a98fced6e102ae  Saints Row IV/libsteam_api.so
5708c3fb70db4e7911e78234ec2f9154  Circuits/libsteam_api.so
5708c3fb70db4e7911e78234ec2f9154  Kelvin/libsteam_api.so
5708c3fb70db4e7911e78234ec2f9154  Reversion/libsteam_api.so
5708c3fb70db4e7911e78234ec2f9154  Sid Meier's Civilization V/libsteam_api.so
5708c3fb70db4e7911e78234ec2f9154  star conflict/libsteam_api.so
5711d554a8bf152cb985bdecc8ffcfd9  Dying Light/libsteam_api.so
697ee139e25ceb0c68a85b5d19e4b774  Divinity Original Sin Enhanced Edition/libsteam_api.so
6fb2a9eb95fd3d981b638a5176ece66b  BioShock Infinite/libsteam_api.so
6fb2a9eb95fd3d981b638a5176ece66b  Saints Row the Third/libsteam_api.so
6fb2a9eb95fd3d981b638a5176ece66b  SpecOps_TheLine/libsteam_api.so
6fb2a9eb95fd3d981b638a5176ece66b  the witcher 2/libsteam_api.so
7d2f4534735247c8c4bf3cce86f6b9dc  Metro 2033 Redux/libsteam_api.so
7d2f4534735247c8c4bf3cce86f6b9dc  Metro Last Light Redux/libsteam_api.so
96d35757b77ee86a234b04e0eebc7a1d  Saints Row Gat out of Hell/libsteam_api.so
96d35757b77ee86a234b04e0eebc7a1d  SpaceChem/libsteam_api.so
9e6d3f1e9f0f07fe833be9a7763d5b74  Limbo/libsteam_api.so
9e6d3f1e9f0f07fe833be9a7763d5b74  thomaswasalone/libsteam_api.so
a2fc655874419dd9dbf65cbf2f306771  PAYDAY 2/libsteam_api.so
b23e07d1249410eb4cdeb656c8e3a0bb  Only If/libsteam_api.so
d1a853eeae8ccb8fe1291a056e22ba96  Sid Meier's Civilization Beyond Earth/libsteam_api.so
d520a3e75d0a3ec305d73700a11c38b7  Victor Vran/libsteam_api.so
ed61d1e36df64b7e68e6e0d3f4ffe000  DIDE/libsteam_api.so
ed61d1e36df64b7e68e6e0d3f4ffe000  DIRDE/libsteam_api.so
fa18c1cef6fb413f50f9d3215855d57a  Metro Last Light/libsteam_api.so
fa18c1cef6fb413f50f9d3215855d57a  Montague's Mount/libsteam_api.so
fa18c1cef6fb413f50f9d3215855d57a  Not The Robots/libsteam_api.so
fa18c1cef6fb413f50f9d3215855d57a  Shadowrun Dragonfall Director's Cut/libsteam_api.so
fa18c1cef6fb413f50f9d3215855d57a  Shadowrun Returns/libsteam_api.so
```
So all games I reported, except for Gat out of Hell, have the same libsteam_api.so .
However there is a non EON game that has the same libsteam_api.so (spacechem), and that one also doesn't start, but it just doesn't start. No Logs that I can see right away.
Spacechem is pretty dated, but the port to steamapi is less dated.
Unfortunately my disk is too small to cache all the games locally.
I've attached the /tmp/dumps/steam_stdout.txt with the continous error messages removed.
This is how SpaceChem dies (a mono app).
[dump.txt](https://github.com/ValveSoftware/steam-for-linux/files/1470609/dump.txt)

**Comment by kisak-valve** [comment]
Closing per "Work around a launch failure for certain titles that include outdated Steamworks redistributable libraries" in the [2017-11-14 steam beta client](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1461843851749212399).
