### ISSUE TITLE
Counter Strike: Globall Offensive bug after ubuntu update

### ISSUE THREAD

**Issue by Vecarius** [ValveSoftware/steam-for-linux#5241]
#### Your system information

* Steam client version (build number or date): idk
* Distribution (e.g. Ubuntu): 17.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

After I updated my system from ubuntu 17.04 to 17.10 my CS:GO crashed and I've got fps drops. Every time I run cs:go It shows a notification that cs:go doesn't respond but after few second it runs normally, but with fps drops. I share logs from console.

https://gist.github.com/Vecarius/f86c38b1017e81e61854779b8cc3291b

**Comment by kisak-valve** [comment]
Hello @Vecarius, let's track this issue in the CS:GO issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1552.
