### ISSUE TITLE
[Antergos] System Hard Lock by using steam overlay

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/steam-for-linux#5246]
#### Your system information
https://gist.github.com/admshao/d09240196acd9db68b2d374fabc5e8fb

* Steam client version (build number or date): 1510705471
* Distribution (e.g. Ubuntu): Antergos
* Opted into Steam client beta?: [Yes/No] Yes, Doesn't really matter
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
While on Dota 2(but happened in others games as well) Using Shift Tab to answers steam messages, open webpages, visit other player profiles eventually will result in steam overlay hangup locking the whole system. Audio still plays, num lock key doesn't change ON/OFF the light indicator in the keyboard. In generall just using steam overlay will eventually hang up the system.

#### Steps for reproducing this issue:

1. Visit some player profile;
2. Answer messages
3. Just use steam overlay

**Comment by kisak-valve** [comment]
Hello @admshao, this issue is already being tracked at #4933.

Some users have had some luck ssh'ing into the box and SIGSTOP, then SIGCONT'ing the frozen game as a workaround.

Closing as a duplicate.
