### ISSUE TITLE
[FR] add "-xinput -no-xinput2" into Chromium Embedded build config

### ISSUE THREAD

**Issue by Zenitur** [ValveSoftware/steam-for-linux#5247]
#### Your system information

* Steam client version (build number or date): last half-or-year releases
* Distribution (e.g. Ubuntu): SUSE 11
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I'm using very old Linux distribution named SLE 11. It's NOT popular cause by openSUSE Leap is out. There is X-Server 1.6 that doesn't support Xinput 2. It was planned to include Xi2 into X-Server 1.6, but it was hold until 1.7: https://www.phoronix.com/scan.php?page=news_item&px=Njg1Nw Finally, SLE11 released with X-Server 1.6 and Xi1, and RHEL6 (much more popular than SLE) released with X-Server 1.7 and Xi2.

Few months ago Steam stopped to work on my SLE11 with the error: "libcef.so: undefined symbol XIQueryVersion". Google says that this variable is added in Xi2.

The main features of Xi2 are multitouch and raw input. If it's not necessary for you, add "-xinput -no-xinput2" into your Chromium Embedded build config. Anyway, I'm the one on the planet who will benefit of them.

Or you can use Xi2 without breaking Xi1-only systems? Icculus did that in 2011 on his Humble bundle game ports. For example in BRAID. 

I send you VirtualBox HDD image with installed SLE 11. The link is below. So, if you want, you can test my case in the VM. Steam is already installed in this image and ready for testing. Admin pass: sourceengine2.

#### Steps for reproducing this issue:

1. Install VirtualBox
2. Download HDD image from cloud: [SLE_11_SP4.vdi.xz](https://yadi.sk/d/AxWNQd1W3Pmtso)
3. Try to reproduse this bug.

**Comment by kisak-valve** [comment]
Hello @Zenitur, from what I can tell, there is [no steam packaging](https://software.opensuse.org/package/steam) for OpenSUSE SLE 11, and xorg-server 1.5 is from 2008, about 4 years older than Steam's initial release, so this is unlikely to change, but we'll see if a Steam dev wants to take a look.

**Comment by Zenitur** [comment]
I know that there is no official support of SLES or openSUSE. I'd post this issue to ask: is Steam supporting multitouch in it's web browser? If no, I think there are no reasons to build Xi2 support. If yes, just close this issue.

It's easy to check multitouch working in Linux, just plug two USB mouses and spawn a second cursor. [Howto](https://www.linux.org.ru/forum/desktop/5688449?cid=5688514)

```
$ xinput list

⎡ Virtual core pointer id=2 [master pointer (3)]
⎜ ↳ Virtual core XTEST pointer id=4 [slave pointer (2)]
⎜ ↳ A4Tech PS/2+USB Mouse id=9 [slave pointer (2)]
⎜ ↳ FSPPS/2 Sentelic FingerSensingPad id=12 [slave pointer (2)]
⎣ Virtual core keyboard id=3 [master keyboard (2)]
↳ Virtual core XTEST keyboard id=5 [slave keyboard (3)]
↳ Power Button id=6 [slave keyboard (3)]
↳ Video Bus id=7 [slave keyboard (3)]
↳ Power Button id=8 [slave keyboard (3)]
↳ Sirius USB2.0 Camera id=10 [slave keyboard (3)]
↳ AT Translated Set 2 keyboard id=11 [slave keyboard (3)]

$ xinput create-master secmouse
$ xinput list

⎡ Virtual core pointer id=2 [master pointer (3)]
⎜ ↳ Virtual core XTEST pointer id=4 [slave pointer (2)]
⎜ ↳ A4Tech PS/2+USB Mouse id=9 [slave pointer (2)]
⎜ ↳ FSPPS/2 Sentelic FingerSensingPad id=12 [slave pointer (2)]
⎣ Virtual core keyboard id=3 [master keyboard (2)]
↳ Virtual core XTEST keyboard id=5 [slave keyboard (3)]
↳ Power Button id=6 [slave keyboard (3)]
↳ Video Bus id=7 [slave keyboard (3)]
↳ Power Button id=8 [slave keyboard (3)]
↳ Sirius USB2.0 Camera id=10 [slave keyboard (3)]
↳ AT Translated Set 2 keyboard id=11 [slave keyboard (3)]
⎡ secmouse pointer id=13 [master pointer (14)]
⎜ ↳ secmouse XTEST pointer id=15 [slave pointer (13)]
⎣ secmouse keyboard id=14 [master keyboard (13)]
↳ secmouse XTEST keyboard id=16 [slave keyboard (14)]

$ xinput reattach 9 "secmouse pointer"
```
Also I think there is a possibility to realize Xi2 without breaking an old Xi1 systems. Like it was made in SDL2. I have a games with Raw Input support working fine on my OS. So I'd prepared an VirtualBox image for a possible testing and debug.

**Comment by Zenitur** [comment]
I'd fixed my issue with the string from this page: https://github.com/solus-project/linux-steam-integration/issues/8

It's no libcef bug. Now Steam is working perfectly without browser. To make browser works, I need to upgrade libXi from 1.2 to 1.3.

**Comment by kisak-valve** [comment]
Closing per the last comment.
