### ISSUE TITLE
Displaying not correct

### ISSUE THREAD

**Issue by NexusByte** [ValveSoftware/steam-for-linux#5248]
Client Version: latest (updated yesterday, 16.11.2017)
Distribution: Ubuntu 17.10
Beta: No
Update System: Yes
Problem: When I start CSGO, the display isn't working correct: https://pbs.twimg.com/media/DOwe8Z8XUAAjbAc.jpg

**Comment by kisak-valve** [comment]
Hello @NexusByte, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1498. Closing as a duplicate.
