### ISSUE TITLE
 symbol lookup error: /usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds

### ISSUE THREAD

**Issue by milankragujevic** [ValveSoftware/steam-for-linux#5249]
#### Your system information

* Steam client version (build number or date): Not sure
* Distribution (e.g. Ubuntu): Kubuntu 17.10 64bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed Steam as a .deb by downloading from `store.steampowered.com`, and installing with the GUI package manager. When I try to launch it, either with `steam` or with the icon, I get the following error in Konsole:

```
milan@milans-Desktop:~$ steam
Repairing installation, linking /home/milan/.steam/steam to /home/milan/.local/share/Steam
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/milan/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
/home/milan/.local/share/Steam/steam.sh: line 444: no match: ssfn*
```

#### What is supposed to happen?
Steam should launch and allow me to login.

#### What happens instead?
Steam doesn't launch, shows error in terminal.

#### Steps for reproducing this issue:

1. Download steam.deb
2. Install with `sudo dpkg -i steam.deb`
3. Run with `steam`

**Comment by kisak-valve** [comment]
Hello @milankragujevic, this issue is already being tracked at #4816.

You should be able to run `LD_PRELOAD='/usr/$LIB/libstdc++.so.6' LIBGL_DRI3_DISABLE=1 steam` or the other workaround at https://github.com/ValveSoftware/steam-for-linux/issues/4816#issuecomment-339329851 to get steam to start for the first time, then the workaround should not be needed after that.

Closing as a duplicate.

**Comment by PaulSchulz** [comment]
Thanks. This fix worked for me.

**Comment by isnullxbh** [comment]
Thanks man!

**Comment by jcarolinares** [comment]
It worked, thank you!

**Comment by mathieujobin** [comment]
Thank you !

**Comment by polcats** [comment]
thank you so much! it worked

**Comment by ferryth** [comment]
thank you.

**Comment by nethunter007** [comment]
Awsome thank you"...

**Comment by Ub3rZ4cH** [comment]
I had the exact same issue, launched with 

> LD_PRELOAD='/usr/$LIB/libstdc++.so.6' LIBGL_DRI3_DISABLE=1 steam

And it works thanks.

**Comment by birdsong108** [comment]
This fixed the issue for me! Thank you so much. Centos7

**Comment by mitchellurgero** [comment]
Works in Linux Mint 19.

**Comment by itsvisher** [comment]
They have mentioned this issue over here on their Wiki: https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Symbol_lookup_error_using_DRI3

Hope this works.

**Comment by sdjdd** [comment]
It works in Ubuntu 18.04. thanks!

**Comment by xiximitho** [comment]
Thanks, it works in RHEL 7.5

**Comment by OndraZizka** [comment]
@kisak-valve Please is Valve going to fix this? It's not easy to figure out for normal users who just run it from UI. I had to try in console and look up the error.
The script could simply do the same on the first run.

**Comment by OndraZizka** [comment]
Anyway, what I get next is 
```
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by kisak-valve** [comment]
Hello @OndraZizka, the 1.0.0.56 steam package has improved behavior related to this issue and should be much harder to encounter this scenario. It's at the discretion of the distro's package maintainer(s) for Steam to pull in the newer package.

**Comment by OndraZizka** [comment]
@kisak-valve Thanks for the prompt reply on Saturday :)
I used the one from https://store.steampowered.com/about/
Although I had an old pre-installed one which could cause the issues.

**Comment by Rich43** [comment]
Mentioned fix works on Ubuntu
