### ISSUE TITLE
Steam settings reset

### ISSUE THREAD

**Issue by Qik000** [ValveSoftware/steam-for-linux#5252]
#### Linux Arch GNOME 3.26

* Steam client version (build number or date): 22.10.2017
* Distribution (e.g. Ubuntu): Arch x64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam doesnt remember my passoword and settings such as language

#### Steps for reproducing this issue:

1. Open steam

**Comment by kisak-valve** [comment]
Hello @Qik000, this issue is already being tracked at #5030 and #5035. Closing as a duplicate.
