### ISSUE TITLE
Steam for Linux doesn't warn on low battery

### ISSUE THREAD

**Issue by yegortimoshenko** [ValveSoftware/steam-for-linux#5253]
#### Your system information

* Steam client version (build number or date): latest release
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

On macOS Steam in-game overlay warns about low battery. This feature doesn't seem to be implemented in the Linux client. It's useful and could be implemented via UPower D-Bus API.

**Comment by kisak-valve** [comment]
Hello @yegortimoshenko, this issue is already being tracked at #3956. Closing as a duplicate.
