### ISSUE TITLE
Phantom Game Downloads

### ISSUE THREAD

**Issue by Prime624** [ValveSoftware/steam-for-linux#5255]
#### Your system information

* Steam client version (build number or date): November 25
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: Yes and No (Issue present on both)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
For about a month now, every time I open steam, around 10 or more games have updates in the downloads tab. However, most or all haven't recently been updated (according to the games' websites) and only a couple show as needing updates in the library tab. I am able to play the games with phantom updates without updating first, but the games with actual updates require me to update before playing. I launch Steam every few days, so having 10 updates every time doesn't make sense. The phantom updates are 0 kb in size. This issue originated on beta, but I disabled beta for a few launches/days and the problem persists. I have tried clearing the download cache, to no avail.
Many updates in downloads:
![Many updates](https://user-images.githubusercontent.com/5740967/33233291-7d35764e-d1c8-11e7-8fb9-0eb78add6288.png)
Only 3 updates shown in library:
![Only 3 updates shown in library](https://user-images.githubusercontent.com/5740967/33233293-7ecb87fa-d1c8-11e7-9255-79bb92f18954.png)

Unsure if it's related, but I am also getting logged out every day or two. I have reported this in the appropriate thread.

#### Steps for reproducing this issue:

1. Launch Steam.
2. Check downloads page.

**Comment by kisak-valve** [comment]
Hello @Prime624, what's the date of the steam beta client you tested? This may have already been fixed in the [2017-11-22 steam beta client](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1465222282557450252).

**Comment by Prime624** [comment]
That update's changelog looks promising. It started happening about a month ago. I switched to the non-beta a few days ago, likely before the 11-22 update, and only just switched back to the beta today. If it doesn't happen again in the next week, then the update must have fixed it.

**Comment by Prime624** [comment]
The 11/22 beta update appears to have fixed the issue.
