### ISSUE TITLE
[Fixed] Can't start Dota 2 - OpenGL 3.3 - Linux env 

### ISSUE THREAD

**Issue by Reckku** [ValveSoftware/steam-for-linux#5256]
#### My system information

* Steam client version (build number or date):  1509425745
* Distribution (e.g. Ubuntu): Ubuntu 14.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### The overview of my issue:
Basically my Steam can't start Dota 2 due to opengl 3.3 required entrypoints ![pick](https://user-images.githubusercontent.com/8358518/33234985-665e67bc-d238-11e7-9dcb-355de74f5da6.png) . I have dedicated graphics card intel HD 4000, and upon declared minimal system requirements HD 3000 is the least and mesa 10.6.

The output of:
glxinfo | grep "OpenGL version" is:
OpenGL version string: 3.0 Mesa 11.2.0

I've tried with and without VAAPI driver for intel but no luck. The full hardware enablement stack of Xenial is installed as well. 

Tell me if you need further information. And thank you in advance.

**Comment by Plagman** [comment]
It's possible requirements have changed in a way that requires newer Mesa for this adapter; thanks for the report.

**Comment by Reckku** [comment]
The thing is I was able to run it 2 weeks ago. And it happened months after I decided to abandon League of Legends for good.

**Comment by kisak-valve** [comment]
For what it's worth, Dota 2 starts fine a couple of my GL 3.3-capable test boxes (Ubuntu 16.04.3 / ATi Radeon 5450 / mesa 17.0.7 and Arch / nVidia GT 240 / 340.104).

**Comment by Reckku** [comment]
Well I know everything is working now and is stable... so. If you can tell me which package is responsible of opengl other then mesa i can download it and rebuild it. Because the core version is 3.2 and actual is 3.0. According to documentation mesa 11.2 has all the opengl 4.1.  

Reference: https://mesa3d.org/relnotes/11.2.0.html

**Comment by danginsburg** [comment]
@Reckku Could you please run with -con_logfile in your Launch Options and then post the contents of <steamdir>/steamapps/common/dota 2 beta/game/dota/console.log?

**Comment by danginsburg** [comment]
....or, did you figure out the issue?

**Comment by Plagman** [comment]
I'm guessing temporarily broken package symlinks then; maybe fallback to swrast/llvmpipe. Thanks for confirming!

**Comment by Reckku** [comment]
@danginsburg the game is working fine now, even though I didn't try to fix it myself - believe there was minor update. If you still with to see the log I will post it here.
<script src="https://pastebin.com/embed_js/uddSKHy1"></script>
