### ISSUE TITLE
Steam no longer loads on Ubuntu Trusty

### ISSUE THREAD

**Issue by madscientist159** [ValveSoftware/steam-for-linux#5258]
#### Your system information

* Steam client version (build number or date): 
Nov 22 2017 13:33:24
* Distribution (e.g. Ubuntu): 
Ubuntu Trusty
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

Steam no longer loads.  Attempting to start Steam results in an error about failing to load steamui.so, and the following message appears on the terminal:

/home/games/.local/share/Steam/ubuntu12_32/libavutil.so.55: undefined symbol: vaQuerySurfaceAttributes

**Comment by kisak-valve** [comment]
Hello @madscientist159, steam picked up a couple more dependencies in the beta client.

You should be able to run something like `sudo apt-get install libva1:i386 libvdpau1:i386` in a terminal to get these dependencies.

**Comment by kisak-valve** [comment]
Hello @madscientist159, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as out of date. If you encounter a similar issue, it'll need a new investigation.
