### ISSUE TITLE
Paid DLC wont install on Steam.

### ISSUE THREAD

**Issue by Portal-Fan** [ValveSoftware/steam-for-linux#5260]
#### Your system information

* Steam client version (build number or date): 
* Ubuntu 16.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [No]

#### Please describe your issue in as much detail as possible:
I bought both the game Dreadout and the soundtrack/manga DLC, but the DLC won't install and I got the DLC refunded so I could test the "Install Game" link after the purchase but nothing would happen.

#### Steps for reproducing this issue:

1. Purchased DreadOut
2. Purchased DreadOut DLC (Soundtrack and Manga)
3.

**Comment by kisak-valve** [comment]
Hello @Portal-Fan, there's insufficient info in this issue report to do anything. Closing as invalid.
