### ISSUE TITLE
Paid DLC wont install on Steam.

### ISSUE THREAD

**Issue by Portal-Fan** [ValveSoftware/steam-for-linux#5261]
* Build date, Oct. 30, 2017.
   * Ubuntu 16.04
   * No. I opted out of beta.
   * No. The system was up-to-date.

Please describe your issue in as much detail as possible:
I bought both the game Dreadout and the soundtrack/manga DLC, but the DLC won't install and I got the DLC refunded so I could test the "Install Game" link after the purchase but nothing would happen.

Steps for reproducing this issue:

1. Purchased DreadOut
2. Purchased DreadOut DLC (Soundtrack and Manga
3.

**Comment by kisak-valve** [comment]
This should also be brought to the attention of the game's devs.
