### ISSUE TITLE
Steam delets all games after every relaunch

### ISSUE THREAD

**Issue by MikaeelMF** [ValveSoftware/steam-for-linux#5262]
Steam client version (build number or date): October 30, 2017
Distribution (e.g. Ubuntu): Ubuntu 17.10
Opted into Steam client beta?: no
Have you checked for system updates?: yes

Every time I relaunch steam it isn’t logged into my account (I check remember my password every time before logging in) and all the games I had them install are gone and I have to install them again.

Steps to make this happen:
0)install steam and your games
1) close steam or restart laptop
2)open steam again

**Comment by kisak-valve** [comment]
Hello @MikaeelMF, are you still experiencing this issue on an up to date system?

**Comment by MikaeelMF** [comment]
Hi I've changed my OS so I don't know anymore

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
