### ISSUE TITLE
Steam does not support any libc different than GLIBC

### ISSUE THREAD

**Issue by Uramekus** [ValveSoftware/steam-for-linux#5263]
**Description:**
As said, steam does not support any libc different than glibc, this is bad because libcs like https://www.musl-libc.org/ are MIT licensed and could easily be statically linked on games and avoid licensing/legal problems, this actually adds a need to do a chroot on a musl-based system, which needs to include all of its glibc dependencies and counterparts inside the chroot.

**Comment by kisak-valve** [comment]
Hello @Uramekus, realistically this isn't going to happen because it would break compatibility with the video drivers on all major distros, and almost all native game builds already on Steam, which makes this request a non-starter.

**Comment by gghhkm** [comment]
@kisak-valve what do you mean by "break compatibility with the video drivers" ? Could give an example?.
