### ISSUE TITLE
Playing videoes fullscreen on store page.

### ISSUE THREAD

**Issue by PaddedGamer** [ValveSoftware/steam-for-linux#5266]
#### Your system information

* Steam client version (build number or date): 
Built: Nov 29 2017 at 14:05:08
Steam API: v017
Steam package versions: 1512000021
* Distribution (e.g. Ubuntu): Linux Mint 18.2 Sonya (64 bit) (Ubuntu Distro)
* Opted into Steam client beta?: [Yes/No] Yes (Bug also appears in the stable version.)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Attempting to load a review video from the steam page will cause the resolution to display incorrectly. This also happens while watching steam broadcasts. A better example is the following image down below. 
![fullscreen glitches](https://user-images.githubusercontent.com/6026744/33448954-354fb446-d5bc-11e7-9e68-0b589e7c1859.png)

I expected the fullscreen window to consume the entire screen space. And not just a fraction of it. 

#### Steps for reproducing this issue:

1. Click on any store page or watch a steam broadcast.
2. Enter fullscreen mode on a video.

**Comment by kisak-valve** [comment]
Hello @PaddedGamer, this issue is already being tracked at #3699. Closing as a duplicate.

**Comment by PaddedGamer** [comment]
Wow two years and still hasn't been fixed. 2015 is when that was posted. *claps* Amazing job Valve. You did well. I'm so proud.
