### ISSUE TITLE
Improve supported platform list

### ISSUE THREAD

**Issue by tleydxdy** [ValveSoftware/steam-for-linux#5267]
Add Linux icon to the supported platform list, current on is a bit confusing. 
![screenshot from 2017-11-30 14-32-40](https://user-images.githubusercontent.com/10610765/33451020-9b0d1796-d5db-11e7-9015-25323893ea81.png)

**Comment by kisak-valve** [comment]
Hello @tleydxdy, Linux support is indicated by the SteamOS icon. Closing in favor of the feature request at #4508.
