### ISSUE TITLE
After restarting pulseaudio, steam will crash when accessing steam settings

### ISSUE THREAD

**Issue by jomihaka** [ValveSoftware/steam-for-linux#5268]
#### Your system information

* Steam client version date: Oct 30 2017, at 19:09:46
* Distribution: Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Fiddling around in steam settings works as expected. However, if one kills pulseaudio server and restarts it, next time going to settings will crash steam.

#### Steps for reproducing this issue:

1. Start steam
2. Kill pulseaudio (pulseaudio -k) and restart it, if it doesn't automatically
3. Go to steam settings (Steam -> Settings)
4. Observe crash

**Comment by kisak-valve** [comment]
Hello @jomihaka, this is functionally the same issue as #1587. Closing as a duplicate.
