### ISSUE TITLE
PulseAudio problems.

### ISSUE THREAD

**Issue by pthfdr-42** [ValveSoftware/steam-for-linux#5271]
#### Your system information

* Steam client version (build number or date): 1509425745
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

After a recent update, Steam crashed.
When I remove all the files under ~/.steam/ and launch Steam,it works,but after exiting and restarting Steam, it crashed again.
OS is Debian Sid,with all updates applied.
PulseAudio is not installed on the PC but I installed "apulse" package to provide similar mechanisms.
[error.log](https://github.com/ValveSoftware/steam-for-linux/files/1529540/error.log)
[crash_20171205104152_1.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/1529545/crash_20171205104152_1.dmp.gz)

#### Steps for reproducing this issue:

1. Install Steam from Debian Repo.
2. Launch Steam,either from ksh or desktop shotcut
3. The first time Steam functions normally,after that Steam crashed without any error message.

**Comment by kisak-valve** [comment]
Hello @pthfdr-42, the minidump you attached is a SIGSEGV in libdbus-1.so.3.5.8, and is also involving libnm-glib.so.4.3.0 (part of networkmanager). Pulseaudio does not appear to be related.

Can you list the contents of `~/.steam/ubuntu12_32/pinned_libs_*`?

**Comment by pthfdr-42** [comment]
`pthfdr@EINHERJAR:/home/pthfdr% ls ~/.steam/ubuntu12_32/pinned_libs_*
ls: cannot access '/home/pthfdr/.steam/ubuntu12_32/pinned_libs_*': No such file or directory`
Here is the packages installed on my PC:
[1.txt](https://github.com/ValveSoftware/steam-for-linux/files/1530341/1.txt)

**Comment by pthfdr-42** [comment]
It turns out it is the problem with the propriety Nvidia driver.Changed my display card to an AMD one and using the open source driver solves the problem.
