### ISSUE TITLE
Unable to add a second Steam Library with the same name, but a different case as an existing library

### ISSUE THREAD

**Issue by janinko** [ValveSoftware/steam-for-linux#5274]
#### Your system information

* Steam client version (build number or date): Dec 5 2017, at 14:43:13
* Distribution (e.g. Ubuntu): Fedora 26
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Tried to create new Steam Library Folder. I had aleready on on drive mounted to /mnt/data at /mnt/data/Steam and tried to create new on on drive mounted to /mnt/Data (note the capital D) at /mnt/Data/Steam.
That failed with "New Steam library folder must be on a filesystem mounted with execute permissions" message.
In log there was:
```
sh: /mnt/Data/Steam//steamapps/.steam_exec_test.sh: Directory or file doesn't exists.
```
and really, there weren't any .steam_exec_test.sh script nor steamapps folder.
When I remounted the /mnt/Data drive as /mnt/DataD everything started to work.

1) The error message should probably be that the file .steam_exec_test.sh was not written, not that it couldn't be executed.
2) It should be possible to have steam directory in the almost same path which differs only in case of the letters.

**Comment by kisak-valve** [comment]
Hello @janinko, this issue is already being tracked at #1174. Closing as a duplicate.

**Comment by srosano** [comment]
Hello, 

For those who are using symlinked folder, that points to a automounted drive on Linux need to know that the order the fstab options has precedence so putting the exec option as the last option in your fstab will ensure that the mount correctly has execute permissions. 

Also chmod and chown the files with the necessary permissions recursively also helps, for good measure chmod -R +x  steam/ and that should work.
