### ISSUE TITLE
Steam Broadcasting is not currently supported on this system.

### ISSUE THREAD

**Issue by martmists** [ValveSoftware/steam-for-linux#5275]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-3 and 1.0.0.54-5 (both runtime and native have this issue)
* Distribution (e.g. Ubuntu): Arch 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I told a friend to watch me play factorio but said it reported my system to not support broadcasting. Steam > Settings > Broadcasting confirmed this, but with no explanation on how it can support it. Back when I used steam on Antergos it DID work, however.

#### Steps for reproducing this issue:

1. Ask someone to watch your game
2. Done

**Comment by kisak-valve** [comment]
Hello @martmists, as far as I'm aware, this is currently unimplemented with Steam for linux, marking as a feature request.

**Comment by ceLoFaN** [comment]
Hey @kisak-valve, is there any progress on this feature?
This FAQ makes this look like a planned feature, more than like a feature request: https://support.steampowered.com/kb_article.php?ref=6730-TOAK-6497#19

**Comment by Kabouik** [comment]
Would like to know about it too. I miss this feature, and using OBS as a replacement is really not the same in terms of performance.

**Comment by siebz0r** [comment]
It's been quite a while since this feature was requested (or 'promised'), I'd appreciate any update on this if that's possible.

**Comment by OvermindDL1** [comment]
Streaming is almost ridiculously easy from linux than it is from, say, Windows.  How is this not implemented?  If the client were open source then I'd PR support in...  >.>

_/me grumbles about broken closed source things_

**Comment by JaneSmith** [comment]
I've been waiting for this for a long time. It would be great to have, especially now that we have the shiny new Steam Play (Proton) and more attention on Linux gaming.

**Comment by Maks7878** [comment]
I too would also love to see this added feature given support in Linux. A few of my friends and I have been long awaiting this feature to be added. +1

**Comment by HunterGraubard** [comment]
Is this ever coming? It's been literally years. I find it very surprising considering Valve's strong support of Linux in general. Steam Broadcasting is an essential feature of Steam for me, as I always stream games to my partner when I play. Since I can't do this on the Linux client, I'm forced to play every single game on Windows instead.

**Comment by arlyoneel** [comment]
Is curious to me, because the linux client works flawessly with steam link in lan/internet and records screen as in other OSes, so I dont think this needs lot of effort to implement.

Yes as @HunterGraubard says, I miss the feature to show how I play to friends.

**Comment by alxpettit** [comment]
Valve -- if you don't want to write the code, open source it and we'll write it for you. Geesh. Bunch of lazies.

**Comment by arlyoneel** [comment]
Just curious, sorry to bother you @kisak-valve any news about this? and the asignee @triage-valve is still working in valve?

Thanks in advance

**Comment by ceLoFaN** [comment]
Unless they announce something like Steam Machines 2, I doubt it will be on their priority list (if they go by one).

**Comment by shigutso** [comment]
3 years ago I [started a thread](https://steamcommunity.com/groups/steambroadcasting/discussions/0/412448792359631878/) on Steam Broadcasting forum but got zero response from Valve. There was also an [interesting discussion on Reddit](https://www.reddit.com/r/linux_gaming/comments/4939ym/to_increase_linux_adoption_we_have_to_show_our/).

Hey, at least this time we got something! Let's have hope :)

**Comment by mmcnutt** [comment]
Also want to express interest in Steam Broadcasting from Linux. 

Given that in home streaming works, the gulf to implement broadcasting can't be insurmountable

**Comment by Termuellinator** [comment]
it's really remarkable that this still isn't implemented :/

**Comment by Protonator** [comment]
+1 for this feature request. The implementation would be one more reason less to boot Windows for certain games. And it would round off the Steam for Linux experience, showing Windows users that they don't have to give up particular features when they switch to Linux.

**Comment by FrankieEnc** [comment]
yeah, +1 to what everyone else said. should be easy?

**Comment by Sanaki** [comment]
Honestly, I'd just like an update. It -seems- like it should be essentially already complete, since both remote play together and in-home streaming work smoothly on linux. If there's something preventing broadcasting from being enabled, just knowing what it is would help.

**Comment by AdamFreemen** [comment]
Two weeks ago Broadcasting worked fine on Linux. What happend? And when it start working again?

**Comment by dsge** [comment]
> Two weeks ago Broadcasting worked fine on Linux.

It did? Are you sure?

**Comment by AdamFreemen** [comment]
> > Two weeks ago Broadcasting worked fine on Linux.
> 
> It did? Are you sure?

Yea. It worked fine about two weeks ago and erlier on my Linux Mint 19 LOVE Edition. But now Steam outputs the following message "Your web browser does not support the minimum set of features required to watch this broadcast".

**Comment by dsge** [comment]
> > > Two weeks ago Broadcasting worked fine on Linux.
> > 
> > 
> > It did? Are you sure?
> 
> Yea. It worked fine about two weeks ago and erlier on my Linux Mint 19 LOVE Edition. But now Steam outputs the following message "Your web browser does not support the minimum set of features required to watch this broadcast".

This issue is about allowing your steam friends **to watch your gameplay** using Steam Broadcasting.

**Comment by AdamFreemen** [comment]
I wrote to support about problem with Live Streams in Steam, and they gave me link on this thread.

![Steam - Ваш браузер не поддерживает минимальный набор функций](https://user-images.githubusercontent.com/53379708/67673684-3e379800-f9ad-11e9-8298-328bac4ba908.png)

**Comment by AdamFreemen** [comment]
Yesterday Live Streams starts working again, but broadcasting settings not active. What a ...?
![Live Stream in Steam - 2019-10-28 20-24](https://user-images.githubusercontent.com/53379708/67734375-7da8c780-fa33-11e9-8714-edc13dc3886e.gif)

**Comment by jatin-cbs** [comment]
Steam broadcasting not supported on linux. Ibus which is default in all distros the CJK input not supported as well. They just introduce steamplay coping DXVK but to be honest valve is just like the others.

**Comment by jatin-cbs** [comment]
I would say feral interactive is the only one which cares.

**Comment by Newbytee** [comment]
Broadcasting seems to work fine for me if I invite them to watch, however if they attempt to click "Watch game" while I'm not already streaming they get the "Steam Broadcasting is not currently supported on this system" message.

That aside, it seems to be working well. No audio though.

**Comment by madrang** [comment]
Last time i checked i had the message "Steam Broadcasting is not currently supported on this system".

This week somehow, after a few system updates now i can enable it, but i dont have the upload to test it properly.

![image](https://user-images.githubusercontent.com/747243/68814432-d177fb00-0646-11ea-86e2-096c86df003b.png)

**Comment by Sanaki** [comment]
Just gave it a quick test. The delay is high and the audio doesn't work, but it's more than we had. I'll poke at settings later and see if it can be made to work better.

**Comment by kisak-valve** [comment]
The follow up issue with the audio capture is being tracked at #6681.

Closing as implemented.

**Comment by jatin-cbs** [comment]
@kisak-valve this issue is not about audio.. When we try to send brodcast request it says its not supported on your system.. Atleast read the issue

**Comment by kisak-valve** [comment]
Hello @jatin-cbs, that follow up issue is being tracked at #6693.

**Comment by Sanaki** [comment]
I seem to be experiencing this issue again. I'm not sure when it changed.

**Comment by Newbytee** [comment]
> I seem to be experiencing this issue again. I'm not sure when it changed.

What isn't working exactly?

**Comment by Sanaki** [comment]
Anyone attempting to view my stream sees that my system doesn't support broadcasting. Same as before.

**Comment by Newbytee** [comment]
> Anyone attempting to view my stream sees that my system doesn't support broadcasting. Same as before.

That's tracked at #6693.

**Comment by kreezxil** [comment]
How hard is it to honestly implement this feature? Considering that Linux has no issue with watching videos and movies on the internet in other web browsers?

**Comment by JaneSmith** [comment]
I'm desperately hoping that this finally gets fixed soon. Surely people will want to use Steam Broadcasting with the new Steam Deck?

**Comment by LoveIsGrief** [comment]
I think the issue might even be that it's not possible to create an RTMP endpoint. There are instructions to broadcast manually: https://partner.steamgames.com/doc/store/broadcast/setting_up and they don't work 
![afbeelding](https://user-images.githubusercontent.com/2829538/149849014-5b0d267b-646a-49fb-81bf-450bcbf5e5c8.png)

**Comment by kreezxil** [comment]
odd, Youtube has an RTMP endoint, and OBS can connect to it just fine.

**Comment by LoveIsGrief** [comment]
Has anybody else tried manually setting up a stream according to the guide? Maybe there really is a problem and there's no access. Or it's just me and the error is elsewhere :shrug: 

Honestly though, I just use https://p2p.chat to stream low latency to my friends. OBS + virtual camera. Game audio is a little more fiddly
