### ISSUE TITLE
Fedora 27 + GTX 1080 TI

### ISSUE THREAD

**Issue by pmpbar** [ValveSoftware/steam-for-linux#5276]
#### Your system information

* Steam client version (build number or date): Can't check should be newest 
* Distribution (e.g. Ubuntu): fedora 27
* Opted into Steam client beta?: [Yes/*No*]
* Have you checked for system updates?: [*Yes*/No]

```
Running Steam on fedora 27 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/pmpbar/.local/share/Steam/steam.sh: line 713:  1143 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
/home/pmpbar/.local/share/Steam/steam.sh: line 444: no match: ssfn*
```
I am getting this error when I launch steam. I just installed the proprietary Nvidia drivers for the GTX 1080 TI.

**Comment by kisak-valve** [comment]
Hello @pmpbar, can you confirm you have a working 32 bit opengl driver stack?

A 32 bit build of glxinfo or glxgears should be sufficient to do a test.

**Comment by pmpbar** [comment]
`$ glxgears` works, is it 32 bit by default?

**Comment by kisak-valve** [comment]
Taking a look at Fedora's, it looks like the [i686](https://koji.fedoraproject.org/koji/rpminfo?rpmID=11891798) mesa-demos package provides glxinfo32 for this kind of troubleshooting. I'd expect glxgears is 64 bit on a 64 bit distro unless you've gone out of your way to grab a 32 bit build.

What I suspect is going on here is a package named something like nvidia-driver-libs.i686 is missing on your system. (from https://negativo17.org/nvidia-driver/)

**Comment by pmpbar** [comment]
Woohoo! That was the issue thank you so much!

`$ sudo dnf install nvidia-driver-libs.i686`

**Comment by jjpe** [comment]
I just ran into this issue, also using Fedora 27. Is this fixable using only RPMFusion?
Or do I really need the `negativo17` repo ?

**Comment by kisak-valve** [comment]
Hello @jjpe, that's just a reference for where I got the name of a 32 bit nVidia driver package. Perhaps you're looking for the i686 variant of [xorg-x11-drv-nvidia-libs](http://download1.rpmfusion.org/nonfree/fedora/releases/27/Everything/x86_64/os/repoview/xorg-x11-drv-nvidia-libs.html)?

**Comment by jjpe** [comment]
That depends. Will that conflict with the Nvidia drivers installed as a `.run` file (which I DL'ed from their website)?
If not, I can install it. Otherwise i'd need to undo that I suppose.

**Comment by kisak-valve** [comment]
You'll need to ask your community how that interaction works out in practice, but in general, it's bad to bypass the package manager with installers like that and nVidia's userspace library version must match the running kernel module's version.
