### ISSUE TITLE
Broken 32 bit libraries after updating steam

### ISSUE THREAD

**Issue by srihari-humbarwadi** [ValveSoftware/steam-for-linux#5280]
#### Your system information

* Steam client version (build number or date): dec 12 2017
* Distribution (e.g. Ubuntu): Ubuntu 16.04 with nvidia GTX 1060
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I was running steam in a docker container for a while now, (10 months or no) everything worked just fine, until the latest update to steam client, i received a 222,000 byte update after which i am not able to 
run steam, this is what the error says
Failed to load steamui.so - dlerror(): libva-x11.so.1: cannot open shared object file: No such file or directory 
and a pop up saying
Failed to Load steamui.so
pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Run steam in a docker container

**Comment by kisak-valve** [comment]
Hello @srihari-humbarwadi, the 2017-11-07 steam beta client added dependencies on the 32 bit variant of libva1 and libvdpau1. Please update your docker container accordingly, or if you grabbed the docker container from someone else, it should be brought to their attention.

**Comment by srihari-humbarwadi** [comment]
okay , so if i just update my image with libva1 and libvdpau1 it should work ?,
currently using Debian jessie as base image

**Comment by srihari-humbarwadi** [comment]
https://gist.github.com/srihari-humbarwadi/3833765f6c271346200cd62d6b5e5c6b
this is my dockerfile with all the deps listed, is there anything missing ?

**Comment by kisak-valve** [comment]
The 32 bit variants would be libva1:i386 and libvdpau1:i386.

**Comment by srihari-humbarwadi** [comment]
I added both of those, it still gives me the same error can't get it to work

**Comment by srihari-humbarwadi** [comment]
@kisak-valve got it working by adding the following libs
kisak-valve
