### ISSUE TITLE
 psychedelic colours in steam  with amdgpu-pro-17.40-492261

### ISSUE THREAD

**Issue by MasterCATZ** [ValveSoftware/steam-for-linux#5282]
#### Your system information

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD A10-5800K APU with Radeon(tm) HD Graphics  
    CPU Family:  0x15
    CPU Model:  0x10
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.6-041406-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon R9 200 Series
    Driver Version:  4.5.13496 Compatibility Profile Context
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67b1
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 3584 x 1024
    Primary Display Size: 14.80" x 11.85" (18.94" diag)
                                            37.6cm x 30.1cm (48.1cm diag)
    Primary VRAM: 4096 MB

Memory:
    RAM:  30165 Mb

* Opted into Steam client beta?: [Yes/No]
YES
* Have you checked for system updates?: [Yes/No]
YES

#### Please describe your issue in as much detail as possible:
Fresh OS Install Ubuntu 16.04.3 LTS (64 bit) + 17.10  (64 bit)
Tried all kernels between 4.10 - 4.14
Steam runs fine using mesa drivers 
but as soon as amdgpu-pro-17.40-492261 is installed all hell breaks loose 
FPS drop 1/3rd  and psychedelic colors in steam 

http://steamcommunity.com/profiles/76561197968742271/screenshots/?appid=212070

Also tried disabling the new Shader Pre-Caching option

**Comment by kisak-valve** [comment]
Hello @MasterCATZ, can you clarify if steam itself is affected, all games, or just Star Conflict. This should also be brought to the attention of the driver vendor.

**Comment by kisak-valve** [comment]
Hello @MasterCATZ, are you still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
