### ISSUE TITLE
After last Steam client update don't starts Euro Truck Simulator 2

### ISSUE THREAD

**Issue by RockBomber** [ValveSoftware/steam-for-linux#5283]
#### Your system information

* Steam client version (build number or date): Dec 15 2017, at 11:47:57
* Distribution (e.g. Ubuntu): Kubuntu 17.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After last Steam client update don't starts Euro Truck Simulator 2 with error:

```
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 227300, ActionID 1] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 227300, ActionID 1] : LaunchApp continues with user response "0"
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 227300, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 227300, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 0
Game update: AppID 227300 "", ProcID 18253, IP 0.0.0.0:0
ERROR: ld.so: object '/home/bomber/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/bomber/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/bomber/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64/eurotrucks2: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
>>> Adding process 18253 for game ID 227300
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 18254 for game ID 227300
GameAction [AppID 227300, ActionID 1] : LaunchApp changed task to Completed with ""
Game removed: AppID 227300 "", ProcID 18253 
No cached sticky mapping in ActivateActionSet.
```
Before Steam client update game starts normally.

I run Steam client with script:

```
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LD_LIBRARY_PATH="/usr/lib32/nvidia-384" steam
```

**Comment by RockBomber** [comment]
Workaround: copy libsteam_api.so to directory without spaces, and add path to LD_PRELOAD:

`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 LD_LIBRARY_PATH="/usr/lib32/nvidia-384" LD_PRELOAD="/home/bomber/.local/share/Steam/libsteam_api.so" steam`

**Comment by kisak-valve** [comment]
Hello @RockBomber, it looks like this game had an update around the time this issue showed up. You should also bring this to the attention of one of the game devs.

**Comment by sebaro** [comment]
The library is in the game's directory, I start steam like this:
``
LD_LIBRARY_PATH="/home/Games/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64" steam
``
Yes, there was an update but I tried with previous versions also beta and it's the same.

**Comment by kisak-valve** [comment]
Hello @RockBomber, @sebaro, are either of you still experiencing this issue on an up to date system?

**Comment by RockBomber** [comment]
All works fine, thank you!
