### ISSUE TITLE
Too many gameoverlayui processes open

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5284]
#### Your system information

* Steam client version (build number or date): 15/12/17
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I checked system manager and found 14! gameoverlayui processes open, they remained open even after closing steam:
https://i.imgur.com/YEmyrGC.png

#### Steps for reproducing this issue:

1. I have no idea.
2. 
3.

**Comment by kisak-valve** [comment]
Most likely a side effect of #4933.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
