### ISSUE TITLE
On the `manage downloads` page it only shows MB, even when its over 1 GB

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [ValveSoftware/steam-for-linux#5290]
#### Your system information

* Steam client version (build number or date): Most recent as of 12/17/2017
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
On the manage downloads page it references everything as `MB`, even if its in the GB's

#### Steps for reproducing this issue:

1. Download something thats over 1G
2. Wait for it to finish
3. Look at how much it says it downloaded next to the game
4. Profit
![screenshot from 2017-12-17 17-31-22](https://user-images.githubusercontent.com/13257145/34085609-58d9050e-e361-11e7-92c3-841ea6197840.png)

**Comment by kisak-valve** [comment]
Hello @gidoBOSSftw5731, are you still experiencing this issue with an up to date system?

**Comment by gidoBOSSftw5731** [comment]
Sorry for the late reply, I don't believe so, but I'll retest and check closer soon.

**Comment by gidoBOSSftw5731** [comment]
Cannot reproduce on debian 10 system, kernel 5.5. Closing.
