### ISSUE TITLE
No steam games start anymore

### ISSUE THREAD

**Issue by kupschke** [ValveSoftware/steam-for-linux#5291]
#### Your system information

* Steam client version (build number or date): Dec 15 2017, at 11:47:57
* Distribution (e.g. Ubuntu): Debian Testing
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Every game I try to start right out of steam crashes immediately.
When I start CS:GO this message will be printed:
Failed to create GL context: Could not make GL context current: GLXBadContextTag

In dmesg I see this crash:
 [   54.025215] csgo_linux64[3871]: segfault at 0 ip 00007effe4762b3e sp 00007fffd7c7a5a0 error 6 in libtier0_client.so[7effe4750000+29000]

Non Valve Games produce some other message in dmesg.
This is what I see when I start "Goat Simulator":
[ 8668.844791] GoatGame[17229]: segfault at c ip 00007f41a60dd0a0 sp 00007fff2b320288 error 4 in libxcb-glx.so.0.0.0[7f41a60cd000+18000]

When I start a steam game outside of steam using the cli it works.

#### System information:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 1500X Quad-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Debian GNU/Linux testing (buster) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.0-1-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11905000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  X.Org AMD Radeon (TM) RX 460 Graphics (POLARIS11 / DRM 3.19.0 / 4.14.0-1-amd64, LLVM 5.0.0)
    Driver Version:  3.0 Mesa 17.3.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67ef
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 23,54" x 13,23" (26,97" diag)
                                            59,8cm x 33,6cm (68,5cm diag)
    Primary VRAM: 4075 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  7985 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  234602 Mb
    Largest Free Hard Disk Block:  47757 Mb
    VR Headset: None detected

Recent Failure Reports:

Is there anything else you need?

Best Regards
Dominik

**Comment by kisak-valve** [comment]
Hello @kupschke, can you list the contents of `~/.steam/ubuntu12_32/steam-runtime/pinned_libs_*` or `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*`? After that, does closing steam, removing the pinned_libs folders, then re-starting steam make a difference?

**Comment by kupschke** [comment]
Hi,

this is the output of the folders:

ls ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_32/
has_pins  libdbus-1.so.3  libgtk-x11-2.0.so.0  libpangox-1.0.so.0  system_libdbus-1.so.3  system_libgtk-x11-2.0.so.0  system_libpangox-1.0.so.0

ls ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_64/
has_pins  libdbusmenu-glib.so.4  libGLU.so.1  libpangox-1.0.so.0  system_libdbusmenu-glib.so.4  system_libGLU.so.1  system_libpangox-1.0.so.0

I removed those folders and restarted steam:
Running Steam on debian  64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 32-bit libdbus-1.so.3. Host: 3.19.4 Runtime: 3.5.8
Found newer runtime version for 32-bit libgtk-x11-2.0.so.0. Host: 0.2400.31 Runtime: 0.2400.10
Found newer runtime version for 32-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
[2017-12-18 22:59:43] Startup - updater built Dec 15 2017 11:47:44
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-12-18 22:59:43] Checking for update on startup
[2017-12-18 22:59:43] Checking for available updates...
[2017-12-18 22:59:45] Download skipped: /client/steam_client_ubuntu12 version 1513371133, installed version 1513371133
[2017-12-18 22:59:45] Nothing to do
[2017-12-18 22:59:45] Verifying installation...
[2017-12-18 22:59:45] Performing checksum verification of executable files
[2017-12-18 22:59:45] Verification complete

But the problem is the same.

Regards
bommi

**Comment by kupschke** [comment]
Hi,

any idea on how to fix this?

Regards
Dominik

**Comment by kupschke** [comment]
When I try to start steam in Big Picture Mode it will crash immediately.
In dmesg the crash gets reported:
steam[17160]: segfault at 5 ip 00000000f694b9c1 sp 00000000ffa58700 error 4 in radeonsi_dri.so[f6909000+b82000]

**Comment by kupschke** [comment]
According to the ~/.steam/error.log you have received an Crash Dump with the CrashID=bp-1a607855-6967-4d5a-a9ae-e01ac2171228

Regards
Dominik

**Comment by kupschke** [comment]
Hi,

starting Steam in Big Picture Mode also leads to this type of crash.
Do you need the crash dump created after this?

Regards
Dominik

**Comment by kupschke** [comment]
This issue got fixed after latest steam update in debian:
https://tracker.debian.org/news/933866
