### ISSUE TITLE
Steam on Kubuntu 17.10 doesn't work at all

### ISSUE THREAD

**Issue by superluig164** [ValveSoftware/steam-for-linux#5293]
Your system information
Asus T100TAF 
1.33 GHz Intel Atom CPU
2GB of RAM
32GB internal storage

* Steam client version (build number or date): Latest stable as of December 18th, 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.10 with KDE (Kubuntu)
* Opted into Steam client beta?: No, don't even get the chance to
* Have you checked for system updates?: Yes, I do updates whenever possible

I downloaded and installed the .deb package, and when I attempt to run it, literally nothing happens.  Steam cannot be found in my resource manager to be killed either.  There is some output in the command line: (my username has been replaced with username)
`Repairing installation, linking /home/username/.steam/steam to /home/username/.local/share/Steam
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
/home/username/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/i386-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
/home/username/.local/share/Steam/steam.sh: line 444: no match: ssfn*`
And then it boots back to the standard command input.

Steps for reproducing this issue:

1. Download the .deb and install it normally
2. Attempt to launch steam
3. Watch as absolutely nothing happens

**Comment by kisak-valve** [comment]
Hello @superluig164, this issue is already being tracked at #4816.

You should be able to workaround this issue by running `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1' LIBGL_DRI3_ENABLE=0 steam` or https://github.com/ValveSoftware/steam-for-linux/issues/4816#issuecomment-339329851 in a terminal once, then the workaround should not be needed after that.

**Comment by superluig164** [comment]
@kisak-valve Thank you for the help, I apologize for the dupe.  I suppose I assumed they weren't the same because the other OP still got the EULA.  

I will try this fix and report back if it doesn't work.  Thank you.

**Comment by superluig164** [comment]
@kisak-valve Here's my output from the command line when I try the workaround...
https://pastebin.com/S0kM5XcU

**Comment by kisak-valve** [comment]
Okay, let's try again with Debian/Ubuntu specific folders:  `LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6 /lib/i386-linux-gnu/libgcc_s.so.1' LIBGL_DRI3_ENABLE=0 steam`

**Comment by superluig164** [comment]
https://pastebin.com/bnECgBRi

Is this a problem with me, or Steam?  So far all other Ubuntu apps work fine...

**Comment by karim789** [comment]
I have exactly the same issue on Ubuntu 17.10.

**Comment by kisak-valve** [comment]
Hello @superluig164, the way Steam handles the Steam runtime was changed a couple years ago to prefer host libraries over the Steam runtime variants. Also, that logic was added to the 1.0.0.55 bootstrap environment. As a result this scenario shouldn't occur with an up to date system.

If you're still experiencing this issue on an up to date system, please open a new issue report.
