### ISSUE TITLE
Steam launcher not displaying

### ISSUE THREAD

**Issue by jrsrjrsr** [ValveSoftware/steam-for-linux#5294]
#### Your system information

* Steam client version (build number or date): /client/steam_client_ubuntu12 version 1513371133, Downloaded Dec 15, 2017
* Distribution (e.g. Ubuntu): Linux Mint 18.3 (Sylvia) with the Cinnamon 3.6.6 desktop
* Opted into Steam client beta?: No (not that I am aware of)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

As of the last update to my machine, the steam launcher does not display.  

Some debugging info:

- An updater dialog displays and disappears like normal
- A "New Inventory" notification displays like normal
- The main launcher window does not display, which is why this issue was submitted.  This is the associated console output: [steam.log](https://github.com/ValveSoftware/steam-for-linux/files/1573797/steam.log)
- The process continues to run and spit out warnings as in the end of the attached log file.  I have to kill the process to shut it down.  When the process is killed, the "syncing to cloud" dialog displays like normal and the process quits.
- The same issue occurs on two different machines with the same OS/desktop, but different hardware.  The first is a Dell Inspiron Laptop with integrated graphics; the second is a custom-build desktop with an NVidia gpu
- Big Picture mode starts successfully using the command `steam -bigpicture`
- Games start successfully using commands of the form `steam steam://rungameid/123456` 
- When running a game directly as above, the console window has many of the same warnings as the attached file, leading me to believe most of the messages are not critical.  By comparing the logs between the two modes and ignoring message that have to do with actually starting a game, it appears that the following CRITICAL error only occurs in the launcher-only mode:
`** (steam:12916): CRITICAL **: marshal_dbus_message_to_g_marshaller: assertion 'message != NULL' failed`

Any help debugging this issue would be much appreciated.

**Comment by kisak-valve** [comment]
Hello @jrsrjrsr does the tray icon show and is it usable like is reported in #5285?

**Comment by jrsrjrsr** [comment]
Yes!!  When I select "Library" from the tray the client displays in the foreground.

**Comment by kisak-valve** [comment]
Thanks for checking, let's track this issue on the existing issue report.
