### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by JesusIslam** [ValveSoftware/steam-for-linux#5295]
#### Your system information

* Steam client version (build number or date):  From Ubuntu Repository
* Distribution (e.g. Ubuntu): Ubuntu Mate 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
```
sudo apt install steam
[sudo] password for didasy: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
System spec:
- Intel i5-7200U
- Intel HD 620

#### Steps for reproducing this issue:

1. `sudo apt install steam`

**Comment by kisak-valve** [comment]
Hello @JesusIslam, ubuntu's package manager has these packages. Have you enabled multiarch with something like:
```
sudo dpkg --add-architecture i386
sudo apt update
sudo apt upgrade
```

**Comment by JesusIslam** [comment]
@kisak-valve Hello, I've done it but it still returns the same thing:

```
sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 steam:i386 : Depends: libgl1-mesa-dri:i386 but it is not going to be installed
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by timvisee** [comment]
I'm experiencing the same, on a recently installed Mac Mini 2012 running Ubuntu GNOME 16.04.

**Comment by gorky** [comment]
https://help.steampowered.com/en/wizard/HelpRequest/HT-T6VG-YH7X-K6T3
It's an Ubuntu 18.04, Linux Mint 19.  Laptop is an older one.  Steam was running fine on Mint 18/Ubuntu 16, but died when I upgraded to Mint 19.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

In general, consulting your distro's community support is the best way to get help with package manager issues, but if you are, please add the output of `apt policy libgl1-mesa-dri libgl1-mesa-dri:i386` and we can try to ponder the issue a little bit more.

**Comment by kisak-valve** [comment]
Closing as outdated.
