### ISSUE TITLE
DLC listing for SteamOS when the game is not on SteamOS

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#5297]
This seems to be a problem occurring a lot, a DLC will list as available for SteamOS, when the game itself is not.

Here's some recent examples (also sent to Pierre-Loup Griffais on Twitter):
http://store.steampowered.com/app/756280/deep_space_waifu_FLAT_JUSTICE__SOUNDTRACK/
http://store.steampowered.com/app/763530/Nocturnal_Hunt__Soundtrack/
http://store.steampowered.com/app/695530/dead_filemp3/

Then this DLC:
http://store.steampowered.com/app/533310/Wells__Soundtrack/
That one did originally have SteamOS support, but they removed it, but the DLC still lists it.

You probably hear "simple" suggestions all the time, but is it not possible to have a DLC not support more than the base game in terms of platforms?

**Comment by kisak-valve** [comment]
To be fair, these are soundtracks and the audio files are not OS-specific.

**Comment by LiamDawe** [comment]
While true, it still seems odd. 

Especially with the Steam store text "This content requires the base game X on Steam in order to play.".
