### ISSUE TITLE
Steam can't install CG:GO to NTFS partition

### ISSUE THREAD

**Issue by mubat** [ValveSoftware/steam-for-linux#5300]
After downloading CG:GO client (5 times) steam write that it has download errors. I upgrade Steam to beta version. And it write some error at file `steamapps/downloading/730/bin/convertdmx.lua`. I opened it and his next rows:

```
-- Make sure all your paths have forward slashes. (do a search and replace if necessary)
--NOTE: change the load path and Save path to your own, directories for the DMX you are converting
Load( "C:/Depot/Valve/trunk/source/cstrike15/content/left4dead2/models/destruction_tanker/dmx/pre_destruction_tanker_trailer.dmx" )
Save( "C:/Users/brian/Desktop/Decomplie/pre_destruction_tanker_trailer.obj" )
```

How to fix problem?

**But game can be lauched via .sh script from folder (wiithout steam connection).**

#### System information

* Steam client version (build number or date): 1513870789
* Distribution (e.g. Ubuntu): Linux Mint 18.3 Cinnamon
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

**Comment by kisak-valve** [comment]
Hello @mubat, this issue is already being tracked at #4800.

There's a workaround at https://github.com/ValveSoftware/steam-for-linux/issues/4800#issuecomment-271763278.

Closing as a duplicate.
