### ISSUE TITLE
Workshop download progress no longer visible in the Steam client

### ISSUE THREAD

**Issue by Baguettedood** [ValveSoftware/steam-for-linux#5302]
#### Your system information

* Steam client version (build number or date): Dec 20 2017, at 16:08:35
* Distribution (e.g. Ubuntu): Antergos
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
What I expected, and what worked in older releases of Steam: Subscribing to a workshop item shows download progress in Steam's download window.
What happens: Workshop item downloads, but download progress is not shown in the downloads window.

I believe it is a side effect of attempting to hide shader cache downloads from the downloads window, which is now in the non-beta Steam client as of writing.

Appears to affect Windows users too, as seen in [this Steam Beta discussion page](http://steamcommunity.com/groups/SteamClientBeta/discussions/0/2906376154318032313/).

#### Steps for reproducing this issue:

1. Have a game installed that uses Steam Workshop (e.g. RimWorld, Arma 3)
2. Subscribe to a workshop item for that game.
3. Check the Steam client's downloads window for download progress on the workshop item.
4. Notice the game's workshop download does not appear in the list, but network usage indicates it is downloading in the background.

Additional note: Workshop downloads, as well as shader cache downloads, are still visible in Big Picture Mode, but idk if that deserves its own bug report.

**Comment by kisak-valve** [comment]
Hello @Baguettedood, per "Fixed bugs preventing workshop items or newly installed DLC from showing up on the downloads page" in the [2018-04-02](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1658888566594367670) Steam beta client update, please opt into steam's beta and retest this issue.

**Comment by Baguettedood** [comment]
Seems to be resolved now, thanks.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
