### ISSUE TITLE
Steam hangs and Steam window doesn't appear in Gnome on Ubuntu 17.10

### ISSUE THREAD

**Issue by devesh** [ValveSoftware/steam-for-linux#5303]
#### Your system information

* Steam client version (build number or date): steam-launcher 1.0.0.54 downloaded from the website
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes. My system is up to date.

#### Please describe your issue in as much detail as possible:

I ran steam from the command line and expected to see it download updates, log in, and then see the steam client load the home page. Instead, I saw the download window, then the login window, and after I logged in, there was nothing. I can see that multiple steam processes are running, but there is no Steam window.

[stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/1586093/stdout.txt)
[steamprocesses.txt](https://github.com/ValveSoftware/steam-for-linux/files/1586095/steamprocesses.txt)

#### Steps for reproducing this issue:

1. Install the steam deb from http://store.steampowered.com/about/
2. Run `steam`.

**Comment by devesh** [comment]
It looks like in Gnome, instead of showing a home page window, it just puts a Steam icon in the notification section. I was able to bring up the library window by clicking on that icon.

**Comment by kisak-valve** [comment]
If anyone happens across this issue report, this issue is being tracked at #5285.
