### ISSUE TITLE
nvidia dropping 32 bits support

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5304]
Since nvidia is dropping 32 bits support, shall we expected a clean beta 64 bits steam client to test? (and a new installer).
(btw, if you could link your binaries to the static libgcc and static libstdc++ to avoid the issues related to those shared libs while you are it...)
port.

**Comment by kisak-valve** [comment]
Hello @sylware, from what I've heard, nVidia is dropping support from their installer to install on 32 bit kernels and is not dropping support for 32 bit userspace applications on 64 bit kernels.
