### ISSUE TITLE
Steam AND CSGO crashed at same time

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#5306]
#### Your system information

* Steam client version (build number or date): 
![steam_version](https://user-images.githubusercontent.com/6024315/34398086-4c334a16-eb41-11e7-8699-5a94a4bd1976.png)

* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

System Info:
https://gist.github.com/nightsky30/cdf65dde88540714c027b19e176dbcb6

#### Steps for reproducing this issue:

1. Started Steam
2. Played CSGO
3. CSGO Crashed during a round of arms race, and Steam completely crashed at the same exact time

How and where can I provide crash logs for Steam??  Nothing shows up under System Information as far as crash reports.

**Comment by kisak-valve** [comment]
Hello @nightsky30, minidumps from steam are commonly found in /tmp/dumps. If you are using the Valve-provided steam package, then there are is a general log at `/tmp/dumps/<username>_stdout.log`, otherwise a general log should be at `~/.steam/error.log`.

**Comment by nightsky30** [comment]
[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/1590404/dumps.zip)

[_stdout.txt.zip](https://github.com/ValveSoftware/steam-for-linux/files/1590408/_stdout.txt.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by kisak-valve** [comment]
Hello @nightsky30, have you seen this issue in recent history?

**Comment by nightsky30** [comment]
@kisak-valve No, I have not.  Feel free to close.  Thank you :)
