### ISSUE TITLE
Steam runtime corrupt upon system shutdown / restart in big picture mode

### ISSUE THREAD

**Issue by PJBrs** [ValveSoftware/steam-for-linux#5309]
#### Your system information
* Steam client version (build number or date):  build number 1513371133
* Distribution (e.g. Ubuntu): Slackware64-14.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
####Symptoms
The symptoms are as follows. When I choose "Restart system" system from within Steam's big picture mode, upon next boot steam always needs to verify its installation and startup takes long. Depending on the desktop environment it also needs to reinstall the entire bootstrap (dialog saying "unpacking steam runtime") - on a bare fvwm session that is, with the unwanted side effect that I need to add my credentials again, even though I've selected to automatically log in. Using a kde session the issue is less severe (credentials are preserved, bootstrap isn't reinstalled), but the long startup time is still annoying.

This took my attention: It appears that choosing Restart system almost directly calls reboot. If I choose reboot from commandline, like when choosing Restart system, X exits almost immediately and then the standard Slackware reboot init script gets executed (/etc/rc.d/rc.6). And upon starting steam after that, it indeed does unpack the runtime again and it forgets my credentials again.

####Expected behaviour
I would expect the following - after choosing Restart system, upon reboot, I expect the big picture mode to come up within about two seconds after X comes up (I start steam automatically). I expect not to see any dialog windows about verifying the installation (both kde and fvwm) or unpacking the steam runtime (fvwm). I expect my account to be logged in automatically, I do not expect that I need to add my credentials upon startup.

I've prepared a gist with two steam startup logs taken after choosing Restart system in big picture mode. The first log (https://gist.github.com/PJBrs/dbe510301e216be72da5444668a0da15#file-steam_stdout-fvwm-with-issue-no_ld_preload_spam-txt) is for fvwm (both before and after restart) and the second is for kde (https://gist.github.com/PJBrs/dbe510301e216be72da5444668a0da15#file-steam_stdout-kde-with-issue-txt). I also added a third log that I created after exiting steam by choosing Exit steam from big picture mode and then restarting kde (https://gist.github.com/PJBrs/dbe510301e216be72da5444668a0da15#file-steam_stdout-kde-without-problems-txt) - no problems then. 
https://gist.github.com/PJBrs/dbe510301e216be72da5444668a0da15

Incidentally, the fvwm logs were full of LD_PRELOAD errors because I preload libstdc++.so.6. I removed those because I don't think they have anything to with the issue. They don't show up on kde, don't understand why...

#### Steps for reproducing this issue:
1. In big picture mode choose Restart System

####P.S.,
I do call steam differently between kde and fvwm. Under kde, $ ps ax | grep steam shows the following steam-related processes:
 3221 ?        S      0:00 bash /usr/bin/steam
 3245 ?        S      0:00 bash /home/steam/.local/share/Steam/steam.sh
 3246 ?        S      0:00 tee /tmp/dumps/steam_stdout.txt
 3470 ?        Sl     3:11 /home/steam/.local/share/Steam/ubuntu12_32/steam
 3551 ?        S      0:00 /home/steam/.local/share/Steam/ubuntu12_32/steam
 3553 ?        S      0:00 /bin/bash /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper.sh -lang=en_US -cachedir=/home/steam/.local/share/Steam/config/htmlcache -steampid=3470 -buildid=1513371133 -steamid=0 -clientui=/home/steam/.local/share/Steam/clientui --disable-spell-checking --disable-out-of-process-pac --enable-blink-features=ResizeObserver --disable-smooth-scrolling --disable-gpu-compositing --disable-gpu --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt
 3558 ?        Sl     0:00 ./steamwebhelper -lang=en_US -cachedir=/home/steam/.local/share/Steam/config/htmlcache -steampid=3470 -buildid=1513371133 -steamid=0 -clientui=/home/steam/.local/share/Steam/clientui --disable-spell-checking --disable-out-of-process-pac --enable-blink-features=ResizeObserver --disable-smooth-scrolling --disable-gpu-compositing --disable-gpu --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt
 3566 ?        S      0:00 /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper --type=zygote --no-sandbox --lang=en_US.UTF-8 --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt --product-version=Valve Steam Client --webview-urls=http://localhost/*,http://steamloopback.host/*
 3658 ?        Sl     0:00 /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper --type=renderer --disable-gpu-compositing --disable-smooth-scrolling --enable-pinch --no-sandbox --service-pipe-token=CFCE778F1327876286C545DB3AA63606 --enable-blink-features=ResizeObserver --lang=en-US --lang=en_US.UTF-8 --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt --product-version=Valve Steam Client --webview-urls=http://localhost/*,http://steamloopback.host/* --disable-spell-checking --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-textur
 
Under fvwm, it is started differently, because of some xsession simplification, like this:
 4413 ?        Ss     0:00 /bin/bash /usr/bin/steam-de
 4497 ?        S      0:00 bash /usr/bin/steam -tenfoot -enableremotecontrol
 4514 ?        S      0:00 bash /home/steam/.local/share/Steam/steam.sh -tenfoot -enableremotecontrol
 4515 ?        S      0:00 tee /tmp/dumps/steam_stdout.txt
 4666 ?        Sl     0:10 /home/steam/.local/share/Steam/ubuntu12_32/steam -tenfoot -enableremotecontrol
 4670 ?        S      0:00 /home/steam/.local/share/Steam/ubuntu12_32/steam -tenfoot -enableremotecontrol
 4671 ?        S      0:00 /bin/bash /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper.sh -lang=en_US -cachedir=/home/steam/.local/share/Steam/config/htmlcache -steampid=4666 -buildid=1513371133 -steamid=0 -clientui=/home/steam/.local/share/Steam/clientui --disable-spell-checking --disable-out-of-process-pac --enable-blink-features=ResizeObserver --disable-smooth-scrolling --disable-gpu-compositing --disable-gpu --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt
 4675 ?        Sl     0:00 ./steamwebhelper -lang=en_US -cachedir=/home/steam/.local/share/Steam/config/htmlcache -steampid=4666 -buildid=1513371133 -steamid=0 -clientui=/home/steam/.local/share/Steam/clientui --disable-spell-checking --disable-out-of-process-pac --enable-blink-features=ResizeObserver --disable-smooth-scrolling --disable-gpu-compositing --disable-gpu --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt
 4677 ?        S      0:00 /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper --type=zygote --no-sandbox --lang=en_US.UTF-8 --log-file=/home/steam/.local/share/Steam/logs/cef_log.txt bview-urls=http://localhost/*,http://steamloopback.host/*
 4804 ?        Sl     0:00 /home/steam/.local/share/Steam/ubuntu12_64/steamwebhelper --type=renderer --disable-gpu-compositing --disable-smooth-scrolling --enable-pinch --no-sandbox --servi bview-urls=http://localhost/*,http://steamloopback.host/*

**Comment by kisak-valve** [comment]
Hello @PJBrs, are you still experiencing this issue on an up to date system? If the desktop environment is violently murdering Steam, then it's reasonable for Steam to do a consistency check on the next start.

**Comment by kisak-valve** [comment]
Closing pending feedback.
