### ISSUE TITLE
Steam client crashes when X is running 30 bits per pixel mode

### ISSUE THREAD

**Issue by KungFuJesus** [ValveSoftware/steam-for-linux#5312]
#### Your system information

* Steam client version (build number or date): Dec 20 2017
* Distribution (e.g. Ubuntu): Gentoo Linux
* Opted into Steam client beta?:  Yes
* Have you checked for system updates?: Yes

I have an nvidia card that supports > 24 bpp, and a monitor which supports it as well.  Starting X11 with 30 bit depths enabled causes many GL and non-GL applications to segfault, including the steam client.

#### Steps for reproducing this issue:

1. Start X with option "Depth 30"
2. Launch steam

I imagine there are many other implications for what this might do to many games expecting 24bpp formats (though, I have managed to launch some games in this mode successfully).  Nvidia is pushing for things like HDR with monitors into the X11 spec, so I imagine getting this working correctly isn't entirely outside of Valve's radar.  GTK apps also render poorly now with 30bpp (though I do remember a time when they didn't).  

Let me know if a core dump is required - however it's pretty easy to reproduce assuming you have a display that supports this.

**Comment by kisak-valve** [comment]
Hello @KungFuJesus, this issue is already being tracked at #4399. Closing as a duplicate.
