### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Vinicius379** [ValveSoftware/steam-for-linux#5313]
I realized that after the last 2 updates, the game presented problems for the player's vision, I used a gamer usb 3 mouse for test, and a common usb 2 mouse and the result was the same, as if it presented delay in the FPS, even in the menu the mouse "jumped" and did not move the screen smoothly.
After many attempts, I unpinned and reinstalled the game, changed all settings and restored to the default and noticed that the "mouse acceleration" option before the updates was set to 1, + and after updating this option is 0 as default, testing the acceleration of the mouse improves but still continues to "skip" instead of normally scrolling the menu and the screen when in the game.
I use a notebook without a dedicated video card, but 2 friends with notebooks (Windows 8 and 10) that have a dedicated video card are experiencing the same problem.
As a last resort, I tried to install the game on the latest and stable Ubuntu and the problem persists.
I do not understand, but the problem persists only in notebooks.
Another friend who owns a Desktop with dedicated video card said that after the update he was with the same problem but uninstalled and reinstalled and the game is normal and he is using a Windows 7.
I have not tried only Ubuntu with dedicated video card, and in Ubunto when it starts the game, it takes a while for the system to send a message asking if you still want to wait or close the program, in case you wait a long time the game starts but with the same mouse problem in menu
And steam can not save the login and password even when you choose to remember it, every time in ubuntu you have to write it all over again

**Comment by kisak-valve** [comment]
Hello @Vinicius379, the steam-for-linux issue tracker is intended for issues with steam itself, not performance issues with individual steam games. If you're having an issue with a Valve title, there are links to the game's issue trackers at https://github.com/ValveSoftware/steam-for-linux#reporting-issues, otherwise this should be brought to the attention of the game's devs.

As for the issue with credentials acting like they are forgotten, that issue is already being tracked at #5030.

**Comment by Vinicius379** [comment]
Thank you, the support on the stem that sent me the link to write here

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/csgo-osx-linux/issues/1586 and #5030.
