### ISSUE TITLE
Username of "catbot" triggers VAC ban

### ISSUE THREAD

**Issue by MrStonedOne** [ValveSoftware/steam-for-linux#5315]
So when you have an username on your GNU/Linux machine containing "catbot", you get a VAC ban.

This is an issue, it should stay here and remain open so that users can be aware.

Catbot is a common enough username (for say a discord or irc bot named cat or catbot) to be used by people who are not cheating, and they need to be warned of this bug.

**Comment by kisak-valve** [comment]
As previously stated, VAC issues are not handled on these issue trackers. This is topic not open for discussion on Github.

Closing as a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2475.
