### ISSUE TITLE
No text on steam at all

### ISSUE THREAD

**Issue by ibrokemypie** [ValveSoftware/steam-for-linux#5316]
#### Your system information

* Steam client version (build number or date):  appid(steam)/version(1513371133)? Cant find any other mention of versiion in the log and cant see in client because of the issue
* Distribution (e.g. Ubuntu): artix linux
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I believe this started recently after updating xorg-server and mesa.
I have all the fonts needed installed, and all fonts anyone has ever mentioned in the issues too.
When steam starts there is simply no text, whatsoever.
Main steam window:
![image](https://user-images.githubusercontent.com/7827846/34513708-b295f76e-f0bd-11e7-902c-83a3a0dd0c57.png)
Steam preferences window:
![image](https://user-images.githubusercontent.com/7827846/34513719-c1688acc-f0bd-11e7-99fa-3674188d07c7.png)
Friends list window:
![image](https://user-images.githubusercontent.com/7827846/34513722-cac823ac-f0bd-11e7-89e5-6bb3228d66e5.png)

This issue more or less makes the steam client unusable.

#### Steps for reproducing this issue:

1. Start steam

**Comment by kisak-valve** [comment]
Hello @ibrokemypie, your screenshots hint that the 32 bit opengl driver being used isn't quite sane as there's no textures rendered. Can you check if other 32 bit opengl applications work as expected?

**Comment by kpcyrd** [comment]
From the archlinux wiki:
> Steam makes heavy usage of the Arial font. A decent Arial font to use is ttf-liberation or the fonts provided by Steam. Asian languages require wqy-zenhei to display properly.
I hope this helps.

**Comment by ibrokemypie** [comment]
@kisak-valve it indeed seemed to be my end at fault, had mismatched mesa and llvm versions, sorting that out has fixed it, thanks!
