### ISSUE TITLE
Autologout after some inactivity

### ISSUE THREAD

**Issue by kpcyrd** [ValveSoftware/steam-for-linux#5318]
#### Your system information

* Steam client version (build number or date): Dec 15 2017, at 11:47:57
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm getting logged out of steam inside the webframe, while I'm still logged into steam itself. I have to close and restart steam to get logged into the webframe again to interactive with the store or with the community tab.

#### Steps for reproducing this issue:

1. Start steam
2. Verify you're logged in in the store web-frame
3. do something else for 10-15min
4. navigate to community and back to store (or reload the webframe)
5. check if you're still logged in

Possibly related to #3167, #5200 and #4971

**Comment by nightsky30** [comment]
I'd like to add maybe related to [#1518](https://github.com/ValveSoftware/csgo-osx-linux/issues/1518) or [#1558](https://github.com/ValveSoftware/csgo-osx-linux/issues/1558) ??

**Comment by kpcyrd** [comment]
Possibly related. I'm getting this without playing a game, I'm going to try to reproduce this with CS:GO as well.

**Comment by kpcyrd** [comment]
This seems fixed, thanks!
