### ISSUE TITLE
Yooka-Laylee game directory is empty

### ISSUE THREAD

**Issue by drradio** [ValveSoftware/steam-for-linux#5319]
#### My system information

* Steam client version (build number or date): Dec 15 2017, at 11:47:57
* Distribution (e.g. Ubuntu): Debian 9 Stretch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue
Yooka-Laylee game directory is empty (contains no game related files) except the only one empty subdirectory (EmptySteamDepot).
I tried to reinstall it, but no files is downloaded, and game directory is empty anyway.
![2018-01-03_21-45-30](https://user-images.githubusercontent.com/35088721/34558587-fc1bad1a-f168-11e7-887a-d9eb92b61a92.png)

**Comment by kisak-valve** [comment]
Hello @drradio, this issue should be brought to the attention of the game's devs.

**Comment by Muffindrake** [comment]
@drradio Please see https://steamcommunity.com/app/360830/discussions/0/1620599015874147447/

**Comment by drradio** [comment]
@Muffindrake, thank you very much! This worked for me.
