### ISSUE TITLE
Steam crashed on Mint

### ISSUE THREAD

**Issue by Xlond** [ValveSoftware/steam-for-linux#5320]
#### Your system information

* Steam client version (build number or date): 1513371133
* Distribution (e.g. Ubuntu): Mint
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]yes

after installing the steam client, i cant start client and i get that error
/home/xlond/.local/share/Steam/steam.sh: line 927: 16592 invalid instruction                 (подготовлен дамп ядра) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
https://gist.github.com/Xlond/98e3a55ddd66906377b9a9f88fcc1706
at steam.sh: line 927 i see:
![screenshot_20180104_190003](https://user-images.githubusercontent.com/35108505/34572118-960f6cd2-f181-11e7-8ff4-b32068a5e192.png)

#### Steps for reproducing this issue:

1. launching steam in the console
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Xlond, what processor is in your system? Does it support SSE3 (from #5164)?

**Comment by EnriqueBet** [comment]
Hello @Xlond  I had the same problem that you on Fedora and found a workaround in Fedora (that seems to work in Ubuntu as well) Could you please try to add "-steamos"  to your instruction. So you should run:
`steam -steamos`

**Or with bumblebee (primusrun)**
`primusrun steam -steamos`

As I said this is a workaround reported on issue #5428. Please confirm if this work for you. :dancing_men:

**Comment by kisak-valve** [comment]
Closing due to lack of feedback.
