### ISSUE TITLE
Selectable ambient music in Big Picture Mode

### ISSUE THREAD

**Issue by Scrumplex** [ValveSoftware/steam-for-linux#5321]
Example: https://www.youtube.com/watch?v=4oxw638tIzQ
Would make Steam a better platform.

**Comment by kisak-valve** [comment]
Hello @Scrumplex, using Nintendo's music has legal headache written all over it, but this feature request could be generalized to be a request to easily change the ambient music in Big Picture Mode so I'm going to leave it open.
