### ISSUE TITLE
Language problem on Linux

### ISSUE THREAD

**Issue by queenmedley** [ValveSoftware/steam-for-linux#5323]
#### Your system information

* Steam client version (build number or date): Dec 15 2017 , API v017 . Package 1513371133
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes.

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

I solved asian languag problem before. (CJK)
https://steamcommunity.com/app/400/discussions/0/412446292775908119/

But recentlry that problem happen again.
When start steam launcher with CJK language, there are no letters on screen.
Changing language in start option is useless even English.
When start steam launcher with none CJK font, it show localed language.

I tried that method several time and reinstall steam and portal. 
Bust all useless.

**Comment by kisak-valve** [comment]
Hello @queenmedley, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
