### ISSUE TITLE
After update Steam failed to start

### ISSUE THREAD

**Issue by docMP** [ValveSoftware/steam-for-linux#5326]
* Steam client version (build number or date): 1513371133
* Distribution (e.g. Ubuntu): 14.04/64bit
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

I'm using Steam with few games on Ubuntu 14.04/64bit, with NVidia. Just after Christmas, Steam started by updating itself. If has worked OK before, but not after this install.
Before: I get a shell asking to install few libraries(ibgl1-mesa-dri:i386, libgl1-mesa-glx:i386) ; I have tried that few times; but nothing was installed. Then I just close it, and Steam start & everything works well
--Failed installation message, which I could ignore;
Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386
..............................................................................................................................
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libgl1-mesa-glx:i386 : Depends: libglapi-mesa:i386 (= 10.1.3-0ubuntu0.6)
                        Depends: libudev1:i386 but it is not going to be installed or
                                 libudev0:i386 but it is not installable
unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
--

## Now after install: 

After the shell is closed, I get a message-window "You are missing the following 32-bit libraries, [note I use 64 bit] and Steam may not run: libdrm.so.2". -> OK -> Installing... 2sec.. "Fatal error; Failed to load steamui.so".

Same in detail:

$ steam

(gnome-terminal:12389): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libdrm.so.2
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
Failed to load steamui.so - dlerror(): libdrm.so.2: wrong ELF class: ELFCLASS64
Installing breakpad exception handler for appid(steam)/version(1513371133)
Installing breakpad exception handler for appid(steam)/version(1513371133)
[2018-01-08 22:16:42] Startup - updater built Dec 15 2017 11:47:44
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2018-01-08 22:16:42] Checking for update on startup
[2018-01-08 22:16:42] Checking for available updates...
[2018-01-08 22:16:42] Download skipped: /client/steam_client_ubuntu12 version 1513371133, installed version 1513371133
[2018-01-08 22:16:42] Nothing to do
[2018-01-08 22:16:42] Verifying installation...
[2018-01-08 22:16:42] Performing checksum verification of executable files
[2018-01-08 22:16:43] Verification complete
[2018-01-08 22:16:45] Shutdown

## Re-install?
$ sudo apt-get remove steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'steam:i386' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

How to Make Steam great again?.... working that is.

**Comment by kisak-valve** [comment]
Hello @docMP, I read that log snippet as steam trying to tell you it needs [libdrm2:i386](https://packages.ubuntu.com/trusty/libdrm2). If you were using mesa, it'd be helpful to keep trying to pin down these libraries, but you've noted that you use the nVidia driver, which doesn't use those packages at all. This hints that the 32 bit nvidia proprietary driver is broken on your system.

Does any 32 bit opengl application work such as glxinfo from mesa-utils:i386?

Separately, please check if you have realpath installed, which is needed for steam to pin libraries, but is not installed by default on Ubuntu 14.04.

**Comment by docMP** [comment]
Hi,
I installed realpath just before repeating this all, no difference.
glxinfo nor mesa-utils are installed (nor were installed, when it worked).

**Comment by docMP** [comment]
Is there anything else to test / reinstall (which commands?) or just reinstall Ubuntu?

**Comment by kisak-valve** [comment]
The current step in troubleshooting is what I asked, can you please confirm that your 32 bit OpenGL driver is sane? It doesn't matter what you use to test as long as the application is 32 bit and uses OpenGL.

**Comment by docMP** [comment]
ref. https://ubuntuforums.org/showthread.php?t=856313
I installed mesa-utils and test glxgears; it works: ~59fps (didn't make Steam work)
$ glxinfo | grep "OpenGL version"
->   OpenGL version string: 4.5.0 NVIDIA 384.111
Please advice what other tests there should be? Or how to reinstall

**Comment by kisak-valve** [comment]
Installing mesa-utils (as opposed to mesa-utils:i386) would give you the 64 bit variant of glxinfo.

**Comment by docMP** [comment]
And how to test the 32bit?

**Comment by kisak-valve** [comment]
Hello @docMP, are you still experiencing this issue on an up to date system?

Installing a 32 bit variant of a package is literally `sudo apt-get install <package name>:i386` like `sudo apt-get install mesa-utils:i386`.

**Comment by kisak-valve** [comment]
Closing pending feedback.
