### ISSUE TITLE
Sometimes can't write inside lobby in CS:GO and steam chat (Shift + TAB)

### ISSUE THREAD

**Issue by nikdale** [ValveSoftware/steam-for-linux#5327]
#### Your system information

* Steam client version (build number or date): 1513371133 (Steam package version)
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Sometimes inside CS:GO (I don't play other games) I cant write in any text insert. To fix this inside lobby I must click on Game Settings, then go back and now I can write. This happens really often. Same on Shift + TAB but I haven't figured it out how to fix that.

**Comment by kisak-valve** [comment]
Hello @nikdale, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
