### ISSUE TITLE
invisible downloads when I quit Steam

### ISSUE THREAD

**Issue by legluondunet** [ValveSoftware/steam-for-linux#5329]
#### Your system information

* Steam client version (build number or date): 15 december 2017
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] YES
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When I ask steam to quit, a dialog box appears and ask me to wait for the download of game XXX to finish.
But the download is invisible: no percentage in the librairy near the game name, no download animation at all in the steam interface.
#### Steps for reproducing this issue:

1. open steam
2. quit steam, this dialog box appear:
![capture d ecran de 2018-01-10 00-30-10](https://user-images.githubusercontent.com/325405/34748715-2684f4c4-f59e-11e7-89c6-12ae6eb735e2.png)
3. Steam will close when it will finish downloading the game

**Comment by Baguettedood** [comment]
I suspect this may be related to shader cache downloads, which are hidden to the user.

**Comment by kisak-valve** [comment]
Possibly a duplicate of #5302. Shader cache downloads are relatively small and normally would not account for a significant delay.

**Comment by kisak-valve** [comment]
Hello @legluondunet, per "Fixed bugs preventing workshop items or newly installed DLC from showing up on the downloads page" in the [2018-04-02](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1658888566594367670) Steam beta client update, please opt into steam's beta if you are not already and retest this issue.

**Comment by legluondunet** [comment]
I can not reproduce this bug for several steam beta, I close this issue. Thank you.
