### ISSUE TITLE
Suspend and steam

### ISSUE THREAD

**Issue by ICHx** [ValveSoftware/steam-for-linux#5331]
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Open Steam
2. Suspend the system leaving steam opened
3. Resume
4. (Optionally) Open TF2

After the resume, there would be a few problems using steam to take place
1. Last seen in steam chat got reset
2. TF2 cannot connect to the matchmaking coordinator(level badge become level 1, cannot connect to casual&VAC)
3. Steam chat would suddenly become "disconnected" and reconnected after a few seconds for a few minutes later once.

Workaround:
1. Close steam before suspension.
or 2. Restart steam after resume.

##Steam Sys Info
電腦資訊：
    製造商：lenovo
    型號：think center
    板型規格：desktop
    未偵測到觸控輸入

處理器資料：
    CPU 廠商：GenuineIntel
    CPU 品牌：Intel(R) Core(TM) i5 CPU         670  @ 3.47GHz
    CPU 系列：0x6
    CPU 型號：0x25
    CPU 步進：0x5
    CPU 類型：0x0
    速度：3459 Mhz
    4 個邏輯處理器
    2 個實體處理器
    超執行緒：支援
    FCMOV：支援
    SSE2：支援
    SSE3：支援
    SSSE3：支援
    SSE4a：不支援
    SSE41：支援
    SSE42：支援
    AES: 支援
    AVX: 不支援
    CMPXCHG16B: 支援
    LAHF/SAHF: 支援
    PrefetchW: 不支援

作業系統版本：
    "Manjaro Linux" (64 位元)
    核心名稱：Linux
    核心版本：4.14.12-1-MANJARO
    X Server 供應商：The X.Org Foundation
    X Server 版本：11906000
    X 視窗管理器：KWin
    Steam 運行版本：<Runtime disabled>

顯示卡：
    驅動程式：NVIDIA Corporation GeForce GT 1030/PCIe/SSE2
    驅動程式版本：4.5.0 NVIDIA 384.111
    OpenGL 版本：4.5
    桌面色彩深度：每像素 24 位元
    螢幕更新頻率： 60 Hz
    廠商 ID：0x10de
    設備 ID：0x1d01
    未偵測到修訂號碼
    螢幕數量：1
    邏輯顯示卡數量：1
    主要顯示器解析度：1920 x 1080
    桌面解析度：1920 x 1080
    主要顯示器尺寸：18.78" x 10.55" (21.54" diag)
 47.7cm x 26.8cm (54.7cm diag)
    主匯流排：PCI Express 4x
    主 VRAM：2048 MB
    支援的 MSAA 模式：2x 4x 8x 16x 

音效卡：
    音效裝置：Realtek ALC662 rev1

記憶體：
    隨機存取記憶體 (RAM)：3813 Mb

其他：
    UI 語言：繁體中文
    語言：zh_HK.utf8
    可用磁碟空間總和：100280 Mb
    最大可用硬碟區塊：26782 Mb
    VR 頭戴顯示器：未偵測到

近期失敗報告：
##

**Comment by kisak-valve** [comment]
Hello @ICHx, this issue is already being tracked at #474. Closing as a duplicate.
