### ISSUE TITLE
Steam not working on Arch linux, no libraries errors.

### ISSUE THREAD

**Issue by PierfrancescoArdino** [ValveSoftware/steam-for-linux#5332]
#### Your system information

* Steam client version (build number or date):  steam 1.0.0.54-3. kernel 4.14.13-1-ARCH
Nvidia gtx960M
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Using bumblebee with the latest drivers. Launching Steam (both native and runtime) from command line produced no relevant errors, after the login there is no window.

https://gist.github.com/PierfrancescoArdino/cf1cd98c8d88ffce9bf82b597017b447

**Comment by kisak-valve** [comment]
Hello @PierfrancescoArdino, your log doesn't suggest that steam is dying, can you check if there's a steam tray icon and if you can bring up steam's main window from there? (from #5285)

**Comment by PierfrancescoArdino** [comment]
Yes, it works.

Sill, this is more like a workaround that a proper solution

**Comment by kisak-valve** [comment]
Thanks for confirming, closing in favor of the existing issue report at #5285.
