### ISSUE TITLE
Wireless Steam Controller prevents In-Home Streaming - Ubuntu 16.04

### ISSUE THREAD

**Issue by ICantSeeIt** [ValveSoftware/steam-for-linux#5336]
#### System information

* Steam client version: Dec. 20, 2017 at 16:08:35
* Distribution: Ubuntu Gnome 16.04.3 LTS 64-bit
* Wireless Steam Controller
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Updated `udev` rules as per [this post](http://steamcommunity.com/app/353370/discussions/0/490123197956024380/), since the controller would not connect wirelessly at all until I changed those rules.  I can provide the full rules file if necessary, since I imagine the problem is somewhere in my specific configuration or else more people would have noticed this.

#### Please describe your issue in as much detail as possible:
Streaming fails to start when a Steam Controller is connected wirelessly.  Streaming works normally when wired or with no Steam Controller connected.  Tested with multiple games, including those with and without desktop launchers.  Results in a black "Streaming Client" window occupying most of the screen (gap at bottom of screen where Windows taskbar would be).  That window is unresponsive and eventually closes and leaves the user at the desktop.  The game runs normally on the Windows host PC, though it quickly shows that streaming has stopped.

The Steam Controller becomes unrecognized (shows as Unknown Controller in Steam controller settings), sometimes ceasing to function at all.  This condition persists after fully restarting Steam and the controller, and only is fixed after a system reboot.  Sometimes the Steam Controller shows as Unknown from the beginning, and functions incorrectly when wireless while Steam is not open (i.e. functions differently than it would when wired with Steam closed), such as the triggers not registering as mouse clicks.  Sometimes after a failed streaming attempt, the Steam Controller will stop working entirely (light stays on, appears to be connected, and haptics activate, but no inputs are received).

#### Steps for reproducing this issue:

1. Open Steam in either desktop or Big Picture mode.  Have Steam Controller connected wirelessly (connecting controller before/after launching Steam did not change behavior).
2. Have Steam running on another PC with games installed
3. Press "Stream" button for any game

Again, I think it is likely that this issue is isolated to my case.

**Comment by kisak-valve** [comment]
Related to #5269.

**Comment by ICantSeeIt** [comment]
Are there any troubleshooting steps that would be helpful for me to try, or any system information files I could provide?

I personally suspect this is related to the `udev` rules.

**Comment by ICantSeeIt** [comment]
I've been messing around with the Steam Controller settings and the `udev` rules (even deleted the changed rules file entirely and saw no consistent change - are the rule changes still needed?  Please update that page if they are not needed anymore) but nothing has clarified this issue at all.  I'm also no longer convinced this is just related to the streaming, because it seems like using a Steam Controller on linux is just fundamentally broken at the moment.  Is there any activity on this issue?  I'm not sure this is at all related to the Steam Link issue that was referenced.

When I connect my controller wirelessly (with Steam open) it often isn't even recognized as a Steam Controller (as opposed to just not showing up as *my* Steam Controller - it does that too sometimes).  Sometimes it doesn't connect at all.  Sometimes it connects and runs fine, until you turn it off or it turns itself off due to inactivity, and then when you connect it back up it stops working and goes back into "Unknown Controller" mode.  Hard reboots cause the behavior to change, but it's random which behavior I get each time I boot up.  Sometimes I boot back up after the Steam Controller became broken and made me restart and it will have the on-screen keyboard open for login password entry when it otherwise never does that.

To reiterate, this controller has absolutely no issues with the same wireless dongle on two different Windows 10 PCs.  It has never been used with a Steam Link.

Today, after I completely deleted the `lib/udev/rules.d/99-steam-controller-perms.rules` file I was able to get the controller to connect wirelessly and be detected properly after a large number of failed attempts and reboots.  This time streaming worked, but there was no audio (Windows 10 server PC audio device had successfully switched to the Steam Streaming Speakers device and was showing audio output, but there was no sound on any possible inputs on the Ubuntu client).

How can I help you guys help me?  I'm sure this is a weird problem that makes no sense, I'm just frustrated since it's been doing this for so long.

**Comment by kisak-valve** [comment]
Hello @ICantSeeIt, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
