### ISSUE TITLE
Steam streaming issue with Unreal Engine 4 based games (May not be limited to Linux)

### ISSUE THREAD

**Issue by mwpow3ll** [ValveSoftware/steam-for-linux#5337]
#### Your system information

* CPU: Intel i7-8700k
* Video: Nvidia Geforce 1080 TI (using v387.34)
* RAM: 64 GB
* Steam client version (build number or date): Dec. 15 2017
* Distribution (e.g. Ubuntu): Fedora 26
* Opted into Steam client beta?: No, but would if a fix were to come along
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

http://steamcommunity.com/app/353380/discussions/0/1488866180617424880/

There seems to be an issue with steam streaming Unreal Engine 4 based games. When streaming to steam link or another computer with steam, the game will load but only shows a green / black screen. You can hear audio and can move the mouse which will interact with the menu, so the game isn't frozen. I have tested this on two games, but others are also reporting the same findings on two other games, one of which is not supported on Linux just yet; therefore, it could be a Windows and Linux issue.

If you install the games locally, not streaming, they work just fine.

Known games with this problem: Helium Rain, Stellar Overload, Everspace, and Interstellar Cat

#### Steps for reproducing this issue:

1. Stream a UE4 based game (known games are Helium Rain, Stellar Overload, Everspace, and Interstellar Cat)

**Comment by mwpow3ll** [comment]
log output that shows:

- Successful stream on Linux of Divinity: Original Sin via steam link
- Unsuccessful stream on Linux of Stellar Overload via laptop computer
- Unsuccessful stream on Linux of Stellar Overload via steam link

[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/1702014/streaming_log.txt)

**Comment by mitrysme** [comment]
hi,

Any news on this bug ? It's pretty annoying because all UE4 games seems to be affected on my linux system.
Thanx

**Comment by mwpow3ll** [comment]
@mitrysme: I have contacted Valve at least three times since opening this defect. They refuse to indicate any level of progress or discuss any details; however, they did say the defect is assigned to @slouken who is the primary steam-link developer.

'It has been assigned to Sam Lantinga - the primary Steam Link developer. Sam does not always have time to comment on bugs but that does not mean he's not aware of the issue.

@slouken: An acknowledgement of some kind would be highly beneficial... there are a lot of UE4 games out there.

On a side note, I have tried getting the Helium Rain developers involved but they've stated its a UE4 game engine issue and not an individual game problem, no big surprise there, and that they've reached out to Epic to see if they can fix on their end.

Its sad... the two invested parties, Valve and Epic, don't seem to care...

**Comment by Plagman** [comment]
Are local Steam screenshots also broken for these titles?

**Comment by mwpow3ll** [comment]
@Plagman: I don't fully understand your question? what do you mean by local steam screenshots?

Playing a UE4 based game locally works just fine; however, if one streams any UE4 based game, either via steam-link or steam PC-to-PC, on Linux, as far as I have tested none of the titles listed work.

This is clearly a UE4 / steam streaming issue only; however, whether it also affects Windows, I can not say... but there was at least one other person on the steam forums reported this issue with Everspace and they currently do not officially support Linux.

**Comment by kisak-valve** [comment]
@mwpow3ll, without In-Home Streaming, can Steam's game overlay take screenshots of the affected games? The default hotkey is F12.

Note: #4933 may interfere with testing.

**Comment by mitrysme** [comment]
i just tested everspace. Still green screen on steam link.
 The screenshot function (F12) does not work either, full black .jpeg

**Comment by Plagman** [comment]
Can you try with today's Steam Client Beta?

https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1657765111819118193

**Comment by Plagman** [comment]
Thanks for testing!

**Comment by mitrysme** [comment]
wow ! just re tested everspace and tartarus and ... it works on the beta !
thx for your hard work :)
