### ISSUE TITLE
Allow option to disable decals (blood / bullet primarily)

### ISSUE THREAD

**Issue by fredddii** [ValveSoftware/steam-for-linux#5343]
This option has been, and is available, in pretty much all Valve games via the user interface. But not Counter-Strike: Global Offensive.

It is even available in Team Fortress 2 which I consider a less competitively active game compared to Counter-Strike: Global Offensive. It has been available in Counter-Strike 1.6 and Counter-Strike: Source but now completely stripped from this game.

The only way to achieve this right now is via a very unfriendly method, by assigning r_cleardecals to one or multiple buttons.

Please bring back the UI option that has always been provided.

**Comment by kisak-valve** [comment]
Hello again @fredddii, like your other CS:GO feature request, you'll want to post this in the CS:GO forums.

Closing as this is not an issue with the Steam client on linux (this issue tracker).

**Comment by fredddii** [comment]
Posted it on the forums before, on Steam as well as Reddit, and even mailed the team on the Valve site. Nothing changed. Many community maps still unplayable due to the excess blood and bullet holes.
