### ISSUE TITLE
D-Bus steam client crash

### ISSUE THREAD

**Issue by MoofMonkey** [ValveSoftware/steam-for-linux#5346]
#### Your system information

* Steam client version (build number or date): 1513371133 (took from logs)
* Distribution (e.g. Ubuntu): Ubuntu 18.04 (btw will be same as 17.04)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
SEGFAULT, same as https://github.com/ValveSoftware/Dota-2/issues/1385
Logs: https://gist.github.com/MoofMonkey/96f469da9f556dafae1de29e5f43f766

#### Steps for reproducing this issue:

1. Launch steam
2. Wait
3. ....
4. Profit

**Comment by MoofMonkey** [comment]
Now it's loading up to "Connecting steam account"

**Comment by JohanG2012** [comment]
Had the same issue earlier, worked fine after a reboot :)

**Comment by MoofMonkey** [comment]
@JohanG2012, in my situation it wasn't fix. By the way it's somehow fixed, friend confirmed. Closing.
