### ISSUE TITLE
Counter-Strike 1.6 Ignores sv_downloadurl (FastDL)

### ISSUE THREAD

**Issue by hobsRKM** [ValveSoftware/steam-for-linux#5347]
**Linux**
**Server config file**

> sv_downloadurl "http://fastdl.inmelodies.com/cstrike/"
> sv_allowdownload 1
> sv_allowupload 1

HTTP access logs on servers shows no URL hits.

**developer 255 displays game server url**

> Using http://139.59.93.30/cstrike/ as primary download location
> Verifying and downloading resources...
> loading maps/mini_dust2.bsp  

sv_download URL completey ignored.All files are being fetched from game server.

**Comment by kisak-valve** [comment]
Hello @hobsRKM, Counter-Strike 1.6 issues are tracked in the [halflife](https://github.com/ValveSoftware/halflife) issue tracker. Let's track this issue at https://github.com/ValveSoftware/halflife/issues/1855.
