### ISSUE TITLE
Artwork and Screenshot Showcases don't display anything

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5349]
#### Your system information

* Steam client version (build number or date): 15/12/17
* Distribution (e.g. Ubuntu): Ubuntu 17.10 amd64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Artwork and Screenshot Showcases don't show anything, it says "No items matching your search criteria were found." No search criteria was specified by me. It just stopped working months ago.

#### Steps for reproducing this issue:

I don't know.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
