### ISSUE TITLE
portal segfaults on startup

### ISSUE THREAD

**Issue by attilakinali** [ValveSoftware/steam-for-linux#5351]
#### Your system information

* Steam client version (build number or date): Dec 15, 2017
* Debian/testing amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Portal starts up,, I get the loading screen and then it crashes.
The only real bit of information I have is the kernel reporting a segfault within the HL2 engine:

Jan 23 20:13:34 jashugan kernel: [1204081.338906] traps: hl2_linux[12903] general protection ip:f7e906b3 sp:ffdf7688 error:0 in libc-2.26.so[f7d3e000+1cd000]

**Comment by kisak-valve** [comment]
Hello @attilakinali, can you take a look at #5330 and see if it's the same issue you are experiencing? You should be able to test by completely closing steam, then running `GLIBC_TUNABLES=glibc.tune.hwcaps=-SSE4_2 steam` from a terminal.

**Comment by attilakinali** [comment]
I do not think it's the same. For one thing, Civ V works fine on my machine, for another, the application never gets to output anything about the segfault. And third,  the kernel is reporting a segfault within the hl2 engine, calling some libc function.

**Comment by kisak-valve** [comment]
Thanks for checking, let's track this issue on the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2508.
