### ISSUE TITLE
Can't select text on About Steam

### ISSUE THREAD

**Issue by h1z1** [ValveSoftware/steam-for-linux#5355]
#### Your system information

* Steam client version (build number or date): Dec 15 2017
* Distribution: CentOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Help->About Steam menu should allow text to be selected and copied.  It does not.

#### Steps for reproducing this issue:

1. Install Steam
2. Find bug
3. Click Help->About Steam to find build date as per contributing requirements.  Wonder why text can't be selected

**Comment by Managor** [comment]
Can agree, it's a pain in the ass.

**Comment by Shiftyone** [comment]
Possibly unrelated, but I can not copy from System Information either. CTRL C and Right Click do not seem to work.

**Comment by h1z1** [comment]
@Shiftyone It's OS agnostic.  I seem to recall it briefly worked to the point you could blindly highlight and copy though it neither provided visual feedback nor appeared to copy at all.  It is still outstanding however.

**Comment by safield** [comment]
Such a pain in the ass! Fix asap please.

**Comment by h1z1** [comment]
For such a silly bug it's hard to believe this was opened almost two _years_ ago.   It did at one point allow you to select the text and copy though you couldn't see any highlight.  That too is broken again.

**Comment by auyer** [comment]
I was able to copy by Ctrl + A ->  Ctrl + C, but there is no visual feedback at all.

**Comment by hasezoey** [comment]
From my understanding this feature request can be closed, because since the new "About Steam" ui, the text is copyable (since around #9398), though i am not sure if this hit stable yet

![Screenshot_20240210_153658](https://github.com/ValveSoftware/steam-for-linux/assets/10911626/c2330c94-b2eb-456d-bd82-37343a8c2cc6)
