### ISSUE TITLE
My CS:GO crashes after loading a server...

### ISSUE THREAD

**Issue by matzeysb** [ValveSoftware/steam-for-linux#5356]
Hello guys , 
I download steam on ubuntu using orginal steam website , after that I downloaded CS:GO like usual game . I set up my graph and everything and I found this error . After I picked server and that all , my map starts to load and it come to recieveing data something ... After maybe 30 secconds it crashes... I have log from terminal 
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system supports the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GL_ARB_buffer_storage.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/filesystem_stdio_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/filesystem_stdio_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/inputsystem_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/inputsystem_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vphysics_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vphysics_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/materialsystem_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/materialsystem_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/datacache_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/datacache_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/studiorender_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/studiorender_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vscript_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vscript_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vguimatsurface_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vguimatsurface_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vgui2_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/vgui2_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/scaleformui_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/scaleformui_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/shaderapidx9_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/shaderapidx9_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/localize_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/localize_client.so: wrong ELF class: ELFCLASS32
Using breakpad minidump system 730/13623.647
USRLOCAL path using Steam profile data folder:
/home/mateo/.steam/steam/userdata/153111420/730/local
Did not detect any valid joysticks.
Timed out waiting for game mapping!
RESZ NOT SUPPORTED!
INTZ NOT SUPPORTED!
RESZ NOT SUPPORTED!
INTZ NOT SUPPORTED!
Failed to read the default inventory image file (materials/vgui/inventory_default.vtf)

##### swap interval = 0 swap limit = 1 #####
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/matchmaking_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/matchmaking_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/client_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/client_client.so: wrong ELF class: ELFCLASS32
CClientSteamContext logged on = 1
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/server_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/server_client.so: wrong ELF class: ELFCLASS32
Game.dll loaded for "Counter-Strike: Global Offensive"
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so: wrong ELF class: ELFCLASS32
failed to dlopen /home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/scenefilecache_client.so error=/home/mateo/.steam/steam/steamapps/common/Counter-Strike Global Offensive/bin/scenefilecache_client.so: wrong ELF class: ELFCLASS32
CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
CGameEventManager::AddListener: event 'game_newmap' unknown.
CGameEventManager::AddListener: event 'finale_start' unknown.
CGameEventManager::AddListener: event 'round_start' unknown.
CGameEventManager::AddListener: event 'round_end' unknown.
CGameEventManager::AddListener: event 'difficulty_changed' unknown.
CGameEventManager::AddListener: event 'player_connect' unknown.
CGameEventManager::AddListener: event 'player_disconnect' unknown.
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission)
Can someone please help who experienced this error and maybe fixed it ? 
Kind regards guys,

**Comment by kisak-valve** [comment]
Hello @matzeysb, in the future, please use the game-specific issue trackers such as [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux) for issues with individual games. That said, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Blind guess, but you're most likely experiencing the issue that was tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1509.

**Comment by matzeysb** [comment]
Here is my system information 
https://gist.github.com/matzeysb/7aa2283ff2a23b8928e2d68f7c37138e

**Comment by matzeysb** [comment]
Maybe there is problem with my system , im not used to linux , I use it because of coding ... haha

**Comment by kisak-valve** [comment]
Your system matches the issue that was tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1509.

Please update mesa to 17.2.7 or newer. I generally recommend [Padoka's Stable Mesa PPA](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa) to do this on Ubuntu. Alternatively, you should be able to workaround this issue by setting MSAA to 2x.
