### ISSUE TITLE
Steam BP webbrowser stops when playing any video fullscreen

### ISSUE THREAD

**Issue by ardje** [ValveSoftware/steam-for-linux#5358]
#### Your system information

* Steam client version (build number or date): 1516948201 / 2018-01-25 21:25:05
* Distribution (e.g. Ubuntu): Steamos beta on a zotac-sn970
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

When trying to play videos fullscreen from any website the browser stops rendering ("frozen") but audio continues. The screen freezes with the bar still on top.
Sites that don't work: youtube, netflix, any local html with mp4, and then press fullscreen.
After fullscreen, going back to not (with the bar on top), that specific "window" will not render. I can open a new "tab" and play videos, and switch back, but when I switch back, I get the same frozen window back.
The tab cannot be used anymore, and needs to be closed.

So it sounds to me the render of that page has crashed, but the remainder of the system doesn't know this, and continues interacting and playing.

**Comment by dubigrasu** [comment]
I can confirm this behavior on my SteamOS installation, Youtube and Netflix both hang in fullscreen mode. 
Is not only a SteamOS (or steamcompmgr) issue though, I tested this also on Ubuntu with both AMD and Nvidia cards with BPM started from the desktop client.
This happens with the current beta build as of Jan 25 2018. The stable build ( Dec 15 2017) does not present this issue.

**Comment by dubigrasu** [comment]
This issue seems to be fixed (for me) with the latest beta update.

**Comment by kisak-valve** [comment]
@ardje, can you retest with the current beta as well?

**Comment by ardje** [comment]
Thanks guys! I haven't seen that update(work), but I saw it in my github notifications...
The new beta indeed works. I took the most problematic provider and pushed fullscreen and I got fullscreen.
So:
Netflix: works.
Youtube: works.
Hidive: works.
Plain .mp4 served over http: works.
