### ISSUE TITLE
Debian Testing removed libva.1.so

### ISSUE THREAD

**Issue by kupschke** [ValveSoftware/steam-for-linux#5360]
#### Your system information

* Steam client version (build number or date):  Jan 25 2018, at 21:25:07
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I cant start steam with STEAM_RUNTIME=0 steam anymore:
~$ STEAM_RUNTIME=0 steam
Running Steam on debian  64-bit
STEAM_RUNTIME is disabled by the user
Error: You are missing the following 32-bit libraries, and Steam may not run:
libva.so.1
libva.so.1
libva-x11.so.1

On debian testing only those libva libraries are available:

~$ dpkg -l | grep libva
ii  libva-drm2:amd64                              2.0.0-2                             amd64        Video Acceleration (VA) API for Linux -- DRM runtime
ii  libva-drm2:i386                               2.0.0-2                             i386         Video Acceleration (VA) API for Linux -- DRM runtime
ii  libva-glx2:amd64                              2.0.0-2                             amd64        Video Acceleration (VA) API for Linux -- GLX runtime
ii  libva-glx2:i386                               2.0.0-2                             i386         Video Acceleration (VA) API for Linux -- GLX runtime
ii  libva-wayland2:amd64                          2.0.0-2                             amd64        Video Acceleration (VA) API for Linux -- Wayland runtime
ii  libva-x11-2:amd64                             2.0.0-2                             amd64        Video Acceleration (VA) API for Linux -- X11 runtime
ii  libva-x11-2:i386                              2.0.0-2                             i386         Video Acceleration (VA) API for Linux -- X11 runtime
ii  libva2:amd64                                  2.0.0-2                             amd64        Video Acceleration (VA) API for Linux -- runtime
ii  libva2:i386                                   2.0.0-2                             i386         Video Acceleration (VA) API for Linux -- runtime

#### Steps for reproducing this issue:

1. Install debian testing
2. Install steam
3. Start steam with STEAM_RUNTIME=0

**Comment by kisak-valve** [comment]
Hello @kupschke, the libva ABI bump is already being tracked at #5339. Feel free to add your experience to the existing issue report.

Closing as a duplicate.
