### ISSUE TITLE
Errors in default skin

### ISSUE THREAD

**Issue by Matombo** [ValveSoftware/steam-for-linux#5363]
#### Your system information

* Steam client version (build number or date): Jan 25 2018
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The default skin of Steam for linux has 2 small issues since i can remember:
- In the main menu (with shop library etc.), when your nick contains an A the is not enoth spacing for it so a little bit of the letter gets cut of.
- in the settings menu->In-Home-Straming the activate streaming checkbox and set pin button slips under the selection list above

**Comment by kisak-valve** [comment]
Hello @Matombo, the kerning issue is being tracked at #3057 and the streaming settings issue is being tracked at #4013 / #3685.

Closing as a duplicate.
