### ISSUE TITLE
Recent steam update stopped recognising nfs drive space. 

### ISSUE THREAD

**Issue by Phalen** [ValveSoftware/steam-for-linux#5364]
Ubuntu 16.04 multiple installs 4.13 and 4.14 kernel
steam api v017 package versions 1513371133
beta no change. 
just after the holidays a new client came out and broke the nfs mount support again.  Please add an option to make steam ignore disk space on 2ndary library folders as a check able option for those of us with drive mounts.  I have had nfs shares holding steam games for close to 8 years now its an important feature that breaks from time to time with the client updates.

**Comment by kisak-valve** [comment]
Hello @Phalen, this issue is already being tracked at #4952. Closing as a duplicate.
