### ISSUE TITLE
Hardware survey crash

### ISSUE THREAD

**Issue by brimston3** [ValveSoftware/steam-for-linux#5367]
#### Your system information

* Steam client version (build number or date): 1513371133
* Distribution (e.g. Ubuntu): debian 9
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam application completely crashs after clicking "next" to participate in the hardware survey. It exits with an assert message:

```
oculus3:~% steam -tcp
Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-02-03 09:37:51] Startup - updater built Dec 15 2017 11:47:44
[2018-02-03 09:37:51] Verifying installation...
[2018-02-03 09:37:51] Verification complete
Refresh rate: 0
[...more refresh rate lines...]
Refresh rate: 1
../common/pipes.cpp (766) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
../common/pipes.cpp (766) : Fatal assert failed: ../common/pipes.cpp, line 766.  Application exiting.

_ExitOnFatalAssert
```
[.steam/error.log](https://gist.github.com/brimston3/82c31d9dd3f3154d292f7696d15b83ff)

#### Steps for reproducing this issue:

1. start steam
2. receive hw survey dialog (opt in radio already selected)
3. click next in survey opt-in dialog
4. briefly see next window before dialog and steam application close.

Possibly related to #4964.

**Comment by kisak-valve** [comment]
Hello @brimston3, are you still experiencing this issue on an up to date system?

**Comment by brimston3** [comment]
@kisak-valve I've not received a hardware survey request in a while, or it went through to my windows-side client. The machine is deb10 now; I will update this issue when/if I get another hw survey.

**Comment by kisak-valve** [comment]
Closing pending confirmation this is still an active issue.
