### ISSUE TITLE
Meu Steam no Linux não salva as configurações

### ISSUE THREAD

**Issue by klebes** [ValveSoftware/steam-for-linux#5369]
#### Your system information
Operating System Version:
    Debian GNU/Linux 8.7 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  Openbox
  

Toda vez que abro o aplicativo da Steam vejo logo que a linguagem e as configs do aplicativo não foram salvas, percebi que este erro acontece neste aplicativo refrente ao linux pois tenho dois computadores com o mesmo sistema Linux Debian 8 estable,

**Comment by kisak-valve** [comment]
Hello @klebes, this issue is already being tracked at #5060. Closing as a duplicate.
