### ISSUE TITLE
Unusual texture in CS:GO

### ISSUE THREAD

**Issue by xyproto** [ValveSoftware/steam-for-linux#5370]
#### Your system information

* Steam client version (build number or date): Jan 25 2018, at 21:25:07
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Nvidia driver version: 390.25 (also for the `lib32-*nvidia*` packages)
* Graphics card: `01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)`

#### Please describe your issue in as much detail as possible:

CS:GO works great, but the lamp textures in Dust II looks odd:

![lamp_texture](https://user-images.githubusercontent.com/52813/35819904-f3499dd8-0a58-11e8-930a-df74d700ecaf.jpg)

Steam support sent me here.

#### Steps for reproducing this issue:

1. Start CS:GO.
2. Play the Dust II level.
3. Notice the unusual looking lamp texture close to the terrorist spawn point.

**Comment by kisak-valve** [comment]
Hello @xyproto, let's track this issue in the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1605.
