### ISSUE TITLE
My 4K notebook is so small that it hurts my eyes.

### ISSUE THREAD

**Issue by iyagicom** [ValveSoftware/steam-for-linux#5371]
#### Your system information

* Steam client version (build number or date): 1513371133 , It is inconvenient because it is not copied.
* Distribution (e.g. Ubuntu): Ubuntu 17.10 wayland
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. I am using the Dell 7559 4K UHD (3840x2160) notebook.
Steam client is too small to see.
My eyes are going to fall.
I do not see a change to the 2X or 3X resolution setting.

I want the browser letter size of the screenshot.

![2018-01-29 09-53-46](https://user-images.githubusercontent.com/15052400/35840731-69a13ed6-0b3b-11e8-8c32-d7d0618cbf3c.png)

**Comment by Plagman** [comment]
Can you try opting into the client Beta?

**Comment by iyagicom** [comment]
Beta client available
Where do I download it?

**Comment by Plagman** [comment]
You can follow the steps there: http://steamcommunity.com/sharedfiles/filedetails/?id=182912431

**Comment by iyagicom** [comment]
Version 1516948201 looks very good.
It seems to have brought the Ubuntu size settings well.
Thank you very much.

**Comment by kisak-valve** [comment]
Hello @iyagicom, thanks for confirming this is the same issue being tracked at #3492.

Closing in favor of the existing issue report.

**Comment by iyagicom** [comment]
I'm sorry. It was not wayland that I tested.
I did not know that installing nvidia proprietary drives automatically changed to x11.
I tested it on x11.
nvidia only runs on x11.

I switched to the x.org server xserver-xorg-nouveau
I tested again with wayland.

Nothing works in wayland.
Steam Launcher, Steam Game does not work at all.
The window does not open.
