### ISSUE TITLE
Error Code 6 on the 2nd page when creating a steam guide from the steam app (not browser)

### ISSUE THREAD

**Issue by Castanietzsche** [ValveSoftware/steam-for-linux#5376]
#### Your system information

* Steam client version : 15/2017, v017, package 1513371133
* Distribution : Ubuntu 16.04.3 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
II'm wanting to write a Steam guide for a game called Yomi.

All went ok for the first page : I wrote a title, I selected a picture (.jpg, 195*195px), I wrote a description and selected two categories (character and multiplayer) and a language (French).

However, when going to the second page, I had Error Code 6.
Here is the screen : http://www.noelshack.com/2018-06-3-1518009743-steamerreur6.jpg

The stats_log.txt says me :
```
[2018-02-07 13:31:31] [AppID 219890] Schema not found on disk
[2018-02-07 13:31:32] [AppID 219890] CAPIJobRequestUserStats - received error 'Failure' (2) from server
```
#### Steps for reproducing this issue:

1. Log In into Steam App, on Library right click onto a game, right click onto View Community Guides
2. On the right : Create Guide
3. Begin to create a guide with a title, a picture, details, category, language, etc. don't forget to tick the box for being the only author of the content.
4. On the bottom of the page : click on "Save and continue"
6. Experience issue as shown on my screenshot :
![steamerreur6](https://user-images.githubusercontent.com/36243760/35939016-2e7b2c02-0c4b-11e8-9dbc-9e221686cb97.jpg)

(I installed Steam with the Ubuntu deposit instead of the .deb package found of the official site (because used to have dbus errors before).)

**Comment by kisak-valve** [comment]
Hello @Castanietzsche, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
