### ISSUE TITLE
[SOLVED] Steam Doesn't Start in Ubuntu

### ISSUE THREAD

**Issue by Thatguy1114** [ValveSoftware/steam-for-linux#5381]
#### Your system information

* Steam client version (build number or date): The Most Recent One
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
So, I installed steam and it went just fine. Up until I needed to properly start it. Running it from the terminal I get this: [*Terminal*](https://gist.github.com/Thatguy1114/204c707098e154ef9d5d611dff8dfb45)

#### Steps for reproducing this issue:

1. Install Steam from the terminal in the official repositories.
2. Start Steam from the Terminal
3. Kablam!

**Comment by Thatguy1114** [comment]
"Turn it off and on again" or "Uninstall and reinstall" worked.

**Comment by kisak-valve** [comment]
Sounds like something went wrong bootstrapping steam (truncated download?). An alternative would have been to run `steam --reset` in a terminal.

In any case, glad to hear you got it working. Closing.
