### ISSUE TITLE
Can't install on Linux Mint 18.3 XFCE

### ISSUE THREAD

**Issue by LikoV2** [ValveSoftware/steam-for-linux#5382]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Linux Mint 18.3 XFCE
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Tried to install Steam, went well with gdebi. Then, Steam tried to install libgl1-mesa-dri:i386, libgl1-mesa-glx:i386 and libc6:i386:

![image](https://user-images.githubusercontent.com/34651209/36144365-1df4929e-10ae-11e8-8a1d-fccd45eb48e0.png)

Tried a sudo apt-get update:
```

Reading package lists... Done 
W: The repository 'http://repo.steampowered.com/steam precise Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://repo.steampowered.com/steam/dists/precise/steam/source/Sources  503  Service Unavailable [IP: 195.167.195.42 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by kisak-valve** [comment]
Hello @LikoV2, the server-sided 503 error code shouldn't block apt from adding 32 bit mesa and glibc.

What's the output of `sudo apt install libgl1-mesa-glx libgl1-mesa-glx:i386`?

**Comment by LikoV2** [comment]
Hello @kisak-valve, thanks for your answer.

The installation fails every time with `E: Unable to correct problems, you have held broken packages.`

**Comment by kisak-valve** [comment]
Can you post your /etc/apt/sources.list and `apt policy libgl1-mesa-glx libgl1-mesa-glx:i386`. Something's not healthy and it's outside of steam. What we're looking for is for the 32 bit and 64 bit variants to have the same version available.

**Comment by LikoV2** [comment]
```
cat /etc/apt/sources.list
# #deb cdrom:[Linux Mint 18.3 _Sylvia_ - Release amd64 20171213]/ xenial contrib main non-free
```

```
apt policy libgl1-mesa-glx libgl1-mesa-glx:i386
libgl1-mesa-glx:
  Installed: 17.0.7-0ubuntu0.16.04.2
  Candidate: 17.0.7-0ubuntu0.16.04.2
  Version table:
 *** 17.0.7-0ubuntu0.16.04.2 100
        100 /var/lib/dpkg/status
     12.0.6-0ubuntu0.16.04.1 500
        500 http://ftp.oleane.net/ubuntu xenial-updates/main amd64 Packages
     11.2.0-1ubuntu2 500
        500 http://ftp.oleane.net/ubuntu xenial/main amd64 Packages
libgl1-mesa-glx:i386:
  Installed: (none)
  Candidate: 12.0.6-0ubuntu0.16.04.1
  Version table:
     12.0.6-0ubuntu0.16.04.1 500
        500 http://ftp.oleane.net/ubuntu xenial-updates/main i386 Packages
     11.2.0-1ubuntu2 500
        500 http://ftp.oleane.net/ubuntu xenial/main i386 Packages
```
```
cat /etc/apt/sources.list.d/steam.list 
deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
deb-src [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
```

**Comment by kisak-valve** [comment]
That spells out the issue pretty clearly. For 64 bit, mesa 17.0.7 is installed with no update source, and there's no source for apt to match it with 32 bit.

I suspect http://ftp.oleane.net/ is a bad package mirror, give a different mirror a try.

**Comment by LikoV2** [comment]
It worked perfectly, thanks a lot for your help.

I'm sorry if it was obvious, I didn't know where to look for. From now on I will know, thanks again.
