### ISSUE TITLE
Bootstrapper does not work with ZFS

### ISSUE THREAD

**Issue by ashkitten** [ValveSoftware/steam-for-linux#5384]
#### Your system information

* Steam client version (build number or date): N/A
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] N/A
* Have you checked for system updates?: [Yes/No] Yes

Extra info:
Using a ZFS dataset for my `/home`, and EXT4 for `/`
ZFS is using 2 8TB hard drives in a mirrored pair

#### Please describe your issue in as much detail as possible:

When running `steam` initially, it is unable to determine the amount of free disk space in the filesystem in order to install the client, and opens a message window that says `Fatal Error: Steam needs at least 250MB of free disk space to update.`

I was able to get it to install by creating an EXT4 zvol and linking `.steam` and `.local/share/Steam` to directories in the EXT4 volume. After it was installed, I was able to move the directories back to ZFS and Steam worked fine.

Steam log: https://ptpb.pw/sD_E

#### Steps for reproducing this issue:

1. Create and mount a ZFS dataset in the home directory
2. Run `steam`

**Comment by kisak-valve** [comment]
Hello @ashkitten, this issue is already being tracked at #4982. Closing as a duplicate.

**Comment by ashkitten** [comment]
Apologies, I thought it was a different issue but setting a quota worked.
