### ISSUE TITLE
High CPU usage when hovering over achievments

### ISSUE THREAD

**Issue by dindybutts** [ValveSoftware/steam-for-linux#5386]
#### Your system information

* Steam client version (build number or date): 1513371133
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expected to read achievment names, I got extreme system lag.

![gif of the bug in action.](https://i.imgur.com/M2uC65W.gif)

#### Steps for reproducing this issue:

1. Open "Activity"
2. Move mouse over multiple achievments
3. Bask in the warmth provided by the high CPU usage

**Comment by kisak-valve** [comment]
Hello @dindybutts, since this issue report was opened, Steam enabled GPU accelerated rendering in web views, which should have helped. Are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
