### ISSUE TITLE
Support Ticket Menu Crashes Client

### ISSUE THREAD

**Issue by tuxdelux** [ValveSoftware/steam-for-linux#5388]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 16.04.3 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Using the support ticket menu, Help -> Steam Support -> Steam Client -> Steam Client Crashes -> Contact Steam Support , will cause the steam client to crash when Step 1 checkbox is used. 
" OK, I agree to including the required information (required) "
Obviously, this prevents this bug from being reported.
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by h1z1** [comment]
Does system info crash too?   Curious because I get the same on both.

**Comment by kisak-valve** [comment]
Hello @tuxdelux, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
