### ISSUE TITLE
Steam depends on libgl1-mesa-glx:i386, but it removes nvidia-340

### ISSUE THREAD

**Issue by MoofMonkey** [ValveSoftware/steam-for-linux#5390]
#### Your system information

* Steam client version (build number): 1513371133
* Distribution: Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam depends on libgl1-mesa-glx:i386, but it removes nvidia-340
Without libgl1-mesa-glx:i386 steam can't launch farther than "Connecting to account"/login form.

#### Steps for reproducing this issue:

1. Download latest steam package from [steampowered.com](http://store.steampowered.com/about/)
2. Install it
3. Launch steam, it'll show up you that it wants libgl1-mesa-glx:i386 to be installed, BUT it will remove nvidia-340
[Logs (proof)](https://pastebin.com/9SATkNV1)
[Sysinfo](https://pastebin.com/LrcJ4vks)

**Comment by kisak-valve** [comment]
Hello @MoofMonkey, do you have the nvidia-340:i386 package installed? If not, that's most likely the reason why steam is not starting.

Does `sudo apt install libgl1-mesa-glx libgl1-mesa-glx:i386` want to add mesa without trying to remove nvidia-340?

**Comment by kisak-valve** [comment]
Hello @MoofMonkey, did you figure out what was happening here? Looking over this again, it looks like the nvidia 340.xx is not compatible with libglvnd, which is historically true.

The Steam client doesn't actually care that these packages are installed, just that its given a sane and working OpenGL driver stack (with a 32 bit and 64 bit userspace) and libc, so these packages could be ignored on your system.

**Comment by MoofMonkey** [comment]
> Hello @MoofMonkey, did you figure out what was happening here? Looking over this again, it looks like the nvidia 340.xx is not compatible with libglvnd, which is historically true.

To be honest - no, I do not remember what I did, but it worked somehow for sure.
I don't think that I can bring old hardware to test that issue, but if I will - I think I'll write here.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing per the last comment.
