### ISSUE TITLE
Steam launcher interferes with gameplay.

### ISSUE THREAD

**Issue by iyagicom** [ValveSoftware/steam-for-linux#5393]
#### Your system information

* Steam client version (build number or date): 1568661534
* Distribution (e.g. Ubuntu): 17.10 Nvidia 384.111
* Opted into Steam client beta?: [Yes/No]y
* Have you checked for system updates?: [Yes/No]y
[vokoscreen-2018-02-18_15-30-37.zip](https://github.com/ValveSoftware/steam-for-linux/files/1734511/vokoscreen-2018-02-18_15-30-37.zip)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. I failed to download the expansion map.
I can not play after that.
The launcher runs and interrupts.
When I play a game, I usually change it to FHD.

2. 컴퓨터 정보:
    제조업체: Unknown
    모델: Unknown
    형식 요소: notebook
    No touch input detected. <-- My dell 7559 is a 4K touchpad.

프로세서 정보:
    CPU 공급업체: GenuineIntel
    CPU 브랜드: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    CPU 제품군: 0x6
    CPU 모델: 0x5e
    CPU 스테핑: 0x3
    CPU 종류: 0x0
    속도: 3500Mhz
    8 논리 프로세서
    4 실제 프로세서
    하이퍼스레딩:  support
    FCMOV:  support
    SSE2:  support
    SSE3:  support
    SSSE3:  support
    SSE4a:  Not support
    SSE41:  support
    SSE42:  support
    AES: support
    AVX: support
    CMPXCHG16B: support
    LAHF/SAHF: support
    PrefetchW: Not support

운영체제 버전:
    Ubuntu 17.10(64비트)
    커널 이름: Linux
    커널 버전: 4.13.0-32-generic
    X Server 공급업체: The X.Org Foundation
    X Server 릴리스: 11905000
    X Window 관리자: GNOME Shell
    Steam 런타임 버전: steam-runtime-beta-release_2017-10-05

비디오 카드:
    드라이버:  NVIDIA Corporation GeForce GTX 960M/PCIe/SSE2
    드라이버 버전: 4.5.0 NVIDIA 384.111
    OpenGL 버전: 4.5
    데스크톱 색상: 픽셀당 24bit
    모니터 화면 주사율: 60Hz
    공급업체 ID: 0x10de
    장치 ID: 0x139b
    수정이 검색되지 않았습니다.
    모니터 개수: 1
    논리적 비디오 카드 개수: 1
    기본 디스플레이 해상도: 3840 x 2160
    데스크톱 해상도: 3840 x 2160
    기본 디스플레이 크기: 13.54" x 7.64" (15.51" diag)
 34.4cm x 19.4cm (39.4cm diag)
    기본 버스: PCI Express 16x
    기본 VRAM: 4096MB
    지원되는 MSAA 모드: 2x 4x 8x 16x 

사운드 카드:
    오디오 장치: Realtek ALC3246

메모리:
    RAM:  15785Mb

기타:
    UI 언어:  한국어 (Korean)
    언어: ko_KR.UTF-8
    총 하드 디스크 여유 공간:  382460 Mb
    최고 여유 하드 디스크 블록:  42636 Mb
    VR 헤드셋: 검색 결과 없음

최근 실패 보고서:

**Comment by iyagicom** [comment]
APK "The island" is replaced and played.
The expansion map is still not clicked.

**Comment by kisak-valve** [comment]
Hello @iyagicom, you may want to let the game's devs know about this.

**Comment by kisak-valve** [comment]
Hello @iyagicom, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
