### ISSUE TITLE
Steam client crash on launch in Ubuntu 18.04

### ISSUE THREAD

**Issue by StenPett** [ValveSoftware/steam-for-linux#5397]
#### Your system information

* Steam client version (build number or date): Feb 23 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever I try to launch Steam, it crashes right after verifying the installed version. No error messages of any kind. I get the following output when I run steam from the CLI:

https://gist.github.com/StenPett/16a16375afcccac1bece085c768083dc

Here's the contents of my error.log file:
https://gist.github.com/StenPett/257708c660daff5034511e64678c430a

Here's the contents of my bootstrap_log.txt file:
https://gist.github.com/StenPett/a9bfd848803b29ab944fb9d175560167

#### Steps for reproducing this issue:

1. Launch Steam
2. -
3. -

**Comment by kisak-valve** [comment]
Hello @StenPett, can you check if your 32 bit opengl driver is healthy? The 32 bit `glxinfo` from `mesa-utils:i386` should be sufficient to use as a test.

**Comment by StenPett** [comment]
@kisak-valve Unfortunately, I had an HDD failure an hour ago, and had to do a complete system reinstall (luckily, I had /home on a separate disk). I have just finished installing 16.04, and here, Steam works like it should.

**Comment by kisak-valve** [comment]
Closing per the last comment.
