### ISSUE TITLE
Unable to change timezone in Big Picture Mode

### ISSUE THREAD

**Issue by ncoder-1** [ValveSoftware/steam-for-linux#5399]
#### Your system information

* Steam client version (build number or date): Dec 15 2017
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I am unable to change the timezone in Big Picture Mode.  It stays at UTC-8 PST despite me clicking on my actual timezone.  In small picture mode it is working fine and time is right in small picture mode's chat.  I am not using a VPN.  System time is accurate and NTP'd.

EDIT:  It also changes my `/etc/localtime` symbolic link on its own to `/usr/share/zoneinfo/America/Los Angeles ` without asking.

#### Steps for reproducing this issue:

1. Try to change timezone in Big Picture Mode.
2. 
3.

**Comment by Shished** [comment]
Sorry for necroposting but this problem is still not fixed. I'm also using Arch Linux.

**Comment by kisak-valve** [comment]
Hello @ncoder-1, @Shished, are you still experiencing this issue on an up to date system? This setting may have been phased out for desktop Linux users.

**Comment by ncoder-1** [comment]
Hi, no, the issue is resolved. Thanks!
