### ISSUE TITLE
RocketLeague invite from friend causing steam client to crash

### ISSUE THREAD

**Issue by trinitronx** [ValveSoftware/steam-for-linux#5401]
#### Your system information

* Steam client version (build number or date): `1513371133`
* Distribution (e.g. Ubuntu): `ubuntu 17.10 64-bit`
* Opted into Steam client beta?: `Yes` ( I tried first without beta, then opt-in to beta and tested with same result)
* Have you checked for system updates?: `Yes`

#### Please describe your issue in as much detail as possible:

After having a friend on steam send a RocketLeague game invite, steam client abruptly crashes!

Problem is 100% reproducible, and happens whether or not the game has been launched first or not.  I tested first multiple times without steam beta client, then changed the beta opt-in setting on, restarted steam, and it downloaded beta client.  Beta client still suffers from the issue.  Seems to be an issue only on the receiver end of a game invite from Linux client.  The friend was using steam client on Windows.

We tested multiple times and the crash happened each time on invite receiver end (my system).  When I sent an invite to my friend (sender was my Linux client, receiver was Windows client), it worked and his client did not crash.  We were then able to play RocketLeague in a party without troubles.

#### Steps for reproducing this issue:

1. Start steam Linux client & login
2. Friend running Windows steam client sends game invite (for RocketLeague, we didn't test other games)
3. Steam Linux client crashes!

System info:

[sysinfo.txt](https://gist.github.com/trinitronx/ab8a7facc8e7423de7d36b20ace1595b)

`steam` console reveals updater version:

```
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-03-02 21:39:07] Startup - updater built Dec 15 2017 11:47:4
```

Tested with:
Non-beta client: steam installed version: `1513371133`
Beta client version: `1519863247` (`Built Feb 28 2018, at 15:31:57`, Steam API: `v018`)

Crash dumps attached:

- For steam `1513371133`: [rl-crashdumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/1777109/rl-crashdumps.tar.gz)
- For steam beta `1519863247`: 
[rl-crashdumps-steam-beta-1519863247.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/1778809/rl-crashdumps-steam-beta-1519863247.tar.gz)

**Comment by trinitronx** [comment]
Just looked in JournalD logs (`journalctl -xn10000`), and see the crash segfault info there:

```
Mar 03 18:15:17 saturn crash_20180303015106_2.dmp[10882]: Uploading dump (out-of-process)
                                                          /tmp/dumps/crash_20180303015106_2.dmp
Mar 03 18:15:17 saturn kernel: gameoverlayui[17430]: segfault at 0 ip 00000000f01a040b sp 00000000ffa22ff0 error 4 in vgui2_s.so[f011a000+290000]
Mar 03 18:15:17 saturn crash_20180303015106_2.dmp[10882]: Finished uploading minidump (out-of-process): success = yes
Mar 03 18:15:17 saturn crash_20180303015106_2.dmp[10882]: response: Discarded=1
Mar 03 18:15:17 saturn crash_20180303015106_2.dmp[10882]: file ''/tmp/dumps/crash_20180303015106_2.dmp'', upload yes: ''Discarded=1
```

**Comment by kisak-valve** [comment]
For reference, the newer attached minidump is a SIGSEGV in vgui2_s.so.

**Comment by kisak-valve** [comment]
Hello @trinitronx, are you still experiencing this issue on an up to date system?

**Comment by trinitronx** [comment]
I just upgraded to Ubuntu 20.04 recently, but haven't tried to play Steam games yet.  I'll have to re-test after getting `xpad` drivers recompiled and installed for this kernel again.  Once I have some free time, and have everything set up again, I can check

**Comment by kisak-valve** [comment]
Closing pending feedback.
