### ISSUE TITLE
64bit ONLY client pls

### ISSUE THREAD

**Issue by TriMoon** [ValveSoftware/steam-for-linux#5405]
#### Your system information

* Steam client version (build number or date):  none at moment
* Distribution (e.g. Ubuntu):  Debian 9.4
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
I have read #5324 and #179, but this issue is different...
I understand that there are many 32bit games you want to keep supporting BUT:
There are people like me who want to stay pure 64bit.

So please provide a 64bit ONLY steam, with a filter that will only show 64bit games in it's listing.
I refuse to install 32bit crap in my 64bit system thank you...

Don't Close this issue to prevent it getting posted over and over again by many others...

**Comment by kisak-valve** [comment]
Hello @TriMoon, a feature request for a purely 64 bit client is already being tracked at #3518.

As for duplicates, those are inevitable because all of the search terms for this are very common and overlap with basic information requested for troubleshooting.

Closing in favor of the existing feature request.

**Comment by TriMoon** [comment]
I'm not using Centos, but **Debian**, if you make it work on debian it will work on **many** other distributions that are derived from debian....
Make this thread a tracker for DEBIAN...

**Comment by blackPantherOS** [comment]
The Valve has announced "does not support 32bit platfrom" around 2 years ago, but the Steam framwork runs only with 32bit components?! WTF? If you does not support 32bit, I accept, but you dont ask me, we support your 32bit client.

The Steam (32bit) support is paused on blackPanther OS for native 64bit Steam client releasing  by Valve. I advise for any distro developers too.

Existing any other prider as well, like GOG, etc.

**Comment by TriMoon** [comment]
> Hello @TriMoon, a feature request for a purely 64 bit client is already being tracked at #3518.
> 
> As for duplicates, those are inevitable because all of the search terms for this are very common and overlap with basic information requested for troubleshooting.
> 
> Closing in favor of the existing feature request.

https://github.com/ValveSoftware/steam-for-linux/issues/5342#issuecomment-358160158
Thats said please provide 2 distributions then, one that is able to run **32-Bit games ONLY** and one that is able to run **64-Bit games ONLY**.

What would you think people would say if you added 64-bit support, and force them install needed 64-bit stuff, in a 32-bit client because it needs to be able to run both type of games? o.O
Yes im still kicking the ones in charge untill people are not forced to multi-architecture...
