### ISSUE TITLE
Dota 2 froze

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#5407]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-3
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Dota 2 froze. I have a truncated core dump, ~700 mb compressed. Let me know if it can be uploaded somewhere for evaluation.

#### Steps for reproducing this issue:

1. Play Dota 2

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, let's track your issue in the Dota 2 issue tracker at https://github.com/ValveSoftware/Dota-2/issues/1422.
