### ISSUE TITLE
Steam freezes computer after closing

### ISSUE THREAD

**Issue by LDD19** [ValveSoftware/steam-for-linux#5409]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.48-1ubuntu
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After trying to fix issue #474 by closing Steam my computer freezes for around 5 minutes. Background applications would stop working after a few seconds too. Nothing out of the ordinary happens in the console. The same issue happens when I try to force close the process in a task manager. However, if I managed to fix this issue by killing the steamwebhelper processes first before closing the Steam process. The lag is proportional to the time that I left Steam opened. This doesn't  happen if I try to close it after only a couple of hours. I think it might be an issue with Nvidia drivers or the fact that I'm using multiple disks to store my games. 

#### Steps for reproducing this issue:

1.  Leave Steam opened for a 12+ hours
2. Play a game
3. Close Steam after resuming from suspend.

**Comment by kisak-valve** [comment]
Hello @LDD19, this issue is already being tracked at #5279. Feel free to add your experience to the existing issue report.

Closing as a duplicate.
