### ISSUE TITLE
tar "Unterminated quoted string" error when launching Steam

### ISSUE THREAD

**Issue by icegt95** [ValveSoftware/steam-for-linux#5410]
#### Your system information

* Steam client version (build number or date): Latest .deb
* Distribution (e.g. Ubuntu): Debian 9.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I went to open Steam this morning after having it work flawlessly for 3 months, and I received the following output in terminal:

```
tim@tim-desktop:~$ steam

Setting up Steam content in /home/tim/.local/share/Steam
/usr/bin/xz: 5: /usr/bin/xz: Syntax error: Unterminated quoted string
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to extract /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz, aborting installation.
```

I'm getting the same error after completely removing, purging, and reinstalling from the .deb.

#### Steps for reproducing this issue:

1. Launch Steam

**Comment by icegt95** [comment]
Update - not sure now if this was a one-off on my end, but I've managed to fix the issue by removing and reinstalling xz-utils.

**Comment by kisak-valve** [comment]
Glad to hear you got it working. Closing per the last comment.
