### ISSUE TITLE
Spontaneously crashing

### ISSUE THREAD

**Issue by LillyWho** [ValveSoftware/steam-for-linux#5411]
#### Your system information

* Steam client version (build number or date): 15 Mar 2018
* Distribution (e.g. Ubuntu): SteamOS Brewmaster latest & Ubuntu 18.04
* Opted into Steam client beta?: Y & N (Makes no difference)
* Have you checked for system updates?: Yes, via internal SteamOS update and apt update

#### Please describe your issue in as much detail as possible:
The Steam client likes to randomly crash while just being idle or downloading a game. It's usable for a couple of minutes but sometimes it restarts only about two minutes in. Same thing happens on Ubuntu, logs for Ubuntu will follow later.

#### Steps for reproducing this issue:

1. Start Steam
2. Leave it running
3. Watch it restart over and over

Steam stdout:
https://gist.github.com/Alexandroid99/0a0a559f45c534ae495839112d53d939

**Comment by Alexandroid99** [comment]
Log for Ubuntu 18.04: https://gist.github.com/Alexandroid99/be118eb8ed7d3ca6392ee4b6e4036da4

**Comment by kisak-valve** [comment]
Hello @LillyWho, are you still experiencing this issue on an up to date system?

**Comment by LillyWho** [comment]
I have since abandoned running on Linux so I cannot tell

**Comment by kisak-valve** [comment]
Thanks for the feedback at least.

**Comment by LillyWho** [comment]
(Well I stopped using it in part because the bug was making it unpractical and I never got any engagement out of this issue. So I guess that's some further feedback for you. 😅❤️)
