### ISSUE TITLE
[First Run] License agreement does not run in Big Picture UI

### ISSUE THREAD

**Issue by flibitijibibo** [ValveSoftware/steam-for-linux#5413]
#### Your system information

* Steam client version (build number or date): Mar 19 2018 11:59:58
* Distribution (e.g. Ubuntu): Fedora 27 x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When installing `steamos-session` on Fedora, the initial run of Steam will pop up either a `zenity` window or an `xterm` session to provide the license agreement for Steam. However, for some reason steamcompmgr does not like either of these windows, so you just get a black screen until you kill the process and it eventually bails on the session entirely.

This is _kind of_ a steamcompmgr bug, but as it turns out the official SteamOS UX places the license agreement in Big Picture itself, using the CEF browser. It would be nice to have the `-tenfoot` or `-steamos` flag skip the license agreement code in the shell script and use Big Picture for the agreement instead, both improving the user experience and working around this pretty obscure bug.

#### Steps for reproducing this issue:

1. Write Fedora Workstation ISO to a USB drive
2. Boot LiveUSB, install with standard partition layout matching SteamOS'
3. Set root password, create 'desktop' user with whatever password
4. Reboot, log in as desktop
5. Update, reboot, blah blah blah
6. dnf config-manager --add-repo=https://negativo17.org/repos/fedora-steam.repo
7. dnf install steam steamos-session steamos-modeswitch-inhibitor.x86_64 steamos-modeswitch-inhibitor.i686 vulkan
8. setsebool -P allow_execheap 1
9. Reboot, log in as steam:steam (be sure to pick SteamOS as your session!)
10. Black screen!

In contrast...

9. Reboot, log in as steam:steam (be sure NOT to pick SteamOS as your session!)
10. Set up Steam as usual in desktop mode
11. Log out, log in as steam:steam (_now_ you can pick SteamOS as the session)
12. Should boot/run just fine!

**Comment by flibitijibibo** [comment]
This is a stupid idea, but a possible workaround would be to add the LD_PRELOAD gunk (and maybe the STEAM_GAME atom?) to `zenity` so that the window will show up in steamcompmgr. It's about as gorgeous as you would expect...

![dy_pdbmwkaiu7ax jpg large](https://user-images.githubusercontent.com/1396814/37843118-6babcfde-2e9a-11e8-919a-32161a2a55b1.jpeg)

... but it's better than a black screen!

**Comment by flibitijibibo** [comment]
Bumping this to CC @alkazar. Think we can fix this in your steamcompmgr branch? Updated repro steps if you need them:

https://plus.google.com/+flibitijibibo/posts/f11ZFpyUzob

**Comment by alkazar** [comment]
@flibitijibibo (that was hard) I will take a look. I would have expected the -steamos option to take care of this though. Is this still a problem?

**Comment by flibitijibibo** [comment]
I believe it still is, yes. I think we need special treatment for zenity for this to work, at least.

**Comment by alkazar** [comment]
@flibitijibibo I think this issue is fixed. I recently did an Arch based steamcompmgr only install with the `-steamos` option and was presented with the license agreement inside big picture with no problems. The whole thing worked very well!

**Comment by flibitijibibo** [comment]
This is indeed fixed by the latest update!
