### ISSUE TITLE
Ridiculous big size with the new steam client update on 4K 28" monitor

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#5414]
#### Your system information

* Steam client version (build number or date): 19/3/18
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
This new stable update blew out of proportions the scaling is so big!!! It's ridiculous on my 4k 28" monitor!
https://i.imgur.com/jJsY87F.png

#### Steps for reproducing this issue:

1. Just updated my steam client.

**Comment by kisak-valve** [comment]
Hello @ekaris, you can get the non-scaled behavior by running steam with the `GDK_SCALE=1` env variable set.

Closing in favor of the existing issue report at #5362.
