### ISSUE TITLE
Steam UI is huge on 4k monitor with latest Steam Beta update

### ISSUE THREAD

**Issue by nazar-pc** [ValveSoftware/steam-for-linux#5415]
#### Your system information

* Steam client version (build number or date): 1521502351
* Distribution:  Ubuntu 18.04 x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Latest Steam Beta update made Steam UI huge (about 4x I think) comparing to other apps.

Looks like you're trying to bring HiDPI support, but it is all about DPI, not resolution! Stop making it 4 times bigger on my 27'' monitor.

What makes things worse, there is no setting to fix this.

All other apps are working properly and X11 DPI is configured to be 96, so all my apps except Steam understand that.

#### Steps for reproducing this issue:

1. Ubuntu 18.04 + Steam beta
2. 3840x2610 27'' monitor (I use Philips 288P)
3. Start Steam

**Comment by kisak-valve** [comment]
Hello @nazar-pc, you can get the non-scaled behavior by running steam with the `GDK_SCALE=1` env variable set.

Closing in favor of the existing issue report at #5362.
