### ISSUE TITLE
Steam locks X11 when quitting or updating

### ISSUE THREAD

**Issue by Nidhoegger** [ValveSoftware/steam-for-linux#5418]
#### Your system information

* Steam client version (build number or date): Built: Mar 19 2018, at 12:02:23
* Distribution (e.g. Ubuntu): Debian Stretch and Debian Buster
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Full system infos: https://gist.github.com/Nidhoegger/9bc1fccc065a8d8fb0c1c57b2ebc8b4c

#### Please describe your issue in as much detail as possible:
When quitting steam (e.g. via Tray -> Quit, via System Shutdown or via Update Dialog (restart steam)) the X11 server locks completly. Only mouse is moveable. My suspicion is that you use X11 exclusive mode or start spamming the X11 server with commands (havent debugged it yet). Sometimes it will start working again after a couple of minutes, most of the time I need to switch to a VT and kill steam with SIGKILL.

What I expect: Steam will quit without blocking X11 completly.

#### Steps for reproducing this issue:

1. Have steam running
2. Press Quit
3. Profit

**Comment by Nidhoegger** [comment]
Also reproducible in Beta client (Built: Mar 22 2018, at 16:58:48)

**Comment by kisak-valve** [comment]
Hello @Nidhoegger, this issue is already being tracked at #5279. Closing as a duplicate.
