### ISSUE TITLE
Steam Overlay freezing games completly

### ISSUE THREAD

**Issue by Nidhoegger** [ValveSoftware/steam-for-linux#5419]
#### Your system information

    Steam client version (build number or date): Built: Mar 19 2018, at 12:02:23
    Distribution (e.g. Ubuntu): Debian Stretch and Debian Buster
    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes

Full system infos: https://gist.github.com/Nidhoegger/9bc1fccc065a8d8fb0c1c57b2ebc8b4c

#### Please describe your issue in as much detail as possible:
When using the steam overlay, it may freeze games completly. Only killing the game will fix the issue. I experience the bug very often when using the webbrowser and start scrolling too fast in a second tab. Sometimes also the MOTD on servers in DOD:S will freeze the game, so I suspect its webkit related.

#### Steps for reproducing this issue:

1. Start a game (in my case Day of Defeat: Source), open the overlay, open a browser and browse to a big homepage.
2. Start scrolling very fast
3. Maybe the overlay will freeze the entire game now.

**Comment by Nidhoegger** [comment]
Also reproducible in Beta client (Built: Mar 22 2018, at 16:58:48)

**Comment by kisak-valve** [comment]
Hello @Nidhoegger, this issue is already being tracked at #4933. Closing as a duplicate.
