### ISSUE TITLE
Random DOTA crashes straight to desktop (Ubuntu 16.04)

### ISSUE THREAD

**Issue by driebe** [ValveSoftware/steam-for-linux#5422]
First off: I post this bug here in the steam-for-linux section, because the official DOTA DEV forums can only be accessed with a beta key / steam verification which does not work for me (independent of the browser I use). So... Let' try this...

#### Your system information

* Steam client version (build number or date): Mar 22 2018, at 16:58:48 (package 1521764535)
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, system up to date
* Hardinfo can be found in the attached TXT file

Systems details can be found at the end of the post.

#### Please describe your issue in as much detail as possible:
Game crashes, supposedly at random, during normal or ranked DOTA matches. This could be analyzed in match with the ID 3797693691 (I was Crystal Maiden) played on March 24, 2018.

#### Steps for reproducing this issue:

1. As the crashes to desktop appear at random and neither the DOTA nor the Steam client returns a crash report, I cannot give an explanation on how to reproduce this error.

[Hardinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/1844473/Hardinfo.txt)

**Comment by hauntingEcho** [comment]
have you added this to [DOTA's bug tracker](https://github.com/ValveSoftware/Dota-2/issues) as well?

**Comment by driebe** [comment]
Will repost in the DOTA section...
