### ISSUE TITLE
2bwm breaks library access

### ISSUE THREAD

**Issue by M4R10zM0113R** [ValveSoftware/steam-for-linux#5424]
SOLUTION:
reset environment variables to allow steam to run normally. Partial fix is using sudo to reset the environment, through another user.

Attached verbose steam logs
[log_xinit.txt](https://github.com/ValveSoftware/steam-for-linux/files/1864396/log_xinit.txt)
[log_2bwm.txt](https://github.com/ValveSoftware/steam-for-linux/files/1864394/log_2bwm.txt)

#### Your system information

* Steam client version (build number or date): 
Mar 22 2018
* Distribution (e.g. Ubuntu): 
Gentoo
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:

a particular window manager (2bwm) breaks access to library when running steam
($HOME/.local/share/Steam)

Possibly associated with a _NET standard, given the WM covers little

Multiple casualties with using the same WM. (It would be a bummer to deem it unsolvable)

Running Steam with xinit doesn't have the issue.

#### Steps for reproducing this issue:
Particular steps have worked to run steam normally

0. Run 2bwm
1. Install steam
2. Remove problematic bundled library incompatibilities
$ find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete
To make steam even launch
3. Open steam
4. Settings>Downloads>Steam Library Folders button, dialogue gets stuck on "Searching", and adding any other location fails with "New Steam library folder must be on a filesystem mounted with execute permissions"

**Comment by M4R10zM0113R** [comment]
ext4

**Comment by M4R10zM0113R** [comment]
The issue arises when using 2bwm.

**Comment by kisak-valve** [comment]
Hello @M4R10zM0113R, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
