### ISSUE TITLE
Steam client update broke Half Life 2: Update game

### ISSUE THREAD

**Issue by CreamyCookie** [ValveSoftware/steam-for-linux#5425]
#### Your system information

* Steam client version (build number or date): 
 Steam Client Beta Update - March 23 

* Distribution (e.g. Ubuntu): 
Ubuntu 16.04 (up to date)

* Opted into Steam client beta?: [Yes/No]
Yes

* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Basically the game doesn't start anymore. 

This "quickfix" described by [UJC](https://steamcommunity.com/profiles/76561198060840847) did work:

> I had the same problem, Linux Mint 18 or so, the way I fixed it was to rename hl2_linux to hl2_linexe, hl2.sh to hl2_linux, and edit hl2_linux (formerly hl2.sh) to replace "hl2_linux" with "hl2_linexe." No library installation neccessary, at least for me.
> 
> To add a little more info to the mix: It seems that Steam is launching hl2_linux when it should be launching hl2.sh. As is apparent from OP's output, a library isn't getting loaded, this is due to hl2.sh setting the LD_LIBRARY_PATH to search in the game's bin/ directory, and since steam launches the executable directly the run-time linker doesn't know to look in bin/ to find the missing library. 

https://steamcommunity.com/app/290930/discussions/2/2549465882916976872/#c1620600279674449297

#### Steps for reproducing this issue:
Run [Half Life 2: Update](http://store.steampowered.com/app/290930/) on Linux.

**Comment by kisak-valve** [comment]
Hello @CreamyCookie, this looks like what gets [called to start the game](https://steamdb.info/app/290930/config/) should be adjusted by the game's dev. It's fairly obvious that the issue has already been brought to his attention as indicated by your pinned forum thread.

**Comment by CreamyCookie** [comment]
@kisak-valve Oh okay.. but isn't that still a bug with Steam if the game itself wasn't updated (I'm not aware of any updates) and worked before that Steam update?

**Comment by CreamyCookie** [comment]
Or am I missing something?

**Comment by kisak-valve** [comment]
Hello @CreamyCookie, are you still experiencing this issue on an up to date system? It looks like this was fixed last November.

**Comment by CreamyCookie** [comment]
@kisak-valve Don't have time atm to test this, so I'm closing this for now. If anyone experiences the same, feel free to to comment here and I'll reopen.

**Comment by teihome** [comment]
```
shared-library-guard active for /var/srv/games/steam_home/steamapps/common/Black Mesa/bms_linux
Blocked library /var/srv/games/steam_home/steamapps/common/Black Mesa/bin/libtcmalloc_minimal.so.4
/var/srv/games/steam_home/steamapps/common/Black Mesa/bms_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory
Game Recording - game stopped [gameid=362890]
```

**Comment by teihome** [comment]
for flatpak, I found this work around to be successful: https://github.com/flathub/com.valvesoftware.Steam/issues/1361#issuecomment-2699483277
