### ISSUE TITLE
Beta update 2018-03-26 broke HiDPI / GDK_SCALE=2

### ISSUE THREAD

**Issue by sorsasampo** [ValveSoftware/steam-for-linux#5427]
#### Your system information

* Steam client version (build number or date): Built Mar 26 2018, at 14:23:04. Steam API v018, Steam package versions 1522101301.
* Distribution (e.g. Ubuntu): Debian Stretch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

`GDK_SCALE=2` worked before this update. After it, the UI is back to unscaled.

#### Steps for reproducing this issue:

1. Enable Steam beta update.
2. Pass GDK_SCALE=2 to `steam`.
3. Observe.

**Comment by dubigrasu** [comment]
Have you enable this option from Steam settings?

**Comment by sorsasampo** [comment]
Now I have, and the HiDPI scaling is back to what it was:

- [x] Enlarge text and icons based on monitor size (requires restart)

I guess this is a new setting? Is `GDK_SCALE=2` now ignored?

Not sure how I feel about that, as `GDK_SCALE` is recognized by a lot of applications.

**Comment by dubigrasu** [comment]
New setting indeed. If is enabled from Steam settings,  GDK_SCALE will function and be recognized as before.

**Comment by vanyasem** [comment]
Unfortunately it never gets enabled for me. It gets back to unset for me after I restart Steam to "apply changes". HiDPI is completely broken for me

**Comment by vanyasem** [comment]
I am running Steam Native on Arch GNU/Linux x86_64

**Comment by vanyasem** [comment]
I am not participating in Steam Beta

**Comment by vanyasem** [comment]
Deleting `~/.steam` and re-logging in solved the issue for me

**Comment by lucasyvas** [comment]
I had it working fine with the GDK environment variable before, but now with the new toggle checked in the options it doesn't work at all. The environment variable is also ignored now :/

**Comment by kisak-valve** [comment]
The [2018-03-26](http://store.steampowered.com/news/38412/) Steam stable client update made this an opt-in feature as noted by @sorsasampo.

In addition to the checkbox in the settings, the `GDK_SCALE` env variable can be used to override the scaling logic.

Closing as the original issue has been resolved.
