### ISSUE TITLE
steam doesn't stay open in the background

### ISSUE THREAD

**Issue by raenii** [ValveSoftware/steam-for-linux#5433]
#### Your system information
* Steam client version (build number or date): latest as of april 5th
* Distribution (e.g. Ubuntu): pop!_os 17.10 (ubuntu 17.10 derivative)
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
when closing all the steam client windows, the entire steam process(es) stop running. this means i don't get any messages or other notifications and my games stop downloading until i open the client again.

#### Steps for reproducing this issue:
1. close all the windows produced by steam

**Comment by kisak-valve** [comment]
Hello @wave98, this reads like #2685. What method are you using to close steam's windows?

**Comment by wave98** [comment]
@kisak-valve the X in the top right.

**Comment by kisak-valve** [comment]
Hello @raenii, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
