### ISSUE TITLE
[Suggestion] Login directly into steam Big Picture + SteamOS compositor

### ISSUE THREAD

**Issue by lf-araujo** [ValveSoftware/steam-for-linux#5435]
#### Your system information

* Steam client version (build number or date): Apr 2 2018
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:

This is a suggestion for improvement.

Thank you for your software, it works very well under Ubuntu. My suggestion is that together with the SteamOS, Valve could permit the steam-for-linux to be shipped with SteamOS's compositor and window manager. A login option in Lightdm or GDM could be added to log into BigPicture+SteamOS compositor so the user would be able to have a more or less similar experience as a SteamOS in their laptops or desktops without the overhead of an underlying desktop environment.

All the best,

lf

**Comment by kisak-valve** [comment]
Hello @lf-araujo, the compositor is [MIT licensed](https://github.com/ValveSoftware/SteamOS/issues/610) and there shouldn't be a problem putting something together with your distro's package management.

However, the actual packaging for the compositor should be handled on a per-distro basis and should remain separate from the steam client. [This PPA](https://launchpad.net/%7Emdeslaur/+archive/ubuntu/steamos) or the documentation [here](https://github.com/ValveSoftware/SteamOS/wiki/steamcompmgr) looks like a good starting point for packaging on Ubuntu.
