### ISSUE TITLE
Steam stuck on "Connecting Steam Account"

### ISSUE THREAD

**Issue by PaymonJay** [ValveSoftware/steam-for-linux#5436]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-3
* Distribution (e.g. Ubuntu):  Antegros - 4.15.15-1-ARCH
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When Steam is launched, it gets stuck on `Connecting Steam account: accountname...`. Have tried multiple reinstalls, reboots, and changing system variables with no changes to behaviour.

Full terminal output:

    [user@localpc ~]$ steam
    /home/user/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
    /home/user/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
    Running Steam on antergos  64-bit
    /home/user/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
    STEAM_RUNTIME is enabled automatically
    Pins up-to-date!
    /home/user/.local/share/Steam/steam.sh: line 874: /home/user/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: Permission denied
    Installing breakpad exception handler for appid(steam)/version(1522709999)
    Installing breakpad exception handler for appid(steam)/version(1522709999)
    Gtk-Message: 13:44:26.385: Failed to load module "canberra-gtk-module"
    Gtk-Message: 13:44:26.386: Failed to load module "canberra-gtk-module"
    Installing breakpad exception handler for appid(steam)/version(1522709999)
    CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
    Installing breakpad exception handler for appid(steam)/version(1522709999)
    CAppInfoCacheReadFromDiskThread took 60 milliseconds to initialize
    [0406/134428.798486:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
    [0406/134429.799967:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
    [0406/134430.800222:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
    [0406/134431.801278:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
    Setting breakpad minidump AppID = 769
    Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
    [0406/134432.804253:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
    Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
    Generating new string page texture 3: 256x256, total string texture memory is 311.30 KB
    Assert( Assertion Failed: !bSharedKVSymbols ):appdatacache.cpp:2098

    crash_20180406134440_18.dmp[3578]: Uploading dump (out-of-process)
    /tmp/dumps/crash_20180406134440_18.dmp
    crash_20180406134440_18.dmp[3578]: Finished uploading minidump (out-of-process): success = no
    crash_20180406134440_18.dmp[3578]: error: libcurl.so: cannot open shared object file: No such file or directory
    crash_20180406134440_18.dmp[3578]: file ''/tmp/dumps/crash_20180406134440_18.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

#### Steps for reproducing this issue:

1. Launch steam via terminal.

**Comment by kisak-valve** [comment]
Hello @PaymonJay, `/home/user/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: Permission denied` is abnormal. Can make sure steam is not trying to run, then delete the `/home/user/.local/share/Steam/ubuntu12_32/steam-runtime` so that steam can regenerate it on the next run and see if that makes a difference?

**Comment by PaymonJay** [comment]
That actually fixed my issue! After deleting `/home/user/.local/share/Steam/ubuntu12_32/steam-runtime` I ran `steam` in the terminal and it actually launched. I then installed VVVVVV to test that I could in fact download and play games and it worked.

I'll close this issue. :)

Thank you!
