### ISSUE TITLE
Changing system volume while in-game affect the game screen

### ISSUE THREAD

**Issue by vsimitsis** [ValveSoftware/steam-for-linux#5438]
#### Your system information

* Steam client version (build number or date): Apr 2 2018
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: Νο
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While i have Counter Strike full screen on main screen and change the system volume with the keyboard's media button, top bar of the game screen goes transparent. The height of this transparent line is equal to Ubuntu's top bar.. When the volume icon of Ubuntu dissapears from the middle of the screen, the game screen goes back to normal. See picture attached.
![screenshot from 2018-04-07 02-15-32](https://user-images.githubusercontent.com/15974928/38460461-227efa1a-3ab2-11e8-9286-1a4f55668af0.png)

#### Steps for reproducing this issue:

1. Open Counter Strike
2. Change system (OS) volume

**Comment by kisak-valve** [comment]
Hello @vsimitsis, let's track this issue in the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1641.
