### ISSUE TITLE
Steam won't automatically login on startup even after checking "remember login"

### ISSUE THREAD

**Issue by SIX10** [ValveSoftware/steam-for-linux#5441]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-2
* Distribution (e.g. Ubuntu): Debian 9.4
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I was starting up steam and was greated with the login page. I logged in, entered my 2FA code, and it started. I then closed out by using i3's kill window shortcut (Mod + q) and then later restarted steam and got the login page again, requiring me to enter my login information and my 2FA code.
#### Steps for reproducing this issue:

1. Logging in on steam and checking "remember me"
2. Closing steam or restarting computer
3. Opening steam again

**Comment by kisak-valve** [comment]
Most likely a duplicate of #5030 / #5035.

**Comment by kisak-valve** [comment]
Hello @SIX10, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
