### ISSUE TITLE
VAAPI HW Decoding incorrect scaling

### ISSUE THREAD

**Issue by grimandreas** [ValveSoftware/steam-for-linux#5442]
* Steam client version (build number or date): Apr 2 2018
* Distribution (e.g. Ubuntu): Ubuntu 16.04.4 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, system has last available updates.

There is some problem with VAAPI decoding on Ubuntu 16.04.4 Client. Screen resolution - 1920x1080 
Host - Windows 10 with the same resolution.
Game launchers and in-game videos (which have resolution less than 1920x1080) zoomed in to the top left quarter of the screen.
For example, when I launch Skyrim SE stream I get this information in console on client:
```
ffmpeg verbose: Reinit context to 848x400, pix_fmt:vaapi_vld
Video size: 836x400, output size: 1920x1080
Video rect: 1920x1080 at 0,80
Texture rect: 836x400 at 0,0
```
**The problem is that context reinitialized to 848x400, video has similar resolution, but scaled to 1920x1080 for unknown reasons.** 
I know there was the same problem in 2014, but in 2015 Valve developers said the problem was solved.
I've tried using this fix http://voltaicforge.com/linux/steam-vaapi-fix-linux/
It doesn't fix problem.
Don't know if it's needed, but it's my output of **vainfo** command:
```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.39 (libva 1.7.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Bay Trail - 1.7.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
```
Any ideas for fixing?

#### Steps for reproducing this issue:
1.  Install latest versions of Ubuntu 16.04 and Steam from http://media.steampowered.com/client/installer/steam.deb
2. Install needed VA libraries via `sudo apt install i965-va-driver:i386 libva1:i386 libva-x11-1:i386 libva-glx1:i386` command
3. Enable HW Decode in IHS Settings of Steam Client.
4. Try to launch any game stream which has launcher or in-game video (Skyrim SE, Age of Empires II HD, etc.)

**Comment by kisak-valve** [comment]
Hello @grimandreas, this issue is already being tracked at #5281. Closing as a duplicate.
