### ISSUE TITLE
Steam doesn't launch on Arch Linux 4.15.15-1

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [ValveSoftware/steam-for-linux#5443]
#### Your system information

* Steam client version (build number or date): 
1.0.0.54-3 (according to pacman -Q steam)
* Distribution (e.g. Ubuntu): 
Arch Linux
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam doesn't launch anymore. It doesn't output any logs besides 
`/home/zed/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
/home/zed/.local/share/Steam/steam.sh: line 154: VERSION_ID: unbound variable
Running Steam on arch  64-bit
STEAM_RUNTIME is disabled by the user`
When the workaround from #3851 is used, it only outputs
`Running Steam on Linux 4.15.15-1-ARCH 64-bit
STEAM_RUNTIME is enabled automatically`
I'm using the latest proprietary Nvidia drivers and steam-native-runtime (same output on steam-runtime and steam-native)

**Comment by zbigniewzolnierowicz** [comment]
I rebooted my PC and it worked.

**Comment by kisak-valve** [comment]
Most likely from the running nvidia kernel module and the userspace library not matching versions. Closing.
