### ISSUE TITLE
Would a non-SSE3 build of Steam be a possibility.

### ISSUE THREAD

**Issue by thedarkb** [ValveSoftware/steam-for-linux#5445]
I don't think it's fair that I can't play my games all of a sudden because my CPU lacks SSE3 support, the system requirements list a Pentium 4 as the minimum but not all Pentium 4s support SSE3. I can't even pirate **my** games because I'm a Linux user and I haven't been able to find a cracked Linux version of half-life.

**Comment by kisak-valve** [comment]
Hello @thedarkb, this issue is already being tracked at #5164. When we hear from a Steam dev, it will either be on that issue report or in a update note for Steam.

Closing as a duplicate.
