### ISSUE TITLE
[Regression] symbol lookup error: path/to/game/executable: undefined symbol: SteamSomething

### ISSUE THREAD

**Issue by axredneck** [ValveSoftware/steam-for-linux#5446]
#### Your system information

* Steam client version (build number or date): 02.04.2018
* Distribution: Antergos (Arch-based)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Some games stopped working after one of Steam updates, **but they worked before** in 2017.
**Strike Suit Zero** gives this error about "SteamRemoteStorage" symbol:
`/home/redneck/.steam/SteamApps/common/strikesuitzero/linux/main/binary/StrikeSuitZero: symbol lookup error: /home/redneck/.steam/SteamApps/common/strikesuitzero/linux/main/binary/StrikeSuitZero: undefined symbol: SteamRemoteStorage`
**You Have To Win The Game** and **Super Win The Game** give error about "SteamUser" symbol:
`/home/redneck/.steam/SteamApps/common/Super Win the Game/SuperGame_NFML: symbol lookup error: /home/redneck/.steam/SteamApps/common/Super Win the Game/SuperGame_NFML: undefined symbol: SteamUser`
`/home/redneck/.steam/SteamApps/common/You Have to Win the Game/TheGame_NFML: symbol lookup error: /home/redneck/.steam/SteamApps/common/You Have to Win the Game/TheGame_NFML: undefined symbol: SteamUser`
And **Duke Nukem 3D Megaton Edition** and **Shadow Warrior Classic Redux** complain about "SteamUserStats":
`../bin/duke3d: symbol lookup error: ../bin/duke3d: undefined symbol: SteamUserStats`
`../bin/sw: symbol lookup error: ../bin/sw: undefined symbol: SteamUserStats`
It's not a regression of games themself because they didn't receive any updates since they worked.

#### Steps for reproducing this issue:

1. Install "You Have To Win The Game" (it's free) or any other game specified above
2. Try to play it
3. Suck a paw

**Comment by noahb01** [comment]
This *could* (no promises) be an issue with finding and locating shared libraries. Are you using the Steam runtime or the Native runtime? I had quite a few library issues with the native runtime before I got everything installed correctly.

**Comment by axredneck** [comment]
I use Steam runtime. Native runtime is not recommended according to Archwiki.

**Comment by axredneck** [comment]
Can somebody test if Steam games i specified work on linux at all?

**Comment by Chiitoo** [comment]
You Have to Win the Game, Super Win the Game, Duke Nukem 3D Megaton Edition, and Shadow Warrior Classic Redux all still work for me on Gentoo Linux.

**Comment by noahb01** [comment]
@axredneck I know it's not recommended, but for me it wouldn't run at all with steam runtime. Because your having problems with it, try using native and see if it loads. Only downside is that you'll need a lot of multilib packages because steam has a lot of x32 dependencies.

**Comment by axredneck** [comment]
@noahb01 Thank You! I installed steam-native-runtime package, runned Steam with native libs and now these games work.

**Comment by kisak-valve** [comment]
Hello @axredneck, are you still experiencing this issue on an up to date system?

**Comment by axredneck** [comment]
The issue is gone for me
