### ISSUE TITLE
Overlay crash in-game

### ISSUE THREAD

**Issue by theo546** [ValveSoftware/steam-for-linux#5450]
#### Your system information

* Steam client version (build number or date): Apr 2 2018, at 15:23:55
* Distribution (e.g. Ubuntu): Archlinux 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When playing a game (Rocket League), when i use the built-in browser of the overlay, the overlay disappair and i cant re-open it until i close then i re-open the game.

#### Steps for reproducing this issue:

1. Open a game.
2. Open the overlay then the built-in browser.
3. Wait for it to crash.

**Comment by theo546** [comment]
Here: https://gist.github.com/theo546/bb268418c55b93af670ae162324149db

**Comment by kisak-valve** [comment]
Hello @theo546, @nightsky30, are either of you still experiencing this issue on an up to date system?

**Comment by theo546** [comment]
Hello, so far I haven't been able to reproduce this issue.

**Comment by nightsky30** [comment]
Same :)

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
