### ISSUE TITLE
No Steam Chat reminder indicators in Ubuntu 17.10

### ISSUE THREAD

**Issue by Odzinic** [ValveSoftware/steam-for-linux#5451]
#### Your system information

* Steam client version (build number or date): April 2, 2018
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When a Steam chat message gets received whether it be a new chat or existing one there is no reminder/indicator in Gnome shell. The Steam indicator does popup in the bottom right corner of the screen properly but if the user is not there during the Steam indicator popup then there is no indication of a received message such as the orange indicator that appears in KDE. This issue makes it very easy to miss message. Utilizing Gnome's message tray may mitigate this issue.

#### Steps for reproducing this issue:

1. Receive any Steam chat message
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Odzinic, the feature request at #3835 covers this issue. Closing in favor of the existing issue report.
