### ISSUE TITLE
Remeber librabry folder

### ISSUE THREAD

**Issue by MauroMombelli** [ValveSoftware/steam-for-linux#5452]
#### Your system information

* Steam client version (build number or date): 16-04-2018
* Distribution (e.g. Ubuntu): Arch linix
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I set up an external disk as steam library, but if i start steam without the hard disk connected, steam forget the library folder.
If i connect the disk and restart steam (if not automatically), i expect steam to see the folder and load the games.
Manually adding back the folder works fine but is tedius every time.

#### Steps for reproducing this issue:

1.  Download some game to an external hard disk
2. Turn off steam, disconnect the hard disk
3. start steam, game are gone (ok), close steam
4. connect disk
5. start steam, game are still gone (NOT ok)

**Comment by kisak-valve** [comment]
Hello @MauroMombelli, this issue is already being tracked at #4383. Closing as a duplicate.
