### ISSUE TITLE
Steam and CSGO crashed as CSGO started

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5453]
Issue transferred from https://github.com/ValveSoftware/csgo-osx-linux/issues/1648.
@nightsky30 posted on 2018-04-21T13:19:19:

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/nightsky30/5d0f131acacdf0535f66b822c30d9f67
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam crashed as CSGO started.  I'd had Steam open for about an hour I think.  I started CSGO.  Everything crashed, and I had to restart Steam and CSGO.  It crashed while at the "Powered By Source" CSGO intro screen/movie.

#### Steps for reproducing this issue:

1. Started Steam
2. Idled for an hour
3. Started CSGO
4. Crash

Here are my dump, log and stdout files:

[log.txt](https://github.com/ValveSoftware/csgo-osx-linux/files/1934545/log.txt)
[stdout.txt](https://github.com/ValveSoftware/csgo-osx-linux/files/1934546/stdout.txt)
[Crashe Dumps.zip](https://github.com/ValveSoftware/csgo-osx-linux/files/1934547/Crashe.Dumps.zip)

**Comment by kisak-valve** [comment]
This looks like the line of interest in the log:
```*** Error in `/home/spike/.local/share/Steam/ubuntu12_32/steam': free(): invalid pointer: 0xd9688850 ***```

For reference, the attached minidump is a SIGABRT in linux-gate.so.

**Comment by kisak-valve** [comment]
Hello @nightsky30, are you still experiencing this issue on an up to date system?

**Comment by nightsky30** [comment]
Hi @kisak-valve I've not experienced this issue in quite a while.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
