### ISSUE TITLE
lib pinning does not handle system LD_LIBRARY_PATH only systems

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5455]
If the gfx system libs are provided in a system LD_LIBRARY_PATH, it will be ignored by the bash ( :'( ) script which creates pinned links because it requires the use of /sbin/ldconfig and ld cache.
More over some systems split 32 bits ld cache location with 64 bits ld cache location which means /sbin/ldconfig will miss the 32 bits libs pinning.
(I would recommend to code a real binary program to manage the pinned libs, called from the main script with a behavior overridable with some user set env var(s) )
I could see that 64 bits steam runtime libxcb-dri3 is missing a symbol for a recent mesa libGL (showed by the vulkan tester).

**Comment by kisak-valve** [comment]
Hello @sylware, what's the exact scenario (with library versions and paths) where LD_LIBRARY_PATH must be handled for pinning?

Using libxcb-dri3 as an example sounds like you're trying to refer to the bootstrapper runtime issue that is being tracked at #4816 and does not apply because the bootstrapper currently does not pin libraries.

**Comment by sylware** [comment]
On Sun, Apr 22, 2018 at 02:16:59PM +0000, sylvain.bertrand@gmail.com wrote:
> Then I dare to ask for a way to do the pinning ourself, a kind of a hook or
> something else, we know the pinning will happen in
> $HOME/.steam/bin/steam-runtime/pinned* directories.

I gave some thoughs about it: what about 2 env variables:
STEAM_PIN_OVERRIDE_32
STEAM_PIN_OVERRIDE_64

Colon separated absolute path names to "soname" files/symbolic links.

Links to those would be installed in pin directories whatever happens (quite
less clumsy than a brutal LD_PRELOAD), and that each time steam is started.

That would give the tools to troubleshoot those pesky steam/system runtime libs
with fine granularity.

-- 
Sylvain

**Comment by h1z1** [comment]
What are you setting LD_PRELOAD to?  The OS should have no problem finding libs based on architecture (32 vs 64 bit for example).   The way library pinning is done in steam makes a giant assumption that ABI/API is always compatible which is narcissistic at best.

> coze I don't use the ld cache on my system

What on Earth would you disable that for?

**Comment by sylware** [comment]
For the moment, since the client runs ok and I don't have steam runtime re-install or
update, I do pin the 64 bits libs manually before starting the client.

**Comment by sylware** [comment]
lib pinning almost useless, with current steam-runtime: only the 64 bits steam-runtime libdbus is enable to run google libcef.

**Comment by sylware** [comment]
With dbus or not, cannot reproduce any breaking pinning.

Seems fixed for now.
