### ISSUE TITLE
Steam cannot find fonts and does not render them

### ISSUE THREAD

**Issue by daerogami** [ValveSoftware/steam-for-linux#5456]
#### Your system information

* Steam client version (build number or date): steam-launcher 1.0.0.54
* Distribution (e.g. Ubuntu): Linux Mint 18.3 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected:
Open steam with fonts rendering.

Actual:
The console repeats `../vgui_surfacelib/linuxfont.cpp (402) : Assertion Failed: Unable to find font named Arial` same for a few other fonts `DejaVu Sans`, `Marlett` and `Lucidia Console` which lead to further errors (read linked log)
These fonts are present in Font Viewer and display correctly.
https://gist.github.com/daerogami/4cbaff7cf2a39e91e0f833b669634d98

![firstlaunch](https://user-images.githubusercontent.com/2267600/39098771-40fec61c-4635-11e8-8a1a-66f1b62e0393.png)
![login](https://user-images.githubusercontent.com/2267600/39098772-43a69778-4635-11e8-934e-fc64c4237845.png)
![dashboard](https://user-images.githubusercontent.com/2267600/39098773-4570fbf2-4635-11e8-91c9-3129d13b42f7.png)
Couldn't get a screenshot, but the context menu text from the applets panel in the bottom right is all squares.

#### Steps for reproducing this issue:

1. Download and install steam
2. Download Segoe UI and manually install the font
3. Force clear the font cache ```sudo fc-cache -frvE```
4. Change {Default Font, Desktop Font, Document Font, Window Title Font} from Noto to Segoe UI 
5. Realize it doesnt work and change back to Noto fonts.
6. Install mscorefonts ```sudo apt-get install ttf-mscorefonts-installer```
7. Restart
8. Run steam

This appears to have been an issue as long as steam-for-linux has been around; however, solutions such as upgrading the OS, installing every relevant font under the sun, installing fonts in ~/.fonts, installing fonts in steam's fonts folder have all proved unfruitful. I cant even remember some of the other guides I have attempted. I'm really puzzled how the client isn't able to access fonts that are clearly available to the OS.

Related to #99

**Comment by kisak-valve** [comment]
Closing per the last comment.
