### ISSUE TITLE
How and where install missings libraries ?

### ISSUE THREAD

**Issue by PowaBanga** [ValveSoftware/steam-for-linux#5458]
#### Your system information

* Steam client version (build number or date): 
2 april 2018
* Distribution (e.g. Ubuntu): 
archlinux
* Opted into Steam client beta?: [Yes/No]
no (i think...)
* Have you checked for system updates?: [Yes/No]
yes
#### Please describe your issue in as much detail as possible:
So, I have some games who can't start (crash on start) After reading some topics, it seem that is because of some missing libraries.
I launched this command line into ´$HOME/.local/share/Steam/ubuntu12_64´
```
ldd $(file *|sed '/ELF/!d;s/:.*//g')|grep 'not found'|sort|uniq
```
```
	libavcodec.so.57 => not found
	libavformat.so.57 => not found
	libavresample.so.3 => not found
	libavutil.so.55 => not found
	libswscale.so.4 => not found
	libtier0_s.so => not found
	libv8.so => not found
	libvideo.so => not found
	libvstdlib_s.so => not found
```

so, ffmpeg is already installed, and should contain some of this libraries... so, I do not understand something... Somebody can help me ?

**Comment by kisak-valve** [comment]
Hello @PowaBanga, .../ubuntu12_64 has libraries for steam itself to use, and is not part of the steam runtime. You probably wanted to look in `~/.local/share/Steam/ubuntu12_32/steam-runtime` for libraries used by games.

**Comment by PowaBanga** [comment]
yes, i looked into `$HOME/.local/share/Steam/ubuntu12_32`
it's a typo on my part
so, what should i do exactly ?

**Comment by kisak-valve** [comment]
There's not enough information here to make a suggestion. What game and libraries are you seeing an issue with?

**Comment by PowaBanga** [comment]
here **couterstrike 2D** don't work,, **space fighte**r and **destination sol**. (there is **transmission element** too, but for this game i recieve an error message who speak about my keyboard layout, so i think that it is an other issue for this game.)

So, I was thinking that with this command : 
`ldd $(file |sed '/ELF/!d;s/:.//g')|grep 'not found'|sort|uniq`
I will see what are missing. It is why I am asking here how to install them...
Am I wrong ?

Should I run this games into a terminal and show answers here ?

**Comment by kisak-valve** [comment]
Something along the lines of `~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ldd <library that failed to load>` from the game's folder has a better chance of giving useful info.

There's some info on the [Arch wiki](https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Transmissions:_Element_120) for Transmissions: Element 120 that may help.

For Arch, you should use pacman to install the distro-specific variants of libraries.

Separately, you also might have some success with the [steam-native-runtime](https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/) package pulling in common dependencies.

If you want to include terminal spew in the issue report, go right ahead. Please use a [gist](https://gist.github.com/) with the output after trying to run those games. You can completely close steam, then run steam from a terminal, or look at `/tmp/dumps<username>_stdout.txt` for the terminal spew.

**Comment by kisak-valve** [comment]
Hello @PowaBanga, are you still experiencing an issue related to this on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
