### ISSUE TITLE
X11 Bad Window Request

### ISSUE THREAD

**Issue by tjakway** [ValveSoftware/steam-for-linux#5461]
The steam client crashes on startup.

- To reproduce: run steam or steam.sh
- I’m running Ubuntu 17.10 with xmonad and nvidia drivers (390.48) in a 2-monitor setup using xrandr.  Can’t include the steam hardware output for obvious reasons but will answer any specific questions.

I originally thought the problem had to involve xmonad but I get the exact same error when booting XFCE.

I’ve tried:
- updating nvidia drivers (from 384 to 390.48)
- Tried installing gcc-multilib
- tried enabling EWMH
  -  starting xmonad with xmonad $ ewmh $ myConfig {…}
  -  tried composing ewmh’s fullscreenEventHook
 - running steam as root
   -  displays a message saying “cannot run as root”
 -  reinstalling steam
 -  deleting ~/.local/share/Steam then launching steam again (to force a reinstallation)
 - launching a xubuntu desktop session instead of xmonad
    - exactly the same error, including after reinstalling steam under xubuntu

The nvidia drivers are definitely loaded, as lsmod output confirms.

```
thomas@thomas-Z370:~$ steam
Running Steam on ubuntu 17.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  155
Resource id in failed request:  0x3e00002
Serial number of failed request:  42
xerror_handler: X failed, continuing
crash_20180423155044_1.dmp[5823]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180423155044_1.dmp
/home/thomas/.local/share/Steam/steam.sh: line 927:  5806 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180423155044_1.dmp[5823]: Finished uploading minidump (out-of-process): success = yes
crash_20180423155044_1.dmp[5823]: response: CrashID=bp-ebfc12c0-bd72-4100-85f7-8a8d42180423
crash_20180423155044_1.dmp[5823]: file ''/tmp/dumps/crash_20180423155044_1.dmp'', upload yes: ''CrashID=bp-ebfc12c0-bd72-4100-85f7-8a8d42180423''
```

[crash_20180423155044_1.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/1940309/crash_20180423155044_1.dmp.zip)

**Comment by kisak-valve** [comment]
Hello @tjakway, this is commonly caused by the 32 bit OpenGL driver being broken or incomplete. Can you check if a basic 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

**Comment by kisak-valve** [comment]
That pretty clearly confirms that the nvidia driver on your system is currently broken. If you've very recently updated the driver and not rebooted, then the running kernel module version may not match the userspace libraries.

This should be fixed before troubleshooting Steam further.

**Comment by tjakway** [comment]
@kisak-valve yep, looks like it.  Sorry for bothering you guys, I assumed it was an issue with steam since everything (firefox, vim, even vlc) else seems to work fine.
