### ISSUE TITLE
18.04 Ubuntu Steam crashes

### ISSUE THREAD

**Issue by robotichead** [ValveSoftware/steam-for-linux#5463]
#### Your system information

* Steam client version (build number or date): Tried reinstalling, should be at latest version
* Distribution (e.g. Ubuntu): 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam will crash shortly after the "Steam Update" progress bar appears. Even after a fresh install.

#### Steps for reproducing this issue:

1. Open Terminal
2. Type in "steam" and hit enter
3. Watch steam crash

-- TERMINAL OUTPUT --
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Gtk-Message: 10:43:17.174: Failed to load module "gail"
Gtk-Message: 10:43:17.174: Failed to load module "atk-bridge"
dbus[14751]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
crash_20180425104313_1.dmp[14760]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180425104313_1.dmp
/home/luke/.local/share/Steam/steam.sh: line 927: 14751 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180425104313_1.dmp[14760]: Finished uploading minidump (out-of-process): success = yes
crash_20180425104313_1.dmp[14760]: response: CrashID=bp-e5b5a87e-c702-4987-9268-fe47a2180424
crash_20180425104313_1.dmp[14760]: file ''/tmp/dumps/crash_20180425104313_1.dmp'', upload yes: ''CrashID=bp-e5b5a87e-c702-4987-9268-fe47a2180424''
-- END TERMINAL OUTPUT --

Steam was working on 18.04 last week, I was able to open steam and play a game. Reinstalling has not fixed the issue. I have tried to install extra software like "gail" and "atk-bridge" however they are installed as outlined in the terminal output below.

-- SOFTWARE INSTALL --
sudo apt-get install libatk-adaptor libgail-common
[sudo] password for luke: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libatk-adaptor is already the newest version (2.26.2-1).
libgail-common is already the newest version (2.24.32-1ubunt/home/luke/.local/share/Steam/steam.sh: line 927: 14751 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"u1).
0 to upgrade, 0 to newly install, 0 to remove and 3 not to upgrade.
-- END SOFTWARE INSTALL --

**Comment by kisak-valve** [comment]
Hello @robotichead, can you move `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` out of the way and see if that makes a difference? If it does, then please list the contents of the old and regenerated pinned library folders.

This reads similarly to https://github.com/ValveSoftware/steam-for-linux/issues/5408#issuecomment-382400187.

**Comment by robotichead** [comment]
Hello @kisak-valve , I sadly did not keep a copy of the pinned_libs*. I did the following to solve the issue

Method
1.) sudo apt-get remove --purge steam-launcher
2.) Find any "steam" folders and remove
3.) Clear trash (no required)
4.) sudo apt-get install steam


This has fixed this issue for the moment. I should also note that originally I installed steam from the deb file provided on store.steampowered.com

**Comment by flajann2** [comment]
I attempted to move the pinned libs "out of the way", tried launching again, and got the following:
----------
> steam
rm: cannot remove '/home/alveric/.steam/bin': Is a directory
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 32-bit libdbus-1.so.3. Host: 3.19.4 Runtime: 3.5.8
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 32-bit libdbus-1.so.3. Host: 3.19.4 Runtime: 3.5.8
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libdbus-1.so.3': File exists
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libGLU.so.1': File exists
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libdbusmenu-gtk.so.4': File exists
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libGLU.so.1': File exists
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libdbusmenu-glib.so.4': File exists
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
ln: failed to create symbolic link '/kernkraftwerk/desktop-state/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libpangox-1.0.so.0': File exists
Installing breakpad exception handler for appid(steam)/version(1524875365)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1524875365)
Installing breakpad exception handler for appid(steam)/version(1524875365)
Gtk-Message: 19:20:49.190: Failed to load module "gail"
Gtk-Message: 19:20:49.191: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
crash_20180430192046_1.dmp[3930]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180430192046_1.dmp
/kernkraftwerk/desktop-state/.local/share/Steam/steam.sh: line 927:  3793 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180430192046_1.dmp[3930]: Finished uploading minidump (out-of-process): success = yes
crash_20180430192046_1.dmp[3930]: response: CrashID=bp-393c1a65-7acf-44ae-83f6-ad0092180430
crash_20180430192046_1.dmp[3930]: file ''/tmp/dumps/crash_20180430192046_1.dmp'', upload yes: ''CrashID=bp-393c1a65-7acf-44ae-83f6-ad0092180430''
----------
Any clues as to why this is failing? I have my .local soft-linked to a bigger drive, but this should not be an issue, right?

Thanks.

**Comment by kisak-valve** [comment]
@flajann2, that log segment indicates Steam is trying to use swrast, which is mesa's slower software renderer. There's a good chance your 32 bit opengl driver is broken and needs to be fixed.

**Comment by Bloodaxe95** [comment]
I had the exact same issue, and was redirected here by a Valve employee. Here are my old Steam pinned libs, if that is helpful!

[Steam Pinned libs.zip](https://github.com/ValveSoftware/steam-for-linux/files/1966960/Steam.Pinned.libs.zip)

**Comment by flajann2** [comment]
@kisak-valve Why oh why does anything use 32-bits anymore? Anyway, the files -- the .so files -- are installed, but Steam is simply not finding them.
I even tried launching Steam on a clean install of 18.04 on my VM, and it's the exact same message!
So whatever it is, it's broken for 18.04 on Nvidia systems.

**Comment by MasterCATZ** [comment]
steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Installing breakpad exception handler for appid(steam)/version(1522709999)
Gtk-Message: 07:01:52.163: Failed to load module "gail"
Gtk-Message: 07:01:52.163: Failed to load module "atk-bridge"
dbus[9526]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20180506070150_1.dmp[9539]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180506070150_1.dmp
/home/aio/.steam/steam.sh: line 927:  9526 Aborted                 $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180506070150_1.dmp[9539]: Finished uploading minidump (out-of-process): success = yes
crash_20180506070150_1.dmp[9539]: response: CrashID=bp-fe7df168-944e-4977-8d64-a4d1f2180505
crash_20180506070150_1.dmp[9539]: file ''/tmp/dumps/crash_20180506070150_1.dmp'', upload yes: ''CrashID=bp-fe7df168-944e-4977-8d64-a4d1f2180505''

**Comment by EnverOsmanov** [comment]
@kisak-valve here both new and old files:
[For_kisak-valve.zip](https://github.com/ValveSoftware/steam-for-linux/files/2019734/For_kisak-valve.zip)

**Comment by quicksketch** [comment]
I just ran into this today, despite having upgraded to 18.04 over a week ago and used Steam several times since then. As with others, moving the pinned_libs helped. Here's the exact commands for those looking to try the same thing:

```
cd ~/.local/share/Steam/ubuntu12_32/steam-runtime
mv pinned_libs_32/ bak-pinned_libs_32
mv pinned_libs_64/ bak-pinned_libs_64
steam
```

**Comment by EralpCelebi** [comment]
The weird thing is after deleting re-installing and somehow getting steam to launch up (somewhat) propperly after the login screen comes up the whole linux system(in my case Ubuntu 18.04) lock up and refuse any inputs. I have not checked the logs in detail but this might be an issue with the whole Ubuntu version.

**Comment by Disk1of5** [comment]
This is very odd i found that i was having this issue after  in installed LMMS using the Ubuntu repo, after i completely removed the LMMS packages and did a apt auto-remove  i was able to launch Steam again.

**Comment by cilazsun** [comment]
Steam keeps crashing. Did apt-get remove --purge steam, rm ~/.local/share/Steam -R and finally apt-get install steam. Dont know what to do next.
```
cila@PC-LX-01:~/.local/share/Steam/ubuntu12_32/steam-runtime$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
Installing breakpad exception handler for appid(steam)/version(1539393410)
crash_20181024154238_1.dmp[31082]: Uploading dump (out-of-process)
/tmp/dumps/crash_20181024154238_1.dmp
/home/cila/.local/share/Steam/steam.sh: Zeile 881: 31077 Speicherzugriffsfehler  (Speicherabzug geschrieben) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20181024154238_1.dmp[31082]: Finished uploading minidump (out-of-process): success = yes
crash_20181024154238_1.dmp[31082]: response: CrashID=bp-765d2909-ac10-4674-9103-a07722181024
crash_20181024154238_1.dmp[31082]: file ''/tmp/dumps/crash_20181024154238_1.dmp'', upload yes: ''CrashID=bp-765d2909-ac10-4674-9103-a07722181024''
cila@PC-LX-01:~/.local/share/Steam/ubuntu12_32/steam-runtime$ 

```

**Comment by maggu** [comment]
> Steam keeps crashing. Did apt-get remove --purge steam, rm ~/.local/share/Steam -R and finally apt-get install steam. Dont know what to do next.

Did you try this?

<code>LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 steam</code>

**Comment by flybd5** [comment]
I am seeing this problem as well.

> Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Gtk-Message: 15:06:33.854: GtkDialog mapped without a transient parent. This is discouraged.
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 64-bit libSDL2-2.0.so.0. Host: 0.8.0 Runtime: 0.10.0
Found newer runtime version for 64-bit libvulkan.so.1. Host: 1.1.126 Runtime: 1.2.135
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libopus.so.0. Host: 0.5.2 Runtime: 0.7.0
Forced use of runtime version for 64-bit libcurl.so.4. Host: 4.5.0 Runtime: 4.2.0
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Forced use of runtime version for 32-bit libgtk-x11-2.0.so.0. Host: 0.2400.32 Runtime: 0.2400.10
Found newer runtime version for 32-bit libSDL2-2.0.so.0. Host: 0.8.0 Runtime: 0.10.0
Found newer runtime version for 32-bit libvulkan.so.1. Host: 1.1.126 Runtime: 1.2.135
Found newer runtime version for 32-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 32-bit libopus.so.0. Host: 0.5.2 Runtime: 0.7.0
Forced use of runtime version for 32-bit libdbus-1.so.3. Host: 3.19.4 Runtime: 3.5.8
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
ln: failed to create symbolic link '/home/zork/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libdbusmenu-gtk.so.4': File exists
Steam client's requirements are satisfied
/home/zork/.local/share/Steam/ubuntu12_32/steam
[2020-10-02 15:06:52] Startup - updater built Sep  3 2020 21:18:09
Installing breakpad exception handler for appid(steam)/version(1599174997)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-10-02 15:06:52] Loading cached metrics from disk (/home/zork/.local/share/Steam/package/steam_client_metrics.bin)
Installing breakpad exception handler for appid(steam)/version(1599174997)
[2020-10-02 15:06:52] Checking for update on startup
[2020-10-02 15:06:52] Checking for available updates...
[2020-10-02 15:06:52] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1599174997)
[2020-10-02 15:06:52] Download skipped: /client/steam_client_ubuntu12 version 1599174997, installed version 1599174997, downloaded version 0
[2020-10-02 15:06:52] Nothing to do
[2020-10-02 15:06:52] Verifying installation...
[2020-10-02 15:06:52] Performing checksum verification of executable files
[2020-10-02 15:06:53] Verification complete
Loaded SDL version 2.0.13-5919606
Gtk-Message: 15:06:53.978: Failed to load module "gail"
Gtk-Message: 15:06:53.979: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  154
Serial number of failed request:  48
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  47
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  49
xerror_handler: X failed, continuing
assert_20201002150652_1.dmp[23766]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201002150652_1.dmp
/home/zork/.local/share/Steam/steam.sh: line 750: 23687 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
zork@zork-Precision-T5600:~/.local/share/Steam/ubuntu12_32/steam-runtime$ assert_20201002150652_1.dmp[23766]: Finished uploading minidump (out-of-process): success = yes
assert_20201002150652_1.dmp[23766]: response: CrashID=bp-2f5dbd6e-bac6-45fd-ae37-325352201002
assert_20201002150652_1.dmp[23766]: file ''/tmp/dumps/assert_20201002150652_1.dmp'', upload yes: ''CrashID=bp-2f5dbd6e-bac6-45fd-ae37-325352201002''

**Comment by kisak-valve** [comment]
Hello @flybd5, no, you're not seeing the issue that was tracked in this issue report.

In your terminal spew, `libGL error: failed to load driver: swrast` indicates that Steam is trying to use mesa's slower software implementation. This usually hints that you're using nVidia's proprietary driver, but do not have 32 bit userspace support libraries installed. The nVidia proprietary driver requires that the running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries have exactly the same version to work properly. On Ubuntu, you can find what driver series you're using, then install `libnvidia-gl-450:i386` with something like `sudo apt install libnvidia-gl-450:i386` (replace 450 with the video driver series you're using).

I'm going to lock this issue report because it's been accumulating more unrelated feedback than relevant feedback for the dbus steam runtime issue that was reported here.
