### ISSUE TITLE
Move Install Folder loses Window focus

### ISSUE THREAD

**Issue by h1z1** [ValveSoftware/steam-for-linux#5466]
#### Your system information

* Steam client version (build number or date): Apr 24 2018 
* Distribution (e.g. Ubuntu):  CentOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. 

The Move Install Folder location prompt can lose permanently lose focus if you click anywhere off it.  Though it does still render, the window appears to ignore events.   Only work around is to go back through the process of moving a folder.

Didn't go through them all but couldn't find any other dialogs that do this.

#### Steps for reproducing this issue:

1. Install a game
2. Right click->Properties->Local Files->Move Install folder
3.  Click anywhere off the popup
4.  Try to click back on it or alt-tab

Repeat step 2 to regain focus.

**Comment by tinfoil-hacks** [comment]
**Your system information**

- Steam client version (build number or date): 2019/05/15
- Distribution (e.g. Ubuntu): Manjaro Linux XFCE, kernel 4.19
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes

Further testing shows that you can regain focus when there are no other pop-up windows "between" the Steam Client main window and the "Move Install Folder" pop-up. The pop-up window also stays on top of other windows (such as a web browser) and is not in the Alt-tab menu.

**Comment by Managor** [comment]
Minimizing the steam client seems to give the move window its focus back.

**Comment by YoshiRulz** [comment]
Still not fixed on build 2020-02-11T19:27:00 (Manjaro x86_64 `steam-manjaro-1.0.0.61-7`, DE is Plasma 5 X11). To reiterate, the window *appears* to be keep-above, but cannot be focused if there's another window over it (visually, behind it). Is it so hard to delegate window management to the window manager?

On a related note, is there a technical reason I can't open the context menu on ANY of Steam's window decorations? It's the easiest way to move windows to another desktop or set them to keep-above.

**Comment by Managor** [comment]
I assume this is now fixed since the move dialog has been remade.

**Comment by J4nsen** [comment]
Works fine for me now

**Comment by YoshiRulz** [comment]
Nope. [Here's a video](https://youtu.be/2LZAjr7mJwY) of me clicking where the dialog is and hitting the thing behind it. I forgot to show it, but the build date in About Steam is 2021-07-20—is there a newer version with a fix?

**Comment by J4nsen** [comment]
It is fixed in the beta build

**Comment by kisak-valve** [comment]
Closing per the last handful of comments.
