### ISSUE TITLE
Steam Client is causing a memory leak in Xorg

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/steam-for-linux#5469]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Kubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
A long session of gaming causes the amount of memory Xorg consumes to rise a lot. This is a pretty big issue, as in one hour Xorg may consume up to 200MB of RAM (from the usual 34MB), and games start stuttering, missing input or just causing a general drop in performance.
When closing steam Xorg almost instantly returns to nominal RAM usage, however this is also causing a system-wide freeze for a short period of time.

#### Steps for reproducing this issue:
1. Play games
2. Check the Xorg memory usage
3. Close steam
4. Check the Xorg memory usage again, note the drop of amount of memory allocated to the process.

**Comment by kisak-valve** [comment]
Possible duplicate of #5279.

**Comment by kiroma** [comment]
Closing in favor of #5279
