### ISSUE TITLE
Shift-select gets stuck in Library view

### ISSUE THREAD

**Issue by bradenbest** [ValveSoftware/steam-for-linux#5470]
#### Your system information

* Steam client version (build number or date): Build Apr 2 2018 / API v018 / package versions 1522709999
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (NB: this bug has affected steam-for-linux for over a year throughout several versions)

#### Extra information

* X11 version (`xdpyinfo | grep -i version`): 11.0 / X.Org 1.18.4 
* Window manager: DWM 6.1 (custom build)
* Desktop: N/A

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Sometimes, when in the library view, trying to click on another game results in a multi-select of every game between the previous game and the one I just selected (as if I had shift-clicked it). And getting rid of the multi-select is almost impossible. I *could* use my arrow keys, but that's just irritating when you have 100+ games. Closing the client window, switching to store and then back, shift-clicking, ctrl-clicking, nothing I do seems to get rid of it short of probably killing the server, which I would prefer to avoid. I attempted to take a screenshot (`import -window root`) of it, but the bug went away seemingly as a result of me trying to take a screenshot.

**Expected Result** - Naturally, I expect clicking a game to select only that game

**Actual Result** - Steam thinks shift is still down, and selects multiple games even if I press and release shift to let steam know it isn't pressed.

#### Steps for reproducing this issue:

The thing is, I have no idea how to reproduce this bug. It's unpredictable. When it happens, it's always unexpected. It's happened to me four times throughout different versions of the client and I have yet to find a pattern. If you have steam open for long enough (as in multiple days/weeks), it will eventually happen.

Due to the nature of the bug, I would suggest investigating the code that executes when you press shift. If it activates a flag variable, it's probably getting stuck due to the user, you know, *using* their OS.

That said, I have found one way to reproduce the bug, though it is unreliable and I'm able to resolve it with a shift click:

1. Configure your window manager to move a window to a different view with a key combo that includes shift (DWM is the easiest way: e.g. Alt+Shift+6).

2. Open another window, like a terminal, in the same workspace/tag as steam.

3. Move both the second window and steam to the other workspace/tag

4. Attempt to click on a game

5. If the bug doesn't happen, repeat steps 3-4 until it does.

Like I said, you're probably better off investigating the source code. There's probably an edge case in there that wasn't checked.

**Comment by bradenbest** [comment]
It's also possible that shift-click *does* resolve the bug when it happens on its own and I'm just being an idiot. I'll try shift-click next time and see if it works.

**Comment by bradenbest** [comment]
Here's a series of screenshots:
![image exhibiting bug](https://i.imgur.com/l7gz955.gif)

**Comment by kisak-valve** [comment]
Hello @bradenbest, this issue is already being tracked at #3451. Closing as a duplicate.
