### ISSUE TITLE
Steam will not start. GTK Warnings.

### ISSUE THREAD

**Issue by Austint30** [ValveSoftware/steam-for-linux#5473]
#### Your system information

* Steam client version (build number or date): 26184
* Distribution (e.g. Ubuntu): Ubuntu 18.04 Bionic Beaver
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I am not exactly sure what is causing the crash to occur, but I think it has to do with using the Communitheme on Ubuntu 18.04. I also have a custom skin (Metro for Steam) installed for the steam client.

Here is the result of running steam with the terminal:
https://gist.github.com/Austint30/fcb80ac94c95084cfd2bbff792965d8a

#### Steps for reproducing this issue:

1. Use Ubuntu 18.04.
2. sudo snap install communitheme
3. Log out. Change session to Ubuntu Communitheme and log in again.
4. Install Metro for Steam skin
5. Log out of steam. Try to log in again. Updating steam window appears and then disappears. This is when it crashes.
6. Start steam using the steam command. Should fail to start with Gtk warnings.

**Comment by kisak-valve** [comment]
Hello @Austint30, the dbus message looks like the line of interest in the log.

Can you move the equivalent of `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` out of the way and see if that makes a difference? If it does, then please list the contents of the old and regenerated pinned library folders.

**Comment by BittaJam** [comment]
Hi. I confirm this bug, I have the very same issue on my Debian system. The output from the terminal looks pretty same. 
I have removed pinned_libs* folders, so Steam would rebuild them, and now it runs normally (with the usual output full of other errors (like "TagLib: MPEG::Header::parse() -- Invalid sample rate", and "process 16956: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../dbus/dbus-connection.c line 2656.", and"[0505/104721.045042:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization", so yes, this solution is working.

**Comment by kisak-valve** [comment]
Hello @Austint30, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
