### ISSUE TITLE
PS3 controller no longer recognized

### ISSUE THREAD

**Issue by Se7enLC** [ValveSoftware/steam-for-linux#5477]
#### Your system information

* Steam client version (build number or date): 1525744445, May 7 2018 18:22:04
* Distribution (e.g. Ubuntu): Kubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Wired PS3 controller is not recognized in Big Picture mode, but it is functional in games.

#### Steps for reproducing this issue:

1. Load steam client
2. Enter Big Picture mode

#### Expected Behavior:

Controller is detected in controller settings, can be used to navigate the UI

#### Current Behavior:

Controller is not detected or functional in the Big Picture UI. Controller does function inside games.

#### Additional Information

- Controller is fully-functional using jstest.
- Was previously working without issue, possibly before most recent beta steam application update.
- I opted out of the beta and allowed the application to "update" to the non-beta release. The controller was fully functional in that release (1522709999, April 2 2018 15:23:55)

**Comment by brain-anti-freeze** [comment]
This update did fix my XBoxOne S controller not being detected however my Nintendo Switch Pro controller is not recognised (either when connected by USB or bluetooth).

**Comment by brain-anti-freeze** [comment]
I'd even say there is a new issue, when the Pro connector is attached (but not recognised) Steam and Xbone controllers are detected in Steam and work the UI but are not detected in games (for instance Rocket League) although if I launch Rise of the Tomb Raider it behaves like up and left were being held down.  With the Pro disconnected, behaviour is normal in most games but RotTR does not recognise any game pad is connected.

**Comment by kisak-valve** [comment]
Hello @brain-anti-freeze, please open a separate issue report for the Nintendo controller issue so that it can be tracked properly.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2018-05-18](https://store.steampowered.com/news/40244/) Steam stable client update.

**Comment by Se7enLC** [comment]
I just got a chance to test the May 18th beta, PS3 controller is detected again.
