### ISSUE TITLE
steam client randomly stuck

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#5480]
#### Your system information

* Steam client version (build number or date): 1525918068
* Distribution (e.g. Ubuntu): Fedora 29
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Regularly steam client hang. Only ```kill -p `pidof steam` ``` can close freezed steam client.

#### Steps for reproducing this issue:
No exactly instruction for reproducing.
But often it occurs after playing in a game.

[steam client backtrace](https://github.com/ValveSoftware/steam-for-linux/files/1993066/steam-backtrace.txt)

I can make more accurate backtrace if you provide debug symbols for steam client.

```
$ inxi -bM
System:    Host: localhost.localdomain Kernel: 4.17.0-0.rc3.git4.1.fc29.x86_64 x86_64 bits: 64
           Desktop: Gnome 3.29.1 Distro: Fedora release 29 (Rawhide)
Machine:   Device: desktop System: Gigabyte product: Z87M-D3H serial: N/A
           Mobo: Gigabyte model: Z87M-D3H serial: N/A UEFI: American Megatrends v: F11 date: 08/12/2014
Battery    hidpp__0: charge: N/A condition: NA/NA Wh
CPU:       Quad core Intel Core i7-4770 (-MT-MCP-) speed/max: 1979/3900 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Vega 10 XT [Radeon RX Vega 64]
           Display Server: wayland (X.org 119999.5 ) drivers: modesetting,ati (unloaded: fbdev,vesa)
           Resolution: 3840x2160@59.98hz
           OpenGL: renderer: Radeon RX Vega (VEGA10, DRM 3.25.0, 4.17.0-0.rc3.git4.1.fc29.x86_64, LLVM 6.0.0)
           version: 4.5 Mesa 18.1.0-rc3
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
Drives:    HDD Total Size: 16241.0GB (19.6% used)
Info:      Processes: 424 Uptime: 2:55 Memory: 13125.4/32037.0MB Client: Shell (bash) inxi: 2.3.56 
```

**Comment by kisak-valve** [comment]
This issue is a regression in xorg server 1.20 (and rc's).

**Comment by NTMan** [comment]
Can you help me reported about this issue to appropriate developers?
I reported about this problem here: https://bugs.freedesktop.org/show_bug.cgi?id=106472
But no one's replied to me.
Maybe I described the problem poorly?
Do you see in the backtrace where the hang are occurred?
Can you add snip with information where stuck are occurred in XWayland ?
Big thanks.

**Comment by kisak-valve** [comment]
https://patchwork.freedesktop.org/patch/223324/ potentially fixes this issue.

**Comment by Silur** [comment]
Confirmed, on an up-to-date arch, wayland, nvidia 396.24 system
most likely a mesa issue

**Comment by kisak-valve** [comment]
Hello @Silur, do you have an optimus setup / is steam running with mesa?

**Comment by Silur** [comment]
yes I was running dota with `primusrun %command%` flawlessly with steam till yesterday

**Comment by NTMan** [comment]
> https://patchwork.freedesktop.org/patch/223324/ potentially fixes this issue.
I tested this patch several days and can confirm that steam client stuck was gone.

**Comment by kisak-valve** [comment]
Closing as fixed upstream years ago (https://cgit.freedesktop.org/mesa/mesa/commit/?id=fe2edb25dd5628c395a65b60998f11e839d2b458).
