### ISSUE TITLE
Please provide a 64-bit package for macOS

### ISSUE THREAD

**Issue by ShikiSuen** [ValveSoftware/steam-for-linux#5481]
Please provide a 64-bit Steam package this year, so that those of us on macOS don't have to install a bootcamp to run Steam when macOS 10.14 comes out in this October.

Reference: https://support.apple.com/en-ca/HT208436

**Comment by kisak-valve** [comment]
Hello @ShikiSuen, feature requests for Steam-for-mac client are outside of the scope of the steam-for-linux issue tracker. You'll want to post on the forums.

Closing as out-of-scope.
