### ISSUE TITLE
Browsing broken after updating to current version

### ISSUE THREAD

**Issue by hkegittel** [ValveSoftware/steam-for-linux#5484]
#### Your system information

* Steam client version (build number or date): April 2, 2018.
* Distribution (e.g. Ubuntu): Slackware Linux 64 bit, 14.2.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have been using Slack 14.2 (64 bit) with Steam, and it worked fine with previous versions of Steam at the beginning of the year. After some months without logging in, I started Steam again and updated its client to the latest version. Now its internal browser doesn't work. The loading wheel appears in the upper right corner, but no HTML ever comes to the window. For example, the store loads endlessly without showing anything. Player profile never shows. Games in my library, however, launch and update without any problems.

#### Steps for reproducing this issue:

Just clicking in profile, store, community or other web features of the client.

**Comment by kisak-valve** [comment]
Hello @hkegittel, please put `/tmp/dumps/<username>_stdout.txt` and `~/.local/share/Steam/logs/cef_log.txt` into [gists](https://gist.github.com/) and provide a link to them.

**Comment by hkegittel** [comment]
Here they are.
https://gist.github.com/hkegittel/0c13bf803884c9d4175af318a63db224

**Comment by kisak-valve** [comment]
`[0512/183810.768675:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.` is the line of interest here, which means you're hitting #5311.

Manually pinning libnss like https://gist.github.com/johndrinkwater/bfbdea56e5b3730cd00809c9503c3cfc should let you get past that issue (the path to steam will differ from this gist).

**Comment by kisak-valve** [comment]
Closing in favor of the existing issue report.
