### ISSUE TITLE
Steam no longer detects Logitech F310 gamepad

### ISSUE THREAD

**Issue by ashleybone** [ValveSoftware/steam-for-linux#5487]
#### Your system information

* Steam client version (build number or date): May 16, 2018
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, currently up-to-date

#### Please describe your issue in as much detail as possible:
I have a Logitech F310 gamepad which has worked with Steam on Linux for several years.  After installing the May 16 2018 Steam update, the gamepad is no longer detected.  When I open Controller Settings, it displays the message "No Controllers Detected".

When I launch Hollow Knight from Steam, it does detect the gamepad, and plays normally. However, Iconoclasts doesn't see the gamepad at all.  Prior to this Steam update, Iconoclasts worked normally with my gamepad.

#### Steps for reproducing this issue:

1. Launch Steam
2. Go to Controller Settings.  The controller is not detected.

**Comment by Daddoggety** [comment]
Have the same gamepad, seems to work for navigation and gameplay but doesn't get detected in controller settings as ashleybone has reported.

**Comment by ashleybone** [comment]
This issue is fixed for me as of the 2018-05-18 client update (release update, not beta).

**Comment by kisak-valve** [comment]
Closing as fixed in the [2018-05-18](https://store.steampowered.com/news/40244/) Steam stable client update.
