### ISSUE TITLE
Distorted fonts in the Steam launcher.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5497]
#### Your system information

* Steam client version (build number or date):"Apr  2 2018 15:23:43"
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
The fonts in the Steam UI is distorted, like this:
![2018-05-25-115610_1152x864_scrot](https://user-images.githubusercontent.com/31236558/40525561-5061782a-5fd0-11e8-8dd1-98b376b0590f.png)
Notice the menu bar.
[error.log](https://github.com/ValveSoftware/steam-for-linux/files/2037946/error.log) and 
[assert_20180525115726_22.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/2037953/assert_20180525115726_22.dmp.gz)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by martmists** [comment]
You might be missing some essential fonts. Try installing the default ones, as well as Noto Fonts which can replace most fonts that you might be missing after that.

**Comment by kisak-valve** [comment]
Hello @pthfdr-42, do you have the fonts-liberation package?

**Comment by pthfdr-42** [comment]
pthfdr:/u/h/pthfdr> fc-list
    /usr/share/fonts/truetype/Anonymous.ttf: Anonymous Pro:style=Regular
    /usr/share/fonts/X11/suxus-iso-8859-1.bdf: suxus:style=Regular
I only have 2 fonts installed because I do not need the extra fonts.  
In privious versions (several monthes ago), Steam could fall back to the default sans/serif/monospace font.  
I think that you should make Steam to fallback to a usable font, like what is displayed in the game list (in this example, Anonymous Pro).

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
