### ISSUE TITLE
Changing download speed trigger "Restart Steam" dialog

### ISSUE THREAD

**Issue by WalkySVK** [ValveSoftware/steam-for-linux#5499]
#### Your system information

* Steam client version (build number or date): 1527129857
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Changing maximum download speed and saving setting trigger "Restart Steam" dialog although Steam doesnt need to be restarted and changes will take effect immediately. On windows it doesnt ask for restart after changing download speed.

**Comment by kisak-valve** [comment]
Hello @WalkySVK, this issue is already being tracked at #5495. Closing as a duplicate.
