### ISSUE TITLE
client language reset after update

### ISSUE THREAD

**Issue by Translator5** [ValveSoftware/steam-for-linux#5501]
#### Your system information
Distribution: Manjaro
packed at: May 18 2018 14:50
Steam API: v018
version: 1526683293
Steam client beta: No
Have you checked for system updates?: Yes

For several months (1/2 year) I receive numerous problems with the Russian translation of steam client.
In the past, the last menu item of the main-window of steam as well as the menu-item at the button of the tray-icon-menu (exit) did not simply exit my steam but also reset my login data. By the way if I use the German or English version of steam the "automatic-login"-function works perfect.
But seems like this was been fixed for some weeks now. Thanks!

A other issue I receive is that my language setup of Russian do fall back to English on updating my client. This Issue is still not fixed for a long time. May somebody reported it already, but I could not find something of this topic in the issues-section.
So, after every setup of language to Russian and closing the client it works on same session.
But after a new PC restart or a new automatic restart of the client in subsequention of a update, the language setup falls back to English.
It would not that critical, if not all my games would not be updated with false language-setup.

**Comment by kisak-valve** [comment]
Hello @Translator5, this issue already being tracked at #5035 / #5030. Closing as a duplicate.
