### ISSUE TITLE
Request: "First-run install" process that checks for and installs dependencies

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/steam-for-linux#5504]
In the Windows version of Steam, many games—probably most—will do a "first-run installation" process when you launch them the first time that installs various frameworks and such required to run the game. Usually a redundant, obsolete copy of DirectX, Visual C++ Redistributable, etc.

Well, sometimes Linux games have their own equivalent of that. Off the top of my head, *Aperture Tag* [requires one called libtcmalloc-minimal4:i386](https://steamcommunity.com/app/280740/discussions/0/350533172680722714/). Why? Who knows. And I'm sure there are others that don't typically register because most, but not all, distros already have them built in, but the games depend on them nonetheless and not having them means pulling out hair wondering why the heck this thing isn't working.

Since the structure of Steam's internal filesystem precludes just bundling the necessary packages with the game itself, the next best thing would be to have the client do its own version of the First-Run Install, which checks for known dependencies and runs an apt-get or pacman script in the background if any are missing. Granted, this would entail doing one of those sudo popups because Linux is stricter about that sort of thing, but it's still a minimal hassle (and won't likely happen to any given user more than once or twice, ever).

**Comment by OvermindDL1** [comment]
> Since the structure of Steam's internal filesystem precludes just bundling the necessary packages with the game itself

Huh, side idea, flatpak'ing or snaps of linux games would be a useful distribution method...

**Comment by kisak-valve** [comment]
Hello @stevethepocket, Aperture tag is mildly misconfigured by the game's dev(s) (see https://github.com/ValveSoftware/steam-for-linux/issues/6179#issuecomment-478279261). The Steam runtime should provide all necessary common dependencies, beyond that it, any dependency issues need to be evaluated on a per-game basis.
