### ISSUE TITLE
[L4D2] periodic fps issues

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#5506]
#### Your system information

* Steam client version (build number or date): May 18 2018, at 14:50:44 (but for a while before)
* Distribution (e.g. Ubuntu): Fedora (several releases)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Vendor ID:           AuthenticAMD
CPU family:          21
Model:               19
Model name:          AMD A8-5550M APU with Radeon(tm) HD Graphics

w/16GB RAM

#### Please describe your issue in as much detail as possible:
This has been happening since I started playing Left 4 Dead 2 on Linux about 4 years ago. I just haven't gotten around to reporting it until now.

Periodically (almost always in the first couple chapters of Dark Carnival and throughout Cold Stream, but it can happen any time on any map), the frame rate drops to around 20-30fps (supposedly, but it really feels more like 5fps) and stays there until either the chapter/map changes or I hide L4D2 for several seconds. `top` reports that a thread named MatQueue0 is throttling my CPU. When it stops using so much CPU%, I can switch back to L4D2 and my frame rate is back to normal.

This video shows it <https://www.youtube.com/watch?v=ci_0MZ0Z4MI>

**Comment by kisak-valve** [comment]
Hello @undeference, let's track this issue in the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2609.
