### ISSUE TITLE
steam client takes a very long time to close

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5507]
When I close the steam client which was running (usually with some dota2) for several hours, it takes ages to shutdown.
(up to several tens of seconds). I don't use the shader cache feature.
(bleeding edge custom distro: linux amd-staging-next, drm/mesa/xserver/xf86-video-amdgpu all git usually no older than a week.
I had a look at top output while it happened, the resident memory usage is sky rocketing as well as the cpu usage for the steam process (the 32 bits one).
Anybody has the same issue?

**Comment by Plagman** [comment]
People have reported an issue where Xorg spikes up to lots of CPU use for a while when trying to exit Steam; is this what you're seeing?

**Comment by sylware** [comment]
Just checked: yes the CPU usage of Xorg is sky rocketting, as well as the
resident size of the steam 32 bits process.

**Comment by kisak-valve** [comment]
Hello @sylware, yes, this reads like the issue being tracked at #5279. Closing in favor of the existing report.
