### ISSUE TITLE
Steam refuses to start with NVIDIA driver 396.24

### ISSUE THREAD

**Issue by MakotoTheKnight** [ValveSoftware/steam-for-linux#5509]
#### Your system information

* Steam client version (build number or date): 1527879669
* Distribution (e.g. Ubuntu): Pop!_OS 18.04 (analogous to Ubuntu 18.04) - 64-bit install
* Opted into Steam client beta?: [Yes/No] No (wish I did)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Attempting to run the Steam client or any games as a shortcut results in a segmentation violation in dmesg.

What I see now instead of my game is:

    [ 5269.544804] steam[43470]: segfault at 0 ip 00000000ed9b4e39 sp 00000000ff886fc0 error 4 in vgui2_s.so[ed963000+291000]

Not entirely clear what could be causing this.  I wonder if this has anything to do with NVIDIA dropping 32-bit support?

#### Steps for reproducing this issue:

1.  Ensure that NVIDIA 396.24 is installed
2.  Start Steam
3.  `dmesg | tail` will show the error in dmesg

**Comment by kisak-valve** [comment]
Hello @MakotoTheKnight can you check if any 32 bit OpenGL application such as glxinfo from `mesa-utils:i386` works? nVidia has dropped support for 32 bit kernels, but not 32 bit applications.

If you can find any minidumps (commonly found in `/tmp/dumps/`) related to this issue, please throw them into an archive and drag and drop the archive into this report.

**Comment by kisak-valve** [comment]
You should read that as your 32 bit opengl driver being incomplete or misconfigured and needs to be fixed before using steam.

**Comment by trou** [comment]
For reference, on Debian Sid, I fixed the problem by installing the `nvidia-driver-libs-i386` package.

**Comment by vans163** [comment]
I have the same issue with 396.24, everything works fine on the first run. But if you exit steam + run it again you get:

```
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  31
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  33
xerror_handler: X failed, continuing
```

And it never starts again. Its probably calling some deprecated or changed GLX function in the 32bit opengl driver. Since the damn opengl spec is so annoying to keep track of (nvidia, amd, intel, windows, mac, linux,..).

**Comment by paroj** [comment]
```sudo apt install nvidia-driver-396:i386```

**Comment by felisucoibi** [comment]
Having same problem with ubuntu 18.10 trying sudo apt install nvidia-driver-390:i386

**Comment by felisucoibi** [comment]
At the end i fixit doing this:
sudo apt-get install libnvidia-gl-390:i386

**Comment by b4ux1t3** [comment]
Note: For Arch/Manjaro users, the package needed to fix this issue is `lib32-nvidia-390xx-utils`.

**Comment by kisak-valve** [comment]
Hello @MakotoTheKnight, are you still experiencing this issue on an up to date system? The issue you encountered at the time is that `nvidia-driver-###` does not reliably pull in `libnvidia-gl-###:i386` for 32 bit userspace support, which is a distro packaging issue.

**Comment by MakotoTheKnight** [comment]
Hi @kisak-valve , I don't believe this is a problem anymore.  On the latest versions of the Steam client (1599174997) running Pop!_OS 20.04 with Nvidia driver version 440.100, I'm able to start and launch Steam.

**Comment by kisak-valve** [comment]
Thanks for the follow up. Closing.
