### ISSUE TITLE
Steam prints repeatedly a error message in log and pages fail to load

### ISSUE THREAD

**Issue by FurretUber** [ValveSoftware/steam-for-linux#5514]
#### Your system information

* Steam client version (build number or date): Jun 1 2018, 10:51:49
* Distribution (e.g. Ubuntu): Xubuntu 18.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Steam client may, after some time, have an error and generate a insanely enormous amount of error messages like:
../common/html/chrome_ipc_server.cpp (501) : Assertion Failed: !"Invalid PID for wait"

#### Steps for reproducing this issue:

1. Open Steam and access your account
2. Use Steam/play games for a while
3. Try to access Store or Forum of a game
4. Notice the messages in the log and the failure of pages loading

This is generating extremely big log files. One example can be seen at: https://mega.nz/#!NtwTwabb!cnOjJDnudkn_ti4Iv-y1UNJUiYo3w98vlW1s9Hbl38I

Please be aware, the log is very big.

**Comment by kisak-valve** [comment]
Hello @FurretUber, are you still experiencing this issue on an up to date system?

**Comment by FurretUber** [comment]
Hi @kisak-valve, I'm no longer facing this problem. I can keep Steam open for long and it works well.

**Comment by kisak-valve** [comment]
Thanks for the follow up, closing.
