### ISSUE TITLE
Moving this issue tracker after sellout

### ISSUE THREAD

**Issue by facePlanted** [ValveSoftware/steam-for-linux#5517]
So now that you know who, did sellout to you know who, can we please move this issue tracker to a better place ?

**Comment by dearlygparted** [comment]
Time to move to Gitlab, I guess.

**Comment by facePlanted** [comment]
https://docs.gitlab.com/ee/user/project/import/github.html

**Comment by Fibbles** [comment]
Not everyone is an anti-MS zealot. Unless there's a deterioration in the service provided by GitHub there is zero reason to move.

**Comment by dearlygparted** [comment]
> Not everyone is an anti-MS zealot. 

As you can see, this was labelled as a "question". It's not about people being zealots, but I think people are interested in Valve's take on this and what their reaction will be (not that they are known for being vocal about those things). 

Remember, Valve was founded by former longtime Microsoft employees Gabe Newell and Mike Harrington. And Gabe Newell once described Windows 8 as "a catastrophe for everyone in the PC space". 

> Unless there's a deterioration in the service provided by GitHub there is zero reason to move.

https://help.github.com/articles/github-terms-of-service/
https://help.github.com/articles/github-privacy-statement/

If either of those change in a way which is unacceptable, then there is plenty reason to move.
