### ISSUE TITLE
Rocket League- Misplaced Steam Overlay

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#5518]
#### Your system information

i7 7700 HQ
Gtx 1050 - Nvidia 396.24.02 driver
Kernel 4.15

* Steam client version (build number or date): 1527879669 , Jun 1 2018
* Distribution (e.g. Ubuntu): Linux Mint 
* Opted into Steam client beta?: NO
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam Overlay is misplaced with Rocket League on Linux. Until you alt-tab the game or going Shift-tab to see full Steam overlay, it stays like this.

![ekran goruntusu - 2018-06-05 17-38-18](https://user-images.githubusercontent.com/24878978/40983142-a129e024-68e7-11e8-8d77-f814c1106127.png)
![ekran goruntusu - 2018-06-05 17-39-18](https://user-images.githubusercontent.com/24878978/40983151-a66a57b2-68e7-11e8-834a-e2544952cc14.png)

#### Steps for reproducing this issue:

1. Steam on Linux
2. Rocket League on Linux
3. Launch

**Comment by r3pek** [comment]
It's been like this since the game came out to Linux AFAIR

**Comment by Leopard1907** [comment]
@r3pek Than it is really sad when you think how much time passed since release and still broken

**Comment by Leopard1907** [comment]
@TheSIlentLink Rocket League devs won't fix it until someone who uses " SteamOS " prove them it is the same on there too.

Because when you report a bug to them , they say they only support SteamOS , Linux support is in beta.

That is where @Plagman comes in.

**Comment by TheSIlentLink** [comment]
Which means that a fix from them is extremely unlikely seeing as SteamOS uses big picture mode and that has a different overlay.

**Comment by Leopard1907** [comment]
@TheSIlentLink Or Valve Linux devs can add a workaround for this app , exclusively. Since everygame has a unique app id , that won't cause a mess. No need to set it as a global SO exception , just for that app.

**Comment by Plagman** [comment]
Looks like this is a Steam bug in any case, so I wouldn't bother the Psyonix guys with it; thanks for the report.

**Comment by Leopard1907** [comment]
@Plagman No problem.

**Comment by Leopard1907** [comment]
Hi @Plagman 

Besides that issue still exists , looks like it also affects Steam Link Android app too. I assume Steam Link app captures game streaming via Steam Overlay because until pressing Shift+Tab ( opening full overlay ) it make game streamed like this :

![screenshot_2018-11-03-01-37-53](https://user-images.githubusercontent.com/24878978/47961607-723cdf00-e01f-11e8-8c99-41f3421653c0.png)

After doing Shift+Tab workaround:

![screenshot_2018-11-03-01-37-06](https://user-images.githubusercontent.com/24878978/47961614-8b459000-e01f-11e8-9f78-fbf187b549bd.png)

**Comment by Leopard1907** [comment]
Also another game is suffering from this.

LISA- A native Linux game

When you hit F1 for options , Steam Overlay collapses into lower left corner of screen.

Shift+Tab is the same workaround.

**Comment by Leopard1907** [comment]
https://store.steampowered.com/app/335670/LISA/

**Comment by Leopard1907** [comment]
Problem still exists.

**Comment by libcg** [comment]
I can confirm the issue here too. It happens with both radeonsi and iris drivers.

**Comment by Leopard1907** [comment]
Issue still exists , latest Steam client beta.

**Comment by Leopard1907** [comment]
Since native version of this game won't get any future updates ( enden Linux and Mac support ) , i'm closing this. I refunded this game and don't have chance to test if it has the same issue with Proton ( probably not ).

Closing.
