### ISSUE TITLE
After going into Big Picture Mode , Steam Overlay font changes

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#5519]
#### Your system information

i7 7700 HQ
Gtx 1050 - Nvidia 396.24.02 driver
Kernel 4.15

* Steam client version (build number or date): 1527879669 , Jun 1 2018
* Distribution (e.g. Ubuntu): Linux Mint 18.3 Cinnamon
* Opted into Steam client beta?: NO
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Problem is just happens like i said on title.

It looks like this.

![ooo](https://user-images.githubusercontent.com/24878978/40985796-8654ac60-68ed-11e8-8750-ae7aadcde17d.png)

#### Steps for reproducing this issue:

1. Go into BPM for either configuring controller or something else
2. Log out from BPM to normal client mode
3. Enjoy the view

**Comment by Leopard1907** [comment]
@OvermindDL1 Well , it happens all the time for me. Going in BPM triggers it.

**Comment by TheSIlentLink** [comment]
I have noticed this too. The only fix I have found is to restart steam.

**Comment by Leopard1907** [comment]
I can't repro this issue anymore. Seems like it is fixed. Closing.
