### ISSUE TITLE
The Steam application is not recognized the Switch Pro Controller

### ISSUE THREAD

**Issue by Guitto** [ValveSoftware/steam-for-linux#5520]
#### Your system information

* Steam client version (build number or date): Jun 1 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: Yes [Yes/No]
* Have you checked for system updates?: Yes [Yes/No]

#### Please describe your issue in as much detail as possible:

My Switch Pro Controller is not recognized by Steam Application. I can see it on the Bluetooth, it works on my system, i can calibrate it on jstest, but it just don't work on my Steam on Linux. On Windows, works like a charm. Its curious to see, that Xbox One Controller works on Steam in Ubuntu.

I did everything: Edited and create rules on uDev (steam://openurl/http://steamcommunity.com/app/353370/discussions/0/490123197956024380/)

I opted for beta client, but nothing works. Steam don't recognize my Pro Controller. On Nintendo Switch, it works fine.
It just work when i open Steam as a Root, then, Steam recognized it. And Works, but i have to install all my games over and over again, and Steam client ups to 2gb on installation folder when a i did it.
I opened an ticket on Steam Support, and Mat did everything to help me, but without success.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I conected and pair my Pro Controller on the System. It works ok. Open Steam, and try to map buttons, but it says my controller is not connected, even if it is connected on Bluetooth and calibrate on jstest. I would like to use it normally, without the necessity to login as a Root.

#### Steps for reproducing this issue:

1. Pair my Pro Controller
2.  Open Steam
3. Steam fails to recognize it

**Comment by kisak-valve** [comment]
Hello @Guitto, the symptoms you've described does hint that this is still a udev issue.

To cover the basics, are you using the Valve-provided steam package or the distro-provided steam package? If you're using the distro-provided steam package, do you also have the steam-devices package installed?

Please copy the udev rule you've written to a [gist](https://gist.github.com/) and include a link to it in this issue report.

**Comment by Guitto** [comment]
Hello @kisak-valve 
I think im using the distro-provided Steam Package(i've installed it on Terminal - sudo apt-get install steam)
I dont know anything about Steam-Devices, only now, when you replied to me. How can i install it on my system?

https://gist.github.com/Guitto/c4b471c80b1e42206a12839ab93d2cb2

Here the rules that i've used on uDev. Thanks for help!

**Comment by kisak-valve** [comment]
I'd like to highlight `make sure you replace 'pgriffais' with a group that the user that runs Steam belongs to` from the example. The line under it should be adjusted appropriately or you can start over with the udev rule from the `steam-devices` package.

For that, you should be able to move your udev rule somewhere for safe keeping, install the steam-devices package with `sudo apt install steam-devices`, then adjust /lib/udev/rules.d/99-steam-controller-perms.rules from the package to include the newer Switch Pro lines.

**Comment by Guitto** [comment]
@kisak-valve before your reply, i've installed steam-devices on terminal and hell yeah! IT NOW WORKS! FINALLY! MAN, many many many thanks!

**Comment by kisak-valve** [comment]
Closing per the last comment.
