### ISSUE TITLE
Client asks you to login in order to ignore a curator, despite being logged in already.

### ISSUE THREAD

**Issue by pardish** [ValveSoftware/steam-for-linux#5521]
#### Your system information

* Steam client version (build number or date): Jun 1, 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

On the Store Page, when coming across the "Suggested Curators" section, you can choose to follow the curator or click "ignore this curator". Clicking ignore, states that "you must be logged in before you can ignore a Steam curator." This is despite already being logged into the client. On the web version of Steam, it does not have this issue.

#### Steps for reproducing this issue:

1. Log into Steam client
2. Go to Store home
3. Scroll down until you see a "Suggested Curators" section.
4. Click "Ignore this curator".

**Comment by kisak-valve** [comment]
Hello @pardish, per "Fixed some cases users would not auto-login to Steam web pages inside the Steam Client" in the [2018-08-13](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1706188320728546746) Steam client beta update, please retest this issue.

**Comment by pardish** [comment]
Tested with 2018-08-13 Steam client beta update, it's working. Thanks, you can close this now.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.

**Comment by LeonardQuirm** [comment]
Has this fix reached the main public release yet?  I'm still seeing this issue today - my client claims it is up to date when using Check for Steam Client Updates, but I'm not on the Beta.
