### ISSUE TITLE
Steam client beta doesn't load pages properly or at all

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#5526]
#### Your system information

* Steam client version (build number or date): 
![screenshot_2018-06-13_06-27-12](https://user-images.githubusercontent.com/6024315/41348642-e70189bc-6ed2-11e8-8c8d-d6b9f323594e.png)
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* System Info:  https://gist.github.com/nightsky30/4f3844e3730f82dc83b168a1eb9b1a04

#### Please describe your issue in as much detail as possible:
After the latest beta update, pages are loading very very slowly or not at all.

#### Steps for reproducing this issue:

1. Update to the Jun 12 beta client build
2. Start Steam client
3. Attempt to visit a page such as the CSGO workshop or store
4. Page won't load properly.

![screenshot_2018-06-13_06-21-31](https://user-images.githubusercontent.com/6024315/41348866-9f30171a-6ed3-11e8-867d-fdbbf70af0d7.png)

**Comment by kisak-valve** [comment]
Hello @nightsky30, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by nightsky30** [comment]
Thank you @kisak-valve I've now added the system info.

#1
I also want to mention that the pages are loading now, and it might have been a change between the June 12th Update and June 13th Update #1.  I found this in the comments from another user regarding June 13th Update #1:
![screenshot_2018-06-13_18-12-39](https://user-images.githubusercontent.com/6024315/41383533-e153e46a-6f36-11e8-9050-f67e2994476d.png)

#2
After June 13th Update #2 a few moments ago I was notified that I had an item in my inventory.  I selected the green envelope menu and attempted to access my inventory to receive the following error:
![screenshot_2018-06-13_18-17-34](https://user-images.githubusercontent.com/6024315/41383688-960dcc68-6f37-11e8-98d7-1bc7c7d95e5d.png)

**Comment by kisak-valve** [comment]
Hello @nightsky30, are you still experiencing this issue on an up to date system?

**Comment by nightsky30** [comment]
Yes, this appears fixed. Thanks
