### ISSUE TITLE
Window dimensions are minimal from steam self-updater update comment links

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#5528]
#### Your system information

* Steam client version (build number or date): 
![screenshot_2018-06-13_18-35-20](https://user-images.githubusercontent.com/6024315/41383895-8e1a1c2c-6f38-11e8-8567-fdebec9ce064.png)
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* System Info:  https://gist.github.com/nightsky30/4f3844e3730f82dc83b168a1eb9b1a04

#### Please describe your issue in as much detail as possible:
When I clicked on the "See all ## comments" link to view the comments from a recent update (June 13 Update 1), it opened a new window to the comments section, but it was opened with minimal window dimensions.  The width and height of the window were as small as could possibly be.

#### Steps for reproducing this issue:

1. Receive a Steam Self-updater notification
2. Expand one of the recent updates in the window's list
3. Select the "See all ## comments" link
4. Notice the small window dimensions of the popup browser window that is created

![screenshot_2018-06-13_18-11-00](https://user-images.githubusercontent.com/6024315/41384171-e9d7f10a-6f39-11e8-934e-9b11f2101e84.png)

**Comment by nightsky30** [comment]
I'll try and remember to check after then next update

**Comment by nightsky30** [comment]
Yep, seems fixed.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
