### ISSUE TITLE
Disconnected from Steam client when attempting to connect to a community server.

### ISSUE THREAD

**Issue by tunanachos** [ValveSoftware/steam-for-linux#5529]
#### Your system information

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3600 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.9.105-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  i3
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.24
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  15998 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  108222 Mb
    Largest Free Hard Disk Block:  87841 Mb
    VR Headset: None detected

Recent Failure Reports:

* Steam client version (build number or date): Jun 13 2018, at 17:03:50 / Steam API: v018
* Distribution (e.g. Ubuntu): Manjaro (Arch) 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

_(I'd like to start by saying I'm not too bright and have attention deficit disorder, so forgive me if I come off a little thick or ask things already answered or quite clear)_

While attempting to connect to community servers on Garrys Mod, Team Fortress 2 and CS:S I get disconnected from the Steam client.

I have tried **everything** from reinstalling my entire OS, removing mods and reinstalling everything to contacting both Steam and FacePunch studio. 

#### Steps for reproducing this issue:

1. Launch Steam
2. Open Garrys Mod and connect to a community server
3. done

**Comment by kisak-valve** [comment]
Possibly related to #5200 / #4971 / #5163.

**Comment by JaQuEsOuzi** [comment]
and how do we fix that?

**Comment by kisak-valve** [comment]
Hello @tunanachos, @JaQuEsOuzi, are either of you still experiencing this issue on an up to date system?

**Comment by tunanachos** [comment]
I haven't played gmod in a long time however the last time I played it I don't recall having this issue.

Don't take my word for it being fixed, I'm just fairly certain it wasn't an issue last time I played. Hopefully someone will be able to post a more helpful comment :)

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as outdated.
