### ISSUE TITLE
Build x64 binaries

### ISSUE THREAD

**Issue by lostiniceland** [ValveSoftware/steam-for-linux#5530]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): OpenSuse Leap 15
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue

All Linux Distributions for Desktop environments have ditched their 32bit Versions. The default is finally x64. Installing Steam requires a plethora of 32bit libraries which just clutters the system and is by now completely unnecessary.

I've filed a bug at Opensuse since I've expected they build the Steam RPM from source, but they confirmed that most are using the provided binaries.

32bit Linux is only used for some embedded hardware (ARM, etc) which is no target platform for Steam.
Please release a x64 Steam client...at least for Linux.

**Comment by kisak-valve** [comment]
Hello @lostiniceland, this feature request is already being tracked at #3518. Closing as a duplicate.
