### ISSUE TITLE
Scaled Content - Steam Browser

### ISSUE THREAD

**Issue by annacmr** [ValveSoftware/steam-for-linux#5531]
#### System Information

* Steam API: v018
* Distribution: Ubuntu 16.04.3 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Detailed Issue:

Hello y'all! Although my computer is very simple I can play DoTA 2 perfectly fine. I have this issue a long time, but it now started to bother me: my steam browser inside DoTA 2 is expected to be at a 100% scale, but it's actually at 125-150% for some contents! 

![screen](https://user-images.githubusercontent.com/13593456/41491533-2a1c2f1e-70e9-11e8-9702-1e2c7e1a1ba1.png)

Is there anything I can do? [This post](https://github.com/ValveSoftware/Dota-2/issues/1178) says this issue was resolved in June, 2017, but the problem still remains for me. Thank you!

**Comment by kisak-valve** [comment]
Hello @annacmr, since this is an issue seen in Dota 2, let's track it in the Dota 2 issue tracker at https://github.com/ValveSoftware/Dota-2/issues/1464.
