### ISSUE TITLE
Team Fortress 2 - Having p11-kit-modules:i386 installed on debian stretch will cause segfault in TF2 

### ISSUE THREAD

**Issue by sovietnorm** [ValveSoftware/steam-for-linux#5536]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Debian Stretch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

`hl2_linux[12032]: segfault at 58494b50 ip 00000000f75ca3d7 sp 00000000ff92368c error 4 in libc-2.24.so[f748d000+1b1000]`

It will very consistently crash at that address on my system.

I was able to find the issue with 

`    GAME_DEBUGGER="strace -f -e trace=open -o strace.log" %command%`

set as the launch options and looking at the strace file. The last file loaded was

`/usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so`

And then a hard malloc error occurs, causing death.

Other files loaded right before this are;

```
13660 open("/usr/lib/x86_64-linux-gnu/libfakeroot/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/lib/i386-linux-gnu/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/tls/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/sse2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/lib/i386-linux-gnu/libffi.so.6", O_RDONLY|O_CLOEXEC) = 37
13660 open("/proc/sys/crypto/fips_enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
13660 open("/dev/urandom", O_RDONLY)    = 37
13660 open("/etc/pkcs11/pkcs11.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/home/jason/.config/pkcs11/pkcs11.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/home/jason/.config/pkcs11/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/etc/pkcs11/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13660 open("/usr/share/p11-kit/modules", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 38
13660 open("/usr/share/p11-kit/modules/gnome-keyring.module", O_RDONLY|O_CLOEXEC) = 39
13660 open("/usr/share/p11-kit/modules/p11-kit-trust.module", O_RDONLY|O_CLOEXEC) = 39
```

Immediately after, it will die.

#### Steps for reproducing this issue:

1. Have steam installed
2. Have  p11-kit-modules:i386 (0.23.3-2) installed
3. Attempt to start tf2
4. Watch tf2 die.
5. Remove p11-kit-modules:i386
6. Start tf2
7. Watch TF2 start

**Comment by kisak-valve** [comment]
Hello @sovietnorm, let's track this issue in the Source-1-Games issue tracker at https://github.com/ValveSoftware/Source-1-Games/issues/2619.
