### ISSUE TITLE
Steam prevents system shutdown, Linux Mint 19 Cinnamon (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Fr6jDJF** [ValveSoftware/steam-for-linux#5538]
#### Your system information

* Steam client version (build number or date): 1528497815
* Linux Mint 19 Cinnamon(Ubuntu 18.04)
* Nvidia970 nvidia-driver-390 / 390.48-0ubuntu3
* Opted into Steam client beta?: [Yes&No] issue occurs on both versions
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
While a shutdown issue was being somewhat fixed on Mint 18.3(Ubuntu 16.04) with the stream beta client(I couldn't find that issue here on GitHub atm.)

On the Ubuntu 18.04 based Linux Mint 19 it goes beyond some shutdown delay/interruption, it seems the system cant do it's full shut down while steam was/is running. This only occurs when Steam is active while triggering a system shutdown.

Tail output:
System-shutdown: 30 output lines suppressed due to rate limiting
Systemd-shutdown[1] Syncing filesystems and block devices.
Systemd-shutdown[1] Sending SIGTERM to remaining processes.
Systemd-Journald[482] Received SIGTERM from PID 1 (system shutdown)
Systemd-shutdown[1] Sending SIGKILL to remaining processes...
Systemd-shutdown[1] Unmounting filesystems
Ext4-fs(dm-0): Re-mounted.Opts:errors=Remount-RO,data=ordered
Systemd-shutdown[1] All filesystems unmounted
Systemd-shutdown[1] Deactivating swaps
Systemd-shutdown[1] All swaps deactivated
Systemd-shutdown[1] Deattaching loop devices
Systemd-shutdown[1] All loop devices deactivated
Systemd-shutdown[1] Deattaching DM devices
KVM: exiting hardware virtualisation
**_^system Idles/hangs at this point_**

#### Steps for reproducing this issue:

1. Leave Steam active
2. Shutdown the system

**Comment by TheSIlentLink** [comment]
Can confirm I have the same issue on Mint 19 with the cinnamon desktop.

**Comment by kisak-valve** [comment]
Hello @Fr6jDJF, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Fr6jDJF** [comment]
Works fine now with Linux Mint 20c , 5.8.0-29-generic
