### ISSUE TITLE
Steam dies from an illegal instruction with lib32-mesa-18.1.2-1 and CPUs without AVX support

### ISSUE THREAD

**Issue by aumars** [ValveSoftware/steam-for-linux#5539]
#### Your system information

* Steam client version (build number or date): 1528497815
* Distribution (e.g. Ubuntu): Arch Linux x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

```
$ steam
/home/pradana/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/pradana/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on arch  64-bit
/home/pradana/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1528497815)
crash_20180623155823_1.dmp[3140]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180623155823_1.dmp
/home/pradana/.local/share/Steam/steam.sh: line 876:  3137 Illegal instruction     (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20180623155823_1.dmp[3140]: Finished uploading minidump (out-of-process): success = yes
crash_20180623155823_1.dmp[3140]: response: CrashID=bp-a4f40c3c-4e68-4197-aa73-b3bbf2180623
crash_20180623155823_1.dmp[3140]: file ''/tmp/dumps/crash_20180623155823_1.dmp'', upload yes: ''CrashID=bp-a4f40c3c-4e68-4197-aa73-b3bbf2180623''
```

Restarting my machine did not help. The only thing I haven't tried is reinstalling the Steam client.

#### Steps for reproducing this issue:

1.  Run `steam` as user using a terminal.

**Comment by kisak-valve** [comment]
This is an Arch packaging issue for `lib32-mesa` being tracked at https://bugs.archlinux.org/task/58697. As this is an issue outside of Steam, there won't be much more activity here.

Reverting to `lib32-mesa-18.0.4-2` should workaround this issue until it is resolved by the package maintainer.

**Comment by kisak-valve** [comment]
Closing per the last comment.
