### ISSUE TITLE
Steam Client with Steam Controller on GNU/Debian9 Stretch USB and Bluetooth bug issue

### ISSUE THREAD

**Issue by user111222333** [ValveSoftware/steam-for-linux#5540]
#### Your system information

* Steam client version (build number or date): 
Steam Client application Built: Jun 8 2018, at 22:22:39
Steam API: v018
Steam Package Versions: 1528497815

* Distribution (e.g. Ubuntu): 
Host OS:
Linux pc-steam 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
Please note ( ! ): This is a clean default installation. Debian 9 Stretch + GNOME Desktop environment + Steam Client.

* Opted into Steam client beta?: [Yes/No]
Initially Steam Client was installed by default with a NO for beta version.
As an attempt to address the underlying issues with the Steam Controller, Steam Client was instructed to 'join' beta client. It was done via GUI.
Steams Controller Firmware was upgraded with no apparent issues to bring a Bluetooth connectivity.
Issues wit Steam Controller persisted. Steam Client was switched back to a default, non-beta version by using the settings options in GUI.    

* Have you checked for system updates?: [Yes/No]
YES, multiple times. Client as of this ticket submission date, is on the most recent available version. 

#### Please describe your issue in as much detail as possible:
ISSUE
Quiting running Steam Client with connected Steam Controller causes a GNU/Linux Kernel to generate errors. Steam Controller stops responding. 

Host OS:
Linux pc-steam 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

Please note ( ! ): This is a clean default installation. Debian 9 Stretch + GNOME Desktop environment + Steam Client.

Steam Client Version: 
Steam Client application Built: Jun 8 2018, at 22:22:39
Steam API: v018
Steam Package Versions: 1528497815

CONTROLLER TYPE:
Steam Controller - Model 1001

Steam Controller Firmware:
'Wed May 30 15:12:13 2018 (1,527,718,333)

Receiver Firmware Version:
Connected via Cable (0)

Please note ( ! ): Steam Controller is connected via USB cable. Wireless 'dongle' is not used.

CONNECTION TYPE:
Wired via USB bus. 
Config file written per best practices guide published at:
https://steamcommunity.com/app/353370/discussions/0/490123197956024380/

USB ID for the Steam Controller: 
Bus 005 Device 003: ID 28de:1102

USB Dev mapping for Steam Controller:
/dev/input/event14 - Valve_Software_Wired_Controller
/dev/input/event15 - Valve_Software_Wired_Controller
/dev/input/mouse1 - Valve_Software_Wired_Controller

Kernel Messages on event: Steam Controller plugged in to USB port of the host:
Please note ( ! ): Steam Controller connected to USB port AFTER Steam Client is loaded, and running as expected.

[ 1039.489129] usb 5-2: new full-speed USB device number 3 using uhci_hcd
[ 1039.664320] usb 5-2: New USB device found, idVendor=28de, idProduct=1102
[ 1039.664324] usb 5-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1039.664327] usb 5-2: Product: Wired Controller
[ 1039.664329] usb 5-2: Manufacturer: Valve Software
[ 1039.672896] input: Valve Software Wired Controller as /devices/pci0000:00/0000:00:1a.2/usb5/5-2/5-2:1.0/0003:28DE:1102.0003/input/input15
[ 1039.729674] hid-generic 0003:28DE:1102.0003: input,hidraw2: USB HID v1.11 Keyboard [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input0
[ 1039.735478] input: Valve Software Wired Controller as /devices/pci0000:00/0000:00:1a.2/usb5/5-2/5-2:1.1/0003:28DE:1102.0004/input/input16
[ 1039.735822] hid-generic 0003:28DE:1102.0004: input,hidraw3: USB HID v1.11 Mouse [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input1
[ 1039.741516] hid-generic 0003:28DE:1102.0005: hiddev0,hidraw4: USB HID v1.11 Device [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input2
[ 1041.019144] input: Microsoft X-Box 360 pad as /devices/virtual/input/input17

Please note ( ! ): There is absolutely no device connected to the host other than generic wired USB keyboard + Mouse and Steam Controller.
Why Kernel sends message '[ 1041.019144] input: Microsoft X-Box 360 pad as /devices/virtual/input/input17' is unclear and unknown.... 

GAME:
Not Applicable 

CONFIG LINK:
Where would I get that info? 

STEPS
OS boots up. 
Steam Software Initiated.
Controller connected via USB to the host machine. No batteries inserted. 
Controller will be used (users specific reasons) only via USB bus.
Controller recognize by the host OS as expected. 
All functions perform as expected.

When user is done using Steam Software on the host, and software is 'closed', Steam controller changes it's 'behavior'. Moving a finger on the left touch-pad functions as a mouse HID accompanied with a lauder audio feedback.

Shortly after Steam Software exited, controller stops responding, produces a 'power on' sound, and goes in to an endless restart cycle/loop.

Disconnecting and re-connecting controller dos not restore a normal and expected behavior. 

RESULTS
Unable to use Steam Controller as expected and advertised.

EXPECTED
Expected a normal state of operations of the Steam Controller, after Steam Software is exited and started again/re-started. 

ERRORs generated:

Kernel messages (dmesg output):

[ 2632.119107] usb 5-2: new full-speed USB device number 36 using uhci_hcd
[ 2632.292762] usb 5-2: New USB device found, idVendor=28de, idProduct=1102
[ 2632.292765] usb 5-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2632.292766] usb 5-2: Product: Wired Controller
[ 2632.292768] usb 5-2: Manufacturer: Valve Software
[ 2632.301062] input: Valve Software Wired Controller as /devices/pci0000:00/0000:00:1a.2/usb5/5-2/5-2:1.0/0003:28DE:1102.002F/input/input47
[ 2632.359414] hid-generic 0003:28DE:1102.002F: input,hidraw2: USB HID v1.11 Keyboard [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input0
[ 2632.364854] input: Valve Software Wired Controller as /devices/pci0000:00/0000:00:1a.2/usb5/5-2/5-2:1.1/0003:28DE:1102.0030/input/input48
[ 2632.364994] hid-generic 0003:28DE:1102.0030: input,hidraw3: USB HID v1.11 Mouse [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input1
[ 2632.370897] hid-generic 0003:28DE:1102.0031: hiddev0,hidraw5: USB HID v1.11 Device [Valve Software Wired Controller] on usb-0000:00:1a.2-2/input2
[ 2640.370906] usb 5-2: USB disconnect, device number 36

# ( ! ) The following is not an expected message:

[ 2640.716506] BUG: unable to handle kernel paging request at 00000028fecaee00
[ 2640.716572] IP: [<ffffffffc04786b3>] usbhid_raw_request+0x103/0x180 [usbhid]
[ 2640.716629] PGD 8000000086907067 
[ 2640.716653] PUD 0 

# ( ! ) The following is not an expected message:

[ 2640.716686] Oops: 0000 [#1] SMP
[ 2640.716709] Modules linked in: uinput fuse binfmt_misc intel_powerclamp coretemp kvm_intel kvm amdkfd radeon ttm drm_kms_helper drm snd_hda_codec_realtek joydev irqbypass snd_hda_codec_generic crct10dif_pclmul crc32_pclmul snd_hda_codec_hdmi i2c_algo_bit snd_hda_intel snd_hda_codec ghash_clmulni_intel snd_hda_core evdev iTCO_wdt intel_cstate iTCO_vendor_support snd_hwdep serio_raw pcspkr lpc_ich mei_me snd_pcm shpchp intel_uncore mfd_core sg snd_timer mei snd soundcore button acpi_cpufreq ip_tables x_tables autofs4 ext4 crc16 jbd2 crc32c_generic fscrypto ecb mbcache dm_mod sd_mod hid_generic usbhid hid crc32c_intel aesni_intel aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd ahci libahci libata scsi_mod i2c_i801 i2c_smbus uhci_hcd ehci_pci ehci_hcd r8169 mii usbcore usb_common
[ 2640.717404] CPU: 3 PID: 8459 Comm: Controller Work Not tainted 4.9.0-6-amd64 #1 Debian 4.9.88-1+deb9u1
[ 2640.717463] Hardware name: Gigabyte Technology Co., Ltd. H55M-S2H/H55M-S2H, BIOS F7 08/20/2010
[ 2640.717518] task: ffff8fad4cb662c0 task.stack: ffffb38040a58000
[ 2640.717557] RIP: 0010:[<ffffffffc04786b3>]  [<ffffffffc04786b3>] usbhid_raw_request+0x103/0x180 [usbhid]
[ 2640.717624] RSP: 0018:ffffb38040a5be88  EFLAGS: 00210206
[ 2640.717660] RAX: 45440065766f6ccd RBX: 0000000000000001 RCX: 0000000000000040
[ 2640.717707] RDX: ffff8fad4f9ad781 RSI: 0000000000000000 RDI: 00000028fecaedfe
[ 2640.717753] RBP: ffff8fad4f9ad780 R08: 0000000000000003 R09: 0000000000000001
[ 2640.717799] R10: 45440065766f6d65 R11: ffff8fad09c4c638 R12: 00000000ea4c1960
[ 2640.717845] R13: 0000000000000041 R14: ffff8fad4da28000 R15: 00000000ea4c1960
[ 2640.717892] FS:  0000000000000000(0000) GS:ffff8fad57cc0000(0063) knlGS:00000000e9650b40
[ 2640.717945] CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
[ 2640.717982] CR2: 00000028fecaee00 CR3: 00000000b7a08000 CR4: 0000000000000670
[ 2640.718028] Stack:
[ 2640.718043]  00000000ea4c1960 0000000000000041 ffff8fad4da28000 fffffffffffffff4
[ 2640.718103]  ffffffffc045be1b b3cd1673ef10c900 b3cd1673ef10c9f3 0000000000000055
[ 2640.718162]  00000000c0414807 ffff8fad09c4c601 00000000ea4c1960 ffff8fad09c4c600

# ( ! ) This messages identifies Valve's Steam Controller as a source os the issue: 'hidraw'

[ 2640.718221] Call Trace:
[ 2640.718247]  [<ffffffffc045be1b>] ? hidraw_ioctl+0x2bb/0x370 [hid]
[ 2640.718292]  [<ffffffff87061eff>] ? compat_SyS_ioctl+0xbf/0x1150
[ 2640.718335]  [<ffffffff86e03d4b>] ? do_fast_syscall_32+0xab/0x180
[ 2640.718385]  [<ffffffff87413d7b>] ? entry_SYSENTER_compat+0x8b/0x9d
[ 2640.718430] Code: 8b 10 48 8b 7f 08 49 8d 82 68 ff ff ff 48 8b 7f 08 40 88 32 75 0d 48 83 c2 01 48 83 e9 01 bb 01 00 00 00 41 83 c0 01 40 0f b6 f6 <44> 0f b6 4f 02 41 c1 e0 08 0f b7 c9 48 89 c7 41 09 f0 41 8b b2 
[ 2640.718817] RIP  [<ffffffffc04786b3>] usbhid_raw_request+0x103/0x180 [usbhid]
[ 2640.718875]  RSP <ffffb38040a5be88>
[ 2640.718902] CR2: 00000028fecaee00
[ 2640.736527] ---[ end trace 014a6eb8f05c3afe ]---

# ( ! ) Disconnecting Steam Controller not even detected, reconnecting it back to USB bus generates these messages, but controller is no longer functions:

[ 2640.770842] usb 5-2: new full-speed USB device number 37 using uhci_hcd
[ 2640.942500] usb 5-2: New USB device found, idVendor=28de, idProduct=1102
[ 2640.942507] usb 5-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2640.942512] usb 5-2: Product: Wired Controller
[ 2640.942517] usb 5-2: Manufacturer: Valve Software
[ 2640.950961] input: Valve Software Wired Controller as /devices/pci0000:00/0000:00:1a.2/usb5/5-2/5-2:1.0/0003:28DE:1102.0032/input/input49

The only available solution to get controller to work again required OS reboot. 
Logging out and back in to the users OS account dose not restore Steam Controller Functionality.

Please confirm if you can reproduce the issue on your side.
Please let me know if there is a some type of a solution you can propose. 
This controller was purchased specifically to see if playing video games using a Steam Software on GNU/Linux platform is more viable vs playing games using MS Xbox / Sony PS gaming platforms.

Your HW of your Steam Controller has an awesome built quality, however, software for GNU/Linux OS - Debian Stretch so far shows to be .... unstable. 

I really wish to be choosing Steam Software as a gaming platform vs MS/Sony. 
If there is any more technical details you might need to diagnose this issue, I will gladly assist you and provide all necessary data you might need. 

(!) It appears there is no way to file a separate bug report using https://help.steampowered.com
Please let me know what is the approved procedure to file another bug report. 

Issue: 
Unable to pair Steam Controller via Bluetooth wireless link. 

Same controller.
Same Host with the Same OS and environment. 

Using guide published @ https://support.steampowered.com/kb_article.php?ref=7728-QESJ-4420
... was not able to pair Steam Controller to the Host Computer via Bluetooth. 

Steam Controller is not detected and therefore not 'seen' by the host computer and the Steam Software running on the host computer.

#### Steps for reproducing this issue:

1.  Start the Steam Client
2.  Connect the Steam Controller via USB
3.  Confirm the Steam Controller functions as expected
4. While keeping Steam Controller connected via USB, quit the steam client (not just close the steam client window, actually quit the Steam Client
5. Using the Steam Controller, move mouse around the desktop, using left touchpad pn the controller
6. Using the Steam Controller, move a thumb on the right touchpad in a circular motion. 
7. Take a not how sound feedback is now different from the sound feedback audible while Steam Client was running. 
8. In about ~5 to ~10 seconds, you would experience the behavior described above. 

Please note ( ! ) Under certain conditions, such as USB keyboard + USB mouse connected to the same group of the USB ports (back I/O panel of the motherboard), once Steam Controller Stops responding, it also causes the keyboard and the mouse to lock up. 

Connecting steam controller to a different groups of ports, allows to continue to operate the Keyboard and mouse, but all the other symptoms and errors from Kernel messages persist.  

This behavior was replicated on an entirely different physical hardware (Mainboard/CPU/...etc.) with exact same results :\

Please let me know what other info you might need or how else can i assist to effectively resolve this issue.

Thank you.

**Comment by user111222333** [comment]
Hello Steam Dev team, is there any update on this ticket?

**Comment by kisak-valve** [comment]
Hello @user111222333, are you still experiencing this issue on an up to date system? In particular, are newer kernels equally affected?

**Comment by kisak-valve** [comment]
Closing pending feedback.
