### ISSUE TITLE
[Dota2] Unable to connect to dota2 games with the latest steam beta.

### ISSUE THREAD

**Issue by DarkDefender** [ValveSoftware/steam-for-linux#5545]
#### Your system information

* Steam client version (build number or date): Jun 27 2018 at 22:28:25 
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

It seems like the latest steam beta (as of today) has messed up somthing with dota2. I am unable to connect to games or watch game now. The client tries to connect, waits for a while and then thows an "Unable to download Network Configuration from CDN" error.

If I downgrade the steam client to the non steam beta, this now works without problems. I also played some Dota2 games on the 27th of june (CEST) with the older steam beta without any problems. So this must be a recent change that messed this up for me.

#### Steps for reproducing this issue:

1. Use the latest Steam beta
2. Launch dota2
3. Try to watch or join a game
4. The dota2 client is unable to connect and throws "Unable to download Network Configuration from CDN"

**Comment by kisak-valve** [comment]
Hello @DarkDefender, what download region are you using in Steam's settings? If you change to a different download region, does that make a difference?

**Comment by DarkDefender** [comment]
@kisak-valve My main one is Sweden.
I've tried switching to: Denmark, Island, US - New York.

None of the switches helped sadly.

**Comment by LiamDawe** [comment]
Just tested Dota 2 and I'm on the Beta client, ranked matchmaking found a match fine after around 2 minutes 30 secs of searching.

Ubuntu 18.04 - UK region.

**Comment by astroty** [comment]
Steam client version (build number or date): Jun 29 2018, at 19:05:50
    Distribution (e.g. Ubuntu): Manjaro Linux
    Steam Runtime Version:  <Runtime disabled>
    Opted into Steam client beta?: [Yes/No] Yes
    Have you checked for system updates?: [Yes/No] Yes

Can confirm error "Unable to download Network Configuration from CDN"
Reverting to stable fixes the issue. Changing download region does not.

**Comment by kaiserprogrammer** [comment]
@fletcherdvalve 
Switching OS from Ubuntu 18.04 to Clear Linux, while maintaining the same Steam setup in the home folder, also resolved this issue.

**Comment by chaosk** [comment]
Referencing https://github.com/ValveSoftware/csgo-osx-linux/issues/1678#issuecomment-402334472

@fletcherdvalve We've been discussing the issue over Reddit messages/emails; issue still persists

**Comment by chaosk** [comment]
Interestingly, it _does_ seem like a problem with locale.

My locale:
```
~ locale
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

With that configuration, game won't connect to game servers. _However_, running Steam with `LC_ALL=pl_PL.UTF-8 steam` fixes the problem. I shouldn't be forced to set `LC_ALL`, though...

**Comment by fletcherdvalve** [comment]
Yeah we are parsing and printing some floating point numbers using the C runtime.  Which is just fundamentally broken for anything where two computers want to talk to each other using a standard format, unless you disable all the locale stuff.  Which is what we are going to do in an incoming beta.

**Comment by DarkDefender** [comment]
I'll just confirm that changing the locale to `en_US.UTF-8` does indeed solve the problem for me also.

**Comment by endersonmenezes** [comment]
Same for me. Opting out of beta fixed the problem.

**Comment by xxxAGSNxxx** [comment]
Thanks for the tip, made the withdrawal of Steam Beta my Dota 2 returned to look for matches normally, this one with the same problem in the search of matches.

Detail in the choice of region could not see the ping of any available region.

**Comment by kisak-valve** [comment]
Hello, per "Fixed an issue where CS:GO and Dota 2 matchmaking would not function properly." in the [2018-07-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) Steam client beta update, please update your steam client and retest this issue.

**Comment by DarkDefender** [comment]
This works for me now! I no one else in here still has problems, I'll go ahead and close this. Thanks!

**Comment by nanonyme** [comment]
@fletcherdvalve Hi, do you have any suggestions on validating whether that recently linked Flatpak issue is actually this same or just something that looks similar? Also, would be possible the describe the solution done a bit more (on conceptual level) without violating NDA to help with debugging.

**Comment by fletcherdvalve** [comment]
The fix was for the steam client to ignore the localization environment variables so that functions like sscanf, etc could be used to parse text files with floating point numbers in them.

I don't know the flatpak issue you are referring to

**Comment by nanonyme** [comment]
There's a link above my comment to a case from flathub-distributed Flatpak build of Steam (just a container using normal Steam  + Steam runtime with host OS replaced with portable abstraction) where there was a claim the CS:GO issue persisted and LC_ALL=C workaround remained working. I'd like to find out if the root cause was isolated to the user's machine or should be something for us to be worried about. Based on your description sounds like the workaround should no longer have any impact with up to date Steam

**Comment by AETolouee** [comment]
I have the exact same issue. but unlike anyone else, workarounds doesn't work on me.
I tried LC_ALL=en_US.UTF-8 and LC_ALL=C. And I'm not participating any steam beta programs.
Though I was able to play dota afew days earlier. until '.steam' folder got removed and I downloaded it againt.

**Comment by babelshift** [comment]
I don't think this issue is fixed. I am experiencing this under the following setup:

```
Steam client version (build number or date): Aug 23 2018, at 19:47:27
Distribution (e.g. Ubuntu): Ubuntu 18.04.1
Opted into Steam client beta?: [Yes/No] Yes
Have you checked for system updates?: [Yes/No] Yes
```
The issue remains on the latest Steam Client Beta build. I was only able to solve this by setting `LC_ALL` to `en_US.UTF-8`, which I feel is something I shouldn't have to do.

**Comment by gambitflush** [comment]
i need help
i have reinstalled dota 2 as it got crashed and i cannot find games of watch matches , it says " check your internet connection,unable to download network configuration from CDN" while my net works absolutely fine . i have no clue what to do please kindly help me out 
![screen shot 2018-10-02 at 3 16 37 am](https://user-images.githubusercontent.com/43794895/46373331-5efac480-c6ab-11e8-9348-42f6357cf662.png)

**Comment by Waviee** [comment]
Hey, I'd like to inquire about how I could open the locale file and set the LC_ALL to en_US.UTF-8 ?

**Comment by UltraGreed** [comment]
```
Steam client version (build number or date): Dec 11 2020, at 00:39:58
Distribution (e.g. Ubuntu): eselect-5.4.80-gentoo-r1
Opted into Steam client beta?: [Yes/No] No
Have you checked for system updates?: [Yes/No] Yes
```

Still have the problem. Had the same problem on Ubuntu|Fedora (can't remember). Also tried using Beta client, issue remains. Don't sure how to change LC_ALL, but running app with `LC_ALL=en_US.UTF-8 steam` doesn't work for me. 
App was installed with Portage.
