### ISSUE TITLE
Recent Steam Beta change broke escaping apostrophe in game path and thus launching

### ISSUE THREAD

**Issue by boombatower** [ValveSoftware/steam-for-linux#5546]
#### Your system information

* Steam client version (build number or date): Jun 27 2018 at 22:28:25 (1530140322)
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes (pending, but not relevant)

#### Please describe your issue in as much detail as possible:

Sometime in the last several weeks launching Civilization games stopped working.

#### Steps for reproducing this issue:

1. Attempt to launch `Sid Meier's Civilization V`
2. Watch preparing to launch box come and go
3. Sadly view a screen without the game running

#### Workarounds

Launching the game directly via the executable works. Also entering `./Civ5XP "%command%"` in set launch options works as well. The core problem appears to be the escaping done to the apostrophe in the game name.

If I change the launch options to `echo "%command%"` the following is printed.

```
'/vol/ssd/0_256G/steamlib/steamapps/common/Sid Meier'''s Civilization V/./Civ5XP'
```

And when run from terminal the following is included in output:

```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

The triple single quote does not work the way it is desired.

Also changing to the following works further confirming escaping.

```
cd /vol/ssd/0_256G/steamlib/steamapps/common/Sid\ Meier\'s\ Civilization\ V/; ./Civ5XP
```

**Comment by moozaad** [comment]
Confirming this is an issue with Civ 5 and 6. Respective workarounds are setting launch options to:

./Civ5XP "%command%"

./Civ6 "%command%"

Looks like bad escaping on the aposthrope in "Meier's"?

**Comment by conrev** [comment]
I can also confirm this on other games, Klei Entertainment's Dont Starve Together also fails to launch with the following error
``/bin/sh: -c: line 0: unexpected EOF while looking for matching " ``
``/bin/sh: -c: line 1: syntax error: unexpected end of file``

**Comment by conrev** [comment]
@Plagman is there any more logs/data that you need to help solve this issue? This breaks too many games in my libraries and it's a bit annoying to deal with.

**Comment by jurgel** [comment]
Happened to me too, game's name is "The Lion's Song"
Works well from terminal.

**System Information:**
- Steam client version (build number or date): Jun 29 2018 at 19:05:50 (1530312634)
- Distribution (e.g. Ubuntu): Ubuntu 18.04
- Opted into Steam client beta?: Yes

**Comment by Plagman** [comment]
This should be fixed in the next Beta, apologies for the inconvenience.

**Comment by kisak-valve** [comment]
Closing as fixed in the 2018-07-09 Steam Client Beta.

**Comment by boombatower** [comment]
Confirmed, thank you.
