### ISSUE TITLE
stuck on login screen on steam machine

### ISSUE THREAD

**Issue by kinglinc** [ValveSoftware/steam-for-linux#5547]
#### Your system information

* Steam client version (build number or date): **june 27 2018, at 22:28:22**
* Distribution (e.g. Ubuntu): **?**
* Opted into Steam client beta?: **[No]**
* Have you checked for system updates?: **[Yes]**

#### Please describe your issue in as much detail as possible:

 **my steam box no longer allows me to log in. I come to the first login screen on startup where I see my username and picture on the left, "login" in the middle, and beside that to the right is "join". 
Clicking my username causes a noise to play -sounds like an error sound- and login is the same.
The only button that does anything is "join" and all it does is show a pop-up that says: "Create Account. Please open a web browser and navigate to store.steampowered.com/join to create your steam account. Then use your new credentials to log in here. "**

**I can go into settings, but nothing there helps. This happened after the last update, "SteamOS 2.0 update 1:2.148"**

**I have restored to factory settings, to no avail. I believe it has something to do with the last update, as thats when it stopped letting me login.**

**attached is a picture of the screen i am stuck on**

![20180628_143524_5](https://user-images.githubusercontent.com/40704913/42117705-38f2e35a-7bcc-11e8-969f-760556d12796.jpg)

**Comment by kisak-valve** [comment]
Hello @kinglinc, are you still experiencing this issue on an up to date system?

**Comment by kinglinc** [comment]
I am no longer experiencing this issue. Thanks.
