### ISSUE TITLE
new chat ignore "-silent" launch option

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#5552]
#### Your system information

* Steam client version (build number or date): all latest beta
* Distribution (e.g. Ubuntu): debian sid 64bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. add "-silent" launch option to steam
2. run steam
3. open friends list
4. open chat with someone
5. send message
6. close chat dialog
7. close friends list
6. quit from steam
7. launch steam again (with silent option)

window "connect to account" not show, it's normal
library not show, normal too
but latest chat dialog and friends list opened

**Comment by Myrddin-Wyllt** [comment]
I've just tested this parameter; everything functions as expected now. 

Starting with the `-silent` parameter however still does have one issue with remembering open chats:
![image](https://user-images.githubusercontent.com/42914865/72380937-16b6b880-36dc-11ea-9f71-28acd44ae1e6.png)

This chat setting is currently not respected with the -silent parameter. If that would be fixed, I'd mark this as solved.

**Comment by kisak-valve** [comment]
Per the last comment, closing as fixed some time ago.

@Myrddin-Wyllt, always starting Steam with no UI visible sounds like it will cause more trouble than the value it would add to the Steam client. If you want to do this, manually create a desktop shortcut that calls `steam -silent`.
