### ISSUE TITLE
crash  at startup

### ISSUE THREAD

**Issue by Cyxapic** [ValveSoftware/steam-for-linux#5553]
#### Your system information

* Steam client version (build number or date):  1.0.0.54
* Distribution (e.g. Ubuntu):  mint 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Steps for reproducing this issue:

1. On run steam:
```
Running Steam on linuxmint 18.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1528497815)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1528497815)
Installing breakpad exception handler for appid(steam)/version(1528497815)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
assert_20180701205133_1.dmp[12473]: Uploading dump (out-of-process)
/tmp/dumps/assert_20180701205133_1.dmp
/home/san/.local/share/Steam/steam.sh: строка 876: 12458 Ошибка сегментирования (подготовлен дамп ядра) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20180701205133_1.dmp[12473]: Finished uploading minidump (out-of-process): success = yes
assert_20180701205133_1.dmp[12473]: response: CrashID=bp-c7711db6-6607-44f6-97b7-d94582180701
assert_20180701205133_1.dmp[12473]: file ''/tmp/dumps/assert_20180701205133_1.dmp'', upload yes: ''CrashID=bp-c7711db6-6607-44f6-97b7-d94582180701''
```
2. Try to reinstall? don't help it.
3. Try update nvidia - no results.

**Comment by kisak-valve** [comment]
Hello @Cyxapic, does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

**Comment by Juseus** [comment]
I've been fighting with the same problem for a long time. Exactly the same kind of "failed" and "error" messages when trying to start Steam. I'm running Linux Mint 19 and I've not opted in to Steam beta.

Today I found a solution that finally worked for me...

1. Installed graphics-drivers PPA
2. Purged all old nvidia packages (apt purge .*nvidia.*)
3. Installed latest nvidia-driver-396 package. Here is the important part: I also installed all suggested packages, some of those solved the actual problem. I tried and installing just the driver and packages that come as a dependency was not enough.
4. Started Steam and now it works as it should

**Comment by Cyxapic** [comment]
@kisak-valve hello! Try to install mesa-utils:i386 - the same problem. (((

**Comment by kisak-valve** [comment]
Can you put the output of `glxinfo` into a [gist](https://gist.github.com/)?

**Comment by Cyxapic** [comment]
full?

**Comment by kisak-valve** [comment]
We're mostly interested in if it gets to real hardware `glxinfo | grep OpenGL` is just as good.

**Comment by Cyxapic** [comment]
https://gist.github.com/Cyxapic/c403d78a28c3a8aad0cb779a1cabaa07

**Comment by Cyxapic** [comment]
It's a miracle - i'll delete all NVIDIA driver, update system and steam started :dancing_men: 
Dont know why :D

**Comment by kisak-valve** [comment]
Glad to hear you got it working. This reads as if your nvidia opengl driver install was incomplete and missing 32 bit support.

Closing as a general system issue and not steam.

**Comment by nnseva** [comment]
The same happens on Ubuntu 19.04 x86-64. Installing the following nvidia libraries for i386 helped me, I hope it also helps others:

libnvidia-compute-XXX:i386 libnvidia-decode-XXX:i386 libnvidia-encode-XXX:i386 libnvidia-ifr1-XXX:i386 libnvidia-fbc1-XXX:i386 libnvidia-gl-XXX:i386

Replace XXX by your current nvidia driver (you can find it searching f.e. installed libnvidia-common driver for x86-64 architecture).

**Comment by nnseva** [comment]
@kisak-valve it looks improperly still to use i386 architecture only, it is actually deprecated and not enough for the most modern games at the moment.
