### ISSUE TITLE
Steam causes system freeze on quit. 

### ISSUE THREAD

**Issue by markovsi** [ValveSoftware/steam-for-linux#5555]
#### Your system information

* Steam client version (build number or date): 1528497815
* Distribution (e.g. Ubuntu): Ubuntu 18.04, Debian 9
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I'm not sure why I can't find this issue here, it's very old issue that exists for a year or longer. When I'm trying to log out from system or when I just quit steam it causes ~4 minutes lag. The system becomes fully freezed because of 100% CPU usage on every core caused by steam and xorg.  
It also can be related to xorg memory leakage  when steam is active during several days. When I quit steam it looks like xorg releases ~1Gb of ram and backs to normal memory usage.

Thank you.

Steps for reproducing this issue:

1. Start steam
2. Wait for 5-days of uptime
3. Close steam

System: 
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:          Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Desktop x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.0.0-rc5
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x162
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20,75" x 11,65" (23,78" diag)
                                            52,7cm x 29,6cm (60,4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: AV200

Memory:
    RAM:  23039 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Total Hard Disk Space Available:  469325 Mb
    Largest Free Hard Disk Block:  5630 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Hello @markovsi, this issue was tracked at #5279 and should be fixed in Steam's beta client. Closing as a duplicate.
