### ISSUE TITLE
Steam client prevent monitor go to power saving mode even if no launched games.

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#5556]
#### Your system information

* Steam client version (build number or date): 1530312634
* Distribution (e.g. Ubuntu): Fedora 29
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

When steam client is runned monitor never has sleep.
But if I close steam client power saving timeout begins works.

**Comment by kisak-valve** [comment]
Hello @NTMan, this issue is already being tracked at #5532. Closing as a duplicate.
