### ISSUE TITLE
Steam Hardware Survey does not occur on Linux client

### ISSUE THREAD

**Issue by samrocketman** [ValveSoftware/steam-for-linux#5559]
#### Your system information

* Steam client version (build number or date): 

  <details><summary>Click to expand screenshot</summary>

  ![screenshot from 2018-07-07 20-05-49](https://user-images.githubusercontent.com/875669/42416365-2fa2d336-8221-11e8-8197-0b94d19658fb.png)

  </details>

  ```
  $ dpkg -l | grep steam
  ii  steam-launcher                             1.0.0.54                                     all          Launcher for the Steam software distribution service
  ```

* Distribution (e.g. Ubuntu):
  ```
  $ head -n1 /etc/issue
  Ubuntu 16.04.4 LTS

  $ uname -rms
  Linux 4.4.0-130-generic x86_64
  ```
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, all system packages are up to date via `apt-get`.

#### Please describe your issue in as much detail as possible:

I have been gaming on Linux for a couple years now with Steam. Unfortunately, I've *not ever* been able to submit a hardware survey. I have a client on my Mac that I open maybe once a year, however, nearly every time I open the Mac client I get prompted for a steam hardware survey.

Why doesn't Steam ever ask me for a hardware survey on Linux? I want to set Linux as the only platform in which I get the hardware survey. We should be able to submit a "primary client" setting in which the survey only appears.

Linux estimates could be misrepresented if this is a prevalent problem with other Linux users.

# Feature request

It would be great if Steam offered an option to choose a primary platform in which to submit hardware surveys.

**Comment by kisak-valve** [comment]
Hello @samrocketman, there's currently no reason to suspect that the sampling method used for the survey has changed since the discussion on #2286.

Closing per https://github.com/ValveSoftware/steam-for-linux/issues/2286#issuecomment-307538674.

**Comment by samrocketman** [comment]
@kisak-valve please re-open this issue.  This issue was intended as a feature request and you closed it addressing the additional information only.
