### ISSUE TITLE
PC doesn't sleep with runned steam

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#5561]
#### Your system information

* Steam client version (build number or date): last beta
* Distribution (e.g. Ubuntu): debian sid 64 bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

DE gnome 3.28. my PC go to sleep after 5 minutes afk. after updates with new chat PC don't go to sleep.

#### Steps for reproducing this issue:

1. set sleep after 5 minutes in settings
2. run steam
3. wait >5 minutes

if I open some steam window or close all, no difference. need only runned steam

**Comment by kisak-valve** [comment]
Hello @steamlinux, this issue is already being tracked at #5532. Closing as a duplicate.
