### ISSUE TITLE
Steam not Launching on Debian Buster

### ISSUE THREAD

**Issue by pazg1234** [ValveSoftware/steam-for-linux#5562]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-5
* Distribution (e.g. Ubuntu): Debian Buster 
* Opted into Steam client beta?: [Yes/**No**]
* Have you checked for system updates?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
I installed Steam from the official non-free repositories along with the proprietary Nvidia driver, also from the repos, I use a GTX 760 and a Intel core i5-3470 CPU, the system works well.
once I run steam from the terminal it gives the following error: [Steam before mkdir](https://gist.github.com/pazg1234/2424a16484a2411b3b4b6754e0b1cd04)
People from around the block suggested I create `/home/usr/.steam/ubuntu12_32/steam-runtime` with mkdir, and thus I did: [Steam after mkdir](https://gist.github.com/pazg1234/322d4ad94a7d50707e81f7040dee2099)
Still, segfault.
`libgl1-nvidia-glx:i386` is installed and so is `libgl1-mesa-glx:i386`
I'm a member of both the Audio and Video groups: 
`usr@usr:~$ groups`
`usr cdrom floppy sudo audio dip video plugdev netdev`
an important clue perhaps is dmseg that says:  `steam[4775]: segfault at fffffffd ip 00000000f7a0a7dc sp 00000000ff800120 error 4 in libc-2.27.so[f7990000+1d2000]
`
Installing nouveau instead of the proprietary driver gives: [Nouveau err](https://gist.github.com/pazg1234/eda084afc7fe1c0bbdc884346d76c149)
Steam is installed on my SSD at /, my /home folder is on my HDD.
#### Steps for reproducing this issue:
1. Use this hardware configuration
2. Install Debian Buster and enable i368 and non-free repository
3. Use any Nvidia driver
4. Run Steam from command line/ et al.
I really need your help, I'm utterly stumped, any logs I need to provide - do tell.

**Comment by kisak-valve** [comment]
Hello @pazg1234, does any 32 bit opengl application work like `glxinfo` from `mesa-utils:i386`?

**Comment by pazg1234** [comment]
> does any 32 bit opengl application work like glxinfo from mesa-utils:i386? 


Firstly thanks, @kisak-valve for the quick answer.
yes indeed glxinfo and glxgears do work.
here's my [glxinfo](https://gist.github.com/pazg1234/3c0cd4d470184dbf7f496af6cf8437fd) (in gist)
and I can confirm glxgears works I'll send a screencapture / -info, if need be.

**Comment by kisak-valve** [comment]
Taking a blind guess here, can you give `LD_PRELOAD='/usr/lib/i386-linux-gnu/libstdc++.so.6' steam` a try?

I read this like Steam needs to successfully run once on the bootstrapper runtime so that it can setup the normal steam runtime. If that helps then the workaround should only be needed once.

**Comment by pazg1234** [comment]
Alright, so firstly I briefly changed to Debian Stable because someone told me to, even though I knew it doesn't work there too, the error message is different there, seems more verbose, [right here](https://gist.github.com/pazg1234/884bc30b8c112d73eeb97013433240c0) 
Now as to what you asked me, I went back to testing but no luck unfortunately, a different error occurs, here [before mkdir](https://gist.github.com/pazg1234/528258c3a911f8e7d74bc823814ab564) and [here after](https://gist.github.com/pazg1234/ff91ccc4397e64d70c7a0fd36f301d7e)
glxgears still works.
I thought perhaps steam doesn't do well with two file systems? my SSD (/) is EXT4 for Civilization and the HDD (/home) is XFS, perhaps worth a re-installation to match both as XFS?

**Comment by kisak-valve** [comment]
Steam is known to have trouble with game update and large XFS partitions, but that does not match your logs. `SteamUpdateUI: An X Error occurred` is strongly hinting this issue is video driver related. Can you double check that you tried the 32 bit variant of glxinfo (and not the 64 bit variant)?

There's various other [open issue reports](https://github.com/ValveSoftware/steam-for-linux/search?q=SteamUpdateUI&type=Issues) related to this symptom.

**Comment by pazg1234** [comment]
@kisak-valve  I believe so.
```
"sudo apt remove mesa-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'mesa-utils' is not installed, so not removed. Did you mean 'mesa-utils:i386'?
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."
```
doesn't that confirm I'm using the correct version?
My XFS partition is not that large, <1TB. 
It's getting stranger by the minute, since yesterday I can also confirm it does work with Arch Linux, mayhap a packaging error?

**Comment by kisak-valve** [comment]
Looking at some of Debian Buster's packages, maybe steam is picking up mesa's [/usr/lib/i386-linux-gnu/libGL.so.1](https://packages.debian.org/buster/i386/libgl1-mesa-glx/filelist) before nvidia's [/usr/lib/i386-linux-gnu/nvidia/current/libGL.so.1](https://packages.debian.org/buster/i386/libgl1-nvidia-glx/filelist)? Can you temporarily move `/usr/lib/i386-linux-gnu/libGL.so.1` somewhere out of the way and see if it makes a difference? If that doesn't make a difference, try `LD_LIBRARY_PATH='/usr/lib/i386-linux-gnu/nvidia/current/' steam`.

It may also be worth trying the GLVND-enabled variant of the nvidia driver (https://packages.debian.org/buster/libgl1-nvidia-glvnd-glx), but be careful and don't let apt remove your entire desktop environment.

**Comment by pazg1234** [comment]
So, both of the first things did not work, I did a `sudo mv /usr/lib/i386-linux-gnu/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so.1.bkp`
and it replied: `ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2018-07-11 17:17:16] Startup - updater built Nov 23 2016 01:05:42
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  18 (X_ChangeProperty)
Value in failed request:  0x0
Serial number of failed request:  11
xerror_handler: X failed, continuing
Segmentation fault`
Nothing.
Afterwards I did the LD_LIBRARY_PATH:
```
LD_LIBRARY_PATH='/usr/lib/i386-linux-gnu/nvidia/current/' steam
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2018-07-11 17:17:52] Startup - updater built Nov 23 2016 01:05:42
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  18 (X_ChangeProperty)
Value in failed request:  0x0
Serial number of failed request:  11
xerror_handler: X failed, continuing
Segmentation fault
```
Nothing still.
libgl1-nvidia-glvnd-glx is already installed on my system, I think it comes with nvidia-driver by default.
I don't know what's the difference or what GLVND means but libgl1-nvidia-glx **is not installed** by default (non GLVND version) shall I install it? think it will make a difference?

**Comment by kisak-valve** [comment]
In your opening post you indicated `libgl1-nvidia-glx:i386 is installed and so is libgl1-mesa-glx:i386` and I don't know if a half-glvnd setup causes trouble. At this point I'm out of ideas to suggest. Hopefully a debian user who's seen this issue shares some insight.

**Comment by pazg1234** [comment]
@kisak-valve true, but I also said 

>  so firstly I briefly changed to Debian Stable with an older driver because someone told me to

This is my second Debian testing install, it's clean and without anything outside of the default nvidia-driver package. 
I also checked 
```
usr@usr:~$ sudo update-glx --config glx
There are 3 choices for the alternative glx (providing /usr/lib/glx).

  Selection    Path                       Priority   Status

* 0            /usr/lib/nvidia             100       auto mode
```
Seems like the Nvidia GLX is default.

**Comment by doraskayo** [comment]
@kisak-valve, @pazg1234: I've experienced the same issue since the new chat update:
```
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  18 (X_ChangeProperty)
Value in failed request:  0x0
Serial number of failed request:  104
xerror_handler: X failed, continuing
assert_20180727170423_1.dmp[201]: Uploading dump (out-of-process)
```
Running Steam like this fixes the issue for me:
```
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
```
However, some games are now missing their sound (for example, Shadowrun: Hong Kong - Extended Edition), so it's not really a solution.

**Comment by doraskayo** [comment]
@pazg1234, your pasted log doesn't show the output of the attempt to use `LANG=en_US.UTF-8` as mentioned in the edit of my previous comment. Can you try again and upload the output?

**Comment by teadur** [comment]
installing nvidia-driver-libs-i386 fixed the issue for me on debian buster

**Comment by pazg1234** [comment]
> @pazg1234, your pasted log doesn't show the output of the attempt to use `LANG=en_US.UTF-8` as mentioned in the edit of my previous comment. Can you try again and upload the output?

> installing `nvidia-driver-libs-i386` allows me to launch steam (1.0.0.59-4) on Debian Buster.

Thank you all for commenting on this thread, I've since switched my computer to an AMD base through and through, thus all my problems are solved, still use Debian, Sid nowadays, hopefully some other soul who experiences this problem shall see this thread.

**Comment by sobotka** [comment]
Quick update for those poor folks trying to get Steam up.

Make sure you have the i386 architecture added via the `dpkg` line. Depending on your video card, `find` the `libgl.so` file that is related to the i386 install. For example, NVidia might have something like `/usr/lib/i386-linux-gnu/mesa/` as a path.

In `/etc/ld.so.conf.d/` create `steam.conf` and add:
```
/usr/lib32
/usr/lib/mesa-diverted/i386-linux-gnu/
```

Run `steam`
