### ISSUE TITLE
without dbus daemons the client segfaults

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5563]
I don't use dbus, I removed it, but then the steam client is segfaulting.

**Comment by sylware** [comment]
tested with the latest beta steam client update, still segfaulting without dbus

**Comment by sylware** [comment]
Did check the latest beta client with some "dbus assertion fix".
I did disable dbus, tried to run the client, still segfaulting :(

**Comment by sylware** [comment]
latest beta, the client is able to start without a session dbus, but it still segfault without a system dbus.

**Comment by nbmlx** [comment]
any news on this? will Steam work without dbus someday?

**Comment by sylware** [comment]
the steam-runtime libdbus is missing a symbol to run google libcef and does not run, it does not crash anymore though. I moved this to another issue then.
