### ISSUE TITLE
Trying to start csgo crashes game and steam in newest beta

### ISSUE THREAD

**Issue by martinfischer** [ValveSoftware/steam-for-linux#5564]
#### Your system information

* Steam client version (build number or date): Built: Jul 11 2018
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Since the beta before this one I had to start steam with `LC_ALL=C steam` from the terminal to get csgo to connect to official servers, but now with the newest beta the game won't start and steam crashes. 

Console log:

```
crash_20180711070649_1.dmp[15657]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180711070649_1.dmp
/home/martin/.local/share/Steam/steam.sh: line 876: 15477 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
/home/martin/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 5: 15485 Segmentation fault      ./steamwebhelper "$@"
crash_20180711070649_1.dmp[15657]: Finished uploading minidump (out-of-process): success = yes
crash_20180711070649_1.dmp[15657]: response: CrashID=bp-828f40f5-bddf-426f-ab91-b0ac42180710
crash_20180711070649_1.dmp[15657]: file ''/tmp/dumps/crash_20180711070649_1.dmp'', upload yes: ''CrashID=bp-828f40f5-bddf-426f-ab91-b0ac42180710''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:766
```

#### Steps for reproducing this issue:

1. Start steam from terminal with `LC_ALL=C steam`
2. Start csgo by hitting Play
3. Crash

**Comment by efe-aydin** [comment]
I can also confirm that this also happens on Ubuntu. I just reinstalled Steam for that because I thought that it was a problem with my computer :(

**Comment by kisak-valve** [comment]
Looks like steam's beta client also crashes out from under Dota 2 as well.

**Comment by Disk1of5** [comment]
Also impacted
steam.sh: line 876: 11919 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by boustrophedon** [comment]
@Plagman I have crash dumps available in [csgo-osx-linux/1689](https://github.com/ValveSoftware/csgo-osx-linux/issues/1689) if that would help.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where Steam could crash when running Steamworks-enabled games, or where Steamworks functionality wouldn't work properly in the game." in the [2018-07-11](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2642934601290756923) Steam client beta update.
