### ISSUE TITLE
I can not input Korean characters through fcitx on steam.

### ISSUE THREAD

**Issue by hellojo011** [ValveSoftware/steam-for-linux#5570]
#### Your system information

* Steam client version (build number or date): Jun 8 2018, 22:22:39 / 1528497815
* Distribution (e.g. Ubuntu): Kubuntu 18.04 Bionic LTS 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I can not use fcitx with steam client. The message "No input window" is displayed in fcitx. but I can input Korean characters in "Starbound" game.

please i need help.

#### Steps for reproducing this issue:

1. I just installed steam for linux.
2. 
3. 

![20180715105358_1](https://user-images.githubusercontent.com/15025232/42729760-c42919d2-881d-11e8-99d0-0d310b40b302.jpg)

![screenshot_20180715_105730](https://user-images.githubusercontent.com/15025232/42729766-ebff30b8-881d-11e8-8070-481fd80f4953.png)

**Comment by kisak-valve** [comment]
Hello @hellojo011, a feature request for fcitx support is already being tracked at #3255. Closing as a duplicate.
