### ISSUE TITLE
"Oxygen Not Included" completely locks desktop at random

### ISSUE THREAD

**Issue by matthew-cline** [ValveSoftware/steam-for-linux#5573]
#### Your system information

* Steam client version: 1528497815, built Jun 8 2018 at 22:22:39
* Distribution: Fedora 28
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since upgrading to the `expressive_upgrade_testing` beta of *Oxygen Not Included*, the game will randomly and very infrequently cause the desktop to **completely** lock up.  Pressing caps lock or num lock does not toggle the lights on the keyboard, and the usual key combination to switch to a virtual terminal does nothing.  Additional, the game's background sound "skips", repeating the same second over and over.

Gists:
* [Steam's report on system information](https://gist.github.com/matthew-cline/172cce65cb4d92e3447f1c9485bebf95)
* [Output of dmidecode](https://gist.github.com/matthew-cline/514bbf8a2158cce620a116d168e16c9a)
* [Output of glxinfo](https://gist.github.com/matthew-cline/f2999abdd72f35eaa59aac4bd0a7f41f)

**Comment by kisak-valve** [comment]
Hello @matthew-cline, no OpenGL application should be capable of locking up the system. This issue should be brought to the attention of the game devs and your video driver vendor.

It may also be worthwhile to see if the kernel is still alive and see if you can SSH into the system and check `dmesg`.

**Comment by OvermindDL1** [comment]
Sounds like a hardware or driver issue as no usermode program should be able to do that, are you certain your GPU/RAM/Motherboard/CPU are in good order?

**Comment by matthew-cline** [comment]
> are you certain your GPU/RAM/Motherboard/CPU are in good order?

My machine is only a couple of years old, I haven't made any changes to the hardware, and the only software changes are automatic updates.

**Comment by OvermindDL1** [comment]
> My machine is only a couple of years old, I haven't made any changes to the hardware, and the only software changes are automatic updates.

Still good to perform stress tests (and depending on what part of a piece of hardware you are stressing may or may not reveal any issues, like testing nVidia GPU's are notoriously bad in their accuracy).  It should be outright *impossible* for a usermode application to hang a system like that, if it is not hardware or driver related then you found a kernel bug, which is extremely unlikely.  ^.^

**Comment by matthew-cline** [comment]
Any particular xorg/gpu stress tester you'd recommend?

**Comment by OvermindDL1** [comment]
I run the mesa tests but then I have mesa development installed as I use it, however it is great at testing near everything.  I know there are some dedicated testing setups out there though but I've not used any off-hand so can't really comment...

**Comment by krop** [comment]
I can confirm. Using openSUSE Tumbleweed & the NVidia blob (different versions tested)
It started before the 'Expressive upgrade' however. At some point, the machine starts swapping and everything finally hangs.

As a workaround, I run a while loop to kill any steamwebhelper process that spawns before launching Oxygen Not Included.
i.e:
```
while ( true ); do
  killall -9 steamwebhelper &>/dev/null
  killall -9 steamwebhelper.sh &>/dev/null
  sleep 5s
done
```
(I usually have to kill discord as well at some point)

Another alternative is to enable the sysrq keys and alt-prntscreen-F when the computer becomes unresponsive.

**Comment by OvermindDL1** [comment]
@krop Are you sure that is not some hardware or driver issue getting worse?  Again, a usermode application should not be even possible to hang something like the desktop unless there is a bug in the desktop, drivers, or hardware.

**Comment by krop** [comment]
> @krop Are you sure that is not some hardware or driver issue getting worse?
Yes. I'm sure it's not a memory/harddrive issue and I'm also convinced it's not a video driver issue or alt-prntscreen-F (aka OOM_KILL) wouldn't kill this process first.

I have a theory, the system doesn't like to have multiple web engines running at the same time (steamwebhelper/chromium, discord and/or the Firefox one). Webengines are monsters (resources and memory wise) and the system decides to sacrifice the worst one.

From what I can see, on startup, the Steam client creates (at least) one proxy - two tcp ports are listening - and launches 5 steamwebhelper processes.
If I had to make a guess from the command being executed, I'd say 4 of these 5 processes try to use this proxy.
I'm not really surprised to see them killed by the OOM_KILL call first.

**Comment by RomuloPBenedetti** [comment]
I'm having the same problem only with this game, on a GTX 1080, Fedora 29, driver 410.73 at the moment, it appears the game trigger some bad behavior of GPU driver, not same issue as @krop as I play other games like Witcher 3 without steamwebhelper give me a problem.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
