### ISSUE TITLE
Scrolling on new friends list skips too far

### ISSUE THREAD

**Issue by Svenare** [ValveSoftware/steam-for-linux#5577]
* Steam client version: Jul 24 2018
* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
New friends list moves too many lines when scrolling (2 scroll steps will move a friend from off the bottom of the list to off the top).  Scrolling in web browser is smooth, it's just native client.

#### Steps for reproducing this issue:
1) Open friends List
2) Scroll

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.17.3-1-vfio
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12000000
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.24
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 119 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20.91" x 11.73" (23.94" diag)
                                            53.1cm x 29.8cm (60.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16046 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.UTF-8
    Total Hard Disk Space Available:  922702 Mb
    Largest Free Hard Disk Block:  57549 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by kisak-valve** [comment]
Possibly related to #4722.

**Comment by kisak-valve** [comment]
Hello @Svenare, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as fixed some time ago. (#4722)
