### ISSUE TITLE
Steam In-Home Streaming fails if IPv6 is disabled system-wide

### ISSUE THREAD

**Issue by john5788** [ValveSoftware/steam-for-linux#5578]
#### Your system information

* Steam client version (build number or date): Jul 24 2018, at 18:27:28
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Click Stream on Aim Hero game. A window pops up very briefly and immediately closes. Game is still running on Host machine, client is doing nothing. This happens with any game, not just just Aim Hero.

I used to be able to use IHS and stream any game including non-Steam games before the update. My host is a Windows 10 system with various games installed and is also running the latest update.

#### Steps for reproducing this issue:

1. Launch Steam
2. Select Aim Hero (or any game)
3. Select Stream
4. Client window crashes.

**Comment by john5788** [comment]
I narrowed down the problem a little bit by executing the streaming_client command manually. I found the command and parameters by using the following strace:

$ strace -f -s999999 -o strace.log -e trace=clone,execve steam

This led me to:

$ /home/john5788/.local/share/Steam/ubuntu12_32/streaming_client --gameid 518030 --server 192.168.1.101:27031 --windowed --quality 2 --bitrate 50000 --captureres 0x0 bc85f0b599b2e{truncated}

When I execute that command, I see this:

/home/john5788/.local/share/Steam/ubuntu12_32/streaming_client: error while loading shared libraries: libtier0_s.so: cannot open shared object file: No such file or directory

I am using STEAM_RUNTIME, is this library missing from the latest update?

**Comment by john5788** [comment]
Notifying @slouken and @kisak-valve to take a look at the debugging and to hopefully get a fix in place. As far as I know there are at least 3 other occurrences of this from other people on Reddit and the Steam forums.

**Comment by backwardscamel** [comment]
Would this be the same issue going the other way? The July timing seems about right where my in home streaming stopped working. Only in my case I am running linux as the host and a Steam Link as the client (Also tried from the android Steam Link app). As soon as I try to connect, Steam on the host crashes with a "Couldn't create socket" message. I have tried all combinations of having ipv6 enabled/disabled on the host with beta and standard steam. If you need me to gather any more information let me know.

**Comment by kisak-valve** [comment]
Hello @john5788, are you still experiencing this issue on an up to date system?

Friendly side note that I'm a moderator for Valve's issue trackers and not a Valve developer myself.

**Comment by john5788** [comment]
> Hello @john5788, are you still experiencing this issue on an up to date system?
> 
> Friendly side note that I'm a moderator for Valve's issue trackers and not a Valve developer myself.

My personal fix was to recompile my kernel with IPv6 support enabled, although I don't even use it.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing pending confirmation that this issue still occurs.
