### ISSUE TITLE
Steam context/taskbar menu non-functional for setting status

### ISSUE THREAD

**Issue by nannerpusser** [ValveSoftware/steam-for-linux#5579]
#### Your system information

* Steam client version (build number or date): Jul 24th 2018
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

4.17.8-1-ARCH x86_64 bits: 64 Desktop: Cinnamon 3.8.8

#### Please describe your issue in as much detail as possible:
Left or right-clicking on the Steam tray icon produces the context menu as it should, but since the Friend List update I can no longer set my status via menu. I cannot set myself Offline and I cannot add the new options (Invisible) to the tray menu via Steam preferences. 

In fact I am having several issues with the new Friend List, but I am limiting this post to just this issue. 

#### Steps for reproducing this issue:

1. Run Steam client
2. Right or left-click your tray icon

**Comment by darealshinji** [comment]
For me the context menu of the tray icon is totally broken:

![screen](https://user-images.githubusercontent.com/5700937/43903689-46967274-9bed-11e8-865a-04ab87755a76.png)

System: Ubuntu 18.04 LTS, x86_64 Linux 4.15.0-30-generic
Desktop: MATE 1.20.0 (wm: Metacity)
Steam client: Aug 1st 2018

**Comment by darealshinji** [comment]
I fixed this issue on my system by installing the 32 bit libdbusmenu library: `sudo apt install libdbusmenu-gtk4:i386`

Steam will use those instead of the apparently broken ones from the runtime. But still, it should be possible to disable this in the settings.
