### ISSUE TITLE
Please let us download windows games

### ISSUE THREAD

**Issue by weltensturm** [ValveSoftware/steam-for-linux#5580]
With the help of DXVK, running even modern games on Linux is getting easier than ever. But if they require steam to run, the whole steam client has to run under Wine as well. This is a problem for two reasons:
* The user experience is trash (it takes ages for it to register clicks, for example)
* It logs you out of your native steam login

To solve this, I am asking for the ability to download games for any system target on the native client. Maybe even add the ability to launch it with Wine, and the ability to set ENV variables for that purpose.

Of course officially supporting that for every game is nigh impossible, for that reason I would hide it behind an option in the beta settings.

Since library detection depends on the "native" version of the game being present, you could also require to specify a "target OS" when adding a new library folder, where only those games can be installed to. This would allow to reuse an existing library when dual booting with windows, for example.

I don't know if it's feasible (probably requires to have the steam runtime running on wine in the background, so in-game steam features work), but I'm hoping for the best :)

**Comment by kisak-valve** [comment]
Hello @weltensturm, this feature request is already being tracked at #74 / #1989 / #4442. Closing as a duplicate.
