### ISSUE TITLE
Unable to close the "ALL NEW STEAM CHAT" window

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/steam-for-linux#5581]
#### Your system information

* Steam client version (build number or date): 
25.7.2018
* Distribution (e.g. Ubuntu): 
Gentoo
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
There is a fake window that covers a significant part of the screen, pressing x in top right corner does nothing.
![steam_window](https://user-images.githubusercontent.com/5174562/43222699-293e9b2c-9051-11e8-9493-60b0a308aaa2.png)

#### Steps for reproducing this issue:

1. Open Steam?

**Comment by Turmfalke2** [comment]
Found a way to close it, apparently I am expected to press on the megaphone, the X and the button at the bottom are just cosmetic.

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, have you seen this issue since initially encountering it?

**Comment by Turmfalke2** [comment]
I haven't seen that window in the last 2 years. Maybe it is displayed only once?

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as outdated.
