### ISSUE TITLE
Steam Controller + Steam Client on GNU/Linux - Big Picture Mode broken

### ISSUE THREAD

**Issue by user111222333** [ValveSoftware/steam-for-linux#5585]
system information

* Steam client version (build number or date): Build 1532458786 Date: July 24, 2018 
* Distribution (e.g. Ubuntu): GNU/Linux Debian 9 (Stretch) + Gnome Desktop + NVIDIA proprietary driver.
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

When starting / Initializing Steam Client in a 'Big Picture Mode' the Steam Controller is not passed on to the game application at all. Operating the controller buttons dose not produce any action with in the game. 
Only physical and mouse UHI devices passed to the game processes.

Running Steam Client in a Desktop mode passes interrupts from the Steam Controller correctly to the game application(s). This includes a custom config/setting profile loaded in to controller for the game. 

#### Steps for reproducing this issue:

1. Start Steam Client in the 'Big Picture Mode';
2. Navigate in the library to a game and choose 'Play' by pressing 'A' button on the Steam Controller.
3. Game will be started in full screen mode, but no actions/interrupts from Steam Controller will be passed on to the game. 
4. Quiting the game will 'drop' user in to a OS's desktop with an airmessage 'Steam already running';
5. Using a physical mouse, click on the air-message or the Steam Client Icon on a Gnome application launch panel, this will present a steam client UI in the 'Big Picture' mode and button/joystick actions by the user on the Steam Controller are passed to the Steam Client UI as expected. 

To work around this bug:

1. DO NOT run / start Steam Client in 'Big Picture' mode, instead, run the Steam Client in a desktop mode. 
When running a Steam Client in a desktop mode, Steam Controller's custom config/profile will be loaded in to Steam Controller and all interrupts/actions will be passed from the Steam Controller properly to the game(s). 

Dev team, whomever is reading this, please ask any questions you might have. I will provide as much info as I can to help to diagnose this so you can do what you do and change the code so this type of 'defects' do not take away from user experience and in turn quality of your product. 

Thank you. 

DM

**Comment by user111222333** [comment]
Additional details:
When Steam Controller connected via USB cable to the host machine, meaning - a wireless dongle is NOT used, this bug dose NOT manifest itself, and using Steam Client in 'Big Picture' mode allows a user to play/operate game(s) with the Steam Controller instead of physical keyboard and the mouse.

**Comment by Plagman** [comment]
Thanks for the report; does this happen with any game? Did it use to work properly and regress, or did that scenario never work properly on your end?

**Comment by user111222333** [comment]
Hello, thank you for your quick response. 
Just tested two games: Metro Last Light Redux and Metro 2033 Redux.
Here's results:

Both games experiencing same issue described above. 

It appears that there is a distinct difference how Steam Client handles initiation of the game(s) between Steam Client running in a Desktop Mode vs Steam Client running in a 'Big Picture' mode. 

When I start Metro 2033 Redux, I get present with  with a window and choices 'Play Metro and Start Metro'? Confusing, but that's not the point. When a I operate my Steam Controller and press 'A' button to 'play Metro' Steams Client UI goes away, game begins and disappears due to been minimized to the gnome application lunch panel. You end up been presented with a Destop and a games music playing on the back ground. And game is running just fine, it's minimized. 

There is a dialog message is hanging on the games screen and to bring it to the front you have to use alt+tab combination. 
Dialog message is the same for both games. In the top task bar of gnome desktop in shows 'mutter-dialog' and in the center of the screen its says "Metro stoped responding' and you have a choice to wait, or quit. 
Now, if you ignore it all together and press alt-tab again, you will be able to choose 'Metro' icon and once it brings actual games window to a full screen that previous 'mutter-dialog' goes away by itself. 

So, yes it happens with any game.
It worked like this always from very beginning. This is not a new issue of the new Steam Client released yesterday. (US Pacific time)

Just tested this this second:
What's new is that now, in Big Picture mode, controllers interrupts ether passed on to the game or the do not get passed on to the game, and that depends how you handle this 'mutter-dialog' message. If you ignore it completely, and wait for the game to pass its initial invitation to press '|>' (play) button, and than press alt+tab to chose the games icon, only than Steam Controller can be used to interact with the game. 
All other actions regarding starting the game and dealing with this start up dialog window will cause Steam Controller not to be able to operate the game and user would have to use the keyboard and the mouse to continue. 

Please let me know if this makes sense. 
It's hard to describe this using words. Taking screenshots it a bit difficult to because all this happens in the a spilt second. 

Please take a look at the screenshots attaches to my ticket here:
https://help.steampowered.com/en/wizard/HelpRequest/HT-FK7M-KGXX-9CVP

But this particular ticket is meant to address this new issue with a 'Big Picture' mode, because if you start Steam Client in the Desktop mode, even dealing with this game start up sequence issues, there is NO issues with Steam Controller interacting with the games.

Let me know if I can help you more to understand what the issue is. 

Thank you.

DM

**Comment by kisak-valve** [comment]
Hello @user111222333, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
