### ISSUE TITLE
turkish letter problem

### ISSUE THREAD

**Issue by DennysSFM** [ValveSoftware/steam-for-linux#5586]
#### Your system information

* Steam client version (build number or date): 1532458786
* Distribution (e.g. Ubuntu): Pardus DDE 17.3
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
hello i am from turkey and i am having some problem about writing turksih letters such as "ö ç ş ğ ü ı"

**Comment by systmrrr** [comment]
sana Türkçe cevap vereyim
sisteme Türkçe ve İngilizce dillerini kurarasan sorun çözülür.

**Comment by newbthenewbd** [comment]
+1. With the recent update of Steam "improving" the user interface (thanks for keeping `-nofriendsui -nochatui` there, either way), writing Unicode characters is broken unless the locale `en_US.UTF-8` is already generated in the system. This is however not the case for many popular distributions of Linux, which, if installed with a language different than English, only generate the UTF-8 locale of that language.

I am using Arch Linux, and in my case uncommenting `#en_US.UTF-8 UTF-8` in `/etc/locale.gen` followed by `sudo locale-gen` worked around the problem. However, I'd like to note that I don't consider this a viable long-term solution, as the line is often commented out by default, and uncommenting it certainly has a slight impact on the system's performance.

**Comment by DennysSFM** [comment]
problem fixed
