### ISSUE TITLE
SteamCMD Not Downloading

### ISSUE THREAD

**Issue by Enverex** [ValveSoftware/steam-for-linux#5588]
I've used SteamCMD to install games on Linux for a while now (and also Windows games on Linux by forcing the platform) and that used to work fine, but in the last few days it appears to have slowed to the point of uselessness. After trying to update No Man's Sky for around 10 hours now, it's made less than 7% progress.

The update looks like this:

	Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.28 (671054205 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.29 (672102781 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)
	 Update state (0x61) downloading, progress: 6.30 (673151357 / 10681419047)

As you can see it is progressing, just at a painfully slow pace. From what I can tell, I can see a single connection to a single Valve owned IP address in London and not much else. I've also tried other games with the same result. About 7KB/s traffic at most.

Are the update servers simply broken, or is this a SteamCMD issue specifically?

**Comment by kisak-valve** [comment]
Hello @Enverex, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
