### ISSUE TITLE
Steam friend list pops up randomly

### ISSUE THREAD

**Issue by RenuzitV** [ValveSoftware/steam-for-linux#5592]
My system information :
https://gist.github.com/RenuzitV/35276d82ffe97271264a006f19958077

* Steam client version (build number or date): Jul 24 2018
* Distribution : Windows
* Have you checked for system updates?: No
* Opted into Steam client beta?: No

After the steam UI update the friend list would randomly open and windows is forced to switch to it, ingame or not. I have tried turning off the friend list, set status to invisible or away, anything but it would still reopen unless i turn steam off. After a few times I think every time any of my friends had their status updated (playing some game, went online, etc) the friend list would pop up, hence why I've never seen any ingame notifications of my friend when they are playing anything, chat notifications and game (csgo) invites are fine though. Also I've seen some people have this problem, but most of my friends arent.

Steps for reproducing this issue:
1. Have Steam on and in online mode
2. Have a friend playing something
3. ingame (only tried with csgo fullscreen) or not (using chrome or anything), the friend list would pop up.

**Comment by kisak-valve** [comment]
Hello @RenuzitV, as noted before at https://github.com/ValveSoftware/csgo-osx-linux/issues/1735#issuecomment-408134123, this should be reported to the larger Steam team via [Steam Support](https://help.steampowered.com/en/).

Closing as Windows is not a flavor of Linux.
