### ISSUE TITLE
New Steam chat messes with top panel

### ISSUE THREAD

**Issue by undeference** [ValveSoftware/steam-for-linux#5597]
#### Your system information

* Steam client version (build number or date): Jul 24 2018, at 18:27:28
* Distribution (e.g. Ubuntu): Fedora 28
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When clicking on the top left corner of my top panel (in MATE with Compiz), the buttons should behave properly. After the Steam chat window opens, the top left of my top panel does not respond. Closing the window makes no difference. Moving the panel makes no difference. Only quitting Steam makes a difference.

#### Steps for reproducing this issue:

1. Click a top left button on the top panel to verify it works.
2. Start Steam
3. Open the new chat window

About 50% of the time, the buttons will stop working.

**Comment by undeference** [comment]
Perhaps

```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x5400106 (has no name)

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 64
  Height: 24
  Depth: 24
  Visual: 0x31c
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x5400105 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: yes
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+0  -1302+0  -1302-744  +0-744
  -geometry 64x24+0+0
```

**Comment by kisak-valve** [comment]
Thanks for checking. It's close enough for me. Closing in favor of the existing issue report (#5584).
