### ISSUE TITLE
Apparent Kernel Panic

### ISSUE THREAD

**Issue by Queuecumber** [ValveSoftware/steam-for-linux#5599]
#### Your system information

* Steam client version: Not sure how to get this, `steam --version` didnt work
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: I assume no
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Kernel 4.17.11 Ubuntu 18.04, I just downloaded and installed steam today for the first time and upon launching and going through the steam guard process, right before the full steam UI is about to show up (I can see the systray icon) the entire system locks up. I assume it is a kernel panic because not even magic sysrq is getting me out of it. The kernel is a custom one from [here](https://queuecumber.gitlab.io/linux-acs-override/). This on intel integrated graphics.

**Comment by kisak-valve** [comment]
Hello @Queuecumber, in general no opengl application should be capable of deadlocking a system, and you're probably seeing a kernel or video driver issue.

**Comment by Queuecumber** [comment]
Definitely agree with you on that one, any idea how I can try to debug it?

**Comment by kisak-valve** [comment]
You might be able to get a dying message from the kernel to another system with [netconsole](https://wiki.ubuntu.com/Kernel/Netconsole).

**Comment by Turmfalke2** [comment]
Other options are kexec with a backup kernel or if your hardware/kernel supports you might find something in pstore.

**Comment by byte1024** [comment]
Diagnosing these problems stink. It would be nice if it just popped up in logs or something, but nooooo that would be too easy, can't have that ;-)

**Comment by kisak-valve** [comment]
Hello @Queuecumber, are you still experiencing this issue on an up to date system?

**Comment by Queuecumber** [comment]
I'll check on it today, but I have reason to believe that there were hardware issues on that machine that may have caused it

**Comment by Queuecumber** [comment]
Seems to be working fine now
