### ISSUE TITLE
Feature Request: Steam for notebooks with Optimus

### ISSUE THREAD

**Issue by Tarik02** [ValveSoftware/steam-for-linux#5600]
I have a notebook with two graphical cards. The integrated one is slow, but consume less power and better for most time. But it's impossible to play any games with it. I am using [nvidia-xrun](https://github.com/Witko/nvidia-xrun) which runs desktop environment using the second graphical card. Also i've tried to use [Bumblebee](https://github.com/Bumblebee-Project/Bumblebee) with VirtualGL or with Primus, but they have very poor performance. So, what about to integrate something like nvidia-xrun into Steam and use it on notebooks with two graphical cards.

**Comment by crawfxrd** [comment]
Is this effectively the same as #634?
