### ISSUE TITLE
Error on keyborad/mouse configurations

### ISSUE THREAD

**Issue by dirlenekosvoski** [ValveSoftware/steam-for-linux#5604]
#### Your system information

* Steam client version (build number or date): Jul 24 2018
* Distribution: Debian Buster
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm having problems in the game settings section. When you click on the keyboard / mouse configuration option the game simply closes. I have already reinstalled the game and already checked the integrity of the files (only one file is in error, but it always happened). My operating system is Linux (Debian).
I'm having problems with game settings. When you open the keyboard / mouse options tab, the keys set for the keyboard do not appear. In the game it works but does not appear in the settings. Even now, you are no longer opening the keyboard / mouse settings, when I click the option the game closes.

#### Steps for reproducing this issue:

1. Open the game on Debian 
2. Select Options
3. Select Keyboard/mouse

The game closes or the configurations of keyboard keys are disappear

**Comment by kisak-valve** [comment]
Hello @dirlenekosvoski, assuming this is actually referring to CS:GO, then this is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1680. Closing as a duplicate.
