### ISSUE TITLE
Help Please, can't connect steam link to my linux computer.

### ISSUE THREAD

**Issue by Ngk252** [ValveSoftware/steam-for-linux#5605]
#### Your system information

* Steam client version (build number or date): 1533163808
* Distribution (e.g. Ubuntu): linux mint 18.3 silvia
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

Hi everyone I'm new around here, don't know if anyone will be able to help me, but thanks in advance for trying. 
I have an issue connecting the steam link to my computer. 
The computer is connected via cable to the router, and the steam link is connected via wifi to the same router. The router is a xiaomi ac1200. I have added rules in the linux mint firewall for TCP ports 27036 and 27037. Also for UDP port 27031. I have also added port forwarding rules in the router's admin page for those ports and also for port UDP 27036. But still steam link cannot see my computer, i do not know what is wrong. I thought connecting the steam link to my computer would not be that difficult, but it's turning out to be a pain in the .... 
If anyone has any idea how to fix this please help me out. Thanks very much. 

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Ngk252, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
