### ISSUE TITLE
happen the issue when i play csgo

### ISSUE THREAD

**Issue by JammyLin** [ValveSoftware/steam-for-linux#5608]
#### Your system information

* Steam client version (build number or date): 1533766730
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
![img_1687](https://user-images.githubusercontent.com/23147837/43683635-94f3535c-98c2-11e8-84f2-677960745bf5.JPG)
![img_1686](https://user-images.githubusercontent.com/23147837/43683620-54253a98-98c2-11e8-99a2-a41cdecf27ec.JPG)

#### Steps for reproducing this issue:

1. play csgo
2. Suddenly,i can't move and the screen keeps jumping,but i can hear my teammate's voice
3. 5s ago,disconnect.

**Comment by kisak-valve** [comment]
Hello @JammyLin, let's track this issue in the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1774.

**Comment by JammyLin** [comment]
If i remember correctly,there was no code 4001 before the new ui was update.
