### ISSUE TITLE
out of memory or address space. texture quality setting may be too high

### ISSUE THREAD

**Issue by psposito** [ValveSoftware/steam-for-linux#5613]
#### Your system information

* Steam client version (build number or date): 1.0.0.54-3
* Distribution (e.g. Ubuntu): Arch Linux (Antergos)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Install Pirate Vikings and Knight II
2. Run the game
3. Get the Error: out of memory or address space. texture quality setting may be too high

**Comment by kisak-valve** [comment]
Hello @psposito, this issue should be brought to the attention of the game's devs.

This is most likely related to https://github.com/ValveSoftware/Source-1-Games/issues/2212 and mesa 18.1.5 or newer may improve the game's behavior.

**Comment by psposito** [comment]
Thank you.

I am already using mesa 18.1.5, just for information.
