### ISSUE TITLE
Menus Not Functioning Properly

### ISSUE THREAD

**Issue by Retalak** [ValveSoftware/steam-for-linux#5614]
#### Your system information

* Steam client version (build number or date): Aug 1 2018, at 22:27:11
* Distribution (e.g. Ubuntu): Arch w/ GNOME
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Menus in the top left of the client do not behave the way they should. Left clicking on a menu after opening it does not close it, you have to right click. Also, if you open the Friends List through either View->Friends or Friends->Friends List, the respected menu stays open and will only go away when you left click on that menu item to reopen it and then right click on it.

#### Steps for reproducing this issue:

1. Left click on "View" or "Friends"
2. Left click on "Friends" or "Friends List". Notice how the menu stays on top of everything.
3. Left click on the same menu again and then right click on it to close. (It would make sense for left click to close the menu, would it not?)

**Comment by kisak-valve** [comment]
Hello @Retalak, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
