### ISSUE TITLE
CSGO can't download any community server data

### ISSUE THREAD

**Issue by MChelik** [ValveSoftware/steam-for-linux#5615]
#### Your system information
[lshw.txt](https://github.com/ValveSoftware/steam-for-linux/files/2277738/lshw.txt)

* Steam client version (build number or date): Aug 8 2018
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, everything is up-to-date

Hello,
Everytime I try to play in any Community Server at CSGO, it gets stuck downloading the maps' data. The link game trying to download actually exists (I copied the link from CSGO console and pasted in browser and it downloads a bz2 file). But somehow game doesn't download it. This bug exists for a long time. Please fix it so we can play on community servers like others.
Thanks

**Comment by kisak-valve** [comment]
Hello @MChelik, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1568. Closing as a duplicate.
