### ISSUE TITLE
Installing games to seperate harddrive

### ISSUE THREAD

**Issue by IvoKintobor** [ValveSoftware/steam-for-linux#5616]
Steam client version (build number or date): Aug 8 2018
Distribution (e.g. Ubuntu): Ubuntu 18.04
Opted into Steam client beta?: No
Have you checked for system updates?: Yes, everything is up-to-date

I have ubuntu 18.04 installed on a 500gb ssd, I have a data RAID array for games and misc. file storage, that is 3x4tb harddrives in RAID 5.

My issue is that when i go to install a game on the raid drive, it shows 0mb free space, yet i see 4.7tb free.

**Comment by nstgc** [comment]
How much space is on `/` and `/home` and `/home/userName`? I've had this happen before as well, since I have a very similar set up (/ is on a RAID1 and games on a RAID0).

**Comment by kisak-valve** [comment]
Closing in favor of #5742.
