### ISSUE TITLE
Unturned - Cinnamon stopped working + dark blue-screen-background window

### ISSUE THREAD

**Issue by Aemuthi** [ValveSoftware/steam-for-linux#5618]
#### Your system information
( From Steam "Help>System Information")
```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
    CPU Family:  0x6
    CPU Model:  0x4e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-47-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce 940MX/PCIe/SSE2
    Driver Version:  4.5.0 NVIDIA 367.57
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x179c
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 12.17" x 6.81" (13.94" diag)
                                            30.9cm x 17.3cm (35.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: %s1

Memory:
    RAM:  7857 Mb

Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.UTF-8
    Total Hard Disk Space Available:  635492 Mb
    Largest Free Hard Disk Block:  382104 Mb
    VR Headset: None detected

Recent Failure Reports:None
```

* Steam client version (build number or date): Built: Aug 8 2018, at 21:32:49
Steam API: v018
* Distribution (e.g. Ubuntu):  Ubuntu 16.04.1 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have no issues with Steam, nor did I have issues with Unturned before around the 25th July 2018. Since then I can't play Unturned, it keeps making Cinnamon crash (I guess it's responsible for the Linux U.I, I don't really know). I tried reinstalling Unturned and Steam and checked for updates, I searched on forums & threads, nothing will do. I also asked for the Steam Support which redirected me here. This is my last resort, I waited quite a moment before doing so.

#### Steps for reproducing this issue:
1. Execute Steam, Execute Unturned from the library
2. Unturned window shows up in a dark-blue background color
![capture du 2018-08-11 18-37-52](https://user-images.githubusercontent.com/41784827/43992934-07b8625a-9d97-11e8-9895-2c7bc27f02cc.png)

3. After 5 or so seconds, Cinnamon crashes and the window "Cinnamon just crashed .You are currently running in Fallback Mode." appears. the UI is completely broken* and the Unturned Window is either inaccessible or still with a dark-blue background.
![cinnamon crashbox](https://user-images.githubusercontent.com/41784827/43992925-d3c680d0-9d96-11e8-8fdf-61967d76ad89.jpg)
![cinnamon crashbox2](https://user-images.githubusercontent.com/41784827/43992930-ef180688-9d96-11e8-8460-b1016b8264a1.jpg)
(Can't take screeshots while an error box appears)

4.a.If you choose to restart Cinnamon, it will restart (closing and reopening every window and the desktop) but then crash again.
4.b.If you don't restart Cinnamon, Unturned stays inaccessible, U.I. stays broken* and you must force-shutdown to close the session.

*broken means different, the taskbar is above, the Start button dissapeared, and some other minor things.

Cinnamon doesn't always crash, sometimes i just have the Unturned window and nothing happens. I close the window after waiting a while but nothing special happens.
Once I managed to actually make it work but never managed to get the same result : Cinnamon didn't crash, I waited then closed the Unturned window using ALT+F4 and the cross, and Cinnamon crashed. After I restarted it, it didn't crash again, and Unturned was on the loading screen, so I was able to play until I closed it.

I also rarely get an error box saying : 
`[Notify 22:13:03.455] Docky - Docky nécessite la transparence pour fonctionner correctement. Certaines options sont inhibés et les thèmes et animations vont s'afficher de manière incorrecte.`
Translated : 
`[Notify 22: 13: 03.455] Docky - Docky requires transparency to work properly. Some options are disabled and the themes and animations will display incorrectly.`

Another rare event : Cinnamon crashes when I close Unturned (dark-blue-background window), I just restart it and it works.

Thanks for taking your time reading all of this and trying to solve my problem :1st_place_medal: 
-Aemuthi

**Comment by kisak-valve** [comment]
Hello @Aemuthi, this issue reads like a DE or video driver issue. You may have better luck with a newer video driver version.

**Comment by hasezoey** [comment]
Having the same problem with Software Inc (Linux Version):
Cinnamon Crash + Where the Game window should be is a dark-blueish area
https://gist.github.com/hasezoey/dc58e334ed8be139f395b7b003cca2b4
(4.a & 4.b dosnt happen to me)

**Comment by kisak-valve** [comment]
Hello @Aemuthi, @hasezoey, are either of you still experiencing this issue on an up to date system?

**Comment by hasezoey** [comment]
@kisak-valve no i dont have it anymore for latest Software Inc(Linux Version), but my hardware changed i dont use nvidia anymore
(switched from GTX 1080 to Vega 64) (and processor changed too i7-4790 -> i7-7700K) since around that time it worked again (and forgot to report back here) - but i dont know if something in the software changed

(still using Cinnamon, on Linux Mint 20)

**Comment by Aemuthi** [comment]
Hello kisak, I'm not using my Linux laptop anymore. Last time I tried launching unturned with it goes back to over a year and a half, and still didn't work, so I probably can't help you more than that...

Have a good day
Aem

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing because there isn't a test case anymore.
