### ISSUE TITLE
Assersion Failed Spam when Downloading Workshop Content

### ISSUE THREAD

**Issue by mikenune** [ValveSoftware/steam-for-linux#5619]
#### Your system information

* Steam Console Client (SteamCMD). Current version as of 2018-08-11
* Linux Debian 9 (Stretch) Kernel 4.9.0-7-amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When running SteamCMD to download and install updates for the ARK: Survival Evolved dedicated server (app ID 376030), I get spammed with the following error message for every workshop Mod I download. This message appears 8 times in rapid succession for every workshop item downloaded. This becan with the most recent update to SteamCMD and effects all SteamCMD isntallations on the system. I have attempted re-installation of SteamCMD but it did not correct the issue.

I have been informed by others that this is not limited to workshop content from a single game (ARK: Survival Evolved) but have not personally confirmed this is the case.

It does not appear to interfere with the download process itself, but it makes my logs VERY chatty and causes difficulty locating specific items within it.

Error Message:
```
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
```

#### Steps for reproducing this issue:

1. Run SteamCMD and download a workshop item (Workshop items for the ARK: Survival Evolved server are still referenced using the PREVIOUS app ID of 346110 instead of the current app ID of 376030).
```
./steamcmd.sh
@ShutdownOnFailedCommand 1
@NoPromptForPassword 1
@sSteamCmdForcePlatformType linux
login anonymous
force_install_dir "/home/steam/ark"
app_update 376030 validate
workshop_download_item 346110 899987403
```
2. View output and see assertion message spam:
```
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
@ShutdownOnFailedCommand 1
"@ShutdownOnFailedCommand" = "1"
@NoPromptForPassword 1
"@NoPromptForPassword" = "1"
@sSteamCmdForcePlatformType linux
"@sSteamCmdForcePlatformType" = "linux"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir "/home/steam/ark"
app_update 376030 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 2.26 (157912572 / 6972906450)
 Update state (0x5) validating, progress: 9.55 (666190827 / 6972906450)
 Update state (0x5) validating, progress: 13.22 (921913633 / 6972906450)
 Update state (0x5) validating, progress: 19.26 (1343210065 / 6972906450)
 Update state (0x5) validating, progress: 26.57 (1852364880 / 6972906450)
 Update state (0x5) validating, progress: 33.63 (2345133268 / 6972906450)
 Update state (0x5) validating, progress: 41.12 (2867162703 / 6972906450)
 Update state (0x5) validating, progress: 48.57 (3386927746 / 6972906450)
 Update state (0x5) validating, progress: 54.50 (3800185650 / 6972906450)
 Update state (0x5) validating, progress: 60.07 (4188433875 / 6972906450)
 Update state (0x5) validating, progress: 68.54 (4779303510 / 6972906450)
 Update state (0x5) validating, progress: 75.49 (5263676453 / 6972906450)
 Update state (0x5) validating, progress: 81.77 (5701891604 / 6972906450)
 Update state (0x5) validating, progress: 86.55 (6034768160 / 6972906450)
 Update state (0x5) validating, progress: 91.66 (6391438588 / 6972906450)
 Update state (0x5) validating, progress: 96.69 (6741953470 / 6972906450)
Success! App '376030' fully installed.
workshop_download_item 346110 899987403
Downloading item 899987403 ...contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized
contentmanifest.cpp (650) : Assertion Failed: !m_bIsFinalized

Success. Downloaded item 899987403 to "/home/steam/ark/steamapps/workshop/content/346110/899987403" (471718302 bytes) quit
```

**Comment by mr-bo-jangles** [comment]
I can confirm that workshop items from the Arma3 workshop are also affected

**Comment by Varrkan82** [comment]
Confirmed on Debian 9.5.

**Comment by christyganger** [comment]
Same with ubuntu 16.04 LTS

**Comment by idahlke** [comment]
Same here for ARMA items.

`workshop_download_item 107410 463939057 validate
workshop_download_item 107410 773131200 validate
workshop_download_item 107410 773125288 validate
workshop_download_item 107410 450814997 validate
workshop_download_item 107410 497660133 validate
workshop_download_item 107410 843425103 validate
workshop_download_item 107410 843577117 validate
workshop_download_item 107410 498740884 validate
workshop_download_item 107410 620019431 validate`

**Comment by johnsmm** [comment]
same on windows, Valve any resolution ?

**Comment by kosimas** [comment]
still an issue. Happens to me for Arma 3 Workshop content.

**Comment by thakyZ** [comment]
I get the same on Ubuntu 16.04 for Starbound content.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
