### ISSUE TITLE
copy and pasting text crashes client

### ISSUE THREAD

**Issue by raenii** [ValveSoftware/steam-for-linux#5625]
#### Your system information

* Steam client version (build number or date): aug 8 2018, 21:32:49
* Distribution (e.g. Ubuntu): ubuntu
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
when i copy or paste text in the steam client or friends list, the web portion of it crashes.

#### Steps for reproducing this issue:

1. copy/paste text using the steam client, steam chat or steam in-game overlay

**Comment by kisak-valve** [comment]
Possibly related to https://github.com/ValveSoftware/Source-1-Games/issues/2636.

**Comment by kisak-valve** [comment]
Hello @raenii, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
