### ISSUE TITLE
Can't access to cdn with Wine client

### ISSUE THREAD

**Issue by jusdepatate** [ValveSoftware/steam-for-linux#5627]
#### Your system information

* Steam client version (build number or date): 19/08/2018 Windows client
* Distribution (e.g. Ubuntu): Ubuntu Mate 18.04 & Wine 2.12 (using POLinux)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] : Yes

#### Please describe your issue in as much detail as possible:

I can't download any games

#### Steps for reproducing this issue:

1. Install Steam throught POLinux
2. Try to install a game
3. Enjoy

#### What I tried
#2573 #2645 #3401 #3450 and [#1456-EUDN-2493](https://support.steampowered.com/kb_article.php?ref=1456-EUDN-2493), also changed my dns to cloudflare, dnsmasq, unbound, nothing works
Thanks, jdp

**Comment by kisak-valve** [comment]
Hello @jusdepatate, I was saw this is a few days back and it's a wine issue that was fixed somewhere between 3.0.2 and 3.13. Please update to a newer version of wine.

Closing as Steam for Windows via wine issues are outside the scope of the steam-for-linux issue tracker.
