### ISSUE TITLE
CS-GO on Ubuntu 16.04.5 LTS - crashes on startup due to new panorama UI

### ISSUE THREAD

**Issue by dpdpkpcom** [ValveSoftware/steam-for-linux#5628]
#### Your system information

* Steam client version (build number or date): 
Aug 8 2018 - 1533766730

* Distribution (e.g. Ubuntu): Ubuntu 16.04.5 LTS

* Opted into Steam client beta?: [Yes/No] No

* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
From any part of the Steam UI, initiated launch of CS-GO. Before the latest update, it launched fine with the -scaleform switch (bypassing Panorama UI). Without that switch I could get into the game approx 25% of the time through Panorama UI, but the remaining 75% of the time I got a "Segmentation Fault". Since the update last week, the -scaleform launch option doesn't seem to work and instead the game tries to load, the screen goes black for a few seconds  and the console reports "Segmentation Fault" before the screen returns to desktop.

By adding the switch -legacyscaleformui as a launch option in the Steam UI, the game launches seamlessly in the old UI (NOT Panorama), which is fine by me.

Without the switch, it segfaults....

Dmesg reports -
csgo_linux64[11896] general protection ip:7f89c84b7cf3 sp:7ffdfcd25d50 error:0 in libSDL2-2.0.so.0[7f89c8468000+f8000]

GDB backtrace reports - 
#0 0x00007ffff5a09cf3 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libSDL2-2.0.so.0
#1 0x00007fffe46abace in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#2 0x00007fffe46ad82b in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#3 0x00007fffe4697549 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#4 0x00007fffe4759403 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#5 0x00007fffe45e4220 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/panorama_client.so
#6 0x00007fffee123c4a in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#7 0x00007fffee123d4d in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#8 0x00007fffede38d92 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#9 0x00007fffede391cd in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#10 0x00007fffedf17100 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#11 0x00007fffee044d84 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#12 0x00007fffee046b55 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#13 0x00007fffee054b25 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#14 0x00007fffee054fd4 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#15 0x00007fffee0ccd52 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#16 0x00007fffee0c8c62 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#17 0x00007fffee0c8d8a in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#18 0x00007fffee2bb469 in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#19 0x00007fffee0ca94c in ?? () from /home/dp/bigssd/Steam2/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so
#20 0x00007ffff68c2499 in ?? () from bin/linux64/launcher_client.so
#21 0x00007ffff68c2499 in ?? () from bin/linux64/launcher_client.so
#22 0x00007ffff68998f9 in LauncherMain () from bin/linux64/launcher_client.so
#23 0x00007ffff75dd830 in __libc_start_main (main=0x4006f0 <main>, argc=3, argv=0x7fffffffdb88, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, 
stack_end=0x7fffffffdb78) at ../csu/libc-start.c:291
#24 0x000000000040079d in _start ()

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I expected the game to launch, not segfault.

#### Steps for reproducing this issue:

1. Launch CS-GO 

If you need any more info, please shout.....

**Comment by kisak-valve** [comment]
Hello @dpdpkpcom, let's track this issue in the csgo-osx-linux issue tracker at https://github.com/ValveSoftware/csgo-osx-linux/issues/1789.
