### ISSUE TITLE
Steam can not run games

### ISSUE THREAD

**Issue by RushabhJoshi** [ValveSoftware/steam-for-linux#5629]
#### Your system information
Ubuntu 18.04.1 LTS
RAM: 6GB
Processor: Intel Core i5
Graphics: Intel Ironlake
Gnome: 3.28.2
OS Type: 64-bit

* Steam client version (build number or date): Aug 8, 2018, at 21:32:491533766730
* Distribution (e.g. Ubuntu): UBUNTU 18.04.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I click on a play button one message box pop up with a message
e.g. "Preparing to launch unturned"
then nothing works

#### Steps for reproducing this issue:

1. Open steam client
2. Enter in games library
3. Click on a game to play (e.g. Unturned)

**Comment by kisak-valve** [comment]
Hello @RushabhJoshi, I took a look at this on my Manjaro Intel gen 4 graphics test box and Unturned uses a version of Unity which requires OpenGL 3.2 or newer while your video chipset only supports OpenGL 2.1.

```
[kisak@Manjaro ~]$ cat ~/.config/unity3d/Smartly\ Dressed\ Games/Unturned/Player.log 

Selecting FBConfig
GLX_FBCONFIG_ID=100
GLX_BUFFER_SIZE=32
GLX_DOUBLEBUFFER=1
GLX_RED_SIZE=8
GLX_GREEN_SIZE=8
GLX_BLUE_SIZE=8
GLX_ALPHA_SIZE=8
GLX_DEPTH_SIZE=24
GLX_STENCIL_SIZE=8
GLX_SAMPLES_ARB=0
GLX_SAMPLE_BUFFERS_ARB=0
GLX_STEREO=0
GLX_CONFIG_CAVEAT=NONE

Desktop is 1280 x 800 @ 60 Hz
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 59, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 62, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 65, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 68, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 71, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 74, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 77, XID 04a00002, display 0x3f15820
XError: GLXBadFBConfig (error 170, opcode 153/34, serial 80, XID 04a00002, display 0x3f15820
Failed to create valid graphics context: please ensure you meet the minimum requirements
E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer
```

Closing as this is a hardware limitation.

**Comment by Darxus** [comment]
The first line of the previous post was the location of the crash log:

[kisak@Manjaro ~]$ cat ~/.config/unity3d/Smartly\ Dressed\ Games/Unturned/Player.log
