### ISSUE TITLE
Steam Play does not work, Steam Client quits

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#5630]
Using the latest Beta Client available today, trying to enable Steam Play for all titles to test it out (since it appears we need to do that, a mentioned game has no install button yet) just crashes the Steam Client.

What logs do you need? Here's a DMP: http://www.filedropper.com/assert201808212316261

Ubuntu 18.04 64bit.

**Comment by felixactually** [comment]
Confirmed on Kubuntu 18.04 64 bit. Using Nvidia proprietary drivers.

**Comment by kisak-valve** [comment]
Hello, was everyone affected using the steam beta client before the announcement? Please try switching to the stable client and back to the beta client and see if that shows improvement.

**Comment by felixactually** [comment]
I switched to the Beta update a while after the announcement. Switching back to non-Beta and then to Beta again resulted in the same crash.

**Comment by tim241** [comment]
I opted out from the beta, then opted in again, results in the same crash

**Comment by LiamDawe** [comment]
I opted out of the beta and back in, it now works. Downloading Doom right now to test.

**Comment by chtk** [comment]
Opted out of beta, and back in. I now have Steam Play enabled globally. Installing Borderlands as I write this.

**Comment by tim241** [comment]
UPDATE: after a restart(after opting back into beta and then restarting) seems to have fixed it!

**Comment by swedneck** [comment]
Can confirm it is fixed

**Comment by bdefore** [comment]
Working for me as well. Did not need to opt out and back in again.

**Comment by Leopard1907** [comment]
It works , although i didn't have the opt out or anything like that. Just worked

**Comment by felixactually** [comment]
Steam Play is now working! Thanks for the fix.
So far I have tried Scrap Mechanic and Raft. Scrap Mechanic crashes to Bugsplat and Raft water is invisible, like when the game is run through regular Wine with DXVK. Does Proton use DXVK?

**Comment by romulasry** [comment]
Does Proton use DXVK?
-- Yes.

**Comment by felixactually** [comment]
Raft water is visible now. I forgot to mention that sooner.
