### ISSUE TITLE
Games where Mac/Win AppID differ are both listed

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/steam-for-linux#5632]
Grand Theft Auto III (12230)
Grand Theft Auto III (12100)
Grand Theft Auto: San Andreas (12120)
Grand Theft Auto: San Andreas (12250)
Grand Theft Auto: Vice City (12110)
Grand Theft Auto: Vice City (12240)
Sid Meier's Civilization IV (34440)
Sid Meier's Civilization IV (3900)
Sid Meier's Civilization IV: Beyond the Sword (34460)
Sid Meier's Civilization IV: Beyond the Sword (8800)
Sid Meier's Civilization IV: Warlords (34450)
Sid Meier's Civilization IV: Warlords (3990)

All the above are listed under STEAMOS+LINUX, with the "Enable Steam Play for all titles" toggle enabled. Unless there's some more exciting work happening back there, this ought to filter out Mac-only games, like the duplicates above.

**Comment by kisak-valve** [comment]
Hello @directhex, this issue is already being tracked at #3406. Closing as a duplicate.
