### ISSUE TITLE
Cannot launch DOOM on Steam Play - Failed to read default.cfg

### ISSUE THREAD

**Issue by OrdinaryMagician** [ValveSoftware/steam-for-linux#5637]
#### Your system information

* Steam client version (build number or date): Aug 21 2018, 22:37:24
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Expected: Normal game launch, like it would do on a Steam install through Wine.
Got: Black screen, console window with "FATAL ERROR: Failed to read default.cfg".

Full log from the game: [ErrorLog_08-22-2018__01-36-11pm.txt](https://gist.github.com/OrdinaryMagician/8652dcbd895303f74052aab3d8c4c49b)

#### Steps for reproducing this issue:

1. Install DOOM
2. Launch through Steam Play
3. Error happens

**Comment by OrdinaryMagician** [comment]
My apologies, it seems this issue has already been reported on the Proton tracker.

**Comment by bash64** [comment]
where is the proton bug tracker???

**Comment by OrdinaryMagician** [comment]
[I'll just link the issue](https://github.com/ValveSoftware/Proton/issues/16)

**Comment by bash64** [comment]
use steam runtime version rather than the native version. issue fixed.
