### ISSUE TITLE
Achievement reset with Steam Play

### ISSUE THREAD

**Issue by elnabo** [ValveSoftware/steam-for-linux#5643]
#### Your system information

* Steam client version : 21 august 2018 at 22:37:24
* Distribution Opensuse 15: 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I used Steam Play to play Age of Empire 2 HD. But when I launched the game, I noticed all my achievements for this game had been reset.

Update : The achievements are reset every time I launch the game.

**Comment by methos789** [comment]
I have the same problem

* Steam client version: 21 august 2018 at 22:37:24
* Distribution: Ubuntu 16.04.5 (64-bits)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

**Comment by xDShot** [comment]
I see all achievements locked in Left 4 Dead 1, though in game menu.

Also Killing Floor 2 has progress reset (all perks are at 0 level) and inventory items missing.

**Comment by shepard8** [comment]
In [this topic](https://steamcommunity.com/app/221380/discussions/2/1736588252395483682/) on Steam, the third post mentions some internal memory representation that is fixed to zero in Steam Play.

I don't know if it helps in any way, but let's gather the available information.

**Comment by beaverusiv** [comment]
I have this same issue and I really hope I can get my achievements back - took 1,500 hours to get what I had...

**Comment by eritro** [comment]
Fixed for me on Proton 3.7-6 Beta

Had this same problem on Age of Empires II: HD Edition

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by elnabo** [comment]
Tried today with Age of Empire 2, using Steam beta built Oct 25 2018, at 22:23:23 and Steam proton 3.7-8.

Seems fixed.

**Comment by shepard8** [comment]
Seems fixed for me too. Thanks!

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
