### ISSUE TITLE
Gamepad not working ingame through Proton in last version of Beta Client

### ISSUE THREAD

**Issue by P4NCH1** [ValveSoftware/steam-for-linux#5648]
**System information:**
* Steam client version (build number or date): 1535014307
* Distribution (e.g. Ubuntu): SteamOS 2.0 update 1:2.154
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

**What is expected:**
Can play any game through Steam Play / Proton with the gamepad like it do works for native Linux games.

**What did happen:**
Can use the gamepad over the BPM interface and to play native Linux games but can not use it to play game through Proton. The gamepad is not detected by the games like it wasn't connected.

**Steps for reproducing this issue:**
1. Turning on PC with or without gamepad connected
2. Autologin to Steam account
3. Connect gamepad if not already connected
4. Lunch a game to play through Proton
5. Gamepad is not detected by the game.

**Other notes:**
In Steam client version 1534892652 the gamepad was working fine. I've tested [gameplay through Proton with DBXV](https://youtu.be/pTWKdoxlDjY).

**Comment by P4NCH1** [comment]
Following with this issue, if I get out of BPM and start Steam Client in normal mode _following the [steps of the workarround for activating Steam Play for all titles](https://github.com/ValveSoftware/steam-for-linux/issues/5631)_ and go to Controller/Gamepad settings it directly says that there is no Controller/Gamepad connected, even if I disconnect it and connect it again

**Comment by P4NCH1** [comment]
Tried this in other system and have the same issue in BPM. Now downloading a game to check if gamepad works ingame.

**System information:**
*Steam client version: 1534979715
*Distribution: MX Linux 17 Horizon
*Opted into Steam client beta?: Yes
*Have you checked for system updates?: Yes

**Comment by Jaegrqualm** [comment]
Also experiencing this. Would downgrade if there was a way.
Arch, current.

**Comment by Juppstein** [comment]
Same issue on Ubuntu 18.04 with Kernel 4.18.4 and Mesa 8.3-devel. Gamepad is an Xbox360 Wireless Controller

**Comment by Jaegrqualm** [comment]
...And somehow it just started working. I don't really know how.

I had plugged in a Gamecube controller, which i messed around with in steam before closing the window(and steam stayed open after that, which is unusual) and went on to play melee with dolphin for a little while. my adapter has PC and Wii U compatability modes with a little switch on the box, it's flipped to wii u for dolphin, and to pc for steam. after playing that for a while, i decided to go over and launch dark souls from the system tray, and after loading up it just miraculously worked. I think that's all the detail I can give. I don't get it.

**Comment by P4NCH1** [comment]
Yeah, I tried again in my SteamOS PC and now seem to be working well in **Steam Client version 1535014307**
It got updated when I turned on to try again.

Will wait some more time and tests before close the issue. Seems to be a recursive problem and not only on generic gamepads

**Comment by P4NCH1** [comment]
Issue updated taking on count last version of Steam client and tests done.

**Comment by DePingus** [comment]
Fedora 28 - Nvidia 396.65 (Negativo17) - Steam 1535768746 (beta client Sept1)

My Steam Controller works normally in BPM. The nav icons in BPM are normal controller icons. Games don't detect the controller. Dead Cells even says "this game works best with a controller" and has nav icons for KB/M. I also tried Hollow Knight and Shadow of Mordor. Same crappola.

I also tested this with my Steam Link + Wireless Xbox360 controller. I get the same thing. BPM works, but the games don't detect any gamepad.

**Comment by P4NCH1** [comment]
I retest this DBXV in actual Steam version and [woks without problems](https://www.youtube.com/watch?v=6Y_oCIJZjpw). Steam detects my generic gamepad as PS3 gamepad and the game as an XBox one but it's no issue.
Gamepad works fine in BPM interface too.

Will close this for now. Don't know if anybody else can reopen it if still have problems but the main issue is solved.
