### ISSUE TITLE
Need for Speed Hot Pursuit has no sound at all

### ISSUE THREAD

**Issue by landjalan** [ValveSoftware/steam-for-linux#5651]
#### Your system information

* Steam client version (build number or date): current
* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] no

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. install game with proton 3.7
2. start and play
3. no sound

**Comment by kisak-valve** [comment]
Hello @landjalan, Proton-related issues are being tracked in its issue tracker. Let's track this issue at https://github.com/ValveSoftware/Proton/issues/277.
