### ISSUE TITLE
DayZ 0.63 Stresstest Battleye not working

### ISSUE THREAD

**Issue by jcr1985** [ValveSoftware/steam-for-linux#5653]
#### Your system information

* Steam client version (build number or date): Aug 23 2018 08:26:40
* Distribution (e.g. Ubuntu): Xubuntu 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Trying to start DayZ which causes the Battleye Launcher (Anticheat) to hang and crash. DayZ is working fine in Offline mode without Battleye enabled.

**Comment by Uramekus** [comment]
Can you please change the title to "Battleye Titles not working" or "Kernel level anticheats are not working "  ? 



this is a persisting issue, given that proton is based on wine and kernel-level anticheats are still  unsupported right now

**Comment by kisak-valve** [comment]
Hello @jcr1985, issues with games run with Proton are being tracked in the [Proton](https://github.com/ValveSoftware/Proton) issue tracker.
