### ISSUE TITLE
Update Loop After Enabling Proton for All Games

### ISSUE THREAD

**Issue by SomeNowTakenUsername** [ValveSoftware/steam-for-linux#5657]
#### Your system information

* Steam client version (build number or date): Latest Beta
* Distribution (e.g. Ubuntu): Arch Linux 64 bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After doing the steps below the following output repeats and continues to open and close the Steam updating window on each cycle.
Edit: For clarification I'm not able to get to the standard Steam GUI so I can't change it back. This happens with the window that pops up everytime  you open steam after restarting you computer.
I installed steam-native-runtime and ran with steam-native but nothing changed.
[Github Gist](https://gist.github.com/SomeNowTakenUsername/7210624f14bfe49ae245c8bd5ad9827d)

#### Steps for reproducing this issue:

1. Opt into Steam Play beta in settings
2. Restart Steam and get updates
3. Go into settings and enable Proton for all games
4. Restart Steam

**Comment by Gokuroro** [comment]
Disabling Proton for all games and enabling it again seem to also trigger the update request.
It looks like the games installed directly through Linux Steam Play originally will only reupdate once, but will do require it again every time you disable and enable the Proton for all games option.

**Comment by RaptorRCX** [comment]
I don't know. For me, I was about to make an issue and saw this. It's reupdating my games every time I launch steam, regardless if I mess with proton settings or not.

**Comment by Gokuroro** [comment]
@RaptorRCX are  you using a Steam Library folder originally from Windows?

**Comment by RaptorRCX** [comment]
Yep, that's the reason.

**Comment by SomeNowTakenUsername** [comment]
I cant disable it again because steam won't get to the GUI

**Comment by nightsky30** [comment]
Glad I'm not the only one who noticed it updating and seemingly downloading the games again if you disable the re-enable Proton.

**Comment by BigDaddyLinux** [comment]
Having the same issue of constant update loop. 

Steam build date Sep 19 2018, at 19:47:14
KDE Neon 64 bit based on Ubuntu
Opted in beta
System and steam are up to date

Everytime I log into the computer and open up steam, it wants to update in excess of 25 games

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by DenisBY** [comment]
I don't have this issue anymore

**Comment by lucifertdark** [comment]
All clear here as well.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
