### ISSUE TITLE
DOOM steam play mouse does not work

### ISSUE THREAD

**Issue by nimbius** [ValveSoftware/steam-for-linux#5658]
#### Your system information

* Steam client version 2.0.2: 
* Distribution (e.g. Ubuntu): steamos 
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

Issue is being reported here as well for beta client 
https://steamcommunity.com/app/221410/discussions/8/1734336452582696216/

mouse cursor movement does not work in DOOM for steamplay beta test.  mouse moves initially, then on first click mouse freezes.  mouse will only move if scroll button is held, or while l/r button are pressed.

#### Steps for reproducing this issue:

1. load doom
2. move mouse
3. click, then try to move (you cant)

**Comment by kisak-valve** [comment]
Hello @nimbius, issues with games run with Proton are being tracked in [Proton's issue tracker](https://github.com/ValveSoftware/Proton/). The closest issue report to this issue is https://github.com/ValveSoftware/Proton/issues/204.
