### ISSUE TITLE
Proton is installed in last selected library location and can't be moved

### ISSUE THREAD

**Issue by Sanaki** [ValveSoftware/steam-for-linux#5659]
While this doesn't directly cause problems for me, when Proton is installed (by steam) it will install in the last selected steam library, whatever that may be. In my case it installed on my SSD when I would have installed it to my HDD instead, but for some people that may result in an install on a removable drive, NAS, or otherwise disadvantageous location. So far as I can tell, no mechanism currently exists to move proton to another drive (other than I assume manually).

Issue moved from ValveSoftware/Proton#347.

As was pointed out in the prior issue, this also means there's currently no mechanism to force an integrity check on proton.

**Comment by alkel-u3** [comment]
I checked and it is now possible to manage Proton from the "Tools" category in the library, including moving to a different location and checking file integrity. I think it wasn't there a few months ago.

**Comment by kisak-valve** [comment]
Closing per the last comment.
