### ISSUE TITLE
Steam controller Sticks  Y axis are inverted when added as buttons/directionals

### ISSUE THREAD

**Issue by Gokuroro** [ValveSoftware/steam-for-linux#5661]
#### Your system information

* Steam client version (build number or date): Aug 23 2018, at 19:47:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When setting one of the pads/analog stick to Joystick Move, it works as expected for all directions.
When manually adding the Up and Down directions in either Left or Right sticks manually by choosing, for example, "Directional Pad" for Style of Input, the Y axis will be inverted.

#### Steps for reproducing this issue:

1. With a Steam Controller connected, open a new game that uses Left/Right stick (example: Hollow Knight) and access the Controller Settings page through the Big Picture mode's overlay
2. Select either the analog or one of the pads to setup
3. Change the Style of Input to "Directional Pad"
4. For the upper directional, select the Left Stick's Up button (LSUP)
5. For the lower directional, select the Left Stick`s Down button (LSDN)
6. Go back through the menu to the top of the controller setup (so it saves the new configurtion)
7. Go back in game and try clicking Up/Down using the new setup
8. Notice that the up and down buttons are inverted
9. Repeat steps 2-8 for the Right Stick

**Comment by Ruedii** [comment]
There are several Linux joystick Calibration tools that can fix this.

One ships with KDE standard desktop that I use.  There is a command prompt one available as well.

However, There needs to be a calibration utility capable of inverting axis and calibrating the range of axis built into Steam.

**Comment by Gokuroro** [comment]
@Ruedii, both axis work normally when using them as analogs, the only issue is when selecting the up/down/left/right analog stick. I don't think adding an external workaround as a solution (given that I'm using the steam controller out of the box setup, not changing anything in any external application) is the ideal case.
Besides, considering that it works normally in the stick emulation mode, I'd suspect that inverting it in an external application would actually invert it in that other mode as well.

**Comment by kisak-valve** [comment]
Hello @Gokuroro, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
