### ISSUE TITLE
Installing from Ubuntu Software Center: /media is not there.

### ISSUE THREAD

**Issue by Cordoha** [ValveSoftware/steam-for-linux#5665]
### Steam from Ubuntu 18.04 Software Center

When installing Steam from the Ubuntu 18.04 Software Center and trying to enable "Content Libraries" because my libraries are in /media/user/drive, **/media** isn't listed in the folders.

### Installing From Valve Sources
Installing Steam from valve sources, enabling current "Content Libraries" in /media is there. I am able to link my libraries. My games show up and update!

### End Notes
- I'm going to try installing Steam with Synaptic to see if there's any difference.
- Because I've installed from Valve sources, my friend said udev stuff is **not** enabled. I want my controller to work!

**Comment by kisak-valve** [comment]
Hello @Cordoha, since this is an issue with the distro-provided steam package and does not show with the Valve-provided variant, this issue will need to be addressed by Ubuntu's package maintainers for Steam.

**Comment by Cordoha** [comment]
Okay. Whether it Ubuntu devs updated the package, or my system in error, or different source **installing** from Synaptic enabled me to set the options, **/media** was there to set the directory to the different drive.

- *not* setting any options, **clicking** OK, the client wants a restart. Not really an issue, but it is annoying. 

I won't close the issue but since I am able to set the directory now, and it is a non-issue using the Synaptic source for installation. Ubuntu Software Center used "dl.flathub.org" source it seems as well. 

:middle_finger: to Ubuntu Software Center.
I guess I need to stop using it, and stop bantering on, and stick to Synaptic & APT.
Thanks.

**Comment by kisak-valve** [comment]
Oh, if it was the flatpak packaged steam, you may want to mention this over at https://github.com/flathub/com.valvesoftware.Steam, but there's a good chance that folder is intentionally restricted.

**Comment by nanonyme** [comment]
You can expose additional directories to the app through flatpak --user --filesystem=/path com.valvesoftware.Steam. It is mostly safe except for home which is not allowed to be shared because the app does interesting tricks to make Steam Cloud work with all games and this is only safe within a contained sandbox. Also, /etc and /usr cannot be shared.

**Comment by kisak-valve** [comment]
Hello @Cordoha, were you able to resolve your issue here? It appears to be part of the nature of Flatpak and there's nothing for a Valve dev to evaluate.
