### ISSUE TITLE
Proton games without cloud save support lose data when uninstalled

### ISSUE THREAD

**Issue by Steveice10** [ValveSoftware/steam-for-linux#5668]
#### Your system information

* Steam client version (build number or date): **Aug 23 2018, at 19:47:27**
* Distribution (e.g. Ubuntu): **Arch Linux**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
Games running through Proton that store save data within their prefix (e.g. in Application Data) and don't support cloud save end up having their save data deleted when uninstalled, as their prefix is also deleted. On Windows, this would not happen; the save data would still be present on the system and usable after reinstalling later.

The game I personally used to test this was **LEGO Harry Potter: Years 5-7**.

#### Steps for reproducing this issue:

1. Save in a Proton game without cloud save support.
2. Uninstall the game.

**Comment by kisak-valve** [comment]
Hello @Steveice10, this fits better in the Proton issue tracker, so let's track this issue at https://github.com/ValveSoftware/Proton/issues/428.

**Comment by Zero86Sk** [comment]
Can it be it saves the data in a Wine Prefix that it than deletes when you uninstall the game? Cause i've notice it too.
