### ISSUE TITLE
Cannot install steam on Ubuntu 18.10

### ISSUE THREAD

**Issue by koalasbruder** [ValveSoftware/steam-for-linux#5671]
#### Your system information

* Steam client version (build number or date): I don't  know
* Distribution (e.g. Ubuntu): 18.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Cannot install Steam. 
Because Ubuntu removed multiarch support if you don't upgraded from 18.04.1 (with multiarch support enabled) to 18.10.
#### Steps for reproducing this issue:

1. Directly install Ubuntu 18.10 from daily build.
2.  Try to install Steam

**Comment by koalasbruder** [comment]
I changed the language from German to English and now it is working.
I don't know why it was not working before.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Cyan4973** [comment]
I've got exactly the same problem,
using Ubuntu 18.10,
and following the exact sequence of commands proposed above.

But it does not work : 
```
Running Steam on ubuntu 18.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/$user/.local/share/Steam/steam.sh: line 823: /home/$user/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory    
```
