### ISSUE TITLE
Tom Clancy's Splinter Cell: Conviction: Failed to request product key from Steam (appID33220)

### ISSUE THREAD

**Issue by FreigeistZ** [ValveSoftware/steam-for-linux#5672]
#### Your system information

* Steam client version (build number or date): Aug 23 2018, at 19:47:27/1535062307
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed 20180820
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Hello All,

Tom Clancy's Splinter Cell: Conviction with DeLuxe Key bought on Steam on 11/27/2016. 
(appID 33220)
Works on Windows Steam Client on Windows 7 for nearly two years now,

Installed on Linux Steam beta client with Proton enabled today.
When I start the game I only get the following message:

Failed to request product key from Steam, pleast try again in a few minutes.

After that I can only click OK and the game fails to start instead of working correctly.

There are no log files available.

#### Steps for reproducing this issue:

1. Start Steam beta Client on Linux
2. Choose "Tom Clancy's Splinter Cell: Conviction" in library
3. Click "Play"

**Comment by kisak-valve** [comment]
Hello @FreigeistZ, issues with games that use Proton are being tracked in its issue tracker. Let's track this issue at https://github.com/ValveSoftware/Proton/issues/456.

**Comment by FreigeistZ** [comment]
Alright, thanks kisak
