### ISSUE TITLE
Steam Play Not Preventing Monitor Powersave/Screensaver

### ISSUE THREAD

**Issue by cluoma** [ValveSoftware/steam-for-linux#5673]
#### Your system information

* Steam client version: Built: Aug 23, 2018 19:47:27
* Distribution: Linux Mint 18.3 KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Playing games using a gamepad usually prevents screen savers or idle power save features from triggering. This is not the case when playing through Steam Play.

#### Steps for reproducing this issue:

1. Enable some powersave feature such as screen auto turn off after 1 minute.
2. Launch a game through Steam Play (Monster Hunter).
3. Don't touch KB+M, wait 1m or play with gamepad for 1m.

**Comment by kisak-valve** [comment]
Hello @cluoma, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/287. Closing as a duplicate.
