### ISSUE TITLE
Playing Grim Dawn with Steam Play resets all achievements in game

### ISSUE THREAD

**Issue by arzardk** [ValveSoftware/steam-for-linux#5675]
#### Your system information

* Steam client version (build number or date): 1535062307
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I loaded my old save, when i played in Grim Dawn with Steam Play feature and after exit all of my achievements was reset.

#### Steps for reproducing this issue:

1. Start Grim Dawn with Proton 3.7
2. Exit game
3. All your achievements will be reset

I'm not sure is this Steam Play(Proton) bug or Steam for Linux so take a look:
You can see that my playtime is enough to gain at least one achievement.
[My Steam page](https://steamcommunity.com/id/arzardk/)
[Video with bug reproduced](https://youtu.be/PiTvjBxr1sY)

**Comment by kisak-valve** [comment]
Hello @arzardk, this issue is already being tracked at #5643. Closing as a duplicate.
