### ISSUE TITLE
[Feature Request] Support for VA-API on AMD hardware

### ISSUE THREAD

**Issue by Holston5** [ValveSoftware/steam-for-linux#5676]
#### Your system information

* Steam: Aug 23 2018 
* Distribution (e.g. Ubuntu): Solus 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Currently VA-API is not supported for AMD cards using the mesa/amdgpu driver.  This means that hardware video encoding for in-home streaming does not work.  This also affects the Steam Link I purchased, and now can't really use on a Linux host.

Please support hardware video encoding for AMD users under the kernel's amdgpu driver.

**Comment by kisak-valve** [comment]
Hello @Holston5, this issue is already being tracked at #4890. Closing as a duplicate.
