### ISSUE TITLE
Proton: allow adding 3rd-party apps and games

### ISSUE THREAD

**Issue by rkfg** [ValveSoftware/steam-for-linux#5677]
#### Your system information

* Steam client version (build number or date): 1535062307
* Distribution (e.g. Ubuntu): Debian Buster/sid amd64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It would be great to be able to launch other apps and games with Proton from Steam directly. There are many alternative vendor-specific stores around like Battle.NET, Origin, UPlay and such. Unfortunately, some franchises migrate there from Steam and while we have the first episodes on Steam the recent installations are somewhere else. One of such examples is the Mass Effect series, only two parts are on Steam and the third is on Origin. Origin and ME3 work quite well on Wine, I completed it years ago with all DLCs but now it's kind of a hassle to setup the prefix and such. Would be great to be able to "add a non-Steam game" for Windows so that a Proton prefix is created and used automatically. Maybe even an installer support to install the store program itself and run it, all using Steam and Proton.

**Comment by vanyasem** [comment]
Looks like https://github.com/ValveSoftware/Proton/issues/122

**Comment by rkfg** [comment]
Could be but I'm not sure that issue belongs to Proton exclusively. Maybe it's more on the Steam side as already notice there.

**Comment by nstgc** [comment]
I agree that this is more of a Steam Client issue than a Proton issue. There is bound to be overlap, but sometimes things fall more into one than the other.

**Comment by ronlaws86** [comment]
Landed here as I created a duplicate in error, however can we add consideration to mod managers for games too? I know at least in wine that some mod managers need access to a game's reg entries (Uncommon but something to consider) as well as the game files, so a way of adding them to co-exist in the same prefix as the game would be needed, 

example, in the library page of the game, in the same area as the Launch button, add a small text link that says something like "Install/Launch Game Utility" or something similar so a utility like Nexus Mod Manager can be added in a way that associates it with the game. (Unless it matters less in NMM's case in which case just add it as a regular non-steam game/application)

**Comment by rkfg** [comment]
This is a great proposition! I read about the ALOT project for Mass Effect 2 that replaces the game textures with quite high res ones, it was not that easy to apply but I succeeded in the end (had to fork and fix the C# program that applies the patch so that it could be run on Wine+Mono). I created a new prefix for that utility but would love to reuse the original game's one. The utility also fixes the game LOD settings that are located in the user's home directory so I had to manually merge that config with the actual one in the Proton prefix.

**Comment by matheusfillipe** [comment]
We totally need this! I've been always trying to get some autodesk products Like autocad and Revit with wine, and proton seems to be the tool that will get this finally working!

**Comment by kisak-valve** [comment]
Closing as implemented in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update.

**Comment by stsp** [comment]
How to use this feature?
Say, I unpacked some windows game.
Then in Steam I am trying to add it as a
third-party game, but steam expects the
`.desktop` file in the "Browse" dialog. And
the games I copy, have no any `.desktop`
files. Forcibly pointing steam to an EXE
file doesn't seem to work.
So how to add the games?
Is there any instruction?

**Comment by jarrard** [comment]
When you goto browse to select the EXE file, change it from desktop to All files down bottom drop down list. 

Keep in mind there is a bug with adding non steam exe's this way and it will create a broken shortcut which you need to go into and select the target exe again, then remove the crap from launch options area.

**Comment by stsp** [comment]
Yes, I figured I could force the EXE open,
it just doesn't help:
![Снимок экрана от 2019-05-23 15-16-39](https://user-images.githubusercontent.com/3295627/58252055-dd58c380-7d6d-11e9-977a-9550348404a8.png)

All seems correct?

**Comment by stsp** [comment]
![Снимок экрана от 2019-05-23 15-18-14](https://user-images.githubusercontent.com/3295627/58252112-024d3680-7d6e-11e9-9b67-246d66b77441.png)

**Comment by stsp** [comment]
Hmm, it just seems that the problem was in
the way I was launching it: I was doing a right
click and in pop-up menu select "Launch".
This didn't work with the EXE. But occasionally
I double-clicked on it instead, and it launched. :)

**Comment by stsp** [comment]
It may be a bug in fact, because Right-click+Launch
works for all other games, but not for the EXE short-cut.

**Comment by jarrard** [comment]
yeah wouldn't surprise me, I typically press the play button just to be sure.

**Comment by reavertm** [comment]
There seems to be a bug in Steam launcher for non-steam games run via Proton. Steam doesn't seem to run proton inside Steam runtime.
Or.. it might attempt to run, but no Steam runtime libs are in LD_LIBRARY_PATH. At least that's what 'run' (game runner script that is exported when you enable PROTON_DUMP_DEBUG_COMMANDS=1) shows:

`LD_LIBRARY_PATH="/home/maciek/.local/share/Steam/SteamApps/common/Proton 4.11/dist/lib64/:/home/maciek/.local/share/Steam/SteamApps/common/Proton 4.11/dist/lib/::"`

but for successful library path propagation from steam-runtime's run.sh, it should have been:

`LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/maciek/.local/share/Steam/SteamApps/common/Proton 4.11/dist/lib64/:/home/maciek/.local/share/Steam/SteamApps/common/Proton 4.11/dist/lib/::"`

And indeed, once I fix 'run' to append, not replace LD_LIBRARY_PATH, and manually call 'run' via steam-runtime's run.sh, it works. At least I was able to successfully install StarCraft remastered. (not trying to run it, just having some issues with steam appId).

**Comment by jarrard** [comment]
Looks like something that should be fixed ASAP!

**Comment by kisak-valve** [comment]
Hello @reavertm, please open a new issue report.

**Comment by reavertm** [comment]
#6475 created.

**Comment by nstgc** [comment]
I wasn't aware you could use Steam's proton in this way. I've looked for guides, failed to find any information whatsoever and deduced it can't be done yet. Could someone link to relevant information?
