### ISSUE TITLE
Switch Pro Controller recognised but not working

### ISSUE THREAD

**Issue by dindon-sournois** [ValveSoftware/steam-for-linux#5678]
#### Your system information

* Steam client version (build number or date): 1535062307
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I plug-in the controller via USB, it seems to be detected as shown in the [log output](https://gist.github.com/dindon-sournois/e220283aceb084a8b6663fa1031e7264). However, it does not work in Steam Big Picture mode or in any game.

Some additional information : 
- I'm using the distro-provided steam package. 
- There is no steam-devices package but I found /usr/lib/udev/rules.d/70-steam-controller.rules which contains an udev rule for the Switch Pro Controller.
- Dual Shock 4 controller and Steam controller work.
- The Switch Pro Controller inputs are not detected by the jstest-gtk tool

#### Steps for reproducing this issue:

1. start steam-runtime
2. plug-in Switch Pro Controller via USB
3. try to use the controller in Steam Big Picture mode

**Comment by yaomtc** [comment]
I'm also unable to get the Switch Pro Controller working. I don't have any Bluetooth capability on this computer, so I've had to try using USB, but no matter what I do, Steam won't recognize it. I've tried two different udev rules, I've tried installing steam-devices, I've tried disconnecting it from the Switch to avoid accidentally turning the Switch on, I've tried different USB ports... nothing works.

* Steam client version (build number or date): August 29 2018, package version 1535576546
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1 (64 bit)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

**Comment by yaomtc** [comment]
@dindon-sournois, where did you get the log from?

**Comment by dindon-sournois** [comment]
@yaomtc You can get them by starting steam in a terminal or in the file /tmp/dumps/$USER_stdout.txt

**Comment by yaomtc** [comment]
```
Local Device Found
  type: 057e 2009
  path: 0003:0010:00
  serial_number:  - 0
  Manufacturer: 
  Product:      
  Release:      200
  Interface:    0

Unable to open local device: 0003:0010:00
```
[60-steam-input.rules.txt](https://github.com/ValveSoftware/steam-for-linux/files/2342587/60-steam-input.rules.txt)

**Comment by yaomtc** [comment]
It now works for me in Ubuntu. Not Solus, though... will have to figure out why.

**Comment by yaomtc** [comment]
Having fixed the rules in Solus it now works there too!

**Comment by dindon-sournois** [comment]
@yaomtc Could you detail what you did or dump your rules file?

**Comment by yaomtc** [comment]
I made sure there were no duplicate rules anywhere (like the old 99-steam-controller) and that `/lib/udev/rules.d/60-steam-input.rules` contained the following:
```
# Nintendo Switch Pro Controller over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009", MODE="0666"

# Nintendo Switch Pro Controller over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*057E:2009*", MODE="0666"
```
Since you're on Arch rather than Ubuntu the file location may differ. (Like on Solus, it's /usr/lib64/, with a symlink pointing to it at /usr/lib/)

**Comment by darkpumpkins** [comment]
Here the NS pro controller is detected in steam but not into the games. I'm using ubuntu 19.10 ( the problem already was present into 18.10 ), I updated my rules for adding Nintendo Switch pro controller but nothing to do, dead cells or rogue legacy both native games does not see the controller ...

**Comment by kisak-valve** [comment]
Hello @dindon-sournois, @darkpumpkins, are either of you still experiencing this issue on an up to date system?

**Comment by dindon-sournois** [comment]
Hi @kisak-valve, it seems to be working on up to date system.

**Comment by darkpumpkins** [comment]
Sorry for the wait.
I tried some native :
- Dead cells
- Rogue Legacy
- Salt and sanctuary

and some with steam play proton : 
- Dark sous III
- Killer Instinct 
- Street fighter V
- Metal gear Solid the phantom pain

The only where my Nintendo Switch pro controller isn't detected is Dead Cells ... the gamepad seems to be detected as a keyboard :/
I think that is a game specific behaviour so the situation is a pretty good.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
