### ISSUE TITLE
Library issues on QubesOS/Fedora28

### ISSUE THREAD

**Issue by MixedMatched** [ValveSoftware/steam-for-linux#5680]
#### Your system information

steam-test (the Qube)                  
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 4GiB
     *-cpu
          product: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
  *-network
       description: Ethernet interface
       physical id: 1
       logical name: eth0
       serial: 00:16:3e:5e:6c:00
       capabilities: ethernet physical
       configuration: broadcast=yes driver=vif ip=10.137.0.15 link=yes multicast=yes

* Steam client version (build number or date): I'm not entirely sure, because I can't actually get steam to run through the command or to launch to a real application, but it should be the latest version as of August 25.
* Distribution (e.g. Ubuntu): Fedora 28 (Qube of Fedora 28 on QubesOS R4)
* Opted into Steam client beta?: [Yes/**No**]
* Have you checked for system updates?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
 I installed steam and it launched correctly after I installed it, but it needed to update and the Qube didn't have enough space, so I shut down the Qube and increased the personal storage. When I started the Qube back up, Steam no longer launched from its bash command. Not that much of an issue because I can just run steam.sh. The real problem was that it required dependicies that it hadn't required before. First it just gave: `Error: You are missing the following 32-bit libraries, and Steam may not run: libc.so.6` I installed glibc and upgraded related software. After I tried launching steam again and this time it gave this: `Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1 libstdc++.so.6 libstdc++.so.6 libstdc++.so.6 libstdc++.so.6 libstdc++.so.6 libstdc++.so.6 libstdc++.so.6 libdrm.so.2 libnsl.so.1
/home/user/.steam/steam/ubuntu12_32/steam: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS64` I was able to install all of those except for libstdc++.so.6 because of a dnf conflict with libstdcxx. I cannot uninstall that and replace it with the correct library because if I uninstall it, it removes basically everything from the whole Qube.

#### Steps for reproducing this issue:

1. Install the Fedora 28 template for QubesOS with the command: sudo qubes-dom0-update qubes-template-fedora-28
2. Create a new Qube with the template
3. Open the terminal and run `su -c 'dnf -y install xorg-x11-drv-nouveau mesa-libGL.i686 mesa-dri-drivers.i686'` (for nvidia hardware only)
4. Run `sudo dnf -y remove rpmfusion-nonfree-release-28.noarch.rpm rpmfusion free-release-28.noarch.rpm`
5. Run `su -c 'dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'`
6. Run `su -c 'dnf -y update'`
7. Run `su -c 'dnf -y install steam'`
8. Shutdown the Qube and increase the space
9. Power the Qube back on
10. Navigate to ~/.steam/steam/
11. Try running steam (It should give missing libc.so.6 error)
12. Run `sudo dnf install libc.so.6`
13. Try running steam again (it should give another missing, but this time with different libraries)
14. Run `sudo dnf install libGL.so.1 libdrm.so.2 libnsl.so.1`
15. Trying to run steam will still give libstdc++.so.6 missing error and you cannot install it without getting a conflict error in dnf between it and libstdcxx. You cannot uninstall libstdcxx without uninstalling a ton of stuff so you're basically stuck in library limbo.

**Comment by MixedMatched** [comment]
I am using the Distro provided RPM, by the way.

**Comment by kisak-valve** [comment]
Hello @MixedMatched, does `steam --reset` work? If not, move/remove `~/.local/share/Steam` and run `steam`.

**Comment by kisak-valve** [comment]
Hello @MixedMatched, are you still experiencing this issue on an up to date system? If not, can you check if you have the `glibc.i686` package installed?

**Comment by kisak-valve** [comment]
Closing pending feedback.
