### ISSUE TITLE
Proton: Mirror's edge disables cursor in steam overlay

### ISSUE THREAD

**Issue by TomJansen** [ValveSoftware/steam-for-linux#5681]
#### Your system information

* Steam client version (build number or date): Aug 23 2018 at 19:47:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Running and playing Mirror's Edge with Proton works fine. However, when you enable the Steam Overlay, the cursor does not show up. You can click stuff but it is just that the cursor icon is gone. The in-game cursor works fine however.

#### Steps for reproducing this issue:

1. Run Mirror's Edge with Proton
2. Access the Steam Overlay

**Comment by kisak-valve** [comment]
Hello @TomJansen, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/168. Closing as a duplicate.
