### ISSUE TITLE
downloading fails when SteamApps/{downloading,common} are on different filesystems

### ISSUE THREAD

**Issue by pal666** [ValveSoftware/steam-for-linux#5682]
#### Your system information

* Steam client version (build number or date): current beta aug 23, but i'm sure it's not new issue
* Distribution (e.g. Ubuntu): fedora 28
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
i have `downloading` and `common` on different filesystems (i didn't check but my guess is what matters is different mount points, so it can't move files and has to fall back to copying). when i download game it is downloaded to `downloading`, then i press play and it starts copying to `common`. and then it says `file xxx is locked`, and deletes copied data from `common`. it happens with more than one game and file is always larger than 2g and my guess is it is first file larger than 2g. do you use signed integers somewhere? i have obvious workaround but you better fix it.

#### Steps for reproducing this issue:
1. symlink `steamapps/common` to different mount point
2. download and try to start `dying light` or `total war: attila` or any game which has file larger than 2g (what is important is that in the beginning game is missing from your library)

**Comment by Vash63** [comment]
I have no idea why it put `downloading` and `common` on different mounts, it did this for me too. Either way the new Steam Client Beta fixed the 2G issue for me so the game that was failing on me (AC Odyssey) went though with no problem.

**Comment by kisak-valve** [comment]
Hello @pal666, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
