### ISSUE TITLE
Doom crashes immediately

### ISSUE THREAD

**Issue by cobbleking** [ValveSoftware/steam-for-linux#5683]
#### R5 1600, RX 480, 24 GB DDR4

* Steam client version (build number or date): August 23, 2018
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I tried to launch DOOM, but instead of launching the game as expected, it immediately crashes with [this](https://gist.github.com/cobbleking/f3af49d74ca84c44c7de73a7dfba1884) error message. Changing APIs desn't help, restarting Steam and my PC don't help, reinstalling drivers doesn't help, even changing distros entirely did nothing.

#### Steps for reproducing this issue:

1. Launch Doom using Steam Play on Linux
2. Watch as it crashes

**Comment by cobbleking** [comment]
Sorry if this isn't the right place to post this, but Steam Support directed me here and i couldn't find a working solution through extensive Google-fu.

**Comment by kisak-valve** [comment]
Hello @cobbleking, search for [wglCreateContextAttribsARB](https://github.com/ValveSoftware/Proton/search?q=wglCreateContextAttribsARB&type=Issues) or [379720](https://github.com/ValveSoftware/Proton/search?q=379720&unscoped_q=379720&type=Issues) in the Proton issue tracker. The short version is that mesa 18.2 preferably with llvm 7+ is needed for Doom / OpenGL. You may also get it going with the Vulkan backend by adding `+r_renderAPI 1` to the game's launch options.

Closing as there are several issue reports on this in the Proton issue tracker.
