### ISSUE TITLE
[Feature Request] Allow way to run non-steam 'games'/applications through proton. eg NMM

### ISSUE THREAD

**Issue by ronlaws86** [ValveSoftware/steam-for-linux#5685]
https://www.reddit.com/r/Steam/comments/99fjzw/steam_proton_for_non_steam_applications/

This reddit covers what we are trying to achieve, however a native, user friendly way of doing this would be preferable. 

So for example, on each steam game listed to launch via proton, add a button/text that says something like "Run utility for this game" or something similar to how POL does it, so that you can say install/run a mod manager and it can find the game files and any registry entries in need of patching/modding.

**Comment by kisak-valve** [comment]
Hello @ronlaws86, this feature request is already being tracked at #5677. Closing as a duplicate.
