### ISSUE TITLE
Feature request: Symlink Proton home directories to the user's actual home directory

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/steam-for-linux#5688]
I could have sworn this was already a feature request, but I did a search both here and on the Proton tracker.

Pretty much, the issue is that saved games get deleted when you delete the prefix (such as on uninstall). Another thing is different games in a series (Mass Effect 1 ==> 2) can't see each other's saves for continuing. Players may also have save data or configurations already present from having played with their system wine or CrossOver. In any case, there are a number of reasons why this is useful, and so I'm requesting it.

**Comment by OvermindDL1** [comment]
Or at least symlink the home directories to some special directory that the user can easily access as well.

**Comment by kisak-valve** [comment]
Hello @nstgc, the functional problem this is trying to solve is at https://github.com/ValveSoftware/Proton/issues/428. Closing in favor of it.
