### ISSUE TITLE
Skyrim not running on SteamPlay in Manjaro KDE

### ISSUE THREAD

**Issue by lil5** [ValveSoftware/steam-for-linux#5689]
#### Your system information

* Steam client version (build number or date): API v018, 1535062307
* Distribution (e.g. Ubuntu): Manjaro KDE Linux 4.14.65
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Game launched via compatibility tool Steam Play

- Clicked play
- Didn't start game

The err.log file is from the terminal that I started steam from (same issue if I start steam normally).

File: [err.log](https://gist.github.com/lil5/bdfacb9e0b0076c5723cc468f3dbf5d5)

#### Steps for reproducing this issue:

1. run manjaro https://manjaro.org/get-manjaro/
2. install steam
3. download skyrim
4. run
5. fail on load

**Comment by kisak-valve** [comment]
Hello @lil5, issues with games run with proton should be reported in the proton issue tracker, additionally 
we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/460#issuecomment-416275294.

**Comment by lil5** [comment]
@kisak-valve Cheers :+1: 

I Had originally sent an issue to Steam Support but because I run Manjaro they sent me to this link https://github.com/ValveSoftware
To remove confusion it might be better to in the future send Issuers of SteamPlay to https://github.com/ValveSoftware/Proton
