### ISSUE TITLE
Superbrothers Sword & Sworcery segfaults at start

### ISSUE THREAD

**Issue by monreal** [ValveSoftware/steam-for-linux#569]
On Fedora 18 (64 Bit with 32 Bit libs, all other Steam games work), Superbrothers: Sword & Sworcery EP segfaults at startup:

Game update: AppID 204060 "Superbrothers: Sword & Sworcery EP", ProcID 2811, IP 0.0.0.0:0
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully
Setting breakpad minidump AppID = 204060
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198024959991 [API loaded no]
/run/media/mimox/usb3/steam/Steam/SteamApps/common/Superbrothers Sword & Sworcery EP/run.sh: line 17:  2814 Segmentation fault      ./swordandsworcery_pc
Game removed: AppID 204060 "Superbrothers: Sword & Sworcery EP", ProcID 2814 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by forivall** [comment]
I solved this issue for myself (on arch (really manjaro)) by copying the files from the humble bundle tar.gz into the steam install directory. https://github.com/ValveSoftware/steam-for-linux/issues/439#issuecomment-11862232
