### ISSUE TITLE
Rumble doesn't work when using Xboxdrv

### ISSUE THREAD

**Issue by Vthyarilops** [ValveSoftware/steam-for-linux#5691]
#### Your system information

* Steam client version (build number or date): August 23 2018 19:47:27
* Distribution (e.g. Ubuntu): Mint 18.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Basically a duplicate of this issue https://github.com/ValveSoftware/steam-for-linux/issues/2578

When using DS3 controller with xboxdrv Rumble does not function, outside of steam rumble functions fine with xboxdrv. I would use xpad but the mapping is completely messed up using a DS3, I use the command

     xboxdrv --detach-kernel-driver --mimic-xpad --silent

#### Steps for reproducing this issue:

1.  Get a controller
2.  Load xboxdrv
3.  .....there ya go, no rumble support

**Comment by Vthyarilops** [comment]
Well I did a bit of further testing and it seems that if I add the --force-feedback option certain games will function with rumble, the only one I could find that worked in Steam was Brutal Legend. ROTR, Shadow of Mordor, or any other game I attempt to test rumble does not function.

**Comment by Vthyarilops** [comment]
I tested further, and somehow Rumble is not working at all with xboxdrv even outside of steam, the only change in the system was updating to the Steam beta with Proton. Before hand rumble was working with Crash N Sane Trilogy, and many other games I had in Playonlinux with "xboxdrv --mimic-xpad --detach-kernel-driver --silent" now nothing works (I even downgraded Wine-staging to 3.11 to test again, no luck) if I run fftest /dev/input/event20 It shows that rumble functions without xboxdrv or with xboxdrv --force-feedback, yet it doesn't work (I am in the input group and have evdev rules to allow xboxdrv to run as non root user) without the --force-feedback it shows no rumble support even though it used to function totally fine.

**Comment by kisak-valve** [comment]
Hello @Vthyarilops, are you still experiencing this issue on an up to date system?

**Comment by Vthyarilops** [comment]
@kisak-valve I don't use xboxdrv with DS3 anymore so I can't confirm if it still happens, though I can confirm that --force-feedback is still required with fftest to use rumble. Sorry

**Comment by kisak-valve** [comment]
That's okay, thanks for the feedback. Closing because there's no longer a test case. This issue was possibly a variation of #4338.
