### ISSUE TITLE
Include proton version in system information

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#5694]
#### Your system information

* Steam client version (build number or date): Aug 27 2018 19:03:23
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Include proton version in system information

**Comment by kisak-valve** [comment]
Looks like having a Proton version in the System Information doesn't make sense. We need to know it on a per-game basis when troubleshooting, not installation-wide.
