### ISSUE TITLE
Battletech showing as a Linux games

### ISSUE THREAD

**Issue by nstgc** [ValveSoftware/steam-for-linux#5696]
Before I begin, I'd like to explicitly state that this is NOT related to the request to override existing Linux ports since one doesn't exist for this game, and it appears others have been able to play this with Steam Play.

# Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Aug 27 2018
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

# Please describe your issue in as much detail as possible:

### What I expect

I expect to see Battletech displayed with a "Runs on this compuuter via Steam Play" note. I expect the install size to be in the GBs

### What I got

There is no indication that it would be run with Proton. Furthermore when I try to install it there is a 15MB download without any executables (which Steam informs me of upon attempting to launch)

### Why I think this is abnormal

I haven't thought anything of this up until now. The game is suppose to be ported to Linux eventually, so even though on the store page it doesn't list Linux support I thought that it was a play holder. However, in the official support list I saw Battletech, which implies that it was installed and run with Steam Play.

# Steps for reproducing this issue:

1. Launch Linux Steam 
2. Find Battletech
3. See that it isn't shown to use Steam Play
4. (optional) Install the game.
5. (optional) See that it installs about 15MB of nothing useful without Steam Play.

**Comment by kisak-valve** [comment]
Hello @nstgc, a quick glance at https://steamdb.info/app/637090/ indicates this game has a linux depot and launch config. It's likely they are testing in a beta branch.

Closing as this is not an actionable bug.

**Comment by nstgc** [comment]
@kisak-valve If that is the case, how is it that there is a Battletech entry on the compatibility page? https://github.com/ValveSoftware/Proton/wiki/Completely-Stable

This has been an on going issue for months, which I have simply ignored.
