### ISSUE TITLE
Can't switch to Steam Beta

### ISSUE THREAD

**Issue by justeff** [ValveSoftware/steam-for-linux#5697]
#### Your system information

* Steam client version (build number or date): June 8, 2018
* Distribution (e.g. Ubuntu): Manjaro 4.17.18-1
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes, newest Manjaro packages

#### Please describe your issue in as much detail as possible:
Can't switch to the beta client. The first time when I try to switch, a new client seems to get downloaded but Steam doesn't get updated, it still restarts with the stable built. I already tried to delete Steam through the package manager and ~/.steam but with no luck.

#### Steps for reproducing this issue:
1. Changed: Steam Settings -> Account -> Change -> "NONE" to "Steam Beta Update"
2. Restarted Steam
3. Steam Settings -> Account says: "Steam Beta Update", but Steam Play is not listed and "About Steam" says: Built: June 8, 2018.

**Comment by kisak-valve** [comment]
Hello @justeff, if you want to try a soft reset of steam, that's `steam --reset` in a terminal, and if that doesn't work, you can move `~/.local/share/Steam` and ~/.steam somewhere out of the way and let steam re-bootstrap.

Afterwards, with steam not running, you can move the steamapps folder into the newer steam install to save time redownloading games.

**Comment by JackRyder** [comment]
I had this issue with my Ubuntu 18.04, completely uninstalling and reinstalling seemed to fix the issue. This includes purging the packages :)

**Comment by justeff** [comment]
Wow, Steam looks different now haha. `steam --reset` broke it, I got a _Fatal Error: Failed to load steamui.so_ message. That's why I deleted the directories, now it's working :)

**Comment by kisak-valve** [comment]
Closing per the last comment. Can't troubleshoot deleted directories.
