### ISSUE TITLE
Steam controller Desktop configuration not loaded after controller power off and on again

### ISSUE THREAD

**Issue by Gokuroro** [ValveSoftware/steam-for-linux#5698]
#### Your system information

* Steam client version (build number or date): 1535402532
* Distribution (e.g. Ubuntu): Arch Linux
* Window Manager used: i3-wm
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When first powering on the Steam controller, after a Steam start, the controller will correctly enable the Desktop configuration. When the controller is powered off (timed out, for example) and on again, it stay in the keyboard+mouse mode until the user opens the Desktop Configuration screen again.
Expected that, after turning the Steam controller off and on again with the Steam client open (minimized to tray or not), the controller is recognized as connected, that it is in desktop mode (no game running) and the desktop configuration is loaded.

#### Steps for reproducing this issue:

1. Start steam (desktop mode);
2. Leave steam in the tray icon (or at least not focused);
3. Power the Steam Controller on for the first time (Bluetooth mode used for this example);
4. Notice that it works as per Desktop configuration (e.g. left pad as scroll when using a circle motion);
5. Turn the Steam Controller off (Steam button + Y);
6. Turn the Steam Controller back on;
7. Notice that the Desktop configuration is not selected (e.g. left pad does not scroll when using the circle motion anymore);
8. Open the Steam > Settings > Controller menu;
9. Click on the "Desktop Configuration" button and close the window afterwards;
10. Notice that now the desktop configuration is loaded again.

Bonus: randomly, clicking on one of the controller settings buttons (Guide Button Chord Configuration, for example), will just power off the Steam Controller.

**Comment by kisak-valve** [comment]
Hello @Gokuroro, are you still experiencing this issue on an up to date system?

**Comment by Gokuroro** [comment]
Hi @kisak-valve, it's been some time since I last used my Steam Controller. I cannot answer that. If it is dependent on my return, we probably should close this.

**Comment by kisak-valve** [comment]
Closing per the last comment.
