### ISSUE TITLE
Steam - Steam Big Picture Mode will not use primary monitor

### ISSUE THREAD

**Issue by CarlB86** [ValveSoftware/steam-for-linux#5700]
#### Your system information
*Steam client version: Aug 23 2018, 19:47:27
*Distribution: Antergos 18.8
*Opted into Steam client beta?: Yes    
*Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have three monitors, all 1080p. When launching big picture mode it is ignoring my preference for primary monitor in the desktop environment deepin and also the /etc/X11/xorg.conf file. It displays on a secondary monitor. This makes it impossible to browse big picture mode when using the steam link or steam link application.

#### Steps for reproducing this issue:
1.  Launch big picture mode from PC or from Steam Link
2.  Primary monitor will display on steam link, but big picture mode will not be visible as it is on a different monitor.

**Comment by kisak-valve** [comment]
Hello @CarlB86, this issue is already being tracked at #3520 / #4178. Closing as a duplicate.
