### ISSUE TITLE
No "voice" option under steam settings making it impossible to change input device for some source games. 

### ISSUE THREAD

**Issue by u83rmensch** [ValveSoftware/steam-for-linux#5701]
#### Your system information

* Steam client version  
 -built aug 28 2918
 -Steam API: v018
 -steam package version: 1535494643
 -current beta as of 8/28/2018

* Distribution (e.g. Ubuntu): 
 -Ubuntu 18.04.1 LTS
* Opted into Steam client beta?: [Yes/No]
 -yes
* Have you checked for system updates?: [Yes/No]
 -yes

#### Please describe your issue in as much detail as possible:

Steam voice options for native source games are not fully accessible and selecting the correct device to use is impossible. This example uses Dota 2 as its really the only source game I play right now. 

#### Steps for reproducing this issue:

1. Open Dota 2  > settings (gear icon) > audio tab. 
2. See the link for "Recording device settings are configured using Steam voice settings", you click the link and the steam overlay will open showing the old steam UI settings for in-game voice settings. 
3. notice the input device is set to just "pulse audio" rather than the device you need it to be on, in my case a steel series headset. 
4. the "change device" button is not available to click
5. "detect device" button does nothing to change the input device
6. remember that you cant do this while the game is running and proceed to close dota 2 so you can change this out of game
7. go back to steam > settings
8. notice that since the UI update the "in-game voice" options does not seem to be in this menu any more, maybe they're in the new chat menu setttings?
9. check the new steam UI friends list chat option. 
10. find that an option to change your input device exists here but upon testing realize that it does absolutely nothing for the game. 

can we please get the steam voice settings back in the steam menu its self please? at least until you find a way to get the voice chat from the new ui to carry over.. or better yet not make your games rely on the client for their audio input, that would be even better.

**Comment by kisak-valve** [comment]
Hello @u83rmensch, this reads like #5617. Feel free to add this to the existing issue report.

Closing as a duplicate.
