### ISSUE TITLE
Steam swrast Failed To Load

### ISSUE THREAD

**Issue by gudenau** [ValveSoftware/steam-for-linux#5706]
#### Your system information

* Steam client version (build number or date): 1.0.0.56 according to the deb
* Distribution (e.g. Ubuntu): Debian x64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Can't get that far

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam should launch, but instead it waits forever after a driver failed to load.

```
gudenau@DESKTOP-DEBIAN:~/Downloads$ sudo dpkg -i steam_latest\(1\).deb 
Selecting previously unselected package steam-launcher.
(Reading database ... 218298 files and directories currently installed.)
Preparing to unpack steam_latest(1).deb ...
Unpacking steam-launcher (1.0.0.56) ...
Setting up steam-launcher (1.0.0.56) ...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
gudenau@DESKTOP-DEBIAN:~/Downloads$ steam
Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1533766730)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
^C
gudenau@DESKTOP-DEBIAN:~/Downloads$
```

#### Steps for reproducing this issue:

1. Install steam
2. Run steam

**Comment by kisak-valve** [comment]
Hello @gudenau, swrast is mesa's slower software renderer. Since steam is trying to use it, that usually indicates your 32 bit opengl driver is missing or broken.

Does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work on your system?
What video card and driver version do you have?

**Comment by gudenau** [comment]
If I try to install `mesa-utils:i386` or any related 32 bit package it wants to uninstall the corresponding 64 bit versions.

I am using a GTX 960 and version 384.130-1 of `nvidia-driver`.

**Comment by kisak-valve** [comment]
Check if you have the `nvidia-driver-libs-i386` package.

**Comment by gudenau** [comment]
THANK YOU

You are the first person to even come up with that and I could not find that in any of the searching I found. Steam works for me now.
