### ISSUE TITLE
CS:GO nost starting anymore

### ISSUE THREAD

**Issue by pcdoc2000** [ValveSoftware/steam-for-linux#5708]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu):  Xubuntu 16.04.5 ( Kernel 4.15.0.33)
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* HW: GTX 1050 TI (Driver: 384.130); Intel I5 6600K: Chipset: Z170 
#### Please describe your issue in as much detail as possible:

When starting Counter Strike Global Offensive screen turns black for about 3-5 seconds and the the process terminates without an error message.

Starting it with the options:
    -safe
    -novid
    -autoconfig
doesn´t help! Same behaviour. 

Reinstalling the game didn´t solve the issue either.

The game worked for multiple months fine and this problem highly likely came with the last update.

Workaround: Using the start option -legacyscaleformui makes the game start and run fine.

#### Steps for reproducing this issue:

1. Starting the game with or without starting the Steam client before

**Comment by kisak-valve** [comment]
Hello @pcdoc2000, CS:GO issues are tracked in the csgo-osx-linux issue tracker, so let's track this at https://github.com/ValveSoftware/csgo-osx-linux/issues/1802.
