### ISSUE TITLE
a lot of Steamplay games updates queued and they don't autoupdate

### ISSUE THREAD

**Issue by legluondunet** [ValveSoftware/steam-for-linux#5709]
Hello,
Each time I open Steam, I have a lot of Steamplay games updates queued and they don't autoupdate at Steam launch, I have to manually launch them.
Is it a bug?

![capture d ecran de 2018-08-30 19-51-21](https://user-images.githubusercontent.com/325405/44871683-d1831980-ac93-11e8-98c2-9e4e466ab51a.png)

Thank you for your help.

**Comment by kisak-valve** [comment]
Hello @legluondunet, Steam not auto-starting all game updates when the steam client starts appears to be the intended behavior.

**Comment by Leeo97one** [comment]
I do not think this is normal. I also have most of my Steam Play / Proton games that are added to the update queue for some reason **every time** I start or restart the Steam client.
![image](https://user-images.githubusercontent.com/1344241/50246720-60987680-03d6-11e9-825c-54f8d562f133.png)

**Comment by kisak-valve** [comment]
Hello @Leeo97one, you're looking for #5644, not this issue.

**Comment by Leeo97one** [comment]
Oh OK, thanks and sorry!
