### ISSUE TITLE
DS4 not working in Shadow Tactics: Blades of the Shogun (418240)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5710]
#### Your system information

* Steam client version (build number or date): Aug 29 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Under Windows 10 the game has native support for DS4 controllers that works but doesn't under my linux distro. It detects it as an unknown wireless controller with no inputs from it working.

#### Steps for reproducing this issue:

1. Load game with DS4
2. Try to use DS4

**Comment by kisak-valve** [comment]
Hello @daasuharo, issues with games run with Proton are being tracked in Proton's issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/1030.

**Comment by daasuharo** [comment]
It's a native linux port; no Proton.

**Comment by kisak-valve** [comment]
Trying this again, hello @daasuharo, this should be also be brought to the game dev's attention.

**Comment by daasuharo** [comment]
Okay, I sent out an email to them. I can add responses from them here if you want.

**Comment by kisak-valve** [comment]
Closing because this is an issue with a third party game and the reporting user has turned into a ghost.
