### ISSUE TITLE
enabling steamplay for all titles shows osx duplicates (gta:vc and sa)

### ISSUE THREAD

**Issue by Ae3NerdGod** [ValveSoftware/steam-for-linux#5711]
#### Your system information

* Steam client version (build number or date): aug 2018 at 20:07:05
* Distribution (e.g. Ubuntu): Linux Mint 19 cinnamon
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] yes, Up to date

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
when enabling steamplay for all titles , GTA: Vice City and GTA: San Andreas duplicate and i believe one is the OSX version and one is the Windows version
for example Vice City. if i click "store page" on one it goes to https://store.steampowered.com/app/12110/
if i go to the other one and do the same thing it leads to https://store.steampowered.com/app/12240/

#### Steps for reproducing this issue:

1. enable steamplay for all titles via settings
2. observe duplicates of GTA vice city and san andreas (or more osx titles with their own appid?)

**Comment by kisak-valve** [comment]
Hello @Ae3NerdGod, this issue is already being tracked at #3406. Closing as a duplicate.
