### ISSUE TITLE
Plugging in a USB network adapter causes steam client to crash

### ISSUE THREAD

**Issue by PhonicUK** [ValveSoftware/steam-for-linux#5713]
#### Your system information

* Steam client version (build number or date): Aug 29 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Not much to it. If I plug in a USB ethernet adapter while steam is running, it'll die.
dmesg shows as follows: https://gist.github.com/PhonicUK/7b634b08ec553f63837c8bfa4ddeeb80

Kernel version 4.18.5 build date Aug 24 2018, Specific hardware is a 13" HP Envy x360 Ryzen 7. 

If the adapter is already plugged in before starting the steam client it behaves fine, and unplugging it while it's running doesn't cause a crash.

#### Steps for reproducing this issue:

1. Start steam client
2. Plug in a USB network adapter
3. Steam is no longer running

**Comment by kisak-valve** [comment]
Hello @PhonicUK, are you still experiencing this issue on an up to date system?

**Comment by PhonicUK** [comment]
Hey @kisak-valve - I can confirm that this behaviour has been fixed and no longer occurs on the latest release.

Tested against Jan 5, 2021 build on Ubuntu 20.04 LTS, fully updated.

Issue closed with thanks :)
