### ISSUE TITLE
Changing proton version forces all win games to update

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#5715]
#### Your system information

* Steam client version (build number or date): Aug 30 2018, at 21:12:26
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Sysinfo: https://gist.github.com/XakepSDK/267aa9a948565d5c21056cab6efff1a5

Changing proton version from 3.7-3 to 3.7-5 Beta forces all win games to be updated.
Some of them just instantly 'finished' downloading, some of them re-downloading content.

**Comment by megatog615** [comment]
It looks some data is downloaded for one of the games and the rest download nothing. I think this is Steam downloading the appropriate Proton files and not having a way to properly show that.

**Comment by douglasg14b** [comment]
For me, some games download in their entirety after changing the proton version....

Given my slow internet this can take actual days to complete.

**Comment by kisak-valve** [comment]
Closing in favor of #5761.
