### ISSUE TITLE
Steam Client won't continue downloading in KDE Plasma Lockscreen State

### ISSUE THREAD

**Issue by ccxex29** [ValveSoftware/steam-for-linux#5720]
#### Your system information

* Steam client version (build number or date):  1535768746
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam Game Download is stopped whenever i leave my PC. In comparison, Blizzard App running on wine keeps downloading my game.
I suspect either the lockscreen or screen energy saving is the cause. However, it's more likely that it's from the lockscreen as screen energy saving should do nothing more than turning off the monitor/display.

#### Steps for reproducing this issue:

1. Use Default Manjaro Linux with KDE Plasma (Latest) and use steam to download game(s)
2. Let it alone until it goes into Screen Lock
3. Steam will stop downloading eventhough I can still check its online status via Steam app on my smartphone.

**Comment by kisak-valve** [comment]
Hello @ccxex29, are you still experiencing this issue on an up to date system?
