### ISSUE TITLE
Friends menu is modal

### ISSUE THREAD

**Issue by Nenderus** [ValveSoftware/steam-for-linux#5724]
#### Your system information

* Steam client version (build number or date): 1535576546
* Distribution (e.g. Ubuntu): ALT Workstation 8.2
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When opening the "Friends List" window via "Friends" - > "View Friends List" or " View"
- >"Friends" pop - up list tab "View " or" Friends " becomes static on top of all Windows and inactive until you re-click the tabs "View" or "Friends" as in the screenshot (steam window was moved after "hangs" drop-down list).

![screen](https://user-images.githubusercontent.com/3469389/44981586-b0644680-af7b-11e8-8b47-f99bbb2709fd.png)

This behavior occurs in Gnome (this bug is also reproduced in Ubuntu 18.04) and Mate. If you are using KDE there is no such bug.

#### Steps for reproducing this issue:

1. Click "Friends"
2. Click "View Friends List"

or 

1. Click "View"
2. Click "Friends"

**Comment by 4LT** [comment]
I can confirm that this also occurs for me
Distro: Arch
Window Manager: dwm

**Comment by Grief** [comment]
I am on KDE and the issue reproduces but differently - the popup menu disappears but clicking into the region where it was drawn even when another window (e.g. browser or something) is opened leads to steam windows activation. Clicking menu again closes the invisible window.

So, I believe the actual issue is that when Chat is opened, menu where it was opened from is not correctly closed

**Comment by objarni** [comment]
I found a workaround: move mouse randomly around the main Steam windows menu bar, the window Friends list window then disappears again, I'm on Ubuntu 18.04 Desktop (Gnome WM).

**Comment by kisak-valve** [comment]
Hello, per "Fixed a case where drop-down menus or notifications would become stuck on screen" in the [2019-01-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1702825843218737580) Steam client beta update, please retest this issue.

**Comment by objarni** [comment]
I just re-tested, it works as expected now. Great, thanks!

**Comment by kisak-valve** [comment]
Thanks for retesting @objarni, closing.
