### ISSUE TITLE
[CS:GO] Ubuntu 18.04.1 LTS Crash

### ISSUE THREAD

**Issue by lbaldim** [ValveSoftware/steam-for-linux#5725]
System Information:
Steam client version: September 3 2018
Distribution:  Ubuntu
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

Issue:
If i close Counter-Strike: Global Offensive after playing and try to relaunch, i'll stare to a black screen for 8-9 seconds and then it'll crash. If i want to play, i need to reinstall it everytime.

Steps for reproducing this issue:

1. Start Steam
2. Start Counter-Strike: Global Offensive

**Comment by kisak-valve** [comment]
Hello @lbaldim, CS:GO issues are being tracked in the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux/issues) issue tracker. When you open a new issue report there, please include your system information from Steam and any CrashIDs or minidumps (commonly found in `/tmp/dumps`) related to this issue.

**Comment by lbaldim** [comment]
Thanks!
