### ISSUE TITLE
Some GTA games repeated in library

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#5726]
#### Your system information

* Steam client version (build number or date): Sep 1 2018, at 01:54:31
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

Some GTA games repeated in my library. Check screenshot.
![IMG/Screenshot here](https://puu.sh/Bp8X8/1488b7c389.png)
I already saw something like this when i was on windows.
When i try to install wrong version, installing preparation window stuck at 0%

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue is already being tracked at #3406. Closing as a duplicate.
