### ISSUE TITLE
Switch Pro Controller not detected with added udev rules & steam-devices installed

### ISSUE THREAD

**Issue by Insantyz1** [ValveSoftware/steam-for-linux#5730]
#### Your system information

* Steam client version (build number or date): Sep 1 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I have the Switch Pro Controller and when I connect it to the computer, the kernel detects it as it shows up when executing "lsusb" in terminal. I have also added correct udev rules, I am using the distro provided steam package with "steam-devices" installed. Yet Steam doesnt detect my Switch Pro Controller.

https://steamcommunity.com/app/353370/discussions/1/1743342647549891550/

#### Steps for reproducing this issue:

1. Plug in Switch pro Controller
2. Launch Steam
3. Controller is not detected

**Comment by Insantyz1** [comment]
Was probably something OS/Distro related. I have updated to 18.10 now and it works. Ticket can be closed.

**Comment by kisak-valve** [comment]
Thanks, closing per the last comment.
