### ISSUE TITLE
Counter Strike Global Offensive isn't starting in ubuntu 18.04

### ISSUE THREAD

**Issue by dicadavid** [ValveSoftware/steam-for-linux#5731]
#### Your system information

* Steam client version (build number or date):  September 4th, 2018
* Distribution (e.g. Ubuntu): ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

Issue

My machine is a i3 6100u 12gb ram using a intel graphics.
 
When starting Counter Strike Global Offensive screen turns black for about 3-5 seconds and the the process terminates without an error message.

Starting it with the options:
-safe
-novid
-autoconfig
-legacyscaleformui
doesn´t help! Same behaviour.

Reinstalling the game didn´t solve the issue either.

The game worked for multiple months fine and this problem highly likely came with the last update.

**Comment by kisak-valve** [comment]
Hello @dicadavid, CS:GO issues are being tracked in the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux) issue tracker, please use that for issues with this game.

That said, you're most likely seeing https://github.com/ValveSoftware/csgo-osx-linux/issues/1757 and try adding `-nojoy` to your game's launch options.
