### ISSUE TITLE
Bug/Improvement: Steam Play Proton & Google Earth VR

### ISSUE THREAD

**Issue by kazetsukaimiko** [ValveSoftware/steam-for-linux#5732]
#### Your system information

* Steam client Build Sep 1 2018, 01:54:31 / package version 1535768746
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:

This is not a bug in Google Earth VR on Steam Play.

Eager to test some of the Proton stuff, I went to install Google Earth VR to see if the support was really there. I have an Oculus Rift and it looks like that headset is unsupported for Steam VR (on Linux?) at this time, but the messaging around this is vague.

I think the user experience could be improved a bit here even in light of no support. When clicking the "Steam VR" icon or attempting to go into a VR game, there may be a way to better tell the user the problem.

Current behavior:
"Headset not detected" + Offer to Reboot -> This messaging is vague. 

Possible alternative behavior(s):
If the Vive is the only supported headset now, it may be prudent to change the message to state "HTC Vive not detected." + Offer to Reboot / troubleshooting link + an explanation like "Steam VR on Linux/SteamOS currently requires one of the following headsets:

Implications:
The first question that popped into my head when seeing this was "How do I tell it I have a Rift?", then running around in settings trying to find how to configure SteamVR. 

While Google Earth supports the Rift, and Earth is "whitelisted" for Steam Play via Proton, these kinds of edge cases are going to open up. This is a friendly suggestion for the Valve team for improving the user experience.

#### Steps for reproducing this issue:

1. Connect an Oculus Rift or other headset unsupported by SteamVR.
2. Open Steam, attempt to start SteamVR.
3. Note the "Headset not detected" / "SteamVR Not Ready" messaging. This does not tell the user what actually is wrong (their headset is not supported).

**Comment by kisak-valve** [comment]
Hello @kazetsukaimiko, the meat of your issue report deals with SteamVR, not the Steam client, so I've transferred this issue to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/128.

As a side note, titling an issue report and starting the issue report with 'this is not an issue with the thing in the title' is potentially frustrating to the interested reader. Please don't do that.
