### ISSUE TITLE
Bioshock Infinite (8870) DS4 wrong mapping on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by daasuharo** [ValveSoftware/steam-for-linux#5733]
#### Your system information

* Steam client version (build number or date): Aug 29th
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. When it displays to use 'x' on screen I have to use triangle but xbox 'x' should be mapped to DS4's Square button. A/B mapping to cross/circle are correct.

Email response back from Virtual Programming's support 
"Unfortunately we ported this under license and have no longer instruction or ability to update."

So I was hoping it be actionable with steam for linux support.

**Comment by kisak-valve** [comment]
Hello @daasuharo, unless I'm missing something, the button cues rendered in third party games are not influenced by the steam client. Looking around a little bit it looks like the game originally only supported xbox-like controllers (regardless of OS) and can't tell the difference between different controllers.

So, there's not much that could be done on this side.
