### ISSUE TITLE
[Feature Request] Allow overriding the proton version per game

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5740]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/1312.
@Sbte posted on 2018-09-08T09:38:16:

# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
In the Steam options we can choose "Use this tool instead of game-specific selections from Steam" to use an alternative version of Proton. It would be nice to be able to select this per game.

## Justification [optional] 
It seems like for every game Proton is downloaded separately (I have to download 300+ MB for every game every time Proton is updated). Since this is happening anyway, it would be nice to be able to select which version is downloaded per game.

Also, if all games work fine with the default selection, but you want to try one game with the latest version, updating all of them to the newer version might actually break games that worked fine with the default version.

## Risks [optional]
Actually reduces risks, because working games are not updated to an unstable version.

## References [optional] 
***
@vanyasem commented on 2018-09-08T10:32:57

@jarrard ValveSoftware/steam-for-linux#5638. Your suggestion is unrelated, and is, in fact, a duplicate
***
@jarrard commented on 2018-09-08T10:43:36

Ok cheers,.

**Comment by tingvarsson** [comment]
> It seems like for every game Proton is downloaded separately (I have to download 300+ MB for every game every time Proton is updated). Since this is happening anyway, it would be nice to be able to select which version is downloaded per game.

Actually not completely true, it sets up a prefix per game, but all are based on the same version of Proton now.
Having two versions of Proton installed is already there, Default and Beta version. Look in your steamapps/common directory and you see both.
So what is missing is configuring which one per game.

The main justification would be for testing new BETA versions for specific games as you mention in the request.

**Comment by LCWilliams** [comment]
I'd like to plus one/bump this!

**Comment by Zamundaaa** [comment]
AFAIK it does **NOT** seem to be like that. It installs proton and then just uses it for all the games. for example I checked my Google Earth VR install in both my Windows and Linux steam folders and it's exactly the same size. No wasted space here.
With 2 Proton versions you'd just have twice the space used by proton, so ~600-700 MB. The amount of space used by this system would be your decision, if you just have one Proton version then it's under 400MB, and if you need other versions for some specific games that doesn't work as well as with your current choice for all then you'd just install a version that works. If you don't have the space or don't want to waste it it's your choice to uninstall specific versions.

If this were implemented you should probably have a selection in your game properties in which you can choose between "use currently selected Proton version in your settings", (possibly, would be nice to have)"use latest Proton version" and every other version that's available.

**Comment by kisak-valve** [comment]
Closing as implemented in the [2019-01-17](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1703951108827819236) Steam client beta update.
