### ISSUE TITLE
Switchable Graphics isn't at all an user friendly experience.

### ISSUE THREAD

**Issue by JohnnyonFlame** [ValveSoftware/steam-for-linux#5741]
#### Your system information

Dell Inspiron 14
Nvidia 750M and i7 4500U

* Steam client version: Aug 29, 2018
* Distribution (e.g. Ubuntu):  xUbuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Using steam on a Switchable Graphics device isn't user friendly. Bumblebee is outdated and provides no Vulkan support, nvidia-prime isn't at all an acceptable solution, and spawning a new x-instance is, while a major inconvenience, but alas, at least a working solution.

For these trying to run Steam games on a different X server than their Steam Clients':
- Configure your new X session, [nvidia-xrun is a great starting point](https://github.com/Witko/nvidia-xrun)
- Save both of these (fragile! don't blame me for _anything_ that happens) [scripts](https://gist.github.com/JohnnyonFlame/c448f3b8dc810032ed3f2cd809351a67) to your home folder
- Now, change your game's launch options to:
`~/steam_setup.sh "%command%"`
- Click 'play' on the steam client
- Switch to a free tty. start your new X server with:
`./nvidia-xrun ./steam_run.sh`
- After being done with said game, kill the xterm window with `exit`

I hope this serves as documentation for those with issues right in this moment, and that maybe this shines a light on what is a major usability issue.

**Comment by kisak-valve** [comment]
Hello @JohnnyonFlame, I'm going to close this issue report as it's informational and not an actionable issue with the steam client.

Related to #5600.
