### ISSUE TITLE
feature request: create a global persistent Proton %USERPROFILE% drive

### ISSUE THREAD

**Issue by nmiell** [ValveSoftware/steam-for-linux#5743]
Currently Proton uses a per-game emulated C: drive that is created when the game is installed and deleted when the game is uninstalled and a Z: drive that's always mapped to /.

I suggest creating a persistent U: drive that is shared by all emulated Windows games that contains the Windows %USERPROFILE% directory and consequently all the Windows Known Folder directories like FOLDERID_RoamingAppData, FOLDERID_LocalAppData, FOLDERID_Documents, FOLDERID_SavedGames, etc.

This would solve two current problems with Proton:

1. Uninstalling a Steam game unexpectedly deletes your save files when the per-game C: drive is deleted.
2. Games which expect to be able to import save files from previous games in the series (e.g. Telltale's The Walking Dead) cannot find the save files because they're in a different unmapped drive C:

**Comment by kisak-valve** [comment]
Hello @nmiell, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/231 / https://github.com/ValveSoftware/Proton/issues/428. Closing as a duplicate.
