### ISSUE TITLE
Play against bots *random* isn't: 1st Cache, 2nd Italy, ...

### ISSUE THREAD

**Issue by petersilva** [ValveSoftware/steam-for-linux#5744]
#### Your system information

* Steam client version (build number or date): Sep 8 2018 at 19:21:25
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expect to get a random map, but I always get the same sequence, first cache, then Italy.

#### Steps for reproducing this issue:

1. Start up CS:GO 
2. Select Play
3. Select Play against bots
4. Competitive
5. Random
6. get Cache map. After Cache, will get Italy.

for the last few months (perhaps since switch to source 2?) 
I'm in Canada, if that makes a difference.

**Comment by kisak-valve** [comment]
Hello @petersilva, CS:GO issues are being tracked in the csgo-osx-linux issue tracker, so let's track this issue at https://github.com/ValveSoftware/csgo-osx-linux/issues/1819.
