### ISSUE TITLE
Dates and times being shown wrongly

### ISSUE THREAD

**Issue by NotMrFlibble** [ValveSoftware/steam-for-linux#5747]
#### Your system information

* Steam client version: 1536436120
* Distribution: Debian stable (with some backports)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Not relevant

#### Please describe your issue in as much detail as possible:

Dates and times are being shown incorrectly.. Dates are being shown with day and month swapped, i.e. in the American muddle-endian format; times are being shown as 12-hour. I expect the proper formats for my locale (shown below).

I'm fairly sure that this started happening with the introduction of the new Steam chat,

```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE=C.UTF-8
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
$ date +'%X %x'`
15:40:29 11/09/18
```

**Comment by kisak-valve** [comment]
Hello @NotMrFlibble, there's already an open issue for this at #3455. Feel free to add your experience there.

Closing in favor of the existing issue report.

**Comment by NotMrFlibble** [comment]
That's for chat. This is for the Steam client in general.
