### ISSUE TITLE
NBA 2K18: unable to connect to 2K server

### ISSUE THREAD

**Issue by alley-oop** [ValveSoftware/steam-for-linux#5750]
#### Your system information

* Steam client version (build number or date): Aug 29 2018, at 20:06:59 / 1535576546
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
1. Launch NBA 2K18, with proton 3.7-6.
2. the in-game connection to 2K server fails.

**Comment by kisak-valve** [comment]
Hello @alley-oop, issues with games using Proton is being tracked in the Proton issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/1405.
