### ISSUE TITLE
Steam doesn't recognise alt+latin letters special latin letters, when not in steam overlay; Steam detects enter as shift+enter in overlay

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5755]
#### Your system information

* Steam client version (build number or date):  Sep 8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes ; but it is also persistant on No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Żółźćśęąń letters don't get recognized in steam(unknown keycode 0?)
And the żźółćśęąń keys(alt+zxolcsean) only work within steam overlay, but don't work in steam chat and steam itself without the overlay.
Present in both beta and stable version of steam;
It broke some time ago, PL keyboard layout is selected in KDE Plasma settings.

Expected: żźółćśęąń letters show up everywhere. Enter works like enter not like shift+enter in steam overlay chat. It doesn't seem to detect the released shift key as being pressed constantly because the letters written are lower case, but it recognizes it as such when I click enter.
Clicking enter fixes the issue.
#### Steps for reproducing this issue:

1. Writing any Polish/Czech etc. special letters into Steam.
2. Shift+tab into a steam overlay, the special letters now work just fine, but clicking enter causes a behavior associated with shift+enter, clicking shift fixes the issue.

**Comment by kisak-valve** [comment]
Hello @kubast2, this issue is already being tracked at #5704. Closing as a duplicate.
