### ISSUE TITLE
Windows+Linux Starting a trade within steam chat causes issues

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5756]
#### Your system information

* Steam client version (build number or date):  Sep 8 2018, at 19:21:25 ; no idea most likely the newest stable windows steam release
* Distribution (e.g. Ubuntu): Arch Linux & Windows 10
* Opted into Steam client beta?: [Yes/No] Yes(Arch) & No(Windows)
* Have you checked for system updates?: [Yes/No] Yes(Arch & Windows)

#### Please describe your issue in as much detail as possible:
Noticed with a friend that it isn't possible to make a trade by sending a trade offer from steam chat, because: 
on windows: it shows up old steam chat, and it causes an interesting glitch(basically both windows shows the chat real time, while the one with a new design after a single character forwards text box to an old steam chat)
on linux: it shows a pitch black trade offer window

Expected: Trade window shows up and it isn't pitch black
#### Steps for reproducing this issue:

1. Open steam chat
2. Right click on a tab with my friends nickname > trading > Send a offer trade
3. Accept the offer to trade

**Comment by Margen67** [comment]
Any update on this?

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost. If anyone encounters this issue, please open a new issue report with a reference to this issue report.
