### ISSUE TITLE
Steam detects a shortcut file that doesn't exist, cannot add a game shortcut to a desktop.

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5757]
#### Your system information

* Steam client version (build number or date): Sep 8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I downloaded a copy of Borderlands 2 ,I saw that a shortcut wasn't created, an ~/Desktop file didn't got created, however steam persists that the shortcut is there, reinstalling the game doesn't help, creating a shortcut manually works, but it ends up having no icon for the game, as  I understood the Icon= field needs to filled with steam_icon_gameID. I created the shortcut manually, it works, but there is no icon.

Expected: Shortcut gets created
#### Steps for reproducing this issue:

1. Download games.
2. One of them won't create a shortcut on desktop. 
3. Right click on a game in steam client and try to create a shortcut on a desktop.
4. "Couldn't create shortcut. It is probably already here"

**Comment by kisak-valve** [comment]
Hello @kubast2, this issue is already being tracked at #5590. Closing as a duplicate.
