### ISSUE TITLE
Steam chat doesn't work when a temporary connection disconnect happens

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5758]
#### Your system information

* Steam client version (build number or date): Sep 8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes ~ persistent in both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Suspending my machine and chainging wifi status and then turning it back on causes issues with steam chat.

Steam chat should either inform it is actually offline from the steam chat or it should reload itself/reestablish connection(?) idk what does wrong, but it often breaks

#### Steps for reproducing this issue:

1. Use steam chat
2. Suspend pc/change wifi network/get disconnected from steam chat without steam chat telling you it is disconnected
3. Now you need to go to offline mode in steam chat and back to online mode for the steam chat to work and send messages.

**Comment by kisak-valve** [comment]
Hello @kubast2, this issue is already being tracked at #474. Closing as a duplicate.
