### ISSUE TITLE
Steam-native doesn't launch even though the libva libraries are installed on the system

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5759]
#### Your system information

* Steam client version (build number or date): Sep  8 2018 19:20:58
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
[kubast2@archlinux ~]$ sudo pacman -Fs libva-x11.so extra/libva 2.2.0-2     usr/lib/libva-x11.so ^[[Amultilib/lib32-libva 2.2.0-1     usr/lib32/libva-x11.so
[kubast2@archlinux ~]$ sudo pacman -Fs libva-x11.so
extra/libva 2.2.0-2
    usr/lib/libva-x11.so
multilib/lib32-libva 2.2.0-1
    usr/lib32/libva-x11.so
[kubast2@archlinux ~]$ sudo pacman -S lib32-libva libva
[kubast2@archlinux ~]$ sudo pacman -S steam-native-runtime
ostrzeżenie: lib32-libva-2.2.0-1 jest w najnowszej wersji -- ponowne instalowanie
ostrzeżenie: libva-2.2.0-2 jest w najnowszej wersji -- ponowne instalowanie
ostrzeżenie: steam-native-runtime-1.0.0.54-5 jest w najnowszej wersji -- ponowne instalowanie
[kubast2@archlinux ~]$ steam-native
Error: You are missing the following 32-bit libraries, and Steam may not run:
libva.so.1
libva.so.1
libva-x11.so.1

^ in a nutshell, steam says it couldn't find libva.so ,but the libs are installed and it literally was launching just fine an hour ago Note: I have steam-native shortcut on desktop and steam-native is first thing that autocompletes in krunner, so I am pretty sure I was running steam-native all this time

#### Steps for reproducing this issue:

1. No idea it broke today even though the files are in here the build version didn't change and the files/libraries are already present on my system.

**Comment by kisak-valve** [comment]
Hello @kubast2, [`libva`](https://www.archlinux.org/packages/extra/x86_64/libva/) and [`lib32-libva`](https://www.archlinux.org/packages/multilib/x86_64/lib32-libva/) no longer provides `libva.so.1`. You're looking for the [`libva1`](https://www.archlinux.org/packages/community/x86_64/libva1/) and [`lib32-libva1`](https://www.archlinux.org/packages/multilib/x86_64/lib32-libva1/) packages which are pulled in by the [`steam-native-runtime`](https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/) package.

Closing as invalid.

**Comment by kubast2** [comment]
@kisak-valve Yep the issue happend, because I updated before `steam-native-runtime` had `libva1` and `lib32-libva1` packages as dependencies, and before `libvs.so.1` and `libva-x11.so.1` were searchable from `pacman -Fs `

**Comment by kubast2** [comment]
other than that it is all good now
