### ISSUE TITLE
Steam doesn't turn on on ubuntu 18.04 lts

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5760]
#### Your system information

* Steam client version (build number or date): no idea
* Distribution (e.g. Ubuntu): Ubuntu 18.04 lts
* Opted into Steam client beta?: Not yet
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
tar: To nie wygląda jak archiwum tar
xz: (stdin): Nieznany format pliku
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/j/.steam/ubuntu12_32/steam-runtime’: Nie ma takiego pliku ani katalogu

Can't launch steam

#### Steps for reproducing this issue:

1. Install ubuntu 18.04.
2. Update ubuntu and install nvidia driver.
3. Install steam.
4. Try to launch steam.

**Comment by kisak-valve** [comment]
Hello @kubast2, I read this as steam failing to download all the bootstrap files, then falling over an empty or corrupt archive. You can try `steam --reset` or move/remove `~/.steam` and try again.

**Comment by kubast2** [comment]
@kisak-valve 
I see, I have just installed steam provided package from steampowered.com
It tried to remove .steam folders etc., but failed because it returned in cmdline
"rm: /home/user/.steam is a folder"
etc. on 3-4 folders
So I have deleted those folders myself, and it have fixed the issue.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by jcrben** [comment]
https://askubuntu.com/a/1018230/457417 seemed to help for me:
`mkdir "/home/$USER/.steam/ubuntu12_32/steam-runtime"`
