### ISSUE TITLE
Shouldn't DE/system default file picker be used instead?

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5762]
#### Your system information

* Steam client version (build number or date): Sep 8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Ubuntu and Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

The steam internal file picker is very barebones.

Because I see that on windows, windows explorer.exe file picker shows up, I presume that desired behavior on Linux would be running system's default/Desktop Enivorment's default file picker.
It should be a lot faster to deploy something that would use System's defaults and fallback to steam's internal file picker if there is none/the default one didn't show up/command not found.
It would be definitely quicker than implementing search+thumbnail+media preview etc. features.

What happens:
Steam's internal file picker opens up

What should happen:
Dolphin's/Nautilus's/Thunar's/<there is some file in linux that has a list/shows the default system filepicker and it probably makes it possible to use any file manager's file picker>'s file picker shows up.

#### Steps for reproducing this issue:

1. Select file in steam's web browser or Steam chat
2. Internal steam file picker shows up.

**Comment by kisak-valve** [comment]
Hello @kubast2, this feature request is already being tracked at #4003. Closing as a duplicate.
