### ISSUE TITLE
All controllers sensetive go crazy

### ISSUE THREAD

**Issue by adam900710** [ValveSoftware/steam-for-linux#5765]
#### Your system information

* Steam client version (build number or date): Sep 8 2018 19:21:25
* Distribution (e.g. Ubuntu):  Archlinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] NO during the test

#### Please describe your issue in as much detail as possible:

The right joystick sensitive of *all* my gamepads (Xbox One, DualShock 4, Nintentdo Switch pro) go crazy nearly all of a sudden.

Xbox One controoller (connected using bluetooth) worked pretty well since Sep 14th, and it was mostly used to play Dark Souls 2 SOFTS with proton.

Now today (Sep 16th) I just uninstalled Dark Souls 2 to try Dark Souls 3, and it turns out that the D-pad is too sensitive, I can't even navigate to "New game" properly.
Then I tried some Linux native games like "The long dark" still the same problem.
The right joystick is damn too sensitive so it's unable to play.

On the other hand, the left joystick is working properly without problem, at least in "The long dark".
Tried all my 3 controllers, none of them has working right joystick nor D-pad.
But left joystick all seems to work properly navigating in "The long dark".

I also checked my pacakge manager log, my last update is Sep 13th, thus no system package update.
I also tried update my system, no change.

#### Steps for reproducing this issue:

1. Use gamepad to play games
2. Try any Linux native game
3. Use right joystick to change view

**Comment by adam900710** [comment]
Well, "Dead cells" doesn't detect the game pad either, instead it still shows keyboard keys other than gamepad buttons.
And in that case, right joystick is just acting like mouse.

**Comment by adam900710** [comment]
BTW, for the same proton game, the same Dark Souls series, DS2 SOFTS works fine with the gamepad, while DS3 has the serious right joystick sensitive problem.

**Comment by kisak-valve** [comment]
Hello @adam900710, If I'm reading this correctly, all the affected games are using Proton and we're tracking issues with games running with Proton in its issue tracker. so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/1484.

**Comment by adam900710** [comment]
Unfortunately, only Dark Souls 2 SOFTS and Dark Souls 3 are proton games.

"The long dark" is Linux native game, and it is the most affected one.
Even setting in-game camera sensitive to 0, it's still too sensitive for the right joystick.

**Comment by adam900710** [comment]
Find a workaround.

In big screen mode, disabling all controller support solves the problem in "the long dark" game.
So it would be something within steam client screwing up the controls.

**Comment by 2fst4u** [comment]
I've just stumbled across this issue, I'm having the same sensitivity issues with The Long Dark but disabling support in Big Picture mode doesn't help. It stops the gamepad from working for me. I also have sensitivity set to zero and it's unplayable.
