### ISSUE TITLE
Taking a screenshot permanently steals focus from the game window

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/steam-for-linux#5769]
#### Your system information

* Steam client version (build number or date): Sept 8 2018, 19:21:25
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

System info as reported by steam: https://gist.github.com/MayeulC/650f3b84a621e113720d4a8b03923d34

Most notably, I'm using Mesa 18.2 on a R9 Fury, with KDE plasma 5 (X window system).

#### Please describe your issue in as much detail as possible:
When I take a screenshot, I expect to be able to play the game after. Instead, the game does not update the video output, and does not seem to accept input. It actually looks like input/output events are buffered, as I can forward to the next frame by alt-tabbing out, then in. It then seems to register the input, as I can for instance display the overlay (which is also unresponsive).

This has been happening for a long (more than 3 months) while.

I reproduced this issue today, with the steam runtime on, big picture off, steam overlay enabled, in Mad Max. Those settings do not seem to be related.
The issue also happens in the main menu.

When alt-tabbing out, the game registers the current mouse position, and I can hear the game sound for a split second.

#### Misc info:
This could somehow be related to #4933.
Users with the same issue:  https://www.reddit.com/r/Stellaris/comments/7wa2ut/bug_taking_screenshots_with_steam_the_f12_key/

log with Mad Max: https://gist.github.com/MayeulC/aa83c59282d8edcef4c626137829c99b
The only slightly interesting line seems to be `Installing breakpad exception handler for appid(steam)/version(1536436120)`

keywords: screenshot, freeze, hang, focus

#### Steps for reproducing this issue:

1.  Play a game (I just tried with Mad Max)
2. Take a screenshot
3. Observe the freeze

**Comment by MayeulC** [comment]
I just did more testing, hoping to isolate the issue, as I have been afraid of taking screenshots trough steam for a while.

Exhibits the issue:
* Life is strange -- gamesave menu (after "press any key"). Music continues until the first alt-tab out. Uses 100% cpu, and made my mouse invisible until I killed it.
* Alien: isolation -- main menu
* Deus Ex: Mankind divided (I remember encountering the issue in-game, but I can't reproduce as I can't run my browser at the same time -- OOM)

No issue:
* Hollow Knight -- main menu
* Osmos -- main menu
* Bioshock infinite -- main menu
* Serious Sam 3
* Half-Life
* Cities: Skylines -- main menu
* Skyrim (proton) -- main menu
* Rise of the Tomb Raider -- main menu
* Windward -- main menu

There seems to be a distinct trend here with feral games, so maybe that's an issue that's specific to them, after all (I'm not sure if those are vulkan games or not). Unfortunately, I was limited to a selection of games I had already downloaded. Stellaris would be interesting to try.

---------
I tested Life is Strange both with and without the steam runtime, both hang. It also hangs when the FPS counter is disabled, and when a screenshot is first taken with the overlay displayed (though in the last case, it did not eat my mouse). It does not happen when the game is windowed. I don't really know what else I could try.

**Comment by kisak-valve** [comment]
Hello @MayeulC, are you still experiencing this issue on an up to date system?

**Comment by MayeulC** [comment]
No, I am not (just retested Life is strange). Thank you for reminding me of this, I'm closing the issue.

Though I use sway these days. I'll also re-test on KDE Plasma ASAP.

The only issue I am experiencing with screenshots is the inability to take screenshots with steamVR (home or otherwise), but I think that feature is just broken, be it on Linux or Windows.
