### ISSUE TITLE
Steam client freezes on i3wm when opening a link

### ISSUE THREAD

**Issue by cakesale** [ValveSoftware/steam-for-linux#5771]
#### Your system information

* Steam client version (build number or date): Sep 8 2018, at 19:21:25
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
On i3wm the Steam client locks up when clicking on a file path or web link from within the Steam client. The file manager or web browser window that opens up locks up the Steam client until the external application has closed.

#### 1 Web Browser
a. Click on a web link from within Steam for example a link on a game's News page
b. I might be wrong here but it seems the first web browser window that opens up if no browser window is already open will freeze the Steam client until the web browser is closed.

#### 2 File Manager
a. Go to the properties of any game > Local Files > Browse Local Files
b. The file manager that opens up will freeze the Steam client until closed.

**Comment by kisak-valve** [comment]
Hello @cakesale, this issue is already being tracked at #5090. Closing as a duplicate.
