### ISSUE TITLE
Grid View Images Are Not Cached

### ISSUE THREAD

**Issue by GarlandKey** [ValveSoftware/steam-for-linux#5773]
#### Your system information

* Steam client version: Sept 20, 2018: 
* Distribution (e.g. Ubuntu): Arch Linux (kernel 4.18.8)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expect that all of the Grid View images to be cached and only re-downled if there's an image updated by the developers. This is normally barely noticeable when on a highspeed connection, but when using wifi, if I'm scrolling my games, it takes a few minutes to download them all (I have over 1000 games). This seems inefficient and likely costly for Valve.  I can't be for sure, but I'm not sure Grid View always operated this way. 

#### Steps for reproducing this issue:

1. Restart Steam
2. Select Grid View
3. Images load every time you restart Steam.  For beta users who restart daily for updates, this is an annoyance, inefficient and probably costly for Valve.

**Comment by GarlandKey** [comment]
Also discussed [here](https://steamcommunity.com/discussions/forum/1/1697175413666796903/), so I'm positive that it isn't just me.  Is this a regression or intentional?

**Comment by kisak-valve** [comment]
Hello @GarlandKey, this issue is already being tracked at #3352. Closing as a duplicate.
