### ISSUE TITLE
GoldSrc Games No Longer Launch

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#5780]
#### Your system information

* Steam client version (build number or date): Sept 20 2018
* Distribution (e.g. Ubuntu): Arch (Testing Repository)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

For almost half a year, all GoldSrc games, even Sven-Coop, will not launch for me. When I click play, it will say "Running", but nothing happends. I've tried with two different window managers, bspwm and i3, both have the same results. All other games launch fine. I thought this would all iron itself out, and played CSGO in the meantime, but I miss 1.6, and this bug still remains. All other games launch fine. Steam runtime is DISABLED.

#### Steps for reproducing this issue:

1. Just try and launch the games

[System Information (Steam)](https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341)

There are more specs in my Steam profile, which is linked in my github page.

**Comment by kisak-valve** [comment]
Hello @shoober420, are there any hints in the terminal spew? (logged at `/tmp/dumps/<username>_stdout.txt`)

Also, does running steam with steam-runtime instead of steam-native make a difference?

**Comment by shoober420** [comment]
I did a fresh install of CS1.6, non beta, without my launch options. Here is the terminal output.

GameAction [AppID 10, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 10, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 10, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 10: 0
Game update: AppID 10 "", ProcID 6609, IP 0.0.0.0:0
>>> Adding process 6609 for game ID 10
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6612 != 6611, skipping destruction (fork without exec?)
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 6611 for game ID 10
>>> Adding process 6613 for game ID 10
Installing breakpad exception handler for appid(steam)/version(1537487679)
>>> Adding process 6614 for game ID 10

**Comment by shoober420** [comment]
I did a fresh install of CS1.6, non beta, without my launch options.

`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 10, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 10, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 10: 0
Game update: AppID 10 "", ProcID 6609, IP 0.0.0.0:0
>>> Adding process 6609 for game ID 10
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 10, ActionID 3] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6612 != 6611, skipping destruction (fork without exec?)
ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/lib/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 6611 for game ID 10
>>> Adding process 6613 for game ID 10
Installing breakpad exception handler for appid(steam)/version(1537487679)
>>> Adding process 6614 for game ID 10`

**Comment by shoober420** [comment]
Fresh install, non beta

`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""`
`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""`
`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to CreatingProcess with ""`
`GameAction [AppID 10, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""`
`GameAction [AppID 10, ActionID 3] : LaunchApp continues with user response "CreatingProcess"`
`Opted-in Controller Mask for AppId 10: 0`
`Game update: AppID 10 "", ProcID 6609, IP 0.0.0.0:0`
`>>> Adding process 6609 for game ID 10`
`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""`
`GameAction [AppID 10, ActionID 3] : LaunchApp changed task to Completed with ""`
`ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class:ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`pid 6612 != 6611, skipping destruction (fork without exec?)`
`ERROR: ld.so: object '/usr/lib32/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: `ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib32/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: `ELFCLASS32): ignored.`
`ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from `LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
`ERROR: ld.so: object '/usr/lib/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: `ELFCLASS64): ignored.`
`ERROR: ld.so: object '/usr/lib/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`
`ERROR: ld.so: object '/usr/lib64/libSDL2.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`
`ERROR: ld.so: object '/usr/lib64/libopenal.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`
`ERROR: ld.so: object '/home/jukilo420_-/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from `LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`
`>>> Adding process 6611 for game ID 10`
`>>> Adding process 6613 for game ID 10`
`Installing breakpad exception handler for appid(steam)/version(1537487679)`
`>>> Adding process 6614 for game ID 10``

**Comment by shoober420** [comment]
[terminal output](https://gist.github.com/shoober420/83ee7378629eddcaafea9e1b8db32577)

**Comment by shoober420** [comment]
To my surprise, using the runtime doesn't work either.

**Comment by shoober420** [comment]
Still isn’t launching, nothing appears to be different in the terminal output.

**Comment by shoober420** [comment]
Games launch fine now. Thank you good sirs!
