### ISSUE TITLE
Restore Windows Games through the Backup & Restore Tool

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5786]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/1609.
@HadetTheUndying posted on 2018-09-26T09:44:18:

# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
You can currently backup your games installed using Steam Play but cannot Restore them through the Linux Client
## Justification [optional] 
This is a Major Oversight and hampers low bandwidth users that take advantage of the backup system as to not go over on their datacaps. I 
## Risks [optional]
None, this functionality should already be present it appears to be an oversight

## References [optional] 
Try Backing up a Windows Only Game in the Linux Client(It will allow you.) Now try restoring it. (It will not allow you to do so.)

**Comment by HadetTheUndying** [comment]
Okay so it does work and I'm an idiot. You need to allow all steam games to be installed via Steam Play in your settings and it'll let you restore them after that.
 oof

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Espionage724** [comment]
Happened upon this thread after searching to see if this was possible; to add onto this, you seem to also need to have a version of Proton **installed** before you can restore a non-Proton game.
