### ISSUE TITLE
Civilization 6 failed to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by kirkins** [ValveSoftware/steam-for-linux#5790]
#### Your system information

* Steam client version (build number or date): Sep 8th, 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

<hr/>

I'm trying to run Civilization 6 from steam. I get a message saying "an unrecoverable error has occured, and civilization 6 cannot continue".

I'm looking through some solutions here, where I found that I could run the Civ6 executable directly from the directory `~/.steam/steam/steamapps/common/Sid Meier's Civilization VI`.

When I run it from that directory in terminal I get back:

    ./Civ6: error while loading shared libraries: libopenal.so.1: cannot open shared object file: No such file or directory

I found some [similar questions][1] which recommend installing various packages but none of them have worked.

  [1]: https://askubuntu.com/questions/608418/error-while-loading-shared-libraries-libopenal-so-1-game-pacapong-in-ubuntu

**Comment by kisak-valve** [comment]
Hello @kirkins, odds are you're getting a false lead to follow because the game is not being run with the steam runtime. When run from steam, `~/.steam/error.log` may collect a hint as to what has gone wrong.

Alternatively, what does `~/.steam/ubuntu12_32/steam-runtime/run.sh ./Civ6` put in the terminal spew?

**Comment by kirkins** [comment]
@kisak-valve my steam has a different file structure. There is a log folder with a bunch of txt files but none with error in the name.

When I use `~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./Civ6` I get:

```
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
[S_API FAIL] SteamAPI_Init() failed; no appID found.

```

**Comment by kisak-valve** [comment]
Okay, then the general terminal log will be at `/tmp/dumps/<username>_stdout.txt`.

**Comment by kirkins** [comment]
@kisak-valve made a mistake, I forgot I updated to 18.04.

The `/tmp/dumps/<username>_stdout.txt` reads:

```
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
```

**Comment by airv** [comment]
It's was the same problem for me. I updated Ubuntu 16.04 to 18.04 and now I have the message ""an unrecoverable error has occured, and civilization 6 cannot continue".

Civ 6 was working perfectly in Ubuntu 16.04.

**Comment by kisak-valve** [comment]
Hello @kirkins, @airv, are either of you still experiencing this issue on an up to date system?

Re-reading this issue report, there's no real hints to ponder on how this game failed to run. It may be worthwhile to also mention this issue to the game's dev(s) if it hasn't been already.

**Comment by airv** [comment]
It's working now. I have no more problem with the game.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
