### ISSUE TITLE
Steam link, multi-monitor, wrong monitor, game crashes, gamepad won't work when it says it should, sound not passing through

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#5792]
Same specs as : https://github.com/ValveSoftware/steam-for-linux/issues/5791

I've been trying really hard to have a good experience with my Steam Link and Steam Gamepad interfacing with my computer, but I've seriously not had a fun time.

I have these issues:
* Sound only plays on the computer, it won't send to the Steam Link. Yes, I've gone through troubleshooting, yes the Steam Link is set to stream audio. Yes I get audio in the main Steam Link menu, but not in Steam Big Picture steamed from my Linux gaming rig.
* I have 3x1920x1080 monitors, sometimes games play on the left monitor, but my main one is the middle one. When this happens, the SteamLink gets confused as to what monitor to display, and half the time I have to get up and just switch back to steam big picture. Completely defeating the whole point of the ecosystem
* A good amount of time games crash, and I don't even get told it's crashing, or still loading, because it just comes back to the "Play" button in Steam Big Picture. I get given zero feedback as to what's going on. This often leads me to also not knowing the game is still loading.
* A good amount of games in my library list gamepad support, but don't work when I'm using it in this configuration. An example is Hoard. Also, some games the button layout doesn't match what's listed on the gamepad itself.

I want this to be an awesome couch experience, but thus-far, this is seriously insufficiently tested considering how long this product has been on the market. I will GLADLY work with WHOMEVER to help make this an awesome product, through beta testing and such. But I am especially frustrated things like these, basic things, have not already been solved by now.

That being said, doing this over my 802.11ac network has actually been pretty awesome, so it's not all salt and vinegar ;)

**Comment by kisak-valve** [comment]
Hello @BloodyIron, multi-issue issue reports are bad for any issue tracker. Please search [the existing issue reports](https://github.com/ValveSoftware/steam-for-linux/issues?q=is%3Aissue+is%3Aopen+label%3AStreaming) and only have one issue per issue report.
