### ISSUE TITLE
[SteamOS] Switching to Steam beta client causes Proton games to stop working

### ISSUE THREAD

**Issue by pierrep** [ValveSoftware/steam-for-linux#5800]
[steam-489830.log](https://github.com/ValveSoftware/steam-for-linux/files/2430271/steam-489830.log)
* Steam client version (build number or date):  Sept 8 2018
* Distribution (e.g. Ubuntu): SteamOS 2.0 (64 bit)
    Kernel Version:  4.16.0-0.steamos2.1-amd64
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

    CPU Brand:  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Driver:  NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54

#### Please describe your issue in as much detail as possible:
Switching to steam beta client causes Proton games to fail to start.
See https://www.reddit.com/r/SteamPlay/comments/9i86fu/steamos_some_games_snake_pass_lego_city/
for another case of this happening

I've attached the Proton log of SkyrimSE when it failed to run - the launcher ran, but I got a black screen after selecting 'Play'.
#### Steps for reproducing this issue:
1. Switch to latest steam client beta on SteamOS
2. Reboot
3. Try playing a Proton game (my test case was SkyrimSE - fails)
4. Revert to stable client (which caused me to encounter this - https://github.com/ValveSoftware/steam-for-linux/issues/5798)
5. Try playing a Proton game - works

**Comment by kisak-valve** [comment]
Hello @pierrep, this looks like the same issue as https://github.com/ValveSoftware/SteamOS/issues/652.

Closing in favor of the existing issue report.

**Comment by pierrep** [comment]
OK no problem...good to see it's already under investigation
