### ISSUE TITLE
I want to know how to make Steam forget about my controller so I can set it up as new again

### ISSUE THREAD

**Issue by harogaston** [ValveSoftware/steam-for-linux#5801]
#### Your system information

* Steam client version (build number or date): Sep 26 2018
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
How can I make Steam recognize my controller as new? I can't see the "IDENTIFY" button for my controller now, and games don't see my controller connected. But it shows in controller settings page.

It is a Trust GTX 560 and I was playing fine before, when I plugged it in for the first time. I got the identity button and I played without any problems. But after I restarted my PC, Steam recognizes the controller differently and  there is no "IDENTIFY" button anymore and the controller does not work in games. 

My question is not operating system related. I want to know how to make Steam forget about my controller so I can set it up as new again.

#### Steps for reproducing this issue:
1. I dont know how it happened.
2. 
3.

**Comment by lucifertdark** [comment]
1. Shut down steam
2. go to steam/userdata/(number folder)/config/controller_configs 
3. delete the contents of that folder
4. start steam
The "IDENTIFY" button will be there now.

**Comment by harogaston** [comment]
I've done that previously. It doesn't work. I don't know if steam has syncronized the info online or how, but after deleting that folder and also everything under "SDL_GamepadBind" in .steam/steam/config/ still when I restart Steam the situation is unchanged.
Here is a screenshot of what I get:

![screenshot_20180930_141133](https://user-images.githubusercontent.com/5424205/46260323-c4d42a00-c4ba-11e8-922d-40ebf0f939f0.png)

**Comment by harogaston** [comment]
I think something might not be right with how Linux is loading my device. Here is some relevant output, and then I will tell you some considerations:
```
hwinfo --usb
09: USB 00.0: 0000 Unclassified device
  [Created at usb.122]
  Unique ID: WYZM.TeVNIXfF2a4
  Parent ID: k4bc.2DFUsyrieMD
  SysFS ID: /devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0
  SysFS BusID: 1-12:1.0
  Hardware Class: unknown
  Model: "Trust GXT Gamepad"
  Hotplug: USB
  Vendor: usb 0x145f "Trust"
  Device: usb 0x0232 "Trust GXT Gamepad"
  Revision: "1.14"
  Driver: "usbhid"
  Driver Modules: "usbhid"
  Device File: /dev/input/js0
  Device Files: /dev/input/js0, /dev/input/by-id/usb-HJC_Game_Trust_GXT_Gamepad-joystick, /dev/input/by-path/pci-0000:00:14.0-usb-0:12:1.0-joystick
  Device Number: char 13:0
  Speed: 12 Mbps
  Module Alias: "usb:v145Fp0232d0114dc00dsc00dp00ic03isc00ip00in00"
  Driver Info #0:
    Driver Status: usbhid is active
    Driver Activation Cmd: "modprobe usbhid"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #8 (Hub)
```

```
dmesg
[ 2063.453404] usb 1-12: new full-speed USB device number 4 using xhci_hcd
[ 2063.598428] input: HJC Game Trust GXT Gamepad as /devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0/0003:145F:0232.0005/input/input20
[ 2063.599086] hid-generic 0003:145F:0232.0005: input,hidraw3: USB HID v1.11 Gamepad [HJC Game Trust GXT Gamepad] on usb-0000:00:14.0-12/input0
```

```
sudo cat /sys/kernel/debug/usb/devices
T:  Bus=01 Lev=01 Prnt=01 Port=11 Cnt=02 Dev#=  4 Spd=12   MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=145f ProdID=0232 Rev= 1.14
S:  Manufacturer=HJC Game
S:  Product=Trust GXT Gamepad
C:* #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
E:  Ad=02(O) Atr=03(Int.) MxPS=  64 Ivl=10ms
E:  Ad=81(I) Atr=03(Int.) MxPS=  64 Ivl=10ms
```

```
sudo cat /sys/kernel/debug/usb/devices
T:  Bus=01 Lev=01 Prnt=01 Port=11 Cnt=02 Dev#=  4 Spd=12   MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=145f ProdID=0232 Rev= 1.14
S:  Manufacturer=HJC Game
S:  Product=Trust GXT Gamepad
C:* #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
E:  Ad=02(O) Atr=03(Int.) MxPS=  64 Ivl=10ms
E:  Ad=81(I) Atr=03(Int.) MxPS=  64 Ivl=10ms
```

I tried installing xboxdrv and messing around with it, it did't work. So for now I am sticking to standard xpad.
One thing I notice is that my controller is not being loaded with the xpad driver when I plug it in, instead it is using the usbhid driver. I don't know if that is normal or not. So I also tried doing: sudo rmmod usbhid && sudo modprobe -v usbhid "quirks=0x145F:0x0232:0x0004" to blacklist my device from usbhid and when I connected it it was indeed loaded with the xpad driver, but it didn't result in the controller working as I expected either.
I would take any comments, advice, or possible things to try. Also if you see anything weird in any of the outputs or would benefit from having more information I am happy to provide it.

Thank you all in advance.
Gastón.

**Comment by kisak-valve** [comment]
Hello @harogaston, are you still experiencing this issue on an up to date system? Maybe give the script in https://askubuntu.com/questions/1214046/trust-controller-in-x-mode-seen-but-gives-no-input a try after adapting d.idVendor and d.idProduct to your controller's usbid.

**Comment by harogaston** [comment]
This is an old post. This issue is resolved for me now.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
