### ISSUE TITLE
Popover Menu Remains Open

### ISSUE THREAD

**Issue by mmstick** [ValveSoftware/steam-for-linux#5802]
![screenshot from 2018-09-30 19-49-19](https://user-images.githubusercontent.com/4143535/46266113-f1536a80-c4e9-11e8-877b-a443d6c19582.png)

#### Your system information

* Steam client version: Sep 26 2018 
* Distribution: Pop!_OS 18.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The popover menus from the Steam client are often completely detached from the client itself, and cannot be clicked on, nor hidden when minimizing the client's main window. They also remain above any other windows on the screen.

#### Steps for reproducing this issue:

1. Click on any menu item
2. Move the steam client, click out of it, and/or minimize it.

**Comment by kisak-valve** [comment]
Hello @mmstick, this issue is already being tracked at #5724. Closing as a duplicate.
