### ISSUE TITLE
[Feature Request] Allow proton even on games distributing Linux version

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/steam-for-linux#5803]
This option could potentially improve the experience with games that are:
- falsely advertising Linux versions (i.e. [Cortex Command](https://store.steampowered.com/app/209670/Cortex_Command/)),
- whose Linux ports are limited in features / are outdated (i.e. [Arma 3](https://store.steampowered.com/app/107410/Arma_3/)),
- or are otherwise broken in weird ways that cause the game to be unplayable (i.e. [Unturned](https://store.steampowered.com/app/304930/Unturned/) / [Counter-Strike: Global Offensive](https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/))

**Comment by kisak-valve** [comment]
Hello @kiroma, this feature request is already being tracked at #5638. Closing as a duplicate.
