### ISSUE TITLE
Top left 64x32 rectangle (from 2013) appears again

### ISSUE THREAD

**Issue by pttoth** [ValveSoftware/steam-for-linux#5807]
#### Your system information

* Steam client version (build number or date): latest version at 2018, oct 2.
* Distribution (e.g. Ubuntu): Linux Mint - Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
- Phantom 64x32 window appears in the top left corner of the screen, when auto-login to friends is disabled and the signed-out Friends window is opened first.
- It doesn't appear if I open another steam window first (e.g.: Library) and then Friends
- Disappears, when I close Steam.
the rectangle looks to be the same from this issue: https://github.com/ValveSoftware/steam-for-linux/issues/2170

#### Steps for reproducing this issue:
1. set favorite steam window to Friends
2. set steam to not sign-in automatically to Friends on startup
3. restart Steam
note here, that Friends window doesn't automatically appear (it does, when auto sign-in is enabled)

4a. open Friends window first through the Steam icon in system tray.
note here, that when the signed-out Friends window appears, the phantom window also appears in the top left corner

4b1. open Library window first
note here, that the phantom rectangle doesn't appear
4b2. open signed-out Friends window second
note here, that the phantom rectangle still doesn't appear

**Comment by kisak-valve** [comment]
Hello @pttoth, can you check if the uninitialized window has the same properties as is described in #5584?

**Comment by pttoth** [comment]
- **xwininfo** returned:

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x520006d (has no name)

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 64
  Height: 24
  Depth: 24
  Visual: 0x9f
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x520006c (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: yes
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+0  -1536+0  -1536-876  +0-876
  -geometry 64x24+0+0

- **xprop** returned:

_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_TRANSIENT_FOR(WINDOW): window id # 0x5200043
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MENU
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_CLASS(STRING) = "Steam", "Steam"

**Comment by kisak-valve** [comment]
Thanks @pttoth, this is a close enough match to consider this a duplicate. Transferred to https://github.com/ValveSoftware/steam-for-linux/issues/5584#issuecomment-426308792.
