### ISSUE TITLE
Blank changelog when notified of update

### ISSUE THREAD

**Issue by mozai** [ValveSoftware/steam-for-linux#5810]
#### Your system information
* Steam version: previous to Oct 2 2018  (updating it is when the error happens, difficult to pin)
* Linux distro: Ubuntu 18.04.1
* Steam beta? Yes
* Checked for system updates?  Yes, and often.

#### Please describe your issue in as much detail as possible:
How to reproduce: Leave Steam running long enough to be notified of a Steam Client update.
What I saw:  https://i.imgur.com/4kAhMHe.png
What I expected: this dialog box used to show me a changelog, now it's a blank dark-blue rectangle.
This has been going on for a few weeks of updates, and at least [one other person](https://steamcommunity.com/app/221410/discussions/0/3220528325741733824/) has seen this behaviour.

#### Steps for reproducing this issue:
1. Leave Steam Client running.
2. Wait.
3. "A Steam client update has been downloaded" notification appears on its own.

**Comment by kisak-valve** [comment]
Hello @mozai, this issue is already being tracked at #5789. Closing as a duplicate.
