### ISSUE TITLE
Steam failing to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by stuartlangridge** [ValveSoftware/steam-for-linux#5811]
#### Your system information

* Steam client version (build number or date): 
steam-launcher deb 1.0.0.52
* Distribution (e.g. Ubuntu): 
Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No]
I'm not sure. I'm in the beta to get Proton, but I don't know if that's the client beta
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:

Launching steam from the command line prints an error and exits:

```
$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
$
```

I've tried moving `pinned_libs` out of the way, as per @kisak-valve's suggestion in https://github.com/ValveSoftware/steam-for-linux/issues/5463, but it didn't help.

**Comment by kisak-valve** [comment]
Hello @stuartlangridge, can you verify that any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

**Comment by stuartlangridge** [comment]
@kisak-valve I can't test that specific example (because installing `mesa-utils:i386` will remove `mesa-utils` and `mate-tweak`), but I've tried running the i386 version of a game (not from Steam; TheMaitreD, built with Unity), and that worked fine (as did its x86_64 version).

**Comment by stuartlangridge** [comment]
After a reboot, this problem seems to have resolved itself; I appreciate that this isn't very helpful, though. I'll close this issue, but if there's any more information I can provide then do reopen it and I'll try to.
