### ISSUE TITLE
Client Not Launching

### ISSUE THREAD

**Issue by Trumpy** [ValveSoftware/steam-for-linux#5812]
#### Your system information

* Steam client version (build number or date): 1.0.054
* Distribution (e.g. Ubuntu): pop!_os 4.15.0-36-generic Nvidia gpu driver: 396.24
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible: 
Steam doesn't launch the actual client. Only the login. Nothing happens after that, I'm forced to kill the process.
https://gist.github.com/Trumpy/cb6f8ab31d48b8bab14cd4f367856914
#### Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/): 
 I expected it to launch the client where I can see the game library.
#### Steps for reproducing this issue:

1. Install Steam through pop!_os repo or pop!_os store
2. Launch Steam through terminal or traditional way
3.

**Comment by kisak-valve** [comment]
Hello @Trumpy, can you verify that any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

**Comment by kisak-valve** [comment]
Hello @Trumpy, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
