### ISSUE TITLE
Star Control Origins fail to start

### ISSUE THREAD

**Issue by jeff29t** [ValveSoftware/steam-for-linux#5813]
* Steam client version (build number or date): sep 8 2018 , à 19:21:25
* Distribution (e.g. Ubuntu): ubuntu 18.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?:  Yes
* CPU: AMD A10 9700
* GPU: AMD RX 580
* Driver: amdgpu-pro 18.30 

I was trying to play Star Control Origins (271260).
The game start correctly, until i try to launch a saved game.
After that the system freeze , i must kill the program.

#### Steps for reproducing this issue:

1. Launch the game
2. Try to launch a saved game

**Comment by kisak-valve** [comment]
Hello @jeff29t, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/1692.
