### ISSUE TITLE
[security] possible data breach: wallet code and taiwan based (+88) mobile phone scam

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#5814]
I bought a wallet code, did input it, and a very fews hours later I was the target of a taiwan based (+88) phone scam.
Since I bought a wallet code for my mobile phone subscription too, it may not be valve but my mobile phone network provider which has a data breach.
I got rid of the full phone number, but I may go to the police (they have full access to my mobile phone history)

**Comment by kisak-valve** [comment]
Hello @sylware, account issues including this should go to Steam Support.

Closing as out-of-scope for the steam-for-linux issue tracker.

**Comment by sylware** [comment]
done.
