### ISSUE TITLE
content servers unreachable

### ISSUE THREAD

**Issue by ashtonflinders** [ValveSoftware/steam-for-linux#5816]
Ubuntu 16.04 LTS
* tried both with a standard apt install and from .deb
* not a firewall issue! (I am behind a wall, but I have had IT monitor traffic and they see no blocks. I have also tried with a mac behind the wall and it works, and the Ubuntu box outside of the wall and it doesnt work).

Issue #1
When starting steam I get a connection error;
"Could not connect to the Steam network."

if I button mash retry connection a dozen times, it WILL connect

Issue #2
Once I am actually connected I can not download any content, and always get the;
"content servers unreachable" message. changing servers does not do anything.

everything seems to start up ok....
$steam
Running Steam on ubuntu 16.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-10-05 17:45:28] Startup - updater built Oct 5 2018 19:11:49
[2018-10-05 17:45:28] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
[2018-10-05 17:45:28] Verifying installation...
[2018-10-05 17:45:29] Verification complete

(does not make a difference if I am signed up for beta or not)

pastebins of possibly relevant logs;

appinfo_log.txt
https://pastebin.com/msP68AzX

content_log.txt
https://pastebin.com/FytG1Hnb

connection_log.txt
https://pastebin.com/qFVSjfHJ

I have a pair of HTC Vive goggles that have been sitting in a box for 4 months now because I havent found a solution for this. This is a work-related machine and I am trying to do some VR dev in my free time. Any help would be really really really appreciated!

-ashton

**Comment by byte1024** [comment]
Well, it doesn't look like its Steam servers as this is what I get from a server you get 100000ms on

```
nmap -p 27020 cm01-ord.cm.steampowered.com

Starting Nmap 7.60 ( https://nmap.org ) at 2018-10-06 14:39 EDT
Nmap scan report for cm01-ord.cm.steampowered.com (162.254.193.6)
Host is up (0.025s latency).

PORT      STATE SERVICE
27020/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.56 seconds
```
`failed talking to cm (**timeout**/neterror - Invalid)`

compared to yours yesterday:
```
[2018-10-05 17:46:20] [0,0] Existing WebSocket ping data (cm01-ord.cm.steampowered.com:27020) results: 100000.0000ms + load 0.0000 (560 seconds ago)
```

It looks like Steam has a timeout at 100000ms - it seems to be the max since none of them in your log goes higher. But, its way too long a time so I'm guessing the connection being used here for the Steam application has a problem or something is causing it to have a problem.

It sounds like its an internet connection at work so it would be interesting if if happens on other computers there or not. If it doesn't, then something on the computer is breaking it. If other computers have the problem then something the IT has done I would think would be the cause.

So in my opinion its something on your end or the ISP. Since there's a wide variety of configurations especially with commercial, its difficult to say.

You can try pinging the server outside of Steam like I did. If it takes more than a second or so then its not Steam related.

**Comment by ashtonflinders** [comment]
I can see the host/port with nmap from the machine;
```
nmap -p 27020 cm01-ord.cm.steampowered.com

Starting Nmap 7.01 ( https://nmap.org ) at 2018-10-06 21:52 PDT
Nmap scan report for cm01-ord.cm.steampowered.com (162.254.193.6)
Host is up (0.0073s latency).
PORT      STATE SERVICE
27020/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.96 seconds
```
I dont think its a firewall/ISP issue, as it works with another computer on the network (on OSX) I think its an Ubuntu config issue, just dont know how....

**Comment by kisak-valve** [comment]
Hello @ashtonflinders, just a random guess here, but does your system have `libnss-resolve:i386` and if not, does adding it make a difference?

When you were switching between the distro-provided and Valve-provided steam package, did you apt purge the previous package and move/remove `~/.steam` and `~/.local/share/Steam` before adding the other one?

**Comment by byte1024** [comment]
Not ideal but another solution might be to do a clean install (after backup) of the OS and Steam or add/put in another drive and do another install of the OS and Steam etc. Sometimes things get so unknown hard to figure out that its just faster.

**Comment by ashtonflinders** [comment]
Yes, purged and removed local directories between installs.

Yes, installed lines, but no help.

@byte1024, this is on my office workstation - an 8 drive raid 6 with 50 tb and a complicated LVM setup. Reinstalling the OS isn't a choice for me.

**Comment by ashtonflinders** [comment]
This is what I dont understand, and makes me think it has to be a a steam config issue...
**from the steam connection log;**
'''
[2018-10-07 12:11:17] [0,0] PingWebSocketCM() (CM04-LON.cm.steampowered.com:27021) failed talking to cm (timeout/neterror - Invalid)
'''
**but, from the same system;**
'''
nmap -p 27021 CM04-LON.cm.steampowered.com

Starting Nmap 7.01 ( https://nmap.org ) at 2018-10-07 12:15 PDT
Nmap scan report for CM04-LON.cm.steampowered.com (162.254.196.84)
Host is up (0.0015s latency).
PORT      STATE    SERVICE
27021/tcp filtered unknown
Nmap done: 1 IP address (1 host up) scanned in 0.43 seconds
'''
**and**
'''
ping -p 27021 CM04-LON.cm.steampowered.com
PATTERN: 0x270201
PING CM04-LON.cm.steampowered.com (162.254.196.84) 56(84) bytes of data.
64 bytes from 162.254.196.84: icmp_seq=1 ttl=114 time=151 ms
64 bytes from 162.254.196.84: icmp_seq=2 ttl=114 time=150 ms
^C
--- CM04-LON.cm.steampowered.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 150.650/150.873/151.097/0.448 ms
'''

**Comment by ashtonflinders** [comment]
Adding the CS servers directly to the config.vdf file fixed the download issue (although its intermittent). Just make sure you make the file 555 so it doesnt get overwritten.
