### ISSUE TITLE
Steam crashes when launching Proton games in a chroot

### ISSUE THREAD

**Issue by PureTryOut** [ValveSoftware/steam-for-linux#5823]
#### Your system information

* Steam client version (build number or date): Built September 8 2018
* Distribution (e.g. Ubuntu): Host Gentoo Linux, chroot Ubuntu Bionic
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes when trying to launch a game via Proton, according to the logs due to failing to connect to PulseAudio. However, besides the fact that native games can play audio via my hosts PulseAudio fine, Steam shouldn't even need it to run.

```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Failed to open digital audio driver Couldn't open OAL device.
crash_20181009162315_1.dmp[1940]: Uploading dump (out-of-process)
```

Since this is happening in a chroot, I'm guessing it's because of missing some mounted directories from the host system, but I can't really figure out which one.

#### Steps for reproducing this issue:

1. Set up an Ubuntu Bionic chroot with Steam and PulseAudio
2. Launch any Proton game

**Comment by kisak-valve** [comment]
Possibly related to #5669.

**Comment by PureTryOut** [comment]
The same symptons, but different error. I can't test the suggestion of adding the user to the audio group though because of it running in a chroot. Also the notion of maybe running on a XFS filesystem is not the case, as it's regular ext4.

Crash dump file: 
[crash_20181009161404_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2462147/crash_20181009161404_1.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in vgui2_s.so.

**Comment by h1z1** [comment]
Any update or anything further we can provide @kisak-valve  ?  Still an infuriating problem.  I remember ALSA used to be a problem but has worked for quite some time.

**Comment by PureTryOut** [comment]
I finally resolved this by setting `PULSE_SERVER="unix/run/user/1000/pulse/native"`, so I guess it failed to connect to PulseAudio after all.

**Comment by robert-scheck** [comment]
Please note that it's actually `PULSE_SERVER="unix:/run/user/1000/pulse/native"` (the `:` missing in the previous comment is quite important), otherwise Steam just crashes without any real error message (which is the only thing Steam seems to do quite well instead of working properly).

**Comment by h1z1** [comment]
fwiw Pulse wasn't available which is why it tried ALSA.  That too failed and steam segfaulted.    They still happen but I haven't hit the segfault crashing steam in at least the last few patches, guessing it was finanlly fixed too.
