### ISSUE TITLE
In-home streaming fails to operate between Linux host and Linux client "Unknown PSK Identity"

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/steam-for-linux#5824]
#### Your system information

* Steam client version (build number or date): 1536436120
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In home streaming used to work between my Gentoo Linux desktop and my Windows 7 VR system. After switching my VR system from Windows 7 to Gentoo Linux, in-home streaming stopped working.

I captured the interaction between the two via wireshark. Wireshark claims that an error code is being sent from the VR system to my desktop.

`TLSv1.2	73	Alert (Level: Fatal, Description: Unknown PSK Identity)`

I have a `localconfig.vdf` file on both systems, which reportedly contains the authentication data for in-home streaming:

https://codingrange.com/blog/steam-in-home-streaming-control-protocol

Interestingly, the AuthData required to make it work is only present on the system trying to connect, rather than on both systems. I suspect that a missing PSK on the new Linux install is the cause, but I didn't try manually editing the file to test that theory because I don't have the source code to check to see how it would behave.

I tried manually connecting to port 27036 on the host as shown there (with -tls1_2 included to ensure that it matches what I saw in wireshark), but I am getting `SSL alert number 115`. At a glance, the session captured by wireshark when using steam to try to connect to it and the session captured by wireshark when using openssl to connect look identical. I did try connect_remote in the console, although steam would automatically try to connect at start, only to have that SSL failure.

#### Steps for reproducing this issue:

1. Setup a Linux system running Steam
2. Setup a Windows system running Steam
3. Verify in-home streaming works from a Windows host to the Linux system.
4. Install Linux on the system with Windows.
5. Install steam on the system that previously had Windows.
6. Try again, and it fails.

If it is relevant, I tried out in-home streaming from the host when it ran Windows to the Linux desktop before setup a Steamlink. This time, I set up the Steamlink before trying in-home streaming with Linux on the host. This is also across subnets with firewall rules only allowing connection establishment in one direction. Those rules weren't a problem for the Windows host Linux client setup though.

**Comment by ryao** [comment]
@slouken @kisak-valve I got this working by launching steam on my Linux workstation (the client) with `LD_PRELOAD=/home/richard/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnssutil3.so:/home/richard/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libplc4.so:/home/richard/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libplds4.so:/home/richard/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnspr4.so:/home/richard/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnss3.so steam`, running `steam steam://open/console` and then doing a `connect_remote $IP:27036` command on the steam console. After doing this, I received a notification saying that it had connected and was able to stream "A Hat in Time".

There is some kind of incompatibility between what Steam expects from the steam runtime and what Gentoo provides. Gentoo is using 3.37.3. Is there any information that you could provide to me that would help me to debug this at downstream? For example, the libnss version that you used, a copy of the libnss sources that you used and a description of how you are exercising the library API.

Also, this seems to affect more than Gentoo clients. There is a decryption error when trying to use the Steamlink Android TV client that breaks the network test. Unfortunately, it is not quite so easy to swap out libnss there. There are a few other experiments that I could do (like swapping out libnss at the host to see if it helps), but I have a few other higher priority things preempting this. I would appreciate it if you could provide me with the information that I requested though so that I have it on the next time slice that I have available to look at this from downstream.

**Comment by ryao** [comment]
Actually, I just did a test without the `LD_PRELOAD` and for some reason unknown to me, this is now working. This is with steam client version 1539393410 on the client. The only remaining issue now is that it doesn't automatically recognize steam on a system on the other subnet like it did when that system ran Windows.

**Comment by darekols** [comment]
@ryao 
I got the same issue. Can you explain what do you mean by "test without the LD_PRELOAD"?

**Comment by cminnoy** [comment]
I also have a Linux host and Linux client for in-home streaming. Steam on the client side tells that I should log-into the host to play the game. Which is weird; if the client is a Windows machine I can perfectly play the games hosted on the Linux machine.

**Comment by darekols** [comment]
Linux host can easily stream games even with Proton runtime (which is amazing), but i could not figure out how to connect with Linux client. I ended up with Windows7 as a host (performance in some cases is better than Win10).

**Comment by ryao** [comment]
@darekols I forgot what I meant. Either stream is doing a LD_PRELOAD on the crypto library or I did in testing.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue (specifically with an encryption failure) on an up to date system?

It appears the issue in the opening post was resolved.

**Comment by kisak-valve** [comment]
Closing as outdated.
