### ISSUE TITLE
Steam shuts down when computer is put to sleep

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#5825]
#### Your system information

![image](https://user-images.githubusercontent.com/42655600/46711206-ffc12500-cc53-11e8-9296-ba48398c298e.png)
```
$ inxi -F
System:    Host: Think-Machinery Kernel: 4.15.0-36-generic x86_64 bits: 64 Desktop: Xfce 4.12.3
           Distro: Ubuntu 18.04.1 LTS
Machine:   Device: laptop System: LENOVO product: 2537WS8 v: ThinkPad T410 serial: N/A
           Mobo: LENOVO model: 2537WS8 serial: N/A BIOS: LENOVO v: 6IET75WW (1.35 ) date: 02/01/2011
Battery    BAT0: charge: 15.9 Wh 23.2% condition: 68.7/94.0 Wh (73%)
CPU:       Dual core Intel Core i5 M 520 (-MT-MCP-) cache: 3072 KB
           clock speeds: max: 2400 MHz 1: 2856 MHz 2: 2811 MHz 3: 2659 MHz 4: 2659 MHz
Graphics:  Card: Intel Core Processor Integrated Graphics Controller
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1440x900@60.06hz
           OpenGL: renderer: Mesa DRI Intel Ironlake Mobile version: 2.1 Mesa 18.3.0-devel - padoka PPA
Audio:     Card Intel 5 Series/3400 Series High Definition Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-36-generic
Network:   Card-1: Intel 82577LM Gigabit Network Connection driver: e1000e
           IF: enp0s25 state: down mac: f0:de:f1:49:0b:d2
           Card-2: Intel Centrino Advanced-N 6200 driver: iwlwifi
           IF: wlp3s0 state: up mac: 18:3d:a2:07:2c:a8
Drives:    HDD Total Size: 500.1GB (8.0% used)
           ID-1: /dev/sda model: CT500MX500SSD1 size: 500.1GB
Partition: ID-1: / size: 23G used: 18G (82%) fs: ext4 dev: /dev/sda1
           ID-2: /home size: 435G used: 20G (5%) fs: ext4 dev: /dev/sda2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 65.0C mobo: 0.0C
           Fan Speeds (in rpm): cpu: 4544
Info:      Processes: 287 Uptime: 2 days Memory: 1855.2/3743.1MB Client: Shell (bash) inxi: 2.3.56
```
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When closing the lid of my laptop Steam shuts down randomly. It leaves behind no error messages on the terminal either. It should not shut down automatically or at the very least it should leave a message. I've had games open during lid close (like TIS-100) and it crashes as well as soon as I play a sequence (I'm assuming it contacts steam to do a cloud save and it fails.
Here's a video demonstration of the shutdown: https://www.youtube.com/watch?v=vfXX7o2-CbA
Here is the terminal output from my tests: https://gist.github.com/Managor/eb497304f63cc72d7066df54660117a6

#### Steps for reproducing this issue:

1. Open Steam
2. Put laptop to sleep by closing the lid
3. Bring your laptop back from sleep

**Comment by Managor** [comment]
Haven't had this happen in a long time. I think it's worth closing. I think the new steam library beta warrants a good cleanup with all the old reports anyway.

**Comment by kisak-valve** [comment]
Closing per the last comment.
