### ISSUE TITLE
VAC server optout

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/steam-for-linux#5829]
I was talking to another Gentoo developer about the packaging for steam in Gentoo. He is one of the maintainers of the Gentoo steam overlay (similar to a repository) where the steam packaging currently lives. He and the other developer working on it have done a good job such that things work well with the steam runtime disabled in favor of distribution maintained libraries. However, there is a concern that this could upset VAC in a way that results in Gentoo users being banned. So far, this has not happened (to my knowledge), but VAC bans carry plenty of penalties beyond just being barred from VAC protected servers:

https://support.steampowered.com/kb_article.php?ref=4044-qdhj-5691

Would Valve implement a global optout that would allow users to opt out of network play on all VAC protected servers in all VAC protected games to ensure that there is no risk of a false positive? Also, could that include a  local opt out that distributions could enable when the steam runtime is disabled in favor of their own libraries while giving users an option to opt back in. In Gentoo, we could have a USE flag to control that.

**Comment by kisak-valve** [comment]
Hello @ryao, VAC in general is out-of-scope for this issue tracker. Please use [Steam Support](https://help.steampowered.com/en/).
