### ISSUE TITLE
select GPU?

### ISSUE THREAD

**Issue by ashtonflinders** [ValveSoftware/steam-for-linux#5830]
I have two nvidia GPUs in my Ubuntu box (16.04 LTS) (Quadro M4000 and Titan V). The M4000 is driving two ultra wide displays. When I run the Vive it shows up (in steamvr settings) as being controlled by the M4000, no matter which GPU it is actually plugged into.

I can not actually get a display out of the Vive, and want to try forcing it to use the Titan V, for debugging (the M4000 only has display ports, while the Titan has an hdmi). Is there a way (or config file) to set which GPU is used?

Anyway I can hard set it in the steamvr.vrsettings config file?

**Comment by kisak-valve** [comment]
Hello @ashtonflinders, this question fits better in the SteamVR-for-Linux issue tracker, so I've transferred it to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/142.
