### ISSUE TITLE
Steam crash if user have libdbusmenu-glib4:i386 installed

### ISSUE THREAD

**Issue by kassindornelles** [ValveSoftware/steam-for-linux#5832]
#### Your system information

* Distribution (e.g. Ubuntu): Elementary OS (Ubuntu 18.04 based) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crash if user have libdbusmenu-glib4:i386 installed on Elementary OS JUNO (Beta 2), but this issue probably can be reproduced on Ubuntu 18.04.1 too.

#### Steps for reproducing this issue:

1. Install libdbusmenu-glib4:i386 (sudo apt-get install libdbusmenu-glib4:i386)
2. Try to relaunch Steam
3. Client get stuck on the login screen.

**Comment by kisak-valve** [comment]
Hello @kassindornelles, this is a known issue.

Deleting `<steam folder>/ubuntu12_32/steam-runtime/pinned_libs_*` allows steam to regenerate the pinned library folders on the next run and automatically workaround this.

The steam folder is `~/.local/share/Steam` if you used the Valve-provided steam package, or `~/.steam` if you are using the distro-provided steam package.

**Comment by kisak-valve** [comment]
Hello @kassindornelles, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
