### ISSUE TITLE
Steam cloud/internet connection breaks after trying to join a CSGO community server

### ISSUE THREAD

**Issue by vitacell** [ValveSoftware/steam-for-linux#5833]
#### Your system information

* Steam client version (build number or date): September 8 2018 19:21:25 (API v018) (1536436120)
* Distribution (e.g. Ubuntu): Ubuntu18.04-64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I got really tired with CSGO, I just want to run it and play, and not trying to fix it by myself. Look, the game works well when I join official servers (Casual, Competitive...)(it never fails), but when I try to join a community server, I can do it only 1 times of 5. The other 4 times it will fail. Now, after a big CSGO update (the one with new main menu), things got worse (lagging chat, fps drop, can not to run any workshop map, and now can not to connect my favourite community servers).
When I am in CSGO I try to connect to a community server or just run local workshop map, CSGO tryes to load the map and then exits to the main menu, after that it will fail to connect to anything, even official servers (Competitive, Casual...), so if I want to try to connect to a community server or official servers (Competitive, Casual...) again, or even to play online game like "Broforce", I MUST to restart steam to try it again (because Steam Cloud loses connection too). When I restarted Steam, I run CSGO and I can to connect official servers again, the problem appears when I try to run unofficial servers (community servers, workshop)(it breaks steam, steam cloud connection, but I still can see my fiends list connected). Workshop worked fine before the big update. Community servers worked mostly fine before the big update.This problem is really annoying for me.

#### Steps for reproducing this issue:

1. Run Arch, Ubuntu, Void...64bits (I had this bug time ago, when I was on other GNU/Linux distros).
2. Run Steam.
3. And then run CSGO, try to join some community server (I usually try to connect to "retake" servers without addons, if you could to join a server, after that try to connect to an official server)

**Comment by vitacell** [comment]
Hi, I can see where is the problem, after the "big update" the game server joining doesn't work fine with Nouveau driver anymore (the game works fine itself with that driver). With Nvidia driver game works fine (except when you join a server, and server has addons, it starts downloading and hangs at 0%, here is no cancel button in-game). So the server joining has problem with Nouveau driver.

**Comment by kisak-valve** [comment]
Hello @vitacell, it may be worthwhile to also bring this to the attention of your video driver vendor.

**Comment by karolherbst** [comment]
@kisak-valve I don't see how that could be in any way driver related, except the game does some white/black listing depending on features or drivers? Those clearly sound like game bugs to me, even if a change within a GPU driver may cause that.

**Comment by vitacell** [comment]
Guys this issue happens again even with NVIDIA driver. Why do I must going back to MS-Windows to play a game which supposed to support GNU/Linux same way as MS-Windows?

**Comment by vitacell** [comment]
Since my last message here, I am using Windows 7 64 bits for playing games, and I never had similar problems in Windows 7. So, how do I must to play Valve games on GNU/Linux if those games do not work properly?

**Comment by kisak-valve** [comment]
Hello @vitacell, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
