### ISSUE TITLE
CS:GO Linux Issues

### ISSUE THREAD

**Issue by Crazily** [ValveSoftware/steam-for-linux#5836]
#### Your system information

* Steam client version (build number or date): Oct 13 2018 
* Distribution (e.g. Ubuntu): Fedora 28 (Doesn't matter, Does it on ubuntu too)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When you join a competitive game. If you restart your computer or your computer crashes when you try to get back in it says you don't have the authkey or authtoken or whatever and it won't let you reconnect to the game.

Another issue is the community server browser doesn't work. And if you do connect to a community server where it downloads non-workshop items it never works. Gets stuck indefinitely. This one is big enough of a problem that someone has made a fix (https://github.com/ericek111/linux-csgo-downloadfixer) that fixes the issue and it does work  but it writes to the games memory and that could cause a vac ban)

#### Steps for reproducing this issue:

1. Open cs:go and join a comp
2. Restart pc / pc crash
3.  Try to join comp back, It won't let you.

Steps for second Issue:
Try to join a community server

The list doesn't work

Get friend to send server ip

Connect to server

If the server has to download stuff it gets stuck on downloading it.

**Comment by kisak-valve** [comment]
Hello @Crazily, CS:GO issues are being tracked in the csgo-osx-linux issue tracker. In general, multi-issue issue reports are bad for any issue tracker, please have only one issue per issue report.

The first issue could be related to https://github.com/ValveSoftware/csgo-osx-linux/issues/1293.

Community server list works here in a quick test (on Gentoo Linux).

The download issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1568.

Closing as out-of-scope for the steam-for-linux issue tracker.
