### ISSUE TITLE
Issues Installing and Running SteamPlay Games

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/steam-for-linux#5837]
#### Your system information

* Steam client version (build number or date): Oct 13
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When attempting to download a steamplay game, the install will get stuck in the "Creating local game files". If I click cancel on this, it will uninstall the game. While this dialog menu is up, it is downloading the game. If I force kill steam and bring it back up, it'll complete the download, but then when I try to run it, a message pops up saying "Failed to request product key from Steam". In my case, this was Assassin's Creed II.

I've also tried this case with the Beta client, and the same thing is happening. Proton 3.16 is being used.

#### Steps for reproducing this issue:

1. Attempt to download Assassin's Creed II
2. Creating local game files dialog will get stuck. Using Task Manager, kill steam. 
3. Bring steam back and wait for the download to complete
4. Attempt to launch the game. At this point, will fail with "Failed to request product key from Steam" dialog error.

I tried Acreed Black Flag and that one is installing now. So possibly something isolated to games that need the key server?

**Comment by kisak-valve** [comment]
Hello @d10sfan, issues with games run with Proton are being tracked in the Proton issue tracker. In this case, Assassin's Creed II is already being tracked at https://github.com/ValveSoftware/Proton/issues/190 and there's a possibly related steam issue at #212. Closing as a duplicate.
