### ISSUE TITLE
Unable to launch csgo

### ISSUE THREAD

**Issue by ayushrockzz** [ValveSoftware/steam-for-linux#5838]
When i try to launch csgo , it shows me a meaasge : "unable to load versions from stem.inf". I tried to valiidate game files......but they r all successfully validated....and also steam client is up to date.....still it is showing the same message....please help me reguarding this.....and also the operating system that i use is lubuntu 18.04.....

**Comment by kisak-valve** [comment]
Hello @ayushrockzz, issues with CS:GO are being tracked in the csgo-osx-linux issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/csgo-osx-linux/issues/1845.
