### ISSUE TITLE
Proton version number not correctly parsed

### ISSUE THREAD

**Issue by JacobSvenningsen** [ValveSoftware/steam-for-linux#5839]
When choosing the version of proton in the settings, 3.7 is listed above version 3.16, which is a higher version. It would seem the versions are sorted lexicographically. This gives users the impression that 3.7 is newer, even though it isn't.

#### Steps for reproducing this issue:
1. Open settings dialog and select settings for Steam Play
2. Enable Steam play for all titles
3. Change compatibility tool
4. Proton 3.7 listed above 3.16, which is newer

**Comment by byte1024** [comment]
Unless they just changed this, I don't see this. For me .16 is above .7

I have:
3.16-1 beta
3.7-8
3.7-8 beta

**Comment by kisak-valve** [comment]
Hello @JacobSvenningsen, are you still experiencing this issue on an up to date system?

**Comment by JacobSvenningsen** [comment]
List seems to be sorted in descending order, as expected
