### ISSUE TITLE
Steam doesn't launch after fresh install

### ISSUE THREAD

**Issue by Mati20187** [ValveSoftware/steam-for-linux#5840]
#### Your system information

* Steam client version (build number or date): 1.0.0.56-1
* Distribution (e.g. Ubuntu): Antergos
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

I've installed steam on my fresh install of Antergos with XFCE DE but it doesn't run. I've tried running both native and runtime versions. When clicking on the icons in menu, nothing happens, but when trying to run from terminal, they return errors:

```
[mati@pc ~]$ steam
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mati/.local/share/Steam/steam.sh: line 823: /home/mati/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory`

`[mati@pc ~]$ steam-native
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
STEAM_RUNTIME is disabled by the user
```
I've tried following methods to fix this problem, but none of them worked:
- rebooting system
- updating system
- reinstalling steam
- trying to enable steam runtime `STEAM_RUNTIME=1 steam`

I have proprietary Nvidia drivers installed, my graphics card is GTX 960.

**Comment by dearlygparted** [comment]
On Arch Linux, `steam` is an alias for `steam-runtime` which uses `LD_PRELOAD` to override problematic libraries. If you want to run Steam with the default launch script, you have to use `/usr/lib/steam/steam`

All 3 methods for launching Steam (the 2 aforementioned methods as well as `steam-native`) are working without issue for me on vanilla Arch. 

Make sure you've followed the instructions on the [Arch Wiki](https://wiki.archlinux.org/index.php/Steam#Installation).

Refer to [Steam troubleshooting](https://wiki.archlinux.org/index.php/Steam/Troubleshooting) for more help.

**Comment by Mati20187** [comment]
When I try to run `/usr/lib/steam/steam` I get this:
`[mati@pc steam]$ steam
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mati/.local/share/Steam/steam.sh: line 823: /home/mati/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
`

**Comment by Mati20187** [comment]
> On Arch Linux, `steam` is an alias for `steam-runtime` which uses `LD_PRELOAD` to override problematic libraries. If you want to run Steam with the default launch script, you have to use `/usr/lib/steam/steam`
> 
> All 3 methods for launching Steam (the 2 aforementioned methods as well as `steam-native`) are working without issue for me on vanilla Arch.
> 
> Make sure you've followed the instructions on the [Arch Wiki](https://wiki.archlinux.org/index.php/Steam#Installation).
> 
> Refer to [Steam troubleshooting](https://wiki.archlinux.org/index.php/Steam/Troubleshooting) for more help.

When I try to run `/usr/lib/steam/steam` I get this:
`[mati@pc steam]$ steam
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on antergos  64-bit
/home/mati/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mati/.local/share/Steam/steam.sh: line 823: /home/mati/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
`

**Comment by kisak-valve** [comment]
Hello @Mati20187, did you update your nvidia driver version since your last restart? If the running nvidia kernel module version does not match the userspace version, it can stall there.

**Comment by kisak-valve** [comment]
Can you run `pacman -Q nvidia nvidia-dkms nvidia-utils lib32-nvidia-utils` and verify the versions match (xxx.xx)? I have a hunch that you opt-ed into the testing repo at some point, but missed adding the corresponding multilib-testing repo.

**Comment by Mati20187** [comment]
> Can you run `pacman -Q nvidia nvidia-dkms nvidia-utils lib32-nvidia-utils` and verify the versions match (xxx.xx)? I have a hunch that you opt-ed into the testing repo at some point, but missed adding the corresponding multilib-testing repo.

`[mati@pc ~]$ pacman -Q nvidia nvidia-dkms nvidia-utils lib32-nvidia-utils
nvidia 410.57-6
error: package 'nvidia-dkms' was not found
nvidia-utils 410.57-3
error: package 'lib32-nvidia-utils' was not found
`
I've checked lib32 packages a hundred times but somehow I missed lib32-nvidia-utils.
After installing it everything works perfectly. Thanks so much for help!

**Comment by kisak-valve** [comment]
Thanks, closing as this was a system config issue.
