### ISSUE TITLE
Steam cannot detect generic controllers after attempting to upload configurations.

### ISSUE THREAD

**Issue by BadRAM** [ValveSoftware/steam-for-linux#5843]
#### Your system information

* Steam client version (build number or date): Oct 14 2018
* Distribution: Solus 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
upon connecting a new controller on linux, the controller is detected and the bindings menu under general controller settings shows all inputs unbound. input is detected correctly and bindings can be set, but once I try to save/upload them with a name, as prompted, it returns to the general controller settings menu and does not show any connected controllers. restarting steam or the system does not bring back the controller.

I have tested this with 2 different controllers from different manufacturers. both continue to function in non steam apps after being 'lost' by steam. I have used both these controllers with steam bpm on windows in the past without issue.

#### Steps for reproducing this issue:

1. connect a new generic gamepad that has never been used on the system before
2. create an input profile in the controller settings menu
3. press the upload button
4. controller will no longer be recognized by steam

**Comment by kisak-valve** [comment]
Hello @BadRAM, are you still experiencing this issue on an up to date system?

**Comment by BadRAM** [comment]
Hello @kisak-valve, I don't have any Linux machines to test on anymore, sorry.

**Comment by kisak-valve** [comment]
That's okay. Thanks for the feedback.

I'm going to close this issue as outdated. If anyone else comes across this issue, they can open a new issue referencing this one and we can continue pondering the issue from there.
