### ISSUE TITLE
Big Picture Mode reverts to 1920x1080 dimensions on game exit.

### ISSUE THREAD

**Issue by Aimela** [ValveSoftware/steam-for-linux#5848]
#### Your system information

* Steam client version (build number or date): Oct 13, 2018
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've been having this issue for quite a while now, where Big Picture Mode will revert to 1920x1080 when exiting a game. A screenshot of the result:
![screenshot_20181018_202830](https://user-images.githubusercontent.com/14956751/47194418-71fcce00-d314-11e8-9064-3300aadc504e.png)

Personally, it doesn't quite feel like the Steam's Linux client is tested in resolutions above 1920x1080 and refresh rates above 60Hz to me.

#### Steps for reproducing this issue:

1. Start Big Picture Mode.
2. Launch game.
3. Close game window.

Some specs:
DE: KDE Plasma
CPU: i7-6700k
GPU: GTX 1080 with proprietary drivers at version 410.57
Monitors: Acer XG270HU and Acer P215H(both set to 2560x1440@144Hz and 1920x1080@60Hz respectively)

**Comment by kisak-valve** [comment]
Hello @Aimela, if you completely close Steam, then run steam from a terminal with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 steam`, does that workaround the issue?

**Comment by Aimela** [comment]
> Hello @Aimela, if you completely close Steam, then run steam from a terminal with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 steam`, does that workaround the issue?

That seems to have helped. I also added "export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0" as a line in /usr/bin/steam and that seems to have persistently fixed the issue.
