### ISSUE TITLE
DS4 Controller recognised in big picture but controller configuration does not apply in game

### ISSUE THREAD

**Issue by ibrokemypie** [ValveSoftware/steam-for-linux#5849]
#### Your system information

* Steam client version (build number or date): Oct 13 2018
* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Steam big picture detects my DS4 controller connected over bluetooth and allows me to navigate. In game however, I can choose configuration for my controller to emulate an xbox controller but it doesn't actually apply, even with forced on.

#### Steps for reproducing this issue:

1.  Connect DS4 controller over bluetooth
2. Start steam big picture
3. Enable DS4 configuration
4. Start a game (eg burnout paradise)
5. Choose a configuration (eg ds4 to xbox)
6. Try to use controller

**Comment by maxrp** [comment]
Just solved a nearly identical issue myself. Only surface level difference was that I was attempting to first get the ds4 controller working via USB connection to keep the bluetooth subsystem out of the picture.

The resolution for me came by adding my user to the `input` group, after I compared `lsof` on a working system and found that on the working configuration the user was able to read and write to the `/dev/input/event*` objects created by the ds4 controller.

Please let me know if any other details would be helpful.

**Comment by alfonsoler** [comment]
Hello! Maybe that could be a solution for my question here: https://github.com/ValveSoftware/steam-for-linux/issues/5911
Could you explain how to use that lsof command and how to add the user to the input in this case?

**Comment by elimpnick** [comment]
I'm having the same issue, but adding myself to the `input` group didn't help.  The controller works in Big Picture mode and I  can navigate the library and such, but as soon as I start a game, it is not detected.  It is detected if I plug the DS4 controller via USB cable.  It doesn't matter if `PlayStation configuration support` is enabled or not.

**Comment by alfonsoler** [comment]
Here you got the solution: https://github.com/ValveSoftware/steam-for-linux/issues/5911

**Comment by elimpnick** [comment]
I'm on Arch Linux, there isn't a `steam-devices` to install.  What I tried is extract both `60-steam-vr.rules` and `60-steam-input.rules` from Ubuntu's `steam-devices` package in `/etc/udev/rules.d` than ran `udevadm control --reload-rules`.  Didn't work.  

So moved the Arch Linux `steam` package's installed `70-steam-vr.rules` and `70-steam-input.rules` out of `/lib/udev/rules.d/` in case it conflicted with the ones from Ubuntu's `steam-devices` package and reran `udevadm control --reload-rules.`  Didn't work.  Figured I try a full reboot.  Nope.  

Again, the controller works over BT in Big Picture mode, but not in game.  It works in game only if connected over USB.

**Comment by namtsui** [comment]
Does DS4 work in your game if you plug it in? I experienced similar symptoms with the XBox 360 USB controller being recognized in Big Picture mode when I tap the buttons, but it did not work in-game. This was on Gentoo. There are two options to fix it. Either add your user to the input group (as noted by others in this thread) or create a games group.

Here are the details:
* controllers
** easy way
add user to input group for permissions to read /dev/input/js0
This is insecure.
** correct way
Add udev rules /etc/udev/rules.d/99-joystick.rules
```
SUBSYSTEMS=="input", ATTRS{name}=="Microsoft X-Box 360 pad", GROUP="games", MODE="0660"
DRIVERS=="xpad", GROUP="games", MODE="0660"
SUBSYSTEMS=="input", ATTRS{name}=="Sony Computer Entertainment Wireless Controller", GROUP="games", MODE="0660"
DRIVERS=="sony", GROUP="games", MODE="0660"
```
Now /dev/input/js0 has group games
Add user to group games
Optional: add user to plugdev group
Optional: /etc/conf.d/modules xpad joydev usbhid (auto loaded if using usb keyboard or mouse)

**Comment by elimpnick** [comment]
@namtsui, from my post above _"It is detected in game only if I plug the DS4 controller via USB cable."_, 

Therefore, yes, it works in the game when I plug it in.

**Comment by Whitetyphon** [comment]
@elimpnick @ibrokemypie I have found a workaround for a similar issue I've been having while trying to troubleshoot my issue #6409

The gist of it is that having more than 2 /dev/input/jsx devices connected at game launch time is causing some kind of issue with maybe creation or hooking of the emulated controller.

So this means that you must only have the ds4 controller connected as a /dev/input/jsx device and no other device connected that is identified as a /jsx device, other than the xbox 360 gamepad that spawns as a consequence from ds4 to 360 pad emulation

My issue was because my keyboard was the device being detected as an additional /dev/input/jsx.

Maybe @Plagman could could look into this

**Comment by kisak-valve** [comment]
Hello @ibrokemypie, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
