### ISSUE TITLE
X Error of failed request: Bad Value

### ISSUE THREAD

**Issue by ProfessorChill** [ValveSoftware/steam-for-linux#5850]
#### Your system information

* Steam client version (build number or date): Fresh Install (pacman says 1.0.0.56-1)
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Launched Steam

#### Steps for reproducing this issue:

1. sudo pacman -Syu
2. steam
3. ???

Graphics Driver: nvidia
Method tried: env LD_PRELOAD="/usr/lib32/libstdc++.so.6.0.25 /usr/lib32/libxcb.so.1.1.0 /usr/lib32/libgcc_s.so.1 /usr/lib32/libgpg-error.so.0" LIBGL_DEBUG=verbose LD_LIBRARY_PATH="$LD_LIBRARY_PATH /usr/lib/nvidia" ~/.steam/bin/steam

Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
/home/lunakiraizarus/.local/share/Steam/steam.sh: line 823: /home/lunakiraizarus/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
[2018-10-19 10:18:22] Startup - updater built Aug 25 2018 00:28:48
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
SteamUpdateUI: An X Error occurred

**Comment by kisak-valve** [comment]
Possibly related to #5840.

**Comment by kisak-valve** [comment]
Hello @ProfessorChill, can you run `pacman -Q nvidia nvidia-dkms nvidia-utils lib32-nvidia-utils` and verify the versions match (xxx.xx)? I have a hunch that you opt-ed into the testing repo at some point, but missed adding the corresponding multilib-testing repo.

**Comment by ProfessorChill** [comment]
Hi @kisak-valve I will be running it when I get home, I ran out the door. I did opt into the testing repo but not the multilib testing repo, this could be the issue.

Thanks for the advice.

**Comment by ProfessorChill** [comment]
I have nvidia nvidia-utils lib32-nvidia-utils

I opted into both testing branches and ran `sudo pacman -Syu` to ensure I had the most recent packages.

I tried to use nvidia-dkms just encase it was a driver issue however that resulted in me having no UI whatsoever in any program.

I then re-installed nvidia nvidia-utils lib32-nvidia-utils.

When I rebooted (which I reboot between all of these steps.) I tried to run steam and I encountered the same error.

Here is the current output of the command you had sent.
```
nvidia 410.57-6
error: package 'nvidia-dkms' was not found
nvidia-utils 410.57-3
lib32-nvidia-utils 410.66-1
```

**Comment by kisak-valve** [comment]
So, the version mismatch between 32 bit and 64 bit nvidia-utils is definitely a problem and needs to be addressed and matching the versions you listed against https://www.archlinux.org/packages/?q=nvidia hint that you're not using the testing repo.

It doesn't matter if you're using the testing repos or not, just that those versions match each other.

**Comment by ProfessorChill** [comment]
Sorry for the delay in my response, This did fix many errors I was having outside of this (thank you very much for that) however, I now have another error showing similar to the one referenced above.
```
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/lunakiraizarus/.local/share/Steam/steam.sh: line 823: /home/lunakiraizarus/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
[2018-10-21 10:31:56] Startup - updater built Aug 25 2018 00:28:48
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
I hope this helps in solving this issue.

**Comment by ProfessorChill** [comment]
CLOSED AS A SYSTEM CONFIG ISSUE,
After solving the initial error, I found that I never re-installed lib32-nvidia-utils.
Thank you for your help and support.
