### ISSUE TITLE
steamwebhelper.sh: line 5:  8279 Segmentation fault

### ISSUE THREAD

**Issue by eiglow** [ValveSoftware/steam-for-linux#5851]
#### Your system information

* Steam client version (build number or date): Oct 13 2018, at 00:47:32
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

steamwebhelper segfaults whenever I try to open a web page in the client, for example, when I open the store. The page fails to load and I'm taken back to my library. Additionally, all friends features are not working, the friends list, any chat windows, whatever, they don't come up, as well as appearing offline to all of my friends.

In addition, it fails to upload the crashdump, with the output of `Unexpected crash report id length`, followed by `Failed to get crash dump id.` and `Report Id: Discarded=1`

I tried using the flatpak version of Steam, which doesn't have this problem, but flatpak has it's own limitations which I'm unable to get around.

I don't know of any steps to reproduce this issue on other systems, it's possible that it's just me.

**Comment by ritschmaster** [comment]
I can second this on Fedora 28 but I don't have to open a website for it. Starting Steam is sufficient to cause periodic segfaults within steamwebhelper:

>  $HOME/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 5:   178 Segmentation fault      (core dumped) ./steamwebhelper "$@"

Maybe firejail is causing this, but I've found no other reports of this behavior or how to solve it on the web. So I don't think that's an jailing issue.

**Comment by eiglow** [comment]
This seems to be fixed in the latest version of Steam. Thanks to whoever fixed it!

**Comment by kisak-valve** [comment]
Hello @ritschmaster, is this issue also fixed for you?

**Comment by kisak-valve** [comment]
Closing per @eiglow's comment.

**Comment by stellarhopper** [comment]
I'm still seeing this on Fedora 28. Additionally the friends list doesn't open in the client, nor do message windows.

`Dec 12 23:10:57 gamestarV3L audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-cored>
Dec 12 23:10:58 gamestarV3L steam.desktop[8760]: /home/stellarhopper/Steam/ubuntu12_64/steamwebhelper.sh: line 5:  4955 Segmentation fault      (core d>
Dec 12 23:10:58 gamestarV3L systemd-coredump[5039]: Process 4955 (steamwebhelper) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 4955:
                                                    #0  0x00007f5466fa833f free (libjemalloc.so.2)
                                                    #1  0x00007f546102f916 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #2  0x00007f5463d09553 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #3  0x00007f5462a170bb n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #4  0x00007f5461426de4 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #5  0x00007f5462af7563 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #6  0x00007f5462b0f0fa n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #7  0x00007f5462b0faf1 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #8  0x00007f5462b10759 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #9  0x00007f5462b2c075 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #10 0x00007f54629d12b0 n/a (/home/stellarhopper/Steam/ubuntu12_64/libcef.so)
                                                    #11 0x00000000004af50c n/a (/home/stellarhopper/Steam/ubuntu12_64/steamwebhelper)
-- Subject: Process 4955 (steamwebhelper) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 4955 (steamwebhelper) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
`

**Comment by kisak-valve** [comment]
Hello @stellarhopper, please open a new issue report.

**Comment by stellarhopper** [comment]
Opened https://github.com/ValveSoftware/steam-for-linux/issues/5957
