### ISSUE TITLE
CSGO will not open (just stays on black screen). Was working before.

### ISSUE THREAD

**Issue by iamlord** [ValveSoftware/steam-for-linux#5852]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @iamlord, there's a good chance you're seeing https://github.com/ValveSoftware/csgo-osx-linux/issues/1757 and adding `-nojoy` to the game's launch options may work around your issue.

Regardless of the workaround, please use the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux) issue tracker for CS:GO issues.

**Comment by iamlord** [comment]
How do I add no joy launch option? Typed in no joy in launch options still getting black screen with mouse. CS Source works fine.
