### ISSUE TITLE
Switch Pro Controller hits every single mouse button simultaneously in X11

### ISSUE THREAD

**Issue by oct2pus** [ValveSoftware/steam-for-linux#5854]
#### Your system information

* Steam client version (build number or date): October 22, 2018
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: [Yes/No]: Yes
* Have you checked for system updates?: [Yes/No] Yes, Persistent Issue

#### Please describe your issue in as much detail as possible:
When I use GNOME-Wayland, I notice no issues and the steam controller I can use the steam rebinding feature to emulate mouse/keyboard inputs as per expected, there are no 'phantom inputs' (the device will not send inputs if I leave it perfectly still on a flat surface).

When I use X11 (Tested with Gnome on Xorg and Openbox), if I have the controller plugged in while I enter steam, its as though every single mouse button is being pressed rapidly and my mouse cursor slowly descends on the x access. I had disabled every single desktop mode customization (everything was set to none, or no input) while on my wayland session, but nothing changes when I entered an x11 session.

 My working guess is the controller is being read as a pointing device and xorg freaks out because of it, but that wouldn't actually explain why it only occurs when steam is on.

#### Steps for reproducing this issue:
1) Plug in a Switch Pro Controller (I am using it wired with no bluetooth through a usb-c connector)
2) Start an X11 Session
3) Start Steam
4) Watch as the magic happens

**Comment by kisak-valve** [comment]
Hello @oct2pus, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
