### ISSUE TITLE
Displayed age of review is incorrect

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/steam-for-linux#5855]
Hi,
While watching the reviews page of Planar Conquest I noticed most of them are from 1970, while one is from 7218. I somehow doubt either of these is correct.  

![steam_review_bug](https://user-images.githubusercontent.com/5174562/47388780-5f6b0600-d713-11e8-9e8f-f746fa6aa86a.png)

I also doubt this is a linux specific issue, but I don't own a different operating system so I can't test that and I have no idea how contact the 'larger team'.

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, are you still experiencing this issue on an up to date system?
https://steamcommunity.com/profiles/76561198053776649/recommended/449300/ and https://steamcommunity.com/profiles/76561197970939691/recommended/449300/ look sane.

**Comment by Turmfalke2** [comment]
yeah, appears to be fixed. Closing this.
