### ISSUE TITLE
Steam freezes on menu hover

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5856]
#### Your system information
Processor: Intel Core i3-2330 w/ 2.2GHz x 4
4GB RAM
Integrated graphics

Deepin OS 15.7 (the OS is based on Debian Stable) running on amdx86_64 installation

* Steam client version (build number or date): Most likely latest.
* Distribution (e.g. Ubuntu): Deepin 15.7
* Opted into Steam client beta?: [Yes/No] Nope
* Have you checked for system updates?: [Yes/No] Yeah.

#### The issue here:
Every time I open up a rollup menu (ie. over my Library tab) or open up my friends tab, my Steam will freeze up, likely due to some HUD rendering error. When I alt+tab after my Steam freezes and there's a rollup menu open on screen when it happens, the menu just floats on top of every other process, no matter what window is open (full screen or not), until I kill the frozen Steam app.

#### Steps for reproducing this issue:

1. Open Steam
2. Hover over the Library tab to open the menu and wait a while with it open. 
3. Wait a couple of seconds with the menu open. Steam will eventually freeze.

OR:

1. Open Steam
2. Open Friends menu and wait for about 10-30 seconds or so until Steam freezes. I haven't thoroughly tested with hover events - will reply back later tomorrow.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
