### ISSUE TITLE
CS:GO Main menu not usable/cut

### ISSUE THREAD

**Issue by HerrNimmersatt** [ValveSoftware/steam-for-linux#5857]
#### Your system information

* Steam client version (build number or date): built Oct 13 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
This bug report coincides with Steam help request HT-4RWH-F7P8-89RN. You can find detailed hardware info there.
My problem is with CS:GO. I can install and start it without problems but the main menu is wrongfully scaled/cut below and not useable. I attached a screen shot of the issue.

#### Steps for reproducing this issue:

1. Start CS:GO
![bildschirmfoto von 2018-10-25 11-48-43](https://user-images.githubusercontent.com/44464291/47492209-c809ce00-d84c-11e8-8040-46c86831a603.png)

**Comment by kisak-valve** [comment]
Hello @HerrNimmersatt, CS:GO issues are being tracked in the csgo-osx-linux issue tracker, so I've gone ahead and transferred this issue to https://github.com/ValveSoftware/csgo-osx-linux/issues/1858.
