### ISSUE TITLE
MTG:A framebuffer freeze on "Updating screen"

### ISSUE THREAD

**Issue by insanemal** [ValveSoftware/steam-for-linux#5858]
#### Your system information

* Steam client version (build number or date):  Oct 24 2018 at 20:19:15 (Package versions: 1540414863)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Opted into Steamlink firmware beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I play many games. Most of my steam games seem to work well with my SteamLink. There is one game I installed Lutris to allow. That is Magic The Gathering: Arena.
It works fine on the local machine. It works on the Steam Link using Wines built in DX11 support. But it's slow. So I installed DXVK. Now it performs great but experiences a framebuffer freeze after the "Checking for updates" screen when used via Steam link.  Sound is still working fine and game is working fine on Linux host. 

#### Steps for reproducing this issue:

1. Install Steam 
2. Verify SteamLink works
3. Install Lutris
4. Install MTG:A
5. Install DXVK into Wine prefix for MTG:A
6. Verify MTG:A runs on local machine
7. Run MTG:A via Steam Link
8. Framebuffer freezes on Checking for updates screen.

**Comment by insanemal** [comment]
#5828 
Feels related

**Comment by kisak-valve** [comment]
Hello @insanemal, this reads like #5831 and/or #5828. Feel free to add your experience to the existing issue reports.

Closing in favor of the existing issue reports.
