### ISSUE TITLE
Steam client crashes on start

### ISSUE THREAD

**Issue by pipebomb** [ValveSoftware/steam-for-linux#5859]
#### Your system information

* Steam client version (build number or date):  Version | 1.0.0.56-1
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

**STR:** Start Steam either from shortcut ot terminal `steam` command

**AR:** Cleint promts for login/password, 2SA token, a connection prompt appears, an icon in system tray and then the icon disappears and no relatedd processes are running

Terminal output:
https://gist.github.com/pipebomb/6c2a40d02888302c1729b1563f1353ae

**Comment by kisak-valve** [comment]
Hello @pipebomb, what is the output of `locale -a` on your system?
```
terminate called after throwing an instance of 'std::runtime_error'
what(): locale::facet::_S_create_c_locale name not valid
```
This looks like the line of interest. In particular I'm interested if your system has en_US.UTF-8 and if not, does adding it to `/etc/locale.gen` and running `locale-gen` help.

**Comment by pipebomb** [comment]
Hello @kisak-valve and thank you for your fast responce on this issue. I am a beginner at Linux but here goes:
```
locale -a
C
en_US.utf8
POSIX
uk_UA.utf8
```
'en_US.UTF-8' is present in '/etc/locale.gen' and I've executed 'locale-gen' just in case. The two locales present have not caused any issues before, but I could easily do without the 'uk' if it meant I could run Steam again. Unfortunately the error still persists.

Best Regards,

**Comment by kisak-valve** [comment]
Please change `.utf8` to `.UTF-8`, rerun locale-gen, and retest.

**Comment by pipebomb** [comment]
Very sorry, but not sure where to change .utf8 to .UTF-8
I have commented with # the `uk_UA.` entry so it does not interfere. 
The `en_US.UTF-8` is cased as is in the `/etc/locale.gen` - I have no idea why the output of `locale -a` is `en_US.utf-8`. `LANG=en_US.UTF-8` is how it is in `/etc/locale.conf`

**Comment by pipebomb** [comment]
Solved by refreshing my distro. Wanted to try out Deepin DE anyway! 
Cheers!
