### ISSUE TITLE
opening the friends window from the tray icon causes xfce panel to freeze?

### ISSUE THREAD

**Issue by Jazoray** [ValveSoftware/steam-for-linux#5860]
#### Your system information

* Steam client version (build number or date):  Startup - updater built Oct 13 2018 00:47:09
* Distribution (e.g. Ubuntu):  Mint 19 XFCE
* Opted into Steam client beta?: [Yes/No] YES
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
when opening the previously closed "friends" window from the steam tray/notification area icon, the xfce panel freezes.
this only happens on the steam beta client.

#### Steps for reproducing this issue:

1. have an XFCE panel. (for example with whiskermenu and disk activity indicators)
2. launch steam and make sure the 'friends' window is closed
3. click the steam tray icon and select "friends"

the XFCE panel freezes. animations do not play and  buttons do not respond.

**Comment by Jazoray** [comment]
since today i am also experiencing this in the not beta

**Comment by nightsky30** [comment]
Just wanted to note I am not experiencing this with the Steam Beta on Xubuntu 18.10

**Comment by kisak-valve** [comment]
Hello @Jazoray, are you still experiencing this issue on an up to date system?

**Comment by Jazoray** [comment]
> Hello @Jazoray, are you still experiencing this issue on an up to date system?

no. in fact i have forgotten about this issue

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
