### ISSUE TITLE
UE4 games infinite download loop - Beta and stable client

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#5861]
#### Your system information

https://gist.github.com/Leopard1907/ca9172f0f9791ccf68ee5ffb16c01a26

* Steam client version (build number or date): Oct 24 2018
* Distribution (e.g. Ubuntu): Linux Mint 18.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I observed that behaviour for 2 games so far.
Warriorb and The Culling.

content_log.txt:

[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2522334/content_log.txt)

I also shot simple videos showing this attitude.

Warriorb:

https://youtu.be/UtbWLgRbpvA

The Culling:

https://youtu.be/eZtrhN33g2E

Yükleniyor means installing , onaylanıyor means verifying.

This update loop deletes files of the games , only way to play these games is ; nuke them from Steam and reinstall them again. Until a new update arrives and put your game into that loop again.

Steam output:

https://gist.github.com/Leopard1907/aa2c67a9e23472810510adb1c01e39ac
#### Steps for reproducing this issue:

1. A Turkish Steam client installation
2. An UE4 game that just got an update
3. Watch this loop after downloading update process ends

**Comment by Leopard1907** [comment]
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2522332/content_log.txt)

@Plagman content_log.txt added.

**Comment by Leopard1907** [comment]
@kisak-valve Hi , filesystem is ext4.

I have two libraries , one is on a 128 gb ssd which is also used by system. Only Rise of The Tomb Raider installed there.

Other library ( which i'm downloading all other games in there ) is on a 1 TB HDD , which that is also ext4.

Output of `lsblk`:

`NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT 

sdb      8:16   0 931,5G  0 disk 

└─sdb1   8:17   0 931,5G  0 part /home

sda      8:0    0 119,2G  0 disk 

├─sda2   8:2    0 111,2G  0 part /
├─sda3   8:3    0     8G  0 part [SWAP]
└─sda1   8:1    0    62M  0 part /boot/efi
`

**Comment by kisak-valve** [comment]
Hello @Leopard1907, are you still experiencing this issue on an up to date system?

**Comment by Leopard1907** [comment]
Sadly none of the native UE4 games i have and noted when i opened this issue doesn't receive updates anymore , as in that issue was reproducible when already installed games got an update later on.

So i can't reproduce that anymore. Issue can be closed.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
