### ISSUE TITLE
Client shut down unexpectedly after a game is closed

### ISSUE THREAD

**Issue by julben** [ValveSoftware/steam-for-linux#5863]
#### Your system information
```
$ lshw -short
H/W path           Device     Class          Description
========================================================
                              system         E692 0.0 (To be filled by O.E.M.)
/0                            bus            151-IB-E692
/0/0                          memory         64KiB BIOS
/0/28                         memory         1MiB L2 cache
/0/29                         memory         256KiB L1 cache
/0/2a                         memory         8MiB L3 cache
/0/2b                         memory         16GiB System Memory
/0/2b/0                       memory         8GiB DIMM DDR3 Synchronous 1333 MHz (0.8 ns)
/0/2b/1                       memory         DIMM [empty]
/0/2b/2                       memory         8GiB DIMM DDR3 Synchronous 1333 MHz (0.8 ns)
/0/2b/3                       memory         DIMM [empty]
/0/2c                         processor      Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
/0/100                        bridge         Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller
/0/100/1                      bridge         Xeon E3-1200 v2/3rd Gen Core processor PCI Express Roo
/0/100/1/0                    display        GM204 [GeForce GTX 970]
/0/100/1/0.1                  multimedia     GM204 High Definition Audio Controller
/0/100/14                     bus            7 Series/C210 Series Chipset Family USB xHCI Host Cont
/0/100/14/0        usb3       bus            xHCI Host Controller
/0/100/14/0/3                 input          SA9023 USB Audio
/0/100/14/0/4                 input          Fitbit Base Station
/0/100/14/1        usb4       bus            xHCI Host Controller
/0/100/16                     communication  7 Series/C216 Chipset Family MEI Controller #1
/0/100/1a                     bus            7 Series/C216 Chipset Family USB Enhanced Host Control
/0/100/1a/1        usb1       bus            EHCI Host Controller
/0/100/1a/1/1                 bus            Integrated Rate Matching Hub
/0/100/1b                     multimedia     7 Series/C216 Chipset Family High Definition Audio Con
/0/100/1c                     bridge         7 Series/C216 Chipset Family PCI Express Root Port 1
/0/100/1c/0                   bus            ASM1042 SuperSpeed USB Host Controller
/0/100/1c/0/0      usb5       bus            xHCI Host Controller
/0/100/1c/0/1      usb6       bus            xHCI Host Controller
/0/100/1c.3                   bridge         7 Series/C216 Chipset Family PCI Express Root Port 4
/0/100/1c.3/0                 storage        88SE6121 SATA II / PATA Controller
/0/100/1c.6                   bridge         7 Series/C210 Series Chipset Family PCI Express Root P
/0/100/1c.6/0      enp4s0     network        82574L Gigabit Network Connection
/0/100/1d                     bus            7 Series/C216 Chipset Family USB Enhanced Host Control
/0/100/1d/1        usb2       bus            EHCI Host Controller
/0/100/1d/1/1                 bus            Integrated Rate Matching Hub
/0/100/1d/1/1/6               communication  AR3011 Bluetooth
/0/100/1d/1/1/8               bus            USB2.0 Hub
/0/100/1d/1/1/8/1             generic        Controller
/0/100/1d/1/1/8/2             bus            USB2.0 Hub
/0/100/1d/1/1/8/3             input          G300s Optical Gaming Mouse
/0/100/1d/1/1/8/4             input          daskeyboard
/0/100/1f                     bridge         Z77 Express Chipset LPC Controller
/0/100/1f.2                   storage        7 Series/C210 Series Chipset Family 6-port SATA Contro
/0/100/1f.3                   bus            7 Series/C216 Chipset Family SMBus Controller
/0/1               scsi0      storage        
/0/1/0.0.0         /dev/sda   disk           256GB Samsung SSD 840
/0/2               scsi1      storage        
/0/2/0.0.0         /dev/sdb   disk           128GB M4-CT128M4SSD2
/0/3               scsi2      storage        
/0/3/0.0.0         /dev/sdc   disk           3TB WDC WD30EZRX-19D
```

> $ uname -a
> Linux hostname 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

> $ nvidia-smi
> Sat Oct 27 20:58:37 2018       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 970     Off  | 00000000:01:00.0  On |                  N/A |
> |  0%   60C    P0    54W / 200W |   1110MiB /  4042MiB |      3%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0       817      G   /usr/lib/xorg/Xorg                            24MiB |
> |    0      1048      G   /usr/lib/xorg/Xorg                           324MiB |
> |    0      1138      G   /usr/bin/gnome-shell                         277MiB |
> |    0      1808      G   ...quest-channel-token=3813739791533961501   358MiB |
> |    0      9724      G   ...-token=F7877CE5669A9D727C5B50F984720BA3    64MiB |
> |    0      9884      G   /home/jul/.steam/ubuntu12_32/steam            27MiB |
> |    0      9894      G   ./steamwebhelper                               3MiB |
> |    0     13140      G   gnome-control-center                           3MiB |
> +-----------------------------------------------------------------------------+

* Steam client version (build number or date): Oct 13 2018, at 00:47:32
* Distribution (e.g. Ubuntu): Debian 9 Strech, stable
* Opted into Steam client beta?: No, but true even for the beta (tried)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I expect the client to be still running after exiting a game. I could not guess what triggers it, but the client often is no longer working afterwards. It does not depend on the game, neither on the version (it is true since at least a few months AFAIK).

#### Steps for reproducing this issue:

1. Launching Steam client (preferably in a terminal to get the standard output)
2. Launch any game and after a while (whatever the duration) stop it
3. Client process will be stopped without explanation, often without any message displayed in the standard output (especially for native games)

Standard output after trying to launch a game, when running the client through a terminal

> $ steam
> Running Steam on debian 9 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> [2018-10-27 19:57:43] Startup - updater built Oct 13 2018 00:47:09
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> [2018-10-27 19:57:43] Checking for update on startup
> [2018-10-27 19:57:43] Checking for available updates...
> [2018-10-27 19:57:44] Download skipped: /client/steam_client_ubuntu12 version 1539393410, installed version 1539393410
> [2018-10-27 19:57:44] Nothing to do
> [2018-10-27 19:57:44] Verifying installation...
> [2018-10-27 19:57:44] Performing checksum verification of executable files
> [2018-10-27 19:57:45] Verification complete
> STEAMPS3 - AsyncTCPSocket created
> STEAMPS3 - AsncTCPSocket destroyed

**Comment by kisak-valve** [comment]
Hello @julben, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
