### ISSUE TITLE
Steam 'Friends' dropdown freezes in place

### ISSUE THREAD

**Issue by Vulksgren** [ValveSoftware/steam-for-linux#5864]
#### Your system information

* Steam client version (build number or date): Oct. 28th, 2018 
* Distribution (e.g. Ubuntu): Linux Mint Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. Just click on the friends tab, sometimes it will freeze and sometimes it won't. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Vulksgren, I'm fairly sure the issue you've described is #5724. Closing in favor of the existing issue report.
