### ISSUE TITLE
Steam 'Friends' dropdown freezes in place/MP4s don't properly load. 

### ISSUE THREAD

**Issue by Vulksgren** [ValveSoftware/steam-for-linux#5865]
#### Your system information

* Steam client version: **Oct. 28th, 2018 (Latest of this date)**
* Distribution: **Linux Mint 19 Tera Cinnamon**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Steps for reproducing this issue:

1. Just click on the friends tab, then click on "View Friends".
![screenshot from 2018-10-28 15-16-47](https://user-images.githubusercontent.com/44548269/47617255-8df73100-dac5-11e8-8a9f-600f03ea8319.png)
2. Just upload any .mp4 and you will see.
![screenshot from 2018-10-28 15-14-01](https://user-images.githubusercontent.com/44548269/47617254-8df73100-dac5-11e8-8b34-b7201a92e09e.png)

**Comment by kisak-valve** [comment]
Hello @Vulksgren, the first part is being tracked at #5724, only the second half will be tracked in this issue report.

**Comment by Leon422** [comment]
This is also happening to me on Ubuntu Budgie.

**Comment by kisak-valve** [comment]
Hello @Vulksgren, @Reonu, it looks like #5724 was resolved. Are either of you still experiencing the MP4 issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
