### ISSUE TITLE
can't enter CVV

### ISSUE THREAD

**Issue by R3D9477** [ValveSoftware/steam-for-linux#5867]
#### Your system information

* Steam client version (build number or date): 13 oct, 2018 at 00:47:32, pack ver. 1539393410
* Distribution (e.g. Ubuntu): Linux Mint 18.3 x64
* Opted into Steam client beta?: don't know
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Can't enter CVV on Steam Client for Linux (windows client under Wine hadn't this trouble)

#### Steps for reproducing this issue:

1. try to buy a game
2. try to enter CVV (push an any numeric key)
![1](https://user-images.githubusercontent.com/15020827/47707522-1b10c600-dc3d-11e8-8bec-de23ec9ec333.png)
3. num. wasn't entered, strange menu was opened instead
![2](https://user-images.githubusercontent.com/15020827/47707531-206e1080-dc3d-11e8-99b0-c87c7317a5e9.png)

Thanks.

**Comment by byte1024** [comment]
That's weird. Is there any reason why this wouldn't affect everyone besides being a problem with the user computer?

I assume its just a field so keyboard and typing event. There probably isn't any code to change what's entered which minimizes any interference.

**Comment by nanawel** [comment]
@r3d9u11 Are you able to use other textfields? (search box, etc.)
Just wondering, I've been having an issue with textfields since an update in september/october.

_Update: it was because I messed up with the locale files. See https://bbs.archlinux.org/viewtopic.php?pid=1865305#p1865305_

**Comment by r3d9u11** [comment]
@r3d9u11 yes, I tried to search games in Store and text input works fine there. I'll try to reinstall latest version of steam for linux and test it, maybe it is not actual for the latest version

**Comment by kisak-valve** [comment]
Hello @R3D9477, are you still experiencing this issue on an up to date system? (It doesn't look like you need to finish a transaction to test.)

**Comment by R3D9477** [comment]
@kisak-valve tested just now, seems like works fine

**Comment by elamtzvibirnbaum** [comment]
Having the same issue. Mac using the latest OS and using the latest Steam as of 7/12/23. Can't enter CVV, get that weird menu. Could this be that with the new update to the Mac Steam client which I presume uses Apple's built in Safari rendering engine an issue with people who have saved their payment method information? I do that on Chrome and when entering a card online it asks me for the CVV, could it be something like that where the Steam client does not know what to do there? Very annoying here, I want to buy a game that is on sale ending soon...

**Comment by elamtzvibirnbaum** [comment]
Here is a workaround for those who have the same issue: go to a text editor elsewhere and type in the CVV then copy and paste it into the field. You will still see the weird menu pop up but you will be able to complete the purchase

**Comment by jdactal** [comment]
I'm having this same issue on macOS as well.

**Comment by rknb** [comment]
Just had this happen in the Steam browser on Windows 10. Cannot enter CVV. The same strange menu opens up in the top left corner.

**Comment by ZiaChiu** [comment]
I am facing the same problem. The keyboard cannot be input and the input box cannot be selected normally. 

I can only rely on PayPal to complete the payment. I used to be able to use debit card payment, but now it is completely unusable.

I've heard about PayPal's recent regional restrictions on purchases. This is ridiculous, and it limits my payment options. I'm not sure if PayPal will simply refuse to process AUD in the future, but right now, PayPal is my only option. This is very frustrating.

Finally, my macos version is 15.6. This all happened after I updated the system. Maybe the Steam background was updated to the latest version without my knowledge, which made it incompatible with the latest version of macOS. Anyway, I can't figure out what happened.

Hopefully, you can fix it before PayPal goes haywire. I'm rooting for you guys to start ValvePay.

**Comment by korodarn** [comment]
This still appears to occur. I was trying to add funds for transaction in Wuthering Waves.  I can click on the checkbox I agree but I cannot type anything in the security code field whether with the main number row above the alpha keys or the numeric keypad, number lock is on. 

It doesn't appear to occur outside the overlay context, but I can't add custom amounts there... which is highly annoying when there are taxes.

**Comment by ORLOX93** [comment]
I'm having this issue on the Steam website, I mostly buy using the web version instead of the steam app as i can use Steamdb's extension that way.

You can type the CVV on the address bar and then cut it and paste it on the text field.
