### ISSUE TITLE
Steam link only running on GNOME xorg.

### ISSUE THREAD

**Issue by michaelothing** [ValveSoftware/steam-for-linux#5870]
I7 4790k
16 GB ram
Amd Vega 64 ati driver.

* Steam client version current beta
* Distribution: Reborn OS (Arch based)
* Opted into Steam client beta?: yes
* Have you checked for system updates?: Yes

Steam link working on GNOME xorg, but, if switched back to regular GNOME, the the steam link displays a scrambled screen and is unusable.

#### Steps for reproducing this issue:

1. Sign in from steam link to PC running gnome

**Comment by kisak-valve** [comment]
Closing in favor of #6148.
