### ISSUE TITLE
Steam chat window broken/clipping - Beta (and now stable) client.

### ISSUE THREAD

**Issue by HellishINC** [ValveSoftware/steam-for-linux#5871]
#### Your system information

* Steam client version (build number or date): _This really needs to be somewhere obvious._
`[2018-11-01 19:57:26] Startup - updater built Oct 31 2018 00:16:21`
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* GPU HW?: GTX 970 on 396.54.09

Steam chat UI 'clips' when receiving a message.

![steam](https://user-images.githubusercontent.com/4485158/47891484-a7bfad80-de10-11e8-9a7e-dcc36fe90b7a.png)

#### Steps for reproducing this issue:

1. Open Steam
2. Wait for a message

**Comment by HellishINC** [comment]
Appears to have been fixed. Closing until either I or someone else experiences issue again.

**Comment by HellishINC** [comment]
Started up again, this time using the stable client (as unstable causes dota2 to crash).

'''Built: Nov 26, 2018, at 20:15:48
Steam API: v018
Steam Package versions: 1543346820'''

**Comment by kisak-valve** [comment]
Hello @HellishINC, are you still experiencing this issue on an up to date system?

**Comment by HellishINC** [comment]
@kisak-valve No I do not. Sorry about not closing sooner.
