### ISSUE TITLE
Switch Pro Controller Rumble is not working

### ISSUE THREAD

**Issue by truboxl** [ValveSoftware/steam-for-linux#5872]
#### Your system information

* Steam client version (build number or date): Oct 31, 2018 at 00:16:47
* Distribution (e.g. Ubuntu): Fedora 29
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On Windows, a lot of my games on Steam as well as Dolphin Emulator work with Nintendo Switch Pro Controller's rumble.

On Linux (Fedora), my games and the emulator do detect the controller but do not seem to detect any rumble support from the controller.
Dolphin Emulator (native) detected the Pro Controller as `evdev/0/Microsoft X-Box 360 pad` after enabling Switch Pro Configuration Support.
Disabling the configuration support only switches it back to `evdev/0/Pro Controller`. Both, however, do not have any rumble support detected.

The only time I can tell if the Pro Controller does have haptic feedback is using Big Picture. Launching games with/without Big Picture do not make any difference of enabling the rumble support. It is disappointing to see that enabling the full feature set of the Switch Pro Controller is through Steam, as far as I am aware of.

#### Steps for reproducing this issue:

1. Connect Switch Pro Controller (USB or Bluetooth) and turn on Switch Pro Configuration Support
2. Big Picture has haptic feedback for the Switch Pro Controller
3. Any games launched after that (or not through Big Picture) do not have rumble support

**Comment by Notakas** [comment]
I've got this same issue. Any news?

**Comment by kisak-valve** [comment]
Hello, per "Added support for rumble pass-through for virtual controllers. This fixes missing rumble support for any controllers opted into Steam Input, and rumble emulation support for the Steam controller." in the [2019-05-22](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1612764629382440848) Steam client beta update, please opt into Steam's beta client and retest this issue.

**Comment by Notakas** [comment]
> Hello, per "Added support for rumble pass-through for virtual controllers. This fixes missing rumble support for any controllers opted into Steam Input, and rumble emulation support for the Steam controller." in the [2019-05-22](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1612764629382440848) Steam client beta update, please opt into Steam's beta client and retest this issue.

Tried it on Dead Cells, it vibrated on hit, but it felt kinda off, the vibration was a bit too long. On Celeste it doesn't work for me. Bleed 2 works perfect.

**Comment by truboxl** [comment]
I can confirm the rumble or vibration capability for the Switch Pro Controller is enabled in certain games and configurable in Dolphin Emulator. Thanks Valve. So I am closing this issue.

For other games that don't have rumble or straight up can't detect the controller, maybe we should follow #6144.

Just want to add that in Fedora, in addition of the udev rules included in RPMFusion's Steam package, I also added the user into the `input` group as mentioned in [this README.Fedora](https://github.com/negativo17/steam/blob/master/README.Fedora#L149). Whether you need it or not, its up to you.
