### ISSUE TITLE
Recettear: An Item Shop's Tale dies when entering the dungeon

### ISSUE THREAD

**Issue by Imantsg** [ValveSoftware/steam-for-linux#5873]
#### Your system information

* Steam client version 1541202990: 
* Distribution Ubuntu 18.10: 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Proton 3.16-4
* Video card Radeon RX 480

When I enter dungeon game randomly dies after few seconds.
[steam-70400.log](https://github.com/ValveSoftware/steam-for-linux/files/2544963/steam-70400.log)

#### Steps for reproducing this issue:

1. Start Game
2. Enter dungeon
3. Run around a little
4. Game dies

**Comment by kisak-valve** [comment]
Hello @Imantsg, we're tracking issues with games run with Proton in the Proton issue tracker, also we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5#issuecomment-435596638.
