### ISSUE TITLE
AMD Laptop: Can't turn on discrete graphics and run Steam games on it

### ISSUE THREAD

**Issue by rdlf4** [ValveSoftware/steam-for-linux#5875]
_Note for Moderators: the reason this thread is being posted here is because Valve is working with AMD to provide better driver solutions and support (or so I was told). I just hope that extends to AMD's APU series for laptops. But it isn't really the case, as noted on this thread._

Hello there.

So I bought this 2018 Acer Aspire 5 laptop with AMD A12 APU, featuring, according to 
`xrandr --listproviders`
the following GPUs:

> Providers: number : 2
> Provider 0: id: 0x79 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 2 associated providers: 1 name:AMD Radeon R7 Graphics @ pci:0000:00:01.0
> Provider 1: id: 0x44 cap: 0x6, Sink Output, Source Offload crtcs: 5 outputs: 0 associated providers: 1 name:Radeon 500 Series @ pci:0000:03:00.0

And the reason I made this thread is because I just can't turn on my dedicated graphics card (AMD Radeon RX540).
I've asked away on Ubuntu and Linux Mint forums, talked to a few people on Hexchat and I was pointed to very old forum threads when the fglrx and radeonsi drivers were around.
But mine is using amdgpu, so I'm afraid the solution differs a little. In other words, I need an updated solution to this issue.
Here are a few details I believe could help:

If I do
`echo ON > /sys/kernel/debug/vgaswitcheroo/switch`
and then check back, nothing changes, as the terminal outputs:

```
root@rodolfo-Aspire-A515-41G:/home/rodolfo# cat /sys/kernel/debug/vgaswitcheroo/switch 
0:IGD:+:Pwr:0000:00:01.0
1:DIS: :DynOff:0000:03:00.0
```

I've also checked [Prime](https://wiki.archlinux.org/index.php/ATI#Dynamic_frequency_switching)  as well as [Switcheroo](https://help.ubuntu.com/community/HybridGraphics#Using_vga_switcheroo), which I believe it's outdated, but no dice. Echoing DIS or ON does nothing so my guess is either this device has to be enabled first, or Switcheroo can't do anything to turn on my dedicated card, or I'm missing something.
This 2015 thread https://ubuntuforums.org/showthread.php?t=2304265 suggests to add a parameter to GRUB, which I believe is the only way to go about this situation, but haven't tried it myself just yet.

For reference, these are my machine's specs:

```
root@rodolfo-Aspire-A515-41G:/home/rodolfo# inxi -Fz
System:    Host: rodolfo-Aspire-A515-41G Kernel: 4.15.0-38-generic x86_64 bits: 64 Console: tty 0
           Distro: Linux Mint 19 Tara
Machine:   Device: laptop System: Acer product: Aspire A515-41G v: V1.06 serial: <filter>
           Mobo: BR model: Wartortle_BS v: V1.06 serial: <filter> UEFI [Legacy]: Insyde v: V1.06 date: 09/27/2017
Battery    BAT1: charge: 13.6 Wh 28.5% condition: 47.7/48.9 Wh (97%)
CPU:       Quad core AMD A12-9720P RADEON R7 12 COMPUTE CORES 4C+8G (-MCP-) cache: 4096 KB
           clock speeds: max: 2700 MHz 1: 1613 MHz 2: 1580 MHz 3: 1413 MHz 4: 1418 MHz
Graphics:  Card-1: Advanced Micro Devices [AMD/ATI] Carrizo
           Card-2: Advanced Micro Devices [AMD/ATI] Polaris12
           Display Server: X.Org 1.19.6 drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 1366x768@59.97hz
           OpenGL: renderer: AMD Radeon R7 Graphics (CARRIZO / DRM 3.23.0 / 4.15.0-38-generic, LLVM 6.0.0)
           version: 4.5 Mesa 18.0.5
Audio:     Card-1 Advanced Micro Devices [AMD] Device 157a driver: snd_hda_intel
           Card-2 Advanced Micro Devices [AMD/ATI] Kabini HDMI/DP Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-38-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
           IF: enp1s0f1 state: down mac: <filter>
           Card-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter driver: ath10k_pci
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 1000.2GB (5.6% used)
           ID-1: /dev/sda model: WDC_WD10SPZX size: 1000.2GB
Partition: ID-1: / size: 195G used: 53G (29%) fs: ext4 dev: /dev/sda3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 0.0C mobo: N/A gpu: 46.0,N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 235 Uptime: 4:36 Memory: 2905.2/7495.2MB Client: Shell (bash) inxi: 2.3.56 

```

It goes without saying that, because my dedicated video card is off, my tests with DRI_PRIME=1 are basically just reflecting the results of my integrated video card.
Is there a way to enable/turn on my dedicated video card? Again, there is no proprietary driver from AMD on this laptop, because they have never ever released a single driver for their own APU series on any Linux Distro, according to their own Download page.

I need this to work, it's the ONLY thing keeping me coming back to Windows when I want to game.
Thank you.

* Steam client version (build number or date): 3 Nov 2018, at 22:19:14
* Distribution (e.g. Ubuntu): Linux Mint 19 Tara 64-bit (Based on Ubuntu 18.04 64-bit)
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

**Comment by kisak-valve** [comment]
Hello @rdlf4, this is outside the scope of this issue tracker and should be discussed on your distro's forums.

That said, you should be able to run `DRI_PRIME=# glxinfo | grep Device` to get a straight answer to which video card is used with that env variable. It's highly unlikely vga_switcheroo is relevant to your system.
