### ISSUE TITLE
Mafia II not starting

### ISSUE THREAD

**Issue by lcarlier** [ValveSoftware/steam-for-linux#5876]
#### Your system information

* Steam client version (build number or date): Oct 13 2018 at 00:47:32
* Distribution (e.g. Ubuntu): Ubuntu Mate 16.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Tried to start Mafia II with Steam Play.
I can see that the status of the game goes to "running" for a couple of seconds then disappear. In the console, the following can be seen

> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
> Game update: AppID 50130 "", ProcID 28785, IP 0.0.0.0:0
> >>> Adding process 28785 for game ID 50130
> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
> GameAction [AppID 50130, ActionID 2] : LaunchApp changed task to Completed with ""
> >>> Adding process 28786 for game ID 50130
> >>> Adding process 28787 for game ID 50130
> >>> Adding process 28788 for game ID 50130
> >>> Adding process 28789 for game ID 50130
> >>> Adding process 28791 for game ID 50130
> >>> Adding process 28796 for game ID 50130
> >>> Adding process 28798 for game ID 50130
> >>> Adding process 28801 for game ID 50130
> >>> Adding process 28813 for game ID 50130
> >>> Adding process 28818 for game ID 50130
> >>> Adding process 28825 for game ID 50130
> Game removed: AppID 50130 "", ProcID 28785 
> No cached sticky mapping in ActivateActionSet.

#### Steps for reproducing this issue:

1. Start steam
2. Install Mafia II
3. Run it

I can't see more error logs. Thanks for helping me debugging this issue.

Kind regards,

Laurent

**Comment by kisak-valve** [comment]
Hello @lcarlier, issues with games run with Proton are being tracked in the Proton issue tracker. For this game you'll want to take a look at https://github.com/ValveSoftware/Proton/issues/330. Closing as a in favor of the existing issue report.

**Comment by lcarlier** [comment]
Thanks for referring to the post. 
Very useful
