### ISSUE TITLE
Chime sound will spam using pointer focus

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#5877]
* Steam client version (build number or date):  Nov 3 2018
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No]  Yes

#### Please describe your issue in as much detail as possible:

I'm using the bspwm window manager. I assume this affects any window manager or desktop environment that has pointer focus enabled. When you mouse over the steam login window after signing in with two factor authentication, you can repeatly spam the chime sound. This is rather annoying. There are other instances this can happen.

Another is when you go into the settings menu, and click the "Change" button for "Beta participation:". Yet another is when under the "In-Home Streaming" tab, and click on "Advanced host options" and "Advanced client options". If you mouse over the windows, that chime sound will spam and its very disturbing. 

#### Steps for reproducing this issue:

1. Have pointer focus enabled with your window manager or deskop environment
2. open multiple windows within Steam
3. mouse over them, and the chime sound will play

**Comment by kisak-valve** [comment]
Hello @shoober420, this is the same issue described in #3575, closing in favor of #6.

**Comment by shoober420** [comment]
My fault for duplicate.
