### ISSUE TITLE
steam client update broke login on linux mint.

### ISSUE THREAD

**Issue by lizardman61** [ValveSoftware/steam-for-linux#5882]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3. 
reset password 3 times plus reset by support 2 times. still tells incorrect password trying to login only happened after last update. been playing star conflict since 2015 with linux mint with no issues & spend $ that I can no longer benefit from.

**Comment by kisak-valve** [comment]
Hello @lizardman61, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
