### ISSUE TITLE
Steamlink mouse clicks are shifted 60 pixels upward when using a 1920x1200 steamlink client

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/steam-for-linux#5885]
#### Your system information

* Steam client version (build number or date): 1541556215 (Steamlink host)
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes on Steamlink host, No on Steamlink client.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
https://gist.github.com/ryao/b6232fdcc0a5f1a84d5de28c8f7c0eda (Steamlink host)

Steamlink mouse clicks on a 1920x1200 monitor when streaming from a 1920x1080 host should handle the screen's vertical alignment and shift themselves 60 pixels downward. Instead, there is no shift, so the mouse clicks appear to need to be done 60 pixels higher than they should be.

#### Steps for reproducing this issue:

1. Setup Steam on a host with a 1920x1080 monitor.
2. Setup Steam on a client with a 1920x1200 monitor.
3. Try streaming from the host to the client.
4. Observe that mouse clicks seem to ignore the black bars at the top and bottom of the screen and appear to assume that there is no black bar at the top of the screen.

**Comment by kisak-valve** [comment]
Hello @ryao, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
