### ISSUE TITLE
Keyboard recognized as controller

### ISSUE THREAD

**Issue by cpf** [ValveSoftware/steam-for-linux#5888]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I would expect my keyboard to not be recognized as a controller. This causes issues in a couple of games, like csgo (Where -nojoy luckily fixes it)
When running a proton game though, it completely messes with everything, and causes the game to misinterpret everything. e.g. Monster Hunter World thinks the controller is always moving top-left.

I have an ergodox infinity, which might be the reason why.

I have found no way of turning off controller support, or making it clear to steam that the keyboard shouldn't be recognized as a controller.

**Comment by kisak-valve** [comment]
Hello @cpf, this issue is outside the scope of Steam in general and needs to be resolved at a system config or distro level.

That said, you should be able to adapt https://github.com/denilsonsa/udev-joystick-blacklist to your needs.

Closing as out-of-scope.
