### ISSUE TITLE
Chat renders incorrectly

### ISSUE THREAD

**Issue by janstuemmel** [ValveSoftware/steam-for-linux#5889]
#### Your system information

* Steam client version (build number or date): Nov 8 2018, at 18:51:57 (Version: 1541710380, API: v018)
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: NO
* Have you checked for system updates?: YES

#### Issue:

Steam chat renders incorrectly (see picture). When i start steam, chat renders correctly, but after a while it looks like on the picture and i cannot close them via "X" button. If i want to close them via Alt+F4, steam wants to close itself.

#### Steps for reproducing this issue:

1. Open steam
2. Wait a while, play a game, etc
3. Open chat

#### My steam system info

https://gist.github.com/janstuemmel/ab6287450fa7897309e9f965559379b0

![steamchat](https://user-images.githubusercontent.com/7893682/48268946-b4f32280-e436-11e8-8ef6-3c2b0b66a4c3.png)

**Comment by kisak-valve** [comment]
Hello @janstuemmel, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by janstuemmel** [comment]
> Hello @janstuemmel, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

https://gist.github.com/janstuemmel/ab6287450fa7897309e9f965559379b0

ty for reply

**Comment by sizeofbool** [comment]
@kisak-valve I had same issue with chat for a week or so, but I can't reproduce it any more. Looks like it was fixed in latest Steam client beta update.

My OS is GNU\Debian 9 'stretch' x86_64.

**Comment by kisak-valve** [comment]
Are you seeing the same fixed behavior @janstuemmel?

**Comment by janstuemmel** [comment]
i think its gone, i close it for now but reopen when it apears again. TY all
