### ISSUE TITLE
steam controller sometimes just doesn't work

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#5890]
At random, Steam will detect the Steam Controller as multiple Unknown Controller's and not respond correctly.

Other times, it will show up as my correct Steam Controller and seems to do literally nothing.

Only started happening since Ubuntu 18.10, didn't have an issue on Ubuntu 18.04.

I blacklisted the hid_steam driver, since that currently breaks it but even now I seem to still be having issues.

Anyone else encountered the same?

**Comment by kisak-valve** [comment]
Hello @LiamDawe, what firmware version is on the steam controller? You can check in Big Picture mode's settings.

**Comment by LiamDawe** [comment]
April 12th

https://imgur.com/a/IgOWOI0

**Comment by LiamDawe** [comment]
Closing as it doesn't happen now.
