### ISSUE TITLE
Steam client crash on startup due to faulty LANG env variable.

### ISSUE THREAD

**Issue by Morindhal** [ValveSoftware/steam-for-linux#5893]
#### Your system information

* Steam client version (build number or date): 1541710380
* Distribution (e.g. Ubuntu): KDE NEON (Ubuntu 18.04 derived)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When restarting the steam-client for a update my LANG environment variable had changed (due to my mistake in a unrelated program) to a faulty locale. This caused the steam client to no longer start and starting through a terminal gave me no helpful crash message.
It did seem to send a error report successfully but I got no user feedback.

#### Steps for reproducing this issue:

1. Start the steam client with the command "LANG=en_SE steam".

**Comment by kisak-valve** [comment]
Hello @Morindhal, are you still experiencing this issue on an up to date system?

**Comment by Morindhal** [comment]
This bug no longer seems to trigger off of a incorrect LANG variable.
Closing this as fixed.
