### ISSUE TITLE
Steam segfault

### ISSUE THREAD

**Issue by SleepingSloth** [ValveSoftware/steam-for-linux#5902]
## **System Information**

- Steam - [System Information](https://gist.github.com/SleepingSloth/190287f70b396a2f311bce95295bc38f#file-system-information)

## **Symtoms**

1. Under Help tab then system Information steam detects the wrong GPU drivers
2. When launching BPM or any game the steam process starts taking up 70% cpu usage

## **GDB Backtrace**

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/???/.local/share/Steam/ubuntu12_32/steam'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x00000000 in ?? ()
[Current thread is 1 (Thread 0xf7937d00 (LWP 2434))]
(gdb) bt
#0 0x00000000 in ?? ()
#1 0xcb7f3fc7 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#2 0xcb7f46cc in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#3 0xcb83edc6 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#4 0xe928e782 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/vgui2_s.so
#5 0xcb84aeb2 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#6 0xcb7d775d in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#7 0xcb7e0462 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#8 0xcb66565e in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#9 0xcb83edc6 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#10 0xcb671e38 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#11 0xcb66169c in ?? () from /home/???/.local/share/Steam/ubuntu12_32/friendsui.so
#12 0xe928c34d in ?? () from /home/???/.local/share/Steam/ubuntu12_32/vgui2_s.so
#13 0xef38463a in ?? () from /home/???/.local/share/Steam/ubuntu12_32/steamui.so
#14 0xef38b383 in ?? () from /home/???/.local/share/Steam/ubuntu12_32/steamui.so
#15 0x5665d980 in RunSteam(int, char**, bool) ()
#16 0x5665e85b in ?? ()
#17 0x56648eec in ?? ()
#18 0xf795fb41 in __libc_start_main () from /usr/lib32/libc.so.6
#19 0x5664c7d1 in _start ()
(gdb)

**Comment by SleepingSloth** [comment]
@kisak-valve 

steam should use these

 - nvidia 410.73-2
 - nvidia-utils 410.73-1
 - lib32-nvidia-utils 410.73-1

instead we get

Driver:  VMware, Inc. llvmpipe (LLVM 7.0, 256 bits)
    Driver Version:  3.1 Mesa 18.2.4
    OpenGL Version: 3.1

**Comment by kisak-valve** [comment]
Hello @SleepingSloth, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
