### ISSUE TITLE
Quit Steam from Gnome application bar is unreliable

### ISSUE THREAD

**Issue by cliffordboulton** [ValveSoftware/steam-for-linux#5904]
First time using Github. Dunno how to add those labels.

#### Your system information

* Steam client version (build number or date): 1541819448 (Nov 10)
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

[Screenshots](https://imgur.com/a/mDhpDbc)

I only have 4 games installed, but the drop-down menu shows very old installs from years back.
Also shown, that Quit link sometimes doesn't always exit Steam, but might not be your problem.

**Comment by kisak-valve** [comment]
Hello @cliffordboulton, the length of the games list in the tray icon is already being tracked at #3037, so let's only track the close request from the DE here.

**Comment by cliffordboulton** [comment]
OK, thanks!

**Comment by kisak-valve** [comment]
Hello @cliffordboulton, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
