### ISSUE TITLE
Can't launch Steam on chrooted environment.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5905]
#### Your system information

* Steam client version (build number or date): 1541819448
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have Debian 9.5 (Stretch) running with i3wm, I'm following https://wiki.debian.org/chroot instructions on how to set up a chroot environment and trying to run Steam inside it. If I don't mount host partitions on chroot directories Steam gives me a `Unable to determine CPU Frequency. Try defining CPU_MHZ.` error. Following all steps described here, the terminal outputs `../common/ipcserver.cpp (1229) : Assertion Failed: CPipeWaiter::BRemove(46) -- not present` and steam doesn't run at all. I can see the updater window but nothing more than that.

Host `uname -a` output:
`Linux FGNull 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

My error.log output:
https://gist.githubusercontent.com/Lurdiel/41d3a3d9947fe866f64094d136941c3c/raw/2dba49b4873fd71d2e614ce2cc0ba7937645a826/gistfile1.txt

#### Steps for reproducing this issue:
1. Create a chroot environment with `debootstrap --arch i386 stretch /path/to/chroot http://deb.debian.org/debian`
2. Mount host partitions on chroot directories:
`mount --bind /dev /path/to/chroot/dev `
`mount --bind /dev/pts /path/to/chroot/dev/pts`
`mount --bind /proc  /path/to/chroot/proc`
3. Run `xhost +` on host machine so I can run GUI applications from chroot.
4. Chroot into /path/to/chroot/
5. Run `export DISPLAY=:0.0` so Steam can show GUI on my host display.
6. Install and run Steam through `apt install steam`.

**Comment by Lurdiel** [comment]
I see, sorry for the trouble then. I'll research what's causing this and try to troubleshoot by myself, thanks for the help anyway.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
