### ISSUE TITLE
Steam downloads not able to fully utilize the Network

### ISSUE THREAD

**Issue by Ayub-Khan** [ValveSoftware/steam-for-linux#5907]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Ayub-Khan/abcf1b43ab57ecc43704ffb9945cddde
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? yes
* Have you verified the game files?: yes

#### Please describe your issue in as much detail as possible:
Steam download speed is very very low. It hits the peak a bit then comes back to 20-50 kbs. If i download any thing else its fast. But in case of steam its always low. This is very irritating. Use to work perfect but since 3-4 months its been acting up and downloading updates very slowly. 
![screenshot from 2018-11-17 17-02-12](https://user-images.githubusercontent.com/7721119/48660969-6e33a700-ea8c-11e8-90d5-73da99f60e66.png)

**Comment by kisak-valve** [comment]
Hello @Ayub-Khan, please reproduce this issue, then copy `<steam install dir>/logs/content_log.txt` to a [gist](https://gist.github.com/) and include a link in this issue report.

**Comment by Ayub-Khan** [comment]
@kisak-valve Here i was able to reproduce and created the following gist
https://gist.github.com/Ayub-Khan/2017b841b2cb41c326dfb084c659079a

**Comment by jsomedon** [comment]
I just installed steam on linux today and had exactly same issue, no such issue on windows. Like Ayub said, it goes peak at start of download for like 3 seconds then it drops under 100 KB/s, occasionally around 250KB/s.

And fyi, I already had dnsmasq on my machine.

**Comment by asyd** [comment]
I have the same issue too. I have FTTH so I can download at more than 100Mb/s but for few weeks  Steam download at around 20kb/s, this very annoying. I don't have the issue on Windows. 

On Linux I'm using: steam-runtime-beta-release_2019-01-10

I'm already use dnsmasq too.

**Comment by asyd** [comment]
FYI, I just downgraded to current stable release and the problem disappear.

**Comment by sorokya** [comment]
I'm also experiencing this issue on Arch. It was alright for a few months after I opted out of steam beta. But, now it seems the issue has made it into stable. It's really annoying when a 26Mb download takes an hour.

My download speed is 100Mbps.

I've tried using different servers and the issue persists.

**Comment by tonysh3** [comment]
> FYI, I just downgraded to current stable release and the problem disappear.

Do you have this problem now?
I have this problem, i guess currently version was "beta" for you.

**Comment by asyd** [comment]
Indeed I still have the issue, even with the stable release.

**Comment by tonysh3** [comment]
> Indeed I still have the issue, even with the stable release.

I don`t know what happened today but after 10 minutes of slow download with 100 byte/sec it become normal (800 kb/s). Try to wait maybe it will work.

**Comment by pohmelie** [comment]
Same here, ubuntu 18.04, 120KB/s instead of 2-3MB/s.

**Comment by Pzychozes** [comment]
This is a bug.
![screen-w](https://user-images.githubusercontent.com/32552973/59221035-0632e280-8bcf-11e9-9614-72ee6688cdc9.jpg)
`Retrieving speedtest.net configuration...
Testing from Beeline Home (128.71.233.78)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Beeline (Krasnodar) [1.00 km]: 9.763 ms
Testing download speed................................................................................
Download: 87.37 Mbit/s
Testing upload speed......................................................................................................
Upload: 91.08 Mbit/s
`
`PING steampowered.com (96.6.13.130) 56(84) bytes of data.
64 bytes from a96-6-13-130.deploy.static.akamaitechnologies.com (96.6.13.130): icmp_seq=1 ttl=58 time=50.6 ms
64 bytes from a96-6-13-130.deploy.static.akamaitechnologies.com (96.6.13.130): icmp_seq=2 ttl=58 time=50.0 ms
64 bytes from a96-6-13-130.deploy.static.akamaitechnologies.com (96.6.13.130): icmp_seq=3 ttl=58 time=50.4 ms

--- steampowered.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 5ms
rtt min/avg/max/mdev = 50.004/50.342/50.613/0.253 ms
`

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by asyd** [comment]
@kisak-valve problem disappears for me

**Comment by kisak-valve** [comment]
Thanks for the feedback @asyd. Closing.
