### ISSUE TITLE
Steam crash after update

### ISSUE THREAD

**Issue by cheddar-cheeze** [ValveSoftware/steam-for-linux#5910]
#### Your system information

* Steam client version (build number or date): 1541817908
* Distribution (e.g. Ubuntu): Void X86_64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Doesn't start after steam client update
[Terminal Output](https://gist.github.com/cheddar-cheeze/34d5e5d16db63832bd58c9559da25bba)

#### Steps for reproducing this issue:

1.  Start steam
2.  Checks for updates
3.  Crashes

**Comment by Sekuraz** [comment]
Had the same problem. Then tried to reinstall steam by removing .local/share/Steam.
Afterwards i get this error: /home/markus/.local/share/Steam/steam.sh: line 823: /home/markus/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory

**Comment by cheddar-cheeze** [comment]
yep, deleting the whole steam folder and reinstalling fixed the issue

**Comment by kisak-valve** [comment]
Hello @cheddar-cheeze, are you still experiencing this issue on an up to date system?

**Comment by Sekuraz** [comment]
As this issue is more than 2 years old I'm feeling like you are necro bumping. The issue is long gone or handled differently. We are not waiting for 2 years to get such an issue fixed @kisak-valve .
I changed to the beta client

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
