### ISSUE TITLE
No Shop, no online Friendslist when running in Ubuntu-Guest-Session

### ISSUE THREAD

**Issue by silelmot** [ValveSoftware/steam-for-linux#5913]
Hey there.
when i am running steam in a guest-session on linux mint, i have no shop nor diskussions or help and the friendslist keeps offline. (but game download and update works)

this is the error i get in console:
`Error 13 locking shared memory file../common/html/chrome_ipc_server.cpp (75) : Assertion Failed: m_pMasterMemStream->BCreatedStream() Error 13 locking shared memory fileError 13 locking shared memory file../common/html/chrome_ipc_server.cpp (75) : Assertion Failed: m_pMasterMemStream->BCreatedStream()`

the strange part is: when i run steam from terminal or even when i aktivate the terminal in the desktop.file steam works great with friendslist and rest online.

the same error with beta and opted out.

#### Your system information

CPU:
    cpu-manufactor: AuthenticAMD
    cpu-brand: AMD Athlon(tm) X4 950 Quad Core Processor      
    speed: 3500 MHz
  
System:
    Linux Mint 19 Tara (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.15.0-39-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11906000
    X-windowmanager: Mutter (Muffin)
    Steam-Runtime-Version: steam-runtime-beta-release_2018-10-24

GPU:
    Driver: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Version: 4.6.0 NVIDIA 396.54
    OpenGL-Version: 4.6

Memory:
    RAM: 7969 MB

**Comment by kisak-valve** [comment]
Hello @silelmot, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
