### ISSUE TITLE
Steam client looks for wrong executable name when launching Tyranny

### ISSUE THREAD

**Issue by lockedude** [ValveSoftware/steam-for-linux#5921]
#### Your system information

* Steam client version (build number or date): 1541819448
* Distribution (e.g. Ubuntu): Debian 8
* Opted into Steam client beta?: No
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I've installed the game 'Tyranny' via the steam client, it downloaded/installed successfully, and when I tried to launch the game a 'Missing Executable' error was thrown. I checked the path that the steam client was looking for the Tyranny executable, and it seemed valid -

nick@Enterprise:~/.steam/steam/steamapps/common/Tyranny$ ls -ltr
total 50608
-rwxr-xr-x  1 nick nick 25750672 Nov 26 20:03 Tyranny.x86
-rwxr-xr-x  1 nick nick 26021488 Nov 26 20:03 Tyranny.x86_64
drwxr-xr-x 10 nick nick    45056 Nov 26 20:15 Tyranny_Data
drwxr-xr-x  4 nick nick     4096 Nov 26 20:15 Ringtones

Then I noticed the steam client indicated it was looking for this location as the executable - .steam/steam/steamapps/common/Tyranny/Tyranny

I renamed Tyranny.x86_64 to Tyranny and was able to launch the game through steam successfully after that.

nick@Enterprise:~/.steam/steam/steamapps/common/Tyranny$ mv Tyranny.x86_64 Tyranny
nick@Enterprise:~/.steam/steam/steamapps/common/Tyranny$ ls -ltr
total 50608
-rwxr-xr-x  1 nick nick 25750672 Nov 26 20:03 Tyranny.x86
-rwxr-xr-x  1 nick nick 26021488 Nov 26 20:03 Tyranny
drwxr-xr-x 10 nick nick    45056 Nov 26 20:15 Tyranny_Data
drwxr-xr-x  4 nick nick     4096 Nov 26 20:15 Ringtones

#### Steps for reproducing this issue:

1. Install the game 'Tyranny'
2. Right click the game in the steam library and select 'Play'.
3. Weep

**Comment by kisak-valve** [comment]
Hello @lockedude, this issue should be handled by the game's devs.

Related forum post: https://steamcommunity.com/app/362960/discussions/0/1748980761814302225/

**Comment by kisak-valve** [comment]
Hello @lockedude, this looks like it was fixed by the game dev(s) back in May 2019.
