### ISSUE TITLE
steamwebhelper and gldriverquery both 100% CPU

### ISSUE THREAD

**Issue by stevenroose** [ValveSoftware/steam-for-linux#5925]
#### Your system information

* Steam client version (build number or date): (can't copy this)
![screenshot-2018-11-28-22-36-30](https://user-images.githubusercontent.com/853468/49186913-c9537c80-f35d-11e8-9e42-844d867b22ec.png)
Arch package `steam-1.0.0.56-1`
System Information: https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-system-information-txt

* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

![screenshot-2018-11-28-22-40-21](https://user-images.githubusercontent.com/853468/49187108-572f6780-f35e-11e8-9ee6-1e098ff8f828.png)
stderr and stdout log while running and exiting:
https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-steam-log
(I also have an issue where Steam refuses to shut down. I have to sigkill it (2 different processes) to have it stop.)

#### Steps for reproducing this issue:

1. Install Steam on Arch.
2. Launch Steam.

**Comment by kisak-valve** [comment]
Hello @stevenroose, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by stevenroose** [comment]
@kisak-valve done. I also have an issue where Steam refuses to shut down. I have to sigkill it (2 different processes) to have it stop.

**Comment by kisak-valve** [comment]
Hello @stevenroose, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
