### ISSUE TITLE
Artifact doesn't launch

### ISSUE THREAD

**Issue by stevenroose** [ValveSoftware/steam-for-linux#5927]
#### Your system information

* Steam client version (build number or date): (can't copy this)
![screenshot-2018-11-28-22-36-30](https://user-images.githubusercontent.com/853468/49186913-c9537c80-f35d-11e8-9e42-844d867b22ec.png)
Arch package `steam-1.0.0.56-1`
System Information: https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-system-information-txt

* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
(Could be related to https://github.com/ValveSoftware/steam-for-linux/issues/5925.)

When trying to launch Artifact, it shows "Running" but no window shows up. Trying again gives an error saying the game is already running.

stderr and stdout output while doing this: https://gist.github.com/stevenroose/1fb78734c34f3a5cb8ee6296b0e38270#file-steam-artifact-log

These processes show up:
```
$ ps aux | grep -i artifact
steven   29555  0.0  0.0  50936  8312 pts/48   S+   23:04   0:00 /bin/bash /opt/steam-library/steamapps/common/Artifact/game/artifact.sh -vulkan
steven   29558 99.8  0.2 2287708 67460 pts/48  Rl+  23:04   2:18 /opt/steam-library/steamapps/common/Artifact/game/bin/linuxsteamrt64/dcg -vulkan
steven   30302  0.0  0.0   8184  2336 pts/36   S+   23:06   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i artifact
```

#### Steps for reproducing this issue:

1. Install and launch Steam on Arch.
2. Install Artifact.
3. Launch Artifact.

**Comment by stevenroose** [comment]
Might be related/relevant that I run Awesome WM, which is not a desktop manager, just a window manager.

**Comment by leifmetcalf** [comment]
I am getting a similar issue on Ubuntu. It is different in that the client doesn't say the game is "running," the game just fails to start after the "Preparing to launch Artifact..." window opens (and then immediately closes).

#### Your system information

* Steam client version (build number or date): Nov 26 2018, at 20:15:48
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Complete stamp: https://gist.github.com/leifmetcalf/8d1d209936f78f10aeb8c17fcf583946

#### Please describe your issue in as much detail as possible:

After installing Artifact, trying to run it from the Steam client does not start the game. A "Preparing to launch Artifact..." window comes up but then closes quickly. I've verified the local files.

#### Steps for reproducing this issue:

1. Install the Steam client beta.
2. Install Artifact
3. Run Artifact from the Steam client.

**Comment by kisak-valve** [comment]
Hello @stevenroose, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
