### ISSUE TITLE
User activity framedrops nonsteam games

### ISSUE THREAD

**Issue by Oreoezi** [ValveSoftware/steam-for-linux#5930]
#### Your system information

* Steam client version (build number or date):27 Nov 2018 
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
In the steps required I've posted everything needed. It is quite depressing this is an actual problem.
#### Steps for reproducing this issue:

1. Playing a non-steam game
2. A friend joining a game and prompting you the message window in the corner
3. The game lagging for a second

**Comment by kisak-valve** [comment]
Hello @Oreoezi, are you still experiencing this issue on an up to date system? If you are, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Oreoezi** [comment]
I still get this issue. I just got used to closing steam before playing non steam games. Here's a gist although my system configuration is irrelevant to the issue. https://gist.github.com/Oreoezi/321b23101927343171626d1b366953d0
