### ISSUE TITLE
Streamed game grabs focus every ten seconds

### ISSUE THREAD

**Issue by robertc** [ValveSoftware/steam-for-linux#5934]
#### Your system information

* Steam client version (build number or date): Nov 30 2018, at 21:56:15
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When streaming games from a Windows PC I alt-tab to another application, the streaming window initially minimizes.  After approximately ten seconds of interacting with the other app the streaming window restores and grabs focus, making any interaction with the other application very difficult.

#### Steps for reproducing this issue:

1. Start up a program (e.g. Firefox)
2. Start streaming a game (tested: Neverwinter; Chivalry)
3. Alt-tab to the web browser
4. Wait ten seconds

**Comment by zorael** [comment]
Hopefully without being a mere me-too post, I'm seeing this on Manjaro with KDE. kwin 5.14.4.

Steam client version (build number or date): Dec 14 2018, at 22:19:08
Distribution (e.g. Ubuntu): Manjaro/Arch KDE
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes

In my case it only steals focus once after having lost it. After I alt-tab back out again, the window happily sits in the background playing game sounds, contrary to normal behaviour. If I lower KWin focus stealing prevention to none, it seems to behave as the original poster describes. Tested game was Muv-luv Alternative.

https://i.imgur.com/Cjea74a.png

**Comment by kisak-valve** [comment]
Hello @robertc, @zorael, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
