### ISSUE TITLE
Keeps logging me out or forgetting my password

### ISSUE THREAD

**Issue by BenjiStokman** [ValveSoftware/steam-for-linux#5937]
#### Your system information
Ubuntu 18.04 4.15 shell. Gnome desktop
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu):  Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Almost every time I open steam, it logs me out, or forgets my password. My games and data still exist when I login
#### Steps for reproducing this issue:
1. Log into steam
2. Restart computer
3. Try to open steam (sometimes works)

**Comment by kisak-valve** [comment]
Hello @BenjiStokman, this issue is already being tracked at #5030 / #5035. Closing as a duplicate.
