### ISSUE TITLE
Switch Wired Pro Controller doesn't work in games, sometimes moves the mouse with Steam open

### ISSUE THREAD

**Issue by eska0** [ValveSoftware/steam-for-linux#5939]
#### System information

* Steam client version (build number or date): 2018-12-04
* Distribution (e.g. Ubuntu): Linux Mint 19
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

---

#### Issue

I have an official, licensed-by-Nintendo _Wired_ Switch Pro Controller (made by PowerA), which is not the same as the regular Pro Controller, but Steam recognizes it as a regular Pro Controller and it doesn't work with any games.

The controller shows up in Big Picture as a regular Switch Pro Controller:

![Switch Wired Pro Controller in Steam Big Picture](https://user-images.githubusercontent.com/45618704/49498532-43569a80-f863-11e8-9239-d1ea91c23b02.png)

The controller's behaviour depends on if Steam is running, if it's in big picture mode, and if Switch Pro Configuration Support is enabled.

| Steam running | Big Picture mode | Switch Pro Configuration Support | Result |
| --- | --- | --- | --- |
| <ul><li>- [ ] </li></ul> | | | The controller works normally in non-Steam applications and sometimes in Steam games that don't require Steam to be running to play (e.g. Psychonauts, but not Super Meat Boy). |
| <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> | The controller does nothing in any game launched through Steam. |
| <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | The controller again does nothing in any game launched through Steam, but now it controls the mouse and keyboard (outside of games). The table below describes how the controller is mapped. |
| <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> | The controller navigates Big Picture normally, but does nothing when games are launched. The home button opens the Steam overlay, but no buttons work in-game. |
| <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> | The controller acts the same as above except the controller can be remapped to mouse/keyboard actions within Big Picture and that works in-game. Outside of Big Picture, it still controls the mouse and keyboard. |
 
---

When configuration support is enabled, this is how the controller acts:

| Controller input | Action |
| --- | --- |
| Right stick | Moves the mouse |
| Left stick | Arrow keys |
| ZR | Left mouse button |
| ZL | Right mouse button |
| L | Ctrl |
| R | Alt |
| Minus | Tab |
| A | Spacebar |
| B | Enter |
| X | Page down |
| Y | Page up |

---

The device name is "Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller" and [this](https://gist.github.com/eska0/a7c45ea34c0d24422c4b7616527b0c10) is the list of events from running `evtest`. If I need to provide any other technical information about the controller or anything else, I can do that.

**Comment by kisak-valve** [comment]
Hello @eska0, please verify you have the `steam-devices` distro package.

**Comment by kisak-valve** [comment]
I missed a critical detail, the udev rules in Ubuntu 18.04's steam-devices is too old to come with Switch Pro Controller entries. You'll want to include (and possibly need to adjust) the Switch udev rules from https://github.com/ValveSoftware/steam-devices/blob/master/steam_input.rules in your udev config.

**Comment by eska0** [comment]
I updated `/lib/udev/rules.d/99-steam-controller-perms.rules` with the version from that repo, and nothing changed. I tried commenting out the other Switch controller lines and adding one for the wired controller, I tried just adding a line to the file that was there originally, still nothing.

At this point I discovered the file `/lib/udev/rules.d/70-steam-controller.rules`, which only contains a line for the wired controller (with the correct vendor and product IDs):

```
# NS PRO Controller USB
KERNEL=="hidraw*", ATTRS{idVendor}=="20d6", ATTRS{idProduct}=="a711", MODE="0660", TAG+="uaccess"
```

I tried moving the line from this file to `99-steam-controller-perms.rules`, but the controller still acts the same as before in all cases.

**Comment by kisak-valve** [comment]
Can you run `lsusb` from the `usbutils` package and check that the vendor/product IDs match your controller.

**Comment by eska0** [comment]
As of version 2018-12-08, it's completely fixed for me.
