### ISSUE TITLE
Steam windows won't show after an update

### ISSUE THREAD

**Issue by SR-dude** [ValveSoftware/steam-for-linux#5941]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu):  LFS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
After getting the login dialog box the main steam windows doesn't show. I had steam working on my 
linux box before an update about a week ago. I tried to reset steam. That gave me a box requesting  a code that was sent to my email address. That part went  fine but still no steam.

[console.txt](https://github.com/ValveSoftware/steam-for-linux/files/2658811/console.txt)

**Comment by SR-dude** [comment]
Here is the accompanying crash dump from /tmp.
[assert_20181207161048_23.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/2658826/assert_20181207161048_23.dmp.zip)

**Comment by kisak-valve** [comment]
Hello @SR-dude, Linux from Scratch in general is not a supportable distro, but you may find some hints from other issue reports with `Assertion Failed: !bSharedKVSymbols`. It's possible this can happen from an incompatible or missing system dependency.

For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

**Comment by SR-dude** [comment]
> For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.
Is there anything in the crash dump?

**Comment by SR-dude** [comment]
Holy Sh*t! Your tip about !bSharedKVSymbols was right. The following line  fixed things for me.
You need a raise. 

STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 STEAM_RUNTIME=1 steam

**Comment by kisak-valve** [comment]
Glad to hear you got it working. That effectively confirms that your issue is an incompatible or broken system dependency.

Closing as Linux from Scratch issues are not going to be investigated in depth.

**Comment by SR-dude** [comment]
The console did report that some libraries are old. The runtime must have updated.
I'll fix that.

**Comment by kisak-valve** [comment]
You should note that a couple libraries are unconditionally pinned to avoid some fatal scenarios (at the expense of harmless log messages).
