### ISSUE TITLE
Artifact not running with Intel Graphics

### ISSUE THREAD

**Issue by murkdum** [ValveSoftware/steam-for-linux#5949]
* Steam client version Nov 26 of 2018 
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My laptop is packed with a Celeron N3350 and no dedicated GPU (it has intel graphics). On windows, this laptop runs Artifact (even if at the cost of very low res textures and settings) and runs Heartstone just fine. On Linux this laptop can Dota2 and heartstone through wine, but fails to run Artifact thanks to Vulkan which is not supported by intel graphics on this laptop with the message:
"Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan".

Is there a way to make Artifact run through OpenGl like Dota2 does? Because it's the only way to make artifact currently work on Linux on my laptop (A way to pick graphics API), also it's a CCG why does it perform so poorly when Heartstone runs fine even through wine? 

#### Steps for reproducing this issue:

1. Have intel graphics and Linux
2. Hit play on Artifact.

**Comment by kisak-valve** [comment]
Hello @murkdum, you most likely do not have a complete vulkan driver stack and for Ubuntu 18.04 you should run `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386`. The 32 bit half is not needed for Artifact, but is good for completeness sake.

**Comment by murkdum** [comment]
> Hello @murkdum, you most likely do not have a complete vulkan driver stack and for Ubuntu 18.04 you should run `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386`. The 32 bit half is not needed for Artifact, but is good for completeness sake.

Working Perfectly!!! Even with more fps and texture quality than on Windows 10! Although I didn't install the 32 bit part. As it is, I'm also gonna test Dota2 with vulkan driver now installed and see if the graphics and performance raise a bit as well!
