### ISSUE TITLE
Inconsistent/wrong characters in romanian translation

### ISSUE THREAD

**Issue by z0id** [ValveSoftware/steam-for-linux#595]
Romanian translation is filled with şŞ, instead of șțȘȚ. This is due to an older mess-up on Microsoft's part regarding the romanian keyboard layout. This character bug is non-existent on Linux, and makes Steam stand out.
It could easily be fixed by automatically replacing all cedilla below diacritics with comma below characters. It also makes sense, as no one in the translation team is willing to replace all characters by hand.

**Comment by licaon-kter** [comment]
Latest beta is missing a font or something.

![diacriticslarge](https://i.imgur.com/WfSnFtN.jpg)

That's Ă, Ț, Ș and Ț.

**Comment by licaon-kter** [comment]
Fixed (except the cut A) in beta March 4. Yay :)
