### ISSUE TITLE
Artifact text replaced with white rectangles 

### ISSUE THREAD

**Issue by RNanclares** [ValveSoftware/steam-for-linux#5951]
#### Your system information
Intel i7 3630QM - Running on Intel 4000 no GPU.

* Steam client version (build number or date): 1543346820 
* Distribution: Ubuntu 18.04 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:

Text in cards and menus gets replaced by white rectangles.
![screenshot from 2018-12-12 10-20-00](https://user-images.githubusercontent.com/11431207/49885269-61407400-fdfc-11e8-81d0-221e38d15abd.png)

**Comment by kisak-valve** [comment]
Hello @RNanclares, this is due to the experimental and incomplete vulkan support for Intel/Ivybridge in mesa (same as https://github.com/ValveSoftware/Dota-2-Vulkan/issues/181). Feel free to reach out to your video driver vendor, but there's nothing that can be done here.

**Comment by RNanclares** [comment]
OK thanks for the fast response. @kisak-valve
