### ISSUE TITLE
Steam client miltiple monitor issues

### ISSUE THREAD

**Issue by krsrdjan** [ValveSoftware/steam-for-linux#5952]
#### Your system information

* Steam client version (build number or date): Steam client from Ubuntu 18.4.1 repository
* Distribution (e.g. Ubuntu): Ubuntu 18.4.1 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Hi support,
I have a bug to report regarding multiple monitor setup on Ubuntu 18.04.
I have ThinkPad T480 with its original dock and two external monitors Dell 24'' running Ubuntu 18.04.1 with default open source graphics drivers. All software is up to date from Main server.

After installing Steam client from official Ubuntu repositories, three monitors setup crashed, and only two monitors are working. 

After restart Ubuntu is still reporting only two existing monitors. 

After sudo apt remove steam steam-launcher problem is still there, only two monitors working.

Only after I did sudo apt purge steam steam-laucher, and apt did reconfiguration I got my three monitors back and working. 

#### Steps for reproducing this issue:

1. Install steam client from official Ubuntu 18.4 repo 
2. Three monitor setup has crashed, only two monitors are available in Ubuntu system
3.

**Comment by kisak-valve** [comment]
Hello @krsrdjan, please clarify exactly what is crashing. Steam? Your entire desktop session?

Unless I'm missing something, your issue is outside the scope of the Steam client and is an issue with your distro's video driver. Issues with the distro-provided steam packaging and dependencies is largely out of the control of Valve and should be reported to the package maintainers.

**Comment by krsrdjan** [comment]
My issue is that Ubuntu system have forced number of monitors after I install steam-client package.
So problem is in steam-client package and its dependencies.

Same problem occurs when I download .deb package of steam client from official steam site and install it.

Since this is ValveSoftware support then I believe you should investigate package that is downloaded from your site.

Thank you/

**Comment by kisak-valve** [comment]
Closing pending feedback.
