### ISSUE TITLE
Can't update - Contentfile Locked

### ISSUE THREAD

**Issue by h1z1** [ValveSoftware/steam-for-linux#5955]
#### Your system information

* Steam client version (build number or date):  Dec 4 2018
* Distribution (e.g. Ubuntu):  CentOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Downloading some titles results in Steam erroring out with "Content file locked" on the downloads page.  Expected result -  Steam provides more details as to what is locked.

#### Steps for reproducing this issue:

1. Start Steam
2. Pick a tittle (this is random.. doesn't happen with all but recovering after it does is atm impossible)
3.  Download and/or update forementioned title
4. Cry as your 100G download fails

Although it will enter a "paused" state, something else to note if you leave Steam in this state it will continue to try downloading over and over regardless.   

There are other cases of this error popping up but I've not found any conclusive reason as to why nor what is locked.  It's not a permissions problem nor is the volume out of space. 

The download does complete as it resides in the downloading directory and assuming there is no post setup required, you can run the game after coping those files manually.   

Tried Validating files and  clearing steamcache.  Tried completely redownloading too.

**Comment by kisak-valve** [comment]
Hello @h1z1, do you have multiple Steam libraries and what filesystem(s) are they on?

**Comment by h1z1** [comment]
@kisak-valve  I do indeed.  They are ext4 and zfs.  Tried installing to both.

**Comment by lucifertdark** [comment]
You need to stick to a single file system for Steam, choose one & remove the other.

**Comment by h1z1** [comment]
@lucifertdark  ?  Doesn't happen with all titles nor does it explain what is failing to lock.   Steam itself is on ext4

**Comment by kisak-valve** [comment]
I've got a hunch your issue is related to #4851. It may be worth checking if the games that fail have individual files larger than 2 GB.

**Comment by h1z1** [comment]
GTA5 is indeed one of the t\ww titles locked.  StandOut (748370)  is the another.  I removed both and was able to reinstall StandOut (can't move it in steam because of a pending update...).  GTA will take a bit more time.   

If that is indeed the cause it's worth noting there are others that did not have this problem.  Overload for example.   Only thing I can think of is one folder resides on zfs.   Quotas are enabled to work around the other problem related to free space... there are 22 tickets regarding it.   I also tried installing to the ext4 volumes without success.

**Comment by h1z1** [comment]
Installing GTA to ext4 worked after removing everything but a single download folder.  Steam clearly has some serious problem with zfs and/or locking.

**Comment by Vash63** [comment]
I can confirm that today's Steam Client Beta fixes this for me.

**Comment by kisak-valve** [comment]
Hello @h1z1, are you still experiencing this issue on an up to date system?

**Comment by h1z1** [comment]
@kisak-valve Nope.

**Comment by kisak-valve** [comment]
Thanks for checking, closing.
