### ISSUE TITLE
Steam Library Folders + NTFS -> Problem with filesystem without execute permissions

### ISSUE THREAD

**Issue by LukasThyWalls** [ValveSoftware/steam-for-linux#596]
With the Custom Steam Library Folders fixed https://github.com/ValveSoftware/steam-for-linux/issues/50#issuecomment-11650405 appears other problem:

![newSteamLibraryFolder](https://f.cloud.github.com/assets/1467366/52138/5f854252-59ee-11e2-91d6-46e8d1d3fe48.png)

Sure it's because the NTFS partition like https://github.com/ValveSoftware/steam-for-linux/issues/304 https://github.com/ValveSoftware/steam-for-linux/issues/178 and others, but meanwhile Steam can detect the problem and avoid it, you could be add a support link into the previous window with information and, why not, instructions for change the mounting system to fix the problem.

Edit: I am trying some solutions to fix without any luck. I will post them later

**Comment by tumbly** [comment]
I just encoutered that bug, here is some details:

Debian GNU/Linux 8 (jessie)
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux
Up to date as of today Oct 16

"About Steam" 
Built: Oct 14 2015, at 12:40:46
Steam API: v017
Steam package versions:14444853545

The workaround involving a symlink works like a charm, please add this trick hidden behind a GUI. :hamster:   
That would be sweet for usability as many people facing the problem won't ever find this issue on github.

**Comment by mdalacu** [comment]
Use this:
[](https://mdalacu.blogspot.ro/2018/01/how-to-mount-ntfs-partition-in-linux.html)

**Comment by mdalacu** [comment]
Use this post that i have wrote:
https://mdalacu.blogspot.ro/2018/01/how-to-mount-ntfs-partition-in-linux.html

**Comment by kurumushi** [comment]
@mdalacu 
That doesn't really solve the problem, it just makes every single file on the ntfs partition have 777 permissions. The real issue is a drawback of NTFS, that there is no way to selectively make files and folders have different permisions, it's all or nothing.
