### ISSUE TITLE
Steam tray icon no longer shows a menu on right clicks in kde.

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#5960]
#### Your system information

* Steam client version (build number or date): 1543346820
* Distribution (e.g. Ubuntu):  Ubuntu/Kubuntu 18.10
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I no longer get the tray menu when right-clicking the tray icon in KDE.

#### Steps for reproducing this issue:

1. Attempt to right-click the tray icon.

#### System information
https://gist.github.com/kubast2/68725caf62e97f975129755395bdc057

**Comment by kisak-valve** [comment]
Hello @kubast2, can you list the contents of `<steam dir>/ubuntu12_32/steam-runtime/pinned_libs_*`?

**Comment by kubast2** [comment]
```
.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:
has_pins               libGLU.so.1   libSDL2-2.0.so.0              system_libGLU.so.1   system_libSDL2-2.0.so.0
libdbusmenu-glib.so.4  libopus.so.0  system_libdbusmenu-glib.so.4  system_libopus.so.0

```

**Comment by kubast2** [comment]
Done it works now. o/
