### ISSUE TITLE
Japanese and Chinese are not supported  in friends chat

### ISSUE THREAD

**Issue by FateRover** [ValveSoftware/steam-for-linux#5966]
#### Your system information

* Steam client version (build number or date): 2018-12-14
* Distribution (e.g. Ubuntu): debian testing
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

while i can input japanese or chinese in the chat window,nothing happened,actually i can not switch my input methods to japanese or chinese.
i use fcitx

**Comment by FateRover** [comment]
but   i can input japanese and chinese in dota2

**Comment by kisak-valve** [comment]
Hello @FateRover, this issue is already being tracked at #3255. Closing as a duplicate.
