### ISSUE TITLE
[Bug] Put computer into suspend (laptop close lid), come back, Wishlist won't load, Games list won't load, need to relogin?

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#5971]
#### Your system information

* Steam client version (build number or date): Nov 26 2018, API v018
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No]: No
* Have you checked for system updates?: [Yes/No]: Yes, frequently

XOMG THE WINTER SALE IS UPON US!

I go to my wish list while logged in, and it loads. But I have to go have a shower, and I shut the lid on my laptop, sending it to sleep.

I come back, and I can still check my profile and other stuff, but now my Wishlist says:

> Oops, there's nothing to show here
> There are 0 items on your wishlist, but none of them match the filters you have applied above

And when I go to my profile, the "Games" link on my profile page (to show others what games I have) is just... not there.

This looks to be a credentials issue, so I'm unsure why suspend interrupts this. Games still launch fine.

This is "resolved" by logging out and back in. But that's a real pain in the ass to do just after a basic suspend...

Please look into this so I can spend my money more or something! Yay! :D

**Comment by kisak-valve** [comment]
Hello @BloodyIron, this issue is already being tracked at #474. Closing as a duplicate.
