### ISSUE TITLE
Invisible mouse in overlay for proton games

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/steam-for-linux#5976]
#### Your system information

* Steam client version (build number or date): Dec 14 2018 at 22:19:08
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

##### Expected behaviour:
Opening the overlay should work just like with native games, either via shift + tab or the "guide" button of the controller.

##### Observed behaviour:
With shift + tab, the overlay seems to be working fine, but the mouse is invisible, which makes navigating it quite difficult.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
I picked a small game for testing: Final DOOM

1. Launch it via steam play
2. Activate the steam overlay with shift + tab: elements react to the mouse, but you can't see the mouse itself

The mouse works in the big picture overlay, but both mouse and buttons navigation is extremely slow (feeling like ~3FPS).
This might be related to my desktop environment: plasma 5 (dark theme), with X.org.

**Comment by kisak-valve** [comment]
Hello @MayeulC, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/168. Closing as a duplicate.

**Comment by MayeulC** [comment]
My bad, I didn't check that repository first. Thank you!
