### ISSUE TITLE
MIC is not working in DOTA 2 on Linux

### ISSUE THREAD

**Issue by iamdarkmatter** [ValveSoftware/steam-for-linux#5977]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Closing as there's no actionable information in this issue report. Please use the [Dota-2](https://github.com/ValveSoftware/Dota-2) issue tracker for issues with the linux variant of Dota-2.
