### ISSUE TITLE
Nintendo Switch Pro Controller only functions in big picture mode

### ISSUE THREAD

**Issue by Mullato** [ValveSoftware/steam-for-linux#5986]
* Steam client version (build number or date): 1543346820
* Distribution (e.g. Ubuntu): Debian 9 Stretch
* Opted into Steam client beta?: [No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After connecting the switch pro controller either via USB or via bluetooth, this same issue will occur. The controller will work perfectly fine in big picture mode, however no buttons will function properly on the controller other than the screenshot button once any tested game is loaded. (I have been testing this on Stardew Valley and Enter the Gungeon with various controller configs) Notably, though, if you hold the home button, the joystick will work as intended. I have already updated udev rules.

#### Steps for reproducing this issue:

1. Connect controller via USB or Bluetooth
2. Enter big picture mode
3. Navigate to a game via big picture mode with controller and attempt to play it

**Comment by kisak-valve** [comment]
Hello @Mullato, the `steam-devices` package should provide the udev rules needed to use the Switch Pro controller with Steam, however, the version in Debian Stretch's repos is too old and does not include the Switch Pro. The closest package to your system that has that controller is [`steam-devices`](https://packages.debian.org/buster/steam-devices) from Buster. You should consider slamming that in to place or extend the current udev rule set to include the relevant entries.

**Comment by Mullato** [comment]
Thank you so much! This worked like a charm. You have no idea how much I appreciate the rapid response @kisak-valve
