### ISSUE TITLE
Feature request: enable tabbed browsing

### ISSUE THREAD

**Issue by darealshinji** [ValveSoftware/steam-for-linux#5990]
Enabling tabbed browsing would be very useful. You could i.e. keep a tab with a community guide open and at the same time browse the Steam community or workshop.

**Comment by Ruedii** [comment]
Agreed, but this should be general steam client, I think.

It would be nice.   Add a web browser panel with tabbed browser.  

Also, using a disk heap for the web browser instead of reloading it should make it pull from idle faster if it gets suspended due to memory pressure.

**Comment by kisak-valve** [comment]
Hello @darealshinji, this was implemented at some point. If you right click on a link, there is now an `Open link in new tab` option. Alternatively, you can control + click on links.
