### ISSUE TITLE
Centos 7.6

### ISSUE THREAD

**Issue by mzigaib** [ValveSoftware/steam-for-linux#5991]
I am getting an error trying to run steam on my linux distro.

STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mzigaib/.local/share/Steam/steam.sh: line 828: /home/mzigaib/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Installing breakpad exception handler for appid(steam)/version(0)
/home/mzigaib/.local/share/Steam/steam.sh: line 889:  3319 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

It was working before a new fresh install that I did recently I got in touch with valve and they told me that maybe you guys could help me to make it work again.

Thanks.

**Comment by mzigaib** [comment]
It seems that some scripts are missing in this installation like "run.sh", maybe a bug in this installation.

**Comment by h1z1** [comment]
Which rpm did you install steam with?

**Comment by mzigaib** [comment]
I did install through the epel repository.

**Comment by mzigaib** [comment]
I also tried to convert the .deb from the steam site and the result is the same, it installs but when I try to run it shows the same error.

**Comment by h1z1** [comment]
Granted it's fairly old but should bootstrap fine.   I don't get that with the steam rpm from epel.   Which github repo are you refering to?

**Comment by mzigaib** [comment]
I am sorry, it seems that the right repository where I am installing from is RPMFusion.
[https://negativo17.org/steam-for-centos-rhel-7/](url)

 The github which I am referring to is this very one here [https://github.com/ValveSoftware/steam-runtime](url)

What do you mean it should bootstrap fine? I am not a programmer but for what I understand you are saying that it should work correctly so why it is not any tips?

**Comment by mzigaib** [comment]
No tips?

**Comment by h1z1** [comment]
Steam will check for updates when it starts.  The process of doing that is refered to as a bootstrap.  The RPM itself doesn't contain really any of a full steam client as it's downloaded on first run.   

Not sure what doing an entire reinstall entails but it looks like either steam was not completely reinstalled or something borked it.   I would verify steam and start with a new config

``` rpm --verify -v steam```

```
  mv -v ~/.steam ~/.steam.bak

 
  ## Ignore not found errors.. just a precaution
  rm -fv ~/.steampath ~/.steampid

  ##   Make sure steam is not running
  ps ax |grep -i steam
```

Then run steam, it should go through a new setup.  Steam has a reset feature but given the unknown state of your config I wouldn't run it.   You can manually move installed games from  your old steam install.

**Comment by mzigaib** [comment]
Thanks for the feedback but the result is the same, after the verify command:

.........  c /etc/profile.d/steam.csh
.........  c /etc/profile.d/steam.sh
.........    /usr/bin/steam
.........    /usr/lib/firewalld/services/steam.xml
.........    /usr/lib/steam
.........    /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz
.........    /usr/lib/systemd/system.conf.d
.........    /usr/lib/systemd/system.conf.d/01-steam.conf
.........    /usr/lib/systemd/user.conf.d
.........    /usr/lib/systemd/user.conf.d/01-steam.conf
.........    /usr/lib/udev/rules.d/51-these-are-not-joysticks-rm.rules
.........    /usr/lib/udev/rules.d/60-steam-input.rules
.........    /usr/lib/udev/rules.d/60-steam-vr.rules
.........    /usr/lib/udev/rules.d/99-shield-controller.rules
.........    /usr/share/appdata/steam.appdata.xml
.........    /usr/share/applications/steam.desktop
.........    /usr/share/doc/steam-1.0.0.59
.........  d /usr/share/doc/steam-1.0.0.59/README
.........  d /usr/share/doc/steam-1.0.0.59/README.Fedora
.........  d /usr/share/doc/steam-1.0.0.59/changelog
.........    /usr/share/icons/hicolor/16x16/apps/steam.png
.........    /usr/share/icons/hicolor/24x24/apps/steam.png
.........    /usr/share/icons/hicolor/256x256/apps/steam.png
.........    /usr/share/icons/hicolor/32x32/apps/steam.png
.........    /usr/share/icons/hicolor/48x48/apps/steam.png
.........    /usr/share/licenses/steam-1.0.0.59
.........  l /usr/share/licenses/steam-1.0.0.59/COPYING
.........  l /usr/share/licenses/steam-1.0.0.59/steam_subscriber_agreement.txt
.........  d /usr/share/man/man6/steam.6.gz
.........    /usr/share/pixmaps/steam.png
.........    /usr/share/pixmaps/steam_tray_mono.png

And then after the other commands the same result:

Repairing installation, linking /home/mzigaib/.steam/steam to /home/mzigaib/.local/share/Steam
Running Steam on centos 7 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mzigaib/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 7: syntax error near unexpected token `newline'
/home/mzigaib/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 7: `<!DOCTYPE html>'
Installing breakpad exception handler for appid(steam)/version(0)
/home/mzigaib/.local/share/Steam/steam.sh: line 889: 28837 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

I don't know if this is just in Centos or if someone else with Centos have the same issue, would be good to know, all that I know is that it was working before and now it doesn't to be fair Centos just had some updates that messed somethings up but nothing big I also don't know if this can be a cause of this malfunction but I would really hope to get it working again, I just can't change the distro. Any help will be welcome thanks again for the feedback.

**Comment by h1z1** [comment]
> Repairing installation, linking /home/mzigaib/.steam/steam to /home/mzigaib/.local/share/Steam

Are you sure you moved .steam to .steam.bak?  You can rm / move /home/mzigaib/.local/share/Steam as well.

If you did the commands I gave it should have reinstalled steam.

**Comment by mzigaib** [comment]
Yes I am sure, but I'll do it again to be sure I also already tried to remove the steam and manually deleted all those directories and installed it again and I also had the same result.
I also in my laptop which have the same system got a different but also a error:

Running Steam on centos 7 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/mzigaib/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /lib/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
mv: cannot stat ‘/home/mzigaib/.steam/registry.vdf’: No such file or directory
Installing bootstrap /home/mzigaib/.local/share/Steam/bootstrap.tar.xz
Reset complete!
Restarting Steam by request...
Running Steam on centos 7 64-bit
STEAM_RUNTIME has been set by the user to: /home/mzigaib/.local/share/Steam/ubuntu12_32/steam-runtime
Installing breakpad exception handler for appid(steam)/version(0_client)
/home/mzigaib/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /lib/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds

It is the first time i installed it there.

**Comment by kisak-valve** [comment]
Hello @mzigaib, that's #4816, and has various workarounds that are only needed on first run.

Also, the 1.0.0.56 steam package should not hit that issue in most cases.

**Comment by mzigaib** [comment]
Thanks for the feedback, yeah I ran steam on Centos several times before with no issues but now something is different I'll take a look on the thread you linked and i'll let you know if i got some progress.
Thanks.

**Comment by mzigaib** [comment]
I was about to quit trying to use steam on Centos but there was a steam update and baamm, working again. it seems it wast a matter of a new update but i'll try the flatpak option next time.

**Comment by mzigaib** [comment]
I am having the same issue again after a fresh install on my system. I turned to Flatpak but it doesn't recognize the games installed on my external drive.

Any tips?

**Comment by h1z1** [comment]
Any chance you ended up running steam as different users?  There are a few old bugs that appear never were patched upstream with regard to permissions


```+ cd /home/steam2/.local/share/Steam
++ command -v tee
+ '[' /bin/tee '!=' '' ']'
+ mkdir -p --mode=777 /tmp/dumps
mkdir: cannot create directory ‘/tmp/dumps’: File exists
+ [[ -f /tmp/dumps/steam2_stdout.txt ]]
+ exec -a /home/steam2/.local/share/Steam/steam.sh /home/steam2/.local/share/Steam/steam.sh
+ tee /tmp/dumps/steam2_stdout.txt
tee: /tmp/dumps/steam2_stdout.txt: Not a directory
/home/steam2/.local/share/Steam/steam.sh: line 99: no match: **: 
+ rm -f /tmp/steam_chrome_shmem```

**Comment by kb-1000** [comment]
@mzigaib Flatpak uses a sandbox for running applications. This just means that the application doesn't request access to those external drives, and, as a result, doesn't get access.

**Comment by kisak-valve** [comment]
Hello @mzigaib, are you still experiencing this issue on an up to date system?

It's not really clear what's gone wrong here besides the Steam runtime (`~/.local/share/Steam/ubuntu12_32/steam-runtime`) being partially or completely missing.

**Comment by kisak-valve** [comment]
Closing pending feedback.
