### ISSUE TITLE
[Steam Link] Laggy audio, in Big Picture, in games, anywhere streaming

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#5992]
* Steam client version (build number or date): Dec 14 2018
* Distribution (e.g. Ubuntu): Ubuntu 18.10 + XFCE4
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Okay so first, the video does not appear laggy, just the audio. There may be one or two frames of video lag, but the audio lag is multiple seconds.

This lag does not happen when the Steam Link is not connected to a computer. But as soon as it is, the audio is then laggy.

I have tried enabling/disabling many hardware encoding options on the Host in the Steam settings, disabling hardware decoding on the client.

My Steam Link is connected wirelessly, but my WAP is a Ubiquiti UAP-AC-PRO, which effectively brute-forces the quality of the wireless. Network testing shows <1ms of lag between the Steam Link and the target Desktop. Furthermore, the overlay shows 30ms of video lag, but no info about audio. and <1ms of network lag. I can easily see upwards of 5mbps to 10mbps for the content being streamed (1080p), set to "Fast" (instead of balanced/best).

I am extremely doubtful a wired connection will change anything whatsoever, as the evidence suggests otherwise, so let's look elsewhere first please. But at this point, I can't find any reason why my audio is laggy. Desktop is connected via wired gigabit, and entire wired network is gigabit.

Specs:
* intel i7-980x
* Asus Xonar DXG soundcard
* 24GB RAM
* Ubuntu 18.10 + XFCE4 + Compiz
* 3x1920x1080 (all landscape), centre (main) monitor is set to 120hz, the others are set to 60hz

Hopefully I can get help with this, it seems plenty of other people have audio lag problems with no solutions found :( I don't want to bin my Steam Link, this is one of the last hurdles I have for it.

**Comment by cminnoy** [comment]
I noticed that my steam link suffers from two similar phenomena:
1. When you are gaming, audio starts to get behind. This becomes very clear when you stream a video from the host (for example via Kodi as non-steam application). The delay starts to build up slowly. But when you stop streaming during playback, and reconnect (keeping the app running), you see the delay is gone. By the reconnect, the SteamLink again got in sync with the host audio stream.
2. After a while, the sound starts become scratchy. This is also a sync problem, but maybe from a different kind. It may well be that the steam link is playing parts of memory that are not allocated anymore, or something. Again, when you stop streaming and reconnect the scratchy thing is gone.

Maybe both are related or not. It could be that the steam link tries to play more audio buffers than it should, builing up a delay slowly over time and in the end getting scratchy sound....

**Comment by LeonardKoenig** [comment]
Same problem here, I've gone through another proposed solution to limit the bandwidth (although they are connected via a Gigabit switch, this should be enough bandwidth...) but this didn't work for me at least.

**Comment by LeonardKoenig** [comment]
probably a dup of https://github.com/ValveSoftware/steam-for-linux/issues/6749

**Comment by LeonardKoenig** [comment]
possibly related to https://github.com/ValveSoftware/steam-for-linux/issues/5187#issuecomment-475568313

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
