### ISSUE TITLE
[Feature request] Any Debug Information Whatsoever on Game Crash

### ISSUE THREAD

**Issue by cwh1te** [ValveSoftware/steam-for-linux#5993]
The number of games that fail silently and produce no logs or error messages is too damn high. Please fix.

I realize this is unhelpful but so is the way the Steam client handles almost everything.

**Comment by kisak-valve** [comment]
Hello @cwh1te, in general, you can use a debugger with the GAME_DEBUGGER env variable and Steam also has a general log at `/tmp/dumps/<username>_stdout.txt` which catches output from games as well. If there's no hints there, then either the game engine is doing its own logging somewhere else or the distro's packaging for steam changed how logging is handled (Debian).
