### ISSUE TITLE
SteamCMD sometime abort operation

### ISSUE THREAD

**Issue by Messiah93** [ValveSoftware/steam-for-linux#5995]
#### Your system information

OS: ArchLinux x64 last version (RR)
* Have you checked for system updates?: Yes, today (also reinstall SteamCMD)

#### Please describe your issue in as much detail as possible:
Since a few days, when I want to update my Gmod or CS:GO server with SteamCMD, sometime, SteamCMD abort the operation itself... Like this:

https://i.gyazo.com/ef1ac7ef7f4d16ccb5f5ad17495a42a8.png

I never had the problem before. But the update process is automatic at 6:00am everydays, if it does not update, it can potentially be a problem.

#### Steps for reproducing this issue:

1. Download and install SteamCMD
2. Install a Gmod server for exemple (~/Steam/steamcmd.sh +login anonymous +force_install_dir $HERE +app_update 4020 validate +quit)
3. When server is installed, try to update it (same command as above) . Hopefully you'll come across the same problem as me.

**Comment by kisak-valve** [comment]
Hello @Messiah93, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
