### ISSUE TITLE
Pressing "View All Achievements" redirects to profile

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#5996]
#### Your system information

* Steam client version (build number or date): Built: Dec 14, 2018, at 22:19:08. Steam API: v018. Steam package versions: 1544834093.
* Distribution (e.g. Ubuntu): Kubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When clicking on the "View All Achievements" button on a game page in my library, Steam client sometimes opens my profile (i.e. the page that is accessible via \<Account\>->Profile in the top menu) instead of the list of achievements for the particular game. This happens with different games and not 100% reliably - sometimes it works as intended from the first time, and sometimes I have to click "View All Achievements", then back from the Profile page and "View All Achievements" again a few times before I get to the achievements page.

#### Steps for reproducing this issue:

1. Go to your library.
2. Select a game.
3. Click on the "View All Achievements" button on the game page.

**Comment by nightsky30** [comment]
I'm actually seeing the same behavior for achievements and other steam links/menu items like "new comments".  And my profile is set to private.  So when it happens to me I see a profile page that says my profile is private and prevents me from viewing it...as if I were not logged into Steam and viewing it publicly.

This makes me think that it is related to all the other issues with our Steam sessions going dormant.  And the refresh is waking our sessions back up.  Thus the second attempt works.

**Comment by Lastique** [comment]
In my case, the second attempt doesn't always work, although it often does.

**Comment by lucifertdark** [comment]
For me it redirects me to a page that says "this profile is set to private" as if I'm logged out of my account, second attempt usually goes to the right place.

**Comment by ijacquez** [comment]
I'm seeing this issue on Linux as well.

**Comment by nightsky30** [comment]
I'm not experiencing the issue anymore with achievements or other pages after updating today.  I think this might have been fixed with the latest Steam Beta - 02/02/2019

> Fixed issue "Servers content unreachable" related to some IPv6 configurations

**Comment by kribjo** [comment]
I have this issue now with Feb 18 2019 build of Steam on Windows.

**Comment by kribjo** [comment]
Going beck and clicking "View all achievements" again does not help, even with multiple tries.

**Comment by kribjo** [comment]
OK, in my case it seems this can be because the game is not officially released yet for some days. Still wish I could see which achievements I have unlocked and which are still locked.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Lastique** [comment]
I haven't seen this for a while now. Doesn't happen to me with Steam client version 1620684960 (built on May 7 2021, at 23:55:52).

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.

**Comment by madmagic007** [comment]
still happening for me on some users, seems to be linked with them disabling game details to private and setting it to friends only again afterwards, evem tho game details are visible, the achievements arent.
