### ISSUE TITLE
PS4 controller not recognized

### ISSUE THREAD

**Issue by TheCoder3156** [ValveSoftware/steam-for-linux#5997]
#### Your system information

* Steam client version (build number or date): Built Dec. 14 2018 at 22:19:08
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam does not recognize my ps4 controller when Sony controller support is on (Wired or wireless).

#### Steps for reproducing this issue:

1. Connect ps4 controller.
2. Open steam client
3. Steam will say no controllers recognized under settings > controller > general controller settings

**Comment by kisak-valve** [comment]
Hello @TheCoder3156, please verify you have the `steam-devices` package installed.

**Comment by TheCoder3156** [comment]
Resolved the problem. Thanks for your help.
