### ISSUE TITLE
[Linux] Error while updating | Broken update file

### ISSUE THREAD

**Issue by JanSeW** [ValveSoftware/steam-for-linux#5998]
#### Your system information

* System information
https://gist.github.com/JanSeW/c732098b41ad1e9f29e824850abd00fa
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After the last big update my Linux machine is no longer able to start CS:GO. At each start a 7.8 GB update is downloaded first, but the following error message appears:

![bildschirmfoto vom 2018-12-29 15-04-42](https://user-images.githubusercontent.com/16487822/50539381-d394b080-0b7f-11e9-8f16-e479ac5ada2b.png)

It looks like the update files are broken. Anyway, I reinstalled the CS:GO section and also repaired the local files (i.e. what's on the Steam help page).
Is this bug or its solution known?
Thxalot,
JanSe

**Comment by JanSeW** [comment]
Okay, now I feel really stupid. The library in which I first installed CS:GO is on a hard disk, which I share with the Windows installation of Steam (NTFS). Now I have placed CS:GO directly on the Ext4 disk, and lo and behold, it works. What is strange is that there were no such problems under my former Manjaro installation.

Thxalot,
JanSe

**Comment by kisak-valve** [comment]
Thanks, that makes this the issue being tracked at #4800.
