### ISSUE TITLE
Can't type russian text, but can paste it

### ISSUE THREAD

**Issue by drradio** [ValveSoftware/steam-for-linux#6005]
#### System information

* Steam client version (build number or date): 1544834093 (Dec 14 2018 22:19:09)
* Distribution: Debian GNU/Linux Stretch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I can't type russian (cyrillic) text from keyboard to any input form, but it's possible to paste text typed in editor (another programm) to the form. Typing leads to no symbol is appeared on the input form. English text works fine.
I think it is because somewhere in libraries is broken.

#### Steps for reproducing this issue:

1. Select input form (for example, in the chat window);
2. Try to type some russian text;
3. Frustrate;
4. Try to paste some russian text;
5. Voilà!

**Comment by sizeofbool** [comment]
@Plagman I can reproduce this issue, but only inside In-Game Overlay. Typing in chat windows while not playing games is working as intended.

My specs:
CPU: i5-6600
VGA: nVidia GTX1060 6Gb (proprietary driver 410.78 backported to stretch)
OS: Debian 9 'stretch' x86_64 (kernel 4.15)
DE: Xfce 4.12

**Comment by zebh** [comment]
This can also be reproduced with Swedish. I can't type the very important "å, ä, ö" characters while in the overlay. Works just fine otherwise, and the overlay shows the characters just fine.

Could it be that the overlay is forced with en_US locale? I know that was a workaround for international players of source games in the past which assumed en_US or C locale and would not start with other locales.

Locale: sv_SE.UTF-8
Steam language: Swedish

**Comment by drradio** [comment]
I found solution: Steam requires en_US.utf8 locale, so I just installed that locale.

**Comment by CandyFiend** [comment]
> I found solution: Steam requires en_US.utf8 locale, so I just installed that locale.

Its really work for debian 9, russian (cyrillic).
1) go to terminal (откройте терминал / консоль bash)
2) type `sudo kate` (напишите `sudo kate`)
3) type password (введите пароль)
4) open in kate /etc/locale.gen (откройте в kate /etc/locale.gen)
5) delete `# ` in `# en_US.UTF-8 UTF-8` (удалите `# ` в `# en_US.UTF-8 UTF-8`)
6) save and close kate (сохраните и закройте kate)
7) type in terminal `cd /usr/sbin` (напишите в терминале `cd /usr/sbin` )
8) type `sudo locale-gen` (напишите `sudo locale-gen`)
9) type password (введите пароль)
10) restart Steam (перезапустите steam)
11) FINISH (try/ пробуй)

**Comment by kolayne** [comment]
@drradio, @CandyFiend This didn't work for me :(
Linux mint 19.3
Cinnamon 4.4.8
Intel Core i5-7200U
Nvidia Geforce 940MX (driver 435.21)

**Comment by sizeofbool** [comment]
@kisak-valve I still have this issue too, but only in some games, like ["Slay The Spire"](https://store.steampowered.com/app/646570/Slay_the_Spire/). Workarounds offered by @CandyFiend didn't worked. (I have both locales enabled and generated already.)
Should this issue be reopened, or we have to report this problem to affected game's developer?
If the latter, what is the best way to do it, e.g. through Steam Support or Steam Community forums?

**Comment by kisak-valve** [comment]
Hello @sizeofbool, I took a look around and #2122 is open and tracking your issue. Feel free to add your experience to that issue report.

**Comment by steamlinux** [comment]
I can confirm this bug. In steam (overlay) another input langs works, but in game doesn't work. example Dead By Daylight, with active russian lang I cant type in chat and I cant movement (w a s d) but digits work
