### ISSUE TITLE
[Feature Request] Inhibit screensaver when a game is running

### ISSUE THREAD

**Issue by TooManyErrors** [ValveSoftware/steam-for-linux#6009]
#### Your system information

* Steam client version (build number or date): Nov 26 2018, at 20:15:48
* Distribution (e.g. Ubuntu): Kubuntu 18.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When a game is running, Steam should send screensaver inhibition signals to prevent systems from enabling screensavers, lock-screens, or entering sleep mode. This is particularly useful if someone is using a controller to play a game, as desktop environments may not monitor controller inputs when checking for idleness.

Utilizing the D-Bus service org.freedesktop.ScreenSaver (https://people.freedesktop.org/~hadess/idle-inhibition-spec/index.html) should solve this problem. Although it doesn't seem to be a formal standard, it is de-facto supported by (at least) KDE Plasma 5, GNOME 3, and XFCE.

There is a similar report at ValveSoftware/Proton#287 but no progress on a solution seems to have been made.

**Comment by kisak-valve** [comment]
Hello @TooManyErrors, this issue is already being tracked at #1693. Closing as a duplicate.

**Comment by kisak-valve** [comment]
And ... I'm going to disagree with myself. DPMS management and screensaver management should be tracked separately.

**Comment by TooManyErrors** [comment]
From what I can tell org.freedesktop.ScreenSaver universally controls idleness behaviors, including both DPMS and screensavers. I'll just close this issue and post my suggestion there instead, unless you think there still is a reason for this issue to be open.
