### ISSUE TITLE
steam crash segfault under unity-DE ubuntu 18.10

### ISSUE THREAD

**Issue by misac1987** [ValveSoftware/steam-for-linux#6011]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): ubuntu 18.10
* Opted into Steam client beta?: [Yes/No]: No
* Have you checked for system updates?: [Yes/No]:Yes

Last steam update later steam client crash under unity-DE 
When I started on terminal:
-----
Running Steam on ubuntu 18.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1543346820)
Installing breakpad exception handler for appid(steam)/version(1543346820)
Installing breakpad exception handler for appid(steam)/version(1543346820)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module **"atk-bridge"**
Gtk-Message: Failed to load module "unity-gtk-module"
crash_20190106203529_1.dmp[31014]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190106203529_1.dmp
/home/recep/.local/share/Steam/steam.sh: line 889: 31000 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190106203529_1.dmp[31014]: Finished uploading minidump (out-of-process): success = yes
crash_20190106203529_1.dmp[31014]: response: CrashID=bp-3faec89f-1b34-41e3-97cd-952722190106
crash_20190106203529_1.dmp[31014]: file ''/tmp/dumps/crash_20190106203529_1.dmp'', upload yes: ''CrashID=bp-3faec89f-1b34-41e3-97cd-952722190106''

**Comment by kisak-valve** [comment]
Hello @misac1987, can you throw `/tmp/dumps/crash_20190106203529_1.dmp` in an archive and drag and drop the archive into the comment box?

**Comment by misac1987** [comment]
sure
[crash_20190106203529_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2730911/crash_20190106203529_1.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump appears to be a null pointer SIGSEGV in libgtk3-nocsd.so.0. Can you list the contents of `<steam dir>/ubuntu12_32/steam-runtime/pinned_libs_32`? If it's empty, please delete the pinned_libs_* folders so that steam will regenerate them.

**Comment by misac1987** [comment]
Sorry rebuild but crash again.I dont know irrelevent but When I use gnome-shell, look great, but under unity 7.5 crash
```
recep@MSI-CR61-3M:~$ steam
Running Steam on ubuntu 18.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Found newer runtime version for 64-bit libopus.so.0. Host: 0.6.1 Runtime: 0.7.0
Found newer runtime version for 64-bit libSDL2-2.0.so.0. Host: 0.8.0 Runtime: 0.9.0
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libdbusmenu-gtk.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libpangox-1.0.so.0. Host: 0.0.0 Runtime: 0.3000.0
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Installing breakpad exception handler for appid(steam)/version(1543346820)
Installing breakpad exception handler for appid(steam)/version(1543346820)
Installing breakpad exception handler for appid(steam)/version(1543346820)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
crash_20190107061609_1.dmp[635]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190107061609_1.dmp
/home/recep/.local/share/Steam/steam.sh: line 889:   620 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190107061609_1.dmp[635]: Finished uploading minidump (out-of-process): success = yes
crash_20190107061609_1.dmp[635]: response: CrashID=bp-b082e6be-c4fe-4672-bd08-260912190106
crash_20190107061609_1.dmp[635]: file ''/tmp/dumps/crash_20190107061609_1.dmp'', upload yes: ''CrashID=bp-b082e6be-c4fe-4672-bd08-260912190106''
```

[crash_20190107061609_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/2731288/crash_20190107061609_1.zip)

**Comment by misac1987** [comment]
when I try like that its run with "ld_preload" 
$: `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 steam`

Running Steam on ubuntu 18.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1548979876)
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[0202/180012.512917:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: browser
[0202/180012.571738:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0202/180012.571986:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1548976293
[0202/180012.572006:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0202/180012.572022:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
[0202/180012.586889:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/pgriffais/src/Vulkan/base/vulkanexamplebase.cpp at line 823
vulkandriverquery: /home/pgriffais/src/Vulkan/base/vulkanexamplebase.cpp:823: void VulkanExampleBase::initVulkan(): Assertion `res == VK_SUCCESS' failed.
Aborted
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)

(steam:11213): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Opted-in Controller Mask for AppId 0: 0
Installing breakpad exception handler for appid(steam)/version(1548979876)
Installing breakpad exception handler for appid(steam)/version(1548979876)
roaming config store loaded successfully - 3268 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1548979876)
[0202/180210.033055:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
[0202/180210.125394:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0202/180210.125649:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1548976293
[0202/180210.125668:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0202/180210.125684:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
[0202/180210.127461:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: gpu-process
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/recep/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 120.47 seconds
[0202/180211.852343:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
JS method call WebChat.GetWebChatLanguage with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
JS method call WebChat.GetCurrentUserAccountID with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
JS method call FriendSettings.RegisterForSettingsChanges with 1 arguments
JS method call WebChat.RegisterForPushToTalkStateChange with 1 arguments
JS method call WebChat.SetVoiceChatActive with 1 arguments
JS method call WebChat.RegisterForComputerActiveStateChange with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call SharedConnection.AllocateSharedConnection with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call FriendSettings.GetEnabledFeatures with 1 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.SetString with 2 arguments
JS method call WebChat.SetPushToTalkHotKey with 1 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:11213): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
JS method call Storage.SetString with 2 arguments
[0202/180242.063538:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
JS method call WebChat.GetWebChatURL with 1 arguments
Exiting workitem thread
[2019-02-02 18:00:08] Startup - updater built Jan 31 2019 23:10:49
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-02-02 18:00:09] Checking for update on startup
[2019-02-02 18:00:09] Checking for available updates...
[2019-02-02 18:00:09] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-02-02 18:00:10] Download skipped: /client/steam_client_ubuntu12 version 1548979876, installed version 1548979876
[2019-02-02 18:00:10] Nothing to do
[2019-02-02 18:00:10] Verifying installation...
[2019-02-02 18:00:10] Performing checksum verification of executable files
[2019-02-02 18:00:11] Verification complete
[2019-02-02 18:02:42] Background update loop checking for update. . .
[2019-02-02 18:02:42] Checking for available updates...
[2019-02-02 18:02:42] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-02-02 18:02:43] Download skipped by HTTP 304 Not Modified
[2019-02-02 18:02:43] Nothing to do
[2019-02-02 18:02:51] Shutdown

**Comment by misac1987** [comment]
when I uninstall libgtk3-nocsd.deb it's run normally 10x for help

**Comment by kisak-valve** [comment]
Hello @misac1987, it looks like this is not a Steam client issue. libgtk3-nocsd.so.0 was also evaluated over on the Steam runtime's side and was blocked https://github.com/ValveSoftware/steam-runtime/issues/286#issuecomment-716551349.

While that issue report doesn't directly apply to this scenario, any issues with that library should be handled by the library's dev(s). Also, Unity DE is less popular than it once was, so most users are less likely to encounter this unless they're specifically looking to reproduce it.
