### ISSUE TITLE
Installing any game with Steamplay/Proton breaks native Kerbal Space Program

### ISSUE THREAD

**Issue by mastersta** [ValveSoftware/steam-for-linux#6012]
**Issue:** Installing any Windows game via SteamPlay, whitelisted or not, prevents the Linux-native version of Kerbal Space Program from running.

**Reproduction Steps:**

1. Install any Windows game via SteamPlay (whitelisted or not does not make a difference). Haven't confirmed whether you have to run the game or not.
2. Install Kerbal Space Program's native Linux version. (May be done prior to step 1)
3. Attempt to run Kerbal Space Program via any means (Steam launcher, executable, command-line). Game will not launch into loading screen.

**Logs:** See [my post on the KSP forums](https://forum.kerbalspaceprogram.com/index.php?/topic/181005-linux-ksp-fails-to-launch-on-my-system-regardless-of-game-version/) for detailed logs.

**Comment by kisak-valve** [comment]
Hello @mastersta, I've transferred this issue over to the steam-for-linux issue tracker because the affected game isn't actually using Proton (or at least it's not supposed to be).

**Comment by lucifertdark** [comment]
I just put something into orbit on KSP with multiple Proton enabled games installed, no problems here, you sure it's not your drivers that are the problem, they do appear to be older than current, LLVM 6 is not current.

**Comment by mastersta** [comment]
Closing this issue because I can no longer reproduce the issue.

**Comment by byte1024** [comment]
I really think this was a coincidence. They only way this should happen is if Steam somehow caused something with Proton (just a download maybe) to block native. More than likely that would be a hot topic with many people having the problem not just one.
