### ISSUE TITLE
Couldn't set up Steam  Data ubuntu 18.04

### ISSUE THREAD

**Issue by Gyankoos** [ValveSoftware/steam-for-linux#6016]
Your system information

* Steam client version (build number or date): 9/jan/19
* Distribution : ubuntu 18.04 
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

1. Dowload the Steam launcher from the oficial website
2. Go to the sofware manager in order to install it
3. Install it
4. click launch
5. it doesn't work, shows this  error
![screenshot from 2019-01-07 19-07-44](https://user-images.githubusercontent.com/46535695/50916294-0588fb00-143b-11e9-8f42-ef069328c491.png)

**Comment by kisak-valve** [comment]
Hello @Gyankoos, does running steam from a terminal give any hints?

**Comment by MasterCATZ** [comment]
try this in terminal where you downloaded file 
sudo dpkg -i  steam_latest.deb

**Comment by kisak-valve** [comment]
Closing due to lack of feedback.
