### ISSUE TITLE
Steam's useless recovery procedure

### ISSUE THREAD

**Issue by fliteshare** [ValveSoftware/steam-for-linux#6017]
AMD FX-8370 Eight-Core @ 8x 4.334GHz [40.0°C]
GPU: GeForce GTX 1080 Ti
RAM: 1094MiB / 32178MiB
Kernel: x86_64 Linux 4.18.0-13-generic
OS: Mint 19.1 tessa
MATE 1.20.0
Compiz
Steam client: 2019-01-04 23:23:48
API: v018
Package versions: 1546909276

After upgrade from LinuxMint 19.0 to LinuxMint 19.1
ETS2 and ATS couldn't be restored from the backup files.
There are several issues with the Steam recovery procedure.

a) Backup files are by default send to a HIDDEN directory.
"/home/username/.local/share/Steam/Backups"
Typical M$windows blunder !
On real computers you want the standard (sysop) backup procedure to copy files to the external backup media. Hiding backups is nothing short of making sure they won't be found.
May is suggest a directory called "Archive" on the user home disk/partition  

b) Restore procedure does NOT find the backup files.
Not even the default (hidden) directory.
Restore doesn't correctly see the restore media and actually "makes up" non-existing directories.
(is this a btrfs thing ?)

c) Creating those non-existing directories and placing the backup files in them does NOT make the restore procedure FIND the backup files.
(is this another btrfs thing ?)

d) after spoofing Steam by having it look at an actual existing directory: "Pictures".
And placing the Backup files in that Pictures directory
It did find the Backup files.
And actually started to PRETEND to "recover" the ETS2 and ATS games.
Too bad for me that after this so called "recovery" was completed.
The games were installed, but in such a state that everything was reset to initialization values.
- Re-fill in your company name
- Select a picture for yourself 
etc..etc..etc.

Could've saved myself a couple of days of frustration in attempting to "restore" anything and just freshly reinstall the bloody games. Because that's what it boiled down to.

How about Steam dictating that your game programmers create a "scoreboard" file to be backupped and restored into a game. Instead of the superfluous stuff that already gets downloaded from the Steam website anyway.

**Comment by kisak-valve** [comment]
Hello @fliteshare, first of all, multi-issue issue reports are bad for any issue tracker, in the future, please use separate issue reports for each issue after searching existing issues.

a) Looks like the default folder is `<steam install dir>/Backups` and you're expected to replace it with your preferred storage location. There isn't a simple way to guess where you want that to be, so Steam defaults to a location it definitely can write to.

b & c) Restoring a game from backup is looking for an individual backup, not a collection of backups (e.g. .../Backups/Backupname/)

d) The game backup is to save on download bandwidth on game content, not user data. If the game pushes game saves to the steam cloud, then your saves should have been pulled down from there.
