### ISSUE TITLE
No steam logon after disconnect ( dota 2 game keep disconecting )

### ISSUE THREAD

**Issue by lynx29** [ValveSoftware/steam-for-linux#6018]
Good day! I running steam on both windows and linux os and mostly playing dota 2 and   cs go. Is it a default behavior or a bug in steam on linux machine when playing dota 2 if wan link would go down momentarily and goes up after a minute and all the machine reconnected to the game. After 3 to 5 minutes the machine with linux os would disconnect again from the server if just clicking reconnect and continue playing same thing happen after 3 to 5 minutes but on windows os this thing is not happening you could experience smooth playing without disconnect and reconnect after that initial disconnect. My solution for that disconnect and reconnect in linux is to close dota 2 and steam and log-in again and reconnect to game by doing that disconnect and reconnect would not happen after that initial disconnect. I hope dota 2 running on  linux could mirror that on windows when our wan link would go down momentarily and goes up again,  It can reconnect with out  the need to close steam and re-login again.

**Comment by kisak-valve** [comment]
Hello @lynx29, this issue is already being tracked in various issue reports. In a quick search I can point towards #4917 and https://github.com/ValveSoftware/Dota-2/issues/1466. Closing as a duplicate.
