### ISSUE TITLE
Artifact crash on launch (llvm OOM)

### ISSUE THREAD

**Issue by her001** [ValveSoftware/steam-for-linux#6020]
### System information

* Steam client version: Jan 4 2019, 23:23:48
* Distribution: Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

### Description

Artifact crashes when it is started, before it can display a window on the desktop. The most relevant part of the game's output seems to be this:

```
tcmalloc: large alloc 5700063232 bytes == 0x559948ef8000 @
tcmalloc: large alloc 29903306752 bytes == (nil) @
LLVM ERROR: out of memory
```

#### Details

When the 01/10 Artifact update came out, the game still worked for me. I played a match and set a keybinding for using a custom chat message on the current tower, then closed the game. The next time I launched it I had this issue. I was able to work around this by running Steam in Flatpak, but that broke sometime after the 01/11 update (again, I believe I was able to play after the update, it broke later).

When run without Vulkan,  Artifact has the expected behavior: **it does not crash**, but obviously I cannot see anything when using OpenGL, since the game doesn't support it (game audio plays, I can still click on things, but the window is black). Other Vulkan games work (Dota 2, Dark Souls III via Proton).

Relevant logs: Artifact's gdb [output and backtrace](https://gist.github.com/her001/a0c21e09bc7ba14887ceafd00ddee9f8), Steam's [system report](https://gist.github.com/her001/81a59dea8a14bc6d09f767bd909274ba), vulkaninfo [output](https://gist.github.com/her001/0670f4b75c525d89679760878390b70d). If someone from Valve wants to see the the strace output or minidump, you can contact me privately, look at dumpid `089a43c4-8569-4e08-9b38-0b02e2190111`, or look at Steam Support ticket `HT-34B3-5BQT-7QGP` (where I was asked to open an issue here).

### Steps for reproducing this issue

For me, all I have to do is attempt to run Artifact, but that wasn't always the case. I don't know what triggered it.

### Other things I tried

Besides what I wrote in the description details, I tried other things which didn't change anything: removing various settings files for the game, verifying the game files, redownloading the game, restarting Steam, restarting (and updating and restarting) my PC, `steam --reset`, and running with and without the Steam runtime/beta client/shader precaching/prefer host libraries.

### (Un)Related issues

I suspect that the following threads may describe the same issue: [Steam Community](https://steamcommunity.com/app/583950/discussions/2/3300476731142923570), [Reddit](https://www.reddit.com/r/Artifact/comments/af29yy/bug_game_does_not_launch_on_linux_after_update/)

Other GitHub issues which look similar, but I believe to be unrelated: #5927 does not have a similar log output, #5943 and #5949 do not have working Vulkan outside of Artifact and have different error messages.

**Comment by AlexandreBonneau** [comment]
As stated in the Steam community thread, this affects Debian too.

**Comment by ponywa** [comment]
I think I have same issue, I use manjaro.

Weird part is I played normally yesterday and both my system and artifact didn't have any updates. Today however game fails to start. Dota on vulkan runs flawlessly.

**Comment by turunenm** [comment]
I had the same issue on Kde Neon (Ubuntu 18.04).

On fresh install game started fine for two times and on the third launch I got no window and std::bad_alloc in the errors.log

 Running rm ~/.steam/steam/steamapps/common/Artifact/game/dcg/shadercache/vulkan/shaders.cache before launching the game fixes the issue for me.

**Comment by MungFuSensei** [comment]
Can confirm that @turunenm 's fix works.

**Comment by Pantar2205** [comment]
confirming @turunenm 's workaround fixes the game. thank you

**Comment by danginsburg** [comment]
I have checked in what I think is a fix for this issue to ship in the next version of Artifact.  For those having problems now, you can also run with -vulkan_disable_pipeline_cache (deleting the shaders.cache file will also work).  I do recommend removing that command-line option when the next update ships since it does help with reducing shader compile time.

**Comment by imbuedHope** [comment]
confirming @turunenm and @danginsburg 's solutions both work.

**Comment by SeveredinTwain** [comment]
Also confirming @turunenm 's solution works.

**Comment by turunenm** [comment]
I just did a simple process of elimination with folder diff after fresh install compared to a launched install. Nice to see that my results also helped others as I'm really new to github 😊

**Comment by her001** [comment]
I was finally able to test this since the update. Seems to be working without any workarounds when it was previously broken. Thanks @danginsburg!
