### ISSUE TITLE
Slow view mode switch with Family View

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/steam-for-linux#6022]
#### My system information

* Steam client version: Jan 4 2019
* Distribution: Ubuntu
* Opted into Steam client beta?: Yes.
* Have you checked for system updates?: Yes.

#### My issue
After having left family view, clicking on a restricted menu item (e.g. the wishlist) will briefly show a warning that the user is still in family mode, which disappears on its own after a (long) moment.

#### Steps for reproducing this issue:

1. Launch Steam client with family mode active,
2. Click the green family mode switch button on the upper right corner.
3. Enter your pin to leave family view, the mode switch button turns red.
4. Now click "Store / Wishlist".
5. Despite already having left the family view mode on a fast computer that should process the wishlist request quickly, this warning will be visible for a long moment and then disappear. ![familyview](https://user-images.githubusercontent.com/1705654/51173729-52932400-18b6-11e9-8820-63aecf8a4140.png)
6. Then, after that long moment, the wishlist appears as requested.

#### Expected behaviour

There should be no 5., the warning shouldn't be shown at all.

This issue has been present in the Steam client since a long time.

**Comment by kisak-valve** [comment]
Most likely a web session timeout and reset simular to #5163.

**Comment by kisak-valve** [comment]
Hello @hzulla, are you still experiencing this issue on an up to date system?

**Comment by hzulla** [comment]
Can confirm, this is fixed. Thanks!
