### ISSUE TITLE
Failure to load Steamui.so client Ubuntu 18.10

### ISSUE THREAD

**Issue by NomadFTW** [ValveSoftware/steam-for-linux#6024]
#### **Lenovo Ideapad 130-15iKB (Budget Laptop)
Intel Corei3 Gen8
Intel graphics
4GB DDR4 Factory RAM +Ballistx sport 4Gb DDR4 RAM = 7.7Gb Usable RAM
Linux Software (Originally Windows 10 Pro)
64 Bit**
* Steam client version (build number or date): **Version 1.0.0.59**
* Distribution (e.g. Ubuntu): **Ubuntu 18.10**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
**I am not experienced enough to provide code, however I do have screenshots.**

My steam client fails to load due to missing libraries, I have attempted deleted and reinstalling the client many times HOWEVER, the steam.deb provided by the official steam repository at i386 and the Ubuntu multiverse repository are outdated and made for 32 bit distributions, while modern Ubuntu distributions are 64 bit (such as mine), this is primarily occurring according to the client due to missing libraries, which I have also attempted to reinstall manually, however they do not exist nor do they download when attempting a full reinstall of steam. I have contacted steam support and they have redirected me here (I've never created an account before), I was told I'd receive direct help from valve on github as they check here often. I have attempted looking for answers online and saw that many other linux users (especially debian 9 users) are experiencing the same issue for years. None of their fixes helped he thus why I am here for an official solution.

It is good to note that, a few weeks ago the steam client was functioning, and now does not.
 

![screenshot from 2019-01-13 22-08-55](https://user-images.githubusercontent.com/46723884/51212576-89525400-1921-11e9-8d46-7c8bca864480.png)
![screenshot from 2019-01-13 22-08-04](https://user-images.githubusercontent.com/46723884/51212594-953e1600-1921-11e9-941b-d885e9a8e311.png)

**Comment by kisak-valve** [comment]
Hello @NomadFTW, can you give an example of one of the dependencies that can't be found and what command you used to try to install it?

In general the steam runtime covers most of these dependencies and steam only needs a sane 32 bit render stack. Can you check if any 32 bit opengl application works like `glxinfo` from `mesa-utils:i386`?

**Comment by byte1024** [comment]
I wonder if Steam flatpack version would help here? https://www.omgubuntu.co.uk/2017/06/steam-now-available-flatpak

**Comment by NomadFTW** [comment]
Hey @kisak-valve thanks for the reply,
The reason the steamui.so won't launch is because of missing 32 bit libraries (dependencies) such as:
libXtst.so.6 
libgtk-x11-2.0.so.0
libgdl_pixbuf-2.0.so.0

I tried `~sudo -apt -install "libXtst.so.6"`, I'm pretty sure its incorrect but this is how I tried manually installing my missing libraries from the i386 repository.

These can be seen in the attached screenshots above (I'm not sure if they appear to you, I'm new to this site so excuse my ignorance).

I checked `glxinfo` on my tilix terminal and it gave me this (code was too long so here's some of it), it seems just fine: 
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_no_error, 
    GLX_ARB_create_context_profile, GLX_ARB_create_context_robustness, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_profile, GLX_ARB_create_context_robustness, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
    Version: 18.2.2
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

I attempted doing a simple test:
```
~$ glxgears
381 frames in 5.0 seconds = 75.983 FPS
300 frames in 5.0 seconds = 59.973 FPS
300 frames in 5.0 seconds = 59.973 FPS
300 frames in 5.0 seconds = 59.975 FPS
300 frames in 5.0 seconds = 59.974 FPS
300 frames in 5.0 seconds = 59.977 FPS
300 frames in 5.0 seconds = 59.968 FPS
300 frames in 5.0 seconds = 59.976 FPS
300 frames in 5.0 seconds = 59.977 FPS
300 frames in 5.0 seconds = 59.967 FPS
300 frames in 5.0 seconds = 59.971 FPS
300 frames in 5.0 seconds = 59.976 FPS
300 frames in 5.0 seconds = 59.965 FPS
300 frames in 5.0 seconds = 59.978 FPS
300 frames in 5.0 seconds = 59.979 FPS
300 frames in 5.0 seconds = 59.971 FPS
```
and then closed the gears animation which gave this:
 ```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 4968 requests (43 known processed) with 0 events remaining.
```

**Comment by NomadFTW** [comment]
> I wonder if Steam flatpack version would help here? https://www.omgubuntu.co.uk/2017/06/steam-now-available-flatpak
> 
> At least until the problem gets solved

Thank you, I'll try that as well.

**Comment by kisak-valve** [comment]
I've got a feeling that `sudo -apt -install "libXtst.so.6"` is going to give you 64 bit variants and you're also testing with 64bit glxinfo. I'd explicitly ask apt to give both 32 bit and 64 bit mesa with something like `sudo apt install libgl1-mesa-glx libgl1-mesa-glx:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386`

**Comment by kisak-valve** [comment]
Hello @NomadFTW, sorry for not answering your last question. I personally do not make recommendations on which Steam install people use.

Are you still experiencing this issue on an up to date system?

The libraries in question should always be available in some form from the Steam runtime or from the base requirement for 32 bit OpenGL. The Steam package dependencies pulls in mesa's 32 bit userspace support and X libraries are a dependency for that.

**Comment by kisak-valve** [comment]
Closing pending feedback.
