### ISSUE TITLE
Scrolling in Steam overlay scrolls multiple pages at once

### ISSUE THREAD

**Issue by junglerobba** [ValveSoftware/steam-for-linux#6025]
#### Your system information

* Steam client version (build number or date): Jan 16 2019
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
According to the changelog, today's beta update "Fixed incorrect mouse wheel scrolling offsets", which it did for the client. However, in the overlay in-game, scrolling is broken now, skipping multiple pages at once. I tested this in gnome, i3 and sway, where the behaviour was exactly the same.

#### Steps for reproducing this issue:

1. Open the Steam Overlay in a game
2. Open any scrollable view (Friends list, Browser window)
3. Use the scrollwheel in that view

**Comment by iodream** [comment]
Had the same bug and it seems to be fixed for me on Xfce Ubuntu 18.04.

**Comment by junglerobba** [comment]
Sorry, I only just had time to test this again. As others have already reported, it's fixed now. Thanks for the quick response!
