### ISSUE TITLE
Cs:go

### ISSUE THREAD

**Issue by Schlutzkrapfen** [ValveSoftware/steam-for-linux#6027]
On 
[2019-01-13 22-21-29.zip](https://github.com/ValveSoftware/steam-for-linux/files/2770112/2019-01-13.22-21-29.zip)

Ubuntu 18.04.1 LTS 

when i Try to start cs:go but have a ps3 controller connected it doesn't start.

**Comment by kisak-valve** [comment]
Hello @Schlutzkrapfen, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1757. Closing as a duplicate.

**Comment by romulosccp09** [comment]
Mensagem enviada por você em 17 de fev às 19:30 | há 1 dia e 5 horas
Boa noite srs, o meu jogo baixa instala tudo direitinho, porém quando escolho o mapa pra jogar o botão de iniciar partida não aparece!!! Como resolver esse problema?
