### ISSUE TITLE
Steam update issue

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6031]
#### Your system information

* Steam client version (build number or date): Jan 17 2019, at 23:10:42
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

With latest beta released, i tried to force enable proton for native game, but i didn't had checkbox.
I tried to opt-out, restart and apt-in to beta again, but checkbox didn't appeared.
I forced steam to check for updates, steam checked for any updates for a while and said, that there is no updates found.
Then i restarted steam and it installed new update(i think, it was downloaded at prev. step, because updating took less than ~1-2 sec)
Now i have that checkbox

**Comment by kisak-valve** [comment]
Hello @XakepSDK, have you seen this issue since the initial report?

**Comment by XakepSDK** [comment]
No, i haven't

**Comment by kisak-valve** [comment]
Let's assume it was a transitional issue back then. Closing per the last comment.
