### ISSUE TITLE
UI: Proton version note cut off for pre-purchased games

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#6032]
#### Your system information

* Steam client version (build number or date): 
![steam_version](https://user-images.githubusercontent.com/1589747/51381843-47462f80-1b26-11e9-822f-fcd16470771f.png)

* Distribution (e.g. Ubuntu): Kubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For pre-purchased games, where there is no "Install" button on the game page in the Library, the note about the Proton version gets cut off in the UI.

![steam_metro_exodus](https://user-images.githubusercontent.com/1589747/51381941-883e4400-1b26-11e9-9774-97d499a5d8fa.png)

For games with the "Install" or "Play" button the note box is taller and the text fits without being cut off.

This may be related to HiDPI displays, I have "Enlarge text and icons based on monitor size" option enabled in the Settings and the display is UHD (the UI is scaled up 2x).

#### Steps for reproducing this issue:

1. Open a pre-purchased game page in the Library.

**Comment by kisak-valve** [comment]
Hello @Lastique, this section of the Steam's Library view has been overhauled since this issue report was filed and should no longer be relevant to the current Steam client.

Closing as outdated.
