### ISSUE TITLE
PS4 Configuration Support + pulseaudio combined sink crashes

### ISSUE THREAD

**Issue by Glog78** [ValveSoftware/steam-for-linux#6034]
#### Your system information

* Steam client version (build number or date):  Jan 17 2019, at 23:10:42
* Distribution (e.g. Ubuntu):  Antergos (Arch)
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
When using pulseaudio combined sink as default in /etc/pulse/default.pa  and a ps4 controller the controller configurator crashes.

Additional Info -> coredmpctl info <crashing process> -> https://termbin.com/t1ld

example lines: default.pa 
load-module module-combine-sink sink_name=mycombined
set-default-sink mycombined

#### Steps for reproducing this issue:
1.) setup pulseaudio
2.) try to enable PS4 Configuration Support

**Comment by kisak-valve** [comment]
Hello @Glog78, this issue is already being tracked at #4891. Closing as a duplicate.
