### ISSUE TITLE
[Linux] Dota 2 no longer works on RHEL/CentOS 7.

### ISSUE THREAD

**Issue by leonmaxx** [ValveSoftware/steam-for-linux#6037]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [https://gist.github.com/leonmaxx/88e3e7c5502055dbc2cefcdbd65a4468](https://gist.github.com/leonmaxx/88e3e7c5502055dbc2cefcdbd65a4468)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
After last update of Dota 2 it doesn't launch but exits with error:
```
FATAL: /home/maxx/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so not loaded
        dlerror(): /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/maxx/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so)
```
  
[Full log](https://gist.github.com/leonmaxx/60b50686a7c1ca7c2f024b6d39fd1fe9)

Please re-compile libengine2.so using older libstdc++ or link it statically using linker (g++ / ld) option `-static-libstdc++`.

#### Steps for reproducing this issue:

1. Install Steam on CentOS/RHEL 7.6.
2. Install Dota 2.
3. Try to launch.

**Comment by kisak-valve** [comment]
What steam distro package are you using?

**Comment by leonmaxx** [comment]
Never mind.
Packagers of steam RPM package, patched `/usr/bin/steam` script to remove `libstdc++.so*` libraries in steam-runtime to workaround some old bug.  
  
I reverted that patch, copied `libstc++.so*` files from `steam-runtime.tar.xz` archive to `steam-runtime/amd64/usr/lib/x86_64-linux-gnu` directory, and started steam. Now there is proper links to `libstdc++` from steam-runtime in `pinned_libs_64` directory and Dota 2 works.
  
Thanks for Your help!

**Comment by kisak-valve** [comment]
Glad to hear you got it working. Your issue should reported to your distro packager for Steam.

Closing as this isn't a Valve issue.
