### ISSUE TITLE
Steam crashes on second run (Void linux)

### ISSUE THREAD

**Issue by DeepwaterCreations** [ValveSoftware/steam-for-linux#6040]
#### Your system information

* Steam client version (build number or date): 1547865289 (if that's what this number is?)
* Distribution (e.g. Ubuntu): Void Linux - glibc, x86_64
* Opted into Steam client beta?: Happens with and without.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When starting Steam for the first time after installation, everything works fine.
Every time afterward, it briefly shows the "updating..." window, then crashes.
I can get it to work again once by deleting ~/.local/share/Steam and telling it to rebuild. After I quit and restart, it crashes again. Uninstalling the package via Void's package manager and reinstalling doesn't change anything - the .local/share/Steam folder remains in place, and it still crashes on startup. Restarting the computer doesn't help either.
[Console output](https://gist.github.com/DeepwaterCreations/5a9233061272d636dea58b8c64d2450a)
[gdb backtrace](https://gist.github.com/DeepwaterCreations/7de49805632bc8a792c339a7950466e9)

#### Steps for reproducing this issue:

1. Run Steam with nothing at ~/.local/share/Steam
2. Tell it to rebuild files when it asks
3. Wait for it to successfully rebuild and launch, observe that everything is working
4. Quit Steam via the menu
5. Run Steam again without doing anything
6. Misery, lamentations

**Comment by kisak-valve** [comment]
Hello @DeepwaterCreations, is dbus running as a service? If not, does adding and running that as a service help?

Possibly related to https://www.reddit.com/r/voidlinux/comments/9c5c7r/steam_client_wont_start/.

**Comment by DeepwaterCreations** [comment]
Aha! That fixes it. Guess this was a problem with me being new to Void, not a problem with Steam. :) Thanks for the help!
