### ISSUE TITLE
Folder names with spaces cause issues when adding Non-Steam games

### ISSUE THREAD

**Issue by RickRNF** [ValveSoftware/steam-for-linux#6047]
#### Your system information

* Steam client version (build number or date): Built Jan 19 2019
* Distribution (e.g. Ubuntu): SolusOS
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Folder names with spaces cause issues when adding Non-Steam games.

If you add a Non-Steam game with a space in the path, Steam will cut off the "Target:" before the space and place the rest of the path within the "SET LAUNCH OPTIONS"

#### Steps for reproducing this issue:

1. Add Non-Steam game to library with path containing space(s) 
    (example: /data/game folder/game.exe)
2. "Target:" becomes "/data/game"
3. "SET LAUNCH OPTIONS" becomes "folder/game.exe"
4. Launching game from library does nothing

**Comment by kisak-valve** [comment]
Hello @RickRNF, this issue is already being tracked at #5220. Closing as a duplicate.
