### ISSUE TITLE
Steam starts again on Exit

### ISSUE THREAD

**Issue by Majkl578** [ValveSoftware/steam-for-linux#605]
After today's update, when I run Steam and then exit it (Steam -> Exit), it starts again. After second attempt, it really quits.

Debian x64 experimental, Gnome Shell 3.6.

**Comment by Fornax96** [comment]
You guys know this is still happening right? I just had steam restart itself after closing 3 times in a row, really annoying! I'm using the latest beta build: 
![image](https://cloud.githubusercontent.com/assets/1247928/15654678/7328782e-2696-11e6-9b35-642eb9e1a078.png)

**Comment by Tele42** [comment]
@Fornax96 since this issue had been closed for 3 years and did not have any activity in that time, you should go ahead and open a new issue report with your system information as requested at https://github.com/ValveSoftware/steam-for-linux#reporting-issues.
