### ISSUE TITLE
Can’t download updates (content servers unreachable)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6053]
#### Your system information

* Steam client version (build number or date):  Jan 21 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Game updates will not download, and remain set to “schedualed for xxx”

#### Steps for reproducing this issue:

1. Open Steam
2. Try to start game updates

**Comment by kisak-valve** [comment]
Hello @shoober420, please check if #6028 is relevant to your system.

**Comment by kisak-valve** [comment]
Thanks for checking. Closing as a duplicate.
