### ISSUE TITLE
crash in libdbus 

### ISSUE THREAD

**Issue by daveknippers** [ValveSoftware/steam-for-linux#6054]
#### Your system information

* Steam client version (build number or date): Jan 4 2019
* Distribution (e.g. Ubuntu): gentoo with kde
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After a random period of time, steam crashes without any notice. I can't seem to correlate the crash to any particular activity. Some days it doesn't happen at all, some days it happens multiple times. 

The dmesg output for the crash is:
```
 CIPCServer::Thr[5968]: segfault at 4 ip 00000000f474c8d4 sp 00000000ec4fec4c error 6 in libdbus-1.so.3.5.8[f4725000+47000]
```

an example log file for one of the crashes can be found [here](https://gist.github.com/daveknippers/c4ea77c0d22386b94869c01312b4acac)

the minidump for that crash can be found here: [crash_dump.zip](https://github.com/ValveSoftware/steam-for-linux/files/2796795/crash_dump.zip)

my steam hardware info is [here](https://gist.github.com/daveknippers/d63cb1c1195933bc6e265ab2d0eec21a)

I believe this bug may have been briefly noticed by kisak-valve in [this thread](https://github.com/ValveSoftware/steam-for-linux/issues/5782) but that wasn't the issue at hand.

there's also [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/5131) which may be related, but i'm not positive.

there's a second error with the same symptoms that pops up on occasion that indicates a problem with libc instead of libdbus, but I haven't managed to capture that happening yet with full logging. the vast majority of the time, the libdbus error is the cause. 

#### Steps for reproducing this issue:

1. start steam
2. continue about day normally
3. eventually it'll happen

**Comment by daveknippers** [comment]
I have an example of the libc crash. Should I attach it here or make a new thread? I'm not really sure it's related but it's very similar in behavior. 

I also have a running hypothesis of a trigger for a crash. from what I can tell, it seems that it only occurs when all steam windows are closed and steam is running from the tray only. My evidence isn't concrete yet but it's been something I'm collecting info on.

**Comment by StripedMonkey** [comment]
I had the same issue today on Ubuntu, restarted after an upgrade of a buncha stuff. The first thing I did was go to the gnome menu, Right click on the steam logo and hit Library. after a moment I get a crash. Since then I've been unable to reproduce.
```
[Snip some ptrace spam]
ptrace attach of "/home/monkey/.steam/ubuntu12_32/steam steam://open/games"[7400] was attempted by "/home/monkey/.steam/ubuntu12_32/steam steam://open/games"[7547]
ptrace attach of "/home/monkey/.steam/ubuntu12_32/steam steam://open/games"[7401] was attempted by "/home/monkey/.steam/ubuntu12_32/steam steam://open/games"[7547]
show_signal_msg: 29 callbacks suppressed
CIPCServer::Thr[7434]: segfault at 0 ip 00000000f7a26bff sp 00000000e2d8d150 error 6 in libc-2.27.so[f79b8000+1d5000]
```

**Comment by daveknippers** [comment]
i'd like to clarify: i earlier noted that i thought the crash only happened when the main steam window wasn't open. i have learned this is not the case. it crashes whenever it wants to.

**Comment by daveknippers** [comment]
all three different crashes (two variants of libdbus and one involving libc) i experienced went away after i cleared out my .steam directory. if someone encounters this issue in the future try this first.

**Comment by montjoie** [comment]
Just got this problem, and removing $HOME/.steam fixed the issue. Thanks
