### ISSUE TITLE
"All licenses are in use for this product" message after downloading games

### ISSUE THREAD

**Issue by julben** [ValveSoftware/steam-for-linux#6057]
#### Your system information

* Steam client version (build date): Jan 4 2019
* Distribution (e.g. Ubuntu): Debian 9.6 (Kernel version: 4.9.0.8-amd64)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I only expected to have the "usual" text saying that the games download was successful. Instead, I had the following: "All licenses are in use for this product".

![screenshot from 2019-01-26 20-53-10](https://user-images.githubusercontent.com/9112511/51792092-f5984780-21ac-11e9-867a-475f189b9185.png)

#### Steps for reproducing this issue:

Unknown. I just downloaded a bunch a games from my Steam library.

**Comment by kisak-valve** [comment]
Hello @julben, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
