### ISSUE TITLE
Cannot copy and paste "About Steam" text

### ISSUE THREAD

**Issue by winny-** [ValveSoftware/steam-for-linux#6065]
#### Your system information

* Steam client version (build number or date): Jan 30 2019, at 23:03:27
* Distribution (e.g. Ubuntu): Gentoo (Gentoo Base System release 2.6)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Cannot copy & paste text in the "About Steam" dialogue. Would be useful in some issues that request this text. Also useful in this issue because I had to carefully type in the build date above, as there is no copy and paste on that text.

#### Steps for reproducing this issue:

1. Help->About Steam
2. Try to copy & paste the text. It's not highlight-able nor is there a dedicated copy button.

**Comment by kisak-valve** [comment]
Hello @winny-, this is already being tracked at #5355. Closing as a duplicate.

**Comment by winny-** [comment]
Oops - did not search for "select text". Thanks for linking the other issue.
