### ISSUE TITLE
It does not use Hangul in Linux.

### ISSUE THREAD

**Issue by iyagicom** [ValveSoftware/steam-for-linux#6068]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 18.04
* Opted into Steam client beta?: [Yes/No] Y
* Have you checked for system updates?: [Yes/No]Y
![20190202113200_1](https://user-images.githubusercontent.com/15052400/52159106-29aac580-26e3-11e9-9dbc-62e29338af6c.jpg)

I can not communicate with Koreans because Hangul is not written.
I can not play games.

**Comment by kisak-valve** [comment]
Duplicate of #5372.
