### ISSUE TITLE
Game deleted after update

### ISSUE THREAD

**Issue by Riiskyy** [ValveSoftware/steam-for-linux#6069]
#### Your system information

* Steam client version (build number or date): Jan 31 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I spent an evening playing Monster Hunter World through steam play. I quit the game to go  to bed, Steam tells me there is an update and asks me to restart steam. I restart steam and then shut down the computer. The next day I wake up and start up the PC, when I open up Steam I cannot find Monster Hunter World. I found that the "Enable Steam Play for all other titles" has been disabled, I re-enabled the setting and fired up Monster Hunter World. Instead of launching the game it starts downloading. I check 

> ~/.steam/steam/steamapps/common/Monster Hunter World

 and the folder is basically empty except for graphics options, config.ini and 3 empty folders. I now have to spend a full day on my slow internet re-downloading this game and hoping that my cloud save is still there.

I tried checking 

> ~/.local/share

 but there is no steam folder here. What happened with this update and why was my game deleted? I have CS:GO installed on Linux too and this was unaffected by the update.

Gist with system info: https://gist.github.com/Riiskyy/9dcdd4e556dcd03b2aa68af3c2ddafce

**Comment by kisak-valve** [comment]
Hello @Riiskyy, looks like you encountered #5901 as a side effect of "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)." from the  [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update, which went the stable client release.

Closing in favor of the existing report.
