### ISSUE TITLE
PlayStation Controller Support crashing Steam (PS4 controller)

### ISSUE THREAD

**Issue by BERNARDO31P** [ValveSoftware/steam-for-linux#6070]
#### Your system information

* Steam client version (build number or date): Feb 2 2019, at 17:21:48 (1549129917)
* Distribution (e.g. Ubuntu): Arch Linux with Gnome
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected: Enabling the PlayStation support to play gaming with my PlayStation 4 controller.
Did: Steam crashed instantly after enabling it.

#### Steps for reproducing this issue:

1. Go to the general controller settings
2. Enable PlayStation Configuration Support

**Comment by byte1024** [comment]
It doesn't do this for me with Fedora so it seems to be either an Ubuntu only issue or a system issue.

**Comment by kisak-valve** [comment]
Hello @BERNARDO31P, this issue is already being tracked at #4891. Closing as a duplicate.
