### ISSUE TITLE
Proton not getting installed by Steam if you only override a native Linux game to use it

### ISSUE THREAD

**Issue by Laaas** [ValveSoftware/steam-for-linux#6074]
I am using NixOS, if that matters at all.

Reproduction steps:
- Install Steam
- Install some native Linux game (I installed FORCED, not actually sure if it also happens with other games)
- Enable Steam Beta (NB, I didn't actually enable Steam Play for unsupported titles)
- Make the native Linux game use Proton instead
- Try playing it

Nothing will happen since Proton isn't installed, and you can confirm it by checking the steamapps/common directory.

**Comment by kisak-valve** [comment]
Hello @Laaas, per "Fixed more instances of 0-byte downloads and missing Proton or data files for Steam Play titles" in the [2019-03-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141142819058) Steam beta client update, please retest this issue.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where the Steam Client wouldn’t automatically update or download Proton before launching games through Steam Play" in the [2019-04-17](https://store.steampowered.com/news/50095/) Steam client update.
