### ISSUE TITLE
Continuous erasing steam play games.

### ISSUE THREAD

**Issue by tuxtergames** [ValveSoftware/steam-for-linux#6078]
Hello everyone,

I made this post cause I don't find any post here related, to my question,
There's a long time that I got some games erase by Proton on my Steam, and almost time are the same games, Batman Arkhan City and Asylum, Rise sons of Rome, Pes 2018, and some times Metal Gear Solid V - The Phantom Pain, I was using the client beta for some testes with non-steam games, then I came back to stable client and the same problem again, even the client downloading some kbs or 450mb for my steam play games avery day, I'll apreciate some help ou explanation about this things.

Tks all.

**Comment by kisak-valve** [comment]
Hello @tuxtergames, game updates are managed by the Steam client, not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by tuxtergames** [comment]
> Hello @tuxtergames, game updates are managed by the Steam client, not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

Thank you.

**Comment by koylio** [comment]
I have this issue too. Some of my proton games are shared with a wine installation of steam on a local library, some with another linux version of steam on a NFS library. Both seem hit equally. Games get redownloaded unless I'm fast enough to select Verify local files. My workaround is to limit updates for non-native titles, so I can just verify them instead redownloading.

**Comment by kisak-valve** [comment]
Hello @tuxtergames, are you still experiencing this issue on an up to date system?

Hello @koylio, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing Steam Library folders between the Steam for Linux and Steam for Windows client (run in wine or otherwise) is not supported and may have unexpected behavior.

**Comment by kisak-valve** [comment]
Closing pending feedback.
