### ISSUE TITLE
Segfault in Artifact

### ISSUE THREAD

**Issue by Oliver-1xok** [ValveSoftware/steam-for-linux#6079]
#### Your system information
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-45-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.2.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 120 Hz
    VendorID:  0x8086
    DeviceID:  0x591b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64" (15.51" diag)
                                            34.4cm x 19.4cm (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC3254

Memory:
    RAM:  15889 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  223754 Mb
    Largest Free Hard Disk Block:  83494 Mb
    VR Headset: None detected

Recent Failure Reports:

* Steam client version (build number or date): Feb 2 2019 at 17:21:48 (Package version 1549129917)
* Distribution (e.g. Ubuntu): Xubuntu 18.04.1 LTS (64 bit)
* Opted into Steam client beta?: [no]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Sometimes Artifact segfaults during connection establishment at matchmaking. 

Kernel message:
GlobPool0[8131]: segfault at 40 ip 00007f0668396315 sp 00007f0674f17710 error 4 in libvulkan_intel.so[7f06682ee000+32c000]

#### Steps for reproducing this issue:

1. Start Artifact
2. Start Matchmaking
3. Repeat 

The error rarely occurs. 

CORE DUMP:
[crash_20190205220108_1.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/2834202/crash_20190205220108_1.dmp.gz)

**Comment by kisak-valve** [comment]
Hello @Oliver-1xok, are you still experiencing this issue on an up to date system? Since the segfault is in mesa/ANV, then if this issue is still around, then it may be worthwhile to also mention it to your video driver vendor.

**Comment by Oliver-1xok** [comment]
> Hello @Oliver-1xok, are you still experiencing this issue on an up to date system? Since the segfault is in mesa/ANV, then if this issue is still around, it may be worthwhile to also mention it to your video driver vendor.

Hello @kisak-valve, yes, this would need a retest with a current system. Xubuntu 18.04.1 is ancient. Unfortunately, I hardly play the game anymore and the error occurred very rarely,  as far as I remember. So I'm afraid I won't be able to reproduce it again if it still exists.

**Comment by kisak-valve** [comment]
Thanks for the feedback at least. Closing.
