### ISSUE TITLE
Closing Steam client windows causes xfce4-taskmanager to crash

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6083]
#### Your system information

* Steam client version (build number or date): 
![screenshot_2019-02-08_18-05-31](https://user-images.githubusercontent.com/6024315/52512763-47d56180-2bcc-11e9-8832-3caedf9f009e.png)
* Distribution (e.g. Ubuntu): Xubuntu 18.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
https://gist.github.com/nightsky30/45ea820b910459d8d6a6e25c7903275a

#### Please describe your issue in as much detail as possible:

Not sure if this goes here but Steam definitely plays a role...Already had Xubuntu report crashes.

I repeatedly crashed xfce4-taskmanager by starting the XFCE Task Manager, starting the Steam client, and closing the Steam client windows.  It does not matter what Steam client window is closed whether it be the "Create/Login existing", "Login credentials", or main main Steam client window.  dmesg logs always showed the following when the task manager crashed.  Repeated crashes did not change the code produced:

[  538.849213] xfce4-taskmanag[14268]: segfault at 0 ip 0000558eda955a23 sp 00007ffd6c79c000 error 4 in xfce4-taskmanager[558eda948000+f000]
[  538.849216] Code: fb 48 83 ec 08 e8 ed 2e ff ff 85 c0 74 09 48 83 c4 08 5b 5d c3 66 90 e8 db 32 ff ff 48 89 df 48 89 c5 e8 b0 36 ff ff 48 89 ee <48> 8b 38 e8 85 29 ff ff 48 83 c4 08 5b 48 89 c7 5d e9 97 3c ff ff 

#### Steps for reproducing this issue:

1. Open XFCE Task Manager (xfce4-taskmanager).
2. Start the Steam client.
3. Close the Steam client by using the top right corner X on any of the windows.
4. Crash Task Manager.
5. Repeat.

**Comment by kisak-valve** [comment]
Hello @nightsky30, since the crash is in xfce, it should also be brought to the attention of the xfce devs.

**Comment by nightsky30** [comment]
https://bugzilla.xfce.org/show_bug.cgi?id=15130

**Comment by byte1024** [comment]
Xfce task manager is what needs to be fixed in my opinion. This application does not rely on Steam (runs without Steam) so it should be hardened to not crash from an application that it adds to its lists, charts, or whatever.

**Comment by nightsky30** [comment]
I've cloned, built, and installed xfce4-taskmanager v1.2.2 from git head master, and I cannot reproduce the crash with that version.

**Comment by nightsky30** [comment]
Closing per bugzilla resolution.

**Comment by nightsky30** [comment]
Not to reopen the issue, but I wanted to mention that I recently had to do a clean reinstall of Xubuntu 18.10 with Steam due to hardware failure, and the same behavior occurs again.  There has to be some issue with the way that Ubuntu/Xubuntu built xfce4-taskmanager for 18.10 or the dependencies used that jive better with 1.2.2 built from master.
