### ISSUE TITLE
Steam cannot detect my AMD Video Drive (AMD Raden 520)

### ISSUE THREAD

**Issue by kendier** [ValveSoftware/steam-for-linux#6086]
* Steam client version (build number or date): 1549129917 (Feb 2 2019)
* Distribution (e.g. Ubuntu): Linux Mint 19.1
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

When I go to terminal:
sudo lshw -c video

then
` 
*-display                 
       descrição: VGA compatible controller
       produto: UHD Graphics 620
       fabricante: Intel Corporation
       ID físico: 2
       informações do barramento: pci@0000:00:02.0
       versão: 07
       largura: 64 bits
       clock: 33MHz
       capacidades: pciexpress msi pm vga_controller bus_master cap_list rom
       configuração: driver=i915 latency=0
       recursos: irq:128 memória:d1000000-d1ffffff memória:b0000000-bfffffff porta de E/S:f000(tamanho=64) memória:c0000-dffff
  *-display
       descrição: Display controller
       produto: Jet PRO [Radeon R5 M230 / R7 M260DX / Radeon 520 Mobile]
       fabricante: Advanced Micro Devices, Inc. [AMD/ATI]
       ID físico: 0
       informações do barramento: pci@0000:01:00.0
       versão: c3
       largura: 64 bits
       clock: 33MHz
       capacidades: pm pciexpress msi bus_master cap_list rom
       configuração: driver=radeon latency=0
       recursos: irq:129 memória:c0000000-cfffffff memória:d0000000-d003ffff porta de E/S:e000(tamanho=256) memória:d0040000-d005ffff
`
But when I go to "Steam - System Information", it didn't recognize my AMD Drive, only the Intel Drive...
https://i.imgur.com/hncrc4h.png

Sorry for my bad English... =/

**Comment by kisak-valve** [comment]
Hello @kendier, Steam is accurately telling you that it is running on the intel chipset. This is not a bug.

You should be able to run steam with `DRI_PRIME=1 steam` from a terminal to run steam on the AMD gpu, or have individual games run on it by adding `DRI_PRIME=1 %command%` to the game's launch options.

Outside of steam, you can test this env variable with `DRI_PRIME=1 glxinfo -B`.
