### ISSUE TITLE
Very slow download speed and game updates

### ISSUE THREAD

**Issue by Ne0shka** [ValveSoftware/steam-for-linux#6087]
* Steam client version (build number or date): Feb 8 2019, 22:05:22
* Distribution (e.g. Ubuntu): Linux ME10MAN 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

content_log.txt: https://gist.github.com/Ne0shka/1749a1cc667d84ff021783a68ac9d87b

Hello, I have a problem with the Steam client on Linux. Very slow download speed and game updates. Reinstalling Steam and the OS didn't help. The Internet speed is good (the audit was conducted using speedtest-cli: https://github.com/sivel/speedtest-cli).
On Linux there is Apache server, but it is disabled. To resolve the problem I tried to install the Google DNS address (8.8.8.8) and install a caching DNS server is dnsmasq. The speed is still small.

**Comment by MaxiHD** [comment]
this is probably a problem with the steam download servers of linux.

**Comment by Ne0shka** [comment]
And when will this issue be resolved? It just takes about 2 weeks.

**Comment by Ne0shka** [comment]
The problem is solved by the rejection of the Steam Beta Update.
@ValveSoftware Please fix it.

**Comment by A7mmud** [comment]
this problem prevents me from switching to linux. 100 kb/s on linux while 5 Mb/s on windows.

**Comment by Ne0shka** [comment]
I know, but i using Linux.

сб, 6 апр. 2019 г., 8:51 A7mmud <notifications@github.com>:

**Comment by vdechand** [comment]
Ubuntu 16.04.6 LTS with 4.4.0-148 kernel.
Disabling ipv6 helps.

**Comment by Ne0shka** [comment]
Another interesting point: in sysctl.conf the IPv6 disable option is applied, but the speed is still low. However, after manual shutdown via sysctl, speed is restored.
Please check the Valve developers for this problem

**Comment by kisak-valve** [comment]
Hello @Ne0shka, since you closed this issue, #6126 was opened to track this issue. Please continue the discussion on that issue report.

Closing in favor of #6126.
