### ISSUE TITLE
Steam won't launch using discrete gpu

### ISSUE THREAD

**Issue by GGwpAiushtha** [ValveSoftware/steam-for-linux#6090]
#### Your system information

* Steam client version (build number or date): 1549672548
* Distribution (e.g. Ubuntu): Linux Mint 19.1 (tried also Ubuntu 18.10 and Lubuntu 18.10)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I have laptop with 2 gpus: integrated (Intel HD Graphics 3000) and discrete (NVIDIA GeForce 520M). I install Steam from official package. And when i use integrated gpu, Steam launched finem but when i switched to discrete, Steam won't appear (in System Monitor only 1 process). Help me pls. 
I can switch GPU only via reboot PC.

I'm already tried reinstall system/steam, but this don't help.

Sorry for bad English.

**Comment by byte1024** [comment]
I do believe this is Nvidia Optimus in which case you would have to use Bumblebee and whatever that other thing was.

Can Steam ever do this automatically? I'm not sure it ever will on Linux. So I personally see this as a won't fix. The easiest fix is to just stay away from Nvidia Optimus retail computers.

**Comment by mercuriete** [comment]
Related to #634

**Comment by kisak-valve** [comment]
Hello @GGwpAiushtha, are you still experiencing this issue on an up to date system?

**Comment by GGwpAiushtha** [comment]
Hi, I am currently using Arch Linux and have no problems with Steam.
I can't check the work under Linux Mint and other distros :(

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as outdated.
