### ISSUE TITLE
Chat can't be controlled with the Steam Controller in Big Picture Mode

### ISSUE THREAD

**Issue by different55** [ValveSoftware/steam-for-linux#6092]
#### Your system information

* Steam client version (build number or date): Feb 8 2019 at 22:05:17
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Pressing Right Trigger to click does not click inside the chat, it clicks whatever element happens to be highlighted back on the "home screen." So if I highlight the settings icon, hit Right Bumper to go into Chat, and then click on a friend, instead of clicking on a friend it will click that settings icon back on the previous screen, kicking me out of the chat and shooting me into settings. This works for anything you can select on the main menu, I haven't tested other screens. 

#### Steps for reproducing this issue:

1. Launch Big Picture Mode with your Steam Controller using the default configuration for BPM.
2. Navigate so that any item on screen is highlighted.
3. Press Right Bumper to switch to the "Chat" view.
4. Click anywhere in the "Chat" view.
5. Get yanked away somewhere else depending on the item highlighted in Step 2.

**Comment by kisak-valve** [comment]
Hello @different55, are you still experiencing this issue on an up to date system?

**Comment by different55** [comment]
Nope, appears that this was fixed at some point. Thanks!
