### ISSUE TITLE
Proton updated to 3.16-7, However DXVK_HUD displays version 0.94

### ISSUE THREAD

**Issue by 0x221E** [ValveSoftware/steam-for-linux#6093]
The steam client shows Proton version 3.16-7 Beta. However DXVK_HUD version shows version to be 0.94.

`/dist/lib/wine/dxvk/version` file of **`Proton 3.16 Beta`** directory shows -

`3b3ccc8194733e20ce7e2a54edcf54fe4a2b9785 dxvk (v0.94-18-g3b3ccc8)`

Is there any manual intervention required to update the version ?

**Comment by LiamDawe** [comment]
I can confirm I also saw this issue, as did others on GOL and in our Discord.

Proton would not update, unless we installed Proton 3.16 Beta from the tools menu.

**Comment by 2A4U** [comment]
> manually download it through steal tools. I did and it worked.
Where do I get "steal tools"?

> Proton would not update, unless we installed Proton 3.16 Beta from the tools menu.
"tools menu" from "steal tools"? Where is the "tools menu"?

**Comment by kisak-valve** [comment]
Steam -> Library dropdown -> Tools -> Double click on Proton 3.16 Beta

**Comment by kisak-valve** [comment]
Hello, per "Fixed more instances of 0-byte downloads and missing Proton or data files for Steam Play titles" in the [2019-03-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141142819058) Steam beta client update, please opt into Steam's beta client and retest this issue.

**Comment by XakepSDK** [comment]
Got one. Less and less with every fix!
https://puu.sh/CXbsJ/6b8af30afc.png

**Comment by 0x221E** [comment]
Sorry for delayed response.
It seems like client is unable to auto-download missing Proton files. PFB gist after removing proton python script;
https://gist.github.com/0x221E/34c5d5247928e43103b7ecb4da626760

On manual integrity verification, it downloaded missing files.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where the Steam Client wouldn’t automatically update or download Proton before launching games through Steam Play" in the [2019-04-17](https://store.steampowered.com/news/50095/) Steam client update.
