### ISSUE TITLE
Steam not working on Linux Mint 19.x

### ISSUE THREAD

**Issue by jusdepatate** [ValveSoftware/steam-for-linux#6098]
#### Your system information

* Steam client version (build number or date): `updater built Nov 23 2016 01:05:42` and last
* Distribution (e.g. Ubuntu): Linux Mint 19.1 Tessa (Ubuntu 18.04)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I installed Steam using the Linux Mint's repos and using Valve's `.deb` and I get errors using both : 
- Linux Mint's deb (in `apt`) :
```
jusdepatate@jusdepatate:~$ steam
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2019-02-18 10:57:40] Startup - updater built
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
and then nothing
- Valve's deb :
```
jusdepatate@jusdepatate:~$ steam
Running Steam on linuxmint 19.1 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/jusdepatate/.local/share/Steam/steam.sh: ligne 828: /home/jusdepatate/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: Aucun fichier ou dossier de ce type
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
and then nothing
(`Aucun fichier ou dossier de ce type` = `No such file or directory`)

Nvidia Drivers are installed
I have an Nvidia GTX 1050 and three screens

#### Steps for reproducing this issue:

1. Install Steam on Linux Mint using official deb or deb in `apt`
3. Send love on GitHub

**Comment by jusdepatate** [comment]
`glxinfo` and `glxgears` output : 

```
jusdepatate@jusdepatate:~$ glxinfo
name of display: :0
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  54
  Current serial number in output stream:  53
jusdepatate@jusdepatate:~$ glxgears
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  41
```

**Comment by kisak-valve** [comment]
Hello @jusdepatate, your system is trying to tell you that your 32 bit opengl driver is broken. Your system is trying to use mesa's libGL.so.1 which is incompatible with nvidia's proprietary driver.

Maybe check if you have `libnvidia-gl-415:i386`?

**Comment by jusdepatate** [comment]
`libnvidia-gl-415:i386` is not installed

**Comment by jusdepatate** [comment]
Now it is working, what i have done : 
- I launched Linux Mint's Drivers manager
- I installed Nouveau drivers
- I installed back 415 proprietary drivers
- I rebooted my computer
- Now steam is working

Thanks to lenashou and Leeo for this help

**Comment by tn5421** [comment]
Thanks, jusdepatate, that helped me as well.

**Comment by vorokai** [comment]
@jusdepatate, Many thanks. Worked for me!

**Comment by gnumoksha** [comment]
@jusdepatate thank you so much! You are the best! I would take days to solve this!

BTW, have you had a problem with apt autoremove? Some packages are required by steam but apt doesn't know it.

**Comment by rodrigograca31** [comment]
Didn't even need to restart. Thanks!
