### ISSUE TITLE
Slow video streaming in Big Picture mode

### ISSUE THREAD

**Issue by oblitum** [ValveSoftware/steam-for-linux#6102]
#### Your system information

* Steam client version (build number or date):  18/02/2019
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Hi, I love to use steam in Big Picture mode, but there are two issues, and one makes it almost unusable for me,  the not so relevant issue is that Big Picture takes too much processing when compared to standard interface, the relevant one is that video streaming in the Store takes ages to load, it's annoying, it simply plays fine in normal view, just changing to Big Picture and it looks like it waits the entire video to load for playing it. I'm on a 4MB connection, and can playback any online videos fine, as well as videos in Steam classic interface, sadly Big Picture is unusable for that.

**Comment by oblitum** [comment]
Looks like it's a very old issue by the way:

- https://steamcommunity.com/groups/bigpicture/discussions/0/864977564132682960/

**Comment by kisak-valve** [comment]
Hello @oblitum, are you still experiencing this issue on an up to date system?

**Comment by oblitum** [comment]
@kisak-valve can't say for sure as I have upgraded my bandwidth and that may hide the problem, which I don't experience anymore. Big Picture is still much more CPU heavier though.
