### ISSUE TITLE
World of Tanks Blitz MMO lists Linux, with no Linux version

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6103]
Since I've been unable to reach the developer, maybe you can fix this directly?

World of Tanks Blitz MMO has been set as available for Linux, SteamOS icon and all despite not having a Linux version: https://store.steampowered.com/app/444200/World_of_Tanks_Blitz_MMO/

**Comment by kisak-valve** [comment]
Hello @LiamDawe, it looks like this issue was resolved some time ago. Closing as outdated.
