### ISSUE TITLE
Steam crashes executing Half-Life 2 and Episode 1 using Steam Controller with Fedora 29

### ISSUE THREAD

**Issue by cold-distance** [ValveSoftware/steam-for-linux#6104]
#### Your system information

* Steam client version (build number or date): Feb 18 2019, at 22:09:18
* Distribution (e.g. Ubuntu): Fedora 29
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Hi, I have some problems with Half-Life 2 in Fedora 29, and it seems the only game (I didn't try Episode 2 yet) that gives me these issues among the games I ran in my current Linux installation (Fedora 29).

Before updating to Mesa 18.3 I was using Mesa 18.2 with my RX 580. The mouse pointer worked slow and with serious lag in the start screen and the options using the Steam Controller, but I could play without any problem. Since I updated to Mesa 18.3, the Steam client started to crash some minutes after starting the Half-Life 2 process. The situation becomes very annoying with Steam Link, and because I always play with Steam Controller, I use Big Picture as interface with the client. The lag with the mouse pointer remains in Mesa 18.3.

I use RPMFusion repo for Steam and full multimedia support. Obviously, I need all the codecs the get full support for the common use of a computer. https://rpmfusion.org/Configuration

This is the configuration of my computer executing the "inxi -SGCMx" command:

```
System:
  Host: fedora-ryzen Kernel: 4.20.10-200.fc29.x86_64 x86_64 bits: 64 
  compiler: gcc v: 8.2.1 Desktop: Gnome 3.30.2 
  Distro: Fedora release 29 (Twenty Nine) 

Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X370-F GAMING v: Rev X.0x 
  serial: <root required> UEFI: American Megatrends v: 4207 date: 12/09/2018 

CPU:
  Topology: 8-Core model: AMD Ryzen 7 1700 bits: 64 type: MT MCP arch: Zen 
  rev: 1 L2 cache: 4096 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 95820 
  Speed: 1548 MHz min/max: 1550/3000 MHz Core speeds (MHz): 1: 1547 2: 1543 
  3: 1547 4: 1546 5: 1548 6: 1550 7: 1546 8: 1539 9: 1547 10: 1718 11: 1547 
  12: 1709 13: 1552 14: 1544 15: 1547 16: 1534 

Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
  vendor: Sapphire Limited Nitro+ driver: amdgpu v: kernel bus ID: 0b:00.0 
  Display: x11 server: Fedora Project X.org 1.20.3 driver: amdgpu 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.27.0 
  4.20.10-200.fc29.x86_64 LLVM 7.0.1) 
  v: 4.5 Mesa 18.3.4 direct render: Yes 
```

I will try to run Steam client from the console later to see if I get some error in the command line.

#### Steps for reproducing this issue:

1.  Starting the Half-Life 2 process from Big Picture and using the Steam Controller.
2.  Mouse pointer works with serious lag with the Steam Controller.
3.  After playing the game for some minutes (between 10 and 30), the Steam client crashes and controller becomes unresponsive.

**Comment by kisak-valve** [comment]
Hello @cold-distance, if you find any CrashIDs or minidumps (commonly found in `/tmp/dumps/') related to this issue, please put them in an archive and drag and drop the archive into the comment box.

**Comment by cold-distance** [comment]
Here are the files.

[Terminal output.txt](https://github.com/ValveSoftware/steam-for-linux/files/2897159/Terminal.output.txt)

[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/2897161/dumps.zip)

**Comment by kisak-valve** [comment]
Possible video driver issue from the log:
```
steam: ../src/gallium/drivers/radeonsi/si_descriptors.c:1150: si_upload_vertex_buffer_descriptors: Assertion `num_records >= 0 && num_records <= UINT_MAX' failed.
crash_20190223195129_1.dmp[5619]: Uploading dump (out-of-process)
```

For reference, the corresponding minidump is a SIGABRT in linux-gate.so. The other minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by kisak-valve** [comment]
Upstream bug report: https://bugs.freedesktop.org/show_bug.cgi?id=109693

**Comment by cold-distance** [comment]
Thank you for your help. It seems it's a regression found in Mesa 18.3. At least you give me very specific instructions it seems I can't do anything more.

I will be attentive to this thread.

**Comment by cold-distance** [comment]
I fixed the lag of mouse cursor installing these packages for 32-bit support. That was my fault (sorry for the words in Spanish):

```
Paquetes modificados:
    Instalar clang-libs-7.0.1-2.fc29.i686         @updates
    Instalar compiler-rt-7.0.1-1.fc29.i686        @updates
    Instalar libclc-0.2.0-13.git1ecb16d.fc29.i686 @updates
    Instalar mesa-libEGL-18.3.4-1.fc29.i686       @updates
    Instalar mesa-libOpenCL-18.3.4-1.fc29.i686    @updates
    Instalar mesa-libgbm-18.3.4-1.fc29.i686       @updates
    Instalar mesa-libxatracker-18.3.4-1.fc29.i686 @updates
    Instalar libglvnd-egl-1:1.1.0-2.fc29.i686     @fedora
    Instalar libwayland-server-1.16.0-1.fc29.i686 @fedora
    Instalar mesa-libGLU-9.0.0-16.fc29.i686       @fedora
    Instalar ocl-icd-2.2.12-2.fc29.i686           @fedora
```

**Comment by cold-distance** [comment]
The crash of Steam client isn't fixed.

[Terminal output 2.txt](https://github.com/ValveSoftware/steam-for-linux/files/2897951/Terminal.output.2.txt)

[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/2897952/dumps.zip)

**Comment by kisak-valve** [comment]
Hello @cold-distance, are you still experiencing this issue on an up to date system?

**Comment by cold-distance** [comment]
I don't know. Give me one day to test it.

**Comment by cold-distance** [comment]
Sorry to be late.

I just tested with Fedora 34 Workstation and the bug is fixed at least for me. This is my current configuration.

`System:
  Host: fedora-ryzen Kernel: 5.12.15-300.fc34.x86_64 x86_64 bits: 64 
  compiler: gcc v: 2.35.1-41.fc34 Desktop: GNOME 40.3 
  Distro: Fedora release 34 (Thirty Four) 
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X370-F GAMING v: Rev X.0x 
  serial: <superuser required> UEFI: American Megatrends v: 4207 
  date: 12/09/2018 
CPU:
  Info: 8-Core model: AMD Ryzen 7 1700 bits: 64 type: MT MCP arch: Zen 
  rev: 1 cache: L2: 4 MiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 95823 
  Speed: 1497 MHz min/max: 1550/3000 MHz boost: enabled Core speeds (MHz): 
  1: 1497 2: 1496 3: 1547 4: 1546 5: 1547 6: 1536 7: 1547 8: 1547 9: 2711 
  10: 2692 11: 1518 12: 1541 13: 1547 14: 1544 15: 1546 16: 1545 
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
  vendor: Sapphire Limited Nitro+ driver: amdgpu v: kernel bus-ID: 0b:00.0 
  Display: wayland server: X.Org 1.21.1.2 compositor: gnome-shell driver: 
  loaded: amdgpu note: n/a (using device driver) - try sudo/root 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.40.0 
  5.12.15-300.fc34.x86_64 LLVM 12.0.0) 
  v: 4.6 Mesa 21.1.5 direct render: Yes `

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as fixed some time ago.
