### ISSUE TITLE
Steam cant download packages and issues an error on ubuntu 14.04

### ISSUE THREAD

**Issue by thabraveRoman** [ValveSoftware/steam-for-linux#6105]
#### Your system information

* Steam client version (build number or date): steam-launcher 1.0.0.59
* Distribution (e.g. Ubuntu): Ubuntu 14.04.05 lts
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No ]Yes

#### Please describe your issue in as much detail as possible:
Steam needs to install these additional packages:
libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
[sudo] password for roman:
......................................
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
libc6:i386 : Depends: libgcc1:i386 but it is not going to be installed
libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
Depends: libdrm-nouveau2:i386 (>= 2.4.38) but it is not going to be installed
Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
Depends: libelf1:i386 (>= 0.142) but it is not going to be installed
Depends: libexpat1:i386 (>= 2.0.1) but it is not going to be installed
Depends: libgcc1:i386 (>= 1:4.1.1) but it is not going to be installed
Depends: libllvm3.4:i386 but it is not going to be installed
Depends: libstdc++6:i386 (>= 4.6) but it is not going to be installed
Recommends: libtxc-dxtn-s2tc0:i386 but it is not going to be installed or
libtxc-dxtn0:i386
libgl1-mesa-glx:i386 : Depends: libdrm2:i386 (>= 2.3.1) but it is not going to be installed
Depends: libxext6:i386 but it is not going to be installed
Depends: libxfixes3:i386 but it is not going to be installed
Depends: libxxf86vm1:i386 but it is not going to be installed
Depends: libudev1:i386 but it is not going to be installed or
libudev0:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
Press return to continue:
(gnome-terminal:7463): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1-mesa-glx:i386 needs to be installed
Package libc6:i386 needs to be installed
Running Steam on ubuntu 14.04 64-bit
STEAM_RUNTIME is enabled automatically
/home/roman/.local/share/Steam/steam.sh: line 388: realpath: command not found
/home/roman/.local/share/Steam/steam.sh: line 828: /home/roman/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
/home/roman/.local/share/Steam/steam.sh: line 888: /home/roman/.local/share/Steam/ubuntu12_32/steam: No such file or directory
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @thabraveRoman, do you have multiarch enabled? Something along the lines of:
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 realpath
```

You're also going to encounter #5311 after that.

**Comment by thabraveRoman** [comment]
I did these commands and:

roman@roman-OMEN:~$ sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 realpath
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 account-plugin-ubuntuone : Depends: ubuntu-system-settings-online-accounts but it is not going to be installed
 accountsservice : Depends: libgcr-base-3-1 (>= 3.8.0) but it is not going to be installed
                   Depends: libpam0g (>= 0.99.7.1) but it is not going to be installed
                   Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
 adduser : Depends: passwd (>= 1:4.0.12)
 apparmor : Depends: initramfs-tools but it is not going to be installed
 base-files : PreDepends: awk
 bluez : Depends: libusb-0.1-4 (>= 2:0.1.12) but it is not going to be installed
         Depends: module-init-tools but it is not going to be installed
 dbus : Depends: libsystemd-login0 (>= 31) but it is not going to be installed
        Recommends: libpam-systemd but it is not going to be installed
 dconf-gsettings-backend : Depends: dconf-service (>= 0.20.0-1)
                           Depends: dconf-service (< 0.20.0-1.1~)
                           Depends: libdconf1 (= 0.20.0-1) but it is not going to be installed
 gir1.2-glib-2.0 : Depends: libgirepository-1.0-1 (>= 1.40.0-1ubuntu0.2) but it is not going to be installed
 gstreamer1.0-plugins-base : Depends: libcdparanoia0 (>= 3.10.2+debian) but it is not going to be installed
                             Depends: libogg0 (>= 1.0rc3) but it is not going to be installed
                             Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
                             Depends: libtheora0 (>= 1.0) but it is not going to be installed
                             Depends: libvisual-0.4-0 (>= 0.4.0-4) but it is not going to be installed
                             Depends: libvorbis0a (>= 1.1.2) but it is not going to be installed
                             Depends: libvorbisenc2 (>= 1.1.2) but it is not going to be installed
 gstreamer1.0-plugins-good : Depends: libaa1 (>= 1.4p5) but it is not going to be installed
                             Depends: libavc1394-0 (>= 0.5.3) but it is not going to be installed
                             Depends: libcaca0 (>= 0.99.beta17-1) but it is not going to be installed
                             Depends: libcairo-gobject2 (>= 1.10.0) but it is not going to be installed
                             Depends: libcairo2 (>= 1.10.0) but it is not going to be installed
                             Depends: libdv4 but it is not going to be installed
                             Depends: libflac8 (>= 1.3.0) but it is not going to be installed
                             Depends: libgstreamer-plugins-good1.0-0 (= 1.2.4-1~ubuntu1) but it is not going to be installed
                             Depends: libiec61883-0 (>= 1.2.0) but it is not going to be installed
                             Depends: libjack-jackd2-0 (>= 1.9.5~dfsg-14) but it is not going to be installed or
                                      libjack-0.116
                             Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
                             Depends: libraw1394-11 but it is not going to be installed
                             Depends: libshout3 but it is not going to be installed
                             Depends: libsoup2.4-1 (>= 2.38) but it is not going to be installed
                             Depends: libspeex1 (>= 1.2~beta3-1) but it is not going to be installed
                             Depends: libtag1c2a (>= 1.5) but it is not going to be installed
                             Depends: libxv1 but it is not going to be installed
                             Recommends: gstreamer1.0-x but it is not going to be installed
 libaccounts-qt5-1 : Depends: libaccounts-glib0 (>= 1.14) but it is not going to be installed
                     Depends: libqt5xml5 (>= 5.0.2) but it is not going to be installed
 libaccountsservice0 : Depends: libgcr-base-3-1 (>= 3.8.0) but it is not going to be installed
                       Depends: libsystemd-login0 (>= 186) but it is not going to be installed
 libc6 : Breaks: libc6:i386 (!= 2.19-0ubuntu6.9) but 2.19-0ubuntu6 is to be installed
 libc6:i386 : Breaks: libc6 (!= 2.19-0ubuntu6) but 2.19-0ubuntu6.9 is to be installed
 libcap2-bin : Depends: libcap2 (>= 2.10) but it is not going to be installed
               Recommends: libpam-cap but it is not going to be installed
 libfolks25 : Depends: folks-common (= 0.9.5-1ubuntu5) but it is not going to be installed
              Recommends: libfolks-eds25 but it is not going to be installed
 libgcc1 : Depends: gcc-4.9-base (= 4.9.3-0ubuntu4) but it is not going to be installed
           Breaks: libgcc1:i386 (!= 1:4.9.3-0ubuntu4) but 1:4.9-20140406-0ubuntu1 is to be installed
 libgcc1:i386 : Breaks: libgcc1 (!= 1:4.9-20140406-0ubuntu1) but 1:4.9.3-0ubuntu4 is to be installed
 libgl1-mesa-dri : Depends: libllvm3.4 but it is not going to be installed
 libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libelf1:i386 (>= 0.142) but it is not going to be installed
                        Depends: libexpat1:i386 (>= 2.0.1) but it is not going to be installed
                        Depends: libllvm3.4:i386 but it is not going to be installed
                        Depends: libstdc++6:i386 (>= 4.6) but it is not going to be installed
                        Recommends: libtxc-dxtn-s2tc0:i386 but it is not going to be installed or
                                    libtxc-dxtn0:i386
 libgl1-mesa-glx:i386 : Depends: libdrm2:i386 (>= 2.3.1) but it is not going to be installed
                        Depends: libglapi-mesa:i386 (= 10.1.0-4ubuntu5) but it is not going to be installed
                        Depends: libx11-6:i386 (>= 2:1.4.99.1) but it is not going to be installed
                        Depends: libx11-xcb1:i386 but it is not going to be installed
                        Depends: libxcb-dri2-0:i386 (>= 1.8) but it is not going to be installed
                        Depends: libxcb-dri3-0:i386 but it is not going to be installed
                        Depends: libxcb-glx0:i386 (>= 1.8) but it is not going to be installed
                        Depends: libxcb-present0:i386 but it is not going to be installed
                        Depends: libxcb-sync1:i386 but it is not going to be installed
                        Depends: libxcb1:i386 (>= 1.9.2) but it is not going to be installed
                        Depends: libxdamage1:i386 (>= 1:1.1) but it is not going to be installed
                        Depends: libxext6:i386 but it is not going to be installed
                        Depends: libxfixes3:i386 but it is not going to be installed
                        Depends: libxshmfence1:i386 but it is not going to be installed
                        Depends: libxxf86vm1:i386 but it is not going to be installed
                        Depends: libudev1:i386 but it is not going to be installed or
                                 libudev0:i386 but it is not installable
 libgstreamer-plugins-base0.10-0 : Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
 libgstreamer-plugins-base1.0-0 : Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
 libnih-dbus1 : Depends: libnih1 (= 1.0.3-4ubuntu25) but it is not going to be installed
 libnm-glib4 : Depends: libgudev-1.0-0 (>= 146) but it is not going to be installed
 libnm-util2 : Depends: libnspr4 (>= 2:4.9-2~) but it is not going to be installed or
                        libnspr4-0d (>= 1.8.0.10) but it is not going to be installed
               Depends: libnss3 (>= 2:3.13.4-2~) but it is not going to be installed or
                        libnss3-1d (>= 3.12.0~1.9b1) but it is not going to be installed
 liboauth0 : Depends: libcurl3-gnutls (>= 7.16.2) but it is not going to be installed
             Depends: libnss3 (>= 2:3.13.4-2~) but it is not going to be installed or
                      libnss3-1d (>= 3.12.0~1.9b1) but it is not going to be installed
 libpackagekit-glib2-16 : Depends: libarchive13 but it is not going to be installed
 libpam-runtime : Depends: libpam-modules (>= 1.0.1-6) but it is not going to be installed
 libpulse0 : Depends: libjson-c2 (>= 0.10) but it is not going to be installed
             Depends: libsndfile1 (>= 1.0.20) but it is not going to be installed
 libqt5gui5 : Depends: fontconfig
              Depends: libfontconfig1 (>= 2.9.0) but it is not going to be installed
              Depends: libfreetype6 (>= 2.3.5) but it is not going to be installed
              Depends: libgtk2.0-0 (>= 2.24.0) but it is not going to be installed
              Depends: libharfbuzz0b (>= 0.9.11) but it is not going to be installed
              Depends: libpango-1.0-0 (>= 1.14.0) but it is not going to be installed
              Depends: libxcb-image0 (>= 0.3.9) but it is not going to be installed
              Depends: libxcb-render-util0 (>= 0.3.8) but it is not going to be installed
              Depends: libxcb-render0 but it is not going to be installed
              Depends: libxcb-shape0 but it is not going to be installed
              Depends: libxcb-shm0 but it is not going to be installed
              Depends: libxcb-xkb1 but it is not going to be installed
              Depends: libxi6 (>= 2:1.2.99.4) but it is not going to be installed
              Depends: libxkbcommon-x11-0 (>= 0.4.0) but it is not going to be installed
 libsqlite3-0 : Breaks: libsqlite3-0:i386 (!= 3.8.2-1ubuntu2.1) but 3.8.2-1ubuntu2 is to be installed
 libsqlite3-0:i386 : Breaks: libsqlite3-0 (!= 3.8.2-1ubuntu2) but 3.8.2-1ubuntu2.1 is to be installed
 libtimezonemap1 : Depends: libcairo2 (>= 1.10) but it is not going to be installed
                   Depends: libgtk-3-0 (>= 3.1.4) but it is not going to be installed
 libudev1 : Depends: libcgmanager0 but it is not going to be installed
            Depends: libnih1 (>= 1.0.0) but it is not going to be installed
 libuuid1 : Depends: passwd
            Recommends: uuid-runtime
 libxcb1 : Depends: libxau6 but it is not going to be installed
           Depends: libxdmcp6 but it is not going to be installed
 openssh-sftp-server : Depends: openssh-client
                       Recommends: openssh-server or
                                   ssh-server
 python : Depends: python2.7 (>= 2.7.5-1~) but it is not going to be installed
          Depends: libpython-stdlib (= 2.7.5-5ubuntu3) but it is not going to be installed
 python3 : Depends: libpython3-stdlib (= 3.4.0-0ubuntu2) but it is not going to be installed
 python3-apt : Depends: libapt-inst1.5 (>= 0.8.11) but it is not going to be installed
 python3-aptdaemon.pkcompat : Depends: python3-aptdaemon (= 1.1.1-1ubuntu5.2) but it is not going to be installed
                              Depends: gir1.2-packagekitglib-1.0 (>= 0.8.9) but it is not going to be installed
 python3-gi : Depends: libgirepository-1.0-1 (>= 1.33.10) but it is not going to be installed
 python3-minimal : Depends: python3.4-minimal (>= 3.4.0-0~) but it is not going to be installed
 python3.4 : Depends: python3.4-minimal (= 3.4.3-1ubuntu1~14.04.3) but it is not going to be installed
             Depends: libpython3.4-stdlib (= 3.4.3-1ubuntu1~14.04.3) but it is not going to be installed
 qtdeclarative5-ubuntu-ui-toolkit-plugin : Depends: libqt5qml-graphicaleffects but it is not going to be installed or
                                                    libqt5graphicaleffects5 but it is not installable
                                           Depends: libqt5svg5 but it is not going to be installed
                                           Depends: qtdeclarative5-window-plugin but it is not going to be installed
                                           Depends: qtdeclarative5-qtfeedback-plugin but it is not going to be installed
                                           Depends: qtdeclarative5-unity-action-plugin (>= 1.1.0) but it is not going to be installed
                                           Depends: libqt5organizer5 but it is not going to be installed
                                           Depends: libthumbnailer0 (>= 1.0) but it is not going to be installed
 signon-plugin-password : Depends: signond but it is not going to be installed
 system-image-common : Depends: python3-gnupg but it is not going to be installed
 sysv-rc : Depends: sysvinit-utils (>= 2.86.ds1-62)
 tk : Depends: tk8.6 (>= 8.6.0-2)
 udev : Depends: libcgmanager0 but it is not going to be installed
        Depends: libkmod2 (>= 5~) but it is not going to be installed
        Depends: libnih1 (>= 1.0.0) but it is not going to be installed
        Depends: procps
 unity8 : Depends: qtdeclarative5-ubuntu-thumbnailer0.1 but it is not going to be installed or
                   ubuntu-thumbnailer-impl
          Depends: ubuntu-thumbnailer-impl-0
 unity8-private : Depends: libunity-core-6.0-9 but it is not going to be installed
 upower : Depends: libgudev-1.0-0 (>= 146) but it is not going to be installed
          Depends: libimobiledevice4 (>= 0.9.7) but it is not going to be installed
          Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
          Depends: libusb-1.0-0 (>= 2:1.0.8) but it is not going to be installed
          Depends: pm-utils but it is not going to be installed or
                   systemd but it is not installable or
                   systemd-services
          Recommends: policykit-1
 upstart : Depends: libjson-c2 (>= 0.10) but it is not going to be installed
           Depends: libnih1 (>= 1.0.0) but it is not going to be installed
           Depends: sysvinit-utils
           Depends: initscripts
           Depends: mountall
           Depends: ifupdown (>= 0.6.10ubuntu5)
           Depends: libjson0 (>= 0.10-1.1ubuntu1) but it is not going to be installed
 whoopsie-preferences : Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
                        Depends: libwhoopsie0 but it is not going to be installed
 zeitgeist-core : Depends: libxapian22 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by thabraveRoman** [comment]
I installed realpath and now:

roman@roman-OMEN:~$ sudo apt install realpath
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  guile-2.0-libs libgc1c2
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  realpath
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 14,5 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Get:1 http://ru.archive.ubuntu.com/ubuntu/ trusty/main realpath amd64 1.19 [14,5 kB]
Fetched 14,5 kB in 0s (83,9 kB/s)    
Selecting previously unselected package realpath.
(Reading database ... 199463 files and directories currently installed.)
Preparing to unpack .../realpath_1.19_amd64.deb ...
Unpacking realpath (1.19) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up realpath (1.19) ...
roman@roman-OMEN:~$ sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 realpath
Reading package lists... Done
Building dependency tree       
Reading state information... Done
realpath is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 account-plugin-ubuntuone : Depends: ubuntu-system-settings-online-accounts but it is not going to be installed
 accountsservice : Depends: libgcr-base-3-1 (>= 3.8.0) but it is not going to be installed
                   Depends: libpam0g (>= 0.99.7.1) but it is not going to be installed
                   Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
 adduser : Depends: passwd (>= 1:4.0.12)
 apparmor : Depends: initramfs-tools but it is not going to be installed
 base-files : PreDepends: awk
 bluez : Depends: libusb-0.1-4 (>= 2:0.1.12) but it is not going to be installed
         Depends: module-init-tools but it is not going to be installed
 dbus : Depends: libsystemd-login0 (>= 31) but it is not going to be installed
        Recommends: libpam-systemd but it is not going to be installed
 dconf-gsettings-backend : Depends: dconf-service (>= 0.20.0-1)
                           Depends: dconf-service (< 0.20.0-1.1~)
                           Depends: libdconf1 (= 0.20.0-1) but it is not going to be installed
 gir1.2-glib-2.0 : Depends: libgirepository-1.0-1 (>= 1.40.0-1ubuntu0.2) but it is not going to be installed
 gstreamer1.0-plugins-base : Depends: libcdparanoia0 (>= 3.10.2+debian) but it is not going to be installed
                             Depends: libogg0 (>= 1.0rc3) but it is not going to be installed
                             Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
                             Depends: libtheora0 (>= 1.0) but it is not going to be installed
                             Depends: libvisual-0.4-0 (>= 0.4.0-4) but it is not going to be installed
                             Depends: libvorbis0a (>= 1.1.2) but it is not going to be installed
                             Depends: libvorbisenc2 (>= 1.1.2) but it is not going to be installed
 gstreamer1.0-plugins-good : Depends: libaa1 (>= 1.4p5) but it is not going to be installed
                             Depends: libavc1394-0 (>= 0.5.3) but it is not going to be installed
                             Depends: libcaca0 (>= 0.99.beta17-1) but it is not going to be installed
                             Depends: libcairo-gobject2 (>= 1.10.0) but it is not going to be installed
                             Depends: libcairo2 (>= 1.10.0) but it is not going to be installed
                             Depends: libdv4 but it is not going to be installed
                             Depends: libflac8 (>= 1.3.0) but it is not going to be installed
                             Depends: libgstreamer-plugins-good1.0-0 (= 1.2.4-1~ubuntu1) but it is not going to be installed
                             Depends: libiec61883-0 (>= 1.2.0) but it is not going to be installed
                             Depends: libjack-jackd2-0 (>= 1.9.5~dfsg-14) but it is not going to be installed or
                                      libjack-0.116
                             Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
                             Depends: libraw1394-11 but it is not going to be installed
                             Depends: libshout3 but it is not going to be installed
                             Depends: libsoup2.4-1 (>= 2.38) but it is not going to be installed
                             Depends: libspeex1 (>= 1.2~beta3-1) but it is not going to be installed
                             Depends: libtag1c2a (>= 1.5) but it is not going to be installed
                             Depends: libxv1 but it is not going to be installed
                             Recommends: gstreamer1.0-x but it is not going to be installed
 libaccounts-qt5-1 : Depends: libaccounts-glib0 (>= 1.14) but it is not going to be installed
                     Depends: libqt5xml5 (>= 5.0.2) but it is not going to be installed
 libaccountsservice0 : Depends: libgcr-base-3-1 (>= 3.8.0) but it is not going to be installed
                       Depends: libsystemd-login0 (>= 186) but it is not going to be installed
 libc6 : Breaks: libc6:i386 (!= 2.19-0ubuntu6.9) but 2.19-0ubuntu6 is to be installed
 libc6:i386 : Breaks: libc6 (!= 2.19-0ubuntu6) but 2.19-0ubuntu6.9 is to be installed
 libcap2-bin : Depends: libcap2 (>= 2.10) but it is not going to be installed
               Recommends: libpam-cap but it is not going to be installed
 libfolks25 : Depends: folks-common (= 0.9.5-1ubuntu5) but it is not going to be installed
              Recommends: libfolks-eds25 but it is not going to be installed
 libgcc1 : Depends: gcc-4.9-base (= 4.9.3-0ubuntu4) but it is not going to be installed
           Breaks: libgcc1:i386 (!= 1:4.9.3-0ubuntu4) but 1:4.9-20140406-0ubuntu1 is to be installed
 libgcc1:i386 : Breaks: libgcc1 (!= 1:4.9-20140406-0ubuntu1) but 1:4.9.3-0ubuntu4 is to be installed
 libgl1-mesa-dri : Depends: libllvm3.4 but it is not going to be installed
 libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.48) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libelf1:i386 (>= 0.142) but it is not going to be installed
                        Depends: libexpat1:i386 (>= 2.0.1) but it is not going to be installed
                        Depends: libllvm3.4:i386 but it is not going to be installed
                        Depends: libstdc++6:i386 (>= 4.6) but it is not going to be installed
                        Recommends: libtxc-dxtn-s2tc0:i386 but it is not going to be installed or
                                    libtxc-dxtn0:i386
 libgl1-mesa-glx:i386 : Depends: libdrm2:i386 (>= 2.3.1) but it is not going to be installed
                        Depends: libglapi-mesa:i386 (= 10.1.0-4ubuntu5) but it is not going to be installed
                        Depends: libx11-6:i386 (>= 2:1.4.99.1) but it is not going to be installed
                        Depends: libx11-xcb1:i386 but it is not going to be installed
                        Depends: libxcb-dri2-0:i386 (>= 1.8) but it is not going to be installed
                        Depends: libxcb-dri3-0:i386 but it is not going to be installed
                        Depends: libxcb-glx0:i386 (>= 1.8) but it is not going to be installed
                        Depends: libxcb-present0:i386 but it is not going to be installed
                        Depends: libxcb-sync1:i386 but it is not going to be installed
                        Depends: libxcb1:i386 (>= 1.9.2) but it is not going to be installed
                        Depends: libxdamage1:i386 (>= 1:1.1) but it is not going to be installed
                        Depends: libxext6:i386 but it is not going to be installed
                        Depends: libxfixes3:i386 but it is not going to be installed
                        Depends: libxshmfence1:i386 but it is not going to be installed
                        Depends: libxxf86vm1:i386 but it is not going to be installed
                        Depends: libudev1:i386 but it is not going to be installed or
                                 libudev0:i386 but it is not installable
 libgstreamer-plugins-base0.10-0 : Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
 libgstreamer-plugins-base1.0-0 : Depends: liborc-0.4-0 (>= 1:0.4.18) but it is not going to be installed
 libnih-dbus1 : Depends: libnih1 (= 1.0.3-4ubuntu25) but it is not going to be installed
 libnm-glib4 : Depends: libgudev-1.0-0 (>= 146) but it is not going to be installed
 libnm-util2 : Depends: libnspr4 (>= 2:4.9-2~) but it is not going to be installed or
                        libnspr4-0d (>= 1.8.0.10) but it is not going to be installed
               Depends: libnss3 (>= 2:3.13.4-2~) but it is not going to be installed or
                        libnss3-1d (>= 3.12.0~1.9b1) but it is not going to be installed
 liboauth0 : Depends: libcurl3-gnutls (>= 7.16.2) but it is not going to be installed
             Depends: libnss3 (>= 2:3.13.4-2~) but it is not going to be installed or
                      libnss3-1d (>= 3.12.0~1.9b1) but it is not going to be installed
 libpackagekit-glib2-16 : Depends: libarchive13 but it is not going to be installed
 libpam-runtime : Depends: libpam-modules (>= 1.0.1-6) but it is not going to be installed
 libpulse0 : Depends: libjson-c2 (>= 0.10) but it is not going to be installed
             Depends: libsndfile1 (>= 1.0.20) but it is not going to be installed
 libqt5gui5 : Depends: fontconfig
              Depends: libfontconfig1 (>= 2.9.0) but it is not going to be installed
              Depends: libfreetype6 (>= 2.3.5) but it is not going to be installed
              Depends: libgtk2.0-0 (>= 2.24.0) but it is not going to be installed
              Depends: libharfbuzz0b (>= 0.9.11) but it is not going to be installed
              Depends: libpango-1.0-0 (>= 1.14.0) but it is not going to be installed
              Depends: libxcb-image0 (>= 0.3.9) but it is not going to be installed
              Depends: libxcb-render-util0 (>= 0.3.8) but it is not going to be installed
              Depends: libxcb-render0 but it is not going to be installed
              Depends: libxcb-shape0 but it is not going to be installed
              Depends: libxcb-shm0 but it is not going to be installed
              Depends: libxcb-xkb1 but it is not going to be installed
              Depends: libxi6 (>= 2:1.2.99.4) but it is not going to be installed
              Depends: libxkbcommon-x11-0 (>= 0.4.0) but it is not going to be installed
 libsqlite3-0 : Breaks: libsqlite3-0:i386 (!= 3.8.2-1ubuntu2.1) but 3.8.2-1ubuntu2 is to be installed
 libsqlite3-0:i386 : Breaks: libsqlite3-0 (!= 3.8.2-1ubuntu2) but 3.8.2-1ubuntu2.1 is to be installed
 libtimezonemap1 : Depends: libcairo2 (>= 1.10) but it is not going to be installed
                   Depends: libgtk-3-0 (>= 3.1.4) but it is not going to be installed
 libudev1 : Depends: libcgmanager0 but it is not going to be installed
            Depends: libnih1 (>= 1.0.0) but it is not going to be installed
 libuuid1 : Depends: passwd
            Recommends: uuid-runtime
 libxcb1 : Depends: libxau6 but it is not going to be installed
           Depends: libxdmcp6 but it is not going to be installed
 openssh-sftp-server : Depends: openssh-client
                       Recommends: openssh-server or
                                   ssh-server
 python : Depends: python2.7 (>= 2.7.5-1~) but it is not going to be installed
          Depends: libpython-stdlib (= 2.7.5-5ubuntu3) but it is not going to be installed
 python3 : Depends: libpython3-stdlib (= 3.4.0-0ubuntu2) but it is not going to be installed
 python3-apt : Depends: libapt-inst1.5 (>= 0.8.11) but it is not going to be installed
 python3-aptdaemon.pkcompat : Depends: python3-aptdaemon (= 1.1.1-1ubuntu5.2) but it is not going to be installed
                              Depends: gir1.2-packagekitglib-1.0 (>= 0.8.9) but it is not going to be installed
 python3-gi : Depends: libgirepository-1.0-1 (>= 1.33.10) but it is not going to be installed
 python3-minimal : Depends: python3.4-minimal (>= 3.4.0-0~) but it is not going to be installed
 python3.4 : Depends: python3.4-minimal (= 3.4.3-1ubuntu1~14.04.3) but it is not going to be installed
             Depends: libpython3.4-stdlib (= 3.4.3-1ubuntu1~14.04.3) but it is not going to be installed
 qtdeclarative5-ubuntu-ui-toolkit-plugin : Depends: libqt5qml-graphicaleffects but it is not going to be installed or
                                                    libqt5graphicaleffects5 but it is not installable
                                           Depends: libqt5svg5 but it is not going to be installed
                                           Depends: qtdeclarative5-window-plugin but it is not going to be installed
                                           Depends: qtdeclarative5-qtfeedback-plugin but it is not going to be installed
                                           Depends: qtdeclarative5-unity-action-plugin (>= 1.1.0) but it is not going to be installed
                                           Depends: libqt5organizer5 but it is not going to be installed
                                           Depends: libthumbnailer0 (>= 1.0) but it is not going to be installed
 signon-plugin-password : Depends: signond but it is not going to be installed
 system-image-common : Depends: python3-gnupg but it is not going to be installed
 sysv-rc : Depends: sysvinit-utils (>= 2.86.ds1-62)
 tk : Depends: tk8.6 (>= 8.6.0-2)
 udev : Depends: libcgmanager0 but it is not going to be installed
        Depends: libkmod2 (>= 5~) but it is not going to be installed
        Depends: libnih1 (>= 1.0.0) but it is not going to be installed
        Depends: procps
 unity8 : Depends: qtdeclarative5-ubuntu-thumbnailer0.1 but it is not going to be installed or
                   ubuntu-thumbnailer-impl
          Depends: ubuntu-thumbnailer-impl-0
 unity8-private : Depends: libunity-core-6.0-9 but it is not going to be installed
 upower : Depends: libgudev-1.0-0 (>= 146) but it is not going to be installed
          Depends: libimobiledevice4 (>= 0.9.7) but it is not going to be installed
          Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
          Depends: libusb-1.0-0 (>= 2:1.0.8) but it is not going to be installed
          Depends: pm-utils but it is not going to be installed or
                   systemd but it is not installable or
                   systemd-services
          Recommends: policykit-1
 upstart : Depends: libjson-c2 (>= 0.10) but it is not going to be installed
           Depends: libnih1 (>= 1.0.0) but it is not going to be installed
           Depends: sysvinit-utils
           Depends: initscripts
           Depends: mountall
           Depends: ifupdown (>= 0.6.10ubuntu5)
           Depends: libjson0 (>= 0.10-1.1ubuntu1) but it is not going to be installed
 whoopsie-preferences : Depends: libpolkit-gobject-1-0 (>= 0.99) but it is not going to be installed
                        Depends: libwhoopsie0 but it is not going to be installed
 zeitgeist-core : Depends: libxapian22 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
roman@roman-OMEN:~$ ~/.steam/ubuntu12_32/steam-runtime/pinned_libs_64
bash: /home/roman/.steam/ubuntu12_32/steam-runtime/pinned_libs_64: No such file or directory
roman@roman-OMEN:~$

**Comment by thabraveRoman** [comment]
This error

**Comment by kisak-valve** [comment]
Hello @thabraveRoman, upstream distro support for Ubuntu 14.04 has ended. If you're able to reproduce this issue with a newer distro release, please open a new issue report and we can ponder it some more.

Closing as obsolete.
