### ISSUE TITLE
Not shown update

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6106]
#### Your system information

* Steam client version (build number or date): Feb 18 2019, at 22:09:18
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

I have skyrim special edition update, that isn't shown in downloads window.
How can i fix it?
https://puu.sh/CQIzr/81b040d7bd.png

**Comment by XakepSDK** [comment]
It happened again! I did not closed steam, what can i do to debug this?
Game - the wither 3 wild hunt
https://puu.sh/DaWLB/2c661af2e6.png

**Comment by XakepSDK** [comment]
Again, but 2 games: Monster Hunter World and Witcher 3

**Comment by kisak-valve** [comment]
Hello @XakepSDK, are you still experiencing this issue on an up to date system?

**Comment by XakepSDK** [comment]
I don't think so

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
