### ISSUE TITLE
Killing Floor 2 quits Steam (232090)

### ISSUE THREAD

**Issue by Niroc** [ValveSoftware/steam-for-linux#6107]
# Compatibility Report
- Name of the game with compatibility issues: Killing Floor 2
- Steam AppID of the game: 232090
[steam-232090.log](https://github.com/ValveSoftware/Proton/files/2897955/steam-232090.log)

## System Information
- GPU: GTX 870m
- Driver/LLVM version: Nvidia 415.27
- Kernel version:  4.19.24-1-MANJARO
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Niroc/ab1f133f7e79e9e0d7932670b5f6cdc5
- Proton version: 3.16-7

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
Using Alt+F4 or the in-game "Exit to Desktop" function not only quits the game but, it also quits Steam 

## Reproduction
Exit the game

**Comment by kisak-valve** [comment]
Hello @Niroc, does `/tmp/dumps/<username>_stdout.txt` have any hints after this occurs?

**Comment by Niroc** [comment]
Hey @kisak-valve 
It appears to be the pipes
[niroc_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/2897974/niroc_stdout.txt)

Game removed: AppID 232090 "", ProcID 30222 
crash_20190224140836_1.dmp[30393]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190224140836_1.dmp
/home/niroc/.local/share/Steam/steam.sh: line 889: 29857 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190224140836_1.dmp[30393]: Finished uploading minidump (out-of-process): success = yes
crash_20190224140836_1.dmp[30393]: response: CrashID=bp-8123e26f-6680-4453-8e90-a55262190224
crash_20190224140836_1.dmp[30393]: file ''/tmp/dumps/crash_20190224140836_1.dmp'', upload yes: ''CrashID=bp-8123e26f-6680-4453-8e90-a55262190224''
../common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
crash_20190224141001_6.dmp[30409]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190224141001_6.dmp
../common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
../common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
../common/processpipe_posix.cpp (507) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Broken pipe)
../common/pipes.cpp (750) : CClientPipe::BWriteAndReadResult: BWrite failed
../common/pipes.cpp (750) : Fatal assert failed: ../common/pipes.cpp, line 750.  Application exiting.

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
assert_20190224141001_8.dmp[30412]: Uploading dump (out-of-process)
/tmp/dumps/assert_20190224141001_8.dmp
crash_20190224141001_6.dmp[30409]: Finished uploading minidump (out-of-process): success = yes
crash_20190224141001_6.dmp[30409]: response: Discarded=1
crash_20190224141001_6.dmp[30409]: file ''/tmp/dumps/crash_20190224141001_6.dmp'', upload yes: ''Discarded=1''
assert_20190224141001_8.dmp[30412]: Finished uploading minidump (out-of-process): success = yes
assert_20190224141001_8.dmp[30412]: response: Discarded=1
assert_20190224141001_8.dmp[30412]: file ''/tmp/dumps/assert_20190224141001_8.dmp'', upload yes: ''Discarded=1''

Would you like any or all of these dumps?

**Comment by kisak-valve** [comment]
Hello @Niroc, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
