### ISSUE TITLE
Steam main window does not open on launch

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/steam-for-linux#6112]
As referenced on https://github.com/ValveSoftware/steam-for-linux/issues/5974 my steam won't open and has to be opened from taskbar.

Is there any permanent solution? The issue is still present and my workaround is to always invoke `xfce-panel` to open it which is pita.. (My DE is not using taskbar usually..)

Problem also present on debian and ubuntu.

--- 

Can i fix this from my side?

Can this be fixed by upstream?

**Comment by kisak-valve** [comment]
Hello @Kreyren, are you still experiencing this issue on an up to date system?

**Comment by Kreyren** [comment]
> Hello @Kreyren, are you still experiencing this issue on an up to date system?

No, iirc it was caused by insufficient implementation of the web browser that caused the GUI to crash.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.
