### ISSUE TITLE
nvidia binary driver 418.39 causes crash on startup

### ISSUE THREAD

**Issue by LouisCyfer** [ValveSoftware/steam-for-linux#6113]
#### Your system information

* Steam client version (build number or date): 1550534751
* Distribution (e.g. Ubuntu): Ubuntu 16.04/18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I hope this issue is resolvable tho I wish to keep up-to-date with drivers etc.

On startup steam mumbles about not finding libGL.so.1

This issue I temporarily could solve by linking this:
> sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so.1

Now I get a Steam error window with "glxChooseVisual Failed"

I suspect the latest NVIDIA propietary driver (time of writing/418.39) are borking the 32bit libs and their system linking.

Note: NVIDIA propietary driver 410.48 are a great fallback driver even with CUDA 10.0!

So, is there anything I can do except switching back to 410.48?

#### Steps for reproducing this issue:

1. install nvidia binary driver 418.39

2. run this command in terminal to link libGL.so.1:
> sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so.1

3. watch it crash

**Comment by kisak-valve** [comment]
Hello @LouisCyfer, mesa's libGL.so.1 is not compatible with nVidia's proprietary driver. This driver issue is a continuation of #5778 and needs to be fixed by nVidia.

You may have better luck with the .run installer instead of the .deb.

Closing in favor of the existing issue report.
