### ISSUE TITLE
Steam proposes to install games only to default location and to /boot

### ISSUE THREAD

**Issue by lumag** [ValveSoftware/steam-for-linux#612]
Actually it looks like two problems here. First, Steam incorrectly parses filesystem information (mtab? /proc/mounts? whatever). From all the mounted partitions it selects only /boot. For the reference I will provide my /proc/mounts at the end of the bug report. Note that I also /home and / mounted. Most probably it looks for /dev/?da? mounts instead of just block devices?

Then it also does not allow one to specify an installation to the user (some kind of 'Other' installation directory - selected by user).

```
$ cat /proc/mounts
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=10240k,nr_inodes=214190,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=407420k,mode=755 0 0
/dev/mapper/valinor-root / ext3 rw,relatime,errors=remount-ro,barrier=1,data=ordered 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /run/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=814820k 0 0
/dev/sda1 /boot ext3 rw,relatime,errors=continue,barrier=1,data=ordered 0 0
/dev/mapper/valinor-home /home xfs rw,relatime,attr2,delaylog,noquota 0 0
rpc_pipefs /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
```

**Comment by kisak-valve** [comment]
Closing as Steam was changed to provide a list of pre-selected Steam Library Folders instead of mount points when there are multiple storage locations.
