### ISSUE TITLE
Issues with a shared steam library between Windows and Linux

### ISSUE THREAD

**Issue by Virepri** [ValveSoftware/steam-for-linux#6120]
#### Your system information

* Steam client version (build number or date): 1.0.0.59-1
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

If a game that features native Linux support is installed from windows, the following issues appear:
- Steam does not recognize the game was installed from windows, and as a result
    - Tries to update the game with Linux files (and thus needs to have an integrity check from Windows)
    - Does not allow trying to start the game with Proton
    - Does not allow updating the game with Windows files

I understand this SUPER was never an intended use case of Steam libraries. I only linked my library on an external drive to install windows-only games on it from Linux, and then discovered this. Some kind of support for this use case would be appreciated, though, even if it _is_ just breaking the ability to link a Windows steam library to a Linux steam install (which wouldn't be preferable but would prevent anybody from breaking their games like this).

#### Steps for reproducing this issue:

1. Boot steam on windows, install a game which has both linux and windows native releases.
2. Reboot to linux
3. Start steam, see the above mentioned issues occurring.

**Comment by kisak-valve** [comment]
Hello @Virepri, sharing libraries across OSes is not supported.

This is noted at "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." on https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation (from #546).
