### ISSUE TITLE
command line options for steam won't give back input / return

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/steam-for-linux#6123]
#### Your system information

* Steam client version (build number or date): Feb 18 2019 22:09:18
* Distribution (e.g. Ubuntu):  ubuntu 18.10
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

Steam command line options : 
https://developer.valvesoftware.com/wiki/Command_Line_Options

do not return in certain cases where you would expect them to.

for example : 
```
steam -login $STEAMUSERNAME $STEAMPASSWORD -nofriendsui -applaunch 9420 -shutdown
```
After the game ran and I closed it, I was sitting in front of a terminal expecting it to give me back control.

but it never did. I took a couple extra measures : I added `-shutdown` though I'm not sure this command can be chained in the same way steamCMD commands can be, the docs aren't very explicit on this.

#### Steps for reproducing this issue:

1. type steam -applaunch `<nonSourceAppId>`

**Comment by kisak-valve** [comment]
Hello @tatsujb, this scenario is already being tracked at #1721. Closing as a duplicate.
