### ISSUE TITLE
Home Streaming locks up after a few minutes on latest beta

### ISSUE THREAD

**Issue by noammor** [ValveSoftware/steam-for-linux#6128]
#### Your system information

* Steam client version (build number or date): March 7, 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

After the last beta client update, I tried to use Home Streaming to watch a video. Every 3-4 minutes of watching video I encountered the following behavior: 

 - On the client (Steam Link device), the video stops playing: video is stuck on one frame, no audio. Using the Steam controller I can move the cursor, but no amount of clicking shows anything visibly happening on the client.
 - On the host, the the video continues to play. I believe the host takes input from the client even though nothing visible is changing on the client besides the mouse cursor moving around.

Further testing showed: 

 - It locks up without any video, too (streaming the desktop)
 - It locks up in games too

I tried updating everything, and lock-ups still happened. When I disabled the beta participation, lock-ups stopped.

I'm using an Nvidia RTX 2080.

#### Steps for reproducing this issue:

1. Start Home Streaming to a Steam Link (haven't tested otherwise)
2. Wait a few minutes
3. Try doing anything

**Comment by sorsasampo** [comment]
Thanks for reporting this! I'm seeing the exact same problem in beta: streaming freezes, but the video keeps playing on host. Disabling beta participation fixes the issue.

Debian GNU/Linux 9.8 (stretch), Linux 4.9.0-8-amd64, NVIDIA GeForce GTX 750 Ti.

**Comment by ryoko227** [comment]
Same issue, will try disabling the beta to see if I can replicate the work around.

**Comment by bradgy** [comment]
Happened to me as well about a minute into streaming GTAV from Linux steam beta host to rPi steamlink app. I was able to ssh into my pi from my phone, kill the steamlink process, and then restart the stream which hooked back into the game. Unfortunately leaving the game meant steam BPM lost  controller input so the game needed to be restarted anyway.
Another issue I saw whilst testing last night with the steamlink app was that audio still came out of the host Linux PC, but I might need to open a separate issue for that.

**Comment by kisak-valve** [comment]
Hello, per "Fixed video freeze after a short time streaming" in the [2019-03-08](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141152962689) Steam client beta update, please retest this issue.

**Comment by bradgy** [comment]
Played rocket league for ~20 min with no freezing after updating the host steam client... seems to have fixed it for me. 

The audio is being muted properly as well now, not sure if that's related as well or just coincidental.

Thanks Kisak!

**Comment by noammor** [comment]
I'm seeing it fixed as well.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
