### ISSUE TITLE
DIrt Rally Not Intenet Connection

### ISSUE THREAD

**Issue by freerunnerlive** [ValveSoftware/steam-for-linux#6130]
#### Your system information
Proton:3.16-7
Distro:Debian GNU/Linux 8.11 (jessie)
Kernel:4.18.0-2-amd64
RAM:16 GB
GPU Driver:NVIDIA 410.66
GPU:NVIDIA GeForce GTX 1070
CPU:Intel Core i7-2700K @ 3.50GHz
* Steam client version (build number or date): 

#### Please describe your issue in as much detail as possible:
Dirt Rally 2.0 

#### Steps for reproducing this issue:

1. Downloading the cert: https://www.upload.ee/files/9626680/codemasters.pem.html
2. openssl x509 -in codemasters.pem -inform PEM -out codemasters.crt
3. cat codemasters.crt >> /etc/ssl/certs/ca-certificates.crt

**Comment by mrpippy** [comment]
This is a Proton issue and tracked at https://github.com/ValveSoftware/Proton/issues/2366

**Comment by kisak-valve** [comment]
Thanks for pointing this out @mrpippy. Since we're tracking issues with games run with Proton in the Proton issue tracker, and using one issue report per unofficially supported game title, https://github.com/ValveSoftware/Proton/issues/2366 is the right place to track this issue.
