### ISSUE TITLE
Can't uninstall proton from Tools tab

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6132]
#### Your system information

* Steam client version (build number or date): Mar 8 2019, at 19:34:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Go to tools tab
2. Uninstall proton
3. Uninstall more of proton entries, if step 2. was success
4. See error "Missing shared content" error

I tried this because steam didn't update proton from 3.16-7 to 3.16-8

**Comment by Cheaterman** [comment]
No updates on this? :-)

**Comment by tomchiverton** [comment]
I was able to do the above steps, but still have a "Proton 4.11" folder in .local/share/Steam/steamapps/common/ even though it's no longer listed under Tools in Steam

**Comment by kisak-valve** [comment]
Closing in favor of #6894.
