### ISSUE TITLE
Controller Config doesn't load automatically

### ISSUE THREAD

**Issue by awsdert** [ValveSoftware/steam-for-linux#6135]
#### Your system information

* Steam client version (build number or date): March 9th 2019 @ 1am
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Automatic for steam & green tick in shield on my taskbar at the moment

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Login, steam boots on login
2. In or out of steam UI, turn on controller
3. Expected Config with reverse scrolling (what it should've been from start) and got default behavior instead

I have to manually go into the desktop config before the controller behaves the way I expect it to.

**Comment by awsdert** [comment]
Btw I had this file to start with (was missing the switch rule so I added that),
/lib/udev/rules.d/99-steam-controller-perms.rules
I saved a copy as
/lib/udev/rules.d/60-steam-controller-perms.rules
on my last login as steam stated it should be called but no change to my problem, I gotta go to bed now at won't have time to respond until after gospel tomorrow night. I did make sure the pgraffais or whatever it was was changed to my own group but that also had no effect.

**Comment by awsdert** [comment]
Whatever you did seems to be working atm the moment, I finally tried the controller without manually loading the config just now after booting up my computer and it's responding the way I expect it too, haven't tried everything but the scroll behavior and the assigned R/L click buttons are doing as I expect, I'll continue normal use for a about a month, if I don't experience any discrepancies between my config and what actually happens I'll consider this solved

**Comment by awsdert** [comment]
Must've been a fluk because it went back to the annoying behavior this morning

**Comment by kisak-valve** [comment]
Hello @awsdert, are you still experiencing this issue on an up to date system?

**Comment by awsdert** [comment]
Haven't used the controller for desktop stuff recently so I'll try after I've done my daily Japanese studies

**Comment by awsdert** [comment]
Yep, works perfectly fine :)
