### ISSUE TITLE
Games use controllers provided by hid_sony or xpad not the ones provided by steam.

### ISSUE THREAD

**Issue by aTosser** [ValveSoftware/steam-for-linux#6138]
#### Your system information

* Steam client version (build number or date): Mar 9 2019
* Distribution (e.g. Ubuntu): Gentoo: Kernel 4.20.7
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
When I use hid_sony with my DS4 I can not play Rocket League at all because it chooses to use /dev/input/js0 which is provided by hid_sony. In CrossCode the game responds to BOTH /dev/input/js1 and /dev/input/js0 which because the keybindings are all messed up with CrossCode the game in completely unplayable with controllers. Right now for Rocket League I had to remap the bindings for SDL manually and disable steam controller support because otherwise I get no controller output at all.

If I blacklist hid_sony or xpad(this issue affects my x360 controller as well) then I get NO controller support at all as Steam can no longer detect any controllers at all.
#### Steps for reproducing this issue:

1. Enable CONFIG_HID_SONY in kernel.
2. Enable Steam controller support.
3a. Run Rocket League -> no controller works
3b. Run CrossCode -> wacky controller behavior

**Comment by Francesco149** [comment]
i think i might be experiencing a similar issue, I'm not sure when it started but trying to play sekiro with a ps3 controller out of the box has super broken bindings where only like 1 button and analog stick work. then if i set the steam input per-game settings to "Force Off" it kinda works but it's still buggy - for example pressing left button also triggers the action for right trigger

**Comment by randomstuff** [comment]
The same kind of thing happened to me because "Steam Overlay" was disabled. Enabling it made the virtual gamepad work.

**Comment by kisak-valve** [comment]
Hello, can someone check if they're still experiencing this issue on an up to date system?

**Comment by aTosser** [comment]
I have retested on a current system. However the results are not really indicative of anything because Rocket League no longer has a native client to test. However, I can use both of my controllers at this point without any need for kernel module fiddling.

I'll close this as no longer relevant.
