### ISSUE TITLE
Goldsrc games not working on AMDGPU video cards

### ISSUE THREAD

**Issue by MJaoune** [ValveSoftware/steam-for-linux#6140]
#### Your system information

* Steam client version (build number or date): Feb 18 2019
* Distribution (e.g. Ubuntu): Gentoo (Kernel 4.19.28, Mesa 18.3.4)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When attempting to start Goldsrc games such as Counter-strike 1.6 or Counter-strike CZ, the game doesn't open up, but it is still running, the word "Running" appears next to title name on Steam library, and I can see hl.sh and hl_linux when running "ps -A | grep hl", and I can only close it by using "kill -9" command, even exiting Steam doesn't close it.

Tried reinstalling Steam, CS, etc... Not working

Source games such as CSGO and CSS work flawlessly.

BTW I am using Steam runtime libraries.

Related (Someone else): https://steamcommunity.com/discussions/forum/1/1779388024827174953/

Log: https://gist.github.com/MJaoune/2a392de51b1a149a2878a17be2e4600d

P.S. When I had an Nvidia GPU with Nvidia proprietary drivers, the games used to work.

#### Steps for reproducing this issue:

1. Get an AMD GPU which supports AMDGPU kernel driver.
2. Use AMDGPU kernel driver with Mesa (Not proprietary driver).
3. Attempt to start any Goldsrc game.

**Comment by kisak-valve** [comment]
Hello @MJaoune, this issue was already tracked at https://github.com/ValveSoftware/halflife/issues/2100. Rebuild mesa with https://cgit.freedesktop.org/mesa/mesa/commit/?id=c605738113fe91d04f799eae52cec28fafac3f2d.
