### ISSUE TITLE
Force Steam Play for games with native ports

### ISSUE THREAD

**Issue by ErikWallstrom** [ValveSoftware/steam-for-linux#6141]
In the [January 17th beta update](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108827819236) change log it says:

> Added the ability to force-enable Steam Play in per-title properties, including for native games

The option to force steam play does not seem to exist. Since the [last issue](https://github.com/ValveSoftware/steam-for-linux/issues/5638) was closed I am writing this here.

**Comment by kisak-valve** [comment]
Hello @ErikWallstrom, the option was implemented. Steam Library -> right click on the game -> Properties -> select `Force the use of a specific Steam Play compatibility tool`.

Closing as this does not appear to be an actionable issue report.
