### ISSUE TITLE
When starting a game the 'start' button is hidden behind the taskbar and the game is not able to start

### ISSUE THREAD

**Issue by Aurdon1234** [ValveSoftware/steam-for-linux#6143]
1. 

#### Your system information

* Steam client version (build number or date): 14/3/19
* Distribution (e.g. Ubuntu): Linux
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Closing do to poor issue report quality. Possibly https://github.com/ValveSoftware/csgo-osx-linux/issues/2004.
