### ISSUE TITLE
Steam can't connect to internet using an proxy connection

### ISSUE THREAD

**Issue by PANCHO7532** [ValveSoftware/steam-for-linux#6151]
#### Your system information

* Steam client version (build number or date): 19/03/2019
* Distribution (e.g. Ubuntu): Linux Mint Cinnamon 64-Bits
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Launched in terminal, throws this:
usuario@PC2 ~ $ steam
Running Steam on linuxmint 18.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1550534751)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
[0319/174024.159774:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: browser
[0319/174024.179755:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0319/174024.179817:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1550527787
[0319/174024.179831:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0319/174024.179837:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
[0319/174024.208154:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
Installing breakpad exception handler for appid(steam)/version(1550534751)
CAppInfoCacheReadFromDiskThread took 71 milliseconds to initialize
Aborting HTTP request because we received invalid headers
Installing breakpad exception handler for appid(steam)/version(1550534751)
Could not create Vulkan instance : 
ERROR_EXTENSION_NOT_PRESENT
Installing breakpad exception handler for appid(steam)/version(1550534751)

(steam:28067): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Opted-in Controller Mask for AppId 0: 0
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Aborting HTTP request because we received invalid headers
Exiting workitem thread
[2019-03-19 17:40:23] Startup - updater built Feb 18 2019 22:08:53
[2019-03-19 17:40:23] Verifying installation...
[2019-03-19 17:40:23] Verification complete
[2019-03-19 17:40:38] Shutdown

#### Steps for reproducing this issue:

1. I am connecting to an local proxy server to my cellphone to gain internet access for my computer, i open the Network Manager (from the panel) > Network Settings > Network Proxy, and set up both http and https proxy fields pointing to the same host and ports. (I tried also setting up only the http proxy field, but the problem its the same.)
2. Opened steam (and after several attempts) and tried to log-in my account. And... it fails
3. Opened steam in the linux terminal, and throws "Aborting HTTP request because we received invalid headers" several times and later it ask for connect in offline mode.

Sorry for my bad english but i dont know what to do now, all the apps are working under the proxy (firefox, apt, irc) but steam is the only one that isn't working.
I dont see anything wrong in Wireshark , anyway i left you the .pcapng, it would help.
[capture.zip](https://github.com/ValveSoftware/steam-for-linux/files/2985501/capture.zip)

I tested steam with its Windows Version and works very nice, but don't works in linux :/
Also i have all UDP and TCP enabled (in an symetrical NAT, but works.)
Please don't say "turn off the proxy boi" because without the proxy i can't connect to the internet.

**Comment by kisak-valve** [comment]
Hello @PANCHO7532, this issue is already being tracked at #1943. Closing as a duplicate.
