### ISSUE TITLE
CSGO stops launching, after installing WINE.

### ISSUE THREAD

**Issue by Xited** [ValveSoftware/steam-for-linux#6152]
#### Your system information

* Steam client version (build number or date): Feb 18 2019, at 22:09:18
* Distribution (e.g. Ubuntu): Kali Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Every time after installing WINE, the CSGO stop launching for ever. I mean, even if I remove WINE, the CSGO stops after a black screen.

#### Steps for reproducing this issue:

1. First install Steam and CSGO.
2. [If you have Kali Linux then you don't have to do anything. Because WINE is pre-installed]. But if you have anything else, just install WINE. Now your CSGO will not launch.

**Comment by Xited** [comment]
I know, Kali Linux is not for gaming. But this problem occurs in every Distributions.

**Comment by kisak-valve** [comment]
Hello @Xited, Kali Linux is purpose made for network penetration testing and is explicitly not meant for general use. Using Steam on it is not supported.

**Comment by Xited** [comment]
Bro, I have tested this in Ubuntu too. The same occurred. And one last thing, don't close any issue without reading it properly.

**Comment by kisak-valve** [comment]
Are there any hints in `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log`?
