### ISSUE TITLE
Proton gets not download for the non-steam games.

### ISSUE THREAD

**Issue by Alexander88207** [ValveSoftware/steam-for-linux#6160]
#### Your system information

* Steam client version: 1.0.0.56
* Distribution: Sabayon
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. Add an non-steam game, without that proton having been downloaded before.
2. Enable Proton for that game
3. Press "Play" and see that the game doesn't start because proton gets not downloaded.

Normally proton gets downloaded by downloading a steam game but doesn't happens for non-steam games.

**Comment by kisak-valve** [comment]
Hello @Alexander88207, are you using Steam's stable or beta client?

**Comment by Alexander88207** [comment]
Yeah its related to #6074
