### ISSUE TITLE
Steam cannot open Friend Chat

### ISSUE THREAD

**Issue by markzz** [ValveSoftware/steam-for-linux#6161]
#### Your system information

* Steam client version (build number or date): Mar 23 2019 00:05:47
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

It appears when GNOME was updated to 3.32, Steam no longer can open steam urls. For example, when trying to open the Friends window, you get `ExecuteSteamURL: "steam://open/friends"` and nothing happens. This happens on both the Friend's menu option and the link in the bottom right of the main window. Even trying to lauch that URL in a different method like in a web browser causes the same thing.

I do get these errors as well, and am including them in case: 

```vulkandriverquery: /home/pgriffais/src/Vulkan/base/vulkanexamplebase.cpp:823: void VulkanExampleBase::initVulkan(): Assertion `res == VK_SUCCESS' failed.```

```./steamwebhelper: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory```

That second one is curious to me as I've never seen a `libpcre.so.3` before. Symbolically linking another pcre shared object to that location does get rid of the error, but it doesn't solve the issue.

#### Steps for reproducing this issue:

1. Launch Steam
2. Click on FRIENDS & CHAT

**Comment by Plagman** [comment]
The Vulkan error message is unrelated, but the dependency problem is related. libpcre.so.3 is supposed to be provided by the Steam Runtime, so please either find the method your distribution offers to re-enable the runtime, or report this bug to your distro packager.

**Comment by kisak-valve** [comment]
Hello @markzz, this issue was previously assessed at #6156. Closing as a duplicate.

Arch bug report: https://bugs.archlinux.org/index.php?do=details&task_id=62095
