### ISSUE TITLE
Library's detail view have a  visual bug on proton non whitelisted titles stats box.

### ISSUE THREAD

**Issue by Blast-City** [ValveSoftware/steam-for-linux#6164]
elementary OS Loki (Ubuntu 16.04).
Steam stable fully updated.

1- Go to settings, enable Proton and uncheck "Enable steam play for all other ti
tles"
2- Go to the library and select the detail view
3- Select a non whitlisted game

Result. The box with game stats (You've played,  Game purchased) doesn't have the right edge.

**Comment by kisak-valve** [comment]
Hello @Blast-City, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
