### ISSUE TITLE
"in game" settings shows the "shortcut key" x button (erase) on the wrong location until the mouse is moved to the right side of the window.

### ISSUE THREAD

**Issue by Blast-City** [ValveSoftware/steam-for-linux#6166]
elementary OS Loki (Ubuntu 16.04).
Steam stable fully updated.

1- Open settings and select "in game".

Result: On the right side of the screen there is a "screenshot key" box with a x button. This button is in the wrong place (left side of the box) until you move the mouse to the right side of the screen. The right place is on right side of the box (after F12).

**Comment by kisak-valve** [comment]
Hello @Blast-City, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
