### ISSUE TITLE
elementary OS. Fullscreen trailers, games and video player makes the wm workspace switch animation stop working. Perhaps Gnome too?

### ISSUE THREAD

**Issue by Blast-City** [ValveSoftware/steam-for-linux#6168]
elementary OS Loki (Ubuntu 16.04).
Steam stable fully updated.

Using `export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` since that's the correct behavior on MacOS and on elementary OS.

1- On workspace 1 start steam and put a trailer, purchased video or a game in fullscreen mode. This content go to workspace 2
2- Press Super+Right to go to the last workspace.
3- Go back to the fullscreen workspace.

Result: There is no workspace switch animation anymore. If you switch to another workspace the animation starts working again. Some shortcuts also stop working and you don't get visual notifications anymore.

It's possible that this is also happening on Gnome.

**Comment by kisak-valve** [comment]
Hello @Blast-City, this issue should also be brought to the attention of the window manager dev(s).

**Comment by Blast-City** [comment]
> Hello @Blast-City, this issue should also be brought to the attention of the window manager dev(s).

Hi already posted it. Thanks.

**Comment by Blast-City** [comment]
I'm closing this issue because it has to do with the OS disabling the compositor on fullscreen apps.
