### ISSUE TITLE
Build-in web browser does not load at all with experimental Kernel 5.1

### ISSUE THREAD

**Issue by TimTomTwo** [ValveSoftware/steam-for-linux#6173]
#### Your system information
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1800X Eight-Core Processor         
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3600 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.1.0-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  X.Org Radeon RX Vega (VEGA10, DRM 3.30.0, 5.1.0-1-MANJARO, LLVM 7.0.1)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.0.0
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 89 Hz
    VendorID:  0x1002
    DeviceID:  0x687f
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 2560 x 2520
    Primary Display Size: 23.50" x 13.23" (26.97" diag)
                                            59.7cm x 33.6cm (68.5cm diag)
    Primary VRAM: 8176 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16050 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  200567 Mb
    Largest Free Hard Disk Block:  85795 Mb
    VR Headset: HTC Vive detected

Recent Failure Reports:

* Steam client version (build number or date): Mar 26 2019, at 23:59:21
* Distribution (e.g. Ubuntu): Manjaro running on experimental Kernel 5.1rc1.d0317.g9e9
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hi,

I'm using the build-in Steam Client from Manjaro Linux and recently updated to the new experimental Linux Kernel 5.1 (to be specific: 5.1rc1.d0317.g9e9)
Since then the web client of Steam is unusable. That loading spinner in the upper right corner is moving, but all pages stay always black.
This affects every Steam feature, where the build in web client is needed (Store front. Community page, Steam Workshop, My Profile, etc...).
Game updates and Cloud syncs doesn't seem to be affected.

Restarting Steam, rebooting OS and even deleting htmlcache and httpcache did not help.

Thanks in advance,
TimTomTwo

PS: While I am at it, I would REALLY REALLY love it, if it would finally be possible to zoom in and out inside the Steam web client ([Ctrl] [+] , [Ctrl] [-] or [Ctrl] and with the mouse scroll wheel). This feature is standard in every other browser, but not here. With any resolution higher than 1080p, the font size can get annoyingly small... 

Gist of _stdout.txt: https://gist.github.com/TimTomTwo/61c824c6915e92e003f2cbbddc2de632

#### Steps for reproducing this issue:

1. Start Steam
2. Click on "Store"
3. ???
4. No profit

**Comment by kisak-valve** [comment]
Hello @TimTomTwo, please copy `/tmp/dumps/<username>_stdout.txt` to a [gist](https://gist.github.com) and include a link to the gist in this issue report.

There's a feature request for browser zoom at #6007.

**Comment by TimTomTwo** [comment]
Hi @kisak-valve ,
wow, that was fast!
I've updated the Issue and added the link: https://gist.github.com/TimTomTwo/61c824c6915e92e003f2cbbddc2de632

**Comment by kisak-valve** [comment]
The most recent CEF update needed some additional dependencies and you've hit https://bugs.archlinux.org/index.php?do=details&task_id=62095.

`./steamwebhelper: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory` in your log is the line of interest.

Adding the symlink and libselinux as mentioned in that bug report should get it working again. This issue should be reported to your distro's package maintainer(s) for steam.

**Comment by kisak-valve** [comment]
I was looking at this a little bit more and this should be provided by the Steam runtime at ~/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libpcre.so.3 and /home/kisak/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libselinux.so.1.

Please manually check that you are on the current beta client.

**Comment by kisak-valve** [comment]
If `multilib/steam-native` is installed on the system, the Manjaro steam package disables the Steam runtime, which would explain why it's working on my Manjaro test box and not your system.

With the steam runtime disabled, any new dependencies must be resolved by the Distro's package maintainers.

Closing as not-our-bug.

**Comment by TimTomTwo** [comment]
@kisak-valve , you rock!
That was really fast and helpful!

For anyone else: 
Yes, it's an manjaro steam problem, as @kisak-valve mentioned above with the link: https://bugs.archlinux.org/index.php?do=details&task_id=62095

One of that commentators already build a self-made fix and packaged it in the AUR. 
Link: https://aur.archlinux.org/packages/steam-native-pcre-fix
Works like a charm after installing this.

**Comment by RockyTV** [comment]
This is a better fix than installing selinux/pcre or symlinking libpcre:


```
$ export LD_PRELOAD="/usr/lib/libgio-2.0.so.0:/usr/lib/libglib-2.0.so.0"
$ steam-native
```

Taken from: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1848072002764995823/

**Comment by amadejkastelic** [comment]
> This is a better fix than installing selinux/pcre or symlinking libpcre:
> 
> ```
> $ export LD_PRELOAD="/usr/lib/libgio-2.0.so.0:/usr/lib/libglib-2.0.so.0"
> $ steam-native
> ```
> 
> Taken from: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1848072002764995823/

This breaks fonts in Counter Strike: Global Offensive.

**Comment by RockyTV** [comment]
@amadejkastelic Correct, I have reported it in the corresponding Arch Linux issue. There's two ways you can fix the native runtime but they're hacky workarounds until Valve decides to do anything about it. I'd suggest reading the discussion at #6156 - we, Arch users, are hoping that the proposed patch will land upstream.

I mentioned 2 ways because one is the DIY way, the other is provided by an AUR package that doesn't require you to mess around with the Steam runtime.

**Comment by sTiKyt** [comment]
Not only Manjaro bug, i have same problem with original Arch Linux
But this fix from AUR works as well.
https://aur.archlinux.org/packages/steam-native-pcre-fix
