### ISSUE TITLE
Steam closes itself when running a game in Proton 4.2-1

### ISSUE THREAD

**Issue by KayKay91** [ValveSoftware/steam-for-linux#6174]
# Compatibility Report
Any game

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 418.56
- Kernel version: 5.0.2
- [Gist](https://gist.github.com/KayKay91/92d38cca48bd348725171097140c6d79):
- Proton version: 4.12-1

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms
Sometimes Steam closes itself when running any game in Proton 4.12-1, does not happen in other versions

## Reproduction
Run any game in Proton 4.12-1

**Comment by kisak-valve** [comment]
Hello @KayKay91, @Skiski, this reads like a Steam issue rather than an issue with Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

Please copy `/tmp/dumps/<username>_stdout.txt` to a [gist](https://gist.github.com) and include a link to the gist in this issue report.

**Comment by KayKay91** [comment]
Here it is https://gist.github.com/KayKay91/c283b7d6506a41802f75044fe90826c4

**Comment by Skiski** [comment]
Here is mine, after when I tried to launch Risk of Rain 2 for the first time.
https://gist.github.com/Skiski/1ee0766f8df24d5bf3ee88b6320ab153

**Comment by garpu** [comment]
stdout log: https://gist.github.com/garpu/0b1a421f6b08791e140739814b622ddb

Console spew that shows an error:  https://gist.github.com/garpu/57e1b34b59e96b2d3f9fdb4f5bbcc66c

**Comment by garpu** [comment]
Forgot to mention that I'm on Slackware 14.2.  Everything's updated. Crashes always happen with this particular error at that line: 

`../common/pipes.cpp (766) : Fatal assert failed: ../common/pipes.cpp, line 766.  Application exiting.

../common/pipes.cpp (766) : Fatal assert failed: ../common/pipes.cpp, line 766.  Application exiting.
`

**Comment by garpu** [comment]
For what it's worth, I haven't had a crash since proton 4.2-2 launched.

**Comment by arzardk** [comment]
Can confirm that Proton 4.2-2 fixed this issue for me.

**Comment by Skiski** [comment]
I haven't had a crash since 4.2-2 but if I run a game with proton, I often have to relaunch steam to run another. When I've pinned down when it occurs, I'll make a report.

**Comment by kisak-valve** [comment]
Closing per the last several comments.
