### ISSUE TITLE
Steamos big Picture mode How to view the game's FPS

### ISSUE THREAD

**Issue by ZILCKIQ** [ValveSoftware/steam-for-linux#6175]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): steamos
* Opted into Steam client beta?: [Yes/No]no
* Have you checked for system updates?: [Yes/No]yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Steamos big Picture mode How to view the game's FPS
2. 
3.

**Comment by kisak-valve** [comment]
Hello @ZILCKIQ, this feature request is already being tracked at #4115. Closing as a duplicate.
