### ISSUE TITLE
Wrong folder for DXVK cache for Proton games in Steam

### ISSUE THREAD

**Issue by arzardk** [ValveSoftware/steam-for-linux#6182]
#### Your system information

* Steam client version (build number or date): Mar 30 2019, 01:35:39
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
For some reasons Proton started to storing cache not in the game related cache folder. For example: Risk of Rain 2 cache folder is `steamapps/shadercache/632360/DXVK_state_cache`, but when you launch the game, cache stored in `steamapps/shadercache/0/DXVK_state_cache
`. Also same issue you can observe with `nvidiav1` cache folder.
#### Steps for reproducing this issue:

1. Opt into Steam Beta client
2. Download any game with DirectX 11 support
3. Launch game through Proton

**Comment by arzardk** [comment]
Problem is now present in latest Stable Steam client for Linux build Apr 16 2019, 21:10:43

**Comment by arzardk** [comment]
It seems like `nvidiav1` cache is now stored properly. Only one issue still remains: DXVK cache.
Steam for Linux Beta May 18 2019, 00:44:39

**Comment by arzardk** [comment]
All problems fixed (at least for me) in Steam for Linux build Jun 14 2019, 20:52:24, Ubuntu 19.04

**Comment by kisak-valve** [comment]
Thanks for following up, closing per the last comment.
