### ISSUE TITLE
Left click on steam icon in tray does nothing

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6186]
#### Your system information

* Steam client version (build number or date): Mar 30 2019, at 01:35:39
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System info: https://gist.github.com/XakepSDK/dc31565852bcbe35ef360aa97e9b9b66

I'm on KDE with KWin 5.15.3
plasmashell 5.15.3
Qt: 5.12.2
KDE Frameworks: 5.56.0
kf5-config: 1.0

1. Start steam
2. Close steam window
3. Single / Double LMB click on steam icon in tray
4. Steam window doesn't appear

This happened with older versions of KDE, Qt, KWin too.
Only way to open steam window is RMB on tray icon and click on needed menu item.

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue is already being tracked at #6178. Closing as a duplicate.

**Comment by superherointj** [comment]
I am still being affected by this.
