### ISSUE TITLE
Steam Download Manager API

### ISSUE THREAD

**Issue by APakrohk** [ValveSoftware/steam-for-linux#6187]
Please check the link below

https://github.com/persepolisdm/persepolis/issues/606

**Comment by kisak-valve** [comment]
Hello @APakrohk, for clarity, please explain exactly what the issue is and what you're asking for.

**Comment by APakrohk** [comment]
We have problem for download with steam in the country with slow internet speed. Please cooperated with persepolis download maneger.

**Comment by kisak-valve** [comment]
Integrating Steam into a third party download manager is a non-starter on Valve's side. The download manager might be able to call [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) in a similar way [LinuxGSM](https://github.com/GameServerManagers/LinuxGSM) does to solve your riddle.
