### ISSUE TITLE
Artifact Segfaults

### ISSUE THREAD

**Issue by Oliver-1xok** [ValveSoftware/steam-for-linux#6192]
#### Your system information

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-47-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.2.8
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x591b
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.64" (15.51" diag)
                                            34.4cm x 19.4cm (39.4cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC3254

Memory:
    RAM:  15889 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  223754 Mb
    Largest Free Hard Disk Block:  82145 Mb
    VR Headset: None detected

Recent Failure Reports:

    Steam client version (build number or date): Feb 18 2019 at 22:09:18 (Package version 1550534751)
    Distribution (e.g. Ubuntu): Xubuntu 18.04.2 LTS (64 bit)
    Opted into Steam client beta?: [no]
    Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
The game suddenly segfaults during a match.
 
Core dump:
[crash_20190404003032_1.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/3045020/crash_20190404003032_1.dmp.gz)

Kernel message:
`dcg[23796]: segfault at 1c8 ip 00007f57fe1f5b78 sp 00007ffe65928290 error 4 in libclient.so[7f57fd466000+228a000]
`
#### Steps for reproducing this issue:
Playing a lot of Artifact. The error occurs very rarely.

**Comment by kisak-valve** [comment]
Hello @Oliver-1xok, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
