### ISSUE TITLE
Allow for linux users to download windows versions of games that have a linux port.

### ISSUE THREAD

**Issue by TehSViN24** [ValveSoftware/steam-for-linux#6193]
* Steam client version (build number or date): 30/3/2019
* Distribution (e.g. Ubuntu): Ubuntu 18.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Issue: linux versions of some games like Company of Heroes 2 have a linux port (made by third parties)
The linux port however is usually an older version of the game and some features are incompadible with windows users(like online play).

Solution: allow for linux users to download the windows version a game(if they want to) and launch it with proton.

**Comment by lucifertdark** [comment]
This is already available & has been for a couple of months at least.

**Comment by kisak-valve** [comment]
Library -> Right click on the game -> Properties -> Check `Force the use of a specific Steam Play compatibility tool`
