### ISSUE TITLE
Civilization 6 does not launch

### ISSUE THREAD

**Issue by Nachtpfoetchen** [ValveSoftware/steam-for-linux#6194]
#### Your system information

* Steam client version (build number or date): 1554351903
* Distribution (e.g. Ubuntu): Fedora29
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [GitHub Gist](https://gist.github.com/)
expected behavior:
I click on play and civilization 6 launches.
What did happen nothing.

Output when I try to launch civ6 from lutris:
Running Steam on fedora 29 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Running /usr/bin/steam steam://rungameid/289070

#### Steps for reproducing this issue:

1. Installing CIV 6
2. Checking for errors from the files
3. Click on play

**Comment by kisak-valve** [comment]
Hello @Nachtpfoetchen, in general, game issues should be reported to the game devs. That said, please completely close Steam/lutris, then run Steam on its own and the game from Steam and check `/tmp/dumps/<username>_stdout.txt` if it has any hints as to what went wrong with Civilization 6.

**Comment by Nachtpfoetchen** [comment]
here is the stdout
https://gist.github.com/Nachtpfoetchen/b05f152aa0c9494e6dc6390f9d10de59

**Comment by kisak-valve** [comment]
`./GameGuide/Civ6: symbol lookup error: /lib64/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var` looks like a line of interest.

Do you have a package called `freetype-freeworld` installed, and if so, please test the game with it removed: `dnf remove freetype-freeworld` (from https://bugzilla.redhat.com/show_bug.cgi?id=1579464).

**Comment by Nachtpfoetchen** [comment]
`freetype-freeworld `is not installed, i have the following packages installed:

`fontconfig-devel-2.13.1-3.fc29.x86_64`
`freetype-devel-2.9.1-6.fc29.x86_64`

**Comment by kisak-valve** [comment]
Perhaps the game has bundled a variant of libfreetype that is incompatible with Fedora 29. Try adding `LD_PRELOAD=/usr/lib/libfreetype.so.6 %command%` to the game's launch options. (from https://www.reddit.com/r/linux_gaming/comments/a98ct4/troubleshooting_can_not_launch_civ_6_on_arch_linux/)

**Comment by Nachtpfoetchen** [comment]
does not work for me:
`ERROR: ld.so: object '/usr/lib/libfreetype.so.6' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

here is the full dump:
https://gist.github.com/Nachtpfoetchen/4de868e79abdb79c97397aa18d4b1849

**Comment by kisak-valve** [comment]
I took a look at my Arch and Fedora test box and found that /usr/lib/ on Arch is 64 bit and /usr/lib/ on Fedora is 32 bit, so the LD_PRELOAD message is accurate and the equivalent workaround would be `LD_PRELOAD=/usr/lib64/libfreetype.so.6 %command%` for you.

**Comment by Nachtpfoetchen** [comment]
Great, the game is starting now. Thank you for your assistance.
