### ISSUE TITLE
Steam client using system wine instead of proton

### ISSUE THREAD

**Issue by null-von-sushi** [ValveSoftware/steam-for-linux#6196]
#### Your system information

* Steam client version (build number or date): 1.0.0.59-1
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I enabled proton for all titles. 
 
I expect selecting Play on a windows game to launch it with proton. Instead, the game seems to launch with regular wine. This was tested with Dark Souls 3 and GTA 5. Dark Souls 3 just crashes, however the GTA 5 launcher stays up and gives an error about connecting to steam. 
 
The `steamapps/compatdata/271590` folder (for GTA 5) is empty, and no prefix was created. The `~/.wine/drive_c/users/my_username/My Documents/` folder has a Rockstar Games folder in it. If I delete the folder and relaunch GTA 5, it gets remade, therefore confirming my suspicion that it's using non-proton wine. 
 
Opening the GNOME System Monitor while GTA 5 is showing the error message, I can see that wineserver is being ran from /usr/bin/wineserver instead of some proton directory. 
 
I tried forcing the proton version to another version, but that made no difference. 

#### Steps for reproducing this issue:

1. Enable Steam Play for all games & Agree to restart the Steam client
2. Attempt to run GTA 5 or any other windows game
 
 
 This all works fine on my laptop and everyone else afaik, but on my desktop steam strangely uses the built-in wine instead of proton.

**Comment by kisak-valve** [comment]
Hello @null-von-sushi, please opt into Steam's beta client and check if that has an effect.

**Comment by null-von-sushi** [comment]
will do

**Comment by null-von-sushi** [comment]
Joining the beta did indeed cause steam to actually download a version of proton , and subsequently launching GTA 5 also worked (after I deleted the compatdata directory for the game. Maybe this was only necessary due to me having issues before). Subsequent launches worked without issue. 
 
 
Is this a known bug?

**Comment by kisak-valve** [comment]
Thanks for checking.

Yes, this is a known issue and Steam's current beta client has improved logic to manage Proton versions (#6045 / #6093).

**Comment by null-von-sushi** [comment]
Ah I see. It's nice to know it's not something I broke :)

If you need me to test anything else I am happy to do so, but I guess that  it's just a matter of waiting for current beta to become stable for us end-users.

Thanks again.

**Comment by kisak-valve** [comment]
Closing per "Fixed an issue where the Steam Client wouldn’t automatically update or download Proton before launching games through Steam Play" in the [2019-04-17](https://store.steampowered.com/news/50095/) Steam client update.
