### ISSUE TITLE
Unable to open friends list

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/steam-for-linux#6198]
#### Your system information

* Steam client version (build number or date): feb 18
* Distribution (e.g. Ubuntu):  Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

Hi,
I suddenly find my self unable to open the friends list, in the terminal it just says ExecuteSteamURL: "steam://open/friends"

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, does `/tmp/dumps/<username>_stdout.txt` have any hints?

Please retest with Steam's beta client.

**Comment by Turmfalke2** [comment]
_stdout.txt appears to be identical with the terminal output. Since writing this report the friends list has opened at some point. However most friends are missing their names:

![friends_list](https://user-images.githubusercontent.com/5174562/55672949-adc72800-58a1-11e9-9343-b5a5cc8ad4a9.png)


It appears the client is also running some sort of debug mode:

```
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call WebChat.SetNumChatsWithUnreadPriorityMessages with 1 arguments
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.SetNumChatsWithUnreadPriorityMessages with 1 arguments
JS method call WebChat.SetActiveClanChatIDs with 1 arguments

```

Going to test with the beta client now.

**Comment by Turmfalke2** [comment]
After restarting with the beta client the friends list works again.

**Comment by Chiitoo** [comment]
I'm guessing this was a connection issue of sorts.

I also lost connection to the friends list, and the main Steam window also said 'no connection'.  Restarting Steam would lead into unable to connect to the Steam service (and did not even get the option to start in offline mode).

It seems to have been resolved for now at least (non-beta client still).
