### ISSUE TITLE
Artifact client is unexpectedly closed.

### ISSUE THREAD

**Issue by Oliver-1xok** [ValveSoftware/steam-for-linux#6199]
#### Your system information
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.0-17-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 415.27
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x13c2
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 6.30" x 3.54" (7.20" diag)
                                            16.0cm x 9.0cm (18.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC1150

Memory:
    RAM:  15979 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  406050 Mb
    VR Headset: None detected

Recent Failure Reports:

* Steam client version (build number or date): Apr 4 2019, at 03:18:17
* Distribution (e.g. Ubuntu): Xubuntu 18.4.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
During a tournament the client was suddenly closed. Some other participants also reported that their clients terminated.  

Kernel message buffer:
`traps: dcg[16097] general protection ip:7f90a29251a7 sp:7ffddf32a130 error:0 in libclient.so[7f90a1cf8000+228a000]`

Core dump:
[crash_20190406234807_1.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/3051061/crash_20190406234807_1.dmp.gz)

#### Steps for reproducing this issue:
I don't know how to reproduce it. It happened to me for the first time.

**Comment by kisak-valve** [comment]
Hello @Oliver-1xok, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
