### ISSUE TITLE
World of Tanks Blitz MMO

### ISSUE THREAD

**Issue by liss21** [ValveSoftware/steam-for-linux#6202]
Steam 1554351903 
Kubuntu 18.04.2
Opted into Steam client beta
System is up to date.
Proton 4.2
Lenovo G570, i3 2370m, HD3000. (Discrete card is dead)

Hi. WoT Blitz won`t start after update to 5.9 patch. The developers report that the game was transferred to DX11. At 5.8 patch i was played perfectly. At now game report "Rendering error: FailedToinitialize".

I tried Proton from 3 up to 4.2 version.
In Windows game run perfect. That means DX11 is supported by HD3000.

Version of drivers:
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00



```

**Comment by TehFreek** [comment]
I'm not sure how this is an issue with the Steam client for Linux rather than with Proton itself, but HD Graphics 3000 technically only supports up to DirectX 10.1.

**Comment by liss21** [comment]
> I'm not sure how this is an issue with the Steam client for Linux rather than with Proton itself, but HD Graphics 3000 technically only supports up to DirectX 10.1.

But the game is going great in Windows. Besides, as I wrote above - on March 21 I played normally, and on March 22 at night the game was updated to version 5.9, and stopped to start, complaining about Render Error.

**Comment by Newbie13XD** [comment]
I think this should be reported in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues).

**Comment by kisak-valve** [comment]
Hello @liss21, issues with games run with Proton are being tracked in the Proton issue tracker, and we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1293#issuecomment-480816876.
