### ISSUE TITLE
Steam Backup is slow

### ISSUE THREAD

**Issue by mmeyran** [ValveSoftware/steam-for-linux#6204]
#### Your system information

* Steam client version (build number or date): latest (as of 2019-04-08)
* Distribution (e.g. Ubuntu): Ubuntu 18.04.2
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Packing or unpacking a Steam backup makes use of a single CPU thread. Now that the base gaming CPU is 4-core, it's a waste.

#### Steps for reproducing this issue:

1. Start creating a Steam backup
2. Open a system monitor to check what CPU is in use
3. Weep silently while your 8-core CPU has a single thread maxed out and 7 other threads idling while Steam Backup is telling you it will take an hour to backup your 80 Gb game.

**Comment by kisak-valve** [comment]
Hello @mmeyran, this issue is already being tracked at #6134. Closing in favor of the existing feature request.
