### ISSUE TITLE
Latest Steam beta Update prevents steam-native-runtime from going online

### ISSUE THREAD

**Issue by breadland** [ValveSoftware/steam-for-linux#6205]
#### Your system information

* Steam client version (build number or date): Apr 4 2019, at 03:18:17
* Steam API: v018
* Steam package versions: 1554351903
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After downloading the latest Steam Beta Update, when running steam-native-runtime, I'm unable to access friends list, etc. My name is in gray, and clicking the Friends & Chat button does nothing. Store, Community, and Profile tabs do not load either. I can access my library, but I can't see any online friends, and they can't see me.

If I use the Steam(Runtime) instead of Steam(Native), I'm able to access all online features.

If I opt out of the beta, Steam(Native) does not suffer from this issue and can access online features just fine.

#### Steps for reproducing this issue:

1. Opt in to Steam Beta Update
2. Install latest Beta Update.
3. Run steam-native-runtime

**Comment by kisak-valve** [comment]
Hello @breadland, this issue was previously assessed at #6156. Closing as a duplicate.

Arch bug report: https://bugs.archlinux.org/index.php?do=details&task_id=62095
