### ISSUE TITLE
Controller problems in Big Picture mode

### ISSUE THREAD

**Issue by jkcoxson** [ValveSoftware/steam-for-linux#6206]
#### Your system information

* Steam client version: The newest one as of April 9th, 2019
* Distribution: Linux Mint 19.1 (But reproduced on Ubuntu and SteamOS)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have been trying to use my PowerA Pro Wired Controller with Steam Big Picture mode to steam from my laptop to my desktop. My laptop, which runs Ubuntu, can't see the controller in the settings. I borrowed a Nintendo-made wireless Switch Pro Controller from a friend, and it worked fine. Steam recognized it instantly, but just not my PowerA one. I have tried multiple laptops running Linux and different Linux distros. Steam just won't recognize it, while other programs on my computer will. Htmlgamepad.com worked fine. I have tried Ubuntu and SteamOS, but they don't recognize it either. Windows works fine, but I don't want to use Windows because of hardware incompatibility with other parts of my laptop. I need Big Picture mode because I am streaming to my gaming rig.

#### Steps for reproducing this issue:

1. Plug in controller
2. Open Steam and open Big Picture
3. Open settings and controller settings

**Comment by kisak-valve** [comment]
Hello @jkcoxson, this reads like the PowerA controller issue being tracked at #5353. Closing in favor of the existing issue report.
