### ISSUE TITLE
[LINUX] Finding out linux games count is impossible with steam play for all titles on

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/steam-for-linux#6209]
#### Your system information

* Steam client version : Feb 18 2019
* Distribution : Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue : 

you see this?
![Screenshot from 2019-04-11 23-17-04](https://user-images.githubusercontent.com/5132359/55993747-2407c800-5cb0-11e9-85b3-53532a91a808.png)

this is utterly obnoxious.

I can never remember how many linux native games I own (and that number frequently changes)

and I need to turn off "steam play for all games", allow steam to restart. discover the linux native steam games count, then re-enable it and restart again.

if you're going to do this at least have a way to count non-native.

this way you have a notion of the linux-native games you own.

emulated is **not** the same and **never** will be. 

porting games needs to be encouraged and rewarded not obscured.

and it's not only the count, that sort view is also really useful.

**Comment by kisak-valve** [comment]
Hello @tatsujb, this issue is already being tracked at #5639. Closing as a duplicate.
