### ISSUE TITLE
DOS titles for Steamplay

### ISSUE THREAD

**Issue by dolour** [ValveSoftware/steam-for-linux#6216]
Is there an issue with DOSBox, or why arent ancient titles like the Space Quest collection,
any of that Star Wars stuff etc, supported out of the box?

**Comment by kisak-valve** [comment]
Hello @dolour, in general, issues with games that are using Proton (Steamplay 2.0) are being tracked in the [Proton](https://github.com/ValveSoftware/Proton) issue tracker. If you have a game-specific issue, please report it there.

Also, Dosbox in general is being discussed at https://github.com/ValveSoftware/Proton/issues/1566.
