### ISSUE TITLE
Steam might crash on unreliable Wifi networks

### ISSUE THREAD

**Issue by MateusRodCosta** [ValveSoftware/steam-for-linux#6219]
#### Your system information

* Steam client version (build number or date): April 16 2019, 21:10:43
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I should be able to play as long as I can, however Steam crashes and takes the game down with it.

Two different crashes happenned, on the first one I got these on my logs:

```
abr 16 20:45:49 delart kernel: CIPCServer::Thr[30930]: segfault at 160 ip 0000000000000160 sp 00000000ebffed5c error 14 in steam[56599000+3f8000]
abr 16 20:45:49 delart kernel: Code: Bad RIP value.
abr 16 20:45:49 delart steam.desktop[5493]: No minidump written, nothing to upload.
abr 16 20:45:49 delart kernel: steam[30911]: segfault at 465f633c ip 00000000f0fad116 sp 00000000ffdf8870 error 4 in libdbus-1.so.3.5.8[f0f82000+47000]
abr 16 20:45:49 delart kernel: Code: 8d 74 26 00 8b 44 24 44 0f b6 54 05 00 83 c0 01 89 44 24 44 88 17 eb bc 8d 74 26 00 8b 44 24 44 83 c0 03 83 e0 fc 89 44 24 44 <8b> 54 05 00 83 7c 24 50 6c 89 17 74 06 8b 17 >
abr 16 20:45:49 delart steam.desktop[5493]: No minidump written, nothing to upload.
abr 16 20:45:49 delart kernel: CIPCServer::Thr[30930]: segfault at 160 ip 0000000000000160 sp 00000000ebffed5c error 14 in steam[56599000+3f8000]
abr 16 20:45:49 delart kernel: Code: Bad RIP value.
abr 16 20:45:49 delart kernel: audit: type=1701 audit(1555458349.417:527): auid=1000 uid=1000 gid=1000 ses=2 pid=30911 comm="CIPCServer::Thr" exe="/home/mateusrc/.local/share/Steam/ubuntu12_32/steam" sig=11 res>
abr 16 20:45:49 delart audit[30911]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 pid=30911 comm="CIPCServer::Thr" exe="/home/mateusrc/.local/share/Steam/ubuntu12_32/steam" sig=11 res=1
abr 16 20:45:49 delart systemd[1]: Started Process Core Dump (PID 407/UID 0).
abr 16 20:45:49 delart kernel: audit: type=1130 audit(1555458349.624:528): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-407-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? >
abr 16 20:45:49 delart audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-407-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succes>
abr 16 20:45:50 delart crash_20190416203111_1.dmp[402]: Finished uploading minidump (out-of-process): success = no
abr 16 20:45:50 delart steam.desktop[5493]: crash_20190416203111_1.dmp[402]: Finished uploading minidump (out-of-process): success = no
abr 16 20:45:50 delart steam.desktop[5493]: crash_20190416203111_1.dmp[402]: error: Couldn't resolve host name
abr 16 20:45:50 delart steam.desktop[5493]: crash_20190416203111_1.dmp[402]: file ''/tmp/dumps/crash_20190416203111_1.dmp'', upload no: ''Couldn't resolve host name''
abr 16 20:45:50 delart crash_20190416203111_1.dmp[402]: error: Couldn't resolve host name
abr 16 20:45:50 delart crash_20190416203111_1.dmp[402]: file ''/tmp/dumps/crash_20190416203111_1.dmp'', upload no: ''Couldn't resolve host name''
```
With this on the coredump:
```
abr 16 20:46:17 delart systemd-coredump[408]: Process 30911 (steam) of user 1000 dumped core.
                                              
                                              Stack trace of thread 30930:
                                              #0  0x0000000000000160 n/a (n/a)
```

```
abr 16 22:53:43 delart steam.desktop[5493]: (steam:4317): GLib-GObject-WARNING **: 22:53:43.247: g_object_notify: object class 'NMAccessPoint' has no property named '\xc8\u0006x\xeb'
abr 16 22:53:43 delart steam.desktop[5493]: free(): invalid pointer
abr 16 22:53:45 delart steam.desktop[5493]: crash_20190416211404_1.dmp[10468]: Uploading dump (out-of-process)
abr 16 22:53:45 delart steam.desktop[5493]: /tmp/dumps/crash_20190416211404_1.dmp
abr 16 22:53:45 delart kernel: audit: type=1701 audit(1555466025.460:817): auid=1000 uid=1000 gid=1000 ses=2 pid=4317 comm="steam" exe="/home/mateusrc/.local/share/Steam/ubuntu12_32/steam" sig=6 res=1
abr 16 22:53:45 delart audit[4317]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 pid=4317 comm="steam" exe="/home/mateusrc/.local/share/Steam/ubuntu12_32/steam" sig=6 res=1
abr 16 22:53:45 delart crash_20190416211404_1.dmp[10468]: Uploading dump (out-of-process)
                                                          /tmp/dumps/crash_20190416211404_1.dmp
abr 16 22:53:48 delart systemd[1]: Started Process Core Dump (PID 10469/UID 0).
abr 16 22:53:48 delart kernel: audit: type=1130 audit(1555466028.272:818): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3-10469-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=>
abr 16 22:53:48 delart audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3-10469-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succ>
abr 16 22:53:51 delart crash_20190416211404_1.dmp[10468]: Finished uploading minidump (out-of-process): success = yes
abr 16 22:53:51 delart steam.desktop[5493]: crash_20190416211404_1.dmp[10468]: Finished uploading minidump (out-of-process): success = yes
abr 16 22:53:51 delart steam.desktop[5493]: crash_20190416211404_1.dmp[10468]: response: CrashID=bp-bbbc0f4c-27ef-4ad7-9946-a291f2190416
abr 16 22:53:51 delart steam.desktop[5493]: crash_20190416211404_1.dmp[10468]: file ''/tmp/dumps/crash_20190416211404_1.dmp'', upload yes: ''CrashID=bp-bbbc0f4c-27ef-4ad7-9946-a291f2190416''
abr 16 22:53:51 delart crash_20190416211404_1.dmp[10468]: response: CrashID=bp-bbbc0f4c-27ef-4ad7-9946-a291f2190416
abr 16 22:53:51 delart crash_20190416211404_1.dmp[10468]: file ''/tmp/dumps/crash_20190416211404_1.dmp'', upload yes: ''CrashID=bp-bbbc0f4c-27ef-4ad7-9946-a291f2190416''
abr 16 22:54:06 delart steam.desktop[5493]: /home/mateusrc/.local/share/Steam/steam.sh: line 906:  4317 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
abr 16 22:54:06 delart gnome-shell[5493]: JS WARNING: [resource:///org/gnome/gjs/modules/signals.js 142]: Too many arguments to method Clutter.Actor.destroy: expected 0, got 1
abr 16 22:54:07 delart steam.desktop[5493]: [0416/225407.060809:ERROR:local_storage_context_mojo.cc(706)] Lost connection to database
abr 16 22:54:10 delart steam.desktop[5493]: chrome_ipc_client.cpp (763) : Assertion Failed: Failed to connect to master html process, created shared memory (spawn time 1097.05)
abr 16 22:54:11 delart steam.desktop[5493]: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
abr 16 22:54:12 delart steam.desktop[5493]: crash_20190416225410_6.dmp[10532]: Uploading dump (out-of-process)
abr 16 22:54:12 delart steam.desktop[5493]: /tmp/dumps/crash_20190416225410_6.dmp
abr 16 22:54:12 delart crash_20190416225410_6.dmp[10532]: Uploading dump (out-of-process)
                                                          /tmp/dumps/crash_20190416225410_6.dmp
abr 16 22:54:14 delart crash_20190416225410_6.dmp[10532]: Finished uploading minidump (out-of-process): success = yes
abr 16 22:54:14 delart steam.desktop[5493]: crash_20190416225410_6.dmp[10532]: Finished uploading minidump (out-of-process): success = yes
abr 16 22:54:14 delart steam.desktop[5493]: crash_20190416225410_6.dmp[10532]: response: Discarded=1
abr 16 22:54:14 delart steam.desktop[5493]: crash_20190416225410_6.dmp[10532]: file ''/tmp/dumps/crash_20190416225410_6.dmp'', upload yes: ''Discarded=1''
abr 16 22:54:14 delart crash_20190416225410_6.dmp[10532]: response: Discarded=1
abr 16 22:54:14 delart crash_20190416225410_6.dmp[10532]: file ''/tmp/dumps/crash_20190416225410_6.dmp'', upload yes: ''Discarded=1''
abr 16 22:54:17 delart systemd-coredump[10471]: Process 4317 (steam) of user 1000 dumped core.
                                                
                                                Stack trace of thread 4317:
                                                #0  0x00000000f7f59929 __kernel_vsyscall (linux-gate.so.1)
                                                #1  0x00000000f7968082 raise (libc.so.6)
                                                #2  0x00000000f79522b6 abort (libc.so.6)
                                                #3  0x00000000f79aa37c __libc_message (libc.so.6)
                                                #4  0x00000000f79b117d malloc_printerr (libc.so.6)
                                                #5  0x00000000f79b27fb _int_free (libc.so.6)
                                                #6  0x00000000efb50f38 n/a (/home/mateusrc/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libnm-glib.so.4.3.0)
```

On the two occasions one of the things that might be useful to know is how was the Wifi network I was in.
I was on a college wireless network. So, there were several access points sharing the exact same SSID (each different Wifi network with its own MAC address) along with a portal wwhich required login with my student credentials. On the specific spot I got to be during class the reception was pretty bad and Steam managed to crash. That though only applied to the first crash.

On the second crash I got to stay on a different place with access to one of those college Wifi networks, and then got on the move, at some point between them the second crash occurred.
 
Both crashes made me lose significant progress.

The first crash seems to be related to dbus somehow, so it might be useful to know I'm running dbus-broker 20-1

#### Steps for reproducing this issue:

1. Be on a unrealible Wifi network (such as being on a place with bad reception)
2. Play a game
3. Play for as long as you are able to

**Comment by yswtrue** [comment]
same error.

`JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.SetNumChatsWithUnreadPriorityMessages with 1 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
Installing breakpad exception handler for appid(steam)/version(1560549607)
No minidump written, nothing to upload.
/home/ysw/.local/share/Steam/steam.sh：行 712:  1349 段错误               （核心已转储）$STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[0616/014928.708643:ERROR:local_storage_context_mojo.cc(706)] Lost connection to database
`

**Comment by kisak-valve** [comment]
Closing pending feedback.
