### ISSUE TITLE
game already running bug

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/steam-for-linux#6220]
#### Your system information

* Steam client version (build number or date): Feb 18 2019
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

games that are not even installed or are installed but attempting to run are provoking the "game already running" error message.

both upon restarting/exiting steam (steam prevented from closing because "game must be shutdown first")
and when starting a game when steam was not already running.

when steam is in this state nothing can  be done. no reboot, no login in and out no Beta vs Vanilla, nothing except complete purge of all steam files and libraries from the entire operating system fixes it.

that's a bit extreme just to be able to run one game.

I'd like a more manageable solution.

Why am I getting "game running" error message for a game that has no files on my OS? that is crazy!

#### Steps for reproducing this issue:

no idea what causes it. perhaps rapid un-installation and re-installation.

happens with 9420 in particular.

**Comment by kisak-valve** [comment]
Hello @tatsujb, it sounds like there was a leftover running process for the game you were testing, and it was able to tell Steam it was running when Steam was forced to restart. It may be easier to find what was running with a process manager like htop in tree mode (run it and hit `t`).

**Comment by tatsujb** [comment]
@kisak-valve so checking if a process existed with htop is something I already did. 

btw a process cannot be open if the binary is not present on said Operating System's hard drive.

**Comment by kisak-valve** [comment]
Hello @tatsujb, are you still experiencing this issue on an up to date system?

**Comment by tatsujb** [comment]
Not quite

it still occurs on occasion, but in a different form 

`Linux tsu 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

updated yesterday (and rebooted). I mainly only get this issue with Rocket league. I'd say it's one out of every 5 runs
sometimes it's just really really bad at closing all those extra processes that are run and then those stick around forever and convince steam the game is running.

Opening task manager, killing all the processes that come up when you search "rocket", or restarting, solves the issue.

**Comment by kisak-valve** [comment]
Thanks for the feedback. 

If this issue is has changed to individual games failing to exit cleanly with Proton, then it would be best for the Proton devs to take a look on a per-game basis. Please add a note with your experience to https://github.com/ValveSoftware/Proton/issues/3521.

Closing per the last comment.
