### ISSUE TITLE
Remove word "beta" from landing page.

### ISSUE THREAD

**Issue by HonkingGoose** [ValveSoftware/steam-for-linux#6223]
#### Your system information

* Steam client version (build number or date): not applicabble
* Distribution (e.g. Ubuntu): not applicable
* Opted into Steam client beta?: [Yes/No] not applicabble
* Have you checked for system updates?: [Yes/No] not applicable

#### Please describe your issue in as much detail as possible:
On the main page it says that the Steam for Linux client is in beta. The client is surely out of beta by now.

#### Steps for reproducing this issue:

1. Go to https://github.com/ValveSoftware/steam-for-linux
2. Note that it says: "Issue tracking for the Steam for Linux **beta** client"

#### Suggested resolution:
Remove **beta** from line of text.

**Comment by TehFreek** [comment]
Do you believe that this issue tracker should be for the release version of the client instead?

**Comment by HonkingGoose** [comment]
Ahhhh.... :bulb: 

I was thinking that "Steam for Linux" is out of beta for a long time. 

But the issue tracker is for the beta version only...

I'll close this issue... :smile:
