### ISSUE TITLE
Inaccessible Steam friends window as well as store, community and profile pages

### ISSUE THREAD

**Issue by fate-on-linux** [ValveSoftware/steam-for-linux#6226]
#### Your system information

* Steam client version (build number or date): Apr 16 2019, at 21:10:43, Steam package versions 1555457005
* Distribution (e.g. Ubuntu): Manjaro, there exist a package manjaro-steam
* Opted into Steam client beta?: No, i tried beta channel but there were no further update.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Logging into the Steam account
2. Trying to open the friends window, opening the store page, community or profile
3. In case of the steam friends window it wont open at all, the other aforementioned display a black page with a loading icon on the right side.

The issue persists and wont change even after reinstall / restarting Steam or the PC.
Online play seems to function other than everything connected to the friends part as i seems to be displayed as offline.

**Comment by kisak-valve** [comment]
Hello @fate-on-linux, this issue was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/6173#issuecomment-477783338. Please read the existing issue report for the workaround or remove the `multilib/steam-native` package.
