### ISSUE TITLE
No voice settings in Steam

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#6227]
#### Your system information
https://gist.github.com/amitavmohanty01/f02edfcb0914879e1cc0249d2e4d96ec

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In the settings menu, there is no voice section. I want to check the setting for my default microphone but there is no setting to do it.

**Comment by TehFreek** [comment]
The voice settings have moved to the Friends & Chat pane settings.

**Comment by amitavmohanty01** [comment]
Thanks. I found the settings. Strangely, my microphone is working in Steam for the voice chat but not in Dota 2 game.

**Comment by kisak-valve** [comment]
Closing per the last comment.
