### ISSUE TITLE
[BUG] A year later and steam still has DNS issues.

### ISSUE THREAD

**Issue by Plaer1** [ValveSoftware/steam-for-linux#6229]
#### Your system information

* I have the latest beta of the steam client.
* Distribution (e.g. Ubuntu):  I"m currently on KDE neon but this issue has persisted **ACROSS DISTROS**
* Opted into Steam client beta?: [Yes/No] Yes, and no. they both **LITERALLY RUIN** my internet connection
* Have you checked for system updates?: [Yes/No] **Yes.**

#### Please describe your issue in as much detail as possible:
When steam is open, it's like I have dail-up internet.

#### Steps for reproducing this issue:

1. Open steam.
2. Congratulations your internet connection is RUINED.
3. 
I have 100/10 up down from my provider, and this is what steam does to my connection on linux:
![FUCKING WHAT](https://user-images.githubusercontent.com/3485414/56440571-cbd85380-62b7-11e9-8d89-42d99d4cc27a.png)

**Comment by Plaer1** [comment]
By the way, it's really awesome to have to go to a third-party website, and thru a steam warning link just to submit a bug. VERY PROFESSIONAL GUYS.  **what about people without github experience?**
Just some food for thought.

**Comment by kisak-valve** [comment]
Hello @Plaer1, this issue is already being tracked at #5907. Closing as a duplicate.
