### ISSUE TITLE
libvulkan segfault

### ISSUE THREAD

**Issue by Galaxy0419** [ValveSoftware/steam-for-linux#6230]
#### Your system information

* Steam client version (build number or date): steam 1.0.0.59-2
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* CPU/GPU: i7-8565U/UHD620
* Driver: lib32-mesa 19.0.2-1

#### Steps for reproducing this issue:

1. Open steam-runtime

#### Detailed Logs
dmesg:
[ 6278.657402] vulkandriverque[31661]: segfault at 0 ip 00007f176ddce1d0 sp 00007ffca4a21de0 error 4 in libvulkan.so.1.1.101[7f176ddb6000+2f000]
[ 6278.657414] Code: 44 24 18 48 8b 44 24 10 8b 40 08 89 44 24 20 83 e8 01 48 69 c0 98 2e 00 00 48 89 44 24 28 0f 1f 40 00 48 8b 44 24 18 45 89 ee <4a> 8b 2c f0 8b 44 24 20 85 c0 0f 84 a0 
00 00 00 48 8b 44 24 10 48
#### Related packages
vulkan-icd-loader 1.1.101-1

**Comment by kisak-valve** [comment]
Hello @Galaxy0419, are you encountering a functional issue to go along with this? Also, do you have the  `vulkan-intel` and `lib32-vulkan-intel` packages installed?

**Comment by Galaxy0419** [comment]
Installing gpu specific vulkan driver and 32bit version of icd-loader solve the issue.  
Further reading: [https://wiki.archlinux.org/index.php/Vulkan#Installation](https://wiki.archlinux.org/index.php/Vulkan#Installation)
