### ISSUE TITLE
Steam is ~~trying to redownload~~ UNINSTALLS certain games since proton-4.2.3

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#6236]
This happens on ubuntu_18.04 and manjaro too.
Sometimes, when I validate the game files the issue gets resolved for certain games.

**Comment by trialism** [comment]
Correction: steam DELETED those games completely!

**Comment by kisak-valve** [comment]
Hello @trialism, can you check if this is a duplicate of #5745.

**Comment by trialism** [comment]
@kisak-valve I had proton enabled globally.

**Comment by A-UNDERSCORE-D** [comment]
Had this (or the other comment I made in #6543 ) happen to me today, this is the second time its occurred within a few months.

**Comment by kisak-valve** [comment]
Hello @A-UNDERSCORE-D, have you seen this issue since https://github.com/ValveSoftware/steam-for-linux/issues/6543#issuecomment-795367480?

**Comment by A-UNDERSCORE-D** [comment]
I have not but Ive also reinstalled my entire system since then so it may be that whatever circumstances are required no longer exist for me

**Comment by kisak-valve** [comment]
Thanks for the feedback @A-UNDERSCORE-D. Because the reporting user has turned into a ghost, I'm closing this issue report.
