### ISSUE TITLE
Extremely low download speed games on Linux

### ISSUE THREAD

**Issue by Krypt0nC0R3** [ValveSoftware/steam-for-linux#6239]
Steam 04.24.19 
Debian 9 x64 Gnome
Opted into Steam client beta? No
Have you checked for system updates? Yes

Extremely low download speed games on Linux. The speed is normal (http://speedtest.net/). On Windows, the problem is not observed.
I tried to change the content region - the speed just drops.
Specified DNS from the provider - without changes.
![Speedtest](https://user-images.githubusercontent.com/46594859/56605431-57dada00-662e-11e9-97b6-ea787d00ef7c.png)
![Region](https://user-images.githubusercontent.com/46594859/56605432-58737080-662e-11e9-822f-cb580917d5e2.png)
![System](https://user-images.githubusercontent.com/46594859/56605433-58737080-662e-11e9-9575-6f2ce32346a4.png)
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3109001/content_log.txt)

**Comment by kisak-valve** [comment]
Hello @Krypt0nC0R3, this issue is already being tracked at #5907. Closing as a duplicate.
