### ISSUE TITLE
Steamclient shuts down when friendlist window is closed

### ISSUE THREAD

**Issue by XXXBold** [ValveSoftware/steam-for-linux#6246]
#### Your system information: https://gist.github.com/XXXBold/007546b9d2e8020dec84795f09e63a30

* Steam client version (build number or date): Build Apr 16 2019
* Distribution (e.g. Ubuntu): Linux Mint 19.1 (x64) Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue description
If the Steamclient Mainwindow is minimized and there is one or more Window from Steam opened (e.g. Friendlist, Chat, ...) and I click on "x" to close this on the preview window from the taskbar, the whole steam client is shut down completely, not just the window closed. (Check added Screenshot)

Expected behaviour:
Only the Friendlist/chat window should be closed, not the Steamclient itself. And even If i want

#### Steps for reproducing this issue (reproduces 100% of the time for me):

1. Start Steam client
2. Open Friendlist
3. Minimize the Steam main window
4. Move mouse over Steam icon in the taskbar
5. If preview appears, click on the "x" of the "Friendlist" window.
6. Steam shuts down completely

Tell me if you need more infos, or I can help in another way :)

![steamclient](https://user-images.githubusercontent.com/30773753/56830756-b84c6000-6856-11e9-96c9-8501348f6cb2.png)

**Comment by kisak-valve** [comment]
Hello @XXXBold, this issue is already being tracked at #3202. Closing as a duplicate.
