### ISSUE TITLE
Leaving steam open causes X11 to leak memory

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [ValveSoftware/steam-for-linux#6247]
#### Your system information

* Steam client version (build number or date): 
Steam beta build from April 19 2019
* Distribution (e.g. Ubuntu): 
Ubuntu 18.04.2
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Leaving steam open for some time causes X11's process (called Xorg on my system) to use use more and more memory. At time of discovery it was holding over 1.5GB of memory, and once steam was closed it dropped to just over 50MB.

#### Steps for reproducing this issue:

1. Start Steam
2. Wait for some time, possibly hours (noticed after a day or two for me)
3. Check X11's memory usage

**Comment by kisak-valve** [comment]
Whoops, I made a bad request to open this issue at https://github.com/ValveSoftware/steam-for-linux/issues/5279#issuecomment-487206841. You've described the issue being tracked at #5764, closing in favor of that issue report.
