### ISSUE TITLE
How to get steam to work with NVIDIA 396.54 driver on Linux Mint 19.1

### ISSUE THREAD

**Issue by DarthMalloc** [ValveSoftware/steam-for-linux#6251]
#### Your system information

* Steam client version : 1.0.0.61
* Distribution Linux Mint 19.1 (Ubuntu 18.04 Bionic): 
* Opted into Steam client beta?: No
* Have you checked for system updates?: No (current error prevents it)
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
[2epc.txt](https://github.com/ValveSoftware/steam-for-linux/files/3124498/2epc.txt)

My system information is in the attached file, and the error is shown in the attached picture.
![Screenshot from 2019-04-27 17-41-28](https://user-images.githubusercontent.com/40067998/56857008-8a8a1880-6935-11e9-8fa6-2ea9b1c928d7.png) The error that I am experiencing is that after installing the NVIDIA 396.54 driver on Linux Mint 19.1, I am unable to run steam. If there is an error in the way that I installed steam or the driver, I would greatly appreciate if someone would guide me in how to install the driver and the client so that they can function properly together.

#### Steps for reproducing this issue:
Try the following on Linux Mint 19.1/Ubuntu 18.04 Bionic:
1. sudo apt-get purge nvidia*
2. sudo apt-get install nvidia-driver-396
3. restart
4. Install latest Steam client
5. Open terminal and run steam

**Comment by sizeofbool** [comment]
Show output from this command:
```$ dpkg --print-foreign-architectures```
If it doesn't output "i386" you have to add this architecture to your system, so driver binaries and other dependencies could be installed for "i386" architecture.
```$ sudo dpkg --add-architecture i386```

On the side note, nvidia driver 396.54 is pretty outdated by now and won't allow you to fully utilize all features of Steam client, such as Proton with DXVK.
Just by a quick glance, it looks like Linux Mint doesn't have newer version available in its repos, but you can install 410 or 418 versions from Ubuntu repos.
I don't use ubuntu or mint, only Debian, so I don't know if this suggestion will break your system now or some time later.

**Comment by kisak-valve** [comment]
Hello @DarthMalloc, nvidia's userspace driver is split into separate 32 bit and 64 bit packages on Ubuntu 18.04 and derivatives. You need to install `libnvidia-gl-<series>:i386` for 32 bit opengl support from nvidia.

For your system, you can check if it's installed with something like `apt policy libnvidia-gl-396:i386` and install it with `sudo apt install libnvidia-gl-396:i386`

**Comment by DarthMalloc** [comment]
Thanks for getting back to me about that. I tried installing the nvidia-430 drive (64 bit) but that didn't allow me to run Steam. I am afraid to install any i386 packages because the last time I did, it made my sound system stop working. Do you know how to install libnvidia-gl-430:i386 while preventing my sound system from failing?

**Comment by kisak-valve** [comment]
Closing because this is a system config issue.

Steam requires a working 32 bit OpenGL driver. Worse case scenario, make a list of packages you're installing so you can use apt purge to remove the newly installed package(s). In general, nvidia's video drivers should not affect audio.

**Comment by Meru** [comment]
@sizeofbool from what you wrote above I understand that that if my gpu is not listed as supported in driver version above 390.XX, there's no reason for me to even try proton? Or I should use newer driver anyway and it will work?

**Comment by sizeofbool** [comment]
@Meru You can use Proton with legacy drivers, but without DXVK.
Nvidia drivers version above 415.XX [is a requirement of DXVK](https://github.com/doitsujin/dxvk/wiki/Driver-support) .
I had success with previous versions of nvidia drivers, but most of the time it leads to issues and\or graphical artefacts, IF you will use DXVK with Wine\Proton.

If your graphics card is old and you are sure that driver support for it was dropped in up-to-date versions of nvidia drivers, then you have to use latest driver available where your graphics card is supported and disable DXVK in Proton to use OpenGL wrapper only.

**Comment by burkecp** [comment]
I can't seem to find this package for the Nvidia 430 driver. I have i386 added as a foreign architecture and other relevant 32-bit libraries. Still, however, I can't run steam because I can't find the download for libnvidia-gl-430 or libnvidia-gl-430:i386. Any direction?
