### ISSUE TITLE
In-Home streaming on Raspberry Pi is extremely quiet and does not mute Host PC

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/steam-for-linux#6252]
#### Your system information

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2
* Distribution (e.g. Ubuntu): Ubuntu Budgie 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Games streamed through the Steam Link app for Raspbian are extremely quiet and do not mute my host PC. I verified the volume of my PC and although it's at 40%, rising it to 100% rises the volume of the stream about 10%. I have to rise the volume of my TV's soundbar to 40 (out of a max of 50) for it to be comfortable. Other content played on my same TV sounds pretty loud at about 28. Soundbar is connected through TOSLINK cable. 

#### Steps for reproducing this issue:

1. Start Steam on host PC
2. Start Steam Link on Raspberry Pi (connected over HDMI)
3. Games are almost inaudible.

**Comment by lavadrop** [comment]
I'm sorry I had a significant error when I wrote the title of the bug.

**Comment by kisak-valve** [comment]
Hello @lavadrop, are you still experiencing this issue on an up to date system?

**Comment by lavadrop** [comment]
Hey @kisak-valve !
The quietness was fixed a long time ago, but the host still plays back audio instead of muting it.

**Comment by kisak-valve** [comment]
Thanks for the feedback. That part of your issue is still being tracked at #6512. Closing in favor of the other issue report.
