### ISSUE TITLE
Uninstalling a SteamPlay/Proton game removes its `compatdata`, which also removes savegames+config, etc

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#6255]
#### Your system information

* Steam client version (build number or date): Apr 16, 2019 | 1555457005
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Uninstalling a SteamPlay/Proton title on Linux will result in the associated `compatdata` directory also getting removed.  The problem is that doing so is highly likely (in fact, almost assuredly) going to remove any savegames and game configs which were stored there, since those are typically stored by the game under `c:\users\steamuser\My Documents` somewhere.  For instance, I just uninstalled TES4:Oblivion to make room for another game, and fortunately I've got a daily backup in place, so I was able to go back into `$STEAMROOT/SteamApps/compatdata/22330` to archive my saves elsewhere, for when I inevitably get back to the game eventually.

#### Steps for reproducing this issue:

1. Install a SteamPlay/Proton game
2. Save game / configure settings /etc
3. Uninstall game

One potential workaround could be to maybe symlink the `steamuser` dir elsewhere, or otherwise exclude that dir from the auto-purge.  Or potentially just leaving the `compatdata` dir alone in general, though that could add up to a lot of wasted space if you've got a lot of SteamPlay titles...

**Comment by kisak-valve** [comment]
Hello @apocalyptech, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/428. Closing in favor of the existing issue report.

**Comment by apocalyptech** [comment]
Bah, sorry.  I swear I'd searched there first, but clearly missed it.  Thx!
