### ISSUE TITLE
nVidia driver issues after latest update

### ISSUE THREAD

**Issue by RenaKunisaki** [ValveSoftware/steam-for-linux#6256]
#### Your system information

* Steam client version (build number or date): Apr 29 2019, at 20:58:26
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
After updating Steam client last night I'm experiencing faults in nVidia GPU driver causing entire system to hang for a few seconds at a time, every 10 seconds or so, until Steam is closed. The GPU driver hasn't been changed and this issue didn't happen before the update.

#### Steps for reproducing this issue:

1. Launch Cities: Skylines
2. Close the game
3. While it's closing, switch to a different workspace with MonoDevelop open

Result: system begins stuttering until Steam is closed (even after the game and MonoDevelop are closed), with message repeatedly written to system log:
```
May 02 16:08:39 guilmon kernel: NVRM: Xid (PCI:0000:01:00): 31, Ch 00000010, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_4 faulted @ 0x1_1144a000. Fault is of type FAULT_PDE ACCESS_TYPE_READ
```

(last two numbers vary)

Chances are this is some nVidia driver bug that Steam is now running into, though it's strange since I have GPU accelerated web view turned off.

**Comment by RenaKunisaki** [comment]
[System Information](https://github.com/ValveSoftware/steam-for-linux/files/3139821/sysinfo.txt)

**Comment by rpachon** [comment]
Hello,
Same random freeze(1 to 7 sec) when playing csgo from my side (No freeze and no error msg with Borderlands 2 full graphics) and as you, it is recent update which make them appear.

Linux Mint 19.1
NVIDIA driver 418 and 430 (tested with both)
Tested with stable and beta version of steam.

dmesg during the freeze:
[  484.274645] NVRM: Xid (PCI:0000:01:00): 69, Class Error: ChId 002a, Class 0000a097, Offset 00001c50, Data 3a400044, ErrorCode 0000000c
[  490.652732] NVRM: Xid (PCI:0000:01:00): 69, Class Error: ChId 002a, Class 0000a097, Offset 000017d0, Data 200205f7, ErrorCode 0000000c
[  506.215888] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: Class 0x1 Subchannel 0x0 Mismatch
[  506.215892] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x4041b0=0x1
[  506.215893] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ESR 0x404000=0x80000002
[  506.216044] NVRM: Xid (PCI:0000:01:00): 13, Graphics Exception: ChID 002a, Class 00000001, Offset 00001f04, Data 01fe699f
[  506.216168] NVRM: Xid (PCI:0000:01:00): 32, Channel ID 0000002a intr 02000000

And also some Xid 31 too.

Hope it can help.

**Comment by kisak-valve** [comment]
Hello @RenaKunisaki, @rpachon, are you still experiencing this issue on an up to date system?

**Comment by RenaKunisaki** [comment]
I'm no longer using Nvidia so I can't say if it's working or not.

**Comment by mryellow** [comment]
I'm no longer inflicting Steam for Linux on my systems so can't say if it's working or not.

**Comment by rpachon** [comment]
I'm not using nvidia anymore so I don't know if it has been resolved. No issue with AMD and last mesa branch.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as outdated.

**Comment by netlore** [comment]
I am currently seeing the same error on a GTX 1080Ti, with the 495.44 driver, while playing some games via proton... it occurrs at random, and causes the system to lock up for 10-20 seconds and the game to close.

[357831.961635] NVRM: Xid (PCI:0000:01:00): 31, pid=681412, Ch 0000006d, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_2 faulted @ 0xfc_d3fa5000. Fault is of type FAULT_PDE ACCESS_TYPE_READ

I believe this is a bug in the Nvidia driver, possibly related to Vulkan.... it does not happen with machines using AMD graphics and MESA.

The more graphics detail I use, the quicker it happens... if I back it down to 1080p medium, it will happen after 5 minutes often, but sometimes several hours (seems random)... while on 4K Ultra is will happen in perhaps 30 seconds every time, even tho the GPU is able to easily manage the 60fps cap.

**Comment by netlore** [comment]
Appears to be related to this:-

https://forums.developer.nvidia.com/t/will-the-fault-pde-access-type-read-bug-in-the-nvidia-driver-ever-be-fixed/79362
