### ISSUE TITLE
Steam broadcasting glitch

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6257]
#### Your system information

* Steam client version (build number or date): May 2 2019, at 00:33:37
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

1. I tried to watch MORDHAU stream from store page, stream did not load
2. I clicked "View broadcast page", but stream did not load
3. I copied URL and opened in browser, stream did not load
4. I switched back to store page
5. Now i have little broken box in bottom right corner

https://puu.sh/Do2ol/ebfab33eef.png
https://puu.sh/Do2oz/8bfbc29639.png

**Comment by kisak-valve** [comment]
Hello @XakepSDK, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
