### ISSUE TITLE
Steam crashes on creating desktop shortcut for non-steam games

### ISSUE THREAD

**Issue by aligodlike** [ValveSoftware/steam-for-linux#6259]
#### Your system information
https://gist.github.com/aligodlike/2687921cf50fa289539ce4b3e79b2997

* Steam client version (build number or date):  May 2 2019, at 00:33:37
* Distribution (e.g. Ubuntu): Manjaro KDE
OS: Manjaro 18.0.4
Kernel: x86_64 Linux 5.0.9-2-MANJARO
DE: KDE 5.57.0 / Plasma 5.15.4

* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
steam crashes when i wanna make desktop shortcut for non-steam games but it doesn't crash for steam games

#### Steps for reproducing this issue:

1. open steam client
2. add a non-steam game
3. click right on that non-steam game and click on "create desktop shortcut"

**Comment by kisak-valve** [comment]
Hello @aligodlike, this issue is already being tracked at #5804. Closing as a duplicate.
