### ISSUE TITLE
Steam Requires Old LibVA (1.8.3)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6260]
* Steam client version (build number or date): May 2 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

Steam requires the old libva1 package (1.8.3) to launch successfully, even if the most recent libva package (2.4.1) is installed, both 32bit and 64bit. Steam shouldnt require legacy libraries to function.

#### Steps for reproducing this issue:

1. Uninstall legacy libva1 packages (1.8.3), both 32bit and 64bit
2. Keep up too date libva packages (2.4.1), both 32bit and 64bit installed
3. Steam will still refuse to start

**Comment by kisak-valve** [comment]
Hello @shoober420, this issue report is invalid because you've disabled the Steam runtime, which is not a supported configuration. Also, the functional implications of using libva1 is being tracked at #5339.

Closing in favor of the existing issue report.
