### ISSUE TITLE
DualShock 4 Controller only works on certain Games

### ISSUE THREAD

**Issue by BlueberryBumsben** [ValveSoftware/steam-for-linux#6261]
#### Your system information

* Steam client version (build number or date): May 2 2019
* Distribution (e.g. Ubuntu): Endless OS 3.5.8
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I was trying to use my DualShock (Playstation) 4 Controller with Steam/ Big Picture Mode and it did not recognize it, both via USB and Bluetooth. I can still play some games from my library with it (Hero Siege, Slay the Spire) but other games don't work with it at all (Deadcells, Ultimate Chicken Horse). The Controller is correctly paired with my Laptop so I'm unsure how to fix this.

**Comment by RussianNeuroMancer** [comment]
Do you see DualShock 4 Big Picture controller settings? If yes, check if "PlayStation user settings" helps. If no, in case if Ubuntu steam-devices package installation is what solved issue for me, but I not sure how to apply it to Endless OS.

**Comment by nanonyme** [comment]
I would be curious if there's any change. We're now shipping also 32bit variants of controller support libraries thanks to cross-compiler in new freedesktop-sdk runtime.

**Comment by kisak-valve** [comment]
Hello @BlueberryBumsben, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
