### ISSUE TITLE
steam doesn't work when internet connection drops

### ISSUE THREAD

**Issue by aligodlike** [ValveSoftware/steam-for-linux#6264]
#### Your system information

* Steam client version (build number or date): May 2 2019
* Distribution (e.g. Ubuntu): Manjaro Linux (Arch based)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
when internet connection drops friend list just pauses at their game info or status or anything
and steam does not show "No Connection" like in windows
and it does not work when internet connection is back
i must exit steam and run it again to work with it again

#### Steps for reproducing this issue:

1. open steam
2. disconnect from the internet (at this point friend list pauses and there is no "No internet connection" warning
3. connect to the internet (and now nothing works until you exit the steam and launch it again)

**Comment by kisak-valve** [comment]
Hello @aligodlike, this issue is being tracked in various issue reports like #5163, #474, #3827, #4917. Closing as a duplicate.
