### ISSUE TITLE
Steam Cloud sync getting stuck at 0%

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6265]
#### Your system information

* Steam client version (build number or date): I don't have the PC available right now, will check later. Should be latest stable. 
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The Kerbal Space Program case began with that a friend of mine had began downloading some games onto the PC in question, then logged out of his account before all of them had finished. A different friend of mine then came along and wanted to play, but upon logging in and downloading Kerbal Space Program, upon launching the game was stuck on what seemed like a download that never moved, stuck on 0%. 

We waited a bit, but no luck. Restarting Steam did not help either. until we disabled Steam Cloud for that game and restarted Steam again.

Note: I have had the same issue, but when doing a different thing, on my home PC running Fedora. I can't seem to reproduce it on this PC any more though, maybe it was fixed in a beta update?

#### Steps for reproducing this issue:

1. Have Steam Cloud saves on your account 
2. Have another user go on Steam and start some (game) downloads 
3. Log out of that account without letting the downloads finish 
5. Start Steam with your account
6. Try to start a game where you have Steam Cloud saves that have not previously been synced to this PC
7. Observe Steam getting stuck on a 0% 0kb/s download until you disable Steam Cloud for that game and restart Steam (only restarting Steam did not work in our case)

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment]
It is hard to say. I was only able to reproduce this on one occasion, and it was with a friend's Steam account on a PC I don't own when trying to run a game my account doesn't have either. Furthermore, the PC this happened on probably has had the OS reinstalled by now, and it may not even exist any more.

In other words, let's say it's not reproducible any more.
