### ISSUE TITLE
Danger Zone drone pilot graphical issue

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6269]
#### Your system information

* Steam client version (build number or date): 29th April
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Drone Pilot view in CS:GO Danger Zone seem to have a graphical issue in the middle of the screen, making it hard to actually pilot properly and see what's below you - a nuisance.

See this image: https://imgur.com/a/b4JsVvh

Now compare with the official image: https://steamcdn-a.akamaihd.net/apps/csgo/images/sirocco/dronepilot.jpg

It shouldn't be there.

#### Steps for reproducing this issue:

1. Load CS:GO with nvidia on Ubuntu
2. Pick Drone Pilot drop-in perk
3. Attempt to fly and see the horrible thing in the middle making it hard to see properly

**Comment by RomanTruba** [comment]
You should post it in https://github.com/ValveSoftware/csgo-osx-linux/issues

**Comment by LiamDawe** [comment]
DOH! Thanks moved: https://github.com/ValveSoftware/csgo-osx-linux/issues/2101
