### ISSUE TITLE
Unable to Stream to Linux from Windows on Beta program for Firefox application

### ISSUE THREAD

**Issue by dmp1ce** [ValveSoftware/steam-for-linux#6270]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Streaming to Arch Linux from Windows crashes as soon as loading the Firefox shortcut application. This only occurs for me on the beta and it just started. Both Steam clients were on the beta program.

#### Steps for reproducing this issue:

1. Set Linux steam client to Beta program
2. Set Windows Steam client to Beta program
3. Create a Firefox application for the Windows Steam client.
4. Try to Stream Firefox from the Linux Steam client
5. Notice the Firefox application will not Stream and will eventually crash the stream on the Linux client

**Comment by kisak-valve** [comment]
Hello @dmp1ce, are you still experiencing this issue on an up to date system?

**Comment by dmp1ce** [comment]
It worked for me once I updated my Steam client on Linux and Firefox on Windows. Thanks for asking me to retest!
