### ISSUE TITLE
The settings window renders incorrectly

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6271]
#### Your system information

* Steam client version: May 15 2019, at 21:17:00
* Distribution: Xubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In the Remote Play tab, all the pairing option buttons are rendered under the device name element.
![image](https://user-images.githubusercontent.com/42655600/57844975-b6cce280-77d9-11e9-8073-15743c09e1cd.png)

The Family tab leaves a huge gap between the box and the list of accounts. For this to appear, you must start steam with the box unticked
![image](https://user-images.githubusercontent.com/42655600/57845343-7d48a700-77da-11e9-8085-6869bb8d0c32.png)
Also, tick the box off, go to another settings tab, return to Family and tick the box on and this will happen
![image](https://user-images.githubusercontent.com/42655600/57845399-9c473900-77da-11e9-849d-11d20f0160f9.png)

**Comment by kisak-valve** [comment]
Hello @Managor, please retest if you can reproduce this issue.

**Comment by Managor** [comment]
Still happens. Been kinda waiting for the eventual settings rework before even touching this issue. The pairing window doesn't seem to be broken any more tho.
![image](https://user-images.githubusercontent.com/42655600/135700961-719e7f6e-e5d5-4a08-8049-c4977ee183c6.png)

**Comment by Managor** [comment]
This is not an issue any more as this settings window has been removed.
