### ISSUE TITLE
Unable to set game storage when installing multiple games

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6273]
#### Your system information

* Steam client version: May 15 2019, at 21:17:00
* Distribution: Xubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
There is no option to change the install location when trying to install multiple games. It seems to install them to the location that you previously installed a game to.

#### Steps for reproducing this issue:

1. Select several games
2. Right click
3. Click on install

Example video: https://www.youtube.com/watch?v=gsVPJ4wnYNY

**Comment by Managor** [comment]
I think this is fixed in the new library beta 
![Screenshot_2019-10-06_22-43-52](https://user-images.githubusercontent.com/42655600/66274835-25930100-e88b-11e9-87df-490aea975c08.png)

**Comment by kisak-valve** [comment]
Closing as fixed in the [2019-10-30](https://store.steampowered.com/news/55600/) Steam client update.

**Comment by Managor** [comment]
This bug has resurfaced.

**Comment by kisak-valve** [comment]
Hello @Managor, please open a new issue report so that it can be tracked properly.
