### ISSUE TITLE
Steam Clients won't connect via In Home Streaming.

### ISSUE THREAD

**Issue by bjwest** [ValveSoftware/steam-for-linux#6280]
#### Your system information

* Steam client version (build number or date):  1558141979 (desktop), 1556574584 (laptop)
* Distribution (e.g. Ubuntu): KDE Neon 5.15 (desktop) Kubuntu 18.05 (laptop)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The Steam Client on my laptop is package version 1556574584 with a build date of Apr 29 2019 at 20:58:26, while the version on my desktop is 1558141979 built May 18, 2019 at 00:44:39.  When I try to check for updates on my laptop it says it's up to date.  This is preventing me from connecting for in home streaming.

I also noticed there is no 'In Home Streaming' selection in the settings dialog on my desktop, it's been replaced with a 'Remote Play' selection.  There is no 'Remote Play' selection on my laptop client's settings.  It's been a while since I've been in the settings, so I don't know when the selection change took place, it may have been when I installed the Seam Link app on my Android tablet earlier today and linked it to my desktop client, or it may be part of the 1556574584 update.

**Comment by kisak-valve** [comment]
Hello @bjwest, in the [2019-05-15](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1611638091301723544) Steam beta client update, In-Home Streaming got a significant overhaul to allow it to be used outside the home. You're mixing the stable and beta release between the two systems. Please use either the stable or beta client on both systems.

**Comment by bjwest** [comment]
Thank you @kisak-valve, I didn't even think about the beta client.  I use it for Proton on the desktop.  I use an old laptop that I don't think would handle most of my games well, let alone Proton, so never opted into the beta on it.   Switching to beta fixed the problem.

Closing due to user dumbness.
