### ISSUE TITLE
Friends get flooded by notifications

### ISSUE THREAD

**Issue by xavir223** [ValveSoftware/steam-for-linux#6289]
#### Your system information

* Current beta
* Distribution (e.g. Ubuntu): Debian testing
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Several friends report that they get flooded by messages that i am now playing game "X". Its unclear why and when this happens but it not happens all the time. I run game "X" for several hours and suddenly it starts to inform them every ~10 seconds. 

#### Steps for reproducing this issue:

1. Unknown

**Comment by kisak-valve** [comment]
Hello @xavir223, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
