### ISSUE TITLE
Deadzone Configurations: Add Shape Selection for Output Anti Deadzone

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [ValveSoftware/steam-for-linux#6290]
#### Your system information
<details><summary>System information</summary>
<p>

<pre>Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1700 Eight-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.1.6-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  compiz
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.30.0, 5.1.6-1-MANJARO, LLVM 8.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.0.4
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x67df
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 31.50" x 17.72" (36.10" diag)
                                            80.0cm x 45.0cm (91.7cm diag)
    Primary VRAM: 4096 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16053 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  479199 Mb
    Largest Free Hard Disk Block:  393220 Mb
    VR Headset: None detected

Recent Failure Reports:

</pre>

</p>
</details>

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2 (May 22, 2019)
* Distribution (e.g. Ubuntu):   "Manjaro Linux" (64 bit)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When using any joystick move output & having no deadzone enabled, the Cross deadzone will still be on. I've attempted to change it to a Circle deadzone, adding Output Anti Deadzone, callibration in Steam, blacklisting hid_steam, adding user to the input group & using sc-controller to no avail. It is most noticeable on the touchpads, but it is still present for mechanical joysticks. Both right and left joystick outputs are affected.

This issue affects both Xbox360 and Steam controllers. For the Xbox360 controller, I disabled steam Xbox configuration support & the issue still persisted. Victor Vran, BallisticNG, Skyrim SE, Retroarch, & Serious Sam Fusion are unaffected. I believe the issue stems from a broken libsteam-api library employed in BlazeRush. If this is an issue with outdated/broken libraries, a workaround would be to add a shape selector for Output Anti Deadzone such that games with broken input can be configured to work as expected. This issue is specific to Linux as Windows 7 does not experience the issue.
#### Steps for reproducing this issue:

1. Open BlazeRush
2. Notice the 4 cardinals have a 3-5 degree deadzone
3. Open Steam config and ensure cross deadzone is disabled
4. Try other controllers

**Comment by kisak-valve** [comment]
Hello @Myrddin-Wyllt, because the game is affected while Steam's xbox configuration is disabled, this sounds like an issue with the game and should be brought to the attention of the game's dev(s).

**Comment by Myrddin-Wyllt** [comment]
I've posted about it in the steam forum, sent a friend request to one of the developers, & emailed Targem games support regarding the issue. Considering this developer has a reputation for being unresponsive, could someone at Valve reach out as well, @kisak-valve? I have no official channel to make contact beyond what I've done besides telephone.

**Comment by Myrddin-Wyllt** [comment]
If Output Anti Deadzone had a shape selection to match the deadzones experienced in games, we wouldn't need to rely on  faith that game developers will correct issues with game input on all platforms. I don't see it being very likely every broken game will get fixes for Linux specifically. In these instances, users need overrides that will fix the issues.
