### ISSUE TITLE
Desktop Controller Configuration: Joystick Move Disappears as Option

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [ValveSoftware/steam-for-linux#6293]
#### [Your system information](https://gist.github.com/Myrddin-Wyllt/4cc23dfec5512efc59b4d93336a6d36b)
* Steam client version (build number or date): Aug 6 2019
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've tried configuring the Steam Controller's Desktop Configuration to use the left touchpad as Joystick Move. Unfortunately, it isn't currently possible to without manually editing .vdf configuration files. 

The only way I found to select Joystick Move as input for Desktop Configuration was to import the Gamepad template with Joystick Move. The problem exists for both Big Picture and Desktop methods of configuration. Weirder still, when I try to select the template's imported Joystick Move, the option vanishes & I need to re-import the configuration.

For games with gallium-nine in use, the Big Picture overlay will not function, so I've resorted to using the Desktop Configuration with these games in order to have controller support. Perhaps some means of automating changing the Desktop Configuration for certain games and reverting when closed could be added to Steam in the future. This would apply for more than just gallium-nine games as there are numerous games which don't work with the Steam Overlay. 

#### Steps for reproducing this issue:

1. Open Steam's Controller Desktop Configuration (inside Big Picture Mode or not)
2. Import the Gamepad template
3. Select the joystick with Joystick Move
4. Watch Joystick Move disappear

**Comment by EPecherkin** [comment]
Well, I have the same issue in Windows 10. Interesting

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by kisak-valve** [comment]
Hello @Myrddin-Wyllt, re-reviewing this issue report, it looks like #7289 is also open for the same issue. Let's continue tracking the issue there.
