### ISSUE TITLE
Configuration Support Disabled for Steam Controller

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [ValveSoftware/steam-for-linux#6294]
#### [Your system information](https://gist.github.com/Myrddin-Wyllt/4cc23dfec5512efc59b4d93336a6d36b)
* Steam client version (build number or date): Aug 6 2019
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
This issue seems very difficult to diagnose, as I can't really predict when or why this occurs but it happens whether wired or wireless, on both Bluetooth-LE and the Steam Controller Receiver. It seems to occur more frequently with multiple controllers connected & in the Desktop Steam client than in Big Picture. Occasionally, I'm greeted with this & sometimes it persists for a few different configuration attempts:
![Screenshot_20190527_134727](https://user-images.githubusercontent.com/42914865/58436634-fde58e00-808b-11e9-96f9-d6df1031567d.png)

I'm not sure why it suddenly decides to work, but considering it isn't even an option on the Linux platform, this shouldn't manifest. 
![Screenshot_20190527_143249](https://user-images.githubusercontent.com/42914865/58436703-574dbd00-808c-11e9-90df-3f66a8b7e3ad.png)
#### Steps for reproducing this issue:

1. Open Steam after a fresh boot
2. Try configuring the controller from the Desktop or Big Picture clients
3. Hope that you can reproduce the issue

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Myrddin-Wyllt** [comment]
This seems fixed.
