### ISSUE TITLE
Moving the left analog stick also moves the right stick (XBox One controller using steamos-xpad-dkms)

### ISSUE THREAD

**Issue by ShadowWarden** [ValveSoftware/steam-for-linux#6295]
#### Your system information

* Steam client version (build number or date): May 22 2019
* Distribution (e.g. Ubuntu): Manjaro 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I try playing a game with the XBox One controller, moving the left analog stick up also moves the right stick to the left. Thus, in a Skyrim like game, moving forward also turns the camera to the left. I'm currently using steamos-xpad-dkms downloaded and installed through the AUR (https://aur.archlinux.org/packages/steamos-xpad-dkms/)
 
#### Steps for reproducing this issue:

1. Install steamos-xpad-dkms (requires linux 4.14 and 4.19 headers)
2. Start up a game that uses the right stick for movement and the left stick for camera orientation (ex. any TES game, Witcher 3 ...)
3. Move the left stick up. On my system, this also pushes the right stick to the left

**Comment by kisak-valve** [comment]
Hello @ShadowWarden, have you encountered this issue with a native linux game, or are all affected games using Proton?

**Comment by ShadowWarden** [comment]
Hey @kisak-valve, I'm seeing this issue in pretty much every game I play. Specifically, I'm seeing this in Shadow of Mordor (Native Linux) as well as Skyrim (Proton)

**Comment by ShadowWarden** [comment]
An update: I've been experimenting with both my xbox controller and steam link through my phone on jstest-gtk and I'm fairly confident that this is a hardware problem and not a bug in steam for linux.

I will test a little more just to confirm and then close the issue.

**Comment by kisak-valve** [comment]
Closing pending feedback.
