### ISSUE TITLE
Commandline parameter "-nofriendsui" does nothing

### ISSUE THREAD

**Issue by Jayman2000** [ValveSoftware/steam-for-linux#6312]
#### Your system information

* Steam client version (build number or date): Apr 29 2019, at 20:58:26
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

[Detailed system information from Steam](https://gist.github.com/Jayman2000/d71c357f64955a785801c34bf8cf275b)

#### Please describe your issue in as much detail as possible:

I launched steam with the command line parameter "-nofriendsui". I expected the friends web UI to be disabled and replaced with the old UI. The parameter actually did nothing.

#### Steps for reproducing this issue:

1. Exit Steam.
2. Run `$ steam -nofriendsui`
3. Click View>Friends

[Command line output](https://gist.github.com/Jayman2000/8126641a2ccb931688db6eddbf5fa73d)

#### Workarround:
Launching Steam with the command line parameter "-no-browser" enables the old friends web UI, but it also makes the Steam Store and Steam Overlay Web Browser unusable.

**Comment by kisak-valve** [comment]
Hello @Jayman2000, the previous iteration of the friends UI in Steam is no longer supported.

**Comment by 07416** [comment]
The `-nochatui` parameter still seems to work. Not even listed on [the Valve wiki](https://developer.valvesoftware.com/wiki/Command_Line_Options#Steam_.28Windows.29).

**Comment by Jayman2000** [comment]
I just tried `-nochatui` and, unfortunately, it didn't work.

**Comment by mutageneral** [comment]
> Hello @Jayman2000, the previous iteration of the friends UI in Steam is no longer supported.

@kisak-valve 
Why not just leave the option to turn it off though? I know the old chat UI still works fine and still exists because I can turn it off with `-no-browser` but that turns off pretty much everything else with it. Clearly this wasn't a technical reason why you couldn't only turn off the new chat and not turn off Chromium Embedded Framework, it was a decision taken by someone so _why_.
