### ISSUE TITLE
Missing 32-bit libraries 

### ISSUE THREAD

**Issue by Greybane** [ValveSoftware/steam-for-linux#6313]
#### Your system information

* Steam client version (build number or date): 1.0.0.61
* Distribution (e.g. Ubuntu): Ubuntu 19.04 amd64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I attempted to install Steam and It crapped out on me. I've enabled multi-arch. 

[Gist](https://gist.github.com/Greybane/8ab166d5d1661e1879edf04087ba744f) of what happens when I run steam.

#### Steps for reproducing this issue:

1. Clean install of Ubuntu 19.04 amd64
2. sudo apt install -y steam-launcher
3. steam

**Comment by kisak-valve** [comment]
Hello @Greybane, Steam is accurately telling you that it needs a working 32 bit OpenGL driver installed to work.

Does any 32 bit opengl application work like `glxinfo` from `mesa-utils:i386` work?

**Comment by Greybane** [comment]
Here's a [gist](https://gist.github.com/Greybane/40a037e8a8bb09c2c50faa3839a391a5) of the install console.
I tried to install dependencies and end up with something similar to this.

```
The following packages have unmet dependencies.
 libgl1 : Depends: libglx0 (= 1.1.1-0ubuntu1) but it is not going to be installed
 libglx-mesa0 : Depends: libgl1-mesa-dri but it is not going to be installed
                Breaks: libglx-mesa0:i386 (!= 19.2~git1906080815.f8f222~oibaf~c) but 19.0.2-1ubuntu1 is to be installed
 libglx-mesa0:i386 : Depends: libdrm2:i386 (>= 2.4.75) but it is not going to be installed
                     Depends: libglapi-mesa:i386 (= 19.0.2-1ubuntu1) but it is not going to be installed
                     Depends: libgl1-mesa-dri:i386 but it is not going to be installed
                     Breaks: libglx-mesa0 (!= 19.0.2-1ubuntu1) but 19.2~git1906080815.f8f222~oibaf~c is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by baryluk** [comment]
@Greybane I think you might want to report this issue to oibaf instead. https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/24959-updated-and-optimized-ubuntu-free-graphics-drivers?50038-Updated-and-Optimized-Ubuntu-Free-Graphics-Drivers=  and https://bugs.launchpad.net/~oibaf

**Comment by kisak-valve** [comment]
Closing because a PPA system package conflict from 2019 is no longer relevant and not a Steam client issue.
