### ISSUE TITLE
I can't send a support ticket with Steam client.

### ISSUE THREAD

**Issue by MeGA-ct** [ValveSoftware/steam-for-linux#6319]
#### Your system information

Versión del sistema operativo:
    Ubuntu 19.04 (64 bits)
    Nombre de kernel: Linux
    Versión de kernel: 5.0.0-16-generic
    Editor de X Server: The X.Org Foundation
    Versión de X Server: 12004000
    Gestor X Window: GNOME Shell
    Versión del runtime de Steam: jenkins-steam-runtime-beta-release_0.20190320.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm trying to create a support ticket for DOTA2 in steam client, but the client always fails to create the report with this message, and I did not have any large attachment.

#### Steps for reproducing this issue:

1. Go to contact support:
https://help.steampowered.com/es/wizard/HelpContactForTechnicalIssue?appid=570&issueid=702
2. Fill the report and click send.
3. Get this message (i have steam in spanish): 
**CONTACTAR AL EQUIPO DE SOPORTE DE STEAM**
**Hubo un problema al enviar tu solicitud de ayuda al equipo de Soporte de Steam. Vuelve a intentarlo dentro de unos minutos.**

**Si estás intentando añadir archivos adjuntos de gran tamaño, prueba a enviar la solicitud sin ellos y a añadirlos a esta más tarde.**

**Comment by kisak-valve** [comment]
Hello @MeGA-ct, are you still experiencing this issue on an up to date system?

**Comment by MeGA-ct** [comment]
Hello, I tested this and it created this Ticket ID:
HT-FQQK-KDT4-RW4V.

But now i use
 Versión del sistema operativo:
    "Manjaro Linux" (64 bits)
    Nombre de kernel: Linux
    Versión de kernel: 5.9.16-1-MANJARO
    Editor de X Server: The X.Org Foundation
    Versión de X Server: 12101002
    Gestor X Window: GNOME Shell
    Versión del runtime de Steam: steam-runtime_0.20211102.0

If you need it i can try it on the last Ubuntu version.

Kind regards.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed some time ago.
