### ISSUE TITLE
I can't play Quake II RTX on Linux. I get "vid init failed" when I try to start the game.

### ISSUE THREAD

**Issue by ralyodio** [ValveSoftware/steam-for-linux#6320]
Ubuntu 18.04

**Comment by kisak-valve** [comment]
Hello @chovy, this issue should also be brought to the game dev's attention.

That set aside, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing due to lack of information.
