### ISSUE TITLE
CSGO crashes on load

### ISSUE THREAD

**Issue by vitacell** [ValveSoftware/steam-for-linux#6325]
#### Your system information

* Steam client version (build number or date): 17-2019 1560817063
* Distribution (e.g. Ubuntu): Slackware64-14.2 and/or Salix64-14.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I am running proprietary Nvidia driver with 32 bits nvidia's driver libs

#### Please describe your issue in as much detail as possible:
CS:Source does work, I can hear some distroted sound when the game is loading, but in game sound is fine.
CSGO start with black screen, and after few secons it crashes, I could to take some info from steam when the game launches:

http://dpaste.com/2P40WKZ

#### Steps for reproducing this issue:

1. Install Slackware64-14.2 or Salix64-14.2, then multilib
2. Install Steam
3. Launch CSGO

**Comment by kisak-valve** [comment]
Hello @vitacell, `Found joystick 'Microsoft Microsoft® 2.4GHz Transceiver v9.0' (030000005e040000a507000011010000), but no recognized controller configuration for it.` in your log indicates you've encountered https://github.com/ValveSoftware/csgo-osx-linux/issues/1757. Adding `-nojoy` to the game's launch options should workaround this issue.

Closing as a duplicate.

**Comment by vitacell** [comment]
> Hello @vitacell, `Found joystick 'Microsoft Microsoft® 2.4GHz Transceiver v9.0' (030000005e040000a507000011010000), but no recognized controller configuration for it.` in your log indicates you've encountered [ValveSoftware/csgo-osx-linux#1757](https://github.com/ValveSoftware/csgo-osx-linux/issues/1757). Adding `-nojoy` to the game's launch options should workaround this issue.
> 
> Closing as a duplicate.

-nojoy does work, thanks for fast answer!
