### ISSUE TITLE
Steam Linux client fails to connect remote computer while Android Steam link can

### ISSUE THREAD

**Issue by adam900710** [ValveSoftware/steam-for-linux#6333]
#### Your system information

* Steam client version : Unknown, latest stable
* Distribution : Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The setup has the following computers:
1. Linux desktop (LD)
2. Linux laptop (LL)
3. Windows VM in Linux Laptop (WV))
4. Android Steam Link (AS)
All computers are in the same network.

LD connect to LL: mostly fail, rare random success
AS connect to LL: Always success
LL connect to LD: mostly fail, rare random success
AS connect to LL: Always success
LD connect to WV: mostly fail, rare random success
LL connect to WV: mostly fail, rare random success
AS connect to WV: Always success (no DX driver, thus no big screen mode)

From streaming_log.txt and connect_log.txt, no connection from Linux Stream at all.
Further more, all system are using both IPv4 (172.16.0.0/24) and IPv6 address.
Firewall is already disabled, and Android Steam Link works proves it.

#### Steps for reproducing this issue:

1. Setup steam with Linux Steam as client, and any other Stream as Server
2. Try to use Remote play from Linux Steam
3.

**Comment by adam900710** [comment]
BTW, all Linux devices are using the same Arch setup, both native and runtime tested the same.

**Comment by nalquas** [comment]
Related #6275

**Comment by adam900710** [comment]
Not sure if that's the same bug.

In my environment, no segfault or crash. Just client fails to connect to remote computer.
On the host, the game is executed without problem.

**Comment by joeknock90** [comment]
@adam900710 That's the same issue. Linux streaming client is completely broken. Game will run fine on host. Client fails to connect and usually crashes.

**Comment by TriplexRoss** [comment]
I checked `dmesg` and found these lines, maybe it'll help.
```
[36661.104158] CIPCServer::Thr[12849]: segfault at aa8a798d ip 00000000f7000003 sp 00000000ec0ede9c error 6 in libnvidia-glcore.so.340.107[f66f1000+c34000]
[36661.104166] Code: 31 8a 8a b0 12 a7 c6 f6 36 c5 a0 90 27 8a f1 df 38 c3 b4 d7 75 c9 a3 93 3a d8 e0 df 37 cb af 94 32 d8 a3 8a 3b ce 93 9c 3a c6 <a3> 8d 79 8a aa 90 32 f5 a8 96 2
6 de ad 91 36 cf ec d5 75 cc a3 98
[36661.104201] audit: type=1701 audit(1561262637.523:135): auid=1000 uid=1000 gid=998 ses=
2 pid=12803 comm="CIPCServer::Thr" exe="/home/ross/.local/share/Steam/ubuntu12_32/steam" s
ig=11 res=1
[36661.188084] audit: type=1130 audit(1561262637.606:136): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-16834-0 comm="systemd" exe="/usr/lib/systemd/syst
emd" hostname=? addr=? terminal=? res=success'
[36663.572168] audit: type=1131 audit(1561262639.992:137): pid=1 uid=0 auid=4294967295 ses
=4294967295 msg='unit=systemd-coredump@0-16834-0 comm="systemd" exe="/usr/lib/systemd/syst
emd" hostname=? addr=? terminal=? res=success
```

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
