### ISSUE TITLE
Invisible download

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6335]
#### Your system information

* Steam client version (build number or date): Jun 21 2019, at 01:43:20
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Sometimes steam downloads something, but downloading item not shown in downloads window. Only labels under `NETWORK USAGE` changing.

**Comment by sysms** [comment]
I can confirm this phenomenon of the "phantom downloads". 
The download queue itself is empty.

I'm observing it at least for the last two iterations of the Steam stable Linux client.



![steamclient_phantom_downloads](https://user-images.githubusercontent.com/4120422/59973636-ae1eb780-95a2-11e9-999e-0c6cfff39b2d.jpg)

I'm currently using the stable client from June 17th.

Link to System Info: https://gist.github.com/sysms/193452d8efbb587bd9980c965d1fef2a

**Comment by byte1024** [comment]
The Pre-Caching does have a identical effect as far as I can see and I believe this is that. It looks like if you're on the library it will blink ready to play when downloading shaders but nothing in the download section.

`Re-worked the shader system to enable downloading and pre-compiling of the whole collection of Vulkan pipelines for a given game. As a result, **some** shader data downloads will now show in the Steam download manager. Pre-compiling will be enabled in a future Steam update.`

At this time, I don't have any that show =)

**Comment by aligodlike** [comment]
same here
steam uses bandwith and it says downloading but download list is empty

**Comment by atomsymbol** [comment]
I am experiencing this issue as well.

It would be nice if Steam showed a summary describing what is being downloaded. Multiple downloads related to several games might be aggregated into a single download summary when possible.

**Comment by atomsymbol** [comment]
Also of note is that while network download is (for example) 182.6 MB, the disk usage - according to the green line in the chart - is zero.

![Screenshot_20190702_192240](https://user-images.githubusercontent.com/22368256/60532978-cc9d5500-9cfe-11e9-8ca7-aaa0e82181f7.png)

**Comment by atomsymbol** [comment]
It seems July-16 update had the invisible downloads fixed but July-17 update pulled it back?

The disk usage (green line in chart) was still zero though even with the July-16 update.

Maybe there can be a checkbox in Settings>Downloads for the user to select whether to hide/show cache updates.

Multiple downloads related to several games might be aggregated into a single download summary when possible in order to reduce the number of mouse clicks when the user wants to remove all downloaded items from the list.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by atomsymbol** [comment]
From my viewpoint, this issue has been fixed for the most part. An unfixed part is that disk usage reported by Steam is zero while downloading shader caches, but the actual disk usage isn't zero in this case.

**Comment by kisak-valve** [comment]
From what I can tell, that is expected. Steam doesn't seem to try to write to disk part way through a shader pre-cache update.

**Comment by atomsymbol** [comment]
That isn't what I see in [glances](https://github.com/nicolargo/glances) (table "DISK I/O", column "W/s") while Steam is downloading shader caches.

**Comment by atomsymbol** [comment]
> From what I can tell, that is expected. Steam doesn't seem to try to write to disk part way through a shader pre-cache update.

To be more precise:

- Game: _Rise of the Tomb Raider_ (this game has the largest shader cache of all Steam Linux games I own)
- Shader cache directory: $HOME/.cache/steam-shadercache/391220
  - Sub-directories: swarm, fozpipelinesv6

I observe the following behavior after disabling shader caching in Steam options, deleting the game's cache, and re-enabling shader caching in Steam options:

1. Steam first downloads (i.e: writes) about 500 MB of data from network into the `swarm` sub-directory.
2. After the download finishes, Steam copies the data (about 500 MB) from the `swarm` sub-directory to the `fozpipelinesv6` sub-directory.

If another download is in Steam's download queue, it will start immediately after the completion of step 1. Thus, step 1 of the next download and step 2 of the previous download seem to be executing concurrently, as far as I can see.

**The disk usage reported by Steam while processing steps 1 and 2 is zero.**

**Comment by X6205** [comment]
In my case are invisible downloads usualy related to Proton runtime. I hide Proton in my Steam Library to not have it visible between games, because Valve is incompetent to hide it on client level. So when i download some games, my invisble downloads are usually proton or steam runtime soldier or something like that..
