### ISSUE TITLE
Steam Hard-Locking with high frequency (recently new)

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#6336]
* Jun 17 2019
* Ubuntu 19.04
* No
* Yes, applied all

This issue started within the last few weeks. I don't know how to reproduce it, but often I'll come back to my STEAM app and it just won't respond at all. can't exit it, can't tell it to quit nicely (have to kill -9 it), etc. Also, it often won't pick up that Rust has properly quit, or sometimes Rust won't properly launch the initial unity settings GUI.

There are times STEAM will lock up multiple times per day, and it seems to happen after random periods of time. I really have not observed a pattern here, be it time to crash, or specific actions crashing the app.

Furthermore, the STEAM overlay (at least in Rust) sometimes doesn't actually load, so the FPS overlay and shift+tab stuff doesn't work. I'm thinking this is related, as it started about the same time.

**Comment by kisak-valve** [comment]
Hello @BloodyIron, are you still experiencing this issue on an up to date system?

**Comment by BloodyIron** [comment]
@kisak-valve I don't think I've had this particular issue for a verrryyy long time. Closing, sorry about that!
