### ISSUE TITLE
Steam clint randomly blocks power management screen blanking.

### ISSUE THREAD

**Issue by bjwest** [ValveSoftware/steam-for-linux#6337]
#### Your system information

* Steam client version (build number or date): Jun 21 2019 @ 01:43:20.  API v018
* Steam package versions: 1561159470
* Distribution (e.g. Ubuntu): KDE Neon 5.16
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam client randomly disables power management  with the notification "My SDL application is currently suppressing power management: playing a game" dosplayed in the Battery and Brightness widget.  Exiting Steam and restarting will clear the problem for a random period of time, after which the power management is disabled again with the same notification.

#### Steps for reproducing this issue:

1. Run Steam client.
2. Wait a random, indeterminate period of time.
3. Notice screen no longer blanks after set inactivity time.

Seems to be similar to issue  #5532 from about a year ago, but I don;t recall having that problem back then.  This started happening a few weeks ago, and I've just now taken the time to trace it to the Steam Client.

**Comment by kisak-valve** [comment]
Hello @bjwest, this issue is already being tracked at #5607. Closing as a duplicate.
