### ISSUE TITLE
Steam infinite game installation after update

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6338]
#### Your system information

* Steam client version (build number or date): Jun 21 2019, at 01:43:20
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

I just got black mesa update, after downloading 6.0GB of 6.0GB, updater switched to installing phase and just stuck, remaining time increases. After some time game goes in to queued state.

I think, i know how to reproduce.

1. Add external library
2. Install game in external library
3. Publish new version of game
4. Add update for a game
5. Your mount with steam installation must have enough space to fit update
6. Your mount with external library must not have enough space to fit update
7. Start updating game

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue is already being tracked at #5558. Closing as a duplicate.
