### ISSUE TITLE
Invalid cd key

### ISSUE THREAD

**Issue by natebo561** [ValveSoftware/steam-for-linux#6339]
#### Your system information
Mount and blade warband will not launch please help I have a Alienware steamer console with a cd key
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @natebo561, this sounds like an account issue, not a technical issue. Account issues are not handled on Github. Please use [Steam Support](https://help.steampowered.com/en/).

**Comment by natebo561** [comment]
Ok thanks
