### ISSUE TITLE
Games cannot download or update ("manifest unavailable")

### ISSUE THREAD

**Issue by jimj316** [ValveSoftware/steam-for-linux#6340]
#### Your system information

* Steam client version (build number or date): Jun 8 2018
* Distribution (e.g. Ubuntu): Debian 10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Since a few weeks ago, my Steam client (on Debian 10) is no longer able to install or update any games; updates never begin, sitting permanently on "scheduled", and installing games from scratch gives a "manifest unavailable" error. An example of the error is below, for the game Lifeless Planet:

"An error occurred while installing Lifeless Planet (manifest unavailable) :

cache13-lhr1.steamcontent.com/depot/261533/manifest/341583837872164349/5(null)"

Everything else on my computer is able to connect to the internet fine, and I've seen no other issues from Steam; I'm also able to download the manifest file from the URL in the error message using my browser. I can't attach it to this report, but it's MD5 is 624ff4066d3278f01a10d44cc6b6e567.

I've tried going through most of the things in the support page that the error links to (https://support.steampowered.com/kb_article.php?ref=2274-IFLV-5334) but none of them have helped. Specifically, I've flushed the steam cache, changed my download location, moved the steam library to a different drive, flushed my DNS cache, purged and reinstalled Steam (through APT), and rebooted my computer several times.

I've also checked to make sure that I have enough disk space in all my system partitions. I've not tried any of the "Advanced Troubleshooting" steps yet, but most of them appear to be written for Windows or Mac.

I'm happy to provide more information if needed.

**Comment by kisak-valve** [comment]
Hello @jimj316, can you check if `nstat -az | grep -i wqueue` is greater than zero, and if it is, does it increase as steam tries to download game content?

**Comment by jimj316** [comment]
I monitored that command through `watch` as I started Steam, logged in, and tried to queue an update.

Before Steam started, it gave the output:
`TcpExtTCPWqueueTooBig           0                 0.0`

The second number then counted up to 7 as Steam logged in; after I queued a download it slowly counted up to 25 over about two minutes before Steam gave up trying to download (the download went from "starting" to "not queued").

**Comment by kisak-valve** [comment]
Thanks for testing @jimj316, that hints that you're seeing the same issue being tracked at #6326 which affects your distro's kernel since 4.19.37-4.

Ask your distro's kernel maintainer(s) to update to 4.19.55 or cherry pick https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b6653b3629e5b88202be3c9abc44713973f5c4b4 if it hasn't been already.

**Comment by kenzodeluxe** [comment]
I have similar symptoms, but apparently for a different reason. When trying to download, I'm getting a similar error message:
```
An error occurred while updating Move or Die (manifest unavailable) :
cache9-ams1.steamcontent.com/depot/323851/manifest/5476459221744372406/5(null)
```
As you can see, the URL has a "(null)" appended. Running a tcpdump, I can validate that the client actually uses that same URL which returns in a 404:
```
GET /depot/323850/manifest/8190235131137338064/5(null) HTTP/1.1
Host: cache63-fra1.steamcontent.com
Accept: text/html,*/*;q=0.9
Accept-Encoding: gzip,identity,*;q=0
Accept-Charset: ISO-8859-1,utf-8,*;q=0.7
User-Agent: Valve/Steam HTTP Client 1.0

HTTP/1.1 404 Not Found
Server: nginx/1.15.10
Date: Mon, 08 Jul 2019 16:03:14 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 92
Connection: keep-alive
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Cache-Control: no-cache,must-revalidate
Pragma: no-cache
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>Not Found</h1>
</body>
</html>
```

**Comment by jimj316** [comment]
I've updated my kernel to 5.2-0.2 now, but I'm afraid I'm still having this issue. Looking closer, I see that the URLs that Steam is trying to download also have "(null)" attached, so presumably this is another instance of that issue.
