### ISSUE TITLE
Multiple selection (shift+click) gets stuck if a system shortcut that contains the shift key is used.

### ISSUE THREAD

**Issue by Blast-City** [ValveSoftware/steam-for-linux#6341]
#### Your system information

* Steam client version (build number or date): 
Version: 1:1.0.0.54+repack-5ubuntu1 from Ubuntu official repo fully updated.
* Distribution (e.g. Ubuntu): 
elementary OS Juno (Ubuntu 18.04) fully updated.
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Steam's multiple selection (shift+click) is permanently selected when a system shortcut that involves pressing the shift key is used. To return to normal behaviour, shift key needs to be pressed again.

#### Steps for reproducing this issue:

1. Open Steam, select library and then select a game on the left list 
2. Press Super+Shift+End to move Steam's window to the last workspace.
3. Go to the workspace that contains the Steam window
4. Select another game on the left list.

The multiple selection is enabled even thought shift click is not being pressed.
This also happens with other Shift shortcuts like the "cycle workspaces backwards" (Super+Shift+Tab).

**Notes:** 
This issue was tested on a new elementary profile (no config) with a new Steam profile (no config) to rule out any config problems.
It's possible that this issue is also happening on Gnome.

**Comment by kisak-valve** [comment]
Hello @Blast-City, this issue is already being tracked at #3451. Closing as a duplicate.
