### ISSUE TITLE
Steam client beta updated, can't login

### ISSUE THREAD

**Issue by Rene2LeLorrain** [ValveSoftware/steam-for-linux#6342]
#### Your system information

* Steam client version (build number or date): Latest beta version updated 
* Distribution (e.g. Ubuntu):  Ubuntu 18.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes ( that's my problem!)

Login fails saying "You have entered your password or account incorrectly ....."

I can login on the web, no problems. The account name is definitively correct but I tried many time to enter my password without success. even with cut and paste from a text editor!

#### Steps for reproducing this issue:

1. Have the Steam client beta installed, and select update ....
2. Close the client to restart it
3. Can't login 

Then I went into the steam directory "~/.steam" and started the script "stream.sh" and got the message "Could not connect to Steam Network." while I was still browsing the steam catalogue with Firefox... 
![Steamclienterror](https://user-images.githubusercontent.com/31149521/60226106-bfdcb500-9857-11e9-9aa5-39da2ab83546.png)

**Comment by kisak-valve** [comment]
Hello @Rene2LeLorrain, you've encountered #6326 which can be confirmed by checking if `nstat -az | grep -i wqueue` is not zero and increases when Steam tries to connect.

Closing as a duplicate.
