### ISSUE TITLE
steam use a bad way to get the name distro

### ISSUE THREAD

**Issue by pruebahola** [ValveSoftware/steam-for-linux#6343]
#### Your system information
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1700 Eight-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3000 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.19.49-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  KWin
    Steam Runtime Version:  jenkins-steam-runtime-beta-release_0.20190320.2

Video Card:
    Driver:  X.Org AMD Radeon HD 7900 Series (TAHITI, DRM 3.27.0, 4.19.49-1-MANJARO, LLVM 8.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.0.6
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1360 x 768
    Desktop Resolution: 1360 x 768
    Primary Display Size: 22.83" x 12.60" (26.06" diag)
                                            58.0cm x 32.0cm (66.2cm diag)
    Primary VRAM: 3072 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  16052 Mb

Miscellaneous:
    UI Language:  English
    LANG:  es_ES.UTF-8
    Total Hard Disk Space Available:  157794 Mb
    Largest Free Hard Disk Block:  138913 Mb
    VR Headset: None detected

Recent Failure Reports:

* Steam client version (build number or date): Jun 17 2019, at 23:31:27
* Distribution (e.g. Ubuntu): Opensuse, Manjaro, ubuntu tested
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
steam get the distro name using "Description" from "lsb_release -a"
This is a problem because 2 things:

1- Not all distro use this method because is the old method (example opensuse) and steam don't detect opensuse as distro and only put "Linux 64bit"

2-Is a old method, actually is "cat /etc/os-release" (used in all distros)

#### Steps for reproducing this issue:

1. check the name steam detect about you distro
2. if only put "linux 64bit", install lsb-release package and steam will detect the name correctly
3. if the name is correctly, remove lsb_release package and steam will put "Linux 64bit" as distro name

**Comment by kisak-valve** [comment]
Hello @pruebahola, this topic is already being discussed at #5909. Closing as a duplicate.

**Comment by pruebahola** [comment]
Thanks @kisak-valve 
I hope this will fix soon, i'm in curiosity about steam survey, is really interesting!
