### ISSUE TITLE
The Linux home streaming client doesn't behave correctly after alt tabbing

### ISSUE THREAD

**Issue by sysrq-reisub** [ValveSoftware/steam-for-linux#6347]
#### Your system information

* Steam client version: Jun 17 2019, 23:31, 1560817063
* Distribution: Ubuntu, tested on Manjaro as well
* Opted into Steam client beta?: Yes, but also tested on the non-beta version
* Have you checked for system updates?: Yes, on every distro

To reproduce the issue you have to:

- Use the streaming client on Linux, playing with a windowed game on the Windows server.
- Alt+tab in Linux from the streaming client to the desktop
- Alt+Tabbing back to the streaming client

Only after this moment

- When receiving ANY desktop notification (the DE default in Ubuntu is gnome-shell), when changing the volume or the brightness, **the streaming-client content shifts to the right.**

- When receiving ANY steam notification, example a simple message or a person that have just opened a game

- When using the screenshot tool

WORKAROUND: To workaround this definitely, just press ALT+ENTER 2 times, after this moment it will never break again until the streaming client is restarted again, so you can alt tab so many times you want, it won't give problems.

EXPECTED
- Receiving steam, and gnome-shell notifications without the streaming client window content to be shifted on the right

![Schermata da 2019-06-28 00-56-41](https://user-images.githubusercontent.com/7904559/60309513-728f3f00-994e-11e9-97ca-dc552446a0ba.png)

**Comment by kisak-valve** [comment]
Hello @sysrq-reisub, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
