### ISSUE TITLE
Issue Report : Please login to your steam client

### ISSUE THREAD

**Issue by mikedebian** [ValveSoftware/steam-for-linux#635]
Hello, yesterday my steam client updated itself and when trying to play several games it asks me to either log into my steam client or that the game can not connect to steam. Every other function of steam works, I am in the beta and when using the ingame option of the steam overlay, everything shows. 

Ubuntu 12.10 AMD64
AMD FX-4100
Asus Sabertooth AM3+ 990FX
4096 MB DDR3 1600 Corsair RAM
Saphire 7850 HD AMD Radeon
Catalyst 12.11 Beta 11

I did not have a problem, nor did I change any settings up until this happened.

I tried to delete steam.sh and reinstall steam. Steam then changed directory from ~/Steam/steamapps/common (Old location of installed games) to ~/.local/share/Steam/steamapps/common

I then proceeded to move the games. After finding out of this problem I downloaded a couple I had not installed before but the problem persisted after rebooting and whatnot.

I would also like to point out that my system is up to date and I did remove/reinstall Steam before and after discovering this. Killing floor for example tells me that I need to have an active internet connection and Steam running and refuses to load my perk. Team Fortress 2 tells me I need to log into Steam to join a game, etc.

**Comment by linuxgruven** [comment]
I have a fix just us sam....works for me...if they cant fix there crap deal...I got tired of re-perking...have over 1000 hours as a lvl 2 sharp...screw them...I think its more of a steam issue...it is a "perk" thing...
