### ISSUE TITLE
Steam store tab does not load

### ISSUE THREAD

**Issue by Occhioverde** [ValveSoftware/steam-for-linux#6350]
#### Your system information

* Steam client version (build number or date): _Beta 1561768292 (28/06/2019)_
* Distribution (e.g. Ubuntu): _Manjaro 18.0.4 Illyria (Kernel x86_64 Linux 4.19.49-1-MANJARO)_
* Opted into Steam client beta?: _Yes_
* Have you checked for system updates?: _Yes_

#### Please describe your issue in as much detail as possible:
I downloaded Steam installation packages from my distribution's Pacman repos today:
![DeepinScreenshot_seleziona-area_20190629161654](https://user-images.githubusercontent.com/18429412/60385581-d028a600-9a8a-11e9-8c3b-1419b5cfd9e1.png)
Once the client started, however, I realized that it is not possible to view the store page because, in its place, a completely black screen appears with the loading symbol perpetually displayed at the top right:
![DeepinScreenshot_seleziona-area_20190629162840](https://user-images.githubusercontent.com/18429412/60385607-20076d00-9a8b-11e9-9222-f00e93222d2a.png)
I have therefore updated to the beta version of the software, but the problem is not solved.
I therefore wonder if there is a way to display this screen anyway without having to use the browser.

#### Steps for reproducing this issue:

1. Open the Steam client
2. Visit the "Store" tab

**Comment by kisak-valve** [comment]
Hello @Occhioverde, you've encountered a packaging issue with the distro's steam package. Installing the `steam-native` package on Manjaro disables the Steam runtime and the distro's package maintainer(s) is responsible for providing all dependencies if the runtime is disabled.

You can workaround this issue by completely closing Steam. then running `STEAM_RUNTIME=1 steam` in a terminal or removing the `steam-native` package.

Closing as not-our-bug.
