### ISSUE TITLE
Steam picks the wrong steam controller config or doesnt think its a gamepad

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6354]
The issue is a little tricky, as it doesn't happen 100% of the time. I'm looking for feedback on how I can find the issue.

#### Your system information

* Steam client version (build number or date): 17th june
* Distribution (e.g. Ubuntu): Manjaro (also happens on Ubuntu)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Set a specific Steam Controller config for Rocket League, launch Rocket League and it picks the official config instead of my own.

Sometimes it also just doesn't pick up the Steam Controller as a gamepad at all.

**Comment by JoranDox** [comment]
Hi @LiamDawe , I just found this issue, and it might sound like my own issue here: https://github.com/ValveSoftware/steam-for-linux/issues/7055, if it's still an issue for you, would you try if my workaround (open BPM, use the steam controller wired, and don't use in-home streaming) works for you? If yes, we could probably bundle our issues as it's likely to be the same.

**Comment by LiamDawe** [comment]
Sorry, no way for me to test now, I refunded RL when they dropped Linux and it was the only game I had the issue with.

**Comment by JoranDox** [comment]
@LiamDawe thanks for replying anyway, any info is useful :)

Did you use the linux binaries or proton + windows binaries? If the former it's different from my issue.
