### ISSUE TITLE
Steam client puts itself on list of streaming targets

### ISSUE THREAD

**Issue by XANi** [ValveSoftware/steam-for-linux#6355]
#### Your system information

* Steam client version (build number or date): Jul 2 2019
* Distribution (e.g. Ubuntu): Debian 10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Since maybe a week or two, my own machine (there is no other steam-capable devices on network) is shown as target for streaming:

![2019-07-02_23-31](https://user-images.githubusercontent.com/147394/60548131-a76e0e00-9d21-11e9-8133-8b6c8b132db9.png)

While streaming to itself kinda sorta works (no mouse input, but evidently streaming as I can see graphic differences), it isn't exactly useful

#### Steps for reproducing this issue:

No idea what is the common factor but I have same issue on other machine that have very similar setup. I can make a pcap if that helps in any way

**Comment by kisak-valve** [comment]
Hello @XANi, are you still experiencing this issue on an up to date system?

**Comment by XANi** [comment]
@kisak-valve I'll look at it most likely monday as I only had that issue on a PC that is at my job

**Comment by XANi** [comment]
Appears to be fine
