### ISSUE TITLE
Steam loses internet connection and turns off computer while playing dying light

### ISSUE THREAD

**Issue by bearcomesout** [ValveSoftware/steam-for-linux#6356]
#### Your system information:
memory: 32G, Processor: Intel core i7-8750H CPU @2.2-GHz x 12, Graphics: GeForcde GTX 1050 Ti with Max-Q Design/PCIe/SSE2, GMONE: 2.28.2, OS Type: 64-bit, Disk: 1 TB

* Steam client version (build number or date): June 17, 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04.2 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Play Dying Light
2. Start Campaign/Regular game
3. Play for 3-5 minutes until a message/pop-up says steam has lost internet connection. 
4. Laptop turns off after 10-15 seconds of seeing the pop-up. 

So far this is only happening on "Dying Light" while playing. I have other games that I can play and not have this issue happen. 

My settings for gameplay on dying light options are for best gameplay.

**Comment by kisak-valve** [comment]
Hello @bearcomesout, this reads like a thermal management issue. Are you able to ssh into the laptop and keep an eye on temperatures and dmesg?

**Comment by bearcomesout** [comment]
I am a complete newbie. Would you be able to tell me how to do that? Any help is greatly appreciated.

**Comment by lhorace** [comment]
Hello there,

Do you have a second machine or a phone with SSH client app? See https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-18-04/ and https://itsfoss.com/monitor-cpu-gpu-temp-linux/.

Cheers

**Comment by kisak-valve** [comment]
Hello @bearcomesout, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
