### ISSUE TITLE
"Cannot connec to Steam Network"

### ISSUE THREAD

**Issue by hellocld** [ValveSoftware/steam-for-linux#6359]
#### Your system information

* Steam client version (build number or date): Jul 2 2019
* Distribution (e.g. Ubuntu): Debian Buster (4.19.0-5-amd64)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam fails to connect/log in when launched ("Could not connect to network"). Attempted launching following deletion of local .steam directory and `steam --reset` with same results. Able to successfully launch and connect with `steam -tcp`. Network connection drops when running Steam VR Beta, but unsure if issues are related.

#### Steps for reproducing this issue:

1. Launch `steam` without any additional parameters

**Comment by kisak-valve** [comment]
Hello @hellocld, this issue is already being tracked at #6326.

Debian Buster's kernel build is affected since 4.19.37-4 and has not pulled in the kernel fix yet. The issue has already been investigated and there's no action to take on Valve's side. Closing as a duplicate.

**Comment by hellocld** [comment]
Ahh, missed that, apologies. Thanks!
