### ISSUE TITLE
Opening a steamplay game crashes the steam client

### ISSUE THREAD

**Issue by Lampwick** [ValveSoftware/steam-for-linux#6363]
#### Your system information

* Steam client version (build number or date): 1.0.0.61-1
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With steamplay activated for all titles. When clicking play on a steamplay title the client freezes on the dialogue stating, "this game will launch with steamplay using a platform compatibility tool..." and then crashes.

#### Steps for reproducing this issue:

1. Open steam client
2. click play on installed steamplay game.
3. Client freezes and then crashes.

**Comment by kisak-valve** [comment]
Hello @Lampwick, this reads like #5634 / #6329. Closing in favor of the existing issue reports.
