### ISSUE TITLE
PS4 controller not detected by Steam

### ISSUE THREAD

**Issue by djfaddie** [ValveSoftware/steam-for-linux#6364]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Connect PS4 Controller
Run Big Picture Mode in latest Steam beta update
Open Settings > Controller >
Disconnect PS4 Controller
Restart Steam in Big Picture
Reconnect PS4 Controller
 it doesn't show any PS4 Controller connected 
2. 
3.

**Comment by romulasry** [comment]
Have you tried the latest beta as of today?

**Comment by romulasry** [comment]
I tried latest beta as of today and it doesn't seem to work (via bluetooth). It works in gnome but it doesn't show up in Steam (beta).

**Comment by romulasry** [comment]
Would including this script fix it: https://steamcommunity.com/app/221410/discussions/0/1693795812304458372/ ?

**Comment by kisak-valve** [comment]
Closing pending feedback from @djfaddie. Without any system information or hints, there's not enough information here to investigate.
