### ISSUE TITLE
Garry's Mod: couldn't load 'gmod_audio' (looking for interface IGModAudio001)

### ISSUE THREAD

**Issue by LouCle** [ValveSoftware/steam-for-linux#6367]
#### Your system information

* Steam client version (build number or date): Jun 17 2019, at 23:31:27
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Launching the game, I get this error: couldn't load 'gmod_audio' (looking for interface IGModAudio001)

I'm on an arch install (kernel 5.1.15) and have been sitting fixing broken symlinks (and non-existing ones). After a Steam update I could no longer run garry's mod (or a good chunk of other source games). After fixing all of these library errors, the game started up and instead crashed with the above error message. I've searched the internet for a long time, to no avail.

Running both the hl2.sh script or the hl2_linux binary gives the following output
https://gist.github.com/LouCle/df0d22bf06e590bd4b6406f0d69a7ace

**Comment by kisak-valve** [comment]
Hello @LouCle, this issue should be mentioned to that game's dev(s).

**Comment by LouCle** [comment]
@kisak-valve I've sent an issue request to Facepunch. I'm just wondering why exactly this game, along with several others, broke in the exact same way after a steam client update.

**Comment by LouCle** [comment]
I just fixed it, by accident actually. Here's the thread from knockout https://knockout.chat/thread/1909/1

**Comment by kisak-valve** [comment]
Glad to hear you got it working. Closing as this was a system permission issue.
