### ISSUE TITLE
Big Picture Controller Config Window Stays Open (Black Screen)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6368]
* Steam client version (build number or date): July 2 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

#### Please describe your issue in as much detail as possible:

Under the Settings > Controller configuration screen with no controller plugged in, clicking on "Big Picture Configuration", "Desktop Configuration", and "Guide Button Chord Configuration" will prompt that theres "No Controller Attached".

After clicking "OK", you are met with a rectangular black screen that remains open with the Big Picture mouse cursor on a blank screen. IMO, after clicking "OK", Big Picture should close since no controller was found, since it leaves you at a black screen. You have to force close it with your window manager.

#### Steps for reproducing this issue:

1. Go to Settings > Controller
2. Click Big Picture Configuration", "Desktop Configuration", or "Guide Button Chord Configuration"
3. Click "OK", and be met with a rectangular black screen that doesnt close unless forced

**Comment by kisak-valve** [comment]
Hello @shoober420, are you still experiencing this issue on an up to date system?
