### ISSUE TITLE
Can't use russian input in steam overlay

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6370]
#### Your system information

* Steam client version (build number or date): Jul 2 2019, at 01:38:08
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Steps for reproducing this issue:

1. Start starbound unstable
2. Open overlay
3. Open chat
4. Try to write to someone using russian language input

**Comment by kisak-valve** [comment]
Hello @XakepSDK, can you check if the en_US.UTF-8 locale is enabled on your system? (from https://github.com/ValveSoftware/steam-for-linux/issues/6005#issuecomment-502343008)

**Comment by XakepSDK** [comment]
I have de_DE.UTF-8, en_US.UTF-8 and ru_RU.UTF-8 enabled

**Comment by kisak-valve** [comment]
Thanks for checking, looks like this issue is already being tracked at #2122. Closing in favor of the existing issue report.
