### ISSUE TITLE
Unable to download games/updates since "(null)" is appended to path

### ISSUE THREAD

**Issue by jkendzorra** [ValveSoftware/steam-for-linux#6372]
Moving this out of https://github.com/ValveSoftware/steam-for-linux/issues/6340 since it is not related to the kernel issue for me either (verified):
I have similar symptoms, but apparently for a different reason. When trying to download, I'm getting a similar error message:
```
An error occurred while updating Move or Die (manifest unavailable) :
cache9-ams1.steamcontent.com/depot/323851/manifest/5476459221744372406/5(null)
```
As you can see, the URL has a "(null)" appended. Running a tcpdump, I can validate that the client actually uses that same URL which returns in a 404:
```
GET /depot/323850/manifest/8190235131137338064/5(null) HTTP/1.1
Host: cache63-fra1.steamcontent.com
Accept: text/html,*/*;q=0.9
Accept-Encoding: gzip,identity,*;q=0
Accept-Charset: ISO-8859-1,utf-8,*;q=0.7
User-Agent: Valve/Steam HTTP Client 1.0

HTTP/1.1 404 Not Found
Server: nginx/1.15.10
Date: Mon, 08 Jul 2019 16:03:14 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 92
Connection: keep-alive
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Cache-Control: no-cache,must-revalidate
Pragma: no-cache
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>Not Found</h1>
</body>
</html>
```

_Originally posted by @kenzodeluxe in https://github.com/ValveSoftware/steam-for-linux/issues/6340#issuecomment-509289830_

**Comment by CodeAndLoathing** [comment]
I too have this issue and verified it using Fiddler. For now I have implemented a custom rule in Fiddler that strips off “(null)” and was able to download updates.

**Comment by jimj316** [comment]
I'm also having this issue on Debian 10; could you share your Fiddler rule so that I can work around this too? I've not been able to download anything for months :(

**Comment by CodeAndLoathing** [comment]
@jimj316  - I added it to the end of the OnBeforeRequest rule

```
if (oSession.PathAndQuery.EndsWith("(null)")) {				 
   oSession.PathAndQuery=oSession.PathAndQuery.Substring(0,oSession.PathAndQuery.Length-6);
}
```

I do have my Fiddler scripting language set to c#

**Comment by CodeAndLoathing** [comment]
@kisak-valve - can we get someone other than "ghost" assigned please.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by CodeAndLoathing** [comment]
I completely rebuilt that entire computer from a clean operating system install and have not had the issue since

**Comment by kisak-valve** [comment]
Thanks for retesting @CodeAndLoathing. Closing as fixed some time ago.
