### ISSUE TITLE
Frequent disconnection from Steam CMs

### ISSUE THREAD

**Issue by Thordin** [ValveSoftware/steam-for-linux#6375]
#### Your system information

* Steam client version (build number or date): 2019-06-12 15:21:58
* Distribution (e.g. Ubuntu): Ubuntu 18.04 x64 Linux 4.15.0-52-generic
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:

We are running some TF2 servers and they keep disconnecting from Steam CMs every couple of hours, especially during the weekends and during the day time. This is happening on multiple hosts and rarely happened to us before this month (which happens to also be the start of summer vacation for most people) so I think this is a problem with Steam and not our servers.

I have noticed the SEND-Q in netstat for this connection will stop at some high number.  During this time we will still be receiving packets from the Steam CM and our server ACKs them, but I don't see any data packets going from our server to the Steam CM. Then some few seconds later it will open a new connection to another CM. Sometimes we will get a RST packet from the Steam CM.

Here are some logs.

https://pastebin.com/raw/Jxn1AYY3

This is a problem because people are unable to use their loadout until they reconnect. They don't know they can reconnect, or they connect to a different server and find that the item server works on another server and blame us for this problem. 

I think the CMs might be overloaded, or something was recently changed with them to cause frequent disconnects, maybe a new firewall setting? The CMs should be fixed and TF2 should be fixed so that reconnecting back to the CM will re-enable user loadouts without asking them to reconnect.

#### Steps for reproducing this issue:

1.  Run a busy TF2 server that has people connecting/disconnecting and changing loadouts. The probability of a disconnection seems to increase on weekends/daytime and the speed at which people leave/join the server and change loadouts.
2.  Observe disconnections to Steam CM throughout the day at steam/logs/connection_log_27015.txt

#### Things we have tried:

* Disabling TCP SACK
* Disabling TCP Window Scaling
* Removing all firewall rules
* Making a hosts entry to have the server connect to a CM in Europe. It appears to reduce disconnects, but not eliminate them entirely.

**Comment by kisak-valve** [comment]
Hello @Thordin, 4.15.0-52-generic is known to be affected by a kernel regression in the TCP stack that is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6326. Please update your system, in particular to the 4.15.0-54-generic kernel build and retest.

**Comment by Thordin** [comment]
I will try rebooting the server for the upgrade later. But is this really related? 

The servers have been able to connect to the steam servers, they just randomly disconnect.
