### ISSUE TITLE
Double click on tray does not restore Steam window

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#6377]
#### Your system information

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2
* Distribution (e.g. Ubuntu): Ubuntu 19.04 (64 бит)
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Operating System: Kubuntu 19.04
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.0-20-generic
OS Type: 64-bit
Processors: 20 × Intel® Core™ i9-7900X CPU @ 3.30GHz
Memory: 31,1 GiB of RAM

Double left button click on tray icon does not restore Steam window  in KDE. it is possible to show steam windows only if to click right button and choose any option in popup menu.
I expected to see Steam Window on left click on tray icon.

#### Steps for reproducing this issue:

1. Install Steam 
2. Start Steam 
3. Logon to steam
4. Close window
5. Double click on tray icon
6. Nothing happens

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, this feature request is already being tracked at #3519 and #4836. Closing in favor of the existing issue reports.
