### ISSUE TITLE
D9VK integrated into Proton

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6378]
* Steam client version (build number or date):  July 9 2019
* Distribution (e.g. Ubuntu):   Arch
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No]  Yes

It would be very beneficial to have D9VK integrated into Proton. The performance improvements over the normal Wine OpenGL wrapper is tremendous. Vulkan really is the way to go for translating D3D calls. Please consider moving over to D9VK in the future.

**Comment by kisak-valve** [comment]
Hello @shoober420, this feature request is already being tracked at https://github.com/ValveSoftware/Proton/issues/102. Closing in favor of the existing issue report.
