### ISSUE TITLE
Copying launch options from game properties is finicky

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6380]
* Steam client version (build number or date): July 8 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

#### Please describe your issue in as much detail as possible:

When trying to copy and paste launch options from the game properties menu, if you move your cursor downward past the slim rectangle box where the text is, it will undo what was highlighted in front of the text, and only highlight whats behind it (to the right). It will also make your command string jump to the back of the line when you move the cursor downward paste the text. I'm not sure if this is an issue with Steam or SDL2, but its a pain in the pooper.

Its very odd behavior, and hard to explain. Its like if you move the cursor up above the text, it copies everything to the right, and when you move the cursor below the text, it copies everything to the left. So even if you started from the beginning of the string from the left side, while you are highlighting while the cursor is above the text, if you move the cursor below the text, what was highlighted disappears. Its very noticeable if you have a long string of launch options like me for games.

LD_PRELOAD='/usr/lib32/libSDL2.so /usr/lib32/libopenal.so /usr/lib/libSDL2.so /usr/lib/libopenal.so /usr/lib64/libSDL2.so /usr/lib64/libopenal.so' %command% -clientport 65007 -console -forcenovsync -fullscreen -gl_enablesampleobjects -h 768 -high -nobots -noff -noforcemaccel -noforcemspd -nohltv -nojoy -nostartupsound -nosteamcontroller -novid -preload -refresh 155 -refreshrate 155 -freq 155 -threads 4 -tickrate 128 -w 1024

#### Steps for reproducing this issue:

1. Open the Game Properties menu and go to launch properties
2. Attempt to highlight the text
3. Move the cursor down below the text while highlighting and it will start glitching

**Comment by kisak-valve** [comment]
Hello @shoober420, are you still experiencing this issue on an up to date system?

**Comment by shoober420** [comment]
The behavior for dragging and highlighting text for copy and pasting is normal now. Thank you.
