### ISSUE TITLE
Steam client won't open

### ISSUE THREAD

**Issue by y-the-alien** [ValveSoftware/steam-for-linux#6382]
#### Your system information

* Steam client version (17/06/2019): 
* Distribution (Ubuntu 19.04): 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Client won't start from clicking it's icon or from using steam @ terminal. No output is showed on terminal.

Installation isn't fresh so I believe that some update broke the client.

#### Steps for reproducing this issue:

1. Open terminal
2. Type steam and pressing enter

1. Left clicking steam icon on programs bar

The client runs if I use this command on terminal: ~/.local/share/Steam/steam.sh 

<details><summary>And outputs the following:</summary><p>

pedro@desktop:~$ ~/.local/share/Steam/steam.sh 
rm: não foi possível remover '/home/pedro/.steam/steam': É um diretório
rm: não foi possível remover '/home/pedro/.steam/bin': É um diretório
Running Steam on ubuntu 19.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-07-11 18:51:28] Startup - updater built Jun 17 2019 23:31:08
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
[2019-07-11 18:51:28] Verificando a instalação...
[2019-07-11 18:51:28] Verification complete
Gtk-Message: 18:51:28.358: Failed to load module "gail"
Gtk-Message: 18:51:28.359: Failed to load module "atk-bridge"

(steam:5791): Gtk-WARNING **: 18:51:28.362: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:5791): Gtk-WARNING **: 18:51:28.363: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",
/usr/share/themes/Yaru/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1560817063)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
[0711/185128.630006:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: browser
[0711/185128.643880:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0711/185128.643957:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1559604844
[0711/185128.643963:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0711/185128.643977:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
CApplicationManagerPopulateThread took 21 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)

** (steam:5791): WARNING **: 18:51:28.872: Unknown device type 14

** (steam:5791): WARNING **: 18:51:28.872: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type
Installing breakpad exception handler for appid(steam)/version(1560817063)
CAppInfoCacheReadFromDiskThread took 273 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1560817063)
Opted-in Controller Mask for AppId 0: f

** (steam:5791): WARNING **: 18:51:29.162: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'hidden'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.162: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.163: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.163: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.163: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.165: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'hidden'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.165: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.165: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.165: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.166: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'hidden'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.166: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.166: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.167: Ignoring invalid property 'autoconnect-priority'

** (steam:5791): WARNING **: 18:51:29.167: Unknown setting 'proxy'

** (steam:5791): WARNING **: 18:51:29.167: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.167: Ignoring invalid property 'address-data'

** (steam:5791): WARNING **: 18:51:29.167: Ignoring invalid property 'route-data'

** (steam:5791): WARNING **: 18:51:29.167: Ignoring invalid property 'address-data'
Installing breakpad exception handler for appid(steam)/version(1560817063)

(steam:5791): Gtk-WARNING **: 18:51:29.537: gtk_disable_setlocale() must be called before gtk_init()
Fossilize INFO: Overriding serialization path: "/home/pedro/.steam/steam/shader_cache_temp_dir_vk_64/steamapprun_pipeline_cache".
roaming config store loaded successfully - 14492 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
[0711/185133.387794:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
[0711/185133.434920:WARNING:crash_reporting.cc(281)] Failed to set crash key: UserID with value: 0
[0711/185133.435001:WARNING:crash_reporting.cc(281)] Failed to set crash key: BuildID with value: 1559604844
[0711/185133.435008:WARNING:crash_reporting.cc(281)] Failed to set crash key: SteamUniverse with value: Public
[0711/185133.435012:WARNING:crash_reporting.cc(281)] Failed to set crash key: Vendor with value: Valve
[0711/185133.435578:INFO:crash_reporting.cc(242)] Crash reporting enabled for process: gpu-process
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/pedro/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 5.87 seconds
[0711/185134.210520:INFO:crash_reporting.cc(265)] Crash reporting enabled for process: renderer
JS method call WebChat.GetWebChatLanguage with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call WebChat.GetSignIntoFriendsOnStart with 1 arguments
JS method call WebChat.GetCurrentUserAccountID with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call WebChat.GetWebChatURL with 1 arguments
Installing breakpad exception handler for appid(steam)/version(1560817063)
CAPIJobRequestUserStats - Server response failed 2
Installing breakpad exception handler for appid(steam)/version(1560817063)
JS method call FriendSettings.RegisterForSettingsChanges with 1 arguments
JS method call WebChat.RegisterForPushToTalkStateChange with 1 arguments
JS method call WebChat.SetVoiceChatActive with 1 arguments
JS method call WebChat.RegisterForComputerActiveStateChange with 1 arguments
JS method call WebChat.RegisterForFriendPostMessage with 1 arguments
JS method call Messaging.RegisterForMessages with 2 arguments
JS method call Messaging.RegisterForMessages with 2 arguments
JS method call Messaging.RegisterForMessages with 2 arguments
JS method call SharedConnection.AllocateSharedConnection with 1 arguments
JS method call WebChat.RegisterOverlayChatBrowserInfoChanged with 1 arguments
JS method call FriendSettings.GetEnabledFeatures with 1 arguments
JS method call SharedConnection.SubscribeToEMsg with 2 arguments
JS method call SharedConnection.SubscribeToClientServiceMethod with 2 arguments
JS method call SharedConnection.RegisterOnLogonInfoChanged with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
JS method call Parental.RegisterForParentalSettingsChanges with 1 arguments
JS method call Broadcast.RegisterForBroadcastStatus with 1 arguments
JS method call Broadcast.RegisterForViewerRequests with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.RegisterOnMessageReceived with 2 arguments
JS method call SharedConnection.SendMsg with 2 arguments
JS method call WebChat.GetPushToTalkEnabled with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call Storage.GetString with 2 arguments
JS method call Storage.GetString with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
Installing breakpad exception handler for appid(steam)/version(1560817063)
JS method call SharedConnection.SendMsg with 2 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
JS method call WebChat.SetNumChatsWithUnreadPriorityMessages with 1 arguments
JS method call Messaging.PostMessage with 4 arguments
JS method call Storage.GetString with 2 arguments
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments

</p></details>

**Comment by kisak-valve** [comment]
Hello @y-the-alien, are you using the distro-provided Steam package or the Valve-provided Steam package? Your terminal spew has conflicting hints and they have incompatible folder layouts

If you move `~/.steam` and `~/.local/share/Steam` somewhere safe and run `steam` to get the Steam client to re-bootstrap, does it start up?

**Comment by y-the-alien** [comment]
What I just did:
1. Renamed ~./steam and ~/.local/share/Steam
2. Run steam on terminal, the client is updated and seems to be working fine.

So, what was happening?

**Comment by kisak-valve** [comment]
Glad to hear you got it working. There's a good chance you switched either intentionally or accidentally between the Valve-provided steam package and the distro-provided steam package, then the launcher script at /usr/bin/steam tripped over itself when asked to deal with a folder layout it didn't setup due to differences between the packages. Luckily, since you didn't delete the previous steam folders, you could compare it to the working install, but that's largely an academic exercise as you've already gotten a working result.
