### ISSUE TITLE
Steam opened 111 "steamwebhelper" processes

### ISSUE THREAD

**Issue by pedrofleck** [ValveSoftware/steam-for-linux#6386]
#### Your system information

* Steam client version (build number or date): 1560817063
* Distribution (e.g. Ubuntu): Fedora 30
* Opted into Steam client beta?: No
* Have you checked for system updates?: System is up-to-date.

#### Please describe your issue in as much detail as possible:
Steam is creating a lot of "steamwebhelper" processes (I killed 111 of them) and was using almost 2GB of RAM (which is a problem when you have just 8GB). When I closed Steam, the processes didn't close and I had to kill them.

#### Steps for reproducing this issue:
I don't know exactly how to reproduce, but I usually start Steam with big picture and open a game, play for like 30min to 2 hours and then I check the processes and there are a lot of them. Now, I just opened Steam before writing this and it started with 4 steamwebhelper processes, now there are 17 of them and I didn't even opened any store page or played a game, it has 4 "steam" processes too, and one of them have 25% of CPU usage and the RAM usage grow 1,2GB.

**Comment by kisak-valve** [comment]
Hello @pedrofleck, are you still experiencing this issue on an up to date system?

**Comment by pedrofleck** [comment]
@kisak-valve not that I have noticed but since I posted this I upgraded my RAM, but it still uses more RAM and creates more processes than I like but nothing to be considered a bug.
