### ISSUE TITLE
SteamLink buttons almost not visble

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#6388]
#### Your system information

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2

* Distribution (e.g. Ubuntu): Ubuntu 19.04 (64 бит)

* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

Remote play binding buttons almost not visible. Issue illustrated on screenshot
![RemotePlayButtonBugIssue](https://user-images.githubusercontent.com/22169129/61174589-9f746080-a5a2-11e9-9334-5ded6ba1e70c.png)
#### Steps for reproducing this issue:

1. Install Steam for linux
2. Open settings
3. Choose Remote Play

**Comment by kisak-valve** [comment]
Related to #6271.

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, are you still experiencing this issue on an up to date system?

**Comment by jpVm5jYYRE1VIKL** [comment]
Hi nope anymore

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
