### ISSUE TITLE
Store quick search popup block store quick search

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#6389]
#### Your system information

* Steam client version (build number or date): jenkins-steam-runtime-beta-release_0.20190320.2
* Distribution (e.g. Ubuntu): Ubuntu 19.04 (64 бит)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
If you start to use quick search in store search result suggestion appears on top of search form and take focus. Due to it search blocked.

![shopsearch_bug2](https://user-images.githubusercontent.com/22169129/61176360-d73dd100-a5bf-11e9-8884-c6b2a3c245e8.png)

#### Steps for reproducing this issue:

1. Install Steam
2. Go to Store window
3. start to use search form

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, I wasn't able to reproduce the overlap with my ubuntu 19.04 and another test box. If you find anything else needed to reproduce you issue, please add it.

**Comment by jpVm5jYYRE1VIKL** [comment]
Hi. Look like. Russian version of steam gui affected only.

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, are you still experiencing this issue on an up to date system?

**Comment by jpVm5jYYRE1VIKL** [comment]
Hi, Issue not observed anymore

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
