### ISSUE TITLE
Linux missing big picture overlay when using a controller setting

### ISSUE THREAD

**Issue by pedrofleck** [ValveSoftware/steam-for-linux#6393]
#### Your system information

* Steam client version (build number or date): 1560817063
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When using Steam on Windows, there are this setting: ""Use Big Picture Overlay when using a Steam Controller from the desktop" that is missing from the Linux client.

#### Steps for reproducing this issue:

1. Go to Steam -> Settings -> In-Game and try to check the "Use Big Picture Overlay when using a Steam Controller from the desktop" setting like in Windows.

**Comment by kisak-valve** [comment]
Probably due to #4309.

**Comment by kisak-valve** [comment]
Hello @pedrofleck, this option was added some time ago. Closing as outdated.
