### ISSUE TITLE
Steam Cloud unavailable

### ISSUE THREAD

**Issue by Adenis890** [ValveSoftware/steam-for-linux#6394]
#### Your system information
Ubuntu 19.04
i5-7400
1050ti
8gb Ram

* Steam client version (build number or date): July 11 2019, at 22:28:23
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Whenever i try to upload a screenshot, Steam Cloud says that is temporarily unavailable. This issues started happening around 1 month ago. It's really annoying. Here is the cloud log:
[cloud_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3396736/cloud_log.txt)

**Comment by kisak-valve** [comment]
Hello @Adenis890, what kernel version are you running? (`uname -a`)

**Comment by Adenis890** [comment]
> Hello @Adenis890, what kernel version are you running? (`uname -a`)

Hello there, i am running 5.0.0-19-generic #20-Ubuntu SMP Wed Jun 19 17:04:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kisak-valve** [comment]
5.0.0-19 has a known issue which is being tracked at #6326. This has already been fixed in the distro's kernel release. Please update your system and retest.

**Comment by Adenis890** [comment]
> 5.0.0-19 has a known issue which is being tracked at #6326. This has already been fixed in the distro's kernel release. Please update your system and retest.

The other kernel 5.0.0-20 is broken for me so i'll have to wait for another kernel release. My system is up to date right now. I'm just not running latest kernel since it's broken.

**Comment by byte1024** [comment]
Should be able to close this as you shouldn't have a problem with any kernel starting from that one. It should be fixed via (Ubuntu 19.04) 5.0.0-20 (more precisely 5.0.0.20.21):

> interfered with networking applications that setup very low SO_SNDBUF values. This update fixes the problem.

https://linuxsecurity.com/advisories/ubuntu/ubuntu-4041-1-linux-kernel-update-01-29-09

**Comment by Adenis890** [comment]
> Should be able to close this as you shouldn't have a problem with any kernel starting from that one. It **was** fixed via (Ubuntu 19.04) 5.0.0-20 (more precisely 5.0.0.20.21) - if it worked for one it should work for all:
> 
> > interfered with networking applications that setup very low SO_SNDBUF values. This update fixes the problem.
> 
> https://linuxsecurity.com/advisories/ubuntu/ubuntu-4041-1-linux-kernel-update-01-29-09

Ok i will. Thanks for helping guys i will wait for the next kernel!
