### ISSUE TITLE
steamui.so: undefined symbol: SDL_RWclose with Solus native runtime

### ISSUE THREAD

**Issue by bkdwt** [ValveSoftware/steam-for-linux#6396]
#### Your system information

* Steam client version (build number or date): 1563306518 
* Distribution (e.g. Ubuntu): Solus 4 with Gnome
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hi. I received an update notification from the Steam and installed it. When rebooting the steam, the following error occurs:

https://gist.github.com/bkdwt/ca8c6509eeb5dd9d5dcee6d0e39034a4

#### Steps for reproducing this issue:

1. Update the steam beta client for the today release (07/16/2019) on Solus (I don't know if this happen with others distros)
2. Restart the client

**Comment by kisak-valve** [comment]
Hello @bkdwt, this is an issue with Solus's Linux Steam Integration and the use of their native runtime option.

It's been noted at https://discuss.getsol.us/d/1583-steam-will-not-launch-with-use-native-runtime-in-the-integration-app-engaged / https://www.reddit.com/r/SolusProject/comments/c5zlpb/psa_latest_steam_beta_is_wont_start/.

**Comment by bkdwt** [comment]
Hey @kisak-valve, many thanks! I'll try this. ;)
