### ISSUE TITLE
Steam doesnt store account cridentials after todays update

### ISSUE THREAD

**Issue by Qik000** [ValveSoftware/steam-for-linux#6397]
#### Your system information

* Steam client version (build number or date): 17/07/2019
* Distribution (e.g. Ubuntu): Ubutnu 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam doesnt sotre my account cridentials as well as my language setting, previously i fixed it with chmod -w registry.vdf but after todays updtate that no longer works

#### Steps for reproducing this issue:

1. Login
2. try to set remember password or langiage
3. restart steam

**Comment by kisak-valve** [comment]
Hello @Qik000, this issue is already being tracked at #5030. Closing as a duplicate.
