### ISSUE TITLE
steam.sh: line 720:  2121 Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by alexandru-calinoiu** [ValveSoftware/steam-for-linux#6399]
#### Your system information

* Steam client version (build number or date): 1.0.0.61
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:

When starting steam using the nvidia discret graphic card I get:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  152
Serial number of failed request:  55
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  54
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  56
xerror_handler: X failed, continuing
crash_20190717221012_1.dmp[2163]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190717221012_1.dmp
/home/calin/.local/share/Steam/steam.sh: line 720:  2121 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190717221012_1.dmp[2163]: Finished uploading minidump (out-of-process): success = yes
crash_20190717221012_1.dmp[2163]: response: CrashID=bp-05c68828-5eba-4eac-9633-049f62190717
crash_20190717221012_1.dmp[2163]: file ''/tmp/dumps/crash_20190717221012_1.dmp'', upload yes: ''CrashID=bp-05c68828-5eba-4eac-9633-049f62190717''
```

#### Steps for reproducing this issue:

1. Install arch
2. Install latest nvidia
3. Start steam

##### Notes

I've tried the fix here https://github.com/ValveSoftware/steam-for-linux/issues/3863 with no luck

**Comment by kisak-valve** [comment]
Hello @alexandru-calinoiu, this reads like you do not have a sane OpenGL driver install.

Please verify you have `nvidia-dkms`, `nvidia-utils`, and `lib32-nvidia-utils` installed and that they are all paired versions. The fact that steam is trying to use swrast means that your system is trying to use mesa's libGL.so with the nVidia proprietary driver, which is incompatible.

**Comment by alexandru-calinoiu** [comment]
Apparently I did not had `lib32-nvidia-utils` installed and this triggered the failure. Fix was to simply install it.

**Comment by kdomanski** [comment]
That's no fix. Steam should report the lack of a needed tool instead of segfaulting with no explanation. Please reopen.

**Comment by flavienbwk** [comment]
Please reopen, issue still persists.
