### ISSUE TITLE
Alt+Tab from streaming game is broken on Ubuntu and Arch Linux in Gnome

### ISSUE THREAD

**Issue by dmp1ce** [ValveSoftware/steam-for-linux#6401]
* Steam client version (build number or date): Most recent stable version. I don't know how to find the build number or date. :-1: 
* Distribution (e.g. Ubuntu):  Arch Linux and Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

When in a streaming game and I `Alt+Tab` to another program and then `Alt+Tab` back into the game, the game is locked and unplayable. I can forcefully close the window in Gnome but that will also close the game.

Before this version of Steam I was able to `Alt+Tab` just fine.

See screenshot for what my game looks like when I `Alt+Tab` back.

![Screenshot from 2019-07-18 11-42-48](https://user-images.githubusercontent.com/58784/61473311-2aaf7680-a954-11e9-8b57-c567a539020b.png)

#### Steps for reproducing this issue:

1. Start streaming game
2. `Alt+Tab` into another window such as Firefox
3. `Alt+Tab` back into the game.
4. Notice the game is no longer responding.

**Comment by Myrddin-Wyllt** [comment]
For what its worth, in Steam Beta on Arch; I've never had an issue & this includes playing non-steam games via streaming. It's possible this issue doesn't exist in Steam beta.

I'm using the KDE desktop though, so perhaps this is GNOME specific?

I don't plan on using GNOME, so perhaps someone who does could elaborate. Is the issue with Steam stable or GNOME?

**Comment by dmp1ce** [comment]
Yeah. I've tried Firefox (used to play Roblox) and Hyper Light Drifter.

**Comment by dmp1ce** [comment]
I tested with the beta on the client side and I still see the same issue. Maybe it is related to Gnome.

**Comment by LaurentDumont** [comment]
I do see the same issue with 
Ubuntu 19.04
Gnome 3.32

The game still appears to be running but alt-tab crashes the streaming client and requires a `kill` or a stream session restart to get going again.

**Comment by macktab** [comment]
Same issue.

[steam-remote-play-issue.zip](https://github.com/ValveSoftware/steam-for-linux/files/3804351/steam-remote-play-issue.zip)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by dmp1ce** [comment]
I just tried on Arch Linux streaming from Windows 10 and it seems to be working fine with Alt+Tabing now. 👍

I didn't test on Ubuntu.

**Comment by kisak-valve** [comment]
Thanks for retesting @dmp1ce. Closing as fixed some time ago.
