### ISSUE TITLE
Clicking item in downloads no longer brings it up in your library

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6402]
#### Your system information

* Steam client version (build number or date): july 17th
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

You used to click a game in your download queue, to have it bring it up directly in your library. Now it doesn't.

#### Steps for reproducing this issue:

Click a game from your downloads list, just opens the library on the last game you had selected instead of that game.

Same issue as here: https://github.com/ValveSoftware/steam-for-linux/issues/6371 but it's not fixed for me.

**Comment by barfin** [comment]
try beta version see if it's fixed
![image](https://user-images.githubusercontent.com/37030489/61529331-4f7c1a80-aa36-11e9-8658-f0793f2e76dc.png)

**Comment by LiamDawe** [comment]
Yeah that seems to work, cheers.
