### ISSUE TITLE
Free To Play games don't get added to library if "Play Game" fails. 

### ISSUE THREAD

**Issue by se5a** [ValveSoftware/steam-for-linux#6403]
#### Your system information

* Steam client version (build number or date): Jul 17 1019 
* Distribution (e.g. Ubuntu):  Mint 19 Cinnamon
* Opted into Steam client beta?: [Yes/No]: No.
* Have you checked for system updates?: [Yes/No] Yes/irrelevent. 

#### Please describe your issue in as much detail as possible:
Attempting to try windows only games using proton on free to play games is impossible due to ftp games not getting added to the client library. 

#### Steps for reproducing this issue:

1. Find a windows only FTP game. 
2. Try to add it to the library, "Play Game" button
3. Error about unsuported operating system (expected)
4. go to steam client library to enable steam play/proton version.
5. game does not exist in library.

This is related to #3331  and #6348, but defines a use case where the current behaviour is problematic.

**Comment by se5a** [comment]
Is there a work around for this?

**Comment by kisak-valve** [comment]
Hello @se5a, this was previously discussed on #6115. Enabling Proton for all titles will allow you to try to use the Free to Play game with Proton.

**Comment by se5a** [comment]
Ah, thanks, that's a lot more help than I got from official steam support which was basically "You're not running Ubuntu, we don't care"

Still, I hope the issue gets addressed in #3331 the whole thing is a bit of bad UX.
