### ISSUE TITLE
steamui.so: undefined symbol: SDL_RWclose with Solus native runtime

### ISSUE THREAD

**Issue by Codified-Vexing** [ValveSoftware/steam-for-linux#6407]
#### Your system information

* Steam client version (build number or date): The latest?
* Distribution (e.g. Ubuntu): Solus OS
* Opted into Steam client beta?: NO
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
It happened after Steam restarting from an automatic update. The relaunch failed and trying to manually launch keeps failing the same way.
It tries checking for updates and pops an alert messages like
`Fatal Error: Failed to load steamui.so`
In the terminal the following displays:
https://gist.github.com/Codified-Vexing/121f1b75bcd60658bee5ec4f9421aa1b

#### Steps for reproducing this issue:
I can't tell. It just updated one day and hasn't launched successfully ever since.

**Comment by kisak-valve** [comment]
Hello @Codified-Vexing, please give https://github.com/ValveSoftware/steam-for-linux/issues/6396#issuecomment-512075886 a read. This is an issue with Solus's Linux Steam Integration project with the native runtime enabled.

**Comment by Codified-Vexing** [comment]
Disabling the integration worked. But then I checked if there was an update for that future, which was true. After updating the integration and re-enabling, Steam worked again.
