### ISSUE TITLE
Requires old dbus-glib

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6416]
* Steam client version (build number or date): July 18 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Steam requires the old legacy “glib” versions of libnm (libnm-glib) and dbus (dbus-glib). They’re no longer officially supported.

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/1de8383ad9fdfc8f552117e5d109bdfa7005634b

https://dbus.freedesktop.org/doc/dbus-glib/

Please update Steam to use the modern libnm package, and to no longer require dbus-glib. Thank you.

#### Steps for reproducing this issue:

1. Uninstall libnm-glib, lib32-libnm-glib, dbus-glib, and lib32-dbus-glib
2. Keep networkmanager, libnm, lib32-libnm, dbus, and lib32-dbus installed
3. Steam will still crash

**Comment by kisak-valve** [comment]
Hello @shoober420, there's already a request to look into dropping the hard dependency on libnm-glib at #3129, so this issue report should only focus on dbus-glib.

These libraries are provided by the Steam runtime and running Steam with the runtime disabled is unsupported. With the Steam runtime enabled, can you attach a [gist](https://gist.github.com) of `/tmp/dumps/<username>_stdout.txt` after reproducing the crash you are seeing?

**Comment by shoober420** [comment]
This is about also dropping the dbus-glib hard dependency, since they both depend on eachother. Steam runs with dbus-glib installed, this is about having it run without both libnm-glib and dbus-glib.

**Comment by shoober420** [comment]
Legacy dbus-glib vulnerabilities.

https://www.cvedetails.com/vulnerability-list/vendor_id-7971/product_id-19912/Freedesktop-Dbus-glib.html

**Comment by kisak-valve** [comment]
Hello @shoober420, Steam is no longer linked against this library.

**Comment by shoober420** [comment]
I can confirm that the legacy dbus-glib isn't required, thank you.
