### ISSUE TITLE
Steam profile is always offline

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#6418]
#### Your system information

* Steam client version (build number or date): 1563346602
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
My steam profile always remain offline. When I try to make it online by going to Friend menu and clicking online, it does not work.

**Comment by qmmp123** [comment]
Can you open friend list? I had the same issue recently. I launched steam via terminal and found problem with library libprce

**Comment by kisak-valve** [comment]
Possibly related to https://bugs.archlinux.org/task/62095.

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
