### ISSUE TITLE
Please add choice for supported platforms. There are mods on Stream that require the original game for Windows on Linux

### ISSUE THREAD

**Issue by gaal-dev** [ValveSoftware/steam-for-linux#6421]
#### Your system information

* Steam client version (latest Steam beta): 
* Distribution (Ubuntu 19.04): 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

Half-Life: Before requires Half-Life game for Windows on Linux. I launched this mod using steamcmd, but it was not trivial.

https://store.steampowered.com/app/261980/HalfLife_Before/

**Comment by kisak-valve** [comment]
Hello @gaal-dev, this reads like #6036. Closing in favor of the existing feature request.
