### ISSUE TITLE
Intermittent Steam Tray Menu Popup without User Input

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [ValveSoftware/steam-for-linux#6423]
#### [Your system information](https://gist.github.com/Myrddin-Wyllt/4cc23dfec5512efc59b4d93336a6d36b)
* Steam client version (build number or date): Aug 6 2019
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm uncertain whether this issue lies with KDE's kwin or Steam's tray icon, but about 3-5 times a day; the Steam Desktop client will become unresponsive for a moment before the Tray menu pops up without being clicked. It happens when switching windows on the taskbar. I suspect the issue is related to compositing, but I can't be sure. I do have some compositing blocks set up through kwin for certain Steam windows so that the right-click isn't invisible (separate issue), so this could be related. While I was reporting this issue it happened ~3 times where clicking on the taskbar is stolen by the Steam Tray icon.
<details><summary>My ~/.config/kwinrulesrc file contents:</summary>
<pre>
[1]
Description=Steam Keyboard
above=true
aboverule=3
acceptfocus=false
acceptfocusrule=2
clientmachine=localhost
clientmachinematch=0
fsplevel=4
fsplevelrule=2
noborder=true
noborderrule=3
skippager=true
skippagerrule=3
skipswitcher=true
skipswitcherrule=3
skiptaskbar=true
skiptaskbarrule=3
title=Steam Keyboard
titlematch=1
wmclass=steam
wmclasscomplete=false
wmclassmatch=1

[2]
Description=Steam Properties
blockcompositing=true
blockcompositingrule=2
clientmachine=localhost
clientmachinematch=0
title=Properties
titlematch=2
types=1
wmclass=steam
wmclasscomplete=false
wmclassmatch=1

[3]
Description=Steam Information
blockcompositing=true
blockcompositingrule=2
clientmachine=localhost
clientmachinematch=0
title=Information
titlematch=2
wmclass=steam
wmclasscomplete=false
wmclassmatch=1

[4]
Description=Steam Settings
blockcompositing=true
blockcompositingrule=2
clientmachine=localhost
clientmachinematch=0
title=Settings
titlematch=1
wmclass=steam
wmclasscomplete=false
wmclassmatch=1

[Directories]
dir_pixmap[$d]

[General]
BrowserApplication[$d]
ColorScheme[$d]
Name[$d]
count=4
fixed[$d]
font[$d]
menuFont[$d]
shadeSortColumn[$d]
smallestReadableFont[$d]
toolBarFont[$d]

[Icons]
Theme[$d]

[KDE]
ChangeCursor[$d]
ColorScheme[$d]
LookAndFeelPackage[$d]
contrast[$d]
widgetStyle[$d]

[KFileDialog Settings]
Breadcrumb Navigation[$d]

[Paths]
Trash[$d]

[PreviewSettings]
MaximumSize[$d]
camera[$d]
file[$d]
fonts[$d]
</pre>
</details>

Someone using Gnome, Xfce, LXQt, MATE, Cinnamon, et al. could help by corroborating this is indeed a Steam Tray issue.

#### Steps for reproducing this issue:

0. Use KDE with window rules as above? (unsure whether this is necessary to reproduce)

1. Open many sub-windows & configuration windows within Steam
2. Switch between them and other system applications using the taskbar
3. Occasionally, the Tray menu will popup stealing focus

**Comment by kisak-valve** [comment]
Hello @Myrddin-Wyllt, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
