### ISSUE TITLE
libva-x11 manjaro linux error + FIX

### ISSUE THREAD

**Issue by Bodyash** [ValveSoftware/steam-for-linux#6427]
#### Your system information

* Steam client version (build number or date): 02.08.2019 (not sure, latelst)
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Steps for reproduce and fix this issue:

1. today i recieved updates for manjaro, installed all of them
2. launch steam -> got error

Failed to load steamui.so - dlerror(): /home/bohdan/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libva-x11.so.1: undefined symbol: fool_postp

https://i.imgur.com/POgnsw1.png

3. seems like something wrong with that lib

so i checked files. In this folder libva-x11.so.1 is symlink to libva-x11.so.1.3900.0
so i removed symlink to local libva-x11"
`rm libva-x11.so.1`

https://i.imgur.com/HczhlPu.png

and linked my system libva to this path
`ln -s /usr/lib32/libva-x11.so ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libva-x11.so.1`

https://i.imgur.com/s3QgsYW.png

And everything works again!

**Comment by Myrddin-Wyllt** [comment]
I've had no such issue on my Manjaro [unstable branch] install & I'm updated to the latest versions of everything. I believe your issue is because you weren't opted into the Steam beta. That's my only plausible explanation.

**Comment by kisak-valve** [comment]
Hello @Bodyash, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
