### ISSUE TITLE
Steam Input controller inconsistencies and freezing PC

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-for-linux#6428]
#### My system information

* Steam client version: August 2nd, 2019
* Distribution: Ubuntu 18.04.2
* Opted into Steam client beta? Yes
* Have you checked for system updates? Yes

#### Problem description

I've got 2 controllers: a wired XBox 1 pad and a PS1 controller plugged into a DInput USB adapter.  For the latter, I've set up button mapping in Big Picture. I've tested the following with the native Disgaea 2 demo.

To get the XB1 pad working, I need to have Steam Input disabled for those in the Steam controller options, otherwise the game doesn't register any input from the pad.

To get the DInput pad working, I have to enable Steam Input or no input will be registered at all. If I don't launch the game through Big Picture but desktop Steam, the button mapping will be the default one, not how I set it up in BP.

This is consistent with other games, except that in some I can't get the PS1 pad to work at all (Yakuza 0 for example). Maybe because they don't support DInput at all? Or don't actually use the Steam Input API?

P.S.: While both controllers are connected and having the game running, the PC will freeze, if I open the Steam controller options with the XB1 pad and then open up the "XInput controller order" with the other pad. But even if I open it with the XB1 pad and it doesn't lock up, the dialog is always empty, not showing any controllers.

**Comment by Myrddin-Wyllt** [comment]
I'll agree that multiple controller order support could use some polish. With only Steam controllers, I even get the empty "Xinput Controller Order" screen. Most often it is with proton games, but it still happens with native titles as well. I've noticed with Steam controllers I need to press the Steam button once before the controller will register & this can be one cause to the empty controller order menu (i.e., but not the only cause, certain games won't show any xinput controllers). This needs to be done before entering a game & I wonder how controllers without a guide button react (i.e., Can these controllers register properly?). Perhaps this is related to your PS1 controller issue.

**Comment by serebit** [comment]
No Proton games detect my PS4 controller, on any Proton version, unless Linux Steam Integration (which uses native libraries instead of much of the Steam runtime) is enabled. Native games don't detect the controller either.

**Comment by DanMan** [comment]
Not sure why but this seems to work as expected now. Either due to one of the last few Steam updates or me installing the `steam-devices` package on Ubuntu - or both. My DInput pad now works with all games, without having to mess with the Input settings.
