### ISSUE TITLE
Steam is constantly logging that makes too many I/O tasks which freeze the entire OS

### ISSUE THREAD

**Issue by fxdave** [ValveSoftware/steam-for-linux#6431]
#### Your system information

* Steam client version (build number or date): 1.0.0.61-1
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I ran steam in terminal in order to see the output and to not write the log to the ssd.  
Here the [output](https://gist.github.com/fxdave/17b8db3d658f96a60a92d47373f5a2a5) is.

#### Steps for reproducing this issue:

1. start steam
2. play a buggy game
3. wait for system lock up

Yes I know this is also a CSGO and also a Linux issue, but if Steam stops writing to the journald (, because why would it? Steam is not something like a system process which has importance to log.), then I could run the steam normally without terminal.

**Comment by Myrddin-Wyllt** [comment]
Could you redirect all output from steam using the command:
<pre>steam > /dev/null 2>&1</pre>
Does the lockup still occur when launching steam this way?

I've been using Steam on Arch for months now without this ever occurring on multiple machines. I haven't yet tried CS:GO, but I've never seen games/steam directly log to journald. Could you show the output of: <pre>journalctl -b | grep steam</pre>

**Comment by fxdave** [comment]
If I launch it using Rofi I can not redirect the output. 
The output of the journalctl: 
https://gist.github.com/fxdave/2ec5d001c47f10be162a36dba2bc823b 

If I launch it by terminal, everything is fine.

Sidenote:
Heavy Parallel I/O tasks cause luck up. (I don't know why) May I should form an issue against linux kernel.

**Comment by fxdave** [comment]
I finally determined what causes the deadlock: my CPU temperature above 80 °C. I may clean the cooler.
Thanks for help.
