### ISSUE TITLE
Provide official Fedora/RedHat/CentOS installer

### ISSUE THREAD

**Issue by Luraktinus** [ValveSoftware/steam-for-linux#6432]
Steam only Supports Ubuntu, which is a unreliable distribution. (dropping 32bit without asking and then roll back because it was a bad idea).

Please Valve/Steam, support a distribution with a company that knows what they are doing!
Like RedHat/Fedora. They are easy to use, support Steam already and are very stable (CentOS even more so).

At least provide an official RPM installer.

[steam.rpm ZIP](https://github.com/ValveSoftware/steam-for-linux/files/3471810/steam.zip)

**Comment by dreamer** [comment]
Steam is already packaged in RPM Fusion repo, which is exactly the place where any Fedora/CentOS/RHEL user would look for it by default. Adding "official" support would not come with any real benefits to the users - only increased cost to Valve… so what's the point?

Also, IIRC when asked for their stance on gaming, Red Hat CEO responded that they want to focus on developers and creators, not the gamers.

**Comment by Myrddin-Wyllt** [comment]
> ["... The Linux landscape has changed dramatically since we released the initial version of Steam for Linux, and as such, we are re-thinking how we want to approach distribution support going forward. There are several distributions on the market today that offer a great gaming desktop experience such as Arch Linux, Manjaro, Pop!_OS, Fedora, and many others. We'll be working closer with many more distribution maintainers in the future. If you're working on such a distribution and don't feel your project has a direct line of contact with us, by all means, have a representative reach out directly. ..."](https://steamcommunity.com/app/221410/discussions/0/1640915206447625383/)
--Pierre-Loup Griffais

**Comment by kisak-valve** [comment]
Hello @Luraktinus, this feature request is already being tracked at #4480. Closing in favor of the older request.
