### ISSUE TITLE
Feature Request. Steam without shell.

### ISSUE THREAD

**Issue by qmmp123** [ValveSoftware/steam-for-linux#6433]
I think a lot of people could notice that linux shells such as KDE, Gnome, Unity etc use a lot of system resources. It causes some problems with performance in games. We can use OpenBox to increase performance but I think that's not enough. What about start steam in Big Picture mode instead of shell?

**Comment by dreamer** [comment]
@qmmp123 there are several ways to accomplish this already - that's basically what SteamOS is. You can also try https://github.com/ShadowApex/steamos-ubuntu or https://github.com/gamer-os/gamer-os or I think there's an option to runt Steam BPM inside Kodi, etc…

**Comment by qmmp123** [comment]
@dreamer Oh. I will try it

**Comment by qmmp123** [comment]
@dreamer Or not. I dont want install another yet OS near with linux. If it requires install new Os I can install windows.

**Comment by dreamer** [comment]
steamos-ubuntu does not require you to install another OS. Neither does Kodi.

**Comment by qmmp123** [comment]
https://github.com/gamer-os/steamos-compositor-plus
I think I found solution
