### ISSUE TITLE
Unable to stream video from Fedora hosts

### ISSUE THREAD

**Issue by iko-deleted** [ValveSoftware/steam-for-linux#6434]
#### Your system information

* Steam client version (build number or date): Jul 17 2019
* Distribution (e.g. Ubuntu): Fedora 30
* Opted into Steam client beta?: No, but I checked and the bug also occurs in beta
* Have you checked for system updates?: Yes

- [system information](https://gist.github.com/cjenn/5df824436b2819464d6011edf826a7db)
- [stdout dump](https://gist.github.com/cjenn/cc4c47e5c4486e3cc0c5579548923334)
- [streaming log](https://gist.github.com/cjenn/cc4c47e5c4486e3cc0c5579548923334)
  - note that the last crash in here happened because I was moving the game window around on the host computer. This may be unrelated.
- [package manager logs](https://gist.github.com/cjenn/71b882974e884261599cf710c0925725)

#### Please describe your issue in as much detail as possible:
When attempting to use remote play from fedora hosts, the video doesn't work. The effect varies, but it's always completely unviewable. The game audio and control inputs work perfectly.

Sometimes the screen is shared correctly for a few seconds before the game is setup, but it glitches out as soon as the game window is created.

This issue started sometime in the last few days; I'm not too sure exactly when. I included the package manager logs as it was likely broken by a recent update.

I tried disabling hardware encoding but that didn't help.

#### Steps for reproducing this issue:

1. Update Fedora
2. Attempt to stream a game from the Fedora host
3. ???

Update 1: I tried to reproduce this in a vm, but it doesn't work by default. I'm going to test it with gpu passthrough.

Update 2: This doesn't occur streaming from with the tv as a host. (it also runs fedora 30)

**Comment by cjenn** [comment]
I should note that I tried disabling hardware endocing and it didn't work.

**Comment by cjenn** [comment]
Streaming works fine from the steam flapak; I'm just going to use that for now.

**Comment by cjenn** [comment]
This appears to be a GNOME specific issue.

I installed and then uninstalled a bunch of other DEs, just to test them out, and that fixed the problem for me.

**Comment by kisak-valve** [comment]
Hello @iko-deleted, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
