### ISSUE TITLE
steam client chat window ui is shifted to the left

### ISSUE THREAD

**Issue by at46** [ValveSoftware/steam-for-linux#6437]
#### Your system information

* Steam client version (build number or date): Aug 6 2019 um 01:15:16
* Distribution (e.g. Ubuntu): Debian/testing with xfce desktop
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Since the latest update the chat is shifted to the left. I can't see the cursor anymore and instead I've some black space on the right. See screenshot. I already restarted my system but with no success. I also tried minimizing/maximizing/resize the chat window with no success either.

![steam_chat](https://user-images.githubusercontent.com/6986646/62627263-5f966400-b929-11e9-9629-550b7a96e823.png)

#### Steps for reproducing this issue:

1. Open a chat window in the steam client form your friends list

**Comment by Nemoder** [comment]
Same issue here:
![screeny](https://user-images.githubusercontent.com/2366443/62755242-0b25de00-ba28-11e9-92e8-862aa2fef159.png)


The first time it happened I restarted the client and it was fixed but now it's happened again and restarts aren't fixing it.

**Comment by Lucki** [comment]
I can confirm this bug in the clients chat. This doesn't happen in the webchat.

**Your system information**

- Steam client version (build number or date): Aug 6 2019 um 01:15:16
- Distribution (e.g. Ubuntu): Arch Linux with Gnome desktop
- Opted into Steam client beta?: [Yes/No] Yes
- Have you checked for system updates?: [Yes/No] Yes

**Comment by NoXPhasma** [comment]
This happens in the beta client for quite some while, even in Steam Overlay this happens. However, it's random for me and closing the chat window and open it again seems to fix it once.

**Comment by StephenLynx** [comment]
Can confirm, ubuntu 18. I don't  think I opted into the beta.

**Comment by Termuellinator** [comment]
Can confirm - sometimes closing and reopening it helps, but more often than not the black edge+shift stays


    Steam client version (build number or date): 1565407153 / Aug 10 2019 um 02:00:27
    Distribution (e.g. Ubuntu): Manjaro KDE
    Opted into Steam client beta?: Yes
    Have you checked for system updates?:Yes

**Comment by Protonator** [comment]
Confirmed under Manjaro Cinnamon with Steam build 1565057304, too.

**Comment by JacobSvenningsen** [comment]
Experiencing this on Debian as well, and a friend of mine has experienced it too on Windows with the in-game overlay, so it doesn't seem to be a Linux-specific issue

**Comment by at46** [comment]
Bug seems to be gone. At least I can't remember when it occurred the last time for me and I couldn't reproduce it now with some testing. If no one else reports that the bug is still there for him I'm going to close this bug report within the next days.

**Comment by bladefox1337** [comment]
"export XDG_CURRENT_DESKTOP=gnome", helped me

**Comment by at46** [comment]
Can anyone still confirm this bug? I haven't had this for a long time now.

**Comment by Termuellinator** [comment]
I too haven't had it long enough that i actually forgot about it, would consider it fixed.

**Comment by at46** [comment]
Since no one posted here that he still has this bug I'm going to close it for now.
