### ISSUE TITLE
'rm' command missing the '-r' flag

### ISSUE THREAD

**Issue by Blaster84x** [ValveSoftware/steam-for-linux#6439]
#### Your system information

* Steam client version (build number or date): downloaded Aug 9, 2019
* Distribution (e.g. Ubuntu): Linux Mint (19.2 Cinnamon amd64)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected:
The Steam installer should run normally, display the EULA and install steam.

Current behavior:
Steam installer exits with the message "Couldn't set up Steam data, please contact technical support." When running `steam` in the terminal, this shows:
`rm: cannot remove '/home/blaster84x/.steam/steam': Is a directory`.
This is because of the `rm` command missing the `-r` option.

Possible solution:
Change the `rm ~/.steam/steam` command to `rm -r ~/.steam/steam` or `rm -rf ~/.steam/steam`.

#### Steps for reproducing this issue:

1. Download the .deb installer from the Steam website.
2. Run `steam` in the terminal.
3. Look at the command output after it returns error.

**Comment by kisak-valve** [comment]
Hello @Blaster84x, this is not a bug, `~/.steam/steam` has been a symlink when the folder layout is setup by the Valve-provided Steam package for years and the intent is to point the symlink to the current running steam install, but the Debian-provided Steam package historically sets up steam there.

Making this recursive would be a destructive change to Steam installs that were setup by any Debian-provided Steam package before 1.0.0.59 and should not be changed.

If you're switching between the Valve-provided Steam package and the Debian-provided Steam package, manually move `~/.steam` and `~/.local/share/Steam` somewhere out of the way before re-bootstrapping the client.
