### ISSUE TITLE
Big Picture Mode starts up when phrase is typed

### ISSUE THREAD

**Issue by N00byKing** [ValveSoftware/steam-for-linux#6441]
#### Your system information

* Steam client version (build number or date): Beta, 10.08.2019
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
So this is a weird one... Every time I type out the word "esc" anywhere in the client, Big Picture mode starts up. Using ``evtest`` I've already confirmed it's not a Keyboard error.
This does *not* happen on the latest stable Steam Version
#### Steps for reproducing this issue:

1. Connect Keyboard
2. Type "esc" (Doesn't need to be a text field, just the library even)
3. Profit!??!?!?

Keyboard in Question is a Wooting One, if relevant

**Comment by Myrddin-Wyllt** [comment]
I can't reproduce this, has it been fixed on your end by the recent updates? If it's gone, please close this issue.

Thanks for reporting!
