### ISSUE TITLE
Steam Chat window UI partially cut off and offset

### ISSUE THREAD

**Issue by Daniel-McCarthy** [ValveSoftware/steam-for-linux#6442]
#### Your system information

* Steam client version (build number or date): Packaging Number: 1565473496 Date: Aug 10 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [**Yes**/No]
* Have you checked for system updates?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
The UI for the Steam Chat is offset by 13 pixels to the left leaving a black bar on the right side and 13 pixels worth of UI not showing at all on the left side.

This always occurs. Restarting Steam and the computer does not help. This issue has also persisted through multiple updates (including the most recent version). This also occurs for me on the Windows client.

Resizing the window and or maximizing it does not help. Once it is done resizing it automatically adjusts to have 13 pixels of black bar on the right side.

I am happy to provide additional information. Sadly I am not sure how to make this occur. It started suddenly and has not gone away. I did not see when this issue started.

#### Steps for reproducing this issue:

1. Open Steam Friends window.
2. Right click any friend.
3. Left click Send Message to bring up Steam Chat.

___
The issue visually:
![Screenshot from 2019-08-09 19-29-50](https://user-images.githubusercontent.com/4957200/62828383-aa72de80-bbaa-11e9-9163-f5f3f20cee6b.png)

**Comment by Termuellinator** [comment]
already reported: https://github.com/ValveSoftware/steam-for-linux/issues/6437

**Comment by Daniel-McCarthy** [comment]
Thank you for letting me know. I did search for previous issues, however clearly I did not enough. I have closed this issue since it is a duplicate.
