### ISSUE TITLE
Steam crashes after resuming from suspend

### ISSUE THREAD

**Issue by simon816** [ValveSoftware/steam-for-linux#6447]
#### Your system information

* Steam client version (build number or date): `Built: Aug 6 2019 at 01:15:16`
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 (With `xubuntu-desktop`)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

```
Operating System Version:
    Ubuntu 18.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.10-050010-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime_0.20190711.3
```

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

If the steam client is left open before suspending the system, on resuming it crashes.
I expect it to continue working on resume.
This is likely a recent issue, I do not recall it happening over a month ago (in June).

End of stdout dump:
```
crash_20190812124451_1.dmp[7357]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190812124451_1.dmp
crash_20190812124451_1.dmp[7357]: Finished uploading minidump (out-of-process): success = no
crash_20190812124451_1.dmp[7357]: error: Couldn't resolve host name
crash_20190812124451_1.dmp[7357]: file ''/tmp/dumps/crash_20190812124451_1.dmp'', upload no: ''Couldn't resolve host name''
/home/simon/.local/share/Steam/steam.sh: line 720:  6663 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

The full log from `/tmp/dumps/simon_stdout.txt`, split before/after suspend: https://gist.github.com/simon816/cdbf3a1c583c7ace26b98ac19a731a85

I can share the crash dump if required.

#### Steps for reproducing this issue:

1. Open steam client
2. `systemctl suspend`
3. Resume system (could be immediately after suspending)
4. Observe steam is no longer running

**Comment by mondalaci** [comment]
I encountered the same issue.

* Steam client version (build number or date): Jun 4 2020, at 05:51:01
* Distribution (e.g. Ubuntu): Linux Mint 19.3 Tricia
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

See [the log](https://gist.github.com/mondalaci/c61e7c049bef728e4a068ea2c8eeebf4).

**Comment by simon816** [comment]
This hasn't happened to me for some time now so presumably whatever was crashing for me no longer is.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by vintagepc** [comment]
I've started to see this happen again with a recent steam client on OpenSuSE 15.3. What information can I provide that would be helpful?

**Comment by kisak-valve** [comment]
Hello @vintagepc, please open a new issue report.

**Comment by vintagepc** [comment]
Done, #8107
