### ISSUE TITLE
Games get alt-tabbed whenever i receive a notification on Steam

### ISSUE THREAD

**Issue by Adenis890** [ValveSoftware/steam-for-linux#6450]
#### Your system information

* Steam client version (build number or date): Aug 12, 2019 at 23:59:12
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Hi,
Whenever i get a notification on steam my games Alt-Tab. It's really annoying especially when you are in a comp match on CSGO. I tried finding a solution but nothing so i decided to post this here because maybe there is a bug.

#### Steps for reproducing this issue:

1. Be in a game 
2. Get a notification
3. Game will alt-tab

**Comment by kisak-valve** [comment]
Hello @Adenis890, this issue is already being tracked at #5286. Closing as a duplicate.

**Comment by kisak-valve** [comment]
Whoops, while possibly related that issue isn't a complete match.

For SDL2 games, running Steam with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 steam` or adding `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to the game's launch options should help mitigate the symptom you're seeing.

**Comment by Adenis890** [comment]
So this is only for games that are not Linux native right?

**Comment by Newbie13XD** [comment]
I have had this occur on Fedora too. I think it might be a GNOME issue.

**Comment by Adenis890** [comment]
> Whoops, while possibly related to that issue, it isn't a complete match.
> 
> For SDL2 games, running Steam with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 steam` or adding `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to the game's launch options should help mitigate the symptom you're seeing.

So these launch options are only for non Native Linux games.

**Comment by Newbie13XD** [comment]
> > Whoops, while possibly related to that issue, it isn't a complete match.
> > For SDL2 games, running Steam with `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 steam` or adding `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to the game's launch options should help mitigate the symptom you're seeing.
> 
> So these launch options are only for non Native Linux games.

They should work with any game that uses SDL2, which includes both native and non-native games. In the case of CS:GO, I'm not sure whether it uses SDL2.

**Comment by Bodyash** [comment]
Arch linux + Gnome desktop
same issue with Dota

whenever i receive a message from friend - game is minimized 
but only if chat window was closed, so i just keeping it opened and minimized

**Comment by Newbytee** [comment]
@Adenis890 Why did you close this?
