### ISSUE TITLE
opengl glx extension not supported by display

### ISSUE THREAD

**Issue by thorwaldson** [ValveSoftware/steam-for-linux#6452]
#### Your system information

* Steam client version (build number or date):
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam should start but  gives "opengl glx extension not supported by display" as output.

#### Steps for reproducing this issue:

1. install Steam via Flathub
2. start Steam

**Comment by kisak-valve** [comment]
Hello @thorwaldson, similar to #4883, this usually is an indication that your 32 bit opengl driver is not setup properly. Does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

**Comment by thorwaldson** [comment]
Output of glxinfo:
glxinfo
name of display: :0.0
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Error: couldn't find RGB GLX visual or fbconfig
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".

Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".
Xlib:  extension "GLX" missing on display ":0.0".

**Comment by kisak-valve** [comment]
What video card and version of Debian are you using?

**Comment by thorwaldson** [comment]
Debian 10.0
Nvidia geforce gtx 960m

**Comment by kisak-valve** [comment]
Please check if you have the `nvidia-driver-libs-i386` package installed with something like `apt policy nvidia-driver-libs-i386`. If you're using an optimus laptop, then it would be easier to try to get Steam working with the Intel gpu, which would use the `libgl1-mesa-dri:i386` package.

**Comment by thorwaldson** [comment]
apt policy nvidia-driver-libs-i386
nvidia-driver-libs-i386:i386:
  Installed: 390.116-1
  Candidate: 390.116-1
  Version table:
 *** 390.116-1 500
        500 http://httpredir.debian.org/debian stretch/non-free i386 Packages
        100 /var/lib/dpkg/status

**Comment by thorwaldson** [comment]
Gonna close this now and change distro.
