### ISSUE TITLE
amdgpu driver for new radeon 5700XT breaks steam client frontend

### ISSUE THREAD

**Issue by leder11011** [ValveSoftware/steam-for-linux#6454]
#### Your system information

* Steam client version (build number or date): Startup - updater built Aug 12 2019 23:47:21
* Distribution (e.g. Ubuntu): ubuntu 18.04 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
![Bildschirmfoto von 2019-08-13 09-49-39](https://user-images.githubusercontent.com/3330116/63141479-1eb3e480-bfe6-11e9-8d57-1ef50543c124.png)

#### Please describe your issue in as much detail as possible:
Immediately after starting steam client the windows decoration gets broken and steam fat client text pieces are all blurred, s. screenshot.

#### Steps for reproducing this issue:

1. Install amdgpu-pro-19.30-855429-ubuntu-18.04
2. install amdgpu OSS driver, not pro
3. run steam client in legacy mode

**Comment by leder11011** [comment]
I brought the issue to the driver developer's attention here:
https://community.amd.com/message/2925619

**Comment by leder11011** [comment]
leder@leder-ryzen-home:~$ echo $DESKTOP_SESSION
ubuntu-wayland

**Comment by leder11011** [comment]
Would you please fix the gremlins characters? It is annoying...

**Comment by troupn** [comment]
I am also experiencing this issue. I did not install the pro version though. It came up after enabling Vulkan by adding my user to the video group as instructed.

**Comment by leder11011** [comment]
OK, one more issue, hopefully it gets fixed. This was my procedure:
- install pro driver incl. vulkan: this was not displaying anything
- uninstall pro driver
- install OSS driver: it was working for one week
- error persisting after one week

I hopefully get my machine working again with a fresh ubuntu 18.04 LTS install and using OSS driver/kernel 5.3 and Mesa 19.2 devel!

**Comment by leder11011** [comment]
Thank you for you information, @troupn !

Now I installed:
- amdgpu OSS (All-Open Variant) w/o Vulkan
- steam is up and running again!

Wishlist @kisak-valve :
- I would like to play games w/ vulkan support
- please fix amdgpu pro variant

Thanks all!

**Comment by kisak-valve** [comment]
Hello @leder11011, issues with your video driver should be mentioned to the video driver vendor if they haven't been already.

In general, that video card should be working with mesa 19.2+, llvm 9+, linux 5.3+, and updated linux-firmware which includes Navi support. The way you've phrased which driver you're using doesn't make it clear if you're trying to use mesa/radv or amdvlk for vulkan support.

This is not an issue to be solved in the Steam client, instead, your distro needs to pick up newer driver components or use PPAs to supplement the distro's packages to fully support your video card out of the box.
