### ISSUE TITLE
Steam crashed while Dota 2 was open taking down both.

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6456]
Your system information

* Steam client version: Aug 15 2019, at 21:07:59. Has happened for at least 5 beta updates.
* Distribution: Xubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System info: https://gist.github.com/Managor/c1f2c2fe5f1c138dff9efcdac47a29de

#### Please describe your issue in as much detail as possible:
Steam crashed while Dota 2 was open crashing both applications. Here are the three crashdumps.
[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/3509505/dumps.zip)
CrashID for `assert_20190816151140_26.dmp` is `CrashID=bp-e9371582-55ff-4db2-bc2c-c745c2190816`. I heard the ID is useful to you.

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by Managor** [comment]
@kisak-valve This can probably be closed. The crash is ancient, a lot has changed and nobody has replicated it to this day.
