### ISSUE TITLE
Using XFCE shutdown/reboot once only closes Steam

### ISSUE THREAD

**Issue by zaggynl** [ValveSoftware/steam-for-linux#6457]
#### Your system information

* Steam client version (build number or date): Aug 12 2019, package versions: 1565656602
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Use XFCE built in Shutdown or Reboot from menu, expect start of shutdown/reboot
2. Steam closes
3. After pressing Shutdown or Reboot again from menu the expected start of shutdown/reboot occurs.

**Comment by zatricky** [comment]
Hi, @zaggynl. Though closed, how does this behaviour compare to the behaviours described at #3301?

**Comment by zaggynl** [comment]
Issue no longer occurs last I tested.

@zatricky: seems similar?
