### ISSUE TITLE
TV has no signal when steamlink connects to computer

### ISSUE THREAD

**Issue by Zman94** [ValveSoftware/steam-for-linux#6462]
#### Your system information

* Steam client version (build number or date): Newest Windows 10 version (will update when I'm home)
* Distribution (e.g. Ubuntu): Windows
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
Steam Link on Raspberry Pi 3b

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I downloaded steamlink for my raspberry pi running emulation station using `sudo apt install steamlink` and was able to boot it up. For awhile, I had no issues, but recently, when I connect to my computer, my computer opens big picture mode, my steamlink connects and I can move around the screen using my controller, but the video and sound don't show up on the tv.
I would expect to see the steam big picture

Steam support ticket with more information https://help.steampowered.com/en/wizard/HelpRequest/HT-273H-PXHG-KKPN

#### Steps for reproducing this issue:

1. `./steamlink`
2. Connect to computer
3.

**Comment by kisak-valve** [comment]
Hello @Zman94, sorry, but issues with the Steam Link for Raspberry Pi client is out of scope for this issue tracker. Feel free to mention this issue over at https://steamcommunity.com/app/353380/discussions/6/ if you're still seeing it.
