### ISSUE TITLE
random disconnects into offline mode, weirdly hindered connectivity that only comes back if i disable and reenable my internet connection

### ISSUE THREAD

**Issue by 1xch** [ValveSoftware/steam-for-linux#6464]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist]
(https://gist.github.com/): 

Operating System Version:
    Ubuntu 19.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-23-generic
    Steam Runtime Version:  steam-runtime_0.20190711.3

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 710/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 418.56

Sound card:
    Audio device: Realtek ALC887

* Have you checked for system updates?: [Yes/No]
yes
* Are you using the latest stable video driver available for your system? [Yes/No]
afaik
* Have you verified the game files?: [Yes/No]
yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I'm getting put into offline mode an average of once per game. 

#### Steps for reproducing this issue:

1. Play dota.
2. Game goes to offline mode, i get disconnected. I can't use my browser and steam says no connection I can however ping out to the internet.
3. I can reconnect if i disable and re-enable my internet connection.

I'd like some assistance troubleshooting this, networking isn't my area and I'd have no idea how to diagnose something like this. 

btw 0 issues except some transient lag before the 'summer scrub', a frustrating experience since

**Comment by byte1024** [comment]
This is very odd. The game itself would have to literally break the networking. I find this less likely than some computer side setting or networking problem... but it is likely possible if it did something not good.

Unfortunately, networking problems entails quite a lot and there's quite a few differences so I'm not suggesting anything.

**Comment by 1xch** [comment]
idk something is giving me a hard time somewhere in the stack

**Comment by nightsky30** [comment]
Sounds sort of like #5200 and a few related issues mentioned there.  Are you using the beta client?

**Comment by 1xch** [comment]
I've gotten it outside of dota now several times...so even though it happens reliably while playing dota, it must be something system/kernel. Potentially some out of suspend driver issue, which I've had to deal with in the past or something new I don't have a clue about.
