### ISSUE TITLE
Steam Client crashes after changing settings

### ISSUE THREAD

**Issue by PensiveCynic** [ValveSoftware/steam-for-linux#6476]
#### Your system information

* Steam client version (build number or date): Aug 28 2019 at 23:51:11 
* Distribution (e.g. Ubuntu): Ubuntu Family: Pop!_OS
* Opted into Steam client beta?: [Yes/No] Tried with and without Beta
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever I try to change some settings in Steam Client, for instance enable Steam Play for all, the Steam client crashes without saving the settings

#### Steps for reproducing this issue:

1. Open Steam Client
2. Open Settings Dialog
3. Click to enable Steam Play for All titles
4. Click OK

attached are the
[error.log](https://github.com/ValveSoftware/steam-for-linux/files/3562016/error.log)
and the dump file: 
[crash_20190830230031_1.dmp.gz](https://github.com/ValveSoftware/steam-for-linux/files/3562017/crash_20190830230031_1.dmp.gz)

**Comment by kisak-valve** [comment]
Hello @PensiveCynic, this issue is already being tracked at #5664, closing in favor of the existing issue report.
