### ISSUE TITLE
Cannot write a review for a Steamplay game (game time not counted)

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/steam-for-linux#6477]
#### Please describe your issue in as much detail as possible:

I played Windows game using Steamplay (Proton) for 10h, but I cannot write a review, Steam showing a message: "Przed napisaniem recenzji musisz uruchomić ten tytuł na co najmniej 5 minut (w chwili obecnej twój czas to 0)." (Before writing a review you have to run the title for at least 5 minutes (your time is 0 now).

**Comment by byte1024** [comment]
I don't think Proton has anything to do with the problem. Have played multiple games and tested other games using Proton and as far as I can see all do show increased time so its obviously working. That would mean to reproduce the problem, it would have to be something deeper than "Played with Proton and no time shows up".

**Comment by kwahoo2** [comment]
> "Played with Proton and no time shows up".

I didn't write that. Time is counted (10h as I wrote) by Steam client, but Steam Store review system for some reason does not recognize it.

**Comment by byte1024** [comment]
> > "Played with Proton and no time shows up".
> 
> I didn't write that. Time is counted (10h as I wrote) by Steam client, but Steam Store review system for some reason does not recognize it.

That wasn't a quote. I was using it in the attempt at saying what you were saying with less words, "I played Windows game using Steamplay (Proton) for 10h ... Steam showing a message ... (your time is 0 now).

Sorry, if I didn't understand correctly as you only now put in that Steam shows 10h played. You wrote previously that "**_I_** played Windows game using Steamplay (Proton) for 10h" followed by "Steam showing" and "(Before writing a review you have to run the title for at least 5 minutes (your time is 0 now)." The fact that you mentioned review didn't matter at that point.

But now that's cleared up :+1:

**Comment by kisak-valve** [comment]
Hello @kwahoo2, are you still experiencing this issue with an up to date system?

**Comment by kwahoo2** [comment]
Seems fixed now.
