### ISSUE TITLE
Cannot upload screenshots

### ISSUE THREAD

**Issue by Patola** [ValveSoftware/steam-for-linux#6478]
#### Your system information

* Steam client version (build number or date): Steam client Beta, Build: Aug 28 2019, at 23:51:11, Steam API: v019, steam package versions: 1567041311
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3
* Opted into Steam client beta?: [Yes] 
* Have you checked for system updates?: [Yes]
* Complete system information: https://gist.github.com/Patola/2fa5199d07637c870888f39448c6aa7b

#### Please describe your issue in as much detail as possible:

I have been able to upload screenshots for a long time. A couple weeks ago, though, without any change on my network, any firewall or any significant updates, I am unable to upload the screenshots I take with F12. In the log, it simply times out. I tried opening a support request in steam but at some time the support person seemingly got tired of the back-and-forth and closed the ticket (which was quite rude). The support request is this one, I don't know if the link would be readable by people here: https://help.steampowered.com/en/wizard/HelpRequest/HT-9GR3-GJHV-T3NY

This is basically what happens now:

I press F12 on a game, it works correctly and takes the screenshot. Left the game, selected the screenshot, and tried to upload that screen to the steam cloud:
http://pix.toile-libre.org/upload/original/1566929425.png
I click upload, I don't set the upload to facebook option (but if I did, the result would be the same), and:
http://pix.toile-libre.org/upload/original/1566929479.png
"There was an error uploading 1 screenshots. Steam Cloud may be temporarily available".

Notice that I have 18+ GB free on my cloud storage, so it's not lack of space.

#### Steps for reproducing this issue:

1. Play a game.
2. Press F12 during the game to take a screenshot.
3. Leave the game.
4. In the screenshots panel that appears right after you leave, select one screenshot and try to upload it. It doesn't matter if public, friends only or private (I tested all of them).
5. The blue bar will get almost to the end, but then it turns orange. It says that there was an "error uploading 1 screenshot. Steam Cloud might be temporarily available". However every other steam function works, including posting messages and reviews, synchronizing savegames to steam cloud, and whatnot.

I am attaching the entire cloud_log.txt file here but this is one of the relevant parts:
```
[2019-08-31 16:27:09] Starting screenshot upload job.
[2019-08-31 16:27:09] [GameID 275850] Processing screenshot #1/1 - 275850/screenshots/20190828043856_1.jpg
[2019-08-31 16:27:10] [AppID 760] HTTP upload for file '275850/screenshots/20190828043856_1.jpg' beginning . . .
[2019-08-31 16:27:22] [AppID 760] HTTP upload for file '275850/screenshots/20190828043856_1.jpg' (offset=0, length=723167) to host 'steamclouduseast.blob.core.windows.net', path /cloud/D3/37/C3/05/760/02B_E_1B8F5ADC_05E33_1.dat - timed out.
[2019-08-31 16:27:23] [GameID 275850] Uploading 275850/screenshots/20190828043856_1.jpg finished with result Failure
[2019-08-31 16:27:23] BUploadScreenshot - BYieldingUploadSingleFile failed for 275850/screenshots/20190828043856_1.jpg
[2019-08-31 16:27:23] Screenshot upload job complete - uploaded 0 of 1
```

[cloud_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3562958/cloud_log.txt)

**Comment by Patola** [comment]
BTW steamclouduseast.blob.core.windows.net resolves to 52.240.48.36 in my PC. Running a quick browser test on port 80, it returns a XML file.

**Comment by Patola** [comment]
Is there a steamcmd script I can run to test the screenshot upload? Maybe it has more verbose output. I am googling for steamcmd documentation but I can find anything related.

**Comment by kisak-valve** [comment]
Hello @Patola, are you still experiencing this issue on an up to date system?

**Comment by Patola** [comment]
No. It really seemed to be something on my network. I was in Brazil at that time. Closing this
