### ISSUE TITLE
30 bit display breaks steam client

### ISSUE THREAD

**Issue by mabod** [ValveSoftware/steam-for-linux#6479]
#### Your system information

* Steam client version (build number or date): steam-manjaro 1.0.0.61-5
* Distribution (e.g. Ubuntu): 5.2.11-1-MANJARO Testing
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I switched xorg driver to 30 bit. This is with nvidia GTX 1050Ti + DP cable + Eizo CS2730 monitor.

The steam client is not starting anymore. It crashes after throwing 1000+ lines of debug output to the console. With 24 bit everything is fine.

I have attached the debug out as text file.

[steam-debug.log](https://github.com/ValveSoftware/steam-for-linux/files/3563216/steam-debug.log)

#### Steps for reproducing this issue:

1. Add the following to your xorg.conf:
```
Section "Screen"
     Identifier     "Screen0"
     Device         "Device0"
     Monitor        "Monitor0"
     DefaultDepth    30
     SubSection     "Display"
         Depth       30
     EndSubSection
EndSection

```
2. Login to gnome, cinnamon or XFCE and start the steam client.

**Comment by kisak-valve** [comment]
Hello @mabod, this issue is already being tracked at #4399. Closing as a duplicate.

**Comment by mabod** [comment]
Wow. Issue #4399 is more than 3 years old. Is there anything happening to fix it or is it just documented?
