### ISSUE TITLE
built-in browser doesn't work

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#6481]
#### Your system information

* Steam client version (build number or date): aug 21, version 1566431379
* Distribution (e.g. Ubuntu): debian unstable
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. start steam
2. go to any tab other than library
3. blackness

dmesg is flooded with this:
[ 2125.315338] traps: Chrome_IOThread[12456] general protection fault ip:7fbf2690f8c2 sp:7fbf12c4f2f8 error:0 in libcef.so[7fbf25bde000+60d1000]
[ 2135.470823] traps: steamwebhelper[12478] general protection fault ip:7f8988fe48c2 sp:7ffdd5c74e38 error:0 in libcef.so[7f89882b3000+60d1000]
[ 2145.594680] traps: Chrome_IOThread[12532] general protection fault ip:7f27b01d58c2 sp:7f279c5152f8 error:0 in libcef.so[7f27af4a4000+60d1000]
[ 2155.805654] traps: Chrome_IOThread[12573] general protection fault ip:7f86de7818c2 sp:7f86caac12f8 error:0 in libcef.so[7f86dda50000+60d1000]
[ 2165.888414] traps: Chrome_IOThread[12610] general protection fault ip:7fb0fbe738c2 sp:7fb0e81b32f8 error:0 in libcef.so[7fb0fb142000+60d1000]

**Comment by kisak-valve** [comment]
Hello @mtmkls, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by mtmkls** [comment]
System info:
https://gist.github.com/mtmkls/f52a658e96079d2fff4de4edbf7d22fa

**Comment by jatin-cbs** [comment]
Not a debian specific also in opensuse.. Its impossible to type or click the shift tab stuff is broken also on fedora

**Comment by lestephane** [comment]
Here is the  [System Info](https://github.com/ValveSoftware/steam-for-linux/files/3584832/steam.txt) from my Ubuntu 16.04 where the browser also doesn't work, stays black 
![image](https://user-images.githubusercontent.com/5460884/64445351-fbf58700-d0de-11e9-8a0c-013b5f50bf5e.png)

**Comment by mtmkls** [comment]
Is there an update on this? It kills the friends and chat windows too.

**Comment by mtmkls** [comment]
I also noticed that when I log into the client, I become online on steamcommunity for a moment, then I'm offline again even though the client is running. I think this is also caused by the built-in browser component not working.

**Comment by kisak-valve** [comment]
Hello @mtmkls, are you still experiencing this issue on an up to date system?

**Comment by mtmkls** [comment]
The current version doesn't have this issue. It got fixed a few months after I opened this report, I just forgot to close it. Thanks for the reminder.
