### ISSUE TITLE
steam game Tomb Raider 2013 fails to start fullscreen

### ISSUE THREAD

**Issue by leder11011** [ValveSoftware/steam-for-linux#6482]
#### Your system information

* Steam client version (build number or date): Startup - updater built Nov 23 2016 01:05:42
* Distribution (e.g. Ubuntu): ubuntu 18.04.3 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In a fresh ubuntu install with amdgpu all-open variant (OSS) for radeon rx 5700xt something is broken:
- TR 2013 runs fine in windowed mode, though I cannot turn around to the left hand side b/c of the ubuntu menu bar
- in full screen mode the game fails to start: black screen and crash

#### Steps for reproducing this issue:

1. start TR 2013 from steam
2. unselect "run in window"
3. press "play"

**Comment by kisak-valve** [comment]
Hello @leder11011, the game crash is most likely a video driver issue and should be mentioned to your video driver vendor.

**Comment by leder11011** [comment]
Not neccessary: I got it running in fullscreen now!
To be precise: TR 2013 does not run in fullscreen mode, when ubuntu desktop is started in ubuntu xserver mode.

Solution:
- logoff from desktop
- select cog in login screen
- select wayland session
- login again

Now TR 2013 runs finally in fullscreen mode!

BTW: for Navi10/radeon rx5700 (xt) hardware: please set the monitor to 60Hz! Otherwise the current amdgpu driver will not start the GPU-fan!!! This will result in crashes due to heat...
cp. this thread: https://community.amd.com/thread/242932
