### ISSUE TITLE
Steam overlay clicks behave extremely unpredictably

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6485]
#### Your system information

* Steam client version:  Aug 30 2019, at 18:54:19
* Distribution: Xubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When trying to highlight text or click on anything, the cursor seems to locate itself at a random offset from its real location. In the following video I try to highlight the player ID in the URL, then the player name, then I try to click on the X to close the browser tab and then I try to close the overlay by clicking. None of these clicks appear to hit ther mark correctly.
[2019-09-07 18-00-33.flv.zip](https://github.com/ValveSoftware/steam-for-linux/files/3586713/2019-09-07.18-00-33.flv.zip)

#### Steps for reproducing this issue:

1. Open a game
2. Open the steam overlay and the web broser
3. Try to click, highlight or drag objects

**Comment by sngl** [comment]
Same here:
Steam Sep19 2019 at 01:52:58
Distribution: Debian + KDE Plasma 5

**Comment by Managor** [comment]
Fixed in the latest beta.

**Comment by kisak-valve** [comment]
Glad to hear, closing per the last comment.
