### ISSUE TITLE
Proton 4.11-4 didn't show up until restart of Steam

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#6490]
Opened Steam
Went to download's
Downloaded 4.11-4 and it was nowhere to be seen.
Exit Steam
Start Steam
4.11-4 showed up

After I created this, suppose it might have been more correct to put into Steam issues instead of Proton but can't delete so there you go.

**Comment by byte1024** [comment]
Thanks for moving it over :-)

**Comment by byte1024** [comment]
Wondering if it was just the UI wasn't updated and starting a game using 4.11-3 would have resulted in 4.11-4 starting.

**Comment by h1z1** [comment]
Can confirm the same.   Strange thing is checking for updates didn't yield anything.

**Comment by byte1024** [comment]
Clarification:  Downloaded 4.11-4 and it was nowhere to be seen means that I had downloaded it but Steam was not showing it in the list of versions.

**Comment by Newbie13XD** [comment]
> Wondering if it was just the UI wasn't updated and starting a game using 4.11-3 would have resulted in 4.11-4 starting.

I've had the same issue occur a couple of times, and based on my experience this seems to be the case.

**Comment by kisak-valve** [comment]
Closing because the the reporting user has turned into a ghost.
