### ISSUE TITLE
Library Beta: No operating system list now

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6497]
#### Your system information

* Steam client version (build number or date): Sept 17th
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

With the Steam Library overhaul, there's no longer a way to switch between Linux games and all games.

The option used to be a drop-down next to the search bar, now it's not.

Additionally, it no longer tells you if a game is running with Steam Play.

**Comment by kisak-valve** [comment]
Closing as implemented with `Added a "filter by platform" button to Linux and MacOS that will filter the current game list to only games that run on the current platform.` in the [2019-09-26](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1591383946838639778) Steam client beta update.

The lack of an indicator for Proton is being tracked at #6494.
