### ISSUE TITLE
Taking screenshot in gnome-shell via Ctrl + Shift  + PrtScn causes clicking to work as though mouse was dragged in web views

### ISSUE THREAD

**Issue by Newbie13XD** [ValveSoftware/steam-for-linux#6498]
#### Your system information

* Steam client version (build number or date): Sep 17 2019, at 01:04:36
* Distribution (e.g. Ubuntu): Fedora 30 Workstation
* Video: GTX 970 with nvidia 430.40 on X.org
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

First, I want to make something clear: this issue has been bothering me for a good while and is **not** something new in the library update. Rather, I only figured out how to reliably reproduce it when showing off the new library to a friend. 

Issue occurs both with hardware acceleration enabled and disabled. I have not attempted to reproduce it with a different window manager, graphics card, nor video driver. 

It only occurs in web views, and as such the old library was not affected. Worth mentioning is that if I open a new window, such as the friends UI or a chat window, the issue does not make its way there until I reproduce it. It does, however, persist in the original Steam window, and a full restart of Steam is required to de-trigger the bug. Closing one Steam window, or all Steam windows, does not de-trigger it once they are opened again. 

While this bug is triggered, right-clicking does not work, however middle-click does seem to work (I can use it to close chat windows). Pressing the enter key on my keyboard does not allow me to send messages in this state, instead producing a newline. GUI button to send messages does keep working however. 

#### Steps for reproducing this issue:

1. Use gnome-shell 3.32.2 as your window manager (have not attempted in others)
2. Open Steam
3. Display a web view (new library works, community home too)
4. Ensure that a Steam window is in focus
5. Press Control + Shift + Print Screen and mark an area to take a screenshot of it
6. Double-click some text (or click an entry in the new library)
7. Click a different part of the text (or a different library entry in the new library)
8. Notice that everything between those points is marked, as though you had dragged your mouse between those points

**Comment by nightsky30** [comment]
Seems like #3451.  If you hit shift again it should fix the issue.  The shift key does not appear to be completing a key-up event.

**Comment by kisak-valve** [comment]
Hello @Newbie13XD, this issue is already being tracked at #3451. Closing as a duplicate.
