### ISSUE TITLE
Steam client may continually unblank the display

### ISSUE THREAD

**Issue by NotMrFlibble** [ValveSoftware/steam-for-linux#6503]
Steam client version: 1568741045
Distribution: Devuan beowulf

The Steam client is, in at least some situations, now actively unblanking the display, which means that if I want to (for example) leave it downloading something, I now have to switch off the monitors. The alternative is to kill the client.

It's possible that the change which “fixed a problem where the screen could go to sleep while using a controller” is at fault here, even though there is no controller attached. There does not appear to be any specific trigger.

**Comment by kisak-valve** [comment]
Hello @NotMrFlibble, this is a subtle variation of #5607 and we'd be better off tracking this as another symptom of the existing issue report. Closing in favor of the existing issue report.
