### ISSUE TITLE
new steam library is slow and unresponsive unless you run steam with native runtimes

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6505]
#### Your system information

* Steam client version (build number or date): Sep 17 2019
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
new steam library is slow and unresponsive unless you run steam with native runtimes
https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/

**Comment by kisak-valve** [comment]
Hello @barfin, general performance with the 2019-09-17 Steam beta client is already being tracked at #6500, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/6500#issuecomment-532667941.
