### ISSUE TITLE
Steamwebhelper randomly causing OOM

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/steam-for-linux#6508]
#### Your system information

* Steam client version (build number or date): Sep 17 2019
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm not yet sure why but sometimes one of the steamwebhelper processes will suddenly start allocating a huge amount of memory causing a system-wide freeze if not killed quickly enough. It may start either after opening a game or closing it.
I've never experienced it before the latest Steam UI beta update.

#### Steps for reproducing this issue:
1. Open/close a game
2. Look for steamwebhelper with abnormally high memory usage

**Comment by kisak-valve** [comment]
Hello @kiroma, this reads like a duplicate of #6502. Please check if `Enable GPU accelerated rendering in web views (requires restart)` is enabled in Steam -> Settings -> Interface.

**Comment by kiroma** [comment]
Oh yeah, you're right.
