### ISSUE TITLE
Segfault when viewing properties on native games without official Linux versions with steamplay enabled.

### ISSUE THREAD

**Issue by natis1** [ValveSoftware/steam-for-linux#6510]
#### Your system information

* Steam client version (build number or date): Sep 15 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When installing a game with a native Linux version that isn't officially listed, such as 60 Seconds! Steam gets confused about if the game is native or not. If steamplay is enabled, when you click on the game it says "runs on this computer via Steam Play" without specifying a version of proton. Launching it causes it to launch the native version as it should. Right clicking on it and clicking properties causes steam to segfault with the following message:

`line 720: 36355 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"` and the following stack trace

https://paste.ee/p/5UWU3

Right clicking and going to properties with steamplay disabled causes the properties menu to appear normally.

Expected behavior: This game should be treated like a normal native Linux game and not a proton game.

#### Steps for reproducing this issue:

0. Enable steamplay.
1. Install a game with a native Linux depot but without Linux being officially listed on the store/game. Like for example 60 seconds!
2. Click on the game in your library and observe that it claims to run in steamplay.
3. Right click on the game and click properties and steam will crash.

**Comment by kisak-valve** [comment]
Hello @natis1, are you still experiencing this issue on an up to date system?

**Comment by natis1** [comment]
I cannot reproduce this on steam package version 1642451672. So thanks for fixing it!
