### ISSUE TITLE
Can't view news on the Steam for Linux group

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6513]
Not client related but not sure where else to post.

You can no longer view any of the news on the Steam for Linux official group (https://steamcommunity.com/games/221410)

If you click any news, it will throw this error:

> Error Loading Event
> Loading the event information encountered the following error.
> Unknown Error: Error: Request failed with status code 400
> EventError_Code

**Comment by Myrddin-Wyllt** [comment]
That's not the only issue; when you go to try and Join a public group, the option is absent from within Steam yet present for web browsers:
### Steam:
![image](https://user-images.githubusercontent.com/42914865/65279917-e3c93300-daf4-11e9-903d-b0293b3f44b4.png)

### Browser:
![image](https://user-images.githubusercontent.com/42914865/65280064-2b4fbf00-daf5-11e9-9cbf-4383cb7fba65.png)

I can't find a way to join Steam groups currently...

**Comment by kisak-valve** [comment]
Hello @LiamDawe, are you still experiencing this issue on an up to date system?

**Comment by LiamDawe** [comment]
All fine now.
