### ISSUE TITLE
New client leaks memory

### ISSUE THREAD

**Issue by IGBC** [ValveSoftware/steam-for-linux#6514]
# 6514
## Your system information

* Steam client version (build number or date): Sept 18 2019 23:48:38
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Newly released client leaks memory like a sieve.

Took about 20 minutes to consume the entire 64GB address space on my machine, nearly took the computer down.

htop reports steamwebhelper as the offending process
#### Steps for reproducing this issue:

1. Open steam
2. Leave steam open on the library page (actually was playing another game in a window
3. Get distracted for 20 minutes
4. Realise the computer is choppy, htop confirms that it's running out of ram and swap

**Comment by kisak-valve** [comment]
Hello @IGBC, this issue is already being tracked at #6502. You should be able to workaround this issue by unchecking `Enable GPU accelerated rendering in web views (requires restart)` in Steam -> Settings -> Interface
