### ISSUE TITLE
[Library Beta] Games installed via Family Share doesn't get listed when "Installed on this computer" filter is selected

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#6519]
#### Your system information

* Steam client version (build number or date): Sep 20 2019 build
* Distribution (e.g. Ubuntu): Linux Mint 19.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Just like i said at the title ; "installed on pc" filter just doesn't include those games and says " X number items hidden due to your preferences" which X= installed games count via Family share.

Yet , they can be seen and accessed via " Library Main Page " but with oddly misplaced text that say's it is being shared.

Display size for library user interface elements is set to " Auto" which is the default behaviour.

Example screenshot:

![library](https://user-images.githubusercontent.com/24878978/65323950-6a444a00-dbb3-11e9-90ee-4b516d4cf949.png)

#### Steps for reproducing this issue:

1. Use Family Library Sharing
2.  Select " installed on this PC" filter
3. Observe misplaced writings at " Library Main Page" view

**Comment by psymin** [comment]
This is how it displays on my machine:

When the shared game is installed on the box:
![library-beta-sharing-installed](https://user-images.githubusercontent.com/326578/65345801-5f2ff080-db98-11e9-92a9-088e6b2ceb18.png)

When the shared game is uninstalled:
![library-beta-sharing-uninstalled](https://user-images.githubusercontent.com/326578/65345808-60f9b400-db98-11e9-8a6b-99fb8a1a1d51.png)

Steam System Information:
https://gist.github.com/psymin/862d6c92430b26bfbe93562f263b3547

**Comment by Leopard1907** [comment]
@psymin

I think instruction were not clear , my bad.

Can you see them listed at left side of library view when you filter as " Installed on this pc "?

Old ui was sorting them like ; "shared account xyz's games" but it doesn't do anymore nor list them as just installed at left side of library list view.

**Comment by psymin** [comment]
I might not be understanding you properly.

This game 20XX is shared and installed.  Is this the way it looks on yours when shared?

![steam-beta-library-installed-shared-2](https://user-images.githubusercontent.com/326578/65446058-c811a580-ddf0-11e9-92c6-be58d97ab07d.png)

![steam-beta-library-installed-shared](https://user-images.githubusercontent.com/326578/65446059-c942d280-ddf0-11e9-9f68-c8eb7ba2bf42.png)

**Comment by Leopard1907** [comment]
@psymin Basically this: 
![old](https://user-images.githubusercontent.com/24878978/65446375-e2717080-de3c-11e9-809e-caf545ffba7d.png)

Can you see how games that are shared with me listed as " Games of Creeping Death " while my games are listed on top?

**Comment by psymin** [comment]
Yes.  I think I understand.

Are you hoping to have some of the functionality from the old library interface that is missing from the new library interface?  You want the ability to group the games in your inventory based on who is sharing them with you?

**Comment by Leopard1907** [comment]
On old Steam UI , the screenshot i just posted a moment ago was on " Installed on this PC " filter. It was ( by default ) seperating games by ownership. So i think lack of that view on same " Installed on this PC " filter at new UI is simply a regression.

**Comment by kisak-valve** [comment]
Hello @Leopard1907, @psymin, per "Fix play bar drawing over the links bar on game details when library sharing is active" in the [2019-09-23](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1589131508782140065) Steam client beta update, please retest this issue.

**Comment by Leopard1907** [comment]
@kisak-valve I tested it now , that play bar issue is solved. However other issue ( which is about functionality more than cosmetics ) still remains.

**Comment by kisak-valve** [comment]
Hello @Leopard1907, are you still experiencing this issue on an up to date system?

**Comment by Leopard1907** [comment]
@kisak-valve Yes, client beta.

https://github.com/ValveSoftware/steam-for-linux/issues/6519#issuecomment-534190779

Like i described in this message back then, this " Games of XYZ ( shared account random name )" section is missing.

![Screenshot_20220223_133718](https://user-images.githubusercontent.com/24878978/155303995-33c816d1-d7e1-4a3c-8f2e-79a8498f9c16.png)

8 Bit Boy in this screenshot is installed from shared account.

Currently it just tucks in everything to "uncategorized" which includes both my games and shared account games mixed. Only way to know which account owns that particular game (s) is clicking to each game on library and seeing this:

![Screenshot_20220223_134617](https://user-images.githubusercontent.com/24878978/155304508-4eac0645-50c3-43b1-acd5-25fa9fc37b7e.png)


Only improvement i noticed ( but not so relevant ) is i can add a new shelf like this on this new UI kinda thingy.

![Screenshot_20220223_134958](https://user-images.githubusercontent.com/24878978/155305074-b217f290-ef68-4435-8d0e-8021a12b88ac.png)

But it still not the pre UI revamp behaviour.

**Comment by helmchenlord** [comment]
On my Library games get listed but as "purchase".
This happened to me several times and every time we had to reshare the games which is very annoying.
I can not trace back when this happens but my guess is after an update from steam client or system update.

![Screenshot_20221119_194055](https://user-images.githubusercontent.com/12427618/202867832-d319fe84-3d76-4cde-bca9-fada8e6989ba.png)
![Screenshot_20221119_193708](https://user-images.githubusercontent.com/12427618/202867834-a61db018-e645-4afc-a584-98d3351463a3.png)

**Comment by Leopard1907** [comment]
Since i created issue too many changes happened and with new way of things handled in this area now, this issue is redundant so closing.
