### ISSUE TITLE
None of the games start

### ISSUE THREAD

**Issue by Lyberta** [ValveSoftware/steam-for-linux#6520]
#### Your system information

* Steam client version (build number or date): Sep 19 2019
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

None of the games start when I try to launch them from Steam library. The executable seems to run as Steam client shows that I'm in game but game windows never appears. After several minutes I can see this in the terminal:

```
../common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
../common/pipes.cpp (770) : Fatal assert failed: ../common/pipes.cpp, line 770.  Application exiting.
```

May be related to #6326 but the Steam itself connects (although from the 4th attempt or so) and I'm running kernel 5.2.9 which should be patched.

**Comment by Lyberta** [comment]
It also may have something to do with file system because after clean reboot it usually works for some time but eventually breaks. However, one time I had a power failure and when booted up the games didn't work.

**Comment by Lyberta** [comment]
Ugh, now it unbroke itself after being broken for several days. I took several dumps of filesystem (just list of files) and don't see stray files being left so I don't think file system is at fault. Maybe another obscure bug in Linux kernel or Steam client.

**Comment by kisak-valve** [comment]
Closing per the last comment.
