### ISSUE TITLE
Steam stops monitor from sleeping

### ISSUE THREAD

**Issue by RockyTV** [ValveSoftware/steam-for-linux#6528]
#### Your system information

* Steam client version (build number or date): Sep 23, 2019 at 16:07:56
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have XFCE installed and up to date to the latest version on my computer. Whenever Steam is running, my monitors are never put to sleep, instead, they keep active as if someone was using the computer when in fact the computer is idle. Closing Steam and its related processes allows this power saving setting to work again.

System info: https://gist.github.com/RockyTV/271ef8e118c9485979bb8dc40eb6fbf4

#### Steps for reproducing this issue:

1.Launch Steam
2. Log-in
3. Let your computer idle for about 10-15 minutes (if you have a setting to put your monitors to sleep)

**Comment by kisak-valve** [comment]
Hello @RockyTV, this issue is already being tracked at #5607. Closing as a duplicate.
