### ISSUE TITLE
VAC was unable to verify your game session.

### ISSUE THREAD

**Issue by dinodude7777** [ValveSoftware/steam-for-linux#6529]
#### Your system information

* Steam client version (build number or date): October 1, 2019
* Distribution (e.g. Ubuntu): Xubuntu 18.04
* Opted into Steam client beta?: [Yes/No] Yes (tried opting out, bug still exists)
* Have you checked for system updates?: [Yes/No] Yes
![image](https://user-images.githubusercontent.com/44576802/65712259-3ad28900-e05c-11e9-8248-213490728f09.png)

#### Please describe your issue in as much detail as possible:
When trying to queue for a matchmaking game in CSGO, get the error "VAC was unable to verify your game session". I tried validating game files, reinstalling the game, updating steam and my pc, rebooting, relogging, etc. Contacted steam support and they told me to make an issue here. Been happening for 2 days. I havent cheated or ever installed anything that might otherwise trigger VAC so I dont think its related to that. I tried queuing on my windows 10 laptop and was able to just fine.
![image](https://user-images.githubusercontent.com/44576802/65712234-29897c80-e05c-11e9-8e07-6ff9e0a01730.png)

#### Steps for reproducing this issue:

1. Queue for a competitive CSGO match
2. Get the error if youre unfortunate enough to be affected

**Comment by kisak-valve** [comment]
Hello @dinodude7777, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2188. Closing as a duplicate.
