### ISSUE TITLE
[Library Beta] Even with every game marked to use proton, some won't work

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6531]
#### Your system information

* Steam client version: Sep 26 2019,  at 17:32:39
* Distribution: Xubuntu 19.04 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System info gist: https://gist.github.com/Managor/7841d190d3ca350a5a9cc32045c67b98

#### Please describe your issue in as much detail as possible:
I have every windows game forced to use proton from Steams general settings. When toggling the filter for Linux, some collections show that they have some games omitted as shown below.
![image](https://user-images.githubusercontent.com/42655600/65721166-320ca200-e0b2-11e9-81c0-8e372ab19b21.png)
When checking the games that are omitted it shows that it is only available for windows
![image](https://user-images.githubusercontent.com/42655600/65721368-962f6600-e0b2-11e9-887a-ee1f67b45b10.png)
When you go to the individual games settings and tick the "Force the use of a specific Steam Play Compatibility tool" on and off, the game will be playable again
![image](https://user-images.githubusercontent.com/42655600/65721441-bf4ff680-e0b2-11e9-92e6-faa77ce1816a.png)

Here is the same in video form: [2019-09-26 23-14-16.flv.zip](https://github.com/ValveSoftware/steam-for-linux/files/3659727/2019-09-26.23-14-16.flv.zip)

#### Steps for reproducing this issue:

1. Enable Steam Play for all titles
2. Filter by games for Linux
3. Find the game from the collections that is getting omitted
4. Go to the individual games settings and tick the "Force the use of a specific Steam Play Compatibility tool" on and off

**Comment by peon501** [comment]
I am sure that the filter doesn't work. I have the same issue on my steam ubuntu 19.04

**Comment by kisak-valve** [comment]
Hello @Managor, @peon501, are you still experiencing this issue on an up to date system?

**Comment by Managor** [comment]
I haven't seen it happen.

**Comment by kisak-valve** [comment]
Closing per the last comment.
