### ISSUE TITLE
BPM overlay steals controller input

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6532]
#### Your system information

* Steam client version: Sep 26 2019,  at 17:32:39
* Distribution: Xubuntu 19.04 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System info gist: https://gist.github.com/Managor/7841d190d3ca350a5a9cc32045c67b98
* Controller type: Steam Controller
* Game: Bioshock Remastered
* Config link: steam://controllerconfig/409710/1873383481
* Mirror report on Steam Forums: https://steamcommunity.com/app/353370/discussions/1/1631916406850610840/

#### Please describe your issue in as much detail as possible:
When trying to play a game with the steam controller, the Big Picture overlay intercepts the controller inputs.

Video of it happening
[2019-09-26 23-58-45.flv.zip](https://github.com/ValveSoftware/steam-for-linux/files/3659883/2019-09-26.23-58-45.flv.zip)

#### Steps for reproducing this issue:

1. Turn your controller on
2. Try to play a game with the controller
3. You can hear the BPM overtaking your inputs

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #6495. Closing as a duplicate.
