### ISSUE TITLE
"Filter by platform" does nothing when Steam Play is enabled for all titles

### ISSUE THREAD

**Issue by Jayman2000** [ValveSoftware/steam-for-linux#6534]
#### Your system information

* Steam client version (build number or date): Sep 26 2019, at 17:32:39
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System information: https://gist.github.com/Jayman2000/5dde942d1193bb23d27ae722df2c0af7

#### Please describe your issue in as much detail as possible:

[A recent update to the New Library beta](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1591383946838639778) "[a]dded a 'filter by platform' button to Linux and MacOS that will filter the current game list to only games that run on the current platform."
##### Expected result
When the button turns blue, non-Linux games are hidden.
##### Actual result
When the button turns blue, nothing happens.
#### Steps for reproducing this issue:

1. Make sure that "Show only games that run on Linux" is turned off. The Tux icon should be gray.
2. Go to Steam>Settings>Steam Play, and make sure that both the "Enable Steam Play for for supported titles" and the "Enable Steam Play for all other titles" boxes are checked.
3. Press "OK", and restart Steam if prompted.
4. Open up the New Library, and press the "Show only games that run on Linux" button.

**Comment by kisak-valve** [comment]
Hello @Jayman2000, this issue is already being tracked at #5639. Closing as a duplicate.
