### ISSUE TITLE
Download speed is twice as high as the set speed limit 

### ISSUE THREAD

**Issue by Brn9hrd7** [ValveSoftware/steam-for-linux#6536]
#### Your system information

* Steam client version (build number or date): 09/19/2019
* Distribution (e.g. Ubuntu): ArcoLinux (Arch based)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After setting a speed limit for downloads the actual download speed is around twice as high as the set value(I've set it to 256KB/s and it downloaded with around 512 KB/s, after setting it to 128KB/s the download speed was around 256KB/s)   

#### Steps for reproducing this issue:

1. set a speed limit for downloads

**Comment by rphsoftware** [comment]
Can reproduce
Steam client application
Built: Oct 2 2019 at 18:45:57 (Latest stable it seems)

Distro: Ubuntu 18.04 LTS

Verified on my router that the client actually downloads at the doubled speed and not just misreports.

**Comment by Zamundaaa** [comment]
Happened once or twice to me, too. It's not the case anymore however.
This isn't even a steam-for-linux issue, my brother had (or perhaps still has) this happening on Windows as well.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by Brn9hrd7** [comment]
Just enabled the download limit and its downloading at the correct speed, so seems fixed.
Haven't used the feature in the last year or so though, so I don't have any (current) long-term experience.

**Comment by kisak-valve** [comment]
Thanks for rechecking. Closing as fixed some time ago.
