### ISSUE TITLE
Proton does not support Samba/NFS

### ISSUE THREAD

**Issue by tsalwierz** [ValveSoftware/steam-for-linux#6538]
In my testing proton does not support samba/nfs (v3 or v4) at all.

Native games run. Proton (kind of) works in that it allows configuration editors to be launched on games like Batman. But once you try to launch the game itself it either doesn't launch at all or does launch and crashes.

Samba works fine on windows as well.

I also tried using ln -s on steam to avoid having to add an external library, same issue.

I wasn't able to find any errors related to this. Steam is able to access all of the files just fine, can verify files, update files and launch games (other then proton).

**Comment by kisak-valve** [comment]
Hello @tsalwierz, this issue is already being tracked in https://github.com/ValveSoftware/Proton/issues/1910, https://github.com/ValveSoftware/Proton/issues/987. Closing as a duplicate.

**Comment by tsalwierz** [comment]
This is not related to that bug. Symbolic linking the game from /home/user/.local/share/Steam/steamapps/common/GAME to /home/user/smb-cluster/steam/GAME works fine with proton.

This issue is specifically related to the steam client not supporting proton on a second NFS/SMB library.

@kisak-valve

**Comment by tsalwierz** [comment]
![stuff](https://user-images.githubusercontent.com/7935624/65821544-d21a1680-e1eb-11e9-94e8-c7e5cfd7ed08.png)

**Comment by hlafaille** [comment]
Sorry to revive something dead, but running Proton games off a 10gig NFS connection, seems there's some issue with `steamapps/compatdata/*/pfx`

**Comment by hlafaille** [comment]
Update on this, I've found out that having a symlink for your "common" folder to your NFS and running with Proton 6.3-5 seems to get Cube World working. I've tried Doom 2016, it installs and launches without error but hangs on a black screen (which IDK is related to shader compilation). Installing Battlefield 1 right now, and will report back.
