### ISSUE TITLE
The "Compare your hardware to that of other Steam users" link doesn't work

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6540]
#### Your system information

* Steam client version: Sep 26 2019,  at 17:32:39
* Distribution: Xubuntu 19.04 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System info gist: https://gist.github.com/Managor/7841d190d3ca350a5a9cc32045c67b98

#### Please describe your issue in as much detail as possible:
When clicking on the "Compare your hardware to that of other Steam users" button on the System information window, it takes you to www.steampowered.com/status/survey.html which redirects to the front page of Steam

Here's video of it. https://youtu.be/yLpj-aggtF8

#### Steps for reproducing this issue:

1. Go to Help -> System Information
2. Click on the underlined link at the bottom of the window

**Comment by kisak-valve** [comment]
Works as expected here.

**Comment by Managor** [comment]
Did a small test. Opening the `www.steampowered.com/status/survey.html` link on Chromium works but opening the link with Firefox brings you to the steam front page.

https://youtu.be/jzfKlVt0nDU

**Comment by Managor** [comment]
I'm assuming the problem might be in the differences in how Firefox and Chromium handle HTTP 302

**Comment by Managor** [comment]
I found the culprit. It's the https everywhere addon. https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/reviews/

A simple fix for this would be to have the UI link to point to the correct website and not the one that needs redirecting.

**Comment by kisak-valve** [comment]
Hello @Managor, are you still experiencing this issue on an up to date system?

**Comment by Managor** [comment]
Yes, this issue is still present.

**Comment by Managor** [comment]
This has been fixed. The stats open up in steam itself so https everywhere can't affect it any more
