### ISSUE TITLE
Remote Play Causes the Client To Use A Full Core Even After Transmission Ends

### ISSUE THREAD

**Issue by Saroufim** [ValveSoftware/steam-for-linux#6541]
#### Your system information

* Steam client version (build number or date): 1569522541
* Distribution (e.g. Ubuntu): Fedora Silverblue 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

When using Remote Play from Linux, the host uses a full core just to stream the content. After transmission ends, the host keeps using a full core until Steam is shut down. Once Steam is closed, it restarts automatically. The automatically restarted Steam client appears to have the wrong fonts in the UI. Once it's shut down again, Steam can be safely restarted manually and it behaves normally again. 

#### Steps for reproducing this issue:

1. Open Steam (BPM or Desktop mode) and start Remote Play from a Steam Link Client
2. Stop transmission (CPU usage continues to be high)
3. Close Steam (Steam restarts automatically and with terrible fonts)

**Comment by kisak-valve** [comment]
Hello @Saroufim, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
