### ISSUE TITLE
Extremely Slow Downloads On Ubuntu 18.04 but very Fast on Ubuntu 19.04

### ISSUE THREAD

**Issue by TactikalKitty** [ValveSoftware/steam-for-linux#6545]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 19.04 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Original OS: I've always been a Linux Mint fan and recently came back to Linux with Linux Mint 19.2: Steam downloads were very, very slow. After resetting router, buying a new ethernet cable, thinking those were the issues, I decided to try a different distro. I Tried Ubuntu 19.04. Steam was surpisingly very fast with all downloads. I never cared for plain Ubuntu, so I tried Ubuntu Budgie which is also based on Ubuntu 19.04. Downloads again were extremely fast. While using Ubuntu Budige Steam would download games up to 50+Mbps. I was impressed.

However when using any distro that is based on Ubuntu 18.04 LTS, Zorin OS 15 or Linux Mint 19, for instance, Steam can barely achieve 1-5Mbps downloads.  I have 1Gbps Internet and am hard wired in. Speedtest.net would clock me around 800+Mbps.  Im worried because the Steam site says Ubuntu LTS is supported, but it seems like the Ubuntu 19.04 version has much better support, however, Ubuntu will be dropping support for 19.04 in January 2020.

#### Steps for reproducing this issue:

1. Using any distro based on Ubuntu 18.04 LTS
2. 
3.

**Comment by Myrddin-Wyllt** [comment]
On Ubuntu 18.04, is libnm-glib4 installed (both 32/64 bit)?

On Ubuntu 19.04, is libnm-glib4 installed (both 32/64 bit)?

**Comment by kisak-valve** [comment]
Hello @TactikalKitty, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
