### ISSUE TITLE
warframe drx10 or hide

### ISSUE THREAD

**Issue by IscanderWSD** [ValveSoftware/steam-for-linux#6548]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Hello my dear frend i have a problem drx10 problems with drx 9 does not support and 10 cannot deliver ubuntu 18 system
 
DirectX 9 support is over. We hope That you will be able to update your graphics card!
2. 
3. with respect Iscander

**Comment by kisak-valve** [comment]
Hello @IscanderWSD, we're tracking issues with games that are run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-536804392.
