### ISSUE TITLE
Cannot interact with the new Library with a game running

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6550]
#### Your system information

* Steam client version (build number or date): September 30th
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

System info: https://gist.github.com/LiamDawe/6ccacafad17b35b11b6e792e64fe04e2

#### Please describe your issue in as much detail as possible:

With the new GPU Acceleration fixes, the changelog noted the Steam client won't do stuff when a window is covering it up. However, it seems that needs tweaking. With Euro Truck Sim 2 loaded and I ALT+TAB I co no longer interact at all with the Steam Library.

#### Steps for reproducing this issue:

1. Load a fullscreen game
2. ALT+TAB
3. Try using the Library...

It's probably linked to this issue: https://github.com/ValveSoftware/steam-for-linux/issues/6549

As it seems after I quit the game, the Library is still unresponsive. Had to restart Steam to get it working again.

**Comment by McMarius11** [comment]
i have the same problem :/.
running KDE Neon with Nvidia drivers

**Comment by LiamDawe** [comment]
All good on this one.
