### ISSUE TITLE
Steam crashes at random times (related to libdbus-1.so.3.5.8)

### ISSUE THREAD

**Issue by nomis6432** [ValveSoftware/steam-for-linux#6551]
#### Your system information

* Steam client version (build number or date): 2019/10/02
* Distribution (e.g. Ubuntu): Arch Linux (up-to-date)
* Opted into Steam client beta?: [Yes/No] Yes (Problem also occurs in non-beta)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam crashes at random times (about once every 10 hours) and when a game is running at the same time that game will freeze. I get the following message in my journal:

`Process 2019 (steam) of user 1000 dumped core. Stack trace of thread 2101:
#0  0x00000000f425c214 n/a (/home/simon/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8)`

I've made a backtrace with the coredump [here](https://gist.github.com/nomis6432/1c1240b098b3f487634c4a3311a6009d) but it looks like I'm missing some symbols.

#### Steps for reproducing this issue:

There are no specific actions that trigger the crash. I'm using an Intel i5-6198DU CPU and no dedicated GPU.

**Comment by adojck** [comment]
I have same issue on Arch Linux. Started like a month ago or so. I get random crashes, but could not find any logs or info regarding the crash.

@nomis6432 how did you get that message?

I think it might be same issue.

**Comment by adojck** [comment]
I have same issue on Arch Linux. Started like a month ago or so. I get random crashes, but could not find any logs or info regarding the crash.

@nomis6432 how did you get that message?

**Comment by nomis6432** [comment]
@adojck The message I get with `journalctl` (press the end key to go to the end of your journal). The backtrace I get by debugging the coredump with `coredumpctl debug` and then running `bt`.

**Comment by kisak-valve** [comment]
Hello @nomis6432, this reads like the issue being tracked at #6318. Can you compare it to what you are seeing?

**Comment by nomis6432** [comment]
This seems to be the same issue indeed. [CheeseManFuus backtrace](https://gist.github.com/CheeseManFuu/d7790225689b81446f971a3a70d9ca9f) is very similar to mine.

**Comment by kisak-valve** [comment]
Thanks for checking, let's track this issue on the existing issue report.

Closing in favor of #6318.
