### ISSUE TITLE
DOOM 2016 crashes Steam Client every time when closing the game

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#6552]
#### Your system information

* Steam client version (build number or date): 1569883362
* Distribution (e.g. Ubuntu): Linux Mint 19.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Basically like i wrote in the title. Game works normally ( with Proton 4.11-6 in my case , i just forced it to use that version ) but when i press ESC and select " exit to desktop " that action leads to a Steam client crash within seconds. It does that every time. I'm attaching crash dumps i retrieved from /tmp/dumps to report also. 

#### Steps for reproducing this issue:

1. Open DOOM 2016 via Proton
2. Use Vulkan API with async compute - NO AA or TSAA 8X ( if that affects things )
3. Then select exit to desktop and witness Steam crash within seconds
[asus_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3683639/asus_log.txt)
[crash dumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/3683640/crash.dumps.tar.gz)

[asus_stdout.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/3683643/asus_stdout.tar.gz)

**Comment by kisak-valve** [comment]
For reference, crash_20191002235446_1.dmp is a SIGSEGV in libc-2.27.so coming from libvstdlib_s.so.

**Comment by MasterCATZ** [comment]
same 



Did not seem to matter if Opengl or Vulkan using Proton 4.x as 3.x lagged badly when ever mouse was touched , can run Vulcan on Ultra while Opengl has to be low for same FPS ... 








[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/3774362/dumps.zip)

**Comment by yuiiio** [comment]
looks same issue on wolfenstein 2.

**Comment by Leopard1907** [comment]
As a workaround , disable Steam Cloud for those titles until issue is solved.

**Comment by yuiiio** [comment]
foo thanks!

**Comment by xDShot** [comment]
Playing DOOM, it sometimes freezes. Killing the game crashes Steam client as well.

coredump: https://transfer.sh/%28/eENsA/doom_coredumpctl.tar.xz%29.tar.gz

**Comment by kisak-valve** [comment]
Hello, per "Fixed Steam client crash after exiting some AutoCloud-enabled games" in the [2019-11-07](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1600394952171527192) Steam client beta update, please opt into Steam's beta client if you haven't already and retest this issue.

**Comment by drcouzelis** [comment]
After a quick test with the latest Steam client beta update, it appears Doom 2016 is no longer crashing when attempting to use Steam Cloud. Thank you!

**Comment by Leopard1907** [comment]
I can confirm crash issue is fixed.

**Comment by yuiiio** [comment]
I can confirm too that fix.

**Comment by xDShot** [comment]
Didn't catch crashes so far.

**Comment by Leopard1907** [comment]
Seems like this fix is also on Stable client too. I've tested it on stable and it works on that channel too. This issue can be closed.

@kisak-valve

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing.
