### ISSUE TITLE
[STORE] Featured & recommended NEEDS to be Platform relative.

### ISSUE THREAD

**Issue by TriMoon** [ValveSoftware/steam-for-linux#6553]
#### Your system information

* Steam client version (build number or date): **Sep 30 2019 @21:41:49**
* Distribution (e.g. Ubuntu): **Kubuntu 19.04**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
When browsing games in the Library using "Featured & recommended" listing, it is VERY ANNOYING and **useless** to have titles listed that are incompatible with the platform the user uses !
Fe. I just noticed a game, new to me, that looked interesting so i wanted to try it out.
So i goto it's store page and click play to install it (a F2P game in this example).
But the DARN game seemed to be for Windows only, while i use Linux.
This is just a very FRUSTRATING experience, because WHY would any user be interested in games that are NOT meant for the platform they use at moment of browsing (Or better yet: Forced advertised by steam) ?

So PLEASE only show games that are relevant to the platform the user uses at moment of viewing !!!

#### Steps for reproducing this issue:

1. Do you **really** need steps for this? o.O

**Comment by kisak-valve** [comment]
Hello @TriMoon, please check that your Platform Preferences are set the way you want at Steam -> Settings -> View account details (top right) -> Preferences and scroll down that section.

**Comment by TriMoon** [comment]
> Hello @TriMoon, please check that your Platform Preferences are set the way you want at Steam -> Settings -> View account details (top right) -> Preferences and scroll down that section.

I have/had it set to "SteamOS + Linux"...

**Comment by OvermindDL1** [comment]
SteamOS is Linux though?
