### ISSUE TITLE
Can't play library' videos

### ISSUE THREAD

**Issue by Bumbadawg** [ValveSoftware/steam-for-linux#6555]
#### Your system information

* Steam client version (build number or date): 30th of september 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Can't play library video like these https://store.steampowered.com/app/1059340?snr=2_9_100006__apphubheader
It starts a blackscreen then stops.

**Comment by NoXPhasma** [comment]
Same for me, it won't happen anything. No matter what movie I try to play. On the console I get this error:
```
./ubuntu12_64/html5app_steam.sh: line 4: 28027 Segmentation fault      (core dumped) ${DIR}/html5app_steam "$@"
```

This is the content of that file:
```
#!/bin/bash
DIR=`dirname $0`
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:.:${DIR}:${DIR}/../linux64:"
${DIR}/html5app_steam "$@"
```

**Comment by lucifertdark** [comment]
Add me to the list of not being able to play videos, I'm getting the exact same error message as NoXPhasma.
https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02

**Comment by Bumbadawg** [comment]
It seems like it's missing configuration

```
GameAction [AppID 1059340, ActionID 1] : LaunchApp changed task to UnlockingH264 with ""
GameAction [AppID 1059340, ActionID 1] : LaunchApp changed task to WaitingOnWideVineUpdate with ""
Opted-in Controller Mask for AppId 1059340: f
Game update: AppID 1059340 "", ProcID 10516, IP 0.0.0.0:0
GameAction [AppID 1059340, ActionID 1] : LaunchApp changed task to Completed with ""
Starting app 1059340
>>> Adding process 10516 for game ID 1059340
CAPIJobRequestUserStats - Server response failed 2
>>> Adding process 10517 for game ID 1059340
>>> Adding process 10518 for game ID 1059340
>>> Adding process 10519 for game ID 1059340
>>> Adding process 10520 for game ID 1059340
Game removed: AppID 1059340 "", ProcID 10516 
Exiting app 1059340

```

**Comment by blooalien** [comment]
Me too, same issue, on Kubuntu 18.04 despite having watched videos on Steam successfully in the past.  Only just noticed the issue today, or I'd have come here looking for this issue sooner.

**Comment by Trenico** [comment]
Same here, I have tried playing videos on Kubuntu 18.04, 19.04 and 19.10, but it just closes and noting plays. It was working fine before the library update.

**Comment by Krafting** [comment]
Same issues on Linux Mint 19.2 and 19.3 I hope this will be fixed soon

**Comment by Morindhal** [comment]
I too suffer from this problem on the latest KDE Neon (Ubuntu 18.04 derived).
Tried it on 2 different hardware setups. (Intel integrated graphics and a non-integrated AMD card)

**Comment by zyll71** [comment]
Same on OpenSuSE Leap 15.1 with plasma.

**Comment by dearlygparted** [comment]
Same here on Arch Linux with the Steam Runtime enabled. All videos from the Steam Library (Steam store videos work fine) fail to play. When pressing play, the pop up appears and then disappears. When running Steam from the terminal, a segmentation fault in the HTML5 Steam app occurs:

`./ubuntu12_64/html5app_steam.sh: line 4: 12311 Segmentation fault (core dumped) ${DIR}/html5app_steam "$@"`

Other users have reported this issue on the Steam for Linux forum:

https://steamcommunity.com/app/221410/discussions/2/1638675549001453606/

**Comment by lucifertdark** [comment]
Library videos are now playable again. Ubuntu 19.10 nvidia 440.59 drivers.

**Comment by fallenguru** [comment]
Confirmed working again on Ubuntu 18.04.4 as well.

**Comment by Krafting** [comment]
Confirmed working on Mint 19.3 but only if you have the Beta channel for steam!

**Comment by Bumbadawg** [comment]
I confirm the beta channel did the trick.

**Comment by Bumbadawg** [comment]
Using Kwin scripts to auto-tile windows, i noticed the window when not in fullscreen, doesn't detect changed window dimensions (not using standard ratio), the canvas doesn't resize.
![image](https://user-images.githubusercontent.com/1251056/74589549-16248100-4ffe-11ea-8bc0-5cc95edeb41e.png)

**Comment by lucifertdark** [comment]
Ah I forgot I'm always using the beta channel.

**Comment by dearlygparted** [comment]
I can also confirm that it's working in the Steam Beta client (built Feb 15 2020). Still not working in the non-beta client (built Feb 11 2020).

**Comment by zyll71** [comment]
Confirm that the library videos are playing on OpenSuSE Leap 15.1 with NVIDIA 440.44 in Beta.
Thanks for fixing this, looking forward to having it pushed into the regular release.

**Comment by zyll71** [comment]
> Using Kwin scripts to auto-tile windows, i noticed the window when not in fullscreen, doesn't detect changed window dimensions (not using standard ratio), the canvas doesn't resize.
> ![74589549-16248100-4ffe-11ea-8bc0-5cc95edeb41e](https://user-images.githubusercontent.com/1251056/74589628-bbd7f000-4ffe-11ea-9708-fd97cc4c7634.png)

**Comment by zyll71** [comment]
I can confirm the issues with the resizing mentioned by Bumbadawg:

When I switch to full screen, the frame and content adapt correctly. When I go back to windowed mode, the image does not resize again but is simply cropped left and bottom.

**Comment by fallenguru** [comment]
FWIW, using a bog-standard Ubuntu [18.04.4] desktop, resizing is fine as well.

**Comment by lucifertdark** [comment]
Full screen & maximized window give the full picture, but resizing to a smaller window cuts off half the picture for me too, Ubuntu 19.10 desktop (Gnome), the videos play properly in Big Picture mode but it switches back to the standard desktop when exiting the videos.

**Comment by kisak-valve** [comment]
Closing as fixed.

@lucifertdark, feel free to open a new issue report for the follow up issue(s).
