### ISSUE TITLE
Steam client crashed every time after start

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#6556]
#### Your system information

* Steam client version (build number or date): 1569883362
* Distribution (e.g. Ubuntu): Fedora Rawhide
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
```
Installing breakpad exception handler for appid(steam)/version(1569883362)
Installing breakpad exception handler for appid(steam)/version(1569883362)
Installing breakpad exception handler for appid(steam)/version(1569883362)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Installing breakpad exception handler for appid(steam)/version(1569883362)
***** OUT OF MEMORY! attempted allocation size: 1048576 ****
memstd.cpp (2383) : Fatal Assertion Failed: OUT OF MEMORY
memstd.cpp (2383) : Fatal Assertion Failed: OUT OF MEMORY
memstd.cpp (2383) : Fatal assert failed: memstd.cpp, line 2383.  Application exiting.

memstd.cpp (2383) : Fatal assert failed: memstd.cpp, line 2383.  Application exiting.

assert_20191005110042_1.dmp[11996]: Uploading dump (out-of-process)
/tmp/dumps/assert_20191005110042_1.dmp
assert_20191005110042_1.dmp[11996]: Finished uploading minidump (out-of-process): success = yes
assert_20191005110042_1.dmp[11996]: response: CrashID=bp-192db859-e651-430a-9166-3d5682191004
assert_20191005110042_1.dmp[11996]: file ''/tmp/dumps/assert_20191005110042_1.dmp'', upload yes: ''CrashID=bp-192db859-e651-430a-9166-3d5682191004''
/home/mikhail/.local/share/Steam/steam.sh: line 720:  6566 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

[mikhail_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/3692910/mikhail_stdout.txt)
[mikhail_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3692911/mikhail_log.txt)
[assert_20191005110540_79.dmp](https://github.com/ValveSoftware/steam-for-linux/files/3692912/assert_20191005110540_79.zip)
[assert_20191005110652_127.dmp](https://github.com/ValveSoftware/steam-for-linux/files/3692913/assert_20191005110652_127.zip)
[assert_20191005110838_231.dmp](https://github.com/ValveSoftware/steam-for-linux/files/3692914/assert_20191005110838_231.zip)
[assert_20191005110042_1.dmp](https://github.com/ValveSoftware/steam-for-linux/files/3692915/assert_20191005110042_1.zip)

**Comment by NTMan** [comment]
[mikhail_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3694235/mikhail_log.txt)
[mikhail_stdout.txt](https://github.com/ValveSoftware/steam-for-linux/files/3694236/mikhail_stdout.txt)
[assert_20191006115154_466.zip](https://github.com/ValveSoftware/steam-for-linux/files/3694234/assert_20191006115154_466.zip)

**Comment by kisak-valve** [comment]
Closing as obsolete.
