### ISSUE TITLE
Library freezing randomly after memory leak fixes

### ISSUE THREAD

**Issue by Dragon8oy** [ValveSoftware/steam-for-linux#6557]
#### Your system information

* Steam client version (build number or date): September 30th
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When attempting to interact with the new library, the whole library freezes. No animations work, only the play button on the current game selected. I can't change the game that is selected either. The rest of Steam works, like swapping to the store page. When I swap back to the library, if I tried to select another game it will be selected when I swap back.

Restarting Steam only occasionally fixes the issue temporarily.

#### Steps for reproducing this issue:

1. Start Steam
2. Attempt to use the library
3. Library freezes

**Comment by kisak-valve** [comment]
Hello @Dragon8oy, this issue is already being tracked at #6499. Closing as a duplicate.
