### ISSUE TITLE
Make Steam detect and use system language

### ISSUE THREAD

**Issue by kassindornelles** [ValveSoftware/steam-for-linux#6558]
Currently a feature that exists on Windows but not Linux is support for system language detection, thus causing the client to boot using the system language (if supported by the client).

By default Steam starts in English (United States) even though my system is set to Portuguese (Brazil) 
(doesn't matter the distro being used.)
I have no knowledge on the subject but this guide seems to explain it better than me of how to detect system language at runtime, would be cool to see that in the client.
https://www.shellhacks.com/linux-define-locale-language-settings/

Detecting the system language at the moment Steam starts and forcing the system language into the client settings at least in the first boot.

**Comment by kisak-valve** [comment]
Hello @kassindornelles, this issue is already being tracked at #4882. Closing as a duplicate.
