### ISSUE TITLE
Micro-Freezes on Steam Client (that also extends to some games)

### ISSUE THREAD

**Issue by ammuench** [ValveSoftware/steam-for-linux#6559]
#### Your system information

* Steam client version (build number or date): 1570046470
* Distribution (e.g. Ubuntu): PopOS 19.04, Kubuntu 19.04
* Opted into Steam client beta?: [Yes/No] Yes & No (reproducible on both)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When using steam client every ~10s the entire client will hang/freeze and be unusable for 1-2s.  While playing Dota 2, the game freezes exactly when the client does.

All other system apps and programs are not affected and run normally during these freezes on the steam client

This issue appears on my system on both an up-to-date version on PopOS 19.04, and a 4-month out of date version of Kubuntu 19.04.  Both updated Steam to the same version.

I have installed steam through Steampowered.com, Ubuntu Repos, and Flatpak--all reproduce the same issue.

Example can be seen here: https://streamable.com/5glzk

#### Steps for reproducing this issue:

1. Load into Steam Client
2. Use it for 10s
3. Wait for 1-2s 
4. Repeat

**Comment by Vladimir-A** [comment]
Try disable GPU accelerated rendering in web views in steam settings.

**Comment by ammuench** [comment]
I've resolved the issue.  I had a an SN30 Pro controller plugged into my machine to charge.  Steam kept recognizing it as a Switch Pro Controller and polling it.  Every time it polled the controller, the freeze happened
