### ISSUE TITLE
Steam rendering bug

### ISSUE THREAD

**Issue by peon501** [ValveSoftware/steam-for-linux#6562]
#### Your system information

* Steam client version (build number or date): 1569883362
* Distribution (e.g. Ubuntu): Ubuntu 19.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes 

#### Please describe your issue in as much detail as possible:
Basically everything related to HTML is broken. Cant press buttons in the overlay and steam doesn't display anything.
![Screenshot from 2019-10-07 02-01-58](https://user-images.githubusercontent.com/1125765/66277463-a52ec900-e8a7-11e9-8d2d-a9a2135c886a.png)

#### Steps for reproducing this issue:
1. I just got this error after the system update.

**Comment by peon501** [comment]
Ubuntu update did some kind of update related to 64bit libs and removed something related to 5 ver. 
 of kernel.

**Comment by kisak-valve** [comment]
Hello @peon501, please check if this is the same issue as #6549 by disabling gpu acceleration for web views in Steam's settings.

**Comment by peon501** [comment]
Yea its the same problem. Works without it.
