### ISSUE TITLE
"View -> Update news" does not open anything

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#6563]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20190711.3
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* [Steam System information](https://gist.github.com/Zorrototo/533bb4f3b9d8d5abc137cd8cf5c00f02)

#### Please describe your issue in as much detail as possible:

When you click the Update news menu item, nothing opens, before it was opening a popup with the various Steam changelogs (like when there is an update available to download).

#### Steps for reproducing this issue:

1. Open Steam
2. click on the View menu
3. click on the Update news

**Comment by Zorrototo** [comment]
and this is a duplicate apparently https://github.com/ValveSoftware/steam-for-linux/issues/5086

**Comment by Myrddin-Wyllt** [comment]
#### Odd, this pops up no problem on my end:
![image](https://user-images.githubusercontent.com/42914865/66707729-0ec93000-ed0b-11e9-890c-4f31a76c5ece.png)

#### Do you have GPU acceleration enabled?
![image](https://user-images.githubusercontent.com/42914865/66707751-62d41480-ed0b-11e9-947c-1994eb7e6335.png)

On NVIDIA graphics, Steam can have issues with GPU acceleration. I'm using AMD graphics, so this might explain your issue.

**Comment by Zorrototo** [comment]
You're right, it now opens the popup, they changed something, I though it would open the update changelog though, the little windows you have when an update is available, it does not.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Zorrototo** [comment]
Actually, it now works but only when the setting "Notify me about additions or changes to my games, new releases, and upcoming releases". is ticked. When I tested with the setting ticked or not it wasn't working.
