### ISSUE TITLE
[Library Beta] Unable to set custom artwork from default browser directory

### ISSUE THREAD

**Issue by Vthyarilops** [ValveSoftware/steam-for-linux#6564]
#### Your system information

* Steam client version (build number or date): Sep 30 2019, at 21:41:49
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I placed my artwork into a folder i made in ~/.steam/artwork/, when I right click a game and choose custom artwork the browser starts in the path ~/.steam/ if I just browse to the "artwork" folder and choose the picture it will not set, I must first browse to / then manually browse back to /home/$USER/.steam/artwork, it must be something related to the relative path that the file explorer starts in.

#### Steps for reproducing this issue:

1. Put artwork somewhere in ~/.steam
2. Right click game, manage, choose custom artwork
3. Select the image from the file explorer without browsing back to / (select from the default directory)
4. Artwork won't set

**Comment by kisak-valve** [comment]
Hello @Vthyarilops, the custom artwork option you've described doesn't appear to be a stock Steam client feature? Are you using some kind of mod that adds it?

The file selection window you've described should be the same one that pops up when selecting a profile picture to upload. Can you check if that has the exact same behavior?

**Comment by Vthyarilops** [comment]
@kisak-valve No it is the new feature to set artwork in the Beta client's new UI, the file selection window is the same as when uploading a profile picture.
![Screenshot from 2019-10-07 15-10-57](https://user-images.githubusercontent.com/32111041/66341313-fa54f400-e914-11e9-9bce-830fb4702746.png)
![Screenshot from 2019-10-07 15-11-17](https://user-images.githubusercontent.com/32111041/66341316-fcb74e00-e914-11e9-9acf-3dc82872c2ec.png)

**Comment by kisak-valve** [comment]
Thanks for clarifying, I was looking at individual games instead of a Collection view.

**Comment by Vthyarilops** [comment]
@kisak-valve No problem, hopefully this gets fixed as it is rather tedious browsing manually through the entire hierarchy (especially if you have a lot of dot folders), simple trick is to copy the path and paste it in the "file name" box and hit open, saves having to browse manually.

**Comment by Managor** [comment]
The Steam filepicker needs a complete rewrite anyways.

**Comment by Managor** [comment]
This is probably not an issue any more as steam uses native filepickers now.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Sid127** [comment]
On arch linux, I'm unable to set custom artwork at all using the file picker.

KDE Plasma
file picker that's opened is xdg-desktop-portal-kde.

A friend also had this issue on Fedora KDE

**Comment by Isaac-Clarke** [comment]
> A friend also had this issue on Fedora KDE

I also have this issue, on Fedora KDE, right now.
I never tried before because it wasn't a priority, I was busy doing other things, but put simply:
I can select whatever image, but no matter the format or re-size, they don't apply on anything.

<img width="1024" height="1451" alt="Image" src="https://github.com/user-attachments/assets/b2bb2e49-ab88-4ebc-9673-8f5b2bffa03e" />

The file in question.
