### ISSUE TITLE
Steam client crashes on startup

### ISSUE THREAD

**Issue by gorky** [ValveSoftware/steam-for-linux#6565]
#### Your system information

* Steam client version (build number or date): Oct  2 2019 18:45:27 1570046470
* Distribution (e.g. Ubuntu): Linux Mint 19 (Ubuntu 18.04)
* Opted into Steam client beta?: [Yes/No] Yes(Maybe?)
* Have you checked for system updates?: [Yes/No] Yes

steve@thor ~ $ steam
Running Steam on linuxmint 19 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-10-07 19:44:59] Startup - updater built Oct  2 2019 18:45:27
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  42
xerror_handler: X failed, continuing
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  43
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-10-07 19:44:59] Checking for update on startup
[2019-10-07 19:44:59] Checking for available updates...
[2019-10-07 19:44:59] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-10-07 19:45:00] Download skipped: /client/steam_client_ubuntu12 version 1570046470, installed version 1570046470
[2019-10-07 19:45:00] Nothing to do
[2019-10-07 19:45:00] Verifying installation...
[2019-10-07 19:45:00] Performing checksum verification of executable files
[2019-10-07 19:45:00] Verification complete
<pre>***End of Run***</pre>
steve@thor ~ $ apt policy libnvidia-gl-435:i386
<pre>
libnvidia-gl-435:i386:
  Installed: (none)
  Candidate: 435.21-0ubuntu0~18.04.2
  Version table:
     435.21-0ubuntu0~18.04.2 500
        500 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic/main i386 Packages
<pre>

**Comment by gorky** [comment]
Steam was running last week, but when started today downloaded Oct 2 version and immediately failed.  NVidia drivers were updated from 390 -> 435, but to no avail.

**Comment by kisak-valve** [comment]
Hello @gorky, apt policy is telling you that the 32 bit userspace support for your updated nvidia driver is not installed, please install it with `sudo apt install libnvidia-gl-435:i386`.

**Comment by gorky** [comment]
That did it, thanks!
