### ISSUE TITLE
Unresponsive Beta UI

### ISSUE THREAD

**Issue by Alkaris** [ValveSoftware/steam-for-linux#6568]
#### Your system information

* Steam client version (build number or date): Oct 7 2019, 22:46:25
* Distribution: Linux Mint 19.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Alright this issue is quite annoying, and I'm sure other people are getting this very issue as well. The problem with the new Beta UI is that it becomes unresponsive and frozen completely, like you can't scroll or click on anything in your Library tab. Now the only workaround method to fix this issue is to click on another tab, let's say click on the Downloads section of Steam, and then clicking back on Library do you get back functionality to click on stuff in the Library and scroll the page on Library.

This too can also happen after closing a game you were just playing, the UI becomes unresponsive and frozen state where it'll still say the game you were just playing that is closed is still running, or it'll be stuck saying that the game is Syncing with the cloud backups. This level of unresponsiveness and stuck frozen screens shouldn't really be a thing here with the new UI. You would expect it to be fast and responsive and updates right away when you expect it to.

**Comment by kisak-valve** [comment]
Hello @Alkaris, this issue is already being tracked at #6499. Closing as a duplicate.
