### ISSUE TITLE
Switch Pro (unofficial) controller not being detected?

### ISSUE THREAD

**Issue by Ub3rZ4cH** [ValveSoftware/steam-for-linux#6570]
Same issue as https://github.com/ValveSoftware/steam-for-linux/issues/5479#issue-321572603
#5479

* Steam client version (build number or date): Oct 2 2019, at 18:45
* Distribution (e.g. Ubuntu): Lubuntu (Ubuntu 19.04)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I want to use my unofficial switch pro controller (previously worked) on steam for linux, but it does not detect, yet is being detected by other programs, and the os just fine.

`Local Device Found
  type: 20d6 a711
  path: 0007:0008:00
  serial_number:  - 0
  Manufacturer: 
  Product:      
  Release:      110
  Interface:    0

Unable to open local device: 0007:0008:00
`

https://imgur.com/djZdTiB

Bus 007 Device 008: ID 20d6:a711  
(could it be that it has no "name/manufacturer" here?

#### Steps for reproducing this issue:

Launch steam via console, see device found, yet when I go to big picture and steam big picture configuration "no controller detected".

**Comment by kisak-valve** [comment]
Hello @Ub3rZ4cH, is Steam installed with the distro-provided package or the Valve-provided package? If you're using the distro variant, than the udev rules from the `steam-devices` is out of date and should be adjusted to include these controller lines https://github.com/ValveSoftware/steam-devices/blob/0563be5d6ccda6efa615fd00c46c13f7961a3b5a/60-steam-input.rules#L28-L32.

**Comment by Ub3rZ4cH** [comment]
> Hello @kisak-valve I saw that, and placed the input rules over, but still no luck, I have a bunch of unofficial third party controllers, one which is a xbox one, that xbox one works I think because it has "XInput Controller" in the product field? but the others have nothing. 

Updating the udev rules I just place into "/etc/udev/rules.d" right?

**Comment by kisak-valve** [comment]
The udev config folder should match existing udev rules, which looks like it's `/lib/udev/rules.d` on Ubuntu.

**Comment by Ub3rZ4cH** [comment]
Ah I see they are located in a different place, I just tried and it still is a no go, shall I just reinstall steam with the steam provided package?

**Comment by jason-oliveira** [comment]
Having this same issue regularly in both Gentoo and Calculate Linux on a SN30 Pro in Switch Pro mode. When first paired over bluetooth, the controller works fine. As soon as the controller is powered off and back on, it will no longer be recognized by Steam. As a comparison, RetroArch will detect the device over and over, regardless of how many times you turn it off and on or re-pair the device, while Steam will ignore its existence completely. 

A workaround is to remove the controller's entry in bluetooth settings and re-pair every time you power on the device.

**Comment by TwistedAkai** [comment]
From the IDs, OP's controller is a PowerA Wired switch controller.

An Archlinux AUR package uses this rule for that controller:
`# PowerA Wired Controller for Nintendo Switch; USB
KERNEL=="hidraw*", ATTRS{idVendor}=="20d6", ATTRS{idProduct}=="a711", MODE="0660", TAG+="uaccess"`

**Comment by kisak-valve** [comment]
Closing pending feedback.
