### ISSUE TITLE
[Library beta] Recent Friends activity shelf is not visible on Linux

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6571]
#### Your system information

* Steam client version: Oct 7 2019, at 22:46:25
* Distribution: Xubuntu 19.04 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Currently I can't find a way to enable the Recent Friends Activity shelf under the Recent Games. This is what it looks on my PC
![image](https://user-images.githubusercontent.com/42655600/66517433-d39ce600-eaeb-11e9-90a9-dbd785bc6cb2.png)
And this is what it looks on my girlfriends PC
![image](https://user-images.githubusercontent.com/42655600/66517474-e2839880-eaeb-11e9-91f7-40ab064db8ac.png)
I have tried setting Low Bandwidth and Low Performance modes on and off. My steam profile is https://steamcommunity.com/id/managor/, if you need to pull logs.

**Comment by Managor** [comment]
Alright, this bug evolved after the latest update. The friend activity shelf just disappears after selecting it.

https://www.youtube.com/watch?v=rgpWy68VTJA

**Comment by Managor** [comment]
I'm fairly certain that I have friends playing games even if steam now tells me that there's no recent friend activity.

**Comment by SublustrisAvis** [comment]
I have 57 friends and I've never seen anything in this self even once from day one of the beta.

**Comment by Managor** [comment]
Same

**Comment by SublustrisAvis** [comment]
Although I didn't mention this is probably isn't Linux-specific, because I'm on Windows.

**Comment by Managor** [comment]
I don't know what happened, but today was the first time I saw anything on the friends activity shelf. For me it is now fixed.
![image](https://user-images.githubusercontent.com/42655600/69899513-fcb15880-136f-11ea-9054-521ad5cba140.png)

**Comment by Managor** [comment]
I assume this bug is moot now that the shelf no longer exists?

**Comment by kisak-valve** [comment]
Makes sense. Closing per the last comment.
