### ISSUE TITLE
Text doesn’t scale to tv. 

### ISSUE THREAD

**Issue by derekagraham78** [ValveSoftware/steam-for-linux#6572]
#### Your system information

* Steam client version (build number or date): 1570492308
* Distribution (e.g. Ubuntu): Manjaro 
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When looking at text either on beta or stable the text in all area is so tiny I have to use the zoom function on accessibility settings of Linux. No way to increase the font size and steam doesn’t scale with the operating system. I’m using 1920x1080 on a 1080p 40” hdtv. 
#### Steps for reproducing this issue:

1. Open steam
2. Look
3.

**Comment by shervinsahba** [comment]
Does running `GDK_SCALE=2 steam` from terminal help? See https://github.com/ValveSoftware/steam-for-linux/issues/5460

**Comment by kisak-valve** [comment]
Hello @derekagraham78, are you still experiencing this issue on an up to date system? In addition to the last comment, can you check the setting at `Steam` -> `Settings` -> `Interface` -> `Enlarge text and icons based on monitor size (requires restart)`?

**Comment by kisak-valve** [comment]
Closing pending feedback.
