### ISSUE TITLE
Controller doesn't initially work when starting game

### ISSUE THREAD

**Issue by ryester27** [ValveSoftware/steam-for-linux#6575]
#### Your system information

* Steam client version (build number or date): 10/7/2019
* Distribution (e.g. Ubuntu): Arch Linux w/ KDE Plasma 5.16.5
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When starting any game (either native or proton game), controller button presses do not register  in-game initially. Instead, button presses play sound effects from the Overlay/Big Picture mode, suggesting that the button inputs are stuck in some hidden overlay interface. I am able to get the controller to work in-game by pressing the 'A' button a couple of times.

Tried disabling several options such as hardware accelerated rendering and smooth scrolling. Disabling the overlay per-game also doesn't help.

Log of a game experiencing the problem here:
https://gist.github.com/ryester27/e3f88e51c18341c9ad9aeff79e7c352c

#### Steps for reproducing this issue:
1. Launch game
2. See issue

**Comment by ryester27** [comment]
@kisak-valve I figured out what the issue was. It's the "Use Big Picture Overlay when using a Steam Controller from the desktop" option causing problems. Disabled it, and everything works as intended again.

**Comment by joeknock90** [comment]
Same Issue, also solved by turning off "Use Big Picture Overlay when using a Steam Controller from the desktop". However, that stops me from being able to change configs easily in game =[

**Comment by loisgomez** [comment]
Thanks for the workaround.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Same here. It's actually stuck at the big screen overlay homescreen, so you can navigate to the exit button and quit the overlay, after which the controller stops working until you restart the game :smiley:

**Comment by ryester27** [comment]
Can someone else confirm that this issue is resolved? I enabled "Use Big Picture Overlay when using a Steam Controller from the desktop" again just recently, and saw that everything was working properly.

**Comment by kisak-valve** [comment]
Closing pending feedback.
