### ISSUE TITLE
Scrollable surface with scrollbar appears in the new game uninstallation UI

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6576]
#### Your system information

* Steam client version (build number or date): Oct 11 2019, at 23:19:39
* Distribution (e.g. Ubuntu): Fedora 30 Workstation
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While this might not exactly be a bug, I don't think it makes much sense for this to be a scrollable surface: 
![image](https://user-images.githubusercontent.com/4428753/66703466-37edbe80-ed13-11e9-8039-2e7686efbb9a.png)

#### Steps for reproducing this issue:

1. Uninstall any given game 
2. Observe a scrollable surface with scrollbar where it is not needed

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Newbytee** [comment]
Sorry, I forgot to respond after checking this. I can't reproduce it any more.
