### ISSUE TITLE
Steam not remembering password

### ISSUE THREAD

**Issue by mdjhd** [ValveSoftware/steam-for-linux#6578]
#### Your system information

* Steam client version (build number or date): Steam package version: 1570046470 built: Oct 2 2019
* Distribution (e.g. Ubuntu): Windows 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When loging in the steam client with "Remember password" option checked and then exiting steam and trying to log in again it asks for password although it shouldn't

#### Steps for reproducing this issue:

1. Log in into the client with "Remember password" option checked
2. Close/Exit the client
3. After opening the client again it ask for credentials

**Comment by kisak-valve** [comment]
Hello @mdjhd, this issue tracker is meant for issues with the Steam for Linux client. Please use [Steam Support](https://help.steampowered.com/) to report issues with the Windows client.

**Comment by mdjhd** [comment]
Hello @kisak-valve, but I already tried Steam Support. The thing is that this is happening on both Windows and Linux as I've tried on both systems. And when asking on Steam Support for help I did put both operating systems in description (Ubuntu and Windows 10) and they redirected me here.
