### ISSUE TITLE
Steam not remembering password

### ISSUE THREAD

**Issue by mdjhd** [ValveSoftware/steam-for-linux#6579]
#### Your system information

* Steam client version (build number or date): Steam package version: 1570046470 built: Oct 2 2019
* Distribution (e.g. Ubuntu): Ubuntu (official and spins all versions) and also on Windows 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When loging in the steam client with "Remember password" option checked and then exiting steam and trying to log in again it asks for password although it shouldn't

#### Steps for reproducing this issue:

1. Log in into the client with "Remember password" option checked
2. Close/Exit the client
3. After opening the client again it ask for credentials

**Comment by kisak-valve** [comment]
Hello @mdjhd, the linux variant of this issue is already being tracked at #5030 / #5035. Closing as a duplicate.
