### ISSUE TITLE
Switching games view is slow

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6580]
#### Your system information

* Steam client version (build number or date): Oct 11 2019, at 23:19:39
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Current library has increased latency in some parts.

1. ~~Home screen is faster, game carts animate faster, better latency than in prev. beta~~
2. ~~Left sidebar game list feels slow on animations(mouse hover)~~
3. Switching games feels bit strange, i think it's because highlighting row in view is bit faster, than switching game view
4. ~~News modal(when you click on news item and full news shown) is very slow and choppy~~

UPD:
GPU acceleration was disabled. I thought i enabled it. With GPU accel enabled, everything is much faster.
News modal is not slow and choppy, left sidebar animations are fast.
I hope switching games view could be faster.

**Comment by kisak-valve** [comment]
Hello @XakepSDK, are you still experiencing this issue on an up to date system? This reads as general performance characteristics of libcef when it is configured to be CPU-only.

**Comment by XakepSDK** [comment]
I think this is solved
