### ISSUE TITLE
Preparing to launch Left 4 Dead 2 but the game is not launched

### ISSUE THREAD

**Issue by nbro** [ValveSoftware/steam-for-linux#6582]
#### Your system information

* Steam client version (build number or date): October 2 2019, at 11:54:50
* Distribution (e.g. Ubuntu): Mac OS X Catalina (10.15)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I click to launch the game Left 4 Dead 2, which yesterday was working, the usual pop-up window says "Preparing to launch Left 4 Dead 2...", then the pop-up window disappears, and nothing happens, so the game is not launched. This happened only today, after I updated my Mac OS X from Mojave to Catalina. I have not tried with other games, as I don't have other games installed. I uninstalled the game, then re-installed, but I was having the same issue. I also tried to re-install Steam, but the problem persists.

**Comment by kisak-valve** [comment]
Hello @nbro, this issue tracker is for issues with the Steam for Linux client. That set aside, Apple dropped support for all 32 bit applications in Mac 10.15 and you've encountered https://github.com/ValveSoftware/Source-1-Games/issues/2847.

Closing in favor of the existing issue report.
