### ISSUE TITLE
[Library Beta] Error adding item to wishlist

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6584]
#### Your system information

* Steam client version (build number or date): 
![Screenshot_2019-10-13_12-50-45](https://user-images.githubusercontent.com/6024315/66719622-185ca180-edb8-11e9-8bcc-e08cb1fdf4be.png)
* Distribution (e.g. Ubuntu): Xubuntu 19.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Library Beta displays an error when attempting to add an item to your wishlist.

![Screenshot_2019-10-13_12-49-25](https://user-images.githubusercontent.com/6024315/66719610-f19e6b00-edb7-11e9-90be-2d838a950819.png)
![Screenshot_2019-10-13_12-44-27](https://user-images.githubusercontent.com/6024315/66719611-f400c500-edb7-11e9-8903-01196c8c61ec.png)

#### Steps for reproducing this issue:

1. Open Library
2. Select feed item with an embedded button to add a game to your wishlist
3. Click button to add game to wishlist
4. Experience error

**Comment by mbp2728** [comment]
Hello, I have the same issue. It started to happen in 2021. Do you have a solution? My error does not say it's a network error. It just show a standard error msg and to try again later.

**Comment by kisak-valve** [comment]
Hello @nightsky30, @mbp2728, are you still experiencing this issue on an up to date system?

**Comment by nightsky30** [comment]
@kisak-valve I cannot reproduce the issue, and the original post's content has changed in the last two and a half years. The wishlist button on that post no longer exists.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
