### ISSUE TITLE
[Beta] When gpu acceleration is on , every clickable or mouse browseable item acts like they're offset

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#6586]
#### Your system information

* Steam client version (build number or date): Oct 11 2019
* Distribution (e.g. Ubuntu): Linux Mint 19.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Like described in title , easy to repro. It doesn't happen when gpu accel is off.
#### Steps for reproducing this issue:

1. Use Steam client with gpu accel on 
2. Browse over achievements etc or any other item on library and store , profile view ( it also affects store and profile sections )
3. Observe the difference

**Comment by Myrddin-Wyllt** [comment]
Another Nvidia-specific issue with GPU acceleration?

My AMD machines don't have this issue.

**Comment by Leopard1907** [comment]
Looks like it is fixed on latest beta,despite there is no changelogs about it. @kisak-valve Feel free to close it.

**Comment by kisak-valve** [comment]
Thanks for letting us know. Best guess is it was the CEF update in the [2019-10-24](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1656688677563235889) Steam client beta update that made a difference.
