### ISSUE TITLE
System text size being ignored, text too small as result

### ISSUE THREAD

**Issue by awsdert** [ValveSoftware/steam-for-linux#6587]
#### Your system information

* 1570045470: 
* Manjaro x64 cinnamon: 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, automatic on opening steam

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen

Steam to load system set font size, my screen is projected onto a wall so I need larger text, the client should abide by that instead of a stupid calculate by screen size option

and what _did_ happen. 

It ignored the font size I had set and went with uber small text, I have to zoom in on the screen just to read it

**Comment by kisak-valve** [comment]
Hello @awsdert. this issue is already being tracked at #5460. You should be able to force steam to scale the output by running it with `GDK_SCALE=2 steam` on a terminal. Finer grained scaling is being tracked at #5908.

Closing as a duplicate.

**Comment by awsdert** [comment]
That's not acceptable for user end! Stop thinking as a developer and start thinking as a user! A user should only have to boot up steam normally, not fiddle with the boot options!

**Comment by awsdert** [comment]
With the help of lutris I ran it with that option and no it did NOT fix it, issue should remain open until I tell you it is fixed!

**Comment by awsdert** [comment]
Finally found the reopen button, was never resolved

**Comment by guivi01** [comment]
I agree, the solution mentioned by Kisak-valve is not a solution but a workaround. And not a very good one for a user point of view. I have found a comment on askubuntu with another workaround with using skins but it is not the best either:
Source: https://askubuntu.com/questions/771056/gui-dpi-scaling-on-certain-apps-very-small
---------------------------------------------------------------------------------------------------------------------------
Currently steam hardcoded the font size on linux.
The only way I found to increase the font size is to use a HiDPI skin
Installation:
    1- Open terminal
    2- cd to your steam skin directory (see note)
    3- Clone the repo(you must have git installed sudo apt-get install git)
        git clone https://github.com/MoriTanosuke/HiDPI-Steam-Skin.git
Then open Steam and go to Settings->Interface. Choose the new skin "HiDPI-Steam-Skin"
NOTE: The exact path to the skins might be different depending on your installation.
It might be located at ~/.steam/skins/ or ~/.local/share/Steam/skins/.
----------------------------------------------------------------------------------------------------------------------------
It would be best if Steam developers add a scaling factor on the Steam->Settings->Interface. If skins can be made which set the font size I am not sure what is stopping them from having some kind of factor multiplier.

Best regard,

**Comment by deaniiyu** [comment]
As of April, 2021 the font size of steam linux remains uncustomizable. I might be mistaken here but honestly I don't think it is so hard to implement, no?
The GDK_SCALE method works fine, but not satifactory, as it only accepts integer but I want something like x1.5 or x1.7. And I don't really like the idea of running steam with a terminal attached to it, currently I start steam in a tmux session but still not a very elegant way from user POV..

**Comment by jasonpremchand** [comment]
`[Desktop Entry]
Name=Steam
Comment[fr]=Application de gestion et d'utilisation des jeux sur Steam

Exec=env GDK_SCALE=2 /usr/bin/steam %U
#Exec=sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U
Icon=steam
Terminal=true
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;x-scheme-handler/steamlink;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true

[Desktop Action Store]
Name=Store
Name[fr]=Magasin

Exec=steam steam://store

[Desktop Action Community]
Name=Community
Name[fr]=Communauté

Exec=steam steam://url/SteamIDControlPage

[Desktop Action Library]
Name=Library
Name[fr]=Bibliothèque

Exec=steam steam://open/games

[Desktop Action Servers]
Name=Servers
Name[fr]=Serveurs

Exec=steam steam://open/servers

[Desktop Action Screenshots]
Name=Screenshots
Name[fr]=Captures d'écran

Exec=steam steam://open/screenshots

[Desktop Action News]
Name=News
Name[fr]=Actualités

Exec=steam steam://open/news

[Desktop Action Settings]
Name=Settings
Name[fr]=Paramètres

Exec=steam steam://open/settings

[Desktop Action BigPicture]
Name=Big Picture
Exec=steam steam://open/bigpicture

[Desktop Action Friends]
Name=Friends
Name[fr]=Amis

Exec=steam steam://open/friends`

**Comment by jasonpremchand** [comment]
My last comment is what my 'steam.desktop' file looks like, the one from my "/usr/share/applications/" directory.

The scaling worked after I added
"Exec=env GDK_SCALE=2 /usr/bin/steam %U" ;

and commented out;

"#Exec=sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U"


PS. I only use English and French so I removed the other language lines, I'm not sure if this is advisable but I haven't had any issues yet.

**Comment by awsdert** [comment]
Welp, from now on, until valve get's it's ass in gear and fixes this issue instead of pretending it isn't with a non-working solution of GTK_SCALE, I'm just gonna use GameHub as they at least have their priorities right, they don't ignore users when they report a problem with the interface

**Comment by palmerbomber1** [comment]
A non command line solution I found, which I found this thread in the same search that led me to the other, is to open steam into big picture and then close big picture after launching steam. Will have to be done every time, but it fixes the text size to something legible for all menus and the top bar where "steam, view, friends, games, and help" live.

You dont have to wait for big picture to fully launch, what I do is launch steam, right click on the icon and select big picture, then right after right click again and exit big picture and the entire UI is resolved for that session
