### ISSUE TITLE
There have been too many login failures from your network in a short time period. Please wait and try again later.

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/steam-for-linux#6595]
#### Your system information

* Steam client version (build number or date): not related
* Distribution (e.g. Ubuntu): Arch, probably not related
* Opted into Steam client beta?: [Yes/No] not related
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I try to login into Steam in Chromium browser, "There have been too many login failures from your network in a short time period. Please wait and try again later." error pops up, although I didn't make any login tries before. I'm sure I did type my password correctly. Happen with both main and alt accounts. I do login into Steam client fine.

#### Steps for reproducing this issue:

1. Open Chromium
2. Open steamcommunity.com
3. Try to login

**Comment by batcha88** [comment]
Same issue here.

Originally I did enter the false code by accident, but now even after 24h I'm still getting the error.
Confirmed with Chrome on Fedora 30, iOS and Windows 10 from within my network.

Firefox seems to work fine though, it has something to do with Chrome.

**Comment by xDShot** [comment]
Well, after several days it now does allow me to login into browser. Would love there was some mechanisms that would enlighten us exact reasons it won't pass (like which IP it was been accesed, user agent, attempts count, etc.).

**Comment by byte1024** [comment]
It looks like its Chromium browser, user error, or some more specific events. I just tested with Chrome (not Chromium) and it worked fine 1st go, signed out and entered in 2 wrong attempts on purpose, 3rd attempt also worked fine.

You may need to test it more and add to the steps for reproducing the problem. Valve won't necessarily say if they will do more to find the problem.

**Comment by kisak-valve** [comment]
Hello @xDShot, @ebrodlic, have either of you seen this issue since it was initially reported?

**Comment by xDShot** [comment]
None
