### ISSUE TITLE
Chat Emoticons Picker Scrollbar Spasms

### ISSUE THREAD

**Issue by Myrddin-Wyllt** [ValveSoftware/steam-for-linux#6597]
#### [Your system information](https://gist.github.com/Myrddin-Wyllt/4cc23dfec5512efc59b4d93336a6d36b)

* Steam client version (build number or date): Oct 15 2019
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Emoticon Picker in chat opens a popup window. There is an issue with the scrollbar appearing within that popup:
![Peek 2019-10-18 14-37](https://user-images.githubusercontent.com/42914865/67123970-301c9700-f1b7-11e9-9e03-8865e642047f.png)
#### Steps for reproducing this issue:

1. Open Steam chat
1. Click on the **Emoticon Picker**
1. Move the cursor to the bottom-right corner, on top of the newly appearing scrollbar

**Comment by kisak-valve** [comment]
Hello @Myrddin-Wyllt, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Myrddin-Wyllt** [comment]
This has been fixed.
