### ISSUE TITLE
[Library Beta] Can't manage DLC

### ISSUE THREAD

**Issue by ritalat** [ValveSoftware/steam-for-linux#6599]
#### Your system information

* Steam client version (build number or date): Oct 15.
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking the "Manage My x DLC" button does nothing. On the Windows client it opens a new window for managing your DLC.

#### Steps for reproducing this issue:

1. Click the "Manage My x DLC" button

**Comment by Skiski** [comment]
I have the exact same problem.
I want to uninstall the HD pack for Shadow of Mordor and I can't...

**Comment by Newbie13XD** [comment]
It works for me on Fedora 30. I was able to start downloading the HD pack and then cancel it, then start it again. 

To be clear, this was via the Manage My X DLC button, not the properties window.

**Comment by Skiski** [comment]
It's strange, I'm also on fedora 30 with gnome...

**Comment by ritalat** [comment]
The manage DLC button is now working properly with the library beta build from Oct 30.
