### ISSUE TITLE
Licensing: putting Steam in other Linux distro repositories

### ISSUE THREAD

**Issue by slix** [ValveSoftware/steam-for-linux#66]
It seems that some distributions, including [Arch Linux](https://mailman.archlinux.org/pipermail/arch-dev-public/2012-November/024040.html), are hesitant to put Steam in their repositories because it is unclear whether they have legal permission to.

Is Valve going to do anything about this in the near future like create distribution agreements or create a general license?

**Comment by Cyncrovee** [comment]
I'm not sure how many people noticed but they changed the license in the COPYING file that comes with the tarball at https://repo.steampowered.com/steam/ (seems to have been changed with 1.0.0.55~).

The new one doesn't mention redistribution rights, and while there is a "For Linux Distributions" section on the linked website which _could_ hint at redistribution rights? (I'm not a lawyer, this is not legal advice. I'm very uncertain about this) It's still quite unclear. Irrc one of the files is even listed as all rights reserved. I feel like this should be addressed.
