### ISSUE TITLE
[Beta] Client doesn't save password

### ISSUE THREAD

**Issue by Rene2LeLorrain** [ValveSoftware/steam-for-linux#6601]
#### Your system information
* Steam client version (build number or date): 1571182697 of 01ct 15 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04.1 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On login for the second time after the update, the saved password does not show and I have to re-enter it.Of course, the first time I did click the "Save Password" case!

**Comment by kisak-valve** [comment]
Hello @Rene2LeLorrain, this issue is already being tracked at #5030 / #5035. Closing as a duplicate.
