### ISSUE TITLE
Tiny "steam update" window

### ISSUE THREAD

**Issue by craig-sanders** [ValveSoftware/steam-for-linux#6607]
#### Your system information

* Steam client version (build number or date): 1571182697
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When the steam client detects that a new version of itself is available, it pops up a window to alert the user.

For the last few versions, that window has been **tiny** (128 pixels wide x 66 pixels high) and therefore unreadable and useless - it's not even big enough to show the buttons, let alone the update news.  BTW, the window is not resizable, either.

If I close that useless window and click on the `Steam -> Check for Steam Client Updates` menu option, I get the same window but with usable geometry (460x518).

#### Steps for reproducing this issue:

1. wait for steam client to detect new version
2. ???
3. profit

PS: it would be useful if the `About Steam` dialog box contained copy-able text fields, so that the build date and/or version number could be copy-pasted into Issues here, rather than an error-prone re-typing by fallible humans.   I know this is unusual in Windows, but it's standard and expected on Linux.   Dialog text that you **can't** copy-paste into, e.g., a google search is useless for, e.g., diagnostic purposes.

**Comment by kisak-valve** [comment]
Hello @craig-sanders, this issue is already being tracked at #1762. Closing as a duplicate.
