### ISSUE TITLE
Add cloud saving to all games

### ISSUE THREAD

**Issue by monterrr** [ValveSoftware/steam-for-linux#6610]
#### Your system information

* Steam client version (build number or date): 2/10/19
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

I think steam could add cloud saving to all games, even ones without support for it.

**Comment by kisak-valve** [comment]
Hello @monterrr, save game locations are not standardized and this needs to be configured on a per-game basis. Additionally, games that support multiple OSes have to consider possible cross-OS variations in the save file format and what effect that may have before setting up a common save folder or making per-OS save folders to avoid conflicts.

There's no magic bullet to enable this for all games.

**Comment by monterrr** [comment]
Can at least steam add the option for the user to do the heavy work and save the files that the user identifies manually as the saves?
