### ISSUE TITLE
Steam does not disable audio on host when streaming to Steam Link

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6611]
#### Your system information

* Steam client version:
![image](https://user-images.githubusercontent.com/42655600/67408011-03a2b980-f5c1-11e9-81e2-1121b8449a32.png) 
* Distribution: Ubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System Information gist: https://gist.github.com/Managor/a3170735dd2fe6cfe022806814c064c5

#### Please describe your issue in as much detail as possible:
Steam does not disable audio on the host machine when streaming to Steam Link. Even though the `Settings -> Remote Play -> Advanced Host Options -> Play audio on host` is disabled. Noticed this difference recently when streaming from someone else's Windows computer that audio is disabled on the host and it doesn't do the same on Linux.

#### Steps for reproducing this issue:

1. Have the aforementioned setting turned off
2. Stream from Linux to Steam Link 
3. Listen to audio from the PC

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #6512. Closing as a duplicate.
