### ISSUE TITLE
Unable to install games directly to NFS share

### ISSUE THREAD

**Issue by viggy96** [ValveSoftware/steam-for-linux#6612]
#### Your system information

* Steam client version (build number or date): 19 October 2019
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When user attempts to install a game on a NFS v4 share, the client reports a disk write error, and the following in the terminal:
```
GameAction [AppID 280160, ActionID 2] : InstallApps changed task to RemoveGameDemos with ""
GameAction [AppID 280160, ActionID 2] : InstallApps failed with AppError_11 with "/media/NFS/SteamLibrary/steamapps/downloading/state_280160_280162.patch"
```
However, installing the game to an ext4 partition, and moving the game to an NFS v4 location works just fine. 

#### Steps for reproducing this issue:

1. Try to install game on NFS v4 share

**Comment by kisak-valve** [comment]
Hello @viggy96, this issue is already being tracked at #5788. Closing as a duplicate.

**Comment by bphd** [comment]
Trying to install MSFS 2020

```
GameAction [AppID 1250410, ActionID 1] : InstallApps changed task to CreateNextApp with ""
GameAction [AppID 1250410, ActionID 1] : InstallApps failed with AppError_11 with ""
```
