### ISSUE TITLE
File manager general problems: Always opening on steam dir, always shows hidden files, etc

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/steam-for-linux#6613]
#### Your system information

* Steam client version (build number or date): 24-10-2019
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam's file manager has always been pretty bad, but you didn't need to use it so much so it was never a real problem. But now i'm trying to fill my library with cover arts and logos since a lot of devs doesn't care and won't upload any.
This are some of the problems with it:
1. Everytime you open it it will be placed at Steam install folder, this wouldn't be too bad since you could just go up in the tree to go to "/home/user/" but the file manager won't let you use that button, it does nothing, it forces you to choose a unit at the top panel, in which i can only select root "/" and then i need to go trough "/home/user/" to find my files, this isn't saved, so the next cover art i want to add is the same problem over and over again.
2.  It always shows hidden files, so when i reach "/home/user/" there is a lot of configuration folders like "/.local/" or "/.gnome/", there are a lot of them so it's more time consuming to search for my images folder.
3. File manager won't show thumbnails, seems like a little unimportant thing, but searching for images is a deal breaker.
4. At the bottom part of file manager you can see "File type" and it's blank, so you can see videos, texts, everything, if I'm searching for cover arts the search should be limited at JPG, PNG and APNG, so the tree wont get cluttered by unusable files.
5. File manager won't remember window size or any change at the columns, this, combined with the very little size of text and icons make things very difficult.
6. When trying to add a Steam library folder, it always opens "ubuntu12_32" folder, that has no sense, it should start on root "/".

#### Steps for reproducing this issue:

1. Try to add a customized logo, banner or cover art.
2. Or try to add a new Steam Library folder.

#### Screenshots comparing how steam file manager works and how would look if it was a native thing.

![Captura de pantalla de 2019-10-25 18-06-13](https://user-images.githubusercontent.com/44957566/67588016-5b722980-f755-11e9-8514-b6b651fe75d3.png)
![Captura de pantalla de 2019-10-25 18-12-30](https://user-images.githubusercontent.com/44957566/67588017-5c0ac000-f755-11e9-8f94-1df37364b7bd.png)
![Captura de pantalla de 2019-10-25 18-23-50](https://user-images.githubusercontent.com/44957566/67588019-5c0ac000-f755-11e9-9b44-aade80dba9ee.png)

**Comment by KibaGasteiz** [comment]
There is 2 possible solutions here, making a "Library beta" style file manager with all this issues solved, or use the same native solution as GTK or QT applications.

**Comment by ananace** [comment]
Considering that many pieces of software are now using the xdg-desktop-portal system, perhaps Steam could also allow for that as well - using an environment flag or a DBUS query? Then the file chooser would use the system implementation, and Steam wouldn't have to maintain their own Linux-specific code for a file choosing dialog.

**Comment by nightsky30** [comment]
Thank you for this.  I'd also like to mention what I experienced with sorting in #6231

**Comment by kisak-valve** [comment]
Hello @KibaGasteiz, the [2022-03-31](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3189118991320514548) Steam client beta update should address some of this feedback.

**Comment by KibaGasteiz** [comment]
Great work, still not perfect but adding covers is MUCH better now :D
