### ISSUE TITLE
Latest Linux client does not accept "£" as a password character.

### ISSUE THREAD

**Issue by PaulEden** [ValveSoftware/steam-for-linux#6614]
#### Your system information

* Steam client version (build number or date): Unknown - Attemoting to install "steam_latest.deb"
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes (but not applied as not logged in to account)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Windows and web logon allows this character.  Current downloaded linux client does not.  Character proven to be working via linux text editor and logging into steam via web on same machine.

#### Steps for reproducing this issue:

1. load Steam client
2. Attampt to type "£" into the password box
3. No character appears.

**Comment by kisak-valve** [comment]
Hello @PaulEden, this issue is already being tracked at #4712. Closing as a duplicate.
