### ISSUE TITLE
Steam controller: No mouse cursor support on Wayland

### ISSUE THREAD

**Issue by TRPB** [ValveSoftware/steam-for-linux#6615]
#### Your system information

* Steam client version (build number or date): October 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When using Xorg, the steam controller functions as a mouse using the touchpad. Under Wayland (at least on KDE), the buttons work fine but mouse cursor emulation is broken.

#### Steps for reproducing this issue:

1. Log in to a wayland session
2. Launch Steam
3. Try to use the controller to move the cursor

**Comment by kisak-valve** [comment]
Hello @TRPB, this issue was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/4738#issuecomment-271682124.

**Comment by IDeathByte** [comment]
Approve this, but with one clarification
Mouse emulation works but cursor is invisible
As in the system there are 2 mice, but pointer movements are drawn only for the main device
Tested on wayland session KDE Plasma 5.12-5.17

**Comment by FreeFull** [comment]
While Steam is running, the mouse emulation only works for X11 windows running through Xwayland (with the invisible cursor). While Steam isn't running, (and the controller is using Linux's built-in driver), it works as expected.

**Comment by TRPB** [comment]
interesting, that doesn't work for me. With steam closed the cursor doesn't move at all.

**Comment by FreeFull** [comment]
You can also try https://github.com/kozec/sc-controller , it has worked well for me together with the sway wayland compositor. But, it shouldn't be necessary, the controller has automatically worked for me without it too.

**Comment by TRPB** [comment]
Than you. Yes, sc-controller works great under wayland.

**Comment by ruineka** [comment]
This holds true today as well but its more than just the steam controller its any device using steam input to move the mouse. It's an issue on the OneXPlayer and Aya Neo.

**Comment by goarvic** [comment]
Any news? This bug has been present since 2019 and there is still no solution?

**Comment by IDeathByte** [comment]
> Any news? This bug has been present since 2019 and there is still no solution?

I didn't check, but as i know, we are still here.
I use [gamescope](https://github.com/Plagman/gamescope) as workaround now, and it solve most problems

**Comment by Crono141** [comment]
This issue was closed erroneously.  Steam deck works fine, yeah, but that's because everything runs through gamescope.  For other linux distos this issue is still present.  The gamescope workaround is just that, a workaround, not a solution.

**Comment by FF-AntiK** [comment]
I switched to KDE Plasma (wayland session) recently and have the exact same problem. Using gamescope might be an ingame workaround but gamescope won't get you anywhere trying to control the (KDE) desktop with the steamcontroller while steam is open.

**Comment by gnufred** [comment]
This is absolutely still a problem. Have the exact same issue on KDE Plasma. Mouse emulation work but the cursor is not moving. Makes issue needs to be reopened.

**Comment by UniqueUsername5** [comment]
This bug is still very much alive for me.
The issue is set to closed.
Does anyone have a solution I have missed?

**Comment by FF-AntiK** [comment]
Nope, still not solved for me either

**Comment by eVen-gits** [comment]
Just connected my steam controller. Manjaro KDE Plasma, unstable channel, wayland. The issue is still alive.

**Comment by KingKrouch** [comment]
Can confirm that this is still an issue in KDE Wayland at least.

**Comment by FormBurden** [comment]
Still an issue today.

**Comment by Patola** [comment]
I am also interested in getting this fixed. After years of resisting I finally switched to wayland with KDE 6. I've also been using sc-controller (I have almost 300 configurations for it) but Steam Input improved a lot and I was starting to use it. Does that happen because of privilege separation in Wayland? Any good way to fix that?

**Comment by Myned** [comment]
For those still subscribed to this: 

The current workaround is with [extest](https://github.com/Supreeeme/extest), as mentioned in a linked issue, likely until Steam supports Wayland directly.

There are some problems such as the cursor being visible over the keyboard while in desktop mode, but at least it's visible at all. :)

For NixOS users:

```
programs.steam.extest.enable = true
```

**Comment by trmz** [comment]
What does it take to get this reopened?  

Still an issue (KDE Plasma, Wayland, latest Steam).   

Hard to believe this will ever get fixed proper if left Closed as it is.

**Comment by Patola** [comment]
> What does it take to get this reopened?
> 
> Still an issue (KDE Plasma, Wayland, latest Steam).
> 
> Hard to believe this will ever get fixed proper if left Closed as it is.

But it's working now. In KDE Wayland, on Archlinux.

**Comment by trmz** [comment]
> > What does it take to get this reopened?
> > Still an issue (KDE Plasma, Wayland, latest Steam).
> > Hard to believe this will ever get fixed proper if left Closed as it is.
> 
> But it's working now. In KDE Wayland, on Archlinux.

That's nice for you, but implies nothing about it being fixed for all, evidently.

**Comment by Patola** [comment]
> 
> That's nice for you, but implies nothing about it being fixed for all, evidently.

You can't blame it on the developers. There is an enormous variety of linux distros and customizations and that makes it impossible to deploy an universal fix -- some installations may prevent Steam from updating or do some other types of blockage, like overriding the udev rules for steam-devices.

They did what they needed to do -- they changed the code that comes with steam for the steam controller and this new code handles mouse emulation properly on Wayland. Distros that allowed for a regular update had the issue fixed, if I were you I would check your changes/customization to the system so as to see what could be blocking the fix from working.

**Comment by trmz** [comment]
> Replying to https://github.com/ValveSoftware/steam-for-linux/issues/6615#issuecomment-3727445754

You came in simping for a billion dollar company with, "Works on my PC, (I use Arch btw)". 

Anyone could do the same for any of 1,000 open issues here, but we don't because we recognize it as vacuous noise.  

You already indicated above that you're "using sc-controller" - it is more likely then that what works for you is not a *stock*, Steam-only configuration.

**Comment by Patola** [comment]
> You already indicated above that you're "using sc-controller" - it is more likely then that what works for you is not a _stock_, Steam-only configuration.

I use both. Calling sc-controller makes it override steam, quitting it takes back the control to Steam. And everything works.
Steam Input has things sc-controller cannot achieve like action sets and some fine-tuning for the trackpads. sc-controller has an easier menu and configuration and also allows you to reprogram the chord button in a much easier way.

I don't understand the aggressive attitude against my comment. I am just saying that the developers of steam-for-linux have done their part on the code. Or maybe not, it's still on their side but you have presented no evidences for that. I suspect that the reason it's not working with you is because of your particular setup, be it your distro or your own customization.

**Comment by Nowa-Ammerlaan** [comment]
It's working provided your distro compiles your DE with support for libei, if that is not the case then that is a problem you need to complain about on your distro's bug tracker.

**Comment by yea55** [comment]
Wanted to chime in and add that this is effecting the 2026 steam controllers as well
