### ISSUE TITLE
Remote play right corner message without doing anything

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/steam-for-linux#6616]
#### Your system information

* Steam client version (build number or date): 2/10/19
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

Got more than one remote play right corner message without doing anything and without ever used it.

#### Steps for reproducing this issue:

1. None

**Comment by kisak-valve** [comment]
Hello @andreldmonteiro, are you still experiencing this issue on an up to date system?

**Comment by andreldmonteiro** [comment]
Hi, I'm not.

**Comment by kisak-valve** [comment]
Thanks for re-checking, closing.
