### ISSUE TITLE
Steam network error -118 Server unavailable

### ISSUE THREAD

**Issue by fedor-elizarov** [ValveSoftware/steam-for-linux#6619]
#### Your system information

* Steam client version : `Build date 25 2019 22:25:17 steam api v020 - version - 1572045180` 
* Distribution : `Linux gnu 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
`
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

![img](https://i.imgur.com/5QGuqv5.png)

```sh
Running Steam on debian  64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-10-28 22:48:57] Startup - updater built Oct 25 2019 22:25:01
[2019-10-28 22:48:57] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-10-28 22:48:57] Checking for update on startup
[2019-10-28 22:48:57] Проверка на наличие обновлений...
[2019-10-28 22:48:57] Downloading manifest: client-download.steampowered.com/client/steam_client_publicbeta_ubuntu12
[2019-10-28 22:48:57] Download skipped by HTTP 304 Not Modified
[2019-10-28 22:48:57] Nothing to do
[2019-10-28 22:48:57] Проверка установки...
[2019-10-28 22:48:57] Performing checksum verification of executable files
[2019-10-28 22:48:58] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/pgriffais/src/Vulkan/base/vulkanexamplebase.cpp at line 823
```

#### Steps for reproducing this issue:

1.  Start steam
2.  Wait
3.  Network fail

--------------------
P.S. I would also like to point out that this is not strange, but `Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/pgriffais/src/Vulkan` @pgriffais delete your home path from steam :D

**Comment by fedor-elizarov** [comment]
Now Game servers have become available, the store is also available, but the chat servers are unavailable (from the left in the screenshot) Now. for example i can play cs:go in online. 

But probably the problem still exists for some. If until tomorrow everything will work (and I will not forget :smile:  ) I will close this issue.

**Comment by Vladimir-A** [comment]
Yes, I have same trouble.
```shell
ExecuteSteamURL: "steam://friends/status/online"
[1028/232420.009186:ERROR:frame_sink_video_capturer_impl.cc(197)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
```

**Comment by fedor-elizarov** [comment]
Now all services working, I close issue.

**Comment by RokeJulianLockhart** [comment]
Today, I observed very similar, with:

<blockquote>

~~~YAML
Steam Beta Branch:  Steam Beta Update
Steam Version:  1767142807
Steam Client Build Date:  Wed, Dec 31 00:45 UTC -08:00
Steam Web Build Date:  Mon, Dec 29 23:51 UTC -08:00
Steam API Version:  SteamClient023
~~~

</blockquote>

…upon resumption from S4 (like [`issues/12378#event-4275495687`](https://github.com/ValveSoftware/steam-for-linux/issues/12378#event-4275495687)):

<p></p><img width="383" height="215" alt="Image" src="https://github.com/user-attachments/assets/810a90a0-5a84-4a09-9d1f-76d388ddca0f" /><p></p>

<details><p></p>

Ignore the strange UI; I happened to be evaluating [`Adwaita-for-Steam/issues/346`](https://github.com/tkashkin/Adwaita-for-Steam/issues/346#issue-3778133252), for [`issues/11627`](https://github.com/ValveSoftware/steam-for-linux/issues/11627#issue-2767591994):

<p></p><img width="500" height="328" alt="Image" src="https://github.com/user-attachments/assets/cb192597-0565-4f47-9075-89374488eabf" /><p></p>

[^1]

[^1]: [`tkashkin/Adwaita-for-Steam/discussions/347`](https://github.com/tkashkin/Adwaita-for-Steam/discussions/347#discussion-9304295)

</details><p></p>
