### ISSUE TITLE
Choosing an image as an avatar and editing community profile

### ISSUE THREAD

**Issue by kiddykoff** [ValveSoftware/steam-for-linux#662]
![Screenshot from 2013-01-11 15:33:19](https://f.cloud.github.com/assets/3113963/61441/c29b192e-5c47-11e2-819a-78807f597f98.png)
There isn't an obvious button for uploading an image for the steam avatar. Furthermore, when uploading the avatar the file browser starts at root and displays hidden folders. A better place to start would be in the home folder.

EDIT: clicking the upload button uploads nothing, you have to click the blank bar to the left of it.

**Comment by kisak-valve** [comment]
Closing as this appears to have been fixed.
