### ISSUE TITLE
Steam Cliente for Ubuntu

### ISSUE THREAD

**Issue by JuanPedraza** [ValveSoftware/steam-for-linux#6620]
#### Your system information

* Steam client version (build number or date): 1.0.0.61 La más reciente que aparece en la página para Ubuntu
* Distribution (e.g. Ubuntu):  Ubuntu 19.10
* Opted into Steam client beta?: NO
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

El cliente de Steam para Ubuntu 19.10 no carga. Se intenta abrir y simplemente no muestra nada y tampoco ejecuta el programa

**Comment by kisak-valve** [comment]
Hello @JuanPedraza, can you check if any 32 bit opengl application works like `glxinfo` from `mesa-utils:i386`?

**Comment by kisak-valve** [comment]
Closing due to a lack of feedback.
