### ISSUE TITLE
Cannot launch steam in linux mint

### ISSUE THREAD

**Issue by TitaneerYeager** [ValveSoftware/steam-for-linux#6621]
#### Your system information

* Steam client version (build number or date): The latest official download from the steampowered site.
* Distribution (e.g. Ubuntu): Linux mint 18.3 Sylvia
* Opted into Steam client beta?: [Yes/No] No I think...
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
So if I install steam from either the linux mint repositories or from the official .deb installer from steampowered download page, it installs. I then go to launch steam and it gives this error:
"Couldn't set up Steam data - Please contact technical support"

#### Steps for reproducing this issue:

1. Install the latest Linux .deb installer for steam
2. Try to launch steam
3. Get an error

**Comment by kisak-valve** [comment]
Hello @TitaneerYeager, the distro-provided Steam package and the Valve-provided Steam package have different, incompatible folder layouts. Please move/remove `~/.steam` and `~/.local/share/Steam` when switching between them.

After that, please check if any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works.

**Comment by Newbie13XD** [comment]
I'd suggest you do `sudo apt install steam` (or install it via the Mint GUI Store) instead of using the .deb package.

**Comment by TitaneerYeager** [comment]
After deleting all steam files and reinstalling the official .deb installer it worked. Thank you!
