### ISSUE TITLE
Cortex Command + Remote Play Together freezes Steam on Fedora 30

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6622]
#### Your system information

* Steam client version (build number or date): Oct 29 2019, at 00:09:44
* Distribution (e.g. Ubuntu): Fedora 30 Workstation
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Playing Cortex Command via Remote Play Together through Proton 4.11-7 freezes Steam, and it to forcefully killed. No window responds (friends, main window, etc.)

#### Steps for reproducing this issue:

1. Download Cortex Command and play it via Proton (native Linux depot is empty)
2. Invite someone to play together with
3. Exit the game
4. Steam should now be frozen

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
