### ISSUE TITLE
steam beta won't allow me to login to Elite Dangerous

### ISSUE THREAD

**Issue by DickThomas** [ValveSoftware/steam-for-linux#6624]
#### Your system information
system info https://gist.github.com/DickThomas/42019539b39614e4ccc5d95a04b9e8ab

* Steam client version (build number or date): build version 1572416120 
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
sign up to Steam Client Beta.
when I sign in I expect my name to show on the top right of the Elite Dangerous launcher.
I get a sign-in window that fails with both Steam and Elite Dangerous user names and passwords.

Exit Steam Client Beta and try again and it works.
#### Steps for reproducing this issue:

1.  Opt in to Steam Beta
2.  Enable Proton for Elite Dangerous and then follow the guide at https://github.com/redmcg/wine/wiki for installing missing dependencies 
3.  Elite Dangerous expects me to sign-in 

sorry I'm not sure what else to add.

**Comment by kisak-valve** [comment]
Hello @DickThomas, we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/). Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/150#issuecomment-547878623.
