### ISSUE TITLE
Steam Play Together not filtering out other sound sources

### ISSUE THREAD

**Issue by ThaChillera** [ValveSoftware/steam-for-linux#6625]
#### Your system information

* Steam client version (build number or date): 30-10-19
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When hosting a steam play together sessions, friends can hear sounds from all sound sources like discord, steam voice chat, youtube videos etc.

When connecting to a friend who's hosting on windows, this isn't an issue and I only hear the game

This issue isn't arch-specific since [This](https://github.com/ValveSoftware/steam-for-linux/issues/6606#issuecomment-547699465) user on Solus experiences the same issue

#### Steps for reproducing this issue:

1. Connect to someone who's hosting on linux, hear everything

#### Possible solutions
[This](https://github.com/ValveSoftware/steam-for-linux/issues/6606#issuecomment-547823765) user mentioned that setting up pulseaudio sinks could be a solution, but I assume this is more a hack, and steam should filter out other sounds natively?

**Comment by kisak-valve** [comment]
Hello @ThaChillera, per https://github.com/ValveSoftware/steam-for-linux/issues/6670#issuecomment-553022562, please retest this issue.

**Comment by ThaChillera** [comment]
@kisak-valve It works! 

its not ideal, since you guys seem to add a new input device when the game window is selected, which makes discord give a popup to ask whether it should select the different input, which makes me unable to read my messages. but that's way outside the scope of this issue ¯\_(ツ)_/¯

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.

**Comment by jeffkeller87** [comment]
Is there something the host or client needs to do to leverage this fix? I'm using the latest steam beta build (Dec 6 2019, at 03:34:35) on Linux Mint 19.2 and still have this issue when hosting.

**Comment by GaiaB0t** [comment]
finding this to be an issue again, beta or not
