### ISSUE TITLE
Steam breaks window composition and font rendering on startup. Turning on any 3D game via steam play dissolves the issue until next startup 

### ISSUE THREAD

**Issue by Yarwin** [ValveSoftware/steam-for-linux#6629]
#### Your system information
Operating System Version:
    Ubuntu 18.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20191007.0
* Steam client version (build number or date):  steam-runtime_0.20191007.0
* Distribution (e.g. Ubuntu):  Ubuntu 18.04.3 LTS (64 bit)
    * Video Card Driver:  X.Org AMD Radeon RX 5700 XT (NAVI10, DRM 3.33.0, 5.0.0-32-generic, LLVM 9.0.0)
    * Video Card Driver Version:  4.5 (Compatibility Profile) Mesa 19.2.0-devel
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam breaks the window composition on startup. Turning on any game via proton dissolves the issue until the next startup. Games works fine through steam play – no other issues experienced outside of it.

![image](https://user-images.githubusercontent.com/5611207/67928494-7280a380-fbbb-11e9-84fc-8c4af6d8c972.png)

![image](https://user-images.githubusercontent.com/5611207/67928708-ff2b6180-fbbb-11e9-8a96-0ca8c01a6c0b.png)
(telegram desktop included to show that the issue is affecting other programs and composition as well – ignore the image, it is just a meme)

#### What I've tried so far:
1) Turning off the steam play (it made everything worse since I couldn't use the workaround to fix it)
2) Disabling GPU accelerated rendering 
3) purging & reinstalling steam 
4) Restarting/tweaking kwin

#### Steps for reproducing this issue:

1. Turn of steam

**Comment by kisak-valve** [comment]
Hello @Yarwin, this reads like a video driver issue. It may be worthwhile to report it to your video driver vendor.

**Comment by Yarwin** [comment]
For future reference – upgrading kernel version to 5.3 and mesa to 20.0 resolved the issue.
https://ubuntuforums.org/showthread.php?t=2425799
