### ISSUE TITLE
Steam shows nothing after recent update

### ISSUE THREAD

**Issue by arabek** [ValveSoftware/steam-for-linux#6631]
#### Your system information

* Steam client version (build number or date): Oct 30 2019, see screenshot
* Distribution (e.g. Ubuntu): Gentoo x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam shows blank instead of displaying anything in any of the content windows.
Nothing works. Not the storefront, not the library.

In big picture mode everything seems to be working besides the inbuilt web browser.

Seems to be some kind of cef framwork problem?

#### Steps for reproducing this issue:

1. Start steam in normal mode

![Screenshot_20191031_105332](https://user-images.githubusercontent.com/2504890/67936991-0a3abd80-fbcd-11e9-9169-562baac22de4.png)

**Comment by byte1024** [comment]
I have that happen at the moment on only using the back button where the last use of it or 1st record is that blank screen there. At the same time though I can go forward into the library screen.

**Comment by arabek** [comment]
Nope, sorry - but this is not the same issue you are having. It displays nothing. The one screen that is working is the downloads screen. Apart from that, every other page in the interface displays a blank black screen of nothingness.

**Comment by anohren** [comment]
I have the same problem. Don't know if it's related to all these processes being created every 7-10 seconds https://github.com/ValveSoftware/steam-for-linux/issues/6603

**Comment by kisak-valve** [comment]
Hello @arabek, please copy `/tmp/dumps/<username>_stdout.txt` to a [gist](https://gist.github.com) and include a link to it here or drag and drop it to the comment box to attach it as a file.

**Comment by arabek** [comment]
```
Loaded Config for Local Selection Path for App ID 413080, Controller 0: /home/arab/.local/share/Steam/steamapps/workshop/content/241100/922641257/818937737353570967_legacy.bin
[413080]Non-Steam Controller Configs Enabled: 1
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: ./libcef.so: undefined symbol: FcConfigGetSysRoot
(repeats indefinitely)
```

Think this makes it clear.

```
[I] media-libs/fontconfig
installed version: 2.13.0-r4
```

**Comment by arabek** [comment]
[arab_stdout.txt.gz](https://github.com/ValveSoftware/steam-for-linux/files/3795315/arab_stdout.txt.gz)

**Comment by kisak-valve** [comment]
Just a guess, can you move `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_*` somewhere out of the way so that Steam can regenerate it on next start and check if that has an effect?

**Comment by arabek** [comment]
Actually, after some more tests, it works if i run steam with:

```LD_PRELOAD=/home/arab/.local/share/Steam/ubuntu12_64/libcef.so:/usr/lib64/libfontconfig.so:/usr/lib64/libdbus-1.so.3 /usr/bin/steam
```

So seems, the steam startup script fails to select proper libraries upon load.

**Comment by arabek** [comment]
Moving pinned libs out of the way didn't fix things.

**Comment by kisak-valve** [comment]
Can you check if you have `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` set somewhere? There's a [comment](https://github.com/ValveSoftware/steam-for-linux/issues/6499#issuecomment-533616972) that `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 steam` makes a difference.

**Comment by smcv** [comment]
The default if `STEAM_RUNTIME_PREFER_HOST_LIBRARIES` is unset is the equivalent of setting it to 1.

Explicitly setting `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` is an escape hatch to undo a behaviour change that was made a while ago, and is not really considered to be a good idea: it's known to break graphics drivers on many (most?) host OSs. The graphics driver always comes from the host system, not the Steam Runtime, and it's entitled to assume that it will get at least the host system's version of the libraries that it depends on.

> Seems strange that a pseudo sandboxed steam install can't work on it's own

This is specific to the `steamwebhelper`, which has its own mini-runtime (`heavy`) that is somewhat newer than the main Steam Runtime (`scout`). `heavy` isn't currently fully self-contained (modulo graphics drivers) like `scout` is; it expects to use libraries from a mixture of `scout` and the host system.

**Comment by arabek** [comment]
Thanks for the explanation! Appreciated.

**Comment by dsmid** [comment]
> Explicitly setting `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` is an escape hatch to undo a behaviour change that was made a while ago, and is not really considered to be a good idea: it's known to break graphics drivers on many (most?) host OSs. 

On my system it's the other way round: the games won't run without STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 thus unsetting it is not a good workaround for me.
However I can confirm the launching steam with 
`LD_PRELOAD=~/.local/share/Steam/ubuntu12_64/libcef.so:/usr/lib64/libfontconfig.so:/usr/lib64/libdbus-1.so STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` as arabek advised works!

**Comment by smcv** [comment]
> On my system it's the other way round: the games won't run without STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 thus unsetting it is not a good workaround for me.

This shouldn't happen. Please could you open a separate issue with full details?

**Comment by dsmid** [comment]
> Please could you open a separate issue with full details?

The issue has been already opened:
https://github.com/ValveSoftware/steam-for-linux/issues/4822

**Comment by Ishidres** [comment]
I have the same issue as mentioned above, but none of the possible fixes like changing the start script could fix the issue. Why is this issue even marked as "Closed" already?

Before it still worked to run games through the terminal using `steam steam://run/[app_id]`, but now this doesn't work anymore, too. :confused: 

Any idea?
