### ISSUE TITLE
Pasting the steam browser URL does so with a delay

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6632]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/67938490-4293c900-fbd8-11e9-95f6-09be99e62434.png)
* Distribution: Xubuntu 19.10 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When pasting the URL from the steam browser, it does so with a delay. It also stops you from pasting it after you shut down Steam so I'm assuming the problem has to do with the clipboard entry being a pointer.
Demonstration video: https://youtu.be/FASG6KhhJXE

#### Steps for reproducing this issue:

1. Copy the URL from steam browser
2. Paste it to somewhere else

**Comment by kisak-valve** [comment]
Hello @Managor, are you still experiencing this issue on an up to date system?

**Comment by Managor** [comment]
The delay still happens but there is an improvement. When you shut down Steam, the system doesn't forget what was in the clipboard.

**Comment by Managor** [comment]
This has been fixed.
