### ISSUE TITLE
Steam GUI still visible in game

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6636]
* Steam client version (build number or date): Oct 30 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

I'm not sure what exactly triggers this to happen, but the STEAM GUI will have a section oh it stuck on the screen. Its just about identical to the bug I posted a while ago.

https://github.com/ValveSoftware/steam-for-linux/issues/4496

Maybe mousing over the search bar causes it, or opening up the menus at the top. I also should mention I'm using GPU accelerated web views. Sometimes reopening the menu will fix it from being stuck on screen.

#### Steps for reproducing this issue:

1. Open up the Steam menus and mouse over the search bar?
2. Steam GUI glitches out and stays on the screen
3. Launch game and part of it is still there

![E8E8A8C0-4E47-44DA-92E5-5C3DD2C2CBBB](https://user-images.githubusercontent.com/5150898/68007695-b96da800-fc52-11e9-941d-33367974da61.jpeg)
![766C3DD3-D757-4C6C-8242-5D121C50C8A9](https://user-images.githubusercontent.com/5150898/68007697-b96da800-fc52-11e9-89cf-e4b2f71c71e3.jpeg)

**Comment by kisak-valve** [comment]
Hello @shoober420, next time you encounter this, can you run `xwininfo`, click on the uninitialized window, and copy/paste the output as a reference to ponder.

**Comment by shoober420** [comment]
Will do sir, when I get home from work.

**Comment by shoober420** [comment]
Here goes my system information. I forgot to post it.

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

So I just downloaded the new Nov 1 2019 Steam build. I was trying to invoke the bug earlier to no success. I noticed it did have some GUI updates, so I'll try and trigger it and post the results.

**Comment by shoober420** [comment]
I was testing this recently with the new beta updates, and it doesn't seem to happen anymore. I've been using the new "Small Mode" anyway, both are very sleek.

**Comment by shoober420** [comment]
This actually just happened again...
![B14E536B-9C12-4BE9-BABF-DABA5C617790](https://user-images.githubusercontent.com/5150898/68657117-12fe8e00-0501-11ea-914c-43433927a280.jpeg)
![58E8C85F-D6E4-43CE-B2FC-1E748DA5EA2C](https://user-images.githubusercontent.com/5150898/68657118-12fe8e00-0501-11ea-890f-3eee432897fe.jpeg)

**Comment by shoober420** [comment]
Finally found some time to do this. I've been all over the place, doing things. So I got the xwininfo here, and some more pics.

[windowbugsteam.txt](https://github.com/ValveSoftware/steam-for-linux/files/4007733/windowbugsteam.txt)

**Comment by shoober420** [comment]
I just was able to get the xwininfo for Steam itself when this bug is happening.

[steamrectanglebug.txt](https://github.com/ValveSoftware/steam-for-linux/files/4023405/steamrectanglebug.txt)

**Comment by shoober420** [comment]
I havent seen this happen for quite some time. Closing for now.
