### ISSUE TITLE
Tooltips freeze Steam client and cause massive CPU usage

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-for-linux#6638]
#### Your system information

* Steam client version: 30th October 2019
* Distribution: Ubuntu 18.04.3 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Nvidia 970 with 430.50 driver
* i5 760 CPU @ 3.5GHz

#### Please describe your issue in as much detail as possible:

The CPU usage skyrockets to the point that the whole client freezes for a few seconds and my CPU fan speeds up. It's not just that page (see below), it happens wherever those tooltips show up. Like also with those links to the right of every community discussion  thread. This started happening with the new library. GPU acceleration on/off doesn't really make a difference. Doesn't happen with my desktop browser, only through the Steam client.

I posted it on the Steam Beta Forum, but either I'm the only one or nobody's reading those.

#### Steps for reproducing this issue:

1. Open page https://store.steampowered.com/news/?headlines=1 (click News -> select "headlines" on the top right)
2.  hover your mouse pointer over the headlines

**Comment by LiamDawe** [comment]
Just checked, can confirm this is also an issue here. 

CPU use jumped from 2% up to around 8-10% just by hovering over the headlines for the tooltip to come up.

**Comment by kisak-valve** [comment]
Hello @DanMan, @LiamDawe, are either of you still experiencing this issue on an up to date system?

**Comment by LiamDawe** [comment]
Nope, all good.

**Comment by DanMan** [comment]
I still get this on the forums for example. If I click on a forum thread, on the right side there's the "more discussions" area. If I hover over those, the tooltip still makes the client freeze for a few seconds.

**Comment by kisak-valve** [comment]
Thanks for rechecking, you've described the issue being tracked at #3994. I'd prefer that we use the older issue report to focus on that specific symptom. Are you seeing similar symptoms elsewhere?

**Comment by DanMan** [comment]
Wherever those tooltip are used, basically. Since the news section has been completely overhauled, that one's off the table. But I guess you're right that it's the same issue.
