### ISSUE TITLE
"Steam Play" Information in New Library UI

### ISSUE THREAD

**Issue by inguin** [ValveSoftware/steam-for-linux#6639]
#### Your system information

* Steam client version (build number or date): Oct 30 2019, 20:05:34
* Distribution (e.g. Ubuntu): Fedora 30
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I kinda like the new Steam Library look & feel, but I'm painfully missing the "Runs on this computer using Steam Play x.y.z" info next to the Play button. Can we please get it back? Thanks!

**Comment by kisak-valve** [comment]
Hello @inguin, this issue is already being tracked at #6494. Closing as a duplicate.
