### ISSUE TITLE
Steam creates ~/Downloads folder, ignoring xdg-user-dirs configuration

### ISSUE THREAD

**Issue by simvux** [ValveSoftware/steam-for-linux#6642]
#### Your system information

System Info / steamruntime Info: https://pastebin.com/ccY2gTdu
* Opted into Steam client beta?: Yes, but issue persists without it
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Every time I launch steam it creates the empty directory ~/Downloads. This is quite annoying considering that I have modified my `xdg-user-dirs` configuration for my actual download folder to be `~/D` through [this ~/.config/user-dirs.dirs configuration file](https://pastebin.com/vj2tawwj). 

So first of all; Why is the directory even created in the first place? Steam doesn't seem to actually ever use it. And secondly, if it needs to be created it should definitely be following the system's XDG configuration to decide where to place the folder. 

I believe this started to happen ever since I switched to the new steam library, maybe this is some weird behaviour caused by Panorama-UI? That could've also just been a coincidence and this has been caused by some other recent update of course. Point being; this didn't used to happen before. 

#### Steps for reproducing this issue:

1. Make sure you're using a non-standard xdg-user-dirs configuration for your XDG_DOWNLOAD_DIR
2. Make sure ~/Downloads doesn't exist
3. Launch Steam
4. The ~/Downloads folder is now created

**Comment by jazztickets** [comment]
Started getting this on the new Steam update as well.

**Comment by YoyPa** [comment]
same while:
```
XDG_DOWNLOAD_DIR="$HOME/Téléchargements"
```

**Comment by NoXPhasma** [comment]
Same for me, I wish Steam won't do that!

**Comment by z0z0z** [comment]
Same.

~/.config/user-dirs.dirs

`XDG_DOWNLOAD_DIR="$HOME"`

**Comment by kisak-valve** [comment]
Hello, per "Removed auto-creation of Documents/Downloads directory." in the [2019-11-07](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1600394952171527192) Steam client beta update, please opt into Steam's beta client if you haven't already and retest this issue.

**Comment by z0z0z** [comment]
Fixed for me.

**Comment by NoXPhasma** [comment]
Fixed for me as well on latest beta.

**Comment by jazztickets** [comment]
Fixed here too.

**Comment by simvux** [comment]
I haven't had this issue for a long time and it seems safe to assume that it's fixed
