### ISSUE TITLE
32-bit linux library is now inaccessible

### ISSUE THREAD

**Issue by tautaula** [ValveSoftware/steam-for-linux#6643]
#### Your system information

* Steam client version (build number or date): latest 32-bit Steam client
* Distribution (e.g. Ubuntu): 32-bit Ubuntu
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam updated. I was surprised, since 32-bit linux is deprecated, no longer supported. I don't know why there was an update for it at all. I expected... no real change. Maybe some bugfixes so that games not meant to play in 32-bit linux would be properly gone. I was /not/ expecting my entire steam library to be inaccessible! I have a good few games that run fine on 32-bit linux, and they worked just fine until this... update? I am not a coder, did not have an account here til I was directed to post to this by (one of?) Steam's support personnel when I tried to describe the issue to them in steam's in-site support system.

I want my games back, please, Steam!

#### Steps for reproducing this issue:

1. have 32-bit steam client (yes, I know it's deprecated. Which makes me wonder why it was updated at all)
2. have steam
3. try to look at steam library

I am not a coder (I know I said this already) and don't really use the CLI much. I can provide screenshots of my inaccessible steam library, and an error message I got by trying to access one of my games (also working perfectly well - before this update) through taskbar dropdown. The game "could not find steam," despite that it was up and running.

The game in question is Wurm Unlimited, in case that helps.

**Comment by kisak-valve** [comment]
Hello @tautaula, Steam's new UI interface is built upon the embedded chromium framework, which is only available for 64 bit.

For the time being you may have luck with running `steam steam://open/minigameslist`, but that may go away or be re-implemented with the new UI at some point in the future.

**Comment by tautaula** [comment]
It loads!

Thank you!!

Maybe, as you said, it will stop working - but for now, it works! Yay!

Also, thank you! (I am very grateful.)

**Comment by VADemon** [comment]
Same story here. Use case: in-home/VPN streaming, 32-bit CPU.
**Another workaround:** "Small mode" was pushed out in a recent Beta branch update.

1. Switch to Beta branch (Settings -> Account), restart
2. In the main Steam window open the "View" context menu -> "Small mode"

This is exactly what you need, just the games list without the rest of the window. The only downside: friends list is 2 clicks away now and no direct access to Steam's console tab.

PS: For me with Beta branch, `open steam://open/minigameslist` in Steam's console does switch view to the disabled library, not working.

PPS: Console is spammed with CEF assertions every second despite `-no-browser` flag.
```
../common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
chrome_ipc_client.cpp (218) : Assertion Failed: Is64BitOS()
```

**Comment by tautaula** [comment]
Because the CLI workaround works for me, and VADemon's solution will block it, I'm unwilling to try your solution, VADemon. If/when the CLI workarond by kisak-valve fails, I will probably try your suggestion.

There was another update to steam. My library is still not back; I was hoping it would be.

Thank you both, and thank everyone else who is working on a solution, too!

**Comment by tautaula** [comment]
`../common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
../common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
chrome_ipc_client.cpp (218) : Assertion Failed: Is64BitOS()
chrome_ipc_client.cpp (218) : Assertion Failed: Is64BitOS()
chrome_ipc_client.cpp (218) : Assertion Failed: Is64BitOS()
chrome_ipc_client.cpp (218) : Assertion Failed: Is64BitOS()`

This keeps spamming my terminal I'm running kisak-valve's solution in. At least once per second.

**Comment by tautaula** [comment]
...When I tried to uninstall a game, the view altered to inaccessible library. I was unable to uninstall the game I guess was never meant to be installed?

**Comment by VADemon** [comment]
Last week I noticed Steam was updated to require x86-64 support :( As such the issue can be closed.

This is bad news to me, sorry to derail but if so, then there's **no way to run In-Home Streaming** ("Remote Play") client **anymore on 32-bit Linux?** It was the only thing that allowed me to continue using _this laptop_ as a thin-client (and it worked greatly, ty!) - otherwise it's ready for waste... that's a shame.

**Comment by truboxl** [comment]
even `steamcmd` got hit with this problem which is a pure terminal program and have to apply `-no-browser` to stop the message

`/data/src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()`

**Comment by kisak-valve** [comment]
Going forward, 32 bit exclusive systems can't really be supported properly.
