### ISSUE TITLE
Valve Hardware Survey crashes

### ISSUE THREAD

**Issue by yigi** [ValveSoftware/steam-for-linux#6645]
#### Your system information

* Steam client version (latest): 
* Distribution (Windows): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Open Steam
2.  Hardware Survey box appears (Yes I would like to participate to survey)
3.  Nothing happens and crashes

**Comment by kisak-valve** [comment]
Hello @yigi, please use [Steam Support](https://help.steampowered.com/) for issues with the Steam for Windows client, so it can reach the larger support team. Additionally, the linux variant of this issue is being tracked at #5367.

Closing as out-of-scope for this issue tracker.
