### ISSUE TITLE
Shifted screen at a 3840x2160 resolution with 150% Scale

### ISSUE THREAD

**Issue by steamLinuxUser898** [ValveSoftware/steam-for-linux#6647]
#### Your system information

* Steam client version (build number or date):  1570046 (OCT/2/19 - 18:45:57)
* Distribution (e.g. Ubuntu): Ubuntu 1910 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The Full-screen picture for Civ5 is shifted after the game start.

I run a 3840x2160 resolution on my screen with 150% scale. When I start Civilization 5 in full-screen mode with 3840x2160 the start-screen is shifted to the right bottom corner. When the first message, with the age verification appears, the window don't respond to a click. The mouse cursor is visible but the click has no effect.

#### Steps for reproducing this issue:

1. Use a 3840x2160 resolution with a 150% scale (configure in the Ubuntu display settings)
2. start Civilization 5
3. The result is visible

**Comment by kisak-valve** [comment]
Hello @steamLinuxUser898, this issue should also be mentioned to the game's devs if it hasn't been already.

**Comment by kisak-valve** [comment]
Closing because this doesn't appear to be a Steam client issue.
