### ISSUE TITLE
PS4 DS4 controller not recognized via Bluetooth on Ubuntu 19.10 (Eoan Ermine)

### ISSUE THREAD

**Issue by Jimbolino** [ValveSoftware/steam-for-linux#6648]
#### Your system information
* Steam client version: Nov 2 2019
* Distribution: Ubuntu 19.10 (Eoan Ermine)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The PS4 controller only works when its connected via USB. When I connect it via Bluetooth its not recognized by steam client or games. With the previous Ubuntu 19.04 it was working fine.

#### Steps for reproducing this issue:
1. Fresh install of Ubuntu 19.10
2. Pair PS4 controller with PC
3. Open steam

**Comment by kisak-valve** [comment]
Hello @Jimbolino, https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849993 indicates this is a kernel regression and unrelated to Steam.

**Comment by yaliv** [comment]
Similar problem here when using Bluetooth. Should I open a new issue?

**Your system information**

- Steam client version: Jul 31 2020
- Distribution: Pop!_OS 20.04 LTS (64 bit)
- Kernel version: 5.4.0-7634-generic
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes

**Please describe your issue in as much detail as possible:**

The PS4 controller (DS4) only works when it's connected via USB. But when connected via Bluetooth it's not recognized by Steam client (Big Picture mode) or games.

**Steps for reproducing this issue:**

1. Use Pop!_OS 20.04, make sure it is up to date.
2. Connect DS4 to PC via USB until the light bar turn yellow and fade-out-fade-in slowly (it is charging the battery) or turn off (the battery is full).
3. Open Steam Big Picture, the DS4 will be detected in Controller Settings and be usable here and in games, e.g. Portal 2.
4. Close Steam.
5. Unplug the USB.
6. Connect DS4 to PC via Bluetooth until the light bar turn white and static.
7. Open Steam Big Picture, the DS4 will not be detected in Controller Settings and not be usable anywhere.
