### ISSUE TITLE
[Library Beta] The event library overlay(?) appears as a broken box

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6652]
#### Your system information

* Steam client version (build number or date): 
![Screenshot_2019-11-06_00-31-25](https://user-images.githubusercontent.com/6024315/68274097-cbbe5c00-002d-11ea-9560-3b435c1572e6.png)
* Distribution (e.g. Ubuntu): Xubuntu 19.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
https://gist.github.com/nightsky30/d6e5e435c7825f7c5d1570e51930cfba

#### Please describe your issue in as much detail as possible:
The CSGO event library overlay(?) that should open appears as a broken box when the user clicks on the CSGO event in the library.

**EDIT:**  Also, "Rahul's Death Day" event that displayed the issue seems to have disappeared, and I cannot get it to return.  Can't find anything on it either...Is someone at Valve creating fake events?

![Screenshot_2019-11-06_00-39-20](https://user-images.githubusercontent.com/6024315/68274134-e395e000-002d-11ea-95a4-b057633fc9ab.png)
![Screenshot_2019-11-06_00-29-41](https://user-images.githubusercontent.com/6024315/68274138-e690d080-002d-11ea-8b5d-e9081714a038.png)

#### Steps for reproducing this issue:

1. Open the Steam Library
2. Click on the CSGO event
3. The event library overlay(?) that should open appears as a broken box

**Comment by kisak-valve** [comment]
Hello @nightsky30, this appears to be resolved and possibly a server side issue.

If you happen across this scenario again and it's consistently reproducible, open a new issue report or let me know and I can re-open.
