### ISSUE TITLE
System Information Box is Populated With Duplicated Raw JSON and Error at the Bottom

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6653]
#### Your system information

* Steam client version (build number or date): 
![Screenshot_2019-11-06_00-31-25](https://user-images.githubusercontent.com/6024315/68274571-24422900-002f-11ea-9c47-3f764c3ccd0c.png)
* Distribution (e.g. Ubuntu): Xubuntu 19.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
https://gist.github.com/nightsky30/d6e5e435c7825f7c5d1570e51930cfba

#### Please describe your issue in as much detail as possible:
System Information dialog box is populated with duplicated raw JSON and error message at the bottom of its contents.  It gets copied out as well with everything else.

Error below JSON:  "The Steam Linux Runtime container tool is not Installed."

![Screenshot_2019-11-06_00-42-50](https://user-images.githubusercontent.com/6024315/68274632-4340bb00-002f-11ea-9ac7-cf9399c8b0ac.png)

#### Steps for reproducing this issue:

1. Open the Steam System Information dialog box.
2. Scroll towards the bottom.
3. See raw JSON of system information and error message after the normal values listed above.

**Comment by nightsky30** [comment]
Also happening with latest build:
![Screenshot_2019-11-06_01-03-15](https://user-images.githubusercontent.com/6024315/68275520-8865ec80-0031-11ea-9f15-1c5564922a65.png)

**Comment by kisak-valve** [comment]
Hello @nightsky30, this may change in the future, but for now this is an intentional addition to Steam's System information to help identify driver issues and runtime variations between Linux distros.
