### ISSUE TITLE
uninstall popup does not appear in downloads section until you go back to library

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6655]
#### Your system information

* Steam client version (build number or date): Nov 6 2019, at 03:10:37
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
uninstall popup does not appear in downloads section until you go back to library
when you click right a game in downloads section and you choose uninstall nothing happens but when you go back to main library section it will show a pop-up to uninstall the game

#### Steps for reproducing this issue:

1. go to download section
2. uninstall a game from there, at this moment nothing happens  
3. go back to library and it will prompt you for uninstall

**Comment by kisak-valve** [comment]
Hello @barfin, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
