### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#6661]
#### Your system information

* Steam client version (build number or date): 1573019418
* Distribution (e.g. Ubuntu): Ubuntu 18.04.03 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Open CS:GO
2. Try:
[-] Add to friend
[-] Look steam profile
[-] Take screenshot
[-] Run Steam Overlay

This features doesn't work

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
