### ISSUE TITLE
gnome-keyring asks for password when launching steam

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/steam-for-linux#6663]
#### Your system information

* Steam client version (build number or date): Nov 6 2019, 03:10:37
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
With the new steam update, if you have gnome-keyring installed you get a password pop up window.

![2019-11-07_13-22](https://user-images.githubusercontent.com/425930/68485779-16da9980-01fd-11ea-8ed4-f09c7edd833d.png)

**Comment by kisak-valve** [comment]
Hello @jazztickets, this issue is already being tracked at #6585. Closing as a duplicate.
