### ISSUE TITLE
[Remote Play Together] Unable to change source for audio recording

### ISSUE THREAD

**Issue by Jibodeah** [ValveSoftware/steam-for-linux#6670]
#### Your system information

* Steam client version (build number or date): 2019-11-07 23:57:46
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When hosting with remote play together, steam starts recording the entire system's audio (including, for example, Discord which one is talking to the friends you're trying to play with via). I have special null sinks and loopbacks setup in Pulseaudio so I can record the game from one that only includes the game. (essentially there's a 'loopback' sink which loopsback to my speakers. I put the game on that and then record from a monitor of it)

The problem is that steam **always** starts recording from a monitor of all my outputs. When I tab out of the game to fix this in pulseaudio control, steam pauses the stream and stops recording. The one dropdown I need to be able to change to fix this vanishes in front of my eyes. (...very frustrating)

Either it needs to keep recording even while tabbed out (which for me it used to!), or there needs to be an option to set the audio source from within steam itself (say the remote play window).

The game I was playing was Lovers In A Dangerous Spacetime but I don't think that's important to the issue.

#### Steps for reproducing this issue:

1. Start hosting steam Remote Play Together
2. Tab out of the game in order to try and change the audio stream Steam is recording from

**Comment by kisak-valve** [comment]
Hello @Jibodeah, this issue is already being tracked at #6625. Feel free to add your experience to that report.

Closing in favor of the existing issue report.

**Comment by Jibodeah** [comment]
@kisak-valve This is not *exactly* the same issue. I was effectively doing the filtering other sound sources out myself (via some pulseaudio sinks and loopbacks), but I'm no longer able to switch steam's audio recording onto the source I need to for steam to only be picking up the game audio.

I appreciate this issue becomes a non-issue if #6625 is fixed, but for now at least it is a separate issue.

**Comment by slouken** [comment]
Can you try with the latest Steam beta client? We've implemented game process audio capture for pulseaudio.

**Comment by Jibodeah** [comment]
That seems to have fixed it. (I don't seem to need to do my workaround with sinks and loopbacks anymore either)

Cheers!
