### ISSUE TITLE
Requires legacy deprecated lib32-libnm-glib over modern lib32-libnm

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6671]
* Steam client version (build number or date): Nov 7 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

The "lib32-libnm-glib" legacy package is deprecated, and isn't supported anymore. Its now proper to use the modern "lib32-libnm" package. Is there a particular reason Steam is still using the older library of this package?

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/1de8383ad9fdfc8f552117e5d109bdfa7005634b
 

1. Uninstall "libnm-glib" and "lib32-libnm-glib" packages equivilent to your distro
2. Leave "libnm" and "lib32-libnm" installed
3. Steam will not launch after signing in

**Comment by kisak-valve** [comment]
Hello @shoober420, this is already being tracked at #3129. Closing as a duplicate.
