### ISSUE TITLE
Are you gonna just ignore issue #3226 forever?

### ISSUE THREAD

**Issue by burjui** [ValveSoftware/steam-for-linux#6672]
Reported in 2014, no progress or feedback whatsoever.

**Comment by kisak-valve** [comment]
Hello @burjui, there's many long standing issues for the Steam client and there will be feedback when there's something notable to retest or a Valve dev needs additional information to understand the issue.

Opening an issue report to ask about another issue report will never result in a favorable response.

**Comment by burjui** [comment]
What will then? 5 years is a very long time in software development. Maybe devs should start to listen to users, instead of giving generic "we are busy" responses. The issue is painfully clear, there is nothing else to test or understand there, it's reproducible 100% of time. And it's not a minor thing, it actually prevents the user from installing the game, which is _already there_ on the disk, it's insane. Please do something. We don't want to buy bigger SSDs or re-download a hundred gigs just because of a Steam bug.
