### ISSUE TITLE
Remote Play Together - Audio from external applications available when hosting on linux

### ISSUE THREAD

**Issue by ShelbyZ** [ValveSoftware/steam-for-linux#6673]
#### Your system information

* Steam client version (build number or date): 2019-11-07 23:57:46
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Audio from external applications are available during Remote Play Together.  We had a voice chat through Teamspeak running and when the Linux users hosts a remote session that client can hear that audio when they are actively speaking.  When a Windows users hosts a remote session we do not experience the same issue.

#### Steps for reproducing this issue:

1. Have an external application providing additional audio (Teamspeak, media player)
2. Linux user host a remote play session to a client
3. Client is able to hear external application audio when joined to remote play session

**Comment by kisak-valve** [comment]
Hello @ShelbyZ, this issue is already being tracked at #6625. Closing as a duplicate.
