### ISSUE TITLE
IPv6 connectivity is not working as intended

### ISSUE THREAD

**Issue by Emanem** [ValveSoftware/steam-for-linux#6675]
#### Your system information

* Steam client version (build number or date): Nov 7 2019, at 23:57:46
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 LTS (with HWE - 5.0.0-32-generic)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have to disable IPv6 system wide to allow steam download at max speed (20 MiB/s) and to let connect to the _Friends_ network.

If I don't disable IPv6 I have to _retry_ connect to friends network twice or three times and the downloads speeds keep oscillating between 10 MiB/s to 100 KiB/s.
As soon as I disable IPv6, the download speed go back up to 20 MiB/s.

My ISP is not capping IPv6 connections (tested with Firefox and other software).

#### Steps for reproducing this issue:

1. Open the steam client and observe described behaviour
2. Disable IPv6
3. Download speeds go as intended

**Comment by kisak-valve** [comment]
Hello @Emanem, this issue is already being tracked at #6126. Closing as a duplicate.
