### ISSUE TITLE
KDE Plasma 5, unfocused chat window does not flash taskbar button on new message

### ISSUE THREAD

**Issue by dpanter** [ValveSoftware/steam-for-linux#6676]
#### Your system information

* Steam client version (date): Nov 7 2019
* Distribution: Siduction (Debian sid)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Expected behavior: When receiving a new chat message and the chat window is unfocused or in the background, the taskbar button should flash or light up to indicate the application has been updated and requests attention. That is the standard behavior in KDE Plasma 5/Kwin.

Current behavior: Only the 'new message' sound plays, the taskbar button does not indicate the chat window has received a new message.

#### Steps for reproducing this issue:

1. Open chat window
2. Send message
3. Focus on another application and wait for a message reply
4. Observe the chat window taskbar button

**Comment by kisak-valve** [comment]
Hello @dpanter, this issue is already being tracked at #2017 (and also mentioned at #3835). Closing in favor of the existing issue report.

**Comment by 39sdev** [comment]
this regressed once again.
chat windows are not being opened in a minimized state when messaged and the icon also doesn't flash. (KDE 6)
