### ISSUE TITLE
dbus-daemon --session makes steam render black window instead of browser.

### ISSUE THREAD

**Issue by monemoc** [ValveSoftware/steam-for-linux#6679]
#### Your system information

* Steam client version (build number or date): latest stable
* Distribution (e.g. Ubuntu): Void
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam refuses to draw in-window content (store and library content, etc. - pretty much everything, except stuff that is drawn by UI kit, like window frame, STORE, LIBRARY buttons above, settings, etc.) and instead shows black window with loading indicator above the top right corner of that black window.

Issue happens if I manually start dbus session via:
```
dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus
```
and as soon as I kill that daemon Steam instantly works as intended (window content loads).
I use this daemon for notifications, I would like to use steam without killing it and restarting manually after.
I would really appreciate any workaround.

#### Steps for reproducing this issue:

1. `dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus`
2. Start steam.
3. Admire the sight of the marvelous and flawless black rectangle inside Steam's window.

**Comment by kisak-valve** [comment]
Hello @monemoc, are you still experiencing this issue on an up to date system?

**Comment by smcv** [comment]
> Issue happens if I manually start dbus session

This sounds like something your OS developers should be setting up for you: on a well-integrated Linux distribution, you shouldn't need to do this yourself. For example, on Debian derivatives, systemd integration that starts a dbus-daemon listening on `$XDG_RUNTIME_DIR/bus` is provided by the `dbus-user-session` package.

**Comment by smcv** [comment]
> Steam refuses to draw in-window content (store and library content, etc. - pretty much everything, except stuff that is drawn by UI kit, like window frame, STORE, LIBRARY buttons above, settings, etc.) and instead shows black window with loading indicator above the top right corner of that black window.

That sounds like the symptom of a `steamwebhelper` crash, which means `~/.local/share/Steam/logs/steamwebhelper.log` and/or `~/.local/share/Steam/logs/cef_log.txt` might have useful information. Please attach those logs as files or share them as a gist.

**Comment by kisak-valve** [comment]
Closing pending feedback.
