### ISSUE TITLE
[feature-request]download games from another pc running steam in a local network

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6680]
#### Your system information

* Steam client version (build number or date): 7 Nov 2019
* Opted into Steam client beta?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Downloading and installing games from another pc running steam in a local network
It's mush easier to get backup and restore it on another PC or downloading it from internet

**Comment by kisak-valve** [comment]
Hello @barfin, this feature request is already being tracked at #3481. Closing as a duplicate.
