### ISSUE TITLE
Windows Buttons in Remote Play Settings look weird

### ISSUE THREAD

**Issue by karl-police** [ValveSoftware/steam-for-linux#6683]
Windows 64 Bit
Newest update on Steam

Button in Remote Play Settings look weird

![](https://i.imgur.com/IlRFldC.png)

**Comment by kisak-valve** [comment]
Hello @karl-police, issues with the Steam for Windows client should be reported to [Steam Support](https://help.steampowered.com/) for the larger support team.

That set aside, this issue is also being tracked at #6271. Closing as a duplicate.
