### ISSUE TITLE
Alien isolation is unplayable du to graphical corruption

### ISSUE THREAD

**Issue by Draluy** [ValveSoftware/steam-for-linux#6687]
#### Your system information

* Steam client version (build number or date): nov 11, 2019
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?:  No
* Have you checked for system updates?: Yes

Detailed system info: https://gist.github.com/Draluy/4f3f43988f7217e48d3171b2b14a0ba9

#### Please describe your issue in as much detail as possible:
Loading any save in Alien Isolation results in a garbled screen. Sounds play fine and some polygons can be seen, but the game is totally unplayable now. 
I'm guessing this is due to the most recent steam client update, as the game was working before, and no other software was updated on my computer.

#### Steps for reproducing this issue:

1. Launch Alien Isolation
2. Load any save.

**Comment by kisak-valve** [comment]
Hello @Draluy, this issue should also be mentioned to the game's dev(s) if it hasn't been already.

**Comment by Draluy** [comment]
Done

**Comment by kisak-valve** [comment]
If possible, please check if you've encountered https://gitlab.freedesktop.org/mesa/mesa/issues/2072 by downgrading to an older version of mesa or applying https://gitlab.freedesktop.org/mesa/mesa/commit/f93bb903020bac21a36e240b2c19a4733c2405ee to your current mesa build.

**Comment by Draluy** [comment]
Thank you for your analysis, it does look like that mesa bug (checked on XCOM2 and I can reproduce the same glitch in menus). I will try to downgrade as soon as I can and post the results.

**Comment by DataDrake** [comment]
I am also able to reproduce this. Rebuilding mesa 18.2.3 with that patch now to verify it fixes it.

**Comment by DataDrake** [comment]
After a brief "validation" session, I can confirm that that patch sorted the problem, thank you!

https://gist.github.com/DataDrake/d2b6af72d584ef6507ad17c9197140d3

**Comment by Draluy** [comment]
Thank you @DataDrake for your time. 
I'm not able to test anything for the time being, so @kisak-valve if you want to close this bug its fine, as this doesn't seem related to steam as I first thought.

Thanks for your kind help.

**Comment by kisak-valve** [comment]
Thanks for testing @DataDrake, closing as fixed in mesa 19.2.4 (released moments ago)
