### ISSUE TITLE
NVidia Optimus system doesn't have i386 drivers

### ISSUE THREAD

**Issue by igorsantos07** [ValveSoftware/steam-for-linux#6688]
#### Your system information

* Steam client version (build number or date): 2019-11-06
* Distribution (e.g. Ubuntu): Linux Mint 18.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Summary: Steam works fine on the Intel graphics driver, but when I switch to NVidia using Prime, it complains about 'glXChooseVisuals Failed`. From several searches I see I should install i386 drivers, but those are not available, and the proprietary NVidia drivers from their website (which should install compatibility drivers too) doesn't work well with Optimus computers either.

[Full report as a Linux Mint forum post](https://forums.linuxmint.com/viewtopic.php?f=59&t=305316&p=1713940)

This seems to be a problem related to #5600 (and not only a feature request) and maybe similar to #6090. There is a [pinned post on the Steam Forum](https://steamcommunity.com/app/221410/discussions/5/846939854395048434/) from 2012 which suggests the abandoned Bumblebee project (also at #634). Is that still a valid / the only solution?

> I'm trying to ignore the very dirty suggestion at #5741

**Comment by Leopard1907** [comment]
I use Steam with an Optimus laptop , no problems. Prime.

If you didn't disable secure boot from bios , i suggest doing that since it causes various problems when loading NV driver.

**Comment by kisak-valve** [comment]
Hello @igorsantos07, not that it directly helps, but the nvidia driver packaging for Ubuntu 16.04 predates a packaging split which reorganized the nvidia blob into separate components. The entire driver is in one large unified package. This is why you couldn't find 32 bit packages.

If you run Steam from a terminal, does the terminal spew give any hints?

Separately, nVidia's prime solution involves using the nVidia GPU to render everything while using the Intel to just scan out to the display. Bumblebee on the other hand, is a method to have individual applications offloaded to the nVidia GPU while the X server and desktop render on the Intel GPU. Bumblebee is comparable to [PRIME render offload](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html) which was introduced in nVidia's 435 driver series.

**Comment by igorsantos07** [comment]
@Leopard1907 I have secure boot disabled already. It would help to compare if you told us your distro and package versions :)

------------------

@kisak-valve, thanks for the explanation! I will think about testing Bumblebee at some other point too, but for now I've spent so much time and patience on the issue that I can only report it back and re-test what I've already done.

So, while testing outputs I noticed NVidia 430 only works on my machine under the Intel GPU. If I change to NVidia and reboot, it doesn't start. I downgrade to 418 and it's now booting properly on both options.

Well, under 430 started under Intel Steam opens fine. However, if I change in Prime to NVidia but do not reboot, Steam (under the new interface, it's awesome btw!) only half-opens. The window does open, but with nothing where the game libraries and sidebar should be, only the top and bottom parts of the window.

Here are the outputs: [Intel 430](https://pastebin.com/Qq2Cmc2Q); [NVidia 430](https://pastebin.com/GZZjCgWt) (I removed most of the "ignoring invalid property" because it was too long and repetitive, but left there most of the different props).

Then, after downgrading to driver 418 I booted under NVidia and got [this](https://pastebin.com/1Cw1ZXLR); changed to Intel without rebooting and the errors are [these](https://pastebin.com/pZ4iRMjr). If I boot under Intel it all works fine.

**Comment by Leopard1907** [comment]
My system: Linux Mint 19.2
Nvidia Driver 440.26

Intel Graphics HD Graphics 630+ Gtx 1050 4 GB mobile

No , don't ever use Bumblebee. It has significant performance overhead and it doesn't support Vulkan oob.

**Comment by igorsantos07** [comment]
@kisak-valve any news/ideas on this? :)

**Comment by kisak-valve** [comment]
Hello @igorsantos07, are you still experience with an up to date system? Linux Mint 18.x is no longer supported by the distro's maintainers.

**Comment by kisak-valve** [comment]
Closing as outdated.
