### ISSUE TITLE
Stop button does not work for proton games

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6689]
#### Your system information

* Steam client version (build number or date): Nov 11 2019, at 22:23:52
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Stop button does not work for proton games

#### Steps for reproducing this issue:

1. Start game with Proton
2. Press `stop` button

**Comment by underlineGalaxy** [comment]
I can confirm this is **still** an issue.

Especially annoying since when I open a proton game and it doesn't work I got no other choice than to restart my system

**Comment by fallenguru** [comment]
> when I open a proton game and it doesn't work I got no other choice than to restart my system

Alt-tabbing out and killing it usually works for me, in these cases?

**Comment by TriMoon** [comment]
I can confirm this is also the case on Kubuntu 19.10

**Comment by krompus** [comment]
It would be great if the button worked, but for now I have a script bound to a keybind (Alt+Shift+F4), to kill all `.exe`s:

`#!/bin/bash`
`kill -9 `ps -ef | egrep '\.exe'|awk '{print $2}'``

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? Most likely fixed by "Fix games not getting stopped via the 'Stop' button in the client UI (steam-for-linux#7435)" in the [2020-12-07](https://store.steampowered.com/oldnews/78652) Steam client update.

**Comment by XakepSDK** [comment]
Working for me

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed.
