### ISSUE TITLE
Yet another Segfault

### ISSUE THREAD

**Issue by vomidug** [ValveSoftware/steam-for-linux#6690]
#### Your system information

* Steam client version (build number or date): 1.0.0.61-3, the one from aur
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
```Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(0)
crash_20191114213043_1.dmp[226210]: Uploading dump (out-of-process)
/tmp/dumps/crash_20191114213043_1.dmp
/home/vomidug/.local/share/Steam/steam.sh: строка 906: 226178 Ошибка сегментирования                   (стек памяти сброшен на диск) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20191114213043_1.dmp[226210]: Finished uploading minidump (out-of-process): success = yes
crash_20191114213043_1.dmp[226210]: response: CrashID=bp-e4133cfc-f8ef-457f-aec4-95ffc2191114
crash_20191114213043_1.dmp[226210]: file ''/tmp/dumps/crash_20191114213043_1.dmp'', upload yes: ''CrashID=bp-e4133cfc-f8ef-457f-aec4-95ffc2191114''
```
Those russian lines are "Segmentation fault"

I tried running ~/.local/share/Steam/steam.sh and it shows some more errors

```
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-11-14 21:31:27] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
SteamUpdateUI: An X Error occurred
X Error:  BadValue
Request Major code 18
Value 0xffffff9c
Error Serial #25
xerror_handler: X failed, continuing
assert_20191114213127_1.dmp[243330]: Uploading dump (out-of-process)
/tmp/dumps/assert_20191114213127_1.dmp
./steam.sh: строка 906: 243297 Ошибка сегментирования                   (стек памяти сброшен на диск) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
 vomidug@Shaitan-Machine-Arch  ~/.local/share/Steam  assert_20191114213127_1.dmp[243330]: Finished uploading minidump (out-of-process): success = yes
assert_20191114213127_1.dmp[243330]: response: CrashID=bp-caef197a-99d7-4a2f-ad22-5e0372191114
assert_20191114213127_1.dmp[243330]: file ''/tmp/dumps/assert_20191114213127_1.dmp'', upload yes: ''CrashID=bp-caef197a-99d7-4a2f-ad22-5e0372191114''```
```
and yes, it gives a control back to the shell and then prints out some more logs

#### Steps for reproducing this issue:

1. Having Arch
2. yay -S steam
3. steam

I suppose, that smth is wrong w/ my X configs, but I tried to reinstall and reconfigure everything and no result. Thanks in advance

**Comment by kisak-valve** [comment]
Hello @vomidug, can you check if any 32 bit OpenGL application works like `glxinfo32` from `lib32-mesa-demos`?

**Comment by vomidug** [comment]
it was not installed before. I installed it and it shows a lot of info. I can post it if needed. Steam still doesnt work

**Comment by 7HEPOW** [comment]
Though I'm on Manjaro, I've encountered the same problem. I've noticed being on the 430xx branch of Nvidia drivers and updating them to 440xx (Packages being: lib32-nvidia-440xx-utils / linux53-nvidia-440xx / nvidia-440xx-utils) fixed it for me. I had to manually remove the 3 430xx packages prior to installing the 440xx branch. Maybe @vomidug can try that and let us know.

**Comment by vomidug** [comment]
> lib32-nvidia-440xx-utils / linux53-nvidia-440xx / nvidia-440xx-utils

@7HEPOW Are you using some custom repos? Or Manjaro ones? I don't see these packages, max version I have is `nvidia-410xx-utils`

**Comment by vomidug** [comment]
ragequitted and reinstalled arch. No new steam issues, closing this one
