### ISSUE TITLE
Pressing `enter` doesn't send message in Steam Chat

### ISSUE THREAD

**Issue by szmarczak** [ValveSoftware/steam-for-linux#6696]
#### Your system information

* Steam client version (build number or date): the latest as of 16th November 2019
* Distribution (e.g. Ubuntu): solus 4.0 64-bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:

1. Open Steam Chat while in-game
2. Type something, then press enter.
3. Instead of sending the message, it makes a new line.

**Comment by kisak-valve** [comment]
Hello @szmarczak, this sounds like Steam overlay got a shift or control modifier keydown event, but not a keyup event, so it thought the key was being held down. Were you alt-tabbed out of the game shortly before noticing this issue? If you can reproduce the issue, please tap your modifier keys and check if that makes a difference.

Possible duplicate of #3451.

**Comment by szmarczak** [comment]
I had already sent a message through a separate Steam Chat window. When a friend messaged me, CSGO was automatically minimized and it switched to that window. When I tried to reply, I couldn't. I'll let you know more in a few mins.

**Comment by szmarczak** [comment]
Correct. I'll comment there.
