### ISSUE TITLE
Steam disables power saving features

### ISSUE THREAD

**Issue by TwilightsHerald** [ValveSoftware/steam-for-linux#6699]
#### Your system information

* Steam client version (build number or date):  Nov 14 2019 
* Distribution (e.g. Ubuntu): Manjaro 5.3.11-1
* Opted into Steam client beta?: Yes/No, tried both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When Steam is running, my system refuses to shut monitor off, go into standby, or sleep.  Monitor may switch off for >5 sec. but quickly reactivates.

#### Steps for reproducing this issue:

1. Start Steam
2. Wait for screen shutdown to occur (it never does.)

**Comment by kisak-valve** [comment]
Hello @TwilightsHerald, this issue is already being tracked at #5607. Closing as a duplicate.
