### ISSUE TITLE
Mono is being mean

### ISSUE THREAD

**Issue by saum22** [ValveSoftware/steam-for-linux#6700]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): ChromeOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Get mono off of a mario kart level editor
2. relentlessly try to install 
3. Loss

**Comment by kisak-valve** [comment]
Hello @saum22, I'm failing to understand how a installing mono on ChromeOS is a Steam issue. Closing as not-our-bug.

**Comment by saum22** [comment]
how do you unistall mono
