### ISSUE TITLE
PROTON_USE_D9VK=1 does not work. Game refuses to run with command in Launcher.

### ISSUE THREAD

**Issue by smeep0** [ValveSoftware/steam-for-linux#6702]
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-4350 Quad-Core 
Video Card:
    Driver:  X.Org AMD PITCAIRN (DRM 2.50.0, 5.3.0-22-generic, LLVM 9.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 19.2.1
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x6818
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 16.14" x 9.06" (18.50" diag)
                                            41.0cm x 23.0cm (47.0cm diag)
    Primary VRAM: 2048 MB

Operating System Version:
    Pop!_OS 19.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.0-22-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20191024.0

* Steam client version (Nov 19, 2019): 
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When trying to run Assassin's Creed using Proton, the game will run as usual with `PROTON_NO_D3D11=1 %command%` as part of the "Set Launch Options".

However when adding the `PROTON_USE_D9VK=1`  in the Launch options, or using it as part of the user_settings.py, the game will seemingly be launching, but nothing will start and the "Launching" button on Steam will revert back to "Play".

AssassinsCreed_Dx9_d3d9.log produced the following entries

> info:  Game: AssassinsCreed_Dx9.exe
>info:  DXVK: d9vk-v0.90-2288-g1c550035d-froglet
>warn:  OpenVR: Failed to initialize OpenVR
>info:  Enabled instance extensions:
>info:    VK_KHR_get_physical_device_properties2
>info:    VK_KHR_surface
>info:    VK_KHR_win32_surface

#### Steps for reproducing this issue:

1. Install Pop!_OS and Steam
2. Install Assassin's Creed
3. Right click game entry -> Properties... -> Set Launch Options...
4. Enter `PROTON_NO_D3D11=1 PROTON_NO_D3D11=1 DXVK_HUD=compiler gamemoderun %command%` and click "Ok". Game will not run.
5. Remove entry `PROTON_NO_D3D11=1` from above line and game will run as normal, abeit with horrible framerates in big crowds.

**Comment by byte1024** [comment]
> info: Game: AssassinsCreed_Dx9.exe
> info: DXVK: d9vk-v0.90-2288-g1c550035d-froglet
> warn: OpenVR: Failed to initialize OpenVR
> info: Enabled instance extensions:
> info: VK_KHR_get_physical_device_properties2
> info: VK_KHR_surface
> info: VK_KHR_win32_surface

There's really no problem listed there. These few log entries won't be of any help.

My guess is that D9VK will get better once its been worked on more. Its still early times. But might be more applicable to have the issue at https://github.com/Joshua-Ashton/d9vk/issues instead.

**Comment by kisak-valve** [comment]
Hello @smeep0, we're tracking issues with games run with Proton in the Proton issue tracker, also we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/183#issuecomment-555508876.
