### ISSUE TITLE
Apt is blocking 32 bit mesa on ChromeOS's Debian container

### ISSUE THREAD

**Issue by saum22** [ValveSoftware/steam-for-linux#6703]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu):  ChromeOS Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Be me
2.  Use chromebook to install steam using guides for Debian
3. Loss 
![Screenshot 2019-11-19 at 10 41 14 AM](https://user-images.githubusercontent.com/57920010/69166769-66507d80-0ab9-11ea-8e5a-9df2df053bc0.png)

**Comment by kisak-valve** [comment]
Hello @saum22, what guide are you using? Did the guide you used cover enabling 32 bit support for debian like the "How to Enable 32bit Support" section of https://linuxconfig.org/how-to-install-steam-with-steam-play-on-debian-10-buster?

Please check if those packages are available from your package manager with something like `apt policy libgl1-mesa-dri:i386 libgl1-mesa-glx:i386`.

**Comment by saum22** [comment]
oh. ok, I'll do that

**Comment by saum22** [comment]
![Screenshot 2019-11-19 at 11 18 11 AM](https://user-images.githubusercontent.com/57920010/69169640-50918700-0abe-11ea-982d-8a7b796009ae.png)
What does this mean

**Comment by saum22** [comment]
also the debian command dosen't work for me

**Comment by saum22** [comment]
(deb, I mean.)

**Comment by kisak-valve** [comment]
It's telling you that there's 4 versions available, but none are installed.

Debian requires that 64 bit and 32 bit package variants have exactly the same version. Maybe try `sudo apt install libgl1-mesa-glx libgl1-mesa-glx:i386` to tell apt to install both variants at the same time? Note: DO NOT let it proceed if it tells you that it wants to remove a large set of packages.

**Comment by saum22** [comment]
Okay!

**Comment by saum22** [comment]
![Screenshot 2019-11-19 at 11 32 51 AM](https://user-images.githubusercontent.com/57920010/69170815-58eac180-0ac0-11ea-939d-450ea63e949c.png)
That didn't work

**Comment by kisak-valve** [comment]
Apt is trying to tell you that it's trying to select mesa 13.0 for 64 bit and mesa 19.2 for 32 bit and mixing versions is not allowed by debian, which is why it's not letting you proceed.

**Comment by saum22** [comment]
How do I solve that?

**Comment by kisak-valve** [comment]
I'm not seeing an obvious reason why the newer 64 bit mesa from stretch-backports and cros-packages are missing.

Is the system up to date? Please run:
`sudo apt update`
`sudo apt upgrade`
then check what packages are available with `apt policy libgl1-mesa-glx libgl1-mesa-glx:i386`.

**Comment by saum22** [comment]
Still fails.

**Comment by saum22** [comment]
![Screenshot 2019-11-19 at 3 01 20 PM](https://user-images.githubusercontent.com/57920010/69186077-78dcae00-0add-11ea-80c6-3ffb14f6010f.png)
wat

**Comment by kisak-valve** [comment]
@saum22, unfortunately, that tells us of a bigger problem. Your Chrome device is ARM-based, and is not supported on Linux. This is indicated by the installed mesa version being an arm64 package instead of an amd64 package. X86 and ARM processors have completely different instruction sets and can not share code. No games on Steam are compiled for ARM processors.

There's a feature request to support ARM-based linux installs at #4061.
