### ISSUE TITLE
Steam app low refresh rate 

### ISSUE THREAD

**Issue by ijaure299** [ValveSoftware/steam-for-linux#6708]
#### Your system information

* Steam client version (build number or date):  Latest as of this date
* Distribution (e.g. Ubuntu): Ubuntu, Arch
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

Scrolling through your app is running at 60hz with my 144hz monitor (running Nvidia GTX1070ti), on Windows your client is smooth at 144hz

#### Steps for reproducing this issue:

1. Get a 120+hz monitor 
2. Scroll through the app and notice the low refresh rate

**Comment by ijaure299** [comment]
To give you an example, Google chrome had this issue too and it was fixed in upcoming 79 version by importing the refresh rate from Xrandr (I think it was specifically on Nvidia)

**Comment by ErikReider** [comment]
Any news on this?

**Comment by kisak-valve** [comment]
Hello @ijaure299, are you still experiencing this issue on an up to date system?

**Comment by eleaf33** [comment]
It hasn't been fixed yet.
Arch, kde 5.25, nvidia driver 515.65.01, nvidia 3080.

**Comment by xpander69** [comment]
Ohh whoops, sorry i didnt notice this as i searched with different terms :D didn't think about searching with refresh rate
Anywa. Same issue here. 60 fps capped everywhere in steam client

**Comment by ErikReider** [comment]
Fixed with the latest update :)

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by eleaf33** [comment]
Its not fixed. Ubuntu 22.10.

**Comment by xpander69** [comment]
Yeah still capped to 60 here also with the latest beta.

easiest way to confirm it is to run `steam steam://open/console`

and then opening a site like vsynctester with: `open www.vsynctester.com`

capped to 60 in webviews everywhere and library scrolling seems to be even slower, but that might be some other issue.

**Comment by ErikReider** [comment]
> Yeah still capped to 60 here also with the latest beta.
> 
> easiest way to confirm it is to run `steam steam://open/console`
> 
> and then opening a site like vsynctester with: `open www.vsynctester.com`
>
> capped to 60 in webviews everywhere

The webview still seems to be capped at 60 for me too. 

> library scrolling seems to be even slower, but that might be some other issue.

It's silky smooth for me on Fedora with Sway

**Comment by xpander69** [comment]
Finally fixed here also when hw acceleration is disabled:

```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1705720677
Steam Client Build Date:  Sat, Jan 20 4:59 AM UTC -08:00
Steam Web Build Date:  Sat, Jan 20 3:04 AM UTC -08:00
Steam API Version:  SteamClient021
```

**Comment by kisak-valve** [comment]
Closing per the last comment.
