### ISSUE TITLE
Steam client fail to start.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6709]
#### Your system information

* Steam client version (build number or date): 1.0.0.61-7
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
```
Steam client doesn't start
Running Steam on manjarolinux 18.1.3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/laichiaheng/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1574216296)
/home/laichiaheng/.local/share/Steam/steam.sh: line 722: 16276 Killed                  $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

#### Steps for reproducing this issue:

1. Open Steam

**Comment by laichiaheng** [comment]
After I reboot my PC, it works...why??

**Comment by kisak-valve** [comment]
Hello @laichiaheng, this reads like you use the nVidia proprietary driver and a recent system update changed the driver version. If the running nvidia kernel module version does not match the userspace version, then most OpenGL applications will silently stall on application start while waiting on the driver.

**Comment by laichiaheng** [comment]
@kisak-valve Does it happen if I'm using AMD GPU?

**Comment by kisak-valve** [comment]
No, mesa is designed to interact with a wide range of kernel releases and userspace updates have always been independent of kernel updates.

**Comment by laichiaheng** [comment]
> No, mesa is designed to interact with a wide range of kernel releases and userspace updates have always been independent of kernel updates.

Then that's weird, because I'm using the AMD RX580 graphic card.
