### ISSUE TITLE
Event window wrong position

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6710]
#### Your system information

* Steam client version (build number or date): Nov 20 2019, at 01:49:33
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Desktop environment: KDE KWin

#### Please describe your issue in as much detail as possible:
Notification popups appear in middle of 2 monitors

#### Steps for reproducing this issue:

1. Install 2 monitors
2. Wait for group event appear
3. Event window (little windows with 2 buttons and text) appears in middle of 2 monitors

**Comment by kisak-valve** [comment]
Hello @XakepSDK, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
