### ISSUE TITLE
[KDE Plasma] Close Button Only Minimizes Window

### ISSUE THREAD

**Issue by Siheyuan98** [ValveSoftware/steam-for-linux#6711]
#### Your system information

* Steam client version : Nov 20 2019, 01:49:33
* Distribution: Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking the close button only minimizes the window into taskbar. Right clicking on the taskbar entry and selecting "close" shuts down the program.

What I expect is, by clicking the close button, the window closes and the taskbar entry disappears, while Steam keeps running with an icon in the tray. At present the close button functions exactly the same as the minimize button.

#### Steps for reproducing this issue:

1. Start Steam, window appears;
2. Click on the close button;
3. Window minimizes into taskbar;
4. Right click on the taskbar entry and select "close";
5. Window is closed and Steam exits.

**Comment by kisak-valve** [comment]
Hello @Siheyuan98, this is a Manjaro packaging issue and is already being tracked at #5307. Closing as a duplicate.

**Comment by Siheyuan98** [comment]
Thank you.
