### ISSUE TITLE
Remote Play Together don't work (the client restarts)

### ISSUE THREAD

**Issue by cucumb3r-user** [ValveSoftware/steam-for-linux#6714]
#### Your system information

* Steam client version: November 24, 2019 11:16 Moscow time
* Distribution: Ubuntu 18.04.3 LTS
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

The Steam client restarts, _sometimes the primary client remains, but it does not work._
I looked at what happens with Steam when a friend connected to me.
Log wrote me this:
`/home/vl/Steam/steam.sh: line 722: 19624 Segmentation error                   (memory stack flushed to disk) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"`
`assert_20191211153705_1.dmp[20504]: Finished uploading minidump (out-of-process): success = yes`
`assert_20191211153705_1.dmp[20504]: response: CrashID=bp-fa93c6de-2cec-4a7b-aca0-b765d2191211`
`assert_20191211153705_1.dmp[20504]: file ''/tmp/dumps/assert_20191211153705_1.dmp'', upload yes: ''CrashID=bp-fa93c6de-2cec-4a7b-aca0-b765d2191211''`
`Running Steam on ubuntu 18.04 64-bit`
So here is the file that was mentioned.
[assert_20191211153705_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/3950381/assert_20191211153705_1.zip)

#### Steps for reproducing this issue:

1. run the game
2. invite a friend to Remote Play Together
3. the client restarts **or** we expect a friend to respond, which will restart the client after

**Comment by edoantonioco** [comment]
It happens to me as well

**Comment by cucumb3r-user** [comment]
i'll just say it's still really
