### ISSUE TITLE
Stadia controller not detected

### ISSUE THREAD

**Issue by nonno-cicala** [ValveSoftware/steam-for-linux#6719]
#### My system information

* Steam client version (build number or date): Nov 20 2019, at 01:49:33
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] Tested both
* Have you checked for system updates?: [Yes/No] Yes

#### My issue:
My wired Stadia controller isn't detected by Steam.
It works perfectly in other programs.
If I start Steam from a terminal I read:
```
Local Device Found
  type: 18d1 9400
  path: sdl://0
  serial_number:  - 0
  Manufacturer: 
  Product:      Google Inc. Stadia Controller
  Release:      111
  Interface:    -1
```
But in controller configuration it says "No controllers detected"

#### Steps for reproducing this issue:

1. Connect Stadia controller using the provided USB cable
2. Start Steam
3. In Settings -> Controller -> whatever setting I try it says there is no controller detected or attached

**Comment by rogersachan** [comment]
https://support.steampowered.com/kb_article.php?ref=8293-PDVM-4434

Support for the controller was added to steam link as of build 710. Does this impact steam for linux as well?

**Comment by nonno-cicala** [comment]
Today I tested again with Steam build: Jan 24 2020, at 17:09:51 , package version: 1579911595 , and it works perfectly!
I also had some problems with the Steam Controller not detected in some games and now that's fixed too! Yay! :smiley:
