### ISSUE TITLE
Steam not recognizing Arcade/Fighting Stick

### ISSUE THREAD

**Issue by Khrona98** [ValveSoftware/steam-for-linux#6723]
#### Your system information

* Steam client version (build number or date): Built Nov 20 2019, at 01:49:33
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have a custom made Fighting Stick with a MadCatz Alpha board that was recognized on Steam on Linux before. The last time I tried it was at the beginning of the year if I recall correctly. It is still recognized as a USB device on my system, as you can see on the screenshot below, but steam fails to recognize it now for some reason.

![image](https://user-images.githubusercontent.com/9277125/69776882-c069d680-117c-11ea-949d-9022a5c9c2b6.png)

#### Steps for reproducing this issue:

1. Connect Fighting Stick
2. Try to configure it from Steam Controller Configuration or Big Picture mode
3. The Stick is nowhere to be found

**Comment by kisak-valve** [comment]
Possibly related change: https://hg.libsdl.org/SDL/rev/f77e63f04ff1

**Comment by zKhrona** [comment]
Sorry for the lack of response, I was waiting for the newer version os SDL with the fixes to land, and after that never got to really test it. But it seems that it still doesn't work, I also had a look at the link you provided and while related to MadCatz, that change was only for the FightPad, not for the Arcade Stick. Is there anywhere I can report this issue so the people behind SDL can fix it?

**Comment by kisak-valve** [comment]
Hello @zKhrona, SDL does have a bug tracker at https://bugzilla.libsdl.org/.

**Comment by Khrona98** [comment]
Hello again @kisak-valve and sorry for the late response. It seems that Steam is finally able to recognize my Fighting Stick again. It's been a while since I last tried it, so I don't know when it was fixed, but it seems to be working again. This issue can probably be closed now. Thanks for the all the help!!

**Comment by kisak-valve** [comment]
Closing per the last comment.
