### ISSUE TITLE
Spec Ops: the line, Free virtual address space dangerously low in a 32-bit process

### ISSUE THREAD

**Issue by bthiebault** [ValveSoftware/steam-for-linux#6725]
#### Your system information

* Steam client version (build number or date): Built Nov 28 2019, at 03:17:32, API v020, package versions 1574913081
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When launching the game with the default configuration by clicking the "Play" button in Steam, it displays the legal terms then exits.

I once or twice had an error message saying:

> Free virtual address space dangerously low (3.9GB taken out of 4GB possible to address in a 32-bit process)!
> Releasing old OpenGL textures, trying to avoid crash.
> Please consider lowering graphics quality settings or resolution to decrease the amount of memory used by the game.

My config is the following:

- Kernel: 5.3.12-arch1-1
- CPU: AMD Ryzen 9 3900X 12- (24) @ 3.800GHz
- GPU: NVIDIA GeForce RTX 2070 SUPER (with proprietary driver installed, version 440.31-3)
- Memory: 1447MiB / 32095MiB (4%)

Here is the crash report: https://pastebin.com/uynEMwPb

I have tried to force the use of a specific Steam Play compatibility tool, but whatever the proton version I chose, the game does not start. With Proton, I don't even have the legal terms displaying/

#### Steps for reproducing this issue:

1. Start Steam client
2. Go to library
3. Select Spec Ops: The Line
4. Click play

**Comment by kisak-valve** [comment]
Hello @bthiebault, this issue should also be brought to the game dev(s) attention. It also sounds similar to https://github.com/ValveSoftware/Source-1-Games/issues/2866. Please update your nVidia driver to 440.36 and check if that has an effect.

**Comment by bthiebault** [comment]
Unfortunately, updating to 440.36 did not have any effect.
I'll try and contact the game devs

**Comment by bthiebault** [comment]
Forgot to mention: the game worked flawlessly a few month ago. It ran perfectly on my machine. I wanted to replay the game this week and it just didn't work anymore.
I didn't change my system configuration except by keeping it up to date

**Comment by byte1024** [comment]
Its not necessarily the Nvidia driver according to the link that kisak mentioned.

Obviously, something changed on your system that the game has a problem with and that problem just happens to cause this. 32 bit applications only have access to 4GB max so it will not have access to more. In this case, its simply using too much of it which isn't much anyway.

It doesn't look like the game's devs are doing updated anymore (old game) or they could fix the problem. I don't think telling them about it will do anything for you in this case.

So it might be that the only thing you can do is try to roll back package updates (or find out some other way) until you find the one that causes it. Then alert the devs of that package to find out who should fix it.

**Comment by bthiebault** [comment]
No idea why, but the game works again. I just kept updating my system when updates where available and it now works.
Sorry I didn't have the time to investigated the root cause.
