### ISSUE TITLE
Steam does not open/render after enabling "Family View"

### ISSUE THREAD

**Issue by fermulator** [ValveSoftware/steam-for-linux#6726]
#### Your system information

* Steam client version (build number or date):  `1574913081`
```
ii  steam:i386                                                       1:1.0.0.54+repack-5ubuntu1                          i386         Valve's Steam digital software delivery system
ii  steam-installer                                                  1.0.0.54+repack-5ubuntu1                            all          Installer for Valve's Steam digital software delivery system
ii  steam-launcher                                                   1.0.0.49                                            all          Launcher for the Steam software distribution service
```
* Distribution (e.g. Ubuntu):  Ubuntu `18.04.3`
* Opted into Steam client beta?: [**Yes**/No]
* Have you checked for system updates?: [**Yes**/No]

#### Please describe your issue in as much detail as possible:
I've been running Steam for years on this system, same OS, numerous Ubuntu upgrade cycles.

Last week I was fiddling with "Family Sharing", and tried enabling "Family View", that worked. HOWEVER, the next time I closed & re-opened Steam, it is failing to open now.  I cannot see any obvious logs to search for that are relevant.  It _does not_ crash, it just doesn't render.

Roughly what happens:

1. Open steam (via GUI as usual, or `steam` on command line)

2. It briefly shows the "connecting" dialogue to the account
![2019-11-28_21:10:37](https://user-images.githubusercontent.com/6778269/69838973-b949d380-1223-11ea-9f2d-c8d151b7a0d8.png)

3. However then does NOT show the usual "steam interface", nor does it show in window manager (alt-tab, window list, etc)

4. Briefly I see the notification popup about "new item in inventory" (but it goes away quickly)
![2019-11-28_21:09:14](https://user-images.githubusercontent.com/6778269/69838982-c070e180-1223-11ea-9dd8-f1b7b6c36592.png)

5. If we can click on the "new item", then it opens a "dead" small box window, and suddenly shows "Family View" w/ Steam icon in the window list
![2019-11-28_21:09:21](https://user-images.githubusercontent.com/6778269/69838987-c5359580-1223-11ea-82b9-af0cfb63334c.png)
![2019-11-28_21:09:24](https://user-images.githubusercontent.com/6778269/69838992-c797ef80-1223-11ea-9f88-90f72cbe864d.png)

^^^ this is what has tipped me off that it is _because_ of enabling Family View.

#### Steps for reproducing this issue:

(what it was for me, uncertain if this is reproducible)

1. Linux, Ubuntu
2. Use Steam
3. Enable "Family Sharing", and switch to "Family View"
4. Close & Re-open steam

#### Workaround

If Family View is indeed the culprit, this worked for me as a workaround to get out of the stuck situation:
1. `steam -bigpicture` <-- it will load!
2. enter your PIN to leave family view
3. go into settings and DISABLE family view on the account
4. close steam
5. re-open steam = tada

**Comment by fermulator** [comment]
[steam_log_family_view_linux.txt](https://github.com/ValveSoftware/steam-for-linux/files/3903467/steam_log_family_view_linux.txt)

See attached, I _think_ a hint of the issue is with the `nss` libraries.

```
Installing breakpad exception handler for appid(steam)/version(1574913081)
Fossilize INFO: Overriding serialization path: "/home/fermulator/.local/share/Steam/shader_cache_temp_dir_vk_64/fozpipelinesv4/steamapprun_pipeline_cache".
roaming config store loaded successfully - 5765 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 10ms
[1128/211038.896227:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1128/211038.957992:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1128/211039.033964:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1574913081)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/fermulator/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 3.30 seconds
[1128/211039.531889:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1128/211039.536849:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[1128/211039.889451:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
BuildCompleteAppOverviewChange: 196
RegisterForAppOverview 1: 7ms
RegisterForAppOverview 2: 8ms
```

**Comment by fermulator** [comment]
Ah-HA!

`steam -bigpicture` loads, then I entered the PIN to leave family view, then DISABLED family view, closed, re-opened and it worked!
(updating WORKAROUND section in main submission)

**Comment by kisak-valve** [comment]
Hello @fermulator, this issue is already being tracked at #5296. Closing in favor of the existing issue report.
