### ISSUE TITLE
"Remember my password" always fail to automatically log in steam

### ISSUE THREAD

**Issue by bg2908** [ValveSoftware/steam-for-linux#6727]
#### Your system information

* Steam client version (build number or date): Nov 20 2019, at 01:49:33
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
When I check "Remember my password" box, Steam seem to remember the password and try to log me in the next times I open it.
But that step is always failed, it will show the text "Connect Steam account: ***** " then prompt me to manual enter password and Steam Guard code.
If I enter password and Steam Guard code, then it can successfully log me in.
If I refuse to fill in the password and turn steam off with "Remember my password" box still checked. It will continue to "Connect Steam account" the next times I open steam. Do this a few times, steam will prompt that there were too many failed attempt from this network and I must wait before I try to log in again.
All this only happens to my account. I had tried this with 1 other account that don't have Steam Guard and it didn't have the these problem.

#### Steps for reproducing this issue:

1. Enter login details, with the "Remember Me" box checked.
2. After logging in, exit steam.
3. Open steam.

Expected result:
Steam remembers my account info and logs me in automatically.

**Comment by kisak-valve** [comment]
Hello @bg2908, this issue is already being tracked at #5030 / #5035.

It may be worthwhile to check if you have `~/steam` (no dot) in your home folder, and if there is, if renaming it to something else makes a difference.

Closing in favor of the existing issue report.
