### ISSUE TITLE
Can't connect to friend's network

### ISSUE THREAD

**Issue by XXXBold** [ValveSoftware/steam-for-linux#6729]
#### Your system information

* Steam client version (build number or date): Date: 16. Dec. 2019, 16:49:05
* Distribution (e.g. Ubuntu): Linux Mint 19.2 Cinnamon (64-bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes (Is up to date)

#### Please describe your issue in as much detail as possible:
Connection to friend's network can't be established, but Internet connection is okay.
If I go to my profile in Steam, I can see the friend list and that some of them are online, but I can't connect in the friend's list. Also I cannot read/write any chat messages, even if I can see that there are some unread ones.
Friendlist:
![friendlist](https://user-images.githubusercontent.com/30773753/69905774-8bde6080-13b0-11ea-89a8-da0afe1786bb.png)

Viewing my profile in the steam client:
![my-profile](https://user-images.githubusercontent.com/30773753/69905776-8ed95100-13b0-11ea-9554-20afbb4dccc7.png)

If I launch steam from the console, and click on "Erneuter Verbindungsversuch" (Try Reconnect) on the friendlist window, following lines are output in console:
`[1130/211743.392395:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
[1130/211743.480280:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
[1130/211743.577775:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -200
`

#### Steps for reproducing this issue:

1. Start steam
2. Show friend list
3. See that there's no connection within the friendlist window, but internet connection is working & friends are visible if visited from Steamclient profile.

**Comment by kisak-valve** [comment]
Hello @XXXBold, please give #5612 a read and let us know if that's the issue you've encountered.

**Comment by XXXBold** [comment]
Not sure if it's the same issue, I've set my timezone to America/Argentinia Buenos Aires to test if it will fix the issue (My default is Europe, Zurich), but no change. Are there any specific Information I can provide to help you?

**Comment by XXXBold** [comment]
Just updated to new Client (06 Dec. 2019, 03:31:00), still no change.

**Comment by XXXBold** [comment]
I've built a new Machine for gaming, including a complete re-installation of the OS (Now on: Linux Mint 19.3, with Kernel 5.3) and all Software as well. I was pretty sure this would "fix" the problem, but no, it's still there.

Are there any steps I can do to locate the issue? Could this be an issue specific to my account?

**Comment by XXXBold** [comment]
Seems the issue is gone since a week or so, without any reason (No Client-update involved) and didn't occur again. Since I cannot reproduce this and have no idea what caused it, I'll close this for now.
