### ISSUE TITLE
Sometimes store browser does not work

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#6733]
#### Your system information

* Steam client version (build number or date): Nov 28 2019, at 03:17:32
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System info: https://gist.github.com/XakepSDK/304efe6e242e17ccb6ae5700c3226660

#### Please describe your issue in as much detail as possible:
Sometimes store browser does not work.
It just shows black window. Browser works if i open library or community and click store again or click one of subitems in store dropdown.
![grafik](https://user-images.githubusercontent.com/4938483/69973472-746fb680-151b-11ea-962b-f4efd5f4e4ce.png)

#### Steps for reproducing this issue:
1. Wait? I don't know.
2. Click on `STORE`
3. Browser does not work

**Comment by XakepSDK** [comment]
More info:
1. I'm in library
2. I click `STORE` button
3. Store opens, but black window
4. I click `STORE` -> `Explore`
5. It shows me website
6. I click `STORE` again
7. Black window
Also i did this again, but waited bit more on explore page, store shows now

**Comment by XakepSDK** [comment]
Ah, steam store index page is dead :frog:

**Comment by h1z1** [comment]
Something to check is what IP address do you get for store.steampowered.com?

```
host store.steampowered.com
wget -O /dev/null https://store.steampowered.com
```

**Comment by kisak-valve** [comment]
Hello @XakepSDK, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
