### ISSUE TITLE
Steam OS update borks video card drivers

### ISSUE THREAD

**Issue by Homeshine** [ValveSoftware/steam-for-linux#6734]
#### Your system information

* Steam client version (build number or date): 
4.1
* Distribution (e.g. Ubuntu): steam OS
* Opted into Steam client beta?: [Yes/No]
NO
* Have you checked for system updates?: [Yes/No]
YES
#### Please describe your issue in as much detail as possible:

I tried opening a support ticket with Steam, and they said they weren't familiar with the Steam OS version of the steam client and my only possible solution is to post here.

I have an Alienware steam machine running Steam OS, and a recent Steam update has effectively bricked it. When I boot it, it gets all the way through the bubbles going up animation, and then it simply boots to a black screen. I can move the mouse and click on the black screen and it makes sounds as if I'm clicking on things; it simply won't display anything.

I've tried reinstalling the entire steam client and restoring from the recovery partition to reinstall the entirety of steamos, but these both failed to fix the issue.

When I boot into desktop mode it works perfectly fine, but I can't play any games that way. So I don't believe it to be a hardware issue. Something and the steam client update has Nerfed the graphics drivers from Steam OS, but I don't know how to fix that.

**Comment by kisak-valve** [comment]
Hello @Homeshine, your previous issue report was transferred to https://github.com/ValveSoftware/SteamOS/issues/702 because it reads like a SteamOS issue instead of a Steam client issue.

Please do not intentionally open duplicate issue reports. Closing as a duplicate.
