### ISSUE TITLE
steamwebhelper.sh causes entire computer to freeze, then self-reboot

### ISSUE THREAD

**Issue by bismurphy** [ValveSoftware/steam-for-linux#6735]
I contacted Steam support regarding this issue, and they directed me here. Below, I have pasted the information I provided to them. Please let me know if other information would be helpful. Hopefully I covered everything :) Thanks!

-----------------------

Hi!

I'm running Ubuntu 18.04.3. I'm experiencing an issue where opening Steam will cause my computer to entirely crash. The exact behavior is that when I open the Steam client, I get the normal login box, then enter my Steam Guard info, then the main Steam window opens. From here, the problem happens. In as little as 1 second, or as much as 20 seconds, my computer completely stops responding to input. I can't move my mouse, and keyboard combinations like CTRL ALT T or CTRL ALT F3 do nothing. If I have audio playing (such as through YouTube), the moment of audio that is playing at that time will freeze or loop (so someone saying "I fear no man" may turn into "I fear-fear-fear-fear" and/or "I fear nooooooooooooooooo"). The computer stays in this non-responsive state for 30-60 seconds, then it automatically reboots itself, and then brings me back to a fresh launch of the OS.

I have found that if I go into the proper directory and do a "sudo chmod -x steamwebhelper.sh", I am able to launch Steam without having this problem. It works perfectly - however, of course, since everything relies on steamwebhelper, I can't actually do anything in Steam (side-note: The old Library didn't use steamwebhelper, but the new one does. Now with the new Library, I can't even use this workaround to launch my games anymore. Is there any way to revert back, until this bug gets resolved?). The only workaround I can do is to launch into Big Picture Mode, which doesn't seem to rely on the steamwebhelper. But of course, it would be nice for Steam to be fully functional.

After a lot of debugging, I decided to do a full reinstall of my operating system, deciding that something must be very wrong, and beyond fixing. Then I installed Steam, and saw that this issue STILL happens. That means I'm observing Steam crashing on a fresh installation of Ubuntu 18.04.3, and not only crashing Steam itself, but my entire computer.

I have not observed any other crashes except for this one that happens from Steam. This makes me believe the problem is not with my computer, otherwise other applications would be likely to crash it. Additionally, if I use the Big Picture Mode workaround to launch a game, nothing crashes, even though I would imagine a game ought to be stressing things if it was a RAM or GPU problem or something of that nature. I've also looked at my drive's SMART data, and nothing appears to be wrong with anything.

I've looked in my system logs, and nothing shows up as a fault or anything. It's as if the whole computer goes down so instantly that it doesn't even have time to make a log.

At this point, I see two possibilities. #1 is that Steam has a bug. #2 is that I'm doing something wrong (and/or my computer has something wrong with it). Could you please help me determine which of these is the case? I am very happy to provide any files that would be helpful, or try any type of patches or whatever else would be necessary to make this work. I've been using Steam for years, and would love to "give back" by doing any diagnostics you would find helpful.

Hopefully this wasn't too long-winded! Just wanted to provide as much info as possible to give an idea of what I'm seeing. Thanks!

**Comment by kisak-valve** [comment]
Hello @tj-murphy, in general, no OpenGL application including libcef should be capable of taking down the entire system. This reads like a video driver issue. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by tj-murphy** [comment]
Hi!

Here's the gist: https://gist.github.com/tj-murphy/eccfdba4d60a7ce6583212ce890a5cba
Let me know if more info is missing, that I should get from inxi or otherwise.

**Comment by kisak-valve** [comment]
That's fairly common hardware besides the impressive amount of ram in the system. I'm not aware of any particular quirks with it.

I'm not going to be able to help much here, but you can try running `steam -no-browser` from a terminal, then going to Steam -> Settings -> Interface -> Uncheck `Enable GPU accelerated rendering in web views (requires restart)` which has a decent chance of putting less stress on the video driver.

Separately, you could try [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) or similar mesa PPA and check if that has an effect. If the PPA helps, than that confirms there's a video driver bug which has already been fixed upstream.

**Comment by tj-murphy** [comment]
Okay, so I did the -no-browser and that seemed to make it work (nice to know that this exists as an option; is there any full list of options like this?) but of course, the library is still not visible. But nice to know I can do this, rather than needing to go in and change the permissions on the .sh file.

Unfortunately, when I unchecked the GPU acceleration, that didn't seem to fix it. Steam did launch successfully, and I let it sit for a few minutes with no problems. But the moment I tried to scroll down on the store page, it froze up like always.

Next I'll try the PPA. Thanks for your suggestions!

**Comment by tj-murphy** [comment]
Interesting - in that issue the person says they crash to login screen, versus with mine it entirely crashes the computer to do a full reboot, same as if I were to unplug the computer and power back up.

**Comment by OvermindDL1** [comment]
I just got to thinking, this sounds an awful lot like an issue my wife's computer had (similar hardware (amd instead of intel, same gpu), same OS) for a while, but in Chrome, until I updated both the kernel to a newer version, updated mesa to absolute latest, and updated the system to 19.10 back in October.  I don't know which fixed it, but check these.  Updated to 19.10 first, if that doesn't work then grab the padoka mesa PPA or so and fully update that, if that still doesn't fix it then install a new mainline kernel ([this script](https://github.com/pimlie/ubuntu-mainline-kernel.sh) makes it a single-command easy but it's easy to do regardless), and of course know what you are doing and how to revert it if something breaks as touching your kernel is something you should know how to do and do with purpose so don't look at me if something happens.  ^.^;

**Comment by OvermindDL1** [comment]
I remotely got into my wife's system, her MESA version is currently 19.1.2 (which is definitely newer than yours at 19.0.8), the kernel version is 5.0.0-36, same as yours (19.10's security updates must have finally included it).  And your Ubuntu version is very very old (18.04?!).  So to start in this case I'd recommend fully updated MESA to at least 19.1.2.

**Comment by tj-murphy** [comment]
18.04 is the latest LTS version of Ubuntu, and is only 1.5 years old - not what I'd call "very very old".

To be honest, I DON'T know what I'm doing here, so rather than blindly making changes, I'd prefer to wait until someone can recommend direct procedures to attempt, such as what kisak suggested above with the -no-browser and the PPA.

**Comment by OvermindDL1** [comment]
> not what I'd call "very very old".

By that I mean the version of some related packages it pulls in, they aren't all well updated for newer GPU's.

At the very least installing the padoka PPA will update MESA (fully supported on 18.04), it has two versions, the STABLE, and the LATEST, the STABLE can be setup like:
```zsh
sudo add-apt-repository ppa:paulo-miguel-dias/pkppa
sudo apt update
sudo apt upgrade
```
And the LATEST can be setup like:
```zsh
sudo add-apt-repository ppa:paulo-miguel-dias/mesa
sudo apt update
sudo apt upgrade
```

I recommend STABLE unless you are specifically wanting some of the newer features.  STABLE is a bit out of date but it at least has MESA 19.2.2, which is a great deal newer and worth trying.

> To be honest, I DON'T know what I'm doing here, so rather than blindly making changes, I'd prefer to wait until someone can recommend direct procedures to attempt, such as what kisak suggested above with the -no-browser and the PPA.

Installing the STABLE version should be entirely safe, worst case you can remove the repository and reinstall the older version, but STABLE contains the minimal recommended version for security and stability.

**Comment by tj-murphy** [comment]
Okay, now this is a strange one.

I did the STABLE version suggested. The repository added just fine. Then updated just fine. But when I went to upgrade, the computer crashed in exactly the same way as it does when I try to launch Steam (everything freezes, sits for a little while, then auto-reboots). I captured the state of the terminal during the freezy period, so hopefully it can provide some insight: https://i.imgur.com/lJFsAfY.jpg

What might cause this? Doesn't seem related to graphics drivers...

**Comment by OvermindDL1** [comment]
> But when I went to upgrade, the computer crashed in exactly the same way as it does when I try to launch Steam (everything freezes, sits for a little while, then auto-reboots).

That definitely sounds like a GPU issue.  If you upgraded MESA but it did that on upgrade (which does immediately register the new driver, a benefit over binary blobs), then now I'm leaning to a hardware issue on either the GPU or motherboard/RAM.  Have you tried running a hard stress test on the GPU for hours (the complete phoronix test suite maybe)?  `memtest86` on your RAM overnight?  Etc...?

**Comment by tj-murphy** [comment]
I've never done any type of hardware stress test. Could you please link me to a guide?

**Comment by OvermindDL1** [comment]
This is a simple download, run, and wait version that I like to use.  It doesn't test 'all' of the GPU and it could be when a certain part of it is accessed is when your system freezes, but there are other tests in the full openbenchmark suite and I'd imagine something would cause it in that cast:  https://openbenchmarking.org/test/pts/gputest-1.3.2

And also let memtest86 full scan run overnight sometime, just to rule out the RAM.  :-)

If it's the motherboard or CPU that can be more... tricky to figure out.

**Comment by tj-murphy** [comment]
So I installed the phoronix test suite. I launched it, gave "interactive" which listed a few options, one of which was to run a stress test, but then in the options of tests to run, I don't see "gputest" in the list. Of the options that list Graphics as the category, many of them are the names of games, and a couple say things like Cuda or Tensorflow. Where exactly do I find your gputest within the software?

**Comment by OvermindDL1** [comment]
What options did you have?

**Comment by tj-murphy** [comment]
Here are all the options I have for stress tests:
https://gist.github.com/tj-murphy/10d1a8ebac992673eaa9695ab2517752

**Comment by OvermindDL1** [comment]
Oy, I don't recall what it was called now.  Maybe just start with running all the Graphics ones?

**Comment by tj-murphy** [comment]
An update: with the help of another user elsewhere, I've tracked down that the issue seems to be in Chromium. 

I installed the `chromium-browser` package through apt, and when I try to launch `chromium-browser`, I get the same exact freeze-and-crash. The same happens after I installed Vivaldi (another browser based on Chromium) through its .deb installer from its website.

It looks like Electron apps use the same rendering engine as Chromium. So I installed Discord from its website as a test of Electron apps. That works just fine. So it sounds like the issue lies in Chromium, but not in its rendering engine specifically. Should I seek out help in a more Chromium-specific place? Where might that be?

**Comment by OvermindDL1** [comment]
It is not a Chromium bug per-say, but rather that Chromium hits the GPU hard and in unexpected ways.  This makes it more likely to hit driver issues of drivers of poor quality especially.

Asking in a more chromium-centric area would probably be useful though, either the official mailing list or maybe Reddit or so?

**Comment by kisak-valve** [comment]
Hello @bismurphy, are you still experiencing this issue on an up to date system?

**Comment by bismurphy** [comment]
Ah, sorry for failing to follow up. This issue was fixed when I updated my BIOS, strangely enough. Must have been some very strange combination of factors landing on a weird edge case which was fixed by the newer BIOS. Thanks for checking up on this!
