### ISSUE TITLE
Steam is always crashing my whole system to login screen after a quite specific time.

### ISSUE THREAD

**Issue by autotoxicus** [ValveSoftware/steam-for-linux#6736]
#### Your system information

* Steam client version (build number or date): currently November 29th 2019, but I also was in the most recent beta before
* Distribution (e.g. Ubuntu): Linux Mint 19.2 
* Opted into Steam client beta?: [Yes/No] Yes and No, a have already tried both
* Have you checked for system updates?: [Yes/No] Yes, it was up-to-date

#### Please describe your issue in as much detail as possible:

Since some time yesterday Steam is crashing my whole system to the login screen every time 1.10 to 1.30 minutes after starting the client. The system seems to freeze for a few second (can't move the mouse cursor anymore) and then crashes the login screen. 
Other than that my system runs perfectly stable. 

#### Steps for reproducing this issue:

1. Start Steam
2. Wait between 1.10 an 1.30 minutes
3. 

What I have already tried to fix this (to no avail):
-opting out of Steam Beta
-booting with older sytem-kernels, namely 5.0.0-36, 5.0.0-35 and 4.18.0-25 (from originally 5.0.0-37 that was installed yesterday)
-restored my system to a backup from December 1st and later also November 30th (edit: does not affect he home folder and therefore not the Steam installation too)
-deleted AppCache folder in Steam installation

**Comment by kisak-valve** [comment]
Hello @autotoxicus, in general, no OpenGL application should be capable of taking down the entire system, which hints that this is a video driver issue. Can you check if you're experiencing the same issue as #6735?

Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by OvermindDL1** [comment]
If you use a recent AMD card (within past few years) make sure your MESA version is updated to at least 19.1.2 (padoka PPA or so is fine) and try again?

**Comment by autotoxicus** [comment]
I'm not so sure if this other issue is comparable. It takes quite a bit longer for me until the system  freezes and it's only unresponsive for one to three seconds. I wanted to try if launching directly in Big Picture mode would make a difference (switching directly there after start didn't), but with that setting active Steam wouldn't want to start anymore at all which took me a few hours to find a way how to fix (steam -nobigpicture). 
Here the system information:
<script src="https://gist.github.com/autotoxicus/ad030aa84fb0c9d53dcd42dc18b33b9a.js"></script>

Regarding graphics driver: I have updated my graphics driver on November 20th last time, so a few days before these crashes have started. But I'm not using MESA, but AMDGPU-PRO as I couldn't get Vulkan to work with MESA. So far didn't have any problems with the official AMD drivers (except I cannot uninstall it without breaking the whole system). The new graphics driver possibly be the culprit, but not clearly. I already try over installing the older version again, that didn't work too. Has problems with allegedly broken packets.

**Comment by OvermindDL1** [comment]
From my understanding, AMDGPU-PRO is pretty out of date now, AMD dev's their main driver in MESA now, and MESA most definitely has vulkan support (arguably one of the best).  I'd try removing AMDGPU-PRO and trying MESA at least 19.1.2.  MESA 'is' the official AMD driver now though, and you never want to install an AMDGPU-PRO over anything else, even an older AMDGPU-PRO installation as it has been known to cause instability, need to do a complete uninstall, reboot, then install, then reboot.

**Comment by autotoxicus** [comment]
@OvermindDL1 I did try to uninstall AMDGPU-PRO quite a few times now, every time my system ended up not being able to start the GUI anymore. I spend a lot of time trying to fix that (even re-installing the AMD-Driver didn't fix it), in the end I always ended up restoring my system with Timeshift.

@kisak-valve I have now actually tried the ownership of the steamwebhelper.sh. I know it was working, because I couldn't see the library, but for me the crashes did still occur. So I suppose we can clearly say that I have a different problem.

**Comment by OvermindDL1** [comment]
> every time my system ended up not being able to start the GUI anymore

That sounds like it's already corrupted.  Was AMDGPU-PRO ever installed on another AMDGPU-PRO or other GPU driver?  There's a wiki around the net somewhere that walks through how to clean it out.

**Comment by autotoxicus** [comment]
I always just install the new versions over the old ones. Is that a problem (I mean on Windows you typically update graphics drivers like that too)?

**Comment by OvermindDL1** [comment]
It's not a problem with proper packaging, but the old AMDGPU/AMDGPU-PRO drivers had bugs that caused issues.  This issue was resolved when AMD switched to using MESA for the main driver load.

**Comment by autotoxicus** [comment]
I have my RX570 only since March this year (2019). I would hope these bugs were already fixed then?

**Comment by autotoxicus** [comment]
OK, I have an update on the situation:
It seems the driver update wasn't the reason for this. I have uninstalled 19.30 (as AMD states on their website with "amdgpu-pro-uninstall") and then successfully installed 19.20 (which I had installed before). To my surprise my system did reboot properly and a check with "dpkg -l amdgpu-pro" confirmed that 19.20 really is installed. But Steam still keeps crashing.

**Comment by OvermindDL1** [comment]
I'm still for saying that mesa should be used, but excepting that, what's your xorg log for the crash.  If you are crashing back to the login prompt that means that xorg is crashing, which is most likely a GPU driver issue (hence the still for using MESA), but the log would say for sure.

**Comment by autotoxicus** [comment]
Only these two errors I could find in the xorg.0.log and the xorg.1.log under ~/.local/share/xorg
[   369.576] (EE) Failed to load module "nvidia" (module does not exist, 0)
[  1922.986] (EE) open /dev/fb0: Permission denied

**Comment by OvermindDL1** [comment]
You might need to look at the system xorg log, or `journalctl` for systemd for the timeframe that it happens.

**Comment by autotoxicus** [comment]
I fixed it!
What I did was uninstalling the tool "Steam Linux Runtime" (btw I have not the slightest idea for what it is good for) which simply appeared a while ago for me in the Proton list. The strange thing is that this tool wasn't causing that before and I have also reinstalled it now and there are still no crashes.

So yesterday I have tried "Are you ready for Valve Index?". To my surprise it was starting through Proton (no native Linux version, although Index is supposed to be Linux compatible). I think what broke this "Steam Linux Runtime" that way was either that I have selected it instead of Proton for the Index test (and tried to run it that way) or that I have tried to run the Steam Linux Runtime directly which made it appear in my home screen of the new library.

I will try to reproduce this issue and let you know if I find out more.

**Comment by OvermindDL1** [comment]
Interesting, I've not ran across that before.  Even regardless it should be impossible to crash xorg without a lower driver level issue (or xorg bug), so this still shouldn't have happened...  Hmm...

**Comment by autotoxicus** [comment]
I gave it a test and can clearly confirm now that it has to do with the "Steam Linux Runtime" alone. Trying to launch it directly is causing this issue and you need to uninstall it (and can possibly reinstall it directly) to get rid of it. Purely the fact that it shows up in the home screen is certainly also a bug (as this doesn't happen when launching the Proton versions directly), but that isn't causing the crashes.

BTW I have I have found a Reddit post that explains very well that this is basically a Linux container. I like that idea, this concept could also be something for Windows in the future to be able to run older games that have problems with Windows10 or even older versions of Windows.

**Comment by autotoxicus** [comment]
This morning it crashed again. I had reinstalled Steam Linux Runtime and, while it didn't cause this problem immediately, the crashes started again after restarting Steam or perhaps just rebooting the whole system.
Uninstalling the Steam Linux Runtime fixed it again, so I will have to to keep it uninstalled for now.

**Comment by jvalrog** [comment]
My Ubuntu 18.04 is also crashing but after some random time (30 min to several hours).

In my case I'm using Nvidia (gtx1050) with 16gb ram and Amd Ryzen 5 1600.

Everytime my system crash, Steam is the common denominator. And sometimes Steam is the only open app on my desktop. I can't get crash information since the journal stops just before the crash.

**Comment by xenon205** [comment]
> My Ubuntu 18.04 is also crashing but after some random time (30 min to several hours).
> 
> In my case I'm using Nvidia (gtx1050) with 16gb ram and Amd Ryzen 5 1600.
> 
> Everytime my system crash, Steam is the common denominator. And sometimes Steam is the only open app on my desktop. I can't get crash information since the journal stops just before the crash.

I have simillar problem. GTX1070 , 32GB ram, Intel 6700HQ

**Comment by kisak-valve** [comment]
Hello, @autotoxicus, @jvalrog, @xenon205, are any of you still experiencing this issue on an up to date system?

**Comment by jvalrog** [comment]
Fixed for me, thanks

**Comment by autotoxicus** [comment]
I haven't installed Steam Linux Runtime ever again since back when found out it to be reason for this issue (only Steam Linux Runtime - Soldier was actually installed). I have just installed and executed it once again and will let you know how it turned out in a next days.

**Comment by autotoxicus** [comment]
@kisak-valve So far no crashes on both, my Desktop-PC (I have been using back then) and my new Mini-PC. Both with up-to-date installations of Linux Mint 20.3 64-Bit.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as outdated.

**Comment by erkinalp** [comment]
Still occurring, and this time worse.
