### ISSUE TITLE
Video Playback of Newer Encoded Videos From YouTube Fail

### ISSUE THREAD

**Issue by speakn2pabst** [ValveSoftware/steam-for-linux#6744]
#### Your system information

* Steam client version (build number or date):   Steam Client Beta - Dec 5th, 2019
* Distribution (e.g. Ubuntu):   Manjaro 
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No]  Yes

Sys Info Gist  -   
https://gist.github.com/speakn2pabst/0c1fc79a87c5eabf1b1795fc4b330253

Also  dav1d  package from distro repositories is installed.

#### Please describe your issue in as much detail as possible:

Certain YouTube videos don't playback in either the Steam Overlay Browser, Big Picture Mode Browser or embedded in the Client for example under the activities page or forum pages.  Upon clicking on the video a startup animation shows briefly, then a Youtube error message is displayed.
Example:   An error occurred. Please try again later. (Playback ID: 53AYLI1Y9Gmx77VW)

They all seem to be videos encoded in   avc1.42001E   with   mp4a.40.2

The problem seems limited to the Steam browser because I can playback these files for instance with an installed Chromium browser or Firefox (but both serve the audio in opus not mp4a while the video remains in avc1).

#### Steps for reproducing this issue:

Following is a Steam page with many YouTube video links (featuring video game music).  The first two Dec 5th entries are failing avc1+mp4a videos (Shinobi + Final Fantasy) while the 3rd video has no issues during playback as it is served in vp9+opus (Pokemon).
https://steamcommunity.com/groups/vgmclub/announcements

This above page receives frequent updates so I apologize if the described examples start sliding down or to another page.

Older av1 videos work such as these included in these included in an av1 beta launch YouTube playlist encoded in 
Codecs : av01.0.05M.08 (398) / opus (251)
https://www.youtube.com/playlist?list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS
[These videos' playback was tested in Big Picture Mode Browser.]

Thanks for your consideration.

**Comment by arrowgent** [comment]
tested what you said
[The Revenge of Shinobi] Run or Die (12” Mix) by 8-BeatsVGM

avc1.4d4014 (135) / mp4a.40.2 (140)

same thing.

steam fails
chromium works fine


in steam's console `open https://www.youtube.com/watch?v=Gfx6vVoPtiU`
also fails

**Comment by kisak-valve** [comment]
Hello @speakn2pabst, @arrowgent, are either of you still experiencing this issue on an up to date system?

**Comment by speakn2pabst** [comment]
Hello.  I just revisited the issue and did not experience the same error.  The video linked by arrowgent played fine using the console.

avc1.4d4014 (135) / opus (251)

I've changed distros from Manjaro to Arch but I think it likely doesn't matter regarding this issue.

In my opinion the issue can be considered resolved/closed.  Thanks for your consideration.
