### ISSUE TITLE
Can not login in Fedora

### ISSUE THREAD

**Issue by namandixit** [ValveSoftware/steam-for-linux#6745]
#### Your system information

* Steam client version: Nov 29 2019, at 00:22:05
* Distribution: Fedora 30
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I try to start and login into Steam, most of the times it simply refuses to log in into the client. Other times, it logs in; but when I try to browse the store, it tells me that I am **not** logged in, tries to log me in inside the client browser and fails. This happens even if I try to start with `steam -tcp`. Running `steam --reset`, reinstalling Steam and completely nuking the `~/.local/share/Steam` didn't fix the issue.

[Here](https://gist.github.com/namandixit/3e673c58d8f4fa791bfe7c3417c6ae55) is the startup log, note the following error in the log:

     opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates

#### Steps for reproducing this issue:

1. Start the Steam client.
2. It refuses to login with message "Could not connect to the Steam network" (Screenshot [1](https://user-images.githubusercontent.com/8736472/70372417-8f08ad80-18d6-11ea-8d33-0c164dab273f.png))
3. If it does logs me in the client, the login status doesn't propagate to the Store tab. (Screenshot [1](https://user-images.githubusercontent.com/8736472/70372383-130e6580-18d6-11ea-8dab-15b7b2fba55d.png), [2](https://user-images.githubusercontent.com/8736472/70372386-23264500-18d6-11ea-9057-a38d59dd76d2.png), [3](https://user-images.githubusercontent.com/8736472/70372389-27eaf900-18d6-11ea-9174-a23f89f43b7c.png))

**Comment by namandixit** [comment]
Following is the output when starting `steamcmd`:

    Redirecting stderr to '/home/naman/.local/share/Steam/logs/stderr.txt'
    Looks like steam didn't shutdown cleanly, scheduling immediate update check
    opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...opensslconnection.cpp (1519) : Assertion Failed: unable to load trusted SSL root certificates
    CreateBoundSocket: ::bind couldn't find an open port between 27060 and 27060
    OK.

**Comment by byte1024** [comment]
It might be with Fedora but I don't think this is a Fedora based issue. I have Fedora 31 and its fine, the packages should be the same or close for this.

Also the issue with the certs is using apt-get here so Debian based with a fix: https://steamcommunity.com/app/221410/discussions/2/1693785669860391247/

**Comment by namandixit** [comment]
@byte1024 I have tried `sudo dnf reinstalll ca-certificates`, but that did not help. I have also tried switching between RPMFusion's and Negativo's `steam` package. It's possible they broken it in F30, I'll try upgrading to F31 and see if that helps.

**Comment by namandixit** [comment]
@byte1024 I have updated to Fedora 31, and it is still not working.

**Comment by namandixit** [comment]
[This](https://gist.github.com/namandixit/91a26c06b3b05e402666b35b1432a619) is the log when running `steamcmd` under `strace`. Note the following lines:

    lstat64("/etc/ssl/certs/ca-certificates.crt", {st_mode=S_IFLNK|0777, st_size=22, ...}) = 0
    openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)

In truth, the file `/etc/ssl/certs/ca-certificates.crt` exists:

    $ ls -al /etc/ssl/certs/ca-certificates.crt
    lrwxrwxrwx. 1 root root 22 Nov 12 03:25 /etc/ssl/certs/ca-certificates.crt -> /etc/ssl/ca-bundle.pem

**Comment by namandixit** [comment]
Installing RPMFusion's Steam on Fedora 31 fixed the issue, closing...

**Comment by freemin7** [comment]
@namandixit Can you point to how to find the right RPMFusion thing for Fedora32?

**Comment by namandixit** [comment]
@freemin7 Run this command ([source](https://rpmfusion.org/Configuration)):

    sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

**Comment by ProjectSynchro** [comment]
This issue should probably be re-opened due to this incoming change to Fedora 43: https://fedoraproject.org/wiki/Changes/dropingOfCertPemFile

Currently in Fedora Rawhide: The Steam client and the bootstrapper cannot connect due to missing certificate bundles. Downgrading the ca-certificates package to 2024.2.69_v8.0.401-5 works around the issue.

I'm not quite sure if this is something that needs to be addressed on Valve's end or if there is some way to work around this via the RPMFusion package

**Comment by JM1** [comment]
@ProjectSynchro: steamcmd failed for the very same reason on Fedora Rawhide. Thank you for the hint to the root cause!

This issue should definitely be reopened. Or should a new bug be created? Wdyt, @namandixit?

Another workaround besides downgrading ca-certificates is to run `update-ca-trust extract --rhbz2387674`.

**Comment by JM1** [comment]
For completeness, the full log for Fedora Rawhide is:

```
+ ./steamcmd.sh +force_install_dir /home/XYZ/Steam/_games/cs2-ds +login anonymous +app_update 730 validate +quit
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/XYZ/Steam/logs/stderr.txt'
Logging directory: '/home/XYZ/Steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
src/common/opensslconnection.cpp (1636) : unable to load trusted SSL root certificates
assert_20250822193024_4.dmp[12]: Uploading dump (out-of-process)
/tmp/dumps/assert_20250822193024_4.dmp

assert_20250822193024_4.dmp[12]: Finished uploading minidump (out-of-process): success = no

assert_20250822193024_4.dmp[12]: error: libcurl.so: cannot open shared object file: No such file or directory

assert_20250822193024_4.dmp[12]: file ''/tmp/dumps/assert_20250822193024_4.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logo
Steam Console Client (c) Valve Corporation - version 1747702063
-- type 'quit' to exit --
Loading Steam API...src/common/opensslconnection.cpp (1636) : unable to load trusted SSL root certificates
assert_20250822193024_17.dmp[25]: Uploading dump (out-of-process)
/tmp/dumps/assert_20250822193024_17.dmp

assert_20250822193024_17.dmp[25]: Finished uploading minidump (out-of-process): success = no

assert_20250822193024_17.dmp[25]: error: libcurl.so: cannot open shared object file: No such file or directory

assert_20250822193024_17.dmp[25]: file ''/tmp/dumps/assert_20250822193024_17.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

IPC function call IClientUtils::GetSteamRealm took too long: 90 msec
OK
```
