### ISSUE TITLE
Half life cant reload gun

### ISSUE THREAD

**Issue by nitrochan531** [ValveSoftware/steam-for-linux#6750]
#### Your system information

* Steam client version 
* Distribution: Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

I cant reload my gun in half life making it pretty much unplayable. I have tried using the back up button i have tried remapping the keys i have tried both at the same time i cant reload my gun

#### Steps for reproducing this issue:

1. It just happens every time i open the game
2. 
3.

**Comment by kisak-valve** [comment]
Hello @nitrochan531, your previous issue report was transferred to https://github.com/ValveSoftware/halflife/issues/2800 because you described an issue with the game instead of the Steam client. Closing as a duplicate.
