### ISSUE TITLE
Bluetooth devices (Xbox One S controller) not pairing correctly via SteamOS bluetooth settings

### ISSUE THREAD

**Issue by alkazar** [ValveSoftware/steam-for-linux#6756]
#### Your system information

* Steam client version (build number or date): build date: Dec 6, 2019 at 03:34:28 / version: 1575605714
* Distribution (e.g. Ubuntu): Arch Linux (up to date as of this posting)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes (there were no further updates available at time of posting)

#### Steps for reproducing this issue:

1. as root, run `echo 1 > /sys/module/bluetooth/parameters/disable_ertm` to allow pairing of Xbox One S controller
2. run steam using `-steamos -tenfoot` options to enable Bluetooth settings in Big Picture mode
3. go to the bluetooth settings and pair an Xbox One S controller
4. turn the controller off
5. turn the controller on

Expected result:
the controller should connect and be usable

Actual result:
the controller does not connect and acts as if it is unpaired; trying to pair it again in the bluetooth configuration screen is unsuccessful. I have to run the `remove` command in `bluetoothctl` before I can re-pair the device from the Steam big picture UI.

Additional notes:
 - I was able to successfully achieve the expected result above by using `bluetoothctl` from the command line and following the connection instructions here (without actually installing the xpad neo driver): https://atar-axis.github.io/xpadneo/#connection
 - I hypothesized that the Steam big picture bluetooth configuration page was not doing the `trust` step. I tested this idea by again following the `bluetoothctl` instructions linked above, but skipping the `trust` command. This resulted in the same failure as the Steam big picture configuration page. Therefore it is very likely the case that the Steam big picture bluetooth configuration page is not doing a crucial step to allow bluetooth devices to be trusted. As a result, devices are not able to reconnect after being disconnected and users must drop to the command line and use `bluetoothctl` to be able to re-connect the devices again.

**Comment by 200Puls** [comment]
I just encountered this bug with the Xbox One Controller. It basically renders the bluetooth ui useless and forces manually pairing the controllers.

**Comment by buxel** [comment]
Confirmed on Manjaro with steam build from Jun. 4 2020

**Comment by leocodeninja** [comment]
I have the same problem with Switch Pro controller. It connects to the controller but I cant move around in the steam UI. 

Can you update gameros to automatically trust all bluetooth connections?

**Comment by thurstylark** [comment]
Same for DS4 controllers.

**Comment by alkazar** [comment]
I finally found a fix, you just need to set `AlwaysPairable = true` in `/etc/bluetooth/main.conf` under the `[General]` section.

I suppose this is outside the scope of Steam, so I am closing this issue.

**Comment by leocodeninja** [comment]
Took you long enough

Regards,
Leo
253-213-8585
