### ISSUE TITLE
Gamepads work in BPM, not in games (only right stick shows in HUD)

### ISSUE THREAD

**Issue by slavoslav** [ValveSoftware/steam-for-linux#6758]
#### Your system information

* Steam client version (build number or date): Dec 6, 2019
* Distribution (e.g. Ubuntu): Funtoo Linux (using steam's flatpak image from flathub)
* Opted into Steam client beta?: Yes (stable is problematic too)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I have two gamepads: DualShock 4 and a generic PC gamepad. Both work great in Big Picture mode (the menus) but games just don't respond to gamepad input.

I can press the guide button on my DS4 to open the Steam overlay when in-game, everything still works there.

If I enable the controller HUD, then only the right stick shows up on screen. I couldn't verify that the game recognized its movement.

The issue is present with both native games and the games that are run with Proton.

I don't know what logs to check, any help would be appreciated.

#### Steps for reproducing this issue:

1. Plug a gamepad in
2. Run Steam
3. Launch a game

**Comment by kisak-valve** [comment]
Hello @slavoslav, can you check if your desktop user is part of the `input` group? (from #5849)

**Comment by slavoslav** [comment]
Hello, my user on the host system is in that group. root and the user inside the flatpak container aren't.

**Comment by slavoslav** [comment]
I guess I should also add:
* both gamepads are connected to my PC with USB, 
* after the gamepad is noticed by Steam, the /dev/input/js0 file is gone.

Oh, I have just now noticed this line in the steam startup log.
```
Couldn't initialize virtual gamepad: Couldn't open /dev/uinput for writing
```

**Comment by slavoslav** [comment]
Ok, so the issue was that the uinput module wasn't loaded. After I loaded it and set some permissions, everything worked, although the HUD still only shows the right stick for some reason.

Sorry for wasting your time and thanks for rubber ducking, hopefully someone will find this issue helpful.
