### ISSUE TITLE
error on installing steam client for linux(Ubuntu 14.04)

### ISSUE THREAD

**Issue by Torinous** [ValveSoftware/steam-for-linux#6759]
#### Your system information

* Steam client version (build number or date): latest for linux
* Distribution (e.g. Ubuntu): Ubuntu 14.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. trying to install latest Steam client
**result**:<script src="https://gist.github.com/Torinous/e57f6f0189bcbe049026a7cbf545449e.js"></script>

sudo apt install steam
[sudo] пароль для torinous:
Чтение списков пакетов… Готово
Построение дерева зависимостей      
Чтение информации о состоянии… Готово
Возможно, для исправления этих ошибок вы захотите воспользоваться «apt --fix-broken install».
Следующие пакеты имеют неудовлетворённые зависимости:
 libgl1 : Зависит: libglvnd0 (= 1.0.0-2ubuntu2.3) но 1.0.0-2ubuntu2.2 должен быть установлен
          Зависит: libglx0 (= 1.0.0-2ubuntu2.3) но 1.0.0-2ubuntu2.2 должен быть установлен
 steam:i386 : Зависит: libc6:i386 (>= 2.15) но он не будет установлен
              Зависит: libstdc++6:i386 (>= 4.3) но он не будет установлен
              Зависит: libx11-6:i386 но он не будет установлен
              Зависит: libudev1:i386 но он не будет установлен
              Зависит: libxinerama1:i386 но он не будет установлен
              Зависит: libgl1-mesa-dri:i386 (>= 17.3) но он не будет установлен или
                              libtxc-dxtn0:i386 но он не может быть установлен
              Зависит: libgl1-mesa-dri:i386 но он не будет установлен
              Зависит: libgl1-mesa-glx:i386 но он не будет установлен
              Зависит: libgpg-error0:i386 но он не будет установлен
              Рекомендует: libxss1:i386 но он не будет установлен
              Рекомендует: nvidia-driver-libs-i386:i386 но он не может быть установлен
 systemd : Зависит: libsystemd0 (= 237-3ubuntu10.31) но 237-3ubuntu10.29 должен быть установлен
E: Неудовлетворённые зависимости. Попытайтесь выполнить «apt --fix-broken install», не указывая имени пакета (или указав решение).

**Comment by kisak-valve** [comment]
Hello @Torinous, upstream support for Ubuntu 14.04 has ended, and by extension isn't supported here as well.

That set aside, Steam needs 32 bit libc6 and a working 32 bit opengl driver stack to be provided by the host system and the package manager is trying to tell you something isn't quite right and is stopping those packages from being added.
