### ISSUE TITLE
Cover images become blurry on mouseover

### ISSUE THREAD

**Issue by CKWarner** [ValveSoftware/steam-for-linux#6760]
#### Your system information

* Steam client version (build number or date): Dec 6 2019 at 03:31:00
* Distribution (e.g. Ubuntu): Kubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Mousing over the cover art causes the selected cover art to expand in order to focus the user's attention on it. Unfortunately, the provided artwork and text are only rendered at the smaller size. This zoom effect simply makes both artwork and text blurry.

Ideally, images should be available at both sizes, and the text should be rendered new at the larger size. As an alternative, both should be done at the larger size and scaled smaller for the smaller view.

#### Steps for reproducing this issue:

1. Mouseover any cover in the Library
2. The artwork becomes zoomed
3. Observe how blurry it is

**Comment by kisak-valve** [comment]
Hello @CKWarner, this functionally the same issue as #6596. Closing in favor of the existing issue report.
