### ISSUE TITLE
Crash on startup ubuntu 18.04

### ISSUE THREAD

**Issue by anandijain** [ValveSoftware/steam-for-linux#6761]
#### Your system information

* Steam client version (build number or date): 1575604565
* Distribution: Ubuntu
* Opted into Steam client beta?: [Yes/No] Not sure (I think not)
* Have you checked for system updates?: [Yes/No] 

#### Please describe your issue in as much detail as possible:
Started steam, it started updating then did not open.
```$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/sippycups/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1575604565)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1575604565)
Installing breakpad exception handler for appid(steam)/version(1575604565)
Gtk-Message: 05:10:30.306: Failed to load module "gail"
Gtk-Message: 05:10:30.307: Failed to load module "atk-bridge"

(steam:30883): Gtk-WARNING **: 05:10:30.314: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita-dark/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:30883): Gtk-WARNING **: 05:10:30.315: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Adwaita-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  154
Serial number of failed request:  47
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  46
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  48
xerror_handler: X failed, continuing
assert_20191211051029_1.dmp[30898]: Uploading dump (out-of-process)
/tmp/dumps/assert_20191211051029_1.dmp
/home/sippycups/.local/share/Steam/steam.sh: line 722: 30883 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20191211051029_1.dmp[30898]: Finished uploading minidump (out-of-process): success = yes
assert_20191211051029_1.dmp[30898]: response: CrashID=bp-f203011d-deb1-4bf8-89f3-f618a2191211
assert_20191211051029_1.dmp[30898]: file ''/tmp/dumps/assert_20191211051029_1.dmp'', upload yes: ''CrashID=bp-f203011d-deb1-4bf8-89f3-f618a2191211''
```
#### Steps for reproducing this issue:

1. not sure if this is reproducible as it looks like theres a bug in the gtk theme?

**Comment by kisak-valve** [comment]
Hello @anandijain, swrast is mesa's slower software renderer. The fact Steam is trying to use it and failing hints that you're using the nvidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you verify this is the case and check video driver version you're using? You should be able to install the 32 bit userspace support with something like `sudo apt install libnvidia-gl-435:i386` (change 435 to match the version that is installed).

**Comment by anandijain** [comment]
Thanks for the quick reply, this was my suspicion last night, but I was hesitant because my OS is 64bit.

Does installing this userspace alter my 64 bit install for use in things like tensorflow? (for my python install)

I didn't post this earlier but this is my GPU specs:
```
NVIDIA-SMI 440.33.01
Driver Version: 440.33.01
CUDA Version: 10.2
GeForce GTX 970
```

Thank you again

**Comment by anandijain** [comment]
To confirm: it did remove my other version, however steam is opening again!

Thanks

**Comment by kisak-valve** [comment]
You've encountered the nVidia issue being tracked at #5778. A shortened assessment at https://github.com/ValveSoftware/steam-for-linux/issues/6753#issuecomment-562982487 may be worth reading.

**Comment by j-o-d-o** [comment]
@anandijain how did you install the 32bit userspace? Because `sudo apt install libnvidia-gl-440:i386` does not exist.

**Comment by Alex-Linhares** [comment]
The easiest solution to this, at least for me, was installing the flatpak version of steam and not touching drivers/cuda.

**Comment by anandijain** [comment]
@j-o-d-o I think I installed an older version, luckily it seems 440 is out now

**Comment by y9luiz** [comment]
using
```
sudo apt install libnvidia-gl-435:i386
```
will remove my cuda, and i could not do it, exists another solution?
