### ISSUE TITLE
Steam crashes on launch on Ubuntu 18.04

### ISSUE THREAD

**Issue by lxs602** [ValveSoftware/steam-for-linux#6764]
#### Your system information

* Steam client version (build number or date): 1575604565
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes immediately after logging in, on 'Configuring Steam account: <username>...'

I am happy to submit any other crash/log files as needed.

#### Steps for reproducing this issue:
1. /usr/games/steam

Crash dump files:
[luke_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3962898/luke_log.txt)
[crash_20191213220830_20.zip](https://github.com/ValveSoftware/steam-for-linux/files/3962899/crash_20191213220830_20.zip)
 
Stdout:
```Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/luke/.steam/ubuntu12_32/steam
[2019-12-13 22:13:19] Startup - updater built Dec  6 2019 03:24:55
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-12-13 22:13:20] Checking for update on startup
[2019-12-13 22:13:20] Checking for available updates...
[2019-12-13 22:13:20] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-12-13 22:13:20] Download skipped: /client/steam_client_ubuntu12 version 1575604565, installed version 1575604565
[2019-12-13 22:13:20] Nothing to do
[2019-12-13 22:13:20] Verifying installation...
[2019-12-13 22:13:20] Performing checksum verification of executable files
[2019-12-13 22:13:21] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
Opted-in Controller Mask for AppId 0: 0
roaming config store loaded successfully - 1885 bytes.
migrating temporary roaming config store
appdatacache.cpp (2433) : Assertion Failed: !bSharedKVSymbols```

**Comment by kisak-valve** [comment]
Hello @lxs602, this reads like #6067. Does moving `~/.steam` somewhere out of the way so Steam can re-bootstrap on next start have an effect?

**Comment by lxs602** [comment]
Hi, deleting .steam has no effect.  I installed Ubuntu 18.04 on a virtual drive, downloaded all updates, and then installed Steam, which then started without problems, so I wonder if I have somehow compromised compatibility with Steam by installing software from ppas. I will try a fresh install to Ubuntu 19.10 and reinstall Steam, unless you have any better suggestions. Thanks.

**Comment by lxs602** [comment]
Fixed by reinstalling Ubuntu.
