### ISSUE TITLE
CS GO: VAC complains about file integrity

### ISSUE THREAD

**Issue by klstilling** [ValveSoftware/steam-for-linux#6766]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.61-3
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expected to play the game without getting disconnected, but I get disconnected near the end of a match with VAC complaining about client problems. I checked all the files, I tried reinstalling steam and CSGO, but it did not fix the problem. I tried moving the CS installation from one disk drive to another. SMART shows no problems with any of my disks.

#### Steps for reproducing this issue:

1. Verify integrity, typically finds 1 file failed to validate
2. Check again, 0 files found.
3. Play game, around the end of a match I get disconnected with VAC error

**Comment by kisak-valve** [comment]
Hello @klstilling, we're tracking issues with CS:GO in the [CS:GO](https://github.com/ValveSoftware/csgo-osx-linux/) issue tracker and this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2086, closing as a duplicate.
