### ISSUE TITLE
Primary featur of clipboard no longer copys selected text.

### ISSUE THREAD

**Issue by bjwest** [ValveSoftware/steam-for-linux#6772]
#### Your system information

* Steam client version (build number or date): Dec 12 2019, at 22:37:09
* Distribution (e.g. Ubuntu): KDE Neon (Ubuntu based) using official PPA.
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When text is selected (highlighted), it should be moved into the Primary clipboard and be ready to be pasted via middle click on the mouse.  In the Steam client, the selected text is not pasted when the middle mouse button is later clicked in another window.  This happens anywhere text can be selected within the client including the Community posts and System Information dialog (the text in the About Steam dialog cannot be selected at all) . 

#### Steps for reproducing this issue:

1. Select (highlight) text in client window
2. Move cursor anywhere text can be pasted like a different window or even the search bar in the Steam client.
3. Middle click and notice either nothing is pasted or, if there were data from a previous operation present, it is pasted into the location instead of text selected within the Steam client.

I can't say exactly when this started occurring because I don't often select text from the Steam client, but I know it was working a couple or three updates ago.  Pasting from the Primary into the Steam client does still work, however.

**Comment by kisak-valve** [comment]
Hello @bjwest, this issue is already being tracked at #175. Closing in favor of the existing issue report.
