### ISSUE TITLE
steam doesn't open after kernel update on fedora?

### ISSUE THREAD

**Issue by boistordu** [ValveSoftware/steam-for-linux#6774]
#### Your system information

* Steam client version (build number or date): 17 decembre 2019 
according to appinfo log `Download skipped: /client/steam_client_ubuntu12 version 1576550254, installed version 1576550254`
* Distribution (e.g. Ubuntu): fedora 31 `5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

that's the output in a terminal
```
steam
Running Steam on fedora 31 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/vigilian/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1576550254)
```

#### Steps for reproducing this issue:

1. put fedora 31 up to date with 5.3.16 kernel
2. reboot
3. stema doesn't start anymore

**Comment by kisak-valve** [comment]
Hello @boistordu, can you check if any 32 bit opengl application like `glxinfo32` works? A common scenario where this happens is when an nVidia proprietary driver user updates their system and the running kernel module version does not match the userspace version. In that situation, all OpenGL applications can get stuck waiting on the video driver.

**Comment by boistordu** [comment]
glxgears works perfectly
I only have glxinfo and glxinfo64
that's the beginning of glxinfo command:
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_libglvnd, 
    GLX_EXT_stereo_tree, GLX_EXT_swap_control, GLX_EXT_swap_control_tear, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_NV_copy_image, GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multigpu_context, GLX_NV_robustness_video_memory_purge, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control, 
    GLX_SGI_video_sync
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_stereo_tree, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_copy_buffer, 
    GLX_NV_copy_image, GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multigpu_context, GLX_NV_multisample_coverage, 
    GLX_NV_robustness_video_memory_purge, GLX_NV_swap_group, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control, 
    GLX_SGI_video_sync
```
I don't find any glxgears32 in the repos.
I can't reinstall the nvidia proprietary if you want. There is a new version if I remember correctly. 
But I can see that the usual mods are loaded:
```
$ lsmod | grep nv
nvidia_drm             53248  10
nvidia_modeset       1118208  21 nvidia_drm
nvidia              19984384  1083 nvidia_modeset
drm_kms_helper        212992  1 nvidia_drm
drm                   512000  13 drm_kms_helper,nvidia_drm
ipmi_msghandler        73728  2 ipmi_devintf,nvidia
```

**Comment by boistordu** [comment]
just to be complete:
```
$ inxi -GS
System:    Host: fedo-mansion-ada Kernel: 5.3.16-300.fc31.x86_64 x86_64 bits: 64 Desktop: Gnome 3.34.2 
           Distro: Fedora release 31 (Thirty One) 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 440.36 
           Display: x11 server: Fedora Project X.org 1.20.6 driver: nvidia resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 440.36 

```

**Comment by kisak-valve** [comment]
`glxinfo32` should be provided by the `glx-utils.i686` package. Regardless, can you check if `xorg-x11-drv-nvidia-libs.i686` is up to date and matches the kernel module and 64 bit userspace version? It looks like RPM Fusion bumped to 440.44.

**Comment by boistordu** [comment]
```
Last metadata expiration check: 2:49:54 ago on Tue 17 Dec 2019 09:18:12 PM CET.
No match for argument: glx-utils.i686
Error: Unable to find a match: glx-utils.i686
```
I install my drivers manually. 

```
$ sudo dnf install xorg-x11-drv-nvidia-libs.i686
Last metadata expiration check: 2:51:14 ago on Tue 17 Dec 2019 09:18:12 PM CET.
Package xorg-x11-drv-nvidia-libs-3:440.44-1.fc31.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by kisak-valve** [comment]
Well, at least that does tell us the running system is using nVidia 440.36 and the 32 bit userspace is 440.44. The driver version must match between the kernel module, the 64 bit userspace, and 32 bit userspace or this scenario happens.

**Comment by boistordu** [comment]
yup sorry I didn't catch it before. 
Just updated to 440.44 and it works. I didn't know that the releave of nvidia drivers were so in sync with the kernels. 
Thanks again and sorry for the disturbance.
