### ISSUE TITLE
Deepin Linux

### ISSUE THREAD

**Issue by AlexMayne5** [ValveSoftware/steam-for-linux#6775]
#### Your system information

* Steam client version:1.0.0.61-2deepin 
* Distribution:deepin 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
comes up with message image linked

#### Steps for reproducing this issue:

1. install deepin
2. install steam with download from steam website 
3. open steam
![2019-12-17_22-41_1](https://user-images.githubusercontent.com/46424598/71040424-75f5cd00-211e-11ea-8c02-653fbf324044.png)
![2019-12-17_22-41](https://user-images.githubusercontent.com/46424598/71040425-75f5cd00-211e-11ea-84e0-07bcdeb44ed1.png)

**Comment by AlexMayne5** [comment]
i am running a core i5 3.2 ghz, 16gb ram, 500gb ssd, amd Tahiti XT

**Comment by kisak-valve** [comment]
Hello @AlexMayne5, can you move/remove `~/.steam` and `~/.local/share/Steam` if it exists, then run Steam from a terminal and copy what it outputs to a [gist](https://gist.github.com)?

Also, if it exists, does `~/.steam/error.log` give any hints?

**Comment by AlexMayne5** [comment]
I tried your steps and it is now working thanks :)
