### ISSUE TITLE
SteamCMD? Report? Broken

### ISSUE THREAD

**Issue by Jonas18175** [ValveSoftware/steam-for-linux#6777]
I don't know where can i report bugs with steamcmd.

I have the common Problem of Timeout of UserInfo:

Redirecting stderr to '/opt/steam/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...threadtools.cpp (833) : Assertion Failed: ThreadGetProcessExitCode: no such process 14308
FAILED. Timed out.
OK

---

I had this problem on centos 7 - i tried everything and nothing works - but the next systemupdate get it running. Now I upgraded my system to Centos 8 and now steamcmd doesn't run anymore.

Here as reference to the other report:  https://github.com/FezVrasta/ark-server-tools/issues/1043

I have a fresh installed steamcmd.

**Comment by kisak-valve** [comment]
Hello @Jonas18175, sounds like you've encountered https://github.com/ValveSoftware/steam-for-linux/issues/6692#issuecomment-564661585. Closing as a duplicate.
