### ISSUE TITLE
Feature request: Check the sound server during startup

### ISSUE THREAD

**Issue by Tea23** [ValveSoftware/steam-for-linux#678]
At the moment, due to Ubuntu being the primary target, Steam + TF2 (and presumably all further Source games) also target PulseAudio. On my Arch system, it's necessary for me to export the `SDL_AUDIODRIVER`environment variable with the value 'alsa' when running Steam. To make this easier, I simply add `export SDL_AUDIODRIVER=alsa` to the top of `/usr/bin/steam`.

It should be fairly trivial to simply incorporate upstream, a check in the Steam script to find out what sound server the user is running and export `SDL_AUDIODRIVER` accordingly if necessary.

Admittedly, I'm not the best BASH monkey in the world so I'm not sure what the check would look like. I imagine, however, Pulse must set some kind of environment variable that we could simply check the existence of in an `if` statement, and export `SDL_AUDIODRIVER` if it doesn't, do nothing if it does. For OSS, I would imagine that the value of `alsa` in the variable might actually be sufficient if the user has ALSA emulation installed; I'm not sure if the variable would work if `oss` was chosen as the variable.

Ultimately I believe such a check - or indeed another solution or workaround - would help Steam get closer to true distro-agnosticism.

**Comment by kisak-valve** [comment]
SDL 2 has a list of preferred audio backends that it walks through. If it can not connect to a running pulseaudio instance, then it continues down the list and eventually tries alsa. If you need SDL 2 to support for an audio backend like JACK or OSSv4, you will need to make sure a system variant of the libraries used by the game(s) is available and is built with support for the backend you want to use.

NOTE: Most games have not been tested against less common audio backends and may have quirk behavior. Your mileage may vary.
