### ISSUE TITLE
Issues copying from address bar

### ISSUE THREAD

**Issue by darealshinji** [ValveSoftware/steam-for-linux#6782]
#### Your system information

* Steam client version (build number or date): Dec 16 2019
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Copying text from the client's address bar isn't working in perhaps 99% of all cases.

#### Steps for reproducing this issue:

1. Enable address bar in settings.
2. Go to a discussion, shop site, guide, etc.
3. Mark the address, right-click on it and copy.

**Comment by kisak-valve** [comment]
In a quick test:
Right click -> copy on the url = clipboard not updated
Click and drag over url -> right click -> copy = clipboard not updated
Double click on url -> right click -> copy = clipboard has url

**Comment by XakepSDK** [comment]
Also pasting is slow

**Comment by arrowgent** [comment]
often times CTRL+C does not copy from the URL.

**Comment by Managor** [comment]
@kisak-valve This can probably be closed as it relates to the old address bar.
I've made a bug report that relates to the new one https://github.com/ValveSoftware/steam-for-linux/issues/10647
