### ISSUE TITLE
Steam redraw issue

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#6783]
#### Your system information

* Steam client version (build number or date): 
![Screenshot_2019-12-22_11-08-47](https://user-images.githubusercontent.com/6024315/71325011-33c8e480-24ac-11ea-8093-e3fc58d282b7.png)
* Distribution (e.g. Ubuntu): Xubuntu 19.10
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
https://gist.github.com/nightsky30/e29fd06661e25d83fe4ae3aaf4c609e3

#### Please describe your issue in as much detail as possible:
There appear to be excessive redraw issues when on the Holiday Market page and then clicking on one of the items in the user's "inbox" menu like viewing new comments or inventory items.

![Screenshot_2019-12-22_11-02-56](https://user-images.githubusercontent.com/6024315/71325012-3deae300-24ac-11ea-9fd4-27714ab01773.png)

This doesn't happen when the Holiday Market page is being loaded, but rather after it has loaded and the user is leaving the market to access their inventory, etc.  Sometimes the redraw is less extensive, sometimes worse.  I've not yet encountered this anywhere else.

![XMcJo1s](https://user-images.githubusercontent.com/6024315/71325225-3ed14400-24af-11ea-94f0-bb2cca5dbd6f.gif)

![q9FCdb2](https://user-images.githubusercontent.com/6024315/71325229-45f85200-24af-11ea-8a4d-7f12899a0c62.gif)

#### Steps for reproducing this issue:

1. Go to the Holiday Market page
2. Leave the Holiday Market page by accessing an inbox item
3. Experience redraw issues

**Comment by kisak-valve** [comment]
Hello @nightsky30, out of mild curiosity, at Steam -> Settings -> Interface is `Enable GPU accelerated rendering in web views (requires restart)` checked and if it is, does switching it have an effect on this issue?

**Comment by nightsky30** [comment]
GPU Acceleration for rendering web views is currently disabled due to issues I am having with #6549, but I can enable it and retest.

**Comment by nightsky30** [comment]
Re-enabling GPU Acceleration for rendering web views does correct the issue.

I've also noted that the black windows issue _appears_ to be fixed in #6549 when running the latest beta and NVIDIA drivers.  I did everything I could think of to try and cause the bug to surface.

**Comment by Leopard1907** [comment]
@nightsky30 https://github.com/ValveSoftware/steam-for-linux/issues/6715

Be aware of this , Steam client can fill your vram very quickly after interacting a few steam windows , after resizing some windows etc and it is permanent. Won't go away until next reboot.

**Comment by Myrddin-Wyllt** [comment]
@Leopard1907 Closing Steam emptys my RX 480 VRAM; restarting Steam seems to be enough on my end.

**Comment by kisak-valve** [comment]
Hello @nightsky30, are you still experiencing this issue on an up to date system?

**Comment by nightsky30** [comment]
It doesn't appear so. I'm not generally having redraw issues any longer even with Re-enabling GPU Acceleration for rendering web views disabled. I did manage to get the featured store page to fail to load once after disabling the setting and restarting. It just didn't render anything until the window was resized. Can't reproduce it though.

![Screenshot_2022-05-21_14-54-18](https://user-images.githubusercontent.com/6024315/169667186-ee16f9ca-78cb-444c-94da-bd5e936771fc.png)
