### ISSUE TITLE
Opening GTA V properties crashes Steam

### ISSUE THREAD

**Issue by AWalton** [ValveSoftware/steam-for-linux#6785]
#### Your system information

* Steam client version (build number or date): Dec 16
* Distribution (e.g. Ubuntu): Kubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Can't adjust properties for GTA V. Output of `/tmp/dumps/` [here](https://github.com/AWalton/test1/blob/master/text.dmp) (I had difficulty uploading it as gist due to foreign characters I think).

#### Steps for reproducing this issue:

1. Right-click GTA V
2. Click Properties
3. Steam crashes

Possibly related to #6757

**Comment by kisak-valve** [comment]
Hello @AWalton, it looks like you've mangled a Breakpad format minidump, can you throw it in an archive and drag and drop it into the comment box?

**Comment by AWalton** [comment]
Hmm it won't let me upload tar or gz archives for some reason, but the file I linked above is accurate, it's just the first 770 lines which are foreign chars. 

After rebooting a few more times the problem seems to have fixed itself? Not sure why. Feel free to close it if there's not any other useful info for you here.

**Comment by kisak-valve** [comment]
Closing in favor of #6757.
