### ISSUE TITLE
After upgrading the NVIDIA driver to 440, Steam on Ubuntu 18.04 LTS failed to start.

### ISSUE THREAD

**Issue by leimao** [ValveSoftware/steam-for-linux#6789]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 18.04 LST
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After upgrading the NVIDIA driver to 440, Steam on Ubuntu 18.04 LTS failed to start.

**Comment by kisak-valve** [comment]
Hello @leimao, does any 32 bit OpenGL application like `glxinfo` from `mesa-utils:i386` work?

Please check if you have the `libnvidia-gl-440:i386` package installed with something like `apt policy libnvidia-gl-440:i386` and if it is missing, install it with `sudo apt install libnvidia-gl-440:i386`.

**Comment by leimao** [comment]
Thanks @kisak-valve .
`glxinfo` does not work on my device. 
```
$ glxinfo 
name of display: :1
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  54
  Current serial number in output stream:  53
```
Installing was `libnvidia-gl-440:i386` not successful neither.
```
$ sudo apt install libnvidia-gl-440:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libnvidia-gl-440:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libnvidia-common-440

E: Package 'libnvidia-gl-440:i386' has no installation candidate
```

**Comment by kisak-valve** [comment]
So, your issue is with your video driver install not providing 32 bit userspace support, and is not an issue on Steam's side. Swrast is mesa's slower software renderer and the fact glxinfo is trying to use it tells us the system is trying to use mesa's libGL.so with the nVidia proprietary driver, which is incompatible.

Can you describe how you installed your current video driver?

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa should provide everything needed for recent nVidia releases on your distro.

**Comment by leimao** [comment]
Thanks. I used to install NVIDIA driver (together with CUDA) according to the instruction https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork. It used to work well with Ubuntu Steam.

**Comment by kisak-valve** [comment]
The issue you've encountered is being tracked at #5778 and is a video driver packaging issue. You should be able to lock in a preferred video driver version from the Proprietary GPU drivers PPA, then add in the individual cuda packages that you want to use without using the CUDA meta-packaging in a method similar to https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-517509736.

Closing in favor of the older issue report.
