### ISSUE TITLE
Missing 32-bit libraries libGL.so.1 (kali linux)

### ISSUE THREAD

**Issue by koumakpet** [ValveSoftware/steam-for-linux#6790]
#### Your system information

* Steam client version (build number or date): **Latest, Downloaded from official Steam webpage**
* Distribution: **Linux kali 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

### More system information
* My CPU: **Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz**
* My GPU: **GeForce GTX 970M & Intel's integrated GPU: HD Graphics 530**
* Detailed system information: https://gist.github.com/koumakpet/f1d14f0594b0ed07ce74c08efc568e47
* I'm Dual Booting Kali Linux and Windows 10 (On Windows side, steam is working fine)

#### Please describe your issue in as much detail as possible:
I have installed Steam client on Linux, but when I tried to run it, it shows me an error:
You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
![image](https://user-images.githubusercontent.com/20902250/71448928-97078080-2711-11ea-91d4-f126628e9f5a.png)
![image](https://user-images.githubusercontent.com/20902250/71448932-a38bd900-2711-11ea-98b1-b9052785ee43.png)

Installation process output: https://gist.github.com/koumakpet/d0493d3b7e14c5bcd49da5770d7bd4ae

I ran command `ldd ~/.steam/root/ubuntu12_32/steamui.so ` as suggested on a steam discussion I found regarding this (posted by slouken)
the output was: https://gist.github.com/koumakpet/41323487a9066f3dab00178809ac8ac0.js

#### Steps for reproducing this issue:

1.  Install steam using the steam webpage package .deb
2. Wait for the installation to complete and run Steam Client
3. An error message appears as shown above

**Comment by kisak-valve** [comment]
Hello @koumakpet, Kali linux is not supported here because it's contradictory to the fundamental goals of the distribution, which focuses on security testing and is not intended to be used as a general purpose desktop environment.

That set aside, `Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1` in the log is trying to tell you to install 32 bit opengl driver support, which would be probably be something like `sudo apt install libgl1:i386 libgl1-mesa-dri:i386 nvidia-driver-libs-i386` to should pull in 32 bit variants of libglvnd, mesa for intel support, and nvidia driver support.

**Comment by ksanjeev284** [comment]
sudo apt install libgl1:i386 libgl1-mesa-dri:i386 nvidia-driver-libs-i386 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nvidia-driver-libs-i386:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by Vassopoli** [comment]
I just want to point out that kisak-valve solutions its almost correct. At least today, when i tried to install the packages, I saw that `nvidia-driver-libs-i386` doesn't exist, but I think that its supposed to be `nvidia-driver-libs:i386` instead. This can also solve your problem @ksanjeev284, i386 is like a tag, not part of the name

**Comment by aka69unkownn** [comment]
im getting this 
You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
please help me
