### ISSUE TITLE
Steam doesn't want to work/Doesn't go Online at all despite all of its attempts to display something (News etc.)

### ISSUE THREAD

**Issue by Max-Spec** [ValveSoftware/steam-for-linux#6791]
#### Your system information

* Steam client version (build number or date): Unsure where to check
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Up-To-Date

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I attempted to launch Steam, but it refuses to go online at any time at all. Every network-related things don't work on Steam at all.
https://gist.github.com/Max-Spec/72559b3a60771d105333f68bfc17af59
Here's what it says when I attempt to launch it.
#### Steps for reproducing this issue:

1. Just boot up Steam on Manjaro Linux.

**Comment by kisak-valve** [comment]
Hello @Max-Spec, can you check if running `LANG=en_US.UTF-8 steam` from an terminal has an effect?

If it does, please share the output of `locale -a`. (from #3125)

**Comment by Max-Spec** [comment]
Nope, it didn't do anything.
Here's the output of the console:
https://gist.github.com/Max-Spec/447b2657c7c7f4a027a561ea61ae6a56

**Comment by kisak-valve** [comment]
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
```
This is telling us that the OpenGL driver had a general failure.

Can you check if any 32 bit OpenGL application works like `glxinfo32` from `lib32-mesa-demos`?

What video card(s) / driver version are you using?

**Comment by Max-Spec** [comment]
I have integrated graphics card.
It's "Intel 4 Series Chipset" as it says.
The glxinfo32:
https://gist.github.com/Max-Spec/0f51a69657328644ca4c2ba06fcd8c86

**Comment by kisak-valve** [comment]
`Device: llvmpipe (LLVM 9.0, 128 bits) (0xffffffff)` is the key detail here, it tells us that you're using mesa's faster software renderer and not actually using your video card to accelerate OpenGL. That chipset is near the least capable hardware that should be able to run Steam, but there's no particular reason why it shouldn't work.

**Comment by Max-Spec** [comment]
What I mean by "Not working" is that it doesn't really want to go Online.
Sorry for the incovenience.

**Comment by Max-Spec** [comment]
One thing: https://i.redd.it/79p2zdih3y641.png
Unread messages thing appears despite the fact that Steam "isn't Online"

**Comment by Max-Spec** [comment]
Well, I still cannot really solve this one.
glxgears says this:
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  23
  Current serial number in output stream:  24

**Comment by Max-Spec** [comment]
Nevermind. The issue was nvidia drivers since it was probably trying to use something that my PC didn't have (NVIDIA graphics card etc.)
