### ISSUE TITLE
Unable to enter characters ÅÄÖ in Steam overlay when playing POSTAL 2 (223470)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6793]
#### Your system information

* Steam client version (build number or date): Dec 20 2019, at 23:41:30
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm unable to enter the characters å, ä, and ö while in the Steam overlay (both Steam chat and web browser) when playing POSTAL 2. I have yet to have this occur in any other game, and I'm able to enter these characters if I tab out of POSTAL 2.

#### Steps for reproducing this issue:

1. Use the `se`/Swedish keyboard layout
2. Start POSTAL 2 via Steam
3. Attempt to enter characters å, ä, and ö into text fields (such as the Steam chat)

**Comment by kisak-valve** [comment]
Hello @Newbytee, this issue is already being tracked at #2122. Closing as a duplicate.
