### ISSUE TITLE
Steam client inhibits the screensaver and sleep (#5532 regression)

### ISSUE THREAD

**Issue by cypher0n3** [ValveSoftware/steam-for-linux#6794]
#### Your system information

* Steam client version (build number or date): Dec 20 2019, at 23:41:30
* Distribution (e.g. Ubuntu): Arch Linux with KDE/Plasma5 (non-wayland)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When the Steam client is running, but no games are being played, Steam will still inhibit power management:
```
# From journalctl:
Dec 28 12:31:29 cypherArchDsk org_kde_powerdevil[1411]: powerdevil: Scheduling inhibition from ":1.16" "My SDL application" with cookie 25 and reason "Playing a game"
```

This occurs even if the system has been cleanly rebooted and no games have been played since.

This appears to be a regression of #5532 

#### Steps for reproducing this issue:

1. Start the Steam client
2. Check `journalctl` for indications that power management is inhibited (`powerdevil` messages in this case)
3. Sleep, screensaver, and other power management features are non-functional.

**Comment by kisak-valve** [comment]
Hello @cypher0n3, this issue is already being tracked at #5607. Closing as a duplicate.
