### ISSUE TITLE
No webviews render; steamwebhelper apparently keeps crashing

### ISSUE THREAD

**Issue by MerkaST** [ValveSoftware/steam-for-linux#6795]
#### Your system information

* Steam client version (build number or date): Dec 16 2019
* Distribution (e.g. Ubuntu): Lubuntu 18.04
* System information: [here](https://gist.github.com/MerkaST/4f2733964718b5164c1f5346b9af0227) 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
After updating to a version of Steam that includes the new UI, none of the interfaces using a webview work anymore and just show a black screen (this includes store, library, community, and user sites. The friends window doesn't appear at all when attempted to open). Webviews have always been spotty on this system, but now they seem to be entirely nonfunctional. Small mode and big picture mode do work and allow working around the issue, although the web browser in big picture mode also appears to not be working. The in-game overlay browser doesn't work, either.
The commandline gets spammed with repeated crashes from steamwebhelper like `/home/username/.local/share/Steam/ubuntu12_64/steamwebhelper.sh: line 23:  4427 Illegal instruction     (core dumped) ./steamwebhelper "$@"`.
The behaviour is identical whether or not the steam runtime is enabled, but steam doesn't launch at all with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`. See the logs in [this gist](https://gist.github.com/MerkaST/081baa8ea454330bc8552a852ab62ad0).

**Expected result:** All webviews load and are usable, the friends window opens and is usable.

**Actual result:** Webviews are blank, friends window doesn't work.

I have reinstalled Steam and tried oibaf mesa-git drivers, both to no avail.

#### Steps for reproducing this issue:

1. Start Steam
2. Open library in Large Mode and/or open store/community/user page
3. Observe blank screen

**Comment by kisak-valve** [comment]
Hello @MerkaST, your CPU does not support CMPXCHG16B, so you've encountered #4196.

Closing in favor of the existing issue report.
