### ISSUE TITLE
Stop steamwebhelper.sh from getting overwritten

### ISSUE THREAD

**Issue by anohren** [ValveSoftware/steam-for-linux#6797]
I need to know how to prevent steamwebhelper.sh from getting overwritten everytime I launch Steam, because it overwrites my workaround for #6603.

**Comment by kisak-valve** [comment]
Hello @anohren, defeating Steam's general sanity checks can not be supported.

That set aside, you may have some luck setting the immutable attribute on the script with `chattr +i`.

**Comment by anohren** [comment]
Hello @kisak-valve, nice of you to reply so quickly.

> Hello @anohren, defeating Steam's general sanity checks can not be supported.

It's been noted. Although I can't say after being referred to Github for support by Steam Support and receiving an overwhelming zero replies to an issue even after having isolated the problematic component, that I consider any other parts supported either.

> That set aside, you may have some luck setting the immutable attribute on the script with `chattr +i`.

Thank you, that seems to work! Good call.

**Comment by anohren** [comment]
Actually, now Steam is just wasting lots of time doing nothing whenever I try to launch a game. 

Doesn't work -- no support. Can't do much other than to write steam off as unusable on linux.
