### ISSUE TITLE
Library becomes highlighted to whatever games are clicked

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6798]
#### Your system information

* Steam client version (build number or date): Dec 20 2019
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

I'm not entirely sure what triggers this bug, but it has happened in multiple scenerios. From uninstalling a game, changing a games properties, opening Steam settings, even for no reason at all.

This is been happening ever since I've used Steam on Linux, and have finally found some time to document this and post a xwininfo log and video of it.

When clicking a game, clicking another one will highlight all games leading up to its point. Its better explained in the video.

https://www.youtube.com/watch?v=RQL0_DGdapc

xwininfo log:
[steamlibrarybug.txt](https://github.com/ValveSoftware/steam-for-linux/files/4007761/steamlibrarybug.txt)

#### Steps for reproducing this issue:

1. Scenerios mentioned above

**Comment by shoober420** [comment]
Here is the video.

https://www.youtube.com/watch?v=RQL0_DGdapc

**Comment by arrowgent** [comment]
pressing SHIFT fixes this, sometimes

rarely the library becomes unresponsive and will not work
click, tab away, click, tab away, click, tab away
does work

why this regression?

**Comment by kisak-valve** [comment]
Hello @shoober420, this issue is already being tracked at #3451. Closing as a duplicate.
