### ISSUE TITLE
Right click on system information window does nothing in plasma

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6799]
#### Your system information

* Steam client version : Dec 20 2019 
* Distribution : Arch Linux
* DE: KDE Plasma
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Right click on system information window does nothing in plasma but in gnome there is copy all to clipboard and etc

#### Steps for reproducing this issue:

1. Steam > Help > System Information
2. Click right
3. Nothing happens

**Comment by kisak-valve** [comment]
Hello @barfin, this reads like #4531. Can you check if https://github.com/ValveSoftware/steam-for-linux/issues/4531#issuecomment-478146883 works around the issue?

**Comment by barfin** [comment]
> Hello @barfin, this reads like #4531. Can you check if [#4531 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/4531#issuecomment-478146883) works around the issue?

yes it did fix it and it's the same issue i think
please close the issue if you think you should

**Comment by kisak-valve** [comment]
Thanks for testing, closing in favor of the older issue report.
