### ISSUE TITLE
[proton] option to copy wineprefix after game is downloaded

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-for-linux#6805]
Option to copy wineprefix after game is downloaded, not after pressing play button, to make use of protontricks in lutris installers.

**Comment by kisak-valve** [comment]
Hello @soredake, supporting protontricks and lutris is outside the scope of this issue tracker.

This is a feature request to run a game without actually letting it run, which is a non-starter for any normal use case.

**Comment by soredake** [comment]
I realized that protonfixes exists.
