### ISSUE TITLE
Steam survey crashes client

### ISSUE THREAD

**Issue by MilesBHuff** [ValveSoftware/steam-for-linux#6807]
#### Your system information

* Steam client version (build number or date): 1576908998
* Distribution (e.g. Ubuntu): arch rolling 64-bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam crashes a second after the hardware survey appears.  This has resulted in Steam being completely unusable since the beginning of this new year.

I get the same result no matter the value of STEAM_RUNTIME.

Googling did not reveal anything useful for me to try, and there are no commandline arguments that tell Steam to not run the survey.

stdout/stderr:  https://gist.github.com/MilesBHuff/cce70f3f29248545af00ecbeb397aa98

#### Steps for reproducing this issue:

1. Open Steam

**Comment by MilesBHuff** [comment]
Seemingly-related issue: https://github.com/ValveSoftware/steam-for-linux/issues/5114

**Comment by ruany** [comment]
Got the same issue.

If you opt out of the survey (two clicks) quickly enough for it to not finish initializing, the client doesn't crash and the survey is disabled, until next time.

**Comment by MilesBHuff** [comment]
I figured that would be the case, but unfortunately mine will not allow me to interact with the dialogs while they're loading.

Thankfully, I can still play games if I launch them directly, via `steam steam://$GAMEID`.

**Comment by TTimo** [comment]
@ruany can you provide Help > System Information for your install (out of the current beta, with the 'Steam Linux Runtime Information' section). (doesn't sound like @MilesBHuff could provide his since he crashes on startup)

**Comment by MilesBHuff** [comment]
@TTimo I figured out that, when using `steam steam://$GAMEID`, Steam doesn't show the hardware survey, even after I close the game.  Since discovering this, I've been able to use Steam more-or-less normally again;  although it still of course crashes immediately if I try to start Steam the normal way.

Here is my System Information: https://gist.github.com/MilesBHuff/fcd67d908794db623543c9777f8484a2

**Comment by TTimo** [comment]
The system info reports that you have a lot of library errors in your steam runtime - are you using the steam runtime modified by Arch? If that's the case please switch to Valve's official runtime and try again.

**Comment by MilesBHuff** [comment]
I noticed that just before you replied, and regenerated the gist with `steam-runtime` instead of `steam-native`.  The crash happens with both, as I mentioned in my OP.

**Comment by ruany** [comment]
System info with Steam runtime (crash occurs in both native runtime and in Steam runtime):
https://gist.github.com/ruany/cb1a60ab28880ee60dd5d583eb96c0e3

FWIW the Steam survey has worked before, using the native runtime, but stopped working after an update. Currently not experiencing any other issues with the client besides the Steam survey crash.

Since it hasn't been mentioned yet, I get this error in kernel logs when the client crashes:
```steam[71762]: segfault at 0 ip 00000000f2e971ed sp 00000000ffb1fa80 error 4 in steamui.so[f2478000+1352000]```

**Comment by TTimo** [comment]
@ruany can you get a crash ID out of the stderr/stdout output? I got one for @MilesBHuff but I'd like to make sure it's the same crash.

It looks like this:

```
assert_20200103200500_1.dmp[60610]: Finished uploading minidump (out-of-process): success = yes
assert_20200103200500_1.dmp[60610]: response: CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103
assert_20200103200500_1.dmp[60610]: file ''/tmp/dumps/assert_20200103200500_1.dmp'', upload yes: ''CrashID=bp-289f5a6e-4f0f-486f-9cc4-8a23d2200103''
```

**Comment by ruany** [comment]
@TTimo Here:
```
Jan 05 06:10:43 desktop assert_20200105061023_1.dmp[49370]: file ''/tmp/dumps/assert_20200105061023_1.dmp'', upload yes: ''CrashID=bp-4ce241dd-f2fe-4373-9d5b-e3a242200104''
Jan 05 06:13:07 desktop crash_20200105061307_28.dmp[71110]: Uploading dump (out-of-process)
                                                            /tmp/dumps/crash_20200105061307_28.dmp
Jan 05 06:13:08 desktop assert_20200105061248_1.dmp[71129]: Uploading dump (out-of-process)
                                                            /tmp/dumps/assert_20200105061248_1.dmp
Jan 05 06:13:10 desktop crash_20200105061307_28.dmp[71110]: Finished uploading minidump (out-of-process): success = yes
Jan 05 06:13:10 desktop crash_20200105061307_28.dmp[71110]: file ''/tmp/dumps/crash_20200105061307_28.dmp'', upload yes: ''CrashID=bp-10054587-dd06-4c27-b08a-e27ec2200104''
Jan 05 06:13:10 desktop assert_20200105061248_1.dmp[71129]: Finished uploading minidump (out-of-process): success = yes
Jan 05 06:13:10 desktop assert_20200105061248_1.dmp[71129]: file ''/tmp/dumps/assert_20200105061248_1.dmp'', upload yes: ''CrashID=bp-74fa228d-22bc-4ec9-96f8-cd8bd2200104''
Jan 05 06:13:45 desktop assert_20200105061324_1.dmp[79457]: Uploading dump (out-of-process)
                                                            /tmp/dumps/assert_20200105061324_1.dmp
Jan 05 06:13:48 desktop assert_20200105061324_1.dmp[79457]: Finished uploading minidump (out-of-process): success = yes
```

**Comment by Urth** [comment]
```
assert_20200108020657_1.dmp[31580]: Finished uploading minidump (out-of-process): success = yes
assert_20200108020657_1.dmp[31580]: response: CrashID=bp-53b5f5eb-0fe2-41d7-8622-2ae662200107
assert_20200108020657_1.dmp[31580]: file ''/tmp/dumps/assert_20200108020657_1.dmp'', upload yes: ''CrashID=bp-53b5f5eb-0fe2-41d7-8622-2ae662200107''
```
I have the same crash on Gentoo Linux ~amd64.

As a workaround you can edit `~/.steam/steam/config/config.vdf` and replace the `SurveyDate` with a recent date so the survey doesn't show.

**Comment by TTimo** [comment]
Next Steam client beta (> Dec 20) will have a fix.

**Comment by kisak-valve** [comment]
Hello, per "Fix a crash while preparing the hardware survey" in the [2019-01-09](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1698353956261271592) Steam client beta update, please opt into Steam's beta client and retest.

**Comment by MilesBHuff** [comment]
Steam just updated and the survey works now.  Thank you for the timely turnaround!
