### ISSUE TITLE
The steam client always wakes up my monitor when I try to lock the screen or close it.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6808]
#### Your system information

* Steam client version (build number or date): latest version
* Distribution (e.g. Ubuntu): Manjaro Gnome
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I try to close or lock the screen, it is always waken up by Steam client.

#### Steps for reproducing this issue:

1. Try to lock the screen or close the screen.
2. The screen turn on immediately.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, this issue is already being tracked at #5607. Closing as a duplicate.
