### ISSUE TITLE
Eve Online Crash on Proton 4.11-11

### ISSUE THREAD

**Issue by z5d69** [ValveSoftware/steam-for-linux#6813]
#### Your system information

* Steam client version (build number or date): December 16, 2019 (runtime version 0.20191210.1)
* Distribution (e.g. Ubuntu): OpenSuse 15.1, 64-bit, all patches applied
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No]  Yes, please see above
* Proton Version v4.11-11

#### Please describe your issue in as much detail as possible:
When I try to run Eve Online, it won't start the game.  Typically it abends with a C++ error in wine (window opens with that).  Startup takes several minutes (which I thought was the way the game worked as I have ONLY steam on linux) even before the crashing started.  Either way, I'm unable to exit the game without completely shutting down display-manager and killing all processes for steam / proton.  
HOWEVER, when I run on 4.2-9 it all runs fine without any of the problems I see in 4.11-11.  
I'm fine with running on 4.2-9 for now but concerned that, after 4.2 is deprecated, I won't have any ability to run the game.  I have run into similar problems with Proton versions so I thought it was a good idea to submit an issue before 4.2 was retired.  

#### Steps for reproducing this issue:
With ONLY ONE character created (no idea if that matters for this as I'm new to the game).  

1. Select Proton 4.11-11 for running Eve Online.  
2. Hit Play
3. Hit Play on Eve startup window.  
4. experience C++ wine crash.

**Comment by kisak-valve** [comment]
Hello @z5d69, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1223#issuecomment-571192393.
