### ISSUE TITLE
Steam Remote Play plays sound on both the client and the host, when the "Play sound on host" option is disabled.

### ISSUE THREAD

**Issue by obedlink** [ValveSoftware/steam-for-linux#6814]
#### Your system information

* Steam client version: 1576550254 
* Distribution: KDE Neon 5.17 User Edition
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

"Steam Remote Play" plays sound on both the client and the host, when the "Play sound on host" option is disabled.

What I see is that unlike windows, Steam does not create a virtual audio device, Steam captures the game's audio from the main sound card. If I put mute on the PC, it is also silenced on the TV.

#### Steps for reproducing this issue:

1. whenever "Remote Play" is used, with the "Play sound on host" option enabled or disabled.

**Comment by kisak-valve** [comment]
Hello @obedlink, this issue is already being tracked at #6512. Your issue title is easier to read at a glance so I've copied it over.

Closing in favor of the existing issue report.
