### ISSUE TITLE
[Feature Request] Allow to configure for a specific GPU(s) per game

### ISSUE THREAD

**Issue by underlineGalaxy** [ValveSoftware/steam-for-linux#6821]
#### Your system information

Unnecessary

#### Please describe your issue in as much detail as possible:

It's an issue especially with AMD because they do not have a visual software like they do on windows. It's a hassle having to deal with the terminal on this issue and there's a lot of laptops that ship with a discrete and an integrated GPU, thus making this issue common.

What about people with multiple GPUs? What if you could change the behaviour of it per game even on those that don't support multiple GPUs?

I believe it would be a good idea to try this feature-set with AMD GPUs first since they have open source drivers.

#### Steps for reproducing this issue:

Unnecessary

**Comment by kisak-valve** [comment]
Hello @underlineGalaxy, you should be able to add `DRI_PRIME=1 %command%` or equivalent vulkan-related env variable to the game's launch options to tell mesa to use the secondary gpu for an individual game.

**Comment by underlineGalaxy** [comment]
So it already exists! That's good.

I think for the next step make it more user friendly. Like have an advanced options and show all these optional toggles. Launch options is less hassle than terminal, but still a hassle for non-tech savvy users. (Could save a few google searches there).

**Comment by kisak-valve** [comment]
Like #4041, this is functionally the same feature request as #634. I've adjusted #634's title to more generally cover the topic.
