### ISSUE TITLE
Installing a non-game from Steam (such as Godot) from store page displays %game%

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6826]
#### Your system information

* Steam client version (build number or date): Jan 10 2020, at 22:11:51
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The prompt that appears when installing games from their store page should show the non-game's name like it does with games, but in the case of non-games it instead displays %game% in place of the non-game's name.

#### Steps for reproducing this issue:

1. Install a non-game from Steam (such as Godot) via its store page (not your library)
2. Observe a prompt saying "Preparing to launch %game%" appear briefly

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
