### ISSUE TITLE
Feature Request: Games should have "community fixes" like the community layouts for steam controller

### ISSUE THREAD

**Issue by underlineGalaxy** [ValveSoftware/steam-for-linux#6827]
For instance, take games like rocksmith, a game that requires external hardware and additional software requirements: there's just no way it will work out of the box without additional fixes and patches.

Why not let the community publish them, as to make it the out of the box experience steam is trying to make to their linux library? We also have to take into consideration steam machines 2.0 can have steamOS, thus linux.

Possible drawbacks with this:

People might use them for mods, even though there are places
Adult patches on Japanese games
It will most likely have no valve curation. Thus the possibility of having viruses from malicius people.

My suggestion is get a few trusted members to curate these patches, or maybe developer curation.

Maybe in the future expand this to windows users too, as to have community made features like more languages, more possible inputs, etc.

**Comment by kisak-valve** [comment]
Hello @underlineGalaxy, this feature request fully overlaps the existing Steam workshop support, which is already available at the game dev's discretion.
