### ISSUE TITLE
Proton Prefixes stay when a game will be moved to a different library

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#6830]
#### Your system information

* Steam client version (build number or date): 1578700296
* Distribution (e.g. Ubuntu): Linux Mint 19.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When Windows games get moved to a new library folder, with the Steam internal tools, the Proton Prefix won't be moved alltogether. This leads to a new Prefix in the new library folder.

#### Steps for reproducing this issue:

1. Install a game with Proton and launch it, so a Prefix will be created
2. Move the game with the Steam local files tools to a new library folder

**Comment by kisak-valve** [comment]
Possible duplicate of #5717.

**Comment by NoXPhasma** [comment]
It is, my search foo is not that good apparently. I will close this.
