### ISSUE TITLE
Steam now always starts minimized

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/steam-for-linux#6832]
* Steam client version: Jan 10 2020 at 22:11:51
* Distribution: Ubuntu 19.10 using the default Gnome Desktop Environment
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe issue in as much detail as possible:

Older versions of the Linux Steam Client would open a window on the system.

The current version only starts minimized. I can then right-click on the Steam icon in the task bar and select the window I wish to see, and it will _then_ appear.

But after stopping and restarting the Steam client, it will once again be minimized.

#### Steps for reproducing this issue:

On Ubuntu 19.10 with Steam client installed:
1. Press [Window]+[A] to see installed applications, find Steam, start it
2. Steam icon appears in task bar, but no window appears on screen
3. right-click Steam icon, choose Library
4. ta-da! Steam client window now appears
5. exit Steam client
6. repeat 1 - again the Steam client starts minimized

#### What I expected

I would want the Steam client to remember the window settings of the last time it had been started.

**Comment by kisak-valve** [comment]
Hello @hzulla, if you completely close Steam, then run `steam` from a terminal, does the client show or does it start minimized? It sounds like the shortcut you're using has been adjusted to call `steam -silent`, which would make the client give this behavior.

**Comment by hzulla** [comment]
Nope, if I run steam from the terminal, it still starts minimized. No client window.

**Comment by TriMoon** [comment]
> Nope, if I run steam from the terminal, it still starts minimized. No client window.

That's very weird because i would love it if that was the case....
On my system it still starts up with the window visible by default...
![Screenshot20200116_171114 neofetch](https://user-images.githubusercontent.com/1723378/72659290-74921b80-39ce-11ea-9287-4f60443375a0.png)

**Comment by Myrddin-Wyllt** [comment]
![image](https://user-images.githubusercontent.com/42914865/72825735-3189af80-3c3d-11ea-9722-6e43f341076b.png)

Set Steam to open the Library by default. When set to Friends, Steam can do this on both Windows & Linux.

The `-silent` launch option now works completely as a bonus; honestly this setting should be **exposed graphically** so everyone complaining about Steam stealing window focus are satiated.

**Comment by hzulla** [comment]
> Try setting Steam to open the Library by default.

That helped. I wonder why this setting got borked on my system, I didn't fiddle with it.
