### ISSUE TITLE
The default global Steam Play compatibility tool is Steam Linux Runtime 

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#6833]
#### Your system information

* Steam client version (build number or date): Jan 18 2020, at 03:34:03
* Distribution (e.g. Ubuntu): Fedora 31 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
By default, the global Steam Play compatibility tool is Steam Linux Runtime. This results in really poor UX for new users who go into settings and enable Steam Play for all titles thinking that will be enough to run their favourite Windows games in Steam but end up having all of them crash instantly without an explanation (I've helped a handful of people confused by why Proton isn't working with this being the reason why).

It also seems that this state is not meant to be accessible as I cannot select Steam Linux Runtime as my global compatibility tool in settings (it isn't in the list there), while I can do it with individual games. 

![steam-poor-ux](https://user-images.githubusercontent.com/4428753/72668026-9fa65a80-3a22-11ea-900a-a3d07cf2ed0a.png)
*Screenshot from freshly installed Steam*

#### Steps for reproducing this issue:

1. Perform a fresh install of Steam
2. Go into settings
3. Observe that the default compatibility tool is Steam Linux Runtime

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment]
> Hello @Newbytee, are you still experiencing this issue on an up to date system?

Haven't done a new installation of Steam for a while, but I'll pay attention to it next time I do. Might try in a VM. Any reason to believe it would have changed?

**Comment by kisak-valve** [comment]
At some point the Steam Linux Runtime stopped being listed as a global Steam Play option, and is only available in the per-game override if the game has a native Linux version available.

Closing as fixed.

**Comment by Newbytee** [comment]
@kisak-valve Looks like you forgot to close it, but I'll do it for you. I can confirm that on my end the default tool now is Proton Experimental.
