### ISSUE TITLE
Ubuntu 19.10 steam opens windows repeatedly and shows no content in windows

### ISSUE THREAD

**Issue by LeMoonStar** [ValveSoftware/steam-for-linux#6835]
#### Your system information

* Steam client version (build number or date): Dec 16 2019, at 16:49:05
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I recently updated from Ubuntu 18.04 to Ubuntu 19.04 ( where steam still runned as expected) and then to Ubuntu 19.10 where steam started to constantly try to reload the content of the libary and other tabs (or show nothing) and Repeatedly opens black windows. [here is a video](https://youtu.be/gXYO8_bVrWw). opening steam via the console outputs hundreds of error messages [Here is the output](https://gist.github.com/LeMoonStar/dec4a3a76d91a75d46fe1bbcca539dbb)

#### Steps for reproducing this issue:

since i haven't found anyone with the same issue i don't think it is possible to reproduce this simply.

1. update to 19.10
2. start steam

i'll happily provide any needed information.

**Comment by TriMoon** [comment]
I am using Kubuntu 19.10 and don't have the issue posted...

@LeMoonStar are you sure you are using the Linux native steam client and not the windows client?
Because the issue of "Window redraw" with black content is only in that version when run on linux using wine and the like...

**Comment by LeMoonStar** [comment]
i'am 100% sure this is the Linux version since I installed it via the .deb package.

**Comment by LeMoonStar** [comment]
i now also tried to purge the steam launcher and then reinstall it (i before just removed it, but not purged it) but that also didn't fix the problem.

**Comment by LeMoonStar** [comment]
The Problem has resolved since I needed to reinstall my Ubuntu (I broke it completely) and everything is working correctly now.

**Comment by kisak-valve** [comment]
Glad to hear you got it working, unfortunately, it also means there's also no test case as well. Closing per the last comment.
