### ISSUE TITLE
Streaming to steam link: audio failures

### ISSUE THREAD

**Issue by ajventer** [ValveSoftware/steam-for-linux#6836]
#### Your system information

* Steam client version (build number or date): Dec 16 2019 16:49:05
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I originally logged this issue with Steam Link support - they directed me here. 
The original request: https://help.steampowered.com/en/wizard/HelpRequest/HT-HYTD-CT79-V4D7
contains the serial number of the device and all relevant log files as well as the description below.

I use the steam link to play games from my PC.
I use Linux on my PC, and stream to the link over an ethernet connection. Initially when starting a game all works well but after 10-15 minutes sound will start cracking and then cut out entirely.
The sound on the PC is not disabled when streaming (I understand it is meant to be - so this may be related ?), and it continous to function just fine when this happens, only the streamed game sound fails.

I have tried every imaginable setting on the link to resolve this, including switching to fast mode and even tried playing at 720p instead of 1080p to no avail. I've undone every custom setting again since nothing worked.

I have tried both beta versions and stable for both the steam app and the link.

The problem appears to be worst with games that use steamplay/Proton but I can't confirm this beyond a subjective sense.

This affects every game I've tried to play. My PC sound system uses HDMI output (in case this matters).

**Comment by kisak-valve** [comment]
Hello @ajventer, this issue is already being tracked at #6749. Also, the secondary issue with the game always playing through the host's speakers is being tracked at #6512. Feel free to add your experience to these issue reports.

Closing as a duplicate.
