### ISSUE TITLE
[solved] glibc-2.30-10 causing Steam to fail to start

### ISSUE THREAD

**Issue by byte1024** [ValveSoftware/steam-for-linux#6838]
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] problem is part of today's updates

#### Steps for reproducing this issue:

1. Install system updates which include glibc-2.30-10 as offending package
2. Steam fails to start

(downgrade glibc and Steam starts again)

**Comment by kisak-valve** [comment]
Hello @byte1024, this should also be mentioned to Fedora's package maintainer for glibc.

**Comment by byte1024** [comment]
Will do.

Additional notes

Its possible for dnf to lose the old packages so that undo/rollback fails. Going to fedora updates site, manually downloading the old ones, then forcing rpm install of old packages may be required to get Steam working again as I'm sure others may run into this problem. Annoying but it works.

glibc-2.30-8 is the last version so its -9 or -10 that breaks Steam.

**Comment by byte1024** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1793609

**Comment by byte1024** [comment]
Separate install of Wine had libc.so.6 in /usr/lib/wine/ for some unknown reason (not there on fresh install of Wine) which conflicted with Steam and glibc-2.30-10.

Removed Wine, removed /usr/lib/wine, re-installed Wine, and both Steam and Wine exist. Steam now starts along with glibc-2.30-10.
