### ISSUE TITLE
Steam Client Inhibits Screensaver

### ISSUE THREAD

**Issue by adnieman** [ValveSoftware/steam-for-linux#6839]
#### Your system information

* Steam client version (build number or date):  Jan 18 2020, at 03:34:03
* Distribution (e.g. Ubuntu):  Ubuntu 18.04.3 XFCE 4.12.4
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam is sending DBus requests to inhibit power management. Only happens when Steam Client is running. 

Here is the DBus information:
method call time=1579622873.373382 sender=:1.917 -> destination=org.freedesktop.ScreenSaver serial=2 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.ScreenSaver; member=Inhibit

#### Steps for reproducing this issue:

1. run 'dbus-monitor --session'
2. Launch Steam Client
3.

**Comment by kisak-valve** [comment]
Hello @adnieman, this issue is already being tracked at #5607. Closing as a duplicate.
