### ISSUE TITLE
Steam updates and dies

### ISSUE THREAD

**Issue by waltermaldonado** [ValveSoftware/steam-for-linux#6841]
#### Your system information

* Steam client version (build number or date): 2020-01-22
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam updates but won't open. I have a GTX 1080 Ti and nvidia-driver-430.

![image](https://user-images.githubusercontent.com/8573950/72944728-8d952680-3d58-11ea-9b04-0afdf48d9019.png)

**Comment by kisak-valve** [comment]
Hello @waltermaldonado, swrast is mesa's slower cpu renderer. The fact that Steam is trying to use it indicates there's an issue with your 32 bit opengl driver stack. Does any 32 bit opengl application work like `glxinfo` from `mesa-utils:i386`?

Also, please check if `libnvidia-gl-430:i386` is installed with something like `apt policy libnvidia-gl-430:i386`.

**Comment by rileyweber13** [comment]
having this same issue after switching to an nvidia card. Specifically, I have the Geforce 1660, the driver for which (I'm using the nvidia-440 package, which I believe is driver version 440.33.1) does not have a 32 bit version. After installing drivers, if I try to install `libnvidia-gl:i386` (which should provide these libraries), `apt` informs me that it will need to remove the driver to do so, without providing a 32-bit alternative.

**Comment by kisak-valve** [comment]
Hello @rileyweber13, nvidia 440.33.01 is an nvidia CUDA driver version, so you've encountered #5778. Your best bet is to add https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa to your system for the 440 series then add the individual CUDA components you need without using the meta packaging from the CUDA installer.

**Comment by rileyweber13** [comment]
@kisak-valve thank you for your help. I'll checkout #5778 and see if I can find some help there. 

I installed with the ppa you linked, but afterwards installed CUDA adding the nvidia repository at  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ and then running sudo apt install cuda. 

Does this use the "cuda installer" that you mentioned?

**Comment by kisak-valve** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-575334890 describes it better than I have, the `cuda` package will most likely purge the 440.48.02 driver from the Proprietary GPU Drivers PPA in favor of the version in the cuda ppa which does not have `libnvidia-gl-440:i386` and nvidia's running kernel module version, 64 bit userspace version, and 32 bit userspace version must exactly match for the driver to work for everything.

**Comment by rileyweber13** [comment]
thanks, that makes sense. I'll keep looking at #5778 because it seems to be exactly what I'm dealing with. Thanks for your explanations!

**Comment by waltermaldonado** [comment]
Installing `libnvidia-gl-430:i386` fixed it. I am closing the issue, thank you very much!
