### ISSUE TITLE
manage screenshot option not working

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6842]
#### Your system information

* Steam client version (build number or date): Jan 22
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

system info: https://gist.github.com/LiamDawe/2d9658a70000c569f7a1e8dfaef19488

#### Please describe your issue in as much detail as possible:

Right click image on Steam -> Manage Screenshots -> nothing happens

It's supposed to bring up the box with all of them for that game, now it does nothing since the most recent beta update. Doesn't say anything in terminal when it happens either.

Testing the stable build, it works fine.

#### Steps for reproducing this issue:

1. opt into beta
2. take game screenshot with overlay
3. attempt to open screenshot manager
4. cry as it fails
5. go back to stable build

**Comment by kisak-valve** [comment]
Hello @LiamDawe, looks like View -> Screenshots works, so it's not completely broken.

**Comment by LiamDawe** [comment]
Yup, that works. It's just the in-library view that seems broken.

**Comment by autotoxicus** [comment]
I can confirm this issue, for me under Linux Mint 19.3. Neither right click->Manage screenshots is working nor the button "Manage my xx screenshots" below. 
Also this issue is only affecting the beta, opting out of it is fixing that for me.

**Comment by Managor** [comment]
Yep, I have the same problem. https://youtu.be/IQxzk2kNIIc

**Comment by arrowgent** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/6868

sorry repost

**Comment by barfin** [comment]
same issue here

**Comment by arrowgent** [comment]
wanted to report that Screenshots & Demo Download works correctly again

Manage Screenshots. and clicking Download Demo works after a recent update


anyone else???

thanks

**Comment by autotoxicus** [comment]
Yes, "Manage Screenshots" works fine again (both via right click screenshot->Manage screenshots and the button "Manage my xx screenshots" below). 
I didn't realize any problem with demo downloads before.

**Comment by LiamDawe** [comment]
Yup works now. Closing.
