### ISSUE TITLE
Steam Link no sound in MacOS Catalina

### ISSUE THREAD

**Issue by jlariza** [ValveSoftware/steam-for-linux#6846]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/16421045/73115361-e8fb1c00-3ef2-11ea-9002-b446dd06c90d.png)

* Distribution (e.g. Ubuntu):  MacOS Catalina 10.15.2
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Good Day,

I used to use my steam link connected to an ubuntu machine and everything worked fine. Last month, I changed to a MacBook Pro. Today, I tried to use my steam link to play some games. It asked me to install the drivers, they installed fine. However, when I started playing the sound did not come from the tv but from the MacBook.

I have tried everything and the mac stills plays the sound. What should I do to move the sound playing to the steam link and the tv?

I find just one similar issue in the forums, with no response https://steamcommunity.com/app/353380/discussions/0/2803982773087569042/

Thank you

**Comment by kisak-valve** [comment]
Hello @jlariza, this issue tracker is primarily limited to issues with the Steam-for-Linux client. You'll want to use [Steam Support](https://help.steampowered.com/) to get support for the Steam-for-Mac client.
