### ISSUE TITLE
Fedora 31: Cannot install any game (manifest unavailable)

### ISSUE THREAD

**Issue by jeyk** [ValveSoftware/steam-for-linux#6847]
#### Your system information

* Steam client version (build number or date): Jan 18 2020, 03:34:03
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Steam client installs and runs fine, but I am unable to install *ANY* game. The error message is the same every time (although the game name and URI are different):

An error occured while installing <GAME> (manifest unavailable):
cache-55-fra1.steamcontent.com/depot/365455/manifest/1911080312180287555/5

I have also tried to change the download servers, the error persists, but the URI changes.

#### Steps for reproducing this issue:

1. Install Steam on Fedora 31
2. Try to download any game

**Comment by jeyk** [comment]
With a browser, I am able to download the manifest from the provided URI. It gives me a ZIP file with a binary blob inside.

**Comment by jeyk** [comment]
I managed to figure it out. My installation was missing _libnet_. After nstalling it with`sudo dnf install libnet` and restarting Steam, I can now download games.

Leaving this here for anyone else who might have the same problem.

**Comment by MineOzelot** [comment]
I have the same problem, but I don't get any error messages. Installation process just gets stuck at "Creating local game files..." stage. And installing libnet didn't help me..
