### ISSUE TITLE
steam crashed when opening USB tethering

### ISSUE THREAD

**Issue by Sodium-Aluminate** [ValveSoftware/steam-for-linux#6852]
#### Your system information

* Steam client version (build number or date): `Jan 18 2020` `v020` `1579321278`
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] **No**
* Have you checked for system updates?: [Yes/No] **Yes**

#### Please describe your issue in as much detail as possible:

I launched steam by type `steam` in my **terminal**, then I plugged my phone in my PC, then I opened **USB tethering** in my phone.
Then steam crashed.
I've tried lots time(more than 3) and steam always crashed when I open the "USB tethering"
**HOWEVER**, it won't crash if I open steam **after** open the "USB tethering" in my phone.

#### Steps for reproducing this issue:

1. open steam in bash
2. plug a phone(my phone -> Redmi Note 4, [AEX](https://aospextended.com/) - v5.8 with [Magisk](github.com/topjohnwu/magisk) 19.3
3. open USB tethering (Share phone’s Internet connection via USB) in settings.

**Comment by Sodium-Aluminate** [comment]
it output (in terminal)
```
** (steam:14798): WARNING **: 00:25:36.253: Unknown device type 14

** (steam:14798): WARNING **: 00:25:36.253: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type

** (steam:14798): WARNING **: 00:25:36.253: Unknown device type 13

** (steam:14798): WARNING **: 00:25:36.253: Could not create object for /org/freedesktop/NetworkManager/Devices/3: unknown object type

** (steam:14798): WARNING **: 00:25:36.253: Unknown device type 16

** (steam:14798): WARNING **: 00:25:36.253: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:14798): WARNING **: 00:25:36.299: Ignoring invalid property 'autoconnect-priority'

** (steam:14798): WARNING **: 00:25:36.299: Unknown setting 'proxy'

** (steam:14798): WARNING **: 00:25:36.299: Ignoring invalid property 'route-data'

** (steam:14798): WARNING **: 00:25:36.299: Ignoring invalid property 'address-data'

** (steam:14798): WARNING **: 00:25:36.299: Ignoring invalid property 'route-data'

** (steam:14798): WARNING **: 00:25:36.299: Ignoring invalid property 'address-data'

(steam:14798): GLib-GObject-WARNING **: 00:25:36.299: invalid cast from 'NMSettingConnection' to 'NMRemoteSettings'
assert_20200124110639_1.dmp[4569]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200124110639_1.dmp
assert_20200124110639_1.dmp[4569]: Finished uploading minidump (out-of-process): success = no
assert_20200124110639_1.dmp[4569]: error: Couldn't resolve host name
assert_20200124110639_1.dmp[4569]: file ''/tmp/dumps/assert_20200124110639_1.dmp'', upload no: ''Couldn't resolve host name''
/home/sodiumaluminate/.local/share/Steam/steam.sh: line 722: 14798 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```
before crashed.

**Comment by kisak-valve** [comment]
Hello @Sodium-Aluminate, this reads like #3959. Does `sudo apt install libnm-glib4:i386 libnm-util2:i386`workaround the issue?  (from https://github.com/ValveSoftware/steam-for-linux/issues/3959#issuecomment-311404926)

**Comment by Sodium-Aluminate** [comment]
> Hello @Sodium-Aluminate, this reads like #3959. Does `sudo apt install libnm-glib4:i386 libnm-util2:i386`workaround the issue? (from [#3959 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/3959#issuecomment-311404926))

I'm not sure......
Because I found it doesn't crash now(and I even not remember what I've done on it)
that's weird......
