### ISSUE TITLE
xbox elite v2 controller + firmware updates support

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/steam-for-linux#6854]
#### Your system information

* Steam client version (build number or date): 1579321278
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes and then no (tested both)

#### Please describe your issue in as much detail as possible:

It would be nice to not only support the xbox 360 and Xbox one S and Xbox one X controllers but also the xbox elite and xbox elite v2 controllers.

currently the last two (or as far as I know only the v2) aren't supported.

I recently bought one and on first try it worked fine, but after booting into windows to map the backplate buttons, it got firmware updated and now the inputs are all scrambled. (this is why I mention it's firmware update.)

obviously this firmware update is how Microsoft intends this controller to be mapped so might as well just adapt to it. 

Here's what I found testing it in the game rocket league :

 

1. left trigger is mapped to right trigger and is constantly receiving input (the only one with this constant input glitch)
2. right trigger is mapped to left

everything else is correctly mapped.

within the big picture configuration menu the correct buttons light up when pressed.

I tried every existing combination of steam big picture's controller input brands and the game's properties menu controller options "Steam Input Per-Game Setting" and "Use BPM overlay when steam input is Active Per-Game Setting".

I found that the controller inputs were killed by "Steam Input Per-Game Setting" being on and that steam big picture's controller input brands (only testing "generic gamepad" and "xbox controller") had no effect on the presence or quality of inputs whatsoever (the input was present but the mis-mappings remained in all cases).

#### Steps for reproducing this issue:

1. connect an updated xbox elite v2 controller
2. launch any game (Rocket League for example) (252950)

**Comment by chaorace** [comment]
I think this issue was fixed some time ago in a microsoft firmware update. My elite controller is on latest firmware and seems to map correctly under the default profile (though the back paddles can't be mapped, which is a missing feature that Steam Input on Windows supports).

**Comment by tatsujb** [comment]
I fixed that since by setting up my controller on windows and then going back to linux.
