### ISSUE TITLE
Invalid SSL Certificate when navigating the store

### ISSUE THREAD

**Issue by argent0** [ValveSoftware/steam-for-linux#6855]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20191210.1(See #6855)
* Distribution (e.g. Ubuntu): Freedesktop.org 19.08.6 (Flatpack runtime) 64bit over archlinux
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I click in various liinks (e.g: store, workshops, etc...)
**expected**: to load the desired site
**What did happen**: I got the message: Invalid SSL Certifcate displayed on screen

#### Steps for reproducing this issue:

1. Open steam
2. Enter a game section
3. Click a workshop link

Console Output
[gist](https://gist.github.com/argent0/655464981f7f5d0f0a850dabf3545eee)

What I've tried:
* System clock is OK
* DNS is google's

**Comment by kisak-valve** [comment]
Hello @argent0, this issue is also being tracked at https://github.com/flathub/com.valvesoftware.Steam/issues/526.

**Comment by smcv** [comment]
> Distribution [...] archlinux

If you are using the Flatpak app, and p11-kit on the host system is version 0.23.19, please upgrade it to version 0.23.20 (or downgrade to 0.23.18, at your own risk). There was an unintended backwards compatibility break between p11-kit 0.23.18 and 0.23.19 (p11-glue/p11-kit#275), which has been reverted in p11-kit 0.23.20.

This mostly affects rolling-release distributions such as Arch Linux and Debian testing/unstable. Stable releases that include p11-kit 0.23.18 or older (e.g. Debian 10, Ubuntu 19.10 or older, SteamOS) are unaffected.
