### ISSUE TITLE
Games still grabbing mouse events when the Steam Overlay is active

### ISSUE THREAD

**Issue by guihkx** [ValveSoftware/steam-for-linux#6856]
#### Your system information

* Steam client version (build number or date):  1579996884 (Jan 25 2020, at 17:39:11)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Whenever I open the Steam Overlay (<kbd>Shift</kbd>+<kbd>Tab</kbd>), any game running in background will still grab the mouse input, i.e., any left or right click made while the Steam Overlay is open, will also be grabbed by the game. This does not happen on Steam for Windows. I've tested this with some native and windows games (via Proton):

* CS:GO (native): Mouse clicks aren't passed to the game, but mouse movements are. To reproduce it, join a casual match, enter spectator mode ("free roam" mode), open the Steam overlay, and move you mouse around.
* Terraria (native): Left/right clicks are 100% replicated by the game, which is really annoying when you need to do a Google search to retrieve some information in the game's wiki. Any mouse action you do will be registered by game, so if you've paused the game, you will be opening random options in the game's menu. If you didn't pause it, your character will attack things around you.
* GTA:SA (Proton): This one is similar to Terraria, everything is registered by the game. It's easily reproducible too, just launch the game and wait until the main menu appears, then you open the Steam Overlay. You'll be able to notice that any mouse movement you do is immediately registered and replicated by the game.

#### Steps for reproducing this issue:

1. Launch GTA:SA using Proton (but it should work in any of the games I mentioned above)
2. Open the Steam Overlay (<kbd>Shift</kbd>+<kbd>Tab</kbd> by default)
3. Move your mouse cursor around; do some random left clicks
4. Game will register everything, when it shouldn't

**Comment by kisak-valve** [comment]
Hello @guihkx, can you test if the workaround at https://github.com/ValveSoftware/steam-for-linux/issues/6506#issuecomment-537197719 has an effect? Possible duplicate of that issue report.

**Comment by guihkx** [comment]
Thanks for answering it so quickly!

I'm a bit confused though. Since I'm running the Flatpak build of Steam, wasn't it supposed to be using their own SDL build? And if they are, I'm not sure how I would be able to downgrade it.

Nonetheless, I've downgraded both `sdl2` and `lib32-sdl` to version `2.0.9`, but had no effect.

**Comment by guihkx** [comment]
Just to make sure this isn't related to Flatpak, I decided to install the regular `steam` package from Arch.

Then, I applied **all** of [these workarounds](https://github.com/ValveSoftware/steam-for-linux/issues/6506#issuecomment-537197719), launched Terraria (native), but the game still grabs mouse events when the Steam Overlay is active.

**Comment by TTimo** [comment]
Thanks - this is a duplicate of #6506 

As you noted, CS:GO doesn't pass button clicks so further work on that is low priority.
But the other titles (Terraria) passing button clicks is new information so we'll look at this again.

**Comment by guihkx** [comment]
Thanks. I'm closing this one in favor of #6506, then.

**Comment by blargle-ragequit** [comment]
I'm having this issue with Steam version of Grand Theft Auto III on up-to-date Arch Linux, both with and without runtime enabled.  Non-beta Steam, built Jul 8 2020 at 23:11:02, package versions 1594252496.

**Comment by alexzk1** [comment]
Same problem yet. I just tried to use Overlay 1st ever time in Elite Dangerous. Space ship follows mouse while I browse web page there. 
Arch Linux here, everything is auto updated.

**Comment by KairaGocen** [comment]
Same problem still exists.

**Comment by Minoo122** [comment]
I've got the same issue for Mint
