### ISSUE TITLE
Controller support is broken on Steam big picture mode

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#6860]
#### Your system information

* Steam client version (build number or date): 157932178
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] no but I tested on both and they both had the same results
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Work out of the box like it use to do..

#### Steps for reproducing this issue:

1. Go into Steam big picture mode
2. Controller in overlay doesn't work and shows as no controller exists but if I go into a game it's fine

I am just using a Logitech Gamepad F310 and yes I did tick generic controller support

One one Manjaro laptop it wasn't coming up or working and on my Manjaro Desktop it for some reason came up as detecting a Xbox 360 controller and even manually setting the keys still didn't work.

**Comment by TTimo** [comment]
Hello @coreybruce - we cannot reproduce the problem. Please provide the runtime diagnostics for your system from the Help > System Information menu (you will need to go into desktop mode).

**Comment by coreybruce** [comment]
Sure thing

`Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  4300 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.5.0-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12007000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime_0.20191210.1

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.44
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c03
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3600 x 1080
    Primary Display Size: 20.91" x 11.77" (23.98" diag)
                                            53.1cm x 29.9cm (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  15956 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_AU.utf8
    Total Hard Disk Space Available:  102099 Mb
    Largest Free Hard Disk Block:  51002 Mb
    VR Headset: None detected

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/corey/.local/share/Steam",
    "data_path" : "/home/corey/.local/share/Steam",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/home/corey/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20191210.1",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        "  4204591      4 drwxr-xr-x   2 corey    corey        4096 Jan 30 16:11 pinned_libs_32",
        "  4204593      4 lrwxrwxrwx   1 corey    corey         105 Jan 30 16:11 pinned_libs_32/libdbusmenu-gtk.so.4 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        "  4204595      0 -rw-r--r--   1 corey    corey           0 Jan 30 16:11 pinned_libs_32/has_pins",
        "  4204596      4 lrwxrwxrwx   1 corey    corey          99 Jan 30 16:11 pinned_libs_32/libGLU.so.1 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libGLU.so.1.3.08004",
        "  4204598      4 lrwxrwxrwx   1 corey    corey         107 Jan 30 16:11 pinned_libs_32/libgtk-x11-2.0.so.0 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.10",
        "  4204599      4 -rw-r--r--   1 corey    corey          70 Jan 30 16:11 pinned_libs_32/system_libgtk-x11-2.0.so.0",
        "  4204601      4 -rw-r--r--   1 corey    corey          53 Jan 30 16:11 pinned_libs_32/system_libjack.so.0",
        "  4204616      4 -rw-r--r--   1 corey    corey          58 Jan 30 16:11 pinned_libs_32/system_libdbus-1.so.3",
        "  4204615      4 lrwxrwxrwx   1 corey    corey          94 Jan 30 16:11 pinned_libs_32/libdbus-1.so.3 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8",
        "  4204594      4 -rw-r--r--   1 corey    corey          69 Jan 30 16:11 pinned_libs_32/system_libdbusmenu-gtk.so.4",
        "  4204597      4 -rw-r--r--   1 corey    corey          50 Jan 30 16:11 pinned_libs_32/system_libGLU.so.1",
        "  4204600      4 lrwxrwxrwx   1 corey    corey          96 Jan 30 16:11 pinned_libs_32/libjack.so.0 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libjack.so.0.1.0",
        "  4204602      4 lrwxrwxrwx   1 corey    corey         106 Jan 30 16:11 pinned_libs_32/libdbusmenu-glib.so.4 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "  4204603      4 -rw-r--r--   1 corey    corey          71 Jan 30 16:11 pinned_libs_32/system_libdbusmenu-glib.so.4"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        "  4204592      4 drwxr-xr-x   2 corey    corey        4096 Jan 30 16:11 pinned_libs_64",
        "  4204604      4 lrwxrwxrwx   1 corey    corey         107 Jan 30 16:11 pinned_libs_64/libdbusmenu-gtk.so.4 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        "  4204606      0 -rw-r--r--   1 corey    corey           0 Jan 30 16:11 pinned_libs_64/has_pins",
        "  4204607      4 lrwxrwxrwx   1 corey    corey         101 Jan 30 16:11 pinned_libs_64/libGLU.so.1 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        "  4204614      4 -rw-r--r--   1 corey    corey          48 Jan 30 16:11 pinned_libs_64/system_libcurl.so.4",
        "  4204610      4 -rw-r--r--   1 corey    corey          49 Jan 30 16:11 pinned_libs_64/system_libjack.so.0",
        "  4204605      4 -rw-r--r--   1 corey    corey          65 Jan 30 16:11 pinned_libs_64/system_libdbusmenu-gtk.so.4",
        "  4204608      4 -rw-r--r--   1 corey    corey          46 Jan 30 16:11 pinned_libs_64/system_libGLU.so.1",
        "  4204609      4 lrwxrwxrwx   1 corey    corey          98 Jan 30 16:11 pinned_libs_64/libjack.so.0 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libjack.so.0.1.0",
        "  4204611      4 lrwxrwxrwx   1 corey    corey         108 Jan 30 16:11 pinned_libs_64/libdbusmenu-glib.so.4 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "  4204612      4 -rw-r--r--   1 corey    corey          67 Jan 30 16:11 pinned_libs_64/system_libdbusmenu-glib.so.4",
        "  4204617      0 lrwxrwxrwx   1 corey    corey          12 Jan 30 16:11 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        "  4204613      4 lrwxrwxrwx   1 corey    corey          98 Jan 30 16:11 pinned_libs_64/libcurl.so.4 -> /home/corey/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0"
      ]
    }
  },
  "os-release" : {
    "id" : "manjaro",
    "id_like" : [
      "arch"
    ],
    "name" : "Manjaro Linux",
    "pretty_name" : "Manjaro Linux"
  },
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /home/corey/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS64\n",
          "renderer" : "GeForce GTX 1060 6GB",
          "version" : "1.1.119 (device 10de:1c03) (driver 440.176.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        }
      }
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_intel.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_intel.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /home/corey/.local/share/Steam/ubuntu12_32/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS32\n",
          "renderer" : "GeForce GTX 1060 6GB",
          "version" : "1.1.119 (device 10de:1c03) (driver 440.176.0)"
        },
        "glx/gl" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        },
        "egl_x11/gl" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "4.6.0 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "GeForce GTX 1060 6GB/PCIe/SSE2",
          "version" : "OpenGL ES 3.2 NVIDIA 440.44",
          "library-vendor" : "glvnd"
        }
      }
    }
  },
  "locale-issues" : [
    "c-utf8-missing",
    "i18n-supported-missing"
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "LC_CTYPE=en_AU.utf8;LC_NUMERIC=en_AU.UTF-8;LC_TIME=en_AU.UTF-8;LC_COLLATE=en_AU.utf8;LC_MONETARY=en_AU.UTF-8;LC_MESSAGES=en_AU.utf8;LC_PAPER=en_AU.UTF-8;LC_NAME=en_AU.UTF-8;LC_ADDRESS=en_AU.UTF-8;LC_TELEPHONE=en_AU.UTF-8;LC_MEASUREMENT=en_AU.UTF-8;LC_IDENTIFICATION=en_AU.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "error-domain" : "srt-locale-error-quark",
      "error-code" : 0,
      "error" : "No such file or directory"
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
        "library_path" : "libEGL_nvidia.so.0"
      },
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/etc/vulkan/icd.d/nvidia_icd.json",
        "library_path" : "libGLX_nvidia.so.0",
        "api_version" : "1.1.119"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_radeon.so",
        "api_version" : "1.1.107"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_intel.so",
        "api_version" : "1.1.102"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_radeon.so",
        "api_version" : "1.1.107"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_intel.so",
        "api_version" : "1.1.102"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_radeon.so",
        "api_version" : "1.1.107"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib32/libvulkan_intel.so",
        "api_version" : "1.1.102"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_radeon.so",
        "api_version" : "1.1.107"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib/libvulkan_intel.so",
        "api_version" : "1.1.102"
      }
    ]
  }
}

The Steam Linux Runtime container tool is not installed.
`

**Comment by TTimo** [comment]
Thank you (your Steam configuration looks fine, problem is somewhere else).

Do you have Steam configured to start in Big Picture mode? If so, try to start in desktop mode then switch to BP mode?

**Comment by coreybruce** [comment]
I did but even if I did it would be the same regardless if I had it started when opening or if I went into big picture mode myself

**Comment by TTimo** [comment]
If I configure Steam to start in BP mode, then the controller doesn't work. It works fine if I start in desktop mode, then enter BP mode. That's a bug, but it doesn't sound like the issue you are running into.

**Comment by TTimo** [comment]
> If I configure Steam to start in BP mode, then the controller doesn't work. It works fine if I start in desktop mode, then enter BP mode. That's a bug, but it doesn't sound like the issue you are running into.

Actually I can't reproduce this problem either today, so maybe I tested that incorrectly too.

**Comment by coreybruce** [comment]
Seems to work on my desktop now, no idea why it wasn't before. Thanks for the help anyways, no idea what was causing the issue

**Comment by pr-delta** [comment]
I am also running into this problem. Specifically with DOOM 2016, where the inputs get messed up when running in big picture mode.
