### ISSUE TITLE
Steam  crashes at startup on ubuntu 18.04

### ISSUE THREAD

**Issue by m4456l** [ValveSoftware/steam-for-linux#6862]
#### Your system information

* Steam client version (build number or date):  2,2,2020
* Distribution (e.g. Ubuntu): Ubuntu 18.04.3 LTS
* Opted into Steam client beta?: [Yes/No]no
* Have you checked for system updates?: [Yes/No]yes

When I try to run steam,it just disappear in a moment.
here is terminal output:

> Running Steam on ubuntu 18.04 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> /home/fang-anpai/.local/share/Steam/ubuntu12_32/steam
> Installing breakpad exception handler for appid(steam)/version(1579321278)
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Installing breakpad exception handler for appid(steam)/version(1579321278)
> Installing breakpad exception handler for appid(steam)/version(1579321278)
> Gtk-Message: 18:11:51.465: Failed to load module "gail"
> Gtk-Message: 18:11:51.465: Failed to load module "atk-bridge"
> 
> (steam:30403): Gtk-WARNING **: 18:11:51.480: 无法在模块路径中找到主题引擎：“adwaita”，
> /usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
> 
> (steam:30403): Gtk-WARNING **: 18:11:51.481: 无法在模块路径中找到主题引擎：“adwaita”，
> /usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Steam: An X Error occurred
> X Error of failed request:  GLXBadContext
> Major opcode of failed request:  151
> Serial number of failed request:  48
> xerror_handler: X failed, continuing
> Steam: An X Error occurred
> X Error of failed request:  BadValue (integer parameter out of range for operation)
> Major opcode of failed request:  151
> Value in failed request:  0x0
> Serial number of failed request:  47
> xerror_handler: X failed, continuing
> Steam: An X Error occurred
> X Error of failed request:  BadMatch (invalid parameter attributes)
> Major opcode of failed request:  151
> Serial number of failed request:  49
> xerror_handler: X failed, continuing
> assert_20200202181150_1.dmp[30422]: Uploading dump (out-of-process)
> /tmp/dumps/assert_20200202181150_1.dmp
> /home/fang-anpai/.local/share/Steam/steam.sh: 行 722: 30403 段错误               (核心已转储) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
> assert_20200202181150_1.dmp[30422]: Finished uploading minidump (out-of-process): success = yes
> assert_20200202181150_1.dmp[30422]: response: CrashID=bp-417fda65-c304-496b-9bb4-d5d212200202
> assert_20200202181150_1.dmp[30422]: file ''/tmp/dumps/assert_20200202181150_1.dmp'', upload yes: ''CrashID=bp-417fda65-c304-496b-9bb4-d5d212200202''

#### Steps for reproducing this issue:

1. install CUDA10.0 (and automatic,install nvidia-driver-440,)
2. install
3. install steam by dpkg -i steam_latest.deb
4.$ steam

**Comment by kisak-valve** [comment]
Hello @m4456l, nVidia's CUDA 10 installer is known to be problematic because it is missing 32 bit userspace support. This issue is being tracked at #5778. Your best bet is to give https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-575334890 a read.

Closing as a duplicate.
