### ISSUE TITLE
big picture overlay issues

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#6863]
## Your system information

* Steam client version (January 25 2020): 
* Distribution (Manjaro): 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes/
[sysinfogist](https://gist.github.com/zany130/7898365812cd9a0acd9e3f0aa191e5e2)

#### Please describe your issue in as much detail as possible:
after playing trails in the sky for a few hours the steam big picture overlay "broke".
Popups of friends going online or whatever would no longer dismiss also nothing could be selected in the overlay. it would show up but clicking or using the controller to select something anywhere on the screen does nothing running 
```
tail -f /tmp/dumps/${USER}_stdout.txt
```
gives this output 
```
Timed out waiting for mutex in PutInternal()
DispatchAsyncEvent backlog, failed to dispatch all this frame. Queue depth: 2714143 (2714150 input number was)
```

#### Steps for reproducing this issue:

1.launch a game with big picture overlay enabled  
2. play for a few hours
3. notice the issues mentioned above and in 
```
tail -f /tmp/dumps/${USER}_stdout.txt
```

**Comment by zany130** [comment]
was able to fix this by opting out and then opting back into the steam beta

**Comment by zany130** [comment]
the issue cam back and I have new logs. so to recap after playing anygame it semms for more than a few hours the bigpicture hud will stop responding and steam notifications like messages online friends etc that appear will get stuck on screen. After exiting the game the steam client will imediantly segfualt 
[Logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/4189187/Logs.zip)

**Comment by zany130** [comment]
[zany130.zip](https://github.com/ValveSoftware/steam-for-linux/files/4253376/zany130.zip)

some more logs

**Comment by zany130** [comment]
still have this issue and this happend last night https://photos.app.goo.gl/ivqQtrknE8cMeqUNA the game ran (and continued to run perfectly fine)

**Comment by kisak-valve** [comment]
Hello @zany130, are you still experiencing this issue on an up to date system?

**Comment by zany130** [comment]
sorry forgot about this issue haven't seen it in a while so no so I guess I can go ahead and close this
