### ISSUE TITLE
Segmentation fault after the "Updating user configuration"

### ISSUE THREAD

**Issue by catrielmuller** [ValveSoftware/steam-for-linux#6864]
#### Your system information

* Steam client version (build number or date): 1579321278
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

The Steam App crash after the "Updating user configuration"

- CrashID=bp-c8fd5c85-3a8a-4d0a-9d72-dfb622200203
- Steam Log (https://gist.github.com/catrielmuller/2cd93e43a6f504a05044890b626d69ad) when run over runtime
- Steam Log (https://gist.github.com/catrielmuller/cad4f43d3d17f0b6a0e4ee8f7c9d230e) when run over native libs
- Native CrashID=bp-4507dcbe-4f44-40d0-abe6-79a512200203'

#### Steps for reproducing this issue:

1. Open Steam
2. LIBGL_DEBUG=verbose steam-runtime

**Comment by catrielmuller** [comment]
Update: This issue only happen on Wayland. on XOrg the app launch without issues.

**Comment by kisak-valve** [comment]
Hello @catrielmuller, are you still experiencing this issue on an up to date system?
