### ISSUE TITLE
Demo Download doesnt do anything anymore...

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/steam-for-linux#6867]
#### Your system information

* Steam client version (build number or date): 0.20200113.0 (1580500660) API v020 Built Jan 31 2020
* Distribution (e.g. Ubuntu): Linux Mint 19.3 Tricia (64 bit) MATE
* Opted into Steam client beta?: [Yes/No] ja
* Have you checked for system updates?: [Yes/No] ja

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

steam game store page:
Click Demo.  Downloading demo appears and installs

instead:
click Demo; nothing happens.

#### Steps for reproducing this issue:

1. store page
2. click demo
3. 

alternatively i have been using
steamdb "game name" demo
terminal > steam steam://install/appid#

**Comment by arrowgent** [comment]
possibly related
https://github.com/ValveSoftware/steam-for-linux/issues/6842
stopped working in a recent BETA update

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/steam-for-linux/issues/6842#issuecomment-586880762.
