### ISSUE TITLE
Manage my Screenshots stopped working

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/steam-for-linux#6868]
#### Your system information

* Steam client version (build number or date): 0.20200113.0
* Distribution (e.g. Ubuntu): Linux Mint 19.3 Tricia (64 bit)
* Opted into Steam client beta?: [Yes/No] ja
* Have you checked for system updates?: [Yes/No] ja

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

library game page:
1) Click Manage my Screenshots - popup with all screenshots opens to delete/upload/manage.
2) alternatively: right click a screenshot and click Manage Screenshots

instead:
1) click Manage my Screenshots, nothing happens.
2) alternatively: right click a screenshot and click Manage Screenshots; Nothing happens

#### Steps for reproducing this issue:

1. Library
2. game library page
3. scroll to screenshots
4. click "Manage my Screenshots"

**Comment by kisak-valve** [comment]
Hello @arrowgent, this issue is already being tracked at #6842. Closing as a duplicate.
