### ISSUE TITLE
Proton does not download if family view is enabled.

### ISSUE THREAD

**Issue by toojays** [ValveSoftware/steam-for-linux#6873]
Could be a variant of #6849, but this is maybe narrower in scope.

#### Your system information

* Steam client version (build number or date): Built Jan 18 2020
* Distribution (e.g. Ubuntu): Debian 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

I saw that Proton 5 is out and that Abzu is now expected to work. As luck would have it, that morning my son wanted to play Abzu. So I booted into Linux, told Steam to force the use of Proton 5 for Abzu, and clicked "Install". The game installed fine, but when I pressed "Play", the status of the game was "Downloading (0%)". It stayed that way for minutes before I just killed Steam.

I was able to resolve the issue by exiting Family View before clicking "Play" on Abzu. I think this allowed Proton to download, and then the game loaded and ran fine. After that I was able to run Abzu from within Family View as well.

I have not attempted to reproduce this issue.

**Comment by kisak-valve** [comment]
Hello @toojays, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
