### ISSUE TITLE
Switching default compatibility tool from Proton 4.11 to 5.0-1 makes Steam classify some installed & working games as "invalid platform" (greyed-out INSTALL)

### ISSUE THREAD

**Issue by fallenguru** [ValveSoftware/steam-for-linux#6874]
#### Your system information

* Steam client version (build number or date): 2020-01-31
* Distribution (e.g. Ubuntu):  Ubuntu 18.04.4
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
Proton 5.0-1 just came out, so naturally I wanted to see if my currently installed games worked better, or at least still worked. Most, like The Witcher 3 (292030), Prey (2017, 480490), and Ori DE (387290) were fine, so were all the whitelisted ones, as far as a 5-minute test could tell ...

... but, for example, The Sexy Brutale (552590) and Sabbat of the Witch (888790) only showed a greyed-out INSTALL button instead of PLAY. Also the "Runs on this computer via Steam Play" line was missing entirely.
Trying to launch them via their store page's Play Now yielded an "invalid platform" error message.

Workaround: Temporarily forcing a specific compatibility tool in the game's properties will restore normal UI behaviour, the option can then be unchecked again.

**Comment by kisak-valve** [comment]
Hello @fallenguru, are you still experiencing this issue on an up to date system?

@DragoonAethis, the scenario you've described sounds like Steam would be configured to run the game with a removed third party build of Proton when it misbehaved. I wouldn't expect Steam to automatically chose a different Proton version when you've explicitly picked a third party compatibility tool which just happened to become unavailable. It's probably better if that behavior remains the same.

**Comment by pernegger** [comment]
Come to think of it, I haven't encountered this on any of my boxes for quite a while. Feel free to close.

**Comment by fallenguru** [comment]
Come to think of it, I haven't encountered this on any of my boxes for quite a while. Feel free to close.

**Comment by kisak-valve** [comment]
Thanks for the feedback, closing.

**Comment by DragoonAethis** [comment]
@kisak-valve I've retested this now and after removing Proton files forced for a game, it just resets the forced Proton version back to the default (no forced version at all). (Which I guess is a bit better than the previous behavior. I'd like some sort of a notification that the forced version is no longer available as well, but eh, doesn't matter much.)
