### ISSUE TITLE
QOL: Add a button to instantly go to the app's compat data

### ISSUE THREAD

**Issue by Joshua-Ashton** [ValveSoftware/steam-for-linux#6875]
It would be cool to add an option to quickly go to the app's compat data/prefix in this menu:

![image](https://user-images.githubusercontent.com/21316711/74089353-559c1c00-4a98-11ea-85e1-3f634a7bf64f.png)

Adding it to this menu also would be nice too:

![image](https://user-images.githubusercontent.com/21316711/74089382-a9a70080-4a98-11ea-9f8b-2f7e56c813f2.png)

**Comment by kisak-valve** [comment]
Hello @Joshua-Ashton, this feature request is already being tracked at #5667. Closing as a duplicate.
