### ISSUE TITLE
Proton 5.0-1 not appearing in list of compatibility tools

### ISSUE THREAD

**Issue by philipl** [ValveSoftware/steam-for-linux#6877]
#### Your system information

* Steam client version (build number or date): Jan 31 2020, at 01:22:48
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I can't see Proton 5.0-1 in the list of compatibility tools, neither at the global or per game level. I've restarted the client plenty of times, and switched back and forth from beta to non-beta with no success.

I've tried manually installing the Proton 5.0 tool, also with no success.

I tried manually adding a tool entry in config.vdf - that also didn't make a difference.

compat_log.txt shows it loading the older versions of proton but no the latest.

#### Steps for reproducing this issue:

1. Run the client
2. Look at list of tools in Settings
3. Don't see Proton 5.0-1

**Comment by Peter-Crawley** [comment]
I am using Ubuntu 18.04.3 LTS, I am not having this problem.

**Comment by virus-found** [comment]
Reproduces for me too. The latest version available is 4.11-12

**Comment by philipl** [comment]
I've clarified the distro version - I'm running 19.10.

**Comment by philipl** [comment]
I tried completely deleting my `~/.steam` and after I logged back in, Proton 5.0-1 was available. I've kept my old directory around if you want to know anything about it for debug purposes.

**Comment by byte1024** [comment]
By saying tools I assume first that it means the tools section of Steam library which is where it should be found if you don't see it in the Proton version selection list.

Based on the issue wording, I can't for the life of me figure out if that was checked.

**Comment by virus-found** [comment]
Today opened up steam after some update - and Proton 5.0-1 automagically appears now.

**Comment by philipl** [comment]
I'm going to close this, given what @virus-found said.
