### ISSUE TITLE
Steam Link output flickers when a full screen application is on front

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6879]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/74107881-31663b00-4b7d-11ea-8399-db527df1393a.png)
* Distribution: Arch Linux
* Desktop Environment: KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When you have a full screen application on front, the screen will flicker, partly revealing what is underneath. This applies to BPM and youtube but not fullscreen games. On desktop without any fullscreen, the flicker applies only to the KDE taskbar.
Demonstrative video here: https://www.youtube.com/watch?v=YVk8V9ufiaA
System info: https://gist.github.com/Managor/43b09135ccbb7d12acab670237d4f7ef
Additionally: The TV is 720p while the display it's streaming from is 1080p, I have an Nvidia video card and the desktop environment is the default KDE desktop. This didn't happen back when I was on Xubuntu and I think it happened last Friday too before the latest steam link beta.

**Comment by Managor** [comment]
So apparently it's not a problem with streaming, but video capture as OBS sees it too. https://youtu.be/EH-InX84M_A

**Comment by Managor** [comment]
#4351 Might be related but the video doesn't look similar.

**Comment by BigB86** [comment]
I'm also having an issue with screen flicker when using Steam Link with my Ubuntu host. I have Steam beta enabled and will try the stable version to see if it fixes the issue. The flicker happens when using Steam Link on an Nvidia shield and is in "Big Picture Mode" on the Ubuntu host and goes away when a game is started.

**Comment by guillaumezin** [comment]
> 
> 
> The flicker happens when using Steam Link on an Nvidia shield and is in "Big Picture Mode" on the Ubuntu host and goes away when a game is started.

Try the command nvidia-settings --assign="AllowFlipping=0" if you have a nvidia card, see #4351

**Comment by Managor** [comment]
Has this been fixed? I haven't encountered it in a long while but I haven't tested anything either.

**Comment by Managor** [comment]
Confirmed today that it is still happening when I streamed to my phone https://youtu.be/dgbkUAb0PXQ
Nvidia driver: 470.74
KDE Plasma: 5.22.5
KDE Frameworks: 5.86.0
QT Version: 5.15.2

**Comment by kisak-valve** [comment]
Closing in favor of #4351.
