### ISSUE TITLE
Controller HUD does not show all inputs

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6880]
#### Your system information

* Steam client version:  
![image](https://user-images.githubusercontent.com/42655600/74107881-31663b00-4b7d-11ea-8399-db527df1393a.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When toggling Controller HUD, it doesn't show all of the controller inputs you make. As an example
Cuphead: https://youtu.be/aHSCPPAj6MY Config: steam://controllerconfig/268910/1895534701
Talos Principle: https://youtu.be/mwn_g0oCRWg Config: The official config

#### Steps for reproducing this issue:

1. Start a game
2. Toggle Controller HUD
3. Test what buttons show on screen.

**Comment by Leeo97one** [comment]
Is this confirmed to be a Linux-specific bug?

**Comment by ShrimpKraken** [comment]
its happening to me on windows 10, only showing right stick input

**Comment by Navrin** [comment]
^ Ditto on windows 10, can only see the right stick and the "touch" d-pad inputs.

**Comment by Managor** [comment]
@kisak-valve This can probably be closed as this option doesn't seem to exist in the new BPM.

**Comment by kisak-valve** [comment]
Closing per the last comment.
