### ISSUE TITLE
Specific controller configurations with Steam Link cause all controllers to lock up

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#6883]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/74107881-31663b00-4b7d-11ea-8399-db527df1393a.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/x2BgjfqBsO0
In the video I have one Steam Controller plugged in the actual PC, one Steam Controller plugged in Steam Link and one DS3 paired with Steam Link. Booting the controllers up in a specific order, you can cause all of the controllers to jam up. 
As additional info, the second Steam Controller plugged in the Steam Link is not registered to the current account.
Playing around with this setup in different order, I've also been able to lock up BPM overlay so that it wouldn't update the UI (unable to reproduce) and I've been able to cause the first controller become the second controller even if the first controller was the only one powered up just seconds ago.

#### Steps for reproducing this issue:

1. Plug one Steam Controller to your PC, and one Steam Controller and a DS3 to your Steam Link
2. Have the Playstation Configuration Support be off
3. Start the game with the controller plugged in your PC
4. When in game, start up the DS3
5. Then start up the second Steam Controller plugged to the Steam Link

#### Results
The controller position for the first and second controller will briefly jump back and forth between the first and the second Steam Controller until both of the controllers lock up. None of its bindings, including the Chord binding work.

**Comment by kisak-valve** [comment]
Hello @Managor, are you still experiencing this issue on an up to date system?

**Comment by Managor** [comment]
You'll gonna have to wait a few months before I can get to my PC to retest.

**Comment by kisak-valve** [comment]
No particular hurry. Closing pending feedback.

**Comment by Managor** [comment]
Heh. Forgot this issue completely and recently rediscovered it when looking through my old issues. Just for the record I was not able to repro the issue.
