### ISSUE TITLE
Don't work button "Play Album"  in soundtracks.

### ISSUE THREAD

**Issue by Vladimir-A** [ValveSoftware/steam-for-linux#6884]
#### Your system information

* Steam client version (build number or date): Jan 31 2020, at 01:22:48
* Distribution (e.g. Ubuntu):  "Arch Linux" (64 bit)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Don't work button "Play Album"  in soundtracks. When I press the "Play Album" button, nothing happens in any soundtracks. In "Music Details" button "Play Album" works fine.

#### Steps for reproducing this issue:
1. Choose any soundtrack.
2. Click the "Play Album" button.
3. Nothing happens.

**Comment by kisak-valve** [comment]
Possibly related to #6842.

**Comment by ArekPiekarz** [comment]
I can confirm the issue occurs on my system too. The music player doesn't show up after hitting "Play album" neither on stable nor on the beta client.

However, after you download an album, you can go to the Downloads section, hit Play there and it will put the album in the queue, show the player and play the songs correctly.

Steam client version (build number or date): Feb 11 2020, at 19:27:00
Distribution (e.g. Ubuntu): Xubuntu 19.10 (64 bit)
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes

**Comment by Vladimir-A** [comment]
#### Steam client version (build number or date): Feb 13 2020, at 22:01:12
It works well.
