### ISSUE TITLE
Steam making symlink loop ~/.steam/root -> /home/<Me>/.steam/root after login

### ISSUE THREAD

**Issue by ffiarpg** [ValveSoftware/steam-for-linux#6885]
#### Your system information

* Steam client version (build number or date):  2/10/20
* Distribution (e.g. Ubuntu): KDE Neon
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
~/.steam/root is symlinked to ~/.steam/ so double clicking the root folder doesn't take me anywhere, I can just keep going deeper ~/.steam/root/root/root/ ... etc

Same thing when I navigate with terminal.

**Comment by TTimo** [comment]
Not observing this. `~/.steam/root` links to `~/.local/share/Steam`

I think some setups override the `~/.local/share/Steam` location via XDG_ environment variables? So maybe that's setup in such a way that it causes the symlink loop? In which case this is a system configuration problem, and not a steam problem?

**Comment by meydominic** [comment]
Hi,
I had a similar error. But in my case I found the solution.
You don't have to use the steam-package which is provided in ubuntu ppa.

You should install the .deb from steam webpage.

I found the solution here in reddit:
https://www.reddit.com/r/linux_gaming/comments/ar6llf/steam_location_steam_or_localshare/

So best solution I think is to remove current steam (`sudo apt-get purge steam`) and download and install .deb from steam page:
https://store.steampowered.com/about/

**Comment by TTimo** [comment]
Thank you @meydominic - as you pointed out, please use the official steam-launcher.deb to install Steam on Debian and Debian derivatives.

We just made available a new beta release of the steam installer, which you can download at https://repo.steampowered.com/steam/archive/precise/steam-launcher_1.0.0.62_all.deb

**Comment by ffiarpg** [comment]
Thanks all, uninstalled, renamed .steam and used the new beta installer and it resolved my issue.

**Comment by peon501** [comment]
I do not recommend you to download anything via URLs.
It is Bad Practice.
Stone on valve side.

**Comment by ffiarpg** [comment]
And I would recommend explaining a good practice if you are going to point out a bad one.

**Comment by BETLOG** [comment]
> sudo apt-get purge steam

Is it actually *necessary* to purge it?

Given how steam has both configuration, application, and containers all within it's main directory doesn't a purge completely erase all of that?

Similarly, seeing as steam updates itself pretty much every day; why isnt this one of those 'fixes'?
