### ISSUE TITLE
Library videos not playing (html5app segfault)

### ISSUE THREAD

**Issue by dearlygparted** [ValveSoftware/steam-for-linux#6886]
#### Your system information

* Steam client version (build number or date): Jan 18 2020, at 03:34:03
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Videos from the Steam Library (Steam store videos work fine) fail to play. When pressing play, the pop up appears and then disappears. When running Steam from the terminal, a segmentation fault in the HTML5 Steam app occurs:

`./ubuntu12_64/html5app_steam.sh: line 4: 12311 Segmentation fault      (core dumped) ${DIR}/html5app_steam "$@"`

Other users have reported this issue on the Steam for Linux forum:

https://steamcommunity.com/app/221410/discussions/2/1638675549001453606/

I don't know if it is related to [#4395](https://github.com/ValveSoftware/steam-for-linux/issues/4395) but, in this case, the Steam Runtime is enabled. 

#### Steps for reproducing this issue:

1. Run Steam from the terminal
2. Attempt to play a video from your Steam Library
3. The video doesn't play. Terminal output reveals segfault.

**Comment by kisak-valve** [comment]
Hello @dearlygparted, this issue is already being tracked at #6555. Closing as a duplicate.
