### ISSUE TITLE
Steam can't run in my ubuntu system, can anyone help me?

### ISSUE THREAD

**Issue by cnwz** [ValveSoftware/steam-for-linux#6887]
#### Your system information

* Steam client version (build number or date): 1579321278
* Distribution (e.g. Ubuntu):  ubuntu 19.10 64-bit
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam can't run in my ubuntu system, but it's good in the virtual machine whit the same version.

#### Steps for reproducing this issue:

:~$steam
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mrwu/.steam/ubuntu12_32/steam
[2020-02-05 23:05:10] Startup - updater built Jan 18 2020 03:21:49
SteamUpdateUI: An X Error occurred
X Error of failed request: GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 152 (GLX)
Minor opcode of failed request: 3 (X_GLXCreateContext)
Value in failed request: 0x0
Serial number of failed request: 51
xerror_handler: X failed, continuing
Major opcode of failed request: 152 (GLX)
Minor opcode of failed request: 6 (X_GLXIsDirect)
Serial number of failed request: 52
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-02-05 23:05:10] Checking for update on startup
[2020-02-05 23:05:10] Checking for available updates...
[2020-02-05 23:05:10] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-02-05 23:05:11] Download skipped: /client/steam_client_ubuntu12 version 1579321278, installed version 1579321278
[2020-02-05 23:05:11] Nothing to do
[2020-02-05 23:05:11] Verifying installation...
[2020-02-05 23:05:11] Performing checksum verification of executable files
[2020-02-05 23:05:11] Verification complete

**Comment by kisak-valve** [comment]
Hello @cnwz, what video card / driver version are you using? Can you check if any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

**Comment by cnwz** [comment]
> Hello @cnwz, what video card / driver version are you using? Can you check if any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

Intel Graphics 620 and NVIDIA GeForce MX150. Thinkpad T480. And driver is the latest version.

**Comment by HorstBaerbel** [comment]
It seems like graphics support on your system is not working. Please run `glxinfo` and post the output. Have you installed the nvidia driver? If you have upgraded your system to 19.10 [this](https://askubuntu.com/questions/1185010/how-to-repair-opengl-on-ubuntu-19-10) might help.

**Comment by cnwz** [comment]
[glxinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/4244699/glxinfo.txt).
I've try to run steam today and up-to-date and it's still not running.
mrwu@mrwu-ThinkPad-T480:~$ steam
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/mrwu/.steam/ubuntu12_32/steam
[2020-02-24 21:18:10] Startup - updater built Feb 11 2020 19:26:28
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  52
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-02-24 21:18:10] Checking for update on startup
[2020-02-24 21:18:10] Checking for available updates...
[2020-02-24 21:18:10] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-02-24 21:18:11] Download skipped: /client/steam_client_ubuntu12 version 1581460722, installed version 1581460722
[2020-02-24 21:18:11] Nothing to do
[2020-02-24 21:18:11] Verifying installation...
[2020-02-24 21:18:11] Performing checksum verification of executable files
[2020-02-24 21:18:12] Verification complete

**Comment by kisak-valve** [comment]
Hello @cnwz, 440.33.01 is a nVidia Cuda driver version, and you've encountered #5778. The lack of 32 bit userspace support is a video driver packaging issue.

You could give https://github.com/ValveSoftware/steam-for-linux/issues/5778#issuecomment-575334890 a try.

Closing as a duplicate.
