### ISSUE TITLE
Live Events Won't Play in Steam Client.

### ISSUE THREAD

**Issue by bjwest** [ValveSoftware/steam-for-linux#6889]
#### Your system information

* Steam client version (build number or date): Jan 31, 2020 @ 01:22:48
* Distribution (e.g. Ubuntu): KDE Neon
* Opted into Steam client beta?: [Yes/No]  Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Clicked on 'Soundtrack Sale' in Store page and noticed the live stream window said "Your Web browser does not support the minimum set of features required to watch this broadcast."  Went back to storefront and clicked the Dead Cells Live event and same message in paces of live stream.

This is recent, although I can't say how recent.  I've watched live events in the past but it's been a few updates since.  The only change on my system is that I move Neon to the new 5.x kernel from the official 4.x kernel.

#### Steps for reproducing this issue:

1. Click to watch any live event.
2. Notice error message in place of live steam.
3.  goto 1

**Comment by kisak-valve** [comment]
Hello @bjwest, this issue is already being tracked at #6780. Closing as a duplicate.

**Comment by bjwest** [comment]
Just recieved today's (Feb 11, 1010 @ 19:27:00) update and the issue is fixed.
