### ISSUE TITLE
I can not write a message through a friend’s page

### ISSUE THREAD

**Issue by cucumb3r-user** [ValveSoftware/steam-for-linux#6891]
#### Your system information

* Steam client version: February 12, 12:26 Moscow time
* Distribution: Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Going to a friend’s page in the Steam application, I can’t write a message to a friend, clicking on “Write a message” does not work, but the “More...” button works.

#### Steps for reproducing this issue:

1. Friend page
2. Click to 'write a message'

**Comment by kisak-valve** [comment]
Possibly related to #6842.

**Comment by kisak-valve** [comment]
Hello @cucumb3r-user, please retest with the current Steam client beta update.

**Comment by cucumb3r-user** [comment]
It works great, now after the 'write message' button a window appears with a friend where I can write a message.
