### ISSUE TITLE
Client crashed and quit when trying to right click a game

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#6895]
#### Your system information

* Steam client version (build number or date): Feb 11
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I right clicked a game, when to hit properties and the whole client vanished.

Log: https://gist.github.com/LiamDawe/80b917222fce614793bc2e9d106fc2c5
DMP: https://gofile.io/?c=H4iUyr

**Comment by kisak-valve** [comment]
Hello @LiamDawe, this issue is already being tracked at #6757. Closing as a duplicate.
