### ISSUE TITLE
VR games not starting if SteamVR is already running

### ISSUE THREAD

**Issue by Matombo** [ValveSoftware/steam-for-linux#6896]
#### Your system information

- Distribution: Manjaro
- SteamVR version: 1.9.16 & Beta 1.10.3
- Steam client version: Feb 11 2020, at 19:27:00
- Opted into Steam client beta?: No
- Graphics driver version: Mesa 19.3.3 (LLVM 9.0.1)
- Gist for SteamVR System Information: https://gist.github.com/Matombo/e89867c0e72923cedc43f29beae2d93e
- Gist for System Information: https://gist.github.com/Matombo/840bf14f73629bd9238f94870020f425

#### Please describe your issue in as much detail as possible:
Same as https://github.com/ValveSoftware/SteamVR-for-Linux/issues/300 but it seems to be steam client related and not Proton+SteamVR so i repost it here.

If SteamVR is running, several games ~run through proton~ (some proton games still run so it doesn't seem to be proton related) don't start with the error message in the steam console output:
```
GameAction [AppID 692690, ActionID 6] : LaunchApp failed with WaitingOpenVRAppQuit with "104"
GameAction [AppID 692690, ActionID 6] : LaunchApp changed task to Failed with ""
```
Starting the games without steamvr running starts steamvr and the game as expected.

Tested SteamVR versions: Beta 1.10.3, 1.9.16

Affected games example: The Gallery - Episode 1, The Gallery - Episode 2, Dance Collider

NOT affected games example: SUPERHOT VR

This issue showed up at the same time as this issue: https://github.com/ValveSoftware/steam-for-linux/issues/6892 The affected games however do not match (see for example The Gallery EP 1 and 2)

#### Steps for reproducing this issue:

1. Start Steam VR
2. Start one of the affected games
3. Game immediatly quits, steam console output says
```
GameAction [AppID 692690, ActionID 6] : LaunchApp failed with WaitingOpenVRAppQuit with "104"
GameAction [AppID 692690, ActionID 6] : LaunchApp changed task to Failed with ""
```

**Comment by Matombo** [comment]
Budget Cuts is unplayable because of this bug: If I have SteamVR not running and start Budget Cuts I get the permanent index controller rumbling bug. If SteamVR is already running (without the constant rumbling valve index controller thanks to a workaround) Buget Cuts won't launch.

**Comment by StefanTT** [comment]
The rumble on start also happens for Windlands 2 and Karnage Chronicles. Others probably too.

**Comment by Matombo** [comment]
> _Edit_
> Further tests show that the rumble does not happen with the release version of SteamVR.

Sadly that doesn't work for me

**Comment by Matombo** [comment]
found a workaround: directly start the games from the exe and not from steam.
For proton games this is a little plot complicated. The template goes like this

STEAM_COMPAT_DATA_PATH=<path>/steamapps/compatdata/<game_id>/ <path>/steamapps/common/Proton\ 5.0/proton run <path>/mnt/Mint/Steam/steamapps/common/<game_folder>/<game_exe>

ofc you need to replace the <> acording to your steam folder

**Comment by Matombo** [comment]
Both this bug and https://github.com/ValveSoftware/steam-for-linux/issues/6892 do not happen when steam is started in offline mode.

However for me they reapear as soon as i go online again.

**Comment by Matombo** [comment]
The bug seems to be gone with the latest beta update.
However https://github.com/ValveSoftware/steam-for-linux/issues/6892 is still here.

**Comment by pop2010** [comment]
I still have that bug.

To avoid it, I start the game, and while it's preparing to be launched I start Steam VR.

Another interesting thing to note is that if I start a non-steam game (pointing to an exe with proton), it works correctly.

**Comment by pop2010** [comment]
Sorry, I'm completely wrong. I installed the beta client and it indeed works now, I thought I was on a SteamVR git.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2020-03-26](https://store.steampowered.com/news/59842/) Steam client update.
