### ISSUE TITLE
remote play : The streaming client exited unexpectedly

### ISSUE THREAD

**Issue by jape42** [ValveSoftware/steam-for-linux#6897]
#### Your system information

* Steam client version (build number or date): Feb 13 2020
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Tried to stream stardew valley fails with above message

#### Steps for reproducing this issue:

1. select remote host from library
2. click on stream
3. error is displayed

[error.log](https://github.com/ValveSoftware/steam-for-linux/files/4204732/error.log)

------

It appears to be trying to run .exe which doesn't exist?

[0214/084800.669339:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
sh: 1: /home/jape/.steam/ubuntu12_32/streaming_client.exe: not found
sh: 1: /home/jape/.steam/ubuntu12_32/streaming_client.exe: not found
[413150]Non-Steam Controller Configs Enabled: 1
sh: 1: /home/jape/.steam/ubuntu12_32/streaming_client.exe: not found

**Comment by medianode** [comment]
I found the same issue, as a work around you can just rename the file "~/steam/ubuntu12_32/streaming_client" to "~/steam/ubuntu12_32/streaming_client.exe" and it runs.

**Comment by tehfiuture** [comment]
> I found the same issue, as a work around you can just rename the file "~/steam/ubuntu12_32/streaming_client" to "~/steam/ubuntu12_32/streaming_client.exe" and it runs.

This worked for me, Thank You

**Comment by jape42** [comment]
seems to be fixed in feb 21 beta build.

**Comment by kisak-valve** [comment]
Closing per the last comment.
