### ISSUE TITLE
Missing the following 32-bit libraries,

### ISSUE THREAD

**Issue by shepjack** [ValveSoftware/steam-for-linux#6899]
#### Your system information

* Steam client version (build number or date): Where do I find this?
* Distribution (e.g. Ubuntu): Ubuntu Studio with Ubuntu 19.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Tried to play a game, results as described.  In addition, I find one of the steam directories, keeps setting itself up over & over.  6 deep & counting at this point.

#### Steps for reproducing this issue:

1. Start a game from an icon.
2. Receive error message: You are missing the following 32-bit libraries, and Steam may not run:
libXtst.so.6
libgtk-x11-2.0.so.0
libgdk_pixbuf-2.0.so.0
libva.so.2
libvdpau.so.1
libva.so.2
libva-x11.so.2.
3. failed to load steamui.so

**Comment by kisak-valve** [comment]
Hello @shepjack, can you copy `/tmp/dumps/<username>_stdout.txt` or `~/.steam/error.log` to a [gist](https://gist.github.com) and include a link to it here?

**Comment by shepjack** [comment]
This what you want?  I also installed Steam from the Website for Steam.  Chose Linux Option.

<script src="https://gist.github.com/shepjack/8f1785ecc5e3a0b6adf1da981a1bd502.js"></script>

**Comment by kisak-valve** [comment]
Looks like the Steam runtime didn't get setup for some reason. Does running `steam --reset` from a terminal help?

If that doesn't make a difference, you can move the entire `~/.local/share/Steam` folder somewhere out of the way and re-run steam to re-bootstrap it.

**Comment by shepjack** [comment]
Wow, that worked.  I love the Linux desktop variations but I'm still trying to wrap my head around how it works as opposed to DOS,  Thanks I owe you.
