### ISSUE TITLE
Mature images are blurred even with the settings on the preferences turned off

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/steam-for-linux#6904]
#### Your system information

* Steam client version (build number or date): 11-02-2020
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Images with: "This image has been blurred, as it may not be appropriate for all audiences." are always blurred even with the settings turned off for blurring, turning the blur on and them off in the settings removes the blur only temporarily.

#### Steps for reproducing this issue:

1. Turn off the blurring for mature pics
2. Mature images on the activity feed should not have blur

**Comment by TTimo** [comment]
Can you confirm that it's specific to Linux?

**Comment by monterrr** [comment]
Also happens on steam for android, had this issue for as long as I remember.

**Comment by andreldmonteiro** [comment]
This was not a bug after all, was a mistake of mine.
