### ISSUE TITLE
Bars of short horizontal lines

### ISSUE THREAD

**Issue by nunyabidnes** [ValveSoftware/steam-for-linux#6905]
* Steam client version (build number or date): 1.0.0.61-7
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

When I launch Steam, there are bars of short vertical lines appearing, as shown in the attached screenshot.
![Steam](https://user-images.githubusercontent.com/48492119/74605289-c775f600-5094-11ea-8b49-82b07a895b8b.png)

Here are the details of my system:
System:
  Kernel: 5.4.18-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 
  Desktop: Xfce 4.14.2 tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM 
  Distro: Manjaro Linux 
Machine:
  Type: Laptop System: HP product: HP Laptop 15-dy1xxx v: N/A 
  serial: <root required> Chassis: type: 10 serial: <root required> 
  Mobo: HP model: 86C9 v: 56.31 serial: <root required> UEFI: AMI v: F.09 
  date: 12/20/2019 
Battery:
  ID-1: BAT0 charge: 42.3 Wh condition: 41.9/41.9 Wh (100%) volts: 12.9/11.3 
  model: HP Primary serial:   status: Unknown 
CPU:
  Topology: Quad Core model: Intel Core i5-1035G1 bits: 64 type: MT MCP 
  arch: Ice Lake rev: 5 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 19048 
  Speed: 933 MHz min/max: 400/3600 MHz Core speeds (MHz): 1: 1044 2: 591 
  3: 1011 4: 699 5: 894 6: 1007 7: 1069 8: 927 
Graphics:
  Device-1: Intel vendor: Hewlett-Packard driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:8a56 
  Display: x11 server: X.Org 1.20.7 driver: intel unloaded: modesetting 
  alternate: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics (Ice Lake 4x8 GT1) 
  v: 4.6 Mesa 19.3.4 compat-v: 3.0 direct render: Yes 
Audio:
  Device-1: Intel vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
  bus ID: 00:1f.3 chip ID: 8086:34c8 
  Sound Server: ALSA v: k5.4.18-1-MANJARO 
Network:
  Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter 
  vendor: Hewlett-Packard driver: rtl8821ce v: N/A port: 3000 
  bus ID: 01:00.0 chip ID: 10ec:c821 
  IF: wlo1 state: up mac: 40:23:43:5b:72:e5 
  IP v4: 192.168.1.210/24 type: dynamic noprefixroute scope: global 
  broadcast: 192.168.1.255 
  IP v6: fe80::80da:18a8:690e:5c87/64 type: noprefixroute scope: link 
  WAN IP: 173.170.156.138 
Drives:
  Local Storage: total: 476.94 GiB used: 15.29 GiB (3.2%) 
  ID-1: /dev/nvme0n1 vendor: Intel model: SSDPEKNW512G8H size: 476.94 GiB 
  speed: 31.6 Gb/s lanes: 4 serial: BTNH933416VQ512A 
RAID:
  Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci 
  v: 3.0 bus ID: 00:17.0 chip ID: 8086.282a 
Partition:
  ID-1: / size: 371.44 GiB used: 15.22 GiB (4.1%) fs: ext4 dev: /dev/dm-0 
Sensors:
  System Temperatures: cpu: 43.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 226 Uptime: 23h 33m Memory: 15.40 GiB used: 3.48 GiB (22.6%) 
  Init: systemd v: 242 Compilers: gcc: 9.2.0 Shell: bash v: 5.0.11 
  running in: xfce4-terminal inxi: 3.0.37 

#### Steps for reproducing this issue:
Open steam.

**Comment by kisak-valve** [comment]
Hello @nunyabidnes, it may be worthwhile to also mention this to your video driver vendor.

**Comment by nunyabidnes** [comment]
> Hello @nunyabidnes, it may be worthwhile to also mention this to your video driver vendor.

Good idea. There seems to be two possible teams responsible: DRM Kernel and 3D Mesa. I'm not sure which would be the best place to start, can you provide guidance? In the meantime, I'll try to figure it out.

**Comment by nunyabidnes** [comment]
FYI: I switched from video-linux to video-modesetting, and the issue is resolved.
