### ISSUE TITLE
Controller Configuration button issue

### ISSUE THREAD

**Issue by Smeejo** [ValveSoftware/steam-for-linux#6907]
#### Your system information

* Steam client version (build number or date): Feb 11 2020, at 19:27:00
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
A few days ago while I was playing American Truck Simulator I decided I wanted to remap a few of the keys on my xbox 360 controller. Set some of them up so that I can have 2 commands set to one button. In order to do this I have to use the "controller configuration" button on library page for the game I'm playing. When I try to click on the Controller Configuration button nothing happens. I should be getting a popup that shows my controller and all my current binds but it doesn't show up.

I've tried closing steam and relaunching it. Tried restarting my computer. Checked for all updates Tried every game I have installed, tried right clicking and selecting controller configuration, left clicking the game and clicking controller configuration on the game page itself.

If I click on "steam" in the top left and click settings then go down to controller everything in general controller settings, big picture configuration, desktop configuration, and guide button chord configuration work perfectly. I've gone into big picture mode and check controller settings in there and again everything works perfectly. Just for some reason the "controller configuration" button for the games that lets you do keybinds does not work.

The games I've tested this on are:
1) american truck simulator
2) dragonball z: kakarot
3) rimworld
4) rise of the tombraider
5) star wars: battlefront 2 classic (2005)

I Submitted a ticket to steam support on steam itself and was told:

> Hello and thank you for your patience,
> Unfortunately, we are unable to troubleshoot your issue within our testing environment.
> 
> If you wish to attempt to run Steam on a different distribution, it's best that you use Github to discuss them with our developers and other Linux users.
> 
> Steam Support for Linux has migrated over to GitHub, you can report your own bug and work directly with the developers here:
> 
> https://github.com/ValveSoftware/steam-for-linux/issues
> 
> Please let us know if you have further questions or concerns.
> 
> Excited to hear from you again!
> Awase
> 

My inxi -F

> Kernel: 5.4.12-144.current x86_64 bits: 64 
  Desktop: Budgie 10.5.1 Distro: Solus 4.1 
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X470-F GAMING v: Rev X.0x 
  serial: <root required> UEFI: American Megatrends v: 5220 date: 09/12/2019 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 2600X bits: 64 type: MT MCP 
  L2 cache: 3072 KiB 
  Speed: 2690 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 3392 2: 2405 
  3: 2878 4: 2599 5: 2407 6: 2966 7: 3013 8: 2464 9: 2540 10: 2328 11: 2649 
  12: 4135 
Graphics:
  Device-1: NVIDIA GM107 [GeForce GTX 750 Ti] driver: nvidia v: 440.44 
  Display: x11 server: X.Org 1.20.6 driver: nvidia 
  resolution: 1920x1080~75Hz 
  OpenGL: renderer: GeForce GTX 750 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 440.44 
Audio:
  Device-1: NVIDIA driver: snd_hda_intel 
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.12-144.current 
Network:
  Device-1: Intel I211 Gigabit Network driver: igb 
  IF: enp6s0 state: up speed: 100 Mbps duplex: full mac: 04:d4:c4:57:dc:96 
Drives:
  Local Storage: total: 465.76 GiB used: 92.49 GiB (19.9%) 
  ID-1: /dev/sda vendor: Crucial model: CT500MX500SSD1 size: 465.76 GiB 
Partition:
  ID-1: / size: 453.31 GiB used: 92.38 GiB (20.4%) fs: ext4 dev: /dev/sda3 
  ID-2: /boot size: 487.3 MiB used: 113.2 MiB (23.2%) fs: vfat 
  dev: /dev/sda1 
  ID-3: swap-1 size: 3.73 GiB used: 512 KiB (0.0%) fs: swap dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 55.1 C mobo: N/A gpu: nvidia temp: 31 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 40% 
Info:
  Processes: 275 Uptime: 3d 4h 50m Memory: 15.61 GiB used: 2.30 GiB (14.7%) 
  Shell: bash inxi: 3.0.37 

#### Steps for reproducing this issue:

1. Open steam
2. right click on a game and go to manage
3. click controller configuration

Alternatively

1. Open steam
2. left click on a game
3. left click controller configuration

I've included a screenshot of the button in question.
![controller config](https://user-images.githubusercontent.com/30884919/74607250-19664e00-508c-11ea-9140-046d307344d4.jpg)

**Comment by dubigrasu** [comment]
AFAIK this was fixed in the beta client.

**Comment by Smeejo** [comment]
23 days, no fix, no word on a fix, no update, nobody assigned to the case. Is there a better place to get help that I don't know about?

**Comment by kisak-valve** [comment]
Hello @Smeejo, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
