### ISSUE TITLE
Steam client losing connection in kubuntu 19.10

### ISSUE THREAD

**Issue by jasoncollege24** [ValveSoftware/steam-for-linux#6909]
#### Your system information
CPU - Intel core i7 4790 @3.6GHtz (4 cores, 8 threads)
RAM - 32GB Dual-Channel
Graphics - NVidia GeForce GTX 1080 (8GB) with proprietary driver 435
Network - Gigabit Ethernet port, with autonegotiaton enabled, and gigabit internet
Disk space - LOTS

* Steam client version (build number or date): Feb 11 2020, at 19:27:00
* Distribution (e.g. Ubuntu): Kubuntu 19.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (checked daily)

#### Please describe your issue in as much detail as possible:
Expected behavior: Steam client remains online in friend list, store, overlay, and online games for as long as it's open, if not started in offline mode.

Actual behavior: Steam client consistently loses connection, after a time. Restarting the client restores connection temporarily.

This happens, whether installed via the apt package manager, or a .deb download from the steam website.

#### Steps for reproducing this issue:

1. Install Steam
2. Open Steam, and login
3. Use steam for a while (includes installing/uninstalling/playing games, using the store, or friend list)

Need more info? Let me know. Thanks.

**Comment by sharkguto** [comment]
its working fine using ubuntu 18.04.... maybe can be a networking issue from your side.

Better you provide some hardware information with dmidecode, lspci,... 

try to issue `netstat -s | egrep -i 'loss|retran'` ... could help

**Comment by jasoncollege24** [comment]
This is the only thing having any connection issues. All other internet software, and devices are working as intended across the entire network, including this machine. Steam connection works normally in Wine, and in Windows 10 on the same machine.

Results of dmidecode [here](https://pastebin.com/RL6qLyBv)

Results of lspci [here](https://pastebin.com/xF00yQKt)

Results of the netstat is below
`    138894 segments retransmitted
    TCPLostRetransmit: 92130
    11 fast retransmits
    TCPLossProbes: 23394
    TCPLossProbeRecovery: 14
    TCPSynRetrans: 428
`

**Comment by jasoncollege24** [comment]
updating this issue, because it's still happening, even after changing operating systems.
 this didn't happen on an install of kubuntu 19.04, or the first install of 19.10 (even when that OS crashed), but it started happening on a second install of 19.10, and now in Pop_OS 19.10.

**Comment by listen1379** [comment]
Are you using wifi or ethernet? If you have a modem, see if you can check its diagnostic logs for any recent messages. For example if it renegotiates with DSLAM/CMTS/OLT regularly, could indicate Internet connection problem. Could also be overheating router or modem.

You can also check `dmesg` and `journalctl` for messages about your wifi/ethernet adapter. I imagine I217 is well supported being an Intel NIC, but sometimes Intel wifi can misbehave. For example I have had Intel 6205 lose connection but report to OS that it was connected.

`journalctl -u NetworkManager -b` messages since last boot
`journalctl -u NetworkManager -n 100` last 100 messages

**Comment by jasoncollege24** [comment]
it's looking like the issue resolved itself. It kept happening for a few more days, then I've seen it maybe once in the last 2 weeks. Thanks for the help.

**Comment by kisak-valve** [comment]
Hello @jasoncollege24, have you seen this issue since your last comment?

**Comment by jasoncollege24** [comment]
Not that I can recall, but I'm also using 22.04 now. Still want me to test, despite version change?

**Comment by kisak-valve** [comment]
Thanks for the feedback. Since it's working for you there's no real point.
