### ISSUE TITLE
Steam spamming "type unknown not a basic type", dbus crash - fixed in beta

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#6911]
#### Your system information

* Steam client version (build number or date): Feb 15 2020
* Distribution (e.g. Ubuntu): Linux Mint 19.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Like title says ; after this beta client update Steam behaves like that.

#### Steps for reproducing this issue:

1. Opt in to Steam beta
2. After booting the pc try launching Steam ( sometimes it doesn't act problematic but consistent enough for me to open a report)
3. Observe

Crash dumps + log:

[crash dumps and log.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/4215357/crash.dumps.and.log.tar.gz)

**Comment by kisak-valve** [comment]
For reference, the attached assert is a SIGSEGV in libdbus-1.so.3.5.8 and the crash*.dmp are DUMP_REQUESTED in crashhandler.so.

**Comment by grahammitchell** [comment]
I had something that might be related. Came home from work to find my root partition was full and the culprit was /tmp/dumps/USERNAME_stdout.log

Some interesting stuff up top and then 400GB of just

```
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
type unknown not a basic type
```

**Comment by Leopard1907** [comment]
Happened again.

[dump+logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/4268487/dump%2Blogs.tar.gz)

**Comment by Leopard1907** [comment]
It still happens.

[29.03.2020 dumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/4398969/29.03.2020.dumps.tar.gz)

**Comment by Leopard1907** [comment]
Fwiw , i didn't experience the issue since update arrived at April 2. 

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2083419329411983618

`Fixed dbus assertion and possible crash at startup`

**Comment by TTimo** [comment]
Thanks @Leopard1907  - the fix is in Steam Beta client and not available in production yet. I am keeping this issue open until fully released.

**Comment by glubsy** [comment]
I've just experienced the problem by starting steam-runtime on Arch Linux. (twice in a row) 
Then started with steam-native and didn't have the issue. Started steam-runtime once more, no issue anymore either. 

Not using the steam beta client. [System specs](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/58898bc4ddbb3d0af781e7cfb038d75626ecc002).

**Comment by ziabice** [comment]
I'm experiencing this same problem since some days on Manjaro.

I'm using the regular Steam client, not the Beta. Version build: 4 apr 2020, Steam package version: 1586022601

The issue is completely random, I don't have found a way to trigger it.

**Comment by kisak-valve** [comment]
Closing as fixed in the 2020-04-28 Steam client update.
