### ISSUE TITLE
Microstutters every second

### ISSUE THREAD

**Issue by kilmanio** [ValveSoftware/steam-for-linux#6912]
#### Your system information

using nvidia-440.59

* Steam client version (build number or date): feb 11 2020
* Distribution (e.g. Ubuntu): void
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
My steam client and some games hang every second.
I've had this issue for ~10 days.
The hang only lasts for a little while (tens / hundred ms), but it makes games unplayable.
I have encountered this in CS;GO, and 7Days to die, while Warframe runs perfectly fine.
I have tried different settings in the nvidia control panel, and switched my cpu frequency governor to 'performance', but nothing has fixed this so far.

**Comment by kilmanio** [comment]
I have uninstalled 'xboxdrv' and blacklisted the 'nouveau' driver.
Issue _seems_ to be gone now.

**Comment by TTimo** [comment]
it would be interesting to know if the fix was actually the removal of xboxdrv, it's likely it was just nouveau

**Comment by OvermindDL1** [comment]
I was getting microstutters just yesterday across my whole GUI (AMD, no xboxdrv) until steam rebooted for an update, it's something about steam running...

**Comment by fvguilherme** [comment]
> I have uninstalled 'xboxdrv' and blacklisted the 'nouveau' driver.
> Issue _seems_ to be gone now.

Here I can't launch CS: GO when `xbovdrv.service` is enable. Others games, like Resident Evil 2, runs smoothly, but I can feel some stutters, for sure. This happens on both package from repository and Flatpak. Proton is enable, if that is important.

System info:

Steam v.1.0.0.61-4;
NVIDIA 440.64-8
Operating System: Arch Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
Kernel Version: 5.5.13-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7,7 GiB

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by OvermindDL1** [comment]
Can't say I've noticed it in a long time now.  Steam currently has been up about a week and it's not stuttering currently either.  It's also surprisingly memory light compared to electron apps that are also running.

**Comment by kisak-valve** [comment]
Thanks for the feedback @OvermindDL1. Closing as outdated.
