### ISSUE TITLE
Game Progress Lost upon installing game on 2nd machine

### ISSUE THREAD

**Issue by audirs4** [ValveSoftware/steam-for-linux#6916]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 19.10 & Pop!_OS 19.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
About a year ago, I started playing Horizon Chase Turbo, and had at least 25% of the game completed. This was done on my laptop running Pop!_OS, likely 18.10 at the time. Some months ago, I decided to play the game on my Desktop running Ubuntu (likely 19.04 at the time). After installing it and launching the game, it showed no game progress. My immediate thought was, oh bummer, the game doesn't have Steam Cloud, oh well. But, when I went back to play it on the laptop, it was now also missing the game progress. The game lists on its Steam Store page that it does support Steam Cloud.

This past weekend, I was playing another game, Mu Complex on my laptop. I was working on the final achievement for getting all hints, which in some cases requires sitting for 30 minutes to get the ability to request the hint. So, I decided to install the game on my Desktop to do this. I loaded up the game, and it wanted me to start a new game. I checked the game store, and saw it did not support Steam Cloud. So I removed it and decided to just finish it on the laptop. Booted up the laptop and the progress saves were all gone. I had played and used the progress just the day before.

#### Steps for reproducing this issue:

1. Install game on a computer. Play for a bit getting some progress in the game.
2. Install game on 2nd computer. Play and see no progress completed.
3. Go back to 1st computer and see progress has been lost there as well.

**Comment by byte1024** [comment]
Would think Valve may need something more to this. I often install a game on two different OSs and the cloud saves have been there always.

Maybe two Linux OS installs is where the problem could be. I almost never have a need to do that for games.

**Comment by audirs4** [comment]
> 
> 
> Would think Valve may need something more to this. I often install a game on two different OSs and the cloud saves have been there always.
> 
> Maybe two Linux OS installs is where the problem could be. I almost never have a need to do that for games.

It has worked in the past for me as well. But for some reason, I've seen the issue with both of these titles. So, it is likely not a huge common issue, but something more specific. Hoping we can figure out why to fix it and prevent others from having similar issues.

If you know of anything else I should provide,  please let me know. I just tried best to explain how it happened. I don't know what else can help besides that.

**Comment by kisak-valve** [comment]
Hello @audirs4, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
