### ISSUE TITLE
Possible that non steam games not react like steam games for launch option?

### ISSUE THREAD

**Issue by kadogo** [ValveSoftware/steam-for-linux#6918]
#### Your system information

* Steam client version (build number or date): February 11 2020 19h27
* Distribution (e.g. Ubuntu): Debian Buster
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

My system link: https://gist.github.com/kadogo/a72b612e48ede28a5bd7495b268de99d

#### Please describe your issue in as much detail as possible:

I filled my non steam game option like in my screenshot

![Capture d’écran_2020-02-20_02-08-40](https://user-images.githubusercontent.com/5759396/74891015-0c947380-5386-11ea-86c8-46262c09b180.png)

![Capture d’écran_2020-02-20_02-09-30](https://user-images.githubusercontent.com/5759396/74891026-11592780-5386-11ea-9e20-99ab96e61401.png)

I add `printf "%s %s\n" "$here/pressure-vessel/bin/pressure-vessel-unruntime" "$@"` in /home/user/.steam/steam/steamapps/common/SteamLinuxRuntime/run-in-scout before the exec for seeing the command that launch the game

#### Steps for reproducing this issue:

1. I launch my non steam game and I see the next result in my terminal

```
/home/user/.steam/steam/steamapps/common/Dead Cells/start.sh DRI_PRIME=1
%command%
```

2.  I did the same test with another game (Steam game this time)

![Capture d’écran_2020-02-20_02-14-54](https://user-images.githubusercontent.com/5759396/74891250-d0154780-5386-11ea-9eed-f179e8fb1fca.png)

```
/home/user/.steam/steam/steamapps/common/SteamLinuxRuntime/pressure-vessel/bin/pressure-vessel-unruntime --
/home/user/.steam/steam/steamapps/common/CrossCode/CrossCode --in-process-gpu
--startedFromSteam 
```

I think that non steam games interpret the launch options like something to be added after the normal command.

If I can help with other test let me know.

Cheers.

**Comment by kisak-valve** [comment]
Hello @kadogo, sounds like you've encountered #6046. Closing in favor of the existing issue report.
