### ISSUE TITLE
Steam client erased game's local files

### ISSUE THREAD

**Issue by madsonviana** [ValveSoftware/steam-for-linux#6920]
#### Your system information

* Steam client version (build number or date): Feb 11 2020, at 19:27:00
* Distribution (e.g. Ubuntu): Pop!_OS 19.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I tried to play No Man's Sky using the Steam Linux Runtime as the compatibility tool.
_expected_: Play the game
_happens_: The Steam client erased all game's local files.

P.S. I had the same issue in another game (SCUM).

#### Steps for reproducing this issue:

1. On Linux download No Man's Sky game;
2. Force Steam Linux Runtime as the compatibility tool;
3. Try to start the game.

**Comment by kisak-valve** [comment]
Hello @madsonviana, this issue is already being tracked at #5901, #5745, https://github.com/ValveSoftware/steam-runtime/issues/200. Closing as a duplicate.
