### ISSUE TITLE
Steam beta recent update made streaming to Steam Link unusable

### ISSUE THREAD

**Issue by playeronlinux** [ValveSoftware/steam-for-linux#6921]
#### Your system information

* Steam client version (build number or date): latest beta is broken. "Feb 11 2020, at 19:27.00" (stable) works
* Distribution (e.g. Ubuntu): Debian 10
* Opted into Steam client beta?: [Yes/No] Yes & No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Within last two weeks streaming to Steam Link performance became so bad, that it's impossible to play games or stream videos. Steam Link keeps showing the "poor connection" icon despite being connected via ethernet cable. Opting out of Steam beta build fixed the issue, so this seems to be an issue with a recent Steam beta update.

#### Steps for reproducing this issue:

1. Opt in to Steam beta
2. Stream a game or a video to Steam Link

**Comment by BigB86** [comment]
I am also experiencing this same exact issue. I'm going to try and opt out of Steam Beta to see if this fixes the issue and will report back. I have a windows host on the same network that streams flawlessly. 
I'm using an Nvidia shield with the Steam Link Android app.

I do a stream network test on the Windows host and the test shows 100 MB/s. I do a stream network test on the Ubuntu host and only shows 5 MB/s and lags to the point of not being playable at all. I would love to get this issue fixed as my more powerful machine is running Ubuntu. Are there any logs you will to address the issue @kisak-valve ?

I would be happy to help to get this issue resolved.

**Comment by kisak-valve** [comment]
Hello @playeronlinux, @BigB86, are either of you still experiencing this issue on an up to date system?

**Comment by playeronlinux** [comment]
@kisak-valve with "an up to date system", do you mean Steam Beta, or stable?

**Comment by playeronlinux** [comment]
Tested with:

Beta participation: Steam Beta Update

About Steam (please make this copy-pastable!):

> Steam client application
> Built: Jul 14 2022, at 05:06:28
> Steam API: v020
> Steam package versions: 1657838689

Apart from still suffering from #4351 and somewhat regular poor connection icons and streaming freezes, Steam Beta streaming seems to be as good (and bad) as it was before opening this issue, so I guess whatever was broken has been fixed.

Leaving the issue open until @BigB86 can verify as well.

**Comment by kisak-valve** [comment]
Thanks for retesting @playeronlinux, closing.
