### ISSUE TITLE
Feature Request: Could you please add a feature of logging frame rate and timestamp into files?

### ISSUE THREAD

**Issue by bigface008** [ValveSoftware/steam-for-linux#6924]
#### Your system information

* Steam client version (build number or date): 1581460722
* Distribution (e.g. Ubuntu): Ubuntu 18.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I'm trying to logging frame rate of several games into files on my Ubuntu. I did find that the Steam client offer a setting to show fps(frame rate) on the screen during the game play, but there seems to be no settings to write those information into files. As you know, the program [voglperf](https://github.com/ValveSoftware/voglperf) that was used to log frame rate had been stopped to develop for a long time, and many people try to get log by voglperf failed to run it properly. **Could you please add the feature that log frame rate and timestamp into specified files?** It will be very beneficial to testing/benchmarking.

Thank you very much!

**Comment by kisak-valve** [comment]
Hello @bigface008, this feature request is already being tracked at #4460. Closing as a duplicate.
