### ISSUE TITLE
Steam beta client fills disk drive with huge error log and resets client settings

### ISSUE THREAD

**Issue by cwchaban** [ValveSoftware/steam-for-linux#6925]
System information:
* Steam client: February 21, 2020
* Distribution: Linux Mint Cinnamon 19.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Steam client continues to fill up error log until the disk is full. After deleting the 100GB error log and restarting, the steam client settings are reset to defaults and some Steam Play titles are marked as uninstalled and must be re-installed.

I'm sorry I can't give you the errors that were generated because I had to delete the error log to get the client working again.

This has happened twice in the past two weeks so the problem was there previous to the Feb 21st update.

I have since switched back to the normal steam client without the same issue but it has only been a short amount of time.

**Comment by kisak-valve** [comment]
Hello @cwchaban, this issue is already being tracked at #6901. Closing as a duplicate.
