### ISSUE TITLE
Xbox one s controller does not work with usb after firmware update

### ISSUE THREAD

**Issue by blastermaster77** [ValveSoftware/steam-for-linux#6926]
#### Your system information

* Steam client version (build number or date): 1582328676
* Distribution:Ubuntu 19.10
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:

Xbox one s controller buttons not working but is reconized by steam after firmware update in a win10 machine. X( 

#### Steps for reproducing this issue:

1. Update xbox one s firmware with microsfot firmware update app
2. Connect and it sees it but no buttons work only rumble
3.

**Comment by hajnal-endot** [comment]
If you're still having this issue: check if your controller is plugged in via a USB hub.  Yes, even a powered one might not give enough juice.
