### ISSUE TITLE
steam hangs in xubuntu 18.04

### ISSUE THREAD

**Issue by MersadAkbari** [ValveSoftware/steam-for-linux#6928]
### System information 
_Xubuntu and steam is lastest version_
_Nvidia GT610_

### Problem
this problem happens to me after updating xubuntu
when i write steam in terminal i see this :

> Running Steam on ubuntu 18.04 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> Installing breakpad exception handler for appid(steam)/version(0)

and when i re installed the steam i saw this :
>ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
>[2020-02-26 03:33:30] Startup - updater built Nov 23 2016 01:05:42
>SteamUpdateUI: An X Error occurred
>X Error of failed request:  BadValue (integer parameter out of range for operation)

### i tried
1 - `sudo apt update`
2 - `sudo apt upgrade`
3 - install steam from official site with .deb file
4 - install steam from apt

**Comment by kisak-valve** [comment]
Hello @MersadAkbari, does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

**Comment by MersadAkbari** [comment]
Hi @kisak-valve , thanks for your help
i reboot the system and i see the problem is fixed . now i am log in to my steam account :D
