### ISSUE TITLE
Problem with steam input and steam overlay in games

### ISSUE THREAD

**Issue by Preceptus** [ValveSoftware/steam-for-linux#6934]
#### Your system information

* Steam client version (build number or date): Latest
* Distribution (e.g. Ubuntu): Arch linux/manjarowish distro
* Opted into Steam client beta?: [Yes] 
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Game: Warframe, probably other games as well, but warframe uses complicated controller config
Problem: steam controller or DS4 stuck in Launcher layer. 
Warframe has many layers like launcher, ingame, melee, menu etc . 
They should all automatically switch as i use functions in the game. However the controller config is always stuck in Launcher layer. This is using DE official config, any config that uses these layers is stuck on the first one(in this case Launcher layer).
Describe what you _expected_ should happen and what _did_ happen.
I expect for it to work as it did back at windows, automatic layer switching and all the modeshifts etc working.
Additionally i noticed that steam has its inputs, and the game uses its ones as well. 
So since the game has fire weapon key binded to trigger, if you in BPM change it to something else, it still fires.
Ive been looking for help for 2 weeks now, hard to fix this problem. Posted on manjaro forums, steam for linux and even warframe forums.
#### Steps for reproducing this issue:

1. Start steam in bpm mode to be sure, might need to force steam input and overlay. 
2. Check warframe controller config settings, select it to be Official Warframe config by Digital Extremes. 
3. Log into game and find out you are stuck with the launcher layer and its unplayable like this.

**Comment by kisak-valve** [comment]
Hello @Preceptus, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-592942595.
