### ISSUE TITLE
Arch - glXChooseVisual failed

### ISSUE THREAD

**Issue by reactormonk** [ValveSoftware/steam-for-linux#6937]
#### Your system information

* Steam client version (build number or date): 1581449474
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After an update, my steam doesn't start anymore. Happened a while back. Deleted everything related to steam, didn't help...

Full log: https://gist.github.com/reactormonk/c7a0a0c857c94d3c0cd8433f63faf837

#### Steps for reproducing this issue:

1. Starting Steam, ( waiting for update process to finish )
2. Entering login data, pressing enter
3. hangs on "Connecting Steam account: ..."

Same error message as https://github.com/ValveSoftware/steam-for-linux/issues/5014, https://github.com/ValveSoftware/steam-for-linux/issues/6764, https://github.com/ValveSoftware/steam-for-linux/issues/6067

**Comment by kisak-valve** [comment]
Hello @reactormonk, does running `steam-runtime` have the same result?

**Comment by reactormonk** [comment]
You're fast O.o - when I properly start it via `STEAM_RUNTIME=1` I get

```
$ STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 STEAM_RUNTIME=1 steam-runtime
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled by the user
Pins up-to-date!
/home/tass/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
[2020-03-02 00:40:34] Startup - updater built Feb 11 2020 19:26:28
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-03-02 00:40:34] Checking for update on startup
[2020-03-02 00:40:34] Checking for available updates...
[2020-03-02 00:40:34] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-03-02 00:40:34] Download skipped: /client/steam_client_ubuntu12 version 1581460722, installed version 1581460722
[2020-03-02 00:40:34] Nothing to do
[2020-03-02 00:40:34] Verifying installation...
[2020-03-02 00:40:34] Performing checksum verification of executable files
[2020-03-02 00:40:35] Verification complete
glXChooseVisual failed
glXChooseVisual failedMain.cpp (333) : Assertion Failed: Fatal Error: glXChooseVisual failed
Main.cpp (333) : Assertion Failed: Fatal Error: glXChooseVisual failed
Installing breakpad exception handler for appid(steam)/version(1581460722)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: ./libcef.so: undefined symbol: FcConfigGetSysRoot
assert_20200302004035_6.dmp[170811]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200302004035_6.dmp
assert_20200302004035_6.dmp[170811]: Finished uploading minidump (out-of-process): success = yes
assert_20200302004035_6.dmp[170811]: response: CrashID=bp-de9db725-5490-4af4-b047-9d9152200301
assert_20200302004035_6.dmp[170811]: file ''/tmp/dumps/assert_20200302004035_6.dmp'', upload yes: ''CrashID=bp-de9db725-5490-4af4-b047-9d9152200301''

```

**Comment by kisak-valve** [comment]
`glXChooseVisual failed` is most likely the real issue here. Can you check if any 32 bit opengl application like `glxinfo32` from `lib32-mesa-demos` works?

**Comment by reactormonk** [comment]
Here's the output: https://gist.github.com/reactormonk/a252b083f7b7eefbeb4830b3b362f74e - I also ran glxgears32, which seem to be turning.

**Comment by kisak-valve** [comment]
Thanks, this might be a newer iteration of #6420.

**Comment by reactormonk** [comment]
There are not pinned libs atm, if I run it with `STEAM_RUNTIME=1` or without.

```
/home/tass//.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:
total 0

/home/tass//.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:
total 0
```

**Comment by kisak-valve** [comment]
That's not expected, please delete the `pinned_libs_*` folders so that Steam will regenerate them on next run.

**Comment by reactormonk** [comment]
Steam only recreates the folders, but doesn't add any links to it on the next run.

**Comment by TTimo** [comment]
Hello @reactormonk - you indicated that you are not using the Steam beta client, can you confirm? The production client was last updated about two weeks ago. The logs you posted show that the Steam client is trying to update - so it would be the first time in a while that you are running the Steam client, correct?

The logs also suggest you are running with Arch's modified steam runtime (https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_native_runtime), which we do not recommend for compatibility reasons.

Can you run the following command and provide the output?

`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ~/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-system-info`

**Comment by reactormonk** [comment]
That gives quite a few error messages on the graphics details :-( https://gist.github.com/reactormonk/7249e04de41daac4aeef07b0b7408ec6

**Comment by reactormonk** [comment]
I've tried via a new steam native instance on a new user account (via hint from #freenode on IRC), and i'm getting `glXChooseVisual failed`. I'll have to say I'm running out of ideas.

**Comment by TTimo** [comment]
The graphics drivers on your system are not working. The problem you are having is unrelated to Steam. The Steam client requires 32 bit OpenGL drivers. Some games will also require 64 bit OpenGL drivers. Having a working set of Vulkan drivers is highly recommended.

**Comment by reactormonk** [comment]
> The graphics drivers on your system are not working.

(X) Doubt

Direct rendering on both 64 and 32 bit are working: https://gist.github.com/reactormonk/66381726de7f35794aa6c09d31c14343#file-glxinfo-L3 https://gist.github.com/reactormonk/66381726de7f35794aa6c09d31c14343#file-glxinfo32-L3

Vulkan rendering is picked up: https://gist.github.com/reactormonk/66381726de7f35794aa6c09d31c14343#file-vulkaninfo-L63

I tested with the trifecta of `vkcube`, `glxgears`, `glxgears32` too, all seem to be working fine.

**Comment by TTimo** [comment]
Ok, I stand corrected, drivers are fine. The Steam client doesn't have a robust way to check and fix it's installation consistency, it's probably easier to bootstrap again by doing something like this:

```
mv ~/.local/share/Steam ~/.local/share/Steam.off
steam
```

But apparently you've already more or less done this by installing on a new user account.

The first log you posted looks to be an installation log done with Arch's modifications (because of the lines `STEAM_RUNTIME is disabled by the user` and `STEAM_RUNTIME_HEAVY: Disabled`). If you do the bootstrap I describe above without Arch's interference and without setting steam related environment variables, do you still get the assertion message? (please provide the full log).

And ofc you've got enough disk space, you are using ext4 filesystems etc.?

**Comment by reactormonk** [comment]
I added `STEAM_RUNTIME=1`. Seems to be the closest I can do to go for runtime. https://gist.github.com/reactormonk/583cd23a5b95692188a902f19a906696

**Comment by TTimo** [comment]
Please uninstall Arch's customized runtime, I think it's called `steam-native`. There should be no /usr/lib/steam/native_runtime.txt file, you should *not* be setting any STEAM_* environment variables.

**Comment by TTimo** [comment]
I note that the `bSharedKVSymbols` assert is gone, so that's progress there at least.

**Comment by reactormonk** [comment]
> I note that the bSharedKVSymbols assert is gone, so that's progress there at least.

I have more the feeling that it's not getting there, because I don't even get a login screen, which I do get with the arch native runtime.

There is no `/usr/lib/steam/native_runtime.txt`, the default is already steam native.

**Comment by TTimo** [comment]
> There is no /usr/lib/steam/native_runtime.txt, the default is already steam native.There is no /usr/lib/steam/native_runtime.txt, the default is already steam native.

Great! Please test without setting any `STEAM_*` environment variables. When set these will disable the runtime environment that the steam client would normally do.

**Comment by reactormonk** [comment]
Oh, wrong way round. What I meant is default is disabled runtime:

```
Setting up Steam content in /home/tass//.local/share/Steam
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is disabled by the user
```

**Comment by kisak-valve** [comment]
Hello @reactormonk, are you still experiencing this issue on an up to date system?

**Comment by reactormonk** [comment]
Works fine for now.
