### ISSUE TITLE
CD key window does not open

### ISSUE THREAD

**Issue by camelCaseSucks** [ValveSoftware/steam-for-linux#6938]
#### Your system information

* Steam client version (build number or date): 2-11-2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I tried to launch Anno 2070 in Proton, it showed a window with the "CD key". I checked "don't show this again" thinking if I needed it, I could open it manually. Now I do need it, so I right-click the game in the sidebar, click Manage > CD Keys, and nothing happens.

**Comment by kisak-valve** [comment]
Hello @camelCaseSucks, please opt into Steam's client beta and retest.

**Comment by camelCaseSucks** [comment]
I joined the beta and it's fixed, thanks!
