### ISSUE TITLE
Can not copy system information

### ISSUE THREAD

**Issue by safield** [ValveSoftware/steam-for-linux#6939]
I am running steam on Linux Mint 19.3

There is no way to copy the system information. There is no caret or text highlighting available.

**Comment by kisak-valve** [comment]
Hello @safield, what desktop environment are you using?

If you right click on the window, there should be an option to copy all text to the clipboard. Also, Ctrl + A, Ctrl + C works here in a quick test.

**Comment by safield** [comment]
I never tried right clicking on the window. Now the options are available to me. Maybe a always present button that says "copy all" would be more obvious to airheads like me.
