### ISSUE TITLE
Controller compatible with Ubuntu xboxdrv and shows up on jstest refuses to show up for steam.

### ISSUE THREAD

**Issue by BrokenGale** [ValveSoftware/steam-for-linux#6944]
#### Your system information

* Steam client version (build number or date): 2/11/2020 @ 19:27:00
* Distribution (e.g. Ubuntu): Pop_OS 19.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
I plugged in a third party nintendo controller (Hori Co., Ltd HORIPAD S)
Installed ubuntu xboxdrv, it both shows up and is detected correctly by jstest
lsusb does show the correct device id and manufacturer (both id and full name)
Steam Controller settings does not detect it.

#### Steps for reproducing this issue:

1. Install Steam and set it to Proton 5.0.2
2. Plug in Horipad Controller
3. Install ubuntu xboxdrv 
4. Check detection and functionality through jstest
5. Check detection and functionality through steam controller settings.

**Comment by kisak-valve** [comment]
Hello @BrokenGale, this might be a udev config issue similar to https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules#L55-L62.

**Comment by BrokenGale** [comment]
I tried to use this guide[](https://www.gamingonlinux.com/articles/you-will-need-to-update-your-udev-rules-for-the-steam-controller.8593), however the file specified by the article does not exist at the specified location. Maybe this only applied to a specific version of steam client (the article was fro 2016)

**Comment by BrokenGale** [comment]
I found the specified file in /lib/udev/rules.d/60-steam-input.rules.
The lines specified are already in the code, what alterations would I need to get it to work?
(I am very new to Linux as a whole please forgive my ignorance)

**Comment by BrokenGale** [comment]
0f0d:00c1 Hori Co., Ltd HORIPAD S does not seem to be in the files (It is a nintendo pro controller wired substitute)
Now that I know the problem, how should I go about fixing it?

**Comment by kisak-valve** [comment]
You should be able to add a line with `KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00c1", MODE="0660", TAG+="uaccess"`, and reload udev's rules or reboot.

If we're lucky, that might resolve the issue.

**Comment by BrokenGale** [comment]
That did the trick, thank you so much for your help!

**Comment by smcv** [comment]
This change has gone out in a beta `steam-launcher` package, version 1.0.0.63.

**Comment by smcv** [comment]
@kisak-valve, for future reference: it would maybe be useful to retitle issues like this to include the specific device, something like "HORIPAD S controller not supported". This can only be fixed on a per-device basis, so it will not help anyone else whose controller is compatible with xboxdrv and jstest but not Steam.

**Comment by SimonCoulombe** [comment]
This worked for my horipad mini4 (ps4 controller for kid) for about a day after I added the following line to my /lib/udev/rules.d/60-steam-input.rule : file
`KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00ee", MODE="0660", TAG+="uaccess"`

After a restart a second controller is created and added to jstest-gtk whenever I start steam. It is called "microsoft x-box 360 pad" and is located on /dev/input/ds1.  Unplugging the hori controller (/dev/input/js0) makes both controllers disappear.  

Now, when I start stardew valley I get "Config loaded: gamepad with camera controls" and the controller buttons are mapped.. weirdly.

**Comment by rrbbrb** [comment]
> You should be able to add a line with `KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00c1", MODE="0660", TAG+="uaccess"`, and reload udev's rules or reboot.
> 
> If we're lucky, that might resolve the issue.

I have the exact same specs and situation but my controller is Horipad mini and the `idProduct` is `"00dc"` instead. This doesn't work for me :(

**Comment by smcv** [comment]
> I have the exact same specs and situation but my controller is Horipad mini and the `idProduct` is `"00dc"` instead

Please open a separate issue in https://github.com/ValveSoftware/steam-devices/ with the details, or open a pull request similar to https://github.com/ValveSoftware/steam-devices/pull/21 if you are able to make it work by adding an extra line to the udev rules with this different `idProduct`.

**Comment by cipitaua** [comment]
in order for gyroscope to work you should use this dedicated driver:
https://github.com/cipitaua/dkms-hid-nintendolic
