### ISSUE TITLE
Alt+tab from a game causes a hang

### ISSUE THREAD

**Issue by AbnocChinwads** [ValveSoftware/steam-for-linux#6945]
#### Your system information

* Steam client version (build number or date): Feb 11 2020, at 19:27:00
* Distribution (e.g. Ubuntu): Ubuntu 18.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When alt+tabbing from any game (whether they're in fullscreen, windowed, or borderless window), the alt+tab menu doesn't appear, and it leaves the game window open but gives me the general PC cursor back, with it comes an inability to do anything other than move the cursor around. I really don't know anything about programming so I have no idea what code needs posting, sorry.

EDIT: Here's the gist of Steam Hardware Information:
https://gist.github.com/AbnocChinwads/de0483d9492c5199d3443f3ce37ed2a7

#### Steps for reproducing this issue:

1. Run a game through Steam, or through it's executable with Steam open.
2. Alt+tab to any other application.
3. Be forced to reset your PC as nothing is doable.

**Comment by kisak-valve** [comment]
Hello @AbnocChinwads, this is almost certainly a video driver issue. It should be reported to the nouveau devs.

You should consider switching to nVidia's proprietary driver for the best experience with your Pascal generation video card.

**Comment by AbnocChinwads** [comment]
Thank you I have done now, totally fixed the issue although I now have to run at 1280p to be able to see my full screen. But I'll get straight to the nouveau devs
