### ISSUE TITLE
Fatal Error: Steamcmd needs 250MB of free disk space to update.

### ISSUE THREAD

**Issue by luca-alsina** [ValveSoftware/steam-for-linux#6946]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Pterodactyl on Debian 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: I can't

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Hello, when i starting my server i have this error:

`[----] Verifying installation...
[----] !!! Fatal Error: Steamcmd needs 250MB of free disk space to update.

*********************************************************
*********************************************************
* Unable to load Steam support library.*
* Unable to load Steam support library.*
* This server will operate in LAN mode only.*
* This server will operate in LAN mode only.*
*********************************************************
*********************************************************`

but i have 14447 / 25600 MB used disk space.

#### Steps for reproducing this issue:

1. Just start the server

**Comment by clort81** [comment]
Same problem here.  What was the resolution?
