### ISSUE TITLE
Shift+tab doesn't open up steam overlay but fps counter works

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#6949]
#### Your system information

* Steam client version: Mar 3 2020
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System specs and info :https://gist.github.com/barfin/6e7435194c7e879bc8d8156162e1537d

#### Please describe your issue in as much detail as possible:
Shift+tab doesn't open up steam overlay but fps counter works

#### Steps for reproducing this issue:

1. launch a game (in my case alan wake)
2. press shift+tab
3. overlay doesn't show up but fps counter works

**Comment by barfin** [comment]
It's not only proton issue though, i tested it in dota2 and i got the same results

**Comment by kisak-valve** [comment]
Possible duplicate of #5714.

**Comment by barfin** [comment]
> Possible duplicate of #5714.

yes it's possible but it happened recently

**Comment by barfin** [comment]
the problem was the lsi "linux steam integration" i removed it and ran steam normally and it worked fine
 it's not a steam bug i think
