### ISSUE TITLE
Is It OK to change variables in "steam" script to change install location ?

### ISSUE THREAD

**Issue by RageCooky** [ValveSoftware/steam-for-linux#6950]
#### Your system information

* Steam client version : steam_latest.tar.gz
* Distribution : Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

I want install steam to other location not home.
After Google found make symlink or just move the folder after install.

So I find my way ... change variables in "steam" script to change install location.
Will it affect steam function or some feature ?
(I prefer use the tarball one to install steam not from distro repo.)

**Comment by sizeofbool** [comment]
Doing this seems not a good idea. If it won't break now, it will probably break in the future.
May I ask why do you want to move Steam Client to another location?
If it is because you want to install games into another location, then Steam Client has implemented feature for that. You can simply select install location for games when downloading games.

**Comment by RageCooky** [comment]
> Doing this seems not a good idea. If it won't break now, it will probably break in the future.
> May I ask why do you want to move Steam Client to another location?
> If it is because you want to install games into another location, then Steam Client has implemented feature for that. [[1]](https://support.steampowered.com/kb_article.php?ref=7418-YUBN-8129) You can simply select install location for games when downloading games.

No special reason, just personal preference, keep home clean. (

**Comment by byte1024** [comment]
Valve wants it installed to home so I suppose you would want a feature to select install location during installation. That might be the most correct way.

rpm's, etc should already have set locations for all files so if you could change that correctly then it should be fine but if an update came along as an rpm, etc then I assume that would cause a problem as it may not know.

I would just deal with having it in home as that's how its designed.

**Comment by TTimo** [comment]
The main data folder for Steam is by default in `~/.local/share/Steam`, the `~/.local/share` part can be changed with `XDG_DATA_HOME`.

Steam will still use `~/.steam` for various important small files and symlinks. It's not ideal - things are working this way for legacy reasons, and changing this now wouldn't be practical.

**Comment by RageCooky** [comment]
> The main data folder for Steam is by default in `~/.local/share/Steam`, the `~/.local/share` part can be changed with `XDG_DATA_HOME`.
> 
> Steam will still use `~/.steam` for various important small files and symlinks. It's not ideal - things are working this way for legacy reasons, and changing this now wouldn't be practical.

Thx. Seems symlink is the only way.
