### ISSUE TITLE
Library customization scrambles after removing/adding mods

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#6952]
#### Your system information

* Steam client version (build number or date): Mar 7 2020
* Distribution (e.g. Ubuntu): Elementary OS Hera
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When customizing the Steam Library for Sourcemods/HL1 mods (changing banners, logos, etc) after adding more or removing some the customization done to one mod will go to another mod or just disappear. 

#### Steps for reproducing this issue:

1. Install mods
2. Add background image/logo/cover art
3. Either add more mods or remove some

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
