### ISSUE TITLE
migrate steam from gtk2 to gtk3

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-for-linux#6953]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by Faalagorn** [comment]
Why was this issue closed @kisak-valve? I guess it because of wrongly filled description, because it is still needed due to GTK2 being deprecated since end of 2020 (see e.g. [this for more info](https://archlinux.org/todo/gtk-2-eol/)) and for things like Wayland support, see https://github.com/ValveSoftware/steam-for-linux/issues/4924#issuecomment-789324760. Is there an open issue to keep track of this?

**Comment by kisak-valve** [comment]
Hello @Faalagorn, the blank issue report template makes this an invalid issue report.

As far as I know, the Steam client uses VGUI2 and Panorama (via libcef) to render, not GTK2. The libappindicator steam tray icon uses a GTK2 render path, but that's non-essential, provided by the Steam runtime and doesn't block the main client window if it is broken or missing.

**Comment by Faalagorn** [comment]
> Hello @Faalagorn, the blank issue report template makes this an invalid issue report.
> 
> As far as I know, the Steam client uses VGUI2 and Panorama (via libcef) to render, not GTK2. The libappindicator steam tray icon uses a GTK2 render path, but that's non-essential, provided by the Steam runtime and doesn't block the main client window if it is broken or missing.

Thanks for a quick reply! Does it mean though that the point about Steam using GTK2 in https://github.com/ValveSoftware/steam-for-linux/issues/4924#issuecomment-789324760 is basically not preventing Steam to be native Wayland application? Though it still be nice to upgrade to GTK3 (or 4) when possible :)

**Comment by MetaDark** [comment]
@kisak-valve Oh ok, so VGUI2 renders the window then? I only looked into the load time dependencies, but it seems like `vgui2_s.so` is loaded at runtime. Does that mean that VGUI2 would have to be updated to support Wayland to close https://github.com/ValveSoftware/steam-for-linux/issues/4924?
