### ISSUE TITLE
CSGO selection wrong microphone - works in steam

### ISSUE THREAD

**Issue by sparkie3** [ValveSoftware/steam-for-linux#6955]
#### Your system information

* Steam client version (build number or date): 3-10-20
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My microphone works just fine on my system. It also works just fine within steam. I can shift + tab, go into friends list, select my microphone, test it, and it works fine. CSGO, however, does not select the appropriate microphone. It selects one of my GPU's HDMI ports for audio rather than the microphone it has been instructed to select. I have tested this by muting all three, and testing in game one at a time. One of them with give me static and noise, and when muted gives me nothing.

#### Steps for reproducing this issue:

1. Enter steam friends list
2. Select actual microphone
3. Test in game and get incorrect microphone

**Comment by kisak-valve** [comment]
Hello @sparkie3, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/190. Closing as a duplicate.
