### ISSUE TITLE
[Feature Request] Add menu “Launch on Discrete GPU”

### ISSUE THREAD

**Issue by YangtseSu** [ValveSoftware/steam-for-linux#6957]
Add option to launch games using the discrete GPU from within steam.
Or set Discrete GPU as default.

switcheroo-control
https://gitlab.freedesktop.org/hadess/switcheroo-control

**Comment by kisak-valve** [comment]
Hello @YangtseSu, this feature request is already being tracked at #634. Closing as a duplicate.
