### ISSUE TITLE
5-30 second delay when trying to use Libray view after restoring Steam client

### ISSUE THREAD

**Issue by WhiteSp1rit** [ValveSoftware/steam-for-linux#6963]
#### Your system information

* Steam client version, build date: Feb 11 2020, at 19:27:00
* Distribution: Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* System info: https://gist.github.com/WhiteSp1rit/a28f64ea2c21c6aac35f4a26b8b0b69e

#### Please describe your issue in as much detail as possible:
When restoring a previously minimized Steam client instance, with Library-Home view already selected, nothing in it can be clicked for up to 30 seconds, Steam client doesn't respond to clicks in this view during this time.

#### Steps for reproducing this issue:

1. Open Steam client
2. Navigate to Library-Home
3. Minimise the Steam client
4. Wait half an hour
5. Restore Steam client
6. Try to click on any game in the games list on the left

**Comment by kisak-valve** [comment]
Hello @WhiteSp1rit, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Hello @WhiteSp1rit, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
