### ISSUE TITLE
System information wrongly shows AVX2 and SHA as unsupported

### ISSUE THREAD

**Issue by monterrr** [ValveSoftware/steam-for-linux#6965]
#### Your system information

* Steam client version (build number or date): 11/02/2020
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:
System information wrongly shows AVX2 and SHA as unsupported on my Zen desktop CPU.

#### Steps for reproducing this issue:
1. Open system information.

**Comment by kisak-valve** [comment]
Hello @monterrr, this issue is already being tracked at #6561. Closing as a duplicate.
