### ISSUE TITLE
Please don't abuse org.gnome.SessionManager inhibit

### ISSUE THREAD

**Issue by mtwebster** [ValveSoftware/steam-for-linux#6966]
#### Your system information

* Steam client version (build number or date): 1581460722
* Distribution (e.g. Ubuntu): Debian Buster/LMDE4 64 bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When the steam client starts, it begins inhibiting (scope flag 8: Inhibit the session being marked as idle), reason: "Playing a game".  It renews this approximately every 30 seconds

The inhibitor should only be active *if a game is actually running*, and it is not necessary to renew this every 30 seconds.

It should work as follows:

1) Start steam
2) Start game (add inhibitor)
3) playing game....
4) exit game (remove inhibitor)
5) exit steam

Thanks

**Comment by kisak-valve** [comment]
Hello @mtwebster, this issue is already being tracked at #5607. Closing as a duplicate.

**Comment by mtwebster** [comment]
Ah sorry! I didn't search hard enough.
