### ISSUE TITLE
Can't start steam with nvidia driver 440.59

### ISSUE THREAD

**Issue by vctt94** [ValveSoftware/steam-for-linux#6969]
#### Your system information

* Steam client version (build number or date): 
 latest downloaded from site today
* Distribution (e.g. Ubuntu): 
Debian
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes, I am in latest debian

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

running steam with nvidiar driver 440.59 generates the following error:
```
Running Steam on debian 10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
/home/vctt/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
Failed to load steamui.so - dlerror(): libGL.so.1: wrong ELF class: ELFCLASS64
Installing breakpad exception handler for appid(steam)/version(1581460722)
Installing breakpad exception handler for appid(steam)/version(1581460722)
[2020-03-18 16:42:13] Startup - updater built Feb 11 2020 19:26:28
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-03-18 16:42:14] Checking for update on startup
[2020-03-18 16:42:14] Checking for available updates...
[2020-03-18 16:42:14] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-03-18 16:42:14] Download skipped: /client/steam_client_ubuntu12 version 1581460722, installed version 1581460722
[2020-03-18 16:42:14] Nothing to do
[2020-03-18 16:42:14] Verifying installation...
[2020-03-18 16:42:14] Performing checksum verification of executable files
[2020-03-18 16:42:15] Verification complete
[2020-03-18 16:43:36] Shutdown
```
#### Steps for reproducing this issue:

1. Install nvidia driver 440.59
2. Run steam
3. bug should happen

**Comment by kisak-valve** [comment]
Hello @vctt94, does any 32 bit OpenGL application like `glxinfo` from `mesa-utils:i386` work? The log is trying to tell you that you do not have a sane 32 bit OpenGL driver stack.

nVidia 440.59 is an unusual driver version to see on Debian 10. How did you install it? If you used nVidia's .run installer, did you have multiarch setup before installing the nVidia driver? It may have skipped 32 bit userspace support because it detected a 64 bit only system.

**Comment by vctt94** [comment]
aparently it does not kisak. Log from glxinfo: `glxinfo: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

I installed by debian's wiki. https://wiki.debian.org/NvidiaGraphicsDrivers

More specific: `apt-get install -t buster-backports nvidia-driver `

**Comment by kisak-valve** [comment]
Please check if you have the `nvidia-driver-libs-i386` package installed with something like `apt policy nvidia-driver-libs-i386` and install it if it isn't already.

**Comment by vctt94** [comment]
It worked. Thanks for the help, I am closing this issue.
