### ISSUE TITLE
Portal and Half-Life:Source games in Steam on Ubuntu 18.04.4, Korean text problem

### ISSUE THREAD

**Issue by stinved** [ValveSoftware/steam-for-linux#6970]
![스크린샷, 2020-03-18 19-43-17](https://user-images.githubusercontent.com/62407552/77124556-8f444780-6a86-11ea-918c-72864fe174b1.png)
![스크린샷, 2020-03-18 19-31-04](https://user-images.githubusercontent.com/62407552/77124557-90757480-6a86-11ea-8f0f-25470a858db8.png)
![스크린샷, 2020-03-18 19-30-58](https://user-images.githubusercontent.com/62407552/77124559-910e0b00-6a86-11ea-878e-02805b77be69.png)

#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @stinved, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/153.

`sudo apt install libfontconfig:i386` may help among the other discussion in that issue report.

Closing as a duplicate.

**Comment by stinved** [comment]
Thank you for the notice

But that command didn't solve the problem

Maybe these games too old

I gonna play recent games, these has no problem Korean sub on Ubuntu

Thanks any way!
________________________________
보낸 사람: kisak-valve <notifications@github.com>
보낸 날짜: 2020년 3월 20일 금요일 오전 8:50
받는 사람: ValveSoftware/steam-for-linux <steam-for-linux@noreply.github.com>
참조: stinved <stinved@outlook.kr>; Mention <mention@noreply.github.com>
제목: Re: [ValveSoftware/steam-for-linux] Portal and Half-Life:Source games in Steam on Ubuntu 18.04.4, Korean text problem (#6970)


Hello @stinved<https://github.com/stinved>, this issue is already being tracked at ValveSoftware/Source-1-Games#153<https://github.com/ValveSoftware/Source-1-Games/issues/153>.

sudo apt install libfontconfig:i386 may help among the other discussion in that issue report.

Closing as a duplicate.
