### ISSUE TITLE
Polish letters not working

### ISSUE THREAD

**Issue by michalszymura** [ValveSoftware/steam-for-linux#6972]
#### Your system information

* Steam client version (build number or date): 20 mar 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

With English(UK): Polish (British keyboard) unable to write Polish letters anywhere in steam.
![Screenshot_2020-03-16_11-56-15](https://user-images.githubusercontent.com/10345171/77236534-5b1c7400-6bb7-11ea-9615-595815146734.png)

**Comment by kisak-valve** [comment]
Hello @michalszymura, can you share the output of `locale -a`? In particular, we want to see `en_US.utf8` as one of the system locales.

**Comment by michalszymura** [comment]
C
en_GB.utf8
POSIX

I actually tested just now regular polish keyboard and it still doesn't work.

**Comment by kisak-valve** [comment]
Thanks for checking, please uncomment `en_US.UTF-8 UTF-8` in `/etc/locale.gen` and run `sudo locale-gen` to regenerate the system locales, then restart Steam and retest.

**Comment by michalszymura** [comment]
It's working fine now. Thank You.
