### ISSUE TITLE
Xbox One controller button mapping is wrong via Remote Play in Resident Evil 3 Demo.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6975]
It only happens to Remote Play, the local gaming is fine.
#### Your system information

* Steam client version (build number or date): Mar 20 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
The D-pad of the controller becomes left stick, the left stick becomes D-pad, button A becomes button X.

#### Steps for reproducing this issue:

1. Plug in the controller
2. Play Resident Evil 3 Demo via Remote Play
3. Try to move the character or skip the scenes.

**Comment by kisak-valve** [comment]
Possibly related to #6682.

**Comment by laichiaheng** [comment]
> Possibly related to #6682.

My host and client are both Linux PC.

**Comment by laichiaheng** [comment]
@kisak-valve @slouken The controller is no more working on Resident Evil 3 Demo with the latest beta update.

**Comment by laichiaheng** [comment]
It is fixed with the latest beta client.
