### ISSUE TITLE
Steam disables numlock on first launch

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#6977]
#### Your system information

* Steam client version (build number or date):  Mar 20 2020, at 18:25:30
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341

Numlock key gets disabled when launching Steam. When closing Steam, enabling numlock key, and launching Steam again, it stays on.

#### Steps for reproducing this issue:

1. Enable numlock key
2. Launch Steam
3. Numlock gets shut off

**Comment by shoober420** [comment]
Another odd thing, is if I manually disable my numlock key, and turn it back on before launching Steam, then it won’t happen. It’s as though you have to activate and deactivate the numlock a couple times before launching Steam so that Steam doesn’t have an effect on the numlock key.

**Comment by kisak-valve** [comment]
Hello @shoober420, this doesn't read like a Steam issue and I was unable to reproduce this behavior on my Arch test box with KDE 5.18.3 and the 2020-03-20 Steam client beta.

**Comment by kisak-valve** [comment]
Right, report this issue to your distribution, it reads like the initial state of the numlock key is out of sync between the hardware and the OS.

**Comment by shoober420** [comment]
Please recheck again, I found out the cause

**Comment by shoober420** [comment]
Most distros depend on some form of “setleds -D +num” to activate the numlock key on boot. Whether it be the “systemd-numlockontty” package, or simply adding “setleds -D +num” to “.xinitrc” like I did.

Note:
Having no scripts or packages installed for numlock activation (default), and enable the numlock key manually by hitting it on the keyboard does not reproduce the issue.

To reproduce the bug, you have to use “systemd-numlockontty” or add “setleds -D +num” in a startup script somewhere (“.xinitrc” or “.zshrc”) and that’s when Steam will disable the numlock key.

Very strange.

**Comment by shoober420** [comment]
Regardless, Steam should still have no effect on the numlock key, no matter how the user chooses to enable numlock. Whether it be via scripts or packages, Steam should not disable numlock.

**Comment by shoober420** [comment]
@kisak-valve 
Have you tried testing this again by chance with all the new info I discovered?

**Comment by kisak-valve** [comment]
Hello @shoober420, my previous assessment stands. This isn't a Steam issue.

**Comment by shoober420** [comment]
For what its worth, I tried various methods listed on the Arch wiki, to enable numlock on boot. I'm going to list the methods I tested and see which ones Steam ignores, and does not respect.

https://wiki.archlinux.org/index.php/Activating_numlock_on_bootup

Steam disables numlock:

systemd-numlockontty package
getty service (personal choice)
bash alternative

Steam keeps numlock enabled:

numlockx package
manually enabling the numlock key before launching Steam

These five methods are the ones I've personally tested, and only method that truly worked was using the "numlockx" package.

@kisak-valve 
Which method do you use to enable the numlock key at boot?

**Comment by shoober420** [comment]
Some things I thought I should share in case anyone comes across this themselfs and is curious about the numlock key. 

It appears that using the “setleds -D +num” method is mainly for activating the numlock at boot in the tty terminals.

Now “numlockx” is specifically made to activate numlock via X.Org Server. I believe that not only does systemd disable numlock at boot by default, X.Org Server also disables numlock by default when launched.

So one will need to use “numlockx” so that the numlock key is truly enabled in X.Org Server.
