### ISSUE TITLE
Gnome Super (Windows key) button has no effect when Steam window is on focus

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/steam-for-linux#6979]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/4261659/77406239-66dd8580-6dc5-11ea-875a-bbf5d0c0a202.png)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Gnome 3.36. When press Super (Windows key) on keyboard and Steam window is on focus, it does nothing, expecting Gnome activities overview appear. Have to switch to another window to make it effect. Dragging cursor to left top corner does work.

#### Steps for reproducing this issue:

1. Open Steam
2. Press Super button

**Comment by xDShot** [comment]
Happens only when Main window on focus. Works when switched to client's sub-windows (game properties, chat, etc.)

**Comment by kisak-valve** [comment]
Hello @xDShot, this issue should also be mentioned to the devs that maintain your desktop environment.

**Comment by xDShot** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2477 upstream report

**Comment by Chiitoo** [comment]
Upstream seems to be of the opinion that this is Steam's doing, but here, using LXQt with KWin, I don't seem to have this issue.

That is, I'm able to bind anything to the super key, and it works just fine even if the Steam window is the currently active window.

**Comment by dearlygparted** [comment]
> #### Steps for reproducing this issue:
> 
>     1. Open Steam
> 
>     2. Press Super button

Couldn't reproduce. Pressing the Super key works as expected for me. Running Gnome Shell 3.36.1 on Arch Linux, however, I am not using the Steam beta client.

**Comment by xDShot** [comment]
Can't reproduce anymore, guess it's fixed.
