### ISSUE TITLE
Deleting custom proton runtime renders game "uninstalled"

### ISSUE THREAD

**Issue by superenginegit** [ValveSoftware/steam-for-linux#6982]
#### Your system information

* Steam client version (build number or date): Mar 23 2020
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When a custom proton version is deleted all games set to run with this version should be reset to the default steamplay runtime. Instead they are marked as "not installed" but can be recovered by going into properties and changing their steamplay runtime.

#### Steps for reproducing this issue:

1. Install game with custom proton version
2. Delete that proton version from the directory
3. restart steam and look for that game

**Comment by kisak-valve** [comment]
Hello @superenginegit, are you still experiencing this issue on an up to date system? (https://github.com/ValveSoftware/steam-for-linux/issues/6874#issuecomment-1159450765)

**Comment by superenginegit** [comment]
No, it switches that game to the default proton version now. So it's as expected.
