### ISSUE TITLE
Game doesn't launch with %command% -EpicPortal

### ISSUE THREAD

**Issue by FireCulex** [ValveSoftware/steam-for-linux#6984]
#### Your system information

* Steam client version (build number or date): Feb 11, 2020
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

command line arguments are ignored after issuing %command% for non-steam games such as those from the Epic Store.
-EpicPortal works fine on its own, but perhaps I want PROTON_LOG=1 or MANGO_HUD=1

#### Steps for reproducing this issue:

1. PROTON_LOG=1 %command% -EpicPortal
2. MANGO_HUD=1 %command% -EpicPortal
3.

**Comment by kisak-valve** [comment]
Hello @FireCulex, this issue is already being tracked at #6046. Closing as a duplicate.
