### ISSUE TITLE
Properties panel crash with A Plague Tale when selected custom proton is deleted

### ISSUE THREAD

**Issue by Hikari-Haru** [ValveSoftware/steam-for-linux#6986]
#### Your system information

* Steam client version (build number or date): 2020-03-23 build
* Distribution (e.g. Ubuntu): Arch - Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When deleting a custom proton version that is assigned to the game A Plague Tale, steam will crash when opening the properties panel for the game. However the same does not happen when I do the same for Streets of Rogue, then the "Force the use of a specific Steam Play compatibility tool" option just gets unchecked and no crash happens.

/home/zuriele/.local/share/Steam/steam.sh: line 722: 186600 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

Can provide dmp file of the crash if needed

#### Steps for reproducing this issue:

1. Set A Plague Tale to use custom proton
2. Delete the custom proton version and restart steam
3. Open steam and open the properties panel for the game
4. Steam should crash to desktop

**Comment by kisak-valve** [comment]
Previously mentioned at https://github.com/ValveSoftware/steam-for-linux/issues/6757#issuecomment-603311283.

**Comment by Hikari-Haru** [comment]
Regarding that comment, it can be repaired by going into the steamfolder/config/config.vdf and setting the CompatToolMapping name for the appid to "" (blank) which disabled the compattool and let me access the properties menu again without crashing

**Comment by soredake** [comment]
Happens again with GTA IV

**Comment by mferraci** [comment]
I have same issue when deleting custom proton version on The Surge and Worms Armageddon

> Regarding that comment, it can be repaired by going into the steamfolder/config/config.vdf and setting the CompatToolMapping name for the appid to "" (blank) which disabled the compattool and let me access the properties menu again without crashing

I confirm deleting all inside CompatToolMapping is a valid workaround

**Comment by 414n** [comment]
I observed this too for Warframe, but not for Dragon Ball Fighter Z.

**Comment by LordJABA** [comment]
AFK it happens for every game that had a specific Proton version that was later removed specified. It should just revert to "use global" in such case, I think.

**Comment by Terryvanderjagt** [comment]
After encountering this bug, Steam removed my game files making me re-download all 75GB of Borderlands 3. :) Is this a side effect of this bug that other users are encountering too, or is this a different issue?

**Comment by DragoonAethis** [comment]
Same here, here's the client crash dump: [crash_20200728194752_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/4990206/crash_20200728194752_1.zip)

**Comment by DragoonAethis** [comment]
Also, here's a solution: Open `~/.steam/root/config/config.vdf` in your text editor, find `CompatToolMapping` and delete all the indented bracket contents below it (or just entries for Proton versions you've removed) - this seems to be a map of Steam app IDs to selected tools, nuking that block makes the properties dialog open properly again for affected games without redownloading anything.

**Comment by romulasry** [comment]
Removing compattoolmapping fixed it, but it is still a bug.

**Comment by soredake** [comment]
This seems to be fixed with steam ui update, it does not crash anymore.

**Comment by DragoonAethis** [comment]
Yep, no longer crashes - just leaves the "force the use of a specific Steam Play compatibility tool" checkbox off.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
