### ISSUE TITLE
No more sound via Remote Play.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#6987]
I also notice that Steam is not in the pulseaudio list anymore.
![2020-03-26 18-28-02 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/77636763-8c1def80-6f8f-11ea-94ae-9ed7ba34eb61.png)

#### Your system information

* Steam client version (build number or date): Mar 25 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes.

#### Please describe your issue in as much detail as possible:
No more sound via Remote Play.

#### Steps for reproducing this issue:

1. Stream every game.
2. No sound.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
