### ISSUE TITLE
Segmentation Fault on launch

### ISSUE THREAD

**Issue by Francexi** [ValveSoftware/steam-for-linux#6989]
#### Your system information

* Steam client version (build number or date): 1.0.0.62
* Distribution (e.g. Ubuntu): Slackware64-current
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I try to launch steam I receive the following:

```
Couldn't find dpkg, please update steamdeps for your distribution.
    Actually, don't worry - this is Slackware!

Running Steam on slackware 14.2 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/francesco/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1585264767)
Installing breakpad exception handler for appid(steam)/version(1585264767)
Installing breakpad exception handler for appid(steam)/version(1585264767)
crash_20200327121547_1.dmp[24498]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200327121547_1.dmp
/home/francesco/.local/share/Steam/steam.sh: riga 722: 24484 Errore di segmentazione $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20200327121547_1.dmp[24498]: Finished uploading minidump (out-of-process): success = yes
crash_20200327121547_1.dmp[24498]: response: CrashID=bp-e8c61357-d745-4dd7-969a-2bf1f2200327
crash_20200327121547_1.dmp[24498]: file ''/tmp/dumps/crash_20200327121547_1.dmp'', upload yes: ''CrashID=bp-e8c61357-d745-4dd7-969a-2bf1f2200327''
```
Attacched to gdb the output is the following
```
Thread 1 "steam" received signal SIGSEGV, Segmentation fault.
0xf7a0b5c1 in strchr () from /lib/libc.so.6
(gdb) up
#1  0xf7458de8 in ?? () from /usr/lib/libGLX_mesa.so.0
```
I've already installed nvidia drivers, both 32bit and 64bit version as suggested in other issues. The NVIDIA driver version is 440.64

#### Steps for reproducing this issue:

run Steam

**Comment by Chiitoo** [comment]
Considering the backtrace, this probably isn't it, but just to make sure, is 'dbus' running?

It's a very popular cause for an early segmentation fault like this here.

**Comment by Francexi** [comment]
```
$ ps -e | grep dbus
 1050 ?        00:00:00 dbus-daemon
 1476 ?        00:00:00 dbus-launch
 1477 ?        00:00:00 dbus-daemon
 1612 ?        00:00:00 dbus-launch
 1613 ?        00:00:00 dbus-daemon
 1685 ?        00:00:00 gmenudbusmenupr
 1769 ?        00:00:00 dbus-daemon
```

**Comment by Francexi** [comment]
> Considering the backtrace, this probably isn't it, but just to make sure, is 'dbus' running?
> 
> It's a very popular cause for an early segmentation fault like this here.

I supposed that the missing of dbus would a be problem. Correct?

**Comment by Chiitoo** [comment]
It would look like you have it running, yeah, so not the issue here.

I wonder if it's about some mesa libraries.  Not that the proprietary NVIDIA drivers use it, but some other things still need it to be around.

I'm not familiar with Slackware, so I'm not sure what to look for exactly.

**Comment by Francexi** [comment]
> It would look like you have it running, yeah, so not the issue here.
> 
> I wonder if it's about some mesa libraries. Not that the proprietary NVIDIA drivers use it, but some other things still need it to be around.
> 
> I'm not familiar with Slackware, so I'm not sure what to look for exactly.

can you try to suggest some locations? Even if is from another distro, i'm enough used to Slackware to find the equivalent in that distro

**Comment by Francexi** [comment]
Also, may be worth noticing two things:
-the system is a notebook and nvidia drivers are installed under bumblebee. Anyway, before updating the drivers to 440.xx all worked. Trying to start steam in primusrun or pvkrun doesn't change anything
-other applications that uses NVIDIA works flawlessy

**Comment by Chiitoo** [comment]
Oh, it used to work... hrm.

I've unfortunately never played around with bumblebee etc. either.  Someone else will definitely know better.

Is it feasible to roll back to the previous driver version, without too much of a hassle?  I don't have much hope for it to be due to the driver itself, but perhaps something during the update changed in addition to the version of the NVIDIA driver.

Sorry I can't be of more help at this time.

**Comment by Francexi** [comment]
> Oh, it used to work... hrm.
> 
> I've unfortunately never played around with bumblebee etc. either. Someone else will definitely know better.
> 
> Is it feasible to roll back to the previous driver version, without too much of a hassle? I don't have much hope for it to be due to the driver itself, but perhaps something during the update changed in addition to the version of the NVIDIA driver.
> 
> Sorry I can't be of more help at this time.

Is a really big problem to me. Since I had to rebuilt the modules, I also rebuilt the kernel to the last stable release

**Comment by gbschenkel** [comment]
@Francexi have you installled multilib and built nvidia-drivers with COMPAT32=yes? Else it will not work!

**Comment by kisak-valve** [comment]
Hello @Francexi, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
