### ISSUE TITLE
Dota Underlords broken in latest Steam client libvulkan update

### ISSUE THREAD

**Issue by shazow** [ValveSoftware/steam-for-linux#6990]
#### Your system information

* Steam client version (build number or date): Built Mar 26, 2020, at 22:46:20, Steam API v020, package versions 1585264767.
* Distribution (e.g. Ubuntu): NixOS, running Steam via Flatpak v1.4.2 using `flathub/com.valvesoftware.Steam`
* Opted into Steam client beta?: No (though same problem exists in the Steam client beta)
* Have you checked for system updates?: Yes.

#### Please describe your issue in as much detail as possible:

Ever since the latest Steam stable update, Underlords no longer starts. I get this error box instead:

```
Failed to initialize Vulkan.
Please make sure your driver and GPU support Vulkan.
```

I tried a few other games, they seem to work fine. Haven't tried all games, but happy to try anything specific. For example, Dota2 still works.

GPU: GeForce GTX 1080 (driver version: nvidia-x11-440.59-5.4.25)

I actually got this error using the beta client last week, so I switched to the stable branch in hopes that it would go away before it became stable, but that's what I get for not reporting it earlier. :)

#### Steps for reproducing this issue:

1. Run latest Steam client (beta or stable) using Flatpak v1.4.2, using the `flathub/com.valvesoftware.Steam` image.
2. Run Dota Underlords
3. Get Vulkan error. :(

I also tried adding -gl to the Dota Underlords run flags, but it just hangs.

**Comment by kisak-valve** [comment]
Related: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/989

**Comment by shazow** [comment]
@kisak-valve Ah handy, thank you, will track that also.

**Comment by kisak-valve** [comment]
@shazow, can you check if the workaround in the linked bug report helps?

Please try adding `XDG_CONFIG_DIRS=/etc/xdg:/usr/lib/x86_64-linux-gnu/GL:/usr/lib/i386-linux-gnu/GL %command%` to the game's launch options.

**Comment by shazow** [comment]
@kisak-valve Confirmed that workaround works for me, using the latest Steam Beta client which was failing with the same error before.

**Comment by guihkx** [comment]
Are you sure you're running the latest Steam build from Flatpak? This fix was added 5 days ago:

https://github.com/flathub/com.valvesoftware.Steam/commit/ae87f47cd15969d5d3019088b4e89341b9a2fbe7

Just run `flatpak update` to update everything.

**Comment by shazow** [comment]
@guihkx You're totally right! It works with the latest com.valvesoftware.Steam image, my apologies.

I tried the latest last week when it was failing on the beta but I forgot to update it when it started breaking yesterday. Thank you.
