### ISSUE TITLE
Steam crashes when trying to open Properties of Brawlout

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#6994]
#### Your system information

* Steam client version (build number or date): March 26th, 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever I try to open the Preferences of [Brawlout](https://store.steampowered.com/app/263720/Brawlout/) the Steam client instantly crashes. I can reproduce it every time and it's the only game which does it.

Another interesting fact is, that it that it should run with Proton, but that won't be shown as such and when I investigated I found out that it actually uses Wine which is installed on my system.

#### Steps for reproducing this issue:

1. Go to the steam library and find Brawlout
2. Open context menu and select Properties
3. Steam client crashes

**Comment by kisak-valve** [comment]
Hello @NoXPhasma, this issue is already being tracked at #6986 (or possibly #6757). Closing as a duplicate.
