### ISSUE TITLE
Prop_vehicle_driveable crash the server when spawn

### ISSUE THREAD

**Issue by Benito1020** [ValveSoftware/steam-for-linux#6997]
**Your system information**

* Steam client version (build number or date): 1585264767, 03/26/2020
* Distribution (e.g. Ubuntu): Windows 10 Pro x64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

**Please describe your issue in as much detail as possible:**

Using the game function crashes your server and client instantly.
I think it's due to a bug in vphysics.so.
It has now been almost 2 years since the release of the Danger Zone that this has been happening, whether on windows server or linux.

**Steps for reproducing this issue:**

1. Download : [vehicle_driveable.zip](https://github.com/Benito1020/Roleplay-CS-GO/raw/master/vehicle_driveable.zip) and extract into csgo folder
2. Open the game and the console and type "_map prop_vehicle_driveable_"
3. The game will crash

**Comment by kisak-valve** [comment]
Hello @Benito1020, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1936. Closing as a duplicate.

**Comment by Benito1020** [comment]
Saturn34 commented on 19 Dec 2018.

2 years later, please fix it....
