### ISSUE TITLE
[STEAM] Switching between Linux/Windows causes games to update

### ISSUE THREAD

**Issue by mattrick** [ValveSoftware/steam-for-linux#700]
Mostsly these are only 1-100 mb updates per game, but sometimes I got message that executable file is corrupted and have to download whole game once again. As long as I update game and play on one OS, it's ok. When only I switch to the other, I get corrupted files and have to update.

OSes:
Ubuntu 12.10
Windows 8

**Comment by tambry** [comment]
I think this issue is still present for me on Windows 10 Anniversary and Ubuntu 16.10. Switching between Linux and Windows requires me to update the games that I updated on the other one, so I could play them there.

**Comment by kisak-valve** [comment]
Can someone please retest that this is an issue and that there are no shared folders involved?

This issue needs some hint of how the two installs of steam are interacting with each other to cause the corruption.

**Comment by tambry** [comment]
Could you clarify what you mean by shared folders?

My installations of Steam are separate on both Windows and Ubuntu, but they share a library folder, that I have located on another drive. Doing it this way in theory should allow the games to share content and avoid me needing to have separate game installations for Windows and Ubuntu (excluding minor platform-specific files such as executables). Unfortunately this does work and switching between Windows and Ubuntu requires me to re-download certain portions of games. For example, having Rocket League fully updated while on my Windows installation and then switching to Ubuntu, will require me to download about 3GB. After fully updating it on the Ubuntu installation and switching back to Windows will require me to download about 5GB.

I at this point try avoid updating and playing the games on my Ubuntu installation, as it would require me to update them once I'm back on Windows.

**Comment by kisak-valve** [comment]
As noted by @johndrinkwater, shared library folders deleting game files for other OSes was tracked at #546.

Provided you handle any permission issues, you can use game files from an existing steamapps folder to avoid downloading the OS independent content again. However, as you wrote, this will lead some content being removed that is not intended for the currently running OS.

It is at the discretion of each game dev to decide how much content is OS independent, or if they want to make their players download OS-specific content that is not expected to work on the current running system. This is not expected to change in the near future.
