### ISSUE TITLE
MacOS SteamCMD login not persisting between runs because it can't cache data

### ISSUE THREAD

**Issue by chriskck** [ValveSoftware/steam-for-linux#7000]
#### Your system information

* Steam client version: SteamCMD
* Distribution: MacOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On the MacOS, running SteamCMD and logging in always triggers the Steam Guard code. After some digging, I think that this is due to the login operation failing to write data to disk. This looks to be a new behavior as it was working properly previously.

#### Steps for reproducing this issue:

1. Install SteamCMD using brew (brew cask install steamcmd) 
2. Run 'steamcmd +login <username> <password>'; it'll prompt you for the Steam Guard code
3. Enter the Steam Guard code; the executable will retrieve the user profile - observe the Assertion errors
4. Exit the SteamCMD session and repeat Step 2 - you'll be prompted again for the Steam Guard code

#### Expected results

After logging in through steamcmd and entering the steam guard code, I should not need to revalidate and enter the steam guard code for subsequent login operations.

**Comment by kisak-valve** [comment]
Hello @chriskck, this issue tracker is intended for issues with the Steam for Linux client. Please use [Steam Support](https://help.steampowered.com/) to report issues with SteamCMD on MacOS.

**Comment by chriskck** [comment]
Here are the error messages I'm seeing when logging in.
![image](https://user-images.githubusercontent.com/1156022/78202448-36db5580-7449-11ea-964f-13a542b06372.png)
