### ISSUE TITLE
New map Anubis crashes game.

### ISSUE THREAD

**Issue by g572staem** [ValveSoftware/steam-for-linux#7001]
New map Anubis crashes game.

 "version" : "0.20200318.2"

* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes, up to date]

Ubuntu 18.04

Nvidia driver: 435.21

Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

from error.log
[0401/211247.537826:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.

Forums:
https://steamcommunity.com/app/730/discussions/0/2143092024468092209/

**Comment by Newbytee** [comment]
This is tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2379 by the way

**Comment by kisak-valve** [comment]
Closing as a duplicate.

**Comment by g572staem** [comment]
> This is tracked at [ValveSoftware/csgo-osx-linux#2379](https://github.com/ValveSoftware/csgo-osx-linux/issues/2379) by the way

I searched before I posted.  issues -> filter -> anubis

Go figure.

**Comment by Newbytee** [comment]
> I searched before I posted. issues -> filter -> anubis
> 
> Go figure.

I intended no offence, rather, I thought it might be useful to let you know where others are discussing it.
