### ISSUE TITLE
Scroll-clicking the links below the Play button in the new library opens a dead pop-up

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#7002]
#### Your system information

* Steam client version (build number or date): Mar 26 2020, at 22:46:20
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
![image](https://user-images.githubusercontent.com/4428753/78224407-ce33bd80-74c8-11ea-82f8-f42a1d1604c8.png)
Scroll/middle-clicking any of these buttons (located in the new library) opens a pop-up Steam browser window which subsequently has its focus stolen by the main Steam window where the content actually loads. The popped-up window stays blank but continues to exist.  

#### Steps for reproducing this issue:

1. View any given software in the new library
2. Scroll-click any of the buttons shown in the screenshot above
3. Observe that an empty window appears

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment]
The behaviour is somewhat inconsistent, but it does not seem to exist in the same manner any more, no.
