### ISSUE TITLE
Reinstall totaly or partial game ?

### ISSUE THREAD

**Issue by Christophedlr** [ValveSoftware/steam-for-linux#7003]
#### Your system information

* Steam client version (build number or date): Mar 26 2020, API Steam v020 version package 1585264767
* Distribution (e.g. Ubuntu): Debian Testing
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

After add a windows Steam directory in games directories list, my installed games are detected. but why reinstall the game completely instead of just downloading the game's executables and .so ?

The principe of not reinstall game (and delete the windows files), is used game in Windows AND linux (without having to reinstall the game each time or have a copy under Linux and a copy under Windows, thus consuming more space on the disk).

#### Steps for reproducing this issue:

1. Install Steam under windows and install a game compatible with linux (The Long Dark for example)
2. Install Steam under Linux (test with actual Debian Testing) and add Windows Steam directory in games directories list
3. Run the game (The Long Dark in my example), and look Steam reinstall 1.3 GB
4. Look into The Long Dark directory: the windows executable are deleted and replaced by linux executables/shell scripts, and a partial files or data are replaced but files is exactly size and data of windows version

#### Other informations
In logic, if the identical version windows and linux except the executables and shell scripts, Steam only must download the executables/shell scripts and not download other files.

In logic, Steam Linux did not delete windows executables/scripts, but just install Linux executables/scripts for use game in Windows and Linux without reinstall totaly or partial game.

**Comment by kisak-valve** [comment]
Hello @Christophedlr, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing a Steam Library between different OSes is not supported and may have unexpected behavior.
