### ISSUE TITLE
SteamWebHelper (possible) memory leak

### ISSUE THREAD

**Issue by FrankNoWar** [ValveSoftware/steam-for-linux#7004]
#### Your system information

* Steam client version (build number or date): March 26, 2020
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes (but doesn't affect current issue)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
* What I _expected_ should happen: Opening my Steam Client and seeing my games library, then playing a game.

* What _did_ happen: Steam Library didn't display, entire 16 GB memory got filled, then entire 24 GB Swap got filled, then computer stopped responding.

* Steam System Information: https://gist.github.com/FrankNoWar/3246d66a677aec55367fef350e00b7ad

#### Steps for reproducing this issue:

1. Open Steam Client (Runtime or Native, doesn't affect issue)
2. Wait for a few seconds
3. Computer hangs because of Out of memory condition (./steamwebhelper process can be still killed with htop or another utility but it requires a lot of patience)
4. If killed, SteamWebHelper comes back and grabs all memory available again.

**Comment by FrankNoWar** [comment]
Forgot to add... a few threads have been started on the Steam Forums, here is an example.

[Memory overflow caused by steam client, any idea how to fix it?](https://steamcommunity.com/discussions/forum/1/2155476542889599656/)

**Comment by TTimo** [comment]
note: the thread suggests this is observed on Windows as well

**Comment by FrankNoWar** [comment]
That’s what I found as well. And I forgot to close the issue as it resolved itself after a few days.
