### ISSUE TITLE
Gift dialog won't go away after accepting a gift

### ISSUE THREAD

**Issue by Xinayder** [ValveSoftware/steam-for-linux#7010]
#### Your system information

* Steam client version (build number or date): **April 3, 2020, 22:37:31**
* Distribution (e.g. Ubuntu): **Arch Linux**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
When receiving a gift, the gift dialog pops up. When you click accept, the confirmation dialog with the text ` You are about to add this item to your library: ` appears and it keeps loading infinitely. The "you've received a gift" window updates and says the game was added to your library, but the confirmation dialog is still "loading".

#### Steps for reproducing this issue:

1. Send a gift to your account
2. Accept the gift
3. Watch as the confirmation dialog displays a loading spinner infinitely.

![](https://i.imgur.com/AeS13iE.png)

**Comment by kisak-valve** [comment]
Hello @Xinayder, have you seen this issue since it was initially reported?

**Comment by kisak-valve** [comment]
Closing pending feedback.
