### ISSUE TITLE
Enabling Shader cache causes high cpu usage at idle

### ISSUE THREAD

**Issue by siyia2** [ValveSoftware/steam-for-linux#7013]
#### Your system information

Archlinux fully updated
Build: April 04 2020

When i launch a proton game with shader cache enabled in settings and then exit the game, steam consumes 12%-13% cpu for no apparrent reason.Proton version is irrelevant.

#### Steps for reproducing this issue:

1. Open Steam and launch a proton game
2. Exit the game normally
3. Check your Steam cpu usage

**Comment by kisak-valve** [comment]
Hello @siyia2, this issue is already being tracked at #6332. Closing as a duplicate.

**Comment by siyia2** [comment]
ok fair enough
