### ISSUE TITLE
Content is black

### ISSUE THREAD

**Issue by anohren** [ValveSoftware/steam-for-linux#7018]
#### Your system information

* Steam client version (build number or date): Don't know since the About Steam window is as large as my thumb and non-resizable. Latest as of time of writing.
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: Yes and No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In response to https://github.com/ValveSoftware/steam-for-linux/issues/6961#issuecomment-610647619

All web content in the client is black

#### Steps for reproducing this issue:
Not known

#### `$ ps aux --forest | grep webhelper`
    user   5550  0.0  0.0  11784   916 pts/0    S+   15:36   0:00          \_ grep --color=auto webhelper

#### `cef_log.txt`

    [0408/154134.207795:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
    [0408/154134.605426:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process

<details>
<summary>System info</summary>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Athlon(tm) 64 Processor 3700+
    CPU Family:  0xf
    CPU Model:  0x27
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2200 Mhz
    1 logical processor
    1 physical processor
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Unsupported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 19.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20200318.2

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 550 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 390.129
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1244
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18.66" x 11.65" (21.97" diag)
                                            47.4cm x 29.6cm (55.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 15 HDMI/DP

Memory:
    RAM:  2992 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  sv_SE.UTF-8
    Total Hard Disk Space Available:  54325 Mb
    Largest Free Hard Disk Block:  29336 Mb

```

</details>

**Comment by TTimo** [comment]
Thanks. And that's the only two lines you have in your `cef_log.txt`?

**Comment by kisak-valve** [comment]
Hello @anohren, you've encountered #4196. The lack of CMPXCHG16B in your processor makes it older than the minimum requirements for Steam on Linux as noted at https://github.com/ValveSoftware/steam-for-linux#hardware-and-software-requirements.

**Comment by anohren** [comment]
I see, I was unaware of that. Thanks for the info! 

That's a commendable compilation of specific requirements. Unfortunately I never thought to look up requirements after stream installed and ran successfully a year ago. Maybe you can highlight in the client somehow when it runs on hardware that is not supported.
