### ISSUE TITLE
Unable to download OpenGL.

### ISSUE THREAD

**Issue by Chaitanya2923** [ValveSoftware/steam-for-linux#7019]
* Distribution : Ubuntu-19.10
* Have you checked for system updates?: Yes

I tried to install OpenGL on my system using the command :

sudo apt-get install libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386

But unfortunately, I get this error : 

E: Unable to locate package libgl1-mesa-dri:i386,
E: Unable to locate package libgl1-mesa-glx:i386,

What's the actual problem, and how to resolve it? I'm quite new to Ubuntu.
Thank you.

**Comment by kisak-valve** [comment]
Hello @Chaitanya2923, Ubuntu's repositories definitely provide those packages.

What does running `apt policy libgl1-mesa-dri libgl1-mesa-dri:i386` give you?

**Comment by smcv** [comment]
```
sudo apt-get install libgl1-mesa-dri:i386, libgl1-mesa-glx:i386, libc6:i386
```

Remove the commas:

```
sudo apt-get install libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386
```

**Comment by listen1379** [comment]
Valve idea: per-distro instructions on the Steam download page. The Ubuntu package, for example, depends on these OpenGL i386 packages. (Checked on Ubuntu 19.10.)

**Comment by listen1379** [comment]
Thing to see: OpenSuSE One Click Install. I'm not sure how popular this distro or this feature remain, but some time ago it was very cool. Website has "YMP" manifest file that has list of packages and/or repositories to add. YaST software manager asks permission to add any repositories/keys, then proceeds to software selection manager with packages and their dependencies "checked" for installation. It will also ask about installing "recommended" deps/packages.

**Comment by Chaitanya2923** [comment]
> Hello @Chaitanya2923, Ubuntu's repositories definitely provide [those packages](https://packages.ubuntu.com/eoan/libgl1-mesa-dri).
> 
> What does running `apt policy libgl1-mesa-dri libgl1-mesa-dri:i386` give you?

Thanks for the reply. Actually installing freeglut helped me overcome all of these complexities :)
