### ISSUE TITLE
Crash on Launch `libGL error: No matching fbConfigs or visuals found`

### ISSUE THREAD

**Issue by jakerobers** [ValveSoftware/steam-for-linux#7021]
## Your system information
* Steam client version (build number or date): 
```
Version         : 1.0.0.61-4
Architecture    : x86_64
Build Date      : Tue 18 Feb 2020 03:51:36 AM CST
Install Date    : Wed 08 Apr 2020 05:49:14 PM CDT
Validated By    : Signature
```

* Distribution: Arch Linux. `uname --all` returns:
```
Linux penguin 5.6.2-arch1-2 #1 SMP PREEMPT Sun, 05 Apr 2020 05:13:14 +0000 x86_64 GNU/Linux
```

* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

- Yesterday the steam client was working perfectly.
- Today I ran `pacman -Syu` to update the system packages. I noticed that there was a new kernel release.
- The kernel release broke the proprietary nvidia driver. This is not unusual, so I updated to the latest graphics driver release that my laptop can support (https://aur.archlinux.org/packages/nvidia-390xx).
- The graphics driver is working again, but steam crashes on load.
- I ran `glxinfo` and everything seems to be okay.

Steam gives a stacktrace of:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1586022601)
Installing breakpad exception handler for appid(steam)/version(1586022601)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  154
Serial number of failed request:  52
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  154
Serial number of failed request:  53
xerror_handler: X failed, continuing
assert_20200408175850_1.dmp[4163]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200408175850_1.dmp
/home/jake/.local/share/Steam/steam.sh: line 722:  4125 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20200408175850_1.dmp[4163]: Finished uploading minidump (out-of-process): success = yes
assert_20200408175850_1.dmp[4163]: response: CrashID=bp-250c566f-d607-4e00-aaad-723322200408
assert_20200408175850_1.dmp[4163]: file ''/tmp/dumps/assert_20200408175850_1.dmp'', upload yes: ''CrashID=bp-250c566f-d607-4e00-aaad-723322200408''
```

#### Steps for reproducing this issue:

1. Install kernel version 5.6.2
2. Install nvidia 390xx
3. Run steam client

**Comment by jakerobers** [comment]
I have a feeling this is probably a driver issue, but I'm not quite sure where to go from here.

**Comment by kisak-valve** [comment]
Hello @jakerobers, nVidia's proprietary requires that the running kernel module version, the 64 bit userspace version, and the 32 bit userspace version match in order to work properly. The scenario you've described is that you've updated the kernel module and the 64 bit userspace libraries, but not the 32 bit userspace libraries.

You should be able to test this with `glxinfo32 -B` from `lib32-mesa-demos`. My guess is that you need https://aur.archlinux.org/packages/lib32-nvidia-390xx-utils/ to match the rest of your driver install.

**Comment by jakerobers** [comment]
This fixed it! Thank you for explaining this in simple terms. I had no idea that I needed to match the 64 bit to the 32 bit. Sorry for making this a tech support issue on your end 😅
