### ISSUE TITLE
Steam Crashes when trying to set Properties of the game

### ISSUE THREAD

**Issue by Shadistikk** [ValveSoftware/steam-for-linux#7024]
#### Your system information

* Steam client version (build number or date): Apr 4 2020
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No (Tested with both Stable and Beta)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam is only crashing with 2 Games for me (Risk of Rain 2, Worms Armageddon. Have tested with 10 other games)
when trying to left click and go to Properties. This happens both with Stable and Beta.

#### Steps for reproducing this issue:

1. Test with games that i mention and try to access games Properties. With Risk of Rain 2 it should
tell with popup that it cannot find games exe file and then it would crash. With Worms Armageddon freshly installed crash should happen immediately.

`/home/sadistic/.local/share/Steam/steam.sh: line 722: 24562 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
`

[assert_20200410182749_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/4462268/assert_20200410182749_1.zip)

**Comment by kisak-valve** [comment]
Hello @Shadistikk, this issue is already being tracked at #6986 (or possibly #6757). Closing as a duplicate.
