### ISSUE TITLE
Percentage of achievements completed is obstructed by friends playing indicator

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#7026]
#### Your system information

* Steam client version (build number or date): Apr 8 2020, at 20:52:25
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

![image](https://user-images.githubusercontent.com/4428753/79047529-5fb4d500-7c17-11ea-9322-448b0e1aa034.png)
The percentage of achievements completed is obstructed. 

#### Steps for reproducing this issue:

1. Sort a shelf by % of Achievements Complete in the collections view
2. Have one of the games in this shelf be played by a friend
3. Observe the percentage being obstructed by the friends playing indicator

**Comment by kisak-valve** [comment]
In a quick test:

Affected: Steam Library Home -> All Games section -> Sort by `% of Achievements Complete`
Not affected: Steam Library -> User made Collection -> Sort by `% of Achievements Complete`

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment]
I can't reproduce it any more. It seems like the UI has changed since I reported this.
