### ISSUE TITLE
Several buttons broken in library game header for Interrogation: You will be deceived Demo

### ISSUE THREAD

**Issue by codingthat** [ValveSoftware/steam-for-linux#7032]
![Library game header](https://user-images.githubusercontent.com/26723818/79378695-0d98ea00-7f5e-11ea-854d-e31230921169.png)

#### Your system information

* Steam client version (build number or date): Apr 4 2020 at 00:37:27
* Distribution (e.g. Ubuntu): Linux Mint 19.3 x64
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

I expected all the links to go to pages specific to the game, as they do for several other games I tried just now.

Only on Interrogation: You will be deceived Demo, which seems to be the only one awaiting an update (I also have Dicey Dungeons with an update in progress but paused—not quite the same thing, I guess) in case that's not a coincidence, are most of the buttons broken.  (It's also the only demo, I think...)

In particular, clicking Store Page, Community Hub, Discussions, or Guides all bring me to the COMMUNITY tab (of the STORE | LIBRARY | COMMUNITY | (ME) tabs at the top) for several seconds but with the main page underneath said tabs blank; after that it seems to give up and brings me to the main front store page of Steam, not specific to the game.

The Find Groups and Support links both work fine.

#### Steps for reproducing this issue:

1. Start Steam
2. Click LIBRARY
3. Click "Interrogation: You will be deceived Demo"
4. Click any of the 4 above-mentioned broken links

**Comment by kisak-valve** [comment]
Hello @codingthat, are you still experiencing this issue? The demo variant of this game doesn't appear to be generally available anymore.

**Comment by codingthat** [comment]
@kisak-valve Sorry, unable to retest: I eventually bought the full game so the demo variant doesn't show for me anymore either.
