### ISSUE TITLE
Steam games don't replay any downloaded shaders

### ISSUE THREAD

**Issue by NikoBellicRU** [ValveSoftware/steam-for-linux#7039]
I'm still a bit confused on this, is the Fossilize replay On by default? Cause i dont notice any diference in reduced stutter when i enable the shaders (only after playing the game for a while), also i think that the shaders that are downloaded are not being replayed cause when i enter the game it creates a new .foz file and the size of it keeps increasing the more i play the game. Every game that i tried had this result so i dont know if this is a driver problem / nvidia. . .

**Comment by HansKristian-Work** [comment]
Fossilize captures are not replayed by default at this time.

**Comment by NikoBellicRU** [comment]
Oh that makes sense, is there any command i can use to enable replay?

**Comment by kisak-valve** [comment]
Hello @NikoBellicRU, are you still experiencing this issue on an up to date system? From a high level point of view, this should be controlled by the Shader Pre-Caching section of Steam's settings.

**Comment by kisak-valve** [comment]
Closing as outdated.

**Comment by NikoBellicRU** [comment]
Hi, i'm bit late but anyway i haven't had any issues with the replay for a while now, all good.
