### ISSUE TITLE
Steam Linux Beta and non beta consumes all memory

### ISSUE THREAD

**Issue by Psilovybin** [ValveSoftware/steam-for-linux#7042]
#### Your system information

* Steam client version (build number or date): April 16th, 2020 @ 23:16:21
* Distribution (e.g. Ubuntu): Arch Linux 5.6.2-zen1-2
* Opted into Steam client beta?: [Yes/No] Yes, but also in regular
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Seems before 5.6 kernel update, it was working fine, I have since upgraded OS with about 2GB updates.  I'm only now posting about this because i hoped it would iron out in a week or so so i've been in Windows until but this is too long.  in the console window, the only valid error to this issue I get is:
steamwebhelper.sh: line 23: 14038 Killed ./steamwebhelper "$@"
it will load the games window, memory will fill up, then steamwebhelper restarts memory clears and the process starts all over again.  Video of this is at the end of this post.  I can interact with the Steam gui up until memory fills up, then it freezes and when process is restart, i can interact with the GUI again.  I've cleared web cache thru steam.  running with -no-browser it doesn't do this at all but i don't have access to my games

#### Steps for reproducing this issue:

1. Running steam
2. this happens
3. 

https://www.youtube.com/watch?v=C53cZlBbj3U

**Comment by kisak-valve** [comment]
Looks like a continuation of #7004.

**Comment by Psilovybin** [comment]
> Looks like a continuation of #7004.

if any information you need, let me know

**Comment by dearlygparted** [comment]
> Looks like a continuation of #7004.

That issue has been closed because the issue apparently "resolved itself". However, this issue is *not* solved. I just experienced this. Today after a fresh boot, I launched Steam and after about 30 minutes I noticed that it had eaten up 10GB of RAM and CPU usage was at about 40%. Tried to exit Steam, but it was unresponsive. Had to kill the process. 

Please fix this Valve. Many users are noticing that the Steam client has become bloated, slow, and generally terrible after recent updates.

**Comment by soredake** [comment]
And https://github.com/ValveSoftware/steam-for-linux/issues/7037

**Comment by Bananaman** [comment]
Fedora 35, with the native RPM Fusion "steam" package:

- SteamWebHelper has a memory leak. It always balloons to huge memory and I have to restart Steam every few days.
- On my 64 GB machine, SteamWebHelper used 27 GB RAM now when I closed Steam.
- This repeats itself every time.
- I wonder if it's related to embedded media (such as YouTube videos) in chat windows. Not sure.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by FrankNoWar** [comment]
All good for me, the client works relatively smoothly on my Arch box (and perfectly on my Deck too 🤘🏻)

**Comment by kisak-valve** [comment]
Closing pending feedback.
