### ISSUE TITLE
"Not enough disk space avaliable" despite having plenty free space

### ISSUE THREAD

**Issue by ErisuKuraku** [ValveSoftware/steam-for-linux#7044]
<details>
<summary>System Information</summary>
<br>

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD A6-7310 APU with AMD Radeon R4 Graphics    
    CPU Family:  0x16
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 20.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20200318.2

Video Card:
    Driver:  X.Org AMD KABINI (DRM 2.50.0, 5.4.0-24-generic, LLVM 9.0.1)
    Driver Version:  4.5 (Compatibility Profile) Mesa 20.0.4
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x9851
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.74" x 10.55" (21.50" diag)
                                            47.6cm x 26.8cm (54.6cm diag)
    Primary VRAM: 1024 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  6862 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Total Hard Disk Space Available:  115534 Mb
    Largest Free Hard Disk Block:  14447 Mb

Steam Linux Runtime Information:
{
  "can-write-uinput" : true,
  "steam-installation" : {
    "path" : "/home/ellis/.local/share/Steam",
    "data_path" : "/home/ellis/.local/share/Steam",
    "issues" : [
    ]
  },
  "runtime" : {
    "path" : "/home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20200318.2",
    "issues" : [
    ],
    "pinned_libs_32" : {
      "list" : [
        "   581923      4 drwxrwxr-x   2 ellis    ellis        4096 Apr 16 21:18 pinned_libs_32",
        "   539307      4 lrwxrwxrwx   1 ellis    ellis         100 Apr 16 21:17 pinned_libs_32/libvulkan.so.1 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libvulkan.so.1.2.135",
        "   539293      0 -rw-rw-r--   1 ellis    ellis           0 Apr 16 21:18 pinned_libs_32/has_pins",
        "   539292      4 -rw-rw-r--   1 ellis    ellis          80 Apr 16 21:17 pinned_libs_32/system_libdbus-1.so.3",
        "   539229      4 lrwxrwxrwx   1 ellis    ellis          94 Apr 16 21:17 pinned_libs_32/libdbus-1.so.3 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libdbus-1.so.3.5.8",
        "   539310      4 -rw-rw-r--   1 ellis    ellis          72 Apr 16 21:18 pinned_libs_32/system_libGLU.so.1",
        "   539308      4 -rw-rw-r--   1 ellis    ellis          80 Apr 16 21:17 pinned_libs_32/system_libvulkan.so.1",
        "   539309      4 lrwxrwxrwx   1 ellis    ellis          99 Apr 16 21:18 pinned_libs_32/libGLU.so.1 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libGLU.so.1.3.08004"
      ]
    },
    "pinned_libs_64" : {
      "list" : [
        "   581924      4 drwxrwxr-x   2 ellis    ellis        4096 Apr 16 21:18 pinned_libs_64",
        "   539294      4 lrwxrwxrwx   1 ellis    ellis         102 Apr 16 21:17 pinned_libs_64/libvulkan.so.1 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.135",
        "   539304      4 -rw-rw-r--   1 ellis    ellis          95 Apr 16 21:17 pinned_libs_64/system_libdbusmenu-gtk.so.4",
        "   539297      4 lrwxrwxrwx   1 ellis    ellis         107 Apr 16 21:17 pinned_libs_64/libpangox-1.0.so.0 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libpangox-1.0.so.0.3000.0",
        "   539296      0 -rw-rw-r--   1 ellis    ellis           0 Apr 16 21:17 pinned_libs_64/has_pins",
        "   539306      4 -rw-rw-r--   1 ellis    ellis          76 Apr 16 21:17 pinned_libs_64/system_libGLU.so.1",
        "   539299      4 lrwxrwxrwx   1 ellis    ellis          98 Apr 16 21:17 pinned_libs_64/libcurl.so.4 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0",
        "   539302      4 -rw-rw-r--   1 ellis    ellis          97 Apr 16 21:17 pinned_libs_64/system_libdbusmenu-glib.so.4",
        "   539301      4 lrwxrwxrwx   1 ellis    ellis         108 Apr 16 21:17 pinned_libs_64/libdbusmenu-glib.so.4 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4.0.13",
        "   539303      4 lrwxrwxrwx   1 ellis    ellis         107 Apr 16 21:17 pinned_libs_64/libdbusmenu-gtk.so.4 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4.0.13",
        "   539295      4 -rw-rw-r--   1 ellis    ellis          84 Apr 16 21:17 pinned_libs_64/system_libvulkan.so.1",
        "   539305      4 lrwxrwxrwx   1 ellis    ellis         101 Apr 16 21:17 pinned_libs_64/libGLU.so.1 -> /home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.08004",
        "   539300      4 -rw-rw-r--   1 ellis    ellis          78 Apr 16 21:17 pinned_libs_64/system_libcurl.so.4",
        "   539311      0 lrwxrwxrwx   1 ellis    ellis          12 Apr 16 21:18 pinned_libs_64/libcurl.so.3 -> libcurl.so.4",
        "   539298      4 -rw-rw-r--   1 ellis    ellis          90 Apr 16 21:17 pinned_libs_64/system_libpangox-1.0.so.0"
      ]
    }
  },
  "os-release" : {
    "id" : "ubuntu",
    "id_like" : [
      "debian"
    ],
    "name" : "Ubuntu",
    "pretty_name" : "Ubuntu 20.04 LTS",
    "version_id" : "20.04",
    "version_codename" : "focal"
  },
  "container" : {
    "type" : "none"
  },
  "driver_environment" : [
  ],
  "architectures" : {
    "i386-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /usr/lib/x86_64-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS64\nERROR: [Loader Message] Code 0 : /home/ellis/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS64\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\n/usr/src/packages/BUILD/vulkaninfo/vulkaninfo.h:479: failed with ERROR_INITIALIZATION_FAILED\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 255
        },
        "glx/gl" : {
          "messages" : "libGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: pci id for fd 4: 1002:9851, driver radeonsi\nlibGL: MESA-LOADER: dlopen(/usr/lib/i386-linux-gnu/dri/radeonsi_dri.so)\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Using DRI3 for screen 0\n",
          "renderer" : "AMD KABINI (DRM 2.50.0, 5.4.0-24-generic, LLVM 9.0.1)",
          "version" : "4.5 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd",
          "issues" : [
            "cannot-draw"
          ],
          "terminating-signal" : 6,
          "terminating-signal-name" : "Aborted"
        },
        "egl_x11/gl" : {
          "messages" : "Waffle error: 0x1 WAFFLE_ERROR_FATAL: dlopen(\"libEGL.so.1\") failed: libEGL.so.1: wrong ELF class: ELFCLASS64\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "unknown",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        },
        "egl_x11/glesv2" : {
          "messages" : "Waffle error: 0x1 WAFFLE_ERROR_FATAL: dlopen(\"libEGL.so.1\") failed: libEGL.so.1: wrong ELF class: ELFCLASS64\n",
          "renderer" : null,
          "version" : null,
          "library-vendor" : "unknown",
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/vmwgfx_dri.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/iHD_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so.1",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/i386-linux-gnu/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/i386-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/i386-linux-gnu/libGLX_mesa.so.0.0.0"
        }
      ]
    },
    "x86_64-linux-gnu" : {
      "can-run" : true,
      "library-issues-summary" : [
      ],
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : "ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32\nERROR: [Loader Message] Code 0 : /home/ellis/.local/share/Steam/ubuntu12_32/steamoverlayvulkanlayer.so: wrong ELF class: ELFCLASS32\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\n/usr/src/packages/BUILD/vulkaninfo/vulkaninfo.h:479: failed with ERROR_INITIALIZATION_FAILED\n",
          "renderer" : null,
          "version" : null,
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 255
        },
        "glx/gl" : {
          "messages" : "libGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: pci id for fd 4: 1002:9851, driver radeonsi\nlibGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so)\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Can't open configuration file /etc/drirc: No such file or directory.\nlibGL: Can't open configuration file /home/ellis/.drirc: No such file or directory.\nlibGL: Using DRI3 for screen 0\n",
          "renderer" : "AMD KABINI (DRM 2.50.0, 5.4.0-24-generic, LLVM 9.0.1)",
          "version" : "4.5 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd",
          "issues" : [
            "cannot-draw"
          ],
          "terminating-signal" : 6,
          "terminating-signal-name" : "Aborted"
        },
        "egl_x11/gl" : {
          "renderer" : "AMD KABINI (DRM 2.50.0, 5.4.0-24-generic, LLVM 9.0.1)",
          "version" : "4.5 (Compatibility Profile) Mesa 20.0.4",
          "library-vendor" : "glvnd"
        },
        "egl_x11/glesv2" : {
          "renderer" : "AMD KABINI (DRM 2.50.0, 5.4.0-24-generic, LLVM 9.0.1)",
          "version" : "OpenGL ES 3.2 Mesa 20.0.4",
          "library-vendor" : "glvnd"
        }
      },
      "dri_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i915_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i965_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/iris_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/kms_swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r200_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r300_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r600_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeon_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/virtio_gpu_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/zink_dri.so"
        }
      ],
      "va-api_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so"
        },
        {
          "library_path" : "/home/ellis/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/dri/dummy_drv_video.so"
        }
      ],
      "vdpau_drivers" : [
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nouveau.so",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_nouveau.so.1",
          "library_link" : "libvdpau_nouveau.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r300.so.1",
          "library_link" : "libvdpau_r300.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_r600.so.1",
          "library_link" : "libvdpau_r600.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_radeonsi.so.1",
          "library_link" : "libvdpau_radeonsi.so.1.0.0"
        },
        {
          "library_path" : "/usr/lib/x86_64-linux-gnu/vdpau/libvdpau_trace.so.1",
          "library_link" : "libvdpau_trace.so.1.0.0"
        }
      ],
      "glx_drivers" : [
        {
          "library_soname" : "libGLX_indirect.so.0",
          "library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0"
        },
        {
          "library_soname" : "libGLX_mesa.so.0",
          "library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0"
        }
      ]
    }
  },
  "locale-issues" : [
  ],
  "locales" : {
    "<default>" : {
      "resulting-name" : "en_GB.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "C" : {
      "resulting-name" : "C",
      "charset" : "ANSI_X3.4-1968",
      "is_utf8" : false
    },
    "C.UTF-8" : {
      "resulting-name" : "C.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    },
    "en_US.UTF-8" : {
      "resulting-name" : "en_US.UTF-8",
      "charset" : "UTF-8",
      "is_utf8" : true
    }
  },
  "egl" : {
    "icds" : [
      {
        "json_path" : "/usr/share/glvnd/egl_vendor.d/50_mesa.json",
        "library_path" : "libEGL_mesa.so.0"
      }
    ]
  },
  "vulkan" : {
    "icds" : [
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/intel_icd.x86_64.json",
        "library_path" : "/usr/lib/x86_64-linux-gnu/libvulkan_intel.so",
        "api_version" : "1.2.131"
      },
      {
        "json_path" : "/usr/share/vulkan/icd.d/radeon_icd.i686.json",
        "library_path" : "/usr/lib/i386-linux-gnu/libvulkan_radeon.so",
        "api_version" : "1.2.128"
      }
    ]
  }
}

The Steam Linux Runtime container tool is not installed.
</details>

When trying to install CS:GO it claims I have not got enough space on my computer despite the file manager saying 121GB avalible and after going into download settings steam thinks ive got 15.14GB left. This is the same for other software larger then 15GB

![Screenshot from 2020-04-17 12-53-31](https://user-images.githubusercontent.com/25765196/79566543-a2a8f980-80aa-11ea-9a49-8e69532f3ae6.png)
![Screenshot from 2020-04-17 12-55-27](https://user-images.githubusercontent.com/25765196/79566600-bce2d780-80aa-11ea-8464-9b1a26042094.png)

**Comment by kisak-valve** [comment]
Hello @ErisuKuraku, what filesystem are you using with your home folder?

**Comment by ErisuKuraku** [comment]
@kisak-valve i'm using EXT4

**Comment by marian42** [comment]
Today I had the issue of Steam filling up the hard drive with a log file, it could be related to this. #7047

**Comment by ErisuKuraku** [comment]
@marian42 no its not that, the hard drive isnt full but steam is reporting that it is and wont install games larger than 15GB

**Comment by byte1024** [comment]
> @marian42 no its not that, the hard drive isnt full but steam is reporting that it is and wont install games larger than 15GB

> When trying to install CS:GO it claims I have not got enough space on my computer despite the file manager saying 121GB avalible and after going into download settings steam thinks ive got 15.14GB left. This is the same for other software larger then 15GB

> [Screenshot from 2020-04-17 12-55-27](https://user-images.githubusercontent.com/25765196/79566600-bce2d780-80aa-11ea-8464-9b1a26042094.png)

It is bit of a double take when looking at that **but the first number** is the free space. In the image of your file manager, you have 15.1GB free out of a total of 121.1GB. Steam is correct.

There is nothing wrong here and should be closed.

**Comment by ErisuKuraku** [comment]
Thanks, I Apologise for wasting everyones time.
