### ISSUE TITLE
Steam remote play of adventure palls from win10 to linux crashed pc

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/steam-for-linux#7045]
#### Your system information

* Steam client version (build number or date): 4/4/2020
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam remote play of adventure palls from a win10 pc to Linux pc crashed it, I could see the image of the game for a moment them it all became unresponsive, hard reset.
The Linux client was the one that crashed.

System info:
https://gist.github.com/monterrr/59a310447081362021fc57a057beb8ae#file-gistfile1-txt

#### Steps for reproducing this issue:

1. Start steam remote play of adventure palls from win10 to linux

**Comment by kisak-valve** [comment]
Hello @monterrr, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please clarify if the host or client crashed.

In general, no OpenGL application should be capable of causing a full system lockup, which hints that you've encountered a video driver issue.

**Comment by monterrr** [comment]
Bug report edited to clarify and add the system info.

**Comment by kisak-valve** [comment]
Hello @andreldmonteiro, are you still experiencing this issue on an up to date system?

**Comment by andreldmonteiro** [comment]
Hi, I encounter the issue no more.
