### ISSUE TITLE
Move install Folder dialog have always-on-top enable

### ISSUE THREAD

**Issue by Krafting** [ValveSoftware/steam-for-linux#7049]
### Your system information

* Steam client version (build number or date): 4 04 2020
* Distribution (e.g. Ubuntu): Mint 19.3 (Ubuntu 18.04)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When you move a game to a different drive/Library, the dialog is always on top, which isquite annoying when we are trying to do other stuff while waiting this to finish, it would be great to have the option to minimize itand not being on top of any windows (just the steam windows at least)
here is a screenshot of the dialog:
http://i.imgur.com/ReUhfRe.png

#### Steps for reproducing this issue:

1. Move a Game to a different Location
2. Suffer for a while

**Comment by kisak-valve** [comment]
Hello @Krafting, this issue is already being tracked at #4841. Closing as a duplicate.
