### ISSUE TITLE
error.log grows exponentially - 180GB

### ISSUE THREAD

**Issue by RickAndTired** [ValveSoftware/steam-for-linux#7051]
#### Your system information

* Steam client version (build number or date): 1586022601 - Apr 4 2020
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

error.log grows exponentially after exiting Steam. It got to 180GB before I killed the Steam process.
This has happened multiple times, but not every time.
It started at nothing or close to nothing and grew to 180GB after a single Steam exit.
It does not slowly grow after each exit.

#### Steps for reproducing this issue:

1. Exit Steam

**Comment by kisak-valve** [comment]
Hello @RickAndTired, this issue is already being tracked at #6911. Please opt into Steam's client beta and retest.

Closing as a duplicate.
