### ISSUE TITLE
[beta] libcef does not work with steam-runtime libdbus

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#7058]
uptodate beta client:if you use the steam-runtime libdbus, the client will break and will periodically output "STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: ./libcef.so: undefined symbol: dbus_validate_bus_name"

you can remove libdbus from the steam runtime distribution or update it.

**Comment by sylware** [comment]
still there... this is the last pinned library (64bits only) required to run google libcef.

**Comment by smcv** [comment]
This was probably resolved by the changes in early to mid September 2021 that fixed #7935.

The mini-runtime used by the `steamwebhelper`, `~/.steam/root/ubuntu12_64/steam-runtime-heavy`, now contains its own `libdbus-1.so.3` which is newer than the one in `~/.steam/root/ubuntu12_32/steam-runtime` (and in particular, it implements `dbus_validate_bus_name()`).

**Comment by kisak-valve** [comment]
Closing per the last comment.
