### ISSUE TITLE
cminterface.cpp (2812) error

### ISSUE THREAD

**Issue by TH3AL3X** [ValveSoftware/steam-for-linux#7063]
This morning for no reason the server of a game has stopped working, then and tried to get into steamcmd and the boot did not work, it stayed in the update ... and tried to reinstall it, change DNS, remove certificates and nothing could not reach that they work

**OS: Ubuntu 18.04**

![image](https://user-images.githubusercontent.com/13141042/80217374-dd2d0c00-863f-11ea-936f-9f9d7c91f3d3.png)

**Comment by TH3AL3X** [comment]
Game server too 
![image](https://user-images.githubusercontent.com/13141042/80217430-f766ea00-863f-11ea-9a75-4e15a9f74235.png)

**Comment by kisak-valve** [comment]
Hello @TH3AL3X, this is a fairly blind guess, but please check if your server has `libnss-resolve:i386` with something like `apt policy libnss-resolve:i386`. If it doesn't, please test if adding it has an effect.

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/80233102-428bf780-8656-11ea-9ff6-43ba4bae80e1.png)

![image](https://user-images.githubusercontent.com/13141042/80233092-3ef87080-8656-11ea-88c8-a5c58a025d13.png)

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/80234346-4de02280-8658-11ea-80dd-bc5661b8cc28.png)
My server ip: 78.47.38.22

As I said it has been working for 4 months so far, this morning everything stopped working without reason and without touching anything

**Comment by TH3AL3X** [comment]
[tmp dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/4531635/tmp.dumps.zip)
I don't know if this is the error log of steam

**Comment by TH3AL3X** [comment]
[logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/4531672/logs.zip)

**Comment by TH3AL3X** [comment]
I reinstalled my machine, and still not working....

**Comment by TH3AL3X** [comment]
My IP Server got blacklisted by no reasons anyways ty for the support
