### ISSUE TITLE
Crash when accessing proprieties of a game with a non-existing proton version

### ISSUE THREAD

**Issue by MegWATTT** [ValveSoftware/steam-for-linux#7065]
#### Your system information

* Steam client version (build number or date): 1587611513
* Distribution (e.g. Ubuntu): Ubuntu 19.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crash when accessing proprieties of a game where a custom proton (in "compatibilitytools.d" folder) version was selected, but doesn't exist in the folder.

Installing this game will also download nothing, and running the game won't work as the executable is not here.

#### Steps for reproducing this issue:

1. Access proprieties of a game and force a proton version which exist in "compatibilitytools.d" folder
2. Close Steam
3. Remove the proton version from "compatibilitytools.d" folder
4. Restart steam
5. Open proprieties of the game. Steam crashes.

**Comment by kisak-valve** [comment]
Hello @MegWATTT, this issue is already being tracked at #6986. Closing as a duplicate.
