### ISSUE TITLE
Steam Does Not Start - Crashes on (X)ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by securerootd** [ValveSoftware/steam-for-linux#7067]
#### Your system information

* Package: steam-launcher
* Version: 1:1.0.0.62
* Distribution: (X)Ubuntu 20.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes on start - do not start.
Crash log details here : https://gist.github.com/securerootd/9ee87c87a44f7503cbd3a6732edd0320#file-steam-crash-log-xubuntu-focal-txt

#### Steps for reproducing this issue:

1.  Open steam
2.  Wait for steam to install dependencies and download files
3.  Enjoy steam crashing
[steam_crash_log_ubuntu_focal.txt](https://github.com/ValveSoftware/steam-for-linux/files/4532823/steam_crash_log_ubuntu_focal.txt)

**Comment by securerootd** [comment]
Here are the system details

**Hardware**

`hwinfo --short
cpu:                                                            
                       Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1866 MHz
                       Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1828 MHz
                       Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1939 MHz
                       Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1900 MHz
keyboard:
  /dev/input/event4    Dell KB216 Wired Keyboard
  /dev/input/event2    AT Translated Set 2 keyboard
mouse:
  /dev/input/mice      Dell MS116 USB Optical Mouse
  /dev/input/mice      Elan Touchpad
monitor:
                       N156BGA-EA2 LCD Monitor
graphics card:
                       Intel HD Graphics 520
sound:
                       Intel Sunrise Point-LP HD Audio
storage:
                       Intel Sunrise Point-LP SATA Controller [AHCI mode]
network:
  wlp2s0               Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter
  enp1s0               Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  lo                      Loopback network interface
  enp1s0             Ethernet network interface
  wlp2s0              Ethernet network interface
disk:
  /dev/sda             ST1000LM035-1RK1
usb controller:
                       Intel Sunrise Point-LP USB 3.0 xHCI Controller
bridge:
                       Intel Sunrise Point-LP PCI Express Root Port #5
                       Intel Sunrise Point-LP LPC Controller
                       Intel Sunrise Point-LP PCI Express Root Port #6
                       Intel Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM 
`

**Software**

`lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
`

**Comment by securerootd** [comment]
Adding DRI 3 to intel Xorg configuration works as a fix here:

/etc/X11/xorg.conf.d/20-intel.conf 

Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "sna"
   Option      "TearFree" "true"
   Option      "DRI"    "3"
EndSection

**Comment by rclortwein** [comment]
I have the same problem!
after the application has been updated, it no longer runs.

**Comment by rclortwein** [comment]
Hello Friend
all right?
did you get an answer to solve this problem?
thankful

**Comment by RRAlex** [comment]
Same situation on Ubuntu 19.10, it updates and then exits.

```
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/user/.local/share/Steam/ubuntu12_32/steam
[2020-05-01 09:23:50] Startup - updater built Apr 27 2020 21:53:21
Installing breakpad exception handler for appid(steam)/version(1588032389)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  52
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1588032389)
[2020-05-01 09:23:50] Checking for update on startup
[2020-05-01 09:23:50] Checking for available updates...
[2020-05-01 09:23:50] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1588032389)
[2020-05-01 09:23:50] Download skipped: /client/steam_client_ubuntu12 version 1588032389, installed version 1588032389
[2020-05-01 09:23:50] Nothing to do
[2020-05-01 09:23:50] Verifying installation...
[2020-05-01 09:23:50] Performing checksum verification of executable files
[2020-05-01 09:23:51] Verification complete
Gtk-Message: 09:23:51.470: Failed to load module "gail"
Gtk-Message: 09:23:51.470: Failed to load module "atk-bridge"

(steam:23667): Gtk-WARNING **: 09:23:51.473: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:23667): Gtk-WARNING **: 09:23:51.474: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  152
Serial number of failed request:  54
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  53
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  55
xerror_handler: X failed, continuing
assert_20200501092350_1.dmp[23703]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200501092350_1.dmp
/home/user/.local/share/Steam/steam.sh: line 750: 23667 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

```

**Comment by kisak-valve** [comment]
Hello @RRAlex, swrast is mesa's slower cpu renderer. The fact that Steam is trying to use it hints that you're using the nVidia proprietary driver and are missing the driver's 32 bit userspace libraries. Figure out which driver series you're using, and add the 32 bit userspace libraries with something similar to `sudo apt install libnvidia-gl-435:i386` (where 435 is the driver series).

Also, your issue is unrelated to the issue reported here.

**Comment by securerootd** [comment]
> Hello Friend
> all right?
> did you get an answer to solve this problem?
> thankful

Yes I did.  See below:

> Adding DRI 3 to intel Xorg configuration works as a fix here:
> 
> /etc/X11/xorg.conf.d/20-intel.conf
> 
> Section "Device"
> Identifier "Intel Graphics"
> Driver "intel"
> Option "AccelMethod" "sna"
> Option "TearFree" "true"
> Option "DRI" "3"
> EndSection

**Comment by ARitz-Cracker** [comment]
Just writing to confirm that installing libnvidia-gl-440:i386 fixed the issue for me, as I have an nvidia card and the driver I have installed is 440.

**Comment by edsantos98** [comment]
I'm having a similar problem and `sudo apt install libnvidia-gl-440:i386` didn't fix it.

```
edsantos@edlegion:~$ sudo apt install libnvidia-gl-440:i386
[sudo] password for edsantos: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnvidia-gl-440:i386 is already the newest version (440.82-1pop1ubuntu1~1588025390~20.04~bf29882).
libnvidia-gl-440:i386 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

So, I upgraded to Pop!_OS 20.04 in the day of its launching (April 30) and since then I haven't been able to launch Steam. The initial update verification happens but when it ends, some transparent window shows up but it doesn't load and dies.

I've tried with every package from Pop!_Shop (deb and flatpak) as well as the deb from the Steam website (installed through Eddy) and the problem keeps happening.

Here are my logs when running `steam` through the command line:

```
edsantos@edlegion:~$ steam 
Running Steam on pop 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/edsantos/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2020-05-10 10:42:06] Startup - updater built Apr 27 2020 21:53:21
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-05-10 10:42:06] Checking for update on startup
[2020-05-10 10:42:06] Checking for available updates...
[2020-05-10 10:42:06] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-05-10 10:42:06] Download skipped: /client/steam_client_ubuntu12 version 1588032389, installed version 1588032389
[2020-05-10 10:42:06] Nothing to do
[2020-05-10 10:42:06] Verifying installation...
[2020-05-10 10:42:06] Performing checksum verification of executable files
[2020-05-10 10:42:16] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
edsantos@edlegion:~$
```

**Comment by ARitz-Cracker** [comment]
@edsantos98 That fix will only work if you have the Nvidia 440 driver enabled. Check the driver manager.

**Comment by rickybrent** [comment]
I'm seeing the same with an intel graphics card (also (X)ubuntu 20.04). The silent, no-logs crash doesn't give a lot to go on.

**Comment by nolt** [comment]
Try to:
`sudo apt install wget gdebi-core libgl1-mesa-glx:i386`
gdebi-core is one of missing package in Ubuntu 20.04 which is necessary.

**Comment by LadaMariusz** [comment]
If u have laptop with Nvidia Optimus GPU, you should launch steam with Nvidia GPU.

**Comment by DhruvaG2000** [comment]
> Just writing to confirm that installing libnvidia-gl-440:i386 fixed the issue for me, as I have an nvidia card and the driver I have installed is 440. Running Kubuntu here

YEP THIS works perfectly! I am using nvidia 460.39 hence i had to install ```libnvidia-gl-460:i386```

**Comment by Jaakk0S** [comment]
> I was seeing the same with an intel skylake graphics card (also (X)ubuntu 20.04); in my case I was able to solve it by exporting MESA_LOADER_DRIVER_OVERRIDE=i965 before running steam. (I followed the same workaround as this bug: https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1876219 )
> 
> Running Steam under Wayland also worked.

sweet mother of.... this worked! just exporting that param... Skylake HD 520 here, too

**Comment by Conzar** [comment]
This worked for me on nvidia 465
```bash
sudo apt install libnvidia-gl-465:i386
```

**Comment by deepakn97** [comment]
> This worked for me on nvidia 465
> 
> ```shell
> sudo apt install libnvidia-gl-465:i386
> ```

This does not work for me. The installation fails and I get the error 'Package libnvidia-gl-465:i386 is not available, but is referred to by another package.' 
I have tried after adding i386 architecture as well, but I get the same output. 
Anything that I am missing here?

**Comment by Conzar** [comment]
> This does not work for me. The installation fails and I get the error `Package libnvidia-gl-465:i386 is not available, but is referred to by another package.`
> I have tried after adding i386 architecture as well, but I get the same output.
> Anything that I am missing here?

I am using the graphics-driver ppa.  So I did the following:
```bash
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt update
sudo apt install nvidia-driver-465 libnvidia-gl-465 libnvidia-gl-465:i386
```

**Comment by Viktor2k** [comment]
Trying to follow the suggested solution above, but fail here:
```
> sudo apt install libnvidia-gl-455:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnvidia-gl-455:i386 : Depends: libnvidia-gl-460:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Any suggestions of what I should try next?

**Comment by kisak-valve** [comment]
Hello @Viktor2k, your packaging issue is most likely unrelated to the issue reported in the opening post, but what does `apt policy libnvidia-gl-460 libnvidia-gl-460:i386` give you?

**Comment by Viktor2k** [comment]
> Hello @Viktor2k, your packaging issue is most likely unrelated to the issue reported in the opening post, but what does `apt policy libnvidia-gl-460 libnvidia-gl-460:i386` give you?
```
> apt policy libnvidia-gl-460 libnvidia-gl-460:i386
libnvidia-gl-460:
  Installed: (none)
  Candidate: 460.80-0ubuntu0.20.04.2
  Version table:
     460.80-0ubuntu0.20.04.2 500
        500 http://se.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages
libnvidia-gl-460:i386:
  Installed: (none)
  Candidate: 460.80-0ubuntu0.20.04.2
  Version table:
     460.80-0ubuntu0.20.04.2 500
        500 http://se.archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages
```

Might have put myself in this situation due to installing an older driver version (455.32.00) to support CUDA 11.1, which might not have been necessary... trying to understand this atm 😅

**Comment by kisak-valve** [comment]
@Viktor2k, give #5778 a read. The nVidia maintained CUDA PPA does not provide 32 bit userspace packages.

**Comment by d43pan** [comment]
Same error for me.

FRESH Ubuntu 20.04.2 LTS
NVIDIA 460 driver

This ended up fixing it:

```
sudo apt install libnvidia-gl-460:i386
sudo apt install gdebi-core
```

**Comment by avivas** [comment]
Here are my logs when running steam:

```
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/alejo/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-06-29 18:41:13] Startup - updater built Jun  8 2021 22:23:36
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-06-29 18:41:13] Using the following download hosts for Public, Realm steamglobal
[2021-06-29 18:41:13] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-29 18:41:13] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-29 18:41:13] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2021-06-29 18:41:13] Checking for update on startup
[2021-06-29 18:41:13] Checking for available updates...
[2021-06-29 18:41:13] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
[2021-06-29 18:41:14] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-06-29 18:41:14] Nothing to do
[2021-06-29 18:41:14] Verifying installation...
[2021-06-29 18:41:14] Performing checksum verification of executable files
[2021-06-29 18:41:14] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
```

- nvidia-driver-460
- Ubuntu 20.04.02 LTS

**Comment by totollygeek** [comment]
> > Just writing to confirm that installing libnvidia-gl-440:i386 fixed the issue for me, as I have an nvidia card and the driver I have installed is 440. Running Kubuntu here
> 
> YEP THIS works perfectly! I am using nvidia 460.39 hence i had to install `libnvidia-gl-460:i386`

That worked for me also! Thanks a lot folks!!!

**Comment by miguev** [comment]
> > > Just writing to confirm that installing libnvidia-gl-440:i386 fixed the issue for me, as I have an nvidia card and the driver I have installed is 440. Running Kubuntu here
> > 
> > 
> > YEP THIS works perfectly! I am using nvidia 460.39 hence i had to install `libnvidia-gl-460:i386`
> 
> That worked for me also! Thanks a lot folks!!!

Somehow this is still a thing. Ubuntu Studio 20.04 here, been playing games regularly without any issues and today out of the blue most games wouldn't draw anything on the screen, or only black screen. Search for the symptoms and this bug came up, and indeed the `libnvidia-gl-4?0:i386` package turned out to be the case, even though it was *already* installed: `apt install --reinstall libnvidia-gl-460:i386` fixed the issue.

**Comment by tilusnet** [comment]
As opposed to many here I don't have Nvidia and it still core dumps.
I think it's worth pausing for a second: this software's installation is a nightmare to deal with. I can hardly call it an installer: it doesn't know what to install on an arbitrary system in order to run. I probably still have loads of missing libraries after it claimed that it installed.

**Comment by kisak-valve** [comment]
Hello @securerootd, are you still experiencing the issue from the opening post on an up to date system? It's odd that the distro's automatic X config wasn't giving sane defaults.

**Comment by securerootd** [comment]
Hello @kisak-valve No - I haven't experienced it as of lately.

**Comment by kisak-valve** [comment]
Thanks for the feedback. Closing as outdated.
