### ISSUE TITLE
Individual group member volume level display in voice channels flows outside box (rounding error?)

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#7068]
#### Your system information

* Steam client version (build number or date): Apr 23 2020, at 00:53:55
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Bug in action: 
![image](https://user-images.githubusercontent.com/4428753/80283717-1c2f9000-871a-11ea-851f-90e774a61fa0.png)
![image](https://user-images.githubusercontent.com/4428753/80283719-218cda80-871a-11ea-99f3-f048cfe3b9e8.png)

#### Steps for reproducing this issue:

1. Be in a voice channel with someone else
2. Set their volume to 58% or 56% (there are likely other percentages that trigger this too)
3. Close the menu wherein you set their volume
4. Reopen it
5. Observe that the volume percentage flows outside of the box and has a large amount of decimals

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
