### ISSUE TITLE
Downloads page give graphic bug

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#7069]
#### Your system information

* Steam client version (build number or date): Apr 4 2020
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Only when I download a game in "downloads page" (in library) of steam client : 
_I have flashing fast lines (as if the screen was at the end of its life) on my screen.
_I see this flashing fast lines anywhere on my screen (Firefox, Thunderbird...).

#### Steps for reproducing this issue:

1. Open the Steam client.
2. Get on the "downloads page" (in library).
3. Download a game.
4. Wait 30 seconds.
5. See carefully or move quickly cursor mouse on a link  or scroll middle button mouse quickly up/down.

**Comment by kisak-valve** [comment]
Hello @vikloen, without a better description, this sounds like a video driver issue and should be mentioned to your video driver vendor.

Please explain exactly what happens and also copy your system information from Steam (`Steam` -> `Help` -> `System Information`), put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by vikloen** [comment]
Hello @ kisak-valve,
I update my description.
I give you the [gist](https://gist.github.com/vikloen/c259272ced2279a9d9e80393ae5ce6da)

**Comment by kisak-valve** [comment]
Thanks, historically the drivers for AMD APUs haven't been particularly well tested. Please retest with mesa from [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) PPA or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) PPA and [report the issue](https://www.mesa3d.org/bugs.html) to the driver vendor.

**Comment by vikloen** [comment]
_I install kisak-mesa from [ ValveSoftware /Proton ](https://github.com/ValveSoftware/Proton/wiki/Requirements)
_I install steam beta.

My problem is not resolved.

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost and this appears to be a video driver issue.
