### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gerasev-kirill** [ValveSoftware/steam-for-linux#7070]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): ubuntu 20.04
* Opted into Steam client beta?: [maybe]
* Have you checked for system updates?: [Yes]

#### Steps for reproducing this issue:

1. install steam client from https://store.steampowered.com/about/ on fresh os (or rm -fr ~/.local/share/Steam)
2. run steam
3. https://gist.github.com/gerasev-kirill/5552944707b64ea7f92eb9c2faa790ea
dump file:
[assert_20200426163203_1.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/4535407/assert_20200426163203_1.dmp.zip)

**Comment by gerasev-kirill** [comment]
output of: hwinfo --short

cpu:                                                            
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1797 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1829 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1625 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1640 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1495 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1400 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1538 MHz
                       Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1688 MHz
keyboard:
  /dev/input/event4    AT Translated Set 2 keyboard
mouse:
  /dev/input/mice      Logitech M105 Optical Mouse
  /dev/input/mice      ELAN1300:00 04F3:3057 Mouse
  /dev/input/mice      ELAN1300:00 04F3:3057 Touchpad
monitor:
                       N156HGA-EAB LCD Monitor
graphics card:
                       nVidia GP108M [GeForce MX150]
                       Intel UHD Graphics 620
sound:
                       Intel Sunrise Point-LP HD Audio
storage:
                       Intel Sunrise Point-LP SATA Controller [AHCI mode]
network:
  wlp3s0               Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter
  enp2s0               Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  wlp3s0               Ethernet network interface
  lo                   Loopback network interface
  docker0              Ethernet network interface
  br-dc2ab1a6d01c      Ethernet network interface
  enp2s0               Ethernet network interface
disk:
  /dev/sdb             HFS128G39TND-N21
  /dev/sda             HGST HTS541010B7
partition:
  /dev/sdb1            Partition
  /dev/sdb2            Partition
  /dev/sda1            Partition
  /dev/sda2            Partition
  /dev/sda3            Partition
  /dev/sda4            Partition
cdrom:
  /dev/sr0             HL-DT-ST DVDRAM GUE1N
usb controller:
                       Intel Sunrise Point-LP USB 3.0 xHCI Controller
bios:
                       BIOS
bridge:
                       Intel Sunrise Point-LP PCI Express Root Port #1
                       Intel Sunrise Point LPC Controller/eSPI Controller
                       Intel Sunrise Point-LP PCI Express Root Port #6
                       Intel Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
                       Intel Sunrise Point-LP PCI Express Root Port #5
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 3.0 root hub
memory:
                       Main Memory
bluetooth:
                       IMC Networks Bluetooth Device
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
                       Intel Sunrise Point-LP PMC
                       Intel Sunrise Point-LP Serial IO I2C Controller #1
                       Intel Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
                       Intel Sunrise Point-LP CSME HECI #1
                       Intel Sunrise Point-LP Serial IO SPI Controller #0
                       Intel Sunrise Point-LP Serial IO UART Controller #0
                       Intel Sunrise Point-LP Serial IO I2C Controller #0
                       Intel Sunrise Point-LP Thermal subsystem
                       Intel Sunrise Point-LP SMBus
  /dev/input/event12   IMC Networks USB2.0 VGA UVC WebCam

**Comment by kisak-valve** [comment]
Hello @gerasev-kirill, `swrast` is mesa's slower cpu renderer, and the fact that Steam is trying to use it hints that you're using nVidia's proprietary driver, but don't have 32 bit support installed. Please check that you have `libnvidia-gl-440:i386` installed with something like `apt policy libnvidia-gl-440:i386` and install it if it is missing.

**Comment by gerasev-kirill** [comment]
it works%)
you should add it to your wiki

**Comment by kisak-valve** [comment]
Glad to hear you got it running, closing as this was a general system config issue.
