### ISSUE TITLE
BPM overlay for Steam Input steals controller input from games

### ISSUE THREAD

**Issue by undu** [ValveSoftware/steam-for-linux#7077]
#### Your system information

* Steam client version (build number or date): Built on 20200427T21:53:32
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When a game is run when "Use BPM Overlay when Steam Input is Active Per-Game Setting" is enabled, I can hear the BPM overlay UI sounds when I press buttons or move the thumbstick.

Some games do not respond to input, other do. They all seem to detect when I have the Dualshock 4 v2 plugged in as the game shows the correct button prompts.

This happens when the steam overlay is on or off, with a steam controller and a dualshock v2 ad with native and games running under proton. Running the game under the steam linux runtime doesn't fix it.

I've tried both on a wayland and an X session, it happens on both, this is using KDE/Plasma.

#### Steps for reproducing this issue:

1. Set "Use BPM Overlay when Steam Input is Active Per-Game Setting" to "Forced On"
2. Plug a controller, run Tricky Towers
3. Try to control the game with the controller

Alternatively, force the game to run using Proton, same issue.

Although similar, this doesn't look like the same issue as https://github.com/ValveSoftware/steam-for-linux/issues/6506 
And just in case, sdl2 version in my system is 2.0.15

**Comment by kisak-valve** [comment]
Hello @undu, this issue is already being tracked at #6495. Closing as a duplicate.
