### ISSUE TITLE
Steam Play Together does not stream game sound

### ISSUE THREAD

**Issue by julben** [ValveSoftware/steam-for-linux#7081]
#### Your system information

* Steam client version (build number or date): May 1st 2020 at 02:16:11
* Distribution (e.g. Ubuntu): Pop!_OS/Ubuntu 20.04/Debian 10.3
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

When trying to use the feature Steam Play Together in any game running through Proton, the client does not stream the game sound to the client which do not owns the title. (I could not test with a native title) 

In the past, it was working well, even though I could not say when that was exactly: you just had to run the game with Proton, and use the "Steam Play Together" system to invite a friend to play with you and his/her machine was receiving both video and audio of the stream.

This was tested with 3 different Linux as hosts (please see above distributions) and Linux/Windows machines as clients.

The vocal chat works though.

#### Steps for reproducing this issue:

1. Run any game with the Steam client
2. Invite a player via Steam Play Together system
3. When player joins, he/she can see the video but not the audio of the game.

Edit: I have been able to confirm that **it does not come from Proton, since, as I suspected, it affects native builds as well**. Changed "steps for reproducing" part accordingly.

Also, I have been able to confirm **it occurs with the Linux version, not when the host is running Windows and the Windows Steam client**. No information for the macOS version.

**Comment by kisak-valve** [comment]
Hello @julben, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
