### ISSUE TITLE
"Received discovery message from client 1234" flooding my terminal output

### ISSUE THREAD

**Issue by L1Q** [ValveSoftware/steam-for-linux#7085]
#### Your system information

* Steam client version [(build number or date)](https://i.imgur.com/haQnK0c.png): Apr 27 2020, at 21:53:32
* Distribution: Manjaro 20.0
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When starting stream from CLI I'd expect to see the terminal output useful information.
What happens is basically in the title: my terminal is filled with ``Received discovery message from client 1234`` messages

```
Received discovery message from client 1234 at [THEIR IP]:[PORT]
```

![screenshot](https://i.imgur.com/TBkABYL.png)

The IP is redacted out to prevent doxxing but it's a regular ipv4.
Ports can vary, ip changes, but it's always ``client 1234``
I don't believe any of the ips belong to valve or devices I own.

Same messages can be found in ``Steam/logs/remote_connections.txt``.

Primary issue for me is that it gets extremely inconvenient to use the console for game troubleshooting as all I see is the spam.

#### Steps for reproducing this issue:

1. be me(?)
2. start steam from CLI
3. ???
4. have a chance of terminal output DDoSed by random person

Q: Does this look like a security issue?
Q: Can I specifically disable outputting this message to console?

**Comment by ptdel** [comment]
I can confirm.  I'm also getting this
![image](https://user-images.githubusercontent.com/5721307/81449666-be09a080-914e-11ea-9149-ec3798be6843.png)

whats more annoying is that my chat keeps disconnecting and putting me into offline mode. Not sure if it's related to this yet though.

**Comment by kisak-valve** [comment]
Hello @L1Q, @ptdel, are either of you still experiencing this issue on an up to date system?

**Comment by L1Q** [comment]
Woah I haven't had this issue in such a long time even forgot it existed.

**Comment by kisak-valve** [comment]
Thanks for the feedback @L1Q, closing as fixed some time ago.
