### ISSUE TITLE
(UI Bug) Cannot opt in or out of beta for game

### ISSUE THREAD

**Issue by heav-4** [ValveSoftware/steam-for-linux#7086]
#### Your system information

* Steam client version (build number or date): Apr 27 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

In a steam game (namely, Baba Is You), I wanted to change the beta I was using (I was already opting in to one), however the dropdown menu does not work. It was working before, and there are other betas to select, however the text in the dropdown menu is selected, and nothing happens when it is clicked. I am trying to opt out of this beta because the game will not start.

#### Steps for reproducing this issue:

1. Click on the dropdown menu for changing betas.
2. 
3.

**Comment by heav-4** [comment]
Update: Pressing "tab" to try to select the dropdown menu and then pressing enter closes the menu, however pressing tab to try to select the dropdown menu and using the arrow keys works, however this is not ideal.

**Comment by kisak-valve** [comment]
Hello @heav-4, are you still experiencing this issue on an up to date system?

**Comment by heav-4** [comment]
hello. wow, it's been a while. i'm not experiencing this anymore, or even using the same device or operating system, sorry.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.

**Comment by spider312** [comment]
Hi,
I have the exact same issue. I figured it out yesterday on the game "Don't Starve Together" for which i managed to opt-in for a beta some weeks ago. The only difference i found is about the solution : i can't manage to change the dropdown menu value via keyboard (no visual difference for focused field in the GUI is a pain)
I tested with another game : "7 Days to Die", the same thing happened : i click the dropdown menu, it opens, i click a beta, dropdown closes keeping "none" value
Game isn't running, restart steam has no effect

**Comment by spider312** [comment]
I managed to opt-in by using Big Picture mode, then had the same bug while returning "none" beta, despite the "none" option being over the dropdown menu at this moment

**Comment by KleerKut** [comment]
I have the same issue in Lubuntu 20.04 and the Big Picture mode trick worked. I had pinned 7 Days to Die to version 20.6 while playing a private server sometime last year and wanted to unpin it. I checked other games and had the same issue of the selection not working. Uninstall/reinstall didn't work. Big Picture mode uses a different UI and works.

**Comment by zaari** [comment]
I have the same issue on Fedora 38. The Big Picture mode workaround made it possible to opt in.
