### ISSUE TITLE
Add PrefersNonDefaultGPU=true to .desktop file of Steam

### ISSUE THREAD

**Issue by Eonfge** [ValveSoftware/steam-for-linux#7089]
#### Please describe your issue in as much detail as possible:
There is a new standard for aiding in multi-GPU setups. You can now set a flag called `PrefersNonDefaultGPU` which will tell the computer to use the alternative (generally speaking, dedicated) GPU. 

By setting this flag, Steam and it's applications will run with the more powerful GPU by default, preventing many annoyed customers as they are rushing B with 20 fps.

#### Docs
- https://www.gamingonlinux.com/articles/the-linux-desktop-entry-specification-gets-a-way-to-automatically-use-a-discrete-gpu-merged-into-gnome.16598
- https://www.hadess.net/2020/05/dual-gpu-support-launch-on-discrete-gpu.html
- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

**Comment by kisak-valve** [comment]
Hello @Eonfge, this issue is already being discussed at #634. I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/634#issuecomment-624698453.

**Comment by smcv** [comment]
steam-launcher beta 1.0.0.70 adds `PrefersNonDefaultGPU=true`, as well as the older `X-KDE-RunOnDiscreteGpu=true`.

(If you get your Steam client through an unofficial distro-specific package, they will need to update to 1.0.0.70 before you see this change.)

**Comment by doraskayo** [comment]
So apparently this results in my integrated GPU being selected instead of my dedicated GPU. My dedicated GPU is the default in my system as configured in BIOS. I'm honestly not sure how this is helpful in my case.

**Comment by smcv** [comment]
> I'm honestly not sure how this is helpful in my case.

It's not. We're trying to make Steam work as well as possible for as many people as possible, using the imperfect tools available to us.
