### ISSUE TITLE
Screenshot uploader no longer shows the pictures as uploaded

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/steam-for-linux#7092]
#### Your system information

* Steam client version (build number or date): 27/4/2020
* Distribution (e.g. Ubuntu): Fedora 32
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Screenshot uploader no longer shows the shots as uploaded after some time, recently uploaded pictures are still showed as being uploaded by a cloud symbol.

#### Steps for reproducing this issue:

1. Upload screenshots and wait

**Comment by monterrr** [comment]
The bug seems to be fixed for me, so I guess you guys fixed it

**Comment by monterrr** [comment]
Stopped working again..

**Comment by kisak-valve** [comment]
Hello @andreldmonteiro, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Thanks for the feedback. If someone else comes across a similar issue, they can open a new issue report. Closing as outdated.
