### ISSUE TITLE
hidpi scaling too large

### ISSUE THREAD

**Issue by vatula** [ValveSoftware/steam-for-linux#7097]
#### Your system information

* Steam client version:
Steam flatpak, Built: May 7 2020, at 23.17.51
Steam API: v020
Steam package versions: 1588895218

For system info see attachment.  
[steam-hw.txt](https://github.com/ValveSoftware/steam-for-linux/files/4597406/steam-hw.txt)

* Distribution:
Fedora Workstation 32 

* Opted into Steam client beta?:
Yes

* Have you checked for system updates?:
Yes

#### Please describe your issue in as much detail as possible:
HiDPI scaling is bad compared to other native and non-native apps.
Clockwise starting from top left:
1. Spotify
2. Steam
3. Nautilus File manager
4. Telegram

Only No 3 is native GTK+ application (Nautilus File Manager). Telegram and Spotify scale text reasonably.
Steam with an option "Enlarge text and icons based on monitor size (requires restart)" scales text unreasonably large.
![image](https://user-images.githubusercontent.com/450851/81379718-f27c5d00-914c-11ea-9aeb-e3c53af78f45.png)

#### Steps for reproducing this issue:
1. Have Fedora 32, Gnome and Xorg session
2. Have 31" 4K Monitor
3. Go to settings in the steam and check the checkbox in the Interface section against "Enlarge text and icons based on monitor size (requires restart)".
4. Restart Steam.

**Comment by kisak-valve** [comment]
Hello @vatula, this issue is already being tracked at #5908. Closing as a duplicate.
