### ISSUE TITLE
What is the correct way to install steam on Ubuntu 20.04 LTS?

### ISSUE THREAD

**Issue by peon501** [ValveSoftware/steam-for-linux#7099]
What is the correct way to install steam on Ubuntu 20.04 LTS?
Should I install via Steam installer in Ubuntu Software Center or just .deb?
Maybe I need to use FlatPack?
Cuz some says that .deb steam overlay and layout doesn't work well and so on?
What is standard (without extra steps) way now?

**Comment by kisak-valve** [comment]
Hello @peon501, I'm obligated to recommend using the Valve-provided packaging from https://store.steampowered.com/about/ for the best experience, but realistically any install method should be fine.

If there's issues with the packaging that affects one kind of packaging and not others, it should be reported to their package maintainers (Valve-provided .deb here, distro-specific packaging variants to the distro's package maintainer(s) for Steam, and flathub-packaged Steam to their package maintainer(s). Of course general Steam issues should also be reported here.
