### ISSUE TITLE
Big picture prompt buttons do not work initially

### ISSUE THREAD

**Issue by blazingkin** [ValveSoftware/steam-for-linux#7103]
#### Your system information

* Steam client version (build number or date): 
Built: Apr 27 2020 at 21:53:32

* Distribution (e.g. Ubuntu): 
Kubuntu 20.04

* Opted into Steam client beta?: [Yes/No]
No

* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
The `Plugged in a controller?` prompt that asks to open big screen does not have clickable buttons until losing focus and regaining focus

#### Steps for reproducing this issue:

1.  Plug in a controller with steam open (no game) (I am using an Xbox wired controller)
2.  See the open prompt
3.  Attempt to click close

**Comment by kisak-valve** [comment]
Hello @blazingkin, are you still experiencing this issue on an up to date system?

**Comment by blazingkin** [comment]
I no longer have a wired controller, so cannot reproduce on my side

**Comment by kisak-valve** [comment]
Thanks for the feedback at least. Closing as outdated.
