### ISSUE TITLE
Steam client segfault after not find plugin

### ISSUE THREAD

**Issue by FurtadoPires** [ValveSoftware/steam-for-linux#7104]
#### System information

* Steam client version: Apr 27 2020 
* Distribution: Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue Detail:
I was using a third party plugin to run some specific games in my library, and after I remove this specific version from my `.steam/root/compatibilitytools.d/` directory, I could not launch the game anymore, and any attempt to access the properties of this specific games result in a segfault of steam client.

I suspect this happens due to steam client not handling the exception of not finding the plugin anymore, causing a segfault in the client instead of reverting the config to some standard option. 

#### Steps for reproducing this issue:

1. Download any steam third party plugin to .steam/root/compatibilitytools.d/ (I used _Proton GE_ in this case)
2. Select some game to use this specific plugin in the properties
3. Remove the plugin from `.steam/root/compatibilitytools.d/`
4. Try to access the properties of this game again

I was able to work around this error by placing back the specific version of the missing plugin (fortunately I knew what version is), this allowed me to access the properties of the game again (without causing a segfault) and change to use the new version of the plugin, so I could safely remove the old version from the directory.

But this might be a problem for users who don't know what version they were using, and reinstall the game / steam client didn't helped.

So I believe steam client need an exception handler for this specific case, because it can affect other users without they knowing.

ID of the ticket I opened in the steam support: HT-8DT3-DGGB-H2WD

**Comment by kisak-valve** [comment]
Hello @FurtadoPires, this issue is already being tracked at #6986. Closing as a duplicate.
