### ISSUE TITLE
Steam dumped core

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#7105]
#### Your system information

* Steam client version (build number or date): 27 April, 2020
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No]  No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I was playing Dota. In the middle of the game, Steam dumped core and I had to restart.
[steam_core.zip](https://github.com/ValveSoftware/steam-for-linux/files/4616318/steam_core.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a DUMP_REQUESTED in crashhandler.so.

**Comment by amitavmohanty01** [comment]
@kisak-valve do you recommend reporting it to their bug tracker ?

**Comment by amitavmohanty01** [comment]
@kisak-valve I do not understand the reasoning behind closing the ticket. You chose not to even answer my question.

The issue pointed out is in `crashhandler.so` but it is also the choice of Steam for Linux to use that. If the issue has to be taken to their bug tracker, then it should be done on behalf of Steam. Until that has been addressed, I do not see any logical closure to this issue.

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, for clarity, this issue report is open as indicated in the top left of this issue report. The issue that referenced this one was closed.

**Comment by amitavmohanty01** [comment]
Hello @kisak-valve , I apologize for the confusion.

**Comment by kisak-valve** [comment]
Hello again @amitavmohanty01, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
