### ISSUE TITLE
Potential race condition [Low priority issue]

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#7108]
#### Your system information

* Steam client version (build number or date): 27 April, 2020
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I started Steam. It took long to validate the game Dota 2. I was able to chat during the time.

Meanwhile, I noticed that there was dump in the system journal.

`Assert( Assertion Failed: GetSteamID().GetAccountID() ):/data/src/clientdll/baseuser.cpp:794`

Attaching the dump herewith.
[assert_20200516021914_24.zip](https://github.com/ValveSoftware/steam-for-linux/files/4637101/assert_20200516021914_24.zip)

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
