### ISSUE TITLE
Steam closes after initial connection to host

### ISSUE THREAD

**Issue by kensaut** [ValveSoftware/steam-for-linux#7109]
#### Your system information

* Steam client version (build number or date): Multiple (Nvidia Shield, Apple TV, LG phone-1.1.61.156)
* Distribution (e.g. Ubuntu): CentOS8
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I want to connect to my host via Steam Link to play a game locally on my host.  When connecting to my host, Steam pops up, but then closes and host goes offline.  Host logs out of Steam.

Network connection to host is good.  It passes the 105 Mb mark for streaming.  

#### Steps for reproducing this issue:

1. I tried it on multiple devices
2. 
3.

**Comment by kisak-valve** [comment]
Hello @kensaut, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
