### ISSUE TITLE
What is lightweightest linux for installing steam?

### ISSUE THREAD

**Issue by MersadAkbari** [ValveSoftware/steam-for-linux#7110]
#### My system information

* os: Bodhi Linux x86_64
* cpu: AMD Athlon 64 X2 Dual 4400+ (2) @ 2.310GHz
* gpu: NVIDIA GeForce GT 610
* memory: 3945MiB

# What is lightweightest linux for installing steam?
I had lubuntu and i had 25 fps on CS:GO
i cant play well with 25 fps so i installed budhi linux (which is lightweight linux)
but when i launch csgo nothing happend(like i didnt launch)
now i want to know what is lightweightest linux for gaming?

**Comment by Semperverus** [comment]
This is not an issue with steam for linux. You should take this discussion over to Reddit.

I would recommend closing this as it is not a bug or a feature-request.

**Comment by MersadAkbari** [comment]
Ok @Semperverus , i have add csgo launching problem was for my launch settings
