### ISSUE TITLE
Crackling sound in voice

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#7111]
#### Your system information

* Steam client version (build number or date): May 15 2020, at 03:04:21
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System information: [gist](https://gist.github.com/XakepSDK/28f42f8ead7c2645b5cb53d9c08bc059)

#### Please describe your issue in as much detail as possible:
Audio output has cracklings. When i speak or somebody else speaks. Like when you speak in a fan, but more annoying.

#### Steps for reproducing this issue:
1. Start a voice call
2. Or use mic test in friends menu settings
3. Sometimes crackling is not present. Try to change voice output and/or input in steam settings from default to current device, this may help too.

**Comment by kisak-valve** [comment]
Possible duplicate of #6747.

**Comment by XakepSDK** [comment]
Duplicate
