### ISSUE TITLE
steam dont respect xdg standard

### ISSUE THREAD

**Issue by icf20** [ValveSoftware/steam-for-linux#7116]
in steam ->library->game ->game proprieties -> local tab->  **browse local files...** in my case opens catfish instead of default file explorer set on mimeapps.list

https://wiki.archlinux.org/index.php/XDG_MIME_Applications
`xdg-mime default thunar.desktop inode/directory`

this is the standard setting and no idea why steam open catfish and only happens on steam

![image](https://user-images.githubusercontent.com/17784575/82132910-72599580-97e5-11ea-9343-f89eec20e916.png)

**Comment by kisak-valve** [comment]
Hello @icf20, I would have expected the steam client to behave the same as running `xdg-open file:/path/to/anywhere` in a terminal. Can you confirm that command opens your file explorer of choice?

**Comment by icf20** [comment]
i close this since the issue was on my end ebcause of inode/directory=exo-file-manager.desktop;
