### ISSUE TITLE
Steam crashing again when trying to open certain games Properties

### ISSUE THREAD

**Issue by CygnusTerminal** [ValveSoftware/steam-for-linux#7118]
#### Your system information

* Steam client version (build number or date): May 15, at 03:04:21
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Trying to open Sword Art Online: Fatal Bullet properties right clicking it crashes the client with a segmentation fault. Game was copied from a Windows partition. Other games copied from Windows partition doesn't show the same behaviour.
[assert_20200518230622_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/4647845/assert_20200518230622_1.zip)
Going into offline mode does not solve the issues, going into non beta also wont work.

#### Steps for reproducing this issue:

1. Open Steam client 
2. Right click SAO:FB and click "Properties"
3. Steam crashes and closes

**Comment by kisak-valve** [comment]
Possibly related to #6986.

**Comment by CygnusTerminal** [comment]
> Possibly related to #6986.

I tried the workaround, did not work. I did not expect it to work since i purged the game from the HDD, reinstalled Steam and it still crashes, i never set a custom proton version for this game.
