### ISSUE TITLE
Pressing Retry connection in Failed to connect to Steam dialogue causes the Connecting window to display seemingly forever

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#7123]
#### Your system information

* Steam client version (build number or date): May 15 2020, at 18:18:24
* Distribution (e.g. Ubuntu): Fedora 31
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If Steam fails to connect when first starting the client, you will be shown a dialogue wherein you have a multitude of options. While I do not get this dialogue very often, it seems that pressing Retry connection always has caused Steam to get stuck on Connecting Steam account <name> window. Note that this occurred even when I had waited out the connection issues while still on the dialogue that let me press Retry connection, and then pressed Retry connection. Killing Steam and subsequently starting it again connected normally- 

#### Steps for reproducing this issue:

1. Have Steam fail to connect on startup
2. Press retry connection
3. Observe that the Connecting window stays there seemingly forever

**Comment by kisak-valve** [comment]
Hello @Newbytee, are you still experiencing this issue on an up to date system?

**Comment by Newbytee** [comment]
I've not attempted to reproduce this recently. We can reopen it if it becomes relevant again.
