### ISSUE TITLE
Youtube videos keep playing sound after Steam library window closes.

### ISSUE THREAD

**Issue by z0z0z** [ValveSoftware/steam-for-linux#7124]
#### Your system information

* Steam client version (build number or date):  Latest Steam beta
* Distribution (e.g. Ubuntu): Arch x86_64
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Steps for reproducing this issue:
On the Steam library, select a game, scroll down and under community content play any youtube video. Close the Steam library window entirely, and the video keeps playing sound in the background.

You can even see a literal "Chromium" process playing sound in pavucontrol, I knew the Steam client used webkit to some extant but I didn't know it had a literal Chromium build inside.

![2020-05-22-135618_951x105_scrot](https://user-images.githubusercontent.com/12925873/82696297-42334c00-9c56-11ea-8ca0-8951946719e8.png)

**Comment by kisak-valve** [comment]
Hello @z0z0z, this issue is already being tracked at #5234. Closing as a duplicate.
