### ISSUE TITLE
Steam Crashes When Connecting a New Thunderbolt 3 Ethernet Adapter 

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/steam-for-linux#7127]
#### Your system information

* Steam client version (build number or date): latest as of 5/23
* Distribution (e.g. Ubuntu): Arch Linux 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When the internet connection switches from wireless -> wired on a new ethernet device that wasn't attached to the system when Steam started, the Steam client will crash. I have reproduced this twice.
 
#### Steps for reproducing this issue:

1. Have a USB C dongle, with ethernet attached and it plugged into your router but not the computer
2. Start downloading a game on Steam, e.g. DOTA 2.
3. While the download is in progress, plug the adapter in
4. The client will crash when the wired connection is done establishing.

Launching the client again with the adapter still connected does not cause a crash, and it downloads the game normally over ethernet. Unplugging the ethernet cable does not crash it either.

**Comment by MersadAkbari** [comment]
same issue

**Comment by MersadAkbari** [comment]
distro family is not important, i had this issue in ubuntu,mint,lmde,etc

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, @MersadAkbari, are either of you still experiencing this issue on an up to date system? This issue reads like it might be from a mismatch between networkmanager libraries in the Steam runtime and the host system.

**Comment by kisak-valve** [comment]
Closing pending feedback.
