### ISSUE TITLE
Proton sometimes causes Steam to crash when a controller is plugged in.

### ISSUE THREAD

**Issue by HippoPenguin** [ValveSoftware/steam-for-linux#7134]
#### Your system information

* Steam client version May 15 2020 at 03:04:21 
* Slackware 14.1
* Opted into Steam client beta?: YES and NO
* Have you checked for system updates?:  YES

#### Please describe your issue in as much detail as possible:
I've noticed that some games using proton completely lock up and crashes Steam and the Game itself if a controller is plugged in.  This happens with both the beta client and the normal client.  Once Steam has crashed the only way Steam can restart seems to be a full reboot.  However other games it does not crash, which makes me think it's how specific games use controllers.

#### Steps for reproducing this issue:

1. Have a controller plugged in
2. Run a game where this issue happens (Enemy on Board)
3. First splash screen appears but Steam and the game have frozen. Steam eventually completely crashes. Game has to be killed manually.

**Comment by kisak-valve** [comment]
Hello @HippoPenguin, are you still experiencing this issue on an up to date system?

**Comment by HippoPenguin** [comment]
I've updated my hardware/computer system a number of months ago. I've not
had the issue on my current system.

**Comment by kisak-valve** [comment]
Thanks for letting me know. Closing as outdated.
