### ISSUE TITLE
Updating from Ubuntu 19.10 to 20.04 removed Steam and it's no longer possible to install it

### ISSUE THREAD

**Issue by enveeed** [ValveSoftware/steam-for-linux#7137]
#### Your system information

* Steam client version: **May 26 2020 21:11:50 CEST**
* Distribution: **Ubuntu 20.04**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes, updating broke it.**

#### Please describe your issue in as much detail as possible:
I've updated my Ubuntu 19.10 install with proprietary NVIDIA drivers (`nvidia-drivers-440` from `ppa:graphics-drivers`) to 20.04. During this steam was removed, I'm not sure why that happened. After the update I attempted to install it again but none of the common ways to install it worked.

**> Installing via the latest `steam_latest.deb`**
The package successfully installs, but running `steam` outputs the following and prompts me to install these packages:
```
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
```
Confirming this leads to this error:
```
Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1:i386
[sudo] password for (user): 
........
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libgl1-mesa-dri:i386 : Depends: libvulkan1:i386 (>= 1.2.131.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
After which steam attempts to start but obviously can't and reports missing 32-bit libraries (`libGL.so.1`, `libdrm.so.2`) and then that `steamui.so` could not be loaded 

**> Installing `steam-launcher` from the Ubuntu repositories**

```
(user)@(host):~$ sudo apt install steam-launcher 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package steam-launcher is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  steam:i386 steam-devices

E: Package 'steam-launcher' has no installation candidate
```

**> Installing `steam-installer` from the Ubuntu repositories**

```
(user)@(host):~$ sudo apt install steam-installer 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 steam-installer : Depends: steam (= 1:1.0.0.61-2ubuntu3)
E: Unable to correct problems, you have held broken packages.
```
**> Installing `steam` for `i386` arch from the Ubuntu repositories**

```
(user)@(host):~$ sudo apt install steam:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 steam:i386 : Depends: libgl1-mesa-dri:i386 (>= 17.3) but it is not going to be installed or
                       libtxc-dxtn0:i386 but it is not installable
              Depends: libgl1-mesa-glx:i386 but it is not going to be installed
              Recommends: mesa-vulkan-drivers:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Attempting to manually install `libgl1-mesa-dri:i386` leads to the same dependency issue as in the first try, and `libgl1-mesa-glx:i386` depends on different packages that all in the end depend on `libgl1-mesa-dri:i386` which leads to the same issue again.

**Things I've tried** (in various combinations and order)
- switching from proprietary drivers back to nouveau, removing the proprietary drivers and installing them again and then switching back to them.
- updating the drivers (`440.64` to `440.82`)
- completely removing the Vulkan SDK from LunarG which I had installed previously for development purposes
- enabling 32-bit architecture (was already enabled)
- checking that the driver installation had also installed the 32-bit libraries (it did)
- confirming that the driver is working fully (with a non-steam game)
- confirming that the drivers vulkan support works (using `vulkaninfo` and `vkcube` from `vulkan-tools` or the Vulkan SDK from LunarG, both work)

#### Steps for reproducing this issue:

1. Install steam and proprietary NVIDIA drivers on Ubuntu 19.10
2. Update to Ubuntu 20.04 (Steam will be removed)
3. Attempt to re-install steam.

**Comment by kisak-valve** [comment]
Hello @enveeed, what does `apt policy libgl1-mesa-dri libgl1-mesa-dri:i386 libgl1 libgl1:i386` give you? Ubuntu's multiarch implementation requires that the 32 bit and 64 bit variants of a package have exactly the same version, so odds are you have a newer 64 bit package with no matching 32 bit variant and the package manager is stopping instead of making a mess.

**Comment by enveeed** [comment]
This sounds plausible, I'm not sure what else I can do to find out if there is a version difference somewhere, the command you gave me returns this and it seems fine:
```
libgl1-mesa-dri:
  Installed: 20.0.4-2ubuntu1
  Candidate: 20.0.4-2ubuntu1
  Version table:
 *** 20.0.4-2ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
libgl1-mesa-dri:i386:
  Installed: (none)
  Candidate: 20.0.4-2ubuntu1
  Version table:
     20.0.4-2ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main i386 Packages
libgl1:
  Installed: 1.3.1-1
  Candidate: 1.3.1-1
  Version table:
 *** 1.3.1-1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
libgl1:i386:
  Installed: (none)
  Candidate: 1.3.1-1
  Version table:
     1.3.1-1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main i386 Packages
```

**Comment by enveeed** [comment]
I've now also tried to manually install `libvulkan1:i386` with `apt` as it seems like it's at least part of the issue, but attempting this will basically remove all packages on my system for some reason, including various Qt libs and the desktop environment itself

**Comment by kisak-valve** [comment]
Since it's mentioned how about `apt policy libvulkan1 libvulkan1:i386`?

**Comment by enveeed** [comment]
You seem to be on to something here, this looks interesting :)
```
libvulkan1:
  Installed: 1.2.135.0~rc2-1ubuntu18.04.1.1
  Candidate: 1.1.126.0-2
  Version table:
 *** 1.2.135.0~rc2-1ubuntu18.04.1.1 100
        100 /var/lib/dpkg/status
     1.2.131.2-1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages
     1.1.126.0-2 1000
       1000 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal/main amd64 Packages
libvulkan1:i386:
  Installed: (none)
  Candidate: 1.1.126.0-2
  Version table:
     1.2.131.2-1 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main i386 Packages
     1.1.126.0-2 1000
       1000 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal/main i386 Packages
```
I'm by far no expert in package management, any idea how I could downgrade the amd64 version?

**Comment by enveeed** [comment]
`sudo apt install libvulkan1 libvulkan1:i386` is trying to remove the world again, sadly. :(

**Comment by kisak-valve** [comment]
This is getting outside my experience, but my guess is that all the `1.2.135.0...` lunarg packages need to be nudged at the same time to make apt be happy with the dependency tree.

**Comment by enveeed** [comment]
That makes a lot of sense, thanks for your advice. I will experiment with it and see if I can manage to fix it, you've already helped a lot! I will update this issue when I've found a solution.

**Comment by enveeed** [comment]
I've solved it by running **`sudo apt-get install libvulkan1=1.2.131.2-1 libvulkan1:i386=1.2.131.2-1`**. This force-replaced the library with the one provided by Ubuntu, which seems to be the only one of the 3 which won't attempt to remove my entire system upon install. Thankyou for pointing me in the right direction! :) Steam installs and works fine now, including Vulkan games.

To summarize, should anyone else have this issue:
- If you have the LunarG Vulkan SDK, make sure its either fully installed or not at all, not party like apparently in my case.
- If you have a custom priority set for `ppa:graphics-drivers`, `1000` in my case (e.g. to skip the fake `440.82.really.440.64` package by Ubuntu), you will have to run the command above, otherwise a simple `sudo apt install libvulkan1 libvulkan1:i386` may be sufficient (or the issue wouldn't be there in the first place, not sure)

**Comment by ZeroCool2u** [comment]
Hi There, just wanted to say thank you @kisak-valve and that I also had a situation similar to this one. 


I had LLVM 10 setup on my machine via the LLVM website. LLVM 10 32-bit is not available for Ubuntu 20.04, so when I did my upgrade, it broke my Steam installation. If I tried to install the dependencies that it requested, it would uninstall the whole world as @enveeed described. Finally, I got it working by doing ```sudo apt install libllvm10=1:10.0.0-4ubuntu1 libllvm10:i386=1:10.0.0-4ubuntu1```. 


If you find this page in the future and have a similar problem, make sure you use the most up to date llvm version available from Ubuntu for both the 64 and 32 (i386) bit versions. You can find them by running ```apt show libllvm10``` and ```libllvm10:i386```.

**Comment by DadddyzKitten** [comment]
Can someone please help Ive tried everything on this page and at the end of it this is what the problem seems to be!!!!
Unable to locate package libllvm10:i386

**Comment by ZeroCool2u** [comment]
@DadddyzKitten Did you try running the commands in my last comment? You really just need the first one.

The root cause of the issue for me, and probably some others, is that I had installed a specific upstream (non-Ubuntu) version of LLVM for development and didn't purge the ppa upon upgrading to 20.04. My version was newer than the one provided by Ubuntu, so I didn't get the updated version when upgrading. Upstream does not provide a 32-bit (i386) version for Ubuntu now, so you must rely on Ubuntu/Canonical to provide that for you. Steam needs this to run.

Beware though, if you do any development that requires a bleeding edge version of LLVM there's a small chance that this could break some of your dev environments.

**Comment by joro1881** [comment]
I also have the same issue, I have tried everything and nothing works. I have libgl1-mesa-dri installed but doesn't recognize it as 'libgl1-mesa-dri:i386'. From your last reply command. 

I am getting : 

E: Version '1:10.0.0-4ubuntu1' for 'libllvm10' was not found
E: Version '1:10.0.0-4ubuntu1' for 'libllvm10:i386' was not foun

So I am constantly getting in a loop for various things not found and it's getting annoyed. So the only solution is to pre-install Ubuntu, so steam can be installed and I cannot do that on this PC due to various information and apps setup. 

What can  I do :( ?

**Comment by joro1881** [comment]
I installed steam using 'flatpak' but the download speed was totally broken, so - had steam but not been able to use it.

**Comment by enveeed** [comment]
@joro1881 If you want to use flatpak, try a VPN for downloads. I think flathub is using GitHub to store contents and on some european ISPs download speeds from GitHub are hilariously slow for some reason even if the connection could provide much more bandwith. I've had the same problem and I'm currently using a VPN for whenever I need to download something from GitHub and the difference is certainly worth it, as far as I know especially release endpoints are effected but you could give it a try.

**Comment by joro1881** [comment]
Tomorrow, I will install it again using flatpak and will try playing remotely to my gaming machine, if this GitHub connection doesn't affect the gaming, I will be fine. 
Explanation: I have the steam issue on my working linux laptop. However, steam remote and flatpak should be enough to play the games through my gaming machine when on travel.

**Comment by Bam4d** [comment]
I also am totally stuck with this issue. I have vulkan and CUDA and a bunch of other things i need on this computer, but if i try to install the vulkan:i386 libraries, apt prompts me saying its going to remove about 220 packages including things like xorg-mesa and i'm not going to risk that because i'd like to be able to log in on monday to do my day job :D

**Comment by kisak-valve** [comment]
Hello @Bam4d, odds are your issue is with nVidia's CUDA PPA, which is unrelated to this issue report. Please give #5778 a read.

**Comment by joro1881** [comment]
Update. Remote Steam playing works as a charm. So I don't need to download the games and flatpak installed steam is sufficient. Thank you all.
