### ISSUE TITLE
"Tick mark" disappears when selecting Unofficial/Custom Proton in Steam Play.

### ISSUE THREAD

**Issue by 0x221e** [ValveSoftware/steam-for-linux#7138]
#### Your system information

* Steam client version (build number or date): 1590536514
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking "Enable Steam Play for all other titles" and then selecting Unofficial Proton version (eg: GE Proton), works fine. However, whenever I restart steam, the "tick mark" disappears. Though, non-verified steam games work fine with selected unofficial proton.

However, when I select the official proton version (i.e Proton 5.0.7) ; the tick mark persists. Attached are the screenshots.
So, it is more of visual bug when unofficial proton is used.

![steam_issue1](https://user-images.githubusercontent.com/10757422/83090816-48428600-a0b7-11ea-821e-13231a1e6982.png)
![steam_issue2](https://user-images.githubusercontent.com/10757422/83090818-4973b300-a0b7-11ea-8784-0c9654be0858.png)

#### Steps for reproducing this issue:

1. Navigate Settings -> Steam Play
2. Select "Enable Steam Play for all other titles" -> Select custom/unofficial proton and restart steam. (You'll observe tick disappeared after restart when you navigate to Steam Play option)
3. Perform above steps by selecting any of the official Proton versions. (tick mark persists)

**Comment by kisak-valve** [comment]
Hello @0x221e, this issue is already being tracked at #6043. Closing as a duplicate.
