### ISSUE TITLE
Some Button presses are undetected for Horipad S for Nintendo Switch (Vendor 0f0d Product ID 00c1)

### ISSUE THREAD

**Issue by BrokenGale** [ValveSoftware/steam-for-linux#7140]
#### Your system information

* Steam client version (build number or date): May 27, 2020
* Distribution (e.g. Ubuntu): Pop_OS 20.04
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam is unable to detect certain button presses on my controller. Controller is a Horipad S for Nintendo Switch. Buttons that don't work are ZL, ZR and the control stick clicks. (JTKtest button number 6,7,10,11)
Had to add line: KERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00c1", MODE="0660", TAG+="uaccess" to /lib/udev/rules.d/60-steam-controller.perm.rules

#### Steps for reproducing this issue:

1. Add line ERNEL=="hidraw*", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00c1", MODE="0660", TAG+="uaccess" to /lib/udev/rules.d/60-steam-controller.perm.rules
2. Open game Project Cars 2
3. Try to reassign controls.

**Comment by kisak-valve** [comment]
Hello @BrokenGale, are you still experiencing this issue on an up to date system?

**Comment by BrokenGale** [comment]
I am sorry, this problem was solved long ago. I simply forgot to close the issue. Sorry @kisak-valve, thank you for your follow up.
