### ISSUE TITLE
Steam Overlay- Overlay cannot recognize Turkish letters

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#7149]
#### Your system information

* Steam client version (build number or date): May 30 2020
* Distribution (e.g. Ubuntu): Linux Mint 19.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Simply , via overlay when i want to type something that contaiins Turkish letters ( ç ,ğ , ö ,ü, ş etc ) it doesn't take the input. Only letters that exists on English works. I noticed it when i was in game and looking to some walkthrough guide that some Steam user prepared. 

I can reply with Turkish letters to this guide via Steam client just fine but is not possible via overlay.

https://steamcommunity.com/sharedfiles/filedetails/?id=636227319 

#### Steps for reproducing this issue:

1. A Turkish client and a preferably an OS set to Turkish language
2. Opening up Steam Overlay while in-game
3. Observing the issue

**Comment by kisak-valve** [comment]
Hello @Leopard1907, this issue is already being tracked at #2122. Closing as a duplicate.
