### ISSUE TITLE
Steam ignoring spaces when adding Non-Steam game

### ISSUE THREAD

**Issue by tim77** [ValveSoftware/steam-for-linux#7151]
#### Your system information

* Steam client version (build number or date): May 15 2020
* Distribution: Fedora 32 (Steam Flatpak)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

If game path contain spaces Steam ignoring it when you adding Non-Steam game and game will not run because of this.

#### Steps for reproducing this issue:

Try to add and run Unigine Valley for example (Windows version via Proton). Game folder contain spaces: `Valley Benchmark 1.0`

How it look like when you adding Unigine Valley:
![Снимок экрана от 2020-05-31 16-02-31](https://user-images.githubusercontent.com/5614476/83353158-397afe00-a359-11ea-84ca-a9a5992fe491.png)

How it **MUST** look like when you adding Unigine Valley:
![Снимок экрана от 2020-05-31 16-01-59](https://user-images.githubusercontent.com/5614476/83353191-747d3180-a359-11ea-8492-6c5c040cc236.png)

**Comment by kisak-valve** [comment]
Hello @tim77, this issue is already being tracked at #5220. Closing as a duplicate.
