### ISSUE TITLE
Failed to open VDPAU backend libvdpau_radeonsi.so when using remote play

### ISSUE THREAD

**Issue by TomokoK** [ValveSoftware/steam-for-linux#7155]
#### Your system information

* Steam client version (build number or date): May 30 2020, 20:39:29
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I am unable to utilize VDPAU hardware decoding on my client. Every time I start streaming, I get the following error:

`Failed to open VDPAU backend libvdpau_radeonsi.so: cannot open shared object file: No such file or directory`
`ffmpeg error: VDPAU device creation on X11 display :0 failed.`

Relevant installed packages:

- xf86-video-amdgpu-19.1.0_2
- libva-2.7.1_1
- libva-32bit-2.7.1_1
- libva-utils-2.7.1_1
- libva-vdpau-driver-0.7.4_4
- libva-vdpau-driver-32bit-0.7.4_4
- libvdpau-1.3_1
- mesa-vdpau-20.0.7_1
- mesa-vdpau-32bit-20.0.7_1
- vdpauinfo
- mesa-20.0.7_1
- mesa-32bit-20.0.7_1
- mesa-dri-20.0.7_1
- mesa-dri-32bit-20.0.7_1
- mesa-vaapi-20.0.7_1
- mesa-vaapi-32bit-20.0.7_1

Steam settings (client):

- Quality: Beautiful
- Performance Overlay: Details
- Limit bandwidth to: Unlimited
- Limit resolution to: Display resolution
- Speaker configuration: Stereo
- Enable hardware decoding

Steam settings (host):

- Play audio on host: Disabled
- Change desktop resolution to match streaming client: Disabled
- Dynamically adjust capture resolution: Disabled
- Use NVFBC capture on NVIDIA GPU: Disabled
- Enable hardware encoding: Enabled
- Enable hardware encoding on NVIDIA GPU: Enabled
- Enable hardware encoding on AMD GPU: Disabled
- Enable hardware encoding on Intel iGPU: Disabled
- Number of software encoding threads: Automatic
- Prioritize network traffic: Enabled

Client specs:

- Linux 5.4.43_1 #1 SMP PREEMPT Thu May 21 07:35:36 UTC 2020 x86_64 GNU/Linux
- Intel i5-8500
- AMD Radeon RX 570
- 16GB DDR4 2666MHz

Host specs:

- Windows 10 Pro x64 v.1909
- Intel i5-3470
- Nvidia GeForce GTX 1070ti w/ driver version 446.14
- 8GB DDR3 1600MHz

I have tried:

- Running steam-native runtime with all needed libraries (see https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_native_runtime)
- `chmod 777 libvdpau_radeonsi.so` - the lib32 and lib64 versions
- Installing ffmpeg locally
- `ln -s /usr/{lib32,lib}/vdpau/libvdpau_* ~/.local/.../ubuntu12_32/steam-runtime/usr/lib/{i386-linux-gnu,x86_64-linux-gnu}/vdpau/`
- Just using one type of VDPAU driver at a time (e.g. mesa-vdpau OR libva-vdpau-driver)
- Hard reinstall of Steam
- Reinstall of AMDGPU drivers
- Removing Steam packaged versions of libva/libvdpau (see https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Hardware_decoding_not_available)
- Reinstalled all Linux firmware packages
- Using proprietary AMDGPU-PRO libva/libvdpau packages
- Using `LIBVA_DRIVERS_PATH` and `VDPAU_DRIVER` environment variables when starting Steam

Both Moonlight and mpv can use VDPAU without any issue.

Here are all the relevant logs I could think of:

`pgrep steam | xargs -I {} cat /proc/{}/maps | grep libva` [libvaSteamUse.txt](https://github.com/ValveSoftware/steam-for-linux/files/4708945/libvaSteamUse.txt)
`pgrep steam | xargs -I {} cat /proc/{}/maps | grep libvdpau` [libvdpauSteamUse.txt](https://github.com/ValveSoftware/steam-for-linux/files/4708963/libvdpauSteamUse.txt)
`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh vainfo` [steam-runtime-vainfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/4708978/steam-runtime-vainfo.txt)
`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh vdpauinfo` [steam-runtime-vdpauinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/4708980/steam-runtime-vdpauinfo.txt)
`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh glxinfo` [steam-runtime-glxinfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/4708988/steam-runtime-glxinfo.txt)
[steamLog.txt](https://github.com/ValveSoftware/steam-for-linux/files/4709082/steamLog.txt)
[systemInfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/4709083/systemInfo.txt)

#### Steps for reproducing this issue:

1. Install VAAPI and VDPAU packages
2. Launch Steam in a terminal
2. Set Steam to use hardware decoding 
3. Launch a game stream
4. Watch the terminal for output regarding VDPAU and ffmpeg

**Comment by TomokoK** [comment]
This isn't an issue on ubuntu 20.04, trying more distros to see if this is just a Void issue

**Comment by TomokoK** [comment]
I've tried both using the vdpau drivers from ubuntu, and copying the void vdpau drivers to the default ubuntu path and neither work. Steam still cannot find the libvdpau_radeonsi.so file. I am out of ideas :(

**Comment by TomokoK** [comment]
Switched back to arch and I have the same issue.

**Comment by TomokoK** [comment]
I think I may have figured it out. The RX570 simply isn't powerful enough to decode the stream. It would be nice if the error message reflected this, as FFMPEG will throw the correct error.

**Comment by akostadinov** [comment]
Do you have this `libvdpau_radeonsi.so` anywhere? I doubt issue was lack of power. Seeing same issue now with Ryzen pro 7840u and the file is just nowhere to find.

**Comment by gustawdaniel** [comment]
I do not have such file like `libvdpau_radeonsi.so`, checked by 

```
sudo find / -name "libvdpau_radeonsi.so" 2>/dev/null
```

but I have nvidia version

```
sudo find / -name "libvdpau_nvidia.so" 2>/dev/null
/usr/lib/vdpau/libvdpau_nvidia.so
```

GPU

```
nvidia-smi
Mon Oct 28 13:05:12 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              3W /  115W |      15MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1035      G   /usr/lib/Xorg                                   4MiB |
+-----------------------------------------------------------------------------------------+
```

and


```
VDPAU_DRIVER=nvidia vdpauinfo
display: :0   screen: 0
Error creating VDPAU device: 1
```
