### ISSUE TITLE
Shader processing using all available memory

### ISSUE THREAD

**Issue by rLy07** [ValveSoftware/steam-for-linux#7157]
#### Your system information

* Steam client version (build number or date): 0.20200505.0
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* [Full steam info](https://gist.github.com/rLy07/a4ccbf9daf6418d4b578668acb9b5d0d)

#### Please describe your issue in as much detail as possible:
Steam uses all available memory when background processing shaders for Shadow of the Tomb Raider which makes the system unusable. I haven't noticed this with other games yet. First happened after the Friday update.
[screenshot at the end of it](https://i.imgur.com/p94zvDH.png) 

#### Steps for reproducing this issue:

1. Have SotTR installed and background shader processing on
2. Start Steam

**Comment by kisak-valve** [comment]
Hello @rLy07, this issue is already being tracked at https://github.com/ValveSoftware/Fossilize/issues/84. Closing as in favor of the existing issue report.
