### ISSUE TITLE
Steam appears to crash unpredictably when idle

### ISSUE THREAD

**Issue by dreac0nic** [ValveSoftware/steam-for-linux#7160]
#### Your system information

* Steam client version: Built, Jun 1, 2020 at 20:22:35; API, v020; Package versions, 1591052255
* Steam hardware information: [gist](https://gist.github.com/dreac0nic/9916ce900855ca96b4d35e59ff5a62d1)
* Distribution: ArchLinux x64 (kernel 5.6.15-arch1-1)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam launches and I can log in just fine. However, any given time while the client is in the background (I have yet to see it crash in front of me), it will suffer a segfault and close. The error messages have largely been unhelpful, and I've attetmpted to dig deeper into them or the minidumps for answers. All I've found is the floating point exception.

Sometimes, I'll be able to play for long periods and have no issues what-so-ever. Steam has even gone all night. Some days I can't even get very far past the Library loading.

Here are some of the dumps and logs from the last few crashes/asserts today:

Tmp log out: [gist](https://gist.github.com/dreac0nic/63c59a536a1697533829f48a8477357e)
Last four minidumps: [tar](https://drive.google.com/file/d/1BBQd9kTpLILiu3gzlPT2Jty-s3zugN6h/view)
A couple shell outs from some of the sessions: [short](https://gist.github.com/dreac0nic/cd85a463e5fd8dbf545229c14a84004a), [long](https://gist.github.com/dreac0nic/ae6acc502ac75050a435092b2f10e602)

#### Steps for reproducing this issue:
I'm not sure how useful these steps are, but this is all I'm doing.

1. Run Steam
2. Idle in the background
3. Wait
4. Silent failure

**Comment by kisak-valve** [comment]
For reference, assert_20200601162039_1.dmp and crash_20200601165916_2.dmp are SIGFPE in steamclient.so, friendsui.so. The other two are DUMP_REQUESTED in crashhandler.so.

**Comment by dreac0nic** [comment]
Interesting. I just tried to grab the latest shell outputs and dumps I had, but I've been trying different methods of launching so they may not line up. Would additional dumps/specific tests be more helpful?

**Comment by dreac0nic** [comment]
If this is not the proper channels for it, I apologize, but at this point I'm a little at a loss. I've tried a number of things in an effort to locate the effect, but haven't had any success. Here's a list of things I've tried:

- Switching window managers: gnome, i3, xmonad, awesome, kde
- Upstream and Zen kernels
- Drivers (mesa, mesa src stable, mesa src latest) w/ friends
- Reinstalling the entire system
- Running beta and normal versions of steam among all these
- Making sure Steam controller udev rules were correct (one of the errors referenced SteamControlle files)

This among a number of small tweaks I've been trying to either source the cause for find a solution. The next thing I'm going to try is running it on just vanilla Ubuntu and if this fails I guess it's got to be hardware, I just can't find what hardware might be causing that, nor do I see any other issues on other platforms or applications. Non-steam games of various variety run fine on linux, even games that don't require Steam running will run fine. It's only the ones that close upon losing Steam that are inaccessible.

Without further ado, here's some of the crash info while running DOOM Eternal under plasma/zen/stable src. There are new gdb dumps/logs/stack traces, unfortunately because currently trying to run Steam with GDB gives me the following and I haven't even started to pick this one apart yet:
```
gdb: /home/spenser/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libdebuginfod.so.1)
```

If any gdb info would be provocatively helpful, I fix that and grab it later.

**journal/system log**
```
Dec 05 21:55:16 calcryx systemd[1]: systemd-coredump@0-22428-0.service: Succeeded.
Dec 05 21:55:16 calcryx systemd-coredump[22430]: Process 19887 (steam) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 20697:
                                                 #0  0x00000000e14dc0c9 n/a (/home/spenser/.local/share/Steam/ubuntu12_32/libmiles.so + 0x600c9)
                                                 #1  0x00000000e14dc389 n/a (/home/spenser/.local/share/Steam/ubuntu12_32/libmiles.so + 0x60389)
                                                 #2  0x00000000e14bfb6d n/a (/home/spenser/.local/share/Steam/ubuntu12_32/libmiles.so + 0x43b6d)
                                                 #3  0x00000000e14dd914 n/a (/home/spenser/.local/share/Steam/ubuntu12_32/libmiles.so + 0x61914)
                                                 #4  0x00000000f7d11628 start_thread (libpthread.so.0 + 0x8628)
                                                 #5  0x00000000f79f8c8a __clone (libc.so.6 + 0x108c8a)
                                                 
                                                 Stack trace of thread 19966:
                                                 #0  0x00000000f7f08549 __kernel_vsyscall (linux-gate.so.1 + 0x549)
                                                 #1  0x00000000f7d17d7c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xed7c)
                                                 #2  0x00000000f5a11da6 n/a (radeonsi_dri.so + 0x8eda6)
                                                 #3  0x00000000f7d11628 start_thread (libpthread.so.0 + 0x8628)
                                                 #4  0x00000000f79f8c8a __clone (libc.so.6 + 0x108c8a)
                                                 
                                                 Stack trace of thread 19968:
                                                 #0  0x00000000f7f08549 __kernel_vsyscall (linux-gate.so.1 + 0x549)
                                                 #1  0x00000000f7d17d7c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xed7c)
                                                 #2  0x00000000f5a11da6 n/a (radeonsi_dri.so + 0x8eda6)
                                                 #3  0x00000000f7d11628 start_thread (libpthread.so.0 + 0x8628)
                                                 #4  0x00000000f79f8c8a __clone (libc.so.6 + 0x108c8a)
                                                 
                                                 Stack trace of thread 19969:
                                                 #0  0x00000000f7f08549 __kernel_vsyscall (linux-gate.so.1 + 0x549)
                                                 #1  0x00000000f7d17d7c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xed7c)
                                                 #2  0x00000000f5a11da6 n/a (radeonsi_dri.so + 0x8eda6)
                                                 #3  0x00000000f7d11628 start_thread (libpthread.so.0 + 0x8628)
                                                 #4  0x00000000f79f8c8a __clone (libc.so.6 + 0x108c8a)
                                                 
                                                 Stack trace of thread 19962:
                                                 #0  0x00000000f7f08549 __kernel_vsyscall (linux-gate.so.1 + 0x549)
                                                 #1  0x00000000f79f402b syscall (libc.so.6 + 0x10402b)
                                                 #2  0x00000000e618ba16 n/a (/home/spenser/.local/share/Steam/ubuntu12_32/chromehtml.so + 0x2aa16)
```

**/tmp/gameoverlayui.log**
```
Sun Dec 06 05:55:07 2020 UTC - GameOverlay process started: pid: 22315
Sun Dec 06 05:55:07 2020 UTC - GameOverlay process connecting to: pid: 22228
Sun Dec 06 05:55:07 2020 UTC - BuildID: 1603992987
Sun Dec 06 05:55:07 2020 UTC - Steam Path: /home/spenser/.local/share/Steam/
Sun Dec 06 05:55:07 2020 UTC - Got gameid on commandline: 782330
Sun Dec 06 05:55:16 2020 UTC - /data/src/common/pipes.cpp (835) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
Sun Dec 06 05:55:16 2020 UTC - /data/src/common/pipes.cpp (835) : Fatal assert failed: /data/src/common/pipes.cpp, line 835.  Application exiting.

Sun Dec 06 05:55:16 2020 UTC - _ExitOnFatalAssert
```

In addition, I've also archived a number of the dumps together and tar'd them: [tar](https://drive.google.com/file/d/1CQaVuFCtczn9OyfMIupmKFTaWdY0EDTL/view?usp=sharing)

I hope that is sufficient information to spark someone's thoughts. Also certainly don't want to come across as demanding an answer, but if anything maybe this info catches someone else with a similar problem or someone who sees a solution that I so clearly cannot!

Thanks!

**Comment by kisak-valve** [comment]
Hello @dreac0nic, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
