### ISSUE TITLE
Crash when viewing properties for game using a deleted Steam Play compatibility tool

### ISSUE THREAD

**Issue by hkva** [ValveSoftware/steam-for-linux#7162]
#### Your system information

* Steam client version (build number or date):  1591052255
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Trying to view game properties for a game using a deleted Steam Play compatibility tool causes the Steam client to crash.

#### Steps for reproducing this issue:

1. Download a custom Steam Play compatibility tool and install it to `~/.steam/root/compatibilitytools.d/` (ex: https://github.com/stevenlafl/Proton/releases/tag/proton-5.0-7-sdk148 fixes for Scrap Mechanic)
2. Restart Steam
3. Set a game to use the aforementioned compatibility tool
4. Remove the tool from `~/.steam/root/compatibilitytools.d/`
5. Restart Steam
6. Right-click the game in your Steam library and select "Properties..."

**Comment by kisak-valve** [comment]
Hello @hkva, this issue is already being tracked at #6986. Closing as a duplicate.
