### ISSUE TITLE
Steam Remote Play Together linux host streams just a black screen

### ISSUE THREAD

**Issue by Elinvention** [ValveSoftware/steam-for-linux#7167]
#### Your system information

* Steam client version (build number or date): 4 June 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expect to be able to act as a host on a Manjaro box and play my games together with my friend who play from Manjaro too.
Instead, my friend gets a black screen with music, sounds, the mouse cursor and a blinking icon, as shown in this screenshot.

![e23850d7_Schermata da 2020-06-05 22-35-46](https://user-images.githubusercontent.com/5737945/83920669-041d4880-a77d-11ea-93e6-40daa875df13.png)

#### Steps for reproducing this issue:

1. Open a game that supports Steam Play Together like "I hate running backwards".
2. Invite a friend with Shift + Tab
3. The friend joins, but he just receives a black screen

**Comment by kisak-valve** [comment]
Hello @Elinvention, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

There's some other issue reports similar to this related to hardware encoding / decoding failing and you can try turning it off at Steam -> Settings -> Remote Play -> Advanced client/host options. If that helps, then you can slowly re-enable each option one at a time until you find which setting is causing the black stream.

**Comment by Elinvention** [comment]
My friend unchecked "Enable hardware decoding" and now he can see. Thanks!

**Comment by XenGi** [comment]
I have the exact same issue.
Here are my system information from steam: https://gist.github.com/XenGi/e3826f27d765f4aa82af89d5de982226

I start steam on my windows and linux box. Then I open a game via "stream" button on the linux box. I can here sound and I can see the mouse moving on the windows box but I have only black screen on the linux box.

**Comment by hyphone** [comment]
My Setup:

Notebook:
AMD iGPU
Nvidia dGPU

Steam starts on the dGPU

Host:
Fedora 35
GNOME
Wayland

Client:
Nvidia Shield TV Pro

I tried to disable every hardware acceleration option in the Host and Client side with no effect.

I also tried to launch Steam with `steam -pipewire-dmabuf`, shared my screen and also got a black screen on the client side.

**Comment by zillem** [comment]
I can play games on my steam link, but the big picture interface will not show, also no desktop sharing possible. Except for in game streaming the TV shows only a black screen with a mouse pointer, Sound is also coming through, and input from the controller also get through to the computer.
I now start the game at the computer, and can play on the TV, far from ideal but works for now.

Host:
- Fedora 35
- GNOME
- Wayland
- AMD RX 6600XT

Client:
- Steam Link

**Comment by DrEVILish** [comment]
I'd like to also put my hat in the ring, I'm also having the same issues

Arch KDE Wayland Nvidia
I've tried both Steam Native and Steam Runtime both installed from Arch/AUR

https://gist.github.com/DrEVILish/47439ba9b9538da349e10e63343d5ffa

Steam Link Client is iPhone

Open Steam Link, Connect to Big Picture, Black Screen on iPhone
Alt+Tab to desktop, Black Screen on iPhone with a visible mouse cursor which moves with host mouse movement

**Comment by hyphone** [comment]
@Elinvention could you re-open this issue? It's still a problem for some.

**Comment by Elinvention** [comment]
@hyphone my original issue was solved. You should open a new one.
