### ISSUE TITLE
Toggling Proton version on/off forces redownload of entire game

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#7168]
#### Your system information

* Steam client version (build number or date): June 4 2020
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have "Force compatibility tool" enabled to use Proton with a certain game. Looking into the dropdown of available Proton versions to see if the Proton beta is available for testing, it's very easy to accidentally disable the option altogether.

Re-enabling the option caused a re-download of the entire 64GB game.

#### Steps for reproducing this issue:

1. Enable 'Force compatibility tool' option, install game
2. Disable/re-enable 'Force compatibility tool' option
3. Observe whole game is redownloaded.

**Comment by kisak-valve** [comment]
Hello @vadi2, this issue is already being tracked at #5901. Closing as a duplicate.

**Comment by vadi2** [comment]
Right! Thanks. I searched for `redownload` but didn't find relevant reports.
