### ISSUE TITLE
HL:Alyx missing executable: hlvr.sh

### ISSUE THREAD

**Issue by towen** [ValveSoftware/steam-for-linux#7170]
#### Your system information

* Steam client version (build number or date): Build date 4 Jun 2020 05:51  package versions 1591251555
* Distribution (e.g. Ubuntu): Debian 9 Sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Previously, HL:Alyx worked perfectly on my system since the day I bought it. (amazing game btw, and props to Valve for having a native Linux version in the first place!)
A few weeks ago an update either to hl:alyx or Steam caused a "missing executable" error when I try to launch the game. Sadly, I can't tell you exactly which update borked it.
When I check, I have no file called hlvr.sh. Instead, I have:
/usr/local/games/steamSSD/steamapps/common/Half-Life Alyx/game/bin/win64/hlvr.exe
bit if I try `locate hlvr.sh` no files are found on my system.

As far as I am aware, I should not have a folder called bin/win64. instead I should have bin/linux64 or similar, but it's not there. It seems that since the update, Steam has been installing the Windows version of the game instead of the native Linux one.
I have tried "verify integrity of game files" as well as uninstalling / reinstalling the game.
Steam support advised me that Debian is not "officially supported" and suggested that I should either try on Ubuntu or ask here on GitHub.

If there was some workaround involving steamcmd to force it to install the Linux version, that would be helpful. Something like the inverse of #5638

#### Steps for reproducing this issue:

1. Install HL:Alyx under Debian
2. Run game
3. See error message:
![image](https://user-images.githubusercontent.com/65292785/83954911-2da1a700-a845-11ea-8530-e2a3ee15b6e3.png)

Any help gratefully appreciated!

Cheers,
Tom

**Comment by kisak-valve** [comment]
Hello @towen, this reads as if Steam had a hard time transitioning from the Windows version to the Linux version.

From the native release:
```
On Linux, if you had installed the game through Proton previously, please follow these steps to correctly download the update:

    Go in the Properties for Half-Life Alyx by right-clicking the game in your Steam Library
    Check the "Force the use of a specific Steam Play compatibility tool" box
    Uncheck the box, and the download will properly complete.
```
(https://steamcommunity.com/games/546560/announcements/detail/3758762298552654078)

**Comment by towen** [comment]
Hi @kisak-valve - that worked perfectly. Thanks so much! :grinning:  
And thanks again for bringing VR to Linux. I no longer have any reason to boot Windows (which makes me feel dirty every time)

Cheers
Tom
