### ISSUE TITLE
Cannot install Steam for Linux

### ISSUE THREAD

**Issue by manfrommahim** [ValveSoftware/steam-for-linux#7171]
#### Your system information

* Steam client version (build number or date): 1.0.0.61
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Launch Steam installer for Linux
2. It never finishes updating because of checksum mismatch.
3. It terminates with an error message.

**Comment by kisak-valve** [comment]
Hello @manfrommahim, does running `steam --reset` from a terminal help? Alternatively, you can try moving `~/.steam` and ~/.local/share/Steam` somewhere out of the way so that Steam's bootstrapper will make a fresh attempt to setup the client.

**Comment by manfrommahim** [comment]
I tried what you suggested, namely, 1] running steam --reset from the terminal and 2] Moving the hidden steam folders out of the way. Neither method worked.

**Comment by kisak-valve** [comment]
Can you attach `~/.steam/root/logs/bootstrap_log.txt`?

**Comment by manfrommahim** [comment]
Okay. Here is the log attached. 
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/4743509/bootstrap_log.txt)

**Comment by manfrommahim** [comment]
Hi, is there any solution to my problem yet?

**Comment by TTimo** [comment]
The client refuses to install, reporting that it is getting modified/corrupted files from the CDN. If you are behind a proxy that is either misconfigured, buggy or hostile that could be a reason. The CDN being misconfigured is another possibility, although less likely.

You would need to download the manifest yourself, (http://client-download.steampowered.com/client/steam_client_ubuntu12 from the bootstrap log), and some of the files yourself based on that - the `bins_ubuntu12.zip` is probably a good candidate. See if the checksums match, or if the file is truncated, modified etc.

All the files the steam client works with during bootstrap are in `~/.steam/root/package` for comparison.

**Comment by kisak-valve** [comment]
Hello @manfrommahim, are you still experiencing this issue on an up to date system?

**Comment by manfrommahim** [comment]
Hi, thank you so much for your query. All is well.

Wish you and your team a happy new year.

Warmly
Suhit
