### ISSUE TITLE
Steam crashes when attempting to download anything

### ISSUE THREAD

**Issue by gunslingerfry** [ValveSoftware/steam-for-linux#7174]
Just installed the steam client to download some soundtracks actually. Brand new machine and install (about 3 weeks ago).

#### Your system information
[system_information.txt](https://github.com/ValveSoftware/steam-for-linux/files/4748779/system_information.txt)
* Steam client version (build number or date): See dump of system information
* Distribution (e.g. Ubuntu): Manjaro 20.0.3
* Opted into Steam client beta?: [Yes/No] Yes, no difference between the two
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Expect downloads to succeed and not crash
Things tried: 
* moving library folder somewhere else
* installing steam-native runtime
* switching to beta client

#### Steps for reproducing this issue:

1. Install steam-manjaro
2. Run Steam, login
3. Attempt to install or download anything
4. Crashes

minidumps: 
[minidumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/4748800/minidumps.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are SIGFPE in steamui.so.

**Comment by kisak-valve** [comment]
Hello @gunslingerfry, are you still experiencing this issue on an up to date system?

**Comment by mryellow** [comment]
My experience was it's so poor that I'll never install Steam on Linux again.

First it demands a dual-arch and duplicate 32 Bit installs of everything.

Then it lags to death whenever downloading.

**Comment by kisak-valve** [comment]
Closing pending feedback.
