### ISSUE TITLE
[Feature Request] Add Proton DB results to game STEAM page

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#7175]
Can we please get a small part of each page for each game on STEAM showing a badge for the ProtonDB rating some other small useful info related added too?

Not sure precisely the best way to do it, but whenever I look into a new game for me, as a Linux gamer, I check the ProtonDB rating pretty much first. And having that (or something equivalent) baked into the storage page for each game on STEAM would go a long way to make it convenient for me, and demonstrate that gaming on Linux is real.

So, please? :)

**Comment by kisak-valve** [comment]
Hello @BloodyIron, I doubt that any more third party data sources will be integrated into Steam's store, especially not for a single platform, but there are some third party browser extensions around and one of them may be interested in pondering what it would take to make that happen.
