### ISSUE TITLE
Can't open Civilization 6

### ISSUE THREAD

**Issue by souenzzo** [ValveSoftware/steam-for-linux#7176]
#### Your system information

* Steam client version (build number or date): 
```
~ pacman -Qs steam
local/steam 1.0.0.62-1
    Valve's digital software delivery system
local/steam-native-runtime 1.0.0.62-1
    Native replacement for the Steam runtime using system libraries
```
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

I can't start civilization from GUI

After google a bit, i see that ` LD_PRELOAD=/usr/lib/libfreetype.so.6 steam steam://rungameid/289070` start's my game, but without `LD_PRELOAD`, it not work too.
Both stdouts, with and without LD_PRELOAD, are here:

https://gist.github.com/souenzzo/5a4d850c1f6548d70ddd1bf6c5181200

**Comment by kisak-valve** [comment]
Hello @souenzzo, this issue was already evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/6234#issuecomment-619045979 and needs to be resolved by the game's devs.
