### ISSUE TITLE
steam handles xproperties wrong

### ISSUE THREAD

**Issue by damianatorrpm** [ValveSoftware/steam-for-linux#7178]
Steam client latest / irrelevant
Distro: irrelevant
See https://steamcommunity.com/groups/SteamClientBeta/discussions/0/648814841695962896/
It happens basically on all non-gnome WM's

#ISSUE
When you maximize the Steam window (by clicking the maximize button at the upper right corner of the window) and then demaximize the window you are not able to maximize it again. The button keep showing you the "demaximize icon" also if Steam is not maximized anymore, untill you minimize the window and show it again. Only now, you are able to maximize Steam again.

#STEPS
Click the "maximize" button to maximize the Steam window
Click the "demaximize" button to demaximize the Steam window
Click the "maximize" button to maximize it again

#EXPECTED
The button icon should display the "maximize icon" and should maximize the window. But it doesn't. It shows the "demaximize icon" and doesn't maximize Steam (this until you minimize and show the window)

**Comment by damianatorrpm** [comment]
So what X11 atoms you want WM's to re-read or what magic to do so it updates,
you maximize icon? chrome CSD works fine.

**Comment by kisak-valve** [comment]
Hello @damianatorrpm, this issue is already being tracked at #3792. Closing as a duplicate.
