### ISSUE TITLE
Crash when launching a game through remote play with dedicated AMD GPU

### ISSUE THREAD

**Issue by Tooniis** [ValveSoftware/steam-for-linux#7181]
#### Your system information

* Steam client version: `Jun  4 2020, at 05:51:01`
* Distribution: Arch Linux
* Kernel version: `5.6.13-arch1-1`
* Opted into Steam client beta?:  No
* Have you checked for system updates?: Yes
* Dedicated GPU: AMD Radeon R5 M330
* Integrated GPU: Intel HD Graphics 520
* Mesa version: `20.0.7`

#### Please describe your issue in as much detail as possible:
The Steam client crashes right after launching a game through remote play, then after 10 seconds or so, it launches a new client instance with a weird monospace font. It happens **only when using the dedicated AMD GPU**, and never when using the integrated Intel GPU. I'm using steam link on Android.

I got this after the crash (changed my username to `$USER`):

    >>> Stopped desktop stream
    >>> Starting desktop stream
    breakpad exception handler for appid(steam)/version(1591052255)
    assert_20200606122932_1.dmp[8168]: Uploading dump (out-of-process)
    /tmp/dumps/assert_20200606122932_1.dmp
    home/$USER/.steam/steam.sh: line 750: 7684 Segmentation fault (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

#### Steps for reproducing this issue:

1. Launch the Steam client with `DRI_PRIME=1` to use the dedicated GPU
2. Connect remote play
3. Launch a game
4. Crash

**Comment by gardotd426** [comment]
Also, hardware decoding/encoding on both the host and remote machine do not work with AMD GPUs on a Windows host and Linux remote. The Steam Remote play settings menu says to report this if it doesn't work, I guess I should report a second issue

**Comment by madhavpcm** [comment]
Steam Client: 
Built : Jul 20 2021, 22:25:57
Steam API: v020
Steam Package Version: 1626824053
Distro: Manjaro
Kernel:5.14.0-AMD-znver2
DGPU: Radeon RX5600M
IGPU: Radeon Vega 6
Mesa:21.2.1
Laptop: Dell G5 SE 5505(2020)
SmartShift : Disabled

DRI_PRIME=1 crashes the whole system, I got a glimpse at the terminal saying X server crashed I couldn't get the image correctly. But this was with manjaro-steam found in pacman. I tried with flatpak steam and these are the results I get 

![image](https://user-images.githubusercontent.com/59736487/131694244-e415410e-2896-4394-9a65-86f17de1a8c1.png)

![image](https://user-images.githubusercontent.com/59736487/131694206-08ab2b46-2cf8-4de4-8ca8-42f75e2ba554.png)

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system? If you are, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing pending feedback.
