### ISSUE TITLE
big picture controller support broken

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#7182]
#### Your system information

* Steam client version (build number or date): june 4 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

any controller I used (tried switch pro and ps4 controller as well as a sn30 pro plus) would not work in steam big picture, no inputs registared and whould even occasionally cause frezzes. controller support works whithin games though its only in steam big picture

#### Steps for reproducing this issue:

1. open steam in big picture
2. connect any controller
3. try to operate big picture with the controller

**Comment by kisak-valve** [comment]
Hello @zany130, are you still experiencing this issue on an up to date system?

**Comment by zany130** [comment]
No looks like it might have been an issue with my system and honestly,  I forgot about this issue
