### ISSUE TITLE
Ubuntu 20.04 apt packaging issue?

### ISSUE THREAD

**Issue by furai** [ValveSoftware/steam-for-linux#7183]
```
The following packages have been kept back:
  steam:i386
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

```
apt show steam:i386 -a
Package: steam:i386
Version: 1:1.0.0.62
Priority: extra
Section: oldlibs
Maintainer: Valve Corporation <linux@steampowered.com>
Installed-Size: 32.8 kB
Depends: steam-launcher (>= 1:1.0.0.62)
Homepage: http://www.steampowered.com/
Download-Size: 8,052 B
APT-Sources: http://repo.steampowered.com/steam precise/steam i386 Packages
Description: Launcher for the Steam software distribution service
 This is a transitional package that can be safely removed once steam-launcher is installed.

Package: steam:i386
Version: 1:1.0.0.61-2ubuntu3
Priority: extra
Section: multiverse/games
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4,504 kB
Pre-Depends: debconf
Depends: libgl1-mesa-dri (>= 17.3) | libtxc-dxtn0, libgl1-mesa-glx, libgpg-error0 (>= 1.10), libudev1, libxcb-dri3-0 (>= 1.11.1), libxinerama1 (>= 2:1.1.1), xz-utils, debconf (>= 0.5) | debconf-2.0, libc6 (>= 2.15), libstdc++6 (>= 4.8), libx11-6
Recommends: steam-devices, ca-certificates, fontconfig, fonts-liberation, libxss1, mesa-vulkan-drivers, xterm | x-terminal-emulator
Suggests: libnvidia-gl-390 | libnvidia-gl-435 | libnvidia-gl-440
Conflicts: steam-launcher
Replaces: steam-launcher
Homepage: https://steamcommunity.com/linux
Download-Size: 1,451 kB
APT-Manual-Installed: no
APT-Sources: http://pl.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
Description: Valve's Steam digital software delivery system
 Steam (https://www.steampowered.com) is a software content delivery system
 developed by Valve software (https://www.valvesoftware.com).  There is
 some free software available, but for the most part the content delivered
 is non-free.
 .
 This package comes with a fairly substantial non-free license agreement
 that must be accepted before installing the software.  If you have any
 opposition to non-free work, please select "I DECLINE" during the package
 installation dialogs.   There are also additional agreements in various
 parts of the application that differ from the original agreement.  In
 other words, pay attention and read carefully if you're worried about your
 rights.
```

Hey, 

* Steam client version: Jun 4 2020 at 05:51:01
* Distribution: Ubuntu 20.04 LTS 64-bit
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

So recently when trying to update my system it all the time reports that Steam cannot be upgraded. I've installed it few weeks ago using `apt install steam-installer`. Did the method of installation from deb repositories change?

Can I just safely remove the mentioned package?

Maybe I should install `steam-launcher` instead?

Can anyone shed some light on this? Thanks in advance for your time!

Cheers,
Furai

**Comment by kisak-valve** [comment]
Hello @furai, looks like recent valve repo work removed `steam-installer` and I'm not aware of any instructions that told users to use `steam-installer` instead of `steam`.

Historically, the distro-provided steam package used a modified folder layout with Steam which does not interact well with the Valve-provided steam package. This has improved a bit in recent history, but the distro package retains compatibility with the grandfathered in folder layout and it's most likely still a rough experience. You can tell if you have the old distro folder layout by checking if `~/.steam/steam` is a folder and not a symlink.

For some clarity, can you run `apt policy steam:i386`?

In general, as long as long as Steam runs fine for you, the package update should have very minor updates. You should not need to update the bootstrap environment to continue to using Steam. The most significant to the end user being updates to udev rules for gamepads.

**Comment by furai** [comment]
As requested output of `$ apt policy steam:i386`:
```
steam:i386:
  Installed: 1:1.0.0.61-2ubuntu3
  Candidate: 1:1.0.0.62
  Version table:
     1:1.0.0.62 500
        500 http://repo.steampowered.com/steam precise/steam i386 Packages
 *** 1:1.0.0.61-2ubuntu3 500
        500 http://pl.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
        100 /var/lib/dpkg/status
```

My steam folder is symlinked.
`/home/<user>/.steam/steam -> /home/<user>/.steam/debian-installation/`

So what does it mean exactly?
What is currently the preferred way to install Steam using commandline?

**Comment by arnediekmann** [comment]
A workaround seems to be to just remove steam and reinstall it via the Deb-Package available for download:

```sh
$ sudo apt remove steam -y
$ sudo apt autoremove -y
$ wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb
$ sudo dpkg -i steam.deb
$ rm steam.deb
```

**Comment by smcv** [comment]
The `steam-installer` name is Ubuntu-specific. The packages are:

* Official Valve packages from repo.steampowered.com: `steam-launcher` (and a transitional `steam:i386` package)
* Ubuntu multiverse: `steam:i386`, `steam-installer` and `steam-devices`
* Debian non-free: `steam:i386` and `steam-devices`

Either install the official Valve packages from repo.steampowered.com, or install the Ubuntu packages (or the Debian packages if you're on Debian), but don't install from a mixture of sources.

**Comment by furai** [comment]
@smcv thanks for a in-depth reply. :) I'll just use whatever Steam/Valve is providing.

**Comment by redmcg** [comment]
I found when using the Ubuntu multiverse repos (with a minimal install of Ubuntu 20.04.1), I needed the `focal-updates` repo. So I had to run:
`sudo apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -cs)-updates main restricted universe multiverse"`

for it to work. Otherwise I got:
````
The following packages have unmet dependencies:
       steam:i386 : Depends: libudev1:i386 but it is not going to be installed
````

**Comment by Ma5onic** [comment]
Instructions are provided on the steam website:
http://repo.steampowered.com/steam/
