### ISSUE TITLE
Steam crashes on start due to Illegal instruction

### ISSUE THREAD

**Issue by ProkopRandacek** [ValveSoftware/steam-for-linux#7184]
* Steam client version: 1.0.0.61-4 (from arch repository)
* Distribution: Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Steam crashes on start due to Illegal instruction

[cpu info & steam console output](https://gist.github.com/ProkopRandacek/48025a8754f4c2190cae416e2fdf9516)
I have seen #5164 but steam used to work for a few months on my machine and still works on windows.

**Comment by kisak-valve** [comment]
Hello @ProkopRandacek, I reproduced this issue on my Arch test box and for me the illegal instruction is `VMOVQ` in `/usr/lib32/dri/r600_dri.so`. That makes this a mesa 20.0.7 -> 20.1.0 regression where AVX is unconditionally used on hardware that does not support it.

This is being tracked at https://bugs.archlinux.org/task/66972.

**Comment by ProkopRandacek** [comment]
Thank you for your help. Simply replacing `lib32-mesa` with `lib32-mesa-git` fixed the issue.
