### ISSUE TITLE
Steam Remote Play Encoder Issues

### ISSUE THREAD

**Issue by ntropy83** [ValveSoftware/steam-for-linux#7185]
#### Your system information

* Steam client version (build number or date): 4th of June 2020 5:51 am
* Distribution (e.g. Ubuntu): Manjaro Budgie
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I figured that when I stream my desktop, the encoder is "Desktop OpenGL NV12 + x264". When I stream a game it changes to "Game Vulkan RGB + libyuv + x264". Whenever that happens some games wont work correctly. For instance Warframe, Homefront: The Revolution or StarCitizen. I know StarCitizen is not supported, but it shows the error pretty good. While Warframe is just broken and crashes the Stream, StarCitizen will start, but there will be vital buttons missing within the game to start it, as well as your friends list. This error occurs when I launch on the laptop (Windows 10).

If I launch from steam link, the encoder never switches and always stays at "Desktop OpenGL NV12 + x264" and that way StarCitizen will work ,as well as the other games. So I only have this issue with my laptop and remote play.

Is there by chance a command or thing I can do to always have the "Desktop OpenGL NV12 + x264" encoder while streaming from the laptop? 

#### Steps for reproducing this issue:

1. Get a Windows 10 laptop
2. remote play a game from the Linux host
3. Try for instance Warframe, Homefront: The Revolution or StarCitizen, they wont work

Thanks for your help in advance.
Greetings,
~ent

**Comment by ntropy83** [comment]
I have a little update on this: when I launch the Warframe launcher or any kind of game launcher via in home streaming; I then can launch Star Citizen and play without issues. It stays on: "Desktop OpenGL NV12 + x264" then. 

This a small workaround so I can remote play on the laptop.

**Comment by insanemal** [comment]
Can we please reopen this. 

I have severe performance issues when it flicks to Vulkan +libyuv mode. 

This is a recent change and it's made everything far far worse

**Comment by insanemal** [comment]
To expand on this, when it flicks to "Game vulkan RGB + libyuv" performance tanks. I've got over 100ms display latency.

When in Desktop OpenGL NV12, performance is fantastic. 

What's extra frustrating is if I force an application open in the background it flips over to Desktop OpenGL and the game continues running and I can see the output fine with low (10-14ms) latency. 

I don't understand why its flipping to this capture mode.

Can we have a tickbox to disable it?

**Comment by parkerlreed** [comment]
Still seeing this on up-to-date everything with AMD on Linux. Anything that uses Game Vulkan RGB maxes out at 25 FPS and is an absolutely terrible experience.
