### ISSUE TITLE
Steam menu does not open from system tray

### ISSUE THREAD

**Issue by kortewegdevries** [ValveSoftware/steam-for-linux#7187]
**System Information**
```
Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
Desktop: Xfce 4.14.2 Distro: Ubuntu 20.04 LTS (Focal Fossa) 
```
* Steam client version: 
Built: Jun 4 2020 05:51:01
Steam API: v020
Steam package versions: 1591251555
```
apt-cache show steam -a
Package: steam
Architecture: i386
Version: 1:1.0.0.61-2ubuntu3
Multi-Arch: foreign
Priority: extra
Section: multiverse/games
Origin: Ubuntu
```
* Distribution: Xubuntu 20.04
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

**Steps for reproducing this issue**

1. Install Steam from Ubuntu repo: steam,steam-installer,steam-devices or steam_latest.deb
2. Click on Steam tray icon
3. Steam menu doesn't appear

**Expected Outcome**
Steam taskabr menu should appear.

**Additional Notes**:

1. Steam is running under Firejail (packages firejail, firejail-profiles) with default config made using ``sudo firecfg``` I haven't checked if FireJail is causing this.

Terminal Output: [firejail_steam.log](https://github.com/ValveSoftware/steam-for-linux/files/4768698/firejail_steam.log)

2. Steam menu relies on libappindicator libdbusmenu both are installed
Terminal output:
```
~: dpkg -l libdbusmenu-* libappindicator-*
||/ Name                             Version                           Architecture Description
+++-================================-=================================-============-===============================================================>
ii  libappindicator-dev              12.10.1+20.04.20200408.1-0ubuntu1 amd64        Application Indicators
ii  libdbusmenu-glib-dev:amd64       16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - development files
ii  libdbusmenu-glib4:amd64          16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus
ii  libdbusmenu-gtk-dev:amd64        16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - GTK+ version developement>
ii  libdbusmenu-gtk3-4:amd64         16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - GTK+ version
ii  libdbusmenu-gtk3-dev:amd64       16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - GTK+ version developement>
ii  libdbusmenu-gtk4:amd64           16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - GTK+ version
ii  libdbusmenu-jsonloader-dev:amd64 16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - Test lib development files
ii  libdbusmenu-jsonloader4:amd64    16.04.1+18.10.20180917-0ubuntu6   amd64        library for passing menus over DBus - Test lib
ii  libdbusmenu-qt5-2:amd64          0.9.3+16.04.20160218-2build1      amd64        Qt implementation of the DBusMenu protocol
ii  libdbusmenu-tools                16.04.1+18.10.20180917-0ubuntu6   amd64        tools useful during development with libdbusmenu
```
**Possible Resolutions Tried**

Removing steam packages via apt, manually removing folders except /home/korte/.steam/debian-installation/steamapps/, doeesn't help.

**Comment by kisak-valve** [comment]
Hello @kortewegdevries, Steam uses libdbusmenu and friends built against gtk2 with the tray icon. A while back using the host variant of this became more problematic than it was worth. If there is a host variant detected, then the steam runtime variant is pinned so that it is prioritized over the host variant.

Can you list the contents of `~/.steam/debian-installation/ubuntu12_32/steam-runtime/pinned_libs*`, delete the `pinned_libs*` folders so that Steam regenerates them on next start, then check if the regenerated folders have changed from before?

**Comment by kortewegdevries** [comment]
Hey kisak thanks for the quick response. Am I missing something? My folder structure is [this](https://imgur.com/KHcaOkE) there...

**Comment by kisak-valve** [comment]
I think that tells us that something is preventing `.../steam-runtime/setup.sh` from setting up the pinned library folders and using an incompatible set of libdbusmenu libraries is expected to cause the tray icon to not have a context menu.

Maybe try going to the steam-runtime folder in the firejail and see where `./setup.sh` has trouble. Something like `bash -x ./setup.sh` should show you exactly what the script is doing.

**Comment by kortewegdevries** [comment]
Yep that fixed the issue,there was nothing preventing the script from running.Manually running the script built the folders and thereby the menu. Thanks!
