### ISSUE TITLE
Steam client crashing, when trying to open GTA V's game Properties settings window.

### ISSUE THREAD

**Issue by perrsona1234** [ValveSoftware/steam-for-linux#7189]
#### Your system information

* Steam client version (build number or date): Jun 4 2020
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expected the Properties settings window for the GTA V game to show up, but instead it crashes the Steam client. 

Here is the output of the `steam -d` command: https://gist.github.com/perrsona1234/8521e909f858499c5dde6f00c9136b91

#### Steps for reproducing this issue:

1. Open Steam client.
2. Select GTA V.
3. Try to open the game's Properties settings window.
4. Crash.

**Comment by kisak-valve** [comment]
Hello @perrsona1234, do you use third party Proton builds? There's a strong chance you've encountered #6986.

**Comment by perrsona1234** [comment]
> Hello @perrsona1234, do you use third party Proton builds? There's a strong chance you've encountered #6986.

Yes, I do use custom builds. From Glorious Eggroll https://github.com/GloriousEggroll/proton-ge-custom

**Comment by perrsona1234** [comment]
I tried this solution https://github.com/ValveSoftware/steam-for-linux/issues/6986#issuecomment-604031549 and now everything works.

Should I close this issue?

**Comment by kisak-valve** [comment]
Thanks for checking, closing in favor of the older issue report.
