### ISSUE TITLE
Fedora is identified as 'unknown' system by Steam client

### ISSUE THREAD

**Issue by cold-distance** [ValveSoftware/steam-for-linux#7191]
#### Your system information

* Steam client version (build number or date): Jun 4 2020 from RPMFusion
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Hi, I don't know why, but in sometime the Steam client for Linux started to not recognize Fedora correctly. With Fedora 31 Workstation, the Steam client started to recognize correctly, but an update (I don't remember what version) introduced this little regression and that regression remains in a Fedora 32 Workstation fully updated.

I use EXT4 file system for the root and XFS for the home and I get the same error on my desktop and on my laptops, two computers with very different configurations (full-AMD Vs full-Intel), so I think the features of computers aren't important so far.

![Captura de pantalla de 2020-06-12 19-51-35](https://user-images.githubusercontent.com/43167050/84533197-ee150800-ace7-11ea-89cf-dc793491b252.png)

#### Steps for reproducing this issue:

1. Open the Steam client from Fedora 31 or 32, probably mixing an EXT4 root with a XFS home.
2. Go to System Information.
3. You will see 'Unknown' in the operating system field instead of "Fedora 32 (Workstation Edition)".

**Comment by pruebahola** [comment]
same issue than this
https://github.com/ValveSoftware/steam-for-linux/issues/5909

**Comment by byte1024** [comment]
> probably mixing an EXT4 root with a XFS home.

It would probably be the XFS as I run straight EXT4 and it shows up correctly unless some other customization causes it to get borked from standard.

Could be a Fedora issue technically as well depending on how one looks at it.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by cold-distance** [comment]
The problem can be solved with the `redhat-lsb-core` package. I think it a problem that could be solved by RPM Fusion setting that package as a strong dependence.

I close this as won't fix. I think it's not a Valve problem
