### ISSUE TITLE
proton versions appear as games in big picture mode

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/steam-for-linux#7192]
#### Your system information

```
Steam client application
Built: Jun 4 2020, at 05:51:01
Steam API: v020
Steam package versions: 1591251555
```

```
NVIDIA Driver Version: 440.82
```

Distribution: Fedora31
Opted into Steam client beta?: No
Have you checked for system updates: Yes

#### Please describe your issue in as much detail as possible:

Proton 3.16 and proton 5.0 appear in installed games in big picture more. They have no picture and clicking play results in "Error Failed to start game (invalid app config)."

#### Steps for reproducing this issue:

1. Start big picture mode session
2. Install some game with proton under Linux
3. Go into installed games

**Comment by kisak-valve** [comment]
Hello @abc-mikey, this is expected and normal for the "Installed" section. Proton is considered a tool instead of a game, and it's useful to have access to some of the options in Manage Tool.

**Comment by abc-mikey** [comment]
This is unexpected enough behaviour that I couldn't distinguish it from a bug. 

As a suggestion maybe disable the pay button to at least prevent the user getting an error.
