### ISSUE TITLE
Steam coredump

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#7195]
#### Your system information

* Steam client version (build number or date): Jun 4, 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I started Dota. I was in a party and we got to hero selection. After selection, Dota got stuck and I got an abandon. I restarted my system to find that to start Dota I Vulkan shaders had to be processed. I tried skipping that but the game was stuck and looking at logs, I found a dump.

```
[dknight@clown ~]$ coredumpctl dump steam
           PID: 991 (steam)
           UID: 1000 (dknight)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-06-14 00:37:43 IST (4min 28s ago)
  Command Line: /home/dknight/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/dknight/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (dknight)
       Boot ID: 6963c6ada6a04e81a3b37231c56fed3b
    Machine ID: f52d0eeb525f4cd584fe54d97e927133
      Hostname: clown.man.machine
       Storage: /var/lib/systemd/coredump/core.steam.1000.6963c6ada6a04e81a3b37231c56fed3b.991.1592075263000000000000.lz4
       Message: Process 991 (steam) of user 1000 dumped core.
                
                Stack trace of thread 1291:
                #0  0x00000000cc0c6669 n/a (n/a + 0x0)
                #1  0x00000000d49b82c0 n/a (/home/dknight/.local/share/Steam/ubuntu12_32/libtier0_s.so + 0x172c0)
Refusing to dump core to tty (use shell redirection or specify --output).

```
Adding minidumps here as well.
[zip.zip](https://github.com/ValveSoftware/steam-for-linux/files/4775257/zip.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by kisak-valve** [comment]
Closing pending feedback.
