### ISSUE TITLE
shader pre-caching:  background compilation for uininstalled games

### ISSUE THREAD

**Issue by GoTeamAnt** [ValveSoftware/steam-for-linux#7196]
With background processing of vulkan shaders enabled, shaders for unistalled games are also compiled.

In the settings window I could see that rocket league shaders were compiled even though I had uninstalled the game when they dumped the linux version.

System: Archlinux

**Comment by AwesamLinux** [comment]
:thinking: maybe this is the same/related to the issue I reported in #7148

**Comment by kisak-valve** [comment]
Hello @GoTeamAnt, per "Improved Shader Pre-Caching behavior around game uninstallation." in the [2020-12-31](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2919986982646109238) Steam client beta update, please opt into Steam's beta client and retest this issue.

**Comment by GoTeamAnt** [comment]
The shader cache directory for rocket league seems to be gone. (no /home/xxx/.local/share/Steam/steamapps/shadercache/252950)
When I enabled background compiling*  there was no indication that the rocket league shaders were compiled.

I did not install the beta client. 

*I have it disabled usually

**Comment by kisak-valve** [comment]
It's unclear from the last comment if that was a valid retest for the issue in the opening post. Closing pending feedback that this is still a current issue.

**Comment by matteoturini** [comment]
Shader background processing works OK. Just tested.

**Comment by matteoturini** [comment]
![image](https://user-images.githubusercontent.com/69425093/153729247-1fea72ca-92b3-4a7d-9041-e5a4b186f8a9.png)
