### ISSUE TITLE
Audio is glitching/poping/stutter in Big Picture Mode

### ISSUE THREAD

**Issue by m0sia** [ValveSoftware/steam-for-linux#72]
Even with the latest update of Steam I am experiencing sound stutter issue. 

Steps to reproduce:
Start Steam in Big Picture Mode and have the sound stutter during splash screen video. When I am tring to watch trailers the sound still glitch. 

In any other application(ex TF2) i don't have that issue.

Processor Information:
    Vendor:  GenuineIntel
    Speed: 3066 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-34-generic
    X Server vendor:  The X.Org Foundation
    X Server release:  11103000

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 430/PCIe/SSE2

```
Driver Version:  4.3.0 NVIDIA 310.14
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xde1
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 6.30" x 3.54"  (7.20" diag)
                                        16.0cm x 9.0cm  (18.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1023 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7985 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  52587 Mb
    Largest Free Hard Disk Block:  12895 Mb

Installed software:

Recent Failure Reports:
    Mon Dec 10 08:51:16 2012 GMT: file ''/tmp/dumps/assert_20121210145109_1.dmp'', upload yes: ''CrashID=bp-65792b44-f0e2-4b61-a4bc-1b0d52121210''

**Comment by moulei** [comment]
Now I no longer have any sound issues once Big Picture is running, again, I said; 'Once'...

When I click the Icon, just as it enters Big Picture I get a slight fuzzy crackle/pop sound, then the audio starts to play ok.

I turned down my system sound and sound in Steam, but I can still here the slight fuzzy crackle/pop...

I'm using Alsa on Slackware

**Comment by kisak-valve** [comment]
Closing as this appears to have been an issue with older pulseaudio.

If this is an issue with an up to date system and the `default-fragment-size-msec = 5` pulseaudio config does not help, then we can investigate further.
