### ISSUE TITLE
PowerA xbox one Controller is not detected

### ISSUE THREAD

**Issue by Nayr438** [ValveSoftware/steam-for-linux#7200]
#### Your system information

* Steam client version (build number or date): June 4 2020
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is unable to detect my PowerA xbox one Controller, games seem to be unable to see it as well.

lsusb -> Bus 001 Device 014: ID 24c6:543a BDA Xbox ONE Pro Ex controller
Is detected by KDE Input and appears fully functional

I have tried 
- using steam-native-runtime
- installing steamos-xpad-dkms
- `KERNEL=="hidraw*", ATTRS{idVendor}=="24c6", ATTRS{idProduct}=="543a", MODE="0660", TAG+="uaccess"`

Detects Microsoft xbox 360 controller just fine. 
I have used the PowerA xbox one controller in the past without issue, buts its been awhile.

#### Steps for reproducing this issue:

1. Connect PowerA xbox one controller
2. check steam big picture mode controller section
3. start game through steam and see it undetected

**Comment by 2talltech** [comment]
http://www.generalarcade.com/gamepadtool/

With a fresh install of Fedora 32 and Steam client (from repositories), I also had this issue (PowerA Pro Ex PS3 wired controller and PDP Rock Candy Nintendo Switch wired controller). Running the gamepad tool fixed it for me. I think it has something to do with how Steam is accessing SDL 2 gamepad mappings upon initial installation. The big picture controller configuration just would not detect anything. No udev configuration or xpaddrv is needed.

**Comment by Nayr438** [comment]
> http://www.generalarcade.com/gamepadtool/
> 
> With a fresh install of Fedora 32 and Steam client (from repositories), I also had this issue (PowerA Pro Ex PS3 wired controller and PDP Rock Candy Nintendo Switch wired controller). Running the gamepad tool fixed it for me. I think it has something to do with how Steam is accessing SDL 2 gamepad mappings upon initial installation. The big picture controller configuration just would not detect anything. No udev configuration or xpaddrv is needed.

Thank you, creating a mapping and setting a environmental variable fixed it. Oddly though instead of it pulling the profile in steam, it actually detects the controller itself now rather than pulling the profile name I set.

**Comment by kisak-valve** [comment]
Nice find, I think that means that SDL hasn't been taught about that controller yet. Can you share the button mapping you're using? Assigning a SDL dev.

**Comment by Nayr438** [comment]
This is what the gamepadtool generated
`SDL_GAMECONTROLLERCONFIG=03000000c62400003a54000001010000,PowerA XBox One Controller SDL2,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.0,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,`

**Comment by Nayr438** [comment]
Dpad down wasn't working with the above one. Here is a working one. I guess steam just doesn't pull the profile name, but still identifies it as a xbox one controller.

SDL_GAMECONTROLLERCONFIG=03000000c62400003a54000001010000,PowerA XBox One Controller SDL2,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.7,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,

**Comment by TTimo** [comment]
See https://github.com/ValveSoftware/steam-devices/pull/9 - install the latest udev rules in 1.0.0.63 or newer.

**Comment by Nayr438** [comment]
> See [ValveSoftware/steam-devices#9](https://github.com/ValveSoftware/steam-devices/pull/9) - install the latest udev rules in 1.0.0.63 or newer.

It didn't make a difference, I still need the SDL line above.

**Comment by TTimo** [comment]
https://github.com/ValveSoftware/steam-devices/issues/10

**Comment by Nayr438** [comment]
I don't personally get the error above.
I would like to however add that my controller is not in the steam udev list and is also wired.

`KERNEL=="hidraw*", ATTRS{idVendor}=="24c6", ATTRS{idProduct}=="543a", MODE="0660", TAG+="uaccess"`
This is however unneeded

**Comment by kisak-valve** [comment]
Hello @Nayr438, are you still experiencing this issue on an up to date system? I'm guessing that you still need a udev line for the controller.

**Comment by Nayr438** [comment]
I actually forgot about this, but I do still have that controller.
It's detected by steam and worked for a quick test run on GTA V without any additional configuration.
