### ISSUE TITLE
Steam taking a very long time to open

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#7203]
#### Your system information

* Steam client version (build number or date): June 15
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam has over the last 1-2 months started taking a ridiculous amount of time to actually appear after you try to load it. We're talking a good five minutes here.

The biggest wait time seems to be on CApplicationManagerPopulateThread, which appears to be taking almost 3 minutes by itself.

Loading Log: https://gist.github.com/LiamDawe/852eccfca1d6bebd031b1d99f4de2e7e

PC Info: https://gist.github.com/LiamDawe/4237a5b51bd05d3bc514646dec6d61d5

#### Steps for reproducing this issue:

1. Install a Steam
2. Have lots of games
3. Attempt to load steam
4. Go make a coffee

**Comment by flukejones** [comment]
Appears to be the same across both native install and flatpak install so far.

- Pop!_OS 20.04
- ASUS GX502 laptop with RTX2070

**Comment by kisak-valve** [comment]
Hello @LiamDawe, this issue is already being tracked at #7117. Closing in favor of the existing report.
