### ISSUE TITLE
Steam on screen keyboard has very l low opacity

### ISSUE THREAD

**Issue by different55** [ValveSoftware/steam-for-linux#7204]
#### Your system information

* Steam client version (build number or date): Jun 4, 2020
* Distribution (e.g. Ubuntu): affects Debian and a fresh install of Ubuntu, both on GNOME 3.36.2
* Opted into Steam client beta?: [Yes/No] On Debian, yes. On Ubuntu, no.
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When using the on screen keyboard with the Steam Controller, the keyboard's opacity is very low. It's impossible to use on bright or mixed screens. If you can get a black surface behind it, it looks normal though. No issues within Big Picture Mode.

#### Steps for reproducing this issue:

1. Plug in Steam Controller
2. Summon OSK with Steam+Select or any other binding

**Comment by stereosix** [comment]
I am also having this issue (on Arch Linux). Steam client Jun 4, 2020.

A crude workaround is to disable compositing (thereby disabling transparency), but then you lose all compositing.
If I have Picom/Compton running, the Steam Keyboard on desktop is barely visible on top of light backgrounds.

![keyboard](https://user-images.githubusercontent.com/2520788/86548965-3a7ced80-bf0c-11ea-9a00-01919378c877.png)

**Comment by Pixel-Meister** [comment]
I also ran into this issue on Ubuntu 20.04.

**Comment by blastermaster77** [comment]
same problem with ubuntu 20.04 , its too transparent on the desktop on bigpicture is fine.

**Comment by different55** [comment]
We all got Nvidia cards? Tried on my laptop that has Intel integrated graphics running the same software versions as my desktop in the first post and it's working properly.

**Comment by Plagman** [comment]
I can't seem to be able to repro this on Mesa either.

**Comment by kisak-valve** [comment]
Hello, per "Fixed a regression with transparent visual selection for SteamOS overlays and on-screen keyboard causing invalid rendering on NVIDIA configurations" in the [2020-08-05 steam client beta update](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2735326880599543430), please opt into Steam's beta client and retest.

**Comment by different55** [comment]
It's now back to being opaque; thanks for getting that patched up!

**Comment by blastermaster77** [comment]
yes its fixed now thanks a lot, now I can use steam desktop mode on my steam link!
