### ISSUE TITLE
Closing Update Window While Signed In Crashes Steam

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#7207]
#### Your system information

* Steam client version (build number or date): Jun 4, 2020 at 5:51:01
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Often when there's a Steam client update KDE Linux systems often don't get the window to appear properly and, if closing the window without manually managing to get it to display, Steam crashes with a 100% reproduction rate (regardless of the Linux OS, in my experience, and has been a longstanding issue). This isn't an easy issue to capture with a screenshot, so I apologize for not providing one for this.

-------------------

For what was expected:

KDE multi-window selecting (reffering to when one moves the mouse into a corner of the screen to view all windows, by default), the aforementioned update window should be visible, except it does not. And attempting to close said window from the taskbar instead causes the entire application to crash.

#### Steps for reproducing this issue:

1. Target the update window when the already signed in to the Steam client without left-clicking the window, by any means, in a KDE desktop environment.
2. Close the aforementioned window.
3. Watch Steam crash.

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue is already being tracked at #2685 / #7007 and is not a crash. Closing in favor of the existing issue report.
