### ISSUE TITLE
Steam Library Freezes When Minimizing and Re-Maximizing

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#7208]
#### Your system information

* Steam client version (build number or date): Jun 4, 2020 at 5:51:01
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Minimizing the Window in the Library menu on KDE systems (as far as I know) and it freezes up both the left game pane and the main one that was introduced in the new "visual" update that was released a while ago. I can't really name a consistency rate and it's easily fixed by moving to another menu and coming back, but it is a slight annoyance, regardless.

----------------------

What was expected:
Minimizing and maximizing the window shouldn't cause the window to misbehave.

What happens:
The main window contents can't be interacted with or appear to but at an abnormally slow pace.

#### Steps for reproducing this issue:

1. Move to the Library menu.
2. Minimize the maximize the window (even try several minutes apart, if it helps).
3. Notice that the left pane can't be selected or scrolled through, as is most likely the case with the main library window too. All other elements of the Steam client should work properly and switching tabs resolves the non-responsiveness.

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, are you still experiencing this issue on an up to date system?

**Comment by ThisNekoGuy** [comment]
At least in the beta branch (I use the beta branch now), this is no longer an issue

**Comment by kisak-valve** [comment]
Thanks for retesting, closing as fixed some time ago.

**Comment by Spartan322** [comment]
Started getting this as an issue.

**Comment by LynnV7777777** [comment]
I've also been getting this issue on a completely fresh Endeavor OS KDE Wayland install, minimizing the window causes it to freeze when you pull it back up, killing the webhelper process will force the app to restart and unfreeze.
