### ISSUE TITLE
Some of the display gets cut off from the bottom of the screen

### ISSUE THREAD

**Issue by sagnikseal** [ValveSoftware/steam-for-linux#7209]
#### Your system information

* Steam client version (build number or date): 1.0.0.61
* Distribution (e.g. Ubuntu): Pop OS 20.04
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I install CS GO on steam and when I launch it the game starts in a window and cannot to changed to full screen because the bottom of the window gets cut off from the screen so the go, apply or any other buttons at the bottom are not available. Please tell me what to do.

#### Steps for reproducing this issue:

1. Start steam
2. Launch CS : GO
3. Try to start a match but the go button is not visible.

**Comment by kisak-valve** [comment]
Hello @sagnikseal, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2004. Closing as a duplicate.
