### ISSUE TITLE
Remote Play from Ubuntu stuttering and flickering

### ISSUE THREAD

**Issue by gamerminstrel** [ValveSoftware/steam-for-linux#7210]
#### Your system information

* Steam client version (build number or date): Built June 15, 2020
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

What happened: I opened Steam Link on my Phone (Moto g6, Android 10) and connected to my PC. Steam Big Picture Mode took a while (up to 30 seconds) to load, and multiple times a second the screen would flicker black while navigating my Games library. When I loaded a game the flickering stopped, but was replaced with video stuttering/lag that was at about the same rate, indicating the underlying issue is still present.  This was replicable streaming from this PC to multiple other devices (Smart TV, Steam Link so far). I have verified it is not a network issue, as my Steam Link and smart TV are using physical ethernet connections to the router, same as my PC. 

This issue was not present from the same PC running Windows 10. 

#### Steps for reproducing this issue:
1: Attempt Remote Play from the Steam Client on Ubuntu (likely Linux in general) to any other device.

If any other information is needed, I would be happy to provide it.

**Comment by kisak-valve** [comment]
Hello @gamerminstrel, you've described the issue being tracked at #4351. Can verify you're using nVidia's proprietary driver and disabling `Allow Flipping` in the driver's opengl settings avoids the issue?

**Comment by gamerminstrel** [comment]
You're right, I disabled "Allow Flipping" in the nvidia driver settings and the flicker goes away almost entirely. Is this a bug in their driver, or is this still something that can be fixed on Valve's end?

**Comment by kisak-valve** [comment]
Thanks for confirming. Unfortunately I don't have any additional insight into this issue.

Closing in favor of #4351.
