### ISSUE TITLE
Hide Proton from Recent games

### ISSUE THREAD

**Issue by X6205** [ValveSoftware/steam-for-linux#7212]
#### Your system information

    Steam client version (build number or date): latest possible as of now
    Built: Jun 4 2020, at 05:51:01
    Steam API: v020
    Steam package versions: 1591251555
    Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Playing games in linux via Proton, Steam client takes Proton into account as another game and displays Proton in "Recent Games" shelf (on picture).

A partial workaround would be to hide Proton in game library, but this has unwanted behaviour. When Proton is hidden and i am downloading it on clean system, dowlnoad manager shows nothing in download queue. But network transfer rate shows that is something downloading at full speed. So hiding is not a good idea.

#### Steps for reproducing this issue:

1. Install some Windows game in linux via Proton
2. After downloading Proton, it will show up in Recent games 

Desired behaviour:

1./ Proton should be masked-out from these "shelfs" like "Recent Games"

![recent_games_proton](https://user-images.githubusercontent.com/14248415/85202578-a0138c00-b307-11ea-8422-80601b2d7c85.png)

**Comment by kisak-valve** [comment]
Hello @X6205, this issue is already being tracked at #6906. Closing as a duplicate.
