### ISSUE TITLE
Feature Request Native Dosbox Wrapper for MOM (Linux)

### ISSUE THREAD

**Issue by siyia2** [ValveSoftware/steam-for-linux#7214]
Hello, i would like to request a native dos-box wrapper for Master of Magic games, performance through proton+dosbox in Linux is abysmal and sound is crackling.

At the moment i launch the MOM games with:

`dosbox %command%`

in steam launch options and i have configured dosbox to automatically mount and launch MOM, but i sure hope sth better can be done? since dosbox works natively in Linux.

**Comment by kisak-valve** [comment]
Hello @siyia2, https://github.com/dreamer/boxtron covers this use case.

**Comment by siyia2** [comment]
Doesnt work because launcher for MoM is not a Dos program.
