### ISSUE TITLE
"PLAY" becomes grayed out "INSTALL" after removing/updating custom proton version

### ISSUE THREAD

**Issue by 7thfleet** [ValveSoftware/steam-for-linux#7216]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20200604.0
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

[More system information](https://gist.github.com/7thfleet/c360850a9fbf48f8f90745bd1790de19)

#### Please describe your issue in as much detail as possible:
When a proton distribution is removed from the filesystem, any games that use it have their green "PLAY" button changed to a grayed out "INSTALL" button.

This button cannot be clicked, and the game otherwise appears as uninstalled and uninstallable.

This issue can be fixed by checking and un-checking the "Force the use of a specific Steam Play compatibility tool". Upon doing this, the grayed button will switch back to the green play button. Of note: Before removing the proton distribution, this checkbox was checked and the custom distribution was selected.

An error message that the requested tool could not be found would be great. I encountered this issue after I updated my system, which upgraded proton-ge. It wasn't obvious what the problem was, particular because the grayed out button said "INSTALL" instead of "PLAY".

#### Steps for reproducing this issue:

1. Install a custom version/distribution of proton (I used glorious-eggroll)
2. Set a game to use that installed version
3. Remove the custom proton install from the filesystem.
4. Restart steam
5. Observe described issue

This might be  related to #6874

Please let me know if there is anything you'd like me to do to help.

**Comment by kisak-valve** [comment]
Hello @7thfleet, it's fair that Steam is not making the game available with an invalid config. I take it you also have `Enable Steam Play for all other titles` checkbox enabled, so Steam uses the global setting once the game-specific setting is removed.

The Steam client behavior in this scenario is already being tracked at #6501. This is just another way to reproduce the scenario.

Closing in favor of the older issue report.
