### ISSUE TITLE
Steam Shaders not downloading/processing

### ISSUE THREAD

**Issue by mikev190** [ValveSoftware/steam-for-linux#7218]
#### Your system information

* Steam client version (build number or date): Latest beta and tested on stable
* Distribution (e.g. Ubuntu): Arch 
* Opted into Steam client beta?: Yes 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam doesn't download any new shaders on a fresh install. I've tried beta and stable and I have 11 games installed and a max of 27mb of shaders. CSGO is even stuttering. I had a look at the logs and I keep seeing similar errors as what I've linked. The size doesn't increase when compiling shaders during gaming either. My GPU is a GTX 1080ti. This worked on a previous manjaro install on the same hardware.

Sample of shader logs:

][2020-06-23 15:50:18] Crawling complete, found 3 different buckets:
[2020-06-23 15:50:18] ae16204e55f02d25 / L2:33aa3fb87a15bfa5f1f7b7b4d8a4bae4: 101 shaders.
[2020-06-23 15:50:18] Done; 0 already registered, 0 succeeded, 101 failed.
[2020-06-23 15:50:18] Server requested 0 shaders; uploading is enabled.
[2020-06-23 15:50:18] b6b2286ed6ebf797 / L2:ad4b934e19c9451ee3bd46c449bff6c8: 1276 shaders.
[2020-06-23 15:50:19] Done; 0 already registered, 0 succeeded, 1276 failed.
[2020-06-23 15:50:19] Server requested 0 shaders; uploading is enabled.
[2020-06-23 15:50:19] Reading 3292 hit entries from cache file /home/tla/.local/share/Steam/userdata/10119912/config/shaderhitcache/SteamSwarm/VulkanPipelinesV4/1237970.
[2020-06-23 15:50:19] SteamSwarm / G7:VulkanPipelinesV4: 3170 shaders.
[2020-06-23 15:50:21] Done; 0 already registered, 0 succeeded, 3170 failed.
[2020-06-23 15:50:21] Server requested 0 shaders; uploading is enabled.

#### Steps for reproducing this issue:

1. Install Arch
2. Install Native Steam
3. Shaders don't precompile

**Comment by NikoBellicRU** [comment]
This also happends to me on pop os 20.04 with rx 570

**Comment by AngryPenguinPL** [comment]
Not sure if this the same issue but when I launch Dota2 I see popup windows with "processing Vulkan shaders" but without progress bar. Just like on this screen: 
![Screenshot_20200715_162639](https://user-images.githubusercontent.com/3121142/87566178-ea97e680-c6c2-11ea-8c63-510cf84afd97.png)

**Comment by NikoBellicRU** [comment]
> Not sure if this the same issue but when I launch Dota2 I see popup windows with "processing Vulkan shaders" but without progress bar.
> Do you have something similar? Is this a separate problem?
> 
> Just like on this screen:
> ![Screenshot_20200715_162639](https://user-images.githubusercontent.com/3121142/87566178-ea97e680-c6c2-11ea-8c63-510cf84afd97.png)

Yeah that also happends to me, idk what happebd but none of my games are prossesing shaders wich sucks cause its stuttering alot :/

**Comment by fightTone** [comment]
> > Not sure if this the same issue but when I launch Dota2 I see popup windows with "processing Vulkan shaders" but without progress bar.
> > Do you have something similar? Is this a separate problem?
> > Just like on this screen:
> > ![Screenshot_20200715_162639](https://user-images.githubusercontent.com/3121142/87566178-ea97e680-c6c2-11ea-8c63-510cf84afd97.png)
> 
> Yeah that also happends to me, idk what happend but none of my games are prossesing shaders wich sucks cause its stuttering alot :/

Same... Did u find a fix?

**Comment by kisak-valve** [comment]
Hello, per "Fixed a bug where Vulkan shader processing could sometimes get stuck" in the [2020-08-18](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2738705758017771491) Steam client beta update, please opt into Steam's beta client and retest.
