### ISSUE TITLE
Non-Steam game picker not escaping spaces properly

### ISSUE THREAD

**Issue by patrickm32** [ValveSoftware/steam-for-linux#7219]
#### Your system information

* Steam client version (build number or date): Jun 4 2020 (latest)
* Distribution (e.g. Ubuntu): Arch Linux (up to date as of 2020-06-23)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When picking a non-steam game file (.desktop or .exe, does not matter) that is located in a directory whose path contains one ore more spaces, the "target" and "start in" paths are cut off right before the space. My guess is that those space characters are somehow not escaped properly which leads to this weird behaviour.

#### Example:

Space in the full path:

![Folder with Space](https://user-images.githubusercontent.com/65464529/85457887-cc960500-b5a0-11ea-9931-da1c8a3bc19b.png)

As you can see, the "target" (second text box) and "start in" (third text box) strings are incomplete.

![Game with Space](https://user-images.githubusercontent.com/65464529/85457904-cef85f00-b5a0-11ea-9265-9eefde13fa18.png)

No spaces at all:

![Folder with no Space](https://user-images.githubusercontent.com/65464529/85458463-6fe71a00-b5a1-11ea-91f8-912c009a5e75.png)

As you can see, everything works like it should:

![Game with no Space](https://user-images.githubusercontent.com/65464529/85458494-7aa1af00-b5a1-11ea-9a93-5f6f3569f4a5.png)

#### Steps for reproducing this issue:

1. Add a non-steam game like described above
2. Enjoy

**Comment by kisak-valve** [comment]
Hello @patrickm32, this issue is already being tracked at #5220. Closing as a duplicate.
