### ISSUE TITLE
Taskbar Menu / Jumplist preferences are not working

### ISSUE THREAD

**Issue by frankc-valve** [ValveSoftware/steam-for-linux#722]
(Migrated from the forums: http://steamcommunity.com/app/221410/discussions/1/882965239897600944/)
Taskbar/jumplist settings doesn't change anything for unity launcher.

Open **Steam** and choose **Steam** | **Settings**
Click the **Interface** tab
Click the **Set Taskbar ...** button at the bottom of the dialog
Note that all settings are enabled but not all appear on the taskbar icon (e.g. **Exit Steam**)

It seems that these settings are being ignored by the Linux client.

**Comment by kisak-valve** [comment]
Closing as this appears to be fixed.
