### ISSUE TITLE
The "STOP" button should be able to kill processes

### ISSUE THREAD

**Issue by vityafx** [ValveSoftware/steam-for-linux#7220]
## Your system information

* Steam client version (build number or date): Jun 20 2020 at 00:01:08
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The STOP button should be able to send "kill -SIGKILL" to a process, without waiting for the graceful shutdown. Most of times, if a game hangs, the stop button is completely useless, and everytime I have to lookup a process in the process table and guess its name (like its not a "MortalKombat11.exe" but `MK.exe`) and kill about 5 processes manually entering the numbers.
If steam had had such an ability just via a single button, it would have been very much appreciated and useful.

#### Steps for reproducing this issue:

1. Try to run any game which hangs on your system. Perhaps, you may code a "while (true) {}" right in the main, add such a "game" into your steam library and run it via proton (or not via proton).
2. Wait for the "game" to run and hang.
3. Press the "STOP" button - it won't stop the process no matter how many times you press it, and the only possible way is to kill the processes yourself.

**Comment by kisak-valve** [comment]
Hello @vityafx, this issue is already being tracked at #6689. Closing in favor of the older issue report.
