### ISSUE TITLE
Actual wayland support (including real HiDPI support)

### ISSUE THREAD

**Issue by WhyNotHugo** [ValveSoftware/steam-for-linux#7224]
#### Your system information

* Steam client version (build number or date): `Startup - updater built Jun  4 2020 05:50:42`
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: (both options are the same)
* Have you checked for system updates?: Everything's up to date on my end

#### Please describe your issue in as much detail as possible:

Steam for some reason runs as a X11-only application, with no Wayland support. I'm not sure how Steam works, since both GTK3 and Qt5 have perfect Wayland support and applications usually run fine. Maybe you're just disabling it at build time?

Because of this, steam runs via XWayland. This presents several issues:
- Won't pick up the display scaling.
- Steam renders super blurry.

There's also a few quirks in how Steam's windows behave, but the main point is that almost everything renders very blurry.

I say almost since:
- Many games run fine natively.
- The initial update window renders perfectly, looks like that's Wayland native. :+1: 

#### Steps for reproducing this issue:

1. Install steam on Wayland (GNOME, KDE or sway. I'm using the latter).
1. Set display scaling to anything > 1 (I'm using 1.5).
1. Run Steam.

#### Extra notes

There's some similar-sounding but inherently different issues around. Most are about using HiDPI on X, where scaling is not entirely native. The issue in that case is that steam renders tiny.

On Wayland, scaling is supported natively, but X applications run via a compatibility-layer (XWayland) that doesn't support scaling (much like what happens on X, and just stretches the rendered window, which results in a lot of blurriness, although the size of all the elements is the expected one.

- #5460 Sounds similar, but, as per the comments, it seems users are still using GNOME on X, not Wayland.
- #6125 Sounds similar, but it's also running on X.
- #7020 Is also someone running via X.

**Comment by kisak-valve** [comment]
Hello @WhyNotHugo, this feature request is already being tracked at #4924 / #5908. Closing as a duplicate.

**Comment by WhyNotHugo** [comment]
#5908 is unrelated, that's Linux with Xorg, not Linux with Wayland.

Different environment, different issue and different symptoms. Likely fixing it is unrelated to fixing this.

**Comment by WhyNotHugo** [comment]
Will continue discussion on  #4924 though, thanks!
