### ISSUE TITLE
Steam won't finish starting

### ISSUE THREAD

**Issue by tremby** [ValveSoftware/steam-for-linux#7226]
#### Your system information

* Steam client version (build number or date): not sure how to get this (--help and --version don't do anything), but the package I have installed says it is version 1.0.0.62, and I downloaded this from the website yesterday.
* Distribution (e.g. Ubuntu): Ubuntu 18.04.4 LTS
* Opted into Steam client beta?: I think so, not certain though
* Have you checked for system updates?: Can't start the client so unsure whether it's fully updated.

#### Please describe your issue in as much detail as possible:

When I start Steam I get a "Connecting Steam account: [my username]..." window which stays forever. The system tray icon has appeared, and its menu opens when clicked, but the "Library" option, for example, does nothing.

If I run Steam from a console, I get some output, which I've put on Gist: https://gist.github.com/tremby/13878b74481a8a0faeffc7f62bd2956b

I have tried moving pinned_libs_* out of the way as I saw suggested in some other issues, but this didn't help.

I'm not sure if this is related to https://github.com/ValveSoftware/steam-for-linux/issues/7225 or https://github.com/ValveSoftware/steam-for-linux/issues/7223

Steam was working fine as recently as two days ago. With no reboot or package upgrades between, it was working and then not working in the same day. Since then I upgraded all packages and rebooted, and it's still not starting.

#### Steps for reproducing this issue:

1. Try to start Steam

**Comment by kisak-valve** [comment]
Hello @tremby, based on `appdatacache.cpp (697) : Assertion Failed: !package.missing_token()` in the log, maybe give https://github.com/ValveSoftware/steam-for-linux/issues/7177#issuecomment-643558754 a try?

**Comment by WHK102** [comment]
`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.` Your libgtk3 is broken or you use a non 64 bits libraries on 64 bits system. What is your operating system? and, what is the source of installation?.

**Comment by tremby** [comment]
Just followed @kisak-valve's suggestion and renamed .local/share/Steam/package. This did the trick -- when I ran it again, it downloaded and installed some things and then started successfully. Thanks!

@WHK102 I guess this means my system packages are OK. I installed Steam from the deb file given by the Steam website, via gdebi.

**Comment by uhoh-itsmaciek** [comment]
@kisak-valve fwiw, I just had the exact same issue and https://github.com/ValveSoftware/steam-for-linux/issues/7177#issuecomment-643558754 (specifically, deleting `~/.local/share/Steam/package`) fixed it for me.

**Comment by kisak-valve** [comment]
Hello, has anyone seen this issue in recent memory?

**Comment by yhojann-cl** [comment]
> Hello, has anyone seen this issue in recent memory?

Hello, I have changed my graphics card from nvidia gforce 1060 gt to a radeon and I have not had any problems again. It seems to be a mix of different issues related to proprietary drivers and mesa. With the amdgpu driver that comes natively incorporated in ubuntu 220.4.1 lts, it has never given any more problems.

**Comment by kisak-valve** [comment]
Closing as outdated.
