### ISSUE TITLE
steam no loonger start

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/steam-for-linux#7228]
#### Your system information

* Steam client version (build number or date):  last beta
* Distribution (e.g. Ubuntu): debian sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
try launch steam and have error
log https://gist.github.com/steamlinux/ac4adef47c7c3ac948715ff54e8f4048

p.s. I try tips from another thread, no help for me

**Comment by stephanlachnit** [comment]
Same problem here.

**Comment by kisak-valve** [comment]
Hello @steamlinux, @stephanlachnit, this issue is already being tracked at #7223. Closing in favor of the older issue report.
