### ISSUE TITLE
OpenGL context error after mesa-utils update.

### ISSUE THREAD

**Issue by bigmb** [ValveSoftware/steam-for-linux#7229]
#### Your system information

* Steam client version (build number or date): June 4th,2020
* Distribution (e.g. Ubuntu): Ubuntu 18.04.4 LTS
* Opted into Steam client beta?: [Yes/No] :  No
* Have you checked for system updates?: [Yes/No]: Yes

System information : 
Intel® Core™ i7-8750H CPU @ 2.20GHz × 12 
GeForce GTX 1060 
64- bit

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Dota2 not able to start. 
Error:  `Failed to create OpenGL context. OpenGL should atleast be 3.1.`   

It was running fine 2 days ago. But then yesterday steam won't start. Then updated the mesa-utils as mentioned in [https://github.com/ValveSoftware/steam-for-linux/issues/7225] and steam started to work. 

Now shows the error or OpenGL context. 
Ran the glxinfo |gerp Open :

```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 19.2.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

#### Steps for reproducing this issue:

1. Open Steam.
2. Try to run dota2.

**Comment by kisak-valve** [comment]
Hello @bigmb, llvmpipe is mesa's faster cpu renderer. The fact that glxinfo is using it means that your system isn't configured properly to use either gpus.

**Comment by bigmb** [comment]
Just had to reinstall the Nvidia drivers and them to primary again.
Issue solved. Thanks.
