### ISSUE TITLE
Controller not working anymore in games

### ISSUE THREAD

**Issue by phkb01** [ValveSoftware/steam-for-linux#7235]
#### Your system information

* Steam client version (build number or date): June 4 2020, 05:51:20
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
My controller does not work in games anymore, but it used to. It's been like two months since I played but back then it was working. Games I tried, that currently don't work but used to:
- Ori and the blind forest (261570)
- Life is strange 1 (319630)

The controller (still) works in big picture mode, and is detected in the controller settings.

The controller also works in non-steam games.

#### Things I tried:

1. Changing the per-game controller mode (force on/force off).

Previously "force off" was required for Ori, so I figured it could have an impact. However, none of the setting values worked.

2. Deactivating the xbox mode in the controller settings.

It used to fix some things in the past so I tried it, to no avail.

#### Controller info:

I'm using a standard Gamecube controller, connected with an official Nintendo adapter, with this [kernel driver](https://patchwork.kernel.org/project/linux-input/list/?series=286281).

**Comment by phkb01** [comment]
I solved the issue. I had to enable haptic support for sdl2.

**Comment by kabouterPop** [comment]
Hello, I have a similar problem. How do you enable haptic support for sdl2?
Thanks

**Comment by phkb01** [comment]
If you're using gentoo, you should know how to enable it. If not, you probably have it enabled already.
