### ISSUE TITLE
Crash on Nvidia equipment after changing drivers, An X Error occurred X Error of failed request:  BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by Goodgun123456789** [ValveSoftware/steam-for-linux#7236]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.64
* Distribution (e.g. Ubuntu): Linux Mint 19.3 Tricia x86_64
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Crash on booting with the following error whilst using Nvidia products and after attempting to upgrade drivers.  
#### Steps for reproducing this issue:
1. Install Nvidia CUDA drivers the uninstall them. 
2. Later install Nvidia 440.95.01 (attempted with 430s as well) drivers whilst using GeForce GTX 1050 Ti.  Nvidia claims the drivers are compatible with this hardware.
3. Attempt to open steam and wait for crash.

console output log attached below, any and all input is helpful in case of PEBKAC:
https://gist.github.com/Goodgun123456789/9d9086ea3e452c62fef9fc59675609ad

**Comment by kisak-valve** [comment]
Hello @Goodgun123456789, nVidia's CUDA PPA packaging does not provide 32 bit userspace support. This is an issue that can only be resolved on nVidia's side.

Please see #5778 for alternate solutions. Closing as a duplicate.
