### ISSUE TITLE
Sometimes Steam stop be detected with other Steam client

### ISSUE THREAD

**Issue by kadogo** [ValveSoftware/steam-for-linux#7237]
#### Your system information

* Steam client version (build number or date): Beta (I will add the version when I go back home)
* Distribution (e.g. Ubuntu): Debian Buster
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
Sometimes using Steam Link on Android my desktop start to be unavailable to Steam Link.

Today I played a game with Remote Play Anywhere and I tried lunching a Non-Steam game but wasn't working (but I think the game was launched but it didn't connect, it's maybe another issue). I tried to use Steam Link to see what happen and launching another install of another game because I couldn't install it from my laptop (by stream).

At my second attempt with the Steam Link my desktop started to be unavaiable and I lost connection.

#### Steps for reproducing this issue:

1. Using Steam Link (I think) by launching a game, closing the Steam Link app, trying to connect again ...
2. It will sometimes refuse to connect
3. The distant computer it's see as offline

If needed I can retrieve information when I go back at my home.

Have a nice day.

**Comment by kadogo** [comment]
@kisak-valve @slouken  I'm back home, which log could be usefull before I restart Steam?

**Comment by kadogo** [comment]
@kisak-valve @slouken Today I had something similar but it look like Steam completed crashed and exit (it's not more running in my terminal).

It's from few hours ago, so if the logs can be usefull let me know what you need. I'm guessing that it happend because I tried to play a game through Steam Link on Android.

**Comment by kisak-valve** [comment]
Hello @kadogo, are you still experiencing this issue on an up to date system?

**Comment by kadogo** [comment]
Hello @kisak-valve 

To be honest, with the Steamdeck I don't really play anymore on my other computer or with my phone remotely.
My computer at that time had a "weird" configuration too so everything together could be related.

I think it's safe to close the issue and open it later if there is a new problem. But based that I was the only one with the issue, I think it would be alright.

**Comment by kisak-valve** [comment]
Closing per the last comment.
