### ISSUE TITLE
All Steam Controllers suddenly working strangely on Linux, both fine on Windows

### ISSUE THREAD

**Issue by kabouterPop** [ValveSoftware/steam-for-linux#7239]
#### Your system information

* Steam client version (build number or date):  Build date June 4 2020, Steam API v020, package: 1591251555
* Distribution (e.g. Ubuntu):  Ubuntu 20.02 64-bit 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Two steam controllers work perfectly on all games in my Windows install. On Ubuntu 20.04 working in the morning (June 27) and then in the evening the configurations seemed to have gone berserk. In the controller config all the buttons and controls check out fine but are not usable in new games and old ones where they had been working perfectly. The only events in between that I can recall: replacing the batteries with freshly charged ones, and playing Kerbal. Earlier I had installed Overcooked2 and both controllers worked perfectly. Later, no reboot or update, they were not recognized and the Game switched from giving me menu options with controller buttons to menu options with keyboard selections. Games for which we have many hours on also no longer work on this system. I have tried all permutations of controller settings (xbox, ps2, etc...) and I have tried using per-game configs but they do not seem to apply when selected, as in: there is no effect. I also cannot get the steam overlay from the button during gameplay. It's really weird. Can I somehow remove and reinstall the controllers? I'm at a loss of what to try next. 

Regarding the similar experinces in two contemporary posts
1. [Controller not working anymore in games #7235](https://github.com/ValveSoftware/steam-for-linux/issues/7235)
--OP solved the issue by enabling haptic support for sdl2.   I have no idea how to do this, so can't comment if this solves it.

2. [Steam Controller works in Desktop/Big Picture but not in-game [regression from libwacom 1.4] #7230](https://github.com/ValveSoftware/steam-for-linux/issues/7230)
--OP reports  upgdate to libwacom 1.4 caused problems, was fixed in an update
My system is on 1.3 and Synaptic thinks that is the most current version.  Not sure what to say about that.

Thanks for any advice! 

#### Steps for reproducing this issue:

1.  Open Steam
2.  Launch game
3.  Fail to control game

**Comment by kisak-valve** [comment]
Hello @kabouterPop, are you still experiencing this issue on an up to date system?

**Comment by kabouterPop** [comment]
Hello @kisak-valve , I haven't tried in a long time. I can test this weekend.

**Comment by kabouterPop** [comment]
Hello, the controller is working as expected on the up-to-date system. Thanks for following up.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
