### ISSUE TITLE
Flatpak steam doesn't generate run files with the PROTON_DUMP_DEBUG_COMMANDS=1 command

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/steam-for-linux#7240]
#### Your system information

* Steam client version (build number or date): June 4 2020 05:51:01
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

Normally PROTON_DUMP_DEBUG_COMMANDS=1 will generate a run under /tmp/proton_$ file when the game is run.

under flatpak version of steam this fails. I searched the entire computer, it cropped up nowhere.

#### Steps for reproducing this issue:

1. install flatpak
2. install steam
3. add PROTON_DUMP_DEBUG_COMMANDS=1 as a run parameter to one game
4. run game

**Comment by kisak-valve** [comment]
Hello @tatsujb, this isn't a Steam client issue, you may have luck mentioning this at https://github.com/flathub/com.valvesoftware.Steam/issues.
