### ISSUE TITLE
Website issues of the Half-Life franchise

### ISSUE THREAD

**Issue by jqadev** [ValveSoftware/steam-for-linux#7248]
## Please describe your issue in as much detail as possible:
I noticed the following issues on the website https://store.steampowered.com/franchise/Half-Life:
1. `HALF-LIFE: ALYX` doesn't have SteamOS/Linux icon
![image](https://user-images.githubusercontent.com/20422423/86712752-a26f2900-c01d-11ea-8d00-9ebb3d4bbadc.png)
2. The quote on the above screenshot is in front of the green field.
3. The quote on the below screenshot is behind the green field.
![image](https://user-images.githubusercontent.com/20422423/86713212-21fcf800-c01e-11ea-977a-b0f2ddbe06bb.png)

@kisak-valve what do you think about replacing SteamOS icon with the penguin one on the list of supported operating systems by a game like in GOG?
Here is my suggestion from 1,5 year ago without any answer https://github.com/ValveSoftware/steam-for-linux/issues/5633#issuecomment-455779818

**Comment by kisak-valve** [comment]
Hello @jqadev, are you still experiencing this issue on an up to date system?

**Comment by jqadev** [comment]
Hello @kisak-valve, this issue doesn't exist anymore.
