### ISSUE TITLE
Shader Pre-Caching Fails preventing games from starting

### ISSUE THREAD

**Issue by ronoverdrive** [ValveSoftware/steam-for-linux#7252]
#### Your system information

* Steam client version (build number or date): July 8 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
system info: https://gist.github.com/ronoverdrive/124d142e371de2d71941f52df74df950

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Shader Pre-Caching should compile and/or download a shader cache. Instead it does nothing when background processing is enabled and crashes when Fossilize attempts to load with the following error:

`Inconsistency detected by ld.so: dl-minimal.c: 126: realloc: Assertion `ptr == alloc_last_block' failed!`

Attempting to force shader compilation via the console with the shader_build command does nothing but create the cache directories. I've attempted both Stable and Beta builds of Steam, both runtime enabled and disabled, a reset with --reset, and completely clearing ~/.steam and ~/.local/share/Steam. Only thing I can do is Disable Shader Pre-Caching to allow games to run.

#### Steps for reproducing this issue:

1. Turn on Precaching
2. Launch any game that uses Vulkan or DXVK
3.

**Comment by darksaboteur** [comment]
I am also experiencing this same issue and can confirm that Disabling Shader Pre-Caching in the Steam client fixed the issue.
I am on Fedora 32 using Steam beta July 8 2020.

**Comment by sinatosk** [comment]
I think I too experiencing this... everything was working fine yesterday, today I start steam after updating mesa drivers, no games would start

I downgraded to the previous drivers, no games would start

I disabled steam pre-cache and no games would start

I deleted the cache inside "~/.local/share/Steam/steamapps/shadercache/" and no games would start

I enabled shader pre-cache and none of the shader cache is downloading and compiling is stuck at 0%

I've tried this with both stable and beta steam

**Comment by frostworx** [comment]
I've seen the same error earlier today while "debugging" SteamVR fail. Any chance this is related here as well?:

```
fyi: at least on arch linux
vulkan-icd-loader-1.2.146-1 also makes SteamVR fail with Error 307
downgrading to
vulkan-icd-loader-1.2.145-1 fixes the problem!
```

https://github.com/ValveSoftware/SteamVR-for-Linux/issues/355#issuecomment-658085677

**Comment by frostworx** [comment]
yes, this looks related indeed:
Tried to start the 32bit game Gods Remastered (628720) which failed.
After downgrading lib32-vulkan-icd-loader-1.2.146-1 to lib32-vulkan-icd-loader-1.2.145-1 the game started normally!

**Comment by kattjevfel** [comment]
I just got hit by this issue, downgrading "fixed" it, but I guess I'll just have to delete the cache folder.

**Comment by frostworx** [comment]
thanks for confirmation!

**Comment by sinatosk** [comment]
> I've seen the same error earlier today while "debugging" SteamVR fail. Any chance this is related here as well?:
> 
> ```
> fyi: at least on arch linux
> vulkan-icd-loader-1.2.146-1 also makes SteamVR fail with Error 307
> downgrading to
> vulkan-icd-loader-1.2.145-1 fixes the problem!
> ```
> 
> [ValveSoftware/SteamVR-for-Linux#355 (comment)](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/355#issuecomment-658085677)

Yeah I was just browsing [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3272) and was about to reply back here to say this

**Comment by frostworx** [comment]
looks like this is really arch linux related, so I opened a bug here:
https://bugs.archlinux.org/task/67277

**Comment by kattjevfel** [comment]
> looks like this is really arch linux related, so I opened a bug here:
> https://bugs.archlinux.org/task/67277

This'll happen to any system that upgrade vulkan-icd-loader I'd imagine.

**Comment by frostworx** [comment]
> This'll happen to any system that upgrade vulkan-icd-loader I'd imagine.

arch build options don't look very experimental, so this is likely, anyway most bug reports come from arch currently.

**Comment by lordheavy** [comment]
https://github.com/KhronosGroup/Vulkan-Loader/issues/433

**Comment by ronoverdrive** [comment]
Confirmed problem with 1.2.146. 1.2.147 has it fixed. Either downgrade to 1.2.145 and wait for Arch to update their repo or use Tk-Glitch's PKGBUILD script to upgrade to 1.2.147.
