### ISSUE TITLE
CSGO not launching in Trusted Launch mode by default

### ISSUE THREAD

**Issue by ipkpjersi** [ValveSoftware/steam-for-linux#7255]
#### Your system information

* Steam client version (build number or date): Built: Jul 8 2020, at 23:11:02
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I launch CSGO on Ubuntu 18.04, and I run the command "trusted_launch_info" it says "CS:GO was not launched in Trusted Launch mode" even though my launch options are empty, I am not using the "-untrusted" launch option, and trusted launch should be enabled by default?

#### Steps for reproducing this issue:

1. Launch Steam client on Ubuntu 18.04
2. Launch CSGO
3. Type the command "trusted_launch_info" 

Here are my launch options, again they are empty:
![empty_launch_options](https://user-images.githubusercontent.com/33754783/87156173-42c98580-c28a-11ea-8c60-30afc505ca82.png)

Here is a screenshot of the bug:
![not_trusted_launch](https://user-images.githubusercontent.com/33754783/87156197-4ceb8400-c28a-11ea-8f89-e51e2bc82c96.png)

It does seem extremely weird to report a game bug on the Steam client issue tracker, but I was directed here by Steam support so here I am.

**Comment by kisak-valve** [comment]
Hello @ipkpjersi, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2482. Closing as a duplicate.
