### ISSUE TITLE
No options to disable Steam HUD for Non-Steam Game Shortcuts

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/steam-for-linux#7259]
The only option to disable the steam overlay is the global settings option.

I don't think any extra explanation is needed for this, it exists in all versions of steam at present. 

Give us a Tick Box that says "Enable the Steam Overlay while in-game"  for non-steam added shortcuts (which still have the original shortcut creation issue btw).

**Comment by kisak-valve** [comment]
Hello @jarrard, this issue is already being tracked at #2804. Closing as a duplicate.
