### ISSUE TITLE
Impossible to bring up Dota 2 through the taskbar in KDE all of a sudden (compositor affected?)

### ISSUE THREAD

**Issue by Captain-Rage** [ValveSoftware/steam-for-linux#7260]
#### Your system information

* Steam client version (build number or date): 
Built: Jul 8 2020, at 23:11:02
Steam API: v020
Steam package versions: 1594252496
* Distribution (e.g. Ubuntu): 
"Arch Linux" (64 bit)"
    Kernel Name:  Linux
    Kernel Version:  5.7.7-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20200604.0
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes (2020-07-12)

#### Please describe your issue in as much detail as possible:
When using KDE and Plasma, suddenly one recent day, bringing up Dota 2 by clicking on the taskbar stopped working along with the compositor while Dota 2 is running. Starting the game works fine, but when alt-tabbing and losing focus of the game, it is no longer possible to click on the Dota 2 icon on the panel to bring it back! It will only flash for a split second and the desktop remains visible. Also, the compositor seems knocked-out while Dota 2 is running (using compositor effects start working again once I quit the game). One strange thing that appeared together with this issue is that after queuing a game and seeing the "Your Game Is Ready" the game sometimes gets minimized when pressing "Accept".

This is very strange, since everything related to Dota 2 and Steam in KDE used to work flawlessly in the past few months and it was possible to bring up the game via the taskbar like any other program, but now something has gone awry (unfortunately I did not note down exactly when this problem started; perhaps over a week ago, after a system update and / or Steam update?).

If anybody else is experiencing a similar problem with Dota 2, or KDE, it would be nice to know. Thank you.

#### Steps for reproducing this issue:

1. Start Dota 2
2. Alt-tab to any other window
3. Now it is simply impossible to click on the icon on the panel to bring up the game again (regaining focus by alt-tabbing still works, however)

**Comment by kisak-valve** [comment]
Hello @Captain-Rage, it's fairly common for some desktop environments to disable their compositor whiles fullscreen games are running to increase performance. You've described a desktop environment bug that should be reported to the KDE devs.

**Comment by olekolek1000** [comment]
This happens only on KDE with nVidia graphics. Taskbar freezes (including date & time widget) when you change your compositor mode. Try restarting plasmashell by typing "plasmashell --replace"

**Comment by Captain-Rage** [comment]
Thank you for the swift replies! Since you say that KDE might be the culprit I have filed a bug report: https://bugs.kde.org/show_bug.cgi?id=424223.
@olekolek1000 Strange, since the graphics card in question is an AMD Sapphire Radeon RX 580 and the drivers are the open source AMDGPU ones. I might try your suggestion. Thanks for the suggestion! This feels like a wonky regression bug, though. I will post here if anything new comes up.

**Comment by AngryPenguinPL** [comment]
Hi.
I have the same problem. Linux OpenMandriva Cooker, KDE Plasma 5.19.3, Qt 5.15.0. GPU: Radeon RX580, Mesa 20.1.

> Hello @Captain-Rage, it's fairly common for some desktop environments to disable their compositor whiles fullscreen games are running to increase performance. You've described a desktop environment bug that should be reported to the KDE devs.

But I'm sure Dota worked well about a month ago. I could click on the panel taskbar and the game was restored. It doesn't work now. Other games work fine so I'm not sure if it's the compositor's fault.
BTW. in KDE when launching fullscreen app, compositor is disabled.

**Comment by Captain-Rage** [comment]
Yeah, sounds exactly like the issue here. Only Dota 2 shows this behavior, and it started about a month ago. Other programs and games are behaving normally and can be brought up by clicking on the panel.

**Comment by nikerrr** [comment]
I had the same issue with Dota, fixed it by unchecking "Desktop-friendly fullscreen minimizes of focus loss" in Dota video settings.

**Comment by AngryPenguinPL** [comment]
> I had the same issue with Dota, fixed it by unchecking "Desktop-friendly fullscreen minimizes of focus loss" in Dota video settings.

Good find. I confirm that it works but this is still just workaround. So we're still waiting for the correct fix from Valve

**Comment by Captain-Rage** [comment]
It seems to have been a KDE and Plasma issue after all. As of 5.19.4 it works to bring up Dota 2 by clicking on the panel:
https://bugs.kde.org/show_bug.cgi?id=424223
