### ISSUE TITLE
Can't enable GloriousEggroll custom Proton (after Steam restarts it is disabled)

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/steam-for-linux#7262]
#### Your system information

* Steam client version (build number or date): July 8 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Can't pertinently enable a non-default proton, such as glorious eggroll.

#### Steps for reproducing this issue:

1. Install any of the latest version of glorious eggroll to .steam/root/compatabilitytools.d
2. Steam > Settings > Steam Play > Advanced > Check "Enable Steam Play for all titles", click on "Run other titles with" select an Eggroll version, click "OK"
3. Go back in Steam after it restarts and go back into Steam Play to see it disabled

![Screenshot from 2020-07-13 18-24-53](https://user-images.githubusercontent.com/19944656/87371637-a4178000-c53a-11ea-9092-cd1be5898a41.png)

**Comment by kisak-valve** [comment]
Hello @romulasry, this issue is already being tracked at #6043. Closing as a duplicate.
