### ISSUE TITLE
Family Share Game Not Appearing

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#7263]
#### Your system information

* Steam client version (build number or date): July 8 2020, at 23:11:02
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Bought a game bundle for a friend who's family sharing on my system and one of the game's refuses to show up in the available games list for whatever reason.

Steam support just pointed me in this direction just because I'm on Manjaro and not Ubuntu.

#### Steps for reproducing this issue:

1. Friend received game bundle
2. They accepted the gift
3. One of the games did not appear on my end, regardless of attempts to refresh it

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, which game are you seeing this issue with? Most, but not all games are available via Family Share.

**Comment by ThisNekoGuy** [comment]
@kisak-valve Resident Evil 0

**Comment by kisak-valve** [comment]
Thanks, `exfgls` = yes in https://steamdb.info/app/339340/info/ indicates this is one of the games that is not available via Family Share.

Looks like it's due to [CAPCOM's EULA](https://store.steampowered.com/eula/339340_eula_0), specifically
```
B: The user agrees not to:

(a)	assign, transfer, lend or grant any third party the right to, or copy of the Program by any means.
```
