### ISSUE TITLE
No confirmation dialog before unchecking "Force the use of a specific Steam Play compatibility tool", unchecking it immediately removes game files from hard drive and requires re-download

### ISSUE THREAD

**Issue by ZakMcKrack3n** [ValveSoftware/steam-for-linux#7265]
#### Your system information

* Steam client version (build number or date): Jul 8 2020 / 23:11:02
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
When unchecking "Force the use of a specific Steam Play compatibility tool" all game files are being deleted without confirmation , if this happens by accident (proximity to proton version dropdown!) this means all game files have to be redownloaded again.

It would be great if this action would be in line with the confirmation dialogue when uninstalling a game, the behaviour now seems unintentional or like a side effect.

If this happens multiple times some GB of data are wasted (for me this meant at least 120GB of games redownloaded by accident accumulated in the past), if this happens only to 1000 people you can do the math for bandwith wasted on this occasion.

#### Steps for reproducing this issue:
Enable "Force the use of a specific Steam Play compatibility tool" for a game in the library and install it, wait until the game is downloaded.
Unchecking the box, this equals right klick on game and choosing "uninstall" without any confirmation dialogue and the game files are gone now.

**Comment by kisak-valve** [comment]
Hello @ZakMcKrack3n, this issue is already being tracked at #5901. Closing as a duplicate.

**Comment by ZakMcKrack3n** [comment]
Thx, hard to keep track for duplicates without knowing what to search for !
