### ISSUE TITLE
Connection to Steam Link does not happen / Game does not appear

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/steam-for-linux#7270]
#### Your system information

* Steam client version (1.0.0.64): 
* Distribution (KaOS): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

I start different Games (Witcher 3, Shadow of Tomb Raider) on my Steam on Linux and the game starts, according to the task manager, while it never appears on any screen. 

#### Steps for reproducing this issue:

1. Launch Steam Link. 
2. Start a game. 
3. See nothing happens. 

Note: I see the desktop of my computer on the phone. 
Phone is a RealmeX. 

Thanks

**Comment by kisak-valve** [comment]
Hello @ShalokShalom, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
