### ISSUE TITLE
Processing Vulkan Shaders indefinitely

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/steam-for-linux#7271]
#### Your system information

* Steam client version
![Screenshot_20200718_114604](https://user-images.githubusercontent.com/6344099/87849860-4a250a80-c8ec-11ea-91a3-ea47cc8dea9a.png)
* Distribution (KaOS on Flatpak): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

![Screenshot_20200718_114405](https://user-images.githubusercontent.com/6344099/87849891-750f5e80-c8ec-11ea-9c29-81d1690b21a2.png)

When I click "SKIP" the game starts. 

I am on a RX 480 
X.Org 1.20.8
Mesa 20.0.8

**Comment by kisak-valve** [comment]
Hello @ShalokShalom, you can check if shader pre-caching is actually stuck at `Steam` -> `Settings` -> `Shader Pre-Caching`. If Steam is warming the shader cache for a game, it'll have `Processing <game name>... (percentage)` just under the `Allow background processing of Vulkan shaders` checkbox. Alternatively, you could monitor `<steam dir>/logs/shader_log.txt`.

Some games have a substantial amount of shaders and shader variations, and can take a significant amount of time to process. For what you've described, there isn't enough information to indicate an issue.

**Comment by ShalokShalom** [comment]
It has taken a few seconds before and takes an infinite time - hence the title - now.

**Comment by ShalokShalom** [comment]
Like that since 10 minutes: 

![Screenshot_20200718_131756](https://user-images.githubusercontent.com/6344099/87851444-23210580-c8f9-11ea-87a2-f4b6ac3edea1.png)

**Comment by ShalokShalom** [comment]
It seems like I had to reboot after the Flatpak had been updated.
