### ISSUE TITLE
"Stream Launch Failed" dialog displays invisible when disconnected while screen locked

### ISSUE THREAD

**Issue by theit8514** [ValveSoftware/steam-for-linux#7274]
#### Your system information

* Steam client version (build number or date): Jul 16 2020, at 22:56:06
* Distribution (e.g. Ubuntu): Pop_OS! 20.04 (based on Ubuntu 20.04), using XFCE desktop
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After a recent upgrade to Pop_OS! 20.04, Steam streaming errors out after the lock screen is displayed. An error window pops up on the screen but it is invisible. I can select this window with xprop, which displays this message:
```
$ xprop
WM_NAME(UTF8_STRING) = "Stream Launch Failed"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_TRANSIENT_FOR(WINDOW): window id # 0x5400005
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MENU, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_CLASS(STRING) = "Steam", "Steam"
```

#### Steps for reproducing this issue:

1. Open Steam on Pop_OS! 20.04 and start Remote Play with another machine.
2. Lock the client machine and wait.
3. Unlock the computer and check Steam. When the issue occurs, clicking on the Steam window will 'ding' as if a dialog is open, but no dialog is visible.
4. Hitting escape or clicking the invisible close button on the dialog closes it.

**Comment by kisak-valve** [comment]
Hello @theit8514, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
