### ISSUE TITLE
Problema no Shaders 

### ISSUE THREAD

**Issue by MicaelDosSantoss** [ValveSoftware/steam-for-linux#7275]
Ola , o problema que estou enfrentando e que todos os meus jogos da STEAM estão com cores estranha nas maiorias das vezes amarelo , azul é vermelho e não consigo resolver

---
Google translate:
Hello, the problem I'm facing and that all my steam games are with strange colors most of the time yellow, blue is red and I can't solve

**Comment by kisak-valve** [comment]
Hello @MicaelDosSantoss, are you still experiencing this issue on an up to date system? In general, this reads like an issue that needed to be evaluated by your video driver vendor.

**Comment by kisak-valve** [comment]
Closing pending feedback.
