### ISSUE TITLE
locale LANG=en_IE.utf8 = insta crash

### ISSUE THREAD

**Issue by icf20** [ValveSoftware/steam-for-linux#7276]
```
locale                               
LANG=en_IE.utf8
LC_CTYPE="en_IE.utf8"
```

```
Steam client's requirements are satisfied
/home/user/.local/share/Steam/ubuntu12_32/steam
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
```

**Comment by kisak-valve** [comment]
Hello @icf20, Steam expects for `en_US.UTF-8` to be available on the system, even if it's not set as the default.

Please check if `en_US.utf8` is part of the output of `locale -a` and if it isn't, uncomment or add an `en_US.UTF-8 UTF-8` line to `/etc/locale.gen` and run `locale-gen` as root to regenerate the system-wide locales.

**Comment by icf20** [comment]
sorry, i totally forgot about this 😓
