### ISSUE TITLE
Steam crashed so Dota got stuck and I am in low priority

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#7279]
#### Your system information

* Steam client version (build number or date): Jul 10
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I was in the middle of a game. In the background, steam had crashed and my game got stuck. So, now, I am in low priority.

Attached is the crash dump.
[lp.zip](https://github.com/ValveSoftware/steam-for-linux/files/4949702/lp.zip)

```
[dknight@clown ~]$ coredumpctl dump steam
           PID: 925 (steam)
           UID: 1000 (dknight)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2020-07-21 01:08:36 IST (5min ago)
  Command Line: /home/dknight/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/dknight/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (dknight)
       Boot ID: f6c7e6f8acd2443583d0eae242bf8775
    Machine ID: f52d0eeb525f4cd584fe54d97e927133
      Hostname: clown.man.machine
       Storage: /var/lib/systemd/coredump/core.steam.1000.f6c7e6f8acd2443583d0eae242bf8775.925.1595273916000000000000.lz4
       Message: Process 925 (steam) of user 1000 dumped core.
                
                Stack trace of thread 1299:
                #0  0x00000000da671180 n/a (n/a + 0x0)
                #1  0x00000000da671eb7 n/a (n/a + 0x0)
                #2  0x00000000d28097a5 n/a (/home/dknight/.local/share/Steam/ubuntu12_32/steamservice.so + 0x687a5)
                #3  0x00000000e1100610 n/a (n/a + 0x0)
```

#### Special request:
1. Own the problem of me not being able to join the game and remove my low priority ban.
2. When an issue is fixed, close the ticket. Also, if the issue is the responsibility of any other third party like distro etc. clearly state the same after analysis.

**Comment by mscalindt** [comment]
I have the same issue and I'm also using Arch Linux and latest Steam client.

**Comment by alihakki** [comment]
i have the same problem.

> 4/11/21 8:46 PM	systemd-coredump	Process 11801 (steam) of user 1000 dumped core.
> 
> Stack trace of thread 12591:
> #0  0x00000000e885107d n/a (n/a + 0x0)
> #1  0x00000000e8851eb7 n/a (n/a + 0x0)
> #2  0x00000000cc0d6655 n/a (/home/alihakki/.local/share/Steam/ubuntu12_32/steamservice.so + 0x3b655)
>

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by mscalindt** [comment]
I wish I could report, but.... the last major ("Dead Reckoning") game update just totally broke native Wayland support. LD_PRELOAD'ing the host SDL2 library doesn't work anymore.

**Comment by kisak-valve** [comment]
Closing as outdated. If something similar shows up again, it'll need a new investigation.
