### ISSUE TITLE
Steam Crashes + Blackout

### ISSUE THREAD

**Issue by GoldenAngel1997** [ValveSoftware/steam-for-linux#7281]
Startup Updater April 09 2019 [found off current bootstrap file]
Kubuntu 20.04.0
Forgone Beta testing
Current Drivers/Headers: nVIDIA Driver 440; Header 5.4.0-42; Up-to-date

Becoming a long-running story, including with multiple steam reinstalls / reflash entire OS. Always happening, after the 1st update gets applied [size ranging from 100MB-220MB in size] / verify update and inputting login info, has the entire GUI freeze to then blackout/crash [no error / warning message at any point] [2-3 cores stuck on 100% load].

Repeatable, by just logging in

**Comment by kisak-valve** [comment]
Hello @GoldenAngel1997, in general, no OpenGL application including Steam should be capable of taking down the system, which hints that you've encountered a video driver issue.

**Comment by GoldenAngel1997** [comment]
@kisak-valve Would it be best, to perform re-install, of the initial/existing driver? Or to engage full removal/install? [Keep using current, or dial back to next older driver set?]. Never encountered this level of trouble, for otherwise fresh run of software/drivers

**Comment by kisak-valve** [comment]
Unfortunately, I don't have any guidance to suggest on the system side, but I have a hunch that the issue you're seeing is a video driver issue that is being aggravated by libcef.

Maybe try running `steam steam://open/minigameslist` in a terminal. This will tell steam to start in "Small mode" which does not use libcef to render.

If that's successful, then go to Steam -> Settings -> Interface and uncheck `Enable GPU accelerated rendering in web views` and if you're lucky, that might avoid the issue when running steam normally.

You'll most likely also want to go to Steam -> Settings -> Library and check `Low Performance Mode`.

**Comment by GoldenAngel1997** [comment]
@kisak-valve Much appreciation, for your inputs, through this [unnecessary] ordeal. It did take an awful lot of fumbling / full stop resets, but ultimately got it working (force holding to 435 suite)., without ANY hitch. I did want to give nVIDIA a chance, hoping they've [remotely] softened their attitude with open source... but well, healing wounds are still an open wound [insert Linus Torvaldis' vocal tirade].

![Linus_Torvalds_Nvidia_Fuck_You](https://user-images.githubusercontent.com/68569816/88243660-19800080-cc5f-11ea-9c0b-f3ce76304f4b.gif)
