### ISSUE TITLE
Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1 libdrm.so.2

### ISSUE THREAD

**Issue by Khantanjil** [ValveSoftware/steam-for-linux#7284]
![error0](https://user-images.githubusercontent.com/61469147/88276015-3a376d00-ccd6-11ea-94f0-d08eb8bb161c.jpg)
![error1](https://user-images.githubusercontent.com/61469147/88276037-44f20200-ccd6-11ea-96dc-7b99bcf504cb.jpg)

#### System Information
Linux 5.3.0-18-generic #19-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* Distribution: Lubuntu 19.10

Hello, im trying to install the steam on my computer but i have this errors:

```
Installing breakpad exception handler for appid(steam)/version(1.0)
[2020-07-23 10:54:39] Installing update...
[2020-07-23 10:54:42] Cleaning up...
[2020-07-23 10:54:42] Update complete, launching...
[2020-07-23 10:54:42] Shutdown
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 3 items discarded.
Restarting Steam by request...
Package xterm needs to be installed
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
Package libc6:i386 needs to be installed
x-terminal-emulator: invalid option -- 'T'
QTerminal 0.14.1
Usage: qterminal [OPTION]...

  -d,  --drop               Start in "dropdown mode" (like Yakuake or Tilda)
  -e,  --execute <command>  Execute command instead of shell
  -h,  --help               Print this help
  -p,  --profile            Load qterminal with specific options
  -v,  --version            Prints application version and exits
  -w,  --workdir <dir>      Start session with specified work directory

Homepage: <https://github.com/lxqt/qterminal>
Report bugs to <https://github.com/lxqt/qterminal/issues>
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME has been set by the user to: /home/tanjil/.local/share/Steam/ubuntu12_32/steam-runtime
Found newer runtime version for 64-bit libdbusmenu-glib.so.4. Host: 4.0.12 Runtime: 4.0.13
Found newer runtime version for 64-bit libGLU.so.1. Host: 1.3.1 Runtime: 1.3.8004
Found newer runtime version for 64-bit libvulkan.so.1. Host: 1.1.114 Runtime: 1.2.135
Forced use of runtime version for 64-bit libcurl.so.4. Host: 4.5.0 Runtime: 4.2.0
Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
libdrm.so.2
```
I installed the steam with
`wget http://media.steampowered.com/client/installer/steam.deb`
`sudo apt-get install gdebi-core`
`sudo gdebi steam.deb`

And i have the error saying "Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1 libdrm.so.2" and also i install the official steam site and gives the same error.
Before of this error, i got an error which i was missing libc.so.6 so i used the command `sudo apt-get install libc6-i386` and now i am the situation of "Error: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1 libdrm.so.2" and how can i fix it? I want to install steam on my computer, and im on Lubuntu

**Comment by Khantanjil** [comment]
Fixed it! Finally, i run this command on terminal 
`sudo apt install libgl1-mesa-dri:i386 libgl1:i386`
`steam`

**Comment by Khantanjil** [comment]
Make sure you do `sudo dpkg --add-architecture i386` and after `sudo apt update` and then install with `sudo apt-get install --reinstall libgl1-mesa-glx:i386` it worked for me!

**Comment by MasterCATZ** [comment]
wow steam was only working a few days ago now showed this

**Comment by asimmakhmudov** [comment]
> Make sure you do `sudo dpkg --add-architecture i386` and after `sudo apt update` and then install with `sudo apt-get install --reinstall libgl1-mesa-glx:i386` it worked for me!

After this operation, 5.587 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?] Yes
Abort.
it didn't work for me

**Comment by kisak-valve** [comment]
Hello @asimmakhmudov, a massive removal of system packages is definitely bad and you shouldn't let apt proceed. Blind guess that you're seeing something similar to #7982.

**Comment by funcelot** [comment]
> Hello @asimmakhmudov, a massive removal of system packages is definitely bad and you shouldn't let apt proceed. Blind guess that you're seeing something similar to #7982.

and do not forget to mention that doitn so will get your laptop a brick!

to restore laptop, press

alt+f2 (tty2), login and set all again

sudo apt update
sudo apt upgrade
sudp apt-get install gnome

**Comment by funcelot** [comment]
i will survive! (c) abba

**Comment by oong26** [comment]
> This work for me:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt-get update
> sudo apt install libgl1-mesa-dri:i386 libgl1:i386
> sudo apt-get upgrade steam -f
> sudo apt install nvidia-driver-libs:i386
> ```

Thank you bro this worked for me.

**Comment by Derber2004** [comment]
> This work for me:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt-get update
> sudo apt install libgl1-mesa-dri:i386 libgl1:i386
> sudo apt-get upgrade steam -f
> sudo apt install nvidia-driver-libs:i386
> ```

Thanks :)

**Comment by CapsAdmin** [comment]
Coming from google with this problem, my issue running the above was that I had a custom ppa for llvm that added some specific version llvm13 while at the same time i had the oibaf graphics driver repo which also had a specific version of llvm13 that all my drivers relied on. 

So doing the above freaks apt out and tells me it wants to remove almost everything graphics related on my system.

My solution was to downgrade llvm13 to the one from the oibaf graphics driver repo lik ethis

```shell
caps@pc:~/Downloads$ apt list -a libllvm13
Listing... Done

libllvm13/unknown,now 1:13.0.1~++20211215022811+5932c004778c-1~exp1~20211215022819.27 amd64 [installed]
libllvm13/focal 1:13.0.0-8~oibaf~f amd64
libllvm13/focal 1:13.0.0-8~oibaf~f i386

ccaps@pc:~/Downloads$ sudo apt install libllvm13/focal
```

where libllvm13/focal was the one I needed.

**Comment by theoarthur** [comment]
> This work for me:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt-get update
> sudo apt install libgl1-mesa-dri:i386 libgl1:i386
> sudo apt-get upgrade steam -f
> sudo apt install nvidia-driver-libs:i386
> ```

It didn;t work for me, saying permission was denied, how do I bypass that?

**Comment by funcelot** [comment]
> 

in general permission denied cured with something like that:

```bash
sudo chown +R <user>:<group> <path_to_cure
```

but as i understand, it sounds like you are trying to execute these commands from root and literally you do not need to use `sudo`.

i believe in that cause `dpkg` is just a debian package manager and if such an issue would ever happened, it will be fixed decades ago. so logically, this is not a security issues, but rather the configuration issue for you system.

**Comment by braiam** [comment]
Those packages should be added to the dependency list of the Debian package.

**Comment by Osyed02** [comment]
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt install libgl1-mesa-dri:i386 libgl1:i386
sudo apt-get upgrade steam -f
sudo apt install nvidia-driver-libs:i386

Works Fine... :)
Thanks...

**Comment by fonikz** [comment]
I've got intel integrated graphics, running Ubuntu Studio 22.04, which runs KDE Plasma. I'm having a similar situation. When I sudo apt upgrade steam -f I get a huge out put of lots of applications that depend on libudev1, but it is not installable. When I search for the package, it is already installed.

**Comment by funcelotwork** [comment]
> I've got intel integrated graphics, running Ubuntu Studio 22.04, which runs KDE Plasma. I'm having a similar situation. When I sudo apt upgrade steam -f I get a huge out put of lots of applications that depend on libudev1, but it is not installable. When I search for the package, it is already installed.

i think you should install not from sudoers trough user profile with a lot of restrictions, but from the root profile, is it solves the problem?

**Comment by olivier1208** [comment]
This worked for me

``sudo apt install libgl1:i386``

After long hours of trying

**Comment by funcelot** [comment]
> This worked for me
> 
> `sudo apt install libgl1:i386`
> 
> After long hours of trying

thanks all, your efforts are meaningful cause i did the same many times, and your comments realy saves one's day, for sure!

**Comment by Synaxis** [comment]
> So doing the above freaks apt out and tells me it wants to remove almost everything graphics related on my system.
apt-get install -f 
-f means fix-dependencies

**Comment by nekromoff** [comment]
Solution that worked for me - downgrading couple of amd64 versions of packages:
https://www.ambience.sk/fix-steam-on-ubuntu-22-04-you-are-missing-the-following-32-bit-libraries-and-steam-may-not-run-libgl-so-1/

**Comment by AhanafRASHID** [comment]
Thank you for the error fix. This worked for me too..

**Comment by Criziz21** [comment]
> Fixed it! Finally, i run this command on terminal `sudo apt install libgl1-mesa-dri:i386 libgl1:i386` `steam`

DON'T RUN THIS COMMAND!!!!!!

**Comment by 108806** [comment]
```sh
$ sudo apt install libgl1-mesa-dri:i386 libgl1:i386                     130 ⨯
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apt : Depends: adduser but it is not going to be installed
       Depends: gpgv or
                gpgv2 but it is not going to be installed or
                gpgv1 but it is not going to be installed
       Depends: libapt-pkg6.0 (>= 2.4.8) but it is not going to be installed
       Depends: libc6 (>= 2.34) but it is not installable
       Depends: libgcc-s1 (>= 3.3.1) but it is not going to be installed
       Depends: libgnutls30 (>= 3.7.0) but it is not going to be installed
       Depends: libseccomp2 (>= 2.4.2) but it is not going to be installed
       Depends: libstdc++6 (>= 11) but it is not going to be installed
       Depends: libsystemd0 but it is not going to be installed
       Recommends: ca-certificates but it is not going to be installed
 base-files : PreDepends: awk
              Depends: libc6 (>= 2.34) but it is not installable
 base-passwd : Depends: libc6 (>= 2.34) but it is not installable
               Depends: libdebconfclient0 (>= 0.145) but it is not going to be installed
 bash : PreDepends: libc6 (>= 2.34) but it is not installable
        PreDepends: libtinfo6 (>= 6) but it is not going to be installed
 bsdutils : PreDepends: libc6 (>= 2.34) but it is not installable
            PreDepends: libsystemd0 but it is not going to be installed
            Recommends: bsdextrautils
 coreutils : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
             PreDepends: libattr1 (>= 1:2.4.44) but it is not going to be installed
             PreDepends: libc6 (>= 2.34) but it is not installable
             PreDepends: libgmp10 (>= 2:6.2.1+dfsg) but it is not going to be installed
             PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
 dash : PreDepends: libc6 (>= 2.34) but it is not installable
 debianutils : PreDepends: libc6 (>= 2.34) but it is not installable
 diffutils : PreDepends: libc6 (>= 2.34) but it is not installable
 dpkg : PreDepends: libbz2-1.0 but it is not going to be installed
        PreDepends: libc6 (>= 2.34) but it is not installable
        PreDepends: liblzma5 (>= 5.2.2) but it is not going to be installed
        PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
        PreDepends: libzstd1 (>= 1.4.0) but it is not going to be installed
        PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed
 e2fsprogs : PreDepends: libblkid1 (>= 2.36) but it is not going to be installed
             PreDepends: libc6 (>= 2.34) but it is not installable
             PreDepends: libcom-err2 (>= 1.43.9) but it is not going to be installed
             PreDepends: libext2fs2 (= 1.46.5-2ubuntu1.1) but it is not going to be installed
             PreDepends: libss2 (>= 1.38) but it is not going to be installed
             PreDepends: libuuid1 (>= 2.16) but it is not going to be installed
             Depends: logsave
             Recommends: e2fsprogs-l10n but it is not going to be installed
 findutils : PreDepends: libc6 (>= 2.34) but it is not installable
             PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
 grep : PreDepends: libc6 (>= 2.34) but it is not installable
        PreDepends: libpcre3 but it is not going to be installed
 gzip : PreDepends: libc6 (>= 2.34) but it is not installable
 hostname : PreDepends: libc6 (>= 2.34) but it is not installable
 init : PreDepends: systemd-sysv
 libc-bin : Depends: libc6 (> 2.35) but it is not installable
            Depends: libc6 (< 2.36) but it is not installable
 libcrypt1 : Depends: libc6 (>= 2.25) but it is not installable
 login : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed
         PreDepends: libc6 (>= 2.34) but it is not installable
         PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed
         PreDepends: libpam-runtime but it is not going to be installed
         PreDepends: libpam-modules but it is not going to be installed
 ncurses-bin : PreDepends: libc6 (>= 2.34) but it is not installable
               PreDepends: libtinfo6 (>= 6.3) but it is not going to be installed
 perl-base : PreDepends: libc6 (>= 2.35) but it is not installable
 sed : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
       PreDepends: libc6 (>= 2.34) but it is not installable
       PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
 shim-signed : Depends: grub-efi-amd64-signed (>= 1.187.2~) but it is not going to be installed or
                        grub-efi-arm64-signed (>= 1.187.2~) but it is not installable
               Depends: grub2-common (>= 2.04-1ubuntu24)
               Depends: mokutil (>= 0.3.0+1538710437.fb6250f-0ubuntu2) but it is not going to be installed
               Depends: sbsigntool but it is not going to be installed
               Recommends: secureboot-db but it is not going to be installed
 sysvinit-utils : Depends: libc6 (>= 2.34) but it is not installable
 tar : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
       PreDepends: libc6 (>= 2.34) but it is not installable
       PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
 util-linux : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed
              PreDepends: libblkid1 (>= 2.37.2) but it is not going to be installed
              PreDepends: libc6 (>= 2.34) but it is not installable
              PreDepends: libcap-ng0 (>= 0.7.9) but it is not going to be installed
              PreDepends: libmount1 (>= 2.37.2) but it is not going to be installed
              PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed
              PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
              PreDepends: libsmartcols1 (>= 2.34) but it is not going to be installed
              PreDepends: libsystemd0 but it is not going to be installed
              PreDepends: libtinfo6 (>= 6) but it is not going to be installed
              PreDepends: libudev1 (>= 183) but it is not going to be installed
              PreDepends: libuuid1 (>= 2.16) but it is not going to be installed
              PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
                ```

**Comment by ma-vick** [comment]
> 

THANK YOU!! THIS WORKED

**Comment by aakarshan-raj** [comment]
don't run these commands, almost bricked my laptop

**Comment by Bsd-us** [comment]
this broke my programs and deleted quite everything

**Comment by neloykarmaker** [comment]
I have This problem when i run steam

```
Steam needs to install these additional packages:
libc6:amd64 libc6:i386 libegl1:amd64 libegl1:i386 libgbm1:amd64 libgbm1:i386 libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1:amd64 libgl1:i386

Press return to proceed with the installation: 
..........
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libc6 is already the newest version (2.31-13+deb11u6).
libegl1 is already the newest version (1.3.2-1).
libegl1 set to manually installed.
libgbm1 is already the newest version (20.3.5-1).
libgbm1 set to manually installed.
libgl1 is already the newest version (1.3.2-1).
libgl1 set to manually installed.
libgl1-mesa-dri is already the newest version (20.3.5-1).
libgl1-mesa-dri set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libelf1:i386 (>= 0.142) but it is not going to be installed
                        Depends: libvulkan1:i386 (>= 1.2.131.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Press return to continue: 
```

**Comment by neloykarmaker** [comment]
> 

When i tried it..

```
$sudo apt install libgl1-mesa-dri:i386 libgl1:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libelf1:i386 (>= 0.142) but it is not going to be installed
                        Depends: libvulkan1:i386 (>= 1.2.131.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by kisak-valve** [comment]
Hello @neloykarmaker, Debian's multi-arch implementation requires that arch variants have exactly the same version, and it also strongly dislikes downgrading packages to resolve package conflicts.

A common scenario that can lead to what you're seeing is when there's a 64 bit package (amd64) and the matched version for 32 bit (i386) never becomes available in the distro's repository or that package version gets removed for some reason and locally installed package is left newer than what is available in the package repositories.

I would inspect the 32 bit and 64 bit packages apt says won't be installed with something like `apt policy libelf1 libelf1:i386 libvulkan1 libvulkan1:i386` looking for where the package versions don't match up and walk up the dependency tree until you find the versions that aren't matched between amd64 and i386.

You can isolate each dependency and ask apt to install one dependency with both arch variants at a time to narrow the scope of your issue. For example with libelf1: `sudo apt install libelf1 libelf1:i386` **IMPORTANT: If apt at any time asks you for permission to remove a bunch of packages, do not let it proceed.** If apt refuses to add that dependency, then it should give you a hint in the output for some more packages to inspect with apt policy and repeat the process until you find which package is giving you trouble.

**Comment by IKiriZudoI** [comment]
> this broke my programs and deleted quite everything

Exactly don't do that, i had the same problem.

**Comment by miguno** [comment]
What helped me, using a NVIDIA 3080 Ti on Debian 12 (X11, not Wayland) where the instructions in the Debian wiki: https://wiki.debian.org/NvidiaGraphicsDrivers#multiarch-install:

```shell
# After installing the NVIDIA drivers, enable 32-bit multiarch
# and update your repository listing.
$ sudo dpkg --add-architecture i386 && sudo apt update

# Afterwards, to install the 32-bit version of the NVIDIA
# libraries package, run:
$ sudo apt install nvidia-driver-libs:i386
```

**Comment by Raysaurous** [comment]
This worked really well, thanks!

**Comment by nothugofsea** [comment]
> This work for me:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt-get update
> sudo apt install libgl1-mesa-dri:i386 libgl1:i386
> sudo apt-get upgrade steam -f
> sudo apt install nvidia-driver-libs:i386
> ```

Thank you it worked for me

**Comment by wenqingx** [comment]
```
he following packages have unmet dependencies:
 libelf1:i386 : Depends: zlib1g:i386 (>= 1:1.1.4) but it is not installable
 libgl1-mesa-dri:i386 : Depends: zlib1g:i386 (>= 1:1.1.4) but it is not installable
                        Recommends: libgl1-amber-dri:i386 but it is not installable
 libllvm15:i386 : Depends: zlib1g:i386 (>= 1:1.2.0) but it is not installable
 libpciaccess0:i386 : Depends: zlib1g:i386 (>= 1:1.2.3.3) but it is not installable
 libxml2:i386 : Depends: zlib1g:i386 (>= 1:1.2.3.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

...

```
steam.sh[721266]: Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
libdrm.so.2
```
how can i fix it ? thanks

**Comment by Darianisak** [comment]
A TL;DR for how I solved the missing `libGL.so.1` dependencies on an Debian/nVidia system:
```
# sudo apt install nvidia-driver-libs:i386
# sudo apt install libgl1-mesa-glx:i386
# sudo apt install --reinstall steam-installer
```

While not an exact one-to-one of the original issue, I've also encountered missing `libGL.so.1` dependencies when running `steam-installer` on a fresh Debian 12 installation.

Per the [documentation](https://wiki.debian.org/Steam#Installing_Steam), I'd installed the listed requirements, including the [NVIDIA drivers](https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_12_.22Bookworm.22) and the `i386` packages from [here](https://wiki.debian.org/Steam#Installing_Steam).

The solution, in my case, was to install `libgl1-mesa-glx:i386` (as mentioned by @Khantanjil ) and the `nvidia-driver-libs:i386` package. There was also a `sudo apt install --reinstall steam-installer` in the mix, however, I don't think that contributed all that much.

Hope this helps others that hit this issue!

**Comment by Behinder** [comment]
That problem happens also on Noble and added multiarchitecture on ARM64 doesnot help either. they have simply no candidate to install. can I build them myself in universal variant?

**Comment by cybergazer** [comment]
The amount of upvotes on this. Can't we just ship the software as a functioning product instead of having to google search this github issue? This happened because there wasn't extensive unit testing of the software before release so they shipping it broken

**Comment by SuMaPa** [comment]
> This work for me:
> 
> ```
> sudo dpkg --add-architecture i386
> sudo apt-get update
> sudo apt install libgl1-mesa-dri:i386 libgl1:i386
> sudo apt-get upgrade steam -f
> sudo apt install nvidia-driver-libs:i386
> ```
 works for me :)

**Comment by JosephCatrambone** [comment]
If you're using Ubuntu 24.04 and later you may have better luck installing the packages `steam-lib-amd64` and `steam-lib-i386:i386`.  These are metapackages which depend on the libraries needed by Steam.  Without them, I had significant issues with conflicts between the different libdrm/libgl versions.

**Comment by Behinder** [comment]
some versions of Ubuntu does not have all the dependencies in apt. I would
advice choosing different distro with proper package management withou snap.

czw., 22 maj 2025 o 23:11 Joseph Catrambone ***@***.***>
napisał(a):

**Comment by thiswillbeyourgithub** [comment]
The commands I had to do to make steam launch were:

```zsh
sudo apt install liblzma5:i386 libzstd1:i386 zlib1g:i386 --reinstall
```
- all three libs were already installed and I had to add the `--reinstall` flag.
- liblzma5 and libzstd where mentioned at steam startup as missing, but zlib was in an ulterior error message: `dlmopen /home/$USER/.local/share/Steam/ubuntu12_32/steamui.so failed: /home/$USER/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/i386-linux-gnu/libpng16.so.16)`

Here is my `uname -a` output:
`Linux REDACTED 6.8.0-87-generic #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`


I'm not sure it will work smoothly but at least it launches.



edit: didn't work. I ended up using [flatkpak](https://flathub.org/en/apps/com.valvesoftware.Steam)
