### ISSUE TITLE
Steam crashed while exiting

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#7290]
[dump.zip](https://github.com/ValveSoftware/steam-for-linux/files/4976001/dump.zip)

#### Your system information

* Steam client version (build number or date): Jul 24, 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I switched account on Steam and usually Steam needs restart for this. While restarting the previous process did not die. This is becoming a common problem with Steam restarts.

I have attached multiple out of process dumps.

#### Steps for reproducing this issue:

1. Restart steam or change account triggering a restart
2. Try on KDE or awesome WM

**Comment by kisak-valve** [comment]
For reference, the attached minidumps are DUMP_REQUESTED in crashhandler.so.

**Comment by amitavmohanty01** [comment]
Tried exiting Steam to close it and there was a crash again. Uploading it here for more context.
[dota.zip](https://github.com/ValveSoftware/steam-for-linux/files/4983468/dota.zip)

**Comment by amitavmohanty01** [comment]
I just reproduced the issue. I am attaching a few more dumps. I think it is in assert.
[dota.zip](https://github.com/ValveSoftware/steam-for-linux/files/4984620/dota.zip)

@kisak-valve I am sensing a pattern here. Most of my dumps are in crash handler or in assert. Is it because of the packaged libraries as I am on Arch Linux and not on Ubuntu?

**Comment by kisak-valve** [comment]
Hello @amitavmohanty01, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
