### ISSUE TITLE
Steam fails to launch games after resuming from suspend.

### ISSUE THREAD

**Issue by laftur** [ValveSoftware/steam-for-linux#7291]
* Steam client version: Built July 23, 2020 (package version 1595519552)
* Distribution: Arch Linux
* Opted in to steam client beta.
* System is on a rolling release, is very, very up-to-date.

Expected behavior:
Suspend should not affect steam's ability to launch games.

#### Steps for reproducing this issue:

1. Suspend. (systemctl suspend)
2. Resume.
3. Launch steam if it isn't already running. (Notably, it doesn't matter if steam was running before step 1)
4. Launch a game through steam.

Steam seems to think the game is running. Stop button does nothing. The game never starts. If enough time is allowed to pass, some games complain that steam must be running in order to launch. This issue is very similar to #474 , however restarting steam doesn't allow games to launch. The only thing I've found to work around the problem is a system reboot. Resetting network services does nothing (systemctl restart dhcpcd).

**Comment by kisak-valve** [comment]
Hello @laftur, since restarting Steam doesn't have an effect, this doesn't sound like a Steam issue. Maybe a bad routing table or kernel issue? I'd restart the network interface to see if that has an effect.

**Comment by laftur** [comment]
> Does your internet browser work fine while in the quirk state?
Yes, my web browser works fine while steam does not. Steam is the only program on my system that I've found to misbehave after resuming from suspension. In fact, all of Steam's normal Internet components work fine while in this quirk state. It seems to be the Steam API (the local system thing that games interface with upon launching) that becomes non-functional.

> I'd restart the network interface to see if that has an effect.
I did try restarting dhcpcd, but just for completeness (and because my system just happens to be running it), I also restarted systemd-networkd. I stopped both services, waited about ten seconds, and then restarted both services. This has the effect of completely setting down the interface and reacquiring an IP from our DHCP server. Again, I don't think this has anything to do with my problem (Steam API), but you asked.

**Comment by kisak-valve** [comment]
Hello @laftur, are you still experiencing this issue on an up to date system?

**Comment by laftur** [comment]
I can no longer reproduce this issue. It's unclear when they problem disappeared.

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing as fixed some time ago.
