### ISSUE TITLE
Steam keep redownloading game after rebooting

### ISSUE THREAD

**Issue by swawif** [ValveSoftware/steam-for-linux#7292]
#### Your system information

* Steam client version (build number or date): Jul 23 2020 at 11:01:27
* Distribution (e.g. Ubuntu): Linux Mint 20 / Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
I have a dual boot PC running Windows 10 and Linux Mint 20, and i have two shared steam library each running on different HDD

everytime i switch OS, steam will re-download almost every game
(but not all)

Currently i haven't seen a pattern on which game that it will redownload, it seems almost random
some game that it redownload were games that were new, some were old.
some came from the other drive, other 

Game that needed redownload
- Overcooked 2
- Payday 2
- Tabletop Simulator
- etc

Games that don't need redownload
- FSX Steam edition
- Moving Out
- No Man's Sky

#### Steps for reproducing this issue:

1. Open Steam on windows
2. reboot to the Linux Mint
3. open steam on the Linux Mint
4. Steam will queue a lot of game to be re-downloaded

**Comment by kisak-valve** [comment]
Hello @swawif, noted in https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing Steam libraries between OSes is unsupported. Any quirks by doing that is undefined behavior.
