### ISSUE TITLE
Steam does not take umlauts

### ISSUE THREAD

**Issue by Supervisor83** [ValveSoftware/steam-for-linux#7294]
#### Your system information

* Steam client version (build number or date): Steam-API: v020 Steam-Paket-Version: 1594252496 steam-runtime_0.20200604.0
* Distribution (e.g. Ubuntu): Debian 10 (Buster) 64bit (Cinnamon Desktop)
* Opted into Steam client beta?: [Yes] Steam Beta Update is enabled
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
When I enter something in Steam (example: chat or shop), and type an umlaut (äöü), it is not displayed (example: Mäuse = muse) "German".

I have the problem only in Steam, in Linux (example: Browser, LibreOffice, TeamSpeak, Terminal, Kate) it works.

#### Steps for reproducing this issue:

1. Just enter a word with an umlaut or just the umlaut.

With best regards
Supervisor83

**Comment by kisak-valve** [comment]
Hello @Supervisor83, this sounds like #5704.

Please verify that the output of `locale -a` includes a line with `en_US.utf8`.

If it doesn't, please uncomment (or add) `en_US.UTF-8 UTF-8` in `/etc/locale.gen` and run `locale-gen` as root to regenerate the system-wide locales.

**Comment by Supervisor83** [comment]
```
locale -a
C
C.UTF-8
de_DE.utf8
POSIX
```
Thanks for your answer.

**Comment by Supervisor83** [comment]
has worked. Thank you very much.

```
locale -a
C
C.UTF-8
de_DE.utf8
POSIX
```
Thanks for your answer.
