### ISSUE TITLE
Problem with running EasyAntiCheat

### ISSUE THREAD

**Issue by Wamolve** [ValveSoftware/steam-for-linux#7298]
#### Your system information

* Steam client version: v020 
* Distribution: Ubuntu 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

![Снимок экрана от 2020-06-07 16-49-01](https://user-images.githubusercontent.com/66585554/88780356-4cb51900-d1a4-11ea-9cc1-8e468f05d913.png)
![Снимок экрана от 2020-06-22 18-49-11](https://user-images.githubusercontent.com/66585554/88780533-8ede5a80-d1a4-11ea-8ea8-e0be54e72f8c.png)
![Снимок экрана от 2020-07-29 14-07-10](https://user-images.githubusercontent.com/66585554/88780725-dc5ac780-d1a4-11ea-8866-ba392d679fb1.png)

Well. I came across something like " Oops! Failed to start EasyAntiCheat". And this is in all games that have EasyAntiCheat. I tried to run EAC separately on Wine and it gave me this error: "The Origin app is required for the game, but it is not installed. Please reinstall the Origin app." In my case, this is the game Plants vs. Zombies: Battle for Neighborville. And all this happens because EAC does not see Origin and issues such an error and closes.What should I do?

**Comment by kisak-valve** [comment]
Hello @Wamolve, this issue tracker is for the native Linux Steam client. While there's some community effort going into improve the situation, the Windows version of EasyAntiCheat run in Wine is known to have issues and this is out-of-scope for this issue tracker.

You may have some luck asking over at the winehq forums.

**Comment by Wamolve** [comment]
OK I'll ask on WineHQ if I don't get an answer there I'll just wait for something to be done with EAC
