### ISSUE TITLE
‘Selected filesystem does not allow executing files.’ can be wrong.

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#730]
Deleted the local content of a game and went to reinstall it and got this:

![Screenshot from 2013-01-18 09:40:12](https://f.cloud.github.com/assets/7708/77673/93b8efc6-6153-11e2-8a7e-9b990a8b75c9.png)

I haven’t changed the install location at this point, the dialog appeared as soon as the install window did. Its happened once before but I thought nothing of it. I cannot get it to reproduce consistently, my ~ filesystem supports executing:

```
john@joran ~ > mount
/dev/sda5 on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
/dev/sda1 on /boot type ext4 (rw)
/dev/sda8 on /home type ext4 (rw)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noexec,nosuid,nodev)
gvfs-fuse-daemon on /home/john/.gvfs type fuse.gvfs-fuse-daemon (rw,nosuid,nodev,user=john)
/dev/sda10 on /media/editing type btrfs (rw,nosuid,nodev,uhelper=udisks)
```

**Comment by dolanor** [comment]
@millerthegorilla Totally solved my problem too. Installed Steam today after a few months without. So it is just the problem of case-sensitiveness.
Thank you !

**Comment by nonchip** [comment]
it's still wrong in current beta

**Comment by h8** [comment]
Still get the same issue. Can't create Steam folder on any ext4 drive. I don't get messages about glibc or similar. SteamApps is in lower case, but it didn't helps.

**Comment by Mecha-Weasel** [comment]
Same issue as this I believe?
https://github.com/ValveSoftware/steam-for-linux/issues/3936

**Comment by nonchip** [comment]
my workaround: `/etc/fstab`

    /home/kyra/.steam/steam/steamapps /home/kyra/.steam/steam/SteamApps none bind 0 0

hurts but works :P

**Comment by nonchip** [comment]
@slouken why is this issue closed? seems to be still an issue for some of us

**Comment by h8** [comment]
@nonchip your solution with strace works for me, but I need to start steam every time with strace, because it will not see previously created library dirs. Also, strace fixes blank store, community, etc. pages.

**Comment by nonchip** [comment]
@h8 for me sometimes it shows the library without strace, but can't install, sometimes it doesn't.
with strace it works everytime, so yeah, we should be using that. but srsly, that's one creepy bug :P

**Comment by h8** [comment]
it seems like an issue with the recent kernel in Ubuntu LTS  https://github.com/ValveSoftware/steam-for-linux/issues/3936
