### ISSUE TITLE
Steam Overlay in Big Picture Mode crashes when using NVIDIA PRIME Render Offload

### ISSUE THREAD

**Issue by solbero** [ValveSoftware/steam-for-linux#7305]
#### Your system information

* Steam client version: Jul 31 2020 at 22:13:33 
* Distribution: Ubuntu MATE 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Playing a game with the Steam Overlay enabled in Big Picture Mode while using NVIDIA PRIME Render Offload crashes Steam. However, playing a game in Desktop Mode with the Steam Overlay enabled does not produce issues.

Disabling the Steam Overlay in Big Picture Mode removes the problem in Big Picture Mode. Unfortunately, this also disables Steam from managing any attached controllers.

The problem is not reproduced when only using the discrete graphics card (NVIDIA Performance mode in `nvidia-settings`) and not NVIDIA PRIME Render Offload (NVIDIA On-demand in `nvidia-settings`)

* [System information
](https://gist.githubusercontent.com/solbero/6d509a99eec0c0b3c13c70b0ee5e5950/raw/00b588906df97b310cafc1a026344363ffcc0457/gistfile1.txt)
* [Terminal output (Big Picture Mode)](https://gist.githubusercontent.com/solbero/db7b8e45accbf3301490d076f6bcaf78/raw/72ce8866ca674b44db4d31f9d26437a79329796f/gistfile1.txt)
* [Terminal output (Desktop Mode)](https://gist.githubusercontent.com/solbero/427c0f7db2be2a5f3e1bdc29546a69c3/raw/83c2397e1f94bae7df431971cdf45806c575f73e/gistfile1.txt)

#### Steps for reproducing this issue:

1. Install  NVIDIA graphics driver 440.100
2. Enable NVIDIA On-demand in `nvidia-settings`
3. Launch Steam with environment variables `__NV_PRIME_RENDER_OFFLOAD=1` and `__GLX_VENDOR_LIBRARY_NAME=nvidia`
4. Make sure the Steam Overlay is enabled
5. Open Steam Big Picture
6. Launch a game

**Comment by solbero** [comment]
I tried the Flatpak Steam and I was able to reproduce the issue there as well.

**Comment by kisak-valve** [comment]
Hello @solbero, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
