### ISSUE TITLE
Steam Fails to Launch (X Error)

### ISSUE THREAD

**Issue by spencer3035** [ValveSoftware/steam-for-linux#7309]
#### Your system information

* Steam client version (build number or date): Jul 31 2020 09:12:07
* Distribution (e.g. Ubuntu): Ubuntu 18.04 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I run 
```sudo apt-get install steam-installer```

to get the current version of steam. Then when I try to run steam in the terminal, after updating, I get the following output: 

```
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/[USERNAME]/.steam/ubuntu12_32/steam
[2020-08-08 23:35:56] Startup - updater built Jul 31 2020 09:12:07
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  154 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-08-08 23:35:57] Checking for update on startup
[2020-08-08 23:35:57] Checking for available updates...
[2020-08-08 23:35:57] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-08-08 23:35:57] Download skipped: /client/steam_client_ubuntu12 version 1596217132, installed version 1596217132
[2020-08-08 23:35:57] Nothing to do
[2020-08-08 23:35:57] Verifying installation...
[2020-08-08 23:35:57] Performing checksum verification of executable files
[2020-08-08 23:35:57] Verification complete

```

And the Steam GUI fails to open. I have checked ```glxinfo``` and ```glxgears``` to make sure that my graphics drivers are working. Other games I have installed outside Steam work without issue. 

#### Steps for reproducing this issue:

1. Install Steam
2. Run Steam

**Comment by kisak-valve** [comment]
Hello @spencer3035, what video card / driver version are you using? I suspect that you're using an nVidia card with their proprietary driver, but don't have the driver's 32 bit userspace libraries installed. Does any 32 bit OpenGL application like `glxinfo ` from `mesa-utils:i386` work?

**Comment by spencer3035** [comment]
I believe you correctly diagnosed the problem. ```glxinfo``` from the different source gives:

```
name of display: :0
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  57
  Current serial number in output stream:  56
```

Driver information

```
sudo lshw -c video 
  *-display                 
       description: VGA compatible controller
       product: NVIDIA Corporation
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:26:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:78 memory:f6000000-f6ffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:e000(size=128) memory:f7000000-f707ffff
```
It looks like the driver is using ```nvidia-driver-450``` based on what is installed. After many hours of troubleshooting, it seems that ```nvidia-driver-450``` does not support ```i386``` architecture. After downgrading to ```nvidia-driver-430``` (The latest version supported by ```ppa:graphucs-drivers```, steam now runs.

**Comment by kisak-valve** [comment]
There's no particular reason why the nvidia 450 would not work. On Ubuntu 18.04, you would need to check that `libnvidia-gl-450:i386` was installed with the rest of that driver series.
