### ISSUE TITLE
Cannot connect to steam network, directly after updating Steam and loggin in with 2FA

### ISSUE THREAD

**Issue by s1ugh34d** [ValveSoftware/steam-for-linux#7311]
#### Your system information

* Steam client version (build number or date): ? don't know how to find this, latest deb file from steam site, updated on first start
* Distribution (e.g. Ubuntu): ubuntu 20.04.1 64-bit 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Fully updated
* Tested under Radeon driver 20.10 and 20.30 steam ran fine under both in the past.

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. 

Expected:
Install steam latest
Steam updates 268mb
Steam login
2FA check clear
Steam library shows up after autologin

What Did Happen:
Install steam latest
Steam updates 268mb
Steam login
2FA check clear
Login begins in GUI then error
Cannot connect to steam network. Could be an issue with your internet connection

I had steam running fine, the last update of the client and no longer can I load the GUI to launch games

re-installed and removed everything thrice

https://gist.github.com/s1ugh34d/91171749ce7615c21f17d923081b6982

`****@****-h:~$ sudo lshw -c video 
  *-display                 
       description: VGA compatible controller
       product: Vega 20 [Radeon VII]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:03:00.0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:133 memory:c0000000-cfffffff memory:d0000000-d01fffff ioport:e000(size=256) memory:dfc00000-dfc7ffff memory:c0000-dffff
`
#### Steps for reproducing this issue:

1. Launch Steam
2. Autologin
3. Steam error window

**Comment by kisak-valve** [comment]
Hello @s1ugh34d, `Could not connect to X session manager: None of the authentication protocols specified are supported` is a possible line of interest from the log. Any particular reason why you're using AMDGPU-PRO? Can you test if Steam has the same behavior with mesa?

**Comment by s1ugh34d** [comment]
I didn't realize there was a different driver for ubuntu. AMD's site directed me to this version and the 20.10 version earlier this year when I got the card.
Would just uninstalling the AMD driver suffice to revert to mesa?

**Comment by s1ugh34d** [comment]
Uninstalled AMD drivers, installed Mesa drivers fresh. Re-installed steam
Same issue

**Comment by SteffenL** [comment]
I believe I've had more or less the same problem for months now but I am using an Nvidia graphics card. The native client stopped working the same way multiple times after installing updates for either Ubuntu or Steam. The flatpak version used to work for me but that one also stopped working eventually.

Part of the error message is simply `Could connect to Steam network`.

![steam](https://user-images.githubusercontent.com/1543854/90594904-92ef1c80-e226-11ea-894c-1397fce93967.png)

Steam error log:
https://gist.github.com/SteffenL/ccf72b1b6f31373743b4e77ccf98c234

I do not know if this is useful:
```
$ sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:02:00.0
       version: ef
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller cap_list rom
       configuration: driver=vfio-pci latency=0
       resources: irq:11 memory:c0000000-cfffffff memory:d0000000-d01fffff ioport:d000(size=256) memory:fb800000-fb83ffff memory:fb840000-fb85ffff
  *-display
       description: VGA compatible controller
       product: GP102 [GeForce GTX 1080 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:68 memory:fa000000-faffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:e000(size=128) memory:c0000-dffff
```

**Comment by darksabrefr** [comment]
I had a similar issue today after updating the Steam client on my Ubuntu 20.10 machine, and it seems it cannot be launched when docker-compose is running (I'm developper, it's my dev stack). @SteffenL : you give me an hint about IP issues, and docker/docker-compose create local virtual networks and so, IPs. Thank you :wink:

**Comment by SteffenL** [comment]
I might have had Docker and Compose installed but it seemed more likely that connections from my IP address were blocked somewhere along the path to the Steam servers when using the client for Linux. I didn't have the problem while using Windows, and I didn't have the problem when connecting to Steam through VPN on Linux, only when I was using my real IP and Linux at the same time. I also had connection problems on a handful of other websites. The problem persisted only until I was assigned a different IP address from my ISP.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
