### ISSUE TITLE
Steam auto shutdown itself when computer is in screen saver mode

### ISSUE THREAD

**Issue by notnotme** [ValveSoftware/steam-for-linux#7312]
#### Your system information

* Steam client version (build number or date): July 31 2020
* Distribution (e.g. Ubuntu): Linux Mint 20
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam just seem to kill itself or hang if my screen saver turn on for too long. When I unlock the screen steam client is not running nor my download. I figured out this behavior tonight, patiently waiting for 64GO to download at 512Kbps.

#### Steps for reproducing this issue:

1. Start steam and start downloading a game (a big one, the one you take 1 or 2 day to get)
2. Before going to seelp, just lock your screen
3. When you wake up, unlock your screen. Steam is not running.

It does not happen right after a screen lock but after a while. I can't tell for the delay because I was just trying to sleep but because it was too hot I checked the download state time to time and noticed this behavior.

**Comment by kisak-valve** [comment]
Hello @notnotme, are you still experiencing this issue on an up to date system?

**Comment by notnotme** [comment]
Hello @kisak-valve the issue did not reproduce anymore, I'm running Mint 21.1.

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing.
