### ISSUE TITLE
(Seemingly) excessive shader pre-caching

### ISSUE THREAD

**Issue by LuyeT** [ValveSoftware/steam-for-linux#7313]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
https://gist.github.com/LuyeT/1e57f6fedcc49f4fa180c96466d92dc3
* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
I believe the vulkan shaders are supposed to be processed only upon update of dota and/or system. They have been processed at least once per day, but not necessarily every launch. It has been this way for the past month or so. The processing takes about 5-30 minutes at 100% cpu consumption.

#### Steps for reproducing this issue:

1. I am not entirely sure on how to reproduce the issue, as it happens frequently, but sporadically.
2. 
3.

**Comment by kisak-valve** [comment]
Hello @LuyeT, shader pre-caching is handled by the Steam client, not Dota 2, which is why I've transferred this issue to the steam-for-linux issue tracker.

This looks like the same issue that's being tracked at #7306. Closing in favor of the older issue report.

**Comment by LuyeT** [comment]
Thanks, and sorry about the duplicate. I searched the dota git for similar
issue and posted due there not being one.

You might want to leave my issue here, closed, to prevent further
duplicates.

Regards
