### ISSUE TITLE
Games won't Start under Zorin OS Lite

### ISSUE THREAD

**Issue by MueEatMorld** [ValveSoftware/steam-for-linux#7315]
#### Your system information

* Steam client version (build number or date): Jul 31 2020
* Distribution (e.g. Ubuntu): Zorin OS Lite
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I want to start a game. I just press play. After this it shows me sometimes a window where I get asked about the options in which I want to run to run the game and then/or the game is getting started. The window gets closed and then it shows in the game list in Steam that game would be running and is highlighted green.But there aren't open any windows or failure prompts. It just give the information that the game would run and after a view seconds the game name is in white scripture again and nothing happens anymore.

#### Steps for reproducing this issue:

1. Just start a game

**Comment by kisak-valve** [comment]
Hello @MueEatMorld, please clarify which games you tried to run. Are there any hints in the terminal spew if you completely close Steam, then run Steam in a terminal and/or check in `~/.steam/error.log`? 

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by MueEatMorld** [comment]
Hello @kisak-valve, the games I tried were AI War: Fleet Command, Crush Crush, Earth 2160,Meeple Station and Regions of Ruin. The error.log doesen't exist, the terminal gave me followed information.

bash: /home/michael/.steam/error.log: Datei oder Verzeichnis nicht gefunden (file or directory not found)

https://gist.github.com/MueEatMorld/ee88f26e29ec817b6e9e1125fa594717

Hope, I did it right.

**Comment by kisak-valve** [comment]
Thanks, I don't have a quick fix but let's try to make sense of what we're looking at anyway...

`Driver:  nouveau NV4B` and `OpenGL Version: 2.1` are the most significant details. Almost all game engines require more OpenGL support than your Curie generation nVidia hardware provides. Unfortunately, hardware from around that period didn't have feature parity between DirectX and OpenGL, and some game engines needed some sRGB features from OpenGL 3.0 to get close, so if a game claims it needs DirectX 9 for windows isn't enough info to determine if it is using OpenGL 2.1 on Linux.

AI War: Fleet Command - OpenGL 2.1 - most likely test case
Crush Crush - unclear
Earth 2160 - unclear
Meeple Station - unclear
Regions of Ruins - OpenGL 3.2 - won't work

Looks like AI War: Fleet Command is a Unity game, so there should be a game log you can ponder somewhere around something like `~/.config/unity3d/Arcen Games/AIWarFleetCommand/Player.log`. This is most likely not the exact folder name.

**Comment by MueEatMorld** [comment]
Thanks for helping out!

Is this maybe helpfull for you?

https://drive.google.com/file/d/1pCXUreAu3EYXdAjzip_X0bYdG4azbVN7/view?usp=sharing

**Comment by MueEatMorld** [comment]
Hello @kisak-valve ,
I just want to ask how far are you in your progress with my problem and would something change, if I use an other distribution?

**Comment by kisak-valve** [comment]
Hello @MueEatMorld, sorry that there was no further followup here. Ultimately, Steam can't compensation for a lack of features in the hardware you reported here and a newer GPU would be needed if you're still using this system.
