### ISSUE TITLE
background feature for fetching shaders issues

### ISSUE THREAD

**Issue by codeman101** [ValveSoftware/steam-for-linux#7316]
#### Your system information

* Steam client version (build number or date):  Jul 31 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No]  I don't know but I think so since I use steam play
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
If you enable background processing for pre-shaeder compiling it will get stuck trying to do it for games that aren't installed. Plus today I discovered it was trying to do it for a game I removed from my library a while back.

#### Steps for reproducing this issue:

1. Enable background shaeder compiling. 
2. Wait for it to attempt to do for a game you don't installed.

**Comment by kisak-valve** [comment]
Hello @codeman101, this issue is already being tracked at #7148. Closing as a duplicate.
