### ISSUE TITLE
Missed translation string?

### ISSUE THREAD

**Issue by BNieuwenhuizen** [ValveSoftware/steam-for-linux#7318]
#### Your system information

* Steam client version (build number or date): "Steam package versions: 1596762082"
* Distribution (e.g. Ubuntu):  Archlinux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] 

#### Please describe your issue in as much detail as possible:

the shader preprocessing dialog says "#SteamUI_JoinDialog_ProcessingShaderCache", this looks to me like a translation string that is missing.

AFAIU all my other Steam stuff is in English.

#### Steps for reproducing this issue:

1.  Run a game
2.  See the dialog

**Comment by feydreva** [comment]
Hello, 
I have the same issue, but only running PathOfExile.
It works fine on other game.
Each time I start POE, I have that pop-up.
Sometimes I close it the game starts, sometimes, I have to wait the 30 min, until this is done before I can play...
It is pretty annoying.
Fyi, my steam client is in english. my desktop environment in French.. but not sure that matter...
I am running Manjaro, up top date. I am opt in for the beta client.
I have pre caching enabled. and it says 2557 Mb.. that s seems to be a lot. can we adjust that ?

Thank you for your help

**Comment by kisak-valve** [comment]
Hello @BNieuwenhuizen, per "Fixed localization placeholder string appearing on the game launch dialog during Vulkan shader processing" in the [2020-08-18](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2738705758017771491) Steam client beta update, please opt into Steam's beta client and retest.

**Comment by BNieuwenhuizen** [comment]
Looks fixed.
