### ISSUE TITLE
TF2 feature request / Windows parity: Raw Input

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/steam-for-linux#732]
Copied from http://steamcommunity.com/app/221410/discussions/7/846939854227821906/

While RAW mouse input is Windows specific, could we get something similar for Linux version?

**Comment by edrickhong** [comment]
Hey, I know this is a security issue but maybe there can be an option for linux users to add themselves into the input group and the game can read directly from evdev for raw input? Or is this solution a no go?
