### ISSUE TITLE
Stuck Update Install Loop / Rebuilding 

### ISSUE THREAD

**Issue by GoldenAngel1997** [ValveSoftware/steam-for-linux#7320]
Phenom II 1090T
12GB DDR3
nVIDIA RTX2060; Driver 435

Now unknown at this point
OS: Kubuntu 20.04
Beta? No
Regularly perform Updates

Persistently oscillating between "Pins potentially out-of-date Rebuilding" / "update eternally hanging at 0 progress", every attempt for running steam. Also have attempted, without any internet connection applied [hoping to perform a clear cache on layout]. Multiple wipe downs of steam / dependencies... Occasionally mentions about an "uninstalled manifest found"

"client-download.steampowered.com/client/steam_client_ubuntu_12"?

How to clear this mess?
Is their anyway, to STOP these client bricking updates!?

**Comment by kisak-valve** [comment]
Hello @GoldenAngel1997, please clarify exactly what steps are involved in "Multiple wipe downs of steam / dependencies". Are you using the Valve-provided Steam package or the distro-provided Steam package?

In general, the Steam package provides a bootstrap environment to setup the current Steam client. It sounds like something went wrong in the setup and something's missing. You could try running `steam --reset` in a terminal to tell Steam to re-bootstrap the client. Alternatively, you can move/remove `~/.steam` and `~/.local/share/Steam` out of the way to get `steam` to run as if it's the first run on your system.

**Comment by GoldenAngel1997** [comment]
@kisak-valve 
Uninstalling of steam / dependencies, whether through a package manager [synaptic] and/or terminal. Screen now decided to freeze up, after that "client-download.steampowered.com/client/steam_client_ubuntu_12" file was mentioned being downloaded [+ 2 cores stuck at 100%]

**Comment by GoldenAngel1997** [comment]
@kisak-valve 
"Uninstalled Manifest" error also present, under Manjaro Linux [constant, repeatable, morale sinking]

**Comment by kisak-valve** [comment]
Hello @GoldenAngel1997, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
