### ISSUE TITLE
Text size is too small on HDPI Screens on Linux

### ISSUE THREAD

**Issue by Crushless** [ValveSoftware/steam-for-linux#7321]
#### Your system information

* Steam client version: (build number or date): 1596217132
* Distribution (e.g. Ubuntu): Arch (Manjaro)
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Font size is much too small to be read on small screens with high resolutions. My Notebook has an 15" Screen with 4K resolution, and the steam client is almost unusable, because all text is much too small.
As an side note, I use prime-run to start steam, because my notebook has Nvidia/Intel hybrid graphics, but the problem also exists when starting steam on the Intel chip.
I tried the "Enlarge text and icons based on monitor size" setting, but it has no effect.
The tip to use "GDK_SCALE=2 steam" does also have no effect.
And to use alternative skins from unknown sources, to correct a simple bug that should be fixed in the application, is also a no-go.
**Please add an option to set the GUI scale factor in the steam settings panel.**
There were multiple open issues about this bug in the past, but they were simply closed, and after years its still not solved. So **please** fix this finally.

#### Steps for reproducing this issue:
1. Get a small HDPI monitor
2. Open steam
3. Look at the text

**Comment by kisak-valve** [comment]
Hello @Crushless, this issue is already being tracked at #6125 / #5460 / #7020. Closing in favor of the existing issue reports.
