### ISSUE TITLE
Streaming client with remote play crahes  when using NVIDIA PRIME Render Offload

### ISSUE THREAD

**Issue by rcano** [ValveSoftware/steam-for-linux#7322]
#### Your system information

* Steam client version (build number or date): aug 6 2020, 22:00:53
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
When using remote play to stream games from a host  pc to a client one, it crashes 1-2 seconds after launching on the client machine when using Nvidia prime render offload (on-demand profile option)

Tried launching steam with __NV_PRIME_RENDER_OFFLOAD=1 and __GLX_VENDOR_LIBRARY_NAME=nvidia and the issue still persist. The last log line on the console is an error regarding ffmpeg:

```
ffmpeg error: VDPAU device creation on X11 display :0 failed.
CVDPAUAccel: av_hwdevice_ctx_create() failed
ffmpeg verbose: Opened VA display via X11 display :0.
ffmpeg verbose: Initialised VAAPI connection: version 1.7
ffmpeg verbose: Unknown driver "Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()", assuming standard behaviour.
VAAPI hardware decoding
ffmpeg verbose: Reinit context to 1536x864, pix_fmt: vaapi_vld
CVAAPIAccel: vaPutSurface() failed: unknown libva error
```

System settings
CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
GPU: GeForce RTX 2070 Mobile

#### Steps for reproducing this issue:

1. Select Prime profile Nvidia On-Demand
2. Select "Enabled Hardware decoding" in steam remote play client options
3. Select "stream" for a given game using remote play

The client will open shortly (you can hear sound for a brief sec) before it crashes and closes up.

**Comment by kisak-valve** [comment]
Hello @rcano, are you still experiencing this issue on an up to date system?

**Comment by rcano** [comment]
ugh... this bug report is so old, than in the mean time it was fixed and re-broken at least 3 times :sweat_smile:. Currently the, the steam beta client as well as mainstream client both work properly for remote play together under ubuntu 22.04

**Comment by bhallionOhbibi** [comment]
I'm also experiencing the same issue this morning after the latest update.
Worked fine yesterday
