### ISSUE TITLE
Embedded Browser in Update Window is Always Black Until Clicked

### ISSUE THREAD

**Issue by 3vi1** [ValveSoftware/steam-for-linux#7324]
System information

* Steam client version (build number or date):  Built Aug 17 2020, at 20:27:57, pkg version 1597803079
* Distribution (e.g. Ubuntu): Ubuntu running KDE Plasma Desktop
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

The embedded browser in the Steam update notification windows (and only there) always appear to be black like so: [https://i.imgur.com/UBK4ngp.png](https://i.imgur.com/UBK4ngp.png).  Clicking in the update window refreshes it so that it displays properly:  [https://i.imgur.com/bBkJ9h8.png](https://i.imgur.com/bBkJ9h8.png).  There are no discernible errors in any system log.

This consistently happens or has happened on every (4+) system I've owned for years now (laptops, desktops, all Ubuntu - any version up to and including 20.10 beta, most using KDE desktop, with nVidia graphics: from 960 up to 2070 series using the current/latest nVidia proprietary drivers from the graphics team PPA).  So I expect it must be a very common issue, but the only existing open problems I've found where about people having black screens with the browsers in other areas of the app which all work fine for me (no issues browsing store, community, etc.).  

I have plenty of other browsers/apps using embedded chromium on these computers, and they do not exhibit this problem - even though they have hardware acceleration enabled; this is only occurring with Steam's update notification window.

#### Steps for reproducing this issue:

1. Wait for an update to the steam client (this happens consistently on every update).
2. Note that update information is black (https://i.imgur.com/UBK4ngp.png).
3. Clicking anywhere in the black area causes it to be redrawn properly.

**Comment by kisak-valve** [comment]
Hello @3vi1, this issue is already being tracked at #6451. Closing as a duplicate.
