### ISSUE TITLE
What's New section has vanished

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#7330]
#### Your system information

* Steam client version (build number or date): August 20
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For the last 3-4 days, the What's New section in my Steam Library has vanished. There's no dedicated setting for it and I haven't gone and tweaked anything to remove it. I am thoroughly confused. There's hundreds I'm following and plenty constantly have news, it's just not there.

Here's a full startup log, don't know if it helps: https://gist.github.com/LiamDawe/31fb3fbdd590aeda71ba8f8476075e16
System info too: https://gist.github.com/LiamDawe/5d68074e189b39056a29d90114e03666

**Comment by monterrr** [comment]
Also happened to me, this is so bad...

**Comment by rufusw** [comment]
I had this problem and found a solution here https://steamcommunity.com/groups/SteamClientBeta/discussions/0/2793874853442543964/

SOLUTION:
Steam -> Settings
Web Browser (left side)
Delete Web Browser Cache
Delete all Browser Cache
Restart

I am on Windows 10 so not Linux specific

**Comment by monterrr** [comment]
@rufusw That worked like a charm on Linux, thanks!

**Comment by kisak-valve** [comment]
Hello, in anyone still experiencing this issue on an up to date system?

**Comment by andreldmonteiro** [comment]
Never saw the problem again.

**Comment by kisak-valve** [comment]
Closing as outdated.

**Comment by TechMan122002** [comment]
Just had this happen to man ive tryed to use the meteds descused here but they have updated the client since these posts so idk how to fix the issue.
