### ISSUE TITLE
Steam Remote Play - Client crashes frequently - Streaming client exited unexpectedly (2)

### ISSUE THREAD

**Issue by ChrisWNY** [ValveSoftware/steam-for-linux#7331]
#### Your system information

* Steam client version (build number or date): Aug 20 15:49:29
* Distribution (e.g. Ubuntu): Windows 10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Host system: 
Graphics: AMD RX 590
CPU: AMD Ryzen 3700x
48GB DDR4 RAM

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Launch Dolphin 5.0-12247 via steam Remote Play from laptop (Windows 10)
2. Launch Metroid Prime 2, allow to run for awhile
3. Streaming client exited unexpectedly (2) - happens frequently - clicking "stream" gets the remote stream back up and running again

No details of crash in streaming_client.exe.log pointing to errors, etc. 

[streaming_client.exe.log](https://github.com/ValveSoftware/steam-for-linux/files/5115489/streaming_client.exe.log)

**Comment by kisak-valve** [comment]
Hello @ChrisWNY, this issue tracker is primarily intended for the Steam for Linux client.

Please use [Steam Support](https://help.steampowered.com/) for issues with the Windows client.
