### ISSUE TITLE
Dualshock 4 unrecognized by big picture mode

### ISSUE THREAD

**Issue by hikagura99** [ValveSoftware/steam-for-linux#7332]
#### Your system information

* Steam client version (build number or date): 1596217132
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed 
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
I changed from official repos to flatpak version of steam since i had some problems with proton, which have been solved, but the client doesn't recognize my DS4 anymore, both if plugged via cable or via bluetooth.

#### Steps for reproducing this issue:

1. Open Big Picture mode
2. Turn on controller
3. Try to configure it (No controller found message pops up)
![Screenshot_20200824_160643](https://user-images.githubusercontent.com/64305290/91183836-3db27f80-e6ec-11ea-9642-cdcf36ad666b.png)

**Comment by lavadrop** [comment]
Tt won't work, flatpak is sandboxed. You have to use the distro package to access hardware.

**Comment by kisak-valve** [comment]
Hello @hikagura99, are you still experiencing this issue on an up to date system? It looks like you're responsible for providing the [steam-devices](https://github.com/ValveSoftware/steam-devices) udev rule set if you're not using a Steam system package that would provide it. (From https://github.com/flathub/com.valvesoftware.Steam/wiki#my-controller-isnt-being-detected)

**Comment by kisak-valve** [comment]
Closing pending feedback.
