### ISSUE TITLE
PDP Wired Fight Pad Pro for Nintendo Switch not recognized

### ISSUE THREAD

**Issue by tailkinker** [ValveSoftware/steam-for-linux#7341]
#### Your system information

* Steam client version (build number or date): 31 July 2020
* Distribution (e.g. Ubuntu): XUbuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

 My PDP Wired Fight Pad Pro for Nintendo Switch is not at all recognized by Steam. This is Vid 0x0e6f:0x0185, which is on the supported controller database as being supported. I am running steam client built on July 31 2020 on Linux (XUbuntu 20.04). My PC is a custom-built Core i7 desktop with 12GB of RAM, and the game pad is completely recognized by the operating system.

#### Steps for reproducing this issue:

1. Purchase the controller
2. Plug it in
3. Test controller using jstest, verify it using lsusb, test it in many pieces of software (where it works flawlessly).
4. Controller does not show up in Steam.

**Comment by gmmarconi** [comment]
I have the same issue on Pop!_OS 20.10

I noticed that it gets recognized by some games, however the buttons are all scrambled and the game lets me remap only a subset of the buttons (i.e. I cannot remap the "+" button which in the scrambled version is mapped to "A" button).

I tried to make it pass as an xbox360 controller with xboxdrv but it looks like this controller is not supported by xboxdrv.

Does anyone have a workaround for this?

**Comment by theGiallo** [comment]
I've found that you can create this file and then Steam sees it. I've adapted it from the one for the pro controller here https://wiki.archlinux.org/index.php/Gamepad#Nintendo_Switch_Pro_Controller_and_Joy-Cons

```
/lib/udev/rules.d/70-steam-controller.rules
```
```
KERNEL=="hidraw*", ATTRS{idVendor}=="0e6f", ATTRS{idProduct}=="0185", MODE="0660", TAG+="uaccess"
```

**Comment by kisak-valve** [comment]
Hello @tailkinker, are you still experiencing this issue on an up to date system? theGiallo's udev rule was added to the steam-devices udev rule set about two years ago.

**Comment by kisak-valve** [comment]
Closing as fixed.
