### ISSUE TITLE
Mouse "jumps" during remote play rather than move smoothly.

### ISSUE THREAD

**Issue by TheExplodingPixel** [ValveSoftware/steam-for-linux#7345]
#### Your system information

* Steam client version (build number or date): 
September 2, 2020, at 22:14:42
* Distribution (e.g. Ubuntu): 
Arch Linux
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
During a remote play session, the mouse input from the client is seemingly sent to the host in a jumpy manner, rather than a smooth movement. This occurs when using my window manager, dwm, as well as steamos-compositor-plus. This makes it impossible to play many games. Both client and host are on Arch Linux. It isn't visible on the client, but you can see it in game from the camera movement and the host's monitor(s).
#### Steps for reproducing this issue:
 
1. Launch a remote play session for any game, with both linux host and client.
2. Move mouse.
3. It may be best to view this in a game with mouse camera controls.

(I know yis didn't want smooth locomotion, but I'd like it for my mouse :p)

**Comment by TheExplodingPixel** [comment]
Okay, just after doing this, I checked again, and of course, it worked perfectly. I'll reply if this happens again.

**Comment by kisak-valve** [comment]
Closing as this appears to be a non-reproducible one-off occurance.

**Comment by alex9099** [comment]
I still have this happen on cachyOS with a 1080ti on the server and arch 
Game i tried is rust, on the map or just dragging things on the inventory, it moves all over the place
I'm with steam client beta on both client and server (stable version has the same behavior)
@kisak-valve
