### ISSUE TITLE
Shows option to create a library on /boot/efi

### ISSUE THREAD

**Issue by Liemaeu** [ValveSoftware/steam-for-linux#7346]
Ubuntu 18.04 (Steam is up-to-date, stable version)

I recognized, that when I install a game it shows me an option to create a library on /boot/efi. This should not be displayed (the EFI-partition is not for games, wouldn't work because of missing writing-writes anyways) and it would be great if Steam could detect the /boot/efi-partition as EFI-partiton and not displaying the option to create a games library on it.

**Comment by kisak-valve** [comment]
Hello @Liemaeu, this issue is already being tracked at #3414. Closing as a duplicate.
