### ISSUE TITLE
Error libc.so.6 Fedora 32

### ISSUE THREAD

**Issue by kurotom** [ValveSoftware/steam-for-linux#7347]
Steam client version: 1.0.0.66-1.fc32
Distribution: Fedora 32 5.8.4-200.fc32.x86_64
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

Error:
> Running Steam on fedora 32 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> Error: You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6
> Steam client's requirements are satisfied
> /home/UsuariO/.local/share/Steam/ubuntu12_32/steam

Yesterday before updating the OS I could play, and after updating I can't use Steam.

1. Fedora 32 built-in application finder.

2. I get the error:
> Running Steam on fedora 32 64-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> Error: You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6
> Steam client's requirements are satisfied
> /home/UsuariO/.local/share/Steam/ubuntu12_32/steam

Help me, please.

**Comment by kisak-valve** [comment]
Hello @kurotom, looks like [`glibc.i686`](https://www.rpmfind.net/linux/RPM/fedora/32/x86_64/g/glibc-2.31-2.fc32.i686.html) provides 32 bit libc on Fedora, please verify that this package is installed.

**Comment by kurotom** [comment]
I have it installed.
# rpm -qa | grep -i glibc | grep -i i686
> glibc-2.31-4.fc32.i686
> glibc-devel-2.31-4.fc32.i686

**Comment by kurotom** [comment]
I was able to fix the problem, from the thread (I don't know how to link on github).
But the url works.

> https://github.com/ValveSoftware/steam-for-linux/issues/5957

In summary:

  1.-  Open the console.
  2.-  steam --reset
  3.-  Enter account and use steam,  : D

Thanks for the help me, keep it up,  : D

**Comment by kisak-valve** [comment]
Glad to hear you got the Steam client working.

Unfortunately, there's not a clear connection between the symptoms and the workaround to figure out what had happened here and the test case is now gone, so I'm going to close this for now.

**Comment by stsp** [comment]
> happened here and the test case is now gone, so I'm going to close this for now.

I have the same problem, and if you
want to test something, I can wait before
doing `steam --reset`.
