### ISSUE TITLE
Unstable Steam operation, constant Dota 2 checks and shader cache updates

### ISSUE THREAD

**Issue by alexeysvrv** [ValveSoftware/steam-for-linux#7348]
#### Your system information

* Steam client version (build number or date): 1599174997
* Distribution (e.g. Ubuntu): Manjaro 20.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Hello dear support. Recently I wanted to play Dota 2 on my computer. I went in, found a rated match, and as soon as I started playing, the game froze. I had to close Dota. As soon as I closed it, I wanted to start it right away, but some kind of check went. It lasted 7-8 minutes. In Dota, by the way, you are given 5 minutes to reconnect, and then it is thrown into low priority. I didn't have time, because of the steam. During this check, I was downloading some kind of shader cache. It took about 530 MB. The only problem is that with the latest client updates, the download speed is often terrible. Units of kilo, ayte per second, although my maximum download speed was 1.1 MB / s. (I have 10 MB / s Internet). What's with Steam? Why is the speed problem? Why should I, due to technical problems, get banned from the game and get low priority? Please fix these download speed bugs and get me out of low priority in Dota. And by the way, almost every time I enter the game, the Vulkan shaders are updated before launching. This is very annoying. How can I disable this? Thank you

#### Steps for reproducing this issue:

1. Go to Dota, find a match, catch a RANDOM freeze.
2. Close the pillbox by killing the process (using ALT + F4, through the task manager and other standard means it does not work)
3. Wait until the Dota check passes in the incentive, the shader cache is loaded(the speed is random, but usually now the first few minutes are very low - units of kilobytes per second) and the Vulcan shaders are updated
Reproducing the problem can be a very tricky task, since freezes in DotA are rare and the shader cache does not always need to be loaded.

**Comment by kisak-valve** [comment]
Hello @alexeysvrv, sounds like Steam's Shader Pre-caching is giving you trouble. This feature is completely optional and can be configured in Steam's Settings at `Steam` -> `Settings` -> `Shader Pre-Caching`.

**Comment by alexeysvrv** [comment]
@kisak-valve Perhaps, but is it possible to optimize this process so that it takes less time? In a recent Steam update, the issue of excessive resource consumption was resolved. Thanks for this. However, pre-caching takes a very long time. I understand that this feature is optional, but it should improve the performance and stability of the game.
Also, you can please check Steam for stability of download speed. Previously, this was not the case and there was always the maximum speed (which allows the Internet channel)

**Comment by rkozlo** [comment]
I have problem similiar like this. It's not about downloading, but about processing them. Turn off the game, and it starting again. It is terrible slow.

**Comment by kisak-valve** [comment]
Hello @alexeysvrvm, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
