### ISSUE TITLE
Steam unable to detect more than one Dualshock 4 controller

### ISSUE THREAD

**Issue by clementchiew95** [ValveSoftware/steam-for-linux#7349]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Endeavour OS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

<details><summary>System Infomation</summary><p>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2526 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "EndeavourOS Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.8.5-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12009000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime_0.20200720.0

Video Card:
    Driver:  X.Org AMD TAHITI (DRM 2.50.0, 5.8.5-arch1-1, LLVM 10.0.1)
    Driver Version:  4.5 (Compatibility Profile) Mesa 20.1.7
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18.78" x 10.55" (21.54" diag)
                                            47.7cm x 26.8cm (54.7cm diag)
    Primary VRAM: 3072 MB

Sound card:
    Audio device: Realtek ALC662 rev3

Memory:
    RAM:  7916 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Total Hard Disk Space Available:  28044 Mb
    Largest Free Hard Disk Block:  9693 Mb
```

</p></details>

#### Please describe your issue in as much detail as possible:
Both my Dualshock 4 controllers pair fine via Bluetooth and works with my non-Steam games, ie: 2P multiplayer works fine. 

Steam only actively detects one of them at any time. The second one just gets ignored. I'm unable to play multiplayer with both DS4 controllers together. When the "active" controller is disconnected, the "idle" controller gets detected immediately after. When detected, controller configs work fine. 

I've added udev rules to detect the DS4 controllers, they don't get detected at all otherwise.

#### Steps for reproducing this issue:

1. Pair both DS4 controllers and connect both of them.
2. Test 2P multiplayer with non-Steam games. 
3. Open Steam
4. The corner pop-up for controller should appear once.
5. Open Steam Controller menu. DS4 detection should be active. Only one DS4 controller is present.

**Comment by clementchiew95** [comment]
Please refer to Steam ticket https://help.steampowered.com/en/wizard/HelpRequest/HT-G9H3-36WW-59GB for minidump and stuff.

**Comment by kisak-valve** [comment]
Hello @clementchiew95, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
