### ISSUE TITLE
Steam guard in big picture cannot enter code no imput field

### ISSUE THREAD

**Issue by 200Puls** [ValveSoftware/steam-for-linux#7351]
#### Your system information

* Steam client version (build number or date):
Steam beta
* Distribution (e.g. Ubuntu): 
Gamer-os / arch
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I removed my steam machine from the trusted devices so that I have to enter the steam guard code again. 
Unfortunately I cannot enter the code as no input field is rendered in bpm.
#### Steps for reproducing this issue:

1. Remove steam machine from trusted devices 
2. Next system start shows pop-up "you need to enter validation code" mail gets sent
3. After pressing "OK" there is nothing rendered no input field just blue background and select and done at the bottom

**Comment by BrianRamsay** [comment]
This just happened to me as well. Disabled steam guard, so my computer is no longer trusted. But big picture mode just shows a blue screen with no options, and I can't exit Big Picture mode

**Comment by kisak-valve** [comment]
Hello, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
