### ISSUE TITLE
Steam crashes a few minutes after launching on linux

### ISSUE THREAD

**Issue by dlitvak98** [ValveSoftware/steam-for-linux#7352]
#### Your system information

* Steam client version: `1.0.0.66-1`
* Distribution: Manjaro Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes from anywhere between a minute and ten minutes after launching and logging in. A workaround is to launch steam in offline mode.

The relevant parts of the logs and crash dump seem to be the following:

[steam.log](https://github.com/ValveSoftware/steam-for-linux/files/5195334/steam.log)
```
assert_20200909115923_1.dmp[131595]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200909115923_1.dmp
/home/dlitvak98/.local/share/Steam/steam.sh: line 750: 128324 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20200909115923_1.dmp[131595]: Finished uploading minidump (out-of-process): success = yes
assert_20200909115923_1.dmp[131595]: response: CrashID=bp-1484ef98-9554-4ff2-b46b-347b02200909
assert_20200909115923_1.dmp[131595]: file ''/tmp/dumps/assert_20200909115923_1.dmp'', upload yes: ''CrashID=bp-1484ef98-9554-4ff2-b46b-347b02200909''
```

**Dump:**
```
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):/data/src/common/pipes.cpp:766
```

#### Steps for reproducing this issue:

1. Be on Manjaro Linux
2. Launch Steam in offline mode
3. Wait for a few minutes

**Comment by kisak-valve** [comment]
Looks like Steam is having an issue with networkmanager and/or dbus.

These are unusual:
`(steam:128324): libnm-glib-WARNING **: 11:59:44.196: Error in get_property: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/Devices/2545`

`(steam:128324): libnm-glib-WARNING **: 11:59:44.240: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/2547: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/Devices/2547`

**Comment by dlitvak98** [comment]
Alright, any idea how I could go about debugging this? In the time it takes steam to crash, `dbus-monitor` logs about 13000 lines that I don't really understand.

**Comment by dlitvak98** [comment]
I figured it out after looking over #3959 

Turns out, I had a docker container that was constantly restarting, a comment in this other issue goes into more detail
