### ISSUE TITLE
F1 2020 cannot start most of the time, but sometimes it starts and then works well

### ISSUE THREAD

**Issue by patkoscsaba** [ValveSoftware/steam-for-linux#7353]
#### Your system information

* Steam client version (build number or date):  September 3, 2020, at 21:18:20
* Distribution (e.g. Ubuntu): OpenSuse
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Today I bought and installed F1 2020. I checked Proton DB and the recommended startup parameters. Immediately after the install the game started, no issues, with "PROTON_USE_SECCOMP=1 %command%" and by choosing DX 11. I played for about half an hour, no issues (other than the small known ones).
Then I quit the game.
When I wanted to start it again, nothing happened. More specifically, the DX dialog appears, I choose DirectX 11, then in the library in Steam the game appears as "Running", but after about 10 seconds there is a small flicker on the screen and then nothing. The Play button activates again.
Here is the output from Steam client when the game FAILS to start: https://gist.github.com/patkoscsaba/ddfe2cc80f5a0fb9656ef1c8d51b4b8c
However, if I continue trying to start the game, sometimes, about once every 20 or so tries, it starts again. When it starts the Steam client output is this: https://gist.github.com/patkoscsaba/7f6d08934f4325d3bf9efa0df574b54f

Things I tried, none if these have any effect:
1. reboot computer
2. restart Steam client
3. add / remove the "PROTON_USE_SECCOMP=1 %command%" options. Sometimes the game start with the SECCOMP option, sometimes without. Performance is the same either way. Having this option doesn't seem to produce any effect on the startup issue.
4. reinstall game. More specifically, uninstall game, remove any remaining files and the whole F1 2020 folder, install the game again. After reinstall, it did not start at all for the first 10 or so tries.
5. disable/enable Steam overlay

#### Steps for reproducing this issue:

1. Install Game
2. Start, then quit the game. It doesn't matter how long do you use the game. Just enter main menu and choose quit.
3. Try starting the game again from Steam client.

I am willing to provide any additional information that may help. Just let me know what exactly and how to obtain the information (ie. run steam in debug mode or something).

**Comment by kisak-valve** [comment]
Hello @patkoscsaba, we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues). Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4047#issuecomment-689604482.

**Comment by patkoscsaba** [comment]
Thanks for the clarification and help.
