### ISSUE TITLE
why are all of the games colors inverted

### ISSUE THREAD

**Issue by rivermansmankid** [ValveSoftware/steam-for-linux#7354]
So whenever i start a steam game all of the colors are inverted and i have tried to do everything
i upgraded my gpu
i reinstall my games
i verified my games
i have done everything please help

**Comment by cakesale** [comment]
You haven't provided much info to work off of.
What are your system specs and distro etc?

**Comment by kisak-valve** [comment]
Closing due to a lack of usable info. In general, rendering issues with games should be reported to the video driver vendor.
