### ISSUE TITLE
libsystemd.so.0 hard dependency

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#7355]
* Steam client version (build number or date): Sep 9 2020
* Distribution (e.g. Ubuntu): Obarun
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System Information: https://gist.github.com/shoober420/151b6c85ff8f4100a450b846aef17ff4

Steam apparently has a hard dependency for libsystemd.so.0, which is rather odd, considering Steam shouldnt rely on a certain init system, given the numerous alternatives to init systems. Please drop the hard dependency for libsystemd.so.0 in favor of people who use other init systems like OpenRC and s6.

**Comment by kisak-valve** [comment]
Works for me with Gentoo/OpenRC with or without the Steam runtime enabled and libsystemd.so.0 isn't installed anywhere on the test system. You've loaded up some system library that links against libsystemd.so.0 and blamed it on Steam.

**Comment by kisak-valve** [comment]
Unrelated to Steam, consolekit has been phased out of production use in Gentoo portage and elogind is the easy replacement to support the login manager / desktop environment. Yes, that test box uses that these days.

**Comment by shoober420** [comment]
Could you please check your “/usr/lib32” directory for the “libsystemd.so.0” file? elogind on some distros will bundle it. I know Artix does.

**Comment by shoober420** [comment]
@kisak-valve 
Nevermind, I got it. Some packages, like lib32-libpulse in the official Arch repos does have a dependency on systemd. When I used the Artix versions of lib32-libpulse, it worked perfectly. Thank you very much for the help good sir.
