### ISSUE TITLE
Remote Play Together Client Controller not detected

### ISSUE THREAD

**Issue by hermpes** [ValveSoftware/steam-for-linux#7357]
#### Your system information

* Steam client version (build number or date):  Sep 3, 2020
* Distribution (e.g. Ubuntu): Mint 20
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While hosting, the client (Windows 10) controller was not detected. This issue also exists if the windows machine is hosting, the linux client's controller is not detected. 

Both machine's controllers are detected if they are the host. 

#### Steps for reproducing this issue:

1.  Host game with Linux Host and Windows Client or Windows Host and Linux Client

**Comment by kisak-valve** [comment]
Hello @hermpes, this issue is already being tracked at #6951, so I've transferred this issue to https://github.com/ValveSoftware/steam-for-linux/issues/6951#issuecomment-690839332. Closing as a duplicate.
