### ISSUE TITLE
Steam & Xinerama after last update

### ISSUE THREAD

**Issue by SpheriX** [ValveSoftware/steam-for-linux#736]
![1](https://f.cloud.github.com/assets/228526/79181/49932f7c-61a5-11e2-91f2-29af3c5c7331.jpeg)
![2](https://f.cloud.github.com/assets/228526/79184/51df23d4-61a5-11e2-9802-3a48810c5a7e.jpeg)
![3](https://f.cloud.github.com/assets/228526/79185/55c6a6de-61a5-11e2-81ea-9a56a5906f83.jpeg)
![4](https://f.cloud.github.com/assets/228526/79186/599a67a0-61a5-11e2-985e-488fa758b38e.jpeg)
![xinerama](https://f.cloud.github.com/assets/228526/79187/5d7b7c10-61a5-11e2-9369-5b48177884ec.jpeg)

**Comment by kisak-valve** [comment]
Hello @SpheriX, are you still experiencing this issue on an up to date system?

**Comment by SpheriX** [comment]
I do not use xinerama now.  So i don't know is this issue actual or not.

29.03.2017 18:30, kisak-valve пишет:

**Comment by kisak-valve** [comment]
Thanks for the feedback @SpheriX. I have not seen this issue on my dual monitor system. If anyone happens across this issue on an up to date system, please open a new issue report and we can investigate further.

Closing.
