### ISSUE TITLE
Steam fails to start: Failed to load steamui.so - dlerror(): /lib/x86_64-linux-gnu/libpng12.so.0: Cannot read file: is a directory

### ISSUE THREAD

**Issue by baschi29** [ValveSoftware/steam-for-linux#7360]
#### Your system information

* Steam client version (build number or date): 12.09.2020
* Distribution (e.g. Ubuntu): Kubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is unable to start. I tried installing via apt and via the download from the steam website.

First there is the following error popping up:
```
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
```

Steam itself throws the following error:
`Failed to load steamui.so - dlerror(): /lib/x86_64-linux-gnu/libpng12.so.0: Cannot read file: is a directory`
(I translated the last part from german: Kann die Datei-Daten nicht lesen: Ist ein Verzeichnis)

I tried various fixes from the internet regarding libc.so.6, but I have all dependencies installed. Libpng12-0 is also installed.

I can provide further information if needed. I hope somebody can help me out with this.

#### Steps for reproducing this issue:

1. Install steam via apt or the steam website on kubuntu 20.04
2. Try to start steam

**Comment by kisak-valve** [comment]
Hello @baschi29, can you check if the `libc6-i386` package is installed on your system with something like `apt policy libc6-i386` and install it with `sudo apt install libc6-i386` if it isn't already.

**Comment by baschi29** [comment]
Hey,

libc6-i386 is installed.

There actually is a libpng12.so.0 directory under /lib/x86_64-linux-gnu/. Weird.

Ther also is a file called libpng12.so.0.54.0 (which is correct I suppose?)

I couldn't find a package the directory belongs to. It is empty nonetheless, so I decided to delete it. After that steam started working again.

I suppose something was very (as in very very) off with my Linux installation. I will close this issue for the time being.

Thanks for your help!
