### ISSUE TITLE
Steam crashes when launching a non-Steam Windows game with Proton

### ISSUE THREAD

**Issue by alkazar** [ValveSoftware/steam-for-linux#7361]
#### Your system information

* Steam client version (build number or date): Sep 10 2020, at 05:50:00 
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Launching a non-Steam Windows game with Proton crashes the Steam beta client.
This same action works after switching back to the non-beta Steam client (build date: Sep 3, 2020, at 21:18:20).
Only the Steam Beta client is affected.

#### Steps for reproducing this issue:

1. Update to latest Steam client beta
2. Add a non-Steam Windows game to Steam
3. Set the game to launch with Proton
4. Launch the game

Expected result: the game starts
Actual result: the game doesn't start and Steam crashes

##### Crash Log:
```
GameAction [AppID 4182879723, ActionID 1] : LaunchApp changed task to UpdatingAppTicket with ""

(steam:245438): Gtk-WARNING **: 17:56:06.844: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1599861500)
Opted-in Controller Mask for AppId 4182879723: 0
GameAction [AppID 4182879723, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 4182879723, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 4182879723, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 4182879723, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/data/src/clientdll/compatmanager.cpp (429) : Assertion Failed: pApp != nullptr
/data/src/clientdll/compatmanager.cpp (429) : Assertion Failed: pApp != nullptr
Installing breakpad exception handler for appid(steam)/version(1599861500)
No minidump written, nothing to upload.
No minidump written, nothing to upload.
~/.local/share/Steam/steam.sh: line 750: 245438 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

**Comment by sizeofbool** [comment]
Same issue here on Debian 10.
Non-Steam game was working fine using Proton, before latest Steam Client beta update was installed.
If I try to launch the game now it doesn't start and crashes Steam Client completely.

**Comment by dpanter** [comment]
Same here, Siduction (Debian sid based) using the beta client and Proton 5.0 next (proton-5.0-10-rc4)
Intel 8700k, kernel 5.8.9, KDE 5.17.5, Nvidia 1080ti 450.66
```
GameAction [AppID 4083467065, ActionID 1] : LaunchApp changed task to UpdatingAppTicket with ""

(steam:271726): Gtk-WARNING **: 21:27:30.630: gtk_disable_setlocale() must be called before gtk_init()

(steam:271726): GLib-CRITICAL **: 21:27:30.630: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed
Loaded Config for Local Override Path for App ID -211500231, Controller 0: /home/panther/.local/share/Steam//controller_base/empty.vdf
GameAction [AppID 4083467065, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 4083467065, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 4083467065, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 4083467065, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/data/src/clientdll/compatmanager.cpp (429) : Assertion Failed: pApp != nullptr
/data/src/clientdll/compatmanager.cpp (429) : Assertion Failed: pApp != nullptr
Installing breakpad exception handler for appid(steam)/version(1599861500)
assert_20200915212735_29.dmp[272136]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200915212735_29.dmp
assert_20200915212644_1.dmp[272140]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200915212644_1.dmp
/home/panther/.local/share/Steam/steam.sh: line 750: 271726 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```
[Steam system info](https://gist.github.com/dpanter/a8130403990a1be01c66313f4270acea)
[Dump files](https://github.com/ValveSoftware/steam-for-linux/files/5227296/dumps.zip)

**Comment by HyperEye** [comment]
I have this issue as well. Non-steam games were working great in Proton until very recently. Opting out of the beta and allowing the Steam client to be downgraded does resolve the problem.

**Comment by TTimo** [comment]
Next beta update (> Sep 10) will address this.

**Comment by HyperEye** [comment]
I received an update last night that appears to have resolved this issue.

**Comment by dpanter** [comment]
Confirmed, non-Steam games launch now and seem to work properly.

**Comment by alkazar** [comment]
I can also confirm that this issue is fixed in the latest Steam client beta.

**Comment by kisak-valve** [comment]
Thanks for testing. Closing as fixed.
