### ISSUE TITLE
Steam Client kill process when closed via Gnome Shell

### ISSUE THREAD

**Issue by Megamiun** [ValveSoftware/steam-for-linux#7362]
#### Your system information

* Steam client version (build number or date): `Sep  3 2020, at 21:18:20`
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When I click on the close button on Gnome Shell, the Steam processm and games being run, are closed. When I click on the close on the window, the process only goes to the background.

Please correct this, closing via Gnome Shell should not close the process. It doesn't close the process with Telegram and other apps 

#### Steps for reproducing this issue:

1. Open Gnome Shell(via super key or hot corner)
2. Click the x button on Steam
3. Steam will close

![Screenshot from 2020-09-13 13-01-46](https://user-images.githubusercontent.com/7376453/93028495-ace40b00-f5ea-11ea-91ea-60baa2950677.png)

**Comment by kisak-valve** [comment]
Hello @Megamiun, this issue is already being tracked at #2685. Closing as a duplicate.

**Comment by Megamiun** [comment]
Hi, @kisak-valve, are there any plans on correcting this? More than one time I lost connection when playing with friends because I went to close the friends window.
