### ISSUE TITLE
Steam not re-downloading a removed Proton version

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7365]
#### Your system information

* Steam client version (build number or date): Sep 3 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I accidentally removed an older Proton version (4.11-13) set for a given game. Steam is not downloading the version again when I try to launch the game. 

#### Steps for reproducing this issue:

1. Remove any Proton version
2. Launch a game associated with the removed Proton version

**Comment by kisak-valve** [comment]
Hello @ranplayer, in Steam, go to your Library, search for Proton, and go to the game-specific properties for Proton 4.11.  From there you should be able to go to the Local Files tab and `Verify integrity of tool files...`.

Does that resolve your issue?

**Comment by ranplayer** [comment]
It worked ! Thanks @kisak-valve
