### ISSUE TITLE
Scrollbars get stuck in scrolling state.

### ISSUE THREAD

**Issue by Okxa** [ValveSoftware/steam-for-linux#7369]
#### Your system information

* Steam client version (build number or date): 1599861500
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

.

* Desktop: Xorg with openbox as Window Manager

#### Please describe your issue in as much detail as possible:

Scrollbars get stuck in scrolling state if mouse down is released outside the window.

Then when mouse is brought back in to the window, the view shifts.

Scrollbar can be resetted by clicking it.

#### Steps for reproducing this issue:

1. Click and hold on a scrollbar on Friends list/Library
2. Drag the view down/up with the scrollbar
3. Move the mouse cursor outside of the window, while still holding down primary mouse button.
4. Release primary mouse button to end drag.
5. Move mouse back in window to see the view jump

#### More info

This bug has been reported at [Steam Client Beta Steam Group](https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3166519278498578811/) 11 Oct, 2019

**Comment by kisak-valve** [comment]
Hello @Okxa, this issue is already being tracked at #4231. Closing as a duplicate.

**Comment by kokoko3k** [comment]
It affects me since ages and i tought it was just me.
I'm still affected, using kde.
