### ISSUE TITLE
Slow Speeds on Steam Link - Ubuntu

### ISSUE THREAD

**Issue by mastralan5** [ValveSoftware/steam-for-linux#7371]
Hi. I am not getting even moderately acceptable speeds from my Steam Link while running Ubuntu. I connect the two computers in my basement to the Link, a Laptop that is Dual Booting Windows 7 and Ubuntu 18.04, getting test speeds of 10Mbps on Windows and 5Mbps on Linux, and a Desktop Dual Booting Windows 10 and Ubuntu 20.04, getting test speeds of 30Mbps on Windows and 3Mbps on Linux. Basically, only the Desktop's Windows 10 is acceptably functional through the device. Wondering if there was a fix for this, or if I should look into getting rid of it. Most of my games are on Linux. Not to experienced a coder but could copy terminal line by lines or follow moderately advanced instructions.

**Comment by kisak-valve** [comment]
Hello @mastralan5, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
