### ISSUE TITLE
Steam client segfault on Ubuntu 18.04

### ISSUE THREAD

**Issue by lkomage** [ValveSoftware/steam-for-linux#7373]
#### Your system information

* Steam client version (build number or date):  Startup - updater built Sep 10 2020 05:49:50
* Distribution (e.g. Ubuntu): Ubuntu 18.04 64bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After a recent system update, Steam client no longer runs. CLI output of failed run is attached. Also attaching a minidump from the crash.

#### Steps for reproducing this issue:
Unsure of steps, happened after system update. Client no longer runs; segfaults.
[Steamcrash.txt](https://github.com/ValveSoftware/steam-for-linux/files/5264503/Steamcrash.txt)
[assert_20200922191110_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/5264509/assert_20200922191110_1.zip)

**Comment by kisak-valve** [comment]
Hello @lkomage, your log has `libGL error: failed to load driver: swrast`. Swrast is mesa's slower software renderer. The fact Steam is trying to use it and failing hints that you're using the nvidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you verify this is the case and check video driver version you're using? You should be able to install the 32 bit userspace driver with something like `sudo apt install libnvidia-gl-450:i386` (change 450 to match the version that is installed).

**Comment by lkomage** [comment]
That made me check things, as it's been set to the proprietary drivers since installation. Driver manager now shows a new option for the "450-server", and I was on the 440 series. Will update this and see what happens.

**Comment by lkomage** [comment]
That fixed it. Curses, I should have checked exactly what *had* been updated. Went to the Ubuntu Driver Manager, selected the newly recommended 450 series driver, rebooted, and Steam works again. Closing this out!
