### ISSUE TITLE
Ugly layout in settings - polish language

### ISSUE THREAD

**Issue by rkozlo** [ValveSoftware/steam-for-linux#7375]
* Steam client version (build number or date): Sep 24 2020 (19:38:35), Steam API: v020, ver: 1600993224
* Distribution (e.g. Ubuntu): OpenSuse Tumbleweed
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Layout of sections in [Setting -> Download -> Limitations]. No need to describe more. I attached screenshot how it looks.
My resolution: 1920x1080
![Screenshot_20200927_091335](https://user-images.githubusercontent.com/44550015/94358730-4dcecd80-00a3-11eb-8c86-10bf0a60455b.png)

**Comment by kisak-valve** [comment]
Hello @rkozlo, Steam's settings window has been overhauled.

If you're seeing a similar issue with an updated Steam client, please open a new issue report.
