### ISSUE TITLE
SegFault in iris_dri.so when using DE other than Gnome or KDE on Ubuntu 20.04

### ISSUE THREAD

**Issue by cpiber** [ValveSoftware/steam-for-linux#7378]
#### Your system information

* Steam client version (build number or date): version 1599174997
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Can't start steam in desktop environments other than Gnome. Also works in KDE Plasma on Kubuntu (not tested in Plasma on Ubuntu).
Got SEGFAULT:
```
steam[2855]: segfault at 24 ip 00000000f63efd76 sp 00000000ffd49300 error 6 in iris_dri.so[f5831000+f06000]
Code: 90 fe ff ff 01 df 89 78 18 85 db 0f 84 1a 07 00 00 83 ee 01 8b 85 84 fe ff ff c7 85 98 fe ff ff 00 00 00 00 81 ce 00 00 09 78 <89> 33 8b b5 a0 fe ff ff 85 f6 74 7d 8d b6 00 00 00 00 0f b6 50 04
steam[3228]: segfault at 24 ip 00000000f63f4d76 sp 00000000ffdb7310 error 6 in iris_dri.so[f5836000+f06000]
Code: 90 fe ff ff 01 df 89 78 18 85 db 0f 84 1a 07 00 00 83 ee 01 8b 85 84 fe ff ff c7 85 98 fe ff ff 00 00 00 00 81 ce 00 00 09 78 <89> 33 8b b5 a0 fe ff ff 85 f6 74 7d 8d b6 00 00 00 00 0f b6 50 04
```

Possibly related:
https://discourse.ubuntu.com/t/call-for-testing-steam-in-focal-fossa/14490/9

#### Steps for reproducing this issue:
Tested on LXDE and i3-gaps (both with and without compositor)

Edit: Purging `xserver-xorg-video-intel` and rebooting worked. As mentioned in the link above, this might be because steam relies on the gnome appindicator. On my kubuntu install I have no problems with the package using Plasma or i3, possibly a wrong check?

**Comment by kisak-valve** [comment]
Hello @cpiber, iris_dri.so is part of the mesa project and your video driver for Intel hardware. Crashes in the video driver should be investigated on the driver side.

The easiest thing you can test is if a newer mesa build helps by using a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) and also mention your issue to your video driver vendor.

**Comment by cpiber** [comment]
I use the kisak-mesa repo (tested before and after)
Which repo would you recommend me to post this? And how would I gather more data? This is all dmesg shows

**Comment by kisak-valve** [comment]
You can look for similar mesa issues at https://gitlab.freedesktop.org/mesa/mesa/-/issues and Intel's xorg ddx is at https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel/-/issues.

**Comment by kisak-valve** [comment]
Hello @cpiber, are you still experiencing this issue on an up to date system?

**Comment by cpiber** [comment]
I'm on different hardware now, so I can't be sure. For reference, here is the bug I filed on your recommendation: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3570

I tried it now on another laptop with Ubuntu 22.04 and steam starts fine on DWM. I guess we can close it? I can try to setup the older laptop again if you think it's important.

**Comment by kisak-valve** [comment]
Thanks for the feedback.

At this time I don't think that there's an actionable detail for a Valve dev to ponder here. If the driver sided investigation makes progress with a hint that there's an application-sided issue, then please add a note here and I can re-open this issue report.
