### ISSUE TITLE
Steam Chat listening to mouse events when it's not supposed to

### ISSUE THREAD

**Issue by adamlwgriffiths** [ValveSoftware/steam-for-linux#7380]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/1239156/94886153-8a406600-04b5-11eb-914a-49801935b5a1.png)

* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Running Gnome 3

#### Please describe your issue in as much detail as possible:

Steam UI is insanely broken. Beyond belief.
Essentially: Steam will take mouse events that are intended for other windows.

Those windows do _not_ have to be overlapping steam, they can be other side of the desktop.
Examples of events that happen (despite mouse being over a different window / other side of screen).
* steam chat scroll bar steals event and causes it to scroll up
* steam chat takes click opening up links
* steam chat initiates a voice call
* steam chat scrolls when using mouse scroll 

I notice this mostly when clicking a link which raises another window. That doesn't mean it's the only time.
Just clicking on a different Window will still do this at times.

Clearly, steam's windows are not 'de-activating' and are intepreting mouse events at totally different X/Y coordinates as being for it.
It explains why voice chat initated (mouse was to the right, probably in line with start call button when clicked).
It explains the scroll bar click (mouse was to the right somewhere in line with the scroll bar).

There are issues - that are multiple years old - stating that Steam doesn't obey the WM protocols properly.
#4457 #2104 #2355 #2496 #597 #807

For a piece of software that has literally earned BILLIONS of dollars, this is just an absolute joke.
Steam is _bad_ on Windows, but Wow. You raised that bar on Linux.
This software is nearly 20 years old.
This is unacceptable.

#### Steps for reproducing this issue:

Just use the chat for more than 5 seconds

Easiest way to see _some_ of this behaviour.
Click a youtube link in chat.
Steam opens your browser.
Now start using the mouse scroll anywhere on the desktop.
What's that? Steam chat is scrolling?

**Comment by kisak-valve** [comment]
Hello @adamlwgriffiths, are you still experiencing this issue on an up to date system?

**Comment by adamlwgriffiths** [comment]
I believe this was related to an issue in the window manager.
