### ISSUE TITLE
Xorg and/or window manager memory usage eventually gradually increases

### ISSUE THREAD

**Issue by dakrk** [ValveSoftware/steam-for-linux#7384]
#### Your system information

* Steam client version (build number or date): Sep 3 2020, 21:18:20 
* Distribution (e.g. Ubuntu): Gentoo GNU/Linux (reproduced issue on Ubuntu 20.04.1 LTS with XFCE too)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
This is quite an odd issue and differs sometimes, but when you have steam open and when you're playing a game, eventually Xorg and/or window manager memory usage starts increasing and doesn't stop until you close steam. It sometimes only increases if you move your mouse, too.

#### Steps for reproducing this issue:

1. Start steam
2. Monitor Xorg and window manager memory usage
3. Play a game, I've personally tested this on Counter-Strike: Source
4. Be patient
5. Eventually memory usage for Xorg and/or your window manager should keep increasing, sometimes by itself or sometimes by moving the mouse
6. Keep it growing for a while, then close steam. Memory usage should stop increasing

**Comment by kisak-valve** [comment]
Hello @dakrk, you've described the issue being tracked at #5764. Closing as a duplicate.
