### ISSUE TITLE
Unable to run both steam native and under wine at the same time

### ISSUE THREAD

**Issue by SFort** [ValveSoftware/steam-for-linux#7386]
Certain games currently only work when steam is ran under wine e.g. rust(252490)
this causes a problem in that only the last launched steam instance will be online.
so depending on the launch order steam friends/store etc is unavailable on native
or the game is unable to authenticate and refuses to join a server.

#### Steps to reproduce 
1. Open steam nativley on linux
2. Open steam under wine

**Comment by kisak-valve** [comment]
Hello @SFort, this issue is already being tracked at #4412. Closing as a duplicate.
