### ISSUE TITLE
Change of Proton Version - redownload of whole game

### ISSUE THREAD

**Issue by nachfuellbar** [ValveSoftware/steam-for-linux#7388]
#### Your system information

* Steam client version (build number or date):  3 Sep 2020
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I downloaded more than 30 gb of mafia definitive edition - because it wouldn't start with default options i tried changing the proton version - aaaaaaaaaaaaaaaaaaaaand the game downloads again.

#### Steps for reproducing this issue:

1. Download a really big game
2. Change Proton version
3. get angry - just kidding (or maybe not when downloading 35gb), but it's really annoying the whole game is downloaded again even when i tried changing from global proton 5.0.9 to explizit 5.0.9 for the game

**Comment by kisak-valve** [comment]
Hello @nachfuellbar, it sounds like you've encountered the issue being tracked at #5901. Did you uncheck the `Enable Steam Play for all other titles` global option before setting the per-game Steam Play override?

**Comment by nachfuellbar** [comment]
I didn't disable it manually - i checked if it's still enabled and it is
So again for confirmation:
Global Steam Play for all other titles to 5.0.9
Enabled the same version for the game explicitly
Steam redownloads game

I just checked if the same happens when i disable the explicit setting and the game remained

Is per chance the usage of steam big picture mode relevant?

And thanks for finding the other issue - i haven't found it when searching for redownload and proton ;)

**Comment by kisak-valve** [comment]
Closing in favor of #5761. This issue report had a better issue title, so I've used that with the other issue report.
