### ISSUE TITLE
Fedora Seg Fault

### ISSUE THREAD

**Issue by cwesson** [ValveSoftware/steam-for-linux#7390]
#### Your system information

* Steam client version (build number or date): 1.0.0.66-2.fc31
* Distribution (e.g. Ubuntu): Fedora 31 (x86-64)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Linux 5.8.12-100.fc31.x86_64 #1 SMP Mon Sep 28 13:03:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz x 4
NVIDIA Corporation GP104 [GeForce GTX 1070]
NVIDIA Driver Version 450.80.02
Cinnamon Version 4.4.8

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I'm trying to start Steam but it crashes with a segmentation fault while starting.

```
$ steam
Running Steam on fedora 31 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/conlan/.local/share/Steam/ubuntu12_32/steam
[2020-10-04 18:30:07] Startup - updater built Sep  3 2020 21:18:09
Installing breakpad exception handler for appid(steam)/version(1599174997)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Installing breakpad exception handler for appid(steam)/version(1599174997)
[2020-10-04 18:30:08] Checking for update on startup
[2020-10-04 18:30:08] Checking for available updates...
[2020-10-04 18:30:08] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1599174997)
[2020-10-04 18:30:08] Download skipped: /client/steam_client_ubuntu12 version 1599174997, installed version 1599174997, downloaded version 0
[2020-10-04 18:30:08] Nothing to do
[2020-10-04 18:30:08] Verifying installation...
[2020-10-04 18:30:08] Performing checksum verification of executable files
[2020-10-04 18:30:09] Verification complete
Loaded SDL version 2.0.13-5919606

(steam:5163): Gtk-WARNING **: 18:30:09.742: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Mint-Y-Dark-Blue/gtk-2.0/main.rc:1085: error: unexpected identifier 'direction', expected character '}'
assert_20201004183007_1.dmp[5171]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201004183007_1.dmp
assert_20201004183007_1.dmp[5171]: Finished uploading minidump (out-of-process): success = yes
assert_20201004183007_1.dmp[5171]: response: CrashID=bp-46a91737-7630-460e-8e43-e9f362201004
assert_20201004183007_1.dmp[5171]: file ''/tmp/dumps/assert_20201004183007_1.dmp'', upload yes: ''CrashID=bp-46a91737-7630-460e-8e43-e9f362201004''
/home/conlan/.local/share/Steam/steam.sh: line 750:  5163 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
```

I tried `steam --reset`, deleting the .local/share/Steam directory, reinstalling steam, but none of them helped.

#### Steps for reproducing this issue:

1. launch steam

[assert_20201004183007_1.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/5324840/assert_20201004183007_1.dmp.zip)

**Comment by kisak-valve** [comment]
Hello @cwesson, is this a new install or was Steam working previously? I suspect this is a regression with nVidia 450.80.02 on Fedora 31. Can you roll back to 450.66 and test?

**Comment by cwesson** [comment]
It was working previously with NVIDIA 440.100 and kernel 5.7.15.  I tried 450.66 and 450.57 on kernel 5.8.12, both segfault'd the same way, and I was unable to install 440.100 on 5.8.12, it failed to compile.  I tried 450.57 and 450.66 on kernel 5.7.15, and saw the same segfault.  I rolled back to 440.100 on 5.7.15, and steam is working again.

**Comment by kisak-valve** [comment]
Hello @cwesson, are you still experiencing this issue on an up to date system?

**Comment by cwesson** [comment]
No, I no longer see this issue.  I'm not sure when it started working, but I'm now on Fedora 37, Steam 1.0.0.78-1.fc37, and NVIDIA 530.41.03.
