### ISSUE TITLE
Error log breaks after deleting

### ISSUE THREAD

**Issue by ctjlewis** [ValveSoftware/steam-for-linux#7392]
### System information
Ubuntu latest LTS.

### Reproduction
1. View `~/.steam/debian-installation/error.log` and see that it is not empty, or produce an error and observe that it is logged.
2. Delete the file.
3. Reproduce an error and see that it is no longer logged at `~/.steam/debian-installation/error.log`.

I imagine this is probably the last bug that Valve would bother fixing, but it's definitely one of the dumbest I've ever encountered, as it is a bug which prevents me from being able to debug all other bugs.

**Comment by kisak-valve** [comment]
Hello @ctjlewis, the creation of error.log is a Debian modification. The Valve-provided steam package does not make it. Report this issue to the Debian/Ubuntu package maintainers for Steam.

**Comment by ctjlewis** [comment]
Thank you very much for that clarification @kisak-valve, apologies for the ticket.
