### ISSUE TITLE
Add dependency on xdg-desktop-portal for new container runtime

### ISSUE THREAD

**Issue by aeikum** [ValveSoftware/steam-for-linux#7393]
The new container runtime uses xdg-desktop-portal to run stuff on the host, e.g. open external links in a web browser. It silently fails to open things if xdg-desktop-portal is missing. Steam should add xdg-desktop-portal as a dependency so this will work for all users.

**Comment by kisak-valve** [comment]
Quite belated, this was included in the 1.0.0.68 Steam package.
