### ISSUE TITLE
Steam Deleting Games from System

### ISSUE THREAD

**Issue by Ominitay** [ValveSoftware/steam-for-linux#7398]
#### Your system information

* Steam client version (build number or date): October 7 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Yesterday, I attempted to launch a game through Steam. It did not launch. I restarted the Steam client, and saw that all of my games were entirely gone. This has happened 3 times now, despite reinstalling the Steam client entirely. Interestingly, Proton and Steamworks remained in the default library location (all of my games are installed on two different libraries on separate partitions). Games were downloading or updating all the times this issue occurred, so that may or may not be the reason for my issue. Notably, the entire common folder is gone from the library location in which a game was not being installed to.

#### Steps for reproducing this issue:

1. Have games installed (Maybe on different library locations, perhaps on different partitions).
2. Wait... (Maybe have game installing as well, I'm not sure this will reproduce on other systems)
3. All games will be gone, and hard drive space will be freed, indicating that the games are truly **gone**.

**Comment by kisak-valve** [comment]
Possible duplicate of #6543.

**Comment by Ominitay** [comment]
Possibly. Nobody seems to have discerned the root cause of the issue either :/ I'll close this issue if I can verify that this is a duplicate of #6543, as some details seem to differ.

**Comment by Ominitay** [comment]
In an attempt to resolve this issue myself, I am wiping my Steam partitions, and installing the Steam Client Beta, to see if the issue persists...

**Comment by byte1024** [comment]
Steam partitions huh? Sounds like you overcomplicated it into a problem.

Overcomplications will often be something never tested as devs can't test every possibility so extra problems can result. Many run into that as they customize their OS too extensively.

Keep it simple, less problems.

**Comment by Ominitay** [comment]
@byte1024 It is hardly overcomplicating anything to have a Steam library on another drive (the ability to have multiple library locations exists precisely for it!), which would necessitate a different partition. It is clearly not my *fault* that this issue has occurred -- it is very likely an issue with the Steam Client.

**Comment by Ominitay** [comment]
Oh, it seems that they deleted their comment. What @byte1024 was saying is that I am overcomplicating stuff by having my Steam library on a separate partition, and that experienced developers are unable to account for that.

**Comment by byte1024** [comment]
What I actually meant was that overcomplicating things tend to cause problems that devs didn't take into account or test. They can't test everything.

Its difficult to say that the OP here didn't do that. Steam obviously works with partitions but people tend to eg use NTFS or other things that can cause issues such as the linked issue.

Keep it simple.

**Comment by Ominitay** [comment]
I've heard that issues can come about when using certain filesystems, however, that is not my case. To clarify, my setup is that I have a partition each on my ssd and hard drive, both of which are formatted as Ext4 (they are dedicated to Steam, as I don't want to have to redownload my games library if I ever have to switch distro, but here I am downloading hundreds of gigabytes hoping that they won't be nuked again :woman_facepalming:). I understand that many users have a similar setup to mine, so it shouldn't be a factor in this issue.
 
I realise that I haven't given much info on my setup here, so sorry for any confusion @byte1024 :)

**Comment by Ominitay** [comment]
Closing as it may be resolved by carrying out what I said in the 4th comment. Will carry on in #6543 if this resurfaces.
