### ISSUE TITLE
Making Steam store page videos go fullscreen from your primary display opens the video on the wrong monitor

### ISSUE THREAD

**Issue by Waddlen** [ValveSoftware/steam-for-linux#7399]
#### Your system information
[System Information Gist](https://gist.github.com/Waddlen/114e145c0b3c9fd83fcd809a56d051ed)

* Steam client version (build number or date): Oct 8 2020, at 22:08:00
* Distribution (e.g. Ubuntu): Pop_OS! 20.04
* Opted into Steam client beta?:  Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I am using X with 3 side-by-side 1440p monitors, all connected by DisplayPort directly to my graphics card. The left monitor is my primary display. Here is a screenshot of my display settings:
![Screenshot from 2020-10-12 19-35-22](https://user-images.githubusercontent.com/23039119/95799285-31957800-0cc2-11eb-9f1f-8e1c94dbe14b.png)
When I open a game's Steam store page and try to fullscreen a video, it works correctly on the right and center monitors. However, trying to fullscreen on the leftmost 'primary display' results in the video going fullscreen on my center monitor, like so:
![Screenshot from 2020-10-12 19-41-56](https://user-images.githubusercontent.com/23039119/95799556-07908580-0cc3-11eb-8392-1e9c4b1cdbef.png)
If I make the center monitor my 'primary display,' then Steam store videos will fullscreen correctly on the left and right monitors, but the center 'primary display' will open the video on my left monitor.

#### Steps for reproducing this issue:

1. Open any game store page on the Steam store, for example Total War: WARHAMMER
2. With Steam open in your 'primary display,' try to fullscreen a video, and watch it open on the wrong monitor.

**Comment by kisak-valve** [comment]
Hello @Waddlen, this issue is already being tracked at #5277. Since this is well written, I've transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/5277#issuecomment-707410231.

Closing as a duplicate.
