### ISSUE TITLE
Broadcast looks like a complete mess 

### ISSUE THREAD

**Issue by adrianlshaw** [ValveSoftware/steam-for-linux#7401]
#### Your system information

* Steam client version (build number or date): Oct 7 2020
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

[System specs](https://gist.github.com/adrianlshaw/0d4b05d2f2278800db8db8a9ea6719bb) 

#### Please describe your issue in as much detail as possible:

When watching a broadcast of someone's game, there is a lot of image distortion.

![Screenshot from 2020-10-13 23-39-52](https://user-images.githubusercontent.com/762640/95923867-549d5600-0dae-11eb-8e19-458c841fed4f.png)

I've blurred the chat and contact for privacy. 

#### Steps for reproducing this issue:

1. Open chat
2. Right click on contact
3. 'Watch game'

**Comment by adrianlshaw** [comment]
It seems like increasing the bit rate solved the problem.

**Comment by kisak-valve** [comment]
Hello @adrianlshaw, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by adrianlshaw** [comment]
Here's the [gist](https://gist.github.com/adrianlshaw/0d4b05d2f2278800db8db8a9ea6719bb) of it

**Comment by kisak-valve** [comment]
Hello again @adrianlshaw, are you still experiencing this issue on an up to date system?

**Comment by adrianlshaw** [comment]
@kisak-valve you may close this issue. i've not experienced this recently.
