### ISSUE TITLE
How to uninstall an app from steamcmd?

### ISSUE THREAD

**Issue by sshnuke3** [ValveSoftware/steam-for-linux#7402]
#### Your system information

* Steam client version (build number or date): steamcmd
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No]no
* Have you checked for system updates?: [Yes/No]yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. How to uninstall an app from steamcmd?
Seems it just has app_build and app_update command but no app_uninstall?

Steam>help

Usage:  steamcmd ["+COMMAND [ARG]..."]...
  or:   steamcmd +runscript SCRIPTFILE

Help topics - type "help <topic>" or run with "--help <topic>" for more information:

               login : Logging in to Steam
             scripts : Executing a sequence of commands via a script file
         commandline : Executing commands directly via the OS command line
             convars : Options and settings that affect this program session
           app_build : Building Steam application content (only for licensed Steam application developers)
          app_update : Installing/updating a Steam application on the local filesystem (EG dedicated servers)

**Comment by kisak-valve** [comment]
Hello @sshnuke3, you can use `+force_install_dir <path>` and setup each game in a separate directory that you can manage or delete.

**Comment by sshnuke3** [comment]
but i still want to uninstall some apps to spare more disk space

**Comment by sshnuke3** [comment]
but i still want to uninstall one app to spare more disk space
but i want to leave other apps on my disk
so how to do this? @kisak-valve

**Comment by kisak-valve** [comment]
Looking around a bit, https://unix.stackexchange.com/questions/463708/uninstall-a-steam-game-with-the-console may help.

**Comment by sshnuke3** [comment]
> Looking around a bit, https://unix.stackexchange.com/questions/463708/uninstall-a-steam-game-with-the-console may help.

i have tried this but steamcmd +app_uninstall appid +quit doesn't work
there is nothing response and the app i want to delete is still there
