### ISSUE TITLE
Craft The World stopped running on proton.

### ISSUE THREAD

**Issue by Stepan-Zigmur** [ValveSoftware/steam-for-linux#7406]
#### Your system information

* Steam client version (build number or date): Oct 12 2020.
* Distribution (e.g. Ubuntu): ROSA Desktop Fresh R11.1 release 2016.1 for x86_64
* Opted into Steam client beta?: [Yes/No] beta and no beta
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Oct 08-09 2020, I was setting up a cs:go game for my friend, and since it didn't run on his computer initially, I started trying it on my computer. Changed versions of proton and in the end, only reinstalling the system on Ubuntu helped on his computer. But the game "Craft The World" stopped running on my computer" I deleted the game itself, reinstalled Steam, changed the versions of proton forcibly, but the game only loaded the black screen and crashed. If you can somehow reproduce the logging, I could lay out the logs of the game launch.
In the Steam client that runs through Playonlinux Wine, the game continues to work normally, but there are slowdowns.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Stepan-Zigmur, we're tracking issues with games run with Proton in the Proton issue tracker, also we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/423#issuecomment-709693695.
