### ISSUE TITLE
Redownload and reprocess Vulkan shaders

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7409]
#### Your system information

* Steam client version: Oct 07 2020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?:No

#### Please describe your issue in as much detail as possible:
I've accidentally removed the **shadercache** folder. Is there a way to redownload and reprocess the Vulkan shaders of my installed games ?

**Comment by kisak-valve** [comment]
Hello @ranplayer, if you toggle the `Enable Shader Pre-Caching` setting in `Steam` -> `Settings` -> `Shader Pre-Caching`, off and on, that should get Steam to do what you're looking for.

**Comment by ranplayer** [comment]
It worked @kisak-valve . Thanks for the quick response!
