### ISSUE TITLE
"Browse Local Files" blocks until command exits

### ISSUE THREAD

**Issue by sparr** [ValveSoftware/steam-for-linux#7419]
#### Your system information

* Steam client version (build number or date): Oct 7, 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I selected a game, right clicked its entry in the library, then went to Properties > Local Files > Browse Local Files. This launched my file browser. Steam became unresponsive until the file browser was closed, because my file browser runs directly from a command instead of being launched in the background when called.

The call to launch the file browser should not block, Steam should fork it and ignore it.

#### Steps for reproducing this issue:

1. Set your file browser to something simple like mc or pcmanfm
2. In Steam, select a game from the Library
3. Right click the game, then Properties, Local Files, Browse Local Files
4. Observe the file manager launch, and the Steam client unresponsive and not re-drawing its GUI
5. Close the file manager
6. Observe the Steam client responsive again

**Comment by kisak-valve** [comment]
Hello @sparr, thanks for the issue report.

This sounds like the xdg-open related issue at #5090. Closing in favor of the older issue report.

**Comment by sparr** [comment]
Duplicate of #5090
