### ISSUE TITLE
New platform: Android: Vive Focus

### ISSUE THREAD

**Issue by ohhmm** [ValveSoftware/steam-for-linux#7420]
Streaming to Vive Focus makes not the best gaming experience. Is it possible to build Steam or SteamLink for the HTC Vive Focus?

**Comment by kisak-valve** [comment]
Hello @ohhmm, as of right now, no it's not available as an option. Speculatively, this would require cooperation from the hardware vendor, and it's likely that wouldn't be a public discussion by either party.
