### ISSUE TITLE
Steam flickers on Linux on a Chromebook (GalliumOs)

### ISSUE THREAD

**Issue by danielristic** [ValveSoftware/steam-for-linux#7422]
#### Your system information

* Steam client version (build number or date): built Oct 7 2020
* Distribution (e.g. Ubuntu): GalliumOS 3.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Any game flickers regardless of the video settings.

#### Steps for reproducing this issue:

Launch any game and it will start flickering at random (even on the title screen).

**Comment by kisak-valve** [comment]
I'm guessing by the list of currently supported hardware for GalliumOS that you're on an Intel-based X86 Chromebook. It may be worthwhile to also mention this issue to your video driver vendor (mesa/Intel).

Also, assuming that is true, you might be able to test a newer mesa version using a PPA like [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa), but this is completely untested with GalliumOS.

**Comment by danielristic** [comment]
Hello,

Thanks for your comment, it is indeed an Intel-based Chromebook (an Intel Celeron N3036 with "3.0 Mesa 20.0.8" according to Steam's System Information panel).

Just to make sure that I understand your suggestions correctly I would need to file a bug report [here](https://bugs.launchpad.net/~oibaf) and also try switching to [this driver](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) which is a fork of the regular one, is that correct?

As there are no specific instructions for GalliumOS, to do so I would follow the general instructions for Ubuntu which consists of the following commands?

```
sudo apt install ppa-purge
sudo ppa-purge ppa:kisak/kisak-mesa
```

or possibly `sudo ppa-purge -d galliumos ppa:kisak/kisak-mesa`

Thanks for your help.

**Comment by kisak-valve** [comment]
From what I could find, GalliumOS 3.1 is based on Ubuntu 18.04 (Bionic), so that would make the removal method for the PPA something like `sudo ppa-purge -d bionic ppa:kisak/kisak-mesa`.

Issues with mesa drivers should go directly to the folks working on that project instead of another PPA maintainer. https://docs.mesa3d.org/bugs.html is a good place to start.

**Comment by danielristic** [comment]
I've updated to the kisak-mesa driver but it still flickers, would that mean it's most likely not a video driver issue?

Thanks.

**Comment by kisak-valve** [comment]
That's unfortunate, thanks for testing. All that tells us is that we didn't get lucky and it's a current issue that hasn't been fixed in the driver since GalliumOS 3.1 was released.

**Comment by danielristic** [comment]
Thanks for your help. After further testing, I noticed a couple of things that make me doubt the video drivers are to blame:
- Contrary to what I initially thought, some games do not have the issue at all.
- For the games that have the issue (eg. Worms Armageddon), while changing the video resolution or settings does not help, launching the game in windowed mode completely prevents the flickering.

I yet need to try this on an external display but it might be an issue with the games themselves.

**Comment by kisak-valve** [comment]
Hello @danielristic, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
