### ISSUE TITLE
Sometimes high cpu usage in idle

### ISSUE THREAD

**Issue by MartinX3** [ValveSoftware/steam-for-linux#7424]
#### Your system information

* Steam client version (build number or date): 1602795778
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Since the proton 5.13 update and the introduction of the soldier steam runtime the steam process itself sometimes hangs with 100% cpu in the background.
I feel like mostly happens after waking the computer up after a night from standby.

#### Steps for reproducing this issue:

It's not really clear for me why this happens and when.

![grafik](https://user-images.githubusercontent.com/4518092/96750925-d9026100-13cc-11eb-8709-85cc03ef37b0.png)

**Comment by kisak-valve** [comment]
Hello @MartinX3, you might be seeing the issue being tracked at #7372. Can you clarify if "hangs" means that the Steam client is completely non-interactive? Also, can you try to get the thread name as described at https://github.com/ValveSoftware/steam-for-linux/issues/7372#issuecomment-696193644?

**Comment by MartinX3** [comment]
It sadly doesn't happen all the time

I think I observed it now 2 times, since I installed 5.13

The steam clients seems to act normal, just this process uses so much cpu sometimes.
(No downloads)

**Comment by MartinX3** [comment]
Now it happened again
I think with the proton update and after a restart.
![grafik](https://user-images.githubusercontent.com/4518092/99153454-e8fa2180-26a8-11eb-9e75-2071302b8a4b.png)

Then closing steam and starting it another time fixed it.

**Comment by MartinX3** [comment]
And it happens again.

**Comment by StefanLobbenmeier** [comment]
I am also having this issue. I noticed it first today just after updating Proton to 5.13, but I can not say for certain that it has not been there before, but it is quite suspicious that I notice it ~5 Minutes after installing Proton 5.13 (see screenshot).

My specs:
 OS: Manjaro 20.2 Nibia
 Kernel: x86_64 Linux 5.8.18-1-MANJARO
 Uptime: 38m
 Packages: 1282
 Shell: zsh 5.8
 Resolution: 2560x1440
 DE: KDE 5.76.0 / Plasma 5.20.4
 WM: KWin
 GTK Theme: Breath [GTK2/3]
 Icon Theme: breath2
 Disk: 95G / 124G (81%)
 CPU: Intel Core i5-8600K @ 6x 4.3GHz [51.0°C]
 GPU: Radeon RX 570 Series (POLARIS10, DRM 3.38.0, 5.8.18-1-MANJARO, LLVM 11.0.0)
 RAM: 2922MiB / 15892MiB



![image](https://user-images.githubusercontent.com/36509607/101895530-f0c5bc80-3ba7-11eb-8575-8429f0f72678.png)

**Comment by StefanLobbenmeier** [comment]
After restarting Steam it uses basically 0%

**Comment by MartinX3** [comment]
Yes, you got exactly the same issue like me.

**Comment by MartinX3** [comment]
Ah, it is definitely connected to the proton installation/updating/deinstallation
I switched all games globally to proton experimental and forced the valve certified games to use proton experimental and then uninstalled proton 3.16 and 5.13 and again the `/home/$USERNAME/.local/share/Steam/ubuntu12_32/steam` process consumes 100% cpu until I restart steam (and the shutdown of the process is heavily delayed as well)

**Comment by kisak-valve** [comment]
Hello @MartinX3, you've described the issue being tracked in #7372. Closing as a duplicate.

It might be worthwhile to follow https://github.com/ValveSoftware/steam-for-linux/issues/7372#issuecomment-696193644 and confirm that the thread name shows up as `CLocalLibraryCr`.
