### ISSUE TITLE
steamcmd client can not running

### ISSUE THREAD

**Issue by g90130** [ValveSoftware/steam-for-linux#7428]
#### Your system information

* Steam client version (build number or date): steamcmd client
* Distribution (e.g. Ubuntu): ubuntu 18.04 64bit with ARM
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. running the steamcmd.sh
the error has been occurred
it report
./steamcmd.sh: line 37: /home/steam/Steam/linux32/steamcmd: cannot execute binary file: Exec format error
![image](https://user-images.githubusercontent.com/46667747/97105049-54c51c00-16f3-11eb-80df-00b6df84811f.png)

**Comment by kisak-valve** [comment]
Hello @g90130, steamcmd does not support ARM systems. Also, almost all content on Steam isn't compiled for ARM.
