### ISSUE TITLE
Exit code 130 Ubuntu 20.04.1

### ISSUE THREAD

**Issue by nickkostov** [ValveSoftware/steam-for-linux#7432]
#### Your system information

* Steam client version (build number or date): steam_latest.deb
* Distribution (e.g. Ubuntu): Ubuntu 20.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (auto on boot)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Install steam.
2. Launch steam.
```
~$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/nick/.local/share/Steam/ubuntu12_32/steam
```
3. I have opened steam but it does not load GUI.
Exit code of steam command is 130.

**Comment by kisak-valve** [comment]
Hello @nickkostov, can you check if any 32 bit OpenGL application works on your system? On older Ubuntu releases I'd suggest trying `glxinfo` from `mesa-utils:i386`, but as of Ubuntu 20.04, the 32 bit variant is no longer available. I suspect that you're using the nVidia proprietary driver, and we've seen Steam wait indefinitely on the video driver here. The nVidia proprietary driver requires that the running kernel module version, 32 bit userspace version, and 64 bit userspace version match to work properly.

**Comment by nickkostov** [comment]
@kisak-valve  thanks for contacting me on the matter I will attempt the glxinfo from mesa-utils:i386.

**Comment by nickkostov** [comment]
Ughh how would I try the driver, I ran it as a command and got a very weird output.
Thanks in advance.

**Comment by nickkostov** [comment]
After several installs uninstalls it works :)
