### ISSUE TITLE
Steam can't close the game Magicka 2

### ISSUE THREAD

**Issue by FurtadoPires** [ValveSoftware/steam-for-linux#7435]
#### System information

* Steam client version: 
![steam_build](https://user-images.githubusercontent.com/7890832/97387979-e3819680-18b5-11eb-8b3d-67dacf332719.png)

* Distribution: Manjaro and Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Steam can't close the process of the game Magicka 2 (238370) after we exit the game. Even if I click on the "Stop" button won't do anything and will remain as a running process.

#### Steps for reproducing this issue:

1. Launch the game
2. Exit the game
3. Try to finish the process using the stop button

**Comment by kisak-valve** [comment]
Hello @FurtadoPires, this issue should also be mentioned to the game's dev(s) if it hasn't been already.

**Comment by FurtadoPires** [comment]
> 
> 
> Hello @FurtadoPires, this issue should also be mentioned to the game's dev(s) if it hasn't been already.

I already did it, I know this is a problem for the developers, but I also open an issue here because I think steam should be able to close the game even if it misbehaves

**Comment by TTimo** [comment]
I can reproduce. `Force Quit` via the in game overlay works but the `Quit` button in the Steam client UI does nothing.

**Comment by TTimo** [comment]
Next beta (> Oct 28) will have a fix for this.

**Comment by FurtadoPires** [comment]
I can confirm that the Nov 4 2020 works. The game still don't close properly, but at least we can now finish the process through the stop button.

Thank you @TTimo
