### ISSUE TITLE
Steam UI sometimes extremely slow

### ISSUE THREAD

**Issue by ychromosome** [ValveSoftware/steam-for-linux#7441]
#### Your system information

* Steam client version (build number or date): Oct 28 2020 23:35:02
* Distribution (e.g. Ubuntu): Fedora 33
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
For a few months now I have severe UI lag in some parts of the Steam Client.
I think it has something to do with videos played or certain game pages. 
I am really not sure what causes it.
My System is up to date, Vulkan, Vaapi and Vdpau are working. (see logs)

Steam Support Info:
https://gist.github.com/ychromosome/6135682ca9f416a9dfec29c9bd842635

Vaapi / vdpau info:
https://gist.github.com/ychromosome/56b899e252c9593abb6d13e2a4c99c37

Also I am unable to watch livestreams or streams from friends. I get the "infamous" "your browser does not support ..." message.

#### Steps for reproducing this issue:

1. use Steam Client and wait for it to appear, usually on pages with trailers or game videos.

**Comment by kisak-valve** [comment]
Hello @ychromosome, the first half of your issue is being tracked at #7245 and the second half is #6780. Closing in favor of the existing issue report.
