### ISSUE TITLE
Specific List Of Games Re-Processes Vulkan Shaders Every Reboot

### ISSUE THREAD

**Issue by HurricanePootis** [ValveSoftware/steam-for-linux#7447]
#### Your system information

* Steam client version (build number or date): 11/3/2020
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Every time I restart my PC and Launch steam, steam will process the shaders for the following games:
Fallout: New Vegas
Cuphead
DOOM 2016
Deep Rock Galactic
SCP: Secret Laboratory
Yakuza Kiwami 2

#### Steps for reproducing this issue:

1. Enable steam shader-cache
2. Enable background Vulkan processing
3. Restart Steam
4. Some shades will rebuild themselves

**Comment by kisak-valve** [comment]
Hello @HurricanePootis, this issue is already being tracked at #7306. Closing as a duplicate.

**Comment by Peque** [comment]
@kisak-valve I have seen several issues like this one closed in favor of #7306. Unfortunatelly, that issue was locked and conversation is limited to collaborators.

Would it be possible to keep the conversation limited to collaborators (if you want to avoid spam) but unlock the reactions so that people can express interest by giving it a "thumbs up"? :blush:

**Comment by Peque** [comment]
@kisak-valve Also, I just noticed the issue was closed but no statement was given. Is this an expected behavior? Otherwise, could it be re-opened?

**Comment by kisak-valve** [comment]
Hello @Peque, you're looking for #8076.

**Comment by Peque** [comment]
@kisak-valve Thanks for the pointer! :blush:
