### ISSUE TITLE
Gtk Nvidia problem probably missing lib32 utils

### ISSUE THREAD

**Issue by taldarus** [ValveSoftware/steam-for-linux#7448]
OP Here: https://github.com/ValveSoftware/Proton/issues/438#issuecomment-720658016

Moving it here because it is no longer relevant to proton specifically.

My suspicion is that it is strongly related to this: https://github.com/ValveSoftware/steam-for-linux/issues/7442
but I have also made considerable improvements from this one: https://github.com/ValveSoftware/steam-for-linux/issues/7395

In fact I found the numerous broken packages and orphan related problems, but nothing I have done has been anything significantly different from tracking down bad/missing files and updating them accordingly.

Terminal Spew: https://gist.github.com/taldarus/39d849198d6b7d5e70b365a733fac95e

Sorry if I was supposed to post this in issue 7442.

**Comment by kisak-valve** [comment]
Hello @taldarus, just like #7395, Swrast is mesa's slower cpu opengl renderer and the fact Steam is trying to use it and failing hints that you're using the nVidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you check what driver series you have installed, then check if the 32 bit userspace is installed with something like `apt policy libnvidia-gl-450:i386`? (Change 450 to match the version that is installed.) If it's not installed, you can run something like `sudo apt install libnvidia-gl-450:i386` to add it to your system.

**Comment by taldarus** [comment]
I tried finding a 32 lib already, but couldn't find the relevant package. Here's what you asked for.

`libnvidia-gl-450:i386:
  Installed: (none)
  Candidate: 450.80.02-0ubuntu0.20.04.2
  Version table:
     450.80.02-0ubuntu0.20.04.2 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
d_____s@N_______r:~$ sudo apt-get policy libnvidia-gl-450:i386
[sudo] password for d________s:             
E: Invalid operation policy
d__________s@N_______r:~$ sudo apt install policy libnvidia-gl-450:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package policy
d_______s@N_____r:~$ apt policy libnvidia-gl-450:i386
libnvidia-gl-450:i386:
  Installed: (none)
  Candidate: 450.80.02-0ubuntu0.20.04.2
  Version table:
     450.80.02-0ubuntu0.20.04.2 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
d_____s@N____r:~$ 
`

I will look up the package policy part, as I am unfamiliar with that. If you know it, I would happily take your advice @kisak-valve
