### ISSUE TITLE
No background in section settings in library

### ISSUE THREAD

**Issue by cucumb3r-ru** [ValveSoftware/steam-for-linux#7451]
#### Your system information

* Steam client version: Nov 4 2020, 18:48:04
* Distribution: Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

When you open the home page of the game library, many sections like "What's New", "Recent Games", "Installed Locally" appear. There is an arrow (v) to the right of the custom sections, when you click on it, the section settings menu appears, but the problem **is that this menu does not have a background**, but the rest of the actions functionality works.

#### Steps for reproducing this issue:

1. Open library home page
2. Click on the arrow (v) in custom sections

**Comment by kisak-valve** [comment]
For clarity, it looks like it's the shelf's drop down menu that is used to select a collection/category. A downward facing arrow (v).

**Comment by cucumb3r-ru** [comment]
yes, down (v)

**Comment by kisak-valve** [comment]
Hello @cucumb3r-ru, please retest this issue.

**Comment by cucumb3r-ru** [comment]
it works right
