### ISSUE TITLE
Steam crashes on starting the application. -Elementary OS Loki-

### ISSUE THREAD

**Issue by Mau5terpiece** [ValveSoftware/steam-for-linux#7452]
#### Your system information

* Steam client version (build number or date): 11/5/2020
* Distribution (e.g. Ubuntu): Elementary OS Loki 5.1.7 64-bit
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expected steam to open into the login menu when I ran the command or clicked on the application.
https://gist.github.com/Mau5terpiece/159d94beafa3ed358d0fd25da84a99ff
#### Steps for reproducing this issue:

1. Install steam through the application center or the apt package manager (sudo apt install steam -y)
2. Launch steam through the terminal (steam) or by clicking on the application in the application menu
3. Steam then crashes with the log aforementioned.
``

**Comment by Mau5terpiece** [comment]
[159d94beafa3ed358d0fd25da84a99ff-d3238a18de75695ffc203e08689043f235478404.zip](https://github.com/ValveSoftware/steam-for-linux/files/5497815/159d94beafa3ed358d0fd25da84a99ff-d3238a18de75695ffc203e08689043f235478404.zip)
I'm an idiot, and don't know how embeds work here's a download to the log

**Comment by kisak-valve** [comment]
Hello @Mau5terpiece, swrast is mesa's slower cpu opengl renderer and the fact Steam is trying to use it and failing hints that you're using the nVidia proprietary driver, but don't have nVidia's 32 bit userspace installed.

Can you check what driver series you have installed, then check if the 32 bit userspace is installed with something like `apt policy libnvidia-gl-450:i386`? (Change 450 to match the version that is installed.) If it's not installed, you can run something like `sudo apt install libnvidia-gl-450:i386` to add it to your system.

**Comment by Mau5terpiece** [comment]
From what I can tell I am using the nvidia-440-server drivers
I have no Idea what info this gives

**Comment by Mau5terpiece** [comment]
Should I upgrade to the 450-server driver?

**Comment by Mau5terpiece** [comment]
Here is what it displays when I ran `apt policy libnvidia-gl-450:i386`
`libnvidia-gl-450:i386:
  Installed: (none)
  Candidate: 450.80.02-0ubuntu0.18.04.2
  Version table:
     450.80.02-0ubuntu0.18.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages`

**Comment by Mau5terpiece** [comment]
that seemed to have fixed it
