### ISSUE TITLE
Steam crashing on startup (Fedora 33, Radeon)

### ISSUE THREAD

**Issue by nicholasbishop** [ValveSoftware/steam-for-linux#7453]
#### Your system information

* Steam client version (build number or date): not sure since it's crashing on startup
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, fully up to date
* OpenGL renderer string: `Radeon RX Vega (VEGA10, DRM 3.38.0, 5.8.17-300.fc33.x86_64, LLVM 11.0.0)`

#### Please describe your issue in as much detail as possible:
Steam should launch, instead it crashes. Output:

https://gist.github.com/nicholasbishop/019ddc1bfe35785596f88f4139eca917

#### Steps for reproducing this issue:

1. Install steam from https://rpmfusion.org/
2. Run `steam` in a shell
3. Observe that it crashes

**Comment by kisak-valve** [comment]
Hello @nicholasbishop, does any 32 bit OpenGL application like `glxinfo32` from https://koji.fedoraproject.org/koji/rpminfo?rpmID=22417555 work?

**Comment by nicholasbishop** [comment]
It seems not:

```
$ glxinfo32 
name of display: :0
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  60
  Current serial number in output stream:  59
```

**Comment by kisak-valve** [comment]
I'm not that familiar with Fedora packaging. Blind guess: does `dnf install mesa-dri-drivers.i686` help?

**Comment by nicholasbishop** [comment]
I found the problem: I had some bad 32-bit libs. Not sure how it happened, but they were 0 sized. Fixed with `sudo dnf reinstall elfutils-libelf-0.182-1.fc33.i686`.

Closing this, thanks for your help :)
