### ISSUE TITLE
Friends list and chat issues, blank windows

### ISSUE THREAD

**Issue by gdushi** [ValveSoftware/steam-for-linux#7457]
#### Your system information

* Steam client version (build number or date): Nov 4 2020
* Distribution (e.g. Ubuntu): Arch Linux 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After the recent update there seems to be an issue with the steam friends list, it doesn't show anything only a blank window which you can't press or move. This happened after a steam client update a few days ago but i let it go thinking that they would release another update to fix it.

Not only is the friends list broken but even the chat, it suddenly opens new tabs every few seconds with a blank window. Sometimes the friends list succeeds to open, other times it does not open at all or opens but with a blank window. High CPU usage is also noted. Chatting with a friend works but it is interrupted by the new windows popping up. I was only able to chat once my friend sent me a message.

![steam_issue](https://user-images.githubusercontent.com/45565887/98547484-8bc13300-2298-11eb-98dd-7a7af643c667.png)

#### Steps for reproducing this issue:

1. After opening a chat with a friend it will automatically open new chats every few seconds.
2. The friends list issue should be present from the start.

**Comment by kisak-valve** [comment]
Hello @gdushi, this issue is already being tracked at #7450. Closing as a duplicate.
