### ISSUE TITLE
Doom Eternal won't load following upgrade from Ubuntu 20.04 - 20.10

### ISSUE THREAD

**Issue by Pentastarch** [ValveSoftware/steam-for-linux#7458]
#### Your system information
Distro:    Ubuntu 20.10
Kernel:   5.8.0-26-generic
RAM:     32 GB
GPU Driver:  NVIDIA 455.28
GPU:    NVIDIA GeForce RTX 2070 SUPER
CPU:   AMD Ryzen 7 3700X 8-Core
Proton: 5.13-1
Steam client:   Built: 4th Nov, version 1604538810 
Steam Runtime Version:  steam-runtime_0.20201104.0

Ubuntu 20.10

In the steam beta - yes

I upgraded from 20.04 to 20.10 and Doom Eternal stopped loading. It gets to the loading screen and hangs. Other games - Doom 2016, Metro Exodus load and run fine.

I have reinstalled steam and the game, verified the files but cant get past the load screen. 

I did change the screen refresh rate to 60Hz from 144Hz, which worked prior to the upgrade, and it loads the next screen and the music starts. But then hangs there. but I haven't got any further.

Any ideas??

**Comment by kisak-valve** [comment]
Hello @Pentastarch, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-724115303.
