### ISSUE TITLE
Enabling steam play for all other titles and selecting a 3rd-party compatibility tool as default makes the box uncheck after the steam restart

### ISSUE THREAD

**Issue by monterrr** [ValveSoftware/steam-for-linux#7459]
#### Your system information

* Steam client version (build number or date): 28/11/20
* Distribution (e.g. Ubuntu): Fedora 33
* Opted into Steam client beta?:  No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking "Enable steam play for all other titles" and selecting Proton flatpak or broxton makes the box uncheck after the steam restart.

#### Steps for reproducing this issue:

1. Download and install a 3rd-party compatibility tool (proton flatpak version or broxton)
2. Click "Enable steam play for all other titles" and select the desired version
3. The box under "Enable steam play for all other titles" will uncheck after the steam restart but the tool still continues to be used.

Related report:
https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/issues/6

**Comment by kisak-valve** [comment]
Hello @monterrr, this issue is already being tracked at #6043. Closing as a duplicate.
