### ISSUE TITLE
Library won't load

### ISSUE THREAD

**Issue by t0stiman** [ValveSoftware/steam-for-linux#7461]
#### Your system information

* Steam client version (build number or date): 2020-10-28
* Distribution (e.g. Ubuntu): Kubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Extra info:
Nvidia GTX 1660
Driver version 450.80.02

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-53-generic
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 2600 Six-Core Processor
Memory: 15,6 GiB

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When i try to open the games library in steam, i expect to see a list of games on my account.
What happens instead is I get a loading animation and it doesn't go away, the library never loads.

![image](https://user-images.githubusercontent.com/18124323/98839607-04b1bd80-2446-11eb-9069-32ca2225fc4c.png)

The store, community, friends list and playing games that are already installed all work.

I have already tried to : 
- reinstall steam, completely (apt purge).
- wait a few months and do another steam reinstall.
- opt in to the beta

#### Steps for reproducing this issue:

1. Open the steam client.
2. Click 'library' in the top bar.

Let me know if you need any more info.

**Comment by kisak-valve** [comment]
Hello @t0stiman, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by t0stiman** [comment]
@kisak-valve https://gist.github.com/t0stiman/a7a090d769a596b742f2aebe9d00fd4a

**Comment by TTimo** [comment]
Your pinned libraries folder looks to be in `/mnt/Data/dingen/steam_linux_link/ubuntu12_32/steam-runtime` when your main Steam install is in `~/.local/share/Steam`. This sounds like you are using symlinks to put some data on other drives, this is likely cause problems.

You could use bind mounts instead, but the best solution is likely to keep the entire core Steam install in `~/.local/share/Steam` and setup an additional Steam library on your `/mnt/Data` drive for all your games.

**Comment by t0stiman** [comment]
Ah, I totally forgot I'd done that. I deleted ~/.local/share/Steam and my game library folders, did a reinstall of steam, and the issue is gone. Thanks for your help.
