### ISSUE TITLE
Is this an official valve package?

### ISSUE THREAD

**Issue by flibblewibble** [ValveSoftware/steam-for-linux#7468]
https://github.com/flathub/com.valvesoftware.Steam/

This app claims to be ValveSoftware (see namespace), is this officially Valve's software package?

If not, why do they claim to be Valvesoftware in the app namespace?

If not, what is Valve going to do about it (trademark issue?, false representation?)

**Comment by kisak-valve** [comment]
Hello @flibblewibble, the very first line of https://flathub.org/apps/details/com.valvesoftware.Steam has "This is a community package of Steam gaming plaform not officially supported by Valve."

It's a community project to put the entire Steam client inside of a Flatpak environment and covers the packaging around the Steam client which is needed to make that happen. My understanding is that that vendor.project is just Flathub's standardized method of organizing all their containers and shouldn't be a problem, but @nanonyme should be able to clarify if that's not the case.

IANAL, but I don't see any legal issues with calling the Steam client exactly what it is.

Off-topic: @nanonyme, there's a minor typo in that description for you to ponder.

**Comment by flibblewibble** [comment]
The issue is I see people come into forums thinking it's an official Valve package when it is not and then we try to explain it is not an official package and where to report issues, they still don't understand that

**Comment by nanonyme** [comment]
@flibblewibble note that app does say bugs need to be reported to the issue tracker on Flathub project. The entire manifest is publicly readable on Flathub. If an end user does not want to trust Flathub packaging infrastructure , then they should not have manually enabled the repo in the first place. There is nothing extra included in the app that wouldn't be strictly to fix quirky games.

@kisak-valve yes, in general dotted name does not mean to imply package originates from Valve. Flathub actively encourages upstream ownership of apps but in this case Valve does not back the project and we have done our best to try to make that fact clear through app metadata. If there's further suggestions to improve situation through metadata, we will definitely be willing to merge changes or improve it ourselves.

**Comment by nanonyme** [comment]
With regards to distribution: the application ships Valve's Steam bootstrapper verbatim. Any further procurement of Valve binaries happens through Steam platform which is bootstrapped on user machine during runtime. This is exact same approach taken by all distros that ship Steam repackaged through distro packages.

**Comment by flibblewibble** [comment]
Shipping verbatim is one thing, modification can result ina  breach of trademarks (one example being Linux Mint's customisation of Mozilla's Firefox is breaching Mozilla's trademarks in a repackaging)
