### ISSUE TITLE
Steam not launching on Ubuntu 20.10 after upgrade

### ISSUE THREAD

**Issue by 3ndri** [ValveSoftware/steam-for-linux#7469]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu 20.10 64 bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam worked fine but after upgrading to 20.10 it show the following message when I try to launch 
 " You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
libdrm.so.2 "
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @3ndri, sounds fairly straight forward. Steam needs the host system to provide a working 32 bit OpenGL driver stack. Please run `sudo apt install libgl1:i386 libgl1-mesa-dri:i386` and retest.

If apt wants to remove a bunch of packages for some reason, do not let it proceed.

**Comment by 3ndri** [comment]
when I try that command I get:
"The following packages have unmet dependencies:
 libssl1.1:i386 : Depends: debconf:i386 (>= 0.5) or
                           debconf-2.0:i386
E: Unable to correct problems, you have held broken packages."

**Comment by kisak-valve** [comment]
Let's find out a little more about those packages. Please share the output of `apt policy libssl1.1 libssl1.1:i386 debconf`.

**Comment by 3ndri** [comment]
libssl1.1:
  Installed: 1.1.1g-1+ubuntu19.10.1+deb.sury.org+1
  Candidate: 1.1.1g-1+ubuntu19.10.1+deb.sury.org+1
  Version table:
 *** 1.1.1g-1+ubuntu19.10.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     1.1.1f-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu groovy/main amd64 Packages
libssl1.1:i386:
  Installed: (none)
  Candidate: 1.1.1f-1ubuntu4
  Version table:
     1.1.1f-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu groovy/main i386 Packages
debconf:
  Installed: 1.5.74
  Candidate: 1.5.74
  Version table:
 *** 1.5.74 500
        500 http://archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by kisak-valve** [comment]
Well `1.1.1g-1+ubuntu19.10.1+deb.sury.org+1` is an interesting package version. Looks like a leftover from when you were on Ubuntu 19.10 and pulled it in from somewhere outside of Ubuntu's repositories.

Apt's multiarch implementation requires that the 32 bit and 64 bit variant of any package must have the same version and it also does not like to downgrade packages.

Maybe try something like `sudo apt install libssl1.1=1.1.1f-1ubuntu4 libssl1.1:i386=1.1.1f-1ubuntu4`. Again, if apt asks to remove a bunch of packages, do not let it proceed. This command should be telling apt to explicitly give you the package version we just found in groovy's repository and make it downgrade the 64 bit variant. Then retest if that clears the blocker for your earlier attempt to install 32 bit mesa.

As an optional followup step, you can also run something like `apt-mark auto libssl1.1 libssl1.1:i386` to tell apt that it's okay to cleanup those packages if for some reason they're no longer needed in the future.

**Comment by 3ndri** [comment]
I tried it. But as I understood it it will downgrade libssl1.1 but will also remove some packages simultaneously and as you said I should not let it remove any other packages.

**Comment by 3ndri** [comment]
The following additional packages will be installed:
  libc6:i386 libcom-err2:i386 libcrypt1:i386 libgcc-s1:i386
  libgssapi-krb5-2:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-3:i386
  libkrb5support0:i386 libnsl2:i386 libnss-nis:i386 libnss-nisplus:i386
  libtirpc3:i386
Suggested packages:
  glibc-doc:i386 locales:i386 krb5-doc:i386 krb5-user:i386
Recommended packages:
  libidn2-0:i386
The following packages will be REMOVED:
  libmysqlclient-dev libnode-dev libssl-dev node-gyp npm
The following NEW packages will be installed:
  libc6:i386 libcom-err2:i386 libcrypt1:i386 libgcc-s1:i386
  libgssapi-krb5-2:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-3:i386
  libkrb5support0:i386 libnsl2:i386 libnss-nis:i386 libnss-nisplus:i386
  libssl1.1:i386 libtirpc3:i386
The following packages will be DOWNGRADED:
  libssl1.1
0 upgraded, 14 newly installed, 1 downgraded, 5 to remove and 6 not upgraded.
Need to get 6,149 kB of archives.
After this operation, 3,973 kB disk space will be freed.
Do you want to continue? [Y/n]

**Comment by kisak-valve** [comment]
You'll need to evaluate the packages that apt wants to remove and get them updated as needed for groovy or they can go away if you don't use them anymore. That's outside of what experience I personally can offer here.

**Comment by 3ndri** [comment]
well, i removed them and now steam seems to work fine

**Comment by kisak-valve** [comment]
Glad to hear it. Closing because this was a package management issue.

**Comment by 3ndri** [comment]
Thank you anyway!
