### ISSUE TITLE
Steam displays out-of-date warning at startup

### ISSUE THREAD

**Issue by Henne91** [ValveSoftware/steam-for-linux#747]
Everytime I start Steam it displays a warning dialog telling me "Your steam package is out of date. Please get an updated version from your package provider or directly from http://repo.steampowered.com/steam for supported distributions."

However, I recently updated to the latest version and when I click on "Steam" -> "Check for client updates" within the Steam client menu it says that it is up-to-date.

**Comment by licaon-kter** [comment]
Have this too now, I'm on the lastest version ( 1.0.0.50 from 05-May-2015 ) w/ latest beta.

Any idea what the error is actually about?

**Comment by licaon-kter** [comment]
Updated to Debian 1.0.0.51 and it's "old and needs updating" now again.

**Comment by licaon-kter** [comment]
Still getting this on every start. :(

**Comment by SkUrRiEr** [comment]
This is still happening on 1.0.0.51 on Debian Testing

**Comment by Kiibakun** [comment]
This is affecting me too.
1.0.0.51 on Ubuntu GNOME 16.04

**Comment by licaon-kter** [comment]
What is checked exactly?

**Comment by SkUrRiEr** [comment]
For reference, this warning went away when I installed the Debian package ( https://packages.debian.org/stretch/steam ) instead of the official Steam one.

**Comment by licaon-kter** [comment]
Not difference here
```
 > apt-cache policy steam 
steam:i386:
  Installed: 1.0.0.51-1
  Candidate: 1.0.0.51-1
  Version table:
 *** 1.0.0.51-1 500
        500 http://ftp.de.debian.org/debian unstable/non-free i386 Packages
        100 /var/lib/dpkg/status
     1.0.0.51 500
        500 http://repo.steampowered.com/steam precise/steam i386 Packages
```

**Comment by davidgiven** [comment]
Same here:

steam:i386:
  Installed: 1.0.0.51-1
  Candidate: 1.0.0.51-1
  Version table:
 *** 1.0.0.51-1 990
        990 http://ftp.ch.debian.org/debian testing/non-free i386 Packages
        500 http://ftp.ch.debian.org/debian unstable/non-free i386 Packages
        100 /var/lib/dpkg/status
     1.0.0.51 500
        500 http://repo.steampowered.com/steam precise/steam i386 Packages
     1.0.0.49-1 500
        500 http://ftp.ch.debian.org/debian stable/non-free i386 Packages

**Comment by licaon-kter** [comment]
And another update for `steam:i386` to `1.0.0.52-1`, not helping. :(

**Comment by licaon-kter** [comment]
Removed `steam-launcher` package ( https://github.com/ValveSoftware/steam-for-linux/issues/4321#issuecomment-214004311 ) and looks fixed for now.
No idea why I had both that and `steam:i386`.
