### ISSUE TITLE
War Thunder (236390) launcher crash if gameoverlayrenderer.so preloaded

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#7478]
#### Your system information

* Steam client version (build number or date): Nov 20 2020 at 03:08:50
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
War Thunder game launcher crashes if `gameoverlayrenderer.so` is in LD_PRELOAD
Temp. fix: `LD_PRELOAD="" %command%`
Unchecking overlay checkbox in game settings does not help

#### Steps for reproducing this issue:

1. Install War Thunder
2. Launch

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue is already being tracked at #6210. Closing as a duplicate.

**Comment by XakepSDK** [comment]
This is different issue. Clicking `Play` in steam should launch War Thunder launcher and this launcher crashes immediately if `gameoverlayrenderer.so` is present
