### ISSUE TITLE
Steam does not register non-steam games with space in pathname.

### ISSUE THREAD

**Issue by ralmond** [ValveSoftware/steam-for-linux#7480]
#### Your system information

* Steam client version (build number or date): 2020-10-28
* Distribution (e.g. Ubuntu):  Ubuntu 20.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When adding a non-steam game, Steam client does not properly register game if there is a space in the path.

Here is the .desktop file:
```
[Desktop Entry]
Encoding=UTF-8
Value=1.0
Type=Application
Name=Nightmares from the Deep: The Cursed Heart
GenericName=Nightmares from the Deep: The Cursed Heart
Comment=Nightmares from the Deep: The Cursed Heart
Icon=/home1/ralmond/Games/Nightmares from the Deep The Cursed Heart/support/icon.png
Exec="/home1/ralmond/Games/Nightmares from the Deep The Cursed Heart/start.sh" ""
Categories=Game;
Path=/home1/ralmond/Games/Nightmares from the Deep The Cursed Heart
```
When imported into Steam, I get the following in the properties dialog:
![Properties](https://user-images.githubusercontent.com/1767426/99858854-72539d00-2b5c-11eb-92cb-83a8049f556a.png)

Two issues are visible, one is not.
1) The pathname is truncated at the first space.
2) There seems to be a redundant quote in front of both the application and directory name.
3) [Not in screen shot] The icon (note space in pathname) is not found.

Additionally, if I have two games whose paths are the same up to the first space (in this case "Nightmares from the Deep 2")  Steam will not see the second game even if I explictly navigate to and select the .desktop file.

#### Steps for reproducing this issue:

1. Install a non Steam game with a space in the pathname.
2. Select "Add a Game> Add a non-steam game ..."
3. Select the .desktop file for the game.

Two example .desktop files are pasted below.
[Nightmares_from_the_Deep_2_The_Sirens_Call_1.desktop.txt](https://github.com/ValveSoftware/steam-for-linux/files/5576590/Nightmares_from_the_Deep_2_The_Sirens_Call_1.desktop.txt)
[Nightmares_from_the_Deep_The_Cursed_Heart_1.desktop.txt](https://github.com/ValveSoftware/steam-for-linux/files/5576591/Nightmares_from_the_Deep_The_Cursed_Heart_1.desktop.txt)

3.

**Comment by kisak-valve** [comment]
Hello @ralmond, this issue is already being tracked at #5220. Closing as a duplicate.
