### ISSUE TITLE
(DeepRock Galactic) Processing vulkan shaders instantly freezing my computer

### ISSUE THREAD

**Issue by hypnohacker** [ValveSoftware/steam-for-linux#7482]
#### Your system information

* Steam client version (build number or date): 
>Oct 28 202
>Steam API: v020
>Steam Package versions: 1603992987

* Distribution (e.g. Ubuntu): 
>Pop OS 20.04 LTS
* Opted into Steam client beta?: [Yes/No]
>no
* Have you checked for system updates?: [Yes/No]
>steam, os, drivers are up to date

####
8Gb Ram, i3770k, GTX660, Pop OS 20.04 LTS, no Steam Beta, drivers are up to date:

**When i'm trying to launch deep rock galactic - steam tries to process Vulkan Shaders and _instantly_ frezes with no progress. If i'll skip the process - game starts.**

In other unreal games (Insurgency sand storm for example - the process of vulkan shaders processing could be finished).

**Comment by kisak-valve** [comment]
Hello @hypnohacker, this issue is already being tracked at https://github.com/ValveSoftware/Fossilize/issues/84. Closing as a duplicate.
