### ISSUE TITLE
Why Does Steam Use its own FIle Browser than OS's? [Feature Request]

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/steam-for-linux#7485]
Steam's File Browser is in need of serious Improvement. Searching and navigating is very painful in my opinion.
![2b7494e00a6bd80d0a4a74c151f6b668](https://user-images.githubusercontent.com/20986867/147104240-743eeb25-1530-4df5-a93d-80257581d3ff.png)

Theres no quick shortcuts to home folder or Other common folders other than Root.
There is no way to jump to a file based on its first letter (as in when you press J it would jump to files starting with J in that folder)
There is no search function.
And there is no Photo Preview (Very important for selecting profile image/Uploading a Photo in Steam chat)
How come Programs like Discord and Others are able to Utilize the OS's File browser to select a photo/file
But steam on Linux uses it's own browser?

in my Opinion The Steam file Browser should either be improved and made up-to-date. Or Steam should find a way to open The OS's File Browser Like Caja..and Other derivatives. 

Note:I'm Running Ubuntu 20.10 With the Latest Steam Client (Beta)

**Comment by LeSnake04** [comment]
it would be pretty cool if steam would just use Thunar (or whatever your favourite file browser is) just like every other Program!

**Comment by shytzedaka** [comment]
> it would be pretty cool if steam would just use Thunar (or whatever your favourite file browser is) just like every other Program!

I agree! Currently i am Using Caja. I am Assuming Debian/Ubuntu Has a Call where it calls the Default FIle manager that is installed.

**Comment by eathtespagheti** [comment]
I think it's to keep the same UI as the Windows version

**Comment by shytzedaka** [comment]
> I think it's to keep the same UI as the Windows version

Well as i said. If Steam's browser was improved. i wouldn't mind it at all.

**Comment by bonkmaykrQ** [comment]
For the steam overlay, I can understand why, since it would draw focus away from the game window and for games that don't support alt-tab it would... Uh. Really f** things up.

Otherwise, I agree that perhaps it's a good idea to use the system's file manager for the built in browser when not in the steam overlay, this goes for Windows too by the way. 

However, I also think that in order to improve the experience *in-game*, we should work on a new and better file browser that can display thumbnails and such and also build it into source engine games if possible. It would really help with the overlay's web browser and also when searching for spray files or using the workshop upload dialog in TF2 or CS:GO.

**Comment by shytzedaka** [comment]
Yup

**Comment by LeSnake04** [comment]
we definetly need bookmarks!

I hate having to find my home directory every time I open the file manager

**Comment by LeSnake04** [comment]
There is something called xdg on Linux,  that allows you to communicate with programs like the file manager based on what the user set in their system settings.

**Comment by kermitfrog** [comment]
A few more things the steam file request dialog does not do (at least in select-directory mode):

- select directory when pressing Return (aka Enter)
- *not* show hidden files (should be switchable via shortcut)
- make it possible to simply enter (or paste) a path as text. Ideally with auto-completion

The easiest way to get all this, is of course to just use the systems dialog.

**Comment by knope** [comment]
> we definetly need bookmarks!
> 
> I hate having to find my home directory every time I open the file manager

Yes, or at the very least the ability to type the path out.

**Comment by shytzedaka** [comment]
Another issue Related to Steam's File Browser:
https://github.com/ValveSoftware/steam-for-linux/issues/8314

**Comment by kisak-valve** [comment]
Hello, the [2023-04-27](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3705942560777969861) Steam client beta update should try to use xdg-desktop-portal where available.

**Comment by choskyo** [comment]
> Hello, the [2023-04-27](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3705942560777969861) Steam client beta update should try to use xdg-desktop-portal where available.

I've started using the new steam beta client and "Upload a Screenshot" for me is currently doing nothing. 
I've double checked that xdg-desktop-portal is installed and nothing new is output to the terminal if I try running steam via that then trying to upload.
In-case it helps, "add non-steam game -> browse" now does use my desktop file picker whereas before I'm pretty sure that also used the steam one.

Are there any logs I could share to help?

**Comment by kisak-valve** [comment]
Hello @choskyo, please add a note to #9373.

**Comment by shytzedaka** [comment]
As seen in recent developments in #9373 and that it is now confirmed working. after a few wayland tests and tests with Other DEs we could be able to finally close this issue :)

**Comment by shytzedaka** [comment]
Confirmed working on Wayland. Steam Version:  1685072487
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/95b8a6e9-7258-43a0-b83e-2a44bc4eb9a5)

**Comment by sTiKyt** [comment]
> Hello, the [2023-04-27](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3705942560777969861) Steam client beta update should try to use xdg-desktop-portal where available.

Well, now it simply doesn't open any file manager at all instead of using old one

**Comment by shytzedaka** [comment]
> Update 2: It seems to open my file browser now, but it doesn't load the file I chose anyway… Jeez, just make it optional or something, old file manager did its job just fine, and now it's all broken

Hey, What OS, File Manager, And Steam beta client version are you on?

**Comment by sTiKyt** [comment]
> > Update 2: It seems to open my file browser now, but it doesn't load the file I chose anyway… Jeez, just make it optional or something, old file manager did its job just fine, and now it's all broken
> 
> Hey, What OS, File Manager, And Steam beta client version are you on?
> 

Latest steam beta, Arch Linux, Thunar, i3wm
