### ISSUE TITLE
If Steam was launched via steam://rungame/ the game specified will be launched again after Steam restarts to apply updates

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#7498]
#### Your system information

* Steam client version (build number or date): Nov 30 2020, at 18:34:44
* Distribution (e.g. Ubuntu): Fedora 32 Workstation
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If Steam was originally launched via a `steam://rungame/` link, following an update to Steam and a subsequent restart, Steam will launch said game again once restarted, along with whatever parameters it was launched with (such as replay ID for CS:GO).

#### Steps for reproducing this issue:

1. Start Steam via a `steam://rungame/` pseudo-protocol link
2. Have Steam update itself
3. Let Steam restart itself
4. Observe that Steam starts up the game again

**Comment by kisak-valve** [comment]
Hello @Newbytee, this issue is already being tracked at #4461. Closing as a duplicate.
