### ISSUE TITLE
Steam Update Dialogue displays black

### ISSUE THREAD

**Issue by alkaris2** [ValveSoftware/steam-for-linux#7500]
#### Your system information

* Steam client version (build number or date): Dec 2 2020
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
From every Steam update for Linux this has been an ongoing issue for a long time. Everytime there's a new update to be downloaded and install, I'm shown the Steam Update Dialogue. But the problem here is I cannot see or read what the notes are for the new update, because it just displays black on the window where it's supposed to show me this information.

![flameshot_2020-12-02__06_06_13_PM](https://user-images.githubusercontent.com/73155407/100843027-aa969c00-34c9-11eb-8241-24f049743f3c.png)

This has been like this since many updates ago, this probably goes way back to when Steam got the new UI changes in Beta, this dialogue box just started rendering incorrectly. You would use to just click on the window box to get it show properly, but as of more recent it stopped doing that. It's very minor thing, but it's annoying being shown this update dialogue, but then can't read what's new.

#### Steps for reproducing this issue:

1. Run and test on Linux
2. 
3.

**Comment by kisak-valve** [comment]
Hello @alkaris2, this issue is already being tracked at #6451. Closing as a duplicate.
