### ISSUE TITLE
Vulkan games launched through steam have the performance drop after 40 minutes

### ISSUE THREAD

**Issue by 6gk** [ValveSoftware/steam-for-linux#7505]
#### Your system information

* Steam client version (build number or date): Oct 28 2020, at 23:35:02  (My local timezone is UTC+1000, if that affects this)
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: No 
- Nvidia GTX 1050 (prop drivers 455.45.01)
- Intel Pentium G4560 (2c4t, 3.5GHz)
- steam system info: http://0x0.st/i70V.txt

#### Please describe your issue in as much detail as possible:

Whenever I launch a vulkan game through steam the performance drops massively after around 40 minutes

Games I've tested: Mirror's Edge (DXVK), Dishonored (DXVK), Shadow Of Mordor (Native, Vulkan Beta)

I have a GOG version of Superliminal which this didn't happen to, so I started to suspect steam being the issue, but I was also optimistic that nvidia fixed their drivers.

So I tried reinstalling Mirror's Edge through steam, and the same problem happens, then I found a cracked exe file, launched it directly with proton and I didn't experience a sudden performance drop. Admittedly I only played for 52 minutes, but in the past, 45 minutes has been the upper end of "fine" performance.

I didn't test adding Superliminal as a non-steam game and seeing if the performance drops.

#### Steps for reproducing this issue:

1. Open steam
2. Launch a vulkan game
3. Play for around 40 minutes

**Comment by kisak-valve** [comment]
Hello @6gk, in general we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues). Let's use this issue report to focus on Shadow of Mordor. It may be worthwhile to also mention this issue to Feral Interactive, since they did the Linux port of the game.

Can you keep an eye on PCIe bandwidth utilization in nVidia's X settings utility and when the game starts under-performing, does that also become a high percentage? I suspect that the video card is running out of vram, and when that happens, then the video driver can fallback to using system ram with a severe performance penalty.

**Comment by 6gk** [comment]
@kisak-valve Thanks for the fast reply.

I have used `nvtop` to check the GPU/VRAM usage of Shadow Of Mordor in the past, and the VRAM didn't appear to be maxing out, however I think the GPU usage did do a drop, I cannot recall this information with 100% certainty so take this with a grain of salt.

I will do some more testing (including launching superliminal through steam) and try remember to get screenshots of relevant info this time. I know for a fact that it wasn't overheating, since when the drop happened the temperature was around the same as most of the other time playing.

**Comment by 6gk** [comment]
Adding Superliminal as a non-steam game, even though it didn't display as "playing", the screenshot button didn't work, and the steam overlay didn't show, it did make the performance drop after 40 minutes. (Yesterday when I wasn't using steam it worked for 1h20m at which point I manually exited, i didn't experience any performance issues)

I didn't get as many screenshots during play as I wanted to (I did a typo which made the auto screenshot loop not work), but the VRAM usage was up to 75% at least 6 minutes before the crash. The temp was around 68 Celsius every time I looked at it, for both the cpu and gpu.

![novideographic](https://user-images.githubusercontent.com/40295114/101113112-68d13700-362a-11eb-9664-720f5a95b6ba.png)

**Comment by 6gk** [comment]
I think it's worth mentioning that I've had this issue for a while, and have made a [reddit post](https://www.reddit.com/r/linuxquestions/comments/irwzdr/fps_suddenly_drops_after_around_40_minutes_of_play) (warning, contradictory & confusing, read summary below instead) in the past. It's only now that I feel like I have enough info to feel like a bug report could be useful.

Summary of the reddit post is basically I narrowed it down to vulkan and of found out that:

 - Shadow Of Mordor's performance problem was related to manual camera movement after that time period (Superliminal's didn't seem to be)
 - cpu governor, DE/WM, distro (arch, popos, ubuntu), kernel (lowlatency, xanmod, normal), mouse/controller all didn't matter

**Comment by kisak-valve** [comment]
Blind guess, does setting the game's launch options to `LD_PRELOAD="" %command%` have an effect?

**Comment by 6gk** [comment]
Good question, I'll give it a shot.

**Comment by 6gk** [comment]
@kisak-valve Wow.. That actually worked. Thank you *so* much! (Was playing for 1h9m without any issues)

Should this issue be closed now that a workaround has been found, or stay open for further investigation so the workaround isn't needed?

Of course, don't hesitate to ask if you need any more info.

**Comment by kisak-valve** [comment]
That workaround hints that there's an issue in the Steam Overlay. Avoiding it doesn't make the issue any less valid.

**Comment by kisak-valve** [comment]
Looking at your system information `/home/mirror/opt/apps/.steam/debian-installation` is an abnormal install location and whatever modification that was done to set that up appears to be incomplete and causes
```
ERROR: [Loader Message] Code 0 : /home/mirror/.steam/debian-installation/ubuntu12_64/steamoverlayvulkanlayer.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : /home/mirror/.steam/debian-installation/ubuntu12_32/steamoverlayvulkanlayer.so: cannot open shared object file: No such file or directory
```
Note the lack of /opt/apps in the path.

**Comment by 6gk** [comment]
Alright. I assumed this was a type of "at the mercy of the drivers" issue since I've never seen anyone have an issue similar to this, so it wouldn't be that easy to debug.

Also, I'm pretty sure (but again, not 100%, memory is kinda fuzzy) that at one point around the time of the reddit post I had the steam overlay checkbox disabled and it still happened.

**Comment by 6gk** [comment]
Ooh, now that is interesting. Very interesting.

I just change my `HOME` variable on launch since I dislike having dotfiles in my home directory.

**Comment by 6gk** [comment]
@kisak-valve That was some good investigating. I changed the path in all 4 files in xdg_data/vulkan/implicit_layer.d, and it appears to be fixed. That also explains why in the past the overlay on vulkan didn't even work in the past, which I thought nothing of.

Thanks and sorry for any trouble I caused. Glad this was just an (admittedly stupid) issue specific to me rather than an extremely obscure bug.
