### ISSUE TITLE
Gloves in CS:GO on Linux do not properly render

### ISSUE THREAD

**Issue by Linus42069** [ValveSoftware/steam-for-linux#7513]
#### Your system information

* Steam client version : 6 december 2020
* Distribution :  Debian Buster 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue: I do not know how to replicate the issue

-yes I have vulkan shaders installed

**Comment by kisak-valve** [comment]
Hello @Linus42069, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2102. Closing as a duplicate.
