### ISSUE TITLE
Civilization V crashes during gameplay

### ISSUE THREAD

**Issue by MaxPayneFH** [ValveSoftware/steam-for-linux#7515]
#### Your system information

* Steam client version (build number or date): 07/12/2020
* Distribution (e.g. Ubuntu): Fedora 32
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

    Kernel Version:  5.9.11-100.fc32.x86_64
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20201203.1

Video Card:
    Driver:  X.Org Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.11-100.fc32.x86_64, LLVM 10.0.1)
    Driver Version:  4.6 (Compatibility Profile) Mesa 20.2.3

#### Please describe your issue in as much detail as possible:

During gameplay the game suddenly closes, the time it takes for the crash to occur varys, it can crash as soon as a new game is started or after 30 minutes of game play.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The game should run for hours without issues like it did in the past.
There are some error messages in the terminal:

<script src="https://gist.github.com/MaxPayneFH/6aec4f0f6eab06f4936e6a37ccec18c3.js"></script>

https://gist.github.com/MaxPayneFH/6aec4f0f6eab06f4936e6a37ccec18c3

#### Steps for reproducing this issue:

1. Launch the game
2. Load a savegame or create a new game
3. Wait for the game to crash

Could you please look into this issue?

Any help would be appreciated.

**Comment by kisak-valve** [comment]
Hello @MaxPayneFH, this issue should also be mentioned to the game's dev(s) if it hasn't been already.

**Comment by 1000101** [comment]
@MaxPayneFH have you seen/tried this https://steamcommunity.com/app/8930/discussions/1/2568690592363871352/ ? I'm not sure if that's the case here, but it might be worth trying out.

**Comment by MaxPayneFH** [comment]
@1000101 Your guess was spot on, I recently upgraded my CPU from a 8 threaded FX 8350 to a 16 threaded Ryzen 7 2700X.
After changing MaxSimultaneousThreads to 16(was previously set to 8) the game has been running fine.

Thanks a lot for the help.
