### ISSUE TITLE
Steam for Linux client automatically reverts to default library location without warning the user.

### ISSUE THREAD

**Issue by skilo83** [ValveSoftware/steam-for-linux#7517]
#### Your system information

* Steam client version (build number or date): 
Built dec 7 2020 at 18:04:33
Steam API: v20
Steam package versions: 1607372145
* Distribution (e.g. Ubuntu): 
ubuntu 20.04 LTS
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The Linux client will automatically use the default steam library location if it cannot find the user specified default location, and it does so without even warning the user about it. This is a huge problem because steam usually has it's default location on the system drive. If the end user is unaware of what drive the steam client is using as the default, it could easily eat up all the system drive space and possibly lock up the system. There should be some prompt letting the user know or even better. Just throw an error and don't just assume that drive doesn't exist anymore and revert back to it's own default location without asking first.

#### Steps for reproducing this issue:

1. Create a new default library location on a secondary drive
2.  Have the drive NOT mounted at boot
3.  Start steam for Linux client and download a game. You will see the client automatically defaults back to it's original default library location without warning the user.

**Comment by kisak-valve** [comment]
Hello @skilo83, this issue is already being tracked at #4383. Since this issue report is well written, I've gone ahead and transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/4383#issuecomment-741481158.

Closing as a duplicate.
