### ISSUE TITLE
Steam app doesn't work in Android 4.4.2

### ISSUE THREAD

**Issue by vitacell** [ValveSoftware/steam-for-linux#7525]
Hi, some years ago I had working Steam app, but even old Steam app versions don't work on Android 4 anymore. I can't have my Steam guard enabled, and everytime I want to sell something, I have to wait 15 days, which makes me to not sell anything.

**Comment by kisak-valve** [comment]
Hello @vitacell, this issue tracker is for the Steam for Linux client. Issues with the Android app are out of scope here.
