### ISSUE TITLE
Changelog empty on update dialog

### ISSUE THREAD

**Issue by h1z1** [ValveSoftware/steam-for-linux#7526]
#### Your system information

* Steam client version (build number or date): Dec 7 2020
* Distribution: CentOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Can't find existing reports but I swear it has been previously and was fixed.  Update prompt appears with a black space for the changelog.

Client version above reflects preupdate.

#### Steps for reproducing this issue:

1.   Run steam
2.  Wait for an update
3.  ...

![steam_blank_update_dialog](https://user-images.githubusercontent.com/17220053/101767415-2e481e00-3ab2-11eb-8351-6885aa59aa6a.png)

**Comment by kisak-valve** [comment]
Hello @h1z1, this issue is already being tracked at #6451. Closing as a duplicate.
