### ISSUE TITLE
three Shadowrun games broken by last linux client update

### ISSUE THREAD

**Issue by UniqueUserajs** [ValveSoftware/steam-for-linux#7528]
#### Your system information

* Steam client version (build number or date):  v0.20201203.1
* Distribution (e.g. Ubuntu): ubuntu 20.04 64-bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

"Shadowrun: Hong Kong", "Shadowrun: Dragonfall", and "Shadowrun Returns" were all broken by the latest linux client update. The screen turns black as if the game were about to start, then returns to the desktop

#### Steps for reproducing this issue:

1. pick one of the Shadowrun games in the library
2. try to run it
3.

**Comment by kisak-valve** [comment]
Hello @UniqueUserajs, this issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/317, feel free to add a note that the other closely related games are also affected.

Closing as a duplicate.
