### ISSUE TITLE
mafia trainer doesn't see the game

### ISSUE THREAD

**Issue by stsp** [ValveSoftware/steam-for-linux#7529]
#### Your system information

* Steam client version (build number or date): 
Dec 9, 2020

* Distribution (e.g. Ubuntu): 
Fedora

* Opted into Steam client beta?: [Yes/No]
Yes

* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
There is a mafia trainer here:
https://www.moddb.com/games/mafia/downloads/mafia-trainer-19
It can be started, it reacts on double-click,
shows help, etc. But when you launch the
game, the trainer keys are not available there.
It just doesn't see the game.

#### Steps for reproducing this issue:

1. Run mafia trainer
2. Run mafia game
3. Press f12

Nothing happens.
f12 should show the trainer in-game menu.

I think this problem is generic with all trainers,
not specific to this one. Perhaps wine doesn't
allow different processes to access each other's
memory, keyboard and screen?

**Comment by kisak-valve** [comment]
Hello @stsp, with the information given, I have to assume that you're running the original Mafia game with Proton and the native linux Steam client. The alternative, running the Steam for Windows client and game in wine is not supported here at all.

With those assumptions, we're tracking issues with games run with Proton in the Proton issue tracker, and one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2812#issuecomment-742862794.
