### ISSUE TITLE
Hairbrained Schemes Shadowrun Dragonfall fails to launch on linux following recent Steam Client update

### ISSUE THREAD

**Issue by dragonbitestail** [ValveSoftware/steam-for-linux#7535]
#### Your system information

* Steam client version (build number or date): 
  **Issue was not present weekend of Nov 28/29,  Steam client update Dec 7th (1607372145)**
* Distribution (e.g. Ubuntu): 
  **XUbuntu 18.04** /  **Intel CPU** / **Nvidia GTX 1080**
* Opted into Steam client beta?: [Yes/No]
  **No**
* Have you checked for system updates?: [Yes/No]
  **Yes**  Only after I ran into the issue.   Only other change was to upgrade Discord client (discord-0.0.13.deb)

Also verified files.

#### Please describe your issue in as much detail as possible:
  Screen goes blank then Game fails to launch.  Seems to be triggering my screen lock.

  Several people have started reporting this issue in the Game's Steam Discussion topics. Some examples:
 [General](https://steamcommunity.com/app/300550/discussions/0/2990917484136800900/) 
 [Bug Reports](https://steamcommunity.com/app/300550/discussions/1/2968398851815378309/)

Last lines from Game's "output.txt"
`/home/USER/.steam/steam/steamapps/common/Shadowrun Dragonfall Director's Cut/Dragonfall_Data/Plugins/x86/libsteamwrap.so : Could not load a dll file. Make sure that the steam_api.dll/libsteam_api.dylib file is placed at the correct location. See the documentation for more info.
 
(Filename: /BuildAgent/work/d3d49558e4d408f4/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 53)

Attempting to find steamwrap.so
 
(Filename: /BuildAgent/work/d3d49558e4d408f4/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 53)
`

#### Steps for reproducing this issue:

1. **Attempt to Launch the Game from Steam Client or Game's Command line Shell Scripts.**

**Comment by kisak-valve** [comment]
Hello @dragonbitestail, this issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/317 and should already be fixed in Steam's beta client. Please opt into the Steam client beta.

Closing as a duplicate.
