### ISSUE TITLE
Linux Mint 19.6, Cinnamon, 64 bit - Doom Eternal ?

### ISSUE THREAD

**Issue by alexei-28** [ValveSoftware/steam-for-linux#7537]
I use Linux Mint 19.6, Cinnamon, 64 bit.
Is it possible to play Doom Eternal on Steam?

**Comment by kisak-valve** [comment]
Hello @alexei-28, in general, this is an issue tracker for issues with the Steam for Linux client and not a general discussion forum. However, we're using one issue report per unofficially supported game title on the Proton issue tracker and that's where you'd find other people interested in this game, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3773#issuecomment-743806419.
