### ISSUE TITLE
Cyberpunk 2077 / Proton issue.

### ISSUE THREAD

**Issue by siliconjesus** [ValveSoftware/steam-for-linux#7540]
#### Your system information

* Steam client version (build number or date): Dec 11, 2020 at 00:39:58
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Cyberpunk 2077 locks hard on mission "The Heist" and I'm unable to proceed.  The game has locked up on other missions, but I was able to quit the game (xkill) then restart and restore.  I lock up at different parts of the dialog between V and Jackie (and the Limo Service) - but I can't get past it to the next save point.  Logfile attached (12.9MB).
[steam-1091500.log](https://github.com/ValveSoftware/steam-for-linux/files/5683913/steam-1091500.log)

#### Steps for reproducing this issue:

1. Get into Limo at the beginning of "The Heist" mission
2. Go through dialog options like usual, the game will lock either during one of the conversations or when you arrive at the destination.
3.

**Comment by kisak-valve** [comment]
Hello @siliconjesus, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-743923963.
