### ISSUE TITLE
remote play broken

### ISSUE THREAD

**Issue by christianrauch** [ValveSoftware/steam-for-linux#7542]
#### Your system information

* Steam client version: 1607372145, Dec 7, 2020
* Distribution: Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The remote play as client under Linux used to work around 4. Dec but is broken with the version from 7. Dec. After accepting an invitation, I get the error message: `The streaming client exited unexpectedly (2)`.

The problem does not appear in the current beta version.

#### Steps for reproducing this issue:

1. accept remote play invitation

**Comment by kisak-valve** [comment]
Hello @christianrauch. please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please check if changing `Steam` -> `Settings` -> `Remote Play` -> `Advanced Client Options` -> `Enable hardware decoding` checkbox has an effect.

**Comment by christianrauch** [comment]
system information: https://pastebin.com/PaVBsFkh

Changing the hardware acceleration did not make a difference.

**Comment by minisori** [comment]
Hi, i had similar problem. Running from terminal i found out it was missing a library that was inside ubuntu12_32 and was solved adding that folder to LD_LIBRARY_PATH.
LD_LIBRARY_PATH=~/.steam/root/ubuntu12_32:$LD_LIBRARY_PATH steam

**Comment by c3ypt1c** [comment]
I have the same problem. Exactly the same setup and steps to reproduce the problem but on Arch Linux.

System Information: [https://pastebin.com/19J2MUa1](https://pastebin.com/19J2MUa1)

**Comment by JanThomas118** [comment]
I have had the same issue (https://ghostbin.com/paste/SF0U2), the workarround with overloading LD_LIBRARY_PATH has worked for me.

**Comment by christianrauch** [comment]
The issue disappeared with the latest update from Dec 20, 2020.

**Comment by kisak-valve** [comment]
Closing per the last comment. Most likely related to https://github.com/ValveSoftware/steam-runtime/issues/317#issuecomment-742911174.

**Comment by hoxu** [comment]
For people coming from search: this error still happens in the stable branch, but is fixed in Steam beta.

**Comment by christianrauch** [comment]
I am facing the same issue again and changing to the beta fixes the issue (again). Could you please verify that the "remote play together" function works before pushing out stable releases?

**Comment by hardwareadictos** [comment]
Having the same issue here on Debian 11

**Comment by kisak-valve** [comment]
Hello @hardwareadictos, the investigation on this issue report has concluded. Please open an new issue report.
