### ISSUE TITLE
Game not being seen by Steam Client when running via command line

### ISSUE THREAD

**Issue by msmafra** [ValveSoftware/steam-for-linux#7543]
* Steam client version (build number or date): Dec 7 2020, at 18:04:33
* Distribution (e.g. Ubuntu): Fedora 33 Workstation
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
To run the game via custom command line or .destkop file and it use the Steam API.

#### Steps for reproducing this issue:

1. Install Cyberpunk 2077 (I think it would work with any game). I don't have CP2077 any more but I noticed it before uninstalling;
2. Run via shell:
```
GAMECODE=1091500
GAMEPATH=/mnt/480GB/Games/steamapps/common/Cyberpunk\ 2077/bin/x64/Cyberpunk2077.exe
ENABLE_VKBASALT=0 MANGOHUD=0 __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia gamemoderun STEAM_COMPAT_DATA_PATH=/mnt/480GB/Games/steamapps/compatdata/${GAMECODE} WINEPREFIX=/mnt/480GB/Games/steamapps/compatdata/${GAMECODE}/pfx /mnt/480GB/Games/steamapps/common/Proton\ 5.13/proton run ${GAMEPATH};
```
3. Check that in the Steam Client that the game is not shown as running and the time it is open is not counting;

**Comment by kisak-valve** [comment]
Hello @msmafra, thanks for the feedback, but in general, running games from outside of Steam is not supported and expecting Steam to know that an arbitrary executable that was started on a system is a game that it should be tracking is something we wouldn't want it to be doing for anyway.
