### ISSUE TITLE
Dec 7th update controller not detected

### ISSUE THREAD

**Issue by smeejo1** [ValveSoftware/steam-for-linux#7544]
#### Your system information

* Steam client version (build number or date): Dec 7th 2020 at 18:04:33
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After the update that happened on December 7th 2020 my steam client no longer detects my xbox 360 wired controller. Clicking on Steam in the top left > Settings > Controller > General Controller Settings shows no controller detected despite it having worked fine leading up to the December 7th update. I've gone into steam > settings > controller > general controller settings and unchecked/checked the box for xbox configuration support (both in big picture mode and standard steam window), I've unplugged and re-plugged in the controller (it's wired not wireless), I've rebooted my computer completely, uninstalled and reinstalled steam,  and I've verified my Operating System does in fact recognise the controller and loads all drivers but nothing seems to have fixed the issue. I messaged steam support but they say they no longer handle Linux and say to post here. My inxi -F is as follows

> System:
> 
> Host: ***** Kernel: 5.6.19-159.current x86_64 bits: 64
> 
> Desktop: Budgie 10.5.1 Distro: Solus 4.1
> 
> Machine:
> 
> Type: Desktop Mobo: ASUSTeK model: ROG STRIX X470-F GAMING v: Rev X.0x
> 
> serial: <superuser/root required> UEFI: American Megatrends v: 5220
> 
> date: 09/12/2019
> 
> CPU:
> 
> Topology: 6-Core model: AMD Ryzen 5 2600X bits: 64 type: MT MCP
> 
> L2 cache: 3072 KiB
> 
> Speed: 2010 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 2073 2: 1915
> 
> 3: 1888 4: 2457 5: 1883 6: 1798 7: 1771 8: 2815 9: 2042 10: 2189 11: 2192
> 
> 12: 1911
> 
> Graphics:
> 
> Device-1: NVIDIA GM107 [GeForce GTX 750 Ti] driver: nvidia v: 455.45.01
> 
> Display: x11 server: X.Org 1.20.9 driver: nvidia resolution: 1920x1080
> 
> OpenGL: renderer: GeForce GTX 750 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 455.45.01
> 
> Audio:
> 
> Device-1: NVIDIA GM107 High Definition Audio [GeForce 940MX]
> 
> driver: snd_hda_intel
> 
> Device-2: AMD Family 17h HD Audio driver: snd_hda_intel
> 
> Sound Server: ALSA v: k5.6.19-159.current
> 
> Network:
> 
> Device-1: Intel I211 Gigabit Network driver: igb
> 
> IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: ******
> 
> Drives:
> 
> Local Storage: total: 1.36 TiB used: 59.44 GiB (4.3%)
> 
> ID-1: /dev/sda vendor: Crucial model: CT500MX500SSD1 size: 465.76 GiB
> 
> ID-2: /dev/sdb type: USB vendor: Western Digital
> 
> model: WD My Passport 2626 size: 931.48 GiB
> 
> Partition:
> 
> ID-1: / size: 453.31 GiB used: 59.33 GiB (13.1%) fs: ext4 dev: /dev/sda3
> 
> ID-2: /boot size: 487.3 MiB used: 118.0 MiB (24.2%) fs: vfat
> 
> dev: /dev/sda1
> 
> Swap:
> 
> ID-1: swap-1 type: partition size: 3.73 GiB used: 0 KiB (0.0%)
> 
> dev: /dev/sda2
> 
> Sensors:
> 
> System Temperatures: cpu: 40.4 C mobo: N/A gpu: nvidia temp: 33 C
> 
> Fan Speeds (RPM): N/A gpu: nvidia fan: 40%
> 
> Info:
> 
> Processes: 265 Uptime: 57m Memory: 15.61 GiB used: 2.31 GiB (14.8%)
> 
> Shell: bash inxi: 3.1.03

#### Steps for reproducing this issue:

1. Open steam
2. Click on Steam in the top left > Settings > Controller > General Controller Settings
3. Click check box for Xbox Configuration Support

**Comment by kisak-valve** [comment]
Hello @smeejo1, this sounds like #7516. Please check if you have `Use native runtime` enabled in Solus's linux-steam-integration project and disable it, then retest.

**Comment by smeejo1** [comment]
> Hello @smeejo1, this sounds like #7516. Please check if you have `Use native runtime` enabled in Solus's linux-steam-integration project and disable it, then retest.

Disabled use native runtime, restarted steam and tried in normal window and big picture mode. Controller still not detected.

**Comment by smeejo1** [comment]
> Hello @smeejo1, this sounds like #7516. Please check if you have `Use native runtime` enabled in Solus's linux-steam-integration project and disable it, then retest.

That fixed it, thanks!

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.

**Comment by smeejo1** [comment]
So apparently disabling Use native runtime makes it so the buttons on the controller are not configurable in game. For example in American Truck Simulator I have it set so I click the right joystick in and it changes the camera mode to first person. That no longer works nor do any of my other buttons. I also, despite trying for the last 3 hours, can not rebind the buttons. When I click on the game and click controller configuration I can set the button bindings in there, load other peoples configurations, or load my saved configurations but the games do not register any of the changes I make there.

It is this way for all my games currently.
