### ISSUE TITLE
Paradox launcher doesn't work with latest steam runtime

### ISSUE THREAD

**Issue by tingvarsson** [ValveSoftware/steam-for-linux#7546]
#### Your system information

* Steam client version (build number or date): Dec 11 2020
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Paradox launcher doesnt start/work. When trying to start Europa Universalis IV nothing happens.
Started to happen on a Beta update last week.
When using steam-native it still works, so suspect something with the runtime.

#### Steps for reproducing this issue:
1. Start Europa Universalis IV

**Comment by kisak-valve** [comment]
Hello @tingvarsson, this issue is already being tracked at https://github.com/ValveSoftware/steam-runtime/issues/331. Closing as a duplicate.
