### ISSUE TITLE
Unable to set game storage when installing multiple games

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#7547]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/102214996-bdee3200-3ee1-11eb-847f-92e02919f150.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video:  https://youtu.be/8Li_5Cy5UCU 
There is no option to change the install location when trying to install multiple games.
Previous instance of this bug was #6273

#### Steps for reproducing this issue:

1. Select several games
2. Right click
3. Click on install

**Comment by blastermaster77** [comment]
I tried it on manjaro and it works, are you in beta branch?

**Comment by Managor** [comment]
It says so in the description.

**Comment by TTimo** [comment]
CNR in Dec 20 Steam beta. Try fewer, different game combos, maybe there's one in the set that your client doesn't like?

**Comment by Managor** [comment]
So it seems that Half-Life 2: Lost Coast has something special in it that causes the option to not appear.
https://youtu.be/EEwvAFe_DV4

**Comment by Managor** [comment]
This has been fixed with the new install menu.
