### ISSUE TITLE
Unable to copy/paste to and from clipboard to in-game chats.

### ISSUE THREAD

**Issue by telometto** [ValveSoftware/steam-for-linux#7554]
#### Your system information

* Steam client version (build number or date): Latest
* Distribution (e.g. Ubuntu): fedora 33
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
As the title states. I am unable to copy/paste things from overlay and desktop into or from the game chat. Copying/pasting works from/to overlay and desktop.

#### Steps for reproducing this issue:

1. This doesn't seem to be a distro-specific issue, rather on all Linux platforms, so I'm guessing that most people will be able to reproduce the problem without difficulty.
2. x
3. x

**Comment by kisak-valve** [comment]
Hello @telometto, please clarify which game's in-game chat.

**Comment by telometto** [comment]
Oh, sorry. It's in CS:GO.

**Comment by kisak-valve** [comment]
Thanks, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1786. Closing as a duplicate.
