### ISSUE TITLE
Moving games/apps from one install path to another doesn't transfer full profile/game

### ISSUE THREAD

**Issue by Emanem** [ValveSoftware/steam-for-linux#7557]
#### Your system information

* Steam client version (build number or date): Dec 19 2020
* Distribution (e.g. Ubuntu): Ubuntu LTS 20.04.1
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed a new NVME and decided to transfer a bunch of games. Proton titles (such as _Dark Souls III_ or _Jedi: Fallen Order_) did not transfer the Proton profile (nor the _shadercache_ directory) hence I had to re-setup them.
Also the Proton software which requires intermediate shop fronts (such as _EA's Origin_) may have trouble when moving the installation folder, resulting in issues such as [this](https://imgur.com/a/f5OLO0y) ([details here](https://www.reddit.com/r/linux_gaming/comments/kgcli2/issue_with_ea_origin_jedi_fallen_order/)).

#### Steps for reproducing this issue:

1. Install Proton game (better _Jedi: Fallen Order_) on a given install path
2. Set it up
3. Move the install path, everything will be needed to be setup form scratch again

**Comment by kisak-valve** [comment]
Hello @Emanem, this issue is already being tracked at #5717. Since there's some additional info here, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/5717#issuecomment-748605476.

Closing as a duplicate.
