### ISSUE TITLE
steam.sh: line 759: 1967724 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

### ISSUE THREAD

**Issue by Dylstructor** [ValveSoftware/steam-for-linux#7561]
Distro: Manjaro
GPU: Nvidia Gforce 1070
CPU: Intel i7-7700k (I think?)

steam.sh: line 759: 1967724 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by Dylstructor** [comment]
also i3wm if that matters

**Comment by kisak-valve** [comment]
Hello @Dylstructor, this line doesn't help troubleshoot your issue in any way. Please run `steam` from a terminal and share the output.

**Comment by Dylstructor** [comment]
Running Steam on manjarolinux 20.2 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/dylan/.local/share/Steam/ubuntu12_32/steam
[2020-12-21 20:42:58] Startup - updater built Dec 20 2020 23:07:02
Installing breakpad exception handler for appid(steam)/version(1608507519)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  46
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-12-21 20:42:58] Loading cached metrics from disk (/home/dylan/.local/share/Steam/package/steam_client_metrics.bin)
[2020-12-21 20:42:58] Using the following download hosts for Public, Realm steamglobal
[2020-12-21 20:42:58] 1. http://media4.steampowered.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
Installing breakpad exception handler for appid(steam)/version(1608507519)
[2020-12-21 20:42:58] Checking for update on startup
[2020-12-21 20:42:58] Checking for available updates...
[2020-12-21 20:42:58] Downloading manifest: http://media4.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1608507519)
[2020-12-21 20:42:59] Download skipped: /client/steam_client_ubuntu12 version 1608507519, installed version 1608507519, downloaded version 0
[2020-12-21 20:42:59] Nothing to do
[2020-12-21 20:42:59] Verifying installation...
[2020-12-21 20:42:59] Performing checksum verification of executable files
[2020-12-21 20:42:59] Verification complete
Loaded SDL version 2.0.14-6278618
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  52
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  53
xerror_handler: X failed, continuing
assert_20201221204258_1.dmp[1969784]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201221204258_1.dmp
/home/dylan/.local/share/Steam/steam.sh: line 759: 1969738 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by kisak-valve** [comment]
Swrast is mesa's slower software renderer, and the fact that Steam is trying to use it hints that you're using the nVidia proprietary driver, but don't have 32 bit userspace support installed.

Please install the `lib32-nvidia-utils` package.

**Comment by Dylstructor** [comment]
> lib32-nvidia-utils

Ok i will try this!

**Comment by Dylstructor** [comment]
Thanks!

**Comment by Dylstructor** [comment]
Wait. Now its saying "Steam is having trouble connecting to the steam servers"

**Comment by Dylstructor** [comment]
oh nvm lol! steam is just down :P
