### ISSUE TITLE
Steam in-home streaming fails to list all games Between two steam clients

### ISSUE THREAD

**Issue by minionprocyk** [ValveSoftware/steam-for-linux#7563]
#### Your system information

* Steam client version (build number or date): Built Dec 20, 2020
* Distribution (e.g. Ubuntu): Fedora 33
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I expect steam to synchronize all available games to stream to all steam clients / steam links. What actually happened is my steam client on my laptop only sees some of the games installed on my desktop, both are running the same steam version on fedora 33. I also tried steam beta on both machines, and the same happens with one exception - If I press play on a game(that was previously greyed out on my laptop) from my steam link (connected to my desktop) then that game now appears streamable from my laptop, and becomes persistent across restarts. Switching back to steam stable build makes that game become greyed out, amongst the other seemingly random list of greyed out games.
#### Steps for reproducing this issue:

1. Install a lot of games on your host desktop
2. Sign in to steam on a different machine that does not have those games installed
3. Some games will be streamable, some will not.

I haven't noticed any pattern with the games, but for completeness some of the games that are greyed out as of today are (The Witcher Enhanced Edition, The Witcher 3, Final Fantasy VII, TemTem, Halo Master Chief Collection, Supreme Commander 2)
Funny enough... I have the witcher collection, 1 and 3 are not streamable, but 2 is. 

All of these games successfully stream to a steam link or to the steamapp on mobile, but NOT to the steam client.

**Comment by kisak-valve** [comment]
Hello @minionprocyk, this issue is already being tracked at #6635, possibly #6200. Closing as a duplicate.
