### ISSUE TITLE
Menu from System Tray Icon missing again.

### ISSUE THREAD

**Issue by gbschenkel** [ValveSoftware/steam-for-linux#7565]
#### Your system information

* Steam client version (build number or date): Dec 20 2020, at 23:07:25 (1608507519)
* Distribution: Slackware 15.0 beta
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Left or right click on Steam Tray Icon give no effect

#### Steps for reproducing this issue:

1. Open Steam
2. Right Click on Steam Icon in System Tray

This is not the first time this happen, last year it happened too.

I have run it on shell, and appears the procedure/function maybe are changed, because the menu is empty, and misspelled.

```
(steam:16968): LIBDBUSMENU-GLIB-WARNING **: 15:13:40.561: About to Show called on an item wihtout submenus.  We're ignoring it.
(steam:16968): LIBDBUSMENU-GLIB-WARNING **: 15:13:41.368: About to Show called on an item wihtout submenus.  We're ignoring it.
```

**Comment by kisak-valve** [comment]
Hello @gbschenkel, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please check the contents of `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*`, then delete the `pinned_libs*` folders so that Steam regenerates them the next time Steam is started. If there's a change in what libraries are pinned and regeneration those folders doesn't help, then please share a list of files in the `pinned_libs*` folders.

**Comment by gbschenkel** [comment]
https://gist.github.com/gbschenkel/3332d0b1403a9f6aa1ab6705ac40bc00

**Comment by TTimo** [comment]
Any difference between Steam client stable/beta? Did you update your distro / Slackware update it's dbus release recently?

**Comment by gbschenkel** [comment]
With Steam stable/beta the issue still occurs.

Yes, dbus(1.12.20) was recompiled day 07/12 and again day 25/12. Since Steam uses 32bits, I am using a multilib(has compat32 in the name) packages, they got recompiled day 13/12 and 16/12. 
I have upgraded my system 20/12 and now again. I saw that libdbusmenu-compat32-16.04.0 was upgraded day 20/12, don't know if libdbusmenu is used by steam, but since I have posted this ticket day 23/12, maybe is related.

Slackware is moving to version 15.0 (beta stage) then it's is getting a lot of up-to-date versions.

While I get a reply for you, I will try recompile libdbusmenu-compat32 to see if this can help solve this issue.

**Comment by garpu** [comment]
https://gist.github.com/garpu/c71cb4aaba91a340418618938322216e

Same, on slackware-current, and the taskbar right click menu quit working after Dec. 25. 

Rebuilding pins brings back my taskbar menu.

**Comment by gbschenkel** [comment]
> Rebuilding pins brings back my taskbar menu.
Rebuilding dbus or libdbusmenu?

**Comment by garpu** [comment]
In ~/.local/share/Steam/ubuntu12_32/steam-runtime, I deleted both of the pinned-library menus.  (Should be one for 32-bit, and one for 64-bit.)  Then I started steam, and the menu was back.  I'm having other issues with it, but I think it's due to a faulty mouse button.

**Comment by gbschenkel** [comment]
Yeah, the other time I was missing zenity to display some information when rebuilding the Pins, but this time it didn't run, I wish to know if when opening steam can we force it to rebuild all Pins instead of delete the files.

**Comment by TTimo** [comment]
Would be useful to get a before/after diff of the pinned libraries.
