### ISSUE TITLE
Steam Fails to start. Error: BadValue

### ISSUE THREAD

**Issue by Kitsune-Ultima** [ValveSoftware/steam-for-linux#7568]
* Steam client version: 1608507519
* Distribution: KDE Neon
* Distro Base: Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

attempted to start steam-latest and received this error
```
user@hostname:~$ steam
Running Steam on neon 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/kital/.local/share/Steam/ubuntu12_32/steam
[2020-12-25 13:28:59] Startup - updater built Dec 20 2020 23:07:02
Installing breakpad exception handler for appid(steam)/version(1608507519)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
user@hostname:~$
```
i have installed libnvidia-gl-455:amd64 and libnvidia-gl-455:i386 with no luck
i have rebooted after install
> ctrl+c 'd as it just hung there with no gui

**Comment by kisak-valve** [comment]
Hello @Kitsune-Ultima, does any 32 bit OpenGL application like `glxinfo` a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit build of this utility on 20.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and try using the utility without installing it to the system.

**Comment by Kitsune-Ultima** [comment]
this is the output
```
user@hostname:~$ glxinfo
name of display: :0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  99
  Current serial number in output stream:  100
user@hostname:~$ 
```

**Comment by kisak-valve** [comment]
Thanks for checking, that tells us that you do not have a working 32 bit OpenGL driver stack. nVidia's proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace have exactly the same version or bad things happen.

**Comment by Kitsune-Ultima** [comment]
using a RTX 3070 if that helps

**Comment by kisak-valve** [comment]
Maybe the output of something like `apt policy nvidia-driver-455 nvidia-dkms-455 libnvidia-gl-455 libnvidia-gl-455:i386` would give a hint?

**Comment by Kitsune-Ultima** [comment]
```
nvidia-driver-455:
  Installed: (none)
  Candidate: 455.38-0ubuntu0.20.04.1
  Version table:
     455.38-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages
nvidia-dkms-455:
  Installed: (none)
  Candidate: 455.38-0ubuntu0.20.04.1
  Version table:
     455.38-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages
libnvidia-gl-455:
  Installed: 455.38-0ubuntu0.20.04.1
  Candidate: 455.38-0ubuntu0.20.04.1
  Version table:
 *** 455.38-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages
        100 /var/lib/dpkg/status
libnvidia-gl-455:i386:
  Installed: 455.38-0ubuntu0.20.04.1
  Candidate: 455.38-0ubuntu0.20.04.1
  Version table:
 *** 455.38-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/multiverse i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by kisak-valve** [comment]
That's easy enough to understand, the nVidia kernel module you're using doesn't match the rest of the driver. Please run `sudo apt install nvidia-driver-455`, which should pull in nvidia-dkms-455 as a package dependency.

**Comment by Kitsune-Ultima** [comment]
Seems to have fixed it yay
