### ISSUE TITLE
PS5 Controller detected but not working in game

### ISSUE THREAD

**Issue by nmousouros** [ValveSoftware/steam-for-linux#7573]
#### Your system information

* Steam client version (build number or date): DEC 24 2020 
* Distribution (e.g. Ubuntu): Fedora 33
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The PS5 Controller worked perfectly until the latest update. I could only test it with NBA 2k21 but it used to get detected and work, now it gets detected, I can use it on steam picture mode and start a game with my controller, the game detects that a controller is connected but the buttons does nothing, even if I go in game settings and try to map them is like pressing nothing. I think something regressed after the latest updates for the PS5 controllers

**Comment by nmousouros** [comment]
Enabling steam overlay fixed the issue, I am not sure if this is the intended behaviour ( some games don't work with it enabled as far as I know)

**Comment by kisak-valve** [comment]
Hello @nmousouros, as far as I know, this is the expected behavior. Steam Input uses the Steam overlay to get a virtual controller into the game.
