### ISSUE TITLE
Freedesktop network manager can crash the client (games freeze immidietly)

### ISSUE THREAD

**Issue by Frontrider** [ValveSoftware/steam-for-linux#7574]
#### Your system information

* Steam client version (build number or date): 1608507519
* Distribution (e.g. Ubuntu): manjaro
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
At first steam was crashing every 5-10 minutes with no error logs, (there was an empty .crash.txt in the steam folder), so I ran steam from terminal. there I got a log which contained this as the last line:
`async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/602: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/Devices/602
`
I am indeed experiencing some networking issues, but I don't think that should crash steam.
It pinted me at this thread that looks useful to me.
https://stackoverflow.com/questions/49570593/no-such-interface-org-freedesktop-dbus-properties-on-object-at-path-org-freed#49571009

Then I stopped my downloads and then got this:
`assert_20201228210921_1.dmp[125208]: Uploading dump (out-of-process)
/tmp/dumps/assert_20201228210921_1.dmp
assert_20201228210921_1.dmp[125208]: Finished uploading minidump (out-of-process): success = yes
assert_20201228210921_1.dmp[125208]: response: CrashID=bp-3f98fb53-b648-4d39-953d-5a3602201228
assert_20201228210921_1.dmp[125208]: file ''/tmp/dumps/assert_20201228210921_1.dmp'', upload yes: ''CrashID=bp-3f98fb53-b648-4d39-953d-5a3602201228''
/home/frontrider/.local/share/Steam/steam.sh: line 759: 111450 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
[frontrider@frontrider-laptop Steam]$ src/common/html/chrome_ipc_client.cpp (927) : Assertion Failed: Failed to connect to master html process, created shared memory (spawn time 131.89)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0`

the relevant dumps are in this zip:
[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/5748671/dumps.zip)

Setting the client to offline mode fixes the crash, so it's definietly networking related.

#### Steps for reproducing this issue:

I changed nothing in my setup, and I'm only running apps from steam.

**Comment by kisak-valve** [comment]
Hello @Frontrider, this issue is already being tracked at #6318 / #6751. Closing in favor of the older issue reports.
