### ISSUE TITLE
No build id in game settings

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#7575]
#### Your system information

* Steam client version (build number or date): Dec 24 at 23:51:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Game settings does not have game build id

#### Steps for reproducing this issue:

1. Go game settings
2. Can't find build id

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue is already being tracked at #7555. Closing as a duplicate.
