### ISSUE TITLE
You are missing the following 32-bit libraries, and Steam may not run: libc.so.6

### ISSUE THREAD

**Issue by ANoobyPlayer** [ValveSoftware/steam-for-linux#7579]
#### Your system information

* Steam client version (build number or date): 31/12/2020
* Distribution: Raspberry pi OS
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
When I execute it says that steam needs to install these aditional packages.Then all goes well until it reach to libgl1-mesa-dri-i386,libgl1-i386 and libc6-i386

#### Steps for reproducing this issue:

1. Install steam from the website
2. Execute the app

**Comment by kisak-valve** [comment]
Hello @ANoobyPlayer, the Raspberry Pi has an ARM-based CPU and Steam is not available for ARM-based systems. Closing in favor of #4061.

**Comment by Newbytee** [comment]
Not really a solution to this issue but you can check out Box86 if you want to run Steam on your Raspberry Pi: https://github.com/ptitSeb/box86. 100% unsupported by Valve but it works.

**Comment by ANoobyPlayer** [comment]
@kisak-valve  @Newbytee  Thanks for the help!
