### ISSUE TITLE
Adding non-steam game does not handle whitespace correctly

### ISSUE THREAD

**Issue by Wandang** [ValveSoftware/steam-for-linux#7580]
#### Your system information

* Steam client version (build number or date): steam-manjaro: 1.0.0.68-1
* Distribution (e.g. Ubuntu): Manjaro 20.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Adding a non-steam game to the library resulted in a malformed entry. The path to the binary had a whitespace inside which was parsed as several entities(target property and launch options) instead of one folder path.

For example: ```/home/username/Games/SuperGame 2/binary.exe```
Should result in an entry with
Target property: "/home/username/Games/SuperGame 2/binary.exe"
Launch options: ``` ```

What happens instead:
Target property: "/home/username/Games/SuperGame"
Launch options: 2/binary.exe

#### Steps for reproducing this issue:

1. Create a folder with whitespace and move a binary inside
2. Add this binary via steam non-steam addition
3. Right click properties of link entity

**Comment by kisak-valve** [comment]
Hello @Wandang, this issue is already being tracked at #5220. Closing as a duplicate.
