### ISSUE TITLE
Game shows as running after exiting if a program is set to start in launch options after game exits

### ISSUE THREAD

**Issue by aliveinadream** [ValveSoftware/steam-for-linux#7597]
#### Your system information

* Steam client version (build number or date):
   Dec 20, 2020, 23:07:25
* Distribution (e.g. Ubuntu):
   Arch Linux 
* Opted into Steam client beta?: [Yes/No]
   No
* Have you checked for system updates?: [Yes/No]
   Yes

#### Please describe your issue in as much detail as possible:
When setting a program to start after a game exits in launch options, such as `killall someprogram && %command% ; someprogram &` , the game shows as still running in Library. I tried this with multiple games and it's the same with all of them.

Expected result: 
Game is shut down properly,
Game isn't shown as running in Library
Program that is supposed to start after game exits is run

Observed result:
Game shuts down properly (not seen in processes
Game is shown as running in Library
Program that is supposed to start after game exits runs, but is closed when pressing STOP in Library view of the game shown as still running.

#### Steps for reproducing this issue:

1. Open launch options for a game
2. Add a program to start after game exits, ex. "killall clight && %command%; clight &"
3. Launch game
4. Close game

**Comment by kisak-valve** [comment]
Hello @aliveinadream, please see the discussion on #6306.
