### ISSUE TITLE
Logitech F710 gamepad periodically disconnects after the latest client updates

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/steam-for-linux#7600]
#### Your system information

* Steam client version: 1610075445
* SteamOS version: 2.0: 1:2.195
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Logitech F710 gamepad periodically turns off after the latest client updates. The problem occurs during system startup or after an idle time. The gamepad is identified as XBOX 360.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Possible duplicate of #7366.

**Comment by CygnusTerminal** [comment]
Can confirm, the problem also happens on pure Arch, with my DS4. It does not happen on other clients/emulators

**Comment by Vladislavuz** [comment]
For me, the problem has been solved. The controller is no longer disabled.

**Comment by kisak-valve** [comment]
Closing per the last comment.
