### ISSUE TITLE
Not obvious which Steam Play compatibility tool is selected in Properties

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-for-linux#7606]
#### Your system information

* Steam client version (build number or date): Stable 1608507519 (Dec 20 2020, 23:07:25), beta 1610592097 (Jan 14 2021, 00:10:17)
* Distribution (e.g. Ubuntu): Debian bullseye (Debian 11 prerelease)
* Opted into Steam client beta?: [Yes/No] Tried both
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Whenever I open the Compatibility tab of a game's properties, "Force the use of a specific Steam Play compatibility tool" shows with a faint check mark (perhaps an indeterminate state?) instead of reflecting the real configuration for this game.

I expected to see one of these:

![full-check](https://user-images.githubusercontent.com/1561141/104733572-ccc14200-5736-11eb-82cf-9f91efa03709.png)

or

![unchecked](https://user-images.githubusercontent.com/1561141/104733591-d34fb980-5736-11eb-82e6-3d21bbfcc370.png)

but instead I see this:

![faint-check](https://user-images.githubusercontent.com/1561141/104733600-d6e34080-5736-11eb-8bd0-5ec4373c5916.png)

This is a new thing since the appearance of the Properties window changed from Steam's traditional UI toolkit (still used for the "Move install folder" and "Verify integrity of game files" popups) to a newer appearance.

This seems to be a visual bug only: if I ignore what is displayed, the game correctly runs with or without the compat tool, according to what I selected most recently. However, it's confusing.

#### Steps for reproducing this issue:

1. Have the Steam Linux Runtime compat tool and at least one Proton version installed
2. Have a small game that will be quick to reinstall (I used Floating Point, 302380)
3. Right click on a game in the Library sidebar, choose Properties
4. Go to the Compatibility tab
5. Check and uncheck "Force the use of..." (repeatedly, if necessary) so that it shows unchecked
6. Close Properties
7. Reopen Properties
    * Expected result: "Force the use of..." is unchecked. The list of compatibility tools is not shown.
    * Actual result: "Force the use of..." has a faint check mark. Steam Linux Runtime is shown selected in the drop-down list.
8. Close Properties
9. Run the game
    * It correctly runs in the traditional `LD_LIBRARY_PATH` runtime (no compat tool) as I requested
10. Reopen Properties
11. Either uncheck and check "Force the use of..." (repeatedly, if necessary) so that it shows checked, or select Steam Linux Runtime from the drop-down list
12. Close Properties
13. Reopen Properties
    * Expected result: "Force the use of..." is checked. The list of compatibility tools shows Steam Linux Runtime selected.
    * Actual result: "Force the use of..." has a faint check mark. Steam Linux Runtime is shown selected in the drop-down list. This looks the same as what I saw in step 7, even though the configuration is now different.
14. Close Properties
15. Run the game
    * It correctly runs in the Steam Linux Runtime environment as I requested
16. Reopen Properties
17. Select a version of Proton from the drop-down list (I used 5.13-5)
18. Close Properties
19. Let the game update (the native Linux version is removed and the Windows version is installed)
20. Reopen Properties
    * Expected result: "Force the use of..." is checked. The list of compatibility tools shows the requested Proton version selected.
    * Actual result: "Force the use of..." has a faint check mark. The list of compatibility tools shows the requested Proton version selected.
21. Run the game
    * It correctly runs using Proton as I requested

**Comment by TTimo** [comment]
thanks - should be addressed in a future update

**Comment by RyuzakiKK** [comment]
I'm experiencing a similar issue with the latest Steam beta client, but the difference is that I see the "normal" tick instead of the fainted one.

Steps to reproduce:
- Right click on a game->Property->Select the "Force Steam Play" and choose Proton 6.3
- Close the property menu
- Reopen property and deselect "Force Steam Play"
- Close the property menu
- Reopen property and the "Force Steam Play" is unexpectedly checked (normal tick, not the fainted tick) with Proton 6.3 in the dropdown, even if in reality the compatibility layer is not enabled.

**Comment by kisak-valve** [comment]
Hello @RyuzakiKK, you've described the issue being tracked at #7671 instead of this issue report.

**Comment by TTimo** [comment]
#7671 is a new issue (which I can reproduce) - this #7606 "indeterminate state" looks fixed though. closing.
