### ISSUE TITLE
Remote play - shaders make it impossible to use with Proton

### ISSUE THREAD

**Issue by tuxrinku** [ValveSoftware/steam-for-linux#7607]
#### Your system information

* Steam client version (build number or date): Jan 14 2021
* Distribution (e.g. Ubuntu): Ubuntu 20.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When streaming games launched through proton, the framerate drops drastically everytime an effect shows up. It's probably related to vulkan somehow. Tested with the steam link app on raspberry pi 4 and android phone.

#### Steps for reproducing this issue:

1. Stream a proton game (tested with Rocket League and Tekken 7)
2. Use boost in Rocket League or any hit in Tekken 7
3. The framerate on both host and client drops to like 10 fps from 60

**Comment by kisak-valve** [comment]
Hello @tuxrinku, this issue is already being tracked at #5591. Closing as a duplicate.
