### ISSUE TITLE
Steam client taking possibly over a gig of ram while idle

### ISSUE THREAD

**Issue by SirBubbles** [ValveSoftware/steam-for-linux#7611]
#### system information
I have the latest stable steam client (on the non-beta branch)
Using Manjaro (Nibia 20.2.1) on the stable branch. Also using the Gnome desktop and an nvidia 2060 super video card, with the nvidia-latest-dkms package, at version 460.32.03. Also using a Ryzen 3600 at stock clocks and 32 gigs of ram. Fully up to date with regards to software.

#### issue description
When running the steam client (steam_runtime, as opposed to steam_native) I will find that more often than not, the main steam process takes at least several hundred megs of ram, sometimes as high as 1.4 gigs. The expected outcome is anywhere between 120 megs to somewhere around 300-400 megs.

All I need to do is fire up steam after a fresh boot or login to X to trigger this. I have tried to export STEAM_RUNTIME=1 to make it use the steam runtime libs that steam comes with, but that usually has no effect. I keep killing and restarting steam to get bearable ram usage out of it.
This has been ongoing for several months now, best I can tell. I'm unsure if it has sometime to do with Manjaro, X, nvidia, or the gnome desktop, but SOMETHING must be causing this.

**Comment by kisak-valve** [comment]
Hello @SirBubbles, this issue is already being tracked at #6802. Closing as a duplicate.

**Comment by SirBubbles** [comment]
As long as something is done about it, the last post on that other issue is mid last year.
