### ISSUE TITLE
Rust Server Crash after 16h online : Warning: failed to init SDL thread priority manager: SDL not found

### ISSUE THREAD

**Issue by zardozlogin** [ValveSoftware/steam-for-linux#7616]
#### Your system information

* Steam client version (build number or date): 20/12/2020
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* 
RUST Server infos:
Protocol: 2275.202.1
Build Date: 01/18/2021 20:48:10
Unity Version: 2019.4.7f1
Changeset: 57728
Branch: release

#### Please describe your issue in as much detail as possible:

I am owner of a RUST server. it's created with WISP (based on pterodactyl) and hosted on a hetzner dedicated server.
The last 2 weeks, my rust server CRASH after 16-18h online.
i tried to reinstall the server totally, to rebuild container, but still same issue.

here is the logs:
 
`eac_server.so [x64] :: OnLoad()
Warning: failed to init SDL thread priority manager: SDL not found
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal Assertion Failed: Symbol table grew beyond unsigned short.  Time to upgrade UtlSymId_t for the symbol type or look for unnecessary spam in the tables.
/data/src/public/tier1/utlsymbol.h (453) : Fatal assert failed: /data/src/public/tier1/utlsymbol.h, line 453.  Application exiting.`

#### Steps for reproducing this issue:

1.  start my rust server at midnight
2.  my rust server crash at around 4PM

**Comment by kisak-valve** [comment]
Hello @zardozlogin, this issue should be reported to the game's devs directly. This issue tracker is for the Steam for Linux client. Closing as out-of-scope.
