### ISSUE TITLE
CS:GO on single large display isn't playable

### ISSUE THREAD

**Issue by russell** [ValveSoftware/steam-for-linux#7623]
#### Your system information

* Steam client version (build number or date): Dec 20 2020, at 23:07:25 1608507519
* Distribution Debian GNU/Linux bullseye/sid
* Opted into Steam client beta?: No
* Have you checked for system updates?: Daily

#### Please describe your issue in as much detail as possible:

CS:GO is great! But I am having trouble finding working settings for my PC, I have a 32:9 ratio monitor 5120x1440 in Linux, and i can't use any fullscreen mode. There are bugs in game that make it totally unplayable. I have tried both triple screen mode and single screen mode, the both suffer from the same artifacting in-game.

I can get a working game IF i run in windowed mode at 1920x1080, but there are quite limited screen resolution choices, and there is no black bars option to just use the center portion of the screen. :(

When playing fullscreen i see visual artifacts, that leave a lasting visual imprint on the view, it's a bit like old CRT monitors that had a ghost image on them. For example the artifacting that is visible in the scope screenshot i have, remains present after leaving the scope (burn in screenshots), so if you use a scope the rest of the game is ruined with visual elements that remain ghosted into the view.

```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7058 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 2080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.32.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 460.32.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.32.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### menus broken in 32:9 mode

![single monitor - menu](https://user-images.githubusercontent.com/2660/105867700-ab453d80-5ff5-11eb-86db-77f34b12c823.png)
![single monitor - menu 1](https://user-images.githubusercontent.com/2660/105867712-ad0f0100-5ff5-11eb-809b-0e5378bcf74d.png)

### menus working in triple screen mode

This actually works pretty decent, you have to modify the launcher args to get to a point where you can have a working menu though.

![triple monitor - menu](https://user-images.githubusercontent.com/2660/105867737-b4cea580-5ff5-11eb-8316-21cd9d4b11bb.png)

### buy menu ugly but functioning

![triple monitor - buy screen](https://user-images.githubusercontent.com/2660/105867794-c4e68500-5ff5-11eb-89d1-94c1ab9e8561.png)

### scopes so distracting they are nigh impossible to use

This screenshot is from triple monitor mode, but it's the same experience in single monitor mode

![triple monitor - scope](https://user-images.githubusercontent.com/2660/105867817-cadc6600-5ff5-11eb-8e9e-ea956c3f8761.png)

# ghosting after using a scope remains, crt style burn in

![single monitor - burn in](https://user-images.githubusercontent.com/2660/105868159-2870b280-5ff6-11eb-80f2-aed1cd7f28ca.jpg)
![single monitor - burn in 1](https://user-images.githubusercontent.com/2660/105868211-3a525580-5ff6-11eb-9556-cfd14a343b2e.jpg)

There are more issues than this, when your are in the 3rd person view after dying in a match, there is heaps of visual artifacts 1/4 of the screen flashes bright yellow.

#### Steps for reproducing this issue:

1. Set your resolution to 5120x1440 and your aspect ratio to 16:9
2. Play game

**Comment by kisak-valve** [comment]
Hello @russell, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2429. Closing as a duplicate.
