### ISSUE TITLE
Steam doesn't detect my manual proxy

### ISSUE THREAD

**Issue by NikoBellicRU** [ValveSoftware/steam-for-linux#7624]
#### Your system information

* Steam client version (build number or date): Steam Client Beta Update - January 21st
* Distribution: Manjaro
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

So i changed to a manual proxy but either in the game or the browser in overlay shows my actual location and not the proxy's/  vpn, if i open firefox or chromium i can see that my location has changed to the one that i choosed to so it seems the problem it's on steam.

https://gist.github.com/NikoBellicRU/f815d55c08273d64b8da0df73c48c2eb

**Comment by kisak-valve** [comment]
Hello @NikoBellicRU, this issue is already being tracked at #1943. Closing as a duplicate.
