### ISSUE TITLE
High CPU usage with no game running.

### ISSUE THREAD

**Issue by wildcard-f8** [ValveSoftware/steam-for-linux#7625]
#### Your system information

* Steam client version (build number or date): Jan 22 2021
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
After a few hours of having the client running, whether I'm playing or not, top shows that Steam is consuming 100%+ of CPU.

#### Steps for reproducing this issue:

1. Run Steam
2. Leave it running for X amount of time.
3. ?

**Comment by kisak-valve** [comment]
Hello @wildcard-f8, can you share the information requested in https://github.com/ValveSoftware/steam-for-linux/issues/7372#issuecomment-696193644? In particular, I'm curious what the name of thread(s) involved.

**Comment by kisak-valve** [comment]
Closing pending feedback. Possibly fixed in the current Steam client beta along with #7372.

**Comment by wildcard-f8** [comment]
Sorry for the very late reply. Yes, I think a previous update fixed it.
