### ISSUE TITLE
Steam forces focus on new chat messages even when notifications are turned off.

### ISSUE THREAD

**Issue by wildcard-f8** [ValveSoftware/steam-for-linux#7626]
#### Your system information

* Steam client version (build number or date): Jan 22 2021
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
While I'm playing a game on full screen mode, whenever a friend messages me, Steam focuses on the chat window causing me to lose control of my game. I have turned off notifications, the flash windows is set to never and everything regarding the chat. Basicall the notification settings don't work even if you turn everything off. New chat windows always pops up and interrupts the game. Annoying when I play driving games, it always causes me to crash. In the middle of games with combat, it causes me to die.

The only solutions I have come up with is to turn off chat (but sometimes I need it) or open a chat window before playing a game. For some reason if a chat window is already open, it doesn't change focus to the chat window. I've also tried playing with window and border-less window, same thing.

#### Steps for reproducing this issue:

1. Play game.
2. Receive chat message.
3. ?

**Comment by kisak-valve** [comment]
Hello @wildcard-f8, this issue is already being tracked at #5286. Closing as a duplicate.
