### ISSUE TITLE
Final Fantasy XV/Final Fantasy 15 will not boot due to linking 32bit libs

### ISSUE THREAD

**Issue by awsdert** [ValveSoftware/steam-for-linux#7634]
#### Your system information

* Steam client version (build number or date): Jan 30 2021 at 01:03:12
* Package version: 1611978348
* Distribution (e.g. Ubuntu): Manjaro x64 Cinnamon
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Expected to see the main menu, didn't even see the intro banner stuff

#### Steps for reproducing this issue:

1. Just launch the game

#### Terminal output
[steam_FFXV.txt](https://github.com/ValveSoftware/steam-for-linux/files/5900508/steam_FFXV.txt)

**Comment by kisak-valve** [comment]
Hello @awsdert, we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues/). Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/74#issuecomment-770439502.

**Comment by awsdert** [comment]
ty, had trouble finding it, suppose I just looked in the wronf repository
