### ISSUE TITLE
Skatebird demo won't run

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#7637]
#### Your system information

* Steam client version (build number or date): Feb 2, 2021 - package 16123222211
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The newest SkateBIRD demo does not launch from Steam, but works fine outside of Steam.

When run with the Steam Beta (tested with stable client too, same issue):

> Starting app 1209690
> >>> Adding process 26288 for game ID 1209690
> GameAction [AppID 1209690, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
> /bin/sh: line 1: stl: command not found
> GameAction [AppID 1209690, ActionID 3] : LaunchApp changed task to Completed with ""
> >>> Adding process 26289 for game ID 1209690
> Game removed: AppID 1209690 "", ProcID 26288 
> Uploaded AppInterfaceStats to Steam
> Exiting app 1209690
> No cached sticky mapping in ActivateActionSet.[0203/211533.877330:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.

Full system info (after trying in normal stable client with same issue): https://gist.github.com/LiamDawe/dd92733586c996755e62f269956f5b2c

#### Steps for reproducing this issue:

1. Try to launch the skatebird demo
2. fail
3. cry
4. Play it directly outside of Steam from the installed folder

**Comment by kisak-valve** [comment]
Hello @LiamDawe, `/bin/sh: line 1: stl: command not found` looks abnormal. Can you verify there isn't something odd in the game's launch options?

**Comment by LiamDawe** [comment]
Ah, hilarious, must have been left over from the last demo. Problem was between the keyboard and the chair....me.
