### ISSUE TITLE
please provide a 64 bit steam client for ubuntu

### ISSUE THREAD

**Issue by jamiew0w** [ValveSoftware/steam-for-linux#7638]
#### Your system information

* Steam client version (build number or date): Can't tell because it won't start :)
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] 
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I'm unable to use steam as it's forcing me to install a 32bit arch on my 64bit system. 

#### Steps for reproducing this issue:

1. Install Ubuntu 20.04
2. Install steam
3. Try run steam

### Additional:

I'm also running into the same issues when using steamcmd.
// Didn't steam claim to move to 64bit like 2-3 years ago? Is this a ubuntu issue?

**Comment by kisak-valve** [comment]
Hello @jamiew0w, this issue is already being tracked at #3518. Closing as a duplicate.
