### ISSUE TITLE
Steam is unable to recover Steam Controller configs for DX11 Proton games after the controller disconnects

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#7654]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/107808057-b3c9a200-6d71-11eb-938a-0c215804642c.png)
* Distribution: Arch Linux, Plasma
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/9cbPYVZpa_w
Steam seems to be unable to recover Steam Controller configs for DX11 games after the controller disconnects. This in not limited to just the in-game configs, but also chord. I have tested several games and the pattern seems to hold only for only DX11 games. This bug has been reproducible on Proton Experimental, 5.13-5 and 4.11-13. This bug is reproducible by disconnecting the dongle or just by simply holding down the home button

Tested games
DX11: Hitman 2, Wreckfest, Cuphead, Crash Bandicoot, ABZU
DX9: Mirror's Edge

As an added bonus: Sometimes, about ½ of the time, steam crashes when exiting the game. I have only tested if exiting the game naturally through in-game menus in Hitman 2 does this and I do not know if Alt+F4 has the ability to reproduce this crash
Second added bonus: Sometimes the game freezes when the controller disconnects or reconnects. I have not paid attention which one causes it.

#### Steps for reproducing this issue:

1. Start a DX11 Proton game
2. Disconnect the controller by holding the home button
3. Reconnect the controller

### Results
The game will no longer receive input from the controller and none of the chorded bindings work either. Sometimes the game itself will freeze completely and ofter Steam will crash when exiting the game naturally.

**Comment by Managor** [comment]
@kisak-valve This can be closed as I am no longer able to reproduce this bug.

**Comment by kisak-valve** [comment]
Friendly reminder that you can close your own issue reports at your own discretion.
