### ISSUE TITLE
Some Steam games do not work on linux mint 20.1

### ISSUE THREAD

**Issue by ioannis120** [ValveSoftware/steam-for-linux#7657]
#### Your system information

* Steam client version feb2021 steam api v020 package 1612763122
* linux mint 20.1
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* I tried to launch supreme ultimate and it does not start
* System:
  Kernel: 5.4.0-65-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
  base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop Mobo: ASRock model: FM2A88M Extreme4+ R2.0 serial: <filter> 
  UEFI [Legacy]: American Megatrends v: P1.80 date: 01/11/2016 
Memory:
  RAM: total: 13.61 GiB used: 2.14 GiB (15.7%) 
  RAM Report: 
  permissions: Unable to run dmidecode. Root privileges required. 
CPU:
  Topology: Quad Core model: AMD A10-7860K Radeon R7 12 Compute Cores 4C+8G 
  bits: 64 type: MCP arch: Steamroller rev: 1 L2 cache: 2048 KiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 28749 
  Speed: 2271 MHz min/max: 1400/3600 MHz Core speeds (MHz): 1: 1970 2: 1926 
  3: 2492 4: 2493 
Graphics:
  Device-1: AMD Kaveri [Radeon R7 Graphics] vendor: ASRock driver: radeon 
  v: kernel bus ID: 00:01.0 
  Display: x11 server: X.Org 1.20.9 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: AMD KAVERI (DRM 2.50.0 5.4.0-65-generic LLVM 11.0.1) 
  v: 4.5 Mesa 21.1.0-devel (git-8481a34 2021-02-13 focal-oibaf-ppa) 
  direct render: Yes 
Audio:
  Device-1: AMD Kaveri HDMI/DP Audio vendor: ASRock driver: snd_hda_intel 
  v: kernel bus ID: 00:01.1 
  Device-2: AMD FCH Azalia vendor: ASRock driver: snd_hda_intel v: kernel 
  bus ID: 00:14.2 
  Device-3: JMTek LLC. USB PnP Audio Device type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 6-1:2 
  Sound Server: ALSA v: k5.4.0-65-generic 
Network:
  Device-1: Qualcomm Atheros AR9227 Wireless Network Adapter driver: ath9k 
  v: kernel port: f100 bus ID: 01:05.0 
  IF: wlp1s5 state: up mac: <filter> 
  Device-2: Qualcomm Atheros QCA8171 Gigabit Ethernet vendor: ASRock 
  driver: alx v: kernel port: e000 bus ID: 03:00.0 
  IF: enp3s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 931.51 GiB used: 23.45 GiB (2.5%) 
  ID-1: /dev/sda vendor: Toshiba model: DT01ACA100 size: 931.51 GiB 
Partition:
  ID-1: / size: 914.46 GiB used: 23.45 GiB (2.6%) fs: ext4 dev: /dev/dm-0 
  ID-2: swap-1 size: 976.0 MiB used: 2.0 MiB (0.2%) fs: swap dev: /dev/dm-1 
Sensors:
  System Temperatures: cpu: 12.1 C mobo: N/A gpu: radeon temp: 10 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 236 Uptime: 6h 59m Init: systemd runlevel: 5 Compilers: 
  gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38

**Comment by kisak-valve** [comment]
Hello @ioannis120, sorry, but this feedback isn't coherent. The nearest game match I can find for "I tried to launch supreme ultimate and it does not start" is Supreme Ruler Ultimate, which does not have a native Linux release.

Please be aware that if your issue is with a game run with Proton, then you can give feedback on the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues), and we're using one issue report per unofficially supported game title. Feel free to open a new compatibility report if someone hasn't already made one for the game you're testing.

Closing because this isn't an issue with the Steam client.
