### ISSUE TITLE
i can not install a game on steam

### ISSUE THREAD

**Issue by ioannis120** [ValveSoftware/steam-for-linux#7660]
#### Your system information

* Steam client version (build number or date): feb 12 2021
* Distribution (e.g. Ubuntu): linux mint 20.1
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible
I tried to install a game and it did not download but it shows me that is downloaded and the files in the directory are missing

#### Steps for reproducing this issue:

1. hit instal
2. it shows me the preparation for download
3. then it does not download it only shows me that is downloaded

**Comment by kisak-valve** [comment]
Hello @ioannis120, please clarify which game you had this issue with.

**Comment by ioannis120** [comment]
with superpower2 steam edition, and supreme ruller ultimate, it only shows me a javascript, right now i download steam all over again and i see what happens.

**Comment by ioannis120** [comment]
nothing the same What should i do?

**Comment by ioannis120** [comment]
it just does not download

**Comment by ioannis120** [comment]
I found the solution, i just needed to get it on experimental proton.
