### ISSUE TITLE
Steam Link audio starts detoriating after 1-4h of gameplay

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#7661]
#### Your system information

* Steam client version:
![image](https://user-images.githubusercontent.com/42655600/108104711-4e88f000-7094-11eb-80c0-386d2db32b92.png) 
* Distribution: Arch Linux, KDE Plasma
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/X8no2ZT1Yoo
When playing through the Steam Link for extended periods of time, the audio starts to slowly deteriorate to static. As shown in the demonstrative video, the audio quality stays normal on the host PC. I have tested this with Pulseaudio and Pipewire and it is reproducible on both. 

#### Steps for reproducing this issue:

1. Play a game for extended periods of time (Resource intensive games like Hitman seem to cause it quicker. Don't quote me on that)

### Results 
The audio slowly detoriates to static. First there appears small cracking sounds in the audio but eventually it'll turn to something you can't listen.

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #6749. Closing as a duplicate.
