### ISSUE TITLE
CSGO Freezes then closes during the card selection on retakes

### ISSUE THREAD

**Issue by plakkiesza** [ValveSoftware/steam-for-linux#7677]
#### Your system information

* Steam client version (build number or date): 12 feb 2021
* Distribution (e.g. Ubuntu): Linux Mint 19.3 Tricia (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, I can upgrade to 20.04 not too keen at the moment to do so.
* Video Card:  NVIDIA Corporation GeForce GTX 1660 Ti 
#### Please describe your issue in as much detail as possible:

My games freezes then closes when I try retakes. This happens when the game starts displaying the card selection. so some parts of the card selection is visible.
Whenever I try check the game files it says there is one corrupt file and it will download and correct.

#### Steps for reproducing this issue:

1. Start retakes
2. wait for card selection screen
3. see attachments
![Screenshot_2021-02-25_19-33-38](https://user-images.githubusercontent.com/20207687/109261065-ebbbf500-7807-11eb-9b76-57541471c1bb.jpg)
![Screenshot_2021-02-24_22-48-13](https://user-images.githubusercontent.com/20207687/109261069-ed85b880-7807-11eb-9895-8d2f7798bb9c.png)

 for what it looks like when it freezes

**Comment by kisak-valve** [comment]
Hello @plakkiesza, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2568. Closing as a duplicate.

**Comment by plakkiesza** [comment]
Thanks for showing that thread. I did search before posting and did not find it.
