### ISSUE TITLE
Issue not running after install

### ISSUE THREAD

**Issue by mk2rs2008** [ValveSoftware/steam-for-linux#7682]
#### Your system information

* Steam client version (not sure): 
* Distribution (Gentoo): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Not sure as this the issue is after install saying (Error: Steam needs to be online to update.         Please confirm your network connection and try again.) Ofc im connect to a network lol. any ideas would be good i have reinstalled about 3 tims gentoo and steam im using a custom kernel as im running this on a ps4 it wont let me use layman either.

Log

ps4@ps4linux ~ $ steam
/home/ps4/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
/home/ps4/.local/share/Steam/steam.sh: line 106: VERSION_ID: unbound variable
Running Steam on gentoo  64-bit
STEAM_RUNTIME is enabled by the user
Pins up-to-date!
/home/ps4/.local/share/Steam/steam.sh: line 828: /home/ps4/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
[2021-02-28 00:05:41] Startup - updater built Oct 24 2018 20:08:45
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
Installing breakpad exception handler for appid(steam)/version(1.0)
[2021-02-28 00:05:41] Verifying installation...
[2021-02-28 00:05:41] Unable to read and verify install manifest /home/ps4/.local/share/Steam/package/steam_client_ubuntu12.installed
[2021-02-28 00:05:41] Verification complete
[2021-02-28 00:05:41] Downloading Update...
[2021-02-28 00:05:41] Checking for available update...
[2021-02-28 00:05:41] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 14]

../tier1/KeyValues.cpp (2943) : Assertion Failed: Error while parsing text KeyValues for resource manifest
../tier1/KeyValues.cpp (2943) : Assertion Failed: Error while parsing text KeyValues for resource manifest
Installing breakpad exception handler for appid(steam)/version(1.0)
crash_20210228000542_7.dmp[35737]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210228000542_7.dmp
[2021-02-28 00:05:42] failed to load manifest from buffer.
[2021-02-28 00:05:42] Failed to load manifest
[2021-02-28 00:05:42] Error: Download failed: http error 200
[2021-02-28 00:05:42] Error: Steam needs to be online to update.         Please confirm your network connection and try again.
crash_20210228000542_7.dmp[35737]: Finished uploading minidump (out-of-process): success = yes
crash_20210228000542_7.dmp[35737]: response: CrashID=bp-833fc10a-223a-4340-ae79-612c82210227
crash_20210228000542_7.dmp[35737]: file ''/tmp/dumps/crash_20210228000542_7.dmp'', upload yes: ''CrashID=bp-833fc10a-223a-4340-ae79-612c82210227''

**Comment by kisak-valve** [comment]
Hello @mk2rs2008, this issue is already being tracked at #7667. Closing as a duplicate.
