### ISSUE TITLE
Text size in Steam-Client is too small

### ISSUE THREAD

**Issue by sjuk** [ValveSoftware/steam-for-linux#7689]
#### Your system information

* Steam client version (build number or date): Feb 12 2021 at 23:22:26
* Distribution (e.g. Ubuntu): Ubuntu 20.04.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expected to get a good readable text size in Steam-Client.
Instead I get a too small text size in Steam-Client.

I already tried to turn off user interface option "Scale text and icons to match monitor settings". But on or off does not make any difference.

And there is no workaround like zooming in/out I know of.

Please see attached screenshots to get an impression about how small the text size is.
![Bildschirmfoto von 2021-02-24 18-27-37](https://user-images.githubusercontent.com/5033784/109549819-c3195100-7ace-11eb-9fa9-007f1c453e80.png)
![Bildschirmfoto von 2021-02-25 17-55-18](https://user-images.githubusercontent.com/5033784/109549837-c8769b80-7ace-11eb-9099-1770dd67a530.png)

#### Steps for reproducing this issue:

1. Start Steam-Client

**Comment by kisak-valve** [comment]
Hello @sjuk, this issue is already being tracked in various issue reports like #5460, #6007, #6410, and #6572. Closing in favor of the older issue reports.

**Comment by sjuk** [comment]
Hello **@kisak-valve**, the other reports are quite old. And I'm suffering from that issue for years. Don't get me wrong.
I'm very thankful to steam supporting Linux that much. But I have to ask.

- Is there any chance to get progress in that issue.
- Do you need more information?
- Is there anything else you need from the Linux community to fix the issue?
