### ISSUE TITLE
Steam Link on NVIDIA Shield TV - Lego The Lord of the Rings - stutter when destroying things

### ISSUE THREAD

**Issue by mss555** [ValveSoftware/steam-for-linux#7695]
#### Your system information

* Steam link version (build number or date):  1.1.73.179
* Distribution (e.g. Ubuntu): Ubuntu 20.04.2, Mesa 20.3.4 - kisak-mesa PPA
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

First of all, a *huge* thank you for your work on Proton, making it possible to play games on Linux! Second, thank you very much for supporting Remote Play from Linux hosts supporting AMD Hardware!

I've recorded a video illustrating the issue with debug information turned on at https://youtu.be/6Aw1l0pAXgI

I've tried several client setups using the exact same host setup:

* Streaming to another Ubuntu 20.04.2 Machine using the regular Steam client: no stuttering, steady 60 FPS
* Streaming to a Raspberry Pi 4 using the Steam Link app: no stuttering, steady 60 FPS
* Playing the game locally on the host: no stuttering, steady 60 FPS

The stuttering only happens when streaming to the Steam Link app running on a NVIDIA Shield TV (I have two of them, a regular Shield TV and a Pro version and both show the same problem). I'm playing many LEGO and other Games using this Remote Play setup and so far it is only in the LotR one where I've observed these drops below 20 FPS when destroying things.

I've also played extensively with changing quality and the streaming bandwidth settings. The stuttering remains the same in all cases.

While the video shows a sequence about 10% into the game, the issue manifests right away. Just start the game and start walking around in the Shire destroying things and you'll observe the stuttering when using Remote Play via Steam Link to a NVIDIA Shield TV.

Here are my settings (also noted in the video description):

Setup Host:

Ubuntu 20.04.2
Sapphire Pulse Radeon RX 5700 (8GB)
Kernel 5.8.0-44
Driver: 4.6 (Compatibility Profile) Mesa 20.3.4 - kisak-mesa PPA
Proton 5.13-6
To be able to run Lego LotR: `protontricks 214510 d3dx9_41`
CPU: i7-6700

Setup Client:

Nvidia Shield TV Version 8.2.2 (32.6.509.0)
Steam Link Version: 1.1.73.179

Here are the requested log files:
[remote_connections.txt](https://github.com/ValveSoftware/steam-for-linux/files/6097066/remote_connections.txt)
[streaming_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6097067/streaming_log.txt)

#### Steps for reproducing this issue:

1. Install Lego LotR using `protontricks 214510 d3dx9_41`.
2. Connect via Steam Link on the NVIDIA Shield TV.
3. Start a new game which will bring you drop you in the Shire. Start destroying random things to experience the FPS drops.

**Comment by kisak-valve** [comment]
Hello @mss555, looking at your issue report, it sounds like this would be better handled as game-specific feedback and we're tracking issues with games run with Proton in the Proton issue tracker, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1836#issuecomment-792276260.

I'm personally not that familiar with Remote Play on the nVidia Shield TV, but it looks like it's the Steam Link for Android app and you can give feedback from that perspective on https://steamcommunity.com/app/353380/discussions/4/.
