### ISSUE TITLE
New steam beta update broke gamepad support.

### ISSUE THREAD

**Issue by blastermaster77** [ValveSoftware/steam-for-linux#7699]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20210126.2
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
After new steam beta update gamepad support is broken It lags, it shows multiple controllers connected
tested with xboxone s and 8bitdo controller, had to revert back to stable to fix it.

#### Steps for reproducing this issue:

1. update to new steam beta update
2. connect gamepad
3. Enjoy the input delay! :(

**Comment by brain-anti-freeze** [comment]
I'm seeing the same (on Arch 5.11).  In big picture you get one correct notification (showing the controller name) then repeated "generic controller" notifications every few seconds.  Controller settings shows the correct controller plus one generic one (I tried disabling generic controller support, no change).  Tried with a Xbox One and an Xbox One S controller, both wired and wireless (using xow).

Messages like this are logged in controller.txt every 5 seconds or so -
`[2021-03-12 17:16:28] Local Device Found
  type: 28de 11ff
  path: sdl://1
  serial_number:  - 0

[2021-03-12 17:16:28]   Manufacturer: 
[2021-03-12 17:16:28]   Product:      Steam Virtual Gamepad
[2021-03-12 17:16:28]   Release:      1
[2021-03-12 17:16:28]   Interface:    -1
[2021-03-12 17:16:28] Unrecognized controller using V1 HID protocol
[2021-03-12 17:16:28] !! Steam controller device opened for index 5.
[2021-03-12 17:16:28] BYieldingRegisterSteamController
[2021-03-12 17:16:28] BYieldingRegisterSteamController - couldn't get identity before registration.
[2021-03-12 17:16:28] Controller has an Invalid or missing unit serial number, setting to '28de-11ff-9e2a21'
[2021-03-12 17:16:28] BYieldingQueryAccountsRegisteredToController
[2021-03-12 17:16:29] CClientJobFetchPersonalizationFileID
[2021-03-12 17:16:30] Steam controller device closed after HID IO failure`

Reverting to stable fixed it.

**Comment by vaslabs** [comment]
same problem here, opting out of beta fixed the issue for me. After last night's update steam controllers are very laggy and crush often,

**Comment by DanMan** [comment]
I also get endless notification spam in the lower right corner: "Generic gamepad. Using configs from DanMan"

Unplugging the generic pad stops it.

**Comment by Markaos** [comment]
With Steam Controller, every I get constant notification spam and every time the notification pops up, it seems like a few events get dropped - it's very noticeable when using controller's touchpad as a mouse. Only happens in beta.

**Comment by t1764722** [comment]
Same with DS4 on Arch. Huge input delay and many dropped inputs with dualshock 4, whether wired or over bluetooth. Opting out of beta resolves the issue.

**Comment by josepapaianni** [comment]
+1 here, steam controller on Ubuntu 20.04.2 LTS

**Comment by DanMan** [comment]
They're working on it: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/4627984302695782288/#c4627984302696018162

**Comment by vaslabs** [comment]
just updated this morning and the issue seems fixed

**Comment by brain-anti-freeze** [comment]
Working for me now back on the beta client version 1615599054.

**Comment by blastermaster77** [comment]
it seems to be fixed now good job. closing. @kisak-valve
