### ISSUE TITLE
compatdata not moved when moving game from one steam library to another

### ISSUE THREAD

**Issue by floriplum** [ValveSoftware/steam-for-linux#7700]
#### Your system information

* Steam client version (build number or date): 1615510515
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When im moving games(only proton games since these write to the compdata folder) to a different drive, using the steam built in "move game" button, it wont move the compatdata saved along with it. Without moving the compatdata manually i need to reconfigure the settings since these are obviously unknown.

#### Steps for reproducing this issue:

1. Create multiple steam libraries and install a proton game to one of them.
2. Configure some changes in the game that would be saved to the compatdata folder.
3. Use the steam feature to move the game to the other library.
4. Start the game to notice that the settings are gone.

**Comment by kisak-valve** [comment]
Hello @floriplum, this issue is already being tracked at #5717. Closing as a duplicate.

**Comment by floriplum** [comment]
Sorry i didnt find anything searching for compatdata.
Thanks for the fast reply.
