### ISSUE TITLE
Steam is randomly crashing after X seconds

### ISSUE THREAD

**Issue by Klairm** [ValveSoftware/steam-for-linux#7702]
#### Your system information

* Steam client version (build number or date): Feb 12, 2021 
* Distribution (e.g. Ubuntu): Endeavour OS  5.11.6-arch1-1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) 
After X seconds of being launched, Steam crashes randomly, at first I thought it was because I was downloading a game but when I stopped the download it stills keep happening.
https://gist.github.com/Klairm/8fdb8192b3695eeb23071147427a71d4

#### Steps for reproducing this issue:

1. Launch Steam
2. Wait a couple of seconds
3. Steam will crash

**Comment by kisak-valve** [comment]
Hello @Klairm, these look like some lines of interest from your log:
```
src/tier1/utlmemory.cpp (307) : Assertion Failed: num >= 0
[...]
munmap_chunk(): invalid pointer
```

**Comment by Klairm** [comment]
Yes, I seen that when it crashes it always point to that file utlmemory.cpp but the errors are differents, sometimes it's `malloc(): unaligned tcache chunk detected`  or `malloc_consolidate(): invalid chunk size`  and also the one you said, all of this erros have in common that it mentions that file, what could be the problem?

**Comment by Klairm** [comment]
Somehow, it works fine now O.o idk what it was
