### ISSUE TITLE
Italian localization covers download speed limit UI in Steam settings

### ISSUE THREAD

**Issue by emmecii** [ValveSoftware/steam-for-linux#7709]
#### Your system information

* Steam client version (build number or date): 12th Feb 2021 build 1613176728
* Distribution (e.g. Ubuntu): Ubuntu 20.04.2 with Gnome 3.36.8
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Trying to put a limit for the download speed inside Steam client, the part of UI to put this limit is borked because the checkbox and the apply button is under other text of the window setting UI and I can't apply this limit as picture attached

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Got to settings>Download>Download restrictions
2. 
3. 
![immagine](https://user-images.githubusercontent.com/22106041/111869213-8aa6bd80-897e-11eb-9c1f-16d5443c137b.png)

**Comment by Cippo95** [comment]
How much time does it take to fix a simple UI issue?

**Comment by emmecii** [comment]
> How much time does it take to fix a simple UI issue?

For the record, this issue is still present

**Comment by emmecii** [comment]
For the record, this issue is still present

**Comment by emmecii** [comment]
For the record, this issue is still present

**Comment by Cippo95** [comment]
This issue was fixed for me in some recent update, I think it can be closed... 2 years to fix this UI issue lol
![2023-02-17_1920x1080_001_fixed](https://user-images.githubusercontent.com/38652363/219627986-610c7001-41a5-4430-8466-8b98bcd595f1.png)

**Comment by emmecii** [comment]
As @Cippo95 stated, the issue seems resolved (tested on my side, all is ok now) and can be considered closed. Looking at the changelogs, there is no fix related to this issue, or it was resolved with some fix on UI rendering for other bugs
