### ISSUE TITLE
compatiability deselect doesn't stick

### ISSUE THREAD

**Issue by codeman101** [ValveSoftware/steam-for-linux#7712]
#### Your system information

* Steam client version (build number or date): Feb 12 2021
* Distribution (e.g. Ubuntu): ArcoLinux
* Opted into Steam client beta?: yes I think so]
* Have you checked for system updates?: yes
*
#### Please describe your issue in as much detail as possible:
if you go the properties of a game and select a custom proton version to run the game but then want to switch back to the default proton version unchecking the force specific proton version doesn't stay unchecked so you're "forced" to the force the default proton version.

#### Steps for reproducing this issue:

1. take a game (for me it was LEGO® Star Wars™ III: The Clone Wars™ (32510)( and select a custom proton version. 
2. run the game with it then close the game and go to uncheck the force option.
3. go back to the same screen and you'll notice the force option is still checked

Note I realize what I wrote here is filled with piuns about "force" but I'm dead serious. None of the puns were intended.

**Comment by kisak-valve** [comment]
Hello @codeman101, this issue is already being tracked at #7671. Closing as a duplicate.
