### ISSUE TITLE
display windows cd keys on linux, if compatibility enabled!

### ISSUE THREAD

**Issue by mendiromania** [ValveSoftware/steam-for-linux#7718]
#### Your system information

* Steam client version (build number or date): March 23 2021
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
currently there's no option to show cd keys for windows games, even if compatibility is ticked. showing keys for linux games works fine. if compatibility is ticked, maybe make it so that it also shows windows games.

#### Steps for reproducing this issue:

1. go to library
2. right click any windows game with a cd key
3. no cd keys available if you're on linux

**Comment by kisak-valve** [comment]
Hello @mendiromania, there's no point in fragmenting the discussion in #212 over multiple issue reports. Closing as a duplicate.

**Comment by mendiromania** [comment]
I wasn't sure if it's a separate issue or not thanks

**Comment by mendiromania** [comment]
mentioned issue was posted on Dec 21, 2012 😭
