### ISSUE TITLE
Xbox controller only detected if connected before Steam is launched

### ISSUE THREAD

**Issue by lhindir** [ValveSoftware/steam-for-linux#7729]
#### Your system information

* Steam client version (build number or date): latest as of 2021-03-30 (March 25 part 2)
* Distribution (e.g. Ubuntu): NixOS (Gnome 3.38 Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Xbox controllers are not recognized by Steam unless they are present before Steam is started. If an Xbox controller disconnects, Steam must be fully restarted before it will be recognized by Steam or games again. I'm on Gnome Wayland and use an Xbox One controller connected to a Microsoft dongle via [xow](https://github.com/medusalix/xow). Steam Controllers connected via the dongle and a PS4 controller connected via Bluetooth are hotplugging fine.

#### Steps for reproducing this issue:

1. Connect Xbox One controller
2. Launch Steam
3. Power cycle Xbox One controller
4. ????
5. Profit!

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Lawstorant** [comment]
Just for posterity, I recently got the same issue in my Laptop running Arch Linux. Weirdly enough, my PC running the same sytem is fine. Adding the same env variable fixed the issue.
