### ISSUE TITLE
CSGO does not run on Arch linux kernel 5.11

### ISSUE THREAD

**Issue by arijitroy003** [ValveSoftware/steam-for-linux#7730]
#### Your system information

* Steam client version (build number or date): appid(steam)/version(1616532526) / Loaded SDL version 2.0.15-6379350
* Distribution (e.g. Ubuntu): Archlinux (5.11.9-arch1-1)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
1. Current rolling release of archlinux installs csgo normally, 
2. Runs for the first time then crashes after some time and does not open again.
3. I have verified the integrity of local files and reinstalled the game multiple times but when you press the play, the OpenGL window opens with a black screen waits for a few seconds and it stops. Steam-client does not crash but csgo does not run, goes back to its initial state.
![Screenshot from 2021-03-31 11-19-33](https://user-images.githubusercontent.com/43462564/113096580-0de3d100-9213-11eb-928b-8f7edd290829.png)

#### Steps for reproducing this issue:

1. Current rolling release of archlinux installs csgo normally, 
2. Runs for the first time then crashes after some time and does not open again.
3. I have verified the integrity of local files and reinstalled the game multiple times but when you press the play, the OpenGL window opens with a black screen waits for a few seconds and it stops. Steam-client does not crash but csgo does not run, goes back to its initial state.

**Comment by kisak-valve** [comment]
Hello @arijitroy003, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2659. Closing as a duplicate.
