### ISSUE TITLE
Steam claims XCOM 2 is still running, even after reboot. Sends SIGINT to SystemD on Stop request

### ISSUE THREAD

**Issue by Takios** [ValveSoftware/steam-for-linux#7733]
#### Your system information

* Steam client version (build number or date): Mar 23 2021
* Distribution (e.g. Ubuntu): opensuse Tumbleweed
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
XCOM 2 crashed for me today. It's still labeled as running in Steam. When clicking on Stop, Steam sends a SIGINT to the SystemD process running for my user (according to the Journal), killing my graphical session and I have to login again. Worse, even after restarting Steam or **completely rebooting** my computer, Steam still says XCOM 2 is running.

#### Steps for reproducing this issue:

No idea. I don't know enough about how Steam determines the state of a game enough to debug this further on my own.

**Comment by Takios** [comment]
The issue has gone away now and I cannot reproduce it anymore. If you like you can close this issue although maybe measures could be implemented to make sure Steam doesn't kill system processes.

**Comment by kisak-valve** [comment]
Hello @Takios, glad to hear it started behaving. I guess we should treat this as a fluke without there being a hint to investigate.

Regarding Steam trying to kill system processes, any regular user shouldn't have the rights to kill another user's processes, including system daemons, and running Steam as root is explicitly not supported, so at least that element of the riddle should be harmless.
