### ISSUE TITLE
Always re-downloading shaders for Rise of The Tomb Raider (native)

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7738]
#### Your system information

* Steam client version (build number or date): Mar 23 2021
* Distribution (e.g. Ubuntu): ArchLinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia GTX 970 4GB (Driver: 460.67)
* Kernel: 5.11

#### Please describe your issue in as much detail as possible:
Steam client is always re-downloading Rise of The Tomb Raider (native) shaders  every time I play and reboot the system. I always let Steam client processing the shaders.

**Comment by kisak-valve** [comment]
Hello @ranplayer, this issue is already being tracked at #6546. Closing as a duplicate.
