### ISSUE TITLE
(big picture) system freezes when opening the friends chat page

### ISSUE THREAD

**Issue by legacychimera247** [ValveSoftware/steam-for-linux#7741]
#### Your system information

* Steam client version (build number or date): latest stable one
* Distribution (e.g. Ubuntu): fedora workstation 33
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Graphic card : nvidia 530 with 390 proprietary drivers

Well if i enter steam in big picture mode and enter the friends menu, everything freezes, most of the times. To make things back to normal i have to

1 force reboot or
2 press the super key, wait a few seconds till i'm back to the gnome activities screen then force quit steam, cause re-entering steam will result in another freeze. Oh and by the way, if i do that while the night light feature is enabled, the light night is gone

#### Steps for reproducing this issue:

1. Open steam in big picture
2. Open the friends page
3. See everything freezing

**Comment by kisak-valve** [comment]
Hello @legacychimera247, for this issue, #7742, and #7743, can you go to Steam -> Settings -> Interface, uncheck `Enable GPU accelerated rendering in web views` and test if that has an effect?

**Comment by legacychimera247** [comment]
hello, seems that this solves all the 3 issues in a row, really thank you

i'll reopen if needed

**Comment by legacychimera247** [comment]
hello, reopening since seems that the issue is not solved, considering it's something that happens mostly when night light is on i guess it's related?

**Comment by legacychimera247** [comment]
this is the terminal output when doing this...

`OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Selection Path for App ID 413080, Controller 0: /home/luca247/.local/share/Steam/steamapps/workshop/content/241100/922638163/818937737353552570_legacy.bin
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_BigPicture, AppID 413090
Loaded Config for Local Selection Path for App ID 413090, Controller 0: /home/luca247/.local/share/Steam/steamapps/workshop/content/241100/1557881022/956347096063773104_legacy.bin
[413090-1557881022]: Successfuly started tracking playtime
AL lib: (WW) alGetError: Querying error state on null context (implicitly 0xa004)
OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Selection Path for App ID 413080, Controller 0: /home/luca247/.local/share/Steam/steamapps/workshop/content/241100/922638163/818937737353552570_legacy.bin`

**Comment by legacychimera247** [comment]
any news on that?it's becoming very tedious...

**Comment by legacychimera247** [comment]
any news on this?because it becoming really frustrating...

**Comment by legacychimera247** [comment]
i have a new pc now with a redeon card and everything is fine, but still it was already fine with latest updated so i guess we can close this
