### ISSUE TITLE
Steam ignores my notification prefrences and steals focus from the game I playing when receviing an invite.

### ISSUE THREAD

**Issue by bluelightzero** [ValveSoftware/steam-for-linux#7744]
I have gone into notifications and turned off all of them:

![image](https://user-images.githubusercontent.com/4492982/114119946-80277600-98e3-11eb-8391-74944ab51542.png)

But when someone invites me to a party, it will steal focus and pop-up the chat:

![image](https://user-images.githubusercontent.com/4492982/114120237-00e67200-98e4-11eb-8836-affb98f76dab.png)

This should never happen if all notifications are off.

There is no need to even have this pop-up as the game has it's own invite message built into the game.

**Comment by kisak-valve** [comment]
Hello @bluelightzero, this issue is already being tracked at #5286. Closing as a duplicate.
