### ISSUE TITLE
Steam doesn't hotplug uinput devices.

### ISSUE THREAD

**Issue by YellowOnion** [ValveSoftware/steam-for-linux#7746]
#### Your system information

* Steam Runtime Version: 
* Distribution : NixOS 21.05
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/YellowOnion/53fa0572ecf445f22bf3bd1ac39cce28
  
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Not sure?

#### Please describe your issue in as much detail as possible:

I wrote a [script to emulate an xbox controller](https://gist.github.com/YellowOnion/ecadcd5d2a55982a7fe74989dbbc1642)

Steam doesn't detect the new device until I restart Steam.

#### Steps for reproducing this issue:

1.  start steam
2. use [pyevdev](https://python-evdev.readthedocs.io/en/latest/tutorial.html#injecting-input) to create a virtual xbox controller
3.  steam doesn't see it.

**Comment by YellowOnion** [comment]
udevadm log:

```
$ udevadm monitor 
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[520375.842949] add      /devices/virtual/input/input30 (input)
KERNEL[520375.842968] add      /devices/virtual/input/input30/event22 (input)
KERNEL[520375.842978] add      /devices/virtual/input/input30/js1 (input)
UDEV  [520375.843935] add      /devices/virtual/input/input30 (input)
UDEV  [520375.844898] add      /devices/virtual/input/input30/js1 (input)
UDEV  [520375.884209] add      /devices/virtual/input/input30/event22 (input)
```

**Comment by baracoder** [comment]
I have the same issue on NixOS. I have retested with the flatpak version on NixOS and it recognizes controllers no problem, so I think this is related to the native FHS environment.

**Comment by kisak-valve** [comment]
Closing per the last comment.
