### ISSUE TITLE
Celeste fails to launch due to a SIGABRT during SteamAPI_Init

### ISSUE THREAD

**Issue by kforney** [ValveSoftware/steam-for-linux#7750]
#### Your system information

* Steam client version (build number or date): Built Apr 12 2021, at 18:51:43 (package version 1618256785)
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Celeste fails to launch at all. This occurs in both the Steam beta and non-beta, and regardless of whether or not the Steam Linux Runtime is used. Debugging with gdb appears to indicate that the issue may be caused by libsteam_api.so . 

This issue does not occur if the Windows version of the game is run through Proton, or when running the DRM-free Linux version from itch.io.

[Here is the output from gdb.](https://gist.github.com/kforney/6527378ac11312db94aadcca9f5ddcc3)

[And here is my system information from Steam.](https://gist.github.com/kforney/06ca63398435fc68d24c8a696bbefa09)

#### Steps for reproducing this issue:

1. Try to run Celeste.
2. It won't actually launch, but the process "Celeste.bin.x86_64" will stick around until killed manually.

**Comment by kisak-valve** [comment]
Hello @kforney, this issue should also be mentioned to the game's dev(s) if it hasn't been already.

**Comment by kforney** [comment]
Yes, I actually started with that: [Steam discussion link](https://steamcommunity.com/app/504230/discussions/4/3100141190333083343/)

Developer flibitijibibo recommended I report the issue here as well, since the gdb output indicated a possible Steam-related issue.

**Comment by kforney** [comment]
The issue appears to have been resolved, either by a recent Arch or Steam update.
