### ISSUE TITLE
0 bytes downloaded at game installation (Hobo: Tough Life)

### ISSUE THREAD

**Issue by CzechGod** [ValveSoftware/steam-for-linux#7751]
#### Your system information

* Steam client version (build number or date): 
![obrazek](https://user-images.githubusercontent.com/24473687/114835725-28e94000-9dd2-11eb-9362-34b7adc1e8b1.png)

* Distribution (e.g. Ubuntu): Manjaro 21 (kernel 5.10.26-1-MANJARO)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I'm trying to install game Hobo but no files are downloaded (just empty folder was created). 

It's weird - no errors and verification files is OK too :D

Downloading updates to other games was correctly.

I tried pc restart, cache clearing, changing regions, target folder - nothing helped.

#### Steps for reproducing this issue:
1. uninstalling "empty" game
2. clearing download cache
3. installing hobo
=> 0 bytes downloaded

![steam-hobo](https://user-images.githubusercontent.com/24473687/114834901-4ff34200-9dd1-11eb-8f44-5ee587b01ba8.png)

**Comment by kisak-valve** [comment]
Hello @CzechGod, it looks like depot 632302 is missing from sub 172249. This should be mentioned to the game's dev(s). (Probably in https://steamcommunity.com/app/632300/discussions/0/3078747887939929177/.)

**Comment by CzechGod** [comment]
it looks as same issue, thx ;)
(and it would be nice if steam client shows some download error)
