### ISSUE TITLE
Can't Open Steam AT ALL

### ISSUE THREAD

**Issue by Arvicii** [ValveSoftware/steam-for-linux#7759]
* Steam client version (build number or date): 18th April 2021
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Problem:
I cannot open steam at all. When I click on the icon, a window pops up and says "checking for updates" for less than a second and it just closes steam. I have tried manually reinstalling steam and I have also tried a COMPLETE uninstall and purge of steam then re-installing steam. nothing seems to work and it has been like this for 3-4 days now. I tried emailing support but they weren't much help either.

**Comment by kisak-valve** [comment]
Hello @Arvicii, if you run `steam` from a terminal, does the terminal spew give any hints?

**Comment by kisak-valve** [comment]
Thanks, `swrast` is mesa's slower software renderer and the fact that Steam is trying to use it hints that you're using the nVidia proprietary driver, but don't have 32 bit userspace support installed. If this is true, then please check which video driver series you have, then install 32 bit userspace support with something like `sudo apt install libnvidia-gl-460:i386`. (Replace 460 with the driver series you have installed.)

**Comment by Arvicii** [comment]
It worked. Thanks for the help!

**Comment by kisak-valve** [comment]
Glad to hear you got it working. Closing as a system config issue.
