### ISSUE TITLE
Checksum for Steam Client installer - where I can find it? SHA256 or SHA512 is needed...

### ISSUE THREAD

**Issue by motocyklista** [ValveSoftware/steam-for-linux#7761]
#### Your system information

* Steam client version (build number or date): it doesn't matter
* Distribution: Ubuntu 20.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I would like to install official installer (.deb) from official Steam website, this is a link ---> https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb

My problem is with security. How I can check that installer file is not corrupted or Meet in the Middle Attack if I don't know what is the checksum SHA256 or SHA512 for this file? You should share with us with checksum on official Steam website.

I hope that you will do this. This is very important to security reason.

P.S. Do you have GPG public key? Maybe the best way is to upload checksum file with GPG public key so it is the best way to do it.

Second question is to repository for Ubuntu. Maybe this is more safe way to get steam client but I must know what is the official steam client (name of the package for Ubuntu for apt command).

Yours faithfully,
Piotr

**Comment by kisak-valve** [comment]
Hello @motocyklista, take a look at .dsc files in https://repo.steampowered.com/steam/archive/stable/ and it looks like there's a steam.gpg in there as well.

**Comment by motocyklista** [comment]
@kisak-valve okay but you don't have checksum for the files. That is mean that I should check installer directly by GPG. Most popular is to check with GPG checksum file than if it is verified manually check each file in terminal by 'sha256sum' command and compare with checksum file.

I hope that you will help me and explain.

**Comment by smcv** [comment]
The apt repository provided at https://repo.steampowered.com/steam/ uses standard secure-APT, the same as Debian and Ubuntu. https://repo.steampowered.com/steam/dists/stable/InRelease is a GPG-signed manifest for the whole of the `stable` suite. It contains the sha256 of the Packages and Sources lists, which contain the sha256 of the actual package.

https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb seems to be redirecting to the official .deb on repo.steampowered.com.

**Comment by motocyklista** [comment]
@kisak-valve so I must add new repository for this link? https://repo.steampowered.com/steam/archive/stable/

Can you tell me if this should look like this: "deb [arch=amd64] https://repo.steampowered.com/steam/archive/stable/ stable main"? So I should use following comman? sudo sh -c 'echo "deb [arch=amd64] https://repo.steampowered.com/steam/archive/stable/ stable main" > /etc/apt/sources.list.d/steam.list'

Above command is correctly? If your answer is yes what command is for install steam? Sudo apt install steam-stable?

**Comment by kisak-valve** [comment]
Manually setting up Steam's package repo isn't something I have done myself and I'm not going to pretend I have, but I can tell you that an Ubuntu test box has this in `/etc/apt/sources.list.d/steam.list`:

```
deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam

# Uncomment these lines to try the beta version of the Steam launcher
# deb [arch=amd64,i386] https://repo.steampowered.com/steam/ beta steam
# deb-src [arch=amd64,i386] https://repo.steampowered.com/steam/ beta steam
```

Also,
```
$ apt policy steam steam-launcher
steam:i386:
  Installed: 1:1.0.0.70
  Candidate: 1:1.0.0.70
  Version table:
 *** 1:1.0.0.70 500
        500 https://repo.steampowered.com/steam stable/steam i386 Packages
        100 /var/lib/dpkg/status
     1:1.0.0.61-2ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 Packages
steam-launcher:
  Installed: 1:1.0.0.70
  Candidate: 1:1.0.0.70
  Version table:
 *** 1:1.0.0.70 500
        500 https://repo.steampowered.com/steam stable/steam amd64 Packages
        500 https://repo.steampowered.com/steam stable/steam i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by motocyklista** [comment]
@kisak-valve thank you very much for answer. So if you didn't setting up the repo so how you installed steam client? From source compilation or how? Can you tell me? What is the best way to install steam on linux. I want do this in safe method. Like you know I want to check installer with GPG key.
