### ISSUE TITLE
Can't disable overlay in non-Steam games.

### ISSUE THREAD

**Issue by YellowOnion** [ValveSoftware/steam-for-linux#7762]
#### Your system information

* Steam client version (build number or date): 2021-05-12
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

There is no option to disable overlay in non-steam games.

![image](https://user-images.githubusercontent.com/364160/115659503-c2928d80-a38e-11eb-85a1-d56e47849542.png)
![image](https://user-images.githubusercontent.com/364160/115659523-c9210500-a38e-11eb-9669-5ad0f78913d1.png)

**Comment by kisak-valve** [comment]
Hello @YellowOnion, this issue is already being tracked at #2804. Closing as a duplicate.
