### ISSUE TITLE
 Gamepads don't work in proton games after the last Steam client update.

### ISSUE THREAD

**Issue by Igortorrente** [ValveSoftware/steam-for-linux#7764]
#### System information

* Steam build date: Apr 12 2021, at 18:51:43
* Steam package version: 1618256785
* Distribution: Debian 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I have a PS4 and a PS2 to USB dongle, and both were working on proton games like Journey, Ori and Blind Forest, and Cuphead, but since the last steam update, the controllers don't work anymore in those games.
These still work in the big picture and left 4 dead 2(native port) though.

#### Steps for reproducing this issue:

1. Connect the controller to PC
2. Start steam in the big picture mode
3. Start a game that uses proton
4. The game will not recognize any joystick

**Comment by Cat-Lady** [comment]
Possibly related to:
https://github.com/ValveSoftware/Proton/issues/4775

...?

**Comment by Igortorrente** [comment]
I don't know if it makes any difference, but I'm using a different proton version in each of the games that I mentioned(Because each game needs a different version to work properly).

In CupHead I'm using the latest proton version, while journey and ori and blind forest I'm using proton 5.0-10.

**Comment by kkartaltepe** [comment]
I think I am also experiencing this on Archlinux.

**Comment by kkartaltepe** [comment]
> Possibly related to:
> ValveSoftware/Proton#4775

I attempted the workaround with setting `HKEY_LOCAL_MACHINE -> System -> CurrentControlSet -> Services -> WineBus` (apparent typo in the linked issue of `Software -> System` which doesnt exist on my registry). However the only difference i could tell is that this prevented the virtual XBox 360 joystick from being created. No input was registered in the game (even after creating a `SDL_GAMECONTROLLERCONFIG` environment variable and passing through to the game, though historically I have never done this).

**Comment by Igortorrente** [comment]
> > Possibly related to:
> > [ValveSoftware/Proton#4775](https://github.com/ValveSoftware/Proton/issues/4775)
> 

Yeah, the @Cat-Lady (The reporter of this bug) mentioned it.

> I attempted the workaround with setting `HKEY_LOCAL_MACHINE -> System -> CurrentControlSet -> Services -> winebus` `DisableHidraw` to `1`(apparent typo in the linked issue of `Software -> System` which doesnt exist on my registry). However the only difference i could tell is that this prevented the virtual XBox 360 joystick from being created. No input was registered in the game (even after creating a `SDL_GAMECONTROLLERCONFIG` environment variable and passing through to the game, though historically I have never done this).

**Comment by Cat-Lady** [comment]
You might want to try messing with few other registry keys related to the controllers - things form the very bottom of this page:
https://wiki.winehq.org/Useful_Registry_Keys

``Enable SDL``, ``DisableInput`` and ``MapControllers`` might be of special interest. It is a bit tedious, but testing them in various - often counter-intuitive - combinations might prove effective (For example, in my case, ``DisableInput`` seems to work exactly in reverse of the description, having it a 1 ENABLES input, and at 0 makes game stop registering it at all).

**Comment by Igortorrente** [comment]
@Cat-Lady Can you send here a tutorial link about how to change the registry keys?

Thanks

**Comment by kkartaltepe** [comment]
> You might want to try messing with few other registry keys related to the controllers - things form the very bottom of this page:
> https://wiki.winehq.org/Useful_Registry_Keys
> 
> `Enable SDL`, `DisableInput` and `MapControllers` might be of special interest. It is a bit tedious, but testing them in various - often counter-intuitive - combinations might prove effective (For example, in my case, `DisableInput` seems to work exactly in reverse of the description, having it a 1 ENABLES input, and at 0 makes game stop registering it at all).

I did play with those and they made no difference in my case.

**Comment by kkartaltepe** [comment]
fwiw this appears fixed for me on 1622844577 (built Jun 4) and proton experimental as well as proton 6.3-4.

On the beta client, proton 6.3-4 continues to work but proton experimental incorrectly maps buttons.

**Comment by Igortorrente** [comment]
> fwiw this appears fixed for me on 1622844577 (built Jun 4) and proton experimental as well as proton 6.3-4.
> 
> On the beta client, proton 6.3-4 continues to work but proton experimental incorrectly maps buttons.

Great to hear it, I will wait the release to confirm it myself.

Thanks for the information!

**Comment by kkartaltepe** [comment]
I mean it is working on the stable with proton experimental. It just appears to be re-broken if you use beta with experimental proton.

**Comment by Igortorrente** [comment]
Ohh,

The games doesn't work if I use anything newer than 5.0-10 :/.

**Comment by Igortorrente** [comment]
Magically it's working again.

**Comment by GNUGradyn** [comment]
I'm havng this issue with wiimotes on steam deck. Steam input works, but if you disable steam input, the controller is not available to any applications running in proton. This prevents use of wiimotes in cemu on proton for example
