### ISSUE TITLE
Steam Client crashes on start - Segmentation fault

### ISSUE THREAD

**Issue by user111222333** [ValveSoftware/steam-for-linux#7769]
#### Your system information

* Steam client version (build number or date):  Steam Version: 1.0.0.68-1 i386 [installed]
* Distribution (e.g. Ubuntu): Debian 11 (Bullseye) 
* Opted into Steam client beta?: [Yes/No] No ( it's a virgin install, since client doesn't run no was opt in to beta in UI)
* Have you checked for system updates?: [Yes/No] Yes.

A new PC hardware was used;
Brand new virgin OS installed - Debian 11 Bullseye;
Proprietary drivers from NVIDIA where installed for the GPU. 
OS starts as expected;
GPU performs as expected;
Steam client was installed via Debian provided repository, as usual;
Steam client was started, with no signs of it running in GUI.
System logs where investigated;
Please see the copy of the part of the log pertaining to the issue.
Please note, no other software, installed on the host. This host is dedicated to Steam Gaming. 

Tech specs of the host: 
System: Host: steam-pc11 
Kernel: 5.10.0-6-amd64 x86_64 bits: 64 Console: tty 0 
Distro: Debian GNU/Linux bullseye/sid
CPU: Info: 6-Core model: Intel Core i7-8700K bits: 64 type: MT MCP L2 cache: 12 MiB
Graphics: Device-1: NVIDIA TU102 [GeForce RTX 2080 Ti Rev. A] driver: nvidia v: 465.24.02
Display: x11 server: X.Org 1.20.10 driver: loaded: nvidia resolution: 2560x1080~60Hz
OpenGL: renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 465.24.02  
Steam Client version: 1.0.0.68-1 i386 [installed]

Please note, that only 48 hours ago, with exact same software environment, Steam Client ran just fine as expected. 
The only change is the hardware - CPU + GPU. 
The GPU driver is the same, OS the same and now - Steam fail to start. 

Please see the syslog: 

Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: libGL error: No matching fbConfigs or visuals found
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: libGL error: failed to load driver: swrast
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Steam: An X Error occurred
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: X Error of failed request: GLXBadContext
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Major opcode of failed request: 151
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Serial number of failed request: 52
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: xerror_handler: X failed, continuing
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Steam: An X Error occurred
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: X Error of failed request: BadValue (integer parameter out of range for operation)
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Major opcode of failed request: 151
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Value in failed request: 0x0
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Serial number of failed request: 51
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: xerror_handler: X failed, continuing
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Steam: An X Error occurred
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: X Error of failed request: BadMatch (invalid parameter attributes)
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Major opcode of failed request: 151
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: Serial number of failed request: 53
Apr 27 02:55:56 steam-pc11 steam.desktop[3014]: xerror_handler: X failed, continuing
Apr 27 02:55:56 steam-pc11 steam.desktop[3077]: assert_20210427025556_1.dmp[3077]: Uploading dump (out-of-process)
Apr 27 02:55:56 steam-pc11 steam.desktop[3077]: /tmp/dumps/assert_20210427025556_1.dmp
Apr 27 02:55:56 steam-pc11 assert_20210427025556_1.dmp[3077]: Uploading dump (out-of-process)#012/tmp/dumps/assert_20210427025556_1.dmp
Apr 27 02:55:56 steam-pc11 steam.desktop[2873]: /home/user1/.steam/debian-installation/steam.sh: line 771: 3014 Segmentation fault $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Apr 27 02:55:56 steam-pc11 kernel: [ 871.586316] steam[3014]: segfault at 0 ip 00000000f79a7db1 sp 00000000ffe5094c error 4 in libc-2.31.so[f7922000+155000]
Apr 27 02:55:56 steam-pc11 kernel: [ 871.586320] Code: 40 38 ca 0f 84 4d 01 00 00 80 f9 00 0f 84 71 01 00 00 40 4f 75 14 8a 08 38 ca 0f 84 36 01 00 00 80 f9 00 0f 84 5a 01 00 00 40 <8b> 08 bd ff fe fe fe bf ff fe fe fe 01 cd 31 cd 01 cf 8d 40 04 0f
Apr 27 02:55:57 steam-pc11 steam.desktop[3077]: assert_20210427025556_1.dmp[3077]: Finished uploading minidump (out-of-process): success = yes
Apr 27 02:55:57 steam-pc11 steam.desktop[3077]: assert_20210427025556_1.dmp[3077]: response: CrashID=bp-a7e84f65-02b5-4716-a9fb-30e332210427
Apr 27 02:55:57 steam-pc11 steam.desktop[3077]: assert_20210427025556_1.dmp[3077]: file ''/tmp/dumps/assert_20210427025556_1.dmp'', upload yes: ''CrashID=bp-a7e84f65-02b5-4716-a9fb-30e332210427''
Apr 27 02:55:57 steam-pc11 assert_20210427025556_1.dmp[3077]: Finished uploading minidump (out-of-process): success = yes
Apr 27 02:55:57 steam-pc11 assert_20210427025556_1.dmp[3077]: response: CrashID=bp-a7e84f65-02b5-4716-a9fb-30e332210427
Apr 27 02:55:57 steam-pc11 assert_20210427025556_1.dmp[3077]: file ''/tmp/dumps/assert_20210427025556_1.dmp'', upload yes: ''CrashID=bp-a7e84f65-02b5-4716-a9fb-30e332210427''
Apr 27 02:55:57 steam-pc11 systemd[1041]: app-gnome-steam-2866.scope: Succeeded.

Please advise what steps can be taken to resolve this, and what can I do to help the Dev team to diagnose this issue. 

Thank you for your development efforts.

**Comment by kisak-valve** [comment]
Hello @user111222333, swrast is mesa's slower software renderer and the fact that Steam is trying to use it hints that you're using nVidia's proprietary driver, but don't have 32 bit userspace support installed. The nVidia proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace are installed and have exactly the same version to work properly.

It looks like Debian Bulleye's repos do not provide nVidia 465.24.02, so whatever alternative install method you used for the video driver has failed to give you 32 bit OpenGL support. Possibly look for `nvidia-driver-libs:i386`.

**Comment by user111222333** [comment]
Got it. Thank you for your feedback. 
During the installation of NVIDIA proprietary driver, installer did prompted if i386 components should be installed... I responded with the 'yes'. 
I will reinstall NVIDIA driver, and report back if the issue has been resolved.

**Comment by user111222333** [comment]
Ok, reporting back. 
Removing proprietary NVIDIA driver ver. 465.24.02 and replacing it with NVIDIA proprietary driver ver: 460.73.01 resolved the issue with Steam Client crushing on start. 

Thank you for your quick response and support.
