### ISSUE TITLE
Shortcut launch failed (non-steam game)

### ISSUE THREAD

**Issue by pseregiet** [ValveSoftware/steam-for-linux#7772]
#### Your system information

* Steam client version (build number or date): Apr 12 2021 at 18:51:43
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I play few games outside of steam with proton. I know this might not be a very common use-case, but hey, it works. At least it did until today. For no apparent reason some of my shortcuts (i.e "Add a  non-steam game to library") stopped working. I get an error message "Steam - Shortcut launch failed. Failed to launch Name Of The Game". I was using steam beta (must have opted-in way back when because I didn't even remember that). Tried regular Steam, still the same problem. Tried to create another shortcut, still the same problem. Interestingly enough, another shortcut for a different game works just fine. Here's what I see in the terminal when I press Play on such a shortcut:
```
GameAction [AppID 2532115102, ActionID 9] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 2532115102, ActionID 9] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 2532115102, ActionID 9] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 2532115102, ActionID 9] : LaunchApp continues with user response "CreatingProcess"
src/clientdll/compatmanager.cpp (740) : Assertion Failed: CCompatManager::GetCompatibilityToolCommandLineInternal: tool 0 "" not found for appID -1762852194
src/clientdll/compatmanager.cpp (740) : Assertion Failed: CCompatManager::GetCompatibilityToolCommandLineInternal: tool 0 "" not found for appID -1762852194
GameAction [AppID 2532115102, ActionID 9] : LaunchApp failed with AppError_51 with ""
GameAction [AppID 2532115102, ActionID 9] : LaunchApp changed task to Failed with ""
```

Negative appID seems strange, doesn't it ? Looking at the compatdata directory I see that the failing game got an appID 2332010280. At first I thought it must be a problem with an int overflow, but the other game that doesn't fail to launch has an even bigger ID... 

#### Steps for reproducing this issue:

1. Add non-steam game to your library
2. Try to run it
3. Get this error

EDIT: I figured out a "fix". If you go to the Compatibility tab for the affected shortcut and uncheck "force a specific version" and then try to launch the game, it won't give you this error. Although the game won't launch either. Then you can go back, select the proton version you want and the game works again.

**Comment by kisak-valve** [comment]
Hello @pseregiet, this reads like the same issue as #7664, so I've transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/7664#issuecomment-829164082.
