### ISSUE TITLE
Nintendo Switch Pro Controller random disconnects with rumble enabled

### ISSUE THREAD

**Issue by AwesamLinux** [ValveSoftware/steam-for-linux#7776]
#### Your system information

* Steam client version (build number or date): 1618256785   (Built Apr 12 2021)
* Distribution (e.g. Ubuntu): Linux Mint 20.1
* Opted into Steam client beta?: Currently no (but tried both)
* Have you checked for system updates?: Yes
[system_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/6409676/system_info.txt)

#### Please describe your issue in as much detail as possible:
Nintendo Switch Pro Controller over bluetooth randomly disconnects when rumble is enabled (in Steams controller settings). The more rumble feedback a game has, the more frequent the problem occurs.

I have tried both the client version above, and the current beta available version available today 1/5.

I remember having this exact same problem sometime last year, it got fixed at some point with a client update if I remember correctly, but now the problem appears to be back.

#### Steps for reproducing this issue:

1. Make sure rumble is enabled in Steams controller settings
2. Play a game that has rumble, I tried it with the Linux Native game DRAG, and R-Type Final 2 through Proton.
3. Controller will randomly disconnect

**Comment by kisak-valve** [comment]
Hello @AwesamLinux, this issue is already being tracked at #7631. Since your issue report adds some additional insight, I've transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/7631#issuecomment-830642325.

Closing as a duplicate.
