### ISSUE TITLE
Everspace II April 28 Update Fail

### ISSUE THREAD

**Issue by kxtg** [ValveSoftware/steam-for-linux#7781]
#### Your system information

AMD Ryzen 7 2700 Eight-Core
Kernel Version:  5.11.6-1-MANJARO
X Window Manager:  Xfwm4
Steam Runtime Version:  steam-runtime_0.20210317.0
Driver: AMD Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.11.6-1-MANJARO, LLVM 11.1.0)
        Driver Version:  4.6 (Compatibility Profile) Mesa 20.3.4
        OpenGL Version: 4.6
Steam API: v020
Steam package versions: 1618256785 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

Running Everspace II on Steam/Proton 6.3-2 and 5.13-6 after April 28 Update:
. The following component(s) are required to run this program: Microsoft Visual C++ Runtime Would you like to install them now ---> Yes
. Accept Third Party Software, click Install
. UE4 Prerequisites (x64) Setup Failed see log file / ox80070538 - Invalid ACL.

Would a permissions tweak ('$ getfacl foldername') work somewhere?

#### Steps for reproducing this issue:

1. Run April 28 Everspace II update.
2. 
3.

**Comment by kisak-valve** [comment]
Hello @kxtg, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4762#issuecomment-831400427.
