### ISSUE TITLE
Steam Input implementation interfering with native Switch Pro Controller driver

### ISSUE THREAD

**Issue by clarfonthey** [ValveSoftware/steam-for-linux#7786]
#### Your system information

* Steam client version (build number or date): Apr 27, 2021 at 23:10:40 (package version 1619570428)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I use the native hid-nintendo driver to get my Switch Pro controller working outside of steam. (see: #6651)

Right now, the built-in Steam Input driver interferes with the native driver in frustrating ways. In order to get things to work with the native driver, I have to use the suggested workaround of running Steam in firejail (`usr/bin/firejail --noprofile --blacklist=/sys/class/hidraw/ /usr/bin/steam-runtime`) which completely overrides any Steam Input settings, but lets me use my controller in games with minimal issues. If I open steam without firejail, Steam Input works, but the controller is interpreted as a mouse and keyboard in other apps while Steam is open, and I can't natively use the controller outside of steam.

I'm making a new issue because despite several requests in the other ticket (#6651) this is still an issue affecting users, and I would prefer to be able to launch steam without having to look up a firejail command just to make things work with my controller.

At minimum, Steam for Linux should detect if the hid-nintendo driver is present and use that instead of its own driver if available, so that Steam Input can still work as expected. Otherwise, the default implementation is fine.

**Comment by kisak-valve** [comment]
Hello @clarfonthey, there's no value in fragmenting the discussion of this issue over multiple issue reports. I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/6651#issuecomment-834250239 because you add a bit more insight.

Closing as a duplicate.
