### ISSUE TITLE
Requiring better threading and/or async IO for scanning games on drives

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/steam-for-linux#7802]
#### Your system information

* Steam client version (build number or date): 19.5.2021 01:54:04, package 1621394999
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With large installs it would be beneficial if Steam client has better threading and/or using asynchronous IO for the scanning. Problems occur with large file amounts (several terabytes across multiple drives) causing Steam client to fail starting.

For one, better threading/async IO would allow using the client in the mean time (chat, community hub etc.).
Second, whole client is killed by OS or crashes when it is unresponsive for too long.
Problem is apparent when starting the client with large number of games installed. 

Currently I have to do following
1. unmount largest drive 
2. start Steam
3. remount the largest drive
4. add the drive content back into Steam (add library folders)

Expected behaviour would be that Steam client could start even with large installs without need to go through umount/mount/readd steps.

All drives are now using ext4. Trying to pre-cache filelist (such as du -sh) is not helping any more. In the past games with large amount of files had worse effect than games with simply few but large files. Size of games is rapidly growing and old workarounds are not working any longer to get client starting cleanly, thus needing the unmount-dance described above.

As a stop-gap measure to fix the immediate problem with starting, client should start first then automatically "add" the configured libraries for the user so that the procedure would be simplified/automated. Since the adding after starting seems to work most of the time that should not be too hard to change in the client and would improve client behaviour rapidly.

Occasionally adding large libraries afterwards (when client has started) will not work either and client terminates: this is where better async IO/threading would prove most beneficial.

#### Steps for reproducing this issue:

1. Boot computer, start Steam client
2. Observe that Steam client terminates before reaching "connecting.."

Alternatively:
1. add large Steam library after starting client
2. observe that client terminates while scanning

**Comment by kisak-valve** [comment]
Hello @ipr, if you run `steam` from a terminal, does the terminal spew give any hints?

Possibly related to #7630.

**Comment by kakra** [comment]
> Possibly related to #7630.

Yes that seems likely, I'm also having quite a large Steam lib.

**Comment by ipr** [comment]
src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (837) : Fatal assert; application exiting
src/common/pipes.cpp (837) : Fatal assert; application exiting
Installing breakpad exception handler for appid(steam)/version(1621394999)
assert_20210523002108_15.dmp[425377]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210523002108_15.dmp
_ExitOnFatalAssert

assert_20210523002108_15.dmp[425377]: Finished uploading minidump (out-of-process): success = yes
assert_20210523002108_15.dmp[425377]: response: CrashID=bp-81272831-a045-429c-87cb-761922210522
assert_20210523002108_15.dmp[425377]: file ''/tmp/dumps/assert_20210523002108_15.dmp'', upload yes: ''CrashID=bp-81272831-a045-429c-87cb-761922210522''

I'll look into uploading dump files.

**Comment by kakra** [comment]
> I'll look into uploading dump files.

I think it was already uploaded to Valve. All they need is probably the crash ID which is already part of the log you posted.

**Comment by ipr** [comment]
> > I'll look into uploading dump files.
> 
> I think it was already uploaded to Valve. All they need is probably the crash ID which is already part of the log you posted.

Ok, good.

**Comment by ipr** [comment]
Looks like new version of Steam client improves starting and I can avoid the unmount+mount things now. Good stuff!

**Comment by kakra** [comment]
I don't think your problem is related to async IO or threading. The stalls you're experiencing happen after the crash event when Steam creates a crash dump and cleans up process memory. The original crash event is probably an OOM issue with large libraries.

But yes, it looks like it received some fixes but I'm still seeing crashes from time to time - and if that happens while in a game, it will immediately crash the game, too, usually resulting in a lot of IO thrashing which feels like the issue might be with IO or threading in the client but really it's the aftermath of the crash when the system cleans up memory and swaps pages back in (which doesn't necessarily mean "swap" but also re-populate caches and page executable code back in for running processes).

**Comment by ipr** [comment]
> I don't think your problem is related to async IO or threading. The stalls you're experiencing happen after the crash event when Steam creates a crash dump and cleans up process memory. The original crash event is probably an OOM issue with large libraries.

No, you got it backwards. It is definitely reporting timeout while scanning disk, crash dump happens AFTER it while there is plenty of memory. And I've disabled the shader cache which was a problem with many other users.

> But yes, it looks like it received some fixes but I'm still seeing crashes from time to time - and if that happens while in a game, it will immediately crash the game, too, usually resulting in a lot of IO thrashing which feels like the issue might be with IO or threading in the client but really it's the aftermath of the crash when the system cleans up memory and swaps pages back in (which doesn't necessarily mean "swap" but also re-populate caches and page executable code back in for running processes).

Again, to be absolutely clear about this: problem occurs during starting of Steam CLIENT, not when starting a game from it.

To tell it as simply as possibly so I can get through to you:
1. ensure there is no steam client running (that's the binary called "steam" you know)
2. start steam (that's the steam client called "steam" you know)
3. observe timeout and abort

It was never about starting a game in this issue.

The changes made to Steam library and storage likely changed the method of scanning/storing information enough that it is now fast enough to avoid the timeout.

Please read the information before commenting.

**Comment by kakra** [comment]
> src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.

This one can simply mean that the process on the other side of the pipe already died... It's not necessarily a timeout. But only the Steam developers will know.

**Comment by ipr** [comment]
> > src/common/pipes.cpp (837) : fatal stalled cross-thread pipe.
> 
> This one can simply mean that the process on the other side of the pipe already died... It's not necessarily a timeout. But only the Steam developers will know.

Sure, but considering rest of evidence (high disk activity still going and so on) the MOST likely reason is simply timeout. The activity is evidence it has NOT died and is in progress and that only the WAITER side is the one with an actual problem. I think that would have been obvious already by what I listed previously above. It is mostly a matter of eliminating possible causes though different options.

I'm not even bothering to explaing the rest.. 

> I think it is bad software design to define timeouts for processes which may take way longer than expected sometimes - or at least it is bad design to let the software crash with an assertion in this case. I somewhat doubt that Valve did such a thing. Also, while your proposed solution could improve things, it's not a proper fix. In that case, the stall condition must be changed instead, or even better: completely eliminated. Async IO doesn't make things magically faster, neither does better threading. A re-design to use async IO or threading may still be needed to eliminate the stall condition. But that's pure speculation, and may introduce new bugs.

You are badly mistaken if you assume users are happy when software is hanging indefinitely. Timeouts are a basic thing in telling a user "ok, this should have worked by now but I'm giving up": consider a mounted network share where the destination is unavailable. Instead of blocking indefinitely user is given the chance to abort ("I know it isn't there so don't try again") or to continue ("server just booted, up it should work now").

You are ludicrous is claiming they are symptom of "bad" or "good" design: there are many very good reasons to use timeouts. For situations which might take potentially forever better approach is to simply handle it in background and let user continue with whatever is possible then.

There is no reason to continue arguing about this any longer since the problem has been fixed.
