### ISSUE TITLE
Steam client crashes on startup

### ISSUE THREAD

**Issue by travis-bradbury** [ValveSoftware/steam-for-linux#7814]
#### Your system information

* Steam client version (build number or date): 1.0.0.70
* Distribution (e.g. Ubuntu): Debian 10.9 (Buster)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam crashes shortly after startup. A window appears, saying "verifying installation", and it goes away after less than a second.

When running `/usr/bin/steam` in the terminal, messages appear saying modules `gail` and `atk-bridge` failed to load. Later, a segmentation fault is reported. Here's the full output: https://gist.github.com/travis-bradbury/93cffde6442d0ed2b7539bfcc9206386.

The first part that seems suspicious to me is this:

```
[2021-05-25 17:36:09] Verification complete
        Loaded SDL version 2.0.15-6501165
        Gtk-Message: 17:36:09.226: Failed to load module "gail"
        Gtk-Message: 17:36:09.226: Failed to load module "atk-bridge"  
        Steam: An X Error occurred
```

Things worked fine yesterday. I'm not sure if my steam client version was the same at the time. Some X packages updated yesterday. I don't know if that's related to the problem or not.

```
Start-Date: 2021-05-24  06:11:51
Commandline: /usr/bin/unattended-upgrade
Upgrade: libx11-xcb-dev:i386 (2:1.6.7-1+deb10u1, 2:1.6.7-1+deb10u2), libx11-xcb1:amd64 (2:1.6.7-1+deb10u1, 2:1.6.7-1+deb10u2), libx11-xcb1:i386 (2:1.6.7-1+deb10u1, 2:1.6.7-1+deb10u2)
End-Date: 2021-05-24  06:11:53

Start-Date: 2021-05-24  06:11:54
Commandline: /usr/bin/unattended-upgrade
Upgrade: libx11-data:amd64 (2:1.6.7-1+deb10u1, 2:1.6.7-1+deb10u2)
End-Date: 2021-05-24  06:11:56
```

I ran `steam --reset`, and steam worked, until I enabled the Steam Play option to allow starting any games using Steam Play. That prompted me to restart Steam, which I accepted, and I was back to the original problem.

I'm not sure if this is related to #7810. In that one, another user had `libGL error: failed to load driver: swrast`. Regardless, I tried to follow the advice there, as best it seemed to fit my situation.
- Downloaded the latest driver from NVIDIA (460.80).
- installed the driver over top of the previous version (460.44).
- During the installation wizard
    - Install DKMS modules.
    - Set up X configuration files.
    - Enable 32-bit support.

#### Steps for reproducing this issue:

1. Run `/usr/bin/steam`.

**Comment by kisak-valve** [comment]
Hello @travis-bradbury, this issue is already being tracked at #7813.

From the log,
```
Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing
Steam: An X Error occurred
```
and `src/public/tier1/utlmemory.h (176) : Assertion Failed: 0` are a strong indicator that you're seeing the same issue as that issue report.

Closing as a duplicate.
