### ISSUE TITLE
[Feature Request] Feature to clear proton compatdata for uninstalled apps

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/steam-for-linux#7815]
Was cleaning disk space when I noticed that I had leftover compat datas from removed games in steam/steamapps/compatdata. Medium size of these is around 500Mb, some of them even took 20Gbs, and there are plenty of them.

Would like to see an option for Steam client to purge chosen data of willing app, including for removed apps, instead of manually removing them. Optional as they might contain save data for games without Steam Cloud or have some prefix workaround applied to make them work.

**Comment by kisak-valve** [comment]
Hello @xDShot, this issue report is close enough to #7418 that they should be discussed together, so I've transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/7418#issuecomment-848679008.

Closing as a duplicate.
