### ISSUE TITLE
Restarting steam after update starts any game that was called when starting steam

### ISSUE THREAD

**Issue by DAMO238** [ValveSoftware/steam-for-linux#7821]
#### Your system information

* Steam client version (build number or date): May 19 2021 at 01:54:04
* Distribution (e.g. Ubuntu): Arch (up to date)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If you start steam, indicating the game that you want to play. For example, I used Lutris to start steam to play hyper light drifter, which ran the command `steam steam://$APPID/` with relevant wrappers and environment variables for my system. After I was done playing, I turned the game off but left steam running in the background overnight. When I woke up, there was a message letting me know there was an update. I selected 'update', which did update, however, it restarted with the exact same command, thus starting up hyper light drifter again. This was unexpected, as I expected it to simply reopen steam not start any game, as that was the state it was previously in. 

#### Steps for reproducing this issue:

1. Start steam with a game as an argument so you immediately get into the game without having to click on anything in steam.
2. Close the game, but not steam.
3. Wait for an update and click restart now.

**Comment by kisak-valve** [comment]
Hello @DAMO238, this issue is already being tracked at #1414. Closing as a duplicate.
