### ISSUE TITLE
Error: You are missing the library(s): libc.so.6 

### ISSUE THREAD

**Issue by DeveloperWOW64** [ValveSoftware/steam-for-linux#7824]
#### Your system information

* Steam client version (build number or date): Does not open so I can't give the exact, but I downloaded the deb package on the 31/05/21 (dd/mm/yy)
* Distribution (e.g. Ubuntu): ChromeOS 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No]  Yes (none given)
* Computer architecture (e.g. ARM): ARM64

#### Please describe your issue in as much detail as possible:
I installed Steam with the guide on [Chrome Unboxed.](https://chromeunboxed.com/how-to-install-steam-on-a-chromebook/)
I then started it and it gave me the error:
`You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6`
I then used the command `sudo apt install libc6-i386`, which is _supposed_ to install libc.so.6, but steam still gives me the error

#### Steps for reproducing this issue:

1. install steam on chromeos using the Chrome unboxed tutorial mentioned above
2. open steam from the launcher

**Comment by kisak-valve** [comment]
Hello @DeveloperWOW64, the guide you found is for x86-based Chromebooks. Steam does not work on an ARM-based CPUs and this is being tracked at #4061.

Closing in favor of the older issue report.
