### ISSUE TITLE
Steam Controller Wayland invisible cursor

### ISSUE THREAD

**Issue by cewbdex** [ValveSoftware/steam-for-linux#7829]
#### Your system information

* Steam client version (build number or date): 19. May 2021 
* Distribution (e.g. Ubuntu): Fedora 34
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

With launched Steam, the cursor of Steam Controller is not visible when using Wayland session (but could be used, if you guess where is it). With Xorg or Steam off the mouse works properly.

#### Steps for reproducing this issue:

1.  Connect Steam Controller
2. Try to use it as a mouse

**Comment by kisak-valve** [comment]
Hello @cewbdex, this issue was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/4738#issuecomment-271682124 and most likely related to https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/431.
