### ISSUE TITLE
http code 0 - Steam needs to be online to update.

### ISSUE THREAD

**Issue by Sodium-Aluminate** [ValveSoftware/steam-for-linux#7831]
#### Your system information

* Steam client version (build number or date): 
deb version: `Version: 1:1.0.0.70`
steam version: `[2021-06-05 15:01:50] Startup - updater built Mar 23 2021 20:11:00`
* Distribution (e.g. Ubuntu):  `Ubuntu 20.04`
* Opted into Steam client beta?: `No`
* Have you checked for system updates?: `Yes`

#### Please describe your issue in as much detail as possible:

I've add all of ips to `/etc/hosts`.
I've checked the package steam needed.
i've alreade rm -rf `$HOME/.steam*` and `$HOME/.local/share/Steam` to avoid old data do something wrong.
I've both tried [the deb from website](https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb) or apt install steam but either of them can work.  
```
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/sodiumaluminate/.local/share/Steam/ubuntu12_32/steam
[2021-06-05 15:13:06] Startup - updater built Mar 23 2021 20:11:00
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
[2021-06-05 15:13:06] Loading cached metrics from disk (/home/sodiumaluminate/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-05 15:13:06] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2021-06-05 15:13:06] Using the following download hosts for Public, Realm steamglobal
[2021-06-05 15:13:06] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1.0)
[2021-06-05 15:13:06] Verifying installation...
[2021-06-05 15:13:06] Unable to read and verify install manifest /home/sodiumaluminate/.local/share/Steam/package/steam_client_ubuntu12.installed
[2021-06-05 15:13:06] Verification complete
[2021-06-05 15:13:06] Downloading Update...
[2021-06-05 15:13:06] Checking for available update...
[2021-06-05 15:13:06] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
[2021-06-05 15:13:06] Download failed: http error 0 (media.steampowered.com/client/steam_client_ubuntu12)
[2021-06-05 15:13:06] DownloadManifest - exhausted list of download hosts
[2021-06-05 15:13:06] failed to load manifest from buffer.
[2021-06-05 15:13:06] Failed to load manifest
[2021-06-05 15:13:06] Error: Download failed: http error 0
[2021-06-05 15:13:06] Saving metrics to disk (/home/sodiumaluminate/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-05 15:13:06] Error: Steam needs to be online to update.	 Please confirm your network connection and try again.
[2021-06-05 15:13:09] Shutdown
src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57dd0340/0x0xee2ffb'
src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57dd0340/0x0xee2ffb'
Installing breakpad exception handler for appid(steam)/version(1.0)
crash_20210605151310_7.dmp[26187]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210605151310_7.dmp
crash_20210605151310_7.dmp[26187]: Finished uploading minidump (out-of-process): success = no
crash_20210605151310_7.dmp[26187]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20210605151310_7.dmp[26187]: file ''/tmp/dumps/crash_20210605151310_7.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

```

#### Steps for reproducing this issue:

(i just install steam and run `steam` in gnome-terminal)

**Comment by Sodium-Aluminate** [comment]
i also tried `ln -s` another `libcurl.so` to `/usr/lib`, but it said:
```
crash_20210605152531_7.dmp[27192]: file ''/tmp/dumps/crash_20210605152531_7.dmp'', upload no: ''libcurl.so: wrong ELF class: ELFCLASS64
```

I wonder where i can get a libcurl.so

**Comment by Sodium-Aluminate** [comment]
here is my apt can install(ubuntu offical source):
```
sodiumaluminate@AlsPad:~$ LANGUAGE=en_US apt list libcurl*
Listing... Done
libcurl-ocaml-dev/focal 0.9.0-2build1 amd64
libcurl-ocaml/focal 0.9.0-2build1 amd64
libcurl3-gnutls/focal-updates,focal-security,now 7.68.0-1ubuntu2.5 amd64 [installed,automatic]
libcurl3-gnutls/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurl3-nss/focal-updates,focal-security,now 7.68.0-1ubuntu2.5 amd64 [installed]
libcurl3-nss/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurl4-doc/focal-updates,focal-updates,focal-security,focal-security 7.68.0-1ubuntu2.5 all
libcurl4-gnutls-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 amd64
libcurl4-gnutls-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurl4-nss-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 amd64
libcurl4-nss-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurl4-openssl-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 amd64
libcurl4-openssl-dev/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurl4/focal-updates,focal-security,now 7.68.0-1ubuntu2.5 amd64 [installed,automatic]
libcurl4/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
libcurlpp-dev/focal 0.8.1-2build2 amd64
libcurlpp0/focal 0.8.1-2build2 amd64
```

**Comment by Sodium-Aluminate** [comment]
i installed `libcurl4:i386` but it still can't connect.
```
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/sodiumaluminate/.local/share/Steam/ubuntu12_32/steam
[2021-06-05 15:40:30] Startup - updater built Mar 23 2021 20:11:00
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
[2021-06-05 15:40:30] Loading cached metrics from disk (/home/sodiumaluminate/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-05 15:40:30] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2021-06-05 15:40:30] Using the following download hosts for Public, Realm steamglobal
[2021-06-05 15:40:30] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1.0)
[2021-06-05 15:40:30] Verifying installation...
[2021-06-05 15:40:30] Unable to read and verify install manifest /home/sodiumaluminate/.local/share/Steam/package/steam_client_ubuntu12.installed
[2021-06-05 15:40:30] Verification complete
[2021-06-05 15:40:30] Downloading Update...
[2021-06-05 15:40:30] Checking for available update...
[2021-06-05 15:40:30] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
Installing breakpad exception handler for appid(steam)/version(1.0)
[2021-06-05 15:40:30] Download failed: http error 0 (media.steampowered.com/client/steam_client_ubuntu12)
[2021-06-05 15:40:30] DownloadManifest - exhausted list of download hosts
[2021-06-05 15:40:30] failed to load manifest from buffer.
[2021-06-05 15:40:30] Failed to load manifest
[2021-06-05 15:40:30] Error: Download failed: http error 0
[2021-06-05 15:40:30] Saving metrics to disk (/home/sodiumaluminate/.local/share/Steam/package/steam_client_metrics.bin)
[2021-06-05 15:40:30] Error: Steam needs to be online to update.	 Please confirm your network connection and try again.
[2021-06-05 15:40:32] Shutdown
src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56d65340/0x0xee32db'
src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56d65340/0x0xee32db'
Installing breakpad exception handler for appid(steam)/version(1.0)
crash_20210605154033_7.dmp[28553]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210605154033_7.dmp
crash_20210605154033_7.dmp[28553]: Finished uploading minidump (out-of-process): success = yes
crash_20210605154033_7.dmp[28553]: response: CrashID=bp-3ba46c67-1a43-46ea-b3b9-5460e2210605
crash_20210605154033_7.dmp[28553]: file ''/tmp/dumps/crash_20210605154033_7.dmp'', upload yes: ''CrashID=bp-3ba46c67-1a43-46ea-b3b9-5460e2210605''
```

**Comment by kisak-valve** [comment]
Hello @Sodium-Aluminate, can you give #7667 a read and see if you're seeing the same issue as that issue report? In particular, does https://github.com/ValveSoftware/steam-for-linux/issues/7667#issuecomment-834005011 workaround the issue you're seeing?

**Comment by Sodium-Aluminate** [comment]
> Hello @Sodium-Aluminate, can you give #7667 a read and see if you're seeing the same issue as that issue report? In particular, does [#7667 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/7667#issuecomment-834005011) workaround the issue you're seeing?

Thanks,but steam still not working after installed `nscd`.

**Comment by Sodium-Aluminate** [comment]
@kisak-valve btw I can resolve the `media.steampowered.com` by dig, firefox or curl.

**Comment by kisak-valve** [comment]
Thanks for testing, maybe try checking if `libnss-resolve:i386` is installed, and if adding that works around the issue (from #4661).

**Comment by Sodium-Aluminate** [comment]
> Thanks for testing, maybe try checking if `libnss-resolve:i386` is installed, and if adding that works around the issue (from #4661).

already installed.

**Comment by Sodium-Aluminate** [comment]
> Hello, I also have this issue on OS X with the same output when I run `/Applications/Steam.app/Contents/MacOS/steam_osx`:
> 
> ```
> [2022-04-11 21:22:58] Startup - updater built Mar 15 2022 17:15:24
> [2022-04-11 21:22:59] Startup - updater built Mar 15 2022 17:15:24
> [2022-04-11 21:22:59] Loading cached metrics from disk (/Users/alex/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/package/steam_client_metrics.bin)
> [2022-04-11 21:22:59] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
> [2022-04-11 21:22:59] Using the following download hosts for Public, Realm steamglobal
> [2022-04-11 21:22:59] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
> [2022-04-11 21:22:59] Verifying installation...
> [2022-04-11 21:22:59] Unable to read and verify install manifest /Users/alex/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/package/steam_client_signed_osx.installed
> [2022-04-11 21:22:59] Verification complete
> [2022-04-11 21:22:59] Downloading update...
> [2022-04-11 21:22:59] Checking for available updates...
> [2022-04-11 21:22:59] Downloading manifest: http://media.steampowered.com/client/steam_client_osx
> [2022-04-11 21:24:06] Download failed: http error 0 (media.steampowered.com/client/steam_client_osx)
> [2022-04-11 21:24:06] DownloadManifest - exhausted list of download hosts
> [2022-04-11 21:24:06] failed to load manifest from buffer.
> [2022-04-11 21:24:06] Failed to load manifest
> [2022-04-11 21:24:06] Error: Download failed: http error 0
> [2022-04-11 21:24:06] Saving metrics to disk (/Users/alex/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/package/steam_client_metrics.bin)
> [2022-04-11 21:24:06] Error: Steam needs to be online to update. Please confirm your network connection and try again.
> [2022-04-11 21:30:49] Shutdown
> src/tier0/threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x7fbed9705510/0x0x70'
> src/tier0/threadtools.cpp (3628) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x7fbed9705510/0x0x70'
> ```
> 
> Also, when I run `/Applications/Steam.app/Contents/MacOS/steam.sh`, I have the following (followed with an apple crash report):
> 
> ```
> [2022-04-11 21:48:14] Startup - updater built Mar 15 2022 17:15:24
> zsh: killed     /Applications/Steam.app/Contents/MacOS/steam.sh
> ```

(offtopic) I'm no idea about this bug, but I use arch now. Now it works perfectly.

**Comment by kisak-valve** [comment]
Hello @Sodium-Aluminate, glad to hear it started behaving for you. Unfortunately, that also means there's no longer a test case for the originally reported issue and a Steam developer can't really ponder this further.

Hello @drpiou, we're focusing on the Steam for Linux client in this issue tracker. Please report issues with the Steam for Mac client to [Steam Support](http://help.steampowered.com/).
