### ISSUE TITLE
Steam crashes with out of memory exception

### ISSUE THREAD

**Issue by TAK-YON** [ValveSoftware/steam-for-linux#7836]
#### Your system information

* Steam client version (build number or date):  1621394999
* Distribution: 64bit NixOS 21.11 Preview 
* Opted into Steam client beta?: No, switching to beta has an issue with libpipewire.so
* Have you checked for system updates?:  Yes

When starting steam after a few minutes to an hour it crashes, with or without user interaction. 
Started around the time that I was downloading Need for speed: Hot Pursuit remastered, but has continued after uninstalling.

Making a [logfile](https://gist.github.com/TAK-YON/33eccfc4a2be60de3a3144bdefe6af9e) shows that it tries to allocate 200MB of something, said it's out of memory and crashes. there is more than 14GB of memory available on the system

#### Steps for reproducing this issue:

1. Launch steam
2. Wait 10-60 minutes

**Comment by kisak-valve** [comment]
Hello @TAK-YON, can you give #7280 a read and check if your symptoms match that issue report?

**Comment by TAK-YON** [comment]
> Hello @TAK-YON, can you give #7280 a read and check if your symptoms match that issue report?

Yes this seems to be the same error

**Comment by kisak-valve** [comment]
Thanks for checking. Feel free to add your experience to the older issue report.

Closing as a duplicate.
