### ISSUE TITLE
Pressing Alt + F4 closes the entire steam, not the current window

### ISSUE THREAD

**Issue by KotoWhiskas** [ValveSoftware/steam-for-linux#7837]
#### Your system information

* Steam client version (build number or date):  May 19 2021 at 01:54:04
* Distribution (e.g. Ubuntu):  Kubuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
On windows, if I press this alt + f4, then the current window (for example, featured or chat) is closing. In Kubuntu, this shortcut closes the entire steam and it disappears from the tray. This happens in both ubutnu and other distributions (kubuntu, xubuntu etc) when system sends close signal. 
#### Steps for reproducing this issue:

1. Open Steam
2. Press Alt + F4

**Comment by kisak-valve** [comment]
Hello @KotoWhiskas, this issue is already being tracked at #3056. Closing as a duplicate.
