### ISSUE TITLE
wrong dialog when saving a picture

### ISSUE THREAD

**Issue by WhiteAW** [ValveSoftware/steam-for-linux#7840]
My system:
Kubuntu 20.10 64-bit
Kernel-Version 5.14.2

Steam-Client Jun 4 2021 19:34:24
Steam-API v020
SteamPaketVersion: 1622844577
Steam-Beta Yes
Updates checked Yes

Problem:
If i want to save/download a picture/screenshot from any game in the library site. By clicking right click on the Picture and then on "Save screenhot as..." there is an open-dialog and not an save-dialog

Steps for reproducing this issue:

1. open the library
2. select any game with "communty content"
3. right click on any picture
4. click on "Save screenshot as..."
-there is the wrong dialog-

**Comment by kisak-valve** [comment]
Hello @WhiteAW, this issue is already being tracked at #6698. Closing as a duplicate.
