### ISSUE TITLE
Steam native-runtime stopped working

### ISSUE THREAD

**Issue by Storm-Engineer** [ValveSoftware/steam-for-linux#7841]
#### Your system information

* Steam client version (build number or date): most recent
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Probably yes, but not sure.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Last week I was using naive-runtime when it prompted me an update is available. I declined as I was troubleshooting a game. Half an hour later, it just self-updated anyway, against my wish... and after that, it can't connect to my account anymore. It just hangs on the "Connecting to Steam account: [username]" window indefinitely.

This affects only native-runtime, the regular steam-runtime works properly.

#### Steps for reproducing this issue:
1. Start steam-native, and log in if needed.

Terminal output:
https://gist.github.com/Storm-Engineer/464c21760828c78bd903748d46ddd4f5

This bug sounds exactly like this one from several years ago:
https://github.com/ValveSoftware/steam-for-linux/issues/5014

There is a thread on the Arch forums as well as an Arch bug ticket about this current issue, check them for more information:
https://bbs.archlinux.org/viewtopic.php?pid=1976804
https://bugs.archlinux.org/task/71092

**Comment by kisak-valve** [comment]
Hello @Storm-Engineer, disabling the Steam runtime is not supported. This issue will need to be evaluated and resolved by the package maintainer(s) that helped you disable the runtime.

**Comment by cybik** [comment]
@DragoonAethis installing libnm0 on Pop_OS did nothing for me.

**Comment by DragoonAethis** [comment]
```bash
cd .steam/steam/ubuntu12_32
file * | grep ELF | cut -d: -f1 | LD_LIBRARY_PATH=. xargs ldd | grep 'not found' | sort | uniq```

That's also from the bug tracker above - this should list any missing libraries. Are you sure everything needed is installed?

**Comment by cybik** [comment]
* I installed libnm0:i386 and tried to start it again - no dice
* On a notion, I reverted from pipewire self-installed-from-debian to Hirsute Upstream and rebooted... and now it works? Wut

**Comment by Noah-Kennedy** [comment]
@DragoonAethis installing the PKGBUILD for lib32-libnm that you linked in the Arch bug tracker thread does solve the problem on my Arch install, so I agree that this does seem to be the fix for Arch.
