### ISSUE TITLE
Segmentation fault since last update

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/steam-for-linux#7844]
#### Your system information

* Steam client version (build number or date): Not sure where to find that info
* Distribution (e.g. Ubuntu): Ubuntu 21.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam crashes on startup.

Log: https://gist.github.com/DomiStyle/f0bc81c962f895dfd76c66971481ce33

#### Steps for reproducing this issue:

1. Start Steam from desktop or CLI
2. Updater shows shortly and then disappears

**Comment by fblanke** [comment]
I get the same behavior and error. Worked fine yesterday

**Comment by DomiStyle** [comment]
I was able to revive Steam by running ``steam --reset``.
Not ideal since it resets all shader caches and Proton settings but at least Steam works again (for now).

**Comment by DomiStyle** [comment]
Steam goes right back to crashing after it finished downloading all shader caches.
