### ISSUE TITLE
Turkish client-Text overlapping at "Downloads" section

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#7846]
#### Your system information

* Steam client version (build number or date): June 7 2021
* Distribution (e.g. Ubuntu): Linux Mint 20
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
As described in the title and also noted [here](https://github.com/ValveSoftware/steam-for-linux/issues/4936#issuecomment-857067219) text overlaps at "Download Restrictions/Limits" part of "Downloads" section. Or it simply might be a misplacement of that tick box about bandwith limiting option.

![Ekran Görüntüsü - 2021-06-08 22-49-32](https://user-images.githubusercontent.com/24878978/121262313-95f1f100-c8bc-11eb-8e3d-1a39eed3f93b.png)

#### Steps for reproducing this issue:

1. Steam client set to Turkish as client language
2. Go to Downloads section
3. Look at marked part ( screenshot provided above)

**Comment by Mormacill** [comment]
Also occuring on german interface, just heavier.


![Bildschirmfoto vom 2021-09-12 19-17-34](https://user-images.githubusercontent.com/31103546/132996782-6789a968-5e2d-47e6-a3dd-993f62398d91.png)
