### ISSUE TITLE
Native Steam broke since last stable update (7 Jun)

### ISSUE THREAD

**Issue by StarterX4** [ValveSoftware/steam-for-linux#7848]
#### Your system information

* Steam client version (build number or date): 8 Jun (beta for now)
* Distribution (e.g. Ubuntu): Manjaro (testing)
* Opted into Steam client beta?: [Yes] 8 Jun update didn't change anything
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

I'm using Steam without Steam Runtime for years. An update released on 7 Jun stopped Steam from running. 
Before that update, Steam was working fine, and i didn't change anything to my OS at the time of update.
Anyway, Steam is working fine _with_ steam runtime.

First, there's an error in terminal:
`Steam: An X Error occurred
X Error of failed request:  BadAtom (invalid Atom parameter)
Major opcode of failed request:  20 (X_GetProperty)
Atom id in failed request:  0x0
Serial number of failed request:  12
xerror_handler: X failed, continuing`

Then there's a bunch of errors:
`src/clientdll/appdatacache.cpp (2679) : Assertion Failed: !bSharedKVSymbols`

And Steam is stuck on "Connecting Steam account" monit.

I tried to debug Steam through `DEBUGGER=gdb steam`, and here's the Gist with GDB log: https://gist.github.com/StarterX4/0187d369961189ea8a0d98620bb2a932

I also debugged Steam with `STEAM_RUNTIME=1` (the first error is also there, but at least Steam runs fine): https://gist.github.com/StarterX4/4312d91a3d9af9ca7c34382d4a44812d

#### Steps for reproducing this issue:

1. STEAM_RUNTIME=0 steam

**Comment by kisak-valve** [comment]
Hello @StarterX4, running Steam with the Steam runtime disabled is unsupported and needs to be evaluated and resolved by yourself or the package maintainers who helped disable the runtime.

Arch bug report: https://bugs.archlinux.org/task/71092

**Comment by StarterX4** [comment]
Installing lib32-libnm attached there solved this for me too. Thanks.
