### ISSUE TITLE
Ubuntu 18.04: After update 8 Jun Steam crashes after start

### ISSUE THREAD

**Issue by liminspace** [ValveSoftware/steam-for-linux#7855]
* Steam client version (build number or date): Jun 8 2021, at 22:23:41
* Distribution (e.g. Ubuntu): Ubuntu 18.04.5
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

log: https://gist.github.com/liminspace/71cfab0db30ac11ea46de6c06904b39a

Steam crashes after start. Before update 8 Jun it worked very well.

If I run `steam --reset`, it works. But when I close Steam and run it again it crashes again.

**Comment by kisak-valve** [comment]
Hello @liminspace, I take it you checked the box to remember your password and trimmed the auto-login detail out of your log snippet?

Your log has `src/public/tier1/utlmemory.h (176) : Assertion Failed: 0` which is a decent hint that you've encountered the issue being tracked at #7813. Closing as a duplicate.
