### ISSUE TITLE
TF2 should not minimize when it loses focus.

### ISSUE THREAD

**Issue by RobertZenz** [ValveSoftware/steam-for-linux#786]
Team Fortress 2 is at the moment minimizing everytime it loses focus. That is actually not a very good behavior when it comes to multi-monitor environments. I want to keep TF2 open on my main monitor while I do something different on my second one (like chatting with someone).

**Comment by salt86** [comment]
Can anyone translate into layman's terms? I would like my tf2 to not minimize while I'm waiting for matchmaking.

**Comment by kisak-valve** [comment]
Hello @salt86, one way is to add `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 %command%` to TF2's launch options in steam. Another is to run steam from a launch script that has 
```
#!/bin/bash
export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
steam
```
or set the env variable in one of the various environment config files that get used by your DE.
