### ISSUE TITLE
steam consistently crashing during steam first launch

### ISSUE THREAD

**Issue by memory-thrasher** [ValveSoftware/steam-for-linux#7860]
#### system information

* Steam client version (build number or date): Jun 8 2021 22:23:36
* Distribution (e.g. Ubuntu): xubuntu 21.04 hirsute hippo (others have reported on 20.04 focal)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### hardware

* rhyzen 3950x (w/ evga water cooler)
* gigabyte aorus x570 pro wifi
* ram: 4x 8gb ddr4 4400 patriot viper steel running at 2880
* (nothing is overclocked, yet)
* evga nvidia 1080 (primary display, 4k @60hz)
* msi rx 570 (secondary displays, 2x 4k @30hz)
* mushkin enhanced pilot-e 500gb m.2 nvme (os)
* wd black sn850 2tb m.2 nvme (data)
* old spinning hdd (backups only)
* game controller, headset, other likely irrelevant accessories

#### Please describe your issue in as much detail as possible:

Simply put, steam crashes in an X exception handler which tries to access (LEA) a negative memory address (32-bit starting with 0x8). This happens after steam verifies itself, before the login prompt. It happened every single time I tried it, up until I reinstalled (an earlier version of) the os.

I [pinged reddit](https://www.reddit.com/r/linux_gaming/comments/nxzhkn/steam_crashing_on_launch_on_xubuntu_2104/), and found others having similar issues on other ubuntu flavors but no solution. I experienced another X-related issue and downgraded to 20.04 lts "focal" which fixed the problem for me. I have been unable to reproduce the issue in focal, though other redditors claim to be experiencing the issue. I have also been unable to reproduce it on a hirsute hippo vm.

I believe this is the same issue reported in #7859 and #7847, and maybe more, but I have more info available than them at first glance.

dumped exerts (copied from my reddit post, formatting may be better there):
https://gist.github.com/memory-thrasher/a2c6adc42628366e250138654b2f371f

I was [instructed to report this here](https://www.reddit.com/r/linux_gaming/comments/nxzhkn/steam_crashing_on_launch_on_xubuntu_2104/h1nt658/) before I could render my experience to repeatable installation steps or identify conflicting packages.

I am relatively certain there is a hardware/driver component to this, seeing as it works in a vm with the same packages installed. I am currently working on setting up a dual boot that is affected so I can try some package/driver combinations.

#### Steps for reproducing this issue:

1. Launch steam

**Comment by kisak-valve** [comment]
Hello @memory-thrasher, `swrast` is mesa's slower software renderer, and the fact that Steam is trying to use it hints that you're using nVidia's proprietary driver, but don't have the video driver's 32 bit userspace component installed. The nVidia proprietary driver requires that the driver's running kernel module, 32 bit userspace, and 64 bit userspace are installed and have exactly the same version to work properly.

Please check that you have `libnvidia-gl-465:i386` installed with something like `apt policy libnvidia-gl-465:i386` and install it with `sudo apt install libnvidia-gl-465:i386`, then retest.

The issue reports you linked don't look like they're related to the log you've shared.

**Comment by memory-thrasher** [comment]
Thanks @kisak-valve . I will remember that if this issue crops up again. As I stated, I no longer have an affected system at my disposal, so I cannot retest this, though I have linked your comment to the other redditors who have also reported this problem.

**Comment by kisak-valve** [comment]
This is a relatively common pitfall from the way Debian manages driver dependencies, which is inherited by Ubuntu, and the driver packaging is outside the scope of Steam itself. 

There's a feature request for better feedback at #5366 (and possibly others). Closing in favor of the older issue report.

**Comment by memory-thrasher** [comment]
I'm not saying steam should fix the way the drivers are packaged. I am saying steam could check for the existence of the nvidia drivers package and then the existance of the i386 lib, and give a more helpful error message
