### ISSUE TITLE
Age confirmation window remains on display.

### ISSUE THREAD

**Issue by Zagnaut1717** [ValveSoftware/steam-for-linux#7864]
#### Your system information

* Steam client version (build number or date): Built Jun 8 2021
* Distribution (e.g. Ubuntu): Pop! OS 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When viewing my discovery cue a page comes up asking for age verification. I pick my age and instead of the dialogue box disappearing it remains on screen even if I exit Steam. A reboot is required to remove it.
  Oddly, if I control-click an item to open a new window BEFORE I interact with any age pickers I can get rid of this rogue dialogue box by just closing the window. The former Steam window is unaffected

#### Steps for reproducing this issue:

1. Open your discovery queue.
2. When prompted for age verification, click the button and chose your birth-year, etc.
3. The dialogue box remains on the screen even after closing Steam.

**Comment by Zagnaut1717** [comment]
Decided to test this on a laptop running Pop! OS 20.10. Issues was reproducible there as well. The comments left on the Steam community thread I commented on suggested the others encountering this bug also ran Ubuntu derivatives.

**Comment by EulBofo314** [comment]
I confirm this behaviour.
Debian 10.10 here, with NVidia backports drivers and Beta client, to use Proton. When asked for an age verification, the day and year are correct, but when I click on the month menu, it stays on the screen... well, on EACH screen of my multiple desktop environment.
![Screenshot_Steam_20210616](https://user-images.githubusercontent.com/86012483/122254476-7155d480-cecd-11eb-84ea-a0f15ce33dda.png)
The only way to get rid of this menu is to close Steam.

**Comment by thaewrapt** [comment]
I'm seeing this on Arch Linux as well. Both current beta and stable are affected.

**Comment by echaskaris** [comment]
#7825

**Comment by rosewoox** [comment]
I'm also just passing here to confirm this. I'm using Neon 5.22 and the issue also occurs.
![Dropdown Menu](https://user-images.githubusercontent.com/86574420/123559382-5b63d180-d761-11eb-9ef8-7b93cfd4d517.png)

**Comment by kisak-valve** [comment]
Hello, examples of this issue keep showing up in various places. Since #7825 is the first report of the issue, let's use that issue report.

Closing in favor of #7825.

**Comment by G-Pomering** [comment]
I'm experiencing this problem as well, typically when entering the month of my birth into a dropdown list to watch an R-Rated game trailer.  I'm running Manjaro (5.10.68.1 kernel), Plasma 5.22.5 desktop.  Lenovo AMD Ryzen 7 4750U laptop with Integrated Renior graphics.  I've seen this problem for at least the past 6 weeks.  Thanks for looking into it.
