### ISSUE TITLE
Steam Play - Can't install previously installed games without first going into properties to force proton version

### ISSUE THREAD

**Issue by af7567** [ValveSoftware/steam-for-linux#7869]
Tested with Steam client beta Jun 16 2021, and also Steam stable release

I have the global setting "Enable Steam Play for all other titles" enabled.
I can install any Windows only games which I have not installed on this PC before.
Games which have been previously installed and then uninstalled can't be installed again - the install button is greyed out and has the message "available for [Windows logo]" next to it.

To install the games with the greyed out install button I first need to go into the game properties and tick then untick the "Force the use of a specific Steam Play compatibility tool" option.

**Comment by af7567** [comment]
I just did some testing to try and reproduce this with only using the latest steam client, and I found that it is caued by a game being set to use a specific Proton version which has been removed. So I was able to reproduce it by:

Right click Windows game > Properties > Compatibility > Force the use of Proton-GE (for example)
Quit Steam
Delete Proton-GE from ~/.local/share/Steam/compatibilitytools.d
Start steam again and see greyed out Install button

**Comment by kisak-valve** [comment]
Hello @af7567, this issue is already being tracked at #7404. Closing as a duplicate.
