### ISSUE TITLE
Steam does not start after first run

### ISSUE THREAD

**Issue by skroute** [ValveSoftware/steam-for-linux#7870]
#### Your system information

* Steam client version (build number or date): Fri 18 Jun 2021 11:21:58 AM CEST
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* More system information:
  [lscpu.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676049/lscpu.txt)
  [apt.list.installed.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676050/apt.list.installed.txt)
  [lsb-release.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676055/lsb-release.txt)
  [lspci-20210613.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676069/lspci-20210613.txt)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

##### What should happen
Steam client should start UI should show up when started (menu or command line)

##### What did happen
Steam starts properly on first install, but subsequent start attempts fail.

#### Steps for reproducing this issue:

1. Clean prior steam install with: `sudo rm -r .steam .steampath .steampid`
2. Install steam `sudo apt install steam`
2. Connect to steam, UI pops up as expected, games can be installed and run.
3. Close steam
4. Start steam (GUI or CLI), UI does not show up and steam exits.

Attached below system information & steam logs

Steam Logs:
  [steam.clirun.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676064/steam.clirun.txt)
  [shader_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676074/shader_log.txt)
  [connection_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676076/connection_log.txt)
  [systemmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676077/systemmanager.txt)
  [content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676078/content_log.txt)
  [configstore_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676079/configstore_log.txt)
  [cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676080/cef_log.txt)
  [cef_log.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676081/cef_log.previous.txt)
  [bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676082/bootstrap_log.txt)
  [controller.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676083/controller.txt)
  [appinfo_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676084/appinfo_log.txt)
  [timedtrial_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676085/timedtrial_log.txt)
  [compat_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676086/compat_log.txt)
  [workshop_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676087/workshop_log.txt)
  [cloud_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676088/cloud_log.txt)
  [remote_connections.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676089/remote_connections.txt)
  [parental_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6676090/parental_log.txt)

**Comment by kisak-valve** [comment]
Hello @skroute, your issue sounds like #7813, but the distro-modified Steam package is redirecting some of the terminal spew with key hints that would have helped you find that. Were you checking the "Remember password" box while testing?

The Steam client beta should have some fixes might resolve your issue. You can try opting into the beta client with something like `echo "publicbeta" > ~/.steam/steam/package/beta` or reset the Steam client once again and select it from the Beta participation section of Steam's settings. Alternatively, you could give https://github.com/ValveSoftware/steam-for-linux/issues/7813#issuecomment-861475454 a try.

**Comment by Neurone** [comment]
Same error for me (Ubuntu 20.04, fresh install with apt works for the first time, login, save password, everything fine, close client, start client, steam exits without errors after `STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy`).

I tried to disable the network and Steam starts and it works without problem in offline mode, so it seems related to to the automatic login attempt.

I tried the beta client as @kisak-valve suggested and it works like a charm.

**Comment by skroute** [comment]
That's right, it looks like the client is working as intended when the "Remember password" is *not* ticked. Symptoms make it look like a duplicate of #7813 .

Thank you for the workaround and quick turnaround, I'll be using it until the fix make it to stable release.

Kind regards
