### ISSUE TITLE
AMD (VAAPI) Hardware encoding doesn't work

### ISSUE THREAD

**Issue by S1lent-Gh0st** [ValveSoftware/steam-for-linux#7871]
System information

* Steam client version (build number or date): 1623193086
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes 

Steam Remote Play seems to use software encoding (libx264) instead of VAAPI. VAAPI seems to be working since I use it for ffmpeg transcoding.

CPU: Intel Core i7-4790K
RAM: 24GB DDR3
GPU: AMD RX 5700-XT

Steps for reproducing this issue:

1. Client settings: 1080p60fps, 50Mbit/s, Stereo, HW Decoding enabled (working on Samsung TV)
2. Host settings: Everything checked except Nvidia NVFBC, thread count: Automatic
3. PC and TV are both connected by ethernet

vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Mesa Gallium driver 21.1.2 for AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.10.42-1-MANJARO, LLVM 12.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

**Comment by kisak-valve** [comment]
Hello @S1lent-Gh0st, this issue is already being tracked at #4890. Closing as a duplicate.
