### ISSUE TITLE
Crashing reliably with double free error

### ISSUE THREAD

**Issue by bigntallmike** [ValveSoftware/steam-for-linux#7878]
#### Your system information

* Steam client version (build number or date): 1623193086
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Steam wouldn't run so I ran `steam --reset` and then started up, signed in and browsed games for a few minutes (without playing anything) and it suddenly crashed again.
```
[0624/141445.315923:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.ScreenSaver.Inhibit: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[0624/141445.316147:ERROR:power_save_blocker_x11.cc(330)] No response to Inhibit() request!
assert_20210624140357_1.dmp[41942]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210624140357_1.dmp
assert_20210624140357_1.dmp[41942]: Finished uploading minidump (out-of-process): success = yes
assert_20210624140357_1.dmp[41942]: response: CrashID=[stuff]
assert_20210624140357_1.dmp[41942]: file ''/tmp/dumps/assert_20210624140357_1.dmp'', upload yes: ''CrashID=[stuff]''
/home/mike/.local/share/Steam/steam.sh: line 772: 40227 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
```

So I just tried executing `steam` again and got this right away:

```
Proceed to auto login
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
src/public/tier1/utlmemory.h (176) : Assertion Failed: 0
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
Installing breakpad exception handler for appid(steam)/version(1623193086)
assert_20210624141547_20.dmp[42408]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210624141547_20.dmp
src/public/tier1/utlvector.h (1208) : Assertion Failed: count >= 0
src/public/tier1/utlvector.h (1208) : Assertion Failed: count >= 0
double free or corruption (!prev)
assert_20210624141540_1.dmp[42412]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210624141540_1.dmp
assert_20210624141547_20.dmp[42408]: Finished uploading minidump (out-of-process): success = yes
assert_20210624141547_20.dmp[42408]: response: CrashID=[stuff]
assert_20210624141547_20.dmp[42408]: file ''/tmp/dumps/assert_20210624141547_20.dmp'', upload yes: ''CrashID=[stuff]'
assert_20210624141540_1.dmp[42412]: Finished uploading minidump (out-of-process): success = yes
assert_20210624141540_1.dmp[42412]: response: CrashID=[stuff]
assert_20210624141540_1.dmp[42412]: file ''/tmp/dumps/assert_20210624141540_1.dmp'', upload yes: ''CrashID=[stuff]''
/home/mike/.local/share/Steam/steam.sh: line 772: 42298 Aborted                 (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
```

**Comment by kisak-valve** [comment]
Hello @bigntallmike, the second part of your issue sounds like #7813. Were you checking the "Remember password" box while testing?

The Steam client beta should have some fixes that might resolve your issue. You can reset the Steam client again, then opt into Steam's client beta in the settings or try manually opting into the beta client with something like `echo "publicbeta" > ~/.steam/steam/package/beta` or reset the Steam client once again and select it from the Beta participation section of Steam's settings. Alternatively, you could give https://github.com/ValveSoftware/steam-for-linux/issues/7813#issuecomment-861475454 a try.

After that, can you reproduce the first half of your issue with the beta?

**Comment by smcv** [comment]
If you use Big Picture mode, you'll want to install a 32-bit version of `libXi.so.6` before switching to the beta, to work around #7874. I'm not sure how you do that on Fedora; it would be `libxi6:i386` on Debian/Ubuntu or `lib32-libxi` on Arch.

**Comment by bigntallmike** [comment]
> If you use Big Picture mode, you'll want to install a 32-bit version of `libXi.so.6` before switching to the beta, to work around #7874. I'm not sure how you do that on Fedora; it would be `libxi6:i386` on Debian/Ubuntu or `lib32-libxi` on Arch.

I noticed the Big Picture bugs but no, I don't ever use it.

**Comment by bigntallmike** [comment]
> Hello @bigntallmike, the second part of your issue sounds like #7813. Were you checking the "Remember password" box while testing?
I was, yes, and I saw that bug post the other day when I was last dealing with this but didn't see the `as long as I do not have "Remember Password" checkbox checked` bit at the time, and turning off that feature does prevent the crash on a reload.
 
> The Steam client beta should have some fixes that might resolve your issue.
At the moment, so long as the non-beta doesn't crash, I will stay away from the beta because it was the cause of my previous crashing issues a couple months ago.
