### ISSUE TITLE
Date Drop-down Lists from Age Content Warnings Get Permantly Stuck On-screen

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#7879]
#### Your system information

* Steam client version (build number or date): June 8 2021, at 22:23:41
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Attempting to enter age restriction data when age restricted content is viewed causes the drop-down list to permanently get stuck on screen until Steam is fully closed.

This screenshot is it hovering over my desktop:
![Screenshot_20210624_132207](https://user-images.githubusercontent.com/28468662/123313910-7e03a980-d519-11eb-943e-afb0cef5f64e.png)

#### Steps for reproducing this issue:

1. Have content warnings enabled in account settings
2. Go to a game that gives the age restriction warning
3. Attempt to enter the correct data

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue is already being tracked at #7864. Closing as a duplicate.
