### ISSUE TITLE
Every time I run steam he downloads up to 500 MB shader cache for Dota 2 even several times in one day

### ISSUE THREAD

**Issue by nleo** [ValveSoftware/steam-for-linux#7880]
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"

**Comment by nleo** [comment]
I don't wait for download make game run and it's ok. If I wait not matter next time it downloads again

Also I always skip shader optimiztions, couse it repeats too.

Can I just disable it becose I can play anyway.

**Comment by kisak-valve** [comment]
Hello @nleo, you can control Steam's Shader Pre-Caching behavior at `Steam` -> `Settings` -> `Shader Pre-Caching`.

**Comment by nleo** [comment]
Ok, thank you, I'll try this
