### ISSUE TITLE
steam doesn't start after installing metro exodus

### ISSUE THREAD

**Issue by helioloureiro** [ValveSoftware/steam-for-linux#7884]
#### Your system information

* Steam client version (build number or date):  1:1.0.0.70
* Distribution (e.g. Ubuntu):  Ubuntu 20.04
* Opted into Steam client beta?:  Yes
* Have you checked for system updates?:  Yes
* Extra info:  inxi -F
System:    Host: goosfraba Kernel: 5.8.0-60-lowlatency x86_64 bits: 64 Console: tty 0 Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Machine:   Type: Desktop Mobo: ASUSTeK model: M5A97 LE R2.0 v: Rev 1.xx serial: 160984785600599 UEFI: American Megatrends 
           v: 2701 date: 03/24/2016 
CPU:       Topology: 8-Core model: AMD FX-8300 bits: 64 type: MCP L2 cache: 2048 KiB 
           Speed: 1405 MHz min/max: 1400/3300 MHz Core speeds (MHz): 1: 1404 2: 1404 3: 1404 4: 1404 5: 1404 6: 1404 7: 1404 
           8: 1404 
Graphics:  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 460.84 
           Display: server: X.Org 1.20.11 driver: nvidia resolution: 1920x1080~60Hz, 1920x1080~72Hz 
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 460.84 
Audio:     Device-1: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel 
           Device-2: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo 
           Device-3: Generalplus type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Device-4: Kingston type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.8.0-60-lowlatency 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 70:4d:7b:62:87:df 
           IF-ID-1: docker0 state: down mac: 02:42:62:44:bd:39 
           IF-ID-2: virbr0 state: up speed: 10 Mbps duplex: unknown mac: 52:54:00:9d:2c:28 
           IF-ID-3: virbr0-nic state: down mac: 52:54:00:9d:2c:28 
           IF-ID-4: vnet0 state: unknown speed: 10 Mbps duplex: full mac: fe:54:00:53:bb:b0 
           IF-ID-5: vnet1 state: unknown speed: 10 Mbps duplex: full mac: fe:54:00:c4:ca:49 
           IF-ID-6: vnet2 state: unknown speed: 10 Mbps duplex: full mac: fe:54:00:2d:b2:85 
Drives:    Local Storage: total: 5.46 TiB used: 1.68 TiB (30.7%) 
           ID-1: /dev/sda vendor: Toshiba model: HDWE140 size: 3.64 TiB 
           ID-2: /dev/sdb vendor: Seagate model: ST2000DX002-2DV164 size: 1.82 TiB 
Partition: ID-1: / size: 9.99 GiB used: 3.03 GiB (30.3%) fs: xfs dev: /dev/dm-0 
           ID-2: /boot size: 1.91 GiB used: 502.9 MiB (25.8%) fs: ext4 dev: /dev/sda2 
           ID-3: /home size: 499.94 GiB used: 469.79 GiB (94.0%) fs: xfs dev: /dev/dm-11 
           ID-4: /opt size: 1.99 GiB used: 1008.6 MiB (49.5%) fs: xfs dev: /dev/dm-12 
           ID-5: /tmp size: 4.99 GiB used: 42.3 MiB (0.8%) fs: xfs dev: /dev/dm-1 
           ID-6: /usr size: 94.95 GiB used: 40.84 GiB (43.0%) fs: xfs dev: /dev/diskspace/usr 
           ID-7: /var size: 49.99 GiB used: 35.56 GiB (71.1%) fs: xfs dev: /dev/dm-5 
           ID-8: swap-1 size: 15.00 GiB used: 2.0 MiB (0.0%) fs: swap dev: /dev/dm-4 
           ID-9: /opt/steam size: 739.00 GiB used: 599.0 MiB (85.0%) fs: ext4 dev: /dev/dm-10 
Sensors:   System Temperatures: cpu: 28.6 C mobo: N/A gpu: nvidia temp: 47 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:      Processes: 398 Uptime: 28m Memory: 31.27 GiB used: 7.59 GiB (24.3%) Shell: fish inxi: 3.0.38 

#### Please describe your issue in as much detail as possible:
I left it installing Metro Exodus (75 GB) and when came back to check, application just crashed.
I tried to restart, but I just got a black screen.
I updated my system to the latest version running on nvidia-460 firmware and got the same black screen.
I downloaded the deb package and reinstalled, but same result.
Starting by console I can see it gets stalled after these messages:

Installing breakpad exception handler for appid(steam)/version(1624650462)
Compiled against SDL version 2.0.15 and linked against SDL version 2.0.15
COpenGLSurface::BInitialize: Current session is 9
Installing breakpad exception handler for appid(steam)/version(1624650462)
Installing breakpad exception handler for appid(steam)/version(1624650462)
Installing breakpad exception handler for appid(steam)/version(1624650462)
Installing breakpad exception handler for appid(steam)/version(1624650462)
Installing breakpad exception handler for appid(steam)/version(1624650462)
defaultfocus=DummyInput not found within layout file for welcome_nocontroller
defaultfocus=DummyInput not found within layout file for welcome_nocontroller

#### Steps for reproducing this issue:
1. Install Metro Exodus.
2. Just run: /opt/steam/steam.sh

**Comment by kisak-valve** [comment]
Hello @helioloureiro, can you clarify if you're using Steam with the desktop client or Big Picture mode? If it's the latter, then you may have encountered #7874.

Does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 20.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

**Comment by helioloureiro** [comment]
Thanks for the quick response @kisak-valve.  The problem is the same and the solution worked here as well.

Thanks a lot!

**Comment by helioloureiro** [comment]
Duplicated from #7874
