### ISSUE TITLE
Unable to revert back to native Linux port after Proton version was forced for a game

### ISSUE THREAD

**Issue by vimpostor** [ValveSoftware/steam-for-linux#7888]
In #5638 the option was introduced to play the Proton version of a game despite a native Linux version being available. I tried this for Metro 2033 Redux and forced the Proton version. However I noticed that the Proton version had weird FPS stutters, so I want to revert back to the Linux native version. Here is what I tried:

- Uninstall the game
- Uncheck "Force the use of a specific Steam Play compatibility tool"
- Restart the whole system
- Install the game again

#### Expected result
The native version of Metro 2033 Redux should start again.

### Actual result
The Proton version was downloaded again, even though the above checkbox is not checked anymore.
Also starting the game now fails with an error (The executable "metro" could not be found, and sure enough, checking in the game data directory shows that the Proton version was downloaded with "metro.exe" in it and no "metro" executable).

#### Your system information

* Steam client version: Jun 8 2021
* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

How can I download the Linux native version again?

**Comment by kisak-valve** [comment]
Hello @vimpostor, this issue is already being tracked at #7671. Closing as a duplicate.

**Comment by vimpostor** [comment]
Thanks very much for the quick response! Sorry, I searched for duplicate bugs beforehand but somehow must have missed that one.
