### ISSUE TITLE
[Feature Request] Being able to select a custom runner for windows games

### ISSUE THREAD

**Issue by Toadfield** [ValveSoftware/steam-for-linux#7893]
I want to use a custom wine version as the runner for my windows games,the problem is that it isn't officially supported for steam.
So I want that you can add every runner you want so that it opens the game.

**Comment by kisak-valve** [comment]
Hello @Toadfield, Steam allows for you to use locally built and third party builds of Proton which covers this use case. You can modify wine inside your locally built version of Proton.

Separately, #5674 already exists as a feature request to use vanilla wine builds with Steam.

**Comment by Toadfield** [comment]
I run every windows game that is not from steam via [bottles](https://github.com/bottlesdevs/Bottles).
So I also want to run steam games via bottles,cause the bottles prefixes use all my custom settings and the newest dxvk version.
And the other reason is that when I start steam windows games via file manager (for example when I play a mod) then I start it with bottles everytime,so it could conflict if I sometimes start it in the steam proton prefix instead of the bottles prefix.

**Comment by Toadfield** [comment]
And support for custom runners in general would be cool,you could easy set how you want to launch the game.

**Comment by Toadfield** [comment]
This feature would also be useful if I want to open a windows game in a windows vm directly through steam.
