### ISSUE TITLE
[Feature request] The Tux button should behave a little differently when steam play for all other titles is enabled.

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#7896]
* Steam client version (build number or date): Jun 8 2021, at 22:23:41
* Distribution (e.g. Ubuntu): arch linux
* Opted into Steam client beta?: [Yes/No]no 
* Have you checked for system updates?: [Yes/No]no

#### Please describe your issue in as much detail as possible:
Imagine the following scenarios:
1. User wants to see all games in his library. He click the enabled tux button, which disables showing Linux titles.
2. User wants to see all native games in his library. He has Steam Play enabled for all other titles/supported titles enabled, he wants to have a separate view of all titles, steam play(where applicable) and native titles and doesn't want to disable steam play to view native titles specifically.

**Comment by kisak-valve** [comment]
Hello @kubast2, this issue is already being tracked at #5639. Closing as a duplicate.
