### ISSUE TITLE
[Feature Request] Being able to select winapps as a runner for windows games

### ISSUE THREAD

**Issue by Toadfield** [ValveSoftware/steam-for-linux#7898]
I use winapps to start programs from my linux host in a windows vm,I want to do the same thing with steam windows games.

**Comment by kisak-valve** [comment]
Hello @Toadfield, managing Steam games inside and outside a VM at the same time doesn't sound like a reasonable feature request.

Noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, there is "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." which let us know that the Steam developers intent was not to support cross OS shared Steam library folders, which would be required for this to work.

If you can write a short script to call winapps with the options that are needed to make it work for you, then you can add that script as a non-steam game to Steam's Library.

**Comment by Toadfield** [comment]
Did I get it wrongly how winapps works?
Cause I thought that with winapps I can open windows executables that are sstored on my windows host directly in a vm.

**Comment by kisak-valve** [comment]
The practical application of what you were asking for is for Steam for Linux to manage game updates meant to be in the VM from the host system, and to enable the use of an RDP-connected VM as a Steam Play option. This is fundamentally wrong in multiple ways for games.

You can still figure out how to put the pieces together on your own, but this is a solid no for Steam client integration.
