### ISSUE TITLE
Trying to run steam on Ubuntu 20 spits this error out.

### ISSUE THREAD

**Issue by zzzd11** [ValveSoftware/steam-for-linux#7902]
Running ubuntu 21.04 64-bit on an rtx 3060, i5-10400f 
and getting this issue, im pretty new to linux and ubuntu so ive tried to install all the packages i could find relating to this (latest gpu drivers, all of that) and still get this error. This is my last resort trying to fix this issue, does anyone have any ideas? ive copy and pasted the direct report under here for help.

zlatko@zlatko:~$ steam
Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/zlatko/.steam/debian-installation/ubuntu12_32/steam
[2021-07-05 18:46:57] Startup - updater built Jun  8 2021 22:23:36
Installing breakpad exception handler for appid(steam)/version(1623193086)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  44
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-07-05 18:46:57] Loading cached metrics from disk (/home/zlatko/.steam/debian-installation/package/steam_client_metrics.bin)
[2021-07-05 18:46:57] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2021-07-05 18:46:57] Using the following download hosts for Public, Realm steamglobal
[2021-07-05 18:46:57] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-07-05 18:46:57] Checking for update on startup
[2021-07-05 18:46:57] Checking for available updates...
[2021-07-05 18:46:57] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1623193086)
[2021-07-05 18:46:57] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
[2021-07-05 18:46:57] Nothing to do
[2021-07-05 18:46:57] Verifying installation...
[2021-07-05 18:46:57] Performing checksum verification of executable files
[2021-07-05 18:46:57] Verification complete
Loaded SDL version 2.0.15-6501165
Gtk-Message: 18:46:58.119: Failed to load module "gail"
Gtk-Message: 18:46:58.119: Failed to load module "atk-bridge"

(steam:48573): Gtk-WARNING **: 18:46:58.126: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:48573): Gtk-WARNING **: 18:46:58.127: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  48
xerror_handler: X failed, continuing
assert_20210705184657_1.dmp[48636]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210705184657_1.dmp
/home/zlatko/.steam/debian-installation/steam.sh: line 772: 48573 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
zlatko@zlatko:~$ assert_20210705184657_1.dmp[48636]: Finished uploading minidump (out-of-process): success = yes
assert_20210705184657_1.dmp[48636]: response: CrashID=bp-0e6b5f02-f60d-494d-aabb-17fc52210705
assert_20210705184657_1.dmp[48636]: file ''/tmp/dumps/assert_20210705184657_1.dmp'', upload yes: ''CrashID=bp-0e6b5f02-f60d-494d-aabb-17fc52210705''

**Comment by kisak-valve** [comment]
Hello @zzzd11, `swrast` is mesa's slower software renderer, and the fact that Steam is trying to use it hints that you're using the nVidia proprietary driver, but don't have the driver's 32 bit userspace libraries installed. The nVidia proprietary driver requires the driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are installed and have exactly the same version to work properly.

Please check what video driver series you're using, then install the 32 bit libraries with something like `sudo apt install libnvidia-gl-465:i386` (change 465 to match the driver series you're using).

**Comment by zzzd11** [comment]
Thanks for the quick response, how do i figure out the right series number for 3060?

**Comment by kisak-valve** [comment]
Looks like nVidia added support for their 3060 card in 460.56, so the 460 series or newer should work.

As far as the Steam client is concerned, it doesn't care what driver series you use, just that you have a sane 32 bit and 64 bit OpenGL render path.

**Comment by zzzd11** [comment]
Looks like i have 460.84 installed according to my nvdia settings, what part am i missing?

**Comment by zzzd11** [comment]
^ i mean for the 32bit library, i can't seem to find online how to install specifically that one for ubuntu 21, i only find the original driver installation which if i understand is just 64 which is why this isnt working. How do i find the 32bit ones lol?

**Comment by zzzd11** [comment]
^ i mean for the 32bit library, i can't seem to find online how to install specifically that one for ubuntu 21, i only find the original driver installation which if i understand is just 64 which is why this isnt working. How do i find the 32bit ones lol?

**Comment by kisak-valve** [comment]
You are most likely missing `libnvidia-gl-460:i386`, which you can check with something like `apt policy libnvidia-gl-460 libnvidia-gl-460:i386` and install with `sudo apt install libnvidia-gl-460:i386`.

**Comment by zzzd11** [comment]
Ok i thought i had that installed but it seems to have installed it properly, now when i type in steam in terminal it returns
Running Steam on ubuntu 21.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/zlatko/.steam/debian-installation/ubuntu12_32/steam

opening steam by searching steam normally doesn't do anything.

**Comment by kisak-valve** [comment]
If the running nvidia kernel module does not match the driver's userspace libraries, then OpenGL applications including Steam can hang waiting on the video driver like that. The easiest way to resolve that scenario is to reboot the system.

**Comment by zzzd11** [comment]
Ok sweet, i restarted and it works now, thanks a lot for the help.
