### ISSUE TITLE
Steam No connection/UI issue

### ISSUE THREAD

**Issue by Skyloop2** [ValveSoftware/steam-for-linux#7906]
One night I was playing a game through proton on Steam (not sure which version and now I can't even check) and I minimized the game to do something else then maximized the game and the system hung at a black screen forever and I couldn't do anything. I had no choice but to do a hard restart by turning the power off and on. When I turned on the PC again and logged into Steam an update went though and after entering my user information to log on the icon just stuck in the bottom right system tray and I couldn't do anything but close it. No other options responded to anything like it was open but the UI wasn't appearing. I tried the reset command and this did nothing. I tried deleting various folders suggested by other users like the runtime one's and this didn't work either even after Steam automatically set itself up again. I tried deleting it altogether and reinstalling including the launcher and this did nothing. No unusual spikes in resource consumption.

I only started to get anywhere when I set the user login screen to automatically sign me in where I hang at "connecting to steam account..." and nothing happens. I tried logging in on my other Windows 10 system and no problem doing that. I haven't changed anything about my network or added any new networks either. Can anyone point me in the right direction here, if you ask for logs or something like that please tell me how to get them because I'm not very techy like that. I'm stumped here.

* Distribution (e.g. Ubuntu): Linux Mint 17.3 
* Opted into Steam client beta?: No (no beta anything present in the file system)
* Have you checked for system updates?: Yes

* Steps for reproducing this issue:

1. Log on to Steam with or without the auto sign in checked, one produced nothing altogether and the other hangs at the connecting account screen.

GPU: Nvidia GT 730 2 Gb (384.130 version drivers)
CPU: AMD Athlon X4 860K Black Edition CPU Quad Core FM2+ 3700Mhz

**Comment by kisak-valve** [comment]
Hello @Skyloop2, upstream support for Linux Mint 17.3 has ended. Please retest with a newer distro release.

**Comment by Skyloop2** [comment]
Oh is that all the problem is? I have Unetbootin on here but it doesn't go up to 20, what program should I use to create the bootable USB?

**Comment by NLBen** [comment]
> Oh is that all the problem is? I have Unetbootin on here but it doesn't go up to 20, what program should I use to create the bootable USB?

Takes a bit longer, but you can use the dd command in the terminal, or (if 17.3 has it and wasn't something solely with newer Mint versions) the USB Image Writer within Mint itself (search for USB in the menu and it should be one of the two/three options given)

**Comment by kisak-valve** [comment]
Closing due to lack of upstream support for Linux Mint 17.3.
