### ISSUE TITLE
Steam crashes/closes on GNOME once Shutdown dialog is shown

### ISSUE THREAD

**Issue by Mershl** [ValveSoftware/steam-for-linux#7908]
#### Your system information

* Steam client version: Jun 8 2021
* Distribution: Fedora 34, GNOME, wayland
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Description
The Steam client crashes/closes once GNOME shows the Shutdown dialog (this is at a point where the user has not decided yet). This is independent of whether Steam currently is focused and/or is minimized. If the user chooses not to shutdown the Steam client will be gone by that time.

Steam is the only application known to do this based on the feedback from #gnome.

The Steam client shows the following lines once GNOME presents the Shutdown dialog:
```
Exiting workitem thread
(steam:17870): GLib-GObject-CRITICAL **: 22:32:45.624: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(steam:17870): GLib-GObject-WARNING **: 22:32:45.624: invalid (NULL) pointer instance
(steam:17870): GLib-GObject-CRITICAL **: 22:32:45.624: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(steam:17870): GLib-GObject-CRITICAL **: 22:32:45.624: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2021-07-07 22:32:45] Shutdown
```

Gnome shutdown dialog window:
![image](https://user-images.githubusercontent.com/520251/124825089-79a4ab00-df73-11eb-8b1d-adb68f825d12.png)

#### Steps for reproducing this issue:

1. Have Steam open
2. Open the Shutdown dialog of GNOME either by
2.1 CTRL + ALT + DEL or
2.2 Top right corner click -> Poweroff
3. Press Cancel when asked to confirm the Shutdown
4. Steam will have closed itself

**Comment by Mershl** [comment]
Side note: Only the native version of Steam does that. The flatpak version does not show this behaviour.

**Comment by kisak-valve** [comment]
Hello @Mershl, this issue is already being tracked at #4558. Closing as a duplicate.
