### ISSUE TITLE
"Remember Password" for login credentials results in hard segfault on Ubuntu 20.04 versions.

### ISSUE THREAD

**Issue by teward** [ValveSoftware/steam-for-linux#7910]
#### Your system information

* Steam client version (build number or date): Client Application, build June 8, 2021, 22:23:41; API v020; Package versions: 1623193086
* Distribution (e.g. Ubuntu): Ubuntu 20.04(.*)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When running the Steam client with "Remember Password" set at the login page, subsequent attempts to load steam after closing out the client will result in a hard segmentation fault crash.

This prevents the Steam Client from being usable unless someone is willing to reenter their password at every single launch.

#### Steps for reproducing this issue:

1. Run Steam launcher and client.
2. Enter credentials with "Remember Password" checked.
3. Completely close Steam, attempt to reopen.  Command line output will eventually print out an error similar to `1698310 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"` on the command line due to a hard segfault.

#### Current Workaround to Fix the Crash

The current workaround is to *remove* "Remember Password" - we need this to be fixed or those of us using Steam Guard will have to reenter their credentials and auth codes every time they open the Steam client.  However, this is a direct crash causer if you enabled "Remember Password".

Debug crash dumps are available if needed.

**Comment by kisak-valve** [comment]
Hello @teward, this issue was previously evaluated at #7813 / #7847 and should be fixed in Steam's client beta. Closing in favor of the older issue reports.

**Comment by teward** [comment]
> Hello @teward, this issue was previously evaluated at #7813 / #7847 and should be fixed in Steam's client beta. Closing in favor of the older issue reports.

So, then you have a timeline for when 'beta' becomes 'stable' given that this issue has been ongoing for *months* with hundreds of reports?
