### ISSUE TITLE
Can't install steam on Ubuntu 21.04

### ISSUE THREAD

**Issue by hardikprabhakar** [ValveSoftware/steam-for-linux#7911]
#### Your system information

* Steam client version (build number or date): June 8 2021
* Distribution (e.g. Ubuntu): Xubuntu (Ubuntu 21.04)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After installing the steam_latest.deb with my software manager, when I open Steam, it displays:
```
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
Package libc6:i386 needs to be installed
Package xdg-desktop-portal needs to be installed
Package xdg-desktop-portal-gtk needs to be installed
[sudo] password for [user-name]:
```

after entering the password it displays this error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libdrm-amdgpu1:i386 (>= 2.4.105) but it is not going to be installed
                        Depends: libdrm-intel1:i386 (>= 2.4.38) but it is not going to be installed
                        Depends: libdrm-nouveau2:i386 (>= 2.4.66) but it is not going to be installed
                        Depends: libdrm-radeon1:i386 (>= 2.4.31) but it is not going to be installed
                        Depends: libdrm2:i386 (>= 2.4.75) but it is not going to be installed
 libglx-mesa0:i386 : Depends: libdrm2:i386 (>= 2.4.75) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
and after that, the app crashes after displaying this on the terminal: 
```
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/sylex/.local/share/Steam/ubuntu12_32/steam
/home/sylex/.local/share/Steam/steam.sh: line 770: /home/sylex/.local/share/Steam/ubuntu12_32/steam: No such file or directory
```
#### Steps for reproducing this issue:

1. Install the deb from official Steam download page and install it 
2. Run `steam` on the terminal and enter the password when asked
3. App crashes after displaying `E: Unable to correct problems, you have held broken packages.` error

**Comment by kisak-valve** [comment]
Hello @hardikprabhakar, the Steam client needs the host system to provide 32 bit and 64 bit glibc and a sane OpenGL driver. Your package manager, apt, encountered some package conflict that it couldn't resolve, and it didn't add those requirements to your system.

In general, apt requires that the 32 bit variant and 64 bit variant of a package have exactly the same version, and it doesn't like to downgrade packages ever, so if you added a PPA which updated a dependency of mesa, or some installed package was downgraded in Ubuntu's package repository and your system was not downgraded to match that version.

You could try to run something like `sudo apt install libgl1-mesa-dri libgl1-mesa-dri:i386`, get a similar error as your opening post, then use something like `apt policy libdrm2 libdrm2:i386` to inspect what package versions are available, and try to install the individual mesa dependencies until you find the package version conflict.

**Comment by hardikprabhakar** [comment]
@kisak-valve Thank you! After running `apt policy libdrm2:i386` and then running `sudo apt install libdrm2:i386` i found the package version conflict at the package `libdrm-common`, so i removed it and then reinstalled it, and then tried to install Steam through the apt package manager and it worked !

**Comment by kisak-valve** [comment]
Glad to hear you unblocked the package conflict. Closing as not a Steam issue.
