### ISSUE TITLE
Crash dumps upload

### ISSUE THREAD

**Issue by alkmim** [ValveSoftware/steam-for-linux#7913]
#### Your system information

* Steam client version (build number or date): 1623193086
* Distribution (e.g. Ubuntu): debian
* Opted into Steam client beta?: [Yes/No] I dont now.
* Have you checked for system updates?: [Yes/No] Yes.

#### Please describe your issue in as much detail as possible:
Whenever steam crashes it uploads a dump of my system. The dump contains to many details of my machine. How can I disable those dumps uploads?

```
assert_<date>_1.dmp[3278603]: file ''/tmp/dumps/assert_<date>_1.dmp'', upload yes: ''CrashID=<ID>' 
```

#### Steps for reproducing this issue:

1. Have a crash in steam. See output in command line saying:

```
assert_<date>_1.dmp[3278603]: file ''/tmp/dumps/assert_<date>_1.dmp'', upload yes: ''CrashID=<ID>' 
```

**Comment by kisak-valve** [comment]
Hello @alkmim, disabling Steam's crash reporter is not encouraged, and the option to disable it might be removed in the future. That said, currently, you should be able to run steam with something like `steam -nobreakpad -nominidumps` to get the effect you're looking for.

**Comment by alkmim** [comment]
Thanks for the clarification @kisak-valve !
