### ISSUE TITLE
Skyrim (Legacy, not Special Edition) cache buffering causing Steam crash

### ISSUE THREAD

**Issue by NLBen** [ValveSoftware/steam-for-linux#7915]
#### Your system information

* Steam client version (build number or date):  8 June 2021
* Distribution (e.g. Ubuntu):  Linux Mint 20.2 Xfce
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since yesterday Steam has been behaving... strange... to say the least. I've got Buffer Pre-caching enabled. Normally, this worked out just fine. Since yesterday however (before and after the update to the newest Mint version) whenever Steam gets to checking the content cache of Skyrim, it downloads an 131, 11 and 180 MB sized files. After that, it closes down down/crashes. Didn't happen before, and I've got no clue in the slightest what's causing it.

*Update note* - just to clarify - it checks the cache of other games too. But they cause no problems whatswhoever. Only after the client is done with Skyrim, it goes down.
*Further update note* - I forgot to add that when I pause the cache download it disappears from the queue and doesn't appear again till I restart Steam. It's a persistent problem.
*Yet another update note* - I forgot to also add - yes, I've got mods installed. But they haven't been updated in a long time (the last about a year ago). So it can't be an mod buffer cache error.

Bootstrap_log.txt in ~Steam/steam/logs says the following about it:

> [2021-07-11 10:02:49] Startup - updater built Jun  8 2021 22:23:36
> [2021-07-11 10:02:49] Loading cached metrics from disk (/home/michael/.steam/debian-installation/package/steam_client_metrics.bin)
> [2021-07-11 10:02:49] Using the following download hosts for Public, Realm steamglobal
> [2021-07-11 10:02:49] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
> [2021-07-11 10:02:49] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
> [2021-07-11 10:02:49] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
> [2021-07-11 10:02:49] Checking for update on startup
> [2021-07-11 10:02:49] Checking for available updates...
> [2021-07-11 10:02:49] Downloading manifest: https://cdn.akamai.steamstatic.com/client/steam_client_ubuntu12
> [2021-07-11 10:02:50] Download skipped: /client/steam_client_ubuntu12 version 1623193086, installed version 1623193086, existing pending version 0
> [2021-07-11 10:02:50] Nothing to do
> [2021-07-11 10:02:50] Verifying installation...
> [2021-07-11 10:02:50] Performing checksum verification of executable files
> [2021-07-11 10:02:50] Verification complete
> 

After the verification complete, it crashes, if I read cef_log.txt correctly:

> 
> [0711/100250.722397:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
> [0711/100250.768816:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
> [0711/100250.810861:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
> [0711/100250.837855:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
> [0711/100252.270440:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
> [0711/100252.322375:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
> [0711/100252.346182:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
> [0711/100252.554908:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
> [0711/100252.561541:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer

For verification, from content_log.txt:

> [2021-07-11 10:02:50] Loaded 2 apps from install folder "/home/michael/.steam/debian-installation/steamapps\appmanifest_*.acf".
> [2021-07-11 10:02:50] Loaded 16 apps from install folder "/media/michael/GamesAndMore/SteamLibrary/steamapps\appmanifest_*.acf".
> [2021-07-11 10:02:52] User owns DLC 821940, but not matching content depot 812279
> [2021-07-11 10:02:52] User owns DLC 734830, but not matching content depot 812283
> [2021-07-11 10:02:52] User owns DLC 821950, but not matching content depot 812286
> [2021-07-11 10:02:54] AppID 72850 scheduler update : Priority Last, timeSinceLastPlayed=18119339, appDisableSecondsRemaining=0
> [2021-07-11 10:02:54] AppID 72850 state changed : Fully Installed,Update Queued,
> [2021-07-11 10:02:54] AppID 72850 state changed : Fully Installed,Update Queued,Update Running,
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,Reconfiguring,
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,Preallocating,
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,
> [2021-07-11 10:02:54] AppID 72850 update started : download 0/189731440, store 0/0, reuse 0/0, delta 0/0, stage 0/295525698 
> [2021-07-11 10:02:54] AppID 72850 update changed : Running,Downloading,Staging,
> [2021-07-11 10:02:54] Got 30 download sources and 0 caching proxies via ContentServerDirectoryService::BYieldingGetServersForSteamPipe (CellID 15 / Launcher 0)
> [2021-07-11 10:02:54] Created download interface of type 'SteamCache' (7) to host cache1-ams1.steamcontent.com (cache1-ams1.steamcontent.com)
> [2021-07-11 10:02:54] Created download interface of type 'SteamCache' (7) to host cache4-ams1.steamcontent.com (cache4-ams1.steamcontent.com)
> [2021-07-11 10:02:54] Created download interface of type 'SteamCache' (7) to host cache6-ams1.steamcontent.com (cache6-ams1.steamcontent.com)
> [2021-07-11 10:02:54] Downloading 282 chunks from depot 72850
> [2021-07-11 10:02:54] Created dual-stack http client
> [2021-07-11 10:03:07] Increasing target number of download connections to 4 (rate was 0.000, now 101.318)
> [2021-07-11 10:03:07] Created download interface of type 'SteamCache' (7) to host cache3-ams1.steamcontent.com (cache3-ams1.steamcontent.com)
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,Committing,
> [2021-07-11 10:03:10] AppID 72850 starting commit from "/media/michael/GamesAndMore/SteamLibrary/steamapps/shadercache/72850/swarm/downloads/" to "/media/michael/GamesAndMore/SteamLibrary/steamapps/shadercache/72850/swarm/" : 1 updated, 0 moved, 0 deleted files
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : None
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,Update Queued,
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,
> [2021-07-11 10:03:10] AppID 72850 scheduler finished : removed from schedule (result No Error, state 0xc) 
> [2021-07-11 10:03:10] AppID 72850 scheduler update : Priority Last, timeSinceLastPlayed=18119355, appDisableSecondsRemaining=0
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,Update Queued,
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,Update Queued,Update Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,Reconfiguring,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,Preallocating,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update started : download 0/64, store 0/0, reuse 0/0, delta 0/0, stage 0/16 
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,Downloading,Staging,
> [2021-07-11 10:03:10] Downloading 1 chunks from depot 72850
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,Committing,
> [2021-07-11 10:03:10] AppID 72850 starting commit from "/media/michael/GamesAndMore/SteamLibrary/steamapps/shadercache/72850/swarm/downloads/" to "/media/michael/GamesAndMore/SteamLibrary/steamapps/shadercache/72850/swarm/" : 1 updated, 0 moved, 0 deleted files
> [2021-07-11 10:03:10] AppID 72850 update changed : Running,
> [2021-07-11 10:03:10] AppID 72850 update changed : None
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,Update Queued,
> [2021-07-11 10:03:10] AppID 72850 state changed : Fully Installed,
> [2021-07-11 10:03:10] AppID 72850 scheduler finished : removed from schedule (result No Error, state 0xc) 

#### Steps for reproducing this issue:

1. Have The Elder Scrolls: Skyrim installed
2. Launch Steam while having Pre-Caching enabled
3. Allow the 'download' to continue

**Comment by kisak-valve** [comment]
Hello @NLBen, this reads like #7280. Can you check if that is the same issue that you're seeing? A hint should show up either in the terminal spew while running `steam` from a terminal. Note: The distro-modified Steam package you're using may redirect some of that to a log file similar to `~/.steam/error.log`.

**Comment by NLBen** [comment]
> Hello @NLBen, this reads like #7280. Can you check if that is the same issue that you're seeing? A hint should show up in the terminal spew while running `steam` from a terminal. Note: The distro-modified Steam package you're using may redirect some of that to a log file similar to `~/.steam/error.log`.

Hello @kisak-valve - just compared and checked against my error.log in ~steam/steam. Nope. Not the same. Only similarity is periodic breakpad exception handlers (but even that doesn't seem to be consistent). What is consistent is that compared to my other logs the renderer process keeps on crashing, but that's about anything notable I can see in there.

If you want I can add the error log to here, but I doubt it'll give you any new related info.

**Comment by NLBen** [comment]
@kisak-valve Okay, forgot to check the updated error.log after running steam in the terminal. Following output got added when running steam int he terminal:

> 
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> BuildCompleteAppOverviewChange: 451
> RegisterForAppOverview 1: 20ms
> RegisterForAppOverview 2: 20ms
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> Installing breakpad exception handler for appid(steam)/version(1623193086)
> assert_20210711134308_1.dmp[11462]: Uploading dump (out-of-process)
> /tmp/dumps/assert_20210711134308_1.dmp
> /home/michael/.steam/debian-installation/steam.sh: line 772: 10993 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
> assert_20210711134308_1.dmp[11462]: Finished uploading minidump (out-of-process): success = yes
> assert_20210711134308_1.dmp[11462]: response: CrashID=bp-905c98f5-a17e-45a0-b1bc-5d66e2210711
> assert_20210711134308_1.dmp[11462]: file ''/tmp/dumps/assert_20210711134308_1.dmp'', upload yes: ''CrashID=bp-905c98f5-a17e-45a0-b1bc-5d66e2210711''

**Comment by NLBen** [comment]
@kisak-valve Did something change on the server-end? Because the problems no longer occur.

**Comment by kisak-valve** [comment]
Glad to hear Steam started behaving better for you.

As a moderator on Valve's issue tracker on Github, I unfortunately do not have access to check something like that. We would need to hear from a Steam dev if they wanted to add some insight.
