### ISSUE TITLE
Steam hangs and crashes on download [Mac OSX Catalina]

### ISSUE THREAD

**Issue by Number16BusShelter** [ValveSoftware/steam-for-linux#7918]
#### Your system information

* Steam client version (build number or date): Jun 8 2021, 15:33
* Distribution (e.g. Ubuntu): Mac OSX Catalina (10.15.7)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For several days I try to run Steam application for OSX. Unfortunately I've faced the problem that application freezes and crushes after a while. I've started to look for possible reasons. Everything I could find for similar issues was tried, but none lead to a success.

I found out that the issue was caused by attempt to download update for a game. So, after pausing download, the app stoped crashing. Also I noticed that it takes up CPU.

#### Steps for reproducing this issue:

1. Start Steam application
2. Start game updates
3. Steam hangs and crashes

If you have any idea of solving this issue please let me know!

**Comment by kisak-valve** [comment]
Hello @Number16BusShelter, issues with the Steam for Mac client are not tracked in this Linux (operating system) issue tracker. Please use [Steam Support](https://help.steampowered.com) for support with Steam for Mac.
