### ISSUE TITLE
third party proton (proton-ge) will bork "enable steamplay for all titles"

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#7921]
#### Your system information

* Steam client version (build number or date): Jul 12 2021, at 21:00:39
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When adding a third party Proton version, like Proton-GE for example, into the `~/.steam/root/compatibilitytools.d` directory, the "enable steamplay for all titles" option will never remain ticked after the required restart of steam after changing the option, and remains off. If i remove Proton-GE, i can enable steamplay for all titles again with no problem.

I must mention that other Proton versions are selectable, but when you try and have Proton-GE as the default for steamplay titles, the box will remain unticked and steamplay disabled by default.

This was originally discussed here.

https://github.com/ValveSoftware/Proton/issues/4958

#### Steps for reproducing this issue:

1. add proton-ge to the `~/.steam/root/compatibilitytools.d` directory
2. launch steam and enable steamplay for all titles using proton-ge under settings
3. restart steam and go back to settings to see its still unticked and disabled

**Comment by kisak-valve** [comment]
Hello @shoober420, this issue is already being tracked at #6043. Closing as a duplicate.
