### ISSUE TITLE
Doesnt start past installer 

### ISSUE THREAD

**Issue by FlufferyAutism** [ValveSoftware/steam-for-linux#7925]
#### Your system information

* Steam client version (build number or date): [2021-07-16 21:39:17] Startup - updater built Apr  9 2019 22:48:20
* Distribution ubuntu
* Opted into Steam client beta?: [bo
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
open steam client 
doesnt launch
running via steam command
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/fluffery/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-07-16 21:35:56] Startup - updater built Jul 16 2021 18:04:56
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

tried again after uninstalling and reinstalling
[2021-07-16 21:38:22] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

uninstalled via
sudo apt purge steam* && sudo apt purge steam && sudo rm -rf ~/.steam
still results in
[2021-07-16 21:42:15] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

#### Steps for reproducing this issue:

1. install ubuntu 20.04
2. sudo apt install steam  
3. run/ open

**Comment by FlufferyAutism** [comment]
entire terminal output

fluffery@tuxbox:~$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/fluffery/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-07-16 21:35:15] Startup - updater built Jul 16 2021 18:04:56
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)



^C
fluffery@tuxbox:~$ sudo steam
sudo: steam: command not found
fluffery@tuxbox:~$ steak

Command 'steak' not found, did you mean:

  command 'speak' from deb espeak-ng-espeak (1.50+dfsg-6)

Try: sudo apt install <deb name>

fluffery@tuxbox:~$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/fluffery/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-07-16 21:35:56] Startup - updater built Jul 16 2021 18:04:56
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ 
fluffery@tuxbox:~$ sudo apt purge steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgl1-mesa-glx:i386 libgstreamer-plugins-bad1.0-0 steam-devices
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  steam:i386*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 4,504 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 255837 files and directories currently installed.)
Removing steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
(Reading database ... 255816 files and directories currently installed.)
Purging configuration files for steam:i386 (1:1.0.0.61-2ubuntu3) ...
fluffery@tuxbox:~$ sudo rm -rf ~/.steam
fluffery@tuxbox:~$ sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  libnvidia-gl-390:i386 | libnvidia-gl-435:i386 | libnvidia-gl-440:i386
The following NEW packages will be installed:
  steam:i386
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,451 kB of archives.
After this operation, 4,504 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 steam i386 1:1.0.0.61-2ubuntu3 [1,451 kB]
Fetched 1,451 kB in 0s (4,026 kB/s)  
Preconfiguring packages ...
Selecting previously unselected package steam:i386.
(Reading database ... 255816 files and directories currently installed.)
Preparing to unpack .../steam_1%3a1.0.0.61-2ubuntu3_i386.deb ...
Unpacking steam:i386 (1:1.0.0.61-2ubuntu3) ...
Setting up steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
fluffery@tuxbox:~$ steam
[2021-07-16 21:36:53] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ 
fluffery@tuxbox:~$ steam
cat: '/home/fluffery/.steam/debian-installation/ubuntu12_32/steam-runtime.tar.xz.part*': No such file or directory
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
find: ‘/home/fluffery/.steam/debian-installation/ubuntu12_32/steam-runtime’: No such file or directory
fluffery@tuxbox:~$ sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
steam:i386 is already the newest version (1:1.0.0.61-2ubuntu3).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fluffery@tuxbox:~$ sudo apt install --reinstall steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 1,451 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 steam i386 1:1.0.0.61-2ubuntu3 [1,451 kB]
Fetched 1,451 kB in 2s (769 kB/s)       
Preconfiguring packages ...
(Reading database ... 255837 files and directories currently installed.)
Preparing to unpack .../steam_1%3a1.0.0.61-2ubuntu3_i386.deb ...
Unpacking steam:i386 (1:1.0.0.61-2ubuntu3) over (1:1.0.0.61-2ubuntu3) ...
Setting up steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
fluffery@tuxbox:~$ steam
[2021-07-16 21:38:22] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ 
fluffery@tuxbox:~$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                                        
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                               
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                         
Hit:5 http://ppa.launchpad.net/lutris-team/lutris/ubuntu focal InRelease       
Ign:6 http://repo.vivaldi.com/stable/deb stable InRelease                      
Hit:7 http://repo.vivaldi.com/stable/deb stable Release                             
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.5 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [60.9 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Hit:12 http://ppa.launchpad.net/micahflee/ppa/ubuntu focal InRelease                            
Fetched 202 kB in 1s (373 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/vivaldi.list:3
fluffery@tuxbox:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fluffery@tuxbox:~$ sudo apt install --reinstall steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 1,451 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 steam i386 1:1.0.0.61-2ubuntu3 [1,451 kB]
Fetched 1,451 kB in 0s (4,982 kB/s)  
Preconfiguring packages ...
(Reading database ... 255837 files and directories currently installed.)
Preparing to unpack .../steam_1%3a1.0.0.61-2ubuntu3_i386.deb ...
Unpacking steam:i386 (1:1.0.0.61-2ubuntu3) over (1:1.0.0.61-2ubuntu3) ...
Setting up steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
fluffery@tuxbox:~$ steam
[2021-07-16 21:39:17] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ sudo apt purge steam* && sudo rm -rf ~/.steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'steam-launcher' for glob 'steam*'
Note, selecting 'steamcmd' for glob 'steam*'
Note, selecting 'steam-installer' for glob 'steam*'
Note, selecting 'steam' for glob 'steam*'
Note, selecting 'steam-devices' for glob 'steam*'
Note, selecting 'steam:i386' instead of 'steam'
Note, selecting 'steamcmd:i386' instead of 'steamcmd'
Package 'steam-launcher' is not installed, so not removed
Package 'steam-installer' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  steam-devices*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 81.9 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 255837 files and directories currently installed.)
Removing steam-devices (1:1.0.0.61-2ubuntu3) ...
fluffery@tuxbox:~$ sudo apt purge steam* && sudo rm -rf ~/.steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'steam-launcher' for glob 'steam*'
Note, selecting 'steamcmd' for glob 'steam*'
Note, selecting 'steam-installer' for glob 'steam*'
Note, selecting 'steam' for glob 'steam*'
Note, selecting 'steam-devices' for glob 'steam*'
Note, selecting 'steam:i386' instead of 'steam'
Note, selecting 'steamcmd:i386' instead of 'steamcmd'
Package 'steam-launcher' is not installed, so not removed
Package 'steam-devices' is not installed, so not removed
Package 'steam-installer' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fluffery@tuxbox:~$ steam
[2021-07-16 21:40:45] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ 
fluffery@tuxbox:~$ sudo apt purge steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgl1-mesa-glx:i386 libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  steam:i386*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 4,504 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 255831 files and directories currently installed.)
Removing steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
(Reading database ... 255810 files and directories currently installed.)
Purging configuration files for steam:i386 (1:1.0.0.61-2ubuntu3) ...
fluffery@tuxbox:~$ sudo apt purge steam* && sudo rm -rf ~/.steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'steam-launcher' for glob 'steam*'
Note, selecting 'steamcmd' for glob 'steam*'
Note, selecting 'steam-installer' for glob 'steam*'
Note, selecting 'steam' for glob 'steam*'
Note, selecting 'steam-devices' for glob 'steam*'
Note, selecting 'steam:i386' instead of 'steam'
Note, selecting 'steamcmd:i386' instead of 'steamcmd'
Package 'steam-launcher' is not installed, so not removed
Package 'steam-devices' is not installed, so not removed
Package 'steam-installer' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgl1-mesa-glx:i386 libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fluffery@tuxbox:~$ sudo rm -rf ~/.steam
fluffery@tuxbox:~$ cd ~/.steam
bash: cd: /home/fluffery/.steam: No such file or directory
fluffery@tuxbox:~$ sudo apt install steam
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi libgstreamer-plugins-bad1.0-0
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  steam-devices
Suggested packages:
  libnvidia-gl-390:i386 | libnvidia-gl-435:i386 | libnvidia-gl-440:i386
The following NEW packages will be installed:
  steam:i386 steam-devices
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,471 kB of archives.
After this operation, 4,585 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu focal/multiverse i386 steam i386 1:1.0.0.61-2ubuntu3 [1,451 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/multiverse amd64 steam-devices all 1:1.0.0.61-2ubuntu3 [20.8 kB]
Fetched 1,471 kB in 0s (5,117 kB/s)      
Preconfiguring packages ...
Selecting previously unselected package steam:i386.
(Reading database ... 255810 files and directories currently installed.)
Preparing to unpack .../steam_1%3a1.0.0.61-2ubuntu3_i386.deb ...
Unpacking steam:i386 (1:1.0.0.61-2ubuntu3) ...
Selecting previously unselected package steam-devices.
Preparing to unpack .../steam-devices_1%3a1.0.0.61-2ubuntu3_all.deb ...
Unpacking steam-devices (1:1.0.0.61-2ubuntu3) ...
Setting up steam-devices (1:1.0.0.61-2ubuntu3) ...
Setting up steam:i386 (1:1.0.0.61-2ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
fluffery@tuxbox:~$ steam
[2021-07-16 21:42:15] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
fluffery@tuxbox:~$ 
fluffery@tuxbox:~$

**Comment by kisak-valve** [comment]
Hello @FlufferyAutism, does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 20.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

I suspect that you're using the nVidia proprietary driver, but don't have the video driver's 32 bit userspsace installed.

**Comment by FlufferyAutism** [comment]
how would i go about doing that
but glxinfo does work

fluffery@tuxbox:~$ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7405 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 465.27
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 465.27
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 465.27
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

my computer is 64-bit dont know why it wouldnt

**Comment by kisak-valve** [comment]
The nVidia prorietary driver requires that that the running kernel module, 32 bit userspace, and 64 bit userspace libraries are all installed and have exactly the same version to work properly. Since you're using the 465 series driver, you should be able to check the userspace libraries with something like `apt policy libnvidia-gl-465 libnvidia-gl-465:i386` and install the 32 bit userspace libraries with something like `sudo apt install libnvidia-gl-465:i386`.

**Comment by FlufferyAutism** [comment]
since im pretty noobie with linux on an actual desktop for all my purposes 
this is the output of apt policy
```
libnvidia-gl-465:
  Installed: 465.27-0ubuntu0.20.04.2
  Candidate: 465.27-0ubuntu0.20.04.2
  Version table:
 *** 465.27-0ubuntu0.20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages
        100 /var/lib/dpkg/status
libnvidia-gl-465:i386:
  Installed: 465.27-0ubuntu0.20.04.2
  Candidate: 465.27-0ubuntu0.20.04.2
  Version table:
 *** 465.27-0ubuntu0.20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages
        100 /var/lib/dpkg/status

```
i already have  `sudo apt install libnvidia-gl-465:i386` installed so idk why it wont work then

**Comment by FlufferyAutism** [comment]
good news got the client to open up

**Comment by FlufferyAutism** [comment]
closing ticket now
thanks for the help
