### ISSUE TITLE
After entering the date of birth on the game page, the selection list does not disappear

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/steam-for-linux#7926]
#### Your system information

* Steam client version (build number or date): 1626461631
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
After entering the date of birth on the game page, the selection list does not disappear
![Снимок экрана-20210717165817-561x370](https://user-images.githubusercontent.com/30505454/126039452-6a4c2bc1-d40a-4a35-98da-9e38e1ecb7e0.png)

#### Steps for reproducing this issue:

**Comment by kisak-valve** [comment]
Hello @Vladislavuz, this issue is already being tracked at #7864. Closing as a duplicate.
