### ISSUE TITLE
Segfault on startup with kubuntu

### ISSUE THREAD

**Issue by frederikja163** [ValveSoftware/steam-for-linux#7927]
#### Your system information

* Steam client version (build number or date):  Installed with `apt install steam` today, cant open UI and don't know how to find this without UI
* Distribution (e.g. Ubuntu): Kubuntu
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I installed steam but after opening steam through clicking on the icon it just crashes, if i try in the terminal i get the following error [
[log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6843972/log.txt). 
[log.txt](https://github.com/ValveSoftware/steam-for-linux/files/6844026/log.txt)

#### Steps for reproducing this issue:

1. Install steam via `apt install steam`
2. Run steam via terminal `steam`

#### Extra information
Im using an HP pavilion with a nvidia gpu and an intel i5 cpu. Someone suggested it was a driver issue so that might be relevant?  I just installed kubuntu a few days ago from a freshly downloaded ISO. This also means i wouldnt object to restarting my system and reinstalling the distro. I have obviosly tried reinstalling steam but that didnt help at all.

I tried following everything on this link: https://askubuntu.com/a/1040737 Both before and after the reinstall of steam.

I also tried several different methods of downloading steam, all got the same error. I tried snap, apt, discover (a kubuntu appstore), and dpkg with the steam.deb file from the official website.

Im willing to both try out on a new fresh install of kubuntu, and a new set of hardware too. As this is just an old computer that im trying to give new life to before buying a new laptop for school. So let me know if you need further information or can help in any way!

**Comment by kisak-valve** [comment]
Hello @frederikja163, `swrast` is mesa's slower software renderer, and the fact that Steam is trying to use it hints that you're using nVidia's proprietary driver, but don't have the video driver's 32 bit userspace libraries installed. Find what driver series you're using, then install the 32 bit driver support with something like `sudo apt install libnvidia-gl-465:i386` (replace 465 with the driver series you're using).

**Comment by frederikja163** [comment]
Ok so i found the driver series with `apt list --installed | grep nv` and found out i use 460, after installing that it seems like it worked just fine. Thanks a lot for the help, this issue can probably be closed now.
