### ISSUE TITLE
Searching Discussions leaves Relevance/Time UI stuck on screen.

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/steam-for-linux#7931]
This has been annoying me for quite some time, this dialogue remains on screen until Steam app is shut down. 

Please fix.

#### Your system information

* Steam client version : Jul 16 2021, at 18:05:04 Package 1626461631
* Manjaro / Plasma  (testing branch)
* Opted into Steam client beta?: [YES]
* Have you checked for system updates?: [YES]

#### Please describe your issue in as much detail as possible:
![Screenshot_20210721_151444](https://user-images.githubusercontent.com/17428910/126438165-8652fa0f-b508-484f-a0b4-6dfd806436f5.jpeg)

#### Steps for reproducing this issue:

1. Go to any games discussion section
2. Search for whatever
3. Select sort by:  issue starts here.

**Comment by kisak-valve** [comment]
Most likely another example of the issue being tracked at #7825 / #7864.

**Comment by kisak-valve** [comment]
Hello @jarrard, let's use #7825 to track this issue. Feel free to add your experience there.

Closing in favor of the older issue report.
