### ISSUE TITLE
Compose an advisory for distrubution maintainers to acheive anti-cheat complicance, and communication with AC providers to get components whitelisted.

### ISSUE THREAD

**Issue by YellowOnion** [ValveSoftware/steam-for-linux#7934]
Recent announcement of Steam Deck announced Anti-cheat support.

Providing anti-cheat on Windows is fairly simple as Windows has the source code so it limits the amount of modifications that entities can do, they also sign a large amount of drivers to help establish a trusted user base.

linux and the userspace components that make up an OS are all open source leading itself to be modified, there's no common use of roots of authority, and some users use their own custom kernels, Many distro's modify and maintain patched versions of core components to the Linux OS system.

There are many components that will likely trigger false positives or cause crashing and security issues, if they're non-standard:

Linux kernel (I assume the AC provides a kernel module?), common gaming patch sets, VFIO/vendor-reset.
systemd (NixOS maintains patches for it's unique set of issues).
Xorg
wayland
LD_PRELOAD
gamemode
mangohud
libstrangle
bubblewrap (again NixOS uses bwrap heavily to emulate "normal" FHS linux).

AC providers have a history of implementing "dumb" easily fooled, "hack detection" systems, (like the KVM patch that let BattleEye users play games or the use of HyperV nesting).

BattleEye has caused BSOD on older windows versions (my friend experienced this), and EAC is notorious for causing serious performance issues on my old Windows computer, that required system restarts to fix.

Security and stability is of utmost importance and with such a large array of different configurations seems to be a huge vector for problems, it would be nice if any closed source components of the kernel modules were audited regularly by a 3rd party, and any part that can be open sourced should be to increase the compatibility and potential for public audits.

AC providers will have to step-up and be more open with the Linux community if they want to establish a good image with Linux gamers as they're already dropping the ball in many key areas like banning VFIO players.

**Comment by kisak-valve** [comment]
Hello @YellowOnion, this request is jumping the gun a bit on this request. We first need to have working integration with the Anti-cheat vendors before requesting better documentation.

I'm going to close this for now, but if the (future, not yet written) documentation is unclear for baseline expectations from the system, then give me a ping here and we can re-open this.

**Comment by YellowOnion** [comment]
> Hello @YellowOnion, this request is jumping the gun a bit on this request. We first need to have working integration with the Anti-cheat vendors before requesting better documentation.
> 
> I'm going to close this for now, but if the (future, not yet written) documentation is unclear for baseline expectations from the system, then give me a ping here and we can re-open this.

Thanks, you bet I will, I miss playing a few games so AC support would be nice, but steam updates constantly break in NixOS without much warning, so I'm anticipating issues and I really hope that the AC providers realize we moved away from Windows to get _more privacy_, more control over our systems, like for example, if the solution is to ship a custom signed Linux kernel, then it's kind of against the spirit of running Linux in the first place.
