### ISSUE TITLE
Proton: the prefix and shader cache folder are not moved when a game is moved to a different drive

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7936]
#### Your system information

* Steam client version (build number or date): Jul 20 2021
* Distribution (e.g. Ubuntu): Manjaro/Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When moving a Proton game for a different hard drive, the equivalent prefix and shader cache folders are not being moved.

#### Steps for reproducing this issue:

1. Move an installed Proton game to a different hard drive
2. Check if the equivalent shader cache and prefix folders were moved as well

**Comment by kisak-valve** [comment]
Hello @ranplayer, this issue is already being tracked at #5717. Closing as a duplicate.
