### ISSUE TITLE
steamwebhelper.sh does not handle spaces in path

### ISSUE THREAD

**Issue by dotterian** [ValveSoftware/steam-for-linux#7939]
#### Your system information

* Steam client version: Jul 20 2021
* Distribution: Ubuntu
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If Steam installation path contains spaces `steamwebhelper.sh` breaks due to lack of quotes around path passed to dirname.
Right now it's 
```shell
DIR=`dirname $0`
```
Should be
```shell
DIR=`dirname "$0"`
```

#### Steps for reproducing this issue:

1. Move your Steam installation to a path containing space in it (in my case it's `/media/%user%/Windows/Program Files (x64)/Steam`. Yeah, I've tried to combine both distributions in hopes to save some space on my drives).
2. …
3. **Steam**ing pile of $#!+

**Comment by kisak-valve** [comment]
Closing per the last comment.
