### ISSUE TITLE
F.E.A.R. 3 (21100) not using cloud saves

### ISSUE THREAD

**Issue by FurtadoPires** [ValveSoftware/steam-for-linux#7941]
* Steam client version: v020
* Distribution: Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

First of all, I'm sorry for opening this issue here. I'm aware this isn't directly related to steam-for-linux but I don't know where I could properly open this issue since this game isn't supported by the original developers anymore. Feel free to just close this issue if that's a unsolvable problem.

The problem is for some reason the game is not using the available cloud space to store the save files, which are the ones in:
Linux: /steamapps/compatdata/21100/pfx/
Windows: \userdata\<user-id>\21100\local\

![fearcloud](https://user-images.githubusercontent.com/7890832/127047845-c022f7c9-10fd-4828-80c5-0f99531179d3.png)

While the progress with the achievements are being saved the same doesn't happens with the game progress, being erased in case of a new install without manual backup.

Since the official developers won't fix it anymore,  I would like to know if something could be done so that the game can sync these files to the cloud without the intervention of the original developers.

**Comment by kisak-valve** [comment]
Hello @FurtadoPires, from the hints you've given, I have to guess that you're running the game with Proton. We're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/963#issuecomment-886983858.
