### ISSUE TITLE
Market Place advanced options Issue

### ISSUE THREAD

**Issue by a7madjg** [ValveSoftware/steam-for-linux#7943]
#### Your system information

* Steam client version (build number or date): jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Going to market place, selecting advanced options, and choosing any scroll list option (Such as weapon list in CS:GO advanced options), then choosing a element of that list, makes the list not go away and stay on screen until steam client is shutdown completely, even if i close the tab using the x button.

#### Steps for reproducing this issue:

1. Go to marketplace
2.  Select advanced options, pick a game (in this example csgo) then pick a filter which uses a list (such as the weapons list in CSGOs advanced filters)
3. Pick any item on the list
The list will stay on screen until completely restarting the steam client

**Comment by kisak-valve** [comment]
Hello @a7madjg, let's use #7825 to track this issue. Feel free to add your experience there.

Closing in favor of the older issue report.
