### ISSUE TITLE
Window control buttons placed in wrong top corner

### ISSUE THREAD

**Issue by anohren** [ValveSoftware/steam-for-linux#7946]
#### Your system information

* Steam client version (build number or date): Jul 20 2021
* Distribution (e.g. Ubuntu): Ubuntu 21.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The buttons to minimize, maximize, unmaximize and close the window don't respect the environment's placement of those buttons. Other windows have theirs in the top left corner, meanwhile Steam has them in the top right.

#### Steps for reproducing this issue:

1. Configure your environment to have window controls in the top left corner
2. Launch Steam client

**Comment by kisak-valve** [comment]
Hello @anohren, this issue is already being tracked at #1040. Closing as a duplicate.

**Comment by anohren** [comment]
Hello, thanks for the info. 

I could not find a mention of this issue in the non-collapsed comments in that thread so I'll have to take your word for it.
