### ISSUE TITLE
innapropriate polkit request for system network configuration modification

### ISSUE THREAD

**Issue by draeath** [ValveSoftware/steam-for-linux#7951]
#### Your system information

* Steam client version (build number or date): 2021-07-20 22:25:57
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed
* Opted into Steam client beta?: [Yes/No]: No
* Have you checked for system updates?: N/A

#### Please describe your issue in as much detail as possible:
When starting steam, it requests access to NetworkManager system level configuration, for no discernible reason (via `org.freedesktop.NetworkManager.settings.modify.system`.

If there is some corner-case reason for requesting this, we should have a setting to control this behavior.

#### Steps for reproducing this issue:

1. Run steam on Linux with protected network configuration (ie, wifi passphrase visible to root only).
2. Receive polkit prompt for `org.freedesktop.NetworkManager.settings.modify.system`.
3. Cancel this prompt, receive a new one immediately.
4. Loop endlessly until some sort of timeout is reached and Steam gives up.
5. Observe that steam works fine despite having been refused this access.

**Comment by kisak-valve** [comment]
Hello @draeath, this issue is already being tracked at #7856. Feel free to add your experience to that issue report.

Closing as a duplicate.
