### ISSUE TITLE
Steam keeps forgetting library folders

### ISSUE THREAD

**Issue by kermitfrog** [ValveSoftware/steam-for-linux#7954]
#### Your system information

* Steam client version (build number or date): Jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu): Neon (Ubuntu 20.04 LTS based)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Recently the Steam client started to forget where the additional Library folders are, so I have to add them again each time I start steam. The additional folders I want to have are not on removable drives.

Things I tried / noticed:
All other Settings are correctly saved and loaded.
in `~/.steam/steam/config`:
- changes are saved in `libraryfolders.vdf`, but overwritten on start.
- making the `libraryfolders.vdf` belong to root and the user unable to write/delete it while having the correct settings does not help (as expected).
- removing lines with "BaseInstallFolder_*" from `config.vdf` does not help either.

#### Steps for reproducing this issue:

1. Start Steam
2. Notice that no Games seem to be installed because only the default library folder is set
3. Add library Folder (Games available again and can be played)
4. Exit steam Client
5. Repeat from 1.

**Comment by HellishINC** [comment]
How are you adding the steam folders again? Steam complains to me that there are contents in the directory already and fails.

**Comment by Martin1991zab** [comment]
With the Beta Client (Jul 30 as 00:13:42) i have a similar effect . I can not remove folders, the option do's not exists at all. 
And for an older folder (the path don't exists anymore) i have the option to "Remove Drive", but after restarting Steam the entry is back.

**Comment by kermitfrog** [comment]
@HellishINC 
> How are you adding the steam folders again? Steam complains to me that there are contents in the directory already and fails.

I'm adding them through the Menu.
Steam -> Settings -> Downloads -> Steam Library Folders -> Add Library Folder
I have never seen the Storage Manager on your screenshot. Are you using the beta?

@Martin1991zab 
Sounds like my problem in reverse...
I can remove folders via context menu (Same place where  you can add them): 
right clicking the entry, then "Remove Library Folder"
Did you try editing the 2 config files I mentioned?

**Comment by HellishINC** [comment]
@kermitfrog 
Yes, I'm on the beta. I was also adding them through steam but it refused to add them.

Either way this issue seems to have been fixed so perhaps it should be closed?

**Comment by kermitfrog** [comment]
I don't like that I had to switch to beta - but it did fix the issue, so I'm closing it.

**Comment by pixartist** [comment]
This issue is appearing again

**Comment by Bisc0tt1** [comment]
Started experiencing this issue myself lately. So far it has sporadically happened to me in a span of about two weeks. Due to the random nature of it, I haven't been able to make much of an effort towards troubleshooting this. All I can add is that the default library points to ~/.local/share/Steam, and the library I have added and set to default points to ~/Games

Not participating in the client beta, version is as follows:
Steam Version:  1694466342
Steam Client Build Date:  Mon, Sep 11 22:49 UTC -08:00

**Comment by nexitem** [comment]
Same issue on Flatpak
