### ISSUE TITLE
[Beta Client] Disk Write Errors

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#7957]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/6024315/127719309-8809e447-2ed8-47e6-aa4f-1411eb27621a.png)
* Distribution (e.g. Ubuntu): Ubuntu 21.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Not sure if related to #7956, but twice now I've gotten disk write errors while downloading Proton Experimental while using the latest steam beta client [Ubuntu 21.04]. And this is the latest re-release that sounds like it fixed a similar issue on OSX. Maybe Linux could use the same fix?

![Screenshot_2021-07-29_21-32-40](https://user-images.githubusercontent.com/6024315/127719531-76d445bc-65c1-4251-ae33-c07e241db3ba.png)
![Screenshot_2021-07-30_17-51-27](https://user-images.githubusercontent.com/6024315/127719537-b98e7af2-95ec-46d7-9bad-59d62182614c.png)

#### Steps for reproducing this issue:

1. Let the Beta Client attempt to download Proton Experimental.
2. Experience Disk Write Errors.

**Comment by kisak-valve** [comment]
Hello @nightsky30, this reads like the issue being tracked at #7956. If you find a hint in `~/.local/share/Steam/logs/content_log.txt` that gives a different hint than that issue report, than we can ponder your issue separately.

Closing in favor of #7956.

**Comment by smcv** [comment]
An easy way to tell: if your `content_log.txt` mentions `errno 24` then this is the same bug as #7956. If not, then it's likely to be something different.

**Comment by nightsky30** [comment]
Thank you both. I'll keep an eye out if it happens again.
