### ISSUE TITLE
Steam Client went black and not showing any thing

### ISSUE THREAD

**Issue by DevProd-6** [ValveSoftware/steam-for-linux#7959]
#### Steam client information :

* Steam client version (build number or date):  Jul 30 2021 
* Distribution :  Arch Linux (64  #bit)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Issue description :
The steam client is not showing any tab they all went black , and also Menu-Items in menu-bar are not working : which are view,friends, games. Also chat is not working, but the big picture mode is working fine (excluding chat,web browser

I tried the following :
1. $ steam --reset
2. reinstalling steam
3. beta client update
and yet nothing worked

#### Note : 
client was working fine, this issue occurred 4 days ago.

![screenshot](https://user-images.githubusercontent.com/45941938/127741923-b074d581-fd63-416d-ab2f-2db8baa393ac.jpg)

**Comment by kisak-valve** [comment]
Hello @DevProd-6, if you completely close Steam, then run `steam-runtime` from a terminal, does the terminal spew give any hints?

**Comment by DevProd-6** [comment]
https://privnote.com/GRbdmsfu#NeVUrUICh
this is the output of terminal after steam-runtime

**Comment by kisak-valve** [comment]
Thanks @DevProd-6, `./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language` in your log tells us that you've encountered the issue that's already being tracked at #7935.

Closing as a duplicate.
