### ISSUE TITLE
Steam Friends will not sign in at start-up after Downloads page update

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#7962]
#### Your system information

* Steam client version (build number or date): 1627685077 (Downloads section update)
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

You have to manually press "sign in" in the friends window or similar buttons found elsewhere eg in the game page in your library.

**Comment by Termuellinator** [comment]
Can confirm here on Manjaro testing. Pretty annoying ^^

**Comment by echaskaris** [comment]
Fixed with latest beta
