### ISSUE TITLE
Items in the "What's new" section of the library home page re-appear on start-up

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#7963]
#### Your system information

* Steam client version (build number or date): 1627685077
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

#### Steps for reproducing this issue:

1. Right click and hide all of the items in the What's new section
2. Items will re-appear on next start-up

**Comment by echaskaris** [comment]
Seems to be gone, will update when new items are available.

**Comment by echaskaris** [comment]
Bug still appears. It seems it is gone if I keep removing them enough, but comes back when there is a new item. (The new item appears, as well as everything that did before)

**Comment by at46** [comment]
For me everything in the what's new section is back there whenever I restart the steam client.

**Comment by echaskaris** [comment]
I'd say this is fixed, not sure since when though.
