### ISSUE TITLE
Once opened combobox never closes

### ISSUE THREAD

**Issue by GitterHubby** [ValveSoftware/steam-for-linux#7964]
#### Your system information

* Steam client version (build number or date): Jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu):  Ubuntu 20.04.02 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever a page is displayed where you have to confirm your birthday and you open the comboboxes, the last opened combobox never closes again - it stays open in in front until you exit the steam client. It also stays on top when you starting games (no matter fullscreen or windowed).

#### Steps for reproducing this issue:

1.  Navigate to a game page where you have to confirm your birthday and change one of the three combobox values.
2.  Once such a combobox opened, it only vanaishes if you open another combobox (day, month or year).
3. Continue navigating => the last opened combobox never closes again (i.e. keeps showing its content list) and stays on top of every displayed  content - even games.
4. Only completetely exiting the steam client also closes the combobox list.

This issue is now for several months and all the OS / video driver / steam client updates did not fix this.

**Comment by GitterHubby** [comment]
![ComboboxBug](https://user-images.githubusercontent.com/6904528/127772839-5e5dcabc-b937-4e16-aa0f-0b8eaae38fc8.png)

**Comment by GitterHubby** [comment]
![ComboboxBug2](https://user-images.githubusercontent.com/6904528/127772861-4247bcd7-3e77-477f-a0cd-7850a3069aba.png)

**Comment by kisak-valve** [comment]
Hello @GitterHubby, this issue is already being tracked at #7825. Closing as a duplicate.
