### ISSUE TITLE
Drop-down menu is detached and never gone until I exit steam

### ISSUE THREAD

**Issue by VitalyAnkh** [ValveSoftware/steam-for-linux#7965]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/24508452/127854319-a940e81e-b5b5-42c2-90c6-06fc93c00f37.png)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Search "Grand Theft Auto V", click
2. steam ask you to input your birthday, click the drop-down menu to choose date
3. The drop-menu are detached and never gone until I exit steam
![image](https://user-images.githubusercontent.com/24508452/127853713-e0f6c4d6-d4e7-4d03-ba14-083e489068a9.png)

![image](https://user-images.githubusercontent.com/24508452/127853936-3f9a339a-6adf-4494-8617-d67ebd3957f7.png)

![image](https://user-images.githubusercontent.com/24508452/127853983-fcb87a53-3fb9-47a2-b632-873cedb48f97.png)

**Comment by kisak-valve** [comment]
Hello @VitalyAnkh, this issue is already being tracked at #7825. Closing as a duplicate.
