### ISSUE TITLE
The dropdown lists in the Steam application are always on top and do not close.

### ISSUE THREAD

**Issue by hsnnsnc** [ValveSoftware/steam-for-linux#7975]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20210630.0 Jul 20 2021
* Distribution (e.g. Ubuntu): KDE neon 5.22 (Based on Ubuntu 20.04 LTS)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No]  Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](![Screenshot_20210806_165140](https://user-images.githubusercontent.com/44933756/128572476-ba08ed22-34fd-48a8-9ffe-e656f9116b8f.png)
![Screenshot_20210806_165211](https://user-images.githubusercontent.com/44933756/128572492-bb0c3221-389f-48e5-a8ef-d86d36fc7f18.png)
![Screenshot_20210806_165256](https://user-images.githubusercontent.com/44933756/128572506-ed67fc69-b849-4e4a-8ba4-7fd80294f2e3.png)
![Screenshot_20210806_165319](https://user-images.githubusercontent.com/44933756/128572511-63ddc242-5f6f-4245-a392-9da2df6c99a7.png)
)

#### Steps for reproducing this issue:

As can be seen from the screenshots I have attached; The Steam app keeps the dropdowns constantly on top after selecting from the dropdowns. I have to close and reopen the Steam app for this to be fixed. Otherwise, the dropdowns lists do not close.

**Comment by kisak-valve** [comment]
Hello @hsnnsnc, this issue is already being tracked at #7825. Closing as a duplicate.
