### ISSUE TITLE
Steam Verifiying installation loop

### ISSUE THREAD

**Issue by Burning290** [ValveSoftware/steam-for-linux#7976]
#### Your system information
RAM:7.8GiB
Processor:Intel Core 2 Quad CPU Q9400 @ 2.66GHz x4
GPU:GeForce GT 710
* Steam client version (build number or date): Latest as of Aug 6 2021 sry i dont know how to check without opening the launcher
* Distribution (e.g. Ubuntu): Ubuntu(64-bit)
* Opted into Steam client beta?: [Yes/No]No
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
I have recently switch for linux mint to ubuntu, and when i donwloaded steam i expected it to be like every time i booted it up on mint, except make take  longer. But what ended up happening was when i try to boot it for the first time it said verifying installation then closed and nothing else happened.
A log of when when i try booting it up through terminal:
[INFO:Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/caston/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-08-06 16:30:18] Startup - updater built Jul 20 2021 22:25:51
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  44
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-08-06 16:30:18] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2021-08-06 16:30:18] Using the following download hosts for Public, Realm steamglobal
[2021-08-06 16:30:18] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2021-08-06 16:30:18] Checking for update on startup
[2021-08-06 16:30:18] Checking for available updates...
[2021-08-06 16:30:18] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2021-08-06 16:30:18] Download skipped: /client/steam_client_ubuntu12 version 1626824053, installed version 1626824053, existing pending version 0
[2021-08-06 16:30:18] Nothing to do
[2021-08-06 16:30:18] Verifying installation...
[2021-08-06 16:30:18] Performing checksum verification of executable files
[2021-08-06 16:30:19] Verification complete

#### Steps for reproducing this issue:

1. Have a fresh install of ubuntu
2. Install Steam and launch
I have a felling it is not like this for most people im just hoping someone can help me fix this also it is not a full loop like the title says it just happens when i try to open it i just didnt know how to word it

**Comment by kisak-valve** [comment]
Hello @Burning290, `X Error of failed request: BadValue (integer parameter out of range for operation)` is the hint in your terminal spew. You can search this issue tracker for similar incidents focusing on that.

Does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of `mesa-utils` work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 20.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

I suspect that you're using the nVidia proprietary driver, but don't have the video driver's 32 bit userspace installed, or the driver is not sane in some other way. The nVidia proprietary driver does require that the running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and have exactly the same version to work properly.
