### ISSUE TITLE
Steam Notifcations sound keeps repeating when getting any kind of notifications

### ISSUE THREAD

**Issue by MilkJug1** [ValveSoftware/steam-for-linux#7978]
#### Your system information

* Steam client version (build number or date): July 20, 2021
* Distribution (e.g. Ubuntu): Arco Linux (BSPWM)
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I was trying to select a Proton version for steam, I noticed that every time that I moved the mouse when it said "This setting will not take effect until you have restarted Steam." the sound for notifications kept repeating, to a point where it was blaring.

It should just play the sound 1 time, but its doing it everytime I move the mouse on those kinds of boxes.

#### Steps for reproducing this issue:

1. Go and select a Proton Version (this way is the easiest I can think of)
2. Click on any version
3. Wait for the windows asking you to restart steam pops up
4. Try and move your mouse (just make sure your headphones are not up to loud)

**Comment by kisak-valve** [comment]
Hello @MilkJug1, this issue is already being tracked at #846. Closing as a duplicate.
