### ISSUE TITLE
Steam is lag too much when I'm logging in to the chat.

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#7979]
#### Your system information

* Steam client version (build number or date): 1628114775
* Distribution (e.g. Ubuntu):  Fedora Rawhide
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is lag too much when I'm logging in to the chat.
By this, I mean delayed response to keyboard input (letters appear in input fields with an unacceptable delay). Also, an unacceptable delay for clicks and scroll with a mouse.
When I sign out of friends & chat the steam response becomes normal.

#### Steps for reproducing this issue:
Demonstration: https://youtu.be/oB8KK6Fh7cc

**Comment by kisak-valve** [comment]
Hello @NTMan, this issue is already being tracked at #7245. Closing as a duplicate.
