### ISSUE TITLE
Upload/share shaders to help other players with stuttering issues

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7981]
#### Your system information

* Steam client version (build number or date): Jul 20 2021
* Distribution (e.g. Ubuntu): Manjaro/Arch
* GPU/Driver: Nvidia: 470.57.02
* Opted into Steam client beta?: No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I've noticed that some games have incomplete or absent pre-shader caching. Would it be possible to upload game shaders so others players wouldn't suffer from stuttering when playing ?

**Comment by kisak-valve** [comment]
Hello @ranplayer, with some protection from abuse, this is how Steam's shader pre-caching already works.

**Comment by ranplayer** [comment]
Great. Is it done as a background hidden task ?

**Comment by kisak-valve** [comment]
I don't have access to the internal details to give an authoritative confirmation, but the part you've shown interest in should be part of a post-game-session worker task (like in #6332 / #6811) that spins up just after exiting a game and having Steam's shader pre-caching enabled. It shouldn't be happening at random in the background.

**Comment by ranplayer** [comment]
Alright. Thanks for the explanation.
