### ISSUE TITLE
Steam keeps downloading small files and checking installs!

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/steam-for-linux#7988]
#### Your system information

* Steam client version (build number or date):  Aug 11 2021, at 17:14:33 
* Distribution (e.g. Ubuntu): Manjaro Plasma
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
It seems Steam keeps downloading little files for many games when I restart. This seems wrong.

![Screenshot_20210813_205555](https://user-images.githubusercontent.com/17428910/129350952-a7384696-d270-492c-8e5e-98d84d76691b.jpeg)

https://gist.github.com/jarrard/83901432e10599bab09c96d6ba471f0d

#### Steps for reproducing this issue:

1. Reboot / Restart Steam
2. Look in DOWNLOADS

**Comment by kisak-valve** [comment]
Hello @jarrard, this looks like the current intended behavior for Steam's shader pre-caching sub-component. It should be noted that older Steam client releases had these relatively small updates as well, but without as much visibility or end-user control over the cache updates. You can confirm this by monitoring `~/.local/share/Steam/logs/shader_log.txt` as those updates come in.

**Comment by jarrard** [comment]
> Hello @jarrard, this looks like the current intended behavior for Steam's shader pre-caching sub-component. It should be noted that older Steam client releases had these relatively small updates as well, but without as much visibility or end-user control over the cache updates. You can confirm this by monitoring `~/.local/share/Steam/logs/shader_log.txt` as those updates come in.

So it just does this endlessly? its only started doing this since the big steam update recently. Also the downloads are not marked as Shader Cache like they normally would be.
