### ISSUE TITLE
All drop down menus in web views remain stuck on screen permanently

### ISSUE THREAD

**Issue by Redbatman89** [ValveSoftware/steam-for-linux#7995]
This is another issue affecting Steam Linux users for awhile too.

https://steamcommunity.com/app/221410/discussions/0/3046105389677620436/

Original Post from OP

All drop down menus in web views remain stuck on screen permanently
I am running Manjaro Linux with KDE Plasma and in every web view (like store, workshop, community) every drop down menu becomes permanently stuck on screen upon opening it, above other windows. It will never close even if it accepts my selection. I have to exit steam entirely to remove it from the screen.

Additionally, the steam interface is noticeably more sluggish than every single other piece of software im using. This is true with or without "gpu accelerated rendering in web views" being activated. (though it is slightly more sluggish with it on).

I am also using Optimus Manager, set to the nvidia card. (though it doesnt seem to matter regardless)

EDIT: Something else ive noticed is that if i open another drop down menu in a web view, it will remove the old stuck drop down menu, with the newly selected menu now being stuck.

System info and specs:
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.42-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4200M CPU @ 2.50GHz
Memory: 7.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 860M/PCIe/SSE2

**Comment by kisak-valve** [comment]
Hello @Redbatman89, this issue is already being tracked at #7825. Closing as a duplicate.
