### ISSUE TITLE
Edit Profile Showcase Drop Down Menu Stays Open

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/steam-for-linux#7998]
#### Your system information

* Steam client version (build number or date): Aug 11 2021, at 17:14:33
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When editing your profile and choosing your showcases, the drop down menu selection for different showcases will stay open after clicking and choosing your showcase, after after moving to another page.

#### Steps for reproducing this issue:

1. Go to Edit or Change Showcase
2. Click the drop down menu to select a showcase for your profile
3. After selecting the showcase the menu remains open on the screen

![20210817_17h50m34s_grim](https://user-images.githubusercontent.com/5150898/129829594-3d6204fc-653b-490a-ac8a-f592e196eb23.png)

**Comment by eukara** [comment]
Yeah, same thing here on OpenSUSE Tumbleweed with the Steam Beta Client. The only way to get it to close is to close Steam and run a new instance.

**Comment by SoulRiets** [comment]
Not only Profile and not only Steam Beta. Any Dropdown menu and It happened to me on Ubuntu and Mint. ![steam screenshot](https://imgur.com/a/YEk9oxH)

**Comment by kisak-valve** [comment]
Hello @shoober420, this issue is already being tracked at #7825. Closing as a duplicate.
