### ISSUE TITLE
Steam Proton Gives this error.

### ISSUE THREAD

**Issue by Redbatman89** [ValveSoftware/steam-for-linux#8002]
Hi so I know Steam Proton is still an ongoing experiment but I find it curious why this error generates over on Gnome Logs

blk_update_request: I/O error, dev sr0, sector 6 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Buffer I/O error on dev sr0, logical block 4, async page read

I know this would normally be a scary error, but it only happens with proton games and not with Linux Native games. I posted an issue like this on reddit over a year ago.

**Comment by kisak-valve** [comment]
Hello @Redbatman89, in general, please report issues with Proton on the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues).

`[...]dev sr0[...]` This is the first device of the kernel's scsi rom subsystem. In modern systems, that's the first CD/DVD/BD drive of the system, and attempting to read, but failing to read a DVD drive is completely harmless. It is most likely inherited behavior from upstream wine.

Closing as not a Steam client issue.

**Comment by dennis1248** [comment]
This does not seem like a Proton issue to me. The log spam triggers on Steam's launch. Might have something to do with the recent changes to Steam's disk manager.

I am guessing it is likely trying to read all disks connected to the system to make a list of available volumes for its disk manager.

`[  385.208974] sr 1:0:0:0: [sr0] tag#23 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[  385.208977] sr 1:0:0:0: [sr0] tag#23 Sense Key : Not Ready [current] 
[  385.208978] sr 1:0:0:0: [sr0] tag#23 Add. Sense: Medium not present - tray closed
[  385.208980] sr 1:0:0:0: [sr0] tag#23 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
[  385.208982] blk_update_request: I/O error, dev sr0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[  385.318970] sr 1:0:0:0: [sr0] tag#28 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[  385.318973] sr 1:0:0:0: [sr0] tag#28 Sense Key : Not Ready [current] 
[  385.318975] sr 1:0:0:0: [sr0] tag#28 Add. Sense: Medium not present - tray closed
[  385.318976] sr 1:0:0:0: [sr0] tag#28 CDB: Read(10) 28 00 00 00 00 00 00 00 02 00
[  385.318977] blk_update_request: I/O error, dev sr0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 8 prio class 0
[  385.318982] Buffer I/O error on dev sr0, logical block 0, async page read
[  385.318983] Buffer I/O error on dev sr0, logical block 1, async page read
[  385.318984] Buffer I/O error on dev sr0, logical block 2, async page read
[  385.318985] Buffer I/O error on dev sr0, logical block 3, async page read
[  385.318985] Buffer I/O error on dev sr0, logical block 4, async page read
[  385.318986] Buffer I/O error on dev sr0, logical block 5, async page read
[  385.318987] Buffer I/O error on dev sr0, logical block 6, async page read
[  385.318988] Buffer I/O error on dev sr0, logical block 7, async page read
[  390.178865] sr 1:0:0:0: [sr0] tag#30 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[  390.178868] sr 1:0:0:0: [sr0] tag#30 Sense Key : Not Ready [current] 
[  390.178870] sr 1:0:0:0: [sr0] tag#30 Add. Sense: Medium not present - tray closed
[  390.178871] sr 1:0:0:0: [sr0] tag#30 CDB: Read(10) 28 00 00 00 00 00 00 00 08 00
[  390.178873] blk_update_request: I/O error, dev sr0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[  390.268882] sr 1:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[  390.268884] sr 1:0:0:0: [sr0] tag#0 Sense Key : Not Ready [current] 
[  390.268886] sr 1:0:0:0: [sr0] tag#0 Add. Sense: Medium not present - tray closed
[  390.268887] sr 1:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 02 00
[  390.268889] blk_update_request: I/O error, dev sr0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 8 prio class 0
[  390.268893] Buffer I/O error on dev sr0, logical block 0, async page read
[  390.268895] Buffer I/O error on dev sr0, logical block 1, async page read
`

@kisak-valve Maybe re-open the issue and change the title?

**Comment by 0xC0ncord** [comment]
I'm seeing this same behavior, but only when starting games under Proton. Additionally, no Proton games are starting at all anymore, but I'm not sure if that issue is directly related to this.

**Comment by dCosminn** [comment]
I'm also getting these, from what i saw only with a game called Stationeers but the big issue is that once every 3 times i launch the game it will also freeze the system and have to push the reset button.  
Ubuntu 21.10, kernel: 5.14.21-051421-generic.

`dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 2 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 2, async page read
dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 3 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 3, async page read
dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 4 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 4, async page read
dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 5 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 5, async page read
dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 6 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 6, async page read
dec 16 05:12:21 H-Linux kernel: blk_update_request: I/O error, dev sr0, sector 7 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
dec 16 05:12:21 H-Linux kernel: Buffer I/O error on dev sr0, logical block 7, async page read`

**Comment by poperigby** [comment]
I'm also getting this, but I'm using the Steam Flatpak. Could it still be from Steam?

**Comment by mathew2214** [comment]
i am also seeing this behavior. 
sysinfo gist: https://gist.github.com/mathew2214/afb01ad1d775a87ec0b1762dc5c415bc
