### ISSUE TITLE
No way to add free Windows content to library for Proton use

### ISSUE THREAD

**Issue by falkreon** [ValveSoftware/steam-for-linux#8005]
#### system information

* Steam client version (build number or date): Jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu): KDE neon 5.20 (Ubuntu-like)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### The Issue

If something is free, there is no way to "purchase" the game to add it to your steam account without hitting the platform verification check for your current system. This means that linux users find it incredibly difficult to play free (proton-compatible) windows content on Steam unless they first download it in Windows.

#### Steps for reproducing this issue:

1. Navigate to any free Steam product for Windows - for example, the PSYCRON demo ( https://store.steampowered.com/app/1368410/PSYCRON/ )
2. Press the "Download" button
3. If you're coming from a browser, select "Yes, Steam is installed" to launch the Steam client
4. Observe the error message correctly preventing you from installing the game, but *also* preventing you from adding it to your library.

#### Ideal solution:

A button to add free content to your library without installing it immediately, either next to the "Download" button or as part of the platform error dialog flow.

#### Known workarounds:

1. Download the content on a windows computer first to place it in your Steam library.
2. Uninstall it (but don't remove from library).
3. Close Steam on the Windows computer and open it on the Linux computer
4. Select the grayed-out entry in the list, right click, and hit Manage
5. From the Compatibility tab, force the use of a specific compatibility tool as normal.

**Comment by kisak-valve** [comment]
Hello @falkreon, this was previously discussed on #6115. Enabling Proton for all titles in Steam's global settings will allow you to try to use demos for Windows-based games.
