### ISSUE TITLE
System information doesn't correctly report dGPU

### ISSUE THREAD

**Issue by sobornostea** [ValveSoftware/steam-for-linux#8007]
#### Your system information

* Steam client version (build number or date): 20/07/2021
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The system information tool in the Steam client doesn't report my hardware properly. In particular it doesn't report my Nvidia dGPU as my main GPU but instead my integrated GPU
Here is the report : https://gist.github.com/sobornostea/b0d1dd9a9f2e8babcb2af1a7aceb43ae

#### Steps for reproducing this issue:

1. Click Help > System Information
2. Under Video Card notice the absence of the Nvidia card

**Comment by kisak-valve** [comment]
Hello @sobornostea, it looks like Steam's system information is accurately telling you that the Steam client is currently running on the AMD hardware. This by itself isn't necessarily a bad thing, as it lets the nVidia GPU stay in a low power state, extending battery life and/or leaves the nVidia GPU free to only focus on game rendering workloads.

You should be able to confirm this by checking what's running on the nVidia GPU with `nvidia-smi` in a terminal.
