### ISSUE TITLE
Requires 64bit operating system error on aarch64 ubuntu.

### ISSUE THREAD

**Issue by FalcoGer** [ValveSoftware/steam-for-linux#8010]
#### Your system information

* Steam client version (build number or date): steamcmd 23.08.2021
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Running steamcmd through box86 on an aarch64 (arm64) linux on a raspberry pi 4 prevents the download of 64 bit only applications, such as 7 days 2 die (294420). I wish to run said 64 bit applications through box64.

I don't know how steamcmd detects 32/64 bit. Also it's rather strange that steamcmd only comes in 32 bit anyway. That's rather antiquated by now.

Is there an option to force the download anyway?

I am aware that there is no official support for ARM chips, but it would be nice if there was a quick fix anyway, such as detecting aarch64/arm64 as 64 bit or a command line flag to force the thing to think that it's 64 bit without checking.

```bash
STEAMPATH="/home/steam/steamcmd/linux32"
STEAMPATH64="/home/steam/steamcmd/linux64"
STEAMUSER="FalcoGerServer"
STEAMPASS="********"
GAMEPATH="/home/steam/Games/7d2d/"

LD_LIBRARY_PATH="$STEAMPATH:$STEAMPATH64:$LD_LIBRARY_PATH" "$STEAMPATH/steamcmd" +login "$STEAMUSER" "$STEAMPASS" +force_install_dir "$GAMEPATH"
```
```text
steam(pi):~>./run_steamcmd.sh
Box86 with Dynarec v0.2.3 c04aeec3 built on Aug 23 2021 19:56:33
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'FalcoGerServer' to Steam Public...src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
OK
Waiting for client config...OK
Waiting for user info...OK

Steam>app_update 294420 validate
ERROR! Failed to install app '294420' (Requires 64bit operating system)

Steam>exit
```

```text
steam(pi):~>uname -a
Linux pi 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:35:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

#### Steps for reproducing this issue:

1. Install and compile box64 and box86 on 64 bit Ubuntu for Raspberry Pi
2. Install and run steamcmd
3. Try to install 294420

**Comment by FalcoGer** [comment]
@kisak-valve thanks for the delete. I'll update the password anyway.

**Comment by kisak-valve** [comment]
Hello @FalcoGer, SteamCMD is not supported on ARM processors.

That said, `@sSteamCmdForcePlatformBitness = ""  : Must be one of: [32 | 64]` at https://developer.valvesoftware.com/wiki/Command_Line_Options#ConVars looks like what you're looking for.

And yes, definitely change that password as the initial post went out via email to users watching this repo.

**Comment by FalcoGer** [comment]
Password is updated.

Thank you for the link. Could you explain what a ConVar is please?

Is it an environment variable (`export sSteamCmdForcePlatformBitness=64`) or do I add that in the command line I launch steamcmd with? Or do I set it in steamcmd itself?

The provided example there doesn't use any of the listed convars.
