### ISSUE TITLE
Indiana Jones and the Emperor's Tomb crashing on intro

### ISSUE THREAD

**Issue by stixholder** [ValveSoftware/steam-for-linux#8012]
#### Your system information

* Steam client version (build number or date): Aug 20 2021, 20:39:31
* Distribution (e.g. Ubuntu): Manjaro (latest updates: https://forum.manjaro.org/t/stable-update-2021-08-17-kernels-kde-software-nvidia-firefox-thunderbird-mate/78666)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When launching the game, it switches to fullscreen, showing intro clips in the preset resolution of 640x480 in the left upper corner. The intro scene with music and the camera floating along the hallway plays for about 1-2 secs, then a windows error popup shows, the while screen freezes and music plays for a few more seconds: 

"(Render) An invalid floating point camera matrix was passed to the D3D driver!"

After pressing "X" on the popup, the game terminates.

#### Steps for reproducing this issue:

1. install game Steam / Linux
2. activating any compatibility Proton version or not, doesn't matter
3. game always crashes as described

**Comment by mtmkls** [comment]
This is a known Wine bug. https://bugs.winehq.org/show_bug.cgi?id=27594

**Comment by kisak-valve** [comment]
Hello @stixholder, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4027#issuecomment-909671918.
