### ISSUE TITLE
Sorting-dropdown list in Discussions Search not disappearing

### ISSUE THREAD

**Issue by wunderbar78** [ValveSoftware/steam-for-linux#8016]
#### Your system information

* Steam client version (build number or date): Package Version: 1629497411 - Built: Aug 20 2021 at 20:39:31 
* Distribution (e.g. Ubuntu): Ubuntu 21.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, all up to date
* Linux 5.13 xanmod
* Mesa 21.2.1 (Mesa almost stable - ppa:ernstp/mesarc)
* Cinnamon 4.8.6

#### Please describe your issue in as much detail as possible:
The dropdown list for sorting the search results in Discussions doesn't disappear after clicking and stays on top of everything, even games running in fullscreen.

![image](https://user-images.githubusercontent.com/60543364/130662946-1e62157f-9b22-45f1-972f-20261951c8bf.png)
![image](https://user-images.githubusercontent.com/60543364/130663141-8782382c-6285-49bc-aef1-1f152915a6c9.png)

While writing this issue I found out that Flameshot (Screenshot tool) sometimes makes the list disappear.
And after that, if I search and sort again, the list will disappear when hovering over the top bar (Shop/Library/etc) or the window loses focus.
If I search & sort and scroll down to view the results, the list is still visible though. If I now hover over the top bar, the main area of the steam client loses its focus and I can't scroll the results anymore.

#### Steps for reproducing this issue:

1. go to Discussions of any game and search something
2. sort the results

thanks in advance for having a look!

**Comment by kisak-valve** [comment]
Hello @wunderbar78, this issue is already being tracked at #7825. Closing as a duplicate.
