### ISSUE TITLE
distribute bash

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#8022]
/bin/sh is usually a minimal shell (for instance dash on devuan or could be ash from busybox, and any other).
Then steam-client bash scripts should have their shebang updated properly.
This will improve the steam-client distro agnosticism.

**Comment by kisak-valve** [comment]
Hello @sylware, please clarity which Steam bash script uses a /bin/sh shebang.

Distributing bash when all major distros provide it is a pointless exercise.
