### ISSUE TITLE
steamwebhelper keeps crashing after updating freetype2

### ISSUE THREAD

**Issue by wvffle** [ValveSoftware/steam-for-linux#8029]
#### Your system information

* Steam client version (build number or date): Jul 20 2021, at 22:25:57 
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When steam is run in a terminal, whenever a web window (be it store or ingame overlay web window) is displayed, the output is spammed with following messages and the window is black.
```
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language
```

It started happening after some update to the freetype2 package in archlinux.

#### Steps for reproducing this issue:

1. Update freetype2 package
2. Restart steam
3. Open store page

**Comment by kisak-valve** [comment]
Hello @wvffle, this issue is already being tracked at #7935. Closing as a duplicate.
