### ISSUE TITLE
Steam dropdown menus cannot be closed

### ISSUE THREAD

**Issue by 2l47** [ValveSoftware/steam-for-linux#8030]
#### Your system information
* Steam client version (build number or date): Jul 20 2021, at 22:25:57
* Distribution (e.g. Ubuntu): Debian 10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When attempting to select a dropdown menu option, the items can sometimes not be selected at all, but the dropdown menu always cannot be closed by clicking outside of it somewhere else in the Steam client window, by clicking the area that first opened it, or by selecting one of the available menu options. Selecting a different dropdown menu will switch to that menu, but it also cannot be closed. Continuing to use the Steam client leads to the dropdown persisting as far as I've seen. Closing the Steam window leaves the dropdown box still rendering without a window, and the Steam client has to be exited to get rid of it.
![dropdown](https://user-images.githubusercontent.com/80786286/131557852-fd85610d-faed-4a05-bb14-f231e3555883.png)

#### Further information
With an active, functional, dropdown menu, you can click on another desktop window like a browser, and observe the dropdown menu close. When you go back to Steam, however, you'll find that you can no longer switch between dropdown menus or change the current selection. Going "Back" in the Steam client and then "Forward" makes selections possible again.

#### Steps for reproducing this issue:
1. Find a game on Steam and try gifting it to a friend with a scheduled date.
2. Try specifying a month, day, year, time, and AM/PM.
3. Close the Steam window and observe that the last selected dropdown menu remains.
4. Exit Steam through the notification center and see the dropdown menu disappear.
5. Repeat steps 1-2 but click into another desktop window and see the dropdown menu close, then go back to Steam and observe that the dropdown selections cannot be changed until you reload the page by navigating "Back" and "Forward".

**Comment by kisak-valve** [comment]
Hello @2l47, this issue is already being tracked at #7825. Closing as a duplicate.
