### ISSUE TITLE
Doom 3 BFG Edition - no video, only sound with AA

### ISSUE THREAD

**Issue by stixholder** [ValveSoftware/steam-for-linux#8039]
#### Your system information

* Steam client version (build number or date): Sep 3 2021, 21:49:55
* Distribution (e.g. Ubuntu): Manjaro stable [UPDATE AUGUST 17](https://forum.manjaro.org/t/stable-update-2021-08-17-kernels-kde-software-nvidia-firefox-thunderbird-mate/78666)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes (not yet updated due to libfreetype issue with Steam client in library view)

#### Please describe your issue in as much detail as possible:
In Doom 3, any anti-aliasing setting other from 'disabled' will cause any 3D rendering and cutscenes to stay black. Sound is ok, HUD and crosshair is displayed, footsteps are audible when moving around (game engine obviously is running), but everything else, models, textures, motion, etc. is not rendered.

#### Steps for reproducing this issue:

1. Run Doom 3 with 'anti aliasing' setting 2x, 4x or 8x

**Comment by kisak-valve** [comment]
Hello @stixholder, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/569#issuecomment-913050921.
