### ISSUE TITLE
Steam fails to successfully launch on Ubuntu 20.04 on 

### ISSUE THREAD

**Issue by solaremperor** [ValveSoftware/steam-for-linux#8040]
#### Your system information

* Steam client version (build number or date): Build date Jul 20 2021 22:25:51
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3 LTS on Linux kernel 5.11.0-27-generic
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I launch steam from the command line for the first time, steam progress bar shows downloading an update. The package is extracted and installed. This windows closes. Then, a progress bar-like windows reopens to check the runtime. Finally, steam checks for updates again and closes once again.

I've put the terminal output in [this GitHub Gist file](https://gist.github.com/solaremperor/58784990bfdd9455df64ff83473801d5).

#### Steps for reproducing this issue:

Have the following as a prerequisite:
1. Install ubuntu [updated to Sep 5, 2021]
2. Use nvidia proprietary driver 460

Then, run the following steps in a terminal window:
1. sudo apt update && sudo apt upgrade
2. sudo apt install steam
3. steam

**Comment by kisak-valve** [comment]
Hello @solaremperor, if you run `steam` from a terminal, does the terminal spew give any hints? The distro-modified Steam package might also redirect some terminal spew to `~/.steam/steam/error.log`.

**Comment by solaremperor** [comment]
@kisak-valve Thanks for reaching out. Following instructions that the issue template had, I've put the long terminal output in a gist and linked it in the issue itself. Here's the GitHub gist link again: [https://gist.github.com/solaremperor/58784990bfdd9455df64ff83473801d5](https://gist.github.com/solaremperor/58784990bfdd9455df64ff83473801d5).

Lines 5 and 6 in the gist show a couple of libgl errors but the execution does seem to continue.

However, lines 8, 228 and 260 have the - same error output "X Error of failed request:  BadValue (integer parameter out of range for operation)" followed by a major opcode failure. I'm no expert here, but I feel like this is a graphics driver issue causing the steam windows to crash when attempting to open it.

Also, the very first output line is an error related to libGLEW: "ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libGLEW.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored."

I don't see any other clues.

Hope this helps.

Best,
S

**Comment by kisak-valve** [comment]
Thanks, `swrast` is mesa's slower software renderer and the fact that Steam is trying to use it hints that you're using nVidia's proprietary driver, but don't have the video driver's 32 bit userspace support installed. The nVidia proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace are all installed and exactly the same version to work properly.

Since you're using the 460 series driver, something like `sudo apt install libnvidia-gl-460:i386` should resolve your issue.

**Comment by jamogriff** [comment]
Thanks @kisak-valve! Had the same issue with the 470 series driver and your explanation and fix worked perfectly.

**Comment by kisak-valve** [comment]
Glad to hear you got it running.

Ubuntu currently also has the nvidia 470 driver series available (https://packages.ubuntu.com/focal-updates/nvidia-driver-470), and Steam doesn't really care what you use as long as you have a sane 32 bit and 64 bit OpenGL render path.
