### ISSUE TITLE
No UX

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/steam-for-linux#8043]
### Result:

![Screenshot_20210907_182806](https://user-images.githubusercontent.com/9594332/132379814-5edc6eeb-fdb2-4566-b62e-8feb069da2d1.png)

### Error log:

Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0xa322c7
Serial number of failed request:  6786
xerror_handler: X failed, continuing
./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

### System information:

* Steam version: 1.0.0.71-1
* Distribution: Manjaro
* Opted into Steam client beta: No
* Checked for system updates: Yes

**Comment by kisak-valve** [comment]
Hello @es20490446e, this issue is already being tracked at #7935, and should already be fixed in Steam's client beta. Please opt in to Steam's beta client.

Closing as a duplicate.
