### ISSUE TITLE
Steam unscheduled downloads impossible to start

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#8046]
#### Your system information

* Steam client version (build number or date): Sep 7 2021
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I start my Steam BETA client, there are many random downloads added to this new download page, most likely shader pre-caching stuff, but I also often have an "unscheduled" download, and it is impossible to have this download to start automatically or by clicking the specific button made to force the download of it. However if I restart Steam this download starts automatically.

It may be one whole issue with the shader pre-caching settings in the BETA, all these nonsensical random downloads that add themselves every time I start Steam, and these unscheduled download that are also added but that I can't manually start.

So on a side note, but this is not the main issue I guess, something is broken with the shader pre-caching, moving to the beta made my cache go from (in the Settings) around 4GB size, to 0, despite the shadercache folder in Steam being 6+GB total. Now the Settings page in Steam shows 1.6GB of cached shaders. I can notice that it grows a little bit every time I start Steam when these little random downloads finish.

Here is an example of all the downloads once finished, this is like that every time I stop Steam for a good amount of time (if I restart it in loop after finishing all downloads, at some point no new downloads are added though) and restart it:

![Screenshot_20210908_063815](https://user-images.githubusercontent.com/17416415/132447800-715eef2d-6505-45ac-a416-a76e29886319.jpg)

You can see a few downloads markes with a 'bubble' that shows what the update is and for some the bubbles is there and says it is shader pre-caching, for all the non marked in my screenshot none are real game updates, these are all shader pre-caching except the King of Crabs update that was for once a real game update.

#### Steps for reproducing this issue:

1. Start Steam
2. Observe many downloads newly added to the list some/most of them being marked as shader cache, but in reality all of them being shader cache because all these game don't receive multiple updates every day obviously (always the same dozen games, my Proton games)
3. Try to manually start one of the unscheduled download
4. Watch nothing happening besides making the download graph move at the same time you click the button to force the download

**Comment by Zorrototo** [comment]
And after sending the above report, I closed Steam, and instantly restarted it, and as expected new downloads!!

![Screenshot_20210908_064850](https://user-images.githubusercontent.com/17416415/132448340-eef11290-8901-432b-b560-50c4af186271.jpg)

If I wait longer, there are more downloads added, here I just closed/restarted.

**Comment by kisak-valve** [comment]
Related to #7972.
