### ISSUE TITLE
"Enable Steam Play for all other Titles" does not save after restart.

### ISSUE THREAD

**Issue by Septimius-Severus** [ValveSoftware/steam-for-linux#8048]
#### Your system information

* Steam client version (build number or date):  steam-1.0.0.71-1 (native)
* Distribution (e.g. Ubuntu): Arch Linux 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After the latest update, I can no longer enable Steam Play for all titles, every time I check the option on the settings page for Steam Play and restart the client, the setting doesn't stay set.

#### Steps for reproducing this issue:

1. Click "Enable Steam Play for all other titles" on the settings.
2.  *Optionally* choose your desired version of proton (it doesn't work no matter what I pick).
3.  Restart as prompted.
4. When the client is up again, the setting will not have saved.

**Comment by kisak-valve** [comment]
Hello @Septimius-Severus, I expect that there's an understated detail that you also have a third party Proton build added to your system.

This issue is already being tracked at #6043. Closing as a duplicate.
