### ISSUE TITLE
Black screen - Gentoo

### ISSUE THREAD

**Issue by UnregisteredUsername** [ValveSoftware/steam-for-linux#8057]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Gentoo (5.10.49-gentoo-r1)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I expected to be met with my library but I got a black screen. Nothing  that relied on webview works. I can alter the settings but not open the store, library, community or friends.

My steamwebhelper.log contained the following:
```
Updating Steam runtime environment...
/home/peter/.local/share/Steam/ubuntu12_64/steam-runtime-heavy/setup.sh: line 421: zenity: command not found
/home/peter/.local/share/Steam/ubuntu12_64/steam-runtime-heavy/setup.sh: line 77: echo: write error: Broken pipe
```

#### Steps for reproducing this issue:

1. Update steam
2. Login

**Comment by UnregisteredUsername** [comment]
The issue seems to  have been fixed while I was installing Zenity.

**Comment by kisak-valve** [comment]
Note: This issue is being tracked at https://github.com/ValveSoftware/steam-runtime/issues/458.
