### ISSUE TITLE
Vibration no longer works for Razer Sabretooth or Xbox Elite Controller 2. Rumble cannot be set in preferences 

### ISSUE THREAD

**Issue by metatron-the-chronicler** [ValveSoftware/steam-for-linux#8063]
#### Your system information

* Steam client version (build number or date):  September 10th 2021
* Distribution (e.g. Ubuntu): Manjaro (5.13.13-1-MANJARO)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Expected: Controller settings should present option to disable or enable vibration under preferences for controller.
Actual: No option is present and vibration does not work even for native games such as Blasphemous.

Update: I was able to get my hands on a DualSense (PS5) Controller. Vibration works as expected with this device.  The preference to enable/disable the vibration functionality is also visible as expected.

**Comment by flashrocket** [comment]
same here for third party xbox 360 controller. Used to work before but an update broke it.

**Comment by atylmo** [comment]
I'm also having this with my Xbox One S controller. The "Identify" button and the option to toggle rumble are missing from the controller settings. Neither wired nor Bluetooth work.

It (sort of) works using the Steam Link app and pairing it with my tablet but I get [the issue described here](https://github.com/ValveSoftware/steam-for-linux/issues/8107) where it shakes all the time. But when using it this way, the "Identify" button does appear.

**Comment by ANDRoid7890** [comment]
I have the same issue with X-Box One S controller.
There's no "Identify" button or an option to toggle rumble like before
Tried to connect via bluetooth/usb, tried to use xpadneo driver, tried to enable/disable custom settings

Vibration still works perfectly in non-steam games which i run with Lutris

Manjaro KDE, unstable branch

**Comment by kisak-valve** [comment]
Hello, based on the feedback on #8590, the 2022-10-27 Steam client beta may help with this issue. Please opt into Steam's client beta and retest.

**Comment by kisak-valve** [comment]
Closing pending feedback.
