### ISSUE TITLE
All my Steam games (both native and Proton/DXVK) recompile shaders every single time I launch them

### ISSUE THREAD

**Issue by user1-github** [ValveSoftware/steam-for-linux#8070]
* Steam client version: September 10, 2021
* Distribution: Ubuntu Mate 20.04.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I identified this issue because DXVK games stutter for a while after I launch them, while native games have longer than usual loading times. I've tried clearing Steam shader cache and let Steam redownload all the shaders, but it didn't help. I have never experienced this issue before and it started happening after I received the new Steam client update, so I suspect it's a bug in the new update. I've attached my system info in a txt file.
I'll also add that the "processing Vulkan shaders" window appears only the first time I launch the game (as it usually should).

#### Steps for reproducing this issue:

1. Run a Proton/DXVK game and close it after a while
2. Run the game again
3. The second time you run the game, it stutters as if you're launching it for the first time
[systeminfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/7156751/systeminfo.txt)

**Edit**: It seems my issue is fixed after updating to Mesa 21.2.2. Closing for now.

**Comment by user1-github** [comment]
Hello @kisak-valve, did you have a chance to check this issue?

**Comment by Esokrates** [comment]
@user1-github So you are re-reporting https://github.com/ValveSoftware/steam-for-linux/issues/7306 right?

**Comment by user1-github** [comment]
> @user1-github So you are re-reporting #7306 right?

No, look at my description.. the "processing Vulkan shaders" window appears only the first time. That report also seems to be specifically for Dota and my issue has started after after I received the September 10 update.
