### ISSUE TITLE
Steam closes itself automatically after some time

### ISSUE THREAD

**Issue by drogeek** [ValveSoftware/steam-for-linux#8071]
#### Your system information

* Steam client version (build number or date): Sept 10 2021
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
* Opted into Steam client beta?: [Yes/No] Used to when this situation happened, switched back to non-beta since then (a few hours ago)
* Have you checked for system updates?: [Yes/No] Yes, everything is up to date, mesa version is 21.2.1 from Kisak PPA,

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam closes after some time, and consistently dota 2 freezes when it happens, leading to me getting tagged as "leaver" and being punished for reasons that are against my will. (Several hours where I can't play, followed by being forced to play with often even less friendly people than usual to be tagged as normal again)
This happened multiple times already, I would say, something like once a day.
I've tried to find the `error.log` file supposed to be located in my `~/.steam` directory (I checked in the shell script that launches the game that it IS where it is supposed to be), nothing.
Anybody having the same issue?

#### Steps for reproducing this issue:

1. Launch steam
2. Leave it open and do stuff

**Comment by jarrard** [comment]
I've noticed steam client has been silently closing allot in the past month also. Not sure if its crashing or not but I use Arch linux non the less.

**Comment by metatron-the-chronicler** [comment]
I have seen steam close silently as well before the September 10 2021 update.

**Comment by cghost-linux** [comment]
I have the crash with latest September update to. I run openSUSE 15.3.
It crashes very often during the day, it is practically unusable.
I started Steam in the console and saved the output in a text file.
[console_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/7191176/console_log.txt)

**Comment by jarrard** [comment]
Deleted all my shadercache files ( was like 10GB almost) and symlinked them all to main user folder location and so far steam hasn't shut itself down. So I suspect I had some bad shadercache files.

**Comment by cghost-linux** [comment]
Deleting shadercache files didn't help me. It seems that a random download in the background is causing the crashes. Today a few games were updated again and during the update Steam shut down.
Today was a steam update, but it didn't fix the problem.

**Comment by kisak-valve** [comment]
Hello @drogeek, mesa 21.2.1 ended up having an on-disk shader cache bug which was fixed in 21.2.2.

Closing per the last several comments.

**Comment by bonkmaykrQ** [comment]
I apologize for necroposting but I am getting this issue again years later, and it started happening sometime after the Families Beta launched. I'm on Steam Beta w/ Trinity desktop on X11 and every once in a while on random occasions steam will pop up with "Shutting down steam..." out of nowhere. After this, it will never open again, if I try to restart it from the terminal it will freeze for about a minute before core dumping. Error messages are not clear. It happens more often right when I do something like start a QEMU VM or turn my VPN on, but it also sometimes just happens randomly for no reason. I just got a competitive ban on THE FINALS for this.

**Comment by NJMonnet** [comment]
I have the same problem on TF2, if I open the steam overlay and try to open someone's profile steam will shut itself down every time, this will also happen when I try to use a link which will interact with the steam app for exemple to join a server.

Steam version : 1721173382
Distribution : Nobara Linux 40 (GNOME Edition)
and my system is up to date.

**Comment by STR4NG3RdotSH** [comment]
Just dropping a note here. Steam client has been closing on me randomly as well. Although instead of investigating I've just put a cron task in to re-open it. It hasn't happened during gaming (yet), like some of you getting flagged... A bandaid solution but doing the trick for me, as my only complaint was steam not compiling shaders in the background because it closed on its own, making gaming sessions get delayed when I actually wanted to play, since it started shaders once I launched steam/game.

cron task: `* * * * * /home/<username>/keep_steam_alive.sh >>/tmp/steam_cron.log 2>&1`

Script:
```
#!/bin/bash
export DISPLAY=:0
export XAUTHORITY=/home/<username>/.Xauthority

pgrep steam || xhost +SI:localuser:<username>; DISPLAY=:0 /usr/games/steam
```

**Comment by yvdorofeev** [comment]
Same issue. It force-exits the game and closes steam. Every ~10 mins.
