### ISSUE TITLE
UI Breaks for Dropdown Menus

### ISSUE THREAD

**Issue by alkaris2** [ValveSoftware/steam-for-linux#8073]
#### Your system information

* Steam client version (build number or date):  Sept 13 2021
* Distribution:  Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

If I click on a dropdown menu in Steam it gets stuck and overlays on top of everything, nothing gets rid of it except closing steam completely.

This has happened on multiple occasions while browsing the Steam Store page and there is something I need to click from the dropdown menu, the dropdown menu gets stuck and won't go away even if you select something from that menu. This completely breaks Steam's usability altogether, I can't cancel the menu either way from pressing Esc or clicking out of the the window, it stays persistent over the screen even if I switch away from it.

**Comment by kisak-valve** [comment]
Hello @alkaris2, this issue is already being tracked at #7825. Closing as a duplicate.
