### ISSUE TITLE
Steam window opening itself everytime i start a game through shortcut

### ISSUE THREAD

**Issue by zeparu** [ValveSoftware/steam-for-linux#8077]
#### Your system information

* Steam client version (build number or date): Built: Sep 16 2021, at 00:09:09
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
up until a couple days ago, i could open steam games through a shortcut, and avoid opening the steam window and find my game.

but since a couple days ago, whenever i try to start a game through steam, the steam main window will open itself forcefully, before starting to open the game.
steam is open in the background (in sys tray) the whole time, and its not entirely restarting steam, just reopening the main window.

#### Steps for reproducing this issue:

1. open steam
2. close steam window
3. start a game through .desktop shortcut / sys tray shortcut
4. steam main window will open itself, and start the game

**Comment by kisak-valve** [comment]
Hello @zeparu, "Stop automatically navigating to the game details page when starting a game" in the [2021-09-17](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/5324933455472331530) Steam client beta update might be related to this issue. Please update the Steam client and retest.

**Comment by zeparu** [comment]
yes, that fixed it, thank you
