### ISSUE TITLE
Proton games not launching with latest beta

### ISSUE THREAD

**Issue by brain-anti-freeze** [ValveSoftware/steam-for-linux#8080]
#### Your system information

* Steam client version (build number or date): Sep 17 (1631912732)
* Distribution (e.g. Ubuntu): Arch with 5.14.5-zen2-1-zen / nvidia: 470.63.01
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Games all launched fine in the prior beta, now no window is displayed, processes run for approx 1 min then quit.  I tried both current proton 6.3 and experimental and deleting and re-creating the prefixes.  All games appear to be affected.  Backing out of the beta fixes the issue completely.  Attached are two logs, one of The Ascent failing with the new beta and the other of it working after opting out of beta.

#### Steps for reproducing this issue:

1. Update to latest beta
2. Attempt to launch any proton game

[steam-979690.log](https://github.com/ValveSoftware/steam-for-linux/files/7189507/steam-979690.log)
[steam-979690-broken.log](https://github.com/ValveSoftware/steam-for-linux/files/7189508/steam-979690-broken.log)
.

**Comment by kisak-valve** [comment]
Hello @brain-anti-freeze, for clarity, please verify that the beta you're referring to is Steam's client beta.

**Comment by brain-anti-freeze** [comment]
Sorry, yes the beta I'm referring to is the Steam client beta.

**Comment by brain-anti-freeze** [comment]
Hmm actually I thought I should try opting back in to the client beta to verify the issue ... and its still working fine after opting back in.  Perhaps something happened when the beta update applied that messed up my installation and re-installing has fixed it.  I'll be sure and try that first next time before logging an issue.
