### ISSUE TITLE
Age verfication page is bugged and dont disappears

### ISSUE THREAD

**Issue by X6205** [ValveSoftware/steam-for-linux#8084]
#### Your system information

* Steam client version (build number or date): Built: Sept 13 2021, at 22:01:31, Steam package versions: 1631572918
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam client for linux has bugged age verification page on store. You can choose your birth date but menus remain open and does not disappear until i quit Steam client.

#### Steps for reproducing this issue:

1. Install Ubuntu 20.04.3 and add Kisak Valve Mesa Fresh PPA
2. Fully update system and install Steam client
3. View any game page with age verification page
![Snímka obrazovky z 2021-09-19 16-03-25](https://user-images.githubusercontent.com/14248415/133930760-445a3daf-9ff0-4d21-b144-82618ab4c43a.png)

**Comment by kisak-valve** [comment]
Hello @X6205, this issue is already being tracked at #7825. Closing as a duplicate.
