### ISSUE TITLE
Destroy All Humans does not launch under Proton 6.3-6

### ISSUE THREAD

**Issue by metatron-the-chronicler** [ValveSoftware/steam-for-linux#8087]
#### Your system information

* Steam client version (build number or date): September 13 2021 
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Expected: Destroy All Humans should launch.
Actual: Destroy All Humans runs without displaying anything, then the steam running indicator returns to Play.
[system-info.txt](https://github.com/ValveSoftware/steam-for-linux/files/7193702/system-info.txt)

**Comment by kisak-valve** [comment]
Hello @metatron-the-chronicler, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4101#issuecomment-922898275.
