### ISSUE TITLE
Shader pre-cache not working on my system, nothing stored

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#8088]
#### Your system information

* Steam client version (build number or date): September 17, 1631912732
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

My shader pre-cache system on Steam is enabled, but it says it's storing nothing. I've been wondering why people in the GOL Discord keep mentioning lots of small updates that I've not seen - turns out mine appears to be stuck doing nothing?

I've tried disabling/enabling and restarting Steam but it still seems to do nothing.

Startup log in case it helps: https://gist.github.com/LiamDawe/3b0f2ba441862df64ab4f9e2315575f2
System details: https://gist.github.com/LiamDawe/c8033564a4065d7480db815d23e586d3

**Comment by kisak-valve** [comment]
Hello @LiamDawe, please attach `~/.local/share/Steam/logs/shader_log.txt` as a file for a Steam dev to ponder.

**Comment by LiamDawe** [comment]
Sure here you go: https://gist.github.com/LiamDawe/d62514423352fc3bd29f553ca36fd4be

**Comment by LiamDawe** [comment]
I cleared the Steam download cache, and on next load Steam settings say I have 2249 MB stored in the shader cache.

**Comment by LiamDawe** [comment]
Just a note that clearing the cache didn't seem to fix it. Has gone back to zero and I seem to be getting no shader updates again since the latest Beta.

**Comment by Plagman** [comment]
Can you try today's Client Beta?

**Comment by LiamDawe** [comment]
It does now appear to show it correctly :)

**Comment by kisak-valve** [comment]
Closing per the last comment.
