### ISSUE TITLE
Unable to use %command% in non-Steam games

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/steam-for-linux#8095]
#### Your system information

* Steam Client Build Date: Sep 17 2021, at 04:30:38
* Distribution: Manjaro Linux x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I added a non-Steam Windows game, Tag: The Power of Paint to the Steam Linux client and I wanted to quantify the performance using MangoHUD. However I noticed that the `%command%` directive does not work when dealing with Non-Steam games and Proton. This makes it difficult to force things like Wine DLL Overrides, FSync, or ESync. With native Linux games it's not as big of a deal as you can make Steam point to a .sh script that will configure the game as necessary.

#### Steps for reproducing this issue:

1. Add Non-Steam Windows game
2. Add `mangohud %command%` to the launch options of the game.
3. Watch in awe as nothing happens relating to MangoHUD.

**Comment by kisak-valve** [comment]
Hello @Sterophonick, this issue is already being tracked at #6046. Closing as a duplicate.
