### ISSUE TITLE
Steam asks to share my screen on every startup

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#8098]
#### Your system information

* Steam client version (build number or date): Sep 23 2021, at 14:35:28
* Distribution (e.g. Ubuntu): Fedora 34 GNOME
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Right on startup of Steam, without initiating a remote play session or such, Steam causes this popup to appear:

![image](https://user-images.githubusercontent.com/4428753/134539148-06d0a3d6-cc99-490b-b63f-07e250b8a8ef.png)

#### Steps for reproducing this issue:

1. Launch Steam on GNOME with PipeWire set up for screen sharing
2. Start Steam
3. Observe that Steam asks if you want to share your screen through PipeWire, even though you didn't initiate screen sharing

**Comment by kisak-valve** [comment]
Hello @Newbytee, this looks like an intended change per `Enabled pipewire desktop capture by default on Linux, pass -nopipewire on the command line to disable it` in the [2021-09-23](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2872724078255992088) Steam client beta update.

**Comment by Newbytee** [comment]
I would be very surprised if this is intentional. Generally, applications that use PipeWire should demand when they need it, not right on startup. Users should understand why they are sharing their screen, and there is no clear indication why my screen is being shared here.

**Comment by Bednar87** [comment]
I am experiencing the same issue on Arch KDE wayland session. The dialog shows up each time it starts. This definitely is not right.

**Comment by Daedrin** [comment]
I can confirm this as well. Pipewire should not be asking for this information on launch, rather when it is being called. I have all remote play, broadcasting, etc disabled in the client and it's still asking for this information on launch.

**Comment by minecraft2048** [comment]
WIP bug report: If I accept the share screen request, any games that uses Proton will not show their window at all. I haven't tested this with Linux native games

**Comment by minecraft2048** [comment]
> I would be very surprised if this is intentional. Generally, applications that use PipeWire should ask when they need it, not right on startup. Users should understand why they are sharing their screen, and there is no clear indication why my screen is being shared here.

I can see why they are doing it though, when you are starting a game through remote play you tend to be not in front of the desktop to accept screen sharing request.

**Comment by smcv** [comment]
> I can see why they are doing it though, when you are starting a game through remote play you tend to be not in front of the desktop to accept screen sharing request.

I'm pretty sure that's the reasoning for doing it this way, rather than each time Remote Play streaming is initiated. Part of the design of Remote Play is that it's initiated by the thin client (phone, laptop, Steam Link, smart-TV) rather than by the "big" gaming PC where the actual game runs.

See also <https://github.com/flatpak/xdg-desktop-portal/issues/324>: it's not currently possible to say "yes, share the screen, *and always allow this in future*", or programmatically set up permission non-interactively.

See also <https://github.com/flatpak/xdg-desktop-portal/issues/523>: it's not currently possible for Steam to say "I want to capture the whole screen, don't ask the user whether to share individual windows or the whole screen".

Perhaps the least-bad UX available, given what's currently possible, would be something like this:

* by default, only start capturing the screen when streaming starts;
* have an option somewhere (in Settings, and maybe also in the pairing dialog for easy access?) to start capturing the screen immediately on Steam startup, with the intention that people who use Remote Play more often would enable this option

**Comment by DanMan** [comment]
The least that should be changed is that it shouldn't even ask, if I have Remote Play completely disabled in the setting. I consider that happening nonetheless a bug.

**Comment by avoonix** [comment]
Not sure if steam can choose the screen on it's own (maybe always the primary display), but that would be very helpful. 
I'm not sure which monitor is which:
![image](https://user-images.githubusercontent.com/63160225/134766311-e2e984dd-e8ea-4042-b44d-7024e20c0a6c.png)

Something like this would be better:
![image](https://user-images.githubusercontent.com/63160225/134766333-5b1ef055-7437-4f50-a4b2-1b850c422144.png)

**Comment by minecraft2048** [comment]
From https://github.com/flatpak/xdg-desktop-portal/issues/324 it seems that @smcv don't want to duplicate the desktop specific code to access Pipewire, and in Flatpak this isn't possible at all. But it shows a UI problem in the portal chooser

**Comment by jmariondev** [comment]
@avoonix That UI is not part of Steam but rather xdg-desktop-portal-gtk, The behavior you're describing is something I've also really wanted and that ticket is at flatpak/xdg-desktop-portal-gtk#333.

**Comment by minecraft2048** [comment]
There is a problem, but maybe this is more of a KDE problem not Steam problem. Or maybe this is portal problem. If I accepted the screen share prompt, KDE notification center automatically switches to do not disturb mode:

![image](https://user-images.githubusercontent.com/2445636/134999552-d8fc98fe-aa7b-494a-bc74-6b8952b51ade.png)

If I accept the screen share prompt for remote play to work, I lose my notifications unless I manually uncheck the do not disturb mode after accepting the prompt. 
Will using RemoteDesktop in combination with ScreenCast fix this?

**Comment by kisak-valve** [comment]
Hello @minecraft2048, that sounds like something to ask the KDE devs about. Most likely an unrelated issue.

**Comment by hkaancaliskan** [comment]
> There is a problem, but maybe this is more of a KDE problem not Steam problem. Or maybe this is portal problem. If I accepted the screen share prompt, KDE notification center automatically switches to do not disturb mode:
> 
> ![image](https://user-images.githubusercontent.com/2445636/134999552-d8fc98fe-aa7b-494a-bc74-6b8952b51ade.png)
> 
> If I accept the screen share prompt for remote play to work, I lose my notifications unless I manually uncheck the do not disturb mode after accepting the prompt.
> Will using RemoteDesktop in combination with ScreenCast fix this?

This is directly related to steam. Actually steam needs to ask for permission when it is needed but instead it ask on startup instead. Launch steam with -nopipewire.
https://www.reddit.com/r/linux_gaming/comments/pu90cx/steam_suddenly_requests_screen_share_on_launch/he1b42y/

**Comment by Newbytee** [comment]
I would guess this is a "feature" since it thinks when you share your screen you're probably presenting or such.

**Comment by kisak-valve** [comment]
Hello, per "Pipewire desktop capture is disabled by default on Linux, launch Steam with the -pipewire command line option to enable" in the [2021-09-28](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2874976428915672907) Steam client beta update, this issue should now be resolved. As the release note suggests, you now need to opt-in to the pipewire integration if you want to experiment with using Steam's Remote Play from a wayland-based desktop session.

**Comment by major-mayer** [comment]
> I would guess this is a "feature" since it thinks when you share your screen you're probably presenting or such.

I think the whole user experience around the portal wasn't designed with use cases in mind like steam has 😐

**Comment by rohmishra** [comment]
Perhaps using https://github.com/flatpak/xdg-desktop-portal/pull/638 once it is merged might be a better solution in long run.

**Comment by kisak-valve** [comment]
Hello @dc740, you're looking for the issue being tracked at #6148 instead of this issue report.

**Comment by dc740** [comment]
ah, that's correct. Thank you @kisak-valve
