### ISSUE TITLE
Unable to launch Steam on Fedora 34

### ISSUE THREAD

**Issue by OracleAndroid** [ValveSoftware/steam-for-linux#8101]
#### Your system information

* Steam client version (build number or date): Unsure, last update was 9/23/21
* Distribution (e.g. Ubuntu): Fedora 34 
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Steam doesn't launch after an update to the Nvidia Driver, and the issue has persisted between reboots. After looking at #7999, I can confirm that the 32-bit Nvidia libraries are installed and my installed package list can be found [here](https://gist.github.com/OracleAndroid/73f3320ee2c2c6a4b8bf03df041ee18c)

I am not able to find an error.log, or a crashdump, but I may not be looking in the right places. :) 

HW Info: 
Ryzen 7 5800x
Nvidia GeForce GTX 1070

Linux Kernel version:
`uname -r`
`5.13.19-200.fc34.x86_64`

#### Steps for reproducing this issue:

1. Enable RPMFusion and Negativo17 Nvidia repo 
2. dnf install steam
3. launch Steam either from Shortcut, or terminal. 

Terminal Output:

``` steam
Running Steam on fedora 34 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/oracleandroid/.local/share/Steam/ubuntu12_32/steam
```

**Comment by kisak-valve** [comment]
Hello @OracleAndroid, similar to the issue report you linked, have you recently updated the nVidia driver version without rebooting? If the kernel module loaded into memory doesn't have the same version as  the driver's userspace libraries, then any OpenGL application can hang waiting on the driver.

**Comment by OracleAndroid** [comment]
As some addl. troubleshooting, I did the following:
1. Uninstall the Nvidia Drivers `dnf remove nvidia*`
2. reboot
3. Switch to tty2, and reinstall `dnf install  nvidia-driver akmod-nvidia nvidia-driver-libs nvidia-settings nvidia-driver-libs.i686 nvidia-driver-cuda`
4. reboot
5. Attempt to start Steam

No changes in behavior.

**Comment by OracleAndroid** [comment]
I gave it another shot this morning, and installed the last driver version (470.63), with still no change to the behavior.

**Comment by OracleAndroid** [comment]
Alright, well some good news. I completely deleted the ~./steam and ~./local/steam folders and have been able to launch Steam. This can be closed.
