### ISSUE TITLE
Sven Co-op stopped from working

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#8102]
#### Your system information

* Steam client version (build number or date): Sep 23 2021 at 14:35:28
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
On steam stable, Sven Co-op crashes.
On steam beta, Sven Co-op does not crash, but does not work properly. I only see main menu background without any controls.
Last game update was 16 days ago, i was able to play it 2-3 days ago.

I wanted to enable steam runtime in compatibility settings, but it didn't show any steam runtime, only proton

System info: https://gist.github.com/XakepSDK/d24447ec94b898cc2d56ecc0d01274f1
Last 7 day updates pacman log https://gist.github.com/XakepSDK/5ce8cadb4d3d65ac2103eabc34ee9c3c

#### Steps for reproducing this issue:

1. Enable Steam Beta
2. Start Sven Co-op
3. Game does not work properly

**Comment by kisak-valve** [comment]
Hello @XakepSDK, this issue should also be mentioned to the game's dev(s).

**Comment by XakepSDK** [comment]
Game works now. No idea why it didn't work yesterday.
