### ISSUE TITLE
Steam dev/publisher streams doesn't work (Optimus/Prime system)

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#8105]
#### Your system information

* Steam client version (build number or date): Sep 23 2021
* Distribution (e.g. Ubuntu): Linux Mint 20.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

On Steam,many dev/publisher pages has streams. Steam client says "your browser doesn't support minimum feature set to watch this stream.". 

- Reproducible with ANY stream on my end. Client is launched with ```__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only```.

- Output of Steam client sys info gathering tool:

https://gist.github.com/Leopard1907/8ee0d7fc9174d1f7e818aa86dd654cea

- System info (inxi -SMGxx):

https://gist.github.com/Leopard1907/e0983505aa30b6798ee8e40fc031b324

#### Steps for reproducing this issue:

1. Open Steam client
2. Preferably use an Optimus/Prime system with env vars above
3. Try to watch any dev/publisher stream

**Comment by kisak-valve** [comment]
Hello @Leopard1907, this issue is already being tracked at #6780. Closing as a duplicate.
