### ISSUE TITLE
Can't close birthday month select box

### ISSUE THREAD

**Issue by olamedia** [ValveSoftware/steam-for-linux#8108]
#### Your system information

* Steam client version (build number or date): Sep 17 2021 at 4:30:38
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Bug with Birthday month select. Can not close the birthday month select box. It can be removed from screen only by client restart.

#### Steps for reproducing this issue:

1. Open month select box on birthday confirmation page (for any game)
2. Try to close it - it leaves open even while browsing between pages

**Comment by kisak-valve** [comment]
Hello @olamedia, this issue is already being tracked at #7825. Closing as a duplicate.
