### ISSUE TITLE
Keyboard numlock issue

### ISSUE THREAD

**Issue by ZeXx86** [ValveSoftware/steam-for-linux#811]
This bug affected me only few times, but is very strange.
I don't know, how to reproduce it, because it is rather random, but is caused by Steam and/or Team Fortress 2.
It happened after longer gameplay for me of TF2. I just looked to my keyboard and I see how num lock LED is blinking in crazy way. I know I don't pressed Num lock key during game or anywhere in Steam, so problem should be in something different than keyboard event.

When LED is blinking [random and fast (100-300ms change of state)] I can't stop it with pressing a num lock key. Even if I quit TF2 problem still persist.
But when I turned off Steam, problem is gone. Starting Steam again and all is OK for longer time.
I don't remember it happened only when Steam was running, so there must be TF2 running for a while I guess.
This bug is here for longer time, I reporting it so late, because I was not sure it is Steam related.

My spec: http://pastebin.com/gTQWDQ5x
Ubuntu 12.10 64bit
Gnome 3 Fallback (No effects)
Steam is running latest version (updated today - 24.1.)

Thanks

**Comment by kisak-valve** [comment]
Hello @ZeXx86, are you still experiencing this issue with an up to date system?

**Comment by ZeXx86** [comment]
No. It does not happened for long time - I am also playing rather other Valve games at these days. But I have to say that I am running Debian stable with KDE 4 now.

Everything is running perfectly for very long time.

**Comment by kisak-valve** [comment]
Thanks for the feedback @ZeXx86, closing.
