### ISSUE TITLE
Clicking on steam tray icon doesn't show main window

### ISSUE THREAD

**Issue by snorlax212** [ValveSoftware/steam-for-linux#8116]
#### Your system information

* Steam client version (build number or date): Sep 17 2021, at 04:30:38
* Distribution (e.g. Ubuntu): Kubuntu 20.04.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

In KDE Plasma 5.18.5 single- or double-click on steam tray icon doesn't show main window (like on Windows or any other software I use in Linux too). Also I used xfce some time ago and this issue present there too.

#### Steps for reproducing this issue:

1. Launch/login steam.
2. Minimize steam to tray
3. Single or double click on steam tray icon
4. On single click - context menu pops up, on double click - nothing happens.

**Comment by kisak-valve** [comment]
Hello @snorlax212, this issue is already being tracked at #4836. Closing as a duplicate.
