### ISSUE TITLE
Proton runs various programs in background upon launching Steam, even with no game running

### ISSUE THREAD

**Issue by Star-X555** [ValveSoftware/steam-for-linux#8118]
#### Your system information

* Steam client version (build number or date): September 30 2021
* Distribution (e.g. Ubuntu): Arch Linux (technically Antergos, but was converted to Arch after that died)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Since the most recent betas of Steam, I've noticed that Steam runs multiple Proton binaries in the background upon Steam starting.  Things like explorer.exe and rpcss.exe open and close repeatedly in the background after Steam starts up.  Occasionally Proton also pops up with a window that says "File not found" with nothing else in it.  I'm guessing this is some kind of new optimizing feature or something, but I'd appreciate knowing what Steam is doing with the various Proton binaries running in the background upon starting Steam, mostly for peace of mind.  Also, fixing the "File not found" error would be nice too, since it's linked to whatever Steam is trying to do in the background.

#### Steps for reproducing this issue:

Start Steam
Open Terminal
Run ps -A
See lots of Proton binaries running after bootup.

**Comment by kisak-valve** [comment]
Hello @Star-X555, this issue is already being tracked at #8114. If you can figure out what Proton version is running when the dialog box is shown, then please add a note to that issue report.

Closing as a duplicate.
