### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by MrSchism** [ValveSoftware/steam-for-linux#813]
System Specs: https://gist.github.com/45ed161ede54ebc30909

So last night, I decided to lock my computer and head to bed.  I did't put it in sleep or suspend because it's a desktop and there's really no reason to do so.

I know that locking the screen hasn't disconnected me before (being I lock it every time I walk away from it).

I return to it in the morning and Steam isn't running.  I look at my terminal output and see the following:

> ****\* OUT OF MEMORY! attempted allocation size: 2097152 ****
> memstd.cpp (2501) : Assertion Failed: OUT OF MEMORY
> memstd.cpp (2501) : Fatal assert failed: /home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/memstd.cpp, line 2501.  Application exiting.
> 
> ? Assert( Fatal assert ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier0/memstd.cpp:2501
> 
> Installing breakpad exception handler for appid(steam)/version(1358979709_client)
> Uploading dump (in-process) [proxy '']
> /tmp/dumps/assert_20130124071213_3.dmp
> success = yes
> response:  CrashID=bp-81322f67-0559-401d-bc69-7f0852130124
> _ExitOnFatalAssert

**Comment by Voker57** [comment]
Steam is running "out of memory" for me right on startup. I have 16G memory + 32G swap.

```
% steam
Running Steam on debian 9 64-bit
STEAM_RUNTIME is enabled automatically
[2017-06-22 10:41:48] Startup - updater built Jun 21 2017 21:30:39
[2017-06-22 10:41:48] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-06-22 10:41:48] Checking for update on startup
[2017-06-22 10:41:48] Checking for available updates...
[2017-06-22 10:41:48] Download skipped by HTTP 304 Not Modified
[2017-06-22 10:41:48] Nothing to do
[2017-06-22 10:41:48] Verifying installation...
[2017-06-22 10:41:48] Performing checksum verification of executable files
[2017-06-22 10:41:49] Verification complete
***** OUT OF MEMORY! attempted allocation size: 805306368 ****
./common/pipes.cpp (571) : Assertion Failed: m_pInternalPipe->BRead failed
```

**Comment by leeps** [comment]
@Voker57 Check out #5069 , might be closer to your issue than this one
