### ISSUE TITLE
Improve "Processing Vulkan shaders" progress dialog

### ISSUE THREAD

**Issue by joshas** [ValveSoftware/steam-for-linux#8138]
Current implementation of "Processing Vulkan shaders" dialog window progress bar does not represent actual progress: it starts fairly quickly, almost reaches end of progress bar and usually stays there from a minute to half an hour or more. This usually leads to pressing "Skip" button.  
If it is impossible to implement progress bar with precise progress display, maybe it would be better to use indeterminate spinner and display progress by showing how many shaders or files were processed to indicate that process is still going and did not stall or freeze.

**Comment by joshas** [comment]
Driver:  AMD AMD Radeon RX 5600 XT (NAVI10, DRM 3.42.0, 5.14.9-200.fc34.x86_64, LLVM 12.0.1)
Driver Version:  4.6 (Compatibility Profile) Mesa 21.1.8

**Comment by kisak-valve** [comment]
The behavior you've described is consistent with a defect with mesa's on-disk cache management and not a Steam bug. There's some details in the links at https://github.com/ValveSoftware/Dota-2/issues/1968#issuecomment-925329414.

Unfortunately, this is a regression that crept into mesa 21.1.x late in its release cycle and the release branch reached its end of life before the fix landed. You may want to mention the commit which fixed that issue to your distro's package maintainer for mesa.

Closing as not-our-bug.
