### ISSUE TITLE
Steam cannot see my home directory if add 3rd party game

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#8154]
#### Your system information

* Steam client version (build number or date): 1631912732
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Menu-> games -> add 3rd party game -> Browse -> attempt to enter /home/

After i entered in steam file browser to /home i dont see home folders for any user it is just empty.

#### Steps for reproducing this issue:

Trivial

![steam_cannot_go_home](https://user-images.githubusercontent.com/22169129/137595379-3f6f8168-d643-4732-8bb4-31fee8809ca2.png)

Gist sysinfo: 

[Github Gist](https://gist.github.com/jpVm5jYYRE1VIKL/5e420ae9719e2e064f975748c2fc81d8)

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by jpVm5jYYRE1VIKL** [comment]
Gist added

**Comment by kisak-valve** [comment]
Thanks, that eliminated an incorrect guess I had. Looking around, this issue is already being tracked at #7834, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/7834#issuecomment-944964388.

Closing in favor of the older issue report.
