### ISSUE TITLE
Crash reports don't use HTTPS and get sent in plain text

### ISSUE THREAD

**Issue by TiagoTiago** [ValveSoftware/steam-for-linux#8157]

**Comment by kisak-valve** [comment]
Hello @TiagoTiago, without a better explanation on how this is a problem, I'm not seeing an actionable issue here.

Minidumps should not have sensitive information in them and it should be going to a crash report collection server that already needs to guard against malicious intent regardless of protocol used.

**Comment by TiagoTiago** [comment]
> Hello @TiagoTiago, without a better explanation on how this is a problem, I'm not seeing an actionable issue here.
> 
> Minidumps should not have sensitive information in them and it should be going to a crash report collection server that already needs to guard against malicious intent regardless of protocol used.

They include all sorts of details about the hardware, folder structure, configurations, drivers and software versions etc; way more than enough to fingerprint a computer, and potentially revealing information that may make things easier for a hacker. Even if Valve's servers are secure, there's the whole rest of the Internet to worry about if the information is transmitted in plaint text.
