### ISSUE TITLE
 Adding a non-Steam game from a .desktop file ignores arguments in double quotes

### ISSUE THREAD

**Issue by lat9nq** [ValveSoftware/steam-for-linux#8164]
#### Your system information

* Steam client version (build number or date): Oct 13 2021, at 19:47:24
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Adding a Non-Steam Game from a .desktop file ignores arguments in double quotes. The `TARGET` and `START IN` fields are populated seemingly properly. `LAUNCH OPTIONS` is blank.

#### Steps for reproducing this issue:

1. Have a .desktop entry with the `Exec` line reading something like `Exec=/path/to/program "/path/to/file"`
2. Add it as a Non-Steam Game
3. Steam ignores the double-quoted argument. The `LAUNCH OPTIONS` field remains blank in Properties.

**Comment by lat9nq** [comment]
If I try escaping characters in a file, i.e. `Exec=/home/lat9nq/repos/yuzu/build/bin/./yuzu -g /home/lat9nq/ROMs/NX/Pok__mon\ Legends_\ Arceus\ v0\ \(01001F5010DFA000\).xci`, Steam will reduce the arguments to `-g /home/lat9nq/ROMs/NX/Pok__mon Legends_ Arceus v0 (01001F5010DFA000).xci` which does not work (program tries to open `/home/lat9nq/ROMs/NX/Pok__mon`).

If I add `\"` before and after the file name, it works in Steam but is unusable on the host operating system (the application receives the string `"/file/name"`.

Again like the original issue, simple double-quotes around the file name makes Steam ignore the arguments altogether.

The motivation behind this issue is yuzu-emu/yuzu/pull/6769

**Comment by bertogg** [comment]
Looking at the related issues mentioned in the first comment, I'm not sure that they are all fixed as their status suggests. I'm testing this with the 15 Aug 2022 build of Steam.

Here's one simple .desktop file:

```
$ cat /tmp/FooBar.desktop 
[Desktop Entry]
Type=Application
Name=FooBar
Exec="/home/deck/Desktop/FooBar.sh"
```

```
$ touch /tmp/addnonsteamgamefile
$ xdg-open steam://addnonsteamgame/%2Ftmp%2FFooBar.desktop
```

This results in a new entry in the games library with

Target: `""/home/deck/Desktop/FooBar.sh""`
Start in: `""/home/deck/Desktop"`

(note the that there is four double quotes in the first case and **three** in the second one)

Now, if the shell script contains a space then we would have this the `Exec` line in `FooBar.desktop`:

```
Exec="/home/deck/Desktop/Foo Bar.sh"
```

This results in:

Target: `""/home/deck/Desktop/Foo"`
Start in: `""/home/deck/Desktop"`

(again, look at the number of double quotes).

The launch options are empty in both cases.

**Comment by smcv** [comment]
https://steamcommunity.com/groups/SteamClientBeta/announcements says the new Steam beta on 2023-02-22 had "Fixes for quotes surrounding shortcut exe and paths", which might help this?

**Comment by bertogg** [comment]
I just checked with the Feb 24 2023 build, and this is only partially solved.

```
Exec="/home/deck/Desktop/FooBar.sh"
```

This results in
Target: `"/home/deck/Desktop/FooBar.sh"`
Start in: `"/home/deck/Desktop`

This works, but note the missing double quote at the end (although it doesn't seem to have an effect in practice, i.e. the pwd of the actual process seems correct).

-------

```
Exec="/home/deck/Desktop/Foo Bar.sh"
```

This results in
Target: `"/home/deck/Desktop/Foo`
Start in: `"/home/deck/Desktop`

This does not work.

**Comment by bertogg** [comment]
The `Exec=/path/to/program "/path/to/file"` case also doesn't work, the parameter is ignored if it comes with quotes.

**Comment by TTimo** [comment]
See https://github.com/ValveSoftware/steam-for-linux/issues/9237

**Comment by TTimo** [comment]
We have a few more things to check and fix.

**Comment by TTimo** [comment]
fixed in next beta. we ran into a GIO bug (among other things): https://gitlab.gnome.org/GNOME/glib/-/issues/2930

**Comment by bertogg** [comment]
With the 2 Mar 2023 build:

```
[Desktop Entry]
Type=Application
Name=Foo Bar
Exec="/home/deck/Desktop/Foo Bar.sh" "/tmp/СТИМ ДЕК"
```

The result is:

```
Target: "/home/deck/Desktop/Foo Bar.sh"
Start in: /home/deck/Desktop/
Launch options: "/tmp/СТИМ ДЕК"
```

It seems to work perfectly fine now, thanks!
