### ISSUE TITLE
Launching client open a Wine file browser window

### ISSUE THREAD

**Issue by julienbenjamin** [ValveSoftware/steam-for-linux#8167]
#### System information

* Steam client version (build number or date): Built on Oct 13th 2021
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Issue in as much detail as possible:
Launching the Steam client opens the client as usual but opens a Wine file browser window in `.steam\ubuntu12_32` as well (see screenshot below). This window keeps reopening when closed, as long as the Steam client is launched.

![Screenshot from 2021-10-20 10-18-14](https://user-images.githubusercontent.com/9112511/138055940-7d336ee7-b06a-445c-966d-381c88c99e02.png)

#### Steps for reproducing this issue:

1. Launch Steam Client

**Comment by kisak-valve** [comment]
Hello @julben, this reads like it's related to #8114. Can you tell what version of Proton is running when that window is spawned?
