### ISSUE TITLE
Steam controller desktop configuration layout failing to load correctly on Ubuntu

### ISSUE THREAD

**Issue by w-canvas** [ValveSoftware/steam-for-linux#8191]
#### Your system information

* Steam client version (build number or date): 1634158817 (Oct 13 2021)
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Using steam controller with the wireless dongle and default desktop configuration layout (recommended one)

#### Please describe your issue in as much detail as possible:

Expected behavior: when launching steam client, desktop configuration should be loaded for steam controller.

Actual behavior: when launching steam client, the steam controller's triggers (mouseclicks) stop working. Limiting the functionality of the controller.

To correctly load the configuration a regular mouse needs to be plugged in and, on the gui, click on steam -> settings -> controller -> desktop configuration -> done (sometimes several times). After this the layout loads correctly, but it needs to be redone every time the steam client is launched.

The problem doesn't occur when booting from a windows partition on the same system.

#### Steps for reproducing this issue:

1. Boot Ubuntu
2. Turn on steam controller
3. Launch steam client

**Comment by Komoszek** [comment]
I also experience this issue on Manjaro Linux 21.2rc with SC connected via BLE using both normal and beta branch of Steam (as of 25.12.2021). Launching and immediately exiting Big Picture mode loads desktop config successfully but it's frustraiting.

**Comment by w-canvas** [comment]
> After reconnecting it works just fine.

Turning the controller on, then off, then on again also works. (```guide_button -> guide_button + Y -> guide_button```).

**Comment by Komoszek** [comment]
I've found that this issue also affects DualSence controllers so it's neither ubuntu nor SC specific (it might also affect other controller if not all of them). You might miss it if you have `hid-playstation` module loaded (which is automatically loaded on newer kernels e.g. 5.15 when you connect DualSense controller)

**Comment by Komoszek** [comment]
It no longer happens to me with the newest beta branch (1643850988).

**Comment by w-canvas** [comment]
It doesn't happen to me anymore either after upgrading to the latest beta version.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
