### ISSUE TITLE
Have not-installable games even with "Enable steam play for all other titles"

### ISSUE THREAD

**Issue by sosloow** [ValveSoftware/steam-for-linux#8192]
#### Your system information

* Steam client version (build number or date): oct 29 02:21:34
* Distribution: Ubuntu 21.10
* Opted into Steam client beta?: Yes (turning off doesn't help)
* Have you checked for system updates?: Yes

Recently I updated to a new Ubuntu 21.10, and some time after that, I noticed that some of the games in my library no longer can be installed. The play button of these games is grayed out and has "available for windows" next to it.

I have steam play enables for all game. Why could this problem appear? I always was able to install any game in my library, even if it has "borked" in protondb.

**Comment by kisak-valve** [comment]
Hello @sosloow, this sounds similar to #7404. Maybe try going to `Steam` -> `Settings` -> `Steam Play` -> pick a different Proton version in the `Run other titles with:` drop down list, then pick the Proton version you want to use most often and see if that helps.

**Comment by sosloow** [comment]
@kisak-valve thanks for the tip. I tried to change proton versions there, and I still have the problem.

**Comment by sosloow** [comment]
So, what happened: games that had custom proton version selected got bugged after I upgraded to a new version of ubuntu. I had to re-select that custom version of proton for them, and they appeared as installable.
