### ISSUE TITLE
Steam Overlay is blank (Linux Mint 20.2 Cinnamon)

### ISSUE THREAD

**Issue by RevolverTexture** [ValveSoftware/steam-for-linux#8193]
**System information**

* Steam client version (build number or date): Oct 13 2021
* Distribution (e.g. Ubuntu): Linux Mint 20.2 Cinnamon
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (Driver Manager)

More: https://pastebin.com/raw/fqvstJk8

**Steam Overlay is blank in full screen and window mode**
Image: https://drive.google.com/file/d/1ghc9bOcfYhMcKmJU0gokjd3-s2GvPKLl/view?usp=sharing

**Comment by kisak-valve** [comment]
Hello @RevolverTexture, this issue is already being tracked at #7889. Closing as a duplicate.
