### ISSUE TITLE
Steam client has rendering glitches when running on Prime Render Offload via XWayland with Nvidia driver 495

### ISSUE THREAD

**Issue by MateusRodCosta** [ValveSoftware/steam-for-linux#8194]
#### Your system information

* Steam client version (build number or date): Oct 29 2021
* Distribution (e.g. Ubuntu): Fedora Silverblue 35 (Flatpak)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected no visual glitches, exactly how it would work on Xorg.

Instead, several glitches happen, like flashing elements, some elements are rendered as a black rectangle or as noise.

Those glitches don't happen if Steam is run via Intel on Wayland.

#### Steps for reproducing this issue:

1. Install Nvidia 495 on a Nvidia Optimus system
2. Boot Gnome on Wayland
3. Run Steam via Prime Render Offfload (for example, the "Run in dedicated GPU" option offered via GUI)
4. Glitches should be happening now

An screenshot showing the issue:
![Captura de tela de 2021-10-30 12-45-49](https://user-images.githubusercontent.com/24463334/139540322-9504a5c1-3b88-4407-8ffa-3e20244a9913.png)

**Comment by MateusRodCosta** [comment]
Hi, so actually I found out that there's a bug in the Nvidia driver that causes problems with XWayland: https://forums.developer.nvidia.com/t/glitches-with-nvidia-driver-470-optimus-render-offload-on-xwayland-with-vulkan-games/185278

This bug apparently goes back to 470 series, which I have a vague memory of also reproducing the issue on when I tried the NVidia driver on wayland a while ago.

What I don't know is if this issue I am reporting is just the Nvidia driver bug or if there's also something causing problems on the Steam client.

**Comment by MateusRodCosta** [comment]
Ok, so after further investigation this bug is really solely Nvidia's driver fault.

If I run Steam with the Intel iGPU, no glitches. If I run Blender with the Nvidia dGPU I can also reproduce similar glitches.

Apparently not Valve's fault, but it would be nice if Valve could work with Nvidia to prioritize a fix, seeing as there are several Nvidia Optimus laptops in the market, most of them sold as gamer laptops.

**Comment by morfyum** [comment]
Issue is still on fresh, up to date Fedora 35: [ 2022-02-27 ] 
  - Intel/Nvidia 470.x driver (i5 5200U + 920M)
  - Gnome 41
  - Wayland

Halft window is goin black for a short moment when moving mouse on elements in Default Store page.

**Comment by happyeggchen** [comment]
Solution found
gsettings set org.gnome.mutter experimental-features '["kms-modifiers"]'
I'm playing minecraft and met the same issue on prime-run xwayland, this should work for you guys

**Comment by DeiDo** [comment]
I believe this is caused by this:
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317

**Comment by happyeggchen** [comment]
> I believe this is caused by (or at least related to) this: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317

Yes, I tried to set this as an environment variable then the glitch is fixed, but has a lower frame rate

**Comment by pm4rcin** [comment]
I have a good message. It is no longer a problem since it was fixed in newest driver (I have tested just now). Confirmed by Erik Kurzinger from nvidia [here](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317#note_1589904). :)

**Comment by MateusRodCosta** [comment]
It was fixed for me too, although I have very very rare tearing with games still (even Steam sometimes), but it doesn't bother me as much.
