### ISSUE TITLE
Starting a specific game seems to break overlay / all UI

### ISSUE THREAD

**Issue by frioux** [ValveSoftware/steam-for-linux#8197]
#### Your system information

* Steam client version (build number or date): Oct 13 2021, at 19:47:28
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Tried to start Hades with many different SteamPlay versions (Experimental, 6.3-7, a couple glorious eggroll versions) and many different launch modes (Vulkan, DX, 32 bit) and I always get either what seems like a total interface lockup or (preferably!) a game crash.

I even upgraded from 460 nvidia drivers to 495, and still see the same issue.

Once this occurs the big picture button on the controller no longer seems to do anything and it's as if the screen is off.  I end up ssh'ing into it to reboot it.

#### Steps for reproducing this issue:

1. Try to start Hades?

**Comment by kisak-valve** [comment]
Hello @frioux, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3312#issuecomment-955692610.
