### ISSUE TITLE
Steam runs out of memory after repeatedly opening and closing games

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#8198]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/42655600/139593096-27f2b960-c870-4f26-8060-3770b47067b6.png)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When you repeatedly open and close games with steam, steam eventually runs out of memory. For this I used an `xdotool` script that opens and closes the game N++ constantly.

```
sleep 10
while true
do
    xdotool click 1
    sleep 10
    xdotool key Alt_L+F4
    sleep 10
done
```

Backtrace:
https://gist.github.com/Managor/d44cff392e49cfaaeba81780a8c6a87c

#### Steps for reproducing this issue:

1. Open and close games repeatedly

**Comment by arrowgent** [comment]
can you show memory with
`free -hw`
for each iteration as the memory used increases?

also verify that the application closed
ex:
`ps -AF|grep steam`
if its closed it will not show up here

**Comment by Managor** [comment]
@kisak-valve This can be closed. I am no longer able to reproduce this.
