### ISSUE TITLE
Proton Experimental update fail

### ISSUE THREAD

**Issue by undeadbydawn** [ValveSoftware/steam-for-linux#8199]
Proton Experimental is stuck in a perpetual failed-update loop. This has been happening for 2 full days now.
I've tried everything I can think of, including deleting the current install, uninstalling from Steam (which failed), multiple reboots, using separate instances of Steam, and booting in different kernels. Proton Experimental outright refuses to install properly and goes back to downloading.
I only need it to play GreedFall. If it doesn't install soon I'll have to refund the game.

**Comment by kisak-valve** [comment]
Hello @undeadbydawn, updates to Proton are handled by the Steam client, not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by undeadbydawn** [comment]
Issue resolved.
Experimental was failing to update cos it was still being 'used' by GreedFall. I switched to another Proton, uninstalled PE, reinstalled and relaunched Steam. GreedFall is now fully playable.
