### ISSUE TITLE
Big Picture takes input from the controller while in-game

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#8200]
#### Your system information

* Steam client version: 
![image](https://user-images.githubusercontent.com/42655600/139701316-07cb5996-ebdd-47e4-9c3a-35c9499d88a3.png)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/VXksIC20aeg
Steam Big Picture takes input while in-game. This is not just sounds, but BPM is actually doing something in the background and can for example install or launch games. I have only tested with a steam controller. This problem is not limited to N++, it is just a lightweight game that is fast to restart. There seems to be no clear cut pattern, but there is a trend that if you do not press anything immediately at game start or if you open the configurator before inputting in-game actions, the bug might not happen.

#### Steps for reproducing this issue:

1. Start a game while Steam Controller is on
2. Press the A button on the controller 

### Results
You should hear BPM in the background.

**Comment by TheKarion** [comment]
Still an issue now

**Comment by JustinRamroop** [comment]
Still happening even with new Big Picture Mode aka Steam Deck UI

**Comment by sam-cavalheiro** [comment]
Same here :(

Steam version: 1698185488
OS: Arch Linux

**Comment by Managor** [comment]
@kisak-valve I believe this can be closed. It's for the old BPM.

**Comment by kisak-valve** [comment]
Closing per the last comment.
