### ISSUE TITLE
Steam Controller mouse input does not work correctly in desktop mode under Wayland

### ISSUE THREAD

**Issue by pobtott** [ValveSoftware/steam-for-linux#8205]
#### Your system information

* Steam client version (1634158817): 
* Distribution (Ubuntu 21.10): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:

When steam launches and Steam Controller uses desktop configuration mouse input stop working.

Tried with a fresh install of Ubuntu 21.10
Stream Controller works as expected in lizard mode.
Input under big picture mode seems to work correctly.

Starting the system with X instead of Wayland resolves the issue.

#### Steps for reproducing this issue:

1. Boot system with Wayland
2. Launch Steam
3. Start Steam Controller

**Comment by kisak-valve** [comment]
Hello @pobtott, this issue was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/4738#issuecomment-271682124 and most likely related to https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/431.
