### ISSUE TITLE
Running Steam with virgl gives glXChooseVisual failed

### ISSUE THREAD

**Issue by DUOLabs333** [ValveSoftware/steam-for-linux#8207]
#### Your system information

* Steam client version (build number or date): `Startup - updater built Oct 13 2021 19:47:06`
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I'm using virgl as my GPU. Because of unrelated library issues, I'm running `LD_LIBRARY_PATH=/home/system/.local/share/Steam/ubuntu12_32:/home/system/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/system/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu /home/system/.local/share/Steam/ubuntu12_32/steam
`. However, when it starts, it just fails with 
```
/home/system/Downloads/WINE/bin/sh: line 1: lspci: No such file or directory
Fontconfig warning: line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Installing breakpad exception handler for appid(steam)/version(1634158817)
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
glXChooseVisual failed
glXChooseVisual failedsrc/steamUI/Main.cpp (409) : Assertion Failed: Fatal Error: glXChooseVisual failed
src/steamUI/Main.cpp (409) : Assertion Failed: Fatal Error: glXChooseVisual failed
Installing breakpad exception handler for appid(steam)/version(1634158817)
DBG DBG ffffffff DUMP_REQUESTED Assert( Assertion Failed: Fatal Error: glXChooseVisual failed ):/data/src/steamUI/Main.cpp:409

No minidump written, nothing to upload.
```

#### Steps for reproducing this issue:
This might not be reproducable, but
1. Make a QEMU virtual machine with the virgl GPU with the Arch operating system.
2. Download `http://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz` and unpack it
3. Run the command above

**Comment by kisak-valve** [comment]
Hello @DUOLabs333, in general, Steam needs libc from the host system (from your virtual machine's environment in this context) and a sane 32 bit and 64 bit OpenGL render path.

Can you check that your render stack is healthy with something like `glxinfo32` from `lib32-mesa-demos` and `glxinfo` from `mesa-demos`? Also, if you're using Arch in QEMU, you may have better results using Arch's distro packaging of Steam instead of a manually unpacked client.

**Comment by DUOLabs333** [comment]
Both give normal results -- `virgl` for both. Is there something specific I'm supposed to be looking  for?

**Comment by DUOLabs333** [comment]
Using Arch's version yield's the same results.
