### ISSUE TITLE
Feature request proton launch flags through GUI

### ISSUE THREAD

**Issue by JibbityJobbity** [ValveSoftware/steam-for-linux#8209]
#### Your system information

* Steam client version (build number or date): Oct 13 2021, at 19:47:24
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Description

This is a **feature request** to help usability.

Several [launch flags for Proton](https://github.com/ValveSoftware/Proton/#runtime-config-options) are done through manually typing launch options. It is not intuitive to apply certain fixes and the current compatibility menu is bare. Manually typing launch options could lead to users forgetting to type `%command%`.
Proposing selectable options under the compatibility tab in a game's properties and buttons to browse or clear the wineprefix. Worth noting to be conscious about conflicts with manually typed options.

#### Steps for reproducing this issue:

1. Navigate to library
2. Right click a game
3. Properties...
4. Compatibility

![image](https://user-images.githubusercontent.com/37820565/140628682-94d43e4f-5de2-4221-912b-e9f15a3bb394.png)

**Comment by kisak-valve** [comment]
Hello @JibbityJobbity, this feature request is already being tracked at #7165. Closing as a duplicate.
