### ISSUE TITLE
Steam Link virtual keyboard sometimes crashes the raspberrypi's streaming process and freezes it.

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/steam-for-linux#8210]
#### Your system information

* Steam client version (build number or date): Nov 05 2021
* Distribution (e.g. Ubuntu): openSUSE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Sometimes, bringing up the Steam Link virtual keyboard crashes the Steam Link stream process and freezes the stream, but the host's program continues running. Only way out is to ssh into my raspberrypi and kill it. It doesn't seem to happen on the AppleTV Steam Link app, though. Unfortunately I haven't tested it as much as the pi's because the AppleTV app is garbage for non-technical issues way beyond Valve's control.

#### Steps for reproducing this issue:

1. Launch Steam Link on the raspberrypi
2. Press the Steam Link guide button on a controller to bring up the Steam Link stream menu
3. Activate the on screen keyboard by pressing the "show virtual keyboard" button
4. Sometimes this will make the raspberry steam link application to crash.

This has happened across all my the host's distros I've used: Ubuntu, Kubuntu, Solus and openSUSE.

**Comment by kisak-valve** [comment]
Hello @lavadrop, Steam Link for Raspberry Pi specific issues are not tracked here. Feel free to use https://steamcommunity.com/app/353380/discussions/6/ for feedback with that application.
