### ISSUE TITLE
realloc() error while trying to start Steam

### ISSUE THREAD

**Issue by Develon5543** [ValveSoftware/steam-for-linux#8220]
#### Your system information

* Steam client version (build number or date): Unknown (Tried beta and normal clients)
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: Yes and No
* Have you checked for system updates?: Yes
* GPU and GPU driver: AMD RX5700XT using AMDGPU
* CPU: AMD Ryzen 9 3900XT

#### Please describe your issue in as much detail as possible:
When running Steam, it will not open past the updater. Here's the output log from the terminal.
```
Running Steam on arch rolling 64-bit
STEAM_RUNTIME is enabled automatically
Steam runtime environment up-to-date!
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/develon/.local/share/Steam/ubuntu12_32/steam
[2021-11-09 23:04:40] Startup - updater built Jul 20 2021 22:25:51
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
realloc(): invalid pointer
crash_20211109230440_1.dmp[49268]: Uploading dump (out-of-process)
/tmp/dumps/crash_20211109230440_1.dmp
crash_20211109230440_1.dmp[49268]: Finished uploading minidump (out-of-process): success = yes
crash_20211109230440_1.dmp[49268]: response: CrashID=bp-d6e6a25e-14a4-4eba-a0f0-c2acb2211109
crash_20211109230440_1.dmp[49268]: file ''/tmp/dumps/crash_20211109230440_1.dmp'', upload yes: ''CrashID=bp-d6e6a25e-14a4-4eba-a0f0-c2acb2211109''
/home/develon/.local/share/Steam/steam.sh: line 772: 49236 Aborted                 (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
```
Here's that minidump too if it helps. 
[crash_20211109230440_1.zip](https://github.com/ValveSoftware/steam-for-linux/files/7510584/crash_20211109230440_1.zip)

#### Steps for reproducing this issue:

1. Type `steam` or `steam-runtime` from the terminal.

**Comment by kisak-valve** [comment]
Hello @Develon5543, for reference, the attached minidump is a SIGABRT in linux-gate.so coming from libLLVM-14git.so. This looks like a duplicate of #8202. Can you confirm that you're also using the `mesa-git` package?

**Comment by Develon5543** [comment]
Hi, @kisak-valve. You are correct, this is a duplicate of #8202. Sorry for the noise! I'll be sure to follow the thread there.
