### ISSUE TITLE
Dropdown UI Element Leaves Persistent Ghost

### ISSUE THREAD

**Issue by Draco18s** [ValveSoftware/steam-for-linux#8221]
#### Your system information

* Steam client version (build number or date): Oc 13, 2021
* Distribution (e.g. Ubuntu): Pop!OS (Ubuntu) 21.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Used a dropdown menu when making a new Steam Community discussion thread, the dropdown did not disappear after selecting an option and persisted after exiting steam and restarting Gnome.

#### Steps for reproducing this issue:

Note: issue may be intermittent

1. Start a new discussion thread
2. Use the dropdown to change the target section

![Screenshot from 2021-11-08 22-53-58](https://user-images.githubusercontent.com/1750680/141170317-8a898470-6b91-40fb-8be3-ab44495903e2.png)

**Comment by kisak-valve** [comment]
Hello @Draco18s, this issue was already evaluated at #7825 and should be resolved in Steam's client beta. Closing in favor of the older issue report.
