### ISSUE TITLE
Steam Client Beta crashing on Arch Linux (realloc(): invalid pointer)

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#8223]
#### Your system information

* Steam client version (build number or date): Unsure, unable to check
* Distribution (e.g. Ubuntu): Arch Linux with KDE Plasma Wayland
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, occurred after system update last night,

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I expected the Steam client to open normally.

When opening Steam normally (e.g., from Application Launcher), nothing happens. When running from terminal, I can see "realloc(): invalid pointer" followed by information about crash dumps.

```
crash_20211110205254_2.dmp[3646]: Uploading dump (out-of-process)
/tmp/dumps/crash_20211110205254_2.dmp
/home/username/.local/share/Steam/steam.sh: line 794:  3630 Aborted 
```

I'm running mesa-git and a Plasma Wayland session.

#### Steps for reproducing this issue:

Trying to launch Steam is enough for the issue to occur.

**Comment by kisak-valve** [comment]
Hello @sonic2kk, this was (offtopic) discussed on #8202, and is a regression in llvm 14 git. This is not a Steam issue, report it to your video driver vendor if it hasn't been already.
