### ISSUE TITLE
Age verification dropdown won't go away until Steam is closed

### ISSUE THREAD

**Issue by andrewdbanks** [ValveSoftware/steam-for-linux#8227]
#### Your system information

* Steam client version (build number or date): 1634158817, Oct 13 2021, at 19:47:24
* Distribution (e.g. Ubuntu): Kubuntu 21.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When reaching an age verification check, the dropdown box for the month selection will stick around until I quit Steam. I'm on Kubuntu 21.10. I can switch workspaces, minimize the window, etc., and this dropdown box will still be on the screen until I close Steam. See attached images. To reproduce, I just navigated to the Grand Theft Auto V store page, and it prompted me for my birth date. I set the month, and now I've got this box here until I quit Steam.

#### Steps for reproducing this issue:

1. Navigate to the Grand Theft Auto V store page.
2. Select a valid birth date using the dropdown boxes; I changed the month.
3. Navigate anywhere else in the Steam client after submitting the page.

![image](https://user-images.githubusercontent.com/12224041/141534468-e4567cc9-abb6-4947-b832-54948c4a07c2.png)

**Comment by kisak-valve** [comment]
Hello @andrewdbanks, this issue was already evaluated at #7825 and should be resolved in Steam's client beta. Closing in favor of the older issue report.
