### ISSUE TITLE
Age verification in non big picture mode

### ISSUE THREAD

**Issue by Brad7173** [ValveSoftware/steam-for-linux#8228]
#### Your system information
----
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 20.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-90-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12011000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20210906.1

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 470.82.00
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1360 x 768
    Desktop Resolution: 5198 x 1080
    Primary Display Size: 18.11" x 10.24" (20.79" diag)
                                            46.0cm x 26.0cm (52.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 80 HDMI/DP

Memory:
    RAM:  31806 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  937366 Mb
    Largest Free Hard Disk Block:  692660 Mb

Storage:
    Number of SSDs: 0
    SSD sizes: %s1
    Number of HDDs: 0
    HDD sizes: %s1
------

* Steam client version (build number or date): 
Steam Client Application
Built: Oct 13 2021, at 19:47:24
Steam API: v020
Steam package versions: 1634158817

* Distribution (e.g. Ubuntu): 
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-90-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
Memory: 31.1 GiB of RAM

* Opted into Steam client beta?: [Yes/No]
Forced to opt out after Nov 11, 2021 update bugs.

* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

In normal mode not big picture mode there is a problem with age verification. It has 3 drop down menus for day, month and year. One of them always remains open even after clicking the button to continue. Unless I completely exit steam it remains open. It does not do this in big picture mode using a joystick. The problem is some aspects of steam are not available in big picture mode such as cart. It is difficult to get to.
#### Steps for reproducing this issue:

1. Open steam in normal mode. (not big picture)
2. Attempt to open any game from store that requires age verification.
3. 
![image](https://user-images.githubusercontent.com/94210825/141605289-6c1237e0-9596-47fb-9748-d9abde72d3b9.png)
![image](https://user-images.githubusercontent.com/94210825/141605306-755baac5-2553-4d97-9034-7eccd0000990.png)
![image](https://user-images.githubusercontent.com/94210825/141605312-bcf53107-7b99-462b-b913-83e0e669c749.png)

**Comment by Brad7173** [comment]
The Nov 11, 2021 issue was steam not exiting. (1) I was having to open task manager and send a kill signal. It would go to the tray and then when opening the tray menu and 'Exit' it would remain open. (2) After my joysticks working flawlessly (Afterglow xbox 360 controller), (shanwan chinese x360 clone with turbo), (Buffalo BSGP1601BK gamepad) for a week they started on a continuous loop of being detected then not detected.

**Comment by Brad7173** [comment]
I am BEGGING you PLEASE fix this!! I have watched update after update hoping and waiting for this to get fixed.

**Comment by kisak-valve** [comment]
Hello @Brad7173, this issue was already evaluated at #7825 and should already be resolved in the Steam client beta. The second issue you mentioned is being tracked at #8226. Closing in favor of the older issue reports.
