### ISSUE TITLE
HL1 spawns window on left-most screen, not primary screen

### ISSUE THREAD

**Issue by Tele42** [ValveSoftware/steam-for-linux#823]
I have a secondary monitor to the left setup with nVidia graphics and HL1 launches and plays on the left monitor only, which is ergonomically unsuitable for gaming. Having choice as to which monitor to use would be ideal.

> Processor Information:
>    Vendor:  AuthenticAMD
>    Speed: 3600 Mhz
>    8 logical processors
>    8 physical processors
>    HyperThreading:  Unsupported
>    FCMOV:  Supported
>    SSE2:  Supported
>    SSE3:  Supported
>    SSSE3:  Supported
>    SSE4a:  Supported
>    SSE41:  Supported
>    SSE42:  Unsupported
> 
> Network Information:
>    Network Speed:  
> 
> Operating System Version:
>    "Gentoo Base System release 2.1" (64 bit)
>    Kernel Name:  Linux
>    Kernel Version:  3.6.11-gentoo
>    X Server vendor:  The X.Org Foundation
>    X Server release:  11301000
> 
> Video Card:
>    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2
> 
>    Driver Version:  4.3.0 NVIDIA 313.18
>    Desktop Color Depth: 24 bits per pixel
>    Monitor Refresh Rate: 60 Hz
>    VendorID:  0x10de
>    DeviceID:  0xe22
>    Number of Monitors:  2
>    Number of Video Cards Not Detected
>    Primary Display Resolution:  1920 x 1080
>    Desktop Resolution: 3840 x 1080
>    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
>                                            50.9cm x 28.6cm  (58.3cm diag)
>    Primary Bus: PCI Express 16x
>    Primary VRAM: 1024 MB
>    Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>    Audio device: Loopback Mixer
> 
> Memory:
>    RAM:  16035 Mb
> 
> Miscellaneous:
>    UI Language:  English
>    LANG:  en_US.UTF-8
>    Microphone:  Not set
>    Total Hard Disk Space Available:  905512 Mb
>    Largest Free Hard Disk Block:  49214 Mb
> 
> Installed software:
> 
> Recent Failure Reports:
>    Tue Jan 22 02:42:31 2013 GMT: file ''/tmp/dumps/assert_20130121214230_1.dmp'', upload yes: ''CrashID=bp-b3613bcc-4f59-4157-81f7-90ad02130121''
>    Wed Jan 23 00:46:23 2013 GMT: file ''/tmp/dumps/assert_20130122194621_1.dmp'', upload yes: ''CrashID=bp-cccc792b-0780-4a48-aeae-3f5fe2130122''
>    Thu Jan 24 00:42:12 2013 GMT: file ''/tmp/dumps/assert_20130123194210_1.dmp'', upload yes: ''CrashID=bp-a96aa96a-717e-4522-bbd5-e089e2130123''
>    Thu Jan 24 01:14:10 2013 GMT: file ''/tmp/dumps/assert_20130123201408_1.dmp'', upload yes: ''CrashID=bp-952c1506-23c4-4f5b-b9aa-c14b32130123''
> Edit: "fix" code block

**Comment by KeebWasTaken** [comment]
Getting this issue 10 years later on gnome wayland. This is some history right here

**Comment by Mart-Bogdan** [comment]
Same here, on KDE + xorg

But running game with Proton resolves this.

**Comment by Blisterexe** [comment]
i am also getting this issue on gnome wayland

**Comment by kisak-valve** [comment]
Please use the ValveSoftware/halflife issue tracker for feedback on Halflife 1.
