### ISSUE TITLE
Steam client is sluggish or does not respond with browser on dual-screen desktop

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/steam-for-linux#8230]
#### Your system information

* Steam client version (build number or date): 13.10.2021 19:47:24
* Distribution (e.g. Ubuntu): Debian/testing
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While running Steam client and browser in a dual-screen with Gnome (v 41 with Wayland) Steam client might not respond inputs or it might be very sluggish in the response. This might be a bug in Gnome, but it might be something in the Steam client as I don't recall seeing anything else with similar problems.

There are different ways the issue manifests: mouse cursor is using wrong style in wrong position ("edge adjust" while in the middle of top bar), the Steam window might not respond to attempts to move it, trying to scroll content in Steam client might be very sluggish or not respond at all.

Sometimes it is enough to simply run a browser on another screen (Chromium) or having it display a video (Firefox) is required to trigger the issue. Playing video as fullscreen can trigger the problem in Steam client if other steps don't.
Firefox ESR (78), Chromium 93 use X11 (through XWayland) as does Steam client (according to xlsclients).

Speculation: Component used by browsers (video/GPU?) might be somehow interfering and/or UI toolkit in Steam might stop rendering if it assumes another window has priority for some reason? (Not detecting different screen and no overlap?) 
Or input is not passed through correctly? (There has been articles describing issues that browsers with multiple components had with inputs under X11 somewhere..)

#### Steps for reproducing this issue:

1. Start Steam client on second screen
2. Start browser (Chromium, Firefox) on first screen, have Firefox play a video (Youtube), make video fullscreen
3. Try to drag and move Steam client window position in the second screen, try to scroll content. Observe that mouse cursor can be wrong for the location it is hovering over.

**Comment by kisak-valve** [comment]
Hello @ipr, this issue is already being tracked at #7245. Closing as a duplicate.
