### ISSUE TITLE
Steam won't launch on hybrid GPU system

### ISSUE THREAD

**Issue by ffortunato60** [ValveSoftware/steam-for-linux#8233]
#### Your system information
HP - Gaming Pavilion 15-ec1001sl Notebook, AMD Ryzen 5, RAM 8 GB, SSD 512 GB, NVIDIA GeForce GTX 1650Ti 4 GB

* Steam client version (build number or date): 1.0.0.61-2ubuntu3
* Distribution (e.g. Ubuntu): Ubuntu 20.04.2 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Steam installed correctly (either from Ubuntu Rep and Steam website). When I try to launch it from the App icon it does the updates, then nothing happens.
When I launch it from the terminal I receive the following info:
[gistfile1.txt](https://github.com/ValveSoftware/steam-for-linux/files/7534204/gistfile1.txt)

The command "STEAM_RUNTIME=0 steam" from terminal provides this answer:
You are missing the following 32-bit libraries, and Steam may not run: 
libXtst.so.6 
libXrandr.so.2 
libXrender.so.1 
libXi.so.6 
libgobject-2.0.so.0 
libglib-2.0.so.0 
libgio-2.0.so.0 
libgtk-x11-2.0.so.0 
libpipewire-0.3.so.0 
libgdk_pixbuf-2.0.so.0 
libva.so.2 
libbz2.so.1.0 
libva-drm.so.2 
libva.so.2 
libva-x11.so.2 
libvdpau.so.1

The majority of these files are present in the directory /usr/lib/x86_64-linux-gnu/ in my system.

I verified that the system includes 32 bit support with the following:
dpkg --print-foreign-architectures
answer:
i386

All other games and software outside Steam work fine, using the Nvidia GPU.
If I disable the Nvidia GPU from NVIDIA Server Settings (PRIME Profile Intel - Power Saving Mode) Steam launches correctly and works fine. How can I have it work with the NVIDIA GPU??

#### Steps for reproducing this issue:

1. Install Ubuntu 20.04.2 LTS
2. Install Steam from Ubuntu Software app or from Steam website
3. Try to launch Steam with App icon or from Terminal

**Comment by kisak-valve** [comment]
Hello @ffortunato60, disabling the Steam runtime is not supported, and comparing missing 32 bit libraries to their 64 bit counterparts is an incompatible and irrelevant comparison.

Ignoring that and focusing on your main issue, the nVidia proprietary driver requires that nVidia's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version to work properly. Your log hints that you're missing nVidia's 32 bit userspace libraries. Please figure out what nVidia driver series you're using, then check if the 32 bit userspace libraries for that driver series is installed with something like `apt policy libnvidia-gl-470:i386` (replacing 470 with the driver series you want to use) and install it if it is missing.

It should be noted that starting with the Valve-provided 1.0.0.73 steam package tries to detect this situation on Ubuntu and requests that the user install the needed video driver package.

**Comment by ffortunato60** [comment]
Hi @kisak-valve, thanks for your answer. Sorry and apologize for my irrelevant comparison. Just trying to learn Linux and confused the corresponding libraries. Not sure to understand your comment about disabling the Steam runtime though.
I am using Nvidia driver series 470.82.00 and the command you indicated produces the following result on the terminal:
franco@franco-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~$ apt policy libnvidia-gl-470:i386
libnvidia-gl-470:i386:
  Installato: (nessuno)
  Candidato:  470.82.00-0ubuntu0.20.04.1
  Tabella versione:
     470.82.00-0ubuntu0.20.04.1 500
        500 http://it.archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages
What shall I do?
Thanks again for your assistance,
Franco

**Comment by kisak-valve** [comment]
I read `Installato: (nessuno)` in that as the 32 bit userspace package is not installed, so the next step would be to install it with `sudo apt install libnvidia-gl-470:i386` and retest.

**Comment by ffortunato60** [comment]
@kisak-valve you are the best!!!! Finally works! It was three days I was messing up and browsing all web pages and forums. Thank you very much, you made my day!
