### ISSUE TITLE
Support for nvidia drivers 390+ (470, 495, etc)

### ISSUE THREAD

**Issue by MOZGIII** [ValveSoftware/steam-for-linux#8238]
As can be seen at https://www.nvidia.com/en-us/drivers/unix/, NVIDIA doesn't ship 32-bit builds anymore. Why does steam refuse to run if I don't have 32-bit video libs? Doesn't make sense. Am I supposed to use old drivers with steam?

**Comment by kisak-valve** [comment]
Hello @MOZGIII, your claim that nVidia does not support 32 bit applications is factually wrong. nVidia has dropped support for 32 bit kernels, but not 32 bit applications on 64 bit systems. Depending on how your distro packages the nVidia driver, the distro packaging may let you install the video driver's 64 bit userspace libraries without also requiring the driver's 32 bit counterpart.

For example, on an Ubuntu system with the nvidia 470 series video driver, the `libnvidia-gl-470:i386` package contains the 32 bit userspace libraries for that series of driver, but nothing directly depends on it in the package manager's dependency tree and it can get missed.
