### ISSUE TITLE
Can't uninstall Proton 6.3-7

### ISSUE THREAD

**Issue by Gorkido** [ValveSoftware/steam-for-linux#8239]
## System Information

- GPU: RX 580
- Distribution: Arch Linux (EndeavourOS)
- Steam pkg: steam-native-runtime
- Driver version: amdgpu
- Kernel version: 5.15.2-arch1-1
- Proton version: 6.3-7

## I confirm:

- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms

Can't uninstall Proton..
![image](https://user-images.githubusercontent.com/81165187/142227822-3e8ec77e-3732-4d90-b067-2d562ebb7946.png)

## Additional Info

i opened steam with `steam` and here is the output:

GameAction [AppID 1580130, ActionID 2] : UninstallApps continues with user response "ConfirmUninstall"
GameAction [AppID 1580130, ActionID 2] : UninstallApps changed task to StartNextApp with ""
GameAction [AppID 1580130, ActionID 2] : UninstallApps changed task to StopDownloading with ""
GameAction [AppID 1580130, ActionID 2] : UninstallApps changed task to InstallScript with ""
GameAction [AppID 1580130, ActionID 2] : UninstallApps changed task to RemoveFromOS with ""
GameAction [AppID 1580130, ActionID 2] : UninstallApps changed task to WaitRunning with ""
Cannot uninstall compatibility tool 1580130 "Proton 6.3-7" because the following application(s) depend on it:
GameAction [AppID 1580130, ActionID 2] : UninstallApps failed with AppError_17 with ""

## What i've done to fix it (didn't work ofc)
Uninstalled steam-native-runtime > deleted "~/.steam/steam/steamapps/common/Proton 6.3" > deleted steam caches > installed other versions of proton and deleted other versions(other versions can be deleted)

**Comment by kisak-valve** [comment]
Hello @Gorkido, the uninstall process of Proton and checking if any games are configured to depend on a specific version Proton is managed by Steam, not Proton itself, so I've gone ahead and transferred this issue report to the Steam client issue tracker.

**Comment by Gorkido** [comment]
> Hello @Gorkido, the uninstall process of Proton and checking if any games are configured to depend on a specific version Proton is managed by Steam, not Proton itself, so I've gone ahead and transferred this issue report to the Steam client issue tracker.

Thanks @kisak-valve

**Comment by arrowgent** [comment]
there needs to be a better tool which displays all the games that proton is configured to use

i have 400 games installed each with different versions of proton selected


>> alternatively delete the proton folder and dont allow it to update.

**Comment by Gorkido** [comment]
> there needs to be a better tool which displays all the games that proton is configured to use
> 
> i have 400 games installed each with different versions of proton selected
> 
> > > alternatively delete the proton folder and dont allow it to update.

How am i supposed to not allow it to update?

![image](https://user-images.githubusercontent.com/81165187/142232911-bef07f3a-e3ca-4752-939f-89841f2e3b5e.png)

**Comment by Gorkido** [comment]
Issue solved.
Fix: Start steam from a terminal and try to delete proton. You'll see some games just like this 
![image](https://user-images.githubusercontent.com/81165187/142946810-dc7771b5-173b-48b2-b215-7991adf3126a.png)
just untick "Force the use of a specific Steam Play compatibility tool" like this
![image](https://user-images.githubusercontent.com/81165187/142946935-9e917347-a7bb-4473-bc6c-54c21289f19f.png)
Done.
