### ISSUE TITLE
Raspberry Pi OS - Steam Link Installation

### ISSUE THREAD

**Issue by Qerxxx** [ValveSoftware/steam-for-linux#8242]
#### Your system information

* Steam client version (build number or date): Steam Link
* Distribution (e.g. Ubuntu):  Raspberry Pi OS
* Opted into Steam client beta?: [Yes/No] 
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

Hi SteamSupport
I have a problem with installing Steam Link on Raspberry Pi 4 (4gb ram)
When starting the application on Raspberry
the following message appears and nothing else happens.

pi@raspberrypi:~ $ steamlink
Package libgcc1:armhf needs to be installed
Steam needs to install these additional packages:
libgcc1:armhf
...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libgcc-s1' instead of 'libgcc1'
libgcc-s1 is already the newest version (10.2.1-6+rpi1).
The following package was automatically installed and is no longer required:
libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Press return to continue:

Before, I used the app and it was OK.
The problem appeared after installing (on a new SD card) the entire system - Raspberry Pi OS (32-bit)

Troubleshoot what has been done:
- reformatting the SD card and installing a new version of the system
- checking available updates for the repository
- reinstalling SteamLink
- installation of the BETA version (Steam Link version 1.1.86 BETA)
https://steamcommunity.com/app/353380/discussions/6/3155328676444853525/

still the same problem

Summary:
New SD card
New clean, official system without any extensions

**Comment by joeknock90** [comment]
Interesting to see if this works. 

Change the line in ````~/.local/share/SteamLink/steamlinkdeps.txt```` that looks for libgcc:armhf to libgcc-s1:armhf

**Comment by kisak-valve** [comment]
Hello @Qerxxx, this issue tracker is for the desktop Steam for Linux client. Please use https://steamcommunity.com/app/353380/discussions/6/ for issues with Steam Link for Raspberry Pi.
