### ISSUE TITLE
Humankind demo not downloadable for Proton

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/steam-for-linux#8244]
#### Your system information

* System info: https://paste.ubuntu.com/p/vnvGSnpy7w/

#### Please describe your issue in as much detail as possible:
I'd like to download the Humankind demo to play with Proton, but I'm not able to:

![image](https://user-images.githubusercontent.com/110988/142708449-7adce6f1-c1d2-4342-9e71-cacc7ad0a034.png)

**Comment by kisak-valve** [comment]
Hello @vadi2, this issue is already being tracked at #7877. Closing as a duplicate.
