### ISSUE TITLE
Steam wont start

### ISSUE THREAD

**Issue by KREATIV-LSH** [ValveSoftware/steam-for-linux#8247]
#### Your system information

* Steam client version (build number or date): Nov 19 2021(not sure how to retrieve this correctly)
* Distribution (e.g. Ubuntu):  Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After downloading steam and starting it it crashes and only shows the update window for 1 second.
Output: https://gist.github.com/KREATIV-LSH/95e4a0d0bb347839a1010c8ef52372d0

#### Steps for reproducing this issue:

1. Download steam with `sudo apt install  steam`
2. Check for updates and update
3. launch steam

**Comment by kisak-valve** [comment]
Hello @KREATIV-LSH, `swrast` is mesa's slower cpu renderer. The fact that Steam is trying to use it hints that you're using the nVidia proprietary driver and are missing the driver's 32 bit userspace libraries. Figure out which driver series you're using, and add the 32 bit userspace libraries with something similar to `sudo apt install libnvidia-gl-470:i386` (replace 470 with the driver series you're using).

**Comment by KREATIV-LSH** [comment]
Thanks man!
Works now!
