### ISSUE TITLE
10 bit colour crashes steam with nvidia.

### ISSUE THREAD

**Issue by LethalManBoob** [ValveSoftware/steam-for-linux#8252]
im on the latest steam beta with arch.
Anyone can test this with enabling 10 bit colour (sudo nvidia-settings if it wont save xorg.conf)
typing steam into the terminal and the log should provide everything.
This has been an issue since march.

**Comment by kisak-valve** [comment]
Hello @LethalManBoob, this issue is already being tracked at #4399. Closing as a duplicate.
