### ISSUE TITLE
Steam creating infinite instances of explorer.exe /desktop until RAM/CPU are maxed out, requiring a hard reboot.

### ISSUE THREAD

**Issue by SeraphisCain** [ValveSoftware/steam-for-linux#8255]
#### Your system information

* Steam client version (build number or date): Nov 22 2021, at 22:12:42
* Distribution (e.g. Ubuntu): Pop_OS 21.04, issue was also present on Linux Mint 20 before switching distros.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Within 30-60 seconds of Steam being opened, infinite instances of explorer.exe /desktop spawn until RAM is full, CPU is at 100%, and system freezes, necessitating a hard reboot. Processes point toward `steamapps/compatdata/0`. Deleting the `0` prefix folder temporarily fixes it, but on next boot Steam re-creates the folder. Workaround is making the `compatdata` folder read-only so Steam can't re-create the folder, which is feasible for me since all my game prefixes are on a separate drive, but may not be feasible for others. This issue only started yesterday, and there's a thread on the Steam Play Reddit of a few other people also experiencing it.

#### Steps for reproducing this issue:

Simply run Steam and wait.

**Comment by kisak-valve** [comment]
Hello @SeraphisCain, this reads like #8114, but the proton instances should be short lived. can you tell what Proton version is being run when this happens? Also, do you have third party builds of Proton installed?

**Comment by SeraphisCain** [comment]
@kisak-valve I *think* it's Proton 6.3 that's being run, but I'm not 100% on that. And I do have 4-5 GE builds of Proton installed, yes. I just triggered the issue again to see if I could figure out which Proton version was being run, but my system went unstable before I could figure it out.

**Comment by zeddidragon** [comment]
Deleting Glorious Eggroll seems to have solved it for me as well. Would've never thought of that!

**Comment by kisak-valve** [comment]
Thanks for checking @SeraphisCain, The Steam client update exposed a previously hidden quirk of older third party Proton builds. This is not something that should be solved on Valve's side.

Closing in favor of the older issue report.

**Comment by mkrupczak3** [comment]
bump
