### ISSUE TITLE
Steam is too small on HiDPI displays

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/steam-for-linux#8256]
Steam on a device like the OneXPlayer (similar to the Steam Deck) is too small to make use of without having to use GDK_SCALE=2 as a launch argument. The setting in steam that "Scale text and icons to match monitor settings" does nothing to resolve this issue. Steam is also not effected by scaling Settings within gnomes display options. As far as I know this is a widespread issue among all distros.

**Comment by kisak-valve** [comment]
Hello @ruineka, this issue is already being tracked at #7020. Closing as a duplicate.
