### ISSUE TITLE
Steam UI is broken with AMD proprietary graphics

### ISSUE THREAD

**Issue by RoboMage** [ValveSoftware/steam-for-linux#8264]
#### Your system information

* Steam client version (build number or date):  Latest (can't read number)
* Distribution (e.g. Ubuntu):  Pop!Os 21.04
* Opted into Steam client beta?: (Tried both)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Using the AMD proprietary graphics drivers for Linux causes Steam to render incorrectly. Games running in proton also suffer the same issue. 
The prop drivers are required for some applications to run correctly (i.e. SideFX Houdini, Substance Designer, etc), and everything else on the system is behaving correctly. In the context of my current system, this rendering issue is unique to Steam.

![steam](https://user-images.githubusercontent.com/27884887/143400827-0dba4da0-2677-4226-a643-5d77a88183c2.png)

#### Steps for reproducing this issue:
1.  Install amd proprietary graphics https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-21-40-1
2.  Set usecase during install to workstation
3.  Open Steam

**Comment by kisak-valve** [comment]
Hello @RoboMage, this reads like a video driver issue and should also be reported to the video driver vendor.

**Comment by RoboMage** [comment]
Alright, I opened an issue with AMD as well. (Hopefully in the right spot)
https://gitlab.freedesktop.org/drm/amd/-/issues/1810

**Comment by RoboMage** [comment]
Issue is caused specifically by the --usecase=workstation flag when installing the graphics driver. Omitting it resolves issue. Details here: https://gitlab.freedesktop.org/drm/amd/-/issues/1810#note_1169750
