### ISSUE TITLE
Steam Link/Streaming not working on Wayland

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/steam-for-linux#8271]
I'm not sure if this is a bug or not implemented yet, but either way it's not working and it only appears as a black screen using a AMD 6700 XT. I hope Wayland support is in the works for this.

**Comment by ruineka** [comment]
SteamPlay remote play does work on Wayland by the way. I was playing Tekken 7 with my brother using this feature.

**Comment by kisak-valve** [comment]
Hello @ruineka, this issue is already being tracked at #6148. Closing as a duplicate.
