### ISSUE TITLE
Gyro input on Switch Pro controller and controllers using the same protocol does not work.

### ISSUE THREAD

**Issue by hperrin** [ValveSoftware/steam-for-linux#8273]
#### Your system information

* Steam client version (build number or date): "Built: Nov 22 2021, at 22:12:42", but this has been happening for a month or so.
* Distribution (e.g. Ubuntu): I've tested on Manjaro and Ubuntu. It probably affects all distributions.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since about a month ago (maybe longer, I can't remember), the gyro on Switch Pro controllers and controllers that use the same protocol (8BitDo SN30 Pro+ and 8BitDo Pro 2 are the ones I've tested) isn't recognized by Steam in Linux. I have the gyro set up to emulate a mouse or a mouse joystick in several games, and they only work in Windows right now. The same controller configuration doesn't work in Linux.

After I've calibrated the controller's gyro in Windows, and reconnected the controller in Linux, Steam's desktop controller configuration will recognize the gyro input (and move the mouse on the screen) until I launch a game, then, again, the gyro input is not recognized.

I have tried this on multiple Windows and Linux machines. Gyro controls work in Windows 10 Home and Pro on the three computers I've tried. Gyro controls do not work in Linux on the four computers (including two of the same computers that do work with Windows) I've tried. This includes both Manjaro Linux and Ubuntu Linux, with various different (recent) kernel versions.

This is most definitely a problem with Steam on Linux, since the exact same setups worked in every case until a recent Steam update, where it broke on every single Linux PC I play on.

#### Steps for reproducing this issue:

1. Connect a Switch Pro controller to Steam on Linux.
2. Set up a game to use the gyro as mouse or mouse joystick.
3. Launch the game and attempt to use the gyro.

**Comment by hperrin** [comment]
Btw, the controllers also have to be re-paired every time they are connected to the machine. I do this in Gnome by going to the Bluetooth settings page, clicking on the already connected controller, putting the controller into pairing mode, waiting for the "Connection" slider to slide to the disabled state, then sliding the toggle back to the enabled state.

When the controller reconnects to the device after being turned on, before I do this whole re-pairing procedure, the Steam client will list the controller as "Unknown Controller" in the Controller Settings page, and the controller simply doesn't work at all in Steam. It does work in other games and software, like Sonic Robo Blast 2 and RetroArch.

**Comment by hperrin** [comment]
Also, if I can take this opportunity to fanboy a little bit, thank you so much for all you do with regard to gaming on Linux! I used to be a PC gamer in the late 2000s, then I switched to Linux and basically missed out on 12 years of gaming. Now, thanks to all your hard work on Proton, Steam, etc., I'm back into PC gaming and absolutely loving it!

**Comment by dmayle** [comment]
I just ran into this same issue.  Works fine on Windows, but booting into linux and the gyro stops controlling games.

**Comment by hperrin** [comment]
This appears to be fixed.

**Comment by dmayle** [comment]
I haven't gotten around to testing this in a while, but just did.  On latest steam, with every Proton I tried (experimental, 7.0-4, 6.3-8, 5.13-6, 5.0-10), this still doesn't work.  I'm *not* using hid_nintendo, or any other hack, just the pure steam switch pro controller support.

**Comment by kisak-valve** [comment]
Hello @dmayle, please open a new issue report so that your issue can be tracked properly.
