### ISSUE TITLE
Cs go Black screen then closed

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [ValveSoftware/steam-for-linux#8277]
I install steam then i install cs go and when i launch it for the first time it show to me a pop up saying that there is another session open and that will cause a conflict on the cloud and there us two buttons cancel or continue i clicked cancel for the first time then i relaunch the game the same pop up then i clicked to continue the game open but with black screen and take a while then the black screen close i try to open it many time but the same black screen the close please help i make a huge search on the internet but i find nothing then i remove it and reinstall it again but the same so please help!!
Os is fedora 35 on lenovo thinkpad T460s
Intel i7 6gen 6600U
Integrated gpu intel 520.
Note: i have windows and fedora intalled on my pc and i used to play cs go on windows, and i have one steam account and i install cs go on fedora from the same steam account.

**Comment by kisak-valve** [comment]
Hello @Abdelkader-gnichi, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2659. Closing as a duplicate.

**Comment by Abdelkader-gnichi** [comment]
Thank u
