### ISSUE TITLE
Steam Big Picture Mode exits fullscreen when exiting game

### ISSUE THREAD

**Issue by bjornfor** [ValveSoftware/steam-for-linux#8280]
#### Your system information

* Steam client version (build number or date): `Nov 22 2021, at 22:12:42`
* Distribution (e.g. Ubuntu): `NixOS 21.05 (Gnome 40 + Wayland)`
* Opted into Steam client beta?: `No`
* Have you checked for system updates?: `Yes`

#### Please describe your issue in as much detail as possible:
I expect that when running Big Picture Mode (BPM) it stays in fullscreen also after exiting a game. However, exiting a game makes it shrink to perhaps to 70% in size, without window decorations. The shrinking happens _after_ exiting the game, typically 1 - 2 seconds.

![Screenshot from 2021-12-03 21-59-49](https://user-images.githubusercontent.com/133602/144672268-22319b2a-56ea-4250-abf4-1021baa9ff2f.png)

As can be seen from the screenshot above, the application no longer fills the screen. If I Alt+Tab in this state other windows can and will fill/use the "gray" area (that's my desktop background). But I cannot "drag" the Steam BPM window anywhere, unlike normal application windows.

This "exiting a game exits fullscreen" behaviour happens reliably after exiting any of the games I've tried (BallisticNG, DiRT Rally, DiRT Rally 2.0).

If I exit BPM and re-enter (not even restarting the Steam client), it goes back into fullscreen (good).

This issue has seemingly the same symptoms as https://github.com/ValveSoftware/steam-for-linux/issues/4313, which was fixed long ago, but apparently I'm not the only one having a similar problem today (https://github.com/ValveSoftware/steam-for-linux/issues/4313#issuecomment-982220169).

#### Steps for reproducing this issue:

1. Start Steam in Big Picture Mode (BPM).
2. Start a game (e.g. BallisticNG) 
3. Exit game.
4. Watch Steam (in BPM mode) no longer being fullscreen (~70% size, no window decorations).

**Comment by DanMan** [comment]
Same here on Fedora 35 ((Sysinfo)[https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329/9081631f3b3fa833ffbb3c59b75c053421fa9bc7])

![steam_bp_bug](https://user-images.githubusercontent.com/298191/144674312-4514cad0-2c19-4808-8572-a97ed1c5c42a.jpg)

**Comment by ruineka** [comment]
Same issue occurs regularly for me as well. Pop OS 20.04-21.10 running under Wayland hooked up to a TV.

**Comment by deathxxx123** [comment]
This thing is happen to me today for 1-st time.
I was playing UnderMine and after exit, i got this windowed big-picture.
In Stardew Walley was the same.
I see after i exit from the game, my controller is lost from steam client.
And maybe because of that, my stem big picture was loosing the full screen mode.
In options my controller was not detected anymore. Need reconnect it to get detected again every single time i exit from these games.
Now i try to change some options in controller:
It was only first option enabled.
Now i click to Xbox configuration and the last option.
Now after exit these games, my controller is still recognized and steam Big-Picture not losing focus or full screen.
All seems to normal now.

Manjaro Gnome X11 with Nvidia 470.xx driver.

**Comment by Disk1of5** [comment]
Also happens to me as well, looks like its not wayland specific because it also happens on Xorg but only with gnome 4.x

**Comment by wezel** [comment]
Can confirm also happens to me: pop-os 21.10 gnome 40.4 on Xorg. I do use steam beta though.

**Comment by DanMan** [comment]
Maybe someone should report this on the Gnome Gitlab, since it seems to be related to Gnome 40+

**Comment by Komoszek** [comment]
So I've done some test with some other WMs(i.e. Openbox and xfce4) and I couldn't reproduce exactly this issue but if we run BPM in windowed mode and maximize it then exiting games will unmaximize it(which I think shouldn't happen and I'm almost certain that it is pretty much the same issue as with the fullscreen) in every WM I've tested (including gnome).

**Comment by Nadonate** [comment]
Same issue.

On POP OS 21.1
Gnome 40.4
Xorg

**Comment by deathxxx123** [comment]
It's no longer happen when starting steam direct with autostart Big Picture mode.
Manjaro Gnome 41.2 , Nvidia 470.94

**Comment by Disk1of5** [comment]
Still an issue in Ubuntu 21.10

**Comment by Disk1of5** [comment]
Still an issue also tested with Gnome 41.5

**Comment by Disk1of5** [comment]
Also an issue with Openbox.

@kisak-valve  any updates on this.. it really breaks the steam home streaming functionality with the steam link  and the Steam link Android app.

**Comment by vgf89** [comment]
Also in Fedora 35, Gnome 41.5, Wayland

**Comment by mbentham** [comment]
Also happens on Pop! OS 22.04, Gnome 42.1, X11 with the deb steam installer

**Comment by Disk1of5** [comment]
OK.. going out on a limb...  after commenting on a lot of these linux bugs i *Suspect* whats happening is the steam Devs are  not putting much time (if any)  into the big picture mode of the linux client...  The reason for this is that their engineers have stated that the Big Picture setup is a separate code base and the plan is that it will be deprecated in favor of the Deck UI .. what sucks is outstanding bugs until it happens... hopefully soon.


What i can tell you all is that right now big picture works correctly with KDE and retains the full-screen when games exit... this is most likely because they have been focusing on the KDE DE as they were working on the Steam Deck.. 

That's just my 2cents...

**Comment by cchulo** [comment]
I got around this issue by setting resolution to 1080p (games and desktop environment). No idea why, but this was the workaround I found. Thankfully samsung tvs have AI upscaling so it doesn't look terribly blurry when gaming from a distance, but still wish I could keep 4K resolution on at all times.

**Comment by deathxxx123** [comment]
Wow i'm impress... just cannot fix one small issue with big picture?
And still not fixed after all?
Are devs playing using big picture? Are devs even try steam?
Why this is still issue?

**Comment by cprn** [comment]
> So the solution for i3wm is to add the following line in ~/.i3/config (change your resolution accordingly, below is 4K):
>
>    for_window [instance="steam"] floating enable, resize set 3840 2160, move position 0 0
>
> and then in Steam Big Picture mode **Settings > Display > Interface** set the **Start Big Picture mode Windowed** to ON.

**Comment by Disk1of5** [comment]
Hey All, it seems that bigpicture replacement is slowly happening

Please see valves post:
https://store.steampowered.com/news/app/593110/view/3394051164709183116

in linux i think you just need to be part of the steam beta and launch steam with -gamepadui

So far it works for me and boots me into the SteamDeck UI... so far after returning from a game steam retains full screen now.. but more testing is required.

Hope this helps! :)

**Comment by cprn** [comment]
> So far it works

Well, for me it works but very very sluggish, about 1 fps.

**Comment by JustCryen** [comment]
Awesome, Even works on Gnome42!

**Comment by razzeee** [comment]
This is solved for me with the new big picture

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5444 was tracking this too

**Comment by bjornfor** [comment]
I cannot reproduce this bug anymore with NixOS 23.05 (GNOME 44.2) and the new Steam big picture mode (gamepad UI). Hooray!

**Comment by Whayme** [comment]
This still occurs for me occasionally with the new UI on GNOME Wayland.

**Comment by JustCryen** [comment]
Well, on Gnome Wayland I can't get it to launch in fulscreen at all. It launches in windowed for over a month now.
But that being said, I've just tried on Gnome on x11 and it does the same thing.

It used to work great in the new UI but now it's performance is laggy and it's only launching in a window.
