### ISSUE TITLE
The game doesn't work. Black screen.

### ISSUE THREAD

**Issue by imLEGR** [ValveSoftware/steam-for-linux#8284]
#### Your system information

* 1637624439, Now 22 2021: 
* Arch Linux.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I start CS GO, a black screen opens. Then the screen closes.

#### Steps for reproducing this issue:
1. Launch CS GO in Steam.
2. opens a black window.
3. Closes the black window.

Found this solution (but now there are no videos in the game):

1. Startup parameters: -novid -nojoy
2. Delete/rename folder "Counter-Strike Global Offensive/csgo/panorama/videos/".

**Comment by kisak-valve** [comment]
Hello @imLEGR, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2659. Closing as a duplicate.
