### ISSUE TITLE
Modify game release rules on Steam

### ISSUE THREAD

**Issue by ALipAkrohk** [ValveSoftware/steam-for-linux#8287]
#### Your system information

* Steam client version (build number or date):  Nov 22 2021,  at 22:12:42 
* Distribution : Arch
* Opted into Steam client beta?:  Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam has been the official platform of Linux for many years, why Steam does not change the rules of publishing the game and using the store.
Games that use Steam in any way they can, actually write their Windows games in a way that is unusable on the Steam operating system.
Most game engines and anti-cheats used to build games, all have good support for Steam OS, but game developers even play their games that way at the cost of lowering the quality of their games or having problems with FPS or increasing Cheaters in their games. It is written that it is unusable in Steam and Linux operating systems, why Valve does not change its rules regarding the release of the game in the store.
The developers are practically insulting Valve and its choices.

![EAC_ON_PolyGUN](https://media.discordapp.net/attachments/911658462889525268/917537403332329512/Screenshot_20211207_013546.png)
![Steam Support](https://cdn.discordapp.com/attachments/907692050999304202/917968398279929906/Screenshot_20211208_054244.png)

**Comment by kisak-valve** [comment]
Hello @ALipAkrohk, it's not clear why Steam support thought that this specific topic was appropriate for the Steam for Linux client issue tracker.

My understanding is that there is no OS platform restrictions when it comes to publishing a game on Steam, and reviewing store policy can only be done by Valve developers internally. This is not subject to public feedback.

Closing as out-of-scope for this issue tracker.
