### ISSUE TITLE
Steam won't exit on its own

### ISSUE THREAD

**Issue by Angell1993** [ValveSoftware/steam-for-linux#8288]
#### Your system information

* Steam client version (build number or date): steam-manjaro 1.0.0.73-1
Steam about popup:
Build: Dec 02 2021
Steam Package Versions: 1638464786
* Distribution (e.g. Ubuntu):  Manjaro 21.2.0 Qonos
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Steam won't exit by itself, I can see that Steam is going through all my proton versions to find one working with the prefix '0' that is running constantly, no idea why..

Terminal output on steam exit, that never ends.. Have to kill the steam process to exit steam..
Installing breakpad exception handler for appid(steam)/version(1638464786)
src/common/pipes.cpp (885) : stalled cross-thread pipe.
src/common/pipes.cpp (885) : stalled cross-thread pipe.
Installing breakpad exception handler for appid(steam)/version(1638464786)
assert_20211208111248_30.dmp[996959]: Uploading dump (out-of-process)
/tmp/dumps/assert_20211208111248_30.dmp
src/clientdll/steamclient.cpp (854) : bufRet.TellPut() == sizeof(uint8)
src/clientdll/steamclient.cpp (854) : bufRet.TellPut() == sizeof(uint8)
assert_20211208111248_30.dmp[996959]: Finished uploading minidump (out-of-process): success = yes
assert_20211208111248_30.dmp[996959]: response: CrashID=bp-62b39cac-e64e-4da1-92d4-39a852211208
assert_20211208111248_30.dmp[996959]: file ''/tmp/dumps/assert_20211208111248_30.dmp'', upload yes: ''CrashID=bp-62b39cac-e64e-4da1-92d4-39a852211208''
Exiting workitem thread

#### Steps for reproducing this issue:

1. Open steam wait for it to load then exit
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Angell1993, this issue is already being tracked at #8113 / #8114. Closing as a duplicate.
