### ISSUE TITLE
Shader pre-caching update: SEVERELY BROKEN on Linux and Mac

### ISSUE THREAD

**Issue by g572staem** [ValveSoftware/steam-for-linux#8292]
CS:GO is broken for all Linux and Mac users with the very recent "Shader pre-caching update".  I don't think it is related to this project but this needs to be seen by someone who can contact the appropriate people at Valve.

Thanks.

https://steamcommunity.com/app/730/discussions/0/3196990234721043288/https://steamcommunity.com/app/730/discussions/0/3196990234721043288/

**Comment by g572staem** [comment]
https://github.com/ValveSoftware/csgo-osx-linux/issues/2868

**Comment by g572staem** [comment]
I should close this but I can't play so...

**Comment by kisak-valve** [comment]
Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/2871.

**Comment by FinnVincible** [comment]
my thing is glitched still how do we fix where is all previous comments
