### ISSUE TITLE
ENTITY MODELS ARE ALL BROKEN ON LINUX AND MAC 

### ISSUE THREAD

**Issue by milkbag19** [ValveSoftware/steam-for-linux#8294]
#### Your system information

* Steam client version  :  This issue has nothing to do with this as many others across mac and linux have this issue
* Distribution :  Kubuntu 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Well playermodels should look like, you know, physically possible people, not like this : 
![image](https://user-images.githubusercontent.com/40251012/145698992-2332f5ca-31e1-45a2-959c-29423ba480e7.png)
![image](https://user-images.githubusercontent.com/40251012/145698995-4d089cc8-70c0-4038-b8de-c70498d6555d.png)
![image](https://user-images.githubusercontent.com/40251012/145699071-6986f50a-db01-4adf-b4d3-341a0bb0ea94.png)
![image](https://user-images.githubusercontent.com/40251012/145699087-e10de34f-07f1-4a45-9fc2-99615122372d.png)

NOTE: This is due to the Friday update.  At first the game just wouldn't launch, and after some sleuthing, it looked to be some issues with OpenGL.  A 2MB update was released not too long after that allowed us to play.  However, this is when the models were broken.  So, its probably an issue with whatever you guys were doing with OpenGL.

#### Steps for reproducing this issue:

1. Use linux or mac os 
2. launch csgo
3. profit

**Comment by kisak-valve** [comment]
Hello @milkbag19, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2871. Closing as a duplicate.
