### ISSUE TITLE
SteamCMD new warning: Please use force_install_dir before logon!

### ISSUE THREAD

**Issue by ich777** [ValveSoftware/steam-for-linux#8298]
#### Your system information

* Steam client version (build number or date): **Steam Console Client (c) Valve Corporation - version 1637624355**
* Distribution (e.g. Ubuntu): **Debian 11**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
Not really sure where to post because it's an "issue" with SteamCMD.
Recently an update from SteamCMD brought up this message: `Please use force_install_dir before logon!`

#### Steps for reproducing this issue:

1. Call `steamcmd.sh +login anonymous +force_install_dir ${SERVER_DIR} +app_update ${GAME_ID} +quit`
2. Message `Please use force_install_dir before logon!` pops up in the logs but game downloads fine

Is this something that needs to be changed to: `steamcmd.sh +force_install_dir ${SERVER_DIR} +login anonymous +app_update ${GAME_ID} +quit` or is the old command still fine? If it needs to be changed, why? Or can this warning be ignored?

**Comment by TTimo** [comment]
The warning is correct - your scripts should use `force_install_dir` before logging in, and avoid using it after logging in.

Using `force_install_dir` used to trigger a forced re-download of a title's content even when no update was necessary. This problem is fixed in `steamcmd`, but there may be other issues and it's still recommended to use `force_install_dir` before logon.

**Comment by ich777** [comment]
@TTimo oh, okay, then I think I have to fix this for my ~64 Docker images... :D

Strange thing is that it never actually triggered a redownload from any game.
Thank you for your time and quick answer! :)

**Comment by TTimo** [comment]
Yeah, that was https://github.com/ValveSoftware/steam-for-linux/issues/8075 - but it only happened under heavy I/O load

**Comment by thesweetiger** [comment]
Hi , I use steamCMD since it's first day and I comfirm it's a bug , it should not happen , all the official documentation say clearly to log in first

**Comment by thesweetiger** [comment]
> Hello @ich777,
> 
> The warning is correct - your scripts should use `force_install_dir` before logging in, and avoid using it after logging in.
> 
> Using `force_install_dir` used to trigger a forced re-download of a title's content even when no update was necessary. This problem is fixed in `steamcmd`, but there may be other issues and it's still recommended to use `force_install_dir` before logon.

your wrong , all the documentation are clear , logon first and use force_install_dir in second , all this info are from steam documentation

**Comment by ich777** [comment]
@thesweetiger I think the person you want to mention is @TTimo or am I wrong?

**Comment by Calingoff** [comment]
Hi, i got the same error (first, i do login anonymous, after i create a file for my server, and after i use force_install_dir and my file in c:   and after i got : please use force_install_dir before logon)

can you explaind clearly what i should do ? step by step ? 

thx for your help

**Comment by strawed1** [comment]
> @Calingoff : simply put the force_install_dir command before the login command in your script.
I did and it still said the same

**Comment by FloppaTest** [comment]
İ  tried without logging in, nothing happens.

**Comment by SGZ-Creations** [comment]
having issues getting further than this on doing this new method of installing server files.

Steam>force_install_dir
Usage: force_install_dir <directory>
