### ISSUE TITLE
CS:GO visual glitches occurs with the recent patches.

### ISSUE THREAD

**Issue by AlexanderCurl** [ValveSoftware/steam-for-linux#8299]
#### Your system information

* Steam client version (build number or date): 1638464786
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, everything up to date.

#### Please describe your issue in as much detail as possible:
With the latest patches CS:GO has major visual glitches in-game, for some reason, a week ago everything was fine.
I attach 2 screenshots as well.

https://imgur.com/a/TTnZzmp
https://imgur.com/a/qOSoGmw

**Comment by kisak-valve** [comment]
Hello @AlexanderCurl, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2871. Closing as a duplicate.

**Comment by beau24** [comment]
Found a solution:
https://www.youtube.com/watch?v=VeH_SNmsBWc
