### ISSUE TITLE
graphic problem with csgo 

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [ValveSoftware/steam-for-linux#8300]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): fedora 35 64-bit 
* Opted into Steam client beta?: 
* Have you checked for system updates?:Yes

i open cs-go but it ask for a small update,after the update i open it (play game) and it open normally but the character shape of the game is  corrupted the mesh of the character is corrupted and the same in the game play all the character (enemies/friends) including my main character is corrupted please help

#### Steps for reproducing this issue:

1. launch cs go
2. ask for small update,i update the game 
3. open the game, all the character of the game are corrupted 
4. close and re-open it the same problem

**Comment by kisak-valve** [comment]
Hello @Abdelkader-gnichi, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2871. Closing as a duplicate.
