### ISSUE TITLE
Steam Crashes To Desktop With No Errors

### ISSUE THREAD

**Issue by oguzdeler** [ValveSoftware/steam-for-linux#8303]
#### Your system information
Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  X550VX
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    CPU Family:  0x6
    CPU Model:  0x5e
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3500 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "EndeavourOS Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.15.7-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101001
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  NVIDIA Corporation NVIDIA GeForce GTX 950M/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 495.46
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x139a
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.60" (15.51" diag)
                                            34.4cm x 19.3cm (39.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC255

Memory:
    RAM:  15801 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  428979 MB
    Largest Free Hard Disk Block:  401861 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 1

* Steam client version (build number or date):  2 2021, at 07:36:11
* Distribution (e.g. Ubuntu): Endeavour OS
* Opted into Steam client beta?: [Yes/No] BOTH
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I freshly installed OS yesterday night. Opened game, after half an hour I thought game freeze but turns out Steam Client crashed and game tried to close itself. 
#### Steps for reproducing this issue:

1. Open Steam Client
2. In half hour client exits without error or warning
3. Playing games or not playing games doesn't matter for the crash.

 
[steamoutput.txt](https://github.com/ValveSoftware/steam-for-linux/files/7714170/steamoutput.txt)

**Comment by kisak-valve** [comment]
Hello @oguzdeler, not that it directly helps, but your log looks similar to #7851.

**Comment by kisak-valve** [comment]
This is the same issue as #7851. Closing as a duplicate.
