### ISSUE TITLE
Attempting to Save Community Content Images Doesn't Work

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#8304]
#### Your system information

* Steam client version (build number or date): Build date - Nov, 22, 2021 at 22:12:42
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

System info: [gist](https://gist.github.com/ThisNekoGuy/bb67d94da57b8dcea140a663eec21b65)

In the `community content` section of games in the user's library, right clicking on images users have uploaded to `save screenshot as` causes a "phantom window" to appear that instead mirrors the window under it at the location it was rendered, like so:

![image](https://user-images.githubusercontent.com/28468662/146103073-fe528085-0d43-40a2-9fc4-48c8c47550f6.png)

![image](https://user-images.githubusercontent.com/28468662/146103201-4a552bac-1632-41a1-bc81-842fb547596d.png)

Because of this, this function doesn't work at all.

#### Steps for reproducing this issue:

1. Login to Steam
2. Go to your library
3. Select a game
4. Scroll down to the `community content` area
5. Right click on a user's uploaded image content and attempt to save it

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue is already being tracked at #6698. Closing as a duplicate.
