### ISSUE TITLE
Steam (Runtime) window mislabeled as Steam (Native)

### ISSUE THREAD

**Issue by noir-Z** [ValveSoftware/steam-for-linux#8305]
#### Your system information

* Steam client version (build number or date): Nov, 22, 2021 at 22:12:42
* Distribution (e.g. Ubuntu): Arch  (w/ Plasma)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I run Steam (Runtime) the title of the Steam window is Steam (Native) instead of Steam (Runtime).
This causes an issue with Plasma's Icons-only Task Manager in the Taskbar:
I have Steam (Runtime) pinned and due to the window being labeled Steam (Native) instead of Steam (Runtime) it won't stack on top of the pinned entry.

#### Steps for reproducing this issue:

1. Pin Steam (Runtime) to Task Manager
2. Launch it

**Comment by kisak-valve** [comment]
Hello @noir-Z, the `(Runtime)` and `(Native)` markings on Arch are part of Arch's distro-specific modifications of the Steam package and not part up Valve's upstream packaging. This can not be fixed from Valve's side.

Report this issue to your distro's package maintainer(s) for Steam.
