### ISSUE TITLE
Every Steam window is completely black

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-for-linux#8306]
#### Your system information

* Steam client version (build number or date): I am not sure how to check
* Distribution (e.g. Ubuntu): Fedora 35 Workstation (proprietary NVIDIA + GNOME Wayland via EGLStreams)
* Opted into Steam client beta?: Not sure
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

![image](https://user-images.githubusercontent.com/4428753/146334354-4dfe0157-8857-4898-8ce0-5ffd70fa5d7e.png)

Steam just looks like this when I start it up. It also takes long to shut down for some reason.

#### Steps for reproducing this issue:

1. Start Steam
2. Observe that every window is pitch black

**Comment by kisak-valve** [comment]
Hello @Newbytee, can you check if it renders as expected with an X based user session?

**Comment by Newbytee** [comment]
> Hello @Newbytee, can you check if it renders as expected with an X based user session?

It does not seem like it, but sometimes it randomly works even in Wayland. I might add that this issue only appeared recently, and happens both if I use the Steam Flatpak from Flathub and the RPM from RPM Fusion. And I can verify that I'm using the Steam Beta update now.

**Comment by kisak-valve** [comment]
Thanks, this is most likely an Xwayland, video driver, or GNOME issue.

**Comment by TiagoTiago** [comment]
I'm getting a similar issue, but it's only BigScreen and the controller config windows that come out all black.

Linux Mint 20.2 with Mate DE; RTX3080-Laptop with official Nvidia driver version 495.29.05

**Comment by knutj** [comment]
Similar problem with Gnome and the latest Nvidia driver.

**Comment by kisak-valve** [comment]
Hello @knutj, there's a good chance you're seeing #8373 instead of the issue reported here.

**Comment by Newbytee** [comment]
I've not seen this for months now, so I'll close it.
