### ISSUE TITLE
"Save Screenshot as.." Uses an 'Open' Prompt Rather than a 'Save as' Prompt

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/steam-for-linux#8314]
System info:

* Steam client version (build number or date):
  steam-runtime_0.20211207.0
  "Built Dec 16 2021, at 22:39:26"
* Distribution: Ubuntu 21.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Upon Pressing on Any Screenshot/Artwork From Any Game on the Community Hub
![savescreenshotas](https://user-images.githubusercontent.com/20986867/147102563-21714208-5464-47f7-a4fa-c2425346a343.png)

Would Result into Steam getting Stuck like this:
![savescreenshotas1](https://user-images.githubusercontent.com/20986867/147102636-716e2345-1255-4f58-9714-b21e18a58727.png)
(Until You Mouse Click Somewhere random on the screen)

Resulting into an Open Prompt:
![savescreenshot2](https://user-images.githubusercontent.com/20986867/147102708-6563b3ea-5715-4f71-8fab-bc67764c13ae.png)
Meaning you can only Overwrite Existing files. Rather than Saving a new File.

**Comment by kisak-valve** [comment]
Hello @shytzedaka, this issue is already being tracked at #6698. Closing as a duplicate.

**Comment by shytzedaka** [comment]
Ok thank you.
