### ISSUE TITLE
Failed to launch game with "non-steam" option

### ISSUE THREAD

**Issue by soheilkhanalipur** [ValveSoftware/steam-for-linux#8321]
System information

* Steam client version (build number or date): 1639697812
* Distribution: Kali 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

…
GameAction [AppID 3940928962, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 3940928962, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 3940928962, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 3940928962, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
src/clientdll/compatmanager.cpp (973) : GetCompatibilityToolCommandLineInternal on dependent tool failed
src/clientdll/compatmanager.cpp (973) : GetCompatibilityToolCommandLineInternal on dependent tool failed
Installing breakpad exception handler for appid(steam)/version(1639697812)
assert_20211226163025_32.dmp[8563]: Uploading dump (out-of-process)
/tmp/dumps/assert_20211226163025_32.dmp
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 3940928962, ActionID 1] : LaunchApp failed with AppError_51 with ""
GameAction [AppID 3940928962, ActionID 1] : LaunchApp changed task to Failed with ""

(steam:8311): Gtk-WARNING **: 16:30:25.476: gtk_disable_setlocale() must be called before gtk_init()

(steam:8311): GLib-CRITICAL **: 16:30:25.476: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed

(steam:8311): Gtk-WARNING **: 16:30:25.839: gtk_disable_setlocale() must be called before gtk_init()

(steam:8311): GLib-CRITICAL **: 16:30:25.839: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed
assert_20211226163025_32.dmp[8563]: Finished uploading minidump (out-of-process): success = yes
assert_20211226163025_32.dmp[8563]: response: CrashID=bp-fe0ec6c4-0e1f-4aa0-afb6-196722211226
assert_20211226163025_32.dmp[8563]: file ''/tmp/dumps/assert_20211226163025_32.dmp'', upload yes: ''CrashID=bp-fe0ec6c4-0e1f-4aa0-afb6-196722211226''
…

**Comment by kisak-valve** [comment]
Hello @soheilkhanalipur, this issue is already being tracked at #7664. Closing as a duplicate.
