### ISSUE TITLE
Steam Chat Friends List Right Click Context Menu Rendering Problems

### ISSUE THREAD

**Issue by krompus** [ValveSoftware/steam-for-linux#8324]
#### Your system information

* Steam client version (build number or date): Dec 16 2021
* Distribution: Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The right click context menu in Steam Chat Friends List is only able to render inside of the chat window. This causes rendering issues when there are too many menu items to display within the window boundaries.

In a context menu that flows downwards, if there are too many menu items to display within the window boundaries, all of the Friends List window contents will shift upwards to accommodate the overflow, and a black bar will display underneath. The user may still move the cursor down to select overflowing menu items.

In a context menu that flow upwards, if there are too many menu items to display within the window boundaries, the overflowing menu items are not rendered or selectable.

The issue is present in both the Desktop Mode Friends List and the Steam Overlay Friends List.

[Screenshot](https://user-images.githubusercontent.com/12161878/147714183-bbd17bfd-d80b-4310-9a9e-90ef95714e8c.png)

#### Steps for reproducing this issue:

1. Open Steam Chat.
2. Right click on a friend in the Friend List.
3. If the context menu contains too many items to render fully within the chat window dimensions, observe rendering bug described above.

**Comment by kisak-valve** [comment]
Hello @krompus, this issue is already being tracked at #7558. Closing as a duplicate.

**Comment by krompus** [comment]
@kisak-valve Oh shit it's a dupe, 15 minutes of my precious time wasted, lol. Thank you. :)
