### ISSUE TITLE
Infinite sound notifications when trying to alt-tab back

### ISSUE THREAD

**Issue by 17314642** [ValveSoftware/steam-for-linux#8328]
#### Your system information

* Steam client version (build number or date): Dec 16 2021
* Distribution (e.g. Ubuntu): Kubuntu 21.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

## Please describe your issue in as much detail as possible:
Steam shouldn't jumpscare me with this abnormal amount of sound notifications. I'm not sure if it is steam issue or kde specific, so pardon me if I'm in the wrong repository.

https://user-images.githubusercontent.com/57731977/147852321-1e6aa700-42ba-43d6-b90f-d88a3383e9d8.mp4

#### Steps for reproducing this issue:

1. Open steam and login
2. Alt+Tab
3. Click on steam icon in the taskbar or hover on steam and try to select login window

**Comment by kisak-valve** [comment]
Hello @17314642, this issue is already being tracked at #846. Closing in favor of the older issue report.
