### ISSUE TITLE
Metro Exodus stopped working yesterday

### ISSUE THREAD

**Issue by laroyru** [ValveSoftware/steam-for-linux#8335]
I had fantastic 22 hours last year playing Metro Exodus via Proton 6.3-8 on 6600XT amdgpu 21.30 Ubuntu 20.04.3. Yesterday after a bunch of updates for both Ubuntu and Metro (1GB) it's stopped working with no meaningful errors. I've managed to get an error report only after upgrading the driver to amdgpu 21.40.1 (no other changes). Can anyone have a look into it? Where should I upload it?

**Comment by kisak-valve** [comment]
Hello @laroyru, we're tracking issues with games run with Proton  in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2414#issuecomment-1006031427.
