### ISSUE TITLE
"System Information" reports wrong information

### ISSUE THREAD

**Issue by TheSHEEEP** [ValveSoftware/steam-for-linux#8338]
#### Your system information

* Steam client version (build number or date): Jan 7 2022
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The "System Information" Steam gives about my PC shows an incorrect GPU. All other information shown in it is correct.

[system_information.txt](https://github.com/ValveSoftware/steam-for-linux/files/7833813/system_information.txt)
The report is attached, but here's the relevant part:

> Video Card:
>     Driver:  Mesa/X.org llvmpipe (LLVM 13.0.0, 256 bits)
>     Driver Version:  4.5 (Compatibility Profile) Mesa 21.3.2
>     OpenGL Version: 4.5
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     VendorID:  0x10de
>     DeviceID:  0x1b81
>     Revision Not Detected
>     Number of Monitors:  2
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 3840 x 1174
>     Primary Display Size: 20.91" x 11.77" (23.98" diag)
>                                             53.1cm x 29.9cm (60.9cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM Not Detected
>     Supported MSAA Modes:  2x 4x 8x 16x 

That's rather odd, given that I have a GTX 1070 and recent drivers (495) are installed, here's e.g. part of the `glxgears -info` output:

> glxgears -info
> Running synchronized to the vertical refresh.  The framerate should be
> approximately the same as the monitor refresh rate.
> GL_RENDERER   = NVIDIA GeForce GTX 1070/PCIe/SSE2
> GL_VERSION    = 4.6.0 NVIDIA 495.44
> GL_VENDOR     = NVIDIA Corporation
> GL_EXTENSIONS = GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_cl...

This is not a laptop or desktop with an integrated GPU, either, which could cause confusion. 
The GTX 1070 is the only available GPU.

Some Proton games (e.g. Kingdoms of Amalur: Re-Reckoning) also show an error that the GPU would not support DirectX10 or a similar issue - while most games work just fine through Proton (e.g. Age Of Empires 4).
I'm not sure if those issues are related, however.

**Comment by kisak-valve** [comment]
Hello @TheSHEEEP, Steam is accurately telling you that the 32 bit render path is using mesa's faster software renderer and not using your video card for OpenGL. Your system is missing NVIDIA's 32 bit userspace libraries. Please install the `lib32-nvidia-utils` system package.

**Comment by TheSHEEEP** [comment]
That makes sense and indeed fixed the reporting issue as well as the game issues (so they were related, I just didn't realize that the games that didn't work must've all been 32bit).

I wonder what removed the package, since it used to report it correctly. Probably got removed accidentally at some point during driver updates.

Either way, since this had such noticeable effects, I think it would be good if Steam could detect if that package is installed or not, though I don't know if that is possible.
