### ISSUE TITLE
YOUR WEB BROWSER DOES NOT SUPPORT THE MINIMUM SET OF FEATURES REQUIRED TO WATCH THIS BROADCAST

### ISSUE THREAD

**Issue by EnderIce2** [ValveSoftware/steam-for-linux#8340]
#### Your system information

* Steam client version (build number or date): Jan 7 2022
* Distribution (e.g. Ubuntu): Ubuntu 20.04.3 LTS x86_64
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
SteamDeck's site (https://store.steampowered.com/steamdeck/) is not loading and I can't watch game streams because of a message telling me that the browser is not supported (YOUR WEB BROWSER DOES NOT SUPPORT THE MINIMUM SET OF FEATURES REQUIRED TO WATCH THIS BROADCAST).

**Comment by kisak-valve** [comment]
Hello @EnderIce2, this issue is already being tracked at #6780. Closing as a duplicate.
