### ISSUE TITLE
UI elements broken.

### ISSUE THREAD

**Issue by Zagnaut1717** [ValveSoftware/steam-for-linux#8341]
Intel i7-5820K
16gb ram
Nvidia 1660

* Steam client version (build number or date): Unable to open UI element to check but I am using the latest beta.
* Distribution (e.g. Ubuntu): Pop! OS 20.04
* Opted into Steam client beta?: [Yes/No] Yes, but the problem exists in both versions.
* Have you checked for system updates?: [Yes/No] Yes and reinstalled Steam

#### Please describe your issue in as much detail as possible:
After opening Steam, hovering over some of the UI elements(Store, Library, Community ect) and clicking on them produces no results.
For example: I open Steam, it opens to the Library page. I hover over Library button and the sub-menu appears. I click on the Downloads option in the sub-menu and nothing happens. The Downloads page does not open. Many sub-menus are simply unreachable because of this bug.

#### Steps for reproducing this issue:

1.  Open Steam.
2.  Hover over UI elements and click on a sub-menu item.
3.  Sub-menu item does not open

Problem just started today. I performed a system update and rebooted when I first got up this morning and I believe a new kernel was installed yesterday since the last time I was able to use Steam like normal

**Comment by Zagnaut1717** [comment]
Problem does NOT present on a laptop running ArcoLinux with KDE desktop. Related to theming issues with Adwaita?

**Comment by SER-3604** [comment]
Can confirm this issue appears on Pop!_OS 21.10 as well.

**Comment by Zagnaut1717** [comment]
Well this is interesting. Returning to stock Pop theme and disabling tiling seems to have "fixed" the issue. I'm even more convinced this is an Adwaita problem.
 Running Steam from the command line does show a few theme engine errors but I was under the impression I could usually ignore the errors there.

**Comment by Zagnaut1717** [comment]
Also, even though the above actions "fixed" the UI issue, clicking on the buttons still sometimes took me to a blank page.

**Comment by SER-3604** [comment]
Sorry, this is likely a pop-shell (the autotiling in Pop!_OS) issue. I had the Pop!_OS default theme installed as well, and that wasn' t the problem.

Upon turning off tiling, these buttons worked normally.

**Comment by SER-3604** [comment]
I would recommend closing this issue.

**Comment by Zagnaut1717** [comment]
Thanks for confirmation. Tiling seems the likely culprit. Disabling it fixed issues.

**Comment by SER-3604** [comment]
@Zagnaut1717 Here's a link to a similar issue on the actual pop-shell repo: https://github.com/pop-os/shell/issues/1312.

Looks like a fix has been made, and it's just waiting to be packaged and released.

**Comment by Zagnaut1717** [comment]
Already on it? Excellent. Turning off tiling really messes with my work-flow.
