### ISSUE TITLE
Can't get Steam to launch, says I'm missing libc.so.6

### ISSUE THREAD

**Issue by pop587** [ValveSoftware/steam-for-linux#8343]
#### Your system information

* Steam client version (build number or date): Can't check, but downloaded latest .deb installer
* Distribution (e.g. Ubuntu): Linux Mint 20 XFCE
* Opted into Steam client beta?: No
* Have you checked for system updates?:  Yes

#### Please describe your issue in as much detail as possible:

I've been trying to install Steam on my laptop, but the client keeps giving me the attached error messages when I launch it. It's a Dell Inspiron with an i3-7020u@2.3ghz and 4 gb of ram.

I first tried the .deb installer I downloaded from the Steam website, then when this happened I uninstalled and tried using the version from the software repository. Got the exact same result both times. It seems to be trying to install some dependencies, but is unable to for some reason. Any help would be appreciated.

#### Steps for reproducing this issue:

1. Install Steam
2. Try to launch it
![Screenshot_2022-01-11_08-40-59](https://user-images.githubusercontent.com/97710230/149439273-e426b4ab-4340-47b1-b045-8ac4d9077241.png)
![Screenshot_2022-01-11_08-42-38](https://user-images.githubusercontent.com/97710230/149439277-68e40774-d922-4d58-88f1-596daaed2281.png)

**Comment by kisak-valve** [comment]
Hello @pop587, this is an Ubuntu package repository issue where Ubuntu downgraded a package and the currently installed package is no longer available. Please give #7982 a read for the longer explanation of what happened here.

https://github.com/ValveSoftware/steam-for-linux/issues/7982#issuecomment-897189992 has the manual package adjustment.
