### ISSUE TITLE
Some games fail to launch

### ISSUE THREAD

**Issue by citizen1277** [ValveSoftware/steam-for-linux#8345]
#### Your system information

* Steam client version (build number or date): Dec 16, 2021
* Distribution (e.g. Ubuntu): Mint 20.3
* Opted into Steam client beta?: No (not currently)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Hey all,
I'm trying to play The Pirate: Caribbean Hunt, but all I get is a text box that says "preparing to launch The Pirate: Caribbean Hunt," then the whole screen does a weird little shift up for a few seconds, and then I'm back to square one.  Steam claims I've played the game for 20 minutes, but that's just the 10 seconds it attempts to launch times 120 😄.  Any help would be appreciated.

##### I Tried
* Launching from the start menu, from Steam, and the local folder.
* Restarting many times.
* Verifying integrity of game files.
* Repairing Steam library folders.
* Beta version of Steam.
* Beta version of The Pirate.
* Reinstalling The Pirate.
* Reinstalling Steam from Software Manager, Steam website, and Github.
* Updating Mesa and checking version.
* The -autoconfig option via Launch Options.
* Installing and launching Crab Game and Star Conflict, and got the same result.
* Installing and launching Cemetery Mary and Come Home, which work fine.

##### System Info
Toshiba Satellite L655-S5150 running Linux Mint 20.3 Una.
https://www.manualslib.com/manual/329583/Toshiba-Satellite-L655-S5150.html
https://gist.github.com/citizen1277/40d6cd44cc385cc320709c4e4d98d893

#### Steps for reproducing this issue:

1.  Attempt to launch The Pirate: Caribbean Hunt from the start menu, from Steam, or the local folder.

**Comment by kisak-valve** [comment]
Hello @citizen1277, your system has an Intel Ironlake generation video chipset which only supports OpenGL 2.1. Your issue is with the limited hardware features on your system and the failing games need higher OpenGL support or Vulkan support. This can't be fixed on the software side.
