### ISSUE TITLE
Blank menu in system tray

### ISSUE THREAD

**Issue by yav12** [ValveSoftware/steam-for-linux#8347]
#### Your system information

* Steam client version (build number or date): Built Jan 15 2020
* Distribution (e.g. Ubuntu): Linux Mint 20.3 Cinnamon
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I click the tray icon on the taskbar, a blank bar shows up instead of the normal options (store, library, friends, recent games etc.), as shown in this image. 
![image](https://user-images.githubusercontent.com/80121423/149636306-b9764977-348e-4b3e-9615-168ea79a00d4.png)
When i run steam from the command line, a message pops up when i press the tray icon: 
```
(steam:11737): LIBDBUSMENU-GLIB-WARNING **: 15:08:48.540: About to Show called on an item wihtout submenus.  We're ignoring it
``` 
(the spelling error is really there too) :>

#### Steps for reproducing this issue:

1. Open steam (through command line or menu)
2. Wait for it to open and the tray icon to appear
3. Press Tray Icon

**Comment by kisak-valve** [comment]
Hello @yav12, this reads like #5222. What are the contents of `~/.steam/steam/ubuntu12_32/steam-runtime/pinned_libs_*`? If you completely close steam, then move or remove the pinned_libs folders, then restart steam, does the steam tray icon behave?

**Comment by yav12** [comment]
Hiya
.../pinned_libs_32 & .../pinned_libs_64 both have several files in them: 
![Untitled](https://user-images.githubusercontent.com/80121423/149638256-7f6f8215-17cc-4af2-9063-b768662b6dbd.png)
After moving the pinned_libs folders and restarting steam, the tray icon works again :crab:
Thanks a bunch
