### ISSUE TITLE
Multi-select on game list gets stuck

### ISSUE THREAD

**Issue by madprops** [ValveSoftware/steam-for-linux#8348]
* Steam client version (build number or date): 
Dec 16 2021
* Distribution (e.g. Ubuntu): 
Arch
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
No

GPU: AMD

It has happened twice that something triggers the multi select on the game list (check image). 

I don't know what triggers it, but when it happens I can't seem to find a way to exit it and select only one game.

If I trigger it manually with shift+click, the same happens, I can't exit the multi select mode.

The only way I've found to exit the mutli-select is to trigger a window update (resize, move, maximize, fullscreen).

![steamstuck](https://user-images.githubusercontent.com/206498/149670930-e2add890-b775-47af-ba4a-680a9286fef1.jpg)

**Comment by kisak-valve** [comment]
Hello @madprops, this issue is already being tracked at #3451. Closing as a duplicate.
