### ISSUE TITLE
Various problems when run as root on Mint 20.3

### ISSUE THREAD

**Issue by dvt-rcx** [ValveSoftware/steam-for-linux#8349]
Your system information
HP Envy x360
Graphics: Intel UHD Graphics 620 
Vendor: Hewlett-Packard 
Driver: i915 
Gist of full info: https://gist.github.com/dvt-rcx/bbaf43342b8e489c465af857e06623b0

* Steam client version (build number or date): Current
* Distribution (e.g. Ubuntu): Linux Mint 20.3 Una
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Unable to launch Steam via shortcuts, requires using terminal.
Upon launch all interfaces appear with black screen, no interactables (as seen here). 
![image](https://user-images.githubusercontent.com/97850615/149679071-bb29dafc-3a53-4f59-b710-2a5a221fba66.png)

Additionally, chat connection cannot be established, "Friends and chat" option brings up nothing, and attempting to use steam-dependent services such as multiplayer yields no results. This is despite login server functioning as expected. 

Games can be installed and launched via Big Picture mode, though other online services (chat, store, etc.) cannot be accessed. Games can also be launched through tray icon actions. 

Expected: Steam functions normally. 

#### Steps for reproducing this issue:

1. Use comparable hardware & drivers
2. Fresh install of Linux Mint 20.3
3. Install Steam through steampowered.com provided package file. 
4. Install, launch, login.

**Comment by kisak-valve** [comment]
Hello @dvt-rcx, if you completely close Steam, then run `steam` from a terminal, does the terminal spew give any hints? Also, if possible, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by dvt-rcx** [comment]
Will do shortly, device is currently obstructed by cat.

**Comment by dvt-rcx** [comment]
> does the terminal spew give any hints? 
This is what terminal is spewing for me, nothing that stands out to me:
![image](https://user-images.githubusercontent.com/97850615/149681015-6fd5ec57-6b33-4f0a-9c91-29ad0c37bb05.png)

Gist has been added to the post, but here is another link for redundancy:
https://gist.github.com/dvt-rcx/bbaf43342b8e489c465af857e06623b0

**Comment by kisak-valve** [comment]
For clarity, they question we're pondering here is why Steam's web component, libcef is failing to initialize.

Reading through your system information `/root/.steam/debian-installation` tells us you're running Steam as root, and you're using the distro-modified Steam package, not the Valve-provided Steam package like you initially claimed.

Running Steam as root is explicitly unsupported and provides absolutely no benefit to you. Please use a regular unprivileged user account. For most things, the difference in Steam packages don't really matter, but they do cause Steam to be installed with different folder layouts which moves things like the location of log files. The distro-modified Steam package could be intercepting hints and sticking it somewhere like `~/.steam/error.log`. Please share that log and `~/.steam/debian-installation/logs/steamwebhelper.log`.

As a secondary note, it appears you have the NVIDIA 390 series video driver installed. This shouldn't matter for the issue being pondered now, but keep it in mind if you have trouble down the road like https://github.com/ValveSoftware/steam-runtime/issues/420.

**Comment by dvt-rcx** [comment]
That does make sense, and I apologize if I misunderstood/misled with anything here. 

My trouble is that installing/running as root seems to be what's happening by default here. I've reinstalled a number of times through my Package Manager, running the installation file from steampowered.com, and straight from my Terminal. Evidently it's installed as root each time, and I don't know how to make it not do that. I haven't had this issue with any other program, but I am fairly new to Linux and I don't mean to waste your time with an issue that's not related to anything you can fix.


That said, if you have any guidance or know why this would be happening, I would greatly appreciate your help on this. 

I'm also unable to find any of those logs that you're referring to, my `/Steam/logs` folder seems to only contain `bootstrap_log.txt`

**Comment by DonKatsu** [comment]
#### Your system information

* Steam client version (build number or date): 1643690051 / 02-01-2022
* Distribution (e.g. Ubuntu): Fedora 35 KDE
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
[Full system information](https://gist.github.com/DonKatsu/80fc71d97ec782fe6900bf0f365ef461)
[Packages modified prior to experiencing this issue](https://gist.github.com/DonKatsu/605b6a0bf87607d093879c507700a585)

I restarted primarily for a mesa update, and after getting back to my desktop Steam installed the beta update I'm on now.
And now I have the same issue. Black/white pages, friends list won't open.

I don't have an error.log to share, but I have a console log and steamwebhelper.log.
[steam console log.txt](https://github.com/ValveSoftware/steam-for-linux/files/7976862/steam.console.log.txt)
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/7976864/steamwebhelper.log)

**Comment by DanMan** [comment]
Same issue here with latest beta on Fedora 35. The inner parts of all tabs (store, library, …) is all black.

Sysinfo: https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329

**Comment by BafDyce** [comment]
I am experiencing the same issue with my flatpak install on Arch Linux.

System information
```
Distro: Arch Linux
GPU: AMD AMD Radeon VII (VEGA20, DRM 3.42.0, 5.15.16-hardened1-1-hardened, LLVM 12.0.1)
Desktop Environment: KDE
Flatpak version: 1.12.4
Steam Flatpak version: 1.0.0.74 (updated today but the issue was also present with the previous installed version)
Steam Beta Opt-In: Yes

Operating System Version:
    Description:	Freedesktop.org 21.08.9 (Flatpak runtime) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.15.16-hardened1-1-hardened
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101003
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20220119.0
```

By switching from beta opt-in back to standard release, the issue disappears. So it seems to be related to some changes in the current beta version of Steam.

<details>
  <summary>Stdout log from `flatpak run com.valvesoftware.Steam`</summary>
  
```
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/fabian
DEBUG:root:Checking input devices permissions
INFO:root:Overriding TZ to Europe/Vienna
steam.sh[2]: Running Steam on org.freedesktop.platform 21.08.9 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[77]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
[2022-02-01 19:29:11] Startup - updater built Feb  1 2022 03:46:32
[2022-02-01 19:29:11] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Installing breakpad exception handler for appid(steam)/version(1643690051)
[2022-02-01 19:29:11] Loading cached metrics from disk (/home/fabian/.local/share/Steam/package/steam_client_metrics.bin)
[2022-02-01 19:29:11] Using the following download hosts for Public, Realm steamglobal
[2022-02-01 19:29:11] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-02-01 19:29:11] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-02-01 19:29:11] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1643690051)
[2022-02-01 19:29:11] Verifying installation...
[2022-02-01 19:29:11] Verification complete
Loaded SDL version 2.0.21-7043441
Installing breakpad exception handler for appid(steam)/version(1643690051)
steamwebhelper.sh[217]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)

(steam:155): GLib-GObject-CRITICAL **: 19:29:12.642: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
CAppInfoCacheReadFromDiskThread took 284 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
Installing breakpad exception handler for appid(steam)/version(1643690051)
assert_20220201192922_25.dmp[391]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220201192922_25.dmp
steamwebhelper.sh[393]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy

(steam:155): Gtk-WARNING **: 19:29:23.124: gtk_disable_setlocale() must be called before gtk_init()
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 216 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 216 -- steam
Installing breakpad exception handler for appid(steam)/version(1643690051)
assert_20220201192923_28.dmp[448]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220201192923_28.dmp
assert_20220201192922_25.dmp[391]: Finished uploading minidump (out-of-process): success = yes
assert_20220201192922_25.dmp[391]: response: CrashID=bp-c39ceed6-5d67-4015-8db7-f0fff2220201
assert_20220201192922_25.dmp[391]: file ''/tmp/dumps/assert_20220201192922_25.dmp'', upload yes: ''CrashID=bp-c39ceed6-5d67-4015-8db7-f0fff2220201''
Installing breakpad exception handler for appid(steam)/version(1643690051)
Connectivity test: result=Connected, in progress=0
roaming config store loaded successfully - 11434 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 14ms
Installing breakpad exception handler for appid(steam)/version(1643690051)
Installing breakpad exception handler for appid(steam)/version(1643690051)
assert_20220201192923_28.dmp[448]: Finished uploading minidump (out-of-process): success = yes
assert_20220201192923_28.dmp[448]: response: CrashID=bp-49c9802b-037b-4aef-9675-eccd82220201
assert_20220201192923_28.dmp[448]: file ''/tmp/dumps/assert_20220201192923_28.dmp'', upload yes: ''CrashID=bp-49c9802b-037b-4aef-9675-eccd82220201''
ExecCommandLine: "'/home/fabian/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 14.36 seconds
Installing breakpad exception handler for appid(steam)/version(1643690051)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[529]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 392 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 392 -- steam
Installing breakpad exception handler for appid(steam)/version(1643690051)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[583]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 528 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 528 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[636]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 582 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 582 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[689]: Runtime for steamwebhelper: defaulting to /home/fabian/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
<-- repeats every few seconds -->
```
</details>

**Comment by kisak-valve** [comment]
Hello @BafDyce, please give #8373 a read and see if that is the issue you're seeing instead of the issue reported here.

**Comment by BafDyce** [comment]
@kisak-valve Yes, the referenced issue is the same for me (same error message). Will give the suggested workaround a try and will report back there. Thanks for the quick response btw :)

**Comment by virnik0** [comment]
Is this similar to https://github.com/ValveSoftware/steam-for-linux/issues/8405 ?

**Comment by smcv** [comment]
In the hope that this will make it a bit more obvious what is going on here:

All the UI elements being black rectangles is a symptom, not a cause. It usually means the `steamwebhelper` component is crashing, which could happen for any number of reasons. If you are seeing this symptom, it might not be for the same reason as other people.

#8373 tracks at least three reasons this can happen, all of which were regressions in the beta branch of Steam (the non-beta branch is unaffected), and all of which can be worked around by running Steam with the `-no-cef-sandbox` option. The three causes discussed in #8373 are: 1. having a new version of glibc; 2. having a locked-down kernel where unprivileged users are not allowed to create new user namespaces (containers); 3. running Steam as a Flatpak app.

@DonKatsu is using Fedora 35 and mentioned on #8373 that `-no-cef-sandbox` is a successful workaround, so it seems that they were experiencing one of the variations of #8373 (probably the first one), so I'm going to ignore their comment on this issue.

@BafDyce is using Flatpak, so presumably they were affected by the third variation of #8373, and I'm going to ignore their comment on this issue.

#8405 tracks another cause for the same symptom, seen by @virnik0, which is *not* worked around by running Steam with the `-no-cef-sandbox` option. We don't know yet what is happening in #8405, and we don't have enough information to know whether #8349 and #8405 are the same.

It is probably best to assume they are *not* the same. If they're tracked as separate issues but are actually the same, then fixing one of them will turn out to solve the other one, at which point it's easy to close the second one as having been a duplicate. If they're tracked as one issue but are actually two separate things, then that has the potential to waste a lot of time on tracking which parts have been fixed and which parts have not.

**Comment by smcv** [comment]
Returning to what is happening to @dvt-rcx specifically:

> My trouble is that installing/running as root seems to be what's happening by default here. I've reinstalled a number of times through my Package Manager, running the installation file from steampowered.com, and straight from my Terminal. Evidently it's installed as root each time, and I don't know how to make it not do that.

Here's what is meant to happen:

* First you install the `.deb` package, somehow: either the Valve-provided `steam-launcher` package from `repo.steampowered.com` (preferred), or the `steam` package from Debian/Ubuntu/Mint (this is unofficial from Valve's perspective, but usually works). **This** step is installing a system-level package, so it has to be done with privileges - perhaps as root, or perhaps by using `sudo` or `pkexec`, or perhaps by using a PackageKit-based package manager like GNOME Software. The package contains the Steam "bootstrapper", which is a minimal version of Steam that is just large enough to download the rest.
* Then, **while logged in as an ordinary user**, you launch Steam for the first time, by using the Steam menu entry, a shortcut, or the `steam` command in a terminal. The "bootstrapper" downloads the rest of Steam and unpacks it into somewhere in your home directory, usually either `~/.local/share/Steam` or `~/.steam/debian-installation` (either one works).
* As the same ordinary user, every time you want to play Steam games, you launch Steam again by using the Steam menu entry, a shortcut, or the `steam` command in a terminal. The data in `~/.local/share/Steam` or `~/.steam/debian-installation` will be updated to the latest version automatically.

If you were installing the `.deb` package by logging in to a full GUI environment as `root`, then you should log out, log back in as an ordinary user, and launch Steam as the ordinary user.

If you were already logged in as an ordinary user, then it might help to describe exactly what you did to install and run Steam for the first time.

If you don't already have lots of games, saved data, etc., it might work best to remove the hidden directory `~/.steam` completely, and start again from a clean slate.

I suspect that the black rectangles might be caused by the web component that is meant to appear in those locations refusing to run as root for security reasons.

> using the distro-modified Steam package, not the Valve-provided Steam package like you initially claimed

It is possible that @dvt-rcx is *now* using the Valve-provided Steam package, but had previously run it from the distro-modified Steam package. If you run Steam from one of the Debian/Ubuntu/Mint-provided packages (which default to `~/.steam/debian-installation`), and subsequently switch to the Valve-provided package from `repo.steampowered.com` (which defaults to `~/.local/share/Steam`), it will continue to use `~/.steam/debian-installation` as the base directory of your Steam installation, to avoid losing your existing Steam data.

This should be harmless: the setup with `~/.steam/debian-installation` is unusual, but works. The really problematic scenario is with old Debian/Ubuntu/Mint packages that used `~/.steam` as the base directory (which was wrong), but if your installation path contains `debian-installation` then you have avoided that problem.
