### ISSUE TITLE
Inscryption recognized as a Linux native game, and get launched without Proton

### ISSUE THREAD

**Issue by Iwyil** [ValveSoftware/steam-for-linux#8350]
#### Your system information
* Steam client version (build number or date):  Built: Dec 16 2021, at 22:39:26
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

<details><summary>Hardware Info</summary>

```
Computer Information:
    Manufacturer:  LENOVO
    Model:  20L9CTO1WW
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.16.1-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101003
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20211207.0

Video Card:
    Driver:  Intel Mesa Intel(R) UHD Graphics 620 (KBL GT2)
    Driver Version:  4.6 (Compatibility Profile) Mesa 21.3.4
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x5917
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.39" x 7.48" (15.31" diag)
                                            34.0cm x 19.0cm (38.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC257

Memory:
    RAM:  23900 MB

There is also a secondary NVIDIA GPU MX150 which in this report is not detected.
```

</details>

#### Please describe your issue in as much detail as possible:
Inscryption IS NOT a Linux compatible game, it is a Windows only game, but it looks like Steam recognize it as a Linux native games, and neither install Proton, nor try to use it when trying to play.
1. In the game list, although Steam Play is disabled for both supported and unsupported games, Inscryption is always available for installation, just like any other Linux native game.
2. Installing Inscryption, even if Steam Play is enabled, does NOT also install Proton, or any other program
3. When I try to lunch the game, from the output of steam, it seems like steam is trying to directly execute Inscryption.exe (line 5)
```
/bin/sh\0-c\0$HOME/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1092790 -- '$HOME/.local/share/Steam/steamapps/common/Inscryption/Inscryption.exe'\0
Game process added : AppID 1092790 "$HOME/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1092790 -- '$HOME/.local/share/Steam/steamapps/common/Inscryption/Inscryption.exe'", ProcID 36680, IP 0.0.0.0:0
chdir $HOME/.local/share/Steam/steamapps/common/Inscryption
...
$HOME/.local/share/Steam/steamapps/common/Inscryption/Inscryption.exe: $HOME/.local/share/Steam/steamapps/common/Inscryption/Inscryption.exe: cannot execute binary file
GameAction [AppID 1092790, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 1092790, ActionID 2] : LaunchApp changed task to Completed with ""
Game process removed: AppID 1092790 "$HOME/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1092790 -- '$HOME/.local/share/Steam/steamapps/common/Inscryption/Inscryption.exe'", ProcID 36680

```
In the redacted line were just some errors about loading the steam overlay library, that come up also during the launch of Linux natives games (removed to reduce noise).

In the process of trying to solve the issue, I also reinstalled Steam, reinstalling from the package manager _and_  deleting all the Steam directories.

The expected result is Steam trying to launch the game using Proton. I experienced the correct behavior in the past (around 28th Dec 2021), but under different hardware and software (can't test said configuration now)

#### Steps for reproducing this issue:

1. Disable Steam Play
2. Install Inscryption (should not be possible)
3. Try to play Inscryption

**Comment by kisak-valve** [comment]
Hello @Iwyil, this issue should be reported to the game's dev(s). At a glance, it appears this game has a `mac-linux-beta` beta branch which is not public and a linux depot.

For now, pick a Proton version in the per-game settings to get the behavior you expected.

**Comment by Iwyil** [comment]
Thank you. I was not aware of the per game setting as an option to force the actual use of Proton. With the option set, the game runs flawlessly.
I will close the issue given that this problem apparently is not of Steam and that there is a solution
