### ISSUE TITLE
Xbox One Controller not working properly

### ISSUE THREAD

**Issue by bitshiftnetau** [ValveSoftware/steam-for-linux#8361]
#### Your system information

* Steam client version (build number or date): 
![steam](https://user-images.githubusercontent.com/26871600/151170641-8ba5acde-4171-4107-88ec-cdc98fe126e5.png)

* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] no idea
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Xbox One controllers don't work properly, for example right button is bringing up the start menu and the 3-stripe button doesn't work.

#### Steps for reproducing this issue:

1. Install steam on Arch
2. Use the Xbox One controller (bluetooth edition, model starts with 9 can't remember the rest)
3. Try to play any game, click right-button

**Comment by kisak-valve** [comment]
Hello @bitshiftnetau, are you using xpadneo? This reads like https://github.com/atar-axis/xpadneo/issues/303.

**Comment by bitshiftnetau** [comment]
No I'm not even using xpadneo as it doesn't support this controller. To be clear, it worked fine just before Christmas when using a Linux client to connect to a Windows machine over Remote Play. The timing may or may not be relevant, this may have always been broken on Linux who knows.

**Comment by bitshiftnetau** [comment]
Ok I installed xpadneo and it's now fixed. I really hate technology. I hate it so so much...
