### ISSUE TITLE
Mass Effect 2 not starting

### ISSUE THREAD

**Issue by ShalokShalom** [ValveSoftware/steam-for-linux#8369]
#### Your system information

* Steam client version (build number or date): 
![Screenshot_20220129_215806](https://user-images.githubusercontent.com/6344099/151677394-8e14cde3-2f41-452c-82ee-6d715619dc47.png)

* Distribution (e.g. Ubuntu): KaOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I launch Mass Effect 2.
A small box appears that lets me choose between the launcher and the game directly 

Whatever I choose, the game crashes. Immediately after I click on any of the two options, the blue STOP X button turns into a green PLAY again. 

I tried with both Proton 6 and the latest 5. 

System Info:
https://gist.github.com/ShalokShalom/1b495c231e99a59ad883fc567d9b7c2d

I use the Flatpak version.

**Comment by kisak-valve** [comment]
Hello @ShalokShalom, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1350#issuecomment-1024986302.
