### ISSUE TITLE
"ZZ_DO_NOT_USE Placeholder" Game showed up in library

### ISSUE THREAD

**Issue by Awk34** [ValveSoftware/steam-for-linux#8371]
#### Your system information

https://gist.github.com/Awk34/35e4b51cb33d59345424428bd037c44e

* Steam client version (build number or date): Jan 16 2022 17:34:49
* Distribution (e.g. Ubuntu): Mint
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I didn't see this in Windows. I rebooted into Mint and saw a "ZZ_DO_NOT_USE Placeholder" item in my library:

![Screenshot from 2022-01-30 14-53-24](https://user-images.githubusercontent.com/5545474/151721893-34542319-96bd-459e-870e-15b7d63faf84.png)

#### Steps for reproducing this issue:

1. Open Steam Library

**Comment by kisak-valve** [comment]
Apparently related to Age of Empires IV Ranked Seasons, appid 1892320.
