### ISSUE TITLE
Issues signing into Microsoft for Halo

### ISSUE THREAD

**Issue by bitshiftnetau** [ValveSoftware/steam-for-linux#8383]
#### Your system information

* Steam client version (build number or date): 
![steam](https://user-images.githubusercontent.com/26871600/152377376-3ed4d297-e785-4745-8a71-40b03c735676.png)

* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Apologies if this isn't the right place, but I have no idea where to go for this issue on Linux. 

There seems to be an issue with logging into Microsoft for Halo on steam. I haven't checked this on any other distribution or system, but I do know that the Microsoft servers are running just fine and I don't have any firewall rules setup which would preclude connection. I managed to get signed in on a previous installation of the same OS. I've tried deleting the MCC folder, uninstalling and re-installing Halo. Nothing works. 

#### Steps for reproducing this issue:

1. Download Steam
2. Download Halo
3. Attempt to login
4. Watch screen hang at password
5. After it fails, try again and watch it hang at the username level

**Comment by kisak-valve** [comment]
Hello @bitshiftnetau, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-1029132376.

**Comment by bitshiftnetau** [comment]
> Hello @bitshiftnetau, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [ValveSoftware/Proton#2907 (comment)](https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-1029132376).

Cool beans :) thanks for all your hard work!
