### ISSUE TITLE
STEAM rebuilding Shader cache every time logging in, even if nothing has changed

### ISSUE THREAD

**Issue by BloodyIron** [ValveSoftware/steam-for-linux#8394]
Thread #7306 was closed prematurely on this topic, so there's relevant stuff in there.

I'm on Ubuntu 20.04, and every single time I log into STEAM it recompiles shaders, even if I just rebooted after recompiling shaders just minutes prior. This is a real pain because it's just wasting electricity, heating my computer up, and other such unnecessary stuff on something that should have already been completed.

Can we please have this investigated? Everyone seems to be experiencing this.

**Comment by kisak-valve** [comment]
Hello @BloodyIron, this issue is already being tracked at #8076. Closing in favor of the older issue report.
