### ISSUE TITLE
Steam won't open (Artix Linux)

### ISSUE THREAD

**Issue by trollface42069** [ValveSoftware/steam-for-linux#8395]
#### System/Steam Information

* steam-1.0.0.74-1
* Artix Linux with OpenRC, Proprietary Nvidia Drivers
* Opted into a steam beta related to the UI but I don't remember specifically which one
   ^ Reinstalling steam via `# pacman -Sy steam` has not fixed the issue
* I have updated quite a few times 

#### The issue:
Upon starting steam in a terminal I am given this error, which after some help on the Artix Forums, I've been informed it's not very helpful and could mean a variety of issues.

#### The error
[tyler@desktop ~]$ steam
steam.sh[5420]: Running Steam on artix rolling 64-bit
steam.sh[5420]: STEAM_RUNTIME is enabled automatically
setup.sh[5492]: Steam runtime environment up-to-date!
steam.sh[5420]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2022-02-06 16:38:36] Startup - updater built Nov 22 2021 22:06:59
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(1642451672)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
^C
[tyler@desktop ~]$ 
#### End of error

I terminated it after the X Error because the program stalls and nothing happens after that, even after letting it sit for about an hour.
#### Error Reproduction

Unsure of how to reproduce the issue

**Comment by kisak-valve** [comment]
Hello @trollface42069, can you check if any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works? The NVIDIA proprietary driver requires that the video driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are installed and have exactly the same version to work properly. I suspect that when you installed the NVIDIA proprietary driver, you skipped installing the video driver's 32 bit userspace libraries, which should be in a system package named similarly to Arch's `lib32-nvidia-utils` package.

**Comment by trollface42069** [comment]
My nvidia version is 495.46-11 and my lib32-nvidia-utils version is 510.47.03-1, the latest available version of each of them. How can I check glxinfo32? I don't think I have 32 bit OpenGL applications to test the drivers with.

**Comment by kisak-valve** [comment]
That package version mismatch is your problem.

**Comment by trollface42069** [comment]
I should also add that I'm getting a new error:

[tyler@desktop ~]$ steam
steam.sh[18536]: Running Steam on artix rolling 64-bit
steam.sh[18536]: STEAM_RUNTIME is enabled automatically
setup.sh[18608]: Updating Steam runtime environment...
steam.sh[18536]: Can't find 'steam-runtime-check-requirements', continuing anyway
[tyler@desktop ~]$
