### ISSUE TITLE
Poor productivity and missing textures CS:GO vulkan.

### ISSUE THREAD

**Issue by Pasha115** [ValveSoftware/steam-for-linux#8399]
#### Your system information

* Steam client version - 1642451672 
* Distribution: Ubuntu
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

#### 
I decided to try using vulkan render in CS: GO (entering -vulkan in the startup parameters)
When I started the game, I noticed black textures not only on the houses, but also on the players' models. Sometimes white squares later appeared in their city instead of fonts. The game also crashes if you do not set "texture translation" in the graphics settings.

**Comment by Pasha115** [comment]
My pc- 
i3 4130
Intel HD 4400
4 GB memory

**Comment by kisak-valve** [comment]
Hello @Pasha115, the drivers for your Intel Haswell generation provides an incomplete, non-spec compliant Vulkan implementation. Graphical artifacts and crashes are likely with any Vulkan application. This is room for improvement on the video driver's side and is not a CS:GO issue.
