### ISSUE TITLE
Steam no longer loading up on Arch

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#8401]
#### Your system information

* Steam client version (build number or date): Can't check, won't load
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I upgraded to the latest version of Arch packages as of today, now Steam won't load up.

Log of it trying to load: https://gist.github.com/LiamDawe/d3ef8693101ee687bb426e461a5bebf1

Crash dump attached:

[crash_20220209143620_15.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/8033545/crash_20220209143620_15.tar.gz)

Not sure how to get you full system specs of everything as usual, since the Steam client won't load to grab it from there.

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libc-2.33.so coming from libnss_mymachines.so.2. Is the latter something that's changed recently by a system update?

**Comment by LiamDawe** [comment]
Upgrading again and....it now works fine.

So something something random upgrade fubar.
