### ISSUE TITLE
Steam picks up other OSes steam libraries & attempts to replace game files with Linux files

### ISSUE THREAD

**Issue by Virepri** [ValveSoftware/steam-for-linux#8403]
#### Your system information

* Steam client version (build number or date): Jan 16 2022, 17:34:49
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam should
A) not pick up other OS's steam libraries (since it is not a supported use case)
B) allow me to actually remove a steam library it autodetected (since I do not want the other OS's steam library attached)

#### Steps for reproducing this issue:

1. Create a steam library on Windows
2. Download a game with a Linux native version
3. Install steam with the drive containing the steam library mounted
4. Steam will auto-detect the library. Removing the library is impossible, because steam will auto-detect it again next startup.

#### Temporary mitigation

Disable automatic game updates (does not solve playing these games under Linux) or do not mount the drive (requires duplicate files).

**Comment by kisak-valve** [comment]
Hello @Virepri, this issue is already being tracked at #8353. Closing in favor of the older issue report.
