### ISSUE TITLE
Bad performance when downloading

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/steam-for-linux#8406]
For some reason Steam takes a huge amount of CPU power when downloading games.

This has been like this since forever, in all the computers that I have tried it. At least on Linux.

No other download application behaves like this. I'm sure that some algorithm is extremely inefficient there.

**Comment by kisak-valve** [comment]
Hello @es20490446e, this issue is already being tracked at #6684. Closing as a duplicate.
