### ISSUE TITLE
steam doesn't open - it did previously.  l

### ISSUE THREAD

**Issue by temper1234** [ValveSoftware/steam-for-linux#8414]
#### Your system information

* Steam client version (build number or date):  no clue - nothing comes up
* Distribution (e.g. Ubuntu): ArcoLinux
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No]  obviously yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. steam used to work.  then it would log me out whenever I started it.  now it is just blank.  
2. if I open steam in a terminal I get: steam.sh[76873]: Running Steam on arcolinux rolling 64-bit
steam.sh[76873]: STEAM_RUNTIME is enabled automatically
setup.sh[76946]: Steam runtime environment up-to-date!
steam.sh[76873]: Steam client's requirements are satisfied
max open descriptors set to 9216

2. 
3.

**Comment by kisak-valve** [comment]
Hello @temper1234, can you check if any OpenGL application like `glxinfo` works? Also, can you clarify what you mean by "just blank"?

Based just on the short terminal spew you've shared, we've seen a similar scenario before where an NVIDIA proprietary driver user updates their video driver, and NVIDIA's proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace have exactly the same version. If they aren't, then any OpenGL application can get stuck waiting on the video driver during initialization. If you're an NVIDIA user and allowed the package manager to do a video driver update recently, then the loaded kernel module for NVIDIA could still be the older version while the userspace libraries on disk are a newer version and the easiest way to clear that situation is to reboot the system.

**Comment by im20A0** [comment]
> Hello @temper1234, can you check if any OpenGL application like `glxinfo` works? Also, can you clarify what you mean by "just blank"?
> 
> Based just on the short terminal spew you've shared, we've seen a similar scenario before where an NVIDIA proprietary driver user updates their video driver, and NVIDIA's proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace have exactly the same version to work properly. If they aren't, then any OpenGL application can get stuck waiting on the video driver during initialization. If you're an NVIDIA user and allowed the package manager to do a video driver update recently, then the loaded kernel module for NVIDIA could still be the older version while the userspace libraries on disk are a newer version and the easiest way to clear that situation is to reboot the system.

I have the same issue. After I updated the NVIDIA driver from 470 to 510, steam launches without any response. After reboot it can sometimes start, but more often there is still no response.

**Comment by byohano** [comment]
> > Hello @temper1234, can you check if any OpenGL application like `glxinfo` works? Also, can you clarify what you mean by "just blank"?
> > Based just on the short terminal spew you've shared, we've seen a similar scenario before where an NVIDIA proprietary driver user updates their video driver, and NVIDIA's proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace have exactly the same version to work properly. If they aren't, then any OpenGL application can get stuck waiting on the video driver during initialization. If you're an NVIDIA user and allowed the package manager to do a video driver update recently, then the loaded kernel module for NVIDIA could still be the older version while the userspace libraries on disk are a newer version and the easiest way to clear that situation is to reboot the system.
> 
> I have the same issue. After I updated the NVIDIA driver from 470 to 510, steam launches without any response. After reboot it can sometimes start, but more often there is still no response.

I've also had the exact same issue as OP, couldn't start Steam again after having left it for awhile.
In that time frame, I did update my NVIDIA driver from 470 to 510. Just tried reverting it, and now Steam works! Seems like the NVIDIA driver version is the core problem. Thanks for the tip @im20A0 !
I find it weird though, because on my computer, I've never been able to make NVIDIA graphics work on Linux (from Linux Mint 20.1 to 20.3), so why would Steam look at a graphics card whose driver isn't even recognized by the OS? Mysterious.

**Comment by MiranDaniel** [comment]
Rebooting worked for me

**Comment by PixsaOJ** [comment]
Reverting is only a temporary solution, but how did you do it (so I can too)?

my output is just this:
```bash
➜  ~ steam
steam.sh[7493]: Running Steam on manjarolinux 21.3.1 64-bit
steam.sh[7493]: STEAM_RUNTIME is enabled automatically
setup.sh[7567]: Steam runtime environment up-to-date!
steam.sh[7493]: Steam client's requirements are satisfied
```

**Comment by Windy-wjf** [comment]
Just change  NVIDIA driver 5xx to 4xx and it will work.

**Comment by PixsaOJ** [comment]
That's not a solution
--  Sent from my p≡p for Android.

**Comment by Windy-wjf** [comment]
> That's not a solution.

It did worked for my computer  Ubuntu 22.04LTS.Your system info?

**Comment by PixsaOJ** [comment]
It worked for me as well. I replied. But thing is I want to use latest 
and greatest because new games are working on it, not 4xx.

Btw, last time i checked steam flatpak worked for like 1 day and its 
broken now.
I posted other info above.

**Comment by Edu4rdSHL** [comment]
For anyone experiencing this issue, that does happen when your current installed Nvidia Drivers are different from the ones our system has loaded, that is to say, your Nvidia drivers have been updated.

The fix is to just reboot ton make the drivers match again.

**Comment by im20A0** [comment]
> For anyone experiencing this issue, that does happen when your current installed Nvidia Drivers are different from the ones our system has loaded, that is to say, your Nvidia drivers have been updated.
> 
> The fix is to just reboot to make the drivers match again and then steam will open.

The fact is rebooting didn't work for me otherwise it wasn't an issue
