### ISSUE TITLE
Context menu of the tray icon doesn't contains any items.

### ISSUE THREAD

**Issue by fomich-artem** [ValveSoftware/steam-for-linux#8425]
#### Your system information

* Steam client version (build number or date): Jan 16 2022, at 17:34:49 (manual typed, your client won't even let you copy the build number!!!)
* Distribution (e.g. Ubuntu):  Ubuntu 20.04.3 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The context menu of the tray icon should contain menu items. Recently, it has ceased to contain any menu items (see attached screenshot).

#### Steps for reproducing this issue:

1. Launch Steam client in Ubuntu MATE 20.04.3 LTS (64 bit)
2. Left mouse click on the tray icon.
3. Context menu of the tray icon doesn't contains any items!

![изображение](https://user-images.githubusercontent.com/1716311/155063877-7d1815f2-8d0d-4bc1-8bc2-c046557a4b26.png)

**Comment by kisak-valve** [comment]
Hello @fomich-artem, can you check if going to `~/.steam/root/ubuntu12_32/steam-runtime` and deleting the `pinned_libs*` folders so that those folders regenerated the next time Steam is started has an effect after Steam is restarted?

**Comment by fomich-artem** [comment]
> Hello @fomich-artem, can you check if going to `~/.steam/root/ubuntu12_32/steam-runtime` and deleting the `pinned_libs*` folders so that those folders are regenerated the next time Steam is started has an effect after Steam is restarted?

Yes, it helps me! Thank you very much!

`rm -rf ~/.steam/root/ubuntu12_32/steam-runtime/pinned_libs*`

**Comment by kisak-valve** [comment]
Thanks for testing. Closing in favor of #5222.
