### ISSUE TITLE
Can't use desktop client with a pad

### ISSUE THREAD

**Issue by legacychimera247** [ValveSoftware/steam-for-linux#8426]
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): fedora workstation 35
* Opted into Steam client beta?: [Yes/No] yes, then reverted back
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I generally use the big picture with my steam controller, but i wanted to have the fps counter for a game so i set the desktop mode. As soon as i started the game (in desktop mode) the big picture overlay started and upon closing the game the big picture was semitransparent but clearly overlapping the desktop interface. I guess there's no way to play with a pad and the desktop mode

#### Steps for reproducing this issue:

1. Open the desktop mode
2. Launch a game with the controller on
3. See the big picture overlay launching instead of the desktop one

**Comment by kisak-valve** [comment]
Hello @legacychimera247, this sounds like the intended behavior if the checkbox at `Steam` -> `Settings` -> `In-Game` -> `Use the Big Picture Overlay when using a Steam Input enabled controller...` is enabled. Please check that setting.

**Comment by legacychimera247** [comment]
hello, i think the enabled function has some bugs, for example steam is opened in either big picture and desktop mode after i close the game with the big picture overlay selected

anyway i don't care cause your suggestion solved my problem, guess we can close this one or you want to investigate the other issue?

**Comment by kisak-valve** [comment]
Thanks for checking the user setting. If you want to pursue the follow up issue, then it would be better if that issue is tracked separately from this issue report since it doesn't sound related to the original issue.
