### ISSUE TITLE
Steam won't start at all - steam.sh: line 794: Segmentation fault 

### ISSUE THREAD

**Issue by Vaults** [ValveSoftware/steam-for-linux#8430]
#### Your system information

* Steam client version (build number or date): Nov 22 2021 22:06:59 (after reinstall)
* Distribution (e.g. Ubuntu): Linux Mint 20
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam will not start anymore. I've tried rebooting, purging the package, deleting all the files, reinstalling for the same error to happen. This happened after a AMDGPU driver update. Running driver version amdgpu-core/bionic,bionic 21.50.50000-1373630, now.

Output:
```
steam.sh[26918]: Running Steam on linuxmint 20 64-bit
steam.sh[26918]: STEAM_RUNTIME is enabled automatically
setup.sh[27081]: Steam runtime environment up-to-date!
steam.sh[26918]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2022-02-22 17:10:58] Startup - updater built Nov 22 2021 22:06:59
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
crash_20220222171058_2.dmp[27171]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220222171058_2.dmp
/home/marcel/.local/share/Steam/steam.sh: line 794: 27168 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20220222171058_2.dmp[27171]: response: CrashID=bp-3eff9e7a-10e4-449a-ae22-213602220222
crash_20220222171058_2.dmp[27171]: file ''/tmp/dumps/crash_20220222171058_2.dmp'', upload yes: ''CrashID=bp-3eff9e7a-10e4-449a-ae22-213602220222''
```
dmesg:
```
[ 2991.677141] steam[26772]: segfault at 0 ip 0000000000000000 sp 00000000ffe0fa8c error 14 in steam[56587000+5d6000]
[ 2991.677153] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
```

**Comment by Vaults** [comment]
Issue was fixed by fixing the AMD scripts such that an uninstall is possible and reinstalling them.

**Comment by photodiode** [comment]
What AMD script are you referring to?
I have the same problem but can't seem to find a fix for it..

**Comment by Vaults** [comment]
@photodiode I didn't document my process, but what I did in general was to just fix my borked install such that I could purge anything that had to do with the AMD packages, get the latest amdgpu-install and reinstall all the packages (the configuration that works for me right now is ```amdgpu-install --usecase=graphics,opencl,hip --vulkan=amdvlk,pro```. I don't remember exactly what but I had to edit around a bit in the amdgpu-install script to get the uninstall working. I hope you get it fixed, the AMD drivers aren't the easiest to fix in the broken state they're shipped.

**Comment by ruanformigoni** [comment]
Had the same issue here on arch, the fix was to reinstall like this:

```
sudo pacman -Rs amdvlk lib32-amdvlk steam
```

```
sudo pacman -S mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon steam
```

I did replace amdvlk for vulkan-radeon, but if I go back to amdvlk it works now, weird.

**Comment by suchipi** [comment]
For me, the fix was to manually opt out of steam beta update by deleting `~/.local/share/Steam/package/beta`.
