### ISSUE TITLE
No notifications on new unread chat messages is appearing on the desktop integration

### ISSUE THREAD

**Issue by notmorganfreewoman** [ValveSoftware/steam-for-linux#8434]
#### Your system information

* Steam client version (build number or date): 

![image](https://user-images.githubusercontent.com/98706845/155288258-02d5edcf-60d3-48e0-9f62-ca020712e41e.png)

* Distribution (e.g. Ubuntu): 

Ubuntu/Mint

* Opted into Steam client beta?: [Yes/No]

No

* Have you checked for system updates?: [Yes/No]

Yes

#### Please describe your issue in as much detail as possible:

No notifications on new unread chat messages is appearing on the desktop integration

#### Steps for reproducing this issue:

1. Log into steam client
2. Receive new chat

Expected notification on the desktop to get my attention to check the steam chat client for messages

No integrated desktop notification bell icon and message that appears with other applications.

The only notification is on the steam friends list, which would be unfocused and minimised or not open at all thus will not get the attention as no notification is received on the desktop.

For more information, perhaps https://specifications.freedesktop.org/notification-spec/latest/ is useful?

**Comment by kisak-valve** [comment]
Hello @notmorganfreewoman, integration with desktop notifications is already being tracked at #46. Closing as a duplicate.
