### ISSUE TITLE
Gamepad (Controller) "Microsoft XBOX Wireless" not working with Horizon Zero Dawn

### ISSUE THREAD

**Issue by roenck** [ValveSoftware/steam-for-linux#8437]
#### Your system information

* Proton Experimental 
* Ubuntu 20.04.3 LTS, Kernel 5.13.0 + hid_xpadneo
* XBox Wireless controller (M) with bluetooth and/or just USB-link

#### Please describe your issue in as much detail as possible:

MS XBox Wireless controller not working within Horzion Zero Dawn.

Check against ""WINEPREFIX=~/.steam/steam/steamapps/compatdata/1151640/pfx ~/.steam/steam/steamapps/common/Proton\ -\ Experimental/files/bin/wine control" indicate that the controller itself is working in wine environment.

Important: The controller is workig within other games running into Proton.

#### Steps for reproducing this issue:

1. Make the gamepad working (/dev/input/js0 available) 
2. Install Horizon Zero Dawn within Ubuntu 20 and latest Steam client
3. Check controller is working wihtin Wine-Environment created for HZD --> is working
4. Start HZD and check if controller is available --> never works

**Comment by kisak-valve** [comment]
Hello @roenck, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-1050300020.
