### ISSUE TITLE
CSGO isnt working in my linux

### ISSUE THREAD

**Issue by liskovia** [ValveSoftware/steam-for-linux#8438]
![Screenshot from 2022-02-25 13-43-16](https://user-images.githubusercontent.com/85588559/155717206-af47e66a-8251-450c-8b9a-467f5ef819b0.png)
![Screenshot from 2022-02-25 13-45-29](https://user-images.githubusercontent.com/85588559/155719481-eeb50f66-6899-43a6-bf86-cf0d1756d3b7.png)

![Screenshot from 2022-02-25 13-46-54](https://user-images.githubusercontent.com/85588559/155717664-9b601bbd-1bb4-40f4-95f3-92ba48d2ad70.png)
![Screenshot from 2022-02-25 13-47-07](https://user-images.githubusercontent.com/85588559/155717673-1f77345c-2f78-41f7-8df2-b3bd83c0915a.png)

I recently installed a new Linux distribution "Pop! OS"
and I had to reinstall all my games and programs. There was no problem with all the games, but after installing CSGO, it wouldn't work (the CSGO window opens and closes after a few seconds). CSGO is natively made for linux so I did not have to use Proton but after an error I tried to turn on CSGO through proton but it did not work this time even the window did not start and a message was displayed to check if I have the latest version of steam. I uninstalled and installed the game but that didn't help either. I enclose in the message screenshots of the specifications of my computer.

**Comment by kisak-valve** [comment]
Hello @liskovia, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2659 / https://github.com/ValveSoftware/csgo-osx-linux/issues/2815. Closing as a duplicate.
