### ISSUE TITLE
Steam overlay semi-transparent black in upper right quarter

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#8440]
![Screenshot_20220227_103310](https://user-images.githubusercontent.com/62955221/155884618-cf885bab-1a4b-4ee3-a261-873e0e5bec25.png)

I made an little example video, for better understanding.
https://youtu.be/Nx4dEvxJU80

#### Your system information

* Steam client version (build number or date): **V020 | 1642451672 | Jan 16 2022**
* Distribution (e.g. Ubuntu): **Debian 11 Bullseye**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Steps for reproducing this issue:

1. Open Any Steam Panel Compatible Game
2. Try opening the steam panel
3. FAIL, **it doesn't work at all**

#### what i wanted to work;
be able to access the steam panel, and thus, use the friends list, browser, etc.

**Comment by kisak-valve** [comment]
Hello @ludwig-VHS, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ludwig-VHS** [comment]
> Hello @ludwig-VHS, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

https://gist.github.com/ludwig-VHS/1ece4e75440f6d80abad975d47db1c50

Here

**Comment by Ristovski** [comment]
@kisak-valve I have the same issue, sysinfo: https://gist.github.com/Ristovski/5fa833b6f55a7b4857a46c83b3bf442d
Let me know if I can debug this somehow.

**Comment by Bugaboo2000** [comment]
I was experiencing the same issue. Downloading adriconf and setting a configuration to disable mesa errors log solved for me.
