### ISSUE TITLE
Feature request: Support of Android kernels lacking System V IPC

### ISSUE THREAD

**Issue by Heasterian** [ValveSoftware/steam-for-linux#8442]
There are more and more options to run Linux apps next to Android, using chroot or proot or Linux with Hallium and emulators like box86/64 or FEX that can start Steam on ARM Linux are also avaliable so it would be nice if slowly Steam support would come to set ups like this. Specially at this moment when gaming machines are getting more expensive and phones much faster, 

Could it be possible to implement fallback to Binder IPC when System V IPC is not avaliable? It should make Steam working with Android kernel.

**Comment by kisak-valve** [comment]
Hello @Heasterian, running Steam on ARM systems is not supported. This reads like something the emulated environment should provide for compatibility if it's not readily available regardless of application.

**Comment by SupinePandora43** [comment]
> running Steam on ARM systems is not supported.

We'll see
