### ISSUE TITLE
No graphic while trying to stream my game in Wayland.

### ISSUE THREAD

**Issue by laichiaheng** [ValveSoftware/steam-for-linux#8444]
#### Your system information

* Steam client version (build number or date): Feb 22, 2022
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Server Side: Yes, Client Side: No.
* Have you checked for system updates?: [Yes/No] Yes.

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Stream successfully like in Xorg.

#### Steps for reproducing this issue:

1. Try to stream games to another PC in Wayland.

**Comment by kisak-valve** [comment]
Hello @laichiaheng, this issue is already being tracked at #6148. Closing as a duplicate.
