### ISSUE TITLE
Content of chat windows is not in correct position, breaking buttons

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#8446]
#### Your system information

* Steam client version (build number or date): steam-runtime_0.20211207.0
* Distribution (e.g. Ubuntu): Manjaro (Windows 10 too)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When receiving a chat message or opening a chat window, the button to minimize, maximize, and close the chat window are not working and are not in their proper position (they are higher). You can also see the issue at the bottom where a black bar appears (the size of the position difference for the buttons in top right corner, as if all the window content is higher), and the emoticon and share file buttons are higher but reach the bottom of the window inside the black bar zone.

Image for reference: https://i.imgur.com/oHu86xp.jpg

Resizing the chat windows sometimes repair the content and moves everything in position.

Problem is similar on the Windows client too after verification a few weeks ago.

#### Steps for reproducing this issue:

1. Open chat window
2. Notice the buttons on top right corner not working and higher than correct position, notice bottom of chat window issues too.

**Comment by kisak-valve** [comment]
Hello @Zorrototo, this issue is already being tracked at #8363. Since this issue report is fairly well written, I've gone ahead and transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/8363#issuecomment-1055625956.

Closing as a duplicate.
