### ISSUE TITLE
Steam crashes as soon as I open it

### ISSUE THREAD

**Issue by gaetano-foster** [ValveSoftware/steam-for-linux#8452]
![weird_colors](https://user-images.githubusercontent.com/70331267/156848639-1dc6034c-19ce-4604-a1bc-c8c4dfe16be3.png)
#### Your system information

* Steam client version (build number or date): March 4, 2022
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I am experiencing a crash in which steam displays a discolored "Updating Steam" window, and then closes. I have also tried running steam via the terminal, and it has shown error messages such as "XError: BadWindow". I have attached a screenshot of the yellow window and a text file with the exact terminal output.

If it helps, here are my PC's specs:

OS: Ubuntu 20.04.4 LTS
Graphics Card: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A]
Processor: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz 64 bit
RAM: 15 GB
Disk Space: 916 GB, 548 Availible

If any more information is required, please do specify!
Also, here are some things I have already tried:
- Downgrading graphics drivers
- Upgrading graphics drivers
- Reinstalling steam
- Installing more libs
- Running with STEAM_RUNTIME=0 (terminal output for this is also attached)
- Running steam --reset

It seems nothing I have tried has worked, so I've come here in search of help. Thank you in advance.

#### Steps for reproducing this issue:

1. open the terminal
2. type "steam"

[steam_output_RUNTIME_0.txt](https://github.com/ValveSoftware/steam-for-linux/files/8189011/steam_output_RUNTIME_0.txt)
[steam_output_normal.txt](https://github.com/ValveSoftware/steam-for-linux/files/8189012/steam_output_normal.txt)
![weird_colors](https://user-images.githubusercontent.com/70331267/156848769-e6d35377-29dd-4df4-a4f4-ff33a7174352.png)

**Comment by kisak-valve** [comment]
Hello @gaetano-foster, disabling the Steam runtime is unsupportable, and not going to help troubleshoot.

Does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of `mesa-utils` work? Unfortunately, Ubuntu doesn't provide a 32 bit build of this package on 20.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

I suspect your system is configured to use the NVIDIA proprietary driver, but doesn't have the video driver's 32 bit userspace libraries installed. If that's the case, then you'll want to identify which driver series you're using, then run something like `sudo apt install libnvidia-gl-510:i386` (replace 510 with the driver series you're using) to ask apt to install them. If that command wants you to remove packages, DO NOT let it proceed.

**Comment by gaetano-foster** [comment]
Ok, I installed the `libnvidia-gl-510:i386` package and reinstalled mesa-utils. However, it still crashes, although it gives a slightly different message. It's almost the same as the previous, but not it says
`Gtk-Message: 19:38:45.660: Failed to load module "overlay-scrollbar"`
`Gtk-Message: 19:38:45.662: Failed to load module "canberra-gtk-module"`

What can I do from here?

**Comment by kisak-valve** [comment]
A separate line of thought, could you be using a 30 bit display? (#4399)

The gtk messages are non-fatal.

**Comment by gaetano-foster** [comment]
Yes, I just tried and it seems that was the problem. Thank you for your time!
