### ISSUE TITLE
After update steam stopped to close properly, all games stopped to work.

### ISSUE THREAD

**Issue by kindagoose** [ValveSoftware/steam-for-linux#8453]
ryzen 5600x
3060 ti proprietary drivers
everything is up to date

* Steam client version (build number or date): Mar 5 2022
* Distribution (e.g. Ubuntu): archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

All games native and proton stopped to work, some stuck on "Preparing to launch" window, others launch and immediately crash or just run but nothing happens and steam think they still work. Steam itself don't close properly, impossible to run it again until all related processes are killed. I tried different proton versions and beta client, no difference.

ps. games thru heroic launcher work fine.

Log:
[(https://gist.github.com/)](https://gist.github.com/kindagoose/ef2c81cad855204e58677fd92cf34a08)

#### Steps for reproducing this issue:
Normal use.

**Comment by GKasparov** [comment]
Can reproduce this issue, I'm experiencing this on Arch Linux with the latest steam update (Beta). This issue however seems to not occur when I am using PulseAudio, occurs for me with Pipewire with Wireplumber.

**Comment by Gaurav-Singh-97** [comment]
Similar thing happening with me on Manjaro as well, except it seems some native linux games can be launched (CSGO (although crashes within a minute after launch), Poly Bridge 2) but windows games that ran through wine (Freeways, Rise of Nations, etc) don't launch anymore.

**Comment by GKasparov** [comment]
Yep, native games mostly seem fine for me (not much out of the ordinary). This issue seems to be occurring with titles running through SteamPlay

**Comment by kindagoose** [comment]
> Can reproduce this issue, I'm experiencing this on Arch Linux with the latest steam update (Beta). This issue however seems to not occur when I am using PulseAudio, occurs for me with Pipewire with Wireplumber.

I am on pulseaudio.

**Comment by GKasparov** [comment]
> > Can reproduce this issue, I'm experiencing this on Arch Linux with the latest steam update (Beta). This issue however seems to not occur when I am using PulseAudio, occurs for me with Pipewire with Wireplumber.
> 
> 
> 
> I am on pulseaudio.

Apologies, when I referred to Pipewire being the issue that was actually a different yet similar crash. Can confirm that even with PulseAudio there are games failing to launch or ones that take way too long to start and are buggy during play.

**Comment by kindagoose** [comment]
A little update, I tried to make a clean install (no ".steam" folder or anything related in "/local/share/") and steam app now closes properly, but as soon as I install any game it fails to do so until new clean install.
