### ISSUE TITLE
The pop-up window when you want to close a game from the client showed wrong text.

### ISSUE THREAD

**Issue by ReShout876** [ValveSoftware/steam-for-linux#8454]
#### Your system information

* Steam client version (build number or date): Date - Mar 5 2022; Version - 1646446125
* Distribution : Debian 11
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I was playing some War Thunder and the game didn't started properly, I wanted to close it using the close button from my library.
I got this pop-up window:
![appoverlay](https://user-images.githubusercontent.com/63971777/156897178-bb2fef20-c351-4764-a451-58e5f23bbef5.png)

#### Steps for reproducing this issue:

1. Have a game running
2. Press the close button

I am not sure if this is random or no.

#### EDIT
It isnt random, it appeared again!

**Comment by kisak-valve** [comment]
Hello @ReShout876, this issue is already being tracked at #8388. Closing as a duplicate.
