### ISSUE TITLE
Elden ring fails to load more often than not

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/steam-for-linux#8455]
#### Your system information

* Steam client version (build number or date): Mar 5 2022 at 01:40:21
* Distribution (e.g. Ubuntu): Fedora 35
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Desktop Environment: Gnome Classic

#### Please describe your issue in as much detail as possible:

Elden Ring plays well once started (apart from using Desktop Controller Configuration rather than that of game, and not stopping), but it fails to load more often than not. There three different ways that it doesn't start:

1. Game Launcher popup doesn't get displayed (nothing appears to happen but steam thinks it's running)
2. Game Launcher popup opens then disappears but no window gets opened (nothing is displayed here and have to close in steam)
3. Game Launcher popup opens and window opens but is black screen (nothing progresses, just black screen. need to switch to steam to stop in)
4. (success) Game Launches popup opens and window appears with white background (game load proceeds normally)

Elden Ring Launch options: PROTON_NO_FSYNC=1 gamemoderun %COMMAND% -windowed

#### Steps for reproducing this issue:

1. Launch elden ring
6. Try again

**Comment by kisak-valve** [comment]
Hello @abc-mikey, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1059957029.
