### ISSUE TITLE
Elden Ring Fails to stop

### ISSUE THREAD

**Issue by abc-mikey** [ValveSoftware/steam-for-linux#8456]
#### Your system information

* Steam client version (build number or date): Mar 5 2022 at 01:40:21
* Distribution (e.g. Ubuntu): Fedora 35
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Desktop Environment: Gnome Classic

#### Please describe your issue in as much detail as possible:

Elden Ring does not exit when stopped. The window disappears but the music keeps playing and Steam thinks it is running. Have to force stop with Steam.

Elden Ring Launch options: PROTON_NO_FSYNC=1 gamemoderun %COMMAND% -windowed

#### Steps for reproducing this issue:

1. Launch elden ring
2. Exit Elden Ring

**Comment by kisak-valve** [comment]
Hello @abc-mikey, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1059957029.
