### ISSUE TITLE
"Steam Play" pop-up dialog is not responding to input

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/steam-for-linux#8466]
#### Your system information

* Steam client version (build number or date): 5.3.2022 01:40:21
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When "Steam Play" pop-up dialog appears ("This game will run in compatibility mode..") it does not react to input: clicking at continue does nothing. The "preparing to start" pop-up dialog is also open at that time so perhaps the input is going to the wrong window for some reason?

This problem seems to appear and disappear at different releases and appears randomly by state of the moon, blood pressure or some other factor I haven't figured out.
This might be related to other issues where the client stops responding if you happen to have a browser running or client is on wrong display or another random reason.
When the problem appears the dialog seems broken somehow: it is hard (impossible) to move and does not appear on desktop overview like normal windows would.

Suggestion: integrate that notification into the same pop-up that already shows installation status (when starting the game requirements are installed). This would reduce clutter and reduce the possibility that the dialogs are interfering with each other.

#### Steps for reproducing this issue:

1. Go to Steam library
2. Select a game which requires compatiblity tool (Proton) and that you have not started yet.
3. When the pop-up dialog appears you may find it hard to close and proceed. Or maybe not.

**Comment by joghert** [comment]
See: https://www.reddit.com/r/linux_gaming/comments/t87rkn/a_little_psa_for_those_using_steam_with_pipewire/

**Comment by ipr** [comment]
> See: https://www.reddit.com/r/linux_gaming/comments/t87rkn/a_little_psa_for_those_using_steam_with_pipewire/

Interesting, but I don't use big picture mode since it is too sluggish in my experience.

**Comment by ipr** [comment]
Problem is gone now, there was update to wireplumber so maybe that was the issue to begin with.

Closing this for now.
