### ISSUE TITLE
Controller Configuration Never Loads for Elden Ring

### ISSUE THREAD

**Issue by OskergMonReap** [ValveSoftware/steam-for-linux#8470]
#### Your system information

* Steam client version (build number or date): Mar 9 2022 at 05:48:15
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Controller Configuration option for Elden Ring never loads, its the 3 bars to infinity. Loads perfectly fine for every other game, already attempted uninstall/reinstall of both the game and steam itself, opt in/out client beta, delete cookies/cache within steam's web browser, cleared downloads, etc.

Issue happens 100% of the time for both Xbox One and DualSense controllers (wired and bluetooth). Only happening with Elden Ring on my PC, tested literally on every other game I own and no issues

#### Steps for reproducing this issue:
Unsure, its 100% of the time for me on my machine.
1. Connect controller (wired or bluetooth, xbox or dualsense)
2. Open steam, right click Elden Ring -> Manage -> Controller Configuration
3. Watch it hang to eternity

**Comment by Dhamma-valence** [comment]
Exactly the same thing has been happening to me. Strangely the flatpak version, with the exact same settings works. Unfortunately that version of steam crashes when I try to use the new Mesa (22.08) for incredibly improved fps with the error  `glxchoosevisual failed`. So now I'm stuck choosing between terrible fps on one version, and my controller not working on the other. And that's not even mentioning the fact that Elden Ring only launches with Proton-GE-7.1-2 and any other version crashes.

**Comment by OskergMonReap** [comment]
I agree with the overall statement, though I must say this game has severe papercuts on Windows too (I've spent more time tshooting my buddy's Windows PC than my own here, he hasn't been able to play whatsoever still). This is obviously a steam issue though, so a bit off topic

FYI, I've had great luck with Elden Ring on GE-Proton7-9

**Comment by Dhamma-valence** [comment]
That's interesting that GE-Proton7-9 works for you, as it only gives me a white screen, while GE-Proton7.1-2 seems to work perfectly on flatpak steam, though the mesa-related fps are rough.

**Comment by OskergMonReap** [comment]
@Dhamma-valence so, after the most recent steam beta client update (3/10/22 build date), the controller configuration started working for me on Elden Ring. How are things on your end? Let me know, I'll keep this issue open if you're still hitting this

**Comment by MabaKalox** [comment]
Same issue, dualsense + steam beta, proton bleeding edge: controller config wont load.
