### ISSUE TITLE
Steam wount opening "Unable to determine whether the expected Nvidia drivers are available - An X Error occurred"

### ISSUE THREAD

**Issue by Termoinador** [ValveSoftware/steam-for-linux#8486]
#### Your system information

* Steam client version (build number or date): 
* Distribution: Debian 11
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1)
	Subsystem: Gigabyte Technology Co., Ltd GA102 [GeForce RTX 3080] [1458:4040]
	Kernel driver in use: nvidia

#### Please describe your issue in as much detail as possible:
I have installed the latest version of debian. After that I have installed the latest NVIDA-Driver from www.nvidia.com.
I have installed steam and when I try to launch steam I get the following:

Unable to determine whether the expected Nvidia drivers are available.
The Steam client may have limited functionality.
steam.sh[4747]: Running Steam on debian 11 64-bit
steam.sh[4747]: STEAM_RUNTIME is enabled automatically
setup.sh[4880]: Steam runtime environment up-to-date!
steam.sh[4747]: Steam client's requirements are satisfied
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2022-03-17 18:22:38] Startup - updater built Mar 14 2022 19:48:46
Installing breakpad exception handler for appid(steam)/version(1647446817)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  GLXBadContext
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  51
xerror_handler: X failed, continuing
Major opcode of failed request:  152 (GLX)
Minor opcode of failed request:  6 (X_GLXIsDirect)
Serial number of failed request:  52
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2022-03-17 18:22:38] Loading cached metrics from disk (/home/termo/.local/share/Steam/package/steam_client_metrics.bin)
[2022-03-17 18:22:38] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2022-03-17 18:22:38] Using the following download hosts for Public, Realm steamglobal
[2022-03-17 18:22:38] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1647446817)
[2022-03-17 18:22:38] Checking for update on startup
[2022-03-17 18:22:38] Checking for available updates...
[2022-03-17 18:22:38] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1647446817)
[2022-03-17 18:22:38] Download skipped: /client/steam_client_ubuntu12 version 1647446817, installed version 1647446817, existing pending version 0
[2022-03-17 18:22:38] Nothing to do
[2022-03-17 18:22:38] Verifying installation...
[2022-03-17 18:22:38] Performing checksum verification of executable files
[2022-03-17 18:22:38] Verification complete
Loaded SDL version 2.0.21-7140709
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  152
Serial number of failed request:  58
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  57
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  59
xerror_handler: X failed, continuing
crash_20220317182238_4.dmp[5047]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220317182238_4.dmp
/home/termo/.local/share/Steam/steam.sh: Zeile 794:  4968 Speicherzugriffsfehler  "$STEAMROOT/$STEAMEXEPATH" "$@"

**Comment by Termoinador** [comment]
Solved. Reinstalled everything and now it works

**Comment by baifachuan** [comment]
Excuse me,  are you reinstalling Nvidia drivers or reinstalling Steam and Games?
