### ISSUE TITLE
Not possible to connect to WPA3 network from game mode on Deck

### ISSUE THREAD

**Issue by frikisama** [ValveSoftware/steam-for-linux#8497]
#### Your system information

* Steam client version (build number or date): Latest Deck update
* Distribution (e.g. Ubuntu): SteamOS 3.0
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Current: Upon trying to connect to WPA3 networks in game mode on the Deck, the user doesn't get asked for WiFi passphrase and the connection fails. There is also no option to enter the passphrase manually as with WPA2.

Connecting through desktop mode works, and if saving the passphrase for all users it continues to work when switching to game mode too.

Expected: When trying to connect to a WPA3 network in game mode, the user gets asked for the WiFi passphrase, and the Deck connects to the network. There is also an option to enter the passphrase manually.

#### Steps for reproducing this issue:

See above.

**Comment by iMonZ** [comment]
> #### Your system information
> * Steam client version (build number or date): Latest Deck update
> * Distribution (e.g. Ubuntu): SteamOS 3.0
> * Opted into Steam client beta?: [Yes/No] NO
> * Have you checked for system updates?: [Yes/No] YES
> 
> #### Please describe your issue in as much detail as possible:
> Current: Upon trying to connect to WPA3 networks in game mode on the Deck, the user doesn't get asked for WiFi passphrase and the connection fails. There is also no option to enter the passphrase manually as with WPA2.
> 
> Connecting through desktop mode works, and if saving the passphrase for all users it continues to work when switching to game mode too.
> 
> Expected: When trying to connect to a WPA3 network in game mode, the user gets asked for the WiFi passphrase, and the Deck connects to the network. There is also an option to enter the passphrase manually.
> 
> #### Steps for reproducing this issue:
> See above.

Any news on that?
It’s pretty useless to use my deck just with Ethernet…

**Comment by cmcgroarty** [comment]
I was unable to add a WPA3 network when I first powered on my Steam Deck (received today) however after the initially downloaded update, I was able to add the same WPA3 network without switching to Desktop mode, and removed the WPA2 network I had fallen back on, and everything has been working fine so far.

**Comment by frikisama** [comment]
This seems to be solved. Closing. Thanks!
