### ISSUE TITLE
Steam cannot find libpipewire after Manjaro system update

### ISSUE THREAD

**Issue by AshtonSnapp** [ValveSoftware/steam-for-linux#8505]
#### Your system information

* Steam client version (build number or date): 1647446817
* Distribution (e.g. Ubuntu): Manjaro Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After installing a system update, Steam refuses to run as trying to load `libpipewire-0.3.so.0` fails stating it cannot find the file. The file does exist - however, it is a symbolic link to `libpipewire-0.3.so.0.348.0`. I attempted downgrading pipewire back to a previous version, however this did not fix the issue.

I then found [this thread](https://steamcommunity.com/app/221410/discussions/0/3105773861188568514/) from May 2021 citing a similar issue on Linux Mint with version 1621881261. I attempted the original fix suggested in the thread, which was to force a stable client download by moving `~/.steam/package/beta` to `~/.steam/package/old_beta`, but this did not work as it simply appeared to re-download version 1647446817. According to user frostwork in the first reply on the thread, this bug had apparently already been fixed. And yet I'm having it here with a later version than what that thread's OP had updated to after frostwork's reply (1621893676).

[I copied the output from running `steam` in the terminal, hopefully this should be helpful.](https://gist.github.com/AshtonSnapp/a96cf631ec532f7260592e24b73705f1)

#### Steps for reproducing this issue:

1. Update Manjaro Linux.
2. Try to launch Steam.

**Comment by kisak-valve** [comment]
Hello @AshtonSnapp, `/home/ashtons/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 102: cannot create temp file for here-document: No space left on device` is the much more important line in your log. Please check if you have free space in your home folder.

**Comment by AshtonSnapp** [comment]
I have around 49% free space on my drive.

**Comment by AshtonSnapp** [comment]
Just needed to restart my computer. FML. Sorry for wasting your time.
