### ISSUE TITLE
Failed to load steamui.so - libcairo.so.2: undefined symbol: FT_Get_Color_Glyph_Layer

### ISSUE THREAD

**Issue by Gab0** [ValveSoftware/steam-for-linux#8512]
#### Your system information

* Steam client version (build number or date): 1647446817
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After I did a full system upgrade in ArchLinux, when I launch steam it crashes with a small gray window that reads: 

`Fatal Error: Failed to load steamui.so`

The same thing happens when launching either `steam-runtime` or `steam-native`. I tried to do a `steam --reset` already.

The last lines on the console read:

```
Installing breakpad exception handler for appid(steam)/version(1647446817)
[2022-03-29 22:37:27] Download skipped: /client/steam_client_ubuntu12 version 1647446817, installed version 1647446817, existing pending version 0
[2022-03-29 22:37:27] Nothing to do
[2022-03-29 22:37:27] Verifying installation...
[2022-03-29 22:37:27] Performing checksum verification of executable files
[2022-03-29 22:37:27] Verification complete
Failed to load steamui.so - dlerror(): /usr/lib32/libcairo.so.2: undefined symbol: FT_Get_Color_Glyph_Layer
[2022-03-29 22:37:28] Shutdown
Installing breakpad exception handler for appid(steam)/version(1647446817)
Installing breakpad exception handler for appid(steam)/version(1647446817)
```

`/usr/lib32/libcairo.so.2` is inside the `lib32-cairo` ArchLinux package. It was last updated on 03/21.
But I'm not sure of what is really causing this issue.

#### Steps for reproducing this issue:

1. Update Arch Linux.
2. Reboot.
3. Launch steam.

**Comment by kisak-valve** [comment]
Hello @Gab0, this sounds like Steam is trying to use a version of Freetype2 that is too old for the system installed libcairo. Can you check if the `lib32-freetype2` system package is installed? Also, please share a list of files found in `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*`.

**Comment by Gab0** [comment]
Oh, I had `lib32-freetype2` on the update ignore list for years due to issues with some other program, now it has 'paid off' x.x
Updating `lib32-freetype2` solved the issue.
Thanks!
