### ISSUE TITLE
steam shutdown entirely on closing "friends & chat" via gnome desktop manager

### ISSUE THREAD

**Issue by ItchieR** [ValveSoftware/steam-for-linux#8514]
#### Your system information
* Steam client version (build number or date): (Package Version) 1648789923
* Distribution (e.g. Ubuntu): Linux ArchLinux 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux
* Opted into Steam client beta?: [Yes/No] Y
* Have you checked for system updates?: [Yes/No] Y
* Steam System Information: https://gist.github.com/ItchieR/26b7daee0894f5fb41c858f583f497ee (may I need to install a few libs as I see a lot of them missing)
* inxi Full: https://gist.github.com/ItchieR/eb262f3f17a1f85e82842bade5340e53

#### Please describe your issue in as much detail as possible:
There is a missbehavor since I have steam on gnome with ~~wayland~~ (I see I am using x11 somehow with gnome on this hardware), especially if a want to close steams "friends & chat" via the gnome desktop manager referred to the desktop viewer (activities or menu) you can see in the screenshot. If I press the red cross (X) on the upper right corner of the windows, it will shutdown the entire steam client, which is not even obtainable via "alt + f4" on steam "friends & chat".

I don't know why this happens, but it also will close all games during steams exit mode and this is annonying.

#### Steps for reproducing this issue:
1. Pressing the menu button or open the activity bar of gnome where you can see all your application, desktop and open windows
2. hover over the steam friends & chat window and close it with the (X) on the top right. (on my configuration its underlayed with a red circle)
![Bildschirmfoto von 2022-04-01 21-38-51](https://user-images.githubusercontent.com/33150592/161372315-2a5b99b7-6422-4dcf-b2d5-a17cca6e6962.png)
4. steam entirely shuts down

**Comment by kisak-valve** [comment]
Hello @ItchieR, this issue is already being tracked at #2685. Closing as a duplicate.
