### ISSUE TITLE
Phantom 360 controller and double input in games

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#8516]
#### Your system information

* Steam client version (build number or date): March31 
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

So steam input randomly stopped working for me in games (it works in the steam interface) and when I go into the controller settings in big picture I see it detects an Xbox 360 controller even when I don't have any controller plugged in any ideas? Tried changing the controller order for my specific game and it just brings of a blank screen as you can see. Tried reinstalling steam with steam --reset and the issue still persist. I also tried unplugging all my usb devices(including my controllers and disabling bluetooth) and it still detects the Phantom 360 controller
here is a gdb log I got noticed it detected two input devices
```
Local Device Found
  type: 0001 0001
  path: sdl://0
  serial_number:  - 0
  Manufacturer:
  Product:      py-evdev-uinput
  Release:      1
  Interface:    -1

!! Steam controller device opened for index 0.
Local Device Found
  type: 045e 028e
  path: sdl://1
  serial_number:  - 0
  Manufacturer:
  Product:      X360 Controller
  Release:      110
  Interface:    -1
  ```
 [Github Gist](https://gist.github.com/zany130/2222fe1cd48a4896af7c6f6f80fd6971)
![](https://cdn.discordapp.com/attachments/417953566485905418/958399782089547786/Screenshot_Steam_1.png)
![](https://cdn.discordapp.com/attachments/417953566485905418/958399781661720656/Screenshot_Steam_2.png)

#### Steps for reproducing this issue:

1.  Disconnect all controllers
2. open steam big pictue
3. Got to controller settings
4. see phantom 360 controller listed

EDIT: new image to show the phantom controller still being detected without any other controllers plugged in and also the above gdb output was done with all usb devices unplugged from my computer (ssh'd into my pc so I could also disconnect the mouse and keyboard just in case)

![image](https://user-images.githubusercontent.com/25832539/161634063-0f462af8-4c11-4669-8f3e-db8b075d7c03.png)

**Comment by blaztinn** [comment]
I have the same issue on Fedora 35 with both stable and beta versions of the Steam client.

**Comment by zany130** [comment]
Fixed on latest steam beta for me should this be closed?

**Comment by corgana** [comment]
FWFW I have had this problem on Windows and Linux for over a year. The phantom controller travels from machine to machine if I connect my Xbox Series X/S controller.
