### ISSUE TITLE
Suggestion: Allow manually running different platform

### ISSUE THREAD

**Issue by shentino** [ValveSoftware/steam-for-linux#8517]
#### Your system information
* Steam client version (build number or date): March 31, 2022
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
You should have an option to run a platform other than the native one where possible.
Example: If you have a game that is released for both windows and linux, you should be allowed to manually run the windows version, probably through proton.

It's possible that the linux version is broken or not as up to date as the windows version, for example

The only immediate application is force-running the windows version of applications/games even if a native version is available, but I suspect the concept would apply in general if there were other cross-platform directions.

#### Steps for reproducing this issue:
1. Find a game that's broken on linux but not windows
2. Try to run it
3. It runs the broken linux version instead of starting up proton

Of note I actually have a couple of games in this situation.

**Comment by kisak-valve** [comment]
Hello @shentino, the Steam client already allows you to do this by going to the game in the Steam library view, right click on the game -> Properties -> Compatibility -> check the `Force the use of a specific Steam Play compatibility tool` and select the compatibility tool you want to use.
