### ISSUE TITLE
File Not Found in Library when Shift-clicking HOME

### ISSUE THREAD

**Issue by Scrumplex** [ValveSoftware/steam-for-linux#8521]
#### Your system information

* Steam client version (build number or date): Mar 31 2022, at 23:11:43
* Distribution (e.g. Ubuntu): Arch Linux testing
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When this issue occurs the library is not usable anymore. Only restarting the client brings it back.

#### Steps for reproducing this issue:

1. Open Library
2. Shift+Click on HOME on the top left of the library page

![Screenshot](https://scrumplex.rocks/img/1649269976.png)

**Comment by kisak-valve** [comment]
Alt-Left arrow key brings back the UI.

**Comment by Scrumplex** [comment]
@kisak-valve yep. Didn't try that yet! It's almost like it's using Chromium Embedded Framework :D

**Comment by literal-0x4e** [comment]
I get this issue whenever I try to read patch notes from the downloads page.

1. Open Downloads page
2. click on the blue **PATCH NOTES** text button in the game's entry
3. drops me to a File Not Found page just like this one

I'm plain-clicking it, no shift-click, no control-click, just simply clicking

**Comment by m-GDEV** [comment]
I still have this issue as well.

I noticed it a few months ago an it happens occasionally. I don't have any specific steps I use to reproduce it.

I was thinking suspending the computer might be a cause but I don't know.

**Comment by Alpha-404** [comment]
I also have this issue

**Comment by FordDeckard** [comment]
I have this issue too. May be interesting to note that I have not had this issue on Linux Mint whatsoever. Both 20.3 and 21.1 have worked flawlessly. I'm currently on Pop!_OS and have encountered several issues, this included.

**Comment by Scrumplex** [comment]
This seems to be fixed with the new Steam UI.
