### ISSUE TITLE
InitializeSandbox() called with multiple threads in process gpu-process

### ISSUE THREAD

**Issue by RfDzDeveloper** [ValveSoftware/steam-for-linux#8522]
#### Your system information

* Steam client version (build number or date): 
* After type steam -v
* steam.sh[184143]: Running Steam on fedora 35 64-bit
  steam.sh[184143]: STEAM_RUNTIME is enabled automatically
  setup.sh[184223]: Steam runtime environment up-to-date!
  steam.sh[184143]: Steam client's requirements are satisfied

* Distribution (e.g. Ubuntu): 
Transient hostname: fedora
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: d0f312bada724ad79fd52c829d2ca402
           Boot ID: 9ebd1285a1604b09bd7b88474b301201
  Operating System: Fedora Linux 35 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:35
            Kernel: Linux 5.16.18-200.fc35.x86_64
      Architecture: x86-64

* Opted into Steam client beta?: 
* [No]
* Have you checked for system updates?: [Yes]
* 
architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    CPU family:          6
    Model:               94
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            3
    CPU max MHz:         4300.0000
    CPU min MHz:         800.0000
    BogoMIPS:            7999.96
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc
                         a cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss 
                         ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art
                          arch_perfmon pebs bts rep_good nopl xtopology nonstop_
                         tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cp
                         l vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1
                          sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsav
                         e avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault
                          invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnm
                         i flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1
                          avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflus
                         hopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida
                          arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_
                         clear flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    8 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushe
                         s, SMT vulnerable
  Mds:                   Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer
                          sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIB
                         P conditional, RSB filling
  Srbds:                 Mitigation; Microcode
  Tsx async abort:       Mitigation; TSX disabled

#### Please describe your issue in as much detail as possible:
My issue is can't open center part of Steam. After successful login i'm geting normal looking borders Steam, but center is white. Never ending loading, and my CPU are running to 90-100%. I can normal using other windows like:
-Steam,
-View,
-Friends,
-Games,
-Help
But others buttons doesn't work. Always white window and sound of crazy fans ;)
I tried reinstall, uninstall. Nothing changes in my system.

## Down bellow i upload all logs from today(04-06-2022)
[steam_logs.txt](https://github.com/ValveSoftware/steam-for-linux/files/8429573/steam_logs.txt)

1. Login
2. Look on the beauty of white steam center
3. Chill with fan ambient.

**Comment by RfDzDeveloper** [comment]
https://gist.github.com/RfDzDeveloper/b099af16fd4218d3a0af1e502aca866e

**Comment by RfDzDeveloper** [comment]
That helped! Everything started work fine :)
Sandbox mode(working fine):
https://gist.github.com/RfDzDeveloper/5853af97b43982f4d600d65517ec5e06

But if i run steam in normal mode problem is still exists.
Normal work(crashed):
https://gist.github.com/RfDzDeveloper/e69f0760bf383e93ac606f8feaf15c87

**Comment by smcv** [comment]
Just a guess, but the crash might be something to do with this:

```
[0407/082817.202892:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

or this:

```
[0407/082817.202892:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

It might help to compare a `cef_log.txt` with no special workarounds (bad scenario) and a `cef_log.txt` with the `steam -no-cef-sandbox` workaround (good scenario).

**Comment by RfDzDeveloper** [comment]
> hello @RfDzDeveloper - in your initial report you said you are not using Steam beta, please consider trying Steam beta client and report any differences in behavior you see.

I'll check it one more time. My bad i was using BETA participation.
After change it to NONE Steam is running well.

Sorry again for my mistake.

**Comment by smcv** [comment]
> i was using BETA participation.
> After change it to NONE Steam is running well.

Do you mean your situation is this?

* Not using the beta (Steam client build 1647446817), no workarounds: good. Steam runs correctly.
* Steam Beta Update (Steam client build 1648789923), no workarounds: bad. Web views are white, "InitializeSandbox() called with multiple threads in process gpu-process" is logged.
* Steam Beta Update (Steam client build 1648789923), with `steam -no-cef-sandbox` workaround: good. Steam runs correctly.

Or, if that's not true, please describe what is happening with a similar level of detail.

**Comment by RfDzDeveloper** [comment]
You describe correct my situation.

**Comment by smcv** [comment]
OK, thanks. @TTimo: this looks like a regression in the beta, perhaps you could point whoever is maintaining steamwebhelper/CEF towards it?

One of my test machines happens to have Fedora 35, so I'll see whether I can reproduce this tomorrow.

**Comment by smcv** [comment]
With the beta, does running Steam as `steam -cef-disable-seccomp-sandbox` work around this?

That's a partial version of `-no-cef-sandbox`, which might help to narrow down where the problem is.

**Comment by RfDzDeveloper** [comment]
After run this command: steam -cef-disable-seccomp-sandbox, application downloaded few things. After this BETA, and NONE run well. 

Now i can run application in BETA participation and NONE without specific modes. Only using Steam shortcut or steam command.

Looks like it is fixed.

**Comment by smcv** [comment]
Do you mean you only needed to run `steam -cef-disable-seccomp-sandbox` *once*, and after you had done that and let Steam update itself, `steam` with no special workarounds (no `-cef-disable-seccomp-sandbox` or `-no-cef-sandbox`) also worked?

**Comment by RfDzDeveloper** [comment]
After run this command: steam -cef-disable-seccomp-sandbox, application downloaded few things. After this BETA, and NONE run well. 

Now i can run application in BETA participation and NONE without specific modes. Only using Steam shortcut or steam command.

Looks like it is fixed.

**Comment by RfDzDeveloper** [comment]
Exactly. 
Now Steam is working without any workarounds.

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by sduensin** [comment]
I just ran into this today.  Switching to the beta channel fixed it.
