### ISSUE TITLE
Compatibility tool configuration failed [Steam Native]

### ISSUE THREAD

**Issue by guglovich** [ValveSoftware/steam-for-linux#8526]
#### Your system information

* Steam client version (build number or date): 31.03.22
* Distribution: Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Proton should have started or the missing files should have been downloaded. Clearing the download cache and checking local files didn't help, Steam is not downloading the missing files. The basic SLR weighs 11kb and the Scout and Soldier weigh 600 mb. I don't know if this is normal, but the files don't download when checked.
This happened after completely reinstalling Steam and Proton.

![Снимок экрана_2022-04-08_20-18-32](https://user-images.githubusercontent.com/54148165/162495788-dc9893cc-c2f8-4ae0-a701-2546e1454e70.png)

When running Steam Runtime, the same behaviour that I had before reinstallation, on Steam Native, occurs. Also, a bunch of child processes are created, games won't start and Steam can't be closed.
https://github.com/ValveSoftware/steam-for-linux/issues/8468

#### Steps for reproducing this issue:
1. Complete reinstallation with residuals removed
2. Proton and SLR installation
3. Running games

**Comment by cyberpunkrocker-zero** [comment]
FYI, steam-native on Arch is unsupported by Steam. Use it at your own risk.

**Comment by guglovich** [comment]
Irrelevant. This problem only goes together with another problem. Everything is working now.
https://github.com/ValveSoftware/steam-for-linux/issues/8468

**Comment by MayeulC** [comment]
Could be related to https://github.com/ValveSoftware/steam-runtime/issues/364
