### ISSUE TITLE
`steamwebhelper` consumes a large amount of RAM (and grows over time)

### ISSUE THREAD

**Issue by CtrlAltDeplete** [ValveSoftware/steam-for-linux#8529]
#### Your system information

[System Information](https://gist.github.com/CtrlAltDeplete/701305d90191cdcf890e9fe8aa4d886b)

* Steam client version (build number or date): 0.20220119.0
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The `steamwebhelper` when left to it's own devices, will consume up to 12GB of memory. It seems like there may be a leak somewhere, as I would not expect it needs that much RAM. It often starts somewhere around 50MiB of RAM, but always climbs.

#### Steps for reproducing this issue:

1. Launch Steam.
2. Wait and monitor `steamwebhelper` RAM usage.

**Comment by kisak-valve** [comment]
Hello @CtrlAltDeplete, this issue is already being tracked at #7042 / #7266. Closing as a duplicate.
