### ISSUE TITLE
SELinux blocking install scripts from executed, openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Mack-W** [ValveSoftware/steam-for-linux#8534]
#### Your system information

* Steam client version (build number or date): build 1647446817
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed (Steam package fetched from distro repo)
* Opted into Steam client beta?: Yes and no, doesn't matter
* Have you checked for system updates?: Yes (and on a regular basis)

#### Please describe your issue in as much detail as possible:
When SELinux policy is set to "Enforcing" mode, install scripts (like VCRedist, DirectX, etc) won't run on game first run.

#### Steps for reproducing this issue:

1. Install openSUSE, drop AppArmor in favor of SELinux and set SELinux policy to "Enforcing" during installation
2. Install some games via Steam (install Steam via `zypper in steam`)
3. Run them.  

You can observe that no install scrpits are being executed. (In fact, some games even won't run, reported as a seperate issue under ValveSoftware/Proton)

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/steam-runtime/issues/502.
