### ISSUE TITLE
Unable to install addons of game

### ISSUE THREAD

**Issue by tmvkrpxl0** [ValveSoftware/steam-for-linux#8539]
#### Your system information
https://www.toptal.com/developers/hastebin/ihezewehox.sql

* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I cannot install some addons of all steam games, when I try to install a addon, download cancels itself immediately
This only happens to some of addons, I can install other ones just fine, but I'm unsure what's causing the issue
This only happens to game that are installed on NTFS drive, which I share with windows installation. Moving games into ext4 drive fails sometimes but succeed when I try again.
This is workshop log file: https://www.toptal.com/developers/hastebin/vecibuholi.yaml
It is filled with `I/O Operation Failed`
It was fine until yesterday
I'm able to create/remove files on the NTFS drive without problem and I have marked all files in my steam library folder in the NTFS drive with 777 using `chmod -R 777 STEAMGAMES`

#### Steps for reproducing this issue:

1.  Install game 
on ntfs drive
2. Install 7+ random addons from workshop
3. Some of them doesn't download

[2022-04-16 21-17-19.zip](https://github.com/ValveSoftware/steam-for-linux/files/8499889/2022-04-16.21-17-19.zip)
This is recording of me trying to restart addon downloading

**Comment by tmvkrpxl0** [comment]
I have tried: changing download location, clearing download cache, verifying integrity of games but none of it worked so far

**Comment by kisak-valve** [comment]
Hello @tmvkrpxl0, it should be noted that sharing a Steam library folder across OSes is explicitly unsupported as noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation.

That said, there might be a general Steam + NTFS issue to ponder here.

**Comment by tmvkrpxl0** [comment]
> Hello @tmvkrpxl0, it should be noted that sharing a Steam library folder across OSes is explicitly unsupported as noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation.
> 
> That said, there might be a general Steam + NTFS issue to ponder here.

I see, still, I dont think shring game with window is cause of problem, only thin that I think could be problem is permission issue but I have already taken care of them

**Comment by tmvkrpxl0** [comment]
@kisak-valve The issue got worse, I am unable to move games from ext4 drive into ntfs drive, it says "Disk write error"

**Comment by tmvkrpxl0** [comment]
I was able to solve the issue by changing fstab entry to `UUID=461CB4351CB4223B   /media/tmvkrpxl0/DATA   auto    nosuid,nodev,nofail,x-gvfs-show,defaults,exec,async,uid=1000,gid=1000    0       0`
I'm still unsure which option was the issue but it works again so it's cool
