### ISSUE TITLE
Launch Options dialog is tiny and not resizeable

### ISSUE THREAD

**Issue by TastyPi** [ValveSoftware/steam-for-linux#854]
When I opened the properties for Half-Life Beta and select SET LAUNCH OPTIONS... the dialog that opens is too small to display the input and I can't make it bigger.

I'm running ArchLinux with Gnome 3.6.2.

![image](https://f.cloud.github.com/assets/934844/98130/79482eba-6714-11e2-9d1b-b682e9c83418.png)

I can't reproduce the error.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
