### ISSUE TITLE
Controller only working for steam overlay and big picture mode, but no gaming.

### ISSUE THREAD

**Issue by K1ngst0m** [ValveSoftware/steam-for-linux#8540]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/34272057/163701357-a64bd231-717f-40c7-9ebb-924319cae40c.png)

* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

---

#### Please describe your issue in as much detail as possible:

When I plugged in my controller(ds4/5, pro controller...), whatever native game or steam play game, it only worked for steam overlay and big picture mode, but no gaming.

- my ds5 controller configuration and other controllers tried either default or online configurations same like this:
![image](https://user-images.githubusercontent.com/34272057/163701501-8759ff16-9954-4581-8634-496fcd16b5ea.png)

- system information, kernel configuration, `udev monitor` output when ds5 plugging in and out: https://gist.github.com/K1ngst0m/22d3c5c637c629956d691e62ab438e51

---

#### Steps for reproducing this issue:

1. plug in ds5 with USB
2. launch steam and big picture mode (controller now is working)
3. launch some game (native or proton, e.g., the binding of Isaac: rebirth, Final Fantasy VI) (controller not working)
4. open steam overlay by pressing the controller's home button and it works.
5. return to the game, and press the controller's home button, the desktop mode can work (whether the steam overlay has been opened or not).

**Comment by K1ngst0m** [comment]
Finally, I solved this by moving the steam client version to beta, everything above now just works fine.😊

**Comment by K1ngst0m** [comment]
Is there any advice for tracing problems same like these? I just solved this issue like a headless chicken.

**Comment by kisak-valve** [comment]
Closing per the last comment.
