### ISSUE TITLE
Very large tooltips on community pages get stuck

### ISSUE THREAD

**Issue by mscatto** [ValveSoftware/steam-for-linux#8547]
#### Your system information

* Steam client version (build number or date): Apr 20 22, 19:06:06
* Distribution (e.g. Ubuntu):  Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When mouse hovering on related community discussions with a lot text, the tooltip gets stuck and takes a very long time to disappear, freezing the entire client until it goes away.

#### Steps for reproducing this issue:

1. Open any discussion on the Community section about any game
2. Hover at related discussions links on the right side of the page
3. If the text is too large, the tooltip gets stuck.
This does not happen on the "main" page, only on related threads where the tooltip has a dark background, unlike the blue tooltips on the main discussions page.

Here is a recording:
https://user-images.githubusercontent.com/39102912/164803169-eb9032bc-b1ff-4086-aef3-8138bd90bed3.mp4

**Comment by kisak-valve** [comment]
Hello @mscatto, this issue is already being tracked at #3994. Closing as a duplicate.
