### ISSUE TITLE
steam web helper uses a lot of system resources

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#8548]
#### Your system information
https://gist.github.com/zany130/8f4b434bde92c432bc5dd1bc4f4a5257
* Steam client version (build number or date):  April 20 2022
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
While playing  The Legend Of Heroes Trails of Cold Steel III I noticed I was getting performance drops and the steam big picture overlay was unresponsive. Acording to kde system monitor steam was spawning several `steamwebhelper` processes which where putting a 20% load on my GPU (GTX 1080) and my CPU (Ryzen 2600x)  as well as a 10% load on the GPU memory and almost a GB of ram.

This also seems to happen even when I am not playing a game or even using the steam interface (steam is in the background doing nothing)

#### Steps for reproducing this issue:

1. open steam
2. open a task manager
3. notice high system usage

**Comment by kisak-valve** [comment]
Hello @zany130, this issue is already being tracked at #6500. Feel free to add your experience to the older issue report. Closing as a duplicate.
