### ISSUE TITLE
Steam don't launch the game

### ISSUE THREAD

**Issue by Trasher195** [ValveSoftware/steam-for-linux#8557]
Distribution: ArchLinux
Opted into Steam client beta?: No
Have you checked for system updates?: Yes

When you press the play button, Steam is endlessly preparing to launch. Checking the integrity of files for this particular game does not work. Reinstalling doesn't help.

Here is what is written in the logs:

**stats_log.txt**

`[2022-04-29 18:16:25] [AppID 228980] Schema not found on disk`
`[2022-04-29 18:16:25] [AppID 228980] CAPIJobRequestUserStats - received error 'Failure' (2) from server`
`[2022-04-29 18:16:25] [AppID 221100] Schema not found on disk`
`[2022-04-29 18:16:25] [AppID 221100] CAPIJobRequestUserStats - received error 'Failure' (2) from server`
`[2022-04-29 18:16:31] [AppID 221100] Schema not found on disk`

**installscript_log.txt**
`[2022-04-29 17:08:46] [AppID 221100] Failed to load installscript "/home/artem/.local/share/Steam/steamapps/common/DayZ/installscript.vdf"`

**Comment by kisak-valve** [comment]
Hello @Trasher195, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3899#issuecomment-1113406066.
