### ISSUE TITLE
Steam's status icon (tray) menu is missing in Ubuntu 22.04

### ISSUE THREAD

**Issue by skoruppa** [ValveSoftware/steam-for-linux#8563]
#### Your system information

* Steam client version (build number or date): Apr 27 2022
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With Ubuntu 22.04 even though there is a Steam icon in the top right corner (appIndicator), nothing happens after clicking it. Both on Xorg and Wayland

The issue is problematic because after closing the main window, Steam is still running and I have no way to close it completely (other than killall command) or to reopen its window

#### Steps for reproducing this issue:

1. Run Steam
2. Click on the Steam's status icon

**Comment by skoruppa** [comment]
Double checked Xorg, and issue is present on it as well

**Comment by kisak-valve** [comment]
Hello @skoruppa, can check what files are listed in `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` (or maybe `~/.steam/debian-installation/ubuntu12_32/steam-runtime/pinned_libs*` if you're using the distro-modified Steam package), then delete the pinned_libs* folders so that Steam regenerates them the next time it is started?

**Comment by skoruppa** [comment]
> Hello @skoruppa, can you check what files are listed in `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` (or maybe `~/.steam/debian-installation/ubuntu12_32/steam-runtime/pinned_libs*` if you're using the distro-modified Steam package), then delete the pinned_libs* folders so that Steam regenerates them the next time it is started.

Thank you! Yes, that helped with the status icon menu :)
