### ISSUE TITLE
Ubuntu 22.04 steam won't launch

### ISSUE THREAD

**Issue by elias2500** [ValveSoftware/steam-for-linux#8565]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] n 
* Have you checked for system updates?: [Yes/No] y

I clicked on the steam app icon and it did nothing. I then followed [this](https://steamcommunity.com/app/221410/discussions/0/3035976310908439316/). Reached the point of 
```bash
STEAM_RUNTIME=0 steam
```
and then :

You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0

And then: Failed to load steamui.so

Then found [this](https://github.com/ValveSoftware/steam-for-linux/issues/7807) there is no beta file or directory to delete.

What's next for me?

NOTE: Steam used to launch and i also was successful on installing and playing a game. This happened out of the blue.

**Comment by kisak-valve** [comment]
Hello @elias2500, disabling the Steam runtime is not supportable. If you run `steam` from a terminal, does the terminal spew give any hints?

Also, can you check if any 32 bit OpenGL application like `glxinfo` from a 32 bit build of `mesa-utils` works? Unfortunately, Ubuntu doesn't provide a 32 bit build of this package on 22.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

**Comment by elias2500** [comment]
**UPDATE**
Running steam by clicking the application icon from the "applications menu" started steam but didn't start the steam GUI. As a result when I ran:
```bash
steam
```
I got:

```bash
steam.sh[7394]: Running Steam on ubuntu 22.04 64-bit
steam.sh[7394]: STEAM_RUNTIME is enabled automatically
setup.sh[7464]: Steam runtime environment up-to-date!
steam.sh[7394]: Steam client's requirements are satisfied
```
but when running:

```bash
steam
```

with the process killed, steam launches normally.  

@kisak-valve Thanks for the comment! But cause I am not very advanced using ubuntu I don't know what any of this means:

"Also, can you check if any 32 bit OpenGL application like glxinfo from a 32 bit build of mesa-utils works? Unfortunately, Ubuntu doesn't provide a 32 bit build of this package on 22.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system."

**Comment by DanGdl** [comment]
Hi
is there any way to install those libs on Ubuntu 22.04:
libc6:i386 
libegl1:i386 
libgbm1:i386 
libgl1-mesa-dri:i386 
libgl1:i386 
libnvidia-gl-470:i386
steam-libs-i386:i386 ?

on launch steam requests those libraries but it can install them
Thanks
