### ISSUE TITLE
Notifications are too dark to read unless you have esports reflexes

### ISSUE THREAD

**Issue by qs-arno** [ValveSoftware/steam-for-linux#8567]
#### Your system information

* Steam client version (build number or date): 1647446817 (Mar 14, 2022 at 19:49:17)
* Distribution (e.g. Ubuntu): Kubuntu 18.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, everything's up to date.

#### Please describe your issue in as much detail as possible:

The notification popups (when a friend starts playing a game, when another LAN machine is ready for in-home streaming, etc.) go very dark about a second after popping up, making them difficult to impossible to read at a distance (e.g. from the couch).

1. The popup appears and looks fine.
2. About 1 second later, the entire popup goes very dark.  It's not completely black, and you can still see that there's text there and that it's a Steam notification, etc. but it's too dark to actually read if you're not sitting right in front of the monitor (in my case, I'm using it through a hardware Steam Link that I'm viewing from the couch).  When I'm at the console, though, I can read it (it's still really dark, but when I'm a foot away from the screen I can read it).
3. About 5 seconds after _that_, the popup dismisses (as you'd expect it to).

The behaviour is the same regardless of whether the computer is just on the desktop, or running a game in full-screen mode (not windowed "full-screen", actual full-screen).  I also thought maybe it might be related to in-home streaming somehow, so I made sure to test that it still happens at the console even when the PC isn't streaming to the Steam Link.

#### Steps for reproducing this issue:

1. Launch Steam.
2. Wait for a notification-worthy event to occur (for example, another LAN PC going online/offline).
3. Observe the above behaviour.

**Comment by kisak-valve** [comment]
Hello @qs-arno, this issue is already being tracked at #4735. Closing as a duplicate.
