### ISSUE TITLE
Opening the Shader Pre-Caching page while Steam is processing Vulkan shaders automatically skips the processing

### ISSUE THREAD

**Issue by treuks** [ValveSoftware/steam-for-linux#8568]
#### Your system information

* Steam client version (build number or date): The 1.0.0.74 version of the Steam Flatpak
* Distribution (e.g. Ubuntu): Flatpak on Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

If you open the Shader Pre-Caching page while the game you're starting up is performing shader processing, it will automatically skip caching, and start to launch. In my experience, it mostly happens while I'm starting up Warframe.

From my testing, it happens on any version and distribution of Steam.

#### Steps for reproducing this issue:

1. Start up a game that utilizes Vulkan cache (for example, start up Warframe with Proton)
2. Open the Steam settings, and then switch to the Shader Pre-Caching page
3. It will automatically skip caching, even though it shouldn't do that

**Comment by Mameng57** [comment]
Same behavior on Steam Ubuntu.

**Comment by kisak-valve** [comment]
Hello @treuks, @maulaniad, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by treuks** [comment]
sorry for the delay, the issue is no longer reproducible
