### ISSUE TITLE
CPU and HDD usage ramps up to 100% and freezes entire OS whiled downloading games

### ISSUE THREAD

**Issue by unclamped** [ValveSoftware/steam-for-linux#8571]
#### Your system information

* Steam client version (build number or date): 1.0.0.74
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes (and upgraded, all via `yay -Syyu`)

#### Please describe your issue in as much detail as possible:
While downloading apps from Steam on my Arch Linux install, both my CPU usage (Indicated by htop and my polybar CPU usage module) and HDD usage (Indicated by the HDD led in my case) go to 100%, and after a while, the entire system starts to become unresponsive (first some apps or tray menus don't open, and then everything is just gone besides the mouse cursor), to the point where even opening tty2 with ctrl +alt + f2 isn't possible, as it will only keep the character _ blinking. After a while (sometimes seconds, sometimes 10+ minutes), it will unfreeze, and Steam will show a big void in the download graph and resume the download like normal, only to freeze once again after a while. The internet seems to cut off entirely while the total freeze occurs, and Steam will sometimes end up canceling the download because there's no internet connection available after unfreezing if the freeze lasted long enough. 
Notes: Changing download regions don't seem to make a change at all. This issue doesn't happen in the Windows version of Steam, so it is most likely not a hardware-related issue (f.e. an old CPU or similar)

#### Steps for reproducing this issue:

1. Open Steam (beta or stable have the same issue)
2. Download a somewhat big app to avoid it from finishing fast
3. Wait and see

**Comment by kisak-valve** [comment]
Hello @unclamped, this issue is already being tracked at #3450 / #4978 / #6684. Closing as a duplicate.
