### ISSUE TITLE
Steam won't start anymore despite having libraries

### ISSUE THREAD

**Issue by UnfortunateSon4** [ValveSoftware/steam-for-linux#8573]
System information:

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Void Linux
* Opted into Steam client beta?: no, as far as I know
* Have you checked for system updates?: yes
* CPU: Intel i7-6700 (8) @ 4.000G
* GPU: NVIDIA GeForce GTX 750 2GB
* Kernel: 5.15.36_1

In order to first make it work I did [this command](https://gist.github.com/UnfortunateSon4/777f93f85369dc07c4e7549bd3372692) to install the libraries I needed. It worked flawlessly the first day, not the case anymore.

In an attempt to fix it I uninstalled Steam, deleted it's two folders (/home/user/.local/share/Steam and /home/user/.steam) and then reinstalled it. After that I started it via the terminal and got [this](https://gist.github.com/UnfortunateSon4/54d380ab500eddcae3e6f04952cccd44)

**Comment by kisak-valve** [comment]
Hello @UnfortunateSon4, can you check if any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-demos works?

In general, the NVIDIA proprietary driver requires that the running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries are all installed and have exactly the same version to work properly. `X Error of failed request:  BadValue (integer parameter out of range for operation)` in your terminal spew hints that your video driver install is broken.

**Comment by UnfortunateSon4** [comment]
@kisak-valve hello, both glxinfo and glxgears seem to be working properly. Would you like to me to make a gist of the glxinfo output in case you might notice anything anomalous ?

**Comment by kisak-valve** [comment]
I'm not really familiar with Void packages, but:
`nvidia-gtklibs-32bit` 390.87
`nvidia-libs-32bit` 510.60.02
`nvidia470-libs-32bit` 470.103.01

These packages are from completely different driver series and are most likely never intended to be used together. You should only be matching the NVIDIA driver version you're using with the NVIDIA kernel module and 64 bit userspace.

If you're not doing anything special to get glxinfo, then there's a good chance that glxinfo installed on your system is a 64 bit build testing 64 bit OpenGL, not 32 bit OpenGL, which is what's interesting for troubleshooting.

**Comment by UnfortunateSon4** [comment]
The void guides for steam on this [void wiki](https://wiki.voidlinux.org/voidlinux_en_all_2021-04/A/Steam)for example mentions installing the 32bit ones too because Steam runs on 32bit.

**Comment by UnfortunateSon4** [comment]
I think I solved it for NOW, I uninstalled the packages with version 390 and 470 and now it seems to work again. That ought to teach me about following guides online. Still, I am amazed it worked the first time even with those old libraries installed.
