### ISSUE TITLE
Steam Overlay is broken / visual glitch on Celeste native game

### ISSUE THREAD

**Issue by BipB0p** [ValveSoftware/steam-for-linux#8585]
#### Your system information

* Steam client version : 1652488014
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed x86_64 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

My steam information https://gist.github.com/BipB0p/fa28928b8dd75a920e56088b97f5c058

#### Steps for reproducing this issue:

1. Launch the game
2. Open the overlay (shift+tab)
![Celeste overlay](https://user-images.githubusercontent.com/88817051/168429004-43f206c9-a429-4a1b-888f-f952a2582754.png)

**Comment by kisak-valve** [comment]
Hello @BipB0p, this issue is already being tracked at #7889. Give https://github.com/ValveSoftware/steam-for-linux/issues/7889#issuecomment-917554177 a try.

Closing as a duplicate.
