### ISSUE TITLE
Steam refusing to launch with Nvidia Performance Mode on Ubuntu 22.04

### ISSUE THREAD

**Issue by Dainted** [ValveSoftware/steam-for-linux#8586]
#### Your system information

* Steam client version (Date): 15th May 2022
* Distribution: Ubuntu 22.04 LTS 
* Opted into Steam client beta?: No

When I launch Steam after changing my Nvidia settings from [On-Demand] to [Performance Mode], Steam refuses to open, when trying to launch using Integrated and then Dedicated from the right-click menu it will still refuse to launch.

The only output from Steam when entering `steam` into a terminal window is:

`steam.sh[29217]: Running Steam on ubuntu 22.04 64-bit`
`steam.sh[29217]: STEAM_RUNTIME is enabled automatically`
`setup.sh[29355]: Steam runtime environment up-to-date!`
`steam.sh[29217]: Steam client's requirements are satisfied`
`dainted@Charcoal:~$`

When launching as Steam Native using `env STEAM_RUNTIME=0 steam`, I get the following result:

`steam.sh[29753]: Running Steam on ubuntu 22.04 64-bit`
`steam.sh[29753]: STEAM_RUNTIME is disabled by the user`
`steam.sh[29753]: Can't find 'steam-runtime-check-requirements', continuing anyway`
`dainted@Charcoal:~$`

Uninstalling Steam, deleting all files from `/home/dainted/.steam/` and reinstalling only works temporarily and once steam is fully closed, it goes back to the same issue (Remember password was also disabled after reinstalling).

I hope to get some support and have this issue fixed.

**Comment by kisak-valve** [comment]
Hello @Dainted, this reads like a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/8179. Can you check if Steam was completely closed before you tried to run it from a terminal? If `steam` detects that it's already running, then it'll hand off to the existing instance and exit early. It's also worth testing the workaround in that issue report.

Disabling the Steam runtime is unsupportable.

**Comment by Dainted** [comment]
Just running `killall -9 steam` and reopening it before editing anything actually worked, I'm quite surprised actually.

Thank you for directing me to Issue #8179 as it has helped fix Steam.
