### ISSUE TITLE
Cannot type cyrilic characters in a chat with friend

### ISSUE THREAD

**Issue by kinazarov** [ValveSoftware/steam-for-linux#8592]
#### Your system information
* Steam Runtime Version: 1652488014
* Distribution (e.g. Ubuntu 18.04): Arch Linux + KDE
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
https://gist.github.com/kinazarov/14ff8aa083bc9b17c208e17b9655c99e
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expect to be able to chat with friends in any language
but I only able to type english characters
If I type my message in other application (Kate for example) and then copy and paste it in a chat window it works

#### Steps for reproducing this issue:

1. Open "Friends"
2. Open chat window
3. Try to type any cyrilic character

**Comment by kisak-valve** [comment]
Hello @kinazarov, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/5589.

Please and or uncomment `en_US.UTF-8 UTF-8` in `/etc/locale.gen`, then run `locale-gen` as root.

Closing as a duplicate.
