### ISSUE TITLE
Source modifications are only visible in home folder.

### ISSUE THREAD

**Issue by Alex-1000** [ValveSoftware/steam-for-linux#8597]
Version: steam:i386 1:1.0.0.61-2ubuntu3
Not beta
Distributive: Linux Mint w/ Cinnamon desktop environment
System updated

When installing Source mods, Steam watches only at _~/.local/share/Steam/steamapps/sourcemods_, even if other location is added and chosen as default for Steam library. Creating symbolical link allows to choose other location but it is a way to go around problem instead of fixing it, and that way you are limited to only one location with all of Source mods.

**Comment by kisak-valve** [comment]
Hello @Alex-1000, this issue is already being tracked at #4179. Closing as a duplicate.
