### ISSUE TITLE
steam home folder permissions allow all users to read them

### ISSUE THREAD

**Issue by juliantaylor** [ValveSoftware/steam-for-linux#860]
the steam folders created in the users home folder have 776 permissions meaning every user on the machine can read them.
This is not a problem for the one created in .local/share/Steam as .local/share is by default only user readable
the ~/.steam folder on the other hand is directly accessible to every user by default on ubuntu systems as there the home is world readable.
There does not seem to be anything important in there (and you can't get to local/share via the links) but just to ensure in future no sensitive information can be leaked the folder should be created with user only readable permissions unless there is a specific reason for them to be world readable.

**Comment by kisak-valve** [comment]
This appears to have been addressed by the Valve provided steam package, which sets `.local/share/Steam` to 700. If you have further concerns with folder permissions for steam installed by a distro-provided package, please contact your distro's package maintainer for steam.
