### ISSUE TITLE
Can't unminimize the Steam window on GNOME Wayland

### ISSUE THREAD

**Issue by 1player** [ValveSoftware/steam-for-linux#8600]
#### Your system information

* Steam client version (build number or date): May 21 2022, at 02:23:45
* Distribution (e.g. Ubuntu): Fedora 36
* Opted into Steam client beta?: Yes, also affects stable branch.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When the application is started, it shows as minimized in the dock. Clicking the Steam icon in the dock renders three Steam icons representing three minimized windows (with no preview whatsoever) that can't be opened nor switched to. Closing one of the icons from the overview screen kills Steam. 

This is what shows when I click the Steam icon in the dock: 

![Screenshot from 2022-05-21 08-36-20](https://user-images.githubusercontent.com/690120/169642309-97732e6a-ab61-457d-bbd4-2cd06e29a7f5.png)

Opening Steam from the tray area still works.

#### Steps for reproducing this issue:

1. Open Steam, in my case it starts minimized
2. Click the Steam icon in your dock to unminimize

**Comment by 1player** [comment]
This might have started happening when I got the Steam Deck preorder alert: whenever I open Steam, it minimizes every window to show me an account alert reminding me to confirm my preorder, and then I got those three minimized windows I can't do anything about. 

I've just permanently dismissed the account alert and it seems to be OK, for now.

**Comment by kisak-valve** [comment]
Hello @1player, this issue is already being tracked at #7029. Closing as a duplicate.
