### ISSUE TITLE
Case misalignment in Record of Agarest War Mariage (740550)'s launch config causes chdir to fail

### ISSUE THREAD

**Issue by zzhiyi** [ValveSoftware/steam-for-linux#8605]
The original report is that Record of Agarest War Mariage (740550) doesn't start. It is caused by the current directory being set to ~/.local/share/Steam/. The game won't run even on Windows if the current directory is set to any other directory because it's calling CreateFileW() with relative paths, for example ../Data/PROJECT.PAC. [The patch](https://pastebin.com/BVWN2250) for Proton makes the fake steam.exe launch the game in the game directory. However, on second thought, I don't think the current directory should be set in steam.exe. Rather, the Steam Linux client should set the current directory before running the proton script. The reason is that the Steam Linux client or native steam client can add non-steam games to its library, and creating shortcuts with "Start In" can be set to any directory. If the current directory is set by fake steam.exe, it will overwrite the settings from the Steam Linux client.

@kisak-valve

**Comment by Joshua-Ashton** [comment]
It should do this, perhaps it is failing due to casing reasons, as the app config is `Exe/` but the depot only has `EXE` as a folder.

**Comment by Joshua-Ashton** [comment]
Yes, this is a casing thing: I made a test case of several app launch configs.

![image](https://user-images.githubusercontent.com/21316711/170478101-4a75efe9-70a6-4533-8ed5-631cac56da1f.png)

The first one gives:

![image](https://user-images.githubusercontent.com/21316711/170478147-f72f7cb9-62f4-4ebe-b618-f2384ab35bb3.png)

The second:

![image](https://user-images.githubusercontent.com/21316711/170478184-93412497-43f8-4fa9-9e1b-e466ee95ec71.png)

The third:

![image](https://user-images.githubusercontent.com/21316711/170478230-2ddffe8f-8365-46a7-a72e-b82f487f48d7.png)

**Comment by zzhiyi** [comment]
@kisak-valve, so is this considered a game bug for the developer side?  It would be nice to have some checks for such issues on the Valve server when developers upload games.

**Comment by kisak-valve** [comment]
Hello @zzhiyi, friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a Steam developer myself. We'll need to hear from a Steam dev on how they'd like to handle this particular issue.

**Comment by Joshua-Ashton** [comment]
@zzhiyi No, Steam just needs to do casefolding when setting working dir

**Comment by zzhiyi** [comment]
By the way, other game configs seem also affected. For example, the steam cloud saves path as shown at https://github.com/ValveSoftware/steam-for-linux/issues/7512.

**Comment by TTimo** [comment]
(fix is making it's way through the pipeline)

**Comment by zzhiyi** [comment]
Thanks. Looks like it's fixed.
