### ISSUE TITLE
Mouse always selects multiple items in Steam client

### ISSUE THREAD

**Issue by greenChainsaws** [ValveSoftware/steam-for-linux#8610]
#### Your system information

* Steam client version (build number or date): Build number: 1.0.0.74-1 Date: 05/30/2022
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When I click anywhere outside of the client my mouse will simply _click._ It won't multi select unless I double-click on a word, or click and drag.  On the Steam client however, the first click I do will set an anchor point for the next click to multi-select from. If I try single-clicking a title and then single-click a different title in my library it will select both games and all the ones in-between. The issue persists after restarting Steam and changing tabs(say from Library to Store). I'll go hours without seeing this issue, and then it'll mysteriously *stop.* 

#### Steps for reproducing this issue:

1. Start Steam
2. Use it a bit
3. Go to 2

Part of the issue is that I don't know what triggers this. I will go literal days without experiencing the issue. I can't even consistently _stop_ the issue. I've tried tinkering around with setting popup windows which seems to have fixed it _once_ but then never did again.

Video for proof: (I only single click in the entire video. Every time I do(assuming I'm clicking in a valid spot) the area selected updates.)

https://user-images.githubusercontent.com/96515029/171019261-934e1998-68c0-4eae-88cb-655edb396a1b.mp4

**Comment by kisak-valve** [comment]
Hello @greenChainsaws, this issue is already being tracked at #3451. Closing as a duplicate.
