### ISSUE TITLE
Feature Request: Rerun Installation Script (install.vdf)

### ISSUE THREAD

**Issue by myo** [ValveSoftware/steam-for-linux#8615]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

- We need a way to run install.vdf files whenever we want from the client to add the required registry fields.
- Make the option user-friendly and call the option "rerun installation script" under context menu > manage.

## Justification [optional] 

- Sometimes running the script fails and the only option is to reinstall or add those registry keys manually.
- Sometimes the registry entries are lost or corrupted.

## Risks [optional]
none that I can see, in case of power loss just rerun the installation script 😆

**Comment by kisak-valve** [comment]
Hello @myo, this feature request is already being tracked at #6346. Closing as a duplicate.
