### ISSUE TITLE
During update Steam client using wrong font(cosmetic issue)

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#8616]
#### Your system information

* Steam client version (build number or date): Exist on all 1653101165
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Screenshot : 
![ksnip_20220527-141709](https://user-images.githubusercontent.com/22169129/171798231-aff8cd03-b8a7-49aa-833d-79cee2915594.png)

#### Steps for reproducing this issue:

1. install Steam 
2. Set Russian language 
3. Wait till new steam update released 
4. In moment of steam client self update you will see squares instead of letters . Look like wrong Unicode code page used.

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, this issue is already being tracked at #8006. Closing as a duplicate.
