### ISSUE TITLE
How to fix this error when launching steam?

### ISSUE THREAD

**Issue by kvadim80** [ValveSoftware/steam-for-linux#8617]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Steam version last downloaded from off site and installed.
2. lsb_release -a
       No LSB modules are available. 
       Distributor ID: Ubuntu
       Description: Ubuntu 20.04.4 LTS
       Release: 20.04
       Codename: focal
3.  Steam client beta: No
4.  Have you checked for system updates? Yes

The client installed itself without problems. But, on startup, I got the following error:

Steam requires at least an Intel Pentium 4 or AMD Opteron, with the following features:
- x86-64 (AMD64) instruction set (lm in /proc/cpuinfo flags)
- CMPXCHG16B instruction support (cx16 in /proc/cpuinfo flags)
- SSE3 instruction support (pni in /proc/cpuinfo flags)

  How to fix it? Because when Windows 7 was installed on this computer, the client worked. And on Linux, it does not start.
![Снимок экрана_2022-06-03_18-47-19](https://user-images.githubusercontent.com/32527625/171985408-a0a809f1-3360-4112-8c48-2272a5357905.png)

**Comment by kisak-valve** [comment]
Hello @kvadim80, there is no workaround for these baseline hardware requirements.

**Comment by kvadim80** [comment]
What does it mean?  Are you saying that steam won't work?

**Comment by kisak-valve** [comment]
That is correct. Out of mild curiosity, what model CPU are you using?

**Comment by kvadim80** [comment]
inxi -C
CPU:
  Topology: Quad Core model: Intel Core2 Quad Q9500 bits: 64 type: MCP 
  L2 cache: 3072 KiB 
  Speed: 2005 MHz min/max: N/A Core speeds (MHz): 1: 2005 2: 2255 3: 2003 
  4: 2449

**Comment by kisak-valve** [comment]
Looking at the spec sheet for this CPU, it looks like it does meet the hardware requirements, however, some LGA 775 socket motherboard BIOS didn't give support for CMPXCHG16B to applications.

Can you double check `cat /proc/cpuinfo` for `cx16` and `pni` in the flags section. There's a small chance that there was BIOS update for your motherboard which fixed exposing support of these hardware capabilities.

**Comment by kvadim80** [comment]
cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9500  @ 2.83GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2005.009
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni tm2 ssse3 lahf_lm pti dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5665.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9500  @ 2.83GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2255.465
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni tm2 ssse3 lahf_lm pti dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5665.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9500  @ 2.83GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2003.135
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni tm2 ssse3 lahf_lm pti dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5665.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9500  @ 2.83GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2449.233
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni tm2 ssse3 lahf_lm pti dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5665.72
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
`
`

**Comment by kvadim80** [comment]
inxi -M
Machine:
  Type: Desktop Mobo: Intel model: DG33BU v: AAD79951-407 
  serial: <superuser/root required> BIOS: Intel 
  v: DPP3510J.86A.0413.2008.0306.2218 date: 03/06/2008 `
`

**Comment by kisak-valve** [comment]
Thanks for checking, there's nothing more that can be pondered from this side. There's no `cx16` in `flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni tm2 ssse3 lahf_lm pti dtherm` so this is a hardware issue.

It looks like that was not the last BIOS update for your motherboard, but Intel removed the bios updater 3 years ago. I found an archived version of the page: https://web.archive.org/web/20190904060640mp_/https://downloadcenter.intel.com/download/17930/BIOS-Update-DPP3510J-86A-

Keep in mind that updating a BIOS always comes with a risk of permanently bricking the motherboard and might not fix this issue anyway. Also, you could look at adding the `intel-microcode` system package, but I wouldn't expect that to change the list of hardware capabilities in /proc/cpuinfo.

**Comment by kvadim80** [comment]
Apparently I have this package. I didn't set it up on purpose.

apt search intel-microcode
Sorting… Done
Full Text Search… Done
amd64-microcode/focal,now 3.20191218.1ubuntu1 amd64 [installed, automatically]
   Processor microcode firmware for AMD CPUs

intel-microcode/focal-updates,focal-security,now 3.20210608.0ubuntu0.20.04.1 amd64 [installed, automatically]
   Processor microcode firmware for Intel CPUs

iucode-tool/focal,now 2.3.1-1 amd64 [installed, automatically]
   Intel processor microcode tool

microcode.ctl/focal1.18~0+nmu2 amd64
   Intel IA32/IA64 Processor Firmware Utility (Transition Pack)

**Comment by kvadim80** [comment]
So you think a bios update might help?  But, how did Steam work then, on the same computer, but with windows7 64 bit installed?
