### ISSUE TITLE
Steam don't start via GUI or CLI

### ISSUE THREAD

**Issue by 19Topgun93** [ValveSoftware/steam-for-linux#8618]
#### Your system information

* Steam client version (build number or date): 1643947182; updatet today with fresh new install Debian
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
[<script `src="https://gist.github.com/19Topgun93/321f02dce2cf3ce75b15885c0d2613c0.js"></script>`](https://gist.github.com/19Topgun93/321f02dce2cf3ce75b15885c0d2613c0)

`lukas@Debian-Lukas:/usr/bin$ ./steam
Unable to determine whether the expected Nvidia drivers are available.
The Steam client may have limited functionality.
steam.sh[26391]: Running Steam on debian 11 64-bit
steam.sh[26391]: STEAM_RUNTIME is enabled automatically
setup.sh[26523]: Steam runtime environment up-to-date!
steam.sh[26391]: Steam client's requirements are satisfied
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2022-06-04 16:21:08] Startup - updater built May 28 2022 01:45:31
Installing breakpad exception handler for appid(steam)/version(1653947812)
src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
Installing breakpad exception handler for appid(steam)/version(1653947812)
src/steamexe/main.cpp (1009) : failed to initialize update status ui, or create initial window
src/steamexe/main.cpp (1009) : failed to initialize update status ui, or create initial window
assert_20220604162108_4.dmp[26614]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220604162108_4.dmp
lukas@Debian-Lukas:/usr/bin$ Unable to init server: Verbindung ist gescheitert: Verbindungsaufbau abgelehnt

(zenity:26611): Gtk-WARNING **: 16:21:08.935: cannot open display: 
assert_20220604162108_4.dmp[26614]: Finished uploading minidump (out-of-process): success = yes
assert_20220604162108_4.dmp[26614]: response: CrashID=bp-95fdf762-efe7-43ec-9814-b65dc2220604
assert_20220604162108_4.dmp[26614]: file ''/tmp/dumps/assert_20220604162108_4.dmp'', upload yes: ''CrashID=bp-95fdf762-efe7-43ec-9814-b65dc2220604''
`

I have install Debian today. Lutris is install to, and I have the Unix NVIDIA driver install, because lutrix wants this. I use Debian 11 with KDE Plasma.

The prompt with check for update works. After that it crashed, if I start it from GUI. From cli is comes the warnings above, and steam don't start.

Thanks for help.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @19Topgun93, in general Steam needs the host system to provide 32 bit and 64 bit glibc, and a sane 32 bit and 64 bit OpenGL render path. Can you check if any 32 bit OpenGL application like `glxinfo` from `mesa-utils:i386` works? If you just installed the NVIDIA proprietary driver, you might need to restart X or reboot to get the gui session running on it.

**Comment by 19Topgun93** [comment]
thanks for the quick help. I have install the mesa-utils:i386 now https://gist.github.com/19Topgun93/bdb25384be53ee3efaf0dd9bfad3176d there is the new output. 

You can see that I install after mesa this: sudo apt-get install libatk-adaptor:i386 libgail-common:i386

and restart then again. There is this output:  https://gist.github.com/19Topgun93/fb108aec2dbb49d58a899a9864049799

**Comment by kisak-valve** [comment]
Did you actually try a basic 32 bit OpenGL test?

The NVIDIA proprietary driver requires that the running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries are all installed and have exactly the same version to work properly. Your logs read like you are missing NVIDIA's 32 bit userspace libraries.

**Comment by 19Topgun93** [comment]
After your comment, I have looked after 32 bit OpenGL. And I have further packages to https://github.com/lutris/docs/blob/master/InstallingDrivers.md where I thought, this is good enough.

after reboot with new installed packages: https://gist.github.com/19Topgun93/880b5aa1bd89e9abdb50ac3ac550742b

output of, I think, OpenGL with glxinfo: https://gist.github.com/19Topgun93/2eaa308a5da48de2f80941bad61a65b7 

I'm not a completly noop with Linux. (I host a host with virtual Server on debian base  :D) But to run games.... There was ever a bad luck for me. But I want to try away of Windows and I wait for my Steamdeck. So I thought. Now is the time to test the swap to linux. In bad case, I have windows on the other disk :D

**Comment by kisak-valve** [comment]
I'm going to guess that the system-installed glxinfo you tried is the 64 bit variant, testing 64 bit OpenGL, and that you've used NVIDIA's standalone .run installer for their 515.48.07 driver release to bypass Debian's package manager. We've seen in NVIDIA's standalone installer skip installing 32 bit userspace support if it didn't detect some 32 bit system packages. If that's true, then re-running the installer might help.

**Comment by 19Topgun93** [comment]
aaah, then i look into the installation for the nvidia installer for 32 bit. There might be something in the internet :D

**Comment by 19Topgun93** [comment]
Success!!

after install the dependecies for i386. I don't know, if I listed it all here :D, I must reinstall the driver.

To do so: go via strg+alt+F4 into cli. 
then type: systemctl isolate multi-user.target
then: modprobe -r nvidia-drm
then run the sh from NVIDIA again. In the Wizard is the ask to install 32bit libaries.
then: systemctl start graphical.target

now launch steam. I am logged in now :D 

Thanks for your help at saturday evening kisak-valve. I hope this is helpful for others too :D
