### ISSUE TITLE
[Feature Request] Use of xdg-desktop-portals

### ISSUE THREAD

**Issue by SViN24** [ValveSoftware/steam-for-linux#8621]
Why:
Over the years we have had issues on linux regarding dialogs specifically file pickers. They usually did not fit in environments outside of the applications mostly because the toolkit usually did not support it.
The people who created flatpak created xdg-desktop-portals for satisfying that purpose, though this is not a flatpak only solution.

Using them you can replace the picker with ones more appropriate to the operating system bringing a lot of the experience to par with windows.
For example this dialog which is (no offense) very bad usability wise

![image](https://user-images.githubusercontent.com/51864332/172470413-cac64289-fab3-4bdd-b942-c92338de7a4c.png)

Can take the from of a KDE appropriate, GNOME appropriate or whatever appropriate depending on the desktop.
It can also help with the adoption of wayland especially with things like home streaming which are currently broken on wayland.
And finally in the case of flatpaks it allows for the user to upload files in a way that does not compromise the sandbox and is easy.

Thanks for reading and i hope you guys at valve consider this. Also great job with the steam deck. I wish you all success in regards to that device.

Source : https://github.com/flatpak/xdg-desktop-portal

**Comment by kisak-valve** [comment]
Hello @SViN24, this is functionally the same feature request as #6828. Closing in favor of the older issue report.
