### ISSUE TITLE
Steam Installation deletes the wrong packages.

### ISSUE THREAD

**Issue by luimen6** [ValveSoftware/steam-for-linux#8623]
#### Your system information
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

I would like to install Steam on my Ubuntu 22. 04.
However, the libxml2:i386 package is required.

But I have installed the amd64 package. If I install i386, the amd64 package will be uninstalled incl. some programs like php or apache or ubuntu-desktop etc. .

How can I install Steam without libxml2:i386?

The following packages are then always deleted. But that must not be the case:

https://gist.github.com/luimen6/197167b32b7dc7feb6f093cacdf75e5a

**Comment by luimen6** [comment]
Hello @kisak-valve,

the output:

`libxml2:
  Installiert:           2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1
  Installationskandidat: 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1
  Versionstabelle:
 *** 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.13+dfsg-1ubuntu0.1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
     2.9.13+dfsg-1build1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
libxml2:i386:
  Installiert:           (keine)
  Installationskandidat: 2.9.13+dfsg-1ubuntu0.1
  Versionstabelle:
     2.9.13+dfsg-1ubuntu0.1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main i386 Packages
     2.9.13+dfsg-1build1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/main i386 Packages
     2.9.12+dfsg-0+ubuntu20.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu focal/main i386 Packages
`

**Comment by kisak-valve** [comment]
The PPA package version mismatch is from a failed build: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=libxml

**Comment by luimen6** [comment]
Thank you very much, I removed the php focal line and installed libxml2:i386 now and it works :)
