### ISSUE TITLE
Automatic Creation of Unused Game Folders on Steam Start Up

### ISSUE THREAD

**Issue by TannerAMay** [ValveSoftware/steam-for-linux#8624]
#### Your system information

* Steam client version (build number or date): 1.0.0.74-1
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

On launch, Steam creates these hidden folders in the home directory even though I do not have those games installed (folders marked with "x" are for games I don't even own):  
x `~/.killingfloor`  
x `~/.mbwarband`  
`~/.paradoxinteractive`  
x `~/.prey`

It also creates folders for games I don't have installed/own in `~/.local/share`:  
x `~/.local/share/bohemiainteractive`  
`~/.local/share/cdprojektred`  
x `~/.local/share/Dredmor`  
`~/.local/share/FasterThanLight`  
`~/.local/share/feral-interactive`  
x `~/.local/share/HotlineMiami`  
x `~/.local/share/IntoTheBreach`  
`~/.local/share/Paradox Interactive`  
x `~/.local/share/PillarsOfEternity`  
x `~/.local/share/RogueLegacy`  
x `~/.local/share/SteamWorld Dig 2`  
x `~/.local/share/SteamWorldDig`  
`~/.local/share/SuperHexagon`  
x `~/.local/share/Terraria`

All of these folders are empty.

I expected Steam to only create folders it needs.

#### Steps for reproducing this issue:

1. Open Steam
2. Delete folders above
3. Restart Steam and the folders return

**Comment by Daystar1998** [comment]
Are you running Steam in Firejail?

The steam.profile contains a number of mkdir commands with the folders you listed.

Either comment those lines out or add ignore commands for them in steam.local

**Comment by TannerAMay** [comment]
This was it! Thank you.
