### ISSUE TITLE
Switching from desktop to tty and back causes steam UI to become unusable

### ISSUE THREAD

**Issue by GoLD-ReaVeR** [ValveSoftware/steam-for-linux#8625]
#### Your system information

* Steam client version (build number or date): 2022 06 07 3:18:43
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
![steambugged-redacted](https://user-images.githubusercontent.com/6508207/173326827-b05a252d-7afa-40e5-8fac-939acd5d2b87.png)
Blue squares are redactions, not part of the bug.

#### Steps for reproducing this issue:

1. Press Ctrl+Alt+F* to switch to a tty terminal
2. Press Ctrl+Alt+F1 to switch back to Xorg
3. Check the steam windows. They do not have to have been open when this was done, they will bug out the same after they are reopened.

**Comment by GoLD-ReaVeR** [comment]
My other applications do not have this issue.

**Comment by kisak-valve** [comment]
This is a blind guess, but as a workaround, does running steam from a terminal with `steam -no-sandbox` have an effect?

**Comment by GoLD-ReaVeR** [comment]
No, that made it a lot worse. Seems it also stops my browser from rerendering properly until I close the steam windows.

**Comment by GoLD-ReaVeR** [comment]
Whatever happened, I haven't had this issue for a few days now, so I consider this fixed.
