### ISSUE TITLE
Xbox series X controller doesn't work with steam input on

### ISSUE THREAD

**Issue by MrArdillo** [ValveSoftware/steam-for-linux#8632]
#### Your system information

* Steam client version (build number or date): Jun 7 2022 
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Activate Steam Input on Xbox Controller
2. Connect Xbox controller (wired, bluetooth or with dongle) all with the same issue
3. Start any game. The game with more problems is Prince Of Persia: Sands Of Time and doesn't show de steam overlay with it activated

**Comment by kisak-valve** [comment]
Hello @MrArdillo, this issue is already being tracked at #7919. The focus should be on figuring out why Steam's overlay isn't working before pondering Steam Input issues..

Closing in favor of the older issue report.
