### ISSUE TITLE
Steam won't launch on Arch Linux

### ISSUE THREAD

**Issue by 0xFrapples** [ValveSoftware/steam-for-linux#8642]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.74-1
* Distribution (e.g. Ubuntu): Arch Linux x86_64 (Kernel: 5.18.5-zen1-1-zen)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected to run Steam with no problems, but it wouldn't launch at all. When trying to launch it via terminal it would output the below:
```
steam.sh[35966]: Running Steam on arch rolling 64-bit
steam.sh[35966]: STEAM_RUNTIME is enabled automatically
setup.sh[36038]: Steam runtime environment up-to-date!
steam.sh[35966]: Can't find 'steam-runtime-check-requirements', continuing anyway
```
And after that it just won't launch. Tried installing through `pacman -S steam`, made sure that all the NVIDIA dependencies are compatible with my graphics card and system was installed yesterday.

#### Steps for reproducing this issue:

1. Open terminal
2. Run `sudo pacman -S steam`
3. Launch

**Comment by kisak-valve** [comment]
Hello @0xFrapples, can you verify that any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works?

We've seen the Steam client get stuck at that point in the terminal spew before while it was waiting on the NVIDIA proprietary driver. The NVIDIA proprietary driver requires that the video driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version. If you recently changed NVIDIA driver versions, the running kernel module might still be the older version and rebooting would be the easiest way to resolve that scenario.

**Comment by 0xFrapples** [comment]
Turns out I didn't have `dmenu` package installed, now I did install it and Steam works perfectly fine.
