### ISSUE TITLE
[Feature Request] Easy way to select an alternative Executeable for Games 

### ISSUE THREAD

**Issue by NightHammer1000** [ValveSoftware/steam-for-linux#8646]
Some Games, Especially those that ship the incredible shitty "2K Launcher" require the use of cryptic Launch Arguments to start another Executable instead of the Launcher to get the Game running.

This would also be great for Modding. (Skyrim with SKSE) for example.

Ideal would be a Field in the Game Settings right where the Launch Arguments are to select an alternative Executable.

**Comment by kisak-valve** [comment]
Hello @NightHammer1000, this feature request is already being tracked at #5766. Closing as a duplicate.
