### ISSUE TITLE
DXVK graphics driver not detected

### ISSUE THREAD

**Issue by konakona0** [ValveSoftware/steam-for-linux#8647]
#### Your system information

* Steam client version (build number or date): built Jun 7 2022
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] No (tested with beta enabled)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Any game running through Proton gives an error message saying that it cannot find DirectX, or a graphics driver was not found.

Vulkan works fine, vkcube runs, native steam games run normally.
Tried using vkd3d-proton-bin from the AUR, and tried running `steam --reset`
Linux, LLVM, and Mesa packages are up to date. Tested experimental and GE Proton and problem didn't change.

[steam stdout](https://gist.github.com/konakona0/183a38b0cf11db0bcaf46c6334382686)
[Steam system information](https://gist.github.com/konakona0/588a464069c44e534fef1d54bcd06ad9)

This is the error message for Hollow Knight and other unity games. Similar errors pop up for other engines.
![image](https://user-images.githubusercontent.com/28904845/175337304-254afe9a-2248-407c-b058-9e8e9b560ba9.png)

#### Steps for reproducing this issue:

1. Run Steam, native or runtime
2. Start a game with proton dxvk compatibility enabled

**Comment by kisak-valve** [comment]
Hello @konakona0, Vulkan is broken in general on your system. (https://gist.github.com/konakona0/588a464069c44e534fef1d54bcd06ad9#file-gistfile1-txt-L253-L265 and https://gist.github.com/konakona0/588a464069c44e534fef1d54bcd06ad9#file-gistfile1-txt-L555-L568)

We've seen this before at https://github.com/ValveSoftware/Proton/issues/2563#issuecomment-1163372112 and the discussion just after it.

This is not a Steam client bug, report it to AMDVLK.
