### ISSUE TITLE
After update: libLLVM-13.so missing

### ISSUE THREAD

**Issue by prinzhoefte** [ValveSoftware/steam-for-linux#8667]
Sooo, I recently updated my System and Steam stopped working. 

libGL error: MESA-LOADER: failed to open radeonsi: libLLVM-13.so: cannot open shared object file: No such file or directory (search paths /usr/lib32/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: libLLVM-13.so: cannot open shared object file: No such file or directory (search paths /usr/lib32/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: libLLVM-13.so: cannot open shared object file: No such file or directory (search paths /usr/lib32/dri, suffix _dri)
libGL error: failed to load driver: swrast
Steam: An X Error occurred

these are the errors I get. I tried to install version 13 of libLLVM, but it only exists for 64 bit, if I do so, steam just screams at me, that I should install the 32 bit version. But it only exists in the 64 Bit version, or I just cant find it anywhere. 

System Info:
OS: Artix Linux
CPU: I9 9900k
GPU: AMD Rx6900xt
RAM: 32GB

If it is an mistake on my side, please help me out. If not, please fix it ^^
Please let me know, if you need any further information.

**Comment by kisak-valve** [comment]
Hello @prinzhoefte, can you check if any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works?

This reads like your package manager has broken 32 bit mesa on your system and the `lib32-mesa` package needs to be updated to something built against llvm 14 (in the `lib32-llvm-libs` system package).

**Comment by prinzhoefte** [comment]
Yes everything else works, I actually got it to run again, by installing an older version of llvm. It seems as steam does not work properly with version 14. I had to install 13 manually from the repo and then it worked just fine.

**Comment by prinzhoefte** [comment]
Would be really nice, if you could fix it, that steam also works with libLLVM-14.so, because my solution is only a temporary one.

**Comment by kisak-valve** [comment]
`libLLVM-14.so` is a dependency of your video driver, not Steam itself, and Steam doesn't care what release branch of llvm is used. It just cares that it's given a sane, working render path. Something in your OpenGL render stack is built against `libLLVM-13.so`, which is why it's needed at runtime.

Can you share the output of `ldd /usr/lib32/dri/radeonsi_dri.so`?

**Comment by prinzhoefte** [comment]
Here you go:

justin@artixpc ~> ldd /usr/lib32/dri/radeonsi_dri.so
```
        libglapi.so.0 => /usr/lib32/libglapi.so.0 (0xf7ec2000)
        libdrm.so.2 => /usr/lib32/libdrm.so.2 (0xf7ea9000)
        libLLVM-13.so => /usr/lib32/libLLVM-13.so (0xef200000)
        libexpat.so.1 => /usr/lib32/libexpat.so.1 (0xf7e79000)
        libz.so.1 => /usr/lib32/libz.so.1 (0xf7e60000)
        libzstd.so.1 => /usr/lib32/libzstd.so.1 (0xef15e000)
        libsensors.so.5 => /usr/lib32/libsensors.so.5 (0xf7e4f000)
        libdrm_radeon.so.1 => /usr/lib32/libdrm_radeon.so.1 (0xf7e3f000)
        libelf.so.1 => /usr/lib32/libelf.so.1 (0xf63e1000)
        libdrm_amdgpu.so.1 => /usr/lib32/libdrm_amdgpu.so.1 (0xf7e32000)
        libdrm_nouveau.so.2 => /usr/lib32/libdrm_nouveau.so.2 (0xf63d6000)
        libvulkan.so.1 => /usr/lib32/libvulkan.so.1 (0xef0dd000)
        libxcb-dri3.so.0 => /usr/lib32/libxcb-dri3.so.0 (0xf63cf000)
        libstdc++.so.6 => /usr/lib32/libstdc++.so.6 (0xeee00000)
        libm.so.6 => /usr/lib32/libm.so.6 (0xeed2f000)
        libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xef0b8000)
        libc.so.6 => /usr/lib32/libc.so.6 (0xeea00000)
        /usr/lib/ld-linux.so.2 (0xf7f25000)
        libffi.so.8 => /usr/lib32/libffi.so.8 (0xf63c4000)
        libdl.so.2 => /usr/lib32/libdl.so.2 (0xf63bf000)
        libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xf63ba000)
        libncursesw.so.6 => /usr/lib32/libncursesw.so.6 (0xef051000)
        libxml2.so.2 => /usr/lib32/libxml2.so.2 (0xee876000)
        libxcb.so.1 => /usr/lib32/libxcb.so.1 (0xeed03000)
        libXau.so.6 => /usr/lib32/libXau.so.6 (0xf63b5000)
        libXdmcp.so.6 => /usr/lib32/libXdmcp.so.6 (0xef049000)
        libicuuc.so.71 => /usr/lib32/libicuuc.so.71 (0xee600000)
        liblzma.so.5 => /usr/lib32/liblzma.so.5 (0xeecd5000)
        libicudata.so.71 => /usr/lib32/libicudata.so.71 (0xec800000)
```

**Comment by kisak-valve** [comment]
Thanks, the `libLLVM-13.so => /usr/lib32/libLLVM-13.so (0xef200000)` line there confirms what I was writing. This is a system issue, update your system, and if that doesn't change afterwards, then report this issue to your package maintainer for mesa.

Closing as not a Steam issue.
