### ISSUE TITLE
Feature Request: Hide Proton from recent games menu

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#8669]
Hey I wanted to make a request to hide proton versions from the recent games menu as it shouldn't be there and looks bad/out of place

Example:
![image](https://user-images.githubusercontent.com/8393780/177143632-6155993b-bdb6-4924-a6ed-0a6993739294.png)

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue is already being tracked at #6906. Closing as a duplicate.

**Comment by coreybruce** [comment]
Ok no problem, thanks for letting me know.
