### ISSUE TITLE
Need a way to sort by purchase/addition date

### ISSUE THREAD

**Issue by SamusAranX** [ValveSoftware/steam-for-linux#8670]
#### Your system information

* Steam client version: 1656536422
* SteamOS version: 3.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

There's a Steam sale going on and like so many other people, I bought a bunch of games for use on my Deck. To that end, it'd be neat I could sort my library by purchase/addition date so I didn't have to scroll through hundreds of games just to find the ones I just bought. Similarly, I think having "New to Library" as a filter option would be useful as well.

**Comment by kisak-valve** [comment]
Hello @SamusAranX, this reads like a feature request for the Steam client, not SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by ZereoX** [comment]
@kisak-valve There is now a "Date Added to Library" sort option in the Steam Library which filters by most recently added games. I believe this meets the requirements of this request and could therefore be closed out.

|Sort Options|
| --- |
|![image](https://github.com/user-attachments/assets/44db6d0b-a9a2-4444-b84e-0736e1db0f11)|

**Comment by kisak-valve** [comment]
Closing per the last comment.
