### ISSUE TITLE
Septerra core on ubuntu 22.04

### ISSUE THREAD

**Issue by Grub56** [ValveSoftware/steam-for-linux#8675]
#### Your system information

* Steam client version (build number or date): jun 7 2022
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No]Not
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
Septerra Core will load in a corner of the screen.  I am having trouble with making the game go full screen.  Is there a way to fix this?

#### Steps for reproducing this issue:

1. Download Steam
2. Install Septerra Core
3. Launch Septerra core

**Comment by kisak-valve** [comment]
Hello @Grub56, this issue should be reported to the game's dev(s) or discussed on community forums. Closing as not a Steam for Linux client issue.
