### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by leslielg** [ValveSoftware/steam-for-linux#8676]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): kubuntu 22.04
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
I have steam and games install in previous ubuntu 22.04 system, I installed kubuntu yesterday and keep my home folder, also steam games, configs. After install steam in new kubuntu system, I can't open any game. One instance is as below:

GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
Fossilize INFO: Setting autogroup scheduling.
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 427520, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 427520, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/leslie/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=427520 -- '/home/leslie/Ext/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio'\0
Game process added : AppID 427520 "/home/leslie/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=427520 -- '/home/leslie/Ext/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio'", ProcID 21993, IP 0.0.0.0:0
chdir /home/leslie/Ext/SteamLibrary/steamapps/common/Factorio
ERROR: ld.so: object '/home/leslie/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/leslie/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
pid 21995 != 21994, skipping destruction (fork without exec?)
GameAction [AppID 427520, ActionID 1] : LaunchApp changed task to Completed with ""
Game process removed: AppID 427520 "/home/leslie/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=427520 -- '/home/leslie/Ext/SteamLibrary/steamapps/common/Factorio/bin/x64/factorio'", ProcID 21993 
ThreadGetProcessExitCode: no such process 21994
Uploaded AppInterfaceStats to Steam

**Comment by kisak-valve** [comment]
Hello @leslielg, there isn't a usable hint in that terminal spew. 

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. We might get lucky with the extended diagnostics information in there.

**Comment by leslielg** [comment]
Here's the system infor:
https://gist.github.com/leslielg/1a9137cd22c8b89dce5fbed6adf62cf8

**Comment by kisak-valve** [comment]
Thanks. Unfortunately, that looks like a fairly healthy optimus laptop, with the exception that Steam Linux Runtime - Soldier is having a hard time (https://gist.github.com/leslielg/1a9137cd22c8b89dce5fbed6adf62cf8#file-gistfile1-txt-L787). That wouldn't affect the native linux build of Factorio.

Maybe there's a file permission issue with `/home/leslie/Ext/SteamLibrary`?

**Comment by leslielg** [comment]
Thanks Kisak, I remount the /home/leslie/Ext/ external disk, now Factorio (native linux game) can work. I also tried proton games, they work well too.
For issue "with the exception that Steam Linux Runtime - Soldier is having a hard time"
Does it matter? How to fix it?

**Comment by leslielg** [comment]
It seems a bug of KDE partition manager, it mounts my external disk without exec option but remount in KDE partition manager with no change of mount parameter solves this issue.

**Comment by kisak-valve** [comment]
If games using Proton 5.13+ is working, then Steam Linux Runtime - Soldier is also has to be working now, because newer Proton is run inside it.
