### ISSUE TITLE
Steam client notifications show blacked out when using Wayland and the client is open

### ISSUE THREAD

**Issue by orowith2os** [ValveSoftware/steam-for-linux#8681]
#### Your system information

* Steam client version (build number or date): Jun 27 2022, at 21:00:03
* Distribution (e.g. Ubuntu): Fedora 36, using Steam from RPMFusion.
* Opted into Steam client beta?: Yes, but this happens on the stable client as well.
* Have you checked for system updates?: Yes, does not fix the issue.

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected result: Whenever a Steam notification shows, it shows properly without issue.

Actual result: Whenever a Steam notification shows, it shows blacked out whenever the Steam client is not running in the background (running as an active window)

#### Steps for reproducing this issue:

1. Open the Steam client, do not close it to a background process.
2. Do anything that causes a notification.
3. Notification shows blacked out.

### ADDITIONAL NOTES: 

This does not happen on X11, or on top of a Steam game.

**Comment by kisak-valve** [comment]
Hello @orowith2os, this issue is already being tracked at #4735. Closing in favor of the older issue report.

**Comment by orowith2os** [comment]
Thank you for linking to that issue, I misread it as not Wayland-specific and so decided to make a separate issue about it. Is this bug going to be fixed for the client anytime soon?
