### ISSUE TITLE
Steam Play tools showing as games in big picture library

### ISSUE THREAD

**Issue by valters-tomsons** [ValveSoftware/steam-for-linux#8684]
#### Your system information

* Steam client version (build number or date): July 14, 2022
* Distribution: Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Proton versions and anti-cheat runtimes should not appear in Big Picture library

#### Screenshots:

<details> 
  <summary>Click me </summary>
  
![Screenshot_2022-07-14-21_1917x1077](https://user-images.githubusercontent.com/4209639/179014257-2720fff8-c9a4-4dca-867b-d90cd50cb081.png)

![Screenshot_2022-07-14-30_1928x1079](https://user-images.githubusercontent.com/4209639/179014228-af33a9e1-7da5-4d8f-995f-0d06a7adc287.png)
</details>

#### Steps for reproducing this issue:

1. Install any Steam-Play distributions or runtimes
2. Open (Library ⇾ Installed) in Big Picture 
3. Proton & run-times are visible

**Comment by kisak-valve** [comment]
Hello @valters-tomsons, this issue is already being tracked at #6906. Closing as a duplicate.
