### ISSUE TITLE
No smooth scrolling

### ISSUE THREAD

**Issue by litLizard69** [ValveSoftware/steam-for-linux#8688]
#### Your system information

* Steam client version (build number or date): 2021-12-10
* Distribution (e.g. Ubuntu): Arch Linux 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Smooth Scrolling is not present in the Linux-version of the Steam-Client, whereas in Windows there is smooth scrolling. This issue is present on all Linux distros I've tried (Arch Linux, Fedora).

#### Steps for reproducing this issue:

1. Install Steam
2. Open Steam
3. Scroll through the menus

**Comment by kisak-valve** [comment]
Hello @litLizard69, this issue is already being tracked at #7839. To be clear, smooth scrolling is unrelated to the issue that was tracked at #4644, where there used to be substantial jumps on each notch of the scroll wheel.

Closing as a duplicate.
