### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by vaniev2004** [ValveSoftware/steam-for-linux#8691]
#### Steps for reproducing this issue:
Hello everyone. There was a problem: in steam games, the keys do not respond or react with a delay. I haven't played for 2-3 months. Now I tried to go into the CS – some keys do not work, or you need to press 10 times to perform the action. It's the same in the pub. I entered the game from epic games – everything is OK. Main – and everything is ok there . The firewood was updated, even I changed the clave for another one, but the problem was not solved. The funny thing is, everything works fine in the lobby of the games, but, for example, after entering a match in the pub, some keys stop responding, although the same shift + tab works, and the tab itself for viewing inventory does not. I tried reinstalling steam and games - it didn't help. This is the first time I've come across this

**Comment by kisak-valve** [comment]
Hello @vaniev2004, sorry, but this issue report isn't coherent. Issues with individual Steam games should be discussed with the game's developers, not the Steam client itself unless there's a specific detail for a Steam client dev to ponder.

Closing as not a Steam for Linux issue.
