### ISSUE TITLE
Unreadable Font On Steam Browser

### ISSUE THREAD

**Issue by Mechanigenic** [ValveSoftware/steam-for-linux#8692]
#### Your system information

* Steam client version (build number or date): **1654574680**
* Distribution (e.g. Ubuntu): **Ubuntu 20.04.4 LTS**
* Opted into Steam client beta?: [Yes/No] **No**
* Have you checked for system updates?: [Yes/No] **Yes**

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. 
2. 
3. 
I am having a really difficult time, please help.

My fonts on steam browser have changed unexpectedly after I installed bunch of fonts on my computer. They are unreadable and I have tried many things to return to original font family. Nothing worked.

I had the same kind of problem with Firefox google search result screen but I managed to fix it by finding the setting on about:config menu and turning the "allow pages to use different fonts" setting off.

For the steam interface I checked the steam.style file and the base-font is set to Arial family, which is OK. I tried to download a skin and activate it but couldn't find a skins folder to save in. Interface drop-down menu doesn't show the skin.

I would really appreciate it if you show me how to return back to original font settings. Please see the attached screenshot.

Thank you in advance
![Screenshot from 2022-07-17 08-55-52](https://user-images.githubusercontent.com/68223834/179515910-c3b97f11-0439-48e1-977a-65d39faa03aa.png)
![Screenshot from 2022-07-18 14-53-19](https://user-images.githubusercontent.com/68223834/179515956-4158d5b6-3ab6-4d1b-b9c5-12c8436891a9.png)
.

**Comment by Munoida** [comment]
Do you know which font that is? And if so, try removing it to see if you can get it to restore back to normal.

Similar thing happened to me with CJK fonts and I had to remove all MS fonts that was not apart of ttf-mscorefonts

**Comment by Mechanigenic** [comment]
Yes, I removed it but I still have the issue.

Actually there are more than one thousand fonts in my font library and some of them are symbols, not even letters. If the font changes out of control like this I'm afraid more trouble is still to come my way.

**Comment by Munoida** [comment]
Yeah the font is a bit unstable with the Steam for Linux client. Assumingly when you uninstalled/removed the font, it changed to whatever comes next. 
Either I'd wait for an official fix from Valve or try to mess around with the .conf files for fonts. 
_which is a nightmare if you don't know XML like how I don't 😵‍💫_

**Comment by Mechanigenic** [comment]
I checked the steam.style file. Fonts seem to be normal, they are set to Arial font family. But somehow they are overridden by Firefox or Ubuntu. I don't know.

I'll just sit here and wait for help I guess. Don't want to do more harm than good.

**Comment by Mechanigenic** [comment]
OK, I fixed it.

I removed all the fonts in .fonts folder.

Also it turns out that Ubuntu update disabled my NVIDIA graphic card driver. Now that I enabled the graphic card back again maybe that helped too.

Now the fonts are the ones I select on Tweaks app.
