### ISSUE TITLE
Update changelog is black

### ISSUE THREAD

**Issue by L1Q** [ValveSoftware/steam-for-linux#8700]
#### Your system information

* Steam client version: Jul 18 2022, at 16:56:59 (build number or date): 
* Distribution: Manjaro 21.3.3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
Steam update dialogue had a full black rectangle where the changelog would be

![image](https://user-images.githubusercontent.com/6942070/180232216-ec528f80-8a60-4c26-b874-ee9e9d8bc6f7.png)

Clicking on the black did not make the content appear.

Tried [this workaround](https://github.com/ValveSoftware/steam-for-linux/issues/6451#issuecomment-804823348) and it helped:
```pkill -f steamwebhelper.*type=gpu-process```

#### Additional information about my system
![image](https://user-images.githubusercontent.com/6942070/180233614-1bc3999d-ee70-4438-ba43-705c829f1ed9.png)

KDE 5.24.6
Kernel 5.18.11-1-MANJARO
Mesa 22.1.3
[l1q-steam-system-info-2022-07-21.txt](https://github.com/ValveSoftware/steam-for-linux/files/9160382/l1q-steam-system-info-2022-07-21.txt)

**Comment by TTimo** [comment]
May fix itself if you bring up the main Steam client window, you may need to interact with it? Resize? Or re-render the store or library? Can you confirm?

**Comment by L1Q** [comment]
Can not confirm anything at the moment, was not running Steam 24/7 for the last couple of weeks. The update screen appears when the Steam client is running _and_ the update is out. In any other case, the update is handled automatically at client startup.

From my memories, the update window is not resizeable, no interaction with it would make the content appear.

Would be happy to test the next time an opportunity comes up.

It would help a great deal if there was a way to trigger the "Self Updater" dialogue at an arbitrary time. Otherwise, any new updates may keep happening at times when my Steam client is not running, rendering the testing process extremely unreliable.

**Comment by nightsky30** [comment]
From what I've experienced, closing the initial update window (which is blacked out), and then selecting `Check for Steam Client Updates..` from the `Steam` menu in the client window forces the update window to redisplay with the content visible.

**Comment by TTimo** [comment]
Thank you, we've identified the problem, this will be fixed in a future update (next Steam client beta cycle most likely).

**Comment by L1Q** [comment]
Update popup appeared today, was black initially, until I switched focus to the main Steam client window with Friend Activity opened and then back. It worked, similarly to what @TTimo suggested.

**Comment by TTimo** [comment]
To be clear, now that you've updated your client we think this won't happen anymore.

**Comment by L1Q** [comment]
Looks good so far, the latest beta update showed up correctly!

**Comment by L1Q** [comment]
Another update appeared with the changelog displaying just fine.

**Comment by jph168** [comment]
Since this https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3350135361891074312 
Steam Beta Update for me, Update Logs are Displaying in their Entirety now as Expected.

**Comment by L1Q** [comment]
Third update in a row with no issue. Yeah, I think it's safe to call this fixed! Thank you!
