### ISSUE TITLE
Segmentation Fault on Manjaro OS

### ISSUE THREAD

**Issue by theHapalua** [ValveSoftware/steam-for-linux#8704]
#### System Information

* Steam client version : 1.0.0.74 
* Distribution : Manjaro OS
* Opted into Steam client beta? : No
* Have you checked for system updates? : Yes

#### Segmentation Fault
I have bought the Dirt Rally game. I downloaded it. I tried to run after downloading, i got this error:
SIGSEGV(11):Segmentation fault.
![Screenshot from 2022-07-24 10-37-19](https://user-images.githubusercontent.com/62661121/180637356-fec023e4-9c71-45b4-9dac-423a05236c95.png)

**Comment by kisak-valve** [comment]
Hello @theHapalua, as the message says, this issue should be reported to Feral Interactive.

https://wiki.archlinux.org/title/Steam/Game-specific_troubleshooting#Dirt_Rally may also be relevant.
