### ISSUE TITLE
Fossilize Replay should have an option to blacklist igpus

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [ValveSoftware/steam-for-linux#8707]
#### Your system information

* Steam client version (build number or date): 1658799147
* Distribution (e.g. Ubuntu):  Arch linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I have a nvidia optimus laptop and when i reboot into hybrid mode (nvidia offload) fossilize replay start and use a lot of cpu power. im guessing it's processing the shaders for my iGPU that previously was not available since i was using nvidia only.

I don't plan on playing game with my underpowered iGPU i would be glad if there was a way to blacklist my gpu from fossilize.

#### Steps for reproducing this issue:
1.install any distribution that allows to boot to nvidia only and hybrid
2. boot to nvidia only
3.  install game
4. play the game to build shaders
5. reboot to hybrid

**Comment by kisak-valve** [comment]
Hello @Marc-Pierre-Barbier, this is effectively the same issue as #7903. In particular, take a look at the third scenario in the opeing post for a potential workaround.

Closing in favor of the older issue report.
