### ISSUE TITLE
Portal 2 (Linux) fails to sync to cloud

### ISSUE THREAD

**Issue by leagris** [ValveSoftware/steam-for-linux#8708]
#### Your system information

* Steam client version (build number or date): Jun 7 2022, at 03:18:43
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Portal 2 cannot sync to cloud.

#### Steps for reproducing this issue:
See all the still relevant details from this Seven year old issue still plaguing Steam Linux experience, because it was never fixed as it was assigned to @davidw-valve who is either no longer at ValveSoftware or was not concerned:
[Portal 2 (Linux) fails to sync to cloud \#3880](https://github.com/ValveSoftware/steam-for-linux/issues/3880)

#### Other crusty details:
-  @mizapf opened this issue on 12 Jun 2015
- @gdrewb-valve added the[ reviewed ](https://github.com/ValveSoftware/steam-for-linux/labels/reviewed)label [on 15 Jun 2015](https://github.com/ValveSoftware/steam-for-linux/issues/3880#event-331429510)
- @gdrewb-valve assigned [davidw-valve](https://github.com/davidw-valve) [on 15 Jun 2015](https://github.com/ValveSoftware/steam-for-linux/issues/3880#event-331429562)

**Comment by kisak-valve** [comment]
Hello @leagris, there's no value in fragmenting the discussion of an issue over multiple issue reports. Closing as a duplicate.
