### ISSUE TITLE
"force_install_dir" command not installing anything

### ISSUE THREAD

**Issue by Elaina525** [ValveSoftware/steam-for-linux#8709]
* Steam client version (build number or date): 1654574676
* Distribution (e.g. Ubuntu): Centos 8
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I wanted to download csgg and open a dedicated server, but the code "force_install_dir ./csgo_Server" didn't work. After pressing enter, steamCMD immediately start a new line. Nothing happens after I login.

Output after "force_install_dir ./csgo_Server"
![image](https://user-images.githubusercontent.com/101787144/181227732-cedc9c28-2e46-46a5-a518-30fde502f29a.png)

Output after login
![image](https://user-images.githubusercontent.com/101787144/181228057-4bf6eeac-47f8-4ddc-8fd3-a93e7bb43e5a.png)

And if I type the code again, it says "Please use force_install_dir before logon!", which I know, is normal.

Output after another "force_install_dir ./csgo_Server"
![image](https://user-images.githubusercontent.com/101787144/181228255-21e6dfde-8964-4feb-8788-99496697de3b.png)

So is this a bug? What should I do to install csgo? Is this because I did all the steps under root user instead of creating a new user?

#### Steps for reproducing this issue:

1. Run steamCMD.
2. Run "force_install_dir ./csgo_Server"
3. Nothing happens after the code above.

**Comment by kisak-valve** [comment]
Hello @Elaina525, `force_install_dir` should tell SteamCMD what local folder you want it to use for the dedicated server. You're looking for `app_update <appid>` (https://developer.valvesoftware.com/wiki/Command_Line_Options#Commands_2) to tell it to start a download, in this case 740 for Counter-Strike: Global Offensive's dedicated server. (`app_update 740`)

**Comment by Elaina525** [comment]
> Hello @Elaina525, `force_install_dir` should tell SteamCMD what local folder you want it to use for the dedicated server. You're looking for `app_update <appid>` (https://developer.valvesoftware.com/wiki/Command_Line_Options#Commands_2) to tell it to start a download, in this case 740 for Counter-Strike: Global Offensive's dedicated server. (`app_update 740`)

It works! Thank you so much!

**Comment by 1sm23** [comment]
指定的这个./csgo_Server文件夹是不是要自己先建？如果不建，应用会下载到哪里
