### ISSUE TITLE
Error "Corrutped Update Files"

### ISSUE THREAD

**Issue by Paplioh** [ValveSoftware/steam-for-linux#8712]
* Steam client version (build number or date):  1654574690
* Distribution (e.g. Ubuntu): Manjaro x86_64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Cant install the following games (dota 2,tf2) all come as the same error "Corrupted Update Files" when i try again nothing happens and gives the same error.
#### Steps for reproducing this issue:

1. Open steam
2. Install dota 2 or tf2
3.  #error
same issue as #8689 
I reinstalled steam,changed accounts, reinstalled the games but no luck..

**Comment by kisak-valve** [comment]
Hello @Paplioh, there's no point in fragmenting the discussion of an issue over multiple issue reports. Feel free to add your experience to the older issue report.

Closing as a duplicate of #8689.
