### ISSUE TITLE
Guaranteed Steam Bug That's Easily Reproducable

### ISSUE THREAD

**Issue by jph168** [ValveSoftware/steam-for-linux#8713]
#### Your system information

* Steam client version: 1658959288 or latest as of July 26
* Distribution: Manjaro
* Opted into Steam client beta?: Yes and Affects Non Beta as well
* Have you checked for system updates?: Always.

#### Please describe your issue in as much detail as possible:
When receiving a Steam Client Update the Dialog window never displays fully until hovering my cursor 
over the Store Library Community or Profile Tab for it to Display the Rest.
![SteamBug](https://user-images.githubusercontent.com/31376624/181408469-8638455d-f3e1-488d-81cc-61bfc8f73d01.gif)

#### Steps for reproducing this issue:

1. Wait for a Client Update
2. Hover over the Store Library Community or your Profile Tab for it to Display the Rest
3. It never Fails to repeat

To Rule Out Before anyone assumes its my Skin: using or not doesn't matter if it makes anyone feel better knowing, 
this issue has been bugging for a long time, it's clearly a slight inconvenience to most and wouldn't be reported if I didn't it seems.

**Comment by kisak-valve** [comment]
Hello @jph168, this issue is already being tracked at #8700. Closing as a duplicate.
