### ISSUE TITLE
Steam Client Update Incorrect Game Restart

### ISSUE THREAD

**Issue by SanAndreyas** [ValveSoftware/steam-for-linux#8714]
System information

* Steam client version (build number or date): 26 Jul 2022
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Problem:
Each time Steam Client updates to a newer version, after update finishes it automatically loads the last closed game i have played even if before Steam Client update there was no game active ( i was not playing anything ).

Steps for reproducing this issue:

1. Update steam client
2. Last closed game played is launched even if no game was active before starting the update procedure

**Comment by kisak-valve** [comment]
Hello @SanAndreyas, this issue is already being tracked at #1414. Closing as a duplicate.
