### ISSUE TITLE
Screenshot download requires existing file

### ISSUE THREAD

**Issue by michami** [ValveSoftware/steam-for-linux#8715]
#### Your system information

* Steam client version (build number or date): July 26, 2020, 18:54:18
* Distribution (e.g. Ubuntu): Ubuntu Mate
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
When downloading a screenshot from the community content page, the dialog that comes up is for selecting an existing file. I cannot create a new file from the dialog, but I can select an empty file that was `touch`ed first. Selecting the empty file does overwrite it with the image data.

#### Steps for reproducing this issue:

1. Left click a screenshot on the community content page.
2. Right click on the expanded image. and select `Save screenshot as...`
3. Notice it will not allow you to create a new file

Video:

https://user-images.githubusercontent.com/11844847/181994467-84d0788f-2c7b-419e-a0f7-7b2904bf0f4f.mp4

**Comment by kisak-valve** [comment]
Hello @michami, this issue is already being tracked at #6698. Closing as a duplicate.
