### ISSUE TITLE
Cloud sync error launching game benchmarks from the command line while offline

### ISSUE THREAD

**Issue by ccallawa-intel** [ValveSoftware/steam-for-linux#8722]
#### Your system information

* Steam client version (build number or date): Jul 26 2022 at 18:54:18
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Launching game benchmarks from the command line is blocked by a cloud sync failure dialog, even when cloud sync is disabled. Going online seems to work around the issue.

#### Steps for reproducing this issue:

1. Disable Cloud Sync in global options
2. Go Offline
5. Launch a game benchmark from the command line. For example, here is Shadow of the Tomb Raider: `steam -applaunch 750920 -benchmark`

**Comment by kisak-valve** [comment]
Cloud Sync ignores user preferences - Always Enabled

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/8763.
@nPHYN1T3 posted on 2022-08-26T23:03:43:

#### Your system information

* Steam client version: 1660960119
* Distribution (e.g. Ubuntu): Garuda (Arch)
* Opted into Steam client beta?: [Yes/No] Tried both
* Have you checked for system updates?: Duh

#### Please describe your issue in as much detail as possible:
I have disabled Cloud Sync for each game individually and globally. However if Steam is offline Cloud Sync always nags that it's enabled and can not sync. This has been going on for a few prior builds and I have reported it to Steam Support several times.

#### Steps for reproducing this issue:

1. Start Steam with Cloud Sync disabled (per game and or globally).
2. Start a game and expect it to launch.
3. Enjoy the Nag screen that Cloud Sync can't sync.

![1-August 26 2022 16:56:31](https://user-images.githubusercontent.com/38122105/187001112-ef5bc913-86a4-4ed8-9a36-58dc72a32b55.png)

The UI has been broken too though for the attached Screen Shot I notice it's finally sizing correctly to where you can click the nag. Before the UI would be sized in a way that you would have to scroll to click the nag buttons.

GameAction [AppID 107410, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
LogonFailure No Connection
GameAction [AppID 107410, ActionID 1] : LaunchApp waiting for user response to SynchronizingCloud "syncfailed"

Installing breakpad exception handler for appid(steam)/version(1658944613)
GameAction [AppID 16900, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
LogonFailure No Connection
GameAction [AppID 16900, ActionID 1] : LaunchApp waiting for user response to SynchronizingCloud "syncfailed"

**Comment by nPHYN1T3** [comment]
I forgot to note the issue is triggered if Steam was launched in offline mode OR online and network has been disabled or dropped.

**Comment by ccallawa-intel** [comment]
Issue is still present in build from Sept 28 2022

**Comment by nPHYN1T3** [comment]
Yup, rumor has it the current beta is fixed but that doesn't help (yet).

**Comment by ccallawa-intel** [comment]
Issue appears to be resolved in build from Oct 6 2022

**Comment by nPHYN1T3** [comment]
Seems fixed here...says with trepidation...

**Comment by ccallawa-intel** [comment]
Issue no longer present in latest builds.
