### ISSUE TITLE
Dynamic collections allows scrolling way past its content

### ISSUE THREAD

**Issue by husjon** [ValveSoftware/steam-for-linux#8727]
#### Your system information

* Steam client version (build number or date):
1658944613
* Distribution (e.g. Ubuntu):
Arch Linux
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Dynamic collections of a certain size (seem to be more than 30 games) makes it so that you can scroll way past the end of the collection.
This does not happen to static collections or even dynamic collections which had the issue that is snapshot to a static collection.

I'm not sure if this happens on other Distros as I'm not able to set up an environment for testing at this moment.

#### Steps for reproducing this issue:

1. Make sure you have a library of about 50+ games.
2. Create a **Dynamic Collection**
3. Set the snapshot filter to f.ex **Single player** (whichever filter yields the most results)
4. You can now scroll way past the end of the collection and the scrollbar barely moves.

#### Screenshots:
**Dynamic collection**
![2022-08-08_12-16](https://user-images.githubusercontent.com/554229/183396250-730127ce-ac7f-4e8f-81bf-af74869c6afa.png)

![2022-08-08_12-18](https://user-images.githubusercontent.com/554229/183396275-9a56ee15-27f3-4451-bd87-cce1572b66e5.png)

**Static collection based on the steps of reproduction**
![2022-08-08_12-20](https://user-images.githubusercontent.com/554229/183396739-0aa03379-2eac-40dc-90bd-3ca87bdf3ba5.png)

![2022-08-08_12-20_1](https://user-images.githubusercontent.com/554229/183396746-aeae4c83-a643-4192-a5fa-5e48d32b8d50.png)

**Comment by husjon** [comment]
I'd like to add that this is also present in the current Beta release (version: **1659742131**, built **Aug 5 2022, 22:53:21**) as well

**Comment by husjon** [comment]
I just updated my Steam client (version: **1663887315**, built **Sep 21 2022, 20:14:17**) and this seem to be resolved.
It seem to now also work as expected in bigger dynamic collections (800+, f.ex filtering all games tagged as **single player**)

I could not see any mentions of a fix in the patch notes so unsure at to which version it was actually fixed in.

City Builder dynamic collection as shown in original issue
![image](https://user-images.githubusercontent.com/554229/191936993-86e2d641-f32c-4bb8-b4ae-f34c856dd39b.png)


Single Player dynamic collection top
![image](https://user-images.githubusercontent.com/554229/191937950-fa2eee11-7c90-4ed1-8ff7-8fcb26abcb3c.png)


Single Player dynamic collection bottom
![image](https://user-images.githubusercontent.com/554229/191937704-b7b727ba-afda-4738-a1ed-7354b46647b3.png)

**Comment by kisak-valve** [comment]
Closing per the last comment.
