### ISSUE TITLE
Can't install/update Steam on Ubuntu 22.04

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#8728]
I can't install/update Steam on Ubuntu 22.04. Neither the deb-file nor a snap-package works. 
I can install the packages but if I open them, the following errors show up.
First it says: "Couldn't find Steam content, did you move it?" Then I have two options - "reinstall" or "search". If I press "reinstall", it shows this error message:
"Couldn't set up Steam data - please contact technical support"
I've already searched on google but nothing worked. I already tried to remove all existing steam files and everything from steam but still the same errors. Of course I restarted the computer a few times and tried the installing process a couple of times.
Ps: If I try to start steam via terminal, it says this:
"bin_steam.sh[10643]: Setting up Steam content in /home/name//.local/share/Steam
/usr/bin/steam: line 46: xterm: command not found"

Yesterday I installed the new Ubuntu before that I've had Ubuntu 16.04, there everything did work fine. Before installing the new Ubuntu, I've uninstalled all games and logged out from Steam.

* Steam client version (build number or date): x
* Distribution: Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

### Steps for reproducing this issue:
You can try to do the same steps as I have done. Written above.

**Comment by TTimo** [comment]
maybe install the xterm package. also make sure you are using Valve's official Steam installer from http://repo.steampowered.com/steam/

**Comment by Firuz2006** [comment]
can you send me ilnk tto installation tutorial

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
