### ISSUE TITLE
Steam Linux Runtimes are unable to access additional disks

### ISSUE THREAD

**Issue by gabuch2** [ValveSoftware/steam-for-linux#8730]
#### Your system information

* Steam client version (build number or date): Jul 26 2022, at 18:54:18
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1 LTS x86_64 
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Games running under Steam Linux Runtimes are unable to access additional disks and system wide directories. This is very serious on games like Retroarch where you might put your content on a secondary disk only for it failing to locate it. Specially if Steam forces you to use the runtime.  

Steam Linux Runtime - Soldier allows you to access all the Steam Library folders, while Sniper only allows you to access the SteamLibrary where the running game is installed. 

#### Steps for reproducing this issue:

1. Install a game where you can access files, like Retroarch
2. Try to access a directory outside the SteamLibrary and Home directories

**Comment by kisak-valve** [comment]
Hello @gabuch2, see the discussion on https://github.com/ValveSoftware/steam-runtime/issues/470. Closing as a duplicate.
