### ISSUE TITLE
GUI components of Library, Friends etc are invisible after system suspend

### ISSUE THREAD

**Issue by coolkys** [ValveSoftware/steam-for-linux#8741]
#### Your system information

* Steam client version (build number or date): 'build date'='Jul 26 2022'; 'steam package versions'='1658944513'
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

What I expected: Normal operation of steam client and all child windows(incl. 'Friends')

What I got: GUI components such as friends entries, game entries(library sidebar games list), background image and buttons within each game library page are not displayed.
>In terms of the Library GUI, hovering mouse cursor over the missing components will seemingly refresh the GUI and force them to reappear.
>However, in terms of the 'Friends' window, resizing/mouse hovering/clicking does not fix the component. If you click on any of the invisible components, the chat window does pop up as normal. Only seemingly possible way to fix this is to restart the entire client.

#### Steps for reproducing this issue:

1. Launch an instance of Steam Client.
2. Suspend computer and resume.
3. Issue occurs.
![Screenshot from 2022-08-14 10-43-05](https://user-images.githubusercontent.com/26796959/184519041-8722cfa5-3ad6-4be4-abec-6fd12081de5b.png)

**Comment by kisak-valve** [comment]
Hello @coolkys, this issue is already being tracked at #8584. Closing as a duplicate.
