### ISSUE TITLE
excessive GPU and CPU

### ISSUE THREAD

**Issue by coolkys** [ValveSoftware/steam-for-linux#8742]
#### Your system information

* Steam client version (build number or date): 'build date'='Jul 26 2022'; 'steam package versions'='1658944513'
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* 
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

What I expected: CPU and GPU usage similar to that of Windows clients.
What I got: In 'Store' or 'Library', CPU usage is around 30~40%, GPU usage is around 50%. In windows, this would be 10~15%, ~20%. Performance is also very low, framerates dropping to (suspected) single digits, and inputs taking seconds to register or even not registering at all.

For reference: CPU is i7-6700K@4.4GHz, GPU is RTX 2060, RAM is 32GB 3200MT/s, Drive is WD Blue 3D 500GB(sata SSD)

#### Steps for reproducing this issue:

1. Launch instance of Steam client.
2. In 'Store' or 'Library', simply scroll down the contents or even just leave them open.
3. Issue occurs.

**Comment by kisak-valve** [comment]
Hello @coolkys, this issue is already being tracked at #7413. Closing as a duplicate.
