### ISSUE TITLE
Non-English input is not supported

### ISSUE THREAD

**Issue by coolkys** [ValveSoftware/steam-for-linux#8743]
#### Your system information

* Steam client version (build number or date): 'build date'='Jul 26 2022'; 'steam package versions'='1658944513'
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

What I expected: Korean and Japanese input to work.
What I got: Even when the input are in the respective input modes in each input settings, any keyboard inputs are cast to English alphabets.

#### Steps for reproducing this issue:

1. Launch instance of Steam client.
2. In any input-able text field, such as store search bar, steam chat etc., attempt to input any non-English languages such as Japanese or Korean.
3. Issue occurs.

**Comment by kisak-valve** [comment]
Hello @coolkys, this issue is already being tracked at #781. Closing as a duplicate.
