### ISSUE TITLE
Steam UI not responsive on Wayland

### ISSUE THREAD

**Issue by m0glan** [ValveSoftware/steam-for-linux#8744]
#### Your system information

* Steam client version (build number or date): 26th of July, 2022
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

As a side note, I have an AMD Ryzen 5 CPU, an AMD Radeon 5700XT graphics card and 16GB of RAM. As far as I remember, this was also an issue on Fedora GNOME.

#### Please describe your issue in as much detail as possible:
On Ubuntu Xorg the Steam UI is working very smoothly without any issues. On Wayland however, any action is very sluggish or delayed. For example, I have to click the minimize/maximize buttons a few times before the action is registered and executed. Same for switching between Store, Library etc. or opening any menu. The interface just feels crippled. 

Why not switch to Ubuntu Xorg then? Well, switching on Xorg comes with its own set of problems. For example, while in-game, GNOME becomes quite laggy on Xorg when minimizing the game to do something else. 

#### Steps for reproducing this issue:

1. Log in on Ubuntu default (Wayland)
2. Start Steam
3. The interface is unresponsive to user interaction

**Comment by m0glan** [comment]
Disabling animated avatars in friends menu resolves the issue. Still, this is a workaround, not a fix.

**Comment by kisak-valve** [comment]
Hello @m0glan, this issue is already being tracked at #6500. Closing as a duplicate.
