### ISSUE TITLE
CS:GO won't launch on proton

### ISSUE THREAD

**Issue by superSTA101** [ValveSoftware/steam-for-linux#8749]
Distro: EndeavourOS (based on arch)

CS:GO won't launch via proton and replies with a error message (attachment).
Yes i have everything up to date.
![Screenshot from 2022-08-16 10-39-14](https://user-images.githubusercontent.com/108533801/185436649-a1d5d106-19d1-47d9-9b06-2323f08a3c80.png)

**Comment by kisak-valve** [comment]
Hello @superSTA101, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title (running CS:GO with Proton is not officially supported), so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-1219664992.
