### ISSUE TITLE
Counter-Strike high latency

### ISSUE THREAD

**Issue by tananaev** [ValveSoftware/steam-for-linux#875]
Latency in Tab menu is floating from 80 to 200 while net_graph shows stable ~50ms. I have never had such problems while playing using Wine, so I don't think Internet connection is causing this. Also, it seems like more players on the server causing higher latency. I tried different rate/cmdrate/updaterate, but nothing helps.

**Comment by kisak-valve** [comment]
Closing as the original issue appears to have been resolved.
