### ISSUE TITLE
Issue with team fortress two MP3 decoding

### ISSUE THREAD

**Issue by RedSunOverParadise** [ValveSoftware/steam-for-linux#8755]
#### Your system information

* Steam client version (build number or date): Steam client application, Built August 20th 2022, Steam package versions: 1660960119
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: [Yes/(No)]
* Have you checked for system updates?: [(Yes)/No]

#### Please describe your issue in as much detail as possible:
Hi, I'm trying to play team fortress two on Fedora 36 (gnome), but I run into issues such as "Failed to create decoder for MP3 [vo/announcer_begins_10sec.mp3]" and other decoding issues. The main menu music and mercenary quotes are also suffering from the same decoder issue.

#### Steps for reproducing this issue:

1. Load into any server on fedora 36
2. Invoke any command that results in a corresponding audio file, such as 'Help!' or any taunt with a sound.
3. Proceed to not have the sound actually play, instead be met with mostly silence.

**Comment by kisak-valve** [comment]
Hello @RedSunOverParadise, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/2734. Closing as a duplicate.
