### ISSUE TITLE
Steam Native black screen in large mode

### ISSUE THREAD

**Issue by chknatwork** [ValveSoftware/steam-for-linux#8756]
#### Your system information

* Steam client version (build number or date): 1660960119
* Distribution (e.g. Ubuntu): Manjaro Linux 21.3.7
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam Native Large Mode shows black out in main interface. Store, Library, Community, and window wenus menus appear but do not respond. Download tab at the bottom doesn't respond either. Using BPM and small mode works though.

Video driver is: video-hybrid-amd-nvidia-prime 2021.11.04 with optimus-manager v1.4
Kernel: x86_64 Linux 5.19.1-3-MANJARO kernel, 
CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx @ 8x 2.1GHz, 
GPU: NVIDIA GeForce GTX 1650

#### Steps for reproducing this issue:

1.  Launch Steam Native
2. Main interface shows black out but menu appear.
3. Switch to BPM and small mode shows normal
4. terminal logs indicate the following lines: 
```
steamwebhelper.sh[13737]: Runtime for steamwebhelper: disabled by environment (this is unsupported)
steamwebhelper.sh[13737]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
```

**Comment by kisak-valve** [comment]
Hello @chknatwork, running Steam with the Steam runtime disabled is not supported. Report this issue to the distro package maintainers who helped you disable it.

That said, this is most likely https://bugs.archlinux.org/task/75600.
