### ISSUE TITLE
 Steam connect link doesn't connect me to a server

### ISSUE THREAD

**Issue by PuddingWithNoMilk** [ValveSoftware/steam-for-linux#8757]
#### Your system information

* Steam client version (build number or date): Aug 20 2022, at 01:17:25
* Distribution (e.g. Ubuntu): Linux Mint Debian Edition
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When i want to join a community server threw a website [for example teamwork.tf]. When i press there join but or any button that uses steam connect link, it only opens my steam app but it doesn't connect me to any servers in game

I didn't have this issue on any other Linux Distributions (pop?_os and ubuntu 21.10) except on Linux Mint ubuntu and debian version

I know that i can just copy the servers IPs and use the "connect [IP-here]" command in source games but it don't want to do that every time i want to try out a new server

**Comment by kisak-valve** [comment]
Hello @PuddingWithNoMilk, this issue is already being tracked at #6992. Closing as a duplicate.
