### ISSUE TITLE
[Linux Mint 20.3] Steam frequently crashing

### ISSUE THREAD

**Issue by Andre8900** [ValveSoftware/steam-for-linux#8762]
#### Your system information

* Steam client version (build number or date): 1660960119 (20th August 2022)
* Distribution (e.g. Ubuntu): Linux Mint 20.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam is crashing frequently without a warning and the running game is closing as well.
I have experienced this on my LM 20.3 installation as well as on a clean(!) LM 21 installation.
It doesn't matter whether the game uses my Nvidia GTX 1060M dGPU or my Intel processor's iGPU.

I fear that some of my hardware might be broken, but I ran memtest86 without any issues.

However, here are the crash dumps. I don't know how to read it and would appreciate any help.
[dumps.zip](https://github.com/ValveSoftware/steam-for-linux/files/9436377/dumps.zip)

#### Steps for reproducing this issue:

1. Open steam
2. Start CS:GO or Shellshock Live (or probably any other game)
3. Wait for it to crash (usually within a few minutes)

**Comment by kisak-valve** [comment]
For reference, the attached crash minidump is a SIGSEGV in an unclear address, coming from steamclient.so. The assert minidumps are DUMP_REQUESTED in crashhandler.so, which is not particularly interesting.

**Comment by Andre8900** [comment]
No more crashes so far in the last days. I'll reopen if needed.

**Comment by WonkySkeleton** [comment]
I've started having this issue in the past few days. I checked my installation of libnm0:i386 as discussed in #8595 and it was already installed. I have also tried to fix the issue removed Steam using the Software Manager and reinstalled and the issue persists. It will often crash while playing games but will also just crash while not the active window. I've also tried the Steam beta but reverted to release as it did not rectify the issue.


    Steam client version (build number or date): 16675222618 (31st Jan 2023)
    Distribution (e.g. Ubuntu): Linux Mint 21.1 (Cinnamon 5.6.7)
    Opted into Steam client beta?: No (crashed on beta as well)
    Have you checked for system updates?: Yes


[dumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/10581280/dumps.tar.gz)

**Comment by Andre8900** [comment]
> I've started having this issue in the past few days. I checked my installation of libnm0:i386 as discussed in #8595 and it was already installed. I also attempted to fix the issue by removing Steam using the Software Manager and reinstalling but the issue persists. I've also tried the Steam beta but reverted to release as it did not rectify the issue. It will often crash while playing games but will also crash while not the active window and without games running.
> 
> Steam client version (build number or date): 16675222618 (31st Jan 2023) Distribution (e.g. Ubuntu): Linux Mint 21.1 (Cinnamon 5.6.7) Opted into Steam client beta?: No (crashed on beta as well) Have you checked for system updates?: Yes
> 
> [dumps.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/10581280/dumps.tar.gz)
> 
> Since uploading the dumps folder I have also used the Synaptic 'complete removal' option to remove steam-launcher, steam-libs-amd64 and steam-libs-i386:i386 (all 1:1.0.0.75), and then purged steam via terminal and reinstalled after manually deleting any steam files uncovered by the find function. Crashes continue to persist.

Hello @WonkySkeleton,
you should probably open a new issue as the moderators will certainly not read comments on closed issues.
My issue was fixed a few days after I reported it here (although I can't tell whether it was because of my report helping them to resolve it...)
