### ISSUE TITLE
Cloud Sync ignores user preferences - Always Enabled

### ISSUE THREAD

**Issue by nPHYN1T3** [ValveSoftware/steam-for-linux#8763]
#### Your system information

* Steam client version: 1660960119
* Distribution (e.g. Ubuntu): Garuda (Arch)
* Opted into Steam client beta?: [Yes/No] Tried both
* Have you checked for system updates?: Duh

#### Please describe your issue in as much detail as possible:
I have disabled Cloud Sync for each game individually and globally. However if Steam is offline Cloud Sync always nags that it's enabled and can not sync. This has been going on for a few prior builds and I have reported it to Steam Support several times.

#### Steps for reproducing this issue:

1. Start Steam with Cloud Sync disabled (per game and or globally).
2. Start a game and expect it to launch.
3. Enjoy the Nag screen that Cloud Sync can't sync.

![1-August 26 2022 16:56:31](https://user-images.githubusercontent.com/38122105/187001112-ef5bc913-86a4-4ed8-9a36-58dc72a32b55.png)

The UI has been broken too though for the attached Screen Shot I notice it's finally sizing correctly to where you can click the nag. Before the UI would be sized in a way that you would have to scroll to click the nag buttons.

GameAction [AppID 107410, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
LogonFailure No Connection
GameAction [AppID 107410, ActionID 1] : LaunchApp waiting for user response to SynchronizingCloud "syncfailed"

Installing breakpad exception handler for appid(steam)/version(1658944613)
GameAction [AppID 16900, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
LogonFailure No Connection
GameAction [AppID 16900, ActionID 1] : LaunchApp waiting for user response to SynchronizingCloud "syncfailed"

**Comment by kisak-valve** [comment]
Hello @nPHYN1T3, this reads like the same issue as #8722. Since this issue report adds a bit more insight, I've gone ahead and transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/8722#issuecomment-1229046714.

Closing in favor of the older issue report.
