### ISSUE TITLE
[ Fedora ] Steam freezing

### ISSUE THREAD

**Issue by Ziimmie** [ValveSoftware/steam-for-linux#8764]
#### Your system information

* Steam client version (build number or date): 1660688177
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam will hang, and won't exit. After killing steam with `gnome-system-monitor`, the process pressure-vessel-wrap is left behind and will not exit, no matter the signal I send it through `kill`. Log for steam is [here.](https://gist.github.com/Ziimmie/b8a1e6708a8a6fb10de67bee303b6972)

#### Steps for reproducing this issue:

1. Open steam
2. Either wait, or try to play/install a game
3. Steam hangs

**Comment by Pistos** [comment]
Possibly related: https://github.com/ValveSoftware/steam-for-linux/issues/8769

**Comment by Ziimmie** [comment]
Marking as not completed. Switched back to Arch and after that the issue seemed to resolve itself.
