### ISSUE TITLE
after last dota 2 update, game looks like this

### ISSUE THREAD

**Issue by nleo** [ValveSoftware/steam-for-linux#8768]
![image](https://user-images.githubusercontent.com/800970/188151100-838fe5eb-39e6-48d9-a484-f083ad35440c.png)

no minimap
allways war fog

what can I do?

**Comment by kisak-valve** [comment]
Hello @nleo, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2/issues/2119. Closing as a duplicate.

**Comment by FlorianWendelborn** [comment]
@nleo the issue should be fixed now, they released a patch a few hours ago that worked for me
