### ISSUE TITLE
 Steam can't find graphics card

### ISSUE THREAD

**Issue by feliciaifu** [ValveSoftware/steam-for-linux#8774]
#### Your system information

* Steam client version (build number or date): Aug 31 2022
* Distribution (e.g. Ubuntu): ArcoLinux(Arch)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
The steam client doesn't work properly on my Archlinux, it doesn't work on my NVIDIA 3060 graphics card, the steam client is horribly laggy and unbearable. But my graphics card driver is working normally, and Devil May Cry 5 can also recognize the graphics card and run normally.
![2022-09-04_12-40_1](https://user-images.githubusercontent.com/93038930/188297715-5a455dc6-d56e-4f5e-a2dc-c184eb689511.png)
![2022-09-04_10-17_1](https://user-images.githubusercontent.com/93038930/188297719-c3259b90-2f6b-4bc9-b909-4a10325f0c96.png)
![2022-09-04_12-40](https://user-images.githubusercontent.com/93038930/188297740-f3b91af5-b6e7-4936-9f4d-ad7077c51bcf.png)
![2022-09-04_12-41](https://user-images.githubusercontent.com/93038930/188297741-3e2b8dc7-feec-4c97-a363-4bf68d50051a.png)

This is system information
[systeminformation.txt](https://github.com/ValveSoftware/steam-for-linux/files/9484055/systeminformation.txt)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by feliciaifu** [comment]
give up playing steam on linux

**Comment by kisak-valve** [comment]
Hello @feliciaifu, your system was missing the 32 bit userspace libraries for the NVIDIA proprietary driver, so it was forced to fall back to mesa/llvmpipe to render on the CPU. On Arch-based systems, this is commonly found in the `lib32-nvidia-utils` system package.

**Comment by feliciaifu** [comment]
> Hello @feliciaifu, your system was missing the 32 bit userspace libraries for the NVIDIA proprietary driver, so it was forced to fall back to mesa/llvmpipe to render on the CPU. On Arch-based systems, this is commonly found in the `lib32-nvidia-utils` system package.

Thank you very much, the problem is solved, thank you😁
