### ISSUE TITLE
[SteamDeck] Steam Controller Configurator shows Deck controls in misleading places 

### ISSUE THREAD

**Issue by spillner** [ValveSoftware/steam-for-linux#8775]
The diagram in the center is an accurate representation of the Deck layout, but the widgets for configuring each input (and the lines connecting them to spots on the Deck diagram) are incorrectly/misleadingly placed.  It looks like the widget arrangement was inherited from the Steam Controller and not tailored to the Deck, even when the Deck is the detected input device (and the proper diagram is displayed).  For example, the lines for the trigger & shoulder button widgets continue past the visible buttons on the Deck diagram and terminate at points near the volume and power buttons.  The lines for the directional pad and A/B/X/Y cluster terminate near the left and right scroll pads, respectively.  Several control widgets do not have any connecting lines, including the select and start buttons (even though they are depicted in the diagram) and the underside pads (which not identifiable as such from their widgets).  Probably most seriously, neither of the joysticks nor the scroll pads have widgets corresponding to (or connected to) their actual locations on the diagram, and so it is not easy to discern visually which set of widgets corresponds to the joysticks and which to the scroll pads (the rectangular ones are indeed the pads, but they're located above the widgets for the joysticks, even though the physical layout is opposite).  All of this makes input configuration more complex and tedious than it needs to be, especially for new users.

It would be user-friendlier if, whenever configuring the Deck as an input Device, the Configurator tool adjusted the layout of the configuration widgets (and connecting lines) to resemble the actual Deck layout, and/or added small identifying labels to the non-obvious widgets (e.g. underside paddles).

Steps to reproduce:
1. Open Steam client on the Deck (either in the native Steam interface or Desktop mode)
2. Select "Settings" under the "View" menu
3. Click on either the "Big Picture Configuration" or "Desktop Configuration" buttons
4. Wait for the Steam Controller Configurator to load (can take over a minute on the first load on the Deck, and 2-10 seconds thereafter)
5. Compare the widget locations around the periphery of the configuration window to the diagram of the Deck at the center
![Steam Deck big picture default controls](https://user-images.githubusercontent.com/1040203/188309449-1aa39b3c-7e7d-4148-84a5-b75100b6eee7.png)

**Comment by ZereoX** [comment]
Hi @spillner, 
I believe that with the new controller configurator the concerns highlighted above have generally been addressed. All inputs now have glyphs or an indication of what is actively being assigned. 

Would you be able to validate?

![image](https://github.com/user-attachments/assets/13aad8dc-8b36-4446-ae67-f0c7bd979ffc)


Thanks.

**Comment by spillner** [comment]
Can confirm that the new configuration tool solves this issue in all modes (native Deck interface, desktop mode with normal client, desktop mode running Steam in Big Picture Mode).  Thank you for following through on this!
