### ISSUE TITLE
Blank controller settings dialogs

### ISSUE THREAD

**Issue by const-reference** [ValveSoftware/steam-for-linux#8776]
#### Your system information

* Steam client version (build number or date): Aug 20 2022
* Distribution (e.g. Ubuntu):  Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
All the settings dialogs in the Controller settings have blank menus and no labels. The controller settings dialogs contain only empty dialog box with a default steam background. So, it is impossible to configure controller for Steam.

### Steps for reproducing this issue:

1. Go to the Main menu-> Steam->Settings->Controller
2. In the dialog box click on any buttons from the following list:
  - GENERAL CONTROLLER SETTINGS
  - BIG PICTURE CONFIGURATION
  - DESKTOP CONFIGURATION
  - GUIDE BUTTON CHORD CONFIGURATION

**Comment by kisak-valve** [comment]
Hello @const-reference, this issue is already being tracked at #8710. Closing as a duplicate.
