### ISSUE TITLE
Bluetooth DS4 controller not disconnecting with "Turn off controller" chord

### ISSUE THREAD

**Issue by Rodancoci** [ValveSoftware/steam-for-linux#8777]
#### Your system information

* Steam client version 1.0.0.75-1
* Distribution: Arch Linux (kernel version 5.19.5.arch1-1)
* Opted into Steam client beta?: No
* Have you checked for system updates? Yes

#### Please describe your issue in as much detail as possible:
The Steam guide button chord for turning off the controller is not working in linux for me. I am using a DualShock 4 controller and it works great in general. The one thing that does not (and is quite annoying) is that **I am unable to turn off the controller** using Steam's guide button chord binding (guide button + triangle by default).

I have tried binding other actions (e.g. show keyboard) to this button combination and they work correctly so I've ruled out the possibility of the key combination not being detected.

While troubleshooting just now I also found out I am unable to apply Steam's default configuration.

![image](https://user-images.githubusercontent.com/11667577/188517691-bad3ada9-7363-4c9d-8f9f-a9490d6f5ae1.png)

Trying to apply the recommended configuration, either by pressing square or by moving the mouse and manually clicking on "Apply Configuration", does nothing.

#### Steps for reproducing this issue:

1. Pair a DS4 controller via bluetooth using OS/DE provided tools.
2. Launch Steam and wait for the configuration to be applied.
3. Press the chord for turning off the controller.
4. Controller does not turn off.

**Comment by kisak-valve** [comment]
Hello @Rodancoci, this issue is already being tracked at #8678. Closing as a duplicate.
