### ISSUE TITLE
[GamepadUI] Option to set resolution for all games instead of per game.

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/steam-for-linux#8778]
Currently I have to go to properties of each game to set the resolution I want to use. I think it makes sense to have a global setting we can set that applies to all games.

**Comment by ruineka** [comment]
This has become one of the most common questions I get and I'm really hoping Valve will throw us a bone. This wasn't always an issue and I sure would like to see a global option be available to set the default resolution for all games. This would be useful in some scenarios on the Steam Deck as well.

**Comment by maddox** [comment]
As an owner with many game, having to manually go to Properties for every installed game is very time consuming and frustrating. As an adult, i could remember to do this the first time I play each game (if i can even remember), but as far as my kids go (or anyone else in the house), they won't. So I have to manually do it ahead of time, which again, is incredibly time consuming and frustrating.

**Comment by schyhub** [comment]
Also would add, an option for "native" for all games by default wouldn't hurt. This would really benefit embedded usage of gamepadui with monitor that doesn't have 720p/800p - which is common on anything but handheld screen

**Comment by ThisByzantineConduit** [comment]
Bump and seconded. When I recently switched over to the new OLED model I had to go through my entire Non-Steam and Steam Library  (over 100 games) and select Native for each one. Was the most time consuming and janky part of transferring over to the new device.

**Comment by matte-schwartz** [comment]
this shipped in the latest Steam Deck Stable client update:
https://store.steampowered.com/news/app/1675200/view/4583064247488721809?l=english

**Comment by ThisByzantineConduit** [comment]
> this shipped in the latest Steam Deck Stable client update:
> 
> https://store.steampowered.com/news/app/1675200/view/4583064247488721809?l=english

Left the comment in this issue a very long time ago so it's nice to see it's now been added! I saw the Steam Client got an update but missed this feature, so thanks for the heads up!

**Comment by kisak-valve** [comment]
Closing as implemented.
