### ISSUE TITLE
Uninstalling a game does not delete the compatdata folder (Steam Deck)

### ISSUE THREAD

**Issue by guymanley** [ValveSoftware/steam-for-linux#8779]
#### Your system information: Steam Deck 256gb with 1TB SD card.

* Steam client version (build number or date): 1660688177
* Distribution (e.g. Ubuntu): Steam OS 3.3.1 Stable brand
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I'd expect that when you uninstall a game, be it from Steam desktop client or game mode, that it would remove the compatdata/(appID) folder for that game as well. I tested and this doesn't seem to be the case. I can see the reasoning for leaving it behind, if a game doesn't have cloud saves then the save data is still stored locally for that game via it's proton container, but this has a rather large disk space cost per game. 200mb to 2gb depending on the game.

#### Steps for reproducing this issue:

1. Install and launch a game targeting windows as the native OS to create a proton folder. 
2. Uninstall the game.
3. Check compatdata folder to see if the appID for your recently installed game it still present, see that it is.

Additional steps on Steam Deck: (note: performed this after uninstalling the game)
1. In game mode, go to your game's library entry. Click the cog icon, then Developer Options, then delete Proton files.
2. Switch to desktop mode. 
3. Check compatdata folder to see if the appID for your recently installed game it still present, see that it is.

I'm not certain that this is even a bug as I've seen issue reported for the opposite effect around 2018. Uninstalling a game deletes proton files and deletes saves for non-cloud save games.

**Comment by kisak-valve** [comment]
Hello @guymanley, this issue is already being tracked at #8587 / #7418. Closing as a duplicate.
