### ISSUE TITLE
General controller settings crashes Steam Client

### ISSUE THREAD

**Issue by Zrocket** [ValveSoftware/steam-for-linux#8783]
#### Your system information

* Steam client version (build number or date): Aug 31 2022, at 04:28:42
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: Yes, but reproducible outside of beta.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
[System info gist](https://gist.github.com/Zrocket/c1ca938c8f9f6aadfdd01c2726d4d20a)

Steam client will crash any time I attempt to access General Controller Settings. I have reinstalled and even downgraded NVIDIA graphics drivers (515.65.01 and 470.141.03), but with no noticeable difference.

This might also be related to another bug where attempting to start BigPicture mode will also crash the client.

#### Steps for reproducing this issue:

1.  Start Steam client
2.  Go to Controller settings
3.  Press General Controller Settings

**Comment by kisak-valve** [comment]
Possibly related to some of the feedback on #8695.

**Comment by Zrocket** [comment]
That's correct; both issues appeared around the same time. I suspect SteamVR might also be effected, but I'm less able to consistently reproduce the issue there.

**Comment by Zrocket** [comment]
How might I provide a crash dump?

**Comment by Zrocket** [comment]
I've discovered something weird while trying to debug this myself: running 'strace -f steam' somehow prevents the crash from happening.

**Comment by TTimo** [comment]
I agree with @kisak-valve this is probably https://github.com/ValveSoftware/steam-for-linux/issues/8695, that button launches a big picture UI window ..

**Comment by Zrocket** [comment]
Duplicate
