### ISSUE TITLE
Can't start the Steam client : Failed to load steamui.so, undefined symbol: vaGetDisplay

### ISSUE THREAD

**Issue by Pixead** [ValveSoftware/steam-for-linux#8789]
#### Your system information

* Steam client version (build number or date): 1661825435
* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible: 

Since yesterday, I cannot start the steam client. Launching the client results in an error : "Failed to load steamui.so", launching it into a command line results in the following error : "Failed to load steamui.so - dlerror(): /home/pixead/.local/share/Steam/ubuntu12_32/libavutil.so.56: undefined symbol: vaGetDisplay"

I have checked, and rebuilt all libraries in both 64 and 32 bits, used steam --reset, removed and reinstalled steam following the guide of gentoo wiki : https://wiki.gentoo.org/wiki/Steam, nothing worked.

#### Steps for reproducing this issue:

1. Launch Steam with or without the steam runtime

**Comment by kisak-valve** [comment]
Hello @Pixead, do you have the `x11-libs/libva` installed and what use flags are you using with it?

**Comment by Pixead** [comment]
Thanks for the swift response!

That package is installed with the abi_x86_32 and wayland use flag.

**Comment by kisak-valve** [comment]
Can you add the X use flag and see if that helps?

**Comment by Pixead** [comment]
Issue solved, thank you!
