### ISSUE TITLE
Steam Crashes on Nvidia/Wayland

### ISSUE THREAD

**Issue by JoshuaFern** [ValveSoftware/steam-for-linux#8792]
#### Your system information

* Steam client version (build number or date): Sep  9 2022, at 23:46:16
* Distribution (e.g. Ubuntu): NixOS/Flatpak
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

System Information: https://gist.github.com/JoshuaFern/9137a79ffd2c6b6bfbe258754ec30288

#### Please describe your issue in as much detail as possible:
When playing "heavier" games Steam will often crash, usually causing the game to crash along with it. In this instance I was playing Quake Champions, but it happens with other games as well.

One workaround I've been using to significantly reduce the amount of crashing is to run games with the third-party "steamtinkerlaunch" compatibility tool and enable the option "toggle steamwebhelper".

Log: https://gist.github.com/JoshuaFern/b2c1a750a145c67b2cb5e2e9dcdd69ab
Coredump: https://gist.github.com/JoshuaFern/3e731ca5dd06f066b531477b164a9a2d

#### Steps for reproducing this issue:

1. Run a game.
2. Wait for the crash.
3. Doubt your choice of switching to Wayland.

**Comment by papamikey** [comment]
it does this for me as well. The less I interact with the Steam Overlay/ steam itself, the better.

**Comment by 20PercentRendered** [comment]
Can confirm. 7 Days to Die horde nights crash steam all the time.

**Comment by JoshuaFern** [comment]
Closing as stale.
