### ISSUE TITLE
Uninstall and Game Properties window non-functional while using -no-browser

### ISSUE THREAD

**Issue by HeteroChromia420** [ValveSoftware/steam-for-linux#8799]
#### Your system information

* Steam client version (build number or date): Aug 20 2022
* Distribution (e.g. Ubuntu): Debian 11 (Stable)
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:

Expected Behavior:
While steam is running with -no-browser, Both Uninstall and Game Properties window should be usable

Actual Behavior:
Neither of those options are usable

#### Steps for reproducing this issue:

1. Launch Steam with -no-browser
2. Right-Click a game in the library and press either "Uninstall" or "Properties"

**Comment by kisak-valve** [comment]
Hello @HeteroChromia420, please see https://github.com/ValveSoftware/steam-for-linux/issues/7564#issuecomment-769901686. Closing in favor of the older issue report.
