### ISSUE TITLE
[Steam Assert] Issues with Steam with 6.0 kernels

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/steam-for-linux#8803]
#### Your system information

* Steam client version (build number or date): Any
* Distribution (e.g. Ubuntu):  Custom Arch Linux
* Opted into Steam client beta?: [Yes/No] Tested with both
* Have you checked for system updates?: [Yes/No] N/A

#### Please describe your issue in as much detail as possible:
What previously worked with the 5.19 kernel or older no longer works on kernel 6.0. If you attempt to use gamescope with steam (embedded or not) it will fail to start. Yes, I know I'm using parameters like steam -steamos3 -steamdeck -gamepadui -steampal with a gamescope-session to get the Steam Deck experience on non-deck hardware, but this works great with kernel version less than 6.0. It's worth noting that even without these parameters the error is the exact same. Using `gamescope -- steam` results in the same assert error. I suspect a similar issue would arise if the Steam Deck were updated to the 6.0-RC2+ kernel.

Steam running from the desktop works fine.
[gamescope-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583846/gamescope-stdout.log)
[steam-stdout.log](https://github.com/ValveSoftware/steam-for-linux/files/9583847/steam-stdout.log)

#### Steps for reproducing this issue:

1. Update to the 6.0 kernel
2. Attempt to launch Steam using gamescope from the TTY.
3. Observe how this crashes with an assert

**Comment by kisak-valve** [comment]
Hello @ruineka, since Steam works when gamescope isn't involved, that makes it more likely this is an issue between gamescope and your kernel. Please report this issue to https://github.com/Plagman/gamescope.

If a gamescope dev finds that this is a Steam-sided quirk, then give me a ping with a link to the relevant details and we can ponder it further on this side.
