### ISSUE TITLE
[Feature Request] Steam Overlay FPS Logging

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/steam-for-linux#8805]
I run into issues with some games where solutions like MangoHud don't hook for reasons I can't track down with some games on my system, but the Steam FPS Counter has 100% success rate polling any game (or at least any game I've tried). I'd like to request a simple flag for having the Steam client "write down" those polling results to a .csv file somewhere. Thank you!

**Comment by kisak-valve** [comment]
Hello @SteveHeist, this feature request is already being tracked at #4460. Closing as a duplicate.
