### ISSUE TITLE
Steam Remote Play doesn't work with a compositor running

### ISSUE THREAD

**Issue by CKWarner** [ValveSoftware/steam-for-linux#8807]
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Kubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

The recent Steam beta update has fixed the terrible encoding performance for Steam Remote Play (yay!) but now it doesn't work unless you manually disable the compositor on the host prior to starting the stream. The client says that the game is running, but it never actually starts the stream of the game, just the desktop. That aspect *was* working properly before the performance fix, it's just that the performance was terrible.

**Comment by kisak-valve** [comment]
Hello @CKWarner, can you describe in more detail how it looks when the streamed game fails? In particular, does #8800 describe the issue you're seeing?

**Comment by CKWarner** [comment]
It does not.

One the host side, no window is opened (blank or otherwise). Steam shows the game status as "Running" but no game is actually launched (as seen by `top` and hardware monitoring),

On the client side (Steam Deck in this case) the stream is of the desktop. The desktop cursor can be moved and elements clicked on with the appropriate controls.

Terminating the stream from the client side leaves the host in the erroneous "Running" state.

The streams function correctly with the compositor manually disabled, so it appears to me to be an issue with opening a window and selecting its contents in a composited environment (which did work previously).

**Comment by CKWarner** [comment]
However the fix in the latest beta for that issue from a cursory test does seem to allow games to launch, though the symptoms were different. I'll test more later when I get the chance.

**Comment by CKWarner** [comment]
I've tried about half a dozen games that weren't working this morning, and they launch after the update. The controls don't get passed through for all of them, which is annoying but is a different issue to the games not launching at all.
