### ISSUE TITLE
Steam Deck | Hotbar Menu input style missing for D-Pad and Face Buttons

### ISSUE THREAD

**Issue by moominfan** [ValveSoftware/steam-for-linux#8808]
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1 build 20220817.1
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When editing a controller layout in Steam Input for Steam Deck, the option for Hotbar Menu is missing in Directional Pad and A,B,X,Y Behavior menus. I expected these controls to have the option like they apparently have in other versions of Steam Input as it is a better fit for them than joysticks and trackpads. This is further supported by [community wiki entry](https://steaminput.wiki/en/input-styles/hotbar-menu) for Hotbar Menu input style.
![hotbar-dpad](https://user-images.githubusercontent.com/106284374/191483701-2ad6aa42-d2e4-429a-9ae1-88060b00e18e.jpg)
![hotbar-abxy](https://user-images.githubusercontent.com/106284374/191483707-0c2dbea9-f128-41d2-a0e1-759bed696b5d.jpg)

#### Steps for reproducing this issue:

1. Edit a controller layout with Steam Deck
2. Edit Directional Pad or A,B,X,Y Behavior
3. Option for Hotbar Menu is missing

**Comment by kisak-valve** [comment]
Hello @moominfan, this reads more like an issue with the Steam client running on SteamOS instead of an issue with SteamOS as a platform, so I've transferred this issue to the steam-for-linux issue tracker.
