### ISSUE TITLE
Standalone Counter-Strike isn't standalone

### ISSUE THREAD

**Issue by directhex** [ValveSoftware/steam-for-linux#881]
It seems the latest changes to the Counter-Strike beta have made the game unplayable for those who own Counter-Strike but not Half-Life. The game stops downloading at arounf the 421 meg mark, and reports "Content still encrypted" when trying to play.

Related to this, installing CS but not HL1 when one has a key for both asks for 903 meg of disk space (which is extraordinarily high), then reports only 9 meg of additional downloads needed to add HL1 on top (which is extraordinarily low)

The HL1 maps folder alone is almost 200 meg, and it makes no sense for CS players to be made to download HL1's full single player map campaign - it also makes no sense for people who legitimately paid for CS not to be allowed to play it until they also pay for HL1

**Comment by friuns2** [comment]
still not fixed 
![image](https://user-images.githubusercontent.com/16543239/37236072-e974569a-240c-11e8-9bb6-bdc1a4358236.png)
