### ISSUE TITLE
Remote Play audio on host

### ISSUE THREAD

**Issue by CKWarner** [ValveSoftware/steam-for-linux#8810]
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Kubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

When using Remote Play with a Linux host (which works now - yay!) audio is played on the host even when "play audio on host" is disabled. More troublingly, using the volume buttons on the client (the Steam Deck in this case) gets passed through to the host to affect **its** volume settings (volume notification pops up on the host). The host shouldn't be playing audio at all, and the client's volume controls should affect only the client.

**Comment by kisak-valve** [comment]
Hello @CKWarner, this issue is already being tracked at #6512. Closing as a duplicate.
