### ISSUE TITLE
Questions about the non Debian based packages

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/steam-for-linux#8813]
Does Valve officially support and maintain the Steam packages through RPMFusion, AUR, Flatpak, and whatever else there might be there?

And out of curiosity, why or why not?

Does the Steam Deck use Steam from Flatpak or AUR?

**Comment by bennettkirlin** [comment]
놀다 [바카라 ](https://liveonlinecardgames.com) 지금 온라인으로 라이브하고 놀라운 보너스를 받으세요

**Comment by Munoida** [comment]
> 놀다 [바카라 ]지금 온라인으로 라이브하고 놀라운 보너스를 받으세요

don't click on that, probably a scam lol

**Comment by TTimo** [comment]
Hello @Munoida,

The only Valve official package for Steam on Linux is a .deb archive, available from http://repo.steampowered.com/steam/

This is what we recommend using on apt-based distros, over any distro-modified installer.

We do not officially support AUR, Flatpak etc. but we are often in touch with the developers of those packages.

**Comment by Munoida** [comment]
I see, thank you for responding!

Do you plan on making official packages for these repositories or would there technically be no need?

**Comment by adenesik471** [comment]
저희 웹사이트 <a href="https://liveonlinecardgames.com/%EC%B9%B4%EB%93%9C-%EA%B2%8C%EC%9E%84/%EC%98%A8%EB%9D%BC%EC%9D%B8-%EB%B0%94%EC%B9%B4%EB%9D%BC-%EA%B2%8C%EC%9E%84-%EB%B0%A9%EB%B2%95-%EB%B0%B0%EC%9A%B0%EA%B8%B0/">온라인 바카 </a> 라를 방문하기만 하면 확실히 돈을 버는 데 도움이 될 아주 멋진 옵션에 대해 조언해 드릴 수 있습니다.

**Comment by Munoida** [comment]
another scam post what the heck?
