### ISSUE TITLE
Steam has troubles rendering UI after waking up from sleep and when it runs for a long timehave to restart Steam).

### ISSUE THREAD

**Issue by kubast2** [ValveSoftware/steam-for-linux#8814]
#### Your system information

* Steam client version (build number or date):  1661825453
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After sometime steam is unable to render:
Friends list(sometimes right after startup).
Unable to render the Library without glitching out.
Unable to view any web pages.
Unable to view chat.
Only happens on Linux, ram passes memtest.

You can also see that resizing a window completely negates this issue.
Once the window is put into it's original position+size(snapped on the right side) the bug happens once again, and contents are miss-rendered/render a lot slower than they should.

[Steam-SystemInformation.log](https://github.com/ValveSoftware/steam-for-linux/files/9626359/Steam-SystemInformation.log)

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
Well no gray boxes at random places.
A bit faster rendering of contents when scrolling.
The html pages loading correctly.
Chat always showing up.
Some chat embeds not screwing with chat window contents.

#### Steps for reproducing this issue:
1. Run steam idle for as long as possible.
2. Use it for a tiny bit(play games, chat etc.).
3. Put your pc to sleep.
4. It may or may not have glitched out, repeat until it does, I can see how that could take a good week.

Including a video showcasing the bug, and how restarting steam(both steam-native and steam-runtime) fixes the issue.

https://user-images.githubusercontent.com/106774766/191767927-0f714ccf-e694-4db9-abff-584c80d628bb.mp4

**Comment by kisak-valve** [comment]
Hello @kubast2, this issue is already being tracked at #8584. Closing as a duplicate.
