### ISSUE TITLE
Steam not opening, inumerous errors

### ISSUE THREAD

**Issue by rakoviny** [ValveSoftware/steam-for-linux#8817]
ASUS Z450L
Intel® Core™ i5-5200U CPU @ 2.20GHz × 4 
Mesa Intel® HD Graphics 5500 (BDW GT2)

* Steam client version (build number or date): latest 27/09/2022
* Distribution (e.g. Ubuntu): Debian Bullseye
* Opted into Steam client beta?: no, i just want it to work.
* Have you checked for system updates?: YES, almost everything i found

I tried to install steam through the .deb file, tried via terminal, via wget, via packages. Tried to fix the errors it presented me, one by one (of course it didn't work). 
It's the first time using debian (and the first time using just linux).

When i open it, through the normal way, just by clicking the icon, shows me this:

_
Steam needs to install these additional packages:
libc6:amd64 libc6:i386 libegl1:amd64 libegl1:i386 libgbm1:amd64 libgbm1:i386 libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1:amd64 libgl1:i386

Press return to proceed with the installation:
_ 

**Then it proceeds to the next error:** 

_
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
libc6 is already the newest version (2.31-13+deb11u4).
libegl1 is already the newest version (1.3.2-1).
libegl1 configurado para instalar manualmente.
libgl1 is already the newest version (1.3.2-1).
libgl1 configurado para instalar manualmente.
libgbm1 is already the newest version (20.3.5-1).
libgbm1 configurado para instalar manualmente.
libgl1-mesa-dri is already the newest version (20.3.5-1).
libc6:i386 is already the newest version (2.31-13+deb11u4).
libc6:i386 configurado para instalar manualmente.
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 dbus-user-session : Depende: dbus (>= 1.12.20-2)
                     Depende: libpam-systemd mas não será instalado
 libcairo2 : Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
 libegl1 : Depende: libegl-mesa0 mas não será instalado
 libgbm1 : Depende: libexpat1 (>= 2.0.1) mas não é instalável
 libgl1 : Depende: libglx0 (= 1.3.2-1) mas não será instalado
 libgl1-mesa-dri : Depende: libexpat1 (>= 2.0.1) mas não é instalável
 libgtk-3-0 : Depende: libcairo-gobject2 (>= 1.14.0) mas não será instalado
              Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
              Depende: libpangocairo-1.0-0 (>= 1.41.0) mas não será instalado
              Depende: libpangoft2-1.0-0 (>= 1.41.0) mas não será instalado
              Recomenda: libgtk-3-bin
              Recomenda: librsvg2-common mas não será instalado
 libpango-1.0-0 : Depende: fontconfig (>= 2.1.91)
 libwebkit2gtk-4.0-37 : Depende: gstreamer1.0-plugins-base mas não será instalado
                        Depende: gstreamer1.0-plugins-good mas não será instalado
                        Depende: libcairo-gobject2 (>= 1.14.0) mas não será instalado
                        Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
                        Depende: libglx0 mas não será instalado
                        Depende: libpangocairo-1.0-0 (>= 1.14.0) mas não será instalado
                        Recomenda: xdg-desktop-portal-gtk
                        Recomenda: gstreamer1.0-libav mas não será instalado
                        Recomenda: gstreamer1.0-plugins-bad mas não será instalado
 yelp : Depende: libyelp0 (= 3.38.3-1) mas não será instalado
        Depende: python3-distro mas não será instalado
E: Erro, pkgProblemResolver::Resolve gerou falhas, isto pode ser causado por pacotes mantidos (hold).
_

And another one:

`You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1`

To top it off:

`Fatal Error: Failed to load steamui.so`

#### Steps for reproducing this issue:

1. I 
2. have
3. no
4. idea.

**Comment by kisak-valve** [comment]
Hello @rakoviny, Steam wants the system to provide 32 bit OpenGL. Since it's not available, it's asking apt to add 32 bit mesa, while also making sure it doesn't try to remove the 64 bit variants of the same packages. Debian's multiarch implementation requires that package variants (amd64 and i386) have exactly the same version. The package manager also strongly dislikes downgrading packages to resolve a conflict. There's most likely an installed system package with a 64 bit version that's newer than what's available in Debian's repos, so apt isn't able to match the 32 bit variant of the same package, so it stops what it is doing instead of making a mess. After that, Steam tries to start even though it's unlikely to have a working video driver.

The general idea to troubleshoot this is to take one pair of Debian packages, ask apt to install them, if it works fine, then that's out of the way and move on to the next one. If it doesn't work fine, then check the package versions of the dependencies with `apt policy` until you find the package with the mismatched amd64 and i386 variants.

For example, I would start with trying `sudo apt install libgl1:amd64 libgl1:i386` and if that fails, then look at `apt policy libgl1:amd64 libgl1:i386` and the versions of the packages that are mentioned as dependencies in the error message.

**Important:** If apt ever asks you to uninstall a bunch of packages, DO NOT let it proceed. That will just give you a bad day.

**Comment by rakoviny** [comment]
K, I just started doing what you said and already failed.

I started by your example: `libgl1:amd64` and `libgl1:i386` 
To my surprise, `libgl1:i386` wasn't installed. When I sent the `apt install libgl1:i386` with `su` on it gave me (AGAIN :'( ) the same error as before :

Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 dbus-user-session : Depende: dbus (>= 1.12.20-2)
                     Depende: libpam-systemd mas não será instalado
 libcairo2 : Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
 libgtk-3-0 : Depende: libcairo-gobject2 (>= 1.14.0) mas não será instalado
              Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
              Depende: libpangocairo-1.0-0 (>= 1.41.0) mas não será instalado
              Depende: libpangoft2-1.0-0 (>= 1.41.0) mas não será instalado
              Recomenda: libgtk-3-bin
              Recomenda: librsvg2-common mas não será instalado
 libpango-1.0-0 : Depende: fontconfig (>= 2.1.91)
 libwebkit2gtk-4.0-37 : Depende: gstreamer1.0-plugins-base mas não será instalado
                        Depende: gstreamer1.0-plugins-good mas não será instalado
                        Depende: libcairo-gobject2 (>= 1.14.0) mas não será instalado
                        Depende: libegl1 mas não será instalado
                        Depende: libfontconfig1 (>= 2.12.6) mas não será instalado
                        Depende: libglx0 mas não será instalado
                        Depende: libgstreamer-gl1.0-0 (>= 1.14.0) mas não será instalado
                        Depende: libpangocairo-1.0-0 (>= 1.14.0) mas não será instalado
                        Recomenda: gstreamer1.0-gl mas não será instalado
                        Recomenda: libgl1-mesa-dri mas não será instalado
                        Recomenda: xdg-desktop-portal-gtk
                        Recomenda: gstreamer1.0-libav mas não será instalado
                        Recomenda: gstreamer1.0-plugins-bad mas não será instalado
 yelp : Depende: libyelp0 (= 3.38.3-1) mas não será instalado
        Depende: python3-distro mas não será instalado
E: Erro, pkgProblemResolver::Resolve gerou falhas, isto pode ser causado por pacotes mantidos (hold).

For a rough translation, it says their dependencies are unmatched then proceeds to say it depends on a lot of things. 
You mentioned it may ask to uninstall something, but even that didn't happen.

**Comment by rakoviny** [comment]
I also did the other thing you asked me, that's why I know it isn't installed. 

`apt policy libgl1:amd64 libgl1:i386`
libgl1:
  Instalado: 1.3.2-1
  Candidato: 1.3.2-1
  Tabela de versão:
 *** 1.3.2-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
libgl1:i386:
  Instalado: (nenhum)
  Candidato: 1.3.2-1
  Tabela de versão:
     1.3.2-1 500
        500 http://deb.debian.org/debian bullseye/main i386 Packages

**Comment by rakoviny** [comment]
might was well give up.
