### ISSUE TITLE
Bioshock infinite in linux not launching

### ISSUE THREAD

**Issue by userofryzen** [ValveSoftware/steam-for-linux#8820]
#### Your system information

* Steam client version (build number or date): Not relevant
* Distribution (e.g. Ubuntu): Not relevant
* Opted into Steam client beta?: [Yes/No]: Not relevant
* Have you checked for system updates?: [Yes/No]: Not relevant

#### Please describe your issue in as much detail as possible:
Bioshock infinite linux native version is not working
It happens since the last 2k update on second September(almost a month has go away and there is not any news about a fix). 
This game has Linux official support, so I want it to work like before in my system in a "click and run " way like before. Actually I didn't finish yet xD. Unless it, probably I'll want my money back since I bought this game on steam after having it on epic store for free, only bought here to support Linux a litlle bit with my money, and it can't be called support from 2k publisher, so no support, no money...

#### Steps for reproducing this issue:

1. Open steam
2. execute bioshock infinite
3.Bioshock crashes

It happens in every Linux desktop, there is more info about it in discussions steam

**Comment by kisak-valve** [comment]
Hello @userofryzen, report this issue to the game's dev(s). Closing because this is not a Steam client issue.
