### ISSUE TITLE
Wingman cascade map cannot be loaded - game crashes

### ISSUE THREAD

**Issue by vegantom** [ValveSoftware/steam-for-linux#8824]
#### Your system information

* Steam client version (build number or date): Sept 28 2022 at 00:52:47, steam API: v020, Steam package versions: 1664418568
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When loading cascade, the game does not load.

#### Steps for reproducing this issue:

1. Install linux
2. Make sure everything is up to date
3. Try to load into the wingman map cascade (with bots or in matchmaking)
4. ???
5. profit

https://steamcommunity.com/app/730/discussions/0/3426697823606029280/ - shows that this has been going on for a long time.

The map should be pulled until it is working on all native operating systems.

Allegedly there is a bug in stdshader (taken from an ubuntu discord, indicating this effects multiple distros, I suspect all linux installs).

Unlikely to be of use:
cpu: 17-7700K - Kernel: 5.19.12-arch1-1
gpu: 1080 Nvidia - nvidia 515.76-3
16GB DDR4 RAM + similar amount of swap partition.
If you want a particular log let me know the path for it and I can upload.

**Comment by kisak-valve** [comment]
Hello @vegantom, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3047. Closing as a duplicate.
