### ISSUE TITLE
steam does not save a specific setting, ever.

### ISSUE THREAD

**Issue by premier69** [ValveSoftware/steam-for-linux#8828]
Hello

how do i save that setting like in the picture, as in i check enable steam play tool to test for all other titles and i want steam tinker launch but it doesn't matter what i choose since after i chose and press ok it wants to restart he client and it does and then when i check settings it's back to being unchecked, it never seems to save.
Files attached: Selection_038.jpg

**Comment by kisak-valve** [comment]
Hello @premier69, this issue report isn't particularly coherent when you're referencing a screenshot that wasn't added. Blind guess, but are you seeing the issue being tracked at #6043?

**Comment by kisak-valve** [comment]
Closing pending feedback.
