### ISSUE TITLE
Hello, please update steam linux client from the deprecated GTK2 to GTK3 or GTK4

### ISSUE THREAD

**Issue by digitalwtf** [ValveSoftware/steam-for-linux#8829]
* Distribution (e.g. Ubuntu): Arch x86_64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

1. Open the Tray Menu
2. Among Others

**Comment by kisak-valve** [comment]
Hello @digitalwtf, without clarifying further, the notes at #6953 apply equally here. As far as I know, Steam uses a mix of VGUI2 and Panorama, not GTK2 to render.

I can only guess that you're referring to #4428 with regard to the tray icon.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ValveSoftware/steam-for-linux/issues/8829#issuecomment-1267770558

@kisak-valve, would this apply to [`discuss.kde.org/t/30535/2`](https://discuss.kde.org/t/how-do-i-ascertain-whether-a-gtk3-4-theme-application-failure-is-the-fault-of-plasma-or-the-application/30535/2?u=rokejulianlockhart) too? To me, it appears to utilise GTK2, even if indirectly.
