### ISSUE TITLE
Can't log back on my main account.

### ISSUE THREAD

**Issue by ReShout876** [ValveSoftware/steam-for-linux#8835]
#### Your system information

* Steam client version (build number or date): i dont know it, it's the recent one with the new login screen
* Distribution (e.g. Ubuntu): Fedora 36
* Opted into Steam client beta?: Nu
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I wanted to see the new login screen, so I logged out then tried to log back in, doesn't work.  
It works on other accounts that I made, but not my main.

#### Steps for reproducing this issue:

1. Log in

images
![](https://cdn.discordapp.com/attachments/1004273671260614757/1027987071043895296/unknown.png)  
once the login screen broke  
![](https://cdn.discordapp.com/attachments/1004273671260614757/1027988664917180478/unknown.png)

**Comment by ReShout876** [comment]
# I might have found the issue!
If I **DON'T** press `Allow` or `Deny`, this event doesn't happen.

**Comment by ReShout876** [comment]
It seems this happens on windows too  
![image](https://user-images.githubusercontent.com/63971777/194627048-2075f08f-e41f-460b-9aea-381ae4b4c4e1.png)

**Comment by poohzaza166** [comment]
now how do i fix this after pressing allow
