### ISSUE TITLE
Media UI does not update when deleting screenshot

### ISSUE THREAD

**Issue by missionfloyd** [ValveSoftware/steam-for-linux#8838]
#### Your system information

* Steam client version: 1664998519
* SteamOS version: 20221005.1
* Opted into Steam client beta?: no
* Opted into SteamOS beta?: no
* Have you checked for updates in Settings > System?: yes

#### Please describe your issue in as much detail as possible:
When deleting screenshots in the Media menu, deleted screenshots are still displayed, and can sometimes still be viewed. Or they may display a blank image icon. They finally disappear after rebooting.

This screenshot was taken _after_ deleting the selected screenshot with ☰ Button > Delete.
![20221007220413_1](https://user-images.githubusercontent.com/4073789/194687761-020dfbdb-80d2-4cf9-8593-9bd6d557d567.jpg)

Looking in `~/.local/share/Steam/userdata/{steamID}/remote/{titleID}/screenshots` shows that it has indeed been deleted.
![Untitled](https://user-images.githubusercontent.com/4073789/194687849-9e578c7d-523a-4c6b-b008-251d41b3ce66.png)

#### Steps for reproducing this issue:

1. Take a screenshot with STEAM+RB.
2. Press STEAM button, go to 'Media'
3. Delete the screenshot you just took.
4. The UI does not update to reflect deleted screenshot.

**Comment by kisak-valve** [comment]
Hello @missionfloyd, this reads more like a Steam client issue than an issue with SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by missionfloyd** [comment]
Looks like it's been fixed, it's working correctly now (Steam client 1666117138)
