### ISSUE TITLE
Resuming from suspend breaks functions

### ISSUE THREAD

**Issue by rado84-github** [ValveSoftware/steam-for-linux#8842]
#### Your system information

* Steam client version (build number or date): 1665100899
* Distribution: Arch Linux 
* Opted into Steam client beta?: No.
* Have you checked for system updates?: Yes.

#### Steps for reproducing this issue:

1. With Steam running in the background put the computer to sleep, then resume it.
2. Have your friends comment a topic of yours or give you an item for the inventory.
3. Open Steam and click on any of the notifications or click "View my steam wallet".
4. Observe that both actions result in a blank screen of the steam client showing nothing but a padlock in the top left corner.

#### Expected result:
After resuming from suspend the said functions should display respectively the clicked notification (new comments to own topic) and the steam wallet with its functions to add funds to it.

#### Other information:
The only way to fix that is to restart the steam client.

#### System information:
![Picture_created_10-10-2022_11-34-40](https://user-images.githubusercontent.com/41172201/194826895-c8330edf-60a9-4681-89ef-d431867eb4b6.png)

**Comment by kisak-valve** [comment]
Hello @rado84-github, this issue is already being tracked at #8584. Closing as a duplicate.
