### ISSUE TITLE
Cannot login with the most recent update to the login methods

### ISSUE THREAD

**Issue by wizardlink** [ValveSoftware/steam-for-linux#8846]
#### Your system information

* Steam client version (build number or date): 2022-10-05 20:39:54 +0000
* Distribution (e.g. Ubuntu): Fedora 36 (Silverblue)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
It is currently impossible to log-in on the Flatpak Steam (though I haven't tested with the system package due to preference) after the mobile app + login updates that recently dropped.

If I try to login with the QR code it gives me a checkmark but never logs me in, whilst the normal log-in method (username + password) gives me error code 79 (both with steam guard code and steam guard confirmation).

For reference, this is also a fresh install of Fedora 36 Silverblue.

#### Steps for reproducing this issue:

1. Install Steam through Flatpak
2. Launch application
3. Attempt to log-in

**Comment by wizardlink** [comment]
For reference, after restarting my system (and with proper udev rules) the problem went away; not sure if I keep the issue open for tracking purposes.

**Comment by kisak-valve** [comment]
Glad to hear you got this working. Closing per the last comment.
