### ISSUE TITLE
Steam Link doesn't work on Ubuntu 22

### ISSUE THREAD

**Issue by rifftual** [ValveSoftware/steam-for-linux#8848]
Hi,

Steam Link stopped working for me when I upgraded to Ubuntu 22.04.01 LTS. Steam on my desktop restart when I establish a connection via Steam Link.

1. Start Steam on my desktop machine
2. Start Steam Link on Android TV (Shield TV) and connect to Steam on desktop machine
3. Steam restarts on desktop machine and so does Steam Link on Android TV

The results is the same whether I run my desktop session on X11 or Wayland.

**Comment by kisak-valve** [comment]
Possibly related to #8843.

**Comment by rifftual** [comment]
Still occurring. Steam crashes (Dumps core) and then restarts. Here's log from starting Steam client on the command line until the crash occurs: https://gist.github.com/rifftual/085ccd21974fe3c0c8b57b3f5670f719

**Comment by rifftual** [comment]
Disabling HW encoding doesn't work.

Here's the log when starting Steam without HW encoding in Remote Play: https://gist.github.com/rifftual/61e907d29e767363710b4ab6ca71b986

And here's the system information: https://gist.github.com/rifftual/9ef631fabf9105d64fe749ca3356232b

**Comment by kisak-valve** [comment]
Looks like hardware encoding didn't get disabled for the software encode workaround experiment.

Your system information confirms that Intel vaapi is broken (https://gist.github.com/rifftual/9ef631fabf9105d64fe749ca3356232b#file-steam-system-information-txt-L217-L230 https://gist.github.com/rifftual/9ef631fabf9105d64fe749ca3356232b#file-steam-system-information-txt-L394-L413). That should be reported to your distro's package maintainer(s) for their Intel vaapi packages.

Blind guess, can you check if `i965-va-driver-shaders` and `i965-va-driver-shaders:i386` are installed with something like `apt policy i965-va-driver-shaders i965-va-driver-shaders:i386`?

**Comment by rifftual** [comment]
Thank you! Installing the shader packages made Remote play work!

Couple of issues persist still (Of which the latter also occurred on Ubuntu 20.04):
- I have to be on Xorg session. On Wayland, I get a black screen on Android TV
- Proton games show a blank scree. I think I could get them to work previously, although slowly, by specifying some opengl CLI flag

**Comment by kisak-valve** [comment]
Glad to hear it started working for you. This issue needs be evaluated on the distro side.

For the follow up issues; the first bullet point is #6148; the second might be similar to https://github.com/ValveSoftware/steam-for-linux/issues/6716#issuecomment-617037116, but regardless, follow up issues should be evaluated separately.

The X error is #9164 and the LD_PRELOAD lines are harmless (#6718)

Closing because this is a system config issue.
