### ISSUE TITLE
Persistent 'unavailable' Steam manifest issues and login problems (latest Steam version)

### ISSUE THREAD

**Issue by NLBen** [ValveSoftware/steam-for-linux#8850]
#### Your system information

* Steam client version (build number or date): 7 October
* Distribution (e.g. Ubuntu): Linux Mint 21 Xfce
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* 
#### Please describe your issue in as much detail as possible:
Yesterday Steam worked just fine. Today the Steam update got applied after a computer shutdown last night, and the new update hits. It started off GREAT (big fat /S). 'Login expired' when I putted in my Steam Guard code a few seconds after the login. Ooooookaaaaay? Second try, it seemed it wanted the Steam Guard again at first but it decided to skip and go to the login. Weirdest login ever.

Now, I'm stuck with a pretty blatant Steam cache issue (caches not DLing properly, I've done everything others recommended in the past in regards to Steam manifest issues on Linux and they keep persisting) and upon trying to install a game the notice about the unavailable

#### Steps for reproducing this issue:

1. Login to Steam
2. Unclear condition
3. Login fuckery
4. Succesfully login in the end
5. See the caches downloads slowing to a crawl (and fail at times due to a 'timeout'
6. Try to install a game, get the manifest issue which also explains the failure of the caches

**Comment by NLBen** [comment]
Update: woops, it's 'unavailable manifest' not missing manifest

**Comment by NLBen** [comment]
https://gist.github.com/NLBen/9732398279a2a842306daa50c1360f4b

**Comment by kisak-valve** [comment]
Hello @NLBen, are you seeing the same login issues if you opt-in to Steam's client beta? I saw some slow shader pre-cache related downloads this morning as well which eventually completed without intervention for me and that looked like a general server-sided issue.

**Comment by NLBen** [comment]
> Hello @NLBen, are you seeing the same login issues if you opt-in to Steam's client beta? I saw some slow shader pre-cache related downloads this morning as well which eventually completed without intervention for me and that looked like a general server-sided issue.

Steam Beta fully fixed both the login issue and the slow caching issues. Weird. I guess 'in beta' it's solved for now, but that leaves 'live' as a potential problem child.
