### ISSUE TITLE
Steam seems slow on Wayland

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/steam-for-linux#8852]
#### Your system information
OS: Pop!_OS 22.04 LTS
KERNEL: 5.19.0-76051900-generic
CPU: Intel Core i7-3770S @ 3.10GHz
GPU: NVIDIA GeForce GTX 1050 Ti
GPU DRIVER: NVIDIA 515.65.01
RAM: 16 GB

* Steam client version: Latest as of writing this (10/15 1:05 PM EST)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No 

#### Please describe your issue in as much detail as possible:
Overall, the Steam client is laggy for what seems to be no reason whatsoever, seemingly especially during notifications..?
It also seems to have some visual bugs like flickering black, but very rarely. Overall the client just seems sluggish.

#### Steps for reproducing this issue:

1. Enable Wayland if it isn't already
2. Use Wayland
3. Open Steam

**Comment by kisak-valve** [comment]
Hello @Munoida, this issue is already being tracked at #6500. Closing as a duplicate.
