### ISSUE TITLE
Remote play doesn't work linux to linux

### ISSUE THREAD

**Issue by thndgonz** [ValveSoftware/steam-for-linux#8855]
#### Your system information

* Steam client version (build number or date): Oct 7, 2022
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (fresh install)

#### Please describe your issue in as much detail as possible:
I installed a fresh install of the distro of my choosing. After that I linked up my steam client with my account and it detected my desktop which I thought it's all I needed. 

I can't decipher anything from the terminal output: https://gist.github.com/thndgonz/b067c60fae324a24926172652ad93bc5

#### Steps for reproducing this issue:

1. Have two devices with linux distros. Preferably arch linux for reproduction.
2. Install steam client. let them detect each other
3. Try to stream a game. Chances are you hear the game's sound then it crashes
[assert_20221017212307_28.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/9805945/assert_20221017212307_28.tar.gz)

**Comment by thndgonz** [comment]
After verifying the log files I discovered this one but I'm not quite sure what to make of it so perhaps anyone could advice: 
[streaming_client.log](https://github.com/ValveSoftware/steam-for-linux/files/9805956/streaming_client.log)

**Comment by thndgonz** [comment]
Seems I was able to find a fix. In my case my laptop uses intel drivers. This **isn't a global fix for everyone** if you are using arch linux and intel drivers: 

Install `lib32-libva-intel-driver lib32-libva libva-vdpau-driver libva-interl-driver` restart your device and you should be good to go.

**Comment by kisak-valve** [comment]
Hello @thndgonz, glad to hear you got this working for yourself. The scenario yoiu've described is that Steam on your system was configured to use hardware accelerated decode, but the relevant system libraries were not installed to support that render path. The missing package dependencies is something that needs to be evaluated by Arch's package maintainer(s) for their Steam package.
