### ISSUE TITLE
An option to edit the Window Decorations

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/steam-for-linux#8856]
Like with Gnome, KDE Plasma and others, we can edit the window decorations however we want, for Steam it is completely static on the right hand side of the window. At the very least can we get an option to put the buttons on the left hand side similar to the OSX client? 
![image](https://user-images.githubusercontent.com/84733553/196428899-48b6c745-ac22-44e9-8dc3-f947cd61a2c0.jpeg)

**Comment by kisak-valve** [comment]
Hello @Munoida, my understanding is that this kind of customization is handled through skins. (https://wiki.archlinux.org/title/steam#Steam_skins)

I've not personally tinkered with them, and there are some issues open related to that (https://github.com/ValveSoftware/steam-for-linux/search?q=skins&type=issues), but my understanding is that they should be working in general.

**Comment by Munoida** [comment]
However, i don't think they change the new Steam Friends windows (Friends list; Chat) as i don't think skins can customize that as it being a chromium process afaik

**Comment by Munoida** [comment]
I think this issue is relevant once again due to the new client not being theme-able (to my knowledge)
