### ISSUE TITLE
Proton crashes on some games after update steam from beta channel to version 1666392376.

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#8864]
#### Your system information

* Steam client version (build number or date):  1666402581
* Distribution (e.g. Ubuntu):  Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)

#### Please describe your issue in as much detail as possible:
Proton crashes on some games after update steam from beta channel to version 1666392376.
Last good steam version was 1666144119

![image](https://user-images.githubusercontent.com/200750/197387370-41c7b133-01d8-449a-803b-5edd6d629c2f.png)

List of affected games:
* Sniper Elite 5 (1029690)  [steam-1029690.log](https://github.com/ValveSoftware/steam-for-linux/files/9846263/steam-1029690.log) https://pastebin.com/Uiyh28ZZ
* Sniper Elite 4 (312660) [steam-312660.log](https://github.com/ValveSoftware/steam-for-linux/files/9846150/steam-312660.log) https://pastebin.com/65HZvzgm
* Resident Evil Revelations 2 (287290) [steam-287290.log](https://github.com/ValveSoftware/steam-for-linux/files/9846902/steam-287290.log) https://pastebin.com/UJVYiwGc
* STAR WARS Jedi: Fallen Order™ (1172380) [steam-1172380.log](https://github.com/ValveSoftware/steam-for-linux/files/9846907/steam-1172380.log) https://pastebin.com/HgCt749b
* Assassin's Creed® Odyssey (812140) [steam-812140.log](https://github.com/ValveSoftware/steam-for-linux/files/9846916/steam-812140.log) https://pastebin.com/R3V9bVSE
* Back 4 Blood (924970) [steam-924970.log](https://github.com/ValveSoftware/steam-for-linux/files/9846923/steam-924970.log) https://pastebin.com/aX1GrM5Z
* It Takes Two (1426210) [steam-1426210.log](https://github.com/ValveSoftware/steam-for-linux/files/9846928/steam-1426210.log) https://pastebin.com/S4giqY0J
* Rayman® Origins (207490) [steam-207490.log](https://github.com/ValveSoftware/steam-for-linux/files/9846933/steam-207490.log) https://pastebin.com/2uBy3c4G
* Need for Speed™ Heat (1222680) [steam-1222680.log](https://github.com/ValveSoftware/steam-for-linux/files/9846939/steam-1222680.log) https://pastebin.com/yc4mTqgN

How workaround issue:
1. Disable shader pre-caching in Steam settings.
2. Switch to stable version (Opt out all beta programs)
3. For some games helps avoiding from launcher.
* For Sniper Elite 4
```
$ mv ~/.steam/steam/steamapps/common/Sniper\ Elite\ 4/Launcher/SniperElite4.exe SniperElite4.exe.bak
$ cp ~/.steam/steam/steamapps/common/Sniper\ Elite\ 4/bin/SniperElite4_DX12.exe ~/.steam/steam/steamapps/common/Sniper\ Elite\ 4/Launcher/SniperElite4.exe
```
* For Sniper Elite 5 
```
$ mv ~/.steam/steam/steamapps/common/Sniper\ Elite\ 5/launcher/sniperelite5.exe sniperelite5.exe.bak
$ cp ~/.steam/steam/steamapps/common/Sniper\ Elite\ 5/bin/sniper5_vulkan.exe ~/.steam/steam/steamapps/common/Sniper\ Elite\ 5/launcher/sniperelite5.exe
```

#### Steps for reproducing this issue:

1. Just update steam from beta channel
2. 
3.

**Comment by kisak-valve** [comment]
Related to https://github.com/ValveSoftware/Proton/issues/6262.

**Comment by kisak-valve** [comment]
Hello @NTMan, per "Fix a crash launching 32 bit Vulkan titles (including DXVK SteamPlay)" in the [2022-10-24](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3428954061821341725) Steam client beta update, please update the Steam client and retest this issue.

**Comment by KibaGasteiz** [comment]
I've tested it and it's working just fine, thanks!

**Comment by kisak-valve** [comment]
Closing as fixed.
