### ISSUE TITLE
[Steam Deck] Steam is Unnecessarily Re-Downloading Files (Shader Cache/Redistributables)

### ISSUE THREAD

**Issue by Walaryne** [ValveSoftware/steam-for-linux#8866]
#### Your system information

* Steam client version (build number or date): 1666117138
* Distribution (e.g. Ubuntu): SteamOS 3.3.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I swapped my SD cards for storing games, and expected everything to just work, and nothing to need to re-download.
Instead, Steam insists that I re-download all of the Steamworks Common Redistributables, and my entire shader cache for each game on the particular card. This is amassing to gigabytes worth of data needing to be re-downloaded every time I swap between my two SD cards with games installed. I cannot find any workaround beyond completely disabling the shader cache, which only works for half of the issue.

I can provide any logs you may need.

**EDIT**
I have a feeling this may have to do with Steam being far too aggressive in how it detects hardware changes (in this case a "drive" being removed and added triggering this).

#### Steps for reproducing this issue:

1. Swap between two SD cards with games installed.

**Comment by kisak-valve** [comment]
Hello @Walaryne, this issue is already being tracked at #8823. Closing as a duplicate.
