### ISSUE TITLE
Games not able to be installed despite Proton being enabled for all games.

### ISSUE THREAD

**Issue by Bitwolfies** [ValveSoftware/steam-for-linux#8867]
Despite having proton enabled for all games, some games like Doom 3 BFG , or Persona 5 Strikers still claim they can only be installed on Windows systems. 
![Screenshot_20221025_205643](https://user-images.githubusercontent.com/65789901/197931408-2f7dc66b-70e7-4030-9aa8-74f8287635bd.png)
Restarted the client, didn't change anythings, not sure how many games this effects, was a blacklist added?

Edit: Burnout paradise no longer appears either, another game known to be broken on proton, doesn't seem to match games that are unverified on steam deck, as I can no longer install Lego Builders journey, a deck verified game.

Edit 2: The Quake remaster as well?

**Comment by kisak-valve** [comment]
Hello @Bitwolfies, this reads like either the selected Proton version in the global Steam Play settings, or the per-game override is set to an invalid or removed Proton version.
