### ISSUE TITLE
after update steam client to version 1666893565 browser scaling being broken

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#8870]
#### Your system information

* Steam client version (build number or date): 1666893565
* Distribution (e.g. Ubuntu): Fedora Rawhide
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)

#### Please describe your issue in as much detail as possible:
After update steam client to version 1666893565 browser scaling being broken
![Screenshot from 2022-10-28 10-21-06](https://user-images.githubusercontent.com/200750/198509497-b6b36bb5-db49-4431-8719-c4ed87c7f6d5.png)

Previous good version was 1666741329
![Screenshot from 2022-10-28 10-30-02](https://user-images.githubusercontent.com/200750/198510258-3d8a292d-c6f9-4e82-97bf-0791ccc9040d.png)

#### Steps for reproducing this issue:

1. Just launch steam client (occurs on all my computers which has enable scaling in GNOME settings)
2. 
3.

**Comment by NTMan** [comment]
UPD: Next update 1666923262 not fixes this issue.
![Screenshot from 2022-10-28 10-40-18](https://user-images.githubusercontent.com/200750/198511821-6015d25d-914a-45a2-854b-9e59e2303d01.png)

**Comment by Seegras** [comment]
More reports. https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3461605794223054264/ 

Please bump up, this probably effects everyone with hi-res monitors not on Windows.

**Comment by jonathanhirschman** [comment]
Scaling issue also affecting the Community section. My basics:

    Steam client version (build number or date): 1666923262
    Distribution (e.g. Ubuntu): Ubuntu 22.04
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes
    Link to full system information report is attached

Note that I'm using fractional scaling to enable multiple monitors with different resolutions/orientations, but not sure that's related to this issue.

![image](https://user-images.githubusercontent.com/33166581/198840263-c5ab9ab8-4427-4a21-9f3d-9e8c4f887dab.png)
[system_info_hirschman.txt](https://github.com/ValveSoftware/steam-for-linux/files/9894006/system_info_hirschman.txt)

**Comment by Sumandora** [comment]
can reproduce on 4K Screen with NVIDIA kernel-open, Gentoo Linux

**Comment by bastimeyer** [comment]
After the recent upgrade, my Steam beta client has started using 200% scaling in those parts where it apparently uses its Chromium component to render the content, like the games library, friends list, etc.

I don't use any HIDPI screens, just two regular 1920x1080 screens, and I also don't have any custom DPI settings applied in KDE Plasma on X11, just 100% scaling with the default DPI value chosen by X11.

I've downgraded to the stable build for now to fix the issue.

**Comment by VladimirMrzv** [comment]
In my system with 1080 screen also 200 scaling on latest update of steam

![image](https://user-images.githubusercontent.com/81020401/199312037-3968f153-38c5-450b-9212-4cbfce2020bd.png)

**Comment by cstew2** [comment]
Scaling for high DPI monitors seems to be fixed for me on the latest beta client update.

**Comment by ThisNekoGuy** [comment]
> Scaling for high DPI monitors seems to be fixed for me on the latest beta client update.

For me, this is only correctly the case if I don't run `-gamepadui`; if I run `-gamepadui`, then use the guide menu to exit big picture mode, then the UI scales too high instead of too small on my 4K display

**Comment by ThisNekoGuy** [comment]
I mean, I just retested this about 10 minutes ago...

**Comment by cstew2** [comment]
> For me, this is only correctly the case if I don't run -gamepadui; if I run -gamepadui, then use the guide menu to exit big picture mode, then the UI scales too high instead of too small on my 4K display

Ah yes, I see what you mean. I've never used `-gamepadui` before but it does seem to scale up too high if you launch steam with that argument. But it does work the way it used to without any arguments.

**Comment by NTMan** [comment]
Yes scaling is fixed in 1667429911 build, but strange thing happened with game properties window. This window is not resizable and content not fit in this window. 

![Screenshot from 2022-11-03 10-31-55](https://user-images.githubusercontent.com/200750/199654715-3d5f6f07-996e-4716-8c17-639c7e392c31.png)

**Comment by Seegras** [comment]
Can confirm. Looks ok on store, library, etc. But not in the dialogues #issuecomment-1301674412 mentions

**Comment by NTMan** [comment]
Finally in 1667871444 version fixed windows sizes.

![Screenshot from 2022-11-08 12-06-28](https://user-images.githubusercontent.com/200750/200497307-f440545d-ea73-43a6-b1a5-6a4d4fe8f4b5.png)
![Screenshot from 2022-11-08 12-06-07](https://user-images.githubusercontent.com/200750/200497321-baa90e67-8de2-4f15-aaa9-379b86b96109.png)
![Screenshot from 2022-11-08 12-05-41](https://user-images.githubusercontent.com/200750/200497323-b4dbe75d-e59b-4217-aae5-c89fbbf0fe6a.png)

**Comment by zaps166** [comment]
Since few releases some windows (game properties, screenshot viewer) are not scaled. Currently I use 1682573004.

**Comment by kisak-valve** [comment]
Hello @zaps166, you're looking for #9209 / #9264 instead of this issue report.

**Comment by zaps166** [comment]
> Hello @zaps166, you're looking for #9209 / #9264 instead of this issue report.

Yes :smile:
