### ISSUE TITLE
hidpi option broken on latest beta

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#8876]
#### Your system information

* Steam client version (build number or date): October 27
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
steam enlarge text and icon option (hidpi) does not scale up steam on the latest beta. works fine If I switch to stable

#### Steps for reproducing this issue:

1. enable enlarge text and icon option (hidpi) on a hidpi screen
2. enroll into beta
3. notice interface does not scale
4. unroll from beta
5. notice interface does scale

**Comment by kisak-valve** [comment]
Hello @zany130, this issue is already being tracked at #8870. Closing as a duplicate.
