### ISSUE TITLE
Duplicate friendlist window

### ISSUE THREAD

**Issue by WebsiteDeveloper** [ValveSoftware/steam-for-linux#8878]
#### Your system information

* Steam client version (build number or date): Oct 31 2022, at 22:15:57
* Distribution (e.g. Ubuntu): Ubuntu 22.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When starting steam the friendlist window is opened twice

**Comment by tearoww** [comment]
Happening to me too on Manjaro KDE, same Steam beta build date. Opening the Friends-window also makes user interface element size larger in the whole client for me.

**Comment by kisak-valve** [comment]
Hello, per "Fixed duplicate friends list windows" in the [2022-11-01](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3379415101030382062) Steam client beta update, please update your Steam client and retest this issue.

**Comment by WebsiteDeveloper** [comment]
The main issue on start seems fixed, although while testing i noticed another way to reproduce the issue:

1. Start Steam
2. Login to friends
3. Set to offline mode 
![image](https://user-images.githubusercontent.com/2150814/199379889-9f61456b-b51b-4223-a56c-fb40510a0693.png)
4. Which results in: 
![image](https://user-images.githubusercontent.com/2150814/199380049-4f3b7413-8ac5-4e7c-b572-e4bb37f3e72e.png)

Then the window sometimes stays when i sign in again, sometimes it crashes and stays blank

**Comment by tearoww** [comment]
> Hello, per "Fixed duplicate friends list windows" in the [2022-11-01](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3379415101030382062) Steam client beta update, please update your Steam client and retest this issue.

Both of the problems are now gone for me.

**Comment by WebsiteDeveloper** [comment]
Seems fixed for me now with the latest version could not reproduce it anymore
