### ISSUE TITLE
System-tray game-quick-start menu not saving entries since latest update

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/steam-for-linux#8884]
#### Your system information

* Steam client version (build number or date): nov 1 2022 at 20:48:56
* Distribution (e.g. Ubuntu):  Manjaro
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

since the latest update (which currently is `nov 1 2022 at 20:48:56`) the game-quick-start menu in the system-tray does not save entries between steam-restarts anymore.
also since the latest update, it had reverted that list somehow to more than ~2 months ago (not using what was set from the previous build prior to `nov 1 2022 at 20:48:56`)

#### Steps for reproducing this issue:

1. have a full list of games recently played and verified to be in the quick-start menu (in a build that is not `nov 1 2022 at 20:48:56`)
2. upgrade to `nov 1 2022 at 20:48:56`
3. start a game
4. close game and steam
5. restart steam and observe not having it saved and having reverted to a older list

PS:
for me it reverted from a list that ways with days recently played (in last build) to a list from august (now is november)

**Comment by Goggo66** [comment]
I can confirm. Steam does remember recently played games when starting and using the new "-gamepadui" option, but this information isn't transferred over to the "old" user interface.

**Comment by belall12** [comment]
> #### معلومات النظام الخاص بك
> * إصدار عميل Steam (رقم البناء أو التاريخ): 1 نوفمبر 2022 الساعة 20:48:56
> * التوزيع (مثل أوبونتو): مانجارو
> * هل اخترت الإصدار التجريبي من عميل Steam ؟: [نعم / لا] نعم
> * هل تحققت من وجود تحديثات للنظام؟: [نعم/لا] نعم
> 
> #### يرجى وصف مشكلتك بأكبر قدر ممكن من التفصيل:
> صف ما_كنت تتوقع حدوثه_وما_حدث_. يرجى ربط أي معاجين رمز كبير[كجوهر Github](https://gist.github.com/)
> 
> نظرا لأن آخر تحديث (وهو حاليا) ، فإن قائمة البدء السريع للعبة في علبة النظام لا تحفظ الإدخالات بين عمليات إعادة تشغيل البخار بعد الآن. أيضا منذ آخر تحديث ، فقد عادت تلك القائمة بطريقة أو بأخرى إلى أكثر من ~ 2 أشهر مضت (لا تستخدم ما تم تعيينه من الإصدار السابق قبل`nov 1 2022 at 20:48:56``nov 1 2022 at 20:48:56`)
> 
> #### خطوات إعادة إنتاج هذه المشكلة:
> 1. لديك قائمة كاملة بالألعاب التي تم لعبها مؤخرا والتحقق من وجودها في قائمة البدء السريع (في بنية غير مكتملة`nov 1 2022 at 20:48:56`)
> 2. الترقية إلى`nov 1 2022 at 20:48:56`
> 3. بدء لعبة
> 4. لعبة قريبة والبخار
> 5. أعد تشغيل البخار ولاحظ عدم حفظه والعودة إلى قائمة أقدم
> 
> ملاحظة: بالنسبة لي ، فقد عادت من قائمة مع الأيام التي تم تشغيلها مؤخرا (في الإصدار الأخير) إلى قائمة من أغسطس (الآن هو نوفمبر)

**Comment by hasezoey** [comment]
Slight update, yesterday i had upgraded steam to build `Nov 2 2022, at 21:58:33`, and the issue still exists in that build

**Comment by hasezoey** [comment]
This issue seems to have been fixed in some version since then, because now in `Nov 11 2022, at 02:54:16` it shows and remembers it correctly again
