### ISSUE TITLE
Games with initial selection dialog window don't start

### ISSUE THREAD

**Issue by Goggo66** [ValveSoftware/steam-for-linux#8887]
#### Your system information

* Steam client version (build number or date): 1667429911
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Testing the new beta client with "-gamepadui" option. Games with an initial selection dialog window (e.g. "Relicta") fail to start.
Starting the same game on the Steam Deck (Relicta is Verified), the selection dialog box is shown. After making the selection, the game starts.

#### Steps for reproducing this issue:

1. Start Steam with "-gamepadui" option
2. Select and start a game that presents an initial selection dialog window (e.g. Relicta)
3. Observe that the "Play" button changes to "Cancel", but nothing more happens, even after waiting for two minutes.

**Comment by Goggo66** [comment]
The latest beta client (version 1667871444) has fixed the issue. Thanks.

**Comment by kisak-valve** [comment]
Closing per the last comment.
