### ISSUE TITLE
Cyberpunk 2077 mouse cursor jumping

### ISSUE THREAD

**Issue by TheSchmutzy** [ValveSoftware/steam-for-linux#8888]
#### Your system information

* Steam client version (build number or date): 1666144119
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1 LTS (64 bit)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
While playing Cyberpunk 2077, even in menu, mouse cursor jumps every 20-30 seconds to the bottom right corner of the screen

#### Steps for reproducing this issue:

1. Start game
2. Wait 20-30 seconds
3. Unable to play with mouse cursor jumping to corner of the screen every 20-30 seconds

It is not my mouse, it happens even when I unplug it, I have tried 3 different versions of Proton, updated my system and GPU drivers, this does not happen with any other game, just with cyberpunk 2077

**Comment by kisak-valve** [comment]
Hello @TheSchmutzy, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1303389731.
