### ISSUE TITLE
Installed game cannot be played as the button says "install" 

### ISSUE THREAD

**Issue by herbzhao** [ValveSoftware/steam-for-linux#8896]
I am using my steamdeck, and today suddenly most of my games become unplayable. 
Steam thinks my game are not installed while they are installed (whether on SSD or SD). 
And I have no way to uninstall the game now. 

https://preview.redd.it/642ru40ul5y91.jpg?width=4080&format=pjpg&auto=webp&s=7ba1e6b9af8d3e6338553fefe65ab4c849b8d767

https://preview.redd.it/t6crf20ul5y91.jpg?width=4080&format=pjpg&auto=webp&s=98004b6e5dd6fe99fd37f08fd5c71bcbac455fe0

**Comment by kisak-valve** [comment]
Hello @herbzhao, this issue reads like a problem with the Steam client instead of SteamOS as a platform, so I've transferred this issue report.

**Comment by TTimo** [comment]
Hello @herbzhao,

I assume this doesn't go away if you restart or reboot?

Have you tried switching to the beta Steam Client (Settings -> System -> Steam Client Udate Channel)? Any software customizations you've made to the device that we should know about?

**Comment by herbzhao** [comment]
Hi @TTimo  I fixed the problem by check the enable "steam play" in the developer options. Not sure why I unchecked it, I may have misread it as steam play everywhere which I don't use.. This options probably shouldn't be allowed to be ticked off on steam deck.
