### ISSUE TITLE
Impossible to close multiple running non-steam games

### ISSUE THREAD

**Issue by rscottyy** [ValveSoftware/steam-for-linux#8900]
#### Your system information

* Steam client version (build number or date): 8/11/22
* Distribution (e.g. Ubuntu): Gentoo (and tested on other distros such as Arch) 
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Whilst running two non-steam games simultaneously, you cannot use steam to exit either application. The application is supposed to close but hangs on exit, and other users explain that it exits the other application instead of the one that was selected.

There's an abundance of steam users on reddit that are experiencing this issue.

https://www.reddit.com/r/SteamDeck/comments/wpmlqu/issue_closing_multiple_nonsteam_games/

I do believe that this issue is moderate in severity.
You are not able to close applications when using -steamdeck / -gamepadui

Ex. you cannot simply close kodi or discord whilst these non-steam apps are running simultaneously.

#### Steps for reproducing this issue:

1. Create two non-steam shortcuts (that don't use proton) 
2. Run both shortcuts at the same time
3. Unable to exit using the steam application, furthermore bugging -steamdeck / gamepadui

**Comment by kisak-valve** [comment]
Hello @rscottyy, this issue is already being tracked at #8474. Closing as a duplicate.
