### ISSUE TITLE
The program is killed instead of minimized to the tray on Sway/I3

### ISSUE THREAD

**Issue by Zeioth** [ValveSoftware/steam-for-linux#8903]
#### Your system information

* Steam client version (build number or date):  1667871444
* Distribution (e.g. Ubuntu): Arch linux (sway)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On I3 and sway desktop environments, pressing the keys "super+shift+q" to close the application, completely kills steam, instead of sending it to the tray area as it should.

#### Steps for reproducing this issue:

1. Install arch linux and sway (but potentially any distro i3/sway)
2. Open steam and then press super+shift+q to close the application. The client is terminated. **This only happens on Steam, every other aplication behave as they should.**

Most likely the program is not treating the close signal correctly.

**Comment by kisak-valve** [comment]
Hello @Zeioth, this is the same issue as #3056 and #3202 where Steam quits on SIGTERM. Feel free to add a note that i3wm is equally affected.

Closing in favor of the older issue reports.
