### ISSUE TITLE
CSGO shows a black screen on opengl and wayland

### ISSUE THREAD

**Issue by digitalwtf** [ValveSoftware/steam-for-linux#8906]
#### Your system information

* Steam client version (build number or date):  Nov 9, 2022
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Nvidia GPU: RTX 3060 ti
* Wayland wlroots

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Game should display
Audio works fine
Steam overlay displays, however on closing it it leaves an artifact

#### Steps for reproducing this issue:

1. Do not use -vulkan, because that works however I can't play in 4:3

**Comment by kisak-valve** [comment]
Hello @digitalwtf, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3029. Closing as a duplicate.
