### ISSUE TITLE
some CS:GO performance issues and display errors

### ISSUE THREAD

**Issue by Callum151** [ValveSoftware/steam-for-linux#8912]
* Steam client version (build number or date): Newest at now(Nov. 12, 2022) I didn't find where to check the steam client version, the issue is not related to steam client anyway
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Description:
1. CS:GO performance issues(low fps)     2. Gloves display are black    3. CS:GO brightness in the game are too dark
I was using Windows 10 system and now I switched to Linux system(Ubuntu-20.04-LTS). The steam client works fine but there are a couple of issues with CS:GO. Firstly, almost all the gloves are black both in game and in the inventory. My red driver gloves are black and I also tested a few other gloves on a community server, none of them are displayed correctly. Secondly, the performance is a big issue on Linux. With the same graphic and display settings, I can reach ~240 fps in game on Windows whereas only ~90 fps on Linux. Thirdly, the game screen is very dark even when I go to settings and change monitor brightness to 130%. I don't have this issue when I use any other application in my Linux system. (Display: Xorg). Since we all know, Source 2 is coming out, I truly hope CS can provide a better gaming experience for Linux users.

PS: you can check my screenshot at https://steamcommunity.com/id/_not_s1mple_/screenshots/

**Comment by kisak-valve** [comment]
Hello @Callum151, we're tracking issues with CS:GO in the csgo-osx-linux issue tracker. Also, in general, multi-issue issue reports are bad for any issue tracker.

1) General Linux performance issues are being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1111. You can post your system information from steam, graphics settings, and performance experience there. 
2) Gloves rendering black is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2102.
3) The game's brightness control is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/50.

Closing as a duplicate.
