### ISSUE TITLE
Per-game vulkan shader cache toggle

### ISSUE THREAD

**Issue by Cphmi** [ValveSoftware/steam-for-linux#8917]
#### Your system information

* Steam client version (build number or date): 1668485453
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:

Steam is shader caching every application launched by it, which is good for steam games. However, I hope this feature can be toggled per game so that we can save some space on the disk. 

The worst thing is - it also works for non-steam apps like emulators, i.e. Yuzu, Cemu, etc., which already have built-in shader caching functionalities. In such case, the shader cache from steam only slows down the game loading and wasted the disk space (steam's shader cache is way more bigger than those generated by emulators).

As shown on the image below, those non-steam apps took more than 10 gigs of storage of shader cache, and there is no way to stop it.

<img width="659" alt="Screenshot 2022-11-15 at 5 01 57 PM" src="https://user-images.githubusercontent.com/99321625/202043000-bb96cf6f-e6ed-4aeb-bada-98c1e3819b8e.png">

#### Steps for reproducing this issue:

1. Add a non-steam game to the steam library, ideally, emulators like Cemu.
2. Run a game with the emulator set to vulkan backend.
3. Caches generated in the `shadercache` folder of steam.

**Comment by kisak-valve** [comment]
Hello @Cphmi, this issue is already being tracked at #6486. Closing as a duplicate.
