### ISSUE TITLE
Closing messages window outside of a game closes all of steam

### ISSUE THREAD

**Issue by Agreeable-f** [ValveSoftware/steam-for-linux#8928]
#### Your system information

* Steam client version (build number or date): Built Nov 17 2022 
* Distribution (e.g. Ubuntu): Garuda linux
* Desktop Environment: KDE Plasma 5.26.3 with latte dock
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

when clicking on steam from my dock sometimes i'd see a "ghost window" as i've called it. it's basically a window that doesn't preview with anything but a close button. closing this (although it may not be labeled as the steam client. usually messages) closes all steam processes. just found out this also works without it being a "ghost window". just closing messages from this state kills steam

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

it should just close the window that it's titled as. (messages, updates, etc.)

#### Steps for reproducing this issue:

1. Open a game.
2. Shift+tab to open the steam menu in-game.
3. open messages with someone or send them an invite. also works if they send you an invite.
4. close the steam menu
5. close the game
6. click steam on your dock (latte dock in my case)
7. close the messages window

**Comment by kisak-valve** [comment]
Hello @Agreeable-f, this issue is already being tracked at #3202. Closing as a duplicate.
