### ISSUE TITLE
Some installed games not seen as being installed

### ISSUE THREAD

**Issue by craig-sanders** [ValveSoftware/steam-for-linux#8933]
#### Your system information

* Steam client version (build number or date):  Nov 19 2022, 1668842190
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I just noticed that some of my games are not identified as being installed when they definitely should be (or even ARE) installed.  I've found two so far, Wolfenstein: The Old Blood (App ID 350080) and Shadowgrounds (App ID 2500).  There may be other "missing" games - I don't know, I haven't checked every game in my Library (that would be tedious as I have 706 steam games).  The majority of my games, at least those that I checked, are correctly identified as being installed.

Instead of the Play button I expect to see, I see an "Install" button and some text saying "AVAILABLE FOR" and then icons for Windows and/or Mac.  The Install button is greyed out and can not be clicked.

If select "Properties -> Local Files" for Old Blood, it tells me that it's taking up 32.68 GB of space.  "Verifying integrity" runs without error, it took a few minutes to run and checked a few hundred files.

"Properties -> Local Files" for Shadowgrounds shows a size of 0 bytes, and the directory only contains Config & Profile directories.   I last played this game in March this year, and as far as I can recall I **did not** uninstall it - it's on a ZFS pool with over 10 TB of free space, and I generally don't uninstall games because I have no reason to do so.  There are some files/dirs dated Oct 24 so it looks like I ran the game then, but didn't play it or save the game...I might have used it to test a new version of Proton or something, just to see if it ran. 

If I go to Properties -> Compatibility and click on "Force the use of a specific Steam Play compatibility tool", then the Install button for Old Blood **immediately** changes to a green Play button, and remains on Play even if I un-check that box. It ran fine. For Shadowgrounds, the button immediately changed to a blue Update button and stays that way if I uncheck the box.  It installed and ran OK.

This suggests the possibility that I had **specific versions of  Proton selected for these games that are no longer installed** - but I have no way of verifying that.   I do know that I have removed several old versions of Proton GE in the last few months.  If that is the case, then Steam should tell me that.  It shouldn't just change Play to a greyed-out Install button and give no hint about what the problem is.

I just found another one, Space Siege (App ID 10530).  Greyed out Install button.  Again, it got a green Play button when I checked the "Force use of specific Steam Proton..." checkbox.    According to Steam, I last played this on Feb 27.  And another, Witcher 3 (App ID 292030) - after toggling the checkbox, this one wants to update 24MB, I last played it on Feb 15.

I don't know if this only started happening with today's update or not.  I only noticed it today whilst idly clicking through some of the games in my library.

#### Steps for reproducing this issue:

1.  Start steam
2.  Examine some games in my library
3.  Notice that some are mysteriously "not installed"

**Comment by kisak-valve** [comment]
Hello @craig-sanders, this issue is already being tracked at #7404. Closing as a duplicate.
