### ISSUE TITLE
Logitech G29 wheel no longer recognized properly by Steam

### ISSUE THREAD

**Issue by CatalinPuscoci** [ValveSoftware/steam-for-linux#8934]
* Steam client version (build number or date):  2021-11-19
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Sometime this week, a steam update rolled out and since then my logitech g29 wheel(the one with PS3/4/5 support) is not recognized by steam and games properly. Games show an xbox 360 controller which has no inputs related to the wheel.
I have checked on the system's side, indeed a virtual `/dev/input/js1` is created by steam. 

Disabling steam input on a per-game basis or disabling playstation controller support makes it show up as a ps3 controller and games will not accept any inputs that are not also present on a controller (pedals, turning wheel) and the l2 and r2 are buttons on the wheel and get picked up as axes in games.

the system still has `/dev/input/js0` which is the actual wheel and it sends events properly with everything working.

[Here's steam's system information if it's of help](https://gist.github.com/CatalinPuscoci/4b5fdfd0f3df08e1cf032480baf2e297)

**Comment by kisak-valve** [comment]
Hello @CatalinPuscoci, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/6323. Closing as a duplicate.

**Comment by CatalinPuscoci** [comment]
Apologies, I could've sworn I looked up 'wheel' and 'logitech' in issues
