### ISSUE TITLE
Steam in Big Picture Mode connected using Steam Link showed a black screen but still interactable

### ISSUE THREAD

**Issue by QuanMCPC** [ValveSoftware/steam-for-linux#8944]
#### Your system information

* Steam client version (build number or date): 1668654564
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
So when I started streaming on Steam using Steam Link from my phone, the Big Picture UI would show up on my computer, but it would show a black screen instead on my phone.

And the thing is that my phone can still interact with the UI even though no picture showed up.

Also, when I launch a game and stream it to Steam Link, it would show the game perfectly fine. 

So I can say it's a graphics or streaming issue of the Big Picture Mode to the Steam Link.

#### Steps for reproducing this issue:

1. Start Steam Link on mobile
2. Press the "Start Play" to start the Big Picture mode on the host computer and the streaming
3. Observe that instead of Steam Link showing the UI of Big Picture Mode, it just showed a black screen

#### Extra info:
 - DE: GNOME 43
 - Display server: Wayland
 - GPU: Intel HD Graphics 620
 - CPU: Intel i3-7020u

**Comment by kisak-valve** [comment]
Hello @QuanMCPC, this issue is already being tracked at #6148. Closing as a duplicate.
