### ISSUE TITLE
Font issue in Arch

### ISSUE THREAD

**Issue by rtrajano** [ValveSoftware/steam-for-linux#8945]
#### Your system information

* Steam client version: 1668654564
* Distribution: Arch
* Opted into Steam client beta?: No at first, then tried beta.
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm seeing an odd issue where there's no text in most of the interface. Interface works if I correctly remember where and what buttons do.

![2022-11-23-032847_3840x2160_scrot](https://user-images.githubusercontent.com/5579073/203506627-64d0c40c-39bc-4b7a-81a8-685e64860689.jpg)

Logs:
https://gist.github.com/rtrajano/7e8de8b07bef159c360cf8564c9693e2

#### Steps for reproducing this issue:

1. `flatpak uninstall com.valvesoftware.Steam`
2. `rm -fr ~/.var/app/com.valvesoftware.Steam`
3. `flatpak install com.valvesoftware.Steam`
4. `flatpak run com.valvesoftware.Steam`
5. sign in with Steam Guard QR
6. Notice normal functioning Steam Client.
7. Quit normally using top left menu.
8. See Segfault in terminal. (logs attached above) `steam.sh: line 798:  5434 Segmentation fault`
9. Start Steam again using `flatpak run com.valvesoftware.Steam` and notice the odd GUI (see screenshot above)

I also repeated the above steps 1-6 but while the Steam Client looked normal during step 6:
1. opted into the Steam Beta Update and restarted Steam.
2. Saw the same Segfault while Steam tried to restart `steam.sh: line 798:  5434 Segmentation fault`
3. `flatpak run com.valvesoftware.Steam`
4. notice the same odd GUI (see screenshot above)

Could be related to this issue except I'm on Arch instead of Fedora and their screenshots show font squares while mine are blank areas. https://github.com/ValveSoftware/steam-for-linux/issues/8935

**Comment by Zeitgeist117** [comment]
might be a dumb question but have you downloaded `ttf-liberation` ? this happened to me when I was new to arch and steam needs the ttf-liberation font to work but for some reason it isn't a dependency when you download steam

**Comment by rtrajano** [comment]
This fixed my issue. I'm wondering why it was working without it for a while and only recently did I need to install this font. Thanks!
