### ISSUE TITLE
Unable to Play Proton Games from Shared SteamLibrary from different user accounts

### ISSUE THREAD

**Issue by eviley3** [ValveSoftware/steam-for-linux#8953]
#### Your system information

* Steam client version (build number or date):  Nov 17, 2022
* Distribution (e.g. Ubuntu):  Endeavour OS
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Make two Linux user accounts, and install Steam on both
2.  Create a Common SteamLibrary folder, say in /mnt/Games with both users having read, write and execute permissions
3.  Install a Proton Game from one of the two Linux user accounts to the common SteamLibrary folder.

The game will launch from the account from which it was installed, but it fails to launch from the other Linux user account, even if both the users belong to the same group.

**Comment by kisak-valve** [comment]
Hello @eviley3, this issue is already being tracked at #6958. In general, wine needs the wineprefix to be owned by the current user to avoid an entire category of hard to diagnose issues and Proton inherits this behavior.

Closing in favor of the older issue report.
