### ISSUE TITLE
DualSense controller mistakenly given X-box prompts in-game; Yakuza Kiwami

### ISSUE THREAD

**Issue by bakerk98** [ValveSoftware/steam-for-linux#8954]
#### Your system information

* Steam client version (build number or date): Stable 11/25/22
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Using SteamInput on Linux, DualSense controller is fully usable in-game. However, I noticed that it will sometimes not portray to games that it is a PlayStation controller. For example, in Yakuza Kiwami, when I launch the game with my DualSense, I would expect to see the PlayStation prompts for buttons, but I see X-box buttons' prompts instead. I can confirm that Yakuza Kiwami offers both, but unfortunately it seems to be an "automatic" detection.

I noticed in dmesg that there is a virtual controller created which I assume is from SteamInput, but that controller is called "Microsoft X-box Pad *". I am wondering if it is possible that this difference in name is what causes the game to display X-box buttons.

I have hid_playstation built-in to my kernel. I also tried this on my SteamDeck, and it has the same issue.

#### Steps for reproducing this issue:

1. Connect a DualSense controller via bluetooth
2. Launch Yakuza Kiwami

**Comment by kisak-valve** [comment]
Hello @bakerk98, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2403#issuecomment-1327897910.
