### ISSUE TITLE
Steam doesn't respect Mozc Japanese IME, treats it as an English keyboard

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/steam-for-linux#8957]
#### Your system information

* Steam client version (build number or date): Latest Beta 11/27 04:24 EST (RPMFusion Repo)
* Distribution: Fedora Workstation Edition 37 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When trying to type with Hiragana or any other input system with Mozc, Steam doesn't detect it and only uses the English keyboard layout. What should happen is that Mozc should be the middleman in the situation and translate Romaji into Hiragana.

https://user-images.githubusercontent.com/84733553/204128130-298f2396-f3e2-4f11-80af-348cc3ccbeac.mp4

#### Steps for reproducing this issue:

1. Install/Enable Mozc Japanese Input System
2. Switch to Hiragana or any other input system
3. it doesn't work

**Comment by kisak-valve** [comment]
Hello @Munoida, this issue is already being tracked at #781. Closing as a duplicate.

**Comment by Munoida** [comment]
> Hello @Munoida, this issue is already being tracked at #781. Closing as a duplicate.

Oh i see, thank you!
