### ISSUE TITLE
G29 Racing Wheel incorrectly detected

### ISSUE THREAD

**Issue by RephlexZero** [ValveSoftware/steam-for-linux#8959]
* Nov 17 2022 Build date
* Arch EndeavourOS
* Non-beta
* Up to date

Out of the blue my Logitech G29 Racing Wheel stopped being detected correctly. 
Previously, in general controller settings it showed up normally and I could use it in games such as F1 2021, BeamNG Drive and Assetto Corsa Competizione under proton with 100% functionality. I used it like this for months, racking up a few hundred hours in racing games on Linux.

Now, it's being detected as a "PS3 Controller" which makes sense as the G29 was originally intended for PS3/4/PC. The buttons on the wheel are mapped like a controller, but in game there is no wheel functionality, no pedals, force feedback, etc... I don't recall doing anything drastic enough to break this.

I've tried a few times to clear the profile it seems to default to, but even reinstalling Steam or my OS seems to persist a broken profile leading me to believe it's a [Steam Input Config cloud save issue](https://store.steampowered.com/account/remotestorageapp/?appid=241100) I used Steam support to request deletion of these files so they can be regenerated correctly but apparently this is not possible... Local deletion seems to always get overwritten and I do not know of a method to delete them myself.

The G29 is correctly identified as as USB device in Dmesg and third party config apps like [Oversteer](https://github.com/berarma/oversteer) also detect it correctly, allowing me to change and calibrate the force feedback.
I am confident the wheel isn't broken, and the regular driver on windows is still fine, but Steam seems to be struggling on Linux here.

#### Steps for reproducing this issue:

1. Fresh install of steam or OS
2. Login
3. Connect wheel
4. Wrong profile is loaded (as shown in steam general controller settings/big picture mode )and cannot be overwritten or used correctly in game
(I think this is a problem that may be unique to my account.)

I have never made an issue here before, please ask for any further info and thanks so much for your help.

![image](https://user-images.githubusercontent.com/67481201/204148046-795266ba-34c0-402d-bf61-c4b6ba27d0b2.png)

![image](https://user-images.githubusercontent.com/67481201/204148117-674e8a92-4aa0-45a4-b7aa-275f384d68a8.png)

![image](https://user-images.githubusercontent.com/67481201/204148156-43dbf62b-e39c-4996-b6b3-5bd253bc490c.png)

**Comment by kisak-valve** [comment]
Hello @RephlexZero, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/6323. Closing as a duplicate.
