### ISSUE TITLE
Linux Steam Client; Install Button for Catherine Classic Greyed Out; all Other Titles Installable

### ISSUE THREAD

**Issue by Xipher-Zero** [ValveSoftware/steam-for-linux#8968]
#### Your system information

* Steam client version (build number or date): Build Date Dec. 1st 2022, at 22:40:28
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: Running Current Software

#### Please describe your issue in as much detail as possible:

Steam play is and has been enabled for all titles for several years on this system. Catherine Classic has been installed and removed several times in the past on this workstation to test compatibility improvements. Recently wanted to test it again against newer GE-Proton versions and the install button is no longer able to be selected (Greyed out) and the windows only icon is present next to it. 

Checked many other titles within my steam library (Both supported and not tested/unsupported) and they are all installable with the install button. Only this single title appears to be effected by whatever is blocking the install.

#### Steps for reproducing this issue:

1. Start steam client and navigate to library.
2. Select 'Catherine Classic' from my game list.
3.  Look at the install button and fume in frustration as clicking on it does NOTHING.

**Comment by Xipher-Zero** [comment]
Attaching steam client system information in case that helps.

[System Information (Steam Sys Info Dump).txt](https://github.com/ValveSoftware/steam-for-linux/files/10145604/System.Information.Steam.Sys.Info.Dump.txt)

**Comment by kisak-valve** [comment]
Hello @Xipher-Zero, this reads like you manually configured the game to use an invalid or removed Proton version.

If you click the ⓘ on the right side of the game, does it show a line like "Runs on this computer via Steam Play. Proton # selected by you for this title"?

Also, if you go to the per-game properties -> Compatibility, is `Force the use of a specific Steam Play compatibility tool` and the dropdown set to a sane value?

**Comment by Xipher-Zero** [comment]
Hello @kisak-valve ,

Wow, great catch. Selecting the ⓘ button did not show a selected version of proton for Catherine, but manually setting a proton version under the compatibility tab and then unchecking the "Force the use of a specific Steam Play compatibility tool" brought the install button back. It is now working as it should!

Thank you!
