### ISSUE TITLE
USB HID devices disconnect on steam startup.

### ISSUE THREAD

**Issue by HFDan** [ValveSoftware/steam-for-linux#8976]
#### System information

* Steam client version (build number or date): `Built: Dec 8 2022, at 03:55:11. Steam package versions: 1670474854. Steam API: v020`
* Distribution: Arch
* Opted into Steam client beta?: Yes (Issue also persists on non-beta version)
* Have you checked for system updates?: Yes

When launching steam, USB HID devices disconnect (either instantly when the steam UI shows up, or with a 10-20 second delay). Sometimes they come back within 30 or so seconds, sometimes they do not, requiring me to unplug them and plug them back in.

Launching steam from the console, i notice a repeated error message `ioctl (GFEATURE): connection timed out`. I do not think these are related to my issue however, as i also see them when running osu!lazer, and the issue does not appear there.

`dmesg`, `journalctl`, xorg logs and steam console output show no useful info and no errors (aside from the aforementioned `ioctl` error).

This happens with:
* My keyboard (Razer Huntsman v1)
* Both of my mice (One whose model i fail to remember and a Razer Balilisk v2)
* All of the controllers i've tried (2 Dualshock 4s, 1 Dualsense, 1 Xbox One controller)

All of the devices listed above are known working. I have tested them on both another arch system (steam not installed) and a *windows* machine (steam installed) and they work just fine.

#### Steps for reproducing this issue:

1. Launch steam.
2. Notice devices from `/dev/input/by-id` disappearing.

**Comment by kisak-valve** [comment]
Hello @HFDan, this reads like a kernel issue with the USB drivers or the specific hardware in your system which should also be mentioned to the relevant Linux kernel dev(s).

**Comment by HFDan** [comment]
I have tried downgrading:
- linux (went all the way back to 5.19, a known good version.)
- linux-firmware
- libusb
- hidapi
- libgusb
- libusb-compat
- libinput
- xf86-input-libinput
- xorg

None of them seem to be the issue.

**Comment by HFDan** [comment]
A janky "fix" to this is to use firejail to blacklist the `/dev/input/by-id/' directory.

**Comment by HFDan** [comment]
This issue seems to be fixed in the latest Steam Beta
