### ISSUE TITLE
Big picture crashes with fatal IO error 11

### ISSUE THREAD

**Issue by lytenyn** [ValveSoftware/steam-for-linux#8977]
#### Your system information

* Steam client version (build number or date): Dec 1 2022 or Dec 8 2022
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] I tested both
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When launching Big Picture mode from sway (hence in Xwayland=, steam crashes immediately or after a while with:

Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

When doing the same from a gamescope session, I get slighly different output from the crash:

xwm: error 2: BadValue (integer parameter out of range for operation) request 137 minor 31 serial 128894
xwm: error 2: BadValue (integer parameter out of range for operation) request 137 minor 31 serial 128897
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
gamescope: /var/tmp/portage/x11-libs/libX11-1.8.2-r1/work/libX11-1.8.2/src/xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Caching cursor image for , serial 1, cache size = 6
GameScope focus changed to appID 751780
SynchronizeClientState(): setting cursor visible
SynchronizeClientState(): setting cursor to 1
ThreadGetProcessExitCode: no such process 186793
CLIENT: Got control packet k_EStreamControlSetCursor
SynchronizeClientState(): setting cursor to 6
CLIENT: Got control packet k_EStreamControlSetCursor
ThreadGetProcessExitCode: no such process 186738
ThreadGetProcessExitCode: no such process 186724
ThreadGetProcessExitCode: no such process 186716
ThreadGetProcessExitCode: no such process 186690
ThreadGetProcessExitCode: no such process 186684
ThreadGetProcessExitCode: no such process 186678
ThreadGetProcessExitCode: no such process 186674
(EE) failed to read Wayland events: Connection reset by peer
zsh: IOT instruction (core dumped)  gamescope -f -e -w 1920 -W 1920 -H 1080 -h 1080 -- steam -tenfoot  -nointro
Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

This has started after a recent steam update. I was on the beta before, so I tried stable, but the result is the same.

#### Steps for reproducing this issue:

1. Launch big picture mode
2. Wait, sometimes a few minutes, often less
3. Steam crashes

Please tell me if any additional input would help

**Comment by lytenyn** [comment]
Still researching, this may be related to https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170 which would indicate it could be a libX11 bug. I'm on libX11-1.8.2.

**Comment by lytenyn** [comment]
OK, so I confirm that downgrading to libX11-1.8.1 solves the issue.

However, if I understand https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/170 and https://github.com/godotengine/godot/issues/69352 correctly, it's not completely clear whether this is a libX11 bug or godot and steam ones, so maybe this should be kept open for the time being?

**Comment by patrick-g-p** [comment]
These issue may be related? https://github.com/ValveSoftware/steam-for-linux/issues/8916

**Comment by Riven-Spell** [comment]
I have the same issue here on Arch Linux, KDE Wayland.

**Comment by Riven-Spell** [comment]
Still reproduces on libx11 1.8.1.

**Comment by kisak-valve** [comment]
Hello @Riven-Spell, just to check, you tested with both 32 bit and 64 bit libx11 downgraded? (`libx11` and `lib32-libx11`)

**Comment by Riven-Spell** [comment]
> Hello @Riven-Spell, just to check, you tested with both 32 bit and 64 bit libx11 downgraded? (`libx11` and `lib32-libx11`)

Guh, should've thought of the multilib packages! It seems to work for this moment (or at least not crash as quickly), but I'll leave it running and see if it crashes.

**Comment by lytenyn** [comment]
After upgrade to libx11-1.8.3-r1, the problem is gone. Not sure whether this includes Gentoo-specific patches relevant to this issue.

**Comment by notpentadactyl** [comment]
Steam Beta crashes with up to date Arch Linux:

```
lib32-libx11 1.8.3-1
libx11 1.8.3-6
```

```
Xlib: sequence lost (0x10000 > 0x2403) in reply type 0xc!
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
steam: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by zimward** [comment]
With the new Big picture mode the problem seems to be gone. I also tried the old Big picture mode which almost immediately crashed with
`Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`
The controller configuration for example still uses old Big picture mode UI which also crashes steam. (but one can configure the controller now through the new Big picture mode UI which i would consider a viable workaround)

Im on up to date Arch linux:
`lib32-libx11 1.8.3-1`
`libx11 1.8.3-6`

**Comment by lytenyn** [comment]
The problem remains gone for me after the upgrade to libx11-1.8.4.
From my point of view, it can be closed.
