### ISSUE TITLE
[Steam Beta] Desktop-mode Library No Longer Loads Library View

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#8979]
#### Your system information

* Steam client version (build number or date): December 10 2022, at 02:13:15 (1670643639)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: RTX 2080 Ti
* GPU Driver: 525.60.11 (Open-GPU Kernel Module)

#### Please describe your issue in as much detail as possible:

The Steam Library page no longer loads anything, effectively breaking Steam for gaming in conjunction with [this other Steam Beta bug](https://github.com/ValveSoftware/steam-for-linux/issues/8916), at least for Nvidia users.

<details><summary>Screenshot:</summary>

![Screenshot_20221210_022615](https://user-images.githubusercontent.com/28468662/206841052-9c99218a-d96f-4cb8-8745-284180a6e39c.png)
</details>

I mean... I know this is the Steam _**Beta**..._ but this is the kind of stuff that made me stop opt-ing into into before in the past...

#### Steps for reproducing this issue:

1. Launch Steam
2. Navigate to "Library"

**Comment by konzty** [comment]
Similar issue here.
**Steam Library stays blank after start of Steam.**
**Opt-out of Steam beta fixes the issue.**

- Steam client beta
- Steam package versions: 1670643639
- Steam installed through distro package repository
- Distro: Linux Mint 21
- Kernel: 5.15.0-56
- Desktop Env: XFCE
- Display Server: X
- GPU: AMD RX 6700 XT
- Driver: mesa 22.0.5-0ubuntu0.1

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, if you completely close Steam, then run `steam-runtime` from a terminal, are there any hints in the terminal spew? Can you attach `steamwebhelper.log` and `cef_log.txt` found in `~/.local/share/Steam/logs` as a file to this issue report?

Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ThisNekoGuy** [comment]
This was fixed in build 1670661475

**Comment by alosarjos** [comment]
@kisak-valve This is happening to me again after today beta update. I don't see anything specific on the logs, and was working fine until just updated
