### ISSUE TITLE
The contents of the SP Controller Configurator and Big Picture windows are not displayed

### ISSUE THREAD

**Issue by Wolfen113** [ValveSoftware/steam-for-linux#8980]
#### Your system information

* Steam client version (build number or date): 1670661475
* Distribution (e.g. Ubuntu): Arch Linux. Kernel: x86_64 Linux 6.0.11-arch1-1
* Opted into Steam client beta?: Tried on both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expected that when opening the Controller Configurator or the Big Picture window, I would see a new interface. But instead it shows me empty windows, with invisible working buttons.

About a month ago, a new Сontroller Сonfigurator appeared in the beta version of Steam. It did not work well, there were graphic artifacts, so I switched to a regular steam where there was still an old Сontroller Сonfigurator.
A couple of weeks ago and in the usual steam it was updated to a new version and now it does not work at all, showing an empty window. Although if you listen to it, invisible buttons are pressed.
And recently, a new big picture was added in the beta version of steam, it is broken with the same problem.

According to my observations from other discussions and statements of my friends, this problem is most often observed in Linux users with a proprietary nvidia driver (I have Nvidia driver 525.60.11). But I can't find a solution to this problem.
I need a controller configurator to set up a steam controller. Since it hasn't been fixed in a month, I'm starting to get worry that this problem will go into regular steam and I will no longer be able to use my gamepad.

#### Steps for reproducing this issue:

1. Connect a controller.
2. Pick a game.
3. Click on the Cog > Manage > Controller Configuration.

Or

1. Switch to Big Picture mode. By clicking on the open button next to the steam user.

![photo_2022-12-10_19-36-36](https://user-images.githubusercontent.com/29464780/206865322-6a6c2ab5-8b2b-4df9-9ecc-c78225bd2e98.jpg)
![photo_2022-12-10_19-36-32](https://user-images.githubusercontent.com/29464780/206865338-e359d684-fbe2-4f65-a418-83d042b52cf7.jpg)

**Comment by kisak-valve** [comment]
Hello @Wolfen113, this issue is already being tracked at #8916 and #8949. Closing as a duplicate.
