### ISSUE TITLE
[Feature Request] [SteamDeck] CPU SMT Toggle

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/steam-for-linux#8981]
It's amazing what sort of difference it can make by simply disabling SMT can make on performance in situations where higher core clock is more important than total thread/core count. Decky Loader can be a bit glitchy and cause issues with the UI becoming unresponsive so I think it just makes sense if such an impactful toggle could make it's way into the official solutions.

Controlling the CPU frequency is extremely helpful as well to really dial in battery life optimizations for your games, the TDP toggle alone is a far cry from what PowerTools is capable of doing.

**Comment by kisak-valve** [comment]
Hello @ruineka, this feature request is already being tracked at https://github.com/ValveSoftware/SteamOS/issues/864. Closing as a duplicate.
