### ISSUE TITLE
Big Picture glitched on beta

### ISSUE THREAD

**Issue by emmandyar** [ValveSoftware/steam-for-linux#8987]
#### Your system information

* Steam client version (build number or date): 1670661475 -  Built Dec 10 at 02:13:15
* Distribution (e.g. Ubuntu):  Kubuntu 22.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes, up-to-date

#### Please describe your issue in as much detail as possible:
Whenever I try to open Big Picture, sound plays, but a glitched window with whatever was behind it at creation time appears. Window seems to work but nothing is displayed. Closing and try opening library from the tray icon reopens it and I have to close steam for it to return to normal

Kubuntu with nvidia 525.60.11

#### Steps for reproducing this issue:

1. Open steam
2. Open big picture

![Screenshot_20221212_151000](https://user-images.githubusercontent.com/23064809/207121858-daa1a5b7-b866-469d-8383-30fb4285ebf2.png)

**Comment by kisak-valve** [comment]
Hello @emmandyar, this issue is already being tracked at #8916. Closing as a duplicate.
