### ISSUE TITLE
#8886 revisited: Non-Steam games do not receive controller input

### ISSUE THREAD

**Issue by slynobody** [ValveSoftware/steam-for-linux#8992]
Issue #8886 is reappearing in the last seven beta client-versions minimum.
Also there are loads of seemingly completly identical controller-layouts to chose from ('steam input')

btw: desktop-mice are invisible / nonexistent too, this seems to be something contributing to the unavailability of mouse-look on controllers when using -gamepadui.

**Comment by kisak-valve** [comment]
The secondary issue is being tracked at #8986.

**Comment by slynobody** [comment]
is there any workaround? patch planned? hint how to deal with it?

**Comment by helliongame** [comment]
I have the same issue...i have a lot of duplicates templates, and is a real hell find the correct template

Any info of how to workaround this?

Greetings

I opened a ticket to steam support to escalate it

**Comment by johndoe1991239** [comment]
Can confirm on the latest beta on Fedora 37. Steam games work properly but non steam games (like Games added through heroic) do not.

**Comment by slynobody** [comment]
while #8986 seems to be fixed now with the last 3 betas, #8886 is still a problem, any news / plans on this? This is highly annoying.

#8886=lost mouse-support on *all* non-steam apps (mouse as well as mouse-look on controllers with steam-input).
