### ISSUE TITLE
The center button of radial menu stops working on Steam Controller when assigned to Touchpads

### ISSUE THREAD

**Issue by ProtonAbyss** [ValveSoftware/steam-for-linux#8994]
#### Your system information

* Steam client version (build number or date): **Dec 1, 2022**
* Distribution (e.g. Ubuntu): **Ubuntu 22.04**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:

The center button of the radial menu becomes unresponsive when assigned to the Steam Controllers touchpads.

If one doesn't assign any other radial menu entries, except for the center button, the center button will lose functionality completely, even if the haptic feedback shows that an event should be happening. However, if you assign another radial menu entry, the center button can be temporarily activated again if one highlights another entry before activating the center button.

#### Steps for reproducing this issue:

1. Map  a touchpad of the steam controller to radial menu inside any game.
2. Assign only the center button to a keyboard key.
3. Repeatedly activate center button and observe results.

**Comment by kisak-valve** [comment]
Hello @ProtonAbyss, you've already reported this issue at #8943. Please do not intentionally open duplicate issue reports.

Closing as a duplicate.

**Comment by ProtonAbyss** [comment]
Apologies. I thought this should be a new issue since my last post was about multiple buttons being assigned to the radial menu and having the wrong menu item being activated. With this issue, I pinpointed a related but different problem, which is the center button itself cannot be reactivated more than once.
