### ISSUE TITLE
Library page is completely empty

### ISSUE THREAD

**Issue by craig-sanders** [ValveSoftware/steam-for-linux#8995]
#### Your system information

* Steam client version (build number or date): Dec 14 2022 at 02:36:48, 1670989818
* Distribution (e.g. Ubuntu): Debian sid
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Kernel 6.0.12
Threadripper 1950X, 64GB RAM.
Nvidia GTX 1060 6GB, driver 515.48.07

#### Please describe your issue in as much detail as possible:

After the latest steam client update (today), the Library page is completely blank, doesn't even display the list of games on the left-hand-side.  It's blank for all items under the Library menu: Home, Collections, and Downloads.

Store, Community, and my profile pages all display without a problem.

#### Steps for reproducing this issue:

1. Start steam
2. 
3.

**Comment by craig-sanders** [comment]
Seems to be fixed in latest update 1671007697, released Dec 14 2022 at 08:27:42

**Comment by kisak-valve** [comment]
Closing per the last comment.
