### ISSUE TITLE
Secondary Steam Library on network share(NFS) disappeared

### ISSUE THREAD

**Issue by megatog615** [ValveSoftware/steam-for-linux#8996]
Steam seems to have dropped my secondary library after a network share was discovered to not be mounted by the system for several days. I discovered this by fixing the problem with the network share, which caused Steam to freeze. I killed Steam with -9 because it was completely unresponsive and now, afterward, Steam seems to have forgotten that secondary library. I also cannot add it back with the new UI.

If the Deck can maintain libraries between sdcards, surely Steam on the desktop can handle when a network library goes down?

I am on the beta update channel.

**Comment by kisak-valve** [comment]
Hello @megatog615, this issue is already being tracked at #8552 and #8989. Closing as a duplicate.
