### ISSUE TITLE
Some native titles do not launch

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/steam-for-linux#8998]
#### Your system information

* Steam client version (build number or date): Dec 14 2022
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Half-Life 2, Starbound, and Stardew Valley will not launch with native default settings as of recently. When switching to Proton, the game successfully launches.

Screen capture of the failure to launch: https://www.youtube.com/watch?v=jCH0h5SVVFw

Terminal output from running Steam, launching Half-Life 2 with Proton, switching to Native, and attempting to run it and then Stardew Valley:

[terminal output](https://gist.github.com/yaomtc/5c05479013179e4879ae137ff035e006)

I have tested a few other Linux native titles, these launch properly: Terraria, Owlboy, Helltaker

System info: https://gist.github.com/yaomtc/d872c96a7255e0504a3397d7d6029ba7

EDIT: Tried both X and Wayland, no change. Tried -windowed, didn't work. Tried following this:

https://wiki.archlinux.org/title/Steam/Troubleshooting#Debugging_shared_libraries

but it wasn't helpful, and I think it's largely out of date.

* I found what should be Linux executables (`/steamapps/common/Starbound/linux/starbound` for example) but none of them work with `ldd`, I just get

        ldd: warning: you do not have execution permission for `./starbound'
        not a dynamic executable

* I'm not using steam-native but that doesn't help anyway
* I tried using `DEBUGGER=gdb steam` but Steam would never successfully launch using that, it would only get partway through the launch process.
* I tried copying libsteam_api.so from the folder for Helltaker (native, works) to the folder for HL2, but that didn't help.

**Comment by kisak-valve** [comment]
Hello @yaomtc, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by yaomtc** [comment]
Done.

**Comment by yaomtc** [comment]
Updated the report with some more things I tried.

**Comment by kisak-valve** [comment]
Out of mild curiosity, what filesystem are you using with `/mnt/WDBlueSSD1/SteamLibrary`? Does your regular system user own this folder and subfolders?

**Comment by yaomtc** [comment]
That one is ext4, and yes.

**Comment by yaomtc** [comment]
I found the issue. My two ext4 drives had `noatime` and `noatime,user` as the mount options in `/etc/fstab`. I added `user` to the options and the issue is gone. I thought `exec` was already one of the defaults but apparently not!

**Comment by yaomtc** [comment]
I found the issue. My two ext4 drives had `noatime` and `noatime,user` as the mount options in `/etc/fstab`. I added `user` to the options and the issue is gone. I thought `exec` was already one of the defaults but apparently not!
