### ISSUE TITLE
Steam status dialogue unresponsive

### ISSUE THREAD

**Issue by anfokaboom** [ValveSoftware/steam-for-linux#8999]
#### Your system information

* Steam client version (build number or date): Dec 1 2022, at 22:40:28
* Distribution (e.g. Ubuntu): ZorinOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Like a lot of people I like to change my Steam status from the Friends dialogue. However, clicking the arrow next to my name produces the dialogue with the statuses, but it becomes non-responsive. From there, I can't use the Friends list except move it around the desktop, all while the status dialogue sits on the desktop without any way to change or close it.

#### Steps for reproducing this issue:

1. Start Steam
2. Open Friends list
3. Click arrow next to Steam name
4. Attempt (but fail) to change status
5. Exit Steam from tray to overcome

**Comment by kodatarule** [comment]
Can confirm that I am also experiencing this on EndeavourOS

**Comment by MatheusKS95** [comment]
This is also happening on Debian 11 (stable)

**Comment by Azer0s** [comment]
Can confirm this is also happening on Pop!_OS 22.04

**Comment by hifi** [comment]
Opting in to Steam client beta fixed similar bug with friends right click context menu that renders joining friend lobbies in some games impossible which don't have an UI for that.

**Comment by anfokaboom** [comment]
Fixed with the latest client update, at least for me. Thank you.
