### ISSUE TITLE
Steam Client and its web-contents capped at 60fps

### ISSUE THREAD

**Issue by xpander69** [ValveSoftware/steam-for-linux#9000]
#### Your system information

* Steam client version (build number or date):  Dec 15 2022 (1671079580)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?:Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam client and it's web-contents seem to be capped at 60 frames per second. Trying to force --disable-frame-rate-limit --disable-gpu-vsync or any other chromium/CEF parameters doesn't seem to do anything.

If ther's some secret parameter to uncap it or cap to 165, please let me know

#### Steps for reproducing this issue:

1. Start steam client
2.  Scroll on store or activity tab and its not high refresh
3.  Or open a website with steam console to see the framerate of the web content (i.e www.vsynctester.com)

**Comment by kisak-valve** [comment]
Hello @xpander69, this issue is already being tracked at #6708. Closing as a duplicate.
