### ISSUE TITLE
Frequent steam crashes 

### ISSUE THREAD

**Issue by rcano** [ValveSoftware/steam-for-linux#9006]
#### Your system information

* Steam client version (build number or date): Dec 15 2022 at 02:03:59
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam simply crashes after being open for a bit, can be a few seconds or some minutes (but less than 60). Launching from console, every time it crashes it seems to be something different, the only consistent bit in the output is:

```
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  46
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  46
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  46
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  152
Value in failed request:  0x0
Serial number of failed request:  46
xerror_handler: X failed, continuing
```
Sometimes it complains about a failed memalloc (despite more than 20GB of ram being available)

Not sure if steam is uploading the crash dumps, but it does print their ID:
`CrashID=bp-50c5266a-3dc8-4edf-9fec-6f4a22221215`

#### Steps for reproducing this issue:

1.  Launch steam
2.  wait a few minutes, could be in a game or not

**Comment by bmjsmith** [comment]
Also experiencing the same symptoms on Ubuntu 22.04, newly since yesterday.  Crashes after maybe 15 seconds every time.  The relevant error for me seems to be:
```
***** OUT OF MEMORY! attempted allocation size: 1630692161 ****
src/tier0/memstd.cpp (3024) : OUT OF MEMORY
src/tier0/memstd.cpp (3024) : OUT OF MEMORY
src/tier0/memstd.cpp (3024) : Fatal assert; application exiting
src/tier0/memstd.cpp (3024) : Fatal assert; application exiting
Installing breakpad exception handler for appid(steam)/version(1669935987)
assert_20221216162322_32.dmp[20966]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221216162322_32.dmp
_ExitOnFatalAssert
assert_20221216162322_32.dmp[20966]: Finished uploading minidump (out-of-process): success = yes
assert_20221216162322_32.dmp[20966]: response: CrashID=bp-b674ec4a-684d-47d3-aa9c-9f8c22221216
assert_20221216162322_32.dmp[20966]: file ''/tmp/dumps/assert_20221216162322_32.dmp'', upload yes: ''CrashID=bp-b674ec4a-684d-47d3-aa9c-9f8c22221216''
```
There's 64GB in this machine and it's doing nothing else at the moment.

**Comment by bmjsmith** [comment]
I ran `~/.local/share/Steam/steam.sh --reset` and it worked for one run, let me open a game.  Then after quitting the game it crashed and we're back to `OUT OF MEMORY`.

**Comment by jtalics** [comment]
~/.local/share/Steam/steam.sh --reset

**Comment by TTimo** [comment]
@rcano 's crash doesn't look like an out of memory (it could be though) - not sure these two reports are the same thing. Does this still happen in current beta (Dec 19th build)?

**Comment by TTimo** [comment]
In any case, please provide a complete steam runtime system information in a gist (Help -> System Information)

**Comment by rcano** [comment]
I've been out of the beta because of how unusable it is. I just switched back to it and it crashed within a minute. [Here's the system information](https://gist.github.com/rcano/6dc80bc139e931c8a257945df6889457)

**Comment by bmjsmith** [comment]
They may be different issues yes, initially I was having the steam client crash within 30 seconds of starting it as per the original report.  

I now only experience this when trying to start some games (Elden Ring for example, it processes shaders then throws OUT OF MEMORY and the whole steam client crashes).  

Here's a [gist of the system info](https://gist.githubusercontent.com/bmjsmith/43eeb4bab3cce816e6bcb36f1b1cbb66/raw/17a7365d4cd768967e4c68e4c45a8ec81311e112/gistfile1.txt).

**Comment by TTimo** [comment]
@bmjsmith - please make a separate report

@rcano:
- Please consider switching over to the official Valve .deb rather than Ubuntu's (https://repo.steampowered.com/steam/)
- Your GL drivers look to be working (32/64 bit) but for an Intel UHD device. You seem to have a discrete NVidia GPU but your drivers aren't configured to use it.
- You have no working Vulkan drivers.

You should fix the above issues and see if problems remain. Please provide an updated crash ID on latest Steam beta client afterwards.

**Comment by rcano** [comment]
> Please consider switching over to the official Valve .deb rather than Ubuntu's (https://repo.steampowered.com/steam/)

hm, maybe. As demonstrated by switching from the beta branch to normal, where the client is redownloaded and it works fine, I don't think this is related with files from the .deb stored in the root partition

> Your GL drivers look to be working (32/64 bit) but for an Intel UHD device. You seem to have a discrete NVidia GPU but your drivers aren't configured to use it.

They are configured just fine, it's the standard optimus setup with nvidia from the `nvidia-settings`, they'll run ogl applications on the intel device unless requested via env parameters. This doesn't affect vulkan applications which do see all the available devices (because this is handled by the vulkan-loader)

> You have no working Vulkan drivers.

I do, and `vulkaninfo` shows this just fine. Steam has no issues running games using vulkan either.

**Comment by TTimo** [comment]
> 
> > You have no working Vulkan drivers.
> 
> I do, and `vulkaninfo` shows this just fine. Steam has no issues running games using vulkan either.
> 

Surprising, your system info reports "cannot-load" "cannot-draw" for all configurations of "x11/vulkan" (LD_* / container, as well as across 32 and 64 bit). Unless I'm reading this wrong but I don't think so.

Can you provide an updated crash ID? The previous one has expired / flushed out of our systems.

**Comment by rcano** [comment]
In theory it finished uploading out of process:
**CrashID=bp-58cd2751-b8c3-4d84-a32b-6706a2221226**
```
Uploaded AppInterfaceStats to Steam
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
crash_20221226220644_34.dmp[847420]: Uploading dump (out-of-process)
/tmp/dumps/crash_20221226220644_34.dmp
/home/user/.steam/steam.sh: line 798: 844820 Aborted                 "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20221226220644_34.dmp[847420]: Finished uploading minidump (out-of-process): success = yes
crash_20221226220644_34.dmp[847420]: response: CrashID=bp-58cd2751-b8c3-4d84-a32b-6706a2221226
crash_20221226220644_34.dmp[847420]: file ''/tmp/dumps/crash_20221226220644_34.dmp'', upload yes: ''CrashID=bp-58cd2751-b8c3-4d84-a32b-6706a2221226''
src/common/pipes.cpp (885) : stalled cross-thread pipe (pipe is disconnected).
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
assert_20221226220648_7.dmp[847461]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221226220648_7.dmp
src/clientdll/steamclient.cpp (858) : bufRet.TellPut() == sizeof(uint8)
src/common/processpipe_posix.cpp (507) : CCrossProcessPipe::BWrite: 32 (Broken pipe)
src/common/pipes.cpp (885) : stalled cross-thread pipe (pipe is disconnected).
src/clientdll/steamclient.cpp (858) : bufRet.TellPut() == sizeof(uint8)
src/common/processpipe_posix.cpp (507) : CCrossProcessPipe::BWrite: 32 (Broken pipe)
src/common/pipes.cpp (885) : stalled cross-thread pipe (pipe is disconnected).
src/clientdll/steamclient.cpp (858) : bufRet.TellPut() == sizeof(uint8)
src/common/processpipe_posix.cpp (507) : CCrossProcessPipe::BWrite: 32 (Broken pipe)

(process:846708): GLib-GObject-CRITICAL **: 22:06:48.463: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
assert_20221226220648_7.dmp[847461]: Finished uploading minidump (out-of-process): success = yes
assert_20221226220648_7.dmp[847461]: response: Discarded=1

**Comment by TTimo** [comment]
@rcano can you test this binary and see if the crash still reproduces: https://www.dropbox.com/s/k3btnf89isxer81/steam-9006.zip?dl=0

To test, replace the steam binary in `~/.steam/steam/ubuntu12_32` with the one from the zip, and run with `-noverifyfiles`.

**Comment by rcano** [comment]
Sorry, I don't see you assigned to the ticket, nor any indication that you work for Valve (I do see  you have committed to this repo), so I'm not inclined to download an arbitrary binary and run it on my machine, I hope you understand.

**Comment by TTimo** [comment]
I do. You can email me at ttimo@valvesoftware.com if that would convince you.

**Comment by rcano** [comment]
Now that I see you can manage this repo I'll trust :). I'll download and report back

**Comment by rcano** [comment]
> To test, replace the steam binary in ~/.steam/steam/ubuntu12_32 with the one from the zip, and run with -noverifyfiles

I do not have the directory `ubuntu12_32` under `.steam/steam` it is present at just `.steam` I assume that's where I should place it

**Comment by rcano** [comment]
Tested by opening and closing games, without this binary it would always instantly crash as soon as I close the first one, this time it resisted 1 game, and crashed shortly after closing the second one:
**CrashID=bp-0416313b-22ed-4ac4-95c8-cc5f22221228**

**Comment by TTimo** [comment]
Thanks - that's just the same crash. Assuming you tested this correctly (did you use `-noverifyfiles`?) then the problem is somewhere else.

I didn't think you needed to start games to reproduce this - from your initial report leaving the steam client idle should be enough? Or do you have to start some games? Which one for instance?

**Comment by rcano** [comment]
> Assuming you tested this correctly (did you use -noverifyfiles?) then the problem is somewhere else.

I did use the parameter, but since the locations you mentioned and the one I ended up using didn't quite add up, I'm not sure.

> I didn't think you needed to start games to reproduce this - from your initial report leaving the steam client idle should be enough? Or do you have to start some games? Which one for instance?

It does crash after idling for a while, I just found that it's much faster to reproduce by opening and game and instantly closing it.

**Comment by TTimo** [comment]
Having another look at the crash dump, you have a lot of threads (> 200) created by your graphics drivers (iris_dri.so). That's not the thread crashing, but this is suspicious.

Please try disabling background shader processing to see if that improves your issue? (Steam -> Settings -> Shader Pre-Caching -> Allow background processing of Vulkan shaders)

**Comment by rcano** [comment]
That setting has been disabled all along, huh.

**Comment by TTimo** [comment]
Please try this fix: https://www.dropbox.com/s/3esi4l29hjyyi75/steam-9006-2.zip?dl=0 (just replace the two files under `ubuntu12_32` and make sure to run with `-noverifyfiles`).

If you get to this by the time another beta has shipped, just test the beta (has this same fix).

**Comment by rcano** [comment]
Sorry it took a couple of days, tried those binaries:

```
[2023-01-05 19:51:50] Startup - Steam Client launched with: '/home/user/.steam/ubuntu12_32/steam' '-nominidumps' '-nobreakpad' '-noverifyfiles'
[2023-01-05 19:51:50] Opted in to client beta 'publicbeta' via beta file
```
Opened and closed several games, played one game for like an hour. No crashes so far, seems stable.

**Comment by TTimo** [comment]
Very nice! So it looks like this is a different set of symptoms for the same root problem as  https://github.com/ValveSoftware/steam-for-linux/issues/8769

I think just depending on hardware/drivers it might manifest differently. An official client update is due to ship shortly.

**Comment by rcano** [comment]
I left steam idle for 3 more hours, no crashes.
