### ISSUE TITLE
when using voice in cstrike, steam-beta-runtime dies

### ISSUE THREAD

**Issue by fred0r** [ValveSoftware/steam-for-linux#9009]
#### Your system information

* Steam client version (build number or date): latest beta running during 20221216
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
when using voice in cstrike, steam dies.
CrashID=bp-d7ff4c66-04ad-4f65-9d15-313c72221216
#### Steps for reproducing this issue:

1.  start beta-steam
2.  start cstrike
3. press configured voice-button in multiplayer
4. cstrike+steam dies

after disabling steam-beta the same operation works fine.

**Comment by kisak-valve** [comment]
Possible duplicate of #8930.

**Comment by fred0r** [comment]
i didnt had any problems before my mentioned beta-update and i install every beta-update.
my prob was introduced by that update and that never happend before.

**Comment by fred0r** [comment]
closing because of https://github.com/ValveSoftware/steam-for-linux/issues/8930
