### ISSUE TITLE
launching dota crashes steam (and dota)

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/steam-for-linux#9016]
hi,

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): [System Information](https://gist.github.com/Turmfalke2/1b609dd742386bbf1819674636c4d621)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

haven't played dota in 2 weeks or so and now whenever I start dota dota and steam crashes shortly after the dota logo during the loading.

In the logs I see some:

> Xlib: sequence lost (0x10000 > 0x8485) in reply type 0xc!

spam, but I am not sure whether that is related.

#### Steps for reproducing this issue:

1. launch dota

@kisak-valve could you please have a look at the dumps and tell me where it is crashing?

[assert_20221218160805_4.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10254080/assert_20221218160805_4.dmp.txt)
[assert_20221218160803_7.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10254081/assert_20221218160803_7.dmp.txt)
[crash_20221218160800_32.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10254082/crash_20221218160800_32.dmp.txt)
[crash_20221218160745_30.dmp.txt](https://github.com/ValveSoftware/Dota-2/files/10254083/crash_20221218160745_30.dmp.txt)

**Comment by kisak-valve** [comment]
For reference, the attached assert minidumps are DUMP_REQUESTED in crashhandler.so. The next crash minidump is a SIGABRT in linuxgate.so coming from libc.so.6 and libopenal.so.1.22.2 (maybe related to #8930 / #9011?) The next crash minidump is a SIGBUS in steamui.so.

If you completely close Steam, then run `steam` from a terminal, are there any hints to ponder in the terminal spew? What version of libX11 are you using? There's recently been some regressions which slipped into libX11 1.8.2 and 1.8.3 and it might be worth testing rebuilding to 1.8.1 to rule that out as a factor if you're using either of those versions.

**Comment by Turmfalke2** [comment]
A LOT of Xlib sequence lost spam and then this follows:

```
Created OPUS PLC voice encoder
warning: The VAD has been replaced by a hack pending a complete rewrite
[ALSOFT] (EE) Could not query RTKit: No such file or directory (2)
[ALSOFT] (EE) Could not query RTKit: No such file or directory (2)
crash_20221218164759_30.dmp[13433]: Uploading dump (out-of-process)
/tmp/dumps/crash_20221218164759_30.dmp
crash_20221218164759_30.dmp[13433]: Finished uploading minidump (out-of-process): success = yes
crash_20221218164759_30.dmp[13433]: response: CrashID=bp-52dde7d7-8c78-4b15-8d5d-80a062221218
crash_20221218164759_30.dmp[13433]: file ''/tmp/dumps/crash_20221218164759_30.dmp'', upload yes: ''CrashID=bp-52dde7d7-8c78-4b15-8d5d-80a062221218''
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
/home/turmfalke/.local/share/Steam/steam.sh: line 798: 12623 Aborted                 (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20221218164803_7.dmp[13446]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221218164803_7.dmp
assert_20221218164803_7.dmp[13446]: Finished uploading minidump (out-of-process): success = yes
assert_20221218164803_7.dmp[13446]: response: Discarded=1
assert_20221218164803_7.dmp[13446]: file ''/tmp/dumps/assert_20221218164803_7.dmp'', upload yes: ''Discarded=1''
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
assert_20221218164804_4.dmp[13452]: Uploading dump (out-of-process)
/tmp/dumps/assert_20221218164804_4.dmp
assert_20221218164804_4.dmp[13452]: Finished uploading minidump (out-of-process): success = yes
assert_20221218164804_4.dmp[13452]: response: Discarded=1
assert_20221218164804_4.dmp[13452]: file ''/tmp/dumps/assert_20221218164804_4.dmp'', upload yes: ''Discarded=1''
pid 13452 != 13451, skipping destruction (fork without exec?)
```

I can't imagine not having rtkit is fatal, but I will try downgrading libX11 from 1.8.3 to 1.8.1

**Comment by Turmfalke2** [comment]
downgrade to 1.8.1 fixed the Xlib sequence lost spam, but didn't fix the crash issue.

I can now see a bit more before the  OPUS PLC line

https://gist.github.com/Turmfalke2/1cc4e485b957c35c0cb7c77d52b5cf55

nothing here strikes me as out of the ordinary.

``` 
Fontconfig warning: "/home/turmfalke/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
``` 
Is something that could be fixed, but again unlikely to be fatal.

**Comment by Turmfalke2** [comment]
no longer an issue.
