### ISSUE TITLE
Remember the selection of unchecked or checked 'Remember Me' during login.

### ISSUE THREAD

**Issue by abhishek-rawal** [ValveSoftware/steam-for-linux#9019]
#### Your system information

* Steam client version (build number or date):  1671236931 (Dec 15, 2022 at 21:27:25)
* Distribution (e.g. Ubuntu): ArchLinux & Fedora.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Everytime steam is started, i have to uncheck 'remember me' before login, because i don't want steam to auto-login.
This is RFE to remember the previous selection (checked or unchecked) during next login.

#### Steps for reproducing this issue:

1. Uncheck 'Remember Me' during login.
2. Exit steam and start again.
3. You have to uncheck 'Remember me' again. (RFE to avoid this step)

**Comment by kisak-valve** [comment]
Hello @abhishek-rawal, this issue is already being tracked at #8771. Closing as a duplicate.
