### ISSUE TITLE
System Information does not properly detect the type of storage device

### ISSUE THREAD

**Issue by xrogaan** [ValveSoftware/steam-for-linux#9021]
#### Your system information

* Steam client version (build number or date): Dec 15 2022
* Distribution (e.g. Ubuntu): Devuan GNU/Linux 4 (chimaera) (64 bit)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The system information window tells me that I have 6 SSD. However I have only 3 (2 M.2 and 1 SATA), the other 3 devices are standard mechanical hard drives. 

```
Storage:
    Number of SSDs: 6
    SSD sizes: 2000G,1000G,1000G,500G,250G,120G
    Number of HDDs: 0
```

Output of `lsblk -o KNAME,TYPE,SIZE,MODEL`:

```
KNAME     TYPE   SIZE MODEL
sda       disk 111.8G Samsung_SSD_840_EVO_120GB
sda1      part 111.8G 
sdb       disk   1.8T WDC_WD20EZRX-00DC0B0
sdb1      part   1.8T 
sdc       disk 931.5G SAMSUNG_HD103SJ
sdc1      part 931.5G 
sdd       disk 232.9G MAXTOR_STM3250310AS
sdd1      part    52G 
sdd2      part     5G 
sdd3      part 175.8G 
nvme0n1   disk 465.8G WD_BLACK SN770 500GB
nvme0n1p1 part   512M 
nvme0n1p2 part  93.1G 
nvme0n1p3 part 372.1G 
nvme1n1   disk 931.5G Samsung SSD 980 1TB
nvme1n1p1 part 931.5G 
```

**Comment by kisak-valve** [comment]
Hello @xrogaan, this issue is already being tracked at #8966. Closing as a duplicate.
