### ISSUE TITLE
Two controller support on "A way out" game

### ISSUE THREAD

**Issue by andirsun** [ValveSoftware/steam-for-linux#9027]
#### Your system information

* Steam client version (build number or date): Latest beta Dec 2022
* Distribution (e.g. Ubuntu): Pop_os
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Hi, the game is running great on my linux machine (pop_os) but the problem is with the controllers.
I want to play cooperative (split screen) and I have two controllers connected to my pc (play station dualsense and Xbox one controller).
When I start the game with two controllers connected and I want to choose the characters, only one controller is detected and the other is not recognized.
I have been trying some tweaks: disable steam input, active support for playstation and xbox controllers on big-picture etc.
I really want to know if I can plan with two controllers. 
#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by mbtns** [comment]
Hi, 

Had a lot of issues with this game, but not with the controllers. 

- Are you playing wired or wireless? I find that in general, playing wired works a lot better
- I play it with 2 xbox one controllers connected with the play-and-charge cable) on Fedora without issues.

Best of luck.

**Comment by kisak-valve** [comment]
Hello @andirsun, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4021#issuecomment-1362843378.

**Comment by andirsun** [comment]
> Hi,
> 
> Had a lot of issues with this game, but not with the controllers.
> 
>     * Are you playing wired or wireless? I find that in general, playing wired works a lot better
> 
>     * I play it with 2 xbox one controllers connected with the play-and-charge cable) on Fedora without issues.
> 
> 
> Best of luck.

I have a dualsense and Xbox one controller, both wired connected.
I am going to take a photo and show it t o you @mbtns thanks !

**Comment by mbtns** [comment]
I also noticed that from this week onward, the beta update - which has the steamdeck style big picture - broke a lot of my games and was very unstable: client crashed after game exit of launching the horrible origin launcher. A way out did not work anymore.

Opting out of beta solved that issue for me (since it did not launch a way out anymore in beta). 

Another thing you can try is switching between proton versions (GE or standard ones), as in some other games, newer versions broke controller support for me as well in the past.
