### ISSUE TITLE
AC Valhalla: remote play button doesn't show on Steam Deck after switching to beta client on the linux host

### ISSUE THREAD

**Issue by sim590** [ValveSoftware/steam-for-linux#9034]
#### Your system information

* Steam client version (build number or date): Dec 15 2022, 21:27:25
* Distribution (e.g. Ubuntu): Archlinux, Sway (wayland)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Normally, when trying to stream a game from my linux host to my Steam Deck, I use the drop down menu on the game's page to select my host name and then I can hit the "Stream" button.

![image](https://user-images.githubusercontent.com/4147254/209471113-7db44ad1-a093-46a9-827e-15ff9657337d.png)

I was able to do just that with the game Assassin's Creed Valhalla. Here a snippet of log that I took from `streaming_log.txt` on my linux host machine which shows that it worked:

<details>

```
{
	"GameNameID"		"Assassin's Creed Valhalla"
	"appid"		"2208920"
	"TimeSubmitted"		"1671960209"
	"ResolutionX"		"1920"
	"ResolutionY"		"1080"
	"CaptureDescriptionID"		"Desktop OpenGL NV12 + libx264 main (4 threads)"
	"DecoderDescriptionID"		"VAAPI tiled hardware decoding"
	"BandwidthLimit"		"15000"
	"FramerateLimit"		"0"
	"Transport"		"4"
	"SlowGamePercent"		"0"
	"SlowCapturePercent"		"0"
	"SlowConvertPercent"		"0"
	"SlowEncodePercent"		"0"
	"SlowNetworkPercent"		"0"
	"SlowDecodePercent"		"0"
	"SlowDisplayPercent"		"0"
	"AvgClientBitrate"		"188.337066650390625"
	"StdDevClientBitrate"		"6.80632209777832031"
	"AvgServerBitrate"		"1143.3026123046875"
	"StdDevServerBitrate"		"0"
	"AvgLinkBandwidth"		"100000.0078125"
	"AvgPingMS"		"1.34277331829071045"
	"StdDevPingMS"		"0.0916737690567970276"
	"AvgCaptureMS"		"16.7724151611328125"
	"StdDevCaptureMS"		"4.28512334823608398"
	"AvgConvertMS"		"0.00440106727182865143"
	"StdDevConvertMS"		"0.0069156973622739315"
	"AvgEncodeMS"		"2.55335664749145508"
	"StdDevEncodeMS"		"0.24547092616558075"
	"AvgNetworkMS"		"1.66352415084838867"
	"StdDevNetworkMS"		"1.22251772880554199"
	"AvgDecodeMS"		"0.340094447135925293"
	"StdDevDecodeMS"		"0.0589310862123966217"
	"AvgDisplayMS"		"0.115278370678424835"
	"StdDevDisplayMS"		"0.0323369242250919342"
	"AvgFrameMS"		"23.9574203491210938"
	"StdDevFrameMS"		"4.56701469421386719"
	"AvgFPS"		"55.1371307373046875"
	"StdDevFPS"		"10.606135368347168"
	"BigPicture"		"0"
	"KeyboardMouseInput"		"0"
	"SteamControllerInput"		"1"
	"TouchControllerInput"		"0"
	"GameControllerInput"		"1"
	"XBox360ControllerInput"		"0"
	"XBoxOneControllerInput"		"1"
	"PS3ControllerInput"		"0"
	"PS4ControllerInput"		"0"
	"PS5ControllerInput"		"0"
	"OtherControllerInput"		"0"
	"GameControllerVID"		"1118"
	"GameControllerPID"		"736"
	"WasSpectating"		"0"
	"RemotePlayTogether"		"0"
}
```

</details>

But I had this issue with the audio crackling [which I heard was fixed on the beta client][betafix], so I decided to try it out and then I wasn't able to stream the game anymore, i.e. that the button on my Steam Deck only showed the "Install" option for the game and I could not select any host to stream from. I tried to go back out of the beta, but that didn't fix it. I still can't stream the game.

However, I clearly can stream any other game that is installed on my linux host. It's only AC Valhalla that just doesn't want to stream anymore. For instance, I can stream AC Odyssey without issue.

I tried reinstalling the game, restarting both the Steam deck and my linux host, upgrading packages on my linux host, reinstalling the game on the host. Nothing fixed it.

I would expect to either be able to stream all my games or none of them. I find weird that AC Valhlalla stopped working.

[betafix]: https://www.gamingonlinux.com/2022/12/valve-has-finally-fixed-the-steam-remote-play-audio-loss-bug-on-linux/

#### Steps for reproducing this issue:

I don't have anyway to workaround, so I'm not sure how to reproduce the issue. I guess:

1. Switch to beta client on an Archlinux host
2. Try to stream to the Steam Deck from the Archlinux host the game Assassin's Creed Valhalla
3. See that it doesn't give the option.

But as I said, I'm not sure that this is sufficient.

**Comment by kisak-valve** [comment]
Hello @sim590, can you check if this is the same issue as #8158?

**Comment by sim590** [comment]
@kisak-valve . I didn't think so at first glance (I saw the post), but I read further and I tried the steps to make the button reappear, i.e. disabling the compatibility option and enabling it again, and it in fact made the button come back, so I think that you are right. This is the same issue. I'll close this one. Thanks!

**Comment by sim590** [comment]
Well, it happened to me again today and the fix I tried above doesn't work anymore. No matter how many time I do it. And again, only AC Valhalla is affected for some reason.
