### ISSUE TITLE
Steam Web Browser did't works after the last update

### ISSUE THREAD

**Issue by Zenitur** [ValveSoftware/steam-for-linux#9037]
* Steam client version (build number or date): Dec 15 2022 21:27:25
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
The Steam application tried to start steamwebhelper a lot of time but it fails without an error.
I'd record the video (45 sec and 5 Mb) available there: https://0x0.st/o5Di.webm

Also I see a lot of messages like this:
```
_xgeWireToEvent: Unknown extension 148, this should never happen.
```
Previously that was one or two times but now it's 5000 times.

#### Steps for reproducing this issue:

1. Start Steam
2. Steam browser didn't works

**Comment by Zenitur** [comment]
My Glibc is 2.17. Is that a reason?

**Comment by kisak-valve** [comment]
Hello @Zenitur, yes, that is a key missing detail and https://github.com/ValveSoftware/steam-for-linux/issues/8491#issuecomment-1075315910 is relevant here.

**Comment by kisak-valve** [comment]
It looks like that makes your system a Debian Wheezy install? That distro release reached its end of life in 2018. Sorry, but we can't support that.

Closing as won't fix.

**Comment by Zenitur** [comment]
This is SteamOS 1.x. Why don't you just rebuild `steamwebhelper` (`steam-runtime-heavy`) with Glibc 2.17 like in a previous build? Why Glibc 2.19, is that really needed?
