### ISSUE TITLE
Can't install steam on debian bookworm/testing

### ISSUE THREAD

**Issue by koreanfan** [ValveSoftware/steam-for-linux#9039]
#### Your system information

* Steam client version (build number or date): steam/testing 1:1.0.0.75-1 i386
* Distribution (e.g. Ubuntu): debian bookworm/testing
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) 
1.sudo apt update
2. sudo apt install steam
output:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libllvm15:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

#### Steps for reproducing this issue:

1. sudo apt update
2. sudo apt install steam
4.

**Comment by kisak-valve** [comment]
Hello @koreanfan, Debian's multiarch implementation requires that arch variants of a package have exactly the same version if you want to install them together. Looking at https://packages.debian.org/bookworm/libllvm15, the majority of Debian's built packages are `1:15.0.6-3` except for i386, which is `1:15.0.6-3+b1`. This is not a steam client issue and must be resolved by your package maintainer(s) for llvm. Report it to your distro.
