### ISSUE TITLE
Steam starts the game it was initially launched with after a restart

### ISSUE THREAD

**Issue by jedenastka** [ValveSoftware/steam-for-linux#9040]
#### Your system information

* Steam client version (build number or date): Dec 15 2022, at 21:27:25
* Distribution (e.g. Ubuntu): Debian Unstable
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

If Steam is initially started by launching a game (with a `steam://rungameid` argument), the game will be launched every time the client restarts.

Example scenario (happens a lot): you start Steam by running the game X, then play games Y and Z, and finally leave it running in the background while you work. It shows you a update popup and you accept it - your work is suddenly interrupted by the game X starting up again. It's not the end of the world, but it is annoying.

#### Steps for reproducing this issue:

1. Ensure Steam isn't open.
2. Launch a game from a launcher created by Steam (Right click the game in Library -> Manage -> Add desktop shortcut) or manually:
```
steam steam://rungameid/<game ID here>
```
4. Close the game (but leave Steam open).
5. Do something that requires a restart - for example, change the language (Steam -> Settings -> Interface).
6. Observe the game start up again.

**Comment by kisak-valve** [comment]
Hello @jedenastka, this issue is already being tracked at #1414. Closing as a duplicate.
