### ISSUE TITLE
Installed Games Use a Blurry Icon

### ISSUE THREAD

**Issue by Tower-Yikk** [ValveSoftware/steam-for-linux#9044]
#### Your system information
Philips 276E (a 4k monitor)
i5-10600k
Gigibyte RTX 2070 Mini ITX

* Steam client version (build number or date): 
   Current one as of writing this post (idk where to look)
* Distribution (e.g. Ubuntu): 
   Ubuntu 22.10
* Opted into Steam client beta?: [Yes/No]
   No
* Have you checked for system updates?: [Yes/No]
   Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Any games I install through steam and check the "Create a system application icon" will use a low resolution icon and scale it up, creating a blurry and messy icon. I know this issue is persistent in windows as well. Is there a way to view the game's icons and manually install a higher resolution icon? Any help would be greatly appreciated.

#### Steps for reproducing this issue:

1. Install Steam
2. Log in
3. Download any game
4. Check the "Create a system application icon" option
5. Wait for game to finish downloading
6. Icon in system menu comes out blurry

![image](https://user-images.githubusercontent.com/86422949/209882702-c0722718-1117-4839-9c8f-610d58728bda.png)

**Comment by kisak-valve** [comment]
Hello @Tower-Yikk, this issue is already being tracked at #2130. Closing as a duplicate.

**Comment by Tower-Yikk** [comment]
Are there any updates to the issue though? It has been nearly 10 years since that issue was made? I honestly don't mind having to through each .desktop file and manually replacing the icon, but I don't know where in the game files I can find those higher resolution icons and googling the icon doesn't always get the correct icon.

**Comment by ghyujkilop** [comment]
> Hello [@Tower-Yikk](https://github.com/Tower-Yikk), this issue is already being tracked at [#2130](https://github.com/ValveSoftware/steam-for-linux/issues/2130). Closing as a duplicate.

Can we have this resolved please? It's annoying and ugly with such pixelated icons. Or at least make it possible to replace icons. If you want free game examples to test this issue on download Minion Masters or VR Chat and you'll see.
