### ISSUE TITLE
[FeatureRequest][Desktop][SteamDeck] Separate game settings per Steam device

### ISSUE THREAD

**Issue by DistantThunder** [ValveSoftware/steam-for-linux#9045]
Hi,
Nowadays, there seems to exist for each application a file listing the location of user data. That location is what is backed up by Steam framework when cloud sync is activated. Or at least so it looks.

With the launch/advent of the SteamDeck, we now have a portable platform which specifications tend to be significantly lower than other gaming systems where Steam is traditionally installed. This usually means that when playing the same game across multiple different systems, one has to fiddle with the game's settings to make them appropriate for the current running platform.

This request is in fact wider in scope than just the Linux Client since I believe it'll require change in the common framework used by all Steam clients.

I would like Steam to have an additional level of granularity and an additional Cloud sync tier for game settings specifically.
For games that would support it, it should be possible to selectively decide to sync the game's settings, independently from the actual progress save data.

Thank you and have nice holidays.

**Comment by kisak-valve** [comment]
Hello @DistantThunder, this is entirely up to the game developers choices of where they chose to store game engine settings versus save files and other config data. They should already have what they need to exclude device-specific game settings from Steam's cloud sync if they want. There's no real guidelines on how this gets stored in the filesystem tree and any implementation of this would either be an unenforced suggestion which would lack adoption or an ever growing pile of application specific hacks.

Sorry, but this is a bit too far of a stretch to request here as a linux-specific feature request. You could try posting this to https://steamcommunity.com/discussions/forum/10/.

**Comment by DistantThunder** [comment]
Thanks for clarifying. It would seem on Steam / Valve side everything is indeed set and ready to be used.
