### ISSUE TITLE
Steam UI input lags on Ubuntu 22.04 

### ISSUE THREAD

**Issue by emmecii** [ValveSoftware/steam-for-linux#9053]
#### Your system information

* Steam client version (build number or date): 1671236931
* Distribution (e.g. Ubuntu): Ubuntu 22.04.1, using Wayland
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam client UI performance at whole (Library, Store, Community, etc.) is degraded with lag on clicking item with mouse or navigate through pages inside the client, output on terminal doesn't indicate anything of abnormal

I remove and reinstalled the client to avoid misconfigurations caused by the upgrade of Ubuntu from 20.04 to 22.04, but the issue persist.

**Comment by kisak-valve** [comment]
Hello @emmecii, this issue is already being tracked at #6500. Closing as a duplicate.
