### ISSUE TITLE
Battlefield 3 - BF3 - Not Working Steam Deck

### ISSUE THREAD

**Issue by NoelCosta** [ValveSoftware/steam-for-linux#9055]
#### Your system information

* Steam client version (Steam Deck - 3.4.4): 
* Distribution (e.g. Steam OS - Stable): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Issue 1:
I cannot open the campaign from the normal gaming mode without an internet connection. When I launch it from desktop mode I need an internet connection. I also had to download an addon to make the browser think I was launching from a windows device.

Issue 2:
Then when I go into the campaign some actions require the default keyboard buttons, and cannot be done with a controller. I think the default controls need to be changed to keyboard and mouse.

#### Steps for reproducing this issue:

1. Press on play
![321783170_3426633367608551_8284331246081573205_n](https://user-images.githubusercontent.com/93773103/210150449-fb085a6a-0c2b-4120-bafd-7ba8fae7ece3.jpg)
![322924180_682799680296652_1919551250805910424_n](https://user-images.githubusercontent.com/93773103/210150451-4178628a-c582-48ec-bf46-7274b57a524f.jpg)

**Comment by kisak-valve** [comment]
Hello @NoelCosta, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3972#issuecomment-1368252181.
