### ISSUE TITLE
age of empire 2 costum games map selection bug

### ISSUE THREAD

**Issue by fakestory** [ValveSoftware/steam-for-linux#9056]
#### Your system information

* Steam client version (build number or date): 15 dec 2022
* Distribution (e.g. Ubuntu): Garuda (arch)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In age of empire 2 DE when you enter the menu for the personalized game the game freezes for several minutes when you click on ''location'' to change the map (sorry my game is in french) only the pointer of the mouse can be moved in this state none of the buttons react
![image](https://user-images.githubusercontent.com/120610914/210154815-06abbb68-adc1-417c-923f-08c608ee0d8c.png)

this bug apply with all different version of proton so far , proton 7 , 6.3-8, proton ge 7.41 , 
i did not had this bug before the steam update.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. lunch steam ( both native or runtime)
2. lunch age of empire 2 definitive edition 
3. click on single player then skirmish 
4. wait the abnormal and long black screen durant loading ( this might be a relatyed issue)
5. clique on the red button on the right to select a map like on the picture.

workaround 

1.lunch bottle ( caffe runner)
2. install steam via bottle script
3. select steam games location
4. lunch aoe2 DE and there no  bug when the game is lunched this way

**Comment by kisak-valve** [comment]
Hello @fakestory, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-1368277077.
