### ISSUE TITLE
Steam Replays save image button opens wrong dialog   

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [ValveSoftware/steam-for-linux#9057]
#### Your system information

* Steam client version (build number or date):  Dec 19 2022, at 22:01:34
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta: Yes
* Have you checked for system updates: Yes

#### Please describe your issue in as much detail as possible:
The "Save Image"-button inside the "Steam Replay 2022" share-dialog opens an open-file-dialog instead a save-file-dialog. Workaround to save your "Steam Replay" is to create 3 empty png-files and select them in the "Save Image" open-file-dialog.

#### Steps for reproducing this issue:

1. Opened the "Steam Replay 2022" page via the prominent link on the mainpage 
2. Clicked on the "Share" button
3. Clicked on th "Save Image" button

**Comment by kisak-valve** [comment]
Most likely a duplicate of #6698.

**Comment by JackLeEmmerdeur** [comment]
Yes you are correct. 
It's pretty much the same problem.
I haven't found that issue in my search beforehand.
