### ISSUE TITLE
Games on Proton open then close

### ISSUE THREAD

**Issue by IM-studios** [ValveSoftware/steam-for-linux#9062]
#### Your system information

* Steam client version (1.0.0.75): 
* Distribution (Ubuntu): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Games (specifically Microsoft Flight Simulator) start normally, open a window, then close almost instantly.

#### Steps for reproducing this issue:

1. Install Microsoft Flight Simulator
2. Use Proton Experimental (or almost any other version)
3. Run the game
[steam-1250410.log](https://github.com/ValveSoftware/steam-for-linux/files/10332198/steam-1250410.log)
[steam-1250410 .txt](https://github.com/ValveSoftware/steam-for-linux/files/10332199/steam-1250410.txt)

**Comment by kisak-valve** [comment]
Hello @IM-studios, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4134#issuecomment-1369012044.
