### ISSUE TITLE
[Left 4 Dead 2] Speaker configuration reverts to 5.1 Speakers

### ISSUE THREAD

**Issue by gamingmsi** [ValveSoftware/steam-for-linux#9064]
#### Your system information

* Steam client version: **Dec 15 2022, at 21:27:25**
* Steam package versions: **1671236931**
* Distribution: **Linux Mint 21.1 "Vera"**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
I've set the Speaker configuration settings to "**2 Speakers**" but when I exit the game and play it again it reverts back to "**5.1 Speakers**" and I have to redo my steps each time I enter the game because it doesn't save my settings and the sound is obviously low with the wrong speakers set by default. I've enabled Steam Cloud and did the steps again but even the cloud doesn't save the speaker configuration. It's very annoying that I have to constantly reconfigure it every time I play the game.

#### Steps for reproducing this issue:

1. Set the Speaker Configuration to "**2 Speakers**"
2. Exit the game
3. Play the game

Here is the image of the persistently wrong Speaker configuration in case you need it.

![20230103152111_1](https://user-images.githubusercontent.com/20128417/210375776-1707a568-ca83-45c9-8f82-0627b20af038.jpg)

**Comment by kisak-valve** [comment]
Hello @gamingmsi, this issue is already being tracked at https://github.com/ValveSoftware/Source-1-Games/issues/2000. Closing as a duplicate.
