### ISSUE TITLE
"Allow background processing of Vulkan shaders" in combination with nouveau drivers cause massive memory usage leading to OOM

### ISSUE THREAD

**Issue by TheSiman** [ValveSoftware/steam-for-linux#9065]
#### Your system information

* Steam client version (build number or date): Dec 15 2022, at 21:27:25
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Whenever I have nouveau drivers loaded and run steam, the "fossilize_replay" process fills memory at roughly 5GB/s (with swap it varies) until it fills memory+swap (which total 60GB on my system) and triggers systemd-oomd, "fossilize_replay" gets killed, created again by steam and the process repeats. This issue doesn't occur with the proprietary nvidia driver.
Disabling "background processing of vulkan shaders" mitigates the issue.

Technical details:
Kernel: Linux 6.0.15 (but I have the same symptoms on 6.2-rc1 mainline)
DE: KDE Plasma 5.26.4
WM: KWin (X11)
GPU: 2080 Super
nouveau driver: 1.0.17
nvidia driver: 525.60.11
Steam was installed from rpmfusion repository
#### Steps for reproducing this issue:

1. Have nouveau drivers active (Fedora and other distros default to this)
2. Install a game that uses proton and background processing of vulkan shaders
3. Run steam

**Comment by kisak-valve** [comment]
Hello @TheSiman, your issue is with the memory usage of lavapipe in combination with fossilize_replay and has nothing to do with nouveau beyond the fact that nouveau is not a Vulkan implementation. This is the same issue as https://github.com/ValveSoftware/Fossilize/issues/205 (and https://github.com/ValveSoftware/Fossilize/issues/200). Closing in favor of the older issue report.

**Comment by DachyVashakmadze** [comment]
I have same problem,  Dota 2 is freezing my system, while it is processing Vulkan .... other games are fine. I have ok system R9 5900HX + RX 6800m +16 ram, not perfect but plenty for Dota 2. Distro: fedora 37/nobara 37/gnom. I was skipping Vulkan every time, today game started crashing, i got ban :(, i just found this spot. do we have any other source to seek solution ?
