### ISSUE TITLE
Ubuntu 22.04 - Steam crashes on launch

### ISSUE THREAD

**Issue by Aerodin** [ValveSoftware/steam-for-linux#9067]
#### Your system information

* Steam client version (build number or date): Latest version (I think 6530)
* Distribution (e.g. Ubuntu): Ubuntu 22.04 64-bit
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes all current.

#### Please describe your issue in as much detail as possible:
Started up my PC.  Tried to launch Steam - normally it launches.  
Instead my monitors flash off and on and I get sent to the login screen.

All other apps etc. work as normal.  No changes since yesterday when it was working and today when it wasn't.

#### Steps for reproducing this issue:

1.  Launch steam
2.  Observe crash.  
3. See screenshot - taken with my phone since it crashes after this point.
https://imgur.com/a/iDjLrvB

**Comment by kisak-valve** [comment]
Hello @Aerodin, in general, no OpenGL application including Steam should be capable of taking down the system, and this reads like a video driver issue.

**Comment by echaskaris** [comment]
Fwiw I have a fairly fresh installation of 22.04 and it works fine. I use the Beta branch and I have an AMD GPU.

**Comment by kisak-valve** [comment]
Glad to hear that it started working. Closing per the last comment.
