### ISSUE TITLE
(214510) LEGO The Lord of the Rings does not start

### ISSUE THREAD

**Issue by thackel** [ValveSoftware/steam-for-linux#9070]
#### Your system information

* Steam client version (build number or date): 
Latest beta
* Distribution (e.g. Ubuntu): 
Arch
* Opted into Steam client beta?: [Yes/No]
Yes
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:

When starting the game the screen goes black and shows a copyright notice. After about 3s it crashes back to desktop.

The last relevant message shown is:
`Internal error (please report) ./dlls/d3dcompiler_43/ppy.y 369: Invalid type indicator (0x0001)`

The system is using an Intel on board graphics card.

I tried proton 7.0.5, experimental and 6.x.

I've attached to proton logfiles of the runs with 7.0.5 and experimental:
[steam-214510-proton-experimental.log](https://github.com/ValveSoftware/steam-for-linux/files/10352936/steam-214510-proton-experimental.log)
[steam-214510-proton-705.log](https://github.com/ValveSoftware/steam-for-linux/files/10352938/steam-214510-proton-705.log)

**Comment by kisak-valve** [comment]
Hello @thackel, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1836#issuecomment-1372346122.
