### ISSUE TITLE
Hardware survey seems to error out

### ISSUE THREAD

**Issue by neonmoe** [ValveSoftware/steam-for-linux#9073]
#### Your system information

* Steam client version (build number or date): Jan 5 2023, at 19:23:52
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I didn't expect anything to happen, but presumably something triggered the Steam client to show me the hardware survey window, as this suddenly appeared while I just had the Library view open.

![Screenshot with two errors, cannot read property 'HardwareSurvey' of null and SteamClient.User.RegisterForHardwareSurvey is not a function.](https://user-images.githubusercontent.com/22432472/211064399-6f392991-6df1-4722-bbcd-7fc00e34cedf.png)

#### Steps for reproducing this issue:

1. Open the Steam client.
2. Open the Library window.
3. Wait for a bit.

I probably have some flag set on my client now to do the hardware survey, since this keeps happening over restarts.

**Comment by nlborlcl** [comment]
![20230107_033101](https://user-images.githubusercontent.com/57191258/211141617-6271a64a-6d46-4342-adf2-72a1b7a6fb16.jpg)
Similar, but a lengthier output. Manjaro, up to date. Kernel 6.1.1-1. Kde plasma 5.26.4. In steam client beta jan 5th.

**Comment by nlborlcl** [comment]
oh, on Wayland.

**Comment by Tourfaint** [comment]
I have the same issue

    Steam client version (build number or date): Jan 5 2023, at 19:23:52
    Distribution (e.g. Ubuntu): Ubuntu
    Opted into Steam client beta?: [Yes/No] Yes
    Have you checked for system updates?: [Yes/No] Yes
    
Exact same error message as the OP.

**Comment by atomsymbol** [comment]
#### Your system information
* Steam client version (build number or date): 2023-Jan-05 19:23:52
* Distribution: Gentoo Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

![desktop 2023-01-08 07:30:36+01:00](https://user-images.githubusercontent.com/22368256/211183714-0b579c9e-ba64-402e-aefe-0272e0027358.png)

**Comment by Fussmatte** [comment]
Steam client version: built Jan 13 2022 at 00:55:04
Distro: Pop!_OS 22.04 LTS, 64-bit
Opted into Steam client beta: Yes
Checked for client updates: Yes

I seem to have a similar issue here, although the error is a bit different, and shorter. The app asks me about the survey, and every time I click "Yes" the below error appears. Whether or not I click yes or no, the same survey pop up appears very shortly after closing the pop-up. Restarting the app only prolonged its reappearance, and I can't get rid of it for good.

![image](https://user-images.githubusercontent.com/44736084/212573486-8db91163-9c82-4b98-8058-140791542e7d.png)

**Comment by nlborlcl** [comment]
I got a regular-looking survey in the last few hours. Hurrah.

**Comment by kisak-valve** [comment]
Closing per the last comment.
