### ISSUE TITLE
Steam Client hang on Nvidia KDE Plasma WAYLAND

### ISSUE THREAD

**Issue by kodatarule** [ValveSoftware/steam-for-linux#9075]
#### Your system information
Operating System: EndeavourOS
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.2-273-tkg-pds (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2

* Steam client version (build number or date): latest beta 06.01.2023
* Distribution (e.g. Ubuntu):  EndeavourOS
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
To provide as much details as possible, whenever a notification is triggered(usually bottom right) it would make the client itself to hang(unresponsive completely frozen, clicking anywhere nothing happens). This issue is observed specifically on KDE Plasma under WAYLAND(as it is not present on Gnome Wayland) and NVIDIA gpu, it started since Plasma 5.25(5.24.6 didn't have this issue) and it is still present on Plasma 5.26.5. 
I did open a bug report which indicated that it is either an Nvidia driver issue or that steam github could help out on this.
Original bug report: https://bugs.kde.org/show_bug.cgi?id=462027
Nvidia forums bug report: https://forums.developer.nvidia.com/t/steam-notification-causes-the-client-to-freeze-hang-completely-kde-wayland/236138

Ways to workaround this is to disable notifications or to use big picture(new gamepadui)

#### Steps for reproducing this issue:

1.  Simple notification to show up while the client is running

```Note: it is interesting that while I see the client being frozen in terminal it doesn't indicate any problems or that something went wrong```

**Comment by kisak-valve** [comment]
Hello @kodatarule, this issue is already being tracked at #8696. Since you've added a fair bit of detail that might be interesting to ponder, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/8693#issuecomment-1374172426.

Closing in favor of the older issue report.
