### ISSUE TITLE
Application may not be hardware accelerated on AMD RX 7900 XTX

### ISSUE THREAD

**Issue by danielgarciagarcia** [ValveSoftware/steam-for-linux#9077]
#### Your system information

* Steam client version (build number or date): Built Dec. 15 2022, at 21:27:15
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam logs show that the bundled LLVM version of the runtime is unable to recognize the recently released AMD RX 7900 XTX GPU as a target.

```
Installing breakpad exception handler for appid(steam)/version(1671236931)
'gfx1100' is not a recognized processor for this target (ignoring processor)
'gfx1100' is not a recognized processor for this target (ignoring processor)
amd: LLVM doesn't support gfx1100, bailing out...
libGL error: glx: failed to create dri3 screen
```

I can confirm that this also happens for any application that run on a setup where one of the following conditions is not true:
- Mesa is version 22.2.0+
- LLVM version 15.0+
- Mesa built against that version of LLVM

This may be preventing Steam application to be hardware accelerated, as the runtime cannot use the GPU properly. This can also be seen while monitoring the CPU usage. When Steam starts the CPU usage goes crazy high and keeps to that level.

I don't know if games are affected.

#### Steps for reproducing this issue:

1. Have an AMD RX 7900 XTX
2. Start Steam from the terminal
3. Check the logging
4. Check how the CPU usage is very high while using Steam

**Comment by danielgarciagarcia** [comment]
Accidentally published the same issue twice. #9078 is the correct one.

**Comment by kisak-valve** [comment]
Hello @danielgarciagarcia, the older issue report takes priority.

**Comment by danielgarciagarcia** [comment]
@kisak-valve No problem, thanks for reopening and sorry for the confusion!

**Comment by kisak-valve** [comment]
Looking this over, it looks like an system packaging issue, not a Steam client issue. The video driver from the host system takes priority over any part of the LD_* Steam runtime and that includes using the system install of llvm for mesa/radeonsi. Last I heard, Arch's mesa 22.3.2 builds were built against llvm 14. If you've done a custom system install, then have you also taken care of `lib32-llvm-libs` and `lib32-mesa` for the 32 bit render path which Steam uses?

**Comment by danielgarciagarcia** [comment]
You are right. I forgot Steam uses 32-bit libraries. Doing for the 32-bit versions the same procedure I did for the 64-bit LLVM and mesa packages fixed the issue.
