### ISSUE TITLE
steam.sh Bus Error

### ISSUE THREAD

**Issue by yugimutou92** [ValveSoftware/steam-for-linux#9080]
#### Your system information

* Steam client version (build number or date): latest?
* Distribution (e.g. Ubuntu): EndeavourOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

```
$ steam-runtime 
steam.sh[15355]: Running Steam on endeavouros rolling 64-bit
steam.sh[15355]: STEAM_RUNTIME is enabled automatically
setup.sh[15429]: Steam runtime environment up-to-date!
steam.sh[15355]: Steam client's requirements are satisfied
/home/yugi/.local/share/Steam/steam.sh: line 798: 15483 Bus error               (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"

```

#### Steps for reproducing this issue:

1. run steam or steam-runtime command
2. get bus error
3. steam doesn't start

**Comment by AlecJDavidson** [comment]
I'm getting this error too, but only in Big Picture Mode.

OS: Arch Linux
GPU Driver: nvidia-525.78.01
Kernel: linux-lts

**Comment by yugimutou92** [comment]
i don't know if it counts as a solution but 
uninstalling steam package
deleting $HOME/.steam
deleting $Home/.local/share/steam folders
and reinstalling steam package fixed problem for me.
