### ISSUE TITLE
Steam Client crashes on latest Steam Beta when attempting to run Borderlands 3 or Tiny Tina's Wonderlands

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#9084]
#### Your system information

* Steam Runtime Version: Build ID: 10257656
* Distribution (e.g. Ubuntu 18.04): Arch Linux
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/apocalyptech/38e8cfe2e22f5ef01974afc930bd77ac
* Have you checked for system updates?: [Yes/No] Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Steam Linux Runtime - Soldier (both `client_beta` and non-Beta versions)
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`? n/a
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?

    depot   0.20230104.83                   # Overall version number
    pressure-vessel 0.20221215.0    scout           # from local file
    scripts 0.20221215.0                    # Entry point scripts, etc.
    soldier 0.20230104.1    soldier 0.20230104.1    # soldier_platform_0.20230104.1/

#### Please describe your issue in as much detail as possible:

I have no idea if this bug should go in here or on the "main" Steam issue tracker, but on the current Steam Beta version, I am unable to launch either Borderlands 3 or Wonderlands -- both of them get a little ways into the app startup (I can see some app-generated messages pop up on the console where I launched Steam), but then the games crash and take the Steam client down with it.  Hopping to the non-Beta Steam fixes it up.

I have tried this with various Proton versions: A couple GE versions, Proton 7.0-5, Proton Next (7.0-6), and Proton Experimental.  And also on both the `client_beta` branch of "Steam Linux Runtime - soldier", and the regular non-beta branch of the same.  I haven't tried all *combinations* of those, but I've yet to have a successful launch using the latest Steam Client Beta for the past couple days.

I *can* run other Proton games from this same Steam install, though -- for instance I'd installed Witcheye, and that works fine.  Also native games (tested quick with Wizorb) seem to work fine.

The various logfiles that I've gathered for this don't really have a lot in 'em that looks useful to me.  The main thing I do see is this stuff on the console:

    [ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
    crash_20230108134850_28.dmp[161491]: Uploading dump (out-of-process)
    /tmp/dumps/crash_20230108134850_28.dmp
    crash_20230108134850_28.dmp[161491]: Finished uploading minidump (out-of-process): success = yes
    crash_20230108134850_28.dmp[161491]: response: CrashID=bp-543f273a-a3c9-4359-ac50-ea5132230108
    crash_20230108134850_28.dmp[161491]: file ''/tmp/dumps/crash_20230108134850_28.dmp'', upload yes: ''CrashID=bp-543f273a-a3c9-4359-ac50-ea5132230108''
    ./steam.sh: line 798: 160731 Aborted                 (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"

That ALSOFT/PipeWire message doesn't show up when launching, for instance, Witcheye, so I wonder if that really is what's causing the big ol' crash?

Anyway, I have launched steam like so: `STEAM_LINUX_RUNTIME_VERBOSE=1 STEAM_LINUX_RUNTIME_LOG=1 PROTON_LOG=1 steam` and am attaching a few logfiles here:

[steam-console.log](https://github.com/ValveSoftware/steam-runtime/files/10369443/steam-console.log) - Full console output
[steam-397540.log](https://github.com/ValveSoftware/steam-runtime/files/10369444/steam-397540.log) - Proton log (from my homedir)
[slr-app397540-t20230108T134842.log](https://github.com/ValveSoftware/steam-runtime/files/10369445/slr-app397540-t20230108T134842.log) - SLR debug logfile

I've also uploaded various "regular" Steam logs over here -- github didn't want me to upload a `.tgz` into this Issue: https://apocalyptech.com/scratchpad/steam_bl3_launch_2023_01_08/ (that page also includes all the other attached files and sysinfo).  I've got the crash dumps available (from `/tmp/dumps`) if need be, though I suppose that stuff might have "sensitive" info in there, perhaps?

Again, not sure if this bugreport belongs here or in the main Steam project -- It's Steam Beta which seems to cause the crashing, but since there's a lot of SLR components available (and other native games and Proton-run games seem to work), I figured this might be the safer starting place.  Let me know if I can provide any more info!

#### Steps for reproducing this issue:

1. Install latest Steam Beta client
2. Attempt to launch BL3 or TTWL

**Comment by TTimo** [comment]
Hello @apocalyptech - this looks like it might be https://github.com/ValveSoftware/steam-for-linux/issues/8930, for which a fix hasn't shipped yet.

**Comment by TTimo** [comment]
I wonder though, does this mean https://github.com/ValveSoftware/steam-runtime/issues/516 is no longer an issue?

**Comment by apocalyptech** [comment]
> I wonder though, does this mean [ValveSoftware/steam-runtime#516](https://github.com/ValveSoftware/steam-runtime/issues/516) is no longer an issue?

Ah, for that one, I'd ended up just hopping on more recent Protons and had been working for awhile -- my understanding there was the the remaining issue that you'd wanted to try and figure out was why BL3 was showing a blank `STEAM_COMPAT_LIBRARY_PATHS` and `STEAM_COMPAT_TOOL_PATHS` in the SLR log, something which is still happening in the SLR logs I'd attached above.

I'm personally fine closing out that other Issue -- I didn't have any ideas as to what else I could look into re: those vars, and the game's been working fine without 'em.  Sorry for the miscommunication there, if you were waiting on something from me!

**Comment by TTimo** [comment]
Fix went in to Jan 12th beta client, please re-test.

**Comment by apocalyptech** [comment]
> Fix went in to Jan 12th beta client, please re-test.

Will do!  Though I think I'll wait for #9094 to get sorted out before I hop back on there.  :)

**Comment by apocalyptech** [comment]
> Fix went in to Jan 12th beta client, please re-test.

Hello!  Apologies for the delay, was headed out of town for the weekend right when the fix for 9094 was released.  I can confirm that on the current Beta version, I can launch both Borderlands 3 and TTWL without any problems.  So, indeed, almost certainly the exact same issue as from #8930.  Cheers, I'll close this out!
