### ISSUE TITLE
Solved: Steam cannot create or join an existing Steam Libary on exFAT drives after kernel update to support exFAT - solution: uninstall exfat-utils (fuse-exfat driver)

### ISSUE THREAD

**Issue by 0x6A7232** [ValveSoftware/steam-for-linux#9088]
This generically applies to any Steam on any distro where you want to use an exFAT partition as a Steam Library, whether shared or not.  You have to have exec permissions on the partition, which is what you'll usually see when looking up errors, but if you have errors adding and creating "cannot add library" or "library folder must be empty" then it's probably that your userspace exfat driver is conflicting with the newer (> = 5.4) Linux kernel exFAT driver.  
If you have Linux kernel version 5.4 or newer, uninstall your exfat driver package and it should start working properly.

**Comment by kisak-valve** [comment]
Hello @0x6A7232, there doesn't appear to be an actionable issue here. Your issue is with the fuse driver.

Closing as invalid.
