### ISSUE TITLE
Steam beta client crash Monster Hunter Rise (1446780)

### ISSUE THREAD

**Issue by Billli11** [ValveSoftware/steam-for-linux#9093]
#### Your system information

* Steam client version (build number or date): 1673508376(Jan 12 2023, at 05:43:25), 1673508241(Thu, Jan 12 13:43 UTC +8:00)
* Distribution (e.g. Ubuntu):  Arch Linux, Steam Deck Preview
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

The latest steam client update cause monster hunter rise (1446780) to crash after shader compile, before RE Engine intro video.

#### Steps for reproducing this issue:

1. Join Steam beta
2. Restart Steam
3. Start Monster Hunter Rise
4. Wait for crash

Tested the following.
1. Revert to stable client.(linux and Steam Deck client). Running
2. Switch proton version. Not working
3. Set `VKD3D_CONFIG=swapchain_legacy`. Not working
4. Remove shader cache. Not working
5. Re-download game files. Not working

[steam-1446780.log](https://gist.github.com/Billli11/2d9d6a28f236f248e1336f13b4c22e2a)

**Comment by minecraft2048** [comment]
Seconded this,
Arch Linux KDE Wayland

**Comment by kisak-valve** [comment]
Hello @Billli11, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5495#issuecomment-1380390130.

**Comment by wvdschel** [comment]
Runs fine on my steam deck, crashes after shader compilation on my laptop. I'm not part of any betas.
Fedora 37 Workstation, Gnome, Xorg, AMD RADV (RX6800S)

I have tried a few different Proton versions, no luck.
