### ISSUE TITLE
Some keys don't work on the big-picture keyboard overlay in Steam client beta (fine in Steam client stable)

### ISSUE THREAD

**Issue by geeksville** [ValveSoftware/steam-for-linux#9095]
#### Your system information

* Steam client version (build number or date): Jan 12 2022 beta version
* Distribution (e.g. Ubuntu): Ubuntu 22.10
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Expected: on-screen keyboard (provided by big picture mode?) should work for all keys.

Actual behavior: Some keys do not work - if either clicked on the key image with the mouse or with the physical keyboard.  For instance the "r" key on my US keyboard doesn't enter an R (or any other character) into the text entry box.  Instead the highlighted key on the graphical keyboard moves to the right to highlight the T key.

This is a regression from the stable Steam client which (though the graphical keyboard is less pretty) does work correctly.

#### Steps for reproducing this issue:

1. Run a game that uses the keyboard.  In this case I used Valheim.
2. When the keyboard GUI is raised, type some keys.  Some keys are fine (QWE for instance) but R is not.  This behavior is the same with either the proton version of Valheim or the native version.

I'm happy to add further details if it would help track this down.  For now I'm moving back to use the stable version of the client.

Update: In my original report I said I was on Ubuntu 22.04.  I'm actually on 22.10.

**Comment by geeksville** [comment]
@kisak-valve I just upgraded to the latest non beta Steam - which is apparently a bit newer than the beta where this bug was 100% reproducable.  So the Jan 31 build of Steam fixes this bug! woot!

**Comment by l3ifk** [comment]
I have the same problem on Ubuntu 24.04. Weird that this problem is reoccuring...

**Comment by twoda5h** [comment]
same problem, fedora 41 in big picture... "o" goes up, "t" goes down.

**Comment by lavadrop** [comment]
This is still unresolved. Please reopen.

**Comment by segakawaii** [comment]
I'm having the same issue as @twoda5h. Using Bazzite 41 with big picture: "q" goes left, "r" goes right, "o" goes up, "t" goes down. This happens on both a physical keyboard and the on-screen keyboard. I'm trying to chat in the game "Sky: Children of the Light". Cannot find any workarounds and changing to Steam Beta Update did not fix my issues.

**Comment by twoda5h** [comment]
P.S. still unresolved. reopen please. happens on all distros for me, only when in the  big picture mode in-game overlay. now on arch

**Comment by cprn** [comment]
@twoda5h Mate, read my previous comment.

**Comment by matoro** [comment]
This is still an issue on non-beta Steam.

**Comment by petar-andrejic** [comment]
Confirm still an issue, Fedora 43 kinoite with steam as an overlay, stable

**Comment by cprn** [comment]
@petar-andrejic if you want updates on this, subscribe to #11158 <- I know the ticket numbers are similar, but it's tracked in that one.

**Comment by TyanColte** [comment]
4 months later and this is still an issue. I've been trying to trace it down but when playing Elden Ring nightreign it's effecting the OSK when trying to set a miltiplayer password and it's very annoying.
