### ISSUE TITLE
Steam Input does not work on Artix Linux (i.e. w/o systemd)

### ISSUE THREAD

**Issue by TheGag96** [ValveSoftware/steam-for-linux#9097]
#### Your system information

* Steam client version (build number or date): Dec 15 2022, at 21:27:25
* Distribution (e.g. Ubuntu):Artix Linux, openrc
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:

Ever since switching to Artix Linux, my DS4 controller does not work with games where it would usually work when launched with Big Picture. I searched around for answers and came across [this Reddit thread](https://www.reddit.com/r/linux_gaming/comments/xnkpyc/ps5_controller_not_working_anymore_with_steam/) where someone using Artix had the same experience, fixed only by switching back to systemd. Is there anything that can be done, or is this going to forever be a hard dependency? Thanks.

#### Steps for reproducing this issue:

1. Install Artix Linux and Steam.
2. Connect a controller to be used through Steam Input.
3. Launch any game with Big Picture.
4. Observe that the game does not respond to controller input.

**Comment by kisak-valve** [comment]
Hello @TheGag96, there is no direct dependency on systemd. Blind guess that there's a permission issue with the access to controller or `/dev/uinput`.

**Comment by TheGag96** [comment]
Ah, right you are - I Googled around and found that running `sudo modprobe uinput` makes it work! I guess systemd basically does that for you, but I'd need some service for openrc that does it too. Thank you!
