### ISSUE TITLE
Non-Steam game name change launch failure

### ISSUE THREAD

**Issue by streetpea** [ValveSoftware/steam-for-linux#9098]
#### Your system information

* Steam client version: 1673573116
* SteamOS version: 3.4.4
* Opted into Steam client beta?: [Yes]
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:

Non-Steam game don’t launch properly when I change their names until I restart the Steam Deck or change between desktop/gaming mode.

#### Steps for reproducing this issue:

1. Add a non-Steam game
2. Launch it successfully and close it
3. Change its name in properties
4. Try to launch it again (unsuccessfully)

**Comment by kisak-valve** [comment]
Hello @streetpea, this reads like a Steam client issue instead of an issue with SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by TTimo** [comment]
Should be fixed in next beta client update.

**Comment by kisak-valve** [comment]
This is expected to be part of the [2023-03-15](https://store.steampowered.com/oldnews/191068) Steam client update.
