### ISSUE TITLE
Steam Deck Desktop Mode on-screen keyboard leaves invisible windows which block input

### ISSUE THREAD

**Issue by jpumc** [ValveSoftware/steam-for-linux#9099]
#### Your system information

* Steam client version (build number or date): Jan 13 2023, at 00:55:04
* Distribution (e.g. Ubuntu): "SteamOS Holo" (64 bit) (Steam Deck)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

On Steam Deck, in desktop mode, opening and closing the steam on-screen keyboard leaves an invisible window, which blocks input to windows below it. Reopening and closing the keyboard on the other half of the screen leaves another invisible window. I think this also happened in the previous steam update, which had the "Maximum number of clients reached" issue.

xprop of the invisible window, taken by running `xprop` in Konsole and clicking the area where the keyboard:

```
_NET_WM_USER_TIME(CARDINAL) = 39024487
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
STEAM_INPUT_FOCUS(CARDINAL) = 0
STEAM_NOTIFICATION(CARDINAL) = 0
STEAM_OVERLAY(CARDINAL) = 0
_VARIABLE_REFRESH(CARDINAL) = 1
XdndProxy(WINDOW): window id # 0x4400010
STEAM_GAME(CARDINAL) = 769
XdndAware(ATOM) = BITMAP
_NET_WM_NAME(UTF8_STRING) = "SP Keyboard"
WM_NAME(UTF-8) = "SP Keyboard"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
_NET_WM_PID(CARDINAL) = 39932
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
_KDE_NET_WM_USER_CREATION_TIME(CARDINAL) = 39003017
WM_CLASS(STRING) = "steamwebhelper", "steamwebhelper"
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: False
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 0, 440
WM_CLIENT_MACHINE(STRING) = "steamdeck"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
```

#### Steps for reproducing this issue:

On Steam Deck:

1. Switch to desktop mode
2. Right click the top half of the desktop: desktop menu opens.
3. Click outside the menu to close it.
4. Right click the bottom half of the desktop: desktop menu opens.
5. Click outside the menu to close it.
6. Open on-screen keyboard with `(STEAM) + (X)`
7. Right click the half of the desktop visible outside the keyboard area: desktop menu opens.
8. Click outside the menu to close it.
9. Close the keyboard with `(B)` or the hide keyboard button on the keyboard
10. Right click desktop where the keyboard was: desktop menu doesn't open
11. Right click desktop where the keyboard was not: desktop menu opens

**Comment by aleclouck** [comment]
I am also seeing this exact issue when ever I close the keyboard it spawns another one and gets in the way of operation

**Comment by KaseyTheJackal** [comment]
I can reproduce this issue without any problems. Every single time, it's repeatable.

Latest SteamOS beta. Trapped in desktop mode so can't get a version number without forcefully powering off my Deck

**Comment by rlparks** [comment]
Can reproduce on the same Steam client version. I've found I can temporarily fix the issue by closing Steam from the tray icon context menu (though it returns the next time the virtual keyboard is closed after Steam is relaunched).

**Comment by revanmj** [comment]
Exactly same issue on my Deck on Beta channel.

**Comment by ltcarneiro** [comment]
This for me happens in stable, beta and preview. Every single time. And it spawns a new window in every virtual keyboard activation.

**Comment by dreamtheater39** [comment]
Same issue. 
Hold the steam key and use the trackpad to use the mouse when this happens

**Comment by Quad-Plex** [comment]
Same issue. Makes it so the on-screen keyboard can only be used once, afterwards steam needs to be killed and restarted everytime. Super annoying.

**Comment by ltcarneiro** [comment]
In preview now, when steam is open, the mouse stop working

**Comment by PrMinisterGR** [comment]
> Same issue. Hold the steam key and use the trackpad to use the mouse when this happens

Unfortunately this doesn't fix it still, as the bottom half of the screen (with the exception of the taskbar), cannot be interacted with after the on-screen keyboard has been invoked.

**Comment by kisak-valve** [comment]
Hello, per "Fixed Big Picture Mode keyboard window not exiting when closed." in the [2023-01-23](https://steamcommunity.com/games/1675200/announcements/detail/3635001990334169993) Steam Deck client beta update, please opt into the Steam Deck Beta update channel if not already and retest this issue.

**Comment by revanmj** [comment]
Seems fixed for me (quickly checked with Brave Browser on desktop).

But now I noticed that touchpad input on the keybaord stopped working in desktop mode (still works while in Game UI) :(

**Comment by ltcarneiro** [comment]
> Hello, per "Fixed Big Picture Mode keyboard window not exiting when closed." in the [2023-01-23](https://steamcommunity.com/games/1675200/announcements/detail/3635001990334169993) Steam Deck client beta update, please opt into the Steam Deck Beta update channel if not already and retest this issue.

I did a quick test using the latest preview build and it worked fine. Thanks!

**Comment by EmmerichFrog** [comment]
Same issue as jpumc, I now get an invisible windows that blocks input until I exit steam. While exiting it show a window with "Shutting down Steam...", similar to big picture mode

**Comment by jpumc** [comment]
Steam client from Jan 28 2023 seems to have fixed this. I spent a few minutes opening and closing the keyboard and using it for these few days and it has not gotten stuck once.

**Comment by Oxotnak** [comment]
Hello, sadly this problem still alive but probably happens much less for other people. I've created discussion in steam: https://steamcommunity.com/app/1675200/discussions/1/4415299132512112941/
Please reopen issue if it's possible. I'm not sure how to reproduce problem but i've seen multiple reports about that on reddit and in steam

**Comment by kisak-valve** [comment]
Hello @Oxotnak, please open a new issue report for the lookalike issue.
