### ISSUE TITLE
Steam crashes with a controller connected

### ISSUE THREAD

**Issue by uhthomas** [ValveSoftware/steam-for-linux#9101]
#### Your system information

* Steam client version (build number or date): https://gist.github.com/uhthomas/4d5f9664cc171c7e874c429d35f32002
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam crashes whenever an Xbox wireless controller is connected.

```
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
steam: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
crash_20230113191437_35.dmp[26669]: Uploading dump (out-of-process)
/tmp/dumps/crash_20230113191437_35.dmp
/home/thomas/.local/share/Steam/steam.sh: line 798: 26310 Aborted                 (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"

~                                                                                                                                                            12s
❯ crash_20230113191437_35.dmp[26669]: Finished uploading minidump (out-of-process): success = yes
crash_20230113191437_35.dmp[26669]: response: CrashID=bp-5161667a-e510-43be-87ef-af9fa2230113
crash_20230113191437_35.dmp[26669]: file ''/tmp/dumps/crash_20230113191437_35.dmp'', upload yes: ''CrashID=bp-5161667a-e510-43be-87ef-af9fa2230113''
```

#### Steps for reproducing this issue:

1. Open steam.
2. Connect controller.
3. Visit either the controller configuration menu, or try to launch a game from big picture with the controller.

**Comment by uhthomas** [comment]
Related https://github.com/ValveSoftware/steam-for-linux/issues/9090, but this issue (https://github.com/ValveSoftware/steam-for-linux/issues/9101) covers more than just the controller configuration menu.

**Comment by kisak-valve** [comment]
Hello @uhthomas, this looks similar to https://github.com/ValveSoftware/steam-for-linux/issues/8977#issuecomment-1344845959. What version of libX11 are you using and does downgrading `libx11` and `lib32-libx11` to 1.8.1 workaround the issue?

**Comment by uhthomas** [comment]
```
❯ paru -Q libx11
libx11 1.8.3-5

**Comment by uhthomas** [comment]
It may be a little tricky to test though, older versions of packages aren't readily available through the package manager as Arch Linux is a rolling release OS.

**Comment by ammgws** [comment]
^ You can install `downgrade` from the AUR to help out with that

**Comment by wxlfsangel** [comment]
Having the same issue as @uhthomas and i downgraded libx11 and lib32-libx11 to 1.8.1 and now the controller settings works

**Comment by PolarisPyra** [comment]
Can confirm. I also had this issue for two days I downgraded libx11 and lib32x11 to 1.8.1 and it worked!

**Comment by XenHat** [comment]
Just confirming that using `downgrade` to install libx11 and lib32-libx11 to 1.8.1 does fix my crash as well.

**Comment by wxlfsangel** [comment]
Has this been fixed in recent updates or do we keep an old version of libx11 and lib32-libx11?

**Comment by kisak-valve** [comment]
Looks like libx11 1.8.4 has been released, but it's not yet packaged for Arch to prompt a retest. In theory, that's the proper resolution to this issue.

**Comment by XenHat** [comment]
Seems to work now!

```
 pacman -Qs libx11            
local/lib32-libx11 1.8.4-1
    X11 client-side library (32-bit)
local/libx11 1.8.4-1
    X11 client-side library
```
![image](https://user-images.githubusercontent.com/980408/232898777-428e8ea9-6668-4224-a86c-6969e69ce97d.png)

**Comment by kisak-valve** [comment]
Closing as fixed.
