### ISSUE TITLE
[Big Picture] Steam Crashes

### ISSUE THREAD

**Issue by gamingmsi** [ValveSoftware/steam-for-linux#9102]
#### Your system information

* Steam client version: **Dec 15 2022, at 21:27:25**
* Distribution: **EndeavourOS (Kernel: 6.1.5-arch2-1)**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
Simple really, enter a big picture, and start clicking stuff, doesn't matter if it's settings or community tab or something else, just interact with with Steam while in Big Picture mode and it will crash, you'll have to log in again. If you do not interact with anything however, it doesn't crash.

#### Steps for reproducing this issue:

1. Enter the Big Picture Mode
2. Interact inside it
3. Crash

**Comment by kisak-valve** [comment]
Hello @gamingmsi, if you completely close Steam, then run `steam-runtime` from a terminal and reproduce the issue, are there any hints in the terminal spew?

**Comment by gamingmsi** [comment]
Yes, here it is.

[steam-runtime output.txt](https://github.com/ValveSoftware/steam-for-linux/files/10416448/steam-runtime.output.txt)

**Comment by kisak-valve** [comment]
Thanks @gamingmsi, these are the lines of interest in your log:
```
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
steam: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

This is a libx11 system package regression starting with 1.8.2 and needs to be fixed in the upstream project.

This is the same issue as #8977. Closing as a duplicate.
