### ISSUE TITLE
Rockstar Games Launcher using 55+ GB of RAM.

### ISSUE THREAD

**Issue by Krutonium** [ValveSoftware/steam-for-linux#9103]
#### Your system information

* Steam client version (build number or date): December 15, 2022 at 21:27:25
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I went to play GTA V, ran the setup, and the setup just ran for ages. Eventually my system started stuttering hard, so I opened System Monitor and well, yeah.

#### Steps for reproducing this issue:

1. Try to install GTA V
2. Go to install the Launcher (RS:G Launcher)
3. ![RAM](https://user-images.githubusercontent.com/3945538/212464113-48799e8a-d4c2-445b-83e0-68e29e4e4519.jpg)
4. Experience debilitating RAM usage the likes of which will be felt until you kill the process.

**Comment by kisak-valve** [comment]
Hello @Krutonium, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-1382737727.
