### ISSUE TITLE
System Information causes gpu hang

### ISSUE THREAD

**Issue by Smoukus** [ValveSoftware/steam-for-linux#9105]
#### Your system information

* Steam client version (build number or date): **Built: Dec 15 2022, at 21:27:25**, **Steam API: v020**, **Steam package versions: 1671236931**
* Distribution (e.g. Ubuntu): **EndeavourOS**
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**
* Kernel: **6.2.0-rc3-273-tkg-cfs**
* CPU: **Ryzen 9 5900x**
* GPU: **AMD RX 6800XT**
* DE: **KDE Plasma**
* Mesa version: **mesa-git and lib32-mesa-git with latest commit as of this writing (7e52bd7b)**

#### Please describe your issue in as much detail as possible:
When I want to gather my System Information in Steam via `Help -> System Information`, I get black screen on both of my monitors. After few seconds the screen comes back, however I am unable to use my mouse and keyboard then.
After the screen reappears, it will go black once again, recover again, but mouse and keyboard are still unusable.
The only option is to hard reboot/shutdown the PC.

I ran the following command in order to figure out what has happened: `sudo journalctl -o short-precise -k -b -1`

I've found some interesting things that probably point out to that hang, however I don't understand much.
Here is the gist of those lines from the log: https://gist.github.com/Smoukus/f31f878c75f0adce978e93b1eb39bb76

#### Steps for reproducing this issue:

1.  Open Steam
2.  Click on Help
3.  Click on System Information
4.  System Information will start to gather.
5.  At the bottom of the System Information window, there will be a text: `...gathering report` (something along those lines)
6.  After few seconds, the above described problem will happen.

**Comment by kisak-valve** [comment]
Hello @Smoukus, Steam shouldn't be doing anything special here and this issue should also be reported to your video driver vendor.

**Comment by Smoukus** [comment]
> Hello @Smoukus, Steam shouldn't be doing anything special here and this issue should also be reported to your video driver vendor.

Hey @kisak-valve, I've created an issue on mesa as well. Was told to make an issue here as well just in case that it had something to do with Steam.

If you think that this issue has nothing to do with Steam directly, feel free to close the issue.

**Comment by Smoukus** [comment]
UPDATE: with the current mesa-git commit that I'm on (883f18f7), it doesnt crash the GPU anymore.

**Comment by kisak-valve** [comment]
Closing per the last comment.
