### ISSUE TITLE
Problems with typing in overlay

### ISSUE THREAD

**Issue by bubba-champion** [ValveSoftware/steam-for-linux#9106]
#### Your system information

* Steam client version (build number or date): 1673573268
* Distribution (e.g. Ubuntu): Void
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Today I cleanly reinstalled my system and moved from DWM to Gnome. After installing and configuring the Steam client, I encountered a problem when printing in the steam overlay. with DWM. I didn't encounter this problem when using DWM. [Details about this issue from a Reddit user](https://www.reddit.com/r/ManjaroLinux/comments/ychtwt/steam_overlay_typing_problem/), but in my case this problem also affects special characters.

#### Steps for reproducing this issue:

1. Installing a Void Linux distribution with Gnome.
2. Installing and configuring Steam then launching game through Steam Play.
3. Try to print something in steam overlay.

**Comment by kisak-valve** [comment]
Hello @bubba-champion, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/6280.

Closing in favor of the older issue report.
