### ISSUE TITLE
Steam Deck resolution option on non-Steam Titles is global

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/steam-for-linux#9108]
#### Your system information

* Steam client version: 1673573116
* Distribution: SteamOS 3.5 20230110.1000
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In the Steam Deck client, setting a Game Resolution option for a non-Steam shortcut will set the same resolution globally for all other non-Steam shortcuts. For example, this issue results in it being impossible to have one non-Steam shortcut playing at 720p, and another at 1080p.

#### Steps for reproducing this issue:

1. Have more than one non-Steam shortcut.
2. Set one shortcut's resolution to any of your choice.
3. Check the resolution of another shortcut. They should match, despite not having set it manually in the other shortcut's properties.

https://user-images.githubusercontent.com/34801996/212527914-32c1583d-f8cb-4120-aa16-7852ab7caa36.mp4

(Footage recorded on a desktop PC, but this was using the Steam Deck client.)

**Comment by kisak-valve** [comment]
Hello @Sterophonick, this issue is already being tracked at #8950. Closing as a duplicate.
