### ISSUE TITLE
Steam client defines HDD as SSD.

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/steam-for-linux#9114]
#### Your system information

* Steam client version (build number or date): 1673573268
* Distribution (e.g. Ubuntu): Fedora Rawhide
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)

#### Please describe your issue in as much detail as possible:
I have no idea if the Steam client can optimize its work on the HDD. But he defines HDD as SSD.

![Screenshot from 2023-01-17 04-35-57](https://user-images.githubusercontent.com/200750/212781172-4c745e96-9a48-4a82-8697-1ca3a95dcabb.png)

```
❯ head /sys/block/*/queue/rotational
==> /sys/block/nvme0n1/queue/rotational <==
0

==> /sys/block/sda/queue/rotational <==
1

==> /sys/block/zram0/queue/rotational <==
0
```

![Screenshot from 2023-01-17 04-50-08](https://user-images.githubusercontent.com/200750/212781542-03a71dc2-ecba-40a7-8bb3-d0077e6ea49b.png)

#### Steps for reproducing this issue:

1. In steam client "Help" -> "System information"
2. Found "Storage" section
3. Number of HDDs showed 0 and HDD sizes is absent.

**Comment by kisak-valve** [comment]
Hello @NTMan, this issue is already being tracked at #8966. Closing as a duplicate.
