### ISSUE TITLE
On Screen Keyboard in Game Mode on Steam Deck for Non-Steam Games uses Desktop Keyboard Window instead of Game Mode's Keyboard (when using Steam+X)

### ISSUE THREAD

**Issue by CarJem** [ValveSoftware/steam-for-linux#9117]
#### Your system information

* Steam client version (build number or date): 1673912699
* Distribution (e.g. Ubuntu): SteamOS 3.4.4
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Onscreen Keyboard uses the Desktop Onscreen Keyboard for Non-Steam Apps (when using Steam+X) while the user is in Game Mode, causing possible soft locks.

A workaround for this issue is to open the keyboard from the QAM. 

_Hopefully, though this will get addressed faster than the multi-apps not closing issue..... that took a whole year to fix._

#### Steps for reproducing this issue:

1. Launch a Non-Steam Game (especially one that doesn't have a game-like fullscreen, e.g. Discord, Google Chrome)
2. Trigger the On-Screen Keyboard via the Show Keyboard Steam Input Trigger
3. Result

**Comment by CarJem** [comment]
I believe that this is been resolved as of the latest beta

**Comment by kisak-valve** [comment]
Closing per the last comment.
