### ISSUE TITLE
Steam no longer starts

### ISSUE THREAD

**Issue by Conusoid** [ValveSoftware/steam-for-linux#9119]
**System information**
OS: Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-20-amd64
WM: i3
CPU: Intel i5-4670 (4) @ 3.800GHz
GPU: NVIDIA GeForce GTX 770

* Steam client version (build number or date): steam/stable,now 1.0.0.68-1 i386
* Distribution: Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

**Description of the issue:**
Freshly installed system (a bit over a week old), steam has been launching successfully every day for the past week (last session was around Sunday), but today it doesn't progress beyond the inscription "Connecting Steam account:..". All required libraries (both 64 and 32) are installed, there were no any updates or installs since the last session.

<details>
  <summary>Terminal output</summary>

```
[23:20:42]max@dom:~$ steam
steam.sh[51559]: Running Steam on debian 11 64-bit
steam.sh[51559]: STEAM_RUNTIME is enabled automatically
setup.sh[51625]: Steam runtime environment up-to-date!
steam.sh[51559]: Steam client's requirements are satisfied
[2023-01-18 23:20:45] Startup - updater built Dec 15 2022 21:26:49
[2023-01-18 23:20:45] Startup - Steam Client launched with: '/home/max/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad'
Installing breakpad exception handler for appid(steam)/version(1671236931)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-01-18 23:20:45] Loading cached metrics from disk (/home/max/.steam/debian-installation/package/steam_client_metrics.bin)
[2023-01-18 23:20:45] Using the following download hosts for Public, Realm steamglobal
[2023-01-18 23:20:45] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-01-18 23:20:45] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-01-18 23:20:45] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1671236931)
[2023-01-18 23:20:45] Checking for update on startup
[2023-01-18 23:20:45] Checking for available updates...
[2023-01-18 23:20:45] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-01-18 23:20:45] Manifest download: send request
Installing breakpad exception handler for appid(steam)/version(1671236931)
[2023-01-18 23:20:46] Manifest download: waiting for download to finish
[2023-01-18 23:20:46] Manifest download: finished
[2023-01-18 23:20:46] Download skipped: /steam_client_ubuntu12 version 1671236931, installed version 1671236931, existing pending version 0
[2023-01-18 23:20:46] Nothing to do
[2023-01-18 23:20:46] Verifying installation...
[2023-01-18 23:20:46] Performing checksum verification of executable files
[2023-01-18 23:20:46] Verification complete
Loaded SDL version 2.27.0-p7692409
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf4a1c590
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf4a1adc0
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[51735]: Runtime for steamwebhelper: defaulting to /home/max/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[51735]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
CAppInfoCacheReadFromDiskThread took 2277 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)

(steam:51722): Gtk-WARNING **: 23:21:00.052: gtk_disable_setlocale() must be called before gtk_init()

(steam:51722): Gtk-WARNING **: 23:21:00.054: Unable to locate theme engine in module_path: "adwaita",
/home/max/.themes/Material-Black-Blueberry/gtk-2.0/main.rc:756: error: unexpected identifier 'direction', expected character '}'

(steam:51722): Gtk-WARNING **: 23:21:00.055: Unable to locate theme engine in module_path: "adwaita",
/home/max/.themes/Material-Black-Blueberry/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1671236931)
local (potentially out of sync) copy of roaming config loaded - 1482 bytes.
roaming config store loaded successfully - 1482 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
Installing breakpad exception handler for appid(steam)/version(1671236931)
[2023-01-18 23:22:47] Background update loop checking for update. . .
[2023-01-18 23:22:47] Checking for available updates...
[2023-01-18 23:22:47] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-01-18 23:22:47] Manifest download: send request
[2023-01-18 23:22:47] Manifest download: waiting for download to finish
[2023-01-18 23:22:48] Manifest download: finished
[2023-01-18 23:22:48] Download skipped by HTTP 304 Not Modified
[2023-01-18 23:22:48] Nothing to do
```
Gtk-WARNINGs were present before, so I think they have nothing to do with it.
</details>

**Steps for reproducing this issue:**

1. Just start Steam.

**Comment by Faalagorn** [comment]
I seem to have the same issue on Arch Linux, with Steam beta, though it seems to work for my wife on the same network and same OS, but different DE.

**Comment by Houtworm** [comment]
I seem to have the same issue on Arch Linux with Steam Beta too, It works fine on my Deck and on my laptop.

I tired to reset Steam, tried native and runtime, but that didn't seem to help, I just have to enter my account details every time I try now :P

I have different terminal output tho here is a small snippet, It just keeps going with these messages but the client never shows

migrating temporary roaming config store
Xlib: sequence lost (0x10000 > 0x45f) in reply type 0xc!
Xlib: sequence lost (0x10000 > 0x461) in reply type 0xc!
Xlib: sequence lost (0x10000 > 0x463) in reply type 0xc!
....


And only when I close steam from the tray I get this at the end of the terminal output

(steam:30898): GLib-GObject-CRITICAL **: 13:50:12.329: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:30898): GLib-GObject-WARNING **: 13:50:12.330: instance with invalid (NULL) class pointer

(steam:30898): GLib-GObject-CRITICAL **: 13:50:12.330: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(steam:30898): GLib-GObject-CRITICAL **: 13:50:12.330: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2023-01-19 13:50:12] Shutdown

I am not sure if it is related to the Original Issue, but in all these years I never had Steam refusing to start, and the timing matches, So I guess it is likely.

**Comment by Faalagorn** [comment]
> Xlib: sequence lost (0x10000 > 0x45f) in reply type 0xc! Xlib: sequence lost (0x10000 > 0x461) in reply type 0xc! Xlib: sequence lost (0x10000 > 0x463) in reply type 0xc!

I also get these errors, not sure if they are related? Hex number goes up every time. I move mouse over the window.

P.S. Steam still doesn't start today, seems to be the same issue, I didn't try removing my profile to log back again yet and logging from Deck as well, but I also never had problems logging to Steam daily.

**Comment by Faalagorn** [comment]
I tried removing all `.local/share/Steam` folder and relogging, but it seems it's stuck, just on a different screen now.
![screenshot_2023-01-19-213619](https://user-images.githubusercontent.com/4951331/213554240-a6878bc1-7128-4040-a811-8ad754f6cd76.png)

**Comment by Faalagorn** [comment]
Well, it seems to have fixed itself now, both with the new and old profile; any clue what could be the issue?

**Comment by Conusoid** [comment]
Ahahaha! You've got to be kidding me! I just wrote out and formalized all my observations up to the dpkg log in the period between the last successful launch of steam and yesterday, when your message popped up and my steam also started (even though it wasn't working an hour ago)! Looks like the issue was on the side of the steam servers, as I thought.
So I guess the issue can be closed now. However, in view of the clearly mysterious nature of the issue, I don't rule out a re-open in the future.

**Comment by Houtworm** [comment]
Yes also fixed here, Still curious what was the issue tho, I see all of us have 1000+ games, maybe that has something to do with it?

**Comment by Conusoid** [comment]
If so, then this once again indicates that the root of the problem is on the side of Steam. However, I find it strange that this issue has affected a very small group of users.

**Comment by Houtworm** [comment]
I have no doubt it was not on the side of steam, it was fixed for all 3 of us when doing nothing after trying everything. It is strange only a few people were affected, It is probably some niche hard/software configuration, the big library, or something else, or maybe a combination. I am also pretty sure not everyone knew where or felt like reported it here, and many many more didn't even launch Steam during this time. I doubt we will get an answer tho, so it is all speculation and that is all that it will ever be.
