### ISSUE TITLE
[Feature Request] add option to remove the prefix when uninstalling a title 

### ISSUE THREAD

**Issue by Yasand123** [ValveSoftware/steam-for-linux#9127]
I understand there are cases where you don't want to remove the prefix, and it's safer to not remove it _by default_ for new users so they don't complain about losing save files. But I remove the prefix in 99% of the cases. And for most of us, who know what they're doing, it's really silly having to 1) use a 3rd party tool to determine the correct ID (i.e. protontricks) and, 2) manually browsing files to find the directory in question and remove it.

**Comment by kisak-valve** [comment]
Hello @Yasand123, this issue is already being tracked at #7418. Closing as a duplicate.
