### ISSUE TITLE
Generating System Information Crashes GPU

### ISSUE THREAD

**Issue by n00btube3D** [ValveSoftware/steam-for-linux#9133]
#### Your system information
[System Information Generated in LTS Kernel (5.15.89)](https://gist.github.com/n00btube3D/d0118f8df273d265638eeb501095fe2e)

* Steam client version (build number or date): Dec 15 2022
* Distribution (e.g. Ubuntu): Arch Linux (6.1.7 kernel)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I'm not sure where to post this issue so I'll post it here first.
[Kernel Log (Excerpt) ](https://gist.github.com/n00btube3D/1f8a73d3f246c40c1bc8af524ff58270)
Steam Log doesn't show anything useful except:
```
amdgpu: The CS has been rejected (-125). Recreate the context.
amdgpu: The CS has been rejected (-125), but the context isn't robust.
amdgpu: The process will be terminated.
```
It only crashes when using 6.1.7 kernel and doesn't happen when using LTS kernel 5.15.89.

#### Steps for reproducing this issue:

1. Attempt To Generate System Information
2. Crashes during "The runtime information tool is preparing a report, please wait..."

**Comment by kisak-valve** [comment]
Hello @n00btube3D, this issue already being tracked at #9105. As mentioned there, Steam isn't doing anything particularly special here and this issue should be reported to your video driver vendor.

Closing as a duplicate.
