### ISSUE TITLE
Steam Client becoming unresponsive

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#9136]
#### Your system information

* Steam client version (build number or date): 1674616553
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Since a few days ago (I would like to say the update that removed the option to start Steam without the browser because it was around those dates, but I have never used that feature) the client has become very unresponsive, taking long times to load activity, and while loading it, it just doesn't respond. It's kinda slower and doesn't response to any input until it finished whatever it's loading

I have reduced the amount of installed games and tried clearing the browser cache inside Steam

**Comment by kisak-valve** [comment]
Hello @alosarjos, can you go to `Steam` -> `Settings` -> `Interface` and note if `Enable GPU accelerated rendering in web views` is enabled or not. If it isn't, then does toggling that on have any effect?

Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alosarjos** [comment]
It's already enabled, I've also disabled animations for friend list views since I know it causes some issues, but all this is happening without any other window/notification opened.

https://gist.github.com/alosarjos/aae849ae851caa304c52305ebe5df1a1

**Comment by alosarjos** [comment]
@kisak-valve  Not sure if this means something, but my system logs are full of this;

![imagen](https://user-images.githubusercontent.com/29999427/214696091-2cc06bb0-f401-4181-ab81-785b2276b5f1.png)

**Comment by kisak-valve** [comment]
That's a regression in your system, `lib32-libx11` 1.8.2 and 1.8.3 has problems.

**Comment by alosarjos** [comment]
Not sure if that's what is causing the issues, I see the package marked as outdated on Arch, hoping it gets updated soon

**Comment by andreldmonteiro** [comment]
Hi, recently I got a new GPU and steam has become very slow interacting with when I use my newly acquired AMD 7900 XTX, if I switch back to the IGP on ZEN4 that I was using before then steam behaves normally and isn’t slow.
I'm using the flatpak version from flathub.

**Comment by Floeqqu** [comment]
Have you ever managed to resolve your issue? I have had the exact same issue for quite some time now, there doesn't seem to be a fix anywhere on the internet really....

**Comment by Floeqqu** [comment]
### I have found a fix
Maybe this has been resolved by now, but I fixed the laggs on steam by disabling my CPU interne graphic chip. You can do this by opening the device manager, then looking for "display adapters", pop it down and there will be listed your GPU and if you have one, your CPU interne GPU. Just right click it and press disable and youre done. Not sure if this will ever help someone but I sure hope so. :)

**Comment by alosarjos** [comment]
Steam Client beta nowadays works perfectly fine with GPU acceleration!!!
