### ISSUE TITLE
steam stuck on grey screen during startup

### ISSUE THREAD

**Issue by CorruptedVor** [ValveSoftware/steam-for-linux#9138]
#### Your system information

* Steam client version (build number or date): 1671236931
* Distribution (e.g. Ubuntu): Arch Linux chroot under Void Linux musl (hence chroot)
* Opted into Steam client beta?: [Yes/No] Yes (also broken without)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected to start up steam, instead get stuck on this grey window.

#### Steps for reproducing this issue:

1. start steam under the arch chroot on void
which gets you this grey screen:
![screenshot-2023-01-25-20:28:22](https://user-images.githubusercontent.com/51972476/214668661-3ccef4c4-b8f5-4136-aca2-6f9edf42ab1a.png)

log:
[log.txt](https://github.com/ValveSoftware/steam-for-linux/files/10502889/log.txt)

This is also broken in the same way when using a void linux glibc chroot under the same void linux musl system

Flatpak version does not have this problem.

EDIT: could reproduce under void linux glibc (no chroot) but fixed after updating void

**Comment by GithubUser5462** [comment]
I get this with the flatpak version

![Screenshot_20230127_215238](https://user-images.githubusercontent.com/1575836/215195111-7de0cdff-84c1-4cfa-87d1-a9ea2c50351d.png)

**Comment by CorruptedVor** [comment]
seems like updating fixes it

**Comment by CorruptedVor** [comment]
reoccurred after an update
duplicate of #8451
