### ISSUE TITLE
beta regression: gamepadui no longer responding to PS4, PS5 controller while focused

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-for-linux#9140]
#### Your system information

* Steam client version (build number or date): beta 2023-01-24 and 2023-01-25
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
I have PS4 and PS5 controllers (Dualshock 4 and Dualsense) paired with my Linux PC via a USB Bluetooth dongle. Before the 24th January beta, I could use the new big picture (gamepadui) with these controllers.

Since the 24th January beta, after selecting my Steam user, the only button that Steam responds to is the guide button (Playstation logo) which opens the system menu as usual; all other buttons are ignored. I can still navigate the UI with keyboard and mouse.

The controllers do work in a few places. When I am at the menu of Steam users, both my controllers do work: it is only when I have selected my user's icon that it stops working. When I click in the search bar, both controllers do work to navigate the on-screen keyboard.

After I launch a game, the controllers work correctly in the game, at least in Cyberpunk 2077 (Proton) and Into The Breach (native Linux). If I press the guide (PS) button while in-game, I get the Steam Overlay with a Steam-Deck-like visual style, and I *can* navigate that with both controllers (tested in Into The Breach only).

Back in the Steam client, if I go into Options -> Controller -> Begin Test, all the buttons appear to be detected correctly and make the corresponding button light up on the controller diagram, but I'm unable to exit from the test, except via Alt+F4 and then exiting Steam via the system tray icon. (While I am in the controller test UI, a prompt suggests holding circle to exit, but nothing happens when I do that, or when I press Escape or click on the menu or "circle to exit" prompts with the mouse.)

#### Steps for reproducing this issue:

1. Pair Bluetooth PS4/PS5 controller
2. Launch Steam, configured to start in Steam-Deck-style "new big picture" (same as `-gamepadui`)
3. Observe controller working as expected while selecting a user account
4. Press confirm (cross) button with my user account highlighted
5. Try to navigate between games or launch a game, observe inability to do so
6. Press guide (PS) button, system menu appears
7. Try to navigate system menu with controller, cursor does not move

**Comment by smcv** [comment]
This is not the same symptom as #9139 (the submitter of #9139 gets unexpected results from input, I get nothing at all) but might have the same root cause.

**Comment by smcv** [comment]
In case it matters, I have "Enable Steam Input for Playstation controllers" enabled.

If I go into options -> Controller -> select PS4 controller -> Non-Game Controller Layouts -> Desktop Layout -> Edit, below "Current Layout" I see a layout named "Disabled", marked as created by ScottD. I'm sure I've never intentionally selected this layout (I don't *think* I've ever selected *any* custom desktop layout). When I view the details, it has no buttons mapped. Is this intended functionality? It seems this might be Valve's official configuration in disguise, because the PS4 controller's guide button chord layout also shows up as having been created by ScottD.

If I click on that layout, go to the Recommended tab, and choose "Official Layout for - Desktop Configuration", that also seems to have no buttons mapped. "Apply layout" takes me back to it being listed as layout "Disabled" by ScottD.

With the PS5 controller, below "Current Layout" I see a layout labelled "Official Layout for - Disabled" with no author listed. This time, the Recommended tab contains two layouts, "Official Layout for - Disabled" with a blue highlight, and "Official Layout for - Desktop Configuration" without. Clicking on either of those takes me to a layout with all buttons disabled.

However, perhaps all of this is irrelevant, because Steam should be using the controller directly and not going via Steam Input?

**Comment by smcv** [comment]
OK, this is particularly weird. The controller only works while Steam *doesn't* have focus!

If I Alt+Tab to another window (in my case a gnome-terminal that I ran `steam` from), then both controllers start working to control the Steam UI. If I click or Alt+Tab back into the `steamwebhelper` window, then it stops responding to the controllers.

**Comment by heyrict** [comment]
I've encountered exactly the same issue today. It seems that gamepadui uses the *Desktop Layout* rather than *gamepad buttons* as an input at present. One workaround is to map dpad to arrow keys, and ab buttons to Enter&Escape in *Desktop Layout*.

**Comment by Balderick** [comment]
Another workaround used by a windows user is to recompile sdl3 for win32 and drop the sdl3.dll in steam folder.  Launch steam with -noverifyfiles and boom has working ps4/ps5 controllers again.
https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3763355214772582411/

Steam Input is so broken for all "supported" controller types it needs a body off chassis rebuild.

**Comment by RomanKode** [comment]
Same issue here on Nobara/Fedora 37 KDE Plasma 5.26.5 Wayland, when focused on NewBigPicture(SDUI) it does not take input from PS5 controller.

**Comment by lmm1191** [comment]
Same issue here on arch linux. works when not focused but is so broken. If I press down, it will skip 1 then selects the next one. Doesn't work on settings even though you hear sounds the a selection is being made (dpad is pressed)

**Comment by smcv** [comment]
This seems to be working now, perhaps it was fixed in the [January 27th](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3659772423367878641) beta?

**Comment by lavadrop** [comment]
> This seems to be working now, perhaps it was fixed in the [January 27th](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3659772423367878641) beta?

Yes, gamepadui now registers DualShock/DualSense main action buttons. However, the new gamepadui actions involving guide button + action button don't work at all, there's no way to call the new virtual keyboard or take screenshots or even display the button combination screen.

**Comment by smcv** [comment]
> However, the new gamepadui actions involving guide button + action button don't work at all

That's not the issue that I reported here, so please report that separately.

**Comment by smcv** [comment]
This seems to be reliable since January 27th.

**Comment by smcv** [comment]
@marco-calautti: The issue that was tracked here a year ago was fixed. There's a different regression for gamepads in steamwebhelper in the new betas since January 2024: see #10406.
