### ISSUE TITLE
"Launcher error" when launching CS:GO Steam Play

### ISSUE THREAD

**Issue by Geworge** [ValveSoftware/steam-for-linux#9141]
#### Your system information

* Steam client version (build number or date): Dec 15 2022, 21:27:25
* Distribution (e.g. Ubuntu): ROSA
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I launch a CS:GO game, the "Launcher Error" error appears:
FATAL ERROR: Failed to connect with local Steam Client process!

#### Steps for reproducing this issue:

1. Launch Steam
2. Enable forced use of Steam Play in CS:GO
3. Run CS:GO

**Comment by kisak-valve** [comment]
Hello @Geworge, running CS:GO with Proton is not supported. Unofficially, that is being tracked at https://github.com/ValveSoftware/Proton/issues/2704.
