### ISSUE TITLE
Tries to edit network connections on launch

### ISSUE THREAD

**Issue by LinAGKar** [ValveSoftware/steam-for-linux#9145]
#### Your system information

* Steam client version (build number or date):  Dec 15 2022, kl 21:27:25
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Datorinformation:
    Tillverkare: PK
    Modell: Metapod_RR
    Formfaktor: Laptop
    Ingen tryckinmatning upptäckt

Processor:
    CPU-leverantör: AuthenticAMD
    CPU-märke: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
    CPU-familj: 0x17
    CPU-modell: 0x18
    CPU Stepping: 0x1
    CPU-typ: 0x0
    Hastighet: 2300 MHz
    8 logiska processorer
    4 fysikprocessorer
    HyperThreading:  Stöds
    FCMOV:  Stöds
    SSE2:  Stöds
    SSE3:  Stöds
    SSSE3:  Stöds
    SSE4a:  Stöds
    SSE41:  Stöds
    SSE42:  Stöds
    AES: Stöds
    AVX: Stöds
    AVX2: Stöds
    AVX512F: Stöds inte
    AVX512PF: Stöds inte
    AVX512ER: Stöds inte
    AVX512CD: Stöds inte
    AVX512VNNI: Stöds inte
    SHA: Stöds
    CMPXCHG16B: Stöds
    LAHF/SAHF: Stöds
    PrefetchW: Stöds inte

Operativsystemversion:
    "openSUSE Tumbleweed" (64 bitar)
    Kernelnamn: Linux
    Kernelversion: 6.1.8-1-default
    X Serverleverantör: SUSE LINUX
    X Serverversion: 12201007
    X Window Manager: KWin
    Version av Steam Runtime: steam-runtime_0.20221019.0

Grafikkort:
    Drivrutin:  AMD AMD Radeon Vega 10 Graphics (raven, LLVM 15.0.7, DRM 3.49, 6.1.8-1-default)
    Version av drivrutin:  4.6 (Compatibility Profile) Mesa 22.3.3
    OpenGL-version: 4.6
    Skrivbordets färgdjup: 24 bitar per pixel
    Skärmens uppdateringshastighet: 59 Hz
    Leverantörs-ID:  0x1002
    Enhets-ID:  0x15d8
    Revision ej upptäckt
    Antal skärmar:  1
    Antal logiska grafikkort:  1
    Primär skärmupplösning:  1920 x 1080
    Skrivbordsupplösning: 1920 x 1080
    Primär skärmstorlek: 13.39" x 7.48" (15.31" diag)
 34.0cm x 19.0cm (38.9cm diag)
    Primär VRAM: 2048 MB

Ljudkort:
    Ljudenhet: ATI R6xx HDMI

Minne:
    RAM:  30019 MB

VR-hårdvara:
    VR-headset: Inget upptäckt

Övrigt:
    Gränssnittsspråk:  Svenska
    SPRÅK: sv_SE.UTF-8
    Totalt tillgängligt hårddiskutrymme:  512116 MB
    Största lediga hårddiskblock:  321440 MB

Lagring:
    Antal SSD-diskar: 1
    SSD-storlekar: 1000G
    Antalet hårddiskar: 0
    
#### Please describe your issue in as much detail as possible:
Whenever Steam is launched, it tries to edit the network connections. Don't know what exactly it's trying to do, but a dialog like [this](https://bugzilla.suse.com/attachment.cgi?id=861447) is opened whenever Steam is launched, if the network is setup to be available for all users.

**Comment by kisak-valve** [comment]
Hello @LinAGKar, this issue is already being tracked at #7856. Closing as a duplicate.
