### ISSUE TITLE
Guide cord mappings do not work on wayland

### ISSUE THREAD

**Issue by zany130** [ValveSoftware/steam-for-linux#9146]
#### Your system information

* Steam client version (build number or date): Jan 27
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
on Wayland guide chord mappings (guide button plus some other button) do not work (ex: there is a default mapping for guide + left stick up for volume up)

on X11 this works fine

workaround, for now, is to use something like https://github.com/sezanzeb/input-remapper to do those mapping

#### Steps for reproducing this issue:

1. Enable the default guide chord mapping or create a new one
2. Press the guide button + the corresponding key 
3. nothing happens

**Comment by eathtespagheti** [comment]
I can confirm that the issue is present on Gnome + Wayland

**Comment by XDM-Inc** [comment]
> workaround, for now, is to use something like https://github.com/sezanzeb/input-remapper to do those mapping

First time wayland user here having the same issue, whats that app supposed to do? can i make can i map the controller chords to the actions again?

**Comment by zany130** [comment]
seems to have been fixed on plasma 6.1

**Comment by Nano-Ocelot** [comment]
On Plasma 6.1.2 here and it doesn't work for me at all.

**Comment by AndrewAmmerlaan** [comment]
Plasma 6 is not by itself enough to fix the issue, you'll also need an xwayland compiled with support for libei.

**Comment by XDM-Inc** [comment]
One thing I noticed is that after you press the cord combo it pops up a remote desktop confirmation which does not remember so if you either plug it out or reboot the computer or close your session it will ask you all over again which pops up in games and is really distracting. I believe kde is well aware of this already as me along with other people have opened up bug reports on it
