### ISSUE TITLE
Steam dont work on Linux Mint 21 - Fatal Error cant load steam.ui.so

### ISSUE THREAD

**Issue by HerrUntermoser** [ValveSoftware/steam-for-linux#9151]
- Linux Mint 21 Cinnamon
- Graphic card is an AMD RX 6600
* Steam client version: Latest from the Ubuntu Repository
* Distribution: Linux Mint 21
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

I have installed Steam with Synaptic. Try to start the Client ends with a "Fatal Error: Failed to load steam.ui.so"

The Flatpak version works, but I can't choose the Steam library folder

**Comment by kisak-valve** [comment]
Hello @HerrUntermoser, if you run `steam` from a terminal, does it give a better hint to ponder?

Does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 22.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

**Comment by HerrUntermoser** [comment]
Thanks for the hint
I found and fixed the first problem: LIBPNG12 is not installed (normally outdated and not longer supported by Ubuntu and Linux Mint)

Now it starts with an empty grey window and gives my this error:
!! Steam controller device opened for index 0.
steamwebhelper.sh[46039]: Runtime for steamwebhelper: defaulting to /home/herruntermoser/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[46039]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1674790765)
Installing breakpad exception handler for appid(steam)/version(1674790765)

(steam:45860): GLib-GObject-CRITICAL **: 15:31:18.910: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:45860): GLib-GObject-WARNING **: 15:31:18.911: instance with invalid (NULL) class pointer

(steam:45860): GLib-GObject-CRITICAL **: 15:31:18.911: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(steam:45860): GLib-GObject-CRITICAL **: 15:31:18.911: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2023-01-30 15:31:18] Shutdown

**Comment by kisak-valve** [comment]
The libpng 1.2 dependency should be provided by the LD_* style Steam runtime on newer systems which is unpacked as part of Steam's startup. It does not need to be installed as a system package.

A grey window sounds like libcef failed to initialize. Those terminal spew lines don't give a hint to what's happening there. Maybe check `cef_log.txt` `steamwebhelper.log`, and `webhelper.txt` in `~/.steam/root/logs` for any libcef-specific hints?

**Comment by HerrUntermoser** [comment]
There is no cef_log or webhelper.txt

Does this error Message from the terminal helps?

Loaded SDL version 2.27.0-p7692409
Gtk-Message: 10:33:00.230: Failed to load module "gail"
Gtk-Message: 10:33:00.231: Failed to load module "atk-bridge"
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xec5059c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xec5041f0

(steam:4054): Gtk-WARNING **: 10:33:00.236: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'

(steam:4054): Gtk-WARNING **: 10:33:00.238: Im Modulpfad »adwaita« konnte keine Themen-Engine gefunden werden,
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
steamwebhelper.sh[4092]: Runtime for steamwebhelper: defaulting to /home/herruntermoser/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1674790765)
steamwebhelper.sh[4092]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported

**Comment by TTimo** [comment]
I'd recommend purging Ubuntu's steam package and trying to install Valve's official version instead: https://repo.steampowered.com/steam/

**Comment by HerrUntermoser** [comment]
Thanks for your help, but I give up on it. No matter which version I take after the update Steam crashes and presents only a gray window. Some dependency is probably not met and before I deal with the original drivers from AMD for my RX6600 (which I do not need, the Linux kernel driver works flawlessly )I just stay with the Flatpak.

**Comment by them3x** [comment]
I'm also having a similar problem with Steam on my I3wm, I'm using an RX6600, this is the error message: (steam:64274): LIBDBUSMENU-GLIB-WARNING **: 14:10:59.525: Trying to remove a child that doesn't believe we're its parent.
BuildCompleteAppOverviewChange: 327 apps
RegisterForAppOverview 1: 14ms
RegisterForAppOverview 2: 15ms
ExecCommandLine: "'/home/messias/.local/share/Steam/ubuntu12_32/steam'"
steamwebhelper.sh[64631]: Runtime for steamwebhelper: defaulting to /home/messias/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[64631]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
BuildCompleteAppOverviewChange: 327 apps
RegisterForAppOverview 1: 10ms
RegisterForAppOverview 2: 10ms
[2023-07-18 14:11:16] Shutdown
Steam cannot start.. it tries to open but fails then automatically closes and tries to restart.

I've already tried reinstalling, purging.. but nothing seems to work. I believe that in some update they might have included something in the code that is causing this problem.
