### ISSUE TITLE
Friends list (browser) is just black.

### ISSUE THREAD

**Issue by mathew2214** [ValveSoftware/steam-for-linux#9154]
#### Your system information

* Steam client version (build number or date):  steam client beta jan 31 2023
* Distribution (e.g. Ubuntu): Debian 12
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: yes

i cannot access the friends tab (browser). its just a black box.  worked yesterday, not today. 

#### Steps for reproducing this issue:

1. open friends tab
2. see its just a black box
3. try to use no-browser as workaround
4. Valve no longer allows no-browser
5. become very upset.

furthermore, trying to close the black friends screen just crashes LXDE with the error
 `lxpanel[12379]: segfault at 0 ip 00007f4b5c6af72d sp 00007ffebcd75b68 error 4 in libc.so.6[7f4b5c57d000+155000]
[  526.367728] Code: c0 48 39 c6 0f 42 c6 c5 f8 77 c3 66 90 c5 f9 6e fe 89 f8 c4 e2 7d 78 ff c5 f9 ef c0 c1 e0 14 3d 00 00 00 fe 0f 87 39 02 00 00 <c5> fe 6f 0f c5 fd 74 f1 c5 fd d7 ce 85 c9 0f 84 8f 00 00 00 c5 c5
`

**Comment by kisak-valve** [comment]
Hello @mathew2214, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, can you check if there's any interesting hints in the `cef_log.txt`, `steamwebhelper.log`, or `webhelper.txt` log files found in `~/.steam/root/logs/`?

**Comment by mathew2214** [comment]
here's the requested log files and system info as a multi-file gist.
https://gist.github.com/mathew2214/ca4fd7513e9c40eac6f45e5b68d26b3a

**Comment by daveknippers** [comment]
yep. that's a black screen.

**Comment by pizzadude** [comment]
I have the same issue.

Fedora 37 KDE
Steam flatpak
Intel iGPU

**Comment by kisak-valve** [comment]
Thanks, I was able to reproduce the issue here was well, but I didn't find anything useful to troubleshoot this further.

Upon starting the Steam client, the Friend's list window does open along with the main window, shows the loading animation, then despawns. When telling it to show the Friend's list after that from the dropdown menu, then we see a solid black window.

We'll need a Steam dev to look into this further.

**Comment by Metal-spoon** [comment]
Can confirm the same issue on fedora 37 KDE wayland.
Also on steam beta, native, not flatpak.

**Comment by mathew2214** [comment]
any chance we could just get re-enable no-browser support until a proper fix arrives?

**Comment by InventorXtreme** [comment]
I am also having the same issue on normal steam on both bspwm and plasma. I am on stable steam.

**Comment by kisak-valve** [comment]
This issue appears to have been resolved. Please retest.

**Comment by Metal-spoon** [comment]
> This issue appears to have been resolved. Please retest.

Seems fixed on my end, thanks for the quick fix!

**Comment by mathew2214** [comment]
the friends windows being just black is now fixed. 
i am still getting the issues when trying to right-click Steam in the taskbar of LXDE though. 
no other application is giving LXDE these issues.
