### ISSUE TITLE
Hardware survey misclassifies HDDs as SSDs

### ISSUE THREAD

**Issue by 4censord** [ValveSoftware/steam-for-linux#9155]
#### Your system information

* ![image](https://user-images.githubusercontent.com/49623362/216063861-ceafbbcc-5478-4b25-83b4-7e59f33174ff.png)
* Arch Linux, `Linux thearch 6.1.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 Jan 2023 21:07:04 +0000 x86_64 GNU/Linux`
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The hardware survey misclassifies my some of my hard disk as SSDs

#### Steps for reproducing this issue:

Get prompted for the hardware survey, see 

```
Storage:
    Number of SSDs: 5
    SSD sizes: 18T,18T,1920G,1000G,0B
    Number of HDDs: 0
```

![image](https://user-images.githubusercontent.com/49623362/216061645-459cb90f-5c09-469d-b83c-74cfdfb74096.png)

My disk setup is as follows:

SSD, 2Tb, Main system disk. This is where the Steam Library lives
SSD, 1Tb
2x HDD 18Tb, in a BTRFS Raid 1

I also do not have a disk that is 0B big.

On request, I can provide the hardware survey data.

**Comment by kisak-valve** [comment]
Hello @4censord, this issue is already being tracked at #8966. Closing as a duplicate.

**Comment by 4censord** [comment]
Oh, I didn't find that one. Sorry for the spam.
