### ISSUE TITLE
Steam Input doesn't work on EA games

### ISSUE THREAD

**Issue by Rekt3y** [ValveSoftware/steam-for-linux#9157]
#### Your system information

* Steam client version (build number or date): 2023.02.02
* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Expected behaviour: Steam Input working in titles that use the EA launcher, with the DualSense working properly.

Observed behaviour: Steam Input doesn't work in titles that use the EA launcher, resulting in controllers not being detected. Disabling Steam Input resolves controller detection, but now analog trigger support doesn't work for DualSense controllers, only for Xbox controllers. The triggers act like a second set of shoulder buttons (like on Switch Pro controllers).

For some reason. removing the udev rules brings back analog trigger support for DualSense controllers, but that results in having to keep Steam Input support off for PlayStation controllers. Otherwise, the DualSense doesn't get detected by any games (including titles like Sonic Frontiers, where Steam Input already worked flawlessly before udev rule removal)

#### Steps for reproducing this issue:
1. Connect a DualSense
2. Enable PlayStation configuration support for an EA title (for example NFS Heat)
3. Launch the game

**Comment by kisak-valve** [comment]
Hello @Rekt3y, we're tracking issues with games run with Proton in the Proton issue tracker. This particular issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/4009. Closing as a duplicate.
