### ISSUE TITLE
segfault in gldriverquery and tons of X errors since latest update

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/steam-for-linux#9163]
#### Your system information

* Steam client version (build number or date): Jan 31 2023, at 19:10:17
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When starting Steam gldriverquery segfaults multiple times.

In addition, the log is continuously spammed by X errors until Steam is closed again.

X errors:
```
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Steam: An X Error occurred
Feb 02 17:48:11 domi-pc steam.desktop[16870]: X Error of failed request:  BadWindow (invalid Window parameter)
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Major opcode of failed request:  20 (X_GetProperty)
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Resource id in failed request:  0x0
Feb 02 17:48:11 domi-pc steam.desktop[16870]: Serial number of failed request:  9
Feb 02 17:48:11 domi-pc steam.desktop[16870]: xerror_handler: X failed, continuing
```

gldriverquery segfault: 
[steam_segfault.txt](https://github.com/ValveSoftware/steam-for-linux/files/10571326/steam_segfault.txt)

Steam system information:
[steam_system_info.txt](https://github.com/ValveSoftware/steam-for-linux/files/10571337/steam_system_info.txt)

#### Steps for reproducing this issue:

1. Start Steam
2. Wait a bit
3. Close Steam

**Comment by kisak-valve** [comment]
Hello @DomiStyle, this issue is already being tracked at #8853. Feel free to add your findings to the older issue report.

Closing as a duplicate.

**Comment by DomiStyle** [comment]
Thanks, I'm going to open a separate issue for the X11 part since that seems to not be part of the issue you linked.
