### ISSUE TITLE
Steam Link Flatpak crash on mouse scroll

### ISSUE THREAD

**Issue by arcolvin** [ValveSoftware/steam-for-linux#9165]
#### Your system information

* Steam client version (build number or date): Steam Link Version 1.2.0.241 (FlatPak)
* Steam Streaming Source Version: 1675222618
* Distribution (e.g. Ubuntu): Fedora 37 (Gnome 43.2 / Wayland)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When using the Steam Link FlatPak most seems to work as intended, however scrolling on a mouse wheel will cause the Steam Link app to freeze or crash and restart.

Other interactions such as navigating menus or launching games all seem to work, but as soon as the mouse wheel is scrolled the app goes down.

Here are some logs from the streaming client. 

[Some logs from the Steam Link system](https://gist.github.com/arcolvin/433db3e75dbcf9b0e451895b6c165954#file-gistfile1-txt).

#### Steps for reproducing this issue:

1. Open the flatpack Steam Link app
2. Connect to remote system
3. Scroll Mouse wheel
4. App crashes and restarts or freezes until Gnome asks if the user wants to force close or wait.

**Comment by kisak-valve** [comment]
Hello @arcolvin, feedback on the Steam Link app is being handled on the forums and is not tracked here. Please post this feedback in https://steamcommunity.com/app/353380/discussions/10/.

Closing as out of scope for this issue tracker.
