### ISSUE TITLE
Steam client fails to start: "SteamClient.Auth.GetLoginUIStyle is not a function"

### ISSUE THREAD

**Issue by Dncnsnwdn** [ValveSoftware/steam-for-linux#9166]
Arch Linux, client is the one pushed out on Feb 1st, not the beta, system is up-to-date.

With the new client, I've been having trouble starting any games. (I suspect this is unrelated, but included is the output from Euro Truck Simulator, in case it contains relevant information. "GetSteamRealm returned failure code 12" and "Don't know Steam universe. Order of init bug?" seem to be common to all the games which don't run.) I was about to file this issue, but before doing so, and running out of ideas, I tried clearing the download cache.

When the client restarts, I get a window titled "Steam Sign In" which says:

`Error Reference: Client Login_7728431_d0c8a14982dcf3ba

SteamClient.Auth.GetLoginUIStyle is not a function`

Steps for reproducing: Try to run the Steam client.
[ETSOutput.txt](https://github.com/ValveSoftware/steam-for-linux/files/10573852/ETSOutput.txt)

**Comment by kisak-valve** [comment]
Hello @Dncnsnwdn, does completely closing Steam, then running `steam-runtime --reset` from a terminal have an effect? This should tell Steam to try to run as if it was the first time it has run on your system.

**Comment by Dncnsnwdn** [comment]
This is embarrassing. I just tried that, seconds before you replied. Yes, it does. And it seems to have fixed the original issue too.

Sorry for bothering you.
