### ISSUE TITLE
New Big Picture Mode exceedingly slow on Nvidia

### ISSUE THREAD

**Issue by noammor** [ValveSoftware/steam-for-linux#9170]
#### Your system information

* Steam client version (build number or date): 3.2.2023
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] tested both
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

It runs at maybe 2 fps. Games work, of course, so it's not some driver issue.

#### Steps for reproducing this issue:

1. Have a RTX 2080 card with the latest drivers
2. Start Big Picture Mode

**Comment by shadywack** [comment]
Same issue, also went to BPM's settings->display->Advanced, Disable GPU Blocklist, restarted Steam, no performance gain whatsoever.

RTX 3080 - 525.85.05 drivers on Pop OS, also tested same driver version on Gentoo with ~amd64, also tested Manjaro, Nobara, issue present across all distros.

Hardware acceleration on nVidia is not working.

**Comment by kisak-valve** [comment]
Hello @noammor, this issue is already being tracked at #8918. Closing as a duplicate.
