### ISSUE TITLE
Steam client re-download gigabytes of game updates almost every day but in reality it is no game update.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ValveSoftware/steam-for-linux#9174]
#### Your system information

* Steam client version (build number or date):  latest
* Distribution (e.g. Ubuntu): madjaro / arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam client re-download gigabytes of game updates almost every day but in reality it is no game update . 
For example to play NMS steam client re-download 2.4 gigabytes . It happens not every restart of steam but in random moment 
every day or every 2 days. 

Tests which i tried: 
1) startup steam 
2) see that it download update and wait until it finish 
3) shudown steam client 
4) start steam client and see that download update not started 
5) play game some hours after it  stop game.
6) shudown steam client 
7) next day stratup steam and  for this game update again started to download , So endless loop

What i already tried : 
1) Tried to clear download cache - not solved 

#### Steps for reproducing this issue:

1. Play steam game
2. stop play game
3. shutdown steam client
4. wait next day 
5. Start steam client and see that it is again download gigabytes of data

**Comment by kisak-valve** [comment]
Hello @jpVm5jYYRE1VIKL, this reads like #8076. The next time you see this, can you take a look at the Downloads view of Steam and cehck if there's a green disk activity graph along with the vertical blue bars for network activity?

If there isn't disk activity being shown during that 2.4GB update, then you're seeing a shader pre-cache update. It might be interesting to attach `~/.local/share/Steam/logs/shader_log.txt` as a file to ponder.

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
