### ISSUE TITLE
unsupported authentication and black screen

### ISSUE THREAD

**Issue by PaddyFr** [ValveSoftware/steam-for-linux#9177]
Distribution: Debian 11 with updates (kernel 5.10.0-21-amd64) and XFCE (4.16), additional winehq-devel (8.0) repository and steam (1.0.0.68-1) installed.

When I try to run "Return to Monkey Island" the game is starting with music and a black screen. In the log it shows many errors like this:

"Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported"

I tried to enable/disable Steam Play in the client settings. I enabled/disabled the beta client. I set display as ":0" and ":0,0" and i used "xhost +". I also ran "steam -no-cef-sandbox -cef-single-process" but the black screen persists.

Log with defaults: https://gist.github.com/PaddyFr/5b7d5b3c904ab645f432cefd2202a467
Log with the above parameters: https://gist.github.com/PaddyFr/00e4d533178df600ad929e449a855f9b

**Comment by kisak-valve** [comment]
Hello @PaddyFr, we're tracking issues with games run with Proton in the Proton issue tracker, also we're using one issue report per unofficially supported game title. Usually, I'd transfer this issue report to https://github.com/ValveSoftware/Proton/issues/6276, but there's a very high chance that you've actually encountered https://gitlab.freedesktop.org/mesa/mesa/-/issues/7360 as a video driver issue.

**Comment by kisak-valve** [comment]
It should be noted that https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20693 already landed in mesa git main to resolve that issue, but it's not lined up for backport to the point releases, so it's expected that most mesa users will get that with mesa 23.1.0.
