### ISSUE TITLE
Big picture do not display on Steam Link iPad

### ISSUE THREAD

**Issue by mohdyusuf** [ValveSoftware/steam-for-linux#9180]
#### Your system information

* Steam client version (build number or date): Feb 3 2023, at 3:49:51
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: Yes and both (tried on official release too)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I hit "Start Playing" button on iPad iOS 16.3, I expect to see the big picture video on iPad. Mouse is seen on iPad.

I only see black screen on iPad, while Linux monitor displays big picture is fine.

#### Steps for reproducing this issue:

1. On Steam Link iOS, click "Start Playing"
2. Observe black screen on iPad, except mouse pointer is there.

**Comment by kisak-valve** [comment]
Hello @mohdyusuf, issues with the Steam Link app are being tracked on the forums. You'll want to post this feedback in https://steamcommunity.com/app/353380/discussions/7/ for a Steam Link dev to ponder.

Closing as out of scope for this issue tracker.

**Comment by mohdyusuf** [comment]
Btw, @kisak-valve , I forgot to mention that the display on Steam Link iOS works fine if the PC is windows. The issue is seen only on my Fedora PC.
