### ISSUE TITLE
New Big Picture mode conflicts with Yakuza 5

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-for-linux#9181]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Fedora 36 w/X11 and Nvidia
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If I bring up the overlay while in the game just once, the next time the game loads a new level or room, the whole game freezes. Screen stays black, all I can do is quit with Alt+F4. Doesn't happen, if I never bring up the new BP GUI.

If I do anything but return to the game from the BP GUI, chances are high it'll just switch to an otherwise empty screen apart from the bottom menu row. I can hear menu sounds but nothing changes visually. Can only exit out via Alt+F4. Usually it'll drop to desktop - apparently - but the BP process is still there, invisible, often grabbing inputs.

Steam then keeps launching into an invisible BP mode until I reboot.

#### Steps for reproducing this issue:

1. Be in the game world, playing normally
2. Bring up the new Steam BP overlay (via gamepad? haven't tried KB) then return to the game
3. Cause the game to load a new room or something so it would bring up the loading screen

**Comment by kisak-valve** [comment]
Hello @DanMan, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4625#issuecomment-1418290175.

**Comment by DanMan** [comment]
I've had this happen in another game the other day (Kena: Bridge of Spirits), which suggests that this isn't a game specific issue.
