### ISSUE TITLE
Controller input broken with Remote Play if game is started without BPM

### ISSUE THREAD

**Issue by mohdyusuf** [ValveSoftware/steam-for-linux#9182]
#### Your system information

* Steam client version (build number or date): Feb 3 2023, at 3:49:51
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: Yes and both (tried on official release as well)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When launching game shortcut under the "Steam Link" app, instead of clicking "Start Playing" (big picture) will break the gamepad controller support in the game.

However, if I launch the Big Picture first, gamepad controller works fine in the game (steam link)

#### Steps for reproducing this issue:

1. Start Steam Link, DO NOT press "Start Playing" instead launch the game shortcut directly at bottom of the app. For me "Lego Star Wars"
2. Gamepad button works in menu, but not working in game.

**Comment by kisak-valve** [comment]
For transparency, the difference between #9180 and this issue report is that the issue you've described here has a working and broken case with the variable between the two being whether or not Big Picture Mode is already running on the host/server side of the Remote Play connection. I've adjusted the title to focus on that.

**Comment by mohdyusuf** [comment]
> For transparency, the difference between #9180 and this issue report is that the issue you've described here has a working and broken case with the variable between the two being whether or not Big Picture Mode is already running on the host/server side of the Remote Play connection. I've adjusted the title to focus on that.

Sure thing, thank you. 🙏

**Comment by Disk1of5** [comment]
really do think that #9150 and this are the same bug.. but in my case even in BPM remote play from Linux to Linux is broken
@kisak-valve can you also add Distro Family: Ubuntu please to the tags

**Comment by smcv** [comment]
Please re-test this now that #9150 is fixed? (I don't know whether that will help here or not, but it might.)

**Comment by kisak-valve** [comment]
Closing pending feedback.
