### ISSUE TITLE
Steam is broken on all Kubuntu systems, Kubuntu 22.04 and Kubuntu 22.10. 

### ISSUE THREAD

**Issue by lowlux** [ValveSoftware/steam-for-linux#9183]
Steam is down on all Kubuntu systems, Kubuntu 22.04 and Kubuntu 22.10. 

Clicking "PLAY" any game results in noting, no errors, no noting. the play button turns green. 

This is with different  protons and different games, and i've deleted all the games and started over, same results

Rust would pull up a blank window and shut off the CPU fan and make a nasty noise, but it's also now doing the green play button on the fresh install 

I've installed a fresh kubuntu and with different drivers it's the same result, 

I have a NVIDIA 3080 12 core AMD 

RUST and every game i have was playable 36 hours ago, and have since been unplayable

Seems steam released a nasty update.

**Comment by kisak-valve** [comment]
Hello @lowlux, if you completely close Steam, then run `steam` from a terminal, are there any hints in the terminal spew? Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

`[Game] shut off the CPU fan`
Steam and all games run from it are always run as a regular user. They shouldn't ever have the ability to directly affect a system cooling system beyond using system resources like any other application.

Your title does not match the symptoms you have described. "Down" is general read as failing to start or unable to login to Steam's servers. Please rephrase the issue report title.

**Comment by lowlux** [comment]
dux@dux-System:~$ flatpak run com.valvesoftware.Steam
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/dux/.var/app/com.valvesoftware.Steam
DEBUG:root:Checking input devices permissions
WARNING:root:Missing permissions for input devices
INFO:root:Overriding TZ to America/New_York
steam.sh[2]: Running Steam on org.freedesktop.platform 22.08 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[77]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
[2023-02-06 23:50:37] Startup - updater built Jan 31 2023 19:05:55
[2023-02-06 23:50:37] Startup - Steam Client launched with: '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
[2023-02-06 23:50:37] Loading cached metrics from disk (/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
[2023-02-06 23:50:37] Using the following download hosts for Public, Realm steamglobal
[2023-02-06 23:50:37] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-02-06 23:50:37] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-02-06 23:50:37] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-02-06 23:50:37] Verifying installation...
[2023-02-06 23:50:37] Verification complete
Loaded SDL version 3.0.0-765-gc4db0725e
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf3f0f8f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf3f0e1c0
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[149]: Runtime for steamwebhelper: defaulting to /home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[149]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[149]: CEF sandbox already disabled
CAppInfoCacheReadFromDiskThread took 22 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed

(steam:146): Gtk-WARNING **: 23:50:48.440: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 380 bytes.
BRefreshApplicationsInLibrary 1: 0ms
roaming config store loaded successfully - 380 bytes.
migrating temporary roaming config store
GetWin32Stats: restoring previous glx context
ExecCommandLine: "'/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'"
System startup time: 12.66 seconds
BuildCompleteAppOverviewChange: 182 apps
RegisterForAppOverview 1: 1ms
RegisterForAppOverview 2: 1ms
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
BuildCompleteAppOverviewChange: 182 apps
RegisterForAppOverview 1: 1ms
RegisterForAppOverview 2: 1ms
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
PermissionError: [Errno 1] Operation not permitted: '../drive_c' -> '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/dist/./share/default_pfx/dosdevices/c:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/proton", line 1522, in <module>
    g_proton.extract_tarball()
  File "/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/proton", line 450, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/dist/./share/default_pfx/dosdevices/c:'
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1172470, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1172470, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1172470 -- /home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Apex Legends/EasyAntiCheat_launcher.exe' -steam\0
Game process added : AppID 1172470 "/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1172470 -- /home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Apex Legends/EasyAntiCheat_launcher.exe' -steam", ProcID 529, IP 0.0.0.0:0
chdir /media/dux/T7 Shield/SteamLibrary/steamapps/common/Apex Legends
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 533 != 530, skipping destruction (fork without exec?)
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 1172470, ActionID 1] : LaunchApp changed task to Completed with ""
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 2206, in makelink
    os.symlink(tarinfo.linkname, targetpath)
PermissionError: [Errno 1] Operation not permitted: '../drive_c' -> '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/dist/./share/default_pfx/dosdevices/c:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/proton", line 1522, in <module>
    g_proton.extract_tarball()
  File "/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/proton", line 450, in extract_tarball
    tar.extractall(path=self.dist_dir)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2124, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2217, in makelink
    targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2118, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2147, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 22] Invalid argument: '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0/dist/./share/default_pfx/dosdevices/c:'
Game process removed: AppID 1172470 "/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1172470 -- /home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/dux/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Proton 7.0'/proton waitforexitandrun  '/media/dux/T7 Shield/SteamLibrary/steamapps/common/Apex Legends/EasyAntiCheat_launcher.exe' -steam", ProcID 529 
ThreadGetProcessExitCode: no such process 625
ThreadGetProcessExitCode: no such process 624
ThreadGetProcessExitCode: no such process 623
ThreadGetProcessExitCode: no such process 531
ThreadGetProcessExitCode: no such process 530
Uploaded AppInterfaceStats to Steam

**Comment by lowlux** [comment]
Booted steam, tried to run apex legends

**Comment by kisak-valve** [comment]
In general, we're tracking issues with games run with Proton in the Proton issue tracker. 

Proton has a [long history of being finicky](https://github.com/ValveSoftware/Proton/search?q=NTFS+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues) when used with NTFS partitions. Your symptoms match this behavior.

The general recommendation is to use a Linux native filesystem with Proton. That said you could give some of the workarounds mentioned in https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a try.

Closing as not a Steam client issue.
