### ISSUE TITLE
Steam does not show the GUI with 2 graphic cards on Ubuntu

### ISSUE THREAD

**Issue by glad2os** [ValveSoftware/steam-for-linux#9185]
#### Your system information

* Steam client version: Jan 31 2023, at 19:10:17
* Distribution (e.g. Ubuntu): Ubuntu 22.04.01 LTS, System76 Gazelle
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Opening a steam launcher on the X11 laptop with 2 graphics cards  

$ sudo lshw -C display
[sudo] password for glad2os-laptop: 
  *-display                 
       description: VGA compatible controller
       product: GA107M [GeForce RTX 3050 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=nvidia latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:90-8f iomemory:a0-9f irq:167 memory:81000000-81ffffff memory:900000000-9ffffffff memory:a00000000-a01ffffff ioport:2000(size=128) memory:c0000-dffff
  *-display
       description: VGA compatible controller
       product: Alder Lake-P Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 0c
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:166 memory:83000000-83ffffff memory:90000000-9fffffff ioport:1000(size=64) memory:c0000-dffff memory:880000000-886ffffff memory:a20000000-affffffff

When I open a steam launcher from the "Show applications" button, it does launch, but not showing the GUI.
glad2os-laptop@system76-pc:~$ ps auxc | grep "steam"
glad2os+    9177 13.6  0.0      0     0 ?        Zl   15:15   0:00 steam <defunct>
Right after the
glad2os-laptop@system76-pc:~$ kill -9 9177

I may launch the steam from the terminal this way

glad2os-laptop@system76-pc:~$ steam
steam.sh[9550]: Running Steam on ubuntu 22.04 64-bit
steam.sh[9550]: STEAM_RUNTIME is enabled automatically
setup.sh[9708]: Steam runtime environment up-to-date!
steam.sh[9550]: Steam client's requirements are satisfied
[2023-02-07 15:16:48] Startup - updater built Jan 31 2023 19:05:55
[2023-02-07 15:16:48] Startup - Steam Client launched with: '/home/glad2os-laptop/.local/share/Steam/ubuntu12_32/steam'........
Could not connect to X session manager: None of the authentication protocols specified are supported
.....
And the GUI works as should. 

Or I may do this:

glad2os-laptop@system76-pc:~$ echo $DISPLAY
:1
glad2os-laptop@system76-pc:~$ DISPLAY=:1 steam
steam.sh[10560]: Running Steam on ubuntu 22.04 64-bit
steam.sh[10560]: STEAM_RUNTIME is enabled automatically
setup.sh[10709]: Steam runtime environment up-to-date!
steam.sh[10560]: Steam client's requirements are satisfied

And everything will work as should
 
 glad2os-laptop@system76-pc:~$ uname -a
Linux system76-pc 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

#### Steps for reproducing this issue:

1. Open the "Show Application"
2. Click on the steam
3. steam launched in processes, but do not launch the GUI.
4. Close steam via kill -9 PID
5. Open a terminal with the DISPLAY=:1 steam
6. Steam GUI works as should

**Comment by kisak-valve** [comment]
Hello @glad2os, you've described the issue being tracked at #8179.

Closing in favor of the older issue report.
