### ISSUE TITLE
Bubble with topic content from the Steam forums just doesn't dissapear for a long time.

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/steam-for-linux#9186]
* Steam client version (build number or date): 8/2/2023
* Distribution (e.g. Ubuntu): Arch Linux based EndeavourOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* PC Info: https://gist.github.com/KibaGasteiz/f90ab0f1bd5509e4139fa99b79c1c067

#### Steps for reproducing this issue:

1. Go to the forums and enter one topic.
2. Look at the right side, there is a "popular topics" section.
3. Just hover the cursor on them and if any of them have a lot of text as content the thing just stays for a very long time, terrible performance and we should have native bubbles instead.
4. This issue has been happening for years, but never find an issue opened here for it.

![Captura desde 2023-02-08 00-51-15](https://user-images.githubusercontent.com/44957566/217394934-65f1f1d8-c485-4661-971a-e3df3f11a7db.png)
![Captura desde 2023-02-08 00-51-36](https://user-images.githubusercontent.com/44957566/217394947-612b3c64-05b8-46d2-848e-defa052bf2f0.png)
![Captura desde 2023-02-08 00-52-56](https://user-images.githubusercontent.com/44957566/217394957-57211e4d-77d6-437f-a92e-0ccc5fb1f15b.png)
![Captura desde 2023-02-08 01-01-08](https://user-images.githubusercontent.com/44957566/217394964-4535ad6e-15d1-4f79-b9ed-3824d77a347d.png)

**Comment by kisak-valve** [comment]
Hello @KibaGasteiz, this issue is already being tracked at #3994. Closing as a duplicate.
