### ISSUE TITLE
Library Icons disapearing

### ISSUE THREAD

**Issue by killerpi997** [ValveSoftware/steam-for-linux#9191]
#### Your system information

* Steam client version (build number or date): Jan.  31st 2023
* Distribution (e.g. Ubuntu): PopOS
* Opted into Steam client beta?:No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After playing a game or suspending computer, library icons will disappear when moved/hovered over instead of displaying their animation/slight enlargement. Sometimes it is minor and only effects the image actively being hovered, other times the library screen is blank until being swiped  with the mouse. I have attached a screenshot of the issue. 
#### Steps for reproducing this issue:

1. play a game or suspend computer
2. go to steam library and hover over icons
3. 
![EX1](https://user-images.githubusercontent.com/124887066/217809101-65759428-d686-4119-9124-099bcf102c2f.png)

**Comment by kisak-valve** [comment]
Hello @killerpi997, this is effectively the same issue as #9042. Closing in favor of the older issue report.
