### ISSUE TITLE
Installing Steam Devices for Flatpak installs steam 

### ISSUE THREAD

**Issue by lowlux** [ValveSoftware/steam-for-linux#9192]
Installing Steam Devices for Flatpak installs steam on the apt system, leaving 2 steam clients, 

Ubuntu LTS

**Comment by kisak-valve** [comment]
The distro provided variant of steam-devices recommends the steam package (https://packages.ubuntu.com/jammy/steam-devices) but does not require it as a dependency. This is a package manager issue, not a Steam client issue.

Regardless, `steam` system package is a bootstrapper, and not the full client. The relative size is negligible at about 6 MB.
