### ISSUE TITLE
steam crashes after exiting aplex legends 

### ISSUE THREAD

**Issue by lowlux** [ValveSoftware/steam-for-linux#9193]
[
![Screenshot_20230209_214459](https://user-images.githubusercontent.com/1283196/217987768-77a4a542-0fe8-437e-a4b0-1186fac33533.png)

**Comment by kisak-valve** [comment]
Hello @lowlux, if you completely close steam, then run `steam` from a terminal and reproduce the issue, are there any hints? Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kisak-valve** [comment]
Closing due to a lack of actionable information.
