### ISSUE TITLE
Rocket League shader cache full download everyday

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#9200]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Everyday, when I start Steam, it downloads Rocket League shader cache entirely, all other games don't download the whole shader cache when I start Steam.
I expect Rocket League shader cache to only update itself, instead of having to download 2.1GB everyday when I have low bandwidth.

https://i.imgur.com/D0NaNBX.jpg

#### Steps for reproducing this issue:

1. Start Steam
2. See all the shader cache downloads added in Steam
3. The Rocket League one is downloading entirely 2.1GB when all other games do the 'normal' shader cache download usually under 1MB

**Comment by kisak-valve** [comment]
Hello @Zorrototo, this feedback is consistent with the more recent feedback on #8076. Closing in favor of the older issue report.

**Comment by Zorrototo** [comment]
This issue is only with Rocket League though. I don't have the issue that all shader cache download gully again, it is only Rocket League, not any of my 25 installed Proton games. Just Rocket League.

**Comment by Plagman** [comment]
Thank you for the report and logs.

**Comment by Zorrototo** [comment]
I swear I'm not lying, it was doing that almost everyday (I don't always reboot the computer), today it downloaded a 2MB shader cache update as "expected" for a "daily" shader cache update. Did you do something on the backend since my report (I highly doubt that)?

//EDIT while writing this reply: OK I clicked the link above and I see that yes, you actually did some backend work :package: 

I love you guys :) you're my heroes.
