### ISSUE TITLE
Steam Client abnormal high GPU and CPU usage

### ISSUE THREAD

**Issue by gort818** [ValveSoftware/steam-for-linux#9207]
#### Your system information

* Steam client version (Feb 10 2023): 
* Distribution (Arch): 
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

### Log files and system information
[SysInfo gist ](https://gist.github.com/gort818/1a4de0ee57249ac6c37d55c7d629f36c)
[cef_log.txt gist ](https://gist.github.com/gort818/e4879a78f7dd910ddca7972e1f42a009)
[steamwebhelper.log gist](https://gist.github.com/gort818/c2df44ffdd6eba9a695cd8d63b6afb2f)
[webhelper.txt gist](https://gist.github.com/gort818/2d891f2ba72197b7f63037ade05858f2)

### Core Dump
[assert_20230216164429_37.zip](https://github.com/ValveSoftware/steam-for-linux/files/10762332/assert_20230216164429_37.zip)

#### Please describe your issue in as much detail as possible:

Steam client using close to 100% GPU and high cpu usage causing the client to become extremely unresponsive and laggy, games cannot be played in this state as steam is using all of my resources.

It does not always happen, sometimes it happens when the client is launched, other times it is seemingly random.

When closing steam in this state it always produces a core dump.

After a while steam returns to normal operation, but could take up to 20 mins. The issue comes back though after some time.

#### Steps for reproducing this issue:

1.  Open steam, high resource use at start or a few minutes later

### Workarounds tried
1. Turn off hardware acceleration  ( doesn't help)
2. Uninstall Steam and all it's config files  ( doesn't help)
3. Killing the plasma session and restarting steam  ( Helps only momentarily)
4. Tried stable steam release ( doesn't help)
5. Disabling Allow background shader processing ( doesn't help)
6. Running steam in small mode ( this seems to work)

**Comment by kisak-valve** [comment]
Hello @gort818, since you're using a random git commit of mesa, can you do a basic video driver sanity check by checking how Steam behaves with a recent point release of mesa?

**Comment by gort818** [comment]
I just tested with Mesa 22.3.4, it a while for the issue to show up, but yeah same issue.

**Comment by gort818** [comment]
Looks like I have a similar issue with discord on this new hardware, but setting this flag `--enable-gpu-rasterization` solved all my issues with discord.

I have now tried creating a new user, reinstalling all packages, tried different kernels, different mesa versions, different motherboard bios.

When turning off hardware acceleration the steam client itself uses 100% of my GPU.

**Comment by lflo5727** [comment]
I can confirm I also have this issue and am NOT using a git release of Mesa or opted into Steam client beta. Seems to have just started yesterday with no system/package updates (possibly something about Steam's webviews?).

Just updated all packages and still seeing it too. I am on Endeavour (basically just Arch)

**Comment by lflo5727** [comment]
Want to add to this, didn't have much a chance to test more things, but I tried launching a game (Team Fortress 2 if that matters) and the CPU usage went back down to expected.
However once I closed the game the CPU usage spiked back to 100% by the Steam process. Doesn't seem to matter where in the Steam app I am. 

Also in difference to noted above by @gort818 , I do not seem to have the same issue on Discord.

**Comment by gort818** [comment]
To rule out desktop environments I tried both Kde plasma and Gnome.. always the same  Steam starts to run at a crawl.
![Screenshot_20230219_134833](https://user-images.githubusercontent.com/9098121/219977242-40b33dda-0c2e-428b-a781-a2036402c7f4.png)

**Comment by gort818** [comment]
also noticed this when running steam from the terminal.
```
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x1
Serial number of failed request:  9
xerror_handler: X failed, continuing

```

**Comment by gort818** [comment]
Not sure how I missed it, but in the screenshot above the gpu is running PCIe gen1@1x.

Actually might be a hardware issue or an amdgpu bug and nothing wrong with steam.

Testing with `amdgpu.aspm=0`

**Comment by gort818** [comment]
Closing as not a steam issue,  setting  the kernel parameter `amdgpu.aspm=0`  solved my issue.

**Comment by lflo5727** [comment]
@gort818  Setting that kernel param did not change anything for me. Steam still sits using 100% CPU for me. 
I did not have change in hardware between when this started and beforehand.
