### ISSUE TITLE
Manage steam library folders doesn't open

### ISSUE THREAD

**Issue by rLy07** [ValveSoftware/steam-for-linux#9212]
#### Your system information

* Steam client version (build number or date): 1676680477
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Going to Settings->Download then pressing the "Steam library folders" does nothing. 
![image](https://user-images.githubusercontent.com/702570/219933151-ae453466-4d38-49bc-83b8-ae0b3e64db0a.png)

#### Steps for reproducing this issue:

1. Open Settings->Downloads
2. Press "Steam library folders"
3. Nothing happens

**Comment by andrewxc** [comment]
I have found that when I open my secondary drive containing my Library folder in the Explorer, my SSD is then recognized, and the Library activates automatically. Can't change anything, but it at least works a little.

**Comment by obi1** [comment]
Same issue here (running on Gentoo). My 2nd Library folder (where I keep all my games) keeps dissapearing from Steam every other update, so right now I am stuck with 0 games and no way to readd the library.

**Comment by rLy07** [comment]
Just to clarify, my original issue is only about the settings page not working. My library otherwise is intact and have access to all games on both of my library. Also this is still an issue after the latest update: 1676836260

**Comment by rLy07** [comment]
The latest update(1676935611) fixed it. Thank you!
