### ISSUE TITLE
Latest update broke icon and focus

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#9216]
#### Your system information

* Steam client version (build number or date): February 17 2023
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Latest beta update broke multiple things. The friend list, and other additional Steam windows (like a chat window) do not have a Steam icon I only see a cross (but I think it is the default when no icon). Also when you click a chat notification, it doesn't bring the chat window into focus, and when you think you get focus on the chat window because the cursor is blinking into the chat window, you still require to find  way to get focus FOR REAL because you could not write where the cursor blinks otherwise.

#### Steps for reproducing this issue:

1. Start Steam
2. Friend list auto opens with no icon
3. Receive a notification and click on it

**Comment by Zorrototo** [comment]
When you only have the main Steam window opened, clicking the Friends & Chat button at the bottom right corner, it opens the friend list, but it doesn't get on foreground, it opens in background.

**Comment by Bill5122** [comment]
Unsure if related, but as someone affected by https://github.com/ValveSoftware/steam-for-linux/issues/4735 while running kde wayland, the issue appears to be resolved for me.  Updating to the beta steam version and while my notifications are usually completely blacked out, they seem to work in the beta.  The downside is that sometimes the notification will not appear at all, but when it does appear it works.

**Comment by Bill5122** [comment]
Also seems like https://github.com/ValveSoftware/steam-for-linux/issues/7839 is fixed now, at least for me.

**Comment by JacobSvenningsen** [comment]
Happens on Debian running XFCE too.
Deadkeys are broken too. Scrolling behaves very differently compared to the "regular" steam window as well.
It seems like steamwebhelper processes are running in an entire different environment now

**Comment by robertc** [comment]
Seeing similar issues on Fedora.  No icon on friends window, chat windows are brought on top of the game instead of letting me just accept invites in-game like it used to.

**Comment by Zorrototo** [comment]
It seems the current beta update fixed everything on my side.

**Comment by echaskaris** [comment]
Steam chat has a steam icon, but it is grouped as steamwebhelper and not with the main steam application.
This is changed behavior, but I may like it... Maybe change the icon to a friends icon.

**Comment by Zorrototo** [comment]
Not everything is fixed, I still need to pass my mouse cursor over the text area to be able to actually write in the text area, of a chat window.

**Comment by Zorrototo** [comment]
It was kinda fixed, but we're back at square one. Clicking notifications doesn't get focus back. If friend list is opened, but in background, clicking the bottom right Friends & Chat button doesn't get the friend list back on foreground. I can't write in chat without putting my cursor over the text area.

**Comment by JacobSvenningsen** [comment]
Everything seems fixed on my end now

**Comment by Zorrototo** [comment]
Clicking Chat & Friends button brings back friend list on foreground now.
It seems I don't need to have my mouse cursor over the text area to be able to write in chat now.
Clicking notification brings the chat window on foreground now.

However, hovering your mouse on people's picture in your friend list is now broken, it tries to show the picture/mini profile card but it kinda flashes a few times and doesn't show in the end. You can also see when it flashes that a Steam icon appears for a split second in the icon task manager.
By trying to find other oddities, I found that right clicking a person's name or picture in friend list, almost fixes this bug, it then kinda works after flashing a couple times. But it is not reproducible all the time, for now it worked once and I can't re-fix it now.

**Comment by Zorrototo** [comment]
Seems to be al in order now for me. Closing.
