### ISSUE TITLE
Slow smooth scrolling, excessive CPU usage

### ISSUE THREAD

**Issue by purplebar0** [ValveSoftware/steam-for-linux#9219]
#### Your system information

* Steam client version (build number or date): ~~February 17~~ 1686379854
* Distribution (e.g. Ubuntu): Artix Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Fixed! ~~If enabled, smooth scrolling finally works in Library and Chat, but not elsewhere in the client. As a result, browsing Steam Store/Community and websites in the Overlay is choppy as it has been since the release of the client, probably.~~

There is also the Chromium issue (pre-109) that makes the scrolling speed (with smooth scrolling enabled) very slow, requiring a hack like sending multiple scroll inputs (ex. by using IMWheel).

Additionally, the CPU usage is very excessive.

#### Steps for reproducing this issue:

1. Enabled smooth scrolling in Steam interface settings
2. Restarted client
3. It works to the extent outlined in the post

**Comment by Bill5122** [comment]
Can confirm it works in library and friends list, but not in the community tab, store tab, or profile tab for me. Everywhere except the library and friends list appears to have the old non-smooth scrolling. I can confirm that the ingame overlay also has non smooth scrolling everywhere, including the friends list and browser page.

**Comment by purplebar0** [comment]
Update to the issue.

Since #7839 has been closed due to smooth scrolling itself being operational, the slow scrolling speed of smooth scrolling is still an issue.

[Mirrored from the other issue](https://github.com/ValveSoftware/steam-for-linux/issues/7839#issuecomment-1527092923):

> The current workaround is to use [IMWheel](https://wiki.archlinux.org/title/IMWheel) and configure it as such:

```
# ~/imwheelrc

# Speed up scrolling for pre-109 CEF
"^(Steam|Friends List.*)$"
    None, Up,   Button4, 2
    None, Down, Button5, 2

# Default (or else Ctrl+Scroll and such won't work in any application)
".*"
    Control_L, Up,   Control_L|Button4
    Control_L, Down, Control_L|Button5
    Control_R, Up,   Control_R|Button4
    Control_R, Down, Control_R|Button5
    Shift_L,   Up,   Shift_L|Button4
    Shift_L,   Down, Shift_L|Button5
```

Also, while smooth scrolling performs well enough that it looks smooth on my setup, CPU usage spikes too hard for what it's worth.

**Comment by ardishco-the-great** [comment]
> 

as per @kisak-valve's instructions, I've retested this problem with said workaround above and have not been able to fix this. I don't know if imwheelrc works on Wayland, so maybe it works on Xorg. More testing is needed. As of now this issue still remains, though.

**Comment by erpadmin** [comment]
scroll speed is slow for me in all sections of the client on manjaro kde.  I would prefer speed to match chrome/chromium browser scroll speed (at least as a default).

should the issue title be updated to reflect scroll speed as well?

**Comment by erpadmin** [comment]
I am attaching two screen shots, 1st at same spot in store front, 2nd after two pulls on the scroll wheel.  I think this demonstrates distance as well a scaling comparison which I think technically should be similar between the 2 but I imagine also related
Desktop -> Resolution 1440p, scaling %125
browser (left) -> 100% zoom
client (right)->Interface: scale text and icons to match monitor settings, enable smooth scrolling in web views OFF (scrolling might be slightly faster vs ON)

![Screenshot_20230702_144605](https://github.com/ValveSoftware/steam-for-linux/assets/2635831/34ded920-94a5-4bf9-a287-121a555f3cb0)
![Screenshot_20230702_144638](https://github.com/ValveSoftware/steam-for-linux/assets/2635831/5e9dce67-02db-4345-a944-724c5d1e7f55)

**Comment by erpadmin** [comment]
screenshot with enable smooth scrolling in web views ON.  compare Sons of Forest position with shot 2
![image](https://github.com/ValveSoftware/steam-for-linux/assets/2635831/b7dd7944-7f4d-4c69-b10f-eb4eb68dd034)

**Comment by CrashTD** [comment]
Would be lovely if this could get some attention. The problem of the extreme slow scrolling is still there.

**Comment by dMailonG** [comment]
Same issue here.

Steam Beta Branch: Stable Client
Steam Version: 1705108172
Steam Client Build Date: Fri, Jan 12 8:52 PM UTC -08:00
Steam Web Build Date: Fri, Jan 12 1:02 PM UTC -08:00
Steam API Version: SteamClient021

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by ardishco-the-great** [comment]
This seems like a bug in chromium being used in the Chromium Embedded Framework that Steam uses, this bug also affects stable discord and other electron apps using older electron versions that make use of Chromium 120.something (I'm not sure of the version number)

> Would be lovely if this could get some attention. The problem of the extreme slow scrolling is still there. (e.g. see #9723 as well)

I guess we'll have to wait until the next major steam update to get this fixed. It doesn't seem like they're going to do us much good here.

**Comment by tehmasterer** [comment]
Seems improved with the February 27th client update.

- **Updated embedded Chromium build in Steam, clearing path for further updates soon.**

**Comment by kisak-valve** [comment]
Closing per the last comment.
