### ISSUE TITLE
After update 1676836260 all pages are blank

### ISSUE THREAD

**Issue by Seegras** [ValveSoftware/steam-for-linux#9220]
#### Your system information

* Steam client version (build number or date): 1676836260
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Everything that's usually rendered from html isn't visible anymore, completely blank: 
![steam-bug](https://user-images.githubusercontent.com/1655796/220025879-d559d91a-3b85-4886-9f2c-a161f3f0f846.png)

This might be related to #9216

**Comment by kisak-valve** [comment]
Hello @Seegras, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

If you completely close steam, then run `steam` from a terminal, are there any hints? Also, it might be interesting to check if there any hints in `cef_log.txt`, `steamwebhelper.log`, and `webhelper.txt` in the `~/.steam/root/logs` folder.

**Comment by echaskaris** [comment]
Works in Ubuntu 22.04. I have gpu accel enabled.

**Comment by Bill5122** [comment]
Able to reproduce on gentoo.  While the steam page is in this state the steam app appears to be completely unresponsive, not even being able to drag the top bar to move the window.  I have however noticed that minimizing and unminimizing the steam page will typically fix the blacked out page.  This is on a 5700xt with kde wayland 5.27 and mesa 23 rc4.

**Comment by Seegras** [comment]
On 1676935611 it works again; but now the scaling is off for Library and Downloads (Bug #9209 ?  Looks exactly like the screenshots there in any case). 

Still you might want the System Information: 
https://gist.github.com/Seegras/b6f76230bb442ab143d63eb3caa52663
(The gist of the gist: X11, Nvidia proprietary 525.85.12 drivers, 4K resolution, 168dpi, WindowMaker)

**Comment by momumi** [comment]
I'm seeing this too on archlinux, KDE, steam-1676935611. This only happens when running `steam-runtime`. `steam-native` seems to work fine.

`steamwebhelper.log`
```
setup.sh[34580]: Updating Steam runtime environment...
/usr/bin/zenity: symbol lookup error: /usr/lib/libsoup-3.0.so.0: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
/home/user/.local/Steam/ubuntu12_64/steam-runtime-heavy/setup.sh: line 208: echo: write error: Broken pipe
```

Also seeing this output in the terminal:
```
steamwebhelper.sh[41062]: Runtime for steamwebhelper: defaulting to /home/user/.local/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[41062]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[41115]: Runtime for steamwebhelper: defaulting to /home/user/.local/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[41115]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
src/steamUI/steamuisharedjscontroller.cpp (416) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (416) : Failed creating offscreen shared JS context
```

**Comment by kisak-valve** [comment]
Hello @Seegras, glad to hear it started behaving.

Hello @momumi, `/usr/bin/zenity: symbol lookup error: /usr/lib/libsoup-3.0.so.0: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation` is a decent hint, but since @Seegras's issue is now resolved, it's most likely unrelated to the opening post.

Please open a new issue report in https://github.com/ValveSoftware/steam-runtime/issues so that your Steam runtime - heavy issue can be tracked properly.

Hello @Bill5122, please open a new issue issue report in this issue tracker so that your feedback can be tracked properly.
