### ISSUE TITLE
`Steam: An X Error occurred` each time steam loses focus

### ISSUE THREAD

**Issue by WhyNotHugo** [ValveSoftware/steam-for-linux#9222]
#### Your system information

* Steam client version (build number or date): Feb 14 2023
* Distribution (e.g. Ubuntu): Flatpak
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Each time Steam loses focus, it prints the following error to stdout:

```
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  20 (X_GetProperty)
Resource id in failed request:  0x0
Serial number of failed request:  9
xerror_handler: X failed, continuing
```

It will continuously repeat the same error once the window is unfocused.

#### Steps for reproducing this issue:

1. Run Steam
2. Focus any other window

I'm using swaywm. I don't see any obvious problems with this, but it fills steam's stdout with rubbish, and makes it super hard to read logs when trying to debug a game that isn't working.

**Comment by kisak-valve** [comment]
Hello @WhyNotHugo, this issue is already being tracked at #9164. Closing as a duplicate.
