### ISSUE TITLE
Can no longer launch Steam after today's update

### ISSUE THREAD

**Issue by tukkek** [ValveSoftware/steam-for-linux#9229]
#### Your system information

* Steam client version (build number or date): up-to-date as of today's update. 
* Distribution:  `Linux 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux`
* Opted into Steam client beta? Don't remember, don't think so.
* Have you checked for system updates? All related Debian `testing` packages updated in the last hour.

#### Please describe your issue in as much detail as possible:
Was using Steam minutes ago, received an update and can no longer start it. Tried updating all packages through the package manager and the issue persists. It can successfully download an update, apply it but then fails to launch after showing a brief "Updating Steam, verifying integrity..." dialog.

#### Steps for reproducing this issue:

1. Receive Steam update (fails on auto-restarting).
2. Try to launch the client again manually (fails).
3. Update system packages, make sure to install every dependency and suggested library (issue persists).
 
Will be attaching logs and console output next.

**Comment by tukkek** [comment]
(Sorry, it took me a while to perform the following steps).

This is the console output after purging (`aptitude purge`) all Steam system packages and installing fresh, including:

1. steam-installer
2. steam-libs
3. steam-libs:i386
4. steam-libs-i386:i386
5. steam-devices
6. steam:i386
7. protontricks

I have received an alert that I ought to clear the Steam home folders manually to properly purge so I've done that as well (including my games library).

I've updated the package index and reinstalled every package list plus recommendations and suggestions (other than NVidia libraries, as I'm using an integrated Intel chipsete).

I received a warning from `steam-installer` about proprietary software, Steam updated its runtime environment and downloaded a 300MB+ update, extracted the package, unpacked the runtime then crashed. So the issue still persists.
[console.output.txt](https://github.com/ValveSoftware/steam-for-linux/files/10798034/console.output.txt)

**Comment by tukkek** [comment]
Zipped dump file mentioned in the tail lines of the log:

[crash_20230221184348_3.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/10798076/crash_20230221184348_3.dmp.zip)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGBUS in libc.so.6 coming from chromehtml.so.

**Comment by kisak-valve** [comment]
Hello @tukkek, can you check if there are any hints in `cef_log.txt`, `steamwebhelper.log`, or `webhelper.txt` in the `~/.steam/root/logs` folder.

**Comment by tukkek** [comment]
A cold system reboot seems to have fixed the problem? I'll install something just to verify that it launches before closing the issue.

**Comment by tukkek** [comment]
Alright all's good apparently. I've installed and played a game, cloud saves all up-to-date, etc.

Sorry for the false alarm and thank you for the ongoing, industry-leading penguin support :)

**Comment by tukkek** [comment]
> For reference, the attached minidump is a SIGBUS in libc.so.6 coming from chromehtml.so.

@kisak-valve feel free to reopen if you think the issue is still worth investigating. I'm assuming it's something like a `systemd` update that did not apply correctly until the reboot or something similar.
