### ISSUE TITLE
Steam segfaults on Intel hardware

### ISSUE THREAD

**Issue by david-morris** [ValveSoftware/steam-for-linux#9230]
#### Your system information

* Steam client version (build number or date): 1.0.0.75-1
* Distribution (e.g. Ubuntu): Arch rolling 64 bit
* Opted into Steam client beta?: [Yes/No] I have in the past, but I'm not logged in, and I've reinstalled steam since; maybe never on this machine.
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

Instead of starting Steam and showing a login screen, steam crashes when it tries to render anything beyond the update-on-start dialog.
[here's the output.](https://gist.github.com/david-morris/632f2ba6b77ad9e7b54bb766d2edec35)

Glxgears runs fine.

This has similar output to #7395 . I have Jasper Lake hardware, mesa and vulkan-intel with 32bit installed:
```
[dmorris@tinkerbell:~]$ pacman -Q | grep vulkan                                                                                                                                                      (02-21 23:54)
lib32-vulkan-icd-loader 1.3.240-1
lib32-vulkan-intel 22.3.4-1
lib32-vulkan-mesa-layers 22.3.4-1
vulkan-headers 1:1.3.240-1
vulkan-icd-loader 1.3.240-1
vulkan-intel 22.3.4-1
vulkan-mesa-layers 22.3.4-1
vulkan-tools 1.3.240-1
[dmorris@tinkerbell:~]$ pacman -Q | grep mesa                                                                                                                                                        (02-21 23:54)
lib32-mesa 22.3.4-1
lib32-vulkan-mesa-layers 22.3.4-1
mesa 22.3.4-1
mesa-utils 8.5.0-2
vulkan-mesa-layers 22.3.4-1
[dmorris@tinkerbell:~]$                                                                                                                                                                              (02-21 23:54)
```

**Comment by kisak-valve** [comment]
Hello @david-morris, can you check if any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works?

**Comment by david-morris** [comment]
Hi @kisak-valve , thanks for that tip.

[here's the output](https://gist.github.com/david-morris/bb17af73cf8b3e9bf0993e43a92f19be) from glxinfo32. I didn't know of any multilib test packages, so thanks.

Unfortunately, that output looks fine to me, and glxgears32 runs fine (or at least it says it does; I'm in the next room on a screen session, setting `$DISPLAY`).

**Comment by kisak-valve** [comment]
Thanks for checking. I think the glxinfo output is hinting that you're seeing #4399.

**Comment by david-morris** [comment]
@kisak-valve great catch, I think that might be useful later.  

But I don't think that's the whole problem.  Or if it is, I need help making a workaround.

When I reduce my bit depth explicitly with `xrandr --output HDMI-2 --set "max bpc" 8`, my screen flashes black and returns, and `xrandr --verbose` [shows](https://gist.github.com/david-morris/d2dee9705b596f7c189b153366ae5f34) that I've successfully lowered the max bit depth on my active display.  But steam fails with superficially similar [output](https://gist.github.com/david-morris/45af597827ddfb1cc84798b1feb10a8a).

**Comment by kisak-valve** [comment]
I'm not particularly familiar with adjusting display depth, but I suspect that the lower sections of glxinfo are also showing similar as what you shared previously.

I'm guessing that you'd want to adjust X's general config by adding a config file in `/etc/X11/xorg.conf.d/` with something like
```
Section "Screen"
  Identifier "Screen Name"
  DefaultDepth 24
EndSection
```
and restarting your X session and compare what glxinfo gives you compared to before.

**Comment by david-morris** [comment]
@kisak-valve hmm.  I tried this and it didn't result in changes to glxinfo output, and steam still crashes.  I also tried the identifier "HDMI-2" and a DefaultDepth of 8.  I'll look further into the xorg documentation over the weekend.

**Comment by david-morris** [comment]
Ok, I've found and commented out my HDR bit depth xorg config, and then I can start steam.  That means that this is in fact a duplicate of #4399 .
