### ISSUE TITLE
Steam client is initially completely unresponsive on KDE wayland 

### ISSUE THREAD

**Issue by Bill5122** [ValveSoftware/steam-for-linux#9231]
* Steam client version (build number or date): 1676935611
* Distribution (e.g. Ubuntu): gentoo
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

When opening steam on kde wayland, the client should be responsive on launch.

#### Steps for reproducing this issue:

1.  Use kde wayland 5.27.  Does not reproduce on sway or kde x11.
2.  Launch steam
3.  Observe the steam client being blanked out and completely unresponsive until clicking on the taskbar icon.  

Hardware information:  https://gist.github.com/Bill5122/6694f883c71d24e9c8bd23dcf3cf0c32 

Video attached.  

https://user-images.githubusercontent.com/93512766/220536991-e2bf9f58-b490-4884-86aa-82ab2fe7447d.mp4

**Comment by Mart-Bogdan** [comment]
Wow. I didn't have such problems with KDE 5.26.5 and wayland.

(there were problems in games, with tearing, but that's not related)

**Comment by marscher** [comment]
I also observe this "gui freeze" of about 30 seconds with plasma-wayland session 5.27.2. I use proprietary Nvidia drivers (525.89.02). Steam is installed via flatpak. I'm happy to provide any further (technical) information if that would be of any help.

**Comment by Bill5122** [comment]
Tried the beta again today and no longer reproducing on kde wayland 5.27.2, so closing.
