### ISSUE TITLE
Steam Beta began to flicker on render updates

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/steam-for-linux#9232]
#### Your system information

* Steam client version (build number or date): Feb 20 2023, at 22:45:22
* Distribution (e.g. Ubuntu): Manjaro 22.0.3
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I have noticed that in a update in the last ~4 days the steam client began to flicker when rendering sometimes

#### Steps for reproducing this issue:

(reproduction is not reliable)

1. Open Steam client
2. Move around different tabs
3. Maybe observe flickering

---

[Video Showcasing the problem](https://www.youtube.com/watch?v=1uzbLzYV4_I)
Note: it may also be some kind of KDE problem, because not all flickers showed up in the OBS recording attached, for example:
- the flickering starts at 00:07 in the video
- the flickering stops at 00:12 in the video, but still visibly happened (obs did not see that)
- the flickering stops at 00:17 in the video for me outside of what the recording saw

**Comment by kisak-valve** [comment]
Possible duplicate of #9221.

**Comment by hasezoey** [comment]
> Possible duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/9221.

the mentioned issue seems to me like it track multiple things and not the flickering as its main point, so would keep this issue open

PS: flickering still happens in `May 27 2023, at 20:15:25` (beta)

**Comment by hasezoey** [comment]
for me the new ui is not flickering anymore from what i can tell
