### ISSUE TITLE
cmdline args in the exe line of non-steam shortcuts no longer working

### ISSUE THREAD

**Issue by Godsbane** [ValveSoftware/steam-for-linux#9237]
#### Your system information

* Steam client version (build number or date):  Feb 22nd Beta (1677103459)
* Distribution (e.g. Ubuntu): SteamOS 3.4.4
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Any applications with arguments appended to the Executable line in a shortcut no longer work.

```
These are excerpts from the log while steam is running, showing how the executable is being launched.
Stable:
Default (current): (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/usr/bin/bash" "/run/media/external/Emulation/tools/launchers/dolphin-emu.sh"
no quotes with spaces: (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /usr/bin/bash /run/media/external/Emulation/tools/launchers/dolphin-emu.sh
quotes, no spaces: (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/run/media/external/Emulation/tools/launchers/dolphin-emu.sh"
no quotes, no spaces: (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /run/media/external/Emulation/tools/launchers/dolphin-emu.sh

Beta:
Default (current): (doesn't work)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/usr/bin/bash"
no quotes with spaces: (doesn't work)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/usr/bin/bash /run/media/external/Emulation/tools/launchers/dolphin-emu.sh"
quotes, no spaces: (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/run/media/external/Emulation/tools/launchers/dolphin-emu.sh"
no quotes, no spaces: (works)
/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4176296924 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- "/run/media/external/Emulation/tools/launchers/dolphin-emu.sh"
```
It appears to be how the executable line is being quoted / escaped now. With the first example on beta - it cuts off the rest of the line.
with the second example it quotes the whole string, not caring about the space between the exectuable and the file.

this will break shortcuts for a lot of users.
#### Steps for reproducing this issue:

1. create any non-steam shortcut with arguments appended to the executable. (like those created by steam rom manager)
2. update to the latest steam beta
3. observe that previously working shortcuts no longer work.

**Comment by TTimo** [comment]
It sounds like you are stuffing command line arguments into the exe path (which used to work although possibly never intentionally). We should look at keeping this functionality working of course since it's a regression, but why not use the launch options for your arguments?

**Comment by Godsbane** [comment]
I have no issue with using the launch arguments going forwards.

I have rebuilt all my personal parsers to do this already. (again mostly referring to using Steam Rom Manager here)

The only issue is that it will catch a lot of people off guard, since as you mentioned it used to work.

There are some implications with AppID changing as well; and things that use it to track per application settings.

thank you for looking into it!

**Comment by TTimo** [comment]
I get your point, thanks for reporting. I'm not sure what the solution will look like, I'm leaning towards extracting arguments on the executable line and moving them to the command line arguments so folks don't get broken in the transition.

As far as AppID changing, there have indeed been some changes there. The AppID used to change which any edits to the exe or start dir, which was causing a bunch of other issues (such as not being able to start a shortcut after editing it's name, requiring a steam client restart). In the beta the AppIDs no longer change with edits.

The first time you run steam might have to shuffle a few things in case of conflicts, but after that the AppID for the shortcuts will not change anymore (they are unique to each steam installation though, basically a GUID).

**Comment by Godsbane** [comment]
Interesting, sounds like great under the hood changes. Is there any documentation on how steam is going to generate AppID going forward? I can report back to the Steam Rom Manager devs so they can update their application.

**Comment by TTimo** [comment]
It's just randomized in a good range reserved for non-steam shortcuts. We're actively working on improving the non-steam shortcuts functionality, it's best if regressions get reported on this tracker directly.

**Comment by TTimo** [comment]
fwiw today's beta brings back the cases you reported broken versus the stable release. we're still working in that area .. please keep an eye out!

**Comment by Godsbane** [comment]
Thanks!

I did some quick tests and things are looking good to me.
