### ISSUE TITLE
Steam installer can't install the tenfoot_dicts_all package.

### ISSUE THREAD

**Issue by QurashiAkh** [ValveSoftware/steam-for-linux#9245]
#### Your system information

* Steam client version (build number or date): `updater built Feb 14 2023 00:47:09`, `updater built Jun  7 2022 03:18:19` & `updater built Nov 22 2021 22:06:59`.
* Distribution (e.g. Ubuntu): Ubuntu 22.04 LTS / Arch Linux.
* Opted into Steam client beta?: No.
* Have you checked for system updates?: Yes.

#### Please describe your issue in as much detail as possible:

Since I switched from Windows 11 to Linux, I keep attempting to install Steam (whether from APT, Snap, Flatpak, or the official Website) and I get this Error preventing me from that, saying:
```
[2023-03-01 17:38:52] Error: Download of package (tenfoot_dicts_all) failed due to checksum mismatch
```
and:
```
[2023-03-01 17:46:25] Package file tenfoot_dicts_all.zip.3a6cb3db75398c509bdc6e389408b6951017494b missing or incorrect size
[2023-03-01 17:46:25] Add pending download: http://media.steampowered.com/client/tenfoot_dicts_all.zip.3a6cb3db75398c509bdc6e389408b6951017494b
[2023-03-01 17:46:25] Manifest download: send request
```
I ran into this Error on Linux Mint, Manjaro, Kubuntu & now Ubuntu (and Zorin OS). I contacted Support and I didn't get a working Solution.

According to my Analysis, it seems that this is a problem with the Steam installer itself, as it looks like the Steam installer had an issue generating a checksum for the `tenfoot_dicts_all` package, or it could be that the Manifest it downloaded is outdated, and so it provided an incorrect checksum for this specific package.

Also, every time it finishes, saying:
```
[2023-03-01 17:47:01] Error: Download of package (tenfoot_dicts_all) failed due to checksum mismatch
[2023-03-01 17:47:01] Downloading update (335,776 of 347,763 KB)...
[2023-03-01 17:47:01] Exhausted list of download hosts
[2023-03-01 17:47:01] Repeatedly failed to download packages, giving up
[2023-03-01 17:47:01] Saving metrics to disk (/home/qurashiakh/.local/share/Steam/package/steam_client_metrics.bin)
[2023-03-01 17:47:01] Error: Steam needs to be online to update.	 Please confirm your network connection and try again.
```
It shows me this box:

![image](https://user-images.githubusercontent.com/61647437/222174373-13d8fe8e-737a-4cd9-ba61-1ecf257f3941.png)

I tried:
- rebooting.
- disabling firewalls.
- downloading the installer from:
  - APT.
  - Snap.
  - Flatpak.
  - Pacman.
  - YaST.
  - Wine.
  - the Official Website.
- googling it.

Things to keep in mind:
- I do have a good internet connection.
- This same Error was thrown in six different fresh installations of multiple Linux Distributions.
- Every other package Steam tried to install got successfully installed, except this particular one.
- Steam used to run completely fine on Windows.
- My ASUS Laptop isn't a Potato Machine either:

![image](https://user-images.githubusercontent.com/61647437/222179227-b336c685-5a18-4b99-9863-b087684f5574.png)

#### Steps for reproducing this issue:

1. `sudo apt-add-repository multiverse`
2. `sudo apt update`
3. `sudo apt upgrade`
4. `sudo apt install steam` or `sudo dpkg -i steam_latest.deb`
5. `steam`

or:

1. Enabling the `multilib` repository.
2. `sudo pacman -S steam`
3. `steam`

---

**Update:** I tried installing Steam using PlayOnLinux & Wine, then on Wine alone using `SteamSetup.exe`, it still didn't work, giving the same exact error about `tenfoot_dicts_all` not being installed. I also installed Vanilla Arch Linux with KDE and tried installing Steam from Pacman & from Pamac, still the same issue.

I ran `steam > steam_logs.txt` on my Arch Linux Installation, and here are the logs:
https://gist.github.com/QurashiAkh/a03666384858862c5d6c1cff30f681f6
Keep in mind that all other Distributions I tried installing Steam on had identical logs, also that it outputted this into my Terminal before starting the logs:
```
bin_steam.sh[46261]: Setting up Steam content in /home/qurashiakh/.local/share/Steam
steam.sh[46261]: Running Steam on arch rolling 64-bit
steam.sh[46261]: STEAM_RUNTIME is enabled automatically
setup.sh[46356]: Updating Steam runtime environment...
steam.sh[46261]: Can't find 'steam-runtime-check-requirements', continuing anyway
```

After it displayed the same error box I mentioned above, I closed it. It outputted this to the console:
```
src/tier0/threadtools.cpp (3645) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56d66c30/0x0xe41feb'
assert_20230310191618_8.dmp[57062]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230310191618_8.dmp
assert_20230310191618_8.dmp[57062]: Finished uploading minidump (out-of-process): success = yes
assert_20230310191618_8.dmp[57062]: response: CrashID=bp-82382ad5-affc-42da-8e99-f76202230310
assert_20230310191618_8.dmp[57062]: file ''/tmp/dumps/assert_20230310191618_8.dmp'', upload yes: ''CrashID=bp-82382ad5-affc-42da-8e99-f76202230310''
```

When I tried to run `steam > steam_logs_retry.txt` after giving an error in the first time, this is what came up:
https://gist.github.com/QurashiAkh/3e10eca4a63da239828990dfb8712140

---

**Second Update:** I installed openSUSE Tumbleweed just for the purpose of installing Steam, and it gave me the exact same checksum mismatch failure. I'm currently thinking of installing Ubuntu on a second computer to see if Steam can install there or not.

**Comment by QurashiAkh** [comment]
Hey! As I am currently on Arch Linux, I gave up on Steam because of this, but not forever. I noticed I had the `ttf-liberation` package installed when trying to install Steam. Steam seemed not to work well with it, and that could've been the root cause of the issue, somehow. Yet, when I installed the Windows 11 Fonts using the `ttf-ms-win11-auto` package from the AUR, Steam automagically installed and worked. I may have issues with playing Games but that would be addressed somewhere else outside this bug report.

**Comment by hharas** [comment]
The reason for this happening is related to my ISP. I switched to Windows 11 and went through the same `tenfoot_dicts_all` drama, then opened a Hotspot Network on my Phone using my Cellular Service Provider's Internet and everything worked.
