### ISSUE TITLE
Notifications blacked out, appearing as black boxes (incoming message or friends opening a game)

### ISSUE THREAD

**Issue by koloved** [ValveSoftware/steam-for-linux#9246]
#### Your system information

* Steam client version (build number or date): 14 feb 2023 year
* Distribution : Arch , wayland, KDE 5.27.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, last updates, mesa-git 23.1

[Screenshot:](https://i.imgur.com/bb1p8AS.png)
I found at least two reddit post and there is solution to fix it:
```
The way to get around this is to create a custom skin disabling the fade effect and it will now show the notification content.

    Open the folder ~/.steam/root/

    Create new folder "skins" ~/.steam/root/skins

    Go to terminal and enter: cd ~/.steam/root/skins

    Then enter: emkdir -p Bottom-Right/resource

    Then enter: cp -r ~/.steam/root/resource/styles Bottom-Right/resource

    Now find and open a new file "steam-styles" with text editor located here: ~/.steam/root/skins/Bottom-Right/resource/styles

    Inside steam-styles search for "Notifications.PanelPosition" and change it to BottomRight if it is not already then set Notifications.SlideDirection to "None" then save.

    Now open steam and go to settings>>interface and then select skin "Bottom-Right" then restart steam.

Now notifications should appear without fade and contain information and not just a black box.
```

1. its blacked out when you are on workspaces where steam is not running
2. When i am in game , then i ll get usual notification like in windows

**Comment by kisak-valve** [comment]
Hello @koloved, this issue is already being tracked at #4735. Feel free to add your findings to the older issue report.

Closing as a duplicate.
