### ISSUE TITLE
Steam client and chat/friendlist are separated in grouped window list

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#9247]
#### Your system information

* Steam client version (build number or date): 2023-03-01
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes 

#### Please describe your issue in as much detail as possible:
Since this beta round, the friendlist and the chat window are separated in my window list when it's set to group same windows. I assume they suddenly use a different window class or window name. Going back to Steam Stable fixes it.

This is with Cinnamon Desktop, might affect other desktops as well.

Steam Beta Example:
![grafik](https://user-images.githubusercontent.com/7719590/222367546-c3986b1d-e2de-44ce-837a-2643904e9b59.png)
![grafik](https://user-images.githubusercontent.com/7719590/222367054-bdb6b844-5d08-46ed-bfa9-e74cc5396b48.png)

Steam Stable Example:
![grafik](https://user-images.githubusercontent.com/7719590/222369400-cffac016-a788-4d45-9522-8af09cac58e2.png)

**Comment by kisak-valve** [comment]
Hello @NoXPhasma, this issue is already being tracked at #9235. Closing as a duplicate.
