### ISSUE TITLE
scaling + multiple monitors makes the game unstable

### ISSUE THREAD

**Issue by rodrigoGA** [ValveSoftware/steam-for-linux#9248]
#### system information

* Steam Runtime Version:  steam-runtime_0.20221019.0
* Distribution: 22.04.2 LTS (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Video Card:  NVIDIA Corporation NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
* CPU Brand:  AMD Ryzen 9 5900X 
     
#### issue description
when I set the scaling to a fraction scale, for example:
* monitor 1: resolution 3840*2160, scaling 175%
* monitor 2:  resolution 1920*1080, scaling 100%

![Captura desde 2023-03-05 21-35-40](https://user-images.githubusercontent.com/2334523/222995756-60c55173-202b-4e82-aa4a-154987c1f8fc.png)

all games seem to behave unstable once opened, first the screen appears and reappears as if it were adjusting, then the mouse is clicked in different places where the pointer is shown.

tested games:
* CSGO
* age of empires 2

**Comment by kisak-valve** [comment]
Hello @rodrigoGA, without a better hint, this reads like an issue that needs to be evaluated by your desktop environment's dev(s) first.

Closing as not a Steam client issue.

**Comment by rodrigoGA** [comment]
Hi @kisak-valve  it's  looks like a  steam or proton problem, the game runs in the native resolution of the monitor, it shouldn't take the desktop resolution into account.
said this in another way, the game always run on 3840*2160 , but when there is a fractional scale in desktop, the steam client seems to have a problem, with 200% this does not happen.

**Comment by kisak-valve** [comment]
I could have been clearer in my initial response. The Steam client itself does not currently support fractional scaling, which is being tracked at #5908.

Your feedback here, however, is overly generalized to any random game being started from Steam. That is either a larger Linux ecosystem issue or specific to the implementation done by your desktop environment and the devs who implemented the fractional scaling in your desktop environment are more likely to come up with an actionable hypothesis on what's gone awry.

The overly generalized feedback is out of scope for this issue tracker, but if you find a specific and actionable hint, then we can ponder this further here.

**Comment by rodrigoGA** [comment]
How it was said in 5908 apparently the steam client uses x2 scaling (ignore 175% from my desk)
But when opening a game, the game seems to refresh the scaling to x2 every time you switch screens and I think that causes the mouse to be in a different position than the pointer is displayed. It seems to be associated with the use of two monitors.
I don't know if they are all the games. I have two games on linux (aeo2, csgo) and in both it happens
