### ISSUE TITLE
Fonts in Library view are too small on HiDPI screens

### ISSUE THREAD

**Issue by norbusan** [ValveSoftware/steam-for-linux#9251]
#### Your system information

* Steam client version (build number or date): Mar 2 2023, at 23:52:21
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Text on the Library page is too small for the Screen, missing scaling
Text on the Store and Community pages is correctly scaled.

See attached screenshot to compare font sizes of menu and game list etc

Display resolution: 3840x2160
Screen size: 702mm x  400mm
DPI: 139

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1735589/223279602-cbb10233-8fd3-4820-b265-bd79ee48cb55.png">

**Comment by kisak-valve** [comment]
Hello @norbusan, this issue is already being tracked at #9209. Closing as a duplicate.

**Comment by howdev** [comment]
the update is worse than before, don't scale anymore. At least before update, in the setting there is enable large text and icon and that works. 

The fix is use commandline forcedesktopscaling=2. OR use -vgui, which will give you old UI back, but the library text cannot be scaled.
