### ISSUE TITLE
Feature Request: Option to Remove game cache or proton game compat folder/files

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#9257]
Hey guys I thought an awesome feature for convenience for Steam Linux/Steam OS users would be the option to view and delete game cache per game or all at once or the option when you uninstall a game to remove the game cache and  proton game compat folder/files. This  would be much easily and allow users to manage their storage while giving far more ease of use and accessibility , remove whats not needed all from the Steam UI instead of just willy nilly deleting the shadercache/compatdata or  figure out what every game ID numbers refer to.

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue is already being tracked at #8266 / #6486 and the Steam client on SteamOS has `Game` -> `Settings` -> `Developer` -> `Delete Proton files` as a UI option.

Closing in favor of the older feature requests.

**Comment by coreybruce** [comment]
Cool, glad this is a feature already being tracked and hopefully looked into :)

**Comment by coreybruce** [comment]
@kisak-valve another aspect this feature is required on is on the desktop UI of Steam as the feature only exists when using big picture mode also the ability to remove shader cache per game and as a whole is missing :slightly_smiling_face:
