### ISSUE TITLE
Steam launch error Ubuntu 22.04 [KDE-Plasma Wayland]

### ISSUE THREAD

**Issue by adamsjo95** [ValveSoftware/steam-for-linux#9259]
#### Your system information

* Steam client version (build number or date):  Latest 03/2023
* Distribution (e.g. Ubuntu):  Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes I have ran sudo apt-get update and upgrade. I have also removed and purged steam steam-launcher from system and done a full reinstall of steam package. 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  sudo apt-get install steam to install the steam client fresh after removal and full purge from files.  Also long with this I updated and upgraded packages and repos. 
2.  After fresh install is completed I go to run the steam program in shell with the follow error log:

# Steam Error Log 

_steam.sh[6234]: Running Steam on ubuntu 22.04 64-bit
steam.sh[6234]: STEAM_RUNTIME is enabled automatically
setup.sh[6302]: Steam runtime environment up-to-date!
steam.sh[6234]: Can't find steam-runtime-check-requirements continuing anyway
[2023-03-14 14:42:07] Startup - updater built Jun  7 2022 03:18:19
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: [swrast_dri.so]
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)_

4. I did my own research on this one to try to resolve it seems like it was related to an nVidia graphics library component that works with OpenGL failing on the libGL error. This is nice but I am running an AMD Radeon RX 5700 XT. I have attached my OpenGL info below

# OpenGL version log

_john@odin:~$ glxinfo | grep OpenGL
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 5700 XT (navi10, LLVM 15.0.6, DRM 3.47, 5.19.0-35-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:_>_

5. I have tried other workarounds with reinstalling mesalib packages or proton but these did not change this result. I will say it is possible this error started occuring when I upgraded KDE from X11 => WAYLAND however even when I revert back to X11 the process error persists. 

Please let me know fi I am missing something here I cant seem to find a solution to get this to work. I even modified 'sudo nano /usr/share/applications/steam.desktop'  change from 'PrefersNonDefaultGPU = true' => 'PrefersNonDefaultGPU = false'

Im at wits end here nothing seams to change the end result.

**Comment by kisak-valve** [comment]
Hello @adamsjo95, does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 22.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

**Comment by adamsjo95** [comment]
@kisak-valve  I downloaded mesa-utils_8.4.0-1_i386 I did not install but I did notice that it was installed on my system already in my software management tool. glxinfo is working perfectly fine thats how I pulled the OpenGL info attached. 

I was able to unpack the contents from the deb file but I am not to sure where to go with it from there. Below is some information on installed mesa library files on my system. 


_apt list --installed | grep mesa

libegl-mesa0/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
libegl-mesa0/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]
libgl1-mesa-dri/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed]
libgl1-mesa-dri/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed]
libgl1-mesa-glx/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed]
libglapi-mesa/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
libglapi-mesa/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]
libglu1-mesa-dev/jammy,now 9.0.2-1 amd64 [installed,automatic]
libglu1-mesa/jammy,now 9.0.2-1 amd64 [installed,automatic]
libglx-mesa0/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
libglx-mesa0/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]
mesa-utils-bin/jammy,now 8.4.0-1ubuntu1 amd64 [installed,automatic]
mesa-utils/jammy,now 8.4.0-1ubuntu1 amd64 [installed]
mesa-va-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
mesa-va-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]
mesa-vdpau-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
mesa-vdpau-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]
mesa-vulkan-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 amd64 [installed,automatic]
mesa-vulkan-drivers/jammy-updates,now 22.2.5-0ubuntu0.1~22.04.1 i386 [installed,automatic]_

#Run steam again 

_steam.sh[17300]: Running Steam on ubuntu 22.04 64-bit
steam.sh[17300]: STEAM_RUNTIME is enabled automatically
setup.sh[17368]: Steam runtime environment up-to-date!
steam.sh[17300]: Can't find 'steam-runtime-check-requirements', continuing anyway_

**Comment by adamsjo95** [comment]
I resolved this issue by reinstalling Kubuntu stable distro on xORG. I think when I tried to install Wayland in the same desktop environment that there was a conflict with accessing the mesaLIB files.

**Comment by kisak-valve** [comment]
Closing per the last comment.
