### ISSUE TITLE
`You do not have enough disk space available to run this game`

### ISSUE THREAD

**Issue by john-peterson** [ValveSoftware/steam-for-linux#926]
### Problem

If one library folder is out of space downloading a game return

> You do not have enough disk space available to run this game. Pleas free up some disk space and then try again.
#### Steam Library Folders

```
folder                          installed   used space  free space
/home/user/.local/share/Steam   0           0 bytes     4.19 GB
/mnt/hgfs/shared/e/steam        0           0 bytes     163.87 GB
```
### Discussion
- Attempting remove of `/home/user/.local/share/Steam` return

> The default Steam install folder can't be removed
- Using a folder link instead doesn't alter the disk space check and therefore doesn't work around this restriction

```
s=~/.local/share/Steam/SteamApps; rm -rf $s; ln -s /mnt/hgfs/shared/e/steam $s
```
- How do I alter the disk space reported to the client?
### Workaround

```
killall steam
mv ~/.local/share/Steam ~/.local/share/Steam.old
steam   # select default library folder
```
### Suggestions
- Allow saving only game files to a separate location (rather than to `./SteamApps`) because
  - the user can backup program settings by other means
  - the path selection is primarily of interest for saving the game files because they're large
- If a library path is out of space, download to the library path(s) with space (instead of halting the download)

**Comment by kisak-valve** [comment]
Hello @john-peterson, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
