### ISSUE TITLE
Steam Beta Client Update: March 14th - UI rendering issue in game library since update

### ISSUE THREAD

**Issue by tgurr** [ValveSoftware/steam-for-linux#9260]
#### Your system information

* Steam client version (build number or date): 1678845529 / Steam Beta Client Update: March 14th
* Distribution (e.g. Ubuntu): Exherbo
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since the latest update (Beta Client Update: March 14th) the UI rendering in the game library got screwed up a little, there's a solid black bar at the bottom and at the top you're unable to see some content / scroll fully up (probably the amount of pixels the black bar at the bottom consists of?).

![steam_beta_march14](https://user-images.githubusercontent.com/414984/225219946-59967d23-4600-4ab2-a544-f0a1bcd66a87.png)

#### Steps for reproducing this issue:

1. Opt into beta
2. Update to latest Steam Beta Client Update: March 14th
3. Observe rendering issue

**Comment by TheISOmorph** [comment]
I have not opted in Steam Beta and have this exact issue since the last update

-     Steam client version (build number or date): 1678914933 / Built: Mar 15 2023, at 20:49:14
-     Distribution (e.g. Ubuntu): Nobara 37
-     Opted into Steam client beta?: No
-     Have you checked for system updates?: Yes

**Comment by Dyskord** [comment]
Also got the same issue since last update, non-beta, on debian unstable.

**Comment by Alexander-Wilms** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/3226457/226234388-b64bfc47-ffb2-4ff1-be70-255ef78213cc.png)

* Steam client version (build number or date): Mar 17 2023, at 18:27:00
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

**Comment by sysms** [comment]
Same issue now also on latest stable steam client on Debian 11:

![steamstable240323](https://user-images.githubusercontent.com/4120422/227705765-25129866-0eb3-4a01-ab04-d57c413d7cd6.png)
![steamclient_blackbar](https://user-images.githubusercontent.com/4120422/227705808-037670da-c60b-40c4-aac7-84459b08f6a4.png)

**Comment by Cippo95** [comment]
Same on Fedora 37.
Scrolling to the bottom of the page fixes it momentarily?

**Comment by sqrt-7** [comment]
Same issue here, latest stable client on OpenSuse Tumbleweed

**Comment by Alexander-Wilms** [comment]
Enabling the Steam Beta Update fixed the issue for me:

![image](https://user-images.githubusercontent.com/3226457/235222203-f2f7039f-c41a-4d11-96cb-22d064b5c706.png)

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-06-14](https://store.steampowered.com/oldnews/195171) Steam client update.
