### ISSUE TITLE
 libgl1-mesa-dri:i386 : Depends: libllvm15:i386 but it is not installable                         Recommends: libgl1-amber-dri:i386 but it is not installable

### ISSUE THREAD

**Issue by Oipo** [ValveSoftware/steam-for-linux#9261]
#### Your system information

* Steam client version (build number or date): Latest instructions from https://repo.steampowered.com/steam/
* Distribution (e.g. Ubuntu): Ubuntu 22.04.2 LTS
* Opted into Steam client beta?: N/A
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
```
oipo@oipo-X670E-AORUS-MASTER:/etc/apt/sources.list.d$ sudo apt-get install \
  libgl1-mesa-dri:amd64 \
  libgl1-mesa-dri:i386 \
  libgl1-mesa-glx:amd64 \
  libgl1-mesa-glx:i386 \
  steam-launcher
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libgl1-mesa-dri is already the newest version (22.2.5-0ubuntu0.1~22.04.1).
libgl1-mesa-glx is already the newest version (22.2.5-0ubuntu0.1~22.04.1).
libgl1-mesa-glx set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libllvm15:i386 but it is not installable
                        Recommends: libgl1-amber-dri:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Oipo, this is a distro packaging issue, not a Steam client issue. In general, Debian packaging requires that arch variants have exactly the same version, and it also dislikes downgrading packages.

Can you share the output of `apt policy libllvm15 libllvm15:i386`?

**Comment by Oipo** [comment]
@kisak-valve aaah, thank you so much! I am using the `apt.llvm.org` for clang-15 specifically, which added another version:

```
oipo@oipo-X670E-AORUS-MASTER:~$ apt policy libllvm15 libllvm15:i386
libllvm15:
  Installed: 1:15.0.7~++20230131104537+8dfdcc7b7bf6-1~exp1~20230131104626.110
  Candidate: 1:15.0.7~++20230131104537+8dfdcc7b7bf6-1~exp1~20230131104626.110
  Version table:
 *** 1:15.0.7~++20230131104537+8dfdcc7b7bf6-1~exp1~20230131104626.110 500
        500 http://apt.llvm.org/jammy llvm-toolchain-jammy-15/main amd64 Packages
        100 /var/lib/dpkg/status
     1:15.0.6-3~ubuntu0.22.04.2 500
        500 http://nl.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
libllvm15:i386:
  Installed: (none)
  Candidate: 1:15.0.6-3~ubuntu0.22.04.2
  Version table:
     1:15.0.6-3~ubuntu0.22.04.2 500
        500 http://nl.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages
```

The fix was ` sudo apt install libllvm15=1:15.0.6-3~ubuntu0.22.04.2` followed by `sudo apt install libllvm15:i386=1:15.0.6-3~ubuntu0.22.04.2`

**Comment by mcourteaux** [comment]
I got the same issue today. Thanks for this! Although I'd like to understand what happened. I also used the same apt.llvm.org thing to install clang-15. After doing so, Steam broke, but I don't understand, as that step was required to be able to install clang 15 I think. And now your fix seems to use an ubuntu-provided repository instead of the llvm repository? Does it mean I could have skipped the apt.llvm.org install helper and installed clang-15 right away?

**Comment by Oipo** [comment]
I think that the issue is that steam compiles their libGL specifically to use libllvm as their shader compiler (don't quote me on this though), which uses the exact version mentioned. I do not know what changed recently that it now requires this specific version and/or if it didn't before.

**Comment by Niclas302** [comment]
i tried also to install steam today and got nearly the same problem what do i have to do?

_**Steam needs to install these additional packages:
libc6:amd64 libc6:i386 libegl1:amd64 libegl1:i386 libgbm1:amd64 libgbm1:i386 libgl1-mesa-dri:amd64 libgl1-mesa-dri:i386 libgl1:amd64 libgl1:i386 steam-libs-amd64:amd64 steam-libs-i386:i386

Press return to proceed with the installation: 
.........
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libegl1 is already the newest version (1.4.0-1).
libgl1 is already the newest version (1.4.0-1).
libc6 is already the newest version (2.35-0ubuntu3.8).
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgl1-mesa-dri is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libc6:i386 is already the newest version (2.35-0ubuntu3.8).
libc6:i386 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libelf1:i386 (>= 0.142) but it is not installable
                        Recommends: libgl1-amber-dri:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.

Press return to continue:**_ 

Know when i press continue this tab closes and a window opens that says: 
**_you are missing the following 32 bit libraries libGL.so.1 libdrm.so.2_**
