### ISSUE TITLE
Steam update March 15th - Patch notes include Big Picture Mode fix for Nvidia GPUS - no change

### ISSUE THREAD

**Issue by hustin-paul** [ValveSoftware/steam-for-linux#9263]
#### Your system information

* Steam client version (build number or date):  March 15, 2023 (20:49:14) - 1678914933
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Received Steam client update, patch notes included it fixes issue with Big Picture Mode performance on Nvidia GPU's. After applying update, restarting steam - there is no change. BPM performance is still at roughly 10 fps in fullscreen. Extremely laggy (hardware acceleration?).

#### Steps for reproducing this issue:

1. Update Steam
2. Restart Steam
3. Switch to Big Picture Mode.

Hardware:
- AMD 5950x
- 64GB Ram
- Nvidia RTX 4090
- Arch 

Drivers up to date.

**Comment by papamikey** [comment]
The fix wasnt for Linux, it was a general fix. The Linux Hardware acceleration on Nvidia GPUs is still a huge issue

**Comment by kisak-valve** [comment]
Hello @hustin-paul, this issue is already being tracked at #8918. Closing as a duplicate.
