### ISSUE TITLE
Steam Client using 100% CPU when idle

### ISSUE THREAD

**Issue by lflo5727** [ValveSoftware/steam-for-linux#9266]
#### Your system information

* Steam client version (build number or date): 1676336721 (Feb 14, 2023)
* Distribution: EndeavourOS (Arch)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam client uses 100% CPU when idle. Doesn't go away after any time period it seems. Steam will continue using 100% CPU until closed or a game is opened. **When a game is running the Steam client's CPU usage drops to a normal level.** 

Once the game is closed the Steam client CPU usage spikes right back up to 100%. 

This issue started about 3 weeks ago for me. I reported in on [another issue here](https://github.com/ValveSoftware/steam-for-linux/issues/9207). 
However reviewing the original poster's issues, we seem to have been reporting on different issues. 

**I did not have any hardware changes** between when this issue started and beforehand. Likewise I did not have any software updates between when it started and not (leading me to speculate if it has to do with Steam's webviews).

I have updated Steam and all other packages since (using Arch package repos) regularly and no change. 
Unlike the other issue, I do not have any issues with high resource usage from Discord and the `amdgpu.aspm=0` kernel param did not resolve the issue. 

This issue is still outstanding for me. 

#### My machine details are below:
OS: EndeavourOS Linux x86_64 
Kernel: 6.2.6-arch1-1 
DE: Plasma 5.27.2 
CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.100GHz 
GPU: AMD ATI 03:00.0 Lucienne 
GPU Driver: Mesa 22.3.6-1
Memory: 8GB

#### Steps for reproducing this issue:

1. Open Steam and do not open a game

**Comment by lflo5727** [comment]
Wow, I completely overlooked what it was. Was messing with settings today and found what it was, it was background processing Vulkan shaders. Disabling background processing as well as letting it finish both let Steam drop back down to a normal CPU usage range.

Sorry for the non-issue.

**Comment by dfaure-kdab** [comment]
Isn't that still a bug? Why should background processing of vulkan shaders last forever and take as much CPU power as mining bitcoin?

**Comment by AntonUserPC** [comment]
> Isn't that still a bug? Why should background processing of vulkan shaders last forever and take as much CPU power as mining bitcoin?

Ubuntu 22.04.03 LTS is also have this bug
