### ISSUE TITLE
System crash when using System Information tool 

### ISSUE THREAD

**Issue by mcgravier** [ValveSoftware/steam-for-linux#9267]
* Steam client version (build number or date): Mar 15 2023, at 20:49:14
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: NO
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:
Steam system information gathering tool causes system crash around 10-30s after displaying the information. I managed to reproduce this consistently

On X this causes screen going black with total loss of video signal to monitor
On Wayland system goes into loop between black screen, and frozen desktop with graphical artifacts

#### Steps for reproducing this issue:

1. Start Steam
2. Go to Help->System Information
3. Let the tool generate system info
4. Crash should happen within 30 seconds

Its worth noting I recently updated motherboard BIOS to fix system stuttering caused by fTPM issue

<details><summary>Detailed system info:</summary>

```
Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  PRIME B350-PLUS
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 3950X 16-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4761 Mhz
    32 logical processors
    16 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.1.19-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101007
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20230118.0

Video Card:
    Driver:  AMD AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.1.19-1-MANJARO)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.3.5
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x1002
    DeviceID:  0x73bf
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 3840 x 2160
    Primary Display Size: 24.88" x 14.17" (28.62" diag)
                                            63.2cm x 36.0cm (72.7cm diag)
    Primary VRAM: 16384 MB

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  32003 MB

VR Hardware:
    Headset: Valve Index (lighthouse)
    Base station or sensor: Valve Corporation Valve SR Imp (lighthouse)
    Base station or sensor: Valve Corporation Valve SR Imp (lighthouse)
    Controller: Valve Knuckles Right (lighthouse)

Miscellaneous:
    UI Language:  English
    LANG:  pl_PL.UTF-8
    Total Hard Disk Space Available:  432241 MB
    Largest Free Hard Disk Block:  159051 MB

Storage:
    Number of SSDs: 2
    SSD sizes: 2000G,480G
    Number of HDDs: 0
```

</details>

**Comment by kisak-valve** [comment]
Thanks, that confirms that this is a video driver issue. This should be reported to your video driver vendor or the relevant packages maintainers for your video driver.

As a basic test, I'd try to reproduce the issue with AMDGPU-Pro disabled or uninstalled.

**Comment by rodehoed** [comment]
I have this one with a 6800XT on Fedora 37 with 22.3 Mesa drivers.  It looks very much like this on https://gitlab.freedesktop.org/drm/amd/-/issues/2384

**Comment by TheSHEEEP** [comment]
I have the same issue and the same GPU as @rodehoed .
Apparently, this is a regression in the kernel (oof!) with the current 6.1.X LTS kernel and can be fixed by reverting to kernel 5.1.15-X .

**Comment by TheSHEEEP** [comment]
Apparently, you can "fix" the issue by reverting your kernel to 5.15-X, it's an issue in the newer 6.1.7+ kernels.
This can be done by installing the 5.15-X kernel and start using that in the GRUB menu.

Of course, since this hardware survey is the only thing that seems to be triggering the issue, I don't know if it's worth it to downgrade your kernel just for this.

But I'd expect the next round of hardware survey results to be somewhat skewed, given that the survey itself leads some systems to crash.

**Comment by jhiggins9999** [comment]
Steam client version (build number or date): Mar 15 2023, at 20:49:
Distribution (e.g. Ubuntu): Manjaro 
Opted into Steam client beta?: 
Have you checked for system updates?: YES
Apologies if this is spam or unnecessary, but I encountered this issue today when I was prompted to submit a hardware survey. If I lingered too long on the (I believe) second prompt that displays your hardware info, the system crashes. I repeated this two more times to make sure it was consistent. I was able to submit the survey by very quickly clicking next during that step. I was again able to reproduce the behavior when I went through @mcgravier's steps.

**Comment by kisak-valve** [comment]
The current understanding of this issue is that this issue is a kernel regression with VA-API which might only affect AMD Navi 2X cards. There's nothing to be done on Valve's side to fix this properly.

This needs to be resolved in the video driver's kernel module.

**Comment by mcgravier** [comment]
Looks like SteamVR is now affected as well, even on kernel 5.15

Crashes every time, with video driver error

**Comment by Lamdarer** [comment]
FYI There is another workaround! In the new Steam Beta I can open the new System Information Window and also mark and copy its content.

**Comment by kisak-valve** [comment]
Hello @mcgravier, your symptoms do not match this issue report.

Hello @Lamdarer, the extended diagnostics information which exercised the VA-API render path has been separated into a new window with the current Steam client beta. You should be able to find that at `Steam` -> `Help` -> `Steam Runtime Diagnostics`.

**Comment by PinkBunnyBun** [comment]
I've also experienced this issue on Fedora.

**Comment by n00btube3D** [comment]
I believe this bug is gone. (System Runtime Diagnostics doesn't crash GPU when I test it)

**Comment by Lamdarer** [comment]
Can confirm, for me the System Runtime Diagnostics does not crash the GPU as well and works fine. (AMD 6800 XT, Mesa 23.1.9, Kernel 6.5.5, Manjaro Linux)

**Comment by mcgravier** [comment]
As of Driver: AMD AMD Radeon RX 6900 XT (navi21, LLVM 16.0.6, DRM 3.54, 6.5.5-1-MANJARO)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.9-manjaro1.1

Crash doesn't happen anymore - is seems the issue is gone
