### ISSUE TITLE
Steam app doesn't starts on second relaunch after first time launching.

### ISSUE THREAD

**Issue by psarapkin** [ValveSoftware/steam-for-linux#9269]
#### Your system information

* Steam client version (build number or date): 1.0.0.75
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam doens't starts second time after successful first launch. 
I have installed Steam on Fedora 37. I successful launched it. I installed CS:GO, and my CS:GO started, and I have played it. There were no problems. The problem is that I cannot start it second time. When click on Steam in Applications (Gnome, Activities), it doesn't start. 
When I try to run a command "steam" in terminal I get this:

> steam.sh[10591]: Running Steam on fedora 37 64-bit
steam.sh[10591]: STEAM_RUNTIME is enabled automatically
setup.sh[10663]: Steam runtime environment up-to-date!
steam.sh[10591]: Steam client's requirements are satisfied

And after that nothing happens. 

#### Steps for reproducing this issue:

1. Install Steam on Fedora Linux 37. 
2. Launch Steam, Install CS:GO, play CS:GO.
3. Exit Steam, restart computer. 
4. Try to Launch Steam from Applications

**Comment by kisak-valve** [comment]
Hello @psarapkin, when you ran `steam` from a terminal, did it return to a prompt after your snippet? Can you check if Steam is completely closed?

This reads like there is a leftover running Steam process. We see similar terminal spew when the newly started instance sees the running instance and does a hand off.

**Comment by psarapkin** [comment]
@kisak-valve Hi. I need to say that I forgot to say that I use GNOME on Fedora. 
Also, there are two ways to start GNOME. I can start GNOME on Wayland or I can start GNOME on X.Org. The difference between them is that X.Org uses the nvidia drivers.  May be I wrong, but only using X.Org the "GreenWithEnvy" starts without error and NVidia Settings shows all information about graphics card. And also I have NVidia Optimus configuration (this is a notebook with integrated(Intel UHD) and discrete (NVidia) cards). 
So, I want to start steam on X.Org because I want my nvidia card to be used. 

So, what did I figure out? Two things:
1. The Steam starts on Wayland without problems. But, I want to run Steam on X.Org. 
2. If I launch Steam from Applications menu in GNOME - then Steam doesn't starts. But, if I launch Steam using the terminal with command "steam" (I wanted to check your question above) - the steam has started. But it started without problems in case when I ran this command right after the operating system started.

**Comment by psarapkin** [comment]
Command `ps -aux | grep -i steam`
gives me this after I start steam from Applications menu
10247  0.1  0.0      0     0 ?        Zl   23:01   0:00 [steam] <defunct>

**Comment by psarapkin** [comment]
> 10247  0.1  0.0      0     0 ?        Zl   23:01   0:00 [steam] <defunct>

**Comment by kisak-valve** [comment]
Thanks for the additional details. I'm fairly sure this is the issue being tracked at #8179 and the workaround in the opening post of that issue should avoid the issue.

Closing in favor of the older issue report.
