### ISSUE TITLE
`Steam - Logged in Elsewhere`

### ISSUE THREAD

**Issue by john-peterson** [ValveSoftware/steam-for-linux#927]
### Problem

Logging in to the Linux client logs out the Windows client and vice versa with the message

> Your account '' is currently in use at another machine.
> You'll need to shut down Steam on your other computer in order to log in here.
### Suggestion

I argue that multiple simultaneous logins should be allowed because
- it's not a significant effort to implement
- users sometimes have more than one device with Steam
- other popular services such as Skype allow this

**Comment by kisak-valve** [comment]
Closing as this no longer applies since in-home streaming was added to the Steam client.
