### ISSUE TITLE
Library tab UI shifted upward in the March 15th 2023 update

### ISSUE THREAD

**Issue by QuanMCPC** [ValveSoftware/steam-for-linux#9271]
#### Your system information

* Steam client version (build number or date): March 15th 2023
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After installing the latest update, when I go to the Library tab, I see that the whole UI of the Library got shifted up, resulting in some part of the UI cutting up and black box below. I have to scroll the UI down using the scrollbar to make the UI shifted back down correctly.

Screenshot (Library games censored for privacy reason) (don't ask)
![problem](https://user-images.githubusercontent.com/60545346/225820981-7c401647-a9e5-4ddd-8cdc-305a92769ada.png)

#### Steps for reproducing this issue:

1. Install latest update
2. Go to the library tab
3. Observe

**Comment by kisak-valve** [comment]
Hello @QuanMCPC, this issue is already being tracked at #9260. Closing as a duplicate.
