### ISSUE TITLE
Cloud Saves are forcibly enabled every time steam is closed and re-opened

### ISSUE THREAD

**Issue by jimmon89** [ValveSoftware/steam-for-linux#9274]
#### Your system information

* Steam client version (build number or date): March 17th 2023, at 18:27:00
* Distribution (e.g. Ubuntu): Garuda Linux (Arch Derivative)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since today at minimum, possibly last night as well, Steam re-enables the syncing of cloud saves every time the client closes and then re-opens.
turning cloud saves off only disables them until you close steam
for years prior to this popping up I've always kept cloud saves disabled due to slow internet. and it's never been a problem.
and i'd prefer if they stayed disabled.

#### Steps for reproducing this issue:
1 - (log in)
2 - (Cloud sync is enabled)
3 - (Disable cloud sync and then click "Okay")
4 - (Go the the "Steam" menu and click "Exit")
5 - (Wait for steam to fully stop)
6 - (Open Steam)
7 - (Cloud sync is once again enabled)

if you need any more info i can provide it on request.

**Comment by Gamertech** [comment]
**Your system information**

- Steam client version (build number or date): March 17th 2023, at 18:27:00 - Flatpak
- Distribution (e.g. Ubuntu): Fedora 37
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes

Can confirm the exact same behaviour starting after the burst of client updates the past couple of days.

After starting the Steam client, cloud sync will be globally enabled automatically. Disabling it in settings, closing and reopening the client will show it's re-enabled again.

**Comment by Stratagerm** [comment]
Can also confirm.

**Comment by koreanfan** [comment]
debian linux, same issue

**Comment by philer** [comment]
Same on Linux Mint 21

**Comment by aditzul89** [comment]
Yes, same . I can reproduce the issue like the OP, with the same conditions.
Ubuntu  20.04.5 LTS

**Comment by jimmon89** [comment]
i was informed of a potential fix for this issue in the steam beta, and it fixes it for me.
so if you don't want to, or can't wait, try the beta

**Comment by Gamertech** [comment]
Fixed in today's stable update. Thanks!

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
