### ISSUE TITLE
> > Fedora 37. I feel dumb, I completely forgot about ReBAR. I can't check right now, but when I get there should I have it on or off?

### ISSUE THREAD

**Issue by Luigui87** [ValveSoftware/steam-for-linux#9276]
> > Fedora 37. I feel dumb, I completely forgot about ReBAR. I can't check right now, but when I get there should I have it on or off?
> 
> On

See, if I have ReBAR on with my 3700X/6800XT, in-menu load times are insufferable, taking at least a minute or more to load into Customization, MP, or the store. With it off, they're fine 🤔 Any ideas?

System:

- CPU: AMD Ryzen 7 3700X
- RAM: 32GB DDR4 2400
- GPU: AMD RX 6800XT
- Storage: Samsung 970 Evo Plus 2TB
- OS: Fedora Workstation 37
- DE: Gnome (Wayland)

_Originally posted by @9thdude in https://github.com/ValveSoftware/Proton/issues/5030#issuecomment-1472461173_

**Comment by kisak-valve** [comment]
This is a general system config issue and unrelated to the Steam for Linux client. Use another medium.

Closing as invalid.
