### ISSUE TITLE
Accessibility: have an option to increase font-size

### ISSUE THREAD

**Issue by m0glan** [ValveSoftware/steam-for-linux#9288]
Large text is something that can be enabled in GNOME accessibility settings on Ubuntu, however the text in Steam still looks tiny by comparison with other applications. I was wondering if it would be possible to have the option to scale the text to, say, 125%.

**Comment by kisak-valve** [comment]
Hello @m0glan, this issue is already being tracked at #5460 / #5908. Closing as a duplicate.
