### ISSUE TITLE
Shifted keys cannot be set as keyboard mapping 

### ISSUE THREAD

**Issue by kohend** [ValveSoftware/steam-for-linux#9291]
#### Your system information

* Steam client version (build number or date):  21/03/23
* Distribution (e.g. Ubuntu):  SteamOS and Ubuntu 22.04
* Opted into Steam client beta?: no
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Went to big picture mode, tried to set the keyboard + button as a mapping for a controller button, it uses shift alone, tried using a BT keyboard to press the key, tried all the steam deck buttons.

#### Steps for reproducing this issue:

1. Enter big picture mode/game mode on the deck
2. Edit a controller layout
3. Try to map a button to a keyboard key that needs shift to be accessible.
4. Fail

**Comment by kisak-valve** [comment]
Hello @kohend, my understanding is that this should be binding Shift to the button, then selecting the gear icon beside it and selecting `Add extra command`, but you've most likely encountered #9277.

Closing in favor of the older issue report.
