### ISSUE TITLE
How to enable CJK input method?Or change to CJK keyboard layouts in Big Picture Mode?

### ISSUE THREAD

**Issue by kamikaze211** [ValveSoftware/steam-for-linux#9302]
#### Your system information
Computer Information:
    Manufacturer:  ASUSTeK COMPUTER INC.
    Model:  DIY-APE B660 PRO MAX PLUS OC
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  12th Gen Intel(R) Core(TM) i5-12400
    CPU Family:  0x6
    CPU Model:  0x97
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  5600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.2.8-x64v1-xanmod1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12101007
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20230118.0

Video Card:
    Driver:  AMD AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.49, 6.2.8-x64v1-xanmod1-1)
    Driver Version:  4.6 (Compatibility Profile) Mesa 23.0.0
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 143 Hz
    VendorID:  0x1002
    DeviceID:  0x73ff
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  3840 x 1620
    Desktop Resolution: 3840 x 1620
    Primary Display Size: 31.38" x 13.15" (34.02" diag)
                                            79.7cm x 33.4cm (86.4cm diag)
    Primary VRAM: 8192 MB

Sound card:
    Audio device: Realtek ALC897

Memory:
    RAM:  31806 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.UTF-8
    Total Hard Disk Space Available:  1748413 MB
    Largest Free Hard Disk Block:  780603 MB

Storage:
    Number of SSDs: 7
    SSD sizes: 2048G,2000G,1000G,1000G,256G,63G,0B
    Number of HDDs: 0
   

* Steam client version (build number or date): steam 1.0.0.76-1;steam-native-runtime 1.0.0.75-3
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### 
Hello,I'm an Archlinux user.
I'm now having an issue with CJK input method.I could not input Chinese,Japanese,nor Korean languages with linux steam cllient.
I tried some other ways,such as using plasma's Krunner hotkey,to enable me typing CJK language on it,and copy the things I typed,and paste them into steam or games.
And also I heard that Steamdeck can let users typing their language by changing the keyboard layout in steam settings.
So I also wonder if I can use the same way in Big Picture Mode,but I found there is no Chinese,Japanese,Korean language keyboard layout in steam settings.
I tried to reinstall the steam package,but got the same resoult.
So what can I do for it?
Or is it just a bug?

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @kamikaze211, this issue is already being tracked at #781 / #3255. Closing in favor of the older issue reports.
