### ISSUE TITLE
Missing "Controllers" tab in game properties | Steam Deck Desktop Client 

### ISSUE THREAD

**Issue by yacinbm** [ValveSoftware/steam-for-linux#9303]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Steam OS
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/yacinbm/1d2d1ec1c1cfc29d5d582f720caa58c0): 
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Proton 5.13+
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: soldier 0.20230228.42394

#### Please describe your issue in as much detail as possible:
I just installed the ([hid-tmff2](https://github.com/Kimplul/hid-tmff2)) driver for the Thurstmaster T300RS racing wheel. The wheel is correctly recognized by the OS, and was tested with [oversteer](https://github.com/berarma/oversteer) and [fftest](https://man.archlinux.org/man/fftest.1.en). 

That being said, whenever I try to launch a game with the default Steam Deck Steam client, my wheel is not recognized. After some diagnosis, I figured out that the issue came from an incompatibility with Steam Input. That being said, the default Steam Deck client does not allow the user to disable Steam Input in the properties of a game. The `Controllers` tab in the game properties is not there for the user to configure.

In order to fix this, I had to overwrite the default Steam client with the one found on pacman, which is less than ideal. I think this option should be added to the Steam Deck default client. 

(All of this was made in Desktop mode of course)

#### Steps for reproducing this issue:

1.  Install a game on the Steam Deck Steam client
2.  Go to the game properties
3.  Notice there is not `Controllers` tab

**Comment by TTimo** [comment]
Hello @yacinbm,

Steam Input only supports joysticks and game pads. Racing wheels are not supported, so it is expected that nothing would show up under Controllers. If the game you are running has support for racing wheels then it should be able to configure and use it as normal however. If that is not happening then it is a bug.

**Comment by TTimo** [comment]
Re-reading through this with @kisak-valve's help, I think I misunderstood what the issue being reported is on here. This behavior of not showing the controllers tab in desktop mode is intentional.

Try running without the `-steamdeck` option and it should come back. Be aware that this tab enables exposes some settings that are not available under gamescope, so you may break things in gamescope that you'll have to come back to desktop to fix.

**Comment by TTimo** [comment]
If you add oversteer or fftest as a non-steam shortcut and run them (from desktop mode), is the wheel still detected? And is there a specific steam game you tested in turn that the wheel is not detected with? Rather than disabling Steam Input we should identify and fix why having it enabled is causing issues.

**Comment by yacinbm** [comment]
Hi @TTimo, so far, I have tested Dirt Rally, F1 2019 and Assetto Corsa, all three of which do not detect the wheel. The wheel also doesn't appear when running `proton control` as a launch option. That being said, upon replacing `steam-jupyter-stable` by the default Arch client, the wheel now appears in `proton control`, when disabling Steam Input (but the games wont run anymore).

I'll try to add oversteer as a non steam command ASAP and launch steam without the `-steamdeck` tag and report back. I'm ok with this not working in gaming mode, as I'm only using the wheel when I'm docked with a KB and mouse.

**Comment by yacinbm** [comment]
Quick update. Adding oversteer as a non steam game and launching it works as intended. The wheel is detected and works properly with force feedback and all. 

You are also correct that launching `steam.sh` with no argument makes the Controller sub menu available. An interesting side note is that by looking at the steam startup logs, I can see that it correctly identifies my racing wheel, regardless of the `-steamdeck` parameter:
```
Local Device Found
  type: 044f b66e
  path: sdl://1
  serial_number:  - 0
  Manufacturer: 
  Product:      Thrustmaster T300RS Racing wheel
  Release:      100
  Interface:    -1
```
After attempting to launch Dirt Rally in non-steamdeck mode, I noticed that it actually downloaded an additional ~2GB of data and it actually switched to the Native Linux version of the game. I don't know why the Deck doesn't use that version by default but w/e. I got an error 127 which was promptly fixed by installing the missing `libxcrypt-compat` with `pacman -S libxcrypt-compat`. And voila! The game works and recognizes the wheel properly! That bein said, I feel like instead of fixing the issue, we just circumvented it, since Dirt Rally doesn't use Proton in this version, it just runs natively. 

This is why I'll get back to you once I get Assetto Corsa running, which uses Proton. I had a working install of AC in Deck mode, but it doesn't want to run in non-deck mode. There are a few tutorials to get AC running on Linux PCs, so I'll report back if I can get it working. It's weird to me that a working install in deck mode would stop working, but hey.

Let me know if you need any more logs/tests on my side!

**Comment by TTimo** [comment]
Thanks for the info, very useful. We suspect the problem may be coming from SDL2 ignoring the racing wheel due to the `SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES` environment variable being set when Steam Input is enabled.

This variable is set by the Steam client and tells SDL2 to ignore gamepads and joysticks and use the Steam Input virtual one instead. It should not ignore non-gamepad things like a racing wheel but what you describe sounds like maybe it does.

In order to test this, you'd need to wrap the launch of Dirt Rally in a shell script (or edit the launch shell script if it already has one), and unset the variable with something like `unset SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES`.

**Comment by yacinbm** [comment]
Did some more experimenting, and I set my launch options to the following (Dirt Rally is using Proton 7.0 on my side):
`"/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin/wine" control; %command%`
This opens wine's control.exe in the Steam environment. I can actually see my wheel in the peripheral list, but none of the inputs work under the `Test Joystick` tab. The Deck's joysticks work though, just not the wheel. 

![control](https://user-images.githubusercontent.com/57112334/228728360-38f67b9c-acde-45cc-a1e6-d1c8201e0c9e.png)

If I run the same command (`"/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin/wine" control`) outside of Steam's environment (in a console for instance), the wheel is detected AND works as intended. Adding the `unset SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES` parameter also does not change anything.

**Comment by yacinbm** [comment]
Did a little more testing, and I modified my Dirt Rally launch options to:
`unset SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES; "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/dist/bin/wine" control; %command%`
which opens my Proton's Wine's control applet. As you can see, the wheel does appear in the list of devices, and the inputs work!
![control](https://user-images.githubusercontent.com/57112334/228729807-8de2f489-b515-4811-b121-23816073c12f.png)
![control_works](https://user-images.githubusercontent.com/57112334/228730559-6897060a-e9d7-4b75-b262-851b68aae8f6.png)
That being said, the wheel is still not recognized in game, and no input is detected when trying to update my key binds.

Let me know if you want me to test anything else!

**Comment by yacinbm** [comment]
Quick update,

After having a search in the hid_tmff2 github issues, I stumbled upon [this thread](https://github.com/Kimplul/hid-tmff2/issues/54) where users have reported issues with Proton versions more recent than 5.0-10.

To test this, I installed Assetto Corsa with Proton 5.0-10 and my steering wheel is indeed detected when executing `protontricks -c "wine control" 244210`, I can see that my wheel's inputs work as intended. I can even get to AC's main menu and set my controls to use the wheels and pedals, great! All of this was done with the default Steam Deck's client (so with the `-steamdeck` parameter).  

That being said, when I get to driving in game, my steering wheel and pedals don't work, as the game is still only recognizing the inputs from my Deck's controller, which I _think_ is related to Steam Input. 

I'll try to find a way to unset the  `SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES` parameter correctly and report back ASAP. Thanks!

**Comment by yacinbm** [comment]
After even more tinkering, it seems that the issue appears with any version of Proton greater than 5.13. The wheel is recognized by Proton (I ran `protontricks -c "wine control joy.cpl" <my game id>` and the wheel is listed) but the inputs are not recognized. 

A similar issue has been reported on the hid-tmff2 GitHub page, where some users have reported that adding a udev rule for the wheel fixed their issue. Unfortunately, it did not for me.

Side note: I was able to make my wheel work with Assetto Corsa on the Deck with Proton 5.13, but I had to disable the Deck's controller, or else the game would read the controller's inputs instead of my wheel.

**Comment by yacinbm** [comment]
After having tinkered with this for two whole weeks, I don't think the missing menu is the issue. Will re-open a ticket with a more descriptive title.

**Comment by TTimo** [comment]
https://github.com/ValveSoftware/Proton/issues/6674

**Comment by yacinbm** [comment]
Thanks @TTimo I opened a ticket with a little more focused info with my findings, I hope this is ok.
