### ISSUE TITLE
System Information window incorrectly shows all available storage devices as SSDs

### ISSUE THREAD

**Issue by barfin** [ValveSoftware/steam-for-linux#9309]
#### Your system information

* Steam client version (build number or date): Mar 29, 2023
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Here's my system info according to steam 
https://gist.github.com/barfin/18618eeb838a8ff06dedfa713e0ce593#file-gistfile1-txt-L79
And here's my system storage list, not only it thinks HDDs are SSDs but it also thinks CardReaders are also 0GB SSDs
![image](https://user-images.githubusercontent.com/37030489/229028771-347722bc-1785-43cb-84b6-e0cce4e02ae6.png)

#### Steps for reproducing this issue:

1. Have a Non-SSD storage and Have steam

**Comment by kisak-valve** [comment]
Hello @barfin, this issue is already being tracked at #8966. Closing as a duplicate.
