### ISSUE TITLE
High CPU usage (25%) when Friends List up on Steam Beta

### ISSUE THREAD

**Issue by Chosin137** [ValveSoftware/steam-for-linux#9314]
#### Your system information

 Kernel Version 6.2.8-1 | Mesa 23.0.1-1 | Intel i7 M 620 CPU |  Nvidia NVA5 Graphics.

* Steam client version (build number or date): Mar 29 Package 1680115169
* Distribution (e.g. Ubuntu): Manjaro STABLE | KDE Plasma 5.27.3 Wayland
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:

When the Friends list is displayed on the screen I'm seeing 25% CPU usage in system monitor consistently. Closing the Steam Friends list drops the CPU usage back to standard levels.

#### Steps for reproducing this issue:

1. Start Steam
2. Open and display Friends List

**Comment by kisak-valve** [comment]
Hello @Chosin137, this issue is already being tracked at #7241 / #7413. Closing as a duplicate.
