### ISSUE TITLE
Steam crashes on startup when 10 bit color is enabled

### ISSUE THREAD

**Issue by happysmash27** [ValveSoftware/steam-for-linux#9315]
#### Your system information

* Steam client version (build number or date): Don't remember; Steam crashes before I can get this
* Distribution (e.g. Ubuntu): Gentoo, but the same issue exists for others on Manjaro and Ubuntu as described in https://steamcommunity.com/discussions/forum/1/3105768154692556817/ . 
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
When enabling 10 bit colour, as described in https://steamcommunity.com/discussions/forum/1/3105768154692556817/, Steam's updating window shows in weird pink colours, and then Steam crashes upon startup with the following log: https://gist.github.com/happysmash27/dfa51dc617362f9c0367e2d230d803e7 . A similar issue is reported on the Steam forums - https://steamcommunity.com/discussions/forum/1/3105768154692556817/ - and in the page that describes how to enable 10 bit color in the first place, as one of the major issues with it. It should not be hard to reproduce this issue at all. 

#### Steps for reproducing this issue:

1. As described in https://linuxreviews.org/HOWTO_enable_10-bit_color_on_Linux, create a file `/etc/X11/xorg.conf.d/30-screensetup.conf` with the following contents to enable 10-bit color: 
```
Section "Screen"
  Identifier    "Default Screen"
  Monitor        "Configured Monitor"
  Device         "Configured Video Device"
  #               24 for 8-bit or 30 for 10-bit
  DefaultDepth    30
EndSection
```
2. Start Steam

**Comment by kisak-valve** [comment]
Hello @happysmash27, this issue is already being tracked at #4399.

Closing as a duplicate.
