### ISSUE TITLE
Newest beta client results in `Failed to load steamui.so`

### ISSUE THREAD

**Issue by ensiform** [ValveSoftware/steam-for-linux#9317]
#### Your system information

* Steam client version (build number or date): April 3rd 2023 https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3684547928702031740
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] YES 
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
Relaunching steam after this update took place results in:

`Failed to load steamui.so - dlerror(): steamui.so.so.0: cannot open shared object file: No such file or directory`

#### Steps for reproducing this issue:

1. Update to latest steam beta
2. Relaunch after update
3. Crash

**Comment by cr1ogen** [comment]
Same error on Debian

**Comment by xangelkawaiix** [comment]
same here

**Comment by kisak-valve** [comment]
Hello @ensiform, you should be able to manually opt out of Steam's client beta by removing `~/.local/share/Steam/package/beta`, but we'll need a Steam dev to take a look at this for a proper fix.

**Comment by sylware** [comment]
idem here, I did add a symbolic link steamui.so.so.0 to steamui.o then I get a mmap failed  (after trying to load pulseaudio, which I don't have on my system, may be unrelated though).

**Comment by hustin-paul** [comment]
Same here on Arch. Anyone know how to opt out of beta with steam cli?

**Comment by BeepIsla** [comment]
Try running Steam with `-clearbeta` (As per https://help.steampowered.com/en/faqs/view/0188-6BB7-D467-08E1) I assume it works on both Windows and Linux

**Comment by kisak-valve** [comment]
Hello, it looks like this issue might have been quietly resolved overnight. Please retest this issue.

**Comment by sylware** [comment]
steamui soname is fixed here, but now I run into a pulseaudio->alsa fallback crash:

PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
mmap() failed: Cannot allocate memory
... the previous message repeated many times...
Assertion 'c' failed at pulse/context.c:1060, function pa_context_set_state_callback(). Aborting.

**Comment by kisak-valve** [comment]
Hello @Eschguy, It's possible the affected build of Steam was queued overnight and this is a belated sighting.

If you manually opt out of Steam's client beta, let Steam update, and opt back into Steam's client beta, and let it update again, can you reproduce this issue?

**Comment by dsalt** [comment]
Seeing similar here, though I'm actually seeing two different (possibly related) failures depending on how I start it. (Current ‘publicbeta’ build, build stamp 1680578442.)

With `-no-cef-sandbox`:
```
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
ATTENTION: default value of option vblank_mode overridden by environment.
CAppInfoCacheReadFromDiskThread took 138 milliseconds to initialize
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Failed to init SteamVR because it isn't installed
Assertion 'm' failed at pulse/thread-mainloop.c:248, function pa_threaded_mainloop_in_thread(). Aborting.
```
(I don't use pulseaudio.)

Without `-no-cef-sandbox`:
```
steamwebhelper.sh[21585]: Runtime for steamwebhelper: defaulting to /home/ds/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[21585]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[21656]: Runtime for steamwebhelper: defaulting to /home/ds/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[21656]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
src/steamUI/steamuisharedjscontroller.cpp (352) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (352) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (352) : Fatal assert; application exiting
src/steamUI/steamuisharedjscontroller.cpp (352) : Fatal assert; application exiting
04/04 18:06:57 Init: Installing breakpad exception handler for appid(steam)/version(1680578442)/tid(21435)
```

(Devuan stable, but with various items including libc6, libdrm, libvulkan pulled in from testing.)

**Comment by kisak-valve** [comment]
Hello @sylware, @dsalt, can one of you please open a separate issue report so that your follow up issue can be tracked properly?

**Comment by Eschguy** [comment]
Hey @kisak-valve, I was able to update into beta now. Thanks!
