### ISSUE TITLE
Game properties doesn't spawn a separate window and can't be closed

### ISSUE THREAD

**Issue by rLy07** [ValveSoftware/steam-for-linux#9322]
#### Your system information

* Steam client version (build number or date): 1680578442
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Opening a game's properties now opens within the library (new feature?) but it's not possible to close it. It becomes unresponsive and doesn't disappear, rendering the library useless and need to restart the client. It's not possible to navigate away from the properties window even when it's still working, like going to the store or community and back.

#### Steps for reproducing this issue:

1. Open the properties for a game
2. Try to close properties using the 'x' in the top right corner

**Comment by xpander69** [comment]
confirming. Same issue with the latest beta. no seprate window and the properties gets stuck inside the main client window, with x not closing it and clicking on library doesn't bring library back into focus either.

**Comment by Leopard1907** [comment]
Same issue, beta client.

**Comment by Tourfaint** [comment]
Can confirm, just updated and can reproduce the bug.

**Comment by Billli11** [comment]
Same issue.

You can run `killall steamwebhelper` to "reset" the library tab after freeze as a workaround for now

**Comment by kisak-valve** [comment]
Hello, per "Fixed issue where viewing app properties caused the Steam client to be unusable" in the [2023-04-04](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3684547928704734445) Steam client beta, please update your Steam client and retest this issue.

**Comment by Tourfaint** [comment]
Updated, seems to be working fine now, properties open as a window and close just fine, thank you!

**Comment by Leopard1907** [comment]
Fixed on my end as well, thanks!

**Comment by rLy07** [comment]
Fixed for me as well, thank you!
