### ISSUE TITLE
Compatibility settings fail to detect game exited and get locked indefinitely

### ISSUE THREAD

**Issue by metov** [ValveSoftware/steam-for-linux#9327]
#### Your system information

* Steam client version (build number or date): Mar 29, 2023
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After exiting a game that is running with Proton, I want to try running with a different Proton version. I go to game properties, compatibility, and see that the dropdown for selecting Proton version has mysteriously disappeared with no explanation.

This happens even when Steam itself detects that the game is not running and displays the `Play` button in the library page. It seems that the compatibility settings use some other, faulty mechanism to detect if the game is running. Or perhaps there is a UI bug where Steam forgets to unlock that UI after a game exits.

I expect the compatibility UI to not change at all whether the game is running or not. If I attempt to *change* the dropdown, that's when Steam should check whether it's running. If it is, Steam should display a clear error message and revert the dropdown to its previous value.

#### Steps for reproducing this issue:

1. Set game to run with Proton.
2. Observe that Steam displays green `Play` button.
3. Start game.
4. Observe that Steam detects the game is running and changes to blue `Stop` button.
5. Exit game.
6. Observe that Steam detects that the game exited and displays green `Play` button again.
7. Attempt to change the game's Proton version.
8. Observe that the dropdown has disappeared with no explanation.

**Comment by metov** [comment]
For other people who have this issue, the only workaround I know is to exit Steam and open it again. On a Steam Deck you will have to restart the whole OS.

**Comment by metov** [comment]
Maybe related to https://github.com/ValveSoftware/steam-for-linux/issues/9273 but honestly I couldn't tell what exactly that issue is about, it was too confusing.

**Comment by metov** [comment]
In the [patch notes](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3683422660277569472) for the April 18 Beta release, I saw:

> Fixed a case where the per-app Steam Play compatibility tool override dropdown would not appear

After enabling beta and installing this update, it seems like the issue is not happening. In fact, it even lets me change the Proton version while the game is running.

**Comment by kisak-valve** [comment]
Closing per the last comment.
