### ISSUE TITLE
Steam controller moves the cursor position, but not the cursor icon on Wayland.

### ISSUE THREAD

**Issue by Veprovina** [ValveSoftware/steam-for-linux#9328]
#### Your system information

AMD Ryzen 5 5600g 
32 GB DDR4 3200 Mhz CL22
Nvme SSD 512 GB Gen3

* Steam client version (build number or date): Mar 24 2023
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When using the Steam controller desktop mode, the right trackpad moves the cursor position, but not the cursor icon. I can see the things on the desktop, steam library and all getting highlighted, but the icon never moves, so it's impossible to use.
Here's a short video of it:

https://imgur.com/pW1AFTU

You can see the cursor is below the library entries, but as i move my thumb across the trackpad up and down, the library entries get highlighted, but the cursor stays where it is. It only moves at the end when i move it with my mouse to stop the recording.

I'm using GNOME Wayland, but this happened on KDE Wayland as well before. I tested it on KDE X11 and there it worked fine, so it's only an issue on Wayland.

#### Steps for reproducing this issue:

1. Use Wayland
2. Open Steam and turn on the Steam controller so it recognizes the controller and starts the desktop mode
3. Move the right trackpad in desktop mode

**Comment by kisak-valve** [comment]
Hello @Veprovina, this issue was previously evaluated multiple times and https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/431 probably has the most technical details behind it.

On the Steam side of this, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8604. Closing in favor of the older issue report.
