### ISSUE TITLE
text in details starts to jump around as it tries allign itself properly.

### ISSUE THREAD

**Issue by salt86** [ValveSoftware/steam-for-linux#933]
# Issue

The text in the game library is jumping around as it tries to render itself with and without a scrollbar, but it doesn't always happen. 

I've attached a video, as i couldn't get proper screenshots.
https://docs.google.com/file/d/0BwkoSonqQhcUd1cyWTU5aEZCY3c/edit
# Steps to reproduce

Start steam regularly and proceed to the detailed view in the library.

First, view a game that has friends playing or have played. (as far as i can tell) Second, view a game that has the same set of factors. Finally, click change category on the right side.

In my example, I viewed World of Goo that has 2 friends playing, then viewed Counter Strike that has 1 friend playing, I clicked change category on the right side, then the text 
It also happened when viewing World of Goo and Half Life (Beta)
in the main steam window started to jump around.
# Details

The window is sized at 992 x 1056 (changing the screen size has stoped the issue from happening again.
World of Goo was in a category called Linux, Half-Life was in a category called Half Life, and Counter Strke was without a category.

**Comment by kisak-valve** [comment]
Hello @kiddykoff, are you still experiencing this issue with an up to date client?

**Comment by kiddykoff** [comment]
I just tested it.

The window is slower to resize, but the text doesn't jump around or bug out like it used to.

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
