### ISSUE TITLE
Steam Storage Manager creates a separate entry on the KDE Plasma Taskbar.

### ISSUE THREAD

**Issue by OhaDerErste** [ValveSoftware/steam-for-linux#9336]
#### Your system information

* Steam client version (build number or date): March 24 2023
* Distribution (e.g. Ubuntu): Arch Linux, KDE Plasma 5.27.4 Wayland
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Steam Storage Manager creates a separate entry on the KDE Plasma Taskbar. This is the only steam window that does this afaik
#### Steps for reproducing this issue:

1.  Open Steam
2. Go to Settings -->Downloads --> Steam Library Folders
3. Main Steam Client window and Settings window get grouped. Storage manager adds another entry to the taskbar
![image](https://user-images.githubusercontent.com/77100649/231013000-f32dcc48-82b3-41e8-8adb-8b1c9888b2a3.png)

**Comment by OhaDerErste** [comment]
This also happens on the Steam deck

**Comment by kisak-valve** [comment]
Hello @OhaDerErste, this issue is already being tracked at #9235. Closing as a duplicate.
