### ISSUE TITLE
feature request: show controller battery level steamdeck-ui  

### ISSUE THREAD

**Issue by frzifus** [ValveSoftware/steam-for-linux#9342]
#### Your system information

* Steam client version (build number or date): Mar 24 2023
* Distribution (e.g. Ubuntu): Arch Based ([ChimeraOS](https://github.com/ChimeraOS))
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It is not possible to check the charge status of connected gamepads. Ideally, there should be a screen in the controller menu and a notification when the charge level falls below a certain threshold.

**Comment by kisak-valve** [comment]
Hello @frzifus, this feature request is already being tracked at https://github.com/ValveSoftware/SteamOS/issues/929. Closing as a duplicate.
