### ISSUE TITLE
Steam won't run on (K)Ubuntu 23.04

### ISSUE THREAD

**Issue by OlegAckbar** [ValveSoftware/steam-for-linux#9357]
#### Your system information

* Steam client version (build number or date): should be latest
* Distribution (e.g. Ubuntu): Kubuntu 23.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I upgraded my Ubuntu and tried to launch Steam it could not connect to network and I saw blank screen instead of store or library. Not that I completely reinstalled Steam I can't login because I see blank windows instead of login window. Here's screenshot of login screen and console log.
![изображение](https://user-images.githubusercontent.com/9915567/233650344-d54cf60d-9453-4e07-b6e5-769328522674.png)
https://gist.github.com/OlegAckbar/81ec047fc49886afe62aaed4668ce30a

#### Steps for reproducing this issue:

1. Upgrade Ubuntu from 22.10 to 23.04
2. Launch Steam

**Comment by smcv** [comment]
If that doesn't work, please look in `~/.steam/root/logs` for `cef_log.txt`, `steamwebhelper.log` or `webhelper.txt` and provide whichever ones exist as an attachment or Gist. (They might not all exist, that's OK.)

**Comment by kisak-valve** [comment]
Thanks @OlegAckbar, `/usr/bin/zenity: symbol lookup error: /lib/x86_64-linux-gnu/libsoup-3.0.so.0: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation` is the key detail and that issue is being tracked at #9356. Closing in favor of the older issue report.
