### ISSUE TITLE
Gyro input is disabled if it's behavior is set to "None" in controller settings.

### ISSUE THREAD

**Issue by KrisCris** [ValveSoftware/steam-for-linux#9359]
#### Your system information

* Steam client version (build number or date): 1681864962
* Distribution (e.g. Ubuntu): SteamOS 3.4.6
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES

#### Please describe your issue in as much detail as possible:

Steam disables gyro input from the controller when Gyro in controller settings is set to "None", resulting in emulators being unable to receive the gyro data anymore.

https://github.com/kmicki/SteamDeckGyroDSU/issues/45

**Comment by kisak-valve** [comment]
Hello @KrisCris, I'm failing to see how this is a bug. You're getting exactly what you told Steam Input to do.

Closing in favor of #8804.

**Comment by KrisCris** [comment]
But, the gyro data can be received when an overlay is open, like open the quick access menu. I don't know which one is bugged but I can't see why gyro data should be blocked. 

The steam gyro settings is about whether to use gyro to emulate other behaviors; whereas we just want raw gyro data handled by that software, then feed to emulators, I guess?

**Comment by KS-HTK** [comment]
No, I do agree with @kisak-valve take. None should block gyro data. What we actually want is an option to get raw gyro data. Not emulating anything at all. But None should still be an option to block gyro inputs.

I don't think this is a bug. Gyro data is recived in the overlay if the gyro is enabled for the default layout. Because game specific profiles only apply to the game not the overlay. Otherwise navigating the overlay is impossible if actions are mapped to keys for gameplay.

**Comment by xfechx** [comment]
Why is this happening? 
So many people have gyro to use DSU. This change will affect a lot. Why all of the sudden gyro set to none (which means no translation) suddenly turns gyro off? Please allow gyro to be set to gyro (seems obvious).

**Comment by KrisCris** [comment]
Yea, having to set the gyro emu to a random non-None value to be able to use raw gyro, doesn't make much sense to me.

**Comment by ds8k** [comment]
> Hello @KrisCris, I'm failing to see how this is a bug. You're getting exactly what you told Steam Input to do.
> 
> Closing in favor of #8804.

Closing in favor of an issue that's a year old with no responses, classy.

Wouldn't this also break any games that natively use gyro for aiming? Quake 2 Remaster for example
