### ISSUE TITLE
"Close" button on "Buy remaining cards on market" hangs steam client

### ISSUE THREAD

**Issue by jpwhiting** [ValveSoftware/steam-for-linux#9360]
#### Your system information

* Steam client version (build number or date): April 18, 2023
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Open steam client
2. Click Username -> Badges
3. Select a game to purchase cards for
4. Click "Buy remaining cards on market"
5. Click "Place order" button
6. Click "Close" button
7. Watch steam client do nothing, not close, etc.

Closing the gui and going back to Username -> Badges brings up the same hung view with Close button still visible, can't scroll it anymore, etc.

Expected result "Close" button should close the view and go back to badges view or something. To get back to badges view you have to completely exit the app from the tray icon and open it again.

**Comment by kisak-valve** [comment]
Hello @jpwhiting, this issue is already being tracked at #7897. Closing as a duplicate.

**Comment by jpwhiting** [comment]
Ah perfect. Thanks.
