### ISSUE TITLE
Steam broke Rabobank iDeal payments

### ISSUE THREAD

**Issue by NLBen** [ValveSoftware/steam-for-linux#9362]
![iDealbroken](https://user-images.githubusercontent.com/87259576/233835963-fb57db73-6ada-47cc-b4d9-5647693e2e0d.png)
#### Your system information

* Steam client version (build number or date): Mar 24 2023, 17:20
* Distribution (e.g. Ubuntu): Linux Mint 21.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
- Start Rabobank iDeal payment  
- Should load in and enable me to pay
- What happens instead is a completely blank screen, while I can login at the Rabobank normally at their site. This seems like Steam broke it - iDeal's site says there are currently no known outstanding issues
- Try it 4x and conclude Steam definitively broke the process while being locked out from making purchases by Steam

#### Steps for reproducing this issue:

1. Attempt an iDeal payment with the Rabobank at Steam
2. See a screen that doesn't load

**Comment by NLBen** [comment]
Attached screenshot of what exactly I'm getting (aka not working iDeal). Edited out a large chunk of the screenshot because of session-related risks.

**Comment by NLBen** [comment]
Little update - just to verify (forgot to do that earlier) I tried to do the same purchase in a regular browser - no issue there. It's something with the Steam web protocols I guess?

**Comment by BG51** [comment]
I also been having this issue since Thursday this week 20th of April 2023. And it only happens through the Steam application for pc for me, works fine through store.steampowered.com. Ive made a ticket which steam closed twice and after verifying that my friends had the same issue Steam told me just get with it, no their problem, all their stuff works they say. Full black screen after selecting Rabobank.

**Comment by Metal-spoon** [comment]
> Little update - just to verify (forgot to do that earlier) I tried to do the same purchase in a regular browser - no issue there. It's something with the Steam client web protocols I guess?

If I had to guess it's because the chromium version the steam client uses is outdated.
Have you tried the beta branch of the steam client?

**Comment by seek-dev** [comment]
People using an untrustworthy, unsecurable, closed-source browser like the Steam client to connect to third-party banking/payment service websites is a good example of why using chromium for a desktop client is a really terrible idea.

The responsible thing would, at least, be for Steam to explicitly block all other domains and defer all links to external browsers.  Consider this "bug" a wake-up for you to adopt better security practices.

**Comment by NLBen** [comment]
> > Little update - just to verify (forgot to do that earlier) I tried to do the same purchase in a regular browser - no issue there. It's something with the Steam client web protocols I guess?
> 
> If I had to guess it's because the chromium version the steam client uses is outdated. Have you tried the beta branch of the steam client?

Sorry for the late reply. Was testing some other stuff which was nagging me, and entirely forgot about the notice about the reply. Yes, the beta branch fixes it, because the beta branch doesn't open the Steam Browser but instead in a new browser screen (at least with the 29/4 update, the day after you posted).

**Comment by kisak-valve** [comment]
Closing per the last comment.
