### ISSUE TITLE
Unable to add a new library with beta flatpak

### ISSUE THREAD

**Issue by Wemmy0** [ValveSoftware/steam-for-linux#9368]
#### Your system information

* Steam client version (build number or date): Built: Apr 18 2023, 23:21:04 API: v020 package versions: 1681864962
* Distribution (e.g. Ubuntu): Fedora 38
* Opted into Steam client beta?: [**Yes**]
* Have you checked for system updates?: [**Yes**]

#### Please describe your issue in as much detail as possible:
After switching to the steam client beta, I'm unable to add a steam library folder. It's not that steam can't see the mount point of my drive (I've given it permissions in flatseal) but the menu to select a location can't even open. The **+** button is there but doesn't do anything.

Here is a video showing the issue, but unfortunately my mouse was hidden from the recording (I'm trying to click the + button).
[Screencast from 2023-04-26 20-39-32.webm](https://user-images.githubusercontent.com/116467716/234709084-db7b91c9-29a4-45f6-953c-d8a40cdb6ad2.webm)

#### Steps for reproducing this issue:

1.  Install steam from flathub
2.  Opt into beta
3.  Try to add a new library folder

**Comment by catalin260** [comment]
I'm having this issue also. And my steam client is not installed via flatpak

**Comment by catalin260** [comment]
> I'm having this issue also. And my steam client is not installed via flatpak

It works if I opt out from beta. I can configure the steam folders again

**Comment by Wemmy0** [comment]
Seems to be fixed with new UI update
At least for me

**Comment by yoyobuae** [comment]
Adding library folders is also broken for me in beta. This issue started when UI was updated.

The new UI opens file selection dialog that asks to select a regular file, not a folder. When I try to select the steam library folder there's only an "Open" button which opens the folder. Only way to actually get pass that dialog is to select regular file (not a folder). No matter which file I try to select the library folder is never added.

**Comment by kisak-valve** [comment]
Hello @yoyobuae, please see https://github.com/ValveSoftware/steam-for-linux/issues/9377#issuecomment-1527381613.

**Comment by darman96** [comment]
I have the original bug, I am on EndeavourOS and fresh non-beta, non-flatpak Steam.
