### ISSUE TITLE
Steam Beta - Filepicker doesn't open with some buttons

### ISSUE THREAD

**Issue by DonKatsu** [ValveSoftware/steam-for-linux#9373]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Fedora 37 KDE (Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
#### Please describe your issue in as much detail as possible:
Some buttons that should open the filepicker don't do anything when clicked.
Some examples include: the "Upload your avatar" button in profile options, or the "Upload an image" button in a chat window.

I noticed this prior to today's large update, but since Steam should now use native filepickers I'm opening this issue.
However, one exception is the "Browse..." button in the "Add Non-Steam Game" window. It **does** work, and opens KDE's filepicker.
#### Steps for reproducing this issue:

1. Click one of those above buttons
2. Nothing happens

**Comment by choskyo** [comment]
**Your system information**

    Steam client version (build number or date): 1683078372
    Distribution (e.g. Ubuntu): Manjaro 22.1.0 (X11)
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes

**Please describe your issue in as much detail as possible:**

Exactly identical to the original poster, except instead of KDE's filepicker when using that Browse button, I get gnome's.

**Steps for reproducing this issue:**

  Same as OP.

**Comment by danildf** [comment]
**Your system information**

```
Steam client version (build number or date): 1683078372
Distribution (e.g. Ubuntu): Gentoo (X11)
Opted into Steam client beta?: Yes
Have you checked for system updates?: Yes
```

**Please describe your issue in as much detail as possible:**

Same as what others have, except Browse button opens xdg-desktop-portal-gtk.

**Steps for reproducing this issue:**

Same as OP.

**Comment by shytzedaka** [comment]
My latest comment in #7485 Gives out an example on How 'Upload an image' or 'Upload Artwork' Does not work (with system information included) if it helps this issue.

**Comment by Nyamiou** [comment]
This issue is present on 1684372665, I also couldn't upload an avatar. I'm on Arch Linux with KDE.

**Comment by DonKatsu** [comment]
The file dialog now opens properly for me with 1684885503.

**Comment by shytzedaka** [comment]
Can confirm as well that it is working :tada: 
(Ubuntu 23.04, X11, Steam Version:  1684885503)
Tried it in Steam Chat and Choosing a profile picture.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/07f54e26-a6ef-4c47-ab68-321fa3caa80c)

**Comment by Zeron100Z** [comment]
Can confirm that as of 1685072487, the Filepicker opens as it should, though interestingly (for at least library cover art) the image refuses to update (process: right click on game, select 'set custom artwork', Filepicker opens, select image file, library entry's art fades out for half a second before fading in with the default art.)
Pop!_OS 22.04, X11, KDE

**Comment by DonKatsu** [comment]
Maybe this should rather be a new feature request issue, but the KDE file picker spwaned from friend chats doesn't have a filter for all filetypes.
Meanwhile the one spawned for uploading an avatar image doesn't have filters at all, resulting in all filetypes being shown.

**Comment by kzdixon** [comment]
Now that this release has come out the filepicker doesn't open for me anywhere where it is applicable; be it profile, chat, or adding a non-steam game. Its completely broken for me on i3wm. No output given in terminal when Steam is launched that way either after clicking the button that shoudl spawn `pcmanfm-qt` on my system.

**Comment by kisak-valve** [comment]
Hello @kzdixon, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kzdixon** [comment]
> Hello @kzdixon, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

https://gist.github.com/kzdixon/4d7c3e646956d53aca048d40aeca090b

**Comment by kisak-valve** [comment]
Thanks, https://gist.github.com/kzdixon/4d7c3e646956d53aca048d40aeca090b#file-gistfile1-txt-L2810-L2816 is the details to focus on. Looks like your system doesn't provide xdg-desktop-portal for Steam to interface to your UI of choice.

**Comment by lostgoat** [comment]
The problem outlined in this issue has been fixed. It only affected some buttons, like uploading an avatar.

It maybe be best to open a new issue to avoid confusion with the history in this thread. It sounds like for @kzdixon we are failing to fall back to the built in file picker when desktop portal is unavailable.
