### ISSUE TITLE
File picker requires picking files even when a directory is needed

### ISSUE THREAD

**Issue by tatokis** [ValveSoftware/steam-for-linux#9377]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Attempting to "Create a backup of the installed files to restore this game in the future" fails due to the file picker demanding a file is picked instead of a directory. The GTK 3 file picker shows up for me. It seems to not be instructed to allow the user to pick a directory, as even when you do end up navigating into an empty directory, the open button gets greyed out.

This appears to happen on anything that requests a path to a directory. For example, I am also unable to change the screenshot folder.

#### Steps for reproducing this issue:

1. Right click on game
2. Click `Properties`
3. Select `Installed Files`
4. Click `Backup game files`
5. Click `Browse...`
6. Attempt to pick a directory

**Comment by tatokis** [comment]
After digging further into this, it looks like steam is using the XDG Desktop portal.
```
method call time=1682678066.907058 sender=:1.389 -> destination=:1.402 serial=93 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=OpenFile
   string ""
   string "Create or select new Steam library folder"
   array [
      dict entry(
         string "handle_token"
         variant             string "steamfileopenportal1469229840"
      )
      dict entry(
         string "directory"
         variant             boolean true
      )
      dict entry(
         string "current_folder"
         variant             array of bytes "" + \0
      )
      dict entry(
         string "multiple"
         variant             boolean false
      )
      dict entry(
         string "modal"
         variant             boolean false
      )
      dict entry(
         string "filters"
         variant             array [
            ]
      )
   ]
```

The `directory` bool was added in [version 3](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser) of the interface. My system has version 2, and thus ignores it. I'm not sure what can be done about this, but it's an unfortunate omission of a critical feature.

**Comment by lostgoat** [comment]
Thanks for the info, sadly it looks like we'll need to fall back to a different file picker if we detect version 2 and a directory is requested.

**Comment by Benedolt** [comment]
I have exactly the same issue trying to a Steam library folder. I have an existing library folder on another disk, steam "forgot" about it and I can't add it back, because the filepicker doesn't accept directories. 

Running the steam client beta (deb) on Ubuntu 20.04.

**Comment by z0rti** [comment]
> I have exactly the same issue
There is a workaround in #9666 that worked for me (manually adding via console)

Maybe there could be a message like "old portal detected please upgrade" or
if portal version < 3 detected then do not use it, but present a console or input field one could paste the path in?

**Comment by Benedolt** [comment]
Can confirm @z0rti's finding: With the latest client beta the old school file picker shows up, but I can only navigate the contents of ~/.steam/steam.

![Screenshot from 2023-07-01 12-04-12](https://github.com/ValveSoftware/steam-for-linux/assets/3541525/f240056e-83c7-41cd-a56c-07947396b22b)

**Comment by segaretroboy** [comment]
Also having this issue
Runtime info here
https://gist.github.com/segaretroboy/ff1f919831542237d9e29d1c6af35ff7 
![20230704_21h25m29s_grim](https://github.com/ValveSoftware/steam-for-linux/assets/20261168/b8e23679-0f00-4213-86e5-a4a204b98cfa)

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.

The follow up issue is being tracked at #9797.
