### ISSUE TITLE
Steam beta: steam config menu cannot assign hot keys to special key

### ISSUE THREAD

**Issue by Billli11** [ValveSoftware/steam-for-linux#9380]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Arch Linux x86_64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
![About Steam_2023-04-28T12:36:17+0800_lossless](https://user-images.githubusercontent.com/23386037/235056918-685b330e-e986-47f1-b2e6-8ad5f7fcbbff.png)

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

After the latest steam beta update. The steam config menu cannot set any shortcut keys to any special key or function key with or without modifier (Alt, Shift or Control key).

Some keys (Tab and backtick `` ` `` ) will display and set to `None`, other (like F1 to F12, Insert and delete) will set to a random alphabet or number

The shortcut key will also set to that specific alphabet or number + modifier when in-game

If the setting is manually edited in file `${HOME}/.local/share/Steam/userdata/${steamid}/config/localconfig.vdf`

    		"InGameOverlayShortcutKey"		"Alt	KEY_Tab"
    		"InGameOverlayScreenshotHotKey"		"Alt	KEY_F12"

then shortcut key will work correctly.
#### Steps for reproducing this issue:

1. open steam setting
2. change shortcut key in the `in-game` tab

**Comment by dsalt** [comment]
Oh, nice. `UTC -0800`.

**Comment by Managor** [comment]
I believe this has been fixed.

**Comment by Billli11** [comment]
You're right. It's fixed
