### ISSUE TITLE
Steam Client Crash Loop

### ISSUE THREAD

**Issue by ObiWanPEZ** [ValveSoftware/steam-for-linux#9381]
* Steam client version (build number or date): Request to install first appeared: 28 April 2023
* Distribution (e.g. Ubuntu): Ubuntu 22.10
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes; Update/Upgrade shows no changes to be made

#### Please describe your issue in as much detail as possible:
I expected Steam to install, restart, and open.
Every time Steam opens, it now shows the "Loading User Data" splash screen for about 1/2 second before disappearing. The Steam window stays closed for about 10 seconds before flashing on the screen for 1/10 of a second before disappearing. I need to sigterm the Steam process before it stops taking focus away from whatever I am typing on every 10 seconds or so.

#### Steps for reproducing this issue:

1. Updated Steam
2. Open Steam
3. Cry

**Comment by bessman** [comment]
I'm seeing this also, when launching Steam via the steam.desktop file. Interestingly, launching Steam from a terminal works OK.

**Comment by kisak-valve** [comment]
Hello @bessman, can you check if #8179 is relevant to your system?

**Comment by bessman** [comment]
Doesn't seem so; I'm on AMD graphics, open source driver.

```
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.49, 6.2.0-20-generic) (0x73ff)
    Version: 23.0.2
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

**Comment by bessman** [comment]
#9383 is relevant though, launching from terminal also fails if `DRI_PRIME` is non-zero.

**Comment by bessman** [comment]
More specifically, the `PrefersNonDefaultGPU` workaround mentioned in #8179 has no effect.

**Comment by ObiWanPEZ** [comment]
I launched from Terminal just now. Works, though I can't click through my offers that pop up in the window.
