### ISSUE TITLE
New Steam Client Beta ignores "-silent"

### ISSUE THREAD

**Issue by reDBo0n** [ValveSoftware/steam-for-linux#9382]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The new Steam Beta ignores the "-silent" flag and opens a window anyway.

#### Steps for reproducing this issue:

1. Run "steam -silent"

**Comment by HugLifeTiZ** [comment]
In addition, if you close the window, it also re-opens it when you shut it down.

Has the flag been renamed, or is it just not working?

**Comment by BaconCatBug** [comment]
I can confirm, the -silent does nothing now :(

**Comment by ChaosBlades** [comment]
This does not seem to affect the deb or flatpak versions of Steam. Or it is already fixed.
Steam package versions: 1682708537
Built: Apr 28 2023, at 18:33:22

**Comment by HugLifeTiZ** [comment]
Are you sure you are using the public beta? I am using the Flathub package for Steam and I am experiencing this issue. I have a different build number than you: 1682723851 built on April 28 at 18:53.

**Comment by BaconCatBug** [comment]
I am on Fedora 38, using the rpmfusion-nonfree Steam client, build 1682723851 with -silent not working
![image](https://user-images.githubusercontent.com/4897163/235463319-01bcff73-b1b7-403e-87ed-2bb26ed6981b.png)

**Comment by reDBo0n** [comment]
Steam Version 1682991685 (2023-05-02) seems to have fixed the issue, could anyone else confirm this?

**Comment by BaconCatBug** [comment]
> Steam Version 1682991685 (2023-05-02) seems to have fixed the issue, could anyone else confirm this?

Fixed for me now too. :crab:

**Comment by HugLifeTiZ** [comment]
I don't know if this counts as resolved? It still pops up the "Waiting for network / logging in" window, whereas I don't think the old version did even that when you requested a silent start.

**Comment by EntityinArray** [comment]
OS: ArchLinux, installed Steam from Arch repositories ```pacman -S steam```
Silent option now works perfectly for me, no "Logging in" window.
Thank you, Valve!

([expose this in the steam's GUI please](https://github.com/ValveSoftware/steam-for-linux/issues/5806)) 🥺

**Comment by loqusion** [comment]
Still not working for me even after the latest update, "waiting for network/logging in" window appears _and_ the main steam window opens right after.

**Comment by Arctize** [comment]
I also get the "Waiting for network" window with the silent option. It disappears after Steam is connected. In earlier versions there was no window popping up at all, which should be the desired behavior I think.

```
Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 11:18 PM UTC -08:00
```

**Comment by HugLifeTiZ** [comment]
Yeah, I hate to bump this, but this still can't really be considered resolved if a window is appearing for "waiting for network" when in the old client, it didn't appear. Is there a `-moresilent` command line option now or something?

**Comment by loqusion** [comment]
Agreed, I even added a rule in my hyprland config for this specific issue to automatically move the window to the "special" workspace. It still appears, and it takes up that workspace for the duration of the loading time, but at least I can hide it with a keystroke and pretend it's not there.

**Comment by logiczny** [comment]
How this is marked as resolved when waiting for network and logging in still appers? Debian 12 here, newest client from official valve site.
```Steam Version:  1692390949
Steam Client Build Date:  Fri, Aug 18 9:39 PM UTC -08:00
Steam Web Build Date:  Fri, Aug 18 10:21 PM UTC -08:00
Steam API Version:  SteamClient020```

**Comment by BaconCatBug** [comment]
I currently have 
```
Steam Version:  1692824614
Steam Client Build Date:  Wed, Aug 23 9:22 PM UTC -08:00
Steam Web Build Date:  Wed, Aug 23 9:28 PM UTC -08:00
Steam API Version:  SteamClient020
```

And the issue has been resolved, no popup when running with the -silent flag.

**Comment by hasezoey** [comment]
for me the popup for "Logging in..." still appears

```txt
Steam Version:  1692824614
Steam Client Build Date:  Wed, Aug 23 22:22 UTC -08:00
Steam Web Build Date:  Wed, Aug 23 22:28 UTC -08:00
Steam API Version:  SteamClient020
````

**Comment by JohnTheCoolingFan** [comment]
Same here, Arch linux, latest package version, just `-silent` flag
```
Steam Version:  1693527575
Steam Client Build Date:  Fri, 1 Sep. 0:03 UTC -08:00
Steam Web Build Date:  Thu, 31 Aug. 21:38 UTC -08:00
Steam API Version:  SteamClient020
```

**Comment by Blood-Pirouette** [comment]
Why is this issue closed when it still exists? Steam still opens a waiting for network dialog when started with a -silent argument. This causes all sorts of issues with third-party apps, windows managers and frankly looks ugly on boot, takes focus and space. On top of that it serves no meaning, it does not tell the user anything important.  

The -silent command argument does not make steam silent, this issue is not closed.
