### ISSUE TITLE
[Steam UI] The client doesn't scale with KDE Plasma

### ISSUE THREAD

**Issue by mrquantumoff** [ValveSoftware/steam-for-linux#9384]
#### Your system information

* Steam client version (build number or date):  Apr 28 1:07 AM UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The application doesn't scale when any scaling settings are set in KDE Plasma/GNOME on Wayland and X11

#### Steps for reproducing this issue:

1. Set scaling to anything that is not 100% in Plasma/GNOME settings
2. Set steam client to beta
3. Update
4. The app doesn't scale

**Comment by kisak-valve** [comment]
Hello @mrquantumoff, this issue is already being tracked at #9209. Closing as a duplicate.
