### ISSUE TITLE
[settings] new beta: Steamplay is missing

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/steam-for-linux#9385]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. open steam
2. go to settings
3. look for steamplay

**Comment by arrowgent** [comment]
steamplay enables setting compatibility (proton) etc.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
While Shader pre-caching was moved into the "storage" tab, Steam Play is missing altogether. I'd understand if the default Proton option was removed intentionally, however the old setting before the update is still being used, so the option was not removed, just the UI entry for it.

**Comment by lucifertdark** [comment]
The per game Proton Compatibility setting is still there when I right click on any specific game but the separate page for the overall Steam Play setting is M.I.A. Is this intentional I wonder? We, the gamers don't need to mess about with those settings as they're set automatically now?

**Comment by arrowgent** [comment]
4-28-23 update added "compatibility" tab to settings

**Comment by GenocideStomper** [comment]
But you still can't set the default version to use.

**Comment by kisak-valve** [comment]
Hello @GenocideStomper, in a quick test here that's not the case. Please open a new issue report so that your feedback can be tracked properly.
