### ISSUE TITLE
[Steam UI][About] The new Steam Client UI About content is not selectable/copy-able

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/steam-for-linux#9389]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Manjaro (Arch)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

The new Steam Client UI About window's content is a static element and can't be selected nor copied for something like submitting a bug.

#### Steps for reproducing this issue:

1. Open the Steam Client UI
2. Click Help -> About Steam
3. Try to click the Steam Version or whatever except the Close button
4. Nothing is clickable or selectable

**Comment by kisak-valve** [comment]
Hello @deanrih, this issue is already being tracked at #5355. Closing in favor of the older issue report.

**Comment by deanrih** [comment]
> Hello @deanrih, this issue is already being tracked at #5355. Closing in favor of the older issue report.

Understood.
