### ISSUE TITLE
Steam client: 3rd party site links in news items open within client browser.

### ISSUE THREAD

**Issue by DerRidda** [ValveSoftware/steam-for-linux#939]
![3rdpartysitesinclient](https://f.cloud.github.com/assets/3391055/100394/34bc415a-6809-11e2-84d2-d36c44efda84.png)

I went to read the latest update for Towns which included a link to their website. After clicking the link the site was loaded within the Steam client, as shown in the image, instead of opening the standard browser, which is the expected behavior.

I tested several other news items that included links to third party sites and they all open in the actual client.

I think I don't need to tell anyone that this is a bit of a security problem.

**Comment by kisak-valve** [comment]
Closing as the referenced url to a third party site now opens in the default browser instead of in the client.
