### ISSUE TITLE
[Steam Overlay UI] There's no way to re-center out of position window

### ISSUE THREAD

**Issue by deanrih** [ValveSoftware/steam-for-linux#9393]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Manjaro (Arch)
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

If a window in the overlay has gone out of position beyond the screen due to any reason (mostly from a bug from a previous version of overlay), then there's no way to retrieve or re-centre the window, Minimizing the window and restoring it again does nothing.

In my case, it's my Friends Window, here's the screenshot

![image](https://user-images.githubusercontent.com/16235605/235141156-e45402be-669f-451f-892d-d5715258958d.png)

#### Steps for reproducing this issue:

I don't really know how to reproduce it nor how to move the window beyond the bound of the overlay

**Comment by deanrih** [comment]
Also, I don't actually know if it's out of bound or the size of the window is 0 so it doesn't visible, in any case, we need some kind of Reset Layout button or similar.

**Comment by deanrih** [comment]
Update:
On Steam Client version 1682723851, the Friends window problem seems to be fixed, however, it causes a problem in some games, currently tested are CS:GO and Dota 2, which the problem when pressing SHIFT+TAB freezes the game and then crashes the game.

**Comment by kisak-valve** [comment]
Hello @deanrih, glad to hear it's working for you.

Your follow up issue is unrelated to this issue report and for CS:GO, is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172.

**Comment by deanrih** [comment]
I have an update, it seems there's a weird behaviour if you have multiple monitor setup, every "window" in the overlay have it's position and size resized every session (as far as I'm aware, every Steam restart) with the center of both monitor/screen being the middle point instead of the center of the currently active screen the game currently displaying on.

My setup have 2 monitors, side by side, my main one is on the left, a 4K ViewSonic VX3211, while the secondary is on the right side of the main one, an old LG with 1600x900 resolution, I notice that when I move any "window" from the overlay, let's say, Notes Window, when I move it to the left and resize it a little bit smaller, and then on the next session the window moved back to the right with the original size, this also could be a reason why my Friends window sometimes disappearing, it might be because the position is reset and go way further to the right and out of bound of the main display.

**Comment by deanrih** [comment]
The last few updates seem to fix this problem and are quite stable, the Friend Window is now staying where they are, actually, all of the windows is now stay where they are and not suddenly gone, hope this will stay stable on the actual release.

**Comment by kisak-valve** [comment]
Closing per the last comment.
