### ISSUE TITLE
New Steam UI: not able to maximize window by double-clicking title-bar

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/steam-for-linux#9397]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Manjaro 22.1.0
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

with the new steam-ui (got the update today), it is not possible to maximize the window by double-clicking the title bar, which has previous working

#### Steps for reproducing this issue:

1. have the new steam-ui
2. try to double-click the titlebar
3. observe not being maximized

maximizing via window-manager or the dedicated button (besides minimize and close) is still working

**Comment by kisak-valve** [comment]
Hello @hasezoey, this issue is already being tracked at #9378. Closing as a duplicate.
