### ISSUE TITLE
[New Steam UI] System information is not copyable

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#9398]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The new Steam Client UI System Information window's content can't be copied or interacted with, which is useful for submitting bug reports. 

The same goes for the "View runtime information" button inside this dialog: at least for me, it opens a new window where the info is completely blank and pressing "Copy to clipboard" copies nothing.

![Screenshot_20230428_163659](https://user-images.githubusercontent.com/42720874/235163791-4ffa2ff1-b5f0-4ac9-9742-1cc964b81611.png)

#### Steps for reproducing this issue:

1. Open the Steam Client UI
2. Click Help -> System Information
3. Try to copy or select text

**Comment by SunRed** [comment]
The latter issue with clicking on the "View Runtime System Information" button seems fixed now. A new window with the json data is now displayed and can be copied using the "Copy to Clipboard" button. But just like the scroll view in the previous window displaying the system information, the list is merely scrollable but no text can be selected and copied from.

**Comment by shytzedaka** [comment]
It would be nice to be able to also copy System Information Either with a button or having the text selectable like the non-beta version of steam. This is rather important for sites like ProtonDB which request your System information for making reports based on your system configuration.
![image](https://user-images.githubusercontent.com/20986867/236795014-6f2d48d4-1189-4692-bfd0-986892004052.png)

**Comment by iodream** [comment]
As of Steam version 1683926267 both System Information and Runtime System Information windows now display the correct data for me and all buttons work correctly. All text can be specifically selected and copied. And you can use Ctrl+A to select everything too.  

Only thing i'd mention would be nice to have a "Copy to clipboard" button in the initial System information dialog like  Runtime information has but this is minor as Select all works fine.  

Tested on X11
The only info that's relevant for debugging and can't be copied or selected is now in the About Steam window.

Thank you for the fix.

**Comment by hasezoey** [comment]
can also confirm that both (`System Information` and `Runtime System Information`) dialogs text is select-able and copy-able

kde plasma wayland

steam version 1683944175

**Comment by shytzedaka** [comment]
Can Confirm as well that this has been fixed, and Copying information on System Information works now.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/f3e33166-c76c-4d27-87d9-8f2cc1f7a1be)
Ran the Test on Ubuntu 23.04 X11 Gnome Desktop

Steam version:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/20986867/1274186a-495e-4c41-92c1-f0b4b73525bc)
