### ISSUE TITLE
New Steam UI: unable to select everything / copy from System information

### ISSUE THREAD

**Issue by hasezoey** [ValveSoftware/steam-for-linux#9399]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): 22.1.0
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

with the new steam-ui it is impossible to select everything in the System Info view to copy everything

also `View Runtime System Information`'s `Copy to clipboard` does not work (does not copy anything and window closes) also the progress-bar is stuck at like ~95%, but `Copy to clipboard` is available

and out of some reason, when being in `System Information` and clicking somewhere in the "text-box" may scroll the box, for example when first opening the window and then clicking in the lower-half of the box it scrolls down (but not again), and sometimes when being scrolled and clicking the upper half it scrolls up a bit

#### Steps for reproducing this issue:

1. have the new steam-ui
2. open `Help -> System Information`
3. try to select everything
4. try to copy via CTRL+C

![steam_runtime_info](https://user-images.githubusercontent.com/10911626/235165387-16d96f4e-6469-4108-a75a-a954f376e6ac.png)

because i cannot copy the system information, here are some screenshots:
![system_info1](https://user-images.githubusercontent.com/10911626/235166324-058ddc00-adbe-4f5c-a31b-27be0c57488c.png)
![system_info2](https://user-images.githubusercontent.com/10911626/235166318-21055384-ffe0-4f4f-bb8c-cd6d7b853ec3.png)

PS: kde system info:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.12-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX Vega
Manufacturer: ASUS

**Comment by kisak-valve** [comment]
Hello @hasezoey, #9398 is already tracking Steam Runtime System Information section. Let's use this issue report to focus on the summary system information.

**Comment by hasezoey** [comment]
looks like i didnt search properly, thanks for pointing it out
