### ISSUE TITLE
[New UI] Client Notifications Positioned Incorrectly

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#9402]
#### Your system information

* Steam client version (build number or date): Thu, April 27 23:07 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Notifications (such as friends going in-game, etc) appears on the right side of the screen as expected so it has the correct X position, but the Y position is incorrectly set. It appears about 3/4 of the way up the screen and moves up and back down before disappearing. 

I have a multi-display Plasma Wayland setup which may be causing the notifications to display incorrectly, but this worked previously with the old UI.

#### Steps for reproducing this issue:

1. Open Steam client.
2. Receive notification.
3. Notifications positioned incorrectly.

**Comment by kisak-valve** [comment]
Hello @sonic2kk, this issue is already being tracked at #9374. Closing as a duplicate.

**Comment by sonic2kk** [comment]
Apologies, I scrolled to see if it was already reported and somehow missed this
