### ISSUE TITLE
Steam overlay crash Company of heroes 2

### ISSUE THREAD

**Issue by Frambooisier** [ValveSoftware/steam-for-linux#9411]
#### Your system information

* Steam client version (build number or date): 1682634349
* Distribution (e.g. Ubuntu): Opensuse Tumbleweed 20230319
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes] but I didnt update yet since snapshot from a week ago cause me alot of troubles

#### Please describe your issue in as much detail as possible:
in coh2 on proton 7 after pressing Shift+tab to open Steam overlay it cause a freeze and then crash of the game, then I switched to proton experimental, 1st try overlay did not activeate at all (as if it was disabled in games properites, but it wasnt) 2nd try game creashed and window popped out with error message. Tried Red alert 3 and steam overlay works there no problem, no more testing has been done.

![image](https://user-images.githubusercontent.com/15931041/235277161-bdf83b89-bfe6-48d0-ae2d-7483136d595c.png)

#### Steps for reproducing this issue:

1. Lunch coh2
2. press ALT+TAB for steam overlay
3.  game should crash or steamoverlay do not show up

**Comment by kisak-valve** [comment]
Hello @Frambooisier, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3875#issuecomment-1528446479.
