### ISSUE TITLE
[New Steam UI] File picker from "screenshot folder" option won't change at selection.

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/steam-for-linux#9415]
#### Your system information

* Steam client version (build number or date):  29/04/2023 Beta
* Distribution (e.g. Ubuntu): EndeavourOS (Archlinux)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It's impossible to change the screenshot folder because the folder picker won't work, you can use it and select a folder but clicking on "Select" does nothing.
![Captura desde 2023-04-29 13-21-23](https://user-images.githubusercontent.com/44957566/235300253-70dd1555-dd71-40c5-aca4-299b6f007304.png)

#### Steps for reproducing this issue:

1. Open preferences, go to in-game section
2. Click on "change folder" for screenshot folder
3. Select the desired folder
4. See how the folder didn't change at all

**Comment by J0hnMatrix** [comment]
Same issue on Windows

**Comment by KibaGasteiz** [comment]
This was already fixed, forgot to close.
