### ISSUE TITLE
ssfn* files not removed from ~/.local/share/Steam

### ISSUE THREAD

**Issue by af7567** [ValveSoftware/steam-for-linux#9416]
* Steam client version (build number or date):  Fri, Apr 28
* Distribution (e.g. Ubuntu): Slackware64 current
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

sysinfo: https://gist.github.com/af7567/3387e8abf3be4f47b4d78096640cc4d4

#### Please describe your issue in as much detail as possible:
I have over 100 ssfn* files in ~/.local/share/Steam. There seems to be one created every time I start up the steam client. The oldest is from Mar 28 2023 so it must be something that changed around that time in the beta client.

**Comment by KibaGasteiz** [comment]
I opted-in the beta yesterday and everytime I start Steam a new file is created:
![imagen](https://user-images.githubusercontent.com/44957566/235301167-46e2e781-9e65-4c58-9434-2dd29884ce89.png)

**Comment by af7567** [comment]
This seems to be fixed now. I don't see it mentioned in any patch notes but I removed all the ssfn files and restarted steam a few times and no new ones are coming back.

**Comment by KibaGasteiz** [comment]
> This seems to be fixed now. I don't see it mentioned in any patch notes but I removed all the ssfn files and restarted steam a few times and no new ones are coming back.

Also fixed on my rig. :D

**Comment by kisak-valve** [comment]
Closing as fixed per the last couple comments.
