### ISSUE TITLE
[New Steam UI] Can't set a custom cover, hero or logo because file picker won't open

### ISSUE THREAD

**Issue by KibaGasteiz** [ValveSoftware/steam-for-linux#9417]
#### Your system information

* Steam client version (build number or date): 29/04/2023
* Distribution (e.g. Ubuntu): EndeavourOS (Archlinux)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With the new beta you can still see the "set custom cover/logo/hero" on the right click menu, but clicking on them does nothing.

#### Steps for reproducing this issue:

1. Right click on any game cover/hero
2. Click on "Set custom cover/hero/logo"
3. Nothing happens :(

**Comment by kisak-valve** [comment]
Possible duplicate of #9373.

**Comment by sbritorodr** [comment]
Also happens when you had custom covers already applied in stable steam. They doesn't show up.

**Comment by nose-gnome** [comment]
+1

**Comment by hardpenguin** [comment]
Yeah I am also affected...

**Comment by worsedoughnut** [comment]
Seems to have changed behavior slightly: (identical behavior on both Beta and Stable)

Now it opens my native file picker, lets me select an image, but then afterwards the existing artwork (or empty image for non-steam games) just flickers black for a millisecond and nothing changes.

**Comment by KibaGasteiz** [comment]
Please open another issue then, this one was already fixed and i forgot to close it, closing this right now :)
