### ISSUE TITLE
Typing anything in the in-game overlay requires 2 button presses

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#9420]
#### Your system information

* Steam client version (build number or date): 1682707471
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Graphics platform: X11

#### Please describe your issue in as much detail as possible:
Whenever i open either a chat window or any other window like the discussions in the in-game overlay if i want to type any letter i have to press it twice. Like if i want to type 's' i have to press the s key twice. This issue does NOT happen in a regular steam chat window outside the overlay. 

This issue is also most likely not caused by the new update as it was already present before it.

#### Steps for reproducing this issue:

1. Open the steam overlay
2. Open a chat window and/or any discussions
3. Try typing anything

**Comment by kisak-valve** [comment]
Hello @iodream, I expect that you were testing games using Proton. This issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/6280. Closing as a duplicate.

If you see this happening with a native linux game, then that is worth pondering separately.

**Comment by iodream** [comment]
Yes that's correct. Sorry i didn't catch the duplicate.

**Comment by kisak-valve** [comment]
Error on my part, #9325 is the relevant older issue report.
