### ISSUE TITLE
The "View Runtime System Information" button opens a window that loads something, and then does not show anything important

### ISSUE THREAD

**Issue by Artem13327** [ValveSoftware/steam-for-linux#9423]
#### Your system information

* Steam client version (build number or date): 1682723851 Sat, Apr 29
* Distribution (e.g. Ubuntu): PepperrrmintOS 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

#### Steps for reproducing this issue:

1. Click Help
2. Then System Information
3. And finally View Runtime System Information
![1](https://user-images.githubusercontent.com/68551925/235321460-d2e660a1-71b1-4c7d-b4c9-ef5889cdc784.png)
![1](https://user-images.githubusercontent.com/68551925/235321734-778dde77-4f14-4baf-96ea-511fcb288f83.png)

**Comment by ThisNekoGuy** [comment]
I'm getting this issue on Arch Linux too
It's pretty important that I access this because I can't write Proton reports without access to this information because the "Copy to Clipboard" button doesn't work.

**Comment by kisak-valve** [comment]
Hello, per "Fixed the Steam Runtime info dialog not showing any information" in the [2023-05-04](https://store.steampowered.com/news/group/4397053/view/3705943193600581522) Steam client beta update, please retest this issue.

**Comment by ThisNekoGuy** [comment]
@kisak-valve Works now, just tested
Looks a little weird though; by that, I mean I guess I'm just used to the old reports including the general system info
