### ISSUE TITLE
Can't select per-game Compatiblity tool

### ISSUE THREAD

**Issue by pacomix** [ValveSoftware/steam-for-linux#9427]
#### Your system information

* Steam client version (build number or date): [System Info Gist](https://gist.github.com/pacomix/d0e276b04def16d7f879a847eac0cf68#file-system-info-txt)
* Distribution (e.g. Ubuntu): ***Ubuntu 22.04.2 LTS***
* Opted into Steam client beta?: [Yes/No] ***No***
* Have you checked for system updates?: [Yes/No] ***Yes***

#### Please describe your issue in as much detail as possible:
***Native Linux Desktop mode***
When selecting the Compatibility tool (Proton version) on a per-game basis, the dropdown list shows all the different Proton versions but when clicking on any of them ***Proton experimental*** remains selected as a result.

The functionality of the override the global Compatibility tool is ok since Proton experimental overrides the steam global setting for the proton version but it is impossible to select a specific Proton version per-game.

On the [Steam.log](https://gist.github.com/pacomix/d0e276b04def16d7f879a847eac0cf68#file-steam-log) you can find a first execution having the Compatiblity tool override enabled and a second one disabled that takes correctly the global setting (set to v4+ or Proton that makes some of my games work on my hardware).
I have all the available Proton versions installed.

One thing to note is that after closing the per-game configuration you can see a popup window (white) being instantiated and immediately closed on the upper left corner of the screen.

***Big Picture Mode***
The Compatibility tool override works without issues. If I exit the Big Picture mode and go back to the ***Desktop mode*** I can see the change properly reflected in the per-game Compatibility tool section and if I try to change it to a different value ***the version set doesn't  change***.
***NOTE***: The Big Picture Mode is REALLY slow at around ~4fps (both Full screen and windowed mode) and curiously as a consequence all the games launched from it are affected by the speed penalty (yes... 4 fps...). If I run the Big Picture mode and after launching the game I minimize it then the game runs at its right speed.

### My conclusion
For some reason the Desktop mode UI doesn't change the setting BUT Big Picture mode does.
I tried to search for the file where this setting is stored with the purpose of checking the file permissions but I couldn't find it (didn't dig way too much though).

#### Steps for reproducing this issue:

1. Open Steam Desktop Mode
2. Override per-game Compatibility tool
3. Observe the Proton experimental always remain selected after clicking on any other available Proton version.
4. ***OPTIONAL***
5. Open the Big Picture mode
6. Override per-game Compatibilitiy tool
7. Run the game to see that the right override has been applied.
8. Exit Big Picture mode
9. Open Steam Desktop Mode
10. Check the per-game Compatibility tool version set
11. Try to change it again => Impossible to change it

**Comment by kisak-valve** [comment]
Hello @pacomix, this issue is already being tracked at #9273. Closing as a duplicate.
