### ISSUE TITLE
Hardware Survey includes wrong GPU

### ISSUE THREAD

**Issue by nPHYN1T3** [ValveSoftware/steam-for-linux#9430]
#### Your system information

* Steam Apr. 28 2023 @ 18:33:22
* Garuda
* No
* Duh

#### Please describe your issue in as much detail as possible:
Got asked to do the hardware Survey. When it finished collecting hardware I noticed the GPU was wrong.

#### Steps for reproducing this issue:

1. Have several GPU's
2. Participate in the Hardware Survey
3. Watch as the hardware listed pulls (most likely) the first GPU it finds rather than the primary or denoted DXVK_FILTER_DEVICE_NAME etc.

**Comment by kisak-valve** [comment]
Hello @nPHYN1T3, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by nPHYN1T3** [comment]
I think you misunderstand. This is the survey i.e. you are collecting the wrong data to understand what a client is running on. I launch Steam on my NON-Gaming GPU and all my games are launched with DISPLAY=:0.0 %command% i.e. if you want accurate data on users hardware it's being done wrong.

**Comment by nPHYN1T3** [comment]
As a fun addendum to this CS2 now has the same behavior. It enumerates GPU's and locks on to the first thing is finds leaving it broken. It constantly locks onto the wrong GPU and ignores the GPU it's run on (the good one) failing with a CreateSwapChain() error because it builds shaders and sets up for the WRONG GPU.

**Comment by blainekyle** [comment]
Just want to add myself to the list of people concerned about this. I don't have a weird config; I'm on my Dell XPS 9710 with an 11800H and a 3060 Mobile GPU. It's not my main gaming machine but I do play some games directly on it, in addition to streaming from my gaming desktop.

The survey is collecting only the iGPU (Intel UHD) and ignoring the RTX 3060. This now makes me think that when news outlets cover Steam HW survey results and point out the surprising number of people gaming on integrated graphics, they're actually seeing a flaw in the data collection process rather a truly fascinating datum.
