### ISSUE TITLE
New steam client Beta(lastest update) disable ps4 controller vibration for Elden Ring only

### ISSUE THREAD

**Issue by deathxxx123** [ValveSoftware/steam-for-linux#9431]
#### Your system information

* Steam client version (build number or date): 28.04.2023
* Distribution (e.g. Ubuntu): Manjaro Gnome
* Opted into Steam client beta?: Yes and No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Tryed several times with beta and stable client and every time beta has no vibration for my controller ps4 for Elden Ring. But with stable (non beta) always have vibration with my ps4 controller. I try with other games and vibration is here with beta and non-beta. It's happen only for Elden Ring. I check the options in steam client and controller is set to vibration enabled. (since with other games vibration is working)
That bug happen after some recent beta update, because before that i was always opt in beta and has no problem with rumble.
After lastest 1 or 2 beta updates is this issue. So i now play with stable steam client and all is good.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I expect ps4 rumble to work with Elden Ring in steam beta.

#### Steps for reproducing this issue:

1.  Istall steam client and opt in beta
2. Use ps4 controller via BT
3. Play Elden Ring and test for vibration/rumble

**Comment by kisak-valve** [comment]
Hello @deathxxx123, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1529699654.

**Comment by deathxxx123** [comment]
Thank you for this.
