### ISSUE TITLE
Feature request: Modify mouse wheel scroll delta to match Windows

### ISSUE THREAD

**Issue by Yasand123** [ValveSoftware/steam-for-linux#9433]
Recently Chromium had an [update to increase the scroll delta](https://chromium-review.googlesource.com/c/chromium/src/+/3971328) (how many pixels the page will scroll per mouse wheel) to match Firefox, native Linux apps and also Windows. This applies to all Electron apps. Since Steam isn't an electron app or based on Chromium it needs to be done by the Steam developers themselves. Currently scrolling is very slow. Plus the fact that Autoscroll (middle click feature) is missing as well.

**Comment by NoksC** [comment]
Same here, scroll speed is very low with mouse wheel on Steam client beta.

**Comment by KotoWhiskas** [comment]
You can just wait till Valve updates their Steam chromium version (it happens I think every 3-6months or so) and it will be fixed automatically

**Comment by Yasand123** [comment]
> You can just wait till Valve updates their Steam chromium version (it happens I think every 3-6months or so) and it will be fixed automatically

What chromium version? I'm not aware of any different versions. Where do you get that from?

**Comment by KotoWhiskas** [comment]
> > You can just wait till Valve updates their Steam chromium version (it happens I think every 3-6months or so) and it will be fixed automatically
> 
> What chromium version? I'm not aware of any different versions. Where do you get that from?

https://bugs.chromium.org/p/chromium/issues/detail?id=1270089#c27

https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3427822455464691230/

**Comment by Yasand123** [comment]
> > > You can just wait till Valve updates their Steam chromium version (it happens I think every 3-6months or so) and it will be fixed automatically
> > 
> > 
> > What chromium version? I'm not aware of any different versions. Where do you get that from?
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=1270089#c27
> 
> https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3427822455464691230/

I didn't even know Steam utilized Chromium, I thought by "Steam chromium version" you meant a completely separate Steam client.

**Comment by NoXPhasma** [comment]
This is bugging me as well. It's so unpleasant to use the Steam Store in the client with that super low scroll speed, that I gave up on that and use my browser instead.

**Comment by kisak-valve** [comment]
Tracking note: Using #11153 to focus on the second request on this issue report.

**Comment by kisak-valve** [comment]
Hello, it looks like libcef has been bumped past the mentioned commit in the Steam client beta. Please retest.

**Comment by rastla** [comment]
@Yasand123 on arch the folder might be different.
If you have Steam open, which folder/path do you see for your steamwebhelper?
`ps -efww | grep steamwebhelper`

**Comment by kisak-valve** [comment]
Closing as the upstream fix has propagated.
