### ISSUE TITLE
[New Steam UI] Can't interact with store just after starting Steam

### ISSUE THREAD

**Issue by Nyamiou** [ValveSoftware/steam-for-linux#9443]
#### Your system information

* Steam client version (build number or date): 1682723851
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
On the new Steam UI, with Steam configured to display the store as the startup location, after launching Steam and closing the "Update News" popup window the store is displayed (with animations and everything) but cannot be interacted with. The cursor doesn't change when hovering over clickable images/links, clicking doesn't do anything, double clicking select the address bar but the address cannot be changed. Scrolling doesn't do anything either. And refreshing the page doesn't fix it.

Also if the window is minimized, sometimes the store will be black when the window is restored. 

If I go to another page (for example the library) and then back to the store, it then does work correctly.

I have a notification for a sale that popup at the same time Steam start, if that is relevant. But waiting for the notification to go away doesn't fix the issue. 

#### Steps for reproducing this issue:

1. Have Steam configured so the startup location is the store
2. Launch Steam
3. Close the "Update News" window
4. Try to interact with the store and observe that it doesn't work
5. Go to the library and back to the store
6. Try to interact with the store and observe that it does work now

**Comment by xksteven** [comment]
I'm on Ubuntu 22.04 and also experience this issue.

What I've noticed is that interacting with the store is instead captured by the url below the menu bar saying "https://store.steampowered.com/"

The other thing I've noticed is that if you resize the window then you can interact with the steam store page again.

**Comment by nightsky30** [comment]
This inability to interact with items in the popups or client window occurs every time Steam is started and only resolves when I switch to the Library window.

I'd also like to add THIS IS AFFECTING OTHER EXTERNAL APPLICATIONS such as Chrome. Until I navigate to the Library in the Steam client, my Chrome web browser will not allow right-clicking and opening of context menus.

It is almost like Steam launches with an assumed right mouse button pressed or some insane thing like that.

**Comment by bradgy** [comment]
Same deal here, resizing the window as per [xksteven](https://github.com/ValveSoftware/steam-for-linux/issues/9443#issuecomment-1533859766) made the store page navigable/clickable again.
Arch, Gnome 44, Wayland, i3 8100, rx580

**Comment by sylware** [comment]
Yep, same here, elf/linux, x11 native (xorg).

Have to browse the library to unlock the inputs in the other web tabs.

**Comment by reDBo0n** [comment]
Can confirm.
My standard view is the Library.
I need to open the Store/Community/Profile tab, then go back to Library and then back to it to let it react to input.
Arch, Steam Build 1683944175

**Comment by laclcia** [comment]
experiencing the same problem.
OS: Manjaro Linux x86_64 
Kernel: 6.3.1-zen2-xanmod1-2
DE: Cinnamon 5.6.8
CPU: AMD Ryzen 7 3700X (16)
GPU: AMD ATI Radeon RX 6650 XT

tested with: 
steam build 1683944175
mesa 23.0.3
mesa 23.1
mesa 23.2.0_devel.170751.19961f81950
all of witch show the same misbehaviour



standard view is library witch work's fine. switching to store/community/profile display the page but is uninteractable untill i either switch back to library and back again to witchever tab i was on OR resize the steam window. after witch interaction's just work on all tabs.

**Comment by reDBo0n** [comment]
It seems to work now, at least for me, on Steam Build 1684372665.

**Comment by iodream** [comment]
Fixed here too. Steam Version:  1684372665. Tested on Kde x11 and wayland.

**Comment by Nyamiou** [comment]
Can't reproduce the issue anymore in 1684372665. Closing. Thank you for the fix.

**Comment by sylware** [comment]
Cannot reproduce here too.
