### ISSUE TITLE
Steam Beta UI issues with scaling/HiDPI 4K

### ISSUE THREAD

**Issue by blutigJK** [ValveSoftware/steam-for-linux#9444]
#### Your system information

* Steam client version (build number or date): 1683078372
* Distribution (e.g. Ubuntu): Arch with i3
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The scaling for the new Steam Beta UI does not respect my system's scaling settings. Everything within Steam is really tiny and appears to be no way to manually change it. This applies to all the tabs (Store, Library, Community, etc) as well as the Friends List and Chats.
I'm also not allowed to use Third Party skins such as Metro for Steam anymore with the changes to the UI.

#### Steps for reproducing this issue:

1. Set "Scale text and icons to match monitor settings" to both on and off
2. Apply fix from [this reddit post](https://www.reddit.com/r/linux_gaming/comments/ln3elc/comment/hhpljbg/?utm_source=share&utm_medium=web2x&context=3)
3. Adjusting scaling within i3 config

None of the above things do anything.

![Tue May  2 10:03:27 PM CDT 2023](https://user-images.githubusercontent.com/48782483/235826078-ac51a263-abfd-463f-ba01-8c068f58ef23.png)

![Tue May  2 10:10:23 PM CDT 2023](https://user-images.githubusercontent.com/48782483/235826088-f08b0909-50df-46d6-abba-06b0fda01ac8.png)

![Tue May  2 10:11:08 PM CDT 2023](https://user-images.githubusercontent.com/48782483/235826155-0d7d3315-89fa-4da6-979d-27e32e0280e0.png)

**Comment by 392781** [comment]
Same issue even with a 1080p screen.  The DPI is completely broken.

**Comment by kisak-valve** [comment]
Hello @blutigJK, this issue is already being tracked at #9209. Closing as a duplicate.
