### ISSUE TITLE
Steam no longer allows choosing the default Proton version

### ISSUE THREAD

**Issue by craig-sanders** [ValveSoftware/steam-for-linux#9445]
#### Your system information

* Steam client version (build number or date): 1682991685, May 2 10:08 AM UTC -08:00
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

(this problem started with the previous big new release with all the UI changes - late April? May 1? - but is still present in the latest update)

#### Please describe your issue in as much detail as possible:

The old Steam -> Settings -> Steam Play dialog used to have a drop-down menu for selecting the default proton version to use.  The new Steam -> Settings -> Compatibility dialog doesn't. It just pops up the warning dialog offering a choice between Restart and Restart Later when I enable steam play for all titles.

Worse, it seems that it automatically sets the default proton version to the one that sorts lowest (it seems to sort by name, not timestamp) - e.g. I have several versions of GE-Proton in my `compatibilitytools.d/` directory, ranging from GE-Proton7-42/ to GE-Proton7-54/ and two ancient ones (Proton-5.21-GE-1/ and  Proton-6.20-GE-1/). 

I used to be able to choose any of these (plus Steam's own proton versions, "Experimental", Hotfix", "8.0-2", "7.0-6", etc), but now there is no drop-down menu and games will automatically use GE-Proton7-42/.

I *can* still override the default for individual games in the Properties -> Compatibility dialog for that game - but a) I don't want to have to do that for every game I own (over 600, that would require an enormous amount of micro-management), I want to be able to set the default, and b) that will inevitably lead to problems when I delete older versions of GE Proton (I've already run into this problem when I've deleted an old version of GE Proton but had specific games configured to use it - they just failed to start without any indication of what the problem was).

It has *always* had a weird bug where it displays the "Enable Steam play for all other titles" as if it's disabled, but turning it on caused the drop-down menu of available proton versions to display.   That was always a little annoying because I had to restart steam twice - once to get it to even notice there was a new version in `compatibilitytools.d/` and then restart it again after choosing the latest version as the default....but at least it worked, it allowed me to choose the default rather than just use the lowest sorting version.

#### Steps for reproducing this issue:

1. Start Steam
2. Click on Steam menu, select Settings, select Compatibility
3. Turn on "Enable Steam Play for all other titles"
4. drop-down menu for all proton versions **should** appear, but it doesn't.

**Comment by kisak-valve** [comment]
Hello @craig-sanders, this issue is already being tracked at #9419. Closing as a duplicate.
