### ISSUE TITLE
[New Steam Overlay] Overlay is crashing the game without Vulcan enabled

### ISSUE THREAD

**Issue by dom1torii** [ValveSoftware/steam-for-linux#9446]
#### Your system information

* Steam client version (build number or date): 1683078372
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

New steam overlay is crashing the game without vulcan enabled in game's launch options. Among games that i have downloaded it only happens with CS:GO (may be only CS:GO issue).

I know that using vulcan is better, but i can't use it because i cant use 4:3 in game with vulcan enabled.

With old overlay everything works fine

#### Steps for reproducing this issue:

1. Participate in the new Steam Beta
2. Launch CS:GO
3. Press Shift+Tab or your shortcut for Steam Overlay

**Comment by kisak-valve** [comment]
Hello @dom1torii, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. Closing as a duplicate.
