### ISSUE TITLE
[New Steam UI] Hardware acceleration has no effect in Steam UI, causing low FPS

### ISSUE THREAD

**Issue by fishxz** [ValveSoftware/steam-for-linux#9452]
Description:
I would like to report a bug regarding the new implementation of hardware acceleration in Steam. After updating to the latest version, I noticed that enabling hardware acceleration has no effect on the performance of the Steam UI, resulting in low FPS.

Steps to Reproduce:

    Open Steam application
    Go to Steam Settings
    Click on the "Interface" tab
    Check the "Enable hardware video decoding" and "Enable hardware video encoding" options
    Restart the Steam application
    Observe the performance of the Steam UI

Expected Result:
Enabling the hardware acceleration feature should improve the performance of the Steam UI by reducing the load on the CPU, resulting in smoother and faster UI animations and interactions.

Actual Result:
Enabling the hardware acceleration feature has no effect on the performance of the Steam UI. The UI animations and interactions still run with low FPS, making the user experience sluggish and frustrating.

Additional Information:
I have tried disabling and enabling the hardware acceleration feature multiple times and have also restarted the Steam application and my computer. However, the feature still does not seem to have any effect on the performance of the Steam UI.

System Information:

    Operating System: Fedora Silverblue 38
    GPU: NVIDIA GeForce GTX 970
    Driver: 530.41.03

**Comment by kisak-valve** [comment]
Hello @fishxz, this issue is already being tracked at #8918. Closing as a duplicate.

**Comment by fishxz** [comment]
well, im talking about the desktop ui. but if track it there aswell, im fine with it.

**Comment by RilicTheFox** [comment]
I also have this issue with the Desktop interface running Nobara 37. I have an Nvidia GTX 1080 running driver version 525.105.17, and it happens on both a DNF installation and on the Steam Flatpak.
