### ISSUE TITLE
Will steam ever support ibus multilingual input?

### ISSUE THREAD

**Issue by opqriu** [ValveSoftware/steam-for-linux#9453]
When will steam support multilingual input for ibus???

https://packages.debian.org/search?keywords=ibus-hangul

`$ sudo apt install ibus-hangul`

Many Koreans use "ibus-hangul".

If I press "Shift + Space" on my keyboard, the ibus inputter converts my English and Korean input.

There are tons of apps on Linux, but only Steam doesn't support ibus's multilingual input conversion.

When will Steam support ibus multilingual input?

**Comment by kisak-valve** [comment]
Hello @opqriu, this issue is already being tracked at #781. Closing as a duplicate.
