### ISSUE TITLE
steam input seems broken on discovery queue on steam deck store

### ISSUE THREAD

**Issue by jpwhiting** [ValveSoftware/steam-for-linux#9455]
#### Your system information

* Steam client version: Apr 28 2023 18:33:22 Build
* SteamOS version: 3.5 BUILD_ID from /etc/os-release: 20230426.1000
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Docked steam deck. Using ps3 gamepad connected via usb.
Opened steam store, scrolled down to discovery queue. Opened it by pressing circle as stated at the bottom of the screen. scrolled through to a game and pressed square button to add current game to my wishlist. Watched as the little wishlist flag didn't get added in the corner nor did the game get added to my wishlist.

#### Steps for reproducing this issue:

1. Open steam store on deck while docked using a controller.
2. Scroll down to discover queue and open it.
3. Hit the button that the bottom of the screen says I should hit to add the current game to my wishlist
4. Watch it not get added.

I also tried other face buttons, triangle also did nothing. Cross correctly closes the discovery queue, circle views the store page. It seems only Ignore and Wishlist actions do not work.

I also tried the same using the deck not on the dock and the abxy buttons work perfectly there, so it may only be a problem when using non deck controllers?

Here's a screenshot I took showing a game and the buttons at the bottom when my ps3 controller is connected. 
![steaminputbroken](https://user-images.githubusercontent.com/932924/236287113-f2fe5fd2-9a0a-4b34-97a5-ec82142fbe64.jpg)

**Comment by kisak-valve** [comment]
Hello @jpwhiting, this reads more like a Steam client issue than an issue with SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by slouken** [comment]
We're not able to reproduce it here. Can you test the controller functionality in the controller settings to make sure the buttons are showing up correctly?

**Comment by jpwhiting** [comment]
Yep, all buttons show pressed in the controller settings. This controller works fine for playing games, etc. also I've never had any issues with it. I'll try the discover queue with other controllers shortly,

**Comment by jpwhiting** [comment]
Heh, I paired a PS5 controller with the deck. Everything in discovery queue works fine. So I tried the older ps3 controller again. Everything works fine on that also now... Closing, sorry for the noise (or maybe a fix went in since yesterday (probably not))
