### ISSUE TITLE
Steam overlay typing issues

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [ValveSoftware/steam-for-linux#9457]
#### Your system information

* Steam client version (build number or date): 
Apr 28
1682708537
* Distribution (e.g. Ubuntu): 
Fedora 38
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes
#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
When I shift tab and try to send a message to a friend with the overlay each character has to be pressed twice for it to register it.
#### Steps for reproducing this issue:

1. Open steam
2. Load game (in this specific case the witcher 3 but is reproducible with other games)
3. hit shift+tab 
4. click on friend from friends and chat in the overlay
5. then click on text box to send a message then keys only register on second press of them.

**Comment by kisak-valve** [comment]
Hello @TheAnnoyingFruit, this issue is already being tracked at #9325. Closing as a duplicate.
