### ISSUE TITLE
Steam UI font error

### ISSUE THREAD

**Issue by LiSiaoCheng** [ValveSoftware/steam-for-linux#9460]
/#### Your system information

* Steam client version (build number or date): Built Apr 28 2023,at 18:33:22
* Distribution (e.g. Ubuntu): Fedora 38 (Workstation Edition)(64 bit)
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
I found that when I set the language of the Steam UI from English to Simplified Chinese, there will be font errors in the Steam UI ,it will be displayed as square frame .

OS:Fedora 38 (Workstation Edition)(64 bit)
Steam languages set Simplified Chinese
Issue Capture:
![Capture](https://user-images.githubusercontent.com/89052505/236362093-d8439fdd-efb7-426d-b722-b875d7e5c54d.png)

#### Steps for reproducing this issue:

1. try install the Steam latest version and beta version again, the same fail
2. Reinstall the OS, the same fail
3. Update Wine and Proton to the latest version, the same fail
4. Copy the Simplified Chinese fonts (simsun.ttc and tahomabd. ttf) of Windows to the Linux distribution, the same fail
5. in the end,I find that the Steam UI font error is caused by Fedora 38 compatibility,after I downgraded OS to Fedora 37, it looked OK
6. I am not sure if other Steam Languages will have similar situations.I Suggest that the Steam team also have a try if there are any other issues

**Comment by kisak-valve** [comment]
Hello @LiSiaoCheng, there's no point in fragmenting the discussion of this issue across multiple issue reports. Since your issue report adds a bit more detail, I've gone and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/9418#issuecomment-1535588848.

Closing in favor of the older issue report.
