### ISSUE TITLE
Steam places %20 instead of space in non-steam path to executable

### ISSUE THREAD

**Issue by Dandraghas** [ValveSoftware/steam-for-linux#9462]
#### Your system information

* Steam client version: 1683253302
* Distribution: Fedora 38  
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
when i add non-steam game with space in its name to steam, path to it executabe and 'start in' containing '%20' instead of space because of that game didnt launch. Yea it easy to fix just remove '%20' and place space instead, but its still a bug...

oh and why steam not has functionality to detect that path is incorrect? im spent 3 hours thinking why game not launching only to discover that path is incorrect.

if you still dont understand what i mean here is example:
**how its works currently:**
`"/media/drive/Games/Example%20Game/game.exe"`
**how it should be:**
`"/media/drive/Games/Example Game/game.exe"`

'%20' is a space symbol but for some reason it doesnt work.

#### Steps for reproducing this issue:

1. Add non-steam game
2. See that path to executable is incorrect because it containing '%20' instead of space

**Comment by SireSalty** [comment]
I had this happen as well.  On beta branch as of 5/8/2023

**Comment by TTimo** [comment]
Should be fixed in latest beta.

**Comment by kisak-valve** [comment]
Closing per the last comment.
