### ISSUE TITLE
[beta] crash due to gsettings

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#9465]
Latest beta update:

(process:7764): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
/mnt/128/home/user/.local/share/Steam/steam.sh: line 798:  7764 Trace/breakpoint trap   "$STEAMROOT/$STEAMEXEPATH" "$@"

Probably due to a bug in the gsettings fallback code (my desktop is pure x11).

**Comment by tgurr** [comment]
Same here. A quick way to revert to stable to at least have a working client again is by deleting the file `rm ~/.steam/steam/package/beta`.

**Comment by sylware** [comment]
Yep, did revert. That said, it may work with a GDK_SCALE env var defined (have not tested though). I suspect a bug in the code path of "no-gsettings" *and* "no-GDK_SCALE env var".

**Comment by Continous** [comment]
> Yep, did revert. That said, it may work with a GDK_SCALE env var defined (have not tested though). I suspect a bug in the code path of "no-gsettings" _and_ "no-GDK_SCALE env var".

This did not solve it for me. I'm running Nix-OS and a pure X11 environment.

**Comment by BlackMage2** [comment]
same bug
`(process:20524): GLib-GIO-ERROR **: No GSettings schemas are installed on the system`

ubuntu 22.04, LxQt Desktop

**Comment by sylware** [comment]
baw... I was about to test if defining a non-empty GDK_SCALE environment variable would go thru... well, it seems not @continous.

Now, we need to wait for the fallback code path to be fixed.

The core video game components on elf/linux are:
- wayland->x11 (with options to force selection).
- xkb (via libxkbcommon[-x11]) for wayland and x11 (if required though).
- vulkan->gl->cpu (with options to force selection)
- libasound (the software mixer is hidden behind the alsa-lib API, pulseaudio/pipewire/dmix/jack/etc).
- /dev/input/eventXX for joypads.

xcb client libs/libxkbcommon[-x11]/libasound/gl should be all libdl-ed (vulkan is libdl-ized by design). Access rights must be check on /dev/input/eventXX for rumble support.

The ultimate goal: all distributed binaries should be pure ELF64 with only one DT_NEEDED, "libdl", and only the following _system_ symbols undefined: dlopen/dlsym/dlclose. No static TLS namely TLS only via pthreads. Ofc with the smallest set of relocation types as possible.

**Comment by BlackMage2** [comment]
what are possible fixes for this?

**Comment by BlackMage2** [comment]
not possible to fix the beta?

**Comment by sylware** [comment]
I tried the latest beta to see if it was fixed or setting GDK_SCALE would work around the bug.

Nope. Both failed and crashed.

We have to wait for a fix.

**Comment by tgurr** [comment]
Latest beta update [Steam Client Beta - May 11th](https://store.steampowered.com/news/group/4397053/view/6687326876665967009) fixed the crash:

* Fixed a startup crash in distributions that don't export the org.gnome.desktop.interface settings schema.

**Comment by sylware** [comment]
fixed here too, thx.

How does close the issue? @kisak-valve

**Comment by BlackMage2** [comment]
only @sylware (the issue author) can close the bug. or a project maintainer

you can close it with the button "Close issue" left to the "Comment" button in the write comment section

**Comment by sylware** [comment]
@BlackMage2 all right.

Hope I won't be scolded by @kisak-valve though :)
