### ISSUE TITLE
Steam store videos change default cursor to one for clickable items (minor)

### ISSUE THREAD

**Issue by glaere** [ValveSoftware/steam-for-linux#947]
Minor aesthetic issue.  

When watching game trailers through the store if you place your cursor over the video control bar (play/pause buttons, etc) then switch away from Steam the default cursor becomes the one for clickable items (for Adwaita a hand rather than a pointer).  If you want to return to a normal cursor you have to leave the cursor over the video and then switch. 

Ubuntu 12.10 with Gnome Shell

Specs: https://gist.github.com/790136117b74d21992ee

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
