### ISSUE TITLE
[New UI] Copy Page URL Does Not Work with KDE/Wayland

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#9474]
#### Your system information

* Steam client version (build number or date): Fri, May 5 19:03 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux (KDE Plasma Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When right clicking on a web view from the Steam client, such as a game store page, and selecting "Copy Page URL", the URL is not actually copied.

However, clicking on the URL along the top *will* successfully copy the URL to my clipboard. So this bug report is specific to the context menu.

I am using the KDE Plasma Wayland session, unsure if this has any impact.

#### Steps for reproducing this issue:
1. Go to a game page (or any web view page)
2. Right click and select "Copy Page URL"
3. Page URL will not be copied.

**Comment by sonic2kk** [comment]
Firefox Developer Edition works no problems for me running native Wayland. Chromium and Brave work as well on native Wayland. This issue is specific to Steam.

**Comment by witcheslive** [comment]
I have a lot of weird issues with anything chromiuim-based in wayland (on kde plasma, nvidia card, gentoo for me), which is annoying because I can't pin down the root cause and don't know who to report what to, but sometimes the clipboard doesn't work, sometimes it does, sometimes pages freeze, sometimes i can reload them, sometimes i can't. sometimes apps get sluggish and eventually stop responding and i have to restart them. wish i had any idea how to narrow it down and figure out the root cause so i could even report it to the correct place.

**Comment by sonic2kk** [comment]
Wayland has worked perfectly fine for me for the last year, this bug report is not about other applications though.

It's also worth nothing that Steam is not a Wayland native application and works through XWayland, and the copy URL feature has been intermittently broken over the years even on X11. It has worked fine for the last while (including the stable release without the new UI) but there appears to have been a regression with the new UI, which is the focus of this bug report.

**Comment by sonic2kk** [comment]
Copying from the top bar has worked across my machines at least since December and currently does still work on the New UI. It is only the Copy URL option in the context menu which does not. It's probably better to open separate issues if copying from within Steam does not work outside of the New UI.

**Comment by dsalt** [comment]
Copying from the URL bar doesn't work correctly anyway – it's the whole URL or nothing, and, as with the rest of Steam, always to _both_ the primary selection and to the clipboard. The latter should only be happening with Ctrl-X or Ctrl-C.

**Comment by sonic2kk** [comment]
The new UI's intended functionality currently, as far as I understand it, is click-to-copy. I agree there is missing functionality for only part of the URL but that's probably for a separate ticket. I should've been clearer in my opening issue.

**Comment by Kastor16** [comment]
Recently switched to KDE and wayland and the problem extends into the Help > System Information screen. 

Right click copy to clipboard no longer works. If you submit game reports on proton you need that information and it's stuck in that screen now.

**Comment by sonic2kk** [comment]
There has been a small change in behaviour. Now when I try to paste after doing Right Click -> Copy Page URL, it copies *some kind* of data to my clipboard but it isn't text data.
- KDE's Clipboard Manager shows the last valid text/image copied as the most recently copied thing
- When I try to paste into the FIrefox search bar, nothing happens.
- When I try to paste into a text field on a web page (such as on GitHub while writing this reply), the page will freeze for around 30 seconds.
- When I paste into applications such as Kate or VSCodium, they become unresponsive and have to be killed from a process monitor.

**Comment by Kastor16** [comment]
As of today's release steam has a new look interface and all my copy and paste issues have gone away.

**Comment by sonic2kk** [comment]
On my machine the behaviour I described in my most recent comment still applies. *Some* kind of data is copied, but it will crash most programs I try to paste it into, and programs that won't crash just simply act like nothing was on the clipboard.

**Comment by perroboc** [comment]
Retesting:

- Steam client beta: up to date
- Arch linux: up to date
- KDE Wayland session
- Using clipboard manager in KDE to check clipboard contents
- Steam installed from official Arch repo

Results:

- Copy text from firefox, paste `CTRL+V` on Steam: ✔️
- Copy text from firefox, paste `Right Click > Paste` on Steam: ❌
- Copy text from Steam `CTRL+C`: ✔️
- Copy text from Steam `Right Click > Copy`: ❌
- Copy URL from Steam `Right Click on Page > Copy Page URL`: ❌

So my understanding is that the menus are not working?

Issue #9542 seems to be a duplicate of this.

**Comment by dsalt** [comment]
Testing in steamwebhelper only.

I see that the text is being placed into both the primary selection and the clipboard without requiring use of the menu or of Ctrl-C. I checked using the following shell script:
```sh
for i in primary secondary clipboard buffer-cut; do
  echo "$i: $(xclip -o -selection "$i")"
done 2>/dev/null
```

Using the ‘copy’ menu items works fine here. I used `xclip` to set different text after selecting some text and before using the menu item. Similarly, URL copying works fine.

(Current Steam beta, time stamp 1692911603. Desktop is Xfce 4.18, and I have xfce4-clipman running.)

**Comment by perroboc** [comment]
Using your script both in X11 and Wayland KDE, copying with the right click menu from Steam.
```sh
for i in primary secondary clipboard buffer-cut; do
  echo "$i: $(xclip -o -selection "$i")"
done 2>/dev/null
```

X11:
```log
primary: Recommended
secondary: 
clipboard: Recommended
buffer-cut: 
```

Wayland:
```log
primary: Posted: 25 Aug @ 7:28pm
secondary: 
clipboard: 
buffer-cut:
```

It seems to be a bug in KDE Wayland.

> Desktop is Xfce 4.18, and I have xfce4-clipman running.
You don't seem to be using Wayland. The clipboard works fine in X11. Can you test in a wayland desktop?

**Comment by adamant-pwn** [comment]
I have the samy issue on Hyprland (Wayland WM). Copying doesn't work -- the clipboard gets reset to the empty value if I try to copy anything with Ctrl+C or "Copy" from the context menu.

**Comment by sonic2kk** [comment]
For what it's worth, this has been working fine for me for the last while, at least the last few months that I can remember (although probably longer).

@adamant-pwn Maybe clipboard sync is needed because Steam runs via XWayland?

**Comment by adamant-pwn** [comment]
Yes, likely so.

**Comment by Managor** [comment]
Is https://github.com/ValveSoftware/steam-for-linux/issues/10647 a duplicate of this or is it a separate issue?

**Comment by sonic2kk** [comment]
I think it's separate. I believe my issue is resolved here and I will close this issue. :-)
