### ISSUE TITLE
Keystrokes are ignored when Steam sends notifications on the new beta

### ISSUE THREAD

**Issue by ardishco-the-great** [ValveSoftware/steam-for-linux#9475]
#### Your system information

* Steam client version (build number or date): 
* Distribution: Arch Linux (6.3.1-arch1-1)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Desktop Environment/Window Manager: SwayWM (Wayland)

#### Expected behaviour:

I expect my keystrokes not to be ignored when I receive a notification like before
After opting into the steam beta, I started observing this behaviour, so I opted out for the time being.

#### Steps for reproducing this issue:

1.  Opt into Steam Beta
2.  Get steam notification
3.  Try to type on Discord or any other program that accepts keyboard inputs
4.  Realize your keystrokes are being ignored (but your mouse is not)

This behaviour is not observed when you're playing a game though, strangely enough

**Comment by kisak-valve** [comment]
Hello @ardishco-the-great, this issue is already being tracked at #9458. Closing as a duplicate.
