### ISSUE TITLE
Unable to set screenshot hotkeys to function keys

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#9478]
#### Your system information

* Steam client version (build number or date): 
![image](https://user-images.githubusercontent.com/42655600/236932289-952046bd-16ae-44ac-8ecf-c571bc4d52c6.png)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative video: https://youtu.be/ZJNet04ZenE
When attempting to set the screenshot hotkey to the function keys, steam for some reason assigns them to basic keys. Ultimately the key that is shown in settings is the one that works as the screenshot key

#### Steps for reproducing this issue:

1. Try to set the screenshot shortcut to a function key.

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #9380. Closing as a duplicate.
