### ISSUE TITLE
[New Steam UI] Uncompressed screenshots not working

### ISSUE THREAD

**Issue by alosarjos** [ValveSoftware/steam-for-linux#9479]
#### Your system information

* Steam client version (build number or date): 1683314987
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes]
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Uncompressed screenshots aren't working. When trying to change the directory on the settings to the one I've always used, it doesn't change and keeps showing my "documents" directory, and even with that, on any of both folders are screenshots being generated

#### Steps for reproducing this issue:

1. Enable uncompressed screenshots from "in-game" settings
2. Try to change directory to save them to a different one
3. Make a screenshot and check if it's been generated on that dir

**Comment by kisak-valve** [comment]
Partial duplicate of #9415.

**Comment by RomeuG** [comment]
It also does not work for me. I can't even change directory in the current stable release.
In the beta release, I can change the directory but Steam instantly crashes.

Even though the option to save uncompressed screenshots is enabled, I do not see any being created, even in the default directory.

**Comment by alosarjos** [comment]
Fixed
