### ISSUE TITLE
[Feature Request] Run Exe Inside of Game's Proton Prefix

### ISSUE THREAD

**Issue by tlneondo** [ValveSoftware/steam-for-linux#9480]
#### Your system information
* Distribution: Endeavor
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

This is the purview of external tools like ProtonTricks and Bottles, but for new Users coming in on the steam deck, its already a big ask to teach them how a Wine Prefix works. This would do a lot to help ease these people in.

**Comment by kisak-valve** [comment]
Hello @tlneondo, this feature request is already being tracked at #5766. Closing as a duplicate.
