### ISSUE TITLE
[New UI] Find in Page doesn't work 

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/steam-for-linux#9483]
#### Your system information

* Steam client version (build number or date): Fri, May 12 21:55 UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux (KDE Plasma Wayland)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Using Ctrl+F on web pages in the Steam Client, such as the Store Page, News Page, Profiles, etc, does not work properly. The find bar will appear in the top right, but clicking into it and typing does nothing.

If a textbox from another application is focued (*excluding* textboxes within the Steam Client), such as a browser search box, even after clicking on the Find in Page search box in Steam, the text input will register with the application whose textbox has focus.

This does **not** affect web pages opened with the Steam Overlay (tested Steam Workshop and Web Browser).

#### Steps for reproducing this issue:
1. Open a web page on the Steam Client, e.g. the Store Page.
2. Press Ctrl+F to open the search box.
3. Start typing.
4. No text will get entered into the search box.
5. With the Find in Page box still opened in Steam, click a textbox from another application, such as the Firefox search bar.
6. Click the Find in Page textbox inside of Steam and start typing.
7. Text entered will appear in the focused textbox from the previous application and not in the Find in Page search box.

**Comment by kisak-valve** [comment]
Hello @sonic2kk, can you test if the same behavior happens with a KDE / X user session?

**Comment by sonic2kk** [comment]
It will be on a different machine but yes I will test and report back (switching between Wayland/X session on KDE is a little touchy, so don't want to do that on my main PC)

**Comment by rejedai** [comment]
> Hello @sonic2kk, can you test if the same behavior happens with a KDE / X user session?

It is. https://steamcommunity.com/groups/SteamClientBeta/discussions/3/6861841362661980903/

**Comment by sonic2kk** [comment]
Can confirm, broken on X11 on SteamOS.

**Comment by sonic2kk** [comment]
Find in Page still does not work, but the focus issue appears to be resolved. So right now the only issue is that the textbox for Find in Page does not accept any input. The cursor appears and the textbox can be focused/unfocusd, it is only input that does not work.

**Comment by Managor** [comment]
I'm not entirely sure what determines the place it spawns in. I've had it spawn on middle right and now it spawns in the center. I've also had people say theirs spaws at bottom middle right on top of the downloads indicator. [Screencast_20240320_074949.webm](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/7fc34311-fdb8-4bd0-9bcd-199787ee330c)

**Comment by sonic2kk** [comment]
Sometimes the dialog spawns in the wrong place but the feature works now, so I will close this issue.

**Comment by int3rnauta** [comment]
I still have the same issue since the same period.

I have the same setup as @sonic2kk , but with the latest Steam version, of course.

- Steam client version (build number or date): 1737514353  -   Wed, Jan 22 3:35 UTC -08:00
- Distribution (e.g. Ubuntu): Arch Linux (KDE Plasma Wayland)
- Opted into Steam client beta?: No, but It's the same with the Beta Client
- Have you checked for system updates?: Yes

In the past I managed to trick the input box and trigger some input (only part of the keystroke appeared in the input box), but I can't reproduce it anymore.
