### ISSUE TITLE
Browser component fails to handle some window maximisation combinations

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/steam-for-linux#9484]
Window manager is Xfwm4. Steam client build date is 1683926267.

Toggling maximisation along both axes via the window manager causes the browser component to display nothing but a blank background. It does not matter which axis is first or whether both are done together, and it happens in both the main window and in steamwebhelper windows.

**To reproduce this**, you will first have to assign key bindings for maximising the window horizontally and vertically _or_ force the Steam window to have server-side decorations – this can be done using devilspie2 and the following in ~/.config/devilspie2/main.lua:
```lua
app_name = get_application_name()
if app_name == 'Steam' or app_name == 'steam' or app_name == 'steamwebhelper' then
  decorate_window()
end
```

Xfwm4's window size toggling (via the window frame) is both axes, vertical and horizontal for the left, middle and right mouse buttons respectively.

**Comment by dsalt** [comment]
The window manager appears not to be relevant except in so far as it's providing the maximisation toggles. (I've tested with sawfish; behaviour is identical.)

**Comment by dsalt** [comment]
This also happens if I shade then unshade the window (with server-side decorations enforced) or, unless the window is pinned to all workspaces, if I switch between workspaces. It does _not_ happen if I toggle full-screen.

I'm reasonably sure that it's down to how the window's size is changed.

**Comment by dsalt** [comment]
Having just done further testing, I see that this also happens when restoring the window from fully maximised by _any_ method other than using Steam's own toggle-size button. (If using xfwm4's maximisation toggles, both axes have to be restored.)

**Comment by dsalt** [comment]
This trigger for the blank browser component bug appears to be fixed now.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by dsalt** [comment]
This should not be closed: while the browser component blanking bug is (partly?) fixed, the maximisation bug **is still present**. This bug report concerns the latter.

**Comment by dsalt** [comment]
Closing now as the remaining trigger (workspace switching) is now reported separately (#11198).
