### ISSUE TITLE
steamwebhelper will show blank screen when maximazing/minimizing window

### ISSUE THREAD

**Issue by Dandraghas** [ValveSoftware/steam-for-linux#9490]
#### Your system information

* Steam client version: 1683944175
* Distribution: Fedora 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When switching between max size window and minimized window steamwebhelper will show blank screen.

Strange that everything works fine if i do normal resizing. Only maximize/minimize will break steamwebhelper

Also i can recover broken steamwebhelper page by switching between store and library

Maybe its because of nvidia gpu, steam is very laggy/buggy on nvidia gpu's

### Videos:
https://github.com/ValveSoftware/steam-for-linux/assets/91272905/2ab4003a-c155-4447-b192-525be6ddc8d6

#### Steps for reproducing this issue:

1. Launch steam
2. Maximize/Minimize steam window
3. See that steamwebhelper showing blank screen

**Comment by kisak-valve** [comment]
Hello @Dandraghas, this issue is already being tracked at #9375. Closing as a duplicate.
