### ISSUE TITLE
Main Window becomes sluggish if there is a child open on another workspace [sway]

### ISSUE THREAD

**Issue by LAURAilway** [ValveSoftware/steam-for-linux#9491]
#### System information

* Steam client version (date): 2023-04-28
* Distribution : Siduction (Debian unstable)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes/
* Window manager: Sway

##### Behaviour:
When steam has a secondary window (i. e. a store page opened as seperate window via press of the middle mouse button or the friends view) open on another workspace than the main steam application, the main window becomes very sluggish, sometimes not even reacting to any input at all. The secondary window is not affected by this and continues funcioning as expected. If the two windows are moved to the same workspace, the issue resolves itself and the main window responds to input as expected once again.
(Edit: the settings menu does not seem to cause issues)

##### Expected Behaviour:
Having the main steam window and a seperate window such as the steam chat on different workspaces should not impact performance of the main client.

#### Steps for reproducing this issue:

1. Use Sway (not tested with other Window Manger so far)
2. Start steam
3. Open any secondary window from steam (i.e. friends list)
4. Move either one of the two windows to another workspace
5. Try interacting with the main steam window (especially the 'store', 'library' and 'community' buttons)

**Comment by kisak-valve** [comment]
Hello @LAURAilway, this issue is already being tracked at #7245. Closing as a duplicate.

**Comment by LAURAilway** [comment]
As far as I can tell it is another issue, as having the chat open on the same workspace does not cause slowdowns on my end.
