### ISSUE TITLE
[Beta] Store view unresponsive until tabs are switched

### ISSUE THREAD

**Issue by Trombach** [ValveSoftware/steam-for-linux#9497]
#### Your system information

* Steam client version (build number or date):
  * Steam Version:  1684200926
  * Steam Client Build Date:  Tue, May 16 1:13 PM UTC +12:00
  * Steam Web Build Date:  Tue, May 16 1:12 PM UTC +12:00
  * Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever I launch steam, the store page is unresponsive the first time I open it. The only remedy is to switch to another tab and back to the store tab.

#### Steps for reproducing this issue:

1. Launch Steam
2. Navigate to Store page
3. Attempt to click on something

[Screencast from 2023-05-16 21-37-51.webm](https://github.com/ValveSoftware/steam-for-linux/assets/19306765/04d3ce71-1854-4169-b80c-1d70ac6bfdb7)

Edit: It seems that there is a bug preventing the mouse cursor from being recorded on Gnome with X11. I hope the video is still useful

**Comment by kisak-valve** [comment]
Hello @Trombach, this issue is already being tracked at #9443. Closing as a duplicate.
