### ISSUE TITLE
Steam interprets the close window command sent by the window manager to mean quit, not close the window.

### ISSUE THREAD

**Issue by rokejulianlockhart** [ValveSoftware/steam-for-linux#9501]
#### Your system information

* Steam client version (build number or date): [image](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/88d8560a-aeb7-44fc-bae1-d4087ed09e8e)
> Steam Version:  1684288425
Steam Client Build Date:  Wed, May 17 02:32 UTC -08:00
Steam Web Build Date:  Wed, May 17 02:08 UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): 
```log
PS /home/rokejulianlockhart> uname -a
Linux RQN6C6 6.3.1-2-default #1 SMP PREEMPT_DYNAMIC Tue May  9 07:50:57 UTC 2023 (78ee477) x86_64 x86_64 x86_64 GNU/Linux
PS /home/rokejulianlockhart>
```
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
[`steam`](https://github.com/ValveSoftware/steam-for-linux/) interprets the close window command sent by the window manager (https://invent.kde.org/plasma/kwin in my case) to mean quit, not close the window. However, [`steam`](https://github.com/ValveSoftware/steam-for-linux/) should interpret the command to mean close the window rather than quit, because [`steam`](https://github.com/ValveSoftware/steam-for-linux/)'s current behaviour is nonstandard.

#### Steps for reproducing this issue:
0. Download [`KWinRules_NoTitleBarAndFrame.zip`](https://github.com/ValveSoftware/steam-for-linux/files/11502918/KWinRules_NoTitleBarAndFrame.zip).
0. Unzip the `.kwinrules` file.
0. Rename its extensions to simply `.kwinrules` rather than `.txt.kwinrules`.
0. Import the `.kwinrules` file via ![GUI:`systemsettings5`/CLI:`kcmshell5`.](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/66828228-dff8-443b-b487-73c40774d31c)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/a9ab0e86-d7fb-48a9-a569-671b1e4024a2) demonstrates that this works.
0. Launch [`steam`](https://github.com/ValveSoftware/steam-for-linux/).
0. Close [`steam`](https://github.com/ValveSoftware/steam-for-linux/) using the title bar.
[`steam`](https://github.com/ValveSoftware/steam-for-linux/) shall immediately quit.

**Comment by kisak-valve** [comment]
Hello @rokejulianlockhart, this issue is already being tracked at #3202. Closing as a duplicate.
