### ISSUE TITLE
Cannot change Compatibilty tool (Proton Version)

### ISSUE THREAD

**Issue by Defiant74ARN** [ValveSoftware/steam-for-linux#9502]
#### Your system information

* Steam client version (build number or date):  Apr. 2023, at 18:33:22
* Distribution (e.g. Ubuntu):  Fedora Linux  6.0.18-300.fc37.x86_64
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Hello !

I have attached the Steam SystemInfo Output and a screenshot.
I use steam on some linux machines and installed Steam using "Flatpak" (flatpak install flathub com.valvesoftware.Steam)

Since some weeks it is not possible any more to change the compatibility setting of an installed game. This behaviour is the same on all our machines.
I have attached a screenshot.
So this means the steam app shows me all available options, but clicking on it leads to nothing. The menu just closes.

I have temporarely removed all data and installed everything new, but the problem persists.

Maybe you know this problem and you can help me.

Thank you very much!

Best regards,
Arno. 

#### Steps for reproducing this issue:

1.  Start Steam Client
2.  Choose Properties at an installled game
3.  Select "Compatibility" 
4. Check "Force the use of specific...."
5. Select  the desired proton version
6. Menu closes, but nothing changes. The setting in as before

[SteamSysInfo.txt](https://github.com/ValveSoftware/steam-for-linux/files/11507989/SteamSysInfo.txt)
![Screenshot from 2023-05-18 10-10-08](https://github.com/ValveSoftware/steam-for-linux/assets/82668265/059eff0a-8d49-4c99-9ce1-a615374134da)

**Comment by kisak-valve** [comment]
Hello @Defiant74ARN, this issue is already being tracked at #9273. Closing as a duplicate.

**Comment by Defiant74ARN** [comment]
Thanks for the fast response. Disabling "Focus on Hoover" is an acceptable workaround.

Regards,
 Arno.
