### ISSUE TITLE
Please add `STEAM_FORCE_DESKTOP_SCALING=2.0` environment

### ISSUE THREAD

**Issue by Arcitec** [ValveSoftware/steam-for-linux#9505]
Steam beta has a new command-line flag: `-forcedesktopscaling`

It can be triggered manually via:

```
flatpak run com.valvesoftware.Steam -forcedesktopscaling 2.0
```

But this is very annoying because it requires copying and editing the `.desktop` shortcut files.

Please make it read from environment variable too. Because Flatpak (Flatseal) is able to permanently set environment variables effortlessly. Without having to edit anything.

I'd love to be able to set env `STEAM_FORCE_DESKTOP_SCALING=2.5` for example. :)

This is related to: https://github.com/ValveSoftware/steam-for-linux/issues/9466#issuecomment-1553014344

**Comment by kisak-valve** [comment]
Hello @Arcitec, per `Added an env var based override for scaling settings STEAM_FORCE_DESKTOPUI_SCALING=<float>.` in the [2023-06-15](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/6627657351330751106) Steam client beta, please opt into Steam's client beta and retest this issue.

**Comment by lostgoat** [comment]
Latest steam update added `STEAM_FORCE_DESKTOPUI_SCALING=<float>`

**Comment by Arcitec** [comment]
# September 9th, 2025, the desktop scaling issues are finally gone forever. 🥳 

https://github.com/ValveSoftware/steam-for-linux/issues/9466#issuecomment-3276314518
