### ISSUE TITLE
[Discussion] Consolidate Steam distribution as official Flatpak.

### ISSUE THREAD

**Issue by xioren** [ValveSoftware/steam-for-linux#9512]
I'd like to propose this as a potential future for Steam distribution. Instead of managing multiple versions for different distros I believe it makes sense to consolidate focus and resources into a single package that is broadly compatible. Many apps I use are heading in this direction and I believe containerized apps are the future.

Is this something that has been considered?

**Comment by kisak-valve** [comment]
Hello @xioren, this issue is already being tracked at #4473. Closing as a duplicate.
