### ISSUE TITLE
Steam Beta causes Xorg to use a large amount of VRAM.

### ISSUE THREAD

**Issue by BlueGoliath** [ValveSoftware/steam-for-linux#9516]
#### Your system information

* Steam client version (build number or date):  1684535786
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Steam causes Xorg to use a large amount of VRAM. For example, on a GTX 960(4GB), peak desktop VRAM is 1906 with Xorg consuming 1143 of it. After closing Steam, total memory drops by roughly 800MB(790) while Xorg drops by 535 MB. I've seen VRAM usage way higher before as well because of Steam/Xorg.

#### Steps for reproducing this issue:

No idea.

**Comment by kisak-valve** [comment]
Hello @BlueGoliath, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.
