### ISSUE TITLE
You cannot assign the F1-F12 buttons to the screenshot button if pressing them requires Fn

### ISSUE THREAD

**Issue by Artem13327** [ValveSoftware/steam-for-linux#9519]
#### Your system information

* Steam client version (build number or date):  1684535786 May 20 2023
* Distribution (e.g. Ubuntu): PeppermintOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: No

**Comment by kisak-valve** [comment]
Hello @Artem13327, this issue is already being tracked at #9380. Closing as a duplicate.
