### ISSUE TITLE
[BETA] Right-click context menu freezes/crashes client

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/steam-for-linux#9523]
#### Your system information

* Steam client version (build number or date): Latest Beta Client
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

 [system info](https://gist.githubusercontent.com/jazztickets/f07f40cf0896a257b911325fc21f5e1a/raw/6c754b42e2f4287eab7b17e812707e1b3b1a66f7/main%2520system%2520info)

#### Steps for reproducing this issue:

1. Go to a page that allows the right-click context menu (e.g. Store page)
2. Spam right-click in different areas

This video shows the menu work for a few seconds, then black boxes start appearing. The entire steam client will then freeze until it restarts after 10-20 seconds.
https://github.com/ValveSoftware/steam-for-linux/assets/425930/4d284271-6e74-4904-88af-50c8da9b8e6a

**Comment by rurigk** [comment]
I also experience this problem, the context menu don't work and if you keep spaming steam crashes

For extra information i use Arch as well and my window manager is Hyprland (wayland), i dont have any other DE to test

**Comment by jazztickets** [comment]
I tried the latest beta and it seems to be better now. Although I noticed that when the menu closes, 2 windows are created/destroyed almost instantly:

https://github.com/ValveSoftware/steam-for-linux/assets/425930/414e1447-e825-49ea-8f6c-32809b2a2c20

I'm on XFCE.

**Comment by jazztickets** [comment]
The latest stable (2023-07-10) still has the crash.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
