### ISSUE TITLE
kali linux: steam giving error code -324

### ISSUE THREAD

**Issue by lexyclear** [ValveSoftware/steam-for-linux#9526]
#### Your system information

* Steam client version (build number or date): sneak peek
* Distribution (e.g. Ubuntu): kali lts
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No]yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
steam keeps giving error code -324. it should be allowing me to interact with dashboard my friends and the store. instead its not allowing anything.
#### Steps for reproducing this issue:

1. start my steam
2. get error code
3. restart it and same error code every time.

**Comment by kisak-valve** [comment]
Hello @lexyclear, sorry, but Kali Linux is not supported here because it's contradictory to the fundamental goals of the distribution, which focuses on security testing and is not intended to be used as a general purpose desktop environment.
