### ISSUE TITLE
Library, Freezing due to steamwebhelper process

### ISSUE THREAD

**Issue by Eddy-Pin** [ValveSoftware/steam-for-linux#9529]
System Information: https://gist.github.com/Eddy-Pin/6e31380d8147103030e0f86372408c63
* Steam client version (build number or date): May 25-26, 2023
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/) 
Booted my system after updating everything after installing a new GPU (Nvidia to Radeon), Nvidia drivers were purged before updating. Started up steam and after a minute of use, the UI started to freeze up to the point of being non-functioning, while the program itself was still running. Terminating the steamwebhelper process through htop temporarily fixes the issue. Signing out of Friends & Chat function fixes the issue. No clue how to reproduce the issue. I have turned off everything related to the Interface in terms of hardware acceleration and smooth scrolling, use low bandwith mode/low performance mode as well, which was suggested on other platforms.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @Eddy-Pin, this issue is already being tracked at #7245. Closing as a duplicate.
