### ISSUE TITLE
[Beta] Videos on a game's store page will continue to play (sound is heard) even after closing the Steam client window

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/steam-for-linux#9540]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1685072487
Steam Client Build Date:  Thu, May 25 10:25 PM UTC -06:00
Steam Web Build Date:  Thu, May 25 10:23 PM UTC -06:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): Xubuntu 23.04
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Videos on a game's store page will continue to play (sound is heard) even after closing the Steam client window.

#### Steps for reproducing this issue:

1. Go to a store page for a game which has a video that plays such as No Man's Sky.
2. Ensure the volume is not muted and the video is playing.
3. Close the Steam client window.
4. Notice the video's sound is still audible and continues to play despite the client window being closed.

**Comment by kisak-valve** [comment]
Hello @nightsky30, this issue is already being tracked at #5234. Closing as a duplicate.
