### ISSUE TITLE
Can't start any game while another game is uploading data to the steam cloud

### ISSUE THREAD

**Issue by eNTi** [ValveSoftware/steam-for-linux#9544]
#### Your system information

* Steam client version (build number or date): 1685072487
* Distribution (e.g. Ubuntu): Artix
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expect steam to start a game and not wait for minutes on end before doing so while save games are uploaded to the steam cloud. This might degrade my experience for online titles but it's completely irrelevant for offline games!

#### Steps for reproducing this issue:

1. Play game 1 and creat saves/screenshots
2. Stop game
3. Try to start game 2 while steam uploads saves/screenshots to the cloud
4. WAIT...

**Comment by kisak-valve** [comment]
Hello @eNTi, this issue is already being tracked at #7581. Closing as a duplicate.
