### ISSUE TITLE
Streaming issues with Proton and/or Gamescope nested

### ISSUE THREAD

**Issue by alvaromunoz** [ValveSoftware/steam-for-linux#9546]
#### Your system information

* Steam client version (build number or date): 1685483787
* Distribution (e.g. Ubuntu): Arch (Host), SteamOS (Steam Deck used for remote play)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

Extra info:
- Audio: pipewire
- Compositor: Wayland
- Desktop environment: KDE Plasma
- Proton 8.0-2

#### Please describe your issue in as much detail as possible:

TL:DR: I'd like to be able to stream Proton games and Gamescope nested games from my desktop launched Steam client. These settings present issues that make it impossible to correctly stream from a Linux host.

Using Darkest Dungeon as an example, I've installed it in an Arch host, with the intent of testing remote play in my steam deck. This game is available as a native Linux game, and also as a Windows game through Proton. I also usually use Gamescope in my Arch machine to make better use of some fullscreen games.

This is the result of the streaing tests, from the Arch host to a Steam Deck (the issues were present in both Gaming and Desktop mode, so it's a host issue):

| Game binary | Gamescope         | Video                 | Audio | Controls |
| ----------- | ----------------- | --------------------- | ----- | -------- |
| Linux       | No                | Yes                   | Yes   | Yes      |
| Linux       | Nested            | Stream loading screen | Yes   | No       |
| Linux       | Steam Integration | Yes                   | Yes   | Yes      |
| Windows     | No                | Black screen          | Yes   | Yes      |
| Windows     | Nested            | Stream loading screen | Yes   | No*      |
| Windows     | Steam Integration | Yes                   | Yes   | Yes      |

\* In Doom Eternal a right touchpad click seems to send something that opens the events page. Everything else is broken.

Since the most compatible scenario is the last one, I've tested other games there like Wolfenstein II and Doom Eternal, and they run as expected.

Steam Integration means launching steam with `gamescope -e -- steam -tenfoot -steamos`

Nested means using these Launch options for a game: `gamescope --nested-width 1920 --nested-height 1080 --nested-refresh 144 --output-width 1920 --output-height 1080 --fullscreen -- %command%`

Gamescope nested seems to block capturing the right PID? And proton without Gamescope integration seems to not send video.

#### Steps for reproducing this issue:

1. Stream from a Linux host with a game setup as above to a steam deck (either in gaming or desktop mode)
2. Test as per the table

**Comment by kisak-valve** [comment]
Hello @alvaromunoz, please give #6148 a read. In particular, the `-pipewire` and maybe `-pipewire-dmabuf` launch options are currently needed to allow Steam Remote Play to capture from Wayland surfaces and gamescope is a Wayland based compositor.

From the looks of it, you've described Remote Play working when both Steam and the game share the same X session inside of Xwayland.

Closing in favor of #6148.
