### ISSUE TITLE
Steam Wallet credit in corner doesnt update when spending money

### ISSUE THREAD

**Issue by OhaDerErste** [ValveSoftware/steam-for-linux#9549]
#### Your system information

* Steam client version (build number or date): 1685483787
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. Add Money to your Steam Wallet
2. Spend it
3. Amout of money next to your Account name doesnt change
![image](https://github.com/ValveSoftware/steam-for-linux/assets/77100649/ff334faf-c829-4055-9b88-91a98a27401f)

**Comment by FQQD** [comment]
I also have the same problem D:

**Comment by kisak-valve** [comment]
Hello @OhaDerErste, @FQQD, per `Fixed incorrect pending wallet balance.` in the [2023-06-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3674420533464178988) Steam client beta, this issue might be resolved.
