### ISSUE TITLE
Flatpak Big Picture cannot shutdown system

### ISSUE THREAD

**Issue by 13hannes11** [ValveSoftware/steam-for-linux#9550]
#### Your system information

* Steam client version (build number or date): 1685483787
* Distribution (e.g. Ubuntu): Fedorar Silverblue 38
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When triggering the shutdown menu option in big picture mode the big picture mode turns black but nothing is happening. When running Steam using the commandline with `flatpak run com.valvesoftware.Steam` I can see the following error when triggering the button:

```
sh: line 1: lsb_release: command not found
sh: line 1: lsb_release: command not found
Error org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

There is a steam dicsussion where someone mentions the issue as well:
https://steamcommunity.com/app/221410/discussions/2/3763354579678964105/

#### Steps for reproducing this issue:

1.  Install Steam via Flatpak
2. Launch BigPicture mode
3. Go to the menu and trigger shutdown.

**Comment by kisak-valve** [comment]
Hello @13hannes11, this reads like a restriction in the Flathub-provided Steam packaging, not an issue with the Steam client itself. That is being tracked at https://github.com/flathub/com.valvesoftware.Steam/issues/1072.

Closing in favor of the older issue report.

**Comment by moviuro** [comment]
I have fixed this by hijacking the obsolete DBus calls made by Steam. Also involves punching holes into the sandbox: https://github.com/flathub/com.valvesoftware.Steam/issues/1072#issuecomment-3898393858
