### ISSUE TITLE
Steam creates a new panel entry instead of reusing the pinned entry

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#9551]
#### Your system information

* Steam client version (build number or date):  1685572056
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With the latest Steam Beta update, steam opens a new entry (Red arrow) in my panel, instead of using the pinned launcher entry (Green arrow). The new entry can't be pinned to the panel.

![grafik](https://github.com/ValveSoftware/steam-for-linux/assets/7719590/9bbcd673-1927-434e-888a-77cad1610b95)

#### Steps for reproducing this issue:

1.  Have Steam launcher pinned to the panel and let it stack windows.
2. Open steam
3. Steam uses a new entry in the panel instead of reusing the pinned entry

**Comment by NoXPhasma** [comment]
We've had a similar issue a while ago, which was fixed https://github.com/ValveSoftware/steam-for-linux/issues/9235

**Comment by faattori** [comment]
I can confirm this, "steamwebhelper" extra entry appeared after updating to latest beta. This did not happen in beta before that.

**Comment by echaskaris** [comment]
Edit the title with [Regression] so it's fixed quickly

**Comment by Apxdono** [comment]
Still observed with latest beta-client:
[System/HW Info](https://gist.github.com/Apxdono/b7dc4050bf282cb0e38cd4974353488c)

```
Steam Version:  1685664179
Steam Client Build Date:  Fri, Jun 2 2:35 AM UTC -08:00
Steam Web Build Date:  Fri, Jun 2 2:19 AM UTC -08:00
Steam API Version:  SteamClient020
```

**P.S. for KWIN users**
This looks like an issue with Window class, since it also affects my `kwin` rule: all windows with `steam` class exactly are moved to Secondary Virtual Desktop in my case. 

This can be **partially mitigated** by changing `Exact Match` to `Regular Expression` -> `^steam.*`.

**Comment by NoXPhasma** [comment]
This issue still persists on the latest beta patch version 1686092969

**Comment by NoXPhasma** [comment]
Fixed with the [latest beta update](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3651903168569436963).
