### ISSUE TITLE
Steam notifications do not appear on the correct spot when using two monitors with vastly different resolutions

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/steam-for-linux#9554]
#### Your system information

* Steam client version (build number or date): 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/623876fc-2703-4d7e-a278-a31b245aac53)
* Distribution: Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Demonstrative image: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/42655600/5b14b2b8-6436-4bb9-807e-d4b7688345b5)
I'm using X11

**Comment by kisak-valve** [comment]
Hello @Managor, this issue is already being tracked at #9374. Closing as a duplicate.
