### ISSUE TITLE
Browse game files opens directory in VSCodium if installed on Steam Beta

### ISSUE THREAD

**Issue by BlueGoliath** [ValveSoftware/steam-for-linux#9560]
But why?

See https://github.com/ValveSoftware/steam-for-linux/issues/9516 for system details.

**Comment by kisak-valve** [comment]
Hello @BlueGoliath, the current Steam client beta is expected to use xdg-desktop-portal for this. It's highly likely system has been configured to use vscodium for this type of dialog similar to https://github.com/VSCodium/vscodium/issues/409.

This configuration is user choice and not a Steam bug.
