### ISSUE TITLE
Launching game from tray icon does not start game's launcher

### ISSUE THREAD

**Issue by SnoutBug** [ValveSoftware/steam-for-linux#9562]
#### Your system information

* Steam client version (build number or date): 1685664179
* Distribution (e.g. Ubuntu): Nobara Linux 37
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Launching a game from the tray icon does not start the steam game launcher, but rather tries to start the first entry in that list. I would expect that steam would launch the most recently selected option instead, or open the games launcher.

Below is the launcher I am talking about
![image](https://github.com/ValveSoftware/steam-for-linux/assets/71790678/6b6dcab0-75fd-482f-bf40-c37bd445673f)

#### Steps for reproducing this issue:

1. Install game using the steam launcher, eg. Ready Or Not
2. Launch Game from Steam Library
    a. See Launcher opening
3. Launch Game from tray icon:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/71790678/1a432929-6603-4fe2-bd35-c7ae2da5f91d)
   a. See game launching without launch option selection

**Comment by kisak-valve** [comment]
Hello @SnoutBug, this is the same issue as #6640. Closing in favor of the older issue report.
