### ISSUE TITLE
Opening steams system info or copying from it crashes Gnome desktop or whole OS

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#9563]
#### Your system information

* Steam client version (build number or date): May 30 2023 
* Distribution (e.g. Ubuntu):  Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If you copy text from steam like from the hardware info for example it would crash the Gnome desktop or the whole OS a few seconds after doing it, I also recorded what happened via systemctl journal  and video. I also notice  a lot of xserver errors in the log while I am using Wayland.

https://gist.github.com/coreybruce/98847beb634403384243a7b2a132d4eb

https://cdn.discordapp.com/attachments/891562634971852810/1110753023040434176/VID20230524121331.mp4

#### Steps for reproducing this issue:

1.  go to  help>system info 
2. either just open the system infor or right click and copy and the desktop will crash. Literally crashed my desktop by just opening it while I was writing this and going through the step so I could write it down.

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue is already being tracked at #9267 and is a video driver regression in the kernel. Closing as a duplicate.
