### ISSUE TITLE
Toasts stealing focus from active application in Sway

### ISSUE THREAD

**Issue by DrymarchonShaun** [ValveSoftware/steam-for-linux#9568]
#### Your system information

* Steam client version (build number or date): 
Build # -- 1685664179 
Build Date -- Thu, Jun 1 4:35 PM UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux; [Sway](https://github.com/swaywm/sway/) as my WM/DE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The toasts/notifications/popups  (for things like friends starting a game, or coming online) are taking focus away from the active window, which stops user input in the active window (web browser, discord, etc.) until the notification goes away.

#### Steps for reproducing this issue:

1. Launch the UI beta update in Sway 
2. Open another application that allows text entry
3. Wait for a notification, and try to type.

**Comment by kisak-valve** [comment]
Hello @DrymarchonShaun, this issue is already being tracked at #9458. Closing as a duplicate.
