### ISSUE TITLE
Steam appears not working against GCC 13.1

### ISSUE THREAD

**Issue by gbschenkel** [ValveSoftware/steam-for-linux#9573]
#### Your system information

* Steam client version: May 30 2023, at 20:40:51
* Distribution: Slackware
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After upgrading to GCC 13.1, Steam can't launch it anymore.
`~/.local/share/Steam/steam.sh: line 798: 11179 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@"`
From what I read on the steam.sh script, it is checking for debuggers, and something on is "wrong" inside the IF FI statement, because the line 798 is where FI resides.

I have tried remove the pinned_libs from `~/.local/share/Steam/ubuntu12_32/steam-runtime` but didn't work either.

In the end I reverted back to GCC 12.2 and Steam started to opened again. Maybe some libs need be recompiled with GCC 13.1, like GLIBC perhaps.

#### Steps for reproducing this issue:

1.  Upgrade to GCC 13.1
2.  Launch Steam (on GUI or console)
3. Steam will try to sync libs and check upgrade and before to load, it crash.

**Comment by kermeat** [comment]
Works fine with 13.1.1 on arch

**Comment by af7567** [comment]
I just updated slackware64-current and have gcc-13.1.0 too, but steam stable and beta clients both start OK for me.
"$STEAMROOT/$STEAMEXEPATH" will be ~/.local/share/Steam/ubuntu12_32/steam which is a 32-bit executable, so if you are using Slackware64 did you also update multilib to gcc-13.1.0?

I have the following package versions:

```
/var/log/packages/gcc-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-g++-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-gdc-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-gfortran-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-gm2-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-gnat-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-go-13.1.0_multilib-x86_64-2alien
/var/log/packages/gcc-objc-13.1.0_multilib-x86_64-2alien
/var/log/packages/gccmakedep-1.0.3-noarch-4
/var/log/packages/glibc-2.37_multilib-x86_64-2alien
/var/log/packages/glibc-i18n-2.37_multilib-x86_64-2alien
/var/log/packages/glibc-profile-2.37_multilib-x86_64-2alien
/var/log/packages/glibc-zoneinfo-2023c-noarch-1
/var/log/packages/steamclient-1.0.0.76-x86_64-1alien
```

I only knew there was an update from seeing this issue :) so it is possible that the multilib packages weren't uploaded when you updated so you only have the 64 bit.

**Comment by gbschenkel** [comment]
@af7567 Nops, I was using GCC 13.1 Multilib soon Alienbob released it, but I stop few months ago after Steam Client Beta wasn't loading the window content, also due a issue with right click menu getting stucked not allowing close it anymore, only when exiting the Steam Client.

I will try update the Client and reinstall GCC 13.1 (Multilib) to check.

**Comment by kisak-valve** [comment]
Closing per the last comment.
