### ISSUE TITLE
Steam won't launch from desktop graphical menu

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#9574]
#### Your system information

* Steam client version (build number or date): 1686278536
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Whenever i launch Steam through KDE Plasma's default menu it'll try to load the main interface but only opens a black window briefly before closing it. Then it'll try again and again and so on until you quit Steam or kill it. 

journalctl shows steamwebhelper is crashing every time. 
The curious thing is if you launch steam through the terminal it launches just fine. 

I have no idea why this is happening but it is. The only difference is Arch's kde distribution of Steam links the menu to execute 
/usr/bin/steam-runtime by default. While the terminal launches /usr/bin/steam but both are just bash scripts which exec /usr/lib/steam/steam

This happens on both x11 and Wayland.

Brief demo: 
https://github.com/ValveSoftware/steam-for-linux/assets/42720874/0539bc4d-08fd-45b8-ae3f-6917893793ba

#### Steps for reproducing this issue:

1. Start Steam in KDE Plasma's default menu
2. Observe multiple crashes

**Comment by kisak-valve** [comment]
Hello @iodream, this issue is already being tracked at #9383. Closing as a duplicate.
