### ISSUE TITLE
Steam refuses to close properly, presumably due to Wine

### ISSUE THREAD

**Issue by Visne** [ValveSoftware/steam-for-linux#9575]
#### Your system information

* Steam client version (build number or date): 1686278536
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes (though I am quite certain that this was an issue before I was using the beta version)
* Have you checked for system updates?: Yes
* DE: KDE

#### Please describe your issue in as much detail as possible:
After closing Steam, it refuses to close entirely and when trying to restart it does not reopen. Also, when shutting down my system I will always get a notification saying `A stop job is running for User Manager for UID 1000`. This is Steam still trying to close, and I will have to wait for the 90 second cooldown before it is SIGKILLed. That means I have to wait every time when rebooting, unless I manually SIGKILL Steam myself first.

On next boot, I find this in my `journalctl -b-1`:
```
Jun 09 18:48:41 arch systemd[637]: app-steam-f8b4be5360c24d8f80c568ee3e2472d5.scope: Stopping timed out. Killing.
Jun 09 18:48:41 arch systemd[637]: app-steam-f8b4be5360c24d8f80c568ee3e2472d5.scope: Killing process 3047 (pressure-vessel) with signal SIGKILL.
Jun 09 18:48:41 arch systemd[637]: app-steam-f8b4be5360c24d8f80c568ee3e2472d5.scope: Killing process 3107 (winedevice.exe) with signal SIGKILL.
Jun 09 18:48:41 arch systemd[637]: app-steam-f8b4be5360c24d8f80c568ee3e2472d5.scope: Killing process 3296 (wine_sechost_se) with signal SIGKILL.
Jun 09 18:48:41 arch systemd[637]: app-steam-f8b4be5360c24d8f80c568ee3e2472d5.scope: Failed with result 'timeout'.
```
This makes me believe that the cause is related to Wine. Note that if I manually try to kill `winedevice.exe` it refuses to close, I have to SIGKILL it before it actually closes.

#### Steps for reproducing this issue:

1. Run Steam
2. Close Steam
3. Restart Steam
4. Steam does not open
5. Run `killall steam`
6. Note that it does not output `steam: no process found`
7. Run `killall -9 steam`
8. Restart Steam
9. Steam opens

Additionally:
1. Run Steam
2. Shut down system
3. Note that 90 second cooldown is required before Steam is SIGKILLed and system completely shuts down
4. Restart system, run Steam
5. Run `killall -9 steam`
6. Shut down system
7. Note that there is no 90 second cooldown

**Comment by kisak-valve** [comment]
Hello @Visne, the scenario you've described reads like there is a misbehaving Proton build, and that the Steam client is just waiting for a child task to complete.

Do you have any third party Proton versions added to Steam? In particular, using a tool like `htop` and going into tree view by pressing `t`, and looking around, can you tell which Proton version has stalled?

**Comment by kisak-valve** [comment]
Yes, that issue should be evaluated by the package maintainer over at the AUR. Probably related to https://github.com/ValveSoftware/steam-runtime/issues/590.
