### ISSUE TITLE
thirdpartylegalnotices.doc and other documents should be in a more friendly document format.

### ISSUE THREAD

**Issue by olavd** [ValveSoftware/steam-for-linux#958]
While a lot of people have office suites and capable readers installed, it shouldn't be an requirement for reading files similar to thirdpartylegalnotices.doc. It's easier to make use of installed web browsers or the Steam client's Chromium Embedded Framework capabilities. And the latter will of course mean direct access from the client's menu system. It is also worth to take notice of Tim Berners-Lee e-mail requirements: http://www.w3.org/People/Berners-Lee/#Before

**Comment by Uramekus** [comment]
fixed
![2018-08-24-17 42 54-screenshot](https://user-images.githubusercontent.com/4643873/44606960-3ab2ea80-a7c5-11e8-895c-e731fee06a77.png)

**Comment by kisak-valve** [comment]
Thanks @Uramekus, closing.
