### ISSUE TITLE
Steam Crashes when "Start Steam in Big Picture Mode" Setting Enabled

### ISSUE THREAD

**Issue by hidinginside** [ValveSoftware/steam-for-linux#9580]
#### Your system information

* Steam client version (build number or date): 1685488080
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: This issue persists in all Steam client versions, beta or not.
* Have you checked for system updates?: Yes
* CPU: AMD Ryzen 7 5800X
* GPU: Nvidia GeForce RTX 3080 Ti
* Desktop Environment (in case this is somehow relevant): KDE Plasma 5.27.5

#### Please describe your issue in as much detail as possible:

So I have found that Steam crashes on the BPM boot logo if I choose the option "Start Steam in Big Picture Mode".  This occurs regardless of participation in the beta client or the stable client.  Big Picture Mode works just fine without this setting enabled. I don't know what update this bug first occurred in as this is my first time using this setting on Linux.

At first I thought I was stuck with no way out of this bug since I couldn't access Steam settings and reinstalling Steam didn't help, though I found that deleting all of the files in ~/.steam except for all of my downloaded games got me back to the regular client application.  I eventually narrowed it down to the file ~/.steam/registry.vdf and deleting that fixed it consistently, and within that file, deleting the "StartupMode" line specifically got me back to the client.  Though the problem still stands that the "Start Steam in Big Picture Mode" option does not work on my system.

I could not find any command line flags that seemed to help this issue, but [here is the output](https://gist.github.com/hidinginside/af975eb69157daa09e8b23a1da026d1e) that comes from running the Steam client from the command line during this crash.

#### Steps for reproducing this issue:

1. Turn on "Start Steam in Big Picture Mode"
2. Completely exit the Steam client
3. Execute the Steam client application
4. Steam crashes at some point during the boot animation

**Comment by kisak-valve** [comment]
Hello @hidinginside, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you're using the Steam client beta, then please also include the output from `Steam Runtime Diagnostics`.

**Comment by hidinginside** [comment]
Here is my [system information](https://gist.github.com/hidinginside/1c13e772fa58b0a118a76acbd89aeff2) and here is my [Steam runtime diagnostics](https://gist.github.com/hidinginside/e23028ca6da8d860381fba6114b610f8).

**Comment by kisak-valve** [comment]
Thanks, looking at the Steam Runtime Diagnostics, https://gist.github.com/hidinginside/e23028ca6da8d860381fba6114b610f8#file-gistfile1-txt-L3389 is the key detail. The NVIDIA proprietary driver requires that the running kernel module, 64 bit userspace libraries, and 32 bit userspace libraries are all installed and exactly the same version to work properly.

In your system, the 32 bit userspace libraries for the driver are not installed, so Steam is forced to fallback to mesa's faster software renderer, llvmpipe, to run at all. Please install the `lib32-nvidia-utils` system package and retest.

As a secondary detail, you'll also want to remove `lib32-amdvlk` to avoid https://github.com/GPUOpen-Drivers/AMDVLK/issues/315.

**Comment by hidinginside** [comment]
Thanks! Installing lib32-nvidia-utils fixed the issue for me.  It would have been nice to get some sort of obvious dependency warning somewhere, but nonetheless, it works now.

**Comment by kisak-valve** [comment]
Glad to hear that it's working. Closing because this was a system config issue.
