### ISSUE TITLE
UI Scale Not Changing and Friends Chat Pop Up on Start Can't be Turned Off

### ISSUE THREAD

**Issue by nekonosukeno** [ValveSoftware/steam-for-linux#9585]
#### Your system information

* Steam client version (build number or date): 1686779606 Wed, Jun 14 4:18 PM UTC -05:00
* Distribution (e.g. Ubuntu): Mint 21 (Mainline kernel)
* Opted into Steam client beta?: [Yes/No] Yes. Happens when opted out as well.
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The UI scaling is far too small to read on a High DPI 4K monitor/TV and cannot be manually adjusted. UI scale is the same whether "Scale text and icons to match monitor" (under Interface menu) is turned on or off. Also, Friends Chat window pops every launch despite being signed out. There is no setting to change this behavior. Setting GDK_SCALE=2 as an environment variable had no effect on the UI.

Update: A work-around if you face the scaling issue is to launch steam with command: steam -forcedesktopscaling 1.5 # or 2 or whatever works for your display. This can be added to the exec= line of the desktop file or whatever launcher you use.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I expected to be able to read the text in the app and expected only one window to open when launched. Instead I have an annoying pop-up and have a very difficult time reading and navigating the app.

#### Steps for reproducing this issue:

1. Launch Steam (UI issue starts here)
2. Log-in
![Steam_Tiny_UI](https://github.com/ValveSoftware/steam-for-linux/assets/106162468/e1977802-79c8-4222-be33-e4ac5630f25b)

**Comment by kzdixon** [comment]
`-forcedesktopscaling 1.5` is a new launch arg that I replaced `GDK_SCALE=2` with in my local desktop file. `GDK_SCALE` only took effect when going into Big Picture Mode and then exiting back to the Desktop client version. `-forcedesktopscaling` stays consistent at launch and when toggling Big Picture Mode for me.

**Comment by rcano** [comment]
Same here

**Comment by nekonosukeno** [comment]
That pretty much worked, the login is still a bit wonky but once logged in the library, store, settings, etc looked normal again. Set mine to 2. For posterity, you can change the launch command in your "start" menu, edit the exec= of the desktop file, and alias to the .bashrc so you never have to type it again no matter how you start Steam.

Just need the annoying chat window to go away now and we're golden. Thanks for the help on the scaling! Will update the issue.

**Comment by osem598** [comment]
can confirm kzdixon's fix works :)

**Comment by rowbawts** [comment]
Same issue not sure how to apply the argument as I use the Flatpak if this could be set as an environment variable it would be a lot easier for most people to workaround.

**Comment by osem598** [comment]
> Same issue, not sure how to apply the argument as I use the Flatpak. If this could be set as an environment variable it would be a lot easier for most people to workaround.

edit the .desktop file for steam. just put -forcedesktopscaling (number of choice) after the command for steam

**Comment by nekonosukeno** [comment]
> Same issue, not sure how to apply the argument as I use the Flatpak. If this could be set as an environment variable it would be a lot easier for most people to workaround.

Forgive me if this is incorrect since I use the deb version but try:
flatpak run com.valvesoftware.Steam -forcedesktopscaling 1.5

You should be able to pass in launch variables this method

**Comment by vizv** [comment]
Enter and then exit big picture mode helps

**Comment by nekonosukeno** [comment]
> Enter and then exit big picture mode helps

This did not work for me, however, while in big picture mode there was a manual scaling mode which I would love to see implemented in browser mode.

**Comment by tesfabpel** [comment]
Same here: Fedora 38 KDE / Wayland (AMDGPU)...
I need to test it also on my main PC (ArchLinux GNOME / Wayland (AMDGPU))... 
I will edit this comment as soon as I can.

**Comment by kisak-valve** [comment]
Hello @nekonosukeno, the main focus of this issue report is already being tracked at #9209. Feel free to add your experience to the older issue report.

Please open a separate issue report focusing on the change in Friends List behavior so that doesn't get buried.

Closing in favor of the older issue report.

**Comment by creativecoder** [comment]
Also, https://github.com/ValveSoftware/steam-for-linux/issues/9466 looks to be related (when running Gnome).
