### ISSUE TITLE
Steam client always shows window to sign in to Friends & Chat on startup

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#9599]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When Steam client starts, it always shows a window saying I'm not signed it into Friends & Chat. I don't use Friends & Chat, and "Sign in to friends when Steam Client starts" option is disabled in settings.

Steam Client should not open Friends & Chat window if it is disabled in settings.

#### Steps for reproducing this issue:

1. Have "Sign in to friends when Steam Client starts" option disabled in Settings -> Friends & Chat.
2. Start Steam client.

**Comment by kzdixon** [comment]
@Lastique does it still appear if you use the UI's "X" to close the friends panel? In my testing (and before this udpate) it would come back if closed via i3wm's `mod+shift+q` (kill window) command but stay closed if I used the UI.
The full client itself now seems to be following suit with this despite me disabling the "Close to Tray" behavior in the past, requiring me to close the client from the tray icon instead or via the dropdown menu in the client.

**Comment by nekonosukeno** [comment]
I am also having this issue. Chat pops open when I sign in and shows that I am signed out yet tells me I was last online [amount of time since I last opened Steam] ago. This would lead me to believe I am being signed into chat and then signed out on start. When "Sign in to friends when Steam Client starts" option is disabled, I shouldn't be getting signed in to chat at all on start.
![Steam_Chat](https://github.com/ValveSoftware/steam-for-linux/assets/106162468/b7af6831-515b-40ed-902e-7d3523b9846d)

**Comment by Lastique** [comment]
> @Lastique does it still appear if you use the UI's "X" to close the friends panel?

Yes. I close the window by pressing X, but every time I start Steam client the window appears again.

**Comment by snorlax212** [comment]
> I am also having this issue. Chat pops open when I sign in and shows that I am signed out yet tells me I was last online [amount of time since I last opened Steam] ago. This would lead me to believe I am being signed into chat and then signed out on start. When "Sign in to friends when Steam Client starts" option is disabled, I shouldn't be getting signed in to chat at all on start. ![Steam_Chat](https://user-images.githubusercontent.com/106162468/246157364-b7af6831-515b-40ed-902e-7d3523b9846d.png)

Had same issue after last steam update (I'm using Xubuntu 22.04.2). I did this and it solved the issue:
```
sudo apt update
sudo apt upgrade
sudo apt autoremove
```

**Comment by huliqan** [comment]
steam-settings-Friends and chat-Log in friends when launching the steam client -=-enable!!! 
reboot steam
steam-settings-Friends and chat-Log in friends when launching the steam client -=-disable
reboot steam
it's all !  the window no longer pops up when starting steam !

**Comment by Lastique** [comment]
@huliqan Thanks, that helped in my case.

**Comment by Panda-X** [comment]
I know this issue is listed under the steam client for Linux, however I would like to mention that I have the same issue with the Windows client as well.

**Comment by echotic** [comment]
Doesn't work for me on Manjaro. Enabling the setting opens the window and signs me in, disabling the setting opens the window again without signing me in.

> steam-settings-Friends and chat-Log in friends when launching the steam client -=-enable!!! reboot steam steam-settings-Friends and chat-Log in friends when launching the steam client -=-disable reboot steam it's all ! the window no longer pops up when starting steam !

**Comment by 8836290** [comment]
> steam-settings-Friends and chat-Log in friends when launching the steam client -=-enable!!! reboot steam steam-settings-Friends and chat-Log in friends when launching the steam client -=-disable reboot steam it's all ! the window no longer pops up when starting steam !

It does not work on Ubuntu 22.04.2.

**Comment by echotic** [comment]
Seems to have been fixed with 
```
Steam Version: 1687386907
Steam Client Build Date:  Wed, Jun 21 23:18 UTC -08:00
```
I no longer have the Friends & Chat window showing.

**Comment by 8836290** [comment]
Same here. It seems now Friends & Chat window respects relevant assigned settings.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
