### ISSUE TITLE
updated to  nvidia 535.54.03-2 now steam won't launch

### ISSUE THREAD

**Issue by danielboston38** [ValveSoftware/steam-for-linux#9600]
#### Your system information

* Steam client version (build number or date): can't launch to find out whatever latest is though
* Distribution (e.g. Ubuntu): arch linux
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

i tried to launch steam client today and nothing happened tried in the console and got this error SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
the only change to my system was a nvidia and linux update ive restarted multiple times. could steam not be compatible?

#### Steps for reproducing this issue:

1. try to launch steam nothing
2. launch steam in console get error
3.

**Comment by Brottweiler** [comment]
Can confirm all good now with lib32-nvidia-utils `535.54.03-1`. We were just unlucky.
