### ISSUE TITLE
Cannot uninstall Proton 7.0

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#9601]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Kubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I try to uninstall Proton 7.0 from Steam by pressing Uninstall button on its page, uninstallation fails showing error "missing shared content".

I have Proton 8.0 and GE-Proton 8-3 installed. I don't need Proton 7.0.

#### Steps for reproducing this issue:

1. In Steam Library, enable showing Tools and find and select Proton 7.0 in the list.
2. Click on Uninstall button on the Proton 7.0 page.

**Comment by kisak-valve** [comment]
Hello @Lastique, one or more games are configured to use the Proton version you're telling Steam to remove and that's causing a dependency check to fail.

This issue is already being tracked at #7407. Closing as a duplicate.
