### ISSUE TITLE
Can't save image from comunity content as a new file

### ISSUE THREAD

**Issue by koresh-krasa** [ValveSoftware/steam-for-linux#9603]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Fedora 38 Silverblue 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
From library tab if user right click on image from community content file picker is not allowing to save image as new file only to rewrite existing one

#### Steps for reproducing this issue:

1. Go to game page on library tab
2. Scroll to community content
3. Try to save image as a new file

**Comment by kisak-valve** [comment]
Hello @koresh-krasa, this issue is already being tracked at #6698. Closing as a duplicate.
