### ISSUE TITLE
steam client (and BP, too) is opaque, bright font and UI not readable

### ISSUE THREAD

**Issue by fmoerl-real** [ValveSoftware/steam-for-linux#9606]
#### Your system information

steam-runtime_0.20230509.49499
Ubuntu 22.04.2 LTS (64 Bit)
Kernel-Name: Linux
Kernel-Version: 5.19.0-43-generic
X-Server-Anbieter: The X.Org Foundation
X-Server-Release: 12101004
X-Fenstermanager: GNOME Shell

Grafikkarte:
Treiber: NVIDIA Corporation NVIDIA GeForce RTX 2080/PCIe/SSE2
Treiberversion: 4.6.0 NVIDIA 515.105.01
OpenGL-Version: 4.6
Desktopfarbtiefe: 24 Bit per Pixel
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
After the new update, the main Window of the steam client is opaque. Bright font and UI-interfaces are very hard to discriminate. 
The menus have the steam type dark color.

On the screenshot you see my background, a dark console for contrast, the opaque main window and a secondary window, actually dark colored. On a dark background as shown in screenshot 2, it works well ;o)

Please fix this nonsense, that is provide the possibility to chose a color. 

#### Steps for reproducing this issue:

1. Just start the steam client or BP
2. 
3. 
![steam_opaque](https://github.com/ValveSoftware/steam-for-linux/assets/78925587/f95564ed-1041-4ddf-83df-4b3f3ad3007e)
![steam_opaque2](https://github.com/ValveSoftware/steam-for-linux/assets/78925587/f5f0420b-32f8-4c4c-ac92-122e0e5712c3)

**Comment by kisak-valve** [comment]
Hello @fmoerl-real, this issue is already being tracked at #9422. Closing as a duplicate.
