### ISSUE TITLE
Steam doesnt start since the last update

### ISSUE THREAD

**Issue by NotPowered** [ValveSoftware/steam-for-linux#9608]
#### Your system information

* Steam client version (build number or date): lastest (updater built Jun 14 2023 20:16:17)
* Distribution debian 11 up to date
* Opted into Steam client beta?: cant
* Have you checked for system updates?: Yes

steam cant start anymore, show only screen with waiting for network, then connection to account then crash

`19:50:09 root@sandbox: /usr/games/steam root -no-cef-sandbox -clearbeta
steam.sh[37485]: Running Steam on debian 11 64-bit
steam.sh[37485]: STEAM_RUNTIME is enabled automatically
setup.sh[37551]: Steam runtime environment up-to-date!
steam.sh[37485]: Steam client's requirements are satisfied
[2023-06-15 19:50:27] Startup - updater built Jun 14 2023 20:16:17
[2023-06-15 19:50:27] Startup - Steam Client launched with: '/root/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad' 'root' '-no-cef-sandbox' '-clearbeta'
[2023-06-15 19:50:27] Beta changed from  to 
[2023-06-15 19:50:27] Checking for update on startup
[2023-06-15 19:50:27] Error: HTTP client not initialized
[2023-06-15 19:50:27] Error: Failed to determine download location for universe 1
[2023-06-15 19:50:27] Vérification de l'installation...
[2023-06-15 19:50:27] Performing checksum verification of executable files
06/15 19:50:27 Init: Installing breakpad exception handler for appid(steam)/version(1686779606)/tid(37655)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-15 19:50:27] Loading cached metrics from disk (/root/.steam/debian-installation/package/steam_client_metrics.bin)
[2023-06-15 19:50:27] Using the following download hosts for Public, Realm steamglobal
[2023-06-15 19:50:27] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-15 19:50:27] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-15 19:50:27] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
src/tier0/threadtools.cpp (3702) : Tried to create a thread that has already been created!
src/tier0/threadtools.cpp (3702) : Tried to create a thread that has already been created!
06/15 19:50:27 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(37655)
assert_20230615195027_5.dmp[37663]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230615195027_5.dmp
assert_20230615195027_5.dmp[37663]: Finished uploading minidump (out-of-process): success = yes
assert_20230615195027_5.dmp[37663]: response: CrashID=bp-2225d421-6300-49d5-a120-482fa2230615
assert_20230615195027_5.dmp[37663]: file ''/tmp/dumps/assert_20230615195027_5.dmp'', upload yes: ''CrashID=bp-2225d421-6300-49d5-a120-482fa2230615''
[2023-06-15 19:50:27] Verification complete
[2023-06-15 19:50:27] Background update loop checking for update. . .
[2023-06-15 19:50:27] Recherche de nouvelles mises à jour...
[2023-06-15 19:50:27] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=2072027382

(process:37655): GLib-GObject-CRITICAL **: g_object_ref: assertion `G_IS_OBJECT (object)' failed

(process:37655): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
Loaded SDL version 3.0.0-1735-g2e465ae31
Xlib:  extension "RANDR" missing on display ":1.0".
GetWin32Stats: display was not open yet, good
Xlib:  extension "RANDR" missing on display ":1.0".
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
GetWin32Stats: display was not open yet, good
Xlib:  extension "RANDR" missing on display ":1.0".
steamwebhelper.sh[37670]: Runtime for steamwebhelper: defaulting to /root/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[37670]: CEF sandbox already disabled
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 76: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 84: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
PulseAudio connect failed (used only for Mic Volume Control) with error: Access denied
PulseAudio context init failed
Xlib:  extension "RANDR" missing on display ":1.0".
CAppInfoCacheReadFromDiskThread took 170 milliseconds to initialize
Failed to init SteamVR because it isn't installed
[2023-06-15 19:50:29] Manifest download: send request
[2023-06-15 19:50:29] Manifest download: waiting for download to finish
Xlib:  extension "RANDR" missing on display ":1.0".
[2023-06-15 19:50:29] Manifest download: finished
[2023-06-15 19:50:29] Download skipped: /steam_client_ubuntu12?t=2072027382 version 1686779606, installed version 1686779606, existing pending version 0
[2023-06-15 19:50:29] Nothing to do
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!

(steam:37655): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
BRefreshApplicationsInLibrary 1: 0ms
roaming config store loaded successfully - 3766 bytes.
migrating temporary roaming config store

(steam:37655): GLib-GObject-CRITICAL **: g_object_ref: assertion `G_IS_OBJECT (object)' failed

(steam:37655): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
Xlib:  extension "RANDR" missing on display ":1.0".
The XFixes extension doesn't exist, disabling streaming cursor support
System startup time: 12.72 seconds
XCB_X11_TO_PID: xcb_res_query_client_ids_reply failed, falling through.
Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
19:50:40 root@sandbox: 

`

**Comment by kisak-valve** [comment]
Hello @NotPowered, `Xlib: extension "RANDR" missing on display ":1.0".` makes this the same issue as #9591. Feel free to add your findings to the older issue report.

Closing as a duplicate.
