### ISSUE TITLE
Steam stuck on Waiting for Network!

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#9609]
#### Your system information

* Steam client version (build number or date): Unable to find
* Distribution (e.g. Ubuntu):  Ubuntu 23.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Since the latest update for the User interface as of today the steam client on Ubuntu snap version is stuck on Waiting for Network and can't go to login page.

#### Steps for reproducing this issue:

1.  Launch Steam (snap version)
2.  Stuck on Waiting for Network

**Comment by lostgoat** [comment]
> Launch Steam (snap version)

Hi ShadowWarfare

snap is not a supported version of steam. Please report this bug to canonical directly, or preferably switch to a supported version of steam. E.g. install the .deb package directly from the steam website.

**Comment by sammypanda** [comment]
+1

**Comment by kha84** [comment]
I can confirm that after uninstalling steam client as snap (god damned snaps auto-update feature on Ubuntu) and reinstalling it from Valve as deb - it returned back to normal
