### ISSUE TITLE
New Steam waste 1.5gb of system ram

### ISSUE THREAD

**Issue by ryuukk** [ValveSoftware/steam-for-linux#9610]
#### Your system information

* Steam Version:  1686779606
* Steam Client Build Date:  Wed, Jun 14 10:18 PM UTC +01:00
* Steam Web Build Date:  Wed, Jun 14 11:41 PM UTC +01:00
* Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): Arch Linux x64 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam uses too much ram, i'd expect it to only just 100-200mb max, this is a game machine, it's not a machine to dedicate resource for steam's electron app, have your developers forgot what they are building? Maybe hiring problem?

I was wondering why the game kept using swap file, it's because of your hungry software!!!

#### Steps for reproducing this issue:

1. Open Steam
2. Check memory usage

![image](https://github.com/ValveSoftware/steam-for-linux/assets/44361234/0f648e8f-3c16-4988-a95c-3d1764766e88)

**Comment by kisak-valve** [comment]
Hello @ryuukk, this issue is already being tracked at #6802. Closing as a duplicate.
