### ISSUE TITLE
New UI scaling doesn't work on 4k monitors

### ISSUE THREAD

**Issue by zodiia** [ValveSoftware/steam-for-linux#9612]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): EndeavourOS / Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Since the new UI update, scaling is broken with my 4k monitor. The option to scale is enabled (yes, I restarted Steam), but it still doesn't want to work.

Screenshot of the issue:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/14910727/7745260b-e118-43c6-9035-48e641442c88)

#### Steps for reproducing this issue:

1. Have a 4k monitor
2. Enable text scaling
3. See the issue

**Comment by kisak-valve** [comment]
Hello @zodiia, this issue is already being tracked at #9209. Closing as a duplicate.
