### ISSUE TITLE
Steam refuses to launch

### ISSUE THREAD

**Issue by Crozh** [ValveSoftware/steam-for-linux#9615]
#### Your system information

* Steam client version (build number or date): Latest  
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

steam.sh[29101]: Running Steam on arch rolling 64-bit
steam.sh[29101]: STEAM_RUNTIME is enabled automatically
setup.sh[29173]: Steam runtime environment up-to-date!
steam.sh[29101]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2023-06-15 17:05:15] Startup - updater built Apr 28 2023 18:32:42
[2023-06-15 17:05:15] Startup - Steam Client launched with: '/home/me/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)/tid(29214)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

#### Steps for reproducing this issue:

1. wake up 
2. try to run steam 
3. steam says nono 
4. delete all steam dependencies and steam with all its folders except for steamapps
5. same error
6. reboot 
7. same issue

**Comment by kisak-valve** [comment]
Hello @Crozh, this was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/9600#issuecomment-1593272815. Your distro is providing you a broken combination of NVIDIA driver packages.

Closing as not a Steam client bug.
