### ISSUE TITLE
Steam not starting on 6.3.8-arch1-1

### ISSUE THREAD

**Issue by MGadhvi** [ValveSoftware/steam-for-linux#9616]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.78-1
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam UI does not open. Happened today when updating to Linux 6.3.8-arch1-1. Error from console window is as follows:

```
steam.sh[875]: Running Steam on arch rolling 64-bit
steam.sh[875]: STEAM_RUNTIME is enabled automatically
setup.sh[949]: Steam runtime environment up-to-date!
steam.sh[875]: Steam client's requirements are satisfied
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2023-06-15 21:03:24] Startup - updater built Jun 14 2023 20:16:17
[2023-06-15 21:03:24] Startup - Steam Client launched with: '/home/mgd/.local/share/Steam/ubuntu12_32/steam'
06/15 21:03:24 Init: Installing breakpad exception handler for appid(steam)/version(1686779606)/tid(1003)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
Steam has been installed with Nvidia drivers
#### Steps for reproducing this issue:

1. Update system to 6.3.8-arch1-1
2. Install Steam via Pacman with Nvidia driver support
3. Run Steam

**Comment by ndavd** [comment]
Same happens to me

**Comment by kisak-valve** [comment]
Hello @MGadhvi, this was previously evaluated at https://github.com/ValveSoftware/steam-for-linux/issues/9600#issuecomment-1593272815. Your distro is providing you a broken combination of NVIDIA driver packages.

Closing as not a Steam client bug.
