### ISSUE TITLE
Update to Steam version 1686779606 broke \ disabled content UI content scaling

### ISSUE THREAD

**Issue by Intrinsic1** [ValveSoftware/steam-for-linux#9618]
#### Your system information

* Steam client version :  1686779606
* Distribution :  Mint 21.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I’m using: Linux Mint 21.1, running the Cinnamon Desktop, at 4K, with 200% UI scaling. Upon updating to what seems like a new UI in 1686779606, the selected content scaling value from the desktop environment no longer seems to apply to Steam. I could not find UI scaling options within Steam to correct this. My setup is pretty much default Mint install, running the AMD driver that is built into the kernel (on an RX 6600 XT)

#### Steps for reproducing this issue:

I suspect that a fully updated Linux Mint install, running 4K with 200% UI scaling, using the AMD kernel driver, and Steam version 1686779606, will re-create this issue

**Comment by kisak-valve** [comment]
Hello @Intrinsic1, this issue is already being tracked at #9209. Closing as a duplicate.

**Comment by Intrinsic1** [comment]
Sorry. I didn't notice the original ticket as the Steam version number it was opened with is different
