### ISSUE TITLE
New UI update broke the steam.desktop launcher

### ISSUE THREAD

**Issue by CHFernandes** [ValveSoftware/steam-for-linux#9621]
#### Your system information

* Steam client version (build number or date): 15/06/2023 - latest
* Distribution (e.g. Ubuntu): Nobara 37
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After the steam UI update I was set on a loop with an transparent window opening and closing, like so:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/20386403/76627c70-677c-4e2b-b04e-e21cb3512c6c)

However, launching with either the `steam` command or `/usr/bin/steam %U` (the one in the .desktop file) command, it opens fine:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/20386403/0d7505fb-c467-4532-8387-92a73b7a96b5)

Then, by forcing the .desktop to open in a terminal, the looping behaviour happened again, but I could get the terminal output:

https://gist.github.com/CHFernandes/fb68335c6e388bebd1cc3cf11235191f

I also noted that each time that the transparent window appears, these messages appear on repeat:

`steamwebhelper.sh[48796]: Runtime for steamwebhelper: defaulting to /home/carlos/.local/share/Steam/ubuntu12_64/steam-runtime-heavy`
`steamwebhelper.sh[48796]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()`
`BuildCompleteAppOverviewChange: 231 apps`
 
`(steam:48292): Gtk-WARNING **: 20:03:19.674: gtk_disable_setlocale() must be called before gtk_init()`
 
`(steam:48292): Gtk-WARNING **: 20:03:19.674: gtk_disable_setlocale() must be called before gtk_init()`
 
`(steam:48292): Gtk-WARNING **: 20:03:19.674: gtk_disable_setlocale() must be called before gtk_init()`
`RegisterForAppOverview 1: 7ms`
`RegisterForAppOverview 2: 7ms`

Of my system specs here bellow: 

![image](https://github.com/ValveSoftware/steam-for-linux/assets/20386403/db8635c0-1a25-4029-9415-5dafd34d4e88)

#### Steps for reproducing this issue:

1. Start the system
2. select the steam icon in gnome menu
3. the loop begins

**Comment by kisak-valve** [comment]
Hello @CHFernandes, this issue is already being tracked at #9383. Closing as a duplicate.
