### ISSUE TITLE
New UI in game overlay menu crashes games

### ISSUE THREAD

**Issue by tomast1337** [ValveSoftware/steam-for-linux#9623]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

 [sys info](https://gist.github.com/tomast1337/04f307dbfacdbef5d4d36a07b7278c76)

#### Steps for reproducing this issue:

1. open Shift+Tab overlay or receive a notification

**Comment by amaanq** [comment]
can confirm happens on one account but not the other for me...not sure what exactly is causing it

**Comment by kisak-valve** [comment]
Hello @tomast1337, this issue is already being tracked at #9586 / #9534. Closing as a duplicate.
