### ISSUE TITLE
Steam no longer respects my global scale of 200%

### ISSUE THREAD

**Issue by daffy1234** [ValveSoftware/steam-for-linux#9624]
#### Your system information

* Steam client version (build number or date): 1686779606
* Distribution (e.g. Ubuntu): Arch, KDE Plasma desktop environment
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The GUI scaling on Steam no longer respects my global desktop scaling. I use a 4k screen with my global scale set to 200% in Plasma's Display Configuration. Steam used to scale along with the rest of my applications, but after the latest update it no longer does.

I've done these troubleshooting steps:
- Ensure every package on my system is updated
- Uninstall Steam, delete all of it's, and reinstall it
- Disable scaling and reenable it

Below is a screenshot of Steam, with a calculator on top. The calculator looks correct to me, but Steam is way too small.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/7970123/ffbe4a30-3e5f-44a6-9450-f21d2183fa71)

#### Steps for reproducing this issue:

1. Set your global scale to 200%
2. Launch Steam

**Comment by yhojann-cl** [comment]
Everyone is talking about that topic here: https://github.com/ValveSoftware/steam-for-linux/issues/9209

**Comment by 914the914** [comment]
Do you mean that if I set the global scaling to 200% (and set it back later), Steam will finally not scale up and display normally?

**Comment by kisak-valve** [comment]
Hello @daffy1234, this issue is already being tracked at #9209. Closing as a duplicate.
