### ISSUE TITLE
Game crashes when calling overlay (CS:GO)

### ISSUE THREAD

**Issue by devionW** [ValveSoftware/steam-for-linux#9626]
#### Information system

* Steam client version: [Latest version].
* Distribution: [Linux Mint].
* Have you participated in the Steam client beta? [No].
* Have you checked for system updates? [Yes].

#### Problem

Expected behavior: I expected that when I run the overlay in a CS:GO game, it would work correctly and not cause a problem.

Actual behavior: However, when I run the overlay, the game hangs and then crashes completely, preventing me from using the overlay in the game.

#### Steps to reproduce this problem:

1. Launching the CS:GO game.
2. Trying to activate overlay, (Shift+Tab)
3. After activating the overlay, the game hangs and crashes.

I would appreciate if you could provide a solution to this problem or tell me what actions I can take to fix this problem.

Thank you for your attention and for waiting for a response.

**Comment by cyph3rjo3** [comment]
This bug has already been reported and is being handled.

**Comment by kisak-valve** [comment]
Hello @devionW, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. Closing as a duplicate.
