### ISSUE TITLE
Right click menu don't work

### ISSUE THREAD

**Issue by sjukfan** [ValveSoftware/steam-for-linux#9628]
#### Your system information

* Steam client version (build number or date): a lot of stores and cafés don't accept c
* Distribution (e.g. Ubuntu): Debian Bookworm
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes (And reinstalled Steam)

#### Please describe your issue in as much detail as possible:
The drop down menu you get from right clicking on a game in the game library list shows up on right click, but don't register left click so you can't open properties and other things.

Same/similar error in the settings window were where the drop down menus opens, but don't register clicks so I can't choose client beta, change language, or other things that uses a drop down menu. 

#### Steps for reproducing this issue:

1. Install Steam on Debian Bookworm
2. Click on drop down menus
3. Click on drop down menus
4. Click on drop down menus
5. No, that's not working.

**Comment by kisak-valve** [comment]
Hello @sjukfan, this issue is already being tracked at #9273. Closing as a duplicate.
