### ISSUE TITLE
Latest Steam version disregarding scaling setting set as disabled.

### ISSUE THREAD

**Issue by Equivocal90** [ValveSoftware/steam-for-linux#9632]
#### Your system information

* Steam client version (build number or date): 6/15/23
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Issue existed both opted in or not
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have "Scale text and icons to match monitor settings" disabled. I would expect Steam to not change scaling regardless of my monitor resolution.
Steam was opening with a scaling of 2 unless opened with either the environment variable `STEAM_FORCE_DESKTOPUI_SCALING` or the argument `-forcedesktopscaling` set to `1.0`

#### Steps for reproducing this issue:

1. Run 4K desktop resolution.
2. Disable scaling in Steam settings.
3. Steam restarts with scaling still enabled.

**Comment by lundal** [comment]
I have the same issue with a 40" 4K display. `org.gnome.desktop.interface/text-scaling-factor` is set to `1.0` but Steam uses `2.0`. Toggling `Scale text and icons to match monitor settings` makes no difference. Setting `STEAM_FORCE_DESKTOPUI_SCALING=1` works.

**System info**
- Steam client version (build number or date): 1686880776
- Distribution (e.g. Ubuntu): Fedora 38
- Opted into Steam client beta?: No
- Have you checked for system updates?: Yes

**Comment by antrys** [comment]
I have the opposite problem.  Scaling is disabled no matter how the toggle is set. I want it enabled, text is tiny.
 **System Info:**
 Steam Version:  1686880776
Steam Client Build Date:  Thu, Jun 15 9:41 PM UTC -08:00
Steam Web Build Date:  Thu, Jun 15 9:10 PM UTC -08:00
Steam API Version:  SteamClient020
Operating System: Arch Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.8-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3050/PCIe/SSE2

**Comment by guymanley** [comment]
Having the same issue as Antrys. Scaling is stuck at 1.0 and tiny on a 4k monitor. Toggling the scaling feature under settings/interface doesn't affect this. Scaling stays at 1.0. 

Distro: Manjaro Linux
Kernel: 6.2.16-1-MANJARO
RAM: 16 GB
GPU Driver: 4.6 Mesa 23.0.3
GPU: AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.2.16-1-MANJARO)
CPU: Intel Core i7-4790 @ 3.60GHz

Steam Version:  1686880776
Steam Client Build Date:  Thu, Jun 15 9:41 PM UTC -08:00
Steam Web Build Date:  Thu, Jun 15 9:10 PM UTC -08:00
Steam API Version:  SteamClient020

**Comment by kisak-valve** [comment]
Hello @antrys, @guymanley, your issue is being tracked at #9209 instead of this issue report.

**Comment by hustin-paul** [comment]
Had this happen too in the recent update. UI was huge on a 4K monitor, forcing with argument brings it back to normal.

**Comment by Equivocal90** [comment]
This now works for me as expected.
