### ISSUE TITLE
Steam will not start past login screen

### ISSUE THREAD

**Issue by JoeyHellums** [ValveSoftware/steam-for-linux#9633]
#### Your system information

Kernel: 5.19.0-45-generic 
DE: Plasma 
CPU: AMD Ryzen 5 3600 (12) @ 4.099GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 

* Steam client version (build number or date):  14 jun (latest)
* Distribution (e.g. Ubuntu): Kubuntu 22.04.2 LTS x86_64 
* Opted into Steam client beta?: [Yes/No]: no
* Have you checked for system updates?: [Yes/No]: yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

steam crashes and reloads when trying to start (with the exception of the login page). steam will display an empty window and then immediately close itsself, then load another window and repeat. 

i have tried installing latest drivers for both cards, uninstalling and reinstalling steam, and even uninstalling and reinstalling xdg-desktop-portal-gnome.

running steam in the terminal only produces this:
steam.sh[46872]: Running Steam on ubuntu 22.04 64-bit
steam.sh[46872]: STEAM_RUNTIME is enabled automatically
setup.sh[46988]: Steam runtime environment up-to-date!
steam.sh[46872]: Steam client's requirements are satisfied

the latest update works on my laptop (also with kubuntu 22.04) so i'm assuming it's some system specific problem.

#### Steps for reproducing this issue:

1. start steam
2. login
3. problem

**Comment by kisak-valve** [comment]
Hello @JoeyHellums, this issue is already being tracked at #9383. You need to completely close the running instance of Steam before doing a test with running Steam from a terminal.

Closing as a duplicate.
