### ISSUE TITLE
Steam is stuck on ubunto :(

### ISSUE THREAD

**Issue by Hopefulfire** [ValveSoftware/steam-for-linux#9635]
#### 
Intel 12700kf
Radeon 560
16GB DDR4

* Steam client version : The newest version (I cant look at it hence it gets stuck in the searching for network) 
* Distribution (e.g. Ubuntu): Ubunto 22.04LTS 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Steam started acting strange after i updated to the version (UI looks fire btw) games started crashing that were "supported on ubunto" csgo for instance. It got to the point where my internet was slowed to 456kb its usually 1.2mb. I restarted my computer and started steam up again and it got stuck on the Waiting for internet screen. I did all the trouble shooting steps on my computer and nothing worked(apt update && upgrade, restarted the internet connection, restarted steam, checked my drivers.). I really liked the new update and its sad that i cant use it and as far as I can tell this would be an issue for anyone using ubunto.

#### Steps for reproducing this issue:

1. Be on ubunto
2. start steam on the latest update(not the latest beta)

**Comment by Hopefulfire** [comment]
I had to use steam -vgui to get steam to work it just wont work on the new ui

**Comment by Hopefulfire** [comment]
I no longer understand whats happening. It works now?

**Comment by mmbossoni** [comment]
In my testing, if you just start steam and let it be it will, eventually, open.
Sometimes it takes more than one minute to show the interface, but it show up.

**Comment by Hopefulfire** [comment]
I solved it. see I cleared my cache in steam it logged me out i had to log
backing using the old interface then went to the new interface it has
worked sense then.

**Comment by kisak-valve** [comment]
Closing per the last comment.
