### ISSUE TITLE
Login window is too small when scalling (2x) is enabled on new UI

### ISSUE THREAD

**Issue by zaps166** [ValveSoftware/steam-for-linux#9639]
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution: Manjaro (Xfce4)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Who's playing windows is too small when scaling is enabled on new UI. Looks like 1/4 is visible for 2x scaling (avatars removed from screenshot):
![obraz](https://github.com/ValveSoftware/steam-for-linux/assets/6239090/6ddd2a24-6bd6-4007-ab0c-e3910934428e)

#### Steps for reproducing this issue:

1. Start new Steam with scaling enabled (e.g. `steam -forcedesktopscaling 2`).
2. Go to the login screen.

**Comment by kisak-valve** [comment]
Login incorrect size windows in a new steam desktop client

Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/9642.
@baryluk posted on 2023-06-16T22:11:18:

#### Your system information

* Steam Version:  1686880776
* Steam Client Build Date:  Fri, Jun 16 1:41 AM UTC -08:00
* Steam Web Build Date:  Fri, Jun 16 1:10 AM UTC -08:00
* Steam API Version:  SteamClient020

* Distribution (e.g. Ubuntu): Debian GNU/Linux, bookworm (Debian 12)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Running Gnome Shell. Curret monitor is 3840x2160 over DP.

Fresh installation of steam, new client.

Login windows

![Screenshot from 2023-06-16 21-46-10](https://github.com/ValveSoftware/steam-for-linux/assets/110322/0d61ba88-32e7-47ad-a758-7480ba68ecc1)
![Screenshot from 2023-06-16 21-46-24](https://github.com/ValveSoftware/steam-for-linux/assets/110322/24578bc9-0019-42e5-aa20-6581af7c8522)
![Screenshot from 2023-06-16 21-46-42](https://github.com/ValveSoftware/steam-for-linux/assets/110322/a72da45c-076f-4ef4-b7cc-8978c6e8eb31)
![Screenshot from 2023-06-16 21-47-44](https://github.com/ValveSoftware/steam-for-linux/assets/110322/e74c2f42-9b8a-453e-b6c4-c8b574009523)


It is possible to navigate the very first window elements using Tab key, and press enter to accept the login.

But it is broken.
***
@zaps166 commented on 2023-06-16T22:23:58:

I think it's same as #9639

**Comment by yllekz** [comment]
Same problem, Linux Mint with a 4K display. UI is almost unusable after the update due to improper UI sizing.

**Comment by Caffeineix** [comment]
I got the same problem when Steam logged out. The login screen was painful to use because the window was too small to fit the UI.

**Comment by onetimehelper** [comment]
Since the big Steam upgrade, the login screen still looks like this on my 4K Samsung S95B OLED TV as monitor:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/134961343/d048e749-8938-4382-8ebc-0a1a91eed937)

Arch, Cinnamon 5.8.2 and
```Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 11:18 PM UTC -08:00
Steam Web Build Date:  Thu, Jun 22 12:26 AM UTC -08:00
Steam API Version:  SteamClient020
```

**Comment by kisak-valve** [comment]
Hello, it should be noted that you should be able to workaround this issue by completely closing Steam, and running Steam from a terminal with `steam -forcedesktopscaling 1` or `STEAM_FORCE_DESKTOPUI_SCALING=1 steam` (on Arch, replace `steam` with `steam-runtime`).

**Comment by kisak-valve** [comment]
Hello, per "Fix login window having the wrong dimensions when dpi scaling is enabled." in the [2023-06-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770775726198) Steam client beta update, please opt into Steam's beta client and retest.

**Comment by zaps166** [comment]
Looks ok now!

**Comment by Lancer11211** [comment]
I've enabled steam beta, removed the forced scaling parameter and nothing changed. Everything is extremely small when I don't use `STEAM_FORCE_DESKTOPUI_SCALING=2.0` but with it, windows' contents are inaccessible.

**Comment by Lancer11211** [comment]
Update: I reinstalled steam and with `STEAM_FORCE_DESKTOPUI_SCALING=2.0` the popups have the correct size now!

**Comment by yllekz** [comment]
@Lancer11211 that fix doesn't do anything for me. Also as of the latest update the problem appears to be getting even worse, as the text size is now even larger and I can't even get into the settings menu.

**Comment by onetimehelper** [comment]
After the recent update it looks fine now.
```
Steam Version:  1689034492
Steam Client Build Date:  Tue, Jul 11 1:59 AM UTC -08:00
Steam Web Build Date:  Mon, Jul 10 7:48 PM UTC -08:00
Steam API Version:  SteamClient020
```

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
