### ISSUE TITLE
steam keeps opening and closing a black screen

### ISSUE THREAD

**Issue by IMIEEET** [ValveSoftware/steam-for-linux#9641]
#### Your system information

* Steam client version (build number or date): cant see because of bug
* Distribution : fedora 38
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [download from drive](https://drive.google.com/file/d/1r51INgqfTGNU1IRtOynd7V6knHCk_3O7/view?usp=sharing)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
after updated to latest "big steam update" that released 2 days ago this happened(actually it worked before i restarting)
anyway after latest update steam keeps opening a black screen and closing, i cant see any page in steam just sometimes "friends window" that keeps opening and closing
[this](https://drive.google.com/file/d/1q5E0RwpKjsW8sZ8oiMujvDo9X1gTdzVN/view?usp=sharing) is a video of it, as you see it keeps opening a closing
also this logs of kernel while this happening:

`Jun 17 00:49:48 imieeet kernel: Composite Threa[192554]: segfault at 0 ip 0000000000000000 sp 00007f12adcdf6b8 error 14 in steamwebhelper[400000+10000] likely on CPU 3 (core 1, socket 0)

Jun 17 00:49:48 imieeet kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.

Jun 17 00:49:56 imieeet kernel: Composite Threa[194829]: segfault at 0 ip 0000000000000000 sp 00007f7bdd5ba6b8 error 14 in steamwebhelper[400000+10000] likely on CPU 0 (core 0, socket 0)

Jun 17 00:49:56 imieeet kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.

Jun 17 00:50:04 imieeet kernel: Composite Threa[197311]: segfault at 0 ip 0000000000000000 sp 00007f51c56c96b8 error 14 in steamwebhelper[400000+10000] likely on CPU 8 (core 4, socket 0)

Jun 17 00:50:04 imieeet kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.

Jun 17 00:50:14 imieeet kernel: Composite Threa[199960]: segfault at 0 ip 0000000000000000 sp 00007f99a273f6b8 error 14 in steamwebhelper[400000+10000] likely on CPU 15 (core 7, socket 0)

Jun 17 00:50:14 imieeet kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.`

some more details: fedora 38, kernel 6.3.7, mesa 23.1.2
#### Steps for reproducing this issue:

1. update to latest version
2. maybe restart 
3. steam stucks in black screen loop and not launching

**Comment by kisak-valve** [comment]
Hello @IMIEEET, if you completely close Steam, then run `steam` from a terminal, does that have an effect?

**Comment by chierighini** [comment]
Having the same problem, killing the process and opening from terminal works, but spits out `g_object_unref: assertion 'G_IS_OBJECT (object)' failed` several times when opening the app and launching games

**Comment by IMIEEET** [comment]
> Hello @IMIEEET, if you completely close Steam, then run `steam` from a terminal, does that have an effect?

yeah that works,
so launching from apps causes this to happen but if i launch it via terminal its ok
also if i right click on steam app and launch it with integrated graphic its ok too

**Comment by kisak-valve** [comment]
Thanks for checking, that makes this the same issue as #9383. Closing as a duplicate.

**Comment by knipp30** [comment]
Having this issue. Disabling GPU rendering in the steam settings fixed this for me.
