### ISSUE TITLE
Login incorrect size windows in a new steam desktop client

### ISSUE THREAD

**Issue by baryluk** [ValveSoftware/steam-for-linux#9642]
#### Your system information

* Steam Version:  1686880776
* Steam Client Build Date:  Fri, Jun 16 1:41 AM UTC -08:00
* Steam Web Build Date:  Fri, Jun 16 1:10 AM UTC -08:00
* Steam API Version:  SteamClient020

* Distribution (e.g. Ubuntu): Debian GNU/Linux, bookworm (Debian 12)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Running Gnome Shell. Curret monitor is 3840x2160 over DP.

Fresh installation of steam, new client.

Login windows

![Screenshot from 2023-06-16 21-46-10](https://github.com/ValveSoftware/steam-for-linux/assets/110322/0d61ba88-32e7-47ad-a758-7480ba68ecc1)
![Screenshot from 2023-06-16 21-46-24](https://github.com/ValveSoftware/steam-for-linux/assets/110322/24578bc9-0019-42e5-aa20-6581af7c8522)
![Screenshot from 2023-06-16 21-46-42](https://github.com/ValveSoftware/steam-for-linux/assets/110322/a72da45c-076f-4ef4-b7cc-8978c6e8eb31)
![Screenshot from 2023-06-16 21-47-44](https://github.com/ValveSoftware/steam-for-linux/assets/110322/e74c2f42-9b8a-453e-b6c4-c8b574009523)

It is possible to navigate the very first window elements using Tab key, and press enter to accept the login.

But it is broken.

**Comment by zaps166** [comment]
I think it's same as #9639

**Comment by kisak-valve** [comment]
Hello @baryluk, this is the same issue as #9639. Since this issue report adds some more details, I've transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/9639#issuecomment-1595403807.
