### ISSUE TITLE
(Almost) impossible to move windows using a title bar in new steam desktop client

### ISSUE THREAD

**Issue by baryluk** [ValveSoftware/steam-for-linux#9643]
#### Your system information

* Steam Version:  1686880776
* Steam Client Build Date:  Fri, Jun 16 1:41 AM UTC -08:00
* Steam Web Build Date:  Fri, Jun 16 1:10 AM UTC -08:00
* Steam API Version:  SteamClient020

* Distribution (e.g. Ubuntu): Debian GNU/Linux, bookworm (Debian 12)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Running Gnome Shell. Curret monitor is 3840x2160 over DP.

Fresh installation of steam, new client.

Trying to move the window using some empty area at the top, most of the time does not work.

This applies to main window, chat, settings, game properties, possibly more.

In settings and game properties, it works if you use drag using left half of the window top bar (about 50% by width).

In chat, basically impossible.

In main window, hit and miss, sometimes it works, sometimes it does not.

Very broken.

**Comment by zaps166** [comment]
Double click to maximize/restore doesn't work either.

**Comment by shadywack** [comment]
nVidia GPU on 525 drivers on Ubuntu, Gentoo w/535, Nobara w/525 or 535, Fedora 38 w/525, Arch w/535, all broken like this across the board.

I didn't have the patience to get the hit or miss results, it appears broken entirely. Cannot move windows.

**Comment by Caffeineix** [comment]
Having the exact same problem on XFCE. For me it only applies when "-forcedesktopscaling 2" is enabled, but without it the UI is incredibly tiny.

**Comment by WiseFerret** [comment]
Happens for me too on Gnome, nvidia 525 drivers, X11. The steam window grew up in size, and became immovable. No startup option is enabled, I have no Xorg scaling either (I do use the large text options from the accessibility settings), and in the interface settings the option "scale text and icons) is set to off. Resolution is 4k.

**Comment by Caffeineix** [comment]
Can confirm this is still an issue in the latest beta.

**Comment by Lastique** [comment]
On KDE, there is a workaround. KWin can be configured to have a global modifier key which you can hold and then drag any window by its contents. In my case, the modifier is the Meta key, so if I hold Meta and Left Click on the Steam client window (anywhere, not necessarily its header area), I can move it around reliably.

The modifier and its behavior can be configured in System Settings -> Window Management -> Window Behavior -> Window Actions tab.

![Screenshot_20230628_195021](https://github.com/ValveSoftware/steam-for-linux/assets/1589747/aea01ea9-9d89-4010-99d9-a7a3c956150f)

**Comment by zaps166** [comment]
I think all Linux WMs have this feature (modifier key for windows - meta or left-alt), but this doesn't work on game overlay Shift-Tab (which is also bugged...).

**Comment by lostgoat** [comment]
I forgot to add a note for it in the update notes, but a fix for this issue should be available in the latest steam beta client.

**Comment by Caffeineix** [comment]
> I forgot to add a note for it in the update notes, but a fix for this issue should be available in the latest steam beta client.

For the most part this seems to be fixed, but is for some reason still an issue in the steam overlay.

**Comment by josephrocca** [comment]
Cross-posting from #9161:

---

I just freshly installed Steam on PopOS 22.04 (basically Ubuntu 22.04), opened it up, and then noticed that I have to grip the window to the left side to be able to grab it:

https://github.com/ValveSoftware/steam-for-linux/assets/1167575/0da3b4f6-1109-4991-8c1b-6eb55a362525

I didn't resize the window or anything. Just fresh install, open it up, and then record the video. Here's another video showing that it doesn't seem to be as simple as "right side is not grippable" because there seems to be a part at the bottom of the middle/right part of the header that is grippable (I'm clicking rapidly throughout this whole video):


https://github.com/ValveSoftware/steam-for-linux/assets/1167575/469ba09d-65d5-411a-a57e-106f3732b7af

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.

**Comment by AtlasC0R3** [comment]
I seem to be having a very similar (if not identical) issue with the current Steam beta (and have been for quite a while). Clicking the buttons on the top (and bottom) of the window works just fine; unused, dead space normally used to move the window does not, and the only way I can move/resize it is with the Meta (or Windows) key and dragging with left click (on DEs that support it). This applies to any Steam window, including the main, properties and chat windows.

This is a demonstration of the described issue, with a text editor underneath the Steam window to show when clicks "fall through."
https://github.com/ValveSoftware/steam-for-linux/assets/39468657/dee07b48-076a-46f1-8e60-c8e5ee5d0556

It seems only the outer edge of the Steam UI is problematic and perhaps doesn't register as part of the app's window estate; the inside, and actual browser-esque interface, is perfectly fine and has no problems being clickable usually.

**Comment by zaps166** [comment]
On my side (Steam "stable") this issue happens on windows in Steam Overlay  (Shift+Tab).

**Comment by angulion** [comment]
Scaling in use? Xorg or Wayland? Just guessing, but would think you have x2 scaling and Steam reacts only on the WxH that an unscaled window would have.. ?
