### ISSUE TITLE
"Friends & Chat" window opens on every start

### ISSUE THREAD

**Issue by echotic** [ValveSoftware/steam-for-linux#9645]
#### Your system information

"Manjaro Linux" (64 bit)
Kernel Version: 6.1.31-2-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20230509.49499

* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

The Friends and Chat window opens on every start of the client. Disabling the setting "Sign in to friends when Steam Client starts" does not sign me in, but the window opens nonetheless. 

Expected behavior:  The Friends & Chat window doesn't open when I start the Steam Client, as was the behavior the last couple of years.

#### Steps for reproducing this issue:

1.  Open Steam Client

**Comment by kisak-valve** [comment]
Hello @echotic, this issue is already being tracked at #9599. Closing as a duplicate.
