### ISSUE TITLE
Steam Client shows blank pages after minimizing window

### ISSUE THREAD

**Issue by echotic** [ValveSoftware/steam-for-linux#9647]
#### Please describe your issue in as much detail as possible:

Minimizing the Steam Client window and then restoring or maximizing the window again leaves a blank Store, Community and Profile page. Refreshing doesn't help to restore content, the page remains blank. Also switching between Store, Community and Profile still only displays a blank page. 
All subpages are also blank, like Store > Wishlist or Store > Featured or Community > Workshop

I have to quit the Client and start it again.

The Library page is the only one unaffected by this.

#### Steps for reproducing this issue:

1. Start Steam Client
2. Minimize Steam Client
3. Restore or maximize Steam Client

#### System

    "Manjaro Linux" (64 bit)
    Kernel Version: 6.1.31-2-MANJARO
    X Server Vendor: The X.Org Foundation
    X Server Release: 12101008
    X Window Manager: KWin
    Steam Runtime Version: steam-runtime_0.20230509.49499

    Opted into Steam client beta?: No
    Have you checked for system updates?: Yes
    GPU: Nvidia

![Screenshot_20230617_010234](https://github.com/ValveSoftware/steam-for-linux/assets/10417863/f48c7465-1d92-485b-8411-7fa979a71d40)

**Comment by kisak-valve** [comment]
Hello @echotic, this issue is already being tracked at #9375. Closing as a duplicate.
