### ISSUE TITLE
Steam UI isn't working anymore after update of Nvidia driver to 535.54.03

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/steam-for-linux#9648]
#### Your system information

* Steam client version (build number or date): Latest beta as of 6/16
* Distribution (e.g. Ubuntu): Ubuntu 23.04
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia RTZ 3090
* Nvidia driver 535.54.03

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I upgraded from the Nvidia 530 driver to the 535 driver and now the UI won't open at all.

https://gist.github.com/dylanmtaylor/944ce86bea78e3489844c75078807101

#### Steps for reproducing this issue:

1. Install Nvidia driver 535.54.03
2. Install Steam
3. Attempt to open Steam

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, this issue is already being tracked at #9577 / #9634. Closing as a duplicate.
