### ISSUE TITLE
New steam UI - workshops "Browse" menu dosnt work 

### ISSUE THREAD

**Issue by blazej700** [ValveSoftware/steam-for-linux#9651]
#### Your system information

* Steam client version (build number or date): Sat, Jun 17 9:02 AM UTC -08:00
* Distribution (e.g. Ubuntu):  Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Browse menu in workshop doesn't work. Its show up but buttons inside don't react to clicks, instead anything under the menu is clicked.

#### Steps for reproducing this issue:

1. Go to any game with workshop support
2. Click "Workshop"
3. Hover over "Browse"
4. Click any item inside menu 
5. Menu disappear and any element under menu is clicked instead

**Comment by kisak-valve** [comment]
Hello @blazej700, this issue is already being tracked at #9273. Closing as a duplicate.
