### ISSUE TITLE
Steam client fails to start and loops indefinitely

### ISSUE THREAD

**Issue by allesmi** [ValveSoftware/steam-for-linux#9652]
#### Your system information

* Steam client version (build number or date): Steam Version:  1686880776
Steam Client Build Date:  Fri, Jun 16 03:41 UTC -08:00
Steam Web Build Date:  Fri, Jun 16 03:10 UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): Fedora (Fedora Linux 38 (Workstation Edition) x86_64)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, latest updates are applied
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] will provide if needed.
* GPU: AMD

#### Please describe your issue in as much detail as possible:

When I start the Steam client via Activities in Gnome Shell, the application chrashes and starts again in a loop.

#### Steps for reproducing this issue:

On Fedora 38, 

1. Start Steam by clicking on Activities -> Steam
2. wait for the loading splash screen to disappear

Expected: the steam client starts successfully, showing the client and the chat window

Actual: steam client opens as black window (no content, no story/library/etc tabs, no steam/view/friends/etc bar), the chat/friends window is visible as normal for a few seconds, then all windows close and the loading splash appears again. it is not possible to quit out of this loop.

Workaround:

I noticed that the application starts successfully when launched in a terminal. I edited the desktop entry file (`/usr/share/applications/steam.desktop`) and commented out the line `PrefersNonDefaultGPU` and then the application starts as expected:
```
# PrefersNonDefaultGPU=true
```

**Comment by kisak-valve** [comment]
Hello @allesmi, this issue is already being tracked at #9383. Closing as a duplicate.
