### ISSUE TITLE
Mislabeled duplicate bug

### ISSUE THREAD

**Issue by NolanSyKinsley** [ValveSoftware/steam-for-linux#9656]
I submitted bug report #9655 and it was immediately declared a duplicate because of a tangential issue I mentioned being reported in a different bug but COMPLETELY disregarding the MAIN ISSUE OF THE BUG REPORT which has nothing to do with the duplicate report. Yes, the drop down menu bug is a duplicate, that is why I only mentioned it in passing, THE MENUS NOT OPENING AT ALL IS A NEW AND DIFFERENT ISSUE. It is not "i can't select a drop down menu" with the old UI any more, it is ALL SETTINGS WINDOWS WILL NOT OPEN WITH THE NEW UI. IT IS A NEW ISSUE.

**Comment by kisak-valve** [comment]
Don't be an ass.
