### ISSUE TITLE
When selecting items from drop-down menus, the focus is lost.

### ISSUE THREAD

**Issue by skvili** [ValveSoftware/steam-for-linux#9657]
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu): Debian GNU/Linux 12 (bookworm)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11779570/steam-logs.tar.gz)
* GPU: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2

When selecting items from drop-down menus, the focus is lost. At first it was only in the Beta and Proton selection sections, but after the update almost all menus behave this way. Now I can't even open the properties of any game.
https://youtu.be/EQggtwO7aoM
https://youtu.be/3LOpsuQ-W9E

#### Steps for reproducing this issue:

1. Install Debian
2. Install Steam
3. Launch Steam and try to select something from the menu

**Comment by kisak-valve** [comment]
Hello @skvili, this issue is already being tracked at #9273 / #9655. Closing as a duplicate.
