### ISSUE TITLE
After UI Update Steam Client Launches Logs In No Window Pops Up

### ISSUE THREAD

**Issue by mt541bike** [ValveSoftware/steam-for-linux#9659]
#### Your system information

* Steam client version (build number or date):  1686880776
* Distribution (e.g. Ubuntu): Ubuntu 23.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* mark@MarksComputer:~$ tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs
tar: Removing leading `/' from member names
/home/mark/.steam/steam/logs/
/home/mark/.steam/steam/logs/workshop_log.txt
/home/mark/.steam/steam/logs/InstallConfigStore.corrupt.txt
/home/mark/.steam/steam/logs/steamwebhelper.log
/home/mark/.steam/steam/logs/timedtrial_log.txt
/home/mark/.steam/steam/logs/cloud_log.txt
/home/mark/.steam/steam/logs/stats_log.previous.txt
/home/mark/.steam/steam/logs/remote_connections.txt
/home/mark/.steam/steam/logs/cef_log.previous.txt
/home/mark/.steam/steam/logs/connection_log.previous.txt
/home/mark/.steam/steam/logs/connection_log_7777.txt
/home/mark/.steam/steam/logs/sitelicense_log.txt
/home/mark/.steam/steam/logs/content_log.txt
/home/mark/.steam/steam/logs/steamui_update.txt
/home/mark/.steam/steam/logs/systemaudiomanager.txt
/home/mark/.steam/steam/logs/parental_log.txt
/home/mark/.steam/steam/logs/compat_log.previous.txt
/home/mark/.steam/steam/logs/shader_log.previous.txt
/home/mark/.steam/steam/logs/appinfo_log.previous.txt
/home/mark/.steam/steam/logs/connection_log_0.txt
/home/mark/.steam/steam/logs/transport_steamui.txt
/home/mark/.steam/steam/logs/systemmanager.txt
/home/mark/.steam/steam/logs/steamui_system.txt
/home/mark/.steam/steam/logs/inventory_service_log.txt
/home/mark/.steam/steam/logs/systemmanager.previous.txt
/home/mark/.steam/steam/logs/librarysharing_log.txt
/home/mark/.steam/steam/logs/webhelper.txt
/home/mark/.steam/steam/logs/client_networkmanager.txt
/home/mark/.steam/steam/logs/bootstrap_log.txt
/home/mark/.steam/steam/logs/transport_client.txt
/home/mark/.steam/steam/logs/compat_log.txt
/home/mark/.steam/steam/logs/content_log.previous.txt
/home/mark/.steam/steam/logs/shader_log.txt
/home/mark/.steam/steam/logs/steamui_system.previous.txt
/home/mark/.steam/steam/logs/stats_log.txt
/home/mark/.steam/steam/logs/controller_ui.txt
/home/mark/.steam/steam/logs/steamui_html.txt
/home/mark/.steam/steam/logs/systemperfmanager.txt
/home/mark/.steam/steam/logs/systemdockmanager.txt
/home/mark/.steam/steam/logs/cloud_log.previous.txt
/home/mark/.steam/steam/logs/steamui_html.previous.txt
/home/mark/.steam/steam/logs/webhelper.previous.txt
/home/mark/.steam/steam/logs/cef_log.txt
/home/mark/.steam/steam/logs/connection_log.txt
/home/mark/.steam/steam/logs/systemdisplaymanager.txt
/home/mark/.steam/steam/logs/configstore_log.txt
/home/mark/.steam/steam/logs/controller.txt
/home/mark/.steam/steam/logs/configstore_log.previous.txt
/home/mark/.steam/steam/logs/connection_log_0.previous.txt
/home/mark/.steam/steam/logs/appinfo_log.txt

* GPU: AMD RX 6600

#### Please describe your issue in as much detail as possible:
Used shortcut icon from favorites tray to launch steam. Steam logs in. I can see brief login in window. Then staring at desktop. In the upper right corner I can see steam is opened. The store, library, community options do nothing when clicked. I can launch a game from the recently played games. The steam overlay won't work if launched this way.

Tried uninstalling steam and reinstalling through snap, uninstalling and reinstalling from steam website and getting the same issues.

 I can launch steam from the terminal. It shows errors. I have to leave the terminal open or it will close steam. Otherwise Steam works normally when using terminal.

#### Steps for reproducing this issue:

1. Launch steam from favorites menu shortcut

![Screenshot from 2023-06-15 08-37-49](https://github.com/ValveSoftware/steam-for-linux/assets/136874619/88cee57f-c461-4290-8c8f-09d044978c46)

![Screenshot from 2023-06-15 08-38-09](https://github.com/ValveSoftware/steam-for-linux/assets/136874619/8f0ab8ec-34c3-46b5-8bf1-2fbe15ecfc74)

What it looks like when launching from a terminal:

mark@MarksComputer:~$ steam
steam.sh[31822]: Running Steam on ubuntu 23.04 64-bit
steam.sh[31822]: STEAM_RUNTIME is enabled automatically
setup.sh[31934]: Steam runtime environment up-to-date!
steam.sh[31822]: Steam client's requirements are satisfied
[2023-06-17 21:17:17] Startup - updater built Jun 16 2023 01:41:16
[2023-06-17 21:17:17] Startup - Steam Client launched with: '/home/mark/.steam/debian-installation/ubuntu12_32/steam'
06/17 21:17:17 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(31995)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-17 21:17:17] Loading cached metrics from disk (/home/mark/.steam/debian-installation/package/steam_client_metrics.bin)
[2023-06-17 21:17:17] Using the following download hosts for Public, Realm steamglobal
[2023-06-17 21:17:17] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-17 21:17:17] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-17 21:17:17] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-17 21:17:17] Checking for update on startup
[2023-06-17 21:17:17] Checking for available updates...
[2023-06-17 21:17:17] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-06-17 21:17:17] Manifest download: send request
[2023-06-17 21:17:17] Manifest download: waiting for download to finish
[2023-06-17 21:17:17] Manifest download: finished
[2023-06-17 21:17:17] Download skipped: /steam_client_ubuntu12 version 1686880776, installed version 1686880776, existing pending version 0
[2023-06-17 21:17:17] Nothing to do
[2023-06-17 21:17:17] Verifying installation...
[2023-06-17 21:17:17] Performing checksum verification of executable files
[2023-06-17 21:17:18] Verification complete

(process:31995): GLib-GObject-CRITICAL **: 21:17:18.291: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:31995): GLib-GObject-CRITICAL **: 21:17:18.291: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xea504370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xea502cc0
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1735-g2e465ae31
Gtk-Message: 21:17:18.341: Failed to load module "gail"
Gtk-Message: 21:17:18.341: Failed to load module "atk-bridge"

(steam:31995): Gtk-WARNING **: 21:17:18.342: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'

(steam:31995): Gtk-WARNING **: 21:17:18.343: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Yaru-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
steamwebhelper.sh[32034]: Runtime for steamwebhelper: defaulting to /home/mark/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[32034]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
CAppInfoCacheReadFromDiskThread took 64 milliseconds to initialize
Failed to init SteamVR because it isn't installed

(steam:31995): Gtk-WARNING **: 21:17:18.785: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 2124 bytes.
BRefreshApplicationsInLibrary 1: 1ms
roaming config store loaded successfully - 2124 bytes.
migrating temporary roaming config store

(steam:31995): GLib-GObject-CRITICAL **: 21:17:20.082: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:31995): GLib-GObject-CRITICAL **: 21:17:20.082: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
System startup time: 1.86 seconds
BuildCompleteAppOverviewChange: 775 apps
RegisterForAppOverview 1: 14ms
RegisterForAppOverview 2: 14ms
ExecCommandLine: "'/home/mark/.steam/debian-installation/ubuntu12_32/steam'"

(steam:31995): GLib-GObject-CRITICAL **: 21:17:21.640: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:31995): GLib-GObject-CRITICAL **: 21:17:21.640: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2023-06-17 21:19:18] Background update loop checking for update. . .
[2023-06-17 21:19:18] Checking for available updates...
[2023-06-17 21:19:18] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=300648246
[2023-06-17 21:19:18] Manifest download: send request
[2023-06-17 21:19:18] Manifest download: waiting for download to finish
[2023-06-17 21:19:19] Manifest download: finished
[2023-06-17 21:19:19] Download skipped by HTTP 304 Not Modified
[2023-06-17 21:19:19] Nothing to do

**Comment by kisak-valve** [comment]
Hello @mt541bike, since Steam works as expected when run from a terminal, that makes this the same issue as #9383. Closing as a duplicate.
