### ISSUE TITLE
Web renderer fails to render after being minimized

### ISSUE THREAD

**Issue by Spartan322** [ValveSoftware/steam-for-linux#9661]
#### Your system information

* Steam client version (build number or date): 1687015240
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11780999/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I expect that when I'm doing anything in the Steam web interface, like the store or workshop, that I can minimize the window and then maximize it again and resume what I was doing.

What happens is that if I'm in anything that seems to call the CEF, (least I assume that's the case) like the store or workshop, if I minimize the window and try to resume, it produces a black screen as if its loading but it never renders anything. This doesn't happen in places like my library or downloads. I can often resume what I was doing if I go to my library and then press the back button on the Steam client.

#### Steps for reproducing this issue:

1. Start Steam
2. Go to store
3. Minimize the Steam window
4. Reopen the Steam window
5. Notice the black screen

**Comment by kisak-valve** [comment]
Hello @Spartan322, this issue is already being tracked at #9375. Closing as a duplicate.
