### ISSUE TITLE
[New Steam UI] The steam app is transparent

### ISSUE THREAD

**Issue by CzarnyCwel** [ValveSoftware/steam-for-linux#9668]
#### Your system information

* Steam client version: 1686880776 (Steam API: SteamClient020)
* Distribution : Pop!_OS 22.04 LTS (Ubuntu-based ) (KERNEL: 6.2.6-76060206-generic)
* Opted into Steam client beta?: YES
* Have you checked for system updates?: YES
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11782052/steam-logs.tar.gz)

* GPU: NVIDIA GeForce RTX 2060 (GPU DRIVER: NVIDIA 525.105.17)

#### Please describe your issue in as much detail as possible:
My entire steam app is Transparent on desktop and when I'm in game using Shift+Tab
https://github.com/ValveSoftware/steam-for-linux/assets/31630440/7b598af2-c1c7-491b-bb07-6e86dbca66e2

**Chat or friends list works fine**
![Zrzut ekranu z 2023-06-18 18-20-37](https://github.com/ValveSoftware/steam-for-linux/assets/31630440/ae46135d-1e08-4181-bb18-424a247ed3fb)

List of my extensions:
![Zrzut ekranu z 2023-06-18 18-16-05](https://github.com/ValveSoftware/steam-for-linux/assets/31630440/288536fd-f8d8-4bf8-8b47-e49e4aa9738e)
**I tried disabling and deleting the "Blur my shell" extension but nothing changed (Yes I restarted the computer)**

#### Steps for reproducing this issue:

1. The problem started after updating to the new Steam UI

**Comment by kisak-valve** [comment]
Hello @CzarnyCwel, this issue is already being tracked at #9422. Closing as a duplicate.
