### ISSUE TITLE
All native OpenGL based Linux Games crash instant, if ingame overlay is opened

### ISSUE THREAD

**Issue by PadTrick** [ValveSoftware/steam-for-linux#9670]
#### Your system information

* Steam client version (build number or date): 15.06.2023
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia 1070 Ti

#### Please describe your issue in as much detail as possible:
All native OpenGL based Linux Games crash instant, if ingame overlay is opened.
CSGO crashes as soon as opened, if ingame overlay is activated.
Also CSGO cant be run with Proton, error msg says Steam Client to old.

#### Steps for reproducing this issue:

1. Play any OpenGL native Linux Game
2. Open Ingame overlay

**Comment by kisak-valve** [comment]
Hello @PadTrick, this issue is already being tracked at #9586 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3172.

Closing as a duplicate.

**Comment by PadTrick** [comment]
> Hello @PadTrick, this issue is already being tracked at #9586 / [ValveSoftware/csgo-osx-linux#3172](https://github.com/ValveSoftware/csgo-osx-linux/issues/3172).
> 
> Closing as a duplicate.

Then why i dont see it here?
maybe move the topic to the steam-linux and not a game specific topic, if all games are affected by this

**Comment by kisak-valve** [comment]
First linked issue is not game specific and on this issue tracker, second is the CS:GO-specific variant for visibility on that issue tracker. There's nothing to be gained from transferring the latter issue report.

**Comment by PadTrick** [comment]
ah ok, totally overlooked the issue, my bad. sorry
