### ISSUE TITLE
Oversized UI elements on 4K 43" display

### ISSUE THREAD

**Issue by azonenberg** [ValveSoftware/steam-for-linux#9671]
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: (attached)
* GPU: Nvidia RTX 2080 Ti

#### Please describe your issue in as much detail as possible:

With the latest Steam client update on a 43" 4K monitor (107 DPI), all UI elements are enormous, at least 2x normal expected font size. Seems like a scaling bug. Toggling the scaling switch under settings doesn't seem to change anything.

Note that this is a 4K display but *not* a hi-DPI system since it's very close to the nominal 96 DPI. Attached screenshot of Steam client with another window behind it showing the expected resolution and font sizes.

![huge-client](https://github.com/ValveSoftware/steam-for-linux/assets/998036/ed3f8c56-de26-444c-ba0f-37a86b1ecee6)

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11782525/steam-logs.tar.gz)

#### Steps for reproducing this issue:

1. Install latest steam update
2. Observe all UI elements are oversized

**Comment by kisak-valve** [comment]
Hello @azonenberg, this issue is already being tracked at #9632 / #5362. Until those issues are resolved, you should be able to run Steam with `STEAM_FORCE_DESKTOPUI_SCALING=1 steam` or `steam -forcedesktopscaling 1`

Closing as a duplicate.
