### ISSUE TITLE
New overlay crash cs:go. if you runing it without -vulkan

### ISSUE THREAD

**Issue by programkeyj** [ValveSoftware/steam-for-linux#9673]
#### system information

* Steam client version: 1687015240
* Distribution : Ubuntu 20.04.6 LTS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11786293/steam-logs.tar.gz)
* GPU: Nvdia RTX3080 4gb

#### Issue details:
After that big update with updated Steam overlay etc. In csgo when i call overlay game just shutdown without asking. And this problem only in csgo.
I wrote to csgo steam support and they told me to create an issue here.
The problem was solved halfway while I was writing this, one person on the forum advised to run with -vulkan .and then it worked.
But with vulkan i have freezes every time i shoot but fps is stable 240-260
But why doesn't it work out of the box?

#### Steps for reproducing this issue:

1. Run csgo
2. Shift+tab(or how you call Steam overlay)

**Comment by kisak-valve** [comment]
Hello @programkeyj, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. Closing as a duplicate.
