### ISSUE TITLE
New UI: scaling is not applied at startup.

### ISSUE THREAD

**Issue by pshirshov** [ValveSoftware/steam-for-linux#9674]
I'm using Plasma Wayland on 4K display with 150% scaling.

New UI does not apply scaling after startup even though I have "Scale text and icons to match monitor settings" checkbox set.

Though if I enter Big Picture Mode then exit it the UI gets scaled properly.

**Comment by kisak-valve** [comment]
Hello @pshirshov, this issue is already being tracked at #9209, and somewhat with #9565. Closing as a duplicate.

**Comment by pshirshov** [comment]
@kisak-valve : may I ask you to do something about https://github.com/ValveSoftware/Dota-2/issues/2367 ?

The game is literally unplayable and noone cares :((((
