### ISSUE TITLE
Pop-up menu items cannot be selected.

### ISSUE THREAD

**Issue by ChibaPet** [ValveSoftware/steam-for-linux#9678]
#### Your system information

* Steam client version (build number or date): Steam Version:  1686880776
* Distribution (e.g. Ubuntu): Debian 11
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: will provide excerpts as needed, but full logs expose internal IPs.
* GPU: nVidia GTX 1660s

#### Please describe your issue in as much detail as possible:

I can't select menu items from pop-up menus in the Steam client. For example, I can go to Steam -> Settings -> Interface, but I can't from there select "Library" for my start-up location. I can click the pop-up menu and see the choices, and when I move my cursor over different menu items they highlight and dehighlight as expected, but when I click on one of them the menu disappears, but the new selection hasn't been chosen. Prior to the recent client update I only noticed this with Proton version selection, but now that the client has updated, it seems to have lost my preference to start in my library, and I can't get back to that. I can't state with certainty that this wasn't an issue before the update.

In the attached images, I can dismiss the menu by moving my mouse to an item, seeing it highlight, and clicking, but the item  does not then show in the screen.

#### Steps for reproducing this issue:

1. Click a pop-up menu.
2. Hover over an item, see it selected, and click to choose it.
3. See that the item was not chosen.

Steps two and three are shown in the before-and-after screenshots, attached. (That said, Github is showing an error on my trying to attach them, so I'll open this and then try attaching again.)

**Comment by ChibaPet** [comment]
Dunno, Github is throwing an error, so I'll link the files from here and try again with a direct attach later.

Github upload error: https://0x0.st/HTWQ.png

Before image: https://0x0.st/HTWu.png
After image: https://0x0.st/HTWS.png

**Comment by ChibaPet** [comment]
Ended up being some change in the sites Github's using to process image uploads. Allowed them via uBlock Origin and I could upload, so here they are directly.

![steam-menu-issue-before](https://github.com/ValveSoftware/steam-for-linux/assets/21206136/da40a34a-b841-4fcd-aedc-5c79f707d7fc)
![steam-menu-issue-after](https://github.com/ValveSoftware/steam-for-linux/assets/21206136/faf0620a-8e91-4575-a529-515d3b70554d)

**Comment by kisak-valve** [comment]
Hello @ChibaPet, this issue is already being tracked at #9273. Closing as a duplicate.
