### ISSUE TITLE
New Steam overlay + dxvk causes startup freeze in some games.

### ISSUE THREAD

**Issue by Blisto91** [ValveSoftware/steam-for-linux#9685]
#### Your system information

* Steam client version (build number or date): 1686880776
* Distribution (e.g. Ubuntu):  Reborn OS (Arch based)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809119/steam-logs.tar.gz)
* GPU: AMD 7900xtx and a Zen 4 iGPU

#### Please describe your issue in as much detail as possible:
Ever since the new Steam UI update i've had issues with a few games freezing during startup the Steam overlay is enabled together with dxvk. Using wined3d with Steam overlay does does not cause the issue and turning off overlay together with using dxvk does not cause it either. At least i haven't been able to reproduce it then.
Back when the new UI was in beta going back to the old one did not reproduce the issue either.

So far i have observed it with 3 games. [Watch Dogs](https://store.steampowered.com/app/243470/Watch_Dogs/), [Tom Clancy's Rainbow Six Lockdown](https://store.steampowered.com/app/15000/Tom_Clancys_Rainbow_Six_Lockdown/) and [Melty Blood Actress Again Current Code](https://store.steampowered.com/app/411370/Melty_Blood_Actress_Again_Current_Code/).
It seems to be racy as with Rainbow Six i have managed to get to the main menu like 1 in 10 times and with Melty Blood i was not able to reproduce the issue with amdvlk until i also had proton logging turned on. With radv it happened all the time.

Proton log and Steam terminal output from Watch Dogs
[watch-dogs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809256/watch-dogs.tar.gz)

Same from Melty Blood
[melty-blood.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11809263/melty-blood.tar.gz)

#### Steps for reproducing this issue:
Watch Dogs is the most consistent one for me, so describing that one.

1. Start the game with Proton with both dxvk and steam overlay enabled ( specific proton version is not important )
2. Game freezes before i even get to the main menu

**Comment by kisak-valve** [comment]
Hello @Blisto91, this issue is already being tracked at #9586. Since this issue report adds some more details, I've gone ahead and transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/9586#issuecomment-1599766031.

Closing as a duplicate.

**Comment by Blisto91** [comment]
I never actually open the overlay tho. Just have it turned on
