### ISSUE TITLE
Steam crashes on Arch after fresh install

### ISSUE THREAD

**Issue by snakebite-382** [ValveSoftware/steam-for-linux#9686]
# Prerequisites 

Version: Can't check because Steam is non-functional, but it last updated on 6/18/2023
OS: Manjaro (arch fork)
Steam Beta: No
System updates: Yes, and drivers too
Logs:
Terminal when running "steam" is attached: https://gist.github.com/snakebite-382/f92bf4176c92854ae849bfeee3f0404f
Can't run the suggested command to unzip logs.

GPU: AMD (Radeon 6600)

# The problem
Tried to run Steam one day and it just would not open (about a week ago)

Already tried:
Restarting,
running `steam --reset`
Delete all traces of steam (including all trace files and dependencies by running `pacman -Rsn steam-native-runtime steam` and deleting the /local/share/Steam and ~/.steam folders, along with game folders) and reinstalling with `pacman -Syu steam`
updating GPU and vulkan drivers (open source linux drivers for both)

# Reproducing
Not sure if this is an arch issue or a me issue so no idea how to reproduce

**Comment by kisak-valve** [comment]
Hello @snakebite-382, please give #9588 a read and check if you're seeing the same issue.

**Comment by snakebite-382** [comment]
Thank you for that. For those wondering the solution was to uninstall `xdg-desktop-portal` `xdg-desktop-portal-gnome` and `xdg-desktop-portal-gtk` and everything works again

**Comment by kisak-valve** [comment]
Thanks for checking, closing as a duplicate.
