### ISSUE TITLE
SteamOS Storage menu - Korean translation typo 

### ISSUE THREAD

**Issue by withteas** [ValveSoftware/steam-for-linux#9690]
#### Your system information

* Steam client version:1687306661
* SteamOS version: 3.4.8
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

1. SteamDeck > Home > Settings > Storage
    - English
      - **Internal Drive** 
    - Korean
      - 내부 **브**라이브 (X) -> 내부 **드**라이브(O)

There is a typo that makes me laugh every time.   
Please fix it.
Thanks.

**Comment by kisak-valve** [comment]
Hello @withteas, this is an issue with the Steam client instead of SteamOS as a platform, so I've transferred this issue to the steam-for-linux issue tracker.

**Comment by withteas** [comment]
- Steam client client version: 1688685284

Today I updated my steamdeck, it was fixed.
Thanks.
