### ISSUE TITLE
After steam update it does not launch properly

### ISSUE THREAD

**Issue by ZMensRain** [ValveSoftware/steam-for-linux#9693]
#### Your system information

* Steam client version (build number or date): Steam Version:  1686880776
* Distribution: Pop!_OS 22.04 LTS
* Opted into Steam client beta?:  No
* Have you checked for system updates?: [Yes/No] 
* Steam Logs: attached 
* GPU: AMD® Radeon graphics / AMD® Radeon rx 480 graphics
AMD® Ryzen 5 pro 4650g with radeon graphics × 12
Ram: 24.0 GiB
Gnome 42.5

#### The problem.
I wanted to play some games on steam but then steam wanted to update so it did and launched fine. However after a restart of steam it opened and got to the waiting for network screen then it closed to the tray. Now when I open it is does the same thing, opens then closes to the tray but I can still launch Blender and Godot from the tray indicator and open the settings window I then tried to open it from the terminal with flatpak run com.valvesoftware.Steam and it opens but i get this warning message:
 Gtk-Message: 19:21:44.232: Failed to load module "gail"
Gtk-Message: 19:21:44.232: Failed to load module "atk-bridge"
Gtk-Message: 19:21:44.232: Failed to load module "appmenu-gtk-module"
and 
(steam:152): Gtk-WARNING **: 19:21:54.939: gtk_disable_setlocale() must be called before gtk_init()

#### Steps for reproducing this issue:

1.  install steam fresh on Pop os with  flatpak install com.valvesoftware.Steam
2. shut down steam and maybe restart your computer
3. try and open steam again
4. have it not open a window and be only visible in the tray

**Comment by NaterEST** [comment]
current only work around is removing these 2 lines on steam.desktop (location: /usr/share/applications):

> PrefersNonDefaultGPU
> X-KDE-RunOnDiscreteGpu

**Comment by NaterEST** [comment]
running steam through terminal also worked for me, using Nobara Linux

**Comment by ZMensRain** [comment]
@NaterEST I am using a flatpak install so I had to go to  **/.local/share/flatpak/app/com.valvesoftware.Steam/** and there are multiple copies of the file so i just changed them all. now it seems to work better but when shutting down it does not show the shutting down pop up. Still not had to use the work around

**Comment by NaterEST** [comment]
I'm using flatpak as well

**Comment by NaterEST** [comment]
well steam came pre-installed on nobara, but it is a flatpak for me

**Comment by NaterEST** [comment]
> now it seems to work better but when shutting down it does not show the shutting down pop up. Still not had to use the work around
interesting, haven't seen that yet.

**Comment by Alexander-Wilms** [comment]
Since today, I can't launch it either, it gets stuck after trying to log in. I tried the openSUSE as well as the Flatpak package with the same result.

[steam-opensuse-package.log](https://github.com/ValveSoftware/steam-for-linux/files/11860012/steam-opensuse-package.log)
[steam-flatpak.log](https://github.com/ValveSoftware/steam-for-linux/files/11860001/steam-flatpak.log)
![Screenshot_20230625_162747](https://github.com/ValveSoftware/steam-for-linux/assets/3226457/05874747-30cb-4bff-a228-c6711900fd61)
![Screenshot_20230625_163047](https://github.com/ValveSoftware/steam-for-linux/assets/3226457/48185ba8-074a-4499-8433-f2912d4aaec9)
![Screenshot_20230625_160038](https://github.com/ValveSoftware/steam-for-linux/assets/3226457/b3ed6afa-5857-4e92-bf93-08804b4e47f0)

```
Operating System: openSUSE Tumbleweed 20230623
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.7-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15,6 GiB of RAM
Graphics Processor: llvmpipe
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B250M-DS3H
```

**Comment by NaterEST** [comment]
> Since today, I can't launch it either, it gets stuck after trying to log in. I tried the openSUSE as well as the Flatpak package with the same result. Commenting out
> 
> ```
> #PrefersNonDefaultGPU=true
> #X-KDE-RunOnDiscreteGpu=true
> ```
> 
> resulted in Steam showing the news window and the chat window once, but now it's stuck at the login window again.
> 
> ![image](https://user-images.githubusercontent.com/3226457/248569467-68587d99-0fc7-450b-acc4-1176e59ca29b.png)
> 
> The GUI being invisible except for the dropdown menus is similar to #9722
> 
> `steam --reset` doesn't fix the issue either.
> 
> [steam-opensuse-package.log](https://github.com/ValveSoftware/steam-for-linux/files/11860012/steam-opensuse-package.log) [steam-flatpak.log](https://github.com/ValveSoftware/steam-for-linux/files/11860001/steam-flatpak.log) ![Screenshot_20230625_162747](https://user-images.githubusercontent.com/3226457/248564445-05874747-30cb-4bff-a228-c6711900fd61.png) ![Screenshot_20230625_163047](https://user-images.githubusercontent.com/3226457/248564441-48185ba8-074a-4499-8433-f2912d4aaec9.png) ![Screenshot_20230625_160038](https://user-images.githubusercontent.com/3226457/248564440-b3ed6afa-5857-4e92-bf93-08804b4e47f0.png)
> 
> ```
> Operating System: openSUSE Tumbleweed 20230623
> KDE Plasma Version: 5.27.6
> KDE Frameworks Version: 5.107.0
> Qt Version: 5.15.10
> Kernel Version: 6.3.7-1-default (64-bit)
> Graphics Platform: X11
> Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
> Memory: 15,6 GiB of RAM
> Graphics Processor: llvmpipe
> Manufacturer: Gigabyte Technology Co., Ltd.
> Product Name: B250M-DS3H
> ```

try launching steam through the terminal and comme the results that could say something.

**Comment by Alexander-Wilms** [comment]
I attached the logs in the original comment:

> [steam-opensuse-package.log](https://github.com/ValveSoftware/steam-for-linux/files/11860012/steam-opensuse-package.log)
[steam-flatpak.log](https://github.com/ValveSoftware/steam-for-linux/files/11860001/steam-flatpak.log)

**Comment by NaterEST** [comment]
right, didn't notice, will check if I can find anything when I get home

**Comment by Alexander-Wilms** [comment]
Thanks!

Here's a log of the output of `steam --reset`:

[steam-reset.log](https://github.com/ValveSoftware/steam-for-linux/files/11860583/steam-reset.log)

**Comment by NaterEST** [comment]
to be conpletely honest, I can't see any really specific "new" lines in the log you just sent now, but will check the others later

**Comment by kisak-valve** [comment]
Hello @Alexander-Wilms, looking at your system information, it looks like you have an AMD RX 480, but something's globally broken that prevents you from using your video card at all. Steam is being forced to fallback to llvmpipe to render anything at all.

**Comment by NaterEST** [comment]
now that I checked, noticed as well

**Comment by NaterEST** [comment]
corrupted drivers maybe?

**Comment by Alexander-Wilms** [comment]
I think I had enabled hardware accelerated web content in the Steam settings some days ago. And yes, it looks like an openSUSE update broke the AMD graphics driver. I'll try to fix that first and report back.

**Comment by NaterEST** [comment]
nice, updated and fixed drivers should fix at least one of your issues, if not all

**Comment by Alexander-Wilms** [comment]
Thanks for the hint, now the openSUSE Steam package works fine again, including the Friends window and hardware accelerated rendering:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/3226457/0c6b653b-235a-4a58-93c4-96442cd03802)

I did the following:

```
sudo zypper dup
sudo zypper update -y
```

Then I removed the Packman repo (http://ftp.gwdg.de/pub/linux/packman/suse/openSUSE_Tumbleweed/)

```
sudo zypper dup
[...]
Die folgenden 13 Pakete werden den Anbieter ändern:
  libOSMesa8               http://packman.links2linux.de -> openSUSE
  libOSMesa-devel          http://packman.links2linux.de -> openSUSE
  Mesa                     http://packman.links2linux.de -> openSUSE
  Mesa-dri                 http://packman.links2linux.de -> openSUSE
  Mesa-dri-devel           http://packman.links2linux.de -> openSUSE
  Mesa-gallium             http://packman.links2linux.de -> openSUSE
  Mesa-KHR-devel           http://packman.links2linux.de -> openSUSE
  Mesa-libEGL1             http://packman.links2linux.de -> openSUSE
  Mesa-libEGL-devel        http://packman.links2linux.de -> openSUSE
  Mesa-libGL1              http://packman.links2linux.de -> openSUSE
  Mesa-libGL-devel         http://packman.links2linux.de -> openSUSE
  Mesa-libGLESv1_CM-devel  http://packman.links2linux.de -> openSUSE
  Mesa-libGLESv2-devel     http://packman.links2linux.de -> openSUSE
```

And then I did a final
```
sudo zypper dist-upgrade
```

**Comment by NaterEST** [comment]
good that it's fixed, I am still having some unrelated to this topic issues. One of them is custom proton versions like Proton GE just not working at all

**Comment by sfxworks** [comment]
> The GUI being invisible except for the dropdown menus is similar to #9722

I just see white now
