### ISSUE TITLE
Game update | notification UI is impossible to use.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#9696]
#### Your system information

* Steam client version: Love how you can't copy this from the about... Jun 16 2023
* Distribution (e.g. Ubuntu): Garuda Arch
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11834088/steam-logs.tar.gz)

* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

If Steam is online it floods my UI with garbage game updates which are nearly impossible to get rid of. There is a tiny drop down arrow in the top right of each "update" notice for remove and show less but most times clicking it just opens the update. Some times you can click on it and hover the Remove option only for clicking on that to also just open the update. Why can't we disable this garbage all together. I don't want to show less I want to show NONE much less fight with this garbage small UI that never works.

#### Steps for reproducing this issue:

1. Open Steam online when there are "update notices" to games you own.
2. See stupid updates you don't care about
3. Try to dismiss/remove the updates via the UI provided...
4. Note how the UI behaves like a mobile advertisement meme where the X is less than a pixel in side making it impossible to click and anything you do just makes the issue worse.
5. Get rid of this garbage notification area PERIOD!

**Comment by kisak-valve** [comment]
Hello @nPHYN1T3, as far as I can tell, you've described the "What's New" shelf on the Library view of the Steam client. This issue is already being tracked at #8061. Closing as a duplicate.

**Comment by nPHYN1T3** [comment]
I read that post and it's not the same problem. While I touch on that i.e. I want this garbage GONE I know it's a pipe dream and Steam will persist badgering customers. The issue I'm reporting is the fact items on that What's New UI can NOT be interacted with correctly. The Drop Down to remove or "show less" does not work.
