### ISSUE TITLE
no more tray icon since latest Steam client update

### ISSUE THREAD

**Issue by sysms** [ValveSoftware/steam-for-linux#9701]
#### Your system information

* Steam client version (build number or date): 
![steam_210623](https://github.com/ValveSoftware/steam-for-linux/assets/4120422/99365f31-a0af-4398-80b7-bcaf1b0bf06d)

* Distribution (e.g. Ubuntu): Debian 12
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11837324/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:

Since the latest Steam stable client, there is no longer a tray icon displayed on Debian 12 and LXDE and XFCE.

This is very bad, since with one of the latest updates (presumably the 14.06.23) ALT-F4 started  to minimize Steam into the tray (and not longer closing it).

So if I accidentally press ALT-F4 (since it's still in my muscle memory) to close steam, I now have to kill it from the command line ("killall steam") to exit it, and can no longer close/exit it from the tray icon.

#### Steps for reproducing this issue:

1. Open latest stable Steam client on Debian 12
2. observe no tray icon on LXDE or XFCE

**Comment by kisak-valve** [comment]
Hello @sysms, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by sysms** [comment]
@kisak-valve after completely rebooting my computer, the tray icon is now back again (just tried in LXDE). :/ 

I'm not sure, what has caused this phenomenon.

FWIW here is the link to the Steam Runtime Diagostics: https://gist.github.com/sysms/bc6a83a1adac180a4c4b5262552d1f00

**Comment by sysms** [comment]
Ok, so it just works only on the first start of Steam it seem.

After closing and reopening the Steam client, the tray icon is gone for good again.

**Comment by sysms** [comment]
I could narrow it down - it's not a Steam problem, as it seems.

If I stay in LXDE, the tray icon is available continuously, even after closing and restarting Steam.
If I switch once to a XFCE session, the tray icon is gone (in XFCE and also in LXDE after switching back to LXDE).

So I guess it's both DEs interfering somehow.
