### ISSUE TITLE
CS:GO crashes when trying to open steam overlay

### ISSUE THREAD

**Issue by j-lohuis** [ValveSoftware/steam-for-linux#9702]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 11:18 PM UTC -08:00
Steam Web Build Date:  Thu, Jun 22 12:26 AM UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): 
Manjaro Linux (Linux desktop 6.1.31-2-MANJARO SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux)
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11839441/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD
AMD Radeon RX 6900 XT

#### Please describe your issue in as much detail as possible:

CS:GO crashes when trying to open the steam overlay.

I have only tested a few other games, namely Terraria and Stardew Valley, where the overlay opens as expected.

I have uploaded a core dump file, which you can download [here](https://drive.google.com/file/d/1RvtMZSu095PhnDzxmtbY7Y5oxfnmQ9qL/view?usp=drive_link) since it is quite large (399M zipped, 3.4G unzipped).

In case you don't want to (which is understandable) here's the back trace gdb spat out:
```
Thread 1 "csgo_linux64" received signal SIGBUS, Bus error.
0x00007f722fc2c772 in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
(gdb) bt
#0 0x00007f722fc2c772 in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#1 0x00007f722fc1edd5 in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#2 0x00007f722fc28994 in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#3 0x00007f722fc29152 in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#4 0x00007f722fc2aa6b in ?? () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#5 0x00007f722fc1b115 in glXSwapBuffers () from /home/julo/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
#6 0x00007f722c4ea803 in ?? () from /home/julo/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libSDL2-2.0.so.0
#7 0x00007f722d83fbb3 in ?? ()
#8 0x00007ffe64c64e40 in ?? ()
#9 0x00007f722cac1ac0 in __bss_start () from /home/julo/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtogl_client.so
#10 0x000000000a66e990 in ?? ()
#11 0x00007f722cac1ac8 in __bss_start () from /home/julo/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/libtogl_client.so
#12 0x00007ffe64c64e40 in ?? ()
#13 0x0000000009dde000 in ?? ()
#14 0x00007ffe64c64e90 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

#### Steps for reproducing this issue:

1. Launch CS:GO via Steam
2. Open the overlay
3. CS:GO closes after 2-3 seconds of being unresponsive.

**Comment by kisak-valve** [comment]
Hello @j-lohuis, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172 / #9586. Closing as a duplicate.
