### ISSUE TITLE
Parts of UI intermittently render or become transparent

### ISSUE THREAD

**Issue by pwalsh0** [ValveSoftware/steam-for-linux#9703]
#### Your system information

* Steam client version (build number or date):  flatpak com.valvesoftware.Steam 1.0.0.75, Steam Version:  1687386907
* Distribution (e.g. Ubuntu): PopOS 22
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Please see screenshots. Many of the ui elements become transparent and don't render properly. This can be seen intermittently if you resize the main steam window and move mouse around or scroll. Luckily restarting steam fixes it until the window gets resized again.

#### Steps for reproducing this issue:
Note I have the 4k scaling fix applied via modified flatpak settings, otherwise the UI would be tiny. In the past this was via GDK_SCALE but as per other issue thread am now using option "-forcedesktopscaling 2". 
When steam starts up ok maximised everything is fine. But if you switch programs or resize steam then this strange transparency stuff happens.
 
Screenshot 1: UI is rendering ok here
![image](https://github.com/ValveSoftware/steam-for-linux/assets/19167795/744c2190-d48d-458a-967b-0e92099a783f)

Screenshot 2: When I scroll up a little bit many of the UI elements become transparent
![image](https://github.com/ValveSoftware/steam-for-linux/assets/19167795/6b08ce2e-e8a3-4c01-b32d-dd6442618884)

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11839739/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @pwalsh0, this issue is already being tracked at #9619. Closing as a duplicate.
