### ISSUE TITLE
When I've lost wifi connection and then I've reconnect back, steam is still offline

### ISSUE THREAD

**Issue by play3man** [ValveSoftware/steam-for-linux#971]
Everything is in the title. Steam just didn't trying reconnect back.

System info http://pastebin.com/FdGQWLhE

**Comment by not83** [comment]
Is this still an issue? If not could it please be closed

**Comment by ekaris** [comment]
I suffer from same problem, when connection is unreliable I have to close steam and login again, it wont go out of the reconnecting loop, and the network is served by fiber optic

**Comment by waltercool** [comment]
Still happen, if you change your network, steam will still working, but it will not renew your session, so the store will work, but anything related with your personal info will work... and games will not start unless you restart steam.

**Comment by kisak-valve** [comment]
Hello, per "Improved the client's responsiveness to network changes" in the [2019-05-15](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1611638091301723544) Steam client beta update and https://github.com/ValveSoftware/steam-for-linux/issues/474#issuecomment-492855274 / https://github.com/ValveSoftware/steam-for-linux/issues/474#issuecomment-493182264, please opt into Steam's beta client and retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
