### ISSUE TITLE
Can't restore game backup in latest Steam client on Ubuntu

### ISSUE THREAD

**Issue by mincopy** [ValveSoftware/steam-for-linux#9710]
#### Your system information

* Steam client version (build number or date):  1687386907
* Distribution (e.g. Ubuntu): Ubuntu (Xubuntu variant)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
/home/kevinm/.steam/steam/logs/
/home/kevinm/.steam/steam/logs/bootstrap_log.txt
/home/kevinm/.steam/steam/logs/transport_steamui.txt
/home/kevinm/.steam/steam/logs/cloud_log.previous.txt
/home/kevinm/.steam/steam/logs/client_networkmanager.previous.txt
/home/kevinm/.steam/steam/logs/backup_log.txt
/home/kevinm/.steam/steam/logs/controller_ui.previous.txt
/home/kevinm/.steam/steam/logs/workshop_log.txt
/home/kevinm/.steam/steam/logs/configstore_log.txt
/home/kevinm/.steam/steam/logs/transport_client.txt
/home/kevinm/.steam/steam/logs/text_filter_log.txt
/home/kevinm/.steam/steam/logs/steamui_update.txt
/home/kevinm/.steam/steam/logs/steamui_system.previous.txt
/home/kevinm/.steam/steam/logs/compat_log.previous.txt
/home/kevinm/.steam/steam/logs/configstore_log.previous.txt
/home/kevinm/.steam/steam/logs/systemperfmanager.txt
/home/kevinm/.steam/steam/logs/controller_ui.txt
/home/kevinm/.steam/steam/logs/cef_log.previous.txt
/home/kevinm/.steam/steam/logs/parental_log.previous.txt
/home/kevinm/.steam/steam/logs/steamui_system.txt
/home/kevinm/.steam/steam/logs/shader_log.previous.txt
/home/kevinm/.steam/steam/logs/systemmanager.previous.txt
/home/kevinm/.steam/steam/logs/parental_log.txt
/home/kevinm/.steam/steam/logs/controller.txt
/home/kevinm/.steam/steam/logs/connection_log_27015.txt
/home/kevinm/.steam/steam/logs/shader_log.txt
/home/kevinm/.steam/steam/logs/systemaudiomanager.txt
/home/kevinm/.steam/steam/logs/client_networkmanager.txt
/home/kevinm/.steam/steam/logs/webhelper.previous.txt
/home/kevinm/.steam/steam/logs/backup_log.previous.txt
/home/kevinm/.steam/steam/logs/librarysharing_log.txt
/home/kevinm/.steam/steam/logs/inventory_service_log.txt
/home/kevinm/.steam/steam/logs/connection_log_7777.txt
/home/kevinm/.steam/steam/logs/systemdisplaymanager.txt
/home/kevinm/.steam/steam/logs/content_log.txt
/home/kevinm/.steam/steam/logs/sitelicense_log.txt
/home/kevinm/.steam/steam/logs/steamwebhelper.log
/home/kevinm/.steam/steam/logs/workshop_log.previous.txt
/home/kevinm/.steam/steam/logs/systemdockmanager.txt
/home/kevinm/.steam/steam/logs/connection_log.previous.txt
/home/kevinm/.steam/steam/logs/appinfo_log.previous.txt
/home/kevinm/.steam/steam/logs/steamui_html.txt
/home/kevinm/.steam/steam/logs/stats_log.previous.txt
/home/kevinm/.steam/steam/logs/compat_log.txt
/home/kevinm/.steam/steam/logs/remote_connections.txt
/home/kevinm/.steam/steam/logs/webhelper.txt
/home/kevinm/.steam/steam/logs/content_log.previous.txt
/home/kevinm/.steam/steam/logs/timedtrial_log.txt
/home/kevinm/.steam/steam/logs/controller.previous.txt
/home/kevinm/.steam/steam/logs/cloud_log.txt
/home/kevinm/.steam/steam/logs/connection_log.txt
/home/kevinm/.steam/steam/logs/systemmanager.txt
/home/kevinm/.steam/steam/logs/appinfo_log.txt
/home/kevinm/.steam/steam/logs/steam_api_log.txt
/home/kevinm/.steam/steam/logs/cef_log.txt
/home/kevinm/.steam/steam/logs/stats_log.txt

* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

CANNOT RESTORE GAME FROM PREVIOUS BACKUP ON LINUX

What should have happened:
I expected to restore a game from my external backup drive so I don't have to download the entire package again from Steam, thereby saving me money on data which is very costly in my country (South Africa).

What did happen:
When selecting 'Restore Game Backup' from the main menu, a dialog ('Restore From Backup') appears, allowing me to browse for the directory containing the backup files. However, a Linux system dialog box appears that only has the option to open a file, not select a directory path. After selecting the game backup directory on my external hard drive, I can only click the 'Open' button, which instead opens any selected directory until I get to the backup files themselves. I have tried selecting the sku.sis, first .csd file and first .csm file but this just returns to the Steam restore dialog with nothing selected. As such, I cannot select the directory from which to restore the game and therefore cannot restore the game.

#### Steps for reproducing this issue:

1. Have Linux with the latest Steam client installed.
2. Select 'Restore Game Backup' from the main menu.
3. Try selecting a backup folder - doesn't work.

As there are many Linux variants with different preferred file dialogs, perhaps this is just a quirk of my installation. Is there any way to revert to the previous in-Steam restore dialog?

**Comment by kisak-valve** [comment]
Hello @mincopy, this issue is already being tracked at #9377. Closing as a duplicate.
