### ISSUE TITLE
Steam Crashes after logging in

### ISSUE THREAD

**Issue by dementive** [ValveSoftware/steam-for-linux#9711]
* Steam client version (build number or date): 1.0.0.78-1
* Distribution (e.g. Ubuntu): Garuda
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/11850947/logs.zip)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
After logging in the app just crashes, I see there are tons of other issues about the app crashing with the new update as well and I have tried all the solutions other people have used to get it working with no luck. I downgraded my nvidia drivers, launched in -vgui, -bigpicture, or --reset mode, Reinstalled my xdg-desktop-portal, updated my system, and tried resintalling steam in a few different ways but nothing I do can get the app to open without crashing. Has anyone found a reliable solution or does it just not work with the new update?

These are the issues I looked at already and tried all the solutions people put but none of these have worked so far to even get the application open.

https://github.com/ValveSoftware/steam-for-linux/issues/9577
https://github.com/ValveSoftware/steam-for-linux/issues/9383
https://github.com/ValveSoftware/steam-for-linux/issues/9692
https://github.com/ValveSoftware/steam-for-linux/issues/9588

#### Steps for reproducing this issue:

1. Open steam and login.
2. Wait for the app to crash.

**Comment by mhosler** [comment]
I also have this issue on arch with nvidia graphic's card

Steam seems to open whenever one of the commands I run requires steam to update. steam -tcp worked once steam.
steam -no-cef-sandbox did not work, but running steam after that opened steam. This only worked once.

Now only steam -vgui opens, but the friends tab is broken.

I have not attempted to downgrade drivers.

**Comment by EvanWashkow** [comment]
I am on Arch, with a Ryzen card, and had this problem on Gnome. KDE Plasma, oddly, worked fine out of the box. No issues whatsoever with KDE Plasma.

In Gnome, I found the solution:
1. Install [switcheroo-control](https://archlinux.org/packages/extra/x86_64/switcheroo-control/)
2. `sudo systemctl enable switcheroo-control`
3. Reboot
4. Right-click the Steam icon, and click "Launch using Discreet Graphics Card"

Hopefully this might work for you (if you're using Gnome)?

**Comment by sfxworks** [comment]
Running kde plasma at the moment and running into this

**Comment by mhosler** [comment]
I downgraded my nvidia driver and after steam --reset, bricked my computer since I did not also downgrade my kernel. 
Did "pacman -Syu" on the mounted drive from an install media. This updated the drivers to current version and a couple GTK 2.0 packages. 
Steam then opened once without issue.

I have not tried to re-open it. So, idk if that is a permanent fix. But you may try
steam --reset
and then removing and reinstalling your nvidia drivers.

**Comment by dementive** [comment]
I was able to fix this by just downloading my games on GOG instead.

**Comment by mhosler** [comment]
Deleting this file allowed me to open steam

~/.cache/nvidia/GLCache
