### ISSUE TITLE
System Information detects only GPU which runs Steam

### ISSUE THREAD

**Issue by Ring-C** [ValveSoftware/steam-for-linux#9712]
#### Your system information

* Steam client version (build number or date): 1687386907, Thu, Jun 22 2:18 AM UTC -08:00
* Distribution (e.g. Ubuntu): Linux mint 21.1 (ubuntu jammy)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: Nvidia/AMD
* Laptop: ASUS gx650py

On Linux Mint we now have preinstalled a nvidia-prime tool, which is allow to switch GPU use between three states:
1) dGPU on-demand - use dGPU for heavy load, and iGPU for easy tasks. In my case its called "nvidia on-demand".
2) iGPU (Power saving) - use only iGPU for all tasks. AMD in my case
3) dGPU (Performance mode) - use only dGPU for all tasks. Nvidia 4090 laptop in my case.
By default, in "on-demand" state steam runs on iGPU.

**Seems like Steam System Information detects only GPU which runs Steam.**
There is no nvidia 4090 in "on-demand" mode.

On nvidia driver 525.105.17, nvidia on-demand:
https://gist.github.com/Ring-C/261f9f4367fc9c7e6339d353748759f5

On nvidia driver 525.105.17, nvidia performance mode:
https://gist.github.com/Ring-C/09cce3943aa313faade37218248a8000

On nvidia driver 530.41.03, nvidia on-demand:
https://gist.github.com/Ring-C/5b34b0d05606673a54c0c9f792ec100b

On nvidia driver 530.41.03, nvidia performance mode:
https://gist.github.com/Ring-C/855880485d9b0fcebcde244868dee011

Drivers installed by Linux Mint Driver Manager, 530 is recommended:
<img width="316" alt="image" src="https://github.com/ValveSoftware/steam-for-linux/assets/130867375/2503e98a-d1a0-447b-baed-a7c3138bd3c6">

**Comment by kisak-valve** [comment]
Hello @Ring-C, while this is true, I'm failing to see how this is an issue. The Steam's system information appears to be acting as intended.

For basic troubleshooting of the Steam client, it's more important to know what GPU the Steam client is running on, and if games choose to use a secondary GPU, they are not restricted by this detail. It is also consistent with Steam on other OSes.

**Comment by Ring-C** [comment]
@kisak-valve correct me if I wrong, but this "system information" used in "Steam Hardware & Software Survey". If so, this is a problem, people use this data to make decisions. If this is how it works on other OSes too - this is a double problem.

**Comment by riquezjp** [comment]
> @kisak-valve correct me if I wrong, but this "system information" used in "Steam Hardware & Software Survey". If so, this is a problem, people use this data to make decisions. If this is how it works on other OSes too - this is a double problem.

It also makes it impossible to contribute to ProtdonDB which requires the steam info verbatim.

Not to mention the anxiety  if my new graphics card is working properly.
