### ISSUE TITLE
Steam no longer respects desktop scaling with latest release

### ISSUE THREAD

**Issue by mothringer** [ValveSoftware/steam-for-linux#9713]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu):  Gentoo, KDE Plasma DE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11853828/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Recently got the new UI update, and steam no longer respects desktop scaling, all text and UI elements are very small, unless run with -forcedesktopscaling in which case the sizing is similar to the old UI when passing the same value as my desktop scaling is set to in the DE settings.

**Comment by kisak-valve** [comment]
Hello @mothringer, this issue is already being tracked at #9209. Closing as a duplicate.
