### ISSUE TITLE
steam keeps asking user to enter password 10 seconds per time

### ISSUE THREAD

**Issue by amazing-2020** [ValveSoftware/steam-for-linux#9714]
#### Your system information

* Steam client version (build number or date):  1687386907
* Distribution (e.g. Ubuntu): opensue 15.5
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11854251/steam-logs.tar.gz)
* GPU: **Nvidia**
#### Please describe your issue in as much detail as possible:
`localhost.localdomain polkitd[803]: Operator of unix-session:8 FAILED to authenticate to gain authorization for action org.freedesktop.NetworkManager.settings.modify.system for unix-process:13058:277490 [/home/fix-bugs/.local/share/Steam/ubuntu12_32/steam] `
_Like the code I paste here, steam ask gnome desktop tell me enter the password(If i don't enter the password it will like this).
OK, I type it, but it continue block my monitor and ask me to enter my password again._
Start from this version
**But whether I type the password or not, steam can connect to the Internet**

#### Steps for reproducing this issue:

1. boot
2. open steam client, although don‘t log in
3. wait not long

**Comment by kisak-valve** [comment]
Hello @amazing-2020, this issue is already being tracked at #7856. Closing as a duplicate.

**Comment by amazing-2020** [comment]
OK, thank you
