### ISSUE TITLE
Adding a new SteamLibrary fails 

### ISSUE THREAD

**Issue by z0rti** [ValveSoftware/steam-for-linux#9719]
Steam-Version:  1687386907
Steam-Client: Build-Datum:  Mi., 21. Juni 23:18 UTC -08:00
Steam: Webbuild-Datum:  Do., 22. Juni 0:26 UTC -08:00
Steam-API-Version:  SteamClient020

Ubuntu 20.04.6 LTS
lxqt
xdg-desktop-portal
xdg-desktop-portal-gtk

Please describe your issue in as much detail as possible:

Trying to add a new SteamLibrary dir to Storage
I hit the + in Storage, i get a FileOpenDialog.
So i click "/" Open, then "mnt" Open, then "SteamLibrary" Open, then "steamapps" Open, then "appmanifest_92.acf" Open
This is the error:
```Couldn't write /mnt/SteamLibrary/steamapps/appmanifest_92.acf/.steam_exec_test.sh: Not a directory```

Problem is: there is only an Open button, not a 'Use this Dir' Button. Or the dialog should not list files just dirs?

**Comment by kisak-valve** [comment]
Hello @z0rti, this issue is already being tracked at #9377. Closing as a duplicate.
