### ISSUE TITLE
Mint 21.1: Issue regarding drop down menus and settings windows.

### ISSUE THREAD

**Issue by piemonke** [ValveSoftware/steam-for-linux#9720]
#### Your system information

* Steam client version (build number or date): Latest version as of 06/24/2023
* Distribution (e.g. Ubuntu): Mint 21.1 Cinnamon
* Opted into Steam client beta?: Yes and no, issue occurs on main and beta branch
* Have you checked for system updates?: Yes, system updates did not affect the issue
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11858544/steam-logs.tar.gz)
* GPU: Nvidia RTX 3080

#### Please describe your issue in as much detail as possible:
All steam dropdown menus from hovering over Store, Library, etc, are cut off and placed improperly. As shown below. It is impossible to access further options that have been cut off.
![An example from hovering over the Store menu](https://cdn.discordapp.com/attachments/855669569153400884/1121568020679118989/image.png). 

Additionally, other menus, such as notifications that are supposed to appear in the bottom right are incorrectly located or cut off. Most importantly, the steam client settings window looks like this. I am unable to access other tabs from the settings menu, nor adjust the size of the window and am unable to navigate it in any way.
![Broken steam settings window](https://cdn.discordapp.com/attachments/583537590892888064/1121770212371476500/image.png)

#### Steps for reproducing this issue:
Admittedly I do not know how to reproduce this issue as it is a constant, and I have no way to stop this issue from occurring, so I do not have any way of replicating it.

I've attempted reinstalling steam, adjusting Linux monitor scaling, restarting my computer, disabling multi monitor layout, applying updates, both the main and beta branches. Nothing I have done has had any effect, and this issue remains constantly without change. This issue occurs on both monitors, at all scaling ratios including base 100%.

**Comment by kisak-valve** [comment]
Hello @piemonke, this issue is already being tracked at #9708. Closing as a duplicate.
