### ISSUE TITLE
Very noticeable decrease in mousewheel scroll distance under new UI

### ISSUE THREAD

**Issue by CrashTD** [ValveSoftware/steam-for-linux#9723]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD RX 580

#### Please describe your issue in as much detail as possible:
In comparison to the old UI the scrolling distance using the mousewheel is significant decreased. as example opening the store and scrolling down one "step" with the mousewheel it scrolls down to this area be visible:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45145914/33fc33bc-4e5a-48ea-9dca-eaa4ed914e73)

however on the old UI (tested using `steam -vgui` it scrolls down in very noticeable bigger steps: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45145914/d825e3c6-dfc9-46ea-9651-f11ffe0edf86)

You can also see the difference clearly in the scroll bar.
old:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45145914/a73e8ad8-f18b-4753-992d-7b6cbdaadf2a)
new:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/45145914/8b3ea2a2-f72f-4af1-a5b2-f925b0d87b9a)

The scrolling distance is halfed at least. but it feels more. it makes scrolling in forums as well very tedious .

**Comment by kisak-valve** [comment]
Hello @CrashTD, this issue is already being tracked at #9219. Closing as a duplicate.
