### ISSUE TITLE
DRI_PRIME=1 working for some titles, not for others

### ISSUE THREAD

**Issue by TheSHEEEP** [ValveSoftware/steam-for-linux#9724]
#### Your system information

* Steam client version (build number or date): 1687563636
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11860179/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:
Usually, I can use "DRI_PRIME=1 %command%" to make any game use the proper GPU.
However, recently I found that this no longer works reliably.

Or rather, it works 100% of the time 50% of the time ;)
Some games will select the proper GPU with the command, others won't.

I thought that maybe Proton would be the problem, but both following games are run using Proton. One selects the proper GPU, the other selects the "mobile" GPU.

Here you can see one game where it doesn't work (Tower Tactics: Liberation):
![image](https://github.com/ValveSoftware/steam-for-linux/assets/1766205/92052859-aa98-4bd7-b694-bd1d073a81d8)

And here is another game where it does work (WH40k: Boltgun):
![image](https://github.com/ValveSoftware/steam-for-linux/assets/1766205/0a706a94-2ea6-4a43-a1de-40a574b175bc)

Paradox titles with their launcher also no longer select the proper GPU. Both the launcher and the game use the "Vega Series" GPU.

After testing a bunch of titles more, it seems to me that all games using Vulkan use the proper 6600M GPU, while OpenGL games use the "Vega Series".
But I'm not 100% certain with this, of course, could just an odd coincidence.

**Comment by TheSHEEEP** [comment]
I tested some more games after noticing something in my screenshot and it seems that OpenGL games always use the "Vega Series" GPU, while Vulkan games use the proper 6600m.

Quite confusing.

**Comment by kisak-valve** [comment]
Hello @TheSHEEEP, this is a video driver issue of some sort. The Steam client shouldn't manipulate this.

Report this issue to the mesa devs.

**Comment by TheSHEEEP** [comment]
In case someone finds this report having the same issue, better add your voice here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9258
