### ISSUE TITLE
[BUG] Clicking on menus doesn't work

### ISSUE THREAD

**Issue by stevanstetzvanin** [ValveSoftware/steam-for-linux#9726]
#### Your system information

Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 6:18 PM UTC -03:00
Steam Web Build Date:  Wed, Jun 21 7:26 PM UTC -03:00
Steam API Version:  SteamClient020

* Distribution (e.g. Ubuntu): Lubuntu 22.04.2 LTS (LXQt 0.17.0)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Intel

#### Please describe your issue in as much detail as possible:

Trying to click on game properties to uninstall and doesn't work, try to click on library collection filter to select the filters and clicking doesn't work.

https://gist.github.com/stevanstetzvanin/ed099595623d6420a259e26576c53de9

#### Steps for reproducing this issue:

https://youtu.be/RTYfGPWtipc

https://github.com/ValveSoftware/steam-for-linux/assets/3605047/912bab23-2a95-462e-9aae-644abbc815ad

**Comment by kisak-valve** [comment]
Hello @stevanstetzvanin, this issue is already being tracked at #9273. Closing as a duplicate.
