### ISSUE TITLE
Cannot start steam client (crash on start)

### ISSUE THREAD

**Issue by owlpaste** [ValveSoftware/steam-for-linux#9727]
#### Your system information

* Steam client version (build number or date):  manjarolinux 23.0.0 64-bit
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11861113/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Steam starts, shows a very brief loading window which I cannot see the contents of
Steam crashes

#### Steps for reproducing this issue:

1. Start steam
2. Wait for it to crash

Tried to use `steam --reset`, it managed to do what looked like a reset and downloaded updates, but still failed to start.
It was working fine 2 days ago :(

**Comment by kisak-valve** [comment]
Hello @owlpaste, based on https://github.com/ValveSoftware/steam-for-linux/issues/9321#issuecomment-1606350825, can you check if #9588 is relevant for you?

**Comment by owlpaste** [comment]
@kisak-valve, thanks for linking to the issue, it was exactly it. Removing the package allowed me to start steam (and probably because I run `--reset` before, it needed me to log in. Though I was unable to login either with QR code, steam guard key or username/password combo, at least it starts!

Thanks, il close this

**Comment by owlpaste** [comment]
Update, I can login now, looking at the `/r/steam` discord, other people were having login issues around the same time so il put it down to that :+1:
