### ISSUE TITLE
Can't select "Add to Favorites" or "Properties" in Small Mode, from right-click menu

### ISSUE THREAD

**Issue by apocalyptech** [ValveSoftware/steam-for-linux#9729]
#### Your system information

* Steam client version (build number or date): 1687386907 / Wed, Jun 21 4:18 PM UTC -08:00
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11862805/steam-logs.tar.gz)
* GPU: Nvidia (binary drivers)

#### Please describe your issue in as much detail as possible:

In small mode, when doing a right-click for the context menu of a game, it's impossible to choose "Add to Favorites" or "Properties" if you've first hovered over any of the other mouse options.  The right-click context dialog just closes right away.  "Add to Favorites" isn't difficult to select if it's the *first* thing you hover over, and *technically* you can get to "Properties" if you're really quick with a mouse movement to make sure that the first thing you select is "Properties" after opening the menu, but that's tough to pull off because the context menu generally closes when your mouse moves away from it.

You can see the behavior here: https://www.youtube.com/watch?v=-H3jHubKZSI

I suspect it might have something to do with the glitchy UIs described in  #9614 -- in the second of the videos I posted there, you can see glitchiness out on the lefthand side of the screen when the sub-menus are collapsed, which almost looks like Steam is creating a new window over there.  Perhaps that new window is temporarily stealing focus, which makes the context menu lose focus, which triggers the context-close.  Here's that video for reference here, too (you may need to watch in 60fps to actually see the glitching): https://www.youtube.com/watch?v=CBA2PBmAq2Y

It's worth noting that this only appears to happen in Small Mode -- when in Large Mode I can get to those menus just fine (though the extremely unpleasant visual glitching is omnipresent no matter what the mode).

#### Steps for reproducing this issue:

1. Go into Small Mode
2. Open a game's context menu
3. Hover over any of the submenu-enabled menu items and then hover over "Add to Favorites" or "Properties"

Other system info:

Computer Information:
Manufacturer: ASUSTeK COMPUTER INC.
Model: TUF B450-PLUS GAMING
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 2600 Six-Core Processor
CPU Family: 0x17
CPU Model: 0x8
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 3400 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.3.9-arch1-1
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: IceWM 3.4.0 (linux-gnu/x86_64)
Steam Runtime Version: steam-runtime_0.20230509.49499
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.54.03
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1c03
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.04" x 11.26" (22.95" diag), 50.9cm x 28.6cm (58.3cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 6144 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: Nvidia GPU 84 HDMI/DP
Memory:
RAM: 32025 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 583502 MB
Largest Free Hard Disk Block: 50577 MB
Storage:
Number of SSDs: 4
SSD sizes: 1000G,1000G,0B,0B
Number of HDDs: 0
Number of removable drives: 0

**Comment by kisak-valve** [comment]
Hello @apocalyptech, this reads like the issue being tracked at #9684. Closing as a duplicate.
