### ISSUE TITLE
"Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and h" Issue

### ISSUE THREAD

**Issue by T0m0ko** [ValveSoftware/steam-for-linux#9730]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Gentoo 1.0.0.76
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11869786/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:
When I tried running steam normally, its stuck on the loading screen to login to steam. Later on I tried steam --reset and checked what it displayed and here's what it says:
"Could not connect to X session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and h" I assume this is what's causing the issue but unsure.

#### Steps for reproducing this issue:

1. Start steam

(I'm still rather new to github so if there is any formatting issues, i apologize.)

**Comment by azurvii** [comment]
Not contributing to the issue itself. FWIW, I found https://github.com/ValveSoftware/steam-for-linux/issues/9692. The `-vgui` mentioned down the thread helped me to get the old / classic UI back, and worked. Hopefully it can help you for the moment.

**Comment by T0m0ko** [comment]
> Not contributing to the issue itself. FWIW, I found #9692. The `-vgui` mentioned down the thread helped me to get the old / classic UI back, and worked. Hopefully it can help you for the moment.

Yeah I did that as well and have been using that workaround for other threads but its only a bare minimum workaround that doesn't have access to friends list or any online elements

**Comment by Zatura** [comment]
I am using fedora 38, after migrating from Wayland to xorg with Nvidia draivers from RPM fusion, the same is happening to me
This my journalctl sample of steam
```
Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12704]: GetWin32Stats: display was not open yet, good
Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: Runtime for steamwebhelper: defaulting to /home/main/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: Running under Flatpak, disabling sandbox
Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: CEF sandbox already disabled
Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:06:56 fedora com.valvesoftware.Steam.desktop[12704]: CAppInfoCacheReadFromDiskThread took 137 milliseconds to initialize
Jul 01 16:06:56 fedora com.valvesoftware.Steam.desktop[12704]: Failed to init SteamVR because it isn't installed
Jul 01 16:07:28 fedora steam[12704]: gtk_disable_setlocale() must be called before gtk_init()
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: roaming config store loaded successfully - 231 bytes.
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: migrating temporary roaming config store
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: BRefreshApplicationsInLibrary 1: 0ms
Jul 01 16:07:29 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Jul 01 16:07:29 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:29 fedora /usr/libexec/gdm-x-session[10138]: (--) NVIDIA(GPU-0): CRT-0: disconnected
...
Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: System startup time: 35.18 seconds
Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
Jul 01 16:07:30 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Jul 01 16:07:30 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: BuildCompleteAppOverviewChange: 358 apps
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: RegisterForAppOverview 1: 12ms
Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: RegisterForAppOverview 2: 12ms
Jul 01 16:07:31 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Jul 01 16:07:31 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by T0m0ko** [comment]
> I am using fedora 38, after migrating from Wayland/noveau to xorg/Nvidia proprietary drivers (from RPM fusion), the same is happening to me
> This my journalctl sample of steam
> ```
> Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12704]: GetWin32Stats: display was not open yet, good
> Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: Runtime for steamwebhelper: defaulting to /home/main/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
> Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: Running under Flatpak, disabling sandbox
> Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12870]: steamwebhelper.sh[181]: CEF sandbox already disabled
> Jul 01 16:06:55 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:06:56 fedora com.valvesoftware.Steam.desktop[12704]: CAppInfoCacheReadFromDiskThread took 137 milliseconds to initialize
> Jul 01 16:06:56 fedora com.valvesoftware.Steam.desktop[12704]: Failed to init SteamVR because it isn't installed
> Jul 01 16:07:28 fedora steam[12704]: gtk_disable_setlocale() must be called before gtk_init()
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: roaming config store loaded successfully - 231 bytes.
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: migrating temporary roaming config store
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: BRefreshApplicationsInLibrary 1: 0ms
> Jul 01 16:07:29 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> Jul 01 16:07:29 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:29 fedora /usr/libexec/gdm-x-session[10138]: (--) NVIDIA(GPU-0): CRT-0: disconnected
> ...
> Jul 01 16:07:29 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: Could not connect to X session manager: None of the authentication protocols specified are supported
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: System startup time: 35.18 seconds
> Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
> Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
> Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
> Jul 01 16:07:30 fedora steam[12704]: Trying to remove a child that doesn't believe we're it's parent.
> Jul 01 16:07:30 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> Jul 01 16:07:30 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: BuildCompleteAppOverviewChange: 358 apps
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: RegisterForAppOverview 1: 12ms
> Jul 01 16:07:30 fedora com.valvesoftware.Steam.desktop[12704]: RegisterForAppOverview 2: 12ms
> Jul 01 16:07:31 fedora steam[12704]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> Jul 01 16:07:31 fedora steam[12704]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> ```

It may have something to do with xorg and Xauthority but I can't really confirm it.

**Comment by T0m0ko** [comment]
Ok managed to solve this issue ENTIRELY. Simply put: it was a driver error. Gentoo couldn't detect any drivers due to my own error of using just "radeon" in the VIDEO_CARDS section in make.conf. Instead I had to use:

VIDEO_CARDS="amdgpu radeonsi"

So, this was my own error, simply put.
After I made the change on the make.conf file, emerged world (aka simply updated my packages/drivers) and rebooted and it worked. Simple as that.
This is definitely a driver issue due to the fact that hardware acceleration is enabled by default.

The best way to check if your GPU drivers are running properly and are being detected is simply by inputting this command:
`glxinfo | grep renderer`

If it displays a "llvmpipe" on the "openGL renderer string", your drivers are not running properly and need to be fixed in your respective distribution. Otherwise, the only other solutions I can think of if you did manage to have drivers working and glxinfo does display your proper GPU, is to try some of these:

1. Delete your .Xauthority/.ICEauthority on both root and user (if you have it on your user/root directory)
2. ``steam --reset``

I have nothing else other than those two key tips to bring out.

Thank you so much to: parona-source on the gentoo matrix chat for helping me out with this issue and for providing me with the glxinfo and amdgpu radeonsi tip. Also thank you to everyone on this thread so far that's been also pointing out this issue. I apologize if i can't help out with respective ubuntu/fedora users but I hope I can give a hint of what might be the issue and solution. Now I'm gonna go test if games work (natively and with proton). I'll close the issue if they do. If not, I'll add an update and with the issue attached. Otherwise, I wish you all good luck.

**Comment by T0m0ko** [comment]
Mirror's Edge (Proton): Works
Half-Life 2 (Native):  Works

All the test games seems to be working fine and steam seems to be working fine on my end.

**Comment by parona-source** [comment]
Basically the issue stems from the new UI using hardware acceleration by default. In @T0m0ko 's case it was using llvmpipe due to broken (well non-existent) mesa drivers for his card, so it was trying to use software rendering and failing.

The steam client could be a lot more helpful about the error message.

For anyone else you should check if hardware rendering works and it doesnt use llvmpipe.
