### ISSUE TITLE
Steam Transparancy Bug 

### ISSUE THREAD

**Issue by bruhdndbndd** [ValveSoftware/steam-for-linux#9734]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [/home/dougdimmadome/.steam/steam/logs/
/home/dougdimmadome/.steam/steam/logs/steam-runtime-system-info-1685905698.txt
/home/dougdimmadome/.steam/steam/logs/steamui_system.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_steamvr_room_setup.txt
/home/dougdimmadome/.steam/steam/logs/vrmonitor.txt
/home/dougdimmadome/.steam/steam/logs/timedtrial_log.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrcompositor.txt
/home/dougdimmadome/.steam/steam/logs/installscript_log.txt
/home/dougdimmadome/.steam/steam/logs/content_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_wine64-preloader.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrdashboard.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_main.txt
/home/dougdimmadome/.steam/steam/logs/basestation_wireless.txt
/home/dougdimmadome/.steam/steam/logs/vrcompositor.txt
/home/dougdimmadome/.steam/steam/logs/vrserver.previous.txt
/home/dougdimmadome/.steam/steam/logs/systemperfmanager.txt
/home/dougdimmadome/.steam/steam/logs/steamui_update.txt
/home/dougdimmadome/.steam/steam/logs/appinfo_log.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_pairing.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrstartup.txt
/home/dougdimmadome/.steam/steam/logs/content_log.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_steam.previous.txt
/home/dougdimmadome/.steam/steam/logs/cef_log.txt
/home/dougdimmadome/.steam/steam/logs/controller.txt
/home/dougdimmadome/.steam/steam/logs/configstore_log.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_steamtours.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_settings_desktop.txt
/home/dougdimmadome/.steam/steam/logs/bootstrap_log.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_steam.txt
/home/dougdimmadome/.steam/steam/logs/transport_client.txt
/home/dougdimmadome/.steam/steam/logs/systemmanager.txt
/home/dougdimmadome/.steam/steam/logs/steamui_system.previous.txt
/home/dougdimmadome/.steam/steam/logs/durationcontrol_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_main.txt
/home/dougdimmadome/.steam/steam/logs/appinfo_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/connection_log_27015.txt
/home/dougdimmadome/.steam/steam/logs/librarysharing_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_systemui.txt
/home/dougdimmadome/.steam/steam/logs/controller_ui.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrserver.txt
/home/dougdimmadome/.steam/steam/logs/transport_steamui.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_controllerbinding.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrsharedresourcemanager.txt
/home/dougdimmadome/.steam/steam/logs/workshop_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/streaming_log.txt
/home/dougdimmadome/.steam/steam/logs/connection_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_settings_desktop.previous.txt
/home/dougdimmadome/.steam/steam/logs/connection_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_controllerbinding.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrmonitor.txt
/home/dougdimmadome/.steam/steam/logs/cloud_log.txt
/home/dougdimmadome/.steam/steam/logs/stats_log.txt
/home/dougdimmadome/.steam/steam/logs/connection_log_7777.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_wine64-preloader.txt
/home/dougdimmadome/.steam/steam/logs/controller_ui.txt
/home/dougdimmadome/.steam/steam/logs/systemdisplaymanager.txt
/home/dougdimmadome/.steam/steam/logs/sitelicense_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_controllerbinding.txt
/home/dougdimmadome/.steam/steam/logs/steamwebhelper.log
/home/dougdimmadome/.steam/steam/logs/vrclient_steamtours.previous.txt
/home/dougdimmadome/.steam/steam/logs/configstore_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_systemui.previous.txt
/home/dougdimmadome/.steam/steam/logs/steamui_html.txt
/home/dougdimmadome/.steam/steam/logs/remote_connections.txt
/home/dougdimmadome/.steam/steam/logs/client_networkmanager.txt
/home/dougdimmadome/.steam/steam/logs/backup_log.txt
/home/dougdimmadome/.steam/steam/logs/systemaudiomanager.txt
/home/dougdimmadome/.steam/steam/logs/text_filter_log.txt
/home/dougdimmadome/.steam/steam/logs/shader_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/compat_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrhw_steamvr.vdf
/home/dougdimmadome/.steam/steam/logs/vrclient_vrdashboard.txt
/home/dougdimmadome/.steam/steam/logs/shader_log.txt
/home/dougdimmadome/.steam/steam/logs/cloud_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_systemui.txt
/home/dougdimmadome/.steam/steam/logs/workshop_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_keyboard.txt
/home/dougdimmadome/.steam/steam/logs/client_networkmanager.previous.txt
/home/dougdimmadome/.steam/steam/logs/compat_log.txt
/home/dougdimmadome/.steam/steam/logs/webhelper.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrwebhelper_keyboard.txt
/home/dougdimmadome/.steam/steam/logs/parental_log.txt
/home/dougdimmadome/.steam/steam/logs/steam-runtime-system-info-1685986731.txt
/home/dougdimmadome/.steam/steam/logs/systemdockmanager.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_pairing.txt
/home/dougdimmadome/.steam/steam/logs/cef_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/steam_api_log.txt
/home/dougdimmadome/.steam/steam/logs/vrwebhelper_settings_desktop.txt
/home/dougdimmadome/.steam/steam/logs/stats_log.previous.txt
/home/dougdimmadome/.steam/steam/logs/vrclient_vrserver.txt]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
main steam client is transparent, however any windows opened are fully opaque. i do not know when this bug started nor why. 

![Screenshot from 2023-06-23 17-07-06](https://github.com/ValveSoftware/steam-for-linux/assets/67775280/d1e767b1-a3ec-4b3b-abcd-a61b03b26ce4)

**Comment by kisak-valve** [comment]
Hello @bruhdndbndd, this issue is already being tracked at #9422. Closing as a duplicate.
