### ISSUE TITLE
DPI scaling broken in the new steam UI update

### ISSUE THREAD

**Issue by CocaineJohnsson** [ValveSoftware/steam-for-linux#9740]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu):  Arch Linux (Linux-Zen-6.3.9), Xorg X11 running BSPWM, no compositor.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11886924/steam-logs.tar.gz)
* GPU: Nvidia ( 535.54.03 )

#### Please describe your issue in as much detail as possible:

After installing a steam update I found the UI had changed, this is in and of itself largely irrelevant if not for the fact that this update broke DPI scaling.

The relevant option:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/53689060/1583d883-07c3-49c7-9efb-34f17f4d01f5)

I have had Steam's DPI scaling turned off for a long time since it's always been scaling the text larger than I prefer, in this case it was still off.

The end result of this is that Steam started up being ULTRAFAT (see screenshot 1), all menus being defunct. 

![Completely broken UI scaling](https://github.com/ValveSoftware/steam-for-linux/assets/53689060/33607ad7-d6e8-4bf5-8d86-1b679d3edc1d)

Menus are inaccessible in this state

![Screenshot_2023-06-27_13-59-22](https://github.com/ValveSoftware/steam-for-linux/assets/53689060/9bf8195f-4dfb-41c1-9afd-4bcdb7ea85b2)

Naturally I could not access settings to fix this, but after some searching I found the commandline parameter `-forcedesktopscaling 1.0`, this does **successfully** disable DPI scaling and results in a very pleasant looking steam UI that isn't oversized.

![-forcedesktopscaling 1.0](https://github.com/ValveSoftware/steam-for-linux/assets/53689060/ec69438a-92db-46e2-bbdb-c904295b734a)

Using this option I could then access the settings menu to see if I could locate a more permanent fix to this issue, as having to use commandline flags to override behaviour is rather unwieldy and not a good permanent fix.

The only relevant setting appears to be turning DPI scaling on and off, so for good measure I tried with DPI scaling ON as well:

![DPI Scaling on](https://github.com/ValveSoftware/steam-for-linux/assets/53689060/63c5fc2d-3250-41e0-99a6-2ebd2722e4a0)

Steam is still ULTRAFAT with this flag on (but at least the menubar works, so settings is accessible).

This, then, leads to the obvious conclusion that the DPI scaling setting is broken in Steam version 1687386907 as both screenshots are virtually identical, aside from cropping differences.

The expected behaviour is that steam should perform no DPI scaling whatsoever with DPI scaling turned off, and not scale everything but the dropdown menus (effectively ignoring the setting and breaking the menubar).

#### Steps for reproducing this issue:

0. Run steam on a system using a bare WM, ideally bspwm with one or more 4K screens.
1.  Launch version 1687386907 with no command line parameters
2. Scaling should be very large.
3. Turn DPI scaling off
4. Scaling should still remain very large.

**Comment by kisak-valve** [comment]
Hello @CocaineJohnsson, this issue is already being tracked at #9632 / #9708. Closing as a duplicate.
