### ISSUE TITLE
Steam overlay non-interactable without -forcedesktopscaling

### ISSUE THREAD

**Issue by CocaineJohnsson** [ValveSoftware/steam-for-linux#9741]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu):  Arch Linux (Linux-Zen-6.3.9), Xorg X11 running BSPWM, no compositor.
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11886924/steam-logs.tar.gz)
* GPU: Nvidia ( 535.54.03 )

#### Please describe your issue in as much detail as possible:

Almost certainly related to #9740 / #9708 

As the title says, I noticed that without `-forcedesktopscaling 1.0` (probably works for other scaling factors or with steam's inbuilt DPI scaling on) the broken scaling option also affects the overlay, preventing any mouse or keyboard input from working. It lets me open and close the overlay with SHIFT+TAB but it doesn't let me interact with any of the UI elements.

#### Steps for reproducing this issue:

1. Turn off scaling in steam's UI on a 4K (or other ultra high resolution system)
2. Launch without -forcedesktopscaling
3. The UI should appear very scaled, trying to use the in-game overlay under these conditions will render with notifications being oversized and the steam overlay itself being seemingly uninteractable (most probably the 'hitbox' for the button is misaligned due to broken scaling, it's likely off-screen or at least hard to find).

**Comment by schuylermartin45** [comment]
I ran into something similar on a Ubuntu 22.04LTS machine (AMD Ryzen 9, Radeon 6950XT) today. In my case, when I opened steam, the window would fail to open and continually try to re-open until I restarted the computer (or presumably a kill -9 if I wasn't lazy enough to try to find the steam process).

When I tried to login for the first time, the login screen failed to render the enter button. It looked like it got cut-off. I am also using a 4K display.

Running with `steam -forcedesktopscaling` seems to have fixed my issue as well.

**Comment by zaps166** [comment]
I use 2x scaling, for me the overlay is like 4x scaling :grinning:

**Comment by kisak-valve** [comment]
Hello, per "Fix a case where the overlay could have dpi scaling applied twice." in the [2023-06-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770775726198) Steam client beta update, please opt into Steam's client beta and retest.

**Comment by zaps166** [comment]
> Hello, per "Fix a case where the overlay could have dpi scaling applied twice." in the [2023-06-29](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770775726198) Steam client beta update, please opt into Steam's client beta and retest.

yee, but now FPS counter is too small 😢 any chance to make it larger?

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://store.steampowered.com/news/app/593110/view/3651911507669747463) Steam client update.
