### ISSUE TITLE
Steam client window headers don't always allow to grab and move the window

### ISSUE THREAD

**Issue by Lastique** [ValveSoftware/steam-for-linux#9743]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Kubuntu 22.04, KDE, X11
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia GeForce RTX 2080Ti

#### Please describe your issue in as much detail as possible:

Grabbing Steam client windows by the header and moving doesn't always work. This reproduces for different windows, including the main window, Settings, About Steam, System Information, and likely others.

#### Steps for reproducing this issue:

1. Move the mouse to the header area of the window. For example, with the main Steam client window, the move the mouse cursor on the same level as the Steam/View/Friends/etc. menu is.
2. Left Click and hold, then move the mouse.

Sometimes doing this does nothing: the mouse cursor doesn't change to the cursor that is displayed when you're moving windows, and the window doesn't move; the mouse cursor just moves without dragging the window. I noticed that this is more likely to happen if you try grabbing the window at the center or the right half of the header and less likely if on the left.

I'm starting Steam with `-forcedesktopscaling 2` command line argument. Naturally, this doesn't happen with other applications and windows using native window decorations.

**Comment by kisak-valve** [comment]
Hello @Lastique, this issue is already being tracked at #9643. Closing as a duplicate.
