### ISSUE TITLE
Steam unlaunchable on Debian Sid

### ISSUE THREAD

**Issue by roryyamm** [ValveSoftware/steam-for-linux#9747]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Debian Sid
* Opted into Steam client beta?: Does not matter, happens on both
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11897831/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD: AMD 6600 XT

#### Please describe your issue in as much detail as possible:
Steam should be able to run, but instead, running Steam from a terminal fails due to a SIGBUS error and generates a crash dump. This occurs with both the beta and the non-beta client. 
[crash_20230628123328_6.dmp.txt](https://github.com/ValveSoftware/steam-for-linux/files/11897858/crash_20230628123328_6.dmp.txt)
When running from a terminal, 'Gtk-Message's saying that Steam couldn't load 'gail' and 'atk-bridge' pop up. 

#### Steps for reproducing this issue:

1. Update to latest Steam client
2. Wonder why Proton Games won't run
3. Restart Steam, get nothing
4. Uninstall Steam and reinstall from .deb file
5. Run Steam and get nothing
6. Run Steam in XTerm
7. Google what a 'Bus Error' is

**Comment by kisak-valve** [comment]
Hello @roryyamm, `[0628/122641.125227:WARNING:discardable_shared_memory_manager.cc(194)] Less than 64MB of free space in temporary directory for shared memory files: 0` in steamwebhelper.log hints towards #9233. Can you check if /dev/shm is out of space?

**Comment by roryyamm** [comment]
If /dev/shm is cleared out with a reboot, then no. I restarted my computer in an attempt to make Steam work, and /dev/shm has 15 G of space remaining. But Steam now works, and so does Discord.

**Comment by kisak-valve** [comment]
Thanks for checking, since that's the likely cause, closing in favor of #9233.
