### ISSUE TITLE
[Critical] Game crashes when trying to open Steam store from CS:GO inventory

### ISSUE THREAD

**Issue by artgol996** [ValveSoftware/steam-for-linux#9753]
* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Ubuntu 22.04.2 LTS
* Opted into Steam client beta?: NO
* Have you checked for system updates?: YES
* GPU: AMD

Game crashes when trying to open Steam store from CS:GO inventory

#### Steps for reproducing this issue:

1. Run CS^GO
2. Open inventory
3. Choose any item 
4. Click by right mouse button 
5. Choose "Sell on Community market" and observe 

Actual result: 
The game is crashed
Expected result: 
The community market is successfully opened

**Comment by kisak-valve** [comment]
Hello @artgol996, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. You should be able to workaround this issue by running CS:GO from Steam Big Picture mode or setting the game's launch options to `-vulkan`.

Closing as a duplicate.
