### ISSUE TITLE
Can't login with new Steam UI, content is too large for window

### ISSUE THREAD

**Issue by Lancer11211** [ValveSoftware/steam-for-linux#9758]
#### Your system information

* Steam client version (build number or date): ?
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: _
* GPU:  AMD

#### Please describe your issue in as much detail as possible:

I already had to use the `-forcedesktopscaling=2` to make the client usable but certain steam windows  have incorrect size.

Example: [imgur link](https://imgur.com/a/0UT39YC)

#### Steps for reproducing this issue:

1. Tried to login
2. ...

**Comment by Lancer11211** [comment]
Workaround: I remove `STEAM_FORCE_DESKTOPUI_SCALING=2.0` when I want to login, then add it again once I'm in to get a usable library interface(most of the time).

**Comment by kisak-valve** [comment]
Hello @Lancer11211, this issue is already being tracked at #9639. Remove `-forcedesktopscaling`, opt into Steam's client beta, then retest.

Closing as a duplicate.
