### ISSUE TITLE
Steam crashes on launch

### ISSUE THREAD

**Issue by dubslow** [ValveSoftware/steam-for-linux#9762]
#### Your system information

* Steam client version (build number or date):  ----  `Download skipped: /steam_client_ubuntu12 version 1687386907, installed version 1687386907, existing pending version 0`
* Distribution (e.g. Ubuntu):  ---- Debian bookworm, =testing rn
* Opted into Steam client beta?: [Yes/No]  ---- No (at least i think not)
* Have you checked for system updates?: [Yes/No] ---- yes apt-get update, upgrade, dist-upgrade

* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] ---- attached to this post [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11912527/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD ---- AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Try to launch steam, but it immediately crashes. It worked 6 or 8 months ago just fine, but somehow managed to uninstall itself from my Debian testing, this is a fresh steam install (tho I didn't actively try to purge the old uninstalled-itself version...?). Terminal output: https://gist.github.com/dubslow/d9b06a1b12e3d3516fb1fe31dd6e5690

#### Steps for reproducing this issue:

1. Download steam .deb from official site, `dpkg -i`, then run.

I am happy to provide any additional details that I can upon direction to what's relevant.

**Comment by kisak-valve** [comment]
Hello @dubslow, `Error 75 getting shared memory size` looks like the key detail in your log. This issue is already being tracked at #9514. Closing as a duplicate.

**Comment by dubslow** [comment]
I had seen that, however the `/dev/shm` part is completely absent from my log, and I thought it may ultimately have a different cause. Altho I think I see several threads of output smashing each other in my paste, so who knows.
