### ISSUE TITLE
Steam Big Picture doesn't save or removes my layouts 

### ISSUE THREAD

**Issue by TheLux83** [ValveSoftware/steam-for-linux#9770]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Manjaro KDE
* Opted into Steam client beta?: Yes and No (tested both)
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11926427/steam-logs.tar.gz)
* GPU: AMD Radeon RX 6800 XT

#### Please describe your issue in as much detail as possible:
Hey there, 
when I try to use the new big picture mode, it seems that there are issues with personal layouts.
When I create a layout and try to save it, sometime it works, and sometimes it doesn't.
When I try to remove an old Layout, that I don't want anymore, it also "deletes" a few other Layouts and also doesn't show the standard layouts anymore.
After restarting steam, everything is back again. As well as the layout I wanted to delete.

I thought that this might be a steam controller issue, but I have the same issue with an PS4 controller with steam input enabled.
Here are the logs from Steam started in a terminal:
Steam Controller Linux Log: https://gist.github.com/TheLux83/4f45f8c9fe23e249b1f6ca62aa530f27
PS4 Controller with Steam Input enabled Log: https://gist.github.com/TheLux83/8e65b477eac1f665f7d5b814da0222b9

I've also tested this with another computer and with an Windows 10 instance at everywhere it's the same problem.

Here are a few pictures to visualize the issue:
1. Showing my Layouts
![1  Your Layouts](https://github.com/ValveSoftware/steam-for-linux/assets/20551716/e89d4ab0-303b-4124-a4ec-9e769dc358e6)

2. After deleting the first layout, a few more are missing
![2  After deleting the first layout](https://github.com/ValveSoftware/steam-for-linux/assets/20551716/e548f353-7603-47b9-8601-2322e6e75ad4)

3. Templates are empty now
![3  Empty Templates](https://github.com/ValveSoftware/steam-for-linux/assets/20551716/44b0ac99-da41-4b61-b4c9-180d9db96e80)

4. As well as Recommended
![4  Empty Recommended](https://github.com/ValveSoftware/steam-for-linux/assets/20551716/97efd483-bf9d-48ae-9038-2a90ac623cdd)

I also had this problems when there was the beta and I was able to use the controller configuration when I started steam with the `-oldbigpicture` parameter. 

#### Steps for reproducing this issue:

1. Create a personal layout and save this
2. Try to delete a personal layout
6. A few more layouts get deleted and also

**Comment by kisak-valve** [comment]
Hello @TheLux83, this issue is already being tracked at #9451 / #9627. Closing as a duplicate.

Having written that, there's
```
Fix bug where configurations could fail to get deleted
Fix bug where configurations could disappear from the configuration browser after deleting a different configuration
```
in the [2023-06-30](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770782278327) Steam client beta update, update your Steam client and retest.
