### ISSUE TITLE
Steam Input layouts default to original tempalte

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/steam-for-linux#9772]
#### Your system information

* Steam client version: 1688171965 (Jun 30 18:19 (Also occurs in Stable)
* Distribution (e.g. Ubuntu): SteamOS Holo (20230630) (OS build does not matter)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11928679/steam-logs.tar.gz)
* GPU: AMD Custom APU 0405

#### Please describe your issue in as much detail as possible:
When loading user-saved layouts in Steam Input, they will default to the template that they were originally created with. This happens with both old and new Steam Input layouts. 

#### Steps for reproducing this issue:
1. Create a new Steam Input layout.
2. Attempt to load the layout.
3. It should revert back to its template.

#### Demonstration
https://github.com/ValveSoftware/steam-for-linux/assets/34801996/3f9ff88b-4dd2-4d03-9d1a-af2eabc7d62f

In this video, I have a keyboard emulation layout for Return to Castle Wolfenstein. This layout can be properly viewed when selecting `View Layout`, but if I were to attempt to load it again, the preview defaults to the `Keyboard (WASD and Mouse)` layout, and will default to that template upon loading.

**Comment by kisak-valve** [comment]
Hello @Sterophonick, this issue is already being tracked at #9451 / #9751. Closing as a duplicate.
