### ISSUE TITLE
Restoration of backup results in Steam crash

### ISSUE THREAD

**Issue by lennie420** [ValveSoftware/steam-for-linux#9774]
#### Your system information

* Steam client version (build number or date): Steam Version:  1687386907 Steam Client Build Date:  Wed, Jun 21 11:18 PM UTC -08:00
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11928945/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Restoring games results in a download of the game or a complete crash of Steam. 

#### Steps for reproducing this issue:

1. Restore a backup
2. Restore process starts
3. Steam crashes

**Comment by lennie420** [comment]
Doesn't seem to be happening with all of my backups but most of them at this point. I think all that have worked are smaller backups (below 4GB) and the only big one that has worked is Dota 2 which I made before I reinstalled my system. Some of the non-working backups go back to 2020 and have always worked on different installs.

Variations of a long lasting bug with backups are still occurring where the client starts to download the game from the internet before trying to restore the backup from disk. Cancelling and restarting the restore process can sometimes bypass this.

**Comment by lennie420** [comment]
Hi @kisak-valve I am onto something here. The way Steam now creates and handles backups has changed. Comparing older backups to the new Dota 2 backup I had made before reinstall, it seems Steam no longer creates separate disks and disk folders.

I played around and moved all csm and csd files from individual "Disk_x" folders to the root of game backup directory and editing the sku.sis from Disk_1 folder. I changed "disks" to "1". The backup completed successfully without crashing Steam.

**Comment by jpkhawam** [comment]
I was also having this issue on both Steam Deck and Fedora Steam Desktop. I was restoring old backups, but all of them were causing steam to crash on both systems.

I tried @lennie420 's solution, and it worked like a charm :) thank you for sharing your find here, I was afraid my 200GB of backups were useless now

**Comment by lennie420** [comment]
That's great @jpkhawam, I'm glad I could help. I just want to mention as well that this is occurring on all distros and not just Fedora. Currently running Arch.

**Comment by TTimo** [comment]
Thank you we've identified the problem, this will be fixed in an upcoming beta update.

**Comment by lennie420** [comment]
Thanks @TTimo, you all are too good. Peace, love and happiness!
