### ISSUE TITLE
Can' create asecond library collection after Steam update

### ISSUE THREAD

**Issue by bionade24** [ValveSoftware/steam-for-linux#9775]
#### Your system information

* Steam client version (build number or date):  1687386907
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes 
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11929335/steam-logs.tar.gz)
* GPU: Nvidia

1.  Start steam for the 1st time
2.  Log In
3.  Open Settings -> Storage -> Press the "+" Symbol -> Nothing happens

Xdg-portal work on other occassions in the Steam client.

**Comment by kisak-valve** [comment]
Hello @bionade24, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by bionade24** [comment]
Runtime info of the computer: https://gist.github.com/bionade24/78dbdfce5f9fa1695f3c88ee3ba245ed

**Comment by kisak-valve** [comment]
Thanks, https://gist.github.com/bionade24/78dbdfce5f9fa1695f3c88ee3ba245ed#file-gistfile1-txt-L2841 looks like a line to ponder. I looks like Steam isn't able to connect to xdg-desktop-portal, which is odd when combined with your note that other uses of xdg-desktop-portal are working.

As a basic sanity check, can you see if the `xdg-desktop-portal` system package is installed?

**Comment by bionade24** [comment]
I detected those contradicting lines, too. Only `xdg-desktop-portal-kde` is installed, not `xdg-desktop-portal`. I just rechecked, when I go to Settings->Storage->Default Storage Location -> Browse Folder Dolphin opens just fine.

**Comment by kisak-valve** [comment]
Thanks for checking, that makes this issue https://bugs.archlinux.org/task/78625.

Closing as a distro packaging issue.

**Comment by bionade24** [comment]
I just installed `xdg-desktop-portal` and now another non-Dolphin window spawns:
![grafik](https://github.com/ValveSoftware/steam-for-linux/assets/42534613/002adb5f-92ef-43b8-a6b6-2a990b126625)

**Comment by bionade24** [comment]
When xdg-desktop-portal.service is masked, steam falls back to the internal file explorer. Wouldn't it be possible to act the same here? It's hard to figure when `xdg-desktop-portal-kde` is installed and the filebrowser portal (dolphin) works that a package is missing.
