### ISSUE TITLE
Crash on startup OpenSUSE tumbleweed.

### ISSUE THREAD

**Issue by MickTheRus** [ValveSoftware/steam-for-linux#9779]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-1.2
* Distribution (e.g. Ubuntu): OpenSUSE Tumbleweed
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11931462/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. #### Steps for reproducing this issue

I tried to open steam on my OpenSUSE tumbleweed system using AwesomeWM and steam just crashes. I used steam about a month ago w/out an issue but for some reason now it keeps crashing. I also tried flatpak and same story.

1. Install OpenSUSE Tumbleweed
2. Install steam from main non-free repos
3. Open Steam?

--------------------------------
`steam -vgui` doesn't work
deleting everything steam related doesn't work
flatpak steam only works with `-vgui` but isn't idela for me.

**Comment by LuNeder** [comment]
Does it crash or is the tray icon still there and just the UI doesn't open? If the tray stay there, we're having the same problem

**Comment by LuNeder** [comment]
Also, does it work if you run steam -vgui? That seems to work fine for me

Tumbleweed here too, but if we do have the same problem then the person over at #9780 is also experiencing it while being on fedora

**Comment by MickTheRus** [comment]
> Does it crash or is the tray icon still there and just the UI doesn't open? If the tray stay there, we're having the same problem

Complete crash, no process running, no tray icon.

**Comment by MickTheRus** [comment]
> Also, does it work if you run steam -vgui? That seems to work fine for me
> 
> Tumbleweed here too, but if we do have the same problem then the person over at #9780 is also experiencing it while being on fedora

Nope

**Comment by MickTheRus** [comment]
I switched to NixOS
