### ISSUE TITLE
Many UI elements non-responsive

### ISSUE THREAD

**Issue by tailkinker** [ValveSoftware/steam-for-linux#9781]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): XUbuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Drop-down combo boxes do not function.  They pop open when you click on them, but do not change.  Menus opened other than the main menu bar do not do anything.

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1.  Use Steam
2. Try to use a menu or combo box
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11931722/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @tailkinker, this issue is already being tracked at #9273. Closing as a duplicate.
