### ISSUE TITLE
Bug: Client doesn't provide correct last interaction timestamp when opening new windows.

### ISSUE THREAD

**Issue by tutacat** [ValveSoftware/steam-for-linux#9783]
#### Your system information

* Steam client version (build number or date): 1688171965 (Sat, Jul 1 1:19 AM UTC), but affects versions at least back to 2015
* Distribution (e.g. Ubuntu): Fedora
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs_1688171965_03072023.zip](https://github.com/ValveSoftware/steam-for-linux/files/11936761/steam-logs_1688171965_03072023.zip)
* GPU: AMD

Operating System Version:
- "Fedora release 38 (Thirty Eight)" (64 bit)
- Kernel Name: Linux
- Kernel Version: 6.0.5-200.fc36.x86_64
- X Server Vendor: The X.Org Foundation
- X Server Release: 12201009 (XWayland)
- X Window Manager: GNOME Shell
- Steam Runtime Version: steam-runtime_0.20230509.49499

Video Card:
- Driver: AMD AMD Radeon Graphics (renoir, LLVM 15.0.6, DRM 3.48, 6.0.5-200.fc36.x86_64)
- Driver Version: 4.6 (Compatibility Profile) Mesa 22.3.3
- OpenGL Version: 4.6
- Desktop Color Depth: 24 bits per pixel
- Monitor Refresh Rate: 59 Hz
- VendorID: 0x1002
- DeviceID: 0x1638
- Revision Not Detected
- Number of Monitors: 1
- Number of Logical Video Cards: 1

#### Please describe your issue in as much detail as possible:
Expected: When a window is opened, the program passes the causal interaction timestamp (i.e. launch, click), to the window manager.

Behaviour: Interaction timestamp is not passed, and the current timestamp is used.

#### Steps for reproducing this issue:

1. Launch Steam
2. Either before the splash window, or before the library window is shown, click on, or type in, another open window than Steam.
3. The new Steam window is focused, even if another interaction happened while Steam was loading.
- The window manager is not passed the correct window-open timestamp (i.e. Steam launching), so it doesn't know whether the new window should be focused or not.

**Comment by kisak-valve** [comment]
Hello @tutacat, this issue is already being tracked at #3783. Since this issue report adds some more details to ponder, I've transferred it to https://github.com/ValveSoftware/steam-for-linux/issues/3783#issuecomment-1618218679.

Closing as a duplicate.
