### ISSUE TITLE
Steam UI transparent on Linux (Fix found!)

### ISSUE THREAD

**Issue by Mumrik93** [ValveSoftware/steam-for-linux#9784]
#### Your system information

* Steam client version;
Steam-version:  1687386907
Byggversionsdatum för Steam-klient:  ons 21 juni 23:18 UTC -08:00
Byggversionsdatum för Steam Web:  tors 22 juni 0:26 UTC -08:00
Steam API-version:  SteamClient020

* Distribution: Linux Mint 21.1

* Opted into Steam client beta?: Yes

* Have you checked for system updates?: Yes

* Steam Logs: [generate by running this command in a terminal: Only got an error message, catalogue does not exists.

* GPU: Nvidia GTX1080ti

#### Please describe your issue in as much detail as possible:
After the latest update a few weeks ago my UI became transparent, making the client very hard to navigate and use overall.

After some asking around on Reddit i found a possible fix, not sure if it will last. But in the nvidia x-server settings, i turned off FXAA and then i rebooted steam, now the UI looks like normal again.. and I could see that the client had a brand new UI.

#### Steps for reproducing this issue:

1. Turn on FXAA (if not already turned on) in the nvidia x-server settings.
2. Reboot steam.
3. That should be it.

**Comment by kisak-valve** [comment]
Hello @Mumrik93, this issue is already being tracked at #9422. Closing as a duplicate.
