### ISSUE TITLE
Steam refusing to launch....

### ISSUE THREAD

**Issue by furycd001** [ValveSoftware/steam-for-linux#9789]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.78-1 (pacman)
* Distribution: Arch *(fully up-to-date)*
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes fully up-to-date system
* Steam Logs: Attached....
* CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
* GPU: NVIDIA Corporation GK107 [GeForce GTX 650]
*  RAM: 16G

#### Please describe your issue in as much detail as possible:
HI Guys..

I have steam installed via **pacman -S steam** on my fully up-to-date system. It had been working just fine until this morning. However, as of this morning steam is refusing to launch. When I attempt to launch it from the terminal, I the following output....

```
steam.sh[1461]: Running Steam on arch rolling 64-bit
steam.sh[1461]: STEAM_RUNTIME is enabled automatically
setup.sh[1535]: Steam runtime environment up-to-date!
steam.sh[1461]: Steam client's requirements are satisfied
[2023-07-04 09:55:10] Startup - updater built Jun 21 2023 21:17:38
[2023-07-04 09:55:10] Startup - Steam Client launched with: '/home/furycd001/.local/share/Steam/ubuntu12_32/steam'
07/04 09:55:10 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(1601)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

My nvidia drivers are **nvidia-470** & I have **nvidia-470xx-dkms  nvidia-470xx-utils  nvidia-470xx-settings  lib32-nvidia-470xx-utils** installed. I'm also running the **lts-kernel** btw..

I've tried reinstalling all my nvidia drivers, along with steam, but steam is still failing to launch.  
I also tried removing **~/.steam/** from my home folder & resetting steam with **steam --reset**, but that had no effect either.  
I also tried launching steam with the old ui **steam -vgui**, but that doesn't work either & I get the same output listed above.  
After running **steam** or **steam -vgui**, it will just sit there forever with no more output unless I press **ctrl+c** to terminate.  

[Here is a copy of my Xorg.0.log in case it's of any use....](https://termbin.com/4lxo)

#### Steps for reproducing this issue:

1. Install steam via **sudo pacman -S steam**
2. Launch steam through terminal..
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11949217/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @furycd001, the NVIDIA proprietary driver requires that the running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version to work properly.

Looking at https://aur.archlinux.org/packages?K=nvidia-470, the AUR currently has:
nvidia-470xx-dkms | 470.182.03-2
nvidia-470xx-utils | 470.182.03-2
lib32-nvidia-470xx-utils | 470.199.02-1

This version mismatch will break all 32 bit applications trying using this combination. You can test this without Steam being involved by installing `lib32-mesa-utils` and running `glxinfo32 -B` in a terminal.

Report this issue to the package maintainer(s) for the nvidia-470xx AUR packages.

Closing as not a Steam client issue.
