### ISSUE TITLE
Steamwebhelper amasses thousands of open file handles over time, eventually reaching limit

### ISSUE THREAD

**Issue by UFeindschiff** [ValveSoftware/steam-for-linux#9796]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11952422/steam-logs.tar.gz)
* GPU: nVidia GeForce RTX 3090 

#### Please describe your issue in as much detail as possible:
Letting the Steam client with the new Web-UI run for a couple days causes the steamwebhelper to amass thousands of open file handles over time. This eventually causes it to run into the system limit causing strange behavior where many applications will no longer launch due to hitting the file handler limit. The error you will get on the console is "Maximum number of clients reached". Users not launching their programs through a console will not receive any feedback and will just have their applications stop working due to the steamwebhelper hogging all of the open file handles. After running Steam for a couple of days I observed the following:

```
$ lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3
   2940 steamwebhelper
    197 dbus-daemon
    138 X
```

This issue only appears to this extent when using the new Steam Web-UI. Running Steam with the -vgui flag does not result in the same behavior.

#### Steps for reproducing this issue:

1. Launch Steam
2. Have it running for a few days
3. Observe as the steamwebhelper amasses thousands of open file handles

**Comment by kisak-valve** [comment]
Hello @UFeindschiff, this issue is already being tracked at #9561. Closing as a duplicate.
