### ISSUE TITLE
[BUG] Steam client fails to shutdown

### ISSUE THREAD

**Issue by alkaris2** [ValveSoftware/steam-for-linux#9798]
#### Your system information

* **Steam client version (build number or date):**  1687386907 - Steam Client Build Date:  Thu, Jun 22 6:48 AM UTC -08:00
* **Distribution:** Manjaro 23.0.0
* **Opted into Steam client beta?:** No
* **Have you checked for system updates?:** yes
* **Steam Logs:**  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11957415/steam-logs.tar.gz)
* **GPU:** Asus Geforce RTX 3070 Dual OC

#### Please describe your issue in as much detail as possible:

When exiting the Steam Client for shutdown it hangs and fails to shutdown keeping multiple thread processes still running even after killing the main Process ID for Steam, as well as the Steam Client used in Proton with pressure-vessel, each process has to be manually terminated.

When ran from Terminal I can see it showing the following errors;

```BASH
Thread "CJobMgr::m_WorkThreadPool:1" (ID 3339862) failed to shut down
```

This message gets repeated on loop, and is unresponsive to `^C` input to exit the process, as any application should always exit when they receive that command input to close. See the following Gist for more details;

https://gist.github.com/alkaris2/09b53b555eee801a4ce789cd4095ba69

I'm forced to kill all the process IDs manually when it fails to respond to the `^C` I also have to manually kill all these following processes spawned by Steam as they too fail to exit when the main process has been terminated;

```BASH
steam
wineserver
plugplay.exe
explorer.exe
steam.exe
winedevice.exe
tabtip.exe
services.exe
svchost.exe
rpcss.exe
conhost.exe
pressure-vessel-adverb
```

I have needed to create a kill script just to terminate everything all at once when Steam fails to shutdown. I've tested if the same happens while Opted-In to Steam Beta and it's the same issue there also. Spawns all these processes and fails to exit cleanly when told to Exit Steam.

Here is also the Dump File that was also created by Steam when it fails to shutdown.
[assert_20230705205739_70.dmp.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11957577/assert_20230705205739_70.dmp.tar.gz)

**Comment by kisak-valve** [comment]
Hello @alkaris2, this issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/6809. Closing as a duplicate.
