### ISSUE TITLE
Lots of windows opening over time

### ISSUE THREAD

**Issue by nijave** [ValveSoftware/steam-for-linux#9806]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Fedora 37
* Opted into Steam client beta?: [Yes/No] Don't think so
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD AMD Vega 64

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Since the UI redesign, I come back to my computer after leaving steam open overnight and find a bunch of windows have spawned. I don't expect these to spawn

#### Steps for reproducing this issue:

1. Open Steam client
2. Let it sit in the background for a while (overnight)
3. Find a bunch of windows have spawned

They are usually stacked in a pile but I spread them out 
![steam](https://github.com/ValveSoftware/steam-for-linux/assets/384474/a5ef0268-0ff7-410e-9d51-f45f649f057a)

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11973099/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @nijave, this issue is already being tracked at #9786. Closing as a duplicate.
