### ISSUE TITLE
Proton games won't launch

### ISSUE THREAD

**Issue by waaynee** [ValveSoftware/steam-for-linux#9808]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): 6.1.31-2-MANJARO (64-bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11979977/steam-logs.tar.gz)
* GPU: Nvidia GTX 1070 Ti

#### Please describe your issue in as much detail as possible:
It seems like the new update broke launching proton games. If you start a game it says 'launching' as shown in the screenshot attached, but it will hang there. Already deleted compatdata as suggested in some reddit threads and tried any newer Proton version including the normal ones an GE.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/26093213/44752e43-fe6e-48b3-9cd7-f9cb4f9c42f9)

#### Steps for reproducing this issue:

1. Choose any proton version for you game
2. Start it

**Comment by kisak-valve** [comment]
Hello @waaynee, we're tracking issues with games run with Proton in the Proton issue tracker, also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3104#issuecomment-1625355405.
