### ISSUE TITLE
Getting a steam notification breaks sway focus and doesn't let you type in other apps

### ISSUE THREAD

**Issue by slonkazoid** [ValveSoftware/steam-for-linux#9811]
#### Your system information

* Steam client version (build number or date):  
```
Steam Version:  1688685284
Steam Client Build Date:  Fri, Jul 7 1:58 AM UTC -08:00
Steam Web Build Date:  Fri, Jul 7 1:59 AM UTC -08:00
Steam API Version:  SteamClient020
```
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11982705/steam-logs.tar.gz)
* GPU: AMD Radeon RX 6500XT

#### Please describe your issue in as much detail as possible:

[Discussion](https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3826414367723695810/?tscn=1684105245)

When you get a Steam notification with the new UI, it doesn't let you use the keyboard in the currently focused app, unless it's a DM notification and the Steam messaging window is in the same workspace as the app you're trying to use. Very distruptive to the point I disabled some notifications.

This happens both with the Steam Runtime and native.

#### What I expected to happen:

I should be able to continue typing.

#### Steps for reproducing this issue:

1. start a text editor
2. get a "now playing" notification on steam

**Comment by kisak-valve** [comment]
Hello @slonkazoid, this issue is already being tracked at #9458. Closing as a duplicate.

**Comment by slonkazoid** [comment]
Ah sorry, I searched for "focus", "sway" and "sway  focus" and didn't find anything
