### ISSUE TITLE
Steam crashloop

### ISSUE THREAD

**Issue by xSylla** [ValveSoftware/steam-for-linux#9812]
#### Your system information

* Steam client version: 1687386907
* Distribution: Fedora 38 (clean install)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11984637/steam-logs.tar.gz)
* GPU: AMD Radeon RX  7900 XTX
* CPU: AMD Ryzen 9 7950X3D

#### Please describe your issue in as much detail as possible:
Hi, when I open steam it just crashloop, it seem to be steamwebhelper fault as I got this on dmesg:

[  239.579140] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
[  250.089468] Composite Threa[6912]: segfault at 0 ip 0000000000000000 sp 00007fa43c4866b8 error 14 in **steamwebhelper**[400000+10000] likely on CPU 19 (core 3, socket 0)

the only workaround I found is to close steam, open library page directly from the app launcher (gnome app launcher in my case)

**Comment by kisak-valve** [comment]
Hello @xSylla, if you completely close Steam, then run `steam` from a terminal, does it behave as expected?

**Comment by xSylla** [comment]
> Hello @xSylla, if you completely close Steam, then run `steam` from a terminal, does it behave as expected?

Tried right now and yes, it works

**Comment by kisak-valve** [comment]
Thanks for checking. This issue is already being tracked at #9383. Closing in favor of the older issue report.
