### ISSUE TITLE
Steam creating tiny ghost windows frequently

### ISSUE THREAD

**Issue by willtheoct** [ValveSoftware/steam-for-linux#9813]
#### Your system information

* Steam client version (build number or date):  1687386907  Wed, Jun 21 17:18 UTC -08:00
* Distribution (e.g. Ubuntu): Ubuntu  22.04.2
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11984868/steam-logs.tar.gz)
* GPU: AMD 2017

#### Please describe your issue in as much detail as possible:
I expect to use my computer with steam running in the background, but not popping up windows, nor popping them up during gameplay. Instead, a small window with no title or rendering, but a border and close buttons appears, sometimes every 15 seconds, sometimes every 2 hours. It closes itself within a couple of seconds, but it brings windows out of focus while gaming, too.

diff of xwininfo when it appears:
```
-     73 children:
+     76 children:
      0x80000a "gnome-shell": ("gnome-shell" "Gnome-shell")  1x1+-200+-200  +-200+-200
         1 child:
         0x80000b (has no name): ()  1x1+-1+-1  +-201+-201
+     0x80044c (has no name): ()  303x125+130+69  +130+69
+        1 child:
+        0x120013b (has no name): ()  283x70+10+45  +140+114
+     0x10000d0 (has no name): ()  283x70+0+0  +0+0
+     0x140014f "notificationtoasts_20_desktop": ("steamwebhelper" "steam")  283x70+2277+1504  +2277+1504
  ```
#### Steps for reproducing this issue:

1. wait for ghost window to appear with no programs but steam running
2. `xwininfo -tree -root`
3. (optional)` xwininfo -tree -root >> file1.txt`
4. (optional) wait momentarily for window to disappear
5. (optional) `xwininfo -tree -root >> file2.txt && git diff file1.txt file2.txt`
6. see three x11 windows added, one labeled with steam

**Comment by kisak-valve** [comment]
Hello @willtheoct, can you reproduce this issue with the current Steam client beta?

This might be related to "Restrict a workaround that prevents a crash on Nvidia GPUs to only activate when we detect an Nvidia GPU. Side-effects for this workaround include window flashing and focus stealing when a steam window is closed, which should no longer affect Intel/AMD users.` in the [2023-06-05](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3666541770799548343) Steam client beta.

**Comment by willtheoct** [comment]
It appears fixed in the steam beta.
