### ISSUE TITLE
Steam causing GPU Memory leak on Xorg and Nvidia

### ISSUE THREAD

**Issue by RafaelAmauri** [ValveSoftware/steam-for-linux#9816]
#### Your system information

* Steam client version (build number or date): Version 1687386907
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

Steam causes VRAM usage to increase each time that the Steam window is opened after being minimized. If you never close steam, the VRAM usage keeps increasing until either your system crashes or you close Steam.

I don't know exactly what aspect of the store is causing this, but I suspect it is something to do with the new UI, because it definitely was not here before.

I have also uploaded a very short video showing the steps for reproducing.

#### Steps for reproducing this issue:

1. Open a GPU monitoring app - I use nvtop
2. Open steam
3. Minimize steam
4. Maximize steam
5. GPU memory usage will increase by a fair bit and not be deallocated
6. Repeat steps 3-4. Each time that you repeat these steps, more and more VRAM will be used.
7. Close steam to restore VRAM usage back to normal

In my case, I am using i3wm, but I had a friend that uses Gnome try the same steps on his PC and he was able to successfully reproduce the same error. He is using Xorg as well, not Gnome on Wayland.

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11987374/steam-logs.tar.gz)
https://github.com/ValveSoftware/steam-for-linux/assets/49131143/e6c8b25b-c583-4b49-85b8-ef4ab95f2693

**Comment by kisak-valve** [comment]
Hello @RafaelAmauri, this issue is already being tracked at #9638. Closing as a duplicate.
