### ISSUE TITLE
steam -vgui doesn't let me start games.

### ISSUE THREAD

**Issue by Drogobo** [ValveSoftware/steam-for-linux#9819]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11992253/steam-logs.tar.gz)
* GPU: NVIDIA GeForce RTX 2070 SUPER 

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
What should happen:
I can start `steam -vgui` and use steam like normal to play games. When I close Steam, Xorg doesn't crash.
What actually happens:
I start `steam -vgui`, and when I start a game, it crashes. When I close Steam, Xorg crashes.

#### Steps for reproducing this issue:

1. Open steam through `steam -vgui`
2. Try to play a game and get frustrated that it won't start.
3. Close steam, and Xorg kills itself.

**Comment by kisak-valve** [comment]
Hello @Drogobo, in general, no OpenGL application including Steam should be capable of taking down the user session. This reads like a video driver issue which should be reported to your video driver vendor.

In any case, this issue is already being tracked at #9807. Closing as a duplicate.
