### ISSUE TITLE
[Feature] Add option to "Add Start Menu Shortcut" for games

### ISSUE THREAD

**Issue by Syphdias** [ValveSoftware/steam-for-linux#9821]
#### Your system information

* Steam client version (build number or date): 1687386907
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: -
* GPU: Nvidia

#### Please describe your feature request in as much detail as possible:
When installing a new game you get an option to add a shortcut to the desktop and to the start menu. After installing it is no longer possible to add a shortcut in the start menu, only add a shortcut to the desktop.

In my case this is a problem when choosing games from a different steam library folder. The games did not get installed on this OS (or even machine) and I still want to have them in my start menu(\*) for easy access.

This is how you can add a game short cut to the desktop after it was installed:
Right-click the game > Manage > Add desktop shortcut
![image](https://github.com/ValveSoftware/steam-for-linux/assets/16988672/a4a13d9d-aca8-410e-9b13-347cead3dce7)

Please add an option for adding a shortcut to the start menu analogous to adding a shortcut to the desktop.

#### My current workaround
- add desktop shortcut for the game:
  Right-click the game > Manage > Add desktop shortcut
- move the shortcut to the "start menu" folder: e.g.
  `mv ~/Desktop/Sea\ of\ Thieves.desktop ~/.local/share/applications/`

(\*) Actually, I use i3wm so I do not see stuff in `~/Desktop` when no widows are open and I do not have a classical start menu. I use dmenu, j4-demnu-desktop, or rofi to launch games. But they scan the same folders so it should be start menu to not confuse anybody.

**Comment by kisak-valve** [comment]
Hello @Syphdias, this issue is already being tracked at #8354. Closing as a duplicate.
