### ISSUE TITLE
New Overlay causes to kill CSGO when using openGL

### ISSUE THREAD

**Issue by JokerGermany** [ValveSoftware/steam-for-linux#9824]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1687386907
Steam Client Build Date:  Wed, Jun 21 23:18 UTC -08:00
Steam Web Build Date:  Thu, Jun 22 00:26 UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): 
Ubuntu Mate 22.04
* Opted into Steam client beta?: [Yes/No] 
The logs are without beta, but it happens with and without
* Have you checked for system updates?: [Yes/No]
 Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
Don't find it
* GPU: Nvidia/Intel/AMD
AMD
#### Please describe your issue in as much detail as possible:

When you start CSGO with the new Steam Overlay activated and press shift + Tab it crashes.
If you click on a profile of a player, it crashes, 
if you get a message, it crashes
Every interaction with the Steam Overlay let to crash

This only happens with OpenGL, but i send log files for both.
https://gist.github.com/JokerGermany/3bee35332f211ff3423a23c53bd95f1d

Similar issue: #9736 

#### Steps for reproducing this issue:

1. Start CSGO
2. Press Shift + TAB

**Comment by kisak-valve** [comment]
Hello @JokerGermany, this issue is already being tracked at #9586 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3172. Closing as a duplicate.
