### ISSUE TITLE
steam doesnt change profile picture in gdm env and thunar

### ISSUE THREAD

**Issue by sjakk** [ValveSoftware/steam-for-linux#9829]
#### Your system information

* Steam client version (build number or date): 1689034492 / Mon, Jul 10 8:59 PM UTC -08:00
* Distribution (e.g. Ubuntu): Arch 6.4.1-arch2-1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: null
* GPU: Nvidia 470xx

#### Please describe your issue in as much detail as possible:
I cant switch my profile picture im using gdm as desktop environment and thunar as file manager

[gist](https://gist.github.com/sjakk/f8265f3ea0057c7faa3713fcaa6db536) steam runtime diagnostic
#### Steps for reproducing this issue:

1. Go to your steam profie and click on edit profile
2.  Try to switch your avatar
3. Nothing happens

**Comment by kisak-valve** [comment]
Hello @sjakk, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by sjakk** [comment]
Here the [gist](https://gist.github.com/sjakk/f8265f3ea0057c7faa3713fcaa6db536)
