### ISSUE TITLE
Can't move up the .steam folder to select NVME for library

### ISSUE THREAD

**Issue by serber1990** [ValveSoftware/steam-for-linux#9831]
#### Your system information

* Steam client version (build number or date):  1689034492
* Distribution (e.g. Ubuntu):  Ubuntu
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes is Up to Date
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Whenever I try to select a new library, I can only access the .steam folder, no option to go up the folders in my tree.

I should be able to move along my files tree with no problems

#### Steps for reproducing this issue:

1. Go to Steam 
2. Settings
3. Storage > + icon to add new library.

#### How is view to select library:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/39016027/16719860-7424-4fb9-8e8c-de9883e8abfc)

**Comment by kisak-valve** [comment]
Hello @serber1990, this issue is already being tracked at #9797. Closing as a duplicate.
