### ISSUE TITLE
Started crashing after system update

### ISSUE THREAD

**Issue by sTiKyt** [ValveSoftware/steam-for-linux#9833]
#### Your system information

* Steam client version (build number or date): Can't check, crashing
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

Logs:
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12022508/steam-logs.tar.gz)

Specific Crash Dump:
[crash_20230712033649_27.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/12022505/crash_20230712033649_27.dmp.zip)

#### Please describe your issue in as much detail as possible:
Updated my system (Nvidia driver, linux, etc.), and now steam doesn't launch anymore

#### Steps for reproducing this issue:

1. Update Arch Linux
2. Try running Steam
3. Crash

**Comment by kisak-valve** [comment]
Hello @sTiKyt, without looking too closely at the details, I expect this issue is already being tracked at #9805. Closing as a duplicate.
