### ISSUE TITLE
Game crashes when taking a screenshot or opening overlay

### ISSUE THREAD

**Issue by melonn1** [ValveSoftware/steam-for-linux#9837]
### Your system information

* Steam client version (build number or date): 1689034492 (.deb version from the pop shop)
* Distribution: Pop!_OS 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Radeon RX 580 (8gb edition)
* GPU Drivers: Mesa 22.3.5
* CPU: Ryzen 5 3600
* Display Server: Xorg (x11)

#### Please describe your issue in as much detail as possible:
Taking a screenshot or opening the new overlay via tab + shift will result in my game crashing about 70%~ of the time, this wasn't an issue until the new UI/Overlay released.

#### Steps for reproducing this issue:

1. Open any game (Risk of Rain 2 and Ultrakill are most affected for me, but it happens on any game too)
2. Try to open the overlay or take a screenshot
3. The game will most likely crash

This seems to be an issue on Wayland as well

**Comment by kisak-valve** [comment]
Hello @melonn1, this issue is already being tracked at #9586. Closing as a duplicate.
