### ISSUE TITLE
Restoring game backup crashes Steam

### ISSUE THREAD

**Issue by coreybruce** [ValveSoftware/steam-for-linux#9839]
#### Your system information

* Steam client version (build number or date):  1689034492
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: https://gist.github.com/coreybruce/7d729d3d7995f99d3704984141e68fee
* [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12036883/steam-logs.tar.gz)
* GPU: RX 6700XT

#### Please describe your issue in as much detail as possible:
Steam will crash when I try and restore any game backup using the Steam backup and restore.
#### Steps for reproducing this issue:

1.  Go to restore game backup
2.  click install
3.  Steam Crashes

**Comment by kisak-valve** [comment]
Hello @coreybruce, this issue is already being tracked at #9774. Closing as a duplicate.
