### ISSUE TITLE
Titlebar buttons do not use user preferences

### ISSUE THREAD

**Issue by ZMensRain** [ValveSoftware/steam-for-linux#9841]
#### Your system information

* Steam client version 1689034492
* Distribution Pop os! latest
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: AMD

Steam windows do not conform with the rest of my windows. I wish to have my close, maximize, and minimize buttons on the the left of the window and their does not seem to be a way to do that I also use the pop os! tiling extension a lot and the steam windows will get cut off by the edge of my screen because they don't conform to my settings. 

#### Steps for reproducing this issue:

1.  download steam as a deb or flatpak
2. download gnome tweaks
3. go to the Window Titlebars section
4. Change Placement to Left
5. open steam
6. see that it has its title bar buttons on the right still.

**Comment by kisak-valve** [comment]
Hello @ZMensRain, this issue is already being tracked at #1040. Closing as a duplicate.
