### ISSUE TITLE
Allow adding global launch arguments

### ISSUE THREAD

**Issue by Qwinci** [ValveSoftware/steam-for-linux#9842]
Allow adding global launch arguments that get added to the per-game individual launch arguments. The reason this would be useful is in situations like when you are using systemwide llvm libc++ you usually need to LD_PRELOAD libstdc++.so into every game (atleast proton ones, proton fails to create a window if you don't) so it would be more convenient to specify it once inside some kind of global launch arguments and then every game would get it without needing to individually add it.

**Comment by kisak-valve** [comment]
Hello @Qwinci, this issue is already being tracked at #3453. Closing as a duplicate.
