### ISSUE TITLE
"Force the use of" -> "Steam Linux Runtime 1.0 (scout)" should not be possible for games that require sniper

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/steam-for-linux#9844]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): any (tested on Ubuntu 22.04 and Debian 12)
* Opted into Steam client beta?: yes
* Have you checked for system updates?: yes
* GPU: any (tested on NVIDIA and AMD)

#### Please describe your issue in as much detail as possible:

A few native Linux games on Steam require the use of the [Steam Linux Runtime 3.0 (sniper) container runtime](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/container-runtime.md#steam-runtime-3-sniper), and are no longer supported or expected to run successfully in the traditional [LD_LIBRARY_PATH-based Steam Runtime 1 'scout' runtime](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/ld-library-path-runtime.md) or the [Steam Linux Runtime 1.0 (scout)](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/container-runtime.md#steam-linux-runtime-scout-on-soldier) that is based on it.

Known games that require sniper so far:

* ~~a non-default branch of~~ Battle for Wesnoth
* Counter-Strike 2 since September 2023
* Dota 2 since July 2023
* Endless Sky
* Retroarch

When configuring these games' properties, I should not be able to choose a compatibility tool that is known to be incompatible with the game. The valid/supportable choices are:

* install the Linux version and run it under Steam Linux Runtime 3.0 (sniper) (internally app ID 1628350)
* install the Windows version and run it under any version of Proton

while these are not expected to work, and should not be offered for these games:

* install the Linux version and run it under the LD_LIBRARY_PATH-based scout runtime
* install the Linux version and run it under Steam Linux Runtime 1.0 (scout) (1070560, SLR 2 'soldier' with an extra scout compatibility layer)
* install the Linux version and run it under Steam Linux Runtime 2.0 (soldier) (13911100)

Steam Linux Runtime 1.0 (scout) (1070560) should only be offered for older games that were designed to run in the 'scout' environment.

#### Steps for reproducing this issue:

1. Install one of the games that runs under sniper. The easiest are the ones that use sniper for their default branch: Dota 2, Endless Sky or RetroArch.
2. Right-click, Properties, Compatibility
3. Check "Force the use of..." and observe the list of compatibility tools that are offered

#### Expected result

The list contains various Proton versions (7.0, 8.0, etc.), and optionally "Steam Linux Runtime 3.0 (sniper)" (internally app ID 1628350).

The list should not contain "Steam Linux Runtime" or "Steam Linux Runtime 1.0 (scout)" (both are names for app ID 1070560), or "Steam Linux Runtime 2.0 (soldier)" (1391110).

#### Actual result

The list correctly contains various Proton versions, which is OK.

The list correctly does not contain "Steam Linux Runtime 2.0 (soldier)" (1391110), for the reasons described in #7430.

The list **does** contain "Steam Linux Runtime" (internally app ID 1070560). If I select it, the game is launched in an environment containing libraries older than the one the game was designed for, and it is likely to crash or run incorrectly.

**Comment by smcv** [comment]
Relatedly relatedly, now that we have more than one SLR branch in active use, it would be great if their displayed names could be changed to something that indicates the sequence and has less emphasis on the codenames, perhaps something like:

```
Steam Linux Runtime             -> Steam Linux Runtime 1.0/2.0 (scout)
Steam Linux Runtime - soldier   -> Steam Linux Runtime 2.0 (soldier)
Steam Linux Runtime - sniper    -> Steam Linux Runtime 3.0 (sniper)
```

**Comment by sylware** [comment]
I don't understand "install the Linux version and run it under the LD_LIBRARY_PATH-based scout runtime" should not be provided???

The only and right user way to tell dynamically the ELF loader where to look for a game "runtime" is LD_LIBRARY_PATH (and to a less extend LD_PRELOAD, and could be a private installation-time configured mechanism).
Game binaries could also (should?) be cleanely built with ELF DT_RUNPATH and could (should?) distribute properly their own runtime (since they could run in STEAM_RUNTIME=0 anyway).
Ofc, they would have to configure their own runtime: configure some non already defined (or override) env variables, for instance for libthai to find its data, or for some x11 data (usually if you use your own distributed shared lib, you would have to use the data with the right format/version and then distribute that data too).

**Comment by smcv** [comment]
> I don't understand [why] "install the Linux version and run it under the LD_LIBRARY_PATH-based scout runtime" should not be provided???

Games that are compiled against sniper require newer libraries than the ones that the LD_LIBRARY_PATH-based scout runtime is able to provide. They get these from the Steam Linux Runtime 3 'sniper' container. There are technical limitations in the LD_LIBRARY_PATH approach that result in the LD_LIBRARY_PATH-based runtime being unable to upgrade some libraries beyond the oldest host operating system that Steam still supports (which is very old).

>  Game binaries ... could (should?) distribute properly their own runtime

This has been tried many times and it always breaks something, usually graphics drivers. One of Steam's biggest compatibility problems with native Linux games is when the game bundles a library that it should be picking up from elsewhere.

I will not discuss the design or purpose of the various Steam Runtime branches further here, because it is off-topic and will distract the developers who have the ability to fix the various problems we've reported. That's not beneficial to anyone.

**Comment by sylware** [comment]
I am sorry, but as far as know LD_LIBRARY_PATH is the only user level way, something is weird here as technically there is no other way.

Would tell me how you can acheive this?
(here or in the issue related to dota2 or a new one).

**Comment by smcv** [comment]
> Relatedly relatedly, now that we have more than one SLR branch in active use, it would be great if their displayed names could be changed to something that indicates the sequence and has less emphasis on the codenames, perhaps something like:
> 
> ```
> Steam Linux Runtime             -> Steam Linux Runtime 1.0 (scout/soldier)
> Steam Linux Runtime - soldier   -> Steam Linux Runtime 2.0 (soldier)
> Steam Linux Runtime - sniper    -> Steam Linux Runtime 3.0 (sniper)
> ```

This part has now *mostly* been implemented. Since last week, they are labelled "Steam Linux Runtime 1.0 (scout)", "Steam Linux Runtime 2.0 (soldier)" and "Steam Linux Runtime 3.0 (sniper)" when they appear in the Steam library.

However, the menu of possible compatibility tools activated by checking "Force the use of" still shows "Steam Linux Runtime". This option is app ID 1070560, the one we now call "Steam Linux Runtime 1.0 (scout)".

**Comment by smcv** [comment]
> However, the menu of possible compatibility tools activated by checking "Force the use of" still shows "Steam Linux Runtime". This option is app ID 1070560, the one we now call "Steam Linux Runtime 1.0 (scout)".

This has also been relabelled to "Steam Linux Runtime 1.0 (scout)" now.

The original issue, that it is possible to select scout for games like CS2 and Dota 2 that are not designed to be run in scout, is still present.

**Comment by Xotabch1** [comment]
> Hello @Xotabch1, running Dota 2 (for Windows) with Proton is not officially supported, and is out of scope for this issue tracker.
> 
> On the Steam Deck, there should be no compatibility tool selected to use with the game in the per-game properties so that the Dota 2 for Linux client is run inside the Steam Linux Runtime 3.0 container environment. Selecting Steam Linux Runtime in the per-game compatibility options will result in [ValveSoftware/steam-for-linux#9844](https://github.com/ValveSoftware/steam-for-linux/issues/9844).
> 
> Feel free to continue discussing this issue in an unofficial capacity on the compatibility report for the game in the Proton issue tracker ([ValveSoftware/Proton#6631](https://github.com/ValveSoftware/Proton/issues/6631)).

@kisak-valve 

hello guys,
As I understood this guy closed my request and directed me here.
He wrote that dota 2 is not officially supported by Proton, Why?
As I understand, officially Steam deck and dota 2 are from Valve, besides dota 2 has yellow sign which means that it is playable. Am I misunderstanding something?

**Comment by Xotabch1** [comment]
Can sombody explain me what you are talking about ? Like in easy way, what button should I press to play dota 2 successfully on Steam deck?

**Comment by smcv** [comment]
@Xotabch1: This is a report of a specific issue in Steam's handling of compatibility tools, tracked here for the benefit of the Steam developers. It is not a general technical support forum, and the more noise we add to it, the longer it will take for the reported issue to be solved.

If you are affected by this specific issue, then the workaround for it would be:

Dota 2 → Manage (gear wheel icon) → Properties... → Compatibility → Make sure that "Force the use of ..." is **not** checked

If you are having trouble launching Dota 2 on Steam Deck, please open a separate issue or support request with full details, instead of replying to this one.

**Comment by mischiefaaron** [comment]
I had the issue of Aseprite switching over to the Windows version so I had to turn on forced compatibility and set it to the Steam Linux Runtime, but it still says it's v1.0 (Scout) with no other options for Soldier or Sniper. I might be automatically using Sniper for all I know, I don't know how to test for that. I believe my issue is the same one described here, yes?

**Comment by kisak-valve** [comment]
Hello @mischiefaaron, your comment reads like it's related to https://github.com/ValveSoftware/steam-for-linux/issues/9875 instead of this issue report.

**Comment by smcv** [comment]
@mischiefaaron: As far as I can tell, what you are talking about is the opposite of this issue.

This bug report is about games like Dota 2 that specifically declare that they need to be run on Steam Linux Runtime 3.0 (sniper). The bug is that the Steam UI allows Steam Linux Runtime 1.0 (scout) to be selected for those games, but it shouldn't allow that: it isn't going to work, and we shouldn't offer users an option if we don't expect it to succeed.

It sounds as though you are asking about an app/game that, as far as Valve knows, is intended to be run in an environment that is compatible with Steam Runtime 1 (scout). As of 2023, Team Fortress 2 is one of many examples of a game like this. The answer is that it is intentional that you cannot choose to run these games in SLR 2.0 (soldier) or SLR 3.0 (sniper), and it's for a similar reason to this issue report: according to the best information we have available, we would not expect that choice to work correctly. Please see https://github.com/ValveSoftware/steam-for-linux/issues/7430 if you would like to read the technical details of why.

If the specific app/game you are referring to (Aseprite) is one that would benefit from being compiled and run in a Steam Linux Runtime 3.0 (sniper) environment like Dota 2 is, then please ask its developer to contact Valve and ask about getting it switched over. I believe the intention is that this will eventually become a "self-service" thing that any Steam game publisher can do, but for now, it requires intervention from a Valve developer. Battle for Wesnoth, Endless Sky and Retroarch are some examples of open-source games on Steam that have been through this process already.

**Comment by smcv** [comment]
This was mostly fixed in the current Steam client beta cycle (2024-04-xx). The beta branch of the various compatibility tools (versioned as 0.20240415 or newer) is currently required for the change to take effect.

**Comment by smcv** [comment]
This is fixed in the current Steam client beta cycle (2024-12-03), so we can probably close this next time the beta is shipped as stable.

**Comment by smcv** [comment]
> This is fixed in the current Steam client beta cycle (2024-12-03), so we can probably close this next time the beta is shipped as stable.

Confirmed fixed in the [2024-12-04 general-availability Steam client](https://store.steampowered.com/news/collection/steam/?emclan=103582791457287600&emgid=4464851965270032763) (this change didn't make it into the release notes, but it's there).
