### ISSUE TITLE
Apex Legends CPU stalling

### ISSUE THREAD

**Issue by 2A4U** [ValveSoftware/steam-for-linux#9848]
After the big **Steam client update** earlier this month Apex Legends will go from a normal FPS to less than 1 FPS no matter what it is rendering (even in character select screen). Then the FPS returns to normal after a few seconds to half a minute. Then it begins to stall again...and so on.

At the time this bug was introduced there were distro software changes on my end.

Linux utility 'top' is showing no other processes hogging up CPU resources. CPU utilization drops to near 5% during the stall.

There is also continuous disk access while Apex Legends is running.

All other games are not effected.

This does not appear to be a system wide power managment issue as the program glxgears can run normally at the same time Apex Legends is stalling in windowed mode.

Giving Apex Legends a higher CPU priority through 'renice' has no effect on this bug.

#### Steps for reproducing this issue:

1. Start Apex Legends to main menu.
2. Wait.

**Comment by kisak-valve** [comment]
Hello @2A4U, we're tracking issues with games run with Proton on the Proton issue tracker, also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1635084862.

**Comment by 2A4U** [comment]
> Hello @2A4U, we're tracking issues with games run with Proton on the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [ValveSoftware/Proton#4350 (comment)](https://github.com/ValveSoftware/Proton/issues/4350#issuecomment-1635084862).

Except the only software that changed at the time this bug started was Linux Steam Client. I doubt it is a proton issue.
