### ISSUE TITLE
Steam Freezes During Launch

### ISSUE THREAD

**Issue by andrewroark** [ValveSoftware/steam-for-linux#9853]
#### Your system information

* Steam client version (build number or date): Unknown (Steam freezes before being able to check version, but I believe it is the latest version)
* Distribution (e.g. Ubuntu): Ubuntu 23.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12051706/steam-logs.tar.gz)
* GPU: NVIDIA GA104 [GeForce RTX 3070 Lite Hash Rate]

#### Please describe your issue in as much detail as possible:
Expected Behavior: Steam Launches without Freezing
Actual Behavior: Steam Freezes During Launch

I believe the Steam client is up to date because it can check for updates before freezing, and because I also tried uninstalling and reinstalling the client, which failed to resolve the issue. Additionally, restarting my system failed to resolve the issue. I suspect a recent client update caused this issue: the client launched properly in the recent past, without any major system updates. I can confirm the client last launched properly on July 9, 2023, and first failed to launch properly for me on July 13, 2023.

![Screenshot from 2023-07-14 09-36-45](https://github.com/ValveSoftware/steam-for-linux/assets/139568753/10b36f1a-9369-4dd1-b277-d02d3a085262)
![Screenshot from 2023-07-14 09-36-26](https://github.com/ValveSoftware/steam-for-linux/assets/139568753/da5f2ffd-6981-4f2d-b720-f0cfee7a913a)

#### Steps for reproducing this issue:

1. Launch Steam 
2. Application Freezes

**Comment by andrewroark** [comment]
I'm using nvidia-driver-525. Would using a different version resolve the issue?

**Comment by andrewroark** [comment]
After reading issue #9780, running `steam -vgui` properly launches. I can give the following info now:
Steam Client Version: 1689034492
System Information: https://gist.github.com/andrewroark/d7f144491394add8d45cee8c12b19946

**Comment by kisak-valve** [comment]
Looking at your system information, your NVIDIA video driver install is broken and Steam is being forced to fallback to llvmpipe to render at all.

https://gist.github.com/andrewroark/d7f144491394add8d45cee8c12b19946#file-gistfile1-txt-L48
https://gist.github.com/andrewroark/d7f144491394add8d45cee8c12b19946#file-gistfile1-txt-L219-L242
https://gist.github.com/andrewroark/d7f144491394add8d45cee8c12b19946#file-gistfile1-txt-L462-L485

**Comment by andrewroark** [comment]
Thank you, I changed the driver to the nvidia-driver-535, and steam ran properly after a system restart.
