### ISSUE TITLE
Game crashes when opening steam overlay

### ISSUE THREAD

**Issue by AndyGura** [ValveSoftware/steam-for-linux#9854]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1689034492
Steam Client Build Date:  Tue, Jul 11 2:59 AM UTC -08:00
Steam Web Build Date:  Mon, Jul 10 8:48 PM UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): 
Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Counter Strike Global Offensive crashes while playing, when trying to open another user's profile. The image freezes immediately and from this state I did not manage to recover 

#### Steps for reproducing this issue:

1. Start game with other players
2. hold "TAB" to view board with players
3. Left-click on any player
4. In the context menu, press "View Profile".
5. Observe that game freezes

**Comment by kisak-valve** [comment]
Hello @AndyGura, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172 / #9586. Closing as a duplicate.

**Comment by AndyGura** [comment]
Thanks!
