### ISSUE TITLE
Steam UI is only shown hours after opening Steam

### ISSUE THREAD

**Issue by luzfcb** [ValveSoftware/steam-for-linux#9855]
#### Your system information

* Steam client version: 
Steam Version:  1689034492
Steam Client Build Date:  Mon, Jul 10 20:59 UTC -08:00
Steam Web Build Date:  Mon, Jul 10 14:48 UTC -08:00
Steam API Version:  SteamClient020

* Distribution (e.g. Ubuntu): KDE Neon User Edition (is based on Ubuntu 22.04) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12059768/steam-logs.tar.gz)
* GPU: Nvidia GTX 1650 - Driver version 535.54.03

#### Please describe your issue in as much detail as possible:

Steam UI is only shown hours after opening Steam. It's a very strange behavior that started to occur with the new UI Steam version. After I open Steam, the Steam icon is shown in systray, however the UI only shows up randomly hours after that.

The only way I've been able to get steam to show the UI immediately is to start steam via `steam --reset` and login again.

If I fully close Steam and try to open it again in the regular way, the problem occurs again.

Here the logs after starting with steam --reset, closing steam completely and starting steam the regular way
[steam-logs-after-reset-close-and-open-again.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12059811/steam-logs-after-reset-close-and-open-again.tar.gz)

**Comment by kisak-valve** [comment]
Hello @luzfcb, this issue is already being tracked at #9692. Closing as a duplicate.
