### ISSUE TITLE
Context menu on Library entry does nothing

### ISSUE THREAD

**Issue by b0bh00d** [ValveSoftware/steam-for-linux#9864]
#### Your system information

* Steam client version (build number or date):  1689034492
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12065071/steam-logs.tar.gz)`]
* GPU:  NVIDIA 2080 Ti, driver 5.35

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Right-clicking on an installed title (e.g., Valheim) brings up the context management menu, but selecting an option( "Manage > Uninstall", "Properties...", etc.) does nothing.  No secondary windows open, nor is there any indication that anything is happening.

#### Steps for reproducing this issue:

1. Open the "Library" panel
2. Locate an installed title
3. Right-click in the left pane, or click on the gear icon, to open the options panel and select "Properties..."

**Comment by kisak-valve** [comment]
Hello @b0bh00d, this issue is already being tracked at #9273. Closing in favor of the older issue report.
