### ISSUE TITLE
Please stop worsening steam with every single update

### ISSUE THREAD

**Issue by gmod64bit** [ValveSoftware/steam-for-linux#9865]
At this point, steam on gnu/linux is bearly operable at all. Flickering piece of laggy unresponsive shit with too many features that don't work to count. 

Why do you developers do this

**Comment by kisak-valve** [comment]
Hello @gmod64bit, this issue report was closed and locked because it's non-constructive, and reads like you're more interested in venting some frustration instead of giving actionable feedback. This is inappropriate for a public issue tracker.
