### ISSUE TITLE
INCOMING CHAT HIDE MY GAME AND SHOWING CHAT WINDOW

### ISSUE THREAD

**Issue by buncis** [ValveSoftware/steam-for-linux#9866]
#### Your system information

* Steam Version:  1689034492
Steam Client Build Date:  Tue, Jul 11 6:59 AM UTC -08:00
Steam Web Build Date:  Tue, Jul 11 12:48 AM UTC -08:00
Steam API Version:  SteamClient020
* Distribution (e.g. Ubuntu): UBUNTU 22.04.2
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. OPEN STEAM 
2. PLAY DOTA 2
3. GET CHAT
4. IT SHOW THE CHAT ON A NEW WINDOW AND HIDE MY DOTA 2 CLIENT 
4. IT GOES TO DESKTOP  SHOW THE SMALL BOX CHAT WINDOW AND HIDE MY DOTA

**Comment by kisak-valve** [comment]
Hello @buncis, this issue is already being tracked at #5286. Closing as a duplicate.
