### ISSUE TITLE
Steam refuses to update any games/content

### ISSUE THREAD

**Issue by int-72h** [ValveSoftware/steam-for-linux#9869]
#### Your system information

* Steam client version (build number or date): July 10th
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* GPU: AMD 5700XT

#### Please describe your issue in as much detail as possible:
Steam refuses to update any of the games, regardless of DL server or whether I use ``-tcp``. 
Being online and all other functionality seems to work fine - just downloading/updating seems to be affected.
The UI says "No internet connection" on each failed to update game, despite everything else working.
I do have a dns caching tool installed as this might be a solution, but it doesn't do anything in this case.

stdout has this error:
```
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
```

#### Steps for reproducing this issue:

1. Start steam.
2. Notice that it can't update any games.

**Comment by kisak-valve** [comment]
Hello @int-72h, can you share `~/.local/share/Steam/logs/content_log.txt`?

**Comment by int-72h** [comment]
> Hello @int-72h, can you share `~/.local/share/Steam/logs/content_log.txt`?

Sure. It's attached:
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12070134/content_log.txt)

**Comment by int-72h** [comment]
Any update on this?

**Comment by int-72h** [comment]
OK, it turns out my DNS cacher wasn't set up properly, now it is it's working fine.

**Comment by int-72h** [comment]
Nevermind, seems to be unrelated. Happening again even with a correctly configured DNS caching tool.

**Comment by int-72h** [comment]
...Disabling IPv6 seems to fix it.
