### ISSUE TITLE
Steam won't open on Ubuntu 23.04

### ISSUE THREAD

**Issue by cjhelloletsgo** [ValveSoftware/steam-for-linux#9878]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Ubuntu 23.04
* Opted into Steam client beta?: No (Same issue if Yes)
* Have you checked for system updates?: Yes
* GPU: AMD 7900xt

Since the UI update I have only been able to open steam in the terminal, it won't open by clicking on the icon. If I click on the Steam icon a small window will open that says logging in and then loading user data briefly then it will close. The steam icon will appear in the topbar but Steam will never open.

#### Steps for reproducing this issue:

1. Install Steam (.deb)
2. Try to open using gui
3. Steam doesn't open
4. Try to open steam in terminal with command "steam"
5. Works fine
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12100978/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @cjhelloletsgo, this issue is already being tracked at #9383. Closing as a duplicate.
