### ISSUE TITLE
Steam detect wrong battery percentage in dual battery systems

### ISSUE THREAD

**Issue by th1nhhdk** [ValveSoftware/steam-for-linux#9881]
#### Your system information

System Information: https://gist.github.com/th1nhhdk/efb33cd4b8231b53308284c7d66b78cf

* Steam client version (build number or date): `1689034492`
* Distribution (e.g. Ubuntu): `Fedora Linux 38 (Thirty Eight) (64 bit)`
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12102252/steam-logs.tar.gz)
* GPU: Intel

#### Please describe your issue in as much detail as possible:
Steam said that my laptop battery is low (10%), turns out it only checks `battery 2 (external)` percentage, not the combined percentage like I expected, KDE Plasma said that my (combined) battery percentage is 34%

#### Steps for reproducing this issue:

1. Have a ThinkPad T480, or any laptop with dual battery
2. Drain battery 2 (external) down to 10%, while keeping battery 1 (internal) at any percentage
3. Plug & Unplug charger with steam running in the background, it'll said that battery is low (10%)

**Comment by kisak-valve** [comment]
Hello @th1nhhdk, this issue is already being tracked at #7308. Closing as a duplicate.
