### ISSUE TITLE
Steam Won't Open On Linux Mint Cinnamon 21.2 Victoria (Except By Right-clicking & Selecting "Settings")

### ISSUE THREAD

**Issue by romeroFan6268** [ValveSoftware/steam-for-linux#9883]
System Information: [System-Info.odt](https://github.com/ValveSoftware/steam-for-linux/files/12103726/System-Info.odt)

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu):  Linux Mint 21.2 "Victoria" Cinnamon Edition
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12103665/steam-logs.tar.gz)
* GPU: AMD Ryzen 3 5300G with Radeon Graphics × 4

Steam does not open on the new "Linux Mint 21.2 'Victoria' Cinnamon Edition." It won't open (like something is blocking it). The only way I can get Steam to open is by right-clicking and selecting "Settings." Even then, running games can be a hassle. For example, "Dying Light" (which has a native Linux version) takes forever to load (a problem that never happened in "Linux Mint 21.1 'Vera'"). When it does load, it plays fine. However, when I try to quit the game, the game freezes. I had to shut my PC off and restart it as a result (this has happened more than once).  Please help!

#### Steps for reproducing this issue:

1. I click on my Steam Icon.
2.  Steam starts, but refuses to open (unless I right-click on it before trying to click on it normally and select "Settings").  Note: If you try to open it it without right-clicking it, I am forced to exit (close) out of steam.  Then, I right-click Steam and select "Settings."  This apparently bypasses the problem, but it still has issues. 
3.  Dying Light has some video issues, and I cannot close out of the game without the computer crashing.  I am forced to power off my PC.
4. The issue then repeats itself upon starting up the computer (Steam not opening up, except by right-clicking and selecting "Settings").  I even tried signing out and signing back in, but the problem persists.

I hope this helps, and I hope you and everyone at Steam will please come up with a solution.  Thanks, and peace out!

![Steam-Startup-Problem](https://github.com/ValveSoftware/steam-for-linux/assets/140053379/24a5dc66-0c56-4144-911d-21268bfa9d3f)

**Comment by romeroFan6268** [comment]
OK, that works.  I also tried adding the shortcut on the desktop.  Those work!  Then why is the Steam icon acting up with the icon panel and the start menu shortcut?  Those do not work.  Why?

**Comment by kisak-valve** [comment]
Thanks, that makes this issue the same as #9383. (See https://github.com/ValveSoftware/steam-for-linux/issues/9383#issuecomment-1584898530).

Closing as a duplicate.

**Comment by romeroFan6268** [comment]
Thanks!  :)

**Comment by magic4you94** [comment]
I'm having issues where steam won't load and is invisible after installing, I'm new to Linux mint Victoria and I don't know if I'm missing something or what, Can anyone help

**Comment by magic4you94** [comment]
Steam won't open after installing and it's invisible in Linux mint 21.2, can anyone help?

**Comment by Unimperfect** [comment]
> I'm having issues where steam won't load and is invisible after installing, I'm new to Linux mint Victoria and I don't know if I'm missing something or what, Can anyone help? I've tried opening in terminal no help, tried everything I've found to tell me how to get it installed but I still have same issue

I am having the exact same issue. I tried doing a clean install and steam was the first thing I installed after doing a system update, and I get the same issue. Pretty frustrating, as I would like to move away from Windows, and one of the main reasons is for gaming. I had heard that Linux Mint "just works".

**Comment by romeroFan6268** [comment]
> Steam won't open after installing and it's invisible in Linux mint 21.2, can anyone help?

I had that same issue as well.  I fixed it by doing these steps.  Open the "Files" folder on the bottom left of the screen.  Once that opens, click the left arrow underneath the "Go" button.  This will show what appears to be a disk with a hole in it.  Click it.
![Steam Fix - Part 1](https://github.com/ValveSoftware/steam-for-linux/assets/140053379/cb25a7b3-25d0-469a-9a24-dbed73d57e60)
Then click the folder "usr," then "share."  Then right-click on the "applications" folder and select "Open as Root."  Type in your password to continue.  Then scroll down until you see the Steam Icon.  Right-click it and select "Text Editor." From there, scroll down until you come to two lines that say... 


PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true

Change these to false, so it now says:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false

![Steam Fix for Linux Mint](https://github.com/ValveSoftware/steam-for-linux/assets/140053379/22fffa07-fa48-4e8e-9011-2cdbe33a770e)


Then choose File, and save.  Then close out of all the folders.  Steam should now work a-okay... ;)

**Comment by magic4you94** [comment]
Unfortunately it didn't work for me, thanks though 
 
  On Wed, Nov 8, 2023 at 10:37 PM, ***@***.***> wrote:   



Steam won't open after installing and it's invisible in Linux mint 21.2, can anyone help?


I had that same issue as well. I fixed it by doing these steps. Open the "Files" folder on the bottom left of the screen. Once that opens, click the left arrow underneath the "Go" button. This will show what appears to be a disk with a hole in it. Click it.

Then click the folder "usr," then "share." Then right-click on the "applications" folder and select "Open as Root." Type in your password to continue. Then scroll down until you see the Steam Icon. Right-click it and select "Text Editor." From there, scroll down until you come to two lines that say...

PrefersNonDefaultGPU=true
X-KDE-RunOnDiscreteGpu=true

Change these to false, so it now says:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false



Then choose File, and save. Then close out of all the folders. Steam should now work a-okay... ;)

**Comment by romeroFan6268** [comment]
I'm sorry to hear that. The only other scenario I can think of is to back all your important files to a USB thumb drive, and do a complete clean install of the previous version of Linux Mint 21.1 "Vera." It's basically the version people liked, before everything went to heck with version 21.2 Victoria...

**Comment by romeroFan6268** [comment]
There is one more thing, actually.  After completing those steps I mentioned, did you exit out of Steam (by right-clicking the Steam icon on the panel and choosing "Exit Steam"), and then going back in?  I think I did that and that finally made it work...

**Comment by magic4you94** [comment]
Thanks, I'll try that if I can figure out how to do it 
 
  On Sat, Nov 11, 2023 at 10:27 PM, ***@***.***> wrote:   


I'm sorry to hear that. The only other scenario I can think of is to back all your important files to a USB thumb drive, and do a complete clean install of the previous version of Linux Mint 21.1 "Vera." It's basically the version people liked, before everything went to heck with version 21.2 Victoria...

**Comment by romeroFan6268** [comment]
Sure thing.  Again, before doing that, after finishing all those steps I mentioned, did you right-click the Steam icon on the Icon Panel and select "Exit Steam," and then try go back into it?  I think that's what finally refreshed it and made it work...

**Comment by magic4you94** [comment]
No I didn't do that I closed out of everything and restarted it

 
 
  On Sat, Nov 11, 2023 at 10:35 PM, ***@***.***> wrote:   


Sure thing. Again, before doing that, after finishing all those steps I mentioned, did you right-click the Steam icon on the Icon Panel and select "Exit Steam," and then try go back into it? I think that's what finally refreshed it and made it work...

**Comment by romeroFan6268** [comment]
Oh, OK.  I can't quite remember if that's what I did, too.  I just know that changing those two lines was the key to getting it to work for me (I read it in a forum somewhere).

**Comment by romeroFan6268** [comment]
You know, changing it so the text editor for Steam read like this:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false

Those changes made it work.  You may wanna look around on the forums here for that.  I know that somewhere that was the key to get it to work right for me (I can't remember where, sorry)>

**Comment by magic4you94** [comment]
Yes I did that just like you said and it didn't work

 
 
  On Sat, Nov 11, 2023 at 10:43 PM, ***@***.***> wrote:   


You know, changing it so the text editor for Steam read like this:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false

Those changes made it work. You may wanna look around on the forums here for that. I know that somewhere that was the key to get it to work right for me (I can't remember where, sorry)>

**Comment by romeroFan6268** [comment]
I'm really sorry to hear.  I don't why that is, it worked for me.  Well, the only thing I can think of is just to roll back to the previous version of Linux Mint.  Sorry... :(

I know I mentioned it.  The only reason I brought it up is because maybe someone else managed to get it to work, but in a different way (with those two lines adjusted like that).  I remember reading those two lines before in numerous forums.  I know that some methods vary.  Just wanna give you the heads-up is all... :)

**Comment by romeroFan6268** [comment]
Here's a Youtube video on how to install Linux Mint with step-by-step instructions (you'll need a USB drive): https://www.youtube.com/watch?v=eI7QQqnV1P8

Here is Etcher: https://etcher.balena.io/

(Remember after you install Etcher, you will need to right-click it and select "Properties."  Then select "Permissions" and check the box that says "Allow executing file as a program."  You can now double-click Etcher to start using it.

Finally, here's the version of Linux Mint 21.1 "Vera": https://www.linuxmint.com/edition.php?id=302

(choose any from one of the mirrors, I'd recommend advancedhosters (the 5th option).

You'll wanna be sure to back up all your important work on another flash drive.  Otherwise, you'll lose all your work.

I hope this helps... :)

**Comment by magic4you94** [comment]
Thanks

 
 
  On Sat, Nov 11, 2023 at 11:18 PM, ***@***.***> wrote:   


Here's a Youtube video on how to install Linux Mint with step-by-step instructions (you'll need a USB drive): https://www.youtube.com/watch?v=eI7QQqnV1P8

Here is Etcher: https://etcher.balena.io/

(Remember after you install Etcher, you will need to right-click it and select "Properties." Then select "Permissions" and check the box that says "Allow executing file as a program." You can now double-click Etcher to start using it.

Finally, here's the version of Linux Mint 21.1 "Vera": https://www.linuxmint.com/edition.php?id=302

(choose any from one of the mirrors, I'd recommend advancedhosters (the 5th option).

You'll wanna be sure to back up all your important work on another flash drive. Otherwise, you'll lose all your work.

I hope this helps... :)

**Comment by romeroFan6268** [comment]
Sure thing.  I hope this helps... ;)

Yeah, it seems some will have to stay on Linux Mint 21.1 "Vera," until Steam or Linux Mint (whoever is at fault) fixes this.  Uffda... :(

**Comment by romeroFan6268** [comment]
> Replying to [#9883 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/9883#issuecomment-1807007191)
> Thanks

Well, did you manage to successfully roll back to Linux Mint 21.1 "Vera," magic4you94?  Just wanna make sure everything went well and everything... :)

**Comment by romeroFan6268** [comment]
Well, I see that Linux Mint 21.3 "Virginia" is out.  However, I'd hold off on upgrading that (and version 21.2 "Victoria"), until either Valve or Linux Mint developers fix this issue.  I'm not sure if it even _**has**_ been fixed in the newest version.  Has it?  A response would be much appreciated, please...

**Comment by romeroFan6268** [comment]
> > Steam won't open after installing and it's invisible in Linux mint 21.2, can anyone help?
> 
> I had that same issue as well. I fixed it by doing these steps. Open the "Files" folder (also known as the Home Folder) on the bottom left of the panel of the screen. Once that opens, click the left arrow underneath the "Go" button. This will show what appears to be a disk with a hole in it. Click it.
> 
> ![Steam Fix - Part 1](https://private-user-images.githubusercontent.com/140053379/281621840-b2c2978e-af0b-4d77-84f4-37925242a248.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU3OTgsIm5iZiI6MTcwNTY0NTQ5OCwicGF0aCI6Ii8xNDAwNTMzNzkvMjgxNjIxODQwLWIyYzI5NzhlLWFmMGItNGQ3Ny04NGY0LTM3OTI1MjQyYTI0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2UxZmRkYTI3ZGZkMzFhNzQxODFkOTk4N2M2YWIzZjI5ZDI5YTM2MTc3YmMyYzJlYzVkOTI3MDc0MGNjNDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Okcr1TXkEiu_mTHj2HP09FhqsBUaUD8sJmUgDTwSfQ)
> 
> Then click the folder "usr," then "share." Then right-click on the "applications" folder and select "Open as Root." Type in your password to continue. Then scroll down until you see the Steam Icon. Right-click it and select "Open With > Text Editor." From there, scroll down until you come to two lines that say...
> 
> PrefersNonDefaultGPU=true X-KDE-RunOnDiscreteGpu=true
> 
> Change these to false, so it now says:
> 
> PrefersNonDefaultGPU=false X-KDE-RunOnDiscreteGpu=false
> 
> ![Steam Fix for Linux Mint](https://private-user-images.githubusercontent.com/140053379/281621889-6c187513-e32e-40e3-9a2c-93cb5c9fa60f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDU3OTgsIm5iZiI6MTcwNTY0NTQ5OCwicGF0aCI6Ii8xNDAwNTMzNzkvMjgxNjIxODg5LTZjMTg3NTEzLWUzMmUtNDBlMy05YTJjLTkzY2I1YzlmYTYwZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTA1YjNmZTYxMzBjNGE5MTVlODllMTE3MTc3MzQ4OTNhNWVjMTQ1NWFiMWMwMzJhZmYyMTc3MTA4OTJkYjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QduviYnxj8I-QDuGyuVQjPvS5ZLehDzgHs8EhsOgab8)
> 
> Then choose File, and save. Then close out of all the folders. Steam should open now... ;)

I'd like to post an update: I recently uninstalled and reinstalled Steam.  The above method worked for me (I hope it does for you, too).  Also, I was finally able to get the PC game "Dying Light" to run properly by doing the following:

1) Right-clicking "Dying Light" in the Steam library and selecting "Properties."
2) Select the "Compatibility" tab and check the box that says "Force the use of a specific Steam Play compatibility tool."
3) Click the blue down-arrow and select the latest stable version: Proton 8.0-4
4) Wait for "Dying Light" to finish updating and that's it!  You're all done... :)

**Comment by magic4you94** [comment]
I still haven't gotten mine to work even by going by people's steps they said they used and I've tried several ways.  
 
  On Sat, Jan 13, 2024 at 3:58 PM, ***@***.***> wrote:   


Well, I see that Linux Mint 21.3 "Virginia" is out. However, I'd hold off on upgrading that (and version 21.2 "Victoria"), until either Valve or Linux Mint developers fix this issue. I'm not sure if it even has been fixed in the newest version. Has it? A response would be much appreciated, please...

**Comment by magic4you94** [comment]
Nothing has worked for me, everything I've tried has not worked  
 
  On Fri, Dec 15, 2023 at 5:02 PM, ***@***.***> wrote:   



Replying to #9883 (comment)
Thanks


Well, did you manage to successfully roll back to Linux Mint 21.1 "Vera," magic4you94? Just wanna make sure everything went well and everything... :)

**Comment by romeroFan6268** [comment]
> Nothing has worked for me, everything I've tried has not worked  On Fri, Dec 15, 2023 at 5:02 PM, ***@***.***> wrote: Replying to #9883 (comment) Thanks Well, did you manage to successfully roll back to Linux Mint 21.1 "Vera," magic4you94? Just wanna make sure everything went well and everything... :) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

When you first start your computer, did you immediately press "F10" (or "F12," depending on the PC)?  This will get you into the BIOS settings.  You'll need to disable "Secure Boot" in order for the computer to detect the flash drive containing the previous Linux Mint version.

**Comment by romeroFan6268** [comment]
I mean, were you able to roll back to the previous Linux Mint version?  "Linux Mint 21.1 Vera" was the last stable version for me for Steam, before things went haywire...

**Comment by magic4you94** [comment]
Yes I did that

 
 
  On Fri, Jan 19, 2024 at 2:26 AM, ***@***.***> wrote:   



Nothing has worked for me, everything I've tried has not worked On Fri, Dec 15, 2023 at 5:02 PM, @.> wrote: Replying to #9883 (comment) Thanks Well, did you manage to successfully roll back to Linux Mint 21.1 "Vera," magic4you94? Just wanna make sure everything went well and everything... :) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>


When you first start your computer, did you immediately press "F10" (or "F12," depending on the PC)? This will get you into the BIOS settings. You'll need to disable "Secure Boot" in order for the computer to detect the flash drive containing the previous Linux Mint version.

**Comment by romeroFan6268** [comment]
> Yes I did that On Fri, Jan 19, 2024 at 2:26 AM, ***@***.***> wrote: Nothing has worked for me, everything I've tried has not worked On Fri, Dec 15, 2023 at 5:02 PM, @.> wrote: Replying to #9883 (comment) Thanks Well, did you manage to successfully roll back to Linux Mint 21.1 "Vera," magic4you94? Just wanna make sure everything went well and everything... :) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> When you first start your computer, did you immediately press "F10" (or "F12," depending on the PC)? This will get you into the BIOS settings. You'll need to disable "Secure Boot" in order for the computer to detect the flash drive containing the previous Linux Mint version. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

OK.  Just to make sure, you were able to successfully install Linux Mint 21.1 "Vera" on your computer?  I just need to make sure, so I can try and find a solution.  I'm new the Linux world as well, sorry...

**Comment by romeroFan6268** [comment]
Well, if rolling back to Linux Mint 21.1 "Vera" did not work, it must be something with Steam.  It seems the new update that Steam implemented did not react well with some PCs...

Have you thought about getting a Steam Deck?  You can play all your games on there, plus you can connect it to your PC (provided you get the Dock Station, which is sold separately).  That might work until Valve fixes this issue (or the Linux Mint developers -- whoever is at fault).

Then again, that pretty much defeats the purpose of having a PC where you are supposed to game to your heart's content.  I'll look around and see if there are other solutions.  That said, those Steam Decks are very good to have...

**Comment by romeroFan6268** [comment]
Well, it appears that the newest update makes it where the method I mentioned -- changing the two lines in Steam setup to:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false

Well, now it only works once, and then it quits for good. I have no idea why... uffda...

I'm suspecting that either Linux Mint, or Steam, or both are at fault.  I have no idea which, sorry... :( 

I can only use the Steam Desktop icon to open it once (if I'm lucky). Then it quits. Same goes for opening it in the Terminal (as well as right-clicking the Steam Icon on the Panel and selecting "Settings").

I also checked to make sure I exited out of Steam, before trying again... to no avail...

**One bright spot: if you restart the computer and type "Steam" in the Terminal again, I found out it that it will work again on my PC. Thank heavens...**

Very complicated to run, you know...

It seems over time, Steam wants us to open it less and less. I don't know why. A lot of us don't wanna switch to Ubuntu to run Steam. Also, from what I've heard, some people are now having issues on there as well.

Even "Minigalaxy" (which is basically the Linux version for GOG Galaxy) does not have any issues opening up...

**Comment by romeroFan6268** [comment]
Well, it appears that the newest update makes it where the method I mentioned -- changing the two lines in Steam setup to:

PrefersNonDefaultGPU=false
X-KDE-RunOnDiscreteGpu=false

Well, now it works only once and then quits for good.  I have no idea why...

Also, the start menu application shortcut for Steam does not work either...

**Now, the only ways I can get it to work is by typing in "Steam" in the terminal, clicking the Steam desktop icon, or by right-clicking the Steam icon on the Panel and selecting "Settings."  It will not open any other way (at least none that I know about).**  

Ay-ya-ya-ya-yai.  Such a rigmarole trying to get Steam to work on Linux Mint... uffda... :(


It seems over time, Steam wants us to open it less and less.  I don't know why.  A lot of us don't wanna switch to Ubuntu to run Steam.  Plus, from what I've heard, some people are even having problems on there as well...

Even "Minigalaxy" (which is basically the Linux version for GOG Galaxy) does not have any issues opening up...

**Comment by romeroFan6268** [comment]
OK, I finally got mine to work on Linux Mint using the following method:

![Linux Mint Invisible Fix](https://github.com/user-attachments/assets/8496b8dd-9804-4f89-b8a8-49630829f29d)

Special thanks to the user Greeedling for addressing this.  You can read more about this issue and other methods here: https://github.com/ValveSoftware/steam-for-linux/issues/10532

Hope this helps... :+1:
