### ISSUE TITLE
[Manjaro] Steam crashes on Startup due to SteamVR

### ISSUE THREAD

**Issue by Arzakon87** [ValveSoftware/steam-for-linux#9885]
#### Your system information

* Steam client version: 1.0.0.78-2
* Distribution: Manjaro 23 / Kernel 6.1.38'1
* Opted into Steam client beta?: Cannot remember, quite honestly, but I'd say no.
* Have you checked for system updates?: Yes
* Steam Logs: Attached.
* GPU: Nvidia GeForce RTX 2060 (Drivers updated to proprietary Nvidia Drivers, v.535)

#### Please describe your issue in as much detail as possible:
For a week or so, since the latest update, Steam won't launch. It starts, verifies the installation and crashes. By running steam on the Terminal I've checked that whenever I try to run it, it says that it has failed to start SteamVR since it's not installed, and it crashes. I've never checked any option to use SteamVR and trying to install any libraries for SteamVR support hasn't solved the issue either. I've checked GitHub, Steam Forums and Manjaro Forums for a while but I haven't been able to find any solution, and I've tried many (resetting Steam, clearing the .steam folder and reinstalling from scratch, checking for additional libraries, running it with -vgui), but nothing seems to work. Any help would be greatly appreciated!

#### Steps for reproducing this issue:

1. Start Steam, either through the terminal or the shortcut.
2. Proceed to verify the installation successfully.
3. Crash when it tries to initialize SteamVR.

Screenshot of the crash and Steam logs attached.

![Steam_terminal](https://github.com/ValveSoftware/steam-for-linux/assets/140083324/56cb8421-b039-4ab7-90af-c77f2ede1f21)
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111546/bootstrap_log.txt)
[cef_log.previous.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111547/cef_log.previous.txt)
[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111548/cef_log.txt)
[client_networkmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111549/client_networkmanager.txt)
[configstore_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111550/configstore_log.txt)
[connection_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111551/connection_log.txt)
[console_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111552/console_log.txt)
[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111553/content_log.txt)
[controller_ui.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111554/controller_ui.txt)
[shader_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111555/shader_log.txt)
[steamui_html.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111556/steamui_html.txt)
[steamui_system.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111557/steamui_system.txt)
[steamui_update.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111558/steamui_update.txt)
[steamwebhelper.log](https://github.com/ValveSoftware/steam-for-linux/files/12111559/steamwebhelper.log)
[systemaudiomanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111560/systemaudiomanager.txt)
[systemdisplaymanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111561/systemdisplaymanager.txt)
[systemdockmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111562/systemdockmanager.txt)
[systemmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111563/systemmanager.txt)
[systemperfmanager.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111564/systemperfmanager.txt)
[transport_client.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111565/transport_client.txt)
[transport_steamui.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111566/transport_steamui.txt)
[webhelper.txt](https://github.com/ValveSoftware/steam-for-linux/files/12111568/webhelper.txt)

**Comment by kisak-valve** [comment]
Hello @Arzakon87, `Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.` in your screenshot is the key detail here, and not related to SteamVR.

This issue is already being tracked at #9805. Closing as a duplicate.

**Comment by Arzakon87** [comment]
The solution on the other issue worked! Thanks!
