### ISSUE TITLE
Every other character inputted into a chat through the in-game overlay doesn't register

### ISSUE THREAD

**Issue by OpenSauce04** [ValveSoftware/steam-for-linux#9886]
#### Your system information

* Steam client version (build number or date): 20/07/2023
* Distribution (e.g. Ubuntu): Gentoo (gentoo-dist kernel)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12114397/steam-logs.tar.gz)

* GPU: Nvidia RTX 3060ti

#### Please describe your issue in as much detail as possible:
Every even number character typed into a chat window inside of the in-game overlay is completely ignored, and the character you entered is not appended to the chat message. If a message is copy-pasted into the chat, it works just fine

#### Steps for reproducing this issue:

1. Run any game
2. Open overlay with shift+tab
3. Attempt to type into a chat window
4. End up typing "hlowrd" instead of "hello world"

**Comment by kisak-valve** [comment]
Hello @OpenSauce04, this issue is already being tracked at #9325. Closing as a duplicate.
