### ISSUE TITLE
Steam Client enter crash loop when launching via dock

### ISSUE THREAD

**Issue by spukiitv** [ValveSoftware/steam-for-linux#9891]
#### Your system information

* Steam client version (build number or date): `Beta, 19-07-2023 (July 19), Debian Package`
* Distribution: `Pop!_OS 22.04 LTS`
* Opted into Steam client beta?: `Yes, as of 21-07-2023 (July 21)`
* Have you checked for system updates?: `No`
* Steam Logs: [`steam-logs.tar.gz`](https://github.com/ValveSoftware/steam-for-linux/files/12131380/steam-logs.tar.gz)
* GPU: `Mesa Intel Arc A370M (DG2)`

#### Please describe your issue in as much detail as possible:

What I expected to happen:

Launching steam via the dock would launch steam to the Library page (as I've configured).

What did happen:

Steam would launch in tray, but UI would keep crashing and re-launching.

This would happen even when launching through the extra menu via any option other than settings (mentioned below).

#### Notes

Launching steam via the terminal or opening to settings seems to mitigate the issue completely until steam is fully shut down.

I know about [Issue #9381](https://github.com/ValveSoftware/steam-for-linux/issues/9381), however the solution (via terminal), and what I've used for now, is not ideal.

Issue does seem to persist on flatpak (Though I would still prefer to use the debian package).

#### Steps for reproducing this issue:

Via dock (Main Issue)

1. Launch steam via the dock simply.

Via terminal

1. Open terminal
2. Launch steam via command. `steam`

Via extra menu to settings

1. Secondary Click the steam icon in dock to access the extra menu.
2. Click "Settings"

**Comment by kisak-valve** [comment]
Hello @spukiitv, this issue is already being tracked at #9383. (Take note of https://github.com/ValveSoftware/steam-for-linux/issues/9383#issuecomment-1584898530.)

Closing as a duplicate.
