### ISSUE TITLE
Steam "browse folder" function opens Visual Studio Code instead of the file manager.

### ISSUE THREAD

**Issue by Veprovina** [ValveSoftware/steam-for-linux#9897]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Arch linux using Gnome
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12137593/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD: AMD Ryzen 5 5600g igpu

#### Please describe your issue in as much detail as possible:
Steam opens right click -> Manage -> Browse local files in Visual Studio Code instead of Nautilus. 
For some reason, Steam (native) started seeing Visual Studio Code (flatpak) as the file manager program. 
This happens in both stable and beta.

It also happens when going to settings - storage, then browsing from there, and it happens in big picture mode too.

#### Steps for reproducing this issue:

1. Right click on a game in library
2. Click "Manage"
3. Click "Browse local folders"

or

1. Click Steam menu
2. Click Settings
3. Got to Storage
4. Click the ... icon, then Browse

**Comment by kisak-valve** [comment]
Hello @Veprovina, this is the a near match to #9560. The Steam client is now calling xdg-desktop-portal for this and that has been configured to use vscode similar to https://github.com/flatpak/xdg-desktop-portal/issues/842.

This configuration is user choice and not a Steam client bug.
