### ISSUE TITLE
Half Life does not respect -noborder

### ISSUE THREAD

**Issue by kevincox** [ValveSoftware/steam-for-linux#990]
When starting half-life with `-window -noborder -w $width -h $height` it still displays a border around the window.

This is really annoying on my multi-monitor setup because in fullscreen mode it fullscreens on my secondary monitor.  This means that I would have to play with my head turned the entire time which isn't very comfortable.  If I could convince it to fullscreen on the proper monitor it would be a work-around but I would still prefer playing windowed with no border.

**Comment by jean-knapp** [comment]
-noborder does not seem to work with Windows 10. Sure, it removes the Title bar, but it still displays a small border. 
![image](https://user-images.githubusercontent.com/54725233/82157658-d9f8fa80-9850-11ea-9884-e5c239822a2f.png)
![image](https://user-images.githubusercontent.com/54725233/82157668-ea10da00-9850-11ea-96aa-b2d188b75026.png)
