### ISSUE TITLE
steam fails to start

### ISSUE THREAD

**Issue by Dialgatrainer02** [ValveSoftware/steam-for-linux#9901]
#### Your system information

* Steam client version (build number or date): 1.0.0.78-1
* Distribution (e.g. Ubuntu): arch linux
* Opted into Steam client beta?: no 
* Have you checked for system updates?: yes
* Steam Logs: (https://github.com/ValveSoftware/steam-for-linux/files/12143508/steam-logs.tar.gz)`]
* GPU: optimus laptop but running on intel igpu

#### Please describe your issue in as much detail as possible:
steam is failing to lauch after an update when i run it fom cli i get errors about steam vr and when i run it with gdb i get this https://gist.github.com/Dialgatrainer02/ef59e444c242c76ec38af51cd723909c 

#### Steps for reproducing this issue:

1. install steam and 32 bit libs from extra repo 
2. run steam from cli
3. see error about steam vr

i have checked that my locales are correct and i have blanked my ld preload so it dosent use any non standard lib i have forced a reinstall by wipingm.local/share/Steam it redownloaded everything tried to run and failed

**Comment by kisak-valve** [comment]
Hello @Dialgatrainer02, `Assertion 'device' failed at src/libsystemd/sd-device/device-private.c:103, function device_get_tags_generation(). Aborting.` in your log makes this the same issue as #9805, which is a distro packaging issue.

Closing as a duplicate.
