### ISSUE TITLE
All menu windows become visible if steam started with no monitor

### ISSUE THREAD

**Issue by tutacat** [ValveSoftware/steam-for-linux#9902]
#### Your system information

* Steam client version (build number or date): client 1689034492 (web 1689043680)
* Distribution (e.g. Ubuntu): Fedora (XWayland)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
* GPU: AMD
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12145221/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/16363617/7922a032-79ff-401e-a9ed-788002a84ef1)
* Each menu window (which should be invisible and borderless) becomes visible and bordered, due to an error when starting steam without a monitor connected.

#### Steps for reproducing this issue:

1. Turn off or disconnect your monitor
2. Open Steam
4. Reconnect your monitor
5. See all the menu windows visible with a border, instead of hidden

**Comment by kisak-valve** [comment]
Hello @tutacat, this issue is already being tracked at #9786. Since your issue report adds some more details that could help a Steam dev ponder the issue, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/steam-for-linux/issues/9786#issuecomment-1647858891.
