### ISSUE TITLE
Terminal pops up when clicking anything steam apps and will only start when closing terminal

### ISSUE THREAD

**Issue by PythonSnake-lang** [ValveSoftware/steam-for-linux#9905]
#### Your system information

* Steam client version (build number or date): Cant find
* Distribution (): Kali
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/):I start portal 2 and then a blank terminal called package install and it only works when i close it

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @PythonSnake-lang, sorry, but Kali Linux is not supported here because it's contradictory to the fundamental goals of the distribution, which focuses on security testing and is not intended to be used as a general purpose desktop environment.

**Comment by PythonSnake-lang** [comment]
ok
