### ISSUE TITLE
Steam uses 2x scaling by default, and it shouldn't

### ISSUE THREAD

**Issue by lnicola** [ValveSoftware/steam-for-linux#9908]
#### Your system information

* Steam client version (build number or date): steam-1.0.0.78-1 / 1689034492
* Distribution: Fedora 38
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12167933/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

Steam starts at 2x scaling, but my system is not configured for that. I'm running GNOME on Wayland.

From `webhelper.txt`: `ThreadSetForceDeviceScaleFactors 1.000000 * 2.000000 = 2.000000`

Also:

```
# https://github.com/ValveSoftware/steam-for-linux/issues/9466
$ gsettings get org.gnome.desktop.interface scaling-factor
uint32 0
$ gsettings get org.gnome.desktop.interface text-scaling-factor 
1.0
$  xrdb -query | grep Xft.dpi
Xft.dpi:	96
$ echo $GDK_SCALE

```

and

![image](https://github.com/ValveSoftware/steam-for-linux/assets/308347/079efbf8-c7a5-4131-a7cc-c54824639cac)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/308347/c3767405-70d9-459b-9cb6-04fa056a10d2)

Setting `LC_ALL=C` has no effect, but running `steam -forcedesktopscaling 1` does what it's supposed to (runs without scaling).

**Comment by kisak-valve** [comment]
Hello @lnicola, this issue is already being tracked at #5362. Closing as a duplicate.
