### ISSUE TITLE
Incessant updating

### ISSUE THREAD

**Issue by Kylemaul** [ValveSoftware/steam-for-linux#9909]
* Steam client version (build number or date): 
* Steam Version:  1690257686
Steam Client Build Date:  Mon, Jul 24 2:50 PM UTC -08:00
Steam Web Build Date:  Mon, Jul 24 7:50 PM UTC -08:00
Steam API Version:  SteamClient020
* Distribution:  Mint (cinnamon::victoria)
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

Steam is making trivial (<1MB each?) updates to ~30 games every time Steam restarts--if I'm not mistaken, several of the games with these 'trivial updates" are 'repeat offenders'...what is going on??**

(relevant excerpts from Steam support chat):

I understand how automatic updating works--I've been using Steam for almost 2 decades lol. This means I also realize that this is not 'normal' at all. -Every- time Steam restarts it picks ~30 games (selection seems random) and updates them with very small updates --almost feels like artwork updates, but idk what their exact contents are. Something to do with Vulkan maybe? Is Vulkan or something else doing all these minor 'updates'? Is Steam having issues registering updates as having been done / needing to be done? fwiw, there are some more 'regular' or 'legitimate' types of updates that are queuing amongst all these 'trivial' ones.

I understand that a certain amount of 'handshaking' must occur, but Steam is fast becoming that awkward type that doesn't know when to stop. If it is functional, (Vulkan preprocessing? other?) well then, I understand--wish it was all a lot more 'above board' tbh, but I get that 'dumbing things down' can be a mercy of its own. In this case, my preference would be to let Steam take care of whatever it is trying to do all at once (e.g. overnight) instead of being a pita every time it launches.
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12168311/steam-logs.tar.gz)

If there is a way to get these 'updates' out of the way all at once, I'm all for that--even if its means I can't use Steam or play games for a day or two...
Which brings me to a final saving grace for this situation. Which is that I have a fairly large game library, and given that I'm now using Linux, there may be minor updates/tweaks to ported games being released at this rate...is -this- what's going on?? 

If there is a way to get these 'updates' out of the way all at once, I'm all for that--even if its means I can't use Steam or play games for a day or two...
Which brings me to a final saving grace for this situation. Which is that I have a fairly large game library, and given that I'm now using Linux, there may be minor updates/tweaks to ported games being released at this rate...is -this- what's going on?? 

#### Steps for reproducing this issue:
1.  launch Steam

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12168315/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @Kylemaul, what you've described are incremental updates to the shader pre-cache of each of these games.

This is the current expected behavior of that subsystem of Steam as more shaders are seen used by the various games over time. You do have the choice of disabling this subsystem if you don't want it at `Steam` -> `Settings` -> `Downloads` -> `Enable Shader Pre-caching` checkbox.

This general topic is already being tracked at #8076. Closing in favor of the older issue report.

**Comment by coreybruce** [comment]
I notice this also, every time I open Steam I get shader cache updates between a few mb to a gb or more and it's kinda annoying how it does this on every launch. it's not like I am opening Steam every few weeks or month  or anything either to make this happen

![Screenshot from 2023-07-27 13-45-33](https://github.com/ValveSoftware/steam-for-linux/assets/8393780/47849bc9-c19e-49c1-be9c-e535fca4e1de)
