### ISSUE TITLE
Steam client not clearing created resources after closing 

### ISSUE THREAD

**Issue by reallygoodnickname** [ValveSoftware/steam-for-linux#9910]
#### Your system information

* Steam client version (build number or date): 1690257686 (Mon, Jul 24 9:50 PM UTC -08:00)
* Distribution (e.g. Ubuntu): Debian GNU/Linux trixie/sid (64 bit)
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD Radeon RX 470 Graphics

#### Please describe your issue in as much detail as possible:
After starting and shutting down Steam, strange behavior was noticed: 

The amount of RAM consumed by the system did not decrease (although it should, since the program was closed). After a little investigation, it was revealed that the steam client creates some files in shared memory (`/dev/shm`) during startup, but does not delete them after closing. Each subsequent start of Steam creates new such files, which further increases the memory consumption.

#### Steps for reproducing this issue:
1.  Open steam client and let it load
2.  Close steam client (`Steam -> Exit`)

**Comment by kisak-valve** [comment]
Hello @reallygoodnickname, this issue is already being tracked at #9233. Closing as a duplicate.
