### ISSUE TITLE
CSGO buttons appear outside of the UI

### ISSUE THREAD

**Issue by diego-crespo** [ValveSoftware/steam-for-linux#9912]
#### Your system information

* Steam client version (build number or date): 
**Steam Version:**  1689034492
**Steam Client Build Date:**  Mon, Jul 10 7:59 PM UTC -08:00
**Steam Web Build Date:**  Mon, Jul 10 1:48 PM UTC -08:00
**Steam API Version:**  SteamClient020
* Distribution (e.g. Ubuntu): 
**DISTRIB_ID**="ManjaroLinux"
**DISTRIB_RELEASE**="23.0.0"
**DISTRIB_CODENAME**="Uranos"
**DISTRIB_DESCRIPTION**="Manjaro Linux" 

I also was able to reproduce this with Pop!_OS 22.04
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD
Ryzen2700X
Nvidia 1080ti

#### Please describe your issue in as much detail as possible:
The buttons to apply changes to the UI and Play button on CSGO for matches are not present on a fresh install of Pop!_OS or Manjaro. Have to add -fullscreen launch option on csgo to get them to appear. Happens with the default settings of Windowed mode, 16x9 aspect ratio, and 1920x1080 resolution. Here are the specs of my computer and the output of /etc/lsb-release
![cs_go_no_play_button](https://github.com/ValveSoftware/steam-for-linux/assets/18536672/0825c61a-4651-4238-a641-3adf5693196a)

Currently the fix is to add this to the launch options -fullscreen
#### Steps for reproducing this issue:

1. Install latest Manjaro or Pop!_OS
2. Download Steam
3. Download CSGO
4. Launch CSGO

**Comment by kisak-valve** [comment]
Hello @diego-crespo, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/2004. Closing as a duplicate.
