### ISSUE TITLE
Counter Strike randomly crashes without an error message

### ISSUE THREAD

**Issue by lobneroO** [ValveSoftware/steam-for-linux#9913]
#### Your system information
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12176840/steam-logs.tar.gz)

* Steam client version (build number or date):  1689034492
* Distribution (e.g. Ubuntu):  Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: AMD 6650 XT

#### Please describe your issue in as much detail as possible:
CS GO has started crashing randomly on Arch Linux / Wayland / Jack ever since Big Picture was released. AMD Ryzen 5800x, Radeon RX 6650 XT.
I have had multiple kernel and driver versions, current mesa is 23.1.3-2, current kernel is 6.4.3-arch1-1

There is no error message, no log that I can see. It just randomly crashes, sometimes in game, sometimes on start up, sometimes in lobby. More often than not it crashes when opening the overlay / getting a message or invite. It crashes without that, though, too. It had worked fine before the Big Picture update. Sometimes it works for 2-3 days without problems, sometimes it crashes 10 times in one competetive short match.
Sometimes it starts working again after restarting steam / the PC, sometimes it does not.

#### Steps for reproducing this issue:
Sometimes crashes without Steam overlay interaction. Sometimes crashes when I get a message via Steam or an Invite to a lobby. Sometimes just crashes randomly. After it crashes once, it may crash during game start up until I restart Steam or my PC.

Often, but not always. :
1. Start Counter Strike Global Offensive
2. Open the Steam overlay
3. Crash
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12176851/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @lobneroO, this issue is already being tracked at #9586 / #9534 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3172.

Closing as a duplicate.
