### ISSUE TITLE
X windows bugging out, but not when i open steam from terminal

### ISSUE THREAD

**Issue by lenerdv2005** [ValveSoftware/steam-for-linux#9917]
* Steam client version: 1:1.0.0.74-1ubuntu2 (at least this is printed by `apt show steam`)
* Distribution: ubuntu 22.04 jammy
* Opted into Steam client beta?: no
* Have you checked for system updates?: everything up to date
* GPU: NV117 / Mesa Intel® HD Graphics 530 (SKL GT2)

#### Please describe your issue in as much detail as possible:
upon opening from the applications tab, steam tries to open a window which barely displays before closing, then waits a few seconds and retries opening another window, in an endless loop. i tried opening it from a terminal and it seems to work fine, but spews 20 or so lines repeating 
`Could not connect to X session manager: None of the authentication protocols specified are supported`
which is obviously the core issue. i just installed steam for the first time, and had trouble with the captcha not working (tried to reset password, went through half a dozen captcha pages, verified, only to be told it wasn't valid and i had to take captcha again; solved by resetting password from browser).

**Comment by kisak-valve** [comment]
Hello @lenerdv2005, this issue is already being tracked at #9383. Closing as a duplicate.
