### ISSUE TITLE
Steamwebhelper crashes when trying to buy dota plus.

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/steam-for-linux#9919]
hi,
Whenever I try buy dota plus through the ingame button a steam window pops up with a frozen loading icon, shorty followed by a crash of the steamwebhelper.

It then opens a random other steam window. So far I have seen a window asking to update an audio driver, the settings menu, an authorize device screen and now one for deinstalling something.

I'm not sure whether there is any logic connected to them, but this feels dangerous.

```
traps: steamwebhelper[10241] general protection fault ip:4b84c8 sp:7ffc99905cc0 error:0 in steamwebhelper[410000+3a9000]
```

#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: No
* Have you checked for system updates?: No
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12195762/steam-logs.tar.gz)

* GPU: Nvidia

#### Steps for reproducing this issue:

1. 
![screen04](https://github.com/ValveSoftware/steam-for-linux/assets/5174562/c6aef567-871c-4fe8-8ea1-c3c76e6d02d3)

2.
![screen05](https://github.com/ValveSoftware/steam-for-linux/assets/5174562/2ce299e7-8fd0-46cc-8c89-c89d91915fd9)

3. 
![screen06](https://github.com/ValveSoftware/steam-for-linux/assets/5174562/f6dbef29-dca8-4625-8d87-a6fcd2a47a8d)

While dota related I assume this is more a steam issue.

**Comment by kisak-valve** [comment]
Hello @Turmfalke2, the third part is already being tracked at #9795.

**Comment by Turmfalke2** [comment]
Ok this is indeed very similar. Don't think it matters whether you buy something cs:go or dota. Would be ok with closing this, just hope the actual issue gets fixed at some point.

The title of the other issue isn't great.

**Comment by Turmfalke2** [comment]
works in the steam beta. Closing this in favour of #9795
