### ISSUE TITLE
Counter Strike on Linux Mint 13 64-bits french displays a message for locales

### ISSUE THREAD

**Issue by Sorcier** [ValveSoftware/steam-for-linux#992]
I installed Counter Strike on Linux Mint 13 x64, it works but i have a message at the boot : 

SetLocale('en_US.UTF-8') failed. Using 'C'.
You may have limited glyph support.
Please install 'en_US.UTF-8' locale.

After the game is launched, lettering are curious

![Capture du 2013-01-28 18:47:22](https://f.cloud.github.com/assets/3408592/104048/d7551096-6975-11e2-9b60-222bb9421a5a.png)

**Comment by BlackHole1** [comment]
thx!

**Comment by LazinessCreator** [comment]
Fix for Fedora: `sudo yum install langpacks-en`
