### ISSUE TITLE
Steam UI main content area stops responding to mouse after being minimized

### ISSUE THREAD

**Issue by dafzor** [ValveSoftware/steam-for-linux#9920]
#### Your system information

* Steam client version: Thu, Jul 27 02:56 UTC -08:00
* Distribution: Manjaro Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12198696/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:

After closing the main steam window to system tray, reopening will have the main content area no longer respond to mouse inputs.

Top bar controls and bottom Add a game and friends will still work but everything else will do nothing when clicked. The last used window control button (minimize, maximize, close) button will display as if it was being hovered.

Maximizing the window or resizing it any way makes the main content area respond to mouse clicks again.

#### Steps for reproducing this issue:

1. Open steam
2. Minimize main window
3. Restore main window

**Comment by dafzor** [comment]
May be related with #6660,

**Comment by kisak-valve** [comment]
Hello @dafzor, this issue is already being tracked at #9375. Closing as a duplicate.
