### ISSUE TITLE
Steam Client becomes multiple windows after leaving it running in the background for few days

### ISSUE THREAD

**Issue by Cookies77777** [ValveSoftware/steam-for-linux#9921]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Ubuntu 22.04 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Later
* GPU: NVIDIA

#### Please describe your issue in as much detail as possible:
I have an issue with the steam client where if I leave my computer on with steam running, after one or two days it spawns multiple windows. I can move them around but not close them unless I exit steam completely. If I close steam completely and restart then its back to normal.
See the screenshot. Did anyone encounter something like this?
If I remember right, it started happening after the big update that unified the client across the devices.

#### Steps for reproducing this issue:

1. Start Steam
2. Keep computer on for few days with steam running in the background
3. Check it once in a while until it happens.
![Screenshot-20230723050745-2560x1440 Steam WTF](https://github.com/ValveSoftware/steam-for-linux/assets/140863615/c8a6355e-3683-4d3c-bd4c-4e0edb538dfe)

**Comment by kisak-valve** [comment]
Hello @Cookies77777, this issue is already being tracked at #9786. Closing as a duplicate.

**Comment by Aldarion77** [comment]
I've detected this behavior on my desktop a few weeks ago. I left it on and in 5 hours, at least 11 windows have opened.
