### ISSUE TITLE
Steam startup became equivalent to starting an old unreliable car after mayor UI update

### ISSUE THREAD

**Issue by panmarco83** [ValveSoftware/steam-for-linux#9922]
#### Your system information

* Steam client version (build number or date): 
* - Steam Version:  1689034492
* - Steam Client Build Date:  Tue, Jul 11 01:59 UTC -08:00
* - Steam Web Build Date:  Mon, Jul 10 19:48 UTC -08:00
* - Steam API Version:  SteamClient020
* Distribution: Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes (Multiple times over the last months)
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12206425/steam-logs.tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
What I expect to happen is that the steam client will start when I click on it's icon or invoke it from a terminal.

What I do NOT expect to happen is being forced to watch htop with 'steam' filter for anything between 1 and 20 (probably more) attempts at starting steam.

* I have completely uninstalled steam from system: sudo pacman -R steam
* I have removed the steam runtime and config folders: rm ~/.local/share/Steam/

#### Steps for reproducing this issue:

1. Open a terminal
2. start htop
3. filter for steam
4. click on steam from menu
5. watch htop and either wait for all the steam processes to stop OR the client to finally start
6. see all the processes die, goto step 4

**Comment by panmarco83** [comment]
today, it took between 20 and 30 atemps

**Comment by panmarco83** [comment]
2023.08.04 12:08 (24h) Gave up at 40 attempts.....

**Comment by panmarco83** [comment]
### Attempting a reinstall with old config folder
* Rename `~/.local/share/Steam/` to `~/.local/share/Steam-OLD/`
* copy `~/.local/share/Steam-OLD/config/` into `~/.local/share/Steam/`
* delete `~/.local/share/Steam/config/htmlcache/`
* try starting up
* [ fails ]

### Attempting Attempting a reinstall with a blank slate
* (Still preserving `~/.local/share/Steam-OLD/`) Delete `~/.local/share/Steam`
* Still [ fails ]

ran the last attempt from a terminal:
```
src/steamUI/steamuisharedjscontroller.cpp (540) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (540) : Fatal assert; application exiting
08/04 16:13:07 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(2666411)
```
this outputs in the terminal just before it dumps out...

**Comment by kisak-valve** [comment]
`src/steamUI/steamuisharedjscontroller.cpp (540) : Failed creating offscreen shared JS context`

Hello @panmarco83, based on that hint, can you check if #9588 is relevant to your system?

**Comment by panmarco83** [comment]
Steam finally started up today after a 20 minutes of monitoring processes and launching.
This is ridicules, what the hell has been done to the client since the large GUI/UI update that has it THIS unstable at START ?!
I am not going to apologize for feeling like the (almost 400) games I have payed for; are being held hostage to failed innovation!
The previous version of the GUI/UI client was just fine, it did what it was supposed to do, what was so deadly important that it was necessary to make it worse ?

**Comment by panmarco83** [comment]
@kisak-valve, Huh, I uninstalled `xdg-desktop-portal-gnome` after reading through your message and reading the issue you suggested.
While reading through, I found something I wanted to try, the `-vgui` launch option, so I tried to launch steam normally first and it looks like it is starting properly now.
