### ISSUE TITLE
Cannot select higher or same level directories than the installation for library folders.

### ISSUE THREAD

**Issue by DestinedLight** [ValveSoftware/steam-for-linux#9924]
#### Your system information

* Steam client version (build number or date):  Steam latest (as of 7/29/2023)
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: Not Applicable(?)
* GPU: Nvidia/Intel/AMD |  AMD RX6800

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Issue: Steam is not allowing for selection of library directory outside of it's install directory (ex. if installed in .debian-installation, this will be the only available directory aswell as any below it)

Expected: Steam will allow a full browse of the directories attached to the system, regardless of position, as long as the user running steam has access
What happened: Steam will not allow user to browse up directories, only down deeper into the installation of steam, will not follow symbolic links.

#### Steps for reproducing this issue:

1.  Open Steam
2. Go to settings -> Storage -> Add
3. 

#### Attached Files:
![DirectoryIssue](https://github.com/ValveSoftware/steam-for-linux/assets/85512355/66ab899b-bcbb-478c-9a62-a014347243e5)
![Debian-installation](https://github.com/ValveSoftware/steam-for-linux/assets/85512355/d2172eb2-a05d-4896-b524-f6fbbfe8d070)

**Comment by kisak-valve** [comment]
Hello @DestinedLight, this issue is already being tracked at #9797. Closing as a duplicate.
