### ISSUE TITLE
Many "pop up menus" and more are not functioning in Xmonad

### ISSUE THREAD

**Issue by aazvf** [ValveSoftware/steam-for-linux#9927]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Ubuntu 20.04 with Xmonad
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12209181/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:

The steam linux client is getting progressively worse and worse, "pop up menus" are not showing, or showing on the wrong screen, or flashing for a brief second then dissapearing, this is a consistent problem with many "pop up menus", more and more are becoming unusable. Here are a list of some problems I am facing which seem to have been introduced over the last few months

Expect, log into friends and see friend list
Actual: Upon log in, no friend list, I must go 'offline' then 'online' for friends list to show

Expect: Clicking nav links like "steam", "view", "friends" should open the menu
Actual: Navigation popups flash for a brief second then close again, or don't open, or get stuck open.

Expect: In friend list, clicking the arrow next to friend should show a menu like "send a message", "view profile" etc
Actual: Clicking on a friend shows no menu

Expect: Unfocusing steam should "release" or "ungrab" my keyboard
Actual: Sometimes my keyboard focus gets stuck in the steam client, capturing all my keystrokes even though my focus is now on another window. Like when I type it types into the steam friends 'search' box instead of the other application I am trying to type in.

I have tried using steam beta, and the legacy menu option but it did not help or acted worse, I only wish that some testing be done on alternative desktop environment / window managers like Xmonad and I fully understand that this may be a result of my unusual configuration.

#### Steps for reproducing this issue:

1. Use steam client in Xmonad
2. Put window in 'floating' mode
3. Click navigation menus and menus in friends

**Comment by kisak-valve** [comment]
Hello @aazvf, this issue is already being tracked at #9790 / #9376. Closing as a duplicate.

"Fixed main client window taking focus from other Steam windows when navigation menus are hovered." in the [2023-07-26](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3662040707257579654) Steam client beta update might have helped with this.
