### ISSUE TITLE
File picker does not open when trying to upload an artwork

### ISSUE THREAD

**Issue by NoXPhasma** [ValveSoftware/steam-for-linux#9929]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* GPU: AMD
* Steam Runtime System Info: https://gist.github.com/NoXPhasma/a920388be848abd5ba3fc950e789e30b

#### Please describe your issue in as much detail as possible:
When trying to upload an artwork on the community page of a game, the file picker won't open. No issue is reported when running Steam on the terminal.

#### Steps for reproducing this issue:

1. Go to an Artwork section of game's community page
2. Go to "Upload your artwork"
3. Click on the file picker

**Comment by kisak-valve** [comment]
Hello @NoXPhasma, Steam should be calling xdg-desktop-portal to open a user-selected file dialog box, but the Arch packaging does not currently require the relevant dependency to be installed with Steam. This is a distro packaging issue being tracked at https://bugs.archlinux.org/task/78625. Separately, https://github.com/ValveSoftware/steam-for-linux/issues/9584 is tracking the missing fallback path.

Install the `xdg-desktop-portal` system package and the corresponding backend of your choice. (https://wiki.archlinux.org/title/XDG_Desktop_Portal)

Closing as a duplicate.

**Comment by NoXPhasma** [comment]
I do have `xdg-desktop-portal` and the proper backend installed and running. It still does not open the file dialog, though.

**Comment by kisak-valve** [comment]
Please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by NoXPhasma** [comment]
I've updated the initial post and added the Runtime info. I'm using the backends `xdg-desktop-portal-gtk` and `xdg-desktop-portal-xapp`. I've also tried to only use one of each, with the same outcome.

**Comment by kisak-valve** [comment]
Thanks, we'll need someone with more insight to take a look. At a glance, the linked wiki article notes that `xdg-desktop-portal-xapp` doesn't provide a file chooser backend, but I'd expect for `xdg-desktop-portal-gtk` to cover that.

**Comment by NoXPhasma** [comment]
I got it fixed, it was an issue on my end by having `xdg-document-portal` service masked.
