### ISSUE TITLE
No steam UI is visible after nvidia 535.54.03 update

### ISSUE THREAD

**Issue by Syjgin** [ValveSoftware/steam-for-linux#9931]
#### Your system information

* Steam client version: built Jul 10 2023 23:58:24
* Distribution: KDE Neon user edition (Ubuntu-based) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: attached
* GPU: Nvidia, driver version: 535.54.03

Steam UI is no more visible, but I still able to launch recent games via tray menu.
After launching steam there are same repeated messages in console:
`steamwebhelper.sh[15455]: Runtime for steamwebhelper: defaulting to /home/chikatori/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[15455]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
BuildCompleteAppOverviewChange: 216 apps
RegisterForAppOverview 1: 4ms
RegisterForAppOverview 2: 4ms
`
Issue is started after graphics driver update, but I need this update for my work.
[logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12212578/logs.tar.gz)

**Comment by sakralbar** [comment]
Some issue with ubuntu 22.04 and nvidia 535 driver:

```
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[44608]: Runtime for steamwebhelper: defaulting to /home/eugene/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[44608]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Could not connect to X session manager: None of the authentication protocols specified are supported
CAppInfoCacheReadFromDiskThread took 20 milliseconds to initialize
Failed to init SteamVR because it isn't installed
local (potentially out of sync) copy of roaming config loaded - 1412 bytes.
Fossilize INFO: Setting autogroup scheduling.
roaming config store loaded successfully - 1412 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 1ms
Could not connect to X session manager: None of the authentication protocols specified are supported
```

**Comment by kisak-valve** [comment]
Hello @Syjgin, the NVIDIA 535.54.03 driver release is known to have a defect in the driver's on-disk shader cache. Update your video driver to 535.86.05 when it comes available via your distro's normal update process.

Until then, you can try to workaround this issue by manually moving/removing NVIDIA's on-disk shader cache. See comments in #9692 / #9764 related to GLCache for examples.

Closing in favor of the older issue reports.
