### ISSUE TITLE
xfce4/Xubuntu untitled windows on display reconnect

### ISSUE THREAD

**Issue by caphene** [ValveSoftware/steam-for-linux#9934]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Xubuntu 22.04.2 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Don't have logs to show yet, will update issue with logs as soon as I can.
* GPU: AMD

#### Please describe your issue in as much detail as possible:
I have a KVM that I use to switch between two machines,  when I start steam the windows show up as expected with the appropriate titles: 
```
Steam
Friends List
{friend name} + 2 Chats
etc.
```

When I switch to my other machine and switch back, I find that steam has now gone from 2-3  windows to ~10 that are all titled "untitled window" and the UI of the main steam window (for example) doesn't work anymore. I have to scroll through the untitled windows to find the corresponding menu items. 

#### Steps for reproducing this issue:

1. Start steam
2. Disconnect display? / Switch KVM to other machine
3. Reconnect display / Switch KVM back to machine with steam

Note: I can't intentionally reproduce it, so I'm not entirely sure what triggers it but I've outlined the behavior that seems to lead to it. I'll produce screenshots to further illustrate as soon as I can. Restarting steam does return the windows to normal until it happens again.

**Comment by kisak-valve** [comment]
Hello @caphene, this issue is already being tracked at #9786. Closing as a duplicate.
