### ISSUE TITLE
Unable to uninstall games from Steam Client (Pop OS 22/Ubuntu 22) 

### ISSUE THREAD

**Issue by ngrogg** [ValveSoftware/steam-for-linux#9936]
-- Summary Of Issue --
I'm unable to uninstall games from the normal Steam client view. I tried both by right clicking the game and selecting "Manage > Uninstall" and from the gear on the installed game page. I confirm I can remove games from the Big Picture mode without issue. I checked under my Steam Settings and I am not enrolled in any Client Beta Participation. I also checked for updates via apt and from within steam itself. 

-- Steps to replicate --
From steam client, right click an installed game, navigate to 'manage > uninstall', and left click. 
Menu disappears but uninstall pop-up doesn't appear. 

-- Debug Attempts --
1. Rebooted computer.
2. Re-installed Steam.
3. Checked my disk health to make sure I don't have a bad partition that would prevent disk reads/writes.
4. Tried in Big Picture Mode to further rule out something on my disk vs something in Steam client.
5. Tried launching steam from BASH prompt to see if there were error messages when attempting to remove a game. There were no error messages.

-- Steam Info --
Steam Client 'About Steam' info:
Steam Version: 1689034492
Steam Client Build Date: Mon, Jul 10 1:59 PM UTC -10:00
Steam Web Build Date: Mon, Jul 10 7:48 AM UTC -10:00
Steam API Version: SteamClient020

-- Computer Info --
OS Info: Pop OS 22 (Ubuntu 22) 
CPU Info: AMD Ryzen 7 7700x 8-core processor
GPU Info: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M]

-- Screenshots --
![Screenshot from 2023-07-30 20-27-22](https://github.com/ValveSoftware/steam-for-linux/assets/54596458/03b21222-5d6e-4621-9fff-221730ba5615)
![Screenshot from 2023-07-30 20-30-44](https://github.com/ValveSoftware/steam-for-linux/assets/54596458/9d93e8dd-bd3e-4600-8830-244dfdc51f1a)

-- Video --
I forgot to enable the cursor in the screen recording. 
[Screencast from 08-01-2023 02:37:29 AM.webm](https://github.com/ValveSoftware/steam-for-linux/assets/54596458/51d4fdde-c6b3-425d-8c1e-5f2f6e04c1d6)

**Comment by kisak-valve** [comment]
Hello @ngrogg, your recording is showing the UI element behind the dropdown menu getting selected. This issue is already being tracked at #9273.

You might be able to workaround this issue by holding the control key while selecting the dropdown menu.

Closing as a duplicate.
