### ISSUE TITLE
Friend list right click menu is unusable

### ISSUE THREAD

**Issue by Zorrototo** [ValveSoftware/steam-for-linux#9937]
#### Your system information

* Steam client version (build number or date): 
* Distribution:  Manjaro KDE
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12231860/steam-logs.tar.gz)
* GPU: Nvidia GTX 1060
* System info: [Gist](https://gist.github.com/Zorrototo/803aa63ccbd2e8a06559d1494c0b4acb)

#### Please describe your issue in as much detail as possible:
When you right click a friend in the friend list, you can not use the menu that opens, because this menu crashes all the time, you have to be very persistent and very quick if you want to click on anything in this menu in friend list.

Here is a video to show the problem, you can see how frustrating it is:  https://www.youtube.com/watch?v=JTKE3SvoqJM
The logs attached above are the logs from that session in the video, I started Steam, took the video, closed Steam.

#### Steps for reproducing this issue:

1. Right click a friend in friend list
2. Try to click on something in the menu that opens
3. Notice the menu crashes and you have to try again

**Comment by kisak-valve** [comment]
Hello @Zorrototo, this issue is already being tracked at #9684. Opt into Steam's client beta and retest.

Closing as a duplicate.

**Comment by Zorrototo** [comment]
Sorry, I tried to search but didn't find.
