### ISSUE TITLE
Steam is downloading Windows version for a native game.

### ISSUE THREAD

**Issue by mmbossoni** [ValveSoftware/steam-for-linux#9947]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12255217/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Dead Cells is downloading windows version even though I don't have any compatibility tool set to it.
If I set compatibility tool to proton it won't download anything.
If I uncheck it, it will download the linux version.
My workaround right now is set it as proton and then uncheck the checkbox
After that (downloading the linux version) if I close steam client and open it again, it will show Dead Cells with an "update available" and try to download Windows version again

#### Steps for reproducing this issue:

1.For me it is just a matter of restart steam client, but I have no idea why/how it get on that state

**Comment by kisak-valve** [comment]
Hello @mmbossoni, this issue is already being tracked at #9875. Closing as a duplicate.
