### ISSUE TITLE
TF2 pulling hl2.exe when hl2.sh is needed to run natively on linux.

### ISSUE THREAD

**Issue by Joshwa** [ValveSoftware/steam-for-linux#9955]
#### Your system information

* Steam client version (build number or date): 1.0.0.76-r1
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12268558/steam-logs.tar.gz)

* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

_expected_
Installing TF2 on Linux would pull the correct executable files, i.e. hl2.sh and hl2_linux

_did_
hl2.exe is pulled, no matter how many times I reinstall, or verify integrity of game files.

#### Steps for reproducing this issue:

1. Install TF2

**Comment by kisak-valve** [comment]
Hello @Joshwa, this issue is already being tracked at #9875. Closing as a duplicate.
