### ISSUE TITLE
CS:GO crashes whenever anything related to the overlay happens(pressing Shift+Tab, getting an achievement, etc.)

### ISSUE THREAD

**Issue by AkiraMorilas** [ValveSoftware/steam-for-linux#9961]
#### Your system information

* Steam client version (build number or date): 
Steam Client Build Date:  Fri, Jul 28 8:44 PM UTC -08:00
Steam Web Build Date:  Sat, Jul 29 12:21 AM UTC -08:00
* Distribution (e.g. Ubuntu): Linux Mint 21.1 Cinnamon
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12273639/steam-logs.tar.gz)
* GPU: AMD(previously Nvidia, could be relevant, see below)

#### Please describe your issue in as much detail as possible:

As per title, CS:GO crashes whenever anything related to the overlay happens(pressing Shift+Tab, getting an achievement, etc.). I've tested other games and none of them crash. I haven't touched Steam in a few months, and I changed my GPU in the meantime(GTX 750Ti → RX 6600). I've tried reinstalling the game and I still have this issue.

#### Steps for reproducing this issue:

1. Launch CS:GO
2. Press Shift+Tab or get an achievement
3. Crash to desktop

**Comment by kisak-valve** [comment]
Hello @AkiraMorilas, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172 / #9586. Closing as a duplicate.
