### ISSUE TITLE
Steam can't add Windows library folder

### ISSUE THREAD

**Issue by StMartin81** [ValveSoftware/steam-for-linux#9963]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution: Archlinux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12285096/steam-logs.tar.gz)

* GPU: AMD RX 6700 XT

#### Please describe your issue in as much detail as possible:
I've wanted to add the Windows Steam library folder to the Linux client. When I try to add the folder I see the following error message on the command line: `Failed system("/mnt/windows/Program Files (x86)/Steam/.steam_exec_test.sh") in execute test: 32256`. The file `.steam_exec_test.sh` doesn't exists in this location and it's also not available anywhere in `~/.local/share/Steam/`.

**Comment by kisak-valve** [comment]
Hello @StMartin81, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, `Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client.` Sharing a Steam library between different OSes is not supported and may have unexpected side effects.

Having written that, `.steam_exec_test.sh` isn't expected to be kept around. It's a very basic check to see if Steam can create an executable file that is usable. Separate from the note above, the error message is telling you that the folder you tried to add is not mounted in a way that allows your regular user run the basic check, and by extension, any games added there later will have trouble. You'll want to look at the file permissions of the folder and the options used when the drive was mounted.

Closing as unsupported in the first note.
