### ISSUE TITLE
Game install path overly simplified.

### ISSUE THREAD

**Issue by ryliejamesthomas** [ValveSoftware/steam-for-linux#9972]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:
* GPU: AMD

#### Please describe your issue in as much detail as possible:

I have my library in three directories, all on the same partition on the same disk.

- Steam's default one: `~/.local/share/Steam`
- One for Linux games: `~/Games/Steam/Linux`
- And one for Windows games: `~/Games/Steam/Windows`

When I go to install a game all three are simply listed as `/home`, so I've had to memorise their order to place games where I want them. This is also reflected in the Settings > Storage window.

It would be useful to show more information in the path.

This issue has existed since the new client released. I don't remember it being a problem before.

| ![screenshot_23-08-09_18-08-57](https://github.com/ValveSoftware/steam-for-linux/assets/25972447/355dfa97-408d-438e-b0e1-6a09f7f424b4) | ![screenshot_23-08-09_18-16-17](https://github.com/ValveSoftware/steam-for-linux/assets/25972447/53f2d283-18cd-4602-9f14-5ec72ce5d25f) |
|-|-|

**Comment by kisak-valve** [comment]
Hello @ryliejamesthomas, this issue is already being tracked at #8653. Since this issue report adds a bit more detail, I've gone ahead and transferred the issue report to https://github.com/ValveSoftware/steam-for-linux/issues/8653#issuecomment-1671163893.

Closing in favor of the older issue report.
