### ISSUE TITLE
Bring back noreactlogin

### ISSUE THREAD

**Issue by Xen0sis** [ValveSoftware/steam-for-linux#9975]
What a nightmare this is..

I got 5 after school clubs running with 10+ computers each..

I have created my own "net-cafe" style launcher, so the kids can't get access to anything else then games i've added in the launcher..

This have worked perfectly for a couple of years now..

I achive this using bat scripts like this:
START C:\"Program Files (x86)"\Steam\Steam.exe -applaunch 730 -silent -login SteamUser SteamPassword -noreactlogin
This will open the game silently so the kids can't get access to the steam library/store and login with our own accouns.

I did also provide a way the kids could login using their own account with this bat script:
START C:\"Program Files (x86)"\Steam\Steam.exe -applaunch 730 -silent -noreactlogin -login *

But it seems you can't use bat scripts with the new crappy login system..

Now i can't login using bat files and have no way to prevent the kids from downloading every game on steam, change account names etc..

So now we are unable to play any steam games anymore.. I assume every net-cafe have this problem now..

**Comment by kisak-valve** [comment]
Hello @Xen0sis, the Linux variant of this issue is already being tracked at #9031. For your Windows specific use case, please give this feedback to [Steam Support](https://help.steampowered.com) for the larger Steam support staff to ponder.

Closing as a duplicate.
