### ISSUE TITLE
Overlay causes to crash games

### ISSUE THREAD

**Issue by NYBACHOK** [ValveSoftware/steam-for-linux#9983]
#### Your system information

* Steam client version: 1690583737 (friday, 28 july 18:44 UTC -08:00)
* Distribution: EndeavourOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12327771/logs.tar.gz)
* GPU: Nvidia Driver Version: 535.98 

#### Please describe your issue in as much detail as possible:
When I try to open overlay in games it causes them to crash.

#### Steps for reproducing this issue:

1.  Lauch game
2. Open overlay

**Comment by kisak-valve** [comment]
Hello @NYBACHOK, this issue is already being tracked at #9586 / #9534. Closing as a duplicate.
