### ISSUE TITLE
steamwebhelper crash loop when launching flatpak Steam in Fedora 38

### ISSUE THREAD

**Issue by leodip** [ValveSoftware/steam-for-linux#9984]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Fedora 38
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12327878/steam-logs.tar.gz)
* GPU: AMD RX6600
* Desktop environment: Gnome 44.3 (Wayland)

#### Please describe your issue in as much detail as possible:
I have installed Steam via flatpak. When I hit the super key in Gnome, type Steam and click the Steam icon to launch it, I can see the Steam application loading for a moment ("Waiting for network...", "Logging in" and "Loading user data..."), and before I can see the Store, my list of games, etc., it crashes with an error message at the top of Gnome:

```
Oops!
We're sorry, it looks like "steamwebhelper" crashed. Please contact the developer if you want to report the issue.
```

That happens in a loop. Every 10 seconds or so, it tries to re-launch it, and crashes again.

I don't get that error if I right click the Steam icon and choose "Library" for example. In that case it launches Steam just fine. But if I just do a normal (default) click on the Steam icon, I get the crash loop.

#### Steps for reproducing this issue:

1. Install Steam via flatpak in Fedora 38
2. Hit the super key, type Steam and click to launch Steam 

Some more logs that I can see when I look in the terminal:

```
INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
INFO:root:Will set XDG dirs prefix to /home/leodip/.var/app/com.valvesoftware.Steam
DEBUG:root:Checking input devices permissions
INFO:root:Overriding TZ to Europe/Lisbon
steam.sh[2]: Running Steam on org.freedesktop.platform 22.08 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
setup.sh[77]: Steam runtime environment up-to-date!
steam.sh[2]: Steam client's requirements are satisfied
[2023-08-12 17:51:01] Startup - updater built Jul 28 2023 18:44:09
[2023-08-12 17:51:01] Startup - Steam Client launched with: '/home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
08/12 17:51:01 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(149)
[2023-08-12 17:51:01] Loading cached metrics from disk (/home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
[2023-08-12 17:51:01] Using the following download hosts for Public, Realm steamglobal
[2023-08-12 17:51:01] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-08-12 17:51:01] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-08-12 17:51:01] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-08-12 17:51:01] Verifying installation...
[2023-08-12 17:51:01] Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xef8d88f0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xef8d71c0
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[236]: Runtime for steamwebhelper: defaulting to /home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[236]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[236]: CEF sandbox already disabled
CAppInfoCacheReadFromDiskThread took 9 milliseconds to initialize
BRefreshApplicationsInLibrary 1: 0ms
steamwebhelper.sh[633]: Runtime for steamwebhelper: defaulting to /home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[633]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[633]: CEF sandbox already disabled
BuildCompleteAppOverviewChange: 177 apps
RegisterForAppOverview 1: 2ms
RegisterForAppOverview 2: 2ms
steamwebhelper.sh[908]: Runtime for steamwebhelper: defaulting to /home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[908]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[908]: CEF sandbox already disabled
BuildCompleteAppOverviewChange: 177 apps
RegisterForAppOverview 1: 1ms
RegisterForAppOverview 2: 1ms
steamwebhelper.sh[1209]: Runtime for steamwebhelper: defaulting to /home/leodip/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[1209]: Running under Flatpak, disabling sandbox
steamwebhelper.sh[1209]: CEF sandbox already disabled
BuildCompleteAppOverviewChange: 177 apps
RegisterForAppOverview 1: 2ms
RegisterForAppOverview 2: 2ms


```

**Comment by kisak-valve** [comment]
Hello @leodip, you've described #9383. If you completely close steam, then run `steam` (or the flatpak equivalent) from a terminal, does that have an effect?

**Comment by leodip** [comment]
> Hello @leodip, you've described #9383. If you completely close steam, then run `steam` (or the flatpak equivalent) from a terminal, does that have an effect?

Thanks for your reply. Ok... I hadn't realized it was the same. 

So yes this command works fine:

`/usr/bin/flatpak run com.valvesoftware.Steam`

This works too:

`env DRI_PRIME=0 /usr/bin/flatpak run com.valvesoftware.Steam`

This one doesn't work (I get the crash loop):

`env DRI_PRIME=1 /usr/bin/flatpak run com.valvesoftware.Steam`

**Comment by kisak-valve** [comment]
Thanks for checking, closing in favor of the older issue report.
