### ISSUE TITLE
Missing translation in the 'In game' settings panel

### ISSUE THREAD

**Issue by mbcraft** [ValveSoftware/steam-for-linux#9987]
#### Your system information

* Steam client version (build number or date):  

Versione di Steam:  1690583737
Data della build del client di Steam:  ven 28 lug 20:44 UTC -08:00
Data della build Web di Steam:  sab 29 lug 0:21 UTC -08:00
Versione API di Steam:  SteamClient020

* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12341637/steam-logs.tar.gz)`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
In the 'Settings' panel, in the submenu 'In game', the 'Scale Steam Overlay text and icons to match monitor settings' element is not localized (I'm using Steam with Italian language).

#### Steps for reproducing this issue:

1. Open the settings panel
2. Choose the 'In game' submenu
3. There you can find the missing translation

**Comment by TTimo** [comment]
Thanks - this should be already fixed in the beta client if you can check.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-09-11](https://steamcommunity.com/app/593110/eventcomments/3816293260298728238/) Steam client update.
