### ISSUE TITLE
Steam (system package) ask me sudo password every time I launch it

### ISSUE THREAD

**Issue by Nekuzar** [ValveSoftware/steam-for-linux#9997]
OS: PikaOS 23.04 x86_64 (based on Ubuntu 23.04)
Kernel: 6.3.0-pikaos 
DE: GNOME 44.3 using X11
CPU: AMD Ryzen 5 4500 
GPU: NVIDIA GeForce GTX 1660 
                                                   
* Steam client version (build number or date): 1690583737

* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
*Log opening Steam in the terminal: 
steam.sh[8615]: Running Steam on pikaos 23.04 64-bit
steam.sh[8615]: STEAM_RUNTIME is enabled automatically
setup.sh[8710]: Steam runtime environment up-to-date!
steam.sh[8615]: Steam client's requirements are satisfied
[2023-08-17 19:40:34] Startup - updater built Jul 28 2023 18:44:09
[2023-08-17 19:40:34] Startup - Steam Client launched with: '/home/sebas/.local/share/Steam/ubuntu12_32/steam'
08/17 19:40:34 Init: Installing breakpad exception handler for appid(steam)/version(1690583737)/tid(8795)
[2023-08-17 19:40:34] Loading cached metrics from disk (/home/sebas/.local/share/Steam/package/steam_client_metrics.bin)
[2023-08-17 19:40:34] Using the following download hosts for Public, Realm steamglobal
[2023-08-17 19:40:34] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-08-17 19:40:34] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-08-17 19:40:34] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-08-17 19:40:34] Verificando instalación...
[2023-08-17 19:40:34] Verification complete
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf08849c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf08831f0
GetWin32Stats: display was not open yet, good
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[8809]: Runtime for steamwebhelper: defaulting to /home/sebas/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[8809]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 42 milliseconds to initialize
BRefreshApplicationsInLibrary 1: 52ms
BuildCompleteAppOverviewChange: 449 apps
RegisterForAppOverview 1: 15ms
RegisterForAppOverview 2: 15ms

It opens a teminal asking me sudo password, I can use password or only close the window and Steam opens normally. If Steam is in system tray it ask me password again when click to open it from main menu. I have this problem since monday. Steam flatpak doesnt have this problem, but wanted to ask first because I prefer the system package one.
#### Steps for reproducing this issue:

1. Launch Steam from terminal or main menu.
2. It opens a terminal asking sudo password.
3. I can use Steam normally but dont want it ask me password everytime I launch it.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/101688283/60f2294b-3bd6-418b-9637-e5758eadc11a)

**Comment by smcv** [comment]
If you run this in a terminal, what output do you get?

```
LC_ALL=C.utf8 STEAM_LAUNCHER_VERBOSE=1 steamdeps ~/.steam/root/steamdeps.txt
```

**Comment by Nekuzar** [comment]
It opens a second terminal asking sudo password, entering password or closing the window results in nothing, dont get output. 

this is steamdeps.txt:

# This is a package dependency manifest used by steamdeps

# This should be set to the version of the Steam runtime that this program
# is built with.
# 
# Available values are:
#	1	- Ubuntu 12.04 LTS
#
STEAM_RUNTIME=1
 
# This should be set to the version of the dependency file format
#
# The file can contain lines starting with #, blank lines and dependencies
# A dependency line consists of a package name for the current runtime,
# along with optional architecture or version requirements using the 
# Debian package syntax:
#   http://www.debian.org/doc/debian-policy/ch-relationships.html
#
STEAM_DEPENDENCY_VERSION=1

# These are non-arch specific dependencies
curl
python-apt
xterm | gnome-terminal
xz-utils
zenity

# These are i386 dependencies for Steam itself
libgl1-mesa-dri:i386
libgl1-mesa-glx:i386
libc6:i386

**Comment by smcv** [comment]
> It opens a second terminal asking sudo password

Do you not get something logged in the original terminal before that happens?

**Comment by Nekuzar** [comment]
Nothing
![image](https://github.com/ValveSoftware/steam-for-linux/assets/101688283/512a0a42-f1a4-4308-9fbb-43b24511aca6)

**Comment by Nekuzar** [comment]
Solved in a OS update, Steam now opens without ask sudo password.
