### ISSUE TITLE
Dropdown Menus can sometimes be clicked through.

### ISSUE THREAD

**Issue by Johnathan-Burns** [ValveSoftware/steam-for-linux#9998]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Debian 12
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12381714/steam-logs.tar.gz)
* GPU: Nvidia (Driver version 525.125.06)

#### Please describe your issue in as much detail as possible:
Attempting to interact with some dropdown menus instead interacts with whatever element is underneath the list.
See attached/embedded images for examples of menus that exhibit this behavior on my system.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/3654304/49c4a7ed-3493-46b8-8a72-3eba34e11dad)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/3654304/6918f116-be46-47e4-9507-039a9536c261)

#### Steps for reproducing this issue:

1. Open Steam Client to Library page.
2. Add a new shelf.
3. Try to use the "Choose a Shelf" dropdown menu.
4. "Delete this shelf" will send you to the game under the menu, for example.

or

1. Open Steam Client and navigate  to the Community Workshop for a game.
2. Choose any tag to go to that tag's page.
3. Try to select something from the "Over time period" dropdown menu.
4. Most of these options are over the third community workshop item, and selecting them will instead send you to that item's page.

**Comment by kisak-valve** [comment]
Hello @Johnathan-Burns, this issue is already being tracked at #9273. Feel free to add your findings to the older issue report.

Closing as a duplicate.
