### ISSUE TITLE
Steam windows can't be opened within CS GO, it crashes the game

### ISSUE THREAD

**Issue by marcT21** [ValveSoftware/steam-for-linux#9999]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Mint
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: in attachment + (tail -f *.log > recording.allLog.log during the reproducing)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
Since the new Steam UI 
When I try to reach a steam window within CS GO, CS GO crash.

#### Steps for reproducing this issue:

1. Open CS GO
2. Open Inventory
3. Click on one box to purchase it
4. CS GO is stuck for a while and close

6. This behavior is the same if I Click on a player profile within CS GO

[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12385518/steam-logs.tar.gz)
[recording.allLog.log](https://github.com/ValveSoftware/steam-for-linux/files/12385520/recording.allLog.log)

**Comment by kisak-valve** [comment]
Hello @marcT21, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3172 / #9586. Closing as a duplicate.

**Comment by marcT21** [comment]
thank you @kisak-valve , yes, we are a lot as I can see! 

The bug is not blocking but very annoying : a player could stuck my game by inviting me; we can't add a player as friend; I can't purchase items in the game...

Could you please give us more feedback?
- In term of **fix**: is it planned ? target date? need to wait CS2?
- In term of **workaround**: should we use an other driver / use the old UI/... ? 

Thank you
Regards

**Comment by kisak-valve** [comment]
Friendly reminder that I'm a moderator and not a Valve developer myself. Unfortunately I can't give any information regarding when that issue will be resolved.

As for a workaround, I've read that some people had success switching Steam to Big Picture mode so that the Big Picture variant of the Steam overlay is used instead of the desktop variant which is having trouble.
